{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1493}{1547}Eno tamo sam ga naöao.
{1549}{1595}Hajde da ga uzmemo.
{1808}{1845}Vidiö? Tamo je.
{1847}{1942}- Ne zajebavaj se sa tim brodom.|- To nije niËiji C.J .
{1944}{2039}- Kako to da niste u ökoli?|- Nema ökole leti, glupaku.
{2041}{2088}Ne nazivaj me tako debeljane.
{2089}{2147}- Hajde sada ostavite brod.|- To je sada naö brod.
{2149}{2205}Video sam Ëoveka da ga stavlja tamo.
{2207}{2239}On sada nije tu.
{2241}{2280}Ko pronadje njegovo...
{2282}{2325}
{2418}{2458}Sranje.
{3340}{3399}Ovde su.
{3401}{3453}Bilo je jebeno vreme.
{3455}{3545}Sve je sredjeno. Freebo je unutra. Bouton|i ja idemo stepenicama.
{3547}{3599}- Joö neko, Toots?|- Devojka sa njim.
{3601}{3657}Devojka. To je dobro.|Tako je laköe.
{3658}{3735}- To je dobro. Ricky je rekao da je to sve.|- I ti verujeö svom douönoku?
{3737}{3810}- Hajde da se predstavimo.|- Imaö li nalog?
{3812}{3899}- äta? Trebalo je da ga nabaviö.|- Trebalo je da nabaviö nalog.
{3921}{3952}Jesi li Ëuo to?
{3993}{4036}»uo sam da neko zove upomoÊ.
{4074}{4126}- Zar ti nisi Ëuo?|- Sranje.
{4674}{4734}Nisi mi rekao da ima i |dece unutra.
{4736}{4800}Nisi mi dao öansu.
{4802}{4850}HoÊemo li da upadamo ili ne?
{4902}{4938}Ajde.
{4997}{5024}Policija! Mirno!
{5026}{5079}Pogreöna soba! Pogreöna soba!
{5108}{5173}- Policija! Bez mrdanja!|- Oh, Sranje!
{5175}{5217}Prazno! Toots!
{5335}{5367}Ustaj!
{5455}{5538}Ne budi glup, Freebo.|Ostani gde si.
{5539}{5588}»uo si damu.|Samo polako.
{5660}{5720}Smrdi na govna ovde.
{5721}{5782}Molim vas nemojte me povrediti.|Nisam niöta uradila.
{6092}{6174}Jesi li ovo traûio,|govno jedno?
{6176}{6206}Rembrandt.
{6424}{6455}Stani tamo!
{7174}{7223}Ne mogu da verujem|öupci!
{7224}{7291}- Nismo imali izbora.|- PoËeli su da pucaju od nekuda.
{7293}{7343}Posmatrali smo Freeboa|6 meseci...
{7345}{7444}a vi öupci ste upali tamo|kao u neki öou loöih policajaca.
{7445}{7520}- Moûda niste trebali da nas pustite.|- Ne moram tebi da se pravdam zdepasti, Macy.
{7521}{7614}Niste trebali ni da budete tamo.|Niste imali ni nalog ni razloga.
{7616}{7678}- Vi niste bili tamo, Kenner.|- U pravu je,Jay.
{7680}{7755}To je sranje.On ima istoriju|zajeba celu milju dugaËku.
{7757}{7827}- Zaöto drûiö ovog seronju ovde...|- Ne moram da trpim ovo sranje!
{7949}{7998}Muka mi je da me stalno riba.
{7999}{8064}Ovo je taËno ono öto se desilo|Tigeru, veliki detektive.
{8066}{8128}Monty, ako ga ne drûiö podalje od mene|povrediÊu ga.
{8130}{8235}Eto zaöto ti nemaö partnera.|Ne moûeö da radiö kao kauboj.
{8237}{8324}Sada nadji stenu|i skloni se unutra neko vreme.
{8326}{8402}- äta, skinut sam sa sluËaja Martinez ?|- Pusti da drugi to srede.
{8404}{8522}Joö jedan sluËaj se pojavio jutros.|Probaj taj da ne usereö?
{8660}{8714}Hey, Bass. Kako je?
{8716}{8783}- Hey, Rem. Kako je?|- U redu.
{8805}{8843}äta mu se desilo?
{8862}{8967}On i neki njegovi|su gadjali pacove sa .357.
{8969}{9074}Ovaj glupak je zajebao stvar kada je|napunio cevku blatom dok je jurio okolo.
{9075}{9138}Povukao je obaraË,|i razneo se.
{9140}{9175}Dodjavola!
{9211}{9284}Evo je ruka koju su klinci naöli|u Taylor Pondu.
{9286}{9317}éenska.
{9319}{9350}Imaö li starost?
{9352}{9390}Recimo, 20.
{9392}{9425}- Otisci?|- Dobri.
{9427}{9499}Bila je tamo par dana.|Poslao sam ih.
{9501}{9570}I nosila je prsten.|Vidiö otisak.
{9587}{9655}Oh, Da.|Udata misliö?
{9657}{9698}Moûda.
{9918}{9983}Koko.Johnnie Walker Red.
{10257}{10302}Ko je nova igraËica?
{10303}{10362}Pada te[ko na oËi, huh?
{10403}{10448}»uo sam za tebe i Kennera.
{10482}{10585}- Nadao sam se da Êeö da ga zapucaö.|- Mislim da mi nije prirasao srcu.
{10587}{10638}Kladim se da se usrao u gaÊe
{10662}{10687}Hvala.
{10689}{10748}Tina, koliko bi me koötalo|da ti udjem u gaÊice?
{10750}{10814}Malo öanse. VeÊ imam tamo|jedan öupak.
{10954}{11056}Pa, za vas momci da uhvatite|Martineza, sa ili bez mene.
{11058}{11140}Zajebi to ËoveËe.|Ovde smo zbog dugih nogu i velikih sisa.
{11142}{11173}Ja sam za to.
{11202}{11263}Usput, kako je sa Beck?
{11291}{11344}- Ne bih znao.|- Da.
{11346}{11388}To nije ono öto je Toots rekao.
{11416}{11494}- Mislim da ima ûelju za tobom.|- Sanjaö.
{11496}{11594}- Ne, biÊete divan par.|- Ovo bih rekao o njoj.
{11595}{11659}Kada se zasere,|ona reöava sa 9 milimetara.
{11661}{11746}Svi znaju da ti se digne|u pucnjavi.
{11748}{11818}Pitam se da li se i Beck |ovlaûi oko gaÊica.
{11837}{11880}äta je tako smeöno?
{11882}{11930}Upravo priËamo o|meksiËkoj hrani.
{11932}{11966}Joö jednu turu?
{11988}{12041}- Ne, Hvala.|- Ne
{12043}{12099}- Moram da idem.|- Rem?
{12101}{12193}Pa ja joö nisam spreman.|UzeÊu joö jedno, Koko.
{12195}{12235}Vaûi se.
{12973}{13023}Zatvaramo, Rem.
{14211}{14275}éalim.
{14277}{14327}Samo mi je potrebno malo vremena.
{15162}{15230}- Dobro juto, Anna.|- Izgledaö kao sam pakao.
{15262}{15369}FBI je uporedila delove|sa ruke koju je Bass poslao.
{15371}{15413}Melanie Ann Hains.
{15415}{15484}Otisci su se pojavili u vladinoj aplikaciji.|Izgleda da je radila u gradonaËelnikovoj kancelariji.
{15486}{15543}U redu, Hvala.
{15836}{15915}- Ti si C.J. Crowley?|- Moûda. Ko ste vi?
{15917}{16005}- Samo da vam postavimo par pitanja.|- VeÊ sam rekao sve öto znam.
{16007}{16059}Video sam Ëoveka kako gura|Ëamac u vodu...
{16061}{16123}ali ga nisam dobro|zagledao.
{16125}{16192}- Da li je on vas video?|- Mislim ne.
{16194}{16268}Padao je mrak,|i nije gledao u mom pravcu.
{16269}{16348}U redu, znaËi gurnuo je Ëamac u vodu.|I öta je onda uradio?
{16350}{16386}Niöta.
{16388}{16459}Gledao je okolo neko vreme.|A onda otiöao.
{16460}{16565}Da vas pitam neöto. Da li bi ste|prepoznali tog Ëoveka da ga vidite ponovo?
{16567}{16640}Pa mogao bih,a moûda,|i ne bih.
{17144}{17195}Ovo ubija njenu majku.
{17318}{17379}Ona je bila kraljica...
{17380}{17462}uzoran uËenik,|svaËija princeza.
{17502}{17545}Pa, Mr. Hains...
{17575}{17631}dali je imala momka?
{17632}{17687}Da, ljubav sa koledûa.
{17717}{17771}To se zavröilo kada je poËela da radi|u gradskoj skupötini.
{17788}{17861}Ime mu je Benjamin.|Alan Benjamin.
{17863}{17937}Znamo porodicu.|Oni su veoma dobri ljudi.
{17938}{17988}Da li je nosila prsten?
{17989}{18099}Od belog zlata sa dijamantima|u obliku cveta.
{18100}{18132}Da li ste ga naöli?
{18170}{18205}Ne, gospodine.
{18237}{18312}To je samo mrtvozornik primetio na ruci|da je nosila prsten.
{18417}{18473}Dali je ûivela sama u gradu?
{18475}{18556}Imala je dve cimerke.|Mlade ûene.
{18557}{18646}Sreli smo ih par puta.|Izgledaju u redu.
{18762}{18846}- Da li biste me izvinuli za par minuta?|- Naravno.
{18973}{19049}Ëula sam da su naöli purpurnog zmaja|kako pluta u luci.
{19051}{19100}Izgleda kao Tommy Trangov rad.
{19126}{19154}Zaöto?
{19156}{19244}Zatoö ötoje izboden kao peËeno prase|u saigonskoj palati.
{19246}{19316}Eto zaöto Benny Lee plaÊa velike novce|tim vijetnamskim govnima.
{19318}{19387}Daj da naruËim burger|i pomfrit, Koko.
{19389}{19476}Nema niöta za Melanie Ann Hains.|»ista je ko suza.
{19478}{19563}- »uo sam da je radila za gradonaËelnika.|- Stara dobra öema.
{19565}{19632}PolitiËari i mlade devojke se ne meöaju.
{19633}{19705}PotreöÊeö neke kaveze|gurajuÊi se po gradskoj skupötini.
{19707}{19798}Nije to  Monty mislio kada je rekao|da se primiriö neko vreme.
{19799}{19823}Znam.
{19825}{19857}Razgovarao si sa cimerkama?
{19883}{19956}Otiöao sam do njihovog stana,|ali nisu bile tamo.
{20047}{20106}Idem sada.
{20138}{20176}HoÊeö da podjem sa tobom?
{20208}{20313}Znaö, Rem, ako imaö senku,|manje Êe ti biti vruÊe.
{20408}{20435}Naravno. Zaöto ne?
{20504}{20567}Ne mogu da verujem da se to|dogodilo Melanie.
{20569}{20617}Kako ste saznali?
{20619}{20667}Zvao je njen otac.
{20701}{20754}- Gde je druga cimerka?|- Jennifer?
{20789}{20837}Otiöla je na obalu proöle nedelje.
{20839}{20956}Njen prijatelj ima kuÊu tamo.|Melanie je trebala da se sretne tamo sa njom.
{20958}{21029}- A Melanie je Miss Hains?|- Da.
{21031}{21065}Kada je Miss Hains otiöla?
{21084}{21132}Petak uveËe.
{21170}{21227}- Mogu li vam doneti neöto za piÊe?|- U redu je, Hvala.
{21228}{21289}UzeÊu Ëaöu vode.
{21348}{21397}Koje je ime njenog prijatelja|na obali?
{21419}{21464}Neznam.
{21466}{21512}Da li je cimerka Jennifer|zvala?
{21539}{21591}Malo sam preplaöena.
{21634}{21695}- Miss Calderon--|- Zovite me  Nikki.
{21696}{21746}Nikki.|äta radite?
{21748}{21830}Pa bila sam na ökoli|pa mi je ponestalo novca...
{21832}{21876}pa sam trenutno model.
{21877}{21921}Kakav model?
{21922}{21955}Hotelska modna deöavanja...
{21982}{22070}za biznismene.
{22072}{22153}Znate, bikini, donji veö,|i tako to.
{22154}{22223}Da li imate ideju zaöto se ovo|desilo Miss Hains?
{22247}{22279}Ne.
{22309}{22343}Da li je izlazila sa muökarcima?
{22345}{22409}Izaöla je sa momkom iz|njene kancelarije nekoliko puta.
{22410}{22487}Mislim da se zove Martin.|Nikad mu nisam znala prezime.
{22539}{22636}Da li imate neöto protiv da pogledam|Miss Hainsine liËne stvari?
{22658}{22751}Ne.|PokazaÊu vam njenu sobu
{23004}{23077}Da li ste odavde,|Miss Calderon?
{23117}{23180}Ja sam iz malog grada|za koji nikada niste Ëuli.
{23182}{23209}Probajte me.
{23211}{23256}Medford Lakes, Ohio.
{23300}{23344}Vaöi roditelji joö uvek ûive tamo?
{23346}{23402}Moji roditelji su poginuli|u saobraÊajnoj nesreÊi.
{23404}{23445}Oh. éao mi je.
{23504}{23531}Ko je ovo?
{23533}{23651}Melanienin bivöi deËko sa koledûa.|Dobar momak. Srela sam ga jednom.
{23735}{23802}Da li je Miss Hains ...
{23837}{23868}uzimala lekove za oporavak?
{23909}{23954}Ne koliko znam.
{23956}{24039}Da li zaista mislite|da je ubijena?
{24074}{24105}Sumnjamo na najgore.
{24211}{24264}Na ovoj...
{24266}{24297}Jennifer sa Miss Hains?
{24299}{24347}Da, to je Jen.
{24349}{24391}Koje joj je prezime?
{24392}{24424}Haller.
{24453}{24518}Da. H-A-L-L-E-R.
{24646}{24707}»ime se ona bavi|da bi ûivela?
{24734}{24810}Da, ona radi u |medicinskoj telefonskoj centrali.
{24812}{24870}Koliko dugo radi tamo?
{24872}{24932}Oko 3 meseca.
{25952}{26051}Ako se vaöa cimerka javi ili se pojavi|odmah me pozovite.
{26052}{26113}Ako se setite neËega,|zovite me.
{26160}{26192}Vi ste iz Milea?
{26223}{26262}- Ja?|- Da.
{26281}{26325}Da. Kako znate?
{26327}{26424}Imate malo irskog akcenta.|éivela sam tamo. Gde baö?
{26425}{26468}52. ulica,|prekoputa Harold Parka.
{26565}{26658}Hey, ja neÊu biti u nikakvoj|opasnosti ovde ?
{26698}{26746}Samo dobro zakljuËajte vrata iza nas.
{26748}{26785}U redu?
{26917}{26967}VratiÊeö se?
{26968}{27017}Ne, moram neöto da uradim.
{27018}{27080}Moram da proverim Annine|cimerke i deËka.
{27098}{27121}Hvala.
{27164}{27247}- Ideö li na roötilj u subotu?|- Neznam.
{27249}{27313}- Svi bi ûeleli da te vide.|- Da.
{27332}{27380}Kako bilo.
{27633}{27677}Tigeru!
{27679}{27715}Tamo si?
{27802}{27840}Budi tih!
{27958}{27993}Da li si to ti, Rembrandt?
{28012}{28046}Da.
{28048}{28111}Dugo se nismo videli.
{28113}{28139}Da.
{28141}{28198}Posao znaö.
{28200}{28265}Treba mi pomoÊ partneru.
{28456}{28491}Glatko, huh?
{28493}{28538}Sam sam napravio.
{28540}{28575}Da.
{28577}{28625}Glatko kao bebino dupe.
{28736}{28802}Dakle kakva pomoÊ?
{28803}{28853}Joö uvek imaö veze|unutar gradske skupötine?
{28855}{28914}- äta te interesuje?|- Mlada ûena.
{28916}{28951}Moje omiljeno.
{28953}{29009}Da, tvoje omiljeno.|Mislim da je mrtva.
{29033}{29085}Moje najneomiljenije.
{29109}{29203}Ime joj je  Melanie Hains.|Radila je u gradonaËelnikovoj kancelariji.
{29205}{29285}Jedna ruka joj se pojavila|u Taylor Pondu.
{29286}{29333}Ne mogu niöta da obeÊam.
{29335}{29383}äta god pronadjeö|ceniÊu to.
{29553}{29601}Boze, nedostajeö mi, Tiger.
{29653}{29712}Dobro smo se zezali,|zar ne?
{29730}{29754}Ti si dobro?
{29782}{29840}Da, dobro sam.|Kako si ti?
{29858}{29894}I ti meni nedostajeö.
{31227}{31321}Izvini na smetnji.|Nisam znala gde drugde da odem.
{31385}{31422}Mogu li da udjem?
{31706}{31777}Kako si znala gde ûivim?
{31779}{31836}52. prekoputa Harold Parka.|SeÊaö se?
{31902}{31964}Proverila sam imenik.
{31966}{32027}Ima samo jedan Rembrandt Macy.
{32069}{32105}Sedi.
{32224}{32298}- Zaöto nisi otiöla do stanice?|- Jesam.
{32324}{32355}Nisi bio tamo.
{32357}{32389}Oh.
{32415}{32477}- HoÊeö li piÊe?|- Naravno.
{32605}{32632}Uplaöena sam.
{32651}{32719}- Zbog Ëega?|- Neko stalno zove i spuöta sluöalicu.
{32721}{32767}Mislim da sam praÊena.
{32769}{32814}- Od koga?|- Neznam.
{32816}{32893}Samo oseÊam da kad god izadjem|neko me posmatra.
{32991}{33023}- Izvoli.|- Hvala.
{33211}{33293}Vidite, nisam vam rekla baö |celu istinu ranije.
{33332}{33435}Mislim da su Jen i Melanie upale|u neöto-- neöto loöe.
{33436}{33470}Kao öta?
{33471}{33557}Pre par nedelja|Jen nije doöla kuÊi noÊu...
{33558}{33589}i Melanie se uplaöila.
{33591}{33614}Zbog Ëega?
{33616}{33691}Pitala sam je ali je ona odlepila.|Nije htela da mi kaûe.
{33729}{33833}Melanie nije baö slika prave nevinosti|kako je svi vide.
{33835}{33887}Ona i Jen su se zabavljale.
{33889}{33963}Mislim zabavljale priliËno jako.
{33989}{34063}Da li znaö sa kime su se zabavljale?
{34065}{34157}Mislim sa momcima iz bara,|klubova, gradske skupötine.
{34215}{34263}Da li si me lagala|za lekove?
{34326}{34373}- Na neki naËin.|- Ne zajebavaj me.
{34397}{34467}I ja sam skuvala sa njima|par puta.
{34543}{34648}Pa pretopstavljam da Melanie nije onakva|kakvu je njen otac opisao.
{34650}{34728}Da je samo znao deo toga.
{34819}{34896}Vidite, kasno je.
{34898}{34990}Ima pristojan hotel na 9. aveniji|UzeÊu vam sobu tamo.
{34992}{35070}Sutra moûemo svratiti do vaöeg stana|da pokupite vaöe stvari.
{35071}{35122}Mogu ostati ovde na kauËu.
{35143}{35226}- To nije dobra ideja.|- Ne ûelim da idem u hotel.
{35255}{35312}Ne ûelim da budem sama.
{35313}{35387}ObeÊavam da neÊu napraviti nikakvu|nevolju ovde.
{35436}{35473}Molim vas.
{35519}{35593}U redu, moûeö spavati na kauËu.
{35594}{35637}DoneÊu ti pokrivaË.
{35858}{35931}Imaö Ëiste peökire |ispod lavaboa u kupatilu.
{35958}{35987}Izvinite öto sam lagala, Detective Macy.
{35989}{36085}Jednostavno je izaölo kad sam Ëula za Melanie,|Uplaöila sam se.
{36118}{36167}Nisam znala öta da kaûem.
{36266}{36319}Ime mi je Rem.
{36321}{36350}Zovi me samo Rem.
{39768}{39804}Nikki?
{39924}{39960}Gde si bila?
{39961}{39992}éao mi je.
{39994}{40075}Trebalo mi malo vremena.|Morala sam da odradim neke stvari.
{40077}{40113}Boze, Nedostajala si mi.
{40570}{40610}Nikki?
{40782}{40830}äta, zar sam te probudila?
{40832}{40909}Ne, mislim da sam se uspavao.|Hajde udji.
{41079}{41111}Joö jedan burna noÊ.
{41112}{41148}Da.
{41219}{41272}Mogu li da napravim kafu?
{41274}{41359}Svratila sam da vidim da li|hoÊeö doruËak. Ja Ëastim.
{41361}{41408}Ne, loöe vreme.
{41409}{41470}Hey, imam neke namernice|za doruËak.
{41568}{41629}Nema sumnje da je loöe vreme.
{41688}{41724}Kasnije.
{41957}{42032}Ko su svi ljudi na|ovoj slici sa tobom?
{42034}{42085}Prijatelji sa posla.
{42087}{42164}To je na roötilju|pre godinu dana.
{42193}{42241}Ova ûena,|to je ona od malopre--
{42243}{42298}- Koja je njena priËa?|- Jedna od mojih partnera.
{42321}{42406}Po izrazu njenog lica danas reklo bi se|da ona ûeli da bude viöe od partnera.
{42433}{42488}A öta je sam azijatkinjom?
{42558}{42610}Ime joj je bilo May Lin.
{42612}{42661}"Bilo" ?
{42662}{42694}Umrla je.
{42758}{42798}Bili ste bliski?
{42826}{42874}Radije ne bih o tom.
{42933}{43042}NeÊu biti u moguÊnosti da te odbacim|do stana kao öto smo planirali...
{43044}{43117}pa Êu ti poslati drugog policajca,|Detectiva Boutona--
{43119}{43193}On Êe ti pomoÊi sa odeÊom|i dovesti te do odeljenja.
{43195}{43249}Dakle videÊu te tamo kasnije.|U redu?
{43340}{43382}Hvala.
{43409}{43445}Nema na Ëemu.
{43849}{43901}Lepo, huh?
{43922}{43979}Naöli su ga u kolima.
{43980}{44063}Vodio je sirotiöte.|Misle da je neko dete to uradilo.
{44125}{44189}Nadam se da neÊu zavröiti|na tvom stolu.
{44216}{44274}Oh, dobio sam toksikoliöke rezultate|ruke.
{44276}{44343}Ima alkohola|i tragovi kokaina.
{44366}{44398}Nisam iznenadjen.
{44425}{44482}Naöa mala princeza nije|baö tako Ëista.
{44508}{44557}Nema niöta za|Nikki Calderon.
{44558}{44644}ali njen momak je ispucan jednom--|öala iz bratstva.
{44646}{44740}Bio je u juûnoj americi sa|valdom za zadnjih 6 meseci.
{44742}{44824}Ta Jennifer Haller|je potpuno drugaËija priËa.
{44826}{44900}Tri prijave za proöenje,|jedna presuda.
{44901}{44987}Piöe da je uhapöena jednom|kod Joey Paloa.
{44989}{45025}Ples u krilu.
{45027}{45095}Previöe krila, nedovoljno plesa.
{45162}{45210}Creighton!
{45212}{45276}- Gde si bio?|- Pokuöao sam da se skrijem.
{45277}{45331}Da li se seÊaö ribe |sa imenom Jennifer Haller?
{45333}{45412}- Da li bi trebao ?|- Da. Uhapsio si je.
{45413}{45487}Oh, Da.|SeÊam se te breskvice.
{45488}{45537}Ja i Cronk smo je priveli.
{45539}{45643}Ponudila nam je radnju ako je |ostavimo negde pre nego je privedemo.
{45644}{45733}-Da li si ikada ponovo naleteo na nju?|-Video sam je da igra nekoliko puta nakon toga.
{45735}{45789}- äta je uradila?|- Moûda niöta. Samo je proveravamo.
{45791}{45895}Cronk tvrdi da joj je video sliku|sa nekim politiËarem ili tako neöto.
{45896}{45953}- Kojim politiËarem?|- Ne seÊam se.
{45955}{46036}Da, bilo je u Tribunu|pre neki mesec.
{46063}{46137}- Ko je bio politiËar?|- Bilo ih je par. Na nekoj zabavi.
{46139}{46219}Zar jedan od njih nije bio...
{46221}{46273}gradonaËelnik, zar ne?
{46275}{46329}Mislim da,|sad kad si pomenuo.
{46331}{46367}I taj kongresman Higgins...
{46385}{46429}i neki drugi glavonje.
{46431}{46489}Pre koliko je bio taj Ëlanak?
{46490}{46591}BoûiÊ. Bila je to neka vrsta|prazniËne zabave ili sliËno.
{46612}{46662}Da, znam Jennifer Haller.
{46664}{46750}Ima jedan od onih oseÊaja da tera|novac da progovori iz tvog novËanika.
{46752}{46801}Lisa, donesi joö jednu, molim te.
{46877}{46926}Kada ste je poslednji put videli?
{46927}{47026}Svratila je pre par meseci.|Nisam joj viöe mogao verovati.
{47118}{47183}Jeste li ikada videli ovu devojku sa njom?|Bile su cimerke.
{47185}{47228}Mislim da nisam.
{47272}{47324}- Hvala.|- Hvala, Lisa.
{47405}{47460}Ta ûenska Haller--
{47462}{47545}Da li je ikada iöla sa momcima|iz gradske skupötine?
{47547}{47625}Ne, uglavnom je bila sa|stokbrokerima i kinezima.
{47626}{47690}Volela je öeme sa likovima|iz Hong Konga.
{47692}{47752}Ona je bila upravo ono|öto su oni traûili.
{47780}{47815}äta to znaËi,Joey?
{47817}{47910}Neki od tih malih jebaËa|vole grubo. Znaö na öta mislim.
{47912}{47988}- Ona je bila "S" i " M" ?|- Moûeö da se kladiö u to.
{47990}{48070}Stvar je u tome da nije volela lickanje
{48239}{48287}HoÊeö jednu od njih?
{48324}{48374}Jednu od njih?
{48376}{48412}Ja Ëastim.
{48460}{48524}- Hvala za piÊe,Joey.|- Uvek, Remy.
{48526}{48562}Uvek.
{48943}{48993}To su Melanie i Jen u pozadini.
{49045}{49122}- Ko je lik sa njima?|- Neznam.
{49124}{49159}Oh, Da.
{49160}{49249}Kako je ime momka koji je vidjao|Melanie u gradonaËelnikovoj kancelariji?
{49278}{49311}Martin.
{49398}{49482}- Naöao si to öto si traûio  ?|- Neznam. Moûda.
{49484}{49551}Odötampao sam ovo.|Pogledaj momka u pozadini.
{49553}{49637}Moûda imamo naöeg Martina.|Vidi da li Tribune moûe da ga identifikuje.
{49638}{49683}Kako kaûeö öefe.
{49685}{49721}Hvala.
{49794}{49829}Tiger!
{50072}{50152}- Neko ûivi ovde?|- Da, stari prijatelj. Bivöi policajac.
{50154}{50202}Imaö Ëudne prijatelje.
{50204}{50232}I nove.
{50292}{50356}Ovo je  Nikki.|Nikki, moj prijatelj Tiger Wu.
{50358}{50411}Hi, Tiger.|Drago mi je da sam te upoznala.
{50441}{50533}- Nikki je Melanie Hainina cimerka.|- Sedite, sedite.
{50534}{50570}Hvala.
{50629}{50677}Da li si pronaöao neöto?
{50679}{50710}Devojka izgleda Ëisto.
{50712}{50810}Vidjala se sa nekim likom odande|par puta.
{50812}{50899}Da, neki Martin.|Poslao sam Becka da ga pronadje.
{50901}{50945}äta je sa samim gradonaËelnikom?
{50947}{51002}Ako tu ima neöto prljavo|i skriveno...
{51004}{51055}nije se pojavilo.
{51106}{51221}Pronaöli smo sliku gradonaËelnika sa |proölog boûiÊnog bala. Hains je bila tamo.
{51223}{51290}Oh, i Taylor Higgins|i Daniel Freita.
{51292}{51334}To je zanimljivo ime.
{51336}{51388}Nedavno sam Ëuo glasine...
{51390}{51434}o Benny Lee...
{51436}{51468}i Daniel Freita.
{51469}{51561}To je Ëudno. Freita je velika zverka.|äta on i Lee imaju zajedniËko?
{51563}{51676}IgraËka komisija je nagradila Freita|sa jednom preostalom dozvolom.
{51678}{51797}A ima dve taËke na Blue Strand|za taj poslednji kazino.
{51799}{51856}I pogodi ko ih poseduje.
{51900}{51943}Benny Lee?
{51945}{52004}Chung trijada sklanja novac|iz Hong Konga.
{52006}{52129}Benny Lee je koristio öansu|da kupi to pre dve godine.
{52131}{52209}- Ko poseduje drugi deo zemlje?|- Neki nemci.
{52211}{52299}Drugim reËima ko god napravi posao|zaradiÊe milione dolara.
{52301}{52367}Stotine miliona.
{52369}{52455}A druga zemlja onog ko je izgubio|niöta neÊe vredeti.
{52618}{52666}Ovo moûda niöta ne znaËi...
{52705}{52782}ali sam takodje Ëuo da|Daniel Freita ima crtu...
{52784}{52829}u Uncle Brother...
{52831}{52883}na ime Tommy Tranga.
{52986}{53059}- HoÊeö li saËekati u kolima?|- Naravno.
{53111}{53158}Kakvu crtu?
{53159}{53198}Niko nezna zasigurno...
{53200}{53290}ali ljudi su vidjali Tommya i Freita|zajedno viöe puta.
{53360}{53400}Vidi ovde.
{53402}{53498}Melanie Hains ima treÊu cimerku,|Jennifer Haller.
{53500}{53573}»oveËe, ona ima crvenu haljinu na njoj|skoro milju dugaËku.
{53617}{53680}Jedan od mojih kontakata kaûe|da je uöla medju azijate.
{53713}{53790}Ona je takodje bila na gradonaËelnikovoj zabavi|zajedno sa Hains i Daniel Freita.
{53792}{53832}Pa?
{53833}{53903}Ta ûenska Haller je otiöla da se vidi sa prijateljem.|Tamo je trebala da se nadje sa Melanie.
{53905}{53954}Niko o obema nije|niöta Ëuo odonda.
{53955}{54018}- Jesi li pozvao prijatelja?|- Ne.
{54020}{54094}Nikki nezna njeno ime.
{54096}{54152}Neki kontakt sa Halleri?
{54154}{54193}Da, njeni roditelji.
{54195}{54268}Ali oni ûive u Indiani i nisu|razgovarali sa njom tri godine.
{54270}{54347}- Siguran si da znaö öta radiö?|- Kako to misliö?
{54529}{54578}Mlada je?
{54859}{54907}Prezime joj je  Calderon.
{54909}{54990}Ona je iz malog grada u Ohiou|koji se zove Medford Lakes.
{55018}{55095}UËini mi uslugu.|Vidi öta moûeö da iskopaö za nju.
{55189}{55240}Oh, Boze.
{55384}{55442}Da, poËistiÊu.
{55444}{55507}Nemoj.
{55760}{55792}äta je to?
{55953}{55985}Niöta.
{55986}{56011}Niöta?
{56080}{56116}Nekad sam se sekla.
{56135}{56158}Zaöto?
{56208}{56285}To je neöto glupo öto sam radila|kao mladja.
{56287}{56335}Ne ûelim da priËam o tom.
{56719}{56759}Uradio sam ludu stvar noÊas.
{56778}{56842}Otiöao sam do kineske Ëetvrti|da vidim neke ljude.
{56844}{56942}Misio sam da mi mogu reÊi|neöto o DanieIu Freiti.
{56957}{57019}Niotkuda pojavio se|Eddie Trang.
{57021}{57093}Sa njim je bilo i par|PTK propalica...
{57094}{57229}i nijedan nije izgledao kao da hoÊe|da mi kupi mai tai u ime starih dana.
{57274}{57304}äta se desilo?
{57306}{57415}Pitao me je öta ja imam sa|DanieIom Freitom...
{57417}{57485}i ja sam mu rekao|da me poljubi u dupe.
{57504}{57585}SledeÊe Ëega se seÊam je 9mm|na mom licu...
{57587}{57676}i niko se nije smejao sem mene.
{57737}{57785}Tommy Trang ima Eddia|na kratkom lancu.
{57787}{57860}Moraö da staviö bubu|u njegovo dupe.
{57862}{57910}Znaö...
{57912}{57968}mora da ima neöto u ovoj|Freita stvari.
{57987}{58035}Bilo je zabavno, Rem.
{58072}{58131}Kao u starim danima.
{58133}{58173}Da.
{58175}{58214}Laku noÊ.
{58216}{58252}Laku noÊ.
{58347}{58398}Neöto nije u redu?
{58517}{58634}Ponovo si na kauËu veËeras.|Moram da ustanem ranije u uradim neke stvari.
{58636}{58697}A onda idemo|na roötilj.
{58805}{58863}Da li ste rekli da ste pronaöli telo?
{58864}{58938}Naöli smo njenu levu ruku.|Joö uvek tragamo za telom.
{58939}{59025}- Da li si imao sex sa njom, Martine?|- Ne, nismo stigli tako daleko.
{59027}{59108}Par puta smo izaöli na veËeru,|jednom na igru.
{59110}{59158}Jesi li se dorogirao sa njom?
{59195}{59250}Idete pravo u centar,|zar ne?
{59252}{59303}Nema svrhe da gubimo vreme.
{59332}{59412}Pa ne mogu umesto nje da govorim,|ali ja ne uzimam droge.
{59414}{59454}Dobro.
{59456}{59512}- Koliko dugo radite za gradonaËelnika?|- Malo viöe od godine.
{59513}{59586}- äta ste radili pre toga?|- Radio sam za Freita korporaciju.
{59635}{59667}Zaöto ste napustili?
{59668}{59709}Ovde je bolja prilika.
{59792}{59828}Poznajete je?
{59880}{59980}Da, sreo sam je u nekim crnim tesnim stvarima|koje je gradonaËelnik bacio za  Mr. Freita.
{59982}{60054}- Bila je sa Melanie.|- äta posle toga?
{60056}{60108}Nikad je nisam video posle toga.
{60146}{60219}Bila je zainteresovana za drugog momka|koji je radio za Freita korporaciju.
{60221}{60283}- Ja sam ih upoznao.|- Koji drugi momak?
{60314}{60375}Ime mu je Oren Doba.
{60377}{60450}On nije tamo viöe.|Otiöao je na pravnu ökolu.
{60481}{60513}Neznam öta da vam kaûem. Nisam video|Jennifer Haller mesecima
{60513}{60579}Neznam öta da vam kaûem. Nisam video|Jennifer Haller mesecima
{60660}{60739}Ali pre ste je puno vidjali,|zar ne?
{60826}{60925}Vidite, ja dolazim iz stare|Bostonske porodice u redu?
{60926}{61003}Stoga si preöao prag|da bi umoËio djoku.
{61005}{61101}Velika stavar. Briga nas za |tvoje porodiËno stablo.
{61102}{61159}Samo öta znaö o|Jennifer Haller.
{61161}{61209}Bila je divlja.|äta da kaûem?
{61211}{61292}U naöem poslu, "divlja" moûe da znaËi|puno stvari. Budi precizan.
{61314}{61348}Volela je da se igra.
{61349}{61394}Znaö, one stvari.
{61396}{61437}" One."
{61439}{61525}Kao biËevanje|na primer?
{61527}{61569}Da.
{61588}{61619}A ti?
{61665}{61740}Da, Naravno. Zaöto ne?|To je bilo neöto drugaËije.
{61741}{61790}Pa, ako dovoljno boli...
{61816}{61855}öto ste prestali da je vidjate?
{61856}{61906}Ona je prestala da vidja mene.
{61908}{62005}To je ionako bio samo fol.|Ja sam bio samo karta do Freita.
{62214}{62257}Moûemo to ovde...
{62293}{62341}ili da odemo do stanice.
{62343}{62385}Ti odluËi.
{62400}{62498}Vidite, hoÊu da pomognem ali moûda|bi trebalo da zovem advokata.
{62500}{62540}Ne treba ti advokat.
{62542}{62643}Samo nam daj neöto öto Êe nas|odvesti na sledeÊi nivo.
{62691}{62753}Freita je voleo da se igra|ponekad.
{62776}{62837}Da li si se ti igrao sa njim|ponekad?
{62839}{62891}- Par puta.|- Gde?
{62893}{62921}Kod njega.
{62923}{62993}- Da li je Jen Haller bila tamo?|- Par puta.
{62995}{63042}Da li si je video sa Freitom?
{63044}{63086}Mislim...
{63088}{63128}intimno?
{63130}{63192}jednom. Kao.
{63194}{63253}- Da li su bili " kinky" ?|- Ne, ona je doöla tamo.
{63255}{63319}Bila je to velika zabava,|sa puno ljudi.
{63320}{63419}Pored toga saËuvala je teöke stvari|za ovaj klub.
{63480}{63511}Club 88?
{63535}{63576}Da.
{63614}{63667}Da li te je vodila u|taj klub?
{63669}{63700}Jednom.
{63749}{63807}Da li je vodila Mr. Freita|u taj klub?
{63827}{63858}Ne mogu da kaûem.
{63944}{63980}Ne moûeö ili neÊeö?
{64007}{64094}Zaista mislim da ne bi trebalo viöe|da priËam bez prisustva advokata.
{64269}{64355}Svaki put kada imamo roötiljadu|pada kiöa.
{64357}{64423}- PriËaj mi o tome.|- SeÊaö se proöle godine?
{64425}{64461}Da, lilo je.
{64543}{64580}To je bilo lepo.
{64582}{64613}HoÊu deset.
{64655}{64695}Kao malo mlada, Rem.
{64697}{64733}äta?
{64734}{64774}Oh, Hajde, Lynn.
{64797}{64876}Monty me nije gledao kao öto ti|nju gledaö joö od venËanja
{64878}{64930}Da ti dupe izgleda joö uvek tako dobro|verovatno bih.
{64952}{64997}Jebi se.
{65118}{65211}Ne svidja mi se ova stvar sa Freitom .|Mislim da si tu na kraju grane.
{65212}{65290}Imam klinca koji kaûe da se zabavljao sa|Freitom i Haller .
{65292}{65410}Pitao sam Tiger Wua da malo pronjuöka|i pogodi ko je ispao-- Eddie Trang.
{65428}{65471}Neko se brine.
{65473}{65579}Joö uvek je to daleko od Melanie Hains|i Benny Leea.
{65581}{65655}Mislim pa öta ako Freita|voli mlade ûene.
{65657}{65705}OËigledno to nije zloËin.
{65873}{65934}Ne gazi mi po jajima.|Nije to öto misliö.
{65936}{65984}Ali ona je kod tebe?
{66010}{66060}Za prvo vreme.|Privremeno.
{66062}{66091}Ti si lud, Rem.
{66122}{66186}Ako dojeö do neËega
{66187}{66249}Ne priËam ti kako to da|odigraö--
{66251}{66334}samo polako i |pobrini se da boli.
{66336}{66398}I molim te,|donesi prvo meni.
{66400}{66434}Apsolutno.
{66436}{66480}Ti ovde vaûiö za glavnu facu.
{66482}{66514}Znam.
{66545}{66584}- äta?|- Vidi Boutona.
{66586}{66672}Pokuöava da dodje do neËega.|NeÊe dobiti niöta.
{66674}{66737}- Mogu li dobiti hot dog?|- Uporan je.
{66807}{66860}Anna je na telefonu za tebe.
{67064}{67100}Da, Anna, Rem.
{67102}{67187}- Vi se momci zabavljate?|- Naravno.
{67188}{67246}Imam neöto öto bi morao|da vidiö.
{67248}{67319}- äta je to?|- Trebalo bi da vidiö.
{67321}{67375}Hajde, Anna.|zar ne moûe da saËeka?
{67377}{67450}Mislim da treba da|vidiö upravo sada.
{67452}{67493}Samostalno.
{67495}{67544}U redu, doÊi Êu.
{67546}{67580}Zdravo.
{67737}{67784}äta ona radi ovde?
{67786}{67833}Ona je deo ove istrage.
{67835}{67902}Da, neko je to|trebalo da mi kaûe.
{67903}{67960}Ono öto si juËe videla|nije ono öto misliö.
{68010}{68084}Nemoj da kopaö sebi rupu|to te neÊe izvaditi.
{68289}{68368}Neöto je iskrslo u stanici|i nemoûe da Ëeka. Moram da odem.
{68370}{68423}U redu, idem da se presvuËem.
{68425}{68488}Molim te pokuöaj da se opustiö.|Dobro se provedi.
{68490}{68601}Ako se ne vratim za par sati,|uzmi Boutona da te odveze do mene.
{68603}{68635}Naravno.
{68672}{68710}∆ao.
{68739}{68801}Doölo iz Tribunove|fotoarhive za tu noÊ.
{68803}{68890}Uglavnom slaveÊe kape|i öampanjski osmeh.
{68944}{69021}Dakle Haller je srela Freita|na toj zabavi.
{69023}{69114}Kladim se u nedeljnu platu da mu je |rekla öta hoÊe za boûiÊ.
{69115}{69175}Ovo umalo da mi promakne.
{69354}{69471}Pitala sam se da li je tvoja prijateljica|zaboravila da pomene da je bila tamo te noÊi.
{69678}{69738}- Hey, to sam ja.|- äta ima?
{69763}{69837}Jesi li iskopao neöto|o Nikki Calderon?
{69839}{69911}Ima stari listing za Calderon|u Medford Lakes...
{69913}{69983}ali nije u upotrebi|godinama.
{69985}{70100}Znam momka nedaleko odatle.|VideÊe öta moûe da pronadje.
{70101}{70127}- JaviÊu ti|- Ovo je privatna stvar.
{70127}{70161}- JaviÊu ti.|- Ovo je privatna stvar.
{70383}{70450}Jeli ovo sluûbeno,|ili se samo zezaö?
{70468}{70506}Znaö je?
{71474}{71543}Vi ste ovde na ivici|gospodjo.
{71570}{71638}Ne plaÊam toliko novca advokatima|ni zbog Ëega.
{71665}{71739}- Kada si zadnji put videla Jennifer Haller?|- Pre mesec dana.
{71762}{71845}Imala je specijalnog klijenta|i oni su regularno bili zajedno.
{71846}{71907}A onda iznenada|to je prestalo.
{71909}{71938}Je li to on?
{72039}{72072}Bio je azijat.
{72103}{72127}Azijat.
{72274}{72318}Rekla si "bili su."
{72337}{72414}Imala je partnera.|Plavuöu.
{72416}{72469}Mislim da joj je ime...
{72471}{72521}Vicki ili Nikki.
{72566}{72610}Neöto tako.
{72797}{72833}Izlazi odavde!
{72865}{72922}- Obuci se.|- Povredjujeö me!
{72942}{72979}Obuci se!
{73469}{73535}Dolazim. Dolazim.
{73829}{73890}Znam da si gladan,|zar ne momËe?
{74486}{74514}äta nije u redu?
{74516}{74570}ReÊi Êu ti öta nije u redu.
{74572}{74648}Neko me ovde jebava|a to mi se ne svidja.
{74650}{74690}O Ëemu to priËaö?
{74692}{74742}Zaboravila si da si bila|na gradonaËelnikovoj zabavi?
{74744}{74793}- Nisam.|- Nemoj da me laûeö.
{74816}{74864}Sluöaj.|Mogu da objasnim.
{74866}{74945}A kad smo kod toga,|objasni öta si radila u klubu 88.
{74947}{74995}U redu.|Bila sam na tom balu.
{74997}{75065}Ali nisam mogla da ti kaûem|zato öto bi mislio da imam neke veze.
{75067}{75146}- Sluöam.|- U klubu 88 sam bila zato öto mi je trebao novac.
{75148}{75202}Jebala si se sa Danielom Freitom!
{75227}{75319}Nisam dodirnula Daniela Freita.|Da li da govorim o sveöteniku.
{75321}{75377}Koji jebeni sveötenik?|Sveötenik do mojega.
{75379}{75415}Isuse!
{75552}{75668}Kada je Jen videla Freita na balu,|on se popeo na vrh njene liste ûelja.
{75670}{75725}Nije je viöe zvao|posle te noÊi.
{75727}{75863}Stoga se ona poigrala sa Orenom Doba|da bi upala u Freitin svet u klubu  88?
{75865}{75926}Freita nije iöao u 88.|Ali je iöao sveötenik.
{75927}{76001}Bio je izaslanik koga je|Jen srela na jednoj od Freitinih zabava.
{76002}{76051}On je bio nekako fetiö uvrnut.
{76112}{76207}Jen je mislila da ako me ukljuËi|u njenu igru sa sveötenikom...
{76209}{76264}da Êe joj on pomogao sa|Freitom.
{76293}{76366}Nikad nisam upraûnjavala sex.|Samo sam se skidala gola.
{76368}{76424}Poötedi me detalja.
{76688}{76741}Sada u ime boga...
{76743}{76823}da li je Melanie Hains|ukljuËena u sve ovo?
{76850}{76940}Melanie je bila Jenina karta|da upozna ljude sa novcem.
{77016}{77047}Mala izgubljena devojËica.
{77074}{77135}Tata nije mogao da joj kupi|ono öto je zaista ûelela.
{77137}{77189}- Stoga öta se desilo?|- Poslednje noÊi u  88...
{77191}{77239}sveötenik je poludeo...
{77241}{77298}i rekao Jen da se nikada neÊe dogoditi|izmedju nje i Freita.
{77299}{77369}- Zasto ne?|- Ispostavilo se da Freita nije sa ûenama.
{77410}{77465}Njegov ukus je malo sladji.
{77492}{77539}- Deca?|- DeËaci.
{77586}{77659}Neöto öto je sveötenik|nazivao zmijom.
{77705}{77741}Znaö li öta je to?
{77767}{77803}Da.
{77884}{77939}To je kineski ilegalni stranac.
{78043}{78102}Kako je taj momak znao sve to?
{78149}{78219}Zato öto je on podvodio deËake|kod Freite...
{78220}{78274}iz sirotiöta koje je vodio.
{78391}{78415}On je mrtav.
{78430}{78470}- Ko?|- Sveötenik.
{78471}{78521}Video sam ga juËe u mrtvaËnici.
{78835}{78878}To je bila ucena.
{78919}{78982}Tvoja cimerka je smislila|da moûe naterati Freita da plati...
{78984}{79032}da bi Êutala.
{79120}{79144}Koliko?
{79175}{79207}Million.
{79209}{79242}Jesi li i ti u tome?
{79312}{79361}Kunem se, Rem.
{79362}{79425}Rekla sam im da je to glupo,|ali nisu hteli da me sluöaju.
{79447}{79508}Freita je trebao da sretne devojke |u kuÊi na plaûi?
{79545}{79608}Tamo je trebao da|donese novac.
{79610}{79665}- Gde je to?|- Neznam.
{79688}{79733}Neznam, Rem.
{79734}{79778}Nisu mi rekli.
{79895}{79934}Tako me je sram.
{79975}{80076}Kada sam Ëula o|Melanie, bila sam tako uplaöena.
{80107}{80181}Mislila sam da Êe i mene ubiti|ako saznaju da znam
{80245}{80301}Rem, ûao mi je.
{80619}{80679}Ja sam.|Ostavi poruku posle signala.
{80706}{80780}Ovde Beck. Podigni ako si tamo.|Neöto je loöe krenulo.
{81011}{81122}Bila sam u kancelariji kada se to desilo|Neki policajci su Ëuli pucanj.
{81124}{81215}- Da li su ih videli?|- Otiöli su pre toga.
{81464}{81513}Pravo u glavu.
{81514}{81600}Verovatno je stajao ovde,|a onda uöao unutra i ubio psa.
{81654}{81694}NeÊe poleteti, Rem.
{81696}{81745}Hajde, Monty.
{81746}{81859}Imam klica koji je poloûio Jennifer Haller|u Freitinoj vikendici viöe puta.
{81861}{81923}ZnaËi da se igrala kod njega.|I joö mnogo ljudi.
{81925}{81991}Pored toga, dobio sam poziv sinoÊ|od deËakovog advokata.
{81992}{82053}Bio je veoma precizan da njegov klijent|nije zainteresovan da se bavi ovim
{82055}{82103}Moûemo da ga odvedemo na sud.
{82105}{82161}- Budi ozbiljan?|- äta je sa njenom priËom?
{82163}{82216}Misliö li da Êe neko krenuti|na Daniel Freita...
{82218}{82314}na osnovu priËe modela za donji veö|koja se zabavlja sa lasteks sexi igrama?
{82316}{82351}- Istina je!|- To je rakla kazala!
{82353}{82444}Neki droger  otkriva guzicu|sa svakakvim sranjem...
{82446}{82495}jednom od najuticajnijih|gradjana?
{82497}{82584}- Baljezga o devojci koja je sada mrtva.|- Nije mrtva. Nestala.
{82586}{82681}Ti neznaö da li sada ona skida neËije gaÊe|u Bumfucku, Egypt.
{82683}{82766}A za tu stvar, ne moûemo da izmislimo|telo Melanie Hains.
{82767}{82836}Ne bi mogao da pronadjeö veliku porotu|u celoj drûavi koju bi to dotaklo.
{82838}{82912}Zar ne vidiö vezu?
{82913}{83002}Imaö Daniel Freita,|Benny Lee i Trang braÊu.
{83004}{83075}Ove devojke su otvorile pokvarenu konzervu,|a oni su se medjusobno poubijali...
{83077}{83166}zajedno sa Ëovekom iz sirotiöta|i Tiger Wuom.
{83215}{83294}Vidi, donesi mi neöto jaËe i|ja Êu jurnuti.
{83296}{83362}- Ali neÊu da stavljam muda u procep.|- äta mi treba?
{83364}{83435}Za poËetak telo,|Melanie Hains?
{83496}{83545}Znam da ne ûeliö ovo da Ëujeö...
{83547}{83610}ali mislim da si poËeo da budeö|opsednut sa ovom devojkom.
{83612}{83683}- Aw,Jesus.|- Moûeö je povrediti.
{83793}{83878}Ovako ja mislim:
{83905}{84007}äta ako kaûemo Freiti ono öto znamo?
{84009}{84094}Ne. Moûda Êe ga to|poljuljati dovoljno...
{84095}{84155}da Êe otvoriti vrata|za Benny Leea i Trangove.
{84157}{84254}Sigurno znaö koju Êe cenu|Freita da plati ako ih da.
{84286}{84341}Oh, Boze, ne verujem u ovo.
{84343}{84393}Ne moûeö da poveûeö taËke i ti to znaö,
{84422}{84509}Sve öto moûeö da uradiö je da ËaËneö meËku,|i zavröiö na uliËnoj patroli do penzije.
{84511}{84592}To je ako Monty podigne to na viöi nivo|öto sumnjam da Êe.
{84611}{84695}Ne zaboravi da je, Daniel Freita|u policijskoj komisiji.
{84807}{84870}Moram da idem.|ReË mudrome.
{84872}{84920}Odvedi je na neko daleko mesto.
{84922}{84984}NeÊe je traûiti ako ne saznaju|da ona neöto zna.
{85177}{85226}äta je mislila...
{85266}{85346}o tome da znaö öta Êe se desiti|Freiti ako ih da?
{85438}{85478}äta?
{85598}{85678}Pa bilo je jedno ubistvo koje|sam istraûivao.
{85733}{85823}.
{85853}{85946}Ja sam razgovarao sa dilerom|da namesti Eddija, Tommyjevog brata.
{86057}{86106}Diler je zavröio mrtav...
{86129}{86177}a Eddie Trang slobodan.
{86230}{86266}Dakle...
{86293}{86341}Tommy je to liËno shvatio.
{86399}{86435}Vidiö...
{86465}{86541}Azijati ne ûele da izgube|kako oni kaûu "obraz".
{86837}{86936}I onda sam ja jedne noÊi|stajao na ulici sa May Lin.
{86998}{87050}Jednog trenutka mi je ona u rukama...
{87084}{87169}a sledeÊeg,|leûala je mrtva na kiöi.
{88298}{88355}To je upravo zaöto niko ne ûeli|da ti bude partner.
{88386}{88457}Zaöto Ëuvaö ovog gubitnika
{88459}{88507}Malo si opsednut sa|ovom devojkom.
{88944}{88983}Jesi li u redu?
{89011}{89059}Da.
{89119}{89167}Trebao bi malo da se naspavaö.
{89328}{89413}Kaûi mi da greöim u odnosu na naËin|na koji me gledaö.
{89545}{89606}Reci mi da zaista ûeliö da odem|da spavam.
{89748}{89799}Ili ûeliö neöto drugo?
{90243}{90292}Reci mi öta voliö.
{90522}{90558}Sve.
{92121}{92161}Jesu li te ovde upucali?
{92373}{92430}Moraö naÊi naËin da im vratiö.
{92561}{92609}Razmiölajao sam o tome.
{92807}{92884}äta misliö o nastavljanju tamo|gde su Melanie i Jen stale?
{92958}{93057}Znam da zvuËi ludo, ali öta ako mi|uradimo njihovu stvar sa ucenom?
{93199}{93238}Uozbilji se.
{93303}{93366}Monty je u pravu.|Sam si to rekao.
{93368}{93434}Niöta ne moûeö dokazati,|pa hajde da im naudimo na drugi naËin.
{93436}{93530}- Ja sam policajac. To je nezakonito.|- Kao i ubistvo May Lin.
{93571}{93610}I Tigera.
{93781}{93837}Ako skoËimo na Freita...
{93873}{93922}ubiÊe nas...
{93948}{94001}kao Melanie i Jennifer.
{94032}{94080}Veruj mi.
{94160}{94214}NeÊe ako budemo pametniji.
{94335}{94388}Ti misliö da je ovo samo igra,|zar ne?
{94390}{94440}Ne, Rem.
{94442}{94526}Ne mislim tako.|Znam da moûemo biti ubijeni.
{94636}{94684}Ali si Ëula Beck.
{94779}{94842}Oni znaju da znam,|i pronaÊi Êe me.
{94879}{94932}Pa ili da odmah poËnem da beûim--
{95133}{95181}OseÊam se dobro sa tobom, Rem.
{95328}{95387}Da li ûeliö da znaö zaöto sam se sekla?
{95423}{95519}Zato öto mi je ûivot bio sranje,|i sve öto sam znala bi je bol.
{95596}{95663}Ali kada me ti pogledaö...
{95664}{95713}kada me dodirneö...
{95812}{95875}OseÊam se kao da Êe mi|srce stati.
{95906}{95971}I ne oseÊam bol.
{95973}{96021}OseÊam se dobro.
{96067}{96142}I nikada nisam neöto takvo|osetila...
{96144}{96192}nekog takvog.
{96333}{96386}Ikada.
{96655}{96720}Mi to moûemo, Rem.
{96749}{96797}To je milion dolara.
{96827}{96876}Uradi to zbog toga...
{96981}{97029}i zbog May Lin.
{100345}{100402}- Zatvoreno je.Nema nikog.|- Otvori.
{100404}{100445}- Jebi se.|- Rekao sam da otvoriö!
{100447}{100509}- äta Êeö da uradiö, da me ubijeö?|- Mrdni seronjo
{100511}{100583}äta dovraga?|Skini mi se?
{100827}{100876}Traûim Benny Leea!
{100878}{100950}- On Êe te ubiti!|- Umukni kretenu!
{101155}{101227}Dugo se nismo videli, Rembrandt.
{101228}{101287}äta te dovodi|ponovu u kinesku Ëetvrt?
{101288}{101346}Samo si mi nedostajao|i tvoj brat, Eddie.
{101368}{101448}Gde je Tommy inaËe?|Napolju lovi pudlicu za ruËak?
{101489}{101560}- äta hoÊeö?|- HoÊu da govorim sa Benny Lee.
{101562}{101629}- Zbog Ëega misliö da on ûeli da te vidi?|- Daniel Freita.
{101701}{101776}- Skloni piötolj.|- Radije ne bih.
{101777}{101886}Hajde, Remy. »ega se plaöiö?|Misliö da Êemo te ubiti?
{101887}{101959}Proölo mi je to kroz glavu, Eddie.
{102314}{102409}Baö si glup, Rem? Uvek zabadaö nos|tamo gde mu nije mesto.
{102451}{102524}»ovek moûe tako da nastrada.
{102525}{102589}a ponekad i njegovi prijatelji.
{102591}{102686}- Nisam doöao da se igram sa tobom, Tommy.|- A zaöto si doöao?
{102757}{102838}- Da ti ispriËam priËu.|- Ne volim baö puno priËe.
{102840}{102902}- Oh, ova Êe ti se dopasti.|- Da? O Ëemu se radi?
{102903}{102960}Daniel Freita, deËaci...
{102962}{103028}i novac koji si uzeo od trijada|da bi kupio zemlju.
{103457}{103481}Nastavi.
{103528}{103593}Puno novca, veliki posao.
{103632}{103721}Sve öto ti je trebalo je Daniel Freitaina|dozvola za igranje.
{103751}{103818}Stoga Tommy dolazi na ideju...
{103820}{103907}kako da njega uvuËe u krevet|sa vaöim guzicama.
{103909}{103992}I tu se ukljuËuje preËasni Henry Moi|u priËu.
{104027}{104096}- PriËa postaje sve bolja?|- Oh, Da
{104098}{104200}Izgleda da se Daniel Freita's|pali na mlade momke...
{104202}{104263}a vi ste mu obezbedili|beskrajne zalihe.
{104265}{104356}Stoga Freita je vaö duûnik zauvek,|a dogovor je zapeËaÊen poljpcem.
{104358}{104478}Sve dok se Jennifer Haller|i Melanie Hains nisu pojavile.
{104681}{104750}PreËasni se malo zabavlja|sa devojkama...
{104752}{104800}i u trenutku razbuktale strasti...
{104802}{104850}on im sve priËa.
{104852}{104906}Potom devojke odluËuju|da malo pritisnu...
{104908}{104985}i tu stupa na scenu Trang
{104987}{105061}Na kraju, Ëetiri mrtva.
{105063}{105160}Dve devojke,|preËasni Moi, naravno...
{105161}{105210}i moj prijatelj, Tiger Wu.
{105377}{105451}- To je priliËno Ëudna priËa.|- Da, mislio sam da Êe ti se svideti.
{105453}{105516}Nisam rekao da mi se svidja.|Rekao sam da je Ëudna.
{105591}{105642}- äta ti ûeliö pandur?|- Novac.
{105644}{105718}- äta ja dobijam zauzvrat?|- Nikad neÊu ispriËati moju malu priËu.
{105719}{105770}OtiÊi Êu iz grada.|NeÊete me viöe Ëuti.
{105772}{105826}Ti si mrtav Ëovek.
{105956}{105991}Koliko?
{106092}{106140}Onaj milion koji su devojke ûelele.
{106255}{106359}I joö jedan milion za ono öto su|ovi tvoji uradili May Lin Choi.
{106361}{106409}Ti si jebeno lud!
{106482}{106553}- Dva miliona je previöe.|- Ne cenjkamo se.
{106554}{106661}Ako posao sa Freita ode juûno,|trijade gube njihov novac.
{106663}{106721}A ako se to desi...
{106723}{106789}obojica znamo|öta Êe se desiti sa tobom, Benny.
{106834}{106894}- Kako Êu znati da Êe ovo nestati?|- Imaö moju reË.
{106896}{106986}Da? äta me spreËava da te obesim ovde sa|ovim ostalim mesom?
{106987}{107057}To je kao na filmovima ,|Benny, znaö.
{107058}{107120}Sve se da srediti unapred...
{107122}{107207}da li bih trebao nestati ili zavröiti mrtav.
{107269}{107353}- Blefiraö?|- Moje je da znam...
{107354}{107403}tvoje da otkrijeö.
{107566}{107603}Imaö muda pandur.
{107643}{107675}ZnaËi imamo dogovor?
{107866}{107931}Ako me zajebeö pandur|biÊe ti bolje da beûiö.
{107984}{108033}VeËeras dakle.
{108143}{108191}Ovo Êe ti reÊi gde|i kada, Eddie.
{108234}{108298}Ponesi novac sam.
{108330}{108394}To nije dovoljno vremena|za tu koliËinu novca.
{108395}{108471}Oh, snaÊi Êeö se veÊ nekako, Benny.
{108490}{108534}U to sam siguran.
{108882}{108934}Hey. Kupili su.
{108936}{108987}- Oh, Boze.|- Da.
{108989}{109047}I digao sam na dva miliona.
{109123}{109165}Oh, Boze.
{109167}{109215}Moraö da se skloniö odavde.
{109240}{109299}- äta Êeö da uradiö?|- Moram da rasËistim par stvari.
{109301}{109351}- NaÊi Êemo se kasnije.|- Gde?
{109353}{109409}Postoji jedna stara ûelezniËka stnica|na uglu 50. i 8..
{109411}{109459}Zatvorena je veÊ neko vreme.
{109461}{109536}Tamo nema nikoga noÊu.|NaÊi Êemo se tamo u 11 :00.
{109569}{109609}Slaûeö se sa tim?
{109686}{109722}éelim te.
{109844}{109892}Imaö me.
{110514}{110584}Devojke su odluËile|da stisnu malo igru.
{110586}{110634}To je priliËno Ëudna priËa.
{110656}{110692}äta hoÊeö drote?
{110792}{110840}On nije znao.
{111109}{111149}- Monty je tu?|- Otiöao na dan.
{111151}{111195}KuÊi je.
{111197}{111283}Neki momak pokuöava da te nadje|celo jutro. Zove se Toby Carr.
{111320}{111360}Hvala.
{111546}{111594}Gde je Toots, Bouton?
{111596}{111683}Neka ûena se zaglavila u podzemnoj.|Idem tamo da se nadjem sa njim.
{111685}{111771}- Gde je Beck?|- Nisam je video ceo dan.
{111772}{111821}- Vidimo se kasnije.|- Da.
{112386}{112457}- Da?|- Mr. Toby Carr?
{112459}{112550}- Ko ûeli da zna?|- Detective Macy. Zvali ste me.
{112552}{112651}Oh, Da. Proveravao sam onu stvar|za vas i Tigera.
{112652}{112716}- äta imate za mene?|- Postojali su neki Calderonsi...
{112718}{112774}koji su ûiveli u MedfordLakesu|nekoliko godina ranije.
{112776}{112829}Ali su poginuli u|saobraÊajnoj nesreÊi.
{112831}{112913}- äta je sa njihovom Êerkom?|- Nisu imali Êerku.
{112915}{113021}Ali je postojala baba koja je ûivela u|Parksu pre nego je umrla pre godinu dana.
{113023}{113082}Ona je bila hranilac.
{113084}{113157}Jedna od njenih ötiÊenika je|bila i devoËica koja se zvala Nicole.
{113159}{113252}éivela je sa tom staricom|dok nije napunila 13, a onda je pobegla
{113254}{113316}Njeno pravo ime je  Donato.
{113318}{113366}To je sve öto sam nabavio.
{113438}{113478}Hvala.
{113670}{113726}- Nicole Donato. Nadji.|- Upravo sam u sred--
{113727}{113777}Uradi sada, Anna!
{113799}{113848}BiÊu za mojim stolom.
{113914}{113988}- Halo?|- Zdravo. Ovde Rem Macy. Je li Monty kuÊi?
{113989}{114033}Ne, ima neöto sa momcima|iz stanice.
{114034}{114118}Ako pozove, raÊiÊu mu da ti se javi|NeÊu zaboraviti.
{114120}{114168}Dobro. Hvala. Zdravo.
{114170}{114205}Zdravo.
{114233}{114249}Donato, Nicole Lee.
{114249}{114290}Donato, Nicole Lee.
{114291}{114353}Dve prijave za prostituciju|kao maloletna.
{114355}{114430}Nisu je zaustavile.|Odsluûila je 4 meseca u maloletniËkom.
{114432}{114517}Nisam imala vremena da proverim izveötaj|o hapöenjima. Imam sastanak i kasnim.
{114604}{114671}Nisi valjda u nekoj nevolji,|Rembrandt?
{114720}{114752}Jesi li u nevolji?
{114887}{114955}Pravo ime joj je Donato.
{114957}{115019}Misliö da sam u tome.
{115064}{115122}Evo izveötaja o zaposlenima|za Melanie Hains.
{115190}{115280}Imamo DanieIa Freita,|BennyLee i Trang braÊu
{115323}{115398}To je dug povratak|Melanie Hains.
{115693}{115741}Da otkloni bol
{115776}{115825}Boli kad se gubi.
{115857}{115917}Kao i ubistvo MayLin.
{115947}{115996}Donesi mi prvom.
{116035}{116083}äta ako to uradimo?
{116151}{116219}Mi moûemo to, Rem.
{116810}{116883}Reci mi ako greöim o tvom|pogledu na mene.
{116985}{117033}Kad me pogledaö...
{117122}{117170}kad me dotakneö...
{117300}{117374}OseÊam kao da mi srce |prestaje da kuca.
{117570}{117627}Ne oseÊam bol.
{117747}{117796}OdeÊam se dobro.
{118019}{118068}Imaö me.
{119508}{119602}Ako ne Ëujeö od mene|do ponoÊi, otvori.
{119637}{119692}SaËekaj malo.|O Ëemu je reË?
{119694}{119749}PonoÊ. Samo tako uradi.
{121047}{121083}Ovde.
{121268}{121316}Nedostajao si mi.
{121444}{121533}- Odakle ti ovo?|- Imala sam to.
{121534}{121598}Nisam video da imaö to ranije.
{121600}{121677}Naöla sam kada sam|pakovala stvari.
{121679}{121729}Emerald?
{121731}{121767}Da.
{121865}{121925}Ne izgleda mi kao|$2 milliona.
{121950}{121995}Benny nije mogao da podigne dva|tako brzo.
{121997}{122071}Evo ovde jednog.|On Êe doneti drugi. ObeÊao je.
{122073}{122122}- UzeÊemo samo milion.|- Ostavi to.
{122123}{122183}- Kako to misliö?|- Mislim ostavi to.
{122185}{122229}Posao otpada.
{122231}{122317}- Zajebavate se sa pogreönim ljudima!|- Skloni piötolj! NeÊe ti trebati.
{122344}{122395}Zaöto ovo radiö , Rem?
{122436}{122485}- Smeöteno nam je, Eddie.|- äta?
{122521}{122588}Njeno pravo ime je Donato.
{122590}{122661}Evo njenih sranja.|Dve prijave.
{122663}{122750}Policajac koji je prvi put uhapsio|bio je Jack Monteleone...
{122752}{122812}prijateljima poznat kao Monty.
{122814}{122884}- Moûda si Ëuo za njega.|- Koga je briga?
{122886}{122975}Moram to da mu predam. On zna kako se ja |oseÊam u vezi tebe i tvog brata...
{122977}{123038}i öta ste uradili jedinoj poötenoj|stvari u mom ûivotu.
{123110}{123168}I znao je da Êu otiÊi toliko daleko|da vam vratim to.
{123234}{123277}Zar nije?
{123305}{123367}Bio je to hot dog prodavac u parku.
{123369}{123434}Video je Ëoveka koga nikad u ûivotu nije video|dok se nisam pojavio sa ovom fotografijom.
{123519}{123575}A tu je i prsten Melanie Hains.
{123645}{123693}U obliku cveta...
{123798}{123866}sa dijamantima.
{123939}{123987}Gde je on?
{124049}{124097}Ovde.
{124126}{124178}Ko pre njemu dve, huh?
{124205}{124261}Daj mi pucu, Rem,|polagano.
{124296}{124378}- äta Êeö da uradiö? Sve da nas pobijeö?|- Ko je ovaj öupak--
{124613}{124674}äta te je toliko zadrûalo?
{124772}{124820}Ako je ikakvo opravdanje, Rem...
{124822}{124894}Znam taËno|kroz öta si proöao.
{124895}{124992}- Pakao je njoj reÊi ne.|- Moûemo li sada da idemo?
{125035}{125116}äta? Ona nema stomak|za ubistvo?
{125168}{125237}- Ja idem.|- Hey, gde ûuriö?
{125239}{125362}Ljudi ovde umiru veËeras.|Moûemo im makar reÊi zaöto.
{125411}{125461}Kada si ovo poËeo|da provaljujeö?
{125463}{125536}Kada sam otiöao da vidim Benny Leea, |a on nije znao o Ëemu priËam.
{125583}{125630}Te devojke nisu pokuöale|da ucene Freita.
{125632}{125692}Ubio si ih da napraviö|laûan sluËaj ubistva...
{125739}{125838}i dozvoliö Nikki da izvede |glumaËki trik
{125840}{125898}Kao öto rekoöe...
{125900}{125951}ono öto jebeno dobijeö|nije vredno onoga öto jebeno dobijeö.
{125953}{126024}- Zaöto ja, Monty?|- Neko drugi je trebalo da preuzme.
{126026}{126100}Ako Benny Lee odluËi da poËne da skida|umesto da plaÊa...
{126102}{126170}onda je bolje,|ti nego ja.
{126227}{126332}-Ne vidim kako Êe da to funkcioniöe.|-Niko ne mrzi Tommy Tranga viöe od tebe
{126334}{126387}Tako Êe to izgledati|kada se razdje dim.
{126388}{126503}ReÊi Êu da si radio neke lude öeme|da streseö Bennyja za novac.
{126530}{126622}- Vidiö gde idem sa ovim?|- Ne, Ne vidim. Puno je rupa.
{126624}{126689}Kao ja kada sam hapsio|Nikki ?
{126690}{126763}To bi moglo da bude interesantno,|da si ti okolo da poentiraö.
{126796}{126844}- Ali neÊeö biti.|- Zaöto si tako siguran?
{126846}{126923}-Kako to misliö?|-Stavio sam sve to na papir...
{126952}{127006}zajedno sa njenim izveötajem o hapöenju...
{127008}{127048}i dao sam Beck.
{127082}{127162}- äta je tako smeöno?|- SledeÊi pogled na tvoje lice.
{127223}{127283}Nikad nisam mislio da Êe ovo proÊi.
{127285}{127351}Kada je Nikki doöla kod mene|sa ovom öemom o uceni...
{127353}{127455}Mislio sam da je previöe riziËno,|ali me je Beck ubedila da je moguÊe.
{127457}{127505}Posle toga,|sve je ovo bio njen öou.
{127507}{127619}Bilo je vremena kada je to bilo tako ludo|da sam mislila da pobegnem.
{127621}{127735}Posebno kada si pomenuo|Medford Lakes.
{127736}{127800}- Ali je Tiger zatvorio posao?|- To jebeni--
{127928}{127978}Daj da ovo zavröimo.|Daj mi Eddiev piötolj.
{128005}{128087}- OdneÊu ovo do kola.|- Samo stoji tamo!
{128169}{128209}Oni Êe te ubiti, Nikki.
{128263}{128322}- Hajde. Reci joj.|- Hajde, Rem.
{128324}{128373}äou je gotov.|Elvis je napustio zgradu.
{128375}{128430}Zar ne vidiö to, Nikki?
{128432}{128522}NapraviÊe da si ti uzela novac|PrebaciÊe loptu na tebe.
{128524}{128606}Uvek pokuöavaö da utrËiö|i spasiö öto se moûe, huh?
{128608}{128677}Da nisi uvek bio takav kauboj,|moûda bi bio pristojan policajac.
{128679}{128741}- Da li si ti to, pristojan policajac?|- Ovo nije gde dobri momci...
{128742}{128837}pobedjuju loöe|Ëistim ûivotom i iskrenim srcem.
{128839}{128888}Pobedjuju oni koji|naprave novac na njemu.
{128914}{128977}- Vi ste loöi momci.|- Mi smo loöi momci?
{128979}{129008}Zaöto?
{129009}{129112}Zato öto smo ubili neko uliËno djubre|i neke debitante?
{129114}{129210}Ili neki deler koji uËestvuje|u deËijem seksu sa Ëovekom godine?
{129237}{129354}Ili neki patetiËni policajac koji je odluËio|da profitira sa mladjom...
{129356}{129417}da mu pravi druötvo|u starim danima?
{129419}{129500}Ko ste dovraga vi|da nas nazivate loöim mocima?
{129812}{129912}NeÊu reÊi niöta.|Znaö to.
{129914}{129962}Naravno, baby, znamo to.
{129996}{130057}Samo Êu uzeti svoj deo novca|i nestati.
{130084}{130133}Nikad o meni neÊeö Ëuti,|Kunem se.
{130155}{130197}Da, to je dobro.|To je dobro.
{130227}{130271}Hvataj ga.
{130273}{130313}Ne, on je otiöao.
{130399}{130467}Sa ovolikim novcem,|mogao bi se izgubiti. Nikad neÊete--
{130488}{130529}HoÊeö li zaËepiti?
{130598}{130664}- Jesam li uplaöen|- Nema Ëega da se plaöim.
{130666}{130746}- äta ako je on u pravu?|- Samo se jebao sa tobom.
{130748}{130837}äta Êe spreËiti vas dvoje da me|ubijete kada odem odavde?
{130839}{130888}Jednostavno Êeö morati da nam verujeö.
{130890}{130963}Mi smo veoma bogati jebaËi!
{131268}{131323}Gde si nabavio to?
{131415}{131472}Monty mi je to dao pre par godina...
{131525}{131583}u sluËaju da neko hoÊe da me povredi.
{132208}{132247}Diöi.
{132455}{132534}To je ono öto je May Lin rekla|one noÊi kad je umrla.
{132729}{132786}Trik je...
{132787}{132841}da nastaviö da diöeö.
{132919}{132952}NeÊeö nikada uspeti.
{132981}{133041}Nisam ovo ûelela da uradim.|Naterali su me.
{133043}{133085}Nema viöe laûi!
{133114}{133163}Rem, joö uvek moûemo da uradimo to.
{133199}{133289}Ti i ja moûemo da uzmemo sav novac|i samo se izgubimo odavde.
{133291}{133340}Uradio bi to.
{133395}{133452}Toliko te ûelim.
{133510}{133575}»ak i kada bi znao da je pogreöno.
{133577}{133630}Joö uvek moûemo.
{133728}{133764}Poverenje--
{133793}{133838}Joö uvek moûeö da mi verujeö.
{133873}{133927}U redu? Stalo mi je do tebe.
{133959}{134016}Prvi put u ûivotu...
{134018}{134066}Imam neöto öto je stvarno.
{134092}{134140}Poverenje, Nikki.
{134218}{134311}Zaöto ti to tako teöko pada?
{134373}{134443}Ko te je takvu napravio?
{134487}{134522}Svi.
{134621}{134687}Svi koje sam ikada znala.
{134769}{134829}Ne svi.
{135095}{135141}Na tebi je.
{135274}{135322}äta god ûeliö.
{135653}{135689}Moûda...
{136014}{136067}u drugo vreme, na drugom mestu.
{136137}{136199}éao mi je.
{137731}{137790}Ne ûelim da umrem.
{137904}{137952}Niko ne ûeli.
{140566}{140614}Imam neöto za tebe.
{140689}{140749}To je manje nego sto velikih.
{140818}{140866}Ti zaista misliö da napraviö|to da radi?
{140868}{140941}To je veÊ uradjeno. Zar nisi proËitao novine|zadnje tri nedelje?
{141000}{141048}Pametan si ti drote.
{141091}{141136}Moûe ti koristiti.
{141163}{141244}- Ne, |- äteta.
{141246}{141297}Postoji neöto öto moûeö|uraditi zauzvrat.
{141299}{141357}- äta je to?|- Drûi Daniela Freita pod kontrolom.
{141359}{141408}Nema viöe igre za njega.
{141409}{141492}To je gotovo.|Jeli to to?
{141580}{141642}Pa postoji joö jedna mala usluga.
{142398}{142496}- Tvoji momci hoÊe neöto drugo?|- Ne ukoliko nema dlake oko toga.
{142523}{142584}Sanjaj.
{142609}{142659}Joö uvek ne mogu da verujem|da su Monty i Beck uradili to.
{142661}{142709}Ja mogu. Nikad mu nisam verovao.
{142711}{142759}Da, ali to je tako uvrnuto ËoveËe.
{142761}{142835}Mislim on i Beck vode|kinesku Ëetvrt sa Eddie Trangom.
{142837}{142885}Ko bi pomislio na to sranje?
{142887}{142950}On je sigurno imao mnogo problema|da ti smesti, Rem.
{142952}{143004}Samo da bi smestio|malom gradskom dileru.
{143006}{143103}Neznam za vas,|ali smeötanje sa sto velikih...
{143105}{143180}nije mali novac|za moja shvatanja.
{143182}{143241}Sve öto imam da kaûem,|ti si jedan sreÊni belac...
{143243}{143304}da ti se piötolj napunio blatom.
{143335}{143377}Da, sreÊan.
{143379}{143438}Moûda sledeÊi put budeö traûio pojaËanje.
{143468}{143519}Kao öto Monty uvek kaûe...
{143521}{143605}kad je u pitanju policijski posao,|ja sam samo kauoboj.
{144326}{144365}Hvala.
{144367}{144416}Laku noÊ, Rem.
{144450}{144523}- »uvaj se?|- Ti takodje, Anna.
{144567}{144653}Ti si lud ËoveËe.
{144655}{144729}- Kako ti je krilo?|- Bivam jaËi svaki dan.
{144731}{144784}Novost o Tommy Trangu|bi trebalo da te oraspoloûi.
{144786}{144843}- äta se deilo Tommy Trangu?|- Neko ga je skinuo ËoveËe.
{144844}{144894}Naöli su ga kako pluta|ispod Bay Bridge.
{144895}{144970}Sranje. Nije moglo da se desi boljem momku.
{144971}{145042}Dao bih puno novca da vidim|kao pada.
{145044}{145089}Da, ja takodje.
{145090}{145145}- Toots, ideö samnom?|- Da, ËoveËe.
{145146}{145190}Mir, Rem.
{145191}{145240}Laku noÊ momci.
{145250}{145500}PREVOD I OBRADA|CEDO FILM - by Lucifer
{145525}{147025}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/99z2q|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
