{25}{175}-== [ www.OpenSubtitles.com ] ==-
{448}{547}Opak sam.
{735}{765}Hvala.
{768}{819}Hvala öto uËestvujete.
{857}{922}Zadrûite koncentraciju.|Polako razmiöljajte.
{950}{996}Trebalo bi sve biti u redu.
{1057}{1153}Pusti Low Rider, Donny.|Donny, Low Rider?
{1808}{1832}Idemo.
{1880}{1966}12 SATI DO ISTEKA ROKA
{2357}{2402}Daj mi bateriju.
{2462}{2535}Kaûem ti da sam pravi.
{2538}{2600}Kuda ovo ide? Kako Êemo uÊi?
{2646}{2720}Ja sam glavni,|ti ne znaö kako...
{2723}{2780}Guba, nisi ti ni tako loö.
{2858}{2891}Sve je savröeno.
{3228}{3273}Zdravo, dame.
{3276}{3388}Uvek sam volela crvenokose.|- Idemo, brzo. Pokret.
{3484}{3573}Znam da se razumeö|u Ferrarije. Da te vidim.
{4215}{4271}Jesi dobro?
{4332}{4412}Misliö da Êemo uspeti?|- Prerano je za prognoze.
{5008}{5090}Diana, Tricia, Nadine|i Rose su na putu.
{5093}{5131}Bravo, ljudi.
{5626}{5671}Ale, reci mi da neöto vidiö.
{5674}{5741}Jedinica dva. éao mi je,
{5744}{5805}ali nepojavljuju se.|- Dovraga!
{5839}{5914}NeÊeö se parkirati|ispred mene.
{5917}{5968}Niöta ne vidim.
{5994}{6043}Moramo se pomaknuti.
{6406}{6470}10 SATI DO ISTEKA ROKA|- PeËe li te ikada savest?
{6473}{6594}Nikako. Ja sam Robin Hood.|PljaËkam bogate, dajem bedi.
{6597}{6622}Doavola.
{6650}{6722}Donny!|-Evo, evo.
{6725}{6819}HoÊeö reÊi da dajeö siromaönima.|- RezaË ûice.
{6861}{6912}Ne, bednima.
{6959}{7007}Mi Êemo ostati|bedni bez ovog auta.
{7193}{7293}Kako ste?|-Novi ste. -Kako znate?
{7296}{7365}Sluöajte, dobro se|brinite za ovaj auto,
{7368}{7436}pa Êu se ja dobro|pobrinuti za vas.
{7439}{7523}Ne treba, kupite joö jedno odelo.|- Bog vas blagoslovio.
{7526}{7569}Posavetuj se|s nekim oko mode.
{7572}{7648}Doöao sam zbog auta, ne zbog|vrata. MiËi debelu guzicu.
{7651}{7708}Napolje! äta gledaö?
{7778}{7860}Dovraga. Bilo je lako.|- Ja sam ti veteran.
{7863}{7938}Napolje, ili pucam!|- Ne mogu da verujem.
{7941}{7991}PucaÊu!
{8041}{8102}Lenji, nesposobni nasilniËe.
{8105}{8202}Svako moûe pretiti oruûjem!|Niöta ne znaö o krai auta!
{8205}{8283}äta ti je?! Treba ti primer!
{9933}{9971}Pogledaj.
{10196}{10278}Vratio se.|Pametan je, Ëuva se.
{10281}{10366}Ostanite gde jeste.|Ako se odveze, sledite ga.
{10369}{10393}Primljeno.
{10622}{10697}äta radi? äta to radiö?
{10878}{10977}Mogli bismo i spustiti|prozor i mahnuti mu.
{10980}{11019}J.J. prati ga.
{11136}{11184}Idemo.
{11270}{11337}Sretno.|-Niöta laköe.
{11443}{11519}Ovde jedinica 2.|Astricky se pojavio.
{11522}{11570}Ako se odvezu, uhapsite ih.
{11624}{11701}SinoÊ je taj kombi|bio parkiran malo niûe.
{11753}{11834}Prate nas.|-Sranje.
{11837}{11864}Kod auta je.
{11936}{11981}Ptico, javi se.
{12032}{12104}Jedinica 1 , pripremite se.
{12107}{12157}Gde si?|- Kod kasina,
{12160}{12229}doöao sam po|devojku nadzornika stolova.
{12232}{12266}Devojke su neËiste.
{12269}{12330}Odlazi, devojke su neËiste.
{12333}{12395}Svi neka se odmah|vrate u garaûu.
{12398}{12518}Sada se poraa?|ldem odmah u bolnicu.
{12521}{12561}Neöto ga je prestraöilo.
{12564}{12634}éena mi se poraa.
{12637}{12692}Ovo uopöte nije moj auto.|Moj auto je malo dalje.
{12724}{12769}Udaljava se od vozila.
{12848}{12872}Vidim te.
{13004}{13061}Stani ovde.
{13398}{13452}Ovde jedinica 2.|Izgubio sam ih.
{13577}{13644}Vrijeme je za ponovni|razgovor sa Fuzzyjem.
{13679}{13708}Pogledaj.
{13711}{13810}KljuËevi koji öalju poruku|prijemniku u autu.
{13813}{13871}Odakle ti?
{13874}{13941}Iz proölonedeljne pljaËke.
{14105}{14140}Ko je?
{14326}{14410}äta se dogodilo?|- Odakle ti kljuËevi? - äta je?
{14413}{14503}Mercedese nadgledaju.|Odakle ti kljuËevi?
{14506}{14593}Od mog Ëoveka iz Southlanda.|I pre sam ga koristio.
{14596}{14723}Kada pre? - Kada smo ukrali|ostale. - Mercedese.
{14726}{14847}Castlebeck. Uspeo je pridobiti|nekoga iz prodavnice.
{14850}{14912}Imamo joö 8 sati.
{14915}{15002}TroöiÊemo vreme|na sastanak?
{15005}{15044}Memphise.
{15047}{15123}Moûda bismo mladeû|trebali izvesti iz grada.
{15126}{15203}»oveËe. Znaö öta? To...
{15206}{15330}Bez Mercedesa nema smisla|dizati druga kola, to je sve.
{15333}{15440}47 nije 50. To Êe reÊi.
{15443}{15545}Joö imamo kljuËeve|Mercedesa iz proöle krae.
{15548}{15654}To je zaplenila policija.
{15657}{15772}éeliö da odemo tamo|i maznemo ih? - Da.
{15775}{15910}Jesi lud? - Brzo, kreÊemo.|Gde su kljuËevi? - Nemoj.
{15913}{15958}Ne izgledam sumnjivo?
{15961}{16041}Otto, tvoj pas je|pojeo kljuËeve.
{16069}{16122}ObiËno jede tablice.|Jesi siguran?
{16125}{16224}»ekaj malo. Pas je|pojeo kljuËeve?
{16276}{16362}Kako Êeö ih izvaditi?|- Nije smeöno!
{16365}{16422}Ni ne pomiöljaj na to.
{16509}{16600}Toby, pokuöaj negde kupiti
{16603}{16695}pseÊu hranu i laksativ.|- Ne mogu da verujem.
{16698}{16789}Nevaljali pas!|- Prihvatimo se posla.
{17185}{17210}Otvori vrata.
{17213}{17262}Brûe!
{17265}{17342}Prestani, rok zvijezdo.|-Isuse Kriste!
{17345}{17399}äta Êemo ovde?
{17451}{17524}Nisi me zvao.|Moramo ostati ovde
{17527}{17578}dok mi ne kaûeö öta znaö.
{17581}{17686}Rekao sam. Znam, jer sam|rekao, To je sve öto znam.
{17689}{17798}Detektive, mislite da je|prekröio uslovnu?
{17801}{17932}Jeste, detektive.|Odbija saraivati sa policajcima.
{18081}{18144}Ovo sam nauËio u staraËkom|domu za kradljivce kola.
{18172}{18207}Pridrûi mi ovo.
{18210}{18289}Ne odbijam saradnju. Samo...
{18292}{18345}Dobro, u redu.
{18348}{18440}Kip Raines je prihvatio|jedan posao i onda ga uprskao.
{18443}{18482}Jako je uprskao.
{18485}{18536}Ko je naruËio posao?
{18606}{18652}Raymond Calitri.
{18673}{18706}Lepo.
{19076}{19143}Imamo öest sati.|Je li pas obavio öta?
{19146}{19192}Toby i Freb ga öetaju.
{19213}{19282}NeÊe niöta uËiniti.
{19285}{19393}Hajde, psu.|äta je, Hemi? Kaki, kuco.
{19457}{19502}Morao je biti ûenski auto.
{19505}{19570}éenski? Kakva ûena|vozi Hemicudu ?
{19588}{19641}PokazaÊu ti.
{19644}{19679}Ruû?
{19704}{19749}U boji auta.
{19800}{19859}äta joö? Rumenilo? Maskara?
{19862}{19937}IduÊi put Êu kupiti|visoke potpetice
{19940}{20005}koûne dodatke|i ruûiËasto donje rublje.
{20008}{20137}Koûa, potpetice?|Moûe ruûiËasto rublje.
{20210}{20323}Calitri je odsedeo 5 godina|u Londonu zbog ubistva.
{20326}{20360}Imigrirao je ovamo '98. g.
{20363}{20457}Pogledaj. Zelenaötvo,|iznuivanje, krae.
{20460}{20501}Vlasnik je otpada,|odande posluje.
{20941}{21011}Moramo Ëekati.
{21077}{21178}Viaö se s nekim?|-Ne.
{21205}{21278}Nekada sam imao devojku.|Bila je divna.
{21281}{21380}Ako je bila tako divna,|zaöto si je ostavio?
{21874}{21926}Zvao sam te da poeö sa mnom.
{21965}{22052}Ne, hteo si da budem|sasvim druga osoba.
{22073}{22185}Nisam hteo da ljudi stradaju.|Hteo sam da malo usporiö.
{22188}{22245}Nisam mogla.
{22248}{22293}Nisam bila spremna.
{22329}{22383}Sada se viöe ne baviö time.
{22386}{22431}Zato öto bez tebe|viöe nije bilo isto.
{22582}{22607}Ja Êu to uzeti.
{22610}{22700}»itao sam to, majmune.|-Pazi öto govoriö.
{22703}{22760}Ovo je dosije sa Odseka|za ubistva, o ubistvu.
{22763}{22828}3 meseca smo dobijali dozvolu|od sudije za prisluökivanje.
{22831}{22886}Nijedan drugi odsek,|pa ni Odsek za krae auta,
{22889}{22983}nije mu se mogao|pribliûiti ni na koji naËin.
{22986}{23040}Shvatate? ReÊi Êu vam neöto.
{23043}{23135}R. Calitrija Êemo uhapsiti zbog|ubistva 1. stepena, majmuni!
{23138}{23228}Koga je briga za krau auta?
{23278}{23341}Ne mogu ih gledati.
{23344}{23389}Brûe to malo, obavite to.
{23533}{23627}äta misliö, je li uzbudljivije|voditi ljubav ili krasti aute?
{23630}{23680}Seks ili dizanje auta?
{23873}{24034}äta kaûeö na seks|za vrijeme dizanja auta?
{24037}{24092}Dobra reËenica.
{24144}{24203}Ali ne pali|kod veÊine devojaka.
{24206}{24260}Samo mi je izletelo. Nisam...
{24306}{24372}Ali nisi mi odgovorila.
{24397}{24447}Problem je...
{24450}{24500}ZaobiÊi menjaË.
{24544}{24592}Da, baö...|-Smeta.
{24595}{24715}Bilo bi öteta|da se menjaË pokvari.
{24718}{24796}Usisni priklopac...
{24941}{24990}Glavni cilindar spojke...
{25102}{25192}Dvostruka grebenasta osovina...|-Ne mogu.
{25195}{25232}»ekaj.
{25235}{25330}äest cilindara, trostruki|Weber karburatori
{25333}{25415}meusobno povezani telom.
{25490}{25535}Vreme je za posao.
{25538}{25633}Dobre koËnice.|Dobre koËnice.
{25967}{26059}Niöta se ne deöava.|- Moûda ima zatvor.
{26062}{26142}Daj mu joö laksativa.|-VeÊ smo mu dali dva.
{26145}{26187}Hej , maleni!
{26237}{26317}Rekao sam ti da je ovo naö|teren. éeliö ga osvajati?
{26320}{26365}Ne ûelimo vaö teren.
{26368}{26412}Ne svia vam se?
{26415}{26476}Dobro je, za vas.|Ali za nas nije.
{26479}{26619}Mislite da ste bolji od nas?|Mogli bismo te nareckati!
{26622}{26730}»oveËe, kljuËevi.|- Samo trenutak.
{26764}{26817}»oveËe.
{26820}{26893}PovratiÊu!|- Kako je to odvratno.
{26896}{26973}Kakav se perverznjak|zabavlja sa pseÊim govnima?!
{26976}{27035}Evo ih! Sva tri!
{27038}{27099}Vi ste ludi.|-Imam ih!
{27102}{27210}6 SATI DO ISTEKA ROKA
{27213}{27320}POLICIJSKA GARAéA|SA ZAPLENJENIM AUTIMA
{27404}{27463}Probudi se, vidi ovo.
{27466}{27548}Svaki put kad vozim Volvo|Beverly Hillsom, uzme ga pauk.
{27774}{27869}Nemamo Volvo ovde.|- Imate, tako mi je reËeno.
{27872}{27978}»ekajte. Kaûem vam|da nemamo volvo.
{28131}{28197}Proverite, pronaite|moj prokleti Volvo.
{28200}{28269}Sfingo, Sway.
{28272}{28327}Mora biti negde ovde.
{28366}{28458}Nema niËeg. Pogledajte.|Ali ima joö jedna garaûa...
{28461}{28523}Hej, pogledaj ovo.
{28526}{28610}Pogledaj je...
{28860}{28918}Oprostite, ne bih|trebao biti ovde.
{28921}{28990}Upravo mi jedan|patuljak öalje poruku.
{28993}{29044}Moram iÊi. Vreme je novac!
{29085}{29147}Ovo je najgori|dan moga ûivota!
{29267}{29329}Det. Castlebeck. krhotine|stakla iz skladiöta
{29332}{29416}potiËu od|ultraljubiËaste ûarulje
{29419}{29471}koja se moûe|bilo gde kupiti.
{29586}{29657}Kog avola radi|ultraljubiËasta ûarulja
{29685}{29731}u skladiötu na Long Beachu?
{30061}{30160}Vidiö ovo staklo?|-UltraljubiËasta ûarulja?
{30163}{30250}Tako je. Proveri ovaj zid,|ja Êu ovaj.
{30273}{30372}SeÊaö se 70-ih?|- Bio sam premlad, hvala bogu.
{30375}{30427}UltraljubiËaste|ûarulje su bile u modi.
{30430}{30516}Koristilo se neko mastilo,|Magic Markers .
{30519}{30567}Videla se samo pod|ultraljubiËastim svetlom.
{30570}{30684}Ako si imao puno podataka|za koje nisi htio da se zna...
{30687}{30757}Na primer, popis|auta za krau... - Tako je.
{30825}{30870}To!
{30873}{30918}Evo popisa!
{30921}{31025}Popis je velik. Ne moûemo|obraditi sve te aute.
{31028}{31192}Moûda i ne moramo. Usmerimo|se samo na najree primerke.
{31195}{31225}Daj nekome da to obavi.
{31228}{31318}Mi Êemo preuzeti ovoga.|Shelby Mustang iz '67. g.
{31321}{31419}Sigurno ih ima samo nekoliko u gradu.|-Kako znaö da ga nije veÊ ukrao?
{31422}{31502}PoznavajuÊi ga,|ostaviÊe ga za zadnjeg.
{31505}{31563}Zaöto?|- Boji ga se.
{31610}{31706}3 SATA DO ISTEKA ROKA
{31853}{31930}Hej , ljudi.
{31933}{31993}»oveËe, öta radiö?
{31996}{32077}Hteo sam uËestvovati.|- Posle Êemo o tome. Doite.
{32459}{32486}Idite!
{32801}{32835}äta ti je? Doi!
{32838}{32896}Zovite osiguranje!|Neko nam krade auto!
{32899}{32977}Idemo! äta radiö?
{32980}{33038}Hteo sam te ostaviti.|äta ti je?
{33335}{33427}Sfingo, gledaj. Prijatelj|ima ZMIJA na tablicama.
{33430}{33534}Sutra Êe se zmija morati|voziti autobusom.
{33623}{33698}Policija, moramo|proveriti jedan auto.
{33701}{33747}Izvolite.
{33898}{33956}Evo malo muzike za voûnju.
{33959}{34047}Malo je drukËija od onog|sranja koje vi puötate.
{34138}{34198}Svia ti se.
{34201}{34259}Prija ti? Znam da ti prija.
{34313}{34388}Zmija! MiËi je!
{34391}{34429}Zmija!
{34645}{34716}Skloni je sa mene!
{34719}{34874}éeli me ubiti!|MiËi je sa mene!
{34877}{34935}äta radiö? Prihvati zmiju!
{34980}{35012}KoËi!|-KoËim!
{35085}{35171}Zmija mi se penje u guzicu!
{35174}{35249}U guzici mi je!
{35252}{35296}ProgutaÊe mi govna!
{35758}{35875}2 SATA DO ISTEKA ROKA
{35994}{36087}Boûe, kako volim taj auto.|Dva su isporuËena.
{36090}{36190}On uspavljuje Vanessu,|a ja sam provozala Bernardine.
{36254}{36298}Koliko ih imamo?|-48.
{36344}{36394}Ali Zrcalo i Sfinga su|imali neoËekivane goste.
{36397}{36478}Castlebeck? -Mislim da da.|-Sve u redu?
{36481}{36570}Dobro su. Kod Otta su,|s Donnyjem i Frebom.
{36573}{36662}Kip i Bravar?|- Joö se nisu javili.
{36691}{36737}Izgubljeni smo u paklu|predgraa. Gde smo?
{36740}{36841}Izgubio si se?|- Gde je izlaz? Sve izgleda isto.
{36844}{36880}Ne znaö gde smo?
{36883}{36929}Murijak. - Ne, murijak|na iznajmljivanje.
{36978}{37032}Uspori. - OkrenuÊe se|za 180 stepeni.
{37099}{37140}»oveËe, u nevolji smo.
{37143}{37188}U poteri smo|za ukradenim "Cadillacom".
{37191}{37230}Idemo prema severu|ulicom Murray Drive.
{37278}{37334}Blokiran put!
{37512}{37553}Gazi!
{37663}{37710}»oveËe!
{37713}{37818}Sranje.|- äta je?
{37821}{37859}Pogodili su ga!
{37862}{37933}Sranje! Vozi u bolnicu.
{37936}{38006}U bolnicama postavljaju pitanja.|-Vozi!
{38009}{38052}Razmisli malo,|u ukradenom smo autu!
{38143}{38206}Ne izgleda dobro.
{38325}{38393}äta se dogodilo?|- Naletili smo na osiguranje.
{38396}{38434}Nismo ih oËekivali.
{38437}{38555}OdveöÊu te leËniku,|privatnom. Stavite ga u auto.
{38609}{38692}Legni pozadi.|Hajde, legni pozadi.
{38695}{38760}Bravaru, ti i Kip|odvezite zadnji kombi Ottu.
{38863}{38949}äta radiö?|- Idem sa njim.
{39066}{39116}Ako neöto poe naopako...|- Idemo.
{39119}{39186}Ja Êu se pobrinuti za njega.
{39263}{39320}Dovröimo posao.
{39550}{39641}1 SAT DO ISTEKA ROKA
{39691}{39778}äta je? - äta je s Humveejem?|- Ukraden je.
{39781}{39842}Cadillac?|- Isto. Kuda idemo?
{39845}{39943}Jedini Shelby iz '67. g.|nalazi se na Long Beachu
{39946}{40006}u International Towers.|- Idemo na Long Beach.
{40841}{40896}Znam da smo puno|toga proöli zajedno, Eleanor.
{40899}{40990}I to ne lepe stvari.|Ali obeÊavam ti;
{41019}{41070}ako budeö pazila na mene,|ja Êu paziti na tebe.
{41595}{41637}Sranje.
{41751}{41810}Moûemo to izvesti|na laköi i teûi naËin.
{42115}{42153}Mislim da je odabrao teûi.
{42526}{42623}1B11 , u poteri smo za sivim|Ford Mustangom iz '67. g.
{42770}{42843}Pisalo je zabranjen smer.|- Primetio si, ha?
{42846}{42899}Isuse.|-Drûi se.
{42981}{43053}OsumnjiËeni se vozi|u smeru istoka niz 4. ulicu.
{43206}{43250}Ne, prema severu|niz ulicu Maine.
{43621}{43684}MiËite se!
{43975}{44003}Makni se!
{44115}{44149}éeliö ludovati?!
{44229}{44258}Samo daj!
{45927}{46001}Jedinica 3 uËestvovala|u saobraÊajnoj nesreÊi
{46004}{46047}na uglu ul. Vincent i 7.
{46879}{46961}Potera se vozi kanalom za|odvodnjavanje uz auto put.
{46964}{47035}Gde je vazduöna jedinica?!|-Treba nam vazduöna jedinica.
{47093}{47154}"Air 1" je iznad potere.
{47157}{47234}OsumnjiËeni putuje u juûnom|smeru brzinom od 160 km/h.
{47324}{47378}Pratite ga, "Air 1".|- Za petama sam mu.
{47575}{47633}Upravo je poveÊao|brzinu na 215km/h.
{47636}{47736}Nastavite sa praÊenjem.|- Brzina 250km/h.
{47739}{47810}Nemojte ga izgubiti.|- PokuöaÊu ga pratiti.
{47813}{47866}270 km/h, 290.
{47896}{47986}Pobegao nam je . - Zaboga!|- Bogami zna da vozi!
{47989}{48074}äta!? -Verovatno je|stvar u autu.
{48131}{48176}Koliko je sati?
{48234}{48284}19:30 h..
{48351}{48436}Mislim da Êu te morati|odvesti iz grada.
{48439}{48485}Tvoj brat je najbolji|dizaË auta na svetu,
{48488}{48557}ali ovo mu moûda neÊe uspeti.
{48603}{48712}Ja nisam kao Memphis.|Ne napuötam prijatelje.
{48715}{48781}Trebao bih te|dobro namlatiti, mali.
{48861}{48978}Misliö da je tvoj brat|pobegao? Pojasni mi stvari.
{49030}{49109}Hajde, da Ëujem.|Pojasni mi ih.
{49112}{49166}Vaöa mama mu je|rekla neka ide.
{49169}{49280}Znala je da Êeö krenuti|njegovim putem ako ostane,
{49283}{49382}pridruûiti se njegovim|ljudima. Rekla mu je da ide.
{49385}{49480}I otiöao je, misleÊi|da Êe ti tako najviöe pomoÊi.
{49483}{49578}Sve nas je ostavio, zbog tebe.
{49623}{49670}Ali to nije bilo teöko.
{49673}{49784}Nije se ûrtvovao ostavivöi|celi svoj ûivot za sobom.
{49787}{49915}Zatim, 6 godina posle, ûivot|je baö divan. Ipak kradeö kola.
{49918}{49952}Ko bi rekao?
{49979}{50046}Dao sam mu sedativ. Spava.
{50049}{50094}OporaviÊe se.
{50151}{50237}POLA SATA DO ISTEKA ROKA
{50753}{50837}Eleanor, to je sitnica.|Da se srediti.
{50840}{50902}Ne, nemoj. Nemoj mi to raditi.
{50986}{51082}Nemoj. Upali.
{51139}{51228}Trebam te, Eleanor.|Jako si mi potrebna, odmah.
{51413}{51503}OsumnjiËeni vozi na jug|avenijom Henry Ford.
{51506}{51563}SreöÊemo se sa njim|na aveniji Okean.
{51611}{51656}Eno ga.
{51659}{51734}Sad si moj , Raines!
{51962}{51996}LU»KO BRODOGRADILläTE
{52831}{52927}OsumnjiËeni ide na zapad.|Idite na istok za presretanje.
{53069}{53153}OsumnjiËeni|ide u vaöem smeru.
{53525}{53590}OkreÊe se na kraju doka.
{54726}{54754}Maknite se!
{55158}{55228}Je li dobro?
{55231}{55327}Kako ste? Sednite.|Nepovreeni ste?
{55330}{55427}Sigurno? Upravo ste|proöli kroz zid.
{55430}{55485}Toranj Long Beach,|ovdje "Air 1", L.A.P.D.
{55488}{55558}Traûim dozvolu|za prelaz preko vazduöne luke.
{55586}{55684}Ne moûe. Prilazi|avion. Zadrûite poloûaj.
{55711}{55805}Ponavljam, ne ulazite|u vazduöni prostor luke.
{56026}{56120}4 MINUTE DO ISTEKA ROKA
{57022}{57065}Eno ga.
{57205}{57249}Napolje iz auta!
{57330}{57365}Rainese!
{58510}{58629}Gde je Memphis? - Ne znam.|- Joö se nije vratio.
{58632}{58737}Kako to misliö? 8 h je.
{58835}{58895}Vreme je isteklo, Atley.
{58898}{58973}Imam 49 kola. Jednog|nema. Dovedite malog.
{58976}{59023}ReöiÊemo stvar.|- Kojeg malog?
{59026}{59123}Nekog malog sa ulice.|äta misliö, kojeg malog?
{59126}{59188}Valjda misliö na Kipa Rainesa.
{59191}{59236}Valjda si u pravu.
{59239}{59280}Smeöno je to, znaö.
{59283}{59360}Ne mogu ga pronaÊi.|Mali gad mi je zbrisao.
{59363}{59435}Pronai ga, Atley.|- äta ako ne mogu?
{59438}{59511}Onda Êe stariji brat|stradati. Meni je svejedno.
{59514}{59635}Moûe bilo koji Raines,|samo ako je od krvi i mesa.
{59638}{59735}Jebem ti...|Zahvali svom bratu.
{59738}{59827}Upravo je preuzeo|tvoje mesto pod giljotinom.
{60078}{60128}éao mi je,|ukrcavanje je gotovo.
{60131}{60234}Nije, ovo je 50. auto.|- Kasniö, odjebi.
{60237}{60328}Ako imaö neöto reÊi,|obrati se Calitriju.
{60757}{60783}Kasniö.
{60786}{60885}»ekaj. SvaaÊeö se|zbog 12 minuta?
{60888}{61008}Upravo sam ukrao 50 kola u|jednoj noÊi! Malo sam umoran,
{61011}{61104}napet i mislim|da zasluûujem malo uvaûavanja!
{61107}{61169}Rekao sam 50 automobila,|ne 49 i po.
{61172}{61299}49 i po? Nije u loöem stanju.|Samo je treba malo obojiti...
{61346}{61478}Naravnati lim. Baö tako.|Auto vredi 60, 70...
{61481}{61584}Moûda i 80 somova.|Oduzmi tih 80 od 200 somova,
{61587}{61695}i sve je u redu. Oduzmi mi 80|od 200 somova i jednaki smo.
{61698}{61827}Moûe. -Dobro. I sve to|sa mojim bratom je gotovo.
{61830}{61880}Gotovo je.
{61883}{61931}Nema viöe, proölost.
{61968}{62013}Nema viöe. Proölost.
{62183}{62277}Niko me neÊe vreati. Niko|mi neÊe pretiti piötoljem.
{62323}{62397}Ubijte ga, uniötite auto.
{62626}{62735}U redu.|Gde je Calitrijev otpad?
{62738}{62864}Otpad Exeter. Idemo? lz Odseka|za ubistva su nam rekli...
{62867}{62917}Neka se nose.
{63306}{63351}Jednorog.
{63354}{63403}Molim?|-Niöta.
{63523}{63587}Gde da te gaam?
{63590}{63649}U glavu ili u grudi?
{63652}{63720}U grudi.|- Sa zadovoljstvom.
{63723}{63815}»ekajte! Velika|promena plana!
{63818}{63854}Stani, Atley!
{63857}{63957}äta radite? Ne!|- Stani!
{63960}{64033}Ne, Calitri me poslao|da vas neöto pitam.
{64277}{64333}Sve Êe biti u redu.
{64336}{64388}Beûimo odavde.
{64525}{64600}Pogreöio si öto si momka|odabrao za prljave poslove.
{64603}{64680}Joö si viöe pogreöio|öto je to bio moj brat!
{64683}{64773}A najviöe si pogreöio|kada si mene hteo ubiti!
{64887}{64931}Oprezno sa tim.|- Sa tim?
{64934}{65007}Spusti je.|- A, da. Oboûavaö drvo.
{65010}{65041}Spusti stolicu.
{65069}{65102}Ne!
{65196}{65218}O, ne.
{66267}{66297}Spreman sam.
{68072}{68141}Ko ste vi?|- Policajac.
{68144}{68215}Bolje nemoj.|- Baö hoÊu.
{68218}{68285}Ako izaemo skupa,|imaö neke moguÊnosti.
{68288}{68399}Ako me ubijeö, tvoj ûivot je|gotov. Policajac sam.
{68402}{68482}Ne, ako te ubijem,|tvoj ûivot je gotov.
{68485}{68548}NeÊe biti tako loöe.|Pogreb Êe prikazati na TV.
{68551}{68662}PoËasna straûa,|pozdrav iz 21 puöke.
{68665}{68710}KovËeg Êe ti omotati zastavom.
{68738}{68789}NajveÊi dan tvoga ûivota.
{69522}{69597}Nalazim se u moralnoj nedoumici.
{69600}{69709}Razorio si grad svojim|ludovanjem. Ti i Eleanor.
{69712}{69803}Ali razumem|zaöto si se vratio poslu.
{69806}{69862}Bratska ljubav je...
{69865}{69905}Bratska ljubav.
{69955}{70020}Spasao si mi ûivot.
{70023}{70090}äta sada da radim?
{70093}{70156}Vi morate odluËiti, detektive.
{70201}{70285}Beûi, Randalle.|Ja Êu se za sve pobrinuti.
{70331}{70426}Idi, pre nego|se predomislim.
{70488}{70612}Na doku 14 stoji|brod s kontejnerima.
{70615}{70665}Mogli biste ga pregledati.
{70937}{71012}Moûe li zgodan, marljiv|kuvar dobiti pivo?
{71015}{71085}Bravaru, niöta ne radiö.|Donesi mi pivo.
{71122}{71193}Memphise! Ljudi, hrana!
{71196}{71241}Hvala, gospodine.|-Dovraga.
{71318}{71433}Jadan Toby.|Stvarno ga boli.
{71436}{71487}Ako je to bol, nemam|niöta protiv ranjavanja.
{71490}{71557}Seksi.
{71588}{71688}Ako je to ranjavanje na neki|naËin prosvetlilo sve vas,
{71691}{71775}ako ste uvideli mrak|ispod sjajne povröine zloËina,
{71778}{71833}ako ste se|poûeleli promeniti,
{71836}{71967}onda ta povreda odiöe|plemenitoöÊu i slavom.
{71970}{72021}Da smo barem svi te sreÊe.
{72024}{72069}Kaûete, Jadan Toby.
{72105}{72141}Ja kaûem, Jadni mi.
{72199}{72247}Progovorio je.
{72250}{72295}Mislio sam da si s Long Beacha.
{72358}{72391}Memphise.
{72478}{72527}Imam neöto za tebe.
{72530}{72587}äta je to?|-Otvori.
{72628}{72715}KljuËevi. To je dobro.|äta da radim s njima?
{72718}{72771}Hej, ovamo. Doite.
{72774}{72860}Doite, hajde.
{72863}{72952}Dame i gospodo,|zadovoljstvo mi je
{72986}{73081}predstaviti vam... -»oveËe!|-Tvoja vlastita Eleanor.
{73084}{73159}To je Eleanor.
{73162}{73224}Tvoja je.
{73265}{73376}U neredu je, ali za par|nedelja Êe biti pravi leptir.
{73475}{73501}Nisi valjda...?
{73504}{73607}Nisam, prodao sam|delove motora za nju.
{73610}{73685}Zapanjen sam.
{73688}{73737}Kupio si mi auto.
{73740}{73825}Da, mali znak zahvalnosti.
{73828}{73889}Za sve.
{73977}{74069}Ovako treba biti.
{74166}{74220}Ui, provozaj se.
{74223}{74286}Znam öta si uËinio.
{74289}{74373}Hvala ti.|-Vidimo se.
{74661}{74725}Ideö se provozati?|-Nego öta!
{75254}{75308}Nemoj mi to raditi...
{75336}{75411}(c) DivX Team|sybtitle by SNK
{75436}{76936}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/98zs9|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
