{1}{1}25.000
{26}{176}-== [ www.OpenSubtitles.com ] ==-
{1364}{1446}Mislim da Êu da umrem.
{1447}{1510}éelela si roendansko slavlje.
{1512}{1572}Kakav je to stari izraz lica?
{1573}{1665}- Nikad nisi meöala burbon sa öampanjcem?|- Ne.
{1666}{1755}- Jevreji ne smeju da piju.
{1798}{1882}Duöo, kako bi bilo|da ja vodim deËake u ökolu?
{1883}{1940}Imaö moj blagoslov.
{1941}{1989}Gde idete?
{1990}{2048}U tatinu kancelariju!
{2049}{2111}- Ko hoÊe tatinu taönu?|- Ja, ja, ja!
{2112}{2187}TrËite do kola. TrËite do kola.
{2188}{2262}TrËite do kola.|Opa. Pazi se.
{2327}{2394}- »ekaj.|- ∆ao, mama. Volim vas!
{2396}{2462}Pozdravite se sa mamom. Zdravo, mama!
{2463}{2527}Zdravo. Budite dobri.
{2528}{2598}- Volimo te.|- Volim i ja vas.
{2599}{2689}U redu. Hajdemo na posao.|Upadajte.
{2690}{2836}Upadajte u kola.
{2837}{2943}U redu. Sedite, momci.|Idemo.
{3057}{3170}Zdravo! Vidimo se|kad se budemo vratili.
{3459}{3507}Zdravo.
{3541}{3590}Zdravo, Gospodine Krejmer.
{3853}{3926}Tatina kacelarija! Tatina kancelarija!
{4037}{4086}Izlaz`te napolje.
{4166}{4214}Zatvori vrata. Dobar deËko.
{4253}{4342}U redu. Ulazite.|Idemo.
{4343}{4430}- Moramo da idemo do kraja.
{4575}{4688}Zdravo, veliki smrdljivi Ëepu za uöi!|Zdravo, veliki smrdljivko!
{5299}{5404}Ko je to?
{5524}{5583}Do sada, sve öto je|otkriveno su tela...
{5584}{5671}- dvoje male dece, Ëiji je identitet nepoznat.|- Odstupi.
{5811}{5895}Sluûba je sada zavröena.
{6248}{6345}Prokleti bili! Vi ste ubice!
{6346}{6435}Vi ste prljave ubice!|I vi to znate!
{6436}{6523}Vi ste ubice, svi vi!
{6742}{6804}Recite nam zaöto ste to uradili.
{6965}{7067}Ubili ste moje deËake!
{7068}{7144}Ubico! Ti prljavi ubico!
{7145}{7220}Ubio si moje deËake, Kejhol!
{7536}{7592}Jesi li ti poludeo?
{7593}{7663}Ne, vrlo sam ozbiljan.|HoÊu Kejholov sluËaj.
{7664}{7756}äta ti znaö o smrtnoj kazni?
{7757}{7863}- ProËitao sam sve öto postoji.|- Onda ne znaö niöta.
{7864}{7919}Znam da ste radili u|korist Sema Kejhola.
{7920}{7972}i da ste ga odrûali u ûivotu|sve ove godine.
{7973}{8083}I takoe znam da je upravo|dobio pravo da vas otpusti.
{8084}{8140}HoÊeö li mi reÊi kako to znaö?
{8141}{8195}Napravio sam od toga svoj problem.
{8221}{8324}A da li znaö, razlog|zaöto me je otpustio?
{8325}{8372}On mrzi advokate.
{8373}{8446}Zaöto bi onda uopöte|on tebe unajmio?
{8563}{8645}Vrati se u svoju kancelariju.|Obojica imamo pametnija posla.
{8728}{8776}Sem Kejhol je moj deda.
{8861}{8910}Vau.
{8996}{9056}Imamo odnos|sa Vilijamsom i Kukom U Dûeksonu.
{9057}{9115}Mogao bih da obavljam posao|iz te kancelarije.
{9116}{9179}Takoe znam da imate|bliske kontakte u ParËmen zatvoru.
{9180}{9231}Niöta ne bi ökodilo da i vi|tamo kaûete po neöto.
{9268}{9326}Shvatam da onda Hol nije|tvoje pravo ime.
{9327}{9404}Moji roditelji su ga promenili|sa Kejhol posle ubistava.
{9405}{9458}Imaö li joö uvek rodbine|tamo?
{9459}{9547}Imam ujnu i Dûeksonu.|Rekao sam joj da Êu moûda svratiti poslom.
{9590}{9652}Zna li ona kakav je|to posao?
{9653}{9714}ReÊi Êu joj|kada stignem tamo.
{9715}{9827}Vi Kejholi ste puni tajni.
{9828}{9932}- Jesi li ikad stvarno upoznao svog dedu?|- Ne.
{9933}{9995}- Jesu li ti rekli da postoji?|- Saznao sam na oËevoj sahrani.
{9996}{10042}- Kada je to bilo?|- 1980.
{10073}{10120}Iste godine kada je Sem|osuen na smrt.
{10121}{10206}- Da, gospodine.|- Tvoj otac mora da je bio|vrlo mlad Ëovek.
{10207}{10286}Trideset pet godina,|pet meseci, öest dana.
{10402}{10470}Moûda nije trebalo da pitam.
{10471}{10518}Nije vaûno.
{10519}{10624}Imao sam 52 godine prvi put kada sam|imao posla sa sluËajem smrtne kazne.
{10625}{10678}Nisam spavao nedelju dana posle toga.
{10679}{10756}- Ja i ovako ne spavam.|- Mmm.
{10757}{10851}Otvaraö strasti koje niko ne ûeli|otkrivenim, a uz to nisi dobrodoöao.
{10852}{10888}U jednom kratkom uûasnom trenutku,
{10889}{10944}Sem Kejhol Êe biti Ëovek o kome Êe se|najviöe govoriti u zemlji.
{10945}{10998}Gospodine Gudmen, ûiveo sam sa|ovim sluËajem, celog svog ûivota,
{10999}{11034}kako god da okretene.
{11035}{11106}- Da postupim tako zvaniËno moûe u stvari|da bude olaköanje. - äanse za pobedu...
{11107}{11192}su smeöne. Nemaö|öanse u paklu.
{11193}{11288}Ja idem, Gospodine Gudmen,|sa ili bez vaöe pomoÊi.
{11330}{11402}Zovi me iz Dûeksona.|Nemoj mi zahvaljivati.
{11403}{11457}Nisam ti uËinio|uslugu.
{11562}{11609}- Je`l on to uradio?
{11610}{11729}O, naravno jeste.|U to nema sumnje.
{11924}{11973}Paûnja molim.
{11974}{12034}Misisipi "Pejzaûni Parobrod"|za centar Dûeksona...
{12035}{12091}se sada ukrcava u plavoj zoni.
{13071}{13138}- Dobar dan, gospodine.|Drago mi je da vas vidim, gospodine.|- Hvala.
{13717}{13786}LiËiö na Indijanca prosjaka.
{13912}{13968}Gde ti je prtljag?|Dûesi, pomozi gospodinu Holu sa-
{13969}{14023}U stvari, odseöÊu u,|hotelu blizu sudnica.
{14024}{14098}Mmm... biÊu budan celu noÊ,|puno Êu da radim, pa-
{14099}{14162}O, srce. Kako god hoÊeö.|Volim te, Ëujeö?
{14163}{14243}Sada idi osveûi se i poûuri nazad.|Ovde su mi majke...
{14244}{14334}jedinih 12 preostalih devica|u celom Dûeksonu...
{14335}{14392}koje samo Ëekaju da te upoznaju.
{14393}{14470}Stvarno mislim da neÊu imati previöe|vremena za druûenje.
{14471}{14546}Moraö nas sve uveseliti priËama|o tome öta te dovodi ovde.
{14547}{14619}Nagaam da je to zbog upotrebe|tvojih advokatskih Ëari...
{14620}{14706}da odvojiö naöe lokalne burûuje|od njihovih nepoöteno steËenih bogatstava.
{14707}{14778}Trebao bi da poËneö|mrzovoljnim starim muûem.
{14779}{14834}On zasluûuje da bude kaûnjen.
{14835}{14909}- Li.|- Da.
{14910}{14982}Ovde sam da branim tvog oca.
{15036}{15124}- Vidi, shvatam da-|- Ti niöta ne shvataö.
{15125}{15192}Nemoj da si nekome neöto rekao.
{15193}{15258}- Li.|- Ni reË.
{15282}{15330}»ujeö?
{15613}{15688}Laku noÊ. Zovi me sutra.
{15689}{15762}- HoÊu.|- U redu. ∆ao.
{16020}{16082}- Divna ûurka, draga.|- O, hvala ti.
{16083}{16144}Ne zaboravi da idemo u muzej|u Ëetvrtak.
{16145}{16214}- Laku noÊ, Adame.|- Laku noÊ.
{16215}{16261}SreÊno.
{16343}{16452}Felps ûivi u gradu.|O, u redu je.
{16453}{16539}Imamo vrlo aktivan romantiËan ûivot.|Samo ne meu sobom.
{16540}{16580}Zaöto ostati u braku?
{16581}{16678}Dobro je za bankara da ima nekog|prihvatljivog za druûenja.
{16679}{16752}I dobro je za tebe da imaö bankara.
{16753}{16825}Dobro uraeno za siroti beli oloö.
{16826}{16871}Zar ne?
{16872}{16945}Nije loöe. Uopöte nije loöe.
{16946}{16995}Naravno, drugo je pitanje|koliko Êu biti prihvatljiva...
{16996}{17074}kada svet sazna da sam|Hitlerova Êerka.
{17153}{17234}U redu je.|Sve je pod kontrolom.
{17235}{17287}Niko ne zna?
{17288}{17364}Govorila sam o svom opijanju.
{17365}{17430}Ali ne. Niko ne zna.
{17431}{17528}Otiöla sam od kuÊe kada mi je bilo 18,|promenila svoje ime, upoznala Felpsa, pobegla.
{17529}{17598}Rekli smo njegovoj porodici|da je moj otac mrtav.
{17599}{17647}Uskoro ni to neÊe biti laû.
{17648}{17750}Govoriö o Semu kao da|ti on niöta ne znaËi.
{17847}{17933}Pa, s vremena na vreme,|ako mi je lep dan...
{17934}{18000}i Sunce sija,
{18001}{18053}Mogu da mislim o njemu,|i priseÊam se malih,
{18054}{18108}prijatnih trenutaka|iz mog detinjstva.
{18109}{18172}NaËina kako me je nazivao|slatkom devojËicom.
{18173}{18263}Ali najbolje pamtim|kako je uniötio apsolutno svakoga...
{18264}{18329}ko je napravio greöku|time öto mu se pribliûio.
{18389}{18438}UradiÊe to i tebi, znaö.
{18485}{18571}Budi vrlo oprezan u|izkopavanju proölosti, Adame.
{18594}{18676}Moûda ti se ne svidi|ono öto pronaeö.
{20214}{20262}Doöao sam da vidim Sema Kejhola.
{20630}{20678}- Taönu.|- O.
{20820}{20868}Raöirite noge, molim.
{20975}{21024}- Narednik Peker.|- Adam Hol.
{21061}{21109}Ovuda, molim.
{21397}{21471}- Ovo nije dobar dan za posetu Sema.|- Zaöto?
{21472}{21579}Upravo je zvao zatvorski advokat.|Sudija je presudio. On umire za 28 dana.
{21604}{21683}Idem po Sema.
{21684}{21730}Ovuda.
{22003}{22051}Briöi.
{22122}{22197}ZakljuËaÊu ova vrata.|Sem Êe ubrzo da doe.
{22198}{22244}Hvala.
{22789}{22874}- `Ajde.|- Marö napolje.
{23067}{23115}Ko si ti, doavola?
{23116}{23213}Adam Hol. Ja sam advokat|u firmi Kravic i Bejn, »ikago.
{23214}{23274}Vi Jevreji nikad ne odustajete, je`l?
{23275}{23330}Ja nisam Jevrejin.
{23331}{23392}Kako onda moûeö da radiö|za Kravic i Bejn?
{23393}{23462}- Pa, mi smo nepristasan|poslodavac. - Stvarno?
{23463}{23575}Znam da imaö oko|150 kolega tamo.
{23576}{23622}Koliko od njih su ûene?
{23646}{23701}Stvarno ne znam. Moûda desetak.
{23702}{23777}O, znaËi imate manje od|deset posto ûena.
{23778}{23834}Koliko kolega Ëamuga imate?
{23866}{23913}Imam Ëetiri afriËko-ameriËke kolege.
{23914}{24009}E pa, to je lepo. Koliko|jevrejsko-ameriËkih kolega imate?
{24010}{24083}- Oko 80 odsto? - Stvarno ne znam.|Meni je sve jedno.
{24084}{24129}Pa, meni je i te kako bitno.
{24130}{24224}Uvek mi je bilo neprijatno da me|zastupaju takvi dreËavi ljudi.
{24225}{24333}Da. Pa, ja mislim da bi mnogi|ljudi to naöli za zgodno.
{24334}{24392}- Zaöto si toliko nervozan?|- Nisam nervozan.
{24393}{24459}Plaöiö se da Êu da proem kroz|to staklo i da te öËepam?
{24460}{24537}Koliko sluËajeva smrtne kazne|si imao?
{24538}{24593}Ovo mi je prvi.
{24594}{24704}O, strava. Jevrejsko kopile je|poslalo ûutokljunca da me spasava.
{24705}{24813}Pobio sam neöto njihovog naroda,|i sada oni hoÊe da ubiju mene.
{24814}{24864}Uvek sam to oËekivao.
{24865}{24912}Priznajeö da si ubio|Krejmerovu decu?
{24913}{24982}Ko si bre ti da mi|postavljaö takvo pitanje?
{24983}{25030}Porota je rekla da jesam.
{25031}{25119}Apelacioni sud je izjavio da je|porota u pravu. Samo to je bitno.
{25175}{25224}Koliko imate godina, gospodine Hol?
{25225}{25277}Dvadeset öest.
{25278}{25365}- Voleo bih da preskoËim preko|vaöeg pravno prizntog poloûaja-|- Roen '69 godine.
{25366}{25412}Tako je. GledajuÊi u vaö|pravni poloûaj, doöao sam do-
{25413}{25458}- Gde?|- U Memfisu.
{25459}{25547}- ja- Sluöajte, viöe bih voleo|da se drûim, a-|- Tamo si odrastao, zar ne?
{25548}{25603}Odrastao sam u mnogim mestima,|uglavnom juûna Kalifornija.
{25604}{25665}Mm-hmm.|Je`l tvoja porodica joö tamo?
{25666}{25751}Mama se ponovo udala.|I ona ûivi u Portlandu.
{25791}{25846}A tvoja sestra.
{25847}{25911}Verujem da se ona zove Karmen.
{26029}{26077}Koledû. Berkli.
{26282}{26353}Kako ste znali?
{26354}{26439}Tvoj glas.|ZvuËiö isto kao tvoj otac.
{26482}{26536}Zaöto si doöao ovamo?
{26537}{26597}On me je poslao.
{26598}{26691}Nisam imao izbora.|Ali Êu te spasiti.
{26692}{26750}- SpasiÊeö mene? - Da.
{26751}{26835}Ovo od sina Ëoveka koji je|sebi prosuo mozak?
{26836}{26890}Idi do avola, ti malo govno.
{26891}{26962}Znaö li ti sa kime razgovaraö?|SpasiÊeö mene? Sranje.
{26963}{27048}»ini se kao da ne moûeö da spaseö|Êurku od Dana Zahvalnosti.
{27049}{27128}Idi, gubi se odavde.|Pokuöaj da spaseö svoje sopstveno dupe.
{27129}{27216}Ja sam jedina osoba na Zemlji koju|je briga da li Êeö da ûiviö ili umreö.
{27217}{27296}Sada, potpisaÊeö ovaj ugovor|kojim pristajeö da budeö moj klijent,
{27297}{27363}ili Êeö biti mrtav za 28 dana.
{27547}{27662}Svi smo pomalo zapanjeni time koliko|veliki je ovaj sluËaj od jednom postao.
{27663}{27712}Uh, öta je to toliko veliko|oko njega?
{27713}{27799}O, znam da "Dnevnik Klarion"|nije "»ikago Tribun,"
{27800}{27887}ali u naöem mestaöcetu,|je sve.
{27909}{27958}Uh, zbunjen sam.
{27981}{28061}Sigurno si video danaönje novine.
{28300}{28370}Hvala puno. Ovo Êe biti|sasvim dovoljno.
{28371}{28436}Javite nam ako postoji joö neöto|öto moûemo da uËinimo za vas.
{28813}{28881}Zaöto ûeliö da odmah okonËaö moje|zastupanje bez borbe?
{28882}{28994}Trebalo mi je puno vremena da zapalim|ona Jevrejska kopilad poslednji put.
{28995}{29060}NeÊu ponovo da prolazim kroz to.
{29061}{29155}- Dobro, to je razumno. - Ne interesuje me|da li ti misliö da je to razumno ili ne.
{29191}{29267}To je u dogovoru, i oko|toga nema pregovora.
{29317}{29395}Idemo dalje.|E pa, ovo je smeöno. "Bez blagosti."
{29397}{29461}Ako ûalbeni proces propadne,|moraÊemo da idemo kod...
{29462}{29525}Guvernera Mekalistera|kao poslednje sredstvo, tako da...
{29526}{29585}bi spreËavanje blagosti u tom|trenutku bilo samoubistveno.
{29586}{29672}Ako bih mogao da povedem Dejvida|Mekalistera u komoru sa sobom,
{29673}{29741}Umro bih sa osmehom.
{29742}{29832}Sueno mi je; Joö jednom mi je sueno.|Dobio sam porotu koja nije mogla da|donese jednoglasnu odluku oba puta.
{29833}{29913}Bio sam slobodan.|Bio sam slobodan Ëovek 12 godina.
{29914}{29992}A onda je onaj ljigavi|kuËkin sin Mekalister...
{29993}{30086}iskoristio mene da bi on bio izabran.
{30120}{30168}Nema nagodbi sa guvernerom.
{30213}{30261}Fino.
{30490}{30564}U redu.|Zaöto si posao kjukluksovac?
{30605}{30653}Zato öto je moj tatica bio u klanu.
{30654}{30743}- Zaöto je tvoj tatica postao kjukluksovac?|- Njegov tatica je bio u klanu.
{30744}{30831}- Strava. Imamo tri generacije, je`l?|- Ne. »etiri.
{30832}{30936}Pukovnik Dûejkob Kejhol se borio|sa Nejtan Bedford Forestom u ratu.
{30937}{31040}I porodiËna legenda kaûe da je on bio|jedan od prvih Ëlanova klana.
{31041}{31093}Dakle da vidim.|Predpostavljam da to njega Ëini...
{31094}{31164}tvojim pra-pra-pra-pradedom.
{31165}{31242}Je`l ti od mene oËekujeö da se|oseÊam ponosnim zbog toga?
{31243}{31294}Zabole me kako|se ti oseÊaö.
{31295}{31370}Samo ti govorim ko si.|Nisi li zbog toga ovde?
{31450}{31521}U redu, Krejmer blizanci|su bili peti bombaöki napad.
{31522}{31584}äta je sa Zemljiönom|upravom u Dûeksonu?
{31585}{31644}Pa, tamo sam "izgubio|svoju nevinost".
{31645}{31703}To je bio prost posliÊ sa samo|nekoliko ötapova dinamita i fitiljem.
{31704}{31766}- Novinsko uredniötvo?|- Prava stvar.
{31767}{31827}- HiröË Templ?|- Najbolji do sada.
{31828}{31895}Krejmerova kancelarija?
{31941}{32059}- To je bila dobra bomba. Ali nisam|nameravao da ubijem bilo koga. - Stvarno?
{32060}{32135}Postavio si bombu u Dom za beskuÊnike|a tamo je spavalo öestoro ljudi.
{32136}{32212}Ali niko nije povreen, zato öto sam|bombu postavio u garaûu.
{32213}{32302}Ja ne pravim maötovite bombe.|One su samo jednostavne male stvari.
{32303}{32392}Ali ja znam gde da ih postavim. Kao öto sam|ti rekao, nisam nameravao da ubijem bilo koga.
{32393}{32475}- A blizanci?
{32558}{32606}értve rata.
{32607}{32657}Otac je izgubio noge?|Ubio se?
{32658}{32706}Ne ûelim da razgovaram o ovome.
{32707}{32798}Je`l ti krijeö neöto od mene?|Ne bih ti to savetovao.
{32799}{32843}Ja nemam öta da krijem.
{32844}{32924}Uradio sam ono öto sam morao.|Klan je bio u ratu.
{32925}{33008}I pobedili bismo, ali smo|poËeli da bombardujemo Jevreje.
{33009}{33090}Svim svojim novcem su potkupili|F.B.I., i pobedili nas.
{33091}{33149}Samo smo trebali da nastavimo|da Ëistimo Ëamuge.
{33150}{33203}Svet bi bio drugaËiji.
{33204}{33271}Da, moûeö da se pretvaraö|da si sav uvreen ovim.
{33272}{33347}Ali duboko unutra,|obojica znamo...
{33348}{33405}postoji deo tebe koji se|slaûe sa mnom.
{33406}{33451}Sereö.
{33452}{33537}Zaöto postajeö toliko osetljiv?|äta krijeö?
{33538}{33604}- Ja niöta ne krijem.|- Ma kako da ne.
{33605}{33697}Voziö svoj auto i neki|pijani crnac ti preseËe put,
{33698}{33747}dok njegova geto muzika treöti.
{33748}{33799}äta pomisliö?
{33800}{33861}"Dovraga ti afro-amerikancu." Ne.
{33862}{33925}Ti misliö "crnËuga."
{33948}{33997}Da imaö imalo petlje,|i rekao bi tako.
{34181}{34246}VratiÊu se sutra.
{34247}{34323}Povredio sam tvoja mala oseÊanja,|jesam li? A?
{34357}{34438}äta si oËekivao da Êeö naÊi ovde?|Starog dobrog dedicu?
{34439}{34509}OËekujeö od mene da jecam|i da te ljubim u dupe...
{34510}{34553}- i pevam psalame oproötaja?
{34554}{34618}- Ne znam öta sam oËekivao.|- Naravno da znaö.
{34619}{34665}- UnuËe.
{35063}{35166}- Zdravo. Ja sam Nora Stark, zastupniËe Hol.
{35167}{35222}Ja na neki naËin Ëistim|za guvernerom Mekalisterom.
{35223}{35318}- Adam, molim vas.|- Adam Êe i biti.
{35319}{35415}Vrlo sam radoznala, Adame. Da li znate|da su identiËne stavke podignute...
{35416}{35463}u nereöenoj i uzaludnoj|advokatskoj molbi...
{35464}{35518}odbijene od strane drûave Teksas|baö proölog meseca?
{35519}{35583}U stvari znam.|Moje je miöljenje, premda,
{35584}{35672}da je Teksas miljama ispred Misisipija|u puno stvari, ukljuËuljuÊi glupost.
{35673}{35739}- Ja sam optimista.|- `Bro jutro, savetniËe.
{35740}{35804}- Dobro jutro, vaöa visosti.|- Dobro jutro.
{35863}{35920}Ovo je ozbiljan posao.
{35921}{36047}Krajnji cilj, nepovratna kazna|za Ëoveka.
{36048}{36168}A vreme je najËistije zlato.|Kada planirate da podnesete ûalbu?
{36255}{36332}»udno, planirao sam da Ëekam da|sud da donese odluku...
{36333}{36392}pre nego öto je podnesem,
{36393}{36454}Visosti.
{36455}{36567}Meutim, ako, kako je oËekivano,|uh... »etvrtak.
{36612}{36677}- A odgovor drûave?|- Slaûemo se.
{36678}{36775}- Da. - Uobraûen mladi advokat|preko puta neÊe predstavljati...
{36776}{36841}dodatna pitanja na ovu ûalbu.|- OËigledno ne.
{36842}{36934}Uh, petak... ujutru.
{36935}{37001}ImaÊete moju odluku u petak.
{37049}{37136}Moûe li sud da oËekuje|dodatne dopune?
{37137}{37229}Je`l vi mene pitate za|moju pravnu strategiju, visosti?
{37230}{37275}Nipoöto, gospodine.
{37276}{37352}Ali me uzbuuje saznanje|da je imate.
{37353}{37399}Moûete svi da idete. Sada.
{37494}{37543}Karl. Kako si?
{37544}{37621}Adame. Popustljivost?
{37622}{37707}- Ja sam ugovorno obavezan da ne pitam.|- Nisi.
{37708}{37816}Ali hoÊeö. Vidiö, guverner|je Ëovek bez imalo predrasuda.
{37817}{37864}On niöta ne iskljuËuje.
{37866}{37925}To öto postajeö advokat|sigurno Ëini Sema ponosnim.
{37926}{38000}Pa, guveneru, od svih ljudi, vama bi trebalo|da je poznato njegovo vienje te profesije.
{38001}{38052}Meutim, ja bih se najradije|drûao teme...
{38053}{38102}ovog razgovora, i po dogovoru,|ostvio bih ga nezvaniËnim.
{38103}{38183}Shvatam da ponovo razmatrate|presudu za ubistvo...
{38184}{38229}mog klijenta.
{38230}{38317}- Adame, da l` ti smeta?|- Ne, gospodine.
{38318}{38398}Adame, oËigledno sam radio vrlo|naporno i vrlo sam ponosan...
{38399}{38474}öto sam dobio osudu na kojoj su|dva prethodna tuûioca omanula.
{38475}{38569}Meutim, dokle god ne sumnjam da je|Sem Kejhol kriv za öta je optuûen,
{38570}{38636}uvek mi je jako teöko da|poverujem da je delovao sam.
{38637}{38726}I kao öto znaö, nikada nije bio|ûeljan da pomogne sebi u tom pogledu.
{38727}{38831}ät-äta vi to taËno hoÊete da kaûete?|Postoji li neöto posebno öto vi znate?
{38832}{38888}Ne. Naravno da ne.
{38889}{38955}Samo hoÊu da se uverim da|da je pravda zadovoljena.
{38980}{39086}Shvatam.|ZnaË da ako bi ja nekako saznao-
{39087}{39158}Adame, ja svoju moÊ|da odluËujem...
{39159}{39254}da li Ëovek treba da ûivi|ili umre shvatam vrlo ozbiljno.
{39255}{39350}- Ako bih na neki naËin mogao da budem|ubeen da se tvoj klijent isto tako oseÊao-
{39351}{39457}éao mi je öto poûurujem. Nora, pomozi|Gospodinu Holu na sve moguÊe naËine.
{39458}{39551}- Bilo je lepo upoznatite.|- I meni takoe.
{39616}{39698}- Da pogodim.|Nisi ubeen da je iskren.
{39699}{39786}- Dozvoli mi malo blagog skepticizma.|- Svakako.
{39787}{39832}Meutim, nezvaniËno,|i drûeÊi se teme,
{39833}{39899}data ti je prilika da|snabdeö guvernera pokriÊem.
{39900}{40023}- Volim politiku. - Jer ako on|odloûi pogubljenje bez razloga,
{40024}{40075}sa jedne strane izgledaÊe|isto kao svoj prethodink.
{40076}{40125}Sa druge strane izgledaÊe|mekan u odnosu na zloËin.
{40126}{40204}A s obzirom na to da je on taj|koji je pridobio osudu u startu,
{40205}{40250}on gleda na svet ili crno ili belo.
{40251}{40337}Tako da ako ja iznesem nove informacije,|to mu omoguÊava da sluöa svoju savest.
{40338}{40383}Recimo da to proöiruje|njegove moguÊnosti.
{40384}{40458}Da bih ti to olaköao, postavljena si|za mog novog najboljeg prijatelja.
{40459}{40567}- Tako neöto.|- Pa, drugarice, nameravam da|pobedim u ovom sluËaju u sudnici.
{40568}{40612}- U toliko bolje.|- To neÊe stiÊi do guvernera.
{40613}{40683}Naravno.|Ako ti je uopöte potrebna pomoÊ,
{40684}{40752}to je kuÊni broj,|to je u kancelariji.
{40753}{40807}Nazovi me.
{41918}{42002}Pronaöao sam ovo u svojoj|hotelskoj sobi sinoÊ.
{42003}{42085}"Dobrodoöao Diksi. Molim te pokuöaj|da ostaviö sve onako kako si naöao."
{42182}{42229}Meni to zvuËi kao lepo ponaöanje.
{42230}{42280}Bilo je prikaËeno na|tajmer bombe laûnjaka.
{42384}{42432}äta?
{42473}{42534}ät-äta misliö da bih trebao|da uradim povodom toga?
{42535}{42588}Zabole me.|Ja mislim o tome...
{42589}{42674}kako taj gas koji Ëe me|primorati da udahnem...
{42675}{42749}izaziva ekspolziju Ëovekovih pluÊa|i njihovo izletanje kroz usta.
{42843}{42918}äta nameravaö da preduzmeö?
{42967}{43037}NastupiÊemo okrutno i neuobiËajeno.
{43038}{43127}Au, tri godine na MiËingenskim Pravima,|i ta jadna ideja je najbolje öto si smislio?
{43128}{43226}1984, zakonodavno telo je usvojilo|zakon kojim se menja naËin egzekucije...
{43227}{43270}sa gasne komore|na smrtonosnu inekciju.
{43271}{43394}Taj zakon se odnosi samo na one|koji su osueni posle 1984.
{43395}{43460}Ja sam poslat ovde 1980.
{43461}{43554}- Sada, öta hoÊeö da kaûeö, do avola?|- Vidim da poznajeö zakon.
{43555}{43637}»itam sve smrtne presude.|Baö kao i ti.
{43638}{43743}- Piöem neke sudske naloge za ljude koji.|Ëekaju izvröenje presude. - Jesi li imao|neku odloûenu presudu do sada?
{43744}{43848}onda zarûi svoje ökolske pravne savete|za sebe, i pusti me da radim svoj posao.
{43849}{43936}Time öto je drûava promenila smrtonosnu|inekciju da bude humaniji metod,|drûava je de fakto priznala...
{43937}{43994}da je gasna komora|okrutan metod egzekucije.
{43995}{44066}Smem li da te podsetim zastupniËe,|govoreÊi kao osuenik na gasnu komoru,
{44067}{44131}biÊu isto toliko mrtav|u oba sluËaja.
{44132}{44204}Pre ili kasnije, da.|Ali ja bih pre reakao kasnije.
{44205}{44309}Pucam od poverenja! Gubim bolje|ûalbe od ove veÊ 16 godina.
{44310}{44390}OseÊam se kao oni belci-|koji uvek gube od crnaËkih svetskih putnika.
{44479}{44537}Zaöto se moj otac zarazio|ovim sranjem?
{44538}{44621}O, sada Êemo da razgovaramo|o naöem Ediju, hmm? BiÊu oprezan.
{44622}{44683}Pa, uniötio si ga. HoÊu da kaûem,|mora da se jako lepo oseÊaö zbog toga.
{44684}{44768}Ja niöta nisam uniötio.|Nikada nije pokuöao da shvati klan.
{44769}{44867}- Bili smo u pravu.|- O, joö uvek misliö da ste bili u pravu?
{44868}{44961}- Vidi öta sada imaö: sidu, drogu|i decu kopilad. - PËele ubice?
{44962}{45060}- Doöle su iz Afrike, zar ne?|- Juûna Amerika. Ali i to je|verovatno dovoljno blizu za tebe.
{45061}{45158}- Zaöto radiö ovo? - Zato öto bi mi ûivot bio|mnogo laköi kada bih samo mogao da te mrzim.
{45159}{45223}Ali ne moûeö, zar ne? Zato öto|sam jednostavno previöe simpatiËan.
{45224}{45288}Pa, radim na tome.
{45289}{45340}Hriste, imaö deset godina kada tvoj|otac izvröi samoubistvo ispred tebe,
{45341}{45413}a onda odeö na sahranu i saznaö|da ti je deda joö uvek ûiv.
{45414}{45485}Strava! Sa izuzetkom da je on|rasista, oloö, i ubica dece!
{45486}{45598}- Zar to nije uteöno?|- O, stani. Srce mi slamaö.
{45642}{45691}Tvoja mrûnja je bila ono|öto ga je oteralo, zar ne?
{45748}{45797}Edi je bio slab.
{45832}{45904}Nikad nisam digao ruku na njega.
{45905}{45961}Nikada ga nisam pojurio.
{45962}{46043}Nikada nisam brinuo ko su|njegovi prijatelji. »ak ni Kvins.
{46044}{46103}Ko?
{46104}{46217}Kv-Kvins Linkoln, mali crnja sa|kojim se Edi svojevremeno igrao.
{46218}{46294}- »ekaj malo. »uo sam to ime pre.|- Niöta to ne znaËi.
{46295}{46360}Kvins Linkoln. On je pominjao to|ime. On je imao nekakve Ëini.
{46361}{46430}- Provodio bi i po tri dana u svojoj sobi|mumlajuÊi neku priËu... - NaredniËe Peker!
{46431}{46518}- o Kvinsu Linkolnu. - To niöta ne|znaËi. Prekini da govoriö o tome.
{46519}{46584}- NeÊu. Ko je- - To niöta ne|znaËi! Prekini da govoiö o tome!
{46654}{46737}Idemo, Sem.
{46738}{46820}- Hajde.
{46948}{46999}- Da.|- Jesi li spavao?
{47000}{47072}- Ne, budan sam.|- Ne pitaj me kako znam,
{47073}{47143}ali sud Êe odbiti|nedelotvornu preporuku.
{47144}{47294}Da, to sam i oËekivao. Uh, pa, biÊu|spreman da podnesem ûalbu u Nju Orleansu...
{47295}{47320}kada sud ovde donese odluku.
{47321}{47387}OËekivaÊu tvoj prvi potez ujutru.|Laku noÊ.
{47837}{47916}- Zdravo.|- Nora.
{47917}{48000}- ∆ao. - Da li ponuda za pomoÊ|joö uvek stoji?
{48001}{48046}Naravno.
{48047}{48151}Moram da pronaem F.B.I. agenta|koji je bio zaduûen za Semov sluËaj.
{48202}{48271}Sem nije bio naöa briga,|razumeö?
{48272}{48379}Nije bio umeöan u stvarno gnusne|stvari, tako da ga nismo pomno pratili.
{48380}{48449}Kada se to promenilo?
{48450}{48560}Kada su nestali socijalni radnici,|Huver nam je gnevno dao sluËaj.
{48561}{48604}Rasprostreli smo novac na sve strane.
{48605}{48724}Ti ljudi su u osnovi bili najobiËnije|neznalice, znaö. Nisu imali kinte.
{48725}{48833}- Tako da smo se molili da oni|ûude za novcem. Nastavi.
{48834}{48944}Hej. O nekim stvarima mogu da|razgovaram, a o nekim ne mogu.
{48945}{49051}A postoje neke stvari o kojima neÊu|da razgovaram, jer ne volim kada vi|advokati izvrÊete istinu,
{49052}{49138}i oslobaate ubice na osnovu nekih|glupih greöaka u istraûnom postupku.
{49139}{49259}To je sranje. Pored toga,|kasno je za nove informacije, momak.
{49260}{49330}Sudovi neÊe hteti da Ëuju.|Ti to znaö.
{49331}{49396}Sudovi nemaju zavrönu|reË u ovom sluËaju.
{49397}{49503}Pored toga, kaûeö da nije bio umeöan u gnusne|stvari. Nema öanse da mu je namera bila da ubije.
{49504}{49572}Naravno da je nameravao da ubije.
{49573}{49636}Marvin Krejmer je bio|rob navika.
{49637}{49724}Bio je u kancelariji|svako jutro pre 8:00 sati.
{49725}{49780}Bomba je eksplodirala|taËno u 8:00 sati.
{49781}{49834}Tajmer je bio nasetovan na 8:00 sati.
{49861}{49908}To nikada nije predstavljeno|na suenju.
{49909}{50001}Hej, nema pomoÊi ako prokleti advokati to|nisu iskoristili. To je bilo u naöem izveötaju.
{50026}{50077}E pa, ûeleo bih da vidim taj izveötaj.
{50078}{50170}E pa, u tome ne mogu da ti pomognem.|Ja sam sada samo ribar,
{50171}{50218}koji bi öto pre ûeleo da ga|vidi pogubljenog.
{50250}{50335}Bio sam okruûen tim nasilnim|seronjama ceo svoj ûivot.
{50336}{50398}Neka osete malo nasilje na|svojoj koûi.
{50399}{50475}Da vidimo koliko su|hrabri bez svojih maski.
{50510}{50566}Znaö o Ëemu govorim.
{50658}{50749}Zaöto naö prijatelj iz F.B.I.- a ne bi ûeleo|da nam kaûe neöto o sluËaju starom 30 godina?
{50750}{50822}Zato öto si sada u Misisipiju.|Zemlji tajni.
{50823}{50885}Ima tela pokopanih na sve strane.
{50886}{50987}Ali niko ne pokuöava da sakrije bilo öta o|Semu. Ne moraju. On je to uradio.
{50988}{51049}Oni samo ne ûele da ti|prosejavaö stare dokaze,
{51050}{51109}jer nisu sigurni öta|joö moûeö da otkrijeö.
{51110}{51172}- Ko su "oni"?|- Svi.
{51173}{51231}Niko. Kakve ima veze?
{51232}{51347}Pa, moûda i te kakve.|Mislim, uzmimo tebe, za primer.
{51348}{51408}Jesi li ti stvarno tu da|mi pomogneö?
{51409}{51473}Ili su te "oni" zaduûili|da me öpijuniraö?
{51626}{51676}Jesi li ikad Ëuo za|Komisiju Suverenosti?
{51677}{51773}- Jedva.|- Pa, ne postoji viöe.
{51774}{51879}PoËeli su sa radom 50-ih godina. To je bila javna|drûavna agencija namenjena drûavnim pravima,
{51880}{51937}tj., borbi za socijalna prava.
{51938}{52022}Neki ljudi misle da je u stvari|koordinirala svim graanskim veÊima belaca.
{52023}{52086}- äta su ta veÊa bila?|- Svaki grad je imao jedno.
{52087}{52165}Lokalna grupa poötovanih belaca-
{52166}{52263}profesionalaca,|stubova njihove zajednice-
{52264}{52308}koji su govorili klanu|öta da radi.
{52349}{52410}ZnaËi da neko nalik Semu|Ëak nije ni donosio odluke.
{52411}{52490}Kao öto je rekao naö prijatelj|iz F.B.I., oni su bili siromaöni,
{52491}{52609}neobrazovani ljudi koji nisu bili sposobni|da nau svoja dupeta uz pomoÊ mape.
{52610}{52719}- Gradska veÊa su ih upotrebila da obave njihova|prljava posla. - A Komisija Suverenosti?
{52720}{52787}Oni su Ëuvali arhive.
{52834}{52904}- Seme, molim te potpiöi ovo.|- Ja niöta ne potpisujem.
{52905}{52978}Ovi dokumenti su zapeËaÊeni od drûavnog|zakonodavnog tela. Kao osuenik na smrtnu kaznu,
{52979}{53033}ti i samo ti moûeö da podneseö|molbu da se tvoje arhive otvore.
{53060}{53121}Trebao bi da umreö za 20 dana.|Ovo bi moglo da pomogne.
{53122}{53202}- Pomogne njemu, moûda. Ne meni.|- Pomogne kome?
{53203}{53265}Guverneru, tupadûijo jedan.|Zar ne shvataö?
{53266}{53339}On ne moûe sam da otpeËati arhive, pa zato|upotrebljava tebe da to uradiö umesto njega.
{53340}{53392}Zaöto? Da bi pomogao meni?
{53393}{53496}On me je ovde smestio. Ne. On samo|lovi ono öto svaki politiËar ûeli:
{53497}{53566}Prljavötinu na svojim neprijateljima.
{53567}{53640}»ega ima u tim arhivama, Sem?
{53641}{53743}NiËega za tebe. Ne, to neöto öto bi oni|upotrebili da maltretiraju i povreuju moj narod.
{53744}{53793}Ja sam tvoj narod.
{53794}{53859}Zar ne shvataö? Ja sam.
{53860}{53949}Ti nisi moj stvarni narod.|Ti nikada nisi ni upoznao moj pravi narod.
{54024}{54094}Ne znam odakle im priËa.
{54095}{54165}Samo je pitanje vremena pre|nego öto dou do mene.
{54166}{54283}éao mi je. Ali moûda sam na dobrom putu.|Pratim neke stre tragove.
{54284}{54337}Za ime Boga, Adame.|Ostavi se toga.
{54338}{54397}Li, stvarno mislim da|mogu da ga spasem.
{54437}{54500}Je`l ti ikad palo na pamet da|on moûda nije vredan spasavanja?
{54501}{54594}- Ne misliö valjda stvarno tako.|- U redu, Adame.
{54595}{54678}HoÊeö li da saznaö proölost?
{54679}{54746}Sada Êu da ti priËam o proölosti.
{56482}{56537}Ovo je bilo moje drvo.
{56700}{56751}Moje liËno...
{56752}{56802}Lovorovo drvo.
{56860}{56937}Bila sam tamo gore.
{57047}{57129}Tvoj otac je bio tamo,|sa Kvinsom.
{57177}{57226}Imali su osam godina.|Moûda devet.
{57227}{57274}I bili su najbolji prijatelji.
{57413}{57502}Tukli su se i öutirali, i pravili|su toliku buku da je tata Ëuo...
{57503}{57567}i izaöao da vidi|kakav je to meteû.
{57568}{57630}Je`l me Ëujeö? Nastavi. Nastavi.
{57631}{57677}Marö kuÊi!
{57678}{57753}Kvinsov otac je radio|na nadnicu za tatu.
{57754}{57840}Zvao se Dûo. Tata nikada nije|bio spretan sa mehanikom,
{57841}{57926}pa je Dûo popravljao stvari za nas,|pravio je stvari.
{57927}{57991}O- On je bio ovde, stalno.
{57992}{58080}Pa se onda Kvins vratio|sa svojim ocem.
{58082}{58156}Moj sin, Kvins,|kaûe da si ga tukao.
{58157}{58227}Ozbiljno su se tukli.|Kao ûivotinje.
{58228}{58332}U jednom trenutku,|tata je dohvatio grabulje.
{58333}{58378}I stvari su izmakle kontroli
{58427}{58490}Oborio je Dûoa.|Dûo je pao na zemlju.
{58491}{58550}Vikao je Kvinsu da trËi|i donese njegovu puöku.
{58551}{58589}Idi po moju puöku!
{58590}{58678}Sem je rekao Ediju da donese njegovu.|Edi se zamrzao.
{58679}{58725}Ali, tata ga je naterao da ode.
{58758}{58845}Dûo... je bio ovde.
{58870}{58916}Tata je bio tamo.
{58917}{59019}- Ulazi u kuÊu. Hajde.|- Dûo je Ëekao svoju puöku.
{59020}{59072}O- On je gledao unaokolo.
{59073}{59139}Sem je imao svoju puöku.
{59140}{59233}A onda je moj dragi,|ljupki otac-
{59765}{59812}Ovo...
{59813}{59881}je bio Misisipi...
{59882}{59937}ranih 50-ih.
{59993}{60071}Tata je rekao "samoodbrana".
{60072}{60146}Nikada Ëak nije bio ni uhapöen.
{60147}{60221}Zbog Ëega su se moj otac i Kvins|tukli?
{60366}{60413}Oko vojnika igraËke.
{60414}{60499}Edi je mislio da ga je Kvins ukrao.
{60500}{60553}Te noÊi ga je pronaöao|pod svojim krevetom.
{60593}{60690}On je to jako teöko primio.
{60691}{60752}I onda je rekao...
{60753}{60817}Ja...
{60818}{60891}sam takoe ubio Dûoa Linkolna.
{61011}{61100}Rekao je:"Da si plaËuÊi molila tatu|da prekine,
{61136}{61216}nema öanse da bi on pucao".
{61217}{61290}Nikako a da to posmatra|njegova mala devojËica.
{61388}{61436}Naravno, bio je u pravu.
{61539}{61601}Bila je moja krivica takoe.
{61917}{61997}Moja je!
{61998}{62075}Marö kuÊi!
{62076}{62132}Kvinse! Kvinse!
{62327}{62384}Pomozi mi, Kvinse.
{62385}{62440}Donesi moju puöku!
{62555}{62659}Tata baö i nije bio spretan sa mehanikom.
{62680}{62740}Isuse!
{62809}{62906}Upravnik ûeli da zna da li si|razmiöljao o svom poslednjem obroku.
{62907}{63009}- Mmm.|- Posebni zahtevi mogu da traûe vreme.
{63010}{63065}Da, hoÊu, uh...
{63066}{63153}Ëiniju Eskimo sladoleda|i francusku kafu.
{63154}{63210}DobiÊeö.
{63211}{63262}Bilo je pet pogubljenja od kako|si ti ovde, Sem.
{63264}{63314}Jesu li ti poznati problemi|sa nekim od njih?
{63315}{63371}Hajde.
{63372}{63449}Svi su umrli na 50 stopa od mene.
{63450}{63524}Svi na listi Ëekanja znaju|sve o svakom pogubljenju.
{63525}{63597}Onda mi priËaj o Tediju Miksu.|HoÊu svaki detalj.
{63651}{63716}Nisu znali öta rade.
{63718}{63774}Sve je poölo naopako.
{63775}{63828}Jesi li video komoru?
{63829}{63917}- Ne joö. - E, postoji|sobica s jedne strane...
{63918}{64029}gde dûelat ide da smuÊka|svoj rastvor sumporne kiseline.
{64030}{64112}U Miksovom sluËaju,|dûelat je bio pijan.
{64113}{64179}- Ma daj.|- Bio je pijan.
{64219}{64305}U svakom sluËaju.
{64326}{64405}Njegova prva koliËina|rastvora nije imala efekta.
{64406}{64473}I Miks je zadrûavao dah|koliko god je mogao.
{64474}{64539}Onda je udahnuo|i niöta se nije desilo.
{64540}{64592}Tako da su Ëekali.
{64593}{64651}Miks je Ëekao.|Svedoci su Ëekali.
{64652}{64727}I polako, okretali su se|prema dûelatu,
{64728}{64773}koji Ëeka i psuje.
{64774}{64825}On se konaËno vraÊa u svoju sobicu,
{64826}{64901}meöa novu koliËinu sumporne|kiseline i povlaËi polugu.
{64902}{64976}Ovog puta sumporna kiselina|kaplje tamo gde bi i trebalo.
{64977}{65041}PovlaËi drugu polugu,
{65042}{65089}ispuötajuÊi kuglice cijanida.
{65090}{65202}Naravno, ovaj gas poËinje|da se isparava naviöe...
{65203}{65311}gde stari Tedi ponovo zadrûava|dah.
{65368}{65464}Tako on napokon udiöe|gas punim pluÊima...
{65465}{65528}i poËinje da se trese i trza.
{65529}{65619}Pa, negde ili drugde|tamo postoji- metalni stub...
{65620}{65709}koji se spuöta od plafona|komore pa sve do poda,
{65710}{65781}i nalazi se direktno iza - stolice.
{65782}{65841}I-
{65990}{66070}I baö kada je Miks postao|stvarno miran...
{66071}{66125}i kada su svi mislili da je mrtav,
{66126}{66204}njegova glava poËinje da se trza|napred-nazad i udara u taj stub.
{66205}{66305}Jednostavno je razbijajuÊi samo tako.
{66306}{66407}OËi su kolutale i öiroko|je otvorio usta.
{66408}{66479}Penio je na usta.
{66480}{66527}I tamo je,
{66562}{66649}samo udarao glavom u taj stub.
{66719}{66767}Bilo je odvratno.
{66805}{66852}Koliko im je trebalo da ga ubiju?
{66853}{66958}Prema izveötaju zatvorskog doktora,|smrt je bila trenutna i bezbolna.
{66960}{67064}Peker mi je rekao da su to bili|najduûih pet minuta njegovog ûivota.
{67065}{67151}»ovek se zgrËio i povraÊao...
{67152}{67199}i lupao svoju glavu toliko dugo...
{67200}{67285}da su delovi njegovog mozga|öikljali iz njegovog temena.
{67634}{67694}Na koji naËin poluga koja se povlaËi|aktivira kanister sa cijanidom?
{67732}{67801}- äta? - Poluga. Je`l radi|sa öarkom ili oprugom?
{67802}{67881}- Ne znam. - Pa, je`l je samo|gravitacija vuËe na dole?
{67882}{67937}Kako bih ja to|do avola mogao da znam?
{67938}{67992}Mislio sam si talentovan|za takve stvari.
{67993}{68085}E pa, tuûi me.|Nisam mehaniËar.
{68086}{68142}To je i Li rekla.
{68143}{68213}Ali si bio dovoljno spretan da|napraviö bombu i ubijeö Krejmer blizance.
{68214}{68278}KuËkin sine.|Je`l sve ovo zbog toga?
{68279}{68376}Mora da si bio budan|celu noÊ razmiöljajuÊi o tome.
{68377}{68456}Izvini, sinak.|éao mi je öto te razoËaravam,
{68457}{68556}- ali, uh, bombe nisu toliko komplikovane.|- Ne mogu biti ni toliko jednostavne.
{68557}{68654}- Ja ne bih znao kako to da uradim.|- To je zato öto nemaö motiv.
{68655}{68726}U vreme kada sam odradio Krejmera,|bilo je vrlo jednostavno.
{68727}{68786}ZnaËi da samo zato öto si antisemit,
{68787}{68861}znaö kako da napraviö bombu,|strateöki je smestiö na drugi sprat,
{68862}{68912}zapaliö fitilj, i onda izaeö|bez ikakvog rizika po sebe.
{68913}{68988}Rizika je puno.|A slave malo.
{68989}{69109}I bio je prvi sprat. Bomba je eksplodirala|ipod njih. Proveri izveötaj F.B.I.- a.
{69110}{69157}- I jesam.|- äta je pisalo?
{69158}{69240}Bomba je eksplodirala ispod njih.
{69241}{69308}Hvala ti puno. Mogu li ti|pomoÊi oko joö neËeg?
{69309}{69386}- Koliko je fitilj bio dugaËak?|- Za ime Svetog Petra.
{69387}{69461}Znaö, to se desilo jako davno.|Ja-ja sam star Ëovek.
{69462}{69523}Moje pamÊenje nije baö toliko savröeno.|Skini mi se s vrata. HoÊeö li?
{69524}{69598}O, siguran sam da moûeö da se|setiö ubistva dvoje dece.
{69599}{69669}Dovoljno dugaËak da bih mogao|da zbriöem odatle. U redu?
{69670}{69781}Osim jedne stvari. Bomba nije|imala fitilj. Imala je tajmer.
{69782}{69902}- äta hoÊeö da kaûeö? - HoÊu da kaûem|da nisi bio sam. Sa tobom je bio joö neko.
{69903}{69990}Nema teorije da si samostalno mogao|da napraviö tempiranu bombu.
{69991}{70050}F.B.I., pretraûili su tvoju|kuÊu, tvoju- tvoju garaûu.
{70051}{70146}Nisu naöli jedan jedini trag|eksploziva bilo gde.
{70147}{70212}Pa, moûda su glupi.
{70213}{70285}Moûda sam bio baö oprezan i|nisam ostavio trag.
{70312}{70362}Da. I moûda je neko drugi|podmetnuo bombu.
{70526}{70574}Ti nemaö pojma öta radiö.
{70661}{70724}Sasluöaj me samo.|Sem nije umeo da napravi tajmer.
{70725}{70787}Njegove bombe su bile proste.|Imale su fitilje.
{70788}{70841}Ova je bila drugaËija.|Bila je sloûena.
{70842}{70919}- Bila je tempirana. Bila je tempirana|da ubije. - U redu. SaËekaj malo.
{70920}{70989}Sem nije postavio bombu.|On nije ubio tu decu.
{70990}{71047}SaËekaj!
{71104}{71225}Komisija Suverenosti ima arhivu o Semu.|Moûe nam reÊi ko je joö bio umeöan!
{71226}{71270}Ko vuËe konce, donosi odluke.|Adame, prekini sa ovime. U redu?
{71271}{71322}Drûavno zakonodavno telo je|zapeËatilo te arhive.
{71323}{71397}Ako tvoj klijent neÊe da potpiöe, ne|moûeö navuÊi sud da ih odpeËati.
{71398}{71471}- Kladim se da znaö naËin na koji|moûemo da zavirimo u njih. - Ne.
{71472}{71529}- Rekla si da hoÊeö da mi pomogneö.|- Pomaûem ti.
{71530}{71587}- Moûda bi trebala da uradiö viöe.|- Moûda ne mogu da uradim viöe.
{71588}{71695}Nora, ako ima drugih,|i umeöana si ötiteÊi ih-
{71696}{71760}Ja-
{71761}{71808}Je`l ti to meni pretiö?
{71809}{71875}Ja traûim istinu svim|raspoloûivim sredstvima!
{72007}{72098}äto ukljuËuje i...|uËtiv zahtev za tvoju pomoÊ.
{72273}{72343}Kao dodatak na okrutan i neuobiËajen|nastup, hoÊu da podnesem novi predlog.
{72344}{72403}Bilo je vreme da poËneö da se|usredsreujeö na zakon, sinak.
{72404}{72461}Nikad nisam prestajao da se|usredsreujem na zakon, sinak!
{72462}{72524}Ali ne postoji niöta öto neÊu|isprobati u nameri da dobijem odlaganje,
{72525}{72571}ukljuËujuÊi i da dokaûem da si lud.
{72572}{72630}- Ja sam lud?|- Tako je.
{72631}{72706}DokazivaÊu da je kao rezultat prisustva|mentaliteta klana u tri generacije,
{72707}{72815}tvoja nesvesna zadojenost mrûnjom i|izopaËenoöÊu nastala iz iracionalnog straha...
{72816}{72906}rezultovala smanjenjem mentalne|sposobnosti da razlikujeö dobro od loöeg.
{72907}{72996}DokazivaÊeö da sam lud zato öto|sam imao drugaËija politiËka verovanja...
{72997}{73057}od tebe i tvog oca...
{73058}{73143}zbog njegovih naivnih, crnaËki-naklonjenih|povreenih oseÊanja!
{73144}{73240}Pa, verovatno se neÊu sluûiti baö|tim reËima u svom iznoöenju Ëinjenica.
{73241}{73299}Samo Êu da saËekam i vidim|izveötaj psihijatra.
{73300}{73378}- O, znaËi ja Êu da idem kod psihijatra, je`l?|- Tako je.
{73379}{73424}Mmm. To je van pameti.
{73425}{73515}Ubiti dva petogodiönjaka zato öto je njihov|otac radio za socijalna prava je van pameti.
{73546}{73593}Nikad nisam hteo da ubijem tu decu.
{73594}{73654}To je lepo.|Ali to je neöto zbog Ëega bi ti...
{73656}{73715}trebao da budeö pogubljen|za taËno 14 dana.
{73846}{73895}U redu.
{73917}{73965}Dobro.
{73999}{74088}Moram s tobom da proËeöljam kroz|joö malo porodiËne istorije.
{74090}{74178}Neke stvari sam saznao od Li,|ali u tome postoji puno rupa.
{74589}{74654}Sada joj je jako teöko.
{74655}{74735}Pokuöao sam da je pozovem kada sam|video ovo, ali se ona nije javila.
{74832}{74912}Mislim da je ponovo poËela da pije.
{74941}{75004}Jesi li si znao da je|ona alkoholiËar?
{75152}{75260}Jeste li ikad osetili pokajanje|zbog nekog od svojih zloËina?
{75261}{75306}Ne.
{75344}{75437}Jeste li se ikad izvinili nekoj|od porodica svojih ûrtava?
{75490}{75538}Ne, kakva bi bila svrha toga?
{75578}{75627}Kakva vi mislite da bila svrha?
{75678}{75726}Nema svrhe.
{76381}{76448}Pekeru.
{76449}{76558}HoÊu da znaö da kada govorim|o tvom tvom narodu,
{76559}{76610}Ja-
{76611}{76660}Pa-
{76701}{76749}Razumem, Seme.
{78670}{78730}Po vaöem profesionalnom miöljenju,|da li Sem Kejhol...
{78732}{78791}ima neöto öto bi bar iz daleka|moglo da se nazove saveöÊu?
{78792}{78849}Nisam naöla takvih dokaza.
{78850}{78937}Doktore Bidous, po vaöem miöljenju,|da li je Sem Kejhol u dodiru sa stvarnoöÊu?
{78938}{79034}- Ne, nije.|- Hvala vam, doktore Bidous.
{79035}{79100}Nemam viöe pitanja,|visosti.
{79126}{79172}äta kaûe drûava?
{79173}{79233}Drûava poziva|narednika Klajda Pekera.
{79310}{79398}NaredniËe Peker, bi li ste stavili do|znanja ovom sudu koliko dugo...
{79399}{79454}ste na svojoj trenutnoj poziciji,|molim vas?
{79455}{79560}Vodim Êelije osuenika na smrt veÊ 15 godina,|gospodine, i Sem je bio sa mnom svo to vreme.
{79561}{79643}I da li ste tokom tog vremena|ikada posmatrali gospodina Kejhola...
{79644}{79691}kako pokazuje da moûda ima savest?
{79692}{79769}Da li je brinuo o oseÊanjima drugih ljudi?
{79770}{79880}O, da, gospodine. Svi znaju da|Sem ima stvarno loö stav prema crncima.
{79881}{79981}Ali baö pre neko veËe rekao mi je u|lice da kada govori takve stvari-
{79982}{80081}Recimo da je pokuöao da se izvini.|I Ëak nije ni rekao sve öto je hteo.
{80082}{80198}I to ga sigurno ne Ëini svecem.|Ali, za Sema, to je velika stvar.
{80199}{80267}On potpuno sigurno ima savest.|Da, gospodine.
{80268}{80353}I tokom svog tog vremena tokom|kojeg ste posmatrali gospodina Kejhola,
{80354}{80467}da li biste rekli da on zna|öta se deöava oko njega?
{80468}{80538}Da li biste rekli da je on izgubio,|uh, vezu sa stvarnoöÊu?
{80582}{80654}Pre par noÊi, bio sam u prolazu,|i on je rekao, "Klajde".
{80655}{80738}Nikada pre me tako nije oslovljavao,|tako da sam znao da je vaûno.
{80739}{80793}Mogu li da ti pomognem?|"Oko Ëega, Sem?"
{80794}{80913}I on je rekao, "HoÊu da umrem sam.|I hoÊu da umrem u pristojnoj odeÊi.
{80914}{80973}I hoÊu da jedem Eskimo sladoled.
{80974}{81031}I mogu li da vidim izlazak Sunca?"
{81032}{81118}Rekao sam, "To poslednje je na meni, Sem."
{81119}{81220}Tako sam ga izöunjao,|i dao mu sat vremena nasamo.
{81221}{81326}Gledao sam kroz prozor. Mislio sam da|Êe moûda da odlepi kada Sunce krene da izlazi.
{81327}{81399}Vidite, proölo je 15 ili 16 godina...
{81400}{81449}od kada je Sem poslednji|put video svanuÊe.
{81450}{81512}Ali je ostao sasvim pri sebi.
{81513}{81589}Po vaöem miöljenju,|zasnovanom na vaöim posmatranjima,
{81590}{81666}da li je Sem Kejhol u|dodiru sa stvarnoöÊu?
{81667}{81725}Sem?|Moûete da se kladite u to.
{81726}{81775}Hvala vam, naredinËe Peker.
{81776}{81861}- Hvala vama.|- Ponudite svedoka, visosti.
{81929}{81983}äta se dogaa u petom krugu?
{81984}{82063}- Danas u toku dana spada na ludilo.|- ∆ao.
{82064}{82139}- ∆ao. - Tu si znaËi.|äta je maldi gospodin Hol naumio?
{82140}{82222}- Niöta novo.|- Pokuöaj ponovo. Na Ëemu je radio?
{82223}{82304}- Svuda traûi nove informacije.|- Kakve informacije?
{82305}{82350}- Nora?|- Gospodine?
{82421}{82500}Da ti moûda ne spavaö sa njime,|je li?
{82502}{82592}- Ne.|- Onda mi reci kakve informacije?
{82594}{82683}- Bilo öta, sve. OËajan je.|- Gde traûi?
{82720}{82786}- Ne znam.|- Pa saznaj.
{82787}{82849}OËajni ljudi su opasni.
{82850}{82946}Moûda bi trebala da spavaö sa njim.
{83033}{83084}- Zdravo.
{83085}{83156}- Moûemo li da razgovaramo?|- Naravno.
{83195}{83244}Temi?
{83445}{83501}Komisija Suverenosti|Ëuva originalne dokumente...
{83502}{83567}pod kljuËem u zgradi arhiva.
{83568}{83649}Zaöto rasporeivanje na zone|ne moûe da saËeka do sutra?
{83650}{83722}- Pitaj guvernera. Ja volim svoj posao.|- Nora.
{83723}{83795}- Nora, Nora.
{83796}{83851}Ti si osoba koje se plaöim.
{83852}{83928}Bink, molim te.|Moram ovo da obavim veËeras.
{83929}{83992}ZakljuËaÊu umesto tebe.
{84049}{84118}- To je naöa mala tajna.
{84119}{84236}- Ti i ja. Laku noÊ.|- Uh-huh.
{84743}{84791}Ovuda.
{85993}{86042}"Komisije Suverenosti"
{86563}{86619}"Graansko VeÊe Belaca, Indianola."
{86731}{86781}Vrati to.
{87057}{87119}"Sa M.K. situacijom|treba iÊi do kraja."
{87120}{87179}- Marvin Krejmer.|- Ili Martin King.
{87180}{87261}"Advokatska kancelarija, 18 mart."|To je Marvin Krejmer.
{87262}{87333}- Kada je bio bombaöki napad?|- 28-og aprila.
{87409}{87478}"Izvröenje akcije usvojeno 2. septembra."|Zar nisi rekao si da je bila u aprilu?
{87479}{87539}To nije datum.|To je 9 prema 2.
{87540}{87587}- Isuse Hriste, glasali su.|- O moj Boûe.
{87588}{87687}- "Komisija je za posao odredila S.K."|- Sem Kejhol. äta je R.V.?
{87734}{87783}HoÊeö reÊi, ko je R.V
{88119}{88168}Zdravo. Hvala.
{88365}{88412}Vreme je za istinu, Sem. Pet dana.
{88413}{88530}OsuÊemo paljbu na vrhovni sud svime|öto nam je na raspolaganju, ali...
{88531}{88594}moram da znam ko je R.V.
{88728}{88815}Seme. Video sam Komisijine arhive.|Bio si sa nekim sa inicijalima R.V.
{88816}{88901}Vas dvojica ste bili zaduûeni da|raznesete Krejmerovu kancelariju.
{88902}{88983}Zaduûeni od strane istih ljudi koji nisu|preuzeli nikavku odgovornost za smrt te dece...
{88984}{89064}i, koliko ja vidim, neÊe preuzeti nikavu|odgovornost zbog onoga öto Êe se tebi desiti.
{89100}{89191}Verujem da se takvi|ljudi nazivaju kukavicama.
{89192}{89280}Razlog iz kog pokuöavaö da|ih zaötitiö je izvan mog shvatanja
{89346}{89395}Kao prvo,
{89422}{89487}ti mali balavi kuËkin sine,
{89488}{89589}ako li mi si ikad viöe tako budeö obratio,|iöËupaÊu ti srce i zabiÊu ti ga u dupe.
{89590}{89696}Drugo, da si proveo upola toliko|vremena uËeÊi da budeö advokat...
{89697}{89767}`mesto da glumiö Dika Trejsija,
{89768}{89835}Moûda bih imao öanse da|ne budem mrtav za pet dana.
{89866}{89956}Kako sada stvari stoje,|sve öto si pokuöao je propalo.
{89986}{90033}Omanuo si!
{90034}{90130}Sada ja moram da platim cenu.
{90131}{90205}Ti si promaöaj! Isto kao|öto je tvoj patetiËni otac bio.
{90206}{90286}Taj kuËkin sin nije|imao muda da ûivi.
{90287}{90341}Bio je gubitnik i zabuöant.
{90342}{90409}Jednostavno je odbacio svoj ûivot.
{90410}{90487}Kako li se samo usudio?
{90488}{90535}Odakle mu pravo|da uradi tako neöto?
{90536}{90626}- Nije bilo na njemu da ga odbaci!|Ja sam mu ga dao!|- Hej, hej, Seme!
{90627}{90698}Njegova majka mu ga je dala!|Bio je Boûiji!
{90699}{90769}- Nije imao pravo!|Odbacio ga je, do avola!
{90770}{90860}- Je`l me Ëujeö? Odbacio ga je!
{90861}{90950}- Zaöto bi to uradio?|- Hajde.
{91248}{91349}- Zdravo. Je`l kuÊi? Gospoica Li je|gore, odmara se. Ne moûe sada da se vidi sa vama.
{91388}{91436}Li?
{91472}{91545}Uh, gde si, Li?
{91546}{91592}Li?
{91627}{91676}Li?
{91709}{91773}Li?
{91955}{92011}O, Isuse.
{92336}{92421}SreÊni mali neÊak.
{92521}{92595}Jesam li ti ikad pokazala...
{92596}{92677}moju omiljenu staru|porodiËnu sliku?
{92711}{92807}Doi ovamo.
{92808}{92853}Idem.
{92881}{92930}Mmm?
{92963}{93043}Nikad nisam imala pravi album sa slikama.
{93044}{93151}Uglavnom zato öto nikad|nisam imala pravih slika.
{93152}{93197}Ovde. Doi ovamo.
{93359}{93446}Evo. Sada, evo ga.
{93447}{93516}Vidiö?
{93517}{93582}Bio je slatko malo dete, zar ne?
{93628}{93722}Jedini problem je,|to öto je bio odgojen...
{93723}{93782}da bude monstrum.
{93879}{93944}Treniran je od roenja.
{94070}{94132}Potomci smo duge loze...
{94133}{94209}pune mrûnje, Adame.
{94210}{94302}Zato ja pijem.
{94303}{94360}UËinim da sve to nestane.
{94361}{94427}Sada si ti ovde.
{94428}{94543}I to neÊe viöe da nestane.
{94644}{94708}Idi kuÊi.
{95067}{95127}Imam tri stvari da ti kaûem.
{95128}{95178}Pod jedan.|Ja sam tvoj advokat dok me ne otpustiö.
{95179}{95231}Ne odustajem.|Pod dva.
{95232}{95339}Onog dana kada si ubio Dûoa Linkolna,|tvoja slatka mala sedmogodiönja|Êerka je bila na lovorovom drvetu.
{95340}{95417}Posmatrala je kako njen otac|hladnokrvno ubija bespomoÊnog Ëoveka.
{95418}{95485}I pod tri.|Kvins Linkoln nikada niöta nije ukrao.
{95486}{95584}Moj otac je naöao tog vojnika igraËku|pod svojim krevetom, ali je bio|previöe prestravljen da ti kaûe.
{95585}{95678}Morao je da ûivi sa time|do kraja svog tuûnog ûivota.
{95679}{95783}Moûda ti nisi imao muda da staviö|taËku na ovo, Sem. Ali ja imam.
{95784}{95877}Ja Êu tome da stanem na kraj.|Imamo joö Ëetiri dana.
{95878}{95967}Ovo je naöa poslednja ûalba, pod|imenom "olaköavajuÊe okolnosti."
{95968}{96033}PriËaj.
{96062}{96116}PriËaj, Seme!
{96165}{96213}Umorio sam se od priËe.
{96271}{96379}Umorio sam se od buenja svakog jutra|znajuÊi da sam jedan dan bliûi smrti.
{96380}{96487}Umorio sam se od ûivljenja u kavezu,|umorio sam se od ovih usranih cigara.
{96488}{96546}Samo se molim da|Êu umreti od raka pre nego öto...
{96547}{96594}me uguöe.
{96624}{96716}Ali najviöe, umorio sam se od Ëekanja.
{96873}{96919}Samo me pusti da se odmorim.
{96920}{97011}Stvarno sam dirnut time öto se oseÊö|dovoljno bliskim da podeliö svoja|oseÊanja sa mnom, Seme.
{97012}{97059}Ali u ovom trenutku,|baö me zabole.
{97060}{97159}Isuviöe sam zauzet pokuöavajuÊi|da pobedim u ovom sluËaju.
{97160}{97217}A sada, poËni da priËaö!
{97260}{97308}Evo nekih sinonima za "olaköavajuÊe."
{97309}{97397}"Prikrivanje, zaslaivanje,
{97398}{97442}ulepöavanje."
{97443}{97510}Nema niËeg lepog u raznoöenju|dva blizanca na komadiÊe.
{97512}{97578}Nema nikavog prikrivanja nad|samoubistvom njegovog oca.
{97579}{97642}I nema zaslaivanja ove Ëinjenice:
{97643}{97739}Moj klijent je kriv,|i zasluûuje da bude kaûnjen.
{97793}{97876}"Razum krivca: da bi uradio neöto."
{97877}{97929}Sem Kejhol je uradio neöto.
{97930}{97985}Ali on ne zasluûuje|da bude ubijen,
{97986}{98063}zato öto je uËen od roenja da|mora da radi jednu stvar.
{98064}{98134}To je ono öto ovaj sud mora da shvati.
{98135}{98196}Nikada nije znao da je|imao druge potrebe...
{98198}{98255}osim mrûnje, netripeljivosti|i nasilja.
{98256}{98380}Njegovi ujaci su bili kjukluksovci, njegova braÊa,|njegov otac, Ëak i njegov deda.
{98381}{98483}Njegov pradeda je bio jedan od|suosnivaËa te mrske organizacije.
{98484}{98572}Nedavno sam video sliku|njega na linËu.
{98573}{98645}Imao je deset godina, a to|mu je bilo treÊe po redu.
{98680}{98753}Naravno ovo je uûasno.|To je- To je zlo.
{98754}{98838}Ali krv i smrt su servirani|nedeljom uz doruËak.
{98871}{98957}Njegov otac je ubijen na sahrani.|Moj klijen je to posmatrao.
{99014}{99107}Kako je sud nesumnjivo svestan,|moj klijent je takoe moj deda.
{99108}{99223}Sada bih voleo da vam ispriËam malo toplih|i Ëudesnih priËa o naöoj familiji.
{99224}{99268}Samo öto ne znam ni jednu.
{99302}{99413}U stvari, ja Ëak svog dedu ne|smatram ni iz daleka divnim.
{99438}{99488}Ali ovo znam.
{99489}{99543}Upravo one stvari koje ga|Ëine toliko mostruoznim...
{99544}{99629}su upravo razlozi koji olaköavaju,|da ga ova drûava ne pogubi.
{99630}{99696}Odgojila ga je njegova|porodica i ova drûava...
{99697}{99750}da postane Ëovek kakav je postao.
{99751}{99817}Kada je postao dovoljno star|da bira, nije imao izbora.
{99852}{99900}Ovo je tragedija Sema Kejhola.
{99957}{100069}To je tragedija koja je|veÊ uniötila tri ûivota.
{100106}{100173}U ime milosra,
{100174}{100276}ne dozvolite joj da ubije ono|öto je ostalo od njegovog ûivota.
{100682}{100752}Hvala vam öto ste|me primili ovako.
{100753}{100822}Zaöto ste ovde?
{100863}{100963}U nadi da Êete zatraûiti od|guvernera da pokaûe malo milsra.
{100964}{101022}ReÊi mu da ne ûelite|da moj klijent umre.
{101023}{101077}Ja i ne ûelim da on umre.
{101078}{101165}Ne ûelim.|Ali oseÊam da mora.
{101166}{101232}Vidite, to-|to nije istina. Nije.
{101233}{101301}Vaöa reË bi imala veliki|uticaj na guvernera,
{101302}{101387}i niko bolje od vas ne zna da|je veÊ bilo dovoljno patnje.
{101388}{101457}Sve bi moglo da se zavröi ovde.|Sada.
{101512}{101620}Nisam ih odvela u obdaniöte tog|jutra jer mi je bilo muka.
{101621}{101728}Tako da sam ima mahala|sa prozora moje spavaÊe sobe...
{101729}{101805}i posmatrala ih kako|skakuÊu u svoju smrt.
{101806}{101864}∆ao, mama! Volim te!
{101865}{101918}Sve je bila moja krivica.
{101919}{101977}Budite dobri!
{102028}{102092}- Adame.|- Gospo?
{102093}{102158}Zaöto si ti stvarno ovde?
{102370}{102499}Doöao sam kuÊi jednog dana i zatekao|svog oca na podu sa piötoljem u ruci.
{102500}{102604}I seÊam se kako sam se pitao:|"äta svi ti peökiri rade tu?"
{102643}{102762}I onda sam shvatio da je|poreao peökire u krug...
{102763}{102831}i onda vrlo paûljivo...
{102832}{102907}legao u sredinu tako da|ne bi napravio nered.
{102957}{103037}U svojoj poruci, je-|je rekao da me je voleo.
{103038}{103112}I da mu je ûao, i...
{103113}{103167}nadao se da Êu|jednog dana shvatiti.
{103168}{103267}I poruËio mi je da Êu ja morati da|se brinem o svojoj majci i sestri.
{103307}{103381}Pored njega na podu je|leûala plastiËna kesa za ubre.
{103382}{103490}Ja sam trebao da stavim peökire u kesu,|poËistim nered i pozovem policiju.
{103491}{103548}"Ne diraj piötolj,"|poruËio je.
{103549}{103603}"Poûuri pre nego öto devojke stignu kuÊi."
{103639}{103730}Vidite, izabrao je dan za koji|je znao da Êu ja tada prvi doÊi kuÊi.
{103771}{103819}Bilo mi je 10 godina.
{103844}{103917}Bilo bi mi drago|da vam pomognem, Adame.
{103918}{103986}Molim te znaj ovo.
{103987}{104053}Sem Kejhol je uniötio|naöe porodice.
{104054}{104132}Samo öto je moja|porodica prva umrla.
{104133}{104209}I ûao mi je...|ali on mora da umre.
{104210}{104279}Zaöto?
{104280}{104404}Mora da umre zato öto sam ja pila|öampanjac na svom roendanskom slavlju.
{104405}{104495}On mora da umre jer je|priËi potreban zavröetak.
{104546}{104665}On mora da umre jer- Mene nije|briga da li je ili nije imao izbora.
{104666}{104747}On je izabrao da|postavi bombu u tu zgradu.
{104748}{104793}I moja porodica je poginula.
{104951}{104999}Znaö, oni su tada bili tvojih godina.
{105061}{105162}Mmm. I bili bi tvojih godina sada.
{105961}{106018}Nisi odustao, zar ne?
{106085}{106185}Ponekad - jednostavno volim da proverim|da li joö uvek imam ono öto je potrebno.
{106186}{106286}- Isuse. äta ti radiö ovde?|- Posmatrao sam te mali.
{106287}{106332}Zasluûujeö Ëinjenice.
{106369}{106487}Te davne 67., pronaöao sam starog pijanca.|Bio je peraË sudova.
{106488}{106605}Tvrdio je da je noÊ pre Krejmer bombaökog napada,|video Sema u restoranu sa joö jednim tipom.
{106606}{106667}Potrebno mi je ime.
{106668}{106754}Opis se poklapao sa tipom u|koga smo uvek sumnjali, ali-
{106755}{106821}R.V.
{106822}{106882}Hej! Roli Vedû.
{106986}{107083}On je bio pravi mrzitelj. Ali pametan. I|nikada nismo mogli da ga poveûemo sa bilo Ëime.
{107084}{107152}- Gde je on sada?|- Oni su se skupili.
{107153}{107197}Znaö, neöto nalik proslavi.
{107198}{107278}VeËe pre velikog pogubljenja|i tako dalje.
{107279}{107355}Mislim, ako je on ovde,|on je tamo.
{108085}{108152}Iöamarao sam ga za medalju.
{108153}{108206}Ljubitelj crnËuga.
{108207}{108255}Nadam se da nisi osetljiv na krv,|lepi.
{108256}{108344}- Hej!|- Nije bio sposoban za to.
{109854}{109916}Polazi. Izbacite ga odavde.
{110066}{110139}- `Ajmo, jebivetru! Marö odavde!
{110242}{110313}Sklonite se od tog momka.
{110314}{110363}Briöimo!
{110402}{110483}O, Boûe. O, Boûe.
{110484}{110542}Hvala vam.
{110543}{110601}Cenim to.
{110602}{110659}- Stvarno?
{110840}{110921}- Roli Vedû. -Jedno od mnogih|imena kojma su me oslovljavali.
{110922}{111007}äta radiö ti ovde?
{111008}{111056}Vi ste podmetnuli bombu i|pobili onu decu.
{111057}{111133}äta, jesi li planirao|hapöenje?
{111134}{111207}- Samo hoÊu da Ëujem vaöe priznanje.
{111208}{111313}Obmana, gospodine Hol.|Vi ûelite samo "da",
{111314}{111391}tako da moûete da identifikujete,|kvantifikujete,
{111392}{111448}priredite pojam zla.
{111449}{111524}Ako sam ja to uradio,|onda sam ja zlo,
{111525}{111597}i mogu biti odabran iz gomile.
{111598}{111669}Otklonjen, odvojen, uniöten.
{111670}{111720}Zlo moûe biti uniöteno.
{111721}{111789}I svi vi dobri ljudi se|moûete oseÊati sigurnim...
{111790}{111862}u Ëauri svog poricanja.
{111863}{111930}- Sem kaûe da ste vi njegov narod.|- I jesmo.
{111931}{111997}A, je`l ovako postupate prema|svom narodu?
{111998}{112057}A? Dopuötate da ispaötaju umesto vas?
{112101}{112197}äta je sa lojalnoöÊu?|A? äta je sa istinom?
{112354}{112458}Istina, zasnovana na vaöim zakonima,|zastupniËe Hol,
{112460}{112548}jeste da je Sem Kejhol kriv i da|je osuen na smrt.
{112550}{112637}Moûda je vreme da vi|pokaûete malo lojalnosti,
{112638}{112701}i pustite da pravda bude zadovoljena.
{112702}{112787}A poöto se to desi,
{112788}{112871}uvek budi paûljiv.
{112872}{112918}Uvek.
{113249}{113307}- On je verovatno joö tamo.|- Uh-huh.
{113340}{113401}- I? - Kada bi|Semu bilo sueno kao sauËesniku,
{113402}{113446}dobio bi najviöe 20 godina.
{113447}{113535}- E, rekli ste da ûelite nove informacije.|- Uz svo duûno poötovanje,
{113536}{113607}ovo je jedva upotrebljiv|dokaz za bilo öta.
{113608}{113678}Odobrite odlaganje.|Dajte mi joö vremena.
{113737}{113816}U redu, ljudi.|Sluöajte. Sada je 08:00 sati.
{113817}{113891}Ovime aktiviram "centar|za vanredne situacije"...
{113892}{113943}i priveremeno|zatvaram ovu ustanovu.
{113944}{114038}I od svih vas oËekujem da|na osnovu toga vröite svoje duûnosti.
{114039}{114105}Bez predomiöljanja,|Bez improvizacije.
{114106}{114183}Ovo pogubljenje Êe se|dogoditi u 16 Ëasova.
{115594}{115668}Za ono öto si uradio onoj deci...
{115715}{115789}niko nikada nije mogao da ti oprosti.
{115845}{115922}Za ono öto si uradio meni...
{115945}{116003}i Ediju,
{116050}{116124}Ja moram.
{116347}{116395}Ne zbog tebe, stari.
{116494}{116542}VeÊ zbog sebe.
{117031}{117116}Edi je rekao...
{117138}{117243}da ti nikada ne bi ubio Dûoa Linkolna,
{117266}{117390}da sam ti ja kroz plaË rekla|da to ne uradiö.
{117391}{117436}Jesi li zbog toga ovde doöla?
{117547}{117596}Ne.
{117787}{117835}Da li bi ga ipak ubio?
{117942}{118006}Da. Da.
{118675}{118788}Na petom zasedanju sud je|odbio poslednju ûalbu Sema Kejhola.
{118789}{118861}AmeriËki vrhovni sud Êe danas|tokom dana odluËiti o njegovoj sudbini.
{118862}{118973}Ako i oni odbiju, guverner Dejvid Mekalister|Êe biti njegova poslednja öansa.
{118974}{119068}Pogubljenje je planirano u|12:01 sutra ujutru.
{119071}{119124}Stefani Bel Flint,|VLBT vesti.
{119268}{119327}Imaö vatre, a?
{119743}{119792}Seme.
{119866}{119940}Upoznao sam neke od ljudi|tvog pravog naroda sinoÊ.
{119980}{120080}Vrlo zanimljiva druûina.|Oni su pravi narod.
{120138}{120186}Pogotovu Roli Vedû.
{120240}{120306}Roli... Vedû.
{120348}{120398}On je bio vrlo zanimljiv.
{120834}{120882}Moram da razgovaram sa straûarima.
{120883}{120930}Otvori Semovu Êeliju.
{121173}{121241}Puno liËite na vaöeg brata,|gospodine Kejhol.
{122059}{122129}Doöao sam da odam poötu, Sem.
{122173}{122220}Oprostim se.
{122221}{122306}Uverim se da si joö uvek jak.
{122450}{122502}Video sam to dvoje male dece.
{122543}{122608}Bili su na prozoru.
{122631}{122696}To je bila greöka.
{122697}{122763}SpreËili smo dva mala Jevreja...
{122764}{122825}od odrastanja u velike Jevreje.
{122826}{122877}Kada se njihov crnaËki-naklonjeni|otac ubio,
{122878}{122969}je kao kada praviö ûabice|kamenËiÊima u jezercetu.
{123011}{123119}Talasi su celome svetu preneli poruku.
{123141}{123213}Jevrej je slab.
{123236}{123303}Kako to smatraö greökom?
{123304}{123358}Nije trebalo da bude ubijanja.
{123359}{123421}Nemoj da smeköavaö, Sem.
{123422}{123469}Taj dan dolazi.
{123543}{123647}Voleo bih kada bi ti mogao da|ostaneö i vidiö to, prijatelju. Dolazi.
{123648}{123712}Svaki dan sve viöe i|viöe ljudi otvara svoje oËi...
{123713}{123775}da bi videlo jedinu|pogreönu stvar u ovoj zemlji...
{123776}{123856}a to je da smo krenuli|protiv zakona prirode.
{123857}{123902}Boûijeg zakona.
{123960}{124070}Samo jaki imaju pravo da preûive.
{124071}{124135}A sada, konaËno,
{124136}{124211}oni nedostojni-
{124213}{124273}Jevrej, Afrikanac,
{124274}{124332}homoseksualac-
{124333}{124396}svi kopaju svoje sopstvene grobove.
{124397}{124520}I kada ih nabacamo unutra,|NazdraviÊu ti, Seme.
{124521}{124594}I ispiöaÊu se na njihova uûasnuta lica.
{124595}{124640}Ne.
{124641}{124711}Bio si odan i dobar vojnik, Sem.
{124712}{124781}Umri sa svojim dostojanstvom.
{124782}{124847}Ne daj da te taj klinac zbuni!
{124848}{124927}U u njemu teËe krv njegovog slabog oca.
{124928}{124996}On nije Ëist.|On nije kao mi.
{124997}{125107}Ne. Ti kuËkin sine.|Ti kuËkin sine.
{125129}{125216}Ja nisam kao ti. Ja nisam kao ti!
{125218}{125301}Samo takni mog unuka, i ubiÊu te!
{125302}{125399}- OtkinuÊu ti glavu! UbiÊu te,|ti proketi kuËkin sine.
{125400}{125440}- Znate li ko je ovo?|- Tvoj brat.
{125441}{125525}O, ne, on nije moj brat!|Ti nisi moj brat!
{125526}{125584}- Bolje idite odavde.|- MoliÊu se za tebe, Sem.
{125585}{125705}- Idi do avola, ti kuËkin sine!|Idi doavola! - MoliÊu se za tebe.
{126022}{126106}Otvori Semovu Êeliju.
{126174}{126222}Sud joö niöta nije odluËio.
{126594}{126675}Voleo bih da poöaljeö|ovo za mene, molim te.
{126740}{126808}Nemam adrese.
{127136}{127184}Ne odustaj, Sem.
{127185}{127232}Mmm.
{127317}{127365}Joö neöto.
{127638}{127686}Nosi ono.
{127819}{127867}Otvori Semovu Êeliju.
{128069}{128117}To je vrhovni sud.
{128118}{128174}Kafa je francuska,|baö kao öto si traûio.
{128175}{128221}Hvala.
{128321}{128370}Zatvori.
{128501}{128556}Adam Hol.
{128698}{128747}Mmm.
{129012}{129061}Joö nije gotovo, Sem.
{129062}{129112}Joö nije gotovo.
{129430}{129505}AmeriËki Vrhovni Sud...
{129506}{129585}je odbio poslednje ûalbe u korist Sema Kejhola.
{129892}{129965}Uguöite ga! Uguöite ga!
{130124}{130172}- Poûuri, poûuri. Idemo.|- Drûi.
{130173}{130214}- Hajde!|- Idemo.
{130242}{130323}Kejhol je potpisao zahtev!|Gudmen je u sudu,
{130324}{130398}i taûi da se otvore|arhive Komisije Suverenosti.
{130399}{130501}- äta da radimo? - Radimo? Ne seÊam se|da mi je bilo ko traûio da radim bilo öta.
{130502}{130621}- Hajde da vidimo Ëega tamo ima.|- Sugeriöe na sauËesnika u bombaökom napadu,|kao prvo.
{130622}{130669}Neki ekstremno desniËarski|ludak po imenu Roli Vedû.
{130670}{130729}Odkud ti to znaö, do avola?
{130854}{130934}O tome Êemo kasnije.|Sada, izvini nas.
{130935}{131025}- O Ëemu si priËao?|- Mislim da to neÊe upaliti, to je sve.
{131026}{131122}Ima i drugih imena.|Neka su poznata.
{131148}{131208}Znati unapred moûe biti korisno.
{131614}{131670}Guverner na vezi, gospodine.
{131671}{131740}- Zdravo, guverneru.|- Senatore.
{131741}{131827}Advokat Sema Kejhola pokuöava da doe|do nekih arhiva Komisije Suverenosti...
{131828}{131884}koje vi i neki od vaöih kolega|baö ne biste voleli da vidite.
{131885}{131965}Imam predlog za vas,|ali morate brzo da delujete.
{131966}{132044}# Can't go home|if you're goin' by the mill #
{132045}{132105}# 'Cause the bridge washed out|at the bottom of the hill #
{132106}{132154}# The big creek's up|and the little creek's level #
{132155}{132211}# Pile my corn|with the devil's shovel #
{132212}{132265}# Stay all night|Stay a little longer #
{132266}{132322}- # Dance all night|Dance a little longer #|- Ovo je za tebe, Kejhol.
{132524}{132624}Mogu, uh, ti ponuditi sedativ,|ako hoÊeö.
{132658}{132706}U redu.
{132751}{132838}Onda bolje poËni da se presvlaËiö.|VraÊam se za 30 minuta.
{132839}{132884}Nemoj da kasniö.
{133098}{133154}# Pull off your coat|Throw it in the corner #
{133155}{133209}# Don't see why you don't stay|a little longer #
{133258}{133338}# Oh, the mule and|the grasshopper eatin' ice cream ##
{134021}{134107}Uguöite ga! Uguöite ga!
{134353}{134427}Otvaraj, Kejhol.
{135168}{135217}U redu je.
{135381}{135442}éalba je 28., nemoj da zaboraviö.
{135443}{135547}- Ostavio sam tvoje papire kod Berija|u pravnoj biblioteci. - Hvala ti, Seme.
{135548}{135648}Dame i gospodo, guverner Misisipija,
{135649}{135729}Ëasni Dejvid Alen Mekalister.
{135897}{135949}VeËeras,
{135950}{136022}AmreriËki Vrhovni Sud...
{136023}{136152}je odbio sve ûalbe podnete|u korist Sema Kejhola.
{136220}{136304}Tako da u- u ovom trenutku istine,
{136305}{136384}ja moram da preuzmem|uûasni teret ove kancelarije...
{136385}{136463}koja je moja i samo moja.
{136464}{136555}Pitanje za mene veËaras je,
{136556}{136643}"Ko je Dejvid Alen Mekalister,
{136644}{136722}- koji maöta da bi se u svojim najboljim|trenucima... - Vidimo se, Dû.B.
{136723}{136800}- ikada mogao pokazati mudrijim od porote...|- Vidimo se uskoro, Seme.
{136801}{136865}- i od 47 sudija...|- U lice, Seme. Pljuni im u lice.
{136866}{136929}- koji su razmatrali sluËaj...|- Molim se za tebe, Seme.
{136930}{137005}- tokom proteklih 16 godina?|- Zdravo, Seme.
{137006}{137086}- Odgovor je jasan.|- Zapamti da je Gospod sa tobom.
{137088}{137167}Kada je pitanje ûivota ili smrti,|niko meu nama...
{137168}{137270}nije bolje upuÊen od naöeg|pravnog sistema.
{137271}{137314}Meutim, veËeras,
{137315}{137402}dobijen je podatak koji sugeriöe da...
{137403}{137486}gospodin Kejhol moûda nije|delovao sam u ovom gnusnom zloËinu.
{137487}{137576}Sada, ako se ove tvrdnje iskaûu taËnim,
{137577}{137674}sigurno je, da Êe svako za|koga se dokaûe da je umeöan...
{137675}{137776}Êe biti gonjen|do krajnjih granica zakona.
{137777}{137825}- Meutim,|- Ne mrdaj! Ruke u vis!
{137826}{137930}bez obzira na koliko|je joö ljudi upleteno,
{137931}{138008}to ne menja...
{138009}{138057}fundamentalnu Ëinjenicu:
{138058}{138132}Sem Kejhol je kriv zaöta je optuûen,
{138133}{138206}i Sem Kejhol mora da plati cenu.
{138381}{138428}Ja se-
{138429}{138549}sa najveÊom poniznoöÊu pokoravam...
{138550}{138593}sa poötovanjem...
{138594}{138674}naöoj "dragoj dami", Pravdi.
{138675}{138751}U jedan minut posle ponoÊi,
{138752}{138842}Sem Kejhol Êe upoznati svog stvaraoca.
{138843}{138931}KonaËna presuda Êe zaista biti njegova.
{139031}{139123}Porodicama ûrtava, kaûemo...
{139124}{139244}niöta ne moûe da zameni|vaö ogroman i straviËan gubitak.
{139245}{139309}Osveta nikada neÊe smanjiti...
{139310}{139421}nepopunjivu prazninu napravljenu|od strane onih kojih sada nema.
{139422}{139508}Molimo se sa vama...
{139509}{139601}da nam Bog da snage i hraborsti...
{139602}{139716}da spreËimo da|ovakvi zloËini ikad viöe...
{139717}{139809}prljaju naöu zemlju krvlju nevinih.
{139810}{139914}Laku noÊ.
{139915}{139985}I neka Bog blagoslovi Ameriku.
{140096}{140210}Mali, nemoj.|Ne pokuöavaj viöe da me spaseö.
{140211}{140321}Znam da negde u sebi,|pokuöavaö da podstakenö nekakvo Ëudo.
{140547}{140617}Ne moûemo da zaboravimo ko je Sem Kejhol...
{140618}{140674}ni vrstu miöljenja koju on zastupa.
{140675}{140746}Siguran sam da ti nisi.
{140747}{140804}- A ostala imena?|- To su korisne informacija.
{140805}{140878}PomoÊiÊe nam da ostvarimo|neke prave promene sledeÊi put.
{140879}{140958}Zar ti zbog toga ne radiö ovaj posao?
{140959}{141037}Sav napredak je u pregovorima, Nora.
{142440}{142520}Od svih ljudi i stvari koje|sam mrzeo celog svog ûivota,
{142521}{142624}ono öto sam najviöe mrzeo sam bio ja.
{142692}{142786}Dat mi je slobodan ulaz na ovaj svet|da ga iskoristim kako god mogu.
{142787}{142858}Sedeo sam ovde 16 godina.
{142888}{142990}Mislio sam da -|Da nikada nikome nimalo dobrog nisam uradio.
{143028}{143079}Mmm.
{143126}{143175}Dok se ti nisi pojavio.
{143325}{143392}Vidiö,|ako Êu da se ponosim tobom,
{143393}{143462}Moram se ponositi tvojim ocem.
{143463}{143551}Nije on bio slab.|Ja- Bio je jak.
{143608}{143698}Dovoljno jak da pobegne.
{143699}{143771}Dovoljno jak da tebi da sve öto imaö.
{143878}{143929}Ako je to mogao da ti da,
{143930}{144044}RaËunam da mora da je ovaj|starac preneo neöto dobro na njega.
{144173}{144222}To nisam znao.
{144633}{144681}Spreman sam.
{144910}{145000}Ui.|»ekali smo te.
{145227}{145343}- Dobro.
{147053}{147102}Mmm.
{147130}{147178}Movin' right along.
{147280}{147338}Mmm.
{147339}{147395}Ja-
{149206}{149304}Ajde, ËoveËe!|äta se dogaa, do avola?
{150645}{150718}Seme, ovo je nalog|za izvröenje smrtne kazne.
{150719}{150773}I sam znaö da se od mene|po zakonu zahteva da ti je proËitam.
{150774}{150873}"Mi, porota, jednoglasno|i bez sumnje nalazimo...
{150874}{150920}sledeÊe oteûavajuÊe okolnosti:
{150921}{150975}Ubistvo je izvröeno pri Ëemu je|tuûeni upleten...
{150976}{151021}u izvröenje zloËina.
{151022}{151093}Ubistvo je bilo posebno gnusno,|svirepo i okrutno.
{151094}{151161}Mi, porota, jednoglasno nalazimo,|iz dokaza...
{151162}{151270}i bez ikakve sumnje to da, tuûeni,|Sem Kejhol, treba da bude osuen da smrt...
{151271}{151335}smrtonosnim gasom u|Drûavnom Zatvoru Misisipi,
{151336}{151439}ParËmen, Misisipi,|13-i april, 1996."
{151501}{151553}I nema odlaganja.
{151554}{151623}Ima li nekog razloga da se ovo|pogubljenje ne nastavi?
{151624}{151671}Ne.
{151697}{151745}Imate li poslednje reËi,|gospodien Kejhol?
{155522}{155587}Moûda su duhovi nestali, Li.
{155682}{155731}Moûda.
{155852}{155919}Hvala ti, Adame.
{155944}{157444}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/9drs6|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
