{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{1062}{1119}VARäAVA 1939.
{3388}{3424}Gospodine Spilman?|- Pozdravljam.
{3434}{3513}Tu sam radi vas,|primjeÊujem vaöe sviranje..|- Tko ste?
{3521}{3652}Dorota, Jurekova sestra. Krvarite!|-To nije niöta...
{3677}{3754}Piöi mu, sad nije vrijeme za razgovor.
{3783}{3820}Zaöto si to skrivao?
{3924}{3983}Ne znam öto da uzmem.|- Uvijek uzmeö previöe.
{4026}{4097}Koliko  kofera Êeö imati?|- Uzeti Êu crvenu odjeÊu.
{4103}{4187}äto misliö, dali da uzmem striËev portret ili ne?
{4192}{4312}Uzmi öto hoÊeö|Ne vidiö li da sam luda od brige?
{4321}{4411}Sad Ëeö doÊi doma.|- Jedan kofer za cipele.
{4430}{4497}Vladek! Mama, doöao je!|- Hvala bogu!
{4555}{4618}Ranjen si.|- Samo ogrebotina, niöta opasno.
{4628}{4716}Na smrt me je brinulo.|ñ Nije bilo potrebno. Dokumente imaö.
{4721}{4825}Ako bi te pogodilo, znali bi, ûiv si.|- Ne govori tako.
{4850}{4895}Boûe saËuvaj!
{4911}{4959}Tata, Vladek je doma.|- No, öto sam rekao?
{4968}{5024}äto radite?|ñ Gdje  je moj öeöir s öirokimi krajevima?
{5044}{5138}Nisam vidio da bombardiraju.|- Varöavska stanica nije jedina.
{5157}{5226}Uzmi svoje stvari, dragi.|- Kamo idemo?
{5240}{5307}Iz Varöave.|- Gdje?|-Nisi sluöao?
{5338}{5413}Nisi vidio Ëasopise?|Gdje su?
{5420}{5459}Upotrijebila sam ih za pakiranje.
{5488}{5587}Vlada je u Lublinu.|- Zdravi muökarci moraju prijeÊi rijeku
{5591}{5715}i postaviti obrambenu liniju.|- Ostale su samo ûene.
{5729}{5841}I öto Êete vi raditi tamo?|VuÊi naokolo prtljagu?
{5850}{5916}Pakiraj, Vladek, ûuri se.|- Nikamo ne idem.
{5924}{6040}Niti ja.|- Ne budite smijeöni! Moramo ostati skupa.
{6053}{6134}Ako moram umrijeti,|radije Êu u svome domu.
{6148}{6211}Boûe saËuvaj.|- Tiöina. Neöto smo Ëuli.
{6236}{6342}Po obavijesti londonskog|BBC-ja engleska je vlada, 
{6349}{6451}kada nije dobila odgovor|na svoj ultimatum, 
{6457}{6582}objavila rat|nacistiËkoj NjemaËkoj.
{6614}{6647}To je predivno!
{6653}{6702}OËekuje se,
{6834}{6879}da Êe i nakon nekoliko sati
{6885}{7007}jednako uËiniti i Francuska.|Poljska nije viöe sama. 
{7169}{7223}To je predivno!
{7257}{7333}OdliËna veËera, mama.|- Istina je.
{7353}{7410}Ako neöto slaviö, moraö se potruditi.
{7423}{7472}Nazdravimo Engleskoj i Francuskoj.
{7493}{7572}äto sam vam rekao?|Sve Êe biti dobro.
{8383}{8424}Pet tisuÊa i tri.
{8460}{8556}Je to sve?|- Toliko nam je ostalo.
{8562}{8617}3003 zlota previöe.
{8654}{8717}OgraniËenje financijskih sredstava:
{8725}{8848}éidovu je dozvoljeno najviöe 2000 zlota.|ñ äto sa ostalim?
{8856}{8893}U banku.
{8910}{9031}Nije glup, Tko bi uloûio novac u njemaËku banku.|- Sakrijmo ga.
{9056}{9133}Pod cvijetni lonac.
{9143}{9249}Ne. Upotrijebiti Êe mo ga|na provjereni naËin. Kao u zadnjem ratu.
{9278}{9323}Izdubili smo noge stola.
{9369}{9437}I ako odnesu stol?|- Kako to misliö?
{9442}{9555}Iz ûidovskih domova uzimaju sve, öto je vrijedno.|- Istina?
{9564}{9628}Budalo! äto Êe im takav stol?
{9659}{9702}äto radiö, za ime boûje?
{9728}{9821}Sakrijmo ga u teglicu.|Nitko neÊe pomisliti na nju.
{9828}{9915}Ne. Razmiöljao sam...|- To je ipak neöto novo.
{9930}{9975}Upotrijebimo psihologiju.|- Molim?
{9988}{10114}Pustimo novac i sat na stolu,|tako pokriven, svima na oËima.
{10185}{10253}Jesi lud?|ñ Svugdje Êe traûiti, samo ne tu.
{10260}{10343}To je najlua ideja koju sam Ëuo!|Naravno da hoÊe. Gledaj.
{10422}{10447}Budalo.
{10468}{10553}Ja sam budala?|ñ Nije loöe, neÊe pomisliti na to.
{10560}{10614}Trajat Êe sate i sate.|- Nikud se ne ûuri.
{10619}{10710}Kako Êe mo ga izvaditi?|- S pincetom.
{10743}{10817}Kako?|- S pincetom, svakog posebno. Zaöto viËeö?
{10826}{10916}Nitko me ne sluöa!|- Tiöina! Stanite u red.
{10921}{10963}Odvjetnica je, hoÊe red.
{10996}{11084}Sat Êemo staviti u teglicu,|novac u violinu.
{11138}{11233}Mogu joö svirati?|- Uskoro Êeö znati.
{11255}{11309}Ja sam, Vladek Spilman.
{11321}{11419}Kako ide?|- Dobro. A ti?
{11430}{11533}u redu, s obzirom na okolnosti.|Znam, zaöto govoriö.
{11538}{11622}Niöta ne mogu uËiniti.|Ne dozvoljavaju dogaanja. 
{11634}{11746}Znam, Jurek...|ñ Nema glazbe, ni radija za éidove.  
{11761}{11840}Takoe za pijanista, kao öto si ti,|naÊi Êeö si posao. 
{11847}{11934}Nisam siguran.
{11963}{12027}Oprosti, ne govorim zbog svoje karijere.
{12036}{12151}Tjedne i tjedne sam sitno radila.|KonËno sam snimala s njim.
{12160}{12311}Bombardirali su stanicu.|- Predivno, da sam te upoznao.
{12328}{12422}Istina?|- Bilo je... nezaboravno.
{12450}{12524}Oboûavam vaöe sviranje, g. Spilman.|- Vladek, molim.
{12530}{12632}Nitko ne svira Chopina kao vi.|- Jeli to kompliment?|Naravno.
{12644}{12761}Tko zna. äalim se.|Idemo na kavu u Paradiso?
{12770}{12797}Vrlo rado.
{12843}{12955}äto ti radiö?|- Zavröila sam konzervatorij.|- Glazbenica?
{12978}{13029}Niöta viöe nego ti.|- Koji instrument?
{13033}{13119}»elo.|ñ Volim gledati ûenu kad svira Ëelo.
{13176}{13204}Tu smo.
{13211}{13257}éIDOVIMA ULAZ ZABRANJEN
{13262}{13359}Sramotno! Kako si dozvoljavaju!|- Takvi su ljudi.
{13364}{13443}éele biti bolji nacisti od Hitlera.|ñ éalit Êu se.
{13458}{13556}Bolje ne, vjeruj mi.|- Kako poniûavajuÊe za vas.
{13691}{13722}IÊi Êemo drugdje.
{13752}{13803}Na öetnju u park.|- Ne.
{13831}{13916}Sluûbena obavijest.|éidovima nije dozvoljeno u park.
{13931}{13992}Moj boûe, öalite se?|- Istina je.
{13999}{14084}Predloûio bi, da sjednemo na klupu,|ali tu je joö jedan oglas.
{14088}{14157}éidovima su i javne klupe zabranjene.|- Glupost!
{14169}{14242}Moûemo stajati tu i priËati.
{14257}{14361}To je moûda dovoljno, öto kaûeö?|Sviraö Ëelo.
{14378}{14467}Lijepo. Najdraûi skladatelj?|Chopin!
{14474}{14565}Ako je tako, moraö nauËiti|njegovu sonatu za Ëelo.
{14584}{14722}Pa ti, Vladek?|Primio bi te. Moj klavir, tvoj Ëelo.
{14729}{14809}Bilo bi predivno, g. Spilman.
{14871}{14921}Samo Vladek, molim.
{14932}{15006}éidovske oznake u varöavskom okruûju.
{15019}{15156}Nareujem, da svi éidovi na ulici nose oznake.
{15169}{15290}Odredba vaûi od 1. prosinca 1939.
{15296}{15370}za sve éidove starije od 12g.
{15393}{15458}Nositi ih moraju na desnom rukavu
{15468}{15575}u obliku modre Davidove|zvijezde na bijeloj podlozi.
{15583}{15735}Podloga mora biti dovoljno|velika za 8-cm zvijezdu.
{15764}{15848}äirina krakova mora biti 1 cm.
{15868}{15982}Tko se toga ne bude pridrûavao,|biti Êe strogo kaûnjen.
{16001}{16098}Varöavski guverner, dr. Fischer.
{16185}{16285}NeÊu je nositi.|- Ja takoer neÊu. NeÊu biti ûigosana.
{16383}{16416}Pokaûi to.
{16530}{16612}Piöe, da je moramo kupiti sami.
{16646}{16751}Gdje?|- NeÊemo je nositi!
{16973}{17064}Ti! Doi ovamo.
{17241}{17285}Zaöto se nisi poklonio?
{17323}{17357}Oprostite mi.
{17624}{17682}Ne smijeö hodati po ploËniku!
{17697}{17732}Idi po blatu!
{18138}{18221}Jesi vidio to?|- äto? Radim. äto je?
{18341}{18417}Sve Êe nas tu staviti.|- Kako, staviti?
{18482}{18552}Po naredbi varöavskoga|guvernera
{18567}{18652}o ureenju ûidovskog geta.
{18666}{18802}U tom getou Êe stanovali svi|varöavski éidovi i doöljaci.
{18864}{18922}éidovi, koji ûive van podruËja,
{18928}{19042}se moraju preseliti do 31. listopada 1940.
{19081}{19189}Sve Êe nas smjestiti tu.|U Varöavi nas je 400.000!
{19196}{19242}IÊi Êe, jer nas je samo 360.000.
{19278}{19419}äto da radim? Baö si pametan,|öto da kupim s tim? 
{19462}{19580}Mama, öto nije u redu?
{19638}{19734}Ostalo nam je samo 20 zlota.
{19873}{19930}äto mogu kupiti s 20 zlota?
{19965}{20064}Dosta mi je kuhanja krompira svaki dan.
{20255}{20347}Takva je cijena. Savjetujem da ju prihvatite.
{20352}{20425}Viöe vam neÊe dati nitko.|- To je Bechstein, g. Lipa.
{20429}{20485}Dvije tisuÊe, niöta viöe.
{20496}{20548}Jesti Êete klavir, kad budete gladni?
{20570}{20679}Van! Lopove nevrijedni,|radije Êu ga pokloniti!
{20712}{20825}äto vam se dogodilo?|Jeste poludjeli, zato öto niste jeli?
{20843}{20932}Radim vam uslugu. 2000,| Platit Êu i selidbu
{21021}{21109}Sigurno niste joö jeli, ludi ste.|- Uzmite ga.
{21962}{21992}Dorota!
{22039}{22068}Bok.
{22132}{22173}Nisam htjela doÊi.
{22193}{22302}Nisam htjela znati za to,|ali me neöto tjeralo.
{22307}{22365}Kako si?|- U redu.
{22411}{22485}Nije istina. Uhitili su mi bratiÊa.
{22502}{22620}Jurek kaûe, da Êe uskoro van. Sramota.
{22644}{22730}Ne brini, neÊe dugo.|- To i ja kaûem.
{22790}{22835}Previöe apsurdno je sve to.
{22977}{23012}Moram...
{23097}{23147}Vidimo se uskoro.
{23289}{23321}Do vienja.
{23736}{23818}Da budem iskren, bojao sam se,|da Êe biti gore.
{23985}{24078}Gdje Êu ja spavati?|ñ Ja Êu s curicom u kuhinji,
{24090}{24155}ti, Henrik i tata ovdje.
{24206}{24231}Pogledajte.
{24284}{24313}Doite vidjeti.
{25160}{25205}Van, djeco. Van!
{25244}{25291}Tata! Tata!
{25697}{25806}Je si li öto prodao?|- Samo "Idiota" Dostojevskog. Za 3 zlota.
{25824}{25900}Bolje nego juËer.|- Za 3 nevrijedna zlota.
{25911}{25972}Neki zarauju milijune.|- Znam.
{25981}{26056}Ne znaö, podkupio sam straûare,
{26063}{26170}da lagano dovoze na tone hrane, cigareta, piÊa,
{26175}{26290}kozmetike. Oko njih umiru|poöteni, nije ih briga.
{26300}{26430}Jeste li vidjeli mog muûa, Izaka Sermana?|Visok, lijep muökarac.
{26443}{26506}Sa sivom bradicom?|ñ éao mi je, ne.
{26522}{26614}Oprostite. Lijepo spavajte,
{26621}{26744}ako ga vidite piöite, piöite mi.|Izak Serman!
{27106}{27225}Zaöto ovuda prolazi arijevski put?|Zar nas ne moûe zaobiÊi?
{27241}{27321}Ne brinite se, izgraditi Êe most.
{27355}{27411}Most? Pa öto.
{27438}{27574}Nijemci tvrde, da su pametni.|Ja mislim da su totalno glupi.
{27590}{27716}Moram nahraniti obitelj,|pa Ëekam, da nas puste prijeÊi. 
{27740}{27813}Zar misle, da dolazim ovdje sluöati glazbu?
{27821}{27891}äto je? Dosaujeö se?
{27905}{27982}Najbolje pleöi.
{27993}{28072}Pleöi, pleöi!
{28309}{28370}A ti? Ne ûeliö plesati?
{28400}{28484}OËistimo cestu za ûidovske plesaËe.
{28850}{28879}Brûe!
{29200}{29240}Brûe, rekao sam!
{29384}{29423}Rodbino ûidovska!
{29447}{29495}Samo veselo!
{29957}{29988}Doöli ste.
{30029}{30077}Jitcak Heller vas Ëeka.
{30249}{30347}äto to znaËi?|- Popijte Ëaj. RuËak Êe biti, kad dou curice.
{30492}{30574}äto Ëeö ti tu?|- Donio je kolaËe.
{30614}{30715}Otac mu je opet otvorio draguljarnicu.|Dobro mu ide, zar ne?
{30780}{30862}Nevjerovatno.|- UshiÊeni smo.
{30870}{30953}Tko?|- Ne pravi se pametan. Tu sam kao prijatelj.
{30965}{31055}Ovamo dovoze sve ûidove iz drûave.|Uskoro Ëe ih biti milijun.
{31065}{31159}Trbati Êe viöe ûidovskih policajaca.|ñ Da uistinu.
{31169}{31267}éeliö, da u gestapovskom duhu pretuËem éidove.
{31273}{31325}Netko mora i to raditi.|- Zaöto ja?
{31331}{31389}Ne novaËiö li momke bogatih oËeva?
{31399}{31482}Pogledaj mojega, pogledaj nas.|- Zato sam tu.
{31487}{31583}Pobrinuo bi se za cijelu obitelj.|Ali radije prodajeö knjige?
{31592}{31677}Da, molim.|- Radim vam uslugu.
{31705}{31805}Pa ti, Vladek? Pijanist si.|Imamo dobru dûez skupinu.
{31815}{31903}Rado bi te primili. Posao nemaö...|- Hvala, imam ga.
{33094}{33147}Oprosti, Vladek, ali ûeli,|da prestaneö.
{33193}{33221}Tko?
{34489}{34587}Gledaj to u boljem svijetlu. U malom getu ste,
{34593}{34699}intelektualci, majstori.|Tu je kao u stupici.
{34707}{34784}Jehuda, daj mi posao.|- Umjetnik si, Vladek.
{34788}{34872}Dovoljno je, da ljudima dajeö volju.|- Rado bi pomagao.
{34883}{34949}Previöe si poznat. I joö neöto.
{34980}{35062}Vi glazbenici niste urotnici. Previöe..
{35113}{35147}..ste melodiËni!
{35300}{35349}Tko je?|- Simche.|- Majorek.
{35406}{35491}Proglas lijepe na mjesto|daleko od nepoûeljnih.
{35541}{35578}Zdravo.
{35707}{35755}Radi se?
{35778}{35855}To je najbolji pijanist u|Poljskoj, moûda i na svijetu.
{35864}{35978}Vladislav Spilman, Majorek.|- Znam te po imenu.
{36006}{36039}Ali te joö nisam Ëuo |kako sviraö.
{36049}{36179}Majorek je bio vojnik.|»udi me, öto nisi socijalist.
{36227}{36289}Idi sad, Vladek. Uskoro Êe policijski sat.
{36332}{36428}Znaö, koliko brojeva Ëasopisa tiskamo?|-500.
{36456}{36537}I koliko ga ljudi proËita po kopiji?|-Dvadeset.
{36547}{36647}Zajedno 10.000 Ëitatelja.|To je poËetak ustanka.
{36658}{36735}Majorek ih skriva u hlaËama|i puöta ih u zahodima.
{36757}{36861}Kako da ih naem?|Nijemci ne hodaju na ûidovske zahode.
{36881}{36918}Za njih su preËisti.
{37722}{37766}Ti vragovi!
{38018}{38051}Stanite!
{38183}{38275}Daj, deËko, ustani.
{38426}{38473}Ustani!
{39232}{39324}VeËeras ne govorite o ruûnim stvarima.
{39340}{39417}Dobar tek.|- Potom Êu vam reÊi neöto smijeöno.
{39424}{39485}Znate, tko je dr. Raszeja.|- Kirurg.
{39503}{39616}Ne znam, zaöto, a Nijemci su|mu dozvolili operirati u getu.
{39625}{39699}Poljaku su dozvolili,|da operira éidova?
{39705}{39746}Znam, da je dobio dozvolu.
{39755}{39835}Bolesnika je uspavao|i poËeo operirati.
{39848}{39960}Zarezao je, kad su uletjeli|esesovci, ubili bolesnika,
{39965}{40032}zatim dr. Raszeju i sve prisutne.
{40077}{40111}Smijeöno, a?
{40159}{40281}Uspavani bolesnik nije niöta osjetio.|- Niöta loöe nisam rekao.
{40302}{40393}äto vam je?|Gdje vam je smisao za humor?
{40418}{40545}Nije smijeöno.|- Znaö, öto je? Ti s tom glupom kravatom.
{40578}{40650}äto to je s mojom kravatom?
{40660}{40748}Trebam ju pri radu.|Ja sad radim.
{40748}{40830}Radiö, da. Parazitima u getu|sviraö na klaviru.
{40835}{40896}Parazitima?|- DeËki, deËki.
{40912}{40969}Neosjetljivim za jade drugih.|ñ Jesam ja kriv?
{40975}{41058}Nisu joö vidjeli,|öto se dogaa oko njih.
{41063}{41111}Krivi su Amerikanci.|- Za moju kravatu?
{41122}{41171}AmeriËkih éidova je puno.
{41216}{41326}äto su napravili za nas?|Ljudi umiru, stradaju.
{41369}{41410}éidovski bankari bi morali
{41416}{41479}uvjeriti Ameriku,|da NjemaËkoj objavi rat.
{41889}{41914}Svjetla!
{42821}{42852}Otvorite!
{43201}{43225}Ustanite!
{43301}{43332}Ti, ustani!
{43401}{43437}Izbacite ga van!
{43801}{43863}Tiho, mama, za Majku Boûju!
{44130}{44188}Idemo, trËite !
{45659}{45694}äibice!
{45829}{45911}Ja sam sestra g. Spilmana.|- Naravno, uite. Ti ne.
{46410}{46457}äto se dogodilo?|- Moj boûe, straöno.
{46470}{46558}Ljude odvode s ceste.|Odvezli su Henrika.
{46623}{46687}Idi doma. Sve Êu srediti.
{46976}{47070}Oprostite, jeste li vidjeli|mog muûa Izaka Sermana?
{47091}{47219}Visok, miran, sa sivom bradicom?|Ako ga vidite, piöite mi!
{47495}{47589}äto se dogodilo?|- Imaju mojega unuka tamo.
{47598}{47711}Odvoze ih.|Izgubili smo vjeru u Boga.
{47743}{47769}Oprostite.
{47843}{47880}Jitcak!
{47899}{48017}Jitcak, ja sam, Vladek Spilman.
{48173}{48232}Henrik je tamo.|- Nisam ga vidio.
{48245}{48298}Vjeruj mi, ulovili su ga.|- äteta.
{48393}{48458}Moûeö li pomoÊi?|- Da, sad me trebaö.
{48497}{48531}Moûeö li nam pomoÊi?
{48566}{48627}To koöta.|- Nemam novaca.
{48635}{48711}Onda niöta. Trebao si nam se|pridruûiti, kad je bilo vrijeme.
{48722}{48797}Rekli su, da imaö utjecaja.|- Tko?
{48814}{48910}Znanci. Rekli su, da si utjecajan Ëovjek.
{49335}{49386}Svi jednaki. Svi jednaki.
{49458}{49494}Gospod Rubinstein.
{49512}{49592}Ti, bandit. Bum-Bum!|Mrtav!
{49634}{49739}Sad me je istinski strah.|- Za tu öalu gospodin je zasluûio cigaretu.
{49748}{49825}Cigarete! Hvala lijepa!
{49887}{49914}Svi jednaki.
{49927}{50037}Da, svi. Samo smo mi,|Nijemci, malo viöe jednaki.
{50392}{50488}U pomoÊ! Lopov!
{51810}{51931}Zaöto su te ulovili?|- Jesam li te molio da odeö Helleru?
{51952}{51985}Vani si, zar ne?
{51993}{52108}Jesi li puzao pred tim smradom?|- Samo sam ga molio za pomoÊ.
{52120}{52232}Koliko si platio?|- S Ëim bi platio?
{52263}{52345}Svaki zaraeni zlot je za hranu!|ñ Znam se za sebe sam brinuti.
{52361}{52417}Odvezli bi te.|- To je moja stvar.
{52437}{52537}Nisu traûili tebe.|Zaöto se guraö u tue stvari?
{52569}{52651}Lud si.|- Takoe, to je moja stvar.
{52893}{52967}äto ti je? Jesi bolestan?
{52996}{53030}Gladan.
{53235}{53317}Imaö radnu dozvolu?
{53341}{53387}Moraö imati dozvolu,
{53395}{53494}ako ûeliö raditi u njemaËkom|poduzeÊu, u protivnom...|- äto?
{53507}{53586}deportiraju te.|ñ ZnaËi glasine su istinite.
{53596}{53634}Preselit Êe nas
{53653}{53802}u radne logore na istoku.|Zatvoriti Êe mali geto.
{54247}{54291}Vladek!
{54298}{54384}Mislio sam, da si na svjetskoj turneji!|U Parizu, Chicagou.
{54390}{54431}Ne ovaj tjedan.|- Loöe izgledaö.
{54458}{54542}Nisi Ëuo glasine?|Preseliti Êe nas na istok.
{54548}{54621}Previöe to uzimaö k srcu.|äto te muËi?
{54639}{54721}Pokuöavam dobiti radnu dozvolu za oca.
{54742}{54799}Dobio sam je za|sebe i ostatak obitelji,
{54803}{54878}ali za oca ne. Svugdje sam veÊ probao.
{54884}{54967}äto nisi doöao k meni.|- Nisam znao da se time baviö.
{54977}{55009}Ja ne, Majorek se bavi.
{55081}{55166}Moûeö mi pomoÊi? Novaca ti nemam.|- Ne vrijeaj nas.
{55183}{55270}Moûeö to napraviti?|-Sutra u 16h u Schultzevoj radionici.
{55292}{55417}Vidiö, kakvu sreÊu imaö danas?|To je povijesni imperativ u akciji.
{55424}{55503}Uvijek kaûem, gledaj...|- Svijetliju stranu, znam.
{55829}{55877}Kako je s leima?|- Bolje.
{55947}{55988}Bolje, da ne pitaö.
{56308}{56337}Hvala.
{56350}{56442}Veseli me.|Moûda vam i ne bude pomoglo.
{56492}{56527}Hvala, g. Schultz.
{56837}{56912}15. oûujak 1942.
{58256}{58375}Makar radimo u getu.|Joö smo svi skupa.
{58743}{58825}Svi van! Skupite se na dvoriötu!
{58889}{58966}Mi radimo tu. Imamo dozvole.
{59076}{59103}Vladek!
{59176}{59212}Ti, na lijevu stranu!
{59503}{59529}Ti.
{59586}{59624}I ti.
{59845}{59924}Ostali se obucite i opet se javite tu.
{59932}{60002}Uzmite svoje stvari! 15 kila, niöta viöe.
{60014}{60062}Kamo nas vodite?
{60657}{60707}éao mi je. Trudio sam se.
{60771}{60820}Mislio sam da Êe nas dozvole spasiti.
{60826}{60922}Prestani, Vladek.|- Misliö da bi Henrik i Halina imali viöe sreÊe!
{61602}{61654}Kamo idemo?|- Raditi.
{61661}{61732}Bit Êe vam bolje nego|u smrdljivom getu. Naprijed!
{62059}{62101}Zaöto sam to uËinila?
{62128}{62181}Zaöto sam to uËinila?
{63249}{63324}Imate kapljicu vode? Moje dijete umire.
{63329}{63413}Umire od ûei. Malo vode, molim vas.
{63481}{63565}Jesi Ëuo, öto govorim? To je sramota!|- »uo sam.
{63573}{63633}Damo se voditi kao ovce u klaonicu!
{63637}{63684}Dr. Ehrlich, tiöe.|- Zaöto ih ne napadnemo?
{63690}{63747}Pola milijona nas je, pobjegnimo.
{63771}{63839}Makar Êemo umrijeti Ëasno,|na uspomenu buduÊnosti.
{63843}{63905}Zaöto ste tako sigurni, da nas öalju u smrt?|- Nisam.
{63916}{63964}Zaöto ne?|- Jer mi nisu rekli.
{63990}{64083}Ali kaûem vam, istrijebiti Êe nas sve.|- Da se borim?
{64088}{64144}Za boj trebamo organizaciju, oruûje..
{64149}{64211}Da se borim s violinskim kljuËem?
{64218}{64291}Nijemci ne bi pobili tolike radnike.
{64304}{64370}U radne logore idemo.|- Naravno.
{64386}{64483}Pogledajte tog invalida,|starce, djecu. HoÊe li raditi?
{64499}{64573}HoÊete li vi nositi ûeljezne|stupove na leima?
{65602}{65663}Henrik! Halina!
{65910}{65946}»uli smo da ste tu.
{65971}{66013}Htjeli smo biti s vama.
{66300}{66334}Kako glupo!
{66359}{66498}Zaöto sam to uradila?|- Ide mi na ûivce.
{66640}{66744}äto je uradila, za Majku Boûju?|- Uguöila je dijete.
{66808}{66841}Bili su se skrivali.
{66850}{66946}Upravo tad, kad je doöla policija,|dijete je zaplakalo.
{66969}{67061}S rukom je zaustavljala njegov plaË.|Umrlo je.
{67101}{67178}Policajac je Ëuo plaË i naöao ih.
{67794}{67829}äto Ëitaö?
{67910}{67955}Ne krvarimo, ako nas ubodete?
{67968}{68019}Ne smijemo se, ako nas ökakljate?
{68027}{68080}Ne mremo, ako nas ubijate?
{68088}{68154}Ne osveÊujemo se, ako nam uËinite zlo?
{68348}{68417}Vrlo primjereno.|- Zato sam je uzeo sa sobom.
{68858}{68925}Budala. äto misli da Êe s tim novcem?
{68972}{69018}DjeËaËe, doi ovamo.
{69132}{69187}Koliko koöta karamela?|- 20 zlota.
{69201}{69298}Jedna karamela? äto Êeö s tim novcem?|- 20 zlota.
{69366}{69448}Imamo skupa toliko?|Ja imam 10.
{69551}{69603}Pet, deset, dvadeset.
{71311}{71344}Brûe, brûe!
{71594}{71649}Halina?|- äto?
{71697}{71778}Smijeöno, da sad to govorim.|- äto?
{71819}{71864}Volio bi, da sam te bolje poznavao.
{71967}{71998}Hvala.
{72410}{72439}Spilman!
{72598}{72655}Budalo, nestani!
{72688}{72819}OËe! Mama! Halina!
{72947}{73047}äto hoËeö, Spilman?|Spasio sam ti ûivot! Idi veÊ!
{73161}{73195}Ne trËi!
{73383}{73425}U red, idemo!
{73835}{73900}No, idu u vruÊe krajeve.
{73980}{74038}Daj mi tu stvar, ne trebaö je viöe.
{74216}{74269}äto radite? Trudna je!
{77810}{77841}Vladek!
{78292}{78331}Zaöto si tu?
{78367}{78396}Tako je...
{78411}{78437}Mene...
{78475}{78497}Nas...
{78574}{78638}Sve, baö sve...
{78734}{78802}Moûda imaju sreÊu.|»im brûe, to bolje.
{78831}{78935}Nije joö kraj. Par dana Êemo biti|tu, dok se duhovi smire.
{78963}{79027}Potkupili smo policajca.|DoÊi Êe, kad bude kraj.
{79096}{79128}Na lijevo!
{79154}{79201}U red, marö!
{79535}{79648}Moj boûe, veË 2 godine nisam bio vani.|- Ne veseli se prviöe.
{80060}{80141}Zlato! Dobra cijena.
{80650}{80744}Znaö je? Ljepotica.|Tko je?
{80756}{80814}PjevaËica. Dobro sam je poznavao.
{80821}{80888}Njezin muû je glumac.|Dobri su ljudi.
{80899}{80986}RazgovaraÊu s njom.|ñNe zaboravi da ih objese ako pomaûu ûidovima.
{81660}{81696}Na lijevo!
{81721}{81766}KoraËajte! Marö!
{81886}{81912}Stoj!
{82122}{82162}To su sami bolesnici!
{82289}{82320}Na desno.
{82530}{82583}Korak naprijed! Ti!
{82918}{82947}Lezite na tlo!
{83704}{83811}Na lijevo! Red, marö!
{84802}{84838}Kako dugo si tu?
{84860}{84961}Od sinoÊ.|Drago mi te vidjeti.
{85086}{85139}PoËeli su konaËno preseljavanje.
{85212}{85248}Znamo, öto to znaËi.
{85294}{85390}Zigmunta smo poslali van.|Dobar Ëovjek.
{85448}{85517}Morao je doÊi vlakom iz Varöave.
{85561}{85669}Doöao je do Sokolova.|Tamo se pruga raËva.
{85685}{85731}Jedan krak vodi u Treblinku.
{85777}{85852}Teretni vlakovi svaki dan|voze ljude iz Varöave
{85860}{85952}u Treblinku, a vraÊaju se prazni.
{85974}{86036}Na toj pruzi nema nikad transporta hrane.
{86064}{86153}Postaji u Treblinki,|ali se nitko ne smije pribliûiti.
{86247}{86280}Istrebljuju nas.
{86395}{86430}NeÊe dugo trajati.
{86492}{86563}Od pola milijuna ostalo nas je|samo 60.000.
{86595}{86719}Najviöe mladih.|Ovaj put Êemo se boriti.
{86804}{86844}U dobroj smo formi,
{86875}{87002}organizirani, spremni.|- Ako trebate pomoÊ...
{87174}{87221}Hajdemo, brûe!
{87502}{87572}Ti! Doi ovamo!
{87610}{87638}Sranje.
{87850}{87899}éao mi je. Oprostite.
{87938}{87978}Ne znam, öto sam mislio.
{88086}{88161}Molim, ne! Nikad!
{88674}{88710}Stavite ga na stranu.
{89112}{89179}Nadam se, da sviraö klavir bolje,|nego öto nosiö cigle.
{89247}{89320}NeÊe dugo izdrûati.
{89350}{89425}PokuöaÊu mu naÊi neöto bolje.
{89926}{89947}Nevolje!
{89966}{90039}Svi éidovi, zbor! Samo éidovi!
{90078}{90144}Poljaci, nastavite raditi!
{90169}{91669}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/8v9w5|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
