{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{780}{899} LEDENA | PRINCEZA 
{3356}{3396}Casey?
{3455}{3518}- Neöto nije u redu, g. Bast?|- Ne, sve je u redu.
{3523}{3598}Samo se pitam jesi li razmiöljala o|opcijama za koledû.
{3602}{3648}Opcijama? Uh...
{3652}{3712}Jesi li Ëula za Helen Stoler ökolarinu|iz fizike?
{3715}{3739}Ne.
{3743}{3835}Daje se studentu iz ove drûave|koji najviöe obeÊava u nauci.
{3839}{3907}Zar to ne bi bili En ili... Vyat?
{3910}{3955}Ne, to si ti.
{3959}{4014}Ti imaö poziv, Casey.
{4017}{4071}Stvarno?
{4075}{4121}- Koji je to?|- Fizika.
{4126}{4159}Tost?
{4163}{4224}- Uh... naravno.|- Ti si veoma sretna.
{4229}{4299}VeÊina ljudi traga cijelog ûivota|za svojim pozivom.
{4302}{4390}- Kako znaö koji ti je poziv?|- Tvoj briljantni profesor ti kaûe.
{4393}{4480}I, naravno, tvojih 11 uzastopnih 5+ na|ispitima je pomoglo.
{4483}{4550}Trebat Êe ti pismo|od mene za ökolarinu
{4554}{4632}i razmisli o specijalnom projektu|iz fizike preko ljeta.
{4635}{4698}Neöto neobiËno ali osobno.
{4703}{4762}Pusti ih da te malo upoznaju.
{4766}{4833}- Rekao je da je to moj poziv.|- VLP.
{4836}{4934}Kako je ovo ''vrlo lako predvidljivo''?|Ti si dobra iz fizike kao i ja.
{4938}{4998}Ni blizu. Ja meljem, ti kliziö.
{5027}{5066}Savröen vidik.
{5128}{5205}Jednog dana Êe se taj deËko probuditi|i shvatiti da mu treba tutor za matematiku.
{5208}{5256}A taj tutor Êu biti ja.
{5277}{5383}IzraËunaj kako da nas pozovu barem|na jednu zabavu i dobit Êeö Nobela.
{5847}{5894}Hej, ti si Casey, zar ne?
{5899}{5949}A - ha.
{5953}{6035}Evo pozivnica za zabavu mog deËka.
{6039}{6075}Opa.
{6079}{6138}Ti si zajedno na kemiji sa|Julianom Vilson, jel' tako?
{6143}{6187}- Mm-hm.|- Da li mu moûeö dati to?
{6191}{6237}Hvala.
{6299}{6359}To je bilo stvarno bezobzirno.
{6363}{6411}Volim g. Basta.
{6415}{6504}Poöto je on otkrio ökolarinu, za koju ja|nisam znala, on je genije.
{6508}{6563}l kad zamislim samo|kako ga malo plaÊaju.
{6567}{6670}Gubitak vrijednosti profesora u naöem|druötvu je, jednostavno...
{6675}{6711}- Ubija me u mozak.|- Mama.
{6716}{6780}PovlaËim to. Oprosti.
{6827}{6882}Moram provaliti öto on hoÊe od mene.
{6885}{6948}Mislim, öto je to osobni nauËni projekt?
{6952}{7071}Zar priroda nauke ne treba biti|bez predrasuda i istinita?
{7075}{7123}Sad on hoÊe moje unutraönje ja?
{7127}{7242}Sva tajna u prouËavanju prirode leûi|u uËenju kako da koristiö svoje oËi.
{7246}{7315}- Da li znaö tko je to rekao?|- Pretpostavljam da je ûena.
{7319}{7410}To je napisao George Sand, ûena koja|je prisiljena koristiti muöko ime...
{7415}{7461}jer je jedino tako mogla izdavati.
{7466}{7512}- Mama.|- Ok.
{7517}{7570}Uostalom, ja uvijek kaûem|mojim studentima,
{7573}{7662}''Znat Êete vaöe predmete kad nauËite|koristiti vaöe oËi.''
{7827}{7873}Oh! Oh, ne...
{7877}{7929}Bila se dobro namjestila.
{7933}{8032}Moram jesti sladoled, a sve öto tvoja|majka ima je zaostale mlijeËne karamele.
{8035}{8104}- HoÊemo li iÊi?|- ä! ä!
{8109}{8160}Pogledaj kako se oporavila!|Nevjerojatno.
{8165}{8214}Joö uvijek Êe se rangirati.
{8247}{8350}Tako je precizna.|Mislim, do posljednjeg...
{8452}{8500}Znaö...
{8503}{8607}Kladim se da postoji toËna|aerodinamiËka formula.
{10860}{10919}- äto to misliö da radiö?|- Ja... ja.
{10922}{10989}- Zaöto snimaö klizaËice?|- Za projekt iz fizike.
{10992}{11108}- Gledala si njen trostruki okret. Zaöto?|- Ne, analiziram njeno kretanje.
{11112}{11162}- Za koga radiö?|- Ni za koga.
{11187}{11266}Teddy, doi ovamo.|Pozvat Êu policiju.
{11270}{11333}Ne, nisam znala da Êe to biti problem.
{11338}{11388}Mislila sam da je ovo javno klizaliöte...
{11414}{11476}Privatno vjeûbanje je od 6 do 10.
{11480}{11552}Ove djevojke treniraju za|regionalno prvenstvo,
{11556}{11611}öto mislim da jako dobro znaö.
{11615}{11695}Ne, ja sam student.|Imam legitimaciju.
{11759}{11799}Imam biljeûnicu.
{11957}{12000}Opa, da.
{12004}{12074}Definitivno öpijunske öifre.
{12078}{12149}- äto ti radiö ovdje?|- Znaö je?
{12154}{12198}Ona je ötreber za nauku.
{12360}{12442}Gledaj, ûao mi je, ali kad ClA|hoÊe nauËiti nove prljave trikove,
{12446}{12494}oni osmatraju klizaËice i njihove mame.
{12497}{12546}- Tina, Da li moûemo popriËati?|- Frenk, ne sad.
{12551}{12614}HoÊu digitalizirati neke slike u moj|kompjuter...
{12617}{12687}da vidim hoÊe li se pojaviti neka|zajedniËka teorija.
{12691}{12746}Ok, ako te Gen zna i ako hoÊeö...
{12749}{12834}buljiti kroz staklo i hvatati biljeöke,
{12838}{12878}ne zanima me.
{12883}{12943}Ali morat Êeö uvjeriti roditelje.
{12997}{13041}Apsolutno ne.
{13045}{13166}Ali nitko izvan komiteta za ökolarinu|neÊe vidjeti ovaj projekt.
{13171}{13285}Evo pismo od mog profesora|koje objaönjava zadatak.
{13318}{13378}I moja vozaËka dozvola.
{13382}{13490}Um... Imam i neke preporuke|od ljudi gdje sam bebisiterica.
{13590}{13698}MoguÊe je. Vidjet Êemo da naö legalni|tim provjerava ovo.
{13860}{13921}Nema priËanja sa mojom kÊerkom.|Ona trenira.
{13925}{13972}Nema ometanja.
{14002}{14055}Ni rijeËi. Ne.
{14145}{14194}Gledaj, ne zanima me ako si ovdje.
{14198}{14264}Ali ako me staviö na ökolski vebsite|kako padam na dupe,
{14267}{14343}bolje traûi novu ökolu.
{14614}{14666}Hej! Ne moûeö sa uliËnim|cipelama na led!
{14756}{14834}éao mi je... Oprosti.
{15307}{15343}Bok, srce.
{15348}{15392}Gen!
{15396}{15482}Gen! Briane, ona trenira.|Znaö pravila.
{15487}{15548}- Donio sam joj hamburger, go. H.|- Gen ne moûe to jesti.
{15553}{15638}- Hajde, sagorijevam tone kalorija.|- Nije dovoljno.
{15642}{15692}- Pola sata?|- Ne ako hoÊeö pobijediti.
{15696}{15785}Trebali bi trenirati naö koöarkaöki tim.|Koristio bi nam udarac u dupe.
{15789}{15871}Ako ne odeö ovog trenutka, upravo|to Êeö i dobiti.
{16002}{16046}Bok.
{16197}{16255}Ne ûelim da dolazi ovdje tokom vjeûbi.
{16259}{16342}Ali nikad ga ne viam.|Sve djevojke koje znam...
{16347}{16450}Ti nisi kao ostale djevojke.|Pobjednici se ûrtvuju.
{16454}{16494}Moûda samo varaju.
{16562}{16614}- IskljuËi to!|- Oprostite.
{16618}{16665}PoËni odakle si stala.
{17231}{17278}ZakljuËak je jednostavan.
{17281}{17320}KinetiËka energija u skoku...
{17324}{17403}jednako je pola klizaËeve mase|puta ubrzanje na kvadrat, minus...
{17407}{17466}Ne, jedva te razumijem.
{17470}{17503}Ali...?
{17506}{17596}Ne znam da li ih je briga|ali je malo previöe...
{17615}{17651}...suho.
{17655}{17710}G. Bast kaûe da ga moram|uËiniti osobnim.
{17714}{17790}- Kako da to napravim?|- Ne znam.
{17794}{17837}Unesi malo viöe sebe u to.
{17918}{17977}Oh, oprosti, Tina.
{17983}{18054}Da li mogu uzeti nekoliko sati?
{18059}{18141}Mislim da Êu moÊi bolje pisati|o principima fizike...
{18145}{18192}ako ih ja primjenjujem.
{18195}{18246}- Da li postoji neki naËin da...|- U redu.
{18250}{18307}PoËinjemo sa satovima|za poËetnike na ljeto.
{18311}{18350}Tri popodneva tjedno.
{18355}{18396}$800.
{18421}{18464}$800?
{18467}{18540}- Kokice! HoÊu kokice!|- Gdje su moje gumeni medvjediÊi?
{18544}{18615}- Dala sam ti ih.|- »etiri hot doga!
{18619}{18689}- Oh, oprosti...|- Pipnula si ih sa prstima.
{18694}{18746}Oh, u redu. NeÊeö ga?|Ja Êu ga pojesti.
{18750}{18802}Oh, dahnula si na njega!
{18855}{18898}Ne bi trebalo raditi ovdje.
{18960}{19003}Ti si i ovdje?
{19007}{19105}Um... Ja radim.|Za moj nauËni projekt.
{19109}{19174}Zar ne pretjerujeö sa tim projektom?
{19177}{19263}Ne, totalno sam posveÊena tome, kao|öto ste vi klizanju.
{19267}{19360}Nije vaûno. Ja sam gladna.|B.L.T. Ovdje. Zadrûi B, dodaj viöe na L.
{19363}{19399}Um... naravno.
{19404}{19499}Goveu paötetu.|Iscijedi je dok ne bude suha. Bez lepinje.
{19503}{19552}- Salata za mene.|- Stiûe.
{19557}{19666}Samo ledenu salatu, pola tanjura|sosa i limun na rubu.
{19670}{19773}Oh, i Ëetvrtinu tanjura sira.
{19776}{19818}Uu, sir!
{19821}{19892}Subota je.|Mogu se usvinjiti ako hoÊu.
{19895}{19956}Ne znam öto ne valja.|Izvodim moj luc.
{19960}{20009}Sve je to zbog sira.
{20012}{20068}HoÊeö li umuknuti?
{20071}{20166}Moram se usredotoËiti. »ula sam da je|Zoi Bloh izvela Ëetverokut.
{20171}{20242}To je glasina.|Koju je vjerojatno ona sama zapoËela.
{20247}{20299}Rano je za mozgalice u ovoj sezoni.
{20303}{20378}- Ne za Zoi.|- Hrana je spremna!
{20523}{20594}Ovo je viöe nego Ëetvrtina tanjura.
{20599}{20660}Um... To je $1.65,
{20664}{20706}$2.35 i $3.35.
{20710}{20830}To je $ 7.30. lli ako Êete podijeliti|drugaËije, to je $1.75 i $5.55.
{20834}{20934}Opa. Moûeö zadrûati sve samo|prestani raditi to.
{21014}{21060}Nema na Ëemu.
{21150}{21238}U redu, svi.|Dobrodoöli na naöe satove.
{21242}{21290}Poredajte se.
{21469}{21507}Izgledate dobro.
{21574}{21681}Da li moûete reÊi naöem asistentu|najvaûnije pravilo ovog odjeljenja?
{21685}{21736}- Mama...|- Nikad ne kasni.
{21741}{21819}ToËno. Imamo puno za napraviti...
{21823}{21911}ako ûelimo biti|spremni za naö recital u kolovozu.
{21916}{21987}Radit Êemo na naöem skoku sa prstiju.
{22064}{22113}Naöem lucu.
{22254}{22328}Ali prvo, morate se osjeÊati ugodno...
{22331}{22409}kad bacate tijela u zrak.
{22412}{22463}Casey, ti si mag za fiziku.
{22467}{22521}Kakvo je pravilo za ono öto ide gore?
{22526}{22589}TehniËki,|svaka Ëestica privlaËi...
{22594}{22625}Casey.
{22666}{22699}Mora pasti dolje.
{22828}{22911}Ovo... je vaö novi najbolji prijatelj.
{23262}{23315}Oh! Oh...
{23319}{23378}Gledajte, Da li moûete probati da|me ne zgnjeËite?
{23382}{23409}Oprosti.
{23415}{23501}Casey. Sastavi malo ruke.|One te izbacuju iz ravnoteûe.
{23506}{23545}- Ruke unutra.|- Ok.
{23549}{23607}Sad probaj to oko 5,000 puta.
{23611}{23691}- U redu.
{23835}{23899}Jeremy!|Taj vrh na klizaljkama je tu sa razlogom!
{23904}{23983}Ukopaj ga.|lli nema prijatelja ovaj tjedan.
{24019}{24066}Ovo je previöe pritiska za recital.
{24070}{24186}To nije obiËan recital.|To je U.S.F.S.A.J.S.T.
{24191}{24227}Zemaljskim govorom, molim te?
{24231}{24335}To je prvi korak u kvalifikacijama za|regionalno takmiËenje.
{24339}{24409}- Mislim za nas djecu.|- Oh.
{24413}{24475}- Vi ne morate to raditi.|- Dobro je.
{24479}{24526}Zato öto je to nemoguÊe.
{26453}{26496}Jesi li siöla sa uma?!
{26655}{26763}Hej, zar ne znaö?|Nema klizanja kad Zamboni nije tu.
{26767}{26828}U redu sam. U redu.
{26831}{26898}- Hvala ti.|- Oh, u redu si?
{26918}{26944}Ok.
{26947}{26990}Oprosti.
{27111}{27190}HoÊeö mi reÊi öto ti je u glavi?
{27194}{27269}Nikad nisam klizala na|tako glatkoj povröini.
{27273}{27338}Htjela sam vidjeti kako to izgleda.
{27343}{27418}- Kliûeö na jezeru?|- Na bari. Blizu moje kuÊe.
{27460}{27558}- Treba ti pomoÊ.|- Ne! Spremna sam krenuti.
{27626}{27666}Oh!
{27827}{27880}Mora da stvarno ûeliö tu peticu.
{27943}{28015}Opa, to je puno stiropora.
{28043}{28127}To nije za peticu.|To je za ökolarinu iz fizike.
{28171}{28298}äto, kao, uh...|inercija, masa, ubrzanje i to?
{28301}{28356}- Kako ti znaö za to?|- Ja sam u automobilima.
{28360}{28429}Izvedem ovu bebicu na put i mogu|je izvuÊi do...
{28432}{28469}...sedam milja na sat.
{28472}{28565}Otpuöem sve ËistaËe ulica u gradu.
{28755}{28826}Um... Trebala bih iÊi kuÊi.
{28829}{28872}Da, trebala bi.
{28923}{28973}Ne mogu oËistiti led dok ti ne sieö.
{28978}{29026}ToËno.
{29031}{29064}Naravno.
{29067}{29116}Pa...
{29463}{29513}Kako ide?
{29517}{29558}Ide.
{29597}{29653}Potreban je nevjerojatan trening i trud...
{29657}{29714}i tu je umjetnost ukljuËena, ali|ûao mi je,
{29719}{29792}ne mogu prijeÊi preko te male|oskudne odjeÊe.
{29798}{29881}Mama, ona je, u stvari,|veoma dinamiËno napravljena.
{29887}{29954}VraÊa te unatrag 50 godina.
{29959}{30058}Ako te ikad budem vidjela stisnutu u ove|stvarËice, poËet Êu plakati.
{30062}{30121}Vjeruj mi, neÊeö nikad.
{30176}{30227}HoÊeö odspavati malo?
{30231}{30243}Molim te?
{30263}{30289}Zdravo.
{30293}{30345}Ovo je moja video prezentacija.
{30348}{30402}Bok. Ja sam Casey Carlyle.
{30407}{30448}Sijeci na trenutak.
{30452}{30500}ZvuËim kao drive in filmovi.
{30503}{30559}Opusti se.|Radi to kao da razgovaraö sa mnom.
{30563}{30620}Bok. Ja sam Casey.
{30656}{30715}Oh, boûe.|Zaboravila sam moje prezime.
{30719}{30745}Da li mogu ispoËetka?
{30750}{30809}Bok. Ja sam Casey Carlyle.
{30814}{30910}OdluËila sam vidjeti da li mogu|dokazati vlastitu hipotezu...
{30915}{30954}primjenjujuÊi fiziku...
{30958}{31034}na zahtjevne elemente u|umjetniËkom klizanju.
{31094}{31158}Sad Êu poveÊati centripetalnu silu...
{31162}{31209}skupljajuÊi moje ruke.
{31213}{31273}Ovo Êe poveÊati moment inercije,
{31277}{31330}pa Êu se zavrtjeti...
{31335}{31358}...brûe.
{31363}{31481}PoveÊat Êu visinu mog skoka|dodajuÊi veÊu silu na vrh palca.
{31607}{31674}- Znaö, izgledaö priliËno opasno.|- Umukni.
{31677}{31769}PoËet Êu sa jednim loöijim.|To je za probu.
{31864}{31923}- Da, taj si priliËno uprskala.|- Ok.
{31927}{31999}- Sad si me naljutila.|- Dobro je.
{32597}{32716}Kad potpiöeö za Nike,|sjeti se da ja nosim veliËinu öest i pol.
{32777}{32837}HoÊu raditi recital.
{32841}{32881}Zbog nauke.
{32917}{32977}Budi ovdje veËeras, u 5:30.
{33003}{33038}Ok.
{33066}{33182}Mm! Tina... Imam Ëajanku|za pitomce na Harwardu u tri.
{33186}{33229}Onda, o Ëemu priËamo?
{33232}{33295}Ne, u redu je. StiÊi Êu.
{33327}{33384}Um...
{33387}{33450}Nemaö niöta za  obuËi.
{33455}{33537}Doi kod mene u podne. Moûda Êe|ti neke moje stare stvari odgovarati.
{33541}{33601}Opa. Ok.
{33713}{33738}äto?
{33782}{33812}Hvala!
{34261}{34323}- Duöo?|- Samo trenutak!
{34492}{34524}SaËekaj malo!
{34551}{34610}- Skoro spremna?|- A-ha.
{34615}{34682}Imam iznenaenje za tebe.
{34866}{34910}To je to.
{34914}{34946}Savröeno.
{34950}{35010}Mislim daje cijeli efekt,|veoma odrastao,
{35015}{35076}sa toËkom na ûenstvenoöÊu.
{35081}{35157}Prerasli smo öepurenje,|ali ne moramo ga poricati.
{35161}{35204}Mislim, kretat Êeö se meu...
{35207}{35307}buduÊim perspektivnim kolegama i|profesorima,
{35312}{35406}i hoÊu da kaûu kad te pogledaju,|''Mi smo ozbiljni.''
{35412}{35459}Pa, definitivno smo uspjeli.
{35494}{35586}Mama, ne moramo ostati na|ovome viöe od sata, zar ne?
{35590}{35670}Um, zato...|htjela sam ti neöto reÊi.
{35674}{35762}Oh... Oh, duöo.
{35766}{35829}- Zbog Ëega je to?|- Tako sam se brinula.
{35832}{35935}éivjela si u tom klizaliötu,|ali sad si ovdje.
{35940}{36052}I uzbuena si, zato öto znaö|öto je u stvari vaûno.
{36057}{36105}Gledaj, prekrstila sam palËeve.
{36179}{36264}Oprosti, to je bilo jaËe od mene.|Oboljenje mama.
{36269}{36341}Samo se opusti. Budi ono öto jesi.
{36347}{36418}Ti si normalna, stabilna, öarmantna,|komunikativna...
{36423}{36450}Mama...
{36454}{36517}Da li hoÊeö joö jednom|da se presliöamo?
{36555}{36618}Bok. Ja sam Casey Carlyle,
{36622}{36709}i ja sam privuËena ovim programom za|fiziku, zbog...
{36712}{36753}Fizika rastura.
{36756}{36839}Na drugoj godini, moûeö se pridruûiti|Kvantum klubu, i to rastura...
{36843}{36929}jer se takmiËimo protiv|Kal Teka, MlT-a i Stenforda.
{36933}{37009}Proöle godine, naö akcelerator ionskih|Ëestica, je zauzeo prvo mjesto.
{37013}{37044}Rasturao je.
{37048}{37128}ZvuËi stvarno, um... razbijajuÊe.
{37133}{37173}Da, stvarno jest.
{37177}{37287}Znate öto mislim da je sjajno?|Ako Caseyna ökolarina uspije,
{37291}{37426}OsjeÊam da Êete vas dvije provoditi|puno vremena zajedno.
{37467}{37524}éele?
{37527}{37599}Oh, kako divno, u grozdovima.
{37626}{37674}Ako imate vremena sad,
{37679}{37770}Provest Êu vas kroz cijeli|nastavni program fiziËke nauke.
{37776}{37886}Mi nemamo niöta osim vremena!|Zar ne, Casey?
{37891}{37923}Sjajno!
{37983}{38042}Znam da kasnim. éao mi je.
{38046}{38113}To je prvo pravilo.
{38196}{38277}U redu, spremite se.|Idemo.
{38857}{38904}Duboko udahni.
{38998}{39050}I sad pusti van.
{39055}{39113}- Nije uspjelo.|- Idemo.
{39154}{39197}U redu, svi.
{39200}{39253}Ja Êu to uzeti.
{39256}{39299}- Sretno.|- Hvala.
{39563}{39587}Bok.
{39989}{40039}Mama...
{40043}{40093}Da li je to ona obukla tvoj stari kostim?
{42551}{42596}Bravo!
{42667}{42698}Da!
{42937}{43039}- Koji je moj rezultat?|- Kako sam proöla?
{43043}{43078}Kako sam proöla?
{43081}{43136}''Dozvola za poËetnike.'' Da!
{43139}{43238}- Casey, kako si ti proöla?|- Dobro, pretpostavljam.
{43242}{43307}Piöe...''Dozvola za juniore.''
{43355}{43429}- äto?|- PreskoËila si dva nivoa.
{43488}{43586}- Zaöto ja nisam preskoËila dva nivoa?|- Zato öto imaö 6 godina, Lili.
{43591}{43667}Juniorski nivo je na kome su|Gen, Nikki i Tif.
{43710}{43793}Da li je to toËno, Tina?|Da sam na juniorskom nivou?
{43855}{43893}Da, toËno je.
{43896}{43966}U redu, idemo se svi presvuÊi.
{43969}{44058}Hajde. Idemo svi.
{44061}{44110}ZnaËi, ako ja...
{44137}{44205}- Ako se hoÊu takmiËiti?|- Ne moûeö.
{44211}{44268}Zaöto ne?
{44272}{44370}Ono öto se desilo je, da su suci vidjeli|ono öto ja gledam cijelo ljeto.
{44374}{44469}Imaö sirovog talenta. Ali to nije dovoljno|da bi probala na regionalnom.
{44472}{44591}Treba ti trener, pomoÊnik,|koreograf, privatno vrijeme na ledu.
{44595}{44666}Nikkini roditelji su uzeli drugu hipoteku|zbog ovoga.
{44670}{44729}- A Tifanin tata radi dva posla.|- Oh.
{44734}{44807}- Gdje si nabavila te klizaljke?|- Garaûna rasprodaja.
{44811}{44907}Spadaju ti sa nogu.|Trebaju ti ruËno pravljene, $600 minimum,
{44911}{44973}a oötrice se trebaju|oötriti svakih öest tjedana.
{44978}{45057}Jel' razumijeö?|Oprosti. Tako je kako je.
{45083}{45162}Moraö ûeljeti to. Moraö|ûeljeti viöe od bilo Ëega drugog.
{45166}{45226}To nije neöto öto radiö iz uûitka.
{45459}{45541}Znaö öto ja mislim,|gice starija?
{45545}{45643}Ovo je posljednji prvi dan ökole.
{45647}{45750}Zato öto Êeö sljedeÊeg prvog dana,|biti u studentskom domu.
{45755}{45809}Pa sam malo poludjela.
{45814}{45894}Napravila sam palaËinke|sa bijelim braönom.
{45946}{46007}Jel' moûete vjerovati da je ljeto gotovo?
{46011}{46077}Tratimo ûivote ovdje.
{46203}{46264}- »ula sam da si napravila dupli.|- Tif!
{46268}{46358}- Pa? Za to mi je trebalo dvije godine.|- Stvarno?
{46363}{46467}- Pa znaËi viat Êemo te?|- Ne, neÊete.
{46471}{46537}Ne na klizaliötu.|Ne mogu trenirati sa vama.
{46540}{46585}Zaöto ne?
{46590}{46648}Um, ne mogu si priuötiti to.
{46651}{46710}- Oh!|- Da.
{46714}{46773}Ali... bilo je zabavno.
{46868}{46981}Gledaj, Casey.|ReÊi Êu ti neöto, u redu.
{46984}{47043}Ne znaö koliko si sretna.
{47047}{47116}- Zbog Ëega?|- Zato öto imaö ûivot.
{47119}{47205}- Misliö da ja imam ûivot?|- Znam da imaö.
{47209}{47292}Imaö vrijeme za TV, za prijatelje...
{47295}{47348}Ali vi moûete klizati koliko hoÊete.
{47352}{47411}I viöe nego öto ûelimo.
{47416}{47470}Voljela bih da budem ti.
{47475}{47570}Imaö subotu naveËer,|viaö deËka...
{47575}{47649}- Da...|- Jedeö öto hoÊeö.
{47652}{47719}Na primjer kruh.|Korpe i korpe kruha.
{47723}{47796}Oh, buu - huu - huu! Koga briga?
{47799}{47847}Koga briga za te stvari?
{47850}{47910}Zar ne ûelite klizati svo vrijeme?
{47954}{47991}- Ne.|- Ne.
{47995}{48084}äto je sa vama ljudi?|Jeste poludjeli?
{48088}{48146}SkakajuÊa äkamp je klizajuÊa maöina.
{48150}{48239}- ''SkakajuÊa äkamp''?|- Moja mama me tako zove.
{48244}{48274}Vidimo se.
{48279}{48312}Jezivo.
{48316}{48358}Moramo uËiti od nje.
{48361}{48454}Upravo ovo komitet za ökolarinu traûi.
{48458}{48554}Tvoj entuzijazam za projekt|jednostavno kipi sa stranica.
{48558}{48632}U stvari, toliko je dobro, da bi ga|vjerojatno mogla i prodavati.
{48678}{48737}Hvala.
{48801}{48837}- Tiffany.|- Hej.
{48841}{48899}äto kad bih ti rekla da mogu|ispraviti tvog Raöirenog Orla?
{48929}{49003}Jel' bi htjela nauËiti kako da ne praviö|previöe koraka na tvom sjedeÊem spinu?
{49009}{49042}Ne pravim!
{49144}{49215}Pa, moûda i pravim.
{49276}{49319}Mogla bi napraviti dupli axl.
{49323}{49356}»ist.
{50157}{50191}I ona se vratila!
{50251}{50303}Kakvo si napravila vrijeme na klizanju?
{50307}{50353}Fizika!
{50357}{50441}Prodajem moj nauËni projekt.
{50490}{50549}Gledaj, izrezbarila si moj lijepi glatki led.
{50597}{50667}Ali, znaö, nije mi bilo tako teöko|dok sam te gledao.
{50695}{50743}Casey!
{50747}{50828}Mama? äto ti radiö ovdje?
{50831}{50915}Ortodontisti. Odijela za nove|noÊne Ëuvare. SjeÊaö se?
{50975}{51026}Evo.
{51031}{51090}äto... äto se dogaa ovdje?
{51176}{51208}Tko je ovo?
{51254}{51324}- Uh...|- Teddy.
{51329}{51365}ToËno. Teddy.
{51369}{51432}Teddy vozi Zamboni.
{51437}{51478}Teddy vozaË Zambonija.
{51482}{51543}Mislila sam da radiö na tvom projektu.
{51547}{51604}I je.
{51607}{51655}Vaöa kÊerka je veoma talentirana.
{51736}{51797}A... vi ste...?
{51801}{51866}- Tina.|- Tina Harwood?
{51870}{51936}- Da.|- KlizaËica.
{51939}{51971}Da.
{51975}{52087}Sa onim trofejima i malim odjelcima.
{52147}{52171}Da.
{52323}{52376}Pa, nemojte da vas prekidam.
{52380}{52483}- Nastavite sa vaöom zabavom ovdje.|- Hvala vam. HoÊu.
{52548}{52646}- Hajde, mama.|- Da. Da, naravno.
{52668}{52698}Bok.
{53520}{53599}Ok. Moraö drûati koljena sastavljena,
{53603}{53666}i ispraviti nogu,|tako Êeö se brûe okretati.
{53670}{53703}Ok, to je lako.
{54058}{54103}Bolje?
{54107}{54164}Savröeno.
{54911}{54986}- Uspjelo je!|- Kao öto si rekla da Êe biti.
{54990}{55097}Kompjuter ne pravi skokove.|To si sve ti.
{55155}{55235}Hajde, mama, samo ovaj put.|Vratit Êu se do 11.
{55239}{55294}Imaö trening sutra u 5:30.
{55298}{55407}Misliö da Êeö biti orna za njega|ako te pustim cijelu veËer van?
{55438}{55502}Mama, izvela sam axl.
{55506}{55584}Jel' mogu dobiti samo|jednu subotu naveËer, molim te?
{55706}{55758}Sa kim ideö?
{55761}{55807}Bok, um...
{55811}{55901}- Da li hoÊeö da izaemo veËeras?|- Sa tobom?
{55905}{55957}Da, znaö, da pojedemo neöto.
{55961}{56057}- Moûda odgledamo film ili neöto.|- Um... Da.
{56109}{56170}- Ali...|- Evo nas...
{56175}{56230}Ovo ne izgleda kao film.
{56252}{56299}Gen!
{56321}{56361}Gen!
{56399}{56442}Gen!
{56469}{56494}Gen!
{56511}{56539}Ja, um...
{56543}{56596}Nisam obuËena za zabavu.
{56635}{56670}Protresi je.
{56739}{56779}Tvoju kosu.
{56874}{56926}Sad, nitko neÊe primijetiti.
{56930}{56972}Radi sa kosom.
{57131}{57176}- Bok.|- Bok.
{57280}{57329}Ne znam nikog od ovih ljudi.
{57334}{57393}Naravno, da znaö.|Svi su u tvom razredu.
{57397}{57457}Ono je... Jason, ragbi.
{57461}{57505}I Luk, nogomet.
{57509}{57571}Znam ih ali...|Ja zapravo ne priËam sa njima.
{57575}{57635}Ja ne priËam sa momcima ili... ljudima.
{57639}{57726}Pa, sad bi bio savröen|trenutak da poËneö.
{57773}{57823}- Hej, Kyle.|- Hej.
{57865}{57899}Casey.
{58008}{58079}Casey, Kyle. Kyle igra hokej.
{58082}{58120}- Casey kliûe.|- Hej.
{58124}{58189}Vi imate puno zajedniËkog.|Zabavite se.
{58216}{58260}Ali... Ja...
{58264}{58298}Briane!
{58403}{58505}- ZnaËi kliûeö, a?|- UmjetniËko... klizanje.
{58509}{58555}- UmjetniËko klizanje.|- Oh.
{58560}{58618}Ne bih ûelio da ostali u timu Ëuju ovo...
{58623}{58687}ali vi bi mogli vjerojatno klizati|u krugovima oko nas.
{58692}{58738}Ali da ne guramo pak.
{58875}{58922}Zaöto ne doeö na naöu|sljedeÊu utakmicu?
{59075}{59114}- O-o.|- äto?
{59163}{59234}Pa, pretpostavljajuÊi da je|njegova teûina oko 150 libri,
{59238}{59333}pri toj brzini spuötanja, njegova|vjerojatna putanja Êe ga dovesti...
{59337}{59395}...direktno kroz prozor.
{59401}{59430}Uuh!
{59497}{59605}Mislim, jednostavno je|V puta M jednako je A.
{59609}{59696}Znaö, brzina puta pokretna sila|jednako je ubrzanje.
{59699}{59727}Fizika.
{59731}{59786}Da, moram da, um...
{59844}{59880}Da, kasnije.
{59911}{59943}Jel' znaö tko je to bio?
{59947}{60005}- To je bio Kyle Dayton.|- Previöe zgodan.
{60009}{60066}Mali savjet.|Nemoj nikada viöe progovarati.
{60070}{60129}Kad se unervoziram,|brbljam pomalo.
{60133}{60179}Kao da se kotaËiÊi|u mojoj glavi otkaËe.
{60184}{60233}Kao oni Plankovi dijagrami, gdje...
{60238}{60290}Ponovo brbljaö.
{60295}{60352}Ja mislim da je brbljanje cool.
{60397}{60454}Hajdemo, Casey.
{60478}{60522}Hvala.
{60867}{60958}ZnaËi ti si veËeras Genina zaötita?|To je obiËno moj posao.
{60962}{61022}Mogla me je upozoriti|da idemo na zabavu.
{61027}{61102}Znaö, moja sestra ima svojih problema.
{61107}{61167}- Tvoja sestra?|- Da.
{61172}{61245}- Ti si Tinin sin?|- Da li je to toliko teöko povjerovati?
{61249}{61318}Ne, ne, samo sam...
{61323}{61373}- Samo sam mislila...|- Da sam posluga?
{61420}{61534}Mislim, i jesam.|Gen kliûea a ja popravljam stvari.
{61567}{61618}Pa, veÊinu stvari.
{61813}{61906}Predmet je jak samo koliko i|njegova najslabija toËka.
{61944}{61980}Fizika.
{61984}{62030}Hvala.
{62109}{62160}U redu, pa...
{62164}{62217}PriËaj mi o, um...
{62220}{62262}...popravljanju stvari.
{62309}{62405}Pa, klizaliöte je bilo rupa|kad ga je mama kupila.
{62410}{62464}Uglavnom sa njenom lovom od razvoda.
{62467}{62543}Ja sam pomogao da se povrati.|Vröio sam popravke, farbanje...
{62547}{62616}Zamboni.|To je bio moj omiljeni dio.
{62670}{62760}ZnaËi, za tebe je to nauka?
{62809}{62859}Mm... tako je.
{62892}{62946}- Oprosti.|- Ah!
{63098}{63156}Ne moûeö siÊi sa leda, zar ne?
{65155}{65202}- Bok.|- Gdje si bila?
{65207}{65235}Ostala sam kasnije u ökoli.
{65239}{65318}Ne, gdje si bila cijeli tjedan?
{65322}{65397}Ovo me je jednostavno razvuklo.
{65400}{65516}Zaöto to radiö? Taj deËko je|najtupaviji osmaö na planeti.
{65519}{65584}Mama, to izgleda dobro|na mojoj aplikaciji.
{65588}{65634}I En to radi.
{65699}{65751}En je sad bila sa tobom?
{65755}{65849}- Da. Prije pet minuta.|- En te je upravo zvala.
{65911}{65978}- äto se dogaa?|- Niöta.
{65982}{66054}I otkad ti dobivaö trojku na testu?
{66058}{66134}Vidjela sam u tvojoj sobi.|I nisam njuökala.
{66138}{66209}Mislim, ti i petice ste kao putar i kikiriki.
{66213}{66254}- Jel' to zakasnjela pobuna?|- äto?
{66258}{66282}Da li...
{66325}{66387}...deËko?|- Mama, ne!
{66391}{66426}Oprosti.
{66430}{66522}ShvaÊaö öto stavljaö na kocku|sa ovakvim tvojim ocjenama?
{66526}{66566}Znam. Znam. Oprosti.
{66570}{66608}OsjeÊam se loöe zbog trojke, ok?
{66614}{66692}- Jel' moûeö malo ohladiti?|- Duöo!
{67283}{67334}Mama, samo se hoÊu|takmiËiti na regionalnom natjecanju.
{67339}{67417}Zaöto?|äto Êeö dobiti od toga?
{67505}{67567}- Dobra sam.|- ZnaËi, öto hoÊeö reÊi?
{67571}{67648}HoÊeö jednostavno odbaciti|cijeli plan za tebe,
{67651}{67751}izbaciti ökolarinu|i postati profesionalni sportaö?
{67795}{67911}Cas, koliki je radni vijek|profesionalne klizaËice?
{67915}{67956}Osam godina?
{67959}{68054}I poslije par godina|onoga bila sam na ledu.
{68059}{68163}I to je to?|To je kraj tvog ûivota?
{68168}{68200}Ja volim to, mama.
{68205}{68308}Cas, ne razmiöljaö o daljnjem ûivotu.
{68311}{68369}Da sam nauËila razmiöljati malo ranije,
{68372}{68438}da sam otiöla na koledû u|tvojim godinama,
{68442}{68505}moûda ne bi ûivjeli ovako.
{68508}{68566}äto fali tome kako ûivimo.
{68569}{68671}Nisam ti mogla dati Ëetvrtinu|stvari koje sam htjela.
{68675}{68722}Dala si mi sve.
{68763}{68827}Onda i ti meni moraö dati neöto.
{69855}{69910}Paûnja, klizaËi!
{69914}{69997}Puötat Êemo klasiËnu muziku|cijelim putem.
{70001}{70035}Oh, Mama!
{70040}{70098}Osim, naravno,|ako netko ne osvoji trofej.
{70102}{70190}- A onda je Outcast za tebe.|- Da!
{70195}{70251}l Ëepovi za uöi za mene.
{70294}{70397}- ZnaËi, pokupili smo i lutalicu.|- Hej.
{70400}{70500}- Zar tvoja mama ne ide?|- Ona nije baö za klizanje.
{70503}{70596}Pogodite? Toyota sponzorstvo,|to je zavröen posao.
{70601}{70652}Tako smo zaostali sa marketingom.
{70656}{70727}Radim dva posla zbog tebe, zato öto|vrijediö.
{70732}{70799}A vrijedit Êeö joö viöe ako pobijediö.
{70803}{70837}PriliËno oötro.
{70841}{70894}Misliö?
{70899}{70962}Hej, gledaj ovo.
{70966}{71008}Hej, Nikki.
{71011}{71087}Svi kaûu da Êemo ja i ti zauzeti|prvo i drugo danas.
{71152}{71193}Dobar pokuöaj.
{71295}{71352}- äto je to bilo?|- KlasiËna psihologija.
{71356}{71439}Omeköam malo takmiËenje da ne|budu opsjednuti pobjedom.
{71445}{71538}- Nemoj nikad pasti na to.|- Razumjela.
{71544}{71601}äto god da se desi u kratkom programu,
{71605}{71692}Ëak i ako padneö, samo reci|sebi da je to treÊina rezultata.
{71695}{71789}- Moûeö se otkaËiti tek poslije dugog.|- OtkaËiti poslije dugog. Ok.
{71792}{71841}Hej, puûu!
{71871}{71924}I ti ideö?
{71927}{71990}Pa, ne moram ako neÊeö.
{71994}{72072}Pa, moûeö ako se kombi|pokvari ili tako neöto.
{72578}{72682}Hej, to je Zoi Bloh,|iliti KlizaËki Lopov.
{72724}{72800}Vidi, vidi.|Zar to nije äepajuÊi Patuljak.
{72803}{72876}Zapravo je SkaËuÊi äkamp.
{72879}{72929}Kao da je to bolje?
{72933}{73007}- Ne priËaj sa njom, Nikki.|- I nemoj joj prilaziti.
{73013}{73058}Ne ûeliö izgubiti klizaljke.
{73063}{73121}Kao da moram ukrasti njene|klizaljke da bih pobijedila ovdje?
{73126}{73196}- lli bijedni kompjuterski program?|- Kako ona zna o tome?
{73199}{73267}Ima oËi na pozadini svojih rogova.
{73271}{73320}- Briöi, Harwoodova.|- Natjeraj me, Blok.
{73324}{73408}Ne prepiri se Genifer.|Znaö valjda i sama.
{73411}{73446}Zoi, hajdemo.
{73451}{73528}- Zamisli da si u...|- U mjehuru. Znam, mama.
{73531}{73594}- Zapamti, nemoj...|- Odstupati od programa.
{73598}{73659}I ako ne napraviö niöta osim pada...
{73663}{73739}To nije ni opcija. Znam, mama.
{73763}{73820}Gledaj me.
{73939}{74021}ZnaËi ti si ta koja pokuöava|bez trenera.
{74066}{74177}Samo sam ti htjela poûeljeti sreÊu.|Nije lako izaÊi tamo prvi put.
{74181}{74205}Hvala.
{74208}{74254}Moraö se koncentrirati.
{74259}{74340}I budi impresivna.|Postavi temelj za sljedeÊu godinu.
{74343}{74422}- SljedeÊu godinu?|- Nema öanse da se plasiraö ove godine.
{74427}{74510}Suci su veÊ sve rangirali|u svojim glavama.
{74538}{74596}Lijepe klizaljke.
{74697}{74733}Hej, hajde.
{74739}{74791}Joö jedna klasiËna psihologija.
{74795}{74883}Ova je stara, ''VeÊ si izgubila|zaöto se onda trudiö?''
{74887}{74912}Hajde.
{74989}{75086}Nemoj se uvrijediti.|Samo jedno malo pitanje.
{75091}{75114}äto?
{75118}{75180}Jesi li Ëula za olovku za oËi?
{75183}{75239}Ne joö. Casey!
{75243}{75282}Stani. Ne joö.
{75286}{75390}Stvarno cijenim trud, ali mislim|da nemaö na Ëemu toliko raditi.
{75511}{75557}- Ja...|- Ti si opasna ûenska.
{75561}{75630}Ali kloni se Briana. On je moj.
{75669}{75713}Teddy...
{75716}{75757}Teddyja moûeö.
{75760}{75794}Oh, um, ali ja ne...
{75799}{75914}Znaö, moûda nisam pametna kao ti,|ali nisam idiot.
{75993}{76081}''Dame i gospodo,''|dobrodoöli na 54. godiönje
{76084}{76161}Newenglandsko regionalno|takmiËenje u umjetniËkom klizanju.
{76166}{76222}Naö prvi klizaË|za kratki program...
{76227}{76309}je Zoi Bloh|iz Vorchestera, Masachusets.
{79655}{79729}Mi volimo klizanje i mi volimo zlato!
{80332}{80363}Da!
{81078}{81182}Ok, uöli smo. Definitivno prva Ëetiri.|Ideö po odjeljcima!
{81186}{81267}Jedino ako Sasha Koen ne doe sad.
{81271}{81295}Dobar posao.
{81299}{81332}Sretno.
{81450}{81563}''Naö zadnji klizaË je Casey Carlyle''|iz Milbrooka, Konektikat.
{83186}{83250}Mama, pridobila je publiku.
{83527}{83642}Jesi li primijetila da je napravila trostruki?|-Doöla je pobijediti.
{83646}{83732}To je shvatila na kompjuteru.
{83737}{83818}Mama, kompjuter ne skaËe umjesto tebe.
{84416}{84465}Prva! Da!
{84469}{84510}- Da!|- Razbijaö, duöo!
{84514}{84566}To je samo za kratko, kratka.
{84658}{84726}- »etvrta.|- Uzimamo.
{84730}{84774}Peta, to je sjajno!
{84779}{84831}Da, ali peta ne ide po odjeljcima.
{84834}{84901}Odkliûi veËeras Ëisti program,|i napredovat Êeö.
{84904}{84952}Izbacit Êeö me sa Ëetvrtog.
{85071}{85157}Casey,|zamalo si izgubila Ëizmu tamo.
{85162}{85271}- Znam, izdaje me.|- Bolje poi sa mnom.
{85344}{85407}- Jesu li taman?|- Stvarno ne mogu prihvatiti.
{85411}{85466}Samo mi dokaûi da ih zasluûujeö.
{85470}{85529}I trebat Êe nam par sjeËiva.
{85534}{85593}Odmah Êu ih naoötriti za vas.
{85596}{85657}Tina, ne mogu vjerovati|da bi pomogla...
{85661}{85698}Bez ulagivanja.
{85703}{85731}Ne.
{85735}{85773}Samo...
{85779}{85818}Hvala.
{85896}{85974}''A sljedeÊi izvoaË''|u slobodnom klizanju za juniore
{85978}{86054}Casey Carlyle|iz Milbrooka, Konektikat.
{88073}{88119}Tko je?
{88123}{88170}A tako se to radi, patuljku.
{88174}{88229}Umukni, jastuËiÊu za igle.
{88234}{88274}Idemo, duöo.
{88279}{88325}Oprostite.
{88411}{88478}Idem po odjeljcima!
{88481}{88510}Dobra djevojka!
{88513}{88570}»estitam!
{88910}{88957}Jesu li to nove?
{88985}{89020}- Da.|- Jesi li luda?
{89025}{89073}Ne moûeö se takmiËiti|sa novim klizaljkama.
{89079}{89149}Treba im, minimum deset|dana da se otkoËe.
{89154}{89219}- Svi to znaju.|- Ali Tina mi nije rekla.
{89223}{89274}Misliö na Tinu,|Ëija robot kÊerka...
{89278}{89342}zamalo nije proöla zbog tebe?
{89346}{89389}TipiËna Tina Harwood.
{89392}{89441}Kao u Sarajevu.
{89470}{89542}Ti baö ne znaö niöta, zar ne?
{89546}{89595}Izbacili su te.
{89625}{89718}Moûda bi trebala ponovno|poËeti bez trenera.
{89774}{89826}Bok, nova djevojko.
{89831}{89922}- Vidimo se u kombiju za 40 minuta.|- Ok.
{90005}{90039}Evo je.
{90042}{90086}- »estitam.|- Hvala.
{90090}{90173}- Bila si sjajna.|- Sretna sam da je to gotovo.
{90211}{90292}- Jesi li sretna zbog mojih nogu?|- äto?
{90296}{90390}éao mi je, Casey, ali tvoje stare|klizaljke su bile u raspadu.
{90393}{90450}Kupila si joj nove klizaljke?
{90453}{90523}Molim te, kao da nisi znala.
{90527}{90612}- Casey, nisam!|- Kako me moûeö lagati u lice?
{90618}{90671}Ista si kao i ona.
{90675}{90759}- Hej, smiri se, Casey.|- Oh, samo je brani!
{90764}{90804}Kao da nisi bio dio toga.
{90809}{90903}- Kako moûeö to misliti?|- Zato öto je istina.
{90907}{91022}Smjestio si mi. Svi vi.
{91026}{91080}Kakvi ste vi to ljudi?
{91294}{91346}Hajde, idemo.
{91350}{91394}Mama?
{91434}{91486}Jel' moûeö doÊi po mene?
{91579}{91648}Ja sam na klizaliötu u Vesterliju.
{91697}{91746}HoÊu kuÊi.
{92044}{92129}Duöo, ui u auto.|Samo ui u auto.
{92134}{92219}- Kako se usuujeö?|- SaËekajte malo, djeco.
{92224}{92310}Misliö da moûeö samo otplesati|nakon öto si povrijedila moju kÊerku?
{92315}{92337}Joan, jel' tako?
{92341}{92432}IzvlaËiö je od uËenja iza mojih lea?
{92435}{92569}Puniö joj glavu snovima o klizanju, a|onda joj uniötiö öanse?
{92573}{92666}UËinila sam vam uslugu. Niste|ûeljeli ovo za Casey i u pravu ste.
{92670}{92715}Ona nije za ovo.
{92718}{92786}Je li nadarena? To joj priznajem.
{92789}{92873}Ali Casey se neÊe boriti za to. Ona je|previöe ljubazna da bi napravila öto treba.
{92877}{92970}Da se progura kroz sve i svakog i|da jednostavno uzme.
{92974}{93098}ZnaËi to je primjer koji si postavila|svojoj kÊerki.
{93103}{93194}Da laûe da se öulja i da vara.
{93288}{93419}Ja sam napravila moju kÊerku snaûnom,|a ti si zabarikadirala Casey u kuÊi.
{93423}{93516}I tamo joj je odliËno.|Pa se, kao öto vidite, slaûemo.
{93520}{93638}Moja kÊerka je briljantna|i uspijet Êe u svemu öto naumi.
{93642}{93695}Ali Êe to napraviti na pravi naËin...
{93698}{93800}usprkos ljudima koji je|uvjeravaju u drugaËije.
{94834}{94881}Casey!
{94903}{94975}- U formi sam. Mogu te stiÊi.|- Odlazi.
{94979}{95050}- Casey, nisam znala!|- Kako da ne!
{95134}{95271}Gdje si bila? Ti si svjesna da si imala|trening prije pola sata?
{95275}{95349}- Da, svjesna sam.|- I?
{95354}{95405}Zavröila sam.
{95487}{95541}Zavröila?
{95716}{95762}Prestajem.
{95766}{95842}Mora sa se öaliö.|To je smijeöno.
{95846}{95950}Ne, ja sam smijeöna öto sam|ovo trpjela ovoliko dugo.
{95954}{96001}Oboje znamo da nemam talenta.
{96004}{96096}Upornost je devet desetina|savladavanja nekog sporta.
{96101}{96209}Jel' znaö öto ja ûelim?|Ne, ne znaö öto ûelim.
{96214}{96262}Zato öto te nije briga.
{96358}{96451}Ako imate osjeÊaj samooËuvanja,|raziÊi Êete se.
{96660}{96751}Sluöam. -HoÊu prekinuti to|öto propuötam ökolu.
{96754}{96792}Ja volim ökolu.
{96796}{96886}Znaö, glupo je i bend Êe|vjerojatno biti uûasan,
{96889}{96986}ali hoÊu iÊi na proljetni ples.
{96991}{97054}I hoÊu iÊi sa Brianom.
{97059}{97164}HoÊu se prestati osjeÊati kao idiot|zato öto izbjegavam matematiku...
{97169}{97219}jer je nemam vremena nauËiti.
{97259}{97341}- I hoÊu...|- U redu. U redu.
{97345}{97445}- Vidim da smo moûda pretjerali.|- Pretjerali?
{97483}{97544}Samo malo.
{97547}{97600}Casey kliûe, mama.
{97774}{97831}Nastavit Êemo ovu raspravu kod kuÊe.
{98356}{98450}- »ula si sve?|- Da.
{98553}{98591}Jesi li dobro?
{98654}{98771}To je tvoje mjesto, Casey.|Ako ja ispadnem, ti si sljedeÊa.
{98798}{98848}Ideö po odjeljcima.
{98874}{98913}Ne.
{98946}{99044}Hvala.|Sutra je moj intervju za Harward.
{99049}{99137}To je moje mjesto.|To bih trebala raditi.
{99141}{99192}Jesi li sigurna?
{99420}{99479}To je lijep eksperiment.
{99512}{99631}Kako vam trostruki skok daje|pravo na ökolarinu iz fizike?
{99635}{99803}Dokaz eksperimenta nije|u silnim kalkulacijama.
{99806}{99925}On je u poboljöanju klizanja|tri juniorska öampiona.
{99951}{100060}Takoer sam primijenila|nalaze na moje klizanje...
{100137}{100243}i, ustvari, uspjela izvesti eksperiment
{100249}{100378}na vrlo lijep i potpuno osoban naËin.
{100381}{100412}Dobro,
{100415}{100500}jer strast je glavna komponenta|koju traûimo kod studenata.
{100504}{100586}Strast tjera ljude da rade izuzetne stvari.
{100590}{100730}Pa, Casey, zbog Ëega osjeÊaö|strast prema Harwardu?
{101070}{101106}Dr. Hili,
{101110}{101231}moja mama i ja smo zamiöljale|Harward praktiËno cijelog mog ûivota.
{101293}{101423}Ne mogu vjerovati da ovo priËam,|ali ono öto bih trebala sad raditi,...
{101489}{101529}...ne mogu to ovdje.
{101550}{101603}éao mi je öto sam vam|troöila vrijeme.
{101662}{101709}Veoma mi je ûao.
{101826}{101940}Gice Carlyle,|neÊemo pomicati sastanak.
{101973}{102020}Znam.
{102317}{102448}Ne moûeö napraviti ovo, Cas.|OdriËeö se svog sna.
{102451}{102546}Ne, mama,|odriËem se tvog sna.
{102613}{102660}Ja idem za mojim.
{104478}{104568}- Kako si znao?|- Mislio sam da neÊeö odustati.
{104571}{104646}äto je znaËilo da Êeö biti|ovdje i padati.
{104650}{104765}Teddy, traûila sam naËin|kako se ispriËati.
{104769}{104838}Pa imam neke ideje za to.
{104842}{104900}Srednje glatko ili kao staklo?
{105961}{106130}Ne mogu priËati ni sa kim koga|ne znam od vrtiÊa,
{106134}{106204}pa kako to da mogu pred tobom?
{106245}{106310}Zato öto puötaö ljudima|da te vide...dok kliûeö.
{106382}{106481}Ali, Casey,|ne moûeö pobijediti sama.
{106484}{106533}Trebat Êe ti neka pomoÊ.
{107178}{107268}- äto hoÊeö?|- 5 minuta.
{107293}{107352}Dugujeö mi toliko.
{107502}{107581}Ako si ovdje zbog isprike,|neÊeö je dobiti.
{107584}{107641}Nisam ovdje zbog isprike.
{107644}{107703}Reci mi öto se dogodilo u Sarajevu.
{107734}{107781}Zaöto nisi pobijedila?
{107865}{107937}Imala sam nesretno zagrijavanje|prije mog kratkog programa.
{107940}{108021}Sudarila sam se sa drugom|klizaËicom i ona se povrijedila.
{108025}{108085}Jel' ti ûao?
{108131}{108261}Gledaj, platila sam moje greöke.|Suspendirana sam.
{108265}{108382}Do vremena kad su me ponovno ubacili,|imala sam 26, i bilo je kasno.
{108386}{108529}Ali ne proe dan da ne poûelim|vratiti taj trenutak
{108569}{108614}i drugaËije ga proûivjeti.
{108748}{108798}HoÊu da me treniraö za Odjeljke.
{108884}{108947}Zaöto bi, za ime svijeta, htjela to?
{108951}{109042}Zato öto nemaö klizaËicu, a ja|nemam trenera.
{109046}{109128}- Uklapamo se savröeno.|- Mislim da nemaö ono öto treba.
{109187}{109266}Tina, moram napraviti ovo.
{109270}{109330}éelim ovo viöe od iËega na svijetu.
{109380}{109428}Rekla sam ne Harwardu.
{109474}{109544}Radit Êu viöe od bilo koje klizaËice|koju si ikad trenirala.
{109549}{109612}A ako propadnem, propast Êu,
{109615}{109706}zbog toga öto nisam dovoljno dobra,|a ne zato öto nemam hrabrosti.
{109710}{109846}HoÊu znati öto mogu u ovom|sportu, i saznat Êu to.
{110159}{110285}Klizaliöte. Sutra u 5:30,|i dobro se naspavaj.
{110315}{110363}Trebat Êe ti.
{110499}{110626}Da uopÊe razmiöljaö o puötanju te|ûene ponovo u tvoju glavu!
{110630}{110682}Ne moram je voljeti ili joj vjerovati.
{110686}{110754}Ne, samo hoÊeö biti|svo vrijeme sa njom.
{110757}{110841}- NeÊu se pretvoriti u nju.|- VeÊ se nazire na tebi.
{110845}{110877}To nije toËno.
{110881}{110954}Odakle ti ta frizura?|I öminka i koöulja?
{110958}{111013}Nisam ti kupila tu koöulju.
{111017}{111060}To nema nikakve veze sa ovim.
{111063}{111167}Mislim da hoÊeö biti ista ona,|i ako se desi da poËneö lagati,
{111172}{111237}hej, nema veze,|barem Êeö biti glamurozna.
{111240}{111305}Misliö da je ovo zbog glamura?
{111308}{111411}To je sport, mama.|Uzbudljiv i prelijep sport.
{111415}{111497}Zar to nije samo da bi se|osjeÊala lijepom?
{111502}{111544}Pa öto ako jest?
{111547}{111594}äto je tu toliko straöno?
{111599}{111721}Biti jak i graciozan i lijep|jednom u ûivotu?
{111849}{111906}Zaöto si ljubomorna na nju?
{111958}{112023}Pa, nema veze koliko ostarimo,
{112027}{112093}svi ostali Êemo mrziti|matursku kraljicu.
{112267}{112370}Znaö da je uvijek bio|Caseyn i mamin show.
{112426}{112470}Jel' znam?
{112491}{112577}Ali kad bi mogla doÊi na|klizaliöte i gledati me.
{112581}{112645}Ne pitaj me! Ne mogu!
{112648}{112716}Poi sad sa mnom odmah, mama.
{112719}{112841}Samo me doi gledati kako kliûem,|pa mi onda reci da prekinem.
{112845}{112910}Znaö öto, imam sat, u redu?
{113218}{113268}''Dobrodoöli na ESPN''
{113271}{113344}istoËni odjeljak|juniorki u kratkom programu.
{113347}{113421}Moram reÊi,|po treningu koji sam gledao,
{113424}{113480}ove djevojke su zapaljive.
{113483}{113575}Tako je. Svaka klizaËica je radila|nevjerojatno naporno da bi doöla ovdje.
{113578}{113657}I svaka je spremna za natjecanje.
{114022}{114093}ZnaËi, i ti si ötreber iz fizike?
{114097}{114144}Iz matematike.
{114147}{114287}Stvarno? Kad bih poloûila matematiku|mogla bih se upisati na faks.
{114338}{114382}Dajeö li instrukcije?
{114413}{114465}Jel' znaö neke slatke momke?
{115171}{115255}Prva u ûenskom kratkom|programu je Zoi Bloh.
{115258}{115381}Ona kliûe svo vrijeme i|publika jednostavno uûiva uz nju.
{115420}{115541}Tiffany je vjerojatno najgracioznija|takmiËarka u ovoj konkurenciji,
{115546}{115612}i definitivno je na vrhuncu danas.
{115615}{115715}Mislio sam da Shantal pokazuje|znake nervoze ranije.
{115719}{115786}Ne viöe.|Totalno upravlja situacijom.
{115861}{115941}Fanovi je zovu SkaËuÊi äkamp, ali|zapamtite to ime...
{115946}{116036}jer ovaj mali zvrk izvodi|nevjerojatne skokove.
{116127}{116224}RijeË poËetnik nije ni blizu|Casey Carlyle.
{116229}{116328}Nikad se nije takmiËila|do ove sezone.
{116407}{116457}Definitivno Êemo je pratiti.
{116461}{116509}''Plasman je sljedeÊi''
{116512}{116589}Zoi Bloh na prvom mjestu,|Nikki Flecher na drugom,
{116592}{116663}prati je Shantal de Groat|i Casey Carlyle.
{116666}{116734}4.8 i 4.9! Jedna 5.0!
{116737}{116782}I jedna 4.6.
{116786}{116859}Oh, hajde!|Nema ''dobar posao'' ili ''bravo''?
{116862}{116933}- Barem sam izvela skokove.|- U igri si, niöta viöe.
{116938}{117008}Nisam vidjela da su ti skokovi teËni...
{117014}{117065}i to utjeËe na tvoje bodove.
{117070}{117092}Zapamti...
{117098}{117173}Tvoj sljedeÊi pokret je uvijek|nastavak tvog prethodnog.
{117176}{117279}Trljaj stopala barem 5 minuta i|popij dosta vode.
{117380}{117422}Uspjela si, djevojko!
{117426}{117491}''Samo kratki. To je samo kratki.''
{117495}{117589}Lagala sam. Ako zabrljaö kratki|ne moûeö nikad pobijediti.
{117666}{117730}Hej, jesi li sredila|stvari sa svojom mamom?
{117736}{117825}Um, jedva smo progovorili|u dva mjeseca.
{117962}{118010}Mislim da sam joj slomila srce.
{118014}{118078}Moûemo pratiti tu liniju zavjere...
{118082}{118230}od Euripida do Shakespira, pa preko|Marka Twaina,
{118233}{118353}nalazeÊi privremeni odjek|u Johnu Shiveru...
{118410}{118461}...Janet Jackson.
{118464}{118505}Zar ne mislite na Shirli Jackson?
{118510}{118604}- ZnaËi da ste proËitali.
{118609}{118698}U redu. SljedeÊi tjedan hoÊu esej|o vaöem kandidatu...
{118702}{118808}o ''naj-nefeministiËkijem piscu 20. vijeka.''
{118954}{119058}''Iz New Yorka''|New York, Ema Flanders.
{119181}{119261}Ovo je to.|Moûeö izgubiti dugi program
{119265}{119349}samo sjedeÊi ovdje ako|se ne pripremiö kako treba.
{119353}{119404}- Stavi ovo.|- Zaöto?
{119409}{119461}Vjeruj mi, ne ûeliö znati.
{119466}{119512}Ako padnu, ti Êeö se osiliti,
{119517}{119596}ako dovedu publiku pred tvoje noge,|osjetit Êeö zadovoljstvo.
{119599}{119663}Nitko drugi ne postoji.
{119712}{119767}Ui u mjehur.
{121773}{121824}Zaboravi.
{121829}{121888}Moram samo Ëuti njen glas.
{122046}{122121}Dobili ste Carlyleove.|Trenutno nismo tu...
{122225}{122312}Ovo nije u vezi nje.|Ovo je zbog tebe.
{122524}{122640}''Naöa finalna klizaËica'' je Casey|Carlyle, iz Milbrooka, Konektikat.
{122754}{122780}Joö jedna stvar.
{122784}{122826}äto?
{122829}{122886}Kliûi iz srca.
{124679}{124780}I evo njenog poËetnog skoka,|trostruki Salkau.
{125162}{125215}Dobro je za ûivce.
{125297}{125335}- Hvala.
{126545}{126591}Trostruki okret.
{126596}{126650}Savröeni doskok.
{126751}{126810}äto? Upravo je izvela trostruki Luc!
{126814}{126877}Sve je kako treba,|ali kompletna improvizacija.
{126882}{126933}- Ona je odstupila od plana.|- I izgrdit Êu je zbog toga.
{126937}{126983}Sutra.
{127115}{127162}Tko je rekao da moûeö pustiti?
{127370}{127462}Nisam vidio ovakav povratak poslije|pada joö od Midori Ito
{127466}{127513}na Olimpijadi '92.
{127518}{127591}To je oporavak godine.
{128598}{128648}Casey Carlyle Ëeka ocjene.
{128652}{128730}Zasad su Nikki i Zoi, prva i druga,|a De Groat treÊa.
{128734}{128806}Da li Êe je taj pad koötati, ili Êe|je onaj oporavak,...
{128810}{128913}da ne spominjemo dodane umjetniËke|teökoÊe, izbaciti ispred ostalih?
{128958}{129002}Visoko! 5.1 i 5.2.
{129006}{129082}Skoro se izjednaËila sa Nikki Flecher.
{129086}{129147}To je moja kÊerka.|To je moja kÊerka.
{129151}{129205}Evo umjetniËkih ocjena.
{129208}{129257}SaËekajte. SaËekajte.
{129318}{129376}Skoro je jednaka sa Nikki.
{129472}{129521}Je li uspjela?
{129524}{129590}Ne, nije dovoljno.|Morat Êe se zadovoljiti sa srebrom.
{129594}{129704}Ovo je vodi na Nacionalno prvenstvo,|i tko zna, moûda i na Olimpijadu 2006.
{129707}{129766}Sa ovom klizaËicom, sve je moguÊe.
{129824}{129858}Hvala ti.
{129966}{130013}Cas?
{130100}{130142}Mama?
{130234}{130308}Da sam samo znala.|Da sam samo na 10 minuta...
{130312}{130364}otiöla na klizaliöte sa tobom,
{130368}{130442}Nikad ne bih...
{130446}{130486}Mama.
{130512}{130553}éao mi je.
{130587}{130625}Tako mi je ûao.
{130670}{130715}Kako to nisam vidjela?
{130771}{130830}Ti me vidiö bolje nego itko drugi.
{131074}{131122}Hajdemo.
{131651}{131696}Casey.
{131775}{131820}»estitam.
{131824}{131914}I moûeö voziö Zamboni|kad god hoÊeö.
{132285}{132367}Bila sam blizu,|ovoliko blizu da izgubim!
{132372}{132448}Odakle su doöli oni trostruki skokovi?!|-Duöo, ti...
{132451}{132530}Zar ne znaö öto Êe se desiti|poslije öest mjeseci sa Tinom?
{132533}{132601}- äto?|- Odrat Êe mi guzicu!
{132606}{132734}- Netko Êe platiti zbog ovoga.|- Nikki. Jel' moûemo popriËati?
{132738}{132810}- Zdravo, Piter.|- Samo sam htio Ëestitati.
{132814}{132904}Radujemo se öto Êemo vidjeti SkaËuÊu|äkampu na Nacionalnom prvenstvu.
{132907}{133015}To je tako slatko. Samo sam izaöla tamo|i klizala najbolje öto znam.
{133020}{133114}A danas,|moje najbolje je bilo dovoljno.
{133156}{133199}- Volim vas.
{133292}{133370}Znate da ovo ne mogu priuötiti.|Moramo joj naÊi sponzora.
{133374}{133425}Radim na tome.|Burger Blast je zainteresiran.
{133429}{133540}Burger Blast?|Oh ne, oprostite, oprostite, ne.
{133544}{133567}Zaöto ne?
{133571}{133632}Ako ih ne moûemo jesti,|ne moûemo ih ni oblaËiti.
{133636}{133724}Moûe neöto zdravije|Naprimjer Grape-nuts?
{133728}{133796}Grape-nuts?|Moûe ulje od bakalara?
{133799}{133858}- Ljudi.|- Znate, ja sam joj majka.
{133862}{133907}äto ja kaûem to ide.|Ona je moja kÊerka.
{133910}{133982}- Ona je moja klizaËica.|- Pa, kÊerka je jaËa od klizaËice.
{133986}{134100}Pa, pitaj svakog profesionalnog|sportaöa trener je jaËi od majke, uvijek.
{134104}{134153}Ljudi!
{134248}{134310}I taj deËko,|moramo to sasjeÊi u korijenu.
{134314}{134365}Ne mogu prolaziti kroz sve ovo,|i joö i deËko.
{134369}{134433}On je velika smetnja.|To je neprihvatljivo.
{134437}{134518}- Ne mogu vjerovati!|- Bit Êeö zauzeta treningom.
{134522}{134565}I Ëetiri kursa za faks.
{134572}{134666}»etiri? Jesi li poludjela, sa svim ovim|öto radi?
{134670}{134715}U redu, dva.
{134719}{134799}- Ali onda Ëetiri najesen.|- Jedino ako proe na odjeljke.
{134803}{134853}Oh, proÊi Êe.
{134860}{134960}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d 
{134985}{136485}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/wgeu|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
