{1}{1}25.000
{42}{128}Paradise; imenica, raj.
{131}{198}1. Mjesto idealne ljepote i ljupkosti.
{201}{271}2. Stanje ushita.
{274}{331}3. Paradise, grad u Massachusettsu
{334}{418}Populacija: 25.408 (7.633 domaÊinstva)
{421}{486}Povröina: 44 km2 (zemlja), 107 km2 (voda) 
{511}{661}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{5247}{5328}POLICIJA
{5601}{5644}Tip je ubijen, Jesse.
{5647}{5685}Ti si ga naöao?|- Da.
{5688}{5746}Radim od 11 do 19.
{5751}{5826}Stao sam se olaköati i ugledao sam psa.
{5930}{5962}Ne poznajem ga.
{5965}{6030}Lisnica i dozvola joö su mu u dûepu.
{6033}{6063}Kenneth Eisley.
{6082}{6138}Velika kuÊa s druge strane vode.
{6141}{6200}Joö jedan putnik u potrazi za rajem.
{6203}{6241}I pronaöao ga je.
{6295}{6329}Izgleda poput kalibra 0.22.
{6352}{6408}To je ubojstvo, zar ne, Jesse?
{6436}{6464}Vjerojatno.
{6506}{6567}Misliö li da ga je plima nasukala ovamo?
{6604}{6697}Nasukano tijelo ne izgleda ovako.
{6700}{6741}Viöe natuËeno.|- Da.
{6758}{6838}Ima oûiljke na licu.|- To su galebovi.
{6857}{6916}Mogao sam ûivjeti i bez ovoga saznanja.
{6923}{6981}äto je sa Ëahurama?
{6995}{7069}Moûda ih je ubojica podigao.|- Ili je upotrijebio revolver.
{7125}{7187}Anthony je rekao preko|telefona da imamo ubojstvo?
{7190}{7288}Pobrini se za mjesto zloËina.|Dvije rane od metka na prsima.
{7291}{7331}To bi bio trag.
{7372}{7448}Joö nema ukoËenosti.|- äto to znaËi?
{7451}{7509}Susreo se s ubojicom prije manje od 2 h.
{7512}{7543}Ili ubojicama.
{7565}{7607}D'Angelo, zatvori podruËje.
{7615}{7682}Studeni je, kapetane. Nitko ga ne koristi.
{7706}{7734}Ovaj tip jest.
{7794}{7865}äto je sa psom? Samo sjedi ondje.
{9067}{9106}Jesse, Jenn je.
{9133}{9169}Jesi tamo?
{9195}{9289}Kasno je. Vjerojatno spavaö ili si na spoju.
{9345}{9427}Oprosti, nisam htjela da|tako zvuËi. Naporan dan.
{9430}{9484}Pokazivala sam na Teaneck u New Jerseyju
{9487}{9552}dok sam davala prognozu za Long Island.
{9574}{9671}No, nije vaûno. Prognozerke|nitko ne shvaÊa ozbiljno.
{9684}{9733}Bila sam vani cijelu noÊ, sve do sada.
{9736}{9817}Postaja je imala dobrotvornu veËeru u Metu,
{9820}{9885}i iöla sam s Craigom, mojim producentom.
{9892}{9946}Mrtva sam umorna. Idem u krpe.
{9953}{10001}Razgovarat Êemo.
{10026}{10068}Ozbiljno.
{10078}{10126}Bila sam vani cijelu noÊ, sve do sada.
{10129}{10211}Postaja je imala dobrotvornu veËeru u Metu.
{10214}{10281}Iöla sam s Craigom, mojim producentom.
{10284}{10341}Mrtva sam umorna. Idem u krpe.
{10344}{10395}Razgovarat Êemo sutra.
{10702}{10729}Hej.
{10768}{10837}7 h je. äto radiö ovdje?
{10840}{10891}Rano ustajem boriti se protiv kriminala.
{10910}{10983}Moûeö li doÊi veËeras?|- Bila bih blesava da odbijem.
{10986}{11037}Moûemo naruËiti veËeru.|- Kinesku?
{11040}{11101}Znaö kako postanem seksi|kada jedem kinesku hranu.
{11104}{11144}Ili kada ne jedeö.
{11213}{11311}POLICIJA, PARADISE MASSACHUSETTS
{11314}{11382}Dob: 37. Rastavljen, bez djece.
{11385}{11461}Roditelji mu ûive u Amherstu.|Obavijestili su ih.
{11482}{11545}Netko ga je ubio i morao je imati razloga.
{11548}{11584}Razgovaraj s njegovim kolegama.
{11587}{11657}Perkins kaûe da Êe se|oko ruËka posvetiti Eisleyju.
{11660}{11707}D'Angelo, tijekom svih godina kao policajac
{11710}{11786}nisam Ëuo da se öefa policije zove kapetane.
{11789}{11863}Doöao je par s kÊerkom. Penningtoni.
{11866}{11922}äto ûele?|- Nisu htjeli reÊi,
{11925}{11981}no mislim da trebate razgovarati s njima.
{11995}{12086}Javi Healeyju da öaljemo|metke na balistiËku obradu.
{12089}{12117}Dobro.
{12145}{12202}Dobro jutro, druötvo.|Ja sam nadstojnik Stone.
{12224}{12261}Molim vas, sjednite.
{12403}{12459}KÊi mi je silovana.|- Mama!
{12462}{12522}Molly, moûda ûeliö ostati.
{12546}{12607}Nisam silovana.|- Molim te, duöo.
{12635}{12718}SinoÊ se vratila kasno.|Pokuöala se uvuÊi u kuÊu.
{12721}{12813}Poderanih traperica, raöËupane|kose i krvave usnice.
{12816}{12877}Traûila sam da je sama pregledam.
{12893}{12970}Nije imala gaÊice i bedro|joj je bilo u modricama.
{13000}{13051}Jeste li je odveli k lijeËniku?
{13054}{13100}Da se proËuje po gradu? Zaboga, ne.
{13103}{13158}OËistila sam je i dovela ravno k vama.
{13161}{13210}OËistili? Kako?
{13250}{13341}U kadi sam je ostrugala, kao da su joj 2 g.
{13344}{13393}Tko ti je to uËinio, Candace?
{13396}{13473}Ne ûelim govoriti o tomu.|- Reci im, mlada damo.
{13476}{13585}Candace, ako ne znamo tko je,|to se moûe opet dogoditi
{13604}{13657}nekomu drugom ili tebi.
{13700}{13778}Odmah reci öto se dogodilo.|- Bez udaranja.
{13839}{13887}Molly, izvedi Candace.
{13970}{14015}Poi sa mnom, Candace.
{14188}{14237}Ne postoji li nekakav test?
{14240}{14317}VruÊa kupka obiËno ukloni takve dokaze,
{14320}{14403}no moûda u bolnici...|- Ne ûelim je voditi onamo.
{14406}{14435}Margaret.
{14501}{14580}Ovo mora ostati u povjerenju.|Moûete mi to obeÊati?
{14583}{14612}Naravno da ne.
{14616}{14719}Ne mislimo brljati o tomu.|No na suenju bi se otkrilo.
{14731}{14772}Ne ûelim viöe razgovarati.
{14775}{14840}éelim svoju kÊer, i vodim je kuÊi.
{14993}{15032}Rekla sam öto sam imala.
{15035}{15130}Go Pennington, zaöto ne...|- Nemam vam öto reÊi.
{15201}{15251}éeliö li mi ti öto reÊi?
{15633}{15681}Jadno dijete. äto Êemo?
{15684}{15747}»ula si majku. Ne ûeli skandal.
{15750}{15796}Niöta neÊemo uËiniti?
{15799}{15878}Nisam to rekao. Idi u srednju ökolu.
{15881}{15935}äto Êu ondje?|- Drûi je na oku.
{15938}{15994}Otkrij tko je to bio.|- Kako?
{16021}{16061}Smislit Êeö neöto.
{16845}{16892}Kasnim?|- Ne.
{16900}{16952}Ne moûeö nekoga pozvati na veËeru
{16955}{17005}i samo baciti kartone s hranom na stol.
{17008}{17073}Naravno da ne. Zanimalo me znaö li ti to.
{17076}{17107}Da, naravno.
{17308}{17361}Ovdje je pas.|- Da.
{18505}{18540}Kamo ideö?
{18613}{18652}éeliö li vodu?
{18703}{18729}Vino.
{19388}{19434}Pod postaje hladan.
{19453}{19496}Sezona je gotova.
{19699}{19733}Zabrinuta sam.
{19782}{19829}Netko Êe ga pronaÊi.
{19836}{19889}Nisam mogla ubiti psa.
{19938}{19985}Pusti to. Idemo, Reggie.
{20035}{20071}Hajde. Spreman?
{20121}{20164}Jesi ga ikada upoznao?|- Koga?
{20193}{20268}IgraËa bejzbola s postera.|- Ozzieja? Ne.
{20286}{20350}Bio je jedan od najboljih koje sam vidio.
{20353}{20414}Bi li bio tako dobar da se nisi ozlijedio?
{20417}{20499}Mogao sam napraviti show,|ali ne bih bio Ozzie.
{20538}{20572}Nedostaje ti?
{20618}{20649}Svaki dan.
{20752}{20806}Zaöto misliö da se slaûemo?
{20827}{20860}Ne znam.
{20877}{20946}NeobiËan smo par. Prestar sam za tebe.
{20969}{21026}A zaöto misliö da se slaûemo?
{21061}{21148}Jer smo prijatelji.|- Prijatelji koji se seksaju.
{21214}{21251}Poput mene si.
{21254}{21325}NeÊeö se predati vezi samo da bi je imao.
{21332}{21409}Nitko od nas ne zahtijeva|predanost onog drugog.
{21412}{21486}äto stvara jednu vrstu|predanosti izmeu nas.
{21534}{21597}Ne mislim to u loöem smislu,
{21600}{21671}ali ti si najjednostavnija osoba koju znam.
{21691}{21798}Znaö öto ûeliö, i ustrajno radiö to öto radiö.
{21817}{21888}Poput mazge.|- Ili poput magarca.
{22017}{22076}Jedan metak, ravno kroz srce.
{22079}{22124}Drugi je probuöio silazni krak aorte.
{22135}{22191}éeliö li pojedinosti|o svemu öto je probijeno?
{22194}{22231}ProËitat Êu izvjeöÊe.
{22459}{22558}Veliki kalibar, standardna|brzina, okvir s 10 metaka.
{22561}{22600}Gotovo kao profesionalni.
{22603}{22674}Meci su uöli u tijelo|udaljeni za 30 stupnjeva.
{22677}{22716}äto ti to govori?
{22719}{22783}Ne znam, Jess. Uglavnom sam pedijatar.
{22786}{22844}Ovo je prvo ubojstvo koje vidim.
{22848}{22916}Sigurno si vidio puno|ovakvih stvari u LA-ju.
{22921}{23006}Moûda se ûrtva pomakla|nakon pogotka prvog metka.
{23009}{23056}Ili jedan napadaË s dva piötolja.
{23059}{23135}Ili dva istovremena pogotka|od dva napadaËa.
{23145}{23211}Trebamo pregledati sve zapise|o vatrenom oruûju u drûavi.
{23214}{23269}Sretno. Svi u drûavi imaju bar jedan 0.22.
{23272}{23336}Treba usporediti podatke.|Tko od njih ûivi blizu...
{23339}{23418}Je li kupljen u Massachusettsu|i ima li potrebne papire,
{23421}{23512}nismo li ga zagubili i ûivi li u Paradiseu.
{23529}{23571}Stjerali smo ga u kut.
{23625}{23700}Ne trebamo za njim?|- Ne, samo daj. Moramo.
{23714}{23797}No pametni zloËinci ne ubijaju|registriranim piötoljima.
{23800}{23870}Misliö da je pametan?|- Ili pametna.
{24357}{24397}Hej, Penningtonice.
{24429}{24466}äto je? Bez pozdrava?
{24506}{24588}Vidiö ovo? Nemoj niöta reÊi.
{24635}{24687}Zapravo, to mi je omiljeno.
{24930}{24987}Reci neöto i mrtva si.
{25336}{25391}Sluöaj, morat Êu te nazvati.
{25394}{25468}ZnaËi li to, Pronaöla sam silovatelja?
{25477}{25554}Unutra je pas.|- Zaötita svjedoka.
{25624}{25664}Bo Marino.
{25683}{25769}Nogometaö.|- Nogometna zvijezda s dva suigraËa.
{25772}{25845}Bo je neöto pokazao Candace|öto ju je nasmrt preplaöilo.
{25848}{25952}Tko je bio s Marinom?|- Kevin Feeney i Troy Drake.
{25969}{26025}Imaö li joö öto?|- Ne joö.
{26028}{26064}Imaö li plan?
{26089}{26133}Progonit Êu ih.
{26136}{26207}Moraö ovdje malo raditi.|- Moje vrijeme.
{26221}{26311}Vrijeme tvrtke. Posao tvrtke.|- To je ûenski posao.
{26340}{26383}Muökarci moûda znaju öto ûene ne znaju.
{26386}{26455}Da, ali silovanje je neöto öto znamo.
{26473}{26523}Zato Êu ih progoniti.
{26813}{26853}Ne naslanjaj se tako blizu...
{26895}{26928}Viöe!
{27173}{27222}Gotova si s esejom?|- Da, moûeö ga uzeti.
{27233}{27292}Hvala lijepa.|- Zadrûi ga.
{27385}{27482}Neöto ti se svia?|- Da. Pogledaj ovo.
{27725}{27797}Nisam znala da snimaö ovo.|- Ja uvijek snimam.
{27800}{27862}Samo sam htjela proËitati.
{27865}{27903}Ona je ta.
{27920}{27956}Bila je draga.
{27984}{28036}Htjela je posuditi moj esej.
{28064}{28152}Misliö da je zgodna?|- Mislim da je super zgodna.
{28160}{28205}Vidimo se.|- Hvala.
{28266}{28320}Meni je pomalo nalik na konja.
{28437}{28474}Ona je ta.
{28501}{28585}Kako se osjeÊaö zbog toga|öto spava s drugim muökarcima?
{28588}{28676}Ima pravo na to.|- Ali, kako se osjeÊaö?
{28733}{28803}Poûelim ubiti svakoga s kim bude.
{28815}{28851}Ali ne uËiniö to.
{28854}{28897}Hvala.|- Nema na Ëemu.
{28959}{29026}Znaö da sam mudrija od tebe.
{29058}{29126}äto ti daje pravo da mi udijeliö savjet.
{29129}{29173}Da. Takvo je pravilo.
{29221}{29336}Jesse, razveden si veÊ 5 g.
{29351}{29436}I savjetujeö mi da zaboravim Jenn?|- Da.
{29472}{29532}Netko ti savjetuje drukËije?|- Ne.
{29565}{29627}Kada bi to uspio rijeöiti s Jenn,
{29630}{29708}moûda bi mogao rijeöiti i problem s piÊem
{29711}{29794}i biti jako dobar policijski nadstojnik.
{29836}{29883}Nikad nisam bio pijan na duûnosti.
{29886}{29947}Nisi bio pijan na duûnosti ovdje.
{30000}{30035}Imaö pravo.
{30068}{30107}Dakle?|- Dakle?
{30195}{30241}HoÊeö da uöutim?
{30244}{30316}Ne. Dobar ti je savjet.
{30356}{30403}Samo nije dobar za mene.
{30959}{31013}Nitko nije dirao tijelo.
{31138}{31175}Tko je ona bila?
{31185}{31247}Na vozaËkoj piöe Barbara Carey.
{31426}{31479}Upucana je jednako kao i onaj tip.
{31482}{31547}Primijetio sam.|- Htio sam biti siguran.
{31600}{31679}D'Angelo, ûelim fotografije|svih automobila na parkingu
{31682}{31730}s Ëitljivim registarskim tablicama.
{31733}{31763}Svih?|- Da.
{31766}{31815}Tko Êe platiti film?
{31852}{31880}Ja.
{31940}{32010}Misliö da je ubojica joö tu?|- Bi li ti bio?
{32116}{32151}Jesi dobro?
{32218}{32256}Zanimljiv je.
{32288}{32327}Nisam primijetio.
{32365}{32407}Skidaju registarske tablice.
{32410}{32458}NaÊi Êe naöa imena.|- I?
{32461}{32524}NaÊi Êe i puno drugih imena.
{32533}{32599}Misliö da Êe nas odvesti na ispitivanje?
{32605}{32648}Policijske snage malog grada.
{32660}{32717}Mislim da nemaju dovoljno ljudi.
{32729}{32801}Bilo bi uzbudljivo da imaju.
{33104}{33171}Trebaö prijevoz?|- äto hoÊete?
{33179}{33207}Razgovarati.
{33599}{33704}Ako ûeliö potonuti u tajnosti,|neÊu to shvatiti osobno.
{33808}{33843}Ovdje je pas.
{33886}{33922}Kako se zove?
{33943}{34032}äto ti misliö?|- Reggie?
{34070}{34127}Izgleda ti kao Reggie?
{34136}{34184}To mu piöe na ogrlici.
{35069}{35146}Bo Marino, Kevin Feeney i Troy Drake.
{35199}{35249}Oboje znamo da su te oni silovali.
{35272}{35343}I znamo da su ti prijetili da to ne kaûeö.
{35399}{35479}Kako znate?|- Nadstojnik sve zna.
{35581}{35613}Ako im to dopustiö,
{35616}{35720}zagorËat Êe ti ûivot dok|god ûiviö u ovom gradu.
{35738}{35820}Ako mi se povjeriö, vratit Êu ti tvoj ûivot.
{35880}{35958}Moja mama...|- Mogu ti pomoÊi s njom.
{36075}{36122}éelim da me nazoveö
{36135}{36211}bilo kada, zbog bilo Ëega.
{36279}{36328}Ovo Êe biti meu nama
{36331}{36392}dok tako ûeliö. To je naöa tajna.
{36466}{36501}äto Êete napraviti?
{36504}{36547}Progonit Êu ih.
{36611}{36668}NeÊete reÊi?|- Ne.
{36688}{36723}NeÊu.
{36766}{36840}Tako se bojim.|- Znam.
{36870}{36953}Zajedno smo u ovomu, dobro?
{37042}{37078}Dobro.
{37624}{37667}Vi ste nadstojnik?|- Da.
{37670}{37735}Zaöto niste u uniformi?|- Opuöteni utorak.
{37738}{37804}Skip Wilder, Boston Herald.|- Bez komentara.
{37940}{38012}Doöli ste Ëak iz Bostona|pokupiti dva metka?
{38015}{38066}Doöao sam vidjeti mogu li kako pomoÊi.
{38069}{38163}Moûete. Vani je novinar iz Boston Heralda.
{38166}{38196}Nisam ga ja doveo.
{38199}{38279}Doznaj vozi li crni BMW.|Jedan me prati uokolo.
{38306}{38353}Jesi li vidio broj tablice, kapetane?
{38356}{38415}Nitko ne gleda broj tablice.
{38560}{38627}»uli ste?|- »uo sam.
{38631}{38679}Na isti naËin?|- Na isti naËin.
{38692}{38726}Bez vidljiva motiva?
{38739}{38789}Mislim da je moûda nasumce.
{38819}{38926}Koliko brzo moûete usporediti|metke s onima iz prve ûrtve?
{38931}{38999}Ja sam öef Ubojstava. Nisam Bog.
{39002}{39092}Nije li to isto?|- Kako sam tek ja razoËaran.
{39111}{39151}Ovo se moûe oduûiti.
{39154}{39251}Kada to potvrdimo, imat Êemo|sve drûavne medije za vratom.
{39292}{39345}Postupak se jednostavno oduûio.
{39359}{39387}Hvala.
{39418}{39446}Kofi?
{39484}{39587}Napiöi izjavu za novine|da imamo sve pod kontrolom.
{39590}{39644}Ja?|- Da, dobar si u tomu.
{39656}{39692}Jesam?|- Da.
{39698}{39736}Imamo li?|- äto?
{39739}{39784}Sve pod kontrolom.
{39816}{39893}éena ti je na liniji 3.|- Bivöa ûena.
{39954}{39983}Nazovite me.
{40149}{40178}Zdravo.
{40184}{40257}Kako si tamo gore?|- »ula si?
{40266}{40302}Jesam.
{40314}{40368}äto misliö da doem sutra?
{40398}{40455}Nije dobar trenutak, Jenn.
{40458}{40522}éelim te vidjeti.|- I ja tebe.
{40531}{40619}Jako sam razoËarana.|- Znam.
{40650}{40747}Mrzim samo priËati telefonom.|- Znam.
{40789}{40885}Previöe radiö, Jesse.|- Znam.
{40938}{41006}Da, razumijem to. A drûavna policija?
{41009}{41035}äto s njima?
{41038}{41103}Ima li razloga misliti|da su ubojstva povezana?
{41106}{41136}Imamo dva ubojstva.
{41139}{41231}Ne znamo je li oruûje isto. Hvala.
{41495}{41565}Larry, Curly, i Moe ûele razgovarati s tobom.
{41622}{41663}U ime gradskog vijeÊa
{41666}{41763}Jim, Carter i ja smatramo|da nas treba uputiti u sve.
{41860}{41902}I, öto se zbilja dogaa?
{41908}{42019}Imamo dva ubojstva.|Ne znamo je li oruûje isto.
{42092}{42155}To je sve öto znate?|- ToËno.
{42160}{42218}Nemate nikakve tragove, niöta?
{42232}{42263}ToËno.
{42268}{42338}Dovraga.|- Rekao sam ti da nije priËalica.
{42348}{42424}äto Êemo s novinarima?|- Svia mi se bez komentara.
{42439}{42540}A öto tvoj ured radi u srednjoj ökoli?
{42574}{42658}Moûda bi mogao malo bolje|rasporediti svoje ljude.
{42710}{42750}Dovraga, ne govoriö li?
{42759}{42812}Samo kad imam öto reÊi.
{42815}{42911}Iölo bi nam brûe uz FBI ili drûavnu pomoÊ.
{42923}{43003}FBI i drûavna policija vuku za sobom medije.
{43008}{43081}NeÊe vam se sviati ovaj grad|kada ga oni dokrajËe.
{43084}{43195}Treba iskoristiti sva sredstva|i usredotoËiti se na ubojstva.
{43205}{43297}Policajac sam veÊ jako dugo.|I dobar sam u tomu.
{43312}{43402}Znam kako ovo raditi. Vi ne.|- Moûemo ti dati otkaz.
{43436}{43502}Da. Ali mi ne moûete govoriti öto da radim.
{43935}{43983}Znaö da sam mudrija od tebe.
{43986}{44063}To je savjet prijatelja ili gradske odvjetnice?
{44066}{44107}Govorim ti kao prijateljica.
{44158}{44207}éeliö svratiti veËeras i pripremiti veËeru?
{44210}{44271}Ne mijenjaj temu, i nemoj ih naljutiti.
{44274}{44335}Kupio sam bijelu ribu.|- Bez kosti?
{44338}{44392}Bez kosti.|- ZvuËi dobro.
{44465}{44518}Znaö öto zvuËi joö bolje?|- äto?
{44521}{44580}Nemoj naljutiti gradsko vijeÊe, Jesse.
{44602}{44647}Onda, moûe u 7 h?
{44650}{44726}Da ne pijeö toliko, ËvröÊe bi to drûao.
{44729}{44756}Znam.
{44796}{44865}äto misliö?|- Premlada je za njega.
{44927}{44970}Tvojih je godina.
{44985}{45035}Ja sam viöe svjetovna.
{45617}{45658}Plaöi li te ubojica?
{45679}{45745}Ne slijeûi ramenima. éelim odgovor.
{45774}{45839}Bio bih budala da me ne plaöi.
{45874}{45934}Bi li pucao na njega?|- Ako bih morao.
{45973}{46039}Jesi li ikada pucao na koga?|- Da.
{46093}{46133}Jesi ga ubio?
{46167}{46193}Da.
{46245}{46307}éeliö mi priËati o tomu?|- Ne.
{46359}{46401}ZnaËi ubio si ga?
{46538}{46583}Jesi li to namjeravao?|- Da.
{46616}{46689}Nisi ga ûelio raniti, moûda upucati u nogu?
{46692}{46726}Imao je maËetu.
{46851}{46933}Ne moûeö dobro disati, imaö tipa s maËetom,
{46936}{47021}naciljaö u sredinu i pokuöaö|ne pomaknuti okidaË.
{47031}{47118}Uvijek pucaö kako bi ubio.|To nije kao u filmovima.
{47121}{47221}Imaö pola sekunde kako|bi smislio öto uËiniti.
{47329}{47408}Moraö tako razmiöljati ako si policajac.
{47411}{47481}Moûda sam ja policajac jer tako razmiöljam.
{47774}{47839}Misliö li da su ubojstva povezana?
{47878}{47962}Ne slijeûi ramenima. Misliö li to?|- Ne znam.
{48008}{48073}No nisi samo policajac.
{48076}{48127}Ti si ipak i osoba.
{48130}{48213}Bolji sam kao policajac|i bolje je da se oni ne nadaju.
{48216}{48284}Nisam sigurna da si bolji|kao policajac nego kao osoba.
{48287}{48383}Loö policajac, ha? - Ne. Znaö öto mislim.
{48412}{48458}Znam. Hvala.
{49032}{49097}Pogoen je ovdje. Sigurno je pao.
{49174}{49253}Obitelj?|- éena, tri kÊeri.
{49264}{49303}Razgovarat Êu s njima.
{49316}{49378}I neÊe imati pojma zaöto su ga ubili.
{49381}{49466}Pitat Êu poznaju li|Kennetha Eisleyja i Barbaru Carey,
{49474}{49578}no neÊe ih poznavati. I neÊemo|pronaÊi vezu izmeu njih troje.
{49705}{49763}To je isto, samo drukËije.
{49792}{49831}Imamo svjedoka.
{49855}{49921}Razgovarao bih s njim.|- Dobro.
{50048}{50130}Ovo je nadstojnik Stone.|Reci mu öto si rekao meni.
{50177}{50211}Naravno.
{50225}{50335}Ulice treba poploËiti.|NepoploËene su vrlo opasne.
{50349}{50416}Voda na ulicama, ulice pune rupa.
{50420}{50483}Philly, rekao si da si vidio neke automobile.
{50486}{50542}Da. Puno automobila.
{50573}{50613}I policijskih.
{50616}{50693}Ne, Philly, prije toga.
{50748}{50843}Da, bio je jedan auto. Crveni Explorer.
{50914}{50949}Siguran si?
{50982}{51036}Ne, ne baö.
{51590}{51616}Muökarci
{52146}{52194}»ekaj malo, Bo.
{52209}{52248}Ne moûete unutra.
{52251}{52315}Koristiö zabranjenu supstancu.|- äto?
{52318}{52390}Zabranjenu supstancu. Puöiö joint.
{52416}{52503}Ovo je muöki zahod.|- Doi u postaju.
{52661}{52708}Zajebi.
{52729}{52789}Nemoj da te uhitim. - Ti?
{52842}{52880}MiËi mi se s puta.
{52883}{52941}Imaö pravo na öutnju.|- Kujo jedna!
{52944}{52991}Odrekneö li se tog prava, sve öto kaûeö
{52994}{53074}moûe se iskoristiti protiv tebe na sudu.
{53077}{53107}»uvaj se.
{53398}{53443}Moûda je loöe vidio boju.
{53446}{53518}ToËno. I samo zato öto je|auto bio na dva mjesta...
{53521}{53614}U drûavi ima moûda 20.000|crvenih Explorera.
{53618}{53667}Nekih 2.000 u zemlji.
{53670}{53741}A to znaËi da su nas promatrali.
{53772}{53853}S druge strane,|barem imamo vjerodostojna svjedoka.
{53907}{53937}Nadstojnik Stone.
{53940}{54005}Vaöa tajnica je zvala. Andrew Lincoln.
{54008}{54046}Moja supruga, Brianna.|- Drago mi je.
{54049}{54117}I meni. Ovo je policajac Simpson.|- Zdravo.
{54137}{54174}Molim vas, uite.
{54359}{54406}Kofi, radije priËekaj ovdje.
{54452}{54509}Kako ste ga nazvali?|- Kofi.
{54522}{54564}SkraÊeno od kofer.
{54577}{54647}Kao Harry Kofer Simpson, igraË bejzbola?
{54650}{54677}Tako je.
{54680}{54735}Molim vas, sjednite.|- Hvala.
{54811}{54852}Dakle, radi se o ubojstvima?
{54855}{54941}Da. Vaö je automobil bio|u blizini mjesta ubojstva.
{54944}{54978}Gdje je ûena ustrijeljena.
{54981}{55064}Ondje smo vas prvo vidjeli,|istraûujuÊi mjesto zloËina.
{55070}{55102}Kako mi je iölo?
{55142}{55226}Zanimalo me imate li oruûje,|osobito kalibra 0.22?
{55229}{55293}Imamo. S dozvolom, naravno. Puöku 0.22.
{55296}{55395}Znali smo povremeno gaati|nametnike u vikendici.
{55398}{55469}Volio bih je posuditi na nekoliko dana.
{55472}{55533}Testirali bismo je da vas|moûemo maknuti s popisa.
{55536}{55593}Naravno, nadstojniËe Stone.|- Jesse.
{55606}{55643}Idem po nju.
{55850}{55902}Sjajan pogled, zar ne?
{55935}{56010}S policijskom plaÊom|ne bih si ga mogao priuötiti.
{56013}{56084}Svia nam se ovdje.|Ali imamo najam samo par mjeseci.
{56087}{56165}Uûivamo na moru, i idemo u|Palm Beach da se ne smrznemo.
{56168}{56220}Dobra ideja. äto vi radite, g. Lincoln?
{56223}{56308}Andy. Uglavnom se brinem za naö novac.
{56328}{56416}Bio sam oftalmolog.|Izumio sam napravu za skeniranje oka
{56419}{56503}koja laserom lomi zrake|i otkriva dubinu roûnice.
{56520}{56551}No, kako bilo...
{56579}{56636}Viöe niste u medicini?
{56639}{56693}Zaöto? Neöto vas muËi u oku?
{56696}{56761}Izvolite.|- Hvala.
{56786}{56835}Go Lincoln?|- Brianna.
{56854}{56911}Brianna, radite li?|- Ne, sada ne.
{56914}{56971}Zajedno smo nekih 15 g.
{56974}{57038}Sve to vrijeme, jednom se nismo prepirali.
{57041}{57121}Bilo bi sumnjivo da to ne uËinimo.|- Svaati se?
{57135}{57221}Ne, da vam ne posudimo puöku.|- Da, bilo bi.
{57264}{57331}Nadam se da Êete uloviti prokletnika, Jesse.
{57346}{57373}HoÊemo.
{57448}{57514}Ljudi dou iz grada i|misle da vladaju ovim mjestom.
{57517}{57553}Da, tako je.
{57567}{57627}»inio se drag.|- Samo glupi policajac.
{57630}{57685}Nije mi se Ëinio glup. Djelovao je pristojno.
{57688}{57741}Zaboga, buljio ti je u guzicu.
{57744}{57789}Rekla sam ti da nije glup.
{57896}{57965}Poslat Êu puöku na balistiËku obradu.
{57968}{58025}Ne ubijaju njime, ali oni su krivci.
{58343}{58389}Policajci smo, zar ne?
{58410}{58516}Da se potvrdimo kao policajci,|moramo ih srediti?
{58519}{58557}Da, tako je.
{58571}{58656}Pojest Êeö 12 krafna? - Prije ili kasnije.
{58690}{58745}Imaö pravo, predugo je proölo.
{58854}{58929}éelim znati sve o Andyju i Brianni:
{58958}{59060}Gdje ûive, gdje je vikendica,|gdje gaaju nametnike,
{59063}{59139}gdje je studirao medicinu,|gdje je iöao u ökolu.
{59270}{59305}"Gaaju nametnike."
{59342}{59417}Tko uopÊe tako govori?|Ljudi tako ne govore.
{59420}{59480}»im isprobamo tu stvarËicu,
{59483}{59560}znat Êemo da meci nisu ispaljeni iz te puöke.
{59566}{59631}Misliö da imaju joö piötolja?|- Dva.
{59634}{59693}I misliö da su to bili oni?|- Da.
{59702}{59750}Imaö sve öto trebaö osim dokaza.
{59753}{59785}To je sve öto nedostaje.
{59788}{59843}Osim motiva.|- Da, i to.
{59884}{59962}Ali im nisi rekao da im je|auto bio na parkingu.
{59965}{60029}Ne trebamo im reÊi sve öto znamo.
{60032}{60080}Jer imaö nekakav predosjeÊaj?
{60083}{60154}Jer je u njima neöto jako laûno.
{60159}{60226}U Paradiseu ima puno toga.
{60241}{60340}No oni su jedini laûnjaci Ëiji|je auto bio nedaleko ubojstva.
{60586}{60645}Uhitit Êeö me, ha?
{60700}{60764}Odlazim odavde.|- Ne, ne ideö nikamo.
{60804}{60876}Moûeö me zaustaviti?|- Naravno da mogu.
{60902}{60941}Samo si napuhan.
{60944}{61028}éena od 55 kg dovukla te|ovamo u lisiËinama.
{61081}{61113}Sjedni.
{61779}{61841}Tko je mlada dama?|- Ne znam.
{61848}{61891}Naöao sam ove fotografije.
{61895}{61945}Gdje?|- U ökolskoj knjiûnici.
{61973}{62021}Nekomu su vjerojatno ispale.
{62079}{62144}Ti nisi jedan od ovih koji ju drûe, ha?
{62147}{62209}Vidite li moje lice na ijednoj od fotografija?
{62288}{62344}Dosta si rekao, Bo.
{62347}{62436}Rita Fiore.|Odvjetnica g. Marina i njegova sina.
{62441}{62516}Nisam niöta uËinio, tata.|- äto se dogaa?!
{62519}{62613}Drûim mu sina zbog optuûbe|o posjedovanju droge.
{62620}{62668}Priveli ste ga zbog puöenja trave?
{62671}{62745}»eka vas tuûba zbog policijske|okrutnosti, samo da znate.
{62748}{62787}Tiho, g. Marino.
{62803}{62897}Uhitili smo vam klijenta|zbog posjedovanja trave
{62900}{63011}s namjerom prodaje, opiranja|policiji i uvrede policajca.
{63046}{63121}A postoji i pitanje ovih slika.
{63363}{63420}Pronaöao bih naËina da Boa puste,
{63423}{63495}ako bi identificirao deËke koji je drûe.
{63544}{63625}NadstojniËe Stone, moj klijent ima 17 g.
{63628}{63677}Nema prijaönjih osuda.
{63680}{63746}NeÊete ga valjda zadrûati preko noÊi?
{63749}{63777}HoÊu.
{63793}{63855}Htio bih da neöto shvatiö, Bo.
{63858}{63927}NijeËeö da poznajeö|osobe na ovoj fotografiji.
{63930}{64033}Ako laûeö, bilo bi pametno|da nam to odmah kaûeö,
{64036}{64084}uz prisutnost tvoje odvjetnice.
{64105}{64144}Ne poznajem ih.
{64178}{64264}Crane, molim vas odvedite|g. Marina u Êeliju.
{64306}{64334}Hajde.
{64449}{64536}Ti si prokletnik.|- Policajac prokletnik za tebe.
{64557}{64620}Osim ako ne ûeliö i ti provesti noÊ ovdje,
{64623}{64737}idi s gospoicom planirati|vaöu tuûbu za okrutnost.
{64797}{64835}Vidimo se vani.
{65044}{65142}Healey mi je rekao...|Kako ono? Bilo je slatko.
{65169}{65260}Ah, da. Rekao je da si pravi poötenjaËina.
{65280}{65314}Baö slatko.
{65416}{65445}Vidimo se.
{65999}{66087}Zaöto drûiö maloga preko noÊi?|- Jer mi se ne svia.
{66166}{66203}Kakav je bio otac?
{66217}{66286}Jabuka ne pada daleko od stabla.
{66352}{66428}Ako netko drugi propjeva,|moûda bude nagodbe,
{66431}{66483}i ona ne bi ni trebala svjedoËiti.
{66561}{66602}Izgledaö umorno, Jesse.
{66621}{66673}Moûeö uËiniti samo ono öto moûeö uËiniti.
{66687}{66735}Ako ubojstva nisu nasumiËna,
{66738}{66824}povezana su na naËin|koji samo ubojice razumiju.
{66846}{66893}Kofi kaûe da imaö predosjeÊaj.
{66927}{66962}Policijski predosjeÊaj.
{66984}{67034}I öto Êeö napraviti?
{67049}{67114}Pojest Êu pizzu i kuhano vino.
{67144}{67180}Kuhani alkohol je dobar.
{67190}{67253}Laku noÊ, Jesse.|- Laku noÊ, Moll.
{67267}{67340}Znam da si udana,|no mogli bismo biti ljubavnici.
{67343}{67389}Stavit Êu te na popis.
{67507}{67560}Ima jedna dvorana za bankete,
{67574}{67657}puna svjetla, i u njoj velika, topla vatra.
{67670}{67717}A vani je hladno i mraËno.
{67720}{67813}Unutra svi jedu i piju i sjajno se zabavljaju.
{67816}{67893}Vrabac uleti na jednom kraju dvorane
{67896}{67948}iz hladnoga mraka.
{67966}{68052}Proleti kroz svijetlu, toplu|dvoranu i izleti na drugi kraj
{68055}{68112}natrag u hladni mrak.
{68153}{68178}I?
{68188}{68289}Ljudski ûivot je poput leta tog vrapca.
{68341}{68379}Ili je bila lastavica?
{68444}{68507}Ne sjeÊam se. No smisao je isti.
{68540}{68647}Ovdje smo jako kratko i imamo|pravo to najbolje iskoristiti.
{69181}{69221}Da, znam, Reggie.
{70085}{70136}Moûeö uËiniti samo ono öto moûeö uËiniti.
{70503}{70546}Znaö li Boa Marina?
{70601}{70676}Je li on napravio one slike?|- Ne znam.
{70679}{70759}Je li joj netko drûao stopala?|- Niöta ne znam.
{70779}{70812}Dobro, Kevine.
{70829}{70884}Morat Êu te uhititi|zbog seksualnog zlostavljanja.
{70887}{70948}Ne, Ëekajte malo.|- Idem u zatvor?
{70997}{71044}Imamo tvoje fotografije
{71047}{71125}na kojima na silu drûiö djevojku koja plaËe.
{71128}{71191}Negdje u tomu je vjerojatno i zloËin.
{71205}{71281}Reci mu, Kevine. Je li to bio Bo Marino?
{71352}{71427}éeliö li u zatvor?|- Bit Êe bijesan na mene.
{71489}{71527}Je li to bio Bo Marino?
{71666}{71693}Da.
{71738}{71768}Tko joö?
{71801}{71841}Troy.|- Troy Drake?
{71871}{71896}Da.
{71934}{71987}Moûda Êeö veËeras spavati kod kuÊe.
{72004}{72084}Joö se nije uvukao u probleme.|- Sada jest.
{72107}{72187}NeÊe valjda u zatvor?|- Ne veËeras.
{72204}{72319}Ali sin vam je sudjelovao|u silovanju 16-ogodiönje djevojke.
{72345}{72394}Morat Êe odgovarati za to.
{72449}{72468}äto joö?
{72477}{72554}Andrew Lincoln oûenio se|Briannom Douglas 1988.
{72562}{72659}éivjeli su u Clevelandu dok|je on bio na specijalizaciji,
{72665}{72696}do 1990.
{72699}{72794}Imaju dva automobila:|Crveni Explorer i... - Crni BMW.
{72817}{72856}Kako znaö to?
{72873}{72970}Nadstojnik sam, sve znam.|Morat Êu te nazvati kasnije.
{73066}{73104}Nastavit Êemo razgovor.
{73261}{73340}Gice Fiore. - SaËuvaj gice za sud.
{73380}{73421}Je li ovo unutarnji poziv?
{73446}{73538}NatoËi mi piÊe, moûe?|Jako veliki i suhi martini.
{73545}{73590}A votka s ledom?
{73593}{73636}Imaö Kettle One?|- Da.
{73730}{73804}Plan mi je bio da te moj izgled tako oËara
{73807}{73856}da bi radio sve öto ûelim.
{73865}{73904}Uspijeva.
{73925}{74008}Jadan naËin da se Boa optuûi za silovanje.
{74050}{74080}Zasluûio je.
{74111}{74176}Mogu te posebno odvesti na sud za to.
{74198}{74265}No da to uËinim,|kako bih te odvela u krevet?
{74491}{74538}Razmiöljaö li puno?
{74541}{74623}Uglavnom mislim, opa.|- Dobro je. Opa mi se svia.
{74645}{74720}U stankama, kad ne misliö opa,
{74723}{74792}znaj da sam malo istraûivala.
{74795}{74843}Temeljito.|- Ja sam vrlo temeljita.
{74863}{74931}A imam i pomoÊ velike odvjetniËke tvrtke.
{74993}{75031}Pokuöaj ne baljezgati.
{75213}{75271}Morala sam znati s Ëime imam posla.
{75365}{75424}Bio si detektiv za ubojstva u Los Angelesu,
{75427}{75509}ali ti je brak bio u krizi|i imao si problem s piÊem.
{75517}{75573}Kako je brak?|- Joö je u krizi.
{75582}{75630}A piÊe?|- Bolje.
{75662}{75742}Znam i da ti ovuda operira serijski ubojica.
{75746}{75772}Da.
{75778}{75842}Sigurno ste u guûvi.|- Jesmo.
{75845}{75916}Ali ste ipak naöli vremena|pozabaviti se ovim silovanjem.
{75945}{76012}ObiËno, kada doete u ove male gradove,
{76015}{76101}i dogodi se ubojstvo,|drûavna policija brzo preuzme.
{76104}{76167}Trudimo se öto viöe toga rjeöavati sami.
{76544}{76576}»asti me veËerom.
{76606}{76639}Lijepo Êu se obuÊi.
{76658}{76706}Malo se napirlitati.
{76724}{76751}Opa.
{76925}{77000}Znam pod kolikim ste sada pritiskom
{77003}{77054}i cijenimo öto ste odvojili vremena za nas.
{77065}{77127}Candace i ja smo znali tko ju je silovao.
{77141}{77242}No sloûili smo se ako bismo to razglasili,
{77245}{77350}moûda ih ne ulovite, a njoj|bismo zagorËali ûivot ovdje.
{77374}{77426}Svima bi pokazali moju fotografiju.
{77429}{77476}Sada vjerojatno neÊe.
{77562}{77632}Dat Êu iskaz. SvjedoËit Êu, bude li potrebno.
{77649}{77680}Bravo.
{77725}{77781}Makni se s mene!|- Ne moûeö unutra.
{77784}{77845}Ovo je glupost. Kevin Feeney je lagao.
{77848}{77912}éao mi je, kapetane.|- U redu je, Tony.
{77920}{77964}Zatvori vrata iza sebe.
{78029}{78081}Moj sin vam je rekao da joj nije prijetio.
{78084}{78180}Rekao joj je da Êe je ubiti|bude li svjedoËila protiv njega.
{78183}{78232}Dajte, njegova rijeË protiv njezine.
{78235}{78314}Nemojte da moram izabrati.|- äto to znaËi?
{78317}{78381}To znaËi da sam shvatio|da je Bo kroniËni laûljivac.
{78401}{78460}Nisam niöta napravio gaduri!
{78665}{78700}Pustite moga sina!
{78834}{78927}Uhitite ga! Uhitite prokletnika|zbog fiziËkog nasrtanja.
{78930}{78960}Polako.
{79056}{79101}Sjednite, g. Penningtone.
{79192}{79256}ObeÊavam da vas viöe neÊe napadati.
{79265}{79293}äto?
{79383}{79422}Vidjeli ste cijelu stvar.
{79428}{79527}Vidio sam kako vrijeate|Candace i njezina oca.
{79551}{79616}Jeste li vi vidjeli|neöto drugo, g. Penningtone?
{79626}{79671}Ne, i ja sam to vidio.
{79681}{79711}I ja.
{79725}{79789}Udario mi je sina bez razloga.
{79810}{79860}Mislim da je postojao razlog.
{80319}{80374}äto, tvoja fotografija u mojoj spavaÊoj sobi?
{80377}{80441}äto napraviö s njom kada ti netko doe?
{80444}{80499}Ostaje. Moraju znati za tebe.
{80676}{80739}I, öto misliö?|- Da mi netko doe?
{80752}{80835}Ne, o mome dolasku.|Znaö, svi mediji u zemlji
{80838}{80911}ûude za nekakvom priËom|iznutra o svemu ovomu.
{80916}{80943}Znam.
{80959}{81047}Doöla bih sa snimateljem i malo istraûivala.
{81050}{81115}Pogled iznutra na to|kako se ti nosiö sa svime.
{81130}{81206}Ne.|- Moûemo napraviti cijelu seriju.
{81231}{81292}Ne, Jenn.|- Ne bih se mijeöala.
{81496}{81527}Hej, Abby.
{83248}{83275}Hej, Jesse.
{83334}{83397}Dva u prsa, kao i ostali.
{83400}{83477}Hladno jutro.|Teûe Êemo odrediti vrijeme smrti.
{83480}{83508}Hej, doktore.
{83530}{83559}Ne sada.
{83762}{83802}Jesse, ûao mi je.
{85228}{85316}Moûda bih trebao sve|poslati k vragu i napiti se.
{85346}{85390}Bog zna da sam dobar u tomu.
{86452}{86536}Ne znam koja je svrha|u zatvaranju tih klinaca.
{86539}{86634}Nisu znali da Ëine loöe?|Nisu se mogli suzdrûati?
{86637}{86721}Nisu.|- Nema nagodbe. Zasluûuju zatvor.
{86760}{86829}Candace ne moûe zamisliti|da sutra ide u ökolu.
{86832}{86915}Ne moûe zamisliti suoËiti se|sa svim kolegama koji znaju
{86918}{86983}da je viöestruko silovana|i fotografirana gola,
{86986}{87099}a trojica poËinitelja bit Êe|u istoj ökoli kao i ona.
{87116}{87151}Moûda i u istom razredu.
{87154}{87227}Moûda nisam mala djevojËica,|ali ûena jesam.
{87231}{87283}I kao ûena, suosjeÊam s njom.
{87286}{87351}Je li sud odredio druötveni rad?
{87379}{87404}Nije joö.
{87407}{87455}Imam li ja pravo glasa?
{87466}{87504}äto bi da uËinimo?
{87507}{87613}Daj mi ih na 1 h u Êeliju.|Daj mi da ih isprebijam.
{87641}{87691}äaliö se?|- Da.
{87730}{87826}Zaöto ne bi odsluûili svoje u policiji?
{87840}{87940}Ti bi, naravno, ozbiljno|shvatio svoje odgovornosti.
{87943}{87989}Ja bih digao paniku.
{88038}{88089}Ali ih ne bih ni taknuo.
{88120}{88160}Vidjet Êu öto mogu.
{88199}{88269}A nerijeöena ubojstva|na podruËju Clevelanda?
{88272}{88310}Niöta se ne podudara.
{88313}{88391}Pucali su na djevojku|u Parmi, blizu Clevelanda.
{88394}{88443}Znam gdje je Parma.
{88480}{88541}Jedino öto se podudara|s ovim naËinom ubijanja
{88544}{88623}dva su ubojstva u Hilton Headu 1999.
{88626}{88685}I tri na Floridi 2002.
{88691}{88727}Gdje na Floridi?
{88772}{88798}U Palm Beachu.
{88892}{88958}Ovdje je tip sa CNN-a.|éeli razgovarati s tobom.
{88961}{89004}Koji?|- Ne znam.
{89020}{89059}To mu se neÊe svidjeti.
{89068}{89150}Svako jutro dajemo izvjeöÊe.|Reci mu kada i gdje.
{89153}{89178}Dobro.
{89196}{89238}Moûda dobijemo nalog za pretres.
{89241}{89310}Nijedan nam sudac neÊe dati|nalog s ovime öto imamo.
{89313}{89344}I ondje neÊe biti oruûja.
{89347}{89412}Moûemo pokuöati.|- Ne ûelim da prestanu!
{89848}{89885}Dobar posao.
{89910}{89965}Moûda jednom postaneö detektiv.
{90015}{90063}Nemamo detektiva ovdje.
{90114}{90170}Ali da ih imamo.
{90651}{90701}éao mi je za tvoju djevojku.
{90732}{90800}Nije mi bila djevojka, veÊ prijateljica.
{90856}{90891}Ne, hvala.
{90894}{90949}Ne pijeö niöta.|- Ne pijem.
{91008}{91043}Pio sam, ali viöe ne.
{91113}{91185}Evo. Mrzim piti sama.
{91288}{91378}Javni tuûilac pristaje na tvoj plan.|äto Êeö uËiniti?
{91422}{91516}Odvest Êu ih na sterilizaciju kod Perkinsa.
{91560}{91639}Marinovi ûele da dignem tuûbu protiv tebe.
{91671}{91745}Sve se dogodilo tako brzo.|- Sigurna sam.
{91774}{91835}I Ëinilo mi se da sporo reagiraö.
{91838}{91915}Bo je napao Candaceina oca|koji je reagirao samoobranom.
{91918}{92014}I Joe se umijeöao, pa se Chuck|morao braniti od obojice.
{92017}{92090}Tako Êeö svjedoËiti na sudu?|- Svakako.
{92332}{92394}Bila sam tuûiteljica u proölom ûivotu.
{92423}{92466}Nemoj se prenaprezati.
{92477}{92559}To je najteûa vrsta sluËaja,|nasumiËno ubojstvo bez motiva.
{92572}{92661}»ini se da serijski ubojice|zabrljaju samo osobne stvari.
{92784}{92831}Kad idemo na sud?
{92839}{92901}Ovo nije baö na naöoj strani.
{92911}{92967}Nagovorit Êu svoje klijente da odustanu.
{92976}{93031}Ako ne ûele?|- HoÊe.
{93138}{93236}äto se zapravo dogodilo|s Boom i njegovim ocem?
{93256}{93352}Pennington ih je prebio,|a ja sam mu to dopustio.
{93367}{93433}Zaprepaötena sam.|- Ne baö toliko.
{93496}{93521}Ne.
{93542}{93588}Bit Êe to naöa tajna.
{93599}{93678}Moûda ih bude joö nekoliko|prije nego ovo zavröi.
{94161}{94228}Stiglo je balistiËko izvjeöÊe za treÊu ûrtvu.
{94251}{94323}Isti kao kod prve dvije. Ista dva piötolja.
{94364}{94438}Tko joö zna za ovo?|- Za sada, samo ti i ja.
{94459}{94539}Dobro.|- Ponestaje mi izgovora.
{94594}{94635}Smrzavam se vani.
{94652}{94723}Kad sam otiöao iz policije u Los Angelesu,
{94726}{94777}doöao sam u Santa Monicu|i samo gledao ocean.
{94790}{94863}Izgubio sam i ûenu i posao.|Ocean me smirivao.
{94919}{94984}OsjeÊaö li se sada tako?|- Ne.
{94988}{95019}Ljut sam.
{95048}{95088}Ubili su mi prijateljicu.
{95091}{95174}Misliö da su ti namjerno ubili prijateljicu?
{95198}{95223}Da.
{95276}{95314}Znam tko je to uËinio.
{95362}{95434}Znam tko je ubio Eisleyja, ûenu na parkingu,
{95437}{95497}tipa u uliËici i Abby.
{95530}{95575}Znam tko ih je ubio.
{95608}{95652}Imaö li motiv?|- Ne.
{95656}{95695}Svjedoka?|- Ne.
{95699}{95727}Oruûje?|- Ne.
{95733}{95803}Mogu odmah pripremiti Êeliju.
{95852}{95888}Dvoje ih je.
{95912}{95979}I neÊe prestati. Ja im neÊu dopustiti.
{96004}{96111}»ini se da ih i ja zanimam,|a moûda ih i ohrabrim.
{96141}{96213}Dakle, to dvoje ljudi ûele ubijati ljude,
{96216}{96275}a sada ûele ubiti i tebe?
{96278}{96327}Nije li ovo sjajna zemlja?
{96339}{96449}Jesse, radije budi oprezan s tim ljudima.
{96502}{96582}Ja sam sa svima oprezan.|- Jesi vraga.
{96636}{96702}Ne bi bilo dobro ovo primiti k srcu.
{96726}{96788}Predugo sam u ovomu|da ne bih imao pravo.
{96791}{96881}Ne mislim sjediti i Ëekati|da pronau novo tijelo.
{97161}{97215}Tako me voliö uznemiriti.
{97389}{97416}Trebaö prijevoz?
{97465}{97503}Vidjet Êe te.
{97662}{97691}Dobro zvuËi.
{97694}{97753}Znaö öto joö bolje zvuËi?|- äto?
{97994}{98031}Izgleda umorno.
{98068}{98113}Ja mislim da izgleda zabrinuto.
{98183}{98239}Moûda smo previöe bezobzirni s njime.
{98264}{98367}Ljudski je ûivot poput vrapËeva leta.
{98832}{98866}To je Reggie.
{98886}{98931}Mislio sam da moûda trebate ovo.
{98957}{98983}Uite.
{99025}{99117}Napravili su balistiËki test?|- Da. Poslali smo ga u Boston.
{99134}{99199}Doite u dnevni boravak.|Brianna vas ûeli vidjeti.
{99202}{99248}Bri, duöo, Jesse je.
{99342}{99410}Pretpostavljam da nije|vezano uz onu pucnjavu.
{99413}{99474}Zapravo, nije ni pucano.
{99492}{99540}Toliko o gaanju nametnika.
{99546}{99611}Moûda je to bila jedna od vaöih drugih 0.22.|- Nije.
{99614}{99659}Nemam drugo oruûje.
{99679}{99708}Jesse Stone.
{99711}{99743}Brianna.|- Zdravo.
{99748}{99805}Kako ste lijepog psa doveli!
{99808}{99864}Zdravo. Kako je sladak.
{99867}{99907}Zdravo, maleni.
{99910}{99998}Zapravo sam ga posvojio.|Bio je od prve ûrtve.
{100001}{100053}Jako dobro za vas.
{100086}{100119}Kako je sladak.
{100142}{100212}Mislim da mu se sviate.|- Jasno da mu se sviam.
{100293}{100328}Idete nekamo?
{100331}{100399}Kao öto sam rekao, kratko smo ovdje.
{100416}{100470}Kada odlazite?|- Sutra naveËer.
{100478}{100570}Kako ide istraga?|- Zapravo ne najbolje.
{100596}{100659}Nadam se da ûrtve nisu puno patile.
{100662}{100734}Pitam se kako je znati da Êeö umrijeti.
{100751}{100814}Jeste li ikada bili u toj situaciji, Jesse?
{100819}{100908}Ja sam provincijski policajac.|Izdajem kazne za parking.
{100928}{100990}Sigurno je jako napeto.
{101015}{101108}Pitam se kako je onomu|koji puca. Sigurno je napeto.
{101111}{101180}Primjena najveÊe ljudske moÊi.
{101183}{101275}Ako misli na takve stvari.|- Mislite li da misli?
{101278}{101361}Ja sam provincijski policajac.|Izdajem kazne za parking.
{101384}{101464}Imate li kakav trag?|- Oslanjao sam se na vas.
{101496}{101536}Svi trebaju razonodu.
{101561}{101650}Ozbiljno, zaöto bismo napravili takvo öto?
{101680}{101714}ZajedniËka perverzija.
{101778}{101824}Barem bismo neöto dijelili.
{101999}{102042}Tko je zadnja ûrtva?
{102094}{102129}Moja prijateljica.
{102132}{102206}Abby Taylor. ProËitao sam u novinama.
{102212}{102289}Sigurno je teöko kada ti je to netko blizak.
{102315}{102341}éao mi je.
{102378}{102404}I meni.
{102540}{102618}Abigail, o, Abigail|Jeste li upoznali Abigail?
{102648}{102730}Kraljicu istetoviranih dama
{102807}{102860}Kako je?
{102869}{102929}Mama mi je malo mrzovoljna.
{102972}{103029}A tata?|- Tata je super.
{103033}{103112}Joö nikada nije ovako stao meni u obranu.
{103189}{103260}Niste to pokuöali zaustaviti.|- Pobjeivao je.
{103295}{103340}Tata je boksao na koledûu.
{103347}{103436}Sigurno je bio dobar. Nema oûiljaka na licu.
{103446}{103513}Jeste li vi ikada boksali?|- Ja ne boksam, ja se borim.
{103543}{103593}U Ëemu je razlika?|- U pravilima.
{103686}{103735}I, kako je u ökoli?
{103793}{103884}Katkad Bo ili Troy bulje|u mene kada prolazim.
{103908}{103952}Ali niöta ne kaûu.
{104008}{104114}VeÊina druge djece dobro se ponijelo.
{104145}{104172}Dobro.
{104420}{104491}éelim da znate da cijenim|to öto ste uËinili za mene.
{104550}{104605}Moûe usluga?|- Naravno.
{104623}{104706}Reggie nema vlasnika, nema obitelj.
{104740}{104784}Mene nikada nema doma,
{104801}{104862}a on treba nekoga da se brine za njega.
{104865}{104931}Moûeö li ga ti uzeti?|- Ne znam, moja mama...
{104934}{104988}Mogu razgovarati s tvojom mamom.
{105012}{105058}Ali se ti moraö brinuti za njega.
{105061}{105137}Hrani ga, öeÊi, Ëisti za njim.|- Znam.
{105168}{105200}Mogu ja to.
{105228}{105264}Znam da moûeö.
{105547}{105572}äto?
{105633}{105678}éao mi je zbog vaöe prijateljice.
{105728}{105765}Hvala, Candace.
{106333}{106412}I, zaöto Abby?|- Jer mi je bila bliska.
{106465}{106557}Misliö da ûele ubiti tebe?|- Nadam se da Êe pokuöati.
{106601}{106651}Znam da nisu gotovi.
{106700}{106789}Znaju gdje ûiviö. Zaöto|ne vrebaju ondje i ubiju te?
{106792}{106852}éele uËiniti neöto viöe umjetniËki.
{106855}{106915}Ludi su. Uvijek to zaboravim.
{106922}{106971}Mislim da su pogrijeöili.
{107003}{107039}Viöe ne idu nasumce.
{107042}{107122}Kao da me ûele muËiti, vidjeti moju reakciju.
{107138}{107206}Moûda bi trebao biti malo paûljiviji.
{107209}{107243}Trebam dokaze.
{107259}{107312}Misliö da Êe te napasti na isti naËin?
{107315}{107386}Serijski ubojice vole ritual.|Napravit Êe sve isto.
{107395}{107500}Jesse, bolji si Ëovjek i|policajac nego grad zasluûuje.
{107538}{107592}Vaûno je öto ti se dogodi.
{107615}{107709}Ruûna istina je da meni to nije tako vaûno.
{107734}{107791}Puno te ljudi voli, Jesse.
{107813}{107864}I ti?|- Osobito ja.
{107885}{107945}I nemoj mi biti sladunjav.
{107966}{108014}Teöko mi je ne biti sladunjav.
{108284}{108369}Reggie Êe biti dobar za Candace.|To je bilo slatko.
{109276}{109324}Jesse, ja sam. Ja...
{109386}{109435}Jessie, Candace je.
{109483}{109576}Nisam vam dovoljno zahvalila|za sve öto ste napravili.
{109593}{109676}Toliko ste mi pomogli, a sada i Reggie...
{109720}{109800}Samo ûelim da znate da sam vam prijateljica
{109803}{109876}i da vam se osjeÊam jako blizu.
{109887}{109922}Dobro, zdravo.
{110341}{110392}Halo?|- Jesse je.
{110423}{110497}Moram vas oboje vidjeti prije nego odete.
{110500}{110608}Na parkiraliötu gdje je|Abby Taylor ubijena. Znate.
{110621}{110676}Kada?|- VeËeras u 22.
{110679}{110718}Je li sluûbeno?
{110724}{110773}Ne, osobno.
{110954}{111008}Ako imam pravo, oni Êe biti ondje.
{111060}{111092}Glupi policajac.
{111113}{111173}Misli da podmeÊe nekakvu zamku.
{111187}{111244}Moûe li iöta uËiniti?|- Nije vaûno.
{111274}{111357}Ovo nam samo olaköava.|Sad znamo gdje Êe biti.
{111558}{111598}Zaöto sam opet ovdje?
{111641}{111688}Imaö djecu i supruga.
{111691}{111742}Jako ljubazno i gospodski od tebe,
{111745}{111842}i znam da to Ëiniö jer ti je|stalo do mene, ali je teöko.
{111868}{111929}Vidiö li iöta, Kofi?|- Joö ne.
{112028}{112066}äto ako si u krivu?
{112102}{112151}Zato imam tebe, Molly.
{112589}{112644}Jesse, mislim da neÊe doÊi.
{112749}{112784}HoÊe.
{112937}{112968}Doöli su.
{112981}{113044}Stiûemo Ëim uzmognemo. Jesi Ëuo?
{113047}{113074}KreÊemo.
{113798}{113870}NeÊu psa u kuÊi.|- Ovo je drukËije.
{113963}{114022}Ja Êu ga paziti.|- Osim ako neÊeö.
{114025}{114051}Tata.
{114187}{114254}Margaret, to joj toliko znaËi.
{114257}{114341}Znaö pravilo.|- Moûemo li malo popustiti?
{114347}{114382}Reggie treba dom.
{114385}{114456}Znaö öto mislim o ûivotinjama u kuÊi.
{114461}{114523}On je sjajan pas.|VeÊ je imao problematiËan dom.
{114528}{114592}ObeÊavam da Êu se brinuti za njega.|- Margaret.
{114605}{114693}Ali, stvarno ga ûelim.|- Ne ûelim psa u kuÊi.
{114701}{114788}Brinut Êu se za njega.|- Osim kada neÊeö.
{114791}{114854}Tata.|- Margaret, ovo joj toliko znaËi.
{114857}{114896}Candace nije kod kuÊe.
{115780}{115812}Podignite to.
{115929}{115996}I da vam dopustim da me pogubite?|- Podignite to.
{116070}{116113}Nisam nikoga ubio.
{116168}{116274}Moûda odsjedim malo, no|nijedan me sud neÊe pogubiti.
{116364}{116413}Nadûivjet Êu vas, Jesse.
{116625}{116654}Diûite se.
{118174}{118250}Makni piötolj prije nego upucaö nekoga.
{118342}{118376}Jesi dobro?
{118465}{118508}Dva piötolja, jedan poËinitelj.
{118548}{118587}Daj to Healeyju.
{120205}{120249}äto gledaö?
{120333}{120389}Jesse, jesi tamo?
{120460}{120493}éao mi je.
{120517}{120624}Znam da sam mislila samo|na sebe i svoju karijeru,
{120635}{120702}i znam da sam se Ëesto|tako ponaöala prema tebi.
{120774}{120843}Jesse, jesi tamo?
{120844}{121044}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
{121069}{122569}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/48h2j|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
