{87}{87}25.000
{112}{262}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{1482}{1671}NIJE ME STRAH
{3279}{3359}Michele! - Maria!
{3379}{3421}Pala sam!
{3563}{3619}Kamo ideö?
{3749}{3828}Razbile su se.|- Rekao sam ti da ne ideö.
{3834}{3920}äto Êu sada? - Zalijepit|Êemo ih. Idemo.
{3960}{4019}Hajde, trËi!
{4244}{4327}Odvratno!|- Proöli su ovuda.
{4366}{4516}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
{4626}{4682}Eno neke kuÊe.
{4818}{4955}»estitam, uspjeli ste.|- Moja se sestra povrijedila.
{5010}{5093}Gdje su ostali?|- Tamo dolje.
{5294}{5353}Tko je pobijedio?|- Lubanja.
{5556}{5657}Ovo mjesto pripada meni.|- Zaöto? -Jer sam ga prvi vidio.
{5705}{5776}Tko nae, njegovo je...
{5803}{5919}Tko je izgubio?|- Ti, jer si zadnji stigao.
{5992}{6094}Morao sam zastati, jer|mi se sestra povrijedila.
{6104}{6262}Izgubio si.|- Tko mora platiti? - Ona.
{6280}{6375}Nije poöteno, zaöto|uvijek ja? Glasajmo.
{6394}{6463}Ne moûe on uvijek|odluËivati o svemu.
{6488}{6607}U redu, glasajmo, ja kaûem|da ti gubiö. - I ja. - I ja.
{6622}{6728}I ja. - I ja.|- Vidiö?
{6838}{6907}äto moram uËiniti?
{6915}{7000}Pokaûi nam je.|- Nema öanse!
{7011}{7070}äto nam mora pokazati?|- Pst!
{7163}{7227}Izgubila si, moraö|to uËiniti. - NeÊu. 
{7239}{7289}NeÊeö?
{7433}{7509}NeÊete niöta reÊi?
{7561}{7654}U redu. NeÊu se viöe|igrati s vama, budale.
{7747}{7835}PlaËeö? - Ne plaËem.
{8926}{8981}Stani.
{9028}{9128}Ja Êu platiti,|zadnji sam doöao.
{9421}{9481}Sranje!
{9517}{9582}Prijei preko.
{10346}{10402}Bio je »ovjek-guöter...
{10408}{10468}...hodao je po zidovima.
{10757}{10832}Tada je postao|Stakleni »ovjek.
{10840}{10942}Ako padne, razbije se.|- äto kaûeö? - Niöta.
{11176}{11251}SkoËi na onu granu|i spusti se dolje.
{11777}{11877}Michele...|Daj mi moje naoËale.
{11953}{12049}Izgubio sam ih.|- Mama Êe te ubiti.
{12062}{12115}PriËekaj ovdje.
{14762}{14855}Jama puna|zlata i dragulja...
{15403}{15487}Jesi li ih naöao?|- TrËi, kasnimo.
{15978}{16045}Eno mame!
{16076}{16154}Gdje ste bili?|Traûila sam vas.
{16162}{16233}Koliko vam puta moram|reÊi da se ne udaljavate?
{16241}{16349}Michele, ovaj put...|- Bili smo... - Odmah kuÊi!
{16681}{16737}Tata je stigao!
{16881}{16921}Tata!
{16929}{17006}Kako si teûak! Lutkice|tatina, daj mi pusu.
{17021}{17114}Gdje ste bili? - Igrali se kraj|potoka. Koliko ostajeö?
{17122}{17286}Kratko. Razbila si naoËale?|- Opet? - Pala je.
{17294}{17350}Moûemo ih zalijepiti.
{17357}{17425}Michele, öto sam ti rekla?|- Nema veze.
{17450}{17546}Jesi li radio sklekove?|- Nije. - Jesam.
{17584}{17660}Vidjet Êemo. Ne budeö li bolji|od mene, nema poklona.
{17665}{17745}Poklon? Kakav poklon?|- Kakav poklon? - Vidjet Êete.
{17943}{18024}Imaö miöiÊe od maslaca?
{18078}{18126}Hajde...
{18132}{18196}SlabiÊ si.
{18343}{18409}Maria, pomozi mu.
{18638}{18704}Sad nam daj poklon!
{18721}{18779}Anna, donesi kutiju.
{18935}{18999}Polako!
{19116}{19175}Brod...|- Ne.
{19180}{19246}To nije brod, veÊ gondola.
{19260}{19351}äto je to? - Brod kakav moûete|naÊi samo u Veneciji.
{19361}{19426}Sa samo jednim veslom?|- äto je to veslo?
{19435}{19493}ätap kojim se pokreÊe brod.
{19513}{19566}Lijep je.|- Nemojte.
{19589}{19652}S time se ne moûete igrati.
{19678}{19795}Policijska Jedinica za|zaötitu UmjetniËke Baötine
{19806}{19936}je otkrila dvije dragocjene|skulpture iz 16. stoljeÊa
{19942}{19987}smatrane djelima|Benvenuta Cellinija.
{19994}{20075}Na kome je red da donese|vino? - Mariin. - Ne da mi se.
{20092}{20193}Idi ti. - NeÊu. Na tebi je red.|- Ne ûelim iÊi.
{20201}{20289}Zaöto ne? - Boli me glava.|- Uvijek se tako izvlaËiö.
{20296}{20441}äutite! Pustite me da Ëujem.|- Prestanite! Idi ti, Michele.
{20493}{20548}Nije poöteno.
{20566}{20663}Nakon poraza maËevalaca|u Hamburgu...
{20670}{20774}äto se dogodilo? - Na njoj|je red da donese vino.
{20850}{20959}Znate li kako u ratu odluËuju|tko ide na opasne zadatke?
{21180}{21270}Tko izvuËe|kraÊu öibicu, mora iÊi.
{21571}{21752}Ti si je izvukao! - Izgubio|si, moraö po vino.
{22459}{22566}Zakopali su ga, i on|poËiva u zemljinoj utrobi...
{22630}{22733}...meu tajnama, truplima,|kostima, kosturima i tami.
{29122}{29199}Gdje si bio?|Mama te traûi.
{29205}{29259}Ljuti su.
{29268}{29340}Jesu li ti udobne cipele?|Kupit Êemo ih.
{29416}{29526}Nadam se da mogu nagovoriti|mamu, doista su slatke.
{29554}{29688}Anna, öto misliö?|- Da vidim. äto ti misliö?
{29753}{29815}Koliko traûite za ove?
{29846}{29931}Koliko koötaju?|- To je dobra marka.
{29939}{30003}Imam i ostale modele.
{30123}{30212}Pino, sin ti je stigao.
{30310}{30378}Gdje si bio?|- äetao sam.
{30387}{30457}Vraga si öetao!|Znaö li koliko je sati?
{30464}{30500}Skoro su 2 sata!|Nitko nije znao gdje si.
{30507}{30533}Mama te je otiöla traûiti.
{30540}{30599}Moraö prestati|Ëiniti öto te volja!
{30605}{30672}éeliö li raditi po svome,|onda idi. Gubi se.
{30782}{30867}Gubi se!
{32249}{32336}Michele, sii dolje! - äto|ûeliö? - VeËera je gotova.
{32344}{32417}Reci da viöe nisam|njihov sin. Ne vraÊam se.
{32425}{32486}Nisi viöe ni moj brat?|- Nisam!
{32493}{32576}Onda mogu uzeti tvoje|stripove? - Ne moûeö.
{32583}{32641}To nema veze s time.
{32718}{32789}Mama Êe se naljutiti.
{32817}{32891}Gdje je tata? - Otiöao je,|kasno Êe se vratiti.
{32945}{33030}äto ima za veËeru?|- Pire krumpir s jajima.
{34240}{34297}Dobro jutro!
{34308}{34385}Pao si s kreveta?|- Razmiöljao sam.
{34392}{34458}O Ëemu si razmiöljao?|- Daj tati pusu.
{34728}{34825}Mislio sam da si ljut.|- O Ëemu si razmiöljao?
{34848}{34938}Reci nam.|- O tuûnim stvarima.
{34962}{35036}Pripremi se, jer veËeras|Êemo obarati ruku.
{35061}{35168}Anna! Kupi mi kobasica.
{35557}{35627}Tata, kad Êeö se vratiti?|- Kasno!
{35920}{35976}Michele.
{36002}{36063}Jedan, dva, tri, crveno!
{36115}{36183}Michele.
{36267}{36326}äto radiö?|- Ne ûelim viöe igrati.
{36332}{36388}HoÊeö da idem s tobom?
{36432}{36487}Pusti ga.
{37831}{37891}Vode...
{37907}{37965}Jesi li ûiv?
{38072}{38183}Vode... - äto kaûeö?|Ne razumijem te.
{38289}{38405}Vode... - éedan si!|éeliö vode?
{38416}{38483}éedan...|- PriËekaj.
{40307}{40363}Gladan...
{40393}{40510}Gladan si?|Nemam niöta za jelo.
{40813}{40968}Sad moram kuÊi. Ako ûeliö,|donijet Êu ti neöto sutra.
{41214}{41308}Jesi li ti dijete?
{42534}{42579}äto radiö ovdje?
{42586}{42687}Poznajem te. Ti si|Amitranov sin, zar ne?
{42695}{42778}Da te viöe nisam vidio ovdje!|Vidim li te opet...
{42794}{42964}Vidiö one svinje? Uvijek su|gladne. Jedu Ëak i kosti.
{43980}{44096}Michele... äto to radiö?|- Niöta, igram se.
{44136}{44225}Vrati sve na mjesto.
{44645}{44741}Ne mogu viöe.|- Pojedi meso.
{44750}{44796}Od njega me boli glava.
{44803}{44867}Ne mogu viöe to izdrûati!|- Anna, ako ne ûeli...
{44880}{44924}Nije bitno.
{45425}{45511}Netko Êe nam doÊi|za par dana.
{45518}{45570}Pa molim bez|strke i cviljenja.
{45607}{45726}Tko Êe nam doÊi?|- Prijatelj.
{45754}{45827}Kako se zove?|- Sergio.
{45875}{45933}Smijeöno ime.
{46004}{46074}Mama i tata oËekuju bebu.
{46096}{46199}Ali, umjesto jedne, raaju se|dvije, jedna plavokosa
{46205}{46264}i jedna smeokosa. Smeokosa|je normalna, a plavokosa luda.
{46269}{46386}Kada ga mama doji,|on ju ugrize do krvi.
{46391}{46486}Mama ga viöe ne ûeli.|Pa kaûe tati da ga ubije.
{46493}{46566}Tata ga odvede u visoku|planinu, ali ga ne moûe
{46574}{46710}probosti jer je to grijeh.|Zato on iskopa rupu
{46717}{46809}i stavi ga u nju. Donosi mu|hranu i vodu da ne umre.
{46903}{46972}Onda on...
{47036}{47144}...neÊe umrijeti.
{47732}{47790}Bok, Michele.
{48066}{48131}äto trebaö?
{48189}{48323}äto mogu kupiti za 500 lira?|- Ne znam, ovisi öto trebaö.
{48332}{48437}Neöto dobro. Imate li|Ëokoladne kekse? - Nemam.
{48446}{48506}Slatkiöi su ondje.
{48557}{48630}Krafnu, Ëokoladicu...
{48703}{48888}Ili KitKat...|Svi su dobri.
{48997}{49061}Assunta... - äto je bilo?
{49069}{49168}Ako je netko gladan, öto|moûe kupiti za 500 lira?
{49193}{49337}Moûe kupiti kruha. Kad je|netko gladan, kupi kruha.
{52433}{52507}éelio sam te pitati neöto...
{52514}{52611}Poznajeö li Felicea,|Lubanjinog brata?
{52630}{52731}Felice Natale.|Ja ga mrzim.
{52823}{53024}On ti donosi hranu? Vidio sam|ga kako odlazi autom odavde...
{53029}{53090}pa sam pomislio...
{53371}{53428}Sada moram kuÊi.
{53521}{53577}U redu?
{53671}{53727}Bok.
{53853}{53927}Jesi li gluh?
{54425}{54526}Sluöaj, oprosti...|Sjetio sam se neËega.
{54541}{54637}Ako neÊeö pojesti kruh,|hoÊeö li mi ga vratiti?
{55014}{55153}Da objasnim. Ako doe Felice,|i pronae ga, shvatit Êe.
{55519}{55593}Onda Êu ga ja uzeti sam.
{57559}{57617}Sluöaj...
{57630}{57689}Kako se zoveö?
{57744}{57854}Kako ti se zove otac?|Moj se zove Pino.
{57894}{57983}Zove li se i tvoj tata|Pino, kojim sluËajem?
{58173}{58250}Idem ja.|- Kuni...
{58370}{58428}Rekao si neöto?
{58474}{58529}Ne razumijem.
{58577}{58667}Kuni...|- Kuni?
{58689}{58803}Kako to misliö?|- Rakuni.
{58812}{58904}Ostaviö li otvoreni prozor,|uÊi Êe ti rakuni...
{58911}{59017}...i ukrasti kolaËe, kekse...|- Ovdje nema rakuna.
{59064}{59156}Rakuni mogu|ugristi ljude.
{59289}{59370}Jesi li juËer pojeo|komadiÊ mesa?
{59479}{59539}Od velike je vaûnosti.
{59608}{59670}Jesi li ti moj Aneo »uvar?
{59730}{59832}Ja nisam aneo.|äto je Aneo »uvar?
{59902}{59984}Onaj koji govori istinu.
{60010}{60109}Meni moûeö reÊi,|neÊu nikome odati.
{60144}{60240}Nisam aneo.|Zovem se Michele.
{60254}{60315}Michele Amitrano.|Idem u peti razred.
{61139}{61302}Mrtav? - äto kaûeö?|- Jesam li ja mrtav?
{61310}{61428}Mrtav? äto?|- Mrtav sam!
{61443}{61505}Mrtav sam! Mrtav sam!
{61513}{61590}Mrtav sam! Mrtav sam!
{61596}{61691}Mrtav sam! Mrtav sam!
{62156}{62272}SjeÊaö se kad nam je g.|Destani priËao o Lazaru? - Da.
{62304}{62403}Kad se Lazar ustao iz mrtvih,|je li znao da je bio mrtav?
{62409}{62475}Ne, mislim da je|mislio da je bio bolestan.
{62577}{62654}Misliö li da samo Isus|moûe oûiviti mrtve?
{62667}{62760}Ne znam, ali mi je teta|ispriËala istinitu priËu.
{62769}{62866}Jednom je neËiji sin ostao|prignjeËen ispod auta.
{62876}{62926}Njegov tata to nije mogao|podnijeti i cijeli je dan
{62933}{63010}plakao. Dao je nekom|vidovnjaku sav svoj novac
{63017}{63115}da mu oûivi sina. Vidovnjak|mu je rekao: "Idi kuÊi,
{63121}{63180}sin Êe ti se veËeras vratiti."
{63188}{63276}Tata je Ëekao, ali mu se|sin nije vratio,
{63283}{63378}pa je otiöao u krevet. Tada|je zaËuo korake u kuhinji.
{63388}{63511}Ustao se i vidio prignjeËenog|sina kojemu je curio mozak.
{63519}{63603}Sin mu je rekao da ga mrzi jer|je poginuo njegovom krivnjom.
{63618}{63695}Ostavio ga je na ulici|da bi mogao trËati za ûenama.
{63739}{63845}äto je onda bilo? - Otac ga je|polio benzinom i zapalio.
{63861}{63934}Dobro je uËinio.|- Naravno.
{64674}{64771}äto to radiö?|- Moram piökiti, spavaj.
{65000}{65066}äto su ti rekli u Milanu?|- äto bi ûelio da kaûu?
{65093}{65181}Rekli su da Êe uskoro|zavröiti. Proöli su mjeseci!
{65187}{65224}äto se dogaa?|Nije mi jasno.
{65231}{65278}Ni ne treba ti biti jasno.|äto manje razmiöljaö,
{65285}{65328}manje Êeö upropastiti.|Treba vremena.
{65360}{65439}Moûe potrajati pola godine.|- Pola godine?
{65446}{65481}Pola godine, godinu,|koliko god treba.
{65489}{65584}Vraga! - ZaËepi!|Niöta nam ne govore!
{65591}{65672}Niöta ne moraö znati.|Dijete mora ostati skriveno.
{65717}{65861}Sakrij ga i budi miran. VeÊ|si par puta zeznuo stvar.
{65873}{65985}On je najgluplji. Kao öto|sam rekao, nesposobni ste.
{66029}{66124}Opusti se. - Da se opustim?|Ne plaÊaju nam!
{66139}{66210}Rekli su da Carducciju novac|izlazi kroz nos! Sranje!
{66217}{66283}ZaËepi!
{66298}{66366}Najgori si ovdje, jer|razmiöljaö. - Ja? - Da.
{66492}{66619}Vraga si ti struËnjak.|Ti si idiot!
{66695}{66820}Vijesti! - Anna, ugasi|svjetlo. PojaËaj TV.
{66909}{66988}Dobra veËer.|Zaötita ljudskih prava...
{66995}{67056}i strpljenje u pregovorima,|poruËio je Carter u Berlinu.
{67064}{67129}Sutra u Bonnu zapoËinje|sastanak industrijskih zemalja.
{67146}{67244}U Trentu je uzbuna|zbog otrovnog oblaka...
{67250}{67295}Daj meni jednu.
{67303}{67422}NeÊe ni danas to spomenuti.|Nisu ni juËer. - Onda?
{67446}{67502}Niöta ne Ëujem.
{67532}{67575}Evo ga!
{67587}{67676}Potraga se nastavlja kroz|cijelu regiju...
{67684}{67757}za malenim Filippom,|otetim u Milanu.
{67764}{67869}Policija prati nove tragove|koji se Ëine obeÊavajuÊima.
{67879}{67981}Sada Êemo prikazati poruku|Luise Carducci otmiËarima.
{67988}{68080}Kojega vraga sad ona hoÊe?|- Ja sam Filippova majka.
{68102}{68176}ObraÊam se|sinovim otmiËarima.
{68185}{68236}Molim vas,|nemojte ga ozlijediti.
{68244}{68328}Dobar je djeËak, lijepoga|ponaöanja, i veoma srameûljiv.
{68335}{68395}Molim vas,|postupajte blago s njim.
{68415}{68475}Sumu koju ste zatraûili|je previsoka,
{68482}{68543}Ëak i za naöu obitelj.|- Ispljunut Êe novac.
{68621}{68699}Prijetili ste da|Êete mu odrezati uho.
{68706}{68770}Molim vas,|nemojte to uËiniti.
{68778}{68840}éeljela bih vas|zamoliti joö neöto.
{68852}{68968}Recite Filippou da ga mama|i tata vole iz sveg srca,
{68975}{69032}i da misle na njega.|- Odrezat Êemo mu oba uha!
{69039}{69094}Oba!
{69370}{69496}Tko si ti? - Michele.|Michele Amitrano.
{69544}{69604}ZvuËi poput imena|nekog pjevaËa.
{69695}{69806}Ja sam Materia Sergio.|- Drago mi je.
{69896}{70053}Nisu te nauËili da kucaö|prije ulaska? - Oprostite...
{70193}{70245}Ti si Pinov sin?|- Molim?
{70252}{70309}Jesi li Pinov sin? - Da.
{70475}{70597}Tiho si dijete.|To mi se svia.
{70722}{70784}Jesi li i posluöan?
{70827}{70889}Onda zatvori|vrata i goni se.
{70897}{70954}Molim? - Zatvori|vrata i goni se!
{70965}{71003}Mama...
{71019}{71073}Mama...
{71090}{71154}Tko je onaj Ëovjek u|kupaonici? - Pusti me!
{71169}{71247}To je Sergio, tatin prijatelj,|rekao ti je da Êe doÊi.
{71283}{71349}Koliko Êe dugo ostati?|- Par dana.
{71373}{71429}Dodaj mi ostalo rublje.
{71480}{71551}A gdje Êe spavati?|- U krevetu tvoje sestre.
{71573}{71642}A ona? - S nama.
{71649}{71751}Dodaj mi. - A gdje Êu ja|spavati? - U svojoj sobi.
{71807}{71886}Ne ûelim spavati s njim! I|ja ûelim spavati s vama.
{71924}{72024}Ne budi blesav. Prevelik|si, ne staneö s nama u krevet.
{72064}{72112}Smanjit Êu se.|- Dosta je bilo!
{72404}{72459}Doi ovamo.
{72588}{72652}Doi.
{72805}{72892}Ne mogu to viöe izdrûati.
{72962}{73108}Da samo znaö... Nemoj mi|oteûavati stvari, zbog mene...
{73143}{73229}Molim te.|- Nije poöteno.
{73282}{73353}NeÊe dugo trajati.
{74505}{74593}Ne mijenjaö se nikada...
{74601}{74689}Moje si juËer,|moje danas, moja vjeËnost...
{74720}{74863}Nemir.|Moûeö pokuöati sada...
{75034}{75144}Poput vjetra si|koji nosi violine i ruûe.
{75244}{75336}RijeËi, rijeËi, rijeËi...|Sluöaj me.
{75345}{75426}RijeËi, rijeËi, rijeËi...|Molim te.
{75438}{75514}RijeËi, rijeËi, rijeËi...|Kunem se.
{75522}{75670}RijeËi, rijeËi, rijeËi,|samo rijeËi meu nama.
{75935}{75992}K vragu!
{77219}{77280}Ti si Filippo, zar ne?
{77321}{77402}Mama ti poruËuje da te voli|i da joj nedostajeö.
{77412}{77510}Rekla je to juËer na TV-u,|i da se ne brineö.
{77531}{77611}Moja je mama mrtva.|- Molim?
{77621}{77767}To je laû! Mama je mrtva! I|tata, i baka, svi su mrtvi
{77774}{77820}i ûive u jamama!
{77941}{78009}Ima li tvoja mama plavu kosu?
{78156}{78233}Ima li u tvojoj kuÊi|slika broda?
{78267}{78379}To nije brod, veÊ jedrenjak.|- Vidiö?
{78409}{78485}Mama ti je bila na TV-u,|vidjela se slika jedrenjaka.
{78494}{78559}Rekla je da te ona i|tata puno vole.
{78566}{78755}Zaöto onda ne dou po mene?|- Ne znam. - I zaöto sam ovdje?
{78928}{78992}Ne znam.|- Ti niöta ne znaö!
{79014}{79086}Odlazi! - Prestani!|- Ti nisi moj Aneo »uvar!
{79111}{79169}Pusti me!|- Prestani!
{79179}{79227}Prestani!
{79245}{79295}Odlazi!
{79326}{79391}Doöao sam ovdje zbog tebe!|Cijeli sam put preöao
{79397}{79457}zbog tebe, a ti me|izbacujeö. - Odlazi!
{79464}{79528}U redu, odlazim, i|nikada se viöe neÊu vratiti.
{79538}{79621}Bit Êeö sam i oni|Êe ti odsjeÊi uöi!
{79666}{79719}I nisam tvoj Aneo »uvar!
{79819}{79875}»ekaj.|- äto ûeliö?
{79954}{80011}Molim te, ostani.
{80235}{80375}Ali, ako se budeö ponaöao kao|luak, odlazim. -NeÊu, obeÊajem.
{80426}{80516}Zaöto ne otvoriö oËi?|- Doi.
{80895}{80983}Znao sam da Êeö se vratiti,|rakuni su mi rekli.
{80995}{81079}Ne opet rakuni!|Otvori oËi.
{81109}{81201}Ne mogu. - Samo na tren.
{81494}{81613}Malen si. - Imam|samo 10 godina.
{81629}{81741}I ja. U koji razred ideö?|- Peti, a ti?
{81754}{81866}I ja. Isti smo! - Da.
{83292}{83378}äto to radiö?|- Niöta, ona pliva.
{83470}{83569}Tako Êe se utopiti.|- Ionako je potrgana.
{83636}{83749}Gdje su ostali?|- Kraj potoka.
{83810}{83881}Salvatore je pitao za tebe.
{84191}{84248}Michele, doi ovamo!
{84324}{84428}Uzrujao si majku. Kaûe da ne|ûeliö spavati sa Sergiom.
{84465}{84574}äto Êe Sergio pomisliti?|- Briga me.
{84697}{84816}Sergio je tvoj öef?|- äto to govoriö?
{84846}{84924}On donosi odluke?|- Ne, on niöta ne odluËuje.
{84937}{84987}On je samo prijatelj.
{85032}{85166}Nije li ti drago öto sam se|vratio? - Jest. - äto je, onda?
{85268}{85376}éelim otiÊi odavde. - Kako to|misliö? Ne svia ti se ovdje?
{85394}{85502}Svia, ali...|- Idemo obarati ruku.
{85535}{85583}Da vidimo.
{85652}{85746}U Ëemu je problem?|- Ni u Ëemu.
{85799}{85879}Ako budeö dobar,|kad se sve ovo zavröi...
{85886}{85956}OtiÊi Êemo na plaûu.|ObeÊajem ti.
{86340}{86398}Znam da si budan.
{87053}{87164}Ovo je moj dom u Brazilu.|Niöta se ne vidi
{87170}{87229}jer je moj prijatelj Paco|prekrio cijelu sliku.
{87234}{87291}Mrtav je.
{87364}{87454}Ovo je moja supruga,|moja gospoa.
{87640}{87747}Imate ûenu crnkinju?|- Obojenu.
{88134}{88235}Brazil je divna zemlja!
{88259}{88382}éivot je jeftin.|Seviran, divan...
{88430}{88506}Nije poput ove usrane zemlje.
{88518}{88617}Je li Brazil daleko?|- Veoma daleko.
{88764}{88860}Sad spavaj. - äto?|- Spavaj!
{90051}{90140}FILIPPO CARDUCCI JE éIV!
{90650}{90736}Ispekla sam tortu.|- Sa ölagom.
{90766}{90834}Doi, daj mi pusu.
{90928}{90987}Idi jesti.
{91103}{91215}Gdje je tata?|- Vani, sa Sergiom.
{91241}{91331}SljedeÊi nas tjedan|vodi na plaûu.
{91345}{91406}I jesti Êemo|dagnje u restoranu!
{91451}{91489}Michele!
{91522}{91578}To je Salvatore!
{91629}{91701}Hajde...|Odnesi mu komadiÊ.
{91896}{91954}Je li dobra?|- Jest.
{92016}{92078}Pogledaj öto mi je|poslao stric.
{92282}{92355}Lijepi su, zar ne?|- Veoma lijepi.
{92362}{92462}Ovome se mogu|produûiti ljestve.
{92523}{92610}Ovaj ima Ëak i krevet.
{92625}{92687}Ovo je policijski auto.|Otvaraju mu se vrata,
{92693}{92842}i ima sirenu. - Sve ti|je to poklonio? - Da.
{92921}{93028}I ovaj je lijep. - Ne otvaraju|mu se vrata, meni se ne svia.
{93049}{93179}Meni se svia. HoÊeö li mi|ga pokloniti? - Ne mogu,
{93187}{93276}stric Êe se naljutiti. - Ali,|on je u Americi. - Ne mogu.
{93323}{93411}Dat Êu ti stripove o|"Texu" za njega.
{93433}{93494}VeÊ sam ih sve proËitao.
{93553}{93614}HoÊeö li mi ga dati|ako ti odam tajnu?
{93620}{93712}Tajna nije vrijedna kamionËiÊa.|- Ova jest, kunem se.
{93732}{93817}Moraö se zakleti Bogom da|nikome neÊeö reÊi,
{93825}{93868}Ëak ni Lubanji.
{93909}{94024}äto to radite? - Pustite nas!|Doi sa mnom.
{94155}{94212}SjeÊaö se one kuÊe|gdje smo bili?
{94216}{94252}U dvoriötu se nalazi|skrivena jama.
{94266}{94350}Ondje se nalazi djeËak.|éiv je, i lud.
{94358}{94442}äto radi ondje? - Neki|odrasli su ga tamo ostavili.
{94450}{94539}Mama mu je bila na TV-u,|ali ga oni ne ûele vratiti.
{94548}{94685}Zapravo, ûele mu odsjeÊi uho.|- Ne vjerujem ti. - Istina je!
{94692}{94763}Zove se Filippo.|Pokazat Êu ti ga.
{94796}{94904}Ne, predaleko je.|- Ne svia ti se ta tajna?
{94932}{94990}Ne baö.
{95009}{95211}NeÊeö mi dati kamionËiÊ?|- Uzmi, ionako mi se ne svia.
{95354}{95452}Oprali su te!|Tko je to uËinio?
{95461}{95554}Spustili su se dolje i oprali|me. - Skinuli su ti lanac.
{95606}{95687}Vidi öto sam ti donio.|Izmrvila se, ali...
{95837}{95912}Joö!|Daj mi joö!
{95921}{95980}Nemam viöe.|Sve sam ti dao.
{96081}{96142}Ako je ötogod ostalo,|donijet Êu ti sutra.
{96584}{96704}Imam ideju.|éeliö li izaÊi?
{96723}{96776}Kamo? - Van.
{96789}{96869}Gdje? - Van iz rupe.
{96878}{96940}Kakve rupe?|- Ove, gdje smo sad.
{97046}{97125}Ovo nije rupa.|- Nego öto je?
{97160}{97242}Ovdje doeö kada umreö.
{97260}{97369}Kako da ti objasnim? Ovo je|rupa iskopana u zemlji.
{97380}{97445}Vani je zrak, polja, sve...
{97574}{97632}Hajde, idemo.
{97853}{97966}Barem pokuöaj!|- Ne mogu!
{98015}{98154}Ne mogu... - Samo|na tren. - Boli me.
{98169}{98212}Pokuöaj!
{99044}{99150}Tamo dolje je more,|ali se ne vidi.
{99253}{99344}Pogledaj. Svia ti se?
{99596}{99659}Vidi ovo!
{101337}{101392}Sluöaj...
{101400}{101465}Moram sada kuÊi.
{101641}{101703}Vratit Êu te tamo dolje.
{101779}{101875}Moram brzo kuÊi jer|moram postaviti stol.
{101886}{101982}Ja Êu ostati ovdje, ali vratit|Êeö se sutra, zar ne? - HoÊu.
{101989}{102039}ObeÊajeö?|- ObeÊajem.
{102329}{102400}äto je to bilo? - Ja.
{102526}{102652}HoÊeö li mi sutra donijeti|sendviË s namazom od sira?
{102662}{102700}äto...?|- Ku-kuc!
{102707}{102818}Vidim te! Iz gnijezda je|izletila, i viöe se ne glasa!
{103033}{103106}K vragu!|To je bio Michele!
{103113}{103176}Svaki put kada stvari|nisu bile na svome mjestu.
{103216}{103324}éelio si ga osloboditi?|Ustani, glupane!
{103412}{103473}Imaö sreÊe öto si|sin svojega oca.
{103485}{103680}Doista imaö sreÊe.|Ne miËi se. Idemo. Ulazi!
{103760}{103823}Dobri Salvatore,|bio si u pravu.
{103834}{103964}Dao sam ti rijeË. Uzmi|volan i pokaûi mi öto umijeö.
{103971}{104028}Sada?|- Kada inaËe?
{104045}{104113}Prati krivinu|i ne zaboravi koËiti.
{104198}{104263}Ovo je savröeno|mjesto za uËenje.
{104351}{104465}Dobar poËetak. Dobro drûiö|volan. Pravi si profesionalac.
{104500}{104552}Opusti se.
{104616}{104663}Uspori!
{104710}{104765}Kamen!
{104809}{104870}Rupa!
{104887}{104937}Salvatore, gledaj naprijed.
{104969}{105030}Salvatore, stijena!
{105042}{105128}KoËi, razbit Êeö mi auto!
{105694}{105799}äto se dogodilo? - Bio|je ondje, s malim.
{106275}{106376}äto ti se dogodilo?|- Udario me je.
{106496}{106559}äto si mu uËinio?
{106576}{106613}Gade! - Niöta mu|nisam uËinio!
{106620}{106682}Kako se usuujeö udariti|moga sina? Ubit Êu te!
{106706}{106764}Prestani! Htio ga je|osloboditi!
{107127}{107181}Smiri se!
{107310}{107361}Pusti je!
{107371}{107497}Pusti je!|- Makni se!
{107530}{107578}Koji vrag...!
{107599}{107736}äto to radiö? Udario si ga!|- Dosta! Svi se gonite!
{107766}{107828}Anna...|- Odlazi.
{107835}{107887}Hajde! Van!
{107901}{107978}Kojega vraga si radio?|- Niöta! Htjela me je udariti!
{108378}{108437}Nije to niöta.
{108639}{108708}Odmori se sada.
{109223}{109290}Michele, sluöaj.
{109307}{109436}ObeÊaj mi da Êeö, kad narasteö,|napustiti ovo mjesto.
{109498}{109555}Michele!
{109586}{109665}Michele!
{109674}{109753}Probudi se.
{109885}{109942}äto si radio danas?|- Niöta.
{109950}{110031}Vraga. Felice mi je rekao da|si ûelio osloboditi djeËaka.
{110044}{110153}Nisam, kunem se. Izvukao sam|ga van, i vratio opet unutra.
{110160}{110295}Koliko te puta vidio? - Tri.|- Koliko? - »etiri.
{110389}{110448}Bi li te mogao|prepoznati? - äto?
{110453}{110554}Bi li te prepoznao?|- Ne, nije dobro vidio.
{110560}{110612}Uvijek drûi glavu|pod dekom.
{110620}{110743}Razgovarao si s njime?|- Nisam. Malo.
{110773}{110824}äto ti je rekao?|- Niöta.
{110864}{110924}Govori o Ëudnim stvarima.|Teöko ga je razumjeti.
{110929}{110999}äto si ti njemu|rekao? - Niöta.
{111151}{111236}Sluöaj paûljivo.|Ne öalim se.
{111245}{111361}Vratiö li se ondje,|prebit Êu te.
{111426}{111530}Vratiö li se, ubit Êe ga,|i ti Êeö biti kriv!
{111564}{111633}NeÊu se vratiti, kunem se.
{111656}{111759}Moraö reÊi: "Kunem se oËevim|ûivotom da se neÊu vratiti."
{111910}{111988}Kunem se oËevim|ûivotom da se neÊu vratiti.
{112035}{112109}Zaboravi na njega,|on ne postoji.
{112123}{112189}Nikada nikome to|ne spominji viöe.
{112223}{112281}Isuse!|Kakav nered!
{112399}{112503}Mogu li te neöto pitati?|- äto?
{112510}{112567}Zaöto ste ga|zatvorili ondje?
{112704}{112762}Nije mi jasno.
{112908}{113030}Postoje stvari koje ti se|Ëine loöima kada netko...
{113124}{113182}Ne razmiöljaj o tome.
{113201}{113260}Zaboravi na sve to.
{113289}{113345}Idi na spavanje.
{113356}{113414}Spavaj.
{114701}{114793}äto gledaö? - Eno psa.|- Gdje je? - Ondje.
{114995}{115090}Ne vidim ga. - Onda ga|samo ja mogu vidjeti.
{115104}{115198}Mislila sam da i ti moûeö,|ali valjda ne moûeö.
{118285}{118343}Tiöina!
{119744}{119866}äto Êemo sada?|- Vratimo se ondje.
{119874}{119934}Gdje? - U napuötenu kuÊu.
{119942}{119986}Kraj Candeline farme.
{119993}{120066}Daleko je.|äto ako poËne kiöa?
{120074}{120152}äto ako poËne kiöa?|SmoËit Êemo se.
{120168}{120248}Ionako te nitko nije pitao|da poeö s nama.
{120352}{120405}Idemo?
{120411}{120484}Ja idem, pridruûite|mi se, ako ûelite.
{120491}{120563}Ako se neÊemo utrkivati.|- Bez utrke.
{120605}{120734}Ti neÊeö s nama?|- Michele, ideö li?
{121378}{121434}Vratimo se kuÊi.
{121441}{121519}Ako te je strah zbog|par kapi kiöe, idi kuÊi.
{122459}{122515}Sklonimo se!
{123285}{123376}Nema ga.|- Znam gdje je.
{123411}{123473}Gdje? Reci mi!
{123502}{123576}HoÊu, ako Êeö se pomiriti|sa mnom. - Reci mi!
{123628}{123695}Odveli su ga u peÊine|blizu Candeline kuÊe.
{123857}{123950}Tko ti je rekao? - Moj tata je|priËao s tvojim i s onim
{123957}{124007}tipom sa sjevera.
{124107}{124212}HoÊemo se pomiriti?|- HoÊemo.
{125541}{125630}Hej!
{126070}{126131}Nema nikoga kod kuÊe!|- Niti ovdje!
{126138}{126202}Gdje su svi?|- Ima li koga kod tebe?
{126229}{126294}Nema!|- äto Êemo sada?
{126319}{126379}Otiöli su.|- Joö bolje.
{126386}{126451}Nisam mogao|doËekati da svi odu!
{126467}{126512}Maria!
{126596}{126659}Gdje su svi odrasli?|- U Assuntinoj trgovini.
{126665}{126712}äto rade ondje?|- Ne znam.
{126721}{126810}Proöli su helikopteri,|i svi su izaöli.
{126817}{126916}Uöli su u trgovinu, a mama je|rekla da mi ne smijemo unutra.
{127258}{127333}Kad Êe zavröiti?|- Kako da ja to znam?
{127354}{127414}Dosadno mi je.
{127600}{127661}Barbara, öto radiö|ovdje? Idi kuÊi!
{127668}{127731}Kad Êeö ti doÊi?|- Odmah. Idi.
{127737}{127767}K vragu!
{127773}{127840}Kad Êe izaÊi naöa|mama? - Uskoro.
{127910}{127965}Idemo kuÊi.
{127973}{128022}Ali, ne ûelim iÊi spavati.|- Ne moraö.
{128170}{128227}Ima dvije rajËice.
{128510}{128572}Posoli je, boljeg je okusa.
{128777}{128831}Poûuri, kasno je.
{128884}{128939}Zaöto ste joö budni?|Brzo u krevet!
{128945}{129033}Ali, nismo veËerali!|- NeÊete umrijeti.
{129040}{129123}U krevet! - Stigli smo|toËno na vrijeme.
{129424}{129552}Zaöto ne spavate? - Moûeö|li im reÊi da tiöe viËu?
{129601}{129693}Donijela sam vam neöto|za pojesti. - äto se dogaa?
{129769}{129843}Jedi i idi na spavanje.
{130337}{130420}Mama...|- äto je?
{130458}{130532}Mrtav je, zar ne?|- Nitko nije mrtav!
{130543}{130599}Nitko! Jasno?
{130926}{130991}Premlad si.
{131174}{131248}Dosta, jedite sada.
{131452}{131519}U redu je ako|ne ûelite jesti...
{131554}{131616}...ali spavajte.
{131719}{131777}VraÊam se za 10 minuta.|Ne budete li spavali,
{131783}{131828}dobit Êete svoje...
{132166}{132239}Jesi li poludio?|- Tiho!
{132350}{132456}NeÊu to uËiniti! Ne ûelim|u zatvor zbog vas!
{132464}{132602}Uvjeti su bili jasni, ti Êeö|se pobrinuti za maloga.
{132627}{132688}Pou li stvari|po dobru ili zlu...
{132694}{132763}...ti Êeö se pobrinuti za|maloga. - Vratimo ga kuÊi.
{132783}{132853}äto mislite?|To je jedino rjeöenje.
{132889}{132953}Pustimo ga na slobodu.
{132984}{133040}Ostavit Êemo ga negdje|na ulici, i rijeöena stvar.
{133154}{133233}Koji ti je vrag? Nemaö|trunka zdrave pameti!
{133245}{133417}Moramo se rijeöiti maloga!|Budale glupe.
{133429}{133502}A ti, nemaö muda.
{133511}{133635}äto si se ti umislio,|Milanski seronjo!
{133652}{133697}äto to radiö, dovraga?|Jesi li poludio?
{133719}{133780}Zaöto ja to moram uËiniti?
{133945}{134026}Nisi li ti bio onaj "hrabri"?
{134042}{134131}Pederu!|- Govno jedno!
{134270}{134338}Joö jednom|digni ruku na mene!
{134346}{134430}Pokazat Êu ti kako je lako|raznijeti glavu nekome!
{134445}{134533}Daj mi piötolj!|Dosta je tih sranja!
{134604}{134670}äto rade?|- Briöi!
{134733}{134875}Hajde, dotakni me joö|jednom! - Imam ideju.
{134950}{135008}UËinit Êemo ono|öto Ëine u ratu...
{135015}{135085}kad odluËuju tko Êe|na opasne zadatke.
{135094}{135157}Svako od nas|Êe vuÊi öibicu.
{135651}{135717}Kamo ideö?|- Pst!
{136313}{136412}Dlakavi pauËe|i sovo u zraku,
{136421}{136507}ljigavi puûu,|i zmijo slijepa,
{136516}{136605}klonite djece se naöe.
{136618}{136695}NoÊni stvorovi,|tragaËi tame,
{136709}{136794}vi koji spavate,|samo kad sunce sja...
{136810}{136879}Bdijte nad tim djeËakom|u snovima njegovim.
{137046}{137141}Dlakavi pauËe|i sovo u zraku,
{137156}{137233}ljigavi puûu,|i zmijo slijepa,
{137258}{137345}klonite djece se naöe.
{137363}{137441}NoÊni stvorovi,|tragaËi tame,
{137452}{137552}vi koji spavate,|samo kad sunce sja...
{137558}{137634}Bdijte nad tim djeËakom|u snovima njegovim.
{138241}{138334}Sve je otkrio, i Ëudoviöte|ga nije moglo zaustaviti...
{138341}{138395}...jer je imao moÊi.
{138556}{138627}Tko je tamo?|Ima li koga?
{138757}{138831}ZaËepi, nema nikoga!
{140159}{140215}Filippo!
{140757}{140814}Filippo!
{141038}{141109}Filippo, jesi li to ti?
{141132}{141187}Filippo!
{141878}{141933}Filippo!
{141985}{142043}»ekaj, skinut Êu ti to.
{142055}{142114}Jesi li dobro?
{142228}{142331}Hajde, idemo.|Ustani.
{142344}{142454}Ustani, ne mogu sve sam!
{142510}{142622}Zar ne razumijeö? Ako|ostaneö, ubit Êe te!
{142656}{142740}Doöao sam te spasiti!|Ustani, budalo!
{142802}{142866}äto?|- Ne mogu.
{142917}{143018}äto si rekao?|- Ne mogu.
{143090}{143224}Oprosti. - Nema isprike,|moraö iÊi, razumijeö?
{143331}{143447}Hajde, joö malo pa smo|stigli. Hajde, imaö snage...
{143553}{143647}Sad se popni, ja Êu te|pogurnuti, ali moraö se popeti.
{143679}{143765}Hajde, izvrsno ti ide...
{143779}{143808}Hajde!
{143818}{143861}Brzo, dolaze!
{143946}{143984}Hajde!
{144079}{144140}Hajde!
{144443}{144510}Bravo, sada skoËi.
{144575}{144612}Bojim se.
{144620}{144689}SkoËi, dolaze!|Moraö skoËiti!
{145005}{145082}Bravo. Uspio si.
{145116}{145217}Doi, Ëekam te.|- Ne, moraö iÊi.
{145230}{145277}Idi!|Odlazi!
{146915}{146973}Tata!
{147192}{147289}Reci neöto, Michele!|Otvori oËi!
{147327}{147374}Michele!
{147385}{147487}Pogledaj me, ne boj se.
{147525}{147592}Otvori oËi!|Otvori oËi, Michele!
{147600}{147666}Pogledaj me, ne boj se.
{147690}{147755}Pino!|Pobjegao je!
{147779}{147826}Reci mi neöto, Michele.
{147858}{147894}Hej...
{147904}{147980}Oprosti.|Nisam znao da si to ti.
{147998}{148061}Nisam znao da si to ti.
{148068}{148160}Pino, ne mogu ga pronaÊi!|Pobjegao je!
{148214}{148287}Ne brini se za njega,|dobro je.
{148295}{148347}Mali je pobjegao!
{148354}{148410}Moraö ga ubiti!
{148779}{148863}Pogodili ste njega,|umjesto mene.
{148892}{148949}Dobar deËko.
{149098}{149184}Drago mi je öto si|se vratio. Doi.
{149229}{149278}Doi.
{149298}{149359}Dobar deËko.
{149366}{150166}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
{151456}{151543}NIJE ME STRAH
{151683}{151752}Scenarij:
{151771}{151835}Reûija:
{151925}{152009}SVRäETAK
{152034}{153534}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
