{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{1416}{1544}MISTI»NA REKA
{1950}{1990}Znaö, bavio sam se sportom.
{2016}{2064}Kada se to deöava?|-7:30.
{2081}{2159}Ko baca veËeras?
{2287}{2340}»ovek je opak. Dobro baca.
{2435}{2500}Lopta mu ide brzinom od 92 milje na Ëaas.
{2720}{2762}Dva puta izlazi na bazu.
{3668}{3742}Izvinite momci. Izgleda sam ojaËao.
{3781}{3849}Znaöö öta, Dejv? Mora da je to u pitanju.
{4140}{4179}äta?|Znate öta bi bilo kul?
{4205}{4276}Da vozimo kola.
{4309}{4345}Samo oko bloka.
{4413}{4467}Da li neko iz ulice drûi kljuËeve u kolima?
{4520}{4550}Da ukrademo kola?
{4567}{4603}Tata bi me ubio!
{4645}{4689}Samo da se provozamo oko bloka|ko priËa o krai?
{5111}{5189}Tata bi te ubio i da napiöeöe ime.
{5735}{5780}Vidiö. Zauvek Êe biti tu.
{5854}{5889}I ja Êu.
{5970}{6002}Zauvek.
{6127}{6169}Mogu li da vas pitam neöto?
{6326}{6386}Da li vi momci mislite da je u redu|da uniötavate opötinsku imovinu?
{6522}{6558}Doite ovamo.
{6641}{6694}Dolazite ovamo!
{7077}{7205}äta kaûete?|-Ne, g-dine.-Ne, g-dine.-Ne.
{7244}{7280}Ne, öta?
{7342}{7437}Gospodine.|-Ti si opasan Ëlan grupe?
{7556}{7600}Gomila propalica.
{7710}{7761}Da li ûiviö u blizini?
{7785}{7823}Ovde.
{7969}{8040}A ti?|-Tamo.
{8152}{8191}A ti? Gde ti ûiviö, sinko?
{8268}{8307}Preko puta.
{8319}{8358}Da li ti je majka kod kuÊe?
{8554}{8652}Idem da porazgovaram sa njom.|Da joj kaûem kakva je propalica njen sin.
{8916}{8960}Ulazi!
{9046}{9115}Ulazi unutra, jebote!
{9590}{9674}Unutra!
{9762}{9843}Vi klinci idite i recite majkama|öta ste uradili.
{10024}{10107}I ne dozvolite da vas opet uhvatim |kako uniötavate moj trotoar.
{10965}{11034}Kako to misliö da je neko stavio Dejva u kola?|Ko je stavio Dejva u kola?
{11043}{11140}Pandur. Imao je zlatnu znaËku.-Kako znaö|da je pandur? Samo zato öto je imao|zlatnu znaËku?
{11147}{11233}Da li si video neöto na znaËki?|Ne.-Ne. 
{11236}{11298}Da li je imao uniformu? Kao öto policija ima?
{11319}{11382}Bio je pandur.
{11382}{11447}äta ste vi radili kada su oni doöli?
{11462}{11595}Pisali smo imena.|-Samo ste pisali imena, ali su oni odveli Dejva.
{11613}{11664}-Da. |To zaista nema smisla. Idemo.
{12287}{12323}Molim Vas.
{12347}{12400}Nemojte viöe. Nemojte.
{12539}{12572}Molim Vas.
{13431}{13499}Da li ste ga videli?Deluje kao oöteÊena roba.
{14601}{14720}Bilo je dobrih udaraca danas.|-Tata, ispao sam.
{14741}{14777}Ali su udarci bili dobri.
{14782}{14815}To je vaûno.
{14872}{14919}Nikada neÊu biti dobar igraË.
{14970}{15192}Hej, ti si moj sin. Ja sam igrao u |gimnaziji od 1978-82.
{15240}{15276}BiÊeö odliËan igraË.
{15394}{15522}Vidiö li ono tamo? -Da.
{15555}{15730}Ovde sam se kao mali igrao.|Onaj öaht je progutao sve lopte koje |smo imali.
{15759}{15828}Lopte za bejzbol, uliËni hokej, fudbal.
{15876}{16003}Da moûemo da dignemo poklopac sa öahta|naöli bi tamo hiljadu lopti.
{16021}{16086}Stvarno? Hajde da pokuöamo?
{16921}{16983}Ulazi uniutra!
{17004}{17070}Hajde tata. Pomozi mi da naem lopte.
{17090}{17209}Moûda sutra. Hajdemo kuÊi pre nego mama|poËne da se brine.
{17595}{17788}Dûemi, Dûemi hoÊeö li da naruËiöä|-Ne ûelim niöta.
{17800}{17961}Rouz, nestalo nam je Malbora. |Vinston je u redu.
{17987}{18156}To znaËi manju zaradi i moram da dignem|cene. -äto ne naruËiö joö?
{18175}{18246}HoÊu, ali ako zovu iz Zdravstvenog centra|ti si moj alibi.
{18676}{18736}Hej ti. -Hej.
{18766}{18843}Izlazim veËeras sa Ivom i Dajanom u 7:30.
{18870}{18937}Nemoj dugo da ostaneö. Sutra je |tvojoj sestri prva priËest.
{19009}{19110}Boûe, zvuËim kao ...-NeËiji otac?|-NeËiji ali ne moj.
{19240}{19285}Vidimo se kasnije, tata.|-Kasnije.
{19318}{19354}Lepo se provedi.
{19505}{19588}Vidimo se kasnije. -Kasnije.
{20348}{20467}Brendone? Na smrt si me preplaöio!
{20485}{20557}Izvini. Nisam hteo da me tvoj otac vidi.
{20580}{20622}Zato si mi se uöunjao u kola?
{20651}{20690}Nedostajao si mi.
{20788}{20827}Uradio sam to samo zbog poljupca.
{20866}{20925}Samo zato? U redu onda.
{21094}{21174}Proölo je veÊ 6 sati. Morao sam da te vidim.
{21287}{21332}ZakasniÊu na sastanak sa Ivom i Dajanom.
{21415}{21498}Sutra? Kao öto smo planirali?
{21575}{21614}Sutra?
{21747}{21780}Ostavi me iza ugla.
{22760}{22843}On me je presekao! Presekao mi je put!
{22876}{22957}Stalno mi je presecao put!
{22960}{23013}Pratio me je celim putem od Linfilda!
{23016}{23055}Pokuöavao je da me ubije!
{23061}{23105}Taj kuËkin sin!
{23128}{23176}Moûeö li da poverujeö koliko se ovaj tip buni?
{23212}{23298}Ne znam, moûda bi trebalo da uzmemo advokata.
{23396}{23432}Sjajno!
{23577}{23631}äta gledaö?|-Stari  kraj.
{23764}{23880}Mogu da ostanem ako sam Vam potrebna.|- Ne treba, u redu je.
{23892}{23987}Nekoliko nas izlazi posle. 
{24088}{24180}Ne, mislim da neÊu. Hvala Dûen.|Hvala u svakom sluËaju.
{24278}{24317}Koliko ima kako te je ûena ostavila?
{24358}{24382}Pa öta?
{24409}{24561}Pa Dûeni ima dobro telo, dobar glas|i lisice. Naterala bi i gej tipa da se predomisli.
{24578}{24721}Pa öta si time hteo da kaûeö?|- Devojka samo hoÊe da spava sa tobom,|ne ûeli da se uda za tebe. Nisi ni trepnuo.
{24739}{24804}éeli da bude u hramu boûanstvenog äona. 
{24816}{24846}Ja sam oûenjen.
{24861}{24902}Bio je i Bil Klinton ali ga to nije spreËilo.
{24920}{24979}Osim toga, sa Lorom nisi razgovarao|veÊ 6 meseci.
{24988}{25012}Stalno se javlja.
{25054}{25113}I niöta ne kaûe. To je baö uvrnuto.
{25131}{25247}Za neki dan Êe se javiti i reÊi mi zaöto je otiöla.
{25265}{25306}Moûda Ëeka da ti neöto kaûeö?
{25915}{25974}Hajde, hajde, hajde!
{26129}{26191}»ini se da Êe izgubiti ovu utakmicu.
{27186}{27230}Pogledaj kakve su ove ûenske?
{27489}{27587}Vidi im se sve ispod suknje!
{27697}{27730}Da!
{27795}{27846}One su samo devojËice.
{28493}{28680}Dejv! Tri sata ujutru je. Gde si do sada?
{28766}{28802}O Boûe!
{28859}{28900}Zajebao sam stvar!
{28912}{29075}äta se desilo? -Neki tip je pokuöao da me|opljaËka, i poseko me je noûem...
{29114}{29200}Pogledaj ruke! Moramo da idemo u bolnicu!
{29221}{29358}Ne, ne nije tako straöno! Nije puno duboko samo|jako boli!
{29372}{29458}Ne moramo u bolnicu!|Pobogu, Dejv. Doi .
{29580}{29690}Iöao sam do kola, kada mi je priöao taj|tip i pitao me da li imam upaljaË.
{29726}{29868}Rekao sam da ne puöim. On je rekao da ni on|ne puöi. Onda je srce poËelo jako da mi udara.
{29877}{29981}Zato öto u blizini nema nikoga sem nas.
{30017}{30091}Tada sam video noû. Tvoj novËanik ili ûivot.|Sa jednim od ta dva ja odlazim odavde.
{30097}{30236}To je rekao?|-Pokuöao sam da proem pored njega. Tada me|je zakaËio noûem.
{30246}{30373}Mislila sam da si hrabriji. |-Zaöto mi ne dozvoliö da zavröim.
{30409}{30483}éao mi je Dejv.
{30590}{30668}On je prokleti ludak, duöo.
{30756}{30813}Odlepio sam.
{30831}{30872}Parkiraliöte je bilo prazno.
{30902}{30941}Svuda je bilo krvi.
{31080}{31104}Ubio sam ga.
{31178}{31202}Ubio si ga?
{31475}{31603}Nikada ranije nisam nekoga povredio.
{31654}{31755}Da, ali morao si , zar ne.
{31811}{31897}Bilo je ili on ili ja.
{32144}{32369}O.K. Idi se istuöiraj.  A ja Êu se postarati |za tvoju garderobu.
{32441}{32542}Stvarno?- Stvarno.
{32922}{33005}92 policija. Radi Ëega zovete?
{33031}{33171}Jedna kola su ovde i vrata su otvorena...|-Gde se nalazite?
{33201}{33359}Ulica Sidni. Kod Pen parka. Tu sam sa prijateljem.|-Sinko, kako se zoveö?
{33367}{33462}éeli da zna ime!|-Tvoje ime. Kako se zoveö?
{33486}{33563}Briöemo odavde! SreÊno, ËoveËe.
{33914}{34015}Centrala. Ovde jedinica 33. TrebaÊe nam kriminolozi.  
{34050}{34113}Moûda bi trebalo da obavestite odeljenje za ubistva.
{34133}{34178}Jedinica 33, da li ste naöli telo?
{34199}{34323}Ne ali po svemu sudeÊi, naÊi Êemo|ga uskoro.
{34743}{34841}Da? -Ja sam u radnji i treba mi pomoÊ.
{34867}{34957}Da li si ti normalan da me zoveö ovako rano?
{34983}{35061}Morao sam! -SaËekaj malo.
{35366}{35482}BiÊu tamo za 10 minuta. Pozovi |Sala i postaraj se da doe tamo.
{35506}{35589}Ona zna da ne mora da radi ali mora|da ide u  crkvu. 
{35661}{35722}Ona Êe sve da zabrlja!
{35759}{35806}äta je to pa zabrljala u poslednje vreme?
{35841}{35886}Nemoj da zaboraviö da imaö joö 2 Êerke.
{35916}{35978}BiÊu u crkvi pre svih, ne brini.
{36338}{36397}Da li se neko pojavio?
{36412}{36477}Ne. -Nije se ni javio?
{36516}{36561}Ne.
{36890}{36967}Dûo. Ja sam Dûemi. Izvini öto sam te probudio.|Traûim Kejti.
{37015}{37077}Da, mislim da je ovde. SaËekaj da proverim.
{37250}{37288}éelim Vam prijatan dan!
{37291}{37360}Dajanina sestra je prespavala ovde, |ali ne i Kejti.
{37374}{37458}Ostavili su je oko 1 ali nije rekla |gde ide.
{37493}{37662}Ne brini. PronaÊi Êu je.|-Da li se viala sa nekim?
{37662}{37727}Ko moûe da vodi raËuna o 19-ogodiönjoj devojci.|-Razumem te.|-»ujemo se kasnije.
{37998}{38096}Hokej utakmica je gotova. |Idem da ispuöim jednu na brzaka.
{38126}{38167}Puno puöiö.
{38548}{38598}Mogu li da vam pomognem?
{38634}{38761}Ne, hvala. Samo traûim Ëaj.|-U drugoj gondoli je.
{38776}{38814}Hvala.
{39239}{39287}Kada Sal stiûe? VeÊ mu je vreme.
{39314}{39391}Novine? -Gloub.
{39448}{39575}Mislio sam da Kejti radi nedeljom.|-Da li si se ti to zaljubio?
{39638}{39694}Ne, samo je ponekad viam.
{39709}{39759}Mojoj maloj je danas prva priËest.
{39831}{39896}Hvala. |Hajde, Rej.
{40276}{40318}Mogu li neöto da te pitam, Dûimi?
{40356}{40472} Moûeö. Zaöto toliko mrziö tog deËka?
{40505}{40594}Ne mrzim ga. Ali zar te on ne|plaöi ponekad?
{40626}{40802}Ne. On je dobar deËko. Sa bratom|je i ako ne mora da bude.
{40829}{41046}Ne ûeli da se oseÊa usamljeno. Ali|ti Dûimi si samo na dva koraka od toga|da mu odseËeö nos i nateraö ga da ga pojede.
{41078}{41149}Ne. Stvarno?|-Baö tako.
{41274}{41337}Evo Sala. I bilo je krajnje vreme.
{41764}{41815}Gde si smradu L.A.?|-Taj sam.
{41851}{41966}Takve stvari se deöavaju, samo u gradu, tako...
{42002}{42067}Telo je unutra.
{42148}{42260}Do sada nije pronaeno puno dokaza.
{42275}{42385}Viri mu noû iz kljuËne kosti...
{42412}{42525}Gde ta kuËka drûi noûeve?|-Da li mu je rekla?
{42619}{42703}Naöli smo registracioni list. Vlasnik je |Ketrin Markham.
{42750}{42834}Da li je znaö?-Moûda je to Êerka|tipa koga poznajem.
{42857}{42961}Naöli smo novËanik i dozvolu u rancu|na podu. Ima 19 godina.
{42979}{43062}Sranje. To je ona.|-Da li je to problem? Jesi li blizak sa|tim tipom?
{43086}{43175}Kada smo bili deca, sada se samo viamo|u kraju.
{43273}{43362}Jebiga, samo 19 godina!
{43392}{43448}BiÊe mu straöno.
{44247}{44316}Nemoj da je zasmejavaö.
{44565}{44753}Ovako smo naöli kola. Bilo je krvi |na vratima kod vozaËa,  na zvuËniku, |joö krvi na volanu...
{44773}{44836}...u visini ramena.
{44898}{44996}On  je stajao pored kola, devojka|ga udara vratima...
{45055}{45198}on se okreÊe, pogaa je u rame,|ona pokuöava da pobegne...
{45284}{45343}äta misliö?|-Moûda si u pravu.
{46154}{46226}Neöto sam naöao. Ovde je bila|na kratko.
{46241}{46353}Pojavio se ubica, ona beûi |na drugu stranu.
{46395}{46463}Bolje da pozovemo ronioce.
{47191}{47271}äta, znaËi niste se dugo videli ili öta...?|-
{47295}{47390}Nisam ga video od kad smo bili deca. |Ne kreÊemo se po istim mestima.
{47512}{47556}Tata, tata.
{47601}{47726}Bilo je divno, duöo!
{48394}{48427}Dobro jutro Fej.
{48474}{48560}Nema niöta o njoj. Tri puta sam proverila.
{48596}{48652}Bilo je kasno, jako kasno.
{48742}{48807}Dobro jutro Majk.|-Dobro jutro tata.
{48839}{48919}HoÊemo li da igramo fudbal?|-Da, hajdemo.
{49131}{49202}Obuci jaknu, Majk.
{49594}{49639}Hej Dûemi.|-äta se deöava?
{49662}{49737}Cela ulica je blokirana.|Sve do Pen Parka.
{49751}{49811}Neko je rekao da ga je video |kako tuda prolazi.
{49921}{49998}äta ti radiö ovde?|-Ovde sam zbog crkve.
{50366}{50414}To su kola moje Êerke.
{50524}{50592}To su kola moje Êerke.
{50663}{50791}Psi su neöto nanjuöili tamo dole. HoÊeö|da odemo dole da pogledamo?|-Da, hajde da pogledamo.
{50833}{50940}Da, Ëujem.-Ovde imamo Ëoveka koji kaûe|da je devojËin otac.
{50993}{51035}Sranje. Da li je stigao psiholog?
{51044}{51142}Stiûe. Neka bude miran dok |ne stigne. Znaö proceduru.
{51165}{51293}Njen otac hoÊe sa tobom da razgovara.|Kaûe da te zna. Ne prihvata ne kao |odgovor. Sa njime su neki momci...
{51322}{51382}Kakvi momci?|-Izgledaju ko ludaci!
{51427}{51525}BraÊa Sevidû.|-äta kaûeö, samo ste se viali u prolazu.
{51560}{51620}U redu, stiûem.
{51733}{51806}Hej, polako.
{51813}{51946}Jebi se! Pusti me da proem!
{51967}{52018} Polako, momci.
{52056}{52154}Nik, idi kod Pita i razgovara sa njegovom|Êerkom i njenom drugaricom.
{52202}{52252}Kejti je bila sinoÊ sa njima.
{52273}{52327}Hej, momci. 
{52335}{52443}Ne budi grub ali saznaj neke odgovore.
{52748}{52790}Hej Dûem. Hej ËoveËe.
{52826}{52900}Da li je ona unutra, äone?|-Nisam siguran. Za sada joö istraûujemo.
{52908}{53001}Ne budi izdrkan i pusti nas da pogledamo|unutra.- To su kola moje Êerke.
{53090}{53179}Svuda unaokolo su psi! Zaöto su psi|ovde?
{53202}{53238}Traûim moju Êerku, äon.
{53245}{53343}I mi je traûimo. Za sada se samo vodi|kao nestala.
{53429}{53648}Reci ponovo.-Izgleda da su je naöli.|-Gde?- Pored starog kaveza za medvede.|-Pravi je haos!
{53693}{53752}Postaraj se da ne proe.
{53800}{53906}∆ini mi se da se neöto deöava.|-Ja Êu se postarati da proemo.
{54139}{54245}Velika je potera za mladom ûenom|koja je nestala u Bakingem Fletsu.
{54266}{54379}Sve öto do sada znamo je se neöto |Ëudno deöava, naena su napuötena|kola kod...
{54391}{54548}...Pen Parka.Policija je brzo stigla|na lice mesta i zatvorila ceo kraj.
{54560}{54652}Ali i sada dok razgovaramo, skuplja se |velika gomila radoznalaca...
{54655}{54753}To je sve öto smo do sad saznali ali|Êemo Vas i dalje obaveötavati.
{54771}{54857}Do skorog sluöanja. Ja sam Dûim Smit |za WB 56.
{55466}{55511}Nikada nisam video niöta sliËno ovome.
{55567}{55605}äta imamo?
{55906}{55944}O, Isuse!
{56666}{56729}Da. Ona je.
{56743}{56806}Kasnije Êemo napraviti identifikaciju.
{56833}{56948}Pogledaj joj rane na glavi! Kao|da je udarana nekom batinom.
{56963}{57032}Ali to je nije ubilo. Upucana je.
{57058}{57109}LiËi na .38.
{57159}{57210}äta Êu mu kog avola reËi?
{57234}{57343}Hej, Dûem. Bog je ostavio znak.
{57346}{57429}Doöao je da naplati.
{57528}{57581}Alo! Stani!
{57655}{57703}Vrati se ovamo!
{58086}{58148}Da li je moja Êerka u toj rupi?
{58297}{58344}Hej polako.
{58368}{58478}Da li je moja Êerka tu?|Pustite me!
{58633}{58790}Da li je tu moja Êerka?
{60623}{60842}Niko ti niöta nije rekao, zar ne?|-Ne. - Nisi je video, moûda to nije ona.
{60887}{60970}Dûemi, Dûemi molim te.
{61009}{61080}To je moja Êerka.
{62301}{62514}To je ona. To je Kejti. To je moja Êerka.
{63138}{63186}Sveûe mlevena kafa.
{63213}{63373}Moramo da uskladimo vreme, da bi|mogli laköe da reöimo sluËaj.
{63379}{63441}To moramo da uradimo odmah, da|ne bi zaboravili neöto za 1-2 dana.
{63504}{63611}Da li ikada razmiöljaö o tome koje su|stvari uticale na naö ûivot?
{63655}{63717}Majka je htela da abortira.
{63744}{63795}Ali se predomislila.
{63869}{63958}O Ëemu priËaö , Dûemi?
{64038}{64217}Ti i ja se nikad nismo razumeli.
{64229}{64347}Da je bilo drugaËije, i moj ûivot|bi otiöao drugim tokom.
{64400}{64460}Moja prva ûena, Marita, Kejtina majka,
{64514}{64561}bila je divna ûena.
{64603}{64650}Kraljevske lepote.
{64697}{64748}I znala je to.
{64766}{64826}Niko nije smeo da joj prie.|Ali ja jesam.
{64846}{64947}Imala je 18 godina kada je bila |trudna sa Kejti.
{64998}{65179}Da sam ja morao da uem u ta kola,|ja bih sigurno poludeo i ne bi imao |hrabrosti da joj priem.
{65238}{65307}I Kejti ne bi bila roena.
{65331}{65408}I ne bi bila ubijena.
{65571}{65686}Da li si viao Dejva?|- On se oûenio Fosterovom Êerkom.
{65814}{65913}Kada se Kejti vratila sa posla juËe?
{65939}{66037}U vreme veËere.|-Da li je izgledala neobiËno?
{66076}{66236}Ne...Bila je samnom i sa drugaricama.
{66254}{66352}VeËerali smo. 
{66456}{66507}Sa Iv i Dajen?
{66518}{66691}Da. Razgovarala je sa Lidijom o priËestu.
{66700}{66851}Do otprilike 8 je bila u sobi |i telefonirala, a posle je otiöla.
{66851}{66908}Da li znate sa kim je razgovarala?|-Ne.
{66943}{67038}Nadam se da se neÊete ljutiti |da uzmemo listing od PTT-a?
{67065}{67246}Samo napred.- Gospodine Markam, |rekli ste da ste veÊi deo dana u subotu|proveli u radnji sa Êerkom?
{67246}{67327}Da li je to taËno?- Da, bio sam uglavnom|pozadi.
{67347}{67433}Da li se desilo neöto neobiËno, |sukob sa muöterijom, bilo öta?
{67454}{67516}Bila je kao i obiËno, sreÊna.
{67710}{67775}»ak i najmanja stvar moûe da pomogne.
{67820}{68001}Samostalna je od malena.Od kada joj|je majka umrla i ja sam izaöao iz zatvora.|Umela je sama da se stara o sebi.
{68039}{68221}Kada bi noÊu plakala, nisam znao...
{68232}{68339}Ponekad  me je gledala tako kao |da me priprema na to da je nikada |viöe neÊu videti. 
{68348}{68389}Isto tako me je gledala i u subotu.
{68395}{68499}To je informacija.
{68524}{68645}PrikupiÊemo ih sve. Sklopiti zajedno, |i pokuöati da sklopimo sliku.
{68660}{68695}Kaûete da ste bili u zatvoru?
{68708}{68761}Zar moramo o tome?|Samo sam pitao.
{68788}{68889}Pre 16 godina sam sluûio kaznu |zbog pljaËke.
{68910}{68999}Da li Êe Vam to pomoÊi da pronaete|ubicu moje Êerke? Samo sam pitao.
{69126}{69219}Izvinite. Sve je u redu.
{69278}{69367}O.K. Dûemi... 
{69373}{69501}Da li je postojalo joö neöto osim |pogleda koji ti je Kejti uputila?
{69741}{69857}Ne, to mi je jutros palo na pamet.
{69857}{69923}Hajde, probaj da se setiö nekih sitnica.
{69946}{70077}DeËko iz komöiluka je doöao da je vidi.|Kao da je oËekivao da Êe je videti.
{70085}{70199}Da li su se zabavljali? -Ne.|Zaöto si tako siguran?
{70205}{70282}Veruj mi. Otac zna.
{70288}{70368}G-o Markam, da li se Kejti viala sa nekim?
{70383}{70457}Ne, nije, koliko ja znam.
{70534}{70659}DaÊu Vam sve podatke koji su Vam|potrebni. Ali sada moramo da idemo|kuÊi, Ëekaju nas dve devojËice.
{70724}{70796}Neko Êe Vas odvesti do kuÊe.
{70900}{70992}Ako se setite neËega, bilo Ëega, |molim Vas da nam se javite.
{71227}{71292}Kaûe da je umalo on uöao u auto kada ste|bili deca. 
{71298}{71476}Nas trojica smo bili ispred moje kuÊe|kada su se pojavila kola i uzeli su Dejva.
{71487}{71541}Ko je to bio?|-Predstavili su se kao policija.
{71547}{71666}Drûali su ga 4 dana i 4 noÊi sve dok |nije uspeo da pobegne.
{71693}{71874}Da li su ih uhvatili?|-Jedan je umro a drugog su uhvatili|godinu dana kasnije.
{71877}{71996}Onog momenta kada sam ugledao |Dûemija Markhama, znao sam |da je bio u zatvoru.
{72023}{72135}Zatvorenici nikada ne izgube taj pogled.|-Moûda on ima taj pogled zato öto je upravo|izgubio Êerku.
{72141}{72266}Ne, to mu je u stomaku.Tenzija u ramenima|je od zatvora.
{72424}{72545}Uzrok smrti je najverovatnije prostrelna|rana od vatrenog oruûja u potiljak a |ne od povreda nanetim batinom.
{72566}{72617}äta ima joö?
{72623}{72807}Intervjuisali smo sve koji su moûda|razgovarali ili se videli sa njim.
{72816}{72952}Joö neöto. U rancu naenom u kolima je|bio spisak hotela u Las Vegasu.
{72964}{73023}Ne izgleda bog zna kako.
{73029}{73083}äta ti misliö Divajn?
{73145}{73202}UhvatiÊemo mi njega, g-dine.
{73243}{73306}U redu! Hajdemo na posao!
{73463}{73552}Da li moûda imaö öemu?|-Moûda i imam.
{73641}{73686}äon je.
{73903}{73985}Kao da je velika guûva na Menhetnu.
{74054}{74096}Da li je i on sa tobom?
{74298}{74351}Da li je to sve, duöo?
{74405}{74470}Zaboga, Lora, bar mi reci svoje ime.
{74758}{74803}Bilo mi je drago öto smo se Ëuli.
{75759}{75842}»ula sam da su kola udarila u neöto?|-äta joö jedna kola?
{75863}{75914}Ne, ne sada.
{75917}{76092}To je bilo na krivini?|-Kola su tamo malo stajala a onda|sam Ëula "∆ao".
{76101}{76175}Neko je rekao "∆ao"?
{76196}{76255}Onda se zaËulo kao da je neöto puklo?|-Kao pucanj, moûda?- Da. moûda.
{76383}{76665}Da li ste gledali kroz prozor, g-o?|-Do tada sam veÊ bila u spavaÊici, a ja|ne gledam kroz prozor u spavaÊici.
{76674}{76745}A glas koji ste Ëuli, da li je bio muöki ili ûenski?
{76766}{76864}éenski, mislim.
{76908}{76973}ZvuËi kao da je devojka poznavala ubicu.
{76997}{77051}Izvinite na uznemiravanju.
{77304}{77396}Hej, Dûemi. Kako je moja Êerka?
{77995}{78061}Kako podnosiö sve ovo za sada?
{78075}{78209}Stvarno sam oËajan.|-Tek Êe da  boli.
{78233}{78399}Kada je moja Dûejni umrla, 6 meseci |mi je bilo loöe.Meni su deca tada bila velika,
{78408}{78548}ali ti nemaö taj luksuz, moraö da se |brineö o domaÊinstvu
{78634}{78830}moraö da vodiö raËuna o mojoj |Êerci i o one dve male devojËice. |To ti je prvi prioritet.
{78886}{78984}Ako si neöto zaboravio...|-Morao sam to da kaûem.
{79053}{79291}PrebrodiÊeö ti to , jer si Ëovek.|Ti si Ëovek starog kova.
{79317}{79474}Stavili su je u vreÊu.-äta si rekao?|-Tako je Kejti izgledala kada sa je video|u mrtvaËnici.
{79496}{79575}Kao da su je stavili u vreÊu i posle |udarali po njoj cevima.
{79650}{79796}Dûejni je umrla u snu. Zaspala je i |nije se probudila. Mirno je otiöla.
{79828}{79947}Ne moraö da tako razgovaraö o Dûini.|-Moja Êerka je ubijena.
{79953}{80105}Neko joj je prislonio piötolj. I dok |mi ovde razgovaramo, ona je na |obdukciji, 
{80111}{80253}seckaju skalpelom a ti mi ovde priËaö|o odgovornosti?
{80386}{80434}Drago mi je da smo se videli, Teo.
{80571}{80636}Samo im reci ono öto ih zanima.
{80675}{80764}Sa kim se viala?|-VeÊ sam rekla braÊi Sevidû. 
{80770}{80874}BraÊi Sevidû?|-Da, bili su juËe ovde.
{80916}{80987}Pokuöaj da kaûeö isto i nama. Sa|kim se viala?- Ni sakim posebno.
{81120}{81203}Vi ste imale oproötajnu veËeru, zar ne?
{81245}{81343}äta?|-Ona je odlazila iz grada, iöla je u Vegas?
{81373}{81518}Otkud Vi to znate?|-Ugasila je bankovni raËun, imala je spisak |hotela, 
{81584}{81673}éelela je da ode odavde ipoËne |novi ûivot.
{81690}{81771}19-ogodiönja devojka ne ide u Las Vegas sama,
{81810}{81871}Sa kim je iöla?
{81878}{81911}Hajde, devojke.
{81931}{82000}Sa kim je trebalo da ide?
{82032}{82089}Brendan.-Molim?-Brendan.
{82175}{82228}Brendan Heris?
{82246}{82371}Da, Brendan Heris.|-Imate li njegovu adresu?
{82929}{83042}Hej Dûemi. Izvini, ja ...
{83045}{83107}Izaöao sam da popuöim cigaretu.
{83119}{83178}Sedi.
{83369}{83416}Ceo dan nisam imao prilike da porazgovaram|sa tobom.
{83476}{83600}Kako si?
{83642}{83707}äta ti se desilo sa rukom?|-Ovo?
{83817}{83898}Pomagao sam prijatelju oko selidbe|i povredio sam ruku na vratima.
{83957}{84034}Uvek si uspevao da se povrediö, zar ne?
{84106}{84165}Drago mi je da te vidim.|-Da.
{84391}{84504}Kako se devojke drûe?|-Valjda su dobro.
{84527}{84614}To je to, sada je u boûjim rukama.
{84967}{85053}Lepo je sedeti ovde, zar ne?
{85335}{85499}Nisam mogao da nateram sebe da traûim|mesto u friûideru za svu tu hranu, koju |Êu sutra i onako baciti.
{85549}{85597}Kakva öteta.-Da
{85677}{85775}Ne mogu da izdrûim pritisak koji me |Ëeka u narednih par dana.
{85900}{85979}Svi koji je se seÊaju dolaze.
{86131}{86232}O Kejti se moûe reÊi, da Ëak i kad |je bila mala, 
{86238}{86333}bila je uredna.
{86431}{86698}Kada sam bio u zatvoru, nako öto je |Rita umrla, seÊam se da sam se viöe |plaöio moje male Êerke...
{87141}{87197}Voleo sam je. Najviöe.
{87397}{87459}Kada bi smo sedeli u kuhinji noÊu,
{87565}{87658}bilo je kao da smo poslednji ljudi na zemlji.
{87684}{87786}Zaboravljeni, neûeljeni...
{87886}{88008}I to stvarno poËinje da nervira
{88047}{88121}moja mala Êerka i ja ne mogu da se|isplaËem zbog nje.
{88273}{88314}Dûemi?
{88445}{88508}Sada plaËeö.
{88606}{88644}Da.
{88813}{88897}Srce mi je slomljeno.
{89004}{89143}Imala je samo 19 godina.
{89324}{89381}éeliö li da te ostavim samog?
{89410}{89479}U redu je ako ostaneö joö malo.
{89529}{89594}Da, svakako da je u redu.
{90114}{90167}Kada si poslednji put video Kejti Markham?
{90207}{90296}Ne mislite valjda da bih je ja povredio?|-Nije povreena, ona je mrtva.
{90405}{90492}Nisam je ja ubio.|-I ponovo, kada si je poslednji put video?
{90533}{90631}Sajmon i ja oko 8 sati.
{90655}{90723}Otprilike oko 8 ili u 8, Brendone?
{90756}{90830}Bilo je oko 8. 
{90830}{90967}Pojeo sam nekoliko parËiÊa pice a|ona je ûurila da se nae sa Iv i Dajanom.
{90994}{91061}Zaöto se ne dopadaö Dûemiju Markhamu?
{91136}{91187}Ne znam.
{91219}{91294}Rekao je Kejti da viöe ne ûeli da me vidi.
{91323}{91466}äta? Zar taj lopov misli da je bolji od nas?
{91478}{91579}On nije lopov.|-On je lopov i provalnik.
{91614}{91701}I ona verovatni ima ista gene, bolje se pazi.
{91742}{91834}»uli smo da je imale neke broöure za Vegas|i da tamo ide sa tobom.
{91941}{91971}Trebalo je da krenemo u nedelju.
{92030}{92078}Trebalo je da se venËamo kada stignemo.
{92214}{92220}OdliËan plan, zar ne?
{92256}{92336}Hteo si da me napustiö? Bez reËi?
{92345}{92431}Mama, rekao bih ti.|-Kao i tvoj otac.
{92645}{92749}Moj brat i ja...njegovi prijatelji...
{92779}{92867}Zdravo, momci.|-On ne govori.
{92903}{92960}Otac nije zatvarao usta a sin mu je mutav.
{92990}{93114}Gde je tu pravda?|-Idi gledaj TV.
{93192}{93302}Brendane, gde si ti bio izmeu|12:30 i 02:00 u nedelju ujutru?
{93346}{93417}Spavao sam.|-Da li moûete to da potvrdite g-o?
{93536}{93729}Mogu da potvrdim da je zatvorio|vrata u 10. U 9 ujutru je siöao |na doruËak.
{93735}{93848}Ali ne mogu da potvrdim da nije otvorio prozor|i siöao niz poûarne stepenice.
{93886}{93970}O.K: Brendane, zamoliÊemo te da |se podvgneö detektoru laûi.|Da li si sposoban za to?
{94083}{94163}Jako puno sam je voleo.
{94222}{94285}Viöe niöta ne mogu da oseÊam|Tako neöto se ne deöava dva puta.
{94445}{94501}Nekima se ne deöava ni jednom.
{94552}{94665}äta radiö ovde?|-Izvini Dûemi.
{94677}{94751}Joö uvek smo iznenaeni.|-Zaöto si joö uvek ovde?
{94837}{94897}Ne znam.
{94903}{95084}Ja samo...da li je Anabet zaspala?
{95119}{95205}Rekao sam joj da uzme tabletu.|-Mogu li i ja da dobijem jedno piÊe?
{95419}{95469}Jedno za usput.
{95621}{95693}Dûemi, mogu da ostanem ako sam ti|potrebna.
{95719}{95778}Mogu da pravim druötvo Anabeti.
{95779}{95811}Dovoljno si uËinila.
{95933}{96001}Za tebe i Dejva, zato öto ste sa nama.
{96631}{96682}DoÊi Êu sutra rano ujutru.
{96732}{96767}Laku noÊ.
{96809}{96857}Da, laku noÊ.
{97445}{97507}Halo?
{97602}{97662}O pobogu! Lora, reci neöto.
{97872}{97935}O.K. äon kakav ti je bio dan?
{97977}{98200}Umoran sam da brinem o mrtvoj devojci|i o drugima kje Êe doÊi posle nje.
{98268}{98392}Ubice öaljemo u zatvore ili kuÊu da tavore|u svojim bednim ûivotima.
{98398}{98452}Tako ti je to.
{98538}{98648}Ne mogu ovo da radim veËeras.
{98687}{98785}Ne mogu.
{98826}{98871}∆ao, mala.
{99195}{99337}Zato öto Ëovek ponekad uopöte i nije Ëovek,
{99378}{99441}ti si samo deËak, 
{99465}{99521}deËak koji je pobegao vukovima,
{99574}{99643}zver sumraka,
{99661}{99836}nevidljiv, tih, |koji ûivi u svetu
{99863}{99928}koji drugi nikada nisu videli.
{99988}{100201}Svet vatrenih boraca,nevidljivih |osim kao plamen...
{100255}{100356}koji ti greje oko, koji nestaje vremenom.
{100736}{100837}Dolazi noÊu,|da uhvati dug i lep san,
{101069}{101152}samo da bi se posle vratio u svoju öumu,
{101202}{101286}nazad svojim vatrenim borcima.
{101517}{101567}Da li spava?
{102192}{102254}Video sam se sa Dûemijem i svima.
{102293}{102373}O.K. »udno je.
{102408}{102497}Trebalo je da se ovako neöto desi da|se ponovo sprijateljimo.
{102533}{102596}Dejv, Dejv, 
{102696}{102755}Joö uvek nema niöta u novinama.
{102770}{102878}O Ëemu?|-O Ëemu?
{102969}{103065}Moûda ga nisam tako jako povredio |kako sam prvo pomislio.
{103115}{103190}On je pljaËkaö. Sigurno ne bi otiöao|u bolnicu.
{103323}{103368}Da. Tako je.
{103436}{103501}To u stvari i nije vaûno.
{103534}{103591}Kejti Markham je mrtva.
{103635}{103692}To se Ëini trenutno vaûnijim.
{104574}{104648}U duöi znam da sam i ja doprineo|tvojoj smrti.
{104710}{104755}Ali ne znam kako.
{105358}{105411}Brendon je proöao detektor laûi.
{105420}{105524}Nisam ni Êeleo da padne.|-Baö sjeban mali.
{105545}{105652}BalistiËari Êe se vratiti za par sati| U meuvremenu imamo spisak|oËevidaca.
{105666}{105764}Svi oni koji jedva Ëekaju da sarauju|sa policijom.
{105845}{105948}Da li je to onaj tip sa kojim si bio |drug u detinjstvu, onaj sa kolima?
{105996}{106169}Mogao bi biti.|-S njim bi trebalo razgovarati. Zna|da Êeö se lepo ponaöati.
{106207}{106243}VideÊemo.
{106584}{106712}Hej, Bojle. Nismo se videli 6-7 godina.
{106751}{106837}Kako si?|-Ovo je moj sin Majkl.|-Kako si Majkl?
{106855}{106917}Ja sam äon. Stari drug tvoga tate.
{106943}{107006}Joö si u policiji.|-Da, odeljenje za ubistva.
{107051}{107128}Ovo je moj partner.|- Ja sam poruËnik Pauels.
{107158}{107229}Dejv, imaö li malo vremena. Hteli smo |da ti postavimo par pitanja.
{107232}{107380}U stvari, hteo sam da otpatim Majkla|do ökole. Brzo se vraÊam.|-Znaö öta, idemo sa tobom.
{107523}{107615}Jesi li dobro?|Da li kirije skaËu?
{107624}{107748}Da zato öto japi stiûu. KuÊu mog oca|su pretvorili u apartmane.
{107755}{107868}Ja i Majkl smo proöli tuda pre neki dan.|Mora da postoji neöto öto moûemo da|uradimo i spreËimo ih.
{107871}{108076}Prijatelj mi reËe pre neki dan da ovom|kraju treba talas kriminala da bi cene|nekretnina bile adekvatne.
{108096}{108197}Mlade devojke bivaju ubijene|u Pen Parku, tako da ima öanse|da Vam se ûelja ispuni gine Bojl.
{108230}{108354}Dejv. Zovite me Dejv.|-VeÊ si to rekao, tata.
{108411}{108497}Idi malo napred. Ovi momci ûele|da razgovaraju samnom.
{108521}{108613}Hajde. -äta se deöava, äon. Da li si|Ëuo za Kejti Markham?
{108682}{108786}Da. Bio sam kod Dûemija juËe ceo dan.|Selest je sada tamo.|-Ko je Selest?
{108791}{108860}Moja ûena.|-Kako Dûemi sve to podnosi?
{108887}{108949}Teöko je reÊi. Znaö ti njega.
{108969}{109094}-Znaö razlog öto smo svratili...|-Sluöaj, video sam je... Kejti..
{109112}{109207}ne znam dali znaö u restoranu pre |nego je umrla.
{109219}{109386}Baö o tome smo i hteli da razgovaramo sa tobom.|Nekolicina ljudi iz bara moûe da se pojavi|kao svedoci.
{109403}{109481}Koliko sam Ëuo, napravila je pravu|predstavu od svoje igre na öanku.
{109495}{109552}Bile su priliËno pijane.|-Bilo je bezopasno.
{109567}{109703}Nisu se skidale ili sliËno. Imaju po 19 godina. |-Kada su otiöle?
{109721}{109810}Ja sam otiöao oko 1 a one su otiöle|15 minuta pre mene.
{109825}{109911}ReÊi Êemo u 12:45.|-ZvuËi otprilike taËno.
{109944}{110098}Da li si primetio neöto ili nekog neobiËnog?|-Majkl! -äta Majkl?
{110107}{110232}Ne znam. Neki tip koji je posmatrao devojke, |neko ko ih je gledao sa mrûnjom,
{110306}{110437}Ne, njihova igra na öanku je bila|neöto najnormalnije.
{110479}{110523}Imaö li dosta novca?
{110752}{110912}Mrzeo sam ökolu.|-äta? Aha. Da.
{110942}{111067}I ja, äone. -Samo joö jedna stvar|g-dine Bojl.
{111099}{111138}Gde ste otiöli posle restorana?
{111180}{111283}KuÊi.-I stigli ste kuÊi otprilike oko 1:15|kao öto ste rekli.-Otprilike, tako.
{111396}{111480}U redu.|-Hvala ti puno, Dejv. OtiÊi Ëemo jednom na pivo.
{111503}{111601}Da, voleo bi to, äon.-U redu.
{111770}{111889}äta?|-äta se desilo sa njim u tim kolima?
{112121}{112264}Moûeö li da poverujeö? Ovo isto je na drugom|mestu 15 puta jeftinije.
{112358}{112504}Ako izuzmemo ljubav, novac i mrûnju kao |razlog, nije ti puno ostalo.
{112528}{112629}Ovo öto se desilo Markhamovima je nasumice.|-PriËaj mi o tome. Stara gospoa...
{112652}{112849}...nije Ëula vrisak, Ëula je pucanj a pre toga |"∆ao", öto mi govori da je Markhamova|Êerka bila jako druûeljubiva...
{112861}{113036}... ili je poznavala tu osobu.- Bila je u kolima i nije |vozila brzo, skinula je nogu  sa gasa, | zastala je...-Da se pozdravi, 
{113045}{113268}on puca u nju.- TrËeÊi beûi.- Da ali, zaöto|je skrenula bez koËnice?- Ne znam. Moûda|je bilo neöto na ulici.
{113273}{113445}Moûda. Moûda. -Ali ta Markhamova mala, |mora da nije Ëekala duûe od 1:10. Kako|je onda mogla da ga udari tako jako..
{113461}{113520}da on odskoËi.-Moûda se ubica nije doËekao|na noge.
{113546}{113615}Tvoj ortak Dejv Bojl mi se Ëini kao tip koji se |uvek doËeka na noge.
{113627}{113728}»ekaj, Ëekaj, otkud sad da doemo do njega.
{113737}{113844}-Upravo smo stigli do njega.On je samo tip koji|je bio u baru. Poslednje mesto, äone, 
{113853}{113978}poslednje mesto na kome je ona bila.|On greöi. Video si mu ruku.
{113986}{114114}Da. Video sam mu ruku.|-Trebalo bi ozbiljnije da se pozabavimo njim.|Makar malo.
{114301}{114429}PreporuËujem Vam ih dva puta dnevno|izmeu 3 i 5 i 7 i 9.|-Naravno.
{114548}{114664}Dobro.-Da li ste razmiöljali o cvetnim |aranûmanima?- Neko se veÊ pobrinuo za to.
{114681}{114812}Dobro.
{114877}{115163}Da li imate obaveötenja?-Obaveötenja?|O da, umrlice. Mi to moûemo da sredimo|ako nam date osnovne podatke.
{115186}{115284}Za donacije ili tome sliËno.|-Gde je moja Êerka?
{115403}{115486}Dole u podrumu.-éelim da je vidim.
{116877}{117149}NaÊi Êu ga. NaÊi Êu ga pre policije|a kada ga naem ubiÊu ga.
{117295}{117372}Da li ste neöto rekli, g-dine Markham?
{117465}{117732}Na umrlici treba da stoji Ketrin Markham, |voljena Êeka Dûejmsa i Marite, pokojne, 
{117756}{118207}Anabetina poÊerka, sestra Sare i Nejdin.
{119214}{119306}Opet vi momci.- Da. Kao dve zle pare.
{119360}{119514}Da li ste svraÊali kod Dûemija. -Da-|-Ima li napretka u sluËaju?
{119535}{119562}Samo smo otiöli da izjavimo sauËeöÊe. Kuda si|ti poöao?
{119609}{119722}Pripuöilo mi se. Idem da ih kupim.|Vidimo se brzo.
{119751}{119829}Usput, g-dine Bojl, öta Vam se |desilo sa rukom?
{119903}{119930}MeljaË otpada u lavabou.
{119962}{120081}Stavio sam ruku u njega i on se|sam pokrenuo. Glupost.|-Mora da je bilo bolno.
{120215}{120378}-MeljaË otpada u lavabou. Sranje.|To ne znaËi da je nekoga ubio. Hajde.
{120827}{120880}»ujem da bi ti jedna dobro doöla.|-Hvala.
{121118}{121026}Trudim se da smanjim.|-Kako god ti kaûeö, Crvena.
{121121}{121147}Uite, idem po Dûemija.
{121326}{121472}Imam par stvari da obavim. VraÊam se |za 1 sat. -Ne moraö da se vraÊaö, Selest.|BiÊu u redu.
{121489}{121567}Jesi li sigurna?|-Selest Bojl?-Da.
{121593}{121778}Kako ste? Ja sam äon Divajn, Dejvov prijatelj.|Ovo je Vajti Pauels.-G-o Bijl.-Drago mi je .
{121789}{122015}Moram da poem.|-Ostavio sam izveötaj u kolima. 
{122030}{122059}Bolje idi ga uzmi.-Da.
{122128}{122161}Hajde.
{122321}{122386}Hej, Selest, mogu li neöto da te pitam?
{122458}{122517}Kada se vratio kuÊi u subotu uveËe?|-äta?
{122538}{122713}Samo pokuöavamo da ustanovimo |taËan redosled dogaaja vezano za Kejti i|siguran sam da ti je Dejv rekao da je video.
{122784}{122945}Ti misliö da je Dejv ubio Kejti? -O ne, pobogu,|nisam to rekao. Nisam to ni pomislio.
{123031}{123224}Ne znam. - Ne, ne, ne. Samo mislimo |da ako saznamo taËno vreme kada je ona |bila na drumu, i znamo kada je Dejv doöao kuÊi,
{123233}{123381}vidiö, ima samo 5 minuta od Vaöe kuÊe do|restorana, a Kejti je napustila restoran 15 minuta |pre Dejva.Razumeö öta mislim?
{123447}{123687}Spavala sam. Subota uveËe. Kada je Dejv|doöao kuÊi, spavala sam.
{123729}{123771}U redu. Hvala.
{124085}{124311}Sranje.Ne, Dûemi, viali su se. Trebalo |je da idu zajedno u Las Vegas. Video sam |avio karte sa njihovim imenima.
{124320}{124555}Brendon Heris je to potvrdio.|-SeÊaö li se öta si rekao u subotu? Kako te|je gledala kao da se viöe neÊete videti.
{124620}{124700}Da li je Brendon Heris ubio moju Êerku?|-Nije.
{124736}{124884}Da li ste 100% sigurni?Proöao je detektor|laûi i Ëini se da je zaista voleo.
{125021}{125155}Molim te reci mi zaöto si toliko protiv |tog malog?
{125187}{125279}Kejti je rekla da si rekao da Êeö|je se odreÊi ako se ponovo bude|videla sa njim.
{125336}{125440}Znao sam njegovog oca. Zvali smo ga |"samo Rej" Heris. -Zaöto?
{125532}{125820}Zato öto je bilo jako puno ljudi sa istim |imenom u kraju. Ludi Rej, psihopata Rej...|sva ostala imena su bila zauzeta, tako da...
{125844}{126078}njemu ostalo "samo Rej". Nikada se nismo|slagali i nije mi se dopadao. I pobegao je od |ûene kada je bila trudna.
{126176}{126375}Mislio sam da iver nikad ne pada daleko|od klade. Nisam ûeleo da Bendon Heris ili neki |drugi Heris izlazi sa Kejti ili sa nekom drugom mojom Êerkom.
{126479}{126601}Ne mogu da verujem da razgovaramo |o Rej Herisu.|-G-dine Markham, 
{126604}{126925}ispitivali smo svedoke, i naiöli smo na par |sumnjivih lica, koje su pre nas, ispitivala|braÊa Sevidû.
{126952}{127014}Pa öta?|-Pa oni nisu policija, Dûemi.
{127047}{127177}Neki ljudi ne razgovaraju sa policijom.|-Uz svo duûno poötovanje g-dine Markham, |da bi smo se bolje razumeli, 
{127186}{127299}ovo je naö sluËaj.|-Koliko dugo?|-Koliko dugo öta?
{127317}{127429}Koliko dugo Êe Vam trebati da naete|ubicu moje kÊeri? Moram da znam.|-Da li se vi to pogaate sa nama?
{127498}{127611}Pogaam?|-Dajete nam rok.
{127721}{127804}Mi Êemo se pobrinuti da se sve dobro |zavröi za Kejti. Ako se Vi slaûete.
{127861}{127994}Vi samo pronaite ubicu moje kÊeri, |poruËniËe. Ja Vam ne stojim na putu.
{128125}{128273}Poslednje öto nam je potrebno u ovom trenutku |je da Dûemi Markham i braÊa Sevidû |jurcaju unaokolo i obavljaju Boûji posao.
{128276}{128508}Svi su ih se plaöili i kada smo bili deca.|I majka im je bila lujka, radila je u fabrici.|Ko ih jebe, budale.
{128615}{128731}Zdravo, momci. BalistiËari su stigli.|-Da li se nalazi poklapaju?|-BiÊete oduöevljeni.
{128799}{129007}Savöeno se poklapa. Piötolj je .38. Smit & Veson.|Kupljen od nekog prodavca oruûja i |poslednji put je koriöÊen 1982 godine.
{129031}{129218}Piötolj kojim je ubijena Kejti Markham je |koriöÊen i za pljaËku prodavnice piÊa 1984 god.|baö ovde u Bakinghem Fletsu.
{129233}{129523}Greöka. Mesto se zvalo Mimina prodavnica |piÊa. Naöao sam dosije. To su odradila dvojica.|Pucali su samo jednom u zid, tako i imamo metak.
{129547}{129628}Dobro obavljen posao. I mislio sam da|Êe Vam se dopasti.
{130531}{130744}U redu je, Rej. Niöta ne brini.
{131187}{131511}Ja sam to rekao? Da mi je bolje bez nje?|Ja sam je voleo, znaö li kako je to!
{131957}{132099}Izvini. Ne, greöiö, nikada viöe|se neÊu tako oseÊati. 
{132143}{132369}Baö ovde! Proöao je kroz bocu Dûeka |i zabila se u zidu. -Straöno.|-Straönije od Ëaöe mleka. Zar ne?
{132425}{132714}Recite mi kako je bilo? Ta dvojica su uöli...|-Sa gumenim maskama, ovuda su uöli, tamo |je ostava...
{132779}{132952}Ova vrata pozadi vode do mesta za|utovar. Ta vrata su uvek zakljuËana.
{132987}{133177}To znaËi da mora da su imali kljuË.|-KljuË? ZnaËi Vi kaûete da je to uradio|neko iznutra?
{133186}{133516}Morao je da bude. Mora da je bar jedan od njih |radio kod mene ranije. Jedini razlog zbog kog su |ispalili metak upozorenja je taj öto su znali da ovo drûim ispod.
{133531}{133783}I to ste i rekli policiji tada?|-Naravno. ProËeöljali su moje spiskove radnika, |ispitivali sve koji su ovde nekada radili.
{133819}{133896}Nikada nikoga nisu uhapsili.|-Da li joö uvek imate kopije |podataka o bivöim zaposlenima?
{133908}{134068}Da. U kutiji u kancelariji. Ali ja znam|ko je to bio.-Stvarno?
{134107}{134392}Taj momak koga sam otpustio par nedelja |pre toga, kuËkin sin je doöao par dana nakon|pljaËke, i zlokobno se cerio, 
{134404}{134558}i ja sam jednostavno znao!|-Ali dokaûi ti to poroti.
{134609}{134728}Da li se seÊate njegovog imena?|-Da li ti ja delujem senilno?
{134766}{134948}Ne, g-dine. -Zvao se Rej Heris.|Zvali su ga "samo Rej".
{135069}{135256}Kaûete da je isti piötolj koriöÊen|za joö jedan zloËin?|-Tako je g-dine Luni. Hvala Vam na pomoÊi.
{135658}{135963}Gde si bila?- Napolju. äta to gledaö?|- Film o vampirima.
{136023}{136168}Glavnom liku je odseËena glava.|Gde si bila Selest?
{136338}{136554}Sedela sam u kolima, niöta posebno samo|sam razmiöljala.
{136626}{136786}O Ëemu si razmiöljala? -Znaö ti.|-Ne u stvari, ne znam.
{137065}{137181}O raznim stvarima, dan kada je Kejti ubijena.
{137232}{137410}Jadan Dûemi. Sve to.- Sve to?
{137469}{137525}Znaö o Ëemu sam ja razmiöljao, draga?
{137591}{137674}O vampirima.
{137689}{137775}äta sa njima?
{137778}{138052}Oni nisu mrtvi. I mislim da ima neöto |divno u njima. Moûda se jednog dana |probudiö i zaboraviö da si Ëovek...
{138057}{138159}...moûda Êe tada biti u redu. 
{138179}{138363}O Ëemu ti to priËaö, Dejv? O vampirima,|duöo i o vukodlacima.-To nema nikakvog|smisla.
{138476}{138661}Ti misliö da sam ja ubio Kejti? Selest.|Da li to uopöte ima smisla?
{138672}{138797}Prestani da priËaö o smrti. - Jedva da si me i|pogledala otkako si saznala da je Kejti mrtva.
{138803}{139061}U stvari, bio sam ti odbojan. -Dejv!|-äta? -Niöta ne mislim. Zbunjena sam!
{139085}{139195}»ak se i tvoj prijatelj äon raspitivao o tebi.|-On nije moj prijatelj, zar to nisi do sada shvatila.
{139204}{139436}On me je ispitivao o tebi.Kada si doöao kuÊi?|-äta si mu rekla? - Rekla sam da sam spavala.
{139489}{139656}Dobro si postupila, duöo.|-Isuse, Dejv! Zaöto mu jednostavno ne |kaûeö za pljaËkaöa?- PljaËkaö?
{139745}{139869}-Da. Sad shvatam kako ti razmiöljaö! Doem |kuÊi sav krvav iste veËeri kada je |Kejti ubijena i ti misliö da sam je ja ubio!
{139941}{139976}Jebiga.
{140778}{141009}Henri. - äta? Henri. -Henri i Dûordû.
{141158}{141194}To nikome ranije nisam rekao.
{141274}{141340}To su bila njihova imena.
{141369}{141393}Zar to nije smeöno?
{141530}{141848}Tako sam ih zvao. |-Dejv je bio deËak koji je pobegao vukovima.
{141951}{142010}O Ëemu priËaö Dejv?
{142032}{142201}PriËam o Henriju i Dûorûu. Odveli su|me na 4-oro dnevni izlet.
{142240}{142361}Zatvorili su me u podrum samo sa |vreÊom za spavanje.
{142400}{142599}Ja, Selest sam im bio hrana.
{142617}{142661}Niko nije doöao da pomogne jadnom Dejvu.
{142766}{142881}A Dejv se pretvarao da je neko drugi.
{143054}{143353}Misliö pre toliko godina...|kada si bio mali deËak...Dejv!
{143380}{143582}Dejv je mrtav! Ne znam ko je izaöao |iz tog podruma ali to svakako nije bio Dejv!
{143647}{143885}Vidiö, duöo, jebiga, to ti je kao sa|vampirima. 
{143898}{144057}Ono öto te izjeda, to i ostaje u tebi.
{144103}{144203}äta ostaje?
{144358}{144432}Znaö li da su terali decu na prostituciju?
{144471}{144630}äta?
{144687}{144782}Jebiga!
{144829}{145064}Viöe ne mogu da verujem svom umu, Selest.|Upozoravam te. Ne mogu da verujem svom umu.
{145166}{145276}Moram da izaem. Moram da razbistrim um.
{145340}{145382}O.K.
{145677}{145738}Samo mislim da treba da usmerimo |istragu u drugom pravcu.
{145745}{145888}Ja ne mislim tako. äta "samo Rej Heris ima |sa svojim sinom? -Znaö kako se te stvari prenose?
{145902}{146078}Moûda je on napustio grad, ali njegov |piötolj nije. - Mislim da bi trebalo da popriËamo |sa Brendonom Herisom sutra ujutru.
{146098}{146208}Da, a ja kaûem Deni Bojl. PriËa o ruci.|éena se definitivno plaöi, 
{146214}{146320}-Mislim da neöto krije, ali mislim da je Deni|Bojl isto toliko ubica koliko i Brendon Heris.
{146330}{146529}Bojl savröeno odgovara profilu ubice: |srednjih 30-ih godina, belac, sa povremenim zapoöljenjem,|seksualno zlostavljan kao dete...-Da li si ti ozbiljan?
{146538}{146722}Po novinama, on bi do sada veÊ bio u |zatvoru. - On nije bio zlostavljan kao dete.|Po toj jednaËini, priznanje zlostavljanja...
{146728}{146858}je deo pogodbe. -Bili ste prijatelji kao deca, zato|si pristrasan.
{146865}{147025}Hej, on nije moj prijatelj. |Ako se ispostavi da si u pravu, moje lisice|Êe biti na njegovim rukama pre tvojih.
{147511}{147812}Hej Dûemi. Malo je kasno. -Da.|-Hladno je. -Da, jeste.
{148074}{148412}Znaö, veÊ par godina unazad sedim ovde,|ËekajuÊi Kejti da se vrati.
{148456}{148569}Bilo bi to oko ponoÊi, a ja bih sedeo i Ëekao.
{148721}{148911}»udno je, öto se viöe neÊe vratiti.
{149006}{149154}Znaö, ja sam je video.|-Koga si video?
{149175}{149353}Kejti. Bili smo u istom restoranu te veËeri.|-Video si Kejti u subotu uveËe?
{149383}{149547}Nisam ranije imao priliku da ti kaûem.|-Da li si razgovarao sa njom?
{149605}{149743}Nije bilo svrhe. Kada sma ponovo podigao|pogled, nje viöe nije bilo tu.
{149954}{150218}Ali, Dûemi...izgledala je sreÊno.
{150705}{150797}Idem joö malo da proöetam. Laku noÊ.
{151166}{151260}Ukrao si mu kola? -Njegova kola su bila|zvaniËno oduzeta.
{151270}{151421}-Ispreed njegove kuÊe? -Ne kola su bila |napuötena u blizini parka.
{151424}{151593}SreÊom mi imamo nadleûnost nad tim delom.|Neka deca su mogla da uzmu kola i da se vozaju, 
{151602}{151803}Zaöto, zaöto si to uradio? -Nakon öto smo |se rastali sinoÊ, reöio sam da razgovaram |sa Bojlom i uteram mu strah u kosti.
{151828}{151958}Doöao sam do njegove kuÊe, i |reöio da pogleda öta ima u kolima.|Naöao sam krv.
{151976}{152068}Na prednjem sediötu kola tvog prijatelja  |Dejva. B negativna.-Koliko?-Malo.
{152074}{152232}Naöao sam joö viöe u prtljaûniku. |Mnogo viöe. Nulta grupa. Ista grupa|koju je imala Kejti Markham.
{152232}{152407}»ekaj malo, Ëekaj. Kejti Markham nije bila|ni u Ëijem prtljaûniku. Neko je jurio kroz |park, gde je i umrla.
{152421}{152537}Mislim da je dosta ispitivanja.|-äta misliö da je tvoj pretres kola bio u redu?
{152541}{152630}Ne, ne naeno i napuöteno na gradskom tlu.
{152645}{152724}Zarad osuguranja. I u najboljem interesu vlasnika.
{152743}{152817}Obavio si fiziËki pretres i podneo izveötaj.
{152876}{152942}Bingo.-HoÊeö li da razgovaraö|sa njim ili da ga poöaljem kuÊi?
{152968}{153040}Dejv je ovde?U pritvoru je veÊ 1 sat.
{153049}{153161} Poslao sam dvojicu najruûnijih da|ga pokupe.
{153183}{153316}Hajdete, g-dine Bojl. Znamo da tu ruku |niste nabili u meljaË otpada u lavabou.
{153328}{153458}Stvarno? A kako to znate?|-Zaöto je Vaöa ûena izgledala kao da Vas se plaöi?
{153467}{153562}Da li ona stvarno zna öta se desilo sa Vaöom rukom?
{153767}{153939}éeleo bih Sprajt ili neöto...|-Kako bi bilo da nam kaûete öta |se zaista desilo u subotu uveËe, g-dine Bojl?
{153978}{154135}Laûete. -To je Vaöe miöljenje, na koje|pretpostavljam imate pravo.|Mislite li da je ovo smeöno? -Ne.
{154159}{154346}Ne, ne mislim. Umoran sam, icrpljen, |sinoÊ su mi ukradena kola a Vi mi |kaûete da joö uvek ne mogu da ih dobijem.
{154346}{154412}O.K.
{154543}{154620}Recite nam g-dine Bojl kako je krv |dospela u Vaöa kola?
{154629}{154789}Kakva krv? -Hajde da poËnemo od |prednjeg sediöta. äta gledate u njega?
{154885}{155006}Misliö li da mogu da dobijem |taj Sprajt, äon? -Naravno.
{155056}{155252}A, kapiram. Ti si dobar pandur.|Kad smo veÊ kod toga, moûe li i jedan|sendviË?
{155292}{155342}Ako veÊ zanovetaö, onda Êeö morati da Ëekaö.
{155413}{155653}A zar ti ne zanovetaö, äone?|-Krv na tvom prednjem sediötu, Dejv, odgovori |naredniku.
{155757}{155936}Imamo mali teren iza kuÊe. Sa sinom sam |igrao svako popodne fudbal posle ökole.
{155960}{156140}Dosta je dobar, tako da puno lopti|ode preko ograde. Tako da ja moram |da se penjem i jednom sam se okliznuo i pao, 
{156146}{156387}i posekao sam ruku i stomak. Bilo je |puno krvi.10 minuta kasnije sam morao |da idem po Majka u ökolu.
{156446}{156568}Verovatno sam joö uvek krvario kada sam |uöao u kola. -Koja je Vaöa krvna grupa?
{156613}{156815}B negativna.- Stvarno? Onda se poklapa.|Onda je sve u redu.- Ne baö.
{156815}{157010}Krv u prtljaûniku nije bila B negativna.|Ne znam niöta o krvi u prtljaûniku.
{157041}{157151}Nemate pojma kako je toliko krvi|dospelo u Vaö prtljaûnik?-Ne.
{157175}{157282}Ovako nigde neÊemo stiÊi, Dejv.|Kako Êe to delovati na sudu?
{157293}{157484}Vi ne znate kako je neËija krv dospela |u Vaö prtljaûnik. -Valjda Vi znate. Vi ste|podneli izveötaj.
{157519}{157693}Koji izveötaj? -Izveötaj o krai kola.|SinoÊ kola nisu bila u mom posedu.
{157709}{157837}Tako da morate da saznate za öta su ih |lopovi koristili. Izgleda ni zaöta dobro.
{158059}{158140}Da li su mi izgledi za Sprajt bolji, äone?
{158164}{158344}Pravio si se prepametnim. »ak i ako je|neËega bilo u kolima, njegov advokat |moûe da kaûe da smo mu podmetnuli.
{158351}{158504}Mogu da ga slomim.- Moûeö da ga slomiö?|Samo si nas uvalio. da li joö uvek misliö|da Dejv ne bi ni mrava zgazio?
{158505}{158665}Nije u tome stvar. -U Ëemu je stvar, äone?|Moramo da se skoncentriöemo na piötolj.|On je najvaûniji.
{158672}{158823}O.K. Moûda.
{158847}{158894}äta Êemo onda sa Dejvom.
{158936}{158989}OslobodiÊu ga.
{159010}{159179}Moûda Keltski krst? To mnogi biraju.|Ovaj divan crveni mermer.
{159313}{159361}Ovaj.
{159370}{159468}Jako lepo. Lepo i jednostavno.
{159723}{159796}Hej, Dûemi.
{159868}{160007}Anabet je rekla da si ovde. Raspitivali |smo se okolo kao öto si rekao.
{160040}{160255}Dûemi, ne radi se o onome öto si ti uradio|za mene. Nije Ëak ni zahvalnost. -Znam.
{160275}{160399}Kejti je bila moja neÊaka. Moûda ne po krvnom srodstvu, |ali je bila naöa  porodica i mi smo je voleli.
{160406}{160659}Ne dovodim to u pitanje. äta ima?|-Panduri su svuda okolo. Rade svoj prokleti |posao. Bar jednom. Njuökaju i sve ispituju.
{160667}{160750}Svaka kurva i barmen sa kojima smo |razgovarali, veÊ je proöla kroz pandurske ruke.
{160753}{160863}Ne moûemo niöta viöe da uradimo.|-Ostaje nam samo "samo Rej"-ov mali.|äta je sa njim?
{160890}{161066}Tih je kao miö. Klinac uopöte i ne |predstavlja problem. Razgovarao sam sa |Dajanom i Ivom i rekle su da je voleo.
{161113}{161220}Dûemi, rekle su i da je ona volela njega.
{161234}{161344}HoÊeö li da ga pritegnemo? -Ne, idite.
{161386}{161748}Joö neöto? -äta?|Ako imaö neöto da kaûeö, reci.|-Reci mu.
{161822}{162001}Partner äona Divajna je priveo Denija Bojla.|Dejvi je video Kejti u subotu uveËe pa|ga ispituju kao i sve ostale.
{162043}{162256}Jutros sam Ëuo joö neöto. Dva uniformisana pandura |su doöla. -Moûda su zaboravili da ga pitaju neöto.
{162271}{162432}Ne, kada su ga pokupili, stavili su ga na |zadnje sediöte, ako znaö na öta mislim.
{162892}{163141}Rejmond Metju Heris, roen 06.09.1957.|Prvi sin, Brendon äejmus, roen 1983.|Iste godine kada je "samo Rej" optuûen...
{163151}{163206}za prevaru vezanu za proneveru|u podzemnoj.
{163233}{163409}Optuûbe su odbaËene i on je osloboen. |U naöoj evidenciji se pojavio ponovo|kada je opljaËkana prodavnica piÊa Lunis.
{163436}{163640}Ispitivan u vezi te pljaËke, i joö jedne|iste godine, isto prodavnica piÊa|I opet puöten zbog nedostatka dokaza.
{163650}{163721}Postao je poznat po tome. Dobio je na popularnosti.
{163750}{163964}Joö jedan poznanik Fingers Rejmond 1985,|koji se povezuje sa pljaËkom Kolekcije retkih|stripova.
{163976}{164128}Kolekcija stripova?- Ma oladi.|-Hej stani malo, to je vredelo $ 150.000.|-Izvini ti.
{164157}{164386}Rejmond je stripove vratio netaknute i|odleûao godinu dana. I izaöai iz zatvora |sa problemom zavisnosti.
{164389}{164511}Poöten posao da bi mogao da odrûava svoju naviku.|-Pa i ne baö.
{164537}{164734}UhvaÊen je ponovo u akciji MCU i FBI|zato öto je preprodavao ukradenu robu|preko drûavne granice.
{164742}{164832}Ukrao je kamion pun cigareta.|-Momak ima stila.
{164837}{165015}I puno tuge. Ukrao je kamion na |Roud Ajlendu i odvezao ga u MasaËusets.
{165030}{165239}I to je federalni prekröaj?|- I zato su ga uhvatili za jaja.Ali, |nije odsluûio ni dana.
{165256}{165336}Ocinkario je nekoga.--Da i izgleda tako. | Posle toga je Ëist.
{165354}{165512}Avgust 1989, on nestaje.|-1. On je mrtav. 2. Postao je zaötiÊeni svedok.|-3. odlazi u duboku ilegalu
{165520}{165645}i pojavljuje se ponovo u starom kraju da bi|ubio 19 -ogodiönju devojku svog sina|Ma, hajde.
{165667}{165909}Nemamo niöta. - Imamo glavnog osumnjiËenog|u provali koja se desila pre 18 godina, za vreme koje |je koriöÊen piötolj. Imamo sina koji se zabavljao...
{165909}{166020}sa ûrtvom. Ja kaûem da imamo dosta. Ima li|tu joö neöto o saradnicima "samo Rej"-a?
{166038}{166248}Pogledaj.Poznati kriminalci, Redûinald Tuki Nil, |Kevin Vajtdûab SuraÊi, Nikolas Sevidû.
{166281}{166427}Entoni Veksmen i jedam Dûejms Markham.
{166504}{166613}Imena samo pristiûu.
{166706}{166783}Da li ste me traûili?-Zdravo. Ja sam|äon Divajn a ovo je Vajti Pauels.
{166798}{166825}Kako je?Moram brzo da se vratim. 
{166887}{167057}Vi ste radili u specijalnoj jedinici sa|Majorom Krajbsom 80-ih. -Da, pa?|- I uhapsili ste jednog sitnog plaËkaöa...
{167065}{167247}Reja Herisa. Ukrao je kamio cigareta.|-VozaË je otiöao u WC.
{167276}{167342}Tip mu ukrade kamion a zaustave ga |zbog prebrze voûnje.
{167362}{167467}A ipak je osloboen?|-Nije osloboen nego je ocinkario.
{167493}{167609}Bostonskoj policiji je trebala|informacija koju je on imao.
{167618}{167725}Koga je ocinkario?|-Kako se ono beöe zvao, jebote?
{167758}{167891}On i joö trojica su opljaËkali  $ 60.000 |iz poreskog. Aha, Dûemi Markham.
{167969}{168052}Tada je imao 19-20 godina. |»istog dosijea, nikad uhapöen.
{168084}{168185}Da li je Heris ikada svedoËio na sudu?|-Nikada nije ni doöao do suda.
{168215}{168330}Markham je odao svoje pajtose, a |javni tuûilac se plaöio da neÊe moÊi |da ih osudi.
{168354}{168446}Pa se dogovorio sa njim. Dve godine|u zatvoru i joö nekoliko uslovno.
{168461}{168527}ZnaËi da Dûemi Markham nikada nije |saznao da ga je Rej Heris ocinkario.
{168606}{168744}Roj Heris je nesta  salica zemlje dva|meseca nakon öto je Markham puöten. 
{168770}{168802}To Vam sve govori.
{169150}{169260}Dûemi. -Zdravo roako, kako si?
{169269}{169513}Dobro. Moûemo li da porazgovaramo na trenutak?
{169525}{169575}Dolazim za trenutak.
{169690}{169819}Ui u moju kancelariju.
{170086}{170157}Divan dan.
{170371}{170546}Da li je sve u redu?
{170597}{170707}Uzela sam Majkla sinoÊ i otiöli smo|u hotel.
{170906}{170994}Ostavila sam Dejva.-Ostavila Dejva?|-Zauvek sam ga ostavila.
{171232}{171434}»udno se ponaöa u poslednje vreme.
{171560}{171604}Uvek sam ga se plaöila.
{171734}{171768}Da li ti neöto znaö?
{171872}{171928}Uvek sam ga pravdao.
{171978}{172094}Znam da je video Kejti one noÊi |kada je ubijena.Nije mi pomenuo|sve dok ga panduri nisu ispitali o tome.
{172100}{172273}Uvek sam imao razumevanja za njega, |ali uzalud.
{172287}{172331}Ima li joö neöto öto bi trebalo da znam?
{172714}{173077}OK.U 3 ujutru u nedelju, vratio se kuÊi|pokriven krvlju.
{173124}{173392}äta je rekao da se dogodilo?|-Da je bio pokuöaj pljaËke i da je |povredio napadaËa.
{173401}{173568}I da ga je moûda Ëak i ubio.
{173733}{173823}Niöta o tome nije bilo u novinama.
{174114}{174506}Da li misliö da je on ubio moju Kejti?
{174826}{174859}O Boûe!
{175263}{175367}PriËaj mi o tvom ocu Brendone. -äta?|-O tvom ocu.
{175394}{175438}Rej senior.SeÊaö li ga se?
{175474}{175516}Imao sam 6 godina kada je otiöao.
{175525}{175659}ZnaËi ne seÊaö ga se?|-Jedva neöto malo.
{175706}{175870}Stalno je mirisao na ûvake. On...|-On öta?
{175943}{176030}Uvek je imao dosta sitnine po dûepovima.|I zveckalo je dok je hodao.
{176086}{176299}Uvek bi ga Ëuo kada dolazi.|Ako bih pogodio koliko ima, Ëak i da sam |blizu, dao bi mi sve.
{176333}{176380}A öta je sa piötoljem? Da li je tvoj otac imao piötolj?
{176416}{176451}Ne.
{176496}{176558}Ali ne moûeö da budeö siguran imao |si samo öest godina kada je otiöao.
{176668}{176701}äta je to?
{176731}{176865}To je ono öto ste traûili.Izveötaji, analize|otisaka, balistiËki nalazi, snimak razgovora sa 92.
{176875}{176938}Cela gomila. -O.K. Hvala.
{176966}{177099}PriËali smo o piötolju tvoga oca.|-Rekao sam Vam da moj otac |nije imao piötolj.
{177134}{177283}Izgleda da smo pogreöili.|-Kada si poslednji put razgovarao |sa njim?
{177313}{177431}Nikada. -Nikada. -reako je da ide |na piÊe i nikada se viöe nije vratio.
{177458}{177533}Ali tvoja majka nije podnela zahtev|zbog njegovog nestanka. Zaöto ne?
{177556}{177586}Zato öto nije nestao.
{177613}{177663}Svakog meseca nam öalje novac.|-äalje novac?
{177716}{177811}$ 500 svakog meseca. TaËan je kao sat.
{177868}{177954}Odakle?|-Na poötanskom ûigu stoji Bruklin.
{177996}{178056}Kako znaö da je od njega?|- Ko bi drugi mogao da bude?
{178162}{178198}Niko drugi nam ne bi slao.
{178246}{178290}Mama kaûe da je tamo bio.
{178320}{178376}Da je tamo napravio neko sranje i da |pokuöava da se iskupi za to.
{178501}{178552}Zaöto me stalno ispitujete o tome|da li je moj otac imao piötolj?
{178638}{178726}Ne voliö öto te to pitamo?- Ne, ne volim.
{178769}{178896}Isti piötolj kojim je ubijena tvija devojka, |tvoj otac je koristio u pljaËki pre 18 godina.
{178952}{179015}Pa, ûeliö li da mi kaûeö neöto o tome?
{179124}{179174}Moj otac nije imao piötolj.
{179184}{179288}Ti si prokleti laûov!
{179433}{179490}Mogu li da idem sada ?
{179526}{179579}Ili Êete me optuûiti za Kejtino ubistvo?
{179995}{180058}Dejv, Dejv Bojl. Kako je?
{180140}{180241}Nije loöe.Kako ste vi momci?
{180276}{180390}U redu. Ali sve je sjebano.
{180419}{180570}Kejti. Jebena tragedija.
{180586}{180913}Da. Malo sam gladan, öta misliö da|odemo negde na klopu. VeËernji izlazak| momaka u sred bela dana.
{181059}{181148}Uskoro moram kuÊi. -Zar ne moramo svi?|Hajde upadaj.
{181159}{181284}U redu.Prva tura je moja.
{181373}{181450}Rekao si pravu stvar.
{181970}{182083}Mislim da mali laûe u vezi piötolja. äta ti misliö?|-Apsolutno se slaûem sa tobom. Rekao sam ti|veÊ 3 puta.
{182107}{182219}äta znamo o ocu?-Ne znam, moûda je|"samo Rej" zaista joö uvek ûiv.
{182267}{182362}Ko bi inaËe slao tolike pare |ako ne otac?
{182520}{182701}Idi kuÊi, popi piÊe, ne razmiölja o tome|neko vreme.- Da. Da li je bilo neöto|od poziva 92? 
{182736}{182786}Mislio sam da si ih presluöao.|-Ja sam mislio da si ih ti presluöao.
{182965}{183140}92 policija.Zbog Ëega zovete?|Jedna kola su ovde i vrata su otvorena...
{183144}{183324}-Gde se nalazite?|Ulica Sidni.Kod Pen parka. Tu sam sa prijateljem.
{183363}{183441}-Sinko, kako se zoveö?|-éeli da zna ime.
{183449}{183541}Tvoje ime, sinko. Kako se zoveö?|-Beûimo odavde. SreÊno, ËoveËe.
{183622}{183722}Da to Êe nam pomoÊi da reöimo sluËaj.|Ma hajde.
{183728}{183862}Idemo na hamburger ili neöto drugo.|Sluöaj. -äta? -Klinac na traci.
{184025}{184085}Sinko, kako se zoveö?|-éeli da zna ime.
{184106}{184213}On je rekao njeno ime.|-Ona je mrtva devojka i o njoj priËa tako.
{184222}{184376}Da, ali kako to klinac zna?|Ona je mrtva u parku, kako on zna |da je krv u kolima njena?
{184539}{184608}Pusti ponovo.
{184771}{184979}Ja imam problem...Ja i Niki.
{185021}{185107}Sa jednim naöim prijateljem.|Prokleti prijatelj.
{185137}{185216}Kunem se, on sam ne ume ni pertle na|cipelama da veûe.
{185266}{185443}Sve ima neka odela koja mu smeöno |stoje...Kada ga neko vidi smeje se.
{185576}{185695}Jedino meni veruje.|A ja mu kaûem baö me zabole.
{185721}{185807}Da li misliö da liËiö na Ronalda Regana?
{186051}{186102}Da li ste Vi ikada ozbiljni?
{186164}{186250}Takva sranja se uvek deöavaju na poslu.
{186264}{186337}Zato je uvek frka.
{186447}{186494}Zaöto misliö da je zastranio?
{186595}{186643}Zbog onoga öto se desilo sa Kejti.
{186737}{186862}A Vi momci? -äta mi.
{186889}{186933}Mi smo joö uvek normalni.
{186933}{186966}Mi smo obiËne budale i sve prolazi pored|nas ili to prespavamo.
{187160}{187266}Da li ûeliö joö jedno piÊe?
{187451}{187587}Morao bi malo da usporim...|-Ma hajde. Ne budi takva piËka.
{187807}{187842}Proûivi malo!
{188786}{188823}Hajde ortaci.
{188843}{188965}Ta ti je dobra!|-Kako si? -Malo pijano.
{189019}{189081}Za naöu decu.
{189226}{189265}Oduvek mi se dopadao ovaj momak.
{189405}{189463}Zato mi je ûao kad ima problema u ûivotu.
{189503}{189573}Ne smeö da dozvoliö da se neko zajebava|sa tobom ili tvojima. Zar ne Dejv?
{189586}{189651}Apsolutno si u pravu.
{189671}{189719}Izgleda kao ludak.
{189794}{189850}O da, moj Ëovek Dejv. 
{190005}{190063}Momak, donesi nam flaöu.
{190394}{190438}Popi piÊe Dejv. -Hajde.
{191603}{191644}I mi smo se znali sa Rej Herisom.
{191697}{191748}Svi su ga zvali "samo Rej".
{191775}{191819}Ali neki su ga zvali Rej Dûingls.
{191962}{192075}Uvek je imao $10 sitnine u dûepovima,| u sluËaju da mora da telefonira|ili neöto sliËno.
{192138}{192371}Dejv? Dejv? Da li si u redu.|Muka mi je. -Idi na zadnja vrata.
{192380}{192429}Ne vole da Ëiste WC .
{193126}{193203}Hej Rej.
{193554}{193601}Doöli ste da proverite da ne upadnem?
{193786}{194011}Doi ovamo na trenutak. Sedi.
{194338}{194371}ReÊiÊu ti neöto o Rej Herisu.
{194398}{194585}Bio mi je ortak.PoseÊivao me je u zatvoru.|Proveravao je da li mi je porodica u redu.
{194670}{194722}I on me je takoe tamo i smestio.|Ocinkario me je.
{194749}{194831}Sranje, to je straöno.- Brinuo sam se za |ûenu i decu u to vreme.- SeÊam se.
{194850}{194908}Roj Heris me je koötao toga da ne |budem sa mojom ûenom koja je bila na|samrti u to vreme. Nisam mogao da budem...
{194932}{195099}...sa njom. Morala je sve sama. A ja nisam |mogao da joj pomognem. Razumeö me?|-Zaöto mi to priËaö?
{195141}{195262}Ubio sam ga tamo. Pucao sam u njega sa 2 metka.|Jedan metak u grlo drugi u grudi.
{195271}{195307}SeÊam se oba pogotka.| 
{195324}{195360}Dûemi...-Prestani da kukaö.
{195402}{195568}Tvoja ûena me je poznavala.|Zna da sam dobar Ëovek.
{195628}{195678}äta ti misliö Dejv? Da li sam ja dobar Ëovek?
{195731}{195921}Koga mrziö?- Nikoga.
{196002}{196038}äta misliö da sam ja uradio?
{196041}{196296}Sve vreme dok sam ga izvlaËio iz vode, |mislio sam da me Bog gleda i klima glavom|nije bio ljut, Kao da se to od mene i oËekivalo.
{196344}{196896}Koga voliö? UËini mi. Da li voliö mamu? |A mene toliko voliö...samo to ne govoriö.
{197014}{197202}Ti misliö da sam ja ubio Kejti? Zar ne?|Sluöaj Dejv, samo Êuti.Ubio sam nekoga ali to nije Kejti.
{197216}{197404}To je priËa o pljaËkaöu.-On nije bio pljaËkaö. |On je zlostavljao dete. Imao je seksualni |odnos sa  detetom u kolima.
{197404}{197511}On je bio jebeni vuk! Bio je zver.
{197775}{197807}Beûi odavde.
{198187}{198220}TrËi!
{198354}{198446}Ubio si onoga koji zlostavlja decu.|-Da. Samo ja i deËak...
{198476}{198511}Da li ti je zlostavljeni deËak pomogao?
{198529}{198640}O ne, nije.|-Ali upravo si rekao. Rekao si ti i deËak.
{198649}{198743}Zaboravi na to!|Sve mi je mutno u glavi!
{198758}{198823}Tvoja ûena misli da si ti ubio moju Êerku.
{198883}{199063}Bolje da si joj rekao koga si ubio. VeÊinu|ljudi je za njih baö briga da li oni umiru ili ne.|Zaöto joj nisi rekao istinu?
{199073}{199239}Ne znam.Moûda sam pomislio da ovo|bolje zvuËi. Ja nisam ubio Kejti.
{199308}{199430}Ne seÊam se da sam Ëuo da je neËije |telo pronaeno, a vi momci?
{199444}{199551}Stavio sam ga u prtljaûnik mojih kola.|-PustiÊeö ovo govno da ti priËa priËe?
{199557}{199610}Ko ga jebe. Ubi ga!|-Ja je nisam ubio!
{199658}{199768}Zaveûite! Zaveûite, jebote! Svi zaveûite!
{199783}{199925}ReÊ je o mojoj Êerki! O njoj priËam!
{200050}{200181}19 godina. -Ja je nisam ubio.|19 godina. -Nisam ubio Kejti.
{200193}{200294}Pogledaj me Dûemi! Gledam te Dejv. Gledam te.
{200311}{200541}Zaötio si to uËinio?|-Moj sin i ja i Selest moramo mnogo|toga da ispravimo.
{200558}{200626}Gledaj öta se desilo baö kada si ti reöio|da ispravljaö stvari.
{200647}{200801}Nema viöe laûi. Nema viöe tajni. |éelim da idem kuÊi kod Selest. éelim da |je osetim.
{200831}{200897}MoraÊeö da odleûiö svoje vreme kao|öto sam i ja morao.
{200912}{201060}Priznaj öta si uradio.|-Sluöaj, deËak...|-Joö jednom li pomeneö deËaka...
{201069}{201458}i rasporiÊu te. Tako sam i mislio da Êe biti.|Ubite ga i bacite u reku.
{201656}{201719}Ako priznaö öta si uradio, pustiÊu te da ûiviö.
{201779}{202049}Samoo glasno izgovori i poötedeÊu ti ûivot.|Priznaj öta si uËinio, i pokloniÊu ti ûivot.
{202081}{202254}Priznaj öta si uËinio. Priznaj.
{202326}{202718}Znam da umeö da govoriö. Pa reci onda.|Reci da me voliö.Ne gledaj u njega. Gledaj mene.|Reci da me voliö.Reci!
{203029}{203425}Moj brta to nikada ne bi uradio bez tebe.|-Pusti me, ostavi me.
{203550}{203700}VratiÊu se. Toliko me voliö da si morao da |ubijeö moju devojku? Govori! Ti prokleta nakazo!
{203700}{204214}Ili Êu te ubiti!-Reci svoje ime!|Reci. Reci Kejti ili Êeö umreti!
{204310}{204401}Mali, hoÊeö li da uperiö taj |piötolj u pod?
{204459}{204792}Hajde da vidimo, ti si hteo da potegneö|piötolj na mene?|-Ne ,ja to ne radim sa decom.
{204792}{204836}Ali vidim da me je neko pretekao u tvom sluËaju.
{204862}{205080}Uite, on me je udario, polomio mi je nos|-UhapsiÊemo ga i poslati u zatvor ako treba.
{205099}{205218}Ne ûelim da ga uhapsite, ûelim ga mrtvog!
{205425}{205474}U jebote!
{205667}{205878}Priznaj öta si uradio, Dejv.I pustiÊu|te da ûiviö. Samo glasno izgovori.
{205906}{206113}I pustiÊu te na miru.IÊi Êeö u zatvor. |Ali Êu ti poötedeti ûivot.
{206121}{206300}Priznaj, Dejv.Priznaj öta si uradio.
{206427}{206840}Da. Priznajem, ja sam to uËinio.|-Zaöto? -Zaöto?
{206840}{207259}Te noÊi, ona me je podsetila na |san koji sam imao.-Kakav san?
{207283}{207468}Na san o mladosti. Ne seÊam se da sam je imao.
{207571}{207767}ZnaËi, to je bilo zbog sna.|Da, zbog sna.
{207812}{207892}Ti bi trebalo da znaö öta to znaËi.|Da si ti primio taj poziv umesto mene.
{208137}{208206}Ali ja nisam primio taj poziv, Dejv.
{208301}{208334}Ti si ga primio.
{208946}{209017}Ovo mesto Êe ti biti poslednje boraviöte.
{209118}{209158}Reka Êe te oprati. 
{209200}{209357}Kakva mu je to priËa o vukovima?|-Njegove priËe me viöe ne zanimaju.
{209575}{209626}Nisam bio spreman.
{209741}{209826}To je to, Dejv.
{209936}{209977}Ovo Êu sam obaviti.
{211293}{211399}Teöka noÊ?
{211431}{211483}Da, i za mene.
{211552}{211591}Video sam metak sa mojim imenom.
{211883}{211947}Uhvatili smo ga, Dûemi.
{212043}{212124}Imate koga? -Kejtinog ubicu.
{212132}{212351}Ubice? Mnoûina.
{212420}{212602}Da, deca, u stvari.Sin Reja Herisona i Rej Junior|i  joö jedan deËak Dûon Roöe. Pre par sati|su priznali.
{212744}{213006}Bez sumnje? -Nikakve.
{213147}{213460}Zaöto? Ni sami ne znaju. Igrali su se |sa piötoljem, videli da dolaze kola, |i pucali su.
{213494}{213649}Kola su usporila i izaöla je Kejti.Kaûu |da su samo hteli da je uplaöe a piötolj|je iznenada opalio.
{213707}{213936}Ali ona je pokuöala da pobegne, |oni su je pratili da ne bi nekome rekla.
{214166}{214300}A da li su je oni tukli?|-Rej Junior je imao ötap za hokej.
{214575}{214677}Pogledaj me. Pogledaj me, Dûemi.
{214756}{214896}Selest Bojl me je zvala. ZvuËala je|histeriËno zato öto Dejva nema veÊ par dana.
{214904}{214948}Moûda ti znaö gde je.
{214988}{215022}Moramo da razgovaramo sa njim.
{215066}{215155}Bostonska policija je naöla telo muökarca|u öumi.
{215212}{215332}Telo muökarca? -Da, pedofil koji|je veÊ 3 puta bio osuivan.
{215385}{215605}éele da razgovaraju sa Dejvom o tome.|Dûemi, kada si poslednji put video Dejva?
{215956}{216045}Poslednji put kada sam video Dejva, 
{216104}{216150}Da, Dejvida Bojla.
{216431}{216541}Dejv Bojl. -Da, Dûemi. Dejv Bojl.
{216717}{216751}Bilo je to pre 25 godina. Odlazio je |niz ulicu u tim kolima.
{217055}{217121}Dûemi, öta si uradio?
{217432}{217481}Hvala öto si naöao ubice moje Êerke, äone.
{217588}{217675}Da si samo bio malo brûi.
{217908}{217978}Da li Êeö slati i Selestinom malom|$ 500 meseËno, takoe?
{218208}{218357}Ponekad pomislim, kako bi bilo da smo |mi bili u tim kolima,
{218422}{218521}sve je ovo samo san, znaö.
{218548}{218593}Samo san, äone.
{218655}{218940}Realnost je ukradena 11-ogodiönjem |deËaku zakljuËanom u podrumu.|ZamiöljajuÊi kakav bi ûivot bio da pobegne.
{219208}{219414}Moûda si u pravu. Sjebali smo se.
{220150}{220540}äon je. éao mi je, potrebno mi je da|to znaö. Ja sam te odgurnuo od sebe.
{220550}{220933}I meni je ûao.Sve je bilo tako zbrkano.|Nisam znala da li te volim ili mrzim.
{220933}{221310}Vrati se kuÊi. Da li si moûda promenio brave?|Ne. Sve je baö onako kako si i ostavila.
{221317}{221668}Nora. -äta je to?|-Nora? To je ime naöe Êerke, äon.|-Nora.
{221712}{221822}Dopada mi se Nora.
{222694}{222926}Ubio sam Dejva. Ubio sam ga i bacio u reku.|Ubio sam pogreönog Ëoveka.
{222974}{223091}To sam uradio. I ne mogu to da ispravim.
{223169}{223480}O Dûemi. éelim da  osetim tvoje srce.
{223544}{223709}SinoÊ, kada sam stavila devojËice u|krevet, rekla sam im kako si ti veliki Ëovek.
{223719}{224060}Koliko si voleo Kejti. Zato öti si je stvorio.|I ponekad, tvoja ljubav za nju je bila tako jaka|da se Ëinilo da Êe ti srce eksplodirati.
{224060}{224256}Prekini. -Rekl sam im da i njih isto|toliko voliö. Svim srcem.
{224265}{224421}I one su bile toliko ispunjene ljubavlju|da viöe ne moraju da brinu o tome.
{224431}{224714}I da Êe njihov tata uËiniti sve za one|koje voli. I da nikada ne greöi.
{224724}{224902}I da ono öta njihov tata uradi, nikako |ne moûe biti pogreöno.
{224994}{225074}I devojËice su mirno zaspale.
{225292}{225585}Rekla si sinoÊ...Znaö...-Selest te je|traûila. Zabrinuta je da se moûda  Dejvu|nije neöto desilo.
{225594}{225749}Rekla mi je isto öto i tebi. Kakva |ûena priËa takve stvari o svom muûu?
{225762}{225975}Zaöto je to doöla tebi da kaûe?|Zato sam i rekla devojËicama, |njihov tata je kralj.
{225975}{226392}I kralj zna öta treba da radi. Ion to radi.|»ak i kada je to teöko. I da Êe njihov tata sve|uËiniti za one koje voli. Ijedino je to vaûno.
{226548}{226695}Svi osim nas su slaboiÊi, Dûemi.
{226734}{226827}Ja nisam slabiÊ Dûemi. A ni ti.
{226897}{226958}Ti bi mogao da vladaö ovim gradom.
{227079}{227287}Hajde, Dûemi da povedemo devojËice|na paradu. Kejti bi to volela.
{230143}{230235}Majkl! Majkl!
{230260}{231760}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/drm6|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
