{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{6813}{6861}Ah, dobro veËe, gospodine.
{6861}{6909}VeÊ sam pomislio kako|nema nikog kod kuÊe.
{6909}{6957}Zaista? A ko biste vi|mogli biti?
{6957}{7029}Detektiv inspektor Doppler,|gospodine,
{7029}{7101}iz Wiltshireske okruûne policije.
{7101}{7161}éao mi je öto dolazim ovako kasno,
{7161}{7222}ali moram malo da popriËam sa vama...
{7222}{7305}o jednoj veoma vaûnoj stvari.|-Pa, onda je bolje da uete.
{7305}{7365}Wiltshireska okruûna policija, kaûete?
{7365}{7426}Tako je, gospodine.|ObiËno sam stacioniran u Salisburyju,
{7426}{7521}ali, vaöi lokalni policajci su me|zamolili da skoknem i da im malo pomognem.
{7570}{7629}To su bili dani, gospodine.|Melodije koje se mogu pevuöiti.
{7629}{7725}To je bilo bezbriûno vreme, inspektore.|HoÊete li jedan akvavit?
{7725}{7773}Ne, hvala vam, gospodine. |VeËerao sam.
{7773}{7857}Moûda biste voleli jedan brendi?|Ili Êete mi reÊi da nikad ne pijete na duûnosti?
{7857}{7918}O, ne, gospodine.|Uvek pijem na duûnosti.
{7918}{7965}Ne mogu si priuötiti|u slobodno vreme.
{8013}{8074}Kavijar. ZnaËi, tako to izgleda.|-Da.
{8109}{8157}»esto sam se to pitao.
{8362}{8422}Ne mogu reÊi da mi|se svia neöto naroËito, gospodine.
{8482}{8541}Ima ukus na riblja jaja.
{8541}{8661}OdliËno. A sad dozvolite da vam sperem|taj grozni ukus jednim sjajnim brendijem.
{8673}{8743}Poite za mnom,|molim vas, inspektore.
{8901}{8938}Sve ove starine, gospodine...
{8950}{8997}vrlo zanimljivo, gospodine.
{9034}{9129}Imate, uh, jako lepu|kolekciju lutaka.
{9129}{9225}Automata, inspektore,|i svi rade.
{9225}{9309}Pa i ne vidim neki smisao imati ih|ovoliko ako ne rade, gospodine.
{9322}{9370}A sad, kao öto kliöe nalaûe,
{9370}{9441}öta mogu da uËinim|za vas, inspektore?
{9441}{9501}Istraûujem nestanak...
{9501}{9573}gospodina Mila Tindla.
{9573}{9621}Da li ga poznajete,|gospodine?
{9621}{9669}Nisam siguran.
{9717}{9802}Izaöao je iz svoje kuÊice|proölog petka kasno popodne...
{9813}{9850}i od onda viöe nije vien.
{9861}{9933}Stvarno, bojim se da nisam|preterano zainteresovan....
{9933}{10006}u nomadske navike|pojedinih frizera.
{10006}{10053}ZnaËi, ipak ste poznavali|dotiËnog, gospodine?
{10053}{10101}Pa, znao sam Ëime se bavi.
{10114}{10197}»ini mi se da mi je ûena jednom|pomenula da ima radnju u Londonu.
{10197}{10257}Kada ste poslednji put videli|gospodina Tindla, gospodine?
{10257}{10330}O, pre nekoliko meseci.|Ne bih mogao taËno da se setim.
{10330}{10462}A nemam ni razloga za to.|-To se baö i ne slaûe sa naöim informacijama.
{10474}{10558}Zamolio bih vas, ako biste mogli|da mi sipate malo vode u brendi, gospodine.
{10617}{10678}U stvari, pre dve noÊi,
{10678}{10762}je rekao Jacku Bennu,|krËmaru 'Kod belog lava',
{10762}{10810}da je krenuo|da se nae sa vama.
{10810}{10881}Barmeni su poznati|oponenti istini, inspektore.
{10881}{10941}Vinski traË je|njihova hleb nasuöni.
{10941}{11002}'Vinski' se odnosi na vino,|pretpostavljam, gospodine.
{11002}{11061}Vrlo dobro.
{11337}{11410}Onda moram da se zapitam ima li joö neöto|öto bi mi mogli razjasniti, gospodine.
{11421}{11457}Kao na primer?
{11457}{11506}Utisak, koji je stekao Ëovek....
{11506}{11578}sluËajno prolazeÊi pored|vaöe kuÊe u petak uveËe,
{11589}{11649}da su se odavde|Ëuli hici.
{11649}{11722}Hici?|-Tri, misli naö Ëovek.
{11722}{11805}Auspuh.|-O, ne, gospodine.
{11805}{11865}Bojim se da toga ima samo u...
{11877}{11950}izvinjavam se, gospodine...|detektivskim priËama.
{11950}{12021}Ne, to su bili hici iz piötolja.|Naö Ëovek je siguran.
{12021}{12080}Razumem. Smem li da pitam...
{12080}{12163}zaöto vam je trebalo dva dana|da doete i da me pitate o tome?
{12163}{12224}Pa, gospodine, uh, za te stvari...
{12224}{12271}uvek treba malo viöe vremena...
{12271}{12320}da to proverimo|nego öto vi mislite.
{12332}{12391}Ovdaönji policajci ûele|da budu sigurni u ove Ëinjenice...
{12391}{12476}pre nego öto me pozovu i pre nego|öto uznemire gospodina poput vas.
{12487}{12548}»injenice?|Kakve Ëinjenice?
{12548}{12619}Pa, poöto je, uh, naö izvor...
{12619}{12680}prijavio incident,
{12680}{12788}mi smo mislili da bi, uh, bolje bilo|da popriËamo sa gospodinom Tindlom,
{12788}{12860}i da vidimo da li bi on mogao|da baci malo svetla na predmet.
{12871}{12955}I da li je mogao? Ako hoÊete to da|iskljuËite, inspektore, samo pritisnite 'stop'.
{12955}{13028}Oh, izvinite.
{13028}{13076}Hvala.
{13076}{13172}Nije ga bilo kod kuÊe|cele subote...
{13184}{13232}niti ga danas ima.
{13232}{13292}Mora biti da smo vas|zvali ovamo bar öest puta.
{13292}{13400}Jupitera mi, gospodine, Merridew|bi se ponosio vama.
{13400}{13459}A. Vaö detektiv, gospodine.
{13459}{13519}O, hvala na komplimentu, gospodine.
{13519}{13568}Ja sam veliki oboûavalac|njegovog Lordstva.
{13568}{13639}Stvarno? Pa, morate mi onda reÊi|koji je vaö omiljeni roman?
{13639}{13706}Ja, liËno, moram vam priznati,|da posebnu naklonost oseÊam prema...
{13707}{13736}'SluËaju razapetog komuniste'.
{13736}{13808}Kad smo uöli u kuÊu|gospodina Tindla....
{13808}{13891}da se uverimo da mu|se niöta loöe nije desilo,
{13891}{13952}naöli smo ovo, gospodine.
{13964}{13999}''Hitno moramo da razgovaramo....
{14011}{14131}Doite u petak popodne|oko 6:30. Wyke.''
{14131}{14215}Smem li da vas pitam,|je l' ovo vaö rukopis, gospodine?
{14227}{14312}Da, moj je, tako je.|-ZnaËi, onda je gospodin Tindle, bio ovde.
{14312}{14408}Bio je.|-A da li se ovde desio i incident pre dve noÊi...
{14420}{14479}prilikom kog je pucano?
{14479}{14528}Pa, na izvestan naËin.
{14528}{14588}Igrali smo jednu igru.
{14588}{14660}Igru, gospodine?|Kakva je to igra?
{14660}{14720}Zove se ''provala''.
{14720}{14792}Provala nije igra, gospodine.
{14792}{14876}Nije li doölo vreme|da mi kaûete...
{14888}{14960}kako ne shvatam svu ozbiljnost|situacije u kojoj se nalazim?
{14960}{15067}»ovek je doöao ovamo.|»uli su se pucnji. On je nestao.
{15067}{15151}I, öta biste vi pomislili,|da ste na mom mestu, gospodine?
{15151}{15236}Lako reöiv sluËaj. Ali, stvari|nisu uvek onakve kako izgledaju.
{15236}{15307}Vidite u 'SluËaju udavljene lutke'',|vaö omiljeni lik, lord Merridew...
{15307}{15379}»ekam objaönjenje, gospodine.
{15391}{15428}Oh. Dobro.
{15440}{15523}Tindle je stigao oko 6:30|a otiöao sat i po kasnije.
{15523}{15619}Od onda ga viöe nisam video.|-Nije ni niko drugi, gospodine.
{15619}{15727}Ali, to je apsurdno! Ne mislite,|valjda, da sam ja ubio Tindla?
{15727}{15800}''Ubio Tindla'', gospodine?|Ja nikad nisam pomenuo reË ''ubiti''.
{15812}{15908}Ma hajde, inspektore.|Ne moûete mi to prikaËiti.
{15920}{15980}''Udavljena ûicom, gospodine.|Smem li da vas pitam kako ste znali...
{15980}{16028}da je milostiva gospoa|tako ubijena?''
{16040}{16087}''VI ste mi rekli, inspektore.''|''Ne, gospodine.
{16087}{16172}Nikad nisam pomenuo 'garotiranje'.''
{16172}{16244}éao mi je ako nalazite|da je to smeöno, gospodine.
{16244}{16303}Sve u svemu,|samo radimo sve öto je potrebno.
{16303}{16376}''Samo radite svoj posao''|zar nije to veÊ otrcana fraza, zar ne?
{16376}{16423}MoguÊe, inspektore.|Veoma moguÊe.
{16435}{16496}''Otrcana fraza.''|To mi se svia.
{16496}{16616}Vaöa ûena i gospodin Tindle su bili jako bliski|veÊ neko vreme, gospodine.
{16616}{16663}Da, znao sam da Êe|te to kad tad saznati.
{16663}{16783}Ne moûete niöta sakriti u malom selu.|-Sasvim taËno, gospodine.
{16783}{16855}Ne sugeriöete valjda na|zloËin iz strasti, iskreno se nadam.
{16855}{16903}Ne zbog Marguerite. Boûe moj!
{16915}{16952}To bi bilo kao izbosti nekog...
{16963}{17024}zbog najobiËnije kaöike|pune hladnog pudinga od pirinËa.
{17024}{17095}Ja baö volim puding|od pirinËa, gospodine.
{17095}{17156}Nalazim da je veoma postojan.
{17156}{17215}To je savröeno.
{17215}{17288}''Svi vi imate sredstvo,|motiv ili priliku',
{17299}{17360}rekao je inspektor Doppler,|dok je zamiöljen vario...
{17360}{17408}joö jednu kaöiku|svog omiljenog pudinga.
{17408}{17479}'Ali samo jedan od vas|je imao sva tri!''
{17479}{17576}TaËno tako, gospodine,|a ta osoba ste vi.
{17576}{17672}Boûanstveno.
{17672}{17732}Pa, onda pretpostavljam da bi najbolje|bilo da vam kaûem öta se desilo.
{17733}{17803}To bi bilo od pomoÊi, gospodine.|-Moûda bi pomoglo joö jedno piÊe?
{17803}{17888}Popio bih joö jedno, gospodine, ali mislim|da vam je flaöa veÊ prazna.
{17900}{17960}U pravu ste, inspektore.
{17960}{18008}I to se moûe ispraviti.|HoÊete li poÊi sa mnom, molim vas?
{18043}{18091}Sad, kao öto veÊ izgleda znate,
{18091}{18139}Tindle je bio u|ljubavnoj vezi sa mojom ûenom.
{18152}{18200}Ja pripadam onom|retkom soju muökaraca...
{18200}{18259}koji iskreno nema niöta|protiv da izgubi dostojanstveno...
{18259}{18307}od dûentlemena koji|igra po istim pravilima.
{18320}{18403}Ali, kao munjom oËeöljani,|pseudo-italijanski ljubavnik...
{18403}{18475}koji je moju indiferentnost|smatrao nezaineresovanoöÊu...
{18475}{18523}to je veÊ, sve zajedno, previöe.
{18536}{18608}HoÊete da kaûete da nikako niste mogli da se|naterate da prihvatite novonastalu situaciju, gospodine?
{18608}{18656}Da li mi to govorite?|-HoÊu da kaûem,
{18656}{18727}da je to bila situacija|koju sam odbijao da prihvatim, inspektore.
{18835}{18895}Igra je za vas veoma vaûna,|gospodine, zar ne?
{18895}{18979}Igranje i igranje igara.
{18979}{19051}Da, inspektore.|-Nisam baö siguran da vidim razliku, gospodine.
{19051}{19111}O, to je savröeno jednostavno, inspektore.
{19111}{19171}Igranje je ono öto|svaki dûentlmen radi,
{19171}{19255}ali igranje odreenih igara|je moja strast.
{19255}{19315}Na neki naËin,|moj ûivot.
{19495}{19591}To mi deluje pomalo tuûno, gospodine.|Kao dete koje nije odraslo.
{19591}{19675}Ne vidim niöta tuûno u detetu|koje se igra, inspektore.
{19675}{19759}Pa i nije tuûno, gospodine,|ako ste dete.
{19759}{19819}Dozvolite mi, inspektore,|da vam kaûem...
{19819}{19879}igrao sam tako|kompleksne igre,,,
{19879}{19987}da bi Jung i Einstein bili veoma ponosni ako|bih ih zamolio da mi se pridruûe.
{19987}{20083}Dostigao sam takve domete uma|i domete duöe....
{20083}{20155}nepoznate u obiËnim|ljudskim odnosima.
{20155}{20215}i uËestvovao|sam u ogromnom broju....
{20215}{20299}ne-baö-nevinih zabava.
{20407}{20479}Postoji li bilo öta öto|vi ne biste smatrali igrom, gospodine?
{20479}{20551}Duûnost? Posao?|Moûda brak?
{20551}{20611}Oh, molim vas, inspektore.|Ne ukljuËujte brak.
{20611}{20707}Seks... seks je igra,|brak je kazna.
{20755}{20839}Vrtimo se u krug od jedne|do druge propale godiönjice,
{20839}{20887}dodaj ''idi'',
{20887}{20959}sakupi 200 guûvi,|200 Êutanja,
{20971}{21043}200 oûiljaka na najtananijim mestima.
{21043}{21137}Da li hoÊete da kaûete, gospodine,|da zbog vaöe indiferentnosti prema ûeni...
{21137}{21209}niste imali motiv da|ubijete gospodina Tindla?
{21209}{21281}Jednostavno vam kaûem, inspektore,|da, sam kao i veÊina muökaraca,
{21281}{21341}ûeleo svoj kolËiÊ|i da sam sve ignorisao.
{21341}{21413}To je bilo priliËno duhovito,|pretpostavljam.
{21413}{21485}A öta imamo ovde,|gospodine?
{21485}{21557}To je samo korpa sa starim kostimima,|niöta viöe.
{21569}{21629}Tradicionalno mesto...
{21629}{21725}za sakrivanje,|siguran sam da Êete se sloûiti.
{21737}{21785}Samo identiteta, inspektore.
{21833}{21881}Igra.
{21881}{21929}HoÊemo li?
{21977}{22061}HoÊemo li?|-O, da, gospodine.
{22061}{22109}Dolazim.
{22217}{22301}U svakom sluËaju, mislio sam|da Êu mladom gospodinu Tindlu....
{22301}{22373}oËitati lekciju zbog njegovog bezobrazluka,|ispitati njegog karakter, kakav je.
{22373}{22433}Moûda se neÊete sloûiti sa ovim, inspektore,|ali verujte mio kad vam kaûem:
{22445}{22505}najkraÊi put do muökarËevog srca|vodi preko poniûenja.
{22517}{22565}Tako Êete najbrûe saznati|od Ëega je sazdan.
{22565}{22673}Oh. I, kako ste isplanirali|da ga ponizite, gospodine?
{22673}{22721}Za poËetak, hteo sam da ga ubedim....
{22733}{22829}da moja ûena ima veoma skup ukus,|a da je on, tako reÊi, golja.. 
{22829}{22937}i da taj problem moûe reöiti|tako öto Êe ukrasti skupoceni nakit,
{22937}{23009}iz mog sefa.
{23093}{23189}Joö sam ga ubedio i da skine|svoju odeÊu i da se preruöi.
{23201}{23309}Sasvim zgodno, iz one korpe koju ste upravo|pregledali, izabrao je kostim klovna.
{23309}{23405}U tom smeönom odelu, provalio mi je|u kuÊu i dinamitom otvorio sef.
{23465}{23513}Nakit je bio u kutiji.
{23633}{23693}Dobro razmiöljanje,|inspektore.
{23825}{23861}Bravo.
{23873}{23957}A gde je nakit sad, gospodine?|-Vratio sam ga juËe u banku.
{23957}{24017}U subotu?|-a, inspektore, u subotu.
{24017}{24077}Odvezao sam se do Salisburyja|i stavio ih u noÊni sef.
{24077}{24137}Veoma pametno, gospodine.
{24137}{24221}Mogu li vas upitati öta ste vi|radili poöto je on razneo sef?
{24221}{24341}Tindle je stavio nakit u dûep pa smo se malo|borili po kuÊi. Sve je to bio deo igre.
{24341}{24461}I baö kad se spremao da poe ja sam postao|bezobrazan i otkrio mu svoje prave namere.
{24461}{24533}Rekao sam mu, naravno, kako sam sve ovo|izveo samo kako bih ga doveo u poloûaj...
{24533}{24629}gde Êu moÊi, pretvarajuÊi se da sam ga zamenio|za provalnika, s pravom da ga ubijem.
{24677}{24737}Kada ste otkrili|svoje namere, gospodine.
{24785}{24821}kako je gospodin Tindle|reagovao?
{24833}{24917}Kao da ga je grom pogodio. Pogutao je|ne samo moju udicu, veÊ i strunu i plovak.
{24917}{24977}Pao je na kolena,|preklinjuÊi za milost,
{24977}{25085}ali ja sam bio neumoljiv, Prislonio sam|mu piötoj na glavu i upucao ga...
{25109}{25181}Êorkom.
{25277}{25349}Upucali ste gospodina Tindla...|Êorkom, gospodine?
{25349}{25409}Odmah se onesvestio.
{25409}{25517}Moja igra je bila gotova.|Bila je to najslaa pobeda.
{25517}{25601}Vi ste mu, u stvari...|prislonili piötolj uz glavu....
{25601}{25685}i povukli obaraË...u igri?
{25721}{25793}Nazovite to njegovim testom|inicijacije, ako tako viöe volite.
{25805}{25889}Doöao je ovde glumeÊi gospodina,|nadajuÊi se prijemu u viöi staleû.
{25889}{25997}Ali, morao je dobiti lekciju.|Ne ulazi se tek tako u moj staleû.
{25997}{26045}Postoje stvari kao öto|je poreklo!
{26045}{26165}Kvalitet kojidobijate poreklom...|ne moûe se steÊi.
{26165}{26225}Naravno, pao je na testu.
{26225}{26285}Moûda bi ga i proöao, gospodine....
{26285}{26381}ali je bio u velikom strahu|za svoju glavu.
{26417}{26465}Takav neodgovorni postupak...
{26465}{26525}zahteva optuûnicu|za ozbiljan napad.
{26525}{26597}Pretpostavljam da je to znatno bolje|nego optuûnica za ubistvo...
{26597}{26645}o kojoj ste do malo pre razmiöljali.
{26645}{26705}Ja joö razmiöljam o njoj.|-Ma, dajte, inspektore.
{26705}{26789}Rekao sam vam öta se desilo.|Posle par minuta se oporavio,
{26789}{26849}prepredeno doöao do zakljuËka|da nije mrtav, 
{26849}{26945}i popivöi nekoliko brendija previöe|odbauljao kuÊi.
{26945}{27065}Jako mi je ûao öto nalazite da je sve|to jako smeöno, gospodine Wyke.
{27065}{27137}Moûda ne delimo|isto stanoviöte.
{27149}{27209}Stanite, samo malo!
{27209}{27279}Zaöto ne pokuöate da sagledate stvari|sa moje taËke glediöta?
{27291}{27363}Na neki naËin, Tindle i jeste bio provalnik.|Krao mi je ûenu, zar ne?
{27363}{27435}I time opravdavate to öto ste ga muËili,|a zatim i ubili, gospodine?
{27435}{27495}Naravno da ne! Kako ne vidite?|To je bila samo igra.
{27495}{27567}Samo krvava igra!|-Stvarno krvava, gospodine.
{27567}{27627}Samo sam postigao ono öto sam|nameravao i to je sve.
{27627}{27675}Moûda ste uspeli da ostvarite ubistvo, gospodine.|-Ne!
{27687}{27771}Ja verujem da jeste, gospodine.|-Ne! Rekao sam vam sve öto se dogodilo.
{27771}{27819}Imate li neöto protiva|da malo pogledam okolo, gospodine?
{27819}{27867}Moûete i da puzite na sve Ëetiri,|ako vam se tako svia.
{27867}{27939}Otvorite svoju kovertu|za pakovanje dlaka.
{27939}{27999}Skupljajte svoje dokaze|dok joö moûete.
{28155}{28203}Sad se pitam,
{28203}{28263}ako bih hteo da se|reöim Tindleovog tela,
{28263}{28347}gde bih ga stavio?
{28347}{28455}Moûda u mog dobrog prijatelja,|Veselog Jacka, mornara.
{28899}{28971}Veoma zabavno, gospodine.
{28971}{29019}Smem li da vas pitam,|kako ste to izveli?
{29019}{29103}Ne. Veseli Jack i ja|imamo naöe male tajne.
{29103}{29187}A smem li onda da vas pitam kako|ste napravili ove rupe u zidu?
{29199}{29259}Onu tamo,
{29259}{29307}i ovu ovde.
{29367}{29451}Meni liËe na rupe od metka, gospodine.|-Sasvim ste u pravu, inspektore.
{29451}{29499}I jesu.
{29499}{29547}Koliko sam vas shvatio,|gospodine,
{29547}{29595}rekli ste mi da ste|koristili Êorke.
{29595}{29703}Dva prava metka za poËetak trika| jedan Êorak za kraj.
{29703}{29751}Morao sam Tindlea da ubedim|u svoje ozbiljne namere.
{29751}{29823}O, razumem, gospodine.|Jedan Êorak.
{29835}{29919}Onda, hoÊete li mi, molim vas, pokazati, gospodine,|gde je stajao g-din Tindle kad ste ga ubili?
{29967}{30015}Mislite, kad sam se pravio|da ga ubijam?
{30015}{30087}Baö tako.|Onda, hoÊete li mi pokazati...
{30099}{30147}gde je taËno stajao|kad ga je metak pogodio?
{30147}{30219}Uporno vam govorim,|to nije bio pravi metak!
{30243}{30315}Tako je, gospodine.|Tako je.
{30315}{30363}Dobro, onda.|Gde je on bio...
{30363}{30447}kada ste opalili Êorak?
{30447}{30507}Stajao je,|ili, bolje reÊi, kleËao je,
{30507}{30579}ili joö preciznije,|öÊuÊurio se, ovde.
{30747}{30819}Kaûete, ovde, gospodine?|-Dva stepenika niûe.
{30891}{30999}Tu. -Da li ste bili blizu|g-dina Tindlea kada ste povukli oroz?
{30999}{31083}Da, vrlo. Stajao sam iznad njega,|zapravo, prislonio sam mu piötolj uz glavu.
{31083}{31143}Vidite, stvarno je osetio piötolj,
{31143}{31191}kada se na to doda|prasak pucnja,
{31191}{31239}trik je bio savröen.
{31575}{31647}Da li vam je potreban tradicionalni|alat vaöeg zanata, inspektore?
{32655}{32703}Laûna krv. gospodine?
{32787}{32835}Mislim da ne znam o Ëemu|priËate, inspektore.
{32835}{32931}Ovde, na ogradi,
{32931}{32979}ispod tepiha.
{33099}{33171}Sasuöena krv, gospodine.|-Krv?
{33171}{33219}Gde?
{33399}{33459}Ne dirajte.
{33459}{33507}Sasuöena krv, zar ne?
{33507}{33567}Evo i ovde ima joö.
{33567}{33627}Neko je prao ovaj tepih.|Vidite?
{33627}{33711}Duboko u vlaknima.|To je krv, gospodine.
{33783}{33831}Joö je vlaûna.
{33867}{33939}HoÊete li mi objasniti,|otkud ona ovde?
{33939}{33987}Nemam predstavu.
{33999}{34071}Tindle nije bio ni ranjen,|niti bilo kako povreen.
{34083}{34131}Pa, morate mi verovati!
{34179}{34275}Pravi meci...prava krv,
{34287}{34383}nije li doölo vreme da|prestanemo sa igrarijama, gospodine?
{34383}{34443}Pogledajte!|Pogledajte prozor!
{34455}{34539}Evo, moûete da vidite parËe stakla|koje je isekao ne bi li provalio.
{34551}{34623}A tamo dole, naÊiÊete i otisak|merdevina u leji za cveÊe...
{34623}{34719}i otisak ciöpele broj 75, ili ma öta je|veÊ, do avola, bio obuo.
{34719}{34767}Vidite, mogu da vam pokaûem!|-Tokom godina,
{34767}{34851}moje oËi su sasvim dobro istrenirane|da same vide stvari, gospodine.
{34851}{34911}Siguran sam da je tako, inspektore.|Samo pokuöavam da vam ukaûem na par Ëinjenica....
{34923}{34959}da potkrepim svoju priÊu,
{34971}{35055}kao öto je raznesen sef|koji sam vam pokazao u svojoj radnoj sobi...
{35055}{35163}kao korpu sa kostimima|koju ste pronaöli u podrumu.
{35163}{35235}Rekli ste da se gospodin Tindle|preruöio u klovna.
{35259}{35343}U korpi nisam video|kostim klovna.
{35343}{35403}Niti ste mi ukazali ni na...
{35403}{35463}onu humku u baöti,|je l' tako, gospodine?
{35463}{35511}Humku?
{35583}{35631}Kakva humka?
{35631}{35703}Ona tamo pored daljeg zida...
{35703}{35751}u senci kedra.
{35751}{35859}Ne vidim niöta.|-Pa, tamo je, u svakom sluËaju.
{35859}{35931}Video sam je pre|nego öto sam pozvonio kod vas.
{35967}{36051}Mislim da bi najbolje bilo|da odemo tamo i pogledamo.
{36327}{36375}Zajedno, gospodine.
{36855}{36939}Evo nas, gospodine.|Sad...
{36939}{37009}zar ne biste i vi rekli da je|ovde nedavno kopano, gospodine?
{37009}{37057}Kako bih ja to znao?
{37057}{37117}Moûda je to baötovan uradio.|Pitajte njega.
{37117}{37165}NaÊiÊete ga negde|kako pravi humke,
{37165}{37243}traûeÊi priliku da oklevete|svog poslodavca... to svi oni rade.
{37243}{37311}Sa moje taËke glediöta,|i iz mog liËnog iskustva znam...
{37311}{37371}da su baötovani|odliËni svedoci.
{37371}{37455}Spori su, metodiËni,|i uvek pozitivni.
{37455}{37563}Inspektore, sad mi je veÊ|dosta ove farse.
{37563}{37647}Da li stvarno mislite da bih bio tolika|budala da zakopam Tinldlea u svojoj baöti...
{37647}{37731}ostavljajuËi svu tu novu, prekopanu|zemlju da moûe svako da je nae?
{37731}{37791}Ako nas niste oËekivali,|gospodine, odgovor je - da.
{37791}{37899}Za par nedelja, sa malo zasaene,|nove trave i par lukovica,
{37899}{37983}bilo bi jako teöko otkriti|mesto gde je neöto kopano.
{37983}{38055}Mi, u policiji, jednostavno znamo...
{38055}{38127}koliko su ubice opsednute|svojim dvoriötima, gospodine.
{38127}{38211}»ovek nije bliûi ubiËinom srcu|u baöti nego bilo gde drugde na zemlji...
{38211}{38283}zar ne, inspektore?|-Ako izuzmemo spavaÊu sobu, gospodine.
{38295}{38355}Mislim da Êete se sloûiti|da je ona i dalje najomiljenija.
{38955}{39003}Ne moûemo promaöiti, Ëija|je ovo soba, eh, gospodine?
{39183}{39267}Moja ûena se tuöita,|ja se kupam.
{40023}{40107}C,c,c,c,c,c.|OdeÊa je sva zguûvana...
{40107}{40155}na dnu ormana.
{40155}{40215}To ne liËi na vas, gospodine.
{40215}{40323}O! Evo jednog zanimljivog|monograma... -''IW''.
{40371}{40431}Ili sam... O! Obrnuo sam|ga naglavaËke.
{40431}{40527}Aha... ''M.T.''
{40551}{40599}Dajte mi da vidim.
{40719}{40803}''Napravljeno po narudûbini i ûelji|u ulici Percy...
{40803}{40887}za gospodina Mila Tindlea,|12-og novembra.''
{40923}{41031}Recite mi, gospodine, kad je g-din Tindle|''odbaljuao'' od vas, kako ste vi rekli....
{41043}{41115}da li je odbaljuao go?
{41115}{41199}I da li je zatim bauljao go|ulicama kroz selo?
{41211}{41271}Presvukao se pre nego|öto je otiöao, u ovo odelo.
{41283}{41319}Da li joö tvrdite, gospodine,
{41331}{41415}da se gospodin Tindle preruöio|u klovna, dole, u podrumu?
{41415}{41475}Da!|-Joö jedan deo...
{41475}{41559}procesa poniûavanja, pretpostavljam.
{41559}{41631}A onda je neko morao|doneti ovo odelo...
{41631}{41691}ovamo iz podruma|i staviti ga u orman.
{41703}{41751}Ja sam.|-Zaöto?
{41763}{41847}Zato öto sam mislio da je bolje da ga stavim u orman|nego da stoji u starom i praönjavom podrumu.
{41847}{41895}Normalnije je.
{41895}{41967}Zguûvano na dnu |ormana? Zaöto?
{41967}{42063}Mislio sam da Êe se ubrzo predomisliti|i ponovo se presvuÊi, da samo blefira.
{42063}{42135}Ne, nije tako, gospodine.
{42147}{42219}Bacili ste ovu odeÊu|na dno ormana...
{42219}{42339}zato öto se znali da gospodinu Tindleu|viöe neÊe biti potrebna.... Nikad!
{42339}{42435}Tako je, gospodine, zar ne?|-Presvukao se pre nego öto je otiöao...
{42435}{42483}i obukao odelo|pre nego öto je otiöao!
{42483}{42543}Mislim da ste sve ovo poËeli...
{42543}{42615}baö onako kako ste mi rekli...
{42615}{42723}kao igru ne biste li|avolski prevarili gospodina Tindlea...
{42723}{42771}ali onda je poölo naopako.
{42771}{42867}TreÊi vaö hitac nije bio Êorak,|kao öto ste pretpostavili,
{42867}{42963}nego pravi metak koji je ubio|gospodina Tindlea na mestu,
{42999}{43095}poprskavöi pri tom|i stepeniönu ogradu.
{43095}{43191}Onda, kad ste shvatili|öta ste uradili...
{43191}{43287}jednostavno ste se uspaniËili|kao i hiljade ubica pre vas,
{43287}{43371}i zakopali leö u baöti.
{43371}{43419}Veoma glupo od vas je...
{43419}{43503}öto niste ni dobro oprali krv sa stepaniöta,|ni spalili odelo.
{43515}{43575}Kunem se, Tindle|je odavde otiöao ûiv!
{43575}{43647}Uz sav rizik da ispadnete|smeöni, gospodine,
{43647}{43695}biËe bolje da to|objasnite sudiji.
{43695}{43743}Vidite, postoji samo jedan naËin|da se sve ovo raöËisti.
{43743}{43803}Ako mislite da je Tindle|napolju u baöti, za ime Boûije,
{43803}{43875}zaöto ne odete i ne iskopate ga.|-Ne moramo da ga naemo, gospodine.
{43875}{43959}Ako ne naemo gospodina Tindlea|ispod sveûe iskopane zemlje....
{43959}{44019}to Êe nam samo znaËiti|da ste u svoj toj panici....
{44031}{44103}pomislili da ga tu zakopate, a onda se predomislil i| zakopali ga negde drugde.
{44103}{44187}Gde?|-To je sasvim nevaûno, gospodine.
{44187}{44235}PojaviÊe se pre ili kasnije.
{44235}{44307}A i  ako se ne pojavi,|nije mnogo vaûno.
{44307}{44367}Imamo vaöu ceduljicu kojom pozivate|gospodina Tindlea da doe,
{44379}{44439}Ëuli su se pucnji,|meci su napravili rupe,
{44439}{44499}krv je na stepeniötu|i tepihu,
{44499}{44595}njegovo odelo sakriveno u vaöem ormanu,|a on je nestao.
{44595}{44655}Kome je potrebno telo?
{44715}{44799}Gospodine, poite sa mnom.
{44811}{44859}Vreme je da poemo.|-Ne! Ne mogu da verujem...
{44859}{44919}Bojim se... Bojim se, gospodine,
{44931}{44967}da moram institirati.
{44979}{45015}Na kraju prilaznog puta|nalazi se policijski auto.
{45027}{45111}Baö me briga ako me Ëeka i cela flota policijskih|automobila, ja nikuda ne idem!
{45447}{45495}Nemojte mi praviti|probleme, gospodine.
{45495}{45579}Molim vas, ne oteûavajte mi.|-Hriste! Povredili ste mi ruku.
{45579}{45651}Ne ostavljate mi drugu moguÊnost.|Samo kad bi se malo smirili.
{45651}{45711}Mogu li da pozovem svog advokata?|To je moje pravo!
{45711}{45759}Moûete ga pozvati i iz|policijske stanice.
{45771}{45819}NeÊemo uraditi niöta|protivustavno.
{45879}{45927}Idemo, gospodine.|Ne oËajavajte.
{45939}{45999}Moûete da se provuËete|sa jedno sedam godina.
{45999}{46047}Sedam godina?
{46047}{46179}Sedam godina ûaljenja öto ste igrali glupu|igru koja je krenula kako ne treba.
{46179}{46287}Poötedite me sentimentalnosti. Niöta nije|krenulo naopako. Sve je iölo baö kako treba!
{46287}{46383}Tako vi mislite, je l' da,|gospodine?
{46383}{46431}Mi, stvarni policajci...
{46431}{46515}nismo toliko glupi,|kao öto nas nekad predstavljaju...
{46527}{46575}pisci poput vas.
{46575}{46635}Moûda nemamo monokle...
{46647}{46719}ni kuÊice u cveÊu,|niti idemo u lov na jelene...
{46719}{46767}nemamo ni troroge öeöire,
{46779}{46875}ali i pored svega smo|veoma efikasni, gospodine.
{46875}{46971}Izgleda da znate vraöki mnogo|o detektivskim priËama, inspektore!
{46971}{47079}Da. Svojevremeno sam ih|proËitao nekoliko, gospodine.
{47079}{47127}A u skorije vreme,
{47139}{47235}poËeo sam da verujem|da su detektivske priËe...
{47235}{47295}normalna razonoda|za plemiÊke umove, gospodine.
{47295}{47355}Ko ili öta ste vi,|o avola?
{47519}{47603}Detektiv inspektor Doppler,|gospodine.
{47687}{47759}Piöe se sa dva 'p',|'Dopple''.
{47783}{47891}öto, sasvim sam siguran|i sami znate,
{47891}{47963}znaËi ''dvojnik''...
{47963}{48035}na nemaËkom.
{48035}{48119}A za one Ëiji se umovi...
{48119}{48203}bave takvim stvarima,
{48203}{48263}to je u stvari...
{48263}{48311}anagram...
{48311}{48383}reËi ''plodder'' (vredan).
{48431}{48491}Tako...
{48503}{48587}inspektor Plodder...
{48587}{48695}postaje inspektor Doppler,
{48767}{48839}ako shvatate,|öta sam hteo da kaûem...
{48959}{49007}gospodine.
{49115}{49199}Milo!|-Taj sam!
{49199}{49259}Govno jedno!
{49355}{49391}Grazie mille.
{49403}{49475}Ti, najveÊe, pokvareno,
{49475}{49547}kopile na svetu, Milo!
{49547}{49595}Preljubazan si!
{49799}{49907}Ne mogu reËi da nije dobro izvedeno.|Bilo je neverovatno lepo.
{49907}{49979}Bilo je vrlo... bilo je brilijantno.
{49979}{50039}Uzgred, zaboravio si|da izvadiö svoje levo oko.
{50159}{50195}Vidiö kako on zna|da sam smeöan.
{50207}{50267}''Uzmi piÊence, Milo.'' Mmm.
{50279}{50315}Izvini.|Posluûi se sam.
{50327}{50399}Moram prvo da se umijem.|Sav sam prekriven öminkom i ovom gumom.
{50411}{50495}Moûeö u kuhinji.|-Ne, radije idem u glavno kupatilo.
{50759}{50795}Veoma ste zdravi, gospodine.
{50807}{50879}éiveli.
{51251}{51323}Moram reÊi,
{51323}{51407}moram da ti Ëestitam, Milo.
{51407}{51455}Bilo je prvoklasno.
{51455}{51539}Stvarno si uspeo da me|prevariö na kratko.
{51539}{51599}Na kratko?
{51671}{51767}Pa, u stvari, sve vreme,|priznajem.
{51767}{51839}Ali, postao sam malo sumnjiËav|skroz pri kraju, znaö?
{51839}{51911}Malo si preterao na kraju,|mislim.
{52223}{52295}äta misliö o mojoj izvedbi?
{52295}{52391}Patnja nevinog Ëoveka,|uhvaÊenog u zamku posrednim dokazima.
{52391}{52511}To nije bila izvedba,|-Naravno da jeste. Moralo je sve biti uverljivo.
{52511}{52595}OËigledno, uspeo sam.
{52595}{52691}Ti stvarno ne moûeö da podneseö|poraz, je l'da, Andrew?
{52691}{52763}Sva te gluposti|koje si prodao Doppleru....
{52763}{52811}o plemstvu koje|gubi dostojanstveno.
{52811}{52859}Isuse.
{52859}{52919}Pa, rekao sam ti,|ti, ti si bio jako dobar.
{52919}{52967}Stvarno dobar.
{52979}{53027}Svideo mi se tvoj|inspektor Doppler.
{53027}{53075}Drago mi je öto vidite....
{53075}{53135}naöu malu maskaradu|na taj naËin, gospodine.
{53135}{53183}Tvoja öminka je bila vraöki dobra...|prvoklasna.
{53183}{53231}Nisi se sam naöminkao, zar ne?
{53231}{53315}Ja sam frizer, ne zaboravi.
{53315}{53411}Imam prijatelje meu...|uh, umetnicima.
{53447}{53495}Pretpostavljam da si se uöunjao...
{53507}{53555}uvukao ovde juËe|dok sam bio u Salisburyju.
{53555}{53651}Da.|-Ubacio svoje odelo u moj orman...
{53651}{53759}i poprskao malo ûrtvene krvi|po stepeniötu, hmmm?
{53771}{53867}To nije bila moja krv, znam|da Êe ti laknuti kad to Ëujeö.
{53867}{53927}Uzeo sam je sa|svinjske dûigerice.
{53927}{53999}Pretpostavljam da si mogao|da upotrebiö i dago vino.
{53999}{54059}O, sad bi mi prijalo jedno piÊe.|-Naravno.
{54059}{54143}Dûin i tonik, mislim.|-Nesumnjivo si ga zasluûio, dragi moj prijatelju.
{54143}{54191}Idemo.
{54239}{54311}Znaö, nisam ti joö|Ëestitao...
{54323}{54359}na tvojoj... igri.
{54371}{54419}Oh?|-Bila je jako dobra.
{54419}{54479}Stvarno to misliö?|Dobro.
{54479}{54539}Moram priznati da sam i ja sam|bio priliËno oduöevljen.
{54539}{54599}Reci mi, da li si stvarno pomislio...
{54599}{54659}da ti je doöao|poslednji trenutak na zemlji?
{54659}{54695}Da.
{54707}{54755}Nisi ljut, zar ne?
{54803}{54863}Ljut? Ne razumem.
{54863}{54911}To si ti rekao.
{54911}{55019}Vidiö, kao öto sam ti objasnio,|dok si glumio inspektora Dopplera,
{55031}{55115}morao sam da testiram tvoj karakter,|da vidim da li si, kao öto sam i sumnjao,
{55115}{55175}stvarno Ëovek kao ja.
{55175}{55235}»ovek koji voli da se igra?
{55247}{55319}TaËno.|-I, jesam li?
{55319}{55379}Nema nikakve sumnje.
{55379}{55451}Uporedi svoje iskustvo|od ovog vikenda...
{55451}{55523}dragi moj Milo, sa bilo kojim|trenutkom iz svog ûivota.
{55523}{55571}Sad, ako budeö iskren prema samom sebi,|moraÊeö da priznaö...
{55571}{55667}da si u mom druötvu proûiveo viöe|nego sa bilo kim drugim.
{55667}{55751}Viöe Ëak nego i sa Margueritom.
{55751}{55835}E pa, nas dvojica znamo kako je|igrati igru, ti i ja.
{55871}{55919}To je retkost.
{55919}{55979}Dva Ëoveka, spojena sluËajem,
{55979}{56039}sasvim ista, imaju hrabrosti...
{56051}{56087}i talenta...
{56099}{56207}da od ûivota prave konstantnu|öaradu malih smicalica,
{56207}{56279}veselih pronalazaka,
{56279}{56363}da se suoËe|sa njegovim prazninama...
{56375}{56459}i njegovim strahovima igrom.
{56471}{56555}Samo igrom.
{56603}{56651}Da li si zaboravio na|momka koji je iskoËio iz ostave...
{56663}{56735}i koji ne zna|gde mu je mesto?
{56735}{56807}Mi smo iz razliËitih svetova,|ti i ja, Andrew.
{56807}{56855}U mom, nema vremena...
{56855}{56951}za male smicalice i|vesele pronalaske.
{56963}{56999}Nema ni pauze za Ëaj.
{57035}{57119}Jedina igra koju|igramo zove se Opstanak...
{57131}{57179}ili smo gotovi.
{57179}{57251}Ako ne pobeujeö|onda je ni ne zavröavaö.
{57251}{57299}Gubitnik gubi sve.
{57383}{57419}Ti verovatno ne moûeö|to da shvatiö.
{57431}{57503}Shvatio ili ne, niöta od toga öto si ispriËao|ne opovrgava moje stanoviöte.
{57503}{57599}Pogledaja samo naËin koji si izabrao da|mi uzvratiö... izigravajuÊi inspektora Dopplera.
{57623}{57671}Jednostavna osveta.
{57671}{57719}Uzvratio sam|kako si zasluûio.
{57767}{57851}Svali ûabar zna to da uradi.|-Pa, da li je tvoja Ëast time zadovoljena?
{57851}{57899}Nereöeno?|Jedan jedan u setovima?
{57899}{57947}''»ast''?
{57995}{58043}Joö jedna od tvojih reËi.
{58079}{58139}Znam...
{58139}{58187}da si me razgolitio...
{58199}{58247}do koske.
{58247}{58331}Znam...da si me u stvari....
{58331}{58391}preplaöio na smrt.
{58427}{58499}Stajao sam na tim stepenicima,|gledao dole...
{58511}{58595}shvatajuÊi da su|moj...moje dugme na rukavu, 
{58607}{58643}ograda,
{58655}{58727}nokat na domalom prstu...
{58727}{58835}apsolutno poslednje|öto Êu videti...
{58835}{58895}ikad viöe.
{58895}{58967}Onda sam Ëuo...
{58967}{59051}zvuk... svoje sopstvene smrti.
{59051}{59111}To promeni Ëoveka, Andrew.
{59111}{59195}Veruj mi, za to si mi|joö duûan.
{59207}{59267}ProÊiÊe. To je samo öok, dragi|moj prijatelju. Evo, dozvoli mi...
{59267}{59351}Ja Ëak ni ne ûelim|da izjednaËim rezultat!
{59351}{59471}I nemoj mi viöe priËatei te tvoje 'jedan jedan|u setovima', 'vaûno je uËestvovati' gluposti!
{59531}{59579}Moj otac je samo|uËestvovao...
{59579}{59663}i njegov otac|i njegov otac.
{59663}{59747}Sve sami gubitnici|ma koliko daleko iöao!
{59783}{59843}Pa, sa mnom|se to zavröava!
{59843}{59903}Sa mnom, Tindleovi|poËinju da pobeuju!
{59951}{60011}Ostali gube.
{60107}{60155}Ti, na primer.
{60191}{60251}Ja? äta gubim?
{60263}{60299}Novu igru...
{60311}{60395}Moj izbor, moja pravila,|igra se na moj naËin.
{60407}{60479}I, da bih poËeo,|morao sam nekoga da ubijem.
{60515}{60575}Ubio si nekoga?|-Ubio sam nekoga.
{60575}{60647}PoËinio ubistvo.|-äaliö se.
{60683}{60731}Ni najmanje.
{60731}{60815}To je prava igra|i pravo ubistvo.
{60815}{60935}Nema apsolutno nikakve svrhe|opet igrati samo prdstavu. Slaûeö se?
{60947}{61043}Apsolutno.|-Viöe se ne pretvaramo.
{61055}{61139}To Êemo prepustiti amaterima...|igraËima dûentlmenima kao öto si ti.
{61139}{61211}Uh, vidiö, Milo, moûda|neki drugi put...
{61223}{61319}Ne mogu da Ëekam!|-Dobro. Dobro.
{61319}{61427}IgraÊemo tvoju igru.|Sad mi reci, koga si ubio?
{61427}{61511}Koga? Koga?
{61511}{61559}Do koga ti je, osim za sebe,
{61571}{61667}najviöe stalo?
{61667}{61775}Da li je to tvoja|devojka, Tea?
{61775}{61835}MoguÊe.
{61835}{61907}Zaöto?|-Ona je ta.
{61967}{62015}Ubio si Teu?
{62015}{62063}Nju, Ëije kobaltne oËi...
{62075}{62171}koje kriju tajnu öumskih|jezera Finske.
{62171}{62219}Ja sam ih zatvorio.
{62267}{62339}Ti...|-Da, zadavio sam je.
{62351}{62411}baö tu, na onom Êilimu.
{62411}{62507}Ja sam je zadavio.|I...o. da,
{62507}{62567}prvo sam je tucao.
{62639}{62711}Silovao si i zadavio...
{62711}{62759}Ne, nisam je silovao.
{62759}{62843}Ona je to ûelela.|-Laûeö!
{62891}{62963}NeÊeö me nasamariti|tako jeftinim priËama.
{62963}{63023}Iskreno, Milo, mislio sam|da si mnogo bolji.
{63023}{63071}Kad sam, juËe|bio ovde...
{63071}{63143}da stavim krv|i odelo za starog Dopplera,
{63143}{63215}Tea je doöla|traûeÊi tebe.
{63215}{63299}Tako sam se ''malo bacio na udvaranje'',|kao öto si ti jednom rekao,
{63299}{63431}pa smo malo plesali, obraz uz ubraz,|uz ove tvoje bezvezne, stare velike orkestre.
{63431}{63491}Reci mi, ko bi joö, sem tebe|Ëuvao te ploËe?
{63491}{63551}U svakom sluËaju,|upalilo je.
{63551}{63635}Nju je zasvrbelo, a ja imam|Ëime da je poËeöem, zar ne?
{63635}{63695}Posle toga je zaspala,
{63695}{63755}i tada sam to uradio,|staro momËe.
{63755}{63827}Zavrnuo sam joj öiju.
{63827}{63887}Ona je bila ispod one,|sveûe iskopane humke...
{63887}{63971}koja je tako privukla starog Dopplera.|-''Bila''? Zar viöe nije?
{63971}{64031}Ne, premestio sam je.|-Gde?
{64031}{64139}U poplavljenu, öljunkovitu jamu?|Napuötenu Fu Manchu fabriku lepka?
{64139}{64187}Sad viöe nije ni|bitno gde.
{64187}{64247}Policija Êe je veÊ pronaÊi ako krene pravim|putem, a moûda su je veÊ i naöli.
{64247}{64307}Policija?|-Da.
{64307}{64355}Telefonirao sam im|pre, od prilike, jedan sat,,,
{64355}{64427}i zamolio ih da se|naemo ovde u 10 sati.
{64427}{64499}Trebalo bi da stignu za,|oko, 15 minuta.
{64511}{64571}Siguran sam da Êe|tako i biti.
{64571}{64703}Predvoeni, bez sumnje, neustraöivim|inspektorom Dopplerom. -Ne.
{64703}{64763}Ovaj put, to Êe biti|pravi policajac.
{64763}{64823}Detektiv vodnik Tarrant,|tako se zove.
{64823}{64895}Proveri, ako ûeliö.
{64907}{64967}Svaöta sam mu|ispriËao o tebi, Andrew.
{64967}{65051}Rekao sam mu da znam da si|Ëovek koji je opsednut igrama....
{65063}{65111}i koji ubistvo smatra|prefinjenom umetnoöÊu.
{65111}{65207}Tvoj ûivotni cilj, rekao sam,|o kome veoma Ëesto priËaö je...
{65207}{65303}da izvröiö pravo, stvarno ubistvo,|sakrijeö telo,
{65303}{65387}a onda da ostaviö tragove, koji vode do tebe,|razbacane po celoj kuÊi,
{65399}{65459}ubeen da ih jadna policija,|skromne pameti...
{65459}{65507}nikad neÊe prepoznati.
{65519}{65615}''Molim vas, gospodine, Andrew Wyke se|neÊe smiriti dok ne izvröi pravo ubistvo...
{65627}{65687}i dok, sve vas policajce,|ne napravi budalama.''
{65687}{65771}Ma daj! Reci to bilo kom|obiËnom vodniku, mastiljari,
{65771}{65831}i zaËas Êeö se naÊi u|ludaËkoj koöulji.
{65843}{65915}Pa, u stvari i ne baö.
{65915}{65987}Rekao sam im Êe im,|ako mi ne veruju,
{65987}{66083}samo jedan pogled na tvoje knjige|i nameötaj u tvojoj kuÊi,
{66083}{66155}potvrditi sve öto sam im rekao|o tvojim opsesijama.
{66263}{66323}Nastavi.
{66323}{66407}Takoe sam im rekao|da je, pre dva dana,
{66407}{66527}tvoja devojka doöla kod mene jako potreöena,|i da mi je rekla da si je optuûio kako...
{66527}{66599}ima joö ljubavnika|i kako si joj pretio da Êeö je ubiti.
{66599}{66671}Kladim se da su poverovali|u svaku tvoju reË.
{66671}{66731}Na kraju, da, jesu.
{66815}{66875}Dragi moj deËaËe.
{66875}{66935}Stvarno mi je jako drago öto si,|uprkos svom poricanju,
{66935}{66995}zahvaÊen duhom igranja,
{67007}{67067}i potrebom, kako ti to vidiö,|pobede po svaku cenu.
{67067}{67163}Ali iskreno, previöe se trudiö...
{67163}{67235}da odjednom porasteö.
{67439}{67511}Alo... alo, Joyce?
{67511}{67559}Andrew je.
{67559}{67619}Mogu li dobiti Teu?
{67691}{67739}Ona je... öta?
{67795}{67843}Zadavljena...
{67891}{67963}Pa, kad se to desilo?
{67963}{68011}Kad... Kad je to bilo?
{68011}{68071}Gde su je pronaöli?
{68071}{68119}äta?
{68119}{68179}Uh, Joyce, uh.
{68179}{68227}Ne razumem öta...
{68227}{68275}Pokuöaj da se kontroliöeö....
{68311}{68371}äta?
{68371}{68431}Policija...
{68431}{68479}se raspitivala...
{68503}{68587}O, moj... boûe.
{68707}{68779}Trebalo je da mi poverujeö.
{68779}{68839}A sada Êemo|da se igramo.
{68839}{68947}Za malo viöe od 30 minuta,|stiÊiÊe zakon.
{68947}{69007}A onda Êe se suoËiti|tvoj briljijnatni um...
{69007}{69055}protiv njihovih vrednih.
{69067}{69139}U ovoj sobi su sakrivena...
{69139}{69211}Ëetiri dokaza koji te okrivljuju...
{69211}{69271}za Teinu smrt,
{69271}{69367}ukljuËujuÊi , kao poslednji znak|prezira prema policiji,
{69379}{69415}i samo oruûje ubistva.
{69451}{69487}Reci, jesi li spreman?
{69559}{69619}Ne moûeö od pravog ubistva|napraviti igru.
{69619}{69679}VideÊemo.
{69691}{69775}Ne zaboravi: Ëetiri predmeta,
{69775}{69835}predmeta koje ti neÊeö naÊi|ali policija sigurno hoÊe.
{69835}{69907}Svi se nalaze na otvorenom.
{69907}{69967}Prvi predmet je...
{69967}{70027}kristalna narukvica.
{70027}{70087}Ne ona...|-Da.
{70099}{70171}Otkinuo sam je sa njenog zgloba.|Ima i, uh, posvetu...
{70171}{70255}Dobro, dobro,|znam öta je napisano.
{71213}{71249}éeliö li da ti malo pomognem?|-Da, proklet bio!
{71261}{71321}C,c,c,c. Tako brzo.
{71321}{71381}Pa, gde mi je spisak?
{71381}{71453}Oh, Boûe.|-Evo ga.
{71453}{71585}''Svaki Ëovek i jednim okom,|moûe videti ono ispred sebe,
{71585}{71657}ali samo oko oötro, a ne sneno
{71657}{71705}vidi ono nevieno.''
{71705}{71765}Rekao si da je|sve na otvorenom!
{71765}{71837}Pa, zar nisam ja onda jedan|prepredeni lukavko?
{71837}{71909}Ne dajeö mi nikakvu öansu,|kopile jedno!
{71909}{71969}Hajde, misli, misli, misli.
{71969}{72053}Na otvorenom a ipak se ne vidi.|Moûe biti i optiËka varka.
{72113}{72209}Videti ono öto se|ne vidi golim okom.
{72209}{72257}To je... mikroskopski malo!
{72257}{72353}Vidi se samo jedan deliÊ.|To je to!
{72353}{72413}Tradicionalni alat vaöeg|zanata, inspektore.
{72557}{72605}Zaöto se ne zapitaö...
{72605}{72689}odakle bi tvoj Ëovek, Merredick,|poËeo sa istragom.
{72701}{72773}Merridew! St. John Lord Merridew!
{72773}{72821}Miran. Ostani miran.
{72821}{72869}Sad, razmisli. äta je zanimljivo|kod kristala?
{72869}{72977}Teöki, sjajni, providni.
{72977}{73061}Gledaö kroz njih|ali ih ne vidiö.
{73061}{73109}To je trik!
{73109}{73193}Jedino mesto na kome se moûe|sakriti providan predmet...
{73193}{73277}tako da bude nevidljiv|a ipak se moûe reÊi da je na otvorenom...
{73277}{73373}je na ili u drugom providnom|predmetu kao...kao...
{73601}{73661}Jasno kao kristal.
{73661}{73733}Ali ja... Ne moram da|uniötim ovo, zar ne?
{73733}{73805}Mogla je bilo kad da je ostavi ovde.|-Tako je.
{73805}{73853}Idemo dalje. äta je sledeÊe?
{73853}{73925}SledeÊi predmet te|mnogo viöe optuûuje.
{73925}{73973}Evo jedne male zagonetke|za koju sam siguran...
{73973}{74033}da te je neka od tvojih dadilja| nauËila.
{74033}{74105}''Mi smo dva brata,|veliki teret nosimo,
{74105}{74165}i straöno nas pritiska.
{74177}{74237}Iskreno reËeno|puni smo ceo dan...
{74237}{74285}a prazni kad krenemo na odmor.''
{74285}{74333}Znam to!|Znam to!
{74345}{74405}Uh, samo minut.|''Puni ceo dan, prazni kad krenemo...''
{74405}{74453}Znam! Par cipela!
{74453}{74537}U ovom sluËaju, jedna leva|ûenska crna cipela, broj 37.
{74597}{74657}Druga, ne moram ni da napominjem,|je i dalje na Teinoj nozi.
{74657}{74729}Boûe! Jadna Tea!
{74825}{74909}Jadna Tea?|To je veÊ bolje.
{74909}{74969}Da li znaö da je to prvi|znak ûalosti koji si pokazao...
{74969}{75041}od trenutka kad si|saznao da je mrtva?
{75041}{75149}Ne bi je stavio ovde negde,|niti gore meu Margueritine cipele.
{75149}{75245}Bilo bi oËigledno.|-Tvoj bol je dirljiv.
{75245}{75329}Ti si stvarno ''so na zemlji'' (veoma pristojan),|znaö li to, Andrew?
{75329}{75401}Uzgred budi reËeno, to ti je trag,|ako te baö zanima.
{75401}{75473}''So na zemlji''?|Zemlja? Zakopana je!
{75473}{75545}Ne, da probam drugo.|So. So.
{75545}{75617}So i biber.|äalitra. Slana voda.
{75617}{75701}Slanik!|U podrumu je! (Saltcellar, cellar).
{76527}{76587}Stvarno si se uzbudio,|zar ne, Andrew?
{76635}{76683}»ak i ako je ulog u igri koju igraö...
{76683}{76743}tvoj sopstveni ûivot,
{76743}{76791}ti si se praktiËno predao igri.
{76827}{76899}Cipela! Cipela.|Pitao sam se...
{76899}{76983}''da sam ja crna cipela,|gde bih se sakrio?
{76983}{77055}Da sam crn kao tvoj öeöir...
{77055}{77139}Da sam crn|kao kec pik...
{77139}{77199}Da sam crn kao...''|-Ugalj!
{77259}{77307}To je to! Kopile!
{77571}{77619}Pokvareni kzËkin sine!
{77715}{77775}Polako se zagrevaö...|i postajeö sve crnji!
{77799}{77859}Mora da je ovo jedno|sasvim novo iskustvo za tebe.
{77871}{77943}Pretpostavljam da u tvojim knjigama nema|baö mnogo mesta za ''crne'', zar ne?
{77943}{78027}Osim za Ëudne mraËne|tipove koji prevrÊu oËima...
{78027}{78147}i pokuöavaju da se poistovete sa|iskompleksiranim jeöama, nauljenim Levantincima,
{78147}{78195}i ostalima.
{78571}{78619}O, ûao mi je,|baö je prljava.
{78619}{78715}To je samo zemlja...|sa Teinog prvog groba iz tvoje baöte.
{78895}{78967}Nije loöe. TaËno na vreme,|koliko vidim.  -Jedva.
{78967}{79063}Pa, öta je sledeÊe?
{79063}{79147}Ne znam öta nalaziö|tako prokleto zabavno u svemu ovom?
{79147}{79195}Zaöto se, do avoka,|smejeö, a?
{79255}{79339}Siguran si da ti je dobro?|-Da, odliËno sam, Jack.
{79339}{79411}Jack?|Ti si sasvim skrenuo.
{79411}{79459}Treba da mi kaûeö|sledeÊi trag.
{79459}{79519}Kod Veselog Jacka!|Nalazi se na mornaru!
{79519}{79603}Tako je!|Baö je tamo.
{79603}{79663}Ali ovaj put, 
{79663}{79747}ti neÊu reÊi...|öta je to.
{79747}{79795}Dobro.
{80923}{80983}Gleda te razoËarano.
{80983}{81043}Ali, ovaj put|se ne radi o smehu.
{81055}{81091}Ili da?
{81163}{81223}Uradi to joö jednom?
{81307}{81379}Boûe moj, do sad mi nikad|nije namigivao.
{81763}{81847}Pretpostavljam da su druge trepavice|na jednom oku jadne Tee.
{81847}{81919}NeÊe joj nedostajati.|Oba oka su joj zatvorena.
{81979}{82027}Koliko joö vremena?
{82027}{82123}Imaö joö oko pet minuta.|Jedva dovoljno, rekao bih.
{82123}{82183}Preostala je joö jedna stvar, mislim...|oruûje kojim je izvröeno ubistvo.
{82195}{82267}Zadavio si je tamo ali Ëime?|Konopcem? OpasaËem?
{82267}{82351}äalom?|-To joj je duboko uölo u vrat, Andrew.
{82387}{82435}Morao sam da vadim|da ga ne izgubim.
{82435}{82531}PlatiÊeö zbog ovoga, obeÊavam ti,|sadistiËki, prokleti ûabare.
{82531}{82603}Nadam se da te nisam|dobro Ëuo.
{82699}{82771}Siguran sam da ti|treba joö malo pomoÊi.
{82771}{82855}Ne bih voleo da moram da poËnem|sa teökim italijanskim zagonetkama...
{82855}{82915}punim prevara|i dvosmislenosti.
{82915}{82963}Dobro.|Dobro!
{83011}{83083}Kako je nekoliko ûabara|primeÊivalo s vremena na vreme,
{83083}{83143}non e oro tutto che scintilla.
{83143}{83203}Da li je to trag?
{83203}{83263}Reci mi, onda, joö jednom|tu prokletu stvar.
{83263}{83311}Non e oro tutto che scintilla.
{83323}{83359}Ne. Joö jednom,|molim te.
{83371}{83503}Non e oro tutto che scintilla.
{83563}{83611}Que hora?|Koliko je sati?
{83623}{83671}Ne, uh...
{83671}{83731}Oro. Oro.
{83743}{83779}Zlato! Zlato!
{83779}{83851}Oro tutto.|Sve zlatno.
{83851}{83959}Uh, scintilla. Scintilla.|Scintillare.
{83959}{84019}Uh, zlato, Uh, scintillates...
{84019}{84067}s-s-sija....
{84079}{84127}Nije zlato sve öto sija!
{84127}{84175}Tako Êe uvek|biti u Engleskoj.
{84175}{84247}Zadavio si je neËim|zlatnim i sjajnim
{84319}{84403}äta... öta je to?|MuziËki trag. Dobro.
{84403}{84463}Sada, hmmm, zlatne, uh...|Zlatne note. Zlatna skala.
{84475}{84511}Zlatnia.. zlatna ûica.
{84523}{84583}To je ûica! Zadavio si je|zlatnom ûicom! 
{84583}{84715}I, kao i svako drugi, sakrio si je iza|trake za zvonce. Ne, doavola, nisi.
{84835}{84895}''Sve se menja''.|U stara vremena...
{84895}{84955}U stara vremena,|kratak pogled na Ëarape...
{84967}{85027}smatran je öokantnim...|»arape!
{85027}{85075}Gde bi ti|sakrio Ëarape?
{85075}{85123}Pa na...nogama.
{85123}{85171}Moge... zlatne noge!
{85219}{85291}Ne posoji zlatna noga|u ovoj prokletoj kuÊi.
{85291}{85363}Da li... je u ovoj sobi?
{85363}{85423}Non capisco.
{85423}{85495}Oh!
{85495}{85543}Kopile!
{85603}{85687}U stara vremena,|kratak pogled na Ëarape...
{85687}{85747}smatran je öokantnim...|»arape!
{85747}{85795}Sad, sam Bog zna,
{85795}{85855}sve se menja.
{85855}{85927}Svet je sasvim|poludeo danas
{85927}{85959}i dobro...
{85960}{86005}SUVIäE LAKO|SKLAPATE PRIJATELJSTVA.
{86227}{86275}»-Ëini mi se da sam|neöto Ëuo.
{86479}{86551}Andrew? Andrew!
{86551}{86647}äta je?|-Stigli su. Policija je doöla.
{86731}{86803}Izgleda da ti je doöao kraj.|VeÊ su sasvim blizu kuÊe.
{86803}{86875}Zadrûi ih napolju.|-Da zadrûim policiju?
{86875}{86995}To se, jednostavno, ne radi,|staro momËe. Ali, ipak, pokuöaÊu.
{86995}{87067}Samo joö malo!
{87067}{87139}Zamajavaj ih nekako!|Molim te!
{87151}{87187}Zapamti:
{87199}{87235}''U stara vremena,
{87247}{87343}kratak pogled na Ëarape.''
{87379}{87427}Gospodine Tindle.
{87427}{87487}Stari dani.|-Nisam vas oËekivao ovde, gospodine.
{87487}{87535}Dobro veËe, vodniËe Tarrant.|-Kratak pogled...
{87547}{87595}U stara vremena.
{87595}{87655}Pre hulahopki, öta?|Najlon.
{87655}{87703}Pre najlona, öta?
{87715}{87763}Svila.
{87763}{87859}I öta onda? äta... joö?
{88039}{88075}Sat. (lice)
{88171}{88291}»arape su imale lice.
{88291}{88339}U stara vremena.
{88579}{88627}Kratak pogled.
{88699}{88771}Sad ga vidiö|sad ga ne vidiö.
{90323}{90383}Zaöto ne bih|ja uöao unutra?
{90707}{90755}Pustite me samo da mu|kaûem da ste ovde.
{90875}{90923}Andrew?
{90923}{91007}Mogu li da ti predstavim detektiva|vodnika Tarranta i pozornika Higgsa?
{91007}{91115}O, da, naravno!
{91115}{91199}Uite, gospodo.|Uite. Izvolite.
{91199}{91271}Ja sam...
{91367}{91427}Ili da kaûem...
{91427}{91547}inspektora Vrednog|i pozornika Novajliju.
{91643}{91751}Hvala vam, vodniËe.|U stvari, neÊete nam biti potrebni.
{91751}{91847}U redu, gospodine. Bolje spreËiti|nego leËiti. To ja uvek kaûem, gospodine.
{91883}{91955}Laku noÊ, vodniËee.|Laku noÊ, gospodine.
{91991}{92075}Laku noÊ, pozorniËe.
{92075}{92123}Laku noÊ, gospodine.
{92615}{92711}Prvo, pretpostavljam da te interesuje|öta je bilo sa Teom.
{92711}{92819}Ona je stvarno zvala juËe dok|sam ja nameötao scenu za Dopplera,
{92819}{92891}i ja sam joj ispriËao za trik koji|si izveo sa piötoljem.
{92891}{92939}Nije bila nimalo|iznenaena.
{92939}{93011}Nije, jer jako dobro zna|kakve igre voliö da igraö...
{93011}{93095}igre u kojima uûivaö|poniûavajuÊi druge ljude.
{93143}{93191}Objasnio sam joj da...
{93191}{93263}ûelim da odigram igru|i da se izjednaËim sa tobom,
{93263}{93335}pa sam je zamolio da mi|pozajmi Ëarapu, cipelu,
{93335}{93443}laûne trepavice i|onu narukvicu...
{93443}{93491}koju si joj tu kupio.
{93503}{93575}Bila je sreÊna öto|moûe da pomogne,
{93575}{93623}kao i njena sustanarka, Joyce.
{93743}{93803}Zaöto sad ne telefoniraö Tei?
{93839}{93887}Sad Êe razgovarati|sa tobom.
{93983}{94067}Ali onda, nemaö baö mnogo toga|da joj kaûeö, zar ne?
{94115}{94175}Ona i nije tvoja ljubavnica, je l' da?
{94247}{94295}Rekla mi je...
{94295}{94355}da vas dvoje niste|bili zajedno...
{94355}{94403}viöe od godinu dana.
{94427}{94475}I joö mi je rekla...
{94487}{94583}da si ti, praktiËno,|impotentan.
{94583}{94631}U stvari, da nisi ni blizu,
{94643}{94691}da te selektor izabere|za sledeÊu Olimpijadu.
{94727}{94775}Upozorio sam te, Andrew.
{94823}{94871}Ja se ne igram|zabave radi!
{94919}{94967}NaroËito ne...
{94979}{95027}igre poniûavanja.
{95087}{95147}Previöe znam o tome.
{95351}{95399}Gde Êeö?
{95435}{95471}Idem po Margueritinu bundu.
{95519}{95567}Ona se ne vraÊa?
{95567}{95615}Ne.
{95807}{95867}éivim...
{95867}{95915}onako kako|ûelim da ûivim.
{95915}{95999}Znaö, razmiöljao sam o|onom piscu o kom si mi priËao,
{96011}{96059}i moje miöljenje je da...
{96071}{96155}su tvoje detektivske priËe|normalna razonoda...
{96155}{96215}snobovskog, zastarelog,
{96215}{96287}podlog uma koji mrzi ûivot.
{96311}{96359}A sad idem|po bundu.
{96767}{96839}VideÊeö.
{96839}{96887}VideÊeö.
{96959}{96995}Inspektore,
{97031}{97103}radio sam u svojoj|radnoj sobi....
{97103}{97151}kad sam Ëuo|nekakvu buku.
{97199}{97307}Uzeo sam svoj revolver...
{97307}{97367}i doöao ovamo...
{97367}{97415}da vidim öta je bilo.
{97451}{97523}Zatekao sam ovog|mladog Ëoveka...
{97523}{97595}kako trËi niz stepenice...
{97595}{97703}sa bundom moje ûene|prebaËenom preko ruke.
{97715}{97775}Viknuo sam mu|da stane,
{97775}{97847}ali on je, neobraÊajuÊi paûnju,
{97847}{97931}potrËao prema vratima,
{97931}{98003}nadajuÊi se|da Êe pobeÊi.
{98003}{98099}Naravno, opalio sam.
{98123}{98195}Ciljao sam nisko.
{98195}{98255}Verujte mi, inspektore,|stvarno jesam.
{98255}{98339}Meutim desilo se|ono najgore.
{98373}{98433}Ubio sam ga.
{98541}{98589}U redu je, gospodine.
{98589}{98637}Nemojte se|bespotrebno uzbuivati.
{98649}{98709}To je moglo|svakom da se desi.
{99069}{99117}Ne mogu de|pustiti da odeö.
{99153}{99225}Kako to misliö?
{99225}{99309}Izaeö odavde...|IspriËaö svima,
{99309}{99357}to je prosto nemoguÊe.
{99357}{99453}Ko... kome bih|ja to ispriËao?
{99465}{99501}Koga bi to|interesovalo?
{99513}{99621}I jedna osoba bi bila previöe, Ëak i Marguerite.|Posebno Marguerite.
{99621}{99679}I öta Êeö sad|da uradiö, Andrew?
{99679}{99763}UbiÊeö me?|Opet Êeö igrati igru 'Provalnik'?
{99763}{99835}Baö tako!|-Ovaj put neÊe moÊi.
{99835}{99931}Ne. Baö se pitam,|zaöto ne?
{99931}{100027}Zbog onoga öto se stvarno desilo|kada sam otiöao odavde u petak uveËe.
{100039}{100135}Oh. äta se|stvarno desilo?
{100135}{100195}Stvarno sam|odbauljao kuÊi...
{100195}{100315}oöamuÊen, prljav i|poniûen.
{100315}{100375}Cele noÊi|nisam oka sklopio.
{100423}{100543}Ujutru sam otiöao u|policijsku stanicu...
{100543}{100615}i ispriËao im|öta si mi uradio.
{100615}{100663}Jedan od njih,|detektiv vodnik Tarrant...
{100663}{100747}o, da, on postoji...
{100747}{100855}me je odveo u jedan sobiËak|gde smo dugo Êaskali,
{100855}{100915}ali mi se Ëini da nije|previöe obraÊao paûnju na...
{100915}{100975}ono öto sam mu priËao,
{100999}{101071}pa sam pomislio,
{101071}{101119}''ovaj neÊe baö niöta|preduzeti.''
{101119}{101191}Ne. Zaöto ne?
{101239}{101311}Jako dobro znaö odgovor na to|pitanje, baö kao i ja.
{101311}{101407}Za njega ja sam samo jedan|obiËan nikogoviÊ...
{101407}{101479}koji tuca ûenu lokalnog plemiÊa i, koji je,|zbog toga dobio öto je i zasluûio.
{101479}{101563}Pa, verovatno, policija neÊe svratiti|ovamo kao öto sam ti rekao da hoÊe.
{101563}{101671}Ali, Ëak i ako ne dou, nikad ti|neÊe poverovati u tu priËu o provalniku.
{101671}{101743}Sada viöe ne.
{101743}{101815}Tako, kao öto vidiö,|izgubio si.
{101863}{101959}Ne moûeö me viöe|prevariti, Milo.
{101959}{102019}Nisam ti poverovao ni jednu|jedinu reË.
{102019}{102079}To je istina.
{102127}{102211}Laûove.|-Pozovi vodnika Tarranta ako mi ne verujeö.
{102259}{102319}Doöao si ovamo da bi mi|rekao kako imaö nameru...
{102331}{102391}da mi ukradeö ûenu,
{102391}{102451}Ëeprkao si po|mojoj muökosti,
{102475}{102619}delio mi lekcije|o podlim namerama,
{102619}{102727}i ismevao si|lik koji sam ja stvorio, 
{102727}{102811}St. John Lord Merridewa.
{102919}{102967}Pa...
{102967}{103015}Ovaj put su svi meci pravi.
{103111}{103147}Igra je gotova, Andrew.
{103207}{103291}Ja idem kuÊi.
{103627}{103723}Milo, kao öto vidiö,
{103723}{103795}ja nisam baö|neki veliki igraË.
{103795}{103855}Hteo sam da kaûem.
{103867}{103963}nikad ne igraj istu|igru tri puta za redom.
{105955}{106027}Andrew...
{106063}{106135}Ne zaboravi,
{106135}{106195}da im kaûeö...
{106243}{106327}da je sve to bila...|samo krvava igra.
{106352}{107852}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
