{1}{1}25.000
{26}{176}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{580}{724}Kleopatra ñ Poslednja|kraljica Egipta
{725}{772}Godina je 69.|pre Hrista.
{774}{866}I Ëin / Egipat je zaspao|pod teökim nebom.
{901}{991}Neûni odblesci meseca|osvetljavaju plavi safir Nila.
{1028}{1117}Topli miris jasmina penje|se uz palatu Aleksandrije.
{1128}{1258}Zemlja faraona|rodila je Kleopatru.
{1300}{1350}U ova nemirna vremena,|mlada vladarka,
{1361}{1451}neopisivo lepa, nosi|nadu celog naroda.
{1470}{1566}Ali, po smrti svog oca, zbog|ljubomore dvora ûednog moÊi,
{1572}{1608}morala je|da pobegne.
{1613}{1670}Njen mlai brat Ptolomej|ûeleo je da vlada sam.
{1695}{1740}OdluËna da|povrati svoj tron,
{1751}{1812}Kleopatra Êe potraûiti|Cezarovu pomoÊ.
{1859}{1950}Povetarac, nosilac novosti, duva|po terasi palate u Aleksandriji.
{1984}{2073}Cezar joö nije svestan öta|Êe mu taj vetar otkriti.
{2107}{2206}Ove noÊi, Kleopatra nosi|sa sobom svoju sudbinu.
{4743}{4804}Stiûemo. Joö samo malo.|Samo nekoliko koraka.
{4808}{4857}Drûite se. Molim|vas, ne dajte se!
{4864}{4920}Stanite! äta|to nosite?
{4945}{5042}Ja nosim poklon kraljice|Egipta, velike Kleopatre,
{5049}{5082}moÊnom Cezaru.
{5088}{5163}Poklon, kaûeö?|äaliö se sa mnom?
{5172}{5226}Niko ne uznemirava|Cezara usred noÊi!
{5232}{5288}Dakle, spusti tepih|na zemlju i odlazi!
{5294}{5465}Primili smo nareenje da spustimo ovaj|poklon pred noge velikog Cezara. LiËno.
{5474}{5495}Ko si ti?
{5500}{5583}Ja sam äarmiona, poverenica|u sluûbi svoje kraljice.
{5595}{5673}A ovaj ovde je|Apolodor Sicilijanac.
{5688}{5743}Ali ti, ko si ti?
{5795}{5827}Ja sam Cezar.
{5916}{5945}- Ti, Cezar?|- Da!
{5950}{5987}Ti si njegova|bleda kopija!
{5993}{6072}I slepa i gluva, njega bih|prepoznala meu hiljadu.
{6080}{6255}Skloni oruûje, idiote!|äarmiona, kaûeö?
{6303}{6374}To je, dakle, velika|sveötenica Aleksandrije?
{6436}{6524}Poloûi taj poklon.|Ja sam Cezar.
{6533}{6596}MoÊni Cezare,|udalji svoju gardu.
{6609}{6667}Moûda uprljaju|sjaj poklona.
{6674}{6721}Pre nego öto te|pustim kroz ta vrata,
{6761}{6836}moram da se uverim u tvoju|vernost, velika sveötenice.
{6841}{6896}Cezare, imaj|poverenja.
{6910}{6944}Veruj mi na reË.
{6959}{7018}Moja vernost|je besprekorna.
{7055}{7133}Brute, ostavi nas!
{7153}{7249}Dozvolite mi da odmotam celi|Egipat pred vaöim nogamaÖ
{7591}{7655}Jednog dana, svi|naöi snovi Êe se naÊi
{7661}{7714}na putu koji|smo naËinili,
{7724}{7765}ali stranice|ove knjige,
{7772}{7852}ûivimo mnogo pre|no öto su napisane.
{7869}{7929}NiËega se ne plaöim,|nikoga se ne plaöim.
{7936}{7998}Neka me svako prihvati|onakvu kakva se prikazujem.
{8006}{8069}NiËega se ne plaöim,|nikoga se ne plaöim.
{8076}{8140}Neka se svako zadovolji|onim öto mu dam.
{8148}{8212}Dobro znam|öta mi pripada,
{8221}{8283}drûim se samo onoga|öto mi pripada.
{8290}{8346}Dobro znam,|ono öto odlazi,
{8352}{8423}ne ûelim niöta|öto nije moje.
{8730}{8808}Sve Êe biti trikÖ
{8834}{8858}Ako mi odoliÖ
{8866}{8953}Sve Êe biti|strategijaÖ
{8968}{9005}Ako me zavoliÖ
{9011}{9093}Sve Êe biti trikÖ
{9104}{9139}Ako mi odoliÖ
{9146}{9229}Sve Êe biti|strategijaÖ
{9241}{9323}Ako me zavoliÖ
{9565}{9653}Ovo Êe biti za ceo|ûivot ili neÊe uopöte.
{9704}{9766}Sve mogu da napravim,|Ëak i greöke,
{9773}{9836}ti sve moûeö da uzmeö,|ali ne i moje srce.
{9845}{9905}Sve mogu da napravim,|Ëak i greöke,
{9913}{9978}sve se moûe nauËiti,|to me ne plaöi.
{9986}{10045}Mogla bih se|svideti celom svetu,
{10053}{10118}mogla bih se predati|i sve saËuvati.
{10125}{10179}Mogla bih se|svideti celom svetu,
{10187}{10267}ali onaj ko se predaje,|mora da se Ëuva.
{10563}{10642}Sve Êe biti trikÖ
{10663}{10696}Ako mi odoliÖ
{10702}{10783}Sve Êe biti|strategijaÖ
{10789}{10841}Ako me zavoliÖ
{10850}{10924}Sve Êe biti trikÖ
{10940}{10977}Ako mi odoliÖ
{10983}{11065}Sve Êe biti|strategijaÖ
{11084}{11126}Ako me zavoliÖ
{11413}{11492}Sve Êe biti trikÖ
{11509}{11545}Ako mi odoliÖ
{11551}{11630}Sve Êe biti|strategijaÖ
{11637}{11685}Ako me zavoliÖ
{11689}{11772}Sve Êe biti trikÖ
{11777}{11828}Ako mi odoliÖ
{11835}{11915}Sve Êe biti|strategijaÖ
{11930}{12045}Ako me zavoliÖ
{12422}{12511}Kakvo samopouzdanje!|Impresioniran sam.
{12565}{12628}Nisam oËekivao|toliko maöte.
{12633}{12681}Rekli su mi da voliö|hrabrost i smelost.
{12695}{12759}Da! Da. Hrabrost|nosi genijalnost aÖ
{12764}{12810}a smelost|Ëini kraljeve!
{12819}{12885}Cezare, doöla sam da|traûim tvoju podröku.
{12903}{12925}Ja sam u opasnosti.
{12931}{13003}Moj brat, Ptolomej, ûeli|moju smrt. Potreban si mi.
{13009}{13042}Ne plaöi se.
{13060}{13099}Ti si sada pod|mojom zaötitom.
{13107}{13165}Cezare, Ptolomej i Potin|traûe da razgovaraju sa tobom.
{13183}{13245}U pravom|trenutkuÖ Neka uu!
{13267}{13332}TiÖ Ti si se usudila|da se vratiö, izdajico!
{13339}{13357}Ovo je zavera!
{13370}{13403}Veliki Cezare,|moja sestra laûe!
{13409}{13491}Ona je na sve spremna da se doËepa|vlasti, neÊe oklevati da te prevari,
{13501}{13547}da upotrebi|muËenje, kao i otrov!
{13553}{13592}Sramota je na tebi,|ûeno bez Ëasti!
{13597}{13698}Mali Ptolomeju, tvoje reËi nisu|dostojne jednog kralja! BruteÖ
{13704}{13852}Oprosti mu, Cezare. On je impulsivan|i dozvoljava da ga ponesu emocije.
{13857}{13882}Dosta!
{13891}{13953}Kao izvröilac|testamenta vaöeg oca,
{13961}{14014}nareujem da se povinujete|njegovim ûeljama.
{14025}{14155}Ptolomeju, oûeniÊeö se svojom|sestrom Kleopatrom i vladaÊeö sa njom.
{14161}{14276}Ako odbijeö, viöe neÊeö biti pod|mojom zaötitom i napustiÊeö palatu.
{14290}{14365}PodseÊam te da si|po ûelji Rima kralj.
{14371}{14438}Ali, ja poötujem Rim! »ak sam|ti isporuËio Pompejevu glavu!
{14447}{14481}- ∆uti!|- Ali...
{14500}{14602}Hajde, obriöi suze. Ne|plaËe se na dan venËanja!
{14617}{14660}Rizikujeö|izlivanje Nila.
{14675}{14713}O, dobro,|dobro, dobro!
{14812}{14881}ObeÊavam da Êu|poötovati tradiciju.
{14887}{14976}Moja draga sestro, moûeö|da raËunaö na moju vernost.
{14988}{15025}Organizuj venËanje|po svojoj ûelji.
{15033}{15123}ProslaviÊemo ga u|sali boginje Isis.
{15125}{15228}- Ne! U saliÖHiljadu|velova! - Isis!
{15236}{15259}Hiljadu velova!
{15266}{15351}éelim muziËare, plesaËe, akrobate|ñ ûelim da sija sa svih strana!
{15361}{15427}Egipat treba da zna da|Êemo zajedno vladatiÖ
{15435}{15468}Ö ruku pod ruku!
{15676}{15732}PodvlaËimo crtu|pod proöloöÊu.
{15740}{15773}Moje srce viöe nije|moglo da izdrûi,
{15784}{15868}zamiöljajuÊi dan kada|Êu te ponovo naÊi.
{15873}{15924}OËi mi se dave|od radosti,
{15933}{15980}od predugog Ëekanja
{15987}{16071}na noÊ slavlja i vreme|koje treba nadoknaditi.
{16084}{16128}I ûelim da|pevam tebi,
{16147}{16185}podigni svoju Ëaöu,
{16189}{16240}u znak izvinjenja|i radosti.
{16249}{16286}Snaûni i ponosni
{16291}{16343}na svoju ljubav koju|smo ponovo naöli,
{16350}{16388}sestra i brat,
{16393}{16440}na ono öto|Êemo deliti,
{16449}{16484}ti i ja.
{16492}{16581}Ruku pod ruku, zajedno|istupamo, / Ti i ja.
{16589}{16684}pogledi nam skreÊu|u istom pravcu,
{16694}{16793}jer se volimo i jer|liËimo, / Ti i ja.
{16800}{16895}legenda Êe se|seÊati naöe veze.
{16901}{16985}Niöta neÊe zaista|uniötiti krvne veze.
{16998}{17088}Ja sam tvoj brat, ali|neÊu se dugo pretvarati.
{17100}{17192}Uskoro Êeö se okrenuti|i ja Êu se osvetiti,
{17204}{17292}noûem u tvoja lea i|poslednjim poljupcem.
{17305}{17356}éelim da|pevam sa tobom,
{17366}{17405}podigni svoju Ëaöu,
{17411}{17460}u ime poverenja|i vere.
{17466}{17506}Snaûni i ponosni,
{17513}{17560}na svoje|nove interese,
{17569}{17606}sestra i brat,
{17612}{17657}jer sve moramo|da delimo,
{17667}{17704}ti i ja.
{17715}{17812}Ruku pod ruku, zajedno|istupamo, / Ti i ja.
{17819}{17904}pogledi nam skreÊu|u istom pravcu,
{17916}{18012}jer se volimo i jer|liËimo, / Ti i ja.
{18019}{18111}legenda Êe se|seÊati naöe veze.
{18234}{18317}Legenda Êe se|seÊati naöe veze.
{18324}{18362}Samo ti i ja,
{18368}{18412}moûeö da|raËunaö na mene.
{18419}{18463}Samo ti i ja,
{18471}{18516}neka ceo svet vidi,
{18527}{18566}da za tebe i mene
{18573}{18620}postoji samo jedan|i to isti glas,
{18626}{18666}i od tebe meni,
{18674}{18717}porodica ne laûe.
{19747}{19835}Ruku pod ruku,|zajedno istupamo,
{19846}{19938}pogledi nam skreÊu|u istom pravcu,
{19951}{20036}jer se volimo|i jer liËimo,
{20050}{20140}legenda Êe se|seÊati naöe veze.
{20164}{20243}Ruku pod ruku, zajedno|istupamo, / Ti i ja.
{20255}{20345}pogledi nam skreÊu|u istom pravcu,
{20353}{20442}jer se volimo i jer|liËimo, / Ti i ja.
{20454}{20555}legenda Êe se|seÊati naöe veze.
{20563}{20599}Samo ti i ja,
{20608}{20660}moûeö da raËunaö|na mene. /Ti i ja.
{20665}{20700}Samo ti i ja,
{20708}{20757}neka ceo svet vidi,
{20766}{20804}da za tebe i mene
{20812}{20857}postoji samo jedan|i to isti glas,
{20863}{20903}i od tebe meni,
{20910}{20992}porodica ne laûe.
{21346}{21389}Sa mnom,
{21397}{21475}ti drûiö Rim u|svojim rukama,
{21498}{21559}deliö istu sudbinu,
{21568}{21641}moÊ bez straha|od sutraönjice,
{21650}{21730}ako se prepustiö|mom zagrljaju.
{21736}{21808}Egipat je|ono öto ûelim
{21820}{21900}i da budem njegova|apsolutna kraljica,
{21908}{21983}i tvoj sluga, a na|meni svojstven naËin.
{21989}{22069}Dovoljno je|parËe pergamenta.
{22242}{22308}Ruka na Zapadu,
{22321}{22401}a srce na Istoku,
{22408}{22485}ovim obavezujuÊim|sporazumom,
{22492}{22567}dva sveta|postaju jedno.
{22577}{22655}Ruka na Zapadu,
{22664}{22746}a srce na Istoku,
{22752}{22826}ovim obavezujuÊim|sporazumom,
{22834}{22928}dva sveta|postaju jedno.
{23235}{23362}Ako je tebi vredno da|izgubiö sebe zbog zemlje
{23370}{23444}i dve obale reke,
{23454}{23529}uzmi celi Egipat|pod svoju kontrolu,
{23535}{23611}a ja, ja Êu|uzeti samo tebe.
{23625}{23700}Polaûem ljubav|pred tvoje noge,
{23708}{23788}to je obeÊanje|koje dajem,
{23796}{23865}ûena i podanik|na tvojoj strani
{23871}{23984}i svi naöi snovi|biÊe osvojeni.
{24123}{24200}Ruka na Zapadu,
{24212}{24286}a srce na Istoku,
{24293}{24375}ovim obavezujuÊim|sporazumom,
{24382}{24456}dva sveta|postaju jedno.
{24467}{24547}Ruka na Zapadu,
{24556}{24631}a srce na Istoku,
{24637}{24712}ovim obavezujuÊim|sporazumom,
{24720}{24797}dva sveta|postaju jedno.
{24948}{25099}ObavezujuÊim|ugovorom.
{25116}{25273}ObavezujuÊim|ugovorom.
{25288}{25442}ObavezujuÊim|ugovorom.
{25496}{25569}Ruka na Zapadu,
{25583}{25651}a srce na Istoku,
{25663}{25743}ovim obavezujuÊim|sporazumom,
{25751}{25828}dva sveta|postaju jedno.
{25837}{25912}Ruka na Zapadu,
{25928}{26001}a srce na Istoku,
{26008}{26087}ovim obavezujuÊim|sporazumom,
{26095}{26284}dva sveta|postaju jedno.
{26551}{26607}Cezare! Marko Antonije|ûeli da razgovara sa tobom.
{26612}{26642}Cezar je zauzet.
{26661}{26691}Neka ue.
{26701}{26805}Da li moûemo da|razgovaramoÖ nasamo?
{26825}{26863}Koja je svrha tvoje|posete, Antonije?
{26870}{26962}Lepo spavaj, Cezare. Dani|koji dolaze biÊe teöki.
{26969}{26995}CezareÖ
{27005}{27052}Otkad si u gradu,|oseÊa se napetost.
{27069}{27101}Ako brzo ne reagujeö,
{27108}{27189}suoËiÊemo se sa pobunom|naroda pod rukovodstvom Potina.
{27200}{27224}Sluöaj me!
{27251}{27281}Potrebno je okupiti legije
{27293}{27372}i proÊi sa vladarima kroz ceo|grad, kako bi se stiöala tenzija.
{27378}{27423}Ako izbije rat, biÊemo|prinueni da uzvratimo.
{27430}{27472}I da spalimo|egipatsku flotu.
{27477}{27509}Budite bez brige.
{27539}{27683}Pomirenje Kleopatre i Ptolomeja|uspostaviÊe red i ravnoteûu moÊi u Egiptu.
{27696}{27769}Trebalo bi liËno da najaviö|i organizujeö svadbu,
{27783}{27855}kako bi prikazao narodu|sliku dobronamernosti Rima.
{27876}{28018}Da. A Kleopatre Êe vladati,|inteligentno iÖ uporno.
{28025}{28073}Izgleda da te neöto|snaûno privlaËi njoj.
{28173}{28278}Ta ûenaÖ Ta ûena|me je osvojila!
{28302}{28342}Veûe nas|velika strast.
{28350}{28478}Strast koja moûe naökoditi tvom|ugledu! Ti si oûenjen, ne zaboravi to.
{28488}{28517}Njegovom ugledu?
{28522}{28555}Moj brak|je sterilan!
{28564}{28653}Joö nemam naslednika kome|sam se nadao i ceo Rim to zna!
{28664}{28706}Ali Senat Êe na to|gledati kao na izdaju!
{28718}{28749}Poznate su ti|rimske vrednostiÖ
{28754}{28828}Ja sam taj koji nameÊe|vrednosti carstvu!
{28920}{29051}Dobro, napustiÊemo|Aleksandriju posle sveËanosti.
{29374}{29444}äta je lepöe|od onog dana?
{29453}{29572}äta je snaûnije od|dva prstena na prstima?
{29589}{29660}Ne vidim.
{29710}{29786}Da li joj kaûe da je|lepa i viöe od toga?
{29793}{29911}Da li mu kaûe da je|kraljica, a on njen kralj?
{29932}{29996}Ne znam.
{30033}{30108}Neûna reË, reË|koja ih zbliûava,
{30116}{30194}pogled koji|klizi izmeu njih,
{30205}{30281}ovo je zauvek|ucrtan dan,
{30294}{30425}ovo je dan koji|treba da bude savröen.
{30432}{30490}Oni su svetlost,
{30512}{30619}oni su Ëuvari|veËnosti,
{30629}{30748}kao sunce nad|buduÊnoöÊu sveta,
{30767}{30832}a ja sam|njihova senka,
{30864}{30979}od senke ka|svetlosti.
{31079}{31153}äta je lepöe od|pisanja istorije?
{31162}{31286}äta je veÊe od|ulaska u seÊanje?
{31299}{31375}Ne vidim.
{31419}{31498}Da li Êe je on odvesti|do najviöeg mesta?
{31506}{31632}Da li Êe ona od njega napraviti|muökarca kakvog je Ëekala?
{31644}{31726}Ko zaista zna?
{31748}{31820}Oni napreduju kako|bi dovröili put,
{31829}{31909}da ih velika sudbina|naËini velikim,
{31920}{31999}ovo je dan kada|poËinje san,
{32009}{32099}ovo je dan kada|svi podiûu poglede.
{32132}{32204}Oni su svetlost,
{32218}{32334}oni su Ëuvari|veËnosti,
{32349}{32470}kao sunce nad|buduÊnoöÊu sveta,
{32483}{32548}a ja sam|njihova senka,
{32568}{32678}od senke ka|svetlosti.
{32920}{33055}Od senke ka|svetlosti,
{33176}{33254}jer Êe nas obasjati.
{33266}{33362}Oni su Ëuvari|veËnosti,
{33380}{33514}kao sunce nad|buduÊnoöÊu sveta,
{33528}{33605}a ja sam|njihova senka,
{33614}{33765}od senke ka|svetlosti.
{33951}{34097}Od senke ka|svetlosti.
{34312}{34554}Od senke ka|svetlosti.
{34648}{34706}Gozbu! Gozbu,|gladan sam!
{34715}{34813}Izvinite öto vas ovako ometam,|ali donosim veoma tuûne vesti.
{34818}{34883}O Ëemu govoriö,|Apolodore? Prii i objasni.
{34894}{34971}Moja kraljice, rat je uvukao|zemlju u bedu i siromaötvo.
{34980}{35060}O, prestani da tako uznemiravaö|gospodare svojim glupostima!
{35067}{35101}UÊuti, Potine,|pusti ga da govori!
{35110}{35155}Veliki poûar je|progutao naöe ûitnice.
{35163}{35189}Narod umire|od gladi.
{35197}{35293}Nil nije dovoljno plavio i|naredna ûetva biÊe mröava.
{35301}{35355}Viöe nijedan seljak|ne moûe da plati porez.
{35389}{35449}Moja kraljice, ceo Egipat|je na ivici propasti.
{35455}{35527}O, laûi! Samo ûeliö|da izazoveö nevolje.
{35539}{35630}Narod je duûan da sluûi opötoj|stvari i svojim vladarima.
{35636}{35687}To je moto Egipta.
{35694}{35747}Kakvo licemerje!|Straûa!
{35755}{35868}Ne! Dozvoli meni, Cezare. Radi|se o mom narodu i mojoj zemlji.
{35879}{35988}Narod treba da povrati poverenje|i da ponovo veruje u Egipat.
{36031}{36100}Nareujem da se porezi|i prisilni zajmovi
{36107}{36170}pokupe od najviöih|dostojanstvenika kraljevstva.
{36176}{36223}Ti se usuujeö da nareujeö?
{36232}{36400}Dok sam ja ûiv, niko ñ ama baö niko! ñ neÊe|pipnuti bogatstvo i privilegije EgipÊana!
{36408}{36447}AliÖ Ma pusti me,|Potine, povreujeö me!
{36453}{36601}Ti, PotineÖ Ti koji si ûiveo od|privilegija, zavera i intrigaÖ
{36611}{36683}ti si taj koji je uveo|sopstvenu zemlju u izolaciju!
{36689}{36787}A ko je izazvao bes egipatskog|naroda pljaËkajuÊi naöa bogatstva?
{36796}{36915}Ko je verovao da Êemo dozvoliti da|nas ovako porobe rimski okupatori?
{36922}{37054}Ko je uniötio ono öto nam je bilo|najdraûe, veliku Aleksandrijsku biblioteku?
{37063}{37129}- Ko je spreman da proda|svoje telo jednomÖ - Prestanite!
{37136}{37200}AliÖ Ptolomeju? UËini neöto!
{37206}{37281}Ne moûeö da dozvoliö da jedan|Rimljanin odluËuje o mojoj sudbini!
{37293}{37369}Pre nego öto sve egipatske|sfinge uniöte kraljevstvoÖ
{37375}{37421}Ti Êe biti samo|daleka uspomena!
{37426}{37484}Cezarove naredbe|su i moje!
{37490}{37529}Ne! Ne!
{37544}{37603}Sada kada je neprijatelj|pobeen, treba da krenemo.
{37612}{37662}Ptolomeje,|pridruûiÊeö nam se.
{37676}{37718}Rim je nestrpljiv u mom odsustvu
{37727}{37828}i jedva Ëekam da vam pokaûem|svu veliËinu mog carstva.
{37837}{37872}äarmiona, spremi nas za put.
{37881}{37963}Ponesi moje|najveliËanstvenije stvari.
{37970}{38003} Rim nas Ëeka!
{38481}{38513}Negde drugde,
{38519}{38573}pod suncem ruûe,
{38595}{38628}negde drugde,
{38637}{38703}svoja srca ulaûemo.
{38710}{38749}Negde drugde,
{38756}{38822}pod suncem ruûe,
{38831}{38867}negde drugde,
{38876}{38948}svoje snove|odmaramo.
{39019}{39072}Gledati iza|horizonta,
{39081}{39135}gde nestaju|granice Orijenta,
{39144}{39195}gledati, a ne|izgubiti razum,
{39203}{39248}iza horizonta.
{39263}{39317}Ispred nas je|hiljadu lica,
{39324}{39376}ispred nas je|milion znakova.
{39384}{39437}Iza nas, oni|koji nas laûu,
{39443}{39502}iza nas ono öto|Êe nam nedostajati.
{39508}{39608}Prati zvezde,|linije naöih dlanova,
{39614}{39706}poslednji|pogled u daljinu,
{39712}{39783}na naöu zemlju.
{39797}{39831}Negde drugde,
{39839}{39889}pod suncem ruûe,
{39909}{39949}negde drugde,
{39958}{40027}svoja srca ulaûemo.
{40034}{40068}Negde drugde,
{40075}{40142}pod suncem ruûe,
{40150}{40184}negde drugde,
{40191}{40269}svoje snove|odmaramo.
{40343}{40399}Bez obzira na|sve loöe znake,
{40405}{40456}preûiveÊemo|sva potonuÊa,
{40463}{40515}nas vodi sunce,
{40523}{40577}da, sunce.
{40591}{40635}Ispred nas je|hiljadu lica,
{40643}{40697}ispred nas je|milion znakova.
{40704}{40757}Iza nas, oni|koji nam pevaju,
{40764}{40819}iza nas, sva|naöa deca.
{40831}{40924}Pratiti svaku obalu,|preÊi pustinje,
{40932}{41033}jedan gutljaj je dovoljan|da nam ugasi snove,
{41039}{41104}na ovoj zemlji.
{41120}{41153}Negde drugde,
{41159}{41209}pod suncem ruûe,
{41220}{41259}negde drugde,
{41266}{41341}svoja srca ulaûemo.
{41348}{41382}Negde drugde,
{41388}{41461}pod suncem ruûe,
{41469}{41504}negde drugde,
{41511}{41578}svoje snove|odmaramo.
{41605}{41710}Negde|drugde/Pod suncem
{41717}{41749}Negde drugde.
{41839}{41870}Negde drugde,
{41877}{41940}pod suncem ruûe,
{41947}{41985}negde drugde,
{41993}{42062}svoje snove|odmaramo.
{42092}{42141}Bez obzira na|sve loöe znakove,
{42156}{42191}/ Negde drugde
{42197}{42286}preûiveÊemo|sva potonuÊa.
{42297}{42340}PreûiveÊemo.
{42391}{42420}Hajde! Hajde!
{42444}{42555}O, voli me,|voli me, duöo.
{42579}{42674}O, voli me,|voli me, duöo.
{42684}{42707}Negde drugde.
{42712}{42760}Negde drugde.
{43167}{43277}Veni... vidi... vici!|(DoohÖ videhÖ pobedih!)
{43284}{43335}éiveo Cezar!|Cezar imperator!
{43343}{43447}Cezare, vratio si se u|Rim krunisan novom slavom.
{43452}{43547}Imenujemo te doûivotnim|voom rimskog naroda.
{43554}{43641}Tvoje ime Êe biti ispisano|iznad vrata Jupiterovog hrama.
{43646}{43743}To je najbolje priznanje|tvojim pobedama i trijumfu.
{43761}{43828}OdluËili smo da u hram|postavimo tvoju statuu.
{43842}{43870}Kako ste me|prikazali?
{43879}{43927}Kako voziö|luksuzne koËije.
{43938}{43964}Svi smo potpisali.
{43972}{44037}ÑKaju Juliju|Cezaru, polubogu.ì
{44052}{44098}éiveo Cezar!|Cezar imperator!
{44104}{44171}Ja sam Cezar, ja nisam kralj!
{44193}{44280}Ali, promeniÊu|Rim, promeniÊu svet.
{44322}{44394}éelim da celo moje|carstvo ûivi u istom ritmu.
{44424}{44543}Doneo sam iz Egipta|fantastiËno blago: vreme!
{44593}{44686}Cicerone, predstavi svim|okupljenima ovo Ëudo!
{44692}{44764}Ovo je revolucija, da, revolucija!
{44778}{44885}Rimski kalendar Êe od sada|biti solarni, a ne viöe lunarni.
{44903}{45097}BiÊe baziran na promeni godiönjih doba, öto|znaËi na periodu rotacije Zemlje oko Sunca.
{45104}{45236}Godina ima dakle 12 meseci i 365 dana.
{45248}{45388}Tvoje ime Êe biti povezano sa ovim|kalendarom zauvek! Do kraja vremena.
{45438}{45511}Rim to duguje|kraljici Egipta.
{45526}{45715}Ne, Rim nikome niöta ne duguje, ako ne svom|jedinom i jedinstvenom gospodaru, Juliju Cezaru.
{45755}{45919}Cicerone, bez Kleopatre, nikada ne|bih mogao da izmenim buduÊnost sveta!
{48859}{48892}Korak po korak,
{48898}{48924}lagani silazak,
{48931}{48983}da ne vidimo|kako nas laûu.
{48989}{49017}Korak po korak,
{49024}{49057}uspela sam|se uz nagib,
{49064}{49118}zauzela|prazna mesta.
{49125}{49151}Korak po korak,
{49157}{49192}uÊi Êu u Êorsokak,
{49198}{49251}ako ne naem|svoje mesto.
{49257}{49283}Korak po korak,
{49289}{49323}uspeti ili|se slomiti,
{49330}{49385}ne ûelim da|me izbriöu.
{49398}{49437}Dan za danom,
{49451}{49480}niöta nisam|ispustila,
{49486}{49525}niöta nisam|propustila,
{49534}{49575}Ëak ni ljubav.
{49584}{49615}Stajala sam na keju,
{49622}{49653}snagom ruËnim|zglobova.
{49661}{49673}Ja sam
{49680}{49729}moderna|ûena, ja sam,
{49737}{49832}ovde, ja sam ûena|koja se otkriva
{49840}{49911}i koja prati|svoje ûelje.
{49917}{49936}Ja sam
{49943}{49993}moderna|ûena, ja ûivim
{50005}{50044}bez kompromisa.
{50053}{50102}Moje srce|je samo moje,
{50108}{50181}moje telo nije|potËinjeno.
{50187}{50209}Ja sam
{50233}{50279}moderna ûena.
{50590}{50620}Korak po korak,
{50628}{50658}treba se drûati|za ogradu,
{50665}{50716}treba dati primer.
{50723}{50751}Penjati se|stepenicama,
{50757}{50791}da se ne bi|nisko palo,
{50800}{50847}nema drugog izbora.
{50864}{50907}Bol za bolom,
{50919}{50961}Ëinimo tako, volimo
{50967}{50995}i, svejedno,|napredujemo.
{51001}{51046}Vrisak za vriskom,
{51055}{51083}drûimo se potrebe
{51088}{51116}da idemo sve dalje.
{51123}{51136}Ja sam
{51143}{51192}moderna ûena, ja sam
{51200}{51298}ovde, ja sam ûena|koja se otkriva
{51306}{51368}i koja prati|svoje ûelje.
{51381}{51404}Ja sam
{51410}{51463}moderna|ûena, ja ûivim
{51473}{51510}bez kompromisa.
{51518}{51567}Moje srce|je samo moje,
{51574}{51648}moje telo nije|potËinjeno.
{51658}{51673}Ja sam
{51684}{51765}moderna ûena.
{51793}{51816}Korak po korak,
{51852}{51908}protiv predrasuda,
{51921}{51961}kuda god stupam,
{51973}{52044}Ëinim to glave|visoko podignute.
{52054}{52086}Korak po korak,
{52105}{52173}protiv predrasuda,
{52185}{52228}kuda god stupam,
{52240}{52309}Ëinim to glave, glave|visoko podignute.
{52315}{52334}Ja sam
{52341}{52396}moderna ûena, ja sam
{52406}{52500}ovde, ja sam ûena|koja se otkriva
{52508}{52575}i koja prati|svoje ûelje.
{52581}{52600}Ja sam
{52607}{52668}moderna|ûena, ja ûivim
{52675}{52708}bez kompromisa.
{52717}{52764}Moje srce|je samo moje,
{52774}{52845}moje telo nije|potËinjeno.
{52853}{52870}Ja sam
{52876}{52943}moderna ûena.
{53110}{53143}Ja samÖ
{53849}{53890}Poigravanje|izgledom,
{53901}{53947}i sve Ëiniti|za lepotu,
{53953}{53989}izbegavati Ëinjenicu
{53997}{54044}da niko nije veËan.
{54051}{54097}Sama, sanjam|o boljim
{54108}{54150}danima, noÊima.
{54160}{54199}Ali sama, postajem,
{54204}{54220}ostajem,
{54226}{54247}u svom srcu.
{54254}{54302}Sve
{54313}{54382}je tako prolazno,
{54414}{54488}krhko kao ljubav,
{54504}{54587}jedan dan sreÊan,|jedan gorak,
{54612}{54676}sve se gubi|dan za danom.
{54682}{54715}Niöta
{54722}{54791}nije kao u snu,
{54815}{54893}kao öto smo mislili,|u vatri zanosa.
{54901}{54924}Svi
{54931}{55001}velovi Êe se|podiÊi jednog dana,
{55012}{55092}jer sve vene|i sve ima kraj.
{55140}{55181}Poigravanje|ravnoduönoöÊu,
{55189}{55237}kako bi se bolje|povlaËili konci,
{55245}{55284}osujetio napredak
{55291}{55339}i veötaËke zamke.
{55345}{55395}Sama, plaËem|za boljim
{55402}{55446}danima, noÊima
{55452}{55495}i sama, seÊam se i
{55502}{55513}neûno
{55520}{55543}od toga umirem.
{55548}{55598}Sve
{55605}{55676}je tako prolazno,
{55698}{55784}krhko kao ljubav,
{55795}{55882}jedan dan sreÊan,|jedan gorak,
{55900}{55964}sve se gubi|dan za danom.
{55983}{56010}Niöta
{56018}{56085}nije kao u snu,
{56111}{56173}kao öto smo mislili,|u vatri zanosa.
{56180}{56209}Svi
{56220}{56293}velovi Êe se|podiÊi jednog dana,
{56303}{56357}jer sve vene i sveÖ
{56397}{56435}Ali vreme|je za ûelju
{56471}{56535}i biti neËija ûelja,
{56558}{56649}oËekujuÊi|zadovoljstva,
{56670}{56738}oËarati se öarmom.
{56809}{56859}A sutra Êe videti
{56872}{56932}plodove koje|sam donela,
{56987}{57043}kako bismo povezali
{57079}{57163}i udruûili
{57187}{57288}svoje buduÊnosti.
{57460}{57513}Sve
{57521}{57579}je tako prolazno,
{57588}{57690}Sve, sve, sve|/ krhko kao ljubav,
{57713}{57793}jedan dan sreÊan,|jedan gorak,
{57816}{57873}sve se gubi|dan za danom.
{57881}{57919}Niöta
{57927}{57989}nije kao u snu,
{57997}{58092}Niöta, niöta, niöta / kao öto smo|mislili, u vatri zanosa.
{58099}{58119}Svi
{58130}{58209}velovi Êe se|podiÊi jednog dana,
{58231}{58287}jer sve vene|i sve ima kraj.
{58295}{58339}Sve
{58345}{58405}je tako prolazno,
{58399}{58452}sve, sve, sve...
{58485}{58541}Sve
{58554}{58623}je tako prolazno,
{58647}{58707}jer sve vene|i sve ima kraj.
{58931}{59048}Cezar je otiöao daleko, a|ova EgipÊanka mi je odvratna.
{59072}{59157}VeÊ duûe vreme ne mogu da|podnesem njihove arogantne parade.
{59174}{59215}Njihova taötina|poniötava sve zasluge.
{59224}{59263}Ali, zaöto se|plaöiö Kleopatre?
{59277}{59298}Ona je strankinja!
{59314}{59369}A, znaËi doûivljavaö|strance kao pretnju?
{59385}{59472}Cezar je uradio öta je morao|za Rim i za njegovu slavu.
{59480}{59536}Cezar se ponaöa u Rimu|kao apsolutni monarh.
{59546}{59604}Dozvoljava da mu se|dive kao boûanstvu!
{59616}{59685}Moj dragi Oktavijane, za|vreme njegovog trijumfa,
{59691}{59812}Ciceron je Ëuo kako narod|kliËe: Ti si kralj! Ti si kralj!
{59843}{59882}I Cezar je to dozvolio.
{59910}{59988}Sanja li on da postane|tiranin, kao kraljevi Orijenta?
{59994}{60031}NeÊe biti|monarha u Rimu!
{60037}{60087}Kraljevi pobuuju ugnjetavanja|i izazivaju okrutnosti.
{60100}{60183}»ak izjavljuje kako moûe|da ima koju god ûenu poûeliÖ
{60209}{60256}poËevöi sa ovom|zmijom sa Nila!
{60285}{60330}Lepide, öta ti misliö o tome?
{60354}{60402}Poligamija se kosi|sa rimskim zakonima.
{60418}{60478}Cezar ne razmatra|naöa miöljenja!
{60484}{60565}Zaöto ste mu dali tako visok|poloûaj, ako ga tako kritikujete?
{60578}{60691}Njega, koji tebe i mene smatra|svojim usvojenim sinovimaÖ
{60725}{60821}Sa svim neprijateljima koje|je stvorio, sigurno loöe spava!
{60863}{60949}Brojni su oni koji sanjaju|da mu zabiju noû u telo!
{60955}{61039}Kasije! Dobro znaö|da ako dotaknemo Cezara,
{61061}{61108}krvariÊe ceo Rim!
{61662}{61695}Biti ovde,
{61700}{61742}kada se|nada predaje.
{61754}{61827}Biti braÊa pred|licem sudbine,
{61838}{61888}i, konaËno,|podiÊi glavu.
{61893}{61976}Kunem se da, golim|rukama ako treba,
{61987}{62068}izgradiÊemo zemlju
{62076}{62131}sutra, kamen|po kamen.
{62162}{62267}Kunem ti se...
{62327}{62457}Krvlju i mesom.
{62487}{62551}Tako mi|svega svetog,
{62561}{62700}Krvlju i mesom,
{62720}{62805}ovde ti se kunem.
{62929}{62944}Znamo
{62953}{63004}da kada su|dani vezani,
{63012}{63086}kao öto su naöi|u prijateljstvu,
{63091}{63149}niöta ih ne|moûe izmeniti.
{63161}{63244}Kunem se da Êemo|zajedno maröirati,
{63254}{63392}tako daleko da Êe nam|buduÊnost izgraditi hramove.
{63406}{63523}Kunem ti se...
{63585}{63718}Krvlju i mesom.
{63741}{63810}Tako mi|svega svetog,
{63821}{63958}krvlju i mesom,
{63979}{64067}ovde ti se kunem.
{64100}{64198}I niöta, i|niko ovde dole,
{64216}{64324}neÊe moÊi da|slomi naö zakon.
{64968}{65098}Krvlju i mesom.
{65118}{65191}tako mi|svega svetog,
{65199}{65343}krvlju i mesom,
{65361}{65443}ovde ti se kunem.
{65875}{65898}Cezare!
{65943}{66007}Kleopatra!|äta radiö ovde?
{66065}{66120}Nijednoj ûeni nije|dozvoljeno da ue u logor!
{66136}{66210}Moj diktator! Moram li da|poötujem sve tvoje naredbe?
{66218}{66270}Samo graani Rima moraju|da ih se pridrûavaju.
{66292}{66367}Ali, svejedno, tvoje|mesto nije ovde.
{66374}{66459}Moj dragi Oktavijane, moje mesto|je tamo gde ûelim da budem!
{66464}{66479}Kakva drskost!
{66488}{66516}Cezare, moram da|razgovaram sa tobom!
{66521}{66560}A samo ovde mogu da se|nadam da Êu te videti.
{66580}{66660}Prekini sa sarkazmom,|moûeö li? I povuci se!
{66676}{66726}Usamljenost me pritiska,|Cezare!
{66743}{66777} Rim mi je uûasno dosadan.
{66796}{66851}Ovde sve samo o|politici i osvajanjima.
{66873}{66932}Rekli bismo da|je negovanje duha
{66939}{67015}i prouËavanje ljudske|psihe potpuno proterano.
{67033}{67072}Nedostaje mi|svetlost Aleksandrije.
{67080}{67164}Vidi, moÊna Kleopatra,|moûe li biti ranjiva?
{67174}{67225}To bi nas gotovo dirnulo!
{67232}{67262}I kuda god da idem,
{67267}{67330}oseÊam nepodnoöljivu|negostoljubivost prema sebi!
{67339}{67364} Ostavi je!
{67380}{67472}Ne zaboravi da si ti moj|gost, a ne rimske drûave!
{67484}{67518}Ma, sve je|jasno, Cezare.
{67539}{67653}Kao öto je jasno da u tvojim oËima|nisam niöta viöe od egzotiËne slike!
{67682}{67708}Ali, varaö se!
{67755}{67815}Znam da ne mogu da budem|prisutan po tvojoj ûelji,
{67840}{67889}ali zaposlen sam|drûavnim poslovima.
{67900}{67933}Ti to znaö i|treba da razumeö.
{67939}{68012}Cezar je od tebe napravio|ûivu boginju, naravno,
{68024}{68062}ali dovodeÊi te u Rim,
{68073}{68130}dao je batinu svojim|neprijateljima.
{68149}{68172}Dosta!
{68180}{68206}U pravu je.
{68215}{68287}Bolji politiËar od|tebe bi se uzdrûao.
{68294}{68309}Ha!
{68318}{68346}Ali, znajte ovo,
{68352}{68422}Cezar neÊe joö dugo|patiti u mojoj senci.
{68438}{68478}VraÊam se u|Egipat! Ptolomeju...
{68498}{68521}Ma, öta priËaö?
{68548}{68605}Tvoja ravnoduönost|mi ne ostavlja izbor.
{68693}{68775}Ostani! Ostani...
{68794}{68844}PrelazeÊi|duge pustinje,
{68860}{68922}podiûem se,
{68933}{68997}ponekad kad sve treba|ponovo napraviti,
{69007}{69077}sam pred|spoljnim svetom.
{69100}{69145}SluöajuÊi öta|ljudi govore o meni,
{69155}{69232}najgore od loöeg,|hvalospev od dobrog,
{69239}{69297}ostavljam iza|sebe korake
{69305}{69382}Ëoveka sa|vrhunskom sudbinom.
{69419}{69499}Da li me to|zaista dotiËe?
{69529}{69608}Ono öto me|dotiËe, to si ti,
{69618}{69668}i zvuk|tvojih koraka.
{69680}{69764}Ono öto me|povreuje, to si ti,
{69772}{69821}kada si|daleko od mene.
{69830}{69908}Ono öto me peËe,|to je tvoja koûa,
{69917}{69975}kada je drugi|previöe sanjaju.
{69981}{70091}Ono öto me plaöi,|to su tvoje ûelje,
{70099}{70208}kada viöe|nisam deo njih.
{70440}{70494}Oko nevernih senki,
{70502}{70569}rizikujem svoj|ûivot u svakom trenu,
{70580}{70644}i dok drugi snevaju,
{70655}{70724}osvajam|zemlju i vreme.
{70746}{70792}PrelazeÊi|duge pustinje,
{70803}{70872}podiûem se,
{70881}{70948}ponekad kad sve treba|ponovo napraviti,
{70956}{71049}sam pred|spoljnim svetom.
{71065}{71166}Da li me to|zaista dotiËe?
{71178}{71259}Ono öto me|dotiËe, to si ti,
{71267}{71317}i zvuk tvog glasa.
{71328}{71407}Ono öto me povreuje,|to su tvoje ruke,
{71416}{71471}ako se otvore za|nekog drugog osim mene.
{71478}{71557}Ono öto me ubija,|to je tvoje srce,
{71567}{71619}kada me njegovi|otkucaji varaju.
{71627}{71730}Ono öto me povreuje,|to su tvoje ûelje...
{71747}{71878}Ja, svedok|tvog ûivota,
{71930}{72023}tvojih ûelja,
{72080}{72174}tvog ûivota,
{72228}{72343}tvojih ûelja.
{72379}{72456}Ono öto me|dotiËe, to si ti,
{72474}{72515}i zvuk tvog glasa.
{72527}{72605}Ono öto me povreuje,|to su tvoje ruke,
{72617}{72664}ako se otvore za|nekog drugog osim mene.
{72677}{72756}Ono öto me ubija,|to je tvoje srce,
{72765}{72818}kada me njegovi|otkucaji varaju.
{72829}{72934}Ono öto me povreuje,|to su tvoje ûelje...
{72945}{73003}Ja, svedok|tvog ûivota,
{73016}{73062}Ono öto me|dotiËe, to si ti.
{73127}{73212}Ono öto me|povreuje, to si ti.
{73218}{73271}Ono öto me|povreuje, to si ti.
{73280}{73355}Ono öto me|ubija, to si ti.
{73366}{73416}To si ti,
{73430}{73504}ono öto me|povreuje.
{73520}{73553}Ono öto me povreuje,|to su tvoje ûelje...
{73560}{73687}Ja, svedok|tvog ûivota.
{73896}{73971}Da li su moje|ûelje sada za osudu?
{74042}{74094}Ima jedna koja Êe te|zadovoljiti, Cezare.
{74167}{74222}Nosim u sebi|plod naöe ljubavi.
{74317}{74344}Dete!
{74373}{74465}Da, dete! Tvoj|naslednik, Cezare.
{74500}{74588}Egipat Êe se povezati|sa Rimom zauvek.
{74639}{74713}Sada, naöe sudbine|su zauvek ujedinjene.
{74769}{74805}Molim te za jednu|uslugu, Cezare.
{74821}{74851}Dozvoli mi da se|vratim u Egipat.
{74872}{74902}éelim da ponovo|zauzmem svoj tron
{74915}{75003}i da naöem detetu podarim|buduÊnost dostojnu svog ranga.
{75239}{75311}Cezar Êe bitu tu za|minut ili dva. Vreme leti!
{75319}{75391}Prijatelji moji, on Êe|podneti zahtev Senatu
{75397}{75431}da ozakoni poligamiju.
{75438}{75473}»uo sam to iz|pouzdanog izvora.
{75478}{75518}On Êe mu dozvoliti|da se oûeni Kleopatrom
{75525}{75572}i da proglasi Cezariona|svojim naslednikom.
{75587}{75634}Onda Êe Rim pasti|pod jaram Egipta.
{75655}{75686}To je sramota!
{75698}{75744}Ne moûemo viöe da|podnosimo takva poniûenja!
{75750}{75794}Cezar moûda misli|da sedne u Senat
{75800}{75864}kao boûanstvo|na zlatnom tronu?
{75872}{75967}Kad pomislim da je odbio krunu koju|mu je Antonije tri puta ponudio!
{75989}{76044}Laûni postupak da bi|prikrio svoju ambiciju!
{76052}{76100}Uskoro Êe i novi kalendar|da ponese njegovo ime.
{76114}{76148}A tako Êe biti i|sa svakom ulicom,
{76155}{76245}svakim hramom i na svakom|kamenu na koji stanete, na svemu!
{76250}{76284}Sve Êe biti sa|njegovim potpisom!
{76304}{76344}Ne moûe da upropasti|i republiku!
{76352}{76377}Strpljenja,|prijatelji moji.
{76388}{76475}Kroz nekoliko sati,|predsedavaÊe Senatom i tu, javno,
{76485}{76527}napaöÊemo ga|u ime slobode!
{76531}{76578}Cezar nikada nije|umeo da izbegne zavere.
{76585}{76624}Moramo u|akciju, brûe!
{76630}{76708}Prijatelji moji, Rim Êe se|uskoro roditi pod novim danom!
{77986}{78070}Moja kraljice...|Cezar...
{78104}{78141}Upravo je ubijen...
{78180}{78217}Uboden je u Senatu.
{78225}{78255}Od strane Bruta,
{78268}{78318}tog izdajnika kojeg je|smatrao svojim sinom!
{78346}{78382}Morate brzo da|napustite Rim.
{78408}{78431}Cezare!
{78438}{78484}Rim je konaËno pokazao|svoje pravo lice!
{78490}{78507}Beûite!
{78515}{78575}Zaverenici Êe uskoro biti|ovde da zavröe svoj posao.
{78590}{78643}Tvoj ûivot i ûivot tvog sina|Cezariona su u opasnosti.
{78661}{78683}Antonije je u pravu.
{78698}{78770}Ti si ovde samo strankinja|koju treba eliminisati.
{78805}{78830}Vratimo se u|Aleksandriju.
{78841}{78896}Treba da uzmeö u svoje|ruke buduÊnost Egipta!
{78906}{78959}DaÊu vam pratnju od nekoliko|poverljivih ljudi do kapije.
{78968}{79074}Kako da viöe poverujem|jednom Rimljaninu? Odlazi!
{79083}{79106}Nemamo izbora!
{79130}{79239}Prihvatimo Antonijevu pomoÊ|i spremimo se za odlazak.
{79258}{79298}Otpratio bih|te, da mogu.
{79310}{79343}Ali, pre svega drugog,
{79359}{79408}moram da osvetim|Cezarovu smrt.
{79919}{79990}Sve se sruöi,|danas ili sutra,
{80003}{80089}Ëak i ako to ne|ûelimo da priznamo.
{80102}{80180}Kada se taj dan|desi i probije vrata,
{80189}{80292}nikada nismo spremni|da se predamo,
{80300}{80401}zatvorimo se ponovo.
{80423}{80493}Kada je|kocka baËena,
{80504}{80592}kada ti sudbina|prepreËi put,
{80600}{80681}seti se da je|bolje da se odvojiö,
{80692}{80783}niËemu ne sluûi|da se drûiö
{80794}{80891}svojih sumnji.
{80915}{81001}Tamo te|nebo poznaje,
{81010}{81096}ljuljuöka joö|tvoje detinjstvo,
{81105}{81188}seti se da treba da|se sa njim spojiö.
{81198}{81295}Uvek postoji neka|zvezda u daljini,
{81302}{81407}koju treba pronaÊi.
{81440}{81480}Treba otiÊi.
{81487}{81560}PoËni odlaskom.
{81572}{81617}Bolje videti
{81625}{81658}i videÊeö,
{81667}{81720}nastavi negde,
{81733}{81796}jer to je jedino|öto moûe da se uradi.
{81804}{81840}Treba otiÊi.
{81849}{81932}PoËni odlaskom.
{81941}{81981}Bolje videti
{81990}{82026}i videÊeö,
{82032}{82083}nastavi negde,
{82102}{82195}jer to je jedino|öto moûe da se uradi.
{82596}{82635}Treba otiÊi.
{82647}{82714}Zavröiti odlaskom.
{82730}{82791}éelimo ponovo|da napravimo,
{82798}{82841}a zatim i da|ponovo ûivimo.
{82862}{82899}ZapoËni negde,
{82908}{83015}jer to se joö|moûe uraditi.
{83062}{83092}Treba otiÊi.
{83099}{83184}PoËni odlaskom.
{83191}{83232}Bolje videti
{83242}{83273}i videÊeö,
{83281}{83337}nastavi negde,
{83347}{83411}jer to je jedino|öto moûe da se uradi.
{83424}{83463}Treba otiÊi.
{83468}{83545}PoËni odlaskom.
{83555}{83596}Bolje videti
{83605}{83638}i videÊeö,
{83649}{83704}nastavi negde,
{83716}{83780}jer to je jedino|öto moûe da se uradi.
{83898}{83978}Jer to je jedino|öto moûe da se uradi.
{84003}{84076}Jer to je jedino|öto moûe da se uradi.
{84083}{84191}Jer to je jedino|öto moûe da se uradi.
{84365}{84452}Kraj I Ëina.
{84477}{85977}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3xnz8|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
