{25}{175}-== [ www.OpenSubtitles.com ] ==-
{1691}{1821}POTONULA SRCA
{2438}{2494}Paket za Roberta Garfilda.
{2499}{2546}- Potpiöite.|- Hvala.
{3708}{3804}MESNI RATNI JUNAK|POGINUO U AUTU
{3904}{4022}Kad god to ûeli,|proölost vas iznenadi.
{4050}{4134}I ne znate gde Êe vas odvesti.
{4152}{4237}Samo se nadate da tamo ûelite otiÊi.
{4645}{4706}Zovite ih na mobilni.
{4712}{4817}Ja idem na put do utorka.
{4950}{5043}U ime predsednika SAD-a|i zahvalnog naroda...
{5048}{5100}...predajem vam ovu zastavu...
{5105}{5164}...u znak seÊanja...
{5170}{5256}...na Ëasnu sluûbu vaöega muûa|majora Dûona Salivena.
{5262}{5334}- Sali!|- Hej!
{5339}{5426}OdluËio sam öta Êu biti|kad odrastem. MaioniËar.
{5432}{5537}- Iz öeöira Êu vaditi zeËeve.|- ZeËevi Êe ti srati u öeöir.
{5541}{5608}Ali priznaj da bih bio straöan gad.
{5873}{5993}U Domu veterana ima kafe i kolaËa.|Moûete doÊi, svakako.
{6089}{6146}- G. Garfild.|- G. Oliver.
{6150}{6245}- Hvala na rukavici.|- Odavno sam Salijev advokat.
{6251}{6352}Ne znam zaöto je bejzbolska|rukavica morala u nasledstvo.
{6383}{6505}- Vi i Sali odrasli ste skupa?|- Da, bili smo troje.
{6510}{6579}Ja, Sali i cura, Kerol.
{6585}{6629}- Kerol Gerber?|- Tako je.
{6634}{6684}Nadao sam se da Êe biti tu.
{6737}{6797}Niste Ëuli za Kerol?
{6854}{6886}Nisam.
{6977}{7021}Naûalost, mrtva je.
{7074}{7112}Moje sauËeöÊe.
{8150}{8212}U ovoj se ulici sve dogodilo.
{8235}{8277}Sad nije niöta posebno.
{8304}{8385}Zaöto oËekujemo da Êe domovi ostati isti?
{8405}{8452}Sve se ostalo menja.
{8740}{8860}»udno, kad ste dete,|dan moûe trajati veËno.
{8879}{8991}Sve se ove godine Ëine kao treptaj.
{10066}{10115}Bobi? Bobi-o!
{10126}{10159}Vreme je za ustajanje.
{10164}{10209}Diûi se iz kreveta.
{10660}{10729}Sretan roendan, g. 11!
{10929}{11014}Opa. Kartica za biblioteku.
{11020}{11115}Za odrasle, molim lepo.
{11178}{11216}Hvala, mama.
{11238}{11271}Nemoj.
{11286}{11385}Misliö da nisam htela da dobijeö|bicikl? Nemam novca.
{11391}{11493}Znaö li kako mi je? Ali tvoj|nam otac nije ostavio novca.
{11498}{11573}Samo tri meseca neplaÊene stanarine...
{11578}{11669}...polisu osiguranja koja je istekla|pre nego öto je umro.
{11674}{11759}Ostavio nam je brdo neplaÊenih raËuna...
{11763}{11816}...koje sam sredila.
{11822}{11888}Jer su ljudi shvatili naöu situaciju.
{11892}{11944}G. Biderman s posla...
{11949}{12029}...bio je susretljiv,|ali nije bilo lako.
{12034}{12146}Recimo ovako.|Tvoj je otac rado iöao na fleö.
{12151}{12233}- äta je fleö?|- Nije bitno.
{12237}{12364}Nemoj da te uhvatim da se kockaö.|Bilo mi je dovoljno za ceo ûivot.
{12381}{12416}Hajde!
{12474}{12553}To je sigurno novi stanar za gornji stan.
{12563}{12678}Ne verujem ljudima koji nose|stvari u kesama. Kurvinski je.
{12684}{12775}- On ima kofere.|- Ali ne iste.
{12780}{12846}Zdravo. Ted Brotigan.
{12851}{12896}Neko Êu vreme stanovati gore.
{12901}{12972}Elizabet Garfild.|Moj sin Robert.
{12977}{13041}Drago mi je, g. Bratigan.
{13047}{13114}Brotigan sam, ali moûete me zvati Ted.
{13124}{13214}Drago mi je.|Nadam se da Êe vam se sviati tu.
{13220}{13255}Hvala, Roberte.
{13366}{13392}SlavljeniËe!
{13422}{13499}Kerol, dovoljno je öto smo|prijatelji i bez tih fora.
{13504}{13564}Svidelo ti se. Evo.
{13580}{13646}- BiÊe sentiö?|- Ne znam.
{13654}{13697}Bolje da ne bude.
{13782}{13838}- Baö takva bicikla.|- Da, to je sjajno.
{13844}{13875}SRETAN RO–ENDAN
{13880}{13923}Hvala.
{13989}{14092}- Nisi dobio biciklu, zar ne?|- Niöta straöno. Mama nema love.
{14098}{14130}Kupuje nove haljine.
{14134}{14235}Mora biti lepa za posao. Ideö?
{14272}{14314}Da!
{14487}{14534}Sali!
{14639}{14669}- Dobio si biciklu?|- Nisam.
{14674}{14768}Nemam niöta za tebe.|Ali, sretan roendan, gade!
{14959}{15012}Laköe! »ekajte me!
{15653}{15746}- äta je fleö?|- Ima veze s kockom, zar ne?
{15751}{15859}Poker.|To je samo za kretene.
{16032}{16108}Ova Ëetvrt straöno propada.
{16112}{16163}Moram se preseliti.
{16326}{16389}- Da?|- Tako se ljavlja na telefon?
{16395}{16501}Oprosti, mama.|Uzbuen sam zbog veËere.
{16528}{16636}G. Biderman mora raditi do kasno,|molio je i mene.
{16641}{16709}VeËeras u "Koloniji" otpada.
{16714}{16738}Dobro.
{16744}{16835}U hladnjaku ima ostataka.|DoÊi Êu kuÊi da te pokrijem.
{16840}{16911}Ugasi plin kad zavröiö...
{16916}{16970}...sa ötednjakom.
{16975}{17045}- Znam.|- Vidimo se.
{17469}{17503}Dobra veËer, Roberte.
{17522}{17566}Ili da kaûem Bobi?
{17572}{17640}G. Brotigan.
{17646}{17677}Ted.
{17716}{17823}To Êe mi biti teûe, ali pokuöaÊu.
{17845}{17888}Ideö posle napolje?
{17952}{18020}Trebao sam veËerati s mamom...
{18025}{18119}...no ona mora raditi.|Iako to nije htela.
{18181}{18233}Jesi li bogataö?
{18266}{18312}Radi roendanskog dara.
{18440}{18481}Kartica za biblioteku?
{18502}{18564}Ne, za odrasle. Boûe.
{18579}{18644}»ekaju te svi najbolji svetski pripovedaËi.
{18649}{18743}Znate zaöto baö to?|Besplatno je.
{18763}{18851}To nije bitno.|Ne bacaj tu legitimaciju.
{18856}{18912}Knjige su suvo zlato.
{18930}{19029}Najbolje nam vekovima pomaûu|da prebrodimo noÊ.
{19047}{19158}Daj piscu vremena da te upeca.|Ne uspe li, nai drugoga.
{19174}{19214}Misliö da moûeö pokuöati?
{19246}{19307}Ako nemam druga posla.
{19322}{19386}Poöteno. Ne boj se.
{19392}{19490}PriËa o dva grada|zavröava odrubljivanjem glave.
{19495}{19611}"Izgubljeni horizont", Ëarolijom|i nepoznatim mestima. Niöta bolje.
{19656}{19757}Odakle ste otiöli pre nego öto ste|doöli ovamo, g... Tede?
{19773}{19841}S mesta koje nije bilo ovako lepo.
{19870}{19902}Ti dugo ûiviö ovde?
{19931}{20007}Da, otkako mi je tata umro.
{20024}{20101}- Kad je bio taj tuûan dan?|- Kad sam imao 5 g.
{20125}{20165}äest godina.
{20188}{20265}Kladim se da znaö sve öto se|dogaa na ovoj ulici.
{20270}{20405}Svakako.|Jer ovde se niöta ne dogaa.
{20482}{20566}- äest godina.|- To je tek treptaj.
{20572}{20623}Jednog Êeö se dana sloûiti.
{20651}{20760}Ben Dûonson zvao je vreme|"starim Êelavim prevarantom".
{20774}{20800}Molim?
{20805}{20899}Stari Êelavi prevarant.
{20904}{20941}Svia mi se to.
{20947}{21049}Mislim da se i meni svia.|Ko je Ben Dûonson?
{21055}{21128}Engleski pisac, odavno je umro.
{21143}{21201}Briljantan, ali blesav s novcem.
{21205}{21298}I sklon vetrovima.
{21303}{21353}äta su vetrovi?
{21548}{21611}Deca uvek misle da je prdeû smeöan.
{21698}{21786}Moûda budem imao posao za tebe.|Prvo moram razmisliti.
{21806}{21839}Zaista?
{21845}{21929}Da. Bude li iölo kako treba,|moûda dobijeö taj bicikl.
{22032}{22085}Kako ste znali da ûelim bicikl?
{22112}{22156}Sva deca ûele bicikle.
{22901}{22977}Mama, opet sam pogledao taj bicikl.
{22982}{23087}Fantom, s toËkovima od 65 cm.|Zaista super.
{23097}{23174}Ne, savröen.|To je bolja reË.
{23180}{23230}PoËni ötedeti novËiÊe.
{23283}{23334}Tede? Ja sam.
{23349}{23375}Ui, mali.
{23380}{23438}Hvala öto si preöao put do neba.
{23450}{23514}Nagrada je bezalkoholno pivo.
{23520}{23563}äto hladnije, to bolje.
{23604}{23680}Prvo ih osetiö iza oËiju.
{23704}{23741}äta osetiö?
{23798}{23877}Prvo ih osetiö iza oËiju.
{24008}{24036}Da.
{24101}{24149}UËinio sam öta ste rekli?
{24155}{24210}- äta?|- Dao sam mu nekoliko sati.
{24216}{24293}"Izgubljeni horizont".|I kako ti se Ëini?
{24298}{24341}Bolje od romana za decu.
{24347}{24385}To svakako.
{24461}{24575}Reci, Bobi...|Bi li voleo zaraditi dolar nedeljno?
{24580}{24610}I te kako!
{24615}{24679}Iskreno, oËi me viöe ne sluûe.
{24684}{24807}Budeö li mi svaki dan Ëitao|HarviË Dûurnal...
{24813}{24887}...naslove, sport, stripove, oglase...
{24892}{24973}...daÊu ti dolar. äta kaûeö?
{25039}{25072}äta joö?
{25080}{25111}Kako to misliö?
{25115}{25177}Sigurno postoji joö neöto.
{25217}{25261}Da. Postoji.
{25302}{25346}äta je pravi posao?
{25376}{25427}Drûi oËi otvorene.
{25431}{25500}- äta traûim?|- Podle ljude.
{25536}{25576}Tako je.
{25606}{25692}Podlo koristim u Dikensovskom smislu,|öto znaËi opasne.
{25697}{25815}Beskrupulozne, koji ne prezaju|ni pred Ëim da dobiju öta ûele.
{25825}{25899}Pravi Êe ti posao biti...
{25911}{25958}...da hodaö okolinom.
{25980}{26059}Ugledaö li njih ili dokaze da su bili tu...
{26065}{26112}...smesta Êeö mi javiti.
{26116}{26200}U redu.|Zaöto su vam za petama?
{26299}{26407}Zbog neËega öto imam.|Neka ostane na tome.
{26458}{26499}Kako izgledaju?
{26564}{26657}Tamna odela, tamni öeöiri.
{26692}{26742}Anonimno...
{26748}{26821}...no prepoznajeö ih po autima.
{26826}{26879}Napadnima i upadljivima.
{26922}{26979}KreÊu se u Ëoporima...
{26984}{27046}...poput ûivotinja koje idu ubiti.
{27137}{27185}I bacaju dugaËke senke.
{27265}{27302}Kakav svet.
{27411}{27483}Nisu panduri, zar ne?
{27496}{27540}Ili tajni agenti?
{27578}{27687}Pitaö jesam li zao Ëovek,|crveni öpijun?
{27714}{27767}Istina, izbegao sam neke kazne.
{27774}{27839}Da su bibliotekarska policija...
{27845}{27911}...bio bih meu najtraûenijima.
{27940}{28058}Ali nisam opljaËkao banku|ni ukrao vojnu tajnu.
{28070}{28109}A ko su oni?
{28145}{28202}Lupeûi, nasilnici,|zovi ih kako ûeliö.
{28211}{28270}Buldozi, neumorni kad neöto traûe.
{28275}{28349}- Poput toga öto imate?|- Tako je.
{28395}{28492}éele me vratiti pod svoj nadzor.
{28498}{28565}Zato budi na oprezu,|jer kad se pribliûavaju...
{28582}{28659}...ostavljaju tajne öifrovane znakove...
{28664}{28744}...na javnim mestima|poput telefonskih stubova.
{28749}{28841}Plakati i obaveötenja o izgubljenim|ljubimcima i psima.
{28904}{28992}Da znam öta Êe uËiniti, nikad|me ne bi uhvatili, ali ne znam.
{28998}{29105}- äta ako ih vidim?|- Pobegni i reci mi öta si video.
{29116}{29197}SeÊaö se kad sam te pitao|znaö li öta se dogaa ovde?
{29203}{29314}- Svakako.|- Zato raËunam na tebe.
{29496}{29569}Bez brige, neÊu dopustiti|krimosima da vas uhvate.
{29574}{29660}- Bobi, gore si?|- Bez brige, ne zna öta misliö.
{29665}{29760}Ti misliö da zna.|To je majËinska moÊ.
{29815}{29853}Go Garfild.
{29935}{29996}Zgodno je ovde.
{30001}{30069}Mama, Ted...|G. Brotigan...
{30075}{30174}PlaÊaÊe mi dolar nedeljno|da mu Ëitam novine.
{30188}{30250}Veoma ste dareûljivi.
{30254}{30340}Uvek vam mladi deËaci|Ëitaju novine, g. Bratigan?
{30345}{30388}Brotigan, gospoo.
{30405}{30473}I da, treba mi neko za to.
{30477}{30549}Od penzije mi oËi nisu kao öto su bile.
{30553}{30614}»ime ste se bavili?
{30619}{30695}Radio sam na severu,|na raznim mestima.
{30824}{30915}Doi, Bobi.|Svet te neÊe Ëekati.
{30949}{31004}- Dovienja, g. Brotigan.|- Bobi.
{31252}{31304}Pogodi öta g. Brotigan...
{31422}{31481}Neöto mi nema smisla.
{31486}{31573}Zaöto Ëovek njegovih godina|toliko ûeli biti s detetom?
{31577}{31610}Ne znam.
{31627}{31714}Ali znam da je rekao da sam sretan deËak...
{31720}{31770}...kad mi je majka za roendan...
{31775}{31866}...dala biblioteËku legitimaciju|za odrasle.
{31907}{31962}Ne znam.
{31967}{32042}Ne verujem mu previöe.
{32048}{32172}Da, upropasti mi sve.|Ne ûeliö da kupim bicikl.
{32177}{32247}éelim! Volela bih da sam ti ga ja kupila!
{32253}{32331}Ali tvoj nas otac nije ostavio imuÊne.
{32353}{32394}To je samo Ëitanje.
{32540}{32604}Ma dobro, nema ötete.
{32651}{32745}Ali samo na tremu, na vazduhu.
{32754}{32779}U redu.
{33302}{33359}Oprostite öto kasnim,|zaboravio sam na vreme.
{33363}{33389}Nema veze.
{33408}{33495}Svi smo robovi, taoci veËnosti.
{33500}{33525}Ben Dûonson?
{33554}{33601}Ne, Boris Pasternak.
{33608}{33702}Bio je Rus. Niko vaûan.
{33724}{33804}äta se dogaa u svetu?|Verovatno neöto besramno.
{33810}{33864}"Potpredsednik Nikson...
{33870}{33946}...osiguravöi nominaciju|u prvom krugu...
{33951}{34052}...pregovara|s Henrijem Kebotom Lodûom..."
{34061}{34164}- Idemo na sladoled. HoÊeö s nama?|- Ne, zaraujem hleb svagdanji.
{34198}{34284}- Dobar dan, gice Gerber, Kerol.|- ∆ao, Tede.
{34331}{34438}Nisam video curu koja je tako|posebna kao Kerol Gerber.
{34449}{34483}Ima ih milion.
{34489}{34516}Da?
{34553}{34615}- Poljubio si je veÊ?|- Fuj!
{34632}{34705}- HoÊeö, obeÊavam ti.|- Dalje od mene!
{34742}{34831}Po tom Êeö poljupcu meriti...
{34836}{34941}...sve ostale u ûivotu.|I biÊe loöiji.
{34992}{35023}Zavröili ste?
{35074}{35173}Jesam. Daj, Ëitaj mi.
{35177}{35259}- Vrati se i radi svoj posao.|- U redu.
{35314}{35352}Ali poljubiÊeö je.
{36792}{36915}"FBI objavljuje nove mere za|borbu protiv crvenih infiltratora."
{36976}{37029}Hej, Bobi.
{37035}{37113}Kad doeö do Fleöa Gordona,|reci mi öta Dejl ima na sebi.
{37138}{37194}Zaöto vas ona toliko zanima?
{37216}{37321}Kad sam bio mlai,|mislio sam da je seksi.
{37357}{37462}Pre stripova imamo sport. Bejzbol.
{37466}{37567}"Mori Vils na putu da sruöi|rekord Taja Koba."
{37573}{37597}Gledao sam Koba.
{37620}{37711}Moj je tata gledao Bejba Ruta.|Kako najavljuje optrËavanje.
{37716}{37796}Protiv "Kabsa".|Pripovedao mi je.
{37801}{37861}A o povratniËkoj igri Nagurskog?
{37913}{38004}Znam da ju je gledao. I vi ste?
{38009}{38116}- Jesam.|- Vi i tata bili ste na istome mestu.
{38139}{38182}Znaö za Bronka Nagurskog?
{38206}{38265}Bio je uzor mome tati.
{38277}{38365}Najbolji igraË "futbola" ikad.|Posle studija...
{38371}{38447}...igrao je 8 g. za "Medvede"|i postali su prvaci.
{38452}{38545}Tad se povukao.|Posle 6 g. penzije...
{38549}{38607}..."Medvedi" su ga vratili kao zamenu.
{38612}{38681}Poslednjeg dana sezone igrali su protiv...
{38686}{38741}..."Kardinala".|Ljutih neprijatelja.
{38771}{38849}Medvedi su morali dobiti|kako bi osvojili titulu.
{38855}{38969}Nagurski nije trebao igrati.|Bio je druga zamena.
{39011}{39072}U prvome poluvremenu igraË|iz poËetne postave se povredio.
{39080}{39165}U drugome poluvremenu|igraËi se naoöe na gomili.
{39171}{39255}Ako ti je tata pripovedao,|rekao je da se prestraöio.
{39260}{39376}- Bio je jako prestraöen.|- Ali zaöto? Nagurski je igrao.
{39382}{39433}I ja sam se bojao.|Kao i svi.
{39449}{39519}Vidiö, hteli smo Ëudo.
{39537}{39620}Hteli smo starog Nagurskog.
{39635}{39708}Hteli smo onakvog, kakav je|bio u proölim danima.
{39729}{39827}Je li bio uspeöan?|Ne ûelim sluöati ako nije.
{39907}{39967}DodavaË mu je dao loptu.
{39979}{40057}Nagurski je polako dotrËao do crte.
{40070}{40121}"Kardinali" su ga okruûili.
{40131}{40158}Ali nekako...
{40211}{40295}Osvojio je nekoliko metara.
{40303}{40340}U iduÊoj akciji isto.
{40346}{40447}I u iduÊoj.|Davali su loptu starcu...
{40472}{40600}...i "Medvedi" su krenuli niz teren.|5 m. 10 m. Joö 7.
{40638}{40729}Kad bi poentirao, pobedili bismo.|Opet bismo bili prvaci.
{40799}{40869}Nastavi! Ne smeö prestati!
{41010}{41039}Tede!
{41072}{41130}Daj, moram znati öta je bilo.
{41255}{41287}Hajde.
{41292}{41349}Znaö öta je tvoj tata uËinio?
{41353}{41403}Ne. äta?
{41408}{41522}SkoËio je urlajuÊi na noge. Svi smo.|Nismo mogli verovati öta se dogaa.
{41527}{41579}Boûe, öta je bilo?
{41596}{41706}Vidiö, to je bilo naöe Ëudo.|Jer on je puzao.
{41729}{41812}Bronko Nagurski puzao je|prema crti polaganja.
{41817}{41901}»inili su sve da ga zaustave.
{41919}{41966}I niöta nije delovalo?
{41972}{42080}Tako je. Ne toga dana.
{42125}{42189}Ne kad smo tvoj tata i ja videli Ëudo.
{42204}{42263}Kad nam je starac doneo titulu.
{42326}{42408}Postigao je polaganje.|Poentirao je za nas.
{42458}{42502}Opet smo bili prvaci.
{42523}{42576}Znao sam da jeste.
{42663}{42777}I tad je opet nestao.|Na sever, odakle je doöao.
{42821}{42871}Bronko Nagurski.
{42902}{42970}Bobi? Bobi-o!
{43398}{43444}Tede?
{43463}{43530}Znam da podlaci ne postoje...
{43535}{43612}...no poËnu li se vozikati...
{43623}{43716}...pojave li se Ëudni plakati|na telefonskim stubovima...
{43735}{43805}Znamo da je to nemoguÊe.
{43837}{43878}Ali ako se dogodi...
{44135}{44189}Bi li morao otiÊi?
{44264}{44330}Da. Viöe ne bi bilo sigurno.
{44355}{44416}A od ûelja neÊe ni biti.
{44423}{44457}Bobi!
{44850}{44925}Taj tvoj Ted...
{44984}{45048}Je li ti rekao odakle je?
{45061}{45133}Iz ne tako lepog mesta kao öto je ovo.
{45200}{45289}To nam ne govori mnogo.
{45308}{45389}- Jel rekao joö neöto?|- Ne.
{45488}{45512}Bobi.
{45624}{45724}- Je li...?|- äta?
{45840}{45874}Niöta.
{45914}{45985}ObeÊaj da Êeö mi reÊi|dogodi li se neöto neobiËno.
{46055}{46088}Halo?
{46214}{46250}ObeÊali ste.
{46255}{46297}Zaista mi treba...
{46356}{46389}Ko je to bio?
{46406}{46468}Niöta, pogreöan broj.
{46643}{46684}Pasji skot!
{47265}{47345}- Znam da si ti, Bobi!|- Mama ti je skoro gotova.
{47350}{47409}- éeli li i Ted doÊi?|- U zabavni park?
{47414}{47489}- Ne bi li hteo da ga pitaö?|- Valjda.
{47518}{47585}UËini to. Idem po Salija.
{47636}{47735}- Voliö kad te cura pobedi?|- Nije poöteno!
{48039}{48112}- G. Biderman me treba.|- U subotu?
{48117}{48217}- Neki ljudi rade za svoj novac.|- Mama, obeÊala si.
{48223}{48303}To su mentolke. »itaj reklamu.
{48309}{48411}"Kuls - hlade grlo."|Gotovo da nisu cigarete.
{48416}{48449}- Mama?|- äta je?
{48455}{48504}Mogu dobiti novac za voûnje i to?
{48509}{48601}Nikad kraja.|Ne zaraujeö li sad?
{48605}{48632}To je za bicikl.
{48637}{48761}Tvoj problem ako ga ûeliö|potroöiti na voûnje s curom.
{49222}{49317}Tede, ja sam.|HoÊeö u zabavni park?
{49453}{49479}Tede?
{49939}{49994}Sve u redu?
{50223}{50266}Tede, probudi se.
{50351}{50393}Moraö mi pomoÊi.
{50410}{50470}Ne znam öta bih.
{50482}{50539}Sad idu na zapad.
{50560}{50607}Ko? Isuse, Tede,|molim te.
{50632}{50724}Idu na zapad, ali moûda se vrate.
{50841}{50933}Tede, molim te, nemoj umreti.
{50978}{51004}Molim te.
{51113}{51155}O, Boûe.
{51175}{51227}äta se to dogodilo?
{51332}{51370}Opet sam se iskljuËio?
{51400}{51487}- Misliö kao hladnjak?|- Da.
{51493}{51557}Ne, mnogo gore.
{51593}{51663}Mislio sam da imaö napad.
{51709}{51735}U redu je.
{51750}{51810}Ali ponovi li se, najbolje da me ne diraö.
{51828}{51891}Niko me ne bi trebao dirati.
{51903}{51941}Oprosti.
{52002}{52080}- Mogu te ostaviti samog?|- Da.
{52161}{52199}U redu je.
{52314}{52343}U redu.
{52461}{52523}Ga Gerber vodi nas u zabavni park.
{52527}{52607}Kerol i ja mislili smo da bi hteo s nama.
{52612}{52734}Hvala, ali mislim da sad to nije pametno.
{52992}{53047}Cigarete su na stolu.
{53103}{53149}Hvala, mali.
{53175}{53209}äta je tako smeöno?
{53226}{53340}Odlazi, uûivaj.|Nemoj pasti s neËega.
{54545}{54586}Kako Êeö je zvati?
{54591}{54716}U redu!|Ko se oseÊa sretnim?
{54722}{54778}Naite damu herc|i pobedite!
{54854}{54896}Niöta laköe!|Lako kao perce!
{54901}{54974}Samo naite damu herc.
{54982}{55081}- Stavite novac. PonoviÊu.|- Samo Ëetvrt dolara.
{55085}{55110}Evo deËka.
{55122}{55247}I tu je kralj. I dama.|Samo recite gde je dama.
{55386}{55450}- SreÊa vas Ëeka.|- Ova.
{55471}{55503}Da! Da!
{55509}{55598}Dvostruko i joö pola dolara.
{55892}{55927}Ova.
{55957}{56029}Dosta, deco.|Moramo prekinuti.
{56033}{56118}- Mogu ga nadmaöiti. Pratiti mu ruke.|- Onda se mogu predati.
{56124}{56189}Samo Ëetvrt dolara.
{56231}{56353}Gore-dole, naokolo.|Unutra-van, pa na stranu.
{56358}{56392}Sad se vrate.
{56398}{56463}Jedna uz drugu ûiva.
{56469}{56542}Recite gde se skriva.
{56568}{56599}Ova desno.
{56609}{56685}Ne, levo. To je moja mala.
{56763}{56811}Sad je dosta.
{56816}{56872}Bobi je imao pravo.
{56878}{56984}- Zaöto ne vratiö sve izgubljeno?|- Mogu, ali ne smem kartati za novac.
{56989}{57013}Hvalisavko.
{57019}{57089}Kaûe da moûe dobiti,|ali ne usuuje se.
{57097}{57184}Vratio bih svoj novac.|Pobedi ga za mene.
{57189}{57294}Ne mogu dopustiti.|Mama ti ne bi bila sretna.
{57298}{57377}Moja mama nikad nije sretna.|To je sve öto imam.
{57382}{57506}Ovaj potez zadivio je öeika|od Arabije. Pogledajte.
{57741}{57798}Ova ovde u sredini.
{57921}{57967}To je to!
{58029}{58058}Samo sam imao sreÊe.
{58063}{58156}UdvostruËi ulog i svi mogu kuÊi sretni.
{58180}{58215}Dobro.
{58383}{58447}IduÊa je 5 g. moga ûivota.
{59427}{59467}Ova ovde.
{59528}{59582}Ovoga niko nije pogodio.
{59647}{59713}Pa, jeste ili nije?
{59863}{59948}- Bilo je sluËajno.|- Moûeö se kladiti.
{60037}{60069}Sad tutanj, mali.
{60074}{60164}Idemo, druötvo. Dosta je.|Doi, Bobi.
{60229}{60283}Priite! Imali smo pobednika.
{60288}{60355}Niöta laköe!|Lako kao perce!
{60860}{60896}Ne boj se.
{60901}{61007}Kad smo krenuli, bojala sam se|da smo se otkaËili i padamo.
{61031}{61089}Veoma smo sigurni.
{61181}{61242}Koga to vraga radiö?
{61248}{61315}Mislio sam da to ûeliö.
{61357}{61430}Samo nisam bila spremna.
{61445}{61479}Dobro.
{61556}{61650}- Bobi, ponovi to.|- Radije ne bih. TuûiÊeö me.
{61661}{61754}Ne, biÊe to naöa tajna.|Brûe, dok se ne spustimo.
{61851}{61930}Bobi, umirem.
{62416}{62488}Hvala. To je bilo neöto najlepöe.
{62521}{62612}Po tome Êeö poljupcu|meriti sve ostale u ûivotu.
{62617}{62647}Molim?
{62659}{62727}Ne znam. ZvuËalo je bolje|kad je Ted to rekao.
{63218}{63318}Znao si gde je dama srce, zar ne?
{63350}{63441}Da. Kao da sam znao sve|öto mu se dogaa u glavi.
{63446}{63542}Znao sam sve öta misli|i nije me mogao prevariti.
{63549}{63622}Znaö öta se dogaa u Salijevoj glavi?
{63656}{63700}Uvek je prazna.
{63705}{63805}Da? Moûda razmiöljam o novoj|rukavici za iduÊu godinu.
{63810}{63889}A öta Êe biti s ovom?
{63918}{63986}- Zaista je ûeliö?|- äaliö se? Oboûavam je.
{63993}{64061}- Onda je tvoja.|- Jeste?
{64066}{64119}OstaviÊu ti je testamentom.
{64161}{64257}- Sali, oboûavaö to da radiö!|- Opet sam te preöao.
{64309}{64369}Kad si mlad...
{64374}{64443}...doûiviö takvu sreÊu...
{64449}{64541}...da pomisliö da ûiviö|na Ëarobnome mestu.
{64561}{64609}Kao öto je bila Atlantida.
{64614}{64726}Kerol, dugujem ti 75 $|i ti si na redu.
{64775}{64836}- Vrati mi 25.|- 25?
{65003}{65041}Tad odrastemo...
{65096}{65158}...i srca nam se raspolove.
{65677}{65730}- Doi.|- »ekaj.
{65807}{65846}äta je?
{65885}{65934}VIDELI STE SPOTA?|TO JE NAä MALENI TERIJER
{65940}{65982}Pitam se öta to znaËi.
{65996}{66093}Da je neko izgubio psa, glupane.
{66113}{66175}Da, ali moûda je to öifra za neöto.
{66180}{66223}O Ëemu ti to?
{66228}{66297}- Hej, pederu!|- Nisam peder!
{66302}{66370}- Ne razgovaraj s njima!|- Kako ti napreduju sise, Gerberice?
{66375}{66447}- Odlazi!|- Odjebi, Heri Dulin!
{66490}{66548}Usamljeni jahaË!
{66774}{66841}Bobi-o, kako je bilo u ökoli?
{66847}{66894}- Dobro.|- Nikad neÊeö pogoditi.
{66903}{67002}Don... G. Biderman,|pozvao me na seminar...
{67007}{67095}...ovoga vikenda u Providensu.|"Nekretnine u 60-ima."
{67100}{67222}Idu i g. Din i g. Kuömen, ali|iznenadilo me öto je mene pozvao.
{67254}{67298}Bobi.
{67306}{67401}Dugo ûelim biti agentica.|Ovo mi je velika prilika.
{67406}{67447}Sjajno, kad?
{67452}{67499}U petak. Samo dve noÊi.
{67509}{67597}- Ne moûeö spavati kod svoje cure.|- Ona mi nije cura.
{67602}{67666}OËito je zaöto ne moûeö.
{67672}{67754}ZamoliÊu majku Sali-Dûona.
{67758}{67786}NeÊe iÊi.
{67812}{67848}Ali mora.
{67862}{67918}Idu u posetu njegovoj baki.
{67937}{68021}Takve sam ja öugave sreÊe.
{68156}{68277}Pozovi svog prijatelja|da sie na öoljicu Ëaja.
{68300}{68329}Dobro.
{68503}{68568}éalim, go Garfild, ali ne.
{68574}{68665}Bio bih loöa dadilja Bobiju.
{68670}{68767}Ali nikad pre nisu me zvali|na pravi seminar.
{68773}{68880}Moûete spavati na kauËu, veoma je|udoban. Moûete otiÊi u...
{68885}{68960}...restoran, a onda moûda i u bioskop.
{69001}{69081}Ovako, ako Bobi, ûeli, hoÊu.
{69173}{69211}Bobi?
{69252}{69317}Zaöto se ti uvek zabavljaö?
{69335}{69400}Ne ûeliö da napredujem?
{69405}{69495}A ja? Nikad ne dobijem öto ûelim.
{69565}{69588}Ko zna?
{69593}{69717}Moûda mi g. Biderman da poviöicu.|Ko zna öta Êu moÊi kupiti?
{69788}{69871}Ma dobro, to je samo vikend.
{69982}{70049}- Hvala.|- U redu.
{71021}{71087}- »uo si za privatnost?|- Oprosti.
{71092}{71172}»ekaj! Ne moûeö samo tako otiÊi.
{71181}{71278}- Pa öta da radim?|- Reci mi kako izgledam.
{71323}{71358}Kao moja mama.
{71366}{71436}Haljina, mislim na haljinu!
{71485}{71512}Opa!
{71543}{71579}Budi aneo.
{71656}{71752}- Mnogo je koötala?|- Ne poËinji s time.
{72661}{72721}"Po miöljenju reportera...
{72726}{72835}...borba Hejvuda i Albinija|moûe okaljati savröen uspeh."
{72901}{72969}Uvek bih se kladio na Holivuda Hejvuda.
{72978}{73041}Tede, sluöaö li?
{73046}{73102}»ula su im sve osetljivija.
{73188}{73313}Hej! Mali, premlad si da puöiö.
{73341}{73385}Koliko dugo ovaj put?
{73391}{73459}Ruöite sve rekorde.
{73496}{73546}Pribliûavaju se.
{73598}{73678}Dobro se skrivaju od mene.
{73682}{73781}- Joö niöta nisam video.|- Dobro.
{73786}{73834}I pre sam greöio.
{73881}{73931}Nastavi o borbi.
{73936}{74020}Dobro. Taj starac Albini...
{74025}{74135}...sutra u Njujorku boksuje|protiv Holivuda Hejvuda.
{74140}{74251}- »ini se da Êe Albini dobiti batina.|- To svakako.
{74272}{74316}Mogao bih se kladiti.
{74322}{74405}Kad ti majka ode, idemo taksijem|u Bridûport.
{74410}{74499}Pojesti neöto. Pogledati film.
{74504}{74559}»uo si za Selo prokletih?
{74595}{74717}O zloj deci obuzetoj vanzemaljskim silama.
{74817}{74851}Evo.
{75184}{75218}äta je?
{75243}{75305}O, ne, tvoj bicikl.
{75401}{75451}Ostani tu, Bobi.
{76054}{76080}Hvala.
{76378}{76431}Hej, mala Gerberice!
{76508}{76563}Joö si sa svojim pederËiÊem?
{76567}{76602}Doi, Kerol, idemo kuÊi.
{76607}{76673}- Gde si ti krenuo?|- Ovo nije smeöno!
{76678}{76731}Nama jeste, mala Gerberice.
{76747}{76784}Ostavi je!
{76789}{76836}Maleni je junak.
{76853}{76916}Zaustavi me, pederËiÊu.|Budi muökarac.
{76946}{76995}Pitao sam te kako ti napreduju sise.
{77000}{77040}Sad ûelim sam opipati.
{77046}{77080}Makni se od mene!
{77097}{77132}Ostavi je!
{77150}{77190}Ona je samo mala Gerberica.
{77202}{77246}- Gade!|- DeËki.
{77251}{77319}Prebijmo pederËiÊa.
{77564}{77664}- Tede, idi kuÊi.|- Svi idemo kuÊi, Bobi.
{77695}{77764}Ko ti je to, vila zaötitnica?
{77781}{77880}RiËi O'Rurk, Vili äerman i Heri Dulin.
{77884}{77939}Nesveto trojstvo iz Sv. Gebrijela.
{77972}{78004}Kako nam znaö imena?
{78009}{78074}Na tvome mestu doöao bih saznati öta znam.
{78360}{78410}Izvini se Kerol i Bobiju.
{78437}{78507}- Ne bi iölo.|- Da ti kaûem zaöto hoÊeö?
{78530}{78612}Znam tvoju mraËnu tajnu.
{78616}{78703}- I objaviÊu je svetu.|- Ja nemam tajne.
{78736}{78841}Voliö nazivati ljude|pederima i homiÊima.
{78876}{78924}Pogledaj me u oËi.
{78952}{78993}Reci mi öta vidiö.
{79031}{79170}Nekoga odevenog u odeÊu tvoje majke|kad misli da niko ne gleda.
{79209}{79277}Reci celome svetu.
{79300}{79354}Sad reci: "éao mi je, Kerol".
{79470}{79520}Oprosti, Kerol.
{79738}{79786}äta je stari rekao?
{79791}{79824}Niöta.
{79908}{79955}Hvala, ljubazni gospodine.
{79960}{80002}äta si mu rekao?
{80007}{80093}Intelektualne sitnice|izmeu ljudi dobre volje.
{80134}{80204}- Tede?|- Da, slatka Kerol?
{80208}{80318}- Veoma si Ëudna osoba.|- Nemoj nikomu reÊi.
{80457}{80493}Sali ima loptu!
{80498}{80551}- O, ne!|- Polaganje!
{80556}{80587}Ulazi u auto.
{80592}{80629}Uzmi psa!
{80740}{80781}KreÊemo!
{80792}{80901}- ∆ao.|- Sretan put.
{81477}{81523}Boûe, podlaci!
{81688}{81733}Gde je damica?
{81738}{81820}Evo ga. Na vreme. Daj poljubac.
{81845}{81890}Uzmi torbe, duöo.
{81921}{81984}- Dobar dan.|- Sjajno izgledaö.
{81990}{82031}- Kako si?|- Sjajno.
{82037}{82096}Ja Êu to uzeti.
{82101}{82172}- Mogu ti pomoÊi s time?|- Ne.
{82209}{82263}Mali voli pomagati.
{82285}{82320}Da, dobar je deËak.
{82325}{82349}Siguran sam.
{82354}{82429}Kakav divan dan.
{82543}{82588}- G. Kuömen, g. Din.|- ∆ao, Liz.
{82704}{82735}éene.
{82799}{82856}Uvek nose previöe prtljage.
{82866}{82932}Znaö öta kaûu.
{82951}{83051}Ne moûeö s njima, ne moûeö bez njih.|Ne smeö ih ubiti...
{83067}{83114}...izvan Montane.
{83436}{83488}Ne Ëini niöta öto ja ne bih.
{83492}{83559}Ako ipak uËiniö,|nazovi to po meni.
{83886}{83975}Nimalo mu ne verujem.
{83998}{84063}Da, zabrinut sam za mamu.
{84148}{84198}Ja sam za sve nas.
{84270}{84317}SELO PROKLETIH
{84373}{84420}- äta Êemo sad?|- Dovoljno si jeo?
{84425}{84504}äaliö se, posle tolikih viröli?
{84509}{84581}Kako zovu ovaj deo grada?
{84586}{84665}»uo sam da govore "tamo dole".
{84703}{84766}Svaki grad ima mesto...
{84772}{84837}...gde prezime nije bitno.
{84865}{84963}Vino je u papirnatoj kesi,|a moûeö kupiti gotovo sve...
{84983}{85046}...imaö li novca u dûepu.
{85076}{85113}Doi.
{85146}{85238}- Ostani blizu.|- Ne brini se zbog toga.
{85242}{85362}Ne bih te smeo voditi ovamo,|ali ne moûeö ostati vani.
{85367}{85405}Doi.
{85423}{85526}Hejvud protiv Albinija,|sutra u Njujorku.
{85531}{85574}Imam viöak novca.
{85579}{85613}äta kaûeö?
{85677}{85719}Ni korak dalje.
{86322}{86359}Hej, mali!
{86374}{86407}Kako se zoveö?
{86427}{86480}Bobi Garfild.
{86485}{86528}Bio si veÊ ovde?
{86533}{86556}Nisam, gospoo.
{86585}{86622}Izgledaö mi poznato.
{86702}{86746}Poznavala sam ti oca?
{86774}{86848}Mrtav je. Davno je umro.
{86871}{86898}I on je bio Bobi?
{86905}{86972}Bobi Garfild, da, gospoo.
{86989}{87036}Baö kao ja.
{87041}{87088}Bio je dobra muöterija.
{87092}{87135}Da, volela sam ga.
{87147}{87182}SvraÊao je...
{87186}{87262}...ponekad na pivo.
{87301}{87392}Recimo ponedeljkom, kad je ovde mrtvo.
{87398}{87474}Ubrzo bismo se svi smejali.
{87505}{87572}Nije bio nimalo zloËest.
{87598}{87641}Bio je i dareûljiv.
{87652}{87707}Ovde nema mnogo takvih.
{87736}{87821}Nikad nije Ëastio pijance.|Divila sam se tome.
{87826}{87910}I uvek je vukao za fleö.
{87925}{87967}Ko ti je to rekao?
{87980}{88028}SeÊam se velikih gubitnika.
{88033}{88090}Uglavnom bi odlazio...
{88096}{88163}...s viöe nego öto je doneo.
{88204}{88295}Bobi je bio sjajan kartaroö.
{88450}{88497}Zadrûi to ako ûeliö.
{88540}{88590}Zgodan je, ne misliö?
{88630}{88689}Tome se moûeö radovati.
{88747}{88792}Imaö li curu?
{88804}{88838}Da, gospoo.
{88850}{88880}Lepa je?
{88892}{88952}Da. Ime joj je Kerol.
{88957}{89009}Zaista je seksi maËka.
{89075}{89131}äta?
{89135}{89174}Idemo, partneru, taksi Ëeka.
{89179}{89254}Tede, moj je tata zalazio ovamo!|Nije izgubio naö novac.
{89258}{89338}Bio je dareûljiv, zabavan|i voleli su ga!
{89343}{89390}- Dobro.|- Nije li to divno?
{89396}{89465}SreÊa za nas öto smo doöli ovamo.
{89471}{89518}Da, to je divno.
{89555}{89652}- Za koliko ste se kladili?|- Za sve öto imam. 200 $ na Albinija.
{89656}{89761}- Mislite da moûe dobiti Hejvuda?|- Da, mislim da moûe.
{89783}{89817}Kladio sam se 10:1.
{89823}{89900}- Znate li öta o boksu?|- Ne, niöta.
{89905}{89943}Ulica Brod 149, molim.
{89950}{89983}BiÊe na radiju.
{89988}{90035}SluöaÊemo sutra uveËe.
{90040}{90073}Nadam se da znaö öta radiö.
{90077}{90163}Dolaze! Brzo, u zaklon!
{90168}{90267}Zakloni um! Ne boj se!|Misli na neöto drugo.
{90273}{90300}Kako?
{90305}{90403}Misli na Kerol. Ne puötaj je.|Misli na sretne stvari. Na Kerol!
{90408}{90442}Zakloni um!
{90446}{90518}Misli na neöto sretno.|Ne puötaj je.
{91601}{91660}Laku noÊ. Ponosim se tobom.
{91666}{91747}éao mi je öto vam nisam verovao.
{91751}{91783}Znam.
{91830}{91929}Moj otac nikad nije Ëastio pijanca piÊem.
{91958}{92009}äta to taËno znaËi?
{92071}{92153}Da je bio dobar Ëovek. Poöten.
{92173}{92248}Nije stvarao nevolje svetu.
{92327}{92386}Laku noÊ.
{92629}{92687}Hejvud kreÊe udarajuÊi.
{92692}{92749}Gotovo je jurnuo.
{92754}{92807}Udara Albinija kako ûeli.
{92813}{92926}Albiniju ruke vise.|Povremeno slabo udara.
{92931}{92988}Udarci lete!
{92992}{93026}Zaboga!
{93031}{93143}Udarac Albinija niotkuda|pogaa Hejvuda...
{93149}{93174}...i baca ga na pod!
{93179}{93250}Broje mu! 8, 9, 10!
{93255}{93284}Zaboga!
{93290}{93377}Nisam video neverovatniji kraj!
{93382}{93437}Albini je porazio Hejvuda!
{93442}{93510}Ovo moram ponovno videti!
{93556}{93578}Opa!
{93597}{93692}Dobili ste 2000 $.
{93810}{93845}Go Garfild.
{93850}{93892}PozvaÊu ga.
{93897}{93940}Bobi, tvoja majka.
{93946}{93978}Dobro.
{94051}{94090}- Mama.|- Duöo.
{94102}{94166}- Nedostajem li ti?|- Svakako!
{94179}{94242}Ali trudim se da ne budem pretuûan.
{94253}{94294}Dobro.
{94298}{94355}- Ne zaboravi oprati zube.|- VeÊ jesam.
{94360}{94393}Dobar deËko.
{94399}{94506}Ne mogu Ëavrljati celu noÊ.|Za delegate je prireen koktel.
{94599}{94630}Joö si tamo?
{94635}{94704}Ispala mi je sluöalica.|Volim te.
{94917}{94955}To je Ëudno.
{95022}{95064}Veza se prekinula.
{95327}{95379}Tih 2000 $...
{95406}{95498}- To je za putovanje, zar ne?|- Tako je.
{95608}{95714}Lagao sam vam. Nisam vam rekao|za plakat o izgubljenom psu.
{95719}{95743}Znam.
{95793}{95841}Kad odlazite?
{95847}{95906}Sutra, kad ti se mama vrati.
{95911}{96009}PokupiÊu dobitak od Lena Fajlsa...
{96015}{96039}...i otiÊi.
{96094}{96147}HoÊu li vas opet videti?
{96184}{96214}NeÊeö.
{96251}{96309}A od ûelja neÊe tako biti.
{96514}{96571}Ne ûelim da odete.
{96684}{96747}Tako je najbolje, maleni.
{96752}{96799}Tako je najbolje.
{97404}{97503}"U joö jednom Ëudnom|preokretu u Vaöingtonu...
{97508}{97625}...Dû. Edgar Huver, direktor FBI-a...
{97630}{97731}...u danaönjoj je izjavi porekao|da je FBI umeöan...
{97736}{97847}...u regrutovanje vidovnjaka|za borbu protiv komunizma."
{98017}{98105}O tome je reË, zar ne?
{98280}{98322}HoÊeö bezalkoholno pivo?
{98345}{98462}Jedino je zato dobro öto odlazite.|Ne podnosim to.
{98482}{98517}Znam.
{98550}{98620}- Znate li sve?|- Ne.
{98669}{98734}äta se dogaa kad dodirnete ljude?
{98748}{98851}Otvaram prozor koji gleda u tue misli.
{98890}{98965}Zbog toga vas ûele?|Zbog tog prozora?
{98971}{99074}Da. Znam neke stvari, vidim ih.
{99079}{99166}Neki to smatraju darom,|za mene je teret.
{99171}{99230}Nekima vredi ono öto vidim.
{99248}{99305}Moûda sam ovaj put pobegao.
{99310}{99340}Hvala.
{99372}{99406}éiveli.
{99414}{99451}U zdravlje.
{99566}{99630}Svi smo samo u prolazu.
{99658}{99714}Samo u prolazu, to je sve.
{99780}{99849}Reci Kerol da bih se i od nje|ûeleo oprostiti.
{99855}{99880}U redu.
{100022}{100072}Bobi!
{100110}{100172}Otii je odmah pronaÊi.
{100212}{100243}U redu.
{100563}{100619}VIDELI STE BRAUTIGANA?
{100625}{100703}MEäANAC JE, ALI VOLIMO GA|VELlKA NAGRADA
{101064}{101122}Je li Kerol kuÊi?
{101127}{101183}Ne, otiöla je Ëitati knjigu...
{101187}{101226}...kod onoga drveta.
{101882}{101954}Ne plaöi me, Bobi Garfild.
{101959}{102015}Pa to je mala Gerberica.
{102132}{102167}Ne!
{102222}{102246}Heri?
{102643}{102690}Kerol! Kerol!
{103128}{103185}Sve je u redu?
{103212}{103288}Udario me! Jako!
{103293}{103324}U redu je.
{103338}{103386}- Idem po pomoÊ.|- Ne!
{103399}{103461}Ne ostavljaj me!|Mogao bi se vratiti.
{103466}{103493}BiÊe u redu.
{103498}{103533}Moûeö li hodati?
{103538}{103561}Ne znam.
{103566}{103636}Samo pokuöaj. PokuöaÊemo.
{103726}{103753}BiÊe u redu.
{103759}{103831}Pokuöaj stati na noge.
{104087}{104165}Evo öta moraö.|Popni mi se na lea.
{104171}{104271}- Ne mogu!|- Moûeö! Moûeö!
{104300}{104325}Moûeö.
{104330}{104415}Misli na neöto drugo.
{104456}{104503}Penji mi se na lea.
{104511}{104592}SeÊaö se kako smo se|to igrali tokom odmora?
{104598}{104661}- Da.|- Ovo je isto.
{105229}{105305}- Bronko Nagurski!|- Nagurski.
{105487}{105529}10 metara.
{105534}{105593}7 metara.
{105709}{105769}Niöta me neÊe zaustaviti.
{106528}{106553}Tede!
{106624}{106654}Pomozi!
{106662}{106703}Mislim da je desna ruka slomljena.
{106709}{106760}Sve Êe biti u redu.
{107169}{107207}Moja ruka!
{107212}{107266}Bobi, uhvati ruku.
{107325}{107357}O, da.
{107386}{107458}Veliki deËko protiv male curice.
{107466}{107578}Tako te se boji.|Misli da imaö lavlje srce.
{107587}{107635}Ozledio me, Tede.
{107640}{107699}Veruj mi, znam.
{107710}{107818}Moram ti pogledati rame.|ShvaÊaö?
{107823}{107866}NeÊu te povrediti, biÊe ti bolje.
{107898}{107942}Ajme.
{107951}{107997}Slomio mi je ruku.
{108001}{108062}Ne bih rekao.|Mislim da je iöËaöena.
{108079}{108122}I mogu to srediti.
{108184}{108252}Doktor si, Tede?
{108257}{108295}Ne, nisam.
{108309}{108372}Ali Ëudan sam, kako si primetila.
{108377}{108430}Ko zna öta sve mogu?
{108437}{108494}Imaö li lavlje srce?
{108582}{108644}Zaûmuri i pokuöaj se opustiti.
{108649}{108709}Bobi, daj mi svoj kaiö.
{108746}{108824}Znaö li öta bol Ëini?
{108829}{108888}Diûe se. Penje s telom.
{108908}{108953}Hvala.
{108958}{108998}Sluöaj me.
{109004}{109051}I opusti se.
{109056}{109123}Jako zagrizi Bobijev kaiö.
{109128}{109236}ZagriöÊeö ga i uhvatiti bol.
{109258}{109299}Opusti se.
{109304}{109345}Zaûmuri.
{109350}{109387}Ne otvaraj ih.
{109392}{109451}Sigurna si, samo udahni.
{109467}{109546}Izdahni, tako. Nema boli.
{109554}{109614}Samo sluöaj moj glas.
{109657}{109729}OseÊam da mi se pribliûavaju, Bobi.
{109747}{109825}Znam. Znakovi su posvuda.
{109831}{109865}Evo.
{109871}{109937}Zagrizi jako i uhvati... Idemo.
{110102}{110137}Tede?
{110151}{110204}Viöe ne boli.
{110225}{110278}Imala si lavlje srce.
{110297}{110339}Bio si dobar, mali.
{110345}{110401}Koji se avo tu dogaa?
{110423}{110469}Mama, gle öta ti se dogodilo.
{110474}{110588}- MiËi ruke s male, gade!|- Nije joj naudio!
{110596}{110654}Kako se usuujeö dirati je!|Pasji sine!
{110658}{110699}Nije joj naudio!
{110704}{110767}Naöao sam je i doneo da joj Ted pomogne.
{110773}{110865}Idi u svoju sobu! A ti Êeö,|prljavi starkeljo, u zatvor!
{110871}{110941}To öto vam se dogodilo je grozno.|Nije se dogodilo njoj.
{110961}{111031}- Zaöto je raskopËana?|- Da joj sredi rame!
{111036}{111079}Rekoh da ideö u sobu!
{111084}{111134}Bobi je rekao istinu!
{111193}{111257}Idemo u kupatilo da se opereö.
{111264}{111322}Doneo me uzbrdo.
{111327}{111381}Ted je uklonio moju bol.
{111386}{111428}Ne diraj je!
{111465}{111497}Idi u kupatilo.
{111501}{111577}Zovem policiju i reÊi Êu|öta sam sve videla.
{111586}{111641}Zaöto im ne kaûete öta se dogodilo vama?
{111674}{111737}Niste bili tamo,|ne moûete znati.
{111741}{111778}Znam.
{111782}{111870}Niste znali da seminar|ukljuËuje piÊe i seks.
{111875}{111974}Znam da vam sin odrasta|dok vi mislite na druge stvari.
{112071}{112189}OdveöÊu malu kuÊi,|bolje da vas nema kad se vratim.
{112377}{112449}- »uvajte se.|- BiÊu dobro, bez brige.
{112454}{112508}Gde Êete do mraka?
{112513}{112627}U restoran, verovatno.|Dobitak Êu uzeti posle.
{112645}{112693}éelim s vama.
{112712}{112758}Bobi, molim te, ui.
{112775}{112816}Posluöaj je, mali.
{113938}{113988}Je li to...
{113993}{114051}...Hausatonik 5837?
{114085}{114156}Imam podatke za vas.
{114161}{114221}O Brotiganu.
{114234}{114317}VeËeras Êe biti u "Korner Poketu"...
{114324}{114358}...u Bridûportu.
{114381}{114448}Spominje se nagrada...
{114454}{114478}Halo?
{114623}{114665}Gadovi!
{115461}{115513}Kad tvoja majka za nekoga...
{115517}{115607}...mentalno napiöe da je loö...|To je neizbrisivo.
{115673}{115761}Znao sam to, ali nisam mislio|da Êe izdati mene.
{115891}{115955}Treba mi novac da preûivim.
{115981}{116049}A ne mogu u "Korner Poket".
{116075}{116139}Treba mi vremena da razmislim.
{116162}{116205}A nemam ga.
{116400}{116439}Evo öta Êete.
{116467}{116505}Napiöite poruku.
{116510}{116537}Poruku?
{116556}{116608}Da, za "Korner Poket".
{116621}{116667}Ja Êu doneti novac.
{116713}{116783}Ne znam je li to pametno.
{116798}{116837}Uzmite moje ruke.
{116875}{116982}Bez brige, neÊu dopustiti|zlikovcima da vas uhvate.
{117814}{117849}Halo?
{117925}{117968}Mogu li pomoÊi?
{117979}{118074}U vezi Brotigana. Otiöao je.|Vozom. Video sam ga.
{118079}{118137}Ne meöaj se, mali.
{118142}{118200}Brotigan je naö problem.
{118270}{118314}Nemojte mu nauditi.
{118363}{118438}Molim vas, nemojte mu nauditi.
{118448}{118496}Idi kuÊi, Bobi.
{120998}{121065}DAJTE MOJ DOBITAK|BOBIJU GARFILDU
{121223}{121270}Tede, imam novac!
{121574}{121612}Tede!
{122092}{122149}Ne ûalim ni za jednom minutom, Bobi!
{122156}{122189}Ni za jednom!
{122230}{122287}Ne bih je dao za ceo svet!
{122932}{122996}Gde si bio?|Razbolela sam se od brige.
{123001}{123054}Potpuno sam siguran.
{123059}{123150}Znaö li kako mi je bilo?|Nisam znala gde si!
{123155}{123241}Misliö samo na sebe!
{123269}{123307}Ted je otiöao!
{123312}{123365}Viöe ga nikad neÊu videti!
{123386}{123457}Dobila si sve öto si htela.|Sretna si?
{123462}{123523}Nema novca! Nemam posao!
{123528}{123585}Sad ima mnogo novca!
{123614}{123691}Vidiö kako je dobro ispalo|öto si ga prijavila?
{123697}{123752}UËinila sam to radi tebe!|Za tvoje dobro!
{123760}{123843}Laûeö! Uvek laûeö!
{123883}{123979}Moj je otac bio dobar Ëovek|i ljudi su ga voleli!
{124018}{124078}Svi osim tebe.
{124091}{124151}Nikad nisi volela ni mene.
{124159}{124267}Tad sam naöao odraslog|prijatelja, i znaö öta?
{124287}{124319}Voleo sam ga.
{124360}{124461}Nisi izdala samo njega,|izdala si obojicu.
{124720}{124744}Bobi?
{125011}{125057}Ted je imao pravo.
{125062}{125124}Nije sve Atlantida.
{125162}{125237}Majka je dobila posao izvan Bostona.
{125243}{125327}A ja sam, svakako,|bio uzrujan, ali...
{125332}{125376}...nisam se bojao.
{125386}{125448}Za to sam mogao zahvaliti Tedu.
{125476}{125552}Gubi se odavde, ovo je sad moje mesto.
{125557}{125616}Ne moûeö to Ëiniti.|Ovo je javni park.
{125620}{125660}Mogu.
{125739}{125780}Mali Bobi Garfild.
{125798}{125873}Gde ti je kum sad kad ti treba?
{126425}{126486}Ovo je za malu Gerbericu!
{127772}{127817}Treba li ti pomoÊ?
{127823}{127858}U redu je.
{128356}{128452}Misliö da Êeö mi moÊi oprostiti?
{128561}{128619}Radim na tome.
{129339}{129410}Kerol, odlazimo.
{129428}{129463}O, ne.
{129503}{129568}BiÊu ovde u MasaËusetsu.
{129574}{129647}- HoÊeö li mi pisati?|- Svakako.
{129652}{129688}Ja Êu pisati tebi.
{129717}{129775}Verovatno ûudeti za domom.
{129796}{129849}Nikad te neÊu zaboraviti.
{130004}{130067}Ti si prebio Herija Dulina?
{130118}{130147}Dobro.
{130173}{130199}Dobro.
{130461}{130515}- »ekaj.|- Ne mogu. Ne sad.
{130572}{130638}- Ali ja...|- I ja tebe volim, Bobi Garfilde.
{130685}{130739}Ali moram spremiti salatu.
{131343}{131382}I öta Êemo uËiniti?
{131388}{131483}Najbolje öto moûemo, mama.|Najbolje öto moûemo.
{131548}{131608}Vreme nikoga ne Ëeka.
{131613}{131686}Ben Dûonson zvao je vreme|"starim Êelavim prevarantom".
{131692}{131762}- Ko je Ben Dûonson?|- Engleski pisac.
{131768}{131850}Blesav s novcem.|I sklon vetrovima.
{131856}{131897}Vetrovi?
{131935}{131993}Bobi Garfilde!
{132720}{132804}Ne biste smeli biti unutra.
{132811}{132863}Nije sigurno.
{132868}{132936}éiveo sam ovde kao mali.
{133038}{133128}- Dugo ûiviö ovde?|- Samo celi ûivot.
{133161}{133232}»ekaj malo! »ekaj!
{133319}{133354}Je li tvoja majka...
{133401}{133451}Je li...?
{133475}{133551}Je li bila Kerol Gerber?
{133574}{133682}- Moja je mama mrtva. Godinama.|- éao mi je öto to Ëujem.
{133758}{133834}Nismo ostali u vezi|kao öto smo rekli.
{133941}{133998}Moj Boûe!
{134002}{134064}Vi ste deËko s ringiöpila?
{134094}{134227}- Mama mi je priËala o tome.|- ObeÊala je da neÊe nikome reÊi.
{134259}{134329}Rekla je da ste bili divni.
{134414}{134455}Jedno od nas je bilo.
{135300}{135372}Moûeö zadrûati to ako ûeliö.
{135450}{135481}Ja sam Bobi.
{135527}{135604}- Moli.|- Moli.
{135743}{135808}Imala je lavlje srce.
{136804}{136890}Nisam viöe video Teda Brotigana.
{136894}{136996}Nije da nisam mislio na njega.|Mislio sam...
{137001}{137040}...i misliÊu.
{137086}{137213}Jer to mi je leto bilo|poslednje u detinjstvu.
{137235}{137341}I iako viöe nikad nisam video|öta ljudi misle...
{137346}{137446}...on mi je ostavio trajan dar.
{137470}{137581}Ted je...|Otvorio mi je oËi...
{137595}{137651}...i pustio buduÊnost unutra.
{137709}{137774}Ne bih ûeleo da sam to propustio.
{137807}{137856}Ni za celi svet.
{138307}{138382}Film je posveÊen|Piotru Sobocinskom
{138384}{138482}U zahvalnost velikom filmskom|snimatelju, saradniku...
{138483}{138541}...umetniku i prijatelju.
{138566}{140066}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/5mcq2|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
