{25}{175}-== [ www.OpenSubtitles.org ] ==-
{5794}{5859}Mr. Lombardo, öta ima?
{6232}{6311}Jesi li videla te oËi?
{6801}{6863}Odjebi!
{6867}{6950}Molim vas da se smirite.
{6954}{7011}NedostajaÊe mi samo...
{7054}{7146}Sedite i smirite se.
{7150}{7314}Stigli smo do polovine|ovog semestra.
{7409}{7496}- Blaûenstvo amfiteatra, zar ne?|- Ne!
{7500}{7615}- To si ti, Jimmy?|- U uËionici mogu da meditiram.
{7619}{7773}- HoÊe da kaûe masturbira.|- Siguran sam da svi znate sve o tome.
{8399}{8480}Nisam ja, ËoveËe!
{8516}{8634}Svi smo Ëuli za izraze|"silovanje", "seksualno uznemiravanje".
{8652}{8747}Diskutovali smo na te|teme ovde.
{8751}{8857}Naöi danaönji gosti dolaze|iz policijske stanice Blue Bay-a.
{8861}{9063}Detektivi Duquette i Perez|Êe nas bolje uputiti...
{9067}{9237}i odgovaraÊe na vaöa pitanja.|Poûelimo im toplu dobrodoölicu.
{9326}{9431}Odlazim odavde.|Ovaj kreten me moûe poljubiti u dupe.
{9651}{9808}Kao öto rekoh... poËeÊemo sa pitanjem.|äta je sex zloËin?
{9812}{9894}Zar to postoji?.
{9971}{10143}Blue Bay, borite se, borite!|BuËaneers (gusari), pobedite veËeras!
{10498}{10556}Ispravi.
{10651}{10755}Ispravi krmu, Jimmy.
{10759}{10831}Dobro je.
{10968}{11115}Spusti glavno. Dobro je, usidri,|i videÊemo se u ponedeljak.
{11189}{11297}BuËaneers su broj jedan,|i ne zaboravite to.
{11413}{11531}- Dobar posao, momci. Vidimo se u ponedeljak.|- Vidimo se, Mr. Lombardo.
{11808}{11891}Super!|Mogao bi da se provodim na onome.
{11968}{12110}To je öerpa, Jimmy.|Pravi mornar bi uzeo neöto poput onoga.
{12164}{12247}To je to... to je pravi brod.
{12295}{12419}Hvala Vam öt o ste me ubacili na ovaj Ëas.|Nije bilo öanse da moj otac plati za ovo.
{12423}{12522}To sada odraujeö.|I uËiö o brodovima.
{12526}{12626}Ja sam iöao na koledû samo|da bi radio oko brodova.
{12655}{12762}Mogu li i ja da se igram sa vama?|ili je to samo za deËake?
{12819}{12989}I, ko Vam pere dûip ovog vikenda?|Stariji peraË automobila!
{12993}{13083}- To je gubljenje vremena.|- Ne, baö nije.
{13087}{13198}- äta mislite da to uradmo Nicole i ja?|- Evo ovako...
{13202}{13336}Idem na Glades (brda), u subotu.|U nedelju, vas dve ga moûete oprati od blata.
{13340}{13392}Dogovoreno.
{13396}{13509}Moja majka je trebala da me vozi danas,|ali nije stigla.
{13513}{13610}Pa sam se pitala moûete|li vi da me odvezete?
{13614}{13756}Ne bi ûeleli da peöaËim?|Moûe se desiti neöto loöe.
{13827}{13916}- Treba li i tebi prevoz, Jimbo?|- Da, ali imam biciklu.
{13920}{13990}Hej, nije problem.
{14239}{14328}Pokuöaj.
{14399}{14487}Suzie, treba li ti prevoz?|Imamo mesta.
{14491}{14619}Isuse! Gde je kupila cipele?|U radnji za bludnice?
{14646}{14734}Pokuöaj ponovo.
{14831}{14901}Lepo je videti da se|vi deca dobro slaûete.
{15905}{15985}- Ne zaboravi u nedelju.|- NeÊu.
{16052}{16125}- Jel to Sam Lombardo?|- ∆ao, Mama!
{16129}{16237}- Sam! ∆ao.|- ∆ao, Sandra.
{16281}{16410}- Zaöto ne ueö na piÊe?|- éao mi je, Moram da idem.
{18230}{18289}- ∆ao, Mr. Lombardo.|- ∆ao, devojke.
{18289}{18379}- ∆ao, Mr. Lombardo.|- ∆ao, devojke.
{18383}{18500}- Vidi, zaboravio je. Znala sam.|- Ne, nisam. Vidite moj dûip.
{18504}{18631}Lep i prljav.|Ali saËekajte dok druga kola odvezemo.
{18635}{18734}Mislite Mercedes nije isto vaö?
{18738}{18819}Moj Benz je plav.|Znaö to, Nicole.
{18823}{18958}- Sam, Ja odlazim.|- Gde su vam krpe, Mr. Lombardo?
{18962}{19066}Krpe su, Kelly,|ispred dûipa.
{19162}{19251}Kelly Van Ryan|Êe ti oprati kola?
{19255}{19343}Ma daj, Barbara.|To je ima dobar cilj.
{19372}{19519}- »ovekoljubivi Sam!|- Teûak posao nikada nikome nije ötetio.
{19607}{19687}Zabavi se u klubu.
{21183}{21263}Izgleda kao nov.
{21299}{21370}Zar niste zaboravili neöto?
{21374}{21483}- Vaö kupon. Moramo ga dobiti.|- Da, u pravu ste.
{21487}{21592}- Zar ne moûemo samo da...|- Pravila su pravila, Mr. Lombardo.
{21596}{21719}- OK, Ëekajte da ga potraûim...|- Mr. Lombardo? Pomalo kasnimo.
{21723}{21826}Nicole mora da ide. Vi me moûete|odbaciti do kuÊe kad ga pronaete.
{21830}{21934}Dajte mi samo minut.
{22075}{22182}- Idi!|- Jesi li sigurna?
{23913}{24007}Frankie! Oh Goûe!
{24093}{24176}Doavola!
{24188}{24334}Zovem iz Blue Bay ökole.|Vaöa Ëerka danas nije bila u ökoli.
{24387}{24477}äta?|Ajde...
{24543}{24627}- To je baö velika riba, Art.|- To je  barakuda.
{24631}{24777}Da nisi jurio bogataöice u|klubu i ti bi uhvatio takvu neku.
{24781}{24875}- NeÊeö je pojesti?|- Zaöto ne?
{24879}{25023}- To je barakuda, znaö, one su otrovne. Ubilo bi te.|- Kao i veËina devojaka sa kojima izlaziö.
{25027}{25078}Sandra Van Ryan, za Sam-a.
{25272}{25334}- äta ima?|- Kelly je pobegla iz ökole danas.
{25338}{25439}- Jesi li Ëuo neöto?|- Ni reË.
{25464}{25576}Nema veze, naöla sam je.
{25651}{25703}Vuci!
{25707}{25791}»uj, Sam...|Stvarno je bilo lepo videti te.
{25795}{25884}Vidi Sandra,|Pomalo sam zauzet sada, tako da...
{25888}{26014}Joö nisam naöla nekoga ko bi mogao|da odrûava moj brod kao öto ti umeö.
{26055}{26187}- Jebeö se sa Barbar-om. Pa öta?|- Moûda sam sada Ëovek za jednu ûenu.
{26191}{26299}Jadni Sam.
{26303}{26383}Stvarno misliö da Êe ûena iz Blue Bay-a|pristati da se uda za tebe?
{26387}{26467}- Jesi li zavröila?|- Shvati, duöo...
{26471}{26604}ti si za iznajmljivanje, dobro jebeö,|to je sve. Uûivaj dok traje.
{26608}{26656}∆ao, Sandra.
{26696}{26765}Vuci!
{26799}{26950}Izgleda da si naöla utehu u pucanju.|Moûda i ja to probam nekad.
{27003}{27115}Da pogaam. Neki momak te nije zvao,|tako da ti je upropastio vikend?
{27119}{27190}I onda si uzela slobodan dan.
{27277}{27419}- Ko je od tvojih mornara ovaj?|- Koji god poûelim.
{27458}{27550}Pa dobro, Kelly.|O Ëemu se radi?
{27619}{27694}äta je bilo?
{27698}{27809}- Nedostaje mi tata.|- Isuse.
{27846}{27959}- I meni nedostaje. Ponekad.|- Ne, nije istina.
{27963}{28069}Nije morao da se ubije,|Kelly.
{28088}{28169}Kelly...
{28243}{28319}Ja...
{28323}{28423}Neznam zaöto je to uradio.
{28447}{28531}Stvarno ne znam.
{28621}{28699}Mogu li...
{28733}{28843}Mogu li da ti donesem neöto?|HoÊeö li jedan valium?
{28946}{29082}- Silovana sam.|- äta, duöo? Nisam te Ëula.
{29086}{29210}- Rekoh silovana sam.|- äta?
{29257}{29336}Silovao me je...
{29340}{29432}Sam Lombardo.
{29443}{29491}Sam Lombardo?
{29535}{29679}- Moja Êerka ne moûe biti silovana!|I kaûete da je to Sam Lombardo uradio?
{29683}{29803}Taj kuËkin sin mora da je lud|ako misli da to moûe meni uraditi.
{29807}{29938}Razumemo kako se oseÊate ali|nam je sada potrebno malo vremena sa Kelly,
{29942}{30031}da uzmemo njenu izjavu, nasamo.
{30095}{30191}- Jel to uredu sa tobom, duöo?|- Da.
{30443}{30533}HoÊeö da napravimo pauzu?
{30537}{30615}HoÊu da se ovo öto pre zavröi.
{30619}{30748}éelela bih da snimim tvoju izjavu.|Ovo su ozbiljne optuûbe.
{30752}{30884}Moramo da znamo sve öto se desilo.|Jesi li spremna?
{31140}{31215}PoËeo je da mi trlja ramena.
{31279}{31411}Pustila sam ga.|Mislim, on je dobar Ëovek.
{31415}{31475}SledeÊeg momenta...
{31479}{31587}ruka mu je bila u mojim pantalonicama.
{31591}{31685}Znate, otpozadi.
{31689}{31763}Njegovi prsti...
{31805}{31931}- Njegovi prsti...|- Samo polako.
{31967}{32070}Bili su u meni.|Na oba mesta, znate?
{32119}{32260}- Da li je uöao u tebe?|- Da.
{32264}{32403}Rekla sam "stani", Vriötala sam. Mislim,|tako je zvuËalo u mojoj glavi.
{32431}{32537}- Povredio me je.|- Da li si probala da se boriö sa njim?
{32541}{32707}- Drûao mi je ruke iza lea.|- äta onda?
{32711}{32841}Stalno je ponavljao,|"Pusti da se to desi, neka se desi".
{32882}{32999}- A onda je samo stao.|- Misliö, povukao se?
{33003}{33137}- Teöko mi je da se setim.|- Pokuöaj, Kelly.
{33263}{33341}Znam da je rekao jednu stvar.|Rekao je:
{33345}{33437}"Ne brini se, nisam svröio".
{33441}{33528}Ne mogu to da zaboravim.
{33532}{33647}Rekao je, "Nijedna devojËica|me ne moûe naterati da svröim".
{33720}{33811}"Nijedna devojËica me ne|moûe naterati da svöim". Isuse!
{33815}{33935}äteta, moûda kad bi imali neki fiziËki dokaz.
{33971}{34102}Moûda nema fiziËkog dokaza|zato öto se niöta nije desilo.
{34106}{34185}Mislim da izMisslja.
{34189}{34320}Sredila je da ostane nasamo sa njim,|da bi bila sa njim ali on nije hteo.
{34324}{34447}Moûda, a moûda i ne. Nikako|nije smeo da dozvoli da ona doe kod njega.
{34451}{34527}Gloria, on je opalio|pola ûena u Blue Bay-u.
{34531}{34646}To ne znaËi da je silovao.|Mogla bi da ode na test istine.
{34650}{34737}A Papa bi mogao da da test mokraÊe.|Ovo je Blue Bay.
{34741}{34857}Pitaj to Van Ryan-ove i|Tom Baxter Êe te skloniti sa sluËaja.
{34861}{34968}Sada se plaöiö Tom Baxter-a?|Ili Sandre Van Ryan?
{34972}{35095}Razgovaraj sa njegovim komöijama,|njegovim kolegama sa posla i Kelly-nim drugaricama.
{35099}{35248}- To Êe uniötiti Lombarda.|- »uo si je. Momak nije Ëist.
{35252}{35327}Naite dokaze.
{36558}{36670}Dobar posao, Jimbo.|Vidimo se u ponedeljak.
{36839}{36935}To je sve öto je ostalo od mog odeljenja jedrenja.
{36985}{37146}- PriËaj sa mnom, Artie.|- Kelly te optuûuje za silovanje.
{37150}{37271}Jimmy mi je rekao.|Izgleda da sam ja zadnji saznao.
{37275}{37456}Sandra Van Ryan je zvala|sve Ëlanove ökolskog odbora.
{37460}{37593}- Tera ih da te suspenduju.|- I oni ne ûele da Ëuju moju verziju?
{37597}{37684}Ovo je ludilo.|Ja sam nevin, doavola!
{37688}{37779}- Moraö mi verovati.|- Samo se ti drûi.
{37783}{37898}- Kada te oslobode optuûbi...|- Nikada se ne moûeö otkaËiti od toga.
{37936}{38060}To ostaje sa tobom.|Prati te svuda, zauvek.
{38089}{38208}TrebaÊe ti pomoÊ, Sam.|Advokat.
{38212}{38364}A koji Êe to advokat u Juûnoj Floridi|da krene protiv Van Ryan-ovih?
{38773}{38863}Zdravo. Doöao sam kod Ken Bowden-a.
{38867}{39019}- Imate li zakazano?|- Da, Sam Lombardo.
{39023}{39129}- Mr. Bowden, vaö klijent od 10:30 je ovde.|- Uvedite ga, molim vas.
{39199}{39250}äta vas dovodi ovde?
{39254}{39423}Do juËe, sam bio savetnik rukovodstva|u Blue Bay srednjoj ökoli.
{39443}{39565}- Jedan uËenik me optuûuje za silovanje.|- Muöko ili ûensko?
{39601}{39730}UËenik se zove Kelly Van Ryan.|äto znaËi, sjeban sam.
{39792}{39915}- Zaöto mi ne ispriËate sve o tome?|- Sranje, odakle da poËnem?
{39919}{40032}Od vaöeg odnosa sa tom devojkom.
{40059}{40164}Ona je uËenik, ja sam bio njen savetnik, niöta viöe.
{40191}{40284}Onda nemate razloga da se brinete.
{40319}{40469}- äta se desilo sa vaöim vratom?|- Ovo? Ne moram to da nosim.
{40539}{40655}Motao se ovde Ëovek iz osiguranja danas.
{40659}{40728}Da vam kaûem kako naplaÊujem.
{40915}{40975}Georgie!|Kakav je vetar danas?
{40979}{41070}Mr. Lombardo, bojim se da vam|danas ne mogu parkirati auto.
{41074}{41130}Ali sastajem se sa Barbar-om zbog ruËka.
{41261}{41394}- PArkiraj mi auto, Georgie?|- Odmah, Mr. Baxter.
{41413}{41523}Zavröio si ovde, Lombardo.|Odlazi odavde.
{41629}{41725}Barbara, öta se dogaa?
{41796}{41947}Moûda me nisi Ëuo, Lombardo.|Zavröio si u Blue Bay-u.
{41951}{42081}Ako se i dalje budeö viao|sa mojom Êerkom zavröio si i taËka.
{42085}{42203}- Odjebi odavde.|- Mr. Lombardo, molim vas...
{42299}{42379}Sve je u redu, George.
{42900}{42987}Sam, Duöo!|Nisam vas videla neko vreme.
{42991}{43088}- Dobrodoöli nazad.|- Rum i koka kolu.
{45238}{45355}- Jel ste dobro?|- Dobro sam.
{45359}{45427}To je baö loöe, jebivetru.
{45727}{45799}Sam?
{45896}{45969}Lombardo?
{46451}{46539}Ej, ËoveËe!|To sam ja.
{46543}{46633}Izvini, ËoveËe.|Stvari su se pogoröale ovde.
{46637}{46711}Vidim.
{46715}{46778}Ui unutra.
{46832}{46947}Siguran si da je Frankie Condo|taj koji te je prebio?
{46951}{47051}To je bio on. Vozio je Sandrin Range Rover.
{47055}{47138}IspiËaj to pandurima, i onda moûemo tuûiti Sandra-u Van Ryan.
{47142}{47242}- Zaboravi.|- Ona ima duboke dûepove.
{47246}{47410}Znam koliko su joj duboki dûepovi.|Mislim da ovako mogu spasiti ovu kuÊu...
{47414}{47511}Ali pogaaj ko je u glavnom odboru banke?
{47515}{47657}Ne trebaju mi joö nevolja od njer.|Misliö da je mogu zaustaviti?
{47661}{47755}Sa sranjem koje sam iskopao o Kelly?|Da.
{47759}{47929}Pre godinu dana, kada joj se|otac ubio, Kelly je pukla i pobegla.
{47933}{48027}Naöli su je u nekom usranom hotelu.|Uraena od kokaina ko tikva.
{48051}{48210}Za to vreme, ti, Sam, si izabran|za "profesora godine" ili takvo neko sranje.
{48214}{48365}Ako vas dvoje stanete pred|porotu oni Êe izgledati glupo.
{48369}{48495}Nisu uzeli izjavu od tebe zato|öto traûe neöto da te ocrne.
{48499}{48581}A neÊe naÊi niöta.
{48626}{48702}Jel da?
{48706}{48811}Ken, Ja ne tucam svoje uËenice.
{49637}{49726}Samo se pravi vaûan pred vama.
{49750}{49871}Dobro veËe, Ruby.|Vidim da jpö uvek imaö Walter.
{49875}{49982}Nadao sam se da ga je do sada neöto pojelo.
{49986}{50122}- Kako vam mogu pomoÊi?|- Suzie nas je zvala. Gde je ona?
{50126}{50184}Znaö put i sam.
{50339}{50435}NeÊeö je ubiti, jeli?
{50463}{50555}Mislim da je nenaoruûana.
{51543}{51648}Dobro da ste i doöli!|äta da me je neko davio?
{51652}{51735}Ili jebao u dupe, Ëak?
{51754}{51895}- HoÊu reÊi vi radite na sex kriminalu?|- Moj partner, Detective Perez.
{52023}{52146}»itam CÈline. On je znao dobro da piöe koliko su ljudi jeftina ubrad.
{52150}{52235}Suzie, ti si pozvala nas, seÊaö se?
{52387}{52523}- Jesu li uhapsili Mr. Lombardo-a?|- Ne.
{52554}{52637}- HoÊe li?|- Ne znam.
{52641}{52724}To ti smeta?
{52742}{52796}HoÊu da izaem napolje.
{52968}{53101}- Kada te je to povezao?|- Otprilike pre godinu dana.
{53105}{53214}- Jel bio joö neko u tvojoj prikolici?|- Ne.
{53218}{53295}- ZnaËi bila si sama?|- Da.
{53299}{53378}- Jel uöao za tobom unutra?|- Verovatno.
{53382}{53526}- Jeste ili nije?|- OK. Da, jeste.
{53530}{53652}I onda? Da li te je dirao?|Jesi li flertovala sa njim?
{53656}{53762}Suzie, Znam da ti je teöko da kaûeö.|Reci nam istinu.
{53766}{53832}Nisam mu rekla ni reË.
{53859}{53970}Stavio je ruke oko mene|i rekao je da sam lepa.
{53974}{54083}- Umem da budem stvarno lepa, rekao je|- Jesi li mu rekla da stane?
{54087}{54223}Sranje! Kakve to veze ima?|Niko mi ionako ne bi poverovao.
{54227}{54364}- Da li te je Sam Lombardo silovao?|- Jeste. Gurnuo me je na pod.
{54419}{54553}- Sada, jel smo zavröili?|- Skoro, Suzie, joö malo.
{54560}{54620}Jesi li mogla da ga odgurneö?
{54650}{54743}Ne. Sam je stao.
{54747}{54831}Jel sad dosta?|Ostavite me na miru.
{54835}{54925}- Ne diraj me!|- U redu, smiri se.
{54929}{55058}Stao je. I to je bilo to.|Samo je otiöao?
{55062}{55236}- Da. Rekao je prvo neöto.|- äta to?
{55258}{55376}Rekao je, "Ne moûe mala kuËka da me natera da svröim".
{55427}{55504}Otvori vrata.
{55550}{55603}Vidi ovu devojËicu.
{55607}{55713}- SavetniËe, imate li jednu cigaretu?|- Zdravo, Jinxy.
{55762}{55859}Ove je baö ona situacija|"jedna dobra i jedna loöa vest".
{55863}{56015}Nema kaucije, ali Êeö dobiti|pravog advokata umesto javnog branioca.
{56032}{56110}Rekao sam ti, Ken.|Nevin sam.
{56114}{56239}Propovedaö u horu.|Nisi jedini koji tako kaûe.
{56371}{56458}ZnaËi ti si nova plaËi-piËka?
{56652}{56747}- Neki komentar na sluËaj?|- Kako se oseÊate?
{56751}{56839}Mr. Lombardo|Êe dobiti ono öto je zasluûio.
{56872}{56931}- OseÊate se uvereni da Êe ga osuditi?|- Da.
{56935}{57051}Lombardov sluËaj je podigao ovaj grad na noge.
{57055}{57184}Evo Sandre Van Ryan, milionera|iz Blue Bay elite.
{57188}{57259}Tu je i devojka iz|potpuno drugaËije sredine.
{57263}{57399}Porota mora da izabere|izmeu ove dve devojke i Sam Lombarda.
{57403}{57508}Uûivo ispred sudnice,|Nancy Duerr, Vesti oËevidaca.
{58468}{58591}Drûava Florida protiv Sam Lombardo.|Sylvia B. Waxman predseda.
{58595}{58686}Svi ustanite.
{58764}{58845}Molim da sednete.
{59175}{59271}Treba li ti pauza, Kelly?
{59354}{59501}Znam da je ovo teöko, Kelly,|ali imam joö jedno pitanje.
{59505}{59683}Iako smo ovo veÊ preöli hoÊu|da svi budemo sigurni da smo razumeli.
{59687}{59847}Kelly, kada si videla da|Mr. Lombardo ûeli da ima sex sa tobom...
{59851}{59990}koje su bile tvoje reËi?|äta si mu rekla?
{60003}{60088}Rekla sam mu, "Ne".
{60092}{60199}Rekla sam,|"Stanite, Mr. Lombardo, molim vas".
{60203}{60290}Vikala sam da stane.
{60294}{60363}Vikali ste...
{60367}{60459}da stane.|I da li je stao?
{60509}{60575}Ne.
{60579}{60710}Silovao me je na podu njegove usrane kuÊe.
{60848}{60917}Hvala.
{61038}{61195}Drugog dana suenja navodno|druga ûrtva Êe izaÊi da svedoËi.
{61199}{61299}JuËe, Kelly Van Ryan|je svedoËila..
{61303}{61391}i bila je povrgnuta unakrsnom ispitivanju.
{61395}{61475}JaviÊemo se kasnije sa novim vestima.
{62032}{62110}Dobro jutro.
{62114}{62339}Gospoice, kada su vas uhapsili zbog|krae u prodavnici kada ste bili prva godina...
{62343}{62489}bio vam je dozvoljen jedan poziv.|Zvali ste Mr. Lombardo, jel da?
{62525}{62604}Miss Toller?
{62608}{62705}I kada su vas izbacili|iz ökole zbog vandalizma...
{62709}{62808}Slomila sam jebeni prozor.|Nije bila moja greöka.
{62812}{62995}SaËekajte da vas pitaju,|i neÊu dozvoliti proste reËi u mojoj sudnici.
{63073}{63207}- I Mr. Lombardo je iöao|sa vama na sastanak kao roditelj?
{63211}{63279}Da.
{63283}{63404}Meni se Ëini da je Mr. Lombardo bio vaö prijatelj.
{63408}{63482}Bio je.
{63486}{63580}Ali to se sve promenilo, kada...
{63584}{63771}vas je, prema vaöem svedoËenju,|Mr. Lombardo silovao..
{63775}{63923}23. Aprila proöle godine.|Jel to istina?
{63927}{64051}Ali u maju, kada ste|uhapöeni zbog posedovanja narkotika,
{64055}{64191}i kada su vam ponovo dali jedan poziv,|opet ste zvali Mr. Lombardo.
{64318}{64424}- Pa öta?|- "Pa öta"?
{64466}{64554}"Pa öta"?
{64567}{64643}Opa, Suzie.
{64647}{64802}Mesec dana nakon öto te je ovaj Ëovek silovao,|ti ideö kod njega za pomoÊ?
{64806}{64891}Meni zvuËi kao da si|ga joö uvek smatrala prijateljem.
{64895}{65059}- Trebala mi je pomoÊ.|- Siguran sam da ti je trebala. Ali on nije bio tu.
{65063}{65183}I ti si provela öest meseci|u popravnoj instituciji.
{65187}{65329}Da li te je to razbesnelo, Suzie? |To da je Sam otiöao? To da on nije bio tu?
{65366}{65524}- Is that why you're saying this?|- I said it, because it happened.
{65528}{65643}HoÊeö li sedeti tu i kunuti|se da te je Sam Lombardo silovao?
{65647}{65771}- Rekla sam da jeste.|- Dozvoli mi da ti postavim pitanje.
{65775}{65856}Da li si uûivala|da budeö gost drûave?
{65860}{65983}ObeÊavam ti da ako laûeö,|poöto verujem da laûeö,
{65987}{66043}ubrzo ponovo posetiti onaj|popravni dom, ili zatvor.
{66047}{66173}I zato Êu ti ponovo postaviti pitanje,|dok si pod zakletvom:
{66177}{66292}Suzie,|da li te je Samuel Lombardo silovao?
{66408}{66487}Miss Toller,|morate da odgovorite na pitanje.
{66585}{66698}- Miss Toller...|- Do avola!
{66702}{66843}- Nije bila moja ideja.|- Prigovor! Odbrana nabeuje svedoka.
{66847}{66932}Sud Êe Ëuti öta ima Miss Toller da kaûe.
{66936}{67009}Miss Toller?
{67051}{67210}Sam Lombardo me nije silovao.|Nije silovao ni Kelly.
{67214}{67307}Ovo je neËuveno!|Svedoku je branioc zapretio...
{67311}{67438}Ovaj sud ima nameru da|Ëuje Miss Toller-inu priËu.
{67442}{67491}Miss Toller?
{67495}{67579}Samo sam ûelela da povredim Mr. Lombarda.
{67583}{67675}Milsim, bio mi je drug u poËetku.
{67679}{67809}Kada su me uhapsili nije mi pomogao.|Otiöla sam u onu prokletu rupu.
{67813}{67927}- Prvo sam mu bila miljenica a onda, baö me briga?|- Reci joj da stane.
{67931}{68027}Kada je Kelly rekla da uradimo ovo,|pomislila sam, cool, öto da ne.
{68031}{68145}Veliki frajer koje me je ispalio,|poput Duquette, biÊe sjeban.
{68149}{68299}- Izvinjavam se Ëasni sudija moram da uloûim prigovor.|- »asni sudija, moûete li me sasluöati?
{68303}{68390}Mr. Baxter,|vi ne sudite u ovom sluËaju.
{68394}{68478}Idite i sedite.
{68559}{68684}Kelly je popizdela na Mr. Lombardo-a,|takoe. Zaljubljena je u njega.
{68688}{68863}Bio je njena fantazija ali onda|je saznala da on spava sa njenom majkom.
{68867}{68955}Jebem ti!|Napuöena stoko!
{68959}{69075}Skidaj te jebene ruke s'mene.|SrediÊu da te otpuste!
{69215}{69301}Samo beûi od mene.
{69333}{69488}- Isuse, ËoveËe, iskuliraj malo!|- Samo se pitam gde Êu sada da ûivim.
{69492}{69599}Izgubio sam kuÊu.|Budim se iz noÊne more.
{69603}{69745}Zaboravi na to.|Upravo smo dobili spor protiv Sandre Van Ryan.
{69780}{69919}- Tek takot?|- Ovi ljudi su ti uniötili ûivot.
{69923}{70041}Rekao sam ti da Êe iÊi predaleko.|Ovog puta su prevröili granicu!
{70045}{70144}PokuöaÊe da se dogovore, veruj mi.|MoliÊe da se dogovore.
{70159}{70239}Evo ih.|∆ekajte! Ajde, devojko.
{70243}{70410}Sam Lombardo je osloboen kada|je jedna od ûrtvi promenila svoju priËu.
{70414}{70511}Izvinite, ovamo.|Ume li neko da Ëita?
{70617}{70712}HoÊu da pritegneö njegova|muda na najbliûi zid.
{70716}{70843}Bilo je moguÊe, dok Gospoica Ne|Tako Pametna nije poËela da baca stvari unaokolo.
{70847}{70960}Ne mogu da verujem da Êeö samo da sediö|i da dozvoliö da se izvuku sa tim... sranjem?
{70964}{71036}To je samo jedna mala bela kuËka.
{71040}{71151}Izgleda da ne shvataö, Sandy.|Tvoja princeza je laûno svedoËila.
{71155}{71328}- PokuöaÊu da je saËuvam od zatvora.|- äta Êemo da radimo?
{71501}{71595}- Evo vaöe kafe, Sam.|- Hvala vam.
{71896}{71979}Ken...
{72227}{72285}Izvinjavam se öto kasnim.
{72289}{72424}- Javljaj se na pozive, Lenore.|- Vaûi, Mr. Bowden.
{72917}{72987}Hvala, Sandra.
{73054}{73179}VideÊu te ja ponovo.|Okej?
{73344}{73447}Drago mi je da te vidim, Tom.|Svrati, otiÊi Êemo na ruËak.
{73531}{73603}Vidimo se u klubu.
{73641}{73706}Vidimo se u klubu.
{73710}{73800}Vidimo se u klubu...
{73868}{73974}Tom, öta si dobio danas?|Hej, ËoveËe.
{74044}{74119}Ovo je za tebe.
{74123}{74231}Bio si odliËan, Ken.|Hvala.
{74235}{74338}Znam da bi voleo da se niöta|od ovog nije desilo. Ali desilo se.
{74342}{74481}Uzmi taj novac i uûivaj.|Nai neko lepo mestaöce.
{74485}{74550}Lenore, isprati Mr. Lombarda napolje.
{74554}{74667}- Do vienja, Sam.|- Do vienja, Lenore.
{75053}{75148}Pazi na moje guötere.
{75311}{75395}- Zdravo, Kelly.|- Crkni!
{75399}{75492}Znaö kako te moja majka plaÊa?|Izgubila je poverenje u mene.
{75496}{75615}Ne mogu staviti ruke na novac dok ona|ne umre, a ona ga troöi da bi platila tebi.
{75619}{75714}- éao mi je.|- Zaöto je ne pojebeö ponovo pa ga zajedno potroöite?
{75718}{75837}Mrzim te!|Mrzim te, kuËkin sine.
{76136}{76258}Vidiö? Ne mogu se vratiti|Êak i kad bi to ûeleo.
{77139}{77221}Prokleta sluûavka.
{78042}{78161}ZnaËi dobio si novac moje majke.|Koliko?
{78184}{78305}- Koliko?|- Znaö ti koliko.
{78309}{78388}Platila je koliko treba.
{78411}{78523}Upalilo je!|Zajebali smo kuËku.
{78527}{78612}Sve je ispalo kao öto si rekao.
{78616}{78767}- äta nije u redu?|- Nije u redu to öto si doöla ovde.
{78771}{78843}Jesi li ti normalna?
{78847}{78956}Da, luda sam,|Pitaj moju majku.
{79020}{79133}I, koliko je 8,5 miliona podeljeno na 3?
{79137}{79231}Super, dobra fora.
{79235}{79392}Mislite da je ovo zavröeno?|Ima ovo da se oduûi.
{79419}{79507}Ozbiljan sam.
{79531}{79675}Posle ovoga veËeras, nas troje|ne trebaju ponovo videti zajedno.
{79689}{79751}Posle veËeras?
{79755}{79892}Pa... ovde smo, zar ne?
{79919}{80006}Moûda je neko slavlje i u redu.
{80010}{80117}Ali znajte da smo u|dogovoru da od sad pa nadalje...
{80169}{80264}radite taËno onako kako ja kaûem.
{81255}{81383}Savetnici poput mene|znaju dosta interesantnih stvari.
{81640}{81740}Sada, ûelim da se vas dve poljubite.
{81744}{81872}Ajde. Nikad ne Ëekajte da vas neko moli.
{83719}{83818}Rekla sam da Êe nas napraviti na budale.
{83822}{83913}U pravu si.|Napravili su nas na budale.
{83917}{84019}Samo öto ih nisi dobro provalila.|»uj me...
{84023}{84099}Lombardo je spavao sa Sandrom Van Ryan.
{84103}{84219}Zaöto nam nije rekao?|To bi dalo Kelly dobar motiv.
{84223}{84296}Moûda su to Ëuvali za suenje.
{84300}{84435}Da si ti Lombardo, sigurno ne|bi voleo da sediö u zatvoru 3 meseca...
{84439}{84528}- Osim ako...|- Osim ako öta?
{84551}{84629}Osim ako nisi smeötao Sandri Van Ryan.
{84633}{84712}Lombardo je bio do uöiju u dugovima.
{84716}{84809}Bogataöica poput Barbara Baxter|je skupa.
{84813}{84972}- Ali zaöto je Kelly morala da ukrade taj novac.|Njen novac je u banci.
{84976}{85082}Ovaj momak je hteo da se oûeni za novac.
{85086}{85242}Kada to nije upalilo, iskoristio|je devojke da smesti Sandri Van Ryan.
{85246}{85303}Zajebo nas je.
{85307}{85409}Zajebavao nas je od poËetka.
{86679}{86811}- Dobar zamah.|- äta Êe te vi ovde?
{86815}{86949}- Znatiûelja, predpostavljam.|- Kako da unapredite vaöe plivanje?
{86974}{87072}O tome kako ide tebi, Sam-u i Suzie.
{87115}{87241}- Molim?|- HoÊete li da palite na Karibe?
{87245}{87357}- U troje teöko da ikad uspeva.|Vi ste siöli s'uma.
{87361}{87448}Teöko je da troje ljudi Ëuva tajnu.
{87452}{87528}Pogotovu ako su dvoje od njih zaljubljeni.
{87532}{87661}Ti i Sam stvarno ne biste|voleli onu tabletarku oko vas, jel da?
{87665}{87803}Jel ti do sada Sam|prodao ideju da maknete Suzie?
{87807}{87943}- To je ubistvo, mala.|- Policija... opametite se viöe!
{87986}{88072}Dobra si, snalaziö se, znaö?
{88076}{88191}Ali nemoj misliti da Êe|ona nakaza Suzie da izdrûi.
{88682}{88758}∆ao, Suzie.
{88762}{88864}Pazi öta radiö sa tim sranjem,|ili Êeö opet u zatvor.
{88868}{88963}Da, ili Êu se overiti.
{89095}{89271}Znaö, mislim da ti nisam|rekao da mi je ûao tvog prijatelja.
{89275}{89343}Kako se beöe zove?
{89392}{89476}Ajde, pomozi mi.|Znaö kako se zove.
{89540}{89707}- Davy.|- Stvarno mi je ûao zbog onoga.
{89711}{89782}- To je policijsko proseravanje.|- äta si rekla?
{89786}{89909}Ne moram da sluöam ta tvoja sranja.|Imam ja prijatelje sada...
{89913}{90069}Ne priËaj gluposti, Suzie.|Nemaö ti ni govno, i nikad ga neÊeö ni imati.
{90171}{90300}Pogledaj ovo.|Slobodno, ne ujeda.
{90304}{90383}Uzmi.
{90423}{90519}Tvoj prijatelj Sam je unovËio Ëek.
{90523}{90625}Stavio je novac na neki strani raËun.
{90629}{90731}Panduri ne znaju Ëije je ime na raËunu.|Misliö da je tvoje?
{90735}{90869}InaËe je i kupio plac na|malom ostrvu i kupio sebi brod.
{90873}{91027}- Zaöto mi priËaö sve to?|- Zato öto znam öta se dogaa.
{91031}{91127}Dvoje je druötvo, troje je guûva.
{91131}{91268}Ne misliö stvarno da Êe|Kelly i Sam podeliti novac sa tobom?
{91316}{91391}Ostavi me na miru.
{91576}{91679}Znaö, ja bih bio strejt neko|vreme da sam na tvom mestu,
{91683}{91798}da bih mogao da pripazim na svoje prijatelje.
{91822}{91913}Ne bih voleo da proeö kao...
{91917}{92003}kao Davy.
{92270}{92351}Sranje!
{92442}{92531}Ovde je Sam Lombardo.|LOstavite poruku.
{92896}{92979}Zvala si Sam-a?|äta nije u redu sa tobom?
{92983}{93124}- Ne znam kome da verujem.|- Meni moûeö verovati.
{93309}{93418}Jel Suzie tu?|Isuse, bojao sam se toga.
{93422}{93593}Ostavila mi je neku blesavu poruku na sekretarici.|Skroz je odlepila.
{93623}{93758}- Smiri tu kuËku.|- Zaöto ne moûeö da doeö?
{93762}{93842}Sam, tako mi nedostajeö.
{93903}{94049}I ti meni. Ali sada ne mogu.|Moramo se drûati plana.
{94073}{94160}- Ako se ona ne sredi...|äta onda?
{94164}{94255}Znaö i sama. SrediËu je.
{94259}{94400}Ali mi trebaö sada da budeö|uz nju umesto mene veËeras.
{94404}{94494}Tako. Super si.|Ti si ona koja je jaka.
{94498}{94607}Pozovi Suzie.|HoÊu da obe Ëujete ovo.
{94735}{94846}Vidite, moramo ostati smireni.|Svo troje.
{94850}{95013}Joö od suenja ljudi misle|da sam bogat pa se i ponaöam tako.
{95017}{95112}Nemoje dozvoliti da se taj pandur poigrava sa vama.
{95116}{95214}- Lako je tebi tako da kaûeö...|- Suzie, iskuliraj.
{95218}{95315}Jedini ljudi koji ovo|mogu da useru smo mi sami.
{95467}{95551}Vi Êete me prejebati jel da?
{95555}{95631}- Zaboga...|- HoÊete!
{95635}{95751}Jesi li ti retardirana ili su ti|mozak sjebala isparavanja iz moËvare?
{95755}{95884}To sam ja za tebe.|MoËvarno ubre, kao i moja mama.
{95899}{95975}Nemoj!
{96022}{96107}Glupa pizdo.
{96851}{96946}Uplaöena si, zar ne?
{97793}{97877}Isuse!
{97881}{97975}- Jesi li ti normalan?|- "Sam". To je Lombardo.
{97979}{98076}- Video si devojke...|- Kaseta je neprihvatljiva.
{98080}{98197}Na njoj je Van Ryan-ovakuÊa, i jebeni porniÊ!
{98201}{98320}Bacale su stvari jedna na drugu u sudnici.|Glumile su!
{98324}{98478}Svi su glumili! Uzeli su|8 miliona dolara od Sandre Van Ryan.
{98482}{98560}Pokuöala je da uniöti Ëoveku ûivot.
{98564}{98688}Mislila je da joj je silovao Êerku.|Nasela je kao i mi.
{98692}{98784}Sluöajte me oboje.|SluËaj je zatvoren.
{98788}{98971}Sandra Van Ryan Êe nas tuûiti zbog|naruöivanja privatnosti, zato ostavite to.
{98975}{99115}- Nadam se da sam bio jasan.|- Misliö da se ovde radi o novcu?
{99119}{99259}O tome da smo ispali glupi? Ispitaj te ga.|On je psihopata hladan kao kamen.
{99263}{99384}- Devojke Êe zavröiti mrtve.|- Dejte ovom balvanu J.F.Kennedy sluËaj.
{99388}{99525}- Razumem da...|- SledeÊi put Êu vas tuûiti.
{99529}{99643}Imate sreÊe öto vas proöli put nisam tuûio.|Jesam li slobodan sada?
{99647}{99736}- Da.|- Hvala.
{99750}{99820}- Puöikurcu jedan!|- äta si rekao?
{99824}{99961}- »uo si me, jebivetru.|- HoÊeö to da mi kaûeö napolje?
{99996}{100090}äta pa ti gledaö?
{101091}{101219}- Izgleda da sam preterao.|- Moglo bi se reÊi tako.
{101280}{101420}Jesi li ikada znala da Êe se neöto desiti,|a nisi uradila niöta da to spreËiö?
{101424}{101571}- Svima nam se to desilo.|- Neöto loöe se desi...
{101575}{101650}a ti niöta nisi uradio.
{101748}{101891}Uradio sam to jednom.|Ne ûelim ponovo.
{102342}{102451}Mislila sam da idemo u bioskop.
{102455}{102579}Mislim da nam treba samo da overimo.
{103009}{103064}Ajde.
{103209}{103290}éelim da ûivim na plaûi jednog dana.
{103294}{103447}Sranje! Ostavila sam kljuËeve.|Idem po njih.
{103911}{104027}- Kelly?|- Suzie...
{104049}{104139}Ja sam.
{104203}{104392}Brinuo sam za tebe.|Mislio sam da se okupimo joö jednom ali zadnji put.
{104396}{104472}- Jesi li ljut na mene?|- Ne, ne.
{104476}{104596}Trebao sam ti bolje objasniti tvoju ulogu.
{104600}{104676}VeËeras Êemo ponovo obraditi plan.
{104739}{104832}Ovo je proslava a ne pakt za samoubistvo.
{104836}{104935}IskuliraÊemo,|samo se opusti.
{104939}{105041}Uzmi malo öampanjca,|gledaj zvezde.
{105070}{105191}Kelly, imaö li neko Êebe|u gepeku maminog Rovera?
{105195}{105307}Budi aneo i otrËi po njega?
{105330}{105409}Dobra devojka.
{105413}{105513}Da ti ispriËam öto sam kupio brod za nas.
{106986}{107065}Jesi li dobro?
{107069}{107202}Mama Êe me ubiti ako sazna|da sam uzela Rover-a.
{108035}{108193}- Nije se sinoÊ vratila kuÊi?|- Ali njena garderoba je i dalje ovde.
{108197}{108328}Walter, ako se razboliö,| pojeöÊemo te odmah.
{108332}{108476}Naöao je nekakve zube u prikolici.|- Rekao je da Êe odgovarati.
{108480}{108572}Suzie nije bila u ökoli joö od suenja.
{108576}{108667}Kaûu da neÊe moÊi da maturira.
{108671}{108766}Kelly Van Ryan je|uvukla u sve ovo.
{108770}{108905}PotraûiÊemo je, Ruby.|Ako neöto saznamo javiÊemo ti.
{108931}{109005}Ajmo.
{109403}{109539}- Ovako poËinje.|- Ne znamo joö uvek niöta.
{109543}{109648}- Izdaj poternicu za Suzin auto.|- Ideö negde?
{109652}{109783}- Imaö sastanak?|- Samo proveri auto, molim te.
{109979}{110063}Ovamo, pored tog starog Ëamca.
{110067}{110181}- Ti i Suzie dolazite ovde?|- Da, ponekad.
{110185}{110350}Mnogo dece dolazi ovamo.|Jel se neöto loöe desilo Suzie?
{110354}{110453}Sali ke Lombardo ikad dolazio ovde?
{110457}{110614}- Jel sam rekao neöto smeöno?|- Samo ideja da bi on...
{110618}{110702}»uo sam da je bio|dosta prisan deci.
{110706}{110821}- Vi ste bili drugari, jel da?|- Ubacio me je na Ëas jedrenja i u tim.
{110825}{110899}Da to odradim tokom|ökolovanja, kao i on.
{110903}{111068}On je dobio stimpediju zbog atletike.|Brodovi nemaju nikakve veze sa tim.
{112307}{112446}Ja Êu ostati ovde neko vreme mali,|zaöto ti ne odeö kuËi?
{112564}{112655}Jimmy...
{112659}{112761}Ljudi nisu uvek onakvi kakvim se|predstavljaju. Zapampti to.
{113180}{113347}Ovde su to uradili. Telo mora|da je u moËvari. Ali su napravili greöku.
{113351}{113492}- Auto je bio bio parkiran pored terminala za autobuse.|- Misliö da ga Sam nije parkirao?
{113496}{113596}∆ekaj sekund.|Potraûite otiske na automobilu.
{113600}{113725}Ako je Suzie ubijena, verovatno je to|uradila Kelly. Ona je sve ovo i zapoËela.
{113729}{113846}- Koliko vam treba vremena?|- Krvnu grupu Êemo uraditi odmah.
{113850}{113929}Ako ûelite DNK, analizu, potrajaÊe nedeljama.
{113933}{114046}Jadna priglupa Suzie. Nikada nije|imala ni öanse. A Kelly je sledeËa!
{114050}{114137}Prekini sa tim. Odmah!
{114141}{114244}NeÊu ni da Ëujem da se|dosaivao Lombardo-u.
{114326}{114457}David! ∆im saznaö|identitet javi mi.
{114486}{114579}- HoÊwö li mi uËiniti jednu uslugu?|- Ray, Ëuo si ga.
{114583}{114683}Rekao je da ja stojim podaleko od njega, ne tebi.|äta ako sam u pravu?
{114687}{114776}Moraö mi poÊi oko ovoga,|partner si mi.
{114780}{114995}- A ako zubi ne pripadaju Suzie?|- Ako nisam u pravu, ostaviÊu se ovoga.
{116030}{116145}- Zdravo.|- éelim da te vidim.
{116149}{116258}Ja sam u gostinskoj kuÊi.|Sam, stvarno sam nervozna.
{116262}{116392}Kelly, smiri se.|Uzmi jedan od maminih valijuma.
{116396}{116483}U sledeÊih nedelju dana je sve gotovo.|Bogati smo.
{116487}{116617}äta ako nas otkriju?|StaviÊe te na elektriËnu stolicu.
{116621}{116723}Ostani u sotinskoj kuÊi.|Nemoj da ides na maturske ûurke.
{116727}{116791}Toliko te volim.
{116795}{116892}I ja tebe volim.|Budi dobra devojka i ostani tu gde si.
{117447}{117555}Posmatrate ljude kroz prozor...|nije li to kaûnjivo?
{117602}{117699}- Suzie Toller je nestala.|- Od kad?
{117703}{117815}Nije doöla sinoÊ kuÊi.|Naöli smo njen auto.
{117819}{117958}- Ray misli da je ubijena.|- NE znam öta da vam kaûem.
{117962}{118126}- Recite mi gde ste bili sinoÊ.|- Ne moram da vam kaûem, jel da?
{118215}{118331}Uite unutra.|HoÊu da vam pokaûem neöto.
{118585}{118649}Izgleda kao da odlazite...
{118653}{118784}Kelly-in dosje. ProËitajte ga. PronaÊi|Êete da je ona besna, seksualno zbunjena devojka -
{118788}{118851}- koja je pretila da Êe ubiti dve osobe.
{118855}{118953}- Koje dve osobe?|- Jedna je njena majka.
{118957}{119105}Druga je...|ûenska osoba iz razreda -
{119109}{119199}- sa kojom je bila u ljubavnoj vezi.
{119203}{119367}- Suzie?|- Imate dosje. ProËitajte ga.
{119387}{119493}DaÊe vam nov pogled na sluËaj.
{119497}{119623}Zaöto mi niste rekli ovo pre suenja?
{119627}{119780}Zato öto sam tada imao|principe koji su mi mnogo znaËili.
{119784}{119852}Sada...
{119856}{119954}mi nisu toliko bitni.
{120241}{120332}Sada bi verovatno trebalo da idem.
{120336}{120457}Osim ako ne planirate da|me zadrûite zbog neËeg.
{121089}{121182}äta se deöava?|Gde je Lombardo?
{121186}{121278}- Otiöao je.|- Krvna grupa odgovara Suzie-noj.
{121282}{121385}Ima joö neöto öto bi trebalo da znaö.
{121389}{121489}Ako je Suzie mrtva, mislim da je ubica kod Kelly.
{121543}{121628}Ray? Sranje.
{121885}{122027}- Ko je?|- Detektiv Duquette. Otvorite kapiju.
{122765}{122870}- Zdravo, Kelly.|- äta Êeö ti ovde?
{123252}{123357}Gde je Kelly?
{123516}{123615}Samo sam pogledao u stranu na sekund.|Na deliÊ sekunde.
{123619}{123749}I odjednom me je öutnula u meunoûje.
{123753}{123883}Nisam pao na zemlju ali|me je usporila dovoljno da...
{123887}{124047}Nisam mogao da je uhvatim.|Okrenula se prema meni sa piötoljem.
{124051}{124166}Ispalila je jedan metak.|Pogodila me je u rame.
{124223}{124324}Nisam imao izbora.
{124381}{124544}Morao sam da uzvratim vatrom.|Dva metka. Mislim. U grudi.
{124619}{124708}Otiöao sam tamo da je zaötitim.
{124745}{124819}Otiöao sam tamo da je zaötitim.
{124823}{124954}Duquette, u vojnoj|obaveötajnoj imamo izreku:
{124958}{125090}"Jednom je öansa, drugi put sluËajnost,|treÊi put je neprijateljska akcija".
{125094}{125239}Ovo vam je drugi put, Duquette.|NeÊe biti treÊeg puta.
{125243}{125336}Da li je bilo dobro|öto ste pucali nebitno je.
{125340}{125491}Ignorisali ste predpostavljene.|Zbog toga su dve devojke mrtve.
{125495}{125595}You are terminated|without pension or benefits.
{125599}{125802}Duquette je naöao Susan Toller-ine zube|i krv na Stoner Beach plaûi.
{125806}{125888}Njena krv je takoe bila|u kolima Van Ryan-ovih.
{125892}{126049}To nas je navelo da pomislimo|da ju je ubila Kelly Van Ryan.
{126053}{126131}Ali nije bilo u redu.
{126192}{126257}Mr. Duquette...
{126293}{126390}Ovo sasluöanje je zavröeno.|This investigation is concluded.|Otpuöteni ste.
{127015}{127091}Hvala.
{128371}{128445}De si, kolega.
{128449}{128559}Nisam te oËekivao do sutra.
{128639}{128733}- Lepa devojka!|- Zaöto Kelly nisi smestio?
{128737}{128870}- KuËka me je upucala.|- Zar vas ne uËe da razoruûate ljude?
{128874}{128943}Da im pucaju u nogu?
{128947}{129100}Jesi li ti postao osetljiv|pre nego öto si ubio Suzie flaöom ili posle?
{129104}{129186}Kelly nije trebala da umre.
{129190}{129301}Ispalo je savröeno. Ubeeni|su da je Kelly smaknula Suzie.
{129305}{129399}- Nisam mogao da ih odgovorim od toga.|- Ne volim iznenaenja.
{129403}{129503}"Svaki beli oblak ima srebrnu postavu".
{129507}{129640}Od sada nema greöaka.|Od sutra me viöe nikada neÊeö videti.
{129644}{129735}Oko toga...
{129739}{129895}Razgovarao sam u banci.|Treba im dva dana da izvröe transfer.
{129899}{129992}- Sereö.|- Misliö? Pozovi ih sam onda i uveri se.
{129996}{130139}äto se ûuriö? Iskuliraj dan ili dva. OtiÊiÊemo na jedrenje.
{130143}{130283}Samo öto mi je brod isporuËen.|Dobro bi mi doöla posada.
{130379}{130463}Nazdravimo za bogate raËune u bankama.
{130498}{130609}Nasmej se, druûe.|Bogat si Ëovek.
{130661}{130755}Za bogate raËune,|i uspeöne poslove.
{130759}{130839}I uspeöne poslove.
{131247}{131403}Vidiö taj Ëekrk?|Okreni ga nekoliko puta, popustio je.
{131519}{131663}- Misliö na ovo?|- Da to je Ëekrk, sluûi da se pritegnu jedra.
{131667}{131765}- PoËni da vrtiö.|- Ovo bi trebalo da je odmor.
{131769}{131834}Kupi sebi lep motorni brod.
{131838}{131967}- Uskoro Êu od tebe napraviti mornara.|- Ili Êeö me udaviti.
{132298}{132410}- Zapelo je.|- Stavi malo ulja za podmazivanje.
{132509}{132654}- Zapelo je kaûem ti.|- Mora da se dizalica zaglavila.
{132655}{132735}Idi na starbord (desna strana broda) i otkaËi je.
{132736}{132821}Nerazumem ni reË öto si rekao.
{132825}{132961}Prati ovu ogradu i pogledaj|da li se zakaËila za neöto.
{133005}{133092}Ubijaö me.
{133255}{133372}- Misliö na ovo?|- Da baö to. vidiö li neöto?
{133477}{133555}Pogledaj malo niûe.|E, tako.
{133775}{133872}Izgleda da sam zaboravio|da ti kaûem neöto, Ray.
{133876}{134007}"Jedna ruka za brod,|druga je za sebe".
{134607}{134723}- äta se desilo?|- Dobar pokuöaj, jebivetru!
{134921}{135016}Ali... ali, ti si mrtva!
{135031}{135095}Ne, nisam.
{135129}{135257}- Sam, za ime Boûje.|- éalim, druûe.
{135261}{135386}Nisi trebao da ubijeö Kelly.|A ni ono dete kod Glades-a.
{135390}{135499}- Kako mu je beöe ime?|- Davy.
{135791}{135936}To je moj sin, Walter.|Radi ovo veÊ dugo, ne boj se.
{135960}{136047}Hvala öto ste doöli u Glades.
{136360}{136473}Doöli ste da gledate Walter-a,|ili ste doöli u poslovnu posetu?
{136477}{136609}- Ne, slobodan mi je dan.|- Pa i izgledali ste mi drugaËije.
{136613}{136745}- Nadala sam se da Êete razgovarati sa mnom.|- O Suzie?
{136749}{136888}U stvari nadala sam se da|Êete mi reÊi neöto o  Ray Duquette-u.
{136973}{137135}Nekad je dolazio ovamo.|Imao je neku vezu sa jednom od radnica.
{137139}{137220}"Girls"... öto su radile u Glades-u.
{137243}{137348}Zaljubio se u nju,|kako sam Ëula.
{137352}{137453}- Jel joö uvek ona radi ovde?|- Ne od jedne noÊi.
{137457}{137603}Sve öto znam je, da je ona|sledeÊeg jutra otiöla a deËak je bio mrtav.
{137607}{137731}Momak po imenu Davy,|se zaljubio u Ray-evu kurvu.
{137815}{137941}Video je Ray-a kako je öamara|i pokuöao je da ga zaustavi.
{137945}{138028}Zato ga je Ray ubio.
{138032}{138152}Suzie je to videla, pa ju je uhapsio.
{138156}{138310}Smestio joj, samo da pokaûe da moûe.
{138314}{138386}To je sve öto se|moûe reÊi o njemu.
{138657}{138808}Za Ray-a.|Pobedili smo, Sam. Gotovo je.
{138979}{139091}äto si tako paranoiËan.|Pogledaj oko sebe, Sam.
{139095}{139227}Moraö me prvo nauËiti da vozim ovo Ëudo,|tek onda te se mogu otarasiti.
{139470}{139543}Okej, Toller.|HoÊu da podesim jedra.
{139547}{139643}- Uhvati se za onaj Ëekrk.|- Ne, ja hoÊu da vozim.
{139647}{139763}Ne voziö nego jedriö.
{139767}{139919}Sada uhvati taj Ëekrk.|éelim da krstarim malo.
{140006}{140117}To je jedna od stvari koju|sam primetila odmah kod tebe,
{140121}{140183}Voliö da krstariö.
{140229}{140327}- Suzie...|- Na primer kad si bio na koledûu.
{140331}{140458}Kladim se da si iöao na Ëasove|ako si mogao da imaö puno izbora.
{140462}{140551}Nikada nisi imao knjige.|Pozajmljivao si ih od devojaka -
{140555}{140638}- a onda si morao da ih pojebeö.
{140642}{140726}Jel tako bilo?
{140755}{140839}Da.
{140843}{140964}Epa, imam dobro kviz pitanje za tebe,|puno izbora, naravno.
{140999}{141169}Pre nego öto je isplovila, Medea je|ubila kralja Creon-a i princeze...?
{141191}{141249}Kamenom?
{141253}{141343}Harpunom? Ili...
{141347}{141452}- Otrovom?|- Otrov!
{141542}{141605}Dobar odgovor!
{142344}{142423}Dobar kamion.
{142580}{142672}Prodajeö Ëamac?
{142747}{142889}Ovo je bio Suzie-in brod.|Mislim da joj viöe neÊe trebati.
{142918}{143043}Smeöno, ne bih pogaao|da li je Suzie dobar mornar.
{143075}{143252}Jednom je jedna ûena testirala njen|koeficient inteligencije. Bio negde oko 200.
{143276}{143386}Ta devojka je mogla da|uradi öta god je htela.
{145043}{145167}Znaö, kada su me uhapsili|zvala sam te oko 100 puta.
{145283}{145419}Stvarno sam verovala u to da si mi drug.
{145423}{145511}Bila sam naivna!
{145567}{145627}äta je ispalo bolje?
{145631}{145751}Ta slama iz Kelly-inog nosa ili  nose,|ili taj pseÊi okovratnik oko tvog vrata?
{145755}{145843}äta mislite, Mr. Lombardo?
{146186}{146319}Izgleda da volite ista mesta.|»udi me da se do sada niste upoznali.
{146323}{146475}Baö Smeöno.|- Ako greöiö u vezi ovoga moûe me uhapsiti.
{146479}{146617}Veruj mi, ovaj je podmitljiv,|dopaöÊe mu se, pogotovu moje ubistvo.
{146621}{146696}Odlazi unutra i upoznaj novog drugara.
{146997}{147074}äta pijeö?
{147352}{147476}Ne stiskaj toliko.|SlomiÊeö dokazni materijal.
{147562}{147654}Za ime Boûje.
{147980}{148076}- Zdravo, Kelly.|- äta Êeö ti ovde?
{149173}{149270}Mogu li vam postaviti pitanje,|Miss Toller?
{149274}{149391}Da li vam se svialo|da budete gost ove drûave?
{149407}{149503}Uf, nadam se da neÊu|nikad da te iznerviram.
{149559}{149635}Keö je spremljen u malim novËanicama.
{149639}{149758}»ek je na raËunu,|minus milion za Ruby i Walter-a -
{149762}{149835}- i minus moja standardna naknada.
{149839}{149924}SluËaj je zatvoren
{150177}{150256}Suzie...
{150280}{150367}Budi dobra.
{150375}{150520}preveo GALIX@mail to galix@ptt.yu
{150545}{152045}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/7pwfs|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
