{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1936}{1983}Poludite!
{2229}{2276}OsjeÊate li to?
{2633}{2688}Kaûem ti, curo,|öef Êete najuriti.
{2689}{2724}Hej, to je drugaËiji mentalitet, Jay.
{2725}{2764}Hajde. Nije njega briga|za povijesti...
{2765}{2796}ovog prostora.
{2797}{2840}Nazvala si ga puöaËem, Suzette.
{2841}{2874}Zar sam to rekla?
{2875}{2926}Hej, puno psujem, OK?
{3400}{3463}Idemo svi!
{3464}{3495}Diûite se!
{3496}{3543}äto to radiö?
{3544}{3594}Nemoj da te vidi|da pijeö.
{3784}{3855}Lovi te Suzette.
{3856}{3903}Pijem rum-colu
{3904}{3943}prije nego se on rodio.
{3944}{4002}Moûe se iÊi jebati.
{4366}{4401}Vidiö to kupatilo?
{4402}{4465}Jim Morrison se onesvijestio|jedne veËeri...
{4466}{4513}sa mnom ispod njega.
{4514}{4597}Jim Morrison je duh,|a ti si.
{4598}{4633}Hajde, Matt.
{4634}{4673}Ne mogu ne raditi ovdje.
{4674}{4721}Moûeö me slobodno upucati.
{4722}{4785}Znaö, upravo sam popravila auto...
{4786}{4856}dugujem stanarinu, dugujem lovu svima.
{4886}{4921}Hajde.
{4922}{4957}Hajde, ozbiljno.
{4958}{5000}Zabavna sam. Ljudi me vole.
{5030}{5073}Ja sam duöa ovdje, ËovjeËe.
{5074}{5117}Ne ûeliö me izgubiti.
{5118}{5153}Ja sam Suzette!
{5154}{5209}Pa, Suzette,|morat Êemo vidjeti...
{5210}{5268}hoÊe li ovaj klub preûivjeti bez tebe.
{5465}{5501}Sranje!
{6610}{6652}äto radiö?
{7010}{7095}1, 2, 3, 4, 5
{7098}{7182}6, 7, 8, 9, 10.
{9187}{9221}Vinnie.
{9372}{9414}Vinnie.
{11068}{11135}Neöto nije u redu sa ovom pumpom.
{11136}{11183}Ne, pumpa je u redu..
{11184}{11226}Morat Êete platiti gotovinom.
{11227}{11258}O, hajde, ËovjeËe.
{11259}{11304}Nemam gotovinu, OK?
{11305}{11338}A taj stroj je neispravan.
{11339}{11381}Zar nemate neku onu stvarËicu?
{11382}{11461}Znaö, onu provlaËeÊu stvarËicu?
{11740}{11783}Odvratno!
{11840}{11873}Odvratno!
{11874}{11934}I nema izgovora za to.
{11935}{12023}Oslonio sam se na ruku i zdrobio
{12024}{12059}dvije muhe!
{12060}{12101}Na mojoj ruci!
{12102}{12166}Ovo je uûasan,|uûasan, autobus!
{12464}{12517}Oprostite.
{12518}{12561}Zdravo.
{12562}{12651}Pitala sam se da li mi moûete pomoÊi?
{12652}{12683}Malo sam u ökripcu sa lovom.
{12684}{12735}I kad bi mogao svatko od vas|dati po jedan dolar.
{12736}{12779}Dolar od svakog od vas...
{12780}{12829}stvarno biste mi pomogli. Ja...
{12898}{12939}Ne radim ovo inaËe.
{12974}{13037}OK. Pa koliko god mi moûete dati.
{13038}{13101}50 centi, 25 centi.
{13102}{13141}Auto mi leûi tamo vani...
{13142}{13173}ostala sam bez goriva...
{13174}{13237}i samo ûelim stiÊi do Phoenixa.
{13238}{13276}Phoenixa?
{13332}{13363}Platit Êu vam rezervoar goriva...
{13364}{13408}ako me povezete.
{13483}{13586}Prvo, jedna muha sleti,|a onda i druga poËne...
{13587}{13622}PoËeo sam luditi.
{13623}{13698}Zamisli,|seksali su se na mojoj koûi.
{13699}{13750}Nadam se da Êeö preboljeti.
{13751}{13786}Isprao sam bakcile.
{13787}{13846}Kad doem u Phoenix,|okupat Êu se.
{13847}{13906}Doista, öto to govori o ljudima?
{13907}{13966}U biti radimo isto öto i muhe.
{13967}{14034}Muöka muha popne se na|ûensku muhu...
{14035}{14074}i onda... ta aktivnost.
{14075}{14135}Ta sliËnost je stvarno depresivna.
{14136}{14191}I zaöto ideö u Phoenix?
{14192}{14247}To ne mogu otkriti.
{14248}{14283}O, razumijem.
{14284}{14371}Da li ti je dozvoljeno otkriti svoje ime?
{14372}{14421}Harry Plummer.
{14454}{14502}Jesi li pisac,|Harry Plummer?
{14503}{14574}Je li to stara pisaÊa maöina...|izmeu tvojih nogu?
{14575}{14630}Jeste,|i ja sam pisac...
{14631}{14674}ali ne ûelim razgovarati...
{14675}{14718}o tome zaöto idem u Phoenix.
{14719}{14765}Onda prestani spominjati.
{14830}{14884}Zaöto ti ideö u Phoenix?
{14918}{14949}Posjetiti prijateljicu.
{14950}{14985}Udana je za nekog bogataöa.
{14986}{15017}On je advokat ili tako neöto.
{15018}{15078}Pitat Êu je moûe li mi posuditi|neöto novca.
{15079}{15115}To je jako loöa ideja.
{15116}{15147}Zaöto? äto je?
{15148}{15187}Pojaviti se nenajavljeno,|i pitati za novac.
{15188}{15219}Bit Êe uvrijeena.
{15220}{15287}-Bila mi je najbolja prijateljica.|-Bila je? Kad?
{15288}{15323}Iöli ste u ökolu skupa?
{15324}{15369}Hej, ne svia mi se öto|me pokuöavaö prokuûiti. U redu?
{15370}{15433}I uzgred, krivo si sve shvatio.
{15434}{15438}Napustili smo ökolu...
{15439}{15471}Napustili smo ökolu...
{15472}{15539}bile smo cimerice,|i Ëesto smo...
{15540}{15611}Pa, bile smo poznate,|ako baö moraö znati.
{15612}{15643}Kako poznate?
{15644}{15684}Bile smo groupi.
{15758}{15793}Ako si svirao u L.A.-u...
{15794}{15841}Velike su öanse,|da smo zvekli, duöo.
{15842}{15875}Zvekli?
{15876}{15943}Da.|Ono öto su te muhe radile...
{15944}{15999}na tvojoj maloj ruci tamo.
{16000}{16031}Baö tako.
{16032}{16087}Jesi li ikad Ëuo za Franka Zappu?
{16088}{16135}Naravno.|Majke Izuma.
{16136}{16179}Hej, vrlo dobro, Harry.
{16180}{16221}E pa on nam je dao nadimak.
{16222}{16291}Sestre KresaËice.
{16436}{16471}Ali niste bile zapravo sestre.
{16472}{16499}Ne.
{16500}{16531}E to je dobro.
{16532}{16563}Ne bi mi bilo ugodno...
{16564}{16595}da ste zaista sestre.
{16596}{16631}Sada ti nije ugodno, Harry.
{16632}{16683}U redu sam. Samo mi je vruÊe.
{16684}{16743}Da.|Izgledaö kao eskim.
{16744}{16819}I prestani njuökati|po mojim sranjima, u redu?
{16820}{16891}Kad se pojavim|na njenom pragu...
{16892}{16939}prekinut Êe sa svime...
{16940}{16991}jer Êemo se iÊi zabavljati.
{17020}{17135}Samo sjedi tu|i budi putnik.
{17232}{17306}Izgledat Êeö prekrasno.
{17307}{17362}Zaöto ne bih zamijenila|cijelu glavu...
{17363}{17418}jer ti imaö sliku|neke osobe, mama...
{17419}{17454}a to nisam ja.
{17455}{17502}Hannah, bit Êeö|mi zahvalna...
{17503}{17538}ako me posluöaö.
{17539}{17598}Samo ûelim normalnu kosu.
{17599}{17670}Ali nije u pitanju normalna,|veËer, duöo.
{17671}{17706}Opireö se.
{17707}{17750}Ne opirem se. Ja...
{17751}{17810}Opireö se svemu|öto kaûem...
{17811}{17882}i to te Ëini nesretnom.
{17883}{17918}Sada...
{17919}{17982}hoÊemo li je zaËeöljati|ili ukovrËati?
{17983}{18030}Ne. Bez kovrËanja.|Preklinjem te.
{18031}{18078}Radije bi je odsjekla.
{18079}{18134}U redu.|ZaËeöljat Êemo je...
{18135}{18182}i prikaËiti i presaviti...
{18183}{18233}i pokuöat sa malo uvrtanja.
{18303}{18350}Zaöto mora biti prema gore?
{18351}{18406}Ne razumijem|zaöto je to pravilo.
{18407}{18489}Zato da se ljudi dive|tvojim nauönicama.
{18876}{18907}50 mi je.
{18908}{18982}Hej, bolje ti je da imaö dobar razlog|öto se zajebavaö sa mojoj muzikom
{18983}{19030}50 mi je...
{19031}{19075}i poklanjam si|roendanski poklon.
{19076}{19111}ReÊi Êu ti öto je...
{19112}{19171}ali mi moraö obeÊati|da me neÊeö osuivati.
{19172}{19246}Moraö nekome reÊi|zar ne, Harry?
{19273}{19320}Odrastao sam u Phoenixu.
{19321}{19387}Otiöao sam u L.A.|da postanem scenarist.
{19388}{19429}Sa 30 godina|zadao sam si rok.
{19430}{19465}Rekao sam,|"Ako ne budem uspjeöan...
{19466}{19539}do svoje 50-e|vraÊam se u Phoenix."
{19764}{19826}U ûivotu nisam pucao iz piötolja.
{19913}{19968}Ima samo jedan metak.
{19969}{20052}Jedan metak namijenjen|odreenoj osobi.
{20248}{20282}I koja bi ta odreena osoba|trebala biti, Harry?
{20326}{20368}Moj otac.
{20402}{20481}Idem u Phoenix|da ubijem oca.
{20740}{20779}Hej, vrlo otmjeno.
{20780}{20835}Jesi li napisao koji film|koji sam moûda vidjela?
{20836}{20863}Nemam namjeru odsjesti|u nekoj ruöevini...
{20864}{20895}gdje se svugdje Ëuje|ledomat.
{20896}{20939}O, ne. Ali si tip koji|se vozi autobusom.
{20940}{20974}To je ono öto ne kuûim.
{20975}{21013}Ne vozim niti letim.
{21014}{21045}Niti leti.
{21046}{21097}Prava si mustra, Harry.
{21098}{21187}Prijavit Êeö se u hotel, okupati|i onda upucati svog oca.
{21188}{21234}Prozori su otvoreni.
{21235}{21318}Ne bi ti ubio ni muhu, Harry.
{21383}{21427}Ja sam osoba koja,|kada ima cilj,...
{21428}{21458}postajem jako fokusiran.
{21459}{21518}Nisi ti fokusiran.|Ti si mutan.
{21519}{21547}Ja sam mutan?|A öto je sa tobom?
{21548}{21587}Ja sam definitivno mutna.|Nisam ni rekla da nisam.
{21588}{21616}Ostajeö bez goriva...
{21617}{21651}prosjaËiö,|imaö tetovaûe.
{21652}{21689}Rekla sam da sam mutna, Harry.
{21690}{21729}Ti si jako mutna.|Jako kaotiËna.
{21730}{21769}Auto ti je u neredu,|puöiö...
{21770}{21833}i iöla si svugdje|i seksala se sa razliËitim ljudima.
{21834}{21881}Jesam li dobro rekao?
{21882}{21935}Ne nosim ni donje rublje,|gospodine Looney Tunes.
{21936}{22068}-Sada izlazi iz mog neurednog auta.|-Ne mogu otvoriti vrata.
{22151}{22202}Adios, ubojico.
{23108}{23190}Hannah, duöo, poûuri.|Svi te Ëekaju.
{23191}{23221}Izgledaö fantastiËno.|Pogledaj ovo.
{23251}{23278}Hvala tata.
{23279}{23306}Izgledaö super.
{23307}{23334}Hvala ti tata.
{23335}{23370}Hajde, duöo.
{23420}{23447}Tako je. Hajde.
{23448}{23488}Tu ti je mjesto.
{23551}{23598}Poûuri se.
{23599}{23666}Idemo svi. Sada svi skupa.
{23667}{23702}Malo nazad.
{23703}{23773}Nazad, nazad.|Skupite se.
{23774}{23827}Slikanje.
{23828}{23855}Mirni.
{23856}{23891}Pogledajte ovamo.
{23916}{23947}U redu. 1, 2...
{23994}{24058}U redu.|Idemo sada.
{24059}{24103}Poûuri.
{24228}{24259}Pribliûi se.
{24260}{24290}Pogledajte ovamo.
{24291}{24330}U redu. 1, 2, 3.
{24331}{24362}Ovamo svi.
{24363}{24418}U redu.|Sada svi u auto.
{24419}{24458}Hajdemo.
{24459}{24501}Poûuri.
{24563}{24606}Tako si lijepa.
{24607}{24641}Mama!
{24642}{24678}Preko ramena...|Oboûavam to.
{24679}{24714}U redu, narode. Zabavite se.
{24715}{24750}Ne zaboravi maramu.
{24751}{24786}Zdravo tata.
{24787}{24823}Zdravo!
{24824}{24858}Zabavite se!
{24859}{24895}Vidimo se.
{24960}{24995}Barkley! Barkley!
{25036}{25086}Ode ona.
{25087}{25133}Izgleda prekrasno.
{25134}{25165}Zar ne?
{25166}{25214}Kao princeza.
{25807}{25862}G. Harry Plummer|je prijavljen ovdje.
{25863}{25910}Molim vas broj njegove sobe.
{25911}{25944}Vaöe ime?
{25945}{25981}Suzette.
{26090}{26140}Da. Ovdje recepcija.
{26141}{26229}G. Plummer, ovdje je Suzette|i traûi vaö...
{26230}{26285}Kakav to ples izvodimo ovdje?
{26286}{26360}Harry? Da.|Moram s tobom razgovarati.
{26393}{26435}Zato öto moram..
{26436}{26470}Zato jer moram.
{26471}{26576}HoÊeö da kaûem cijelom|svijetu öto spremaö?
{26577}{26629}Koji ti je broj sobe?|Ispljuni.
{26630}{26699}U redu.
{26700}{26738}Hvala.
{26824}{26862}Ovo nije prikladno.
{26863}{26910}Upadaö u moj prostor.
{26911}{26963}Kreirao sam svoj okoliö.
{26964}{27018}Povalit Êu te, Harry.
{27075}{27114}U redu.
{27115}{27158}Hej, öto je ovo?
{27190}{27279}Jesi li ti u nekom kultu ili neöto?
{27280}{27321}Zovem osiguranje.
{27322}{27390}äto George Harrison radi ovdje?
{27391}{27427}Ne diraj to.
{27428}{27471}Niöta ne diraj.
{27472}{27507}Ovo je uûasno.
{27508}{27555}Tvoje oËi gledaju u sve.
{27556}{27620}Moraö neöto povaliti, Harry.
{27664}{27695}Molim te, izai iz sobe.
{27696}{27765}Ti trebaö povaliti,|i ja trebam povaliti...
{27766}{27815}i nalit Êu si rum-kolu...
{27816}{27855}a onda pod tuö...
{27856}{27927}a onda Êu te "znaö-öto".
{27928}{27969}Pogledaj ovamo!
{27970}{28007}Ne ûelim se seksati.
{28008}{28042}Ja Êu ti pokazati.
{28043}{28126}Ne. VeÊ si oneËistila|moj okoliö.
{28127}{28167}Samo stojim ovdje.
{28168}{28198}Ne stojiö.
{28199}{28270}Viöe si ti po sobi nego ja.
{28316}{28359}Sluöaj, Suzette...
{28360}{28427}ja imam vrlo posloûen|ûivotni stil.
{28428}{28503}Ovo je treÊa soba u kojoj sam|otkad sam ovdje.
{28504}{28559}Prva je bila preblizu liftu...
{28560}{28601}druga je gledala u susjedstvo...
{28602}{28633}gdje sam odrastao.
{28634}{28690}Ako ne radim stvari disciplinirano
{28691}{28725}pogotovo kad putujem
{28726}{28768}razvijam psihiËke probleme.
{28769}{28850}Na primjer stolica mi bude zatvorena.
{28851}{28901}Kao da sam to trebala znati.
{28902}{29033}Ima odreene stvari koje mi|ne gode, a seks je jedna od njih.
{29034}{29061}Ne seksaö se?
{29062}{29086}ToËno.
{29087}{29118}Koliko je proölo, Harry?
{29119}{29151}10 godina.
{29152}{29234}10 godina!|Laûeö mi!
{29235}{29286}Naöao sam naËin da mi|ûivot funkcionira.
{29287}{29343}Ali ne funkcionira, mislim,|Ëini ti se da je u redu,
{29344}{29406}jer slaûeö stvari i|paliö svijeÊe.
{29407}{29470}da bi ti proradila crijeva?
{29471}{29545}Harry, daj da ti ga izdrkam.
{29546}{29589}- Ne!|- O, ma daj.
{29590}{29659}Harry, ja dobro drkam.
{29660}{29703}Ne. Molim te.|Drûi se dalje od mene.
{29704}{29747}Ja... Ja ne radim|stvari naglo.
{29748}{29786}Ja volim razmisliti najprije...
{29787}{29858}a ti si previöe... previöe...
{29859}{29898}Previöe öto?
{29959}{29998}Nagla.
{30064}{30130}U redu.|Ostavit Êu te na miru.
{30164}{30215}Ali moram malo odspavati.
{30216}{30265}Gdje odspavati?
{30266}{30317}U tvom okoliöu.
{30358}{30429}äto je sa tvojom prijateljicom... Vinnie?
{30430}{30493}Oh, ne znam gdje mi je bila pamet.
{30900}{30933}Uzimaö li dovoljno vitamina, Harry?
{30934}{30996}Ovdje izgleda kao ljekarna.
{31792}{31865}Zdravo. Ovdje Harry Plummer|iz sobe 419, ponovo.
{31866}{31971}Postoji li moguÊnost da se preselim|u neku drugu sobu?
{31972}{32011}Baö niöta?
{32012}{32094}Postoji li moguÊnost da|prekinete ovu halabuku?
{32215}{32250}äto je?
{32251}{32283}Zar ne Ëujeö to?
{32284}{32317}Imaju maturalnu veËer.
{32318}{32369}Ne znam kako uopÊe moûeö spavati.
{32396}{32467}Cijeli ciklus mi je poremeÊen.
{32500}{32560}Princeza i zrno graöka.
{32591}{32678}Hej, ËovjeËe. Hej, narode.|Daj malo ohladite.
{32712}{32767}Ma daj, ËovjeËe.|Ljudi pokuöavaju spavati.
{32859}{32930}O, Hannah. Hannah?
{33008}{33047}Hannah?
{33084}{33130}Na Ëemu je?
{33131}{33178}NiËemu. Samo smo|malo popili öampanjca.
{33179}{33218}Ne seri mi.
{33219}{33274}Na acidu.
{33275}{33333}U redu je. Samo diöi.
{33334}{33375}Harry, miËi mi se s puta.
{33376}{33427}MiËi se.
{33428}{33462}Neka netko donese mokar ruËnik.
{33463}{33498}HoÊe li biti u redu?
{33499}{33533}Da. Samo donesi ruËnik.
{33534}{33586}Hajde, duöo.|Samo diöi.
{33587}{33630}Kad ga je uzela?
{33631}{33666}Prije nekih dva sata.
{33667}{33742}2 sata.|»ovjeËe, bit Êe u totalnoj komi.
{33743}{33773}Narode bolje je da odete.
{33774}{33826}Nema öanse. Da je ostavimo ovdje?
{33827}{33874}Pa niti ne znamo tko ste.
{33875}{33910}Ja prijateljica njene majke.
{33911}{33977}Moûeö misliti.
{33978}{34022}Da. Hannahine majke?
{34023}{34058}Zezate me?
{34059}{34130}Lavinia Kingsley, ljepotane.
{34131}{34168}Sada briöite.
{34215}{34287}Hajde. Idite!
{34288}{34323}U redu je.
{34324}{34390}Izgleda stvarno bolesno.
{34391}{34435}Njena majka je Vinnie?
{34471}{34506}Da.
{34647}{34696}Znam. Samo diöi.
{34729}{34788}OdliËno. To je u redu.
{34789}{34833}To je u redu.
{34834}{34904}O, ËovjeËe! Tako je. Neka ide.
{34905}{34947}Neka ide.
{34948}{34975}Samo neka ide duöo.
{34976}{35003}Samo neka ide.
{35004}{35036}O, evo ga joö jednom!
{35037}{35103}O, Harry.|Moûda nikad viöe neÊeö srati.
{35104}{35184}U redu.
{35185}{35224}Dobra djevojka.
{35359}{35398}Izvoli.
{35459}{35498}Sada je sve u redu.
{35499}{35562}Samo misli na lijepo plavo nebo.
{35669}{35720}Mama.
{35757}{35816}Odvest Êu te kuÊi.|Ne brini.
{35817}{35864}Samo se opusti.
{35865}{35924}Sada Êeö se bolje osjeÊati.
{36531}{36574}Hajde. Idemo.
{36615}{36661}Hajde. Idemo.
{36799}{36864}Ovuda,|u djeËje krilo.
{36865}{36896}äto?
{36897}{36928}DjeËje krilo.
{36929}{36964}Krilo?
{37164}{37205}Barkley.
{37268}{37291}Barkley.
{37292}{37387}Hannah. Pas...|Uhvati psa.
{37474}{37515}Jeste li se Ëuli sa mojom majkom?
{37516}{37584}Hej. To je izmeu tebe i tvoje majke.
{37614}{37694}Hajde, Barkley.|Ulazi.
{38364}{38399}Oprostite.
{38400}{38473}Oprostite.|Mogu li vam pomoÊi?
{38474}{38520}Hej, Vin.
{38586}{38642}Suzette?
{38643}{38678}Da.
{38679}{38781}O, moj Boûe.|Jesi li to stvarno ti?
{38782}{38817}Da.
{38818}{38881}Ustvari, ne. HoÊu reÊi,|ove cice nisu moje.
{38882}{38919}One su... One su laûne...
{38920}{38984}ali tu unutra negdje sam ja!
{39016}{39049}äto radiö tu?
{39050}{39101}Ja... Dovela sam Hannah.
{39102}{39127}Moju kÊer?
{39128}{39210}Da. U redu je.|U krevetu je.
{39255}{39290}Ne, nije.
{39291}{39349}Nije u krevetu.|Sada je njena maturalna veËer...
{39350}{39406}i trebala je provesti noÊ|kod Carol Bishop.
{39407}{39487}Ne, Vin.|U krevetu je. Pogledaj.
{39535}{39602}Zaöto je ti dovodiö kuÊi?
{39603}{39710}Zato jer su tulumarili u hotelu|u kojem sam odsjela...
{39711}{39826}i trebao joj je prijevoz|pa sam je dovezla.
{39827}{39866}To nema nikakvog smisla.
{39867}{39910}Neöto si izostavila...
{39911}{40006}Kao öto je sa Julesom,|njezinim pratiocem?
{40007}{40054}Ne znam. HoÊu reÊi,|oni su otiöli...
{40055}{40114}Pretpostavljam sa ostalim klincima.
{40115}{40154}Znaö öto. Stvarno me Ëiniö|nervoznom, Vin.
{40155}{40210}Mislim, ja sam samo, kao...|Izluujeö me, ËovjeËe.
{40211}{40322}Mislim, zar ti nije drago|öto me vidiö?
{40435}{40482}Suzette, öto hoÊeö?
{40483}{40514}Suzette, öto hoÊeö?
{40515}{40566}Tko je rekao da ûelim iöta?
{40567}{40670}Samo se pojaviö niotkuda|poslije 16 godina?
{40671}{40718}20.
{40719}{40762}Ili 20.
{40763}{40814}éeliö novac.
{40815}{40850}Tko ti je to rekao?
{40851}{40886}Pitam te.
{40887}{40922}Da li ûelim novac?
{40923}{40985}To je tako sjebano!
{41011}{41080}Mislim, to öto sam bila u Phoenixu|nema niöta sa tobom.
{41081}{41138}Govoriö li mi istinu?
{41139}{41190}Ne. Sranje.|OK, Vinnie. »ekaj.
{41191}{41237}Dobila sam nogu sa posla.
{41238}{41328}äto si rekla mojoj kÊeri?
{41329}{41387}Nabrojala sam sve tipove|sa kojima si se pukla.
{41388}{41426}To nije smijeöno, Suzette.
{41427}{41501}Nije imala pojma tko sam ja, Vinnie.
{41502}{41537}Naravno da ne.
{41538}{41577}Moj suprug, moja djeca,|moja zajednica...
{41578}{41662}Oni ne znaju niöta o tom razdoblju|kad smo ti i ja bile prijateljice.
{41663}{41789}Ljudi s kojima sam bila povezana tada|ukljuËujuÊi i tebe... oni...
{41790}{41849}oni...
{41850}{41930}viöe nisu dio moje|trenutne stvarnosti.
{41931}{41972}O, zajebi svoju trenutnu realnost.
{41973}{42030}Mislim, pogledaj se i svoje bazene...
{42031}{42072}i fontane. Ma daj, Vinnie.
{42073}{42118}Ne zovi me Vinnie.|Nitko me ne zove tako.
{42119}{42155}Moje ime je Lavinia.
{42156}{42185}Vinnie.
{42186}{42240}U redu.|Dat Êu ti 5000 $...
{42241}{42283}da nestaneö iz mog ûivota.
{42319}{42382}Nisam te doöla ugnjecati.
{42383}{42442}- Ugnjetavati.|- Kako god.
{42443}{42512}Tako si uötogljena.
{42546}{42596}Tako uötogljena.
{42627}{42685}Nisam uötogljena.
{42686}{42757}Samo sam dovela malu kuÊi|jer joj je trebao prijevoz.
{42758}{42813}A trebao joj je prijevoz.
{42814}{42896}Suzette, nisam nezahvalna.
{42897}{43005}Ali ta djevojka je na dekanovoj listi.|Ide na jesen u Vassar.
{43006}{43071}Ona je predsjedavajuÊa...|svoje generacije na maturi.
{43072}{43118}Kuûim.
{43153}{43188}Ne brini.
{43189}{43250}Nisam joj niöta rekla.
{43345}{43412}La-La-La-La-Lavinia.
{43593}{43644}Dole.
{43861}{43900}Hannah. Hannah, probudi se.
{43901}{43960}Moram razgovarati sa tobom.
{43989}{44024}Ginger!
{44025}{44104}Ovo te se ne tiËe. Van.|I zatvori vrata, molim te.
{44105}{44144}HoÊu spavati.
{44145}{44228}Imat Êeö dovoljno vremena|za spavanje polije ovoga.
{44229}{44343}Pitat Êu te neöto i ne prihvaÊam|niöta osim same istine.
{44385}{44456}Jesi li se drogirala na|maturalnoj sinoÊ?
{44457}{44496}O Ëemu priËaö?
{44497}{44532}Jesi li se drogirala?
{44533}{44572}Odgovori mi iskreno.
{44735}{44778}Popila sam vino.
{44811}{44922}Glupo sam pomijeöala crveno i bijelo|i od toga mi je pozlilo.
{44923}{44982}Saznala sam za to kad je bilo kasno.
{45027}{45074}I to je sve?
{45075}{45126}To je bilo dovoljno.
{45643}{45738}Ja sam gost Harryja Plummera.|Dao mi je svoj kljuË... 419.
{45739}{45802}G. Plummer je promijenio sobu.
{45803}{45878}Sada je u sobi 1007.
{45907}{45946}Hvala.
{46398}{46428}Harry?
{46454}{46533}OËistili su bljuvotinu,|ali sam se morao preseliti.
{46534}{46566}Naravno da si morao.
{46567}{46614}O, tako sam gladna.
{46615}{46651}Moram neöto pojesti.
{46652}{46687}Izvoli. HoÊeö jednu?
{46688}{46749}Trebala bi pojesti neöto konkretno.
{46750}{46801}NaruËit Êu doruËak.
{46802}{46837}Ne. Ne ostajem.
{46838}{46937}Samo Êu se presvuÊi i|onda odlazim.
{46938}{47027}O, pripremio sam ti kupku.
{47118}{47172}Ti si mi pripremio kupku?
{47202}{47275}Nisi ni znao kada Êu se vratiti.
{47276}{47342}Stalno sam dodavao toplu vodu.
{47528}{47597}Nisam u istom raspoloûenju|kao juËer, Harry.
{47598}{47633}Ne, ne, ne. Naravno.
{47634}{47729}Samo öto je bila pakleno duga noÊ.
{47860}{47927}Kada Êeö upucati svog oca?
{47956}{48004}NeÊu danas. Nedjelja je.
{48259}{48306}Harry?
{48307}{48354}äto je?
{48355}{48402}Ui.
{48403}{48438}Zar nisi gola?
{48439}{48522}Samo ui. éelim razgovarati.
{48588}{48615}Da?
{48616}{48668}Sjedni.
{48812}{48847}O, ËovjeËe.
{48848}{48930}Bila sam kao ruglo|u njenom slatkom malom svijetu.
{48931}{48998}Trebao si vidjeti to, Harry.
{48999}{49070}»ak i klinci imaju svoje krilo.
{49103}{49138}A tu je i Vin...
{49139}{49190}öepuri se okolo|kao princeza...
{49191}{49266}a bazeni su se punili.
{49267}{49330}Sredila je i nos.
{49331}{49378}Nisam joj niöta rekla, ali...
{49379}{49475}Ne znam ali definitivno to nije|bio njen nos, Harry.
{49531}{49628}»ovjeËe, ona je u zemlji iz snova.
{49629}{49756}A onda me je pogledala|kao da sam kakav duh iz proölosti.
{49757}{49840}Na smrt prestraöena kao da Êu|je raskrinkati.
{49927}{50025}Ponudila mi novac da nestanem, Harry.
{50107}{50154}Nisam ga uzela.
{50155}{50242}Ne bih ga takla ni|sa 10 metarskim ötapom.
{50289}{50336}Barem imaö svoj integritet.
{50457}{50553}Da. Integritet|i bez prebijene sam
{50595}{50643}Imam neöto...
{50644}{50670}HoÊeö li vode?
{50671}{50711}Ne, ne moraö, Harry.
{50712}{50764}U stvari, moûe malo vode.
{50816}{50866}Tko do vraga zna da sam ovdje?
{50867}{50938}Ne znam. Moûda hotel.
{51047}{51115}Javi se na telefon, Harry.
{51185}{51281}Da.
{51282}{51322}Uh, da.
{51401}{51515}Ne. Naravno. Doite gore.|Soba broj 1007.
{51516}{51562}Tko je to bio?
{51563}{51598}Lavinia.
{51599}{51638}äto?!
{51665}{51717}Rekla je da te mora vidjeti.
{51718}{51756}O, Boûe!
{51764}{51848}Poslije svega öto sam ti rekla|misliö da je ûelim ovdje?
{51849}{51884}Samo sam posluöao svoj|instinkt, Suzette.
{51885}{51986}Nisi posluöao svoj nego njen!|Ona manipulira ljudima!
{51987}{52060}Mrzim te, Harry!
{52317}{52349}Lavinia Kingsley.
{52350}{52385}Harry Plummer.
{52386}{52491}Suzette se upravo briöe...|Kupala se.
{52528}{52567}Ne ûelim prekidati...
{52568}{52603}iöta.
{52604}{52660}Ne, ne. Molim vas uite, go. Kingsley.
{52661}{52689}Hvala, g. Plummer.
{52690}{52725}Biti Êu samo 2 sekunde...
{52726}{52897}Bolje ti je da si se doöla ispriËati, jer si me tretirala kao|zadnji oloö i ako misliö da Êeö me oraspoloûiti, varaö se.
{52898}{52941}Popuöit Êu jednu, Harry. Istrpi.
{52942}{53021}Imaö pravo biti uvrijeena|i ja ti se ispriËavam.
{53022}{53073}Zato sam i doöla.
{53304}{53351}HoÊeö li mi se pridruûiti, na ruËku, sutra popodne?
{53436}{53500}I öto Êe se dogoditi na ruËku, Lavinia?
{53501}{53645}éeljela bih priliku da ti objasnim zaöto viöe|nisam osoba koja sam bila prije.
{53646}{53737}Kako sam se promijenila na bolje|i kuda mi ide ûivot.
{53738}{53860}Na primjer, jako sam aktivna u dobrotvornom radu Ëak je i|posaeno stablo, blizu gradske vijeÊnice, sa mojim imenom
{53861}{53892}na njemu ovdje u Phoenixu.
{53893}{54020}Phoenix je mitska priËa koja je ustala iz pepela|kao öto sam i ja postala sasvim druga osoba.
{54021}{54093}Htjela bih priliku da ti se predstavim.
{54094}{54129}Ljudi se zaista mijenjaju, Suzette.
{54130}{54336}Nije da mi je bilo lako, ali viöe nisam mogla biti osoba|koja sam bila jer ta osoba nije ono öto sam ja.
{54337}{54465}Vinnie, stani, jer si se poËela uvlaËiti sama|sebi u öupak, a meni se ne ide za tobom.
{54466}{54513}Ja sam je shvatio.
{54514}{54561}Baö vam hvala.
{54562}{54603}Harry, dosta.
{54604}{54659}Vinnie, ja se ne sramim svoje proölosti.
{54660}{54765}Ja se barem ne öepurim u nekom Lane Robu i papuËama|i pretvaram da se niöta nije dogodilo.
{54766}{54807}Moj muû je advokat!
{54808}{54857}O, zbilja? äto Êeö me tuûiti?
{54858}{54901}Dozvoli mi da zavröim, molim te.
{54902}{54951}On teûi karijeri u politici.
{54952}{55040}Prva dama drûave Êe biti "Sestra KresaËica".
{55041}{55065}Ja nisam "Sestra KresaËica".
{55066}{55147}Sluöaj. Ja sam majka i to vrlo dobra.
{55148}{55228}Hannah mi je sve rekla öto se dogodilo|na maturalnoj veËeri.
{55229}{55329}Rekla mi je da je pila crveno i bijelo vino|i da joj je od te kombinacije pozlilo.
{55330}{55429}Pozlilo? Bila je totalno u komi, go. Kingsley.|Zar ne, Suzette?
{55430}{55520}O, nije tako, Harry. Ona bi rekla svojoj|majci sve.
{55521}{55605}Dakle, kada je ruËak?
{55606}{55652}Molim?
{55653}{55727}RuËat Êemo.|Sama si rekla.
{55728}{55868}Da, ali sam rekla sve öto sam planirala|reÊi za vrijeme ruËka.
{55869}{56004}Znaö, odakle ja dolazim, Lavinia koje je vukojebina|u West Hollywoodu.
{56005}{56186}Ljudi mogu priËati o sebi do beskraja,|ali imaju toliko pristojnosti da pitaju:
{56187}{56259}"Dakle, öto ima novog kod tebe?"
{56260}{56299}Podne, u predvorju?
{56300}{56437}Suzette, ja nisam samougaajuÊa.|Moûda sam puno toga, ali to nisam.
{56438}{56516}A zaöto joö uvijek priËaö o sebi?
{56541}{56612}Usput reËeno, kako si|znala u kojoj sam sobi?
{56613}{56683}Opisala sam te portiru.
{56713}{56792}"Opisala sam te portiru."
{56793}{56907}Moram je napiti i pokrenuti njen mojo, ËovjeËe.
{56908}{56979}Ali se prvo moram naspavati.|Tako sam umorna.
{56980}{57035}O, da. Ovo je dobro.
{57337}{57375}Harry?
{57413}{57520}äto ti je napravio, tvoj otac,|da ga toliko voliö?
{57568}{57630}Pa nekako me je prokleo.
{57675}{57714}Kako je to uspio?
{57745}{57848}Imali smo obiteljski posao,|prodaja namjeötaja. Mrzio sam ga.
{57849}{57932}Htio sam biti pisac.|On je to mrzio.
{57933}{57968}"Samo naprijed," rekao je.
{57969}{58052}"Sve öto takneö pretvorit|Êe se u sranje.
{58053}{58152}Jednog dana Êeö pogledati öto si postigao|i neÊeö imati öto vidjeti."
{58153}{58210}Pa, ipak si otiöao, zar ne?
{58211}{58248}To mi se svia.
{58281}{58344}I onda si zbrisao u Hollywood?
{58345}{58383}Da.
{58413}{58528}Bilo je super. Cijeli svijet|je htio dio mene.
{58529}{58668}Znaö, tada je svatko skakao|u krevet sa svakim.
{58669}{58732}Imao sam Dodge Duster.
{58733}{58832}Svakog petka na veËer|jeo sam kod Joe Allena.
{58833}{58888}Boûe, bilo je fantastiËno.
{58889}{58941}HoÊeö reÊi da si vozio?
{59007}{59087}Zlatnog Dodge Dustera|sa bijelim vinilnim sjedalima.
{59165}{59217}Jesi li imao curu?
{59251}{59290}Da.
{59291}{59333}äto se dogodilo?
{59363}{59446}Sve se raspalo baö kao|öto je on i rekao.
{59447}{59550}Ma daj. Dajeö starom previöe zasluga.
{59551}{59598}Ne prodajeö namjeötaj.
{59599}{59654}Da li on joö to radi?
{59655}{59694}Ne.
{59727}{59882}On je... On je u jednom mjestu|koje se zove Horizon Hills.
{59883}{59949}To je staraËki dom.
{60263}{60304}Ne miËi se.
{60355}{60488}Moûeö raditi öto god hoÊeö|ali ti nije dozvoljeno da razmiöljaö.
{60701}{60756}Razmiöljaö, Harry.
{60801}{60834}Prestraöen sam.
{60835}{60868}Umukni.
{60869}{60903}OK.
{61331}{61408}Dobro jutro, g. Plummer.
{61409}{61477}Imaö dvije stvari koje ti idu na ruku.
{61478}{61556}Prvo je da sam dobre volje,|a drugo je da si sladak.
{61613}{61648}O, Suzette.
{61649}{61697}Doöla sam se osobno ispriËati.
{61698}{61738}Potpuno sam zaboravila na Ginger.
{61739}{61768}Danas polaûe vozaËki.
{61769}{61807}- Ginger?|- Moja 16-godiönja kÊer.
{61808}{61843}Ne mogu ti opisati koliko je ovo vaûno.
{61844}{61880}Moram odgoditi ruËak. Izvini.
{61881}{61906}Ovo je za tebe.
{61907}{61936}Je li se ti to pokuöavaö izvuÊi iz ovoga?
{61937}{62035}No! Ovo je jedan od onih obreda prolaza.|Moram biti tamo.
{62036}{62087}U redu. Idem sa tobom.
{62128}{62188}Mama, öto radiö?
{62189}{62231}Niöta.
{62232}{62280}Tko je to?
{62281}{62337}Suzette, moja prijateljica.
{62338}{62399}Tvoja prijateljica?
{62400}{62475}U redu. Samo idi u auto.|Dolazim za minutu.
{62476}{62516}E, neÊeö me nogirati.
{62517}{62589}Dogovorile smo se|i ja sam se sva sredila.
{62664}{62759}OK. Samo da se organiziram.
{62760}{62887}Oprostite. Moûete li odnijeti ovo u sobu 1007?|I nemojte ih zalijevati.
{62888}{62991}Nije im potrebno zalijevanje. VeÊ je zaliveno,|pa im ne treba zalijevanje.
{62992}{63023}Hajde. Idemo.
{63024}{63091}Ne zalijevajte ih. Molim vas.
{63092}{63156}OK. U sluËaju da primijetiö...
{63157}{63189}ima jedna mala sitnica.|Vjerojatno neÊeö primijetiti.
{63190}{63236}Ginger ima naviku...
{63237}{63353}Ponekad stvara tihe zvukove u dnu grla|i specijalist je rekao da to nije niöta.
{63354}{63424}Vjerojatno Êe se samo rijeöiti s vremenom.
{63425}{63449}- OdliËno.|- Da.
{63450}{63477}Naöa politika je...
{63478}{63523}Ona je... Samo Êe to ignorirati.
{63560}{63619}Udahni, Gin.
{63620}{63707}Htjela sam se tetovirati, mama,|ali si mi rekla da ne smijem.
{63708}{63763}Ostani u svojoj traci, duöo.
{63764}{63803}Da li joj je jezik probuöen?
{63804}{63920}Draga, nije lijepo priËati o ljudima|pred njima kao da ih nema.
{63921}{63956}Poznajem jednu koja ima probuöenu usminu.
{63957}{64004}U redu, koncentriraj se na voûnju, Gin.
{64005}{64040}Bolje da me ne dopadne tip|koji je bio Jennifer.
{64041}{64072}Sruöio je zbog govorenja.
{64073}{64149}U redu. Onda nemoj govoriti. Samo vozi.|Tako se dogaaju nesreÊe.
{64150}{64189}Zbog razgovora?|Ne bih baö rekla mama.
{64190}{64221}Ostani u svojoj traci.
{64222}{64260}Na koju traku misliö?
{64261}{64289}Na onu u kojoj si!
{64290}{64325}Pa ako sam u njoj u Ëemu je problem?
{64326}{64357}Gledaj gdje voziö!
{64478}{64573}Uvijek je bilo teûe sa Ginger nego|sa Hannahom, jer je ona
{64574}{64669}orijentirana na rjeöenja, dok je Ginger|viöe umjetniËki orijentirana öto je
{64670}{64796}ono öto volim kod nje i|ohrabrujem, ali je malo prkosna.
{64797}{64880}- Nisi joj valjda dala ime po Ginger Baker?|- Ne.
{64881}{64960}Dok sam bila trudna ûudila sam za|umbirom pa sam ga jela svaki dan.
{64961}{64994}Mnogo bolje.
{64995}{65066}- Isuse. Koliko je sati?|- Ne znam.
{65067}{65094}Naravno da ne znaö.
{65095}{65138}O, Boûe, nadam se da Êe proÊi ovaj put.
{65139}{65210}To Êe biti tako dobro za njeno samopouzdanje.
{65211}{65258}Znaö onog tipa Harryja,|onog kojeg si upoznala?
{65259}{65378}On ne vozi. Sada bi mogao jer|smo se sinoÊ seksali.
{65379}{65444}To mu je bilo prvi put nakon 10 godina.
{65445}{65496}Nekako mi se dopalo, znaö.
{65497}{65540}OsjeÊala sam se kao da sam neöto postigla.
{65541}{65628}Hej, kad je svröio, bilo je|kao da je na elektriËnoj sjedalici.
{65629}{65704}Mislila sama da ste vas dvoje u vezi.
{65705}{65852}Ne, ne. Pokupila sam ga negdje u Blytheu|i mogu ti reÊi da nije bio loö.
{65853}{65908}Ima nade za Harryja.
{65909}{65960}Nada za Harryja.
{66017}{66048}Mrzim ovo mjesto.
{66049}{66104}Kuûim te. Moûeö li se zamisliti da ovdje radiö?
{66133}{66286}Bez boja. Poludila bi. Moraju biti ûive boje|oko mene ili bi pukla. Mrzim prljave boje.
{66287}{66390}Gledala si u moju odjeÊu kad si to rekla.
{66391}{66450}- Nisam|- O, da. Jesi.
{66451}{66506}- Ne, nisam.|- Jesi, gledala si.
{66507}{66538}Ubila bih za tu, a...
{66539}{66570}- Da.|- Bi.
{66571}{66662}Ma da, Suzette.|Gotov iste boje je kao i ... zidovi.
{66663}{66758}- Ma daj. Nije.|- Jeste.
{66759}{66956}Ja sam iste boje kao i odjel za motorna|vozila, a ti... izgledaö kao cvijet.
{67008}{67095}- Zaöto si tako ljuta?|- Nisam.
{67096}{67171}Mislim, svi tipovi ovdje|bulje u tebe.
{67172}{67207}To je i bit, zar ne?
{67240}{67272}Kakva bit?
{67273}{67426}Pa, ako se skockaö kao si se ti skockala|to je oËigledan pokuöaj privlaËenja paûnje.
{67427}{67457}Ne izgledam uopÊe drugaËije.
{67458}{67600}O, molim te. Imala si puno manje grudi.
{67601}{67649}HoÊeö reÊi da ti moje cice smetaju.
{67650}{67729}Ma daj. Ovaj stroj me smeta jer ne funkcionira.
{67730}{67849}Znaö öto? Mislim da te ljuti jer si|nekad ti imala bombe.
{67850}{67912}- Ma, molim te.|- Istina je.
{67913}{68081}I znaö öto? Prije si voljela pokazivati i bile su|poznate, te cice, a ja sam bila ravna kao daska.
{68082}{68168}Pa sam ih, znaö, napravila veÊim.
{68217}{68268}Ako Êeö se osjeÊati bolje...
{68269}{68321}Ne osjeÊam se loöe. Nije mi|potrebno da se osjeÊam bolje.
{68322}{68405}Malo su prevelike, i znaö öto...|Pretjerala sam.
{68406}{68481}Pa, nisam htjela niöta reÊi,|ali prevelike su.
{68482}{68541}Da. Otiöla sam iz jedne krajnosti u drugu.
{68573}{68628}Mama, sruöio me bez razloga!
{68629}{68660}Gin, öto se dogodilo?
{68661}{68772}Niöta! Vozila sam kao svaka normalna osoba,|ali me on odluËio gaziti.
{68773}{68832}Piöe da si proöla kroz crveno.
{68833}{68908}Da. Moûeö misliti! Kao da bih to napravila na testu!
{68909}{69032}Oh! A svima sam rekla da polaûe|ovu glupost i obeÊala sam Jennifer
{69033}{69096}da Êu je odvesti u Pickle Pan!
{69097}{69135}Znaö öto? Ja Êu...
{69168}{69219}Odvest Êu je ravno kuÊi.
{69220}{69255}Ponaöala se prema tebi kao prema psu.
{69256}{69291}Pa, jako je uzbuena!
{69292}{69327}Odbacit Êu te do hotela.
{69328}{69371}Ne, Ëekaj malo.|Ovo nije...
{69372}{69407}Ovo je velika stvar...
{69408}{69439}Mi se Ëak niti ne slaûemo.
{69612}{69651}Netko je ostavio Barkley vani.
{69652}{69739}Barkley! Barkley!|Doi ovamo.
{69740}{69777}Barkley! Gin.
{69778}{69836}Ginger, uvedi Barkleya.
{69837}{69959}- Ne mogu mama, previöe sam depresivna.|-Hej, dovedi psa.
{69960}{70042}Hajde, Barkley, glupane jedan.
{70077}{70160}Hannah! Ostavila si otvorena vrata!|Pas je izaöao vani!
{70197}{70247}Hannah, ugasi glazbu!
{70421}{70447}Hannah?!
{70480}{70527}Hannah!
{70528}{70588}Razlaz. Hajde. Razlaz!
{70657}{70687}Mama!
{70688}{70785}Hajde, Hannah.|Izlazi iz bazena.
{70786}{70845}Hannah, stani!
{70884}{70940}-Niöta nije bilo, kunem ti se.|-Moûeö misliti.
{70941}{71014}-Imam skoro 18 godina!|-Ne zanima me koliko imaö godina, Hannah.
{71015}{71108}Joö uvijek ûiviö u mojoj kuÊi, voziö|auto koje smo mi kupili,
{71109}{71200}platili smo za tvoj fakultet i dok|god je tako poötivat Êeö naöa pravila!
{71201}{71320}Jesi li me razumjela? Sada izlazi odatle,|obuci se i ugasi tu glazbu!
{71321}{71408}- A ni ti niöta ne pomaûeö.|- äto sam sad je napravila?
{71409}{71508}Pa stojiö tu i izgledaö kao da sve to odobravaö.
{71509}{71575}Ali rekla si da izgledam kao cvijet.
{71576}{71707}- Mama, nagazila sam na puûa!|- Ovdje nema puûeva, Gin.
{71708}{71760}A öto je ovo öto puûe i öto sam upravo ubila?
{71761}{71856}Jules! Poznajem te joö dok si|bio u vrtiÊu, mladiÊu.
{71857}{71954}Ovo nije kako se ja inaËe ponaöam, go. Kingsley.
{72490}{72623}Hannah, ne misliö li da su se|samo goli kupali?
{72624}{72727}- Ne. Navalili su jedan na drugoga.|- U bazenu gdje se mi, kao obitelj, kupamo?
{72728}{72803}- Da.|- O, Boûe.
{72804}{72885}Misliö li moûda da su se samo|trljali jedan uz drugoga?
{72886}{72915}Ne, jebali su se.
{72916}{73005}O, Boûe. Hannah je predstavnica svoje klase|i taj momak Jules...
{73006}{73072}Dobio je nagradu za druötveni rad.
{73073}{73129}On je mali prevarant, eto öto je.
{73130}{73157}Zaöto to govoriö?
{73158}{73241}Zato öto to on je. Prepoznajem ja to.|Mogu ja to nanjuöiti.
{73242}{73349}Ne znam öto bih sada trebala napraviti.|Da li misliö da bih trebala nazvati njegove roditelje?
{73350}{73384}Mene pitaö?
{73450}{73552}- Zaöto bacaö te limune?|- Limuni eliminiraju smrad.
{73553}{73644}Boûe. Potpuno si prolupala oko ovoga.
{73645}{73728}- Jesam.|- äkola je gotova, a oni su maturanti,
{73729}{73818}pa su se vratili i popili par piva,|i onda se skinuli i skoËili u bazen.
{73819}{73865}Samo su se zabavljali.
{73866}{73940}Oni su djeca!
{73941}{74019}éelim ti neöto pokazati.
{74045}{74080}- Doi.|- äto je?
{74081}{74188}Osvjeûi pamÊenje.|Pogledaj ovo.
{74189}{74283}- Ovo nisu djeca?|- O, moj Boûe.
{74284}{74360}SjeÊaö se da smo sjedili tamo iznad|Sunset Boulevarda i Ëekali da izae sunce?
{74361}{74392}Dok nas murjaci nisu potjerali.
{74393}{74456}- Izlazak sunca iznad Sunseta.|- Prei na poantu.
{74457}{74548}Pa to je bila tvoja ideja da se popnemo.|A znaö li zaöto?
{74549}{74580}- Ne.|- ToËno.
{74581}{74656}Samo smo radili svakakva sranja|bez razloga, Vin.
{74686}{74757}Boûe. To je Raymond.|Moj muû.
{74758}{74821}äto Êeö sada sa mnom?|Da se sakrijem u ormar?
{74822}{74890}Ne. On zna za tebe. Samo mu nisam|rekla baö pravu istinu.
{74891}{74949}äto si mu rekla?|- Rekla sam mu da smo bile skupa na fakultetu.
{74950}{75013}- Bila sam na fakultetu?|- Da.
{75014}{75144}- Loöa sam laûljivica, Vinnie.|- U redu. Govori öto manje istinu.
{75145}{75196}- Bok, duöo.|- Bok.
{75197}{75316}- Oprostite.|- Ovo je Suzette.
{75317}{75340}- Suzette?|- Bile smo cimerice u Los Angelesu.
{75393}{75451}O, Suzette. Da, naravno. Suzette.
{75457}{75603}- Zdravo. Iöla si na UCLA?|- Tamo sam vidjela "Country Joea i Ribu".
{75724}{75868}Ostani na veËeri, Suzette.|Lavinia i meni bi bila Ëast da ostaneö.
{75869}{75940}- Molim te. Ostani na veËeri.|- Naravno.
{76009}{76047}Superiöka.
{76179}{76254}- Ostajem na veËeri.|- Da.
{76516}{76650}- Je li mamina prijateljica za ozbiljno?|- Ne znam. Nije me briga.
{76750}{76876}Izlazi iz moje sobe, u redu? Sve öto radiö|je da jedeö a tako si mröava.
{76877}{76912}äto tebe muËi?
{76956}{77162}- Mama me uhvatila u bazenu sa Julesom.|- Pa?
{77201}{77272}Nismo plivali.
{77309}{77384}- Vlastita mama?|- äuti. Bilo je uûasno.
{77385}{77468}Samo je tamo stajala i natjerala nas|da izaemo iz bazena.
{77469}{77579}Bilo je tako poniûavajuÊe. To je najgora|stvar koja mi se ikad dogodila.
{77580}{77619}Pala sam na vozaËkom.
{77620}{77731}Tebi je dozvoljeno da padneö. Meni nije.|Ja niti ne znam kako to izgleda.
{77732}{77849}Pogledaj me. Pogledaj. Ja sam na|svakoj stranici godiönjaka.
{77948}{78079}A sutra moram stati ispred|cijele ökole i reÊi neöto profinjeno
{78080}{78219}tako da mogu svi maturanti otrËati|u svoju buduÊnost i ûivjeti zauvijek sretni.
{78220}{78267}Koja laû.
{78268}{78355}Voljela bih da mogu tamo stati i prdnuti pred svima.
{78370}{78439}- Zaöto to i ne napraviö?|- Da, moûeö misliti.
{78440}{78603}Svi moji uËitelji, ravnatelj ökole, tata, mama...|posebno mama.
{78604}{78679}Moûeö li zamisliti njenu reakciju?
{78753}{78832}Barem ne bi bilo dosadno.
{78949}{79084}"Uspjeh iÊi iz neuspjeha u neuspjeh|bez gubitka entuzijazma."
{79085}{79132}Winston Churchill.
{79133}{79235}Ali öto ako osoba koja te testira|toliko smrdi da se ne moûeö koncentrirati?
{79236}{79295}Crveno svjetlo znaËi da moraö stati, Ginger.
{79296}{79389}Nova tema. Hannah...|kako ti ide govor?
{79390}{79488}- Razmiöljam da napravim neöto nekonvencionalno.|- Pa to je uvijek dobra ideja.
{79489}{79595}Da je uvijek dobra ideja|onda ne bi bilo nekonvencionalno.
{79596}{79712}Bit Êeö dobro. Dobro izgledaö.|Dobila si malo boje u licu.
{79713}{79773}Jesi li se danas sunËala?
{79774}{79817}Da, Hannah.
{79914}{79949}Ginger, Ginger.
{79950}{80041}- Opusti grlo kad jedeö.|- Da, Ginger.
{80093}{80121}Suzette?
{80165}{80204}Poznavala si moju ûenu prije mene...
{80205}{80273}ToËnije, prije sviju nas.
{80274}{80353}Je li se puno promijenila u sve ove godine?
{80394}{80443}Vidim istu osobu.
{80474}{80635}- äto vas dvije imate zajedniËkog?|- äto imamo zajedniËkog, Vin?
{80675}{80775}Pa, povremeno smo iöle na koncerte.
{80840}{80961}- Kakve koncerte?|- Rock.
{80962}{81017}Ali su trebali biti stvarno rock.|Zar ne, babe?
{81042}{81104}Babe?
{81105}{81151}Imale smo vrlo visoke standarde.
{81152}{81200}»ekaj. Kao grupa?
{81201}{81265}Ha ha!|Mama u guûvi.
{81326}{81459}Stoji tamo stiskajuÊi svoju torbicu.|Sa svojom savröenom frizurom.
{81485}{81554}"Ajmo svi! Idemo!|Kasno je!"
{81625}{81698}Teöko nam je to zamisliti, Lavinia.
{81699}{81747}Vinnie... Vin.
{81748}{81796}Da, babe.
{81797}{81896}Plesala je. To je radila. Plesala.
{81897}{81935}Naöa mama?
{81990}{82100}Naöa mama je jako, jako, jako loöa plesaËica.
{82101}{82192}E pa to je ono öto bilo jako,|jako dobro u svemu tome.
{82193}{82280}Nije te bilo briga öto su drugi|mislili, zar ne, babe?
{82408}{82453}Lavinia?
{82559}{82594}Lavinia?
{82743}{82845}Zna li tko öto predstavlja Suzettina tetovaûa?
{82874}{82920}Nemoj niöta reÊi, Suzette.
{82930}{83020}To je guöter sa krunom na glavi. Zna li tko?
{83061}{83133}Nemam pojma.
{83134}{83177}Jim Morrison.
{83178}{83229}"Ja sam Kralj Guötera".
{83230}{83394}Takoer je sebe zvao "Mr. Mojo Risin'"|öto su bila slova njegova imena samo pomijeöana.
{83395}{83642}To je napisao u Meksiku nakon öto je bio budan|cijelu noÊ poslije penjanja po piramidi sunca.
{83685}{83738}Mama, ti si otkaËila!
{83739}{83821}Da. Ponaöaö se kao neka|posve drugaËija osoba.
{83882}{83953}Baö se Ëudno ponaöaö, Lavinia.
{83954}{84073}Nema te vi pojma koliko Ëudna mogu biti.
{84139}{84221}- äto je to bilo, do vraga?|- PileÊa prsa.
{85007}{85034}Suzette?
{85035}{85156}Zapela sam u predgrau, Harry.|Imam priliku vidjeti kako ûivi druga strana.
{85157}{85260}Ne znam. Stvarno je uvrnuto.|Komplicirano je biti u svom ovom sranju.
{85261}{85339}Pa napredovala si od juËer.|JuËer te nije htjela ni vidjeti.
{85340}{85373}To odliËno. To je fantastiËno.
{85374}{85461}Ne znam baö. Kako tebi ide?|ZvuËiö nekako ubrzano.
{85462}{85539}- Piöem kao lud.|- Da? äto piöeö?
{85540}{85653}Ne znam. Sve. RijeËi, misli, slike.|Kao da je sve eksplodiralo iz mene.
{85654}{85739}- OsjeÊam se uzavrelo.|- Uzavrelo?
{85764}{85868}- Krenulo te, Harry. To je to.|- To je viöe od toga, Suzette.
{85869}{85917}To je... to je...
{85970}{86049}- Mislim da si ti moja muza.|- Uh, Harry, Ëekaj malo.
{86050}{86113}Ja sam samo maËka koju si upoznao u pustinji.
{86114}{86151}Da, toËno. I da ja...
{86152}{86245}Ja... Ne bih te upoznao u pustinji da si|nisam sjebao ûivot tako dobro.
{86246}{86288}Gdje ovaj razgovor vodi?
{86289}{86389}Da sam napravio samo jednu stvar drugaËije,|da mi je uspjela samo jedna stvar
{86390}{86503}moj cijeli ûivot bi krenuo u nekom drugom pravcu.|Ovako, sve mi je krenulo krivo i dovelo do tebe.
{86504}{86661}- Hej, ne ûuri toliko.|- Onda ne bih trebao osjeÊati niöta prema tebi?
{86662}{86813}Ne, ne. Moûeö osjeÊati öto kod hoÊeö|ali nemoj od svega praviti predstavu u tri Ëina.
{86784}{86850}- Kada se vraËaö kuÊi?|- KuÊi?
{86851}{87026}- HoÊu reÊi nazad, ma znaö, u hotel.|- Hm. Harry sluöaj, napiöi öto god hoÊeö, u redu.
{87027}{87171}Samo iskopaj iz sebe, duöo,|zato öto je sve tamo. Sve je u tebi.
{87172}{87252}A sada navali.|Vidimo se kasnije.
{88017}{88071}Da li naöa mama ima tajni ûivot?
{88072}{88186}Dozvolite mi da vam neöto kaûem o vaöoj majci.|Ne bi vas ubilo da budete malo bolji prema njoj.
{88187}{88270}Kako to da ona sve zna|o Van Morrisonu odjednom?
{88271}{88341}Jim Morrison, ne Van Morrison. Isuse.
{88342}{88443}OK, Jim Morrison. Govorila je o njemu|kao da ga je poznavala ili neöto tako.
{88444}{88510}- Operite sue.|- Sue? Rosa ih pere.
{88511}{88572}- Koja Rosa?|- Ne znam.
{88573}{88647}Imate ljude koji vam briöu guzicu, a vi|ne znate niti njihova imena.
{88648}{88731}- Hannah, jesi li Ëula to?!|- Samo operite sue, u redu? Ti peri,
{88732}{88807}a ti briöi. Evo vam spuûva.|I nema koriötenja perilice sua.
{88808}{88876}- Zaöto?|- Zato öto ste pokvarena deriöta.
{88877}{88905}Ne, nismo.
{88906}{88981}Pogledajte sva ova sranja koja imate.|Pogledaj. äto je ovo?
{88982}{89074}- Mreûica za banane.|- Super. Imate mreûicu za svoje banane.
{89075}{89148}Mislim, nema ih baö svatko.
{89149}{89257}Ne trebaju nam tvoja predavanja.|»ak nas niti ne poznajeö.
{89352}{89431}Ti i ja se odavno poznajemo|mala Miss Kraljica Maturalne veËeri.
{89432}{89590}Mi ûelimo da znamo o naöoj majci.|Bila je dinamit.
{89591}{89657}Bila je luda prijateljica.
{89658}{89731}»ekaj. äto to znaËi?|äto je radila?
{89732}{89849}Je li puöila travu? Je li se opijala|i svugdje povraÊala i seksala se?
{89850}{89896}Je li ikad iöta napravilo krivo?
{89952}{89989}Gdje vam je otac?
{89990}{90068}Tamo gdje ja viöe nikad neÊu iÊi.
{91056}{91094}äto to radiö?
{91136}{91403}éelim izaÊi van... bez mog sata, ali sve|öto posjedujem je beû boje.
{91968}{92036}Hajde, Vinnie. Idemo. äto ti toliko treba?
{92086}{92113}Harry?
{92146}{92193}Priveûi me, hoÊeö li?
{92194}{92249}Vin, öto tamo viöe radiö?
{92250}{92385}Suzette, izgledaö tako...|prelivajuÊe.
{92386}{92421}Hvala.
{92422}{92502}- HoÊete li biti do kasno?|- Definitivno.
{92532}{92588}Spremna ili ne, dolazim!
{92687}{92725}O, moj Boûe!
{92818}{92862}Tvoja kosa.
{92930}{92953}Da?
{92954}{92996}- O...|- Dakle?
{92997}{93095}Jebeno je dobra, ËovjeËe.|- Da?
{93096}{93141}Da, da.
{93142}{93217}Harry, doi i reci mi öto misliö?
{93338}{93432}- Trebalo je hrabrosti.|- Spremna? - Idemo.
{93433}{93455}Tooo!
{93456}{93490}Uzmi torbice.
{93491}{93562}- O, bok.|- Bok.
{93563}{93591}Ostani briljantan.
{93592}{93626}Reci laku noÊ, Harry.
{93627}{93687}Laku noÊ, Harry. Aah!|O, Boûe. Prepalo me je.
{94082}{94125}äto je?
{94126}{94214}Zaboravila sam koliko je to buËno i glasno|i prljavo i znojno i... to je... ja...
{94215}{94251}Vinnie, hajde. Hajde.
{94252}{94339}- U redu, daj mi sekundu. Samo minutu.|- OK, u redu, u redu.
{94340}{94414}- Tvoja minuta je istekao. Idemo, idemo.|- O, Suze, Suze.
{94415}{94491}Hajde, progurajmo se.|äto Êeö piti?
{94492}{94557}- Moûe kava?|- Vinnie! Ma daj.
{94558}{94669}- Daj mi neöto , malo ûestoko.|- Dobit Êeö ga duöo, dobit Êeö.
{94670}{94730}Oprostite. Izvinite.
{94731}{94764}O, straöno mi je ûao.
{94765}{94863}Moja greöka. O, Boûe.|Suzzete, samo se sudaram sa ljudima.
{94915}{94970}éao mi je. Straöno mi je ûao.|Suzette! Suzette!
{94971}{95011}Da! Ovdje sam, duöo.
{95012}{95053}Hajde, hajde.
{95054}{95098}Nabavila sam nam mjesta.
{95099}{95231}- Joö uvijek se dobro snalaziö u barovima.|- Pa, na mom si terenu, duöo.
{95232}{95321}I öto Êemo sada?
{95322}{95359}- Rum i Cola i tiki.|- äto god ûeliö!
{95360}{95437}äto god ûeliö!
{95438}{95519}äto kaûeö na barmenovu guzu?
{95552}{95579}Vratila se.
{95580}{95626}Malo podsjeÊa na Rod Stewarta. Malo.
{95627}{95710}Stvarno liËi na Rod Stewarta.|Pogledaj njegovu malu Rod Stewart guzu.
{95711}{95771}Ne tako glasno. »ut Êe nas.
{95772}{95806}U redu
{95807}{95906}Oprostite. Da li biste htjeli plesati?
{95907}{96099}O... to je tako lijepo od tebe, ali ne. Udana sam.|Imam djecu, kuÊu, i psa, u stvari zlatnog retrivera.
{96100}{96167}Baö je lijepo od tebe öto si me pozvao.|Hvala ti puno.
{96168}{96229}Bilo je to lijepo od njega, zar ne?
{96302}{96337}U redu, vrijeme je.
{96338}{96368}- Za öto?|- Idemo plesati.
{96369}{96440}- Mislim da ne bih.|- Spusti svoju torbicu.
{96441}{96498}- Ne, ne mogu.|- Duöo. - Ne joö.
{96499}{96560}- Vinnie, hajde, duöo. Pusti je.|- Ne.
{96561}{96629}- Molim te, duöo. Pusti svoju torbicu.|- Ne mogu. Ne mogu.
{96630}{96735}U redu, popij. Do kraja. U redu?|Hej, Rod, pripazi...
{96736}{96816}- Pripazi na naöe stvari, moûe? Idemo plesati.|- Nema problema.
{96847}{96990}Mislim da nije pravi tempo za mene.|Samo malo nije. Malo prebrzo.
{96991}{97045}Hajde, duöo. Opusti se.
{101343}{101405}Koja ludnica, ha?
{101406}{101472}äto to gledaö, duöo?
{101668}{101756}Pogledaj sve te zvijezde.
{101757}{101822}Koliko ima znaö imena, Vin?
{101856}{101888}Nula.
{101960}{102044}- Jesi li bila u Europi, Vinnie?|- O, da.
{102074}{102152}Jesi li bila u Parizu u Francuskoj?
{102184}{102295}Jesi li bila na ono velikom, poznatom|groblju gdje je Jim pokopan?
{102296}{102342}Pere-Lachaise.
{102404}{102447}I kakvo je?
{102573}{102604}Tuûno.
{102756}{102791}Da.
{103814}{103878}- Zatvori vrata.|- U redu.
{103879}{104002}éelim ti reÊi, tek toliko da se zna,|da ih ni sama nisam vidjela 20 godina.
{104003}{104074}- äto?|- Vidjet Êeö.
{104075}{104132}Samo tamo upali svijeÊu.
{104227}{104298}Stvarno ne znaö öto Êu ti pokazati?
{104335}{104386}äto je? Stvarno ne znam.
{104387}{104470}Bit Êe ti pravo iznenaenje.|Niti ne nasluÊujeö?
{104471}{104502}Ne!
{104503}{104539}Da vidimo.
{104540}{104585}- Jesi spremna?|- Da.
{104651}{104694}To je...
{104695}{104742}Kolekcija kuraca rock zvijezda.
{104743}{104814}O, moj Boûe. Rekla si da si ih bacila.
{104815}{104850}Rekla si da je to povijest..
{104851}{104886}- Ne, nisam.|- Da, jesi.
{104887}{104958}Rekla sam da je to povijest, ali to nije isto|kao i da ih bacim.
{104959}{104992}- Priznaj da si lagala.|- Lagala sam.
{105005}{105044}Zatvori oËi. Imena su na poleini.
{105045}{105081}Nervozna sam, Vin.
{105082}{105165}Pogodi Ëiji je prvi kurac.
{105369}{105402}Roger...
{105457}{105492}Waters.
{105493}{105524}Jimmy Page.
{105525}{105564}Daj mi to. Zezaö me?
{105565}{105604}A ovaj je... Jimmy?
{105605}{105633}Vrlo ûilav i... Ooh!
{105634}{105662}"Arlo Guthrie."
{105663}{105748}O, ne. Taj je tvoj babe.|Tog uzmi. Pogledaj ovo.
{105749}{105777}- äto je?
{105778}{105806}Keith! To je Keith.
{105807}{105840}A ovaj je...
{105841}{105884}Uzela sam ga, zato öto sam ga pogladila.
{105885}{105913}O, Boûe.
{105914}{105953}Ovaj je... »ak niti ne znam. Boûe.
{105954}{106023}Gdje? »ekaj malo, Ëekaj, Ëekaj.|Ne, ne, ne, ne.
{106024}{106097}- Popuöit Êu ga.|- NeÊeö to napraviti.
{106098}{106175}- Da, da. HoÊu.|- Ma daj, duöo. To Êe biti...
{106176}{106223}Tako je star. Koliko je star?
{106224}{106277}Pa, vjerojatno je mlai od nas.
{106404}{106515}- Tko je to?!  - Izgleda blesavo.|- Tko je to?
{106547}{106575}Ne znam.
{106576}{106607}Pogledaj ovog maliöu gdje viri.
{106608}{106652}- Isuse Kriste!|- Rekla sam ti...
{106715}{106755}Tako je ûestok.
{106756}{106787}Steve neki.
{106788}{106811}Steve...
{106812}{106862}I evo ga... Steve...
{106863}{106920}Zaöto nas nije netko zaustavio?
{106971}{106999}To je tako cool.
{107000}{107029}Nije...
{107030}{107070}- To je moje.|- Tvoje je je.
{107071}{107099}O, Boûe.
{107124}{107155}To je neka vrsta...
{107156}{107197}Izgleda kao nos ili tako neöto.
{107198}{107235}Ovo je totalno sjebano.
{107236}{107259}Keith?
{107260}{107311}- O, moj Boûe!|- O, Suze!
{107312}{107367}Oh! Oh! O, moj Boûe.
{107368}{107403}Imam ga. Evo.
{107404}{107459}Zaöto nisi ugasila joint?
{107460}{107494}Daj da ti pomognem.
{107495}{107535}- Nemoj me udariti.|- O, moj Boûe.
{107564}{107595}O, moj Boûe.
{107596}{107639}Spaljujemo kuÊu.
{107640}{107663}Lavinia! Lavinia!
{107664}{107714}U redu je, duöo.
{107739}{107767}O, Boûe.
{107768}{107816}Bok, Raymonde.
{107842}{107873}äto se dogodilo, Lavinia?
{107903}{107958}Da li je to ono öto mislim da je?
{107959}{108002}äto misliö da je?
{108003}{108046}Pa...
{108047}{108097}Lavinia, öto... öto...
{108098}{108155}äto to imaö na sebi?
{108156}{108203}äto si napravila sa kosom?
{108204}{108249}Odrezala ju je. Kako ti se svia?
{108250}{108273}Lavinia...
{108284}{108335}U redu, Raymonde, vidi...
{108372}{108493}znaö kako neki, um...|ljudi skupljaju baseball kartice?
{108494}{108551}Pa, Suzette i ja smo...
{108552}{108596}äto? äto? Fotografi?
{108716}{108756}Ne, Raymonde.
{108826}{108903}éao mi je. Ne, ne.
{109042}{109148}Ne. Bile smo... groupie.
{109180}{109241}Ti... Ti si... Ti si bila groupie?
{109242}{109289}Bila si groupie?
{109290}{109337}Da.
{109338}{109405}A ovo... ovo su slike glazbenika.
{109406}{109429}Glazbenika?
{109430}{109500}I nekoliko njih u prolazu.
{109533}{109584}Kako to misliö da ste bile groupie?
{109711}{109741}Mi...
{109742}{109781}Oprosti.
{109782}{109872}Tata, mama, gdje ste?
{109873}{109920}Oh, sranje!
{109921}{109963}- äto sam napravila?|- Lavinia!
{109964}{110035}äto to radiö?|Isuse. Smrdi kao...
{110036}{110077}Evo.
{110078}{110113}Zdravo, duöo.
{110520}{110569}Ginger je.
{110570}{110622}Uzela je moj auto.
{110730}{110872}Ovo je tako glupo. Samo sam malo udarila|u parkirani auto i odvezli su me u bolnicu
{110873}{110922}i natjerali me da obuËem ovu glupost!|Mama, öto ti se dogodilo sa kosom?
{110981}{111027}U redu je. Sjedni.
{111028}{111087}Nisam ozlijeena, osim öto me|zraËni jastuk udario u lice.
{111088}{111137}Vozila si bez vozaËke dozvole.
{111138}{111185}Pa zaöto me onda ne vode u zatvor?|To ima viöe smisla.
{111186}{111240}VeÊ si dovoljno u problemima, mlada damo.
{111241}{111336}Vozila sam se po cijelom Phoenixu, tata. To je bio jedini|auto koji sam udarila. »ak ni to nije bila moja greöka.
{111337}{111380}Kako to misliö da nije tvoja greöka?
{111381}{111421}Hannah mi je dala kljuËeve.
{111422}{111469}Rekla si da Êeö ostati u Blossom Krugu.
{111470}{111516}Bilo je dosadno. To je samo krug.
{111517}{111573}Dozvolila si sestri da vozi tvoj auto?
{111574}{111618}Ne mogu vjerovati da si tako neodgovorna.
{111619}{111715}Ja?! Ti imaö cijelu povijest neodgovornog|ponaöanja. Ti i Suzzete.
{111716}{111754}Ne mijeöajte mene. Ja samo stojim ovdje.
{111755}{111783}I radiö öto?
{111784}{111872}äto ti imaö sa naöom obitelji,|osim toga öto si doöla i sve uniötila?
{111873}{111904}Sve je bilo u redu dok se ti nisi pojavila.
{111905}{111936}Nije bilo sve u redu.
{111937}{111968}Ona je sve pogoröala.
{111969}{111993}Suzette.
{111994}{112025}- Lavinia.|- Mama! Ti si tako...
{112026}{112132}licemjerna. Poludjela si jer sam se seksala|sa svojim deËkom u bazenu.
{112133}{112205}- To mi je posao.  - U bazenu?|- Samo te pokuöavam zaötititi.
{112206}{112254}Mislim da to nije problem,|dok mi stalno diöeö za vratom.
{112255}{112308}- Molim te budi tiha.|- Toliko sam sigurna da se guöim.
{112309}{112356}Jedva Ëekam da odem na kole|da se maknem od tebe.
{112357}{112388}Zaboga, ovo je bolnica.
{112389}{112472}Pusti je da govori! Upravo mi govori|kako sam usrana majka.
{112473}{112577}- Ovo je javno mjesto.|- äto se ti brineö? Da Êeö izgubiti koji glas?
{112578}{112671}Brinem se za tebe. Za to se brinem, Vinnie,|ili kako se veÊ zoveö ovih dana.
{112672}{112773}Jedan tren okopavaö biljke,|a sljedeÊi slaûeö penise po podu.
{112774}{112852}- Penise?|- Ne znam tko si ti.
{112853}{113032}Ne. Ne znaö. U pravu si. Toliko sam zauzeta|okopavanjem biljaka i voditi te na nogomet
{113033}{113194}i skupljajuÊi tvoja sranja|i vodeÊi psa na tko koju po redu injekciju...
{113255}{113294}Izgubila sam se.
{113452}{113494}Moûemo li iÊi kuÊi, molim te?
{113588}{113654}Toliko sam umoran da viöe ni ne vidim.
{113655}{113718}Znate, danas je maturalna sveËanost.
{113719}{113771}Da, mama, a ja sam jako, jako gladna.
{113855}{113943}Niste niöta Ëuli öto sam rekla, zar ne?
{114352}{114394}äto se dogodilo?
{114586}{114760}- Halo. - Harry, sluöaj. Idem nazad.|Pokupit Êu svoje stvari i auto i odlazim. VraÊam se u LA.
{114761}{114823}- Ali...|- Ali niöta.
{114824}{114923}Ti si samo tip kojeg sam pokupila, Harry.|Samo sam te pokupila, u redu?
{114924}{115005}Dosta mi je govorenja.|Samo mi se miËi sa puta.
{116086}{116193}- Hannah i Ginger su bile ljute na mene. One nisu...|- Nisu one krive. Bile su u pravu, Vin.
{116194}{116430}Ne pripadam ovdje. Ne znam gdje|pripadam. Samo sam doöla ovdje...
{116468}{116639}Ne znam zaöto sam doöla. Ne znam öto traûim.|Samo znam sjebati situaciju.
{116640}{116759}- Sjebala sam situaciju jako dobro. To me ide.|- Ne.
{116760}{116836}- A vi se, narode, svaate i prepirete.|- Izgubila sam.
{116837}{116915}- Sve sam ja kriva.|- Ne, nije. Izgubila sam.
{116916}{117091}Ali to je ono öto ljudi rade kada se vole.|ViËu jedni na druge i prepiru se.
{117092}{117187}Sve bih dala da imam obitelj sa kojom|se mogu prepirati i svaati
{117188}{117299}ali ja imam samo jebenu maËku|koja nije vrijedna spomena.
{117300}{117368}Ali ja sam tvoja obitelj.|Sa mnom se svaaö, zar ne?
{117369}{117415}O, Vin.
{117468}{117753}Moja jedina slava je öto sam pustila zilijun glazbenika|da mi se uvuku u gaÊe, a nije ih bilo briga za mene.
{117840}{117949}I ja sam to radila, samo öto nisam mogla|o tome priËati dok nisi doöla ti.
{117950}{118051}Sada se tome smijem i pleöem.|Pogledaj me.
{118052}{118249}Ti si sila, slatkice. To je ono öto volim kod tebe.|Nema nikoga kao öto si ti, u redu?
{118250}{118371}- Volim te.|- I ja tebe.
{118372}{118459}1, 2...
{118460}{118566}3, 4, 5, 6...
{118567}{118652}7, 8, 9, 10.
{118786}{118889}Znaö, doveli su nekog tipa na nosilima.
{118890}{118977}Lice mu je bilo plavo|i imao je neöto prebaËeno preko sebe.
{118978}{119067}Mislila sam da je mrtav.|»ak je i on pogledao u moje cice.
{119121}{119204}Moûda si ga oûivjela.
{119246}{119314}O, ËovjeËe.
{119315}{119352}äeta mi se.
{119353}{119406}OK. Gdje ûeliö iÊi?
{120905}{120982}Rano je. Ne ûelim ga buditi.
{121345}{121444}- Gdje je on?|- Neöto nije u redu.
{121445}{121479}- Ovo nije dobro.|- Zaöto?
{121480}{121573}- Ne.|- Prekrasan je dan, Suzette. Mogao bi biti bilo gdje.
{121574}{121609}- Ne. Neöto nije u redu.|- äto?
{121610}{121652}OsjeÊam to.
{121797}{121915}- O, Vin, pisaÊa maöina je na dnu bazena.|- äto?
{121916}{122009}- Piötolj. Mora da je uzeo piötolj.|- Harry ima piötolj?
{122010}{122077}Da. Sa samo jednim metkom|namijenjeno samo jednoj osobi.
{122078}{122169}- Kome?|- Njegovom ocu.
{122170}{122269}- Upucat Êe svog oca?|- Da. Samo sam... »ovjeËe, loöe se osjeÊam.
{122270}{122351}- Nazvala sam ga i poklopila i...|- Suzette, Suzette, sluöaj.
{122352}{122417}- OsjeÊam...Da...|- Saberi se. Gdje je njegov otac?
{122418}{122485}- On je u nekom staraËkom domu.|- OK.
{122486}{122611}- Zove se neöto neöto.|- Neöto. U redu, koncentriraj se.
{122612}{122668}- Neöto... Horizon neöto.|- Horizon Hills?
{122669}{122721}Tako je. Horizon Hills.|Znaö gdje je to?
{122722}{122757}Da.
{122758}{122793}Pa idemo, ËovjeËe.
{122794}{122874}Ali to nije staraËki dom.
{123110}{123193}- äto namjeravaö s njim, Vin?|- Piötolj je nezgodna stvar.
{123194}{123309}O, ËovjeËe. äto da napravim?|Kako da ga odgovorim?
{123310}{123436}Smislit Êeö neöto. Samo ostani|mirna, racionalna.
{123573}{123686}- Lagao si mi Harry.|- A ti si mi rekla da ti se miËem sa puta, sjeÊaö se?
{123687}{123768}- Ulazi u auto.|- Ovo je izmeu mene i njega.
{123769}{123883}- Ali on je veÊ mrtav, luaËe.|- Ne, nije. Ovdje je.
{123884}{123943}- äto?|- Ovdje.
{123974}{124025}Zaöto ga joö uvijek okrivljujeö?
{124026}{124076}Znaö kakvog oca sam imao?
{124077}{124151}- Kada sam bio Ëetverogodiönjak, bio sam...|- Jebeö Ëetverogodiönjak.
{124152}{124253}Cijelo moje djetinjstvo nikad ga nije bilo.|Svaku veËer sam iöao u krevet bez oca da me uöuöka.
{124254}{124296}Znaö koliko ötetno to moûe biti?
{124297}{124437}äteta öto se nismo tada poznavali, jer|sam ti mogla poslati svog oca da te on uöuöka.
{124438}{124507}Mrzio me je, mislio je da sam bezvrijedan|kritizirao sve öto sam napravio.
{124508}{124547}Za boga miloga.
{124848}{124945}- Pregazila si me.|- Netko je morao. Jesi li se ti Ëuo?
{124946}{125055}- Ne gazi se preko ljudi!|- Harry, iöle smo samo 5 km/h.
{125056}{125131}U Ëemu je problem?|Ionako si se htio ubiti, zar ne?
{125132}{125160}Harry, hajde.
{125161}{125221}- Obje ste lude.|- ToËno.
{125222}{125308}- Imam ga. Imam ga.|- Daj mi to.
{125410}{125449}äto Êeö napraviti?
{125450}{125512}PomoÊi Êu ti, Harry.
{125702}{125725}Isuse.
{125909}{125951}To je bio tvoj jedini metak.
{126257}{126322}Idi i oprosti mu, Harry.
{126386}{126454}VeÊ si ovdje.|Mogao bi i popriËati s njim.
{127581}{127632}Tata?
{127633}{127697}Tata?
{127698}{127755}Tata?
{128029}{128084}Hajde, Suzette. Poûuri.
{128121}{128168}- Poûuri. poûuri!|- Idem, idem.
{128169}{128215}Moûda su veÊ poËeli.
{128440}{128471}Doi.
{128522}{128559}Hajde.
{128560}{128675}Suzette, doi i ti.|Hajde, hajde.
{128676}{128715}Obuj cipele, duöo.
{128716}{128795}-»ekaj.|-Gdje Êeö? Hajde. Jesi li? Dobro.
{128796}{128863}äto je sa drugom?|Izgledaö super.
{128961}{129097}Mrzim osjeÊaj laûnog viöe od bilo Ëega na svijetu.|Ne bi vjerovali öto vam ljudi sve govore...
{129098}{129219}"Moraö iÊi na kole. Moraö shvatiti öto Êeö|raditi. Moraö zaraditi novac."
{129220}{129314}A mi mislimo...|"Boûe, pa joö smo praktiËno djeca."
{129315}{129447}Ali vaöi nastavnici i vaöi roditelji i ostali|sve su veÊ za vas isplanirali sa velikim oËekivanjem.
{129448}{129554}Ali öto ako to nema veze sa vama?
{129591}{129654}Izgubili biste svoj smisao.
{129706}{129755}A to je laûno.
{129819}{129947}Mi idemo u buduÊnost, a ja niti ne znam|öto nas tamo oËekuje.
{129948}{130077}Ponekad sam preplaöena na smrt.|Ponekad sam uzbuena.
{130078}{130235}éelim svima u mojoj klasi...|ne, ûelim svima da öto god napravili
{130236}{130369}napravite to poöteno. »ak i ako|zabrljate ili posrnete.
{130370}{130494}Radije posrnem radeÊi po mome,|radeÊi öto ja ûelim
{130495}{130567}nego raditi neöto öto od mene ûeli netko|drugi i u tomu uspijem.
{130602}{130772}Radije Êu se svaati sa svojom obitelji|nego se pretvarati da je sve u redu.
{130815}{131001}Diplomci klase 2002, krenite.|Krenite u svijet i budite poöteni.
{131002}{131063}Budite poöteni.
{131938}{131965}Duöo, bila si prava.
{131966}{132062}A sada idemo svi skupa kuÊi.|Ti nas prati u svom autu, u redu?
{132063}{132148}Ne. Ja sada odlazim.|Da, imam joö napraviti neke stvari.
{132149}{132245}- Ali moram ti vratiti odjeÊu.|- Ma u redu je. Zadrûi je.
{132246}{132283}To Êe mi biti opravdanje da|te ponovo posjetim.
{132284}{132350}Za to ti ne treba opravdanje.
{132420}{132504}- Bilo nam je ludo.|- Da.
{132505}{132579}- Mama! O, moj Boûe. Narode!|- äto je?
{132580}{132649}- Totalno sam zaljubljena.|- Tko? U koga?
{132650}{132717}äööö. Ovdje...|Ovdje je.
{132718}{132785}»ekaj, Ëekaj.|Ne on, ne on.
{132786}{132829}Evo ga. To je on.
{132870}{132900}Glazbenici.
{132901}{132947}Da.
{134017}{134082}- Hej, Suzette.|- Da?
{134083}{134176}- éeliö li Ëuti priËu koju piöem?|- Da. Reci mi.
{134177}{134384}Pa, rijeË je o tipu koji je totalno kompliciran|kada susreÊe ûenu koja...
{134442}{134477}ona je...
{134478}{134593}Harry, preskoËi na kraj.|äto bude sa njima?
{134634}{134724}Ne znam. To joö nisam prokuûio.
{134902}{134948}Ona je drkaËica.
{135008}{135049}I to radi fantastiËno.
{135630}{136666}Subtitles by:|M O Z E N
{136691}{138191}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/5ry78|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
