{25}{175}-== [ www.OpenSubtitles.com ] ==-
{2952}{3020}- Majkle.|- Karle!
{3031}{3090}Majkle, jesi li video ovo?
{3176}{3236}Prepoznaješ ga?|- Ne.
{3279}{3386}- Jesi li video veæ Jigaelov zid?|- Otvoren je tek prošle nedelje.
{3392}{3488}Postoje èetiri lica antihrista|koji se uzdiže na vlast.
{3498}{3576}Lik Jigaelovog Satane, |kao deteta, je isti!
{3599}{3653}- O èemu govoriš?|- Nema sumnje.
{3662}{3747}Demijen Torn je antihrist.
{3781}{3849}- Ah, Karle...|- Majkle, moraš mi verovati!
{3856}{3921}Ja sam arheolog, |a ne religiozni fanatik.
{3929}{4023}"Èak i danas, on je veæ na svetu,|i njegova moæ æe biti velika,
{4033}{4161}i on æe napredovati, i uèiti,|i uništiæe moæne i svete."
{4172}{4248}Cenim to, ali koje |moguæe èinjenice...
{4254}{4302}Njegov otac je znao.
{4311}{4362}Pre nedelju dana, |pokušao je da ga uništi.
{4423}{4509}To je minorni detalj |koji su novine preæutale.
{4530}{4599}Lièno sam mu dao bodeže.
{4671}{4734}On je u Èikagu, |živi sa svojim stricem.
{4740}{4858}Sada ti... moraš uzeti ovo i |dati njegovim novim roditeljima.
{4864}{4945}- Pa, šta je to?|- Pismo unutra objašnjava sve.
{4964}{5034}- Karl, ne možeš oèekivati...|- Oni moraju biti upozoreni!
{5046}{5117}Ja sam suviše star. I suviše bolestan.|Ne mogu da idem lièno.
{5141}{5219}I ja sam jedina živa |osoba koja zna istinu.
{5245}{5306}Moram da održim reputaciju!
{5314}{5387}Zato moraš biti ti.|Tebe æe slušati.
{5395}{5436}I onda me osuditi. Ne!
{5444}{5529}Vidi, Karl, mi smo stari prijatelji.|Mislim da se razumemo.
{5546}{5634}- Ne možeš oèekivati da poverujem...|- Onda idi do Jigaelovog zida!
{5653}{5699}- Šta, sada?|- Sada!
{6462}{6492}Evo, Majkle.
{6505}{6540}Karl Bugenhagen,
{6551}{6627}nadam se da mi ovo |garantuje mesto na nebu.
{8813}{8865}Majkle, sada æe ti trebati baklja.
{9342}{9394}To je vavilonska kurva!
{9413}{9460}Ovo je neprocenjivo.
{9866}{9913}Majkle.
{9938}{10005}Majkle! Doði ovamo!
{10151}{10189}Vidi.
{10269}{10318}To je on.
{10586}{10627}- Ima li drugog izlaza?|- Ne.
{11358}{11397}Karle...
{11425}{11485}Antihrist je sa nama.
{11754}{11870}Karle! Moramo napolje! Karle! Karle,|hajde, pomozi mi! Karle, pomozi mi, hoæeš li?
{11927}{11955}Karle!
{11968}{12027}- U pomoæ!|- Majkle!
{12093}{12142}Majkle!
{12554}{12649}Možda su nas |sile zla savladale
{12671}{12717}i pobedile,
{12730}{12832}ali æe dobro prevladati,|jer je tako napisano u Knjizi Otkrovenja.
{12851}{12905}"Tada æe zli biti otkriven,
{12917}{13008}koga æe Gospod pojesti|duhom svojih usta
{13029}{13113}i uništiti ga|jasnoæom Njegovog dolaska."
{13595}{13668}{Y:i}ÈIKAGO |{Y:i}SEDAM GODINA KASNIJE
{13775}{13829}- Demijene!|- Dolazim!
{14126}{14193}- Vidimo se sledeæeg leta, Džime.|- Pozdravi roðaka.
{14200}{14237}- Hoæu. Pa-pa.|- Pa-pa.
{14413}{14452}- Hajdemo!|- Dolazim.
{14615}{14659}- Jesi li ga našao?|- Da, dolazi.
{14893}{14959}- Do viðenja, tetka Merion. Drago mi je da |sam vas ponovo video. - Ko ti je rekao?
{14993}{15021}Rekao mi šta?
{15038}{15103}Ljubaznost ti nije jaèa strana, Demijene.
{15115}{15192}Sigurna sam da nisi došao|da se pozdraviš zato što ti to želiš.
{15202}{15268}Nisam znao da si tu.|Ali sam hteo da doðem.
{15275}{15304}Zaista?
{15319}{15352}Zbogom, tetka Merion.
{15618}{15661}- Sve spremno?|- Mislimo da da.
{15671}{15701}- Vraæam se brzo.|- Idemo.
{15881}{15954}Sada... vi momci imate svoj novac,
{15961}{16037}tako da je ovo neki dodatak,|u sluèaju nužde.
{16189}{16250}Saèekaj! Da li si se |pozdravio sa tetka Merion?
{16258}{16280}Jesam.
{16398}{16430}Tetka Merion?
{16451}{16512}Oh, Mark!|Nisam te dovoljno videla.
{16520}{16604}- Trebao si da doðeš u moju sobu da poprièamo.|- Žao mi je, tetka Merion.
{16626}{16693}Znam da si bio zauzet,|jureæi za roðakom.
{16707}{16768}Ne smeš mu dozvoliti |da te tako vucara za sobom.
{16777}{16819}Ne vucara me. |Sviða mi se.
{16873}{16913}Zagrli me.
{16954}{16990}Èuvaj se.
{17025}{17086}Da, tetka Merion. Zbogom.
{17184}{17218}Samo malo!
{17284}{17307}Zbogom, tata.
{17336}{17391}Jesi li me zaboravio? |Sigurno?
{17425}{17466}Evo, dušo, uzmi malo kolaèa.|Želim ti prijatnu nedelju.
{17475}{17500}Zdravo.
{17781}{17838}- Baš je teška, tetka Merion.|- Užasna je! Zašto su je pozvali?
{17844}{17949}Da bi mogla da maše prstom,|i da nam pokvari vikend.
{17958}{18048}Bar ne moramo da veèeramo sa njom.|Bože! I kakav je to miris?
{18057}{18144}Lavanda, budalo! Sve stare žene|se kupaju u njoj. Ne znam zašto.
{18156}{18241}- Sada, momci. Samo zato što ide...|- Na naše nerve!
{18248}{18322}Polako. Marej je u pravu.|Da èujemo za tetka Merion.
{18333}{18365}Ura!
{18389}{18433}Marej, daj cigaretu.
{18441}{18513}- Znaš odgovor na to.|- Ako ne pitaš, neæeš znati.
{18527}{18587}- Jesi li upoznao novog komandanta voda?|- Nefa?
{18597}{18635}Nef kao "nije važno".
{18650}{18737}Isti su. Kad srenteš |jednog, sreo si ih sve.
{18748}{18819}Pažnja! Pogled napred!|Grudi izbaci! Stomak uvuci!
{18835}{18880}Znaš šta? |Ti si lud!
{18889}{18939}- Da, jer smo vežbali.|- Bože!
{19083}{19162}- Da li bi želela malo krema, tetka Merion?|- Pitala si me šest puta.
{19204}{19238}Žao mi je, zaboravila sam.
{19253}{19309}Nisi zaboravila. |Samo te nije briga.
{19322}{19378}Merion, da se ne svaðamo ponovo.
{19388}{19434}- Bez krema.|- Bez krema!
{19454}{19528}Èarls æe nam pokazati |neke slajdove posle veèere,
{19540}{19590}zašto nam onda ne bi |rekla zašto si došla, Merion?
{19623}{19727}Posedujem 27% Torn Industrije,|koje mi je ostavio tvoj otac.
{19739}{19837}I imam sva prava da raspolažem|svojim deonicama kako god želim.
{19857}{19914}- Znamo to.|- Znaš li takoðe da,
{19921}{19988}trenutno,|ostavljam sve tebi, Rièarde.
{20016}{20079}Ali, ako ne uradiš šta tražim...
{20088}{20160}Merion, ne preti mi.|Jer, koliko je mene briga...
{20168}{20251}Ne može da te ne bude briga|za sumu oko 100 miliona dolara!
{20258}{20292}Ne bi trebalo da sam ovde...
{20301}{20369}Vi ste ovde, doktore Voren,|jer ste kustos Tornovog Muzeja.
{20381}{20450}A posedujem 27% i njegovih deonica!
{20458}{20536}Merion, reci šta imaš.|Ako je neprijatno, da završimo s tim.
{20557}{20616}Hoæu da momke |vratiš iz akademije.
{20629}{20676}Hoæu da ih pošalješ |u odvojene škole.
{20706}{20789}Nije me briga šta želiš,|što se tièe deèaka.
{20806}{20899}- Nisu tvoji sinovi, nego naši.|- Nijedan deèak nije vaš.
{20914}{21003}Treba li da te podsetim|da je Mark, Rièardov sin od prve žene.
{21012}{21077}- A Demijen je sin njegovog brata.|- Hvala ti.
{21115}{21183}- Hvala ti mnogo!|- An... An... molim te.
{21194}{21254}Merion, zbog èega |je sve to, do ðavola?
{21260}{21341}Skloni Marka od Demijena.|Nije im mesto zajedno!
{21356}{21425}- Demijen daje jako loš primer, |zar ne vidiš? - Šta?
{21453}{21512}To je to. Što se tièe mene,|razgovor je završen.
{21550}{21621}- A ja predlažem da...|- Rièerde, ti si slep. Namerno slep!
{21639}{21709}- Znaš da je tvoj brat pokušao |da ubije Demijena. - Napolje!
{21723}{21820}- Rièarde, isteraj je!|- Zašto je pokušao da ga ubije? Reci istinu!
{21827}{21907}- Merion, on je bio bolestan!|- Ne moraš to da joj objašnjavaš!
{21914}{22004}Ako ih ne odvojiš, sve što imam |ostaviæu u dobrotvorne svrhe!
{22013}{22060}Nije me briga šta |æeš uraditi sa novcem!
{22067}{22131}Rièarde, molim te! Slušaj me!|Znaš da je ovo što govorim istina.
{22145}{22193}Možda sam stara, |ali nisam luda.
{22202}{22249}Tvoj brat je pokušao |da ubije Demijena.
{22257}{22333}- Napolje! Hoæeš li joj reæi da izaðe?|- Izlazim.
{22478}{22574}Žao mi je, Èarlse. Izvinjavam se u njeno ime.|Stara je i nije joj dobro.
{22583}{22645}Ne, to je... u redu.|Razumem.
{22655}{22776}- Trebao sam pre veèere da primetim...|- Rièarde, uveravam te, ne razmišljaj o tome.
{22794}{22831}Idem da postavim slajdove.
{22926}{23001}Hoæu da izaðe do jutra.|Ne želim je u kuæi.
{23009}{23078}- Sirota žena je senilna.|- Ta "sirota žena" je opasna!
{23088}{23128}Zagaðuje vazduh svojim ludilom!
{23136}{23213}Deèaci ne mogu da podnesu|da budu u istoj sobi sa njom.
{23222}{23265}U redu, ide odmah ujutru.
{23275}{23326}- Zašto mrzi Demijena?|- Ne znam.
{23333}{23425}Strašno ga mrzi! I treba da odem,| ne samo zbog deèaka ili mene.
{23435}{23466}Pokrenula je nešto u tebi.
{23475}{23543}U redu, gotovo je. |Rešeno je.
{23684}{23744}Hajde. |Da se pridružimo Èarlsu, a?
{24285}{24337}Mnogi od ovih su veæ poslati.
{24354}{24414}Trebalo bi da imamo |prvu isporuku za oko tri nedelje.
{24598}{24663}Mislio sam da æe |vas ovo interesovati.
{24683}{24741}- Oh, dragi Bože!|- Da, malo je zastrašujuæe, zar ne?
{24775}{24827}Vavilonska kurva?
{24836}{24913}Fenomenalan si.|Da, vavilonska kurva.
{24925}{25021}Ona predstavlja Rim.|"Deset rogova zveri su deset kraljeva,
{25028}{25128}koji još nemaju kraljevstva, ali æe im biti|privremeno dodeljeno od strane ðavola."
{25137}{25171}Njegova imena su uklesana ovde.
{25193}{25225}Kvarilac.
{25251}{25328}Mali Gor. Oèajni.
{25341}{25429}- Zašto ga jaše?|- Ne znam. Ali to neæe biti veèno.
{25438}{25483}Knjiga Otkrovenja kaže da deset kraljeva,
{25502}{25582}"æe mrzeti kurvu,|i naèiniti je oèajnom i golom,
{25594}{25664}i ješæe joj meso, |i izgoreti je u vatri."
{25697}{25763}To baš nije lepo.
{25815}{25855}Ko je mlada dama?
{25867}{25931}Njeno ime je Džoan Hart.|Ona je moja prijateljica, novinarka.
{25943}{26037}Radi na Bugenhagenovoj biografiji,|arheologa koji je radio u toj oblasti.
{26051}{26121}- Èuo sam za njega.|- Ona dolazi u Èikago, Rièarde.
{26130}{26188}- Želi da te intevjuiše.|- Zašto?
{26198}{26273}Pa... Kao prateæa stvar izložbi,|gazda arheoloških iskopavanja.
{26289}{26358}- Nisam mnogo sreæan kad |su intevjui u pitanju. - Znam.
{26367}{26405}- Bilo koje vrste.|- Znam.
{28899}{28951}Spremni! Stanite!
{28967}{29036}Pokaži... oružje!
{29174}{29234}- To mora da je on.|- Izgleda u redu.
{29249}{29283}Svi su oni isti.
{29321}{29392}Prisloni... oružje!
{29407}{29501}Bredli vod, brzo stanite!|Drugi vodovi, u salu.
{29516}{29574}Desnim krilom, |napred marš!
{29708}{29747}Voljno, momci.
{29761}{29806}Ovo je narednik Denijel Nef.
{29815}{29899}On æe preuzeti vod kao |komandant, od narednika Gudrièa.
{29916}{30021}Narednik Nef je jako iskusan vojnik,|i siguran sam da æe za nekoliko nedelja,
{30029}{30093}ovaj vod biti najbolji |na celoj akademiji.
{30119}{30191}Ostaviæu sva dodatna |uputstva naredniku.
{30449}{30556}Prièaæete samo kada vam se obratim.|I slušaæete sve što kažem.
{30589}{30672}Jer imam nameru da |zablistam na novom mestu.
{30684}{30773}A jedini naèin da ja zablistam, |je da zablistate vi.
{30810}{30911}Vi ste mala jedinica koju moram |da uglancam do vrhunca vaših moæi,
{30936}{30997}tako da zaslepite |svakog na ovoj pisti.
{31027}{31085}- Da li ste me razumeli?|- Da, gospodine!
{31127}{31193}Srešæu se sa svakim pojedinaèno|u svojoj kancelariji posle doruèka.
{31209}{31261}Za sada... vaša imena?
{31287}{31340}- Mark Torn, narednièe.|- Torn?
{31355}{31412}Tvoja prodica ima jake |veze sa ovim mestom, zar ne?
{31446}{31526}- Pa, zar nije tako?|- Moj otac i deda su bili kadeti, gospodine.
{31536}{31624}Dobro. Ali shvataš da ti to ne |donosi privilegije. Svi smo ovde isti.
{31700}{31722}Tvoje?
{31736}{31771}Demijen Torn, narednièe.
{31819}{31881}- Vi ne lièite.|- Roðaci, narednièe.
{31937}{32010}U redu. Ali razumeš, |isto važi i za tebe.
{32061}{32087}Tvoje ime?
{32804}{32852}- Jutro, Bile.|- Pa! Rièarde.
{32879}{32951}Uzgred, moram nešto |da poprièam sa tobom.
{33001}{33064}Ja sam prvi koji priznaje |da je teško složiti se sa Polom,
{33081}{33156}ali su nam trebale godine da bismo |našli èoveka sa njegovim kvalifikacijama.
{33166}{33231}Ne sumnjam u to.|Nego...
{33244}{33278}Njegovo ponašanje.
{33297}{33385}Èak mogu da se nosim i sa ponašanjem.|Sretao sam ga u svakakvim stanjima.
{33406}{33517}Ne. Ne sviða mi se šta predlaže.|Meša se u moje poslove.
{33528}{33592}I nemam nameru da skrivam |šta oseæam po tom pitanju.
{33603}{33672}Misliš da bi mogao da nas|upetlja sa ministarstvom pravosuða?
{33684}{33736}Pa, on se bavi jako |emotivnim stvarima.
{33753}{33887}Bile, da ga saslušamo.|Jedino što tražim je
{33894}{34005}da ti kontrolišeš svoje primedbe,|malo delikatnije nego obièno.
{34174}{34227}Džini!|Je li gðica Merion obuèena?
{34239}{34328}Mislim da nije budna, gospoðo Torn.|Kucala sam, ali nije odgovorila.
{34336}{34358}Hvala ti.
{34474}{34507}Tetka Merion?
{34517}{34552}Propustiæeš avion!
{34991}{35111}Pole, ti kažeš da bi trebalo da|napustimo lidersku poziciju u elektronici.
{35121}{35200}Grešiš. Moj izveštaj kaže da su |glavni prioriteti Torn Industrije,
{35212}{35253}energija i elektronika.
{35268}{35359}Zvog ovog dvojca, ignorišemo ono |što se dešava u ovom postrojenju.
{35371}{35499}Ignorišemo to na sopstveni rizik. Naša profitabilna| buduænost, pored energije, leži u gladi.
{35517}{35617}Šta? To je tipièna tvoja tvrdnja, |Pole. Bezoseæajna je i...
{35624}{35678}I istinita. |Nije bezoseæajna, realistièna.
{35690}{35721}Pasariane, saèekaj.
{35780}{35831}Jesu li ti rastvori obeleženi?
{35841}{35931}Ne, ne još. Svaki tank |ima razlièito ðubrivo i pesticid.
{35939}{36030}Neæe biti dok ih |ne ubacimo u probne useve.
{36041}{36079}U redu, idemo.
{36100}{36168}Jedna osoba umre od |gladi svakih 8.6 sekundi.
{36180}{36298}Sedam svakog minuta.|420 svakog sata. 10,000 svakog dana!
{36310}{36367}Da bi nahranili ove ljude,|morali bi da isušimo okean.
{36376}{36473}Moramo da razvijemo nove sojeve|visoko prinosnih useva, otpornih na bolesti.
{36481}{36548}Naftne države ne oklevaju|da nam pritiskaju jugularnu venu.
{36569}{36614}Pa, šta je to toliko |drugaèije kod hrane?
{36622}{36682}Da imate nož u stomaku, |bili biste mirni.
{36703}{36751}Zašto, onda, zvati moju strategiju neetièkom?
{36760}{36842}To je neèoveèno, nesavesno,|i po mom mišljenju, nedozvoljeno.
{36850}{36902}Šta je nehumano |kod hranjenja ljudi?
{36910}{36954}- Telefon, gdine Torn.|- Zauzet sam.
{36961}{36993}Hitno je, gospodine.
{37079}{37188}Bilovo mišljenje je, ako kontrolišemo hranu koju jedu ljudi,|to je kao da od njih pravimo robove.
{37198}{37285}- Ah, mušterije!|- Ali ti hoæeš da od njih otkupimo zemlju.
{37294}{37356}Torn ima mašineriju i znanje
{37365}{37437}koje je lako prilagodljivo|za planiranje uzgoja velikih razmera.
{37448}{37503}To, sa pesticidima i ðubrivima |koje proizvodimo,
{37516}{37589}nam daje odskoènu dasku|za bilo koji entitet na svetu.
{37599}{37677}Ako kontrolišemo njihovu zemlju,|pravimo od njih stanare.
{37685}{37775}- Bile, mi im punimo stomake.|- Moram da se složim sa Polom.
{37792}{37827}Odmah se vraæam.
{37926}{37999}Merion je umrla u snu sinoæ,|srèani udar.
{38007}{38077}- Žao mi je.|- Moram da idem. Prièaæu kasnije sa tobom, Bile.
{38105}{38179}- Pole, kako bi bilo doruèak ujutru?|- Naravno.
{38259}{38309}- Jesu li se veæ uselili u stan?|- Danas.
{38387}{38417}Ponovo je zima.
{38428}{38480}To je Demijenov |otac tamo pozadi.
{38487}{38550}I moj stari je igrao |u tom timu. To je on.
{38559}{38624}On je bio na liniji,|ali Robert Torn je bio kvorterbek.
{38636}{38697}I tada je cela igra |zavisila od njega.
{38706}{38758}- Ti si sledeæi, Demijene.|- Hej, Tedi.
{38782}{38865}Ne govori više nikad o mom ocu.|Razumeš li?
{38879}{38918}Zar ne možeš da prihvatiš šalu?
{38930}{38960}Da.
{39061}{39155}- Oko èega je to bilo?|- Tvoj roðak stvarno misli da je faca.
{39171}{39235}Moj stari mi je rekao da |Tornovi sami prave sebi šešire,
{39243}{39315}jer izgleda da ne prodaju |toliko velike, kolike su im glave!
{39468}{39519}Zažaliæeš to, Torne.
{39535}{39605}"Matematika dobar.|Nauka, vrlo dobar. Vojna istorija dovoljan."
{39617}{39674}- "Soba za popravak".|- Da, narednièe.
{39698}{39758}Fizièko je odlièno.|Èujem da si dobar igraè fudbala.
{39812}{39888}Budi ponosan na svoja dostignuæa.|Ponos je u redu, kada ima razloga za to.
{39912}{39946}Da, narednièe.
{39980}{40044}Ovde sam da te nauèim,|ali sam takoðe tu i da ti pomognem.
{40055}{40106}Ako ima bilo kakvih |problema, doði kod mene.
{40118}{40226}Ne boj se. Danju ili noæu.|Bilo koji savet. Razumeš?
{40242}{40328}- Šta god vi kažete, narednièe.|- Moramo da se dobro upoznamo.
{40348}{40389}Vidim da si siroèe.
{40420}{40475}To nam je zajednièko.
{40493}{40535}Pošalji Fostera unutra.
{40649}{40708}Šta je sad?|Zar ne voliš na leðima?
{40753}{40789}- Tedi!
{40815}{40852}Još jedan Torn.
{41643}{41711}- Šta kog ðavola èekamo? Foster.|- Da, gospodine?
{41718}{41777}Jeste li vas dvojica |završili? Napolje!
{41845}{41885}Šta to radiš? |Glancaš pod?
{42136}{42172}Šta si mu uradio?
{42219}{42258}Ne znam.
{42287}{42326}Ne znam.
{42442}{42515}Hajde. Jednom oko poljane.|Daæu ti prednost.
{42669}{42704}Hajde!
{42831}{42906}Kad planiraš da otvoriš izložbu?
{42914}{42977}Dosta zavisi kad æemo dobiti |poslednje primerke iz inostranstva.
{43011}{43056}- Rekao bih oko Uskrsa.|- Dobro.
{43179}{43229}Hoæeš li praviti |roðendansku proslavu za Marka?
{43252}{43324}- Znaš dobro da hoæu. Hoæe li jezero biti zaleðeno?|- Ponesi klizaljke.
{43488}{43575}- Doneo sam odluku u vezi tvog izveštaja.|- Neka da...
{43582}{43636}Prešao sam na stranu Bila Atertona.
{43668}{43696}Da...
{43728}{43809}Mislim da bi bilo prerano da se|upustimo u tako radikalan program.
{43819}{43868}Ne bih želeo da rizikujem pre vremena.
{43889}{43932}- Držaæemo na ledu?|- Dobro.
{44088}{44153}Rièarde, ako misliš |da sam otišao predaleko,
{44182}{44258}ako æe  se nastaviti Bilov antagonizam|prema meni, možda treba da se povuèem.
{44296}{44364}Zaboravi. Tvoje vreme dolazi.
{44610}{44667}- Izgleda kao da æe padati kiša, Marej.|- Možda, gospodine.
{44677}{44714}- Idemo.|- Gdine Torn!
{44733}{44793}Žao mi je što vièem,|nisam htela da vas propustim.
{44800}{44875}Moje ime je Džoan Hart.|Verujem da vam je Èarls Voren prièao o meni.
{44884}{44917}- Jeste.|- Moram da prièam sa vama.
{44926}{45012}- Pa, zamolio sam ga da...|- Ledeno je. Možemo li da sednemo u vaša kola?
{45020}{45074}- Pa...|- Znam da ne prièate sa novinarima...
{45083}{45125}- Idem na aerodrom.|- Dva minuta.
{45133}{45156}- Pa...|- Molim vas?
{45163}{45210}- Ne mogu da propustim avion. Sada, ako...|- Idem na aerodrom sa vama.
{45309}{45344}U redu, upadajte.
{45659}{45743}U redu, gðice Hart. Vreme nam je kratko,|onda, šta biste voleli da znate?
{45765}{45818}Da li ste ikada sreli |arheologa Karla Bugenhagena?
{45857}{45950}- Ne. Èuo sam za njega.|- On je bio i isterivaè duhova. Da li ste znali to?
{45963}{45988}Ne.
{45998}{46044}Njegov kostur je pronaðen prošle nedelje na vašim |iskopinama kod Hazora, blizu Jigaelovog zida.
{46052}{46152}Sedam godina posle njegovog nestanka.
{46169}{46294}Novinarska pretpostavka. |Kostur nikada nije potvrðen kao njegov.
{46301}{46351}Ali jeste!|Upravo dolazim odande.
{46382}{46445}Vaš brat se sreo sa njim. |Da li znate zašto?
{46460}{46498}Odakle vam ta informacija?
{46514}{46608}Fotograf sa kojim sam radila|je išao sa vašim bratom. Poginuo je tamo.
{46628}{46722}- Odseèena mu je glava.|- Marej, zaustavi auto.
{46730}{46820}Vaš brat je išao da vidi Bugenhagena.|Nekoliko dana kasnije, on je nestao!
{46832}{46903}- Izaðite!|- Da li znate zašto je išao da se vidi sa njim?
{46910}{46947}Nemojte da vas |izbacujem, gðice Hart.
{46956}{47032}Morate me saslušati.|Radim na toj prièi veæ godinama!
{47041}{47075}Mislim da sam je pohvatala.
{47098}{47146}Nikada ranije nisam |verovala u prorèanstva iz Biblije.
{47154}{47235}Ali sada, vi ste u smrtnoj opasnosti!
{47243}{47329}- Nemojte nikada više da me kontaktirate!|- Uzdajte se u Hrista!
{47342}{47383}Samo vas On može spasti.
{47392}{47453}Molim vas, molim vas!|Morate me saslušati!
{47463}{47517}Molim vas, molim vas!|Morate me saslušati!
{47528}{47595}Bugenhagen je |upozorio vašeg brata!
{47616}{47639}Bože...
{47728}{47814}I upravo prošle nedelje |smo otkrili Jigaelov zid.
{47832}{47904}- Ko je Jigael?|- Neverovatna osoba. Veoma misteriozna.
{47914}{48018}Nismo sasvim sigurni. Bio je kaluðer, |isterivaè duhova. Živeo je oko 13. veka.
{48029}{48112}Prièa ide da se Satana |lièno pojavio Jigaelu,
{48120}{48183}koji je, potpuno oèekivano,|poremetio.
{48194}{48265}Takoðe se krio,|opsednut slikom koju je video:
{48274}{48373}neverovatna vizija Antihrista,|od roðenja do pada.
{48400}{48452}Ali razlog zašto ne želim |da išta kažete Rièardu je,
{48483}{48542}želim da to bude poklon.|- Dobro.
{48551}{48594}Imam iznenaðenje |i za vas, takoðe.
{48619}{48721}Vaš omiljeni komad.|Staviæemo ga taèno u sredinu galerije broj 4.
{48731}{48786}Mislim da bi trebalo da je |naslonite na jedan od sporednih ulaza!
{48809}{48890}- Èarlse.|- Džoan! Kada si ušla?
{48901}{48967}- Sinoæ,|- Izvini me, An. Ovo je Džoan Hart, koja...
{48978}{49053}- Koja je htela da intervjuiše Rièarda.|- I intervjuisala sam ga.
{49060}{49104}- Šta si uradila?|- Ne prihvatam ne kao odgovor.
{49114}{49174}- Bilo je suviše važno.|- Mora da si jako ubedljiva.
{49183}{49235}Nema visoko mišljenje o reporterima.
{49312}{49348}Izvinite, imam poziv.
{49450}{49555}Vaš muž je malo nefer prema štampi.|Bili su jako dobri za njegovog brata.
{49562}{49619}Zaista?|Nikad nisam znala njegovog brata.
{49634}{49696}Tako je!|Vi ste druga žena Rièarda Torna.
{49712}{49769}Recite mi za Demijena.|Kakv je on deèak?
{49778}{49822}- Da li voli život na vojnoj akademiji?|- An!
{49833}{49956}- Ne prièaj ništa. Rièard je besan!|- Èarlse, ti si u opasnosti! Svi vi!
{49977}{50028}- Šta je to ušlo u tebe?|- Videla sam Jigaelov zid.
{50036}{50085}- Nije me briga šta si videla.|- Moraš ga videti! Demijen...
{50103}{50154}Šta sa Demijenom?
{50209}{50248}Nisam još sigurna.
{50394}{50432}Oko èega sve to?
{51993}{52087}- Koji je Demijen Torn?|- On je onaj široki primaè tamo preko.
{52150}{52181}Odmori se.
{52594}{52636}...koji vladaš na nebu,
{52646}{52700}blagosloveno ime tvoje,
{52708}{52751}i kraljevstvo tvoje.|Tako æe biti, na nebu...
{53292}{53360}- Ne! Ne! Šta...
{53493}{53586}Hajde. Molim... |Šta je ovo?
{53757}{53791}Molim te.
{53826}{53863}Oh, Bože.
{55075}{55130}Pomozite mi! Ne!
{55386}{55457}Pomozite mi!
{57711}{57736}Hej, tata!
{57990}{58042}To nije pošteno. |Sada æeš dobiti!
{58722}{58767}Ura!
{58777}{58844}- Poželi želju i duni u sveæice.|- Hajde, Mar. Oduvaj ih!
{58883}{58916}Sve, Mark.
{59010}{59037}Èekaj, Mark.
{59085}{59120}Iseci tortu.
{59162}{59218}- Poželi želju!|- Veæ je poželeo.
{59228}{59263}- Oh, evo jezera.
{59415}{59478}Oh, Pole. Zaista želim da znam
{59487}{59551}kako si rešio da odložiš|tvoj projekat akvizicije zemljišta.
{59574}{59630}Pa... to može biti u najveæem| interesu za kompaniju, Bile.
{59642}{59692}Ali još uvek ne razumem |tvoje protivljenje.
{59705}{59761}Samo zato što nikad nije |raðeno, ne znaèi da je nelegalno.
{59786}{59804}Ne.
{59823}{59860}Ali da li je etièki?
{59994}{60037}- Eto je.|- Hvala.
{60046}{60086}- Uzmi viljušku, dušo.|- U redu.
{60098}{60121}Hvala.
{60342}{60423}- Kako ide na akademiji, Demijene?|- U redu, gdine Buher.
{60431}{60462}A narednik Nef?
{60471}{60514}- Da li ga znate?|- Pitali su me za njega.
{60559}{60603}Samo vodim raèuna |o tebi, Demijene.
{60619}{60674}Da li znaš taèno šta |ja radim za Torn industriju?
{60693}{60744}- Ne skroz, gospodine.|- Pa, trebalo bi.
{60758}{60846}Trebao bi da znaš sve o planovima Torn |industrije, biæe tvoje jednog dana.
{60869}{60902}I Markovo.
{60918}{60966}I Markovo. Naravno.
{60984}{61064}Tako, zašto ti,|ne posetiš fabriku?
{61086}{61148}- Mogu li da povedem i neke prijatelje?|- Naravno.
{61158}{61201}Mogu li imati vašu pažnju?
{61224}{61265}Slušajte, svi!
{61281}{61369}Pre nego što Mark otvori svoj poklon,|imam iznenaðenje za vas,
{61378}{61423}tako da želim da me pratite.
{62347}{62414}13. roðendan se smatra od mnogih|kao poèetak puberteta, muškosti.
{62425}{62567}Mnoge kulture imaju, obrede incijacije.|I ti æeš proæi to Demijene.
{62593}{62728}Da...Vreme je došlo da odložiš deèje stvari|i da se suoèiš sa tim ko si.
{62760}{62833}Veliki trenutak, Demijene.|Sigurno ga oseæaš?
{62857}{62902}Mislim da da.
{62934}{62971}Nisam siguran.
{62994}{63109}Ali oseæam da mi se nešto dešava.|I da æe se desiti.
{63123}{63184}Sumnje o sudbini. Svi ih imamo.
{63204}{63251}Tvoj stric je imao, siguran sam.
{63260}{63307}I Bil Aterton. I ja.
{63346}{63447}Duboko poznanje bez reèi|da naše vreme dolazi.
{63530}{63577}Hej, Demijene, hajde! Imamo vatromet!
{64121}{64162}- Oh, pogledaj ovo!
{65317}{65342}Pucaj!
{65668}{65742}- Oh! Èarlse!|- Ne mogu da stanem.
{65787}{65840}Devojèica mi je oèitala lekciju,|ali je postala odvratna.
{65864}{65899}Šta bi želeo?
{65910}{65983}- Hot dogove, hamburgere, rebarca?|- Sve. Umirem od gladi.
{65993}{66051}- Zašto ne odeš u šator za zagrevanje?|- I hoæu.
{66076}{66164}Èarlse... Èula sam tvoju prijateljicu reporterku.|Kako joj beše ime?
{66173}{66219}- Džoan Hart.|- Jako mi je žao.
{66231}{66334}Da... bilo je èudno,|da je udari kamion na napuštenom putu.
{66344}{66374}Znam.
{66454}{66485}- Evo.|- Hvala ti.
{66711}{66736}Pucaj!
{67618}{67645}Ne.
{67798}{67862}- Bile!|- Tata!
{67875}{67917}- Bile!|- Ostani van leda!
{67927}{68002}Drži se!
{68016}{68055}- Ko je to?|- Gdin Aterton.
{68068}{68132}Drži se, Bile!|Neka neko uzme motku.
{68182}{68231}Oh, Bože! Nestao je!
{68311}{68382}- Ovde je!|- Struja ga je ponela!
{68475}{68557}- Izgubili smo ga!|- Raširite se, svi!
{68564}{68620}- Da li ga iko vidi?|- Evo ga!
{68639}{68702}Hajde! Hajde! |Nestao je.
{68717}{68775}- Tata, šta da radimo?|- Evo ga ovde!
{68799}{68851}- Neka neko uzme sekiru!|- Bože!
{68957}{68996}Uhvatila ga je plima.
{69038}{69092}- Tata!|- Koliko može da izdrži ispod?
{69102}{69138}Mrda se!
{69198}{69240}Pomerite se, svi!
{69333}{69369}Gdine Torn!
{69435}{69473}- Brzo!
{69518}{69577}Drži se.|Uhvatiæemo te.
{69638}{69694}Raširite se! |Svi se raširite!
{70500}{70551}Rièarde... uskoro odlazim.
{70590}{70658}Pa, Pole, tvoje vreme je |stiglo ranije nego što smo mislili.
{70692}{70761}Biæeš usamljen na mestu |predsednika neko vreme,
{70774}{70825}jer An i ja idemo na odmor.
{70907}{70973}Ne brini, Rièarde.|Mislim da smo sve pokrili.
{71008}{71061}Hvala ti što si ostao |tu ovih nekoliko dana.
{71084}{71124}Cenim to.
{72208}{72273}- Jutro, Bajrone.|- Na naslovnim stranama ste ovoga jutra!
{72285}{72347}Oh, verovatno ste to veæ videli.|Mislim da je zgodno.
{72373}{72456}- Jeste li èuli od Pasarijana?|- Ne. Izgleda kao da je nestao.
{72476}{72533}- Rièard želi da vas vidi.|- Vratio se sa odmora?
{72545}{72592}- Da, i izgleda odlièno, pritom.|- Trebalo mu je to.
{72655}{72714}Kog ðavola Pasarijan radi u Indiji?
{72727}{72795}Trebalo mi je mišljenje još nekoga|oko kupovine naše zemlje tamo.
{72805}{72850}Zar veæ kupujemo?
{72869}{72944}Složio si se da mogu da aktiviram|zakljuèke iz mog izveštaja u potpunosti.l
{72953}{73075}To me ne izostavlja iz donošenja| odluka što se tièe kompanije!
{73088}{73155}- Bio si na odmoru.|- Mogao si da me zoveš telefonom!
{73172}{73226}Bil Aterton ne bi |doneo takve odluke!
{73236}{73312}- Ja nisam Bil Aterton.|- I ne oèekujem da budeš.
{73329}{73417}Ali oèekujem da posluješ |po pravilima voðenja kompanije!
{73511}{73547}Zapamtiæu to.
{73721}{73765}Za šta ti treba Pasarijan?
{73779}{73889}Nešto nije u redu u dizajnu njegove| P-84 jedinice. Voker je uzrujan.
{73902}{73985}Znam da je on glas propasti i užasa,|ali ovaj put ima pravo.
{73996}{74027}Prepusti to meni, Rièarde.
{74141}{74211}U ovo vreme, Napoleon je |mislio da je nepobediv,
{74223}{74288}i tada je napravio |svoju veliku grešku.
{74297}{74358}Kada je napao, Rusi su se |spretno povukli u svoju zemlju.
{74367}{74462}Navukli su ga, i došao je do |Moskve, koju je našao u ruinama.
{74535}{74573}Ko se smejao?
{74614}{74655}Ja, gospodine.
{74663}{74692}Ti?
{74706}{74739}Doði ovamo.
{74804}{74846}Sa tim komadom papira.
{74871}{76371}-== [ www.OpenSubtitles.com ] ==-
