{1}{1}23.976
{26}{176}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{6940}{7020}Pripremite se za poruku od Diantusa...
{7025}{7155}...predsednika Zemlje i rotacionog|premijera SunËevog sistema.
{7428}{7487}- Barbarela?|- G. PredsedniËe.
{7586}{7633}- Ljubav!|- Ljubav!
{7667}{7704}Samo trenutak. Da obuËem neöto.
{7708}{7786}Nemoj da se muËiö...|Ovo su drûavna posla.
{7791}{7890}Ovo öto moram da kaûem je|izuzetno... To je tajna.
{7894}{7927}Tajna?
{7950}{8063}Da li si Ëula za mladog|nauËnika Duran Durana?
{8068}{8148}- Jesam.|- On je na putu ka SevernjaËi...
{8153}{8231}...nestao u neistraûenoj|okolini Tau Kite.
{8236}{8279}Ali... zaöto je to tajna?
{8284}{8391}Zato öto je Duran Duran|pronalazaË Pozitronskog zraka.
{8396}{8482}- To je oruûje.|- Oruûje?
{8517}{8568}Zaöto bi neko hteo da izmisli oruûje?
{8572}{8611}Otkud bih ja znao?
{8658}{8722}Univerzum je vekovima bio miran, ser.
{8726}{8870}Koliko mi znamo. A ipak, ne znamo|niöta o Tau Kiti i njenim stanovnicima.
{8874}{8941}Da li bi oni mogli joö uvek da budu u|primitivnom stanju neurotiËne neodgovornosti?
{8945}{9068}TaËno. I ako oni od ovog|mladog nauËnika nauËe...
{9073}{9134}...tajnu Pozitronskog zraka...
{9139}{9264}...mogli bi da razbiju|divno jedinstvo univerzuma.
{9279}{9404}- To bi znaËilo starinsku nesigurnost...|- I rat.
{9426}{9531}- Misliö sebiËno takmiËenje i...|- Mislim rat.
{9536}{9633}- Krvavi sukob meu celim narodima.|- Ne mogu da verujem.
{9637}{9719}Ni ja. Ali ne smemo da rizikujemo.
{9748}{9861}- Moramo neöto da preduzmemo.|- Da. Ti si devojka koja to mora da uradi.
{9865}{9974}- Zaöto ja?|- Nemam ni vojsku ni policiju.
{9979}{10168}Ne mogu da odvojim predsedniËki odred.|Plus, ti si Astro-Navigatriks sa 5 zvezdica.
{10172}{10279}Tvoj zadatak je: Nai Duran Durana...
{10284}{10397}...i upotrebi svoje neuporedive|talente da oËuvaö sigurnost zvezda...
{10401}{10475}...i naöe rodne planete. Kako me pratiö?
{10479}{10615}- Dobro.|- Evo jedine postojeÊe Duranove slike.
{10631}{10738}26 godina. Kestenjaste|oËi. PriliËno zgodan deËko.
{10828}{10873}Nisam sigurna da Êu uspeti|da ga prepoznam, ser.
{10877}{10978}Dobro, ovo je prenosni|detektor moûdanih talasa.
{11054}{11188}Paûnja... Podesi svoj|prenosnik atoma na 0-3-5.
{11218}{11298}- Sreeno.|- Objekat u prenosu.
{11334}{11381}Objekat primljen.
{11385}{11521}Da bi ispitala prisutnost Duran|Durana, samo pritisni ovaj kontakt.
{11526}{11664}- UpaliÊe se svetlo. OglasiÊe se alarm.|- Ima ugraenu jeziËku kutiju.
{11719}{11778}Evo neËega öto bi moglo da ti zatreba.
{11871}{11941}- To je oruûje?|- Za samooËuvanje.
{11945}{12019}Pozajmili smo ga iz Muzeja Sukoba.
{12053}{12141}To je moja curica. Jednom, Barbarela...
{12145}{12213}...moramo da se naemo uûivo.
{12255}{12318}Hvala ti. I...
{12333}{12366}...ljubav!
{12384}{12419}Ljubav!
{12508}{12586}Naoruûana... Kao goli divljak.
{13112}{13186}Alfa 7 Bazi... Alfa 7 Bazi.
{13200}{13330}Napuötamo oblast SunËeve|gravitacije za 7 minuta. Potvrdite.
{13350}{13405}Baza Alfi 7. Potvreno.
{13460}{13532}Spremite se za ubrzavanje|u vreme-svemir.
{13536}{13635}Ubrzavanje u vreme-svemir...|Kontinuum kreÊe sada.
{13897}{13975}Alfi, kada stiûemo u|gravitaciono polje Tau Kite?
{13979}{14104}154 sata, sedam minuta,|prema zemaljskom vremenu.
{14109}{14142}Dobro.
{14271}{14384}- Probudi me za 154 sata.|- Potvreno.
{14425}{14511}- Laku noÊ, Alfi.|- Potvreno.
{15443}{15525}Usporavanje izgleda u redu...
{15541}{15652}Barbarela na noge lagane.
{15819}{15901}Spremi se za unos hrane.
{16159}{16293}Zavröetak kursa u vremenskom|ubrzanju kroz 7 sekundi.
{16314}{16379}Alfi... To je Tau Kita.
{16514}{16604}- äta se deöava?|- Magnetne smetnje.
{16693}{16744}Magnetne smetnje?
{16874}{16921}Sistemi za opasnost!
{17035}{17123}Svi sistemi za opasnost Êe sada da rade.
{17249}{17412}- Naöi magnetni ötitovi ne rade!|- Snaga magnetnog uragana je 11.9.
{17416}{17566}éiro kompas je neispravan,|ponavljam, neispravan.
{17571}{17655}- Kaûeö da ne moûeö da upravljaö?|- To je taËno.
{17659}{17753}PrebaciÊu na ruËno. Kakve su nam öanse?
{17784}{17848}Naöe trenutne öanse za ne-uniötenje...
{17852}{17982}...su 0,00002 prema 10.000.
{18211}{18310}Moj stabilizator br. 2 je oöteÊen.
{19787}{19931}- Gde sam?|- To sam ja sam htela da pitam tebe.
{19965}{20117}Planeta 16 u sistemu Tau|Kita. Gustina vazduha 0,051.
{20122}{20208}Hladno vreme sa moguÊnoöÊu|olujnih padavina.
{20212}{20333}Analiza atmosfere: zemaljska|sa blagim viökom kiseonika.
{20337}{20466}Prebrojao sam 600.324|molekula po kubnom milimetru.
{20470}{20525}Pa, barem Êu moÊi da diöem.
{21660}{21738}Kakve Ëudesne male devojke! Zdravo!
{21793}{21842}Govorite li Engleski?
{21929}{21986}Parlez-vous franÁais?
{21991}{22091}»ekajte, samo da podesim moju jeziËku|kutiju. Mora da je GalaktiËki dijalekt 5.
{23207}{23260}Ali ja se nisam skijala godinama!
{24217}{24301}Pa to je Duran Duranov svemirski brod!
{24608}{24645}Zdravo!
{25166}{25277}Sluöajte, deco, ovo je zabavna|igra ali je otiöla predaleko.
{25281}{25406}NeÊu da vas povredim. HoÊu da|saznam neöto o ovom svemirskom brodu.
{25425}{25497}Hajde, odveûi me ili Êu|da pozovem tvoje roditelje.
{25633}{25678}To je baö slatko, ali ja...
{26217}{26256}Ne!
{26933}{26966}UpomoÊ!
{26988}{27021}UpomoÊ!
{27160}{27193}Stanite!
{29201}{29234}Zdravo!
{29356}{29389}Hvala vam!
{29456}{29489}Ne!
{29615}{29654}Ne razumem.
{29686}{29745}Parlez-vous franÁais?
{29799}{29856}Bolje podesi moju jeziËku kutiju.
{29968}{30001}Da li si dobro?
{30039}{30117}Mislim da jesam... Ko ste vi?
{30135}{30227}Ja sam Mark Hend, hvataË. A ko si ti?
{30231}{30354}Ja sam sa planete Zemlje. Kaûi mi|öta znaö o ovom svemirskom brodu.
{30358}{30506}Ne znam niöta. Bio je ovde kad|sam prihvatio posao hvataËa.
{30511}{30644}- Posao hvataËa?|- Da. Sva deca ûive ledenoj Brani...
{30648}{30728}...dok ne dostignu upotrebljiv uzrast.
{30732}{30833}- Upotrebljiv?|- Onda ih hvatam kao öto si videla.
{30837}{30933}- Predajem ih vlastima.|- Razumem.
{31010}{31113}Hvala ti. Da li si|Ëuo za ime Duran Duran?
{31118}{31272}Ne znam niöta. éivim sam na ledenoj|brani. Takav je ûivot hvataËa.
{31330}{31418}Tek Êeö u Sogou naÊi|odgovor na tvoje pitanje.
{31423}{31513}- Sogo? Da li je blizu?.|- Odmah iza onog ledenog zida.
{31698}{31786}Da li sam tvoj svemirski brod|video na daljem kraju ovog jezera?
{31790}{31859}Da, ali se bojim da je pokvaren.
{31863}{31947}- Magnetna oluja mi je uniötila stabilizator.|- Moûda ja mogu da pomognem.
{31952}{32137}PriliËno sam iskusan mehaniËar.|Popravljam i odrûavam ovaj ledobrod.
{32176}{32283}- Ako hoÊeö, odveöÊu te do tvog broda.|- Ali, nema vetra.
{32309}{32345}SaËekaj.
{32590}{32643}- Kakva ljupka kabina!|- Vetar.
{33106}{33196}Toliko sam ti zahvalna na pomoÊi.|Kako bi mogla da ti se zahvalim?
{33201}{33291}Sigurna sam da Êe ti|se moja Vlada oduûiti.
{33296}{33409}Ako ima neöto öto bih ja|mogla da uradim, samo reci.
{33413}{33495}Mogla bi da me pustiö|da vodim ljubav sa tobom.
{33500}{33564}- Da vodimo ljubav?|- Da.
{33568}{33652}Ti Ëak i ne znaö moj psiho-kardiogram.
{33692}{33739}Na Zemlji, ljudi ne vode ljubav...
{33743}{33864}...ukoliko njihovi psiho-kardiogrami|nisu u savröenom slivu.
{33869}{33968}Pitala si öta bi mogla da uradiö|za mene. I ja sam ti rekao.
{33972}{34058}Dobro. Samo ne vidim neku vajdu od toga.
{34063}{34106}- Da li imaö pilule?|- Pilule?
{34126}{34245}- Nema veze, imam ja neöto.|- äta je ova pilula?
{34286}{34360}Pilula za prenos ushiÊenja, naravno.
{34365}{34430}- Nisam Ëuo za to.|- Razumem.
{34434}{34551}Na Zemlji, kada su naöi psiho-kardiogrami|u skladu za voenje ljubavi...
{34556}{34607}...uzmemo pilulu za prenos ushiÊenja.
{34611}{34680}I ostanemo ovako. Evo, pokazaÊu ti.
{34704}{34780}Na minut ili dok se|ne dostigne pun odnos.
{34986}{35124}Baö me briga za to. Mislio|sam na ovo... krevet!
{35188}{35290}To? Ali to niko nije radio vekovima!
{35294}{35378}Osim sirotog mene koji ne moûe da|priuöti pilulu i psiho-kardiograme.
{35383}{35513}- äto ne?|- SpreËava maksimalno dejstvo.
{35517}{35653}Sada su takoe dostupni i supstituti|za podröku ega i samopoötovanje.
{35658}{35796}- ZnaËi, neÊeö?|- Ako insistiraö, mislim da ne.
{35813}{35901}Ali stvarno nema svrhe raditi to ovako.
{36041}{36131}- Bez odeÊe, molim.|- Oh.
{37467}{37547}Sada Êu da pogledam tvoje stabilizatore.
{37678}{37813}Poöto je tvoja odeÊa pocepana,|posluûi se mojim krznima, Barbarela.
{39419}{39547}Mislim da sam naöao nevolju.|Sada moûeö da nastaviö za Sogo.
{39551}{39684}Tamo Êeö naÊi Duran Durana|mlaeg. Ako je joö ûiv...
{39709}{39742}Dobro.
{39782}{39862}Sad, Barbarela, zar|se ne slaûeö samnom...
{39867}{39969}...da su za neke stvari,|starinski naËini najbolji?
{39991}{40093}äta...? A, to.
{40097}{40187}Da, moram da priznam da|je bilo stvarno zanimljivo.
{40191}{40254}Ipak, zbunjujuÊe je.
{40258}{40381}- Da li Êeö samnom u Sogo?|- Ne, viöe volim spokojstvo Brane.
{40386}{40457}Sogo je previöe strog,|ljudi su previöe rezervisani.
{40461}{40580}Moûda ponovo svratiö ovde...|kad obaviö svoj zadatak.
{40584}{40653}Da, moûda i hoÊu...
{40696}{40768}Pa, zdravo. I hvala joö jednom...
{40814}{40857}Na svemu.
{40861}{40920}Bilo mi je zadovoljstvo.
{41047}{41166}- Molim izvestite o vaöem stanju.|- Ne bi razumeo.
{41596}{41692}- Stabilizator neispravan.|- Popravljen sam naopako.
{41721}{41792}Ulazimo. AktiviraÊu zemaljsku elisu.
{42340}{42391}Barbarela!
{42423}{42484}Barbarela!
{42515}{42587}Puna operativna snaga|svih podzemnih sistema.
{42783}{42836}Nagib od 45 stepena.
{42884}{42927}Povröina je blizu.
{43701}{43768}Moram da se reöim ovog repa.
{45531}{45590}- Mrtva sam.|- Nisi.
{45723}{45824}- Gde sam?|- U lavirintu NoÊnog Grada.
{45828}{45937}- Da li si ti aneo?|- Ja sam Pajgar, poslednji ornitantrop.
{45989}{46083}- Kako si?|- A ti?
{46112}{46198}Ja sam sa Zemlje. Zovem se Barbarela.
{46236}{46355}Ali ti si meka i topla. ReËeno|nam je da su zemaljska biÊa hladna.
{46360}{46396}Nismo svi...
{46427}{46507}Jadan moj svemirski brod. Vidi ga.
{46560}{46593}Vrlo mi je ûao.
{46631}{46697}Pajgare, öta se desilo tvojim oËima?
{46701}{46783}Pao sam tokom magnetne|oluje i odneli su me u Sogo.
{46787}{46821}Sogo?
{46825}{46926}NoÊni Grad pod upravom Velikog|Tiranina. Tamo su me oslepili.
{46930}{47020}Ostavili su me da umrem u lavirintu|ali me je profesor Ping naöao.
{47025}{47068}To je uûasno.
{47166}{47238}Da li stvarno moûeö da letiö?
{47242}{47299}Ne, izgubio sam volju za letenjem.
{47303}{47412}- Kako straöno!|- Viöe nije vaûno. To je proölost.
{47417}{47557}- Da li si Ëuo za Duran Durana?|- Duran Duran?
{47561}{47658}Da, Duran Duran. On|je astronaut sa Zemlje.
{47662}{47727}Ne znam za takve stvari.
{47781}{47869}- Moûda Profesor Ping moûe da pomogne.|- Profesor Ping?
{47873}{47947}On je vrlo mudar i zna sve o Sogou.
{47952}{48057}- Gde mogu da ga naem?|- On je sa ostalima, jedu.
{49719}{49838}- Eno ga tamo. Profesore Ping?|- Profesore Ping?
{49843}{49911}- Da?|- Zovem se Barbarela.
{49947}{50041}Reci mi. Odakle potiËeö?
{50095}{50272}Posedujeö izgled zemljanina.|Ti si ûenskog pola, taËno?
{50277}{50326}TaËno.
{50384}{50445}- Da li je to orhideja?|- Jeste.
{50450}{50575}Orhideje su slabe hranljivosti|i teöko se uzgajaju u ovoj klimi.
{50579}{50721}Velikog Tiranina zabavlja da se ljuti|zbog izdataka za ishranu robova orhidejama.
{50751}{50914}- Kakvo je ovo mesto?|- To je Sogo, NoÊni Grad...
{50918}{51027}...pod upravom Velikog Tiranina|i posveÊen svim oblicima zla.
{51031}{51103}A ovo je lavirint.
{51107}{51216}Svi koji nisu zli,|proterani su u lavirint.
{51235}{51280}Gledaj!
{51518}{51627}- Ko je taj dûentlmen?|- To je Grand Grotesque.
{51632}{51728}To je uobiËajen naËin|zavröetka ûivota u lavirintu.
{51814}{51941}Profesore Ping, da li ste|ikada Ëuli za Duran Durana?
{51971}{52098}Duran Durana sa Zemlje? Jesam, svakako.
{52102}{52201}- On je ûiv? Gde?|- U Sogou, bez sumnje.
{52205}{52262}Moram odmah da odem tamo.
{52291}{52406}Ali, kao öto si videla, niko|ne moûe da napusti lavirint.
{52410}{52533}- Imam svemirski brod, joö da je ispravan.|- Dete moje, moûda mogu da ti pomognem.
{52538}{52643}O, kada biste mogli...|Ja Êu da vas odvedem tamo.
{52648}{52715}Pajgare, hoÊeö li da nam pokaûeö put?
{53544}{53680}- U Ëemu je problem?|- Mislim da su stabilizatori.
{53685}{53730}Hajde da pogledamo.
{53913}{53964}Pajgare, olovku...
{54038}{54114}- Evo.|- Hvala ti.
{54160}{54240}Hvala Bogu da hipodontiËni|molekuli nisu oöteÊeni.
{54245}{54372}- Da li Êe dugo da potraje?|- Sati? Dani? Nedelje?
{54376}{54413}Ko zna?
{54417}{54486}Geniji su tajanstveni.
{54490}{54556}Ne moûe da traje nedeljama.
{54605}{54638}Pajgare?
{54686}{54784}- Moûeö da me odneseö do tamo.|- Ne, ne mogu.
{54788}{54845}Atrofija veÊeg krilnog miöiÊa.
{54850}{54932}Aneo je aerodinamiËno biÊe.
{55002}{55074}To je pitanje morala.
{55189}{55323}Ostaje samo da Ëekamo.|Pajgare, gde ûiviö?
{55352}{55428}Hajde. ObjasniÊu ti kako da me vodiö.
{55583}{55665}- Samo napred.|- To je gnezdo.
{55691}{55792}- Pa, jeste. Tu ûivim.|- »udesno je.
{55832}{55877}Drago mi je da ti se svia.
{55964}{56025}»ekaj! Dolaze.
{56251}{56289}UpomoÊ!
{56347}{56383}Pajgare, ravno pred tobom.
{56440}{56511}Pajgare, ne, na desno.
{56515}{56554}Sada!
{56807}{56942}- äta je to?|- Jedan iz Crne Garde Velikog Tiranina.
{56946}{57086}- Unutra nema niËega.|- Ne, Crni Gardisti su koûnjaci.
{57090}{57162}Ne sadrûe mesnatu tvar.
{57222}{57289}Pajgare, spasio si mi ûivot.
{57817}{57856}Pajgare?
{57892}{57966}Pajgare... O, Pajgare!
{57971}{58020}Paûljivo!
{58058}{58103}O, Pajgare!
{58183}{58236}Zanimljiva terapija!
{58541}{58629}- Vratila mi se volja za letenjem.|- Znam.
{58657}{58745}O, to je bilo... Bilo je prosto nebeski.
{58773}{58865}- Moûeö li da me odvedeö u Sogo?|- Ali ja ne vidim.
{58869}{58955}- Ja Êu biti tvoje oËi, Pajgare.|- Ne verujem da je to moguÊe.
{58959}{59035}OboriÊe nas patrole Crnih Gardista.
{59039}{59115}Uz pomoÊ mog lansera|mini-projektila, neÊe.
{60232}{60324}- Da li si dobro, Pajgare?|- Jesam, hvala ti.
{60853}{60886}Ne svia mi se kako ovo izgleda.
{61396}{61435}Malo nadesno.
{61713}{61747}Pajgare, pazi!
{61929}{61967}Imam ga!
{62052}{62101}Nadesno!
{62814}{62888}Gore, Pajgare, gore...
{63215}{63270}Moûemo da se sakrijemo iza te planine.
{63384}{63419}Pajgare!
{63554}{63590}Pajgare!
{64339}{64396}- Da li si dobro?|- Jesam.
{65083}{65164}U pravom trenutku. Energetska|kutija mi je skroz prazna.
{65167}{65210}Da li smo sada dobro?
{65242}{65323}Valjda. Izvini.
{65598}{65678}Stigli smo! TaËno je ispod nas.
{65683}{65761}Moramo da se spustimo u sporednu|ulicu, za tvoju sigurnost.
{65766}{65848}Da te u Sogou vide sa|anelom bila bi anatema.
{65969}{66033}Pajgare, sagni glavu.
{66773}{66913}Jao, sigurno imamo neöto|da sakrijemo tvoja krila.
{67405}{67450}»ekaj, Barbarela!
{67618}{67719}- Ne plaöi se, Pajgare.|- OseÊam opasnost. Pazi se.
{67779}{67865}Nema niËega. ObeÊavam ti. Doi!
{68478}{68525}Barbarela!
{68529}{68580}Pajgare, Ëekaj me!
{68629}{68684}äta hoÊeö od mene?
{68743}{68776}Oh!
{68995}{69067}Zdravo, lepa-lepa.
{69118}{69151}Zdravo.
{69269}{69304}Hvala veliko.
{69308}{69392}HoÊeö da doeö da se igraö samnom?
{69396}{69472}Za nekoga ko izgleda kao|ti ne naplaÊujem niöta.
{69584}{69656}Ti si vrlo lepa, lepa-lepa.
{69661}{69733}Ne zovem se "Lepa-Lepa".|Zovem se Barbarela.
{70115}{70230}- Da li si negde videla anela?|- »udnu pticu?
{70234}{70267}Da.
{70506}{70567}Kakvi su to vriskovi?
{70571}{70655}Dobra veÊina dramatiËnih|situacija poËinje vriskom.
{71234}{71271}Pajgare!
{71539}{71572}Jadni Pajgar...
{71862}{71938}Pajgare, idi unazad. Iza tebe je soba.
{72346}{72401}Ne prate nas.
{72454}{72519}Pajgare, doi.
{72569}{72626}Kaûi mi öta to znaËi.
{72639}{72744}"Komora KonaËnog...
{72827}{72872}...Reöenja".
{72876}{72923}Ne svia mi se kako to zvuËi.
{73066}{73119}Bolje da se gubimo odavde.
{73197}{73266}Vi koji odabraste smrt, dobrodoöli.
{73270}{73408}Da okonËate gorËinu ûivljenja,|moûete odabrati meu tri uzbudljiva...
{73412}{73480}...i iznenaujuÊa oblika umiranja.
{73484}{73597}Po jedan vas oËekuje iza svakih|od vrata koja vidite pred sobom.
{73601}{73731}Ako ne odaberete, biÊete|predati Matmosu. Nema ûalbi.
{73771}{73820}SledeÊe reöenje.
{74475}{74536}SledeÊe reöenje.
{74540}{74589}Bolje da rizikujemo.
{74952}{74999}»ekaj!
{75236}{75302}Hvala veliko.
{75331}{75384}Morate da poete samnom.
{75456}{75530}Kako se zoveö? äta radiö u ûivotu?
{75535}{75603}Ja sam domar Velikog Tiranina.
{75607}{75701}- »estitam na izboru trenutka.|- Nisam ja.
{75706}{75805}- To je odredio Veliki Tiranin.|- Razumem.
{75809}{75893}Kakva je to uûasna stvar ispod poda?
{75952}{76046}- To je Matmos, dete moje.|- Matmos?
{76051}{76137}Ti si stvarno sa Zemlje. Ne shvataö.
{76142}{76222}- Ne.|- Matmos...
{76226}{76318}Ceo grad je izgraen iznad jezera.
{76322}{76437}Veoma neobiËnog jezera. Sastavljenog|kao ti i ja od ûivuÊe energije...
{76441}{76502}...ali od energije u teËnom obliku.
{76507}{76562}I ono nas posmatra.
{76607}{76778}MagnetiËno je. Poöto je pozitivno naelektrisano,|napaja se negativnim psihiËkim vibracijama.
{76782}{76841}Koje bi ti nazvala "zlim".
{76846}{76998}Ono raste od zlih misli, dela i mesa.
{77003}{77081}Za uzvrat, daje nam|toplotu, svetlo i sam ûivot.
{77086}{77176}Ali, poseduje uûasan apetit.
{77196}{77268}Moûda Êeö videti nekom drugom prilikom.
{77293}{77334}Pajgare! Pajgare!
{77338}{77426}Ne brini. Uskoro Êeö ga videti.
{77430}{77499}Sad, molim poi ovuda.
{77524}{77645}Sedi. Bojim se da moraö|da uradiö kako kaûem.
{77717}{77764}Tamo, sedi.
{77789}{77863}Napred... Molim.
{78072}{78115}- O, Moksis...|- äta?
{78120}{78200}Vidi, Moksis. Zemljanka.
{78204}{78263}Uzmi je. Uzmi je sad.
{78268}{78391}Domar nas nikad neÊe pustiti. Uvek nam|pokvari zabavu. Hajde da ipak pokuöamo.
{78862}{78925}- Igraj se s nama, zemljanko.|- Moraö da se igraö s nama.
{78929}{79017}- Imamo puno lutaka.|- Boûe moj, öta one rade ovde?
{79022}{79106}Stomoksis i Glosina su|sestriËine Velikog Tiranina.
{79111}{79164}Na naöem dvoru ih oboûavaju.
{79169}{79228}- Zaöto ne sa nama?|- To nije fer.
{79232}{79308}- Prvo Veliki Tiranin, deco.|- Mi smo je prve videle.
{79313}{79414}- Budite dobre, devojke.|- Stomoksis, Glosina... ostanite uz mene.
{79875}{79945}I, moja lepa-lepa, sreÊemo se opet.
{80465}{80549}Ti...! Mala jednooka ûenska.
{80553}{80624}Imaö dobro pamÊenje, Lepa-Lepa.
{80628}{80739}Volim da ponekad izaem meu|moj narod... da budem kao oni.
{80744}{80845}UobiËajeno. Zlo, kako ga ti zoveö.
{80898}{80996}I, ja sam tvoja mala jednooka ûenska.
{81000}{81088}Takoe sam i Veliki Tiranin.
{81092}{81199}- Pa, lepo je to.|- Neizmerno me zabavlja.
{81204}{81315}ZnaËi, traûiö informacije|o odreenom Ëoveku, zar ne?
{81320}{81453}Da, ovde sam po nareenu|predsednika republike Zemlje.
{81457}{81587}- Doöla sam da naem Duran Durana.|- Ne mislim na njega, nego na anela!
{81591}{81681}- Pajgar?.|- Da, Pajgar.
{81686}{81803}Pobegao je iz lavirinta. ZloËin!
{81808}{81939}Uniötio je 12 mojih|Crnih Gardista. ZloËin!
{81943}{82089}I usuuje se da mi uskrati|zadovoljstvo jedinstveno u Sogou...
{82093}{82171}...zemljanku. ZloËin! ZloËin!
{82176}{82295}- Gde je Pajgar?.|- HoÊeö svog pernatog priljatelja?
{82321}{82354}Tamo je.
{82613}{82649}Pajgare!
{82862}{83031}Zabavno, zar ne, Lepa-Lepa?.|Zar ne ûeliö da se poigraö?
{83035}{83102}Lepa-Lepa... Moûeö da se|igraö sa nama, ako hoÊeö.
{83106}{83242}- Da, öto da ne!|- Dobro, Lepa-Lepa.
{83247}{83341}Matmos veÊ deluje na tebe.
{83406}{83521}To je zbog isparenja.|Od njih ti se igra.
{83650}{83691}- Skinite ga sa krsta!|- äta?
{83696}{83768}Skinite ga sa krsta ili|Êu da ti rastopim lice!
{84006}{84092}Moje lice! Moje prelepo lice...
{84109}{84183}- Stani ili pucam.|- Stoj!
{84188}{84245}- Moje lice!|- Upozoravam te.
{84272}{84350}Kako se usuujeö da ugroziö moje lice!
{84396}{84476}Pogledajte njenu energetsku|kopËu, vaöe veliËanstvo.
{84507}{84606}Prazna. Ovo oruûje je|bezopasno kao deËja igraËka.
{84678}{84813}ZnaËi, to je bio trik? Trebalo|je da svoje trikove priËuvaö za...
{84817}{84924}- Za ptice, vaöe veliËanstvo?|- Da, za ptice.
{84929}{85000}Ptice. Dajte je pticama.
{85029}{85074}Moraö...
{85520}{85606}Reci mi, moja elegantna, pernata nakazo.
{85611}{85689}Na öta si mislio dok si|vodio ljubav sa Barbarelom?
{85693}{85779}Vodio ljubav? Ne razumem.
{85784}{85883}Ne pravi se Ëedan prema|meni. Nisi u poziciji.
{85887}{85975}Da imaö bar jedno oko,|video bi kakav sam ja uûitak.
{85979}{86045}Moje lice, moje telo.
{86049}{86120}Sve na meni je uûitak.
{86142}{86209}Izuzetan uûitak.
{86237}{86331}- äta to hoÊeö?|- PodeliÊu svoje uûitke sa tobom.
{86336}{86399}VodiÊeö ljubav samnom.
{86447}{86533}Aneo ne vodi ljubav.|Aneo jeste ljubav.
{86537}{86588}Onda si mrtva guska.
{86592}{86625}Straûa!
{86674}{86742}Bacite ovog krilatog öaöavka Matmosu.
{87062}{87160}Hajde... Ui unutra.
{87590}{87689}O, kako su slatki.
{88219}{88274}UpomoÊ!
{88351}{88386}UpomoÊ!
{88495}{88550}Ovo je stvarno previöe|poetiËan naËin za umiranje
{89170}{89272}- Lozinku, brzo.|- Ne razumem.
{89337}{89419}- Ti si politiËki zatvorenik?.|- Ne bih rekla.
{89441}{89529}- Da li si ti jedna od nas?|- Ja sam sa Zemlje.
{89533}{89671}Zemlja...? Planeta Revolucija.|Da li Êeö pristupiti naöoj stvari?
{89676}{89740}Kakva stvar? Ko si ti?
{89769}{89899}Ja sm Dildano, voa Revolucionarnih|Snaga. Ovo je naö ötab.
{90001}{90040}- éivela revolucija!|- Revolucija!
{90044}{90080}Izveötaj patrole.
{90201}{90332}Drugi nivo odmah... Ne,|kreni tajnim prolazom.
{90733}{90771}Vrata!
{90986}{91037}Da li si ti tipiËna zemaljska ûena?
{91094}{91127}Ja sam nadproseËna.
{91168}{91281}- Kako sam izaöla iz ptiËjeg kaveza?|- Kroz tajni tunel za bekstvo.
{91285}{91425}äirom grada smo postavili|tajne tunele za bekstvo.
{91585}{91654}Za zaötitu naöe grupe.
{91748}{91869}- Shvataö da ste mi spasili ûivot.|- éivot bez razloga nema svrhe.
{91889}{91942}Sigurna sam da Êe vam|se moja Vlada oduûiti.
{92005}{92085}Zemljanko, da ti kaûem öta bih ja hteo?
{92139}{92194}Mislim da znam.
{92356}{92504}Ne! Ne tako. Kao na Zemlji... pilula.
{92509}{92581}- Imam pilulu!|- Ali...
{92716}{92819}Zar ne moûemo na vaö naËin?|Ne ûelim da menjaö navike.
{92824}{92869}Ja nisam divljak.
{93053}{93122}- Pilula.|- A-ha.
{93171}{93232}Pet godina sam oËekivao ovo iskustvo.
{93254}{93289}»ekaj!
{94738}{94783}éivela Revolucija!
{94919}{94976}Moja grupa mora...
{95402}{95451}Zdravo!
{95504}{95541}Izvini!
{95697}{95742}Moja grupa mora da dobije...
{96676}{96797}Gde si naöao ove pilule?|Samo zemljani znaju za njih.
{96958}{97013}Ti... Kakve novosti?
{97017}{97116}Moja grupa mora da dobije viöe|oruûja pre nego öto krenemo u napad.
{97120}{97223}- Vratite se na poloûaj. OËekujte nareenja.|- Razumem.
{97277}{97405}- DobiÊete vaöa nareenja!|- éivela revolucija!
{97409}{97466}Vrata... vrata... Vrata!
{97626}{97718}Moraö da mi kaûeö! Da li ti je|neko sa Zemlje dao ove pilule?
{97722}{97825}- »ovek zvan Duran Duran?|- To je taËno.
{97829}{97911}- Gde je on?|- Pilule mi je dao kad je doöao.
{97916}{98017}Nisam ga video od onda. Mislim|da je ûiv... verovatno u zamku.
{98021}{98120}- Da li imaö neöto öto bih mogla...|- Naravno, uzmi jednu tajnu uniformu.
{98124}{98157}Hvala ti.
{98219}{98295}Moja Vlada me poslala|ovamo da naem Duran Durana.
{98300}{98355}Tvoja Vlada...?
{98360}{98506}To mora da znaËi da imaö|svemirski brod i oruûje.
{98511}{98593}Da... Ne svia mi se ovo crveno.
{98597}{98663}Da li bi pozajmila svoju|opremu za naöu stvar?
{98667}{98782}Ne, ne smem to da uradim. Ne|dok ne izvröim moj zadatak.
{98962}{99081}- Moûda moûemo da se nagodimo.|- Na öta misliö?
{99112}{99190}Samo Crna Kraljica|zna gde je Duran Duran.
{99194}{99305}Ranjiva je jedino dok je u|svojoj tajnoj Dvorani Snova.
{99333}{99392}- Dvorana Snova?|- Da.
{99396}{99476}Ona spava sama u sobi iznad Matmosa...
{99481}{99575}... okruûena zidom energije,|za koji ima tajni kljuË.
{99579}{99731}Ipak, postoji i drugi|kljuË, kojeg sada imam ja.
{99736}{99853}Ti hoÊeö da naeö Duran Durana.|Ja hoÊu da zarobim Crnu Kraljicu.
{99858}{99919}Kapiraö öta hoÊu da kaûem?
{99924}{100029}Ako stvarno imaö drugi kljuË,|zaöto ga veÊ nisi upotrebio?
{100151}{100206}Zato öto naöe snage|joö uvek nisu dovoljne.
{100210}{100354}Da bi zarobili Crnu Kraljicu,|moramo da izvedemo vojni udar.
{100358}{100413}To bismo mogli sa tvojim|naoruûanjem i svemirskim brodom.
{100417}{100516}Sa Crnom Kraljicom u tvojim rukama,|znala bi gde da naeö Duran Durana.
{100520}{100563}- Da, razumem.|- Dobro.
{100598}{100669}Treba mi öest sati da pripremim napad.
{100706}{100817}Prvo, treba da kontaktiramo Profesora|Pinga da vidimo da li je popravio Alfa 7.
{100821}{100917}»as posla. Imam tajni radio ureaj.
{101276}{101347}Profesor Ping ätabu...|Profesor Ping ätabu.
{101351}{101410}- Profesor Ping ät...|- Ne!
{101414}{101494}ätab Profesoru Pingu...|ätab Profesoru Pingu.
{101499}{101571}- Javite se, molim.|- Ping ovde. »ujem vas jasno.
{101576}{101635}- Zemljanka je...|- Barbarela.
{101640}{101740}...Barbarela je samnom. Moûemo da|upotrebimo njen svemirski brod i naoruûanje.
{101744}{101911}- Da li je njen brod popravljen?|- Jeste, sada je spreman za let.
{101953}{102027}- OdliËno!|- Ipak, postoji jedna opasnost.
{102031}{102134}Patroldûija Crne Garde je primetio|brod i moûda se vrati da ga uniöti.
{102139}{102190}Nebesa!
{102195}{102306}Programirao sam brod da ode na|skriveno mesto van lavirinta.
{102310}{102406}- Ping, ti si Ëarobnjak.|- Upravo sada poleÊe.
{102410}{102500}Ode. Savröena letna putanja.
{102535}{102695}Mesto okupljanja biÊe nam|u 16:00 sati. Lozinka je...
{102699}{102787}"Llanfairpwllgwyngyllgogerychwyrn|- drobwIIllantysiliogogogoch."
{102791}{102824}Misliö, lozinka je...
{102828}{102897}"Llanfairpwllgwyngyllgogerychwyrn|- drobwIIllantysiliogogogoch."
{102901}{102934}TaËno!
{102992}{103039}- U redu?|- U redu.
{103076}{103164}ätab se odjavljuje. ätab se odjavljuje.
{103501}{103573}Pravo vreme. Kraljica|je u Dvorani Snova.
{103578}{103656}- A kljuË?|- KljuË!
{103798}{103872}- Evo ga tajni kljuË.|- Gde?
{103902}{104023}Nevidljiv je. Samo nevidljivi kljuË|moûe da otkljuËa nevidljivi zid.
{104155}{104188}Gde?
{104286}{104360}Matmose... kljuË!
{104465}{104500}KljuË...
{104589}{104632}Imam ga!
{104862}{104934}StaviÊu ga oko tvog tajnog vrata.
{105047}{105083}Nevidljivo.
{105151}{105291}Sad, tajna mapa koja Êe te|odvesti do dvanaestog hodnika.
{105312}{105351}Kakav hodnik?
{105465}{105500}Dobro!
{105529}{105562}Ovuda!
{105810}{105921}"Llanfairpwllgwyngyllgogerychwyrn|- drobwIIllantysiliogogogoch."
{105953}{105994}éivela revolucija!
{106121}{106154}Samo trenutak.
{106900}{106961}Nisam baö luda za cevima.
{108135}{108248}Izvinite. Moûete da mi kaûete kako|da doem do dvanaestog hodnika?
{108537}{108590}Imam neöto za tebe.
{108931}{109013}- äta je to?|- Suötina muökarca.
{109028}{109077}Suötina muökarca?
{109452}{109518}Dakle, umakla si pticama!
{109537}{109654}Svejedno. Moj je red da se malo zabavim.
{109659}{109702}Kreni zamnom.
{109740}{109791}Ovuda, molim.
{110931}{111028}- äta je ova stvar?|- Uskoro Êeö da vidiö, mila moja.
{111032}{111137}"Sonata za dûelata i razne devojke".
{111230}{111331}To je... nekako fino, zar ne?
{111335}{111438}Da. Fino je... Na poËetku.
{111592}{111713}SaËekaj da se melodija promeni.|Moûda promeni i tvoju melodiju.
{111727}{111799}Jao, kako to misliö?
{112142}{112245}Kad dostignemo kreöËendo,|umreÊeö... od zadovoljstva.
{112250}{112340}Tvoj kraj Êe biti brz,|ali sladak... veoma sladak.
{114753}{114841}äta je ovo? Ne mogu da verujem.
{114846}{114883}To je nemoguÊe!
{114896}{114996}Pokvarena devojko... äta si|uradila mojoj prekomernoj maöini?
{115000}{115088}Upropastila si je.|Upropastila si me. Vidi, vidi!
{115105}{115202}Kablovi za napajanje se skupljaju.|Pretvorila si ih u pruÊe.
{115206}{115339}Spalila si prekomernu maöinu.|Pregorela si joj sve osiguraËe.
{115343}{115382}Jao meni!
{115387}{115494}Iscrpela si joj napajanje.|Nije mogla da odrûi tvoj tempo.
{115524}{115653}Neverovatno! Kakva si ti to|devojka? Zar te nije sramota?
{115748}{115867}Sramota! Sram te bilo! PlatiÊeö za ovo.
{115906}{116039}Imam ja neöto za tebe. PoûeleÊeö|da si umrla od zadovoljstva.
{116043}{116102}Sad Êeö upoznati mudrost biËa.
{116107}{116170}Zar mi nisi dovoljno uËinio?
{116174}{116281}UradiÊu ti stvari koje su|izvan svih poznatih filozofija.
{116286}{116347}SaËekaj da dovuËem moje sprave.
{116736}{116769}Duran Duran?
{117087}{117177}O, prepozna me?
{117207}{117248}Prepoznala te?
{117252}{117386}Nikada ne bih mogla da te prepoznam. Mislila|sam da imaö samo 25 godina. äta se desilo?
{117390}{117499}- Matmos ostavlja posledice.|- Ali, ostario si 30 godina!
{117504}{117644}Matmos ima svoje naËine ishrane.|Za uzvrat, uËi te istini.
{117648}{117734}Doktore Duran, moûete|li da mi dodate odeÊu?
{117756}{117869}Predsednik Republike Zemlje|me poslao da vas spasim.
{117874}{117960}- I vratim vas na Zemlju.|- Planeta Zemlja? Nikad!
{117964}{118050}Da ti kaûem zaöto?|Zato öto previöe znam.
{118054}{118124}Ovde u Sogou sam|saznao istinu i suötinu.
{118128}{118220}Govorim o uzviöenosti,|otmenosti Ëistog Zla.
{118224}{118285}Moje Ëizme, molim.
{118290}{118395}Humanizam! Moral! Principi...!|To je ubre! Glupost!
{118399}{118460}Govorim samo o istini i suötini.
{118464}{118563}- Gde je pozitronski zrak?|- ZnaËi, to je.
{118567}{118620}äta on radi?
{118625}{118773}Sve osobe i stvari na njegovom putu|su deminimalizovane na Ëetvrti nivo.
{118777}{118822}- Misliö...?|- TaËno.
{118826}{118931}Nepovratno prebaËeni|u Ëetvrtu dimenziju.
{118936}{119047}- Ali, to je Ëudoviöno!|- Da, jeste. Zar ne?
{119051}{119110}Zaöto nisi preuzeo vlast ovde u Sogou?
{119115}{119172}Prvo bi trebalo uniötiti Crnu Kraljicu.
{119176}{119291}Ali, kao öto znaö, ona je uvek|okruûena svojom Crnom Gardom.
{119295}{119400}Ko god uspe da je ubije,|momentalno bi doËekao uûasnu smrt.
{119405}{119458}Odatle moj oprez.
{119488}{119623}Uûasna mi je pomisao da neko meni|uradi ono öto ja radim drugima.
{119627}{119734}Ali, meni su rekli da je Crna|Kraljica ranjiva dok spava.
{119738}{119824}O, jeste. U Dvorani|Snova nema Crnih Gardista.
{119829}{119896}Zato öto u Dvoranu nema pristupa.
{119900}{120013}Ali, vreme je za moje|zadovoljstvo... i tvoju smrt.
{120042}{120075}»ekaj!
{120143}{120215}Znam kako moûeö da ueö u Dvoranu Snova.
{120220}{120322}- Kako? Govori!|- Imam kljuË.
{120375}{120449}- Kako izgleda?|- Nevidljiv je.
{120491}{120617}ZnaËi stvarno ga imaö...|Dajem ti pet minuta.
{120633}{120699}Vodi me u Dvoranu Snova.
{120724}{120785}Nakon tebe, Barbarela.
{121283}{121344}Desno, Barbarela...
{121375}{121414}Sada levo...
{121457}{121490}Stani.
{121526}{121563}Otvori!
{121710}{121813}- Ovo mora da je nevidljivi zid.|- Jeste. A sad, gde je kljuË?
{121974}{122062}- Hajde, ne izvrdavaj.|- Pokuöavam da naem kljuËaonicu.
{122549}{122629}Zarobljena si. Zarobljena|si u Dvorani Snova.
{122634}{122706}- Matmos Êe te proûdrati.|- Vaöe veliËanstvo!
{122711}{122855}Nema svrhe. Imam dva kljuËa.|Zid je zatvoren za veËnost.
{122859}{122926}Doktore Duran,|prestanite sa tim ludilom!
{122930}{123086}- Vratite se sada sa samnom na Zemlju.|- Na Zemlju se vraÊam samo kao osvajaË!
{123091}{123225}ZahvaljujuÊi tebi je Kraljica, moja|poslednja prepreka, sada uklonjena.
{123229}{123286}ZahvaljujuÊi tebi, Barbarela.
{123355}{123466}Sada me viöe niöta neÊe|zaustaviti. Danas, Gospodar Sogoa...
{123470}{123632}...sutra, gospodar Zemlje, gospodar|galaksije, gospodar univerzuma!
{124084}{124232}Reci mi, moj fini, pernati|prijatelju, na öta si mislio...
{124236}{124302}...dok si vodio ljubav sa Barbarelom?
{124338}{124445}Aneo ne vodi ljubav.|Aneo jeste ljubav.
{126228}{126320}Probudite se, vaöe veliËanstvo!|Morate da se probudite.
{126376}{126489}Odstupi, zemljanko!|Znam da nisi stvarna.
{126493}{126580}Moûda je tako, vaöe veliËanstvo.|Ali bolje da verujemo svojim oËima.
{126609}{126726}Kukavna curo, öta si to uradila?|Niko ne moûe da ue dok spavam.
{126730}{126808}Vaö domar preuzima presto.
{126836}{126943}- äta to govoriö?|- Istina je. Uzeo vam je kljuË.
{127025}{127173}- ZakljuËani smo, vaöe veliËanstvo.|- KljuË. Ukrao je kljuË!
{127178}{127279}Osuene smo... osuene!
{127372}{127475}Rekao je da Êe nas Matmos|proûdrati. Na öta je mislio?
{127522}{127654}ReËeno je da, osim ako|sam u Dvorani Snova sama...
{127658}{127701}...Matmos Êe me uzeti.
{127911}{128024}- To je prestona dvorana.|- Mogu da vidim ceo grad i lavirint.
{128029}{128090}Naûalost, ekran je jednosmeran.
{128094}{128172}Niko ne vidi tog poganog|dûukca koji me zakljuËao.
{128177}{128298}Vaöe VeliËanstvo! Napadnuti|smo. Stvorenja iz lavirinta.
{128302}{128355}Bune se!
{128359}{128488}Kako se usuujeö da prekineö krunisanje!|Poöaljite vazduhoplovnu armadu!
{128554}{128599}Brzo, vaöe veliËanstvo, lavirint.
{128688}{128782}To je Dildano. On Êe da nas spasi.
{129524}{129631}- Vaöe veliËanstvo, svi su uniöteni.|- Dobro.
{129636}{129712}- Nema viöe stvorenja u lavirintu.|- Nema viöe letelica!
{129717}{129776}Imaju zemaljsko naoruûanje!
{129813}{129953}Budalo! Laûove! Idioti!|Zar sve moram sam?
{129993}{130096}- Moram da uniötim ovaj oloö.|- UpotrebiÊe Pozitronski zrak.
{131065}{131106}Radi!
{131139}{131198}Radi... Radi.
{131678}{131711}Sve je izgubljeno.
{131761}{131911}Moram da umrem, u redu, ali ja sam|ta koja Êe poslednja da se smeje.
{131915}{132001}Imbecil ne zna tajnu Velikog Tiranina.
{132005}{132138}Krajnje oruûje. OslobodiÊu Matmosa.
{132142}{132238}- Misliö da je to pametno?|- Sogo Êe nestati.
{132269}{132351}To Êe biti kraj. Apokalipsa!
{133153}{133237}- Gde smo ovo?|- U Matmosu. I to ûive!
{133242}{133281}To vidim, ali zaöto?
{133285}{133423}Matmos je stvorio ovaj mehur da|se zaötiti od tvoje nevinosti.
{133427}{133460}To je fino.
{133636}{133708}Ne, ne, stani! Nareujem.
{133713}{133751}Ja sam Duran Duran.
{133837}{133884}Ja sam gospodar Matmosa.
{133971}{134018}Nazad!
{134023}{134056}Nazad!
{134107}{134199}UniötiÊu te pozitronskim zrakom.
{134779}{134848}Toliko si dobra da si|naterala Matmosa da povrati.
{134852}{134897}Pajgar! äta si uradila Pajgaru?
{134901}{135024}Prepuöten je Matmosu, ali nije|bio niöta svarljiviji od tebe.
{135028}{135069}Ne moûeö biti mrtav.
{135103}{135220}Pobedila si, Barbarela. Ali Zemlja je|izgubila svog poslednjeg velikog diktatora.
{135225}{135313}Genije pozitronskog zraka...
{135493}{135564}äto mu ne pruûiö veötaËko disanje?
{135568}{135617}Imam bolju ideju.
{135811}{135880}Molim te... Pajgare, molim te.
{135918}{135963}Molim te, probudi se!
{136064}{136179}Moramo da odletimo do|mog broda. Imaö li snage?
{137149}{137303}Pajgare, zaöto si je spasio nakon|svih uûasa koje ti je uradila?
{137307}{137360}Aneo nema seÊanja!
{138125}{138240}K R A J
{138270}{138390}Prevod:|Ivan PetkoviÊ
{160000}{160001}septembar MMV|realpetko@yahoo.com
{160026}{161526}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3873f|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
