{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{500}{2000}{Y:i}(c)2004 prevod i adaptacija titla|Atlantis´|0655680498
{2470}{2541}Sve je poËelo dana kada sam umrla.
{2558}{2735}U mojoj Ëitulji bi bio opisan nezanimljiv ûivot|nezanimljive ûene
{2768}{2806}Ne preûivele.
{2811}{3013}Ali, nije bilo Ëitulje, jer je dan moj e smrti bio i |dan kad sam poËela da ûivim.
{3049}{3088}Ali, to dolazi kasnije.
{3359}{3482}Ovo je moj ûivot. Povezani,|obiËni dani.
{3496}{3570}ZahvaljijuÊi mom poslu.
{3596}{3638}Izvinjavam se.
{3654}{3708}Do sada je trebalo da postanem umetnica.
{3729}{3823}Umesto toga, pravila sam reklame|za kreme za lepotu.
{3924}{3997}PostaÊeö pravi ovisnik, Sali.
{4011}{4086}Ja verujem u Ëaroliju iz boce.
{4088}{4169}Kako si je nabavila?Joö uvek|nije u prozvodnji.  - Ima naËina.
{4228}{4266}Probaj.|- NeÊu.
{4334}{4399}Opet me boli. Nekako me zateûe.
{4433}{4540}Za jedni nedelju lansiraÊemo najuzbudljiviji...
{4549}{4618}i najrevolucionarniji proizvod za lepotu od...
{4650}{4682}sapuna.
{4710}{4743}" Beauty Line".
{4807}{4915}Ova krema ne krije efekte starenja,|veÊ preokreÊe sistem.
{4948}{5042}Ali, sa promenom dolazi i ûrtva.
{5055}{5249}Moj suprug i ja smo odluËili da se ja povUËem|sa mesta modela.
{5266}{5340}Bilo je ovo fantastiËnih 15 godina.
{5360}{5480}Ali, reöili smo da izaberemo novo lice|koje Êe nas predstavljeti.-TaËno.
{5522}{5615}Predstavljam vam novi simbol lepote.
{5682}{5779}Sada  se radujem öto Êemo se videti u |sveËanoj sali, gde Êemo...
{5794}{5877}nazdraviti Trini i naöem uspehu.|- Paûljivo, Dûordû
{5891}{5958}Ona nema dovoljno godina da bi pila.
{6079}{6136}Imaö viöe talenta od bilo kog u zgradi.
{6149}{6193}Zbog Ëega te i mrzim, usput.
{6195}{6264}Ovo je moja prva glavna kampanja.|Mora biti savröena.
{6271}{6340}Znaö to.|- äta nije u redu sa tobom?
{6401}{6433}SreÊno.
{6516}{6631}Nisi mogla da odoliö, morala si|da napraviö scenu.
{6676}{6740}äta je?|Ukrala sam tvoj trenitak?
{6778}{6804}Uite.
{7207}{7244}Dobar dan, gospodine.
{7278}{7335}Da li i dalje ûelite da me vidite, ili?
{7346}{7372}Sedi.
{7541}{7591}Nisam zadovoljan.
{7662}{7743}Ovo nije ni blizu onome |öto sam  hteo.
{7749}{7796}Ne znam öta ste mislili.
{7813}{7881}éao mi je - POgledajte ovu crvenu,|pogreöna je.
{7896}{7977}éelim da bude tamnija.|- Ja sam Ëula kad ste rekli...
{7986}{8060}Znam öta sam rekao.
{8088}{8141}Moûda vas nisam razumela.|- OËigledno.
{8161}{8234}Mogu to da popravim, samo mi|dajte öansu.
{8252}{8316}Ja ne nagraujem nesposobnost.
{8327}{8447}Ne znam zaöto sam mislio da Êe vaöa umetnost |biti bolja od vaöe garderobe.
{8488}{8538}I, idite kod manikira.
{8555}{8602}Za ime boga.
{8633}{8711}Pusti je da sredi to|. Znaö da je dobra.
{8755}{8803}Kako god.|Do sutra uveËe.
{8845}{8902}U ponoÊ.
{8912}{8940}Hvala vam.
{10130}{10161}Izvinite.
{10198}{10230}Moûete li da...
{10242}{10306}malo stiöate muziku?
{11698}{11723}Maco.
{11745}{11821}Kako si se tamo popela?|Sii.
{11886}{11936}Zaglavila si se?
{12021}{12071}NateraÊeö me da se popnem tamo.
{12887}{12947}Hej, polako!|SaËekaj!
{12969}{13024}äta god sad oseÊaö, razmisli.
{13040}{13116}Pogledaj. Ja sam policajac,|moûda mogu da pomohûgnem. - U redu.
{13126}{13181}Dobro sam, samo...|- Sluöaj me...
{13185}{13281}uspeÊemo zajedno. Kako se zoveö?|- Patient Filips.
{13322}{13368}Ali, ova maËka....
{13371}{13428}Da, naravno.|I veoma je lepa.
{13468}{13542}Veoma slatka.|- Ali, nema je viöe. - U redu.
{13587}{13640}Sigurno si veoma tuûna zbog toga.
{13651}{13700}Koji je broj tvog stana?
{14135}{14189}Dobro si?|- Hvala.
{14325}{14363}Sigurno si dobro?
{14391}{14436}To je ta maËka.
{14445}{14536}Nisi se zezala. ZnaËi, htela si da|spasiö maËku.
{14555}{14611}Da, ali nije moja maËka.
{14619}{14678}Spasila si neËiju maËku?
{14688}{14726}To je druga stvar.
{14780}{14826}Kasnim na posao!
{14865}{14945}Danas predajem rad.|- SreÊno.
{14971}{14986}Hvala.
{16060}{16132}Niko ne moûe da pobedi vreme.
{16154}{16230}Da li si to znala?
{16249}{16328}Lepota je Ëudo, zar ne?
{16355}{16398}Da.
{16415}{16453}Danas sam veoma zauzet.
{16458}{16538}Posle idem na piÊe.|Nemoj da me Ëekaö.
{16555}{16611}Davno sam to prestala.
{16679}{16756}I, otkaûi onaj ruËak sutra.
{16766}{16823}Problemi?|- Sumnjam.
{16851}{16902}Ali, Stadiki ne prestaje da me zove.
{16910}{16985}NauËnici su gori od modela.
{17011}{17076}Moraö da ih maziö kao|da su deca.
{17083}{17126}Zakaûi za drugi put.
{17655}{17706}»ovek sendviË nailazi.
{17774}{17809}Gospode.
{17990}{18018}Dobar dan.
{18039}{18068}Zdravo.
{18135}{18208}Ovo je policajac o |kome sam ti priËala.
{18231}{18264}Detektiv Lon.
{18305}{18340}Tom.
{18351}{18428}To je sjajno ime.|Tom Lon.
{18448}{18527}Rimuje se sa puno reËi.
{18568}{18612}Ne da je to bitno.
{18687}{18729}Moram da nastavim sa radom.
{18896}{18926}Zdravo.
{18964}{18998}Kako si pronaöao...
{19049}{19144}Neöto ti je ispalo. To se deöava kad|Ëovek ûuri.
{19159}{19182}Hvala.
{19244}{19273}Ovo je tvoje?
{19306}{19334}Da.
{19356}{19388}Lepo je.
{19402}{19427}Hvala.
{19432}{19494}POdseÊa me na ranog äagala.|Elegantno...
{19505}{19620}ali i stabilno.|Nalik tradiciji starih mejstora.
{19621}{19671}Impredionirana sam|. Nemoj da budeö.
{19671}{19740}Primetio sam stvari u tvom stanu pa|se sad öepurim.
{19762}{19820}Ali, stvarno mi se svia.|- Hvala.
{19893}{19980}HoÊu da ti se izvinim öto sam pomislio|da hoÊeö da skoËiö.
{19984}{20029}Ako mogu da te vodim na kafu?
{20040}{20128}Znam jedno dobro mesto u blizini.
{20183}{20244}Moûda je bolje sutra. U jedan?
{20297}{20320}Da.
{20380}{20403}U redu.
{20438}{20480}ZnaËi, sutra u jedan.
{20491}{20563}Potrudi se da bude tamo.|- Da, ser.
{20573}{20650}Ako pogreöim, moûeö da baciö kljuË.
{20723}{20746}Vidimo se sutra.
{20866}{20949}To je Ëovek za tebe!
{20958}{21004}Misliö?|- Hej.
{21048}{21110}Prvo, moraö da obrijeö noge.
{21118}{21200}Drugo, znaö öta treba uraditi, zar ne?
{21222}{21414}Prvo, to je samo kafa,|i drugo, nikada se neÊu drugaËije obuÊi.
{22020}{22066}Ovo je Patiens iz|umetniËkog odeljenja.
{22089}{22164}OËekujem da neko doe po...
{22198}{22252}Ali, mora da bude tamo do ponoÊi.
{22311}{22355}Znam da niste vi krivi, ali...
{22410}{22439}U redu.
{22460}{22508}OdneÊu sama.
{23291}{23338}Ima li koga?
{23581}{23665}Daj, kad si ti dobio savest?
{23692}{23834}Nije me briga za glavobolje, muËninu,|padanja u nesvest...
{23837}{23909}sa tim simptomima mogu da ûivim.
{24146}{24235}Ali, ovo öto gledamo ne moûe da se sredi.
{24260}{24390}Mogu da ûivim sa zavisnoöÊu, ali ovo su|straöni sporedni efekti.
{24412}{24498}NeÊe se desiti ako nastave da je koriste,|a postaraÊemo da tako i bude.
{24503}{24559}Jer, odatle stiûe novac.
{24571}{24616}Nisam siguran.
{25060}{25104}Ne bih mogao da ûivim sa tim.
{25150}{25224}Ne mogu da pretvaram ljude u Ëudoviöta.
{25247}{25297}Boûe. - Moramo da |prekinemo ovo.
{25312}{25362}Ne smemo da nastavimo.
{25406}{25439}Ko je tamo?
{25508}{25542}Dolazim.
{26078}{26130}Moûeö da izaeö, u redu je.
{26141}{26198}Samo hoÊemo da ti postavimo par pitanja.
{26269}{26317}Izvinite, ali
{26350}{26391}nisam namrno.
{26414}{26488}äta to radiö?|- Nemoj viöe nikada to da uradiö.
{27523}{27552}Gde je?
{27670}{27733}Otiöla je niz ulicu|kroz cevi.
{27771}{27829}Ne znamo ko je, ali znamo |öta je Ëula.
{27844}{27896}Ne smomo da rizikujemo.|Otarasite je se.
{27968}{28036}Zatvori vrata.
{36821}{36943}Nikad nisam bila ponosnija!|Sada verovatno slaviö!
{36969}{37054}Fantaziraö o lizanju njegovih prstiju.|- Ne, to ja radim.
{37079}{37147}Kakva je bila prezentacija?|- Zovi me.
{37518}{37612}Ovde Tom Lon, ja sam |stigao i Ëekam te.
{37646}{37678}Ti nisi ovde.
{37695}{37741}Moram da se vratim na posao, pa...
{37774}{37799}zdravo.
{38191}{38282}U redu, maco.|Vreme je da ti naemo dom.
{38446}{38483}OPHELIA PAUERS
{38895}{38951}Da li ste vi Ophelia Powers?|- Da.
{38973}{39044}Pronaöla sam vaöu maËku...|- PonoÊi...
{39044}{39109}Nikad ranije nisi dovela stranca.
{39120}{39161}Molim vas, uite.
{39188}{39248}Ne mogu, moram da idem, kasnim.
{39823}{39870}PonoÊ. - Molim?
{39883}{39967}Tako se zove. |Egipatska je.
{39985}{40048}Veoma retka vrsta.
{40070}{40133}Kaûu da imaju posebne moÊi.
{40156}{40199}Da se pojave niotkuda?
{40201}{40244}Izmeu ostalog.
{40365}{40440}Vaöa maËka...
{40480}{40520}Nema kofeina.
{40542}{40647}»ini ga razdraûljivim. |I vi izgledate Ëudno, draga.
{40689}{40803}Moûda zbog maËaka? Izgleda da|su se vezale za vas.
{40819}{40893}Ovo mi je veÊ bio loö dan.
{40910}{41005}Ne mogu ni da se setim veÊinu juËeraönjeg|dana...- Moûda mogu da vam pomognem.
{41071}{41146}Ovo nije vaö problem. »ak i ne znam|zaöto sam ovde, pa...
{41154}{41200}U redu je, recite mi.
{41209}{41264}Kasnim na posao, izvinite.
{41282}{41356}Vratite se kad god ûelite.|Uvek sam tu.
{42027}{42049}Dobro sam.
{42062}{42089}Ja sam dobro.
{42146}{42201}äta nije u redu sa tobom?
{42217}{42334}Nikad nisi radila dizajn.|Ti Ëak i ne znaö gde su.
{42347}{42453}I to zato , citiram- ne|moûeö da se setiö.
{42468}{42546}Tvoja nesposovnost je straöna.
{42630}{42695}Da li me uopöte suöaö?
{42975}{43011}éao mi je.
{43047}{43080}éao?
{43125}{43175}To nije ni malo dovoljno.
{43197}{43233}Dobro.
{43247}{43308}Da kaûem to drugaËije.
{43351}{43483}éao mi je zbog svakog sekunda koji sam|bacila radeÊËi za netalentovanog...
{43506}{43567}neetiËnog egomanijaka|kao öto si ti.
{43597}{43674}Pokupi stvari, otpuötena si.
{43858}{43894}Nisam to mislila.
{44031}{44061}Ona je heroj.
{44602}{44653}Ne mogu da opiöem.
{44657}{44732}Kao da jesam ali i nisam|ja to govorila.
{44755}{44828}äta ti kaûeö? - Nemam öta, zahvaljujuÊi tebi.
{44835}{44902}Ne razumeö.|Htela sam da budem pristojna...
{45052}{45101}äta to bi?|- Alergija?
{45130}{45158}Moûda?
{45402}{45501}Upravo si otpuötena, seÊaö se?|- Ali, predivna je.
{45592}{45614}Sal?
{45693}{45728}Sali!
{45854}{45954}Da li znaö da kad te zadrûe radi posmatrnja,|niko te u stvari se posmatra?
{45970}{46035}Da li su ti rekli öta nije u redu?|- Nemaju pojma.
{46059}{46117}Ali, uradili su mi milion|temeljnih testova.
{46132}{46212}Moraö da vidiö mog doktora.|- Vidim da ti je bolje.
{46236}{46342}äto me podseÊa....äta se desilo sa|onim slatkim detektivom?
{46415}{46510}Ne bi nam uspelo. - Gubim strpljenje,|ti uvek to misliö.
{46525}{46596}Jeste tako. A ovog puta|imam i dobar razlog.
{46610}{46639}Veruj mi.
{46655}{46715}Odbijam da sabotiraö|dobru stvar.
{46732}{46793}Sredi to.
{46809}{46835}Ja te volim, a i on Êe te voleti.
{46855}{46880}Sada idi.
{46886}{46933}Lapo se provedi.
{46979}{47020}Moram da se vidim sa zgodnim doktorom.
{47022}{47075}Da li izgledam ranjivo?
{47123}{47194}Dobrota je neöto öto Ëuvate u srcu,|jer ste tako izabrali.
{47212}{47314}Nije lako, neki ljudi izaberu da budu|loöi, ali vi morate biti drugaËiji.
{47336}{47373}Bolji. Razumete? -Da.
{47440}{47485}Mogu li da vidim vaö piötolj?|- Ne.
{47509}{47562}Kako postajete neko?|- Kad ga ubijete? - Ne.
{47836}{47892}HoÊu da budete dobri momci, shvatate?|- Da.
{47911}{47947}Hajde da igramo.
{48157}{48222}U stanici su mi rekli|da si moûda ovde.
{48326}{48389}Nismo popili onu kafu.
{48485}{48580}Samo veliki Ëovek moûe da se suoËi|sa ovom mafijom. Bez podröke?
{48590}{48669}Navikao sam da radim sam, uglavnom.|- Tako si izabrao? - Da.
{48727}{48767}Ranije sam imao partnere, ali...
{48774}{48842}izgleda da preozbiljno  shvatam posao.|- Znaö moju prijateljicu Sali?
{48861}{48916}Pitala sam je öta misli o meni.|Rekla je da...
{48937}{48999}sam zabavni individualac. - Ne verujem.|Tako je rekla.
{49020}{49057}Jedan na jedan?
{49072}{49118}Ona i ja?|- Da, hajde.
{49155}{49187}HoÊeö?
{49734}{49788}Ovo nisam radila od malena.
{51329}{51369}Mogu li da dobijem loptu nazad?
{51425}{51493}Meni ne izgledaö toliko zabavna sad.
{51867}{51962}Gospodin je ûeleo da vas obavestim da Êe|do kraja dana biti u fabrici.
{51976}{52055}To znaËi da je u restoranu i uËi Trinu |kako da postane zvezda.
{52078}{52145}Smatraj me obaveötenom. - Samo|je rekao da Êe raditi sa...- Vesli.
{52174}{52269}On mi nije rekao niöta smisleno|joö od kada je rekao - da.
{53155}{53273}Halo? - »ovek bi mislio da u srediötu|moderne medicine imaju dobar bar.
{53289}{53363}ZvuËiö kao da ti je bolje.- To je od leka|Ëije ime ne mogu da izgovorim.
{53403}{53433}äta ima? - Niöta.
{53445}{53548}Malo grickam. - Zar ne bi trebalo|da se grickaö sa slatkim policajcem?
{53631}{53694}Mislim da jesam.
{53729}{53823}Reci mi sve. Ja ovde baö i |nemam neke novosti da ti ispriËam.
{53875}{53969}Razgovarali smo i igrali jedan na jedan.|- Znaö da igraö koöarku?
{53997}{54061}Izgleda da znam.|»ak sam i pobedila.
{54081}{54171}Zar te niËemu nisam nauËila?|Nekad nemoj da pobediö momka u sportu.
{54181}{54241}To ih upropasti.|Izgube muökost.
{54251}{54326}Nisam planirala, |jednostavno se desilo.
{54338}{54461}Kaûem ti, neöto stvarno uvrnuto|mi se deöava.
{54509}{54576}PraktiËno sam ga saskoËila.|- To je poûuda, duöo.
{54600}{54645}éivotinjska privlaËnost.|- Misliö?
{54699}{54739}äta ako postane gore?
{54790}{54883}äta ako sledeÊi put...|- POzvao te je da izaete ponovo?
{54889}{54934}Oboûavam ga!|- I ja.
{54958}{55045}Ali, brinem za sebe. Kao da|ne mogu da budem ja.
{55048}{55098}Slobodno budi ja kad ga |vidiö sledeÊi put.
{55128}{55208}Zezam se. Budi svoja.|- Svoja?
{55276}{55300}Dobro.
{55327}{55346}PokuöaÊu.
{55357}{55433}Moram da idem. Pozdravi|decu, dragi.
{55489}{55558}Izvinite, mislim da imam groznicu.
{55969}{56105}Ugasi to! - Umukni!|- Gubitnice!
{56448}{56513}Izvini duöo.|Satanina ûurka.
{56582}{56663}Zdravo ljuvabi. Mislim da bih|se u tvojim rukama izvukao.
{56672}{56700}Polaskana sam.
{56730}{56844}Ali, da li samo ovaj put moûeö|malo da utiöaö muziku?
{57220}{57280}Znaö öta? Zaöto sama|ne ugasim muziku?
{57368}{57389}Hej, ludaËo!
{57503}{57540}Izvini, öta si rekao?
{57557}{57610}Ako je muzika glasna...
{57929}{57998}Da li Ëujeö ovo?|Zove se tiöina.
{58009}{58078}Samo to sam htela.|Neka tako ostane.
{58102}{58167}Hvala ti za zabavu, bilo|mi je dobro.
{59312}{59379}Vreme je za akciju.
{61382}{61416}Amateri.
{61602}{61719}Mislite da moûete doËi ovde i |ukrasti sve ove lepe stvari?
{61741}{61825}Nije baö dobra ideja.
{65942}{65988}Bile su unikat.
{66015}{66053}Iz Egipta.
{66112}{66167}Kaûu da skaËe kao maËka.
{66203}{66284}Riba MaËka?|- Ne, KuËka MaËka.
{66823}{66861}KolaËi.
{68797}{68861}Znala sam da Êeö se vratiti.|Kad budeö spremna.
{69218}{69270}Istorija boginje.
{69456}{69543}Oni su svetinja proölosti.|Prenose im poruke.
{69563}{69656}Vi ste ovo napisali?|- Bila sam profesor 20 godina.
{69679}{69766}Dok me akademija nije degradirala.
{69876}{69922}To je sestrinstvo.|Boginja Meseca i Sunca.
{69994}{70051}Ostavila je oseÊaj dvojnosti|u svakof ûeni.
{70073}{70150}Neustraöive, neûne, paûljive.
{70160}{70209}Ali, i graciozne.
{70224}{70287}Ali, kakve to ima veze sa mnom?
{70305}{70363}äta se desilo te veËeri?
{70379}{70447}Ne seÊam se.|- HoÊeö da ti kaûem?
{70478}{70542}Da. - Umrla si.
{70602}{70635}äta?
{70663}{70720}Nisam umrla, ovde sam.
{70740}{70815}Umrla si, ali si |ponovo roena.
{70831}{70904}Vi ste ludi.|- Vi ste luda dama- maËka.
{70927}{70979}PonoÊ je bila tvoja sudbina.
{71022}{71077}Zato te je testirala.
{71152}{71165}Da sazna da li si spremna.
{71190}{72690}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/7q29f|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
