[INFORMATION]
[TITLE]
[AUTHOR]
[SOURCE]
[PRG]
[FILEPATH]
[DELAY]0
[CD TRACK]0
[COMMENT]
[END INFORMATION]
[SUBTITLE]
[COLF]&HFFFFFF,[STYLE]bd,[SIZE]24,[FONT]Tahoma
00:01:12.12,00:01:17.03
ZENE

00:02:01.80,00:02:06.12
Sklanjajte ga.

00:02:09.91,00:02:14.30
Sve je u redu, srecice, postoji[br]naziv za takvu zenu i retko

00:02:14.60,00:02:17.45
se koristi van stenare.

00:02:22.65,00:02:28.93
U redu, kuco, pet minuta za kupovinu[br]na prvom spratu. Kreni.

00:03:11.59,00:03:15.16
Besplatan uzorak novog proizvoda[br]sa svakom kupovinom od 25 dolara.

00:03:15.72,00:03:21.64
Zelite li vi fejs lifting u teglici.[br]-Ovo je moje lice, zadrzi to.

00:03:32.40,00:03:37.12
Silvi? -Posmatram zenu koja treba[br]da bude u mom casopisu sa

00:03:37.68,00:03:44.20
natpisom da je tanka linija izmedju[br]odece i pidzame. -Ne kupujes sada?

00:03:45.00,00:03:52.72
Zasluzila sam, od sest jutros sam[br]na poslu. Volim radne subote, niko mi ne smeta.

00:03:53.20,00:04:00.25
Zar ne bi trebalo da si na putu ovamo?[br]Koliko je sati? -Seksas li se ti to?

00:04:01.73,00:04:05.93
Da li bih onda razgovarala sa tobom?[br]Ne odgovaraj.

00:04:06.49,00:04:15.28
ldem na manikir, kada je danas sastanak.[br]-U pola jedan, nemoj da kasnis.

00:04:16.24,00:04:22.97
Kada kasnim? Vidimo se tako[br]negde.

00:04:34.13,00:04:41.49
Dobar dan, Riti treba vode,[br]pije iz solje. -Tanja vas ceka.

00:04:42.25,00:04:51.26
Vi ste Tanja? To vam je ime,[br]nemojte mi pricati, zurim.

00:04:52.06,00:04:57.54
Otisla sam kod numerologa koja[br]je rekla da promenim ime ako zelim

00:04:57.98,00:05:00.33
da promenim zivot. Radila sam u[br]''kod gdina Bronija''.

00:05:01.93,00:05:07.45
Ne idem cesto u Kvins. -lstog dana[br]kada sam promenila ime

00:05:07.81,00:05:10.66
zaustavila se limunzina ispred radnje[br]i znate da je izasla Madona.

00:05:11.14,00:05:12.49
Moram da stignem na rucak u[br]jedan.

00:05:12.97,00:05:19.01
Pitala sam se sto je to uradila i[br]onda sam joj uradila najbolji manikir.

00:05:19.73,00:05:24.49
Promenite. Koristim svoj lak.[br]Kazu da imam dara.

00:05:24.86,00:05:26.78
Rucak je u Kontektikatu, to je druga[br]drzava.

00:05:27.66,00:05:33.26
Sledece je da me zovu iz Saksa kako[br]je Madona prezadovoljna manikirom

00:05:33.66,00:05:37.11
i nude mi posao. Zelite da probate[br]moju dzungla crvenu? -Nije lose.

00:05:37.63,00:05:39.62
Namazala sam ga devojci koja[br]radi na parfemima, tek se doselila

00:05:42.06,00:05:43.87
i onda je zapocela vezu sa ozenjenim[br]covekom.

00:05:44.27,00:05:47.62
Ako ne mozes da zavrsis, doci cu[br]drugi put, kakva ti je sreda?

00:05:49.27,00:05:57.22
Ozenjeni je neka zverka u Vol Stritu.[br]Ne mogu da mu upamptim ime.

00:06:01.47,00:06:06.31
Neki Hejns. -Da nije Stiven Hejns?

00:06:07.27,00:06:15.23
Taj je. Sreda u 11 ili u dva.[br]-Sreda ne odgovara, sada mi sredi ovo.

00:06:16.95,00:06:22.86
Stiven Hejns ima aferu sa prodavacicom,[br]o cemu se tu radi?

00:06:24.47,00:06:28.31
Da ste ikada videli Kristal Alan,[br]ne biste ni pitali.

00:06:40.64,00:06:43.51
Uplasila sam se, dodji.

00:06:44.87,00:06:49.19
Parkirala sam se u 78. ispred prodavnice[br]usisivaca, nemoj da zaboravis.

00:06:49.99,00:06:53.44
Zasto bi zaboravila? -Cula sam[br]nesto uznemirujuce.

00:06:56.31,00:07:04.40
Zagrlite mamu. Zar ne pozdravljamo[br]tetu?

00:07:08.87,00:07:15.72
Dora, spremi se za polazak.[br]-Glava me ubija, imas li aspirin?

00:07:17.00,00:07:19.88
Sta si cula i gde mi je tasna?[br]-Sta ovo predstavlja?

00:07:21.32,00:07:22.96
Sada slikam. -A grncarija?

00:07:26.97,00:07:29.92
Cudni su to ljudi.

00:07:30.80,00:07:35.04
Ne znam kako Alan uspeva da[br]zivi ovde. -lselio se. -Sta?

00:07:37.28,00:07:42.48
U studiju je na osmom spratu,[br]treba mu prostora. Dora?

00:07:43.20,00:07:46.08
ldemo, ne mogu da se koncentrisem.

00:07:46.76,00:07:51.81
Ti ces voziti? -Sta god da si cula,[br]ako je o nekome koga znama, nemoj

00:07:53.28,00:07:56.45
mi reci. -Previse je licno.[br]-Jeste o nekome?

00:07:58.81,00:08:04.09
Smeta nam dim. -Moze se ukljuciti[br]u upaljac u kolima.

00:08:05.48,00:08:11.21
Neces ti voziti. Kako si mi ti?[br]Zaboravi, idemo.

00:08:36.74,00:08:39.17
Rucak? -Da.

00:08:42.46,00:08:49.06
Dolazi mi sezdeset zena na rucak,[br]nisam se ni istusirala.

00:08:49.50,00:08:55.98
Donela si mi hemijsko?[br]-Jesam. Divna slika.

00:08:58.89,00:09:07.42
Cvece, i... znas gde je ono sto[br]sam spremila sa onim na ivici?

00:09:07.78,00:09:11.38
Pred tobom je.

00:09:12.86,00:09:18.94
Vidi, lice device Marije se pojavilo[br]u lraku.

00:09:19.54,00:09:23.03
Covek bi tesko poverovao da si[br]rodjena u zemlji koja deli Nobelovu nagradu.

00:09:23.86,00:09:30.90
Ja sam iz Danske, kao i testo.[br]-Mama, sta se desilo?

00:09:31.78,00:09:37.46
Trebalo je da mi pomognes sa[br]izvestajem o knjizi. -Zaboravila sam.

00:09:37.98,00:09:41.71
Rok je ponedeljak. -Ali danas imam[br]rucak, ja sam potpredsednik.

00:09:42.18,00:09:48.58
Sta ti je bitnije, parce trave ili moje[br]obrazovanje? -Zasto sve ostavljas za kraj.

00:09:48.98,00:09:53.07
Uta moze da ti pomogne.[br]-Nikol Kidman ima celulit.

00:09:53.67,00:09:54.98
Daj da vidim.

00:09:56.26,00:10:01.94
Uradicemo posle rucka, ne mogu[br]jer treba da zavrsim crteze koji

00:10:03.43,00:10:08.07
kasne i da pokupim avionske karte.[br]-Zasto sve ostavljas za kraj?

00:10:09.79,00:10:14.36
Tako se razgovara sa majkom?[br]-To moze da popravi kolac.

00:10:14.83,00:10:20.31
To je pet poena. -Od kada ti[br]brojis kalorije? -Od kako sam debela.

00:10:21.31,00:10:26.24
Ti si savrsena. -Sama cu napisati[br]izvestaj.

00:10:27.95,00:10:31.44
ldi pod tus. -Misli da je debela.

00:10:31.84,00:10:36.95
Otac te je zvao, zeli da rucate[br]kada se vratis sa odmora.

00:10:39.20,00:10:44.52
Ne znam kada je to poslednji put[br]hteo. -Rekao je da je vazno.

00:10:44.96,00:10:55.04
Sprema se da mi prenese posao.[br]Znas li da godinama cekam na to. Boze.

00:11:00.60,00:11:09.04
Lusi? Moli, rekla sam ti da ne[br]stavljas psa u krevet.

00:11:09.68,00:11:15.24
Zasto dizajniramo odecu koju nikada[br]ne bismo navukle na sebe?

00:11:16.68,00:11:17.89
To je tvoj deda pravio za svoje[br]musterije, ali nece biti moje.

00:11:18.65,00:11:24.45
Sta je ovo? -Filter za kafu za put.

00:11:30.57,00:11:35.01
Sigurno je neki prodavac.[br]Cekaj malo.

00:11:36.45,00:11:43.57
Ko bi znao da ce izaci, to je novi[br]leksus. -Naravno da hoce, smiri se.

00:11:44.12,00:11:47.81
Prosula je pirincano mleko po[br]sah tabli, imate krpu? -Evo.

00:11:49.65,00:11:56.13
Megi, stavi mi ovo u friz.[br]-Stavicu pored mleka od 2%.

00:12:00.29,00:12:07.41
Boze, ne mogu da verujem da sam[br]stigla. Niakda te nisam videla danju.

00:12:08.09,00:12:10.17
l nisi.

00:12:13.85,00:12:17.81
Ja sam ldi Koen. -Natasa.

00:12:21.50,00:12:26.54
Drago mi je, samo Natasa.[br]-Ona je super model.

00:12:28.50,00:12:36.33
Ne zovi me tako, opredmecuje me,[br]ja sam osoba. -U redu, nisi tasna.

00:12:36.89,00:12:40.18
ldem po pice, ne ogovarajte me.

00:12:42.21,00:12:47.49
Prosla je obuku o ljutnji.[br]-Sto se ljuti? -Gladna je.

00:12:49.41,00:12:55.62
Treba da se skrasis sa nekim ko[br]je pravi za tebe. -Sa muskarcem?

00:12:56.10,00:13:02.58
Prihvatam te kao gej prijateljicu,[br]ali to je odjednom pola sveta.

00:13:02.90,00:13:08.70
Ne znas koliko je lakse biti u vezi[br]sa zenom, ako se izgubimo, obe

00:13:09.22,00:13:14.58
trazimo pomoc, gledamo samo[br]jednu emisiju, ne pijemo iz tetra paka,

00:13:15.30,00:13:19.63
ili trazi da se izvlaci prst ili ima[br]opsesiju da pisa na tri metra.

00:13:20.18,00:13:25.03
A kada je seks u pitanju nijedna[br]ne zeli upaljena svetla.

00:13:27.02,00:13:29.74
Dugujes mi sto dolara.

00:13:30.87,00:13:35.42
Reci mi koliko cu cekati na tvoju[br]drugu knjigu?

00:13:35.91,00:13:41.30
Zelim da je stampam pre smrti.[br]-To se ne radi tek tako.

00:13:46.42,00:13:51.70
To je bilo pre 60 godina, nastavimo[br]dalje. -Malo je ometena, si videla

00:13:52.31,00:13:53.99
sa kim izlazi?

00:13:57.11,00:13:58.92
Da li je Meri tu?

00:13:59.55,00:14:03.27
Divno je sto ste otvorili kucu za[br]central park. Vasa majka je

00:14:03.59,00:14:07.15
bila predsednica zenskog komiteta[br]godinama. -To je bilo vazno i ja

00:14:07.75,00:14:09.75
nastavljam tradiciju.

00:14:11.19,00:14:16.96
Ne znam kako stizete i svoj posao.[br]-Farmaceutski poslovi.

00:14:19.79,00:14:23.76
lmate sampanjac i svedski sto[br]na travnjaku, posluzite se.

00:14:27.15,00:14:31.59
Stigla si na vreme. -Ti uvek kasnis.

00:14:32.11,00:14:37.52
Skloni to. Bas divna zabava.[br]-Hvala sto si otvorila.

00:14:38.19,00:14:41.68
Za sta su najbolje prijateljice.[br]-Sta je bilo?

00:14:42.24,00:14:47.72
Nista, zasto pitas? -Cudno si me[br]pogledala, sta se desava?

00:14:50.11,00:14:52.72
Kruzis ocima, nesto mi ne govoris.[br]-Govorim ti sve.

00:14:58.12,00:15:02.16
Mislim da se otac razmislja da mi[br]prepusti posao.

00:15:03.17,00:15:10.92
To je dobro? -Fantasticno je,[br]ali cu morati da kazem Stivenu.

00:15:11.80,00:15:20.01
Gde je on? -Radi kao i poslednjeg[br]meseca radeci svako vece na nekom fondu.

00:15:21.53,00:15:29.32
Stvarno? -Ali za 24 sata cemo piti[br]kapucino na Trgu Sv. Marka.

00:15:30.16,00:15:36.36
Dobro si? -Jesam, idem nesto[br]da pojedem.

00:15:58.85,00:16:03.13
Ne moras. Uzmi karticu.

00:16:11.70,00:16:16.01
Lepa haljina. -Hvala.[br]Dobre naocare.

00:16:16.37,00:16:18.46
lzvoli. -Hvala.

00:16:21.97,00:16:29.86
ldi, to je mnogo hrane, kako uspes?[br]-Reci cu vam, saznacete ionako.

00:16:32.49,00:16:39.45
Jedem za dvoje. -Boze, zar ne[br]kazes ''ne'' nekada?

00:16:40.38,00:16:45.02
Sta je bilo? -ldi je opet napumpana?

00:16:45.49,00:16:46.86
Sigurna si? -Svakako.

00:16:47.38,00:16:50.70
Zelim da nastavim dok ne dobijem[br]decaka. -Zar nam ih nije dovoljno?

00:16:51.58,00:16:55.74
Ne razumete, ne postoji nista[br]uzbudljivije da znas da u sebi

00:16:56.10,00:16:59.03
gajis ljudsko bice, zar nije tako?

00:17:00.86,00:17:10.11
Pregledala sam neke gluposti na[br]tavanu i videla kutiju i teglice.

00:17:10.55,00:17:15.35
Otvorila sam kutiju i nisu bile teglice[br]nego gomila Moline decje odece.

00:17:16.15,00:17:23.23
Vidim te zeke i osetim udarce u[br]matericu. -Razmisljas o jos dece?

00:17:23.91,00:17:32.19
Nisam mislila o tome, ali nesto se[br]menja u poslednje vreme. -Sta?

00:17:34.91,00:17:40.11
Moram da piskim. Odmah se vracam.

00:17:45.43,00:17:50.79
ldi, nisam htela da kazem nista.[br]Meri mi je kao sestra.

00:17:51.23,00:17:53.95
Rekla sam da ne zelim da znam.[br]U vezi sa Meri je?

00:17:54.83,00:17:57.03
Ostaje tajna? -Tajna.

00:17:57.55,00:18:00.59
Stiven ima aferu. -Ne.

00:18:01.04,00:18:06.31
Nova manikirka iz Saksa mi je rekla[br]da se vidja sa nekom koja radi

00:18:06.75,00:18:08.51
sa parfemima. -Prskalica?[br]-Verujes li u to?

00:18:09.11,00:18:16.79
Zelis da kazes Meri? -Naravno da[br]ne, ali govori o jos jednom detetu.

00:18:20.00,00:18:25.32
Sta ako to nije istina, koliko je[br]za verovati manikirkama?

00:18:25.88,00:18:29.96
One i cvecarke znaju sve.[br]-Ne treba da kazemo nista.

00:18:36.20,00:18:38.36
Mozda se zavrsi ubrzo i ne znam[br]nikoga ko se uvalio u nevolju

00:18:38.80,00:18:47.24
jer je cutao. Znam stvari o prijateljima[br]i to mislim bas. -l ja.

00:18:49.96,00:18:51.80
ldemo.

00:18:53.01,00:18:55.48
Zaboravila sam da piskim.

00:18:59.01,00:19:01.72
O, ne.

00:19:02.16,00:19:06.37
Hvala vam. -Sve je bilo divno, dacete[br]mi naziv kateringa, bilo je ukusno.

00:19:06.96,00:19:11.09
Sve sam sama spremila.[br]-Kuvala si?

00:19:12.93,00:19:19.48
Na sta si mislila, sada cemo sve to[br]morati da uradimo, a nismo sve ti.

00:19:19.88,00:19:23.09
Cestitam. -Poziv za tebe, on je.

00:19:27.36,00:19:32.32
Zdravo, duso, gotovo su otisle,[br]mozes da dodjes kuci.

00:19:32.72,00:19:36.73
Jer odlazimo rano ujutru, da jedemo[br]napolju...

00:19:40.93,00:19:51.14
Stivene, trebala nam je vecnost[br]da isplaniramo put i treba nam odmor.

00:19:51.66,00:19:54.65
Mora da postoji nacin.

00:20:01.45,00:20:12.25
Dobro, zvacu agenciju, Venecija[br]ce biti tamo. Kada dolazis kuci?

00:20:13.21,00:20:15.66
Necu te cekati.

00:20:23.81,00:20:29.34
Ta kancelarija ga ubija.[br]-Nesto to radi.

00:20:29.86,00:20:33.62
Nismo htele da prisluskujemo.[br]-Hvala sto ste dosle danas.

00:20:35.66,00:20:40.38
Ostala bih da nemam planove.[br]-lmam decu kod kuce.

00:20:41.06,00:20:43.90
Bicu dobro.

00:20:51.18,00:20:53.38
Do djavola.

00:20:54.91,00:20:59.87
Moras da me podrzis, treba da[br]razgovaramo sa citaocima,

00:21:00.39,00:21:03.78
tako ce se sama istaknuti.[br]Hoces da napravis brend casopisu.

00:21:04.78,00:21:10.26
Postanemo modni casopis mislene[br]zene. Dovedemo provokativne pisce,

00:21:10.82,00:21:15.74
stavimo holivudske dive na[br]naslovnu stranu.

00:21:16.14,00:21:22.78
Znam, ali ti si me unajmio sa razlogom,[br]sledece godine ces biti genije.

00:21:23.27,00:21:27.59
Meri je na trojici. -Nede, imam[br]problem, moram da idem.

00:21:29.83,00:21:33.86
Kako je prosao rucak sa ocem?[br]-Kakav je osecaj biti sef

00:21:34.26,00:21:35.67
svoje dizajnerske kuce?

00:21:36.11,00:21:43.79
Otac me je otpustio. Rekao je da[br]nisam pokazivala svoj rad.

00:21:44.23,00:21:48.99
Ali dizajniranje savrsenog fraka za[br]zenu da ga nosi kod kuce nije

00:21:49.71,00:21:58.44
bas moj rad. -Dodji do mene,[br]otvoricemo flasu i opet ogovarati muskarce

00:21:58.99,00:22:04.56
koji ne veruju u nas. -Ned te[br]opet riba? To je uzas.

00:22:05.04,00:22:10.16
Zasto ne veruje tvojoj viziji?[br]-To je kriza poverenja.

00:22:10.56,00:22:13.79
Moram da povucem nekoliko[br]velikih pisaca u ovaj casopis

00:22:14.19,00:22:17.20
i to brzo. -Mozes ti to, ne staj.[br]-Volim te.

00:22:18.52,00:22:23.44
Ne bi da mi vidis kosu. Da se[br]vidimo u Saksu na sisanju?

00:22:25.08,00:22:27.52
Ne idi tamo, unakazice te.

00:22:31.12,00:22:36.68
Ta zena je neljubazna.[br]Vidimo se, zdravo.

00:22:37.60,00:22:40.00
Meri?

00:22:41.48,00:22:43.00
Zene.

00:22:50.57,00:22:55.33
Ja sam Meri Hejns i prijateljica je[br]zakazala za mene.

00:22:55.85,00:22:57.93
Jeste, ali ne mozemo da vas[br]ubacimo narednog sata.

00:23:01.29,00:23:04.76
Mogu li dobiti manikir. -Da proverim.

00:23:06.81,00:23:11.72
Tanji je otkazano. -Odlicno.[br]-Prvi sto napred.

00:23:23.64,00:23:27.69
Tanja, poslali su me ovde.[br]-Sedite.

00:23:29.94,00:23:35.25
Da pogledamo. Sta smo radili?[br]-Ribala sam kupatilo.

00:23:36.14,00:23:44.13
Mislila sam nesto neutralno.[br]-A dzungla crveno?

00:23:44.81,00:23:49.61
To je previse za mene.[br]-Ovo je fino.

00:23:51.21,00:23:52.90
Moze.

00:23:54.06,00:23:56.89
Koji je to parfem? -Muz mi ga je[br]poklonio.

00:23:57.65,00:24:01.94
Vec sam ga omirisala, isti nosi[br]i moja prijateljica, ona radi dole

00:24:02.37,00:24:08.33
na parfemima, i ima skup ukus.[br]Zove se Kristal Alen.

00:24:10.66,00:24:15.61
Ona je sa muskarcima koji imaju[br]novac, ima jednog.

00:24:17.58,00:24:23.02
Tip koga se dohvatila je uvek[br]u novinama, ali Kristal nije za brak.

00:24:24.34,00:24:30.30
Ne pamtim ime. Lep prsten.[br]Na pogresnoj je ruci.

00:24:30.90,00:24:38.06
Drugarice su mi ga dale proslog[br]Bozica. -Zove se Stiven Hejns.

00:24:38.46,00:24:46.14
Bila sam prisutna kada ga je upoznala.[br]Skupo odelo, zgodan i kaze

00:24:46.58,00:24:52.47
da zeli da kupi parfem za zenu.[br]l Kristal pita koji je tip zene?

00:24:52.83,00:24:55.42
A on kaze da je tip koji mirise tako.[br]To je bilo slatko, ali je za

00:24:55.74,00:24:59.51
Kristal to bio izazov, ona ga je pitala[br]da li bi hteo nesto seksipilnije.

00:25:00.31,00:25:06.94
Pogleda ga kao macka, i gotovo[br]da mi je bilo zao coveka, nije imao sanse.

00:25:07.66,00:25:13.42
Uzme bocicu Dzezabela, to nosite,[br]poprska ga na sebe i da mu da

00:25:13.99,00:25:18.62
pomirise i on pocne da je njuska[br]i to mu se dopalo vise nego sto

00:25:19.22,00:25:24.23
je trebalo. Sve je to igra za Kristal.[br]Kada je uzela karticu, prepoznala je ime.

00:25:25.02,00:25:29.63
Sta se onda desilo? -Onda ga je[br]proganjala i poceli su da se

00:25:29.99,00:25:33.95
vidjaju, vodi je na vecere, kupuje[br]joj odecu, salje cvece u vazi.

00:25:35.67,00:25:46.99
Mislim da... setila sam se da moram[br]da idem negde.

00:25:48.12,00:25:54.96
Da li sam opet pricala previse?[br]Zabavljam klijente dok radim, gdjo...

00:25:55.36,00:26:05.84
Hejns. -Tako mi je zao, nisam znala,[br]ja i moja velika usta.

00:26:06.64,00:26:10.75
Samo ne pominjite vise.[br]-Necu.

00:26:13.72,00:26:16.87
Dona?

00:26:18.88,00:26:27.24
Meri je, trazim Silviju. Jos je na[br]sastanku? Recite joj da mi se javi.

00:26:30.28,00:26:36.24
Kasnim? lzvini. -Cula sam,[br]otac ti je seronja.

00:26:37.00,00:26:42.73
Narucila sam ti koktel, znam da ne[br]pijes popodne, ali hoces, pocni sada.

00:26:45.12,00:26:50.16
Da vidis los lifting, Helen Anvers,[br]na dva sata, deluje kao da ulazi

00:26:50.60,00:26:56.80
u zemljinu atmosferz.[br]Zelis da kaznim tvog oca?

00:26:58.33,00:27:01.45
Stiven me vara. -Sta?

00:27:02.12,00:27:06.81
Ne mogu da verujem da sam to[br]rekao. -Neka tvoja prijateljica?

00:27:08.44,00:27:12.57
Prodaje parfeme u Saksu.[br]-Prskacica je?

00:27:13.57,00:27:17.33
Kako nisam znala, pre tri meseca[br]je kupio sagorevace kalorija.

00:27:20.46,00:27:25.25
Mislila sam da smo srecni.[br]-Sta ces da radis?

00:27:26.01,00:27:31.41
Reci cu mu da se iseli. -To nije[br]pametno. Neko je rekao da ne

00:27:31.77,00:27:33.97
radis nista kada ne znas sta da[br]radis.

00:27:34.89,00:27:41.57
Muz sa kojim sam 13 godina ima[br]aferu. Pricaju ili mi se smeju kada

00:27:41.93,00:27:46.78
su u krevetu? Ne govori mi da se[br]pretvaram da to nije nista.

00:27:47.17,00:27:49.01
Nemas pojma kakav je osecaj.

00:27:51.10,00:28:00.45
Da pokusam, osecaj je kao da te[br]je neko sutnuo u stomak.

00:28:00.90,00:28:05.50
Da je srce prestalo da ti kuca,[br]kao san u kome padas i ocajno

00:28:05.94,00:28:15.50
zelis da se probudis pre udarca,[br]ali ne mozes. Vise ne verujes nikome.

00:28:16.06,00:28:19.30
Niko nije onaj za koga se izdaje.[br]Zivot ti je zauvek promenjen.

00:28:20.30,00:28:30.27
Jedino sto proistice je to da ti niko[br]nikada vise nece slomiti srce.

00:28:31.71,00:28:37.63
Ne mogu da verujem da mi nisi[br]rekla. -Htela sam da volis oca.

00:28:39.14,00:28:46.54
Ko je ona bila? -Prodavacica[br]tkanina, videla sam je,

00:28:47.07,00:28:51.34
Nosila je previse sminke.

00:28:51.74,00:28:59.19
Sta si ti uradila kada si saznala?[br]-Nista, ta devojka ne znaci

00:28:59.59,00:29:08.59
Stivenu vise od tkanine tvom ocu.[br]Da je voli ti bi to osetila.

00:29:08.99,00:29:14.11
Ne mogu da budem uz njega.[br]Ovo treba da uradimo.

00:29:14.63,00:29:17.11
Prolecni je raspust, otici cemo[br]na nekoliko nedelja.

00:29:18.95,00:29:23.55
Treba mu veca doza ljubavnice[br]da mu nedostaje zena.

00:29:24.03,00:29:33.20
Nije ovo film iz 30-ih. -lmas kcerku[br]kao sto sam je imala i ja,

00:29:33.88,00:29:35.36
nisi samo ti u pitanju.

00:29:35.92,00:29:41.60
Reci Stivenu da sam pozvala tebe[br]i Moli na plac, otici cemo sutra.

00:29:42.43,00:29:51.24
Ne bih o tome razgovarala sa prijateljicama,[br]sve ce zeleti da pomognu, ali ces

00:29:51.68,00:29:54.28
na kraju ti brinuti o njima[br]umesto o sebi.

00:29:57.48,00:30:03.96
Zao mi je, ali je dobro znati[br]da ti je majka jos uvek potrebna.

00:30:09.76,00:30:14.44
Da li je to izlazak sunca, jer sam[br]na pogresnoj strani.

00:30:15.24,00:30:17.96
Ucuti, trebao je neko Meri da[br]je odveze na aerodrom.

00:30:19.49,00:30:24.28
Ja ne zovem lazna prijateljstva[br]da ne moram nikoga da vozim.

00:30:24.76,00:30:28.32
Na sledecoj raskrsnici skrenite levo.[br]-Ko je to?

00:30:28.68,00:30:34.16
Dama za navigaciju, uvek je smirena[br]i ne odgovara, moj muz je zaljubljen u nju.

00:30:41.32,00:30:45.85
Osecam da se nesto ne govori.[br]Sta se desava a da ne znam?

00:30:48.25,00:30:51.13
Aleks, sta ti mislis o braku[br]Meri i Stivena?

00:30:53.48,00:31:00.73
Deluje savrseno spolja, ali nesto[br]se desava. Meri ne voli da gleda

00:31:01.09,00:31:04.61
u pukotine, previse je zauzeta[br]popunjavajuci ih.

00:31:05.17,00:31:13.33
Ona je sva ''suma blista, suma peva'',[br]ali ce pre ili kasnije... Meri odradjuje nekoga?

00:31:15.33,00:31:20.17
Zasto mislis da je to Meri?[br]-Da li Stiven ima aferu?

00:31:20.61,00:31:25.57
ldi, alapaco. -Nisam rekla nista.[br]-Poznajemo li je?

00:31:26.89,00:31:28.13
Tajna? -Tajna.

00:31:28.66,00:31:33.21
Prskalica u Saksu. -Ne, kako je[br]to podnela?

00:31:33.93,00:31:40.34
Ne zna. -Kako ne zna?[br]Sta vam je, mi imamo tajnu, ne i ona.

00:31:40.94,00:31:47.74
Mora i ona. -Danima se borim sa[br]ovim. Najbolje smo prijateljice od koledza.

00:31:48.50,00:31:54.86
Mislim da treba zna. -lli?[br]-Da ne kazemo nista.

00:31:55.22,00:32:01.46
Mora da zna, to je ispravno.[br]Hocete ja da joj kazem?

00:32:14.38,00:32:16.94
Zdravo. -Mogla sam taksijem.

00:32:17.38,00:32:21.11
Zasto da ides na aerodrom sama?

00:32:22.51,00:32:27.47
Tu su sve informacije. l zovi nas.[br]-Kod doktora.

00:32:28.59,00:32:31.70
l dolazi covek u utorak da popravi[br]slavinu.

00:32:37.42,00:32:40.19
Sta radite ovde? -Ulazi.

00:32:41.70,00:32:43.63
Ne, izaci cemo.

00:32:46.83,00:32:54.95
Postoji razlog sto smo sve sa tobom[br]ovde danas. Silvija ima nesto da ti kaze.

00:32:57.07,00:33:06.23
Tesko je. -To je u vezi sa kuckom[br]sa parfemima?

00:33:06.56,00:33:12.56
Znala si, a nisi mi rekla?[br]Tako sam povredjena.

00:33:13.08,00:33:17.23
Ovo se desava meni.

00:33:22.15,00:33:28.55
Sada je receno, a sta ti je rekao[br]kada si se suocila sa njim?

00:33:30.36,00:33:35.07
On ne zna da znam. -To je smesno.

00:33:41.16,00:33:48.72
Cenim sto zelite da pomognete,[br]ali ne analizirajte sve ovo sada.

00:33:49.96,00:33:56.48
Budite tu za mene tiho.[br]ldemo.

00:33:57.76,00:34:01.16
Sada ne bi trebalo da upravljam[br]teskom masinerijom.

00:34:11.08,00:34:17.21
Mama, bilo bi kul da napravimo[br]tetovaze majki i kcerki.

00:34:18.76,00:34:25.36
Dobar pokusaj. -Promenilo bi ti imidz.[br]-Sta mu fali? -Nema veze.

00:34:28.25,00:34:32.12
Mogu da se tetoviram?[br]-Kada mi probuse nos.

00:34:33.57,00:34:39.45
Zasto me ne cujes? -Zelis tetovazu,[br]ali je neces dobiti.

00:34:42.97,00:34:47.77
ldem da gledam tv. -Ostani sa[br]nama, divan je dan.

00:34:48.41,00:34:51.37
Mogu li bilo sta?

00:34:53.33,00:34:58.69
Mislim da ce danas biti dovoljno[br]toplo za kupanje.

00:34:59.17,00:35:06.05
Moram da oblacim kupaci, muskarci[br]mogu da se setaju bez briga.

00:35:06.61,00:35:10.29
Starije zene moraju da se pokrivaju[br]samo radi setnje po plazi.

00:35:14.30,00:35:21.06
Stiven je. -Ne javljaj se, neka[br]misli da se provodis bez njega.

00:35:21.78,00:35:25.78
Mrzim te igrice, ali je dobro imati[br]kontrolu.

00:35:26.34,00:35:32.10
Naravno, zvao je tri puta od kako[br]smo ovde. Preklinje te da se vratis.

00:35:35.18,00:35:37.90
Bilo bi tako lako da ga ne volim.

00:35:38.74,00:35:41.77
Trebalo bi da postoji tableta od[br]koje nestaje ljubav.

00:35:42.42,00:35:52.82
Zasto bi to zelela, tesko je i naci je.[br]-Stiven je. -Sada mozes da se javis.

00:35:55.62,00:35:58.18
Da? Stivene?

00:36:00.46,00:36:02.50
Umirem da vidim kako izgleda.

00:36:03.38,00:36:10.30
Ovo je losa ideja, nemamo plan,[br]pogledaj tu tasnu.

00:36:12.11,00:36:16.50
Treba mi avans. -Necu ti pomagati,[br]zavrsi prokletu knjigu.

00:36:19.51,00:36:23.95
Mama, umorna sam od kupovine.[br]Zelim da idem.

00:36:24.63,00:36:30.67
Ne mozemo, teta Silvi proganja[br]nekoga, mozemo da odemo kada zavrsi.

00:36:31.39,00:36:33.90
Mrzim ovu radnju.

00:36:35.23,00:36:43.91
Ejpril, saslusaj me, reci cu ti nesto[br]vazno i upamtices to do kraja zivota.

00:36:45.30,00:36:53.91
Niko ne mrzi Saks. Uradimo ono[br]zbog cega smo dosle.

00:36:55.47,00:36:58.16
Mama, mozemo li da pojedemo[br]nesto?

00:36:59.35,00:37:01.03
Sa musterijom je.

00:37:05.23,00:37:12.39
Kristal, telefon za tebe, muskarac je.

00:37:25.75,00:37:29.60
Ona je bozanska. -Videle smo je,[br]idemo sada.

00:37:29.96,00:37:33.32
Ni za zivot. -Slazem se sa Sofi.

00:37:37.60,00:37:45.64
Stivene, nadala sam se da si ti,[br]kako si, nedostajao si mi ove nedelje.

00:37:46.52,00:37:54.89
Okrutno je i imam kaznu za tebe.[br]A da spremim romanticnu veceru?

00:37:55.73,00:37:59.76
Ono veliko kockasto belo iz cega[br]izlazi vatra je rerna.

00:38:01.53,00:38:06.41
Naravno, tvoj posao je na prvom[br]mestu, ne brini.

00:38:06.97,00:38:10.20
Sacuvacu ti parce torte sa svecom.

00:38:11.28,00:38:16.80
Nisam htela da ti kazem da ne[br]bi pravio grzvu i bice drugih rodjendana.

00:38:20.65,00:38:25.29
Uzasno bih se osecala da te[br]odvlacim od bitnog posla. Siguran si?

00:38:28.24,00:38:29.93
Vidimo se onda.

00:38:31.93,00:38:38.17
Ta glupa zena, od kako je negde[br]se ponasa kao izgubljeno stene.

00:38:38.57,00:38:43.33
lmam audiciju u cetiri, a sada pravim[br]veceru, kako ce to biti?

00:38:44.61,00:38:46.78
Htela si. -Moram da idem.

00:38:47.57,00:38:50.37
Mozes negde da se sklonis da[br]bismo imali stan za sebe.

00:38:51.49,00:38:56.33
Srecno na audiciji.[br]-Mozete li mi pomoci?

00:38:56.73,00:39:00.85
Odlazim, ali vam Pet moze pomoci.[br]-Receno mi je da trazim Kristal Alan.

00:39:02.05,00:39:08.53
To ste vi? Cula sam da na specijalne[br]nacine znate sta treba musterijama.

00:39:08.93,00:39:11.90
Gde ste to culi? -Uokolo.

00:39:13.34,00:39:19.33
Nosim sanel no. 5 od krstenja,[br]sta biste predlozili?

00:39:20.37,00:39:28.06
Nista previse stalno. -Znate[br]tacno na cemu ste sa mnom.

00:39:28.74,00:39:36.66
Zelim da parfem bude moj odraz,[br]pametan, neustrasiv, bistar, veran,

00:39:37.02,00:39:41.90
zastitnicki prema prijateljima,[br]nemilosrdan prema varalicama.

00:39:42.30,00:39:45.07
Kupujete parfem ili pisete licni[br]oglas?

00:39:45.74,00:39:49.10
Moja prijateljica nosi nesto novo,[br]muz joj je to kupio ovde.

00:39:50.59,00:39:57.27
ldi, kako se zove parfem koji[br]ima Meri Hejns koji joj je kupio Stiven?

00:39:57.78,00:40:04.79
Stiven Hejns, mozda ste ga usluzili,[br]zgodan, platinum kartica, mozda

00:40:05.27,00:40:07.14
zvuci poznato?

00:40:07.63,00:40:12.30
Znamo da kreses Stivena i Meri[br]nam je prijateljica, zato prekini.

00:40:23.11,00:40:28.51
Varao te je i ti mu nista ne kazes.[br]-Od povratka iz Mejna je slanje

00:40:29.03,00:40:38.31
cveca i ''sta mogu da ucinim za[br]tebe?'' Mozda je mama u pravu,

00:40:38.83,00:40:41.39
mozda ta afera nije bila bitna.[br]-Kada si postala Francuskinja?

00:40:41.87,00:40:44.15
Ne spavam sa njim. -Dobro je,[br]neka pati.

00:40:45.51,00:40:49.87
Da ne pricamo, kako je Geri?[br]-Gotovo je sa njim.

00:40:52.79,00:41:08.80
Bojis se da izaberes. -Nije, izabrala[br]sam jednom dok mi nije pocela karijera.

00:41:10.47,00:41:13.88
Rekao mi je da zeli da poletim,[br]da ne moze da bude sa zenom

00:41:14.24,00:41:18.28
koja ima tako razvijene vijuge.[br]-Tu je bio samo on u pitanju.

00:41:19.04,00:41:23.88
Muskarcima je tesko da budu[br]sa uspesnom zenom, zato mi

00:41:24.32,00:41:30.32
treba da budemo psiholozi kao ti.[br]Ti kocis uvek jer mislis da ces moci

00:41:30.76,00:41:32.96
da ga promenis.

00:41:33.36,00:41:37.00
Kada se zaljubis ne mislis kako ce[br]ispasti, samo to radis.

00:41:38.44,00:41:42.52
Na prvom sastanku kada mi je[br]dao bundevu. -Bila je noc vestica.

00:41:43.68,00:41:46.88
To je lepo da ti daju bundevu.

00:41:51.41,00:42:00.88
Bili smo divan tim, 13 godina, 13[br]bundeva, to je bitno.

00:42:01.52,00:42:06.28
Mrzim noc vestica sa svim tim[br]strancima na vratima.

00:42:06.76,00:42:09.77
Kada ne budes trazila naici ces[br]na coveka za koga ces zeleti

00:42:10.17,00:42:12.61
da se udas i to ce biti sve.[br]-Ja sam taj muskarac.

00:42:17.17,00:42:20.81
Sta mislis o ovome?[br]-Na tebi?

00:42:22.41,00:42:26.73
Stivenu se mozda posreci veceras.[br]-Gdjo Hejns, odavno vas nismo videli.

00:42:28.97,00:42:31.37
Probala bih. -Stvarno?

00:42:32.34,00:42:35.97
U cemu je problem?[br]-Ovo je vasa velicina.

00:42:36.69,00:42:39.89
Priznajem da sam potcenila vrednost[br]klizista u krevetu.

00:42:41.01,00:42:43.98
Mozda ti ostavi nesto novca[br]na stocicu.

00:42:46.29,00:42:52.97
Zasto bi zena kupila nesto od cega[br]joj butine izgledaju kao da ih je

00:42:53.33,00:42:55.02
pogodila kisa meteora.

00:42:55.82,00:42:57.98
Kako ste unutra? Treba li druga boja?

00:43:04.53,00:43:09.34
Da li je previse? -Ne, idem po[br]jos nesto.

00:43:10.22,00:43:12.66
lmate li bolje svetlo negde?[br]-Da, u hodniku.

00:43:15.02,00:43:17.53
Ne stidim se.

00:43:26.22,00:43:28.50
Vi ste prva musterija koja je imala[br]hrabrosti da to proba.

00:43:29.02,00:43:36.55
lmate li one podmetace?[br]Moracu da uzmem, koliko je ovo?

00:43:37.02,00:43:42.19
ltalijanski rucni vez, zato je[br]650 dolara. -lma u jos nekoj boji?

00:43:42.70,00:43:47.55
U sampanj. -Volim je, uzecu je[br]u obe.

00:43:47.91,00:43:54.51
Gotovina ili kartica? -Uzimate li cekove?[br]Ne, ali rado cu vam otvoriti racun.

00:43:55.15,00:44:00.63
Provera kredita je brza.[br]-Nemam vremena za to.

00:44:03.30,00:44:07.86
Da vam dam broj nekoga ko[br]bi vam to rado dao preko telefona.

00:44:09.46,00:44:16.27
Kako je njegovo ime?[br]-Stiven Hejns, porodicni prijatelj.

00:44:17.63,00:44:25.55
Ona nam je klijent, nalazi se u[br]kabini niz hodnik, da vam ona

00:44:25.95,00:44:28.95
ovo odobri?

00:44:30.47,00:44:42.39
To ne bi bilo dobro, nova sam[br]u gradu i jos je nisam upoznala.

00:44:42.99,00:44:49.31
Ne bih volela da se ovako upoznamo.[br]Razumecete to?

00:44:50.28,00:44:53.47
Naravno, zvacu gdina Hejnsa.

00:45:08.64,00:45:14.72
Ne mislis da je dobro? -Meri, ona[br]je u kabini niz hodnik, Kristal Alen.

00:45:17.28,00:45:22.60
Kako znas to? -Videla sam je da[br]prica sa prodavacicom.

00:45:23.12,00:45:26.24
Trosi bogatstvo i stavlja to na[br]Stivenov racun. -To nije istina.

00:45:26.60,00:45:34.92
Ako joj placa racune, jos je sa[br]njom. -ldem kuci, pomozi mi.

00:45:39.32,00:45:44.81
Bezis od pocetka, cega se bojis?[br]-Da cu biti jos veca budala nego sto jesam.

00:45:46.32,00:45:52.40
Ta zena se ugnezdjuje u tvoj[br]zivot, ako se ne suprotstavis

00:45:52.84,00:45:56.81
samo je pitanje vremena kada ce[br]ona seci bundevu sa tvojom kcerkom.

00:45:58.04,00:46:04.68
Dajem ti dozvolu da budes losa,[br]idi tamo i rasturi je.

00:46:07.17,00:46:10.53
Cuvacu ti ledja, samo idi.

00:46:14.81,00:46:20.13
ldi, mozes to. -Mogu to.

00:46:25.57,00:46:30.13
Sranje, zezas me?

00:46:34.38,00:46:43.49
Ja sam Meri Hejns. -Ovo je cudno.[br]Verovatno ti je rekao.

00:46:44.13,00:46:51.66
Nije te pomenuo, ali znam za tebe.[br]-Cudno da mi se nisi javila ranije.

00:46:52.10,00:46:55.14
To nije moj stil, ali rekoh kada si[br]tu da se predstavim...

00:46:56.41,00:47:01.45
Zao mi je i znam da Stiven nije[br]hteo da vas povredi.

00:47:02.58,00:47:08.09
Ne znas nista o mom muzu.[br]-Znam da zena ne krade tudjeg muza,

00:47:09.02,00:47:13.94
sami odu. -lzgleda da si veoma[br]iskusna.

00:47:15.46,00:47:21.58
Stiven je previse pametan da[br]nekoga kao ti shvati ozbiljno.

00:47:23.62,00:47:29.62
Znam mnoge zene kao sto ste[br]vi, imate prijatelje i fine kuce

00:47:30.46,00:47:34.42
sa rokovnicima punim socijalnih[br]dogadjaja, ruckova za fondove

00:47:34.83,00:47:40.27
sa kojima imate utisak da radite nesto[br]u zivotu, ali na kraju prekinete

00:47:41.06,00:47:43.23
da obracate paznju na muskarce,[br]oni postanu usamljeni i potraze

00:47:44.87,00:47:53.14
nekoga ko ih ceni i to shvataju[br]veoma ozbiljno.

00:47:54.55,00:48:02.31
Dosla sam ovde sa idejom da[br]kada bi videla da sam ljudsko bice

00:48:02.87,00:48:09.75
a ne neka misao da bi osetila[br]sazaljenje.Trenutak spajanja sa

00:48:10.23,00:48:17.27
drugom zenom i da ces shvatiti[br]stetu koju si nacinila, ne samo

00:48:17.76,00:48:22.35
meni, nego porodici.[br]-Ne znam sta ste rekli.

00:48:24.64,00:48:34.15
Prestani da se vidjas sa mojim[br]muzem. -To je na njemu.

00:48:36.96,00:48:45.16
Stivenu se nikada ne bi dopalo[br]nesto tako droljasto.

00:48:45.55,00:48:50.32
Ako mu se ne dopadne ono sto[br]nosim, ja to skinem.

00:48:55.56,00:48:59.12
Bila si u pravu. -Vodi me odavde.

00:48:59.60,00:49:03.44
Ko si ti? -Bas ga je nagazila.

00:49:09.80,00:49:16.65
Sta jos? -Svadjaju se i onda se[br]Meri ucuti i pita ga da li zeli

00:49:17.04,00:49:23.36
da bude sa njom. l on joj kaze[br]da je voli.

00:49:27.97,00:49:34.21
Meri je prestala da ga slusa i kaze[br]da nije nameravao da afera bude nesto

00:49:34.97,00:49:39.57
i da je vise puta pokusao da je[br]zavrsi.

00:49:39.97,00:49:42.76
Muskarci se uvaljuju stvari iz kojih[br]ne znaju kako da se izvuku.

00:49:43.80,00:49:49.81
Pogresio je rekavsi da je nastavio[br]da se vidja sa Kristal jer je primetio

00:49:50.21,00:49:54.13
da je postala zavisna od njega[br]i da nije hteo da je povredi.

00:49:54.48,00:49:58.65
Da povredi nju? -To je i Meri rekla i[br]pogresila rekavsi da ne vidi

00:49:59.09,00:50:03.13
da ga juri samo zbog novca.[br]-l jeste, poslednje sto muskarac

00:50:03.65,00:50:08.33
zeli da cuje da je zena jedino[br]dovoljno glupa da ga voli zbog njega.

00:50:09.61,00:50:12.61
Niko ne ume da se svadja, treba[br]da naprave skolu.

00:50:13.38,00:50:18.66
Sada je postavio bitno, da li mogu[br]ikako da to stave iza sebe.

00:50:20.01,00:50:25.50
Slomilo bi ti srce da si ga cula.[br]-Koga briga, imamo li posao?

00:50:26.02,00:50:32.54
Meri kaze da zeli razvod. -A on?[br]-Da, uzmu vremena da razmisle i

00:50:33.01,00:50:37.02
da ce prenociti u hotelu.[br]-A ona?

00:50:37.58,00:50:41.49
Gadjala ga je velom.[br]-To je lose.

00:50:48.70,00:50:53.26
Zena mi je nudila posao.[br]-Ne mozes sada da odes.

00:50:57.26,00:51:07.26
Cujem nesto. -To je to, bezi iz[br]broda koji tone, Uta.

00:51:07.94,00:51:13.74
lmam pravilo da se ne vezujem za[br]porodice, bas zato.

00:51:19.38,00:51:24.31
Treba mi nesto da pojedem sto nije[br]bezmasno, beskaloricno, svuda je voce.

00:51:24.75,00:51:27.22
Gde je djubre? -Nisi mi dala da[br]ga kupim.

00:51:31.82,00:51:38.98
Znajte da se Stiven i ja razvodimo,[br]ima aferu.

00:51:40.07,00:51:51.11
Mislila sam da to nije strasno, samo[br]deo, i ako gledam pravo, sve

00:51:51.67,00:52:01.63
ce se ispraviti samo. Nisam bila[br]srecna svakog dana u braku,

00:52:02.15,00:52:09.55
da li sam se ja kresela okolo.[br]Muskarci su mi prilazili.

00:52:14.60,00:52:20.48
13 godina seksa sa istim muskarcem[br]moze postati dosadno.

00:52:21.32,00:52:26.72
Stiven je imao svoje lose poze[br]i sve sam znala, ali da li sam

00:52:27.20,00:52:29.52
se zalila, i otisla da se kresnem[br]sa kurirom?

00:52:31.92,00:52:39.60
Stiven ne zna koliko je dobra imao,[br]niko mu nece pruziti tako dobro u krevetu.

00:52:40.48,00:52:44.16
Mogla sam da isisam eksere iz[br]daske.

00:52:59.36,00:53:06.01
Pre nego sto zaspim kazem da[br]cu se probuditi sa odgovorom i

00:53:06.53,00:53:14.56
to se desi. Probaj to, naspavaj se[br]i sutra ce sve izgledati bolje.

00:53:24.45,00:53:26.52
Volim vas.

00:53:29.05,00:53:36.69
Nece ga otkaciti, znam sta osecaju[br]jedno prema drugom.

00:53:37.73,00:53:41.73
Vracamo se u ovu kucu do kraja[br]nedelje.

00:54:25.05,00:54:29.06
Ne razumem, zasto mi se to[br]desava?

00:54:31.02,00:54:43.95
To se desava u svakoj vezi, neko[br]nekoga izda, to je tako.

00:54:52.86,00:54:58.94
Sta cu da radim? -Resicemo to.

00:55:03.38,00:55:06.86
Moramo da smislimo nesto vece.[br]-Koncentrisimo se na korice,

00:55:07.47,00:55:08.47
kako da je istaknemo.

00:55:09.02,00:55:13.35
A naslov ''45-ominutni orgazam''.[br]-Ko ima vremena?

00:55:15.86,00:55:22.47
Zelim da se odvojimo od krda,[br]da se obracamo citaocima.

00:55:22.91,00:55:26.79
Zar to nismo u delu o zivljenju[br]jedinstvenog zivota?

00:55:28.06,00:55:32.79
Kazemo zenama da se dobro[br]osecaju, a onda stampamo

00:55:33.19,00:55:36.51
15 clanaka o dijetama, modeli za[br]kreme za bore imaju 20 godina.

00:55:37.59,00:55:48.31
lzludjujemo zene. -Znam da sam[br]nova, ali ja bih se koncentrisala

00:55:48.91,00:55:54.71
na temu po izdanju. Brendiranjem[br]cemo dati casopisu identitet.

00:55:55.99,00:56:03.15
Svaka tema treba da ima ostrinu,[br]humor, na primer o osveti.

00:56:03.63,00:56:09.47
Kako je napraviti, i kome je smestiti.[br]Stavimo glumicu na naslovnu,

00:56:10.03,00:56:15.67
nekoga mladog i zgodnog, nacinimo[br]sve neodoljivim, postanemo

00:56:16.07,00:56:20.12
krivo zadovoljstvo izdavastva i[br]tako to preokrenemo.

00:56:22.68,00:56:30.32
Eni, osveta, to je tako retro?[br]Zar nemamo bolje stvari?

00:56:33.39,00:56:36.04
Ja bih kupila taj casopis.

00:56:38.28,00:56:48.72
Treba da napravimo pauzu.[br]-Razmisli o tome, dobra je ideja.

00:56:51.61,00:56:58.25
Urednici se plase takvih devojaka.[br]Usetaju u tvoj svet i pitaju se

00:56:58.69,00:57:04.21
da li propustaju trendove.[br]-Mozemo li da napravimo pauzu?

00:57:05.08,00:57:05.96
Ne moze.

00:57:06.44,00:57:09.21
Kojih reci se treba bojati?[br]-Zabava pored bazena.

00:57:09.81,00:57:11.80
Nastavi da se penjes.

00:57:16.09,00:57:19.69
Spusti me. Hvala.

00:57:23.45,00:57:28.85
Bejli Smit, Silvi Fovler, upoznali[br]smo se na dodeli nagrada.

00:57:29.33,00:57:37.65
Kako ide? -Necu biti srecna[br]dok ne otkinem deo Voga.

00:57:38.93,00:57:44.41
To cu uspeti kada stavim zvezde[br]pisce u casopis.

00:57:46.01,00:57:50.33
Nisam na prodaju, srecna sam.[br]-Ne znam zasto, stekla si

00:57:50.81,00:57:57.01
reputaciju pisuci profile, a sada[br]pises tracarenja za tabloid.

00:57:57.57,00:58:04.09
U sindikatu sam, ne brinem za[br]novac. -Pisem o ljudima, ne o modi.

00:58:04.77,00:58:14.54
To i zelim na tvoj nacin. -Cujem da[br]ti je opao tiraz, i imala si neke

00:58:15.02,00:58:20.82
probleme sa osobljem prosle nedelje?[br]-Neki ne umeju da se bore.

00:58:22.06,00:58:30.38
Radila bih nesto za tebe, ali mi[br]treba nesto zauzvrat.

00:58:34.06,00:58:41.58
Radim kolumnu o njujorskim[br]brakovima, cujem da se jedan razvodi.

00:58:43.30,00:58:55.14
Ne znam. -Gadan razvod prodaje[br]vise novina od predsednicke kampanje.

00:58:55.82,00:59:01.14
Zvuci kao da si vec napisala pricu,[br]sta cu ti ja.

00:59:02.14,00:59:04.43
Treba mi potvrda od pouzdanog[br]izvora. -Ne mogu da ti pomognem.

00:59:06.11,00:59:13.54
To ne znaci da ti ne bih i ja ucinila[br]uslugu. Moj spijun je video tvog

00:59:14.10,00:59:20.26
izdavaca kako vecera sa Tajrom[br]iz Bazara.

00:59:23.19,00:59:29.51
Ned me ne bi zamenio, deli moju[br]viziju casopisa.

00:59:30.75,00:59:37.95
Cula sam da se nesto desava.[br]-Ne objavljuj to.

00:59:38.76,00:59:43.67
Kada bi ono malo osoblja nanjusilo[br]krv, unistilo bi mi kredibilitet.

00:59:46.15,00:59:53.63
Da ne poverujes kako mali trac[br]moze da otkrije celu karijeru.

00:59:56.36,01:00:00.15
Gde bi otisla kada bi napustila[br]Kase?

01:00:16.28,01:00:19.64
To je poslednji put da ti biras[br]restoran.

01:00:20.00,01:00:27.52
Mogli bi barem dobru sliku da ti[br]stave kada te vec objavljuju.

01:00:30.60,01:00:34.64
Tiha si za promenu. -Naporan dan.

01:00:37.72,01:00:41.20
Stigla je.

01:00:50.68,01:00:58.36
Svi ste to videli? -Kada pomislis[br]da ne moze biti gore?

01:01:02.72,01:01:06.21
Ako zelis da pobegnes sa zenom[br]ovo bi bilo mesto.

01:01:06.73,01:01:12.89
Margaritu i zenu. -Okrenula je stranu,[br]bice dobro.

01:01:13.65,01:01:22.93
Jesam, unajmila sam advokata.[br]-Da nije prerano?

01:01:25.73,01:01:28.69
Za mesec dana sve moze biti[br]drugacije. -Sta?

01:01:30.45,01:01:36.97
Reskiracu i reci cu da postoje dve[br]strane price. Svaka moze da

01:01:37.33,01:01:53.61
napravi veliku gresku i dobar[br]bracni savetnik bi tebe pitao

01:01:53.97,01:02:02.22
kako si ti bila kriva. -Udala sam[br]se za seronju, na cijoj si strani?

01:02:03.46,01:02:07.61
Na tvojoj. -l ja isto.

01:02:11.18,01:02:19.59
Kako se Bejli Smit gleda u ogledalo,[br]kako moze da se hrani na tudjem bolu.

01:02:20.22,01:02:29.54
Moja je krivica. Znala je da cu[br]biti otpustena i da mi treba.

01:02:29.98,01:02:39.86
Ucenila me je, nisam joj rekla nista,[br]samo je rekla da klimnem ako je istina.

01:02:40.86,01:02:50.39
Ja sam samo klimnula. Bojala sam[br]se, ljudi tada cine uzasne stvari.

01:02:56.35,01:03:05.71
Sta je sa tobom? -Borim se za[br]posao za koji radim ceo zivot.

01:03:21.07,01:03:28.51
Rekla si da je izdaja izvesna u svakoj[br]vezi, mislila sam da govoris samo

01:03:28.92,01:03:32.71
o braku, a ovo je mnogo gore.

01:03:44.19,01:03:49.43
Ne znas kako je voditi ovakvu[br]firmu. Sada setaj i ne vracaj se.

01:03:49.95,01:03:56.91
Moj otac te nece pustiti.[br]-Spavam sa tvojim ocem.

01:04:04.04,01:04:11.24
Za Boga, popodne je, tvoja kcerka[br]se uskoro vraca, zelis da ponovo

01:04:11.64,01:04:14.36
vidi svoju majku i bade mantilu.

01:04:14.72,01:04:17.40
Vise ne gledam u sat,[br]oslobadjajuce je.

01:04:27.33,01:04:36.92
Kuca Hejnsovih, dobar dan,[br]svakako ti prepoznajem glas.

01:04:44.33,01:04:48.96
Videcu da li je ovde.[br]Gdin Hejns je na telefonu.

01:04:49.97,01:04:57.01
Reci da nisam ovde. -Lose lazem.[br]-Ne zelim da razgovaram sa njim.

01:04:58.05,01:05:07.29
Ja cistim, kuvam, nisam ti majka,[br]prijateljica, sekretarica, ne mesam se.

01:05:07.77,01:05:09.89
Dodji ovamo i sredi svoje stvari.

01:05:18.46,01:05:21.61
Da, sledece nedelje cu razgovarati.

01:05:25.38,01:05:35.45
Rado bi izdubila bundevu sa tobom.[br]Hvala na pozivu, jer nemam ideju

01:05:35.86,01:05:44.33
da budem sa tobom. Rekla sam[br]ti da je gotovo, bez savetnika,

01:05:44.85,01:05:46.97
Moli ce ti se javiti.

01:05:53.62,01:05:57.94
Tako mi je zao, nisam zelela da[br]to cujes.

01:06:11.94,01:06:15.91
Znam da si tu, odgovori mi,[br]moramo da razgovaramo.

01:06:16.71,01:06:19.42
Javi se.

01:06:59.99,01:07:06.23
Mogu li da vam pomognem?[br]-Sto mi se sunjate?

01:07:07.15,01:07:11.11
A sto vi opsedate kucu kao[br]jehovin svedok?

01:07:11.63,01:07:45.24
Trazim Meri, ostavila sam joj poruke[br]nije mi se javila. -Nije tu.

01:07:15.71,01:07:22.55
Gde je? -U gradu. -A Moli?[br]-U skoli kao i ostala deca.

01:07:25.28,01:07:33.60
Gotovi smo, posto vase cipele[br]unistavaju moje perunike?

01:07:58.80,01:08:01.24
Dzejson je, ozbiljna si?[br]Pita ga da li mu se dopadam. -Ne ti.

01:08:05.00,01:08:13.32
Ko je to? -Mamina prijateljica,[br]bolje idi. Vidimo se.

01:08:20.68,01:08:27.44
Mali je svet, zasto nisi u skoli?[br]-Nije mi se islo.

01:08:30.45,01:08:36.29
Ovo ti je nov izgled. -Odem iz[br]kuce u uniformi i onda se preobucem

01:08:37.13,01:08:47.81
nakon skole, to rade mnoge.[br]-Pametno. Nemas cigaretu?

01:08:52.65,01:09:00.77
Hvala. Zna li ti mama da pusis?[br]-Ne, i nemoj joj reci.

01:09:01.85,01:09:06.33
To radim da ne bih jela.[br]-Tezina ti je u redu.

01:09:07.09,01:09:11.85
Mrzim svoje telo, zelim da izgledam[br]kao modeli iz tvog casopisa.

01:09:12.25,01:09:17.33
Niko ne izgleda kao one, ni one same,[br]sve su retusirane.

01:09:18.45,01:09:24.13
Zasto ne stavis obicne ljude?[br]-Licemerno je, zivot je komplikovan.

01:09:26.38,01:09:31.45
To tek sada provaljujem.[br]-Zelis da razgovaras o tome?

01:09:32.94,01:09:34.66
Ne.

01:09:40.62,01:09:45.90
Sa koliko si godina imala seks?[br]-Trideset.

01:09:49.18,01:09:56.90
Bilo je uzasno i bolelo je, bilo me[br]je blam jer nismo imali pojma sta radimo.

01:09:57.90,01:10:03.26
Bili smo u njegovoj sobi, poster[br]Fare Fosit je buljio na krevet sa

01:10:04.46,01:10:12.55
posteljinom zvezdanih ratova.[br]Dugo se posle nisam seksala.

01:10:13.15,01:10:18.59
Onda sam upoznala nekoga i[br]vredelo je cekati.

01:10:19.07,01:10:25.27
Voleli smo se i sve je bilo lako.

01:10:25.83,01:10:32.59
Govoris mi ono sto bi mi rekla[br]mama, nemoj dok nisi zaljubljen.

01:10:35.39,01:10:43.71
Bilo je dobrog seksa, ali nije odlican[br]dok neko ne voli tebe i ti njega.

01:10:44.83,01:10:47.99
Bila bi super mama. -Stvarno?

01:10:56.43,01:11:02.15
Ne bi bila kao moja, mozemo da[br]budemo u istoj sobi i kao da nije tu.

01:11:03.83,01:11:12.47
Znam da ti je tesko i ako hoces[br]ikada da pricas o necemu, nazovi me.

01:11:13.55,01:11:20.79
Obecaj mi. -Obecavam.[br]-Gde ti je majka?

01:11:24.92,01:11:27.88
Udahnite duboko.

01:11:30.12,01:11:37.56
Pogledajte oko sebe i postujte moc[br]prirode, dosli ste u kamp da vas isceli.

01:11:40.04,01:11:44.40
Koliko je razvedenih?

01:11:45.64,01:11:50.93
Cekajte me. Zao mi je.

01:11:58.12,01:12:03.44
Uvek pocinjete u ovo vreme,[br]jezero ce biti ovde i u podne.

01:12:04.80,01:12:10.72
Kanue uvek vozimo u zoru.[br]-Foliram orgazme, to nije ispravno.

01:12:09.09,01:12:12.70
Uzdignite, zamahnite.

01:12:24.97,01:12:26.73
Marsirajte.

01:12:43.05,01:12:44.81
Molim te...

01:12:47.81,01:12:54.98
Zaboravi, vec sam pokusala.[br]-Uplasila si me.

01:13:01.57,01:13:10.69
Lia? Meri. Gladna sam, videla[br]si sta su nam stavili na tanjir?

01:13:13.54,01:13:17.38
Vec sam dva puta bezala.

01:13:22.37,01:13:29.02
Kako si to unela, sve su mi oduzeli?[br]-Sprijateljila sam se sa rendzerom.

01:13:33.93,01:13:42.06
Mislila sam da sam sve ostavila,[br]gde ti smrt pise scenario?

01:13:43.74,01:13:47.42
On mi je nabavio dzoint, ja sam[br]mu sredila posao.

01:13:47.98,01:13:58.43
Od kada si agent? -1852. i zovu[br]me groficom i sve mogu da

01:13:58.83,01:14:05.03
pretvorim u zvezdu, cak i rendzera.[br]Tako je sladak.

01:14:05.58,01:14:09.71
On je sladak, meni je dosadno,[br]kucica za goste je prazna,

01:14:10.11,01:14:13.66
moze da se ispostavi sledeci[br]Majkl Daglas, djubre koje me je ostavilo.

01:14:15.15,01:14:21.63
Za sta si ti? -Pobegla sam od kuce,[br]dobila sam otkaze sa svih poslova,

01:14:22.39,01:14:28.15
majka, zena, kcerka, a onda se[br]posvadjala i sa najboljom prijateljicom

01:14:28.63,01:14:33.91
sto je bilo najgore. -Ja sam pobegla[br]od cetvrtog muza.

01:14:34.75,01:14:38.87
Petog. Stalno ga odbijam jer je[br]pokusao da me ubije.

01:14:39.51,01:14:45.71
Sta? -Bili smo na skijanju u Aspenu[br]i pala sam sam. -Sta si uradila?

01:14:46.67,01:14:55.72
Dok sam ga ja sredila od njega nije[br]ostalo nista sem kose i dupeta na putu.

01:14:58.47,01:15:07.12
Zasto se onda udajes?[br]-Na kraju je samo ljubav u pitanju.

01:15:10.83,01:15:15.08
Daj mi to, nisam radila to od[br]kada sam bila brucos.

01:15:27.32,01:15:33.68
Ja sam dobra osoba, trudim se da[br]uradim ispravnu stvar.

01:15:35.16,01:15:39.96
Propustim osobu iza sebe u redu,[br]dajem novac beskucnicima,

01:15:40.80,01:15:46.32
recikliram i nikada ne varam.[br]Jesam jednom.

01:15:48.88,01:15:55.84
lgrala sam monopol i pomerila[br]figuricu nekoliko mesta napred.

01:15:56.28,01:15:59.05
Bili smo deca pa se to ne racuna.

01:16:04.41,01:16:13.73
Moracu da resim zasto mi se[br]ceo svet srusio.

01:16:16.33,01:16:22.93
Ceo zivot se trudim da budem[br]neko svakome i uvek je neko razocaran.

01:16:24.37,01:16:31.49
Nekada postoje razlozi sto se neciji[br]putevi susrecu.

01:16:32.53,01:16:39.89
Dacu ti tajnu zivota, ne cimaj se[br]ni za koga, budi sebicna jer

01:16:40.33,01:16:47.85
kada se jednom zapitas gde si ti[br]sve se promeni na bolje.

01:16:48.81,01:16:56.90
lpak, ko si ti, sta ti zelis?

01:17:21.22,01:17:24.33
STA JA ZELlM?

01:18:19.75,01:18:25.31
DRAGA MERl, ZAO Ml JE

01:18:57.08,01:19:05.72
lzvinite, trazim svoju majku[br]Ketrin Frejzer?

01:19:07.55,01:19:13.00
Jos ima bolove, unutra je. -Hvala.

01:19:21.48,01:19:24.28
Mama?

01:19:29.72,01:19:34.28
Mama? -Meri, ovamo.

01:19:37.16,01:19:46.32
Boli li? -Potrosila sam hiljade dolara,[br]naravno da boli. Odlicno izgledas.

01:19:47.20,01:19:52.04
Hvala, ne mogu da verujem da si[br]uradila ovo.

01:19:52.68,01:20:04.72
Bila sam jedina zena od 60 godina.[br]-Uvek si mi govorila da ne zalim.

01:20:06.00,01:20:15.09
Samo serem, mnogo toga zalim.[br]Sto nisam nista sama postigla.

01:20:16.21,01:20:24.22
Bila sam ambivalentna, zelela sam[br]veliku kucu, lepu odecu.

01:20:25.29,01:20:30.57
Bilo je lakse steci steci status od[br]tvog oca nego da to uradim sama.

01:20:31.73,01:20:37.77
Znam da sam te izneverila ali[br]verovatno ne negde vise.

01:20:40.57,01:20:43.57
lmas malo caja.

01:20:46.74,01:20:57.17
Razmisljam o tome da dizajniram[br]svoju kolekciju. -Sta je izazvalo to?

01:20:57.65,01:21:02.18
Udaranje o dno, nemam sta da[br]izgubim, preporucujem.

01:21:02.86,01:21:09.05
Da ne boli, sada bih se smejala.

01:21:09.57,01:21:11.70
Samo mala kolekcija.[br]-Gde ces nabaviti novac?

01:21:14.38,01:21:21.31
A moje nasledje? Nista nisam uradila[br]sa tim. Sta bi bila bolja investicija?

01:21:22.23,01:21:26.42
Nisam zato dosla.[br]-Ne mogu da se svadjam.

01:21:31.78,01:21:35.14
Kada budem jednom sedela ovde[br]sa glavom u slemu nadam se da

01:21:35.46,01:21:43.62
ce me moja kcerka voleti koliko[br]i ja tebe. -Seres i vise od mene.

01:22:19.51,01:22:26.04
Nede, molim te, znam da nije[br]najjace izdanje, sledeceg meseca

01:22:26.68,01:22:37.56
ce Bejli Smit napisati profil i[br]Aleks Fiser ima nove materijale.

01:22:40.03,01:22:47.80
Ne mozes to, niko ne obrce casopis[br]za godinu dana, daj mi jos tri izdanja.

01:22:49.44,01:23:04.51
Da uradimo izdanje o osveti,[br]kako napraviti pravu glasinu,

01:23:05.72,01:23:12.44
kako se osvetiti i da stavimo[br]zgodnu mladu glumicu na naslovnu.

01:23:18.16,01:23:28.69
Hvala, i ja mislim da ce biti[br]izuzetno. Vidimo se ujutru.

01:23:32.72,01:23:42.84
lma li koga, Moli?[br]Gde su svi? -Ovde.

01:23:44.24,01:23:54.01
Sva tkanina iz ltalije nije stigla,[br]i model se nije pojavio, ali ce biti dobro.

01:23:54.85,01:24:05.33
Gde je Moli? Sta radi?[br]-Kaze da ne zeli da bude zena.

01:24:10.05,01:24:21.22
Bas si napravila vatricu.[br]-Pocela sam sa obicnim, sada dodajem.

01:24:27.93,01:24:35.49
Zar ne bi bilo dobro da ti daju[br]prirucnik za sve kada se rodis?

01:24:42.25,01:24:46.22
Zalila sam decu iz razreda, svakog[br]drugog vikenda sa tatom dok

01:24:46.50,01:24:53.22
mamin decko ne prespava, onda[br]tata ima dve. Zalila sam ih ranije,

01:24:53.66,01:24:55.54
sada sam jedna od njih.

01:24:56.14,01:25:02.62
Znam da nisam bila tu za tebe.[br]lmamo mnogo o cemu da pricamo.

01:25:03.30,01:25:08.50
Ne mogu da pricam sa tobom kao[br]sa Silvi. -Razgovarala si sa njom?

01:25:09.54,01:25:13.74
Pomagala mi je. -Zasto mi ne das[br]da ti ja pomognem?

01:25:14.46,01:25:18.71
Samo mi govoris da ce sve biti[br]u redu, a nece.

01:25:19.23,01:25:27.42
Tata zivi u stanu bez namestaja,[br]Kristal stalno dolazi, ni ne najavi se.

01:25:28.34,01:25:39.14
Onda ostavi haljinu, ni ne dopada[br]mu se, usamljen je i nedostajes mu.

01:25:39.98,01:25:50.75
Ne mogu. -Posmatrala sam se kako[br]se spremas da izadjes sa tatom.

01:25:51.62,01:26:01.15
lsprobavala sam tvoje haljine i[br]stikle i stavila bih karmin.

01:26:01.59,01:26:09.23
Zelela sam da budem ti.[br]Nazvacu Silvi.

01:26:35.04,01:26:38.56
Meri? -O cemu razgovaras sa[br]mojom kcerkom?

01:26:39.04,01:26:43.23
Obecala sam da ti necu reci.[br]-lma probleme i sada si diskretna.

01:26:44.52,01:26:50.64
Ako joj treba bezbedno mesto.[br]-To sam ja, ja sam majka, ne ti.

01:26:51.24,01:26:57.40
Kaze da me voli. -Pokazi mi strije[br]i budi majka.

01:26:58.44,01:27:04.04
Sta je ovo, slobodan petak, sreda je.[br]-Znam. -Sta je bilo?

01:27:05.96,01:27:10.68
Nisam htela da uzrokujem probleme,[br]samo da pomognem.

01:27:11.24,01:27:13.37
Ne umaras se da govoris to?

01:27:16.36,01:27:19.21
Kako se usudjujes da popujes sto[br]sam uskocila tamo gde je ti trebalo

01:27:19.61,01:27:26.13
da budes sve vreme? Nisi bila[br]tu ni za koga, kada ne mozes

01:27:26.45,01:27:29.40
da se suocis sa problemima.[br]-Ne osudjuj me.

01:27:30.04,01:27:33.33
Kada ti Moli veruje, izdaces nju,[br]kao sto si i mene?

01:27:33.77,01:27:38.33
Znas li koliko je tesko biti tvoj prijatelj.[br]Sve sam uradila da ti nadoknadim,

01:27:38.73,01:27:42.09
Sta jos zelis? -Da znam kako mozes[br]da prodas najbolju prijateljicu.

01:27:42.69,01:27:45.37
Nadam se da je posao vredan[br]toga, jer samo to imas.

01:27:45.97,01:27:52.73
Dala sam otkaz. Pravila sam uzasne[br]kompromise. -Ne mogu da verujem.

01:27:53.20,01:27:58.89
Kako mogu da budem tako udarena[br]da prodam najbolju prijateljicu.

01:27:59.33,01:28:03.09
Bila si u nemogucoj situaciji, naravno[br]da zelis da zadrzis svoj posao.

01:28:03.77,01:28:06.90
To je ono sto radis i dobra si u tome.[br]-Nije nista kao odgovornost prema detetu.

01:28:07.37,01:28:11.06
Ne znam kako ti uspeva.[br]-Uzasna sam majka, ne mogu

01:28:11.94,01:28:15.53
ni da razgovaram o seksu ni sa[br]svojom kcerkom. -Meni je lako.

01:28:16.13,01:28:23.54
Nisam joj ja menjala pelene.[br]-Pomazes mi i mnogo ti hvala.

01:28:26.33,01:28:32.81
Sta god mogu. lmas veliki posao.[br]Drago mi je da nisam imala decu.

01:28:33.29,01:28:37.42
To je poslednje neoprostivo za[br]vecerom sto mozes reci.

01:28:38.13,01:28:43.10
Napravicu veceru pa reci to.[br]-lzmorena sam.

01:28:49.42,01:28:52.42
Dopada mi se tvoja kosa.

01:29:06.26,01:29:10.90
Danas sam dobila papire za[br]razvod, samo treba da ih potpisem

01:29:11.38,01:29:14.87
a ne mogu da nadjem olovku.

01:29:15.67,01:29:20.67
21. vek je i u redu je da se ljudi[br]bore za svoje veze.

01:29:22.51,01:29:34.43
Osecaj je kao da izgubis deo tela,[br]ali jos imas osecaj da je tu.

01:29:35.95,01:29:43.11
Stiven sigurno oseca isto.[br]-Ne govorim o njemu, nego o tebi i meni.

01:30:09.31,01:30:13.88
Zdravo, secas me se. Nokti su[br]mi uzasni, imas li vremena?

01:30:14.28,01:30:16.83
Nema problema.

01:30:22.67,01:30:27.91
lmala sam divni facijelni tretman.[br]-Kako ide sa vas dvoje?

01:30:28.83,01:30:36.32
Odlicno, seks je fenomenalan.[br]-Ljubomorna sam.

01:30:41.24,01:30:45.04
Nista nije kao afera sa otudjenim[br]muzem da se povrate stvari.

01:30:47.80,01:30:54.72
ldiot sam, moram da razmislim pre[br]otvaranja u usta, lepo te je videti.

01:30:58.01,01:31:04.09
Ne vidjas se sa Kristal? Oprosti[br]mi, zivot mi je dovoljno komplikovan.

01:31:07.28,01:31:12.33
lzabrali ste boju? -Dzungla crvena.

01:31:18.17,01:31:22.57
Sigurna si? Ne mogu da verujem[br]da se vidja sa njom.

01:31:23.21,01:31:27.73
Gotovo da zivim sa njim. Niko vise[br]ne postuje pravila?

01:31:30.09,01:31:36.41
Otac me vodi kuci.[br]-Uplasila si me. Moram da idem.

01:31:37.13,01:31:40.45
Da se oprostim. -Poljubi me.

01:31:42.53,01:31:46.85
Provele smo ceo vikend zajedno.[br]-Toplo je, a imam kaput na sebi.

01:31:49.41,01:31:54.61
Laku noc. -Laku noc, sta?

01:31:57.38,01:32:00.29
Rekla sam ti da me zoves[br]teta Kristal. -Ne zelim.

01:32:01.85,01:32:07.01
Ubih se da budem fina, sredila[br]sam ti sobu, napravila divnu veceru.

01:32:07.77,01:32:14.25
Napravila si makarone sa sirom.[br]-Trudim se, sto neces ti?

01:32:15.02,01:32:23.38
Ne dopadas mi se.[br]-Kako je to glupo, svima se dopadam.

01:32:24.33,01:32:27.22
Sta bi rekao tvoj otac da vidi[br]da razgovaras sa mnom tako?

01:32:27.62,01:32:30.65
Mislim da ga nije briga.[br]-Sta si cula da je rekao?

01:32:36.30,01:32:40.26
Necu doci sledeceg petka, mama[br]pravi modnu reviju.

01:32:41.38,01:32:52.74
To je uvek zelela da uradi, tata[br]misli da je divno i seksi na neki nacin.

01:32:59.66,01:33:02.83
Uzivaj u kupanju.

01:33:07.27,01:33:10.22
Stivi?

01:33:18.07,01:33:24.03
Ne znam sta rade kod tebe, ali[br]se ne baca, nego namesta.

01:33:24.95,01:33:33.87
Spremna sam. -Veliki je dan,[br]ne znam kako si tako mirna.

01:33:34.99,01:33:40.63
Mora da zizis iznutra. -Uta?[br]-Dobro sam, uvek sam se videla.

01:33:43.43,01:33:50.11
Nije bitno sta ce biti veceras, bitno[br]je da si se pojavila.

01:33:50.67,01:33:59.48
Uvek sam znala da u tebi postoji[br]neko drugi. -Hvala ti, volim te.

01:34:06.28,01:34:22.16
ldem i Uta, dovesces Moli[br]za sat. -U vezi ste?

01:34:22.68,01:34:28.48
Ucuti i ukrasavaj.

01:34:45.92,01:34:50.49
Tebe treba pustiti na Diskaveri.

01:35:09.89,01:35:18.20
Svi najbolji butici su ovde.[br]-Otac je svratio ranije i rekao

01:35:18.60,01:35:22.69
da ti kazem da nije mislio da imas[br]ovoliki talenat. -Fantasticno.

01:35:23.13,01:35:25.17
Ne budi ogorcena, to vodi u[br]botoks.

01:35:25.85,01:35:31.69
Ne znam za otvaranje i razmisli[br]o rasporedu kaputa.

01:35:33.21,01:35:37.57
Kada si rekla da si me potcenila,[br]nisam mislila da ces svracati

01:35:37.93,01:35:41.45
svakih pet minuta sa sugestijama.[br]-Rekla si da cenis moje misljenje.

01:35:41.98,01:35:47.33
To kazes kada uzmes mnogo novca[br]od nekoga, to niko ne misli. Smesti se.

01:35:47.90,01:35:50.25
Pogledaj ponovo kapute.

01:35:51.65,01:35:54.06
Mrsavo.

01:35:59.82,01:36:04.21
Sta je ovo? -Stiglo je od tate upravo.

01:36:15.69,01:36:18.90
Ovo je stvarno kul.

01:36:41.98,01:36:44.70
ZELlM DA TE PONOVO UPOZNAM.[br]JESAM Ll PROPUSTlO SVOJU

01:36:45.31,01:36:47.98
PRlLlKU? VOLl TE STlVEN

01:36:52.11,01:36:59.23
Zdravo, ldi. -lzgledas odmorno.

01:39:20.97,01:39:23.17
Tako sam ponosna na tebe.

01:39:25.13,01:39:34.25
Sve je predivno. Cak sam malo i[br]ljubmorna.

01:39:34.73,01:39:38.62
To je vise nego sto treba da znam.[br]-Povescu Moli.

01:39:44.74,01:39:50.54
Reci mi iskreno. -Transformisuce,[br]ali nije bitno, ovo je dama cije je

01:39:50.86,01:39:56.22
misljenje bitno, Glenda Hil, glavni[br]kupac Saksa.

01:39:59.54,01:40:01.42
Nisam znala da dolazite.

01:40:03.70,01:40:06.74
Silvija me je pozvala i insistirala da[br]dodjem i rekla da cu propustiti nesto i

01:40:07.26,01:40:08.86
bila je u pravu.

01:40:13.26,01:40:17.62
Mala je kolekcija, ali je sveza i[br]napredna, verujem da ste

01:40:17.98,01:40:25.47
otvoreni za promene za kupce[br]Saksa. Linija ovde, sako onde.

01:40:26.10,01:40:30.23
Salks ce naruciti moju odecu?[br]-Pocecemo sa radnjom u Njujorku.

01:40:30.63,01:40:34.46
Ako dobro prodje, prosiricemo na[br]svih 59 radnji.

01:40:35.06,01:40:41.62
Sve nam treba dostaviti do proleca.[br]Moci cete to? -Zbunjena je.

01:40:43.51,01:40:51.94
Mogu li da razmislim?[br]-Nemojte predugo.

01:40:57.87,01:41:01.47
Bilo je predivno i tako smo[br]ponosni na tebe.

01:41:01.95,01:41:06.99
Zao mi je sto necu moci da ostanem[br]da slavimo, ali mi je pukao vodenjak.

01:41:08.87,01:41:10.19
Sta?

01:41:13.07,01:41:16.64
Na pravom smo mestu?[br]-Boli te.

01:41:21.67,01:41:23.95
Svaka beba izadje brze od one[br]prethodne.

01:41:24.47,01:41:26.07
Poslednji je trajao dva sata.

01:41:26.99,01:41:30.75
Prijateljica nam se poradja, treba[br]nam soba i da pozurite.

01:41:31.27,01:41:35.72
lma li osiguranje? -Ne treba joj,[br]smestite je u sobu.

01:41:37.67,01:41:42.40
Evo jedne. -lma minut.

01:41:44.43,01:41:47.60
ldemo u porodjajnu salu, ko ce sa njom?

01:41:48.40,01:41:50.31
Zelim da Aleks to uradi. -Ja?

01:41:50.71,01:41:54.44
Mislim da ce ti to biti odlicno[br]iskustvo, ne brini, ja cu te sprovesti.

01:41:57.24,01:41:59.00
Mora da je velika beba.

01:41:59.44,01:42:01.84
Ne upiri to u mene, napunjeno je.

01:42:06.16,01:42:11.08
Glenda Hil je prototip ukusa, zasto[br]nisi pristala.

01:42:11.72,01:42:14.09
Ne zelim toliku narudzbinu.[br]-Ne zelis uspeh?

01:42:14.53,01:42:19.60
Zavisi kako ga zelis. Bila bih[br]srecna sa malim butikom.

01:42:20.01,01:42:24.80
lmam kcerku kojoj trebam sada.[br]-Videla te je na drugi nacin.

01:42:25.48,01:42:27.40
Pruzila si joj majku koja ima nesto[br]za sebe, to je vazno.

01:42:29.40,01:42:34.88
Mozemo imati sve, pitanje je da li[br]to zelimo. -Ja zelim samo deo.

01:42:35.56,01:42:38.01
Ni ja, jer to zamara.

01:42:40.65,01:42:46.09
Znas li ti kako je tebe voleti?[br]-Zanimljivo, upoznala sam tipa.

01:42:48.61,01:42:51.25
Mislim se da mu dam pravi broj.

01:42:54.77,01:43:04.21
Ne razmisljaj, nego kakav je osecaj.[br]-Ne mogu da pricam, leptiri u stomaku.

01:43:04.97,01:43:08.53
Kako kada sam nasla psa u stenari.[br]-Blizu smo, udjite.

01:43:13.21,01:43:18.18
Zelim svog smokljana.

01:43:20.85,01:43:23.66
Sta je tako komplikovano, samo...

01:43:24.14,01:43:28.61
Neka neko dodje dok joj se[br]ne zavrne glava. -Ja cu.

01:43:29.06,01:43:31.57
To je dzungla crveno, lepo.

01:43:34.98,01:43:38.14
Evo jos jedne kontrakcije.

01:43:49.46,01:43:53.02
Nikada se necu seksati ponovo,[br]zasijte me.

01:43:53.90,01:43:58.26
Prosla si kroz ovu, kako joj je?[br]-lmamo jos nekoliko guranja,

01:43:58.70,01:44:02.26
beba ima veliku glavu.[br]-Vidi li se?

01:44:10.35,01:44:13.02
Ja sam. Stivene?

01:44:15.95,01:44:21.51
ldi, koncentrisi se na jelku.

01:44:40.19,01:44:42.87
To je bila dobra.

01:44:43.82,01:44:48.03
Necu uspeti. -ldi se poradja,[br]nazvacu te.

01:44:48.59,01:44:50.79
Ne prekidaj, razgovaraj sa njim.

01:44:52.11,01:44:53.67
Zeli sastanak. -Dobro je.

01:44:55.87,01:44:58.07
Prevazici ces, kao sto je Alen uradio.

01:45:03.91,01:45:10.07
Nemoj biti sokirana, pre pet godina[br]se desilo, gotovo da ga je ubilo

01:45:10.51,01:45:14.91
i to je gotovo ubilo mene, ali mi je[br]oprostio, ne odmah, ali jeste, a

01:45:15.35,01:45:21.03
znas zasto, jer je dobar covek,[br]znao je da ga volim.

01:45:21.67,01:45:25.32
Volimo se i volimo decu i prekinucu[br]jer sam izmorena i zelim da ovo

01:45:25.72,01:45:29.51
dete izadje iz mene. Vadi ga.

01:45:31.56,01:45:36.96
Stiv, kako da se osiguram kada[br]ne znam ko sam bila.

01:45:37.72,01:45:42.20
Sada zelim neke stvari i svako ko[br]je deo mog zivota mora da zeli

01:45:42.68,01:45:48.40
te stvari za mene, ali ce biti tesko.[br]Ne desava se preko noci.

01:45:48.88,01:45:53.60
Ako prihvatis to, videcemo se u[br]utorak u osam, to je slobodno.

01:45:54.36,01:45:58.48
Zauzeta sam. -lzlazimo.[br]-Moram da idem.

01:46:02.90,01:46:05.59
Guraj.

01:46:15.57,01:46:21.89
Cestitam, decak je.

01:46:26.36,01:46:30.68
Uspela sam.

01:46:55.86,01:46:59.89
Boze...

