{1}{1}25.000
{26}{176}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1392}{1466}PRAVEDNO UBISTVO
{2032}{2122}Jedan, meu oËi.
{2154}{2226}Meu oËi.
{2916}{2956}Napolje. -äta?
{3034}{3074}Bila je na bezbednom.|-Bila je napolju.
{3084}{3148}Tu je stala, bila je bezbedna.
{3212}{3298}Dosta, neÊu da Ëujem ni jednu|reË.
{3322}{3366}Smiri se.
{3519}{3596}Baka me je vodila da gledam.
{3637}{3728}Gledaö Bobija Fiöa kako igra|deset partija istovremeno.
{3750}{3948}Bio je 5,6 poteza ispred na svakoj tabli.|Postao je svetski öampion i onda poludeo.
{4047}{4180}Postao je paranoiËan, toliko da nije|video niöta pred sobom.
{4350}{4416}Mat.
{5144}{5364}Zovem se Dejvid Fisk, detektiv prve|klase, radim u policiji skoro 30 godina.
{5388}{5614}Za to vreme ubio sam 14 ljudi.|-Pusti to joö jednom.
{5642}{5760}Ubio sam 14 ljudi. -Lud je.
{5824}{6020}Kada je sve poËelo? Kako?
{6132}{6244}Moûda je poËelo sa »arlsom Rendalom.
{6348}{6546}Bio je ubica dece, ubio je kÊerku|svoje devojke pre oko Ëetiri godine.
{6692}{6772}Bio je optuûen, ali ga je porota oslobodila.
{7144}{7361}Partner i ja smo to smatrali|neprihvatljivim. Moj partner je dobar Ëovek.
{7879}{7982}Stvarno Êeö uraditi to?|-äta?
{8004}{8110}SrediÊeö Rendala za ubistvo koje|nije poËinio?
{8278}{8438}Ti si moj partner, moj uzor.|To se ne radi.
{8508}{8630}Nikada nismo vodili ovaj razgovor.|-Koji?
{9100}{9174}Sredio sam.
{9268}{9374}Rendal je izgubio slobodu za zloËine|koje nije poËinio.
{9508}{9572}Ja sam izgubio svoju veru.
{9618}{9674}Idem. -Dobro.
{10040}{10108}Shvatite ovo kao priznanje, pre nekoliko|nedelja su se stvari zagrejale.
{10118}{10304}äta imamo? -Markus Smit, poznat|kao Pauk, diler, iznuda, ubistvo, dosta toga.
{10332}{10474}Preobratio je staru zgradu u klub 404|u Harlemu. Moûda prizna kada nas vidi.
{10484}{10598}Ne verujeö u Ëuda? -Kada jednom|budeö uzeo raËun, verovaÊu.
{10614}{10694}Idemo, ja Ëastim.|-To je Ëudo koje ûelim da vidim.
{11108}{11210}Ovde pere novac. -»isti zelembaÊe.
{11260}{11374}Sve je to posao. -Moram da pustim mlaz.
{11622}{11746}Samo tren, neÊu da virim.|-Nema problema.
{11844}{11906}Momci imaju sreÊe. -Zaöto?
{11918}{12164}Nema redova do wc-a i piökite|stojeÊi, otkopËate, otresete, zakopËate.
{12210}{12342}HoÊeö ömrk? -Odakle ti?
{12360}{12460}Od Pauka, prvoklasno je.
{14066}{14170}Nije loöe. -äta si htela?
{14212}{14426}Turk, vukao si me za kosu.|Sestra me je jaËe vukla. -Kako god.
{14512}{14570}Bolje idi.
{14822}{14894}Kuda Êeö ti? -U penziju.
{14909}{15006}Ovo je Amerika, ui u taksi da|zaradiö poöteno.
{15024}{15077}Krenula je, jedva Ëekam da je vidim.
{15088}{15188}Rendalov beg i makro su bili moje|deseto ubistvo.
{15232}{15380}Smatrajte me ËistaËem ulica, Ëistim|ono öto su ova ubrad ostavila.
{15634}{15732}Moramo saznati ko je uradio ovo.|-DaÊu mu orden.
{15744}{15830}Ko je uradio ovo? -NeÊe da priËa.
{15860}{15950}Pravo ime Robert Brejdi. -äteta.
{16032}{16155}Opet ste na mom mestu zloËina.|-Ne znaö ko je Bobi Brejdi?
{16164}{16216}Upoznala sam ga pre oko sat vremena.|-Deluje izbliza.
{16226}{16370}Po tragovima oko rane rekla bih|na oko metar. NeÊemo Ëuti njegove öale.
{16380}{16514}äta? -»ula sam za Grega, dobar|je, Pevcu. -To je bilo brzo.
{16522}{16558}Samo te pratim u korak.
{16648}{16764}Trguje grehom, diluje meso, bere|plodove kada su sveûi.
{16780}{16934}Sada neko mora da mu udari kurvu,|srce mu je stalo, ne diöe viöe.
{17026}{17130}äta ûeliö sa ovim? -Da iskoristimo|najbolje.
{17180}{17236}Moûda Êemo upoznati neku koja|ti se dopada.
{17258}{17344}VeÊ mi je dosta od-znaö-koga.|-Ne zezaj.
{17354}{17410}Toliko mi je ispraznila spermatozoide|da moram da sednem kada piöem.
{17442}{17480}Mogu da zamislim. -äta da ti kaûem.
{17550}{17668}Izvolite? -Razgovarali bismo o vaöem|öefu. -Gore je.
{17694}{17732}Drugom öefu.
{17892}{17954}On je seronja. -Zaöto?
{17996}{18050}Poite za mnom.
{18180}{18228}Znate nekoga ko bi ûeleo da ga|ubije? -Ja.
{18260}{18338}Joö neko? -Mrtav je?
{18368}{18484}Opametite se i pomozite nam ili|Êu zvati nekog iz imigracionog i
{18494}{18530}da vas poöaljem sledeÊim avionom.
{18540}{18614}Samo napred, Amerikanka sam.
{18724}{18874}Pozovite nas bilo kada ako Ëujete|neöto.
{18928}{18996}Mislim da traûimo Sema mesara.|-Koga?
{19044}{19290}Ozbiljno, koliko daleko ûelite da odemo?|-Da istraûite joö malo, provalite ko je
{19300}{19344}i smestite ga u zatvor, ako vam|to ne smeta za obuku.
{19374}{19484}Radimo i na dileru Pauku koji je|povezan sa novim ubistivima.
{19558}{19658}Moûemo da ih zakucamo ko zna|koliko i da odemo.
{19668}{19762}äta s tim? Naiöao sam na advokata koja|mi gotovo trlja nos, pa sam naiöao na njega.
{19774}{19880}SreÊni kres. -Za njega se direktno|kresala. -Jeste.
{19910}{20038}Izvucite öta moûete i onda je oslobodite.|Mrzim da gonim proklete advokate.
{20240}{20324}Ovo nije Paukov klub.|-Pozadi smo.
{20356}{20518}Ovo je napuötena fabrika.|-Nisam proseËna krtica.
{20576}{20742}ObiËno je neka siromaöna afro-amerikanka,|narkomanka ili prostitutka.
{20806}{20874}Advokati su pametniji od|afro-ameriËkih narkomana.
{20888}{20970}Uglavnom, ali nekada samo misle|da jesu.
{20980}{21056}Sve je spremno. -Sigurno je bezbedno?
{21068}{21130}Reci devojci da poËne.
{21160}{21266}Spremna za ovo?|-Da zavröimo s tim.
{21290}{21462}Ueö unutra i Ëekaö da te pita ono|öto tebi treba i ne vraÊaö se ovde
{21472}{21604}sa manje od 4 unci. -4 unce, to je|mnogo, kupujem samo malo u klubu.
{21614}{21694}Samo reci da ti treba sveûi prah za|vikend. -Reci da ideö na odmor.
{21798}{21960}Posle ovoga Êe mi dosije biti Ëist.|Niko iz moje firme neÊe znati?
{21974}{22028}Nikada se nije desilo.
{22042}{22174}Znamo da si bolja od ovoga, uradi ovo|i prestani da guraö to u nos.
{22184}{22254}Ideö kuÊi, udaö se i dobijeö decu|i nikada se ne vratiö ovde i to je to.
{22432}{22468}Moûemo. -Da, gospodine.
{22610}{22722}Dûesika, slomij nogu.
{22772}{22858}Vrata s leve strane, zvoni.
{23052}{23178}Dovedi nam druötvo ovde.|Hajde, debeljko.
{23290}{23328}KreÊemo.
{23526}{23582}Dobar dan. -Zdravo.|-Idem dole.
{23626}{23770}Kako si? -Si videla ovo?
{23802}{23932}On je opasan diler, sve se pretvara|u ubre. -U pravu je.
{23946}{24024}SeÊaö se podzemnog psa?|-äta sa njim?
{24034}{24076}On je proizveo generaciju narkomana.
{24084}{24228}Pretvorio si prostor u klub i studio?|-Dopada ti se? -Da.
{24288}{24450}äta je podzemni pas radio sve vreme?|Glancao je cipele, i uvek je spasavao nekoga.
{24462}{24624}Ali öta je radio za super snagu?|-Odlazio je u ring, vadio tabletu i gutao je.
{24644}{24702}U pravu si.
{24716}{24860}äta se radi? -Nestalo mi je belog.|Ti ga imaö.
{24870}{24974}Idem na skijanje sa prijateljima,|sa mnogo njih. -Gde?
{24986}{25100}U Aspen, Koloradu.|-Mogu da ti pokaûem.
{25110}{25162}Ti imaö prvu klasu.
{25172}{25294}Skijaö? -Naravno, ceo ûivot.|Nemamo ceo dan.
{25324}{25508}Spusti jaknu i ostani malo.|-éurim, imam ugovor.
{25546}{25682}äalio sam se, o'ladi. -O'laena sam.
{25692}{25736}äta Êemo?
{25816}{26004}Vi kuËke sa istoËne strane uvek|naleÊete na crnju kao öto sam ja.
{26028}{26084}Sada se bojiö?
{26144}{26204}Izgleda da je doöla konjica da te|spase.
{26250}{26314}Izvolite? -Pusti nas unutra.
{26323}{26386}Izvinite, ovde nema nikoga pod|tim imenom.
{26396}{26450}Samo ûelimo da razgovaramo.
{26508}{26578}Znam kako i gde da traûim.
{26712}{26776}Doi tatici.
{26808}{26866}Uvek boli prvi put.
{26878}{26992}Dobro si? -Zaöto ne bi bila, gledamo|tv.
{27002}{27067}Mogla je da vidi ili Ëuje neöto öto|bi je uplaöilo. -Kao öta?
{27077}{27140}Kako neki veliki kreten,|ubija svog velikog debelog psa.
{27150}{27232}Niko ne odgovara tom opisu.|-PokazaÊu ti öta je ruûno.
{27290}{27350}DoveöÊeö ûenu? -Idemo.
{27402}{27452}Dobro si? -Ja sam.
{27462}{27523}éelite svoje ûice nazad?
{27834}{27892}Dole!
{28111}{28194}Hajde. -Jedan je mrtav.
{28436}{28552}To je proölo dobro.|Sranje, krvariö.
{28572}{28711}3-4 centralna jedinica, 1141 zahteva|hitnu pomoÊ. Povreen u 184 u Sv. Nikoli.
{28776}{28867}Bila si dobra, opusti se.
{28898}{28984}Ako vam ikada zatreba advokat...?
{29127}{29240}U ime dobrih dana, pustili smo|da iskrvari i opozvali hitnu pomoÊ.
{29290}{29416}Stavio si mu do znanja.|-Jaki ste mi, öutirate vezanog Ëoveka.
{29434}{29533}UÊuti, govno jedno, razneÊu ti glavu,|neÊu razmisliti dva puta.
{29546}{29677}UzeÊu debeljkov piötolj i vratio se|i stavio ti metak meu oËi.
{29792}{29828}Gde je hitna pomoÊ?
{29840}{29928}Ovo je bio zajeb na gomili da ih|sve zavöri, nemate niöta.
{29952}{30096}A ubistvo? -Nema droge, pa nema|namere zloËina, nema zavere, nema niËega.
{30108}{30252}Nema zloËina, kako se to piöe?|Ubistvo, reket, droga.
{30278}{30394}Imate sreÊe da belkinja nije umrla,|unutraönja kontrola Êe razgovarati
{30405}{30442}sa obojicom i sastaviÊe izveötaj|u nekoliko narednih nedelja.
{30454}{30583}NezvaniËni, niste prekröili proceduru|jer je ûrtva imala oruûje.
{30592}{30639}Ako se budete drûali jedan drugoga|proÊi Êete kroz ovo.
{30650}{30756}Usaglasite priËe jer se ja ne vraÊam|u Bar Rokvej jer ste vi zajebali stvar.
{30766}{30886}I proveöÊete neko vreme sa|psihijatrom. Shvatite to ozbiljno,
{30895}{30960}ili idete u suspenziju.|-To ubre Êe samo da odöeta.
{30978}{31016}Prekini, Turk.
{31072}{31150}Opusti se, srediÊemo ga.
{31166}{31242}Gospodo, pitanja. -Ko je odluËio|da se ue tada? -Ja.
{31250}{31302}A ko da se ue u prostorije?|-Moja.
{31312}{31358}Odmah ste se predstavili kao policajci?|-Da.
{31367}{31436}Predstavili ste se kao policajci?|-Poloûaj douönika je postao
{31445}{31520}neuverljiv i bojali smo se da je|bila u opasnosti. -Bili ste u pravu.
{31528}{31568}Jebeno znam to.|-Molim?
{31580}{31624}Zavröili ste sa mojim klijentom?
{31702}{31776}Dopao mi se Mekartni.|-Nema niöta izmeu njih.
{31795}{31846}äta misliö? -Niöta tamo.
{31862}{31995}Ugrozili su douönika, videli su oruûje|i reagovali, razbili su osumnjiËenog,
{32004}{32089}ali on ne podnosi tuûbu.|Da vidimo öta Êe psiholog reÊi.
{32126}{32258}Doktore, saznaÊemo da li sam|dovoljno normalan da nosim piötolj,
{32268}{32410}da jurim zlikovce?|Zaöto si postao policajac?
{32422}{32508}Bila je Nova godina, tada je delovalo|dobro. Ja nisam imao iste prilike kao vi.
{32520}{32648}Tamo odakle sam ja je bilo ili|piötolj i znaËka ili da budeö ûrtva.
{32661}{32744}Kako se oseÊaö kada pucaö?|-Kao öto je prljavi Hari rekao:
{32754}{32828}"niöta ne fali pucnjavi, ako se|puca u prave ljude."
{32840}{32988}A kada loöi? -Onda je grozno, ali|bih radije da uËestvujem u tome.
{32998}{33180}Kako se oseÊate kada vidite da|ginu nevini? -Nekako se umrtvite na to.
{33248}{33476}Uzmite ovo da zapiöete misli i pitanja|sve öto ste primetili kod sebe.
{33642}{33710}Probajte. -ZvuËi zabavno.
{34190}{34276}Napred, Turk. Imaö treÊu.
{34378}{34546}Vidi to, imaö je. Nije bitno öta|kaûu, izuzetan si.
{34596}{34630}Napred, Turk.
{34714}{34750}Ima loptu.
{35154}{35252}Njujoröka policija je puna frustracije,|neprijateljstva i testosterona i spremna
{35260}{35390}da eksplodira svaki tren. Smatrajte|me kao izduv. Jedno povlaËenje
{35400}{35534}obaraËa i pada pritisak. Znate zaöto|ulazite u policiju? Da dobijete poötovanje.
{35544}{35610}VeÊina poötuje znaËku, a svi|poötuju oruûje.
{35752}{35870}Razgovarao sam sa J.D,|imate leö pod imenom Filip Trejger.
{35892}{35944}Pravo ubre. -Kako je bilo?
{35960}{36084}Neko mu je dao da proba svoju|stvar, ubijen je svojim piötoljem.
{36108}{36208}Da li je ubica ostavio neöto?|-Ostavio je pesmu.
{36394}{36472}Sajmone, seÊaö se one pesme?
{36574}{36652}äta radiö? -Turk se raspituje.
{36796}{36836}Ovo je neki ludak.
{36910}{37070}"U boûanskoj klasi, odsekao sam|mu vrat i zadrûao dupe,
{37080}{37128}uzeo sam mu ûivot i piötolj, ali|öteta öto nije jedini"
{37144}{37230}Ide tako neöto, nije neka, ali se rimuje.
{37244}{37276}Pevcu? -Da?
{37320}{37468}Traûimo istog, sredio je Rendala|pre neku nedelju, gde je bio vaö?
{37478}{37542}Proöle nedelje. -Radimo ponovo sa|Rendalom, izgleda da je isti sredio
{37552}{37650}dilera oruûja kod 33. proöle nedelje.|-Kako misliö nazad na posao?
{37696}{37944}äetajte, nauËite neöto.|-Recite mi da se zove Greg Brejdi?
{38016}{38120}OkidaË, broj 11.
{38346}{38468}Metak odgovara 45-ici u OkidaËevom|stanu, to nije bilo iznenaenje pa sam
{38478}{38580}proverila, to je iz oruûja koje je|ukradeno iz Virdûinije proölog meseca.
{38596}{38680}Verovatno je on ubio OkidaËa.|-To i oni misle, odgovara opisu.
{38690}{38782}Ne pomaûe da naemo tipa veÊ|ûrtve dok on piöe jebene pesme.
{38852}{38946}Izvinite, da? -Turk, ne zaboravi|da imamo sud kasnije.
{38980}{39188}»ujem da je izubijao onog dilera?|-Pauka, pa?
{39234}{39274}Da li je?
{39354}{39558}Jeste, oborio ga je, bio je vezan|i poËeo je da ga öutira u stomak.
{39618}{39856}Onda mu je kleknuo na grudi i|poËeo da ga mlati po licu iznova i iznova.
{39868}{39984}"slomiÊu ti jebeno lice, kuËko".
{40020}{40258}Lik je poËeo da kaölje, mislio sam|da Êe ga ubiti.
{40432}{40554}Ti si loöa devojka. -Imam posla.
{40656}{40790}SavetniËe, ruke su mi vezane bez|starateljstva svi dokazi nakon
{40798}{40898}prestresa se moraju odbaciti.|-Zezate me.
{40908}{41018}Moram da odobrim zahtev odbrane|da se odbace sve optuûbe sa silovanje
{41030}{41076}i napad protiv gdina Vendlija.
{41136}{41214}éelite da prie bilo Ëijoj Êerci?
{41260}{41386}Puötam vaöeg klijenta u svet.|Sigurno Êemo se ubrzo vratiti.
{41396}{41430}Pazi.
{41490}{41596}UhvatiÊemo te, kada izaeö|pazi svoja lea.
{41748}{41864}Vodite ga odavde pre nego öto|neko pusti svoje ruke.
{41946}{42054}Psiholog je rekao da treba da se|zapisujem i evo.
{42120}{42238}Mislim se o pravilu na terenu|kada povlaËim obaraË, volim ga.
{42258}{42392}"izvini, ti si ömokljan koji|se pojavio i toliko si glup da ne
{42402}{42486}moûeö da baciö loptu samo zato|öto si na pauzi".
{42502}{42640}Omiljeni deo "palice su otpale, ali|svi begunci napreduju na sopstveni rizik".
{42648}{42670}Prijatnog li iznenaenja.
{42680}{42746}Takav ûivot treba da bude, treba|da budeö drkadûija na svoj rizik.
{42832}{42970}Ili ne. Ipak, joö jedan silovatelj,|kome Êe on nedostajati? Nikome.
{42984}{43034}Broj 12 i joö brojim.
{43390}{43432}Vrela kafa.
{43460}{43508}Vrata s leve strane. -Ima li znakova|nasilnog ulaska?
{43516}{43604}Ne deluje tako, det. Perez je veÊ|unutra. -äta kaûeö na Metse sinoÊ?
{43640}{43700}Tedi, doi da vidiö.
{43790}{43946}Jebote. To je veliko. -I moÊno.
{43956}{44038}To je plazma? -Lcd.|-Ne, to je plazma.
{44050}{44178}Momci, pucanj izbliza, ovde ostavljen.
{44194}{44278}PiËkica se nije mnogo borio.|-Niöta ne ukazuje na to.
{44320}{44452}Nema borbe, obijanja, posekotina,|modrica... -Niko ne ûeli da sluöa
{44460}{44526}o tvom intimnom ûivotu.|-Za tebe je detektiv, mali okice.
{44588}{44686}Izgleda da je opet naö momak.|-Koga je ovaj put?
{44696}{44784}Dûon Van Lajten, radi kao prodavac|kola. Imao optuûbu za silovanje koja
{44792}{44824}je odbaËena.
{44858}{44936}Vidite ovo. -»ovek izbegava sve|poötovanje za lepotu i öarm
{44946}{45078}uzimao je ono öto ûene ne bi dale|i nije imao pravo na ûivot.
{45128}{45226}Naö Ëovek, izgleda da je nagazio|naöeg starog prijatelja Dûonija.
{45238}{45358}Znate ga? -Bio je opasan kuËkin sin.
{45428}{45520}Znate li koliko je zabavno ne uhvatiti|serijskog ubicu. -äta hoÊete da kaûete?
{45540}{45716}Ozbiljno razmislite da li ûelite da vodite|na ovom sluËaju. -Mislite da nismo dorasli?
{45734}{45918}Imate oko 110 godina meu vama.|-120.
{45976}{46112}Ako zeznete, moûda vas odbiju za|penziju. éelite to?
{46178}{46320}406, poruËniËe. -äta znaËi?
{46338}{46528}Ted Vilijams, poslednji dan sezone.|Menadûer ga ûeli na klupi da ga zaötiti.
{46556}{46654}On je ipak uöao, zavröi si 406.|Poslednji nije preöao 400.
{46684}{46796}Vaö je, samo nemojte da mi kukate|kada vam neki saobraÊajac
{46806}{46924}zaustavi serijskog ubicu zbog prebrze|voûnje i uhvati vaöih 5 minuta slave.
{46934}{47058}I da mislite da vam je pred nosom i|da vam treba 100 hiljada svetlosnih godina.
{47072}{47288}Svetlosne godine mere razdaljinu,|ne vreme. -UpamtiÊu to.
{47340}{47480}2003, ovaj je istorija krstarenja|po gej barova i ubijanja od batina.
{47504}{47564}Muökarci su nalaûeni upucani i|mrtvi u stanu.
{47574}{47702}Ko god da je, pribliûi im se i prosvira|im mozak bez problema.
{47716}{47788}Ne ostavlja otiske i ponosi se svojim|delom.
{47802}{47922}Koje bi moglo biti ubistvo broj dva,|nazad od Ëetiri...
{48078}{48140}Bio sam potreöen prvih nekoliko|puta kada sam ubio hladnokrvno.
{48184}{48302}Brinuo sam se da Êe me izbaciti|iz policije ako me uhvate.
{48312}{48364}Nisam se brinuo zatvora nego da|izgubim ötitnik.
{48374}{48404}Hteo sam da radim sledeÊeg dana|oËekujuÊi da Êu se oseÊati drugaËije.
{48416}{48504}Mislio sam da Êe me gledati kao|civile za koje ne znaju koji je prljav.
{48704}{48834}Ali nisu, tada sam znao da mogu|da nastavim da to radim veËito.
{48928}{48976}SledeÊa stanica, Pauk.
{48990}{49110}Da smo mu zatvorili posao, bio bi|moûda krtica, uzeli smo advokata.
{49140}{49274}Trebalo je da svedoËi da je kupila|kokain od njega, bila je dobar advokat.
{49304}{49376}Partner i ja smo otiöli u klub 404|u Harlemu.
{49400}{49548}Malo o njemu, on mi je partner preko|30 godina, on je najbolji policajac ikada.
{49594}{49646}Ja ga uvek pratim kroz vrata.
{49688}{49860}Metak namenjen meni je proklizao|kroz njegov torzo. Bio mi je uzor.
{49870}{49938}Dan kada sam prestao da se trudim|da budem Tom Kalen je bio najbolji
{49946}{49990}dan mog ûivota.
{50410}{50500}PevËe, pregledala sam dosije.|-Zanimljivo na öta troöiö vreme.
{50552}{50624}Tokom hapöenja je kod »arlsa|Rendala naen piötolj.
{50678}{50770}U ostalim pucnjavama je bilo oruûja,|ali ima dosta sliËnosti.
{50790}{51006}Mislim da treba neko da ga poseti u|zatvoru. Dobra ideja, ali ne Perez i Rajli.
{51020}{51168}Mogu da zeznu, to je vaûno.|SrediÊemo to Turk i ja.
{51986}{52041}Detektivi, »arls Rendal.
{52128}{52274}äta vi, seronje, hoÊete?|-Kakvo ogorËenje. Voliö poeziju?
{52297}{52391}äta? -Voliö poeziju?
{52422}{52580}Ruûe su crvene, ljubiËice plave,|ûelim da ti okom iskopam oko.
{52634}{52791}Mislio sam da umeö da rimujeö.|-Jebite te, idem odavde.
{53032}{53128}Zaöto smo iöli tamo? -Kako bi|izgledalo da nismo?
{53203}{53384}OpustiÊeö se? -äto sam popustljiviji|to je gore.
{53402}{53459}ZvuËi zabavno. -HoÊeö da probaö?
{53470}{53594}Paûljivo, to ima poseban efekat|na ûenu. -Nasilje?
{53702}{53874}Tamo je gde pripada. -éao mi je o tome.|-Ne brini.
{53908}{54066}äta god se desilo, ne vuËem te|za sobom. -Ne brini, dobro sam.
{54097}{54212}Ne znam öta sam mislio.|-Mislio si na desetogodiönjakinju
{54222}{54428}kojoj je razbijena lobanja. Hteli su|da te spreËe, ali sam ti se divio.
{54502}{54622}To je bilo pravedno, nema|dvoumljenja tada.
{54872}{55141}Ja sam ubica i pojavljujem se na vratima|ili na prozoru i otvaraö mi, ko sam onda?
{55162}{55188}Neko koga znam.
{55259}{55438}A pesme? Treba da je napraviö|pre odlaska ili Êeö nakon ubistva?
{55448}{55556}Nema otisaka na njima, onda sam|imao rukavice kada sam ih pisao.
{55566}{55720}Poznajeö ûrtve i zbog lakog pristupa,|verovatno i one znaju tebe, moraju.
{55728}{55800}To su sve seronje, neÊe verovati|nikome, naroËito ako te ne znaju.
{55818}{56010}Ali ja ih viöe znam od toga, znam|sve. -Pratiö ih, izviaö.
{56364}{56456}HoÊe li iko da kaûe? -äta?
{56628}{56758}U pravu je, to je policajac.|-Preterujemo.
{56826}{56958}Kaûem vam da je policajac.|-Kada prestajeö sa tim?
{56980}{57018}Polako, samo to kaûe.
{57042}{57332}Znam öta govori i mislim da je to|sranje. Ubij me, ali ne govori to.
{57791}{57866}A veËera? -HoÊeö da izaemo?
{57890}{57960}Gde? -Baö me briga, ti ideö.
{57982}{58106}U Ëemu je problem? -Ni u Ëemu,|ako hoÊeö da ostaneö, izvoli.
{58118}{58282}Ne izlazi mi se. -Nemoj me daviti,|ovo mi je najbolji deo dana.
{58344}{58398}Kreöeö se samo sa pandurima?
{58448}{58497}-Ponekad sa vatrogascima|ili bivöim robijaöem.
{58598}{58636}Imam poötovanja prema vatrogascima.
{58686}{58816}Znaö zaöto odnose svoju uniformu?|Ne veruju ti.
{58956}{59022}äteta öto nisi upoznala Pem Lajtens,|slagale biste se.
{59032}{59174}Neko je sproveo tog tipa pravdi,|zato sam mu se dopadala.
{59184}{59248}Moûda Êe ti se jednom ostvariti,|misle da je policajac.
{59268}{59396}Ima smisla. -Sranje, to je neki|psihopata. -Na poslu ih ima.
{59618}{59662}Lepo spavate? -Ne baö.|-Da.
{59672}{59724}Dobro jedete? -Ne. -Da.
{59734}{59804}Neki koömari? -Da sam zaglavljen|u sobi sa vama zauvek.
{59856}{59878}Ne.
{59886}{59974}Mislite da moûete da se vratiti|na duûnost? -Svakako. -Da.
{59984}{60090}Mislite o penziji? -Mislite na|smrt sa beneficijama? äta ima loöe?
{60102}{60288}Mislite o penziji? -Ne, Ëemu bih|se radovao, igranju softbola?
{60297}{60386}A obezbeenje? -Previöe je opasno.|-äta Êete? -Moûda kupim Ëamac.
{60430}{60572}Samo Êu reÊi. Kaûete da traûimo|jednog od naöeg, ali öta ako je
{60580}{60614}bivöi robijaö?
{60703}{60888}Misli na Martina Bauma.|-äta sa njim?
{60903}{61024}Dobio je otkaz pre neku godinu,|nije motiv, ali je poznavao sve ûrtve.
{61042}{61194}Turk, ja sam znao veÊinu, i ti si.|I Rajli i Perez, Ëak i Karahil.
{61206}{61282}Moûda si ga ti ubio?|-Jesam.
{61314}{61438}Pesme i mesto su sve, moramo da|poveûemo ubistva öto znaËi da
{61448}{61480}moramo da se bacimo na forenziku.
{61497}{61672}To je previöe, devojka veÊ|radimo na tome, otvara ga dok priËamo.
{61686}{61782}äta si rekao? -Evo nas opet.|-Pazi na jezik.
{61806}{61900}Nije mislio niöta. -Neka govori|u svoje ime.
{61912}{62028}HoÊu. -RasturiÊu ga.
{62118}{62218}Stavi jaja u dûep, a vi imajte|poötovanja prema drugu profesionalcu.
{62286}{62418}NastaviÊemo? Gde smo bili?|-PriËali o Martinu Baumu.
{62454}{62600}Neki su uzimali novac, Baum se|borio za njih, pokuöao da zataöka.
{62610}{62703}Robijao je? -Tuûili su ga, ali se on|nagodio davöi ostavku.
{62714}{62797}U Ëemu je stvar? -Mogao sam da|laûem da ga zaötitim, ali nisam.
{62820}{62968}Zaöto ne bi ubio tebe, zaöto bi se|ponaöao kao serijski ubica?
{62980}{63038}Otkud znam, samo kaûem.|-Nema smisla.
{63103}{63220}Proverite ga ako hoÊete.|Vi mislite da je policajac.
{63234}{63334}Kaûem da moûete da ga proverite.|-Treba nam bolji razlog zaöto bi on
{63347}{63397}bio osumnjiËeni.
{63440}{63509}Mora da je pms.
{63642}{63714}Zdravo, momci. -äta se deöava?
{63730}{63820}Donela sam vam izveötaj FBI|o rukopisu. Ne smeta vam
{63830}{63909}da gledam dokaze koje sam|sakupila i obradila za vas?
{63924}{64016}Nema problema. -Ovo je fascinantno.
{64094}{64164}Idemo. -Sklanjaj ruke od mene.
{64174}{64336}Dao bih vam malo privatnosti.|Uûivajte.
{64347}{64704}äta je sa tobom? -éao mi je zbog|sinoÊ, to je navika, mogu da se odviknem.
{64726}{64932}To je sranje. -Nije, ozbiljna sam.
{65159}{65274}Zaöto je Turk tako brzo prihvatio|trag? Da bi nas spreËio da naemo ubicu.
{65284}{65398}To bih ja uradio da pokrijem sebe.|Nema boljeg pogreönog traga od Bauma.
{65409}{65491}Ima smisla. -Mrzim tog tipa.
{66190}{66226}Dolazi.
{66302}{66350}Dvadeset do tri ujutru.
{66418}{66516}Da li ubija vreme? Ili je vreme za ubijanje?
{66976}{67110}Hajde, Baum, ubij nekoga.|Ubij Turka, on ti je smestio.
{67370}{67474}Video si ovo? Sluûba '99,|poluautomatski, orden u pucanju.
{67488}{67554}Moûe da sredi tipa sa 20 metara.
{67618}{67734}Vidiö kompjuterske direktorijume?
{67950}{67988}Da li je Karen primetila neöto novo?|-Ne joö.
{67998}{68066}NeÊu da budem u kolima kada|bude ubio nekoga.
{68162}{68250}Ja Êu. -To je deËko, ponosim se tobom.
{68546}{68640}Ti si Perez? Ja sam Martin Baum.
{68722}{68856}Imam dozvolu za ovo, radim kao|obezbeenje u restoranu.
{68870}{68942}Poöto verujete da policajac obavlja|ubistva sa poezijom pa mislite da
{68952}{69082}proverite Bauma, ima prljav posao.|-Misliö da imaö prljav posao?
{69094}{69160}Nego öta. -éivot je grozan.
{69184}{69240}Sve je u redu, Sajmone?|-Gde si bio?
{69272}{69352}éelite da nam kaûete joö neöto?|-Imam neöto u dûepu.
{69438}{69558}Pasoö, izveötaje o karticama, karte.
{69568}{69650}Kada je ubijen Brejdi, pratio sam|klijenta u Brazil.
{70008}{70094}Ako je taj silovatelj ili ubica zaista|neko ko se kaje, mora mu se to odobriti.
{70116}{70236}Ne seÊam se tvog imena, ali sam|imao toliko momaka koji su pomagali
{70246}{70282}tokom godina.
{70372}{70462}Toliko deËaka da je teöko upamtiti|im imena.
{70482}{70602}Ja sam Dejvid Fisk, detektiv prve|klase. Moûda me se ne seÊaö sada,
{70612}{70768}ali hoÊeö do kraja svog ûivota.|Otac Konel, da bog da trunuo u paklu.
{70769}{70826}13 oboreno, joö jedan preostao.
{71042}{71124}Beli donji veö.
{71234}{71350}Uklanjam predmet koji je ubaËen|u rektum preminulog i stavljam
{71360}{71418}u vreÊicu za dokaze.
{71504}{71556}Odmah se vraÊam.
{71650}{71708}Joö jedan, rukom pisano.
{71806}{71928}"Starac kome su deca verovala,|u nemoguÊnosti da kontroliöe poûudu,
{71938}{72112}pepeo pepelu, prah, prahu, crkva|ne moûe da ga zaustavi, neko mora"
{72166}{72206}VideÊu öta joö mogu da naem.
{72354}{72456}äta je bilo? -Otac Konel mi je|dao prvo priËeöÊe.
{72594}{72744}Nisam imao priliku da se javim.|-Pogledajte, kasnije Êemo uporediti beleöke.
{72770}{72890}Naö prijatelj je imao bliski susret sa|sveötenikom, spustio mu je pantalone.
{72908}{73006}Ne govori tako. -Sam pogledaj.
{73066}{73130}SledeÊe Êe nam reÊi da je|Baum sluûio ovde.
{73164}{73206}Ova dvojica smrde.
{73218}{73308}Doktore, proËitali ste pesme, moguÊe|je da je on policajac.
{73336}{73440}Nisam ga video, Ëak ni Ëuo|za policajca serijskog ubicu.
{73454}{73502}Idemo, devojke.
{73658}{73734}Dajte nam savet kako da ga|uhvatimo. -Ne brinite za to,
{73762}{73808}ûeli da bude uhvaÊen.
{73856}{73972}Nisi naöla bolje mesto za ruËak.|-Htela sam da se zahvalim.
{73984}{74132}Za Pauka? -I za posetu u bolnicu|i ohrabrenje.
{74148}{74230}äto bi hteo to? -Nakon vremena,|beûanje nije dovoljno.
{74244}{74432}Vaöa kÊer je u timu? -Igrala je,|ali sada ima 25 i ûivi u Kaliforniji.
{74442}{74530}A majka? -Umrla joj je dok je bila|veoma mlada.
{74560}{74676}éeli da svi znaju da se izvukao,|koliko je briljantan.
{74710}{74936}VeÊina ubistava su bili osumniËeni Turka|i Pevca i on im preti pred svim svedocima
{74948}{75012}i poöalje nas na juriö na Bauma.|Zaöto bi to uradio?
{75026}{75126}Pokaûite mi joö, za sada nemate niöta.|Daj mu joö. -A podaci iz crkve?
{75138}{75260}Onaj koga je Turk proganjao.|-Ispostavilo se da je otac Konel
{75268}{75400}premeötavan svuda, öto bi radili|to sa katoliËkim sveötenikom?
{75410}{75472}OËigledno je, iza oltara daje deci|viöe od priËesti.
{75490}{75528}Turk je priznao da ga je poznavao|kao dete.
{75630}{75722}Taj sveötenik ti je dao prvo priËeöÊe?|-Jeste.
{75748}{75862}Pokuöao je neöto neprikladno?|-Nikada.
{75892}{76112}Zaöto bi neko mislio da jeste?|-OsumnjiËen sam?
{76138}{76322}Ne, ali leöevi smrde, i mnogo toga|potiËe iz tvog pravca.
{76338}{76560}PotiËe ili je gurnuto? -Povezan si|sa ûrtvama, a nisi majka Tereza.
{76612}{76804}Nisam imao problema sa tim sveötenikom.|-To bi bilo sve.
{76988}{77204}Razgovarao sam sa Relijem i Perezom.|-Ne zezaj se, sluöaj. Misle da je Turk taj.
{77360}{77566}To je baö smeöno, nije ozbiljno.|Svi su prihvatili da jurimo naöeg.
{77576}{77828}Ali to nije Turk. -Znaö to? Kako?|-Sa sigurnoöÊu.
{77874}{78056}Taj otac Konel je bio njegov sveötenik|kada je bio dete. -Rekao ti je to.
{78064}{78234}Nije mi rekao da je zlostavljao decu.|-To je sranje. Turk je dobar.
{78256}{78450}Ne govori mi öta da radim. Da nisi|zucnuo o ovome ili si zavröio.
{78648}{78714}Mogu li da govorim sada?|-Slobodno.
{78736}{78996}Budi paûljiv. Turku je stalo do ljudi.|Znam da nekada deluje kao pit bul,
{79024}{79276}nije bitno, stalo mu je do zaötite|ljudi, i ako ga ne podrûiö, zaûaliÊeö.
{79802}{79972}Isuse. -Izvini, imaö vremena?
{79990}{80214}Znaö da smo Turk i ja prijatelji i da|bih sve uËinio za njega. -I on za tebe.
{80240}{80466}Da li bi ti uËinila sve za njega?|-Kuda ovo vodi?
{80486}{80600}HoÊe da spavaö sa mnom.|-Stvarno?
{80664}{80812}Ne bi mu smetalo, ali nisam zato ovde.|-Zaöto?
{80850}{81016}Gde si bila one noÊi kada su ubijeni|Rambo i OkidaË?
{81046}{81264}Da li si ih poznavala pre ubistva?|Znam da nisi kriva, delujeö tako.
{81384}{81442}Znaö onda kako je Turku.
{81554}{81812}Treba da mi nabaviö informacije|diskretno, moûeö to? -Svakako.
{82048}{82088}Genije? -Savröen tajming.
{82102}{82218}Baö si dobro sredio poruËnika,|nagazio mi je partnera. -I treba.
{82234}{82384}Treba da izgladimo stvari.|-HoÊeö da se obuËem u osam?
{82404}{82476}Moûe u devet, moram da se naem|sa starim prijateljem. -Svakako.
{82902}{82970}Momci, hvala öto ste doöli.|Ovo je äeril Bruks i ima neöto da ti kaûe.
{83018}{83234}Moja kÊer Gven je umrla pre 4 godine.|-Imala je 10 godina, silovana i ubijena je.
{83264}{83530}»arls Rendal je uradio to.|-Zaöto nam to govorite?
{83540}{83684}Jer je osloboen. -Zaöto?|-Zato.
{83716}{83864}SvedoËila sam za njega, rekla sam|da je bio sa mnom.
{83882}{84038}äeril praöta. -Pretio je da Êe me|ubiti.
{84082}{84296}Pozdravi se sa policajcima, idi|kuÊi i ne napijaj se na smrt.
{84550}{84666}HoÊu da kaûeö to, reci.
{84774}{84942}Podmetnuli smo piötolj u Rendalov|stan, rekao sam to, sreÊni?
{84972}{85166}Uradio bih ponovo, jer taj kepec|ne bi pobegao. -äta ûeliö od nas?
{85176}{85280}Mislite da je Turk serijski ubica,|preterujte se.
{85320}{85634}PomoÊi Êu vam za to, ali ne uvlaËite|»aka Rendala, jer ako izae, umreÊe.
{85666}{85832}Molim? -Dva puta Êu ga liËno|upucati.
{86240}{86352}Moja baka je volela operu, pomagala|nas je öivenjem.
{86362}{86476}Nizao sam joj igle, sav novac je|davala crkvi. -Divio si joj se?
{86496}{86522}Oboûavao sam je.
{86538}{86636}Pevac? -Religiozan je, ide u crkvu.|-A ti?
{86652}{86770}Naö posao je da 99% populacije|bude bezbedno od preostalih 1%.
{86826}{86906}Problem je öto treba da provedemo|pola ûivota sa tim 1%, i öto bolje
{86916}{87068}radimo posao, manje onih 99% misle|da smo im potrebni. Ne obraÊaju paûnju.
{87080}{87238}Samo policija i kriminalci obraÊaju|paûnju na ulice, ostali idu negde ili kupuju.
{87430}{87578}Imam nareenje da si pod ograniËenim|poslom, radiö za stolom, sledeÊi
{87588}{87680}put na sastanku sarauj sa psihologom.
{87862}{88054}RazbiÊu glavu onom Perezu öto|mi daje ova sranja, ubiÊu ga.
{88072}{88164}äta je bilo? -Nije ovo patija öaha.
{88174}{88322}Moûda jeste, ako sada kreneö|na Pereza, uöetaÊeö u zamku.
{88334}{88470}On te samo Ëeka.|-Jebeni Angus mu veruje.
{88564}{88702}»ekaj na pravo vreme i uzvrati.|-Sada nije pravo vreme, veruj mi.
{88886}{89032}Turk, moram da preskoËim veËeras.|VideÊemo se sutra i ûao mi je zbog
{89048}{89266}Angusa, proÊi Êe to.|Laku noÊ.
{89444}{89508}To je policajac.
{89720}{89764}äta imaö za mene, lepotice?
{89886}{90006}Pazi, ima razloga öto me Perez|proganja. -Previöe je pametan da
{90014}{90154}bude tako glup. -Nije on iöao|na koledû, samo jednu godinu.
{90168}{90324}Izbacili su ga i Ëujem da je bio|uhapöen.
{90568}{90670}Ako pucaju na tebe, moraö da|pobegneö...
{90702}{90878}Banka je dobra jer kreöu dve|prostitutke na zadnjem sediötu.
{91066}{91192}Znaö one neandretalce.|-Normalan je.
{91208}{91334}A belac? -Rus, Evegenij Mugalat.
{91502}{91598}To sranje me ubija. -Znam to.
{91672}{91772}Ubija i mene, ali ja ga ispuötam pod|svojim uslovima.
{91810}{91930}Sigurno nisi zapisao ni jednu reË|u blokËe koje nam je Proski dao.
{91940}{92080}Naravno da nisam, a ti?|-Jesam, pomaûe mi.
{92162}{92290}Zapiöeö i izbaciö to. Probaj.|-Daj mi da vidim.
{92342}{92502}Ne zezaj, to je privatno moje je.
{92514}{92670}SmuËilo mi se sve, da jurcam okolo,|traûim tragove, hapsim, pravim izveötaje
{92678}{92730}da svedoËim, dogovaram se.|Sve je to bilo sranje.
{92828}{92876}Detektive?
{93010}{93088}Sve je onda poslalo jednostavno.|-Det. Perez ovde, Rajli, öta ima?
{93098}{93174}Mrzim seronje, volim da ubijam ljude,|od Ëega sam odustajao?
{93186}{93318}Dogovorio sam sastanak sa Pevcem|sutra, ne ûelim da Turk sumnja.
{93330}{93394}Zabavu za penziju, zlatan sat,|rukovanje sa gradonaËelnikom
{93404}{93450}i ime na nekoj plaketi?
{93588}{93650}Jebena stvar.
{93678}{93716}Bolje je ovako.
{93748}{93828}Sada su svi znali ko sam.
{94878}{95084}Ja sam. Mislim da me je neko pratio|do kuÊe. Sada je napolju.
{95096}{95230}Doi ovamo, ili me samo nazovi.
{96344}{96394}Otvori. -Turk?
{96552}{96612}Sada sam te zvala.|-Spusti piötolj.
{96642}{96698}Prate me kola. -Spusti piötolj.
{96836}{96908}Imaö neöto da mi kaûeö?|-U vezi sa Ëim?
{96918}{97016}OkidaË, Rendal? -Uöunjao si mi|se u stan?
{97028}{97130}äta rade u tvom kompjuteru?|-Proveravala sam sve povezanosti.
{97208}{97266}Krijeö neöto od mene?
{97390}{97638}Tek sam dobila ovo, pesma.|Rukopis se ne poklapa, laûan je.
{97666}{97780}Ti si je napisao?
{97920}{98038}äta se deöava ovde?|-Provodiö mnogo vremena sa Perezom?
{98048}{98172}Ljubomoran si? -Mogu li da ti|verujem?
{98240}{98592}Da. -Daj mi sve o Perezu i Rajliju|i sve öto znaju o meni. Ne igraj se sa mnom.
{98616}{98836}Joö viöe mislim da je policajac.|-Ja sam uveren da je policajac.
{98890}{98942}NaroËito kada mi je neko pucao|na kuÊu. -Povreen si?
{98966}{99080}éeli to da zna. -Mrtav je.
{99100}{99192}Zove se Mugalat. -Tip koga smo|pre neko veËe videli u restoranu?
{99202}{99336}Na intezivnoj je u Sv. Luki, misle|da je on odsekao glavu Jakovu.
{99358}{99476}Misliö da je ûrtva ili osumnjiËeni?|-BiÊe zabavno kako god bilo.
{99514}{99650}Doktore, öta ima?|-Jedan od najËvröÊih ljudi.
{99662}{99862}Izvukli smo 6 metaka. Ima tri i od|ranijih pucnjava. »ovek je tenk.
{99874}{99986}Mogu li da razgovaram sa njim?|-Teöko, ali napred.
{100000}{100052}On Êe samo da klima, ja Êu da|odgovaram.
{100096}{100318}Evgenij, probudi se, grizliju.|Ne govoriö ruski?
{100618}{100736}Ova ruska maöina bi mogla da|nam bude prvi svedok.
{100766}{100858}Probudi se da nam kaûeö ko ti|je to uradio.
{100960}{101024}To je dosta, detektive.
{101036}{101140}Onda nam reci gde je Jakovova glava.
{101168}{101388}4343 treba mi stalni Ëuvar pacijenta|Magulata u Sv. Luki.
{101528}{101592}Na ovaj broj se prijavljuje policijska|brutalnost?
{101622}{101750}Maca ti je pojela jezik?|-Opet si na uslovnoj, misliö da Êeö
{101758}{101802}me uplaöiti, öta hoÊeö?|-Paûljivo, moji poreznici su ljuti.
{101812}{101874}Ne plaÊaö porez, prei na stvar.
{101888}{102040}Jedna tvoja ûrtva je ukrala mnogo|oruûja, isto koje se pojavljuje u zloËinima.
{102058}{102142}Jednostavno je, nai ukradeno|oruûje i imaö svog momka.
{102152}{102310}Poznajeö ga? -Ako postoji tip koji|je opasnost po ljude, ja ne bih rekao niöta.
{102324}{102445}Dajem ti joö dve sekunde, znaö li|ga i kada Êemo se videti?
{102458}{102557}U petak uveËe u devet u mom|klubu. -BiÊu tamo.
{102574}{102752}Ako je neko glup, ovaj je najgluplji.|-Polako, samo budi mamac.
{102802}{102931}Pokrili smo te, niko ti neÊe smetati|u klubu i ti neÊeö visiti po zatvoru.
{102942}{103104}Dogovorili smo se? -Ali ako vaö|poËne da luduje ovde,
{103114}{103169}neÊu da mi na vrata doe Dûodi|Foster, nego marinci.
{103945}{103964}Dobro veËe, detektive, hoÊete|jednu, grozna je, ali bolje iöta nego niöta?
{104081}{104195}»im sam Ëuo da prokleti Rus nije|umro, znao sam da stvari neÊe biti iste.
{104206}{104358}Morao sam da promenim pravila|i strategiju, da uradim neöto nepovratno.
{104568}{104634}Krenuo sam na neoprostivo.
{105292}{105362}Molim te, ne...
{105862}{106048}»uo si öta sam rekla? Kako bih|mogla da preterujem?
{106060}{106350}Taj psihopata me je upravo napao.|-RazmotriÊu to, ne prilazi.
{106426}{106466}Jebeö to.
{106904}{106969}Izvinite, ja sam det. Koreli|mogu li da pogledam rezervacije
{106978}{107024}Samo napred.
{107268}{107390}Ovde det. Koreli, traûim Pereza i|Rajlija, ali ne mogu.
{107564}{107624}Moram hitno da razgovaram sa|njima.
{107694}{107776}Razumem, ali mi treba lokacija.
{108455}{108495}Stigao je.
{108531}{108560}Pusti me unutra.
{108684}{108814}Hvala Bogu, to je policija.|-Gde Êemo? -Prati me.
{108838}{108926}Igrao sam basket na nekoliko|blokova odavde. -Ne zezaj.
{108936}{109006}Kao dete se nisam bojao da se|meöam sa takvima kao öto si ti.
{109046}{109192}Sada je loö kraj. -Ne i za mene.
{109222}{109407}Uöao je, za sada je dobro.|-Dosta priËe, öta imaö?
{109431}{109566}äta misliö da Êe uraditi?|PoruËniËe, to je sranje.
{109578}{109652}Izgubio sam dva zuba tog dana.|-Nije civil nego diler.
{109690}{109776}Volite te zlatne zube, treba da|mi zahvaliö.
{109802}{109946}Nosim prsluk i Starski i HaË ga|posmatraju kao dva sokola. Gej.
{110046}{110158}Znaö naöeg pesnika, öta imaö za mene?|-Idemo.
{110204}{110293}Molim te. -Ne znaËi niöta öto|Ëovek priËa.
{110324}{110455}Misliö da mu je onaj piötolj plastiËni?|Sigurno vodi do OkidaËa.
{110469}{110550}U öta se kladiö? -U petsto.|-Vaûi. -I ja u joö petsto.
{110614}{110706}Ja tebi pomognem, ti uzvratiö.|-Pomozi mi.
{110760}{111012}Imam film, klinci sa mature.|Identifikovali su te. -Mene?
{111094}{111162}Sada razumeö? -Da.
{111200}{111358}Kako sam ispao? Kao pesnik?
{111408}{111455}Idemo.
{111474}{111550}Napisao sam pesmu za tebe,|da je Ëujeö?
{111660}{111916}Baci piötolj, smesta.|-Zapravo plaÊaju vas morone?
{111928}{111990}Spusti piötolj. -Rado.
{112016}{112114}Da proËitate moju pesmu.|ProËitaj.
{112158}{112292}"Pokuöali ste da mi smestite i to|ovako, mislili ste da Êe mi
{112302}{112448}odseÊi oku, ali ste ga samo|poduvali". OdliËno.
{112556}{112700}äta ti radiö ovde? -Ne gledaj me,|ali sam hteo da te zaötitim i da ih
{112710}{112850}vidim, vredelo je. -Radimo svoj|posao, neÊemo se izvinjavati.
{112860}{112932}I ne ûelim, napolju je ubica sa|znaËkom, öta vi, moroni radite ovde?
{112966}{113048}Nije to. -Nije. -Upravo sam|zaradio 1000 dolara.
{113102}{113154}Opipajte me.
{113310}{113390}Fin dodir, öta radiö nakon posla,|sem ako nisi obeÊan nekome,
{113402}{113455}ne ûelim da se meöam u neöto.|äta ti se desilo sa licem?
{113472}{113546}To je bilo ujed ljubavi.|-UÊuti, jebote.
{113728}{113814}O Ëemu govori? -Ako nisi pao na|ovo to ne znaËi da nisi naö Ëovek.
{113910}{113972}Zeznuli ste.
{114048}{114119}Greöite. -Jebeni psi.
{114208}{114314}Opusti se, pauku. Da popijemo neöto.
{114378}{114478}Mislim da ovde postoji friûider.
{114528}{114606}Odmah se vraÊam.
{114881}{115005}Ovaj Ëovek je pucao u tebe?|Siguran si?
{115455}{115500}Nedostajem ti?
{116216}{116290}Polako. -U redu je.
{116300}{116450}Isuse, Pevce. -Sedi.
{116594}{116748}Moraö da saznaö za ovo od mene.|Otvori knjiûicu i poËni da Ëitaö.
{116766}{116892}Sve öto ûeliö da znaö je unutra.|Samo napred.
{116940}{117138}Naglas! Da se zna. Vidiö kameru ovde?
{117294}{117457}Ime mi je Dejvid Fisk, detektiv|prve klase, policajac sam skoro 30 godina.
{117569}{117696}Tome, treba dosta da preemo|i nemamo dovoljno vremena.
{117748}{117876}Ime mi je Dejvid Fisk, detektiv...|-Zovem se Dejvid Fisk.
{117888}{117990}Policajac sam skoro 30 godina.|-Ne oËekujem da me pamtite.
{118031}{118162}Proölo je mnogo vremena od kako si|me postavio u krilo i rekao mi da me voliö.
{118172}{118276}Do tada sam ubio 14 ljudi.
{118332}{118448}Ali ti garantujem da Êeö pamtiti|ime do kraja ûivota.
{118728}{118872}Ne postajeö policajac jer ûeliö da|sluûiö i ötitiö nego zato öto ti
{118881}{119022}daju piötolj i znaËku, veÊina poötuje|znaËku. Svi poötuju oruûlje.
{119044}{119140}Ja ti se kao ubica pojavljujem na|vratima. -To nije partija öaha.
{119150}{119231}Moûda jeste. Praviö pogreöne poteze.
{119246}{119326}Dva Êu mu smestiti u glavu liËno.
{119346}{119474}Znam do moralnosti, umrtviö se|na to...
{119693}{119764}Tom Kalen mi je bio uzor.
{119993}{120048}Onog dana kada sam prestao da|se trudim da budem on je bio
{120056}{120104}najbolji dan mog ûivota.
{120182}{120336}Pre nekoliko godina sam smestio|ubici dece »arlsu Rendalu.
{120386}{120504}Trebalo je da znam da Êe me|progoniti.
{120555}{120666}äta ûeliö da uradim sa ovim?|-To je sve öto imaö da kaûeö?
{120698}{120804}Dugujem ti objaönjenje.|-Zaöto mi to govoriö sada?
{120826}{120946}Ivan Grozni Êe se probuditi uskoro|i identifikovati me.
{121090}{121186}Dobro veËe, ûelite jednu, grozna|je, ali bolje iöta nego niöta.
{121212}{121300}Mogu da uem tek tako, a zatvorenik|spava, izai.
{121326}{121392}Jesam li izabrao pogreönog Rusa?
{121600}{121660}Sada Êemo nezvaniËno.
{121745}{121931}éelim da razotkrijem Rendalovo|ubistvo. S obzirom na uslove, öto da ne?
{121943}{122144}Ne moraö da mi zahvaljujeö.|-A o onome da ne budeö ja, ne shvatam.
{122164}{122450}Veliki si policajac, ti si me insipirisao|celog ûivota, onda si prekröio zakon.
{122460}{122576}Podmetnuo si piötolj Rendalu,|izneverio si me.
{122622}{122969}Izgubio sam svoju veru, tada je|sve poËelo i onda nisam mogao da stanem.
{123010}{123132}Na kraju, nisam ni ûeleo.
{123300}{123543}Radio sam svoju stvar i na kraju|je bilo gotovo, ubre je palo.
{123634}{123802}Ne razumem ni reË. -Znam, Ëim|sam Ëuo da Rus nije umro,
{123814}{123938}znao sam da moram da promenim|pravila, da uradim neöto nepovratno.
{123958}{124000}Uradio sam neoprostivo.
{124156}{124332}äta da radim, prijatelju, partneru,|da te uhapsim? MoraÊu da prijavim.
{124348}{124434}Mi smo tim. -Bili smo.
{124468}{124644}To je bilo juËe, danas upireö piötolj|u mene.
{124812}{124860}Ali joö nije opalio.
{124990}{125120}Zbogom, Tome. -Kuda Êeö?|-Ne znam, verovatno u pakao.
{126262}{126414}Dejve? -Ne pribliûavaj se.|-NeÊeö. -HoÊeö da se kladiö?
{126446}{126519}Ne ti partneru. -Ali ja bih.
{126580}{126731}Karen, polako. -Ne moûeö da prestaneö|da misliö na mene. -UÊuti, Dejve.
{126742}{126798}BraniÊeö ovo govno. -U glavi sam|ti.
{126808}{126908}Ne branim ga, samo polako.|-Jebi se, Turk. Spusti piötolj.
{126919}{126974}A ako ne uradim to?|-RazneÊu ti mozak.
{126994}{127048}Dopada mi se kako to zvuËi.
{127131}{127178}Rekla sam da se ne mrdaö.
{127262}{127360}Daj mi piötolj. Ostani ovde.
{127544}{127622}»oveËe, jebem ti.
{127716}{127876}Stare brave, tako su dobre.|-Moramo da zavröimo ovo, spusti piötolj.
{127907}{128166}Plan ti je da me uhapsiö, zavedeö|u dosije, da mi pretraûiö telesne öupljine?
{128205}{128381}Da me prijaviö za Ëudoviöte nedelje|ili da budem psiho profil za Opru?
{128438}{128507}NeÊe moÊi. -Ne ostavljaö mi izbora.
{128524}{128728}Imaö, da pobegnem. Da li bi to|uradio za mene? -Ne radi to.
{128756}{128890}PobeÊi Êu. -Moraö da uradiö|pravu stvar.
{129143}{129231}To je 10-10, ispaljeni hici, osumnjiËeni|beûi, idemo. -Ne radi to.
{129274}{129530}Ispaljeni hici, osumnjiËeni beûi.|To je hapöenje. Hajde.
{129698}{129912}Pravedan Ëovek stoji preda mnom,|heroj u prljavoj zemlji.
{129940}{130257}Brat u zagrljaju, u srcu si ti.|Nadao sam se da Êeö razumeti.
{130314}{130393}Razumem. -Ne razumeö.|-Razumem.
{130578}{130790}Jedino u ûivotu öto mi je pruûilo|zadovoljstvo je ubijanje tih drkadûija.
{130928}{131022}Ovo je stvarno loöe.
{131038}{131184}10-30, oboren policajac.
{131790}{131844}Ne idem nikuda.
{132078}{132244}34 centralna jedinica, 10-30|oboren policajac, poûurite.
{132350}{132400}Stiûemo za 6 minuta.
{132772}{132856}Nemoj...
{133030}{133202}34 centrala? Recite.|10-55, otkaûite hitnu pomoÊ.
{133310}{133430}Sigurni ste? -Siguran.
{133610}{133786}Sam si ovo uradio. -Znam.
{133886}{134114}Dobro si postupio. Jesmo li bili|dobri? -Jesmo.
{134138}{134548}Dobar si ti Ëovek, voleo bih da|sam ti, takav uspeh.
{135486}{135556}Baö ti je bio neöto partner.|-Svetla.
{135596}{135784}Kako mi vidimo, detektiv Fisk je|zatvorio vrata za pesnikom.
{135924}{136226}Kako vi kaûete. Zavröili smo?|-Jesmo.
{136710}{136816}KÊerka se javila, uznemirila se zbog|Pevca i zabrinula se za mene.
{136860}{137006}Pitala je da li bih uradio neöto glupo,|a ja sam je pitao da li misli
{137016}{137080}na Ëasove obuzdavanja ljutnje ili|da se penzioniöem.
{137102}{137304}Rekao sam da Êu uraditi öto i uvek.|Rekla je da i ne bih mogla niöta drugo.
{137352}{137552}Rekla je da sam dobar policajac.|»udno, Pevac je rekao isto.
{137640}{137762}Spremni ste da igrate?|Dajte ruke.
{137787}{139287}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/ksr7|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
