{25}{175}Оглашавајте свој производ или марку код нас; контактирајте www.OpenSubtitles.org
{1740}{1860}NEVIDLJIVI COVEK
{6715}{6744}Dodjavola!
{7690}{7732}Dodjavola.
{9283}{9404}Ja sam prokleti genije.
{9687}{9743}Boze...
{9966}{10041}Sebastiane, znas li|koliko je sati?
{10052}{10139}Da Vinci nikada nije spavao.|Kaze da je to gubljenje vremena.
{10153}{10192}Ko je to ?
{10257}{10293}Ne tice te se.
{10379}{10409}Ne vise.
{10470}{10501}Linda...
{10557}{10597}...otkrio sam gde gresimo.
{10646}{10678}Provalio si?
{10687}{10717}Pogledaj ovo.
{10857}{10892}Gledaj.
{10982}{11136}Posle 11 meseci i tek tako|ti padne na pamet? Kako? 
{11148}{11229}Uobicajeno. Kafa i keks.
{11239}{11288}Mrzim te.
{11294}{11417}Mozes li da pronadjes Meta, pa dodjite u laboratoriju?|Zelim Izabel za test.
{11433}{11477}Mislim da mogu da ga pronadjem.
{11484}{11517}Kad ces moci da budes tamo?
{11525}{11597}Trebalo bi da je svanulo u Svedskoj.
{11605}{11757}Pa, mogao bih da pozovem Komitet za dodelu|Nobelove nagrade i kazem im da sam spreman.
{11784}{11843}Vidimo se za koji minut.
{12054}{12083}Met.
{12099}{12163}Sebastian je zvao.|Idemo do laboratorije.
{12172}{12227}Cemu tolika zurba?
{12235}{12266}Otkrio je gresku.
{12274}{12309}Salis se.
{12317}{12399}- Kada?|- Dok smo spavali.
{12452}{12492}Hoces da te povezem?
{12555}{12616}Mozda bi trebali da idemo|odvojeno.
{12632}{12710}Umorio sam se od ovog skrivanja, Lin.
{12717}{12778}Moraces mu reci|jednom.
{12787}{12861}I hocu, jednom.
{12867}{12925}Samo cekam pravi trenutak.
{12993}{13097}Sa njim nema|pravog trenutka.
{14480}{14517}Dobro jutro Dr. Kejn.
{14524}{14588}- Zelim vam prijatan dan.|- Hvala.
{15188}{15236}- Dobro jutro.|- Zdravo, Ed.
{15243}{15315}Vas tim je poranio danas.|Nesto specijalno?
{15322}{15397}Zao mi je, Ed. Znas pravila.
{15603}{15711}- IDENTIFIKUJTE SE, MOLIM.|- Kejn, 0027.
{15718}{15756}POTRVDJENO.
{16812}{16854}Isabel.
{17587}{17622}Dodji, lsabel.
{17644}{17698}Smiri se duso.
{17807}{17849}Dobra devojka.
{18157}{18199}U redu je.
{18250}{18298}Necu te povrediti.
{18363}{18405}Budi mirna.
{19212}{19241}Isabel?
{19248}{19308}Postaje sve agresivnija|u zadnje vreme.
{19317}{19421}Zato omamljivac i postoji.|Ja cu je uhvatiti.
{19429}{19554}Ovo predugo traje.|Pocelo je da utice na njen mozak.
{19563}{19637}- Pobrini se za taj ugriz.|- Hvala, snaci cu se.
{19794}{19857}U deset dolara da cu je|prvi srediti.
{19866}{19905}Vazi.
{20258}{20324}Izabel, tata ima|iznenadjenje za tebe.
{20867}{20909}Promasio si.
{20917}{21006}Promasio sam zato sto|ne vezbam za vreme pauze za rucak.
{21104}{21136}Dugujes mi deset dolara.
{21173}{21212}Stavi na moj racun.
{21223}{21349}Mozda cu ti jednog dana|zaista naplatiti taj dug.
{21473}{21554}Sara je izgleda ljuta.|Predlazem da budes fin.
{21562}{21683}- Ovo je sranje Sebastijane.|- Dobro jutro i tebi.
{21696}{21743}Hajde da stavimo majmuna|na sto.
{21752}{21883}Kako mozes da opravdas davanje tog|seruma Izabel bez testiranja?
{21892}{21929}Zato sto pokusavam|da ustedim vreme.
{21936}{21988}Posle je mozes i pokopati.
{21995}{22064}Mislis da pokusavam da|ubijem Izabel ovime?
{22070}{22163}- Da je ubijes? Pre da je istopis.|- Laboratorija ja spremna.
{22174}{22292}Tvoje zamerke su pribelezene|i odbijene.
{22299}{22343}Da, gospodine.
{22397}{22501}Kako to da kad kazes "Da gospodine",|zvuci kao "Jebi se".
{22522}{22553}Vezba.
{22581}{22648}Kako si me uopste ubedila|da nju zaposlim?
{22657}{22712}Trazio si najboljeg|veterinara u zemlji.
{22720}{22849}- Njoj je vise stalo do zivotinja.|- Mozda je zato tako dobra.
{22890}{22961}Kakav je taj tip sa kojim|se vidjas?
{22967}{23022}On je sve sto ti nisi.
{23059}{23103}Mora da je glup.
{23710}{23778}- Spremno u 40.|- U redu.
{23820}{23861}Vitalne funkcije?
{23869}{23894}Sve u normali.
{23900}{23974}Koriscenje reci "normalan"|ne shvataj bukvalno.
{23983}{24074}- Prva pomoc, spremna.|- Kakav je tvoj status?
{24081}{24123}Govori vam Bog.
{24128}{24204}Vi remetite prirodan|poredak stvari...
{24212}{24308}...i bicete zestoko kaznjeni|za navek vekova.
{24318}{24366}Bog je rekao svoje.
{24381}{24444}Koliko sam ti puta|rekao Frenk...
{24461}{24506}...da ti nisi Bog.
{24529}{24563}Jesam.
{24612}{24663}Izvini sefe. Zaboravio sam.
{24678}{24722}Momci, da li ste spremni?
{24728}{24761}Da.
{24779}{24889}Kao da su oni|nekada morali da nas cekaju.
{24901}{24982}Reci Njegovom Visocanstvu da je|Meri bila spremna pre dva sata.
{24992}{25042}Da, reci cu mu.
{25055}{25119}- Sve je spremno, sefe.|- Ok, snimaj.
{25126}{25153}Krecemo.
{25183}{25314}Predmet je Izabel 2.|U fazi prelaza je 126 sati.
{25444}{25498}Testiram fazni D protokol...
{25507}{25615}...ozraceni protein Kejn 125.
{25622}{25718}Ako prestanes da ih zoves po sebi,|mozda bi imao vise srece.
{25725}{25813}Hvala, Dr. Kensington,|na toj ljubaznoj primedbi.
{25820}{25866}Siguran sam da cu je ukljuciti|u svoje memoare.
{25874}{25948}I ja cu vas|staviti u moje.
{25955}{26043}Momci, budite ozbiljni|molim vas.
{26070}{26166}- Mislis li da ce preziveti?|- Ne znam. Ja samo ovde radim.
{26174}{26237}Kvantni odrazi kalibrisani.
{26272}{26338}Ok, Saro|nadji joj venu.
{26522}{26554}Sprej.
{26751}{26781}Vena je spremna.
{26828}{26870}U redu.
{26922}{26968}Idemo na sve ili nista.
{26980}{27054}Ne ti, Mat.|Cast je moja.
{27620}{27738}Inekcija ubacena u 08:47.
{28188}{28237}Otkucaji srca ubrzani.
{28343}{28406}- Jos uvek smo na zelenom.|- Potvrdjeno.
{28425}{28528}Bioelektricna energija i indikatori|kvantnog pomeraja su stabilni.
{28682}{28728}Imamo celijsku reakciju.
{29118}{29183}Radi...|Ovo zaista radi.
{29205}{29266}- Naravno da radi.|- Ne duvaj se.
{29414}{29487}Rad srca se ubrzava.|Uplasena je. U redu je.
{29493}{29628}Da nesto nije u redu, odmah|bi se manifestovale promene.
{29723}{29808}Dodjavola, pritisak joj pada,|a puls je visok.
{29995}{30029}Posmatraj joj srce.
{30119}{30199}Nepravilan rad srca|i mozdane aktivnosti.
{30209}{30288}- Dozivece srcani udar!|- Defibrilizator!
{30298}{30348}Pripremite reanimator.
{30512}{30602}- Crta je ravna. Gubimo je.|- E necemo. Udri je!
{30613}{30648}Cisto!
{30715}{30759}- Ponovo!|- Cisto!
{30859}{30896}- Ponovo!|- Cisto.
{30939}{30968}- Hajde.|- Ponovo!
{30975}{31009}Cisto!
{31049}{31089}Sranje.|Jos jednom!
{31138}{31186}Cekaj!|Nesto se desava!
{31357}{31414}Jos uvek je neravnomerno...
{31423}{31474}...stabilizuje se.
{32772}{32818}O, covece.
{32834}{32967}Mozdana aktivnost se vraca na normalu.|Kvantni odrazi stabilni.
{33050}{33107}Dobro dosla nazad, Izabel.
{33270}{33322}Tako je, duso!
{33350}{33407}- Uspeli smo.|- Dobar rad.
{33414}{33474}To! Tako se to radi.
{33482}{33549}Kako joj je|doktore?
{33610}{33679}Mislim da ce biti OK.
{33819}{33933}- Hajde. Unutra.|- Hajde Izabel.
{33939}{34013}Samo napred.|Dobra devojka.
{34079}{34124}Pogledaj kako je mirna.
{34132}{34193}Izgleda kao da joj se|nista nije dogodilo.
{34201}{34328}Zakazujem resekciju za ponedeljak.|Hocu da proverim neuropatske puteve.
{34337}{34423}Tek sto si je povratio|i vec hoces da joj seces mozak?
{34429}{34486}Ja ne vodim jebeni zoo vrt!
{34503}{34604}- Ti si prokleto jebeno kopile.|- Reci joj da se salis.
{34612}{34676}- Je li tako?|- Tako je.
{34682}{34738}Necu da je secem jos nedelju dana.
{34771}{34821}Ne budi takav seronja.
{34830}{34899}Konacno imamo nesto|da proslavimo.
{34905}{34974}- Kul. Ja sam gladan, hajdemo.|- I ja sam.
{35019}{35074}Trebali bi tebe da isecemo.
{35129}{35231}Dame i gospodo|molim vas za malo paznje...
{35237}{35267}Evo ga, pocinje.
{35273}{35366}Za najbolji istrazivacki tim|za koji sam ikada cuo.
{35374}{35411}Ziveli.
{35638}{35732}I onda je bila velika eksplozija|a zatim je ona rekla:
{35739}{35872}"Ako si tako pametan|zasto si jos u drugom razredu?"
{35879}{35961}- Kad su joj izrasle obrve?|- Za mesec dana.
{35968}{36032}- Na koliko si bio suspendovan?|- Na mesec dana.
{36564}{36623}Hej... mislila sam|da si otisao.
{36633}{36683}Nemam gde da odem.
{36764}{36817}Jesam li ja|nesto propustila?
{36829}{36898}Zar ne bi trebalo|da si srecan?
{36908}{37044}Ovo je bilo poslednje otkrovenje.|Izgleda na pocetak kraja.
{37055}{37144}To nije tacno. Pred nama|je zivotni vek posmatranja i belezenja.
{37152}{37274}Ljudi kao Met imaju strpljenja|za takve stvari, ali znas ti mene...
{37283}{37392}...meni treba veliko otkrice|i spektakl.
{37399}{37479}Takav sam ja|sa detaljima.
{37498}{37584}Znam i ja sam bila|jedna od njih.
{37699}{37785}Mislio sam da nam je|sjajno zajedno.
{37842}{37872}Ti si bio sjajan.
{37905}{37973}A ja sam samo|stajala pored tebe.
{38010}{38131}Daj, imali smo|dobrih trenutaka.
{38142}{38199}Da, imali smo.
{38307}{38386}Jesi li ikada pozelela|da vratis sat unazad?
{38430}{38478}Da ponovo pokusamo?
{38519}{38635}Takva putovanja ne postoje.
{38653}{38758}Pa, mozda bi trebali|da ih izmislimo.
{39283}{39319}Ili ne.
{40524}{40573}Kakav je to osecaj?
{40930}{41004}Pre cetiri godine, ovaj|komitet mi je dao...
{41014}{41073}...vrlo specifican|i izazovan zadatak...
{41079}{41159}...da pretvorim zivo bice|u nevidljivo...
{41166}{41225}...i da ga...
{41233}{41301}...vratim potpuno bezbedno|bez ikakvih posledica.
{41317}{41421}Otkrili smo da slanje|u zemlju Nedodjiju lako.
{41445}{41512}Vratiti ih u nazad|je bilo veoma tesko.
{41882}{41948}Primarn DNK vam se raspadao?
{41955}{42018}Praceno sa nestabilnom|celijskom vezom.
{42030}{42084}Resili ste problem?
{42125}{42156}Nisam ga resio.
{42207}{42296}Ali, blizu smo.
{42393}{42439}Samo nam treba jos vremena.
{42794}{42884}Od kako ste usli u moju ucionicu|na kao brucos...
{42892}{42943}...znao sam da ste|drugaciji od drugih.
{42951}{43041}Tokom godina je vasa genijalnost|je bila zaista impresivna.
{43061}{43098}Hvala, dr. Kramer.
{43105}{43151}Nemojte mi jos zahvaljivati.
{43192}{43278}Ovaj komitet vam je izasao|u susret van svih granica.
{43284}{43422}Tolerisali smo vasu ekscentricnost,|kao i potrebu za privatnoscu.
{43429}{43557}Ali uveravam vas da smo|na kraju strpljenja.
{43563}{43634}Ako ne dobijemo rezultate|i to brzo...
{43649}{43731}...vasa genijalnost|ce prestati da me impresionira.
{43747}{43804}I ako to ne mozete,
{43812}{43913}...nacicu nekog drugog|Sebastian Kejna koji moze.
{43930}{44018}- Sta se tamo desilo?|- Bilo bi bolje da je dobro.
{44025}{44109}- Nisam bio spreman za to.|- Ti nisi bio spreman?
{44118}{44199}To nema nikakve veze,|ako imas neke rezultate prijavi ih.
{44207}{44287}- Mogu li da objasnim?|- Upravo si slagao Pentagon.
{44294}{44354}Kada budu saznali|sta smo postigli...
{44362}{44442}...sta ce ih spreciti|da preuzmu projekat?
{44450}{44529}- Zasto bi oni to uradili?|- Zato sto im vise necemo trebati.
{44537}{44621}Ali to je njihov projekat.|Jednom ce se i to desiti.
{44628}{44715}Mozda je njihov projekat,|ali to je moj san, moja vizija.
{44723}{44828}- Sta sad predlazes?|- Da sami odradimo fazu 3.
{44837}{44884}Faza 3? Jesi li poludeo?
{44893}{44992}Ne mozes tek tako testirati|na ljudima. Postoje procedure.
{45014}{45148}Istorija se ne pravi prateci pravila.|Pravi se hvatanjem trenutaka.
{45202}{45296}Ti hoces da budes prvi.|O tome se ovde radi.
{45314}{45444}Ovde se ne radi o meni, vec o nama.|Rekli smo da cemo promeniti svet...
{45513}{45566}...i ovo je nasa sansa.
{45620}{45688}Kako si uspeo da ubedis komitet|za fazu 3?
{45699}{45778}- Ja sam volontirao. Oni su odobrili.|- Nema sanse.
{45788}{45832}Zezas me?
{45885}{45966}Ti si se prijavio?|Jesi li ti poludeo?
{46027}{46152}Jonas Salk je testirao polio vakcinu|na sebi. Da li je on bio lud?
{46159}{46218}Da. Prilicno sam siguran|da je bio.
{46239}{46279}Sranje.
{46301}{46436}Za prehodne 4 nedelje|smo vratili 7 primata.
{46443}{46557}- Rezultati govore sami za sebe.|- Mozda samo verujes u to?
{46563}{46703}Saro, mislio sam da ces biti srecna.|Ostavljamo zivotinje na miru.
{46820}{46941}Tako brzo napredovati je veliki rizik,|bez obzira o kom se radilo.
{46949}{47082}- Ne mogu da verujem da su odobrili.|- Ja mislim da je to strava.
{47092}{47124}Stvarno...
{47133}{47222}Kada bismo dalje napredovali,|ovo bi bio sledeci logican korak.
{47287}{47433}Bicu nevidljiv 3 dana|i onda cete me vratiti.
{47439}{47467}Ma ko ga jebe.
{47474}{47533}Nadam se da mogu racunati na to|da date sve od sebe?
{47689}{47718}Dobro.
{47970}{48037}Kako smo mu dozvolili|da nas nagovori na ovo?
{48081}{48138}Mozemo li o tome kasnije?
{48145}{48206}Htela sam da vodimo ljubav.
{48223}{48293}Shvatas li da rizikujemo|nase karijere?
{48363}{48411}Da, Mat.|Shvatam.
{48418}{48473}Zasto smo onda pristali?
{48493}{48603}Zato sto oboje znamo da je Sebastijan|jedini koji to moze da izvede.
{48712}{48836}- Da te pitam jos nesto.|- Da nije ko ce da bude gore?
{48983}{49025}Da li ti on ponekada nedostaje?
{49120}{49169}Zasto me to pitas?
{49177}{49242}Zato sto je ocigledno|postavio neke standarde.
{49307}{49366}Da ti kazem malu tajnu.
{49410}{49537}Koncept Sebastijana|je tezi od...
{49545}{49606}...samog Sebastijana.
{49762}{49808}Spremni smo za tebe.
{49937}{49982}Vidimo se kasnije.
{50059}{50173}- Jos uvek nije kasno da stanemo.|- A ja mislio da sam ja nervozan.
{50180}{50230}Mi smo, takodje, puno|ulozili u ovo.
{50233}{50302}Da li ste culi onaj vic|o Supermenu i Cudesnoj Zeni?
{50308}{50371}- Prestani sa zafrkavanjem.|- Ne, ovaj je stvarno dobar.
{50379}{50442}Supermen leti|iznad Metropolisa.
{50450}{50517}Napaljen je i proverava|sta se desava na krovovima.
{50524}{50656}Odjednom vidi Cudesnu Zenu|koja se sunca na jednom krovu.
{50662}{50802}Ona lezi oanko predivna, polugola,|izgleda stvarno jebozovno.
{50810}{50854}Supermen kaze sebi:
{50863}{50931}"Bas bi mi prijalo malo "cudesne" pice."
{50938}{51054}Zatim on shvata da moze|da doleti i kresne je pre...
{51062}{51149}...nego sto ona primeti,|jer on je Supermen.
{51157}{51214}Brzi je od metka.
{51223}{51331}Zato se on spusti dole i pojebe je|tako brzo da ga ona nije ni primetila, i ode.
{51338}{51473}Cudesna Zena sedne i kaze,|"Sta je to bilo jebote?"
{51487}{51562}A nevidljivi covek rece:|"Ne znam...
{51570}{51659}...ali me dupe rastura."
{51712}{51812}To je smesno, zar ne?|Ma hajde... smesno je.
{52327}{52429}Dame, molim vas.|Ovo je nauka.
{52613}{52662}Pocinjemo sa infuzijom.
{52792}{52890}- Ok. Kako se osecas?|- Malo sam napet.
{52896}{52999}Puls 88. Pritisak 140/85.|Malo je povisen. 
{53005}{53054}Pitam se zbog cega.
{53085}{53117}Da li si siguran?
{53135}{53177}Potpuno.
{53216}{53273}- Da li smo gore na "nebu" spremni?|- Spremni.
{53329}{53359}Idemo.
{53367}{53459}Nadam se da ovo nece|biti neki film sa ubistvom.
{53475}{53539}Ako je to u pitanju|ja bih njegov Pors.
{53549}{53611}Janice, kako to|mozes da kazes.
{53623}{53654}Izvini.
{53671}{53719}Pors je moj?
{53738}{53838}Subjekat je muskarac, starosti 38 godina,|tezine 75 kilograma.
{53962}{54017}Serum je gotov.
{54054}{54099}- Ovo bolje da uspe.|- Uspece.
{54107}{54179}- Ozbiljno?|- Hoces li da se kladimo?
{54187}{54262}Ako pobedim, neces biti tu|da mi platis, tako da necu.
{54271}{54301}Jesi li spreman?
{54320}{54422}Ja cu to da uradim.Tako da ako nesto|krene naopako, niko ne bude kriv.
{54502}{54533}U redu.
{54651}{54688}Tvoje zadnje reci?
{54727}{54821}Da. Ako umrem, pretvarajte se da sam|rekao nesto dubokoumno i pametno.
{55678}{55752}Inekcija ubrizgana|u 18:23.
{55818}{55917}- Osecas li nesto?|- Nista za sada.
{56022}{56089}- Sve vitalne funkcije stabilne.|- Nista se ne desava.
{56094}{56172}Ljudska DNK je kompleksnija,|mozda treba vise vremena.
{56178}{56226}- Meris li dobro.|- Da.
{56234}{56311}Proveri radijacijski deo.|Nemoguce je da nema reakcije.
{56317}{56394}Nema promene|u bioelektricnoj aktivnosti.
{56408}{56436}Jebote!
{56454}{56548}- Ponovicu proceduru, OK?|- Cekaj.
{56614}{56692}Poceo sam da osecam nesto.
{56742}{56801}Moja ruka...
{56812}{56864}Postaje toplije.
{56917}{57009}Pocinje da pecka.
{57072}{57174}Ide prema mojim|ledjima.
{57369}{57401}Pocelo je.
{57683}{57757}Sranje! Boli.
{57788}{57832}Cepa me.
{57850}{57953}Otkucaji srca se ubrzavaju.|Puls je 110... 130!
{58150}{58233}Isuse! Mislio sam da nece|ovoliko boleti!
{58248}{58279}Frenk, ocitavanja?
{58287}{58378}Mozdani talasi nepravilni.|Na granici je udara.
{58497}{58593}Puls je 165, 170.|Pritisak je 180 sa 110!
{58599}{58659}Seabastiane, da li me cujes?
{58848}{58914}- Srce ce mu puci!|- Spremi se za reanimaciju!
{58922}{58961}Stize!
{59133}{59198}Celijska aktivnost.|Pocinje pretvaranje.
{59204}{59266}Bioelektrika u crvenom!
{59304}{59336}Cekaj.
{59349}{59391}Uspece mu.
{59522}{59559}Puls je 180.
{59567}{59619}Drzi se stabilno.
{60130}{60198}Jebote...
{60366}{60492}Puls pada. 170, 160, 150.
{61088}{61204}Prelazak u nevidljivo stanje|desio se u 18:26.
{61251}{61282}Da li je on dobro?
{61289}{61391}Da, samo je u bioelektricnom soku.|Onesvestio se od bolova.
{61399}{61438}Vitalne funkcije se|vracaju u normalu?
{61444}{61527}Puls 110, opada.|Pritisak je 130/75.
{61535}{61628}- Kvantna ocitavanja u normali.|- Bioelektricni rad se stabilizuje.
{61789}{61858}Bar nesto za pricu unucicima.
{61922}{61991}Puls stabilan na 85.
{62041}{62148}Uspeo si. Prvi si.
{63232}{63277}U redu je.
{63298}{63348}Zaspala si.
{63392}{63477}- Njegovo disanje je hipnotisuce.|- Da.
{63511}{63561}Koliko je vec tako?
{63586}{63622}17 sati.
{63635}{63747}A vec imamo dovoljno podataka|za dva zivota istrazivanja.
{63760}{63806}To je ceo novi svet, Lin.
{63912}{64036}Stalno gledam u tu prazninu,|pitajuci se da li je stvarno tu.
{64061}{64152}- Vidi li ti to?|- Sebastijane, da li me cujes?
{64164}{64278}Hriste... svetlo.|Ugasite ta prokleta svetla.
{64391}{64435}Ne mogu da zatvorim oci.
{64441}{64517}Naravno, kapci su ti providni.
{64524}{64657}Cudno. Isto se osecam, ali|nisam ovde.
{64682}{64728}Tu si.
{65055}{65089}Ovde sam.
{65097}{65157}- Gde?|- Kod ogledala.
{65180}{65231}Gledam u sebe.
{65325}{65412}Odnosno, ne gledam u sebe...
{65534}{65596}Hej, kako mu je?
{65602}{65659}Zasto ne pitas Sebastijana?
{65686}{65787}- Kako se osecas?|- Nije lose, uzevsi sve u obzir.
{65953}{66008}Samo da podesim atmosferu.
{66018}{66117}Smeta mu svetlo, posto|su mu kapci providni.
{66155}{66217}Pa... kakav je osecaj|biti duh?
{66223}{66319}Duhovi su mrtvi.|A ja veoma ziv.
{66327}{66366}Hajde, ne budi krelac.
{66372}{66433}Izvini.|Nisam mogao da odolim.
{66440}{66544}Sad se osecam kao|da se igramo Marka Pola.
{66582}{66643}Pitam se|gde li je sad.
{66651}{66759}Izgleda da ova promena|nije uticala na tvoju licnost.
{66776}{66880}- Upravo je prosao pored mene!|- Sad cu ja da ga nadjem.
{66972}{67034}- Vidis li ga?|- Gde je on?
{67042}{67084}Jesi li ga video?
{67177}{67222}Uhvatio sam te sefe.
{67263}{67331}Vi momci, nemate|smisla za humor.
{67349}{67398}Sranje, o Boze.
{67405}{67528}Sredila sam da neko od nas bude|po ceo dan tu, ako ti nesto zatreba.
{67535}{67656}Ostali ce biti pored telefona|tako da ako nesto podje naopako...
{67664}{67783}Moze stici za 30 minuta. Znam.|Ja sam pisao pravila. Secas se?
{67805}{67911}Htela sam da budes siguran. Postavili|smo termo-kameru za posmatranje.
{67919}{67986}- Obozava ovo, zar ne?|- Sta?
{67993}{68069}- Da bude glavna.|- O, da. Obozava to.
{68079}{68154}Pa i bilo je vreme za promenu.
{68187}{68222}Samo, zapamtite.
{68260}{68323}Ovo je jos uvek moj projekat.
{68594}{68717}- Sigurna su u vezi nocne smene?|- Da, ionako nemam drustveni zivot.
{68724}{68810}Znam. Radoholicarski sindrom.
{68816}{68897}Karter ce doci ovamo u 6|da te zameni.
{68904}{68968}A ja dolazim u 8.|Ako ti zatrebam, pozovi me.
{68983}{69031}Bicu dobro.|Idi i naspavaj se.
{69038}{69092}- Ok. Zdravo.|- Zdravo.
{71068}{71099}Saro...|Da li si budna?
{72550}{72598}Sebastiane?
{72764}{72814}Jesi li ovde?
{73120}{73171}Znam da si ovde.
{73483}{73563}- Kako ti je prosla prva noc?|- Nespokojno.
{73569}{73638}Tesko je spavati kad|ne mozes da zatvoris oci.
{73645}{73676}Sta si radio?
{73682}{73773}Ustajao sam par puta.|Malo sam prosetao...
{73779}{73846}Sara je spomenula|nisi bio u svojoj sobi.
{73854}{73898}Isao sam po solju kafe.
{73904}{74014}Trebalo bi ubuduce da kazes dezurnom...
{74022}{74084}...gde ides ako ti se nesto desi.
{74092}{74183}Dirnula me je tvoja briga,|to nije nikakav problem.
{74189}{74249}Necemo ni da postane.
{74297}{74341}Sve je normalno,
{74392}{74448}Ok. Hajde da ovo skinemo.
{74555}{74592}Jesi li dobro?
{74608}{74638}Jesam. Zasto?
{74658}{74713}Izgledas mi malo nervozno.
{74777}{74841}Ne.|Sasvim sam dobro.
{74970}{75019}Gledas li u mene?
{75051}{75086}Ne.
{75118}{75148}Zasto?
{75234}{75263}Bez razloga.
{75552}{75657}- Kakva je klijentela?|- Taj momak mi je prisao, i rekao:
{75663}{75776}"Volim zene kao i kafu".|Ljudi se jos pale na tu recenicu?
{75782}{75868}- Mozda je mislio hladne i gorke.|- Veoma smesno.
{75876}{75957}Moram da piskim.|Drzi Kartera dalje od moje hrane.
{75963}{76049}- Trudicu se, ali ne obecavam.|- U redu.
{77248}{77309}U pocetku ce biti cudan,|ali posle ce se smiriti.
{77317}{77424}Ne, sta bi ti uradio kada bi znao|da ne mogu da te vide?
{77433}{77567}Mene podilaze zmarci.|Nisam mogla da pisam bez termo-naocari.
{77575}{77662}- Kao da bi neko zeleo to da vidi?|- Otkud znam?
{77673}{77763}Da li nas pitas sta bi mi uradili,|ili sta bi Sebastian?
{77771}{77796}U cemu je razlika?
{77804}{77878}Postoji ljudska priroda,|a postoji i Sebastijanova priroda.
{77887}{77944}On se uvek sali da je Bog.
{77953}{78036}Zamisli sta bi bilo|da on odredjuje pravila?
{78044}{78078}Strasna pomisao.
{78084}{78155}- Hvala Bogu, skoro je gotovo.|- Aleluja.
{78161}{78256}Tek smo poceli.|Mislite da je ovo sa njim lose?
{78264}{78349}Zamislite sta ce biti|ako se vojska docepa ovoga.
{78357}{78437}Bolje nasa vojska|nego neka druga.
{79838}{79896}Sebastijane, zaboga.
{79913}{80041}Nemas pojma kako je ovo zabavno.|Trebala bi da probas.
{80055}{80117}Sigurno cu imati prilike.
{80281}{80343}Hej, opusti se.
{80352}{80479}Ovo mi je poslednja noc. Zasto ne bi|izvrsili jedan eksperiment?
{80539}{80672}Mozes li da pretpostavis sta je ovo?
{80683}{80719}Sta?
{80878}{80929}Kakav je osecaj?
{80974}{81031}Malo previse poznat.
{81214}{81317}Nisi se pitala kako je|voditi ljubav sa nevidljivim covekom?
{81348}{81429}- Bilo bi kao u stara vremena.|- Kako to mislis?
{81437}{81484}Ti nikada nisi bio tu.
{81502}{81559}Sada sam ovde.
{81594}{81657}Pricali smo o ovome.|Secas se?
{81668}{81702}O cemu?
{81712}{81782}Htela si da saznas razliku.
{81814}{81897}Sebastijane, znam koja je razlika.
{81912}{82024}Ne radi se o tome sta ne vidim,|vec sta ne osecam.
{82081}{82126}Odmori se.
{82137}{82184}Sutra ces imati naporan dan.
{82417}{82469}Subjekt:|Dr. Sebastijan Kejn.
{82479}{82603}Transformisan pre|86 sati i 23 minuta.
{82612}{82731}Sve ide po redu. Ubrizgacemo|protein Kejn 127.
{82738}{82798}Iradijacija gotova.
{82809}{82841}Spremno.
{82866}{82948}- Da li si spreman?|- Nisam bas.
{83004}{83059}Poceo sam da uzivam.
{83094}{83148}Idemo.
{83192}{83256}Bice gotovo za tren, prijatelju.
{83314}{83404}Inekcija data u 09:28.
{83750}{83792}Kako se osecas?
{83810}{83877}Nesto nije u redu.
{84095}{84139}Srcana aktivnost raste.|Frenk!
{84149}{84193}Pokazatelji su poludeli!
{84199}{84301}- Bioelektrika skace.|- Proverite radijaciju.
{84362}{84398}Sta?
{84407}{84453}Sta se desava?
{84460}{84526}Ne mogu da disem!
{84532}{84618}- Proveri disanje.|- Pluca su mu blokirana. Intubacija!
{84730}{84766}Kartere!
{85524}{85613}- Menja stanje.|- Vracaj ga na sto!
{85639}{85668}Izgubili smo signale.
{85693}{85757}Prokletstvo!
{85785}{85861}- Daj mi AG-7.|- Vazi.
{86008}{86038}Nema pulsa.
{86062}{86109}Nemam puls!
{86117}{86162}Pocinjemo sa reanimacijom.
{86371}{86407}Nemoj mi umreti.
{86414}{86521}- Nemoj mi umreti.|- Imam puls.
{86644}{86736}- Sebastijane, cujes li me?|- Upada u sok.
{86929}{86974}Isuse.
{87178}{87237}Pogadjam|da nije dobro proslo.
{87243}{87281}Nije.
{87309}{87403}Izgledas zabrinuto.|Mora da je bilo gadno.
{87481}{87519}Skoro da si umro.
{87535}{87599}Sve sto me ne ubije|ucini me jacim.
{87609}{87757}Da, i prekida nase karijere.|Sta bismo onda rekli Kremeru?
{87784}{87829}Nista.
{87841}{87898}Ne mora jos da zna.
{87929}{88043}- Ne mozemo lagati ostale.|- Nemamo izbora.
{88052}{88129}Ostacu ovakav jos|ko zna koliko, pa cu morati da...
{88138}{88201}...napravim nekoliko izmena.
{88354}{88386}Gotovo je.
{88498}{88528}- Otvori.|- Ovde.
{89293}{89317}OK, dizi.
{89370}{89412}Kartere, daj ventilator.
{89845}{89894}Ok. ne pomeraj se.
{90273}{90298}Ne mici se.
{90472}{90523}Hvala.|Tako je vec bolje.
{90615}{90649}Evo...
{90689}{90778}- Ovo je poboljsanje.|- Mozes da prodjes kao covek.
{90784}{90882}- A ranije nije mogao.|- Imate lice sa kojim mozete da pricate.
{90891}{90967}Mozemo normalno da koristimo svetlo.
{91002}{91097}Ok. Hajde da pokusamo da|otkrijemo sta nije bilo u redu.
{91104}{91176}Pre nego sto i on pocne|da ujeda ljude.
{91363}{91421}- Prokletstvo!|- Sta je?
{91429}{91469}Ponovo sam izgubio koheziju.
{91492}{91551}- Jesi li se priblizio?|- Ne.
{91569}{91648}Jednostavno ne mogu da|shvatim B i C.
{91663}{91698}B i C?
{91743}{91874}Ucitelj mi je u 5-om razredu govorio|da je genije sposobnost...
{91880}{91952}...da predjes sa A na D, bez prolazenja|preko B i C.
{91963}{92011}Sebastijan to moze.
{92017}{92124}Ali ja, moram na B i C.
{92227}{92299}Drzi se, Sebastijane.|Jos malo, pa smo tu.
{92358}{92408}Hajdete momci. Sklanjajte se.
{92786}{92849}Ne mogu vise da|podnesem ova testiranja.
{92857}{92894}Znam da je tesko.
{92902}{92968}Seres.|Nemas ti pojma.
{92976}{93029}Ovo nije lako nikome|od nas.
{93036}{93132}Jebi se Mat!|Lako je tebi.
{93166}{93234}Samo tri dana sam|trebao da budem u ovom stanju.
{93243}{93308}A bicu jos deset.|Jel' tako?
{93318}{93442}Deset dana jebenih testova,|zracenja i igala.
{93482}{93558}Ne mogu vise da izdrzim.
{93567}{93639}- Mislio sam da...|- Zajebi to sto si mislio!
{93654}{93687}I nemoj nikada...
{93693}{93762}Nemoj mi reci|kako ti je tesko.
{94197}{94246}Ovde je.
{95083}{95178}Uh, kako bih ti lizao sisice...
{95219}{95271}Dr. Kejn, sta se desava.
{95278}{95379}Samo da ti kazem da idem|malo napolje.
{95392}{95476}Stani. Idete napolje?|Sacekajte trenutak.
{95573}{95608}Dr. Kejn!
{95614}{95656}Kako to mislis?
{95664}{95724}Ako ne odem malo napolje,|poludecu.
{95733}{95804}- Ne mozete izaci takvi odavde.|- Zasto ne?
{95813}{95891}- Takvo je pravilo.|- Moje pravilo i upravo ga menjam.
{95899}{95968}- Identifikacija.|- Kejn 0027.
{95976}{96041}- Potvrdjeno.|- Ne mozete ga tek tako promeniti.
{96048}{96149}Ne zelim da trosim svoj zivot u ovoj,|od Boga zaboravljenoj, laboratoriji.
{96157}{96236}Odoh napolje. Vracam se|za par sati.
{96243}{96293}Sranje!
{96511}{96632}- Zdravo!|- Ovde Karter. Imamo problem.
{97156}{97237}- Kako ide Ede?|- Zdravo doktore.
{97271}{97390}- Nisam vas dugo video.|- Znas kako je po nekada.
{97396}{97424}Rad, rad, rad...
{97432}{97536}Poceo sam da brinem posto|vam kola stoje.
{97545}{97604}Puno ti hvala Ed.
{97613}{97657}Ali sve je u redu.
{98848}{98906}Hej, pogledaj, vidi!
{98913}{99012}- Pogledaj ovo!|- Covece, sto je cudan!
{99062}{99104}- O moj boze!|- Mama, Mama!
{99113}{99182}- Mama! Mama!|- Sta je bilo?
{99211}{99248}- Sta?|- Pogledaj. To je duh.
{99255}{99354}- Ne budi smesan.|- Mama ali to je duh.
{99386}{99498}Naci cemo se u laboratoriji.|Otici cu do njegovog stana samo da proverim.
{99508}{99541}Ok, videcemo se tamo.
{99558}{99598}Mogao bi biti ovde.
{99659}{99704}Mogao bi biti bilo gde.
{101400}{101434}Sranje.
{101765}{101826}Ni ne pomisljaj na to.
{102029}{102074}Ko ce saznati?
{107837}{107892}Sranje.
{107964}{108027}Met, ja sam. Bio je ovde.
{108033}{108102}Ne, skinuo je masku.
{108110}{108217}Mora da je negde napolju.|Nemam pojma gde je otisao.
{108223}{108278}Idem nazad do laboratorije.
{108300}{108399}Kako? Kako to da uradim?|Ne mogu ni da ga vidim.
{109675}{109749}Kazes da zelis da ga|upucamo? Ja sam za.
{109755}{109863}To nije majmun vec Dr. Kejn.|Da nismo malo preterali?
{109871}{109969}Ne dajem ni pet para ako smo preterali.|Napolju, on je rizik.
{109976}{110088}Ako neko sazna sta je on,|ceo projekat je propao.
{110094}{110201}Opusti se.|Niko nece saznati.
{110209}{110268}- Da li i dalje mogu da ga upucam?|- Gde si bio?
{110281}{110313}Rekao sam Karteru.
{110338}{110429}Postao sam uznemiren. Otisao sam|kuci da pokupim neke stvari.
{110438}{110473}Seres?
{110489}{110517}Bila sam u tvom stanu.
{110524}{110597}Uradio si vise od|"uzimanja stvari".
{110604}{110712}- O cemu pricas?|- OD svih ljudi, ti. Kako mozes?
{110718}{110774}Sta si videla u mom stanu?
{110781}{110837}Videla sam tvoje lice i|tvoje stvari.
{110843}{110933}Sebastian u javnosti.|Zasto si morao da izlazis u javnost?
{110940}{111067}Ja sam i dalje vodja projekta.|Ja donosim odluke.
{111081}{111178}U pravu si.|To je tvoja odluka.
{111199}{111315}Ali ako odes ponovo, kunem se|da cu otici u odbor.
{111344}{111412}I odbaciti svoju karijeru?
{111431}{111477}Najverovatnije ne.
{111529}{111559}Probaj me.
{111797}{111847}Znaci to je... a?
{111859}{111916}Zvanicno, ja sam zamorce.
{111923}{111992}Prijavio si se dobrovoljno.|Znao si za posledice.
{112034}{112127}Sledeci put kad ides u nabavku,|nabavi mi i tocak da vezbam.
{112134}{112177}Ok, naravno.
{112223}{112284}Spakujmo se i|krenimo kuci.
{112309}{112412}- Tocak za vezbu? On to ozbiljno?|- Sta mislis?
{112468}{112557}Odbor zna sta radimo.|Zar ne?
{112631}{112717}- Sranje Lin!|- Nema veze ako ga vratimo nazad.
{112723}{112832}- Ne mogu da verujem da si to uradila!|- Mogla si da odbijes, a nisi znala.
{112859}{112957}Sve sto trazim je,|molim te ne zajebavaj nas.
{113127}{113211}- Mislis da je rekla nesto?|- Ne, ona je u ovo zabrazdila.
{113219}{113271}- Ona me ne brine vise od...|- Sebastijana.
{113278}{113412}Nevidljiv je duze od zivotinje.|Moze uticati na njegov mozak.
{113418}{113467}Sta ako vec jeste|uticalo?
{113569}{113603}Miran.
{113753}{113782}Dobro.
{113813}{113922}- Pa kako je bilo?|- Kako to mislis?
{113929}{114057}- Kad si bio napolju.|- Samo sam isao okolo. Znas.
{114063}{114153}Samo si setao okolo.|Ma daj, ima i vise zar ne?
{114164}{114203}Na primer sta?
{114232}{114279}Covece, da sam to bio ja...
{114288}{114371}...zajebavao bih ljude,|saputao im na uvo.
{114381}{114477}Visio bih u Victoria's|Secret. Bio bih kralj.
{114594}{114642}Detinjasto, zar ne?
{114656}{114688}Ne.
{114730}{114817}Pa, kasno je.|Nisam dugo bio napolju.
{114829}{114878}Jesi li video nekoga?
{114886}{114942}Bila je jedna devojka.
{114992}{115051}- Jesi li se petljao sa njom?|- Ne.
{115096}{115216}Pa... mozda sam je malo uplasio.
{115238}{115278}Kakav je osecaj?
{115312}{115353}Svidja mi se.
{115425}{115466}Lepo.
{117859}{117988}Lin, secas se B i C?|Mislim da sam pronasao.
{118030}{118127}55% reverzije.|To je najbolje do sada.
{118134}{118278}Proteinska struktura je corsokak.|Kljuc je u upravljanju radijacijom.
{118284}{118378}75%. 80%.
{118388}{118446}- 82.|- Hajde.
{118461}{118498}Uspeli smo.
{118505}{118536}Ne, usporava.
{118542}{118601}- Budi optimista.|- Usporava.
{118609}{118701}88. 92%.
{118734}{118792}93%.
{118824}{118883}94%.
{118915}{118964}95%.
{119079}{119118}- Ne!|- Sranje!
{119153}{119299}- Celijska veza puca.|- Puna kvantna kaskada na 95%.
{119311}{119352}Neki napredak.
{119358}{119462}Da sam sad na stolu,|bio bih gomila pecenog mesa.
{119477}{119501}Ne iskusavaj me.
{119509}{119552}Sve smo blize.
{119558}{119651}Blize! Samo je zamenio kvantnu|energiju za stabilnost!
{119658}{119696}- Smesno je.|- Hajde!
{119703}{119794}- Nerviras me sto nisi mislio na to.|- Stavrno Met?
{119801}{119897}95%?|To cak nije vredno mog vremena!
{119953}{119979}Seronjo.
{120267}{120332}Ti si idiot. Sta je tvoj problem?
{120342}{120439}Met ide ka necemu,|koristila bi mu tvoja pomoc.
{120493}{120567}Da, on ide ka necemu.|Ok.
{120573}{120672}On se kiti mojim perjem,|i to vec godinama.
{120678}{120781}Sidji sa svog jebenog trona.|On se ubija od posla pokusavajuci da ti pomogne.
{120817}{120843}Ili da me ubije.
{120892}{120953}A znas li sta je najtuznije?
{120962}{121051}Imam ovaj dar,|a ne mogu ga iskoristiti.
{121084}{121133}A sada je to dar.
{121140}{121188}Naravno da je dar.
{121194}{121328}Da niste bili tako kratkovidi|pustili bi me iz ovog kaveza da istrazujem.
{121348}{121491}Da ti nisi bio tako kratkovid bio bi|sa nama pokusavajuci da spases zivot.
{121548}{121592}Moj zivot?
{121604}{121658}Ja nemam jebeni zivot.
{121669}{121711}Ja sam zatvorenik.
{121786}{121858}- Ne, ti nisi zatvorenik.|- A, je li?
{121877}{121964}Da li o tome mislis kad|odlazis odavde nocu?
{121972}{122051}Jel tako ti opravdavas|svoju krivicu...
{122058}{122204}...dok sam ja zarobljen u ovoj rupi|a ti se kod kuce...
{122212}{122272}...jebes sa svojim deckom?
{122383}{122439}Sta te najvise muci?
{122459}{122521}To sto nemas zivot...
{122596}{122646}...ili to sto ja radim?
{123778}{123841}Frenk, dolazim|dole u laboratoriju.
{123855}{123897}Zar ne spavas?
{123903}{124017}- Da Vinci nikada ne spava.|- OK. Ovde sam ako ti zatrebam.
{125597}{125687}Znam Virginio...
{125694}{125783}Virginio znam...
{125792}{125853}Ne, ne, ne, ne.
{127244}{127298}Mamu ti jebem...
{127324}{127421}Da si stigao kasnije,|pocela bih bez tebe.
{127854}{127879}Isuse!
{128237}{128286}Nista ne vidim.
{128516}{128553}Halo?
{128576}{128611}Ne.
{128617}{128662}Ne, ovde je.
{128671}{128746}Da, siguran sam.|Gledam u njega.
{128765}{128802}Nesto nije u redu?
{128816}{128922}- Hocete da ga probudim?|- Ne, upravo sam proverio.
{129053}{129115}Sta dodjavola ona|misli da je.
{129121}{129203}Nisam dovoljno dobar za nju?|Nisam dovoljno dobar?
{129211}{129281}Pokazacu im oboma|koliko sam dobar.
{129288}{129328}Tisina!
{129404}{129453}Tisina!
{129467}{129521}Hoces da se zajebavas|sa mnom kucko?
{129528}{129609}Znas li sta se desava|kad se zajebavas sa mnom?!
{129941}{130052}Ne brini. Niko te nece povrediti.|Niko.
{131417}{131521}Stvarno je pametna. Sve sto radi|je da stalno vrti iste slike.
{131527}{131573}Sta da radimo?|Da idemo za njim?
{131584}{131652}Ne. Idemo u odbor.
{131659}{131721}Zar ne bi trebali da sacekamo|i popricamo sa njim?
{131729}{131796}Ubio je psa, golim rukama.
{131802}{131874}- Bio si tamo?|- Odlazi svaku noc...
{131881}{131977}...a da uopste ne brine za|svoju i nasu sigurnost.
{131983}{132054}- Sta je uradio?|- Ne zelim da znam.
{132062}{132148}- Jesmo li u nevolji?|- Ti nisi prevario odbor.
{132166}{132214}Preuzimamo odgovornost.
{132222}{132303}- Sta cemo da uradimo kad se vrati?|- Nista.
{132312}{132371}Odbor ce nas osigurati.
{132377}{132433}Recicemo ti sutra ujutro.
{132790}{132899}Imao sam mnogo poverenja u tebe,|misleci da ces se pobrinuti za sve.
{132908}{132972}Znam da je pogresno|ono sto smo uradili.
{132980}{133117}"Pogresno" je preblaga rec.
{133132}{133183}Hajde da to ostavimo ovde.
{133301}{133388}Zvacu generala Kastera|da zakaze sastanak odbora.
{133396}{133467}Ti se vrati u laboratoriju.|Mi cemo se pobrinuti za njega.
{133473}{133519}Ima li jos nesto|sta bismo mogli da uradimo?
{133526}{133609}Mogao bi da mislis o|ciscenju svoje kancelarije.
{133654}{133746}Oboma nam je|veoma zao.
{133753}{133822}Malo je kasno za izvinjenje.
{133930}{133964}Hauarde?
{133987}{134027}O cemu se radi?
{134043}{134116}- Samo neki problemi na poslu.|- Koliko ozbiljni?
{134123}{134182}Dovoljno da probude par generala.
{135909}{135953}Zdravo sefe.
{136413}{136438}Upomoc!
{136574}{136617}Upomoc!|Upomoc!
{137441}{137473}Howarde!
{138199}{138274}- Zasto si nervozan?|- Iznenadio si me.
{138286}{138346}Nema "Dobro jutro" za mene danas.
{138359}{138408}Ne volis me vise.
{138428}{138504}- Samo sam u zurbi.|- OK onda.
{138523}{138588}Ovo ce biti veoma naporan dan.
{138807}{138847}Kada se vratio?
{138855}{138953}U 3 sata. Lutao je oko laboratorije|kao nikada do sada.
{138969}{138999}Kramer je vec zvao?
{139009}{139089}Verovatno jos sastanci|sa komitetom.
{139102}{139199}Trebalo je nesto da cujemo.|Zovem ga.
{139289}{139346}Halo, da li je|dr. Kramer tu?
{139366}{139402}Sta?
{139505}{139546}O Boze!
{139589}{139678}- Sta nije u redu?|- On je mrtav.
{139684}{139773}- Sta?|- Udavljen je u bazenu prosle noci.
{139954}{140009}Generala Kastera molim.
{140187}{140228}Nema signala.
{140293}{140407}- Ni ovde nema izlaznog signala.|- Bolje da zovemo obezbedjenje.
{140515}{140616}- Ovlascenje molim.|- McKay 1-Delta-835.
{140637}{140711}Ovlascenje pogresno.|Zahtev odbijen.
{140723}{140842}To je prvi put. McKay 1-Delta 835.
{140857}{140913}Ovlascenje pogresno.|Zahtev odbijen.
{140937}{140983}Daj da ja pokusam.
{141009}{141083}Kensington 2-Romeo-159.
{141089}{141179}Ovlascenje pogresno.|Zahtev odbijen.
{141303}{141349}Imamo problem.
{141460}{141492}Ne mogu da verujem.
{141499}{141643}- Kada ce poceti da nas traze?|- Moze potrajati i nekoliko dana.
{141650}{141747}- Mozes li da provalis u sistem?|- Vec sam usao.
{141813}{141918}- Neki zastitni sistem.|- On je izvanredan.
{141926}{141999}Nekako je bolji|od mene.
{142039}{142093}- Sta je to?|- Sistem je dobar.
{142099}{142226}Nas pristupni kodovi su obrisani.|Ostao je samo jedan.
{142378}{142454}- Mi smo u klopci.|- Uhvaticemo ga.
{142461}{142503}Daj mi jedan.
{143385}{143428}Nije ovde.
{143504}{143606}Ok, Sebastijane. Zabava je zavrsena.|Reci nam gde si.
{143614}{143718}Izvini Linda, ali ti ne mogu|dopustiti da me prijavis.
{143774}{143821}Sebastijane, gde si?
{143839}{143892}Ti nemas pojma kako je to.
{143914}{144028}Moc, sloboda.|Ne mogu to da ostavim.
{144057}{144181}Sta god da si planirao|telefoni, liftovi...
{144193}{144286}...nece ti uspeti.|Znaju sta se desava.
{144292}{144329}Ne, ne znaju.
{144342}{144411}Kramer je umro pre|nego sto je rekao bilo kome.
{144430}{144473}Video sam to.
{144479}{144506}Isuse.
{144522}{144657}- Shvatas li uopste sta pricas?|- Neverovatno je sta sve mozes da uradis...
{144663}{144773}...kad ne moras da se pogledas|u ogledalo.
{144799}{144861}- Sebastijane.|- Zbogom Linda.
{144929}{144968}Sranje!
{145036}{145077}Gde je Janice?
{145104}{145149}Bila je iza nas.
{145158}{145204}Jebi ga.
{145211}{145298}Jebi ga.|O Boze.
{145771}{145803}Ovde.
{145893}{145962}- Strelice.|- Da li je to bio Sebastijan?
{146218}{146268}O, Boze.
{146275}{146304}Sranje!
{146314}{146358}O, Boze.
{146432}{146471}Bila je odmah iza nas.
{146480}{146551}Kako je mogao to da uradi?
{146564}{146637}Pukao je.|Jednostavno je pukao.
{146652}{146688}Sve gore je.
{146705}{146777}- On je na sve mislio.|- Sta?
{146783}{146846}Znao je da cemo ga prijaviti.
{146858}{146971}Znao je da ce njegova karijera|biti gotova, i njegov jedini izlaz...
{146979}{147102}...je da se uveri da niko ne zna|sta je on, ili sta je uradio.
{147112}{147213}- Sto znaci da ce nas pobiti.|- Proklet bio!
{147226}{147288}- Mogli ste da zaustavite to.|- Smiri se.
{147294}{147357}- Rizikujes nase zivote.|- Cuti!
{147363}{147427}Ne govori joj da cuti!|U pravu je!
{147433}{147537}Ne zanima me da li je u pravu.|Ne interesuje me cija je ovo greska!
{147549}{147621}Samo zelim da znam|sta sada da radimo?
{147683}{147742}Frenk, mozes li da|povratis sifre?
{147775}{147866}- Pokusacu.|- Ne mozemo sebi dozvoliti|da ovde sedimo i cekamo.
{147873}{147968}Necemo cekati.|Uhvaticemo ga.
{147998}{148042}Da li si koristio ovo ranije?
{148049}{148142}Napravili smo to za pronalazenje|pacova koje smo gubili.
{148149}{148202}Suvise mali za termalno skeniranje.
{148217}{148296}- Povezujem.|- Ukljucenje.
{148302}{148371}Aktiviram detektore kretanja.
{148387}{148433}Imamo kretanje.
{148459}{148526}- Koridor 6.|- Tamo je.
{148598}{148639}Imamo ga.
{148678}{148718}- Proveri.|- Proveri!
{148731}{148799}- Mat, budi oprezan.|- Cuvaj nam ledja.
{148806}{148856}- Spreman?|- Uradimo to.
{149105}{149173}Skreni levo u sledecem koridoru.
{149180}{149242}Mozemo li ga zarobiti|u koridoru osam?
{149248}{149352}- Ako nastavi u tom pravcu.|- Ja sam u koridoru pet.
{149643}{149703}- Ima li sta?|- Mislim da mozemo da izadjemo odavde.
{149711}{149778}Postoje pomocne stepenice|pored lifta.
{149836}{149889}Sranje, izgubio sam ga.
{149904}{149959}- Izgubio sam ga.|- Stao je.
{150038}{150062}Ja sam.|Ja sam.
{150133}{150184}- Imas li ti nesto?|- Nista.
{150193}{150237}Kako je mogao da prodje|pored nas?
{150243}{150288}Nije mogao.
{150362}{150433}Tamo. Iza cevi.
{150522}{150559}Dr. Kejn?
{150585}{150659}- Cujete li me.|- Uhvaticu ga.
{150702}{150741}Pokrivaj me.
{150760}{150787}Pokriven.
{151220}{151324}To je samo ventilacija.|To je samo prokleta ventilacija.
{151514}{151568}Pusti ga!|Pusti ga!
{151973}{152013}Met, sta se desava?
{152034}{152088}Karter je pao.|Gadno je povredjen.
{152097}{152122}Izlazi odatle.
{152141}{152189}Gde je jebote Sebastijan?!
{152198}{152269}Sranje. Iznad tebe je.
{152554}{152653}- Gde je krenuo?|- Dolazi ovim putem u laboratoriju.
{152668}{152738}Vrata su zatvorena!|Zatvorio me je!
{152798}{152836}- Imas ga?|- Da.
{152851}{152924}Jos je tu.|On je sa tvoje strane vrata.
{152934}{152994}- Gde?|- Pravo ispred tebe.
{153001}{153038}Ide ka tebi.
{153121}{153201}Imam toplotu u celoj prostoriji.|Pet ili sest.
{153314}{153349}Gubim sliku!
{153472}{153574}Ispumpava toplotu.|Neces moci da ga vidis.
{153608}{153683}Vazduh ima istu temperaturu|kao i njegovo telo.
{153692}{153724}- U zamci je.|- Idem.
{153733}{153793}- Nije sigurno. - Idi po Kartera.|Naci cemo se u laboratoriji.
{153801}{153858}- Ne smemo da se razdvajamo.|- Idi po Kartera.
{153867}{153926}Marco. Polo.
{154012}{154048}Marco.
{154125}{154149}Promasio si.
{154156}{154304}- Sad je dobro vreme da ti naplatim.|- Hajde. Mislis da mozes protiv mene?!
{154312}{154352}Hajde!
{154559}{154593}Sta se desava sa tobom?
{154601}{154686}Da li te je sjebao serum ili moc?
{154741}{154883}Zar nisi ti taj koji je sjeban?!|Kupis moje ostatke...
{154904}{154979}...nemas zivota, osim onog|koji si pozajmio od mene!
{155010}{155084}- Cak i sa Lindom!|- Ona te je napustila. Secas se?
{155091}{155218}Isuse, ne mogu da zamislim. Sta je|ona videla u gubitniku kao sto si ti!
{155227}{155278}Ja nisam poremeceni seronja!
{155287}{155356}Ne, ali si slabic.
{155489}{155594}Mislio sam da cu te tesko|ubiti! Ali mi se nekako svidja.
{155985}{156113}Jebiga!|Puls mu je slab. Disanje je slabo.
{156119}{156172}- Bice OK!|- Ne, on umire!
{156178}{156256}- Bice OK!|- Dolazi ovamo!
{156264}{156333}Drzi pritisnuto ovde|dok se ne vratim.
{156339}{156397}- Gde ces?|- Potrebna mu je krv.
{156403}{156504}- Sacekaj ostale!|- Ako sacekam, umrece!
{156537}{156561}Jebi ga!
{156984}{157054}Boze, rekao sam da se nadjemo ovde.
{157592}{157633}O, Boze.
{158316}{158418}Hajde. Daj mi jedan korak,|Sebastijane. Samo jedan jebeni korak.
{158436}{158466}Pokret!
{158735}{158772}Jebi ga!
{158828}{158874}Prilicna zbrka.
{159091}{159139}Jebi ga!|Mamu ti jebem...
{159178}{159216}Odlazi!
{159252}{159372}- Ludo smo se zabavljali prosli put.|- Ne molim te. Nemoj.
{159391}{159426}Lepo spavaj.
{159712}{159748}Znas...
{159794}{159866}...uvek sam se divio|tvojoj zivahnosti.
{160358}{160438}Proklet bio Kartere!|Nemoj umreti sad.
{160464}{160539}Saro, gubim ga.
{160580}{160629}- Gde je ona?|- Bila mu je potrebna krv.
{160636}{160709}- Otisla je sama?|- Mogao bi da umre!
{160729}{160773}Mrtav je.
{160793}{160831}Hajde.
{161126}{161156}Cekaj.
{161623}{161671}Nastavi sa prskanjem.
{161786}{161828}O, ne.
{162018}{162053}Nista.
{162101}{162152}Sta se desava?!
{162210}{162293}Mrtva je, zar ne?
{162463}{162489}Isuse.
{162716}{162775}Imam ga.|Imam ga.
{162822}{162869}O, Boze!
{163235}{163278}- Jebi ga.|- Pa-pa, Linda.
{163309}{163369}Zabavljaj se sa svojim momkom.
{163456}{163502}Zakljucani smo ovde.
{163554}{163602}Koliko je lose?
{163657}{163747}Gubis krv,|ali nije pogodio ni jedan organ.
{163755}{163817}- Frenk?|- Ne.
{163874}{163952}Moram da nadjem nesto|da zatvorim ranu.
{164109}{164148}Sranje.
{164269}{164306}Pricaj sa mnom.
{164313}{164403}Sve mi se vrti.
{165191}{165288}- Jesi li jos sa mnom?|- Nista ne osecam.
{165336}{165380}Mozes li da osetis ovo?
{165415}{165453}Malo.
{165466}{165493}Hajde.
{165499}{165543}Moraces da se boris.
{165552}{165619}- Treba mi da ostanes budan.|- Trudim se.
{165632}{165714}Hajde. Pricaj sa mnom.
{165728}{165759}Pricaj sa mnom!
{166823}{166877}Zdravo, lice.
{168362}{168438}Necemo umreti ovde.
{171983}{172057}Vraticu se sa pomoci.|Obecavam.
{172862}{172976}- Ovlascenje molim.|- Kejn 0027.
{172983}{173058}- Potvrdjeno.|- Hvala.
{173117}{173207}- Ne mogu da te ostavim.|- Zao mi je, ali nemas izbora.
{173213}{173269}O, da. Imam.
{173762}{173862}Mislis da si Bog?|Pokazacu ti ja Boga!
{176242}{176301}Oduvek sam znao da si bila kucka!
{176498}{176523}Kucko!
{176625}{176688}Nije ni cudo sto nije islo|medju nama!
{176958}{177029}Drzi se dalje od nje!
{177124}{177194}Mislio sam da ja tebe|spasim za promenu.
{178094}{178156}Hajde.|Cuo sam eksploziju.
{178645}{178684}- Ne diraj to!|- Sta?
{178692}{178749}- To je nitro.|- Moramo da ga zaustavimo.
{178756}{178803}Ne, ne mozemo!|Hajde!
{178809}{178871}Tamo, na liftu su merdevine.
{179002}{179068}- Mozes li da se penjes?|- Imam li izbora?
{179634}{179681}Ti prvo.
{181188}{181224}Pokret!
{181582}{181616}O, sranje!
{181648}{181686}Pomeri se sa strane!
{182084}{182137}Vraca se opet!
{182302}{182331}Dole!|Idi dole!
{183229}{183257}Sranje.
{183359}{183416}Bolje da krenemo pre nego|sto sklizne.
{184441}{184521}Sklanjaj se od mene!|Sklanjaj se od mene!
{185809}{185931}- Pusti me!|- Poslednji poljubac.
{185977}{186031}Za dobra stara vremena.
{186644}{186671}Idi dodjavola.
{187514}{187538}Hajde.
{188058}{188102}O, Boze.
{188109}{188211}Nije Bog. Ne vise.
{188236}{189736}Молимо вас да оцените овај титл на www.osdb.link/33hud|Помозите другим корисницима да изаберу најбоље титлове
