{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{677}{750}Legenda kaûe da su je |napisali MraËni.
{750}{925}Nekronomikon Eks Mortes, grubo|prevedena kao "Knjiga Mrtvih"
{1006}{1160}Knjiga je sluûila kao prolaz|do zlih onostranih svetova.
{1249}{1411}Napisana je davno,kada su|mora bila crvena od krvi.
{1444}{1524}Tom krvlju je napisana knjiga.
{1656}{1794}1300.godine, knjiga je nestala.
{2213}{2320}ZLA SMRT II
{2610}{2776}Kako izgleda ta koliba?|-Malo je troöna.U planini je.
{2776}{2966}Siguran si da je prazna?|-Da.Mislim da jeste.
{3894}{3954}äta misliö?
{4015}{4108}Svidja mi se Ash.
{4157}{4223}Mljac,Mljac.
{4318}{4417}»udno se oseÊam ovde.|äta ako se vlasnici vrate?
{4417}{4513}NeÊe se vratiti.|Ako ipak do toga dodje,
{4513}{4588}reÊi Êemo da su nam se kola|pokvarila ili tako neöto.
{4588}{4628}Poverovali bi.
{4651}{4757}äta kaûeö da popijemo|malo öampanjca?
{4757}{4836}Ipak ja sam muökarac,a ti ûena.
{4836}{4953}Tako je bilo kad sam poslednji|put proveravao.
{5328}{5494}Hej,ovde je magnetofon!|-Vidi öta je snimljeno.
{5554}{5682}Ja sam profesor Rejmond Nobi,|iz Odeljenja za staru istoriju.
{5706}{5799}Mislim da sam doöao|do izuzetnog otkriÊa
{5799}{5913}u zamku Kandar.Tamo sam|putovao sa svojom ûenom,
{5913}{6020}Henrijetom, kÊerkom Eni|i pomoÊnikom, Edom Keylijem.
{6020}{6146}U zabaËenoj prostoriji zamka| pronaöli smo neöto izuzetno:
{6146}{6300}Naturam Demantom,|"Knjigu Mrtvih"
{6344}{6418}Moja supruga i ja doneli smo |knjigu u ovu kolibu,
{6418}{6526}gde sam mogao da je|neometano prouËim.
{6526}{6614}Ovde sam poËeo sa prevodjenjem.
{6614}{6707}Knjiga govori|o duhovnom prisustvu,
{6707}{6857}zlu koje luta öumama i tamnim|prostorima Ëovekovog staniöta.
{6857}{6948}Izgovaranjem odlomka knjige,
{6948}{7114}tom mraËnom duhu se daje|dozvola da zaposedne biÊe.
{7140}{7325}Pravilan izgovor tih|pasusa je sledeÊi...
{7884}{7931}Linda!
{8004}{8075}Linda!
{14454}{14530}Nestalo je.
{14547}{14582}Sunce ga je oteralo.
{14723}{14806}Za sada.
{14850}{14971}Moram pobeÊi pre mraka.
{15230}{15338}Pridruûi nam se!
{16632}{16770}Moram...Moram da se saberem!
{20883}{20920}Hval bato.
{21045}{21125}Eni!|-Zdravo!
{21125}{21178}Kako je proöla ekspedicija?|-Sjajno.
{21178}{21230}Pronaöla sam stranice|"Knjige Mrtvih".
{21230}{21393}Znam.Dobio sam tvoj telegram.|U kavom su stanju?-Pogledaj.
{21393}{21482}Nisu ostarile ni dan,a proölo|je 3000. godina.-Moûda i viöe.
{21482}{21538}Kada Êemo poËeti sa|prevodjenjem?-VeËeras.
{21538}{21598}Da li je sve dogovoreno |sa mojim ocem?
{21598}{21650}Trebalo bi da bude,ali nisam|nedelju dana razgovarao sa njim.
{21650}{21734}U kolibi nema telefon.|Idemo mojim autom.
{21734}{21819}Do tamo Êe nam trebati|jedan sat.
{21831}{21882}U telegramu si napisala da je|tvoj otac naisao na neöto
{21886}{21962}u prvom delu prevoda.äta je| pronaöao u"Knjizi Mrtvih"?
{21992}{22137}Verovatno niöta.|Moûda prolaz u drugi svet.
{27068}{27146}Igraj sa mnom!
{28332}{28375}Zdravo ljubavi!
{29110}{29151}Radionica!
{29938}{30043}Sada imamo duöu|tvoje Linde!
{30043}{30202}Ona pati u beskonaËnim mukama!|-Gotova si!
{30245}{30290}Motorna testera!
{31497}{31582}Molim te,Ash,|nemoj me povrediti.
{31582}{31710}ObeÊao si da Êemo zauvek|biti zajedno.Volim te!
{31710}{31769}Neee!!!!
{31769}{31818}Da!
{31818}{31954}Tvoja ljubav je bila laû!|Ona sada gori u paklu!
{35659}{35888}Dobro sam.Dobro sam.
{35888}{35946}Ne bih rekao!
{35946}{36041}Upravo smo isekli naöu devojku|motornom testerom.
{36041}{36162}Da li to zvuËi dobro?
{37542}{37776}Kopilad!Prokleta kopilad!
{37918}{38018}Vratite mi ruku!
{38842}{38890}Izvinite!
{39062}{39246}Izvinite,da li je ovo put |prema kolibi Nobijevih?
{39246}{39360}Tako je, ali vi neÊete tamo.|-Zaöto?
{39594}{39760}Mora da postoji neki drugi put.|-Nema puta.
{39870}{39940}äta Êete uopöte tamo?
{40069}{40126}Ne tiËete se.
{40266}{40448}Setio sam se!|Tako je, postoji jedan putiÊ.
{40448}{40590}Mogli bi ste da pratite Bobi Dûo|i mene.-ZvuËi u redu.
{40590}{40650}Ali, to Êe vas koötati.|-Koliko?
{40650}{40790}»etrdeset...Sto dolara.
{40790}{40974}NosiÊeö moj prtljag|i dogovorili smo se.
{40974}{41102}Naravno!
{43719}{43814}Tako je! Ko se sada smeje?
{43974}{44062}Ko se sada smeje!?
{45207}{45345}Zaboga!A priËala je|o dve male torbe!
{45630}{45706}Ovo je tvoja nova kuÊa.
{45870}{45938}ZBOGOM ORUéIJE
{48071}{48119}KuËkin...
{48634}{48738}Sredio sam te, malo djubre.
{49512}{49639}RazneÊu te na parËiÊe!
{49660}{49715}VideÊeö!
{53730}{53809}Udari ga!
{53809}{53885}Kopile!
{54101}{54213}HoÊeö li biti dobro?|-Ne znam, mislim da hoÊu.
{54234}{54288}Sedi mirno.
{54308}{54349}Poznajete li ovog |kuËkinog sina?
{54349}{54421}Ne.Mislili smo da Êe njen otac|biti ovde.Zato smo odluËili...
{54421}{54506}Gospode!Gde su moji roditelji?
{54782}{54921}äta si im uËinio?!
{54936}{55028}Eni dodji ovamo!
{55158}{55242}Hajde da ga ubacimo unutra.
{55302}{55433}Poludeo je.|-Pogreöio sam.
{55590}{55683}»ekajte!
{55683}{55793}Pogreöio sam!|Tako je,kuËkin sine!
{55983}{56100}Nadam se da Êeö|dole istruliti!
{56232}{56270}Sranje!
{56270}{56358}Znam da te boli,draga,|ali sve Êe biti u redu.
{56358}{56461}Za pet minuta Êu otiÊi|da dovedem öerifa.
{56477}{56558}Proverio sam sve sobe.|Tvoji roditelji nisu ovde.
{56558}{56658}Moûda nisu ni dolazili.|-Ovo su oËeve stvari.
{56694}{56768}Proölo je samo nekoliko sati|od kako sam preveo
{56768}{56868}i izgovorio naglas prve pasuse|za prizivanje demona
{56868}{57035}iz"Knjige mrtvih".|Sluöajte, ovo je glas mog oca.
{57047}{57221}Sada je moja ûena posednuta|kandarijanskim demonom.
{57221}{57326}Neka mi bog oprosti za ovo|öto sam oslobodio na Zemlji.
{57340}{57513}SinoÊ je Henrijeta| pokuöala da me ubije.
{57513}{57707}Sada je 1. Oktobar,16:33.|Henrijeta je mrtva.
{57729}{57806}Nisam mogao|da raskomadam njen leö,
{57806}{57966}pa sam je odvukao niz| stepenice i sahranio je...
{57966}{58067}Sahranio sam je u podrumu.|Neka mi bog pomogne,
{58067}{58177}sahranio sam je u zemljanom|podu podruma.
{58366}{58425}äta je to bilo?|-Neko je dole s njim.
{58425}{58517}NemoguÊe!|-Beûimo odavde!
{58517}{58759}Neko je u mom podrumu!|Neko sa sveûom duöom!
{58759}{58837}Pustite me napolje!!!|Neöto je ovde!!!
{58837}{58897}Oslobodi ga!|-To je trik! Znam!
{58897}{58922}Pusti ga!
{58922}{59162}Otvorite!!!|Dodji!
{59162}{59256}UpomoÊ!!!|Dodji slatkoj Henrijeti!
{59325}{59373}Poûuri!|-Trudim se!
{59373}{59490}UpomoÊ!Poûurite!
{59490}{59616}ProgutaÊu ti duöu!
{61640}{61703}Neöto je napolju.
{61722}{61924}Veötica u podrumu je|samo deo toga.
{61924}{62118}To ûivi u ovoj öumi, u mraku.
{62146}{62323}Neöto öto se vratilo iz mrtvih.
{62364}{62458}Molim te, hajdemo odavde!|Ne mogu viöe!-OtiÊi Êemo.
{62458}{62498}Niko ne sme da izlazi,|ne pre svanuÊa!
{62498}{62627}Sluöaj ti mene!
{63218}{63327}SeÊaö li se te pesme, Eni?
{63327}{63394}Pevala sam ti je kada si| bila mala. - Majko?
{63394}{63486}OtkljuËaj ove lance, brzo!
{63674}{63798}Ne!|-Rodjena si 2. Septembra 1962.
{63798}{63904}Toga se dobro seÊam,|zato öto je padao sneg.
{63904}{64038}Cudno, sneg u septembru.
{64055}{64180}Ta stvar u podrumu|nije moja majka!
{64342}{64500}Mi smo oni koji smo bili|i biÊemo opet!
{64500}{64668}Mi smo duhovi knjige!Mi hoÊemo|ono öto je vaöe!éivot!
{64668}{64849}Mrtvi do zore!
{65210}{65293}Oslobodi me!
{65533}{65674}Kuda ideö?!|Pomozi nam kukavice!
{65703}{65778}Oslobodi me!
{66198}{66298}Mi ûivimo!Mi ûivimo!
{67212}{67303}»udno.|äta?
{67317}{67498}Put kojim smo doöli|viöe ne postoji.
{67498}{67658}Kao da su ga veötice progutale.
{69367}{69428}äta je to bilo?
{69428}{69541}Moûda neöto pokuöava| da se probije u naö svet.
{70234}{70280}Tamo je!
{70329}{70531}UÊi Êemo svi zajedno.|Dodjavola, ne!Ti si radoznao.
{71063}{71151}Idem sa tobom.
{72404}{72557}Sranje, rekao sam ti|da ovde nema niËega!
{73132}{73202}Presveta majko boûija!
{73218}{73269}OËe!
{73269}{73456}Eni, ovde je mraËni duh koji|hoÊe da vas uniöti.
{73456}{73614}Vaö spas leûi tamo...
{73725}{73827}U stranicama knjige!
{73827}{73954}Izgovorite pasuse,|oterajte zlo.Spasite moju duöu!!!
{74064}{74157}I sopstvene ûivote!!!
{74389}{74496}Dûejk, prejako mi steûeö ruku.
{74496}{74618}Ne drûim te za ruku.
{75063}{75178}Hej, gde je Bobi Dûo?
{77830}{77923}Gde je ona?
{78190}{78258}Moramo da izadjemo|i pronadjemo je.
{78258}{78378}Ako je izaöla u öumu,|moûeö da je zaboraviö.
{78517}{78562}äta nije u redu?
{78562}{78724}Osetio sam se kao da mi je neko|preöao preko groba.
{78724}{78823}Kakva je to slika?äta je to?
{78845}{78985}1300. godine, zvali su tog Ëoveka|"heroj sa neba".
{78985}{79100}ProreËeno je|da Êe on uniötiti zlo.
{79100}{79299}Nije dobro obavio posao.|Jesi li pronaöla?-Evo ga.
{79299}{79362}Dva pasusa.
{79485}{79705}Prvi pasus tera mraËnog|duha da se otelotvori.
{79727}{79782}äta Êe nam to?
{79782}{79962}Drugi pasus otvara vrtlog|u vremenu i prostoru
{79962}{80094}i fiziËki oblik mraËnog duha|moûe se oterati u vrtlog.
{80094}{80179}To je najbolji prevod koji mogu...
{80238}{80354}Tako je, sada sam ja|vodja predstave.
{80354}{80432}Idemo u öumu|da potraûimo Bobi Dûo.
{80432}{80551}Kada je pronadjemo,|beûimo odavde.-Ne, idiote!
{80551}{80688}Sve Êe nas pobiti!|Do sada je sigurno mrtva.
{80688}{80886}Zar ne shvataö? Sa ovim|stranicama, bar imamo neku öansu!
{80937}{81075}To su hokus-pokus sranja!|Ove stranice niöta ne znaËe!
{81238}{81418}Sada nemate izbora. MiËite se!
{81626}{81722}Lud si!|-Rekao sam ti da kreneö!
{81722}{81830}Glupi Ëobane!
{81924}{82010}RazneÊu ti glavu!
{83107}{83268}Nema puta.Kuda Êemo sada?!
{83313}{83405}Bobi Dûo!!!
{83799}{83882}Zbog tebe Êemo svi izginuti!-Umukni!
{83882}{83961}Ostavi ga!
{83993}{84072}Bobi Dûoooo!!!
{84269}{84371}Gde si, devojko?
{85085}{85174}Pridruûi nam se!
{85437}{85512}Eni!!!
{89206}{89261}Izvini!
{89261}{89384}Prenesi me u drugu sobu, uzmi|sekiru i ubij ga kada se vrati.
{89384}{89469}Prvo izvadi ovo iz mene!
{89769}{89854}Ne mogu da diöem.
{89854}{89966}Pomozi...|Trudim se!
{90174}{90266}∆uti!∆uti!
{90908}{90999}Proveri prozore.
{90999}{91082}Proveri prozore, verovatno Êe...
{94294}{94446}Sluöaj me!Sada sam dobro!|Ona stvar je otiöla!
{94742}{94858}Dodjavola!Rekao sam ti da sam|dobro! Sluöaö li me?
{94858}{95010}»ujeö li öta govorim?|Dobro sam!
{95089}{95278}Dobro sam.|U redu je. Moûda jesi.
{95278}{95386}Ali, koliko Êeö dugo biti?
{95427}{95539}Ako hoÊemo da pobedimo ovu| stvar, potrebne su nam stranice.
{95578}{95728}Onda sidjimo u podrum|i raskomadajmo veöticu!
{96856}{96918}Sjajno!
{97957}{98042}Stranice su negde dole.
{101827}{101895}Stranice, brzo!
{105995}{106116}Hej, progutaÊu ti duöu!
{106116}{106191}Progutaj ovo.
{108342}{108530}Zavröila sam samo prvi pasus,|da se zlo otelotvori!
{108641}{108726}Nisi zavröila?
{108726}{108788}Ostao je drugi pasus, onaj...
{108894}{109070}Onaj koji Êe oterati zlo!|-Izgovori ga! Odmah!
{109314}{109444}Ne gledaj ga! Zavröi pasus!|Oteraj ga!!!
{109938}{110006}Ne!!!
{111234}{111362}Pobedili smo,pobedili smo!|Pobeda je naöa!
{112188}{112266}Uspela si, mala!
{112266}{112327}U ime boga!
{113096}{113163}Zaboga, kako se zaustavlja?!
{114810}{114888}Ubijte zver!
{115054}{115117}Beûimo!|Beûimo u zamak!
{115994}{116134}Pozdrav onom koji je doöao|sa neba da nas oslobodi uûasa!
{116398}{116557}Neeeeee!!!!!!
{116582}{118082}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
