{1}{1}25.000
{26}{176}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{913}{939}Jesam te!
{1025}{1063}Budite dobri.
{2013}{2047}Tko su ovi?
{2080}{2124}Naoruûani su!
{2160}{2208}äto hoÊe, gice Li?
{2449}{2500}- äto ovo znaËi?|- Idemo!
{2550}{2585}Pusti me!
{2631}{2728}- Strpajte ih u autobus!|- Djeco, sluöajte!
{2757}{2817}Ovamo! Za mnom!
{3106}{3159}POR. KIT LI
{3200}{3244}Sve Êe biti u redu.
{3247}{3299}- Gice Li!|- UpomoÊ!
{3459}{3525}- NaredniËe, doite!|- U autobusu su djeca!
{3700}{3759}- PoruËniËe, spremni smo.|- Idemo.
{3780}{3842}Vaöa ûena je u autobusu.|éao mi je.
{3847}{3897}Ne treba ti joö|biti ûao, vojniËe.
{3964}{4035}SjeÊaö se teroristiËkog|napada u gradu lani?
{4078}{4155}Bomba ispod autobusa naËinjena je|od istog eksploziva.
{4159}{4232}- To su isti tipovi.|- Koji su njihovi zahtjevi?
{4234}{4291}Djeca su iz bogatih obitelji...
{4295}{4379}...i ovi teroristi traûe 20 milijuna.
{4381}{4451}GradonaËelnik je voljan|isplatiti puni iznos.
{4456}{4497}PoruËniËe, vaöa pancirka.
{4509}{4545}Zaboravi. Idemo.
{4674}{4703}PoruËniËe?
{4766}{4788}Dolje!
{4906}{4965}Boûe moj!|Nije imao izgleda!
{5012}{5053}äto mogu uËiniti, Kit?
{5065}{5131}Smiruj djecu.|IzvuÊi Êemo vas.
{5152}{5183}Imamo 10 minuta.
{5198}{5247}Uskladite satove. Sad.
{5363}{5440}- UobiËajena postavka.|- PresjeÊi Êu uzemljenje.
{5512}{5568}äto mislite? I drugu?
{5571}{5635}Doima se lagano.|Dodaj mi naoËale.
{5783}{5821}Pogledaj.
{5842}{5882}Ako presjeËemo ovu ûicu...
{5886}{5972}...öto Êe nam se svima dogoditi?
{5976}{6047}- Pretvorit Êemo se u kaöu.|- Pogodio si.
{6186}{6237}Da vidimo öto je unutra.
{6294}{6326}Obiljeûene su bojom.
{6348}{6427}äto je tim luacima sa ûicama|obiljeûenim bojom?
{6434}{6510}PresijeËemo li jednu, ûivi smo.|Drugu, mrtvi smo.
{6514}{6594}Ja bih plavu. äto ti misliö?
{6596}{6653}Mislim da Êu se|usrati u gaÊe.
{6747}{6808}Imamo bombaöa na telefonu!
{6841}{6955}- VojniËe! Ne daj da umrem.|- Vjeruj mi. Bit Êe sve u redu.
{6966}{7033}- Kit, nemoj dugo.|- NeÊu. ObeÊavam.
{7095}{7131}PoruËnik Li ovdje.
{7133}{7242}- Zdravo. Ja sam Doktor.|- Doktor?
{7244}{7379}Sad sam bogat jer je gradonaËelnik|isplatio ucjenu.
{7426}{7511}Ako veÊ imate novac, recite|kako da deaktiviramo bombu.
{7515}{7582}- Reci "molim".|- Poûurite se, poruËniËe.
{7590}{7630}Molim vas, recite mi.
{7682}{7774}Vrlo dobro. Pristani|na sve zahtjeve terorista.
{7779}{7866}Pregovor prema priruËniku.|Ali nemoj mi udvoravati.
{7871}{7941}- Ja poötujem samo hrabrost.|- Vrijeme prolazi!
{7982}{8056}Ostavit Êu na tebi|deaktiviranje bombe.
{8065}{8141}Ali mogao bih nas sve ubiti.
{8174}{8255}- Tko riskira profitira.|- Doktore? Halo?
{8630}{8663}Presijeci crvenu!
{8865}{8903}Bomba je deaktivirana.
{8987}{9093}- »ujeö li? Sve Êe biti dobro.|- Hvala, vojniËe!
{9267}{9299}Dopustite.
{9327}{9411}- »ekala sam autobus, ali...|- Taksi! Autobus kasni.
{9422}{9463}Ne!
{11055}{11128}Dvije godine poslije
{11254}{11345}Klub oboûavatelja Frankieja Lonea
{11405}{11485}Stigli smo. Vrlo dobro.|Pazite gdje stajete.
{11568}{11669}Kaûem ti, ovo je posljednji put|da to radim.
{11706}{11791}Velika stvar. Frankie Lone|izvodi opasnu scenu.
{11794}{11884}To je samo promocija za njegov film.|HoÊu pravu priËu.
{11990}{12061}Pazi mu glavu.|Frankie, probudi se.
{12075}{12145}Hajde, Frankie.|Popio je Ëitavu bocu.
{12166}{12241}Bit Êe spremna. ObeÊavam. Bog.
{12295}{12351}- äto gledaö?|- Niöta.
{12368}{12412}Kako to misliö, niöta?
{12514}{12545}Uzmi kaskadera.
{12549}{12645}Frankie nikad ne koristi|kaskadera. Sam izvodi.
{12650}{12701}Sam i pije.
{12705}{12799}Zdravo. Snimamo li veÊ?
{12929}{12995}Spreman sam za svoj krupni|plan, g. Spielberg.
{13002}{13099}- Charlie je.|- O, Charlie.
{13117}{13181}- U redu je. Da.|- Ti nenadareni...
{13336}{13448}Snimamo li veÊ ljubavnu scenu?|Divno miriöeö.
{13452}{13532}Zaboravi. Uzimamo kaskadera.|Hej, Kit!
{13546}{13598}Kit, trebamo te!
{13632}{13672}Silazi.
{13885}{13943}U redu, drûite ga.
{14054}{14106}Frankie, volimo te!
{14150}{14209}Previöe sam pijan|za opasnu scenu.
{14213}{14297}- Moraö.|- Pusti mene.
{14305}{14345}Kaskader Êe mi|uniötiti ugled.
{14348}{14412}- Radije bi se razlio po ulici?|- Ima pravo.
{14507}{14576}- Dolazi.|- Zumiraj na Frankieja.
{14580}{14618}- Nemoj ga izgubiti.|- Jasno.
{14661}{14723}Svidjet Êe ti se.|Bit Êe veliko!
{14727}{14786}Frankie Êe skoËiti.
{14827}{14894}- Hvala öto ste doöli. Silazim.|- Samo öto nije spreman!
{14942}{14970}Vratit Êu se.
{15069}{15106}U redu! Idemo!
{15703}{15767}Dajmo mu mjesta, ljudi.|Odmaknite se.
{15887}{15993}- Opet si dublirao za Frankieja?|- Nije se osjeÊao dobro.
{16002}{16087}Nemoj ga ötititi.|Moj sin je prokleta pijanica.
{16107}{16227}Razmaûeno deriöte. A bio je|majstor borilaËkih vjeötina.
{16276}{16335}Ne brinite se.|Opet Êe biti majstor.
{16563}{16593}Vrati to.
{16709}{16753}Ne izgleda kao Frankie.
{16795}{16833}Teöko je reÊi.
{16869}{16953}- Misliö da je kaskader?|- Pogledaj bolje.
{17002}{17029}Evo!
{17066}{17130}To se Frankie ugurava|u gomilu!
{17191}{17250}Znaö öto to znaËi?
{17260}{17358}Ne izvodi sam opasne scene.|Prevarant je!
{17367}{17447}Napuöimo priËu. Moûemo je|pustiti iduÊi mjesec.
{17452}{17529}- Moûda Ëak i u dva dijela.|- Sjajno.
{17533}{17632}U meuvremenu Êu ga pratiti,|da vidim öto joö mogu otkriti.
{17669}{17731}Jesi li Ëuo?|Kako sjajna zamisao!
{17737}{17785}Nikad neÊeö potuÊi|moju gledanost.
{17815}{17901}Helen! Molim te, ponaöajmo se|kao profesionalci.
{18115}{18158}Da se niste usudile.
{18232}{18297}Tko je to uËinio?|Sad si u neprilici.
{18312}{18372}Kit, pridruûi nam se.
{18385}{18442}Ne, hvala.|Na duûnosti sam.
{18457}{18500}Zaöto si tako ozbiljan?
{18503}{18559}BuduÊi da si moj Ëuvar,|nareujem ti...
{18562}{18681}- ...da me ötitiö od ovih ûivotinja.|- One trebaju zaötitu.
{18814}{18873}- Vidiö li Frankieja?|- Ovo je sjajno.
{18878}{18911}- Najbolji si!|- Hvala.
{18913}{18952}Ne prestaj snimati.
{19084}{19119}Hvala.
{19215}{19289}Ne ûelimo novinare ovdje.|Daj mi tu traku.
{19356}{19437}- Jeste li Ëuli za slobodu tiska?|- Da, baö.
{19439}{19501}Gdje mislite da ste?|U Americi?
{19509}{19545}Vrlo pametno.
{19588}{19658}- Ali ovo je moje.|- NeÊu opet pitati.
{19663}{19711}äto Êeö uËiniti,|grubijane?
{19945}{19980}Hvala lijepa.
{20002}{20071}äto umiöljaö, tko si?
{20075}{20163}- Radije brzo trËite.|- Imaö li pojma tko sam ja?
{20204}{20243}äto je time mislio?
{20391}{20411}Brûe!
{20457}{20483}Poûuri se!
{20507}{20549}MiËi tu debelu guzicu.
{20657}{20785}- Kaûem vam, ovo je ûivot.|- »ekaj samo subotu.
{20792}{20881}Hotel Grandeur.|Velika stvar za bogate i slavne.
{20885}{20946}Dogaaj sezone.
{20962}{21009}O Ëemu je rijeË?
{21036}{21092}Izloûba dragulja...
{21097}{21189}...koji su nekad pripadali|krvoûednom ruskom caru.
{21194}{21268}Neprocjenjivi su.
{21275}{21356}Osiguranje Êe biti jaËe|nego u Fort Knoxu.
{21390}{21423}HoÊe li biti komada?
{21429}{21544}NeÊeö vjerovati. »uo sam|da Êe doÊi i porno zvijezda.
{21562}{21625}- Prodano.|- Imam tri pozivnice.
{21629}{21690}Ti, ja i joö netko.
{21720}{21793}Kit bi trebao ostati u predvorju.|Povest Êu tatu.
{21839}{21886}- Frankie, hajde.|- U redu, duöo.
{22014}{22087}Tko god da je ispraznio|bazen, otpuöten je!
{22111}{22172}Neka netko pomogne Frankieju.
{22729}{22794}{y:i}Izloûba u hotelu Grandeur.
{22798}{22878}{y:i}Evo i kustosa zbirke, g. Kuryakina.
{22883}{22975}Dr. David Wang|38 g., MUäKARAC
{22989}{23038}{y:i}Moûete li nam|{y:i}joö öto reÊi?
{23042}{23086}SIGURNOSNA PROVJERA|POTVR–ENA
{23090}{23125}U redu.
{23240}{23287}Ovaj nije tako opasan.
{23305}{23353}äaliö se?|To je Frankie.
{23386}{23487}Briga me. Jednoga Êu ga dana|izazvati na borbu.
{23491}{23583}- Vidjet Êemo tko je bolji.|- Nitko nije bolji od njega.
{23601}{23666}Ja sam najbolji!|»ujeö? Reci!
{23670}{23733}U redu! Smiri se!|Ti si najbolji.
{23825}{23870}U redu, ljudi, sluöajte.
{23888}{23939}Taj posao u subotu...
{23953}{24038}...bit Êe najveÊa kraa koju smo|ikad pokuöali sprovesti.
{24045}{24135}Uspijemo li, bogatstvo Êe biti...
{24148}{24208}...veÊe od vaöih|najluih snova.
{24270}{24302}Tiöina!
{24306}{24388}Vrlo je vaûno da ne doe|do pogreöaka.
{24422}{24507}Ova operacija mora biti|izvedena kiruröki precizno.
{24513}{24622}Od danas neÊe biti|tolerancije za pogreöke.
{24628}{24752}Kao primjer: loöa izvedba|proölotjedne pljaËke banke...
{24762}{24854}...kad je oËita pogreöka|skoro ukljuËila alarm.
{24870}{24977}Znaö o Ëemu govorim,|zar ne, Lee Chin?
{25021}{25081}- Nisam ja.|- Ne brini se. Znam da je bio Wang.
{25194}{25241}Ne miËite se|ili Êu je ubiti!
{25244}{25368}Hajde. Voljna je umrijeti za mene|kao i ostali. Pokaûi mu!
{25656}{25757}- Bolno? - Niöta öto dobar doktor|ne bi mogao srediti.
{26147}{26205}ZATVORENO
{26223}{26286}éao mi je.|Zatvoreni smo do sutra.
{26294}{26374}- Policajac Chow Kam.|- Kako vam mogu pomoÊi?
{26746}{26834}äto sam ja, tvoj zubar?|Daj, Joyce, budi ozbiljna.
{26845}{26890}Oprostite, gospodine.
{26894}{27008}Ova izloûba je veoma vaûna.|éelim vas u najboljem izdanju.
{27012}{27057}Bit Êu, obeÊavam.
{27062}{27156}Nakon svega, ûelite ostaviti dojam|na Frankieja Longa, ne?
{27160}{27193}Izvrsno.
{27200}{27270}I upamtite, Sammo Hung|je najveÊi.
{27274}{27323}I to je sve.
{27339}{27431}- Je li on lud?|- Ja sam s vama, ljudi.
{27435}{27498}- Frankie je najbolji.|- Imaö pravo.
{27502}{27597}- Znaö da nema kaskadera?|- Voljela bih ga dohvatiti.
{27607}{27695}VeËer Êe biti zanimljiva.|To je sigurno.
{27699}{27782}- Jedva Ëekam da doem na posao.|- äto je?
{27799}{27917}- Istegnula sam neöto na skvoöu.|- Ja sam jednom istegnula rame.
{27921}{27992}- Boljelo me tjedan dana.|- Loöe.
{27997}{28052}Ovuda.
{28093}{28163}Joyce, neki te policajac treba.
{28190}{28271}- äto je?|- Moûemo li razgovarati nasamo?
{28466}{28533}äto radiö? Rekla sam ti|da je s nama gotovo.
{28538}{28597}Daj. Razgovarajmo o tome.
{28599}{28663}Nedostajeö mi, duöo.|Proölo je dosta vremena.
{28668}{28711}I ti meni nedostajeö.
{28713}{28808}Zaöto onda ovo radimo?|Pomirimo se.
{28829}{28902}Nije to tako jednostavno, Kam.
{28910}{28998}Svake veËeri na vijestima govore|o ubijenim policajcima...
{29003}{29083}...nadjaËanim od banda|i uliËnih kriminalaca.
{29099}{29160}Svaki put kada Ëujem|tvoj dojavljivaË...
{29162}{29224}...pomislim da Êeö|zavröiti mrtav.
{29227}{29307}Zar ne moûeö raditi siguran posao,|recimo biti raËunovoa?
{29309}{29368}PreuveliËavaö stvari.
{29371}{29456}Da, uvijek ja.|To sam veÊ prije Ëula.
{29464}{29514}Molim te. Samo...
{29529}{29600}- Joyce, trebaö prijevoz?|- Nego öto.
{29631}{29688}»ekaj, Joyce!
{29823}{29900}Joyce, ûeliö da molim?
{29907}{29966}To ti je najbolja|zamisao veËeras.
{30001}{30041}HoÊeö li usporiti?
{30060}{30108}Ne mogu vjerovati!
{30137}{30179}To je David.
{30209}{30314}- Fai-Fai, lijepo izgledaö.|- Budalo. Poprskao si me.
{30341}{30409}- Poznajeö ovu osobu?|- Ne.
{30464}{30533}- Moûemo li sad krenuti?|- Stvarno.
{30571}{30600}»ekaj.
{30674}{30751}Ja Êu te povesti.|Moûemo razgovarati.
{30921}{30964}To ti je bio deËko?
{30985}{31049}Imali su ljubavniËku svau.
{31059}{31133}Idemo u vruÊu kadu.|HoÊeö li nam se pridruûiti?
{31137}{31230}Ne, hvala. Moûda drugi put.|Moûete me ostaviti ovdje.
{31364}{31424}Hvala. Bog.
{31495}{31575}VruÊa kada? To je bilo jadno.
{31618}{31683}Kod tebe je upalilo, zar ne?
{31692}{31798}»ujem da Êe Frankie Lone|sutra doÊi na izloûbu.
{31814}{31889}Zbilja? Frankie, majstor|borilaËkih vjeötina?
{31895}{31973}Njegove filmske borbe|su na zavidnoj razini.
{31983}{32043}ShvaÊaö li da Êe dovesti|tjelesne Ëuvare?
{32196}{32281}Oni mogu biti problem.|Daj to Kongu.
{32418}{32457}Snimimo ovu probu.
{32619}{32696}Nije dobro. Brûe! Idemo!
{32722}{32756}Moûete vi i bolje.
{32819}{32897}Udari me jaËe ili si otpuöten!
{32945}{32987}Odmaknite se! Brûe!
{32992}{33035}Sad svi na pod.
{33069}{33113}Rez! Idemo dalje.
{33118}{33186}- U redu, okupite se.|- Bilo je izvrsno.
{33195}{33246}Ti, vjeûbaj te udarce.
{33264}{33350}Udaraö kao mlakonja.|Svi ste sramotni.
{33355}{33423}Dajmo im pauzu. 10 minuta?
{33431}{33492}- Zasluûili su samo pet.|- Idemo.
{33576}{33646}- Scena od proölog tjedna.|- Dobro napreduje.
{33650}{33714}Zbilja se ispucavaö na njima.
{33727}{33827}Nisam siguran za ovo.|Zvuk mi nije dobar. Ponovno.
{34161}{34221}Pusti me! Gade!
{34432}{34553}Dobro je. Najbolji "dubbing"|od "Shogunovog knjigovoe."
{34580}{34611}Umri!
{34622}{34714}Ovo je amaterska produkcija?|Ja sam Frankie Lone!
{34729}{34856}Budite od koristi! Idem u Ameriku|snimati prave filmove!
{34862}{34929}- Smiri se.|- Dosta mi je. Odoh odavde.
{35265}{35328}Mrzim ljude pored sebe|dok piöam.
{36116}{36176}- äto je?|- Samo radim svoj posao.
{36203}{36270}äto bi se ovdje moglo dogoditi?
{36723}{36785}- Ispala vam je djetetova igraËka.|- Ne miËi se, Frankie.
{36844}{36897}- Ni makac.|- äto je?
{36922}{36998}- Mina.|- Sigurno se öaliö.
{37004}{37109}Nije öala. Pomakneö li se,|svi smo gotovi.
{37120}{37156}UËini neöto.
{37160}{37212}- Dajte mi palicu.|- »uli ste ga!
{37241}{37322}Kad nabrojim do tri, makni nogu.
{37370}{37404}Lud je.
{37448}{37481}»ekaj!
{37511}{37563}Moram se pripremiti.
{37596}{37668}Hajde, tatice, moûeö ti to.
{37746}{37790}- U redu.|- Jedan...
{37854}{37905}...dva, tri!
{38141}{38176}Provjeri Frankieja!
{39232}{39263}Vidi, to je Frankie.
{39326}{39398}Kit, tamo je ona|zgodna novinarka.
{39432}{39462}»uvaj se.
{39514}{39585}- Kako si?|- Lijepo je vidjeti vas.
{39611}{39661}- Poûuri se.|- Dobro izgledate.
{39907}{39962}- Vidimo se unutra.|- Dobro.
{40051}{40091}Baterija je opet prazna.
{40371}{40403}äto je?
{40439}{40547}Zakasniö li, imat Êeö viöe posla|s osiguranjem.
{40586}{40634}Morat Êu riskirati.
{40689}{40731}Nakon svega, upamti:
{40737}{40796}Tko riskira profitira.
{40812}{40864}{y:i}Tko riskira profitira.
{41468}{41508}Tko umiöljaö da si?
{41525}{41566}Ne moûeö unutra!
{41599}{41653}- Dobra veËer.|- Ovuda, molim.
{41659}{41721}Dragulji su osigurani.
{41729}{41809}Slomljeni kovËeg ukljuËit Êe|alarme u policiji.
{41886}{41917}Hajde.
{41977}{42029}- Zdravo joö jednom.|- Zdravo.
{42063}{42156}»ini se da je to komunikator|za osobne poruke.
{42185}{42259}Imaö pravo. Osoban je.
{42273}{42371}Kaûem vam, spremaju se nevolje.|Taj tip je terorist.
{42375}{42432}Terorist? Kako izgleda?
{42438}{42504}Nisam mu vidio lice.|Prepoznao sam mu glas.
{42511}{42612}Znam da je ono s kadom|moûda bilo grubo...
{42633}{42692}...ali, zar te ne privlaËim?
{42696}{42779}Naravno. Kao da sam upoznala|peÊinskog Ëovjeka. Oprosti.
{42875}{42913}Telef on mu je iskljuËen.
{42924}{43001}Da si Frankiejev Ëuvar,|mogao bi doÊi do njega.
{43005}{43041}Istina je.
{43045}{43101}A ta priËa|o teroristu u hotelu?
{43105}{43196}- Daj prestani.|- U redu. Vratit Êu se.
{43245}{43315}- Jesam.|- Hvala. Idemo.
{43320}{43363}Potpisat Êu kasnije.
{43369}{43458}- Sjajno je kad je zvijezda tako fina.|- Nije to niöta.
{43483}{43560}Dobro je povremeno se|druûiti s obiËnim ljudima.
{43682}{43793}»uo sam da Êe ovdje biti|porno zvijezda i...
{43807}{43884}Porno zvijezda?|To misliö da sam ja?
{43950}{43989}Nadao sam se.
{44001}{44036}Ovuda, gospodine.
{44042}{44150}Tamo Frankie opipava|oboûavateljicu. Sjajno.
{44264}{44297}»ekaj malo.
{44312}{44382}Moramo ovo provuÊi|kroz osiguranje. Evo.
{44454}{44489}Proite ovuda, molim.
{44526}{44566}Gospoo, jeste li dobro?
{44580}{44649}- Jesi li dobro, duöo?|- Savröeno.
{44653}{44712}Evo, podigao sam ti torbu.
{44732}{44797}- Kakav gospodin.|- Trudim se.
{44839}{44897}- Uûivaö, tata?|- Nego öto.
{45603}{45637}Vidimo se, tata.
{45942}{45990}- äto je?|- Dostava.
{45994}{46037}- Za koga?|- Pogodi.
{46708}{46754}Divni su.
{46766}{46828}Ni upola divni kao ti.
{46842}{46872}Baö.
{46951}{47052}Zaöto joj se upucavaö?|Sa mnom je.
{47071}{47144}HoÊeö me naljutiti? Gubi se.
{47162}{47203}Moja pogreöka.
{47230}{47284}Imaö posla s|krivim Ëovjekom.
{47823}{47876}Mogu li vidjeti|vaöe pozivnice?
{48616}{48664}ZATVORENO
{49036}{49121}- UpomoÊ. Pomozite mi.|- Gubi se.
{49140}{49217}- Makni se od mene.|- Nemojte otiÊi.
{49221}{49258}Molim vas, pomozite.
{49323}{49405}Traûio sam malo akcije, ali|nisam ovo imao na umu.
{49967}{50016}Hajde! Vas dvojica, za mnom.
{50285}{50343}- Izgubili smo ga.|- Pogledat Êu ovdje.
{50347}{50395}- Provjeri dizalo.|- Dobro.
{50728}{50751}Tiho.
{50821}{50861}Teroristi me love.
{50888}{50939}- äaliö se.|- äto?
{50997}{51074}Znam da se bojiö, ali|ne brini se sad o tom.
{51090}{51124}Ja sam tu.
{51148}{51182}ätitit Êu te.
{51420}{51481}Ne paniËari.|Potraûit Êu izlaz.
{51643}{51702}Mrtav je! Boûe moj!
{51727}{51823}Zarobljen sam u zgradi|koju su preuzeli teroristi.
{51834}{51910}- Gdje sam to veÊ Ëuo?|- äto Êemo uËiniti?
{51952}{52023}Ti ostani tu. Ja Êu se|za sve pobrinuti.
{52050}{52073}Da.
{52164}{52202}Ali ako se izvuËemo...?
{52217}{52261}UËinit Êu sve öto ûeliö.
{52270}{52333}- Sve?|- ObeÊavam.
{52351}{52399}- »uvaj se.|- HoÊu.
{52507}{52574}Dobro sam. Samo se|moram pripremiti.
{52589}{52669}Ne brini se, duöo.|Tatica Êe se vratiti.
{52978}{53032}UpomoÊ, Frankie. Pomozi mi!
{53136}{53194}UËini neöto. Ubit Êe me.
{53198}{53253}- Poûuri se.|- Hajde, superjunaËe.
{53378}{53433}Brojim do tri. Jedan!
{53530}{53555}Dva!
{53629}{53659}Tri!
{53743}{53781}Superjunak.
{53801}{53842}Moja straûnjica.
{53865}{53924}Nije li vaö posao|da to provjerite?
{53928}{54003}Ne moûemo poslati aute u hotel|samo zbog vaöe rijeËi.
{54007}{54081}- O Ëemu je rijeË?|- Razgovaraj s njim.
{54085}{54170}- Bombaö po imenu Doktor je tamo.|- Doktor?
{54174}{54244}Onaj koji je raznio ökolski|autobus u Nanchangu?
{54258}{54355}- Izgubio sam ûenu u toj eksploziji.|- éao mi je.
{54375}{54417}Pretraûite hotel.
{54454}{54576}- VeËeras je izloûba dragulja?|- Sve je puno osiguranja.
{54585}{54663}Ako ne radiö,|zaöto ne proeö tamo?
{54699}{54725}Provjerimo to.
{55223}{55245}»ekaj.
{55267}{55296}Glave gore, ljudi.
{55635}{55671}Ostani blizu mene.
{55701}{55742}Znam se brinuti za sebe.
{55827}{55900}Nemam ni svoj uöljivi telefon|s praznom baterijom.
{55914}{55950}äutite!
{55955}{56033}- Ovo neÊe dugo potrajati.|- Rekao sam, tiho!
{56040}{56138}Ovdje smo samo zbog dragulja.|Radite ono öto vam se kaûe.
{56143}{56208}Nemojte stvarati probleme.
{56212}{56274}I pustit Êemo vas da uûivate|u siru i kavijaru.
{56282}{56339}Jasno?
{56366}{56407}Ovo je vijest.
{56460}{56546}Je li g. Wells iz Kato|osiguranja ovdje?
{56681}{56764}- Ja sam.|- Dajte nam sigurnosnu öifru.
{56776}{56889}Ne znam je zbog sigurnosnih|razloga, razumijete.
{56926}{56981}Helen, zumiraj. Zumiraj!
{56988}{57033}Vjerujte mi, ne znam öifru.
{57141}{57172}Jesi li vidio?
{57256}{57336}Imaö 45 minuta|da razbijeö öifru. Jasno?
{57341}{57416}Da, Zeko. Nema zime.|To mi je posao.
{57735}{57876}Zovu me Kong, osmo Ëudo svijeta.|Razbit Êu te.
{57882}{57967}Dobro izgledaö. Jesi li|razmiöljao o glumi?
{58019}{58044}Doi!
{58073}{58134}- Nisi li ti majstor borilaËkih|vjeötina? - äto?
{58138}{58180}Hajde, bori se!
{58200}{58267}Ne lice!|Sutra imam snimanje!
{58340}{58368}Hvala.
{58622}{58678}Imamo auto vani.
{58682}{58733}{y:i}Vidi öto hoÊe|{y:i}i rijeöi ih se.
{58782}{58851}- Pusti mene da govorim.|- Zaöto?
{58855}{58944}- Ja sam policajac.|- Nastojat Êu to upamtiti.
{58947}{59010}- Odmakni se.|- Poslije tebe, Prljavi Harry.
{59013}{59086}Oprostite, gospodine. Mogu li|vidjeti vaöe pozivnice?
{59098}{59178}Policija. Imamo dojavu|da bi moglo biti problema.
{59192}{59257}- Problema?|- Gdje je drugi Ëovjek?
{59266}{59318}U Ëemu je problem?
{59323}{59411}- Ovaj Ëovjek nije bio prije.|- Ja sam druga smjena.
{59421}{59492}- Idemo gore.|- U redu. Ovuda.
{60245}{60272}Zovi policiju!
{61283}{61306}äto Ëekaö?
{61416}{61449}IduÊi put probaj s vratima.
{61872}{61897}Sranje!
{61975}{62005}UËini neöto!
{62406}{62432}Idemo gore.
{62468}{62526}- Hvala na voûnji.|- Nema problema.
{62538}{62612}- Nemilosrdni su.|- Vjeruj mi, nije to niöta.
{62622}{62653}äto sada?
{62657}{62722}- Iznenadit Êemo ih.|- Iznenaditi?
{62851}{62914}äto? Dizalo? äaliö se!
{63352}{63382}Uzmi ovo.
{63402}{63499}Moja djevojka Joyce mi je to dala|da si öaljemo poruke.
{63531}{63610}Traûim samo da joj to|daö za sluËaj...
{63623}{63684}...da se meni neöto dogodi.
{63750}{63814}Ali iznenadni Êe napad|upaliti, zar ne?
{64074}{64113}Smiri se, u redu?
{64195}{64231}- Sine.|- Dolje!
{64235}{64297}U redu je, tata.|NeÊe me ozlijediti.
{64304}{64371}Sjedni, starËe,|ili si mrtav! »ujeö li?
{65166}{65194}Izlazi! SkoËi!
{65728}{65750}Kam, pazi!
{65779}{65803}Hajde, idemo!
{66109}{66136}Svi na pod.
{66160}{66182}Tata.
{66410}{66445}Ima ih joö.
{66744}{66833}Prestanite pucati ili Êemo|ubiti ovoga, kunem se!
{66891}{66933}Ne ûelite ga mrtvoga.
{66936}{67018}On je jedini koji moûe|razbiti öifru. Natrag.
{67076}{67137}Taj stari ima muda. Snimaj.
{67198}{67235}Stani!
{67341}{67398}Ostanite mirni.
{67446}{67506}Bacite oruûje!
{67524}{67558}UËinite tako!
{67591}{67628}Bacite ga.
{67900}{67969}- Drûat Êu obojicu na oku.|- U redu.
{68095}{68194}- Joyce, jesi li dobro?|- Misliö da ûelim glumiti Ramba?
{68396}{68488}Ja sam policajac. Policija|je stigla, ostanite mirni.
{68495}{68569}Recite nam kako ste|porazili teroriste.
{68577}{68628}- Makni se.|- Snimaj Frankieja.
{68712}{68769}Mir. To nije|moja dobra strana.
{68775}{68789}Hajde.
{68789}{68806}Hajde.
{68873}{68911}Mogao si stradati.
{68937}{68974}Tko riskira...
{68990}{69026}...profitira.
{69137}{69163}To si ti.
{69194}{69222}Kujin sine!
{69420}{69438}Pazi!
{70119}{70149}Ne dajte mu da pobjegne.
{70178}{70270}Nai novinarku i uzmi joj|kasetu koju je snimala.
{70274}{70302}Moûe.
{70328}{70361}Pusti me!
{70372}{70443}Moûda i hoÊu.|Bacit Êu te kroz prozor.
{70447}{70558}- Nemoj joj nauditi, gade!|- äuti ili Êu joj nauditi...
{70564}{70657}...i prisiliti tebe da gledaö|svaki bolni trenutak.
{71149}{71181}Idi, idi, idi!
{71185}{71241}MiËi se, miËi se!
{71877}{71907}Hajde, idemo!
{72153}{72216}{y:i}Trebamo pomoÊ!
{72261}{72328}Nai pratnju za bolniËare!|Uvedi ih unutra!
{72332}{72379}Trebam specijalce!
{73836}{73884}ubojica
{75308}{75366}Evo kakav je dogovor.|HoÊu kasetu.
{75388}{75481}Ako mi kaûeö gdje je,|maknut Êu svoje prijatelje.
{75487}{75529}A ako mi ne kaûeö...
{75580}{75677}...mogao bih postati neugodan.|VraÊam se za pet minuta.
{75995}{76063}- Je li to godzilla?|- Daj ruku ovamo!
{76081}{76153}- Ne mogu!|- Daj. Izgleda gladno.
{76273}{76341}Hajde, skoËi. Uhvatit Êu te.
{76696}{76735}U redu je, Helen.
{76772}{76843}Jesi li vidio, tata?|Kit ubire sve zasluge.
{76847}{76883}On je obavio posao.
{76959}{77018}No, no. Bit Êe sve u redu.
{77100}{77132}Poduzmi neöto!
{77195}{77250}Poûuri se!|Izvuci me odavde!
{77473}{77548}Gmizavi kujin sine!|Napravit Êu cipele od tebe!
{77747}{77865}- Paûljivo straga! To boli.|- Sine, moraö se utiöati.
{77870}{77912}- Traûe nas.|- Da.
{77945}{78002}Misliö da sam otrovan?
{78010}{78065}Ne pokazujeö simptome.
{78087}{78174}Da jesi, mjesto oko ugriza|bi ti utrnulo.
{78262}{78370}OsjeÊao bi hladnoÊu.|OsjeÊaö li iöta sliËno?
{78418}{78481}- Mislim da si dobro.|- Samo te stid.
{78486}{78545}Dosad bi veÊ|izgubio svijest.
{78601}{78660}äto se dogodilo?|Je li dobro?
{78778}{78810}Bit Êe dobro.
{79165}{79205}Znao sam, tata.
{79224}{79297}- äto je?|- äto da se to i meni dogodilo?
{79301}{79360}- Kako to misliö?|- Moûda sam otrovan.
{79444}{79529}- Ja ti to neÊu isisati.|- Ali ja sam tvoj mali!
{79588}{79665}Ne moûemo ostati ovdje.|Moramo krenuti.
{79673}{79787}Vi idite. Moram u ambulantu|po protuotrov.
{79793}{79872}Zaöto riskiraö ûivot?|Moûete oboje poginuti.
{79879}{79942}BolniËari joj mogu|pomoÊi kada dou.
{79960}{80021}Molim te, ne daj...
{80028}{80072}Ne daj da umrem.
{80082}{80122}Molim te, ne daj...
{80144}{80191}{y:i}Ne daj da umrem.
{80260}{80346}PomoÊi Êu joj i doÊi Êemo za vama.|Ne brinite se. Hajde.
{80368}{80419}U redu. Ali Ëuvaj se.
{80435}{80530}- Hajde, Frankie. Idemo.|- Dobro, dobro!
{80570}{80623}»ekaj malo. Ti ne ideö?
{80626}{80721}Frankie, ti to moûeö.|Nema viöe kaskadera.
{80753}{80791}Idemo. Smjesta!
{81195}{81215}Provjeri barikadu!
{81555}{81601}Imala si pravo,|Joyce. Oprosti.
{81699}{81741}Imala sam pravo u Ëemu?
{81770}{81868}Ne bih smio biti super murjak|kad mogu toliko izgubiti.
{81888}{81977}Shvatite, vas dvoje. Neki od nas|su ranjeni kao i vi.
{81981}{82038}Neki od nas, vaûnih ljudi.
{82060}{82130}Samo nastavi tako,|pametnjakoviÊu. Izazivam te.
{82161}{82226}Nije pametno naljutiti|zaljubljenu ûenu.
{82244}{82299}- Vjeruj mi.|- äto radiö?
{82304}{82414}U ovakvim sluËajevima prvo se|puötaju ranjeni taoci.
{82484}{82556}Ne izgledaö dobro.|äto se dogodilo?
{82558}{82614}Sve u redu.|Bit Êe mi dobro.
{82619}{82720}éao mi je öto sam se prije|naljutio. Nisam htio.
{82726}{82788}Bilo je nepristojno od mene|nabacivati se tvojoj curi.
{82810}{82856}Nema veze. Nema veze.
{82864}{82922}Daj da te Ëastim piÊem.
{82929}{83014}- Lijepo od vas, ali dobro sam.|- Zahtijevam!
{83112}{83176}Ne, molim vas!|Ne ûelim umrijeti!
{83220}{83300}- Bojim se visine!|- Uskoro Êeö biti na zemlji.
{83304}{83373}- Ne, molim vas, joö uvijek sam|dijevac! - Prestani sliniti!
{83533}{83556}Pogledaj.
{83581}{83672}Ovdje Kit. Dobro sam.|Trebam naÊi ambulantu.
{83732}{83768}Sluöajte me!|Ne razumijete!
{83771}{83812}Doktore, policija.
{83839}{83908}Ovdje policija Hong Konga.|Opkoljeni ste.
{83912}{83974}Jedini vam je izbor|da se predate!
{83985}{84073}Ali ja imam brojne izbore.|Evo izbora broj jedan.
{84106}{84159}Pomozite nam.|Vrlo su nasilni.
{84200}{84284}Ambulanta je 431 .|Dovedi pomoÊ öto prije.
{84298}{84343}Zaöto ambulanta?
{84380}{84461}- äto hoÊeö?|- Helikopter na krovu...
{84465}{84516}...za 30 minuta.
{84522}{84577}- Ne moûemo tako brzo.|- Moûete.
{84580}{84634}Ne shvaÊate me ozbiljno.
{84640}{84709}{y:i}Znate da bi to bila pogreöka.
{84713}{84805}Helikopter na krovu|za 30 min. Da ili ne?
{84810}{84866}Treba nam bar sat.
{85107}{85193}On je veÊ bio mrtav.|Producent je sljedeÊi.
{85198}{85277}{y:i}Spremite helikopter za let|{y:i}na Tajvan za 28 minuta!
{85315}{85362}Zaöto idemo Ëak|na Tajvan?
{85401}{85478}Ne brini se, ne idemo. Ali|policajci nisu baö pametni.
{85504}{85589}Ovo Êe ih zbaciti s traga|i dati nam priliku za bijeg.
{85620}{85657}PriliËno pametno.
{85663}{85727}- Kakav sjajan plan.|- Dobro. Ljubi mi guzicu.
{85731}{85793}Moûda Êeö ûivjeti|joö pola sata.
{85803}{85876}Vi ste doista najbolji terorist|kojeg sam ikad vidio.
{85881}{86012}Pametan, proraËunat, ubojit.|Dive mu se i boje ga se.
{86017}{86076}DoÊi Êu vam u pomoÊ.|Budite strpljivi.
{86091}{86155}- Gadafi se trese u vaöoj sjeni.|- Da.
{86164}{86262}I ako mogu dodati osobnu|primjedbu, vrlo ste zgodni.
{86362}{86389}Hajde.
{86510}{86544}- äto je to?|- »ekaj.
{87480}{87598}1, 2, 3, 4, 5, 6, 7, 8, 9, 10.
{87602}{87631}äto radiö?
{87662}{87730}- Vjeûbam.|- Prestani s tim sranjem.
{87809}{87870}- Svakako.|- Baci oruûje, oloöu.
{87874}{87967}- Izgledam li naoruûan?|- To sam ja, Frankie, u redu?
{88000}{88073}- Hej, tata.|- Na pod.
{88276}{88332}Uljepöaj mi dan, ptiËice.
{88378}{88446}- Ruke gore.|- Viöe nisi tako opasan, je li?
{88450}{88478}Ohladi.
{88526}{88586}- Dobra smo ekipa.|- Ako ti kaûeö.
{88640}{88717}Za starog Ëovjeka uopÊe nisi loö.
{88721}{88791}Samo gledaj, sine.|Moûda nauËiö neöto.
{89140}{89163}Prestanite!
{89238}{89319}- Zaöto se ovdje puca?|- Mislili smo da smo neöto Ëuli.
{89338}{89399}Drugi put provjeri prije|nego öto pucaö, idiote!
{89496}{89551}Moramo iÊi. Vani su.
{89566}{89609}Pretraûite ostale katove.
{89695}{89753}Ostani ovdje.|Ja Êu provjeriti.
{89820}{89879}äto umiöljaö da si?|Izdajeö nareenja, a...
{90019}{90085}Ja sam Doktorova|miljenica, seronjo.
{90253}{90313}Nitko me naziva|seronjom, kurvice.
{90516}{90586}Gledaj, tata.|To je porno zvijezda.
{91048}{91075}To nije u redu.
{91401}{91505}Stani, oloöu. Vrijeme je za|Frankieja. Primi se za noge.
{91517}{91604}Podigni ih do oËiju,|ti bezvrijedni izmetu.
{91611}{91640}Tata!
{91663}{91696}Sveûi ga.
{91792}{91855}Dosta mi je akcije.|Ti ga sveûi.
{91907}{91936}Dobro onda.
{92057}{92117}Pomozi mi, tata.|Prevelik je.
{92127}{92201}Moraö ti. Ako ti pomognem,|tko Êe ga drûati na niöanu?
{92234}{92270}Ja Êu.
{92323}{92414}Oprosti, ali staromodan sam.|éene ne smiju imati oruûje.
{92429}{92481}Moûeö ti to. Hajde, deËko.
{92499}{92569}Nema öanse, tata.|Poput gorile je.
{92605}{92639}Jadan si.
{92649}{92708}- HoÊeö li moÊi?|- O, da.
{92715}{92788}Dat Êu ti, ali opasno je.|Moraö biti paûljiva.
{93027}{93072}- äto je to?|- äto?
{93169}{93205}Ciljaj njega.
{93213}{93259}- Ciljaj dolje.|- U njega.
{93304}{93371}Ne, ne ovdje. Dolje.
{93386}{93470}Mogu samo reÊi da bi bio|opasan da imaö mozga.
{93474}{93525}Spasio sam ti ûivot.
{93529}{93625}Nisi, glupane. Opameti se, deËko.|Ona je s negativcima.
{93648}{93701}Tvoj stari je|pametniji od tebe.
{93757}{93798}Pametniji sam i od nje.
{93820}{93883}Ispraznio sam oruûje prije|nego öto sam joj ga dao.
{94030}{94146}Ni ne pomiöljaj. Takneö li ga,|neÊu se suzdrûavati.
{94269}{94317}Ti nisi dama. Kuja si!
{94394}{94423}Ne, ne!
{94446}{94507}IduÊi put prekriûi noge.
{94575}{94639}Nemoj ga ubiti.|On je savröeni taoc.
{94674}{94764}PretuÊi Êu ga namrtvo|nakon öto se preodjene.
{94772}{94807}Nakon öto se preodjenem?
{94890}{94994}- Odakle ti moj filmski kostim?|- éelim istuÊi superjunaka.
{95116}{95140}äto se dogaa?
{95160}{95191}Sutraönje vijesti.
{95471}{95504}Ambulanta
{95899}{95936}Hvala na pomoÊi.
{95944}{96025}ObeÊao sam si da viöe nikoga|neÊu ostaviti za sobom.
{96036}{96116}Viöe nikad?|Ovo ti se veÊ dogodilo?
{96168}{96196}Samo jednom.
{96223}{96275}Ali trebao sam ih|moÊi spasiti.
{96376}{96446}- éao mi je.|- Gdje je kaseta?
{96458}{96518}Ispod kovËega u sobi|za izloûbu.
{96524}{96601}Ovo je prvi put da je|Doktor snimljen.
{96608}{96675}- Kakva korist od toga?|- Nisam siguran.
{96693}{96741}Ali ne ûelim da|on uzme snimku.
{96833}{96895}- Brzo Êeö se vratiti?|- ObeÊavam.
{97061}{97150}Sluöaj, moûda ti stvari prije|nisu polazile za rukom...
{97168}{97271}...ali znam da Êe ovaj put|sve biti u redu.
{97548}{97573}Pogodak!
{98225}{98301}- äto kaûeö? Svia ti se?|- Seronjo!
{98379}{98448}- Nemoj!|- Bacit Êu te kroz taj prozor.
{98759}{98842}Moj plan bi uspio|da se ti nisi umijeöao.
{98850}{98938}Ti i onaj tjelesni Ëuvar.|Gdje je on, uostalom?
{98976}{99067}Smirite se. IzvuÊi Êu vas|za koji trenutak.
{99144}{99178}Frankie.
{99195}{99232}Gdje je tvoj Ëuvar?
{99251}{99306}- Ne znam.|- Zbilja?
{99310}{99342}- Da.|- To je lijepo.
{99358}{99388}Frankie!
{99447}{99530}Ovo me viöe ne zabavlja.|Dovedi tog Ëuvara ovamo.
{100073}{100132}- Gdje je Bolo?|- Sere.
{100143}{100200}- Niöta ne vidim.|- »ekaj malo.
{104663}{104688}Ne!
{105283}{105305}Zeko!
{105401}{105423}Zeko!
{105628}{105664}Svi natrag!
{105695}{105754}Uhvatite ga! Uhvatite ga!
{105768}{105804}Ne! Ne!
{105817}{105871}Pustite me!
{105894}{105939}- Stavi mu lisiËine!|- Evo!
{105983}{106016}Vodi ga odavde!
{106037}{106078}Lovite!
{106331}{106364}Dolje!
{106402}{106475}Ostanite pribrani!|Dovedite bolniËare!
{106508}{106548}Ostanite mirni!
{106560}{106623}Nema razloga za uzbunu!
{106737}{106850}- äto Êemo s njim?|- To je Ëuvar Frankieja Lonea.
{106869}{106925}Pustite ga.|äto se dogaa?
{106953}{107041}Voa terorista je Doktor.|Psihopat...
{107048}{107166}...koji je raznio ökolski autobus.|Ubit Êe sve taoce.
{107175}{107244}- äto predlaûeö?|- Ne moûemo samo stajati.
{107248}{107354}Iznenadite ga prije|nego öto pronae izlaz.
{107358}{107417}Mislim da ne mogu riskirati.
{107421}{107487}S njim nema drugog naËina.|Vjerujte mi.
{107491}{107575}Ne mogu riskirati s taocima.|Vodite ga.
{107587}{107646}- »ekajte! Ima joö neöto.|- äto?
{107708}{107782}Novinarka je snimila Doktora|i njegove ljude. Pogledajte.
{107806}{107847}- Da vidim.|- Da, gospodine.
{108013}{108064}Bio je jedan od|naöih najboljih.
{108252}{108286}»ujeö li?
{108301}{108362}Tvoj Ëuvar stvara probleme.
{108502}{108587}éao mi je.|Samo radi svoj posao.
{108630}{108739}Ne mogu si pomoÊi.|Uvijek je bio radoholiËar.
{108756}{108857}Ako vam je laköe, otpustit Êu ga|Ëim ovdje zavröimo.
{108895}{108933}Rijeöit Êu ga se.
{108947}{109015}- Na koljena!|- Molim vas. Dajte.
{109023}{109080}»ekajte! Imam ideju.
{109105}{109129}Ne ti.
{109177}{109247}äto kaûete na znak dobre|volje policajcima vani?
{109279}{109339}Reci mi.|I neka bude dobra.
{109349}{109444}Mogli biste pustiti mene|i Frankieja neozlijeene.
{109448}{109493}Kukavice! äto smjeraö?
{109501}{109563}Netko mora neöto uËiniti.
{109598}{109662}Moram reÊi da to|nije loöa ideja.
{109670}{109761}Osim onog dijela u kojem|si ti neozlijeen. éalim.
{109781}{109819}Ne! Molim vas!
{109821}{109868}Ne, molim vas!
{109879}{109905}Pustite ga!
{109957}{109996}Frankie, ne daj im...
{110364}{110409}Kasnije Êete mi zahvaliti.
{110416}{110511}Njegovi filmovi su neukusni|i bezvrijedni. Ipak...
{110530}{110641}...ako mi ne predate helikopter|i Frankiejevog Ëuvara...
{110645}{110755}...poslat Êu dolje par|iz ameriËkoga konzulata.
{110798}{110840}Taj öupak!
{110886}{110951}- Poûurite se s tim heliÊem.|- ZapovjedniËe.
{110956}{111024}Morate me razmijeniti|za te taoce.
{111415}{111476}To si ti, Kit? To si ti?
{111623}{111681}- Kamo Êeö?|- Pusti me.
{111700}{111792}Vidio sam te na vijestima.|Uûivo si puno zgodnija.
{111812}{111904}Ako hoÊeö da te pustim,|moûda se moûemo dogovoriti.
{111944}{111968}Pa...
{112012}{112102}Napravit Êu priËu o tebi. Imam|dosta moÊi na TV postaji.
{112217}{112298}Ekskluzivnu. Moûeö ispriËati|svoju ûivotnu priËu.
{112344}{112397}Glupa ûensko. Evo ti|ekskluzivna priËa.
{112559}{112612}Connie Chung, poûderi se.
{112677}{112770}Kad helikopter stigne,|dovedite mi Ëuvara.
{112774}{112801}äto se dogaa?
{113261}{113346}Joyce! Joyce! Komunikator.
{113541}{113580}Ti mala kujo.
{113584}{113644}Pokuöavaö dozvati|pomoÊ? Je li?
{113852}{113915}- NeÊu te predati njemu.|- »ekaj.
{113926}{114038}Mogu ga zaustaviti. ObeÊao sam|nekome da Êu se vratiti.
{114042}{114123}- Ne kröim obeÊanja!|- Ne vraÊaö se unutra. Jasno?
{114177}{114251}Imamo situaciju. Sve jedinice...
{114255}{114298}Natrag! Natrag!
{114318}{114357}Stani tamo!
{114361}{114399}- Stani!|- Otvaraj!
{114487}{114555}- Van!|- Da se nitko nije makao!
{114619}{114652}éao mi je.
{114703}{114828}Znam da ne razumijete,|ali moram to uËiniti.
{114837}{114958}Objasnit Êeö mi kad te uhitim.|U meuvremenu, sretno.
{115087}{115130}Ne! »ekajte!|Ne pucajte!
{115270}{115326}Pustite ga! Ne pucajte!
{115384}{115414}»ekaj! »ekaj!
{115446}{115476}Pazi!
{115799}{115840}Ludi gad.
{116101}{116246}»ekaju te na krovu.|Budi oprezan! Helen.
{116949}{117011}Otvorite paljbu! Sruöite ga!
{118030}{118059}Jeste li vidjeli Kita?
{119311}{119349}- Ne moûeö!|- Vi idite!
{119361}{119405}- Preopasno je!|- Idite!
{119446}{119470}Kit!
{119540}{119572}Jesi li dobro?
{119604}{119638}Jesi li ovdje?
{119687}{119734}- Gdje si?|- Ovdje.
{119760}{119808}- Ne vidim te.|- Iza tebe.
{119994}{120018}»isto je. Doite.
{120161}{120186}Brûe!
{120826}{120855}Pusti me!
{121184}{121206}Helen!
{121286}{121321}Oprosti, Kit.
{121342}{121389}Oprosti.|Pokuöala sam pobjeÊi.
{121426}{121490}Znao sam da Êeö se|doÊi iskupiti...
{121494}{121566}...nakon öto nisi uspio spasiti|svoju ûenu i ökolsku djecu.
{121622}{121692}Sluöaj, zbog|poslovne uljudnosti...
{121696}{121765}...namjestio sam sat|na bombi za pet minuta.
{121777}{121847}Riskantno je, ali to ti|joö uvijek daje priliku.
{121899}{121985}Ne sluöaj ga, Kit! Spasi sebe...
{122014}{122046}...i sve ostale!
{122221}{122324}Opet nisi uspio. PobjeÊi Êu|dok ti glumiö ukletog junaka.
{122548}{122575}Ovo je ostavio.
{122983}{123075}- NeÊete nas pustiti? Daj!|- Voljela bih da mogu.
{123101}{123167}Ali Kong ima velike|planove za tebe.
{123186}{123234}Trebalo bi biti zabavno.
{123300}{123402}äto se tiËe policajca,|ovo je svröetak puta.
{123447}{123483}Ne! Nemoj!
{123525}{123547}Molim te.
{124051}{124079}Pusti ga!
{124287}{124318}Jesi li za ples, starËe?
{124396}{124421}Stani!
{124473}{124506}Ne diraj ga.
{124532}{124566}Pusti ga na miru.
{124592}{124629}Dosta je, gade!
{124695}{124717}Tata!
{125012}{125049}To je moj deËko.
{125722}{125751}Pokaûi mu, Frankie!
{125838}{125876}Misliö da si opasan?
{125887}{125950}Sada Êeö osjetiti pravu bol.
{125981}{126034}Lijep govor,|filmska zvijezdo.
{126093}{126129}Stvarno ûeliö plesati?
{126159}{126225}- U redu, idemo.|- Da.
{126409}{126431}Hajde.
{126519}{126546}Ni blizu.
{126587}{126641}Dovoljno blizu?
{127925}{128026}Ne! Daj da se odmorim,|da doem do daha.
{128551}{128596}Kada Êe mene boljeti?
{128628}{128654}Uskoro.
{128757}{128822}»ekaj. Je li to ono|öto mislim da jest?
{128830}{128897}Frankiejevi rekviziti.|S tvoje internet stranice.
{128918}{128955}Ali, ja sam nenaoruûan.
{128966}{129040}Ne boj se. Dat Êu ti ih.
{129306}{129350}Hej, to boli!
{129360}{129426}Ni pribliûno koliko|Êe ovo boljeti.
{131722}{131746}Hajde!
{132051}{132080}To! To!
{132087}{132132}To! Razbij ga!
{132657}{132681}To!
{132993}{133067}Joyce! Joyce! Daj, duöo.|Probudi se!
{133130}{133222}- Kam!|- Hajde. Sada je sve u redu.
{133231}{133265}Jesi li dobro?
{133309}{133340}Da vidimo.
{133478}{133545}Frankie, bio si sjajan,|sine. Bio si sjajan.
{133574}{133608}Naravno da sam sjajan.
{133623}{133651}Frankie!
{133868}{133925}»ekajte! Stanite! UpomoÊ!
{133943}{133984}Pomozite mu.
{133995}{134037}Kakva humanost!
{134052}{134138}- Ne moûete ni zamisliti taj strah.|- Sad je gotovo.
{134370}{134450}- Koliko je loöe?|- Istu postavku je koristio i prije.
{134528}{134622}- äto si tada uËinio? - Pogreöno|sam presjekao crvenu ûicu.
{134628}{134692}- Onda presijeci plavu.|- Da razmislim.
{134704}{134793}Idi i spasi sebe, Kit.
{134821}{134882}Preûivjet Êemo ovo.|Samo se drûi.
{134920}{134953}Sve öto sam ûeljela...
{134968}{135010}...bila je dobra priËa...
{135036}{135112}...i pristojna gledanost.|Moûda poviöica.
{135150}{135179}Mislim...
{135209}{135256}Ja sam dobra novinarka.
{135381}{135469}- äto?|- Izaöao sam. Na sigurnom sam.
{135499}{135576}Kako ti ide? Crvena ili plava?
{135594}{135679}- Bolesni gade!|- Znam da ti moûeö rijeöiti problem.
{135716}{135790}Crvena ili plava?|Imaö oko 30 sekunda.
{135860}{135926}Tko kaûe da mora biti|crvena ili plava?
{135982}{136026}Ova metalna nit.
{136036}{136081}{y:i}Prije si me|{y:i}pokuöao prevariti.
{136085}{136179}Htio si da pomislim da je|metalna nit satni mehanizam.
{136242}{136276}Ali zapravo je...
{136337}{136397}...sklopka za deaktiviranje,|zar ne, Doktore?
{136449}{136548}Nemoj odgovoriti.|Pokuöajmo samo, u redu?
{137015}{137062}Ovaj put ti gubiö.
{137100}{137180}O, ne. Ni izbliza.
{137193}{137287}Ima joö zloËina, bombi|i ljudi za ubijanje.
{137298}{137350}{y:i}Silovanja i pljaËki.
{137361}{137424}Dobio si bitku,|ali ne i rat!
{137441}{137511}Kako se osjeÊaö, Doktore?|Je li ti rame utrnulo?
{137529}{137608}{y:i}Krvari li ti nos?|{y:i}OsjeÊaö li slabost?
{137667}{137707}To je zmijski otrov.
{137718}{137805}Noû kojim sam te ubo|bio je umoËen u njega.
{137822}{137899}Potraûiö li pomoÊ, otrov|bi se mogao proöiriti.
{137903}{137968}Tko riskira profitira.
{138008}{138054}Ne moûe biti.
{138270}{138298}Pomozite mi!
{138468}{138488}Stari!
{138693}{138757}- Jebeno! Rolex!|- Vidi ove dragulje!
{138778}{138823}- Idemo.|- Bjeûimo odavde!
{139272}{139351}Hvala na brizi, ali|Frankie je dobro.
{139355}{139430}U znak poötovanja|prema nevinim ûrtvama...
{139437}{139507}...osnivam zakladu|Frankieja Lonea.
{139522}{139594}Sva zarada moga novog filma...
{139599}{139724}...iÊi Êe obiteljima ûrtava|i za oporavak preûivjelih.
{139734}{139801}Hvala. Cijenim vaöu pomoÊ.
{139948}{139996}Oprostite. Prolazimo.
{140019}{140081}- Igra u 11:00 h.|- Moj producent.
{140099}{140146}»ekaj! Helen!
{140148}{140205}Izvanzemaljci su se spustili|u leteÊem tanjuru!
{140207}{140291}Prelili su me ûeleom i|vröili rektalna ispitivanja!
{140302}{140346}Govorim istinu!
{140361}{140439}Dobra stvar jest to|öto je to sjajna priËa.
{140444}{140488}To Êe biti moj iduÊi film.
{140493}{140555}Samo öto Êu osobno|napisati scenarij.
{140559}{140623}Ipak ja najbolje|znam pojedinosti.
{140631}{140672}Nije li tako, tata?
{140695}{140740}äto ti je s nosom?
{140751}{140839}Ovaj put neÊe Frankie Lone|biti junak.
{140860}{140944}Ima joö veÊi junak,|netko puno vaûniji.
{141009}{141104}U redu. Charlie Wang,|moj pokojni redatelj.
{141350}{141384}O Ëemu razmiöljaö?
{141424}{141542}Prvi put u dvije godine|mogao bih mirno spavati.
{141565}{141603}Hej, tjelesni Ëuvaru!
{141629}{141689}Nisam li rekao|da Êu te uhititi?
{141853}{141894}Ovo Êe biti zabavno.
{141901}{141931}Ne brini se.
{141935}{142045}Nakon öto objavim priËu,|neÊe te moÊi optuûiti.
{142091}{142149}Stari, javnost mi vjeruje!
{142156}{142255}Vjerovat Êe mi i ako im kaûem|da nosiö ûenske gaÊice. I ti!
{142280}{143780}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3uds6|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
