{41}{137}u kvartu su bili propalice i huligani.|Skupljali su skalpove.
{164}{245}Odatle je doöla irokeza.
{247}{351}Uvijek je bio rat.|-Za to sluûe ratnici.
{353}{425}Ne znam. Ne|nedostaje mi taj ûivot.
{425}{497}PomoÊi Êu vam pronaÊi|Murdocka, i ispraviti pogreöku, ali...
{535}{600}Ne mogu ubiti.|-»ak ni Pikea?
{600}{679}»ak i ako bi sprao ljagu|s imena ako ga ubijeö?
{679}{761}Moja Ëista savjest|je jedino öto trebam.
{761}{792}No...
{792}{856}Gdje je ona luda budala?
{895}{952}Prijenos.
{955}{1012}OsjeÊaje izljeËenja.
{1015}{1099}Ne moûeö pospremiti|te stvari, znaö?
{1099}{1190}Moraö izraziti|kako bi napredovao.
{1202}{1278}Moraö ojaËati|svoj emocionalni toranj.
{1278}{1386}Poslati valove ljubavi|prema sebi i prihvaÊanja.
{1473}{1521}Hvala.
{1569}{1688}VOJNA PSIHIJATRIJSKA BOLNICA|Mannheim, NjemaËka
{1825}{1878}Odmaknite se!
{1892}{2003}»ini se potpuno neosjetljiv na to.|Ne moûemo dobiti bazno oËitanje.
{2003}{2106}Jeste li povisili voltaûu?|-Svakog puta. -I?
{2108}{2204}OsjeÊaji izljeËenja, duöo!|Je li to sve öto imate?
{2204}{2264}Evo ga.|-Odmaknite se.
{2367}{2448}Da, mislim da|sam neöto osjetio.
{2473}{2623}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{2794}{2902}Howard Little, dobio si paket|od Annabelle Smith.
{2935}{3029}Ne znam nikakvu Annabelle Smith.
{3074}{3158}Naravno da znaö, Howey.|Naravno da znaö.
{3161}{3235}Annabelle, sjeÊaö se?|Sestra iz Da Nanga?
{3237}{3328}Crvenokosa, duplo amputirana.|Profesionalna zmajarica.
{3364}{3429}DeËki. Annabelle.
{3477}{3604}Annabelle. -Annabelle,|nadmaöila si samu sebe. Pogledaj ovo!
{3604}{3700}Tako je stvarno!|-Film. 3 dimenzije.
{3702}{3758}Ustaj, vojniËe!
{3758}{3837}ävabe napreduju na|zapadnom frontu. -Zaboga!
{3837}{3892}Imam tajnu misiju za tebe.
{3892}{3971}Uzmi ovo i podijeli ih meu|vojnicima. -Da, gospodine.
{3973}{4060}Nemoj iznevjeriti kraljicu.|-NeÊu, gospodine. -OdliËno!
{4064}{4156}Film, film, film!|Proglaöavam te vitezom.
{4160}{4232}Sir, sagnite glavu.|Ustanite i idemo ponovo.
{4271}{4362}Sad pjevaj kraljici.|Kad kaûem... Ne joö.
{4446}{4513}Daj mi svoje naoËale!|Daj mi naoËale!
{4527}{4626}Kad klekneö odmah sagni glavu. Gledanje|u oËi je nepoötivajuÊe. ShvaÊaö?
{4695}{4753}Sada me gledaö u oËi.|To je pogreöno.
{4760}{4810}Film, film, film!|Aquamane, zdravo!
{4877}{4940}Ustani, sir 3Du.
{4940}{5024}I uûivaj u svojem filmu.
{5112}{5201}Brate, al' bi mi dobro|doölo dva sata "ne ovoga".
{5201}{5294}Podijeli sedative i|naruËi pizze za ove frikove.
{5294}{5386}Film, film, film...
{5405}{5489}Film... Sranje!
{5527}{5628}Oprostite, mogu li vam pomoÊi?|-Da. Satnik Murdock? Gdje je?
{5630}{5685}Onuda.|-Hvala.
{5685}{5736}"El diablo".
{5767}{5853}Smirite se. Nema|priËanja za vrijeme filma.
{6026}{6076}<i>Pa to je 3D, ËovjeËe!</i>
{6129}{6174}Kapetane Murdock?
{6174}{6261}SjeÊate me se? Iz Bagdada?
{6412}{6493}Ovo je besmisleno. Lik je proövikao.|-Da, zbog toga je ovdje.
{6493}{6572}Njegov Ëitav tim je|pobjegao, osim njega.
{6572}{6678}Film! -Pogledajte okolo,|uvjerimo se da je sam.
{7426}{7493}O, satniËe!|Vaöa koËija vas Ëeka!
{7493}{7579}éalim, druötvo. Moram iÊi! Uûivajte|u filmu! IspriËat Êete mi kraj!
{7579}{7680}Charisa, kako si? Ostani lijepa,|duöo! -Idemo, B.A. -Pokret!
{7750}{7800}Idi po kamion!
{7800}{7915}äefe, pucaju na nas!|Vidim metke u 3D-u! -Ulazi unutra!
{7915}{8011}Kao da stvarno pucaju na nas!|-I pucaju na nas, luda budalo!
{8052}{8107}Stani!|-Pregazi!
{8229}{8313}éalim, stari. -Izgleda da su|krenuli prema Tormacku.
{8313}{8373}Idemo, idemo.
{8483}{8548}Gospodo! -Jebote,|pa to je Hannibal Smith!
{8548}{8701}Je li itko od vas naoruûan i/ili traûen|bjegunac? -Nije. -Mi smo oboje.
{8704}{8778}äto znaËi...?|-To je loöa ideja! Loöa ideja!
{8778}{8862}Ne budi beba. Ulazi u avion!|-Otimate avion?
{8862}{8915}Zato sam se pridruûio vojsci.
{8915}{8996}Moramo zavröiti bijeg! Budi muöko|i penji se! -Najbolji i najbistriji.
{8999}{9087}Hvala, deËki, to bi bilo sve.|-Tko ima kljuËeve? Trebam kljuËeve!
{9087}{9186}äto Êe ti kljuËevi? -Trebam kljuËeve?|-Za öto? Ovo je loöa ideja.
{9188}{9251}Izvukli smo ga s psihijatrijskog|odjela. Hannibale,
{9251}{9344}preuzmi i idemo. -Opusti se,|bit Êeö dobro. -Uzmi ovo.
{9346}{9438}HoÊe me onesvijestiti? Bolje da|me onesvijesti inaËe Êu ja tebe.
{9438}{9514}SvjetleÊa dugmad me zbunjuje...|-ZaËepi, Murdock!
{9514}{9593}Murdock. Idemo. -Je l' znaö voziti ovaj|avion? Zaboravi. Idem se ja predati.
{9596}{9687}äto ovo dugme radi? -Hajde!|Hajde, Murdock. -PosreÊilo mi se.
{9687}{9756}Drû'te se, deËki!
{9900}{9963}Stani! Stani, stani!
{10027}{10114}Faco, cura ti se vratila.|-U rikverc, odmah!
{10145}{10195}Bjeûi, Joe, brzo!
{10195}{10296}C-130 protiv Mercedes Benza.|-Uzleti, Murdock.
{10325}{10380}Brûe! Brûe! -Pokuöavam!
{10948}{11010}Vozi nas do kontrole leta.
{11013}{11087}Dame i gospodo,|oËekujemo laganu turbulenciju.
{11089}{11190}Molimo ostanite na mjestima dok|kapetan ne iskljuËi znak za pojas.
{11190}{11305}Ne brinite, deËki! Turbulencija|nikad nije sruöila avion.
{11358}{11411}Koji je to vrag?
{11411}{11516}Ali imamo podzvuËne|auto-lovce (UAV) sa projektilima!
{11523}{11586}A oni stalno ruöe avione.
{11641}{11718}Pristiûu. Palim protumjere!
{11960}{12085}Jeste vidjeli to? To je moja diverzija!|Zaronili su na moju diverziju.
{12190}{12269}»ekaj, Ëekaj! OkreÊemo se!
{12305}{12382}<i>Murdock, koji vrag to radiö?!</i>
{12384}{12475}SjeÊate se Meksika, deËki?
{12504}{12593}Dame i gospodo, ovdje kabina.|Ako pogledate na vaöu desnu stranu
{12595}{12689}primijetit Êete|da vam desno krilo gori.
{12753}{12852}SaËekajte! Paljba projektila na Ëekanju.|-PoruËnica Charisa Sosa, DCIS.
{12852}{12952}BojniËe, nemojte sruöiti taj|zrakoplov! Prisilite ih da slete!
{12955}{13036}Drûavni bjegunci su na tom avionu.|-Kao i ukradeno vlasniötvo vojske SAD-a.
{13036}{13113}Billy, hoÊu video tog|projektila na mom monitoru!
{13204}{13264}Projektil lansiran, gospodine.
{13331}{13420}Pogodak! Presreli|su i uniötili Herkula.
{13422}{13480}éao mi je, poruËnice.
{13729}{13813}Ne mogu vjerovati. -Gospodine,|padobrani su se otvorili na Bufordu.
{13816}{13911}äto? -HoÊu da ugasite|te dronove, smjesta!
{13911}{13993}5000 km su... -Tko god|upravlja njima neka ih vrati!
{13995}{14065}Trebamo spustiti te dronove,|ja Êu najebati.
{14065}{14127}HoÊu ih ûive!
{14257}{14333}Jesu svi dobro? -Koje su|öanse da misle da smo mrtvi?
{14396}{14504}Ne odliËne. -Reci mi da nismo|viöe u onom avionu. -Nismo u avionu.
{14504}{14592}Hannibale, ako smo na 6000 m,|moûemo disati, zar ne?
{14595}{14681}O Ëemu ti to priËaö, 6000 m?!|-Upalimo oruûja!
{14681}{14787}Koji vrag? -Hej, Bosco,|smrdiö! Moram otvoriti prozor!
{14911}{15019}äto moûete, piËke?!|äto moûete?!
{15110}{15189}Faco, daj meni malo!|-Zaöto smo u padajuÊem tenku!?
{15189}{15293}Jer je avion eksplodirao!|-äto? äto?! Kad?! -Nedavno!
{15295}{15376}Reaperi su ga sruöili!|-Koji Reaperi?
{15444}{15511}Isti koji nas sada|pokuöavaju ubiti!
{15511}{15592}Krivim tebe, Hannibale!|-TehniËki ne letimo! -Znam!
{15592}{15652}Padamo, budalo!
{15789}{15830}Isuse!
{15851}{15921}UAV-2 je pao.|Izgubili smo jednog drona.
{15921}{15983}Hannibale, u nevolji smo!
{16072}{16122}Zakon!
{16122}{16237}Faco, idi do topa. Ima jedno|jezero 800 m od ove pozicije.
{16237}{16367}äto pokuöavam pogoditi? -Vjeruj mi!|Zakreni top za 82 stupnja! -Paljba!
{16417}{16463}Pali!
{16501}{16546}Pali!
{16609}{16690}Pokuöavaju sruöiti|onaj drugi dron? -Ne.
{16690}{16755}Pokuöavaju letjeti tim tenkom.
{16755}{16861}Leti tenkom! -Ne moûe letjeti|tenkom, budalo! -Rotiraj 16 stupnjeva!
{16863}{16918}Jesam!|-Pali!
{17026}{17108}Rotiraj 34 stupnja! Odmah!|-Hannibale... -»ekaj!
{17108}{17175}Pali!
{17225}{17338}Je li to potvren pogodak?|-Okreni se naprijed i Ëekaj!
{17417}{17482}Murdock, zatvori poklopac!|-Poklopac, moûe!
{17482}{17544}Je l' uspjelo? Je l' uspjelo?|-Hajde, duöo!
{17544}{17606}Poklopac neÊe...
{17606}{17666}<i>Bacit Êu te van!</i>
{17669}{17738}äefe. Ciljam u niöta!
{17738}{17827}Hajde! -Bila mi je Ëast,|gospodo! -Hajde, duöo.
{17829}{17889}NajveÊa voûnja je|ona posljednja!
{17889}{17961}Ispali sve!|-Hajde, duöo!
{18031}{18076}KAKO VOZIM?
{18407}{18491}<i>To nije poöteno|prema ribama!</i>
{18491}{18558}<i>Varalico!</i>
{18584}{18659}<i>Ti i tvoje gunanje.</i>
{18659}{18728}<i>Uplaöila si svu ribu!</i>
{19062}{19150}EUROPSKI STOéER CIA-e|Stuttgart, NjemaËka
{19189}{19256}PËele, vrijedne pËele.
{19256}{19316}Moûete skinuti sakoe, deËki.
{19316}{19378}Ovdje je pakao.|Znojim se kao kurva u crkvi.
{19380}{19433}Gospodine. -Da?|-Smitha i njegov tim
{19433}{19524}su napala 2 Reaper drona u C-130|avionu iznad Mannheima, NjemaËka.
{19541}{19654}Ne znam je li enkripcijska greöka,|ali piöe da su sruöeni, u tenku.
{19685}{19774}NORAD kaûe da je eksterni,|ali izvjeötaji se ne podudaraju.
{19793}{19843}Naravno da jeste.
{19846}{19937}Jedna njemaËka kuÊanica kaûe da je|vidjela tenk kojeg su izvlaËili iz jezera
{19937}{19997}i tipa koji sliËi Murdocku.
{19997}{20100}Oprostite, kuda za Berlin?|<i>-Traûio je kako doÊi do Berlina?</i>
{20102}{20222}To je nemoguÊe. -Ovo Êe biti drugi|put kako je Smith umro ovaj tjedan.
{20222}{20287}Je li to moguÊe?
{20409}{20467}<i>äto imaö za mene?</i>
{20467}{20574}Upravo sam dobio proËiöÊenu sliku|Smithovog posjetitelja u zatvoru.
{20574}{20697}Ne znam joö tko je.|-Zdravo, zgodni.
{20723}{20788}Vidjela sam ga veÊ.
{20788}{20855}Znam ovog tipa.
{20901}{20946}Bagdad...
{20946}{21032}Spoji me s Langleyem.|Idemo pecati.
{21035}{21167}Jesi Ëuo za to? Ja sam Ëuo dijelove,|ali koliko smo mi? -Gospodine... -PriËam!
{21167}{21277}Moûeö prestati? Imate poziv|na sigurnoj liniji od poruËnice Sose.
{21279}{21363}Traûi agenta Lyncha.|-On nikada nije dostupan.
{21363}{21430}Agent Lynch iz Bagdada?
{21469}{21541}äator generala Morrisona.
{21562}{21608}Van!
{21627}{21673}Zaöto je imamo?
{21673}{21764}Ima fantastiËnu osobnost.|Zato.
{21764}{21840}S kime priËam?|-Ovdje satn...
{21843}{21956}PoruËnica Sosa. Je li to agent Lynch?|éao mi je, znam samo prezime.
{21956}{22044}Nemam ga. äto mogu uËiniti|za vas, poruËnice?
{22044}{22174}Gledam u vaöu sliku iz|zatvorskih baraka u Fort Carsonu.
{22190}{22308}Zgodna je. -Jeste li posjetili bivöeg|pukovnika H. Smitha u zatvoru?
{22349}{22433}Ne znam o Ëemu priËate.
{22433}{22529}Bivöa satnice. <i>-Ako ste|sudjelovali u Smithovom bijegu</i>
{22529}{22615}<i>i ako mu trenutno|pomaûete u skrivanju...</i>
{22639}{22687}Druökane...
{22687}{22742}<i>Ako moûete dokazati|takvo neöto...</i>
{22742}{22804}vaöe slijedeÊe promaknuÊe|Êe biti u rangu pet zvjezdica.
{22804}{22886}I ako pomaûete|vratiti one ploËice,
{22886}{22986}<i>morat Êu vas,|naûalost, razoËarati.</i>
{23214}{23303}HoÊu njezine telefone,|raËunala, sve Ëime operira,
{23303}{23382}ûelim znati sve, aktivne|prisluökivaËe na svemu öto ima,
{23384}{23495}ûelim pratiti svaki njen korak odsad pa|nadalje. -U Ministarstvu Obrane je.
{23495}{23586}Briga me i da je Bog.|Napravi to!
{23610}{23665}äefice, pogledajte ovo.
{23665}{23759}Nabavili smo ovu fotografiju Pikea|u Kˆnigsbanci u Frankfurtu.
{23759}{23866}<i>Sigurnosne kamere su uhvatile njega|i nepoznatog Arapina kako Ëesto putuju</i>
{23869}{23936}od postaje do banke.|Sve proölog mjeseca.
{23936}{24032}Pike postaje traljav. -Ali ako smo ga mi|uoËili, jesu Smith i njegov tim takoer?
{24034}{24113}<i>Ne, ne, ovo je izvuËeno direktno|iz Pentagonove baze podataka.</i>
{24116}{24185}<i>Nema öanse|da su mogli nabaviti ovo.</i>
{24185}{24288}Mislim da stalno trebamo pretpostavljati|kako imaju viöe informacija od nas.
{24288}{24423}Pike je donosio ploËice u Kˆnigsbank|toranj u Frankfurtu zadnjih mjesec dana.
{24425}{24533}<i>Sutra, kada donese zadnju|ploËicu bit Êe predane Arapu.</i>
{24533}{24655}Ovo Êe biti jedini put u zadnjih 6|mjeseci kako su ploËice na istoj lokaciji.
{24655}{24730}Ovo nam je najbolja|i jedina prilika da ih vratimo.
{24732}{24828}<i>IÊi Êe iz Kˆnigsbank tornja|na vlak u 17:15h za Z¸rich.</i>
{24828}{24933}Gospodo, pobrinut Êemo se|da ne stignu na taj vlak.
{24933}{24984}Faco...|-Da?
{24986}{25051}Vrijeme da povratiö|svoj stari plamen.
{25051}{25159}<i>Ako je dobra koliko mislim da je,|bit Êe u Frankfurtu presresti ploËice.</i>
{25207}{25283}Zaöto bi joj dojavio to?|-Ona je kriûar.
{25283}{25372}<i>Trebat Êemo je pripremljenu.</i>|-Drûite oËi otvorene, deËki.</i>
{25375}{25475}<i>Charisa Sosa, poziv za vas.|Charisa Sosa.</i>
{25475}{25533}Sada problem.
{25535}{25638}<i>Ako Sosa prati nas, moûemo|pretpostaviti da Lynch prati nju.</i>
{25667}{25794}I ako misli da stoji izmeu njega|i ploËica, neÊe oklijevati ubiti je.
{25794}{25866}Faco, idi na|ûeljezniËki kolodvor.
{25902}{25960}Ovdje Sosa.
{25981}{26048}Ako postoji prijetnja od|Lyncha, nosi se s time.
{26051}{26091}Halo?
{26091}{26171}<i>Mogu pucati.|Ponavljam, mogu pucati.</i>
{26171}{26233}Halo?
{26377}{26434}Neöto nije u redu.
{26480}{26559}<i>UoËeni smo, deËki. PovlaËite se.|Ne svia mi se ovo.</i>
{26559}{26621}Vidite, neka vas ne vide.
{26696}{26792}<i>Zdravo, ljepotice.</i> -Imaö muda.|Ubacio si mi telefon? <i>-Morao sam.</i>
{26792}{26868}<i>Jedino sam tako mogao priËati|s tobom. Lynch nadzire tvoj.</i>
{26868}{26940}<i>Moraö odmah povuÊi svoj tim.</i>|-PronaÊi Êu te, Faco.</i>
{26943}{27055}Nemoj iÊi blizu nje, ili nekog drugog.|<i>-Ne ako ja prvo naem tebe.</i>
{27209}{27276}Hajde! Dobro...
{27341}{27398}Isuse!
{27417}{27496}äto to radiö?|-Pokuöavam te spasiti!
{27580}{27633}Charisa...
{27633}{27691}Daj, znaö da smo nevini.
{27693}{27789}Znaö da jesmo. -Laûeö.|Kao öto si lagao u Bagdadu.
{27791}{27861}Nisam... nisam niöta|znao o ploËicama.
{27863}{27923}U tom... U tom trenutku.
{27926}{27986}Pun si govana!
{27988}{28086}Prestani se izvlaËiti.|Ti si lagala meni! -Kad?
{28089}{28156}Daj. éeliö o tome? -Da, ûelim!|-Stvarno ûeliö o tome? -Da!
{28156}{28244}Kad sam se ja igrao, i ti si, a kad|sam postao ozbiljan uplaöila si se!
{28244}{28331}Ja sam se uplaöila?|-Da, jesi! UspaniËarila si se...
{28331}{28400}i pobjegla.
{28530}{28604}Charisa, daj.|Ja sam drûavni bjegunac.
{28607}{28714}Znaö toËno tko sam i öto sam. Misliö da|sam doöao u Frankfurt umiriti stari prekid?
{28714}{28748}Ne.
{28750}{28829}Ovdje sam jer mi to nismo uradili.|Jer nam je namjeöteno.
{28829}{28933}Ovdje sam jer je na|kraju istina vrijedna rizika.
{28976}{29074}I ja vjerujem u tebe,|makar ti ne vjerujeö u mene.
{29172}{29244}Boûe, zaboravio|sam kako si predivna.
{29371}{29431}Zapamti tu misao.
{29709}{29836}<i>O, moj Boûe. On ima piötolj!|Onaj tamo! Ima piötolj!</i>
{29937}{30000}Sranje!|-Gdje je Peck?
{30000}{30059}OdliËno pitanje.|Naite ga!
{30256}{30342}K÷NIGSBANK TORANJ|Frankfurt, NjemaËka
{31757}{31812}Dobro, zapleöimo.
{31812}{31889}Silazimo. Straûa,|pripremite se za pokret.
{31889}{31961}Kao i uvijek ostanite|blizu mene, gospodine.
{32524}{32601}Kako ti ide, frajeru?|<i>-Murdock, stiûe Arapin.</i>
{32601}{32733}<i>DugaËka na lijevu stranu.|Murdock se vraÊa i stigao je do zida.</i>
{32733}{32802}<i>Uhvatio je!</i>
{33351}{33416}<i>B.A, izgubio sam kovËeg!</i>
{33416}{33481}<i>Puca na mene, odlazim!</i>
{33680}{33749}B.A, idi po ploËice!
{35087}{35171}Federalci javljaju o nekoj|pucnjavi kod Kˆnigsbanke.
{35171}{35260}Bjeûi odavde i vodi nas do|te zgrade öto prije. -Da, gospoo.
{35761}{35828}IzmuËio si me|ovog puta, Baracus.
{35828}{35895}Nisam mislio da|sam ispao iz forme.
{35898}{35994}Naûalost, jesam.|Gdje je ostatak tima?
{35994}{36044}Smith, Peck?
{36044}{36125}Onaj idiotski pilot, seronja.|Kako se zove?
{36262}{36344}Ovog puta Êeö se morati potruditi,|Baracus. Da vidimo öto znaö.
{36435}{36516}Hajde. äto to radiö? Jesi umoran?|-NeÊu te ozlijediti.
{36519}{36591}Naravno da neÊeö.|Ja Êu tebe ozlijediti.
{36706}{36797}Ne ûelim te ubiti, stari. -Ne ûeliö?|NeÊeö! Ja Êu tebe ubiti, Baracus.
{36797}{36902}NeÊu se igrati s tobom, Pike. -Idemo.|Imam dva piötolja ovdje, sjeÊaö se?
{36902}{37005}»im mi ruka ode iza, gotovo je.|-Kunem se, uËinit Êu to.
{37005}{37068}Nisi valjda kukavica?
{37070}{37120}Jesi li?
{37269}{37365}Trebaö prijevoz, momËino? -Spasio|si mi ûivot! Nisam ga mogao ubiti!
{37538}{37638}MiËite se s puta!|Dolje, dolje!
{38350}{38437}Da, ovo je pravi|broj policajaca.
{38439}{38523}Slatko. Imaö sreÊe|öto nema ljudi okolo.
{38523}{38597}Ne, duöo.|Ti imaö sreÊe.
{38765}{38849}Jedeö to hladno?|-Kako god mogu.
{38861}{38938}Rupa je u krovu.|-Puno njih.
{38940}{39007}Jesu to oni?|-Ja Êu!
{39084}{39161}Dobro. Arapin|nije ni pisnuo.
{39163}{39235}Sosa je bila na kolodvoru.|-Jesi je vidio?
{39235}{39298}Da.|-Jesi priËao s njom?
{39298}{39393}Nisam imao izbora.|Vjeruj mi. -Vjerujem ti.
{39393}{39528}Da uvijek krivo odluËujeö u vezi ûena.|Koji dio tebe razmiölja trenutaËno?
{39530}{39616}Lynchovi ljudi su joj se pribliûili. Morao|sam reagirati. Zato si me i htio tamo.
{39616}{39739}Da ih zaustaviö. Ne da s njom priËaö.|-Morao sam oboje. -Molim te.
{39753}{39844}Nekako sumnjam u to.|-Zbog Ëega si ti toliko ljut?
{39844}{39923}Dobili smo ploËice. Htio|si je pripremiti. Pripremili smo je.
{39923}{39983}Zna da ih nismo ukrali.
{39986}{40058}Bila bi oduöevljena|saznati tko jest.
{40101}{40153}äto?
{40235}{40316}Morao si znati.
{40415}{40530}Ti si morao znati, kad si me ostavio|ûivoga, da se ovo sprema.
{40669}{40746}Kako nisi?
{40842}{40906}NauËio si me...
{40961}{41029}skoro svemu öto znam.
{41031}{41120}Hannibale, znaö tko je ovo?
{41412}{41487}Svi znamo.
{41534}{41582}Morrison?
{41585}{41671}K vragu, ne.|-Isuse Kriste.
{41698}{41774}<i>Nisam baö siguran|da je blagoslov.</i>
{41777}{41846}Dobar lov, prijatelju.
{41870}{41916}Hvala.
{41916}{41985}KuËkin sine!
{42098}{42170}Morrison.|Jebote!
{42338}{42393}Nisi ti general.
{42393}{42486}Kako si mu to|mogao uËiniti? Nama?
{42508}{42565}Ne znaö niöta o voenju ljudi.
{42565}{42633}Znao sam, ako mi je|Lynch pomogao pobjeÊi,
{42635}{42705}ti si morao biti dio toga.
{42724}{42808}Ti i Pike ste planirali ukrasti|one ploËice s Lynchom,
{42808}{42894}a vi ste ga izdali.|Kako si nas izdao.
{42894}{42971}Lynch nas nikada|nije mislio ukljuËiti.
{43009}{43079}Mislio nas je iskoristiti.
{43081}{43141}Ubacio je tebe kao osiguranje.
{43143}{43242}Nije mislio da Êeö izdati|najstarijeg prijatelja.
{43244}{43347}Ja sam prvi udario, Hannibale.|Borac sam. -Ne, ti si laûljivac!
{43347}{43414}Izdajica! -Onda ne|odugovlaËi ovo! Ubij me!
{43414}{43477}FantastiËna ideja!
{43515}{43580}äefe, dopusti mi ovo. -Faco.
{43596}{43673}NeÊu nikog ubiti.|-NeÊeö, Bosco.
{43673}{43791}Ja Êu. -äto god rekao, nemoj|ga ubiti. -Ne ûelite gledati?
{43791}{43879}Okrenite glave. -NeÊu biti ni|dio toga! -I ja ga ûelim ubiti,
{43879}{43966}ali on nam je karta za izlazak. -Jednom|zna o Ëemu priËa. Posluöaj ga!
{43966}{44069}Faco, on nam je jedini dokaz!|-Murdock! On nas je doveo ovamo!
{44069}{44169}Moûeö mu raznijeti glavu nakon|svjedoËenja. -Uniötio je sve!
{44169}{44282}Razmisli öto Ëiniö! -Dobro. -Ako|ne moûeö podnijeti... -DeËki, dosta!
{44342}{44455}Dosta! Faco, dosta je bilo!|Odstupite! Svi van!
{44455}{44565}Ne ûelim da ti to|moraö uËiniti. -Faco, van!
{44565}{44647}Odstupi, vojniËe! Faco! Odmah!
{44800}{44877}Znao si da se Morrison maskirao kao|Arapin. Zaöto nam to nisi rekao?
{44879}{44951}<i>Nisam bio sto posto|siguran.</i> -A 99?</i>
{44951}{45028}Jesi pomislio da je|tada vrijedno spominjanja?
{45028}{45081}Lynch, öto si ti mislio?
{45081}{45150}<i>Mislio si da Êu ga ubiti na mjestu?</i>|-Bio sam siguran u to.</i>
{45150}{45222}Joö uvijek jesam.|<i>Imaö li ploËice?</i>
{45224}{45277}Ne bih te zvao da nemam.
{45277}{45335}Smith... Vrati ploËice.
{45337}{45399}Ubij Morrisona i|vratite svoje ûivote.
{45402}{45471}HoÊu potpisana|i odobrena pomilovanja.
{45474}{45539}Za mene i svakog|od mojih ljudi.
{45539}{45634}<i>Od Bijele kuÊe,|MVP-a i Zdruûenog stoûera.</i>
{45637}{45697}»ujeö?
{45730}{45800}Trebat Êe mi joö malo vremena.
{45802}{45865}Koliko?
{45977}{46059}Daj mi 5 minuta.|-»ekam.
{46287}{46356}<i>Zar ne shvaÊaö Hannibale?
{46370}{46486}Borimo se za njih,|krvarimo, umiremo, briga ih!
{46486}{46632}Smrt i uniötenje, prodaju ih kao|na trûnici! -Ne svaljuj ovo na njih!
{46632}{46766}Nisu oni u pitanju! Tvoj ratni|protest je krao milijarde dolara!
{46795}{46886}Tko si ti? -Ja sam|general. Ti si pukovnik.
{46886}{47006}Ja kaûem "SkaËi!", a ti "Koliko|visoko?" Kraj priËe. -Sada jeste.
{47085}{47171}Vidio sam tvoj|grob u Arlingtonu.
{47171}{47270}<i>Umro si kao|drûavni heroj.</i>
{47555}{47608}Smrt je prelagana.
{47608}{47711}A zadnje öto trebamo je joö jedna|laû. -Nemoj to raditi, Hannibale.
{47713}{47802}Dugujeö mi toliko.|-Ti dugujeö meni!
{47802}{47883}ReÊi Êeö im da smo nevini.
{47900}{47965}Zar ne?
{47965}{48027}Hannibale, besmisleno je.
{48030}{48169}Za Ëega se sad boriö?|Ti i oni deËki? »in? Uglede?
{48171}{48257}<i>Sranje su!|Vi ste osuenici!</i>
{48257}{48339}<i>S ploËicama ili bez|vi ste drûavni bjegunci,</i>
{48339}{48449}<i>a kad zavröe s vama Hannibale,|jednostavno Êe vas izdati.</i>
{48452}{48550}Zulu-1, Zulu-1, ovdje äiroki maË,|moûete napasti.
{48550}{48607}äiroki maË,|sam si to smislio?
{48610}{48655}Zakon!
{48655}{48715}äiroki maË...
{48768}{48838}äefe, moûeö li to napraviti?
{48876}{48924}Nama?
{48926}{48993}äto je Morrison|napravio? -Ne!
{48993}{49053}Ni za milion godina.
{49070}{49190}Ali nisi to predvidio. -Koliko dugo|si znao da je on? -Jeste ludi?
{49190}{49281}Znam da ti jesi,|ali, Faco, optuûujeö ga?
{49339}{49427}Radije bih stao pred|streljaËki vod nego izdao vas.
{49427}{49475}Ne dajte da nas ovo razdvoji.
{49475}{49583}Ne sada. Kada trebamo jedan|drugoga kao nikad prije.
{49710}{49766}Pokret!
{50068}{50108}To je zakon!
{50111}{50171}Izgleda baö kao|Call of Duty, zar ne?
{50171}{50276}Dobro, ovako Êemo: Bez novina,|drûite tamoönju policiju i medije podalje.
{50279}{50339}5 km radijus. Bez letova.
{50339}{50461}Poöaljite agencijski tim za ËiöÊenje,|i vratite mi te vraûje ploËice.
{50480}{50595}NjemaËka policija drûi tvoj cijeli|tim zatoËen u Kˆnigsbank tornju.
{50631}{50693}Ja nemam tim,|to je Smithov naËin.
{50693}{50761}Ja radim sam.
{50924}{50991}<i>AMBASADA SAD-a|Putujem s malo opreme.</i>
{50991}{51101}Neöto kao odanost|mi baö ne odgovara.
{51135}{51218}Mislila sam da ti i|Smith radite zajedno.
{51218}{51338}Pogreöno si mislila. -Da, imamo|oruûje. Ne, ne moûeö nas pregledati.
{51389}{51458}<i>HoÊeö se dogovoriti?|Moûemo se dogovoriti.</i>
{51461}{51566}äto kaûeö da posvetim|svoju nadolazeÊu buduÊnost...
{51583}{51640}uniötavanju tvoje?
{51643}{51700}äto kaûeö da se ti opametiö...
{51700}{51753}i da se poËnemo dogovarati?
{51753}{51820}Prije nego netko drugi poËne.
{51849}{51904}Bivöa satnice.
{51931}{52000}Osim ako nemaö papir|koji izgleda ovako
{52000}{52106}onda ovaj problematiËni|mladiÊ pripada meni. Idemo.
{52122}{52194}Kako su dobili ovaj zahtjev?|-éao mi je, Pike.
{52197}{52273}Sa mnom je barem bilo pravila.|-CIA ima pravila.
{52273}{52336}Naöa su samo|bolja od tvojih.
{52336}{52420}Kreni! -Lynch, kad bih mogla|zatvoriti ovu sobu s tobom unutra
{52422}{52477}uËinila bih svijetu|veliku uslugu.
{52480}{52520}To nije lijepo.
{52523}{52595}Lynch?|-Vjerojatno.
{52595}{52647}DeËki, ostanite blizu vatre.
{52647}{52736}Ako se oni avioni zadrûe neÊe|oËitati toplinu naöih tijela.
{52736}{52846}Glupi Lynch. Nije nas mogao ni|ubiti. Niti je potraûio ploËice.
{52846}{52938}Kako stojimo s|nenasiljem, B.A? Jesi ljut?
{52940}{53000}Naravno da je.|Koga briga za ploËice?
{53000}{53096}Morrison je bio jedini koji nas je mogao|osloboditi. Bez njega nemamo niöta.
{53139}{53206}äto Êemo, öefe?|-Ne znam, Murdock.
{53209}{53285}Ne znam.|-Ja znam.
{53307}{53398}Taj Lynch... Mislim|da sam ga shvatio.
{53398}{53484}Imaö plan, mali?|-Kako Êemo otiÊi odavde?
{53484}{53559}Dajte mi 20 minuta.
{53642}{53724}Morrison je mrtav.|Smith i njegov tim su mrtvi.
{53724}{53834}Za 15-ak minuta dobit Êemo|ploËice. -Ti to likujeö?
{53834}{53925}Ne, nego sam te pobijedio.|Nakon öto si me izdao.
{53925}{54002}Imali smo dogovor, sjeÊaö se.|-Ne ja i ti. -Ti, ja i Morrison?
{54002}{54100}Ne ja i ti izravno. -Vas|dvojica ste me izbacili i uzeli plijen.
{54141}{54227}Hej, öto to radiö. U autu smo.|-U autu Êemo ovo obaviti?
{54227}{54283}Napravit Êe to.
{54283}{54350}Bravo. Savröeno.
{54350}{54443}äto to on radi? Isuse!|-Kako ide, Kyle? Jesi dobro?
{54446}{54534}Dobro je. -Daleko si ti|od dobroga. äto to radiö?
{54534}{54654}Stavljam priguöivaË. -To je kompenzator|trzaja. Ide suprotno od kazaljke na satu.
{54654}{54755}Tako drûiö piötolj? Tako si prije drûao|piötolj, a joö si ûiv? Nevjerojatno!
{54755}{54856}Posljednja ûelja: Ne daj|ovome da me ubije. Molim te.
{54997}{55103}Ako Sosa zna da smo ûivi...|-Vjerovat Êe da je i Morrison ûiv.
{55103}{55189}Nadajmo se da je Lynch|joö uvijek prisluökuje.
{55251}{55292}Ovdje Sosa.
{55292}{55364}<i>General Morrison|je kod mene.</i>
{55364}{55462}äto? Oprostite.|Ne Ëujem vas. Tko je to?
{55462}{55529}Dobro, ovo nije baö dobro|smiöljeno. -Nemoj zajebavat'!
{55532}{55606}Pogledaj ovo. Moram vas uËiti|kako me ubiti? UËini mi uslugu.
{55606}{55700}Uperi cijev. Uperi piötolj u|moju glavu. -Sigurno? -Tako je.
{55700}{55793}HoÊe to proÊi? -Prije nego|ozlijediö nekoga osim mene.
{55793}{55846}Evo ga. Dobro je, dobro je.
{55848}{55959}Nikad ne stavljaj lisice Ëovjeku|iza lea. Ne moûeö vidjeti ruke.
{55961}{56021}To je bilo cool.|-Svidjelo ti se?
{56023}{56078}Svidjelo mi se.|Jako mi se svidjelo.
{56081}{56191}Jesi dobro, idiote? -Da, dobar|udarac. -Molim te, veûi ga.
{56191}{56270}Ne moramo ih koristiti.|Ne trebamo lisice. -S kime priËaö?
{56270}{56349}Brad, telefon ili piötolj.|Izaberi. -Isuse!
{56349}{56455}Spusti piötolj. -Nisam|te ja zeznuo. Morrison je.
{56455}{56532}Stvarno te ûelim ubiti.|-Morate Ëuti ovo, gospodine.
{56532}{56642}<i>Je li to Smith? -Kao bivöi|pukovnik bivöoj satnici,</i>
{56642}{56740}<i>znam da imam 30 sekundi prije|nego locirate ovaj signal, zato sluöajte.</i>
{56740}{56798}<i>Moûemo dokazati|naöu nevinost.</i>
{56800}{56918}Dobro, vratite se malo. Rekli ste da|imate Morrisona? Generala Morrisona?
{56918}{56999}Tako je. <i>-Imate ga ûivog?|-I zdravog.</i>
{56999}{57081}<i>UnatoË tome öto nas je|Lynch htio potamaniti.</i>
{57081}{57169}Previöe za objasniti sada, ali|Morrisonovo svjedoËenje oslobaa nas
{57172}{57244}<i>i ukopava Lyncha.</i>
{57296}{57388}Ali ne bez ploËica.|<i>-Takoer su kod mene.</i>
{57390}{57455}Zapamti, Lynch|misli da smo mrtvi.
{57457}{57510}éelim da tako ostane.|-Daj mi olovku.
{57510}{57649}<i>Trebat Êu kad i gdje...</i> -Olovku. -Joö ih|koristiö? <i>-L.A. dokovi. 48 sati. Zora.</i>
{57651}{57716}<i>Dovest Êu Morrisona i ploËice.</i>
{57716}{57822}Za uzvrat, ûelim ponovno|suenje pred civilnim sudom.
{57824}{57884}<i>Dobro.|Dogovoreno.</i>
{57884}{57946}L.A. dokovi. Za 48 sati.
{57946}{58049}Nekakvo sranje s vaöe strane|i to je to. Dogovor otpada.
{58092}{58169}Jesmo ih naöli?|-Ne.
{58220}{58263}Pike...
{58263}{58318}Vjerujeö u druge prilike?
{58361}{58409}Sada vjerujem.
{58409}{58495}Previöe?|-Ne, dobro je.
{58538}{58608}Moj red.
{58831}{58893}Zapamti tu misao.
{59080}{59164}Ovdje Sosa.|<i>-Zdravo, ljepotice.</i>
{59402}{59538}Oni su izvukli deblji kraj, zar ne? Pogledaj|B.A.-a. Izgleda kao ogromna banana.
{59538}{59605}Dobro jutro, prijatelju.|-Dobro jutro.
{59730}{59812}Rabin Binky Rabinowitz?
{59860}{59924}Koju sam ti putovnicu dao?|-Vi ste iz Tanzanije?
{59927}{60003}Moja majka je iz Tanzanije.|-Sranje! äto se dogodilo?
{60219}{60286}PreobraÊam se na judaizam.
{60313}{60440}Budi spreman na pokret. Tri su mi s desna.|-Dva iza mene i jedan na SI-om izlazu.
{60802}{60879}Zar mu Murdock priËa|svoju ûivotnu priËu?
{60936}{61013}Ima Boga. -On priËa|svahili? -Gotovi?
{61034}{61101}Imaö dovoljno za rad,|mali? -Imat Êemo.
{61104}{61190}Tebi i meni trenutaËno dolaze neke|ogromne usluge preko Atlantika?
{61190}{61265}Trajekt koji prenosi iskljuËivo|robu s crnog trûiöta.
{61265}{61348}Kako Êemo doÊi do njega?|-Dobri stari brodovi.
{61348}{61423}O tome priËam, Murdock,|o putovanju preko mora stilom.
{61425}{61502}Ovo je pravi naËin putovanja.|KlasiËan. Cool. Siguran.
{61504}{61612}Znaö Bosco, moûda jednog dana|savladaö svoj strah od letenja.
{61653}{61718}To nije brod!
{61754}{61821}Samo ne danas.|-Murdock.
{61823}{61895}Zaboravio si öto sam ti rekao.|Rekao sam moraö ga uhvatiti
{61895}{61962}nakon öto mu ubrizgaö.
{62001}{62051}Moja greöka.
{62674}{62720}K vragu!
{62720}{62775}Moja glava!
{62828}{62919}Curry. Tvoje|omiljeno. -Daj mi to.
{62921}{62976}Imaö i tost?
{63017}{63068}Tost.
{63101}{63187}Opet ste me uspavali,|ha? -Dobro...
{63187}{63307}»itavo ubrizgavanje,|uspavljivanje: Hannibal i Faca.
{63307}{63389}Curry: Murdock.
{63389}{63466}Zaöto imam osjeÊaj|da sam pao na lice?
{63490}{63540}Reci mi to.
{63612}{63691}Lynch je paradoks.|Murdock, jesi zavröio?
{63693}{63816}On je tip koji treba potvrdu|drugih, ali voli teatralnost.
{63840}{63923}On je administrativac,|ne operativac.
{63979}{64027}Gdje je?
{64053}{64106}Vrlo lijepo.
{64106}{64182}<i>Zato ostaje öto je|dalje moguÊe od toËke udara.</i>
{64185}{64276}<i>I nikad ne prlja ruke ako|ne mora. Ali mi Êemo to promijeniti.</i>
{64278}{64350}Ne moûeö prevariti|varalicu, ludo.
{64369}{64504}Nema ûara, plamena Ëak ni|baterija. Pogledaj ovo. -Polako.
{64537}{64631}<i>On nikada nije|bio na Ëelu neËega.</i>
{64676}{64763}<i>Siguran je negdje|gdje povlaËi konce.</i>
{64818}{64969}Hej, öefe. äto Êe nam ovoliko ovoga?|-Jer je pretjerivanje podcijenjeno.
{64998}{65074}<i>Dovest Êemo ga|u prve redove.</i>
{65113}{65180}<i>Lynch...</i>
{65180}{65261}<i>Zadnje mjesto|gdje bi ûelio biti.</i>
{65312}{65415}I izloûite ga,|da ga Ëitav svijet vidi.
{65415}{65484}Pitanja?
{65535}{65614}ä'a ima, öefe?|-Hej, B.A.
{65614}{65676}Bit Êe teöko, zar ne?
{65710}{65794}Pa, ne mogu ti obeÊati da neÊe.
{65794}{65851}ProËitat Êu ti|neöto na brzinu.
{65851}{65911}"Pobjeda dobivena nasiljem,
{65914}{66026}jednaka je porazu|jer je trenutaËna."
{66055}{66108}Ghandi.
{66108}{66204}"Bolje je biti nasilan|ako nam je nasilje u srcu,
{66204}{66316}nego obuÊi plaöt nenasilja|i prekriti nemoÊ."
{66345}{66400}Tko je to rekao?
{66400}{66551}Isto on. Ghandi se nije bojao|boriti za ono u öto je vjerovao.
{66554}{66640}U öto ti vjerujeö, B.A.?
{67036}{67163}"Jer ûivot je opera..."
{67247}{67309}Ne valja, zar ne?
{67309}{67369}Mislim da ide viölje.
{67407}{67494}Ne, dobro je.|-Faco, öto je?
{67494}{67568}Ma samo razmiöljam o ovome.
{67568}{67621}Ovo je...
{67621}{67712}Uvijek smo se vraÊali ûivi.|Nas Ëetvorica.
{67712}{67796}Zbog staroga.|-Znam. -Ja nisam on.
{67796}{67856}Faco, znam to.|-Murdock...
{67856}{67913}Ja nisam Hannibal.
{67913}{67997}Tko ima najviöe|izgubiti u ovome, Faco?
{67997}{68050}Ja.
{68069}{68136}A ja ti vjerujem.
{68136}{68203}Znam, ali...
{68225}{68282}Ti si lud.
{68371}{68450}Ne toliko lud.
{68630}{68712}LOSAN–ELESKA LUKA
{68848}{68915}<i>Naöi orlovi su moûda|sletjeli. Svi spremni?</i>
{68915}{69021}<i>Primljeno. Tim 1 u pokretu.|-Primljeno. Tim 2 na putu.</i>
{69157}{69244}Dobro deËki.|Svi spremni?
{69244}{69325}Podiûemo zavjesu.
{69325}{69385}Vrijeme za öou.
{69508}{69570}To je Smith tamo!|Pratite ga!
{69589}{69668}<i>Timovi na poziciji?|-»ekamo.</i>
{69711}{69774}Na poziciji.
{69795}{69846}PucaËki tim 1, potvrdno.
{69848}{69906}501, 10-8.
{69906}{69989}Zasad samo priËajmo.|Morrison je primarna meta.
{69989}{70052}PloËice su paket.
{70052}{70093}Da?
{70095}{70169}<i>Dobro, priËa sa Sosom.|éelim taj poziv!</i>
{70169}{70270}Lagala si nas! Imali smo dogovor!|-éelim taj vraûji poziv! Hvala.
{70272}{70332}<i>Imali smo dogovor,|ali mijenjam dogovor.</i>
{70332}{70445}<i>Zezaö me, Sosa?! Zezaö me?! -Ovo je|komplicirana razmjena i nema igranja.</i>
{70445}{70531}<i>Sluöajte ili ostanite|glavni bjegunci do daljnjega.</i>
{70531}{70620}Zaboga, Morrison je|ovdje. Imam ploËice.
{70620}{70721}<i>Izloûen sam, Sosa. Izloûen!|-NeÊemo to raditi na dokovima.</i>
{70723}{70814}Sluöaj me, neÊemo se predati.
{70817}{70920}<i>Morate to uËiniti pod mojim uslovima ili|nikako. -Nosi se s time, i nosi se ti.</i>
{70920}{71008}Ispalila ih je.|<i>-Faco, B.A., povlaËimo se.</i>
{71011}{71071}<i>Sosa nas je zeznula.</i>|Murdock?</i>
{71073}{71126}Dovezi helikopter na desetu.
{71167}{71222}Krenuo je.|<i>Vidiö ga? Krenuo je.</i>
{71222}{71296}Za boga miloga, opusti se.|<i>-Opuöten sam.</i>
{71323}{71418}Nemoj to raditi Hannibale, molim te.|-To je Morrison. Skinite ga!
{71418}{71519}Ima li ploËice? -Smith ima ploËice.|-Naciljao sam Morrisona. Pucam!
{71605}{71673}<i>Malo preblizu, mali.</i>
{71673}{71749}äto se dogodilo?|-äto to on radi?
{71749}{71843}<i>Gdje su? Netko, recite mi.|Jesu zdrobljeni ili öto je?</i>
{71874}{71960}Ovo je bilo puno laköe|s tri plastiËne Ëaöe.
{72042}{72128}<i>Svi ostanite mirni.</i> Obratite|pozornost, <i>bez naglih pokreta.</i>
{72159}{72255}<i>Pobijedit Êeö tipa kao öto je|Lynch ako mu pruûiö tri stvari:</i>
{72255}{72332}äto to oni rade?|-Distrakciju...
{72385}{72445}<i>äto se dogaa?!</i>
{72485}{72550}Diverziju...
{72644}{72711}Ovo je diverzija!|Pratite kontejnere!
{72711}{72771}<i>Traûe izlaz!|Pucajte!</i>
{72773}{72845}Ne pucajte!|Stanite! Ne pucajte!
{72939}{73001}Jebote!
{73109}{73195}U napad! -Smith se|poigrava s tobom.
{73195}{73262}<i>Pokuöava ti odvuÊi paûnju.|Daj, Lynch, budi pametan.</i>
{73262}{73322}Sredite ih! Sredite!
{73361}{73454}<i>Kontakt! Iznad|vas je. Ima rakete!</i>
{73605}{73660}I djelidba.
{73660}{73778}KlasiËan... PovlaËenje, povlaËenje!|Bjeûite odatle! -Ne, ne...
{73919}{73993}äto se dogaa?|äto se dogaa?
{73993}{74068}<i>Dobar plan, mali.|-Napuni rakete!</i>
{74068}{74152}Upucaj ih! -äuti, znam öto|radim. -Dobro, paintbaleri...
{74154}{74221}Vrijeme za prelazak na profiÊe.
{74248}{74312}B.A, prijei na|sekundarnu poziciju.
{74339}{74447}Dobro, mijenjamo igru.|Evo öto mislim o vaöem planu.
{74622}{74715}Isuse Kriste! -Toliko o|velikoj prijevari, Smithe.
{74718}{74790}<i>äto je to bilo?|-Faco, öto je to bilo?</i>
{74790}{74873}<i>Pike je pogodio brod!|Napravio je rupu u trupu!</i>
{74873}{74969}äto je s planom? <i>-Pike je upravo|uniötio plan! Prevrnut Êemo se!</i>
{74972}{75044}Bosco, bjeûi odatle!|-Idem po Hannibala!
{75058}{75130}Pokrivajte me. Idem po|ploËice! -Da, gospodine.
{75221}{75283}Bosco, bjeûi odatle!
{75283}{75346}äefe, drûi se!
{77959}{78045}<i>Bosco, Pike je iznad.|Ponestaje mi municije.</i>
{78338}{78405}Sranje!|-Kako je, zgodni?
{78429}{78494}Kako se ti ne znaö|koristiti oruûjem. Bravo!
{78496}{78571}Bliski prijatelji i meci.|Gdje su kad ih trebaö?
{78652}{78731}Nemoj ovo shvatiti osobno,|ali... pogledaj ovamo.
{78731}{78796}Nasmijeöi se, Ëekaj blic.
{78861}{78909}Baracus!
{79163}{79220}Bosco!!!
{79513}{79570}<i>Lynch...</i>
{79623}{79678}<i>Lynch...</i>
{79825}{79884}<i>Doi, Lynch...</i>
{80043}{80112}Daj, Smith,|prestani se zajebavati!
{80112}{80177}<i>Lynch, doi, Lynch.</i>
{80273}{80347}<i>Lynch! Gdje sam?</i>
{80431}{80486}<i>Doi, Lynch...</i>
{80582}{80630}<i>Gdje sam, Lynch?</i>
{80683}{80762}<i>Lynch, Lynch, Lynch...</i>
{80817}{80865}Lynch!
{81220}{81318}Tu si, Hannibale!|Svuda sam te traûio.
{81318}{81424}Neka te oûiljak ne zavara.|Moralna naËela su dobra.
{81426}{81484}Moj jiu-jitsu je|malo bolji, ali...
{81484}{81625}Imao si... tu neku prednost sa|kontejnerima i autima, vatrometom...
{81628}{81687}Lynch, Lynch, Lynch...
{81690}{81745}Boûe, kako je to iritantno.
{81747}{81831}Ali daj Pikeu raketu...
{81831}{81903}I pokvariö svima planove.
{81903}{81990}Hannibale, nemoj to uËiniti.|-Znaö, Smith, moûeö imati najbolji...
{81990}{82097}recept na svijetu. -Dugujeö mi toliko.|-Ali ubaciö par metaka u smjesu...
{82097}{82155}Hannibale, ne Ëini to.|-Lynch, nemoj!
{82249}{82316}I ta torta se neÊe ispeÊi.
{82316}{82364}Tvoj svjedok, tvoj piötolj,
{82364}{82407}tvoj problem.
{82467}{82536}Dobro si sluûio|svojoj zemlji. Oprosti.
{82673}{82764}Zdravo, Bene.|Gdje si bio Ëitav moj ûivot?
{82795}{82874}Koji vrag?|äto to radiö, ËovjeËe?
{82877}{82937}Krvarim.|-Krvariö?
{82937}{83006}Nemoj ustajati.
{83148}{83203}K vragu!
{83205}{83287}Moralna naËela su ti loöa|kao i tvoj jiu-jitsu, Lynch.
{83318}{83368}Bolje se drûi piötolja.
{83368}{83426}Stavi mi napunjeno|oruûje u ruku,
{83426}{83500}ja Êu tebi metak u glavu.
{83831}{83903}Rekao sam da Êu te upucati.
{83903}{84037}Pancir ti je spasio ûivot. No, neÊe|puno koristiti ako te upucam u glavu.
{84037}{84128}HoÊe, ako ga iskaliö.
{84128}{84198}Hannibale, nemoj to raditi.|Hannibale, molim te.
{84198}{84282}Pobijedit Êeö tipa kao öto je|on ako mu pruûiö tri stvari:
{84282}{84378}<i>Distrakciju...</i> -äto se|dogaa? <i>-Diverziju...</i>
{84399}{84450}I djelidbu.
{84507}{84625}<i>Onda ga izloûiö,|da ga svi vide.</i>
{85071}{85121}Dobro je.
{85159}{85214}Iznenaenje.
{85234}{85281}Agente Burris?
{85281}{85387}Kako ste me nazvali? -Agent|F. Burris, tako se zovete, zar ne?
{85387}{85452}<i>Barem to ime imam|na ovom nalogu.</i>
{85454}{85569}Osim ako nemate papir|koji izgleda isto kao ovaj...
{85569}{85653}Smijeöno. To sam|i ja rekao. Citira mene.
{85742}{85845}Uhapöeni ste za pokuöaj ubojstva,|klevete protiv vladinih sluûbenika,
{85845}{85936}i pokuöaja krae tajnih vladinih...|graviranih tiskovnih ploËica.
{86030}{86082}Izgleda da je plan uspio,
{86085}{86166}s obzirom da je Pike raznio brod,|jer nisam raËunao na to.
{86166}{86207}Meci nisu proöli.
{86281}{86334}Kako se osjeÊaö, stari?
{86334}{86382}Ne dobro.
{86425}{86480}OsjeÊam se razuman.
{86480}{86591}Trebao sam te davno pogoditi u glavu.|-Je li ludo öto osjeÊam vaöu nervozu?
{86593}{86655}Izgledam li vam nervozno?
{86655}{86706}Mislite da sam poraûen?
{86706}{86840}Krvarim, ne znojim se. -Odvedite|ga, deËki. Idemo, princezo.
{86929}{87041}<i>Koja je razlika izmeu|potresa mozga i nagnjeËenosti?</i>
{87041}{87180}To je bilo predivno. Imao si pravo.|Kaciga je djelovala. Hapöenje uspjelo.
{87209}{87269}Odradio si dobar|posao. Jesi dobro?
{87269}{87403}Pao si krivo? -Neka Hannibal|smiölja planove slijedeÊeg puta.
{87403}{87451}Dobro.
{87451}{87509}Kako savjest, momËino?
{87528}{87581}Mirna.
{87806}{87864}Ostavi ga upaljenog.
{87943}{88017}Tko je od vas Sosa? -Ja sam.|-PoruËnik Sosa. -Ja.
{88020}{88089}Od ovog trenutka vaöi zatvorenici|prelaze u federalni pritvor.
{88089}{88156}Imam nalog za ovog Ëovjeka.|-Od ovog trenutka...
{88159}{88264}Daj da ti pomognem. Trebaö|öavove? Reci mi da ih trebaö.
{88264}{88329}Mogu te jako dobro zaöiti.
{88329}{88370}Gospodo...
{88410}{88561}CIA vjeruje u poboljöanje moralnih naËela|kao i u Ëvrste profesionalne standarde.
{88561}{88629}S time ûelimo vam iskazati...
{88631}{88712}naöe najiskrenije isprike za|ovo öto se dogodilo ovdje.
{88734}{88780}Ugodan dan i|Bog vas blagoslovio.
{88780}{88832}Gdje ga vodite?
{88864}{88909}Koga?
{89010}{89067}Niste nam rekli ime.
{89106}{89214}Moje ime je Lynch.|-Naravno da jest?
{89290}{89355}Je li on to rekao Lynch?
{89760}{89827}Provjeri mu tablice.
{89923}{90029}PoruËniËe. -Gospodine, kad ste stigli?|Nisam znala. -Samo malo. -Da, gospodine.
{90197}{90290}To je veliki nered.|Ali dobili smo ploËice.
{90309}{90417}Naûalost, morat Êu vas sve|optuûiti za bijeg iz pritvora. -äto?
{90417}{90482}Hannibale, o Ëemu on priËa?|-Nepravedno smo osueni,
{90482}{90547}ali je joö uvijek nezakonito|pobjeÊi iz zatvora.
{90547}{90628}Direktore McCready, Smith i njegovi|ljudi su bili zasluûni za povratak ploËica.
{90628}{90703}Oni su osueni bjegunci,|a ja se toga trebam rijeöiti.
{90703}{90765}Ovo je sranje, gospodine.
{90767}{90844}Da, moûda za njih jeste sranje,|ali za vas, satniËe...
{90844}{90890}VraÊamo vam vaö stari Ëin.
{90890}{90983}Njih Êemo poslati maröalima i ove|godine Êe biti na Long Beachu...
{90985}{91081}ShvaÊam, ali, gospodine.|-Ovo moramo napraviti!
{91271}{91331}Idemo, pokret!|-Stanite, Ëekajte!
{91379}{91501}Ovo je pogreöno. -Ne brini. -Napravljena|je pogreöka i ja Êu je ispraviti.
{91527}{91614}Znam da hoÊeö.|-éao mi je, Faco.
{92448}{92503}Dobar plan, Faco.
{92503}{92599}Da, zamijenili smo Lynchove|i vraÊamo se u zatvor.
{92599}{92676}Vratili smo ploËice, moûemo iÊi|podignute glave. UËinili smo pravu stvar.
{92676}{92752}Da, a oni su nas zatvorili.|Ovo je sranje!
{92752}{92812}Opet su nas zeznuli, Hannibale.
{92812}{92880}Vjerovali smo sustavu, a|on se okrenuo protiv nas.
{92880}{92954}Ne zaboravite, deËki, koliko|god se stvari Ëinile nasumiËnima,
{92956}{93004}uvijek postoji plan.
{93004}{93067}Mali...|-Pa...
{93069}{93150}Ne ûelim ti ukrasti|uzreËicu, öefe, ali...
{93323}{93390}Volim kad plan uspije.
{93508}{93558}<i>Vlada ih joö uvijek traûi.</i>
{93560}{93635}<i>Preûivjeli su kao plaÊenici.</i>
{93676}{93743}<i>Ako imate problem...</i>
{93743}{93807}<i>Ako nitko drugi|ne moûe pomoÊi...</i>
{93810}{93877}<i>I ako ih moûete pronaÊi...</i>
{93877}{93927}<i>Moûda vi moûete angaûirati...</i>
{93927}{94009}ALFA TIM
{94034}{95534}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
