{1}{1}25.000
{26}{176}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{972}{1033}Toledo - 1580 ad
{1379}{1425}Ne radite to, Domenikos.
{1451}{1501}Ne morate to da radite.
{1525}{1582}Ne radi iste greöke.
{1596}{1632}SaËuvaj sebe.
{1638}{1714}Zar ne vidiö?|Dajem ti öansu da budeö spasen.
{1722}{1754}Vaöa poslednja öansa.
{1778}{1883}Sve öto treba da uradite,|je da naslikate moj portret.
{1922}{1948}Ali...
{1990}{2029}VeÊ sam naslikao.
{2048}{2153}Da, ali|voleo bih da to uradite ponovo.
{2170}{2227}äta kaûeö?
{2260}{2306}VeÊ imate vaö portret.
{5092}{5156}Zovu me El Greko.
{5242}{5297}Ja sam slikar i...
{5397}{5426}Ne!
{5606}{5702}Piöem o dogaajima|koji su oblikovali moj ûivot...
{5708}{5772}...jer sutra je mom ûivotu,moûda,kraj.
{5833}{5884}Moûda Êe me spaliti na lomaËi.
{5917}{6014}Ja sam Domenikos Teotokopulos.
{6058}{6091}Roen sam na Kritu.
{6410}{6470}Brûe! Kasnimo!
{6545}{6620}Ne shvatam öta radiö|pa stalno kasnimo
{6763}{6804}Zdravo Nikolo!
{6812}{6851}Zdravo Maestro!
{6860}{6919}Koje ste anele slikali|ovog puta Maestro?
{6926}{6975}Doi da popijeö sa nama|Mi Ëastimo!
{7077}{7131}Dole! Dole droljo!
{7258}{7328}ZnaËi radiö cele noÊi?|Znam tu vrstu "posla".
{7359}{7395}Zdravo veliËanstvo od Krita!
{7417}{7455}U tvoje zdravlje!
{7737}{7832}Prolaz za Njegovo|VisoËanstvo guverner Krita...
{7838}{7939}...i njegovu Êerku|Groficu FranËesku.
{7971}{8026}Krit je|u venecijanskom posedu...
{8037}{8128}...Ali sam bio mlad i duboko|u sebi oseÊao sam se slobodan...
{8174}{8285}...i sanjao sam i putovao|slobodan, kao i moji preci.
{8329}{8458}Mi smo se KriÊani|uvek odupirali napadaËima...
{8479}{8548}...ali nikad nismo izgubili|i smisao za humor.
{8592}{8660}Ipak je bilo vrlo vaûno|da se zaradi za ûivot.
{8969}{9019}Njegovo visoËanstvo|vojvoda Da RIMI.
{9800}{9863}Maestro Domenikos Teotokopulos.
{10127}{10179}ipak morao sam da priznam...
{10189}{10268}...naö okupator je postao|opasno zavodljiv u poslednje vreme.
{10278}{10313}Hvala, visoËanstvo.
{10326}{10379}Aukcija poËinje.
{10391}{10415}»etiri stotine.
{10423}{10446}»etiri stotine.
{10454}{10494}FranËeska Da RIMI.
{10502}{10537}∆erka Vojvode.
{10557}{10615}Razmaûena...
{10626}{10716}...arogantna, lepa i|zbog toga...
{10726}{10795}...sto puta viöe opasnija|od njenog oca.
{11168}{11199}Pet stotina.
{11205}{11234}Pet stotina.
{11279}{11314}Gospoda Kallergis.
{11326}{11355}äest stotina.
{11375}{11410}äest stotina.
{11426}{11475}KupiÊu tri slike po toj ceni!
{11847}{11873}Hiljadu!
{11904}{11933}Jesi li luda?
{11973}{12049}Njen otac je bio|guverner Krita...
{12068}{12129}...i mogu zamisliti|kako se oseÊao.
{12176}{12247}Ne samo da ga|je odvukla na aukciju...
{12259}{12329}...veÊ ga je|naterala da kupi moju sliku...
{12337}{12371}...i to po visokoj ceni.
{12376}{12442}To nije vaö novac. Zaboravljate|naslee moje majke.
{12451}{12481}Nemaö ga, joö.
{12498}{12580}Uostalom koga briga|ko Êe vas napasti!
{12586}{12643}Da li Êe napad to nadoknaditi?
{12718}{12774}äta god je FranËeska poûelela...
{12779}{12815}...FranËeska je dobila.
{12826}{12917}Ovaj put, meutim,|viöe je zatraûila.
{12929}{12981}Viöe nego öto|moûe rukovati.
{12991}{13032}Poput mene, naravno.
{13055}{13096}Sviate mu se.
{13121}{13167}ObiËno je ûestok.
{13222}{13270}Imam moje male naËine.
{13283}{13318}Kako se ono zvaöe?
{13329}{13364}Argon.
{13388}{13433}Kao pas Uliks.
{13584}{13672}Za zmije|da Ëuvaju kuÊu.
{13694}{13811}A sa njenim drûanjem|uöla je u moj atelje.
{13825}{13861}Nepozvana.
{14272}{14356}Moj otac odrûava|oproötajni ples.
{14372}{14456}Moûda vam bude...|zabavno.
{14786}{14820}Ti ne ideö?
{14827}{14868}Svi na Kritu Êe biti tamo,|a ti neÊeö da ideö?
{14875}{14933}Pusti to! Ne idem!
{15028}{15111}HoÊeö, moraö da ideö!
{15152}{15201}Ne mogu te ostaviti samog.
{15217}{15319}Ideö na ples.|Nikolas Êe biti sa tobom.
{15342}{15401}On Êe drûati svoje oËi otvorene.
{15411}{15459}Da Rimi smera neöto.
{15469}{15516}Posluöaj oca.
{15554}{15658}moj otac je vodio|otpor na planini.
{15671}{15739}Moja je ûelja bila|da budem kraj njega...
{15750}{15820}...On je insistirao da ide|moj omiljeni brat...
{15828}{15882}rekavöi da su moje ruke dragocene.|Slike su moje oruûje...
{15893}{15959}...ne razumejuÊi ga u potpunosti|u to vreme.
{15989}{16079}On je uËinio sve da me ubedi|da napustim Krit.
{16101}{16149}Nisam bio svestan onda...
{16154}{16251}...da me priprema za|razliËitu vrstu otpora.
{16264}{16347}otpora koji nije imao veze|sa nekim posebnim osvajaËem.
{16356}{16447}Sada razumem da je to|otpor svetlosti...
{16455}{16492}...protiv tame...
{16502}{16563}...voen|od strane viöe sile.
{17172}{17224}Seti se zaöto smo doöli ovde.
{17232}{17307}SeÊam se, a ti?
{17597}{17630}Moram da priznam...
{17640}{17710}...Te veËeri FranËeska|je bila oËaravajuÊa.
{17801}{17863}Mogla je da öarmira|Ëak i kamenje!
{17877}{17963}Tako mi je drago da si doöao|Mislila sam da Êeö se plaöiti.
{17972}{18019}Vojnika vaöeg oca|ili njegovog novca?
{18025}{18048}Mene.
{18220}{18283}»ak i najopasnija mesta...
{18294}{18355}i najopasniji trenuci...
{18402}{18514}uvek je naöla naËin|da se me privuËe.
{18739}{18810}najbolji slikari na svetu...
{18824}{18860}...rade u Veneciji.
{18925}{19009}Da li ste ikada pre|videli Ticijana?
{19027}{19058}Ne.
{19099}{19149}On je porodiËni prijatelj.
{19170}{19220}Trebalo bi da doete u Veneciju.
{19277}{19313}Moj zaviËaj je ovde.
{19327}{19369}Nemate domovinu.
{19379}{19437}Ljudi poput tebe|nemaju zemlju.
{19445}{19467}Zaöto?
{19474}{19535}Jer Ijudi poput tvojih|zemljaka je oduzmu?
{19546}{19591}Venecija ima mnogo lica.
{19602}{19668}Postoji Venecija dobroËinitelja|i osvajaËa.
{19678}{19754}, ali postoji joö jedan Veneciji|gde moûeö...
{19771}{19809}...da postaneö sve öto poûeliö.
{19817}{19842}Ja sam samo slikar.
{19848}{19879}A ti misliö da si dobar?
{19889}{19929}Dakle, niste!
{20005}{20056}Moûete, meutim,|da postanete veliki.
{21554}{21610}Idi! Pokreni svog oca|Spasi ga.
{21618}{21652}Moj otac Êe|veËeras napasti!
{21757}{21809}Bez obzira na praznike...
{21824}{21920}...Da RIMI je jednu stvar|imao na pameti:
{21975}{22020}da uguöi otpor.
{22089}{22199}Ona je imao posla sa KriÊanima|Ijudima uvek spremnim...
{22208}{22276}...da ûrtvuju sebe|za domovinu.
{22356}{22421}Mladi Ijudi poput mene...
{22439}{22471}...leûe mrtavi...
{22490}{22539}...na zemlji.
{22605}{22673}Trebao sam da leûim i ja|tamo sa njima.
{22790}{22837}Ovog puta smo pobedili.
{22864}{22900}SledeÊi put...
{22938}{23005}...Ko zna Ëije Êe telo|tamo leûati.
{23130}{23200}Ovaj put smo pobedili...
{23218}{23257}...ali smo izgubili mnogo
{23308}{23390}SledeÊi put... ko zna.
{23900}{23962}Za mrtve!
{23971}{24005}Neka poËivaju u miru!
{24016}{24057}Neka poËivaju u miru!
{24482}{24577}On mora da ide. Ti ideö sa njim.
{24648}{24742}Od sada...|ti si njegov zaötitnik.
{24843}{24877}Sviraj!
{27006}{27066}Venecija, 6 MESECI KASNIJE
{27121}{27186}Sa blagoslovom moga oca|i Nikola...
{27195}{27269}...OdluËio sam da traûim|moju sreÊu u Veneciji.
{27352}{27413}Radio sam u ateljeu poznatog|Ticijana...
{27419}{27493}...i FranËeska protiv|volje njenog oca...
{27509}{27582}...svom svojom snagom|Ëinila je...
{27583}{27639}...sve za mene da bi|moj ûivot,bio udoban.
{27929}{27991}Opet je mraËno raspoloûen
{27999}{28056}Kao nebo u ovom gradu: Crno
{28469}{28545}To je Ticijan.
{28556}{28611}Tvoje vreme Êe doÊi.
{28617}{28677}Ti si sve bolji|- Ali ne dovoljno dobar, E.
{28735}{28802}Barem sam nauËio da radim|obrve.
{28810}{28872}Ko zna, moûda jednog dana|Mi ostavi da radim i uöi.
{28968}{29016}Zaöto sam, doavola napuötao Krit;
{29020}{29072}Zato jer te ûivot vodi gde on hoÊe
{29078}{29117}tvoj posao je da slikaö!
{29125}{29191}To je rekao tvoj otac,|to kaûem i ja
{29587}{29708}Nemoj mi reÊi da ovde|nema niöta lepo.
{30201}{30261}Da li sam bio u pravu öto sam ovde doöao?
{30304}{30359},Jesam li ovo ûeleo?
{30803}{30838}Krit...
{30865}{30925}Kako mi nedostaje Krit!
{31167}{31273}Atelje Ticijana ne moûe-|se porediti sa bilo kojim ateljeom koji sam znao.
{31301}{31394}Bio je prepun|kretanja i aktivnosti.
{31403}{31473}Svet dolazi iz svih krajeva Italije,|iz celog sveta...
{31482}{31560}...da izrade svoje portreti|potpisan od Ticijana.
{31576}{31614}Oprostite mi, oprostite mi...
{31625}{31664}Vaöa Svetosti...
{31675}{31732}Laskate mi.|Ja sam jednostavan sveötenik.
{31741}{31780}Atelje Ticijana.
{31786}{31830}Najboljeg umetnika|na svetu!
{31842}{31915}Priprema i meöanje boja|boje, boje..
{31950}{32032}Ako ûelite poÊi|ovde, Vaöe VisoËanstvo.
{32062}{32130}I pre svega ostalog,|dolazi Crkva...
{32157}{32280}...koja je imala moÊ i novac,|da sprovede zahteve.
{32303}{32339}Oprostite mi...
{32436}{32511}U äpaniji|se ne vide takve stvari.
{32523}{32551}Je li tako, Gevara?
{32948}{32979}Ko je to?
{32985}{33084}Ova... Maestro...
{33092}{33123}Ovaj.
{33133}{33205}Navodno je najbolji na Kritu|Gde god da je to mesto.
{33223}{33296}Ako ûelite da me sledite,|Maestro je spreman.
{33305}{33328}Naravno.
{33657}{33698}Maestro!|- Da...
{33707}{33776}»asni gosti|iz äpanije su ovde!
{33782}{33816}Dobro doöli u Veneciju.
{34119}{34145}Da, da...
{34154}{34245}veliËanstvo gradi|veliËanstven dvor...
{34254}{34287}...kakav äpanija nikada nije videla.
{34296}{34344}äta äpaniji, ceo svet!
{34361}{34392}Escorial!
{34404}{34453}Pa, Senor Ticijana?
{34510}{34579}Ja sam star Ëovek, Senor Hakone.
{34592}{34678}Toliko vrednost moûe da me ubije.
{34689}{34713}Ne!
{34757}{34786}Moûe da ga ubije.
{34937}{34967}Pauza!
{35531}{35578}Nikolos je moja senka.
{35608}{35679}Veran, ûeleÊi da ostvari|naredbe moga oca...
{35687}{35731}...pratio me svuda...
{35748}{35821}...posmatrao je|svakog i sve.
{35972}{36002}Tog dana...
{36019}{36127}...posetili su nas predstavnici|Crkve äpanije.
{36171}{36231}Meu njima je bio sveötenik...
{36321}{36430}...Ëiji pogled sam osetio|kako me probada...
{36437}{36488}...nisam znao razlog toga.
{36684}{36772}Pauza je i za tebe Domenikos,|ili Êeö i danas jesti boju?
{37131}{37226}Moj brat Manousos|okrenuo se ûivotu na moru...
{37262}{37365}i znao sam da Êe jedan dan putovanje|da ga dovede u Veneciju...
{37379}{37418}...sa najnovijim vestima od kuÊe.
{38137}{38184}Da RIMI nam postavili zamku.
{38198}{38251}Na venËanju|Otrovali su vino.
{38278}{38316}Svi su zbrisani.
{38368}{38430}- A otac?|- Svi.
{39425}{39513}Kako sam mogao da toleriöem ovo|nepravdu i nastaviti da ûivim...
{39526}{39577}...u zemlji osvajaËa?
{39619}{39667}, ali sam morao da radim.
{40401}{40490}Joö nije gotovo.|Treba da potpiöeö.
{40661}{40723}Dominikos Theotokopoulos
{41899}{41963}uobraûen mladi grËki...
{41970}{42028}...Ëije se ime|ne moûe izreÊi.
{42035}{42109}Zato Êu te zvati...
{42157}{42181}Greko.
{42279}{42339}Maestro hoÊete li potpisati?
{42352}{42406}Ne! éelim viöe crveno!
{42412}{42440}Oh, moj Boûe!
{42543}{42592}To je grËki mit.
{42615}{42676}Tit?os nalog|iz äpanije.
{42692}{42743}Zaöto mislite da je tako okrutno?
{42752}{42830}Jer je pogledao bogove u lice.
{42850}{42888}Video je puno.
{42905}{42934}Kao ti i ja.
{42952}{43032}Ljudi traûe istinu,|ali,ûele li da je vide?
{43047}{43086}Sluöaj moj savet.
{43102}{43191}Nikad ne pokazuj sve|- Zaöto?
{43203}{43249}NeÊe ti nikad oprostiti.
{43346}{43405}Ne mogu slikati kao ti.
{43412}{43486}Bolje!|Budi El Greko! El Greko!
{43537}{43638}Ticijan je vremenom|poËeo da me posmatra.
{43683}{43726}Bio je dobar Ëovek...
{43742}{43798}...i iskusan majstor.
{43853}{43940}Tako da sam polako poËeo|razvijati kao umetnik...
{43962}{44013}...slikati|moje slike...
{44028}{44105}...koristeÊi|venecijanski stil tog vremena.
{44300}{44418}FranËeska je lepa|i veoma poûeljna.
{44456}{44539}I pored nemirne prirode,|duboko u...
{44550}{44619}...je osetljiva|, napaÊenoj duöi.
{44654}{44729}To je FranËeska|koju sam hteo da naslikam.
{44782}{44870}U svakom sluËaju...|dugujem joj mnogo.
{44936}{45017}Za mene, FranËeska je|bila Venecija.
{45226}{45292}Dani u mom studiju|kod, Ticijana...
{45304}{45362}...su iöli glatko.
{45440}{45574}Dalje da pobegnem iz|uobiËajene religiozne teme...
{45598}{45681}...poËeo sam prouËavati|i opisivati stvari...
{45691}{45752}...koje su vezane|za moje korene.
{45774}{45837}stvari iz|grËke mitologije.
{46581}{46625}video sam originalni u Rimu.
{46769}{46804}Ne to je grËki.
{47043}{47149}na Kritu veruju da su zmije|poslate od strane bogova.
{47157}{47184}Bogova?
{47217}{47298}Neki smatraju da je paganski|Umetnost moûe biti opasna.
{47304}{47334}Opasno...
{47343}{47398}Znam, sve ta gola tela...!
{47446}{47472}Moûda.
{47538}{47588}Ali, ko moûe|da naslika duöu?
{47596}{47623}Ko zna?
{47672}{47728}Umetnost duöe, meutim,|je tvoj posao?
{47769}{47830}Bilo koji oblik umetnosti je opasan.
{47857}{47918}Sve misterije Boga|su opasne.
{47938}{47988}Mudar sveötenik!
{48043}{48088}Tvoj posao je veoma opasan.
{48097}{48121}A tvoj.
{48235}{48272}Vi ste vrlo dobri,znate.
{48347}{48388}Moûda sam nekad bio.
{48410}{48456}Bog vam je dao poklon.
{48468}{48532}Sada moramo pronaÊi naËin|da ga koristite.
{48580}{48628}Ne, saËekajte...
{48634}{48671}Veoma je dobar.
{48759}{48792}Ne.
{48834}{48895}Nije joö dovoljno opasna.
{49625}{49716}PoËeo sam da oseÊam potrebu|za promenu.
{49732}{49784}Dovodio sam moje cetkice u|red..
{49798}{49876}posle normalanog dana|na poslu...
{49899}{49979}öpanski sveötenik se|pojavio ponovo.
{49992}{50090}On me je zamolio da potpiöem rad|koji sam odbacio...
{50103}{50177}...pre par nedelja.
{50190}{50263}Rekao je da je dobar|Znao sam da nije.
{50292}{50357}Odlazite?|- Da.
{50417}{50469}I ja odlazim. Idem|kuÊi u äpaniju.
{50542}{50634}Da li biste potpisali ovo?
{50749}{50786}Stvarno nije dobar...
{50819}{50864}Neka ja budem sudija o tome.
{51710}{51743}Kako je u vaöoj zemlji?
{51866}{51901}Puna je svetlosti!
{51928}{51968}Lepo zvuci.
{52027}{52081}Barem imate dom gde|se moûete vratiti.
{52248}{52306}äpanija je|novi svet.
{52340}{52369}A ti...
{52388}{52477}Trebate novo platno|VeÊe..
{52515}{52578}äta ûelite od mene|Senor Gevara Ninjo;
{52584}{52672}ne ûelim niöta, El Greko.
{52752}{52793}Bog ûeli.
{52994}{53091}Joö uvek ne znam ko je hteo|da odem u äpaniju.
{53129}{53225}Bog ili|cudni sveötenik?
{53272}{53363}Ipak,ideja mi|je bila zanimljiva.
{53441}{53521}Venecija je poËela da gubi|primamljivost...
{53531}{53607}i rad za Ticijana|je bio tako iscrpan...
{53618}{53714}nisam imao energije|za moj posao.
{53743}{53815}Ono öto me je joö drûalo|tamo bila je FranËeska.
{53859}{54030}A Ëudno je öto ona|odluËila da me ostavi.
{54055}{54132}Nije mogla|da se odupre...
{54141}{54183}...pritiscima njenog oca...
{54204}{54274}...koji se protivio|naöoj vezi.
{54305}{54375}Viöe ne mogu IzbeÊi|moÊ moga oca.
{54385}{54469}On je odluËio da se oûeni|sa starim aristokratom...
{54479}{54521}...da promoviöe|svoje ambicije.
{54528}{54603}Ja sam ûena|Nemam slobodu izbora.
{54619}{54688}Jedini naËin da pobegne|planu njenog oca...
{54694}{54734}je da postane monahinja.
{54796}{54844}Svaki Ëovek ima svoj put.
{54850}{54879}Ona nije imala izbora.
{55005}{55067}Moja inspiracija da je naslikam|kao Mariju Magdalenu.
{55076}{55103}A slika?
{55111}{55160}Greönica koja je|postala Svetac.
{55344}{55385}Moram da priznam.
{55444}{55516}Rastanak je|bio izuzetno teûak...
{55522}{55579}...i bolan za oboje.
{56076}{56135}Madrid, 5 GODINA KASNIJE
{56181}{56214}Gevara je bio u pravu.
{56226}{56288}äpanija me je|prihvatila raöirenih ruku.
{56299}{56391}Postao sam odmah prihvacen|i poznat.
{56419}{56475}Sada mogu slikati|kako mi se svia...
{56488}{56546}...i pregovarati|kako sam ûeleo.
{56568}{56631}Drûao sam svoju sudbinu|u mojim rukama.
{56642}{56732}Pa? Mi moûemo|ponuditi 225 dukata.
{56792}{56828}Cena je 900 dukata.
{56837}{56863}To je nemoguÊe.
{56871}{56938}Isus je|na RaspeÊe.
{56947}{57019}Ali Marija Magdalena,|nije na pravom mestu.
{57024}{57050}Stvarno?
{57080}{57140}A vi znate gde je|Da li ste bili svedok?
{57250}{57341}Da prepolovimo razlike?|900 ili Niöta.
{57366}{57424}Ova vrednost nije za prodaju|vec...
{57430}{57463}za njeno iznajmljivanje.
{57522}{57563}Nikada je ne moûete posedovati.
{57574}{57643}Stvarni vlasnik|mog rada... je veËnost.
{57653}{57704}VeËnost- ovo je bogohuljenje?
{57718}{57779}UmetniËki temperament...
{57845}{57935}vrednost slike je, pet stotina!
{57945}{58021}Mnogo viöe|od pet stotina dukata.
{58394}{58473}Jedna od najboljih|koju sam ikada video.
{58709}{58747}Vecnost...
{59936}{60043}Gospodine, pomozite.
{60108}{60186}On je ovde. Zbog mene.
{60327}{60357}äta se deöava?
{60380}{60474}Sveötenici su poËeli|da se bave mnogim stvarima.
{60480}{60517}Izvan umetnosti.
{60534}{60605}I onda kaûeö, moj prijatelju...
{60636}{60679}...da je umetnost opasna!
{61233}{61295}Gospodar dolazi|u sred noÊi sada...
{61505}{61613}je Gospod...|I to lep...
{61820}{61897}Danas svako misli|da razgovara sa Bogom.
{61926}{61993}Na kraju|necemo biti potrebni viöe.
{62012}{62054}äta je ovo, öala?
{62073}{62159}Devojci nije dobro,|ali nije vestica.
{62174}{62248}Joö si mlad. Razumeö.
{62330}{62368}Ali budite oprezni, Gevara.
{62395}{62486}Neki vrlo visokog ranga|prate vaöe korake.
{62536}{62577}Nemojte ih razoËarati.
{62663}{62707}On je ovde sada.
{62746}{62799}On je svuda.
{62892}{62993}Zaöto ne mogu da te vide|zaöto ne moûete da vidite?
{63222}{63267}äta ce biti sa njom?
{63285}{63327}Ona... To
{63350}{63466}...Êe biti vaöa prva odluka.
{63730}{63801}Prvo je doöao miris.
{63846}{63905}Kao hladan povjetarac.
{63935}{63987}Na njegovo prisustvo.
{64020}{64110}Okliznuo se u mom ateljeu|niotkuda.
{64140}{64257}U Ëudno, stidljiv,|malo glup izraz.
{64306}{64395}Htela bi da kupim sliku,
{64455}{64505}odnosno iznajmim jedanu.
{64530}{64610}Naravno, ako mislite da|sam dostojna.
{64661}{64720}äto je trapavija...
{64741}{64822}...viöe atraktivnija|je bila u mojim oËima.
{64879}{64924}To stvorenje...
{64940}{65056}Kako da zamislim da Êe biti|moj partner za ûivot!
{65107}{65157}Zadrûali ste je|posle svega.
{65217}{65267}Bila sam u katedrali.
{65292}{65346}»ula sam öta se dogodilo.
{65605}{65645}Ocaravajuce.
{65675}{65702}Zaöto?
{65724}{65758}äta vidiö?
{65785}{65828}To je svetac.
{65856}{65889}éena.
{65917}{65949}Lepo.
{65981}{66007}Ne.
{66083}{66120}äta vidite?
{66203}{66264}Zatvori oËi|i reci mi öta vidiö.
{66374}{66410}äta vidite?
{66485}{66529}Vidim njene oËi.
{66575}{66630}Njene oËi nose toliko.
{66656}{66717}Kao da su videle sve.
{66742}{66803}Ali su tako mirne.
{66829}{66919}Bilo je kao da pada u Ijubav|za prvi put.
{67074}{67109}Moram da idem.
{67150}{67189}Ali cete se vratiti?
{67310}{67355}da pozirate|za portret.
{67642}{67770}Doöla je sledeÊeg dana,|i sledeÊeg dana i sledeÊeg dana.
{67829}{67920}I svaki put je bilo|kao hladan povetarac...
{67930}{67978}...koji mi je|ispunjavao duöu.
{68005}{68094}Moûda sam naöao|öta sam traûio u ûivotu.
{68131}{68186}Neprestano sam je slikao.
{68219}{68280}Cheronima je dobra osoba.
{68292}{68358}Slikajuci nju,pomoglo|mi je da izrazim,boûansko...
{68370}{68427}...koje svako|krije u sebi.
{69634}{69658}Ne!
{69748}{69793}Nije zavröena.
{70028}{70103}Stvarno sam toliko lepa?
{70320}{70419}Bilo je kao da se ponovo|zaljubljujem,kao prvi put.
{70672}{70753}Ovo sveto stvorenje|nikada ne prestaje da me impresionira...
{70761}{70818}i joö mi nije dala|svoje srce...
{70847}{70889}...i to mi se svidelo.
{71507}{71587}»ak i moj voljeni Nikolos,|moja senka...
{71596}{71634}...delovao je zadovoljno.
{71650}{71722}Cheronima je ponovo i ponovo dolazila.
{71756}{71830}Dok se Guevara nije|iznenada pojavio.
{71846}{71958}Sve viöe i viöe,|je ulazio u moj ûivot.
{71969}{72003}Domenikos neÊete verovati öta...
{72469}{72532}Ova vrsta posla je troöenje|tvog talenta, moj prijatelju.
{72554}{72630}éene su meu voljenim|boûijim stvorenjima!
{72638}{72690}Lepota, postoji li|umetnost bez nje?
{72935}{73016}Moûda postoji bolji|model Bogorodice.
{73063}{73102}Evo nas opet...
{73122}{73178}sekularna dama...
{73194}{73281}...koja ûeli da je pamtimo|kao sveticu zauvek.
{73287}{73314}Dakle, zar ne?
{73328}{73359}Oprezno!
{73370}{73448}Gde ste krenuli,na kraju|postacete Inkvizitor.
{73751}{73793}On mi se ne dopada.
{73996}{74049}Idete li na ispovest|- Izvinite.
{74056}{74119}- Vi imate mnoge grehe|- Nisam uradila niöta loöe!
{74125}{74152}Joö ne.
{74157}{74221}ali najveÊi greh je|da se spreËi njegov rad.
{74230}{74297}On ne pripada vama. Ona pripada Bogu.
{74303}{74391}Vi se igrate sa vatrom|seniorita De Las Kouevas.
{74402}{74453}Kako se usudujete|- Sluöaj dobro!
{74464}{74550}On ima prava da zna sve|Treba neko da ga vodi..
{74558}{74598}A to ne moûete biti vi.
{74610}{74663}Ona mora da veruje u neöto.
{74845}{74884}On veruje da u ûivotu!
{74905}{74937}U ûivot
{75257}{75306}Vi ste Gospodar...
{75332}{75404}...koji dolazi u pola noÊi?
{75456}{75492}Moûete li ga videti?
{75545}{75575}Da.
{75809}{75872}»ekamo vaöu presudu.
{76030}{76066}Na lomacu!
{76359}{76404}Ninjo de Gevara...
{76451}{76531}Dobrodoöli, veliki Inkvizitoru.
{77925}{77955}Morate da odete.
{77964}{77997}Otac dolazi.
{78010}{78043}Zar ne razumete?
{78060}{78098}Nema razloga za strah.
{78108}{78141}Ja se ne bojim.
{78186}{78214}Onda skoËite.
{78261}{78306}Morate razumeti, Domenikos.
{78347}{78440}Ako odem sa tobom sada,|nema povratka.
{78478}{78513}Ja cu te uhvatiti.
{78529}{78569}Ovde dolazi tvoj otac...
{78578}{78658}Moj otac... Idi! Idi!
{78708}{78749}Idi unutar odmah!
{78787}{78842}Kasnije sam shvatio...
{78850}{78900}Cheronima je bila u pravu.
{78910}{79031}Nikad ne potcenjuj zlo|na koje su Ijudi sposobni.
{79719}{79766}äta si video. Niöta.
{79830}{79879}Ne mogu je|izbaciti iz mog uma.
{79908}{79972}Prvi put|da te vidim srecnog!
{79993}{80020}Da...
{80084}{80138}Da, ja sam srecan.
{80592}{80685}Cheronima,|je krhko stvorenje...
{80710}{80789}naÊi hrabrosti da se opire|Tvrdoglavom ocu...
{80807}{80889}...a noÊu iskradati se|da doe u susret meni.
{81186}{81220}Znam ga.
{81240}{81287}Ubrzo Êe poûeleti da napusti ovo.
{81311}{81355}Ovaj grad ga guöi.
{81379}{81456}Do sada, sam ga doveo do ovde.
{81468}{81544}Ali ne mogu da ga|odvedem gde treba da ode.
{81557}{81596}Sada je red na tebe.
{81619}{81693}Odsada ti moraö|brinuti o njemu.
{81736}{81803}On ne zna da cuva svoja leda.
{81849}{81910}Vi od sada pazite.
{81953}{81983}Vi.
{82096}{82127}Vi.
{82483}{82509}Idite!
{83387}{83430}Gde je moja Êerka Moja Êerka!
{83440}{83534}éelim da vidim moju Êerku|Moja Êerka.
{83933}{83974}nisam mogao da|zamislim...
{83985}{84049}da ce ova noc|promeniti sve.
{84089}{84138}dobio Cheronimu...
{84159}{84211}ali sam izgubio Nikolasa...
{84237}{84278}moj prijatelj...
{84343}{84389}...moja senka!
{84534}{84580}Ne!
{85078}{85117}Ne!
{85233}{85313}Nikolas je znao|öta Êe se desiti.
{85348}{85428}imao je mnogo naËina|da sazna stvari.
{85448}{85493}Ipak, iako je znao...
{85533}{85636}nije oklevao da se ûrtvuje|da me zaötiti...
{85648}{85727}...i da odrûi obeÊanje|dato mom ocu.
{85769}{85865}On je takoe znao da sam sada|u dobrim rukama.
{85887}{85938}Cheronima me volela.
{86041}{86094}éeleo sam da zadrûim zemlju...
{86132}{86191}...ali je njemu bilo potrebnije.
{86221}{86315}Zemlja koja mu je bila laka,
{86334}{86432}zemlja od kuÊe,|zemlja sa Krita.
{86709}{86788}Toledo 8 GODINA KASNIJE
{87484}{87531}Moje ruke su zaspale tata.
{88541}{88640}Slikam jer ûelim da|preobratim Ijude u svetce.
{88681}{88823}Slikam jer ûelim da njihove|duöe pretvorim u Ëisto svetlo.
{88881}{88982}Slikam jer ûelim da sve|pretvorim u svetlo.
{89026}{89096}Samo svetlo Êe osvojiti smrt...
{89106}{89168}Slikam|da pobedim smrt.
{89454}{89496}Dobijate...
{89507}{89585}gomilu|starih greönika...
{89600}{89675}...i pretvarate nas u svetitelje.
{89750}{89804}Kakva je ovo magija?
{89882}{89955}Vi ste opasan|Ëovek, Domenikos.
{89984}{90017}Opasan.
{90547}{90605}Ovo je najbolji rad|,koji si uradio.
{90612}{90679}Ali zaöto?|äta ga Ëini dobrim?
{90691}{90730}Vi ga Ëinite dobrim.
{93007}{93092}najbolje vreme za ples|,ples iz domovine.
{93106}{93154}ples Krita.
{93167}{93257}Sa ovim umetniËkim delom,|"Pogreb grofa Orgaz"...
{93263}{93343}...ulazite|meu velikane.
{93364}{93399}éiveo El Greko!
{93439}{93467}Za prijateljstvo!
{93565}{93612}Hvala za moj portret.
{93621}{93708}Kada zavröite, duöa moja|zapitali öta telo preferira.
{93712}{93763}Moje ili öta je on slikao.
{93797}{93832}El Greko!
{93887}{93941}äpanija mi je dala toliko.
{93949}{94000}viöe nego öto samm oËekivao.
{94013}{94085}slave, prijatelja, bogatstva...
{94108}{94140}...Ijubav.
{94163}{94200}äta vidite?
{94224}{94279}vidim prijatelje...
{94316}{94347}naöe dete...
{94371}{94397}Tebe...
{94425}{94460}äpaniju...
{94491}{94531}SreÊu...
{94572}{94626}Zapamti samo jednu stvar.
{94652}{94740}Ovaj put, ne moûete iÊi.
{94748}{94838}Ovaj put ne ûelim da odem.
{96009}{96080}Moraö mi pomoÊi.
{96094}{96178}Inkvizitor je uhapsio mog muûa,|pekara Karkadil-a
{96194}{96282}On je Grk,|on ne govori äpanski
{96368}{96398}Ovo je vaöa zemlja!
{96405}{96460}Kako moûe inkvizicija|da postane pravo?
{96469}{96534}Ne razumete|nemoûete protiv njih..
{96558}{96593}Pokuöao si?
{97145}{97194}Ko ste i kako ste doöli ovde?
{97231}{97264}Koji je njegov zloËin?
{97276}{97347}ja te pitam neöto!|Za öta je kriv.
{97358}{97425}On je priznao.
{97433}{97511}Kojim jezikom je priznao!|On ne govori äpanski!
{97528}{97591}Zahtevam da bude slobodan!
{97601}{97649}Ko si ti da zahtevaö od nas?
{97673}{97711}Tiöina...
{97777}{97853}On je najznaËajniji slikar|äpanije.
{97869}{97912}Zar ga ne prepoznajete?
{97961}{98003}äta je, Domenikos?
{98033}{98090}Zar neÊeö pozdraviti|starog prijatelja?
{98104}{98230}moj prijatelj nije nosio|odoru Velikog Inkvizitora!
{98354}{98444}Ovaj Ëovek je nevin|i zahtevam da bude puöten..
{98451}{98484}Zahtevaö?
{98503}{98562}Od inkvizicije?
{98645}{98688}Poöto ste ovde, gospodo...
{98696}{98763}Moj dragi prijatelj i Hakone|ispovednik naöeg kralja...
{98770}{98854}...da objasnite arogantanom|GrËkom prijatelju naö...
{98859}{98892}...novi poredak stvari?
{98900}{98920}Uredu!
{98927}{98990}ZahtevaÊu, moliÊu!
{99001}{99050}Ako je to ono öto ûelite|samo ga oslobodite!
{99094}{99124}Jako dobro.
{99154}{99189}Pusti ga!
{99209}{99235}äta?
{99250}{99345}Inkvizicija moûe biti|tako milosrdna i nemilosrdna.
{99367}{99397}Kao Bog!
{100178}{100215}Nedostajeö mi, Domenikos.
{100402}{100448}äta je sa ostatkom?
{100495}{100531}U vatru.
{100571}{100607}Sve njih.
{101754}{101836}äta je to öto transformiöe|Ijude u svetce?
{101869}{101942}Bol? MuËenje?
{101956}{102016}Nepravda,Vera?
{102033}{102067}Znanje?
{102078}{102186}Moûe li moja slika da|pretvori Ëoveka u svetca;
{102208}{102296}ili samo samo ja vidi|te Ijude kao svetce?
{102304}{102363}Postao sam opsednuti.
{102404}{102501}pripremao sam se za bitku|,i ako toga nisam bio svestan.
{102519}{102554}I poËeo sam da Ëinim...
{102563}{102622}...jednu od najgorih stvari koje|sam mogao da uradim.
{102634}{102716}poËeo sam da zanemarivam|Cheronimu,mog Anela »uvara.
{103072}{103129}Nikada mi nisi rekao|ko je model.
{103189}{103243}Nikada mi nisi rekao... ali znam.
{103497}{103546}Ti me voliö joö, Domenikos?
{103707}{103751}Zaöto mi ne odgovorite?
{103886}{103912}ReËi.
{103962}{104018}Ne trebamo ih viöe.
{104049}{104088}GrËka ludo!
{104340}{104375}Domenikos!
{104422}{104457}Bojim se!
{104621}{104667}Znam öta radim.
{104673}{104723}Nisi ti ratnik, Ijubavi moja!
{104758}{104818}äta je Ëini ratnika?
{104877}{104959}Moûda samo neko|ko ne pobegne?
{105075}{105135}Neko pita za vas.
{105150}{105228}Gevara me pritiskao|sve viöe i viöe...
{105242}{105326}i odnos izmeu nas|ili öta god je...
{105340}{105438}...je dostigao taËku pucanja,|spreman da eksplodira.
{105507}{105573}Koliko je Ëudan bio taj Ëovek.
{105603}{105719}On je imao sposobnost da|atmosferi da nepodnoöIjiv teret.
{105739}{105824}I moÊ steËena,posle|svih ovih godina...
{105848}{105924}...naËinila ga je mraËnim.
{105941}{106033}Od prvog trenutka kada je|sveötenik doöao u moj ûivot...
{106046}{106145}...nisam mogao da shvatim|öta ûeli od mene.
{106173}{106393}Ovi svetitelji liËe na ludake|ili prosjake.
{106473}{106514}oseÊam kao da ih znam.
{106559}{106586}Znam li?
{106625}{106659}Naravno.
{106851}{106942}i moûete ih pretvoriti u svetitelje.
{106955}{106979}Moûda.
{107051}{107093}Moûda ste ih vi pretvorili.
{107147}{107200}Samo Bog stvara svetitelje.
{107208}{107285}Ko zna öta radi ovih dana.
{107359}{107416}Dakle, bitka Êe biti izmeu nas.
{107513}{107568}To Êe biti zabavno.
{107612}{107666}Zar niste zbog toga i doöli?
{107711}{107793}Svako ko je neko|u Toledu...
{107815}{107866}...ima portret od tebe.
{107880}{107918}Sada je moj red.
{108034}{108071}Mogu odbiti.
{108099}{108139}Naravno da moûete.
{108184}{108299}Ali to bi bilo beûanje.
{109038}{109091}Atmosfera je bila|toliko napeta...
{109101}{109141}...nisam mogao da diöem.
{109193}{109251}osetio sam negativan|magnetizam koji je rastao sve viöe...
{109261}{109302}kao pred buru...
{109316}{109385}...i mogla je da se razbije|u bilo kom trenutku.
{109812}{109931}Trojanski konj|GrËki osvajaËi...
{109971}{110016}...u Toledu, a ne na Troju.
{110045}{110112}momak koji pokuöava|da ih zaustavi...
{110137}{110181}...da jede zmije.
{110316}{110394}äta pokuöavaö da kaûeö, Domenikos?
{110443}{110486}Ja sam samo slikar.
{110635}{110746}Ako bi ste bili samo slikar,|ja vas ne bih ni primetio.
{110847}{110886}Kada pokreÊete Ijude...
{110922}{110981}ulazite u njihove glave...
{111020}{111061}...u njihova srca.
{111122}{111196}Ko zna öta|tamo upravlja vama.
{111204}{111290}Umetnost uvek povreuje|Ijude koji pate.
{111390}{111485}Veliki Inkuisitor Êe baciti|sve umetnike u vatru
{111509}{111540}Ne.
{111592}{111649}Ne "sve" umetnike.
{111660}{111740}Bilo je oËigledno da je hteo|da naslika portret...
{111749}{111797}...ali ne samo to.
{111809}{111898}Cela dva dana pokuöavam|da se koncentriöem na portret...
{111926}{111991}...ali on nije sedio|na istom mestu.
{112002}{112096}okretanje u ateljeu|u potrazi za mojim slikama...
{112109}{112160}pokuöava da ue|u njih...
{112170}{112200}i analizira ih...
{112210}{112303}...izgleda da traûi naËin da|ih upotrebe protiv mene.
{112324}{112410}i moûda sam mu dao priliku.
{112429}{112516}OdluËio sam da slikam|kao öto je zaista.
{112523}{112556}Stvarni Gevara.
{112578}{112613}Kako to?
{112629}{112736}Kako ovi Ijudi|izgledaju kao sveci?
{112841}{112880}Zaöto mi ne govorite?
{112925}{112974}Nema niöta da kaûem.
{113007}{113096}Nema niöta da kaûe...|Nema niöta da kaûe..
{113108}{113176}, Bog Êe da oprosti|tvoju aroganciju.
{113235}{113278}Reci mi neöto, Domenikos.
{113309}{113341}Mrzite me?
{113352}{113401}Ja ne mrzim nikoga.
{113525}{113562}äta ûelite od mene?
{113625}{113657}Moj portret|- Zaöto?
{113811}{113926}éelim da vidim öta vidiö u meni.
{114375}{114424}OËe naö, koji jesi...|da se sveti ime...
{114432}{114474}.. da tvoje kraljevstvo doe,|neka bude tvoja volja...
{114483}{114529}...kao i na nebu,tako i na zemlji...
{114536}{114584}...hleb naö nasuöni...|Daj nam danas...
{114591}{114633}...oprosti nam naöe dugove...
{114642}{114693}...Kao öto i mi opraötamo|duûnicima naöim.
{114702}{114741}I ne dovodi nas|u iskuöenja.
{114750}{114796}no izbavi nas|od zla. Amin.
{115956}{115980}Jeli spremna?
{116102}{116133}Onda mi pokaûi!
{116735}{116761}Izvinite.
{117133}{117173}Ti zasluûujeö vatru i drvo!
{117228}{117272}Tek Êeö Ëuti za mene!
{117735}{117788}Ti si idiot!
{117858}{117888}äta si uradio?
{118555}{118588}Zaöto ne razgovaraö sa mnom?
{118654}{118696}Zaöto mi nikad ne priËaö?
{122368}{122436}BiÊe poslato po vas?.
{122471}{122506}Kada Êe se to?
{122512}{122542}Kada budu spremni.
{122554}{122606}U poslednje vreme bilo je puno posla.
{123598}{123631}äta je ovo?
{123646}{123676}Niöta.
{124173}{124214}Skupite sve, molim te.
{124224}{124279}Mi Êemo pokupiti stvari.|Odlazimo veËeras.
{124285}{124329}Cheronima,ja ostajem.
{124365}{124466}Inkvizicija zahtev da svedoËiö|Znate öta to znaËi.
{124474}{124524}Oni ne mogu da spale|El Greka,ne mogu?
{124529}{124590}Ne mogu,naravno.|Ali Dominikosa, meutim, mogu!
{124610}{124663}PodseÊam vas da imate sina!
{124668}{124772}Kao öto si mi rekla jednom...|Ovaj put ne mogu da idem!
{124780}{124807}Reci mi neöto...
{124825}{124877}Zaöto misliö da sam se zaljubila u tebe?
{124918}{125001}Misliö da me briga za|tvoj ugled?
{125107}{125166}Sve do Ëega mi je stalo...
{125230}{125275}si ti.
{125292}{125329}ne mogu.
{125438}{125468}U redu.
{125516}{125577}Tvoj sin i ja odlazimo ujutro.
{125618}{125648}Cheronima!
{125688}{125746}Ako me voliö, neÊeö iÊi.
{125799}{125845}, joö uvek nisi shvatio.
{125938}{126032}Volim te|Ali koketiranje sa smrÊu.
{126038}{126134}Ako ostanem, ja Êu poËeti|da te mrzim, Dominikos.
{126183}{126236}Ne mogu da podnesem
{126285}{126322}Ja nisam tako hrabra.
{126334}{126383}Za trenutak sam osetio da sam izgubio...
{126421}{126515}Ali iznutra duboko sam oseÊao|neoËekivanu sigurnost...
{126538}{126628}da mi neöto govori da sam bio|predodreen od sudbine...
{126639}{126673}...za ovu bitku.
{126703}{126760}To je bila borba za moj ûivot...
{126778}{126835}...i bitka mog ûivota.
{128427}{128486}Ne znam da li mogu da|neöto uËinim.
{128493}{128540}Gevara je|teûak Ëovek.
{128547}{128579}Zato sam poslala po vas.
{128611}{128658}Ti ga toliko voliö?
{128667}{128690}Da.
{128760}{128788}Vi?
{129965}{130007}Da li se prvi put sreÊemo?
{130097}{130154}Doöla sam kod vas|zbog izvesnog slikara.
{130194}{130313}äta mislite o tome da|napravite izuzetak sa njim?
{130357}{130423}On je greöan|i mora biti kaûnjen.
{130460}{130512}Moramo da branimo|veru, naravno.
{130535}{130618}Ali ubeivanje donosi bolji|rezultat od nasilja.
{130735}{130819}Zamislite kiöu da pada|na ovaj hram.
{130836}{130886}Sve öto vam treba|je prasak...
{130905}{130982}i voda Êe poËeti da teËe|sa zidova, na postolja...
{130987}{131060}...da sve bude natopljeno|dok se sve ne usmrdi.
{131073}{131112}To je greh.
{131135}{131218}Moramo da zatvorimo|svaku pukotinu u zidu.
{131300}{131369}Vi pokuöavate|da zaustavite kiöu?
{131440}{131486}Sada sam te prepoznao.
{131510}{131556}Sa njegove slike.
{131592}{131638}"Marija Magdalena".
{131656}{131735}Zato ne oklevate da|branite greönika.
{131750}{131819}Ja sam moûda...|. Ali on...?
{131852}{131889}Poötedite ga.
{131907}{131971}Koristite snagu vaöe odore|da uradite neöto dobro.
{132028}{132054}Hajde.
{132150}{132226}Ja Êu koristiti moju snagu.
{132241}{132336}I on Êe se osetiti|... plamen.
{132566}{132691}Koga najviöe mrziö?|Njega ili sebe?
{132839}{132899}»udno je|kako u teöka vremena...
{132909}{133010}...moj brat Manousos je uvek|bio pored mene, kao da je znao
{133094}{133130}da mi je potreban.
{133240}{133358}On mi treba, ali je bolje|da ne zna öta se deöava.
{133785}{133851}Zaöto je ovako tiho, niko nije umro?
{133869}{133951}Pobogu,joö te nisu obesili?
{133991}{134070}Molim te razgovaraö|sa junakom...
{134076}{134132}...velike pomorske borbe|protiv Turaka!
{134276}{134305}Ti?
{134329}{134379}Bitka kod Lepanta;
{134419}{134460}Trebao sam pretpostaviti.
{134465}{134509}Rat je odvratna|stvar, Domenikos.
{134515}{134545}äta sam vidio mojim oËima...
{134552}{134585}momka pored mene...
{134590}{134643}...moj prijatelj, odseËenih ruku.
{134669}{134736}Ko zna gde Êe postati|bogalj covek...
{134755}{134795}...jadan momak,Servantes.
{134832}{134875}Barem se borite.
{134938}{135008}Ja beûim ceo moj ûivot.
{135113}{135192}Moj otac treba da se|oseÊa postien zbog mene.
{135198}{135232}Tvoj otac bi|ponosan na tebe.
{135258}{135300}Oni su uvek bili ponosni na tebe.
{135338}{135405}i nadam se da jeste|gde god da je.
{135540}{135589}Jesi li video sveta, Manousos?
{135624}{135671}Ne znam da li sam video ceo svet...
{135692}{135808}...ali öta sam video, svuda|znaju za El Greka.
{135886}{135921}Doneo sam ti neöto.
{135959}{136006}Ukus od kuÊe. Rakija.
{136200}{136236}Za mog brata!
{136253}{136317}NajveÊeg grËkog slikara|u äpaniji!
{136325}{136375}Dokle god je ûiv.
{136383}{136437}Pa ako Êe da umre,|da umre kao...
{136444}{136522}...najveÊi grËki|öpanski slikar.
{136530}{136558}BiÊu bolji na sahrani.
{136576}{136652}Pitam se kako je oseÊaj|na äpanskoj sahrani.
{136943}{137020}Mora da si veoma ûedan,|posle sedamnaest godina!
{137031}{137096}Koliko je godina proölo od|kako sam napustio Veneciju...
{137106}{137191}a reËi Ticijana|i dalje zvona u uöima...
{137202}{137247}...Ëistije|glasnije nego ikada.
{137255}{137276}Moj savet:
{137286}{137366}Ljudi su u potrazi za istinom,|dali stvarno ûele da je vide?
{137375}{137458}Sluöaj moj savet|Nikada ne pokazuj sve..
{137478}{137529}- Zaöto?|- Nikad ti neÊe oprostiti.
{137577}{137632}ne mogu da slikam kao ti.
{137639}{137719}Boljei!|Budite El Greko! El Greko?
{137861}{137942}Sada sam umoran,|tako umoran.
{138006}{138096}Novi dan sviÊe|nemem viöe vremena za pisanje..
{138108}{138159}Moramo da pripremim|sebe.
{138172}{138228}Uskoro moûda|neÊu biti ûiv.
{138240}{138312}Uskoro Êu moûda|u zagrljaj vatre.
{138361}{138460}Moûda Êe me spaliti,|spaliti moje slike...
{138484}{138560}, ali nikada neÊe biti u stanju|da uniöte moj ûivot...
{138570}{138633}, i razlog radi kojeg|su se rodile moje slike.
{138659}{138772}A razlog je da|zaötiti svetlost od tame.
{138784}{138852}To nikad|neÊe biti uniöteno.
{139628}{139705}Vi Êete goreti u paklu!
{139827}{139933}U vatru!|- Bog s tobom!
{142136}{142216}Vi ste Domenikos Teotokopulos,|poznat kao El Greko;
{142320}{142345}äta se deöava?
{142356}{142404}ne moûete biti|u sobi.
{142410}{142444}, ali imam ideju. Doite sa mnom.
{142461}{142507}Hakone je ovde.|Hakone je veoma bolestan.
{142700}{142754}Ovde si bezbedna.
{142859}{142908}Da li ûivite sa Cheronimom|De Las Kouevas.
{142979}{143022}Zaöto se nikad niste oûenili;
{143047}{143121}Ne treba nam saglasnost|od nekog drugog.
{143167}{143254}Pa ti si iznad zakona|Crkve.
{143266}{143288}Ne.
{143361}{143458}Ali, moûda Ijubav|ne podleûe zakonima.
{143470}{143526}Crkva se tiËe greha.
{143550}{143579}bez Ijubavi?
{143585}{143613}Da li imate sina.
{143645}{143721}Xorxe Manuela;|kopile!
{143740}{143806}Ovo pokazuje Crkva|svoju snagu?
{143839}{143872}napadaju decu?
{143886}{143965}Trebalo bi da odete kuÊi.
{143970}{144048}Ne. Ne odlazim.
{144066}{144099}Ja sam prijatelj El Greka.
{144119}{144183}I sada da preemo|na sadrûaj vaöih slika.
{144203}{144275}Jedan: izvrtanje Pisma.
{144289}{144403}Dva: bogohuln likovi Svetitelja|kao da su kriminalci.
{144414}{144445}, ali ovo...
{144458}{144537}Tri: paganskim tumaËenjima|anela.
{144544}{144588}Ko su lica|Dionis!
{144595}{144614}To je...
{144622}{144707}»etiri: ËinjeniËnom|netaËnosti u biblijskim scenama.
{144712}{144776}Pet: senzacionalne i|vulgarane i boje.
{144786}{144858}äest: izopaËenje vere.
{144873}{144943}Sedam: jeretiËka subverzija|prave doktrine.
{144962}{145059}Osam: Ignorisanje uredbe|Saveta Trenta...
{145067}{145097}...o izgledu slike.
{145107}{145163}Posebno stava öest|stava B..
{145169}{145244}...koja kaûe da liËnosti|mora biti skromna.
{145258}{145336}Te optuûbe su smeöne|i ti to znaö.
{145374}{145485}Bojim se da ne razumeö|ozbiljnost situacije...
{145491}{145521}...onoga öta vas Ëeka.
{145904}{145933}Moj informator nam kaûe...
{145942}{145993}...da ste dva puta jeli|svinjetinu petkom.
{146009}{146090}Vaö sin se krsti|nepravilno u Crkvi.
{146193}{146269}Vaöe slike ometaju|Ijude u molitvi.
{146282}{146301}Ne.
{146311}{146380}Vaö cilj je samo|da se hvalite.
{146402}{146441}Kad Êu se moÊi braniti?
{147029}{147057}Kojom odbranom?
{147161}{147217}Moram da pozovem|svedoka odbrane.
{147226}{147267}Ovo je protiv pravila.
{147403}{147474}Ja zovem Velikog Inkvizitora...
{147493}{147551}...kardinala Ninja de Gevaru!
{147612}{147690}Pozivam ga da odgovori,|zaöto je traûio...
{147700}{147779}...od jeretika da|napravi njegov portret!
{148231}{148273}Pa, moj stari prijatelju?
{148353}{148394}Optuûujeö me za bogohuljenje?
{148411}{148434}Da.
{149098}{149154}éenski Svetitelji|su vam previöe lepi.
{149163}{149219}Krila anela|su veoma velika.
{149237}{149269}Veoma velika;
{149280}{149339}Moûda ti znaö bolje|od Crkve.
{149350}{149391}Moûda ste videli anele.
{149481}{149515}Odgovori na pitanje.
{149549}{149597}Jesi li video anela?
{149642}{149681}Jesi lii video?
{149766}{149792}Ne.
{149817}{149853}Ali ih slikaö.
{149941}{150065}I svet Êe misliti da znate|kako aneli izgledaju...
{150077}{150136}...jer ih vide na|vaöim slikama.
{150150}{150245}Nije bitno öta mi kaûemo,|öta Crkva uËi...
{150257}{150357}...jer mislite da|ste struËnjak.
{150364}{150447}Ti! Niöta drugo,nego|egoistiËni umetnik.
{150454}{150522}Koji nikada nije video anela!
{150610}{150666}Ti si video Anela?|- Kako se usuujeö!
{150700}{150724}äta?
{150749}{150793}Nije bitno öta ti kaûeö.
{150810}{150869}äta da kaûem dalje|apsolutno si u pravu.
{150917}{150960}Ja sam bogohulnik.
{150995}{151073}äta je umetnost|ako nije bogohuljenje?
{151100}{151192}Zar nije Bog jedini i|pravi kreator?
{151391}{151424}Da.
{151468}{151508}Ja sam kriv...
{151574}{151640}Ja dajem Ijudima|nove svetove...
{151657}{151690}nove boje...
{151729}{151762}...u novom svetlu.
{152043}{152097}Sebe osuuje.
{152141}{152219}»inite moj posao|vrlo lakim, moj stari prijatelj.
{152473}{152510}éalim te.
{152630}{152663}Iskreno.
{152741}{152830}Misliö da moûeö zagrejati|svoju hladnu duöu na...
{152841}{152909}...lomaËama Ijudi|koje bacaö u plamen?
{152983}{153044}Pitali ste me öta vidim u vama.|Sluöaj onda.
{153425}{153479}Kada ste ispruûili|ruke za Bogom...
{153498}{153579}...i mislili ste da|ste blizu praznini.
{153626}{153665}Niste nauËili.
{153709}{153790}Kako Bog da vam govori|dok umesto Ijubavi, öirite...
{153802}{153905}...uniötenje, paljevinu, mrûnju,|i smrt oko vas!
{153963}{154020}I sada naravno je moj red
{154029}{154073}, ali ne moûete me spaliti.
{154101}{154137}Dozvolite mi da vam kaûem zaöto?
{154170}{154233}Zato öto gorim ceo svoj ûivot.
{154254}{154304}Ceo ûivot.
{154312}{154381}Ali ne u vatri,veÊ u svetlosti.
{154416}{154468}Ja sam se bacio u bljesak.
{154495}{154579}Vi palite vatre jer|se plaöite da gorite.
{154624}{154670}Vi se plaöite svetlosti.
{154788}{154890}Zato mi te je ûao, moj stari|prijatelju Ninjo de Gevara.
{154963}{155015}Ne greöiö öto se plaöiö.
{155060}{155170}U svakoj vatri koju paliöi|toneö dublje u tamu...
{155178}{155305}...i koliko god Ijudi da spaliö,|ti nikada neÊeö pobeÊi.
{155471}{155532}Moûe li tama|da pobedi svetlost?
{156167}{156199}Eminencijo?
{156939}{156976}äta radiö? Ti si bolestan!
{156984}{157005}Hajde.
{159009}{159040}Budalo!
{159047}{159073}Da, jesam.
{159114}{159149}Gotovo sam te izgubio.
{161816}{161885}DOMINIKOS THEOTOKOPOULOS
{161891}{161965}je roen na Kritu 1541...
{161975}{162083}i umro u Toledu|äpanija u 1614.
{162120}{163337}{C:$00FF00}prevod:Ned@-2009|cyberkurajber.2@gmail.com
{163362}{164862}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
