{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{294}{389}
{431}{515}JA SAM DAVID
{527}{583}U godinama nakon|drugog svetskog rata
{584}{642}mnogo je ljudi u IstoËnoj Europi|oterano u radne logore
{643}{699}zbog neslaganja sa|svojim novim reûimima.
{699}{757}Zbog toga su mnoge|porodice razdvojene.
{762}{819}éivot je u tim logorima|bio straöno teûak,|a beg je bio nemoguÊ.
{820}{895}Za jednog deËaka, imenom David,|to je bila jedina nada...
{983}{1017}"Sluöaö li me?
{1033}{1152}Moraö noÊas pobeÊi.|To je jedina öansa da ostaneö ûiv.
{1165}{1240}Budeö li sledio moje upute|i uspeo odmaÊi od logora,
{1244}{1330}moraö napustit Bugarsku,|a da te ne primijete.
{1337}{1394}Svi Êe te hteti uhapsiti,
{1397}{1470}i ne budeö li veoma oprezan,|biÊeö uhvaÊen"
{1506}{1630}Uspeö li prebeÊi granicu,|trebaö nastaviti prema Danskoj.
{1654}{1771}Prvo, kreni na jug, prema Solunu,|i sakrij se na nekom brodu koji ide za Italiju.
{1775}{1858}U Italiji, potrudi se|stiÊi koliko moûeö severnije.
{1872}{1940}Putovanje Êe biti|dugo i moûda nemoguÊe,
{1950}{2043}ali moraö stupiti u|vezu s vlastima u Danskoj.
{2045}{2087}Ne moj ga otvarati.
{2090}{2165}Vidi li neko sadrûaj|pre no ga dostaviö,
{2169}{2206}vratiÊete nazad ovamo.
{2233}{2271}Jesi li razumeo?
{2279}{2342}Znam, Ëitav ûivot si proveo u logoru,
{2345}{2411}no postoji svet izvan njega.
{2415}{2469}A to je jedan veoma opasan svet.
{2473}{2509}Ne veruj nikome!"
{3113}{3209}"Kad doe vreme, otii iz|barake prema zapadnoj ogradi."
{6758}{6779}"Kad ugledaö signal,
{6782}{6832}imaÊeö 30 sekundi|da preskoËiö ogradu,
{6835}{6888}pre no ponovo ukljuËe far."
{7906}{7940}Ako me pogode...
{9157}{9204}"Skriveno pod panjem blizu ograde logora,
{9208}{9295}naÊi Êeö zapeËaÊenu kovertu,|koju Êeö morati nositi za vreme svog putovanja."
{10372}{10443}"Budeö li sledio moje upute|i uspeo odmaÊi od logora,
{10447}{10538}moraö napustiti Bugarsku,|a da te ne primete.
{10541}{10622}Moraö uËiniti sve öto sam ti govorio,|ukoliko ûeliö pobeÊi.
{10626}{10675}Smestili bi te sutra u drugi logor
{10679}{10736}i ja viöe ne bi mogao paziti na tebe"
{11330}{11380}"Usmeri kompas na jug prema Solunu.
{11384}{11444}Trudi se stiÊi tamo Ëim pre moguÊe."
{12689}{12711}Ko je to uËinio?
{14041}{14102}Izlazi!|Izlazi odmah!
{14167}{14264}HoÊeö pobeÊi iz raja?|Tako si nezahvalan?
{15510}{15588}"Granica izmeu Bugarske|i GrËke je dobro obezbeena.
{15592}{15697}I dodatno osigurana ûicama za alarmiranje.|Ne dodiruj ih."
{16081}{16217}Eno ga! Hvataj!|Begunac!
{16241}{16289}Stoj! Stoj!|Stani deËko!
{16317}{16388}Vrati se!|KuËkin sine!
{16435}{16534}Stoj! Kuda misliö otiÊi?|Ne moûeö pobeÊi!
{16537}{16596}UhvatiÊu te, gade!
{16632}{16662}Stoj!
{16685}{16728}Stoj!
{16761}{16818}UhvatiÊu te!
{17033}{17087}"Usmeri kompas na jug,|prema Solunu,
{17090}{17145}i sakrij se na nekom|brodu koji ide za Italiju."
{18882}{18940}Ej! Zaöto si ostavio otvoreno?
{21062}{21097}Johannes...
{21122}{21154}jesam li mrtav?
{21193}{21216}Ne.
{21220}{21308}NeÊu uspeti pobeÊi.|PronaÊi Êe me.
{21311}{21402}Ne ako Êeö biti oprezan.|Niko te ne sme videti.
{21406}{21449}A ako te ugledaju,
{21452}{21511}okruûi se ljudima oko sebe.
{21514}{21540}Kako?
{21543}{21633}Znaö dosta jezika,|koje si nauËio od ljudi u logoru.
{21638}{21748}Sluöaj paûljivo...|da moûeö razgovarati s ljudima...
{21753}{21791}i da ih razumeö.
{21796}{21846}Prestraöen sam.
{21850}{21912}Ima mesta gde je jako lepo.
{21922}{21960}Video sam ih.
{21972}{22066}Ali veÊ odavno,|ih nisam video
{22087}{22131}Ti Êeö ih videti.
{22141}{22201}Zaöto ti ne poeö sa mnom?
{22212}{22254}To je tvoje putovanje.
{22286}{22374}Ja imam svoje.|- äta Êu traûiti?
{22390}{22461}äta Êu pronaÊi u Danskoj?
{22468}{22504}Slobodu.
{22526}{22586}Ali ja Ëak ne znam ko sam.
{22844}{22902}äta radiö na mojem brodu?
{22923}{22984}Nisi mi dirao Ëasopise, mali?
{23087}{23164}Idem te prijaviti kapetanu.|Nadrljao si, deËko.
{23167}{23246}Ne, molim ne recite mu!|Moram stiÊi u Italiju.
{23336}{23407}Ako ne me izdate,|daÊu vam ovo!
{23587}{23626}Sedefna dröka.
{23629}{23691}Slatki noûiÊ.|Izgleda sovetski.
{23694}{23786}Daj mi i kompas|i imaö pogodbu.
{23788}{23857}Ne mogu! Samo noû.
{23881}{23962}Znaö, mogu ga uzeti|i ipak te izdati.
{23966}{24033}No, ja sam Ëastan Ëovek.
{24037}{24136}Verovatno bi si navukao neprijatnosti|zbog nedovoljne paûnje...
{24140}{24198}Ok, napravio si pogodbu.
{24204}{24261}Roberto, jesi li pogledao skladiöte!|Izlazi gore!
{24264}{24333}Budi miran, kreÊem gore.
{24346}{24416}»uj, ne mogu rizikovati 
{24420}{24472}da te joö ko vidi dok|izlaziö na pristaniötu.
{24475}{24542}Pa kad se pribliûimo obali,|spustiÊu te s palube
{24546}{24598}i moûeö otplivati do kopna.
{24697}{24801}Ne brini, struja Êe ti|pomoÊi da dospeö do obale.
{24822}{24850}Spreman si?
{24884}{24912}SreÊno!
{26556}{26654}"Kad stigneö u Italiju,|okreni na sever, dok ne stigneö do Danske."
{28766}{28836}Zaöto te mrze tako jako, Johannes?
{28840}{28879}Jer mrze sve ljude,
{28883}{28934}koji ne veruju,|u ono u öta oni veruju.
{28938}{28996}Moji roditelji, zaöto nisu|verovali u isto u öto veruju straûari?
{28999}{29038}Jesam li zato ovde?
{29041}{29095}Ne znam niöta o tvojim roditeljima,
{29099}{29160}no izgleda da je tako.
{29164}{29205}Ne seÊam ih se.
{29235}{29286}Znaö li kakvi su bili?
{29292}{29358}äto su verovali?|Odakle smo doöli?
{29361}{29397}David,
{29400}{29445}Ne znam niöta o tebi.
{29448}{29489}Trebao sam umreti.
{29492}{29560}Ne reci to viöe nikada!|Niti ikada pomisli!
{29563}{29620}Zaöto ne?|NiËeg lepog nema ovde!
{29625}{29677}Koji je smisao ostati ûiv?
{29681}{29763}Jer dok si ûiv, moûeö promeniti stvari.|Ako si mrtav, ne moûeö.
{29768}{29870}UËini sve öto moûeö da ostaneö ûiv.|Pod svaku cenu. Idemo.
{30194}{30258}Znam, Ëitav ûivot|si proveo u logoru,
{30262}{30322}no postoji svet izvan njega.
{30328}{30398}A to je jedan|veoma opasan svet.
{30424}{30469}Ne veruj nikome!"
{31544}{31587}Lepo izgledaju, a?
{31591}{31637}Oprosti ako|sam te uplaöio!
{31639}{31694}éeliö dobiti malo hleba?
{31709}{31776}Da, molim.|- Imaö li iöta novca?
{31798}{31819}Ne.
{31822}{31879}Bojim se, moji hlebovi nisu besplatni.
{31882}{31920}Gde ûiviö?
{31970}{32028}U cirkusu sam.
{32043}{32084}U cirkusu, a?
{32087}{32177}Pa, taj neÊe stiÊi|za joö dve nedelje.
{32181}{32239}Mislim da si stigao malko prerano.
{32243}{32340}Gde mogu dobiti neöto|novca za hleb, gospodine?
{32377}{32433}Pogledaj ovu kuhinju!
{32436}{32463}Besprekorno Ëista.
{32466}{32550}a ovo... je tradicionalna|peÊnica na drva.
{32552}{32651}Znaö li kako hleb peËe|Abruci, dole niz ulicu?
{32654}{32688}Na plin!
{32691}{32809}A ljudi i dalje kupuju kod njega,|umesto kod mene! Neverovatno!
{32882}{32969}Znaö, pre no ti dam neöto hleba,
{32972}{33038}moraö za mene neöto uËiniti.
{33060}{33129}Moraö se nasmeöiti!|- Zaöto?
{33132}{33243}Zaöto? Jer Êeö imati|najbolji hleb u Italiji.
{33247}{33284}Eto zaöto.
{33465}{33538}Sveta Elizabeta,
{33541}{33663}deËko pita zaöto...|bi se trebao osmehnuti.
{33667}{33725}Misliö li da znaö kako?
{33734}{33765}Ko je to?
{33768}{33817}To je Sveta Elizabeta.
{33821}{33878}Pokroviteljka pekara.
{33880}{33964}Brine se o svakom ko treba pomoÊ.
{33967}{34024}Posebno o pekarima.
{34036}{34086}Trebaö se sam uveriti.
{34110}{34163}Uzmi ovo...
{34167}{34252}i moûda pomogne|nekad i tebi.
{34256}{34295}Kad veÊ ûeliö,
{34298}{34408}samo tu stoj, a ja Êu ti|izabrati jedan lep sveû hleb.
{35159}{35245}Ima neöto u njemu...lice...
{35249}{35298}njegove oËi...
{35303}{35382}Nisu oËi normalnog deteta.
{35385}{35441}Uite i sami se uverite.
{35515}{35591}Prijatelji ûele|s tobom razgovarati.
{35637}{35734}Samo ûele znati ko si.|Ne moraö zato brinuti.
{35800}{35873}Trebamo te pitati nekoliko pitanja.
{36026}{36078}Pokuöavam ti pomoÊi!|Moraö mi verovati!
{36082}{36112}Pusti me otiÊi!
{37047}{37129}"Putuj severno,|Ëim dalje moûeö.
{37137}{37179}SreÊa s tobom."
{37825}{37913}Postrojavanje! Odmah! Postrojavanje!
{37948}{38039}Odmah! 
{38046}{38084}Ko je to uËinio?
{38091}{38133}Ko je za to odgovoran?
{38196}{38250}Mora biti on! Znam to!
{38256}{38285}Ubij ga!
{38536}{38582}Sveta Elizabeta...
{38586}{38627}zovem se David.
{38630}{38718}Jedan pekar mi je rekao,|da pomaûeö ljudima.
{38721}{38763}éelim stiÊi u Dansku.
{38766}{38835}Trebam pomoÊ da|izaem iz ovih öuma.
{38838}{38890}Trebam stiÊi do Danske,
{38893}{38961}ali ne mogu, izgubio sam se.
{39881}{39922}"Niko te ne sme videti.
{39933}{39979}A ako te ugledaju,
{39983}{40054}okruûi se ljudima oko sebe."
{40109}{40158}"Sveta Elizabeta...
{40162}{40234}deËko ûeli znati zaöto|bi se trebao osmehnuti.
{40238}{40295}Misliö li da znaö kako?
{40621}{40720}Sveta Elizabeta... mogu li|te zamoliti za neöto drugo?
{41067}{41131}Odlazi! Molim te, odlazi!
{41134}{41177}Nisam te hteo naljutiti.
{41180}{41274}»asna reË, samo|sam se hteo uklopiti.
{41282}{41337}Dûina! Tiho!
{41340}{41428}äta radiö na mojoj lozi?|Jedeö moje groûe, a?
{41431}{41529}Pa, dobro je öto si tu,|jer trebam pomoÊ. Doi...sa mnom.
{41567}{41596}Hajde!
{41635}{41689}Bogu hvala, öto te Dûina uhvatila.|OËajna sam.
{41693}{41779}Trebam te da odneseö|vino na proslavu Betelievih.
{41783}{41831}Molim te, budi paûljiv.
{41837}{41957}TreÊe imanje niz cestu.|I evo tri lire zbog maltretiranja.
{42009}{42070}äta? Ne dam ti viöe!
{42073}{42153}Znate li na koju je stranu sever?|- LiËim li ti ja na kompas?
{42157}{42204}Nemam pojma.|Pitaj Betelieve. Hajde idi!
{42207}{42288}Idi! Idi!
{42377}{42474}Dûina! ZloËasti pas! Doi!
{43730}{43771}Napokon!
{43777}{43859}Gde si bio?|Trebao si biti ovde pre sat!
{43914}{44006}Dobre vesti, svima!|Vino je stiglo!
{44024}{44105}Bravo deËko!
{44139}{44213}NeÊu da mi se stranci|motaju na proslavi.
{44217}{44256}Nestani!
{45381}{45412}äta je s tobom bilo?
{45415}{45474}Trebaö iÊi u klozet, ili öta?
{45527}{45597}Kupio bih neöto hrane, molim|- »estitam.
{45601}{45718}Doöao si na pravo mesto.|- Trebam...jedan ovakav
{45721}{45795}ovo i...jedan ovakav.
{45799}{45836}Imaö novac?
{45860}{45934}A da ti prodam celi duÊan za to?
{45937}{46028}Da, i da ti dam i|ûenu i decu, takoe.
{46031}{46074}Gubi se!
{48172}{48238}David!
{48319}{48347}Mama...
{48442}{48502}Da me ikada sluöaö,|to se ne bi dogodilo!
{48506}{48586}»uj, smiri se. Ne moûemo|biti daleko od benzinske stanice.
{48589}{48634}Ne ûelim peöaËiti,|a da ne znam gde idem.
{48637}{48692}Ujedno, nemam obuÊu za hodanje.
{48744}{48775}Oprosti, mladi ËoveËe!
{48778}{48807}Trebam pomoÊ.
{48811}{48846}Znaö li za benzinsku|negde u okolini?
{48850}{48907}DeËko ne govori engleski.|Pitaj na talijanskom.
{48910}{48931}Dobro.
{49287}{49368}Moj demiûon|treba puniti.
{49371}{49456}Moj demiûon|treba puniti.
{49551}{49584}Ne?
{49587}{49630}Moj demiûon|treba puniti.
{49634}{49688}Video sam jednu niz cestu,|tamo to moûete obaviti.
{49692}{49768}O, govoriö engleski.|Super.
{49776}{49868}HoÊeö nam otiÊi po benzin,|platio bih ti?
{49871}{49903}Da, gospodine.
{50928}{50953}Gospodine...
{50956}{51014}voleo bih kupiti neke stvari.
{52753}{52777}Hej!
{52806}{52883}äta radiö na mom imanju?|Doöao si neöto ukrasti, a?
{53010}{53041}Hajde, bori se!
{53085}{53133}äta je to?|Negde si to ukrao?
{53136}{53218}Nemoj, daj mi to, to je moje!|- Niöta? Sad je moje!
{53305}{53361}Beûi, straöljivËe mali!
{53364}{53398}I ne vraÊaj se viöe!
{54632}{54671}Johannes...
{54747}{54795}ûelim pobeÊi.
{54872}{54970}Rekao si, dok ûivimo|moûemo neöto promeniti.
{54973}{55046}Kako znaö da Êe nas|ostaviti na ûivotu?
{55049}{55072}Ne znam.
{55076}{55134}Moramo otiÊi,|ako ûelimo preûiveti.
{55137}{55236}UbiÊe nas ako pokuöamo.|- UbiÊe nas ionako.
{55240}{55323}Trebamo uraditi sve,|da ostanemo ûivi.
{55326}{55384}Tako si rekao.
{55464}{55518}Strah te je.
{55532}{55561}Da.
{55579}{55603}Strah me.
{55614}{55696}Ne ûelim se viöe bojati,|nikada, Johannes.
{55737}{55785}Ni ja.
{56119}{56171}Carlo! PomoÊ!
{56270}{56320}PomoÊ!
{56363}{56410}PomoÊ!
{56597}{56630}PomoÊ!
{56756}{56793}Ne diöi!
{57508}{57560}Volim te, David.
{57825}{57858}Budan si?
{57885}{57911}Gledala sam te.
{57914}{57976}Htela sam biti sigurna, da si dobro.
{57999}{58053}Koliko sam dugo spavao?
{58056}{58097}Od juËe.
{58101}{58148}Sigurno si umoran.
{58152}{58216}Kad je doktor stigao,|nisi se mogao probuditi.
{58220}{58275}Mama te stavila pod pokrivaËe...
{58289}{58343}Gde mi je torba?
{58346}{58403}Kakva torba?
{58423}{58508}Niöta. Zbunjen sam.
{58512}{58550}Opekao si se...
{58554}{58607}ali ne jako.
{58610}{58675}I ja sam se opekla. Vidiö?
{58679}{58766}Nije straöno.|Sheko i Angelo su u nevolji.
{58769}{58830}Tata ih je oterao|leÊi bez veËere.
{58833}{58907}Jer se nisu|trebali igrati s vatrom.
{58942}{58990}Kako se zoveö?
{59049}{59114}David.|- Ja sam Marija.
{59136}{59189}Hvala öto si me spasio, David.
{59203}{59242}Tata je rekao da sam mogla umreti.
{59277}{59318}Mogao si i ti.
{59329}{59376}Veoma si hrabar.
{59504}{59566}Dali se ti smejeö?
{59573}{59638}Da. Zaöto pitaö?
{59656}{59690}Ne znam.
{59693}{59753}Moûda zato jer misliö da sam smeöna?
{59756}{59785}Ne.
{59788}{59868}Onda, jer bi me mogao nasmejati?
{59891}{59934}Probudio si se!
{59937}{59980}Marija, jesi li ga ti probudila?
{59983}{60022}Rekla sam ti da to ne radiö!
{60038}{60133}Zove se David, mama.|I probudio se sam.
{60137}{60174}Nisi li, David?
{60202}{60291}Sii i pripremi se za ruËak.|David Êe biti dole za minutu.
{60295}{60333}Da, mama.
{60500}{60554}Spasio si moju Mariju.
{60567}{60595}Zato,
{60599}{60655}dugujem ti ûivot.
{60725}{60768}OseÊaö li se dobro?
{60808}{60870}Trebala bih javiti tvojim|roditeljima, sad kad te nema.
{60874}{60912}Verovatno su veoma zabrinuti.
{60917}{61007}Raspitali smo se,|no niko ne zna odakle dolaziö.
{61013}{61065}Ne trebate biti zabrinuti za mene.
{61068}{61172}Ne ûivim blizu.|Ustvari putujem kuÊi.
{61175}{61206}Sam?
{61222}{61266}Kuda ideö?
{61320}{61366}RuËak je spreman, gospoo.
{61374}{61401}Hvala, Julia.
{61470}{61505}Pa...
{61516}{61565}kad si daleko od kuÊe,
{61581}{61652}ûelim da ostaneö|kod nas nekoliko dana.
{61655}{61723}Doktor je rekao, trebaö odmarati|dok rana ne zaraste.
{61726}{61809}Donela sam ti neku|staru Carlovu odeÊu.
{61819}{61887}Obuci se...i sii dole.
{61890}{61950}Napravili smo poseban|ruËak tebi u Ëast.
{61953}{62014}Svi su dole,|ûele te upoznati.
{62892}{62951}Hteo sam ti|reÊi da mi je ûao.
{62957}{63013}Nisam te hteo juËe istuÊi.
{63046}{63136}»uj, pomislio sam da si jedan od onih...|deËaka koji su Mariji ukrali bicikl.
{63142}{63207}I ti bi tako pomislio, ne?
{63211}{63274}Ne.|- Carlo, silazi na ruËak.
{63277}{63348}Zvala sam te pre pet minuta.|- Idem.
{63364}{63429}Molim te, ne reci roditeljima|öto se juËe dogodilo, uredu?
{63432}{63473}Nisam hteo.|Kunem se!
{63476}{63509}Vredi?
{63591}{63621}Hvala.
{63624}{63650}Idemo.
{64223}{64346}David, zovem se Gioovanni Reshigno|i Marijin sam otac.
{64350}{64415}»ast nam je,|öto si u naöem domu.
{64471}{64574}David, doi ovamo.|Marija ûeli da sediö pokraj nje.
{64615}{64665}Marija, znam da je|tvoj red za molitvu,
{64668}{64773}no ako nemaö protiv,|volela bih je ja danas izmoliti.
{64843}{64880}OËe naö,
{64884}{64966}zahvalni smo na predivnoj hrani,|koja se naöla na trpezi...
{64969}{65046}i dobroti kojom nas obasipavaö...
{65049}{65142}Posebno se ûelimo zahvaliti..|öto si nam poslao Davida...
{65146}{65203}Ëija je hrabrost i poûrtvovnost...
{65206}{65301}saËuvala naöu Êer Mariju...
{65310}{65429}Molim te, blagoslovi Davida|i celu njegovu familiju...
{65441}{65554}i uputi nas da nastavimo|Ëiniti dobra dela.
{65558}{65610}Hvala ti puno.
{65614}{65661}Amen.
{65702}{65787}O David, ne znam za tebe,|no ja sam izgladneo.
{65798}{65832}Jedimo!
{66269}{66306}U redu je, David?
{67440}{67486}Lepo je imati familiju?
{67528}{67567}Dopada mi se.
{67583}{67651}Nisam upoznala nikoga ko je nema.
{67664}{67700}Ti nemaö familiju?
{67711}{67781}Ne znam, ali voleo bih.
{67812}{67860}Mi ti moûemo biti familija.
{67863}{67927}Bio bi poËasni Ëlan.
{68183}{68227}Voliö li svog brata Carla?
{68230}{68300}Da, ali stalno mi se ruga.
{68303}{68410}Zove me "plaËljivica".|No ne plaËem viöe onoliko.
{68429}{68471}Ti ga ne voliö?
{68479}{68532}Ima puno ljudi koje ne volim.
{68535}{68570}Zaöto...ne voliö?
{68601}{68684}Jer je svet pun straönih ljudi, Marija...
{68695}{68764}ûele ti straöno zlo.
{68791}{68829}Video sam ih.
{68833}{68918}Ne misliö da smo mi...|straöni ljudi, zar ne?
{68922}{69002}Ne, uopöte.|- Dori i Carlo?
{69073}{69165}Uimo unutra.|éelim ti neöto pokazati.
{69174}{69242}Tata ima puno knjiga poezije.
{69245}{69299}»ita mi iz njih.
{69958}{70008}äekspir mi je najomiljeniji.
{70028}{70076}Voliö äekspirove pesme?
{70090}{70133}Nikada ih nisam Ëitao.
{70146}{70201}Ne znaö za niöta dobro...
{70204}{70229}je li?
{70304}{70344}äta je ovo?
{70403}{70439}To je Zemlja.
{70481}{70555}Nikada pre nisam|video takvu kartu.
{70560}{70605}Moûeö li ju Ëitati?
{70684}{70715}Ovo je Italija...
{70718}{70754}Ovo Rusija...
{70757}{70805}Ovo je Amerika...
{70808}{70857}Gde je Danska?
{70911}{70952}Eto tu.
{70956}{71059}Tu gore. ävajcarska i NemaËka|su izmeu nje i nas.
{71065}{71176}Jesi li kad bila u Danskoj?|- Ne. A ti?
{71212}{71260}Ja sam na putu tamo.
{71263}{71316}Jesi?|Zaöto ideö u Dansku, David?
{71320}{71431}Marija, pretpostavljam da ne bi|trebala bitiovde bez oËevog dopuötenja.
{71435}{71503}Oprostite. Htela sam Davidu|pokazati neke stihove.
{71506}{71532}U redu Marija.
{71536}{71599}Zaöto ne bi otiöla nabrati|cveÊa za ljude pre veËeri?
{71603}{71684}Moûe li mi David pomoÊi?|- Ne, David ostaje ovde.
{71688}{71749}Tata i ja ûelimo|s njime razgovarati.
{72020}{72078}Kako je ruka, David?
{72099}{72120}Dobro..
{72124}{72225}David, Giaanni i ja se ûelimo|uveriti da je s tobom sve u redu.
{72228}{72314}Jutros si rekao|da si na putu negde.
{72317}{72353}Kuda ideö?
{72365}{72424}Idem u...
{72427}{72485}trebam sustiÊi cirkus.
{72551}{72590}Cirkus?
{72594}{72665}Da, ja sam sa cirkusu.
{72668}{72728}äta radiö u cirkusu?
{72731}{72818}Puno stvari.|- Tamo su ti roditelji?
{72823}{72866}Da.
{72871}{72938}Zaöto su te roditelji|ostavili da putujeö sam?
{72942}{73051}Sve je u redu. Nemaju niöta protiv.|- David, da li nam laûeö?
{73055}{73090}Ne.
{73122}{73195}Laûeö li nas?
{73198}{73273}David, laûi nisu dozvoljene|u ovom domu.
{73277}{73348}Ne! Kunem se!|- Dobro...
{73350}{73390}Sve je u redu, David.|Sve je u redu.
{73394}{73463}David, ûelimo da nas uveriö,|da ne moramo brinuti.
{73466}{73561}Ne trebaö brinuti.|Ne bi ti mogli nauditi.
{73589}{73670}Oprosti öto smo te|pitali toliko pitanja.
{73754}{73821}Zaöto se ne bi otiöao|pripremiti za veËeru?
{74906}{74943}Ukrao si ga.
{75040}{75123}Kad nije bilo nikoga,|uvukao sam se u ured onog tipa.
{75129}{75184}Znaö li öta Êe biti|ako te otkriju?
{75189}{75215}Bilo je u njegovoj ladici.
{75219}{75301}ObeÊaj mi, kad nema nikoga,|neÊeö uzeti neöto öto nije tvoje.
{75304}{75353}ObeÊaj mi!
{75508}{75601}Ko je to uËinio?|Ko je za to odgovoran?
{75604}{75680}Mora biti on! Znam to!
{75690}{75775}Ubij ga!|Moramo ih nauËiti lekciju!
{76099}{76159}Ne, bio je on.
{77452}{77507}»uvaj je, Sveta Elizabeta.
{77524}{77615}Ja ne zasluûujem|da se brineö za mene.
{77619}{77669}Ja ne zasluûujem niöta dobro.
{77874}{77946}Molima te, kaûi Mariji,|da mi je ûao.
{77950}{78017}I ako sretneö Johannesa...
{78021}{78069}reci mu da mi je ûao, takoe.
{79824}{79897}Proleteri sa svih strana...|- Ujedinite se!
{79900}{80006}Proleteri sa svih strana...|- Ujedinite se!
{80462}{80510}To je bila velika greöka, momËe.
{80566}{80635}Nisam bio ja!|Nisam ja napravio!
{80910}{80938}Pustite me napolje!
{83154}{83209}Ne otimaj se!|Hajde!
{83275}{83309}Ostani tamo, momËe!
{83369}{83454}Stoj!|Stoj kad kaûem!
{83524}{83588}Hej, kamo misliö otiÊi?|Vrati se!
{83653}{83682}PriËekaj, mali!
{84195}{84289}Hej, prijatelju!|Vidim, stigao si do obale. Bravo!
{84292}{84343}Roberto?|Zaöto nisi na brodu?
{84346}{84429}Napustio sam ga.|Bilo je jako skuËeno.
{84432}{84522}Osim toga, uhvatili su|me u krai krompira.
{84525}{84562}HoÊeö se voziti?
{84576}{84603}SkaËi ovamo!
{84741}{84802}Kuda si krenuo?
{84815}{84873}U Dansku.|- Dansku?
{84898}{84968}Dug put.|Idem samo do Milana.
{84971}{85059}Nema veze..|- Bio sam u Danskoj pred nekoliko godina.
{85063}{85156}Prelepo je.|Puno lepih devojaka.
{86729}{86797}Dovienja prijatelju...|i sreÊan put!
{86801}{86856}Puno pozdravi Dansku|u moje ime.
{87853}{87884}Zdravo!
{87893}{87940}Znam kad ima nekoga.
{87944}{88045}Uvek osetim,|kad me neko promatra straga.
{88049}{88123}Neka vrsta psiho-energije, zar ne?
{88151}{88209}Doi, pogledaj ovo,|hoÊeö li.
{88236}{88272}Trudim se Ëitavo jutro
{88276}{88359}uhvatiti suötinu|ovog prelepog mesta.
{88365}{88441}ObiËno kad doem|ovde je maglovito,
{88444}{88531}ali danas izgleda| neÊe biti posla za mene.
{88548}{88592}äta ti misliö?
{88609}{88668}Veoma... je lepo.
{88672}{88748}Jeli je?|Meni izgleda malo beûivotno.
{88837}{88905}Imaö jako zanimljivo lice.
{88908}{88963}Dopuötaö li da te naslikam?
{88966}{89023}Kakvom bojom Êete|mi nacrtati lice?
{89064}{89084}To mi se dopada.
{89087}{89159}Mislim da si malo izazovan model.
{89162}{89226}Nemaö niöta protiv|posediti izvesno vreme?
{89251}{89348}Ja sam Sophis, usput...|kako se zoveö?
{89351}{89370}David.
{89373}{89445}David? Prelepo!
{89448}{89567}Michelloangelo je imao svog Davida,|ti Êeö mi omoguÊiti da imam svog.
{89782}{89840}Vrlo dobro...sediö mirno, Davide.
{89843}{89960}VeÊina tvojih vrönjaka ne bi|mogla biti ni minutu mirna.
{89980}{90031}Uvek im kaûem|öto se viöe budu micali,
{90034}{90100}toliko Êe slika biti loöija.
{90165}{90224}No to ne znaËi da|nesmeö micati usne.
{90227}{90319}Razgovaranje neÊe pokvariti sliku,|nisam tako loöa.
{90329}{90384}Ustvari, nemam  öta reÊi.
{90387}{90441}Dobro, onda ne moraö niöta govoriti.
{90446}{90502}Ima puno ljudi na ovom svetu
{90506}{90537}koji nemaju öta reÊi,
{90540}{90610}a usta ne zatvaraju|...veËito govore.
{90630}{90706}U pravu si öto|Ëuvaö svoje reËi.
{90710}{90775}To znaËi da Êeö|biti moÊan Ëovek.
{90778}{90830}Ne ûelim biti|Ëovek velike moÊi.
{90834}{90912}Onda ne moraö biti.
{90957}{91073}Budi sreÊan öto si ososba|koja moûe biti moÊna,ako to poûeliö.
{91141}{91186}Imam takvih problema...
{91189}{91245}s tvojim oËima...
{91257}{91342}Nikada nisam troöila toliko|crne boje, dosad.
{91361}{91448}Tako ozbiljne oËi.
{91513}{91592}Tako ozbiljno lice.
{91830}{91919}Joö nekoliko zavrönih|dodira i gotovi smo.
{91948}{92047}Moja je kuÊa blizu odavde.|volela bih te pozvati na ruËak...
{92051}{92123}Da te isplatim za|tvoju ljubaznost.
{92127}{92151}Gde ûivite?
{92156}{92239}Odmah preko granice.|U ävajcarskoj.
{92334}{92364}David,
{92368}{92467}potpuno si siguran da ti|roditelji dopuötaju putovati?
{92471}{92526}Sve je u redu.|Nemaju niöta protiv.
{92529}{92595}Ne ûive blizu granice, ionako.
{92615}{92654}Shvatam.
{92720}{92763}äta je to?
{92770}{92828}Blok za skiciranje.
{92833}{92886}Svi crteûi su mi unutra.
{92924}{93016}Mogu li ih pregledati, molim.|- Razume se.
{93020}{93080}Ali te upozoravam,|nisu jako dobre.
{93085}{93158}Napravila sam nekoliko|umetnina kad sam bila mlaa,
{93161}{93233}no nikad ih nisam dovröila.
{93239}{93319}ZapoËela sam ponovno slikati|pre nekoliko godina.
{93323}{93370}Samo za vlastito zadovoljstvo.
{93618}{93651}Ko je to?
{93655}{93784}Neki deËak, kog sam poznavala|pre dugo vremena.
{93818}{93887}Rekla sam ti da neÊe biti jako lepe.
{94011}{94084}Moram izaÊi napolje.|- äta?
{94088}{94149}Neöto se dogaa s tobom?
{94156}{94236}Moûeö raditi öta ûeliö,|ali rekao si da ûeliö videti ävajcarsku.
{94239}{94286}éelim.
{94412}{94460}Vidiö,
{94464}{94581}Sada Êe nam doÊi proveriti identifikacijske|dokumente. Imaö li ikakvih?
{94644}{94701}Ne.|- Nije toliko vaûno.
{94704}{94785}To nije opasna granica.|NeÊe biti problema.
{94795}{94837}Ok?
{94842}{94872}Da.
{95142}{95197}Dobar dan, gospoo.|- Dobro jutro.
{95201}{95264}Dokumente, molim.|- Da, naravno.
{95419}{95515}A dokumenti od deËaka?|- To mi je unuk, oficiru.
{95518}{95601}Napustili smo kuÊu u velikoj ûurbi jutros...
{95604}{95688}zaboravio je poneti identifikacijske papire.
{95747}{95791}Ne znam.
{95794}{95881}Imam nareenje proveriti|sve dokumente, Ëak i od dece.
{95926}{96011}Ne moûete li preskoËiti|koje pravilo?
{96015}{96068}Mali samo ûeli...smeniti vladu...
{96072}{96188}...skockati zakone|i brzo pobeÊi napolje.
{96277}{96374}Dobro gospoo Anderson,...|ugodan dan.
{96389}{96419}...I mladi ËoveËe...
{96423}{96552}Moûeö li nam poveÊati plate,|kad doeö na vlast?
{96792}{96846}Video si?|Nije bilo problema.
{96850}{96902}Sada moûemo otiÊi neöto ruËati.
{97100}{97176}Bojim se, da se ne otrujemo|od mog umeÊa kuvanja.
{97179}{97259}Puno je skuplje od|mog slikanja.
{97263}{97314}Meni izgleda kao|pravo slikarstvo.
{97317}{97354}PriËekaj malo.
{97357}{97464}Trebamo dodati moj poslednji|rad na zid galerije.
{97467}{97518}Pridrûi minutu,|hoÊeö li?
{97631}{97661}Hvala.
{97934}{97976}Tako ti izgledam?
{97979}{98074}Da. Takav si utisak ostavio na mene.
{98078}{98173}To se zove impresionistiËko slikanje.
{98188}{98239}Reci mi,
{98278}{98355}öta vidiö kad je gledaö?
{98402}{98441}Sebe?
{98446}{98553}Pa, da, no nisam to imala na umu.
{98557}{98626}Slike trebaö gledati...drugaËije.
{98630}{98702}Kao da gledaö neöto drugo.
{98706}{98751}Zadubi se...
{98754}{98840}da vidiö öto ti kazuje.
{99050}{99082}Dobro...
{99110}{99194}kad je pogledam deËaka na slici,
{99198}{99315}vidim vrlo inteligentnu...|vrlo ozbiljnu osobu.
{99319}{99366}I dobru osobu.
{99369}{99414}No...
{99447}{99547}ima neöto u oËima,
{99550}{99679}a i u licu, izgleda|nekako izgubljen i tuûan.
{99692}{99758}No to je jedino|öto mogu videti,
{99761}{99894}zato jer on ne dopuöta|da se vidi neöto viöe.
{99897}{100007}Zaista to sve vidite?|- Da. Vidim.
{100074}{100142}Opa, Ëaj je gotov.
{100328}{100423}Nadam se da je dovoljno hrane za tebe, David.|Ja ne volim jako puno jesti.
{100426}{100501}Znam da momci mogu|pojesti priliËno puno.
{100504}{100564}Dobro je.|PriliËno je dovoljno. Hvala.
{100568}{100594}Dobro.
{100620}{100707}Zdravo, Annet.|Hrana ti nije dovoljno dobra?
{100710}{100778}Ili si doöla pozdraviti naöeg gosta?|NeÊeö pozdraviti gosta?
{100790}{100835}Voliö li maËke, David?
{100839}{100887}Ne znam.|Pretpostavljam.
{100892}{100958}Upoznaö li Annet, zavoleÊeö je.
{100961}{101085}Veoma je slatka i graciozna,|nije li tako, maËkice?...
{101088}{101125}äta je to?
{101140}{101187}äta?
{101191}{101226}Ovo?
{101259}{101307}Medaljon.
{101319}{101423}Imam ga godinama.|Pripadao je mojoj majci.
{101443}{101480}PokazaÊu ti.
{101483}{101577}Otac ga je dao ugravirati, na poleini...
{101617}{101744}Dao joj ga je na dan venËanja.|"Za T., s ljubavlju, Jan."
{101836}{101930}To je onaj deËko,|koga ste nacrtali.
{101946}{101993}Da.
{102017}{102097}To je moj sin, Peter.
{102140}{102189}Bio mi je sin.
{102207}{102340}Umro je, ubrzo nakon|je snimljena ta slika.
{102355}{102446}äta se dogodilo?|- Pnumonija.
{102450}{102529}Nije bio krepko dete.
{102532}{102630}No bio je jako sladak.|Vrlo umiljat deËak.
{102636}{102679}éiveo je tu s vama.
{102682}{102782}Ne, tada smo ûiveli u Zurichu.
{102786}{102849}Dogodile su se neke stvari...
{102852}{102911}nakon Peterove smrti...
{102914}{102981}i odluËila sam se preseliti ovamo.
{102985}{103099}Ujedno, ko ne bi voleo|ûiveti ovde gore?
{103108}{103194}Mjesto je tako lepo.
{103200}{103276}Nije li tako, maËkice?
{103333}{103392}HoÊeö li ju malo pridrûati?
{103396}{103466}NeÊe te ogrepsti.|Ok.
{103618}{103664}Tako je meka!
{103706}{103744}I vibrira.
{103747}{103815}Prede, Davide.
{103818}{103888}Nikada nisi mazio maËku, do sada?
{103896}{103930}Ne.
{104282}{104340}Gde ûiviö, Davide?
{104785}{104818}Nigde.
{104903}{104942}Ja sam u cirkusu.
{104952}{104996}U cirkusu?
{105000}{105091}O, vrlo lepo.|Mora biti veoma zanimljivo.
{105094}{105161}Da, zaista.|Vrlo je zanimljivo.
{105170}{105229}»uj, ako nemaö gde provesti noÊ, 
{105233}{105304}veoma si dobrodoöao ostati ovde.|- Ne.
{105313}{105399}Ne mogu. Moram iÊi.|Ne mogu ostati viöe nigde nikada.
{105401}{105488}Davide, imaö li kakvih nevolja,
{105492}{105570}volela bih ti pomoÊi, kad bih mogla.
{105641}{105704}Molim vas,
{105708}{105786}nemojte me izdati.|- Izdati te kome?
{105789}{105824}Njima.
{105835}{105883}Njima, bilo kime.
{105886}{105990}NeÊu te predati nikome.|Zbog niËega!
{105994}{106096}Ovde si potpuno siguran, Davide.|Siguran si.
{106106}{106169}Od straûara?
{106181}{106243}Od svakoga.
{106253}{106353}Hteo bih ti reÊi sve, Sophis.|Ali ne mogu.
{106356}{106390}Ne mogu.
{106406}{106474}Davide, ne trebaö mi reÊi niöta.
{106477}{106545}éelim samo da znaö,|da si ovde van opasnosti.
{106549}{106620}I sve Êe biti u redu.
{107076}{107124}Spavaj dobro, Davide.
{107130}{107189}Sve Êe biti u redu.
{108220}{108317}Dobro jutro, Davide.|Nadam se da te nisam probudila.
{108354}{108405}Moram iÊi u selo.
{108407}{108494}ObeÊala sam doneti hranu|prijatelju koji je bolestan.
{108508}{108586}Moûeö iÊi sa mnom, ako ûeliö.
{108724}{108811}Zaöto ljudi rade uûasne stvari?
{108831}{108881}Kao öta?
{108889}{108996}Kao prebijanje ljudi, ubijanje,|zatvaranje u logor.
{109010}{109088}VeÊina ljudi ne Ëini tako neöto, Davide.
{109270}{109345}Moj prijatelj, Johannes,|uvek mi je govorio
{109364}{109403}"Ne veruj nikome!"
{109406}{109505}éivot ne bi imao vrednosti,|kad nikome ne bi verovao, Davide.
{109527}{109655}Moûeö biti oprezan,|no moraö verovati ljudima.
{109664}{109755}Kako znate jesu li|ljudi loöi ili ne?
{109758}{109881}David, veÊina ljudi je dobra.
{109892}{109984}Imaju familiju, i prijatelje.
{109988}{110097}I ûele proûiveti ûivot|öto sreÊnije mogu.
{110101}{110204}Dobro, uvek je bilo|i loöih ljudi na svetu.
{110207}{110296}I obiËno ih prepoznaö,|kad ih sretneö.
{110299}{110349}Ali ponekad ne moûeö.
{110397}{110460}No to te ne sme spreËiti
{110465}{110568}da ûiviö svoj ûivot|u potpunosti i slobodno.
{110572}{110634}Da naeö prijatelje,
{110637}{110726}i vidiö dobrotu u ljudima.
{110729}{110839}Jer ako tako ne uËiniö,|nikada neÊeö otkriti öto je sreÊa.
{111029}{111113}To je kuÊa moga prijatelja.
{111119}{111176}Ne moraö ulaziti, Davide.
{111180}{111289}Zaöto ne bi otiöao istraûiti.|ObiÊi duÊane.
{111293}{111410}NaÊi Êemo se u knjiûari,|nakon malo vremena. Ok?
{111510}{111575}To su dobri ljudi, Davide.
{111577}{111647}Ne trebaö brinuti o niËemu.
{111650}{111683}Ok?
{114815}{114844}Zdravo..
{114899}{114943}Zdravo i tebi.
{116520}{116602}Moraö uËiniti sve öto sam ti govorio,|ûeliö li pobeÊi.
{116606}{116654}Smestili bi te sutra u drugi logor
{116657}{116726}i ne bi viöe mogao paziti na tebe"
{116764}{116838}To je jedini naËin|da stigneö na sigurno.
{116845}{116892}Jesi li razumeo?
{116914}{116976}Znam, Ëitav ûivot si proveo u logoru,
{116981}{117045}ali postoji i svet izvan njega.
{117049}{117160}A to je jedan veoma opasan svet.|Ne veruj nikome.
{117214}{117247}I...
{117250}{117311}ûao mi je zbog tvog|prijatelja Johannesa.
{119765}{119875}Sophis, video sam pre takvu knjigu.
{119907}{119947}äta je to?
{119981}{120044}To je jedna prekrasna knjiga, Davide. 
{120048}{120150}Napisala je jedna ûena,|koja je izgubila muûa i sina
{120152}{120215}u Bugarskoj, nakon rata.
{120219}{120266}Suprug je bio doöao iz Engleske,
{120269}{120307}i kad je otiöao u Bugarsku
{120311}{120352}organizovati ustanak|protiv komunista,
{120355}{120430}poveo je deËaka i ûenu sa sobom.
{120433}{120530}Kasnije, svi su bili uhapöeni,|a Ëoveka i deËaka su ubili.
{120533}{120589}Jedan je straûar poznavao ûenu,|i joö od detinjstva
{120592}{120671}je bio zaljubljen u nju.
{120675}{120802}Sredio joj je laûne dokumente|i pomogao pobeÊi.
{120807}{120945}Jeli ta ûena... joö uvek ûiva?|- Da. éivi u Danskoj.
{125307}{125353}Ja sam David.
{125398}{125447}Znam, David.
{125451}{125498}Znam.
{125500}{126000}SUB BY JAP-KOKAN
{126025}{127525}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
