{40}{73}Ne znam. Smisli neöto.
{232}{273}Samo sam htjela razgovarati.
{274}{368}Mislila sam da bismo moûda|mogli otiÊi u kafiÊ ili neöto sliËno.
{371}{413}Oh, ûeliö kavu?
{414}{470}Ovdje ima kave,|imaju sve vrste piÊa.
{497}{576}Ah... moûda bolje neko tiöe mjesto?
{593}{682}Ovo mjesto moûe biti tiho. Sjedala|tamo na kraju su priliËno tiha.
{712}{755}DeËki kojim sportom se bavite?
{759}{791}Ah, igramo hokej.
{793}{827}O, ja volim hokej.
{827}{852}DeËki za koga igrate?
{853}{903}Igramo za Philadelphia Flyers.
{906}{948}Dakle svi ste iz Philadelphije?
{949}{987}Ne. Ne.
{987}{1019}Ustvari nitko od nas.
{1020}{1072}Imate li joö sve svoje zube?
{1073}{1128}Pa, imam sve zube, osim...
{1148}{1174}ovih.
{1181}{1206}HoÊeö ih isprobati?
{1206}{1242}Da, hoÊu.
{1341}{1364}Izgledam li seksi?
{1365}{1406}Da!
{1431}{1581}-== [ www.OpenSubtitles.org ] ==-
{1645}{1709}Definitivno bolje|izgledaju na njoj nego na tebi.
{1759}{1795}- Hvala.|- Baö slatko.
{1800}{1872}Onda hoÊemo li otiÊi u mirniji kutak?
{1877}{1942}Ne, ne, ne, ne, ne...
{1942}{1962}Kamo ideö?
{1962}{2025}Trebale smo imati|veËeras poslovni sastanak.
{2027}{2088}Poslovni sastanak? Poslovne ûene,|morate slaviti. Pobijedili smo veËeras. Idemo.
{2089}{2124}éelim se zabaviti s pobjednicima,
{2124}{2144}hajde Deb!|- Da!
{2144}{2202}Samo doi i ostani, pleöi s nama.
{2209}{2252}- Ok.|- Da!
{2261}{2311}Ok, ajmo do kurca plesati!
{2435}{2524}Ne sramite se, slobodno se spustite,|i popunite ove prazne stolice.
{2529}{2592}Hvala vam puno za dolazak,|ovo je tako uzbudljivo!
{2617}{2707}Po prvi put u viöe od trideset godina,
{2713}{2766}Graham Parker i  "The Rumour".
{3753}{3815}Gdje su mu oboûavatelji?|Pa, gdje su?
{3818}{3862}Teöko je gledati bend...
{3880}{3953}kada znaö da se svi u bendu sjeÊaju|iskrcavanja na Normandiju.
{4098}{4136}Pa, koliko je novinara doölo?
{4176}{4213}Ti to ozbiljno?
{4215}{4268}Nitko nije doöao!|Nitko.
{4274}{4310}Nitko nije ovdje?
{4311}{4355}O, deËko iz Green Daya je ovdje.
{4357}{4411}Da, Billie Joe, poslao sam mu mail.|On je oboûavatelj.
{4411}{4454}Moraö uslikati njih dvojicu.
{4454}{4535}Ne, kaûe da ne ûeli intervju,|on samo gleda koncert.
{4537}{4577}O, kako je bezobrazan.
{4579}{4635}"Ne volim...ne volim fotografiranje."
{4661}{4694}Odrasti, Green Day!
{4696}{4742}ZaËepi gubicu, Tom Selleck.
{5166}{5206}Baö je dobro öto si napravio ovo.
{5289}{5350}Pete, htjela sam da znaö da sam dobila|ponudu za posao od Sony Recordsa,
{5352}{5383}i mislim da Êu prihvatiti.
{5385}{5420}Ja sam radio za Sony.
{5422}{5457}Znam.|Tamo te vole.
{5460}{5548}- Sa kime si razgovarala?|- John Cleary.
{5571}{5665}- Ja sam zaposlio Johna Clearya.|- On je zaposlio mene.
{5667}{5695}äta ti znaö?
{5697}{5748}Govorio je sve najljepöe|o tebi.
{5750}{5816}Ne, on je kurac,|i sjebat Êe i tebe.
{5818}{5860}Ne ako dobro|radim posao.
{5876}{5955}Stvarno? Ja sam sklopio|posao sa Pearl Jamom.
{7171}{7199}Ti nemaö...
{7201}{7290}Da, ne bih ih nazvao|dobrim klasiËnim pokretima
{7310}{7345}ali si dala sve od sebe.
{7347}{7376}Ti si super za plesanje.
{7390}{7415}Hvala.
{7418}{7489}Imamo mali...mali tulum|u hotelu nakon ovoga,
{7489}{7531}trebala bi svratiti i, ah...
{7533}{7576}i druûiti se, u hotelu.
{7613}{7663}HoÊeö da ja doem u hotel?
{7666}{7708}Da. Htio bih da doeö...
{7737}{7774}u hotel sa mnom.
{7803}{7856}Pa, öto bi radili tamo?
{7859}{7955}Moûda moûemo naÊi neko tiho mjesto,|zabaviti se, i nekako vidjeti kamo to ide.
{7962}{8081}Napraviti to kako... odrasli ponekad Ëine, i...
{8087}{8132}Kao... seks?
{8140}{8177}Ah, mislim...
{8194}{8278}ako ûeliö, ako je to|na meniju, ali...
{8287}{8328}Ne pokuöavam to nametnuti.
{8333}{8382}Dakle ti bi radio seks sa mnom?
{8386}{8448}Radio seks? äto si ti Borat?
{8460}{8496}Jel' se ti meni nabacujeö?
{8497}{8589}Da, da, nabacujem ti se.|Zgodna si, kul si i draga si i...
{8591}{8627}imaö lijepe oËi.
{8688}{8718}éao mi je.
{8726}{8791}Udana sam, imam dvoje|djece i trudna sam.
{8856}{8938}To je ono öto zovemo|"hat-trick". Opa.
{8940}{8998}Oprosti, nisam ti rekla, da...
{8999}{9075}stvarno uûivam|jer si tako fin prema meni.
{9093}{9177}Ne, ja...nadam se, da ne|ispada previöe sladunjavo,
{9191}{9288}ali ah, mislim da se takva kao ti...|rijetko pronalazi.
{9289}{9316}Hvala ti.
{9320}{9364}I ja bi posve radio seks s tobom.
{9441}{9538}DeËki, to je bio spektakularno,|stvarno dobro odraeno, nevjerojatno.
{9539}{9583}- Hvala.|- Dobro, dobro.
{9611}{9633}Hej Graham!
{9636}{9663}Pete! Kako si, ËovjeËe?
{9675}{9730}Pa ah... doöle su prve brojke.
{9736}{9772}Da, tako je da. Ah...
{9782}{9825}Sretan? Kako izgleda?
{9833}{9882}Oko polovice tvoje zadnje ploËe.
{9885}{9956}Ah, dakle ti si oËekivao to prodati.
{9963}{10021}Viöe se ne prodaju.|Nekad su se prodavale.
{10024}{10115}Ali ne sad. Nisam seksi|öesnaestogodiönja curica.
{10117}{10171}Ali ja sam je htio prodati.|To je tako dobra ploËa.
{10172}{10202}OsjeÊam kao da sam te iznevjerio.
{10203}{10296}O, ne, ja Êu biti u redu, ËovjeËe.|Moj troökovi su tako niski.
{10301}{10348}Upravo sam dobio pjesmu u Glee.
{10353}{10420}Tip u invalidskim kolicima|pjevat Êe azijskim djevojka, vjerujem.
{10421}{10480}Ne znam, nikada nisam vidio|show, ali to mi je reËeno.
{10481}{10570}Tajna je, pobrini se|da imaö mala jaja.
{10572}{10615}To je kljuË ûivota.
{10619}{10660}Graham, nemam|mala jaja, u redu?
{10660}{10712}Imam velika jaja.|I moram pribaviti za njih.
{10712}{10739}Graham!
{10745}{10767}Hej, hej, öto ima?
{10768}{10813}- Billie! Hej, prijatelju!|- Kako si, ËovjeËe?
{10814}{10861}- Dobra jebena zabava, ËovjeËe!|- Ne stignem te vidjeti!
{10861}{10906}- Da, jebote!|- Hvala.
{10906}{10971}Inspiriran sam.|Odmah ûelim pisati jebene pjesme.
{10972}{11022}Inspiriran, ha? To me inspirira.
{11023}{11043}Idemo otiÊi na piÊe.
{11043}{11063}Idemo na piÊe.
{11063}{11091}Dobro.|Ideö s nama?
{11091}{11154}Ne, ne, ja sam...|Meni je dosta, vi deËki idite.
{11164}{11206}»estitam na Glee.
{11238}{11294}Da, hvala. Baö.|Vidimo se Pete.
{11302}{11330}- Dobro.|- Dobro, vidimo se.
{11331}{11353}Do vienja deËki.
{11373}{11407}Imaö pjesmu za Glee?
{11407}{11421}Da.
{11422}{11483}To rastura, to je toliko love, to je...
{11486}{11519}Dobro je da je za sve nas.
{12232}{12293}Zaöto si stavila zube|od onoga tipa u usta?
{12297}{12335}To je tako odvratno.
{12372}{12404}Bio je prljav.
{12405}{12456}Ne, nosio je kravatu.
{12459}{12505}- To je toËno.|- Nije bio prljav.
{12506}{12593}Kad sam ga poljubila, osjetila sam njegove|zubiÊe sa svojim jezikom.
{12595}{12626}- Stvarno?|- Da.
{12628}{12701}Bilo je kao ljubljenje bebe.|Francuski poljubac s bebom.
{12798}{12857}Mogu li te pitati neöto glupo?
{12860}{12931}Znaö li zaöto nam je|nestao novac iz trgovine?
{12944}{12974}Nestao vam novac?
{12976}{13050}Da. Oko 12.000 dolara.
{13051}{13094}Misliö da sam ga ja uzela?
{13127}{13240}Ne. Mislim, ja...pa, ne, ja jesam,|ali ne znam. Ali nisam...
{13240}{13260}Nisam ja.
{13262}{13385}Onda kako ûiviö u takvo lijepom|stanu i imaö takav öminkerski auto?
{13389}{13467}Da, u pravu si. Ahm... Vidiö,
{13513}{13609}ja...sam...pratnja.
{13626}{13698}PlaÊaju mi za izlaske.
{13705}{13731}Ti...
{13771}{13863}Ali samo tri do pet puta godiönje.|Deset puta najviöe.
{13897}{14038}Ali to nije tehniËki "prostitucija",|jer ne moram spavati s njima.
{14041}{14070}Ah pa, to je dobro.
{14071}{14174}Ali to uvijek Ëinim. Zbog toga to radim|samo Ëetiri do osam puta godiönje,
{14175}{14213}petnaest puta najviöe.
{14224}{14244}Hah.
{14248}{14294}Jedne godine sam to napravila dvadeset puta.
{14296}{14323}Pa...
{14328}{14371}Dokle god misliö da je sigurno.
{14374}{14401}To je sigurno.
{14404}{14471}Radim to samo deset do trideset puta godiönje.
{14484}{14537}Dakle, öto misliö tko krade novac?
{14558}{14595}To je jebena Jodi.
{14599}{14616}Ne.
{14620}{14669}Da. Ona je luda kurva.
{14718}{14745}Hah.
{14766}{14832}BuduÊi da si mi rekla, ja sam..|ûelim ti neöto reÊi.
{14832}{14870}Ti si trudna.
{14887}{14918}Kako znaö?
{14972}{14999}Opa.
{15015}{15047}Moûda bi trebala reÊi Petu.
{15048}{15080}Nisi joö rekla Petu?
{15081}{15106}Nisam joö rekla Petu.
{15106}{15122}Zaöto?
{15123}{15186}Ne znam.|Samo ûelim da me ûeli.
{15187}{15257}Ne ûelim da me ûeli, jer sam trudna.
{15262}{15351}Idi kuÊi popuöi mu kurac|pa mu reci i onda Êe to voljeti.
{15367}{15404}- Misliö?|- Bit Êe tako uzbuen.
{15411}{15467}Ili joö bolje, joö bolje...
{15470}{15541}trebala bi mu to|reÊi dok mu puöiö kurac.
{15542}{15592}Gledaj. "Ja sam trudna".
{15737}{15770}äto radiö?
{15776}{15825}Odgovaram na neke e-mailove.
{15833}{15878}U koje vrijeme moraö iÊi na posao?
{15881}{15921}Kao prije deset minuta.
{15946}{15983}éeliö kasniti?
{15990}{16053}Ne, ne smijem kasniti.|Ne danas.
{16318}{16394}Vidiö li da stojim tu pred tobom?
{16421}{16444}Polugola?
{16573}{16598}Da.
{16606}{16718}I zbog toga...|ne osjeÊaö niöta, ili...?
{16733}{16787}Ma daj.|Jel' pokuöavaö zapoËeti svau?
{16789}{16855}Ne, ne pokuöavam zapoËeti svau.
{16857}{16890}Pokuöavam te pojebat'!
{16892}{16930}O, Boûe, znaö öto? Samo...
{16948}{17033}Baö danas, od svih ovih dana|moraö mi dati mira.
{17039}{17076}U redu?|-  Kako god.
{17088}{17120}O, Boûe.
{17223}{17256}äto...?
{17280}{17352}Nisam shvatio je to bilo namjerno!
{17358}{17435}Nisam niöta rekao jer|nisam htio da ti bude neugodno.
{17435}{17493}Mislio sam da sam galantan.
{17532}{17576}U redu, u redu, ja sam seronja.
{17596}{17623}Boûe.
{17691}{17720}Znaö öto je tvoj problem?
{17722}{17805}Nikad ti nije pravi trenutak,|nikad nisi prisutan.
{17807}{17851}Nikad nisi u svom tijelu.
{17852}{17907}To nije toËno.|Meni...meni..je pravi trenutak.
{17907}{17974}Znaö kako znam? éelim|odjebati iz pravog trenutka.
{17981}{18018}Kunem se. To je samo...ja ne mogu...
{18020}{18070}ne mogu te pobijediti.|Jednostavno ne mogu.
{18071}{18109}Ne moûeö samo otiÊi od mene.
{18112}{18140}O, Boûe.
{18155}{18179}Hej!
{18181}{18234}Kako napreduje izdavaËka tvrtka, Pete?
{18247}{18282}äto? Nije dobro.
{18286}{18344}Joö uvijek Ëekam|da stignu brojke.
{18383}{18426}äto si Ëuo?
{18432}{18519}Neke brojke su stigle.|Manje je nego smo oËekivali.
{18570}{18650}A zaöto onda Larryu dajeö novac?
{18670}{18689}äto?
{18691}{18754}Znam sve.|Razgovarala sam s knjigovoom.
{18762}{18813}Dobro, znaö öto? Ne ûelim|ulaziti u neke gadnu svau.
{18814}{18893}Dakle moûemo li razgovarati na naËin|kako nam je terapeut rekao?
{18895}{18938}Fino. Fino!
{18963}{19083}Tuûna sam... kad si neiskren.
{19134}{19206}Razumijem da si tuûna|kad sam neiskren prema tebi.
{19215}{19293}Vrijea me kada me tretiraö s prezirom
{19294}{19352}i stjeraö me u Êoöak|pa pokuöaö natjerati u laû.
{19357}{19381}Ok.
{19387}{19471}Tuûna sam öto te je|tako lako natjerati na laû
{19472}{19526}jer si ti takva laûljiva vreÊa govana.
{19530}{19568}To nije...ne moûeö to uËiniti.|Ne moûeö to uËiniti,
{19568}{19623}terapeut je rekao da|me ne smijeö osuivati.
{19624}{19670}To nije osuda.|To je samo Ëinjenica.
{19690}{19715}Poöteno.
{19723}{19811}Istina je da ponekad uskratim istinu.
{19821}{19879}Ali samo zato öto sam prestraöen na smrt
{19879}{19970}od tvojih nelogiËnih luaËkih|pretjeranih reakcija.
{19971}{19997}Pa...
{20012}{20122}Vrijea me i reagiram|kad si takvo nepoöteno govno
{20123}{20190}da posuujeö ocu novac|bez da mi to kaûeö,
{20192}{20238}dok tvoja diskografska kuÊa|ide u steËaj
{20239}{20321}a mi smo na rubu gubitka|naöe jebene kuÊe!
{20652}{20697}O Ëemu joö laûeö?
{20711}{20779}Uzimam Viagru veÊ dvije godine.
{20780}{20905}Neöto prije pojeo sam 6 kolaËiÊa|i moj kolesterol je 305.
{20909}{20957}Srce mi moûe eksplodirati svake sekunde.
{20958}{21007}Ovo bi mogle biti moje zadnje rijeËi.
{21014}{21095}O! I dao sam Charlotti antibiotike|dok ti nisi gledala.
{21097}{21183}Zato joj uho ozdravilo.|Dakle, idi jebi svog vraËa.
{21223}{21310}Da li mi joö uvijek radimo...|ono öto radimo?
{21329}{21379}To me ne Ëini sretnom.
{21382}{21455}Ti nisi sretan. Ti me ne voliö.
{21459}{21549}OsjeÊam to. Nisam slijepa.
{21573}{21670}Isuse. Mi smo kao poslovni suradnici.
{21676}{21755}Mi smo kao brat i sestra.|Nema viöe strasti.
{21756}{21803}Nismo poput brata i sestre.|Znaö öto smo mi?
{21803}{21885}Mi smo poput Simona i Garfunkla i|nekako si me pretvorila u Garfunkla.
{21888}{21923}Nemam pojma öto to znaËi!
{21925}{21949}Art Garfunkel!
{21949}{22037}äto ne valja s Art Garfunklom?|Ima prekrasan glas.
{22038}{22097}Ima nevjerojatan glas.|Sve je mogao opjevati,
{22097}{22159}ali öto hoÊu reÊi je,|da si me pretvorila u njega!
{22160}{22194}O Ëemu dovraga priËaö?
{22195}{22240}äto...|- Simon ga kontrolira!
{22242}{22336}To je zato Simon|piöe jebene pjesme!
{22343}{22384}On je bolji.
{22390}{22424}Znaö öto? Vidim naËin na|koji gledaö naöu djecu.
{22425}{22482}Imaö toliko ljubavi i|suosjeÊanja za njih.
{22482}{22537}Mene nikada ne gledaö tako. Nikada.
{22544}{22633}Bismo li joö uvijek biti zajedno, da|nisam zatrudnjela prije 14 g...?
{22634}{22700}Znaö öto? NeÊu tim putem. To...
{22727}{22755}Bismo li?
{23127}{23149}Ok.
{23226}{23289}Znaö öto? »ak niti ne|ûelim roendan ovdje.
{23291}{23324}Moraö ga otkazati.
{23327}{23416}Ne, neÊu. VeÊ sam platio|dostavu, stavio polog,
{23416}{23466}i siguran sam do kurca|da neÊu sve nazivati
{23467}{23520}dva dana prije,|jer si ti promijenila miöljenje.
{23669}{23726} Vaöa djevojka nije ruûna </ i>
{23756}{23802} Zapravo Larry, ona nije moja djevojka, </ i>
{23802}{23851} ona je samo|- To je kul, prijatelju. </ i>
{23852}{23899} Ne moraö objaönjavati|meni svoju djevojku</ i>
{23899}{23918} Ali ona nije..</ i>
{23919}{23991}Moûeö li, molim te,|prestati lizati svoje prste?
{24021}{24092}Znaö li koliko je|bacila na tvojim rukama?
{24098}{24143}A ti ih stavljaö u usta.
{24154}{24194}To je odvratno. Prestani.
{24285}{24312}Prestani!
{24314}{24333}Ubit Êu te!
{24334}{24380}Hej! Sadie! Dosta!
{24383}{24417}Dobro, nikoga nije povrijedila.
{24417}{24461}éeliö li reÊi neöto,|samo drûi jezik za zubima.
{24462}{24533}Nikad nisi draga prema njoj|i sad je agresivna prema tebi.
{24534}{24584}Rekla sam ti da Êe se to dogoditi.
{24766}{24825}Muka mi jer se svi svaaju.
{25323}{25438}éao mi je öto misliö da sam|odvratna. U pravu si. Pusa. Charlotte.
{25772}{25844}äto misliö da Êeö|biti kad odrasteö?
{25907}{25957}Ne znam. Hm..
{25995}{26026}Ne znam.
{26047}{26091}Misliö da bi htjela djecu?
{26103}{26133}Mm-hmm. Samo jedno.
{26133}{26170}Samo jedno? Zaöto?
{26172}{26300}Jer ako imam dvoje onda|Êe se drugo...svaati s onim drugim.
{26303}{26361}Jesi li tuûna kad se svaate?
{26379}{26452}Ne ûelim da se itko svaa.
{26627}{26664}Volim te.
{27358}{27453}Zaöto nitko ne govori?|Zaöto je to tako tiho?
{27524}{27568}To su zvuci tiöine.
{27757}{27826}d ja ne mislim da mogu|stvarno preûivjeti...
{27972}{28047}d molim se za kraj vremena,|to je sve öto mogu uËiniti
{28102}{28292}d Moliti za kraj vremena, tako|da mogu zavröiti svoje vrijeme s tobom.
{28297}{28330}d I to je bio davno i to je bio daleko,|- Prestani tata.
{28330}{28367}d I to je bio davno i to je bio daleko,
{28367}{28426}d to je puno bolje nego öto je to danas.
{28426}{28481}Kako Êeö tih pojesti?
{28488}{28517}Koliko god poûelim.
{28529}{28570}ReÊi Êu te mami.
{28571}{28620}Pokuöaj. Pa Êeö vidjeti öto Êeö dobiti za BoûiÊ.
{28631}{28661}Niöta.
{28682}{28745}Cinkari zaglave u buhari.
{28750}{28787}Zapamti to.
{28908}{28939}Hej, Peter.
{28941}{28969}- Bok!|- Bok.
{29075}{29119}Dobro. Tu smo.
{29135}{29167}Dobru zabavu.
{29183}{29210}Peter?
{29224}{29251}Peter!
{29293}{29313}Bok!
{29316}{29343}Catherine.
{29346}{29378}Josephova majka.
{29379}{29431}Oh, dobro. Znam te.|Bok, Catherine.
{29431}{29492}Naöa djeca su iöla u ökolu|zajedno osam godina.
{29493}{29526}Ja...oprosti.
{29535}{29566}Pozdrav, Joseph.
{29604}{29670}»ujem da naöa|djeca Ëavrljaju online.
{29672}{29738}Da? »ula sam da je tvoja supruga|vriötala na mog sina,
{29738}{29763}i to mi nije pravo.
{29764}{29783}Molim?
{29784}{29828}Ona je vriötala na mog sina.
{29830}{29914}Zar ne? Prijetila ti je?|Psovala ga je.
{29919}{29960}Hej, on je trinaest godina|za boga miloga.
{29961}{29999}Koji je vrag s njom?
{30000}{30074}Hej, bolje provjeri koje lijekove uzima|i daj joj öto treba.
{30075}{30129}Ok, znaö,|zaöto ne...zaöto ne...
{30134}{30227}odjebeö, jer priËaö o mojoj|dragoj, slatkoj supruzi.
{30229}{30263}- Oh, ja da odjebem?|- Da, ti odjebi,
{30263}{30338}jer tvoje dijete je ûivotinja.|On je jebena ûivotinja.
{30339}{30393}Zaöto mu ne staviö uzicu?|- Okreni se. Okreni se, okreni se!
{30394}{30417}Okreni!
{30419}{30493}Ako mi opet uvrijedi kÊer,|zgazit Êu ga jebenim autom.
{30497}{30567}Kuûiö? U stvari, ako budeö opet vrijeala|suprugu, znaö öto Êu uËiniti?
{30567}{30611}DoÊi Êu ti u kuÊu dok budete spavali,
{30612}{30683}uzet Êu tvoj iPad|ili tvoj iPod ili iMac,
{30683}{30723}i gurnut Êu ih u tvoju jebenu i-PiËku.
{30724}{30802}Nemam niöta za izgubiti.|Tvoj klinac je problem.
{30803}{30889}Moje dijete je jebeni aneo.|Nemam vremena za ovo sranje.
{30890}{30968}Joö se suzdrûavam.|Ali da nismo u ökoli...
{31004}{31061}Dirao si moje...|Dirnuo si me?
{31065}{31114}- Nisam te dirao.|- Dirnuo si gornji dio grudi!
{31115}{31167}Nisam. Nisam. Tu ravno|ispod ramena.
{31169}{31238}Ravno ovdje. Ti si zapravo...|Pogodio je moju bradavicu!
{31239}{31259}Tvoju öto?
{31263}{31285}Ti si luda!
{31285}{31310}Zaöto bi to uËinio?
{31310}{31336}Takli ste maminu bradavicu?
{31337}{31397}Upravo je dodirnuo moju bradavicu!|Zaöto bi mi to uradio?
{31397}{31428}Bocnuo sam te po ramenu.
{31428}{31463}Bradavice su mi vrlo visoko.
{31465}{31493}Dotaknuo sam tvoju koöulju.
{31493}{31525}äto misliö da je pod koöuljom?
{31525}{31560}- Taknuo sam...|- Grudi su mi ispod koöulje.
{31560}{31605}Tvoj rame, rame.|Upravo je dotaknuo moje grudi.
{31606}{31676}Pa, to je smijeöno mjesto|za rame. Na mojoj sisi!
{31677}{31725}Hej! Djeca su okolo.
{31727}{31799}Ovo nije gotovo. Ovo nije gotovo.|Zaûalit Êeö.
{31801}{31856}Idemo. Idemo, idemo, idemo!
{31859}{31914}A zaöto bi, jebote, povjerovali Desi?
{31920}{31963}Upravo si priznala.
{31978}{31999}Jesam li?
{32002}{32070}Ukrala si 12.000|dolara od mene Jodi,
{32070}{32115}i ûelim da mi ih vratiö.
{32117}{32172}Mogu li bar dobiti preporuku?
{32173}{32261}»uvala si mi djecu|dok si bila na oxycontinu.
{32262}{32289}Oksikodonu.
{32290}{32323}Dobro, oksikodon.
{32323}{32350}Oxyconten.
{32353}{32378}Oxyconten?
{32379}{32404}Oxykitten.
{32406}{32439}äto je Oxykitten?
{32448}{32468}Miijauu.
{32473}{32566}Jodi. Dovela si me u opasnost.|Mene i moju obitelj.
{32570}{32606}To je bio vapaj za pomoÊ!
{32622}{32649}U pomoÊ!
{32658}{32685}U po-moÊ.
{32688}{32729}Zaöto mi ne pomognete?
{32735}{32784}Zaöto mi ne pomognete?|PomoÊ.
{32791}{32828}PomoÊ.
{32836}{32882}PomoÊ.
{32899}{32935}Zaöto mi ne pomognete?
{32940}{32974}Jesi li i sad napuöena?
{32977}{33026}Pomozite mi!
{33093}{33127}Je li to za mene?
{33129}{33156}Jesu li to policajci?
{33163}{33194}Je li ovo namjeötaljka?
{33196}{33233}Trebam iÊi.
{33235}{33274}Ok, vidimo se kasnije.
{33292}{33335}Jebi se, Debbie.
{33350}{33388}Jebi se.
{33426}{33484}Da li bi mogao|da mi posudiö malo novca?
{33487}{33589}- Volio bih da ti posudim novac, ali...|- Hvala.
{33592}{33643}- Ali ne mogu.|- Zaöto?
{33656}{33744}Ne bih ûelio da ugrozim odnose
{33746}{33837}sa nekim do koga mi je stalo|tako öto bih mu posudio novac.
{33847}{33882}Gledaj dokle smo doöli
{33884}{33980}da moûeö da doeö kod mene po savjet|i da si u stanju da me traûiö novce.
{33992}{34070}Da te pitam neöto. Koga viöe|voliö Simona ili Garfunkela?
{34072}{34130}- Garfunkel.|- Stvarno? Garfunkel?
{34132}{34178}Da, on ima aneoski glas.
{34180}{34280}Ima odliËan glas, ali öta je sa|Simonom? On je napisao pjesme.
{34282}{34391}Koga briga? Svi piöu|pjesme. Koliko ima pjevaËa?
{34394}{34487}- Simon je takoer dobar pjevaË.|- Art Garfunkel je cijeli hor u jednom Ëovjeku.
{34488}{34553}Da li si ikada Ëuo Paula Simona|da pjeva "Bridge Over Troubled Water"
{34556}{34662}sam na koncertu? To je noÊna mora.|Kao kad ökripiö noktima po ploËi.
{34681}{34739}Ima li öansi da ja grijeöim|u vezi svega?
{34741}{34804}Definitivno. Naravno.|Apsolutno.
{34834}{34910}Joseph je bio jako uzrujan|kada sam razgovarala s njim o tome,
{34918}{34983}pa sam mislila da je vaûno da se...
{35002}{35044}udruûimo i to razrijeöimo.
{35046}{35079}Apsolutno.
{35082}{35136}Ah, morat Êemo to razrijeöiti, ali
{35141}{35196}Debbie je, ah, rekla mom sinu da
{35201}{35273}izgleda kao Tom Petty,|u negativnom smislu -
{35274}{35297}Tko je Tom Petty?
{35298}{35342}Znaö ti dobro tko je Tom Petty.
{35346}{35417}I rekla je da, ako se to|opet dogodi, ona Êe
{35418}{35500}"sj..... njegovo malo dupe."
{35505}{35547}Baö je to rekla.
{35566}{35627}Jesi li ozbiljna? Nisam rekla.
{35633}{35688}Ne bi nikada. Djetetu?
{35696}{35824}Tvoj sin veÊ mjesecima oskvrnjuje|Facebook stranicu moje kÊeri.
{35829}{35864}Ovi ljudi su laûovi.
{35868}{35913}On je rekao da mi je sin ûivotinja,
{35914}{36001}i ako ga ne budem drûala na uzici,|zgazit Êe ga autom.
{36007}{36029}Jeste li to rekli?
{36030}{36072}To je...to je smijeöno.
{36075}{36110}Tko govori tako?|- Ti.
{36111}{36132}Nije to rekao.
{36133}{36189}- Dobro, ma znaö, ono öto sam rekao...|- Meni je rekao!
{36192}{36250}...öto sam rekao je da moramo|dodatno pripaziti na naöu djecu
{36250}{36317}jer sa svim tim tehnoloökim napretkom,
{36318}{36373}trebaju nauËiti odgovorno koristiti tehnologiju.
{36373}{36424}Ne, ne, öto on...ono öto mi je rekao,
{36424}{36452}je...nazvao me "i-PiËkom."
{36453}{36493}- äto?|- RjeËnik Catherine, rjeËnik!
{36493}{36519}Samo ga citiram!
{36520}{36624}Kako Êu prenijeti öto su mi ova|dva muda rekli ako to ne ponovim.
{36625}{36668}Moûete li molim ne govoriti|tako, Catherine?
{36668}{36705}Glazbenik ima probu u susjednoj sobi.
{36706}{36748}Oprosti, jebeni glazbeniËe.
{36761}{36842}Moûda da viöe liËim na|par ovih laûnih seronja,
{36843}{36882}izgledaju kao da su u reklami za banke.
{36884}{36913}Baö tako izgledate.
{36915}{36971}Kao da ste usrani par|iz reklama za banke.
{36975}{37036}Ovaj razgovor je beskoristan.
{37037}{37104}Sad bih se najradije protegnula unazad i
{37105}{37186}i raspalila vas oboje s nogom po zubima.
{37189}{37229}Vi me stvarno plaöite.
{37229}{37283}To se dogaa kad|ötakora stjerate u kut.
{37284}{37341}Stjerajte me u kut,|ja Êu si progristi jebeni put kroz vas.
{37343}{37372}Progristi Êu put kroz vas.
{37375}{37410}Catherine, moûete bolje od ovoga.
{37411}{37478}Jebi se, Jill. Ti si|straöno jebena ûena.
{37480}{37564}To je razlog zaöto te svi mrze, Jill.|Ovakvo sranje.
{37568}{37647}Nedjelotvorna, jebena usrana kosa.
{37665}{37712}I drago mi je öto ti je suprug umro.
{37722}{37795}Jer si jebeni öupak.|Vjerojatno se ubio.
{37806}{37863}Ok, Catherine, mislim da smo|shvatili öto se dogaa.
{37880}{37930}Sad znate s Ëim se moramo nositi.
{38975}{39017}NeÊu jesti tu piletinu.
{39023}{39052}Zaöto ne?
{39072}{39126}Htjela bih biti vegetarijanac.
{39128}{39169}Moûeö li postati vegetarijanac sutra?
{39170}{39185}A-a.
{39186}{39245}Vi ste Ëitali moje poruke?
{39258}{39279}Ne, nismo.
{39280}{39303}Da, jesmo.
{39304}{39347}Mi bismo trebali paziti na vas.
{39349}{39379}Kako si saznala?
{39380}{39454}Joseph mi je rekao da ste se|iskalili na njega i njegovu mamu,
{39455}{39505}i da ste puknuti, i s tim se slaûem.
{39506}{39550}OK. Nemoj vrijeati.
{39554}{39649}Vi me vrijeate. »itanje mojih poruka je|kao da Ëitate moj dnevnik.
{39650}{39728}A ti si stvarno bila divna na iChatu.|Bili smo jako ponosni na tebe.
{39729}{39786}Da, htjeli smo ti vratiti raËunalo i telefon.
{39787}{39816}Jebite se!
{39824}{39883}Ok, dobili smo prvi sluûbeni|"Jebi se."
{39884}{39954}Ok, tako ne govorimo|jedni drugima u ovoj kuÊi.
{39955}{40031}Vi si meusobno|tako govorite cijelo vrijeme!
{40037}{40122}I Josephu i njegovoj mami.|Natjerala si Josepha na plaË.
{40129}{40222}Joseph je zaljubljen u tebe.|Voliö djeËaka koji plaËe.
{40223}{40269}äuti, Charlotte.
{40270}{40366}Vi tako oËajniËki ûelite da|budem savröena i da ne grijeöim.
{40367}{40423}Pa, vas dvoje ste jebeno ludi.
{40424}{40445}Ok.
{40446}{40520}Sve öto radite je svaa. Ili se|ne svaate, öto je joö gore
{40520}{40579}jer izgleda da se|mrzite tjednima.
{40580}{40639}Opsjednuti ste svakom sitnicom koju napravim,
{40640}{40738}i ne vjerujete mi i ne vjerujete u mene,|i veÊ mi je jebeno muka od toga!
{40745}{40782}Da, rekla sam "jebeno".
{40786}{40822}Jebeno, jebeno, jebeno.
{40825}{40931}Kaznite me zauvijek. Nije me briga.|Nije me briga ni zaöto.
{40949}{41095}Mrzim sve, svi su poludjeli i|ne briga me ako nemam prijatelja.
{41112}{41159}Jesi li joö uvijek uzrujana zbog "Losta"?
{41161}{41194}Naravno da sam uzrujana zbog "Losta"!
{41194}{41290}Uzeli ste mi to sranje prije|nego sam vidjela dvije zadnje epizode!
{41300}{41348}Sad ne znam koji se kurac dogaa!
{41459}{41511}Ona postaje baö poput nas.
{41527}{41630}Nadam se da nikada neÊu dobiti mjeseËnicu,|ako je to ono öto se dogaa.
{41939}{41982}Gdje si to naöla?
{41990}{42025}Ukrala sam ih.
{42160}{42198}Hvala ti.
{42227}{42256}Sitnica.
{42343}{42422}Naöa djeca su luda.|I to je naöa greöka.
{42438}{42515}Misliö li da moûemo uËiniti|da okrenemo stvar, ili...?
{42516}{42586}Sadie je trinaest.|Mogla bi biti izgubljen sluËaj.
{42587}{42666}Mislim, gdje je nauËila takav|rjeËnik? Mi tako ne govorimo.
{42667}{42707}Nemam jebenog pojma...
{42717}{42784}Misliö da je Sadie ovako|luda zbog nas?
{42786}{42852}Ili su to hormoni i "Lost".
{42857}{42949}J. J. Abrams.|On uniötava naöu kÊer.
{42950}{42968}Da.
{42969}{43009}Taj jebeni ötreber.
{43012}{43074}OsjeÊam se loöe zbog nas!|OsjeÊam se loöe zbog nas.
{43075}{43170}Odjednom smo kao postali|magnet za negativnosti.
{43173}{43219}Zaöto nas ljudi napadaju?
{43232}{43316}äto smo napravili?|Dajemo sve od sebe.
{43331}{43367}HoÊemo li priËati o naöoj svai?
{43371}{43495}Mislim da smo pod velikim stresom. Ajmo ovaj put|samo pustiti da proe od sebe.
{43498}{43527}Da.
{43529}{43566}Dajmo mira jedno drugom.
{43567}{43616}Dobro, super. Hvala ti.
{43619}{43693}I ûao mi je zbog oca.|U pravu si. Ovo je...
{43717}{43815}éao mi je öto je on jedna|beskrajna skitnica.
{43837}{43944}Istina je, ovo nije zbog nas.|RijeË je o naöim roditeljima.
{43949}{44015}»ak nismo ni ljuti jedno na drugo.|Ljuti smo na njih.
{44015}{44058}ToËno!|ToËno.
{44062}{44136}Hajdemo da im oduzmemo moÊi,|tako öto Êemo ih voljeti.
{44158}{44184}Moûemo li to da napravimo?
{44186}{44224}Da.
{44230}{44256}Hvala Bogu.
{44274}{44324}Nekako se veÊ bolje osjeÊam, a ti?
{44332}{44366}-A ti?|-Da.
{44370}{44413}-Volim te.|-I ja tebe volim.
{44510}{44576}Nije do nas, to je do njih.
{44586}{44616}Totalno.
{44900}{44942}äto radiö?|Moramo se spremiti za zabavu.
{44944}{45009}Sad sam pogledala zadnju epizodu "Losta".
{45051}{45077}Ok.
{45088}{45157}Znaö öto? Nemamo|vremena za to baö sada.
{45160}{45192}Dolazi nam puno ljudi.
{45196}{45227}Svi su mrtvi.
{45241}{45265}äto?
{45276}{45361}Jack, Kate, Sawyer...
{45365}{45440}- Ne zanima me serija sada.|- Jin, Sun...
{45445}{45507}Ok? Samo hoÊu da odeö pod tuö,|obuËeö se.
{45509}{45538}- Hajdemo to staviti na Ëekanje!|- Walt, Juliet...
{45545}{45584}Svi ti ljudi.
{45588}{45619}Ne razmiöljaj o "Lostu" danas.
{45621}{45693}Sutra, "Lost". Cijeli dan.
{45698}{45777}Jack? Nema öanse. Stvarno?|Upravo sada, tuö.
{45782}{45841}Ja ne ismijavam|tvoj glupi Mad Men!
{45849}{45902}Prije svega, ja se ne|uzbuujem zbog Mad Mena.
{45907}{45943}Zato öto je Mad Men koma!
{45945}{45991}Kroz öto je sve Don Draper proöao
{45993}{46065}tuËe sve öto Jack izvodi|na nekom jebenom otoku.
{46067}{46134}Gomila ljudi puöi|u uredu, to je glupo.
{46145}{46201}Puno je viöe od toga.|I ti ne moûeö uopÊe
{46203}{46264}da razumijeö kako je bilo|öezdesetih godina.
{46266}{46315}Ti plaËeö tokom Med Mena.
{46317}{46422}- Ja ne plaËem. Ja to cijenim.|- Kako da ne.
{46424}{46471}OdvraÊaö me od teme.
{46475}{46524}Molim te, samo se obuci.
{46637}{46680}- Pozdrav!|- Bok.
{46682}{46720}Tako mi je drago da si ovdje.|- Da.
{46721}{46765}Trebam potporu u|sluËaju da postane Ëudno.
{46767}{46808}Oh! Dobro, spremna sam te uprijeti.
{46817}{46872}- Tako. Uzmi ove salvete.|- Uprimo.
{46957}{47011}Dakle ah, dakle to je|djevojka koja radi, ah,
{47012}{47045}to je djevojka koja radi za vas.
{47045}{47101}- Da, to je ona.|- ... radi za Debbie.
{47103}{47129}»ini se fina.
{47143}{47198}Supruga mi nikada ne bi dopustila|imati zgodnu radnicu kao öto je ona.
{47199}{47224}- Da?|- Ne.
{47227}{47273}Svaka ûena koja radi za nas...
{47277}{47334}izgleda kao da je preûivjela|neku straönu nesreÊu.
{47468}{47550}Ti si spokojna kad je to|u blizini tvoga muûa?
{47553}{47610}Ah. Pete ne bi znao|öto uËiniti s tim.
{47630}{47675}Misliö da naöe ûene|upravo gledaju prema nama?
{47676}{47706}- Oh, svakako.|- Da.
{47716}{47759}Oni izgledaju kao pedofili.
{47897}{47917}Hvala.
{47917}{47979}.. I djevojke su tako uzbuene.|Svi su vani.
{47979}{48024}- Bok. Sretan roendan.|- Bok. Oh, hvala vam puno.
{48025}{48071}- Hej. Kako si, ËovjeËe?|- Kako ste vi?
{48072}{48096}Dobro vas je vidjeti.
{48097}{48172}Sretan roendan Pete,|kako divno te je vidjeti!
{48173}{48217}- Baka Molly!|- Oh, ti si prekrasna.
{48217}{48283}A pogledajte moju prekrasnu, prekrasnu...
{48285}{48312}Prekrasnu!
{48313}{48360}Ne. Kuûim, samo se pitam|zaöto bi trebao...
{48361}{48414}Hej, Pete! Pete! Jason je ovdje.
{48415}{48445}Peter. Bok.
{48445}{48490}- Hej, kako ide, Jason?|- OdliËno, izgledaö dobro.
{48491}{48521}- Hvala.|- Da.
{48522}{48570}Kako ti se svia ono öto|radim tvoj djevojci?
{48570}{48611}Kako ti se svia Debbieno tijelo nakon mene?
{48612}{48649}- Lijepo je.|- Hajde, pokaûi im.
{48655}{48697}Pogledajte ovo.|To je lijepo.
{48698}{48732}Pogledajte ovo dupe nakon mene.
{48733}{48782}Sada poËinje ovdje...
{48788}{48840}a bilo je poËinjalo ovdje...
{48841}{48888}a ja sam ga doveo gore.
{48913}{48953}Nema na Ëemu.
{48954}{49009}Gospodine, jeste li vi trener?
{49026}{49056}- Da.|- Ha.
{49057}{49121}Pa. No, ne samo fiziËki.|Duhovni.
{49123}{49157}Ja sam svojevrsni vodiË.|- Mm-hmm.
{49158}{49199}Vi bi trebali porazgovarati.|Mislim da Êete...
{49199}{49235}- Du-ah...|- Êete... se slagati.
{49265}{49307}Doi duöo,|moram ti neöto reÊi.
{49308}{49335}Da.
{49549}{49577}Tko je to u bazenu?
{49578}{49607}Moje.
{49679}{49705}Pozdrav.
{49706}{49721}Pozdrav, Debbie.
{49721}{49745}Kako si?
{49745}{49765}Dobro.
{49769}{49812}SjeÊaö se mog muûa, Peta?
{49813}{49892}O da! Ja...nisam|te prepoznao s dugom kosom.
{49894}{49953}Oh da, ne, pustio sam da raste.
{49954}{49974}Sretan roendan.
{49975}{50021}Oh! Hvala ti puno!
{50026}{50051}Vrlo stari ökotski viski.
{50052}{50131}Oh, vau. Znaö...nadam se da|mu nije proöao rok.
{50166}{50204}Ne, ökotski viski nema rok.
{50227}{50260}Poboljöava se s godinama.
{50305}{50378}Da. Ne. Ma znam.|Ah, hvala ti puno.
{50380}{50417}Lijepo.|Hajde!
{50418}{50447}- Naravno.|- éao mi je.
{50533}{50599}Pa, öto radite u Chinu, Oliver?
{50600}{50621}Ja sam kirurg.
{50621}{50668}- Opa. Kakav?|- To je super.
{50684}{50715}Uglavnom za kraljeûnicu.
{50735}{50812}Moja specijalnost je skoliozna kirurgija.
{50815}{50902}Moja mama mi je znala govoriti|kao da sam imam skoliozu
{50902}{50974}jer sam, znate, malo pogrbljen,|ali to je druga stvar.
{50979}{51020}Ne, vi definitivno ne izgledate dobro.
{51021}{51049}- Hej!|- Hej!
{51051}{51099}- Hej!|- Oprosti öto kasnimo!
{51100}{51152}Bio sam u laboratoriju klonirati sebe.
{51154}{51203}Sutra Êemo ih imati joö sedmero.
{51204}{51282}Oöiöali smo ih drugaËije, tako|da ih konaËno moûemo razlikovati!
{51284}{51331}Svia ti se nova frizura, Travis?
{51332}{51364}Ja sam Jack, prokletstvo!
{51365}{51405}Oh, naravno.
{51407}{51450}Larry, ovo je moj otac.
{51458}{51483}Stvarno?
{51500}{51533}Kako ste?
{51534}{51580}- Oliver.|- Oliver? Oh!
{51581}{51623}"Mogu li dobiti joö malo?"
{51629}{51696}"Molim te, Oliver, trebam zalogajËiÊ."
{51697}{51725}Volim taj film.
{51730}{51778}Morate da vam to stalno spominju.
{51779}{51792}Ustvari ne.
{51792}{51835}Nos me svrbi ovdje.
{51836}{51895}Oprostite, ispriËavam se. Ja sam|Claire, Larryeva supruga.
{51896}{51961}Vrlo lijepo vas je vidjeti, ali|idem po djecu.
{51976}{52031}Sada je neÊemo vidjeti cijeli dan.
{52043}{52127}Pomogao bih duöo, ali znaö, imam|visoki tlak, a i baö ne ûelim to.
{52130}{52157}Mogu li ti dati za popit tata?
{52158}{52176}- Da.|- éeliö li neöto?
{52177}{52201}Bijelo vino.
{52202}{52222}- Bijelo vino?|- Da.
{52222}{52259}- Oh, jaka stvar.|- Da.
{52281}{52345}Pa tko je znao da je Debbie imala tatu!
{52356}{52469}Gdje ste bili petnaest godina?|Nikad vas nisam vidio na Hanuku, BoûiÊ, ili
{52471}{52552}Ramazan, niöta. Kako ste izvukli od|svih tih stvari? Imate li ûenu?
{52554}{52590}Da, moja supruga je kod kuÊe.
{52591}{52619}Oh, zaöto...zaöto nije doöla?
{52620}{52679}Radovi.|ämirglaju nam palubu.
{52683}{52722}Pustili ste ûeni da ömirgla palubu?
{52728}{52776}Nadzire to, da.
{52777}{52797}Ok.
{52798}{52826}Hej, deËki.
{52829}{52867}Hej!
{52868}{52973}Pogledajte kako su djeca velika!|Sadie!
{52983}{53011}Bok, Larry.
{53012}{53043}Bok, Sadie.
{53044}{53114}Mama. Tko...tko je Oliver?
{53130}{53152}äto misliö?
{53154}{53178}Je li on tvoj tata?
{53182}{53251}Je li on moj ta...|On je moj bioloöki otac.
{53266}{53298}äto to znaËi?
{53300}{53390}Ahm, to znaËi da je moja mama, baka...
{53395}{53470}on i moja mama su|imali dijete i da sam to ja!
{53474}{53517}O, pa ti si naö djed.
{53531}{53582}Uh, dobro, zaöto ne pitaö svoju majku?
{53586}{53609}Da.
{53612}{53684}Valjda bi onda, bio|vaö djed, onda da.
{53687}{53710}éelite li da bude?
{53711}{53782}Da. Onda smo dobili|joö jednog djeda. Hajde!
{53792}{53819}äto...?
{53826}{53891}- Drugi djed?!|- Vrijeme za trampolin.
{53929}{53987}Da, to je bio izrazito neugodno.
{54016}{54112}Barem je ta lijepa djevojka bila|tu da nam odvrati pozornost.
{54505}{54590}Oh. Moj boûe, bok. Ja i mene,|nisam te vidio.
{54591}{54629}- Bok.|- Ja sam te vidio.
{54631}{54701}Jeste li vi deËki doöli zajedno?|Jeste li... par?
{54751}{54813}- Ne, nismo doöli zajedno.|- Ne, ne apsolutno ne.
{54815}{54860}Samo sam...oprostite, mislila sam da je...
{54863}{54895}brkovi su malo...
{54898}{54932}Hmm. To je poöteno.
{54933}{54954}Samo samo pretpostavila.
{54955}{55001}Ovo su brkovi hetero muökarca.
{55008}{55133}A koja je razlika izmeu muökih|homo brkova i... hetero brkova?
{55142}{55173}Miris.
{55248}{55291}Ah. IspriËavam se.
{55434}{55597}Dakle, Ëini mi se da je kirurgija kraljeûnice|na vrhu kirurgijskog lanca.
{55603}{55663}Pa, nismo kardio, nismo neuro...
{55664}{55749}ali volim misliti da smo|vaûan dio spektra.
{55757}{55785}Operirate li svaki dan?
{55786}{55805}VeÊinu dana.
{55808}{55838}Viöe puta dnevno?
{55840}{55881}Tri, Ëetiri puta.
{55884}{55962}Dakle, koji je raspon cijena?|Npr. kad bi htio...
{55967}{56010}- Ja..radije ne bih o tome govorio.|- Oh, ja sam samo...
{56017}{56079}Toliko je velik da vam je neugodno reÊi.
{56085}{56125}Ne bih rekao neugodno.
{56131}{56168}Postoje li grbavci danas?
{56169}{56206}- Naravno.|- Nikada nisam ni jednog vidio.
{56207}{56259}Pa, to je zato jer|postoje spinalni kirurzi.
{56260}{56288}To je zbog vas.
{56290}{56385}Svaki put kad ne vidim grbavca,|vi ste za toliko bogatiji.
{56412}{56446}Volite Beatlese, zar ne?
{56466}{56495}Tko ne voli Beatlese?
{56496}{56528}- Nitko.|- Ne. Nitko.
{56571}{56618}Dakle smijeöno. On je tako smijeöan.
{56622}{56658}Koje je tvoj astralni znak?
{56664}{56684}Vaga.
{56685}{56718}- Oh, ËovjeËe.|- To nije dobro.
{56719}{56736}Ne, gospodine.
{56736}{56784}To nije dobro.|Ne za mene, to nije dobro.
{56785}{56828}Spolno smo potpuno nekompatibilni.
{56828}{56858}- Apsolutno.|- To nije toËno.
{56858}{56895}- Zar ne?|- To je takva öteta. Da.
{56896}{56935}Ne, to je...mislim, loöe koliko moûe biti.
{56936}{56977}- Ne znaö to.|- Koji je tvoj?
{56993}{57031}Ja sam Rak.
{57051}{57083}- Stvarno?|- Je li to dobro?
{57085}{57104}Opa.
{57104}{57148}- äto to znaËi?|- To je nekako Ëudno. Pa,
{57149}{57228}Bik i Rak su na neki naËin|srodne duöe u Zodijaku.
{57230}{57318}Mi smo neöto kao savröeno kompatibilni,|jer ja nadomjeötam ono öto ti nedostaje,
{57318}{57358}i ti nadoknaujeö ono öto mi nedostaje.
{57359}{57474}I tihi Rak gotovo uvijek|ima veliki penis.
{57507}{57556}Neugodno mi je...
{57559}{57613}Hvala. Hvala ti.
{57649}{57699}Oh! Htjela sam nazdraviti.
{57708}{57781}DeËki, hvala vam puno za dolazak,|hvala vam puno. Hm...
{57788}{57825}Pete puni Ëetrdeset i...
{57828}{57858}- »udno.|- I,
{57859}{57950}spremni smo zapoËeti ovu novu|fazu u naöim ûivotima s otvorenim srcima.
{57951}{58060}Spremni smo odabrati radost i...|i oprostiti svima.
{58061}{58099}Dakle, hvala vam svima öto ste doöli.
{58100}{58144}- éivjeli.|- »ekaj!
{58152}{58185}Oprosti kome?
{58187}{58268}O mislim da je ona to|mislila opÊenito. Znaö, samo...
{58282}{58320}Staviti proölost iza nas, i...
{58321}{58349}ûivjeti bez zamjeranja.
{58350}{58412}Ali konkretno kome opraötaö?
{58414}{58489}Samo sam.... ûelim znati|pojedinosti prije nego öto nazdravim.
{58491}{58604}Dobro. Tebi, i...|i mom tati i drugima.
{58653}{58680}Vidim...
{58707}{58769}Pa znam...znam da|imate neke probleme sa mnom,
{58769}{58818}ali sam znatiûeljan,|zaöto je on unutra?
{58820}{58876}Prije danas, nitko nije ni znao da postoji.
{58877}{58934}Pa, moji roditelji su se razveli|kad sam bila jako mlada i
{58934}{59006}ne provodimo toliko vremena zajedno,|i htjela bih da poradimo na tome.
{59008}{59100}Baö kao öto bi poradili na...
{59119}{59188}tvojim financijskim problemima.
{59193}{59259}Ona govori o svim kreditiranjima.|I posuivanju...
{59260}{59312}Znam...znam öto je htjela reÊi.
{59340}{59439}Ti si lijepa ûena,|ali nisi posve savröena.
{59442}{59488}Rekao bih iskreno, ti si öestica.
{59488}{59502}- Oh.|- Ooh.
{59503}{59583}äest - öest i pol.|Ja bi te mogao napraviti jedanaest.
{59584}{59602}Stvarno?
{59602}{59644}Kad sam pronaöao Deb, bila je sedam.
{59656}{59689}A sad je dvanaest.
{59690}{59733}éelim bit...ûelim biti dvanaest.
{59734}{59755}Ne moûeö biti lijena.
{59757}{59780}Ne ûelim biti lijena.
{59781}{59836}Gledaj u mene. Ti ne moûeö biti lijena.
{59838}{59871}NeÊu biti lijena.
{59873}{59942}Znaö li kako je ona dobila svoje tijelo?|Tijela od Jasona.
{59945}{59972}- Opa.|- Reci to.
{59973}{60000}Tijela od Jasona.
{60001}{60022}Reci to ponovno.
{60023}{60054}Tijela od Jasona.
{60055}{60077}A sad samo reci Jason.
{60078}{60098}Jason.
{60099}{60128}- Opet?|- Jason.
{60128}{60172}To zvuËi dobro, zar ne?
{60174}{60203}Da.
{60249}{60302}Koji kurac se sad dogaa?
{60330}{60386}Kada ste zadnji put vas dvoje|vidjeli, ja sam znatiûeljan?
{60386}{60427}Zapravo, ruËali smo|zajedno proöli tjedan.
{60427}{60470}A-ha. A prije toga?
{60476}{60513}Proölo je oko sedam godina.
{60517}{60606}Sedam godina? To je öala, zar ne?|To je kao dvije Olimpijade.
{60608}{60642}Ali ja sam loö Ëovjek.
{60644}{60664}Pusti, tata.
{60665}{60771}äto Debbie ne razumije|je da nije loöe pomoÊi roditelja.
{60775}{60854}I da sigurno nije loöe|da roditelj pomogne djetetu.
{60859}{60889}Siguran sam da se Oliver slaûe.
{60890}{60932}- Pa, ah...|- Zar to stvarno radiö baö sada?
{60933}{60982}»inim öto?|Nisam ja zapoËeo zdravicu.
{60983}{61037}Stvarno Êeö se nabacivati|mom tati zbog novca?
{61038}{61090}äto? On operira Ëetiri puta dnevno.
{61091}{61157}On je savröen. Pomaûe svima,|i to ublaûava njegovu krivnju
{61157}{61202}od svih pitanja u svezi ostavljanja.
{61203}{61263}Ne moûeö kupiti oprost, zar ne Pete?
{61277}{61376}Mislim da nitko ne traûi poklon,|mislim mi bismo... mu vratili.
{61386}{61462}Ako ste vas dvoje u velikoj stisci,|ja.. bih bio viöe nego sretan pomoÊi.
{61466}{61493}Ne.
{61496}{61627}Nije dobro posuivati novac|od obitelji jer to uzrokuje zamjerke.
{61632}{61655}SjeÊaö se?
{61658}{61696}Da, je, je,|je, je.
{61699}{61735}äto..öto ûeliö da uËinim?
{61737}{61782}Ok, priznajem da je moj ûivot sranje?
{61782}{61824}Je li to ono öto ûeliö|da kaûem? Sretna?
{61825}{61912}Zar mi nije dopuöteno imati malo|radosti s ovom djecom koju nikad nisam htio?
{61924}{62003}Nikad nas ne prestajeö pitati novac.
{62006}{62057}Obitelj pomaûe obitelj.
{62059}{62118}Ali to je istina. Obitelj pomaûe obitelj.
{62123}{62191}Gledaj, ja ne oËekujem da|u potpunosti razumijeö.
{62193}{62250}Ti..tvoj tata te napustio.|Ti si slomljena iznutra.
{62250}{62306}Nije tvoja krivnja jer ne moûeö osjetiti ljubav.
{62309}{62349}Postoji neöto öto ne moûeö...
{62380}{62423}Ovo ide u krivom smjeru.
{62440}{62491}Znate öto? Radije bih imala svog tatu
{62491}{62530}- Mm-hmm.|- nego tvog oca,
{62534}{62579}jer me ne izluuje.
{62582}{62631}Znaö koja je najbolja kvaliteta mog oca?
{62635}{62677}Je li on niöta ne pita.
{62707}{62771}Ne znam koji kurac|on upravo sada misli.
{62775}{62850}Pogledajte to.|Niöta. Niöta.
{62853}{62974}»ak ga ni ne znam ga. I ispala sam|savröeno dobra bez njegova doprinosa. Ok?
{62976}{63076}Shvatio sam öto je tvoj problem.
{63088}{63126}Mrziö éidove!
{63151}{63208}äto je Ëudno jer su|vaöa djeca éidovi.
{63208}{63243}Nemoj igrati na ûidovsku kartu, Larry.
{63244}{63270}Ne igram na ûidovsku kartu.
{63271}{63303}Ozbiljno, pohabana je.
{63304}{63373}Ne moûeö koristiti ûidovsku kartu.|To je cijeli smisao ûidovske karte.
{63373}{63442}To je toËno. Ne moûete|to koristiti, to traje zauvijek.
{63443}{63502}Ah,...znate öto? Ja...ja moram iÊi.
{63503}{63546}Da. Izvrsno. Stvarno veliko iznenaenje.
{63547}{63627}Bok Oliver! Vidimo se kasnije!|Vidimo se za sedam godina.
{63628}{63688}Pobrini se reÊi zbogom|unucima koje si danas upoznao.
{63689}{63761}Znaö, öto god da uËinim|nije dobro zbog tebe? Niöta.
{63763}{63845}Bez obzira koliko jako se trudim,|ja sam samo kreten, ali znaö öto?
{63848}{63905}Znaö öto sam shvatio?|To si ti. Ti si kreten.
{63939}{63975}Sretno s izglaivanjem ovoga.
{63980}{64044}Sretan ti roendan i jebi se.
{64058}{64116}Hej! Vidimo se kad Cubsi postanu öampioni.
{64136}{64193}Ja Êu zapaliti svijeÊe.|Samo vi nastavite, ok?
{64233}{64298}- Moûda bismo trebali pokuöati nazdraviti ponovno.|- Znaö, moûeö li biti tiho?
{64309}{64344}Bacio si me pod autobus.
{64344}{64364}Upravo si me bacio pod autobus.|- Ne, ja ne razumij...
{64364}{64436}Bacio si me pod...|bacio si me pod autobus!
{64437}{64488}Znaö dogovorili smo se|da proe i zaboravimo
{64488}{64558}ali onda si poËela kidati|moga tatu kao luakinja.
{64560}{64595}Nisam kidam tvog tatu!
{64596}{64684}Samo mu kaûem|öto ti kaûeö meni.
{64684}{64720}Ne budi tako naporna.
{64721}{64762}Nisam naporna.
{64765}{64831}Ti si me napravio takvom!|Ja sam zabavna djevojka!
{64832}{64915}Ja volim zabave! Ja sam Sally partijaöica!
{64918}{65035}Pleöem hip-hop! Ne mogu vjerovati|da sam protraÊila cijeli ûivot
{65037}{65114}nateûuÊi jaja|ljudi koji ih nemaju.
{65121}{65190}Ja sam jedina ovdje|koja ima bilo kakva jaja!
{65206}{65284}d Sretan roendan ti
{65304}{65384}d Sretan roendan ti
{65402}{65514}d Sretan roendan dragi Pete
{65524}{65631}d Sretan roendan ti
{66324}{66357}Mama?
{66420}{66468}Mama! äto radiö?
{66470}{66492}äto?
{66493}{66549}Ti puöiö?|U..u dvoriötu?
{66551}{66617}Ne! Ne. To su od Barb.
{66677}{66704}Mama!
{66706}{66757}Od kada si puöaË?
{66759}{66782}Nisam puöaË.
{66783}{66818}Mislim da si rekla da puöaËi umiru.
{66818}{66877}Ne puöim.|Nisam puöila.
{66878}{66902}Vidjela sam te!
{66902}{66920}Ne, nisam.
{66920}{66959}Mama, ti puöiö?
{66960}{67037}Deb, ne smijeö puöiti, ti si trudna.|Dobro ti je iölo.
{67038}{67071}Ti si trudna?
{67072}{67124}Nema J-ene öanse.|Ne ûelim joö jednu sestru!
{67125}{67169}Ja ne ûelim nju kao sestru.
{67170}{67225}éao mi je. Tako mi je ûao.|Samo mi je izletjelo.
{67225}{67272}Jesu li stvarno trud...|Od kad si trudna?
{67272}{67348}Od kada te to briga?|Ti ne ûeliö joö jedno dijete!
{67348}{67383}Nemaö pojma öto ja ûelim.
{67383}{67417}éelim azijsku bebu.
{67418}{67454}Mi neÊemo imati azijsku bebu!
{67454}{67481}Da, hoÊemo!
{67482}{67507}Oni nisu Azijati.
{67507}{67540}- Sadie!|- Kupit Êemo je.
{67540}{67561}äuti, Charlotte.
{67561}{67576}Ti öuti!
{67576}{67600}äuti, Sadie!
{67601}{67624}äuti, Charlotte!
{67625}{67660}- äuti!|- Ok, Sadie. äuti!
{67660}{67692}äuti, Charlotte!
{67693}{67735}- äuti!|- Ok, prestati govoriti öuti!
{67735}{67783}Ti si trudna?|Od kada si trudna?
{67784}{67816}Kada si saznala?
{67866}{67950}HoÊeö li prestati jesti kolaËiÊe, molim te?!
{67955}{67997}Prestani jesti kolaËiÊe!
{68009}{68060}Prestani jesti kolaËiÊe!
{68146}{68233}Hej! Upravo smo Ëuli!|Dobit Êete bebu!
{68248}{68287}Vidiö, moûe se dogoditi svakome.
{68288}{68332}To je tako divno.
{68332}{68372}Daj mi da...|oh, to je fantastiËno.
{68373}{68415}»estitamo.|- Oh, to je divno.
{68415}{68451}Tako sam sretna zbog tebe.
{68472}{68505}Zgrabi drugog klinca.
{68511}{68540}- Mislio sam da si imala?|- Nisam nikada.
{68542}{68595}Ovo je previöe odraslo za tebe.|Idemo van.
{68596}{68639}»estitamo.
{68679}{68742}Pa, mislim da smo onda|zaglavili zajedno zauvijek, zar ne?
{68743}{68774}Zar nismo oduvijek?
{68775}{68805}Ti uopÊe ne ûeliö dijete!
{68806}{68851}Naravno da hoÊu. Nikada nisam to rekao.
{68851}{68912}Gle, ja stvarno ..nisam htio|da sam mogao birati.
{68913}{68974}Trebao bi to tiskati na Ëestitke.|To je lijepo.
{68975}{69004}Debbie...
{69008}{69079}Uh, sretno s trudnoÊom,|Debbie. Ali, molim te...
{69089}{69164}brini se o sebi. To je|puno riziËnije nakon Ëetrdesete.
{69169}{69192}Nisam Ëetrdeset.
{69194}{69277}Naravno da jesi.|Roena si 5. prosinca 1972.
{69278}{69335}Nisam Ëetrdeset! Ka..kako znaö?
{69336}{69412}Bio sam tamo!|Ja sam odveo tvoju majku u bolnicu.
{69413}{69446}Pa to nije ono öto je rekla.
{69446}{69506}Da, tvoja mama je imala|trudove samo dvadeset minuta.
{69506}{69578}Nisi mog...nisi mogla doËekati da me|upoznaö, moûeö li to zamisliti?
{69579}{69616}»ak te niti ne poznam.
{69619}{69717}Ne moûeö samo tako doÊi u|moju kuÊi i priËati o uspomenama.
{69718}{69799}Gledaj, moûda nam nije bilo|sueno da budemo jedno drugom u ûivotu.
{69802}{69862}Mislim da ovo nije bila dobra ideja.
{69947}{69995}»ekaj malo.|Hej, Ëekaj malo.
{70007}{70080}Otiöao si. I nisi se vratio.
{70081}{70167}Moj prvi ûivot bio je uniöten.|Dao sam sve od sebe u drugom ûivotu.
{70168}{70228}Dakle ja sam uniötila tvoj ûivot?|Bila sam osam godina.
{70231}{70315}Ljudima je bolje kad sam|izvan njihovih ûivota! To mi sin govori.
{70318}{70353}Misliö da je moj ûivot tako savröen?
{70354}{70458}Imam trinaestogodiönjaka koji je dupeglavac,|imam ûenu koja, koja...
{70473}{70520}koju Apaurin odrûava na ûivotu!
{70524}{70559}Nikad prije to nisi rekao.
{70560}{70633}Ne misliö valjda da ûelim od tome razgovarati?|Podijeliti s tobom?
{70634}{70722}To nije naö naËin!|Mi se ne povjeravamo jedno drugome, ne poznajemo se.
{70724}{70773}A ja sam mislio da ti tako ûeliö.
{70774}{70812}Kako...kako...kako Êu izaÊi iz ovoga?
{70813}{70910}Kako da vas pridobijem|da me skinete s kriûa?
{70957}{70994}ZvuËiö kao Sadie.
{70995}{71022}Tko je Sadie?
{71025}{71089}Ne. Tvoja kÊer. Mlaa?
{71091}{71110}Velika.
{71112}{71202}Tvoja starija. Znam...znam to!|Divna djevojka.
{71210}{71282}Hej, deËki. Neki od nas moraju otiÊi.
{71283}{71342}Bi li ovo bio dobar trenutak da iöuljamo?
{71434}{71477}Kamo tata ide?
{71715}{71771}Najbolji roendan ikad!
{71930}{71946}O sranje!
{71947}{71976}Bici staza, öupËino!
{71977}{72066}Jebi se, ti mraËna priötava guzico,|pizda ti materina!
{72076}{72117}Tvoj tata je joö uvijek ovdje.
{72139}{72195}Znam. To je nekako Ëudno.
{72196}{72239}Gdje je dovraga Pete?
{72272}{72299}Uhm...
{72309}{72381}Je li to u redu ako Joseph|bude s nama neko vrijeme?
{72389}{72416}Mm-hmm.
{72459}{72490}Bok, Joseph.
{72501}{72529}Bok.
{72545}{72574}HoÊeö li komad torte?
{72577}{72600}Oh! Da naravno.
{72630}{72666}Hvala. Hvala.
{72719}{72754}U redu, onda.
{72764}{72795}Oni su tako slatki.
{72795}{72821}Tako slatki...
{72822}{72858}On izgleda baö kao Tom Petty.
{73016}{73053}Idi okolo!
{73122}{73163}Pazi! Pazi!
{73267}{73319}Hej, Pete. Super zabava!
{73381}{73410}Da.
{73433}{73465}Najbolja!
{73483}{73518}A onda ga treseö.
{73537}{73579}A onda se pojavi restoran.
{73586}{73668}Ta...tata? IspriËavam se.|Idem potraûiti Peta.
{73670}{73746}Da li bi ti smetalo da|ostaneö s curama joö malo?
{73749}{73779}Pa, ako me hoÊeö.
{73781}{73821}Jedino ako ti nije problem.|Ne moraö.
{73823}{73850}Naravno.
{73884}{73945}Mogu li dati Sadie da mi pokaûe|posljednju epizodu "Lost"?
{73945}{73984}Pitala me da li sam gledao, a nisam.
{73984}{74023}Da, to bi bilo lijepo.
{74050}{74082}Hvala.|- Hvala.
{74107}{74152}Rekla je da moûemo gledati.|Hajde!
{74208}{74253}Dopustit Êu ti da gledaö "Lost".
{74257}{74276}Hajde.
{74317}{74350}Je li to straöno?
{74351}{74407}Pokrit Êu ti oËi ako postane previöe straöno.
{75171}{75224}Jeste li ljuta na mene?|Jesam li neöto rekao
{75224}{75263}Pst. Larry, molim te.
{75605}{75650}Je li me zajebavaö?
{75666}{75728}Je li me zajebavaö?
{75753}{75796}Otvorio si vrata baö pred mene.
{75798}{75868}Nisam otvorio jebena|vrata pred tebe. Otvorio sam vrata!
{75870}{75927}Ah! Jebiga, bio sam baö tu!
{75933}{75981}Trebao bi gledati|prije nego öto otvoriö vrata,
{75981}{76015}Bio sam na jebenoj bici stazi.
{76016}{76093}To je mrtvi kut. Nema jebene|bici staze. Ovo je stambena Ëetvrt.
{76094}{76128}Izvadi glavu iz guzice.
{76128}{76147}Obratite pozornost!
{76148}{76193}Otvorite te proklete oËi.|äto radiö, mjeseËariö?
{76194}{76274}Trebao bi gledati|da li biciklist prolazi.
{76276}{76299}Ti bi trebao gledati!
{76299}{76359}To nije moj posao da pazim na tebe.|Pazi se sam!
{76359}{76406}Ja ne pazim na tebe. Ja te ne vidim.
{76407}{76458}Jebe mi se gdje si i öto radiö!
{76458}{76516}Nitko nikada ne pazi na mene!
{76519}{76572}Trebam tvoje ime i broj.
{76576}{76598}Zaöto?
{76598}{76633}Jer Êeö platiti za moja vrata.
{76634}{76653}Jebi se!
{76654}{76743}Zaöto ne platiö za moj bicikl,|i moje lice, jebeni pizdek!
{76911}{76945}Nemoj me nepoötivati.
{77012}{77051}Jeste li sigurna da je to on?
{77062}{77100}Ja ne mislim da je on!
{77165}{77217}Zapisati Êu ti registarsku tablicu.
{77330}{77398}"Range Rover iz Sunlanda."
{77477}{77492}äto radiö?
{77492}{77528}äto radiö?|- Ou.
{77689}{77766}Pretpostavljam da zabava|nije ispala kao öto je planirano.
{77800}{77846}Nije bila dobra zabava.
{77875}{77899}- Bok.|- Bok.
{77899}{77942}Uvest Êu vas unutra Ëim|zavröi snimanje na rendgenu.
{77943}{77966}- Ok.|- Ok.
{77967}{77985}Je li on dobro?
{77986}{78084}Da, ima slomljeno rebro i malo|cendra, ali Êe biti u redu.
{78143}{78243}Znaö Pete nikad nije bio pravi borac.
{78270}{78370}Ali to je razlog zaöto te oûenio. To je|razlog zaöto te voli. Jer ti si borac.
{78391}{78489}A tebi to treba. Jedna osoba|u vezi mora primiti udarac.
{78507}{78545}Misliö to u dobrom smislu?
{78546}{78619}Oh, to je... to je velika pohvala.
{78673}{78703}Hvala.
{78738}{78786}Sluöaj, znam zaöto si zabrinuta.
{78787}{78841}Misliö da Êe se pretvoriti u mene, ali...
{78862}{78905}Ja ne mislim da Êe se to dogoditi.
{78906}{78974}On je pametniji i|vjerojatno malo slai.
{79008}{79041}Malo manje éidi.
{79057}{79136}Iako nakon pedesete, to|Êe se sve promijeniti.
{79137}{79205}Spremi se da se jedan dan|probudiö s rabinom.
{79232}{79283}Ali dobra vijest je, znaö...
{79317}{79390}on Êe te voljeti zauvijek.|To je u naöem DNK.
{79401}{79444}Drûimo se u blizini.
{79478}{79567}On se brine za tebe, znaö.|To je veliki pritisak na njega.
{79569}{79636}Znam. Ja sam..nemam|s kim razgovarati o tome.
{79637}{79671}Zaöto ne razgovaraö s Claire?
{79672}{79720}Oh, ako joj se otvorim,|ona Êe me ostaviti.
{79721}{79768}- Ne, neÊe.|- Hmm.
{79769}{79792}Larry, ona te voli.
{79793}{79879}Znam, ali ima jedna toËka|nakon koje ne moûeö ostati.
{79989}{80098}Pretpostavljam da je teöko oprostiti nekome|ako se on formalno ne ispriËa.
{80190}{80234}Je li se ti to ispriËavaö?
{80242}{80290}Vrlo sam blizu.
{80346}{80391}Da, Ja..ja...ûao mi je.
{80525}{80576}Drago mi je da su svi u redu.
{80625}{80676}Oh. Hvala ti.
{80835}{80873}Dobro. OtkaËio sam se.
{80873}{80902}Ok.
{80944}{80981}Ovo je neugodno.
{80996}{81018}äto?
{81023}{81080}Trebam Ëetrdeset dolara za taksi.
{81110}{81143}To je smijeöno.
{81159}{81188}Ne, ne öalim se.
{81226}{81280}Ti si me vozila. Ja...nisam se pripremio.
{81294}{81330}Imam samo sto.
{81331}{81362}To je u redu.
{81374}{81412}Vratit Êu ti kusur.
{81441}{81498}Dobro, daj mu pusu za mene.
{81934}{81993}Ne..ne kuûim.
{82021}{82136}Vidi, to nije tuûno, sretno je, jer su|pomogli jedni drugima ostvariti svoju sudbinu.
{82137}{82165}Oh.
{82171}{82274}Super. Imat Êu neke lude noÊne more.
{82561}{82585}Bok.
{82590}{82616}Bok.
{82844}{82956}Stvarno sam puno viöe voljela naöe ûivote prije|nego smo probali sve promijeniti.
{82963}{82998}éao mi je.
{83005}{83044}Ne. Meni je ûao.
{83052}{83111}Ne ûelim skrivati niöta od tebe.
{83132}{83172}Volim te. Ti si moja ûena.
{83183}{83224}Jednostavno nisam vas htio iznevjeriti.
{83274}{83313}Jesi li bijesan öto sam trudna?
{83317}{83385}Ne nisam bijesan. Oduöevljen sam.
{83392}{83425}Ne osjeÊaö se uhvaÊenim u zamku?
{83440}{83489}Ponekad osjeÊam kao da sam ja tebe uhvatio u zamku.
{83490}{83522}Ne osjeÊam se uhvaÊenom u zamku.
{83531}{83559}- Stvarno?|- Ne.
{83571}{83615}Trebala bi, jer sam te uhvatio.
{83618}{83652}Ne moûeö nigdje.
{83669}{83736}Napumpat Êu te svakih deset godina|ostatak tvog ûivota.
{83736}{83789}Nikad neÊeö moÊi otiÊi. Nikada
{83790}{83857}Nikad se ne osjeÊam zarobljenom.|Sretna sam s tobom.
{83857}{83985}A ja te volim toliko puno.|Ti si mi najomiljenija osoba na cijelom svijetu.
{83998}{84119}Doavola, zaöto plaËem?|Neöto nije u redu sa mnom.
{84121}{84153}Ti si trudna.
{84156}{84183}O, da.
{84194}{84221}Sranje.
{84232}{84311}Upravo sam vani rekla|tvom tati da ga volim.
{84312}{84349}äto ako on misli da sam sada kao on?
{84350}{84380}Ne, neÊe on to misliti.
{84382}{84431}Ne ûelim da misli|da ga volim baö toliko.
{84432}{84475}Ne, to se nikada neÊe dogoditi.
{84493}{84582}Moûeö li to vjerovati?|Ovo je najlua stvar ikad.
{84583}{84645}äto Êemo uËiniti s treÊim djetetom?
{84646}{84715}Nemam pojma.|Kako Êemo si to priuötiti?
{84723}{84758}Prodat Êemo kuÊu.
{84763}{84793}Ne moramo.
{84794}{84835}- Ma ipak moramo.|- Ma ipak moramo.
{84841}{84899}Napravit Êemo nove uspomene u novoj kuÊi.
{84913}{84950}Volim te.
{84993}{85050}Ima li neöto öto|ûeliö za roendan?
{85062}{85112}To je bio najgori roendan ikad.
{85137}{85188}Ima jedna stvar,|ali ne mislim da ti se neÊe svidjeti.
{85191}{85214}äto?
{85227}{85276}Ne bih imao niöta protiv otiÊi vidjeti neku glazbu.
{85284}{85311}Bi li htjela to uËiniti?
{85311}{85331}Da.
{85333}{85359}- Stvarno?|- Da.
{85362}{85429}Ne vjerujem ti,|ali srce si zbog toga.
{85430}{85468}Kako Êemo te iöËupati odavde?
{85473}{85542}Mogu otiÊi vlastitom voljom.|To nije mentalna ustanova.
{85543}{85578}- Moûe li?|- Da.
{85590}{85638}To nije poput "Leta|iznad kukaviËjeg gnijezda."
{85650}{85692}"Molim vas, nemojte staviti|jastuk preko mojeg lica."
{85746}{85781}Hajdemo odavde, McMurphy.
{85783}{85843}Moûe, öefe.|HoÊeö li me nositi?
{85874}{85930}Nosiö me sve ovo vrijeme.
{86877}{86916}Volim ovu pjesmu.
{86929}{86958}Stvarno?
{86976}{87010}Zaöto?
{87124}{87161}Zaöto ne potpiöeö ugovor s njim?
{87164}{87213}Ryan Adams? Ne, on je...
{87233}{87265}NeÊe on potpisati sa mnom.
{87265}{87309}Zaöto ne? Ti si najbolji.
{87317}{87357}On je izmeu dva izdavaËa.
{87404}{87456}Idemo probati razgovarati|s njim nakon koncerta.
{88694}{88723}Hvala.
{88757}{88889}»EKAJTE, IMA JOä! :)
{89557}{89629}éao mi je ako nisam|fensi i bogata
{89632}{89715}i ako to ne pokazujem svojom|Vidal Sassoon frizurom.
{89729}{89753}Oprostite.
{89760}{89797}Prekini da mi trepkaö.
{89809}{89841}- Oprosti.|- Ok.
{89856}{89928}Voljela bih da ustanem,|raöirim noge
{89930}{90001}i öutnem oboje po zubima.
{90056}{90106}To je ono öta bih|voljela.
{90108}{90193}Voljela bih da moje jebeno stopalo|nabijem u tvoju lubanju.
{90219}{90275}To se deöava kada|ötakora stjerate u kut.
{90277}{90305}Jebeno Êu vas pobiti.
{90313}{90377}Stjerajte me u kut,|i ja Êu vas jebeno saûvakati.
{90381}{90410}Progrist Êu put kroz vas.
{90415}{90501}Treptava. Odgrist Êu ti|jebene kapke.
{90511}{90549}NeÊeö mi treptati,|zar ne?
{90552}{90593}Da li ste pili prije|nego öto ste doöli?
{90595}{90645}Ne, ali Êu poËeti|da pijem.
{90650}{90731}RasjeÊi Êu nekoga kao ribu|i popit Êu mu krv.
{90733}{90765}To Êu da popijem
{90770}{90842}ako ne poËnemo da dolazimo|do jebene poante.
{90853}{90906}Vjerojatno Êu poËeti sa|glavom Karen Carpenter.
{90921}{91007}Otkinut Êu joj glavu|i popit Êu joj krv.
{91014}{91060}A onda Êu da se vratim i|da vas zapalim.
{91094}{91127}Sve Êu da vas zapalim.
{91129}{91173}Ali poËet Êu sa tobom, Jill.
{91180}{91209}Jebeno Êu da te muËim.
{91220}{91298}Znate öta Êu da napravim?|Kupit Êu jebeni kamion.
{91300}{91328}I konopac.
{91330}{91382}Omotat Êu ga oko ta vaöa|tri jebena vrata
{91384}{91428}i vuÊi Êu vas po gradu.
{91431}{91460}Jebem mu mater,|to Êu da napravim.
{91462}{91515}To je potpuno nepotrebno.
{91521}{91583}Stvarno, Jill?|Tako misliö?
{91590}{91666}Odjebi, Jill. Boûe,|svi te jebeno mrze.
{91682}{91706}Boûe!
{91708}{91733}To nije ljepo.
{91737}{91810}Popuöi jebeni kurac, Jill.
{91830}{91863}To je potpuno nepotrebno, Catherine.
{91865}{91920}Ti si jebeni öupak.|Svi te mrze.
{91923}{91951}Mrze tvoju jebenu|kratku frizuru.
{91979}{92030}Drago mi je öto ti je|umro muû.
{92035}{92112}Jer si jebeni öupak.|Vjerojatno se ubio.
{92134}{92182}Ja bih se ubila.
{92201}{92254}Boûe, ubila bih se, Jill.
{92304}{92351}Rez!
{92376}{93876}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
