{0001}{0001}RIO LOBO
{26}{176}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{4597}{4649}Hajde,|uozbiljite se.
{4652}{4743}- Kutija je priliËno teöka, poruËniËe.|- Zlato je obiËno takvo.
{4746}{4797}Hajde, ulazite.
{4852}{4932}- Ulazite s tim, i ostanite tamo.|- Da, ser.
{5016}{5066}Recite kapetanu Meknaliju da voz Ëeka.
{5069}{5134}- »ekamo instrukcije.|- Da, ser.
{5234}{5309}ReÊi kapetanu Meknaliju|da voz Ëeka.
{5370}{5434}- »ekaju se instrukcije.|- Hvala.
{5507}{5576}Izvinite öto vas uznemiravam, kapetane.
{5607}{5706}ReËeno vam je, poruËniËe.|Zaûalio bi da nisi.
{5709}{5744}Da, ser.
{5747}{5800}- äta hoÊeö?|- Poruka iz Pleinsburga.
{5803}{5901}- äta hoÊe poruËnik Forsajt?|- Dalje instrukcije, ser.
{5904}{5988}Reci poruËniku da ue u vagon,
{5991}{6064}i ostane tu dok ja ne pokucam na vrata.
{6067}{6102}Da, ser.
{6326}{6438}- VodniËe, zlato je na vozu.|- Jeste li Ëuli?
{6513}{6565}Kapetan kaûe da ueö u vagon
{6568}{6630}i ostaneö unutra|dok on ne pokuca na vrata.
{6646}{6696}Sretno, poruËniËe.
{6745}{6790}Idemo.
{7242}{7318}Hej, vodniËe.|Voz je napustio Pleinsburg.
{7321}{7401}Jeste li Ëuli?|Samo sluöajte.
{7524}{7593}Kapetane!|Stiûe poruka.
{7694}{7767}- Voz je na putu.|- Bolje se spremite.
{7770}{7837}- Ne brinite, kapetane.|- »ekamo.
{7944}{8001}Kada voz treba da bude|kod ReËne raskrsnice?
{8004}{8082}Za 15 minuta, ser.|NatovariÊe drva i vodu.
{8085}{8142}- Ko komanduje?|- Kapetan Baret, ser.
{8168}{8229}Pa, prenesi kapetanu Baretu|moje pozdrave.
{8232}{8295}I reci mu ako neöto poe naopako|kod ReËne raskrsnice,
{8298}{8365}LiËno Êu se postarati|da zaûali zbog toga.
{8368}{8403}Da, ser.
{8432}{8517}Ne razumem kako moûeö|da Ëujeö voz osluökujuÊi öine.
{8520}{8592}- Sve öine su spojene...|- Zaveûi!
{8595}{8629}Tiöina.
{8632}{8746}- Evo stiûe, voo.|- U redu. Povucite se.
{8773}{8886}Nemoj da vas neko primeti.|I ne izlazite dok ja ne kaûem.
{9463}{9531}Teöko je propustiti toliko zlata.
{9534}{9603}Kada stigne do kapetana,|vratiÊemo ga.
{9643}{9722}U redu, momci. Idemo.|MiËite se. Hajde.
{9743}{9808}Stavite konopce na prugu.
{10180}{10268}Bigfut, reci kapetanu|da je voz ovuda proöao.
{10271}{10306}Svakako, vodniËe.
{10309}{10418}- Postaraj se da su konopci zategnuti.|- Veûite ih Ëvrsto i brzo.
{10503}{10565}Henk, brûe,|ili Êe voz proÊi!
{10594}{10667}Kapetane! Proöli su ReËnu raskrsnicu.
{10686}{10750}Dûejms... imaö li dovoljno masnoÊe?
{10753}{10840}Imamo dovoljno da kad voz naleti|neÊe moÊi da ide nikuda.
{10843}{10918}- Bolje stavite malo viöe.|- Da, ser.
{10921}{10970}- Da, ser.|- Spremni?
{11000}{11083}Ove ose su poludele.|Samo ih sluöaj.
{11086}{11133}Baö su poludele.
{11426}{11580}- Kako izgleda, poruËniËe?|- Pa, izgleda dobro.
{11701}{11794}- Stiûe, kapetane.|- Svi u zaklon.
{11797}{11855}I ne izlazite dok mene ne vidite.
{11858}{11920}Buford, silazi s tog drveta.
{11983}{12060}- Voz je napustio ReËnu raskrsnicu, ser.|- Dobro.
{12063}{12120}Kad stigne ovde,|nema razloga za brigu.
{12123}{12180}- Joö nije ovde, poruËniËe.|- Ne, ser, ali...
{12183}{12278}- Smeta li ti ako ja brinem?|- Ne, ser.
{12281}{12356}- Mogu li da kaûem neöto, poruËniËe?|- Reci.
{12373}{12471}Da li ste zato öto je put od ReËne|raskrsnice do ovde najgori
{12474}{12539}dali detalje o zlatu poruËniku Forsajtu?
{12542}{12596}To je jedan od razloga.
{12599}{12668}Zajedno ste veÊ dugo, zar ne, ser?
{12691}{12778}- Od poËetka rata.|- Da, ser.
{12957}{13037}Maöina se baö zahuktala uz brdo.
{13157}{13210}Usporavamo, poruËniËe.
{13460}{13529}Gledaj kako naleÊe na masnoÊu.
{13631}{13698}ToËkovi proklizavaju|i nemamo vuËnu snagu.
{14325}{14381}Ose!
{14438}{14486}Moramo da izaemo odavde.
{14580}{14698}- Sve je spremno, kapetane.|- OdliËno. Bili Dûo, spusti taj konopac.
{14772}{14830}Ne dozvoli da se para nakupi.
{14939}{15003}U redu, svi se penjite.|Otpusti.
{15064}{15114}Hajde, penjite se.
{15215}{15265}Poûurite! Poûurite!
{15361}{15409}Dûek, hajde!|Penji se, Dûek!
{15478}{15531}Vili, skoro da nisi uspeo.
{15593}{15660}Linija je mrtva.|Moûda su veze prekinute.
{15663}{15742}Veza je prekinuta|izmeu nas i ReËne raskrsnice!
{15745}{15830}- Prokletstvo! Javi predstraûi.|- Da, ser.
{16196}{16249}Otvori vrata.
{16510}{16608}- Kapetane, ose su baö zauzete.|- Da. Vidim ih.
{16647}{16697}Za ime Boga, Hari, skaËi!
{16928}{17022}Hajde! SkaËi!|SkaËi s voza.
{17107}{17159}- Ne mogu da vidim.|- SkaËi.
{17249}{17331}- Dûonsone, da li su svi napolju?|- ProveriÊu, kapetane.
{17430}{17475}Ne vidim nikoga.
{17478}{17573}Daj osama malo dima|i vadi ih odatle.
{17576}{17651}Ne ûelim ih unutra kad ja ulazim.
{17860}{17913}Vaö je, kapetane.
{18388}{18449}Da, ser.
{18452}{18566}Idemo brûe nego öto smo planirali.|Moûeö li da ga usporiö?
{18706}{18806}- KoËnice ne pomaûu, kapetane.|- UdariÊemo negde.
{18809}{18876}Bolje pronaite dobar oslonac.
{20328}{20390}- Dobar posao, vodniËe.|- Je li bilo problema?
{20393}{20446}- Ne puno.|- Bajd je sa zlatom.
{20449}{20499}Konji su ovde.
{20651}{20696}BiÊeö u redu, Dûim.
{20785}{20850}- äta se desilo?|- Zamastili su öine.
{20853}{20943}ZaskoËili su nas i izbacili nas napolje.|Kad sam ja stigao, voz nije bio tu.
{20946}{21024}- Moûeö li da pokreneö maöinu?|- Ne, ser. Sva para je otiöla.
{21313}{21398}- Toliko plena!|- Daj meni malo.
{21439}{21500}Ima dovoljno za svakoga.
{21591}{21679}- Svo zlato je tu, ser.|- Brzo ga utovarite.
{21682}{21739}Teöko je, voo.
{21742}{21813}Hajde. Pomerajte se.
{21816}{21884}Desetaru, pokreni ta kola.
{21887}{21947}Nemoj da potroöimo Ëitav dan, ljudi.
{22013}{22063}U redu, kreÊi.
{22455}{22546}- Kako mu je, desetare?|- Ima veliku posekotinu na ramenu.
{22549}{22617}- BiÊu u redu.|- äta ti je sa licem?
{22620}{22725}- Ubacili su osinjak u vagon.|- Zato smo morali da skaËemo, ser.
{22761}{22864}- Gde je poruËnik Forsajt?|- Dole niz prugu. Teöko je povreen.
{22867}{22918}- PoruËniËe.|- Da, ser.
{22921}{23022}Voljno. Razdvojte se i|pomozite im ovde. MiËite se napred!
{23349}{23419}Kapetane Meknali, ovde.
{23828}{23929}Izvinite, ser. Nismo mogli|da ostanemo u vagonu sa osama.
{23965}{24028}Znam. OseÊaö li ovo?
{24031}{24137}Kapetane, pobunjenici mora da su znali|za to zlato odnekud.
{24140}{24222}- Nema sumnje da jesu.|- Nema sumnje da su nas zaskoËili.
{24225}{24353}- OseÊaö li ovo, Ned?|- Ne. Samo sam ukoËen, ser.
{24378}{24442}Moûeö li da pomeraö glavu?
{24445}{24504}Ne. Ali ne boli, ser.
{24507}{24573}- BiÊu u redu.|- Vrat ti je polomljen.
{24675}{24765}éao mi je öto ne mogu|da budem s tobom...
{24768}{24821}Znam, ser.
{24871}{24913}Kapetane...
{24961}{25048}...uhvatiÊete ih, zar ne?|- HoÊu.
{25976}{26067}Desetare,|popni se na ovaj vagon i baci pogled.
{26180}{26318}Idi ispred nas. Vidi kojim putem su otiöli.|Verovatno na jug.
{26321}{26411}Kapetane, zlato je nestalo.|Imaju ga, ser.
{26414}{26464}Tako sam i mislio.
{26498}{26530}Ovde, kapetane.
{26582}{26669}Imali su kola.|Vide se tragovi. Razdvojili su se.
{26672}{26768}Deo je otiöao ovim putem|sa kolima a ostali ovuda.
{26771}{26834}Kola su bila teöka|i na dolasku i na odlasku.
{26837}{26893}Tovar je mogao biti|ova gomila kamenja.
{26896}{26952}Moûda su hteli da to mislimo.
{26955}{27066}- Misliö li da je zlato na kolima?|- Pa, ja idem za kolima.
{27069}{27153}Povedi pola trupe|i pratite one koji su otiöli prema istoku.
{27156}{27222}Kartel,|ti i tvoja grupa pratite mene.
{27225}{27325}I poruËniËe... Ako ih uhvatite,|dovedite par njih natrag.
{27328}{27407}- I hoÊu da budu sposobni da priËaju.|- Da, ser.
{27556}{27603}Pratite me.
{28369}{28432}Dûenkins. Proveri taj trag.
{28668}{28714}- Kapetane.|- äta je?
{28717}{28801}Naöao sam dugme sa pobunjeniËke|uniforme. Moûda su poöli ovuda.
{28804}{28904}- Da li kola mogu tuda?|- Nema öanse.
{28907}{29016}Ti i Miler poite sa mnom|a ostali pratite taj trag.
{29344}{29417}Ako je zlato bilo u kolima,|sada ga pakuju.
{29420}{29526}- Uöli su u vodu ovde.|- Otiöli su uzvodno ili nizvodno?
{29529}{29568}Ko to moûe znati?
{29571}{29679}U redu. Vas dvojica idite nizvodno|a ja Êu uzvodno.
{30220}{30314}Hej, "Dûoni Reb",|ostani gde si!
{30460}{30509}Nenaoruûan sam.
{30544}{30620}To me i muËi.|Okreni se u svakom sluËaju.
{30829}{30896}- Nemoj ga udaviti.|- NeÊu.
{30941}{30997}Udario je glavu, kapetane.
{31022}{31076}Pomozi nam.
{31178}{31237}Teûi je od bebe kita!
{31324}{31424}- Tamo je sve mirno, vodniËe.|- Nadajmo se da tako ostane, kapetane.
{31736}{31786}Bolje ostavi taj zavoj na miru,
{31789}{31842}ukoliko ne ûeliö da ponovo prokrvariö.
{31845}{31927}- Kako se oseÊaö?|- Boli me.
{31930}{32043}- Udario si glavom od kamen.|- OseÊam se kao budala, uhvaÊen.
{32046}{32097}I ja bih isto.
{32130}{32208}Ti nemaö problem sa nogom.|Taj zavoj me je prevario.
{32211}{32248}Bajd mi ga je pozajmio.
{32251}{32319}I krv je takoe prava, pukovniËe.|Od jenkijevskog metka.
{32322}{32419}- Ko me je oborio s konja?|- Taskarora.
{32422}{32496}I mene malo boli pukovniËe.|Vi ste veliki Ëovek.
{32524}{32613}Vi ste jedinica koja nam|veÊ neko vreme krade tovare zlata.
{32616}{32716}- To je Ëetvrta tura koju ste uzeli.|- Jugu trebaju pare, pukovniËe.
{32719}{32788}Znam te od nekud, zar ne?
{32791}{32835}- TaËno.|- Kako se zoveö?
{32838}{32885}Pjer Kordona.
{32888}{32948}Majka Francuskinja, otac Meksikanac.|Iz Nju Orleansa.
{32967}{33019}Pre Ëetiri ili pet godina u Abelini.
{33022}{33080}- Tako je.|- Neöto oko konja, zar ne?
{33083}{33183}- Veliki dorat. Ti si ga bio ukrao.|- Nije taËno. Osvojio sam ga.
{33186}{33251}- Ti si osvojio alata.|- Alat je bio hrom.
{33254}{33340}Kada igraö poker,|treba da znaö u öta se igra.
{33343}{33414}SeÊam se.|Obojica smo bili na tom velikom doratu.
{33417}{33515}Ja sam bio napred|a ti pozadi sa piötoljem.
{33518}{33608}- Tvoji prijatelji su hteli da me ubiju.|- Meni se to nije svidelo.
{33611}{33723}PukovniËe, bolje Êu se oseÊati|ako se udaljiö od tih puöaka.
{33774}{33894}Niko nije bio povreen.|Reci mi, öto sam ja u ovoj opremi?
{33897}{34010}Pa, pukovniËe, ti si mene iskoristio|a sada Êu ja tebe.
{34013}{34090}Ovog puta ti ideö napred|i vodiö nas odavde.
{34093}{34179}Ako naletimo na Jenkije,|ti Êeö biti izmeu nas i njih.
{34182}{34275}- Prvi Êeö biti pogoen.|- Ne znam ja gde su sve naöe jedinice.
{34278}{34352}Ako ne znaö,|bolje pokuöaj da dobro pogodiö.
{34355}{34426}Da sam na tvom mestu|malo bih o tome razmislio pre polaska.
{34429}{34527}- Kad kreÊemo?|- »im padne mrak.
{34715}{34801}- Da li moraö da mi veûeö ruke?|- Kapetanova naredba.
{34823}{34932}PukovniËe, jahaÊu odmah iza vas.|Dobro bacam ovaj noû.
{34935}{35000}- A i ne pravi se buka.|- Jasno mi je.
{35003}{35089}Ugasi to svetlo.|I ta pozadi, takoe.
{35092}{35138}Spremite se za pokret.
{36009}{36050}Kapetane!
{36116}{36201}- äta je bilo, desetare?|- Kuda nas on vodi?
{36204}{36295}Juûno. Ne vidim zvezde,|ali bi trebalo da idemo na jug.
{36298}{36383}Greöiö.|Na kojoj strani drveta raste mahovina?
{36386}{36444}- Na severnoj.|- Mahovina je na ovoj strani.
{36447}{36503}U ovom momentu idemo na sever.
{36506}{36638}Svakako. Idemo na sever. Pola|äeridanove vojske je juûno odavde...
{36641}{36738}Jedini naËin je da ih zaobiemo.|Ne znam da li vas mogu provesti,
{36741}{36822}ali to je tvoja ideja, kapetane,|i ti se suoËi s njom.
{36825}{36943}Bolje da ne pokuöavaö neöto,|pukovniËe. Moûeö da zaûaliö.
{36960}{37004}Povedi.
{37389}{37437}Stani, pukovniËe.
{37511}{37590}Bliûimo se vodi i oseÊam neki dim.
{37593}{37681}- Pogledaj, vodniËe.|- Bolje da pripaziö na Jenkija.
{37863}{37954}- O Ëemu razmiöljaö, pukovniËe?|- Ne znam gde je baö svaka jedinica.
{37957}{38007}Moûda ima i vaöih "Dûoni Reb"-ova.
{38400}{38494}- Bez sumnje Jenkiji. KonjiËka uniforma.|- To Êe biti 10. Ohajska.
{38497}{38604}- Bili su udaljeni 20 milja juËe.|- Dosta brineö o lokaciji.
{38607}{38671}- Trudim se, vodniËe.|- Moûemo li proÊi?
{38674}{38807}- Bolje da pitaö ovog Jenkija.|- Najbolje da idemo s desna, istoËno.
{38810}{38903}Prenesi vesti.|Blizu smo jenkijevskog kampa.
{38906}{38980}Postarajte se da su konji tihi.|Koristite ruke ako morate.
{38983}{39090}- Kako Êu ja kad su moje vezane?|- Odveûi ga.
{39182}{39275}- Dobro pripazi, pukovniËe.|- HoÊu.
{39301}{39356}Hajde napred. Polako.
{40033}{40088}Vidiö li neöto, pukovniËe?
{40138}{40225}Pobunjenici s boka. Diûite se!|Dolazite ovamo.
{40256}{40301}Svako za sebe.
{40409}{40500}Podelite se i jaöite juûno.|SreöÊemo se kod mosta.
{40503}{40585}Nemojte da izgubite zlato.|Obrajen, ti i...
{42741}{42836}Nemoj da si nervozan, vodniËe.|Samo spusti piötolj.
{42888}{42986}Nastavi da se kreÊeö.|Kapetan ti je pokraj tog ognjiöta.
{43132}{43207}- äta mu se desilo, pukovniËe?|- Udario je glavu.
{43210}{43260}U redu je.|Probudi ga.
{43533}{43616}- äta je u toj konzervi, vodniËe?|- Rakija od kukuruza.
{43619}{43671}I meni bi dobro doölo malo toga.
{43889}{43934}Bolje budite tihi.
{43959}{44030}Kapetan vam je u pogreönoj uniformi,|seÊate li se?
{44153}{44206}Dakle, kapetane, kako se oseÊaö?
{44249}{44353}U peÊini si rekao da se oseÊaö kao|budala. Sada se ja tako oseÊam.
{44369}{44429}I mislio sam da si se suviöe lako predao.
{44432}{44530}Kada smo poöli da beûimo na sever,|zapravo smo iöli u nevolju.
{44533}{44648}- Baö ti je bilo stalo do tog zlata.|- Ne koliko mi je bilo stalo do vas.
{44651}{44736}Neko u mojoj uniformi|mora da vam je davao informacije.
{44739}{44820}- Njega ûelim.|- I hoÊete da ti mi kaûemo ko.
{44823}{44911}Recite mi i odvezaÊu vas|i okrenuti vam lea...
{44914}{44997}Vas dvojica imate dobre öanse|da pobegnete.
{45000}{45092}U suprotnom... vi ste zarobljenici|u pogreönoj uniformi.
{45095}{45178}- Znate öta to znaËi za vas!|- Da, ja znam.
{45181}{45248}A naöi momci gube öansu|da dobiju joö zlata.
{45251}{45315}Rat joö nije zavröen, pukovniËe.
{45343}{45436}U redu. Ovamo!
{45439}{45516}- Kapetane. Stanite!|- Ovamo!
{45832}{45898}Kapetane! Ovo sam upravo primio.
{45992}{46056}Prokletsvo! Sve ovo nizaöta!
{46059}{46115}RAT JE GOTOV
{46722}{46774}- HladnoÊa i groznica?|- Ne, ser.
{46777}{46827}- Imate grËeve?|- Ne.
{46830}{46907}ImaÊete, kad pojedete ovu svinjetinu.|Popijte ovo.
{46910}{46965}- SledeÊi|- Ime, Ëin, jedinica.
{46968}{47057}Makomb, Bajd.|Mlai desetar. Tupelo strelci.
{47060}{47143}Mala jedinica, a sve manja i manja.|»uo sam da sam samo ja ostao.
{47146}{47197}Duûina internacije, osam meseci.
{47200}{47255}Daj to blagajniku. SledeÊi.
{47258}{47349}- Bio si u pravu.|- Znao sam da Êe da doe.
{47352}{47423}Kordona, Pjer. Kapetan.|1. luizijanska konjica.
{47426}{47487}DobiÊete dva dolara, kapetane.|Potpiöite ovde.
{47490}{47551}- Imate pravo na vaö maË, kapetane.|- Mogu li da dobijem piötolj?
{47554}{47615}- Vatreno oruûje nije dozvoljeno.|- MaË nije ni bitan.
{47632}{47705}Filips, Taskarora, vodnik.|1. luizijanska konjica.
{47814}{47889}- Pjer i Taskarora.|- Imate dobro pamÊenje.
{47892}{47945}Drago mi je da ste prebrodili oluju.
{47948}{48014}Bio je to jednostavan ûivot -|bez vina, ûena, pesama.
{48017}{48081}- I bez viskija.|- Ja to mogu da promenim.
{48084}{48139}Ne smeta vam da pijete sa Blu Belijem?
{48142}{48229}- PiÊu sa samim avolom.|- I ja se isto tako oseÊam.
{48232}{48288}Idemo u pravom smeru.
{48587}{48646}Zdravo, tri viskija.
{48668}{48738}Ne to ubre!|Daj nam viskija.
{48741}{48811}Ali, pukovniËe, ovo je domaÊe.|Jamajkanski rum.
{48814}{48881}- Puno sam ga platio.|- I puno ga naplaÊujeö.
{48884}{48971}Daj nam to sa donje police.|Daj mi flaöu.
{49198}{49283}PukovniËe,|znam zaöto ste hteli da nas vidite.
{49286}{49385}Niste naöli onog|ko nam je rekao za vaöe zlatne ture.
{49388}{49459}Onog ko vam je prodao informacije|o naöim zlatnim turama.
{49462}{49531}Ne, nisam. Ali Êu ga naÊi.
{49534}{49585}ZvuËi liËno, pukovniËe.
{49588}{49660}MladiÊ koga znam od njegovog roenja
{49663}{49731}je bio u vagonu u koji ste ubacili osinjak.
{49734}{49782}Da li je bio teöko povreen?
{49785}{49868}- Sahranili smo ga sledeÊeg dana.|- éao mi je.
{49871}{49940}Ubili smo vaöeg prijatelja,|ali nas ne smatrate direktno odgovornim.
{49943}{50017}To se deöava u ratu.
{50020}{50144}Ali prodaja informacija, to je izdaja.|Prljava izdaja za novac.
{50147}{50221}- HoÊu njegovo ime.|- Bilo ih je dvojica.
{50224}{50280}Ne znam im imena.|Dali smo im novac.
{50283}{50359}- Oni nama informacije.|- Moûete li da ih opiöete?
{50362}{50448}Jedan je bio ogroman.|Skoro kao vi.
{50451}{50515}Onaj drugi... Tako kao vi.
{50518}{50586}Onaj drugi, bio bi primetan i u mraku.
{50589}{50678}Bio je kao albino.|Bela kosa, bela koûa. Manji Ëovek.
{50681}{50776}- To je sve.|- To je viöe nego öto sam ja znao.
{50779}{50831}Vas dvojica moûete da mi pomognete.
{50834}{50909}Ako naletite na nekog od njih, javite mi.
{50912}{50957}Budite sigurni da hoÊemo.
{50977}{51036}- Joö jedno piÊe?|- Dozvolite da mi vama uzmemo piÊe.
{51039}{51107}Koliko ste dobili na izlasku?
{51110}{51145}Dva dolara.
{51148}{51227}- Kuda ste krenuli?|- Malo Êu da razgledam.
{51230}{51279}Ja se vraÊam u Teksas.
{51282}{51341}»ovek koji me je odgajio|ima ranË u Rio Lobou.
{51344}{51402}NeÊeö stiÊi daleko sa dva dolara.
{51405}{51508}Dok ste bili iza reöetaka,|naöe plate su stizale na vreme.
{51511}{51571}BiÊe dovoljno do Teksasa.|Moûeö da mi dugujeö.
{51574}{51638}Nisam znao da Êu ikada|da poûelim da poljubim Jenkija.
{51641}{51769}Ako naletimo na nekog od one dvojice,|kako da vas kontaktiramo?
{51772}{51863}Blektorn, Teksas.|To je blizu tvog Rio Lobo okruga.
{51866}{51924}äerif tamo moûe|da stupi u kontakt sa mnom.
{52383}{52515}Vidim da je öerif Blektorn okruga uzeo|neöto novca od nagrade.
{52518}{52617}Jedna od ovih koûa|vredi dosta piÊa.
{52620}{52670}- Dobro je videti te.|- Hvala.
{52673}{52721}Pitao sam se kada Êeö se pojaviti.
{52724}{52804}Dobio sam tvoju poruku|da Pjer Kordona ûeli da me vidi.
{52807}{52863}Da. Svratio je sinoÊ.
{52866}{52955}U hotelu je.|Ui. PosluûiÊu te piÊem.
{52977}{53087}O Ëemu se radi, Kord?|Moûeö li mi reÊi zaöto si ovde?
{53123}{53241}Nije li Kordona uzeo par armijskih|platnih spiskova od Jenkija?
{53244}{53276}Tako je.
{53279}{53371}»uo sam da si ga uhvatio|i stavio u logor.
{53374}{53423}Dobro si Ëuo.
{53463}{53595}Kord, ne spremaö se da praviö nevolju,|zar ne? To mi se ne bi svidelo.
{53598}{53642}Ne brini, Pet.
{53645}{53703}Osim toga,|suviöe si dobar za tog mladiÊa.
{53706}{53790}Nema netrpeljivosti meu nama.|Rat je gotov.
{53793}{53871}Oh, to je dobro.|Zaöto onda hoÊeö da ga vidiö?
{53874}{53958}Jedini razlog öto je Kordona|nestao sa tim platama,
{53961}{54060}je zato öto su mu|neki od naöih prodavali informacije.
{54063}{54110}Njih traûim.
{54113}{54201}Radiö li za vojsku|ili je ovo liËno?
{54204}{54249}Oboje.
{54252}{54345}äerife, izgleda da ti stiûe druötvo.
{54348}{54446}- Ko od vas je öerif?|- Ja sam Pet Kronin. Ako ima neöto...
{54449}{54540}éelim da prijavim ubistvo. I hoÊu da|uhapsite Ëoveka koji je to uradio.
{54543}{54596}- Gde se to dogodilo?|- U Rio Lobou.
{54599}{54665}éao mi je, to je van moje nadleûnosti.
{54668}{54771}- NeÊete niöta da uradite?|- Izvinite. Rekli ste Rio Lobo...
{54774}{54872}Imate li vi veze sa öerifom?
{54875}{54944}- Ne, ja...|- Da li bi onda mogli da se ne meöate?
{54947}{55028}äerife, znaËi li to|da neÊete niöta da uradite?
{55031}{55091}To znaËi da ne mogu niöta da uradim.|Tamo nemam nadleûnosti.
{55094}{55122}»ovek je ubijen...
{55125}{55216}Ukoliko me US maröal|ili öerif Rio Loboa ne traûe da...
{55220}{55308}Vi znate öerifa Rio Loboa|i znate da vas neÊe traûiti.
{55311}{55341}Znam.
{55344}{55420}»ovek koji stoji iza ubistva|je jedan od njegovih zamenika.
{55457}{55489}éao mi je gospoice.
{55492}{55570}Pa, i meni je. Samo sam mislila...
{55639}{55671}I meni je!
{55791}{55904}- Ko je öerif Rio Loboa?|- Tom Hendriks.
{55928}{56012}- Blu Tom?|- TaËno. Nailazio si na njega?
{56015}{56116}Dovoljno sam ga jurio,|ali nikad mi se nije posreÊilo.
{56141}{56192}- äta kaûeö na piÊe?|- Izlazim.
{56195}{56241}Kao i obiËno. UzeÊu ti jedno.
{56413}{56458}Grad se öiri, Pet.
{56572}{56642}- Dobro jutro, Henk.|- Jutro. Mogu li da pomognem?
{56645}{56693}Upoznaj mog dobrog prijatelja|Korda Meknalija.
{56696}{56725}- Drago mi je.|- Hvala.
{56728}{56818}- Traûim Pjera Kordonu.|- Soba 19.
{56821}{56890}- KljuË je nestao.|- Sigurna sam da je gore.
{56893}{56989}Samo momenat.|Ostavio je poruku o neËemu.
{56992}{57114}UbiÊe svakoga ko ga probudi|ukoliko se ne radi o poûaru.
{57117}{57235}Dao mi je dva dolara da se postaram|da niko ne napravi poûar.
{57238}{57314}Sa dva dolara ovde|moûe da se kupi dosta sna.
{57317}{57391}- Onda da malo priËekamo.|- äta kaûeö na ono piÊe?
{57404}{57455}Ako se seÊaö, ti ga plaÊaö.
{57458}{57509}- Zdravo, Dûejn.|- Zdravo, öerife.
{57512}{57574}Sedi. Daj nam flaöu, Dûim.
{57696}{57747}Mala uûurbana gospoica.
{58005}{58125}Sigurno je ili u hotelu ili u zatvoru.|»ak, proveri zatvor.
{58420}{58485}- Nema nikoga u zatvoru, Vajti.|- U redu.
{58519}{58615}Dûordû, ti idi pozadi.|Ui sa te strane.
{58696}{58748}Vas dvojica sa mnom.
{59236}{59309}Pa, mlada damo.|Dosta smo te jurili.
{59312}{59426}äerife, ovo je Ëovek koga sam traûila|da uhapsite. On je ubica.
{59429}{59505}To moûe da pokvari|öerifovo miöljenje o meni.
{59508}{59569}Bila je to samoodbrana.|Pokuöao je da me ubode.
{59572}{59599}To je laû!
{59602}{59712}Stanite malo, ovo je moj posao.|äta vi zapravo traûite ovde?
{59715}{59826}Ime mi je Karter. Vajti Karter.|Zamenik öerifa iz Rio Loboa.
{59829}{59904}Ovde sam doöao da naem nju.|Traûena je.
{59907}{59939}Zbog Ëega?
{59942}{60044}Ona i starac sa kojim je ûivela su vodili|jedan od onih medicinskih poslova.
{60047}{60157}Znate veÊ, zmijsko ulje,|prevare sa ökoljkama, dûeparenje...
{60160}{60237}Joö jedna laû. Niöta nisam uradila.
{60240}{60348}äerif iz Rio Loboa samo hoÊe da|razgovara, tako da Êu da je povedem.
{60351}{60475}Stani malo. Ja sam öerif Blektorna.|HoÊu da vidim nalog.
{60478}{60557}- Nalog?|- Za hapöenje mlade dame.
{60560}{60605}Nisam se toga setio.
{60608}{60666}Bez naloga, nikoga ne vodite.
{60669}{60717}Ja imam nalog ovde.
{60760}{60877}Zadovoljni, öerife?|Sada, spusti piötolj i sedi.
{60914}{61008}U redu, svi budite mirni.|Niko neÊe biti povreen.
{61026}{61054}Hajde.
{61257}{61293}Pazi!
{61543}{61630}- Jesi li pogoen, Pet?|- Ne, povredio sam se kad sam pao.
{61633}{61687}Ostario si.
{61690}{61777}Zdravo, kapetane.|Drago mi je da si nam se pridruûio.
{61780}{61862}»uo sam buku i znao sam da si ti.|Kako je zapoËelo?
{61865}{61949}Ova mlada dama je ustrelila|tog belokosog Ëoveka.
{61952}{62040}- Baö joj se nije iölo sa njim!|- Moûeö li da joj zameriö?
{62043}{62097}Ovo je jedan od onih koje ti traûiö.
{62100}{62184}- Pa, nisam... Da li si siguran?|- Siguran sam.
{62187}{62231}Da li je mrtav?
{62234}{62310}- Naûalost, da.|- Da li sam ga ubila?
{62313}{62371}Ne sasvim, ali ste svakako pomogli.
{62374}{62478}Pa, nisam mogla da idem sa njim.|Radije bih bila mrtva.
{62481}{62580}- Skoro da ste nas sve poubijali.|- éao mi je...
{62598}{62657}HoÊete da se onesvestite?
{62711}{62810}- äta Êu s njom?|- Odnesi je u moju sobu.
{62853}{62944}- Gde je?|- Gore levo. Vrata su otvorena.
{63109}{63144}Neko je unutra.
{63147}{63243}Oh, zaboravio sam.|Hajde, Mejbl. Napolje.
{63246}{63295}Hajde. Pomeraj se.
{63298}{63380}- Zaöto ne mogu da spavam?|- ObjasniÊu ti kasnije. Hajde.
{63383}{63478}Da li je to razlog öto ja idem?|Mislila sam da si dûentlmen.
{63481}{63572}- Zauzet si.|- Drûim se dalje od kavge.
{63596}{63693}Henk, idi po pogrebnika.|Nema veze. Evo ga stiûe.
{63696}{63750}»uo sam pucnjavu, öerife.|Trebam li vam?
{63753}{63853}Imam dosta posla za tebe. Jedan ovde.|Dva tamo i jedan u Êoöku.
{63856}{63904}Odmah Êu da poËnem.
{63969}{64020}äta si otkrio?
{64023}{64126}PriËao sam sa vozaËem koËije|koji ju dovezao iz Rio Loboa.
{64129}{64201}Kaûe da ju je pokupio|par milja van grada.
{64204}{64264}Rekla nam je istinu.
{64267}{64378}On ju je jurio i ubio je|starca sa medicinskim kolima.
{64381}{64463}äta je Taskarora rekao u onom pismu?
{64492}{64585}Samo da je video jednog od ljudi|koje traûiö. »oveka bele kose.
{64588}{64707}- To Êe biti Vajti dole.|- Vajti je radio za bogatog Jenkija.
{64710}{64768}Taskarora kaûe da ranije|nije video tog Jenkija.
{64771}{64840}Ali ti ne bi doöao Ëak iz Blektorna|da mi to kaûeö.
{64843}{64964}Taskarora je u nevolji.|HoÊe da uzmu zemlju njegovog starog.
{64967}{65061}- I ti si mislio da Êu ja da se pridruûim?|- Dva piötolja su bolja od jednog.
{65064}{65132}Moûda traûimo istu stvar.
{65135}{65190}Moûda mogu da ti pomognem.
{65193}{65312}Pa, s tobom sam.|LÊi Êu Ëak do Rio Loboa i otkriÊemo.
{65315}{65406}- äta ste upravo rekli?|- Dakle, kako se oseÊate?
{65409}{65532}Ne znam. Niste li vi Ëovek|koji je bio dole...
{65535}{65590}...i pomogao nam|kad nam je trebala pomoÊ.
{65593}{65668}Pjer Kordona, gice...|Kako se zovete?
{65671}{65728}äasta - äasta Delejni.
{65731}{65806}Ne nosite pantalone, g. Kordona.
{65809}{65888}- Nisam imao vremena posle pucnjave.|- Sada imate.
{65891}{65975}- Zaöto ih ne obuËete?|- Jer vi leûite na njima.
{66089}{66190}- Ni vi nemate mnogo odeÊe na sebi.|- Ko mi je skinuo odeÊu?
{66193}{66230}- Ja.|- Zaöto?
{66233}{66310}- Bacali smo novËiÊ i ja sam dobio.|- Nikad nisam Ëula neöto tako...
{66313}{66424}Niste li Ëuli za popuötanje odeÊe|osobama kada su u nesvesti?
{66427}{66541}Oh, da.|Sigurno se ponaöam kao idiot, zar ne?
{66544}{66629}- Rekao bih skoro tako.|- Da, i ja isto.
{66632}{66686}Mislite da bih mogla da popijem piÊe?
{66689}{66781}- NeÊete ponovo da se onesvestite?|- Ne, g. Meknali.
{66784}{66838}Da li pijete samo|pre nego öto Êete da se onesvestite?
{66860}{66928}Teöko da je tako, gospoice.
{67026}{67079}Jeste li dobro?
{67138}{67239}Oh, nisam li Ëula neöto|o odlasku u Rio Lobo?
{67242}{67309}- Jeste.|- OdliËno. Idem sa vama.
{67312}{67383}- Ti? Oh, ne, ne ideö.|- Nemoj biti smeöna.
{67401}{67521}Koliko dobro poznajete Rio Lobo?|Nikada niste bili tamo.
{67524}{67634}Ne znate gde da idete,|s kim da priËate, ni ko je neprijatelj.
{67637}{67700}- Ja mogu da pomognem.|- Zaöto bi htela da ideö?
{67703}{67860}HoÊu da uzmem moja kola.|Stari »arli je hteo da meni ostanu.
{67898}{67955}Kad god se setim njega ja...
{68016}{68129}- U svakom sluËaju, to je sve öto imam.|- Ne moûeö da jaöeö u toj odeÊi.
{68132}{68204}Ako mi nabavite konja|biÊu spremna za deset minuta.
{68207}{68353}Kada trupe budu paradirale, javi mi.|BiÊu u baru.
{68430}{68480}Evo je.
{68496}{68554}Ja Êu to uzeti.
{68581}{68666}- Koliko ima do Rio Loboa?|- 70 ili 80 milja.
{68669}{68747}- Trebalo mi je tri dana koËijom.|- Nama Êe trebati joö viöe.
{68785}{68871}Neöto smo zaboravili.|Zna li ona da jaöe? Znaö li?
{68874}{68989}- Na koju stranu se penjeö?|- Na levu. Znao sam.
{69246}{69340}- PriliËno si dobar uËitelj, Francuz!|- Da.
{70100}{70201}Ovo izgleda kao dobro mesto da se|prespava. Hladno je, ali biÊe hladnije.
{70204}{70267}PogledaÊu öta ima da se zapali vatra.
{70270}{70365}äasta, da li moûda nemaö|flaöu onog zmijskog ulja?
{70368}{70432}- SluËajno imam.|- OdliËno.
{70983}{71078}Hej, zbog Ëega ste tako sretni,|pukovniËe?
{71081}{71169}Pa, popio sam dovoljno,
{71172}{71259}toplo mi je, i opuöten sam.
{71305}{71356}Pa, ako vi dobri ljudi...
{71426}{71548}moûete bez mene, ja Êu na spavanje.|Laku noÊ.
{71632}{71682}Ja se smrzavam.
{71700}{71750}Ovo Êe ti pomoÊi.
{71868}{71932}Nemoj to da radiö. Ne volim to.
{71939}{72043}- éao mi je. Hteo sam da...|- Sita sam dodirivanja.
{72046}{72113}äta se desilo?|Zbog Ëega si to rekla?
{72116}{72225}- Zaöto bih ti objaönjavala?|- Zato öto ûelim da znam.
{72263}{72303}U redu.
{72320}{72401}Bila sam udata.|Nije to bio dobar brak.
{72404}{72473}On nije mogao da pije, a ipak je pio.
{72476}{72535}A kada bi pio, nije bio dobar.
{72555}{72605}Kada bi pio, kockao bi se.
{72608}{72681}A kada bi izgubio,|mislio bi da je prevaren.
{72684}{72746}Ne znam da li su ga varali ili ne.
{72749}{72845}Ali jedan drugi Ëovek|je bio brûi a i dobar strelac.
{72848}{72915}Tako sam morala da naem posao.
{72927}{72993}Znaö li kako je raditi u kafani?
{72996}{73114}- Ne.|- Nikada te ne puötaju na miru.
{73145}{73180}Nikada.
{73262}{73340}Onda se pojavio dobri stari »arli Sims.
{73343}{73422}Jedini Ëovek koji je ikada|bio dobar prema meni.
{73425}{73483}I ubili su ga.
{73543}{73676}- Imaö li joö pitanja?|- Da. äta Êeö sada da radiö?
{73695}{73789}- Idem da spavam.|- Mislio sam kada se sve ovo zavröi?
{73872}{74033}UzeÊu »arlijeva kola|i onda idem... Ne znam.
{74036}{74095}Ne moûeö da vodiö|medicinski posao sama.
{74098}{74200}PriliËno sam dobra u ubeivanju ljudi da|kupe ApaËi biljni tonik.
{74203}{74288}Neöto Êe se desiti.|Uvek je tako.
{74331}{74413}Znaö öta... Sviaö mi se.
{74457}{74522}- Zaöto?|- Zato öto ne plaËeö.
{74525}{74606}Oh, ali ja plaËem. Video si me.
{74609}{74734}Plakala si zbog prijatelja, ne zbog sebe.|U tome je velika razlika.
{74789}{74874}Nemoj biti fin sa mnom, molim te.
{75063}{75121}- Nisam mislio da...|- Zar nisi hteo da to uradim?
{75124}{75214}Naravno da jesam.|Ali ja sam obiËno taj koji zapoËne.
{75217}{75330}Zato sam ja zapoËela.|Jer sada znam kada Êe da prestane.
{75333}{75400}Pa, ja bih...
{75403}{75458}Oh, laku noÊ.
{76281}{76396}Vidiö li ove motke iznad mene?|Ne znam Ëemu sluûe.
{76399}{76443}Sve su izgorele.
{76446}{76547}Rekao bih da su ih koristili Indijanci|da sahrane svoje mrtve.
{76550}{76639}Stavljaju tela na motke i onda ih spale.
{76642}{76725}- Verovatno leûiö na neËijoj lobanji...|- äta?
{77383}{77437}äta kaûete na buenje?
{77540}{77613}- Kako se ona stvorila ovde?|- Pitaj je.
{77692}{77835}- Otkud ti ovde?|- Dok si spavao. Bilo je hladno.
{77841}{77905}Zaöto kod mene? Zaöto ne kod njega?
{77908}{78001}On je mlad. Mislio sam...|Pa, ti si stariji.
{78004}{78062}- Ti si udoban.|- Udoban?
{78065}{78141}Zvali su me raznim imenima,|ali "udobnim"!
{78144}{78257}Jedno Êu reÊi.|Bolje ugrejeö Ëoveka nego vruÊa cigla.
{78274}{78330}Lepo je biti cenjen.
{78333}{78441}- Da li ja to miriöem kafu?|- Da. Ustani i posluûi se.
{78473}{78525}Diûi se i na posao.
{79073}{79116}Hajde.
{79545}{79669}- Ovo je Rio Lobo. Pogledajte.|- PriliËno je tiho.
{79672}{79735}Kasno je da se bilo öta zapoËinje.
{79738}{79837}Gde ûivi Taskarorina devojka?|Rekla si da se tamo moûemo sakriti.
{79840}{79930}Da, ona je na kraju grada.|U blizini je i ötala za konje.
{79933}{79991}Moûemo li tamo a da nas niko ne vidi?
{79994}{80062}Da, ako moûete da preete ulicu.
{80090}{80158}- Pogledaj, Francuz.|- Dobro.
{81104}{81151}Ja sam, äasta.
{81176}{81225}Poûuri, Marija.
{81431}{81536}Sluöaj, ovo su Taskarorini prijatelji.|Doöli su da pomognu g. Filipsu.
{81539}{81661}Ovo je kapetan Kordona.|A ovo je pukovnik Meknali.
{81664}{81770}- Treba nam mesto da prenoÊimo.|- Ali konji...?
{81773}{81846}- Nije dobro ako su i oni tu.|- Gde je dobro mesto?
{81849}{81929}Tamo ima prazna kuÊa. Vidiö?
{81932}{81992}NaÊi Êete ötalu s desne strane.
{81995}{82099}- U redu. Ja Êu ih odvesti.|- Budi paûljiv. Posmatraju.
{82102}{82199}- Zaöto si se vratila?|- To je duga priËa.
{82202}{82293}Ali prvo, reci mi öta rade KeËam i öerif?
{82296}{82379}Teraju Filipsa da proda ranË.
{82382}{82432}- Da li ga je prodao.|- Ne znam.
{82435}{82515}Taskaroru nisam videla|otkako si ti otiöla.
{82518}{82577}Svi ovde su uplaöeni.
{82580}{82626}äerifovi ljudi svuda osmatraju.
{82629}{82685}- Osmatraju li ovu kuÊu?|- Svuda.
{82688}{82744}Nije bezbedno za vas da ostanete.
{82747}{82824}VeËeras moramo da ostanemo.|Nismo jeli.
{82827}{82932}Izvinite, nisam se setila.|Smesta Êu neöto da pripremim za vas.
{84647}{84727}Izvinite. Neko me juri.|Nemam kuda.
{84732}{84788}- Ne moraö da ideö.|- äta?
{84821}{84875}Moûeö da ostaneö ovde.
{84905}{85004}- Moûeö li da ugasiö to svetlo?|- Kako ti kaûeö.
{85112}{85201}Hvala. Nemoj da stojiö na sred sobe.
{85348}{85426}- Vidiö li nekoga?|- Nikoga.
{85429}{85490}- HoÊeö li da ja pogledam?|- Ja gledam.
{85493}{85597}- Da, ali ja mogu da izaem napolje.|- Bolje prvo neöto obuci.
{85615}{85703}- Kako ti kaûeö.|- Ne, nisam to mislio.
{85706}{85814}- Ne mislim da treba da izlaziö.|- Dakle... moûemo da ostanemo ovde.
{85879}{85987}Imam dosta tortilja i pasulja|i ljutih paprika i neöto vina.
{85990}{86087}- ZvuËi dobro. Voleo bih da mogu ostati.|- Zaöto ne?
{86090}{86189}Zato öto mislim da su sada otiöli.|Moram da se vratim mojim prijateljima.
{86192}{86286}- éao mi je.|- Ne znam kako da ti se zahvalim.
{86289}{86372}- I ne moraö.|- Ime mi je Pjer. Kako se ti zoveö?
{86375}{86449}- Hvala ti, Amelita.|- Stani malo.
{86541}{86589}U redu je.
{86761}{86812}To dobro miriöe.
{86908}{86958}Ui.
{86961}{87061}- Gde si bio?|- Ostavio sam konje i krio sam se.
{87064}{87149}- Krio si se? Od koga?|- Od ljudi koji osmatraju grad.
{87152}{87235}- Rekla sam ti. Gde si bio?|- U kuÊi neke devojke.
{87238}{87331}Devojke? Brzo radiö.|Gde si je upoznao?
{87334}{87442}Zalupio sam vrata, kad eno nje.|Lepa je. Tamna kosa.
{87445}{87535}- I mislim da se zove Amelita.|- Znam je. Ona mi je prijateljica.
{87538}{87600}- Pa, pomogla mi je.|- Nadam se da si se lepo proveo.
{87603}{87657}Prestani.|äta Êemo sada da radimo?
{87660}{87705}PrenoÊiÊemo ovde.
{87708}{87769}Ujutro Êu da odem do grada|da vidim öta mogu da otkrijem.
{87772}{87821}Zaöto ne odemo do Filipsovog ranËa...
{87824}{87899}Ako osmatraju grad, bez sumnje|osmatraju i ranË.
{87902}{87957}- A i öerif te poznaje, zar ne?|- Poznaje me.
{87960}{88031}HteÊe da zna öta radiö ovde.
{88034}{88114}Uvek ûeli da sazna sve o strancima.
{88117}{88256}Umotaj ruku i reci da si povreen|i da traûiö doktora.
{88259}{88384}Zubar je prijatelj Taskarore i g. Filipsa.|On vam moûe dosta toga reÊi.
{88387}{88496}OseÊam da mi se bliûi zubobolja.|Nadam se da imaö dosta vina, Marija.
{89231}{89293}Hvala. Pobrini se da dobiju vode.
{89296}{89346}- VratiÊu se brzo.|- Budi paûljiv.
{89748}{89823}- Proölo je dosta vremena, Marija.|- U redu momci, idemo.
{89872}{89943}Taskarora. Doi ovamo.
{90115}{90150}HoÊeö da me vidiö?
{90153}{90238}Upravo si doveo konje u grad.|Da li su tvoji?
{90241}{90308}- Naöi su.|- Mislim da su neki od njih ukradeni.
{90311}{90358}To je laû.
{90361}{90424}Ne. Pustite ga na miru!
{90427}{90464}Prekinite!
{90501}{90558}Prekinite s nasiljem!
{90979}{91020}Dosta je.
{91109}{91135}äta se deöava?
{91138}{91235}UËimo ga ponaöanju.|Krao je konje.
{91289}{91381}Neka ostane dovoljno ûiv za veöanje.|Vodite ga u zatvor.
{91384}{91447}Hajde. Diûi se.
{91495}{91583}- Povedi i devojku.|- Zaöto?
{91751}{91811}Jesi li u redu, damo?
{91901}{91966}Najbolje je da ideö kuÊi.
{92023}{92062}Hajde!
{92089}{92148}Ti si nov u kraju, zar ne?
{92166}{92239}- Jutros sam stigao.|- Planiraö dugo da ostaneö?
{92276}{92396}- Zubobolja.|- Doco, imam muöteriju za tebe.
{92488}{92577}Kad srediö zub, iskaskaj iz grada.
{92620}{92674}ZvuËi kao dobar savet.
{92760}{92840}- Doktore...|- Uite, gospodine.
{93012}{93116}Pripazi na onog velikog.|Vidi da li stvarno ima pokvaren zub.
{93191}{93266}- Dakle, imaö pokvaren zub?|- Ne, nemam.
{93269}{93348}- Sedi na stolicu.|- Rekao sam ti, zub mi je u redu.
{93375}{93447}- Zar ne moûemo da porazgovaramo?|- Vidiö li onog momka tamo?
{93450}{93519}Proverava tvoju priËu o zubu.
{93522}{93636}- Otvori usta öiroko.|- Ne mogu da priËam otvorenih usta.
{93639}{93715}Ja postavljam pitanja,|ti samo klimaj glavom.
{93718}{93810}Ona devojka, Marija, öto su je|pretukli... Je li te ona poslala?
{93813}{93899}- Da.|- Tako sam i mislio jer si se tako pojavio.
{93902}{93941}To boli.
{93944}{94021}VeÊina mojih pacijenata se puno dere.|Pogledaj tamo.
{94190}{94293}- Nema ga.|- Da li je to moj zub?
{94296}{94349}Ne. Tvoji su u redu.
{94352}{94414}Reci mi öta se ovde deöava.
{94417}{94554}Onaj koji svime upravlja je KeËam.|Doöao je ovde odmah posle rata.
{94557}{94689}Hendriks je ubio naöeg öerifa|i KeËam ga je proglasio novim öerifom.
{94735}{94821}- Pogledaj tamo.|- Voleo bih da znam o Ëemu priËaju.
{94824}{94885}Nema potrebe... ucena.
{94917}{94969}Rade iste stvari kao i do sada.
{94972}{95065}Hendriks öalje siledûije|na ranË starog Filipsa.
{95068}{95156}OteraÊe mu svu stoku,|tako da on nema niöta.
{95159}{95236}Onda Êe mu reÊi da jedini naËin da|spase svog sina od veöanja
{95239}{95345}je da im prepiöe ranË|za Ëetvrt prave vrednosti.
{95348}{95422}Znam tog starca.|Tvrdoglav je kao magarac.
{95425}{95479}Ali mnogo voli svog deËaka.
{95501}{95598}Tako Êe ga drûati dok ne popusti|i ne prepiöe im zemlju.
{95601}{95672}KeËam je nakupio dosta zemlje.
{95675}{95788}- Sve ono öto vredi, gospodine...?|- Nije ni bitno.
{95804}{95889}Pa, g. Nije-ni-bitno, nadam se|da ti moûeö neöto da uradiö.
{95892}{95983}- Imaö li dosta ljudi da ti pomognu?|- Pa, ne baö. Nemam.
{95986}{96079}Nek je Bog s tobom.|éelim ti svu sreÊu.
{96082}{96143}Moramo joö jednom da se proderemo.
{96146}{96223}ObiËno se svi dobro proderu|kad im dam ovu injekciju.
{96269}{96321}To je prava injekcija.
{96324}{96413}Da si bio dobar glumac,|ne bih je koristio.
{96416}{96475}To Êe biti dolar i öest deliÊa.
{96501}{96592}- HoÊe li Ëetiri dela biti dovoljno?|- Taman.
{96628}{96734}- Hvala, g. Nije-ni-bitno.|- Meknali. VideÊemo se.
{96924}{97030}Morate da se sakrijete. Marija kaûe|da je öerif poslao ljude ovde.
{97044}{97146}- Gde moûemo da se sakrijemo?|- Pod krevet. Brzo.
{97149}{97266}Samo momenat.|Pospite malo vode po mojoj glavi.
{97380}{97453}- Sve?|- Da, slobodno.
{97746}{97817}- Ko je?|- Otvori.
{97820}{97881}- Samo momenat.|- Poûuri.
{97884}{97929}Samo momenat.
{98035}{98102}- Ima li joö koga ovde?|- Pa, vi ste ovde.
{98105}{98195}- Ne vidim vas. Ko ste vi?|- Iz öerifove kancelarije.
{98316}{98372}Ovde nema nikoga.
{98641}{98685}Otiöli su.
{98863}{98949}- Zaöto se smejete?|- NeÊeö poverovati öta je rekao.
{98952}{99057}- To je privatno.|- Da li ti to zaista upali?
{99060}{99157}- Znaö li öta je rekao?|- äta je rekao?
{99160}{99258}"Joö jedan poljubac pre nego öto|umremo." Moûeö li da zamisliö?
{99261}{99309}- To je glupo.|- Nije.
{99386}{99450}- Ko je to?|- Ja.
{99500}{99558}- äta si otkrio?|- Dosta toga.
{99561}{99617}Jutros su pretukli Mariju,
{99620}{99690}zatvorili su Taskaroru|zbog krae sopstvenih konja,
{99693}{99788}i otiöli su na ranË starog Filipsa|da ga nateraju da popusti.
{99791}{99862}- HoÊemo li to da im dozvolimo?|- Ne ako moûemo uraditi neöto.
{99865}{99922}éao mi je öto nisam mogla doÊi ranije.
{99925}{99994}- Bilo je ljudi.|- Imali smo posetioce.
{99997}{100079}- Raspitivao sam se o putu do ranËa.|- Ja Êu te povesti.
{100082}{100144}- Nama govora!|- Ovde ne moûe da ostane.
{100147}{100205}Ti to znaö, zar ne?|UzeÊu kola.
{100208}{100274}- Zaöto?|- To je sve öto mi je ostalo.
{100277}{100334}Moûda mi se ponovo ne ukaûe|öansa da se vratim po njih.
{100337}{100386}Mora da nam zaista mnogo verujeö!
{100389}{100439}Vi ste dobri,|ali suoËavate se s velikim problemom.
{100442}{100541}- Moûeö li neprimetno da odeö iz grada?|- Sa sreÊom. Pomozi mi, Amelita.
{100544}{100617}SreöÊemo se istoËno od grada,|pola milje od male crkve.
{100620}{100722}Ja Êu vam pokazati.|äta joö mogu da uradim za vas?
{100725}{100804}Pomoli se.|VratiÊemo se ako sve bude u redu.
{100807}{100857}BiÊe suviöe teöko za samo dva Ëoveka.
{100860}{100913}Nadam se da Êe nas biti trojica|kad sretnemo g. Filipsa.
{100916}{101011}- HoÊeö li nam pokazati put?|- Da. Pratite me.
{101399}{101454}Tamo su dvojica pored one kapije.
{101457}{101507}Ne vidim treÊeg...
{101510}{101586}Stani malo.|Vidite li onu straÊaru iza kuÊe.
{101589}{101671}- Izgleda kao dim od cigarete.|- Imaö dobar vid.
{101674}{101710}Vidim ga.
{101713}{101822}- Moûeö li izaÊi na kraj s njim?|- Naravno. Mogu da mu priem iza lea.
{101825}{101860}U redu.
{101882}{101924}A ti?
{101927}{102008}OstaviÊemo äastu u kolima|pa kada mi proemo...
{102011}{102085}Kako Êete da im se pribliûite?
{102088}{102171}Udobni muökarac|je reöio da ih ustreli.
{102174}{102222}Kako Êeö da ueö u kuÊu?
{102225}{102305}Filips Êe ti prosuti mozak|pre nego öto sazna na Ëijoj si strani.
{102308}{102357}- Da ti nisi...?|- Ne budi sarkastiËan.
{102360}{102421}- Imaö li neki predlog?|- Da, imam.
{102424}{102484}Ja Êu da uem s kolima.|Vi Êete biti pozadi.
{102487}{102535}HoÊeö li da pogineö?
{102538}{102627}Ubili su »arli Simsa...|éelim da plate za to.
{102630}{102694}- Ja sam protiv toga.|- Ovo ti je prvi korak, zar ne?
{102697}{102762}Ako ne uspeö,|neÊe se pruûiti druga öansa.
{102765}{102845}- Ja to ne dozvoljavam.|- On je zaljubljen u mene.
{102848}{102929}- Nisam to rekao.|- Rekao si da misliö da jesi.
{102932}{103026}Idemo li da spasemo starca|ili ostajemo ovde da se svaamo?
{103029}{103148}Daj mi par minuta pre nego öto kreneö|ali mi se i dalje ne svia ta ideja.
{103151}{103227}To izmeu vas dvoje|- onako iznenada, zar ne?
{103230}{103332}Nisam ja, on je. Da li su svi Meksikanci|nagli kao öto je on?
{103335}{103387}Jedan mali poljubac|i balon se veÊ naduvao?
{103390}{103458}Hajdemo u kola.
{104271}{104334}Proölo mu je dva minuta.
{104337}{104412}Joö dva minuta i znaÊemo|da li je tvoja ideja bila dobra.
{104415}{104478}Kada zapoËne pucnjava,|ne zaboravi da se sagneö.
{104481}{104528}Da, pukovniËe.
{104543}{104605}Idemo.
{105153}{105204}Imaö posetioce.
{105314}{105383}äta li je to, sto mu gromova?
{105404}{105456}Ostani gde si, gospoice.
{105518}{105587}- Kuda si krenula?|- Konjima treba vode.
{105590}{105678}- Mislila sam do Êu je ovde naÊi.|- Ovaj put nije bezbedan...
{105681}{105746}Nije li ona devojka|koju je Vajti Karter traûio?
{105749}{105803}- Jesi li to ti?|- Da, ja sam ta.
{105806}{105902}- Imaö li joö onog zmijskog ulja?|- Da, imam ga dosta u kolima.
{105905}{105958}Mislim da Êu da uzmem malo.
{105961}{106038}Gde si bila? Svuda te traûe.
{106041}{106115}Ne znam... Oh, mislim da vam mogu reÊi.
{106118}{106178}Ne svia mi se Vajti.|Nisam htela da me pronae.
{106181}{106258}Svako ima drugaËiji ukus. Ne moûeö...
{106282}{106364}- äta to bi?|- Sigurno tvoj prijatelj uzima zmijsko ulje.
{106367}{106492}äta devojka treba da uradi|kad je momak svuda prati?
{106495}{106556}Umorna sam. Nisam spavala.
{106559}{106634}Osim pre neku noÊ, na mestu|gde je neki Indijanac sahranjen.
{106637}{106719}- Bilo je uûasno!|- Gde je to Indijanac sahranjen?
{106722}{106803}Ne seÊam se. Bilo je to|pre nego öto me je neko udario.
{106806}{106889}- Udarili su te?|- Nisam ga videla, ali me je udario.
{106892}{106956}- Gde?|- Ovde.
{106959}{107040}Dugo ti je trebalo.|Ponestajalo mi je tema za priËu.
{107043}{107086}To je teöko poverovati.
{107150}{107203}- Poûuri.|- Samo malo.
{107233}{107310}äta se tamo dogaa? Ko je tamo?
{107313}{107365}Odgovorite ili pucam.
{107368}{107438}Stani malo. HoÊemo da ti pomognemo.
{107596}{107683}- Prestani da pucaö budalo.|- Ne prilazite viöe!
{107686}{107790}- Ja idem. NeÊe pucati na ûenu.|- Nemoj na to da raËunaö.
{107864}{107920}G. Filips, pustite me unutra.
{107949}{108024}Samo ti ostani tu gde si.
{108066}{108119}äta se tamo dogaa?
{108341}{108399}Pazi. Dalje od tog prozora.
{108447}{108497}- Gde je äasta?|- Unutra.
{108529}{108579}- Ko je tamo?|- Ja sam.
{108582}{108651}- Ko si ti?|- Pjer Kordona.
{108654}{108736}- Taskarorin kapetan?|- Bio nekad.
{108739}{108781}Niöta ne pokuöavaj.
{108827}{108934}Ti, veliki, silazi s tog Ëuda.
{109054}{109148}Podigni ruke visoko|i polako kreni ovamo.
{109189}{109285}I ti isto, Kordona. I drûi ih visoko.
{109346}{109404}Samo ih drûite visoko.
{109615}{109710}Drûite ruke gore i recite neöto. Hajde.
{109713}{109787}- äta da kaûem?|- Da te Ëujem da priËaö.
{109790}{109849}- Ako prekineö da me bodeö...|- Znao sam!
{109852}{109920}Prepoznajem po govoru da si Jenki.
{109952}{110036}- Zar mu nisi rekla?|- Teöko ga je ubediti.
{110039}{110116}Video bih vas,|da vas napadne gomila niötarija.
{110119}{110226}Ti reËe da si bio kapetan mog malog.|Kako da ti verujem?
{110266}{110333}Da li ti je pisao o naöoj prvoj bici?
{110385}{110506}- Nije li bio pogoen u ruku?|- Mislim da govorite istinu.
{110509}{110568}äta ovaj prokleti ogromni Jenki radi|ovde?
{110571}{110644}Prokleti ogromni Jenki juri drugog|prokletog ogromnog Jenkija
{110647}{110695}i usput pomaûe tebi.
{110701}{110782}- Kako se zoveö?|- Kord Meknali.
{110785}{110840}Zar ti Taskarora nije priËao o meni?
{110843}{110937}Svakako da jeste.|I neÊu da ponavljam öta je rekao.
{110940}{110985}Reci neöto o njoj.
{110988}{111077}Ustrelio bih je, da nema najlepöe noge|koje sam ikada video.
{111080}{111167}- Nisam imao priliku kao vi.|- äta Êe ona ovde?
{111170}{111252}Vajti Karter joj je ubio prijatelja.
{111255}{111323}Starog »arli Simsa. »uo sam.
{111326}{111383}- Sad znam ko je ona.|- Vajti je mrtav.
{111386}{111436}Najbolje vesti koje sam Ëuo ove godine.
{111439}{111504}- Ko ga je ubio?|- Ona.
{111507}{111613}Pa, baö sam naivan kao govedo! Takve|noge a zna i da puca.
{111640}{111717}Duûan sam vam öto ste me izbavili|iz nevolje u kojoj sam bio.
{111748}{111835}- Ovo treba nazdraviti.|- Meni svakako treba piÊe.
{111838}{111915}Imaju mog malog.|äta Êete da uradite po tom pitanju?
{111918}{111971}UjahaÊete u grad i provaliti u zatvor?
{111974}{112049}Ovo nije za mlade.|Od Ëega si ga napravio?
{112052}{112116}HoÊeö li tek tako da provaliö u zatvor?
{112119}{112208}Odgovor je ne,|osim ako ne ûeliö da ga ubiju.
{112211}{112270}- Misliö da sam budala?|- Ne radi se o tome.
{112273}{112323}Treba nam neöto za razmenu.
{112326}{112368}- Kao na primer?|- Recimo KeËam.
{112371}{112435}KeËam? Da li si ti ozbiljan ili lud?
{112438}{112517}Oboje po malo,|ali to je jedini naËin da ti izbavimo sina.
{112520}{112613}- Kako da stigneö do KeËama?|- Ti mu dobro poznajeö ranË.
{112616}{112698}- Bio sam tamo pre nego öto ga je uzeo.|- Koliko je udaljen?
{112701}{112731}Dva... tri sata.
{112734}{112859}- Ideö li sa nama?|- Pa i ja sam pomalo lud.
{112862}{112965}Ima li neko bezbedno mesto za ovu|mladu damu dok se mi ne vratimo?
{112968}{113028}Kod Henka Prajora koji nam je usput.
{113031}{113118}Mislim da Êemo stiÊi pre mraka,|ako smesta krenemo.
{113121}{113179}- Ja Êu s vama. Mogu da pomognem.|- Ti ne ideö.
{113182}{113266}Pukuöavaö da upravljaö stvarima|otkako smo se sreli.
{113269}{113367}Budi mirna i sluöaj me. Ti ne ideö!
{113370}{113446}- Samo joj reci, Francuz.|- Da.
{113531}{113617}Dao bih sve moje konje da mi se|pruûi öansa da sretnem tog momka.
{113620}{113683}G. Prajor, ako se mi ne vratimo, ti reËe...
{113686}{113749}NeÊu vas razoËarati.
{113755}{113813}Rekao sam ti|da Êu odvesti devojku u Blektorn.
{113816}{113857}Hvala ti.
{113885}{113927}- Hajde, äasta.|- Ne.
{113980}{114034}Sto mu...? Francuz!
{114037}{114138}Ideö li ti s nama ili imaö|neöto pametnije da radiö?
{114171}{114211}To je smeöno pitanje, pukovniËe.
{114214}{114280}I ti bi hteo to da radiö, zar ne?
{114304}{114415}Ne, g. Filips, nema ni govora.|Ja sam samo udoban.
{114504}{114594}Zoveö me Francuz. Ja sam|polu-Meksikanac, znaö li ti to?
{114597}{114707}Da. Koja polovina je kleËala|a koja ljubila ruku?
{115151}{115228}- Gde li se KeËam nalazi?|- U velikoj kuÊi.
{115231}{115306}- Kako izgleda?|- Ogroman. Crna kosa. Brkovi.
{115309}{115354}To moûe biti bilo ko.
{115357}{115453}Moûe biti onaj öto je bio s Vajtijem|kad smo im davali novac.
{115495}{115604}- Koliko ima ljudi?|- 15 ili 20 ruku u zgradi za radnike.
{115607}{115674}Eno jednog tamo,|i joö jednog malo udesno.
{115677}{115767}I oni öto Ëuvaju mesto,|öto bi vi rekli straûari.
{115770}{115880}- KeËam niöta ne prepuöta sluËaju.|- Vidim trojicu... ne, Ëetvoricu.
{115883}{115936}Eno jednog pored kapije.
{115939}{116036}Moramo njih prvo da sredimo,|onda da uemo u kuÊu,
{116039}{116127}uhvatimo KeËama, i onda ga iskoristimo|da se otarasimo ostalih.
{116130}{116233}- Kaûeö bolje da ga ne ubijemo?|- Bolje je da ga ne ubijemo.
{116236}{116336}- Dakle, Francuz?|- Ja Êu se pobrinuti za onog ispred kuÊe.
{116339}{116415}Ja Êu onog s leva|i onog ispred zgrade za radnike.
{116418}{116462}Ostavite jednog za mene.
{116465}{116537}Moûeö li da se priöunjaö|onom pored kapije?
{116540}{116606}Mogu se priöunjati kojotu ako hoÊu.
{116609}{116668}Najbolje da ja krenem prvi.
{116671}{116732}Ne valja da se baca.
{116768}{116823}Podseti me da neöto pitam Taskaroru.
{116826}{116866}äta to?
{116869}{116951}Rekao je da si ti pravi svetac|koji nema poroka.
{116954}{116999}Nemam ja niöta s porocima.
{117002}{117102}To me ne spreËava da uûivam kao|svetac kad mi se pruûi öansa.
{117130}{117246}- Zaöto nisi zatrubio?|- Spreman? Ako nisi, ja idem sam.
{119977}{120027}- Gde je starac?|- Evo ga.
{120030}{120092}Da li si sredio onog kraj kapije?
{120095}{120145}Sad je kod druge kapije|i Ëeka Svetog Petra.
{120416}{120501}Onaj veliki za stolom,|je onaj öto sam mu dao pare.
{120504}{120552}Vodnik Ajk Gorman.
{120803}{120864}Dugo sam Ëekao ovaj trenutak.
{120965}{121027}Stariji vodniËe Gorman,|kako se sad oseÊaö?
{121061}{121182}SeÊaö li se poruËnika Forsajta?|Ovaj je za njega.
{121417}{121464}- Diûi se!|- Samo na kratko.
{121654}{121728}Meknali, daj mu jedan za Taskaroru.
{121854}{121907}U redu, hajde da popriËamo s tvojima.
{121910}{122002}Reci im da ako se mrdnu,|prosuÊu ti mozak. Proderi se.
{122005}{122124}»ujete li me? KeËam ovde.|Ne pomerajte se. Niöta ne preduzimajte.
{122127}{122180}- »ujete li me?|- Da, Ëujemo te.
{122183}{122256}Reci im da dovedu naöe konje.|I jednog za tebe.
{122259}{122320}Dovedite im konje i jednog za mene.
{122323}{122359}U redu.
{122362}{122477}Pitaj ga gde je sakrio tapije|od svega öto je pokrao.
{122480}{122552}Ne misliö valjda da ih ovde Ëuvam?
{122555}{122627}Gde ih Ëuvaö? Gde su?
{122630}{122672}- U banci.|- Gde?
{122675}{122735}- U banci.|- Gde?
{122749}{122854}Ovde su. Iza tog ormana. U sefu.
{122857}{122901}Pogledaj.
{123081}{123127}ZakljuËano je.
{123357}{123433}Evo ih, Meknali. Sve öto smo traûili.
{123436}{123470}Pazi!
{123547}{123608}Gorim! Pomozite, molim vas!
{123617}{123690}- Filips, pomozi mi, molim te.|- Neka izgori.
{123693}{123766}Nemoj da izgori|pre nego öto potpiöe ove papire.
{123769}{123852}- Jesi li spreman da potpiöeö?|- Sve Êu da potpiöem.
{123855}{123895}U redu, Francuz.
{124086}{124209}KeËam, pogledaj ovo.|OkidaËi su zavezani.
{124212}{124291}Vidi öta se deöava|kad mi se palac oklizne.
{124294}{124372}A ni palËevi mi nisu jaki kao nekad.
{124398}{124456}Imamo vaöe konje.|äta da radimo s njima?
{124459}{124551}Dovedite ih do kuÊe. Hajde, kreÊi.
{124611}{124705}Jedan neka drûi konje.|Ostali, raziite se.
{124821}{124874}Izlazimo.
{124905}{124980}Uradite kako kaûe. Niöta ne pokuöavajte.
{125018}{125081}Ti uzmi alata. Ovaj je moj.
{125084}{125157}Moûeö li da ga pripaziö|dok ne uzjaöem?
{125286}{125375}TuËa unutra me je baö izmorila.
{125402}{125463}U redu, KeËam, pomeraj se.
{125571}{125621}Hajde da stanemo ovde.
{125637}{125684}Ne mogu viöe da jaöem ovako.
{125687}{125762}Da li bi radije da hodaö?
{125786}{125858}- Da li nas neko prati?|- Nisam nikoga video.
{125861}{125938}Da malo popriËamo.|Ti hoÊeö da izbaviö sina iz zatvora,
{125941}{126019}...zar ne, g. Filips?|- Svakako da hoÊu.
{126022}{126098}- Kako Êemo da ga izbavimo?|- IskoristiÊemo KeËama.
{126101}{126222}A koliko vremena misliö da Êe trebati|Hendriksu da nas pohvata?
{126225}{126327}Ti i tvoje vojno razmiöljanje.|Moraö da imaö reöenje za sve.
{126330}{126392}- äta Êemo da radimo?|- U redu.
{126395}{126471}Mi civili nismo budale|kao öto vi Jenkiji mislite.
{126474}{126547}- Ima tvrava kod Longhorn Springsa.|- Tako je.
{126550}{126644}- Tamo Êemo ga odvesti.|- äta Êe Hendriks da radi?
{126647}{126721}Radije bi da vidi KeËama mrtvog|nego da ga vojska uhvati.
{126724}{126792}- Imaö li ti neki plan?|- Da.
{126795}{126916}Ne vadimo Taskaroru iz zatvora, veÊ mu|se tamo pridruûimo i utvrdimo se. Ti...
{126919}{126995}A ja idem do Longhorn Springsa|i dovodim konjicu.
{126998}{127085}- Mudro za jednog kapetana, Francuz.|- Hvala, ser.
{127088}{127163}Moraö da se vratiö sutra|do kasno popodne.
{127166}{127226}Ako upadnemo u nevolju,|do tada se moûemo snaÊi.
{127229}{127321}Idim ovim putem dok ne stigneö do puta|za kola, onda skreni prema zapadu.
{127324}{127395}Sretno, pukovniËe. Ser.
{127398}{127477}Ne zaboravi da mi se palac umorio.
{127480}{127595}Izbegavaj kamenje. Konj moûe|da mi se spotakne i imaÊemo nesreÊu.
{127740}{127845}- äta vi radite ovde?|- Bili smo na Filipsovom ranËu.
{127848}{127904}Barter je mrtav.|Mintonu je slomljeno rame,
{127907}{127971}a »ester je bio onesveöÊen.
{127974}{128036}Kaûe da je neka devojka|dovezla medicinska kola.
{128039}{128125}Razgledao ih je|i to je poslednje Ëega se seÊa.
{128128}{128236}Moglo ih je biti tri ili Ëetiri.|Kola su nestala kao i Filips.
{128239}{128355}- Da li je neko video kuda su kola otiöla?|- Nisam mogao da vidim trag. Mrak je.
{128358}{128443}Spens, uzmi pet ljudi|i Ëuvajte severni put.
{128446}{128527}Morton, ti uzmi nekoliko ljudi viöe.|Ostavi nekog blizu juûnog puta.
{128530}{128630}Ostali idite do zapadnog skretanja.|Zaustavite svakog ko dolazi ili odlazi.
{128633}{128720}Ubijte svakog ko pokuöa da proe.|Sad pokret.
{128848}{128939}- Zaöto ovde stajemo?|- Taskarorina devojka.
{128942}{129056}Moûda mogu da vidim kako stvari stoje.|Moûeö li izaÊi na kraj s KeËamom?
{129059}{129159}Ako Ëujeö buku, to g. KeËam umire.
{129422}{129498}Uhvatili ste ga! Drago mi je.
{129539}{129616}Ako ne znaö,|na öpanskom KeËam znaËi svinja.
{129619}{129672}Mnogo toga se desilo noÊas.
{129675}{129781}Doöli su ljudi s Filipsovog ranËa|i ispriËali su öta ste uradili,
{129784}{129848}i öerif je straöno besan.
{129851}{129969}Da li bi hteli da vidite|öta radi kad je besan?
{130036}{130111}Amelita, pokaûi mu.
{130246}{130292}Pogledajte.
{130309}{130416}Samo napred, dobro pogledajte.|To je öerifovo delo.
{130419}{130528}- Zaöto?|- Da me natera da priËam. Da me kazni.
{130531}{130635}To je uradio i onda se smejao.
{130663}{130749}- Jednog dana Êu ga ubiti.|- Ako stigneö pre mene.
{130752}{130809}Jednog dana Êu ga ubiti.
{130839}{130962}Budite paûljivi.|äerif ima mnogo ljudi koji vas traûe.
{130965}{131019}A ostali vas Ëekaju u zatvoru.
{131022}{131130}U maloj smo prednosti.|Mi imamo njihovog gazdu.
{131212}{131275}- MoliÊu se za vas.|- Laku noÊ.
{131332}{131409}Joö ne znaju da imamo KeËama,
{131412}{131484}ali znaju da smo bili kod tebe|i da si s nama,
{131487}{131570}tako da nas verovatno oËekuju.
{131573}{131677}- I dalje hoÊeö da pokuöaö?|- Sa ili bez tebe, pukovniËe.
{131680}{131743}Jasno mi je.
{131839}{131884}Pomeraj se.
{132083}{132146}Bliûimo se zatvoru, g. KeËam.
{132149}{132259}Moja reuma je nezgodna,|i nemoj da mi izazivaö prst.
{132492}{132580}Vi u zatvoru.
{132626}{132690}Recite Hendriksu da izae.
{132886}{132975}Blu Tom,|imamo tvog prijatelj KeËama ovde.
{132978}{133103}A tu je i skraÊena puöka|sa zavezanim okidaËem iza njega.
{133106}{133165}Hteo bi neöto da vam kaûe.
{133168}{133310}Stariji vodniËe, ako zabrljaö neÊeö|doûiveti da vidiö posledice. PriËaj.
{133313}{133409}Ne pucaj, Tome.|Uradi kako on kaûe. Niöta ne pokuöavaj.
{133412}{133469}- Jesi li ga Ëuo?|- »uo sam.
{133472}{133535}Izvedi sve svoje ljude iz zatvora.
{133588}{133638}»uli ste ga. Izaite.
{133901}{133955}Sad svi spustite oruûje.
{133958}{134042}- äta vi kaûete, g. KeËam?|- Uradi to. Za ime Boga, uradi to.
{134045}{134108}U redu, bacajte ih.
{134158}{134270}Svi se lagano miËite|dok ne stignete ispred onog hotela.
{134342}{134386}Hendriks, ti ostani tu.
{134389}{134473}Joö neko je u tom zatvoru, KeËam.
{134476}{134543}Tom, nemoj ni da pomiöljaö.|Ko god da je, vadi ga.
{134578}{134630}U redu, Barni, izai napolje.
{134698}{134773}Baci piötolj i idi tamo sa ostalima.
{135383}{135445}HoÊete li da sjaöete g. Filips?
{135470}{135574}Nadam se da ne okine dok silazim.
{135585}{135662}Silazi, stariji vodniËe. Idemo u zatvor.
{135801}{135885}Ne brinite, g. KeËam, izbaviÊemo vas mi.
{135888}{135991}To je dobra ideja, öerife.|äto ne probaö? Molim te probaj.
{135994}{136090}Ne, Tome, zaboravi.|On hoÊe da neöto pokuöaö. On je lud.
{136093}{136204}U pravu je. Imam joö jedan. Ulazi.
{136306}{136375}BiÊemo ovde dan ili moûda dva.
{136401}{136461}Onda stiûe US konjica.
{136482}{136590}- Trebao sam te ubiti jutros.|- Trebao si da pokuöaö.
{137060}{137133}Jutros nisam mogao reÊi dobro jutro,|ali mi je svakako drago da te vidim.
{137136}{137205}- Kako se oseÊaö?|- Fino. Osim par bolnih rebara.
{137208}{137308}Ja Êu biti ovde s KeËamom|u sluËaju da njegovi pokuöaju neöto.
{137326}{137434}Ti nemoj da brineö, KeËam.|Prvi Êeö da pogineö.
{137462}{137562}- Gde je kapetan Kordona?|- Otiöao je po pomoÊ.
{137565}{137628}Koliko dugo Êemo biti ovde?
{137631}{137694}Dok on ne stigne s konjicom.
{137729}{137784}Ugasi to svetlo.
{138068}{138145}G. Filips,|da li je to jedina melodija koju znaö?
{138148}{138239}Ovu i ne znam, pa je zato i veûbam.
{138374}{138449}PukovniËe, jeste li imali problema|da uete u grad?
{138452}{138532}Ljudi su bili pripravni,|ali mi smo imali KeËama.
{138535}{138606}Mislite li da imaju ljude i na putevima?
{138609}{138656}Hendriks nije glup.
{138659}{138742}äta ako uhvate kapetana|pre nego öto nae pomoÊ?
{138745}{138864}Onda smo u veÊoj nevolji nego|öto smo bili kad smo sve ovo zapoËeli.
{138945}{139025}G. Filips,|ima li öanse da prestanete s tim?
{139070}{139118}Da, staÊu da popijem piÊe.
{139121}{139197}Ako ga ima, ja Êu ti ga doneti.
{139532}{139590}Kuda si ti krenuo?
{140128}{140157}U zatvoru.
{140176}{140281}Ovde doktor Dûouns, zubar.|Mogu li da uem?
{140284}{140326}Pusti ga unutra.
{140456}{140504}Rizikujeö dolazeÊi ovde.
{140507}{140567}Ne baö. Ne osmatraju mesto.
{140570}{140615}Nemoj se na to kladiti.
{140618}{140663}Doneo sam hrane i piva.
{140666}{140749}- Da bi KeËam neöto pregrizao.|- Nema piva za njega, zar ne?
{140752}{140838}Nema ni za tebe, osim ako ne obeÊaö|da viöe neÊeö svirati u tu harfu.
{140841}{140877}PrestaÊu.
{141235}{141291}- Ko je tamo?|- äasta.
{141467}{141572}- äta ti radiö ovde?|- Nisam mogla da Ëekam i ne znam niöta.
{141575}{141651}Uzela sam konja od g. Prajora.|Niko me nije video.
{141668}{141704}Hej, vi u zatvoru.
{141937}{142003}- äta hoÊeö?|- Imam poruku.
{142006}{142069}Ne ûelim da budem ustreljen|dok je isporuËujem.
{142072}{142110}Evo je.
{142184}{142239}Vidi öta je.
{142745}{142804}- Imaju Francuza.|- Da li je u redu?
{142807}{142865}OËigledno.|HoÊe da ga razmene za KeËama.
{142868}{142953}- Dakle nema vojske.|- Gde hoÊe da ih razmenimo?
{142956}{143047}Ima jedan ambar pored potoka|na drugoj strani grada.
{143050}{143100}Znam gde je.
{143103}{143191}BiÊe u ambaru s Francuzem sat|vremena po izlasku sunca.
{143205}{143280}- Mi treba da odvedemo KeËama.|- Je li to sve?
{143283}{143378}- To je sve.|- äta Êe da rade posle razmene?
{143381}{143473}Njih ima viöe od nas.|äta misliö da Êe da rade?
{143476}{143592}- äta Êemo da radimo, pukovniËe?|- Izgleda da nemamo izbora.
{143595}{143671}Ti öto si doneo poruku, jesi li tamo?
{143674}{143707}Ovde sam.
{143710}{143774}Reci Hendriksu da Êemo biti tamo.
{143777}{143869}I ako sretnemo nekoga na putu do tamo,
{143872}{143917}izgubiÊe gazdu.
{143920}{143966}ReÊi Êu mu.
{144120}{144164}Zna li neko koliko je sati?
{144225}{144278}Dva sata do izlaska sunca.
{144309}{144355}Ima li neöto da ja mogu da uradim?
{144361}{144444}Mogao bi da ponese|papire koje je KeËam potpisao,
{144447}{144513}i vrati ih pravim vlasnicima.
{144568}{144651}NeÊe znati da ih je KeËam potpisao|do posle razmene.
{144716}{144767}Hvala vam svima.
{144813}{144868}éelim vam sreÊu.
{144871}{144928}SreÊu, kaûe!
{144931}{145030}Treba nam viöe od sreÊe.|Treba nam Ëudo.
{145033}{145129}äta ti kaûeö, vodniËe?|Misliö da Êemo uspeti?
{145487}{145568}Poöto ti ne ûeliö to da kaûeö,|mogu li onda ja?
{145571}{145611}Vreme je.
{145676}{145738}U redu, dovedi ga.
{145773}{145899}Bolje saËekaj Ëetiri, pet minuta kad|odemo, onda odjuri do tvojih prijatelja.
{145902}{145956}Ako izgubimo, brzo se izgubi iz grada.
{145995}{146095}- HoÊu samo da ti kaûem...|- VideÊemo se.
{146170}{146276}Bolje da skineö taj osmeh s lica,|ili Êu ja to da uradim.
{146671}{146722}SaËekajte malo.
{147118}{147203}Ostanite na ovoj strani grada|i ostaÊete Ëitavi.
{148709}{148740}Pazi.
{148743}{148845}U redu je, pukovniËe Meknali,|ovo su prijatelji.
{148894}{148990}- äta vi radite ovde?|- Doöli su da pomognu.
{148997}{149117}NeÊe biti od koristi|ako nisu stvarno dobri.
{149120}{149179}- Doca vam je dao tapije, zar ne?|- Svakako.
{149182}{149238}Ali öta nam one vrede ako vi izgubite?
{149241}{149361}- Bolje pazite u öta se meöate?|- Tebe smo obeÊali da razmenimo,
{149364}{149456}ali nismo rekli u kakvom stanju Êeö biti.
{149490}{149580}- Zna li neko od vas da puca?|- Bajd je dobar strelac.
{149583}{149685}Njega se seÊaö. Njegov zavoj na|kapetanovoj nozi ti je zadao glavobolju.
{149688}{149754}- SeÊaö li se, pukovniËe?|- SeÊam se.
{149757}{149867}- Svi mi smo bili u ratu, pukovniËe?|- U redu, s nama ste.
{149879}{149951}Neka neko pripazi na zadnja vrata.
{150440}{150541}Imaö viöe pomoÊi nego öto misliö,|pukovniËe. Ljudi su tamo iza zida.
{150544}{150605}Mogu da iznenade one momke|i zaobiu ih.
{150608}{150713}- Bajde, koliko je dubok potok?|- Menja se. Tri, Ëetiri... öest stopa.
{150716}{150800}- Da li je dubok kod mosta?|- Trebalo bi.
{150803}{150895}Imam ideju. Moûeö li da rastegneö ovu|razmenu i daö mi malo vremena?
{150898}{150963}- Ne dugo...|- Bajde, daj mi tvoj piötolj.
{150966}{151046}- äta hoÊeö da uradiö?|- Nemam vremena da objasnim.
{151822}{151884}Ja viöe ne mogu da odugovlaËim.
{152055}{152106}äta hoÊeö?
{152117}{152201}- Jesi li spreman?|- Ja sam spreman.
{152204}{152262}Prvo ti pusti KeËama, mi Êemo Kordonu.
{152265}{152322}HoÊu da vidim Kordonu.
{152337}{152389}Izvedite ga.
{152473}{152572}- Zadovoljan?|- Kad god ste spremni.
{153068}{153135}Hej, pukovniËe, stoji tamo gde treba.
{153193}{153251}U redu, KeËam.
{153287}{153364}Sada Êeö polako|da ideö na drugu stranu.
{153367}{153458}- Otpusti opasaË.|- Zaöto?
{153461}{153557}Da bi ti ruke bile zauzete. Sad öetaj.
{153612}{153670}To je dovoljno.
{153727}{153782}Evo vaöeg Ëoveka.
{153796}{153847}Pomeraj se.
{153970}{154037}U redu. Samo polako.
{154588}{154626}Stani gde si.
{154629}{154713}Oko öest piötolja je upereno u tebe,|ne pomeraj se.
{154824}{154913}- Dakle, öerife, öta Êe da bude?|- Ja hoÊu KeËama.
{154925}{155019}I ja ga hoÊu. Tebi nije od koristi.
{155022}{155102}Prepisao je sve tapije|natrag pravim vlasnicima.
{155120}{155232}- ävorc ste, obojica.|- Da li je to istina, KeËam?
{155235}{155272}Ne. Stani malo, Tom.
{155283}{155329}Laûe. Ne pucaj!
{155760}{155821}VraÊaj se unutra, budalo.
{155875}{155924}Polako.
{155927}{155990}Prestani da vriötiö. Nisi povreen.
{156037}{156085}Krateû je beskoristan.
{156088}{156183}Ne smeta ti da pucam, a?|Bolje se oseÊam.
{157024}{157132}Ima ih mnogo viöe od trojice.|BiÊe ih teöko nadjaËati.
{157159}{157247}- Pit, imaö li dinamita?|- Mogu da ga nabavim.
{157250}{157329}- Ima li svrhe koristiti ga za bar?|- Ako ga ubacim pravo kroz prozor.
{157332}{157410}- Povedi Grega da te pokriva.|- Hajde Greg.
{157581}{157676}Vidiö li one momke?|Pokuöavaju da nas zaobiu.
{157988}{158050}- PukovniËe...|- Video sam ga.
{158192}{158238}Nai öibicu.
{158538}{158568}Pazite!
{158731}{158814}Taj dinamit nam je mogao biti u krilima.
{158817}{158872}Drago mi je öto sam te poveo.
{158926}{158989}To bi trebalo da ih zadrûi.
{159314}{159364}Pazi iza tebe. Beûimo odavde.
{159440}{159503}- Kuda ste krenuli?|- Pobeeni smo, öerife.
{159506}{159603}VraÊajte se nazad, vi bedni...|Dolazite ovamo.
{160194}{160269}- Kuda si krenuo?|- Za Hendriksom.
{160428}{160538}- Beûe, pukovniËe.|- Hendriks neÊe daleko.
{160742}{160794}Drago ti je öto si me poveo?
{160797}{160872}Raöirite se. Ovo joö nije gotovo.
{161055}{161134}Okreni se, öerife.|HoÊu da vidiö ko Êe da te ubije.
{161829}{161886}Povratili ste svoj grad.
{162368}{162427}Ja... Rekla sam ti da Êu da ga ubijem.
{162441}{162540}- Rekla sam ti, zar ne?|- Rekla si mi.
{162543}{162658}Imala sam pravo na to.|Ceo ûivot Êu da nosim ovaj oûiljak.
{162684}{162809}I kad god ga pogledam, ûelim da znam|da sam imala pravo da ga ubijem.
{162812}{162888}Da ga ti nisi ubila,|neko drugi bi to uradio.
{162908}{162970}Da li bi mogla da me povezeö?
{162973}{163076}G. Meknali,|pored vas se Ëovek oseÊa tako...
{163079}{163144}Molim te, nemoj da kaûeö udobno.
{164128}{164406}www.statserb.sr.gov.yu
{164431}{165931}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3zu65|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
