{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1190}{1310}UMRI MIäKI SA OSVETOM|by SLAY
{2772}{2844}Alane, bombaöki odred,|specijalna odeljenja...
{2848}{2897}...drûavna policija i FBI.
{2901}{2981}PoruËniËe Dûergensen, ti Palmere|idi u hitnu bolnice Sveti Dûon...
{2985}{3049}...u sluËaju da imamo|povreene na ulici.
{3053}{3105}Krejmer, nai gradskog inûenjera.
{3109}{3163}Moram da podnesem izveötaj o öteti.|Veoma vaûno.
{3167}{3239}Bonvit TeIer. Ko bi uopöte ûeleo|da raznese|prodavnicu obuÊe?
{3243}{3289}Jesi li ikad video ûenu da|propusti rasprodaju obuÊe?
{3293}{3345}Koni, poËni sa svedocima.
{3349}{3433}Riki, ti i Dûo potrudite se da|uniformisani naprave kordon tamo...
{3437}{3512}...i ne dozvolite prokletoj TV da ue.
{3516}{3559}Inspektore, telefon.|- Ne sada.
{3563}{3635}Bensone, saobraÊaj!|Oslobodi Petu aveniju do tri...
{3639}{3678}...ili Êemo imati sobraÊajnu|guûvu iz pakla.
{3682}{3808}Voltere, mislim da treba da uzmeö ovo.
{3855}{3903}Glavna jedinica inspektor Kob.
{3907}{3974}Glupi Sajmon reËe pekaru dok|je iöao na vaöar...
{3978}{4022}...daj mi tvoje pite, 
{4026}{4086}ili Êu ti odseÊi glavu.
{4090}{4171}Bonvit je bio samo da vam|skrenem paûnju.
{4175}{4254}Ima li detektiva po imenu|Meklejn tamo?
{4258}{4378}On je suspendovan.|- Ne Voltere. Nije. Ne danas.
{4382}{4439}Ko je to?|- Zovi me Sajmon.
{4443}{4518}äta hoÊeö?|- HoÊu da igram jednu igru.
{4522}{4622}Kakvu igru?|- Sajmon kaûe.
{4626}{4725}Sajmon Êe da kaûe Meklejnu|öta da uradi...
{4729}{4770}...i poruËnik Meklejn Êe to uraditi.
{4774}{4853}Neposluönost rezultuje kaznom.
{4857}{4893}Kakvom kaznom?
{4897}{4983}Joö jedno veliko bum na veoma|javnom mestu...
{5038}{5109}äta hoÊeö da Meklejn uradi?
{5113}{5178}Sajmon kaûe da poruËnik Meklejn...
{5182}{5239}...ode do ugla 138 ulice i Amsterdama...
{5243}{5310}...koji je u Harlemu, ako se ne varam.
{5314}{5383}Kovalski! Lamberte! Jel' znate gde|da naete Meklejna?
{5387}{5449}Sumnjam da Êe te ga naÊi u crkvi.
{5453}{5573}Bolje pronaite pod kojim kamenom|se nalazi i dovucite ga ovamo.
{6115}{6161}Dûone.|- Hvala. Daj mi joö malo.
{6214}{6286}Isuse Dûone, izgledaö kao govno.
{6388}{6449}Gde smo stali s tim izveötajem?
{6453}{6539}Imamo tri ubistva u Crvenoj kuki|u proöle dve noÊi.
{6543}{6647}Stavi Majnera na to. I Dûenetija. ZvaÊe iz|gradonaËelnikove kancelarije pre kraja dana.
{6651}{6734}SledeÊe, 14 ubretarskih kamiona|ukradeno iz dvoriöta u Stejton Ajlendu.
{6738}{6887}14, Isuse! Jel' to osnivaju|graevinsku kompaniju?
{6891}{6977}To je Dûonova gazdarica, hoÊe da|oËisti njegov stan.
{6981}{7040}Prevara sa osiguranjem.
{7044}{7117}Kamioni su najverovatnije|veÊ u Kaliforniji.
{7121}{7222}UgovaraË podeli pare sa lopovom. Imali smo to u|Dûersiju pre nekoliko godina Dûo, seÊaö li se?
{7226}{7305}Vidi öta Keli moûe|da uradi s tim.
{7310}{7375}Hej, koji su bili|brojevi lutrije sinoÊ?
{7380}{7417}4-6-6-7.
{7458}{7537}Joö uvek igraö|na svoju znaËku, Riki?
{7540}{7619}Da. 6-9-9-1 svake nedelje.
{7622}{7669}6-9-9-1. SreÊan broj.
{7673}{7730}Pola policajaca ovde|igra na svoju znaËku.
{7750}{7889}Kako su deca, Dûone?|- Dobro.
{7892}{7949}Jesi li priËao sa Holi?
{8020}{8054}Ne, nisam priËao sa Holi.
{8058}{8108}Stiûemo, Inspektore.
{8143}{8201}Je li to vruÊina ili|sam ja preplaöen na smrt?
{8205}{8261}Proveri da li je piötolj priËvröÊen?
{8265}{8311}Da. Dobro je.
{8494}{8568}Ti si prva ûena posle Holi da me je|videla kako radim ovo.
{8572}{8729}PoËastvovana sam.|- Da, i ona je bila.
{8758}{8840}I...gde Êe biti podröka?
{8912}{8990}PovuÊi Êemo se do 128 ulice.
{9052}{9126}äta? Deset blokova? Zezate me?
{9130}{9222}Oh, ËoveËe. To je stvarno super.|Voltere, o Ëemu se ovde radi?
{9226}{9281}Ako ne uradimo to öto kaûe,|razneÊe joö jedno mesto.
{9285}{9320}Zaöto ja?
{9324}{9416}Nemam pojma. Samo je rekao da|to moraö da budeö ti.
{9451}{9541}Lepo je biti potreban.|- Iskreno, Dûone...
{9545}{9609}äto se ne ostaviö toga o Holi?
{9643}{9744}Ti i Sajmon ste mi upropastili|odliËan mamurluk. - Dobro.
{10062}{10136}VratiÊemo se da te pokupimo|za 15 minuta.
{10140}{10217}Ne ûurite. OËekujem da budem|mrtav za 4. - Idemo, Bili!
{11504}{11574}Hej, ujaËe! Doi da vidiö ovo!
{11618}{11710}Devet i deset je, zaöto niste u ökoli?|- Toni hoÊe ovo da proda.
{11714}{11765}Toni. Onaj tip bez vrata koga|zovu loö T?
{11769}{11846}Naöao ga je u kontejneru.
{11850}{11894}Ako nastavi da krade, njega|Êe da nau u kontejneru.
{11898}{11969}Nije ukrao. Njegov ujak mu je to dao.
{11973}{12046}Hm. Dodaj mi te novine.
{12113}{12206}Ne dozvoli da te ljudi iskoriöÊavaju. TrËite|kroz ceo grad sa ukradenom imovinom.
{12210}{12301}Ako vas uhvate, upaöÊete u nevolju|dok on bude poricao sve.
{12305}{12394}HoÊeö da nam kaûeö da vratimo|to Toniju?
{12398}{12478}Ne. Ja Êu to vratiti Toniju|sa porukom.
{12506}{12545}Sad, gde idete?
{12549}{12579}U ökolu.|- Zaöto?
{12639}{12693}Da bi smo otiöli na fakultet.|- A zaöto je to vaûno?
{12729}{12768}Poötovanje. A ko su loöi momci?
{12772}{12836}Momci koji prodaju drogu.|- Momci koji imaju oruûje.
{12840}{12884}Ko su dobri momci?|- Mi smo dobri momci.
{12938}{12993}Pa, ko Êe vam pomoÊi? - Sami|sebi Êemo pomoÊi.
{13059}{13121}Tako je.
{13125}{13208}Hajde odavde. Idite u ökolu.
{13299}{13355}UjaËe, doi da vidiö ovo.|- äta?
{13358}{13432}Belac stoji na ulici.|- Video sam takvog.
{13436}{13476}Ne ovakvog.
{13645}{13708}{Y:i}JA MRZIM »AMUGE
{13713}{13844}Zovi 911. Reci policiji da doe|ovamo brzo. Neko Êe biti uskoro ubijen.
{13849}{13895}I vucite dupeta u ökolu,|jeste li Ëuli?
{13898}{13951}Da. U redu.
{14562}{14648}Dobro jutro.|- Dobro jutro.
{14652}{14734}Imate li prijatan dan, gospodine?|OseÊate li se dobro?
{14738}{14832}Ne bih neöto liËno,|ali belac koji stoji u Harlemu, 
{14836}{14893}noseÊi znak, "Ja mrzim Ëamuge", 
{14897}{15012}ili ima liËne probleme|ili mu nisu sve ovce na broju.
{15016}{15077}Hej, tebi se obraÊam!
{15081}{15145}Imaö deset sekundi pre nego|öto te oni momci vide.
{15149}{15218}I kad te vide, ubiÊe te.|Razumeö li?
{15222}{15312}ImaÊeö vrlo ruûan dan.
{15316}{15370}Da, priËaj mi o tome.
{15374}{15423}Ovo je stvar policije, za vaöu sigurnost...
{15427}{15501}Prokleto si u pravu da je stvar policije.|Predlaûem ti da se sakrijeö u moju radnju, 
{15505}{15542}pre nego öto policija doe.
{15546}{15596}äta jebote?!
{15636}{15700}O sranje.
{15804}{15904}Sluöajte, ja sam policajac na sluËaju. - äta?|- Neko je razneo radnju Bonvit Telera.
{15966}{16096}Isti seronja je rekao da moram da|uradim ovo, ili Êe da raznese neöto drugo.
{16118}{16154}Sranje, sranje, sranje.|- Imam piötolj. - Oni imaju deset.
{16158}{16264}Idite preko puta ulice. - PoËni da se|ludiraö, kao u crtaÊima, kao u Belvjuu.
{16268}{16375}Hej, Zevse, jel ovo tvoj prijatelj?|- Izgleda li kao moj prijatelj?
{16379}{16475}Mislim da je tip pobegao iz neke bolnice|znate, kao Belvju?
{16579}{16677}Ja sam glas mog boga. I moj bog...
{16681}{16745}Rekao sam bibliotekarki da imam|veliku glavobolju...
{16749}{16787}...ali mi nije verovala.
{16791}{16902}Stvarno imam uûasnu glavobolju...Imam|uûasnu glavobolju! Moja glava ne...
{16950}{16997}UÊuti jebote! Napravio si veliku|greöku. Njegovu bulju. Seci to sranje.
{17135}{17212}Momci, momci!|- Momak prirode mrzi crnce.
{17216}{17243}äta Êemo da uradimo?|Napravio si veliku greöku.
{17442}{17512}U vis, u vis, u vis!|- Oh, sranje! - Nazad! Nazad!
{17516}{17596}Hej, Zevse. äta tripujeö?|- Nazad jebote! Sad!
{17600}{17686}Hajde, ËoveËe, ustaj.|Beûi odavde!
{17723}{17771}Zaustavi taksi!|Zaustavi prokleti taksi!
{17775}{17829}Ne pucaj!|- Ustaj! Hajde, ustaj!
{17833}{17942}Nazad. Ne öalim se! Ne ûelim to.|Ali uradiÊu. Znate da Êu uraditi to.
{17946}{18020}Hajde! Hajde! Beûi odavde!|- Vozi! Vozi!
{18042}{18180}Ne staj. Samo vozi. Vozi kroz crveno!
{18184}{18228}Evo, ËoveËe. To je sve öto imam|- Skloni taj novac. Niko te ne pljaËka.
{18232}{18276}Vozi kroz sva svetla. Vozi.
{18280}{18352}Vaûi öefe.
{18379}{18423}Oh, ËoveËe! Do avola. - Jel ta|posekotina|duboka? - Otkud ja znam?
{18427}{18539}Samo pritisni dobro.|- Do avola! Oh, jebote!
{18543}{18629}Isus, jel tako? Dûon Meklejn.|Duûan sam ti.
{18633}{18703}Prokleto si u pravu! Znaö li öta|rade s mojom radnjom sada?
{18707}{18776}Kuliraj Isuse. - Kuliraj? Pokuöavaö da|govoriö crnaËki? PriËaj kao belac.
{18780}{18809}Isuse, ûao mi je...
{18813}{18863}Zaöto me stalno zoveö Isuse? Zar ti|liËim na portorikanca?
{18867}{18898}Momak tamo te je nazvao Isus.
{18902}{19000}Ne Isus. Rekao je, "Hej, Zevse."|Moje ime je Zevs.
{19004}{19075}Zevs?|- Da otac Apola, planina Olimp...
{19079}{19125}...ne zezaj se samnom... 
{19129}{19207}...ili Êu ti zabiti munju posred bulje!|Zevs! Imaö li problema s tim?
{19211}{19333}Ne. Nemam problema s tim.|U centar. Policijska stanica.
{19337}{19386}Oh, to je stvarno super.
{19491}{19566}Dosijee svih prestupnika|koji su nedavno puöteni...
{19569}{19605}...i bilo koga koje je|uhapsio sa strane.
{19667}{19705}»ist primer megalomanijaka.
{19709}{19773}To je patoloöko stanje|u kojem fantazije o kontroli...
{19778}{19849}...predominiraju.|On hoÊe kontrolu nad njim...
{19854}{19909}...nad njegovim postupcima, njegovim|mislima, Ëak i oseÊanjima.
{19913}{19954}ZvuËi kao da imaö tajnog oboûavaoca.
{19960}{20043}Da. Moûda mi poöalje cveÊe.|- Svi znaju da voliö ömokljane.
{20048}{20143}Ne takva vrsta oseÊanja. Ovaj|momak je gadan.
{20147}{20213}Kako je to? - Niöta öto|tuöiranje ne bi moglo da popravi.
{20218}{20264}Pivo se obiËno pije na usta, Dûone.
{20268}{20357}Daj mi samo aspirin, hoÊeö li?|- Dobro. Drûi ovo ovde.
{20387}{20469}Ovo je Fred äiler, i on je...|- Psihijatar. Da, znam to.
{20473}{20556}Da. SuoËavamo se sa megalomanijakom...
{20560}{20600}...sa moguÊom paranoidnom|öizofrenijom.
{20604}{20704}PreskoËite do objaönjenja|kakve uopöte veze ovo ima samnom.
{20708}{20803}Ne znam. Ali znam da eksplicitno|ima veze s vama.
{20807}{20887}Ovaj Ëovek hoÊe da vas mlati dok|ne padnete.
{20891}{20935}HoÊe da igrate uz njegovu muziku|onda...
{20939}{21065}...obuËem haljinu i da me jebe?|- Hteo sam da kaûem ubije.
{21069}{21137}On ima previöe besa u sebi.
{21141}{21222}I moglo bi da se manifestuje fiziËki|ako je pod stresom.
{21226}{21279}Neko koga je uhapsio, neko|koga je naljutio?
{21283}{21349}To bi mogla da bude prokleto|dugaËka lista. - Jebi se, Dûo.
{21353}{21406}Ovi ljudi ne vole da rade anonimno.
{21410}{21466}Oni ûele da vi znate ko to radi.
{21470}{21574}To ime Sajmon, verovatno nije alijas.|Verovatno je Sajmon ili neka varijacija.
{21578}{21674}Sajmon, Robert I. Uhapöen 86-te.|Iznuivanje. Kidnapovanje. 10 do 15.
{21678}{21762}Odsluûio 7 godina zbog dobrog vladanja.|Puöten zbog radne dozvole pre dva meseca.
{21766}{21811}Proveri!|- Hvala, Rik.
{21815}{21896}Bob Sajmon je bio propali bankar|koji je kidnapovao partnerovu Êerku.
{21900}{21968}On je kreten, ne psihopata.|Tip koga traûimo je potpuno lud.
{21972}{22040}Ludak koji zna dosta o bombama.
{22044}{22109}Ovo smo naöli na deËjem igraliötu.|Profesionalno.
{22113}{22144}Veoma kul stvar.
{22148}{22186}Znate veÊ...bum.
{22190}{22236}Misliö da moûeö tako da je|mlataraö okolo, »arli?
{22240}{22283}Nije pomeöana.|Ne moûe nam niöta.
{22287}{22348}Ova stvara je veoma opasna.|To je binarna teËnost.
{22352}{22469}äta?|- Kao epoksid.|Dve teËnosti.
{22473}{22535}Svaka za sebe...
{22569}{22649}...nemate niöta. Ali ako ih pomeöate...|Riki. Pomeri se malo.
{23062}{23123}»arli, nosiÊeö tu stolicu u bulji!
{23127}{23205}Gospode boûe, »arli!|- Kao öto sam rekao, veoma kul stvar.
{23209}{23266}Sa ovakvim paketom dobijate upozorenje.
{23270}{23364}Bomba mora sama da se naoruûa. VideÊete|kako se crvena teËnost uliva u bezbojnu...
{23368}{23425}...pre nego öto se detonira.
{23429}{23457}Koliko pre?
{23461}{23507}Deset sekundi, dve minute.
{23511}{23639}Bilo kad. Ali kad se pomeöaju|budite negde drugde.
{23643}{23736}Ova stvar mora da je priliËno retka.|Naite da li neka od ovih nedostaje negde.
{23740}{23813}Kraa u Livermorovoj|laboratoriji preko vikenda.
{23817}{23869}Imaju li dovoljno da|naprave joö jednu, Dûo?
{23873}{23948}Oko 2000 funti.|- Toga?
{23952}{24032}Mehanizam za detoniranje moûe|biti bilo öta radio, elektriËno.
{24036}{24093}Moûete Ëak i pejdûerom da pozovete.
{24097}{24149}Inspektore, to je on!
{24153}{24228}Bomba ima dupli povratni mehanizam.|Prljav mali trik koriöÊen Libanu.
{24231}{24359}»arli. »arli. - äta?|- HoÊeö li da ukljuËiö lokator?
{24570}{24641}Sajmone. - Nosio je tablu|iöao je ulicom i preûiveo.
{24645}{24674}Hauptman VoIter.
{24678}{24772}Gde su moji golupËiÊi sada?|- GolupËiÊi?
{24776}{24861}Imao sa dva goluba, vesela i bela|odleteöe mi tog dana.
{24865}{24922}Zaöto su mi odleteli?|Ne moûete da kaûete.
{24926}{24982}Ne znate.|- Mislite na Meklejna?
{24986}{25040}Ne, mislim na deda mraza.
{25101}{25129}Da ovde sam.
{25134}{25205}Ah, tu si ipak.|A tvoj prijatelj?
{25209}{25352}Hajdete. Trebate nam u drugoj sobi.|Idemo. Hajde. - Traûe vas. Idite.
{25357}{25425}Da, i on je ovde.|- Mogu li da priËam s njim?
{25479}{25528}Da li je samariÊanin od mahagonije tu?
{25533}{25571}Imaö li problema sa mahagonijom?
{25574}{25652}Ne, moj jedini problem je öto|sam imao poteökoÊa...
{25656}{25697}...spremajuÊi igru za Meklejna.
{25702}{25755}Umeöao si se u dobro napravljen plan.
{25759}{25856}Moûeö da nabijeö tvoj dobro napravljen|plan u tvoje dobro napravljeno dupe.
{25914}{25948}To nije bilo pametno.
{25953}{26044}éivoti su u pitanju ovde.|- Nije bilo dovoljno vremena, inspektore.
{26048}{26100}Bolje se nadaj da Êe ponovo da pozove.
{26103}{26138}HoÊe.
{26191}{26264}Riki, reci tim ljudima da uÊute tamo!
{26268}{26337}Tiöe malo tamo!
{26533}{26614}Sajmone.|Nije govorio u ime svih nas.
{26618}{26696}To nije bilo prijatno.|Ne dozvolite da se to opet ponovi.
{26700}{26776}Pa, koje je tvoje ime, deËko?|- Ne zovi me deËko.
{26780}{26859}Izvini. To je bio slab pokuöaj da|budem zabavan.
{26863}{26984}Hteo sam da te poöaljem kuÊi|sa ukorom ali sada mislim...
{26988}{27036}Imamo ga. To je telefonska|govornica...u Oslu.
{27088}{27152}Sad kaûu da je u Suarezu u Meksiku.
{27155}{27240}Australija. Zaboravi. Skrembluje|sistem. Ne znaju gde je.
{27244}{27339}Zabavljamo se sa telefonskom|kompanijom, zar ne?
{27343}{27416}Sajmon kaûe da Meklejn i|SamariÊanin odu do metro stanice
{27420}{27456}u 72-goj i Brodveja.
{27460}{27538}ZvaÊu vas za 15 minuta na|telefonsku govornicu ispred stanice.
{27542}{27630}Bez policije. Ako se ne odazovete|smatraÊu to neposluönoöÊu.
{27634}{27727}Da li me razumeö, Dûone?|- O, da razumem te.
{27731}{27826}Razumem da si jebeni kreten|koji voli deËje igre.
{27830}{27874}Teöko.|- Teöko?
{27878}{27956}Onda ko si ti, neko koga sam|uhapsio? äta si uradio?
{27960}{28060}krao u prodavnici, oduzimao taöne|transvestit öta?
{28064}{28132}Ne moûeö me uhvatiti|ako bih ukrao tvoju stolicu
{28136}{28166}sa tobom u njoj.
{28170}{28230}Moju stolicu samnom u njoj?
{28234}{28298}Da te pitam neöto krele...
{28301}{28359}...zaöto pokuöavaö da me ubijeö?
{28363}{28408}Dûone, Dûone, smiri se.
{28412}{28511}Zaöto ne doeö ovamo|da razjasnimo ovo kao ljudi?
{28515}{28601}Da sam hteo da te ubijem,|veÊ bi bio mrtav.
{28605}{28691}Sajmone, ovde inspektor Kob.|Poötujem vaöa oseÊanja prema Meklejnu...
{28695}{28759}...ali verujte mi kreten nije vredan toga.
{28762}{28816}Nagazio je na ûuljeve mnogih|ljudi u ovom odeljenju...
{28820}{28880}...sledeÊeg meseca biÊe|radnik obezbeenja.
{28884}{28979}Njegova ûena ne ûeli|niöta da ima s njim...
{28983}{29012}...i na dva koraka je|da postane alkoholiËar.
{29016}{29076}Jedan korak. Jedan korak.
{29080}{29125}Sad, sluöajte me.
{29129}{29218}ZvuËite kao vrlo pametan Ëovek|äta ûelite?
{29222}{29340}Da li vi to priËate o novcu?|- Pa, bilo öta, bilo öta.
{29344}{29406}Meklejn je muva u wc öolji.
{29410}{29492}äta je potrebno da ga zaboravite|i da ûivite sreÊno?
{29496}{29575}Novac je sranje za mene|Ne bih se odrekao Meklejna...
{29579}{29646}za svo zlato u vaöem Fort Noksu.
{29650}{29714}72-ga ulica, metro, telefonska|govornica 15 minuta.
{29718}{29774}Meklejn i samariÊanin.
{29778}{29840}Ako ste dovoljno lukavi|naÊi Êe te torbu.
{29844}{29913}Tako da znate öta podrazumevam|pod kaznom.
{29984}{30035}Pa, hvala ti za tvoj glas podröke.
{30039}{30110}Mislio sam da je vredelo pokuöati.|Ovaj Ëovek je totalni manijak.
{30114}{30227}Nije mogao da bude jasniji. Dao vam je|nagoveötaje za njegov identitet...
{30231}{30300}govorio je nemaËki...|Rekao je "vaö" Fort Noks...
{30304}{30346}i zamucao je kad ga je|Meklejn pritisnuo.
{30350}{30400}Stvarno verujete da ovaj|Ëovek ne moûe biti podmiÊen?
{30404}{30504}Sama pomisao na novac bi ga|samo joö viöe razbesnela.
{30696}{30778}äta je to?|- Tvoja znaËka.
{30782}{30815}Traûiö da opet budem policajac?
{30819}{30890}Riki, daj mu piötolj|- Nisi odgovorio na moje pitanje.
{30894}{30982}Hej! Nisi odgovorio na moje|pitanje, Votlere.
{30987}{31049}Jeste li gotovi, poruËniËe?
{31086}{31164}Vas dvojica bolje krenite da bi|stigli do 72-ge ulice na vreme.
{31168}{31228}Dûo idu sa pojaËanjem.|- U redu.
{31233}{31297}Ja ne idem nikuda.
{31299}{31340}Sajmon kaûe da moraö da ideö.
{31345}{31445}NeÊu da skaËem kroz|obruËe za nekog psihopatu.
{31450}{31474}To je belac sa problemima belaca.
{31479}{31526}Zovite me kada pree 110-tu ulicu.
{31550}{31630}Hej. Zaöto si spasao moju bulju?|- Nisam.
{31633}{31685}SpreËio sam da beli policajac|bude ubijen u Harlemu.
{31690}{31743}Ako jedan policajac bude ubijen danas,|sutra Êemo ih imati hiljadu.
{31746}{31842}Svi sa nervoznim prstima|na obaraËu, razumeö li?
{31896}{31934}Vratite ga nazad.
{31992}{32047}Gde si naöao tu bombu?|- U kineskoj Ëetvrti.
{32050}{32095}Sranje!
{32100}{32168}Hej kolega! »ekaj.
{32172}{32268}Hej, nisam tvoj kolega. Nisam tvoj|komöija tvoj brat, ili tvoj drug.
{32272}{32368}Ja sam stranac za tebe.|- U redu stranËe.
{32393}{32471}Znaö li gde je park u|115-toj ulici i Svetog Nikole?
{32531}{32562}Da, to je u Harlemu.
{32566}{32619}äta misliö gde su naöli tu bombu?
{32623}{32751}Sluöaj, ovaj Ëovek ne mari za boju koûe|Ëak iako ti misliö suprotno.
{32806}{32842}äta ja to radim?
{32846}{32896}Kuliraj, Stvari bi mogle da budu gore.
{32900}{32953}Lepo sam se gojio dok sam bio|suspendovan, puöio cigare...
{32957}{33006}i gledao kapetana Kengura. Hajde.
{33275}{33328}Stigli su do telefona|ali ima problema.
{33332}{33430}Koliki problem?|- O oko 300 funti.
{33464}{33512}Izvinite gospoo, treba nam ovaj|telefon zbog sluûbenih stvari.
{33516}{33538}Molim vas.
{33542}{33586}Ja sam policajac.|Treba mi taj telefon.
{33590}{33640}Skloni se s telefona!|Policijski posao!
{33672}{33700}Pa, nikad nisam...|Mogu da se naviknem na ovo. 
{33704}{33768}Moûete da naete telefon preko|puta ulice.
{33771}{33866}Da razjasnimo neöto. Ja sam jedini|ovde na zadatku Ne radi to sranje viöe.
{33870}{33950}Da razjasnimo joö neöto. Potreban sam ti viöe|nego ti meni. Ako ti se ne svia odlazim.
{34245}{34303}Dobro. Trebaö mi.
{34433}{34511}Potreban si mi viöe nego|ja tebi.
{34624}{34691}Halo. Svaka ptica svom jatu...|takoe svinje i prasiÊi...
{34695}{34767}Pacovi i miöevi imaju njihovu öansu|kao öto ja imam svoju.
{34771}{34816}Lepo. Rimuje se.
{34820}{34881}Zaöto je telefon bio zauzet?
{34885}{34955}Zvali smo liniju za ljude u krizi.|- Savetujem vas da budete ozbiljniji.
{34959}{35003}To je javni telefon. äta da ti kaûem?
{35007}{35105}Jednostavno kaûi da je bila debela ûena na|telefonu i trebalo vam je minut da je otkaËite.
{35141}{35275}Sad, Dûone, postavljena je priliËna koliËina|eksploziva u kanti za otpatke pored tebe.
{35319}{35376}Pokuöaj da beûiö,|i eksplodiraÊe.
{35380}{35431}Niko neÊe da beûi,|ali imam stotine ljudi ovde.
{35435}{35524}U tome je stvar.|Sad, da li imam tvoju paûnju?
{35528}{35589}Dok sam iöao ko Svetog Ive,|sreo sam Ëoveka...
{35593}{35655}sa 7 ûena, svaka ûena je imala 7 vreÊa....
{35659}{35719}Svaka vreÊa je imala 7 maËaka,|svaka maËka je imala 7 maËiÊa...
{35723}{35760}MaËiÊi, maËke, vreÊe i ûene, koliko|njih je iölo kod Svetog Ive?
{35764}{35851}Moj broj je 555...|- Nisam Ëuo! Ponovi!
{35855}{35953}Nema öanse. Moj broj telefona je|555 i odgovor.
{35957}{36011}Zovite me za 30 sekundi|ili umrite.
{36083}{36156}7 momaka sa 7 ûena...|- UÊuti Meklejn. Dobar sam u ovome.
{36160}{36284}Sedam momaka... UÊuti rekao je 7 ûena|sa 7 vreÊa 7 puta 7 je 49. Reci mi ostalo.
{36288}{36343}VreÊa sa 7...vreÊa sa 7...
{36347}{36402}Zar nisi sluöao? äta je s tobom?
{36406}{36472}Loö mamurluk kao prvo!
{36476}{36528}Dobro. 7 ûena puta 7 je 49. Sa 7 maËaka...
{36532}{36576}7 puta 49 je 343, zar ne?
{36580}{36630}Jel me to pitaö ili mi kaûeö?|- Kaûem ti.
{36634}{36715}343 puta 7 je 2401...
{36719}{36771}2.401. To si i ti dobio?
{36775}{36830}Da. Jel tako 2401?
{36834}{36905}Tako je, okreni 555-2401.
{36942}{37011}Ne, Ëekaj! To je trik.
{37015}{37077}Zaboravio sam na Ëoveka. - Kog Ëoveka?|Jebeö Ëoveka, imamo 10 sekundi.
{37081}{37132}Rekao je koliko njih|je iölo kod Svetog Ive.
{37136}{37219}Zagonetka poËinje...|Dok sam iöao kod Svetog Ive.
{37222}{37258}éene ne idu nikuda.
{37263}{37357}äta rade?|- Otkud ja do avola znam?
{37362}{37444}Ko onda ide ko Svetog Ive?|- Samo Ëovek.
{37448}{37495}Samo jedan Ëovek?|- Odgovor je 1.
{37498}{37561}Kako da okrenem 1?|- 555-0001.
{37565}{37632}Samo jedan Ëovek ide?
{37636}{37691}Halo, Dûone. Prosto ko pasulj.|Daj nam neöto teûe sledeÊi put.
{37696}{37760}Ali zakasnili ste 10 sekundi.|- Ne! Odgovor je 1!
{37762}{37825}Bomba je u kanti za otpatke!|Dole! Bomba!
{37828}{37862}Dobro doöao u Nju Jork. Hajde.|Ustani.
{38881}{38994}Nisam rekao Sajmon kaûe.|Sada je 9 i 50, Dûone.
{38998}{39079}Voz broj 3 upravo stiûe.
{39083}{39163}Ostavio sam neöto provokativno u tom|vozu Dûone.
{39167}{39197}Sajmon kaûe...
{39201}{39304}Stignite do telefona pored kioska|na stanici u Vol Stritu...
{39308}{39385}do 10 i 20 ili Êe voz broj 3|i njegovi putnici ispariti.
{39389}{39473}Koristite li bilo koji prevoz|sem civilnog razneÊu voz.
{39477}{39538}Pokuöate li da evakuirate voz,|razneÊu ga.
{39542}{39609}ZvaÊu vas za 30 minuta.
{39641}{39666}Budite tamo.
{39670}{39786}Jebote. 90 blokova za 30 minuta?|Treba nam duplo viöe od toga.
{39790}{39854}Nemamo Ëak ni kola!
{39858}{39915}Hej, gospodine, policija!|Zaplenjujem ova kola...
{39919}{39970}... u sluûbene policijske svrhe.
{40039}{40120}Super. Nekad sam bio taksista.|Najbrûi put juûno je... äta radiö jebote?
{40300}{40322}Hteo si da kaûeö?
{40326}{40458}Rekao sam da sam bio taksista.|Najbrûi put juûno je 9-tom avenijom.
{40462}{40502}Mi izgleda da idemo istoËno.
{40650}{40714}Gde do avola ideö, Meklejn? 9-tom|avenijom je najbrûe juûno!
{40717}{40774}Ne viËi. Znam öta radim.
{40779}{40882}Ni sam bog ne zna öta radiö!|- Krenuli su istoËno prema parku.
{40886}{40963}Vol Strit je juûno!|- Ne viËi. Imam glavobolju.
{41084}{41142}Oh boûe!
{41146}{41196}Rekao sam ti da je put kroz park|uvek zakrËen.
{41200}{41264}Nisam rekao put kroz park.
{41308}{41354}Rekao sam kroz park.
{41422}{41487}Sranje. Izgubili smo ih|u parku, idu juûno.
{41742}{41800}Imam ga Koni. Ide stazom sa pogledom.
{41820}{41850}Beûite s puta. 
{42110}{42192}Pazi! Pazi! Jel ti to|ciljaö na ove ljude?
{42196}{42246}Ne. Moûda ta mimikrija.
{42294}{42314}Drvo! Drvo!
{42465}{42505}äta se deöava?
{42640}{42660}Drvo! Drvo!
{42694}{42714}Drûi se!
{42724}{42744}Kamen! Kamen!
{43020}{43040}Meklejn!
{43050}{43070}äta?
{43374}{43395}Beûi s puta!
{43415}{43448}Kako se katolici krste?
{43451}{43475}Sever, jug, zapad, istok.
{43498}{43545}Koliko joö vremena?|- 27 minuta.
{43550}{43632}Ha! Od 72-ge i Brodveja do centralnog|parka juûno za 3 minuta. Mora da je rekord.
{43792}{43854}Da, a öta sad?
{44012}{44115}Treba nam vatrogasni kamion. - äta?|- Da ga pratimo.
{44201}{44292}911 poruËnik Dûon Meklejn pristupni|broj 7479, zovem sa civilnog predajnika.
{44296}{44371}Dajte mi hitnu liniju, odmah.
{44375}{44411}Hitna, recite.
{44415}{44529}Imam dva ranjena pozornika na uglu 14-te|i 9-te avenije. Potrebna je hitna pomoÊ.
{44533}{44607}Ruzveltova bolnica je dva bloka odavde.|Tu idu hitni pozivi.
{45268}{45308}Uspori jebote, Meklejn!
{45313}{45423}Kao fudbal, nabaviö sebi blokera|i ideö pravo u N-zonu.
{45497}{45553}Da si rekao Vol Strit, mogli smo da|ga pratimo do kraja.
{45557}{45610}Greöiö.|Juûno od 14-te ulice je druga bolnica.
{45614}{45684}Sveti Luka.|- Drûi se!
{45908}{45981}Vreme!
{45985}{46042}10 i 2. Na pola puta smo|joö 18 minuta.
{46046}{46092}Jebeö ovo. Drûi se.
{46480}{46516}Preuzmi volan!|- Gde Êeö ti?
{46520}{46626}Trebalo bi da smo ispred voza. Ja Êu na|taj voz a ti stigni do telefona do 10 i 20.
{46630}{46747}SrediÊu tu bombu. Ako ne stigneö,|pokrivam te, ako ne stignem, pokrivaö me.
{46756}{46804}Ako obojica ne stignemo?
{46808}{46920}Onda smo se sjebali. Idi. Sad!|Stigni do tog telefona do 10 i 20.
{46924}{46984}Moj jebeno sreÊan dan.
{47146}{47274}Sranje! Pazite! Beûite|s puta!
{47421}{47481}Ovo je bila loöa ideja.
{48116}{48188}Izvinite. Pomerite se.
{48541}{48640}112 Vol Strit.|- Ovo nije taksi.
{48644}{48699}Ne razumete.|- Svetlo vam je upaljeno. BiÊu jasan...
{48703}{48782}112 Vol Strit ili Êu vam ukinuti dozvolu.
{48786}{48861}äta je bilo, ne volite belce?
{48865}{48975}112 Vol Strit. Dobro.
{49245}{49324}Pomerite noge. Izvinite.
{50342}{50372}Sranje!
{50405}{50488}Izvinite, izvinite.
{50505}{50553}Policija.
{50570}{50634}HoÊete li se pomeriti odatle malo,|molim vas? Ja sam policajac.
{50638}{50698}Izvinite. Pomerite se.
{51340}{51397}Izvinite, mogu li da proem.|Izvinite.
{51504}{51577}Izvinite, oËekujem poziv,|treba mi taj telefon.
{51581}{51645}Zaöto ne uzmete drugi?
{51745}{51828}Gospodine, molim vas|treba mi taj telefon.
{51832}{51897}Ja sam doöao prvi, brate.
{51901}{51946}Brate?
{51950}{52060}Beûi s prokletog telefona!|- Ruke u vis!
{52444}{52537}Moram da odgovorim na taj poziv.|- UÊuti i digni ruke u vis!
{52541}{52626}Izvinite. Izvinite. Pazite.
{52630}{52684}Dame i gospodo ja sam|njujoröki policajac.
{52688}{52728}ZamoliÊu vas da mirno i tiho...
{52732}{52819}...krenete prema drugom kraju vagona.|Hajde.
{52865}{52937}Hajdete, sad!
{52941}{53005}Pazite, pazite.
{53072}{53155}Moram da odgovorim na taj poziv.
{53159}{53214}U vis!
{53218}{53372}Sluöaj, ako moraö da me ubijeö|onda me ubij!
{53376}{53484}Ali ja moram da se javim na|taj telefon! U redu?
{53612}{53703}Tu sam.|- A Meklejn?
{53707}{53785}Na putu je. Znaö malo je spor,|ispao je iz forme.
{53789}{53846}Pravila su se odnosila na obojicu.
{53850}{53928}Ovo je neposluönost. Zbogom.
{54114}{54259}Verujte mi ljudi. Sagnite se.
{55104}{55169}Beûi odatle! Sagni se,|budalo!
{56399}{56436}Meklejn?
{56597}{56617}äta?
{56746}{56794}Moûe da se vidi sve do podzemne.
{56798}{56904}Koliko ima vatrogasnih kamiona? Momci!|- Kako moûete da ih vidite odavde?
{56971}{57063}PozorniËe, recite tim ljudima|da se vrate nazad.
{57067}{57127}Imamo puno ogrebotina i modrica|nekoliko kontuzija... 
{57131}{57166}...nekom starcu je pejsmejker stao...
{57170}{57250}...i trudnici je pukao vodenjak,|i to je sve. Kako si ti Dûone?
{57270}{57342}Joö uvek ne Ëujem dobro.|- »udo je da si joö uvek ûiv. 
{57388}{57472}Da, to je problem, Dûo. - äta?|- Deo o Ëudu.
{57476}{57538}Koje su bile öanse da stignemo|ovde na vreme?
{57569}{57578}Nikakve.
{57582}{57665}Ta bomba bi eksplodirala|bez obzira na sve.
{57683}{57800}Skini ovo s mene, Dejv.|- äta je tako posebno na ovom mestu?
{57804}{57882}Ne znam. Neöto se ne slaûe.|- PoruËniËe Meklejn.
{57886}{57935}Traûe vas i Gopodina Karvera.
{58012}{58043}Gde?
{58093}{58190}Dûone, ovo je Endi Kros iz FBl.
{58194}{58228}Bil Dûarvis. On je iz...
{58232}{58334}Ja sam iz druge agncije.|Drago mi je öto sam vas upoznao.
{58338}{58435}Ovo je poruËnik Meklejn.|Ovo je gospodin Karver.
{58439}{58504}Imamo nekoliko pitanja. Prvo...
{58508}{58560}Da li prepoznajete ovog tipa?
{58709}{58773}Ne.|- A ovog?
{58859}{58902}A vi?
{58947}{59005}Da li ste prepoznali glas preko telefona?
{59057}{59122}Ne. - Da li ste primetili|da vas prate neka kola?
{59225}{59331}Ne. - Da li vas je bilo ko pratio?|Bilo kakvo prisluökivanje?
{59335}{59407}Telefon, kuÊa, bilo öta neobiËno?
{59411}{59520}Pa sad kad pominjete, osetio|sam trenje
{59524}{59582}izmeu prstiju na nogama.
{59586}{59663}Mislio sam da je atletsko stopalo|ili tako neöto.
{59734}{59777}ProËitali smo vaö dosije.
{59781}{59830}Rekli su nam da Êe te saraivati.
{59834}{59992}Saraujem s Ëim? Gubimo vreme ovde.|- Ako hoÊete da delimo informacije....
{59996}{60049}...onda dajte nama malo.
{60053}{60117}Prvo hoÊemo da Ëujemo öta on zna.
{60120}{60176}Znam isto öto i vi.
{60208}{60269}Tip tamo postavlja bombe.
{60273}{60309}Zove se Sajmon.
{60313}{60387}Govori nemaËkim akcentom,|i iz nekog razloga
{60391}{60433}je vrlo ljut na mene.
{60437}{60502}Recite mi zaöto?
{60631}{60679}Prvi Ëovek tu je Matijas Targo.
{60683}{60738}Bio maarski vojnik,|struËnjak za eksploziv.
{60742}{60793}Sad verujemo da radi za irance.
{60797}{60861}Radi?|- Internacionalni terorista.
{60865}{60892}Po ugovoru.
{60930}{60974}Ko je devojka?|- Targoova druga polovina.
{60978}{61037}Glasine su da su izraelci postavili bombu|ispod njihovog kreveta...
{61040}{61130}...on nije bio kuÊi,|ali oni misle da su nju ubili.
{61134}{61236}Drugi Ëovek je bio odurni poruËnik|u istoËno-nemaËkoj vojsci.
{61239}{61280}Vodio je infiltracionu jedinicu...
{61284}{61344}stvar koju su nacisti radili|u bitci kod Bulga.
{61348}{61420}Trupe koje govore engleski...|- Gledao sam film.
{61449}{61571}Sve öto znamo o njemu je|da njegov medicinski dosije...
{61574}{61643}pokazuje da pati od migrene.|Njegovo ime je Piter Krig.
{61703}{61784}To je izvanredan izveötaj.
{61789}{61848}Kakve to veze ima samnom?
{61853}{61917}Da li vam ime Gruber znaËi neöto?
{62023}{62112}Da, poznato mi je.
{62117}{62187}L.A. - äta?|- Ona stvar u Los Anelesu.
{62231}{62295}Piter Krig je roen kao
{62298}{62374}Sajmon Piter Gruber.
{62403}{62478}On je brat Hansa Grubera.
{62577}{62673}Da, to je ona stvar u L.A.
{62677}{62750}Skontali smo da je reöio da vam|nakaËi etiketu na noûnim prstima...
{62754}{62824}i uradiÊe bilo öta da vam je nakaËi.
{62828}{62990}lnspektore, to je on.|- Nemojte mu reÊi da smo tu.
{63046}{63096}Sajmone.|- Inspektore.
{63142}{63210}Sada, ko je od FBI u kombiju?
{63214}{63332}Da vidimo, skoro sigurno Kros.|Hajde, Endrju, reci zdravo. - Zdravo.
{63336}{63415}Znam da nikad ne radiö sam|pa reci zdravo Bile.
{63419}{63496}Joö uvek pokuöavaö da naoötriö zube|griûuÊi naoËare?
{63543}{63659}Ova gospoda su, kako se kaûe|tamo gde je gusto.
{63663}{63714}Stavio sam 2.400 funti eksploziva...
{63718}{63795}u jednoj od 1.446 ökola|u veÊini Nju Jorka.
{63799}{63903}Podeöena je na tajmer da|eksplodira u 15 Ëasova.
{63939}{63998}Hvala.|Vaöa Êutnja kaûe da sam shvaÊen.
{64002}{64066}Jeste li rekli 2.400 funti?
{64070}{64134}Da, ali molim vas da me|viöe ne prekidate. Sajmon kaûe:
{64138}{64183}ako pokuöate da evakuirate ökole...
{64187}{64290}...bomba Êe biti detoniraana preko radija.|I gospodo neko Êe nadgledati.
{64294}{64390}Ponavaljam: jedna ökola Êe biti zauvek ukinuta|u 15 Ëasova...
{64394}{64434}osim ako...|- Osim ako öta?
{64438}{64530}Osim ako Dûon Meklejn i njegov novi|prijatelj zavröe zadatak koji im postavim.
{64534}{64583}Dûone, jel sluöaö?|- Da.
{64662}{64730}Telefonska govornica|iza Tomkinsovog parka.
{64734}{64800}Dvadeset minuta.|Idite peöice. Bez ûurbe.
{64804}{64902}Ako ste dovoljno lukavi provaliÊete|lokaciju bombe i njenu öifru za demontiranje...
{64906}{65027}Ovaj, gospodo imali smo popust|za ove radio detonatore.
{65031}{65087}Jedini problem je öto|proklete stvari reaguju
{65091}{65140}na policijske i FBI frekvencije.
{65144}{65222}Da sam na vaöem mestu,|ugasio bih vaöe radio frekvencije.
{65226}{65270}Sajmone, Ëekaj.
{65371}{65477}2.400 funti tog teËnog sranja.|Moj boûe!
{65481}{65524}Dovedite mi premijera.
{65528}{65595}BiÊe ovde za 30 minuta.|Na pres konferenciji je.
{65599}{65675}Dovedite sve starije oficire|ovde odmah.
{65679}{65743}I nemojte da mi dajete gluposti|jurisdikciji.
{65747}{65800}Imam dvoje dece u|ökoli u 64-toj ulici.
{65829}{65879}Kako mogu da pomognem?|- Koliko ljudi imate?
{65883}{65963}75, ali ako pritisnem dugme za uzbunu|mogu da dobijem 500 iz Vaöingtona.
{65967}{66019}Kad?|- Pola tri, tri sata.
{66023}{66077}Izmeu sada i tada...
{66081}{66176}MoraÊemo sve sami.|Idemo.
{66212}{66312}Tomkinsov park je 2 milje daleko.|TrËite. Bez radija. Uzmi moj telefon. 
{66316}{66399}Ako neöto uradite zovite me preko centrale.|SreÊno.
{66403}{66478}Hvala. Naite tu bombu.
{66482}{66527}Riki, gde su?|- Ovamo.
{66531}{66596}Glavni Ëovek je öef Alen.|- äef Ëega?
{66600}{66653}Tranzita.
{66657}{66738}äefe Alen, Ëovek koji je ovo uradio,|rekao nam je da je postavio 
{66742}{66812}veoma veliku bombu
{66816}{66909}u jednoj Njujorökoj ökoli.
{66913}{66957}Rekao je da ne moûemo da evakuiramo.
{66961}{67018}Ali nije rekao da ne moûemo da traûimo.
{67022}{67091}Predlaûem da dovedemo sve,|mislim sve, 
{67095}{67149}policiju, tranzit,|sanitarce, vatrogasce...
{67153}{67255}Ëak i proklete bibliotekare...|i poËnemo da pretraûujemo ökole.
{67259}{67288}I to odmah.
{67292}{67356}Govorim o 1000 zgrada
{67360}{67419}a imamo 3 sata i 15 minuta|da to uradimo.
{67422}{67489}Voleo bih da ne uvlaËimo medije u ovo|jer ako oni otrkiju ovo....
{67492}{67609}imaÊemo paniku.|Slaûemo li se? - Hajde ljudi idemo.
{68036}{68080}Naseli su.
{68124}{68165}Moûete da poËnete.
{68535}{68675}Kuka, kanap i mamac.
{69697}{69775}NaredniËe Tarli. NaredniËe Tarli.
{69779}{69890}U poslednjih 5 minuta|pozivi su se utrostruËili.|äta se deöava?
{69894}{69946}Stani. Dozvoli da objasnim.
{69950}{70028}Do kraja dana|preuzimamo komunikacije odeljenja.
{70032}{70079}Kako to mislite preuzimamo?
{70083}{70178}Ugasili su policijski kanal.|Svi pozivi idu preko ove centrale.
{70182}{70233}A ja Êu da se udam za Donalda Trampa.
{70239}{70342}Volö, öta se dogada?|Zaöto su svi otiöli odavde?
{70441}{70501}Pamela, gledaj koliko je sati,|dolazi vreme za smenu. Nadleûni se brinu
{70505}{70594}za prekovremeno. Svi su otiöli da se|otËekiraju. SledeÊa smena uskoro dolazi...
{70598}{70686}Mnogo sereö, Volö.|- Hvala.
{70865}{70909}äta doavola?
{71201}{71254}Detektive... Bob Tompson, 
{71258}{71311}Iz kancelarije gradskog inûenjeringa.
{71343}{71407}Doöli smo da procenimo ötetu.
{71450}{71525}»oveËe, vi ste doöli priliËno brzo.
{71554}{71698}Ovo je Vol Strit, gospodine|mnogo novca.
{71702}{71815}Mnogo donosioca odluka koje|gradonaËelnik ne ûeli da naljuti.
{71856}{71900}Jel to ovde?
{71962}{72032}Sveti Toledo!
{72036}{72106}Neko se stvarno zabavljao.
{72110}{72207}Bio bih vam zahvalan ako bi ste|mojim kolegama pokazali put dole.
{72255}{72368}Naravno. Dûimi,|imaö li bateijsku lampu?
{72372}{72416}Marfi, hajde i ti.
{72420}{72474}Rik Volö.|- Dûon Ginter.
{72478}{72530}Hajdete, gospodo. Idemo.
{72617}{72686}Bili ste na svetskom sajmu,|znate kakav je to haos bio.
{73474}{73561}Molim vas obavestite gospodina Litla|da je ovde gospodin Vanderflog.
{73676}{73729}Tu je gospodin Vanderflog|za gospodina Litla.
{74072}{74152}Idu dole 20 metara.
{74156}{74179}Mnogo je pare ovde.
{74183}{74227}Neke cevi za paru su pukle.|- Kao u sauni.
{74231}{74324}Momci iz ûeleznice su|zatvorili 3 traku.
{74328}{74409}PomoÊna svetla.|- PomoÊna svetla su...Hej!
{74436}{74502}Bez pucanja!|- Govori engleski!
{74506}{74563}Oto ne zna da priËa engleski,|zar ne Oto?
{74567}{74638}Gde smo naöli ovog tipa?|- Jedan od Targoovih gorila.
{74707}{74771}Idite sve do gore. Sve do gore.
{74939}{75003}Pa, öta je to bilo u L.A.?|Jesi li popularan ili tako neöto?
{75006}{75058}Da, oko 5 minuta.
{75062}{75123}Nemoj da mi kaûeö.|Rodni King, jel tako?
{75127}{75181}Jebi se. Znaö ko je taj tip Sajmon?|- Ne.
{75185}{75278}Bacio sam mu mlaeg brata sa 32 sprata|Nakatomi zgrade u L.A.
{75299}{75343}Izgleda da je malo nadrndan.
{75347}{75393}»ekaj, hoÊeö da mi kaûeö|da sam u ovom sranju
{75397}{75469}zato öto je neki beli policajac bacio|brata nekog belog seronje sa krova?
{76569}{76625}Gospodine Vanderflog, Feliks Litl.|Veze sa korporacijama.
{76629}{76707}éao mi je öto ste morali da Ëekate,|ali bila je ekplozija u metrou.
{76711}{76756}To je oötetilo naöe alarme.
{76760}{76795}Verujem da je sve u redu?
{76799}{76853}Ne, dragi boûe.|Bezbedno i sigurno.
{76857}{76929}Interesovala vas je razmena valute.
{76933}{77007}Mi nismo komercijalna banka|u normalnom smislu.
{77011}{77073}Mi smo primarno
{77077}{77138}za vlade, centralne banke.
{77142}{77203}Pored depozita, naravno.
{77208}{77227}Naravno.
{77231}{77295}A vi ste u poslu sa cveÊem?|- Nazad! Hajde!
{78397}{78473}Ne, gospodine Vanderflog to je|lift za sef.
{78505}{78583}Izvinite. Naöi alarmi su|soniËni i seizmiËni.
{78587}{78648}Ne reaguju dobro na eksplozije.
{78652}{78747}Ovaj posao sa metroom je|izbacio naö sistem.
{78751}{78818}Ustvari, morali smo sve da iskljuËimo.
{78822}{78861}Majstori su dole sad.
{78865}{78887}Moj boûe!
{78892}{78974}Da, dragi boûe i ako bi neko znao...
{79078}{79157}Ali, mislio sam da je|ovo razmena valute?
{79161}{79241}O, mislim da Êemo preÊi|pravo na podizanje.
{79607}{79659}Banka federalnih rezervi.
{80402}{80519}Kapetane, doite da vidite ovo.|Neöto nije u redu.
{80523}{80617}Mislite, da moûete to popraviti?|- Samo jedan minut.
{80707}{80760}Dobro. VratiÊu se. Dole!.
{80881}{80931}Nazad!
{80935}{80970}Nazad!
{81775}{81834}Hajde!
{82101}{82118}Portirnica.
{82122}{82188}Siite dole!|Napadnut sam!
{82192}{82264}Smiri se druûe,|moûda Êeö ovo da preûiviö.
{82268}{82312}Sranje!
{82844}{82914}Mislim da je mrtav draga.
{82956}{83012}Pobrinite se za kancelarijske radnike.
{83016}{83070}UËinjeno öefe.
{83149}{83182}A trg?
{83186}{83246}Ta oblast je obezbedena öefe.
{83498}{83545}Moj boûe! Ovo je Fort Noks.
{84094}{84177}140 milijardi dolara.
{84181}{84226}Deset puta viöe nego|u Kentakiju. Fort Noks, za turiste.
{84720}{84804}Dûone, jedva ste stigli.|Niste u formi.
{84808}{84897}Da jedva smo stigli.|äta hoÊeö da uradimo?
{84901}{84968}äta ima Ëetiri noge i|uvek je spremno da putuje?
{84972}{85104}äta je rekao? - äta ima 4 noge|i uvek je spremno da putuje?
{85109}{85196}äta je s tobom, zar nemaö decu?|To je öala o slonu.
{85391}{85477}To je bomba?|- Da idi uzmi je.
{85480}{85518}Ne. Ti si policajac.
{85521}{85582}Trebalo bi da pomaûeö.|- Pomaûem.
{85585}{85662}Kad Êeö poËeti da pomaûeö?|- Kad budeö uzeo bombu.
{86080}{86144}Paûljivo!|- Paûljiv sam.
{86147}{86188}Ne otvaraj.
{86193}{86258}äta? Moram da otvorim.|Sve Êe biti u redu.
{86505}{86555}{Y:i}JA SAM BOMBA. UPRAVO STE|ME AKTIVIRALI.
{86559}{86649}Sranje! Rekao sam ti da ne otvaraö!
{86761}{86813}Verujem da vidite poruku.
{86817}{86861}Ima vremensko ograniËenje
{86865}{86895}zato molim vas ne beûite.
{86899}{86979}NeÊemo da beûimo.|- Kako da je demontiramo?
{86983}{87026}Na fontani su dva balona.
{87030}{87122}Da li ih vidite? Jedan od 5|galona i jedan od 3.
{87126}{87218}Sipajte u jedan balon taËno|4 galona vode
{87222}{87300}stavite ga na ploËu.|I tajmer Êe stati.
{87304}{87412}Morate biti precizni. Jedan mililitar|manje ili viöe
{87416}{87462}rezultovaÊe detonacijom.|- »ekaj malo.
{87606}{87650}Ne razumem. A ti?|- Ne.
{87704}{87748}Daj te balone.
{87935}{88003}OËigledno ne moûemo da sipamo|4 galona u balon od 3 galona. 
{88007}{88083}Znam! Napunimo balon od 3 galona|do vrha. Sipamo ta 3 galona
{88087}{88155}vode u balon od 5 galona. Imamo 3 galona|vode u balonu od 5 galona.
{88159}{88199}I onda?
{88203}{88251}Uzmemo balon od 3 galona|i napunimo ga do treÊine.
{88255}{88312}Rekao je da budemo precizni,|tacno 4 galona.
{88316}{88455}Do avola! Svi policajci traûe|a ja se igram deËje igre u parku.
{88459}{88515}Hej! HoÊeö li da se fokusiraö na|ovaj problem?
{88904}{88986}Rekao si, nemoj niöta da kaûeö ako ne znaö!|Daj mi
{88990}{89047}te balone. PoËinjemo od poËetka|- Ne moûemo od poËetka.
{89075}{89156}äutnuÊu te u bulju ti glupi...|- Reci, reci!
{89196}{89257}Hteo si da me nazoveö crnjo!|- Nisam! - Jesi!
{89261}{89351}Nego öta? - Seronjo! Kako ti to zvuËi?|Ne svia ti se öto sam belac.
{89433}{89499}Jesam li te tlaËio? Jesam li muËio|tvoj narod nekako?
{89503}{89564}HoÊeö da ti kaûem tvoj problem.|Ti si rasista! - äta?
{89568}{89628}Ne dopadam ti se zato öto sam belac!
{89632}{89681}Ne dopadaö mi se zato öto|Êu zbog tebe poginuti!
{89685}{89799}Koliko joö vremena?|- Sranje! Manje od minuta. Baci to.
{89803}{89892}Ne moûemo. DetoniraÊe. »ekaj.
{89942}{90003}Znam. Ovde ima 2 galona|vode, jel tako?
{90007}{90057}Ostaje 1 galon|praznog prostora. - Da.
{90061}{90107}Ovde ima 5 punih galona, jel tako?|Ako prespeö 1 galon od 5 galona, 
{90111}{90168}u ovaj imamo taËno 4 galona.
{90172}{90248}Sipaj!
{90305}{90359}Nemoj da prospeö! - Dobro.
{90363}{90431}Imamo 4 galona.|- Uspeo si Meklejn!
{90435}{90503}Stavi je na ploËu!
{90530}{90563}{Y:i}DEMONTIRANO
{90699}{90761}»estitam. Joö ste ûivi. »estitam.|- Da uspeli smo.
{90765}{90849}Opet me iznenaujeö, Dûone.|Ovo prelazi u ruûnu naviku.
{90967}{91039}Nemam sad vremena|za razgovor, Sajmone.
{91043}{91098}Dogovor je dogovor.|U kojoj ökoli je bomba?
{91102}{91174}Naprotiv, imate dosta vremena.
{91179}{91303}Dva sata i 47 minuta taËno.
{91307}{91366}Dosta vremena da|istestiram tvoje vijuge.
{91370}{91490}Sluöaj, seronjo imam uûasan mamurluk.
{91495}{91559}U kojoj ökoli je bomba?
{91562}{91670}Strpljenja, Dûone. Put do istine|ima mnogo krivina.
{91673}{91755}NaÊi Êeö kovertu ispod obruËa|fontane.
{91759}{91860}Kad kreneö na zadatak koji ona|postavi, upitaj se:
{91865}{91952}äta ja 21 od 42?
{92003}{92060}Zaostajemo s vremenom.|Treba da ostavimo ostalo i odemo.
{92064}{92140}Smiri se Targo. Nema policajca|na 20 blokova odavde.
{92143}{92253}Poöalji domaÊi tim|na Jenki stadion. Zaöto?
{92257}{92310}Tamo treba neöto da naemo?
{92314}{92358}äta je 21 od 42?
{92362}{92442}21. Polovina od 42.|42 Ëega?
{92446}{92490}Koliko igraËa imaju Jenkiji?
{92494}{92517}25.
{92521}{92610}äta je joö 21? Blek-dûek?|- Klub.
{92614}{92668}To je lov u mutnom|eto öta je.
{92768}{92818}Gde je nabliûi A voz?
{92822}{92922}»ekaj. Neko dete bi moglo da nae ovo.
{92962}{93006}U pravu si.
{93143}{93265}Vratite se! Vi mali kuËkini sinovi!|Hej ti zapamtio sam te!
{93303}{93368}Gde Êeö? äta to radiö?
{93372}{93429}Pusti me kretenu.|- Pazi na jezik!
{93433}{93524}Ideö u dom za maloletnike|zbog Ëokolade?
{93528}{93594}Pogledaj okolo.|Svi policajci rade neöto.
{93598}{93646}BoûiÊ je. Moga bi da pokradeö|gradsku skupötinu.
{93823}{93899}Hajde.|- Moj bicikl!
{93903}{93926}Seronjo!
{93930}{94030}Gde Êeö? Jenki stadion je tamo.
{94189}{94259}Zaöto ne pregaziö svakoga na ulici!
{94263}{94323}äta do avola radimo ovde?
{94327}{94392}Da te pitam neöto.|äta Vol Strit nema?
{94396}{94455}Govoriö u zagonetkama?
{94459}{94502}Ne, prati me. äta Vol Strit nema?|- äta? 
{94506}{94570}äkole. A Ëega imaju kao govana?|- »ega?
{94738}{94787}{Y:i}BANKA FEDERALNIH REZERVI
{94791}{94842}VratiÊu se za minut.
{94846}{94975}äta da radim s ovim?|- Daj ih onim policajcima tamo.
{94979}{95059}On je ovde.|- Moûda bi mogao da budeö malo jasniji?
{95063}{95162}Meklejn je ovde. Ide prema banci.
{95190}{95250}Crnac ide prema meni.
{95254}{95322}Kakva öteta!
{95326}{95384}Posle toliko muke|na stadionu.
{95388}{95438}Ubij ga, Sajmone.
{95442}{95503}Prestani da se igraö s njim i ubij ga.
{95531}{95582}Dobro. Neka bude tako.
{95586}{95706}Nek' poËiva u miru.|InformisaÊu Karla u holu.
{95710}{95751}Pokupi tvoj tim i|idite odavde.
{95755}{95778}A ovaj?|- PozorniËe!
{95906}{95968}TrebaÊe mi odgovor na to pitanje.
{96098}{96183}Pusti ga.|- Razumem.
{96187}{96251}Dûon Meklejn mi je reako|da vam dam ovo.
{96290}{96350}Isuse ne otvarajte.|To je bomba.
{96354}{96461}Joö jedna? Ah, vidim.
{96465}{96488}Bolje da krenemo.
{96492}{96582}Hvala vam na pomoÊi.|Stvarno je cenimo.
{96652}{96729}äta to radiö?
{96774}{96832}NeÊu da se vozim s tim.
{96836}{96891}Neko dete moûe da je vidi...
{96895}{96939}Ubaci je pozadi.
{97074}{97145}Hej zar Êe te ostaviti|ovo mesto nezaötiÊeno?
{97374}{97420}Razumem.
{97646}{97724}Kako ste?|- Dobro sam.
{97728}{97782}Ko ste vi?|- Dûon Meklejn, policija Nju Jorka.
{97785}{97817}Jeste li dobro?
{97820}{97897}Da, dan za pranje veöa.
{97925}{97976}äta mogu da uradim za vas, poruËniËe?
{97979}{98043}Jeli bilo tiho ovde celo jutro?|- Pa...
{98047}{98122}Osim one eksplozije|pre nekoliko sati.
{98125}{98186}Niste videli da se desilo neöto|Ëudno u zadnjih sat vremena?
{98190}{98281}Ne. Imamo policiju ovde, priliËno je|mirno posle eksplozije.
{98329}{98396}Baö smo krenuli u patrolu,|do sefa ako hoÊete s nama.
{98400}{98519}Da. HoÊu.|- äta mislite o ovoj vruÊini?
{98523}{98562}Indijsko leto.
{98566}{98646}Izgleda da Êe kasnije da|pljuöti kiöa kao iz kabla.
{98650}{98753}Ovo je jedan od vaöih kolega.|Detektiv Oto, zar ne?
{98865}{98909}Majk, kako si?
{98964}{99054}Stalno govorim sebi da Êu iÊi|stepenicama zbog rekreacije
{99058}{99178}ali na ovako vruÊ dan izgleda da|uvek zavröim vozeÊi se liftom.
{99829}{99877}Koji su brojevi lutrije bili sinoÊ?
{99881}{99958}Igrate lutriju, ne?
{99962}{100085}Moja ûena kupuje dva tiketa svake|nedelje. Stalno igra iste brojeve.
{100089}{100134}Kaûem zaöto ne igraö|druge brojeve a ona Êe:
{100138}{100253}"To su moji sreÊni brojevi".|Imam tikete upravo ovde.
{100325}{100414}Spusti jebeni piötolj!|Spusti piötolj!
{100782}{100832}Ima li koga ovde?
{101082}{101129}Stani! Ruke u vis!
{101133}{101193}Ne, Dûone! To sam ja! Sranje!
{101250}{101317}Zamalo öto nisam dobio|srËani udar zbog tebe.
{101321}{101400}Jesi li dobro?|- Da to nije moja krv.
{101404}{101459}äta se deöava?|- Idi pogledaj.
{102015}{102103}Hej, Meklejn gde su svi?
{102107}{102154}Jebeni Sajmon.
{102196}{102232}Trebalo je da pretpostavim.|Nije hteo osvetu. PljaËka. 
{102349}{102433}äta je bilo unutra?|- Ovo.
{102437}{102494}äta je ovo? Sranje! Je li ovo zlato?
{102498}{102568}Tako je. Do davola öto je teöko,|sve su pokupili?
{102572}{102671}Da. - Za to im je bio potreban|tenk ili...
{102675}{102782}Ili kamion za smeÊe.|- 14 velikih kamoina za smeÊe.
{102786}{102863}Skoro da nas je zgazio takav kamion.|- Do avola! Uspori.
{102868}{102904}Baci to sranje.|- Nema öanse.
{102908}{102956}NeÊe ti dozvoliti da|ga zadrûiö.
{102960}{103009}VideÊemo.|- Treba nam auto.
{103182}{103264}Moûeö li da ga upaliö?
{103267}{103320}Naravno. Ja sam elektriËar|Jedini problem je
{103402}{103452}öto predugo traje to.
{103743}{103840}Nisu na mostu.|- Dole Meklejn, F.D.R.
{103915}{103959}Idemo! Poûuri.
{103995}{104119}Sranje. Sjeban telefon.
{104123}{104190}äteta. äta je 21 od 42?
{104194}{104242}Ne znam.|- A Jenki stadion?
{104246}{104293}BiÊemo tamo poöto|ih uhvatimo.
{104335}{104371}Isuse! äta ti misliö da si|Hilari Klinton?
{104375}{104444}Tako je, Hilari Klinton,|42 Predsednik.
{104448}{104529}Ona bi bila 43.|- Ali ko je bio 21?
{104579}{104609}Ne znam.|- Ne znaö?
{104613}{104648}Da li ti znaö?|- Ne! - Pa?
{104692}{104742}Ova kola su sranje, nagazi!
{104746}{104822}To je Jugo. EkonomiËan je,|ne brz.
{104881}{104938}äta to radiö?|- Nabavljam nam drugi telefon.
{105080}{105159}Stani! Hej, ko je bio 21 predsednik?|- Jebi se!
{105212}{105248}»oveËe, ala je taj tip ljut.
{105252}{105300}OseÊaÊe se bolje kad pogleda|na zadnje sediöte automobila.
{105304}{105352}Sranje!|To je bila moja zlatna poluga.
{105356}{105417}Meklejn. Dajte mi inspektora|Voltera Koba.
{105421}{105483}Gde si do avola?
{105487}{105521}Nije u pitanju osveta,|pljaËka je.
{105525}{105626}Zlato je u federalnim rezervama.|Uzeli su gomilu. Krenuli su severno
{105630}{105666}u kamionima za smeÊe?|- Jesi li pio?
{105670}{105768}Ne od jutros. Ima puno kamiona severno
{105772}{105862}na F.D.R. oko 70 na sat. Zatvori most|i dovedi helikoptere ovamo.
{105866}{105962}Ne bih mogao da zatvorim hot-dog|kiosk sada. Raöiren sam na sve strane.
{105966}{106056}äta je s bombom?|- Ima veze s 21 predsednikom....
{106060}{106101}21 öta?|- Voltere!
{106105}{106200}Sranje! Prokleti mobilni telefoni.
{106204}{106269}Nazovi Mansona na Triburu.|Reci mu da zatvori sve mostove
{106273}{106346}severno od 59-te.|Traûimo kamione za smeÊe.
{106377}{106469}Meklejn kaûe da kamioni puni zlata|idu preko F.D.R.
{106473}{106545}Nisu dozvoljeni kamioni|na F.D.R. - Koni!
{106582}{106666}U redu. NeÊu da se protivim bez obzira|koliko glupo to bilo.
{106670}{106740}K-9 proveri kotlarnik.
{106744}{106787}Jesi li naöao iöta, Carli?
{106791}{106855}Mogu da provedem ovde nedelju dana|sa rendgenom i da i dalje ne naem niöta.
{106859}{106938}Nemaö nedelju dana. Imaö 5 minuta.|Onda idemo do 86-te ulice.
{106942}{107008}Radimo najbrûe öto moûemo.
{107012}{107048}äta je bilo?
{107052}{107135}Meklejn je pominjao neöto|o zgradi federalnih rezervi.
{107139}{107193}Zar to nije blizu mesta gde|je eksplodirala bomba u Vol Stritu?
{107376}{107428}Koliko hoÊeö da ostanemo ovde?
{107432}{107492}Ljudi na stadionu,|ostaju ili idu?
{107496}{107549}Karl je trebalo da se javi do sada.
{107765}{107792}Hajde. Hajde.
{107857}{107933}Ostanite gde jeste. Meklejn se moûda|joö pojavi.
{107961}{108109}Smiri se, Targo. Ako je joö ûiv,|neÊe moÊi da razgovara ni sa kim.
{108113}{108145}SledeÊe skretanje.
{108180}{108232}Zdravo, ovde Elvis Duran. U programu ste.
{108236}{108338}Prvo hoÊu da vam kaûem kakav|sjajan öou imate. Stalno vas sluöam.
{108342}{108380}Hvala. äta imate da kaûete?
{108384}{108488}Znate li zaöto policija juri po gradu? 
{108492}{108599}Postavljena je bomba u ökoli.|Moj roak je policajac.
{108603}{108660}Neko je postavio veliku bombu|u neku ökolu...
{108664}{108720}Samo öto oni ne znaju u koju.
{108724}{108794}Pa ih sve pretraûuju.
{108798}{108848}Sve ökole u gradu.
{108851}{108904}Koje sranje!
{108939}{108979}Doris! Moûeö li da pozoveö|moju ûenu.
{108983}{109101}Tarli! Pola prokletog|grada zove 911.
{109168}{109264}Nestali su. - äta.|- Ko je ovaj tip Hudini?
{109267}{109394}Dole! Dole!|- Jel ova stvar ima vazduöne vreÊe?
{109397}{109452}Tvoja strana ima.|Ne znam za moju...Meklejn!
{110003}{110128}U kamionu. Da ti vidim ruke.|Stavi ih na vrata!
{110222}{110278}Nemoj da me ubijeö! Nemoj da me ubijeö!
{110319}{110342}Jesi li ti vozaË?
{110346}{110423}Ne, ja sam kozmetiËar,|naravno da sam vozaË!
{110451}{110483}Gde voziö ovaj kamion?|- Na akvadukt.
{110487}{110653}Zaöto voziö ovo na trkaËku stazu?|- Ne, akvadukt, vodeni akvadukt.
{110657}{110693}Akvadukt?
{110753}{110859}Vidite? Ide odavde|pravo gore do Ketskil planina.
{110863}{110909}äta?
{110915}{110967}Cev za vodu.|DugaËka je oko 60 milja.
{111134}{111171}Jesili ti glavni?|- Da.
{111175}{111254}Policija. Da li su proöli|neki kamioni ovuda u zadnjih
{111258}{111283}nekoliko minuta?
{111287}{111387}ZapisaÊu te proklete klovnove.|Bolje im je da obrate paûnju na posao.
{111391}{111418}äta se desilo?
{111422}{111471}Tuce idiota je uölo kroz ovu cev.
{111475}{111545}Ne punimo viöe tamo, nego ovamo.
{111549}{111599}Toliko o mostovima i helikopterima.
{111603}{111649}Imate li mapu da vidim|gde idu ovi tuneli?
{111653}{111697}Da, evo je.
{111741}{111829}Idemo prilËno ispod pilane|dok ne doete do Koferove brane.
{111833}{111900}Odatle smo veÊ doveli|vodu iz rezervoara.
{111904}{111942}Ima li neki ulaz i izlaz tu?
{111946}{111985}Imate otvore za ventilaciju|svake dve milje.
{111989}{112096}Ne, mislim sa kamionom?|- Kod Koferove brane.
{112100}{112187}Samo pratite park kod pilane|to je oko 20 milja.
{112191}{112276}Tamo Êemo se sresti.|- A öta Êu ja da radim?
{112280}{112352}Idi na Jenki stadion.
{112356}{112434}Idi imamo manje od 2 sata.|- Do avola!
{112572}{112627}Hej, jel' neöto nije uredu?
{112631}{112742}480 jardi kamenja je odneöeno do sada.|Deset puta viöe nego kod Huverove brane...
{112746}{112814}Sada je 516 stopa kamenja
{112818}{112851}iznad naöih glava.
{112855}{112919}Ovaj deo je faza|3 tunela 3.
{112923}{112987}Planiranje je poËelo 1954. god.
{112990}{113056}ali graenje nije poËelo|do 1970. god. 
{113060}{113124}Znate li öta je|najinteresantnije kod tunela 3?
{113128}{113181}Ne, öta Dûeri?|- Cevovodi. Svaki...
{113345}{113432}Glavni poËetak|od tunela 1 i 2.
{113436}{113536}Hajde! Kakvo mesto da se pokvari...
{113540}{113614}Stani. Daj mi tvoj ölem.
{113618}{113707}Imaö li jaknu? SaËekaj tu.
{113711}{113796}SaËekaj da doe do vrata.
{113800}{113882}Hej. Momci. Miki O'Brajan,|obezbeenje akvadukta.
{113886}{113959}Dobili smo izveötaj|da je tip proöao ovuda sa 8 irvasa.
{114144}{114218}Da, rekli su da je bio veseli,|stari, debeli Ëovek
{114222}{114256}sa sneûno-belom bradom.
{114260}{114333}Slatkim crveno-belim odelom.|»udi me da ga niste videli.
{114415}{114526}äta je bre s ovim telefonima?|Dajte mi neöto.
{114563}{114639}Sranje! Jeli taj tip mrtav?
{114643}{114725}Da, Dûeri plaöim se da jeste.|- Moj boûe!
{114729}{114909}HoÊu da nadeö VolteraKoba.|On je moj öef.
{114913}{114997}Reci mu da si bio sa|Dûonom Meklejnom.
{115001}{115068}Reci mu da sazna|ko je 21 predsednik.
{115072}{115095}»ester A. Artur.|- äta?
{115121}{115202}»ester A. Artur, 1881-1885, 
{115206}{115260}nominovani potpredsednik 1880.
{115264}{115336}Jel znaö da je bio|carinik ovde u Nju Jorku?
{115340}{115389}Ne, nisam znao to Dûeri. »uvaj se.
{116163}{116195}Sad?
{116213}{116264}Ne, samo je jedan od njih.
{116430}{116478}{Y:i}IGRA JE GOTOVA
{116635}{116675}Da ili ne?
{116827}{116858}Ne!
{116868}{116911}PratiÊemo ga.
{116971}{117042}TV nas je uhvatila, moramo da pustimo|ove iz saobraÊajnog.
{117046}{117085}Ne, pobrinuÊemo se|kasnije za saobraÊajne guûve.
{117089}{117153}äta je s ovim?|- Frekvencije su se zaglavile.
{117156}{117194}Gde je Riki?
{117198}{117247}Ne mogu da ga dobijem. Voltere.|- äta? - Zgrada federalnih rezervi.
{117251}{117308}NajveÊe skladiöte zlata|u svetu.
{117362}{117440}Poöalji odeljenje tamo. Nadi Rikija.|Vidi öta se do avola deöava.
{117480}{117522}Voltere, moraö da Ëujeö ovo.
{117634}{117722}Isuse, mislio sam da je ovo zadnji ulaz.|- Jeste, Voltere.
{117746}{117818}Za pola sata Êemo imati pobune|u svim ökolama u gradu.
{117899}{117970}{Y:i}OSNOVNA äKOLA »ESTER A. ARTUR
{117974}{118038}PoËnite od najviöeg sprata.|20 ljudi po spratu.
{118042}{118098}Poöaljite 50 dole u podrum sa nama.|äta je s Meklejnom?
{118102}{118181}Ni reËi. Dobijam samo zauzet signal.
{118205}{118260}Zar ovo nije kao stavljanje svih|jaja u jednu korpu.
{118264}{118323}äta ako Meklejn greöi?
{118327}{118379}Voltere, ovo je direktorka Martinez.|lnspektor Kob.
{118383}{118443}Zdravo, inspektore?
{118447}{118509}Ne bih da uznemiravam vaöu decu ali|bih vas zamolio da ih prebacite
{118513}{118552}u auditorijum i drûite pod kontrolom.
{119003}{119076}Stigli smo do brane.|Moûeö da pozoveö zadnjeg straûara.
{119202}{119257}Straûar! Moûeö da zatvoriö.
{119300}{119362}Stigli smo do brane.|Moûeö da doeö.
{119398}{119488}Nils? Moûeö da zatvoriö.
{119492}{119506}Nils?
{119510}{119574}Paûnja. Paûnja Nils je mrtav.
{119578}{119660}Ponavljam. Nils je mrtav,|kretenu.
{119664}{119720}I njegov drug. I ona 4 momka iz|istoËno-nemaËkih zvezda.
{119724}{119864}Tvoji momci u banci?|Malo Êe da kasne.
{119886}{120018}Dûone, u kamionu voziö 13|milijardi dolara.
{120022}{120100}Dogovor ne bi doöao u obzir, zar ne?|- Imam ponudu za tebe.
{120104}{120193}Izai ispod kamena kojeg se krijeö|i nabiÊu ti kamion u bulju.
{120222}{120254}Veoma ûivopisno.
{120401}{120453}Rekao sam ti da se ne igraö s njim.
{120457}{120503}Havla. To mi je veoma pomoglo.
{120582}{120650}Ugrozio si celu misiju|i ugovor.
{120712}{120771}Ranjivi smo sve dok|ne stignemo na brod.
{120775}{120805}StaÊu ovome na kraj.
{120862}{120891}Stani!
{120968}{121150}Targo! Targo! Doi ovamo!|RazneÊemo branu.
{121154}{121187}PotopiÊemo ga...
{121197}{121253}Jani, postavi je gore.
{121511}{121614}Voltere, doi da vidiö ovo.|Domar je rekao da je ovo stiglo jutros.
{121618}{121673}Nije ukljuËeno.|- Da.
{121677}{121746}Sad pogledaj napred.
{121825}{121877}IzbuöiÊemo öarke. Izbacite sve napolje.
{125611}{125667}Meklejn, gde si?|- Ovde!
{125671}{125729}OdliËan naËin da signaliziraö nekom.
{125733}{125848}Jesi li bio na stadionu?|- Da, tamo nema nikog.
{125853}{125907}Nisi nikog video?|Niko te nije pratio?
{125911}{125961}On nas zajebava!
{126013}{126075}"Niko te nije pratio. Niko. Niko"
{126079}{126131}Hajde! Hajde!
{126236}{126291}Nije montirano.|Otvori.
{126376}{126445}{Y:i}äIFRA ZA OPOZIV
{126568}{126659}Pa, moûeö da|opozoveö potragu.
{126663}{126725}Moûeö li da je deaktiviraö?|- Ne bi trebalo ni da je diram.
{126729}{126794}Ko zna kakve sve zamke ima ova stvar.
{126798}{126860}A öifra?|- Niöta joö.
{126864}{126899}Kada Êemo da evakuiramo?
{126903}{126993}Sajmon kaûe da ako vidi jedno dete|da izae iz zgrade...bum.
{126997}{127103}Ne moûemo da stojimo ovde sa palËevima|u buljama Ëekajuci da ta stvar eksplodira!
{127261}{127336}Sranje!
{127340}{127401}Sagni glavu! Drûi ga mirno!
{127503}{127534}Vozi!|- Blokiraju nas!
{127537}{127572}Zaobii ih!
{127881}{127978}Saznao sam ko je 21 predsednik.|Neki tip zvani Artur.
{127982}{128029}»ester A. Artur?
{128033}{128083}»ester A. Artur je osnovna ökola?|- Da, tako je.
{128683}{128800}Znam da obiËno imate okupljanje|petkom, ali danas je specijalno.
{128804}{128871}Gospodin Lambert je iz|vatrogasne sluûbe.
{128875}{128979}On hoÊe da sa nama uveûba|novu vatrogasnu veûbu.
{128983}{129073}PodeliÊete se u dve grupe.
{129077}{129141}Ova polovina Êe se poreati uz zid.
{129144}{129261}Druga polovina u ovom smeru. Idemo brzo|i tiho.
{129265}{129341}Svi ustanite, molim. Profesori|Êe vam pomoÊi.
{129345}{129424}Vatrogasna veûba, malo sutra.|Ovaj tip nije iz vatrogasne sluûbe.
{129428}{129474}Moûda je to zbog radija.
{129478}{129549}Misliö da nas jure?|- Ne.
{129553}{129630}Toni nas je ocinkario.|- Nije.
{129634}{129664}Hajde.
{129668}{129716}Gde Êeö?
{129782}{129878}Daj meni da vozim.|- Zaöto mi nisi rekao, ranije?
{129930}{129996}Naravno da je postavio|bombu u tu ökolu.
{130000}{130064}Zaöto?|- Da bi dobio tvoju potpunu paûnju.
{130172}{130220}Zato. - Nai kutiju sa osiguraËima.|- äta?
{130264}{130302}Gde je kutija sa osiguraËima?
{130306}{130364}Izvadi osiguraË za koËioni sistem.
{130368}{130428}Koji je?|- Izvadi ih sve.
{130432}{130533}Sagni glavu.|Sagni glavu jebote.
{130537}{130629}Sluöaj, drûi se jebote.
{131255}{131335}äta se desilo?|- Imaö li trostruku A kartu.
{131361}{131419}Nastavite dalje, nastavite dalje.
{131423}{131483}Portir upravo zadnji put|pregleda zgradu.
{131939}{131984}Hvala, G-o Martinez. Hajde.
{131988}{132068}Trojke i devetke su divlje.
{132072}{132116}Sagni se!
{132344}{132388}O, ËoveËe!
{132464}{132506}äta to radiö?|- Ispitujem ga.
{132510}{132554}äta Êe da ti kaûeMrtav sam?
{132558}{132600}NeÊu znati dok ga ne pitam.
{132604}{132684}Vidi ima li aspirina|u odeljku za rukavice.
{132712}{132764}Nema öanse. Ti vidi.
{132892}{133020}Deset novËiÊa. I tip u kamionu je|imao isto deset novËiÊa.
{133023}{133087}Moûda su imali meunarodne pozive.
{133144}{133209}Ne. to je za naplatu. Za mostarinu.
{133262}{133390}Dole! Dole! Na öleperu, kamioni!
{133430}{133483}Sranje, veÊ su ih ukrcali na brod.
{133536}{133640}A obalska straûa?|- TrebaÊe im 1 sat da dodu ovamo.
{133684}{133748}Moûemo da skoËimo!|- äta?
{133752}{133817}Ima 100 stopa do palube.|- Ali ne do krana.
{133822}{133887}Kablovi bi te presekli na pola.
{133917}{133960}Ja to mogu.|- Ne seri, sii dole.
{133964}{134016}Potraûi rukavice u kolima.
{134108}{134183}äest zamki,|Ëetiri Êorsokaka
{134187}{134252}i rupa u jabukovom drvetu.
{134355}{134456}Dobro, lutko...|hajde da igramo.
{134460}{134494}Sad Êemo da se trkamo.
{134498}{134546}Kad kaûem sad trËite kao ludi.
{134550}{134655}Pratite policajca i vatrogasca.
{134659}{134711}Voltere, postajemo tenki s vremenom.
{134715}{134800}Ne, joö Ëekamo. Meklejn joö uvek|moûe da nae öifru.
{134857}{134937}ZakaËi ga za kran.|- Baö tu.
{134941}{135012}Dobro je.
{135016}{135071}Za ovo Êe trebati Ëudo.|- Drûi mi fige.
{135129}{135212}Imaö ga skoro. Da, dobro je!
{135236}{135315}Gde se ûuriö?|- Idem prvi ovaj put.
{135353}{135419}Imamo internu komunikaciju, gospodine.
{135423}{135523}Voltere, deca su moûda dobro|ali ako i dalje Ëekamo, upiökiÊu se.
{135527}{135571}»ekaÊemo, Koni.
{135599}{135643}Joö 6 minuta.
{135994}{136063}Meklejn. Dole.
{136292}{136365}Sranje! Hajde! Poûuri!
{137059}{137117}»oveËe, drago mi je öto si|me odgovorio od skakanja.
{137801}{137845}Uhvati njegove noge.
{138087}{138136}Dodi da vidiö neöto.
{138140}{138171}Kasnije.
{138200}{138277}Vaûno je.|- Kasnije.
{138281}{138333}Ne, sad!
{138386}{138428}Ovo je u kontejneru.
{138836}{138909}NaÊi Êu Sajmona, odvesti ih do|obale i izvuÊi Êu öifru od njega.
{138914}{138956}Uzmi ovo.
{138961}{139002}Kako to radi?|- Ne znaö da pucaö iz oruûja?
{139006}{139073}Ne znaju sva braÊa kako se puca|iz oruûja ti rasisto.
{139077}{139176}Tuûi me. Samo povuci to i pucaj.|- To je sve.
{139179}{139263}Da, samo nemoj da raniö sam sebe.
{139266}{139340}I ne budi heroj.|Ako ga naeö zovi me.
{141060}{141102}Glupane! - Jesi li podesio|auto pilota? - Da.
{141284}{141340}Ne mrdaj se.
{141466}{141555}O, samariÊanin.|- Daj prokletu öifru.
{141560}{141667}äifru? Misliö za ökolu?
{141671}{141718}Izvini, ali ne mogu.
{141722}{141774}Predaj öifru na radio|ili Êu te 
{141778}{141850}poslati na drugi svet.
{141894}{141930}Ako to moraö da uradiö.
{142240}{142332}Moraö da ga otkoËiö prvo.
{142336}{142410}Sad radi. Gde je Meklejn?
{142828}{142872}Ne pucaj!|- äta si rekao?
{142969}{143015}Reako je:"Ne pucaj".
{143021}{143116}U redu »arli, krenuÊemo|sa evakuacijom.
{143120}{143184}»uli ste Ëoveka! Idemo!
{143228}{143366}Na moj znak. 5, 4, 3, 2, 1! Idemo!
{143430}{143514}Hajde! Brzo!
{143518}{143588}TrËite! TrËite!
{143592}{143630}PobediÊemo! PobediÊemo!
{144137}{144230}Gledaj, öta rade?|Hej, gde Êete?
{144234}{144318}Gledam te ceo dan,|mali ËoveËe. PolicajËe.
{144355}{144419}I nikako da odeö.
{144422}{144471}Da ja sam taj jebeni energetski zeka.
{144534}{144567}A, gde Êeö sad?
{144649}{144726}HoÊeö da me uhapsiö, zeko?
{144788}{144827}NeÊu te uhapsiti.
{144849}{144906}VeÊ Êu te...
{145154}{145205}Znao sam da je sranje. Niko nije gledao.
{145208}{145290}Vreme je da izvuËemo »arlija.|Vreme je isteklo »arli. Izlazi.
{145295}{145334}Daj mi joö 30 sekundi.
{145337}{145388}TrebaÊe ti minut i 15 ako si dete.
{145391}{145449}Zadnji put kad sam te video, nisi bio|lak na nogama! Izlazi!
{145479}{145541}Moj boûe!
{145582}{145672}Izvadite ih odatle!|- UËionice su zakljuËane! - Beûite!
{145713}{145825}Bilo koji sa brojem 4!
{145829}{145872}äta se deöava, Voltere?
{145876}{145933}Joö uvek ima dece u zgradi.
{146053}{146129}Ostajem.|- Ne. Izlazi odatle.
{146170}{146237}Jesi li gledao Porodicu Adams?
{146241}{146306}Imaju tipa koji se zove LurË?
{146310}{146363}Misliö da Êu te pustiti|da doeö do piötolja?
{147035}{147083}4...4 ma do avola!|Sklonite se!
{147377}{147437}Gde su, Voltere?|- Joö uvek unutra.
{147593}{147649}Bez hrabrosti nema slave.
{147718}{147793}Ako doemo do krova moûemo|da skoËimo na drugu zgradu.
{148013}{148103}SOS! SOS! Obalska straûa.|Prijem.
{148576}{148640}Hajde, deco! Sranje, predaleko je!
{148801}{148849}Bez hrabrosti nema slave.
{148853}{148899}Jebeno veliki brod.
{148903}{148965}Ostanite na liniji.|- Da, ostaÊu.
{149398}{149453}Sirup za palaËinke.
{149470}{149625}Glupane, glupane.|- Zdravo Dûone Meklejn.
{149661}{149709}Nije bilo bombe u ökoli.
{149713}{149834}Ne. Ja sam vojnik,|a ne monstrum.
{149838}{149910}Mada neki put radim|za monstrume.
{149914}{149982}Prava bomba je na ovom brodu.
{150086}{150146}Obalska straûa.
{150150}{150230}Rekao sam im gde je brod.
{150234}{150351}Igra je gotova?|- Ne joö.
{150355}{150429}Obalska straûa, prijem.
{150433}{150546}Stave te na Ëekanje?|- Rekla mi je da ostanem na liniji.
{150659}{150690}Boûe, oboûavam ovu zemlju.
{150694}{150734}Znaö, tvoj brat je bio seronja.
{150801}{150888}U pravu si. Bio je seronja.|Sredio si ga.
{150995}{151085}Izvini. Pomognite|Meklejnu da sie dole?
{151122}{151166}Paûljivo sad.
{151206}{151289}Sad, imaö li komunikaciju?
{151293}{151336}Obalska straûa, prijem.
{151340}{151383}Obalska straûa.|- Jesi li tu, draga? - Da.
{151387}{151481}Moûeö li da snimiö poruku? - Da.
{151484}{151532}PoËni sad, molim te.
{151693}{151771}Ovo je poruka od CRF.
{151775}{151863}Dugo je zapad krojio zaveru|da ukrade bogatstvo sveta...
{151867}{151911}remeteÊi balans|ËoveËanstva
{151916}{151943}do ekonomske gladi.
{151947}{152014}Danas, Êemo to nivelisati.
{152018}{152094}Za nekoliko minuta, sadrûaj|banke federalnih rezervi, 
{152098}{152167}zlato, na kojem|poËiva vaöa ekonomija, 
{152171}{152235}biÊe rasprostranjeno,|eksplozivom, 
{152239}{152285}po dnu Long|ostrva.
{152325}{152409}Ako ste u vidokrugu,|doite da gledate.
{152528}{152601}Sve Êeö da digneö u vazduh?
{152605}{152649}To je ideja.|Neka gospoda na srednjem istoku
{152653}{152717}misle da Êe tako|zaraditi dosta novca.
{152721}{152808}Potrudi se da ljudi odu bezbedno|s broda. Vidimo se kod lansiranja.
{152836}{152896}Kakve ovo ima veze sa|ubijanjem Meklejna?
{152936}{152989}éivot ima svoje male bonuse.
{152993}{153049}Zar nisi rekao da Ëak|i ne voliö svog brata?
{153053}{153104}Postoji razlika u nedopadanju|i nemarenju kad ga neki
{153108}{153192}glupi irac sa ravnim tabanima|baci s prozora.
{153196}{153242}Ja nisam ni poznavao tog kretena.
{153246}{153300}Ja te nisam ni pozvao na|ovaj brod.
{153304}{153412}Nema zagonetke koja Êe da zaustavi ovo sranje?|- Nema öifre, zagonetke ili odbrojavanja.
{153416}{153504}Hej, kretenu. Da, ti kretenu.
{153541}{153605}Moram da znam samo jednu stvar.
{153608}{153741}Imaö li aspirina?|Imao sam uûasnu glavobolju ceo dan.
{153812}{153924}Mora da je tvoj sreÊan dan.|Zadrûi boËicu.
{154221}{154376}Gde je zlato?|Preöao nas je.
{154380}{154444}Kontejneri su puni|ovoga.
{155226}{155281}Da nisam spasao tvoju bulju
{155285}{155340}ne bih sedeo ovde ËekajuÊi da poginem|sa 100 milijardi dolara.
{155344}{155448}Imam loöe vesti za tebe. EksplodiraÊeö|samo samnom. Nema zlata na brodu.
{155452}{155522}Kako znaö?|- Poznajem mu porodicu.
{155526}{155609}Jedina bolja stvar od uniötavanja|100 milijardi dolara
{155613}{155671}je da nateraö ljude da|pomisle da si to uradio.
{155675}{155727}Gde je onda? - Ne znam,|mora da je zamenio negde, na doku.
{155731}{155786}I to Êe me naterati da se bolje oseÊam?
{155790}{155841}Ne, neÊeö umreti, takoe.
{155845}{155919}Znaö neki policijski trik|sa lisicama da se izvuËemo odavde?
{155923}{155985}Da, upotrebi kljuË.
{155989}{156019}Jel znaö da obijeö ovu bravu ?
{156023}{156057}Jel to opet neöto na raËun crnaca?
{156061}{156108}Jesi li jebeni bravar ili nisi?
{156112}{156174}Treba mi neöto s|Ëim bih mogao.
{156178}{156228}äta kaûeö na ovo parËe kabla?
{156232}{156252}Moglo bi.
{156324}{156380}»ekaj.|- äta radiö jebote?
{156460}{156550}Sranje! Jel moûe ovo? Da li je|dovoljno veliko?
{156554}{156604}Da, moglo bi da uspe.
{156608}{156681}IspustiÊu ti u tvoje ruke.|Skupi ruke.
{156685}{156768}Nemoj da ga ispustiö.|Jesi li spreman ?
{156772}{156856}1, 2 pljuni. - Da!|- Jesi li uhvatio?
{156860}{156940}Pomeri ruke.
{157006}{157061}Do avola Meklejn|tek si poËeo da mi se dopadaö.
{157066}{157158}Nemoj. Ja sam seronja|- Zaöto?
{157161}{157225}Slagao sam te.|- Oko Ëega?
{157229}{157298}SeÊaö se kad sam rekao da je Vajs|naöao onu bombu u Harlemu? - Da.?
{157301}{157416}Naöao je u kineskoj Ëetvrti.|- To je bilo nisko.
{157419}{157477}»ak i za belca kao ti.
{157482}{157594}äta je to bilo?|- Ne znam.
{157598}{157646}Sluöaj, to je bio jedini naËin da te|nateram da podeö samnom.
{157651}{157780}Jesi li oûenjen, Meklejn? - Da. »udi me|da bi neko ostao s tobom dugo da se oûeni.
{157783}{157858}Nije ostala,|nekako smo razdvojeni.
{157863}{157898}äta ti to znaËi nekako razdvojeni?
{157902}{157971}Ona je bila u L.A. Ja sam bio u Nju Jorku|Posvaali smo se preko telefona.
{157975}{158062}Ona je zalupila sluöalicu.|Nisam je zvao od tada.
{158066}{158146}Koliko je proölo od tada?|- Oko godinu.
{158235}{158299}äto se smejeö?
{158303}{158393}Bacio si svoj brak zato öto si|bio isuviöe glup da podigneö sluöalicu??
{158397}{158496}Misliö da je to smeöno? Smejeö se tuoj nesreÊi.|- Kladim se da okrivljujeö svoju ûenu, takoe...
{158500}{158551}Moja ûena je veoma tvrdoglava ûena.
{158621}{158680}Prestani da se smejeö i|otkljuËaj ove lisice!
{158684}{158734}Skoro sam uspeo!
{158738}{158797}A, kakva koncetracija? Sranje!
{158801}{158839}Ispustio sam ûicu! Prokletstvo!
{158910}{158965}Gde je?|- Nai je.
{158969}{159033}Ne vidim je!
{159060}{159133}äta je to bilo?
{159137}{159194}Mislim da sam, je naljutio.
{159198}{159234}Idi meklejn, beûi odavde!
{159238}{159316}Moram da uradim neöto!|- Do avola, Meklejn, sluöaj me!
{159347}{159393}Idi.
{159397}{159481}NeÊu da mi proe ovaj dan sa|tvojom smrÊu na savesti.
{159485}{159541}Sad Êuti i smisli neöto.
{159545}{159596}Alat. Proveri sobu sa|motorom. - Nema vremena!
{159627}{159644}äta sad radi?
{159648}{159693}Sranje! Meöa se!
{159751}{159868}äta to radiö?|- Nagni se unapred.
{159872}{159966}Sad Êe brzo da ide.|Nagni se unapred.
{160067}{160152}Sranje! Sranje! Jebote!
{160205}{160251}Hajde! Hajde!|- Jebote! Moja noga!
{160266}{160368}Penji se! Idemo, idemo!
{160415}{160500}Sranje! Moja noga.
{160550}{160599}TrËi, proklet bio!|- TrËim!
{160603}{160645}Jesi li dobro? Pazi. SkaËi!
{161396}{161429}Kako je on?
{161433}{161504}Ranjen sam u nogu.|äta misliö kako sam?
{161508}{161538}BiÊe u redu.
{161542}{161566}A ti?
{161570}{161728}Dobro. Jeste li izvadili Rikija odande?|- Da, naöli su ga.
{161765}{161833}HoÊeö li biti dobro?|- Imam uûasnu glavobolju.
{161837}{161910}Misliö da su ljuti na mene? - Ne bih|se brinuo za njih. DoÊi Êe do tebe.
{161914}{161998}Trenutno su zauzeti|operacijom spasavanja.
{162002}{162079}Otpatci! Otpatci!
{162083}{162153}Nema zlata dole.|- äta priËaö?
{162157}{162207}Odneo ga je sa sobom.|Pobedio me je.
{162211}{162299}Dûone pobedio nas je sve.|- Nije igrao protiv svih vas.
{162303}{162395}Zajebi to, Meklejn! Joö uvek si|ûiv, zar ne?
{162399}{162477}Zar nisi?
{162481}{162545}ZnaËi, on je izgubio.
{162548}{162609}Daj mu novËiÊ, Lamberte.
{162613}{162651}Seronjo.
{162757}{162796}Da, na moj raËun.
{162985}{163059}Reci samo da Êeö prihvatiti,|raËun Karmen.
{163063}{163131}KuËkin sin je imao aspirin!
{163136}{163239}Da ovde Dûon. Da li je Holi tu?|SaËekaÊu.
{163642}{163681}Zevse, saËekaj!
{163686}{163795}Dûone? Dûone, proklet bio...
{164504}{164601}JuËe smo bili vojska|bez drûave.
{164605}{164684}Sutra Êemo morati da odluËimo
{164712}{164769}koju zemlju ûelimo da kupimo!
{164889}{164978}I zapamtite, ovo je sve|zbog
{164982}{165057}gluposti
{165061}{165112}Njujoröke policije.
{165158}{165187}Za Njujoröku policiju!
{165204}{165248}Za pale drugove!
{165476}{165503}Za drugove!
{165858}{165907}PoruËniËe, preuzmi.
{165911}{165976}Prvi vod, morate biti u|ökolskom autobusu
{165980}{166021}za 30 minuta.
{166062}{166148}Avion je u Novoj äkotskoj.|Moûemo biti tamo za 20 minuta.
{166351}{166388}Bez ûurbe.
{166392}{166485}Jurgen, ti Êeö biti pop.|- Pop?
{167097}{167141}Svetla! Ugasite svetla!
{167526}{167652}{Y:i}SEVERNA GRANICA|NAJVE∆A STANICA ZA KAMIONE U KVEBEKU
{167692}{167726}Hej kretenu!
{167730}{167789}Jel sam doöao u loöe vreme?
{167918}{167993}Mislim da je ljuta na tebe, Meklejn.
{168493}{168591}Idi, ispod nas je sad. Okreni ponovo,|Zevse, öta je na tvojoj strani?
{168595}{168639}Izgledaju kao buba-övabe sa svetlima.
{168702}{168791}Zar ne idemo u Novu äkotsku?|- Idite s kamionom.
{168796}{168849}Ja imam neöto liËno da zavröim.
{168920}{168964}Idemo na posao.
{169288}{169367}Tako je! TrËite, seronje!|Eksterminatori su ovde!
{169647}{169751}äta do avola? Sranje!|Helikopter je iza nas!
{169755}{169821}Dim je za nama!|Imaö li oruûje?
{169824}{169878}äta je ovo?
{169948}{170013}Drûi ga mirno!|Ne mogu niöta da vidim!
{170109}{170173}Sranje!|- äta sranje!
{170259}{170301}Drûite se. Idemo dole.
{170305}{170349}Pazi na kabl!
{170353}{170411}Meklejn, öta do avola?
{170460}{170541}Puni smo dima,|sranje leti po meni!
{170611}{170657}Kamion!|- Drûite se.
{170812}{170899}Moramo da idemo odavde.|Uskoro Êe poËeti da pucaju.
{170903}{171036}Ne mogu da otkaËim pojas!|- Pazite! Evo ga ide!
{171040}{171161}Ne mogu da izaem, Meklejn .|- Izvadi ga odatle.
{171165}{171254}Gde Êeö ti?|- Idem da mu privuËem paûnju.
{171685}{171774}Sranje. Sve je bolje i bolje.
{171908}{171992}Nisam znao da u Kanadi|moûe biti ovako zabavno.
{172116}{172177}Daj mi neöto u|öta Êu da pucam.
{172205}{172258}Hajde, daso. Pokaûi mi|to nasmejano lice.
{172771}{172816}Pozdravi tvog brata.
{172867}{172906}Beûi odavde!
{173293}{173371}Jipi-ka-jej, seronjo.
{173447}{173523}Izgleda da si mu privukao paûnju.|- Izgleda tako.
{173583}{173664}Moûda bi trebalo da pozovemo vatrogasce?|- Ma, ko ih jebe. Nek' se prûe.
{173729}{173805}Sranje!|- äta je?
{173843}{173919}Ostavio sam Holi da Ëeka na vezi.|- Pozovi je ponovo.
{173955}{174064}Ne znam Zevse. BiÊe veoma ljuta.|- PreÊi Êe preko toga.
{174068}{174132}Ne znam, Zevse.
{174156}{174259}Kao öto sam ti rekao, ona je|veoma tvrdoglava ûena.
{174263}{174324}Mora da jeste Ëim je|udata za tebe.
{175145}{175330}Pripremio >>> SLAY
{175355}{176855}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
