{1}{1}25.000
{26}{176}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{4392}{4464}Koja masa!|To su studenti!
{4556}{4606}Pustite ih unutra.
{5067}{5161}BALET LERMONTOV|VATRENO SRCE
{5731}{5794}Sediö mi na kaputu!
{5843}{5891}Vreme je za sendviË!
{5949}{6055}45 MINUTA KASNIJE
{7088}{7136}Nigde ga ne vidim.
{7137}{7213}Program? -Dva molim.|- Jedan ovde.
{7214}{7257}Hvala, drugar.
{7316}{7409}Muziku je napisao Palmer.|Bolje da bude dobra.
{7429}{7537}Teöko da bi Boronskaja|plesala glavnu ulogu da nije.
{7605}{7666}Ko je ta Boronskaja?
{7673}{7759}Poöto si Ëekao 6 sati u redu|da je vidiö kako igra...
{7760}{7845}Nisam Ëekao da bih video|bilo koga, veÊ da bih sluöao.
{7867}{7918}Jeste li ikada Ëuli za|profesora Palmera?
{7920}{7987}Nikada. -Nikada.|- »uÊete.
{8002}{8104}U programu piöe, muziku|napisao Endrju Palmer.
{8105}{8158}To je naö profesor|sa Akademije.
{8159}{8231}Zato ta vaöa, kako se zove,|bolje da bude dobra.
{8232}{8310}Teöko je zamisliti da bi mogla|da bude bilo öta drugo.
{8519}{8576}Eno ga! Palmer!
{8590}{8639}Palmer!
{9385}{9432}Mi ga poznajemo.
{10954}{11024}SeÊaö li se moje rapsodije?|- Zaboravi.
{11025}{11075}Da! To je tvoja rapsodija.
{11081}{11138}Pokazao si mu je?|- Naravno.
{11143}{11224}Ne misliö valjda da ju je|ukrao? -Naravno da ne.
{11710}{11783}IZABELA,|KONTESA OD NESTONA
{11791}{11845}DRAGI, PROFESORE|PALMER,
{11846}{11928}POZVALA SAM NEKE LJUDE|POSLE PREDSTAVE.
{11930}{12011}PRIDRUéITE NAM SE|I POVEDITE G. LERMONTOVA.
{12806}{12887}Ona je veliki pokrovitelj|umetnosti.
{13144}{13171}Viki!
{13233}{13267}Viki!
{13570}{13597}Viki,
{13628}{13678}Lermontov Êe doÊi.
{13944}{14016}Hej! I ovo je tvoje,|zar ne? -Da.
{15674}{15730}äta Ëekate!
{15974}{16026}Dozvolite, molim.
{16427}{16535}Profesore Palmer!|Veoma smo ponosni na vas!
{16537}{16570}Hvala, konteso. Kontesa|od Nestona, g. Lermontov.
{16575}{16647}KonaËno da upoznamo|ovog velikog Ëoveka.
{16648}{16737}Nisam mislila da Êu uspeti|da vas dovedem ovamo.
{17035}{17109}Ako Êe neko da nam peva|moraÊu da odem.
{17119}{17167}Ne podnosim amatere.
{17169}{17202}»ak i kada se deöava|kod lejdi Neston?
{17206}{17223}äta hoÊeö da kaûeö?
{17230}{17330}Mislim da ima roaku|balerinu, profesionalnu.
{17495}{17605}G. profesore, molim vas|sedite, g. Lermontov.
{17667}{17736}Da li ste spremni|za iznenaenje?
{17737}{17824}Mislite iznenaenje ili öok,|lejdi Neston?
{17828}{17927}BiÊu direktna. Zamolila sam|roaku da nam neöto odigra.
{17959}{18041}äta kaûete na to?|- äok.
{18088}{18157}Veoma ste iskreni.
{18164}{18246}Znate, ne bih se usudila|da vam dosaujem
{18247}{18305}i predstavim nekog|amatera.
{18308}{18400}Moja roaka veÊ dugo|pleöe glavne uloge.
{18403}{18484}KritiËari imaju veoma|pozitivno miöljenje o njoj.
{18487}{18569}Kako biste definisali|balet, lejdi Neston?
{18609}{18694}Pa, mogao bi se nazvati|ËiöÊenjem emocija.
{18695}{18778}Moûda. Ali za mene je|balet mnogo viöe.
{18792}{18855}Za mene je to religija.
{18857}{18944}»ovek ne bi baö voleo da|vidi izvoenje religije
{18950}{19002}u sredini,
{19013}{19056}kao öto je ova.
{19072}{19137}Nadam se da me|razumete.
{19189}{19254}PrivlaËni divljak!
{20153}{20229}äampanj koktel, molim vas.|- U redu.
{20230}{20306}äampanj koktel, molim.|- Da, gospoice.
{20392}{20475}Na ovakvoj zabavi oËekuje|se da svi budu sreÊni.
{20575}{20662}Moûda se vama ne svia,|isto koliko i meni?
{20669}{20750}Ali, mislim da bi moglo|biti i gore. -Mislite?
{20755}{20827}Ustvari, bilo je jako blizu.|- Stvarno?
{20830}{20860}Hvala.
{20864}{20944}Trebalo je da nas poËaste|malom predstavom plesa.
{20960}{21039}Ali razumeo sam da Êe me|poötedeti tog uûasa.
{21040}{21132}G. Lermontov,|ja sam taj uûas.
{21257}{21373}Malo je kasno za izvinjenje,|zar ne? -Da, malo je kasno.
{21391}{21451}éao mi je.|Straöno mi je ûao.
{21457}{21490}Ali vam nije ûao öto nisam|plesala, zar ne?
{21515}{21560}Smem li da pitam zaöto?
{21561}{21639}Zato öto sam draga moja|gice... -Viktorija Pejdû.
{21640}{21718}Gice Pejdû, ako prihvatim|poziv da doem na zabavu,
{21719}{21789}onda ne ûelim da|prisustvujem audiciji.
{21841}{21903}Da. U pravu ste.
{21975}{22037}Zaöto ûelite da pleöete?
{22104}{22162}Zaöto vi ûelite da ûivite?
{22182}{22232}Ne znam taËno zaöto,
{22240}{22300}ali moram.
{22312}{22371}To je i moj odgovor.
{22468}{22554}Poite sa mnom. -Gde?|- Da popriËamo.
{22558}{22646}Ali ja to ne ûelim.|- Ne brinite, ja Êu govoriti.
{22988}{23053}Recite mu da hoÊu|da me primi.
{23057}{23129}äta je, Dimitri? -Neki|mladiÊ po imenu Kraster.
{23130}{23216}Dolazio je sto puta i i sto puta|sam mu rekao da spavate,
{23217}{23266}ali mi nije poverovao.
{23267}{23357}Loöe laûeö, a g. Kraster ima|dobar oseÊaj za to.
{23358}{23409}Uvedi ga.
{23482}{23541}Gospodin Kraster!
{23955}{24066}äta mogu da uËinim za vas?|- éao mi je öto vam smetam,
{24069}{24139}ali radi se o veoma|vaûnoj stvari.
{24155}{24267}Da? -SinoÊ sam vam napisao|pismo. Glupo pismo.
{24272}{24320}éeleo bih da mi ga vratite|pre nego öto ga proËitate.
{24340}{24374}Razumem.
{24470}{24513}To je to!
{24547}{24638}Naûalost,|veÊ sam ga proËitao.
{24724}{24832}G. Lermontov, molim vas!|- Vi ste uËenik prof. Palmera?
{24836}{24936}Napisali ste delo za gudaËki|kvarter i koncert za klavir.
{24942}{25002}Da. -Veoma interesantno.
{25028}{25122}HoÊete mi odsvirati neöto?|Neöto vaöe, mislim.
{25162}{25219}Naravno, ako to ûelite.
{25510}{25585}Ovo je studija koju sam|napisao za klavir.
{25705}{25783}Ali mislim da je preradim|u operu.
{26673}{26744}VeÊ ste zavröili?|Veoma interesantno.
{26765}{26842}Nadam se da vam nisam|pokvario doruËak!
{26849}{26955}Uzgred, treba mi novi|voa orkestra.
{26967}{27041}Interesuje vas? -Ja...
{27062}{27197}Ne mogu da platim puno.|8 funti nedeljno i troökovi.
{27263}{27309}FantastiËno!
{27344}{27396}Onda doruËkujte i doite|u Kovent Garden.
{27412}{27436}Hvala.
{27442}{27517}Vaöe pismo, g. Kraster.
{27610}{27662}Ako hoÊete moj savet,
{27724}{27777}uniötite ga i zaboravite.
{27897}{27970}Vatreno srce je vaö rad,|zar ne?
{28007}{28088}Ovakve stvari se dogaaju|uglavnom nenamerno.
{28089}{28170}Znam, zato...|- Zato vredi upamtiti,
{28176}{28324}da je veÊa sramota morati|ukrasti, nego da ti ukradu.
{28417}{28451}Dovienja.
{29290}{29349}Svakako da Êu pokuöati.|Zbogom.
{29374}{29416}Izvoli, sine.
{29429}{29468}Hej, izvinite!
{29486}{29550}Da li se ovuda ide na|pozornicu? -Ime?
{29551}{29635}Dûulijan Kraster.|- Kako? -Dûulijan Kraster.
{29659}{29712}Vaöe ime nije na spisku.
{29878}{29947}Vodim li kuËe? -Da.
{29954}{30051}Imam zakazano. -éao mi je,|ja samo radim svoj posao.
{30062}{30137}Dobro jutro, éorû.|- Dobro jutro, madam.
{30142}{30278}Kako je madam, éorû?|- Veoma, veoma ljubomorna.
{30285}{30370}Zbog one fotografije.|SeÊate se?
{30402}{30465}Irina, traûe te od jutros|po celom Londonu.
{30467}{30502}Odselila sam se.|- To sam i ja rekao.
{30506}{30583}Koliko Êu joö dugo Ëekati?|- Poslao sam po nekog.
{30584}{30690}Vaöe ime, mladiÊu?|- Dûulijan Kraster.
{30700}{30762}Imam sastanak|sa g. Lermontovim.
{30768}{30838}Dûulijan Krajst... -Kraster.
{30850}{30965}éorû, ako ga je Lermontov|pozvao treba da ga pustiö.
{30985}{31088}U redu, madam.|U redu, öto se mene tiËe.
{31092}{31147}Poite za mnom,|mladiÊu.
{31264}{31360}Da li ste vi plesaËica?|- Da. NoÊna.
{31393}{31433}Ne znam mnogo|o baletu.
{31435}{31518}Vi ste umetnik?|- Da. Kompozitor.
{31584}{31677}I ûelite da vidite, koga?|- Nisam siguran...
{31683}{31728}Svi su tamo.
{31935}{32009}Izvinite, ko je ovde glavni?|- Ima ih petorica,
{32010}{32062}öestorica koji misle|da jesu.
{32063}{32100}Izvinite, znate li ko je|ovde glavni?
{32102}{32165}Ne pitajte mene, mladiÊu.|Ja sam samo neËija majka.
{32168}{32215}To ovde ne znaËi niöta.
{32343}{32428}Moûete li mi reÊi ko je ovde|glavni? -Glavni za öta?
{32463}{32541}G. Lermontov mi je rekao|da doem. -Zaöto?
{32547}{32622}Angaûovao me. -Ne kao|igraËa, nadam se. -Ne.
{32833}{32904}G. Ljubov ûeli da se|ovo ukloni.
{32910}{33042}Ostaje na pozornici.|- U redu, ako vi tako kaûete.
{33196}{33275}Aha! Dolazi velika|Boronskaja.
{33300}{33381}Danas kasni samo|43 minuta!
{33418}{33487}Da li treba sam da|veûbam tvoj deo?
{33545}{33621}Mom strpljenju je kraj!|Idem kod Lermontova
{33622}{33704}da mu objasnim zaöto ne|moûe da nas zadrûi oboje!
{33740}{33780}ZnaËi, mogu da poËnem|da se pakujem.
{33783}{33887}Ne ûuri! Moûda Êe odluËiti da mu|moje usluge viöe nisu potrebne.
{33889}{33930}Dovoljno je lud!
{33935}{34025}Ako idemo, idemo zajedno,|dragi. ObeÊavaö?
{34100}{34178}Ko ste vi? -Viktorija Pejdû.|Nadam se da vam je
{34184}{34265}g. Lermontov priËao o meni.|Pozvao me je.
{34266}{34312}Ovo je previöe!
{34313}{34364}On ih poziva, ja ih uËim.
{34365}{34434}Ja ih otpuötam,|on ih zaboravlja!
{34445}{34560}NesreÊna devojko, sad idite|u onaj Êoöak gde Êete naÊi
{34565}{34730}joö 5 devojaka kojima|je on ukazao gostoprimstvo.
{35015}{35063}Tiöina, molim!
{35153}{35236}éelim da probamo 1. Ëin|Vatrenog srca.
{35245}{35325}Oni koji ne uËestvuju neka|odu sa pozornice, molim.
{35487}{35567}To je sve?|Dobro, slaûem se.
{35630}{35682}Kuda, draga moja?
{35684}{35750}Da razgovaram|sa g. Lermontovim.
{35751}{35831}Zar ne bi trebalo da saËekate|da se zavröi proba?
{35835}{35911}U redu je.|Ja ga liËno poznajem.
{35916}{35970}E, to je veÊ neöto drugo.
{35973}{36028}Borosof! -Da, Boris?
{36031}{36101}Neka ostane tamo.|DoÊi Êu gore.
{36315}{36374}Dobro jutro, g. Lermontov.
{36415}{36501}Moramo uËiniti|neöto sa tim.
{36506}{36543}Devojke su sinoÊ jedva|imale mesta da se kreÊu.
{36546}{36600}Ljubov je ipak u pravu.|- Aha, Ljubov...
{36605}{36663}Znamo da je on uvek|u pravu.
{36664}{36769}Stvarno tako misliö? -Da.|- Pa, dobro. Odnesite ga.
{36955}{37037}Vidite, draga moja,|g. Lermontov je vrlo zauzet.
{37058}{37155}Idite tamo i Ëekajte|sa ostalima.
{37226}{37264}Da, i hoÊu.
{37270}{37328}Sergej SergejeviË! -Da?
{37330}{37411}Poznajete li Dû. Krastera,|kompozitora i dirigenta,
{37414}{37492}ili neko njegovo delo?|- Ne. -Ni ja.
{37495}{37572}äto dokazuje da je öteta|öto nam oduzima vreme.
{37574}{37623}Evo ga tu, sa nama.
{37637}{37708}Lermontov ga je jutros|angaûovao.
{39079}{39130}Brzi pokreti nogom!|E!
{39926}{39996}»as zavröen!
{40021}{40095}Mislim da je dovoljno.|Hvala, gospodo.
{40130}{40180}I ostalim Ëlanovima orkestra|treba da posvetite paûnju.
{40200}{40232}Sutra.
{40235}{40275}ROJAL OPERA HAUS,
{40276}{40349}SPECIJALNI POZIV ZA SVE|»LANOVE ORKESTRA.
{40350}{40399}TA»NO U 9.30 h.|KRASTER.
{40582}{40671}Gospodo, ûao mi je öto sam|vas ovako rano okupio.
{40700}{40792}Ovo nije moj prvi susret s ovim|baletom, ali stvarno moram...
{40946}{41013}Jednu ili dve stvari|moramo ponoviti.
{41019}{41086}Vatreno srce, uvertira.
{41122}{41170}Od poËetka, molim.
{41203}{41253}Uzgred, trube.
{41286}{41393}Drugi deo, drugi red. Je li|kod vas obiËna E nota?
{41402}{41497}Ne. E mol.|- To je sasvim razliËito.
{41498}{41515}Treba da je obiËna E.
{41530}{41576}Od poËetka.
{41910}{41970}Gospodo, znam da je teöko da|pokrenete usta od ranog jutra,
{41973}{42025}ali moramo se truditi|zajedno.
{42026}{42112}Malo ujednaËenije.|PoËinju oboe.
{42300}{42347}IspoËetka, molim!
{43033}{43073}To je dobro!
{43077}{43128}G. Kraster!
{43133}{43198}äta se taËno ovde|dogaa?
{43203}{43252}Jeste li siöli s uma?
{43258}{43345}Je li vam jasno ako sazovem|orkestar jedan sat ranije,
{43351}{43411}da treba da ih ekstra|platim?
{43417}{43507}Zaöto veûbate Vatreno srce?|Jesam li to traûio od vas?
{43508}{43572}Pa... -Recite mi.|Baö me interesuje.
{43573}{43653}Siguran sam da Êe interesovati|i g. Lermontova!
{43689}{43780}Pa? -Svia mi se.|- Svia vam se?
{43788}{43873}Ne sumnjam da vam|se svia i Marseljeza!
{43879}{44009}Ali nisam Ëuo da je neko sazvao|orkestar u zoru da bi je uveûbao.
{44059}{44119}Lermontov,|preuzmi momka!
{44125}{44210}Uostalom on je tvoje|otkriÊe, ne moje.
{44213}{44290}G. Kraster, ubuduÊe kada|budete veûbali,
{44295}{44380}molim vas da malo viöe|kontroliöete svoje ambicije.
{44382}{44459}To, zaöto ste izabrali|da veûbate u zoru...
{44464}{44562}Dobro jutro gospodo,|ostaÊe i za mene misterija,
{44566}{44595}koju neÊu uspeti|da reöim.
{44615}{44675}Mogu li da vidim taj deo|sa pogreönom notom?
{44785}{44870}U Vatrenom srcu svakako|ima delova kojih niko
{44875}{44965}ne treba da se stidi.|- Hvala, g. Lermontov.
{45254}{45327}Dobro jutro g. ice Pejdû?|- Dobro jutro Edi.
{45328}{45397}Je li Lord Oldham sa vama?|- Jeste.
{45398}{45447}Pazite, gospoice.
{45505}{45598}Dobro jutro, Piter. -Zdravo, Viki.|- äta ti radiö ovde? -A ti?
{45599}{45661}Idem na ruËak|sa g. Lermontovim.
{45662}{45722}Znaö, momak koji|vodi balet.
{45723}{45765}Radi posla ili zabave?|- I jedno i drugo, nadam se.
{45770}{45847}äta ti radiö ovde? Ideö u öoping?|- Ne brini, Griöa.
{45848}{45903}DoveöÊu je nazad|u 3 sata.
{45957}{46025}Kako ste, madam?|- Kako ste, vi?
{46026}{46104}Zdravo, Piter. Nadam se|da nisi dugo Ëekao. -Ne.
{46108}{46190}Niste upoznali moju|prijateljicu. Viki Pejdû.
{46196}{46236}Drago mi je.
{46287}{46360}Da te povezem?|- Ne, hvala, Piter.
{46363}{46412}Izvinite, gice Pejdû.
{46474}{46533}Ko? Viktorija Pejdû?
{46580}{46652}Da. Moûe da igra.
{46790}{46983}MATINE, SUBOTA|VIKTORIJA PEJDé.
{49881}{49973}Dobro jutro, drage dame.|Nadam se da ste dobro.
{50001}{50069}éelim da vam kaûem|par stvari.
{50072}{50148}Kao öto znate balet|odlazi na turneju.
{50156}{50254}Bio bih oËaran kada bih|mogao sve da vas povedem.
{50274}{50354}Naûalost, to zadovoljstvo|mi je uskraÊeno.
{50360}{50448}Onima koje ne moûemo|da povedem, rekao bih ovo:
{50453}{50519}Nemojte da vas to|obeshrabri.
{50520}{50610}To öto vas ne vodimo,|ne znaËi da ste loöe balerine,
{50612}{50703}veÊ da, naûalost, ove godine|nemamo viöe mesta.
{50712}{50819}Molim vas istupite.|Gica Fejt, Bejli, Hardi i Lori.
{50977}{51002}Da.
{51003}{51083}Zahvaljujem vam na trudu.|Siguran sam da vam je
{51084}{51139}i g. Ljubov jednako|zahvalan.
{51165}{51246}Nadam se da Êemo|se opet sresti.
{51282}{51356}Viki, mislio je na nas!
{53648}{53681}Sluöajte!
{53715}{53765}Prijatelji moji.
{53773}{53828}Udajem se!
{53889}{53939}Drago moje dete.
{53946}{54012}éelim ti puno sreÊe.
{54219}{54323}Irina, draga! éelim ti sreÊu|sa novim partnerom.
{54329}{54414}Gde je Griöa? Griöa!|- Evo me Irina.
{54415}{54462}Dragi Griöa,|da li me mrziö?
{54463}{54564}Nikada te ne bih mogao mrzeti,|ali kako da ti ikada oprostim?
{54565}{54631}Mali moj. Znala sam|da Êeö mi oprostiti.
{54632}{54733}Nemoj da se svaaö s muûem,|kao öto si se svaala s Griöom.
{54734}{54814}Gde je Boris od jutros?|On nema niöta da mi kaûe?
{54829}{54865}Boris!
{54957}{55049}On nema srca.|Taj Ëovek!
{55987}{56021}Slobodno!
{56079}{56147}Kraster, imam posao|za tebe.
{56194}{56304}Dobro sam razumeo da do sada|nisi mnogo sreÊan s nama?
{56310}{56403}Pa... -Pa, öta? -äef orkestra|nije, baö, ono o Ëemu
{56409}{56477}sanja mladi kompozitor.
{56479}{56564}Bojim se da posao koji imam|za tebe, takoe nije san
{56565}{56640}mladog kompozitora.|Nadam se da ga neÊeö
{56642}{56739}smatrati potpuno|nedostojnim tvog talenta.
{56762}{56845}CRVENE CIPELICE, BALET|FILIPA BELTRANA
{56850}{56920}Balet Crvene cipelice je...
{57205}{57252}Izvinjavam se.
{57276}{57378}Balet Crvene cipelice pravljen|je po bajci Hansa Andersona.
{57403}{57482}To je priËa o devojci,|opsednutoj ambicijom
{57484}{57570}da igra u crvenim|cipelicama.
{57579}{57697}Odlazi da igra. Sve je dobro|i ona je veoma sreÊna.
{57727}{57782}Ali, uveËe se umori.
{57823}{57873}éeli da ide kuÊi,
{57906}{57973}ali crvene cipelice
{58008}{58056}nisu umorne.
{58060}{58125}One nisu nikada|umorne.
{58130}{58181}Igraju na ulicama,
{58214}{58259}preko brda,
{58261}{58317}preko dolina, po öumama,
{58321}{58369}noÊu i danju.
{58419}{58493}Vreme leti, ljubav leti,
{58526}{58580}ûivot leti,
{58620}{58702}ali crvene cipelice|igraju i dalje.
{58724}{58812}äta se desilo na kraju?|- Ona umire. -Da znam.
{58816}{58893}Muziku je napisao Bertran,|proöle godine,
{58894}{58956}na turneji po Juûnoj|Americi.
{58958}{59039}Ima loöih delova.|Obeleûeni su plavom bojom.
{59046}{59121}éeleo bih da vidim öta|moûeö da uradiö,
{59123}{59189}i da ih bukvalno|preradiö.
{59197}{59292}Imaö vremena. Bez ûurbe.|- Hvala.
{59306}{59392}»ekaju vas, g. Lermontov.|- U redu. Dolazim.
{60550}{60635}Pogledaj je. U odliËnoj|formi je veËeras.
{60645}{60721}Ne interesuje me u kakvoj|formi je, ni ona,
{60722}{60821}niti bilo koja prima balerina,|koja je toliko luda da se uda.
{60826}{60911}Daj, molim te.|- Ona je gotova, proölost.
{61039}{61103}Ne moûeö imati oboje.
{61109}{61197}IgraËica koju ponese sumnjiva|lagodnost ljubavi,
{61226}{61298}nikada neÊe biti velika.|Nikada!
{61577}{61685}To je bilo uglaeno, ali ne moûeö|promeniti ljudsku prirodu.
{61687}{61765}Ne? Mislim da moûe|i bolje da se uradi.
{61767}{61854}Moûe se ignorisati.
{62504}{62574}Boris... -Zbogom.
{62694}{62825}Dakle, Irina, sada Êeö moÊi|da spavaö koliko hoÊeö.
{62830}{62911}I da ideö na zabave|svake veËeri.
{62928}{63061}A ti Êeö biti miran.|»asovi neÊe kasniti.
{63067}{63156}NeÊe viöe biti galame.|NeÊe viöe...
{63161}{63252}NeÊe viöe biti, Irine.
{64105}{64144}Gice Pejdû!
{64174}{64223}Jeste li mnogo umorni?
{64229}{64299}Da, hoÊu reÊi, nisam.
{64309}{64410}Gospodine, predstavljam|vam Viktoriju Pejdû.
{64414}{64461}Direktor Opere.
{64475}{64562}Reûiser.|- Drago mi je, gospoice.
{64578}{64724}Bili ste u Monte Karlu?|- Da, proöle godine sa tetkom.
{64729}{64831}Onda znate hotel Pariz.|- Da, ali mislila sam da...
{64837}{64915}Hotel Pariz.|BiÊe vam udobno tamo.
{64980}{65036}DRAGA MOJA, G–ICE PEJDé,
{65041}{65118}NADAM SE DA STE|SLOBODNI VE»ERAS.
{65123}{65211}POSLA∆U KOLA PO VAS U 8.|BORIS LERMONTOV.
{65271}{65364}Kola g. Lermontova|vas Ëekaju, gice Pejdû.
{69053}{69115}ObuËeni ste kao da idete|na konferenciju. -Zdravo.
{69125}{69153}Pa, je li konferencija|u pitanju?
{69155}{69227}Da. Prepiru se unutra.|Ja sam ovde od 7.
{69272}{69323}Gice Pejdû, doite.
{69595}{69675}Upravo sam izlazila kad|sam dobila vaöu poruku.
{69989}{70097}Pozvao sam vas zato|öto spremamo novi balet.
{70122}{70243}OdluËio sam da vam dam|öansu da igrate glavnu ulogu.
{70259}{70335}Ali jednu stvar moram|odmah da vam kaûem.
{70341}{70450}Moje kolege ne veruju|u vaöe sposobnosti kao ja.
{70559}{70673}Ali, dodao bih ovo. Ma öta|da oni liËno veruju,
{70695}{70756}svi Êe vam pruûiti|pomoÊ.
{70761}{70815}Ostalo je na vama.
{70827}{70867}To je sve.
{70908}{70977}PoËinjemo sutra ujutro.
{70978}{71015}éelim da ne zaboravite|na svoju ulogu
{71017}{71050}i odete pravo na spavanje.
{71090}{71121}HoÊu.
{71246}{71275}Gice Pejdû?
{71360}{71414}SreÊno. -Hvala.
{71558}{71610}I? äta je bilo?
{71627}{71675}Dobila sam ulogu|u novom baletu.
{71677}{71774}Baletu?! Kom baletu?|Crvene cipelice!
{71853}{71952}Sluöajte ovo, g. Kraster!|To je nemoguÊe!
{71971}{72037}Ovaj deo nisam mogao ja|da napiöem, zar ne?
{72038}{72121}Zaöto da ne? -Niste ga obeleûili.|- Nije bilo potrebno.
{72122}{72166}Govori sam za sebe.
{72168}{72237}Ustvari, imao sam neke|ideje u vezi toga.
{72238}{72316}MladiÊu, potreban nam je|aranûman! -Dozvolite.
{72429}{72477}Ovo je scena za crkvu.
{72540}{72615}Koral na trgu.|ZvuËi otprilike ovako.
{72807}{72871}Zatim dolaze crkvena|zvona.
{73142}{73229}Svi gudaËki instrumenti.
{73309}{73391}Pojavljuje se sveötenik.|KreÊu duvaËki instrumenti.
{73567}{73640}Da vam odsviram ples|za cipele?
{73797}{73852}Hvala, g. Kraster.
{73965}{74010}Ovaj put ûelim|da promenite sve!
{74012}{74120}éelim novi aranûman!|- Izvolite.
{74155}{74236}A, gde je orkestracija?|- Kada je ûelite?
{74242}{74385}JuËe. NeÊu da vas vidim,|dok ne zavröite.
{74390}{74427}I neÊete!
{75025}{75109}Zaöto niste u krevetu?|- Uplaöili ste me.
{75133}{75185}To mi je i bila namera.
{75255}{75336}Dakle, zaöto niste u krevetu?|- Od velikog uzbuenja
{75337}{75408}nisam mogla da spavam.|Zato sam ovde.
{75409}{75478}Stvarno? -Video sam vas.|- Hvala.
{75479}{75529}Ali, vi niste videli mene.
{75530}{75606}I vama je naredio da|idete na spavanje?
{75611}{75707}Radim aranûman za moj|novi balet Crvene cipelice.
{75721}{75812}Da li je to i moj balet?|- Da. Mislim da jeste.
{76228}{76335}Kako li izgleda probuditi se|ujutro i shvatiti da si slavan?
{76345}{76417}Ti nisi osoba koja o tome|moûe dugo priËati.
{76455}{76520}SreÊno. -SreÊno.
{77770}{77867}Previöe se unosi u igru.|Zaöto joj ne kaûeö, Griöa?
{77868}{77916}Gledaj svoja posla.
{77930}{78017}Treba da pleöe sa mnom,|i to u deËijoj koöuljici.
{78022}{78124}Sa stilom. Ne moûe da|igra sve odjednom.
{78128}{78176}Trebalo bi to da zna.
{78177}{78250}OËekujeö da ona to zna,|Ivane IvanoviËu?
{78251}{78323}Zar nisi i ti nekad hteo|da pleöeö sve?
{78452}{78549}Doneo sam skice za kostime.|- Trenutak. Sedi.
{78683}{78758}Ljubov, treba neöto|uraditi sa muzikom.
{78760}{78859}Piruetu je poËela ranije.|- Tempo je prebrz.
{78866}{78958}To je pravi tempo.|- Naravno. Joö jednom!
{79123}{79270}BiÊe ona dobro. -Nadam se.|- Joö uvek sumnjaö, Sergej?
{79276}{79360}Ona je naravno, öarmantna|devojka, ali...
{79363}{79433}Ne znam niöta o njenom öarmu|i to mi je najmanje vaûno.
{79440}{79494}Ali kaûem ti,|neÊe Ëekati kraj.
{79495}{79585}Publika Êe joj aplaudirati|u sredini. -Ma, daj.
{79590}{79639}Zaöto? HoÊeö da se kladiö?
{79651}{79683}Dosta! Dosta!
{79725}{79845}Gice Pejdû, pokuöavamo|da stvorimo neöto lepo.
{79847}{79923}Ali, ako nastavite da se|okreÊete kao straöilo,
{79924}{79998}i savijate kolena kao konj|koji vuËe stara kola,
{80000}{80059}teöko da Êemo uspeti.
{80156}{80291}Dobro. Prihvatam opkladu.|- Daj da vidim skice.
{80343}{80392}Devojka...
{80709}{80832}Pazite se, gospoice.|Taj Ljubov je ûivotinja.
{81306}{81371}Joö uvek mislite|da ja to mogu?
{81372}{81453}Vaö trenutni izgled govori|da smatrate da je teöko.
{81454}{81527}Nadam se da Êete za dve|nedelje, do premijere,
{81528}{81600}uvideti da su stvari|priliËno jednostavne.
{81610}{81684}Ne zaboravite da se veliki|utisak moûe postiÊi,
{81685}{81760}samo velikim bolom|u telu i duöi.
{81857}{81937}Ne ûelite da pokvarite|disanje, zar ne?
{81967}{82025}Sredio sam da od danas|ruËate u mojoj kancelariji.
{82028}{82063}Kraster!
{82238}{82286}Sedite tamo, molim vas.
{82301}{82357}Kraster, za klavir!
{82358}{82418}Da li obiËno imate muziËku|pratnju za vreme obroka?
{82420}{82510}Ne. Ali, bojim se da Êe|to biti vaöa sudbina
{82512}{82556}u naredne dve nedelje.
{82557}{82640}Kraster Êe vam svirati muziku|iz Crvenih cipelica
{82641}{82722}za vreme svakog ruËka,|Ëaja i veËere. Do premijere.
{82728}{82762}Shvatam.
{82797}{82893}Na ovaj naËin dobro Êete|se upoznati sa muzikom.
{82898}{82949}Verovatno hoÊu.
{82951}{83022}Muzika je jedino vaûna.|Samo muzika.
{83045}{83099}G. Kraster, izvolite.
{83370}{83455}Neki su se specijalizirali|za takvu vrstu muzike.
{83461}{83560}Neki. -Vi? -U moje vreme.
{83748}{83836}Da li bi ste na trenutak|prestali da to svirate?
{83837}{83884}To je pravi tempo.
{83905}{83976}OdsviraÊu temu za plesnu|dvoranu.
{83978}{84056}To je najlaköe probavljiv|deo aranûmana.
{84057}{84097}I viöe od toga.
{84104}{84204}Izbacujem scenu, ali je i dalje|u mom aranûmanu.
{84231}{84298}Napisao sam ovo za|plesnu dvoranu.
{84299}{84380}Svako ko poznaje muziku|videÊe plesnu dovoranu.
{84591}{84669}»ak Êe je i Lermontov|videti, Ëak i vi.
{84719}{84798}Ali kad vas vaö partner|podigne u vis,
{84800}{84878}moja muzika Êe vas|transformisati. -U öta?
{84943}{85017}Cvet koji se njiöe|na vetru.
{85055}{85119}Oblak koji plovi nebom.
{85150}{85197}Belu pticu u letu.
{85208}{85259}äta kaûete na paradajz?
{85271}{85361}On bi voleo vaöu pticu|i cvet. -A vi ne biste?
{85366}{85442}Da ste plesaË znali biste|da je vaûna samo...
{85443}{85516}Trenutak.|Vaûna je samo muzika.
{85533}{85608}U svakom sluËaju teöko je|odlepiti se od zemlje,
{85609}{85662}bilo da ste ptica, ili cvet.
{85768}{85852}Zar niöta neÊete da|zamiöljate prvo veËe?
{85901}{85992}Da. Rat izmeu mene|i publike.
{86265}{86358}Uz moju muziku|Êete pobediti.
{87178}{87253}Gice Pejdû. Ja nisam|dirigent u cirkusu,
{87254}{87302}niti ste vi konj!|- Prebrzo je!
{87303}{87415}VideÊete da nije, ako|otklizite lagano do kraja,
{87416}{87482}pre nego öto krenete|u piruetu.
{87497}{87572}Udarac palicom na dole|znaËi da zastanete.
{87573}{87621}Razumemo se, gospodo?
{87624}{87695}Idete na drugi udarac.|- NemoguÊe.
{87750}{87845}Jednostavno je.|Vidite ovu palicu? -Da!
{87850}{87895}Onda je pratite!
{88872}{88920}SreÊno! -SreÊno.
{89035}{89130}Viki! Pleöi kojim god ûeliö|tempom, pratiÊu te.
{89243}{89324}SreÊno, g. Kraster. -Hvala.|- Nervozan? -Ne.
{89658}{89734}Nemaö o Ëemu da brineö.|Aranûman je odliËan.
{89736}{89810}Stvarno? -VeliËanstven!|Kad bih... Odlazi.
{90805}{90882}Griöa... -Haos.|Svuda samo haos!
{91015}{91110}Crvene baletanke!|- äta? -Nisu tu!
{91267}{91402}Gde su? -Siguran si da ih|ti nisi spremio. -Da, da.
{91625}{91718}Boris, pogledaj ovo!|Nespretni slonovi!
{91719}{91766}Uniötili su moj dekor.
{91770}{91906}Vidi ova vrata! -Neko Êe ih|popraviti. -Ali, ko? Ko?
{91980}{92007}Dimitrij!
{92095}{92185}Prvi maler? -»ak ne mogu|da se setim kako ulazim!
{92186}{92262}To vam se samo Ëini.|äta kaûete na ovo?
{92329}{92390}Da, to je to! U redu je|kad Ëujem muziku.
{92393}{92470}Onda Êe sve biti u redu.
{92522}{92602}Muzika je jedino vaûna.|Niöta drugo, sem muzike.
{92620}{92702}Da sam imalo sumnjao|u vas, ja bih bio nervozan.
{92703}{92752}Jesam li nervozan?|- Ne.
{92753}{92825}PlesaÊete za Ljubova,|Ratova, mene,
{92826}{92897}ljude za koje ste mnogo|puta plesali.
{92926}{92999}Verovao sam u vas od|samog poËetka.
{93003}{93057}Ali danas svi pleöu.
{93059}{93140}éelim da veËeras pleöete sa|istom ekstazom koju sam
{93142}{93237}video samo jednom pre toga.|- U Merkuri pozoriötu?
{93258}{93369}Da. U Londonu, jednog|kiönog subotnjeg dana.
{93375}{93419}40 sekundi! -Dolazim.
{93504}{93537}SreÊno!
{93540}{93640}Ti si maioniËar! Zavröili smo|sve ni iz Ëega, za tri nedelje.
{93642}{93730}I najbolji maioniËar moûe|da izvadi zeca iz öeöira,
{93733}{93781}ako je zec veÊ u öeöiru.
{94321}{94396}äteta öto u pozoriötu ima|samo 300 mesta.
{94397}{94471}Mogli smo da napunimo|Albert Hol veËeras!
{94473}{94548}Da. Sutra Êe ceo svet|priËati o nama.
{119790}{119881}Dobro si? Da li oseÊaö|kako ti u glavi buËi?
{119899}{120002}Sav taj aplauz, cveÊe,|klicanje, to nije niöta.
{120008}{120112}Ali ja, koji sam video Pavlovu,|Kartaginu, kako pleöu,
{120146}{120227}kaûem ti da sinoÊ nisi bila|ni loöa, ni dobra.
{120370}{120470}Sada Êu ti reÊi istinu.|Bilo je dobro.
{120492}{120586}Hvala, g. Ljubov. -Zovem|se Griöa. -Ja sam Viki.
{120602}{120663}Kako ste?
{120677}{120718}A kasnije...
{120739}{120796}Boris Lermontov|ûeli da te vidi.
{120802}{120864}Zaöto u sred Ëasa?|Zaöto?
{121594}{121632}Tiöina!
{121821}{121882}Ko je to? A, to si ti!
{121906}{122006}Ne, ne. Hvala öto si zvao.|Uopöte me ne ometaö.
{122116}{122165}Ali, molim vas! Zar ne|vidite da telefoniram?
{122200}{122291}Slaûem se. Muzika je|najotmeniji sport.
{122297}{122386}Da. To je divna|uloga za nju.
{122999}{123049}Ne ove sezone,|veÊ sledeÊe.
{123101}{123181}Veoma ljubazno öto ste zvali.|Mnogo vam hvala.
{123182}{123260}Nema viöe poziva.|»ak ni Ëestitanja.
{123476}{123550}G. Kraster, to je sve.|Hvala. Ponosim se tobom.
{123555}{123636}G. Lermontov, ûeleo bih...|- Drugi put.
{123651}{123736}Razumete francuski?|ProËitajte i doite drugi put.
{123850}{123933}Gica Pejdû.|- Uite, gice Pejdû.
{123979}{124048}éelim da popriËamo|o vaöoj buduÊnosti.
{124118}{124203}Kada sam vas prvi put sreo|kod lejdi Neston,
{124205}{124261}postavili ste mi|jedno pitanje.
{124263}{124344}Pitali ste me da li ûelim|da ûivim, ja sam rekao: Da.
{124345}{124433}Ustvari ja ûelim viöe,|mnogo viöe.
{124439}{124521}Da napravim neöto|veliko iz malog.
{124540}{124612}Da od vas napravim|veliku balerinu.
{124626}{124738}PostaviÊu vam isto pitanje.|äta vi ûelite od ûivota?
{124760}{124810}Da ûivite? -Da igram.
{124986}{125076}Imamo joö dva meseca do|poËetka sezone u Monte Karlu.
{125133}{125190}IÊi Êemo na turneje.|BeË, Rim, Kopenhagen,
{125193}{125307}ätokholm, zatim Amerika.|IduÊe godine ponovo London.
{125312}{125388}Sve velike uloge za vas.|Kopelija, éizela,
{125389}{125462}Labudovo jezero,|Uspavana lepotica.
{125479}{125589}Vi Êete ih osveûiti! Vi Êete plesati|i ceo svet Êe plesati sa vama!
{125648}{125740}Ni reËi.|Ja Êu da govorim,
{125780}{125905}a vi Êete da igrate.
{126615}{126698}Laku noÊ. -Laku noÊ, Griöa.|- Nije bila loöa veËeras.
{126704}{126807}Bila je dobra. -Dobra?!|Ona je vatra!
{126932}{127060}Laku noÊ. -Laku noÊ, Sergej.|- Viki je bila veliËanstvena.
{127159}{127253}Treba da rekonstruiöemo|pozoriöte. -äta mu fali?
{127254}{127305}Suviöe je malo.|- Laku noÊ, Lermontov.
{127307}{127374}Laku noÊ, Livi.|- Vreme je za Ëudo.
{127375}{127409}Pravi je trenutak!
{128825}{128898}Laku noÊ, Boris.|- Laku noÊ, Griöa.
{128927}{129015}Laku noÊ, Boris.|- Laku noÊ, Sergej.
{129035}{129117}Laku noÊ, g. Lermontov.|- Laku noÊ, Viki.
{130452}{130541}Laku noÊ, Boris.|- Laku noÊ, Sergej.
{130573}{130627}Hvala vam. To je sve!
{130639}{130709}Laku noÊ, Boris.|- Laku noÊ, Griöa.
{130750}{130853}Kaûite mi koji je najbolji|restoran. -La Rezerv.
{130859}{130895}Da, La Rezerv.
{130896}{130969}Laku noÊ, g. Lermontov.|- Laku noÊ, Livi.
{130988}{131038}Rezerviöi mi sto.
{131102}{131170}Za dvoje? -Da.
{131295}{131394}Dûulijan! Nisam poûelela|laku noÊ Lermontovu.
{131399}{131500}G. Dimitri? -Ne, gica Pejdû|joö nije doöla.
{131504}{131632}G. Ratov? Ne, nije ni on.|G. Ljubov? Ne.
{131733}{131802}Upravo su mi rekli|da su svi u gradu
{131803}{131907}na zabavi sa g. Ljubovim.|Roendan nu je.
{133393}{133508}Dozvolite, gospodine. Poklon|od kazina Monte Karlo.
{133719}{133772}Boris Lermontov!
{133869}{133968}Dobro veËe, Griöa. Mogu li|se pridruûiti tvom druötvu?
{133973}{134014}Sa zadovoljstvom!
{134428}{134538}Davno nisam sedeo ovako,|zajedno sa celom porodicom.
{134831}{134940}Ali Ëini mi se da velika|gica Pejdû nije sa nama.
{134951}{135062}Zar vam ne nedostaje joö jedan|Ëlan naöe sreÊne porodice?
{135100}{135131}Ne,
{135138}{135165}ne bih rekao.
{135170}{135240}Zaöto i bi.|Ti si zauzet Ëovek.
{135400}{135473}Svi znamo da ste jako|zauzet Ëovek,
{135474}{135558}ali nemojte reÊi da|niste primetili.
{135563}{135610}Ne preteruj.
{135625}{135742}Boris, imamo romansu|u naöoj sredini. -Sjajno!
{135748}{135794}Romeo Kraster,
{135814}{135871}i Julija Pejdû.
{135908}{135979}Kada je poËela|ta velika romansa?
{136010}{136058}Od Crvenih cipelica
{136113}{136140}äarmantno.
{136180}{136240}A, gde su otiöli veËeras?
{136251}{136297}Zar je to vaûno?
{136330}{136366}Mladi su,
{136367}{136419}zajedno su i vole se.
{137178}{137234}Dragi? -A?
{137248}{137320}OdluËila sam da, ipak,|verujem u sudbinu.
{137390}{137436}Drago mi je.
{137635}{137674}KoËijaöu!
{137751}{137796}KoËijaöu!
{137910}{138005}ProbudiÊeö ga.|- HoÊu da znam gde smo.
{138039}{138079}KoËijaöu...
{138416}{138468}Jednom,|kada budem star,
{138492}{138575}ûelim da doe neka mlada|devojka i da me pita,
{138602}{138680}G. Kraster, koje je to mesto|na kojem ste bili najsreÊniji
{138682}{138735}u svom ûivotu?
{138783}{138823}Ja Êu joj reÊi,
{138828}{138945}Draga moja, nikada nisam znao|taËno koje je to mesto bilo.
{138949}{139017}Negde na Mediteranu.
{139029}{139105}Bio sam sa|Vikotorijom Pejdû.
{139110}{139210}Ona je bila Ëuvena|balerina.
{139244}{139315}Voleo sam je mnogo.
{139381}{139450}Tada je bila veoma|mlada,
{139457}{139521}i priliËno neiskvarena.
{139542}{139596}Bili smo, seÊam se,
{139626}{139681}veoma zaljubljeni.
{140697}{140738}Video si to?
{140744}{140814}Smeöila mu se.
{140818}{140909}Ne bih rekao.|- Ti misliö da sam slep?
{141027}{141089}Gledaj kako igra!
{141100}{141146}Sa zadovoljstvom.
{141175}{141252}U mislima je s njim.
{141459}{141486}Da!
{141505}{141531}Da!
{141570}{141613}U redu. OdliËno!
{141635}{141715}Dobro veËe. Bojim se da je|aranûman joö malo sirov.
{141735}{141770}Vidim da ste imali vremena|da ga pogledate.
{141800}{141907}Da, g. Kraster.|Pogledao sam ga.
{141985}{142079}Pozvao sam vas da|razgovaramo o vaöoj muzici.
{142087}{142134}Da preemo na stvar.
{142151}{142241}äta se to dogaa izmeu|vas i gice Pejdû?
{142304}{142375}Da li bi Dimitri mogao...|- Da.
{142538}{142598}Da. Volimo se.
{142671}{142718}Razumem.
{142741}{142820}Jeste li videli njen|nastup veËeras?
{142824}{142905}Da, ja sam dirigovao.|- Uûivali ste?
{142906}{142983}Bilo je to neöto najlepöe|öto sam video u ûivotu.
{142984}{143030}Bilo je nemoguÊe.
{143035}{143173}Znate zaöto? Zato öto nije|radila umom, veÊ srcem.
{143191}{143299}Sanjarila je. Taj luksuz|nikad ne dozvoljavam
{143305}{143360}Ëlanovima svoje trupe.
{143365}{143440}Ona ûeli da bude|velika balerina.
{143445}{143525}PriËala vam je o svojim|velikim ambicijama?
{143530}{143625}O, da... -Ali, ona joö uvek|nije velika balerina!
{143629}{143710}Niti Êe to postati ako dozvoli|da je neko idiotsko
{143716}{143792}zbliûavanje skrene|sa glavnog puta.
{143807}{143930}G. Lermontov, ne razumete.|Mi se stvarno volimo.
{144075}{144214}G. Kraster, imao sam vremena|da pogledam vaö rad. -I?
{144232}{144296}Nalazim da je i on|nemoguÊ!
{144560}{144601}Nije istina.
{144615}{144666}Dobar je. -Detinjast,
{144678}{144769}povröan i sasvim|beznaËajan.
{144812}{144850}Ako je tako,|oslobaam vas tereta.
{144870}{144944}Ima puno prvoklasnih|baletskih trupa,
{144945}{145017}koje Êe ga prihvatiti|i izvuÊi korist.
{145019}{145105}Moja najveÊa ambicija nije|da komponujem za balet.
{145106}{145192}Za neke je to drugorazredni|naËin izraûavanja.
{145327}{145377}G. Kraster napuöta|trupu.
{145384}{145475}Dajte mu platu za dve|nedelje i priznanicu.
{146235}{146310}Spremao sam se da doem|da ti poûelim laku noÊ.
{146311}{146382}Neöto se desilo? -Ne.|Da ne zaboravim,
{146383}{146430}nemoj viöe da radiö|na novom baletu.
{146432}{146490}OdluËio sam da prekidamo.|- Prekidamo?!
{146493}{146600}Kako to misliö? VeÊ sam|uradio plesnu koreografiju.
{146607}{146677}Taj momak Dûulijan|je talentovan.
{146680}{146774}Najbolji aranûer kojeg smo imali.|- Dûulijan Kraster odlazi,
{146779}{146905}i ne ûelim o tome viöe da|diskutujem. -Ja ûelim!
{146920}{146990}Misliö da ne znam da oûivim|aranûman kada ga Ëujem?
{147000}{147108}Misliö da radim danju|i noÊu iz zadovoljstva
{147110}{147209}öto öto mi je nareeno|da traÊim svoje vreme?
{147216}{147340}Dosta mi je ove ludnice!
{147370}{147440}Prekidam!|Dajem ostavku!
{147495}{147568}Mislim da si doneo veoma|vaûnu odluku.
{148310}{148496}Pa? äta je rekao? -Ne ûeli|da stvarno odeö, Griöa.
{148475}{148581}éao mu je. -U tom sluËaju|Êu razmisliti!
{148603}{148654}äta je rekao za Dûulijana?
{148668}{148771}Nikada ga nisam video|tako ljutog.
{148779}{148903}Govorio je o nezahvalnosti|i nelojalnosti.
{148929}{149027}I to, da kada liËna verovanja|poËnu da se meöaju...
{149028}{149073}Znam taj deo!
{149084}{149176}Draga moja deco,|jako mi je ûao.
{149230}{149328}Ali, jutro je pametnije|od noÊi. -Ujutro!
{149333}{149440}Ujutro odlazi za Pariz|vozom u 8.15 h.
{150155}{150246}Da li je to Ëuvena gica|Pejdû doöla da me isprati?
{150249}{150322}éelim da razgovaram|sa vama.
{150531}{150612}éelim da znam zaöto ste|otpustili Dûulijana.
{150614}{150694}Bojim se, gice Pejdû|da se to vas ne tiËe.
{150768}{150821}Ali, poöto ste veÊ tu...
{150900}{150948}Kraster nije bio dovoljno|mudar i umeöao se
{150950}{151080}u neke moje planove.|Ja to ne dozvoljavam.
{151130}{151247}Nekad sam mislila da Êe u mom|ûivotu biti mesta samo za ples.
{151275}{151320}Opet Êete tako mislita,|draga moja.
{151325}{151395}Ako Dûulijan ide,|idem i ja.
{151465}{151526}äta taËno nameravate|da uradite?
{151531}{151600}IgraÊu negde drugde.|- Naravno!
{151604}{151713}To neÊe biti teöko s obzirom|na ime koje sam vam dao,
{151728}{151816}pod uslovom da vas|oslobodim ugovora.
{151823}{151930}»ak i ako to uradim,|da li Êe biti isto?
{151983}{152062}Nikada nisam ni mislila|da bi bilo isto.
{152102}{152201}Mogao bih da od vas napravim|najveÊu svetsku balerinu.
{152313}{152393}Da li verujete u to?|- Da, verujem.
{152487}{152557}I to vam niöta|ne znaËi?
{152581}{152667}Vi znate taËno öta|mi to znaËi.
{152775}{152821}Voz polazi!
{152878}{152931}Dovienja, g. Lermontov.
{153083}{153144}Gica Pejdû dolazi!
{153314}{153347}Dûulijan!
{153361}{153394}Dûulijan!
{153479}{153523}Idem s tobom.
{153794}{153888}G–ICA VIKTORIJA PEJDé,|VEN»ALA SE JU»E U LONDONU,
{153889}{153981}ZA DéULIJANA KRASTERA.|S POäTOVANJEM, R. DONAT.
{156123}{156160}Slobodno!
{156167}{156255}Kasniö! Nadam se da nisi|previöe radio.
{156261}{156340}Na svu sreÊu imam|sudski nalog sa sobom.
{157052}{157150}Boris, nemoj mi reÊi da|si se opet predomislio.
{157332}{157406}Ne ûelim da je spreËim|da radi.
{157409}{157483}Moûe da igra gde hoÊe|i kada hoÊe.
{157490}{157546}Osim u Crvenim|cipelicama.
{157547}{157615}äta je sa momkom?|- To je neöto drugo.
{157616}{157670}Sve öto je napisano je moje.|I to stoji u ugovoru,
{157680}{157737}Crvene cipelice i deo koji|je uradio na Lepoj mlinarici.
{157757}{157823}Interesuju me samo|moja prava.
{157838}{157885}Ali, ako zadrûiö Crvene|cipelice na repertoaru,
{157900}{157925}moraÊeö da platiö honorar|za autorsko pravo.
{157930}{158000}Crvene cipelice nisu|viöe na repertoaru!
{158237}{158344}»uo sam da je Patrik|u Parizu. -Jeste.
{158371}{158442}Bio sam na veËeri|s njima sinoÊ.
{158482}{158562}Da? Boronskaja je s njim?|- Jeste.
{158581}{158605}Mogu li neöto uËiniti?
{158620}{158716}Kakav im je brak? Uspeöan?|- Patrik izgleda tako misli.
{158762}{158852}HoÊeö li da ti organizujem|sastanak sa Irinom?
{158859}{158974}Da organizujeö, ne.|Neka bude sluËajno.
{159739}{159774}Boris!
{160526}{160614}Laku noÊ, Boris!|- Laku noÊ, Irina.
{160641}{160731}Dobra sezona? -Uvek,|sa baletom Lermontov.
{160763}{160837}Laku noÊ, Boris.|- Laku noÊ, Sergej.
{160845}{160961}Sergej! Ui i seËakaj,|molim te. -Naravno.
{161080}{161177}Laku noÊ, Boris.|- Griöa, molim te doi.
{161472}{161500}Pisma.
{161538}{161622}Niko mi ne piöe.|- Nije taËno.
{161637}{161712}Ovo je tvoje. Od Viki.
{161720}{161754}Od Viki?
{161760}{161855}Kako je ta devojka?|- ProËitaj i vidiÊeö.
{161861}{161945}Ovo je o Dûulijanu.|Piöe o njegovoj novoj operi.
{162003}{162059}Opisuje novu strukturu.
{162289}{162348}Kaûe da je ona|inspiracija,
{162400}{162435}Ëudo.
{162440}{162483}Hvala. To je sve.
{162600}{162692}Od naöih mladih buntovnika.|- Dezertera.
{162707}{162755}Nadam se da su sreÊni.
{162762}{162835}ProËitaj, Boris.|- Da, proËitaj i ti.
{162840}{162885}Moûda Êeö zaûaliti öto si|izgubio tog momka.
{162900}{162939}Sumnjam.
{162960}{163045}Kad smo kod toga, éak|mi je poslao novi aranûman
{163048}{163122}za Lepu mlinaricu.|Dopada mi se.
{163170}{163206}Moûemo s njim otvoriti|sezonu u Londonu.
{163210}{163278}Sa Irinom? -O tome|Êemo razgovarati.
{163390}{163470}Molim te baci pogled.|I bez predrasuda.
{163480}{163570}»uo sam te kako i sebi to|ponekad kaûeö. -Svaki dan.
{163571}{163619}Laku noÊ. -Laku noÊ.
{163627}{163731}Kad bolje razmislim, moûda bih|mogao da proËitam ta pisma.
{163901}{163990}Moje pismo je pisano|samo za mene.
{164003}{164084}Vidimo se, Boris.|- Laku noÊ, Sergej.
{164295}{164370}Nisam mogao da mu|dam da ga proËita.
{164374}{164506}Naziva ga monstrumom.|Talentovani, okrutni monstrum.
{164512}{164564}Trebalo je da mu|to kaûete.
{170608}{170664}DRAGA MOJA VIKI,
{171000}{171045}éao mi je öto kasnim,|Borise Lermontov.
{171165}{171238}Video sam lejdi|Neston sinoÊ.
{171285}{171377}Stigla je jutros.|Ostaje nekoliko nedelja.
{171396}{171500}Gica Pejdû dolazi na kraÊi|odmor iduÊe nedelje.
{172250}{172315}Kao da nam je sueno da se|sreÊemo na ûelezniËkoj stanici.
{172340}{172425}äta radite ovde? -»ekam|tebe. Sedi, molim te.
{172620}{172739}Znaö, draga moja da sam|uvek traûio velike plesaËice.
{172910}{172974}Svima si nam|nedostajala.
{172980}{173075}Mislio sam da Êemo|i mi tebi nedostajati.
{173097}{173210}Jeste. -Treba samo da|kaûeö jednu reË.
{173290}{173350}Kako su svi?|- UkljuËujuÊi i mene? -Da.
{173355}{173405}Nikad bolje!|- Kako je Griöa?
{173406}{173477}Stalno se bori sa Irinom.|- Kako je ona?
{173478}{173557}Stalno se bori sa Griöom.|- A Sergej? -Podmlauje se.
{173620}{173730}A ti? Jesi li sreÊna?|- Da, veoma sreÊna.
{173770}{173895}Mislio sam na igranje.|- Nisam igrala mnogo.
{173899}{174041}Znam. Ali nikada nisi|prestala da igraö. -Ne.
{174060}{174152}I nikada nisi prestala da|uzimaö Ëasove? -Nikada.
{174184}{174275}Zaöto on nije s tobom?|- Radi na novoj operi.
{174276}{174350}Ima generalnu probu|u Kovent Gardenu.
{174352}{174438}Da li bi odustao kada bi|traûila od njega? -Ne znam.
{174439}{174500}Ne znaö? -Ne bih to traûila.|- Zaöto on to traûi od tebe?
{174507}{174555}Zna li on öta traûi?
{174765}{174882}Pripremamo novi balet.|Radimo ga veÊ nedeljama.
{174904}{175019}Kostimi i dekor su divni.|Griöa je pun entuzijazma.
{175025}{175080}Ti znaö öta to znaËi.
{175213}{175287}Od kako si otiöla niko|viöe nije plesao
{175290}{175390}u Crvenim cipelicama.|Nije i neÊe.
{175480}{175610}Viki, obuj ponovo crvene|baletanke i pleöi za nas.
{175817}{175881}Ovo je BBC, 3. program.
{175887}{175986}Rojal opera haus,|Kovent garden, London.
{175987}{176063}VeËeras je premijera|nove opere mladog
{176064}{176138}Britanksog kompozitora|Dûulijana Krastera,
{176140}{176217}do sada poznatog jedino|po aranûmanu za balet
{176219}{176269}Crvene cipelice.
{176270}{176315}Balet Crvene cipelice|imao je velikog uspeha
{176320}{176390}proöle godine u Monte Karlu,|u izvoenju Lermontov baleta.
{176395}{176453}U naöoj zemlji joö|nije izvoen.
{176540}{176640}Prekidamo program zbog|najnovije vesti.
{176661}{176732}Dame i gospodo,|sa ûaljenjem javljamo
{176733}{176802}da se Dûulijan Kraster,|kompozitor,
{176803}{176880}koji je trebalo da diriguje|na premijeri svoje opere,
{176881}{176929}iznenada razboleo.
{176931}{177001}Ser Hartli Mingild Êe|dirigovati umesto njega.
{177049}{177108}Evo, dolazi Ser Hartli|Mingild.
{177112}{177160}PratiÊemo s paûnjom ovu|njegovu izvedbu.
{177310}{177358}Dobro doöli, gospodine.
{177498}{177580}Pitao sam se da li Êu|te naÊi ovde.
{177633}{177681}I naöao sam te.
{177688}{177760}Otiöao si sa svoje|premijere. -Da.
{177801}{177885}Dûulijan! -Zaöto ti nisi?
{178225}{178295}U 8 imamo voz za nazad.|Poimo zajedno.
{178385}{178458}Ali, veËeras pleöem.|- Prosto otii.
{178480}{178529}Dobro veËe, g. Kraster.
{178530}{178609}Zar ne treba da ste veËeras|u Kovent Gardenu?
{178639}{178716}Zaboga, ostavite me|na miru obojica!
{178717}{178792}Dûulijan, molim te saËekaj|da zavröi predstava.
{178793}{178879}BiÊe kasno. -Ti si veÊ|zakasnio, Kraster!
{178880}{178956}Reci mu zaöto si ga ostavila!|- Nisam ga ostavila!
{178957}{179032}Jesi! Izabrala si ûivot,|a tvoj ûivot je balet!
{179034}{179109}Moûeö da igraö bilo gde,|u celom svetu!
{179120}{179201}HoÊeö li se zadovoljiti|s neËim öto nije najbolje?!
{179203}{179284}Ako je tako, nikada neÊeö|biti velika balerina!
{179286}{179365}HoÊeö li je ti napraviti|velikom balerinom? Nikada!
{179366}{179459}Otkako si je odveo, danima sam|Ëekao öansu da je povratim!
{179460}{179551}äta misliö zaöto?|- Zato öto ste ljubormorni!
{179557}{179651}Da! Ali na naËin koji|ti nikada neÊeö razumeti!
{179875}{179990}Pa, Viki? -Volim te,|Dûulijan. Samo tebe.
{180088}{180210}Moûda si njega volela viöe?|- Ne znam, ne znam!
{180275}{180350}Ako sada odeö s njim ne|ûelim da se ikad vratiö.
{180360}{180480}Viki, on ûeli da uniöti naöu|ljubav! -Besmislica!
{180515}{180650}Idi! Idi s njim i budi|domaÊica!
{180665}{180750}Sa baletom si zavröila|za sva vremena!
{180808}{180878}Viki, pogledaj me.
{181294}{181342}Zbogom, draga moja.
{181433}{181472}Dûulijan!
{181806}{181835}Viki!
{181859}{181905}Viki!
{181920}{181971}Sluöaj!
{182045}{182114}Svi Ëekaju na tebe.
{182156}{182226}Tuga Êe proÊi, veruj mi.
{182240}{182301}éivot ide dalje.
{182341}{182427}Od sada, pa nadalje,|igraÊeö,
{182484}{182550}kao niko do sada!
{183542}{183627}Gospoice, gde Êete?
{183847}{183905}Gice Pejdû,|kuda ste krenuli?
{185555}{185583}Dame...
{185631}{185675}i gospodo,
{185750}{185796}ûao mi je,
{185831}{185886}öto moram da|vam kaûem,
{185922}{185981}da gica Pejdû,
{185999}{186045}ne moûe,
{186073}{186108}da igra,
{186130}{186168}veËeras,
{186223}{186262}niti,
{186310}{186377}bilo koje drugo veËe.
{186442}{186486}Ipak,
{186538}{186586}odluËili smo,
{186654}{186704}da vam predstavimo,
{186728}{186788}Crvene cipelice...
{186887}{186931}To je,
{186968}{187006}balet,
{187076}{187147}koji je proslavio nju,
{187171}{187219}balet kojeg je ona,
{187241}{187280}proslavila,
{187298}{187360}PredstaviÊemo ga,
{187443}{187473}jer,
{187583}{187616}mislimo,
{187682}{187730}da bi ona,
{187764}{187814}ûelela da vidi.
{188720}{188800}éao mi je.
{188968}{189005}Dûulijan?
{189014}{189061}Da, draga.
{189071}{189134}Skini mi crvene|cipelice.
{189159}{190659}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/5cesy|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
