{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{586}{663}OBOSTRANE GREäKE
{789}{833}-Uite.
{963}{988}Pakujem se.
{1002}{1087}-éao mi je zbog tvoje sestre.|To je straöno.
{1123}{1280}-Bolje je öto se ranije zavröilo nego|da je nastavila da ûivi kao..
{1305}{1382}-Kuda si se zaputio? Ne |pridruûujeö se valjda  neprijatelju.
{1397}{1488}-Postojem akcionar. -Da nema ovo|neke veze sa onim öta se dogodilo Suzan?
{1511}{1574}-Ne ûelim viöe da vidim ni jednog|dilera droge. NeÊu da ih branim.
{1598}{1703}Ne ûelim da ih gonim. PrimiÊu metak|pre nego öto zavröim ovaj posao. Ili Êu skrenuti.
{1717}{1812}-To ti se nikada nije desilo,|Arture. Nemaö ti to u sebi.
{1838}{1890}-SreÊno. Javi mi gde si.
{1955}{2030}Ideö joö da radiö?
{2039}{2091}-Ne, samo zavröavam za danas.
{2170}{2230}MOTEL "SIDRO"
{2743}{2829}-Dobra si. -Treba mi san.
{2838}{2903}-Bilo je najbolje, Mjurijel, najbolje.
{3080}{3125}-To je istina.
{3437}{3470}-OdliËno dupe.
{3612}{3660}-Mislim da sada treba da |prekinemo, Leri.
{3775}{3909}-Kako to? -Razmiöljam da se ustalim |sa Talmedûom, pitao me da se udam za njega.
{4120}{4196}-Drago mi je da si Ëekala dok|se nisi zabavila. -Oh, Leri...
{4214}{4256}Svia mi se ovo koliko i tebi, ali je|vreme da to uradim.
{4284}{4350}HoÊu decu pre nego öto on i ja |ostarimo. -Ja dajem dobru decu.
{4366}{4390}-Ti si oûenjen, Leri.
{4424}{4502}-Znaö da je to gotovo. Ako |hoÊeö se udaö samo reci.
{4663}{4722}-Ja ne ûelim da se udam|za tebe, Leri.
{4835}{4865}-Vidim...
{5104}{5226}-Razmiöljla sam o tome... -Ali je noÊas|bilo tako dobro da si se predomislila.
{5535}{5571}Starzing.
{5641}{5730}KuËkin sin! Deset, |najviöe petnaest.
{5785}{5900}-äta je bilo? -Potrebni smo Gasu|i Liju za dve muöterije dole u "Raj"-u
{5994}{6052}-Mrtve? -Tada zovu "Ubistva".
{6083}{6177}Uvek Êu se seÊati gde sam bio|one noÊi kada me je Mjurijel Vin öutnula.
{6238}{6271}-KrenuÊu sa tobom.
{6286}{6345}-Dok sam na mestu zloËina mogu|da uzmem sluËaj.
{6402}{6484}-Vreme je i treba mi.|-Neverovatna si, Mjurijel.
{6513}{6609}-NeÊe ti dopustiti da vodiö troduplo.|-Ali mogu da pomaûem.
{6773}{6802}-OblaËi se.
{6826}{6860}Ona je sa mnom.-U redu.
{7709}{7760}-Leri? -äefe?
{7797}{7891}-Ko je ovo? -To je Mjurijel Vin iz|kancelarije tuûioca.
{7902}{7996}-Zdravo. -Razgovarali smo o ovom|sluËaju kada ste zvali. Htela je da poe.
{8049}{8166}Pametna je.-Kada se bude saznalo da|Êe dobiti slobodan vikend biÊe ih svuda.
{8179}{8197}-Gde je dokaz?
{8226}{8276}-Tu smo svi u redu.
{8341}{8383}-Tri automobila ispred restorana |su automobili ûrtava.
{8394}{8487}Osim vlasnika restorana tu je agent|za avionske karte Luiza Rimarti.
{8512}{8558}Plus momak koji se zove|Pol Dûetson.
{8616}{8640}Pazi gde stajeö.
{8899}{9004}-Radna verzija. Naoruûani pljaËkaö|besni, kasa je prazna.
{9020}{9120}Depozita nema. értve nemaju|novËanike i nakit.
{9229}{9311}-To nije sve öto nemaju.|-Da, to je mast.
{9326}{9378}-KulmaËi kaûe da je seksulano|napastvovana, analno.
{9401}{9484}-To je bezbolno, zar ne?|-Postoje znakovi penetracije,
{9494}{9582}tragovi lubrikanta. Tip je nosio|gumicu. -Malo Ëudno.
{9605}{9709}-NezaötiÊeni seks moûe da ubije.|-Idemo. Pustimo ga da zavröi.
{9740}{9803}-PozvaÊu aerodrom da vidim gde|je poslednji put bila Rimarti.
{9974}{9999}-Dobre cipele.
{10013}{10064}-Naeni su oko devet, devet i |trideset? Ko ih je prvi primetio?
{10086}{10175}-Mislim da je gas doöao do ovde.|Moûda po telefon, moûda po piötolj.
{10190}{10261}-Da li je imao piötolj za kasom?
{10278}{10378}-Rafi je bio na telefonu. Kad je sinoÊ|otiöao, tip ûena su joö uvek bili tu.
{10394}{10509}Gas zatvara za praznike. Rafi je prijavio|kada je video da su kola joö na prakingu.
{10542}{10617}Luiza je bila ove. Ona je bila |upucana.
{10634}{10725}Druga ûrtva... Izgleda da ih|je sve odvukao do hladnjaËe.
{10746}{10830}Ako je bila sasvim krvava, on ima|krv na odeÊi koja niije doöla sa njegove glave.
{10853}{10918}Moram da radim teûe.|On je dobio svoje.
{10934}{10983}-Moûda to nije bila Ëista pljaËka.
{11004}{11110}Moûda je neko brljao sa tuom devojkom.|Zatim bio uhvaÊen i stvari su izmakle kontroli.
{11157}{11205}-Sve je moguÊe sa ljudima.
{11299}{11372}-Leri kaûe da ste dobri.|-S'obzirom na izvor...
{11409}{11455}-Da, to je taËno. Potrebni|su mi nalozi.
{11485}{11584}-Gasova kuÊa, kuÊa Luize Rimarti.|äto brûe to bolje.
{11636}{11664}-Mogu li da vidim?
{11726}{11764}-Ako mislite da Êe pomoÊi...
{11841}{11860}-Evo.
{11898}{11949}-Pokrij cipele.
{12427}{12454}Jesi li dobro?
{12516}{12580}Koncentriöite se, savetniËe i idite|po naloge.
{13036}{13130}-Dûordû, Dûordû nije ovde. Otiöao|je na pecanje. -Nedostupan je?
{13157}{13196}-Otiöao je na pecanje.
{13407}{13463}-Molim te, molim te, molim te...
{13514}{13620}-Da, Dûilijen Saliven. -Sudijo, Saliven,|ûao mi je öto zovem kasno
{13625}{13723}ovde Mjurijel Vin iz kancelarije tuûioca.|-U redu je, savetniËe.
{13757}{13787}äta mogu da uradim za vas?
{14101}{14202}Arture, treba mi usluga, sudija Saliven|bi potpisala naloge da mogu da joj ih
{14208}{14289}odnesem, ali Grijer hoÊe da ostanem |u zgradi. -HoÊeö da ih ja odnesem?
{14308}{14380}-Da saËekaö da ih potpiöe i vratiö ih.|-Jednostavno. -Jesi li siguran?
{14384}{14429}-Siguran sam. -Hvala ti.|-Gde ûivi?
{14449}{14565}-Adresa je ovde. To je nova zgrada.|Jedna od onih kojom pokazujeö poreklo.
{14615}{14665}-Kako si saznala za ono kod Gasa?
{14671}{14769}-Bila sam u prolazu i videla|sam ûutu traku.
{14839}{14922}-Reci mi kako ûivi ledena kraljica i |zaöto je kod kuÊe za praznike, hvala Bogu.
{14956}{14985}-Svakako Êu je pitati.
{15014}{15171}-Arture, nije bila tvoja krivica zbog |onoga öto se dogodilo Suzan.
{15190}{15219}-Znam.
{15267}{15362}-Misliö da bi to pomoglo.|-To je Grijer.
{15963}{16131}-Sudijo Saliven, imam naloge od |gice Vin. -A vi ste?
{16151}{16244}-Rejven, Artur Rejven. -Naravno,|savetniËe bili ste kopd mene na sudu.
{16286}{16309}-Tako je.
{16355}{16513}-Da li ste i vi na sluËaju?|-N, bio sam u kancelariji i...
{16553}{16635}... gica Vin je bila zauzeta, pa...|-To je vrlo kolegijalno od vas.
{16758}{16796}-Brzo Êu.
{17301}{17344}-Sedite, gdine Rejven.
{18013}{18051}Znate li pesmu?
{18109}{18205}-Muziku...ne... äta je to?
{18242}{18303}-Betoven.
{18334}{18374}-Veoma je dirljivo.
{18414}{18517}-Uspavljuje. -Izvinite öto|sam vas muËio.
{18561}{18603}-Nije bio problem.
{18686}{18786}-Imate divnu kuÊu. -Hvala.|Laku noÊ, gospodine Rejven.
{19720}{19866}-Da pogaam, doöli ste da razgovarate|o Luizi Rimarti. -Ne, traûim Dûeneviv Kerijer,
{19872}{19984}najbolju prijateljicu, koliko sam razumeo.|-PoslaÊu po nju. Uite.
{20000}{20038}Recite Dûeni da doe, Nensi.|-Da, gospodine.
{20090}{20178}-Dugo se nismo videli. Sedite.|To je dobra stolica.
{20201}{20270}-Ovakva fotelja bi mogla da|uspava moje dupe.
{20351}{20453}-Kako je zloËin? -Ja ne radim zloËin.|Kakva je bezbednost na aerodromu?
{20476}{20533}-Koliko god je potrebno.
{20544}{20671}-Radio sam sa Luizom i Gasom i kako|se zove onaj drugi? -Dûetson, Pol Dûetson.
{20698}{20791}-Doöli su dvadesetog uveËe. Otiöli|po sendviË, dobili su metak.
{20811}{20878}-On i Luiza su bili par?|-»uo si neöto o tome?
{20932}{21044}-Ne, ali je Luiza umela da zavede.|.ImaÊu to na umu.
{21079}{21139}-Verovatno ti je drago öto ipak|nisi uspeo da ueö u pilote?
{21160}{21284}-Ponekad joö ûalim, ali nije da dobijeö|ono öto ûeliö nego da ûeliö ono öto dobijeö.
{21315}{21377}-Zar to nije maarska izreka?|-Ne, Maari kaûu:
{21387}{21448}"Ne dobij ono öto ûeliö, dobij ono|öto svi drugi ûele"
{21504}{21607}-Ipak ti ide dobro. Da nemaö|kopije onih slika na zidu?
{21627}{21713}-To su sve gluposti.|-Znam to, Ernale.
{21818}{21914}-Dûeneviv, poruËnik Starzek ûeli da|vam postavi par pitanja. -Zdravo.
{21926}{22053}Moûete da priËate u sobi za konferenciju.|-Dobro. IÊi Êu gde i ti.
{22073}{22094}-Naravno.
{22314}{22433}-NeÊe trajati dugo, Dûeneviv. Mogu li|da vas zovem Dûeni? -Da, to mi je ime.
{22538}{22672}-Ti i Luiza ste bile bliske. -Na poslu, da.|Bile smo prijateljice, verujem.
{22691}{22799}-Ne van posla? -Luiza je bila sama.|Ja sam udata. To je razliËito.
{22825}{22922}-Da. Luiza se dosta "druûila".
{22923}{23001}-Volela je da izlazi. Da se malo |provodi nakon propalog braka.
{23029}{23134}-Bivöi joj nije bio baö dobar?|-Mislim da ga nije videla dobro.
{23159}{23245}Videla je boju njegovog novca|dosta vremena.
{23346}{23384}-U tome je stvar.
{23427}{23574}-Luiza je zaglibila. Hipoteka na kuÊu.|kartice, kazne, plata joj je iöla pravo u banku.
{23686}{23748}-Znali ste za to?|-Da. Rekla mi je da joj je teöko.
{23779}{23858}-Stvar je u tome da sam video njenu|kuÊu. Stvari u kuÊi. Nove stvari.
{23879}{23963}OdeÊu, veliki ekran, nakit,|vozila je dobar auto.
{23978}{24076}Pitam se da li je moûda postojao neki|dareûljiv dûentlmen u njenom ûivotu.
{24135}{24176}-Nikad mi nije rekla.|-Mislite da bi?
{24199}{24287}Da li je Luiza neko ko bi vam to|rekao? -Luiza nije imala mnogo
{24294}{24381}ûelje da priËa o muökarcima. Rekla|bi da je troöila tu novac.
{24432}{24551}-Mislim da bi rekla.|-äta sa drugim izvorima?
{24602}{24690}-Kao na primer? -Na primer|da je prodavala svoje dupe.
{24710}{24823}-To je odvratno reÊi, naredniËe.|-Znam da jeste, ali ne bi bilo prvi put.
{24902}{24973}-ShvatiÊu to kao da ne mislite da|je bitno. -I nije.
{24984}{25066}-A droga? -Luiza nije koristila drogu.|-A da li je prodavala?
{25095}{25170}-Imala je decu. Bila je majka,|odgovorna majka.
{25192}{25270}Mislim da ne znate o kome priËate.|-Tako je. Ne znam.
{25311}{25454}-Znma da nije imala prihode van svoje|plate, a troöila je daleko viöe od toga.
{25475}{25568}Mora da postoji odgovor na to.|Znate na öta mislim? -Ne, ne znam.
{25810}{25856}-Da li znate da je pala na testu|za drogu? -Ne, nije.
{25871}{25943}Bio je laûno pozitivan. Pogreöno|je testirana i bila je veoma besna zbog toga.
{25973}{26055}-Zaöto je bila besna? To je bio |sluËajan uzorak. Moglo je svakome
{26082}{26165}da se desi. Posle se raöËistilo.|-Nije joj smetalo mokrenje u posudu.
{26188}{26236}To je bilo zbog naËina kako su je|tretirali. Rekla je da je spavala
{26256}{26295}sa muökarcima koji ne bi stavili|ruke tamo gde ti ljudi jesu.
{26312}{26379}-ZnaËi, misterija je odakle je Luiza|dobijala novac?
{26406}{26452}-Za mene jeste, da.
{26492}{26533}-To je otprilike sve za sada.
{26613}{26629}Hvala.
{26809}{26888}Video sam Dûeneviv kako izlazi,|delovala je nekako eksplozivno.
{26919}{26985}-Pitao sam je neka ökakljiva|pitanja. -Kao na primer?
{27009}{27107}Da li je Luiza prodavala drogu ili|bila sa nekim matorim bolesnim tipom.
{27139}{27253}Sve je to pomeöala öto je dovodi da|ima puno novca kom se ne moûe uÊi u trag.
{27313}{27464}Imaö li neku ideju? Moûda je krala|-Mi nemamo krae.
{27506}{27642}Ako hoÊeö da kradeö imaö priliku |sa kartama. Ona je radila sa kartama.
{27680}{27788}-Zar je to moguÊe? -Karte se |posmatraju. Od drveta do poda.
{27805}{27911}Svaki put kada neko leti brojaË|uparuje kupon sa novcem.
{27921}{27996}Ako nema uplate, zazvoni mi telefon.|Telefon mi nije zvonio dve, tri godine.
{28016}{28099}-U letnju je tako. Nema tolerancije.|TuûiÊu te, uhapsiti, to funkcioniöe.
{28132}{28222}-To ne ostavlja mnogo. Ne kurva se,|ne prodaje, ne piöe knjigu,
{28231}{28310}ne sa polovinom ljudi koji prolaze|ovuda na putu za Atlantik Siti.
{28373}{28423}-Neöto sam propustio, Ernale?
{28472}{28506}-Ne.
{28554}{28595}Niöta nisi propustio.
{28761}{28829}Moraö da me sasluöaö. Leri.|-Zato sam ovde.
{28858}{28899}-Ne znam baö za to.
{29076}{29099}-Ovo je veoma ökakljiva priËa.
{29116}{29208}-Ernal ima neÊaka... -Ernal? äef |obezbeenja na aerodromu?
{29223}{29309}-Ime mu je Kolins Farvel. Crnac je.|Ernal kaûe da je njegova sestra tada
{29322}{29425}volela crno meso. Klinac je sjeban.|Kaûe da pokuöava da se sredi od
{29444}{29561}kako moûe da se seti, ali on je u|zatvoru i Ëeka na osudu za treÊu
{29585}{29672}osudu za drogu. To je |doûivotna bez uslovne.
{29688}{29766}-Da li Kolins zna neöto? -Ernal|kaûe da ga je zvao i kukao kako
{29803}{29875}Êe pasti ukoliko mu Ernal ne |pomogne. Ernal je rekao da je kasno
{29901}{30002}i da je to veÊ uradio. Tada je rekao da|ima neöto o ubistvima i da bi se trampio.
{30058}{30146}Da, to sam i ja mislio. -Mora da je|dobro, jer ti onda ne bi bio ovde.
{30186}{30239}-To je samo izgovor da te vidim,|Mjurijel.
{30264}{30369}-Hajde... -Luizina porodica kaûe|da je imala neki antiËki nakit.
{30383}{30479}I Kolins tvrdi da zna ko ga ima,|ili bar tako kaûe Ernalu.
{30504}{30597}-Postoji dosta medaljona na svetu.|-Ovaj je imao slike dve devojËice unutra.
{30645}{30753}-äta misliö? -Mislim da je to samo|priËa, rekla-kazala.
{30790}{30902}Ali mislim da ti i ja treba da odemo na|put do zatvora i vidimo.
{30968}{31119}-Mene je uzbudilo. Idemo. |-Ovo je skoro uzbudljivo kao seks.
{31727}{31791}-Skidajte mi ove lisice.|Ne idem ja nikuda.
{31880}{31924}-Prvo da Ëujemo öta imaö.
{31947}{32002}-DoÊi Êe moje vreme pre nego|öto ti kaûem iöta.
{32067}{32149}-Imaö pogreöno ponaöanje.|Ernal je bio u pravu povodom toga.
{32557}{32671}-Moja najomraûenija stvar, druûenje|sa dilerima droge. Oni su toliko bolji od mene.
{32693}{32747}-Radije bi  ih izubijao
{32756}{32782}-Ja to ne radim.
{32822}{32903}-Izvini, Leri... -Nismo radili na|sluËaju pa samo hoÊu da znaö.
{32927}{33017}-Neki to rade, ja ne.|-U redu.
{33060}{33089}-NaredniËe?
{33165}{33196}-Druga runda.
{33278}{33371}-Moraö da zapamtiö da Êeö, ma |öta nam kaûeö, odraditi svoje i
{33446}{33585}jednostavno mrzim da budeö|ovde. Moûda cinkariö to nekome.
{33605}{33682}-Deset godina moûe da izgleda kao|20. -Nikoga ja nisam ocinkario.
{33716}{33782}-Iznenadio bi se kada bi Ëuo kako|se takva priËa brzo proöiri.
{33824}{33941}Treba da nam kaûeö sve öto znaö i|mi Êemo to da uporedimo i
{33965}{34074}ako shvatimo da si iskren, tuûilac|Êe da ti kaûe öta ti to pomaûe.
{34098}{34203}-I to mogu samo da preporuËim.
{34319}{34412}-Moram samo jedno da znam.|NeÊu svedoËiti. Jel' tako?
{34593}{34625}-U redu.
{34722}{34825}-Moûe li ovo da mi se skine?|Da popuöim cigaretu?
{34847}{34947}Moûe da mi zadrûi priËu, znaö?|-Bolje bi bilo.
{35200}{35333}-Pomagao sam u tom restoranu.|-Kada?
{35372}{35484}Proöle nedelje pre nego öto sam |uhapöen. Ali, imao sam osam, ne öest.
{35513}{35691}-Pa? -HoÊe da kaûe da su policajci|uzeli neöto za sebe, ali i öest je dovoljno.
{35708}{35794}On je samo ûrtva. -To je istina.|-Da Ëujemo joö malo istine.
{35937}{36057}-Otvaram i taj tip "Veverica" |ulazi. -"Veverica"?  -Da.
{36106}{36182}-Tako ga zovu na ulici.|Samo znam da tip prodaje.
{36195}{36286}-Drogu? -Ne, ne "Veverica".|On prodaje sitne stvari, lanËiÊe...
{36335}{36446}stvarËice öto stavljaö na narukvice i|to. -I bio si zainteresovan za tu robu?
{36459}{36607}-Baö me briga za njegova sranja.|Posmatrao sam ga i izvadio je to.
{36646}{36739}I video sam taj medaljon sa lancem.|Pitao sam ga odakle mu to.
{36763}{36861}Jer to ne izgleda kao neöto öto on|ima. Tu postaje smeöno jer 
{36868}{37015}poËinje da uvrÊe oËima. Kaûe mi:|"N-nemoj da b-brineö, i-imam mesto z-za to"
{37032}{37135}Taj tip je lud. Ne ume uopöte da|priËa, ali sam pomislio kakve veze ima.
{37148}{37230}"Samo hoÊu da pogledam to"|Pa mi ga je dao.
{37243}{37351}Gledam ga i crteû je star.|Vidi se da ne vredi niöta.
{37364}{37453}pitam ga: "Ko Êe da kupi takvo |sranje?", a on mi kaûe:
{37480}{37565}"K-Kin eto ko" neko ko|se zove Kin.
{37580}{37623}"Kako misliö Kin? Ko je Kin?"
{37667}{37780}Onda mi ga uzme i otvori ga, a |unutra slike dve bebe.
{37826}{37938}I kaûe mi da mu je to dala mama|jer m uduguje neki novac.
{37963}{38043}"Joö mi nije platila, ali Êe Kin|da mi da sve öto mi ona duguje"
{38073}{38221}Nisam razumeo öta mi priËa dok mi |jasno nije rekao: "Mama je sad mrtva"
{38254}{38343}Rekao je da je öestoro palo i da sam|to Ëitao u novinama proöle nedelje
{38367}{38416}a ja sam mu rekao da moûe da me|poljubi u dupe jer ja ni o Ëemu nisam Ëitao.
{38453}{38575}On kaûe: "Jesi, jer ona nije bila|jedina koju su naöli"
{38606}{38652}"Odradio sam joö dvoje u isto vreme"
{38720}{38757}-Rekao je da ih je "odradio"?|-Tako je rekao.
{38783}{38874}-Rekao sam da mu treba pomoÊ jer |mu ne verujem ni reË. Nije ni pokuöao da
{38897}{38985}se raspravlja sa mnom. Rekao je|da ga je briga öta verujem.
{38993}{39087}Samo da zna da Êe, kada se sve ovo|slegne, dobiti otkup od tog Kina.
{39118}{39153}-Otkup? -Tako je rekao.
{39179}{39315}Razmiöljao sam i setio sam se|te pucnjave.
{39332}{39406}Rekao sam mu: "Znam da ne |priËaö o tome" i on me je samo
{39427}{39513}pogledao i rekao" Nema veze|öta ja priËam".
{39642}{39706}-To je to? -To je to. |Meni to zvuËi dovoljno.
{39729}{39810}-I "Veverica" je sve öto imaö.|-Da, to je sve öto znam.
{39864}{39934}äta mislite? Vredi paklice?
{40023}{40143}-Vredi paklice, ali prvo mora|da bude istina.
{40541}{40648}-Leo? -Lari, öta radiö ovde meu|pravim herojima? -Odmaram se.
{40666}{40742}-Svi smo ovde övorc.|-Ta ti je dobra, Leo.
{40785}{40865}-Znaö li nekoga "Vevericu"?|-Veverica Gendalf? -Imam samo Veverica.
{40894}{41022}-Lopov, prestupnik. -Znaö li o kome|govoriö? Romio Gendalf mu je majka.
{41028}{41087}-Znaö li gde mogu da ga naem?|-Naravno da znam.
{41135}{41241}-Zatvoren je. Pokupili smo|ga sinoÊ. -Zbog Ëega?
{41274}{41367}-Zbog istoga. Veverica voli da|se zakljuËa u prodavnice noÊu.
{41392}{41513}Prespava i ode pre jutra. Izabere|neöto, zakljuËa i ode.
{41718}{41766}-Da li je imao neöto kod sebe kada|ste ga uhvatili?
{41786}{41837}-Nije imao periku. -Pa, öta je imao?
{41905}{41989}-Traûiö neöto posebno? -Da, nakit,|medaljon.
{42028}{42113}Znaö, lice. -Da, znam öta je|medaljon.
{42158}{42217}-Mogu da pogledam u knjigu stvari.
{42256}{42297}-NeÊeö ga naÊi tamo.
{42345}{42405}-Zato öto ga nije imao kod sebe?
{42445}{42520}-Ne. -To je loöa vest, Leo.
{42570}{42669}-Da, treba da popriËaö sa|Vusnikijem.
{43059}{43189}-Starzik Leri. -Zdravo, Ajk, joö uvek|prodajeö alkohol srpovodiocima zakona?
{43207}{43280}-»im zatraûe? -äta Êeö ti?|-Na duûnosti sam.
{43307}{43358}-Bilo öta sa ledom.
{43376}{43480}-Jesi li viao Toma Vusnikija?|-Ne, od kako gledam u piÊe.
{43686}{43797}-Kako ide Ajk?|-Onako.
{43952}{43975}-Vusniki?
{44037}{44059}-Starzik?
{44074}{44174}-Jesi li reöio ono sa starim Gasom?|-Moûemo li da popriËamo? -Naravno.
{44209}{44256}SaËekaj u kolima, duöo.|-Ne, saËekaj ovde, duöo.
{44289}{44359}-Ako imaö neöto da kaûeö, reci|jer sam na krenuo.
{44375}{44480}-Krenuo si ti u suspenziju. Zavisi koliko|si puta ovo veÊ uradio.
{44500}{44597}-Uradio öta? -Ukrao zatvorenikovo|vlasniötvo i poklonio ga devojci.
{44871}{44953}-Stiöajmo ovo. Nije hteo da skine|periku pa sam ga nauËio lekciji.
{45067}{45213}-äta? -ReÊi Êu ti ötetu. Nemam dokaze.|Ni u knjizi ni tamo gde treba da stoje.
{45232}{45288}äta misliö da Êe Berni advokat da|uradi sa tim?
{45507}{45618}Veverica je imao to.|Ne verujem mu. On je ubre.
{45647}{45721}Ali nije takvo ubre. -Moûda|moûeö da se zaloûiö za njega.
{45749}{45799}-Ne ugroûavaj ovim moj posao,|znam da Êu da svedoËim.
{45864}{45988}-Gde su slike? -Slike?|-Slike dece mrtve ûene!
{46026}{46057}-Nije bilo nikakvih slika.
{46139}{46167}-Jel' da?
{46213}{46238}-Bacio sam ih.
{46319}{46414}-Sebe zoveö policajcem, Vusniki.|Ja te ne zovem.
{46564}{46629}-Reci öerifu, da sam i ja|uËestvovao u tom hapöenju.
{48323}{48430}-Jesi li to video nekada, Veverice?|-Ne seÊam se, ali dobro izgleda.
{48486}{48529}Moûda se seÊam da sam video neöto |takvo. -Moûda se seÊaö?
{48546}{48585}äta to treba da znaËi da se moûda seÊaö?
{48620}{48738}To sam uzeo od policajca koji je to|uzeo od tebe. SeÊaö se policajca Vusnikija?
{48758}{48836}-To je u redu ako je tako rekoa.|-Zoveö policajca Vusnikija laûovom?
{48850}{48927}-Ne, nisam rekao laûo. Ti si to|rekao. Nisam ja to rekao.
{48947}{48986}-Pa da li je? Laûov?
{49053}{49142}-Pre bih rekao prevarant. Neki |prevaranti su laûovi, jel' tako?
{49196}{49322}-Moûda si u pravu u vezi sa tim|Veverice ili viöe voliö da te zovem Romeo? 
{49370}{49435}-Ne, Veverica je sasvim u redu.|-Dobro.
{49524}{49594}-Je li ovo tvoje?|-Policajac je to ukrao od mene.
{49617}{49686}-Zaboravi to na sekund, Romi.|Kako si ga uopöte dobio?
{49773}{49925}Vidiö, mislim da to zahteva odgovor.|To je ukradeno vlasniötvo koje je
{49938}{50008}bilo kod tebe. Posedovanje tueg|vlasniötva. Znaö to. Bio si ovde.
{50032}{50114}-Ja ga nisam ukrao. -Pa, kako si|ga dobio' -Nisam rekao da sam ga dobio.
{50130}{50231}-Pripadao je ûeni koja se zvala|Luiza Rimarti. -Kome?
{50288}{50324}-Znaö Luizu Rimarti?
{50414}{50502}-Znao sam da Êeö me to pitati.|-To je bitno pitanje.
{50553}{50713}VeÊ sam to video, znao sam da Êeö|priËati tako. Nisam samo naleteo na tebe.
{50741}{50850}Samo smo ti i ja. Nema svedoka, |nema dokaza. Samo da bude jasno.
{50869}{50978}éeliö da stvari budu jasne, zar ne?|Izmeu tebe i mene, mislim da si
{50992}{51097}u pravu öto se tilËe policajca Vusnikija.|-Vusniki. -Ali ja nisam Vusniki.
{51114}{51175}I ne idem nikuda jer nisi|iskren sa mnom.
{51397}{51425}-Gde su deca?
{51807}{51850}-Koja deca bi to bila, Romi?
{51907}{51968}Znaö li Gasa Nidlsa, Romane?|-Ne seÊam se ni jednog...
{51986}{52058}-Ne igraj se sa mnom, Veverice.|Znaö Gasa jer te je isterao iz
{52075}{52162}restorana mnogo puta, iöutirao te|napolje... -To je bilo odavno.
{52198}{52273}-Znaö li gde je Gas sada?|-Da, znam.
{52292}{52339}-I Luiza Rimarti, znaö li gde je ona?
{52379}{52479}I da je ovaj medaljon, u kome nema |njene dece, uzet od nje.
{52516}{52615}Od Luize Rimarti. To je ime ûene|koje ne moûeö da se setiö.
{52697}{52817}Evo öta ja mislim. Mislim da si se krio|kod Gasa kao i obiËno i on te uhvatio.
{52836}{52992}I pretio ti. I bilo ti je dosta, baö tad.|Krenuo je ka puci, ti si prvi stigao do nje i....
{53046}{53144}Gas je nestao, ali su bile samo dve|muöterije Luiza Rimarti i Pol Dûetson
{53158}{53328}pa su i oni otiöli. Poöto nisi pravi|ubica nego sitni lopov sve si pokupio
{53349}{53451}ukljuËujuÊi ovo i zato je bilo kod tebe|kada si bio uhapöen.
{53489}{53568}äta si uradio sa piötoljem, Romi?|Gde si stavio piötolj kada si ih upucao?
{53612}{53697}-Upiöao sam se.|Zbog tebe sam se upiöao.
{53792}{53899}Mislim da je to tvoja savest, Romeo.|PriËaö kroz svoju beöiku.
{53969}{54072}-U redu. Kako to da sam uradio sve|to, ubio troje ljudi, kako da se ne seÊam?
{54095}{54199}-To Êemo da uradimo, Romi. Samo |ti i ja da ti pomognemo da se setiö.
{54229}{54305}Ali, prvo da ti donesemo suve|pantalone. I joö neöto.
{54353}{54486}Dok Ëekamo, öta misliö da probamo|ovo. Neka bude da znam da si ovo uradio.
{54557}{54644}Samo da pretpostavimo da znam.|-U redu, pretpostavimo.
{54668}{54803}-Tako je. Pretpostavimo da stvarno|znam kao da sam video na kameri.
{54831}{54959}-Gas ih je imao. -Recimo da jeste i|ti si na njoj, samo se ne seÊaö.
{54989}{55066}Kako bi to objasnio? Uradio si to,|ali se ne seÊaö.
{55097}{55132}-Ne znam. -Kako je to moguÊe?
{55217}{55279}-Moûda su mi izbrisali pamÊenje.|Ne seÊaö se niËega.
{55335}{55368}To bi bilo objaönjenje.
{55546}{55623}-Gospdodin Gandalf je imao nezgodu.|Vidite da mu naete neke suve pantalone.
{55647}{55683}Odmah, veoma je neprijatno.
{55868}{55911}äta je sa tim drugim poslom?
{55957}{56049}-Kojim drugim poslom? -Kresao si |pozadi nakon öto je umrla.
{56078}{56156}-Nikada nisam uradio neöto takvo.|Koliko god da je mrzim, ja...
{56206}{56295}-Zaöto si je mrzeo? -Ona je bila|jedna od onih kuËkastih ûena.
{56324}{56411}ObeÊa jedno, a radi drugo.|Takva je bila.
{56465}{56611}Zovem se Romeo Gandalf, imam |34 godine i Ëitam i piöem engleski.
{56678}{56775}Dajem ovu izjavu slobodno i |svojevoljno i niko mi nije niöta obeÊao
{56815}{56986}da bih dao izjavu. Razumem da |se snima dok je Ëitam.
{57069}{57259}TreÊeg sptembra 1996 svratio sam|u restoran Gasa "Raj".
{57300}{57419}Krio sam se i naöao me je. Jednom |me je pretukao i plaöio sam se
{57433}{57479}da Êe to ponovo da uradi...
{57529}{57605}Imao je piötolj u kasi. To znam |zato öto je pretio da Êe me upucati.
{57665}{57734}Otiöao sam po piötolj i on mi je priöao.|Pucao sam pre nego öto sam shvatio
{57751}{57800}öta se deöava. Tamo je bilo|joö dvoje ljudi...
{57854}{57940}-Deö, da ti dam vizitku moje nove|firme. -U redu. Hvala.
{57985}{58088}-Kako ide, Lari? -Zdravo, Arture.|Ide odliËno. Mjurijel ga je nagazila.
{58123}{58232}-"Ogrejdi, Stajnberg, Markoni i Hogan"|ne treba da se brineö sa Irce?
{58291}{58403}Bar nisi otiöao na mraËnu stranu.|Mislim isto öto i ti o advokatima odbrane.
{58450}{58512}-Niko ne misli kao ja o advokarima|odbrane, savetniËe.
{58632}{58665}-Svi ustanite.
{58924}{59001}-Gdine Gandalif izborili ste izmeu prava|da vam se sudi pred porotom  u konsultaciji
{59018}{59101}sa vaöim advokatom i odabrali ste|ovakvo suenje. Nakon öto sam Ëula
{59117}{59235}dokaze i vaöu izjavu proglaöavam vas|krivim po optuûnici za ubistvo Gastasa Dislinidasa,
{59257}{59323}Luize Rimarti i Pola Dûetsona.
{59695}{59715}-Hvala vam mnogo.
{60007}{60118}-NaredniËe, Starzik, Talmedû Norman,|Mjurijel mi je priËala o vaöem sjajnom radu.
{60182}{60271}-Hvala. imali smo sreÊe.|-Mjurijel  ne opisuje to tako.
{60294}{60325}Ona kaûe da ste najbolji.
{60450}{60481}»estitam. -Hvala.
{60543}{60576}-Mora da se odliËno oseÊam.|-Da.
{60635}{60681}-Martini? -Da. -U redu, u redu.
{60744}{60771}-Ne treba mi ovo.
{61094}{61113}-Sudijo Saliven...
{61212}{61237}-Samo sanjajte, savetniËe.
{61289}{61319}-Te, samo...
{61499}{61690}-Romeo Gandalf biÊete u zatvoru |gde Êete ostati tokom trajanja
{61708}{61772}iikakvih ûalbi koje moûete da |podnese. Ako se sud ovog suda
{61787}{61962}zadrûi do daljnjeg, biÊete kaûnjeni|smrtnom kaznom smrtonosnom injekcijom.
{62663}{62734}SEDAM GODINA KASNIJE
{62769}{62841}-Ove male stvari nas iskuöavaju,|Arture otkad sam izabran za sudiju.
{62875}{62903}-Ali zaöto ja, Voltere?
{62924}{62957}-Svi dobijamo i po neöto teöko |uz ono lako.
{62985}{63055}Apelacioni sud zavrti Ëarobnim |ötapiÊem i pretvara nekog ûapca
{63069}{63148}sasvim neûeljnog prezauzetog |advokata besplatno u divnog princa.
{63167}{63244}Daje mu zahtevnu klijentelu koja|ne plaÊa za koju treba da juri.
{63261}{63331}-TehniËki, mogu sebe da optuûim|za nezalaganje.-Zaista?
{63345}{63413}Nisam znao da radiö na sluËaju |Gandalf. -Dostavio sam prve naloge
{63429}{63470}za pretres sudiji Saliven da potpiöe.
{63509}{63597}-Po mom, veoma skupom, zakonitom|miöljenju to nije problem.
{63706}{63794}Dobro Êe ti doÊi da se odvezeö do|zatvora u svom novom automobilu,
{63813}{63911}imresioniraö klijenta da zna da ga |zastupa Ëovek koji ima automobil
{63928}{63965}vredan 60.000$. 
{64322}{64391}-11 sati, Gandalf. -Potpiöite ovde.|Govornica broj tri.
{64690}{64707}-Hvala.
{65186}{65257}-Ja sam Artur Rejven, advokat koji vam|je dodeljen od suda, gdine Gandalf.
{65293}{65394}-Ti si pravi advokat? -Da, jesam kao|öto sam siguran da su i svi drugi bili.
{65413}{65510}-Moûda su i bili, ali nisu niöta uradili|za mene jer je to bila samo priËa.
{65540}{65604}-Ja se ne razlikujem. -Razlikujeö se.|Ti si mi poslednja nada.
{65637}{65673}Ako neöto ne uradiö ja sam mrtav.
{65701}{65808}-Da vam neöto objasnim. Jedini|napredak u menjanju vaöe kazne
{65826}{65911}jeste ako nabavimo nove dokaze ili|dokaûemo nedostojno ponaöanje tuûioca.
{65932}{66018}Imate li neke nove dokaze?|-äta sa DNK? 
{66049}{66142}Neka me testiraju da vide da li imam|neöto od toga. -DNK nije bilo bila 
{66161}{66241}bitna za vaöe suenje. Nije bilo krvi, |vlakana ili sperme kao dokaza.
{66265}{66311}Zapravo, vi ste priznali ubistva.
{66397}{66540}-Da li su vas silili na neöto? Da li je|sila upotrebljena protiv vas?
{66562}{66668}-Upiöao sam se zbog policajca.|-Koliko se seÊam, tuûilac je tvrdio
{66686}{66750}da ste se upiöali iz krivice. -Mislio|sam da treba da se uneredim zbog toga.
{66797}{66914}Ne znam. -Da vas pitam, gospodine....|Mogu li da vas zovem Romeo?
{67025}{67054}Kako da vas zovem?
{67094}{67172}VeÊina ljudi me zove Veverica, ali|mi se svia gospodin Gandalf.
{67201}{67306}-U redu. Gospodine Gandalfe, |prihvatiÊu da ste potpisali ovo priznanje.
{67328}{67435}HoÊu da i vi to prihvatite. U njemu |priznajete da ste ubili troje ljudi, ali
{67448}{67511}poriËete da ste sodomirali ûrtvu|Luizu Rimarti.
{67535}{67611}Zaöto ste to poricali kada je autopsija|ustanovila da se to dogodilo?
{67644}{67689}-Jer ja niakda ne bih uradio tako|neöto.
{67740}{67832}-Niste je sodomirali.|-Ne, ËoveËe. To je neöto prljavo.
{67851}{67879}-Ako vi niste, ko je onda?
{67909}{67968}-Moûda je to bio onaj koji je ubio|nju i ostale. Ne znam.
{68067}{68147}-Da li ste se podvrgli detektoru laûi|kada ste davali priznanje?
{68163}{68233}-Detektor laûi sa iglama koie skaËu|gore dole. Da, uradio sam to.
{68274}{68366}Prokleta stvar je baö skakala.|Da li je to dobro?
{68406}{68491}-Ne, to nije dobro.|Niöta nije dobro.
{68540}{68586}Moûda Êe proÊi neko vreme pre|nego öto budem mogao da se vratim ovde.
{68602}{68653}-Naite mi novog sudiju.|Ne, kao ona matora.
{68674}{68747}Neöto je zeznula. Meni je |neöto smutila sigurno.
{68828}{68854}-PokuöaÊu.
{69170}{69211}SUDIJA UMEäANA U SKANDAL|POTKUPLJIVANJA
{69275}{69296}SALIVEN REAGUJE NA OPTUéBE
{69320}{69365}LEDENA KRALJICA SE TOPI
{69394}{69421}SALIVEN DOBILA äEST GODINA
{69801}{69825}-Tamo. -Hvala.
{69938}{69964}Izvinite me? -Da?
{70118}{70144}Kako mogu da vam pomognem?
{70217}{70243}-Hvala. -Hvala.
{70262}{70301}-Neki sok? |-Ne, samo kafu.
{70362}{70393}-älag? -Ne. 
{70485}{70527}-Gdine Rejven, ako nemate posla,|kao öto ste rekli...
{70551}{70639}-Vi ste bili predsedavajuÊi na suenju|Romeu Gandalfu. -I ûelite da znate
{70655}{70755}da li sam ikako bila nepodobna za|to. Nisam bila po uticajem alkohola
{70772}{70824}tokom suenja gdinu Gandalfu|ako to ûelite da znate.
{70844}{70937}-Video sam vas tog dana. Nema |sumnje da ste potpuno kompetentni.
{71012}{71053}-Pa, öta ûelite da me pitate?
{71088}{71147}-Da li ste ikada ponudili odbrani da|se pozove na ludilo?
{71217}{71327}-Kao sudija traûila sam da mi se|pruûe svi dokazi. -Ali nije bilo uverljivo?
{71347}{71416}-Niöta ne bi podrûalo tvrdnju |neuraËunljivosti. Mjurijel Vin je imala
{71433}{71498}video traku sa priznanjem. Nije bilo|znakova da je bilo prisiljavanja i 
{71513}{71583}savetnik gdina Gandalfa nameravao|da se posluûi tim.
{71597}{71667}-»ovek nije bio baö obrazovan na|Harvardu. --Bio je kvalifikovan advokat.
{71695}{71766}Vi ste sigurno dovoljno pametni da|traûite klupsko suenje jer je on mislio,
{71788}{71867}sasvim razumno, da sam meka na|velikim kaznima. Dotle nikada nisam
{71884}{71964}izdala smrtnu kaznu. -Da li vam|je bilo teöko da to uradite?
{72005}{72085}-Ne znam kakve to veze ima sa|bilo Ëim. Poötovala sam zakon.
{72139}{72223}-Da li vam je bilo Ëudno öto je|Gandalf priznao ubistvo troje ljudi, 
{72248}{72385}ali poroicao sodomiranje? -Kriminalni|um je i bizaran i banalan po mom iskustvu.
{72434}{72461}-Uûivajte.
{72530}{72559}-Nedostaje vam zakon?
{72610}{72684}-Nisam doöla ovde da odgvaram |na svoja liËna oseÊanja.
{72715}{72774}-Izvinite. Uvek sam vam|se divio na klupi.
{72918}{72943}-Imate li joö neko pitanje?
{73008}{73107}-Ne. Hvala vam. -Izvinite me, ali|zavröila mi se pauza za ruËak.
{73142}{73213}-Nisam shvatio zaöto se odabrali da|se vratite ovde nakon uslovne kazne.
{73253}{73304}Izvinite, izvinite. Oprostite mi.
{73345}{73412}Oproötaj se ne traûi.|Prijatan dan.
{73509}{73558}-To bi bilo to? -Da, hvala.
{73577}{73624}-Da li je to sudija koja je bila|u zatvoru? -Da.
{73649}{73696}-Mnogo njuöka za bivöeg robijaöa,|rekla bih.
{74015}{74108}-Dobili ste Artura Rejvena, molim |vas ostavite poruku.
{74126}{74267}-Zove Dûilijen Saliven, ostaviÊu vam|svoj kuÊni broj, moûete... -Izvinite, nisam
{74287}{74379}digao sluöalicu, ja...|éao mi je ako sam vas uznemirao.
{74403}{74531}-U redu je, bila sam preosetljiva.|Zovem vas zato öto sam neöto zaboravila.
{74551}{74640}Neöto öto je znaËajno za vaöeg|klijenta. Mogu da svratim do vas na
{74653}{74749}poslu sutra.... -Ne morate to da radite...|-Ne, zavröimo sa ovim.
{74790}{74911}Vidimo se sutra u 9.30? -To bi bilo|sasvim u redu. -Hvala. Dovienja.
{75378}{75406}-äta li ona radi ovde?
{75524}{75619}-Dûen Saliven, mnogo vam hvala|öto ste doöli. -Hvala vama.
{75637}{75664}-Molim vas.
{75840}{75888}-Verovatno Êete misliti da sam|bezbriûna kada proËitate ovo, 
{75914}{75976}ali sam to primila pre par meseci|i to sam shvatila kao neöto öto
{75990}{76041}je vezano za moj prethodni ûivot.
{76063}{76134}SeÊam se da sam jednom imala |priliku da se odrazim.
{76191}{76266}Smrtnu kaznu sam proglasila samo|dva puta. U drugom sluËaju kazna
{76286}{76371}se odugovlaËi od kako je doöena.|To mora da ima neke veze sa vaöim klijentom.
{76432}{76474}-MoraÊemo da odemo tamo.|U zatvor.
{76562}{76644}-Volela bih da ne budem dalje umeöena.|-Ovaj zatvorenik je pisao vama.
{76666}{76734}HoÊe da razgovara sa vama. Morate|da ga ubedite da razgovara sa mnom.
{76750}{76806}Ne ûelim da to uradim.|Zaista ne ûelim.
{76875}{77014}-PokuöaÊu sa ovim. ObeÊavam |da Êu se zaista potruditi, ali ako ne mogu
{77097}{77122}hvala vam öto ste doöli.
{77265}{77390}Marta, moûeö li da pozoveö |upravnika zatvora? -Naravno.
{77574}{77668}Sudijo Saliven, ovo piöem zato öto |imam neke informacije. TiËu se
{77681}{77797}sluËaja pre vaöeg gde ste osudili|Ëoveka na smrt. On je ovde u zatvoru.
{77815}{77903}I on je zapravo sledeÊi koji Êe da|"odöeta" pa je ovo nekako hitno.
{78021}{78042}OdliËno, daj mi ga.
{78085}{78165}UpravniËe, ovde Artur Rejven. Neöto|je iskrslo öto se tiËe mog klijenta
{78186}{78207}Romea Gandalfa.
{78899}{78923}-Potpiöite se, molim.
{79020}{79037}-Samo dama.
{79089}{79149}-Stvarno mi je ûao. Samo ga pitaj|da li Êe da razgovara sa mnom.
{79172}{79212}-Ako kaûe ne? -OdveöÊu te nazad.
{79379}{79394}-Ovuda.
{79462}{79481}SaËekajte ovde.
{79840}{79859}-Evo, proite.
{79966}{79990}Odmah Êe doÊi.
{81032}{81107}-Ako planirate da ponovo dolazite,|ne bih dolazila kada imaju odmor.
{81143}{81169}-Ne planiram da dolazim ponovo.
{81490}{81535}-Evo vaöeg momka. BiÊu ovde|ako vam zatrebam.
{81924}{81995}-Pa, poöta se konaËno probila?
{82049}{82083}Joö uvek izgledate priliËno|dobro, sudija.
{82141}{82248}-Nisam sudija, to dobro znate.|-Tako uvek mislim o vama.
{82402}{82456}-Koliko dugo ste bolesni?|-Nekoliko godina.
{82500}{82537}Samo öest meseci traje ovako.
{82579}{82650}Ubrzo izlazim odavde. |-Dobili ste puötanje.
{82670}{82700}-Kaûu za par meseci.
{82803}{82885}Ko bi rekao da Êe biti tako brzo?|Koliko ste vi odradili?
{82925}{82994}Izvinite, nisam doöla ovde da |razmenjujemo zatvorska seÊanja.
{83011}{83057}Doöla sam samo da vas pitam da li|biste razgovarali sa advokatom o
{83070}{83137}vaöem pismu meni. Ako se naravno,|to odnosi na Romea Gandalfa.
{83172}{83314}Niste bili iskljuËivi. -Ako je to tip|koji je presudio Gasu, onda se o njemu radi.
{83691}{83709}-VideÊe vas.
{83775}{83809}-Jeste li dobro?
{85566}{85645}-Zaöto je gospodin Erdaj u zatvoru?|-Upucao je Ëoveka.
{85690}{85726}»ovek je preûiveo, ali je Erdaj |dobio osam godina.
{85781}{85863}-Da li vam je bio od pomoÊi? |-Ne mogu o tome da diskutujem sa vama.
{85912}{85965}Ali, vam hvala. éao mi je öto|ste morali da ulazite unutra.
{86026}{86062}-Miris je u pitanju viöe od svega.
{86122}{86204}Nakon öto sam izaöla, samo|sam se tuöirala i tuöirala dok nisam
{86217}{86255}shvatila da miris nije bio|na mojoj koûi.
{86403}{86472}Bio je u mojoj glavi.|I joö uvek jeste.
{86520}{86563}Pre nego öto sam otiöla u|zatvor mislila sam da,
{86605}{86719}kada kriminalci odrade svoje,|to bude iza njih, ali nije.
{86797}{86843}To je öteta koju nosiö unutra.
{86910}{86987}Kao da si se zagadio.|To je zapravo taj miris.
{87032}{87075}Miris protraÊenog ûivota.
{87173}{87275}-Moram da vas imam na sudu da biste|potvrdili autentiËnost pisma.
{87380}{87414}Toga sam se plaöila
{87851}{87879}-Zdravo, Leri.
{87936}{87952}-Zdravo.
{88012}{88119}-Lepo te je videti- Izgleda da se samo|nije promenilo to öto sam stariji od tebe.
{88245}{88320}-Zvala si? -Artur Rejven zastupa|Vevericu Gandalfa.
{88334}{88467}-Vevericu, zar ga joö nisu smaknuli?|-Ne, to je jedno od onih sudskih odvlaËenja.
{88486}{88591}Artur ima neöto i povukao je sudiju|Harloua koji voli da igra poslednje
{88609}{88684}utoËiöte ûrtve pre nego öto |Êe na kraju dopustiti da se sve desi.
{88702}{88801}-Artur je sada advokat odbrane?|-Ne joö uvek je sa Ogrejdijem, Stajnbergom...
{88825}{88916}ali je apelacioni sud to svalio na njih,|a oni na Artura. -äta ima?
{88950}{89058}-Ernala Erdaja. -Ernala?|äta Ernal ima sa Vevericom?
{89084}{89145}-Ne znam. Ubrzo Êemo saznati.|U Harlovoj sudnici u dva.
{89174}{89227}äto nam daje dovoljno vremena|da raËumo i da se ispriËamo.
{89403}{89529}MJURIJEL VIN Ime govori sve|Za tuûioca
{89602}{89636}-Izvolite, gice Vin.|-Hvala, Franko.
{89702}{89802}-Izgledaö divno. To bi bilo to|»ak i na bilbordima.
{89879}{89947}-Prestao si da puöiö?|-Trudim se.
{89974}{90042}-Ionako viöe nema mesta gde|moûeö da puöiö.
{90074}{90147}-Nisi se ni malo promenio.|-Verujem da je to zbog kuÊa.
{90168}{90239}-KuÊa? -Da, pre par godina sam|poËeo da ih renoviram i prodajem.
{90255}{90308}-Stvarno? Moûeö sve to? Tapiseriju,|ElektriËne radove? 
{90323}{90450}-Da, imam svoje knjige "Uradi sam".|I ako radiö polako sve bude jasno.
{90491}{90584}-Nisam znala da te zanimaju takve|stvari. -Uvek si znala öta si htela.
{90613}{90639}-Meni je trebalo duûe.
{90672}{90741}-Boûe, nisi samo ruûna faca,|zar ne Starzik?
{90782}{90817}-Trebalo bi da znaö, Mjurijel.
{90900}{90998}-Jesi li joö uvek oûenjen? -I to je|propalo. -éao mi je öto to Ëujem.
{91014}{91060}-Helen je dobra ûena, zaluûila|je dobrog muökarca.
{91074}{91127}-Uvek sam mislila da si ti dobar|muökarac. -Imam svoje momente.
{91231}{91261}-Kako ste ti i Tolmadû?
{91308}{91377}-Tolmadû vodi ûivot koji ga celog|obuzima. Ja vodim ûivot koji me
{91389}{91470}uglavnom zadrûava ovde. Kada smo|zajedno dosta razgovaramo.
{91505}{91593}On stvari prihvata stvari, ja ih zovem|ptiËija perspektiva. Sa svim mojim
{91622}{91712}problemima mislim da viöe doprinosim|druötvu nego on.
{91762}{91887}Imamo divnu kuÊu i povremeno idemo|na divne odmore. Ne Ëesto...
{92003}{92025}-Kako je u krevetu?
{92083}{92108}-Dobro je.
{92154}{92184}-Nemate decu? 
{92220}{92253}-Ne, nemamo ih.
{92307}{92410}-Zbog toga najviöe ûaim.|-Svi ûalimo zbog neËega.
{92550}{92571}-Jeste li spremni da naruËite?
{92673}{92752}-Koliko Êe trajati? -KuÊa je velika.|Sigurno Êe mi trebati dve godine.
{92811}{92846}Pa, bar se tako nadam.
{92972}{92996}-Jesi li video ko je to?
{93030}{93117}-Da. Ledena kraljica, suenje|Veverici. äta ona radi ovde?
{93131}{93165}-Nemam pojma. Artur je stavio na|listu svedoka?
{93185}{93260}-NeÊe biti neka zanimljivost.|Bila je uhapöena zbog mita.
{93278}{93342}-Nakon öto je napustila kriminalni|sud, znam. Pijana za klupom, kakva öteta.
{93373}{93458}Nekada sam da budem na Ëasovima|Dûilijen Saliven, i da budem viöa.
{93484}{93538}-Uvek moûemo da uzmemo par|santimetara.
{93563}{93618}-To je smeöno, Leri, ne seÊam se |da ti je to bio problem.
{93859}{93936}-Obratite paûnju i biÊete sasluöani.
{94201}{94234}-Moûemo li da priemo, visosti?
{94270}{94299}-Moûete.
{94435}{94557}-Imam ovde Dûilijan Saliven kako|bi potvrdila da je primila pismo
{94580}{94645}zbog koga sam posetio gospodina|Erdaja u zatvoru.
{94665}{94717}-Dûilijen Saliven? Sudija Saliven?|-Tako je.
{94739}{94813}Ako optuûba ima neöto protiv|mogu da otpustim svedoka.
{94834}{94889}-Ako kaûete da je dobila pismo od|Erdaja, to je u redu, ali mi bismo
{94905}{94934}da ga vidimo.
{95111}{95169}-U redu. -U redu, krenimo.
{95206}{95240}Uvedite gospodina Erdaja, molim.
{95847}{95882}-Moûete da idete.
{96049}{96165}-Da li se kunete da Êete govoriti|istinu i samo istinu? -Da.
{96191}{96232}-Moûete li da kaûete svoje ime i|spelujete ga?
{96259}{96466}-Ernal Erdaj. E-R-N-A-L   E-R-D-A-J.
{96767}{96797}-Nastavite, gospodine Rejven.
{96985}{97043}-Moûete li da kaûete sudu|gde trenutno boravite?
{97080}{97173}-Trenutno sam u zatvorskoj bolnici.|-Zbog Ëega?
{97228}{97337}-Imam rak pluÊa.|-éao mi je öto to Ëujem, gdine Erdaj.
{97374}{97416}-Za koji zloËin ste osueni?
{97448}{97515}-Pre Ëetiri godine sam se posvaao sa|nekim Ëovekom u baru i upucao sam ga.
{97537}{97616}-To nije naËin, ali sam ga upucao.
{97676}{97769}SreÊom, oporavio se kada sam |proglaöen krivim i dobio osam godina.
{97785}{97937}-Prisetite se treÊeg septembra 1996.|Moûete li da kaûete öta ste radili te veËeri?
{98108}{98201}-Ubio sam Luizu Rimarti, Gasa Linidasa|i Pola Dûetsona.
{98242}{98297}-Visosti, prigovor.|da, pretpostavljam.
{98320}{98437}Odbija se. Gospodine Rejven?|-RazumeÊu ako gica Vin traûi odlaganje.
{98453}{98537}-Nije taËno. Nismo dobili infomraciju|o svedoËenju ovog svedoka.
{98551}{98650}-Ovo je samo sasluöanje. Samo sam|hteo da dobijem zabeleûeno
{98669}{98718}svedoËenje gdine Erdaja öto je|moguÊe ranije s'obzirom na njegovo zdravlje.
{98755}{98869}-Odobravam odlaganje od 24 sata.|Gdin Erdaj ostaje u pritvoru u bolnici.
{99172}{99192}-Hvala vam.
{99692}{99720}-Taj kuËkin sin laûe.
{100030}{100119}-Svedok se podseÊa da je joö uvek|pod zakletvom. Moûete da nastavite.
{100144}{100161}-Hvala.
{100192}{100286}-Da li biste rekli sudu malo bliûe o|vaöoj poslednjoj izjavi?
{100479}{100578}-Bila je jedna devojka na aerodromu,|Luiza Rimarti, agent za avionske karte.
{100613}{100688}Da ne priËamo loöe o mrtvima, ali|Luiza je bila daveû. -Molim te.
{100948}{101026}-I pogreöio sam öto sam se spetljao|sa njom. -Bili ste zaljubljeni u nju?
{101045}{101145}-Moûda u poûudi. To je bila |neka vrsta opsesije.
{101202}{101347}Deöava se i kada ste sa nekim kao|Luiza morate da budete Ëvrsti pa
{101398}{101491}sam poËeo da pazim na nju i jedne |veËeri sam video ono öto sam i 
{101504}{101526}mislio da Êu videti.
{101644}{101769}Luiza se naöla sa nekim tipom na|aerodromu. Auto se tresao 40 minuta.
{101820}{101917}-Kada se taj susret dogodio?|-TreÊeg septembra 1996.
{101941}{101997}-Moûete li da identifikujete Ëoveka|koji je bio sa gicom Rimarti? -Ne.
{102029}{102072}Obukao je Ëizme i odvezao se.
{102333}{102374}Pratio sam Luizu do "Raj"-a.
{102453}{102522}Napravio sam scenu. Nazvao sam je|droljom, ona mene oûenjenim...
{102555}{102605}-Gledaö? Da li tvoja ûena zna kakav|si ti perverznjak?
{102622}{102692}-Tu se umeöao Gas -Gospodine, |ne moeûte tako ovde da priËate.
{102718}{102795}-Kaûe mi da odem, a ja da ona ide|sa mnom. Luiza kaûe da ne ide.
{102816}{102865}Pa sam je uhvatio i vukao.|Nije htela da krene.
{102898}{102917}Gas se vraÊa.
{102956}{103036}"Gas imaö, piötolj? Znam te,|neÊeö ti pucati ni u koga." 
{103049}{103086}"Pusti je! Odlazi! Sada"
{103135}{103204}-Pusti je! -NeÊeö pucati u mene i|ti to znaö. -Da...
{103272}{103315}-Ona se gubi i otima piötolj Gasu.
{103353}{103458}-Pokuöavam da je smirim i.... bum.
{103547}{103578}Dobila je veliku rupu u sebi.
{103682}{103839}Sedi i gledam kako izlazi krv iz|nje. Gas odlazi da pozove hitnu pomoÊ
{103857}{103932}i ja samo stojim i gledam kako mi|se ûivot pretvara u veliku mrlju na podu.
{104068}{104148}Dovienja poslu, penzijo, braku...
{104214}{104273}Pa kaûem Gasu: "»ekaj"|-Da Ëekam da umre?
{104292}{104427}-I bila je. Tu se presavila,|pa sa rekao da nema ûurbe jer je gotova.
{104449}{104507}-Nema ûurbe, mrtva je.|Malo sam se uzbudio.
{104605}{104724}Stajo je tu i vikao na mene sa piötoljom.|Mislio sam da Êe razmiliti, ali
{104746}{104804}"Zovem pandure" -Gas me|ne Ëuje i kreÊe ka telefonu.
{104826}{104923}Ja ga pratim i viËem: "»ekaj, Gas!"|I kada nije hteo...
{105019}{105047}Upucao sam ga u glavu.
{105138}{105165}I tako je otiöao Gas.
{105204}{105312}Pa sam pomislio, kada su svi veÊ|mrtvi, napraviÊu da izgleda kao pljaËka.
{105354}{105453}PoËeo sam da Ëistim i tada sam|video onog drugog kako se krije pod stolom.
{105549}{105595}-Da li ste primetili gdina Dûetsona |kada ste uöli?
{105620}{105698}-Ne bih rekao. ObraÊao sam paûnju|samo na Luizu.
{105745}{105865}Ali kada sam ga naöao, to je bilo |zeznuto. Luiza i Gas su bili kao...
{105905}{106054}zeznut trenutak... Bilo je loöe i sve...|ali se desilo pre nego öto sam razmislio.
{106083}{106204}Ali taj drugi momak je jednostavno|bio na pogreönom mestu.
{106315}{106330}-äta ste uradili?
{106367}{106438}-Rekao sam mu da odvuËe tela u |hladnjaËu. -Zaöto ste to uradili?
{106480}{106556}-Ne znam. Verovatno da mi da |vremena da razmislim.
{106650}{106668}-Stavi ih na vreÊe.
{106683}{106707}-I öta ste mislili tada?
{106761}{106815}-Dok je doneo Gasa znao sam da|Êu morati i njega da odradim.
{106859}{106890}Rekao sam mu da sedne u stolicu.
{107029}{107086}-OstaviÊeö me ovde?|-VezaÊu te.
{107220}{107307}-Tada sam i u njega pucao.|Bilo je brzo. To je sve öto mogu da kaûem.
{107366}{107427}Kao öto sam i rekao, onda sam |oËistio i uzeo sve stvari koje bi
{107441}{107545}i pljaËkaö uzeo i otiöao odatle|da saËekam da panduri dou po mene.
{107568}{107597}-Zaöto ste mislili da Êe doÊi po vas?
{107626}{107712}-Kada ubijete troje ljudi ne mislite da |bi doöli po vas, koliko god da su glupi.
{107766}{107849}-Zaista. Kada ste dobili ideju|da smestite Romeu Gandalfu?
{107927}{107962}-To je nekako bila sreÊa.
{108039}{108143}Znao sam Vevericu, gdina Gandalfa.|On je lutao po aerodromu i traûio 
{108155}{108204}neöto da uzme. VeÊ je uzimao|vlasniötvo aerodroma ranije.
{108287}{108395}Luiza je izgubila nakit, taj medaljon.|Ostavila ga je negde.
{108473}{108589}Veverica ga je uzeo. Ona ga nije|videla da je uzeo, ali je on bio u zatvoru.
{108653}{108768}Rekla mi je da joj javim ako se on|negde pojavi. Rekao sam da Êu da vidim.
{108855}{108920}Naravno on je to poricao.|Dok mu nisam rekao da je 
{108933}{109004}vredan i da moûe da dobije otkup|za njega. -Otkup?
{109032}{109150}Upotrebili ste reË "otkup"?|-Da, kao nagrada.
{109246}{109327}On je poËeo da priËa kako moûda|zna gde je i takve gluposti.
{109389}{109457}Pristao sam da platim par dolara i|ispadnem veliki heroj pred Luizom.
{109477}{109535}Naravno, to se deöava pre nego|öto je bila upucana. Posle toga sam
{109551}{109599}mi je palo na pamet da Veverica|moûe da odgovara.
{109625}{109722}Znao sam da se sakrivao u prodavnicama|nakon zatvaranja i onda ih pljaËkao.
{109742}{109795}»uo sam da je Gas naredio da|mu se ne muva oko lokala.
{109827}{109973}Znao sam da ima medaljon i onda|me je pozvao neÊak da Êe morati
{109988}{110044}da ode u zatvor na duûe vreme pa|sam odluËio da je to bilo to.
{110291}{110420}Moj neÊak Kolins Farvel|je duga priËa.
{110486}{110587}On je polu-crnac. Moja sestra,|nek joj je Bog u pomoÊi, je rano
{110629}{110717}umrla i trudio sam se da ne upada u|nevolje, ali mogao sam da Ëuvam snagu.
{110755}{110883}On je bio tri puta osuivan i |ûurka je bila gotova, pa sam rekao
{110955}{111046}Kolinsu za medaljon i kako moûemo|da se dogovorimo za njega.
{111065}{111127}-Da li ste mu rekli da ste ubili|troje ljudi? -On to nije znao.
{111176}{111217}-Ali je znao da ste pokuöavali da|smestite gdinu Gandalfu?
{111255}{111315}-Kolin je shvatio, moûda je blesav,|ali nije glup.
{111356}{111411}-Planirali ste ovo sa vaöim|neÊakom, öta se onda desilo?
{111436}{111528}-»ekao sa da se pojave panduri|i pitaju za Luizu i doöli su.
{111583}{111708}To je bio Leri Starzik. Leri je dobar|policajac i nije glup.
{111734}{111786}-Ali je zagrizao, zar ne?
{111860}{111882}-PopriliËno.
{111916}{112006}-Nikada niste pomislili da moûda|gdin Gandalf ima alibi za to veËe?
{112040}{112116}-Momci kao öto je Veverica su sreÊni|öto imaju gde da budu, briga ih za alibi.
{112158}{112213}-To je bila netraûena procena,|gospodine Erdej.
{112246}{112277}-äta da vam kaûem? 
{112432}{112469}Moûemo li da napravimo pauzu?|Sloöilo mi se.
{112548}{112576}-Sud pravi pauzu.
{112632}{112697}-Treba nam taj neÊak Farvel, da li|znamo gde je? -NaÊi Êu ga ja.
{112712}{112779}To Êe biti kraj Ernalove priËe.|-Nisi mu niöta poverovao?
{112794}{112889}-Jesi li ti? -Znam da laûe, samo ne|znam zaöto. -Zaöto? Zato öto
{112905}{112987}duguje nekoj bandi öto mu |Ëuvaju dupe sve ove godine.
{113006}{113117}Sada Êe da umre, on prizna i|oni spase brata. Sa tim zadovoljstvom
{113129}{113274}da tuûilac i policajac izgledaju|priliËno glupo. -Vidimo se na sudu.
{113648}{113699}SeÊate me se? -Da, seÊam se.
{113720}{113791}-»oveËe, baö neko svedoËenje.|äta mislite? 
{113812}{113868}-Mislim da su razlozi tog Ëoveka|suviöe jednostavni.
{113891}{113951}-Da li ste otiöli sa posla da biste|doöli ovde? -Bilo je u novinama.
{113978}{114012}-ZnaËi niste znali za nju i njega?
{114043}{114081}-Nisu postojali ona i on.
{114158}{114223}-Moûda Êemo morati ponovo da|razgovaramo sa vama, go Kerijer.
{114299}{114367}-Ne ûelim da se meöam u ovo.|-Ovde ste, zar ne?
{114420}{114463}Siguran sam da ste shvatili neöto|do sada.
{114594}{114666}-Lagali ste detektiva Starzika |1996. godie. Da li je to taËno?
{114701}{114803}-Jeste. -Lagali ste da biste natakli|omËu oko vrata drugog Ëoveka?
{114825}{114903}-Da. -Odvratna istina, zar ne?
{114927}{115019}-Nisam ponosan na to. -Zaöto bismo|onda sada verovali odvratnom laûovu?
{115048}{115101}-»ak i odvratni laûovi ponekad|govore istinu.
{115171}{115258}-HoÊete da kaûete da sada nemate|öta da izgubite dajuÊi ove izjave?
{115274}{115348}-Ako mislite da se brinem oko|smrtne kazne, ne brinem se.
{115364}{115417}-Mislite da laköe moûete sada|da se ûrtvujete?
{115445}{115475}-Ne znam da li bih to tako nazvao.
{115592}{115680}I mislim da to ne bih uradio da ne|umirem. Skidam to sa savesti.
{115703}{115799}-»oveka kog ste poslali na smrtnu |kaznu i tri ubistva odlaze tek tako?
{115823}{116015}-Priznao sam ih, Veverica,|bolje da odlazi posle sedam nego da umre.
{116037}{116108}-Mora da je teöko belom Ëoveku|koji nema veze sa bandama?
{116129}{116274}-To jeste. -Da,to stalno govorite,|ali zar nije istina da ste pod zaötitom bande.
{116301}{116386}-To je novost za mene. -I da je|priznanje ubistava vrsta brze odmazde?
{116434}{116512}-Ako u to verujete. -Rekli ste da |je narednik Starzik dobar detektiv?
{116527}{116611}-Jedan od najboljih. -Mora da ste|bili nervozni dok ste mu prodavali priËu.
{116625}{116726}-Tako je bilo. Da sam mogao da biram...|-Zaöto ste sodomirali Luizu Rimarti?
{116742}{116824}-Ja to nisam uradio. -Ne kao |konaËnu osvetu? Poslednje poniûenje?
{116847}{116952}-Rekao sam vam da nisam nameravao|da ubijem Luizu. Gasa i Dûetsona da,
{116964}{117086}ali Luizu... To se samo desilo.|-Ali je ona bila analno napadnuta?
{117125}{117173}-Moûda je momak u kolima|voleo to, ne znam. 
{117198}{117269}-Nalaz patologa potvruje da se|analni napad dogodio nakon smrti.
{117286}{117352}-äta da vam kaûem? To nisam bio ja.|-Moûda vaö sauËesnik?
{117364}{117401}-Nisam imao sauËesnika.|To je moje delo.
{117461}{117507}-Kako ste znali da je gospodin|Dûetson bio u restoranu?
{117544}{117643}-Nisam znao. -Samo ste odluËili da|pretraûite mesto kako bi bili sigurni
{117656}{117698}da nije postojao svedok koga niste|videli'? -Ne znam, moûda sam neöto Ëuo.
{117711}{117742}-Da li ste Ëuli neöto? -Pogledao|sam okolo i video sam ga.
{117762}{117801}-Jeste li sigurni da ga nije naöao|vaö sauËesnik? -Rekao sam vam 
{117819}{117880}da nisam imao sauËesnika. |-Ovo je isti nesauËesnik koji nije
{117894}{117991}sodomirao gicu Rimarti?|-Prigovor. Gdin Erdaj je veÊ
{118013}{118063}izjavio da nije imao sauËesnika.|-Prihvata se.
{118087}{118153}-Koliko je proölo nakon öto vam je|dijagnoziran rak dok niste pisali sudiji Saliven?
{118203}{118274}-Bilo je otprilike u isto vreme.|-ZnaËi to nije bila sluËajnost?
{118302}{118446}-Mislim da ne. -U pismu gdina |Gandalfa piöe da je to bila sluËajnost.
{118469}{118534}-Ne znam niöta o njegovom pismu.|-Pisao sam sudiji i nisam dobio odgovor.
{118548}{118624}-I to je bio kraj vaöe borbe? |Da piöete o velikom nedelu.
{118645}{118749}-Potrudio sam se. -Uradili ste ono öto|su traûili od vas oni koji su vaö ötitili 4 godine?
{118766}{118796}-Niko nije traûio da niöta uradim?
{118829}{118914}-Jedno pismo? Samo je to trebalo|da sredite svoju savest?
{118933}{118964}-Sada smo ovde, zar ne?
{119014}{119102}-Da li ste mogli da viate vaöu ûenu |i porodicu svakodnevno tokom ovog postupka?
{119120}{119212}-Imate li neöto sa tim, savetniËe?|-Svedok Êe se uzdrûati od pitanja.
{119227}{119250}»ak i ona retoriËka.
{119384}{119482}-éelela bih da diskreditujem ovog|svedoka ako se dokaûe kao neophodno.
{119505}{119604}Nepotrebne informacije su mu |omoguÊile privilegije koje 
{119616}{119686}ne bi dobio u drugom slluËaju.|Nadam se da Êe sud odbaciti
{119703}{119786}ovo na osnovu da svedoËenje|ne moûe da se koristi.
{120144}{120183}-Ne, ne mislim da smo joö|tu stigli.
{120258}{120370}-Slaûem se da svedok ima neke|probleme ali je svojevoljno priznao ubistva
{120399}{120499}za koje je drugi Ëovek osuen|na smrt. Bio bi nedostatak naöe
{120514}{120605}odgovornosti ako ne bismo nastavili|sa ovim joö malo. Ovde treba da 
{120622}{120672}se postaramo da se izvröava pravda,|zar ne, gice Vin?
{120686}{120740}-Da, visosti i protivimo se |izvrtanju prilika.
{120768}{120866}-Pa onda bismo vi, ja i gdin Rejven |trebalo da se slaûemo sasvim dobro
{120882}{121007}poöto smo svi na istoj strani.|-Nemam daljih pitanja, za sada.
{121040}{121091}-Ja imam jedno.|-Izvolite.
{121182}{121297}-Da li je Romeo Gandalf, osuenik na|smrtnu kaznu, imao bilo öta sa
{121312}{121386}ubistvima za koje je osuen?|-Niöta.
{121431}{121452}Ja sam mu smestio.
{121500}{121575}-To je nesreÊa jer mu je zakazano|da umre za tri nedelje. -Prigovor.
{121598}{121655}-Usvaja se.|-Nemam daljih pitanja.
{121679}{121736}-Ovaj sud Êe se ponovo sastati|za 48 sati.
{122877}{122980}-Boston. Mrzim saobraÊaj, mrzim|politiËare, volim "Redsocks"-e kada pobeuju.
{122999}{123053}-Zaboravi na "Redsocks"-e, mi smo |ti kojima je potrebna pobeda.
{123068}{123139}-Moûeö li da potvrdiö adresu|Kolinsa Farvela? -Da i lokalne
{123154}{123214}vlasti su me uverile da mogu da|izdaju nalog dva sata nakon öto
{123227}{123273}stignemo tamo. Nadam se da|Êemo ga naÊi.
{123289}{123340}-Zaöto misliö da Êe hteti da Êe hteti|da razgovara sa mnom?
{123353}{123441}-Ako poverujemo Ernalovu priËu,|to znaËi da je Farvel sauËesnik.
{123458}{123505}-Ili je on zvao Ernala i rekao mu|da je Veverica zakljuËan ili je
{123522}{123611}Ernal rekao njemu. Ako se Farvel|drûi priËe, moûemo obojicu da ih 
{123625}{123714}uhvatimo. -äta ako tvrdi drugaËije?|-Reci mu da je vreme za veliku porotu.
{123736}{123842}-Po Bostonu Kolins je naöao Isusa.|Razgovara sa njim u javnosti nakon
{123855}{123942}ponovo naenog mir. Nakon öto|se otarasio droge, ovaj ga je posetio.
{123963}{124019}-Nema problema. Lepa suknja.
{124616}{124744}-Gdine Rejven, öta mogu da uradim|za vas? -Hteo bih da kupim neki parfem.
{124782}{124863}-äta ste imali na umu? -Moûda biste|vi mogli neöto da predloûite?
{124880}{124922}-Da li je osoba starija?
{124951}{124972}Mlada?
{125035}{125075}-Tinejdûer? -äta vi koristite?
{125184}{125211}-ZvuËi kao dobar parfem.
{125367}{125437}Video sam vas juËe u sudu.|To je bilo izuzetno hrabro.
{125477}{125512}-Hrabro?
{125629}{125694}Da li biste ûeleli toaletnu vodu ili|parfem?
{125716}{125748}-Dobijate viöe sa toaletnom vodom?
{125772}{125845}-Voda je besplatni deo.|-éeleo sam da priËam sa vama.
{125883}{125961}KupiÊu toaletnu vodu. -Ne morate|niöta da kupite da biste priËali sa mnom.
{125982}{126115}-Ne, znam to, ali Êu je ipak kupiti.|Znate, nikada nisam kupio to ranije?
{126145}{126178}Pretpostavljam, da vam to neöto|govori o meni.
{126203}{127703}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
