{1}{1}23.976
{55}{111}Mnogo hvale za tako malog konja.
{135}{195}Iako je moûda mali, vatren je.
{201}{263}äta je to? -To je äekspir momci.
{276}{299}To je äekspir.
{324}{474}-== [ www.OpenSubtitles.org ] ==-
{709}{741}Jebote!
{861}{906}Vidi to Kolacicu, vidi to.
{1269}{1292}To je za tebe momak.
{1326}{1343}To je za tebe.
{2168}{2237}To je öest pobeda za redom za |ovog malog od nigde.
{2242}{2343}Jedna do rekorda. On je moûda |najveca senzacija od Nade i Krosbija.
{2352}{2442}Svi stoje cim se on pojavi.
{2449}{2515}Ako nemoûete da priuötite 25 centi|okolno drvece ce vam obezbediti pogled.
{2522}{2586}U cemu je tajna ove price.
{2590}{2711}Verujem da daju Kolacicu dve pinte |hladnog piva pre svake trke.
{2733}{2809}Boûe.
{3059}{3078}Dobro jutro.
{3172}{3191}äta je ovo?
{3216}{3264}Pivo. Od oboûavalaca.
{3286}{3322}Prilicno je dobro takode. Ima joö unutra.
{3425}{3450}Gde je konj?
{3465}{3486}Potpisuje autograme.
{3531}{3545}äta?
{3619}{3671}Izvoli. Pusti da se osuöi pre |nego öto pokuöaö da prodaö.
{3699}{3743}Carls. Misliö da moûe oboriti rekord?
{3757}{3780}Da ga pitamo.
{3785}{3834}Kolacicu, misliö da ceö dobiti joö jednu?
{3844}{3858}Oboriceö rekord?
{3904}{3951}äta misliö da je prokrenulo ovog konja?
{3976}{4011}Mislim da smo mu samo dali öansu.
{4036}{4083}Ponekad je sve öto nekome treba,| druga öansa.
{4110}{4189}Mislim da mnogo ljudi tamo |zna o cemu pricam.
{4263}{4295}Evo momci.
{4310}{4344}Uzmite koju potkovicu.
{4372}{4429}Ove su posebne.| Nikad im ne nestaje srece.
{4454}{4483}Izvoli.
{4627}{4697}Seme, gde su dodavola moje potkovice?
{4784}{4834}Ne mogu da radim ovako.
{4852}{4858}On nije ûivotinja za parade,| on je trkacki konj.
{4926}{4997}Sluöaj Tome, malo odnosa sa javnoöcu...
{5001}{5100}Ne mogu da napravim odlicnog konja,|ako nemam vremena da radim sa njim.
{5109}{5150}Kako misliö, on jeste odlican konj.
{5154}{5185}To neznamo joö.
{5190}{5218}Dobio je öest trka za redom.
{5225}{5250}Protiv koga?
{5348}{5416}Ovo, ovo je odlican konj.
{5626}{5672}Prvo ih je zgnjecio u derbiju Kentakija.
{5691}{5735}Onda ih je zdrobio u Feniksu.
{5781}{5874}Zatim je uniötio sve pridoölice u |Belmontu da bi prigrabio trostruku krunu.
{5898}{5960}Sa skoro 18 ruku,| veliki je koliko je i brz,
{5961}{5981}18 ruku?
{5995}{6016}Skoro je duplo veci.
{6039}{6069}Veliki je.
{6119}{6208}Roden u savröenom odgoju,| predstavlja savröenu formu,|postavlja savröen rekord.
{6215}{6284}Milioner gos. Ridle je moûda |konacno kreirao savröenog konja.
{6298}{6393}Do sledeceg susreta, ovo je Horace| Holdsteader za Metrotell vesti.
{6438}{6515}Kako to misli savröen?
{6538}{6569}äta dodavola savröen znaci?
{6587}{6598}äta?
{6619}{6693}Pokaûi mi neöto savröeno,| ja cu ti pokazati neöto öto nije.
{6824}{6920}Sluöajte, on je ocigledno najbolji| konj na istoku, naö je najbolji na zapadu.
{6931}{7081}Mislim da publika zasluûuje da vidi koji|konj je bolji. -Moûda to ne vidite narode|ali mi je rukavica pala na sto.
{7093}{7132}Govorimo o trci gos. Hauarde?
{7137}{7241}äta god gos. Ridle ûeli. Uporeda trka|trka sa ulozima, trka u dûakovima.
{7252}{7317}Samo zato öto smo manji,| ne znaci da smo uplaöeni.
{7327}{7409}Tamo u srcu Amerike, svaki maliöa zna|tacno öta ste mislili.
{7418}{7511}Cujete gos. Ridle imate zakazano kod |sudbine, sastanak sa...
{7571}{7692}...sudbinom? -Da sudbinom i njeno ime je|Morski Kolacic.
{7797}{7858}Drago mi je da konacno |imaju trke u Kaliforniji.
{7884}{7920}Koriste li zapadnjacka sedla tamo?
{7972}{8095}Porediti ove konje je smeöno. |Admiral je pravi trkacki konj.
{8105}{8158}Dobio je svaku bitnu trku u Americi.
{8171}{8257}Ovo malo ûdrebe, trci na stazama za krave.
{8307}{8461}Kada bi se odazvali na svaki izazov,| od onih koji ûele da steknu ime....|Ne bi bilo fer prema nama.
{8487}{8515}Ne bi bilo fer ni prema njima, takode.
{8549}{8598}Ne biste stavili Dûeka Dempseja u |ring sa nekim iz srednjekategorije.
{8715}{8730}Srednja kategorija?
{8770}{8831}Ubicu ga. Razbicu mu nos.
{8835}{8853}Kukavica. -Znam.
{8864}{8926}Srednja kategorija? |-Moracemo malo da ga isperemo.
{8944}{8958}Kako?
{8980}{9028}Ovo je joö uvek Amerike, jel' tako?
{9083}{9101}Keö.
{9140}{9227}100.000 dolara.|- Najveci dobitak u istoriji Amerike.
{9228}{9245}Iskreno se nadam.|
{9248}{9360}Dobiceö sva vrhunska grla.| Postaviceö ovo mesto na kartu.
{9388}{9518}Moûda imaju tu plavu krv,ali je| naö novac isto tako dobar kao i njihov.
{9531}{9576}Carli. -Dag. Ovo je naö momenat.
{9584}{9644}Oni su zaglavljeni u proölosti. |Ovo, ovo je buducnost.
{9659}{9680}Lud si.
{9715}{9740}Dodi ovamo.
{9764}{9780}Dodi ovamo! -Zaöto?
{9808}{9953}Zar ne ûeliö da ih vidiö kako izlaze iz|vagona i post na tvojoj stazi.
{9999}{10048}To je samo po sebi pobeda.
{10062}{10080}Dag.
{10103}{10172}To je cilj. Baö tamo.
{10223}{10262}Prodajeö kola ovako?
{10285}{10306}Na stotine.
{10323}{10385}Smirite konje. Smirite konje. |Baö kada ste mislili da ste sve videli.
{10392}{10504}Dag Strubs je opljackao teglu sa keksom,|razbio kasicu i prodao porodicno srebro.
{10512}{10557}100.000 dolara za jednu trku.
{10566}{10621}Poûelim da hodam na sve cetiri i |nabacim sedlo na leda.
{10632}{10719}Hoce li Kolacic biti favorit, malo |verovatno narode.Sprema nam se invazija.
{10755}{10824}Govorimo o dobitnicima derbija,Belmonta...
{10857}{10906}Sacekajte, sacekajte to je jedan konj.
{10913}{11030}Ali za 100.000$ kako da Admiral ne usidri| svoj brod u ovoj prijateljskoj luci.
{11040}{11112}Ovo je Tic-Tac McLaclin uûivo.
{11173}{11204}Trka od 100.000$...
{11292}{11313}Ne, hvala.
{11408}{11414}Sranje.
{11426}{11444}Carls.
{11459}{11474}Sranje.
{11496}{11519}Da znam öta misliö.
{11533}{11547}Dodavola sa njima.
{11559}{11616}Trkacemo se u svakom slucaju.|I dalje ce tu biti najbolji konji sveta.
{11630}{11684}Ako pobedimo, morace da se suoce sa nama.
{11703}{11734}Morace da se suoci sa nama.
{11996}{12151}Specijalni agent je cista brzina, poveöce| ali nece izdrûati.Ne daj da te povuce.
{12157}{12174}Necu.
{12177}{12226}Indijanska metla moûe da bude tu takode.
{12238}{12306}Znacemo da ga sputavaju |ako upotrebe prsten.
{12360}{12497}Moraö da se paziö Rosemonta.|Zavröava kao teretnjak.
{12516}{12559}I borice se sa tobom na kraju.
{12576}{12667}Moraö da izgradiö prednost |pre nego on krene.
{12711}{12861}Joö uvek je vlaûno od juce, zato pokuöaj|da se drûiö dalje od öine.
{12884}{12927}Mislim jedno 3 öirine?
{12932}{12956}Da. To je dobro.
{13026}{13236}Sem toga, samo pokuöaj da osetiö.|Reci ce ti kada je spreman.
{15592}{15619}Hajde Red!
{16069}{16113}Hajde! Hajde!
{16340}{16375}Pazi ga decko. Pazi ga.
{16783}{16820}Nije moja krivica. Ne ovaj put.
{16826}{16869}Rekao sam ti da paziö na Rosemonta.
{16873}{16891}Mislio sam da ga imam.
{16899}{16940}Prestao si da jaöeö. |-Nisam mogao da ga vidim.
{16947}{17011}O cemu pricaö? Leteo ti je uz rep.
{17015}{17054}Ne mogu... -äta?
{17072}{17102}Da vidim tamo!
{17293}{17312}Lagao nas je.
{17336}{17371}äta? -Lagao nas je.
{17396}{17429}Hoceö dûokeja koji nas laûe?
{17445}{17463}Kako to misliö?
{17496}{17514}Ne moûe da vidi.
{17539}{17592}Slep je na jedno oko.
{18156}{18182}U redu je Tome.
{18247}{18274}U redu je?
{18287}{18311}Da. U redu je.
{18411}{18503}Ne bacaö ceo ûivot,| zato öto je malo slupan.
{18609}{18619}Laku noc.
{18796}{18889}Izgleda da je taj njihov konj ipak samo|izvikan, nakon svega.
{18963}{19041}Bar viöe ne moramo da se bavimo tom|David i golijat glupoöcu viöe.
{19121}{19146}Ok, momci, pustite me da prodem.
{19461}{19483}Dodavola sa tim.
{19577}{19604}Samo par objava.
{19623}{19746}Prvo. Red Polard ce ostati dûokej |Kolacica, sada i zauvek.
{19773}{19862}Drugo. Ako se plaöe da dodu i trkaju |se sa nama idemo mi da nademo njih.
{19875}{20057}Prijavicemo se na svaku trku u kojoj je|i Ratni Admiral i ako se ispiöe, |prijavicemo se na sledecu na kojoj je.
{20072}{20138}I ne vracamo se dok se ne suocimo| sa njim. Bilo pobeda, poraz |ili nereöeno.
{20196}{20327}Znate, radije bi jednog ovakvog konja,|nego joö 100 Ratnih Admirala.
{20331}{20351}Hvala momci.
{20975}{21072}Ja... stvarno ne znam öta da kaûem.|Cenimo ovo.
{21089}{21198}Siguran sam da i Kolacic ovo ceni, samo|je malo stidljiv da govori u javnosti.
{21233}{21284}Inace bi vam se sam zahvalio.
{21312}{21477}Verujem da ste svi ovde danas, jer ovo |je konj koji nece da odustane.
{21514}{21566}Cak i kada ga ûivot udari po nosu.
{21656}{21744}Ali dodavola, svako izgubi par.
{21805}{21888}Ili se spakujete i odete kuci, ili |nastavljate da se borite. Je li tako?!
{21968}{21985}Tako je.
{22011}{22091}Sada... |Da li vi ûelite da vidite tu trku?
{22096}{22122}DA!!!
{22147}{22178}éelite? -DA!!!
{22200}{22249}Hocete da vidite ovog momka| kako jaöe tog konja?
{22313}{22333}Morski Kolacic.
{22445}{22507}Ekstra! Kolacic na ratnoj stazi.|Hoce li biti trke?
{22524}{22551}Sve piöe ovde.
{22621}{22686}Ne znam zaöto su toliko zabrinuti.|Pogledajte nas.
{22702}{22734}Konj nam je premali.
{22747}{22786}Dûokej nam je prevelik.
{22803}{22830}Trener nam je prestar.
{22895}{22940}A ja sam previöe glup da |primetim razliku.
{22969}{23029}Mislite da bi ûeleli da se trkaju sa|nama umesto da beûe.
{23285}{23436}Dame i gospodo nalazim se u mnoötvu| ljudi, gladnih lica koja zahtevaju |mec ûivota.
{23451}{23578}Doöli su veceras po zimi, |vetru kasne oktobarske veceri.
{23588}{23695}Dajte da se probijem do jednog od njih |da biste i vi culi.Izvinite. Izvinite.
{23739}{23892}Gospodo, öta vas dovodi veceras sa troje|male dece da vidite ovog malog konja?
{23899}{23940}Zato öto ûelimo da vidimo tu trku.
{24034}{24181}Rekao bih, zar ne mislite da gos. Ridle|duguje ovoj zemlji...  -TRKU!
{24430}{24461}Dobro, ali pod mojim uslovima.
{24503}{24527}Koje god uslove ûelite.
{24531}{24583}3.16 ne prihvatam niöta drugo.
{24598}{24611}U redu.
{24630}{24727}éelim hodajuci start sa zvonom.|Bez naprava.
{24757}{24788}Mislite na startnu kapiju.
{24850}{24865}Dobro.
{24888}{24980}I trkamo se ovde na domacoj stazi.|O tome nema pregovora.
{25033}{25066}Deluje kao dovoljno lepo mesto.
{25108}{25160}Mislim da cete naci da je| udobno gos. Hauard.
{25404}{25435}Isuse!
{25467}{25496}éelim da budem konj.
{25521}{25564}Skoro da si dovoljno veliki.
{25584}{25619}To je veoma smeöno.
{25656}{25697}Cak ni ne miriöe kao ötala.
{25723}{25786}Verovatno je sreduju svakog jutra.
{25804}{25829}I dalje je sranje.
{25941}{25966}Pa jeste.
{26241}{26280}Privatna ötala Ratnog Admirala.
{26302}{26342}Nas su smestili u odaje za sluge.
{26366}{26381}Je li to on?
{26415}{26497}Ne. Previöe je mali.
{26584}{26612}To je on.
{26696}{26721}Boûe.
{26922}{26982}Moûda je on tip konja koji| samo dobro izgleda u ergeli.
{27249}{27293}Moramo da preuzmemo vodstvo.
{27311}{27344}Kolacic nikad ne preuzima vodstvo.
{27356}{27446}Znam, ali moramo da ga naucimo da se |probije prvi.
{27466}{27559}Ako se to cudoviöte oslobodi,| nikad ga necemo stici.
{27616}{27638}äta? Da ga preobucimo?
{27747}{27770}Imamo dve nedelje.
{27995}{28136}Izvinite. éeleli bi da kupimo vaöe zvono.
{28217}{28291}Nije mi rekao da dolazite.|-Verovatno je to prevideo.
{28302}{28353}Da upalim svetla ili neöto? -Ne.
{28390}{28485}Dobro. To je predatorski odgovor.
{28503}{28580}Ako ga poceöem po boku, ohrabrice se.
{28600}{28659}Samo ûelimo da ga naucimo| da to radi sa zvonom.
{28671}{28695}Koliko da ga vodim?
{28708}{28787}100 stopa, samo da nauci da krene prvi.
{28807}{28820}Ok. Razumeo sam.
{28895}{28921}Spremna si? -Spremna.
{29513}{29537}U redu. Idemo.
{29999}{30027}Hajde Tome!
{30039}{30071}Kada ceö da treniraö tog konja?
{30116}{30156}Kada se probudi, valjda?
{30326}{30346}Celu stazu?
{30373}{30456}éelim da to obavi jednom| bez icega ispred njega.
{30474}{30505}Da, ali ja ne vidim tamo.
{30525}{30548}I to je u redu.
{30559}{30571}On moûe.
{30575}{30670}Daj Tome. Tome molim te.|Zaöto to uvek radiö?
{30695}{30700}Sranje.
{30772}{30783}Sjajno.
{30888}{30922}Isuse.
{31138}{31159}Boûe.
{31611}{31664}Hej kako si Tikvo.
{31798}{31815}Hej Rede.
{31909}{31935}Boûe.
{32016}{32064}Trebao sam da te koristim kao dûokeja|umesto sluge.
{32072}{32143}Ne, ne. Bilo je sjajno.
{32189}{32239}Sluöaj, u maloj sam nevolji.
{32258}{32334}Imam konja u Anexu i pokuöavam |da prodam deo njega.
{32345}{32363}Teöka vremena i tako.
{32379}{32448}Pitao sam se da li bi ti...
{32482}{32538}Tvoji su ... Red Polard.
{32569}{32594}Projahacu ga, za tebe.
{32728}{32786}Povedi ga za 5 furlonga i vrati.
{32791}{32827}Moûe li on to? -Naravno.
{32975}{32989}Probaj sada.
{33247}{33269}Ok, probaj ponovo.
{33448}{33461}Lagano. Lagano.
{34823}{34890}Najveci deo ötete je na nozi.
{34908}{34941}Koliko je loöe?
{34955}{35002}Smrskana je.
{35018}{35091}11 ili 12 preloma.Moracemo da operiöemo.
{35147}{35168}Drûite mu palceve.
{36192}{36209}Zavröili smo.
{36253}{36310}äepace, ali izgleda da ce hodati ponovo.
{36363}{36401}Moci ce da jaöe?
{36437}{36459}Ne nece moci da jaöe.
{36474}{36522}Sigurni ste? -Nece jahati.
{36535}{36549}Hodace.
{36581}{36596}Cuvajte se.
{36630}{36643}Hvala.
{36798}{36836}Trebao si da vidiö onog drugog.
{36871}{36896}Biceö dobro.
{36905}{36964}Za par meseci biceö kao nov.
{37007}{37067}Ja sam onaj koji izmiölja price,| secaö se?
{37130}{37221}Pa, da. Moûda malo duûe od toga.
{37354}{37439}Sluöaj, mislim da cemo |morati da se povucemo.
{37482}{37502}Ne.
{37519}{37623}Ne, ne odustajte. -Sinko, on je| odlican konj ali ne moûe sam.
{37631}{37652}Ne odustajte.
{37848}{37870}Zovite ga.
{37920}{38025}Sinko, niko... -U redu je. Zovite.
{38101}{38141}Ne, ne odustajemo.
{38155}{38225}Red Polard ûeli da Kolacic dobije ovu |trku viöe nego bilo öta na svetu.
{38242}{38266}Nije nam dao da odustanemo.
{38310}{38342}Hvala, cenim to.
{38410}{38522}Ledeni dolazi. To je kao da je |Bejb Ruth ustao sa klupe.
{38529}{38581}Nervi od celika, ledena voda u venama.
{38591}{38629}Dûordû Wolf je... -Nebitan.
{38644}{38718}Mogu da dovedu jahace apokalipse öto |se mene tice.
{38732}{38752}Nece biti razlike.
{38764}{38830}Ratni Admiral je superiorniji,|sa superiornijim odgojem.
{38849}{38885}Nije bitno ko je putnik.
{38957}{39002}Ima jak karakter Dûordûi.
{39006}{39042}Ide kao avion.
{39063}{39153}Udalji ga od öine malo pre skretanja.
{39164}{39190}Kao ti u Zlatnom kupu.
{39196}{39211}Tacno.
{39231}{39284}Treba da se zagreje, zato kreni polako.
{39294}{39360}Kada ga pitaö, ne koristi bic.
{39368}{39414}Samo mu pokaûi da je tu.
{39429}{39451}Znace da je vreme.
{39464}{39490}Dobro.
{39501}{39584}I nikad po levoj strani.
{39619}{39667}Udarali su ga po levoj| kada je bio ûdrebe.
{39696}{39721}Voleo bi da ga ti jaöeö Dûoni.
{39739}{39818}Hajde. Bicu tamo sa tobom.
{40083}{40223}Sjajno. Sada, pokaûi mu ötap na cetvrt,|i dace ti celu novu brzinu.
{40397}{40482}Nateraj ga na levo, malo ranije.
{40494}{40516}I dace ti joö viöe.
{40673}{40691}Sada zatvori vrata.
{41130}{41202}Znaö kako Smit hoce da se boriö za prvo|kod prvog skretanja?
{41222}{41239}Da.
{41256}{41282}Radimo na tom zvonu.
{41304}{41333}Malo sam nervozan zbog toga.
{41338}{41354}Ne. Dobro je.
{41376}{41425}Moraö da popustiö na zadnjoj.
{41451}{41465}Da popustim?
{41487}{41511}Vrati mu vodstvo.
{41557}{41798}Neka se bori Dûordûi. Ako ga suociö sa| tim konjem,i on ga pogleda u oko,| nema öanse da izgubi tu trku.
{41821}{41874}Samo ga drûi do zadnjeg skretanja.
{41893}{41939}I dopusti mu da dobro pogleda Admirala.
{41965}{41982}A onda ga pusti.
{42036}{42163}Nije u njegovim nogama Dûordi,| nego ovde.
{42314}{42408}Do 10 ujutru, najbliûe mesto za |parkiranje je bilo 15 blokova daleko.
{42430}{42500}Kolicina osveûenja je opadala.
{42513}{42616}17.000 galona limunade. 60.000 Hot-Dog-a
{42713}{42881}NBC je prenosio trku. Firme su skratile|radni dan da bi zaposleni stigli na trku.
{42894}{42987}Delimicno zahvaljujuci objavi |gos. Hauarda od dan ranije.
{43009}{43146}Znam da je ovo fensi staza, ali trebali|bi da otvore polje da bi normalan|svet mogao da vidi trku.
{43179}{43237}Ne bi trebalo da budete bogati da bi|uûivali u necemu ovakvom.
{43267}{43343}Kolacic je uöao u trku sa 2:1.
{43355}{43420}Ali to nikad ne biste pretpostavili po|rastucoj buci sa polja.
{43473}{43563}Do kraja je skoro 40.miliona |Amerikanaca je culo poziv.
{43608}{43764}Joö uvek je vlaûno na öini, zato ga |drûi dalje od nje.
{43779}{43858}Jedno 5 stopa od ograde.
{43873}{43905}Proöetao sam stazom jutros.
{43943}{43958}Dobro.
{44047}{44102}Trebalo bi da krene kao öto smo veûbali.
{44154}{44204}Ali, ima joö jedna stvar.
{44243}{44285}äta? Da ga pustim da me |stigne na zadnjoj?
{44350}{44386}Niste jedini koji poznaje ovog konja.
{44512}{44535}Siguran put Dûordû.
{44547}{44563}I kratak.
{44590}{44614}Idemo Seme.
{44745}{44778}Srecno Dûordû. -Hvala Nik.
{44812}{44819}Carli.
{44879}{44989}Dûokeji su se pozdravili.|Kao bokseri sa rukavicama.
{45012}{45058}Hajde Dûordû, nije vreme za price.
{45070}{45153}Oba konja su na stazi,| i moûete cuti urlik publike.
{48551}{48600}Sada ga uspori, uspori.
{48692}{48730}Ajde Dûordû. Ajde.
{48844}{48878}Hajde Dûordû, ne zajebavaj se.
{48949}{48980}Nadam se da si u pravu Red.
{48992}{49008}Idemo.
{49219}{49252}Dodavola Dûoni.
{49900}{49924}Polako ortak.
{49965}{49986}Tako je.
{50695}{50754}Uradi to. Sada, hajde Dûordû.
{50763}{50780}Pusti ga.
{50813}{50832}Sada, Dûordû.
{50901}{50924}Do videnja Carli.
{51014}{51030}Pusti ga.
{51386}{51404}Hajde Kolacicu!
{51786}{51797}To!
{53377}{53409}Cestitam.
{53495}{53518}Ledeni uspeo si.
{53526}{53547}Kako se osecaö?
{53559}{53636}Samo bih voleo da je moj dobar prijatelj|Red Polard ovde umesto mene.
{53637}{53657}Bice.
{53781}{53855}Ovim zavröavamo radio prenos trke veka.
{55896}{55953}Svi pozdravite osvajaca, da narode vratio se.
{55964}{56066}Nema viöe takvih trka za ovog malog| ponija, jer mu iskreno nema ravnog.
{56077}{56136}Ako ce on da se trka ûalim ostale konje.
{58932}{58956}Kada ce znati?
{58987}{59023}Ne znam, moûda za sat.
{59038}{59082}Nisam sigurna. Carls je sa veterinarom.
{59140}{59284}Da li boli kada je savije, jer ako...|-Ne znamo niöta joö. Nazvacu te cim|saznam öta je.
{59664}{59700}Gos. Hauard.
{59916}{59974}Pukao mu je ligament.
{59984}{60064}Stavio sam mu dasku da ga |imobilizujem ali....
{60074}{60126}Trenutno je totalno hrom.
{60165}{60191}Nece se ponovo trkati.
{60390}{60483}Znam da je teöko. Ali uspavacu ga ako |hocete da to uradim.
{61392}{61445}U redu je druûe, doci cu ja do tebe.
{62444}{62578}Vidiö. Prvo malo fleksibilnosti.
{62592}{62629}Onda moûeö da se osloniö na nju.
{62644}{62732}Cim pocneö da se oslanjaö na nju,|cela noga ojacava.
{62758}{62810}Znam, znam. I ja ûurim ortak.
{62831}{62875}Ali znaö öta je Hadrijan rekao za Rim.
{62904}{62947}Ciglu po ciglu moji gradani.
{62966}{62986}Ciglu po ciglu.
{63112}{63186}Oni su arapski, pa ne moraju da piju.
{63217}{63295}Ti konji, znaö po 5 -6 dana.
{63320}{63345}Bez kapi vode.
{63377}{63398}Kao kamile.
{63411}{63488}Ne kaûem da bi ti to trebao.
{63522}{63551}Samo kaûem da to oni rade.
{63668}{63755}Da se malo odmorimo.
{64689}{64712}Ne znam Red.
{64728}{64761}äetacemo u krug.
{64805}{64829}Misliö da ce te noga drûati?
{64862}{64900}Konj teûi 1200 funti Seme.
{64900}{64934}Ja sam samo mali teret.
{64939}{64970}Ne, mislim na tvoju nogu.
{65176}{65287}Morski Kolacic juriöa stazom, prestiûuci| konkurenciju jednog po jednog.
{65315}{65392}Treci je, drugi sada je prvi.
{65418}{65474}I Morski Kolacic je pred ciljem.
{65493}{65583}Da pobedi sa Red Polardom u sedlu, da.
{66074}{66084}äta je?
{66535}{66562}Polako drugar.
{66786}{66847}Ortak osecaö se bolje, zar ne?
{67014}{67029}U redu je Seme.
{67039}{67062}Samo cemo da se öetemo malo.
{67081}{67104}Ne samnom Red.
{67450}{67464}Dobro je.
{67673}{67683}Dobro izgleda.
{67695}{67722}Sjajno Red.
{68762}{68785}Je li uopöte moguce?
{68794}{68920}Naravno. Vecina im ni ne pruûi öansu.|Vecina ih samo...
{68938}{69040}Najbolji nacin je da ga odvedemo tamo|i pustimo da galopira.
{69062}{69114}To je jedini nacin na koji| cemo stvarno znati.
{69123}{69147}Moûe li on to da podnese?
{69160}{69210}Naravno. Mislim tako.
{69761}{69813}Bio je odlican, niöta nisam osetio.
{69821}{69892}Dacemo mu pun trening u petak ujutru.
{69919}{69970}Moûda 6 furlonga, da vidimo öta imamo.
{69981}{70017}Vaûi. Bicu ovde.
{70039}{70054}Hvala Dûordû.
{70151}{70173}Doöao je sam.
{70218}{70237}Moûe li biti spreman?
{70274}{70291}Za öta?
{70309}{70337}Hajde. Znaö za öta.
{70548}{70575}Dobro jutro.
{70602}{70649}Fino ûdrebe.
{70658}{70672}Ko je on?
{70680}{70718}Dvogodiönjak, nije joö spreman.
{70758}{70830}Mislio sam da moûda spremate konja za |"Stohiljadarku" -Ne.
{70844}{70873}Samo dvogodiönjak.
{71034}{71051}Ovde si dugo?
{71061}{71085}Ne. Tek sam stigao.
{71102}{71128}Zavröavam citanje.
{71170}{71197}Siguran sam da cu te videti uskoro.
{71202}{71219}Vaûi.
{71393}{71622}Ovo nije kolac, ovo su tri kolaca sa |treönjom na vrhu i malo oraha, jer me|ovaj konj dovodi do ludila.
{71651}{71758}Pogodite ko radi 6 furlonga u petak.|Ko puca na dobitak.
{71765}{71877}Pogodili ste, covece da li biste ikad?
{72261}{72330}1.12 1.13 neöto tako.
{72362}{72402}Ako pocne da öepa, uspori.
{72419}{72449}Pokuöaj da vidiö kako se oseca...
{72806}{72820}U redu je momak.
{72837}{72851}U redu je momak.
{73183}{73264}Najgora ispala od svih.
{73340}{73348}Red.
{73402}{73426}Daj da popricamo.
{73432}{73487}Pricaj! Rede ne moûe...|Rede ne moûeö to da uradiö.
{73495}{73537}Moûeö da se obogaljiö do kraja ûivota.
{73541}{73578}Bio sam obogaljen za do kraja ûivota.
{73593}{73613}Ozdravio sam.
{73633}{73652}On mi je pomogao.
{73667}{73698}Vi ste mi pomogli.
{73797}{73827}Isuse. -Red.
{73926}{73973}I to je moj konj koliko je i vaö.
{74247}{74269}Dodavola.
{74326}{74348}Na njemu je da odluci, Rede.
{74349}{74426}Ali ako on kaûe... |-On je doktor, na njemu je.
{74534}{74578}Ti si napravio ovo. -Aha.
{74601}{74787}Obmota se oko cizme, zategne do kolena|i skoro da niöta ne osecam.
{74979}{75073}Sluöajte moûe da se raspadne u svakom| momentu zaboravite na trkanje.
{75089}{75141}Vidite to, baö tu. To je jedva zaleceno.
{75156}{75226}Nema nacina da se zna koliko| moûe da izdrûi.
{75271}{75358}Ako se ponovo povredi, moguce je da |nikada viöe nece hodati.
{75410}{75464}Moguce. Rekao je samo da je moguce.
{75481}{75560}Dodavola sve je moguce, To smo vec |dokazali, zar ne?
{75564}{75600}Drugacije je. -Da!
{75611}{75648}Ovo je stvarno drugacije.
{75730}{75762}Nije samo trka.
{75792}{75825}To je Santa Anita.
{75859}{75897}Imao sam tu trku, bio sam tamo.
{75920}{75942}Znam.
{76490}{76646}Cak i sa povezom, jedva ce drûati|ako ga udare ili ispadne iz sedla.
{76662}{76678}éelite da znate öta mislim?
{76695}{76710}Naravno.
{76719}{76770}Bolje mu je slomiti nogu nego srce.
{76878}{76925}Nije samo noga. -Ok. -Nije.
{76938}{76996}Moûe da padne, da ga pregaze.
{77013}{77063}Ako padne sa konja.... -Moûe umreti?
{77370}{77429}Znaö verujem da moûe.
{77525}{77600}Ali bez obzira koliko sam se trudila nikad|nisam uspela da nateram loptu da ostane|u rupi.
{77666}{77697}Uvek se ponovo iskotrlja.
{77909}{77942}Samo ga pusti da jaöe Carls.
{78006}{78029}Pusti ga da to uradi.
{78231}{78337}Mogao sam da podnesem jedan povratak, ali|ovo je smeöno. Ko je sledeci? Lazar?
{78347}{78401}Heroizam. Ludilo. Uzbudenje.
{78408}{78462}Najveca gomila koja je ikad doöla da |vidi trku u Santa Aniti.
{78470}{78594}50.000 na sediötima. 25.000 u polju.|A samo je 12 sati.
{79061}{79075}Nije loöe.
{79154}{79181}Sv. Kristofer.
{79202}{79216}Za srecu.
{79237}{79270}Malo je kasno za to, zar ne?
{79480}{79526}Dobro. Idemo da dobijemo trku.
{80364}{80513}Veötica je brzina, bice na celu, ali |mislim da nece podneti daljinu.
{80525}{80578}Prati ga kao i uvek.
{80608}{80621}Dobro.
{80658}{80783}Svadbeni Zov moûda krene kasno,|i ima petlje zato ga se pazi.
{80795}{80819}Tu greöku necu ponoviti.
{80960}{81013}Opustite se momci, bice dobro.
{82033}{82095}Srecno. -Dobro izgledaö.
{82195}{82212}Opusti se.
{82264}{82282}Da narucim pice, a?
{82314}{82339}Dobra ideja.
{83514}{83536}Zdravo matori.
{83573}{83598}äta ceö ti ovde?
{83616}{83636}Imam joö jedna usta.
{83647}{83698}Samo zato öto ne jaöem njega ne |znaci da cu presedeti trku.
{83735}{83780}Ne brini, nemam öanse.
{83821}{83842}Vidimo se na cilju.
{85767}{85785}Hajde momak.
{85813}{85842}Hajde.
{86546}{86596}Kako si Red? -Dûordûi.
{86619}{86634}Momci dobro ste.
{86750}{86767}Hej, zlatni decko.
{86847}{86863}Evo ga.
{86878}{86904}éelim ti lepu voûnju Dûoni.
{87118}{87154}Idi sa njim Dûoni.
{87435}{87456}Hajde.
{87759}{87795}Ajde Kolacicu.
{88629}{88711}Znate svi misle da smo pronaöli |tog slomljenog konja i popravili ga.
{88761}{88776}Ali nismo.
{88862}{88888}On je popravio nas.
{88953}{88976}Svakoga od nas.
{89041}{89161}Mislim da smo na neki nacin popravili|i jedni druge, takode.
{90000}{90823}divxnaslovi@yahoo.co.uk|www.paranomia.net
{90848}{92348}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/5j6au|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
