{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{1445}{1514}Utiöajte se malo!
{1551}{1591}Barbara!
{1594}{1641}Do avola.
{1872}{1953}äta, do avola, radite?|Pokuöavam da uËim!
{1956}{2025}I mi imamo ispite.|Jesi li Ëula za moderni ples?
{2028}{2108}Ne moûeö da uËiö uz muziku?|-Ne, ne mogu!
{2111}{2205}Utiöajte to ili idem kod Su.|-Pa idi onda. Odjebi.
{2208}{2278}Idem kod Su.|Idem kod Su.
{2672}{2721}Pusti me!|-äta je?
{2823}{2913}Neko je tamo napolju.|Neko je tamo napolju.
{2916}{2975}äta priËaö? Tamo nema nikoga.|-Ima!
{3065}{3132}Smiri se.|-Ne mogu da se smirim.
{3135}{3226}Bolje se pobrini za to, jer|ne mogu da uËim uz disko-muziku.
{3379}{3459}Mala gnjida je|dovela veliku gnjidu.
{3620}{3673}Muzika nije glasna.|-Jeste!
{4740}{4789}Zaboga! Ovaj krik je uûasan!
{4840}{4927}Koju si maËku zadavio da bi|ga dobio? -To je njen glas!
{4930}{4967}Nisi ga sinhronizovao?|-Nisam
{4970}{5004}To je njen glas?|-Jeste?
{5007}{5056}Stvarno?|-Da.
{5071}{5167}Pusti ponovo|da Ëujemo krik.
{5372}{5421}Joö jednom?|-Da.
{5558}{5630}IskljuËi sve efekte|osim krika.
{5854}{5918}Dosta!
{5936}{6008}U pravu si. Njen je.|I uûasan je!
{6022}{6118}Dûek, nisam angaûovao devojku|zbog krika, nego zbog njenih sisa.
{6121}{6198}äto se onda brineö? Ko Êe da|sluöa krik pored takvih sisa?
{6201}{6257}»ekaj malo, Dûek!
{6260}{6330}Koliko godina radimo zajedno?
{6401}{6489}Da vidimo. Upoznali smo|se na snimanju "KrvoproliÊa".
{6492}{6622}Radili smo "KrvoproliÊe 2",|pa "Loö dan na krvavoj plaûi".
{6654}{6806}Pa "Bordel u krvi". I dolazimo|do ovoga, "Poludeli studenti".
{6821}{6970}Usput, nisam ti rekao. Mislim|da nam je ovaj film najbolji.
{6973}{7075}Skoro dve godine. -Boûe!|Pet filmova za dve godine.
{7078}{7214}Znaö öta ne razumem? Zaöto pametan|deËko kao ti, joö snima ovakva sranja.
{7217}{7270}Ti ih snimaö.|Ja sam ton-majstor.
{7273}{7369}Ma nemoj! Ovaj tvoj|vetar zvuËi kao da prdiö!
{7372}{7426}To je snimak iz arhive.|Koristili smo ga milion puta.
{7429}{7508}U tome je stvar!|»uo sam ga milion puta!
{7518}{7583}Nabavi neöto novo.|-Novi vetar. Dogovoreno.
{7597}{7710}I krik treba sinhronizovati.|-Znaö li neku koja dobro vriöti?
{7758}{7827}Imam neke ideje.|-Mogu misliti.
{7830}{7869}Samo se pobrini za krik.
{8390}{8490}PUCANJ NIJE BRISAN
{9015}{9093}To je preterana presuda|politike Bele kuÊe.
{9096}{9258}Ista anketa je pruûila veliku|pordöku guverneru Dûordûu Mekrajanu
{9261}{9386}Kad bi se danas odrûali izbori,|po anketi, guverner Mekrajan bi
{9390}{9499}pobedio sa zavidnih 62% glasova,|prema predsednikovih 23%.
{9502}{9594}Organizator predsedniËke kampanje,|Dûek Maners je izjavio:
{9597}{9684}"Predsednik je morao|doneti neke teöke odluke.
{9687}{9757}Ali kada se sprovede|ta politika
{9760}{9869}i poboljöa ekonomska klima,|öto se toplo nadamo,
{9890}{10008}narod Êe se osvestiti i podrûati|predsednika na ovim izborima.
{10038}{10101}Do tada se moûe|svaöta dogoditi."
{10104}{10226}U kongresu nestrpljivo oËekuju|da Mekrajan potvrdi kandidaturu.
{10229}{10331}Moûda neÊe dugo Ëekati. Guverner|je sada u hotelu Belvju Stratford,
{10334}{10457}gde Êe se uskoro obratiti zvanicama|povodom Dana osloboenja
{10460}{10550}Nagaa se da Êe tom prilikom|objaviti svoju kandidaturu.
{10554}{10623}Dûoan, ima li novosti|iz Belvju Stratforda?
{10626}{10713}Joö nema. Ali Ëim bude|ukljuËiÊemo se uûivo.
{10716}{10844}U Filadelfiji se nestrpljivo|Ëeka proslava Dana osloboenja.
{10847}{10917}Ove godine proslava|Êe biti posebna,
{10920}{11016}jer je proölo 100 godina od|poslednjeg oglaöavanja zvona slobode.
{11019}{11120}Stogodiönjica Êe se, u subotu|proslaviti uliËnom paradom
{11123}{11252}koja Êe se zavröiti spektakularnim|vatrometom na Pens Lendingu.
{11255}{11340}Izgraena je kopija zvona|slobode u prirodnoj veliËini.
{11343}{11447}Sastavljena je od novËiÊa koje|su darovala deca iz cele zemlje.
{11450}{11534}»ujem da Êe ga doneti|posle vatrometa.
{11537}{11582}Tako je.
{11585}{11663}Upravo se javljaju|iz Belvju Stratforda.
{11666}{11754}Pogledajmo naöeg politiËkog|reportera Frenka Donahjua
{11758}{11832}Uûivo iz Belvju Stratford hotela|s proslave Dana osloboenja.
{11835}{11929}Frenk, izgledaö odliËno.|Da li si razgovarao sa guvernerom?
{11932}{12008}Jesam, Dûoan, ali vrlo kratko.|Stigao je pre par minuta.
{12011}{12132}Pitao sam ga kako mu se Ëini,|do sad, proslava jubileja.
{12136}{12185}Rekao je da mu je|Ëast biti ovde.
{12188}{12291}PrisustvovaÊe paradi i oglaöavanju|novog zvona u subotu uveËe.
{12294}{12382}éao mu je öto je|zvono tako dugo Êutalo.
{12413}{12493}Raduje se novom oglaöavanju|slobode po celoj zemlji.
{12496}{12639}Guverner sada pozdravlja prijatelje,|a Ëuli smo i da Êe ovde veËerati.
{12642}{12753}Njegovi ljudi kaûu da Êe nam se|posle veËere obratiti dugim govorm.
{12783}{12866}Ja sam Frenk Donahju|iz Gradske panorame.
{12885}{12967}Hvala Frenk,|ËuÊemo se kasnije...
{14041}{14109}Hajde da proöetamo uz reku.
{14161}{14210}Baö lepo.
{14243}{14336}Pogledaj, neko je na mostu.|-Nije vaûno.
{14339}{14391}Bulji u nas.|-Ma, koga je briga?
{14394}{14433}Mene je briga.|-Betsi.
{14436}{14508}NeÊu viöe da|ostanem ovde.
{14511}{14563}äta to radi?|-Ne znam.
{14566}{14678}äta je on? Neki voajer?|-Nije vaûno. Idemo ovuda.
{16936}{16964}Isuse Hriste!
{17866}{17920}Boûe! Pomozite mi!
{18027}{18086}Izbavite me odavde, molim vas!
{18273}{18334}O, Boûe!
{20207}{20264}Prasak?|-Da, neka vrsta praska.
{20268}{20319}Gde?|-Nisam siguran gde...
{20322}{20364}Bili ste okrenuti prema autu?|-Jesam.
{20367}{20403}Onda ste Ëuli eksploziju gume.
{20406}{20463}Da, Ëuo sam eksploziju gume,|ali je prvo bio prasak.
{20466}{20515}To je bio eho.|-Ne, nije.
{20518}{20596}»ujte, znam öta je eho.|Ja sam tonski snimatelj.
{20599}{20666}Prasak se Ëuo|pre eksplozije gume.
{20669}{20762}äta ste radili tamo?|-Snimao sam zvukove za film.
{20765}{20824}Snimili ste nesreÊu?|-Jesam.
{20876}{20922}äta se desilo nakon toga?
{20925}{20986}Auto je sleteo s|puta u reku i onda sam...
{20989}{21048}äta ste uradili?|-Pokuöavam da vam kaûem.
{21051}{21134}SkoËio sam u reku|i izvukao devojku.
{21153}{21217}Tamo je bila i devojka?|-Da, tamo je bila i devojka.
{21220}{21305}Koja devojka?|-Ona koju sam dovezao. U sobi.
{21308}{21357}Ona je bila u autu?
{21376}{21425}Jeste.|-Jeste li sigurni?
{21454}{21514}Pa, nisam ronio zbog jabuka.|Naravno da sam siguran.
{21517}{21576}Na dubini od 2.5 m je priliËno|mraËno. -äta je sad ovo?
{21579}{21715}Zar se ovako dobija objektivna|izjava svedoka? Zaboravite!
{22150}{22197}Doktore, kako joj je?
{22200}{22326}Ima veliku sreÊu. Blagi öok|i ogrebotine. Nema teûih povreda.
{22329}{22412}Mogu li da je vidim?|-Moûda spava. Pod sedativima je.
{22415}{22482}Samo Êu je pozrdaviti.|-Nemoj predugo.
{22558}{22607}Kako si?
{22657}{22736}Imaö li moju torbu.|-Nemam.
{22739}{22820}Sigurno Êe je policija naÊi.|Nemoj brinuti.
{22823}{22863}Znam.
{22866}{22925}Kuda Êeö?|-Moram da idem.
{22928}{23000}»ekaj malo. Mislim da je|bolje da se vratiö u krevet.
{23003}{23098}Nisu joö zavröili s tobom.|Hajde, popni se.
{23101}{23150}Dobro, samo joö malo.|-Vaûi.
{23175}{23224}Kako se oseÊaö?
{23252}{23376}Doktor kaûe da sam imala|sreÊe. -Da, trebalo je to videti.
{23435}{23502}Hvala öto si me izvukao.|-Taman posla.
{23557}{23628}Nisam video da si toliko|lepa zbog blata na licu.
{23631}{23694}Joj, nisam se naöminkana!
{23708}{23794}Bez brige, nije straöno.|Ovo je bolnica.
{23797}{23875}Ko si ti?|-Ja sam Dûek Teri. Ko si ti?
{23921}{24011}Sali. Drago mi je öto|smo se upoznali, Sali.
{24295}{24344}Odlaziö?
{24359}{24408}Da, moram da idem. Ali...
{24431}{24536}äta kaûeö da odemo na piÊe|kad izaeö? Po moguÊstvu iz Ëaöe.
{24549}{24596}Vaûi.|-OK. »uvaj se.
{24599}{24655}Moûe veËeras?
{24658}{24767}Ne verujem. Ne veËeras. Ali|pitaÊu doktora kad Êe te pustiti.
{24770}{24862}ZadrûaÊe me u bolnici.|-Sali, moraö da ostaneö u krevetu.
{24866}{24926}Ne ûelim da budem u bolnici.
{24929}{24997}éao mi je, ali ja ne mogu|niöta da uradim.
{25001}{25100}Molim te, ne volim bolnice.|Moram da odem odavde.
{25103}{25211}Dobro, dogovoriÊemo se.|Ostani ovde. DoneÊu ti odeÊu
{25214}{25312}i kad se vratim|idemo na piÊe. Moûe? Vaûi?
{25334}{25399}Trebaju mi cipele i kaput.|-Da, doneÊu ih.
{25402}{25467}Ali neÊu se vratiti|ako sad ne ostaneö.
{25470}{25519}OK.|-Vaûi.
{25965}{26043}Izgleda da Êe biti dobro.
{26046}{26134}Zove se Dûek Teri.|Izvukao je devojku iz auta.
{26137}{26254}Ponaöa se kao prava budala.|Ne znam kako Êemo to zataökati.
{26257}{26343}Dovedite ljude. HoÊu da se|smiri ovo mesto. NeÊu cirkus.
{26346}{26441}Ovo je taj. Bio je tamo na|licu mesta. Sve je video.
{26444}{26555}On je sve video? -Da, zove se|Dûek Teri. Izvukao je devojku iz auta.
{26676}{26755}HoÊu da razgovaram sa vama.|I sa devojkom, takoe. Gde je ona?
{26758}{26803}Tamo je.|-Sad spava.
{26806}{26886}Ako hoÊete da razgovarate|samnom, budite brzi, jer hoÊu kuÊi.
{26889}{26971}Moûemo li negde nasamo|da razgovaramo? -SrediÊu to.
{26974}{27059}Osiguraj onu sobu.
{27062}{27159}Gospodine, öta se dogaa? -SaobraÊajna|nesreÊa. »ovek je poginuo.
{27162}{27256}Znam to. »emu ovolika frka?|-Jesi li znao da je to Mekrajan?
{27259}{27292}Guverner Mekrajan?
{27295}{27389}Mrtvac na kolicima bi verovatno|bio naö sledeÊi predsednik.
{27418}{27470}Moj glas bi dobio.|-Isuse Hriste.
{27556}{27605}Hajdemo unutra da razgovaramo.
{27847}{27921}Izvukli ste devojku iz auta?|-Jesam.
{27951}{28058}Voleo bih da zaboravite|da ste je ikada videli.
{28079}{28123}»ekaj malo.
{28126}{28194}Ko ste vi?|-Zovem se Lorens Henri.
{28197}{28272}Radim za guvernera Mekrajana.
{28275}{28324}Bio mi je takoe i prijatelj.
{28354}{28403}Pravi prijatelj.
{28444}{28505}éao mi je zbog guvernera.
{28508}{28620}OËigledno bi ste ûeleli da|sam spasao i njega. Ali...
{28642}{28701}Ja sam bio tamo...|ona je bila ûiva.
{28705}{28794}Znamo öta se desilo.|Guverner je mrtav.
{28819}{28890}Ne ûelimo da osramotimo|njegovu porodicu.
{28893}{28983}Znate li öta bi novinari|uËinili da se doËepaju ovoga?
{28986}{29064}äta hoÊete da kaûem, da nije|bila tamo? VeÊ sam rekao policiji.
{29067}{29116}To je veÊ sreeno.
{29188}{29313}Dobro. A öta Êemo s devojkom?|-RazgovaraÊu s njom. SaraivaÊe.
{29316}{29409}Jednostavno Êe nestati iz|Mekrajanovih kola? Tek tako?
{29412}{29489}Tako je.|-Gospode. Ne znam.
{29492}{29611}Zar ne moûete da Êutite?|Bolje da je guverner poginuo sam.
{29649}{29732}Ne znam da li mogu tako.|Ja sam bio tamo, i ona je...
{29735}{29807}Koga je briga|öto ste bili tamo?!
{29810}{29910}HoÊete reÊi njegovoj ûeni da je|umro öetajuÊi neku devojku?
{29913}{29987}Ili da to proËita u novinama?|-Ali tako se desilo.
{29990}{30102}To je istina, zar ne?|-äta to vama znaËi?
{30156}{30253}Ali njegovoj porodici|bi to mnogo znaËilo.
{30439}{30458}U redu.
{30461}{30538}IzveöÊemo vas i|devojku na zadnji ulaz.
{30697}{30752}A da odemo kao tebe?
{30755}{30804}NeÊeö kuÊi, zar ne?
{30853}{30954}Rekla sam ti ko je|bio u autu, je li? -Jesi.
{30957}{31078}Neki pametni novinar mogao|bi zakljuËiti da sam i ja bila tamo.
{31081}{31180}Tamo mi je torba sa|dokumentima i haljina.
{31183}{31242}Moûda Ëeka|pred mojim vratima.
{31246}{31349}Ili pred mojim. Ja sam onaj|koji te je spasao.
{31352}{31453}Da, taËno.|Hajdemo u hotel.
{31543}{31634}Prvo piÊe, onda moj|stan, a sad i hotel.
{31637}{31691}Ovo ide vrtoglavom brzinom.
{33697}{33783}Lepa noÊ za öetnju.|-Jeste.
{33809}{33892}Hajde da proöetamo uz reku.
{33895}{33965}Baö lepo.
{33968}{34038}Pogledaj, neko je na mostu.|-Nije vaûno.
{34041}{34093}Bulji u nas.|-Ma, koga je briga?
{34096}{34137}Mene je briga.|-Betsi.
{34140}{34211}NeÊu viöe da ostanem ovde.
{34214}{34264}äta to radi?|-Ne znam.
{34267}{34378}äta je on? Neki voajer?|-Nije vaûno. Idemo ovuda.
{36032}{36060}Isuse Hriste!
{36753}{36802}Sranje!
{39858}{39917}HoÊeö li kafu?
{39982}{40072}Ej! HoÊeö li kafu?|-A? Dobro jutro?
{40076}{40131}Kako si?|-Dobro. Kako si ti?
{40134}{40200}Vrlo dobro.
{40203}{40297}äta to radiö?|-Sluöaö muziku?
{40300}{40409}Ne. Ovo je...|Ovo je moj posao.
{40412}{40488}Snimam zvuËne efekte|za filmove. -A, filmovi.
{40491}{40565}SinoÊ sam snimao zvuËne efekte.
{40568}{40617}äta su to zvuËni efekti?
{40620}{40776}Znaö ono, kad gledaö film Ëujeö|lupanje vrata, cvrkut ptice, vetar.
{40779}{40925}Snimam te zvukove i montiram|ih u film, pa tek onda gledaö film.
{40965}{41016}Radiö dobre filmoe?|-Ne, samo...
{41019}{41074}Samo one loöe, na ûalost.
{41077}{41132}Ja stvarno oboûavam filmove.
{41135}{41271}To mi je veoma zanimljivo,|jer se bavim öminkanjem.
{41274}{41385}Zasad samo u eklamne svrhe.|Sanjam o öminkanju na filmu.
{41388}{41489}Videla sam velike zvezde.|Na primer, Barbaru Strejsend.
{41509}{41561}Ne öminkaju je kako treba.|-Ne.
{41564}{41648}Ja znam kako da sredim lice.|-Stvarno? To je dobro.
{41664}{41717}HoÊu da neöto Ëujeö.
{41747}{41863}SinoÊ sam snimao neke zvukove.|Snimio sam i tvoju nesreÊu.
{41866}{41912}Sve imam na traci.
{41915}{41982}Snimio si nesreÊu?|-Da, jesam.
{41985}{42084}Samo, mislim da nije bila nesreÊa.|Mislim da je neko pucao u gumu.
{42087}{42158}To je ludost.|-Ne, nije. Sluöaj ovo.
{42161}{42289}»uÊeö dva zvuka. Prvi je|pucanj, a drugi eksplozija gume.
{42292}{42341}OK? Sluöaj.
{42547}{42622}»uj ponovo. -»uje se prasak.|Moûda je i bio pucanj.
{42625}{42729}Ali iskreno reËeno, uopöte mi se|ne sluöa repriza sinoÊne veËeri.
{42732}{42781}»ini me nervoznom.
{42784}{42835}Mogu li da te pitam neöto?|-äta?
{42838}{42889}äta si radila sa Mekrajanom?
{42951}{43056}To je vrlo liËno pitanje.|To se tebe ne tiËe.
{43059}{43141}Ne mislim na detalje, samo...|-Hladno mi je i nisam naöminkana.
{43144}{43196}Daj, Sali, zaboravi.|-Kakva pitanja.
{43199}{43280}»ak ne znam ni ko si ti.|-Voleo bih da me upoznaö.
{43283}{43351}äta Êemo za ono piÊe?|-Neki drugi put, OK?
{43354}{43461}Sali, spasao sam ti ûivot. Mogla|bi bar da popijeö piÊe samnom.
{43511}{43617}OK. Nazovi me kod drugarice|Dûudi Demings. BiÊu tamo.
{43620}{43710}NaÊi Êeö je u imeniku.|-Govoriö li istinu?
{43714}{43773}Da.|-Dobro, pozvaÊu te.
{43776}{43804}Vaûi.
{44501}{44583}Snimljena je Mekrajanova|nesreÊa. »uo sam na radiju.
{44586}{44630}Moûda je na TV-u.|-äta?
{44633}{44679}Film kako je Mekrajan poginuo!
{44693}{44772}Ma kako neverovatno zvuËalo,|lokalni fotograf Meni Karp,
{44775}{44842}bio je na mestu|nesreÊe s kamerom.
{44845}{44980}Saznajemo da je g. Karp prodao|film Ëasopisu "News Today".
{45038}{45188}Frenk Donahju je razgovarao s njim|ispred redakcije, pre nekoliko minuta.
{45197}{45296}Otiöao sam tamo da|bih probao novi film.
{45299}{45422}Vrlo je pogodan za noÊna|snimanja. Mnogo radim noÊu.
{45426}{45559}Stajao sam tamo i iznenada |Ëuo kako se pribliûava auto.
{45562}{45668}Nisam obraÊao paûnju dok|nije poËeo da proklizava.
{45671}{45783}Automatski sam se okrenuo i|snimio kako probija ogradu i pada.
{45786}{45865}G. Karp, Frenk Donahju.|-Dobro.
{45868}{45935}Da li je guverner vozio?|Da li je imao kontrolu nad autom?
{45938}{46010}Kontrolu? Sleteo je s puta.|Siurno nije imao kontrolu.
{46013}{46079}Da li je bio sam u kolima?|-Pa, ja nisam nikoga video.
{46082}{46169}Zaöto niste otiöli u policiju?|-O, ne! Ne!
{46172}{46241}Nijedan policajac nije|pomogao meni.
{46244}{46309}Ne bi mi platili koliko ovi.
{46312}{46353}Gde ideö?|-Moram da idem.
{46356}{46430}Moraö da ideö?|äta je sa audicijom?
{46433}{46502}Ekskluzivni snimci|Mekrajanove smrti.
{46505}{46594}Jedan po jedan, molim.|Ekskluzivni snimci Mekrajanove smrti.
{46651}{46688}KonaËno!|-Je li Rik tu?
{46691}{46802}Ne. Sem vodi audiciju.|-Daj mi kljuË. Brzo!
{46817}{46891}A Sem i devojke?|-DoÊi Êu posle.
{47270}{47316}Dûek?
{47384}{47448}Hajde, otvori!|Ja sam. Sem!
{50612}{50691}Ovo je kljuËni trenutak|u filmu, morate to da shvatite.
{50694}{50765}Hej, Dûek, gde ideö?|-Odmah se vraÊam.
{50768}{50827}Sad si mi potreban.|Dolazi ovamo.
{50935}{50984}äta misliö?|-Nastavi da traûiö.
{50987}{51037}Da nastavim da traûim?|Dûek, o Ëemu priËaö?
{51397}{51518}éao mi je, Dûek, pretrpan sam.|-Molim te, uËini mi uslugu.
{51521}{51584}VideÊu öta mogu da uradim.|Doi posle ponoÊi.
{51611}{51660}Sali, ovde Dûek.
{51674}{51734}Vidiö? Rekao sam ti|da Êu te nazvati.
{51737}{51796}äta Êemo s onim|obeÊanim piÊem?
{51868}{51917}Gde ideö?
{51962}{52013}Da se naemo na stanici.
{52235}{52274}Sali!
{52277}{52309}Zdravo!|-Zdravo!
{52312}{52389}Drago mi je öto sam te uhvatio.|-Bila sam na vratima.
{52422}{52465}Imam samo 20 minuta.
{52468}{52558}OdliËno. PopiÊemo|piÊe i ideö na put.
{52561}{52622}Pa... hoÊu da uhvatim |dobro mesto.
{52626}{52720}Daj, nemoj, Sali. ObeÊala si mi.|-Dobro, ali samo 10 minuta.
{52724}{52798}Vaûi. Daj da ti ponesem ovo.|-OK, hvala.
{52818}{52867}Kako se oseÊaö?|-PriliËno dobro.
{52870}{52919}Lepo izgledaö.|-Hvala.
{53152}{53258}äta prvo vidiö kad|nekoga upoznaö?
{53261}{53320}Noge. Oboûavam noge.
{53369}{53474}Ma daj! -Dobro.|Lice. Vidiö lice. -TaËno.
{53477}{53631}Ako ti lice ne izgleda kako treba,|niko te viöe neÊe ni pogledati.
{53634}{53728}Tvom licu ne treba öminka.|-Svakom licu treba öminka!
{53731}{53790}Ali ne sme izgledati|naöminkano. -Shvatam!
{53794}{53927}Sve sam pokrila na svom|licu, tako da ne vidiö öminku.
{53930}{54090}Sad si naöminkana? -Da, jesam.|-Ne verujem ti. -Ozbiljno!
{54093}{54198}Za to sam izgubila dva sata.|Ovo je izgled bez öminke.
{54201}{54304}Stvarno? Hteo bih da vidim|kakav je izgled sa öminkom.
{54307}{54395}Pa, to... to radim samo|za posebne prilike.
{54398}{54469}A slomljeni nos?|Kako bi to sredila?
{54472}{54546}To je lako.|Samo uzmeö malo...
{54549}{54639}»ekaj malo. Da vidim.|Mislim da mogu da ti pokaûem.
{54642}{54700}Treba ti ovakva Ëetkica.
{54703}{54760}Uzmeö malo smeeg pudera.
{54763}{54837}Uzmeö samo malo...|-»ekaj, öta to radiö?
{54840}{54907}»ekaj malo!|Ovo je ozbiljan posao.
{54910}{54977}Dobro, izvini!
{54980}{55130}Naneseö ga ovde. Ali moraö|biti paûljiv da se ne primeti.
{55133}{55207}Zaöto se smeökaö?
{55210}{55283}Zadivljen sam öto|toliko znaö o tome.
{55286}{55346}To te ne zanima!|-Zanima me.
{55349}{55435}Ne zanima te. Samo me|zagovaraö da bih propustila voz.
{55438}{55511}Nije istina.|Samo nisam hteo da odeö.
{55514}{55538}Zaöto?
{55541}{55620}Zato öto mi se sviaö.|Tek smo se sreli, a ti veÊ odlaziö.
{55623}{55736}Ne znam niöta o tebi.|-äta te zanima? Sve Êu ti reÊi.
{55779}{55852}Dobro, ti si ton-majsto, je li?|-Jeste.
{55855}{55907}Kako si dobio posao?
{55910}{55967}Dobro pitanje.|Ne znam.
{55996}{56072}Ne, reÊi Êu ti.|Sve je poËelo u ökoli.
{56075}{56179}Kao deËak sam popravljao radio-|-aparate, napravio sam svoj stereo,
{56182}{56249}Sva ta Ëuda...|znaö taj tip deËaka.
{56252}{56346}Posle toga, kad sam otiöao u|vojsku, tamo sam usavröio veötinu.
{56349}{56415}Stvarno?|Bio si u ratu?
{56418}{56544}Ne, ne. Bio sam dobar vezist.|Nisu mi dali da napustim Nju Dûersi.
{56547}{56647}Kratko sam radio u policiji,|i posle sam poËeo na filmu.
{56650}{56705}»ekaj malo. Bio si pandur?
{56708}{56781}Ne. Radio sam za|King Komiön. -Ko su oni?
{56784}{56881}PolitiËari koji su hteli da|zaustave korupciju u policiji.
{56884}{56951}Tada sam prekinuo i...
{56954}{57004}Zaöto si to uradio?
{57007}{57146}Duga je to priËa. ne zanima te.|-O, zanima me. Vrlo je interesantno.
{57172}{57227}Mislio sam da te|viöe zanimaju filmovi.
{57230}{57357}Filmovi su zanimljivi, ali...|ovo je pravi ûivot na ulici.
{57360}{57409}Uzbudljivo je.
{57453}{57502}Dobro.
{57505}{57642}OzvuËio sam najboljeg tajnog|policajca. Zvao se Fredi Kors.
{57645}{57731}Njegov zadatak je bio da|namesti korumpiranom kapetanu
{57734}{57786}koji je ucenjivao mafijaöa.
{57789}{57883}Moj posao je bio da ga|ozvuËim i snimam razgovor.
{57886}{57945}Stani malo. Kako to|misliö "da ga ozvuËiö"?
{57948}{58072}Zalepio sam mu mikrofon|sa odaöiljaËem oko pojasa.
{58175}{58224}Meki, dadaj mi traku.
{58248}{58365}Fredi, daj mi signal. Broj|do deset. -Jedan, dva, tri...
{58549}{58617}OzvuËenje je bilo sjajno. Mogli su|da budu nekoliko blokova daleko
{58620}{58693}i ja bih sve Ëuo kao|da su na dva metra od mene.
{58696}{58767}-Hej, Milte. Kako si?|-Zdravo, Fredi.
{58770}{58835}Drago mi je da te vidim.|Dobro izgledaö. -Hvala.
{58838}{58914}I ti. Dobro izgledaö u|tom odelu. 
{58928}{59008}Doveo sam nekoga|koga ûelim da upoznaö.
{59011}{59060}Kapetane Kenedi, ovo je Milt.
{59063}{59115}Koga je briga za|kapetana Kenedija?
{59118}{59217}Smiri se, Milte.|-Ne ûelim da se upoznam s njim.
{59220}{59318}Polako! On je|Ëovek na poloûaju.
{59321}{59405}Dobro, hajdemo u kola. Idemo|da se provozamo i da popriËamo.
{59408}{59492}Prvo je kapetan rekao mafijaöu:
{59495}{59651}Znam da on ima öuraka. Video|sam ga kako razgovara s njim.
{59654}{59720}äurak je poznati kriminalac.
{59723}{59802}Milt je uslovno puöten|i ne sme da se druûi s njim.
{59809}{59945}Moram to da javim socijalnom|radniku. VratiÊe ga u Êorku.
{59954}{60075}Ali moûemo da se dogovorimo.|∆utaÊu za 5000 dolara.
{60086}{60267}5000$? Jesi li ti lud? PoËetna|svota je bila 1000$. -1000&?
{60270}{60370}»uo sam vrlo jasno,|ali tada su poËele smetnje.
{60752}{60818}UhapsiÊu ga, razumeö?|-U redu.
{60821}{60905}äta ti je? Znojiö se, Fredi.|äta ti je?
{60916}{61027}Nisam raËunao na to da Êe|Fredi postati nervozan i znojiti se.
{61051}{61144}Znoj je pregoreo bateriju|i kiselina ga je grizla.
{61147}{61230}Stani kod ove pumpe.|Moram da piöam.
{61823}{61855}Sranje.|-äta je?
{61858}{61972}Baterija se topi.|Kiselina ga grize. Idem unutra.
{61975}{62047}Ne, otkriÊeö ga.|Moram unutra.
{62050}{62178}Ne moûeö! -Baterija ga grize!|-Briga me. Sve Êeö uprskati.
{62237}{62281}Moram da idem.|-Dûek, ti si lud.
{62761}{62810}O, Isuse Hriste!
{63471}{63575}Nije tvoja krivica.|-Da, reci to Frediju.
{63578}{63644}Jebi ga.|Jesi li dobro?
{63647}{63770}Ne. Neöto me muËi. Cela ova stvar sa|Henrijem, guvernerovim pomoÊnikom.
{63773}{63878}I s tobom je razgovarao?|Zbog toga odlazim iz grada.
{63881}{63940}Platio mi je da odem na nekoliko|meseci. -Tako sam i mislio.
{63990}{64049}Pokrivaju mnogo viöe od vaöe veze.
{64052}{64140}Neko je pucao u gumu.|-Kako moûeö biti tako siguran?
{64144}{64230}Jesi li videla slike|u "News Today"? -Jesam.
{64233}{64288}MontiraÊu na njih zvuk|koji sam snimio.
{64291}{64381}Kad budeö videla, biÊeö|sigurna da guma nije pukla.
{64416}{64451}Ne znam.
{64454}{64522}UËini mi uslugu,|ostani na nekoliko dana.
{64525}{64612}Zaöto?|-Mislim da mi moûeö pomoÊi.
{64615}{64752}Ne znam. VeÊ sam se|gadno zaglibila u problemima...
{64755}{64812}Ako time rasteretim savest,
{64816}{64890}moûemo otiÊi zajedno.|Mislim... öto da ne?
{64893}{64972}Kakvog smisla ima|da odlaziö sama?
{65005}{65054}Ne znam.|-Ma hajde.
{65206}{65263}Moram prvo da razmislim.
{65380}{65429}RazmisliÊu o tome.
{71185}{71240}Hej, Sali, kako si?
{71243}{71342}Drago mi je öto te vidim.|Gledam dobar film na TV-u.
{71345}{71394}Sjajno izgledaö.
{71409}{71483}Pa... öta radiö?
{71568}{71668}Jesi li za piÊe?|Moûe viski?
{71905}{71954}Da?|-Ja sam, Sali.
{72043}{72117}Hej, Sal, ui!
{72120}{72183}Sjajno izgledaö!|äta ti radiö ovde?
{72186}{72255}Gospode, Meni!|Zar ovu sobu nikada ne Ëiste?
{72258}{72357}Treba rano ustati i uhvatiti|sobaricu. Joö uvek nisam uspeo.
{72397}{72514}Drago mi je öto si svratila.|Kako si me naöla?
{72517}{72644}Radili smo ovde milion puta.|-Tako je. Jesi li za piÊe?
{72647}{72729}Nisam doöla na piÊe.|-Nisi?
{72732}{72822}Ono veËe me zamalo|nisi ubio. UBIO, razumeö?
{72825}{72938}Duöo, nisam imao niöta s tim.|To je bio nesreÊni sluËaj. -Je li?
{72941}{73015}A öta je bilo s tobom?|-Kako to misliö?
{73018}{73104}Zbrisao sam Ëim sam video|da momak skaËe u reku!
{73107}{73204}Obavio je to mnogo bolje,|nego öto bih ja to ikada mogao.
{73207}{73365}Ne znam da li sam ti rekao|ranije... ja ne znam da plivam.
{77320}{77369}Super!
{78792}{78916}Znate li koliko je ovde bilo|ludaka sa priËom o zaveri? -Ne znam.
{78919}{79039}Da mi svaki plati 10 centi, kupio|bih celu Floridu i penzionisao se.
{79042}{79113}Na slikama se jasno|vide bljesak i dim.
{79116}{79233}To moûe biti svaöta.|Zaöto sve mora da bude zavera?
{79236}{79342}»ovek popije koju previöe,|sleti s puta i padne u reku.
{79345}{79428}NesreÊa! Prosto i jednostavno.|-Nije nesreÊa.
{79431}{79508}Bio sam tamo. Neko je|pucao u gumu. »uo sam i snimio.
{79511}{79613}Dakle, Ëuli ste ubistvo.|OdliËno! To mi se baö svia!
{79616}{79701}Jeste li vi zaduûeni za istragu?|-Jesam.
{79704}{79784}Da li ste proverili Mekrajanovu|gumu? ñNisam. Zaöto bih?
{79787}{79837}Jer je na njoj rupa od metka.|Zato öto je ubijen.
{79840}{79914}To vi kaûete. Svi ostali|kaûu nesreÊa. -Ko?
{79917}{80013}Osnovana je posebna komisija koja|Êe potvrditi da je reË o nesreÊi.
{80016}{80052}Samo Êe to da kaûu?
{80055}{80157}Oni nemaju dokaza. Nemaju traku|i gumu. Nisu razgovarali sa mnom.
{80160}{80273}Znam mnogo o tvojim trakama.|Zbog tebe su umrli dobri policajci.
{80289}{80350}Ovo nema veze s tim.|Nemate prava to da kaûete.
{80354}{80419}Gadite mi se!|Eto, to je zajedniËko.
{80422}{80523}Ako te ne volim, ne znaËi|da neÊu da obavim svoj posao.
{80526}{80642}Daj mi traku. PoslaÊu je|u laboratoiju na proveru.
{80645}{80747}Pogledajte moj film sloûen|iz fotografija. ShvatiÊete.
{80750}{80840}Ako nabavimo Karpov original,|pucanj Êe biti mnogo jasniji.
{80843}{80932}Karp se bogati prodajom|slika od Ëasopisa do Ëasopisa.
{80935}{80996}Zaöto misliö da bi|ih dao nama?
{80999}{81075}Mora. To je dokazni materijal.|-Ne mogu da ga naem, Teri!
{81078}{81160}Naite ga. To je vaö posao. -Ne|govori mi kako da radim moj posao.
{81163}{81242}Moûe da nam kaûe öta je|tamo radio s kamerom.
{81245}{81300}Niko ne ûeli da zna.|Nikoga nije briga.
{81303}{81393}Ne ûele prljave pojedinosti.|Ni politiËki atentat. NesreÊa.
{81396}{81472}»ovek je mrtav.|To mu neÊe pomoÊi!
{81475}{81536}Nije to zbog njega!|Znam da je mrtav.
{81540}{81641}Zar ne shvataö? Ako nekaûnjeno|mogu ubiti Mekrajana, ko je  sledeÊi?
{81644}{81714}Ko "oni"? Prvo mi|objasnite ko su "oni".
{81717}{81849}KomunistiËki zaverenici? Ili moûda|Iranci s ilegalnim oruûijem?
{81852}{81928}Dajte prestanite.|SaËuvajte paranoju za TV.
{81931}{81969}Jebite se.|Odlazim.
{81972}{82103}Ostavite te slike ili Êu vas uhapsiti|zbog sakrivanja dokaznog materijala.
{82106}{82150}Tako znaËi.
{82153}{82246}Dobro. BiÊu u kancelariji ceo dan.|Moûete me tamo nazvati.
{82249}{82290}Ja Êu zvati vas.|Ne zovite vi mene.
{82479}{82528}Ovde Burk, gospodine.|-Ko?
{82553}{82597}Burk, gospodine.
{82600}{82699}Burk, öta si to uradio?|-Ne razumem pitanje.
{82702}{82784}Jesi li lud? Trebao si|samo da ugovoriö slikanje.
{82787}{82846}Znate li öta govorite?
{82849}{82873}Gde si?
{82876}{82976}Zovem iz govornice.|Predlaûem da me nazovete.
{83626}{83675}Oprostite, je li g. Karp tu?
{83689}{83729}Mogi li da uem?|-Zaöto?
{83732}{83802}Samo ûelim da uzmem slike.|-A ko ste vi?
{83805}{83911}Muöterija.|Imao je mnogo muöterija.
{83914}{83958}Vi ste novinar, zar ne?|-Nisam.
{83961}{84040}I vi ûelite Karpov film, je li?|-Ne znam o Ëemu govorite.
{84043}{84143}äteta öto ne postoji zakon protiv|laganja. Baö bih se "nahapsio".
{84146}{84253}Ja sam muöterija i uzeo bih|svoje slike. -I on je muöterija.
{84256}{84320}Ponudio mi je 1000 dolara.|-Stvarno?
{84323}{84384}A njegova ûena tri.
{84387}{84459}Ne izgleda mi toliko vredan,|ali valjda ona zna öta radi.
{84462}{84538}Izgleda da je Karp|zaraivao na razvodima.
{84541}{84651}Nije ga briga za muöterije. Ovo|sam naöao pod njegovim krevetom.
{84704}{84777}Trebao si da namestiö|slikanje Mekrajana, a ne ubistvo!
{84780}{84861}Shvatio sam cilj operacije,|ali se nisam sloûio s njim.
{84864}{84919}Nisam ga ja ubio,|to je nesreÊan sluËaj.
{84922}{85000}SluËajno si pucao u gumu?
{85008}{85104}Ako se seÊate, taj plan sam|predloûio na sastanku 6. juna.
{85107}{85173}Taj plan je odbijen,|zar se ne seÊaö?!
{85176}{85251}Priznajem, malo sam|prekoraËio dopuötenja.
{85254}{85320}Ali sam uvek bio|izvan moguÊnosti greöke.
{85323}{85423}Ali cilj je postignut.|IzbaËen je iz kampanje.
{85431}{85545}Burk, ja te ne poznajem.|Ja te nikada nisam video.
{85548}{85642}Nemoj me nikada viöe zvati.|-Samo malo. Nije sve reöeno.
{85659}{85716}Promenio sam gumu|i namestio gumidefekt.
{85720}{85801}Izbrisao sam trake onog momka.|Svi Êe misliti da je ludak.
{85804}{85858}Karp je nestao, ali naÊi Êu ga.
{85861}{85918}Meutim, ostaje devojka.
{85922}{86037}OdluËio sam da je ubijem. IzgledaÊe|kao serijsko seksualno ubistvo.
{86040}{86127}To Êe osigurati naöu operaciju.|-Kakvu operaciju?
{86248}{86310}Hajde, Beti, pokuöaj ponovo.
{86343}{86392}28. put.
{86478}{86516}Dosta!
{86519}{86584}Dosta. Moraö da govoriö|u mikrofon. Ne Ëuje te.
{86587}{86636}Dosta!
{86689}{86748}Dobro... zamenite se.
{86763}{86829}Beti. vuci je za kosu.|Dûejn, ti vriöti.
{86852}{86898}29. put.
{87192}{87266}Sem, biÊu u svojoj sobi.|-Hej! Gde si ti, do avola?!
{87269}{87363}Imao sam posla.|-Zaveûi!
{87366}{87443}Mislio sam da radiö za mene.|-Radim. U Ëemu je problem?
{87446}{87530}Trebaju nam efekti za drugi kotur.|Imamo spisak. -OdliËno, nabaviÊu ih.
{87533}{87640}Nisam joö dobio ni|vrisak za prvi kotur. -Da.
{90335}{90399}Zaöto se ne javiö?|To je policija.
{90402}{90457}Ko je bio ovde?|-Neki tip. Rekao je...
{90460}{90539}Koji tip!|-Ne deri se na mene.
{90657}{90706}Da?|-Koji je tebi avo?
{90709}{90796}äta je?|-Traka koju si mi dao je prazna!
{90799}{90841}Sve trake su prazne!
{90844}{90932}Ne razumem te. Prvo mi|napuniö glavu atentatom,
{90936}{90985}a onda mi daö praznu traku.|Zaöto?
{90988}{91062}Zato öto je neko izbrisao traku.|Izbrisali su mi sve trake.
{91065}{91142}Aha, "oni" su ih izbrisali.
{91145}{91248}äta Êe biti sledeÊe? PokuöaÊe|da te ubiju? Ti si lud!
{91395}{91450}Sali, ovde Dûek.
{91453}{91542}Sluöaj me. Moram da ti|pokaûem film koji sam napravio.
{91545}{91609}Ostani kuÊi, odmah dolazim.
{91836}{91907}Da li je Dûek Teri tu?|-Jeste.
{91910}{91967}Ja sam Frenk Donahju.|-Debi.
{91970}{92066}Evo ga. -Dûek. Kako ste?|Ja sam Frenk Donahju.
{92084}{92152}"Gradska panorama".|-A, da.
{92155}{92211}Moûemo li da razgovaramo?|-Ne, sada ne.
{92214}{92320}Samo dva minuta. Doöao sam|samo zbog toga. Samo dva minuta.
{92323}{92392}O Ëemu ûelite da razgovaramo?|Vrlo je liËno.
{92395}{92444}Moûemo li uÊi tamo?
{92447}{92496}Moûe.|Dobro.
{92530}{92641}Ovde snimate filmove?|I ja sam hteo da budem glumac.
{92644}{92693}äta hoÊete.
{92711}{92793}Rekli ste policiji da je neko|pucao u Mekrajanovu gumu.
{92796}{92878}Ko vam je rekao to?|-Dûek, to nije vaûno.
{92881}{92953}Ja sam novinar.|Ja imam svoje izvore.
{92956}{93061}Zaöto bi ste se interesovali za|ludaka koji govori o atentatu?
{93064}{93113}Ja ne mislim...
{93116}{93203}Moûemo li uÊi unutra?|-Ne, ne. Idemo ovamo.
{93356}{93423}Ne mislim da ste ludi.|Zato sam ovde.
{93426}{93514}I ja sam pomalo istraûivao.|Svaöta se ne slaûe u toj...
{93518}{93606}kako policija kaûe,|bizarnoj nesreÊi.
{93610}{93714}äta je s devojkom? HoÊe da|zataökaju. Vi ste je videli.
{93718}{93765}äta je joö rekao vaö izvor?
{93768}{93875}Pa, izmeu ostalog,|i da ste snimili pucanj.
{93878}{93940}OdliËan rad, Dûek.|Rado bih Ëuo traku.
{93943}{94052}Mogao sam je snimiti i|u studiju. -Mogli ste, ali...
{94092}{94134}ne verujem.
{94137}{94227}Mislim da imate traku.|I to onu pravu.
{94246}{94351}Doite u emisiju. Svima|Êete reÊi öta ste videli i Ëuli.
{94354}{94483}A tada Êemo pustiti traku.|Sjajna priËa. äta kaûete?
{94486}{94593}Sranje! Niko neÊe poverovati.|Frenk Donahju veruje.
{94596}{94704}A njega svake veËeri|gleda osam miliona ljudi.
{94707}{94781}Ako pristanete, garantujem|vam da Êe sutra uveËe
{94784}{94902}svih osam miliona ljudi|verovati u priËu Dûeka Terija.
{95831}{95914}Da, Ëula sam trenutak|pre eksplozije gume.
{95917}{95969}U pravu si.|To je pucanj.
{95972}{96064}Jesi li to odneo u policiju?|Dao sam im kopiju.
{96068}{96117}Poslali su je u laboratoriju.|I bila je prazna.
{96120}{96179}Neko ju je izbrisao.|Jesi li siguran?
{96182}{96294}Ja sam je snimio. Puötao sam je,|a sada je prazna kao i sve trake.
{96297}{96430}Smiri se. Zvuk je vrlo jasan,|samo je slika malo mutna.
{96433}{96514}Niko neÊe verovati.|ReÊi Êe da sam je montirao.
{96517}{96616}PoËinitelj ima veze s policijom.|Oni hoÊe da Mekrajan nestane.
{96619}{96684}Ne ûele da Ëuju o mom pucnju.
{96687}{96737}äta Êeö da uradiö?|-Molim?
{96740}{96819}äta Êeö da uradiö?|-Ja?! Valjda mi!
{96822}{96889}Kakve ja imam veze s tim?|-Ne seri, Sali.
{96892}{96982}Znam öta si radila u onom autu.|-äta ti znaö?
{96986}{97048}Ti i tvoj prijatelj Karp ste|hteli da ucenjujete Mekrajana
{97051}{97140}slikajuÊi vaö odnos|posle proslave. Zar ne?
{97143}{97224}Rekla su mu da te uzbuuje|voûnja preko vode?
{97227}{97326}Ko ti je to rekao?|-Video sam tvoje ranije snimke.
{97329}{97405}Imaö dobre sise. Ko je|platio za slikanje Mekrajana?
{97408}{97470}Ja nisam bila u kolima.|Zar nisi Ëitao novine?
{97473}{97577}Koliko Êe izdrûati Henrijeva kamuflaûa?|PriËao sam sa novinarom koji zna sve.
{97580}{97681}Izbrisali su mi trake, naterali te|da nestaneö, sada sam ja na redu.
{97684}{97746}Ali ja neÊu nestati.|-Je li? Ja hoÊu.
{97749}{97808}Ko ti kaûe da to neÊe biti zauvek?|-äta to treba da znaËi?
{97812}{97894}Nisam li te upoznao pod vodom?|To je bila nesreÊa.
{97897}{97972}Meni mi ne bi naudio.|-Nije li te smestio u auto?
{97975}{98079}Jeste, ali... -Misliö da nije znao|da Êe neko pucati u gumu?
{98130}{98179}Nije mogao znati.|-Ma daj, Sali.
{98182}{98301}Da te nisam izvukao, sada bi|bila mrtva. Zar ne shvataö to?
{98392}{98458}Sedi, hajde.|HoÊu da Ëijem sve.
{98461}{98529}IspriËaj mi sve|od poËetka.
{98532}{98649}Bio je to posao kao i drugi. Ja ih|odvuËem u krevet, Meni snima.
{98652}{98690}"Njih"? Koga "njih"?
{98693}{98767}Muûeve. Uglavnom|niûe gradske sluûbenike.
{98770}{98819}Zaöto?
{98848}{98926}Zbog novca.|-Tako straöno ti treba novac?
{98929}{98972}Znaö gde radim.
{98975}{99095}PlaÊaju mi da se smejem kao budala|i da pokazujem 27 razliËitih karmina.
{99098}{99255}Zaraujem bedno. Ali|niöta drugo ne znam da radim.
{99258}{99302}Zato sam to Ëinila.
{99305}{99378}Nisam baö imala|odnose sa njima.
{99381}{99455}Samo ih dovedeö u|nezgodnu situaciju. -Jeste.
{99458}{99580}Meni kaûe da to i zasluûuju,|ako se igraju vatrom.
{99583}{99639}Ne moûeö da zavedeö poötenog.
{99642}{99725}Verovatno sam htela da mu verujem,|jer mi je tako bilo laköe.
{99763}{99867}A Mekrajan? äta je s njim?|-Meni me je odveo na proslavu.
{99870}{99980}Rekla sam Mekrajanu da je divan.|Trudio se to i da mi dokaûe.
{99983}{100057}Iöunjali smo se na zadnji|izlaz i otiöli njegovim kolima.
{100060}{100156}Ko je unajmio Menija|da vas slika? -Ne znam.
{100159}{100261}Milsliö da nije znao kako njegov|klijent planira da puca u gumu?
{100264}{100288}Ne.
{100291}{100384}Ne bi mu se isplatilo da ti|je rekao. -On to ne bi uËinio.
{100387}{100448}Zar nije hteo da zaradi?|-Jeste.
{100452}{100523}Sada je zaradio veliku lovu.|Koliki je tvoj deo?
{100526}{100586}PlaÊao mi je.|-Verovatno premalo.
{100589}{100669}äta se to tebe tiËe. -Dosta mi je|da me ti tipovi zajebavaju.
{100672}{100773}Prvo me Henri natera da Êutim|da bi saËuvao guvernerov ugled.
{100776}{100877}Onda saznam da je ubijen|i da nikoga nije briga za to.
{100880}{100960}Niko neÊe ni da Ëuje|o zaveri. Ne shvatam!
{100969}{101049}Da ti kaûem neöto.|Ja znam öta sam video i Ëuo.
{101052}{101138}I potrudiÊu se da svi u|ovoj drûavi to vide i Ëuju.
{101141}{101255}A ti Êeö mi pomoÊi. Nai svog|partnera Karpa i uzmi mu originalni film.
{101258}{101308}Ovo nije dobro.|Treba mi original.
{101311}{101416}Ako to ne vide svi na TV-u,|zatvoriÊe sluËaj.
{101419}{101510}A onda Êe visuljke, kao öto|smo ti i ja, odmah ukloniti.
{101513}{101589}Imaö izbor. Moûeö|biti luda ili mrtva.
{101592}{101713}PokuöaÊu da ti nabavim film.|Samo me posle otkaËi od svega.
{101716}{101781}Voleo bih da moûeö samo|da se brineö zbog mene.
{101784}{101872}Pokuöavaö da me uplaöiö. Ide ti dobro.|-Pokuöavam da nam spasem guzice.
{101875}{101932}Sama Êu se brinuti|za svoju, hvala ti.
{102406}{102494}Dogaaji poËinju da se povezuju.|-Je li? äta, na primer?
{102498}{102551}Izvoli.|-Kako sam s tim autom zavröila...
{102554}{102611}Smiri se, sedi.
{102614}{102706}Kako sam s tim autom|zavröila na dnu reke?
{102709}{102823}Pa, videla si. Momak vozi i|odjednom mu eksplodira guma.
{102826}{102911}Nije mu eksplodirala guma.|Neko je pucao u gumu.
{102914}{102982}O Ëemu govoriö?|Kako ti to znaö?
{102985}{103050}Znam. Jednostavno znam.
{103053}{103117}Ko je pucao?|Niko.
{103139}{103200}Reci, Meni.|BiÊe samo izmeu nas dvoje.
{103290}{103424}Nazvao me je neki ludak i rekao|da radi za nekog kandidata.
{103427}{103534}A taj bi voleo da izbaci|Mekrajana iz trke.
{103537}{103586}Izgledalo mi je kao|normalan posao.
{103589}{103681}Rekao mi je da je Ëuo|za naö rad i ponudio mi je 6000.
{103684}{103743}äest?|Meni si rekao tri.
{103775}{103844}Pa... tri odmah, a tri posle.
{103847}{103912}Kada bi mi rekao|za tri posle?
{103915}{104059}Kad ih dobijem, kad inaËe?|-Da, naravno.
{104062}{104116}Hej, öta je s tobom?
{104135}{104219}Misliö da te zajebavam?|Ne verujeö mi?
{104222}{104322}Kako sam mogao da budem |siguran da Êe mi tip platiti?
{104334}{104432}6000 je mnogo novca|za ovakav posao.
{104435}{104521}Izvukao je vrednost.|Nije trebao da pogine.
{104524}{104610}Nije trebao ni da bude povreen.|To je bila nesreÊa.
{104613}{104653}Tek posle sam shvatio.
{104656}{104800}Ludak je planirao da puca u|gumu i da izazove laköi sudar.
{104803}{104881}Policija bi ga tad izvuka|iz auta...  -Sa mnom?
{104884}{104955}Da, sa tobom.|A ja sam trebao sve da snimim.
{105007}{105058}Lep laköi sudar.
{105061}{105126}Nije trebao da pogine.|To je bila nesreÊa.
{105129}{105198}Koliko puta moram da ti kaûem?
{105218}{105280}Meni, mi smo ga ubili.
{105283}{105327}Stani malo, mi?
{105330}{105430}Kako to misliö.|Mi nismo niöta uËinili.
{105433}{105539}Ja sam bio u öumi, ti u autu.|Ja nisam pucao u gumu, a ni ti.
{105542}{105632}Pusti ta sranja|o savesti.
{105701}{105836}Osim toga, niko nije|plakao nad ishodom dogaaja.
{105849}{105913}äta bi se dogodilo|da je ostao ûiv?
{105916}{105981}Karijera bi mu bila|gotova zahvaljujuÊi nama.
{105984}{106063}A ovako, momak ostaje Ëist.
{106066}{106198}Svetac je. MuËenik! Jutros si|prihvatili jedan od njegovih predloga.
{106201}{106254}Ti si svinja, Meni.
{106257}{106376}I ja sam takoe.|-äta to govoriö? äta ti je?
{106379}{106501}Moram da kaûemo istinu pre nego|öto zakljuËe sluËaj i ubiju nas!
{106504}{106542}O Ëemu govoriö?
{106545}{106622}Mekrajan je ubijen.|To moraju svi da znaju.
{106625}{106754}Ti si luda. Mi smo ga|ubili. HoÊeö li u zatvor?
{106757}{106843}Ali ja sam bila u autu,|a ti u öumi.
{106846}{106932}Misliö da Êe nam poverovati?
{106935}{106983}Ne znam, ali neöto|moram da uËinim.
{106986}{107076}Samo ti zaveûi gubicu|i uzmi pare.
{107079}{107195}Ovo je velika stvar.
{107198}{107247}Briga me.
{107250}{107322}Ovo öto radimo je istorija.
{107325}{107376}ZaradiÊemo bogatstvo.
{107379}{107467}BiÊe u svim novinama.|BiÊe u svim Ëasopisima.
{107470}{107538}BiÊe na vestima|u 18h.
{107541}{107680}PraviÊe TV priloge,|a ja Êu traûiti bogatstvo.
{107683}{107791}Zar ne razumeö, zlato?|Malo smo zabrinuti.
{107794}{107916}Briga me! Ne ûelim da uËestvujem|u tome! Zadrûi 3000 posle.
{107935}{108062}Ne budi tako glupa.|Novac je novac.
{108099}{108178}Kao da smo leöinari.|-Prvo svinje, pa leöinari.
{108181}{108282}Jesi li pojela kutiju|krekera u obliku ûivotinja?
{108354}{108433}Treba mi piÊe, Meni.|Daj mi piÊe.
{108436}{108527}Da, sigurno. Evo piÊa.|-Daj mi flaöu.
{108636}{108685}Tako treba, malena.
{108698}{108832}äta kaûeö da odemo u|Atlantik Siti? -Ne svia mi se.
{108835}{108901}PokazaÊu ti grad. BiÊe|nam lepo. -Dosta! Pusti me!
{110177}{110226}FantastiËno!
{110229}{110278}OdliËno!
{110320}{110381}äta sad?|-Sjajna si.
{110384}{110467}NazvaÊu tipa sa TV-a|i idemo u program.
{110470}{110534}HoÊeö li da jedeö?|-HoÊu, hvala.
{110537}{110598}Moûe li kornfleks?|-Bilo öta.
{110701}{110774}Frenk Donahjua, molim.|Ovde Dûek Teri.
{110777}{110867}Da?|-G. Donahju, Dûek Teri zove.
{110870}{110927}G. Donahju?|-Dûek? Da.
{110930}{110996}Predomislio sam se.|HoÊu da Ëujete snimak.
{110999}{111118}Imam i Karpov film. Kada se|puste zajedno, sve se jasno vidi.
{111121}{111232}Sjajno! Sad sam zauzet. ZvaÊu|te za 20 minuta. Koji ti je broj?
{111263}{111333}Ne znam zaöto!
{111336}{111385}Htela je da to uËinim!
{111394}{111503}Sama je traûila.|Preklinjala me je! KuËka!
{111506}{111583}Nisam to hteo da uËinim!
{111586}{111666}Ona me je naterala.
{111669}{111733}Pitajte je, reÊi Êe vam.
{111736}{111824}OK. Gde je?|-Ne znam. Negde.
{111850}{111973}U onoj velikoj rupi iza|Redi marketa. Neöto grade.
{112002}{112126}Ali ne sluöajte je! Naterala|me je na to! -Recite mi gde ste.
{112210}{112316}Niöta neÊe vredeti ako se|liËno ne pojavite na TV-u
{112319}{112456}da kaûete öta ste videli|i Ëuli. -ReÊi Êu. -OdliËno.
{112459}{112553}äta je sa devojkom?|I ona je bila tamo.
{112556}{112615}Jeste, ali je ne meöajte.
{112618}{112726}Zaöto? -Ne ponosi se|onim öto je uËinila.
{112729}{112817}U redu. Mogu li|bar da razgovaram sa njom?
{112820}{112927}To zavisi od nje...|-Ok. SrediÊu to, Dûek.
{112930}{112990}Dûek, saËekajte|samo sekund.
{113058}{113143}Kad moûemo da se naemo|da vidim snimak? -Kad hoÊete.
{113146}{113232}OdliËno. Mogu li da vas nazovem|popodne? Gde Êete biti?
{113235}{113318}BiÊu kuÊi ceo dan.|-Onda Êu vas tamo nazvati.
{113340}{113397}∆ao. -Sad sam razgovarao|sa Donahjuom.
{113400}{113481}Ko je on?|TV reporter, istraûitelj.
{113484}{113537}Ime mi niöta ne znaËi.|Ne gledam vesti.
{113540}{113585}äta?
{113588}{113655}äta hoÊe?|-PustiÊe traku u emisiji.
{113658}{113717}DogovoriÊemo sastanak.|-Divno.
{113720}{113810}HoÊe da se i ja pojavim na TV-u|i kaûem öta sam Ëuo i video.
{113813}{113870}Sama traka|ne bi mnogo vredela.
{113873}{113991}HoÊe i ti da se pojaviö. -Zaboravi.|Ne ûelim niöta s tim da imam.
{113994}{114075}Znam da ne ûeliö, ali|hoÊeö li bar da priËaö s njim?
{114078}{114132}Ne, neÊu!
{114135}{114207}Daj, Sali. Ne mogu|da kaûu da oboje izmiöljamo.
{114210}{114297}Ako se pojavimo u javnost,|niko nam ne moûe niöta.
{114300}{114349}Dobro, ali moram da razmislim.
{114359}{114480}Jutros u skupötini, inspektor Meki,|odrûao je konferenciju za ötampu.
{114484}{114568}Prva istraûivanja o smrti|guvernera Mekrajana
{114571}{114636}pokazala su da je bio|ûrtva bizarne nesreÊe.
{114639}{114733}Sranje! -Imamo i vesti o|seksualnom ubistvu Meri Roberts
{114736}{114819}22 godine stara sekretarica|iz centra grada.
{114822}{114916}Telo joj je jutros|naeno na gradiliötu
{114919}{114987}nakon öto je policija|primila anoniman poziv.
{115317}{115460}Devojka je prvo zadavljena, a|posle izbodena u stomak i prepone.
{115463}{115538}Ubodi imaju oblik|zvona slobode.
{115541}{115630}Policija ne moûe da|objasni to groteskno znaËenje.
{115633}{115779}Pitali smo psihologa u kakvoj|su vezi zvonasti oblik rana
{115782}{115837}i skoraönja proslava|Dana osloboenja.
{115840}{115910}Ovde Sali.|-Zdravo, Sali. Ovde Frenk Donahju.
{115913}{115970}Trebali ste da nazovete Dûeka.
{115973}{116074}Stvar je vrlo vruÊa.|Ne mogu nikako da ga dobijem.
{116077}{116232}Telefon mu je stalno zauzet.|Zato zovem vas. -Da, i?
{116675}{116762}Telefon ti nije u redu.|Zovem te ceo dan, zauzeto je.
{116765}{116836}Kako to misliö.|Celo popodne Ëekam poziv.
{116839}{116929}I on te je zvao, zauzeto je.|-Kako to znaö?
{116932}{117005}Zvao me je. HoÊe da|se naemo u 5h na stanici.
{117008}{117092}Odakle mu tvoj broj?|-Nisi mu ga dao? -Nisam.
{117095}{117161}Nije bitno. Reporter|moûe da sazna sve brojeve.
{117164}{117288}NaÊi Êu se s njim i daÊu mu|traku i film. -Zaöto mene nije nazvao?
{117306}{117376}HoÊe nasamo da razgovaramo,|da me ubedi da se pojavim na TV-u.
{117379}{117429}Ne. Trebao je da me nazove.
{117432}{117568}Telefon ti ne radi. -Radi! Stalno|sam kod kuÊe. Zvao sam!
{117571}{117622}Evo, sluöaj.
{117639}{117721}Moûda je i poöta deo zavere.|-Ne, neöto se ne uklapa.
{117724}{117826}Nema veze. Dajmo mu|traku i film i zavröimo s time.
{117829}{117885}Kad dobije film|sve je gotovo.
{117934}{118067}U redu. HoÊe da se naete? -Da.|-U redu, otiÊi Êeö na sastanak.
{118070}{118194}DaÊeö mu film i traku.|-Gde Êeö ti biti? -Blizu.
{118197}{118263}Ne razumem.|-OzvuËiÊu te.
{118274}{118317}Da me ozvuËiö?|Zaöto?
{118320}{118419}éelim da se osiguram. Ovaj|put me neÊe niko preÊi.
{118468}{118568}Ako nestane s filmom, neÊe|to moÊi da porekne. SnimiÊu ga.
{118571}{118639}Da ti nisi malo paranoiËan?
{118642}{118734}On je reporter, ovo je velika priËa.|Zaöto nas ne bi ubacio u emisiju?
{118738}{118841}äta se desilo kad sam odneo|traku policiji? Izbrisali su je.
{118844}{118920}äta to radiö? -Pravim kopiju.|Ne smeta ako se osiguramo.
{118923}{118991}A öta je sa filmom?
{118994}{119068}Ne mogu sad da napravim kopiju.|Nemam vremena za to!
{119071}{119138}Dobro, dobro! OzvuËi me.|-Skini kaput.
{119141}{119171}Da zavröimo s tim.
{119541}{119643}Pretpostavljam da mnogo putujeö.|-Da, bio sam svuda po svetu.
{119646}{119693}I ja sam jednom putovala.
{119696}{119810}Onda imaö li 60 min i 60 dolara?
{119813}{119874}O, ne. Jesam li to rekao?|-Jesi, rekao si tako.
{119877}{119990}Ne, imam 20 min i 20 dolara.
{119993}{120085}äteta öto nemaö|40 min i 40 dolara.
{120088}{120155}Da, baö öteta.|-Da, prava öteta.
{120168}{120251}äta ako momak ima|20 min i 20 dolara?
{120254}{120389}Vozovi uvek kasne.|To se redovno dogaa.
{120392}{120548}Kladim se da imaö najmanje|30 min. -Misliö? -Najmanje.
{120551}{120676}Verujem da imam|30 min i oko 30 dolara.
{120687}{120752}OdliËno, moram da|pozovem nekoga.
{120755}{120829}NaÊiÊemo se za 2 min|na drugom kraju Ëekaonice.
{120832}{120939}To Êe ti biti 2 dolara manje.|Ali neka ti bude. Razumeö?
{120942}{121015}Ne razumem.|Razumeö li ti mene?
{121018}{121085}Vidimo se.|-Da, razumem te.
{121183}{121232}Hej, Ralfi!
{121497}{121605}Vi se samo igrajte! Ja Êu|da proslavim Dan osloboenja.
{122947}{123049}Uspori! Sranje!|-I ti si mi neki mornar!
{123052}{123153}Smeöno! Odrasti malo|i nauËi da se suzdrûiö.
{123156}{123230}Evo ti 10 dolara!
{123251}{123362}äta je s mojih 30 dolara?|Jebi se! -Zajebala si stvar!
{123407}{123456}Sranje.
{128069}{128165}Mislim da malo preterujeö?|-Nemamo öta da izgubimo.
{128168}{128269}Da sam pametna, bacila bih|sve to u smeÊe, i gotovo!
{128272}{128364}Ali imam original kod kuÊe.|-Pa Ëemu onda sve ovo?
{128367}{128451}Zbog Menijevog filma.|Moramo biti oprezni.
{128454}{128565}U pravu nevolju sam upala|samo kad sam bila preoprezna.
{128655}{128705}Moram da namestim ton.|Broj do 10, polako.
{128708}{128759}1, 2, 3,...|-Ne, sporije!
{128762}{128836}1, 2. 3...
{128839}{128910}Bolje da krenem.
{128913}{128974}Ne zaboravi da ovo imaö|na sebi. -OK.
{128977}{129034}Ako ti trebam, samo govori.
{129037}{129086}OK. Primljeno.
{129155}{129204}Sali, doi.|-äta je?
{129221}{129265}Hvala ti.
{129399}{129448}Prijem zavröen.
{130765}{130817}Halo, Dûek. Da li me Ëujeö?
{130820}{130934}Kad se ovo zavröi moûemo u Njujork.|Moûemo da odemo u pozoriöte.
{130937}{131055}Znaö, kao äugar Bejbi. A znam|i dobar hotel na Tajm Skveru.
{131058}{131095}Sali?
{131098}{131178}Ja sam Frenk Donahju.|-Drago mi je.
{131181}{131286}HoÊemo li malo da |proöetamo? -Kuda?
{131289}{131357}Mislim da imamo problemËiÊ.|-Kakav?
{131360}{131409}Moûda zvuËi ludo, ali...
{131433}{131513}Mislim da nas prate.
{132154}{132204}Boûe, kako brzo hodate!
{132219}{132291}U mom poslu morate|da imate brze noge.
{132294}{132378}Gde je Dûek?|-KuÊi, odmara se.
{132381}{132456}Posao izaziva napetost.|-Kojim vozom idemo?
{132459}{132563}Joö ne znam. Imate li traku|i film. -Da, u torbi su.
{132935}{133036}Umakli smo im, je li? -Nikad|ne moûete biti dovoljno oprezni.
{133039}{133177}Znate öta? Samo polako hodajte|do kraja perona ispred mene.
{133180}{133262}Ne shvatam zaöto mislite|da bi nas neko pratio.
{133265}{133344}Samo da znate öta bi|neki uËinili za ovakvu priËu.
{133347}{133404}Da, verujem.|-Ne, ne okreÊite se.
{133408}{133477}OdaÊete nas.|-Da, tako je.
{133480}{133562}Pretvarajmo se da|se niöta ne dogaa.
{133826}{133898}Pogledajte ovo mesto.|Ovo je odvratno!
{133901}{133991}Da, prava sramota.|»ak viöe nije ni sigurno.
{133994}{134078}PodseÊa me na priËu o onom|tipu iz Njujorka. SeÊate se.
{134081}{134180}Da, imali smo emisiju o tome.|Sakrije se u Êoöku podzemne
{134183}{134269}ûeleznice u doba najveÊe|guûve. Niko ga ne primeÊuje.
{134272}{134432}OtkopËa kaput, izvadi sekiru|i opali nekoga po glavi.
{134435}{134530}Idemo, Sali.|A kada su maöinovoe ötrajkovale
{134533}{134623}on je nestao.|Kao da je i on ötrajkovao.
{134626}{134662}Zato se viöe ne vozim metroom.
{134665}{134748}Nije sigurno. Da nema vas,|ni sada ne bih doöla.
{134847}{134889}Hajde, reci!
{134892}{135012}Eto, razumete? Kako se|samo ovaj priöunjao! Opasno je.
{135111}{135143}Dolazi voz.
{135205}{135242}HoÊemo li s njim?
{135245}{135330}Gde! Hajde!|-Tamo je vatromet veËeras?
{135333}{135402}Tako je.|Tamo je dobar bar.
{135405}{135519}Mogli bi da popijemo piÊe,|da razgovaramo i onda na vatromet.
{135522}{135559}Naravno.
{135562}{135624}HoÊete li mi pomoÊi|da sklopim priËu? -HoÊu.
{135649}{135717}IspriËaÊete je sa|ûenskog stajaliöta. -Da.
{135726}{135771}Franklin Bridû Ekspres?
{136111}{136191}»emu toliko galame oko Dana|osloboenja? -Bilo je na TV-u.
{136194}{136245}Ne gledam vesti.|Padam u depresiju.
{139063}{139112}Zovite Hitnu pomoÊ!
{139131}{139180}Probaj pozadi.
{139531}{139580}16 ili 35?
{139583}{139674}Na öta mislite?|-äirina filma.
{139677}{139752}U TV stanici imamo|ureaje za 16 mm.
{139755}{139831}Da, mislim da jeste.|-Dajte mi sa pogledam.
{139834}{139880}Naravno.|-Hajdemo pod svetlo.
{140180}{140219}Izvolite.
{140222}{140273}Imate li i traku?|-Da.
{140318}{140362}Da, 16 mm.
{140524}{140563}Zaöto ga guûvate?
{140775}{140832}Zaöto ste to uËinili?
{140854}{140898}Dûek Êe vas ubiti.
{141009}{141073}Boûe, ne!
{141306}{141365}Ako pisneö, mrtva si.
{141443}{141576}Vatromet Êe sve priguöiti
{143194}{143243}Dûek, molim te!
{143459}{143516}Dûek, molim te!
{143519}{143553}Ne!
{143632}{143695}Dûek. UpomoÊ!
{148100}{148152}Halo, Dûek. Da li me Ëujeö?
{148155}{148272}Kad se ovo zavröi moûemo u Njujork.|Moûemo da odemo u pozoriöte.
{148275}{148350}Znaö, kao äugar Bejbi. A znam|i dobar hotel na Tajm Skveru.
{148353}{148467}Serijski ubica zadavio je|joö dve mlade ûene.
{148470}{148557}Tragedija se zavröila kad je|poslednja ûrtva, Sali Badina
{148560}{148661}ubila napadaËa u krvavoj borbi|na vrhu zgrade Port Of History
{148664}{148729}tokom vatrometa povodom|proslave Dana osloboenja.
{148732}{148822}Identitet davitelja|joö nije poznat.
{148825}{148934}Smrt guvernera Mekrajana|nastavlja da öokira...
{148979}{149019}Dûek!
{149022}{149133}O, Boûe! Molim te!
{149302}{149366}Dûek, molim te!
{149382}{149465}O, Boûe, Dûek!
{149559}{149595}To se zove vrisak.
{149598}{149652}Joö! Joö!
{149655}{149714}Glasnije! Glasnije!
{149717}{149828}BiÊe glasnije.|-FantastiËno.
{149831}{149940}äta misliö o ostatku?|-Pa, dobro. Na poËetku...
{150003}{150052}Da, dobar vrisak.
{150059}{150103}Dobar vrisak.
{150112}{150151}Dobar vrisak.
{150555}{150755}prevod by éILE
{150780}{152280}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/4zteu|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
