{0}{300}{y:i}sa engleskog preveo i obradio|Gaca62
{325}{475}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{4489}{4515}{Y:i}Bime!
{5415}{5503}äto me tako gledaö?|Brzo Êu se vratiti.
{5762}{5849}Na mesto, Lado!|Na mesto.
{5905}{5992}O, Ivane IvanoviËu!|Uite! Uite!
{6034}{6157}Izvinite, negde ste poöli?|-Moûe da saËeka, nije bitno.
{6167}{6240}Dobar dan.|-Dobar dan. Izvolite.
{6244}{6269}Hvala.
{6286}{6356}Uite i izaberite.|Svi su na broju.
{6460}{6545}Lado... öta ti je, Lado?|Dobar pas.
{6556}{6623}NeÊu ti niöta. Nemoj da|se ljutiö.
{6652}{6729}Lado, pazi kako se|ponaöaö.
{6747}{6810}Povukli su i na oca i na|majku. -»ista rasa!
{6814}{6894}Da... -Ni jednom nisam uspeo|da naem neku manu.
{6902}{6927}Sjajni su.
{6956}{7014}Lado! Pazi!
{7021}{7148}Zna zaöto sam doöao, zato|je nervozna. Lado!
{7204}{7229}Budi mirna.
{7264}{7304}Fuj to! Fuj!
{7344}{7380}MoraÊu da je izvedem|odavde.
{7414}{7524}Hajde, idemo, kad ne umeö|lepo da se ponaöaö.
{7567}{7634}Prestani! Kako te nije|sramota?
{7638}{7713}Vi ne morate da ûurite,|sad Êu da je veûem.
{7769}{7804}Doi kod mene.
{7857}{7933}Vi rekoste da ih je|sedam okotila?
{7937}{8037}Tako je. 3 sam veÊ dao a|4 su mi ostala.
{8041}{8087}A... tako.
{8092}{8164}Lado,  nemoj!|Fuj to!
{8333}{8361}Dolazim odmah!
{8391}{8517}Tako je, Lado. Smiri se.|Popij malo mleka.
{8539}{8566}Smiri se.
{8678}{8703}Izvukao se.
{8874}{8971}Trebao sam odmah da ga udavim.|OËigledno da je s greökom.
{8995}{9035}Prokleti albino.
{9084}{9130}I odakle on ispade?
{9145}{9248}Ponekad se okoti neki ûuti, ali ovo|se deöava jednom u 100 godina.
{9252}{9294}Na sramotu svih|svojih predaka.
{9360}{9447}éena mi nije dala da ga udavim|a sad je prekasno.
{9471}{9528}MoraÊemo da ga se reöimo|kako znamo i umemo.
{9544}{9628}Ne govorite nikome jer Êe mu i|roditelji izaÊi na zao glas.
{9632}{9669}MoraÊu da ga uspavam.
{9689}{9776}A öta drugo mogu? Ako se proËuje|niko neÊe hteti kuËiÊe.
{9812}{9855}Ne mogu oËima da|ga vidim.
{9884}{9914}Gubi se.
{9938}{9999}Ja vam savetujem da|uzmete ovo.
{10010}{10074}Pogledajte mu samo|boju.
{10139}{10197}Uzmite bilo kog od ova Ëetiri.
{10202}{10261}Za godinu, dve donosiÊe|vam medalje.
{10265}{10296}Garantujem vam.
{10777}{10814}BimËe, ja sam.
{10929}{10965}Pogledaj ti ovo!
{11009}{11042}Ko je to uradio?
{11078}{11139}Ko je ovo napravio?
{11321}{11359}RazbojniËe jedan!
{11417}{11557}Sad moramo ovo da oËistimo, a je|ne mogu da se sagnem. Gde is ti?
{11591}{11617}Doi ovamo.
{11670}{11791}Gde si? Doi, doi ovamo.|Hajde da popriËamo.
{11808}{11875}Vidi... pogledaj sam...
{11893}{12033}Iskidao si 'Bibliju za vernike i|nevernike'. Ne diraj viöe knjige.
{12037}{12142}Ne diraj knjige!|Sluöaj me, Bime!
{12156}{12279}Knjige ne diraj inaËe Êeö|dobiti svoje. Jasno?
{12303}{12383}Sram da te bude!|Sramoto jedna!
{12413}{12464}Baö su te zainteresovala|ova pera.
{12506}{12616}To je jastuk a ne prepelica.
{12815}{12846}Doöao si da mi pomogneö?
{12908}{12985}Samo napred. Dobar si ti|momak. Hvala ti.
{13837}{13888}Nemoj! Ostavi to.
{13947}{13997}Interesujete moja biografija?
{15042}{15068}Zdravo.
{15135}{15269}Usamljen si? Sve ti Ëinim. Ko zna gde|bi sad bio da te nisam uzeo?
{15299}{15368}Dobro, smiri se malo.
{15382}{15442}Sluöaj öta sam pronaöao|kod Sabanejeva.
{15474}{15559}Sama Ëinjenica da|seteri potiËu...
{15563}{15669}od prastare rase lovaËkih pasa,|nije toliko nepoznata...
{15673}{15802}kao ona da seteri predstavljaju|najkulturniju i najinteligentniju rasu.
{15842}{15896}Tako je. Sluöaj dalje.
{15926}{16026}Crveni seteri su odgajeni u domu|moskovskog doktora Bersa.
{16054}{16163}On je ukrstio jednu keruöu sa|Carskim crnim seterom.
{16184}{16275}Kako su kuËiÊi izgledali i gde|su sve otiöli, ne znamo...
{16279}{16392}ali znamo da je jedan od njih|gajio grof Lav Tolstoj.
{16412}{16524}Razumeö, Bime, zato je jedno tvoje|uvo crno, to si povukao na 'cara'...
{16538}{16578}Dobro, neÊemo viöe|pominjati cara.
{16595}{16711}To znaËi da bi ti mogao biti potomak|psa najveÊeg svetskog pisca.
{16832}{16873}Hajde, spavaj.|Spavaj, spavaj!
{16979}{17009}Sve Êe biti u redu.
{17107}{17142}{Y:i}Sve Êe biti u redu..
{18474}{18502}Traûi, Bime!
{18542}{18580}äto si stao? Traûi!
{19487}{19616}Dobar si bio danas, Bime. Samo öto,|kad ptica poleti, treba da legneö,
{19620}{19709}a ti se sav uzbudiö i|zaneseö.
{19754}{19779}To ne smeö da radiö.
{19837}{19871}Mogao bi da|nastradaö.
{19905}{19993}NabaviÊemo mi tebi i|pedigre i medalje.
{20015}{20124}Ako ih ti ne dobijeö, ko Êe?|VideÊeö.
{20169}{20259}Ti si pas koji ima|neverovatan njuh.
{20335}{20378}Smetam li?|-Ne.
{20459}{20525}Sad ste mi sve|razjasnili.
{20542}{20640}»esto vas viam na|livadama.
{20650}{20750}Izgledate kao lovac,|ali nemate puöku.
{20780}{20849}ZnaËi, vi to sve zbog njega...
{20883}{20987}da bi ûiveo onako kako mu|je sudbina odredila.
{21037}{21118}Zamislite samo,|Ëim Ëuje pticu...
{21145}{21194}ukipi se kao mrtav.
{21203}{21228}Da.
{21245}{21310}Voleo bih da imam jednog|takvog, ali za ribu.
{21410}{21469}Sigurno je Ëistokrvan,|je l' da?
{21510}{21540}»istokrvan.
{21579}{21639}Ali sa njim nije sve u redu.|-äta mu fali?
{21672}{21759}Trebao bi da bude crn sa|crvenkastim öarama.
{21774}{21845}A on nije ni sliËan. Njegove|boje su atipiËne.
{21852}{21955}To je znak degeneracije. MoguÊe da|nam zbog toga ne daju papire,
{21959}{22013}i tako ga liöe svih|pseÊih prava.
{22091}{22186}Dakle, ako se rodiö kao svi ostali,|onda je to u redu...
{22215}{22322}a ako si drugaËiji,|to ne valja.
{22359}{22391}To nije u redu.
{22422}{22481}Bim i ja se slaûemo|sa vama.
{22524}{22634}A kako vaöe pecanje?|-Ma... pustite.
{22668}{22783}Pogledaö svu ovu lepotu...|i odmah ti je bolje.
{22912}{22998}Sve ima svoju svrhu i u svemu|moûemo da uûivamo.
{23066}{23161}Pogledajte njega, ima i noge,|i uöi i nos.
{23218}{23309}Imaö najbolji nos na svetu.|Svi Êe biti ljubomorni na tebe.
{23313}{23364}Samo nemoj da mi se|uobraziö.
{23380}{23483}Pa, odoh ja polako.|-Sve najbolje.
{23667}{23740}Ne valja biti sam. Uvek je|lepo popriËati sa nekim.
{25202}{25293}{Y:i}Ponekad mi se Ëini kao da|je sve ovo juËe bilo.
{25321}{25374}{Y:i}A ponekad mi se Ëini da|je bilo jako davno.
{25431}{25510}{Y:i}Nisam ni primetio kako nam je|prvo leto proletelo.
{25556}{25636}{Y:i}Bim je brzo nauËio sve moke|obaveze i navike.
{25683}{25751}{Y:i}Jedva smo Ëekali jesen.
{25779}{25831}{Y:i}I, konaËno je stiglo.
{26010}{26115}Poûurite, narode. Idemo.|Autobus polazi.
{26119}{26144}Izvolite.
{26290}{26374}Ne bojte se. Pas je miran.|Sedi.
{26399}{26483}Psima je zabranjen ulaz u|autobus. -Zaöto?
{26487}{26561}Takva su pravila...|izaite.
{26565}{26628}A zaöto im je zabranjen ulaz?|-Eto tako. Zabranjen je!
{26633}{26694}To si sad izmislio.|-Nisam.
{26698}{26767}NeÊu da vozim.|-Pola sata smo te Ëekali.
{26771}{26908}Spremite sitan novac za kartu.|I ne idemo nigde dok ne izaeö.
{27609}{27696}I öta sad ja da radim?|-Otkud znam?
{27776}{27806}PlatiÊu ti.
{28076}{28110}Upadaj, Êale.
{28176}{28206}A nemam prava!
{28931}{29044}Stanica Otradnoj! Idemo, narode!|Nemojte da zaboravite stvari.
{29095}{29135}Hvala vam na paûnji.
{29151}{29230}Znaö öta si ti, ucenjivaËu jedan?|-Izlazi napolje.
{29234}{29320}Ti si parazit. -Nemoj da ti pozovem|vojnu policiju. Imam piötaljku.
{29324}{29384}Samo  napred, duvaj!|Duvaj, duvnem ti ga!
{29409}{29477}Niste trebali da mu platite. Nije|imao prava da vas izbaci.
{29579}{29684}Momci, puno sreÊe.|-Do vienja.
{30533}{30566}Hajde malo da se|odmorimo.
{31320}{31401}Moûeö li da zamisliö,|ponudio sam mu mito?
{31488}{31570}Baö tebe briga.|A ja?
{31660}{31778}Uopöte nije bitno da li sam mu dao|rublju za malu, 20 za veliku...
{31782}{31816}ili 1000 za ogromnu|uslugu.
{31861}{31893}Svejedno, bruka je.
{31936}{32006}Kao da prodajeö svoju savest|deliÊ po deliÊ.
{32099}{32238}Bime, nisi ti u stanju da shvatiö da|su ovi papiriÊi i savest...
{32298}{32391}ponekad jako Ëvrsto|povezani.
{32651}{32687}Dobro veËe, TrofimiËu.
{32729}{32817}Ivane IvanoviËu!|Dobro veËe.
{32821}{32916}Baö sam se pitao ko je u ovo doba.|-Moûemo li da prenoÊimo kod vas?
{32920}{32982}Dobar Ëovek je kod mene|uvek dobro doöao.
{32990}{33028}Uzmite malo krompira.
{33051}{33168}Niste se baö proslavili. Ulovili|ste samo jednu ptiËicu?
{33177}{33265}Bim je isterao joö tri.|-äta? I vi ste promaöili?
{33330}{33377}Izgleda da sam ostario.
{33396}{33497}Mrzim da ubijam ptice. Ali ako|ne pucam, razmaziÊu psa.
{33526}{33563}Imate predivnog psa.
{33587}{33699}Nije standardne boje, pa se bojim|da neÊemo dobiti papire.
{33712}{33750}Sluöa li vas?
{33760}{33867}Sve sluöa. Teöko Êete naÊi|pametnijeg psa od njega.
{33877}{34006}Pogledajte ga kako se umiljava.|Vi ga hvalite a on se umiljava.
{34010}{34037}Na mesto!
{34077}{34195}Pretpostavljam da vam je sad ûivot|mnogo lepöi, od kad je sa vama.
{34199}{34243}U pravu ste, mnogo je lepöi.
{34268}{34330}Jedite, dragi moji,|samo se vi sluûite.
{34337}{34389}Kad smo kod ubijanja,|sasvim ste u pravu.
{34393}{34437}Previöe smo ûivotinja|poubijali.
{34470}{34546}SeÊate se one naredbe|da ubijamo svrake?
{34550}{34645}Rekoöe, ötetoËina. Kao i soko.|-Da, seÊam se.
{34650}{34761}A onda stiûe druga naredba, nisu|ötetoËine i lov je zabranjen.
{34765}{34855}A vukovi? -Skoro smo|ih istrebili.
{34881}{34967}Onda opet, ubijajte vrane,|zato öto pustoöe gnezda.
{34994}{35128}A niko ne zna koliko sam naöao ptica|zatrovanih otrovima koje mi bacamo.
{35144}{35246}Pokuöavaju da ubijaju insekte,|a umesto njih ubijaju ptice.
{35260}{35369}Ubijanje ptica znaËi ubijanje öume.|äuma ne moûe da ûivi bez ptica.
{35434}{35542}I ko je za to kriv? Najlaköe je|okriviti sivu vranu.
{35547}{35642}Sad kad su doterali cara do|duvara doneli su zakon...
{35646}{35765}i nekoliko razliËitih ukaza pa sad|ûivotinje mnogo laköe diöu.
{35792}{35919}Samo öto svaki Ëovek mora na sebe|da preuzme odgovornost.
{35923}{35953}Mora to da oseti.
{35978}{36066}Zato öto priroda znaËi ûivot,|i ûivot znaËi priroda.
{36079}{36128}Jedno bez drugoga|ne moûe da opstane.
{36148}{36229}I to treba svako da nauËi|joö u detinjstvu.
{36233}{36300}Bez obzira da li kasnije postane|ministar ili radnik.
{36348}{36465}Zaöto ne piöete o tom?|-PriËaö gluposti, stari.
{36469}{36506}Ne, u pravu je.
{36531}{36652}Samo öto o tome treba pisati na|vreme a ne naknadno.
{36658}{36754}Tako je. Lako je biti hrabar|posle bitke.
{36770}{36810}Jedite, dragi moji.
{36815}{36924}I papire bi trebalo da dobije po|zaslugama a ne po boji.
{36949}{37037}Niöta se ne brinite. Dobar pas uvek|pokaûe koliko vredi.
{37604}{37725}Bolje da kreneö, stigao ti je|mezimac. -Dolazim.
{37752}{37887}MladunËe jelena. Majka mu je|ubijena pa ga mi hranimo.
{37969}{38007}Dolazim, dolazim.
{38052}{38126}Evo. Doi sa mnom.
{38161}{38223}Doi ovamo. Hajde.
{38247}{38272}Evo.
{38321}{38348}Dobar momak.
{38427}{38481}Samo polako.
{38496}{38608}Uzmite, ovo je za vas. -Niste trebali,|Petrovna! Hvala vam.
{38612}{38651}U zdravlju da pojedete.
{38659}{38700}Do vienja.
{38704}{38795}Idemo, Bime. -Jedva Ëeka.|Hajde, trËi.
{40820}{40849}Kreni!
{41086}{41135}äta gledaö?|Niko nije savröen.
{41687}{41719}äta je bilo?
{41806}{41912}To je samo jeû, Bime!
{41918}{42053}Jako je koristan. Nemoj!|On je smrt za ötetne insekte.
{42084}{42207}NeÊeö ga uplaöiti. Hrabar je.|On se ne plaöi ni zmija. Idemo.
{42919}{43042}UËeni ljudi kaûu da ti sve vidiö|crno belo. Baö öteta.
{43104}{43206}Ali, niöta ne brini.|Kao prvo, moûda greöe.
{43223}{43325}A drugo, to znaËi da imaö svoje|sopstveno vienje stvari.
{43529}{43601}Danas nam je bio|sreÊan dan.
{45694}{45771}{Y:i}To su stvarno bili|sreÊni dan.
{45877}{45906}{Y:i}Doöla je i zima.
{45998}{46110}{Y:i}Spremili smo se za prvi ispit|i Ëekali smo leto.
{46532}{46632}{Y:i}Nismo znali da nas oËekuju|mnogo ozbiljnije provere...
{46654}{46728}{Y:i}od najobiËnijeg ispitivanja Bimovih|lovaËkih sposobnosti.
{46762}{46875}{Y:i}Nismo mogli ni da pretpostavimo koliko|Êemo neoËekivanih prijatelja i...
{46879}{46936}{Y:i}neprijatelja steÊi u|buduÊnosti.
{47022}{47084}Bime? Zdravo.
{47096}{47210}Zaöto sediö tu? Jesi li se izgubio?|Pokaûi mi, gde ti je kuÊa.
{47234}{47263}Hajde, pokaûi mi.
{47401}{47469}Dolazim. Misliö, ovde?
{47522}{47547}Idemo unutra.
{47718}{47743}Strpi se.
{47818}{47924}Gazda Êe ti otvoriti a ja|moram da idem.
{47935}{48029}Hajde, ui.|Zaöto ne ulaziö, Bime?
{48079}{48104}Dobar dan.
{48108}{48195}UËinilo mi se da se izgubio,|ali me je sam doveo ovamo.
{48199}{48269}Izvolite, uite. -Ne, hvala,|ne bih da smetam.
{48273}{48330}Uite, baö bi mi bilo|drago.
{48346}{48408}Ne oseÊam se dobro, zato|je morao sam da izae.
{48412}{48447}Zar se ne plaöite?
{48475}{48542}Bim se uvek brzo vrati.
{48558}{48656}Kad se proöeta, zagrebe mi na vrata|iako zna da su otvorena.
{48673}{48762}Poöto ne moûe da dohvati zvono,|ovako najavljuje svoj dolazak.
{48766}{48874}Zna da vrata sluûe da moûe|da se ue unutra.
{48878}{48922}Zna da treba samo da pita i da|Êe mu ih neko otvoriti.
{48938}{48975}Kamo sreÊe da je to tako.
{49010}{49101}A öta je sa vama?|Imate grip? -Ne.
{49137}{49225}Imam problema sa srcem...|Stare rane.
{49247}{49329}Stare rane mogu da se iskoriste,|ali su veoma neprijatne.
{49341}{49366}Tako je.
{49370}{49442}A gde vam je drugarica?|Vidim da sve radite sami.
{49520}{49614}Umrla je... pre tri godine.
{49656}{49721}Izvinite... nisam hteo...
{49758}{49783}äteta...
{49988}{50086}äta je sa njegovim papirima?|Da li ih je dobio?
{50099}{50161}ZnaÊemo sledeÊeg leta.|Tada je izloûba.
{52239}{52347}{Y:i}Molim vas za paûnju! Neka u|ring uu ökotski seteri.
{52351}{52437}{Y:i}Muûjaci najmlae|starosne grupe.
{52452}{52526}{Y:i}Molimo vas da|uete u ring.
{52552}{52605}{Y:i}Krenite u krug.
{52794}{52831}{Y:i}Drûite rastojanje.
{52899}{52958}{Y:i}Pratite broj ispred vas.
{53120}{53185}Moûete poËeti.|-Hvala.
{53497}{53535}Priite broju 5.
{53725}{53823}Kakvo je sad ovo Ëudo?|-Nikad niöta sliËno nisam videla.
{53827}{53922}Od Betsa i Lade. Ovde su|mu joö tri brata.
{53926}{53980}Neverovatno.|-Albino.
{53987}{54073}Prvi put ovo vidim.|-Mogao je bar da ga ofarba.
{54103}{54185}Neverovatno.|-On se öali sa nama.
{54246}{54341}Nije izabrao ni vreme, ni mesto|za svoje öale.
{54373}{54457}Ko je taj Ëovek? -Penzioner.|Joö od kraja rata.
{54469}{54568}Ozbiljan Ëovek. -Pisac.|Poneöto i objavi.
{54572}{54663}Svi penzioneri su pisci.|Pozovite ga za sto.
{54674}{54765}{Y:i}Molimo vlasnika psa broj öest|da doe do sudijskog stola.
{54784}{54897}{Y:i}Molimo vlasnika psa broj öest|da doe do sudijskog stola.
{54995}{55085}Sad Êe svi moji kuËiÊi biti|diskvalifikovani. -Sasvim je moguÊe.
{55089}{55220}Da su bar sudije iz naöeg grada, nego|je tu i neki profesor iz Moskve.
{55232}{55284}Onaj beli pas je|najlepöi od svih.
{55295}{55358}Moûete li nam reÊi koje je|rase vaö pas?
{55362}{55468}»istokrvni ökotski seter. Njegovi|roditelji su navedeni u prijavi.
{55472}{55541}Ali ni otac ni majka|mu nisu beli.
{55556}{55682}To je taËno, ali... -Nemamo|pravo da ga ocenjujemo.
{55715}{55745}Sklonite ovo.
{55749}{55886}Ali... on ima izvanredne|lovaËke sposobnosti.
{55890}{55956}Verovatno... ali ja vaöeg psa|izbacujem iz takmiËenja...
{55960}{56046}zato öto njegova boja ne odgovara|standardnoj boji njegove rase.
{56051}{56142}Znate. Lav Tolstoj je|imao setera...
{56146}{56254}od crvenog oca i crna majke,|a on je ipak...
{56258}{56355}Tako svako moûe da prati|predake svog psa...
{56359}{56419}sve do psa velikog pisca.
{56447}{56509}A time pokuöavate i sami da|se uzdignte na Tolstojev nivo.
{56564}{56653}U pravu ste. Imamo previöa|Tolstoja.
{56703}{56751}Pojavljuju se u buljucima.
{56897}{56936}äta to znaËi?
{56993}{57124}Uklonite uljeza iz ringa.|-U redu, Bime. Idemo.
{57128}{57180}{Y:i}Molimo sva neovlaöÊena|lica da napuste ring.
{57184}{57209}Idemo.
{57234}{57297}Ivane IvanoviËu, ne shvatajte|ovo liËno.
{57333}{57473}{Y:i}Bim je udaljen sa takmiËenja jer|ne odgovara standardima svoje rase.
{57491}{57577}Vaöa torba. -Zaöto ste ga doveli?|äta sam vam ja rekao?
{57585}{57660}Ipak je on ovde najlepöi pas.|-äta ti znaö?
{57664}{57699}Da li biste mi ga prodali?
{57759}{57794}Prodajte mi psa.
{58081}{58222}U tvoje zdravlje. Poneo si se Ëasno|i principijelno. Polako!
{58353}{58471}éivot teËe dalje. TI si dobar pas.|Takve pse svi vole.
{58481}{58551}»ak iako nemaju ni pedigre,|ni medalje.
{58611}{58722}Vidi! TrËe kao besomuËni.|Gde god se okreneö, dûukela.
{58737}{58873}Do skora stanari nikad ne bi|dozvolili ovaj zulum.
{58912}{58992}Samo öire zarazu. I jedu hranu|koje ionako nema dovoljno.
{59005}{59064}Ko?|-Ko? Psi!
{59112}{59177}Dobar dan.|-Dobar dan.
{59222}{59247}Klipan.
{59287}{59405}Svaki dan dolazi kod nje.|-Verovatno se vole.
{59429}{59546}Ljubav! U jednosobnom stanu?|Paz' da nije!
{59582}{59710}Ranije, dok smo ûiveli po zajedniËkim|stanovima, niko nije ni pomiöljao na to.
{59723}{59788}I od njih ima koristi.|-Od koga?
{59812}{59849}Kako od koga? Od pasa.
{59866}{59953}Otkud vam ta ideja? Samo gledajte|öta se deöava.
{59957}{60052}Vide li roditelji öta im deca rade?|Na njihovom mestu, odavno bih se ûalila.
{60062}{60160}Kako to mislite, koriste?|Pogledajte mu gazdu.
{60183}{60316}Dopuöta mu da trËi bez uzice, da plaöi|decu. Mogao ni neko da ujede.
{60327}{60419}Ko? -äta ko?|PriËam o ovom psu.
{60433}{60492}Niöta ne razumete.|-Samo sam...
{60546}{60606}Ujeo me! Ujeo me je!
{60614}{60732}Pobogu öta se ovde deöava?|Dobri ljudi, vi ste mi svedoci.
{60736}{60829}Ne, neÊe ovo tek tako proi.|Ljudoûderu jedan! Pavele TitiËu!
{60852}{60915}Jeste li videli, Pavele TitiËu,|öta mi je uradio?
{60922}{60994}Znala sam da Êe se to|kad-tad desiti!
{60998}{61099}äta si znala? äta se dereö?|-Ujeo me je, parazit jedan!
{61161}{61186}Hej!
{61317}{61371}Bime, öta je bilo?
{61440}{61469}Ko te poplaöio?
{61511}{61595}Sad idemo u redakciju, a sutra|poËinje sezona lova.
{61900}{61946}Izvolite, uite,|nije zakljuËano.
{61985}{62046}Dobar dan.|-Dobar dan.
{62061}{62119}U lov?|-Da, u lov.
{62128}{62232}Na lisice? -Ne, mi nemamo|niöta sa lisicama.
{62247}{62294}MoraÊete malo da saËekate|sa lovom.
{62383}{62429}Ako smem da pitam, zaöto?
{62462}{62568}Sezona je poËela. -PoËela, poËela,|ali ograniËena.
{62582}{62628}No, da preemo na stvar.
{62669}{62694}Sedite.
{62864}{62994}Vi imate psa, a ja imam ûalbu|na vaöeg psa.
{63157}{63184}Ovo su gluposti.
{63188}{63311}Niti je ikad ikog ujeo, niti Êe|ujesti. Bim je pametan pas.
{63346}{63476}Pametan! Jednom prilikom zamalo|me nije oborio sa nogu.
{63484}{63604}Ovo je Ëudno razmatranje ûalbe. Na koga|je uloûena ûalba, taj nek je i Ëita.
{63608}{63721}Moramo ovako. Pored toga, ûalba|nije na vas nego na psa.
{63743}{63833}Ne moûemo je dati psu da Ëita.|Pas mora da ode odavde.
{63850}{63979}Nemate Ëak ni saglasnost za drûanje psa.|Sve sam lepo proverio.
{63997}{64074}Trebalo bi da se naemo sa tuûiteljkom|i da raspravimo celu stvar.
{64078}{64114}Samo trenutak.|Samo malo.
{64159}{64244}Gde ste?|-Tu sam, gde bi' bila?
{64252}{64339}Doite. -Propade|nam lov.
{64355}{64421}Evo i nje.|-I sve Êu vam reÊi.
{64446}{64542}Ne postoji zakon kojim se psima|dozvoljava da napadaju ljude.
{64547}{64604}Svi su videli da|me je ujeo.
{64622}{64685}Ujeo vas je?|-Hteo je da me ujede.
{64707}{64764}Hteo?|-Za malo da me ujede.
{64789}{64868}Bime, gde si?|Doi ovamo.
{64934}{65003}Vrata su otvorena,|idi i zatvori ih.
{65156}{65188}I donesi mi papuËe.
{65280}{65305}Poûuri.
{65413}{65506}Dobro, sad mi donesi i drugu.|Donesi mi i drugu.
{65718}{65743}Hvala.
{65751}{65845}Ko bi rek'o? Baö pametna|kuca. Pametna!
{65860}{65895}Sedi na stolicu.
{65987}{66088}Doöli su nam gosti.|Pozdravi ih.
{66110}{66224}Zdravo! Levom. Leva je bliûa srcu.|-I vi. Priite bliûe.
{66229}{66296}Pruûite ruku, i recite, 'Daj öapu'.|-Je l' neÊe da me ujede?
{66300}{66383}Ne bojte se, neÊe.|Pozdravi se.
{66407}{66466}Daj öapu! Daj!|-Ne bojte se.
{66536}{66599}Bime? äta ti je?
{66648}{66725}Kako se to ponaöaö?|Odmah da si doöao.
{66811}{66846}Sad me je uvredio!
{66850}{66949}To vaöljivo kuËe me je uvredilo!|Mene, jednu uglednu ûenu!
{66953}{67004}Za srce me je ujeo!|-Dosta!
{67036}{67125}Nikad vas nije ujeo i ne ûeli|niöta da ima sa vama.
{67129}{67247}Ne viËite na mene! -Tiöina!|Baö ste mi vi ugledna ûena!
{67260}{67285}Idite!
{67294}{67378}Ja sad idem, ali ËuÊemo|se mi joö!
{67388}{67512}ZapamtiÊete sve öto ste mi rekli.|PokazaÊu ja vama!
{67575}{67686}Bili ste, priliËno grubi prema njoj.|-Sa njima se ne moûe drugaËije.
{67695}{67759}Kad bih ih ispustio iz ruku|u zgradi bi zavladala anarhija.
{67773}{67846}Ako joj se ne svia|to je njena stvar.
{67878}{67962}Ko je  moj najljuÊi neprijatelj?|-Ko?
{67966}{68082}Onaj koji niöta ne radi. Ko nas moûeö|niöta da ne radiö a dobro da jedeö.
{68102}{68146}Da, moguÊe je niöta|ne raditi.
{68153}{68246}Uzgred, a Ëime se vi|bavite? -Piöem.
{68277}{68417}To nije nikakav rad. Samo sedite, niöta|ne radite, a opet vas plaÊaju.
{68428}{68512}Da, ponekad.|éivim od penzije.
{68529}{68667}I ja sam penzioner. Ali radim kao|predsednik kuÊnog saveta. Za dûabe.
{68683}{68795}Celog ûivota sam bio na rukovodeÊim|mestima ali imam obiËnu penziju.
{68850}{68892}Ni pisati nije lako.
{68910}{69000}Pisati? Danas svako|moûe da piöe.
{69029}{69133}Da sam malo mlai, nauËio|bih ja vas pameti.
{69162}{69202}Dobro, to je to.
{69302}{69396}Ako piöeö istinu,|samo tako nastavi.
{69433}{69536}Za istinu ti moûda neko i plati,|ali je mnogo ËeöÊe...
{69551}{69592}da ti moraö za nju da platiö.
{69667}{69757}Ti, Bime, moûeö da ostaneö,|samo se sklanjaj od te ûene.
{71296}{71376}Skloni se! Idi kuÊi!
{71623}{71683}äta je bilo? ∆uti!
{71779}{71883}Ko to tamo radnom narodu|ne da da se odmori?
{71896}{72030}Ti to meni? Pogledaj malo!|Ova dûukela Êe opet da me ujede.
{72034}{72120}A gde si ti poöla?|HoÊeö da nam kaûeö svima?
{72133}{72271}Ja znam, znam gde Êeö! Ideö na pijacu|da prodajeö po tri put veÊim cenama.
{72275}{72365}Danas je nedelja, ljudi su|lepo raspoloûeni.
{72369}{72430}a ti im otimaö sve,|do poslednje kopejke.
{72434}{72522}A zaöto je ti toliko grdiö? Moûda je|krenula u razgledanje grada?
{72526}{72666}äta je sa vama? Zaöto me brukate|pred svima zbog ove dûukele?
{72678}{72786}I tebe Êu ja da prijavim!|-Kako vas nije sramota?
{72790}{72887}Mene kako nije sramota?|Vas treba da je sramota!
{72891}{72938}I tebe Êu da prijavim!
{72947}{73015}Samo ti piöi!|Knjiûevnice!
{73020}{73108}A ti, Bime, idi kuÊi! Jesam li ti rekao|da joj se sklanjaö s puta!
{73125}{73159}äta to radiö? Pusti me.
{73195}{73236}Samo se vi smejte!|Jako je smeöno!
{73245}{73348}Volela bih vas da vidim|kad vas ova zver ujede.
{73360}{73494}Vidi ih, nikad Ëoveka nisu videli|pa svi izmileli iz svojih rupa!
{73506}{73560}Samo polako!|NapaöÊe on i vas!
{73639}{73741}äta je sad? Idemo u lov.|Jesi li sreÊan?
{73774}{73854}Idemo, ili Êe opet neko da|nas zaustavi.
{74124}{74183}VeÊ dugo vas Ëekam.
{74197}{74299}Nije vas bilo iako je lovna|sezona poËela.- Da...
{74303}{74427}VeÊ sam mislio da niste dobili|papire i da su vam uzeli psa.
{74439}{74470}Ne, to nije moguÊe.
{74504}{74613}Papire nismo dobili, ali ne mogu|da nam zabrane da idemo u lov.
{74620}{74738}äta ti je? Niöta ne brini,|ni za öta te ne bih menjao.
{74742}{74815}Za prijateljstvo nam ne trebaju|nikakvi papiri.
{74819}{74899}Ko je to? Idi, vidi.|-Papiri niöta ne znaËe.
{75091}{75145}Kakva je ono prikaza?
{75312}{75402}To nije nikakva prikaza...|to je neki nesreÊnik.
{75423}{75458}Gde mu je gazda?
{75489}{75570}Nema gazdu...|Nekad je imao.
{75588}{75669}Svi psi lutalice su nekada|imali gazdu.
{75709}{75823}Ovo Ëupavo stvorenjce je ûivelo|u nekoj maloj drvenoj kuÊici.
{75837}{75904}Nije nikome smetalo i sluûilo|je koliko je moglo.
{75936}{75980}Onda su mu sruöili kuÊicu.
{75984}{76122}Vlasnici su dobili novi stan sa|parketom i izbacili su kuËe.
{76131}{76201}Je l' to istina ili ste|sve izmislili?
{76213}{76287}éivote je izmislio, a ne ja.
{76330}{76362}NastradaÊe.
{76389}{76506}NeÊe, uzeÊu ga ja.|Doi ovamo, doi.
{76510}{76542}Bime, doi.
{76556}{76652}»ekaj! Gde si poöao?|UhvatiÊu te ja.
{76720}{76784}»ekaj! äto si tako ljut?
{76858}{76946}Vi idite. Samo idite,|uhvatiÊu ja njega.
{76976}{77043}NeÊe poÊi sa vama.|-HoÊe!
{77047}{77089}Ne veruje viöe ljudima.
{77103}{77171}»ekaj, neÊu ti niöta.
{77237}{77262}Idemo, Bime.
{77982}{78031}Nije mi dobro, BimËe.
{78104}{78151}Loöe... jako mi je loöe.
{78208}{78290}ärapnel... örapnel se|pomerio.
{78310}{78350}Loöe mi je, BimËe.
{78406}{78453}Izvolite, izvolite.|-Ko je to?
{78457}{78490}Doktori su stigli.
{78516}{78593}Ne, Bime, smiri se.|-äta ti je, Bimuöka?
{78634}{78700}äta da radimo?|-Bime, doi ovamo.
{78734}{78828}Smiri se, to su dobri ljudi.|Ne plaöite se, doktorko.
{78870}{78920}Dajte mi ruku.|Ruku dajte.
{79032}{79058}Eto, vidite.
{79071}{79101}Baö neprijatno.
{79130}{79198}äta vas muËi?|-Srce.
{79246}{79376}Imam örapnel. Joö od rata.|-Kad ste poslednji put imali napad?
{79399}{79494}Nikad ovako... Nikad nisam imao|ovako jak.
{79498}{79557}RaskopËajte koöulju.
{79802}{79846}Morate u bolnicu.
{79874}{79957}Stepanovna! Gde je Bim?|-Ovde je.
{79985}{80023}Stani, smiri se, duöo.
{80068}{80126}Spremite se, poûurite.
{80134}{80197}BimËe, niöta ne brini.
{80239}{80264}»ekaj me.
{80312}{80424}Brzo Êu se vratiti. »ekaj me.|Jesi li razumeo?
{80649}{80744}Bime, ti ne moûeö sa njim.|Stani, kuda Êeö?
{80774}{80799}Na mesto.
{80960}{81054}Draga moja Stepanovna...|-Da, Ivane IvanoviËu?
{81058}{81123}HoÊete li da pripazite na Bima?|-Naravno.
{81127}{81232}Ujutru ga pustite da izae. Sam Êe|se vratiti. SaËekajte malo.
{81243}{81336}Sve Êe biti kako treba. -»ekaÊe me.|Rekao sam mu i ËekaÊe me.
{81340}{81410}U redu, ne brinite.|-Molim vas.
{81414}{81443}Ozdravite brzo.
{81447}{81525}Sve Êe biti u redu. Samo vi|nama brzo ozdravite.
{83395}{83500}Bime, donela sam ti malo kaöice.|Hajde, jedi.
{83579}{83674}Toliko ti nedostaje gazda?|Pa to je neverovatno.
{83702}{83774}HoÊeö moûda malo da|proöetaö?
{83811}{83855}Moûda naeö neöto|za jelo.
{83868}{83985}Pretpostavljam da voliö travu,|moûda iskopaö neöto iz ubreta.
{83989}{84023}Hajde, traûi.
{89149}{89238}äta Êeö ti ovde?|-Ostavi me na miru.
{89324}{89379}äta si mi se nalepio?|Skloni se!
{89718}{89766}äta Êeö ti ovde?
{89808}{89861}Hej! Vidi ti njega!
{89925}{90016}Jao! Skloni se! Beûi!|-Hvataj ga!
{90020}{90122}Petrove, oterajte ga ili Êe|öef da me ubije.
{90149}{90203}Dobro, dobro, skloni se|odatle.
{90215}{90318}Tako. Ovo ti je jedna ozbiljna|institucija. Bolnica, burazeru.
{90337}{90400}{y:i}Tim 3, hitan poziv.|-Gde si ti poöao?
{90483}{90522}Joö si ovde? Beûi!
{90564}{90589}Adresa?
{90617}{90650}Ulica Sadovaja 47.
{90825}{90862}HoÊeö li se, konaËno|skloniti?
{92701}{92748}Mrzim noÊna deûurstva.
{92752}{92817}Onda nai neki drugi|posao.
{92911}{93047}Joö nisi otiöao? To niöta|ne valja. Jesi li gladan?
{93062}{93130}Hajde, podeliÊemo ovo|öto imam. Jedi.
{93161}{93250}Baö mi neöto loöe izgledaö.|äta se desilo?
{93305}{93330}Reci mi.
{93541}{93566}Evo, jedi.
{93600}{93625}Jedi.
{93797}{93834}JadniËak mali.
{93879}{93910}»ekaö gazdu?
{93946}{94006}Ovo ti nije bolnica,|ovo je hitna pomoÊ.
{94055}{94093}Doi, pustiÊu te napolje.
{94280}{94419}Beûi kuÊi. Verovatno te|gazda veÊ Ëeka.
{94488}{94528}Tako je. Dobar momak.
{94620}{94645}Zdravo!
{94664}{94720}Ne laûem te, beûi kuÊi!
{95343}{95378}Dolazim, Bime!
{95419}{95500}Sad Êu da ti otvorim. Stigao si!|Dobra kuca.
{95531}{95612}Vratio se se kuÊi, maliöa.|Jesi li gladan?
{95639}{95737}Znala sam da Êeö naÊi neöto za jelo.|Svaka ti Ëast. A sad na spavanjac.
{95745}{95795}Ujutru Êu te pustiti napolje.|Spavaj.
{96679}{96710}Gde Êeö ti?
{96752}{96816}Dobro jutro.|-Dobro jutro.
{96885}{96915}äta je ovo?
{96929}{97054}Pas u medicinskoj ustanovi?|Odmah ga izbacite odavde.
{97058}{97118}Evo, odmah. Pomozite mi.|-Idi kuÊi.
{97122}{97184}Gubi se odavde!|-Nemoj da ga bijeö.
{97219}{97284}Baö ti je uspelo, je l' da?|-Moûda Êe tebe posluöati.
{97288}{97341}Pomeri se. äta kad bih|ja tebe...
{97376}{97421}Kako ne shvatate,|samo Ëeka svog gazdu.
{97429}{97524}Joö juËe sam ti rekao da ti gazda|nije ovde. Moraö da ga potraûiö.
{97529}{97595}Hajde sad! Idi!|KuÊi!
{97599}{97676}Idi, traûi gazdu. Dobar momak.|Zatvori kapiju.
{101164}{101241}»ekaö gazdu ili si se|izgubio?
{101325}{101395}Uzmi bombonicu, uzmi|baö je fina.
{101430}{101531}NeÊe. -Moûda Ëeka da|je odmotamo.
{101537}{101574}Sigurno nije gladan.
{101644}{101703}Baö lepo! Vidi ovo!
{101736}{101851}Psi na öetaliötu.|Je l' ovo tvoj rejon?
{101855}{101883}Da, vidim i sam.
{101887}{102014}Niöta ti ne vidiö. NeÊe Ëak ni bombonu.|Od njih ne moûe da se ûivi.
{102031}{102135}Onda nemoj da ûiviö. Pogledaj se,|sav si izgladneo, jadniËak moj.
{102145}{102245}Krenuli smo sa liËnim uvredama?|A öta je vama smeöno?
{102249}{102366}Uz duûno poötovanje, imam posla.|Pomeri se. Tebi kaûem, glavonja!
{102370}{102460}Opet me vreaö!? Svi ste Ëuli.|PozvaÊu miliciju.
{102472}{102537}Samo izvoli, hajde,|pozovi.
{102545}{102632}PokazaÊu vam ja.|-Mene Êe da plaöi milicijom!
{102636}{102693}Druûe!|-Da?
{102698}{102827}Samo ti Ëekaj. DoÊi Êe gazda.|-Nije ga ubedio.
{102841}{102894}Nataöa, öta to radiö?
{102898}{102934}Gde ti je tvoja milicija?|-Sad Êeö da vidiö.
{102938}{103026}Ne diraj ga! Moûda je|bolestan.
{103046}{103174}Kakav bezobrazluk. Pored svih ovih|gripova i infekcija... öta imamo?
{103178}{103312}Sa naöim pokoljenjima, tako reÊi naöom|buduÊnoöÊu, sedi ova öetajuÊa zaraza.
{103316}{103415}Nisu svi psi zarazni.|Pogledajte kako je ovaj lep.
{103422}{103509}Kakva varvarizam! Borim se, borim,|pokuöavam neöto da vas nauËim...
{103513}{103566}ali dûabe, kad ste neuki i|neobrazovani.
{103570}{103644}Jeste li baö sigurni?|-Ti si, bre zarazan.
{103663}{103748}Divalj je, jeste, divalj!|I mene je ujeo!
{103752}{103855}Krv mi je tekla! Mesec dana sam|bila nesposobna za rad.
{103859}{103930}Nema öanse! Gde vas je ujeo?|Pokaûite nam.
{103943}{104083}Deriöte jedno! Tome li te uËe na tom|tvom fakultetu, ötetoËino jedna,
{104087}{104186}da pred ovolikim ljudima tako razgovaraö|sa jednom uglednom ûenom.
{104190}{104235}Kuda ide ova zemlja?
{104239}{104313}Kamo sreÊe da moûete sami|sebe da vidite.
{104323}{104410}I ko vam je dao pravo da|me vreate? -Milicija!
{104414}{104443}Zovite... zovite |miliciju.
{104467}{104523}Dobar dan! Ko me je zvao?|-Drugarica.
{104527}{104643}äta vi gledate? »emu sluûite? Psi!|Psi se öetaju centrom grada. -Psi!
{104647}{104780}I divlji pitekantropusi! -Jeste li ga|Ëuli? Psuje. U zatvor s njim!
{104784}{104919}»ekaj. Zaöto me vreaö?|-Samo malo. Imate li svedoke?|
{105025}{105052}äta je bilo?
{105060}{105159}Ovaj student neÊe da ide u|milicijsku stanicu.
{105163}{105232}Ovo dvoje hoÊe,|ali on neÊe.
{105239}{105325}To ne moûe tako.|Ne sluöa miliciju.
{105335}{105431}Ako oni kaûu, ima da ide sa njima.|-Vodi ga u stanicu.
{105551}{105582}I öta Êemo mi sa tobom?
{105646}{105743}Koga Ëekaö? Gazdu?
{105752}{105825}Svi ti studenti su isti. Mi od usta|odvajamo za njihovo ökolovanje,
{105829}{105857}a oni nas vreaju.
{105887}{106026}A evo i njega. Mi o vuku...|Za sve je on kriv!
{106067}{106164}On je glavni krivac. Dobro je|öto ste ga doveli!
{106168}{106227}Sam je doöao. Pametnica.
{106231}{106352}Pametnica?! Kako moûete tako neöto|da kaûete za jednu ûivotinju?
{106356}{106444}On i ja smo sve videli.|Ovaj momak nije kriv.
{106448}{106567}äta? Ne mogu Ëak ni da vam ponovim|kako me je nazvao. I to zbog tog psa!
{106581}{106654}Taj pas je besan. Trebalo bi ga|otrovati. -Dosta!
{106658}{106711}Doöli smo ovamo da...
{106715}{106806}Tiöina inaËe Êu sve da vas|pohapsim. Recite, öta je bilo.
{106896}{106974}Lucija, jesi li videla|Bima? -Nisam.
{106993}{107056}Pobegao je.|-VratiÊe se.
{107063}{107147}IspriËali smo sve kako|je bilo, zar ne?
{107183}{107246}Izvolite. -Moûete da|idete.
{107287}{107362}Je l' moûemo i mi? -Hvala, kuco.|Hvala i vama.
{107366}{107439}On sve razume.|-A öta je sa nama?
{107443}{107485}Vi ostajete.
{107489}{107544}Poveûite me sa lovaËkim|savezom. -U redu.
{107561}{107641}äta je bilo, Crnouhi?|-Andreje LeonidoviËu.
{107680}{107784}Halo? Treba nam informacija o|jednom psu. Seter.
{107827}{107927}Broj? Samo da vidim.|124.
{107966}{108066}Kako... kako nemate? NemoguÊe.|Ovo je dobar pas.
{108095}{108209}Gde? U opötinu? Hvala.|Pozovi mi opötinu.
{108213}{108321}Nema on vlasnika. Taj pas|nije prijavljen.
{108401}{108492}Ako ovako laje na nas u milicijskoj|stanici... -Moûete da idete.
{108496}{108593}I to je sve? Kako mislite da odrûite red|kad ste sve konce ispustili iz ruku.
{108597}{108692}Veterinarski odsek. -Dovienja,|dedice. Potraûite mi broj 124.
{108696}{108787}Kakav dedica, mogu bre, otac da ti|budem. -Idite, odmorite se malo.
{108811}{108948}Seter sa uroenom manom?|Moûda ima manu.
{108974}{109022}Trunke poötovanja nemaju.
{109030}{109139}A kad dovedu nekoga ovakvog,|onda ga joö tapöu po ramenu.
{109164}{109241}Na kraju Êe dûukela, av i|sve da vas izujeda!
{109297}{109322}Ljudoûder!
{109344}{109433}Molim? Kako zaöto? Treba mi|vlasnikova adresa.
{109443}{109557}Zapiöite, Projeûja 41,|stan 19.
{109607}{109723}Pronaöli smo ti vlasnika. Odakle mi|je poznata ta adresa?
{109742}{109809}To je adresa one ujedene.|-»ija?
{109813}{109929}One ujedene. -Pitekantropusova.|To su neki stari raËuni..
{109939}{109985}Moûete li vi da ga odvedete?|-Naravno.
{110380}{110405}Samo malo, dolazim.
{110436}{110498}Nemoj da zvoniö,|ne zvoni, duöo.
{110502}{110632}Dobar dan. -Dobar dan. Gazda je u|bolnici a Bim je ostao da Ëuva stan.
{110636}{110694}Tako izlazi i vraÊa se.|Izvoli.
{110719}{110752}Izvolite, uite.
{110813}{110908}Ne, Bime. Nije se vratio.
{110968}{111013}Poznajete Ivana IvanoviËa?
{111017}{111115}Ne. Upoznala sam Bima i on me|je doveo ovamo.
{111133}{111196}Adresu sam dobila u policiji.|-Molim?
{111200}{111302}Mislila sam da se izgubio. Ali on je|samo traûio svog gazdu.
{111419}{111453}Niöta nije jeo?
{111457}{111552}Kod kuÊe nije. Moûda je|naöao neöto na ulici.
{111563}{111644}Nije. Mnogo mu nedostaje|gazda.
{111673}{111707}Ako nastavi ovako,|propaöÊe.
{111711}{111800}NeÊe. Suviöe je pametan pas|da bi tek tak propao.
{111833}{111902}Koliko ih ima koji lutaju ulicama.|Uvek nau neöto da pojedu.
{111955}{112078}Hajde, pojedi bar neöto.|Jedi, jedi!
{112089}{112149}Ne moûe to tako.|Hajde.
{112198}{112324}Jede! Mnogo pametan jedan pas!|TaËno oseti kad ga ljudi vole.
{112369}{112445}I ja Êu probati tako da ga|nagovorim, kao vi.
{112459}{112528}Njegov vlasnik je u gradu?|-Nije, prebaËen je u Moskvu.
{112689}{112752}Zaöto to radite?|-ObjasniÊu vam.
{112797}{112893}Ne puötajte Bima napolje dok|mu ne vratim ogrlicu.
{112897}{112932}VratiÊu je ujutru.
{113037}{113114}Ne brini se, Bime. VratiÊe|ti se gazda.
{113335}{113454}Zove se Bim. »eka svog gazdu i|ûivi sam u stanu.
{113458}{113497}Molim vas, nemojte da|ga povredite.
{113519}{113570}Vi ste baö jedna dobra|devojka.
{113590}{113688}A on je veran i pametan pas.|»ekajte.
{113730}{113755}Gde Êeö sad?
{113840}{113903}Pretpostavljam da je gazda|jako dobar Ëovek.
{113913}{113956}Tih i povuËen.
{114012}{114067}U ratu je bio teöko|ranjen.
{114083}{114162}Ovo mu je sin.|Nestao u planinama.
{114190}{114271}Pre Ëetiri godine.|A ovo mu je ûena.
{114275}{114313}Nije mogla da se pomiri sa|sinovljevom smrÊu.
{114433}{114470}Jeste li vi odavde?
{114495}{114598}Ne, studiram u Moskvi.|Ovde sam na praksi.
{114620}{114679}U ovom gradu su ûiveli neki|jako dobri pisci.
{114688}{114766}I Ivan IvanoviË stalno|neöto piöe.
{114772}{114892}Mogu li da pogledam? -äto da ne?|Pa nisu mu to pisma.
{114902}{114933}Gledajte koliko hoÊete.
{115079}{115121}Sve je o tebi, Bime.
{115257}{115308}Mnogo te voli.
{115421}{115514}Moram da krenem. Sutra putujem|za Moskvu. Zavröila sam praksu.
{115582}{115652}Da li znate u kojoj je|bolnici?
{115664}{115783}Ne znam, duöo. Ali, pretpostavljam da|se neöto desilo veÊ bi nam javili.
{115882}{115973}Ne brini, Bime. NaÊi Êu ti ja|u Moskvi gazdu.
{116021}{116096}ZnaËi, odlaziö?|-Da. Do vienja.
{116100}{116133}Do vienja, Daöenjka.
{116223}{116289}Pridrûite Bima da ne poe|za mnom.
{116293}{116400}Da, da, BimËe.|-Do vienja, Bime.
{116412}{116451}SaËekaj, stani.
{117647}{117774}Moraö da öutneö na gol.|Hajde, Tolja! äutiraj!
{117778}{117817}Promaöio si!
{117983}{118019}äta Êemo sad?
{118058}{118156}Moramo da mu je uzmemo.|ProbuöiÊe je. Uzmi mu!
{118212}{118253}Pogledajte! Donosi je.
{118357}{118382}Vidite?
{118426}{118462}Meni si doneo?
{118511}{118555}Daj mi je. Mogu li|da je uzmem?
{118623}{118648}»iji si ti?
{118775}{118817}Zdravo, Crnouhi.
{118834}{118901}Jeste li videli?|Dao mi je öapu.
{118931}{119044}Sigurno je dresiran. -Nego öta je!|Vidiö da ima i ogrlicu.
{119053}{119078}»itaj.
{119084}{119207}Zove se Bim. »eka svog gazdu i|ûivi sam u stanu.
{119216}{119322}Sigurno je gladan. Hajde da|mu naemo neöto za jelo.
{119326}{119403}Mi Êemo da mu donesemo.|-Poûurite!
{119473}{119568}Evo. Bolje da ste mu doneli|neku kobasicu.
{119578}{119714}Doneo bi mu ja ali mi je mama kod kuÊe.|Morao bih da veûbam sviranje.
{119719}{119764}Doneo sam paradajz.
{119768}{119846}On ne jede paradajz.|Probaj, Bime.
{119871}{119924}Zaöto neÊeö da jedeö?
{119934}{120064}Jedi! Pogledaj kako je lepa jabuka.|Tako ukusna i crvena.
{120068}{120136}Moûda Êe ipak malo paradajza?|-Ne, neÊe sigurno.
{120140}{120219}Moja mama kaûe da psi|öire zarazu.
{120229}{120358}äinteri hvataju one koji su zarazni,|ovaj ima ogrlicu. Pogledaj.
{120363}{120464}Uzeo je! Momci, jede!|Dobra kuca.
{120468}{120532}Jedi, Bime! Sve pojedi!
{120536}{120614}Zaöto si se do sad stideo?
{120618}{120643}»iji je ovo pas?
{120757}{120825}Dobro, Ëiji je to pas?|-NiËiji.
{120829}{120889}Moj. Sad je moj.
{120937}{120995}Dobro, recite mi, nije niËiji|ili je njegov?
{121022}{121130}Ima ploËicu na ogrlici.|-Da vidimo.
{121249}{121362}Nije lepo lagati, mladiÊu.|Po ploËici ovaj pas nije tvoj.
{121388}{121497}Kako te nije sramota? Jesu li te|roditelji uËili da laûeö?
{121525}{121555}Teöko meni!
{121712}{121781}Moram da odvedem psa|tamo gde mu je mesto.
{121803}{121829}äta to radite?
{121881}{121933}Ne dirajte tog psa!
{121937}{122025}Pusti ga. Moûda mu je vlasnik|neki alkoholiËar.
{122055}{122136}Onda Êemo napisati prijavu i|konfiskovati psa.
{122140}{122181}Zar ne verujete ovome|öto piöe?
{122196}{122271}Verujem, momËe. Naravno.
{122301}{122363}Ali, kao öto se ono kaûe,|veruj ali proveri.
{122401}{122448}Znate li vi öta je|to budnost?
{122513}{122545}Niöta vi ne znate.
{122575}{122600}Idemo!
{122622}{122649}Hajde!
{122690}{122715}Gde Êeö?
{122785}{122812}Hajde! Idemo!
{122872}{122975}Zaöto si mu rekao za ploËicu?|-Mislio sam da je dobar Ëovek.
{122979}{123007}Mislio? Ti si mislio!
{123012}{123108}Ti si prvi poËeo,|sad je moj...
{123114}{123201}Ionako bi ga odveo.|-éao mi psa.
{123205}{123333}Misliö da ga meni nije ûao.|-Tako ti je to sa odraslima!
{123406}{123431}äta je bilo?
{123462}{123507}Dosta! Idemo!
{123817}{123885}Zvala sam ga. Nije u|dvoriötu.
{123889}{123975}DoÊi Êe on. A ima i onu|ogrlicu sa ploËicom.
{124167}{124246}Opet si doveo jednog!?|Gospode Boûe!
{124254}{124285}Ne gunaj!
{124314}{124370}Ovo mi je petstota ploËica|u kolekciji.
{124392}{124417}Ima i tekst.
{124458}{124483}Evo, pogledaj.
{124541}{124569}Raritet!
{124585}{124676}Pusti ga. Zaöto si ga doveo ovamo,|mogao si i na ulici da mu skineö?
{124680}{124720}Neka deca su me pratila.
{124759}{124873}Nisam mogao da ga pustim. Mogli bi da|me prijave da su me videli.
{124908}{124951}Najbolje bi bilo da|ovde prenoÊi.
{124986}{125014}Idi u predsoblje!
{125115}{125140}Vidi ovo!
{125252}{125305}Samo ti spavaj, Lucija.|VratiÊe se Bim.
{125309}{125408}Uvek se vrati da prespava.|Samo ti spavaj.
{126153}{126197}äta je? äta ti je?
{126206}{126305}Pusti ga napolje. Svanulo je.|ProbudiÊe celu zgradu.
{126408}{126470}Pazi samo da te ne ujede!|Pazi!
{126595}{126681}Izlazi! Gubi se! Izlazi napolje|kad ti kaûem!
{126716}{126741}–avole jedan!
{126808}{126833}Pazi!
{126853}{126899}Izlazi napolje, ötetoËino jedna!
{127001}{127026}UjeöÊe te!
{127032}{127093}Jao!|-Sam si to traûio!
{127135}{127183}Rekla sam ti da|Êe te ujesti.
{130388}{130419}Pozdravite nam Moskvu!
{131349}{131398}Bime! Duöo!
{131486}{131535}Kuda? Ne moûete napolje!|-Idi kuÊi!
{131564}{131589}Idi kuÊi!
{131624}{131649}Idi kuÊi!
{133171}{133276}Otvorite na trenutak. -Ne mogu.|Ne smem. Stvarno ne mogu.
{133280}{133327}Otvori joj na trenutak.|-Zaöto se ti meöaö?
{134185}{134301}Kad je sledeÊa stanica? -Za oko|90 minuta. Ovo je brzi voz.
{134925}{134977}{Y:i}KRAJ PRVOG DELA
{135002}{136502}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/afc3x|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
