{0}{300}{y:i}prevod i obrada|Gaca62
{325}{475}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{4639}{4706}Pustite me, molim vas.|-Ne moûemo, gospoice Loel.
{4711}{4802}Gospodin Braun ûeli da ogledate celu|borbu, a tek je treÊa runda.
{4808}{4885}VratiÊu se, samo me|pustite da idem sama.
{4890}{4981}Gospodin Braun je veÊ besan,|izgubili smo vas na dva minuta.
{4986}{5048}ObeÊavam da neÊu beûati.
{5053}{5151}Gde mogu da odem?|-U redu. Pusti je.
{5651}{5711}Predomislila sam se.
{5729}{5801}NeÊu da gledam boks.
{5813}{5862}Gladna sam.
{5891}{5938}Pozovite mi taksi.
{5992}{6032}Pozovi taksi.
{6038}{6105}Ali, gospodin Braun ûeli... -Gospodin|Braun je rekao da joj ugaamo.
{6110}{6155}Pozovi taksi.
{7234}{7292}93. stanica, narednik Lids.
{7298}{7374}Sedi. Kapetan Piterson.|-Da, gospodine. Znam, gospodine.
{7379}{7430}PoruËnik?|-Na duûnosti, gospodine.
{7435}{7509}Da li je joö u kancelariji?|Znam! Znam!
{7620}{7702}∆ao, Lenarde! Dobro je, za promenu|videti te opuötenog.
{7708}{7804}Dobro veËe, kapetane.|Neöto hitno? -Hitno?
{7843}{7919}Kad imam neöto hitno|ja ostavim podreenima.
{7924}{8042}Imam tamo neke dobre cigare...|-Ne, hvala. Ostavio sam cigare.
{8048}{8178}I brendi! Moj doktor mi je zabranio sve|za öta vredi ûiveti... skoro sve.
{8232}{8272}Lenarde...|-Da, gospodine?
{8277}{8388}Mora prestati to tvoje rasipanje|novca naöih poreskih obveznika.
{8393}{8465}Ovu jabuku sam platio iz|sopstvenog dûepa, kapetane.
{8470}{8592}Lenarde, u poslednjih öest meseci|potroöio si 18.600 dolara,
{8597}{8683}baveÊi se jednim, jedinim|Ëovekom.
{8697}{8790}Braun nije Ëovek, on je|organizacija.
{8799}{8860}Potreban mi je novac da bih|se borio protiv novca.
{8865}{8995}Sluöaj, poruËniËe. LiËno nemam niöta|protiv tebe, Ëak ti se i divim.
{9004}{9091}Prepametan si, ali za to|nisi ti kriv.
{9099}{9254}Nego, öta Êemo sa ovih 18.600 dolara?|äta da kaûem komesaru?
{9266}{9396}Ja sam veÊ... izdiktirao objaönjenje|ako ûelite, moûete da ga iskoristite.
{9461}{9610}{Y:i}Memorandum za kapetana Pitersona o|troökovima 93. policijske stanice.
{9616}{9691}{Y:i}Kombinacija svakim danom|postaje sve jaËa,
{9696}{9773}{Y:i}i jedini naËin da se sruöi je|da se uhapsi njen voa.
{9779}{9852}{Y:i}Kad Graci napusti zemlju,|Braun...
{9888}{9969}äta ti misliö, öta je ovo,|istraga ubistva?
{9975}{10064}Imaö posla sa najveÊom koliËinom|prljavog novca na svetu.
{10069}{10159}Krenuo si kaöiËicom za Ëaj|da isuöiö moËvaru.
{10192}{10251}Kombinacija ne vodi knjige,|niöta ne beleûi.
{10256}{10336}Sve se zasniva na usmenoj reËi|i gomilama gotovine.
{10341}{10391}To im je jedina slabost.|-Koje?
{10397}{10443}Moraju da imaju blagajnika.
{10448}{10501}Pa?|-Ja znam njegovo ime...
{10506}{10601}ime Ëoveka koji podigne sluöalicu,|pozove »ikago ili Nju Orleans,
{10606}{10751}i kaûe, "Hej, Bile, Dûo Êe skoknuti|za vikend, daj mu 50.000."
{10756}{10871}Spusti sluöalicu i novac je veÊ|spreman. Novac od reketa!
{10877}{11010}I od toga, negde van granica grada|otvore novi bar sa kockarnicom.
{11016}{11103}U bar svrati gomila gimnazijalaca|da se malo provede.
{11109}{11214}Puni su k'o brod, raspiötolje se|i izgube i koöulje sa lea.
{11220}{11320}Onda nabave piötolj. Zabrinuti su,|ûele da nadoknade gubitak,
{11325}{11419}i tako radnik na benzinskoj pumpi|zavröi mrtav da metkom u dûigerici.
{11470}{11567}A ja gledam Ëetiri klinca kojima se|sudi za prvostepeno ubistvo.
{11573}{11603}Pogledajte ovo!
{11608}{11706}Prvostepeno ubistvo zato öto je dotiËni|gospodin Braun podigao sluöalicu.
{11711}{11778}Braunu ne moûeö niöta.|»ist je.
{11787}{11853}Nemaö nikakav dokaz. Nemaö Ëak ni|kaznu za nepropisno parkiranje...
{11859}{11921}Da, a zaöto je toliko oprezan?|To nije normalno.
{11926}{11996}Ne moûeö poroti reÊi da je neko kriv|zato öto je previöe nevin...
{12001}{12097}Nije niöta neviniji od ovog piötolja!|-Previöe sve primaö k srcu, Lenarde.
{12102}{12169}Nevin je dok se ne dokaûe|da je kriv.
{12192}{12236}Da, kapetane.
{12297}{12361}Joö neöto, kapetane?
{12405}{12438}Da.
{12444}{12480}Devojka.
{12490}{12531}Suzan Loel.
{12568}{12652}Pratiö je veÊ öest meseci.|Zaöto?
{12707}{12813}Zato öto je Braunova devojka.|Ona nam je najvredniji trag.
{12854}{12919}Mi ne znamo skoro niöta|o Braunu, ali...
{12924}{12991}ûena zna, trudi se|da sazna.
{12996}{13051}Ako uspem da je se doËepam i|nateram da progovori...
{13056}{13117}Lenarde, öest meseci si|bezuspeöno pokuöavao!
{13129}{13190}One ode u Vegas,|ti odeö u Vegas.
{13195}{13254}Ona odleti na Kubu,|ti odletiö na Kubu.
{13259}{13338}Nisi mogao da dobijeö troökove pa|si platio iz sopstvenog dûepa.
{13343}{13385}Morao sam jer me ne biste|podrûali.
{13391}{13464}Pa, nisam ja zaljubljen u nju,|Lenarde, nego ti!
{14002}{14099}Ovo je nezvaniËno, Lenarde.|Ostaje meu prijateljima.
{14146}{14205}Probaj da se suoËiö sa|Ëinjenicama.
{14279}{14368}Ne podnosiö pomisao da se ona|nalazi u zagrljaju onog oloöa.
{14377}{14416}Zaboravi je!
{14489}{14623}Pandur si, Lenarde. U knjigama postoji|17.000 zakona koje treba sprovoditi.
{14629}{14709}Nemeö ti vremena da prevaspitavaö|zabludele devojke.
{14733}{14816}Sa Braunom je veÊ|tri i po godine.
{14829}{14881}To je mnogo dana...
{14908}{14951}i noÊi.
{14974}{15019}SuoËi se sa tim, Lenarde.
{15102}{15147}Drago mi je öto se|slaûeö.
{15962}{16001}Samo nemojte da beûite.
{16006}{16121}Morali bismo da vas jurimo a gospodinu|Braunu to se ne bi dopalo.
{16143}{16185}Gospodine Odabon!
{16203}{16239}Suzan!
{16244}{16306}Drago mi je öto te vidim.
{16311}{16375}Kako ste? Godinama vas|nisam videla.
{16380}{16450}Izgledaö mi nekako drugaËije|Suzan. Ja...
{16455}{16555}Jedva sam te prepoznao.|-Sasvim sam ista, gospodine Odabon.
{16560}{16603}A kako je tvoja predivna|majka?
{16608}{16683}Negde je u Engleskoj,|izgubila sam joj trag.
{16688}{16826}Mislio sam da ste zajedno otiöle.|»uo sam da VladoviË svira Betovena.
{16847}{16933}Klavir me viöe ne interesuje kao|nekad, gospodine Odabon.
{16939}{17049}Sad si me razoËarala.|Ne sviraö viöe?
{17066}{17164}Sad se bavim samo pokerom,|gospodine Odabon.
{17245}{17357}HoÊete da pleöete sa mnom, gospodine|Odabon? -Svakako, Suzan.
{17375}{17475}Jesi li dobro?|-Naravno. Naravno!
{17827}{17906}Onog dana kad nas gospodin Braun|pusti na naöu damicu...
{17911}{17960}SrediÊu je liËno.
{18182}{18230}Gospodine Odabon...|-Suzan.
{18235}{18322}Progutala sam neke pilule,|mislim da umirem.
{18328}{18364}Suzan!
{18392}{18434}Pozovite hitnu pomoÊ.
{18441}{18485}Samo se skljokala.
{19154}{19202}Kako se sad oseÊaö, Beni?
{19208}{19237}Izgubljeno.
{19242}{19292}OseÊam se uûasno,|gospodine Braun.
{19297}{19363}Nastavi da se boriö, Beni.|Imaö petlju.
{19368}{19413}Izgubio sam i tri zuba.
{19418}{19510}Dobro, izgubio si. SledeÊi put Êeö|pobediti, pokazaÊu ti kako.
{19528}{19647}Pogledaj Dûoa MekKlura. Nekad je on|meni bio öef, sad sam ja njemu.
{19660}{19727}U Ëemu je razlika izmeu|nas dvojice?
{19742}{19820}Diöemo isti vazduh, spavamo|u istom hotelu.
{19839}{19887}Nekad je bio njegov!
{19917}{19962}Sad pripada meni.
{19977}{20044}Jedemo iste önicle,|pijemo isti burbon.
{20049}{20078}Pogledaj.
{20083}{20153}Isti manikir, ista dugmad|za manûetne.
{20161}{20266}Ali, postoji samo jedna razlika...|Ne izlazimo sa istim ûenskama.
{20273}{20304}Zaöto?
{20309}{20400}Zato öto ûene znaju razliku.|Imaju instinkt.
{20411}{20472}Prvi je prvi a drugi|je niko.
{20481}{20527}VeËeras je najbolji pobedio,|gospodine Braun.
{20532}{20574}Bio si bolji od Martineza.
{20580}{20678}Samo öto si to zaboravio. Uöao|si u ring i rukovao se sa njim.
{20683}{20787}éeliö i da mu budeö prijatelj i da|se boriö sa njim. Ne, Beni. Ne.
{20803}{20857}Gospodine Braun.|-Zatvori vrata!
{20930}{21023}Nego, Beni, ko upravlja ovim|svetom? Imaö li predstavu?
{21029}{21112}Ja ne, gospodine Braun.|-Tako je, ne ti.
{21120}{21162}Ali, zanimljivo je...
{21168}{21264}da se ne razlikuju puno od tebe.|Imali su neöto.
{21273}{21361}Imali su i iskoristili su to.|Ja imam, on nema.
{21383}{21469}äta je to, Beni? äta je to|öto pravi razliku?
{21533}{21569}Mrûnja.
{21582}{21684}Mrûnja je prava reË, Beni. Mrzi Ëoveka|koji pokuöava da te pobedi.
{21689}{21734}Ubij ga, Beni!|Ubij ga!
{21739}{21822}Mrzi ga dok ne pobesniö, i izaÊi|Êeö sa velikim parama.
{21842}{21908}I cure Êe te saletati.
{21951}{22045}MoraÊeö da iskljuËujeö telefon i da|zatvaraö vrata da bi mogao da spavaö.
{22136}{22187}Ustani, Beni.
{22389}{22457}Zaöto ste to uradili,|gospodine Braun?
{22470}{22571}Trebalo bi da mi uzvratiö.|U tebi nema mrûnje.
{22589}{22673}Pocepaj Benijev ugovor.|Ne treba mi viöe.
{22814}{22849}Gde je Suzan? U kolima?
{22854}{22905}Malo pre sam pokuöao da vam|kaûem, gospodine Braun.
{22911}{22987}äta da mi kaûeö?|-Da je u bolnici.
{23000}{23072}äta je bilo?|-Progutala je neke pilule.
{23118}{23215}Uzmi kola i dovezi ih otpozadi.|Usput mi kupi cigarete.
{24197}{24240}Gde je?
{24246}{24291}U bolnici.
{24325}{24372}Umire.
{24795}{24873}Prebacite je na zatvorsko|odeljenje.
{24900}{24983}Dobar dan, poruËniËe.|Ovo je gospodin Braun.
{25043}{25137}äta hoÊete, gospodine Braun?|-Dûo, reci mu da ûelim da ona izae.
{25142}{25189}Gospodin Braun ûeli da pustite|gospoicu Loel,
{25194}{25235}kako bi je prebacio u|privatnu bolnicu.
{25241}{25270}Da li joj je roak?|-Ne baö.
{25275}{25317}Muû?|-Samo dobar prijatelj.
{25322}{25410}Posete su utorkom i petkom.|Ne znam kuda ste uöli...
{25415}{25503}ali istim tim putem izaite napolje.|-Reci Ëoveku da se ne uzbuuje.
{25508}{25597}Gospodin Braun je razuman Ëovek,|ne poznajete ga.
{25609}{25645}Ma nemojte?
{25653}{25779}Ne poznajem ga, ali nameravam da vaöem|gospodinu Braunu zagorËam ûivot.
{25784}{25818}Ne biste smeli tako da govorite,|poruËniËe.
{25823}{25860}PrekoraËujete svoja ovlaöÊenja.
{25865}{25975}Dûo, Ëovek ima razloga da me mrzi.|Nedeljna plata mu je $96.50.
{25980}{26055}PotrËko u mom hotelu|zarauje viöe od njega.
{26061}{26131}Zar ne vidiö, Dûo da je|Ëovek pravedan?
{26136}{26199}LiËna oseÊanja kod njega|ne igraju igru.
{26208}{26286}Moja devojka umire u drûavnoj bolnici|i ja hoÊu da je izvedem odavde!
{26291}{26342}Uhapöena je, gospodine Braun.
{26347}{26386}A optuûba je?|-Ubistvo.
{26392}{26477}Gluposti, ne bi ubila ni muvu.|-Pokuöala je sebe da ubije.
{26484}{26558}Je l' to zloËin? -SluËajno se|kosi sa dva zakona,
{26563}{26637}Boûijim i ljudskim. Ja je teretim|po ovom drugom.
{26642}{26710}Reci Ëoveku, ako je izvede|pred sud, ja Êu...
{27119}{27158}Aliöa!
{27182}{27227}Aliöa...
{27301}{27343}Suzan.
{27352}{27430}Sklonite se od zatvorenice, gospodine|Braun. -Suzan, jesi li dobro?
{27435}{27508}Braune, ne mrdajte!|-Suzan!
{27680}{27716}Dûo...
{27743}{27839}reci Ëoveku da Êu ga slomiti tako brzo|da neÊe stiÊi ni da zine.
{27845}{27921}Reci mu da Êu ga sledeÊi put videti|u predvorju mog hotela...
{27926}{27996}da Êe plakati kao beba i moliti|10 dolara na zajam.
{28004}{28096}Reci mu to! I reci mu da ja|nikad ne gazim svoju reË.
{28117}{28237}Sigurno ste uradili neöto jako lepo kad|ste stigli tu gde ste, gospodine Braun.
{28243}{28343}PronaÊi Êu to, otvoriti ga|i seckati deo po deo.
{28348}{28421}Mrzim i samu pomisao na to|öta Êu tamo naÊi.
{28577}{28651}äta sam ti rekao, Dûo?|Pravedan Ëovek.
{28816}{28919}Gospoice Loel? Da li me Ëujete,|gospoice Loel?
{29132}{29175}Jeste li doktor?
{29180}{29256}Zovem se Dajmond,|detektiv sam.
{29295}{29344}Ostavite me na miru.
{29349}{29440}Moram da vam postavim par pitanja,|a vi morate da mi odgovorite.
{29445}{29546}Hladno mi je. Da li mogu da|ukljuËe grejanje?
{29560}{29606}Moûete li da nam donesete|vruÊu kafu, molim vas?
{29612}{29671}Ako ustanete i malo proöetate|biÊe vam mnogo bolje.
{29677}{29752}HoÊu da spavam, samo me|pustite da spavam.
{29793}{29865}Evo, popijte samo malo,|molim vas.
{29906}{30005}Veoma ste ljubazni.|Svi su ljubazni.
{30025}{30069}Ne zasluûujem to.
{30075}{30135}Hajde, popijte malo.
{30159}{30197}Tako je.
{30290}{30328}Dobro je.
{30364}{30428}Zaöto ste pokuöali da|se ubijete?
{30465}{30563}Ne znam zaöto. Ne seÊam se.|Pustite me da spavam, molim vas.
{30568}{30639}Da niste moûda ljubomorni? Da li je u|pitanju druga ûena? -Molim vas...
{30644}{30764}Jeste druga ûena, zar ne? Pomenuli|ste njeno ime, Aliöa, je l' tako?
{30824}{30901}äta je sa Aliöom? Da li se gospodin|Braun via sa Aliöom?
{30907}{31002}Ne! Ne znam. Ne znam|ni ko je ona.
{31007}{31073}Kako onda znate njeno ime?|-Ne znam...
{31078}{31164}Sigurno znate, uporno ste ga ponavljali.|Gde ste mogli da ga Ëujete?
{31169}{31213}Nisam Ëula...
{31238}{31280}Videla sam ga.
{31287}{31347}Gde ste ga videli?|Na nekom pismu?
{31352}{31395}U njegovom stanu.
{31447}{31516}Padala je kiöa...
{31563}{31644}i prozor je... bio zamagljen.
{31669}{31766}Po prozoru je prstom pisao|ime, ovako...
{31799}{31851}Zamagljeno staklo...
{31889}{31925}"Aliöa".
{31988}{32043}I kad me je video...
{32054}{32100}obrisao ga je.
{32109}{32194}Straöno mi je hladno.|-Gde je sad Aliöa?
{32217}{32292}Ne znam.|-Niste ga pitali?
{32303}{32363}Ne bi mi ni rekao.
{32446}{32485}äta je to?
{32490}{32559}Prolaze kamioni, joö malo|pa je jutro.
{32565}{32630}Da li se Braun iznervirao kad|ste ga pitali za Aliöu?
{32635}{32728}Ne znam ja niöta. Ne dirajte me!|Idite! Molim vas, idite!
{32733}{32775}Ako mislite da ste i dalje pametna i|poötovana devojka...
{32780}{32816}kao do pre Ëetiri godine,|niste!
{32821}{32914}Pokuöali ste samoubistvo, uhapöeni ste!|Moûda odete u zatvor na öest meseci.
{32919}{32983}Sestro! Molim malo vode!
{32989}{33061}Gospoice Loel, odgovorite mi na|joö jedno pitanje. -Ne!
{33066}{33130}Ko je Aliöa?|-Recite vi meni.
{33135}{33188}Ustanite!
{33230}{33329}U prizemlju je Ëovek sa nalogom|{y:i}habeus corpus{y}. -Kad pre?
{33334}{33378}MekKlur, öta da mu kaûem?
{33383}{33443}Znaö öta {y:i}habeus corpus{y}|znaËi, Seme?
{33448}{33487}Znam öta radi.
{33493}{33560}To je na latinskom, znaËi,|"moûete uzeti telo".
{33566}{33619}Gospodin Braun moûe|da je uzme.
{33743}{33779}Seme...
{33836}{33912}Moramo da otkrijemo|ko je Aliöa.
{33931}{34020}HoÊu da pokupiö svakog dripca|koji radi za Brauna.|
{34040}{34106}Pokupi i samog Brauna.
{35301}{35354}äta se deöava?|-On je lud!
{35361}{35429}Ko? -Dajmond!|Skroz je lud!
{35439}{35489}äta je ovo, MekKlure?
{35510}{35576}Kad su nas pokupili pomenuo|sam tvoje ime.
{35582}{35630}Znaö öta su rekli?
{35686}{35746}Prestani da se izmotavaö.|äta te pitao?
{35760}{35837}Pitao me za neko ûensko ime.|Uporno me samo to pitao.
{35842}{35911}Uporno je pitao za ime|te devojke.
{35932}{35992}Kao da nije normalan!|-Lud je.
{35998}{36035}Koje devojke?
{36054}{36134}Na vrh mi je jezika.|Ne znam...
{36157}{36270}Nekakva Alisa ili tako neöto...|Aliöa! Jeste, to je to! Aliöa.
{36279}{36327}I öta si mu rekao?
{36339}{36415}Baö ono öto znam...|niöta.
{36426}{36565}TaËno tako, Fanti. Ne znaö niöta,|baö niöta... ne zaboravi to.
{36821}{36882}Imam prava na jedan telefonski|razgovor.
{36906}{36971}Koga bi da zoveö?|-Gospodina Brauna.
{36976}{37080}Gospodin Braun je trenutno zauzet|Êaskanjem sa gospodinom Dajmondom.
{37127}{37200}Zakonski, uopöte ne moram da|se podvrgnem ovom testu.
{37205}{37285}Znam i cenimo vaöu saradnju,|gospodine Braun.
{37290}{37332}A ako odbijem?
{37339}{37423}Pa, ako odbijete, imam toliko|pitanja da vam postavim...
{37428}{37476}da biste mogli par dana da|ostanete u toj stolici.
{37482}{37545}Ovako, za nekoliko minuta|znamo da li laûete.
{37551}{37611}Nastavite. Dajte da|zavröimo sa ovim.
{37632}{37688}Da me ovako uhapsite zbog|nelegalne trgovine,
{37693}{37766}mogli ste bar neöto bolje da|smislite, poruËniËe.
{37777}{37889}I ja viöe volim osumnjiËene za ubistvo,|ali... danas nismo imali ni jedno.
{37907}{38006}Bilo bi mi drago da vam uËinim to|zadovoljstvo, poruËniËe.
{38064}{38178}GovoriÊu jednu po jednu reË, veÊina|od njih vam niöta neÊe znaËiti...
{38184}{38248}ali. ûelim da kaûete prvo öto|vam padne na pamet.
{38253}{38311}Recimo, ja kaûem, "slatko"...|-A ja kaûem, "öeÊer".
{38317}{38416}Ako ja kaûem, "policija"...|-Ja kaûem, "$96.50".
{38440}{38499}Jabuka.|-Kruöka.
{38504}{38546}Plavo.|-Okean.
{38552}{38583}Braon.
{38588}{38667}Za vas, gospodin Braun, samo me|prijatelji zovu "Braun".
{38751}{38821}Voda.|-Viski.
{38826}{38878}Piötolj.|-Dozvola.
{38890}{38942}äpageti.|-Betini.
{39001}{39065}äta? äta je to?|-Koje?
{39076}{39113}Betini.
{39131}{39194}Italijansko kafanËe na|severnoj strani.
{39206}{39297}Otkad to? Nikad Ëuo.|-Preskupo je to za vas.
{39306}{39367}Nastavi, Dûo.|-éene.
{39372}{39411}Skupo.
{39420}{39467}Sneg.|-Belo.
{39472}{39508}Aliöa.
{39589}{39684}Kako rekoste ime?|-éensko ime... Aliöa.
{39722}{39764}Ne.|-äta ne?
{39769}{39824}Rekao sam "ne", hoÊete|da ponovim?
{39829}{39867}Poznajete Aliöu, zar ne?
{39872}{39914}Naravno.|-Ko je Aliöa?
{39919}{39993}Dvogodiönja ûdrebica koja je|polomila nogu usred trke.
{39999}{40084}Izgubio sam 10.000.|-Laûete, gospodine Braun.
{40090}{40199}Kad ste Ëuli "Aliöa" srce vam je|poskoËilo, krvni pritisak ne laûe.
{40204}{40270}Znate öta to znaËi?|To znaËi da ste se poplaöili.
{40276}{40389}Gospodin Braun se nije uplaöio zbog|konja. Ko je ona i öta vam znaËi?
{40424}{40480}Ako je to zloËin,|zatvorite me!
{40524}{40583}Uhapsi me, niötarijo!
{40596}{40662}U redu, vodi ga odavde,|Seme.
{40680}{40727}U Êorku?
{40733}{40801}Ne, nazad na dno.
{40943}{41016}Gospodin Braun je jako|uticajan graanin.
{41021}{41137}Izbegao sam 14 komesarovih poziva,|15. put me je uhvatio.
{41163}{41220}Joö jedan poziv i|gotov sam.
{41296}{41344}Lenarde, öta si uradio?
{41349}{41419}Daj mi samo jedno normalno|objaönjenje, samo to traûim.
{41425}{41501}Pratio sam trag,|sledio sam logiku..
{41536}{41601}96 nezakonitih hapöenja.
{41619}{41722}Kako Êu to da objasnim? -MoraÊete|da objasnite samo 95...
{41748}{41849}Seme, öta da radim sa Lenardom?|Reci mi, öta da radim?
{41854}{41940}Samo mi daj joö 18.000 za|sluËaj Braun.
{41964}{42042}SluËaj Braun je gotov!|Kraj!
{42047}{42133}Gotovo, nema viöe!|SluËaj je zatvoren!
{42420}{42456}Hej, Seme...
{42471}{42566}Kako se zove onaj dripac kojeg|nismo uspeli da naemo?
{42577}{42626}Ralf Betini.
{42643}{42701}Koliko dugo nismo niöta|Ëuli o njemu?
{42707}{42772}Tu negde, sedam godina,|zaöto?
{42779}{42858}To je otprilike isto ono vreme kad|je Graci napustio zemlju...
{42863}{42966}a Braun preuzeo posao.|-Da, pa?
{42990}{43050}Pogledaj ovaj dijagram.
{43098}{43192}Pogledaj kako je skoËio|na pomen Betinija.
{43211}{43298}Betini je bio jedini nalog za hapöenje|koji nismo uspeli da izvröimo.
{43322}{43394}Nema ga veÊ godinama,|moûda je mrtav.
{43399}{43532}Ne, nije. Proverio sam.. mrtvaËnicu,|sva dosijea i niöta nisam naöao.
{43572}{43641}Zaöto ne ideö kuÊi?|Idi, odmori se malo.
{43653}{43724}Ne, moram prvo da obavim|jedan razgovor.
{43755}{43791}Lenarde...
{43816}{43869}Piterson je ozbiljno mislio.
{43889}{43970}Naljutio si ga, to znaËi da|je sa nama gotovo.
{43990}{44069}äta moûemo da izgubimo?|$96.50 nedeljno?
{45493}{45582}Stvarno imaö petlju!|-Zdravo, Rita.
{45594}{45679}äta si sad smislio?|Mada, mislim da znam.
{45696}{45811}Reko', moûda bismo mogli na ples.|-Do sad sam plesala, poruËniËe.
{45817}{45920}Pored toga, nije te bilo öest|meseci, a povrh svega...
{45925}{46003}ako ûeliö sastanak, onda se ponaöaj|kao i svi ostali, prvo me pozovi...
{46012}{46047}nedelju dana unapred.
{46052}{46092}Rita, vidi...
{46097}{46197}veËeras pravim zabavu, pa sam mislio,|moûda bi volela da doeö?
{46217}{46317}Zabavu?|Ko dolazi?
{46324}{46416}Samo ti i ja.|-Glupa ti je öala.
{46433}{46535}PoruËniËe... ili me uhapsite,|ili mi pustite ruku.
{46682}{46721}Lenarde.
{46776}{46812}Lenarde!
{47040}{47091}Vodi me na zabavu.
{47236}{47296}Ti si prelepa devojka,|Rita.
{47411}{47463}Ali si glupa!
{47469}{47548}Nikad mi niöta lepo nisi rekao|da odmah ne zabrljaö.
{47565}{47638}Zaöto traÊiö vreme se|jednim pandurom?
{47682}{47755}Mogao bi da mi naeö neku|lepu, bogatu propalicu.
{47760}{47837}Sa svojim vezama sigurno bi|mogao nekoga da mi preporuËiö.
{47842}{47940}äta imaju te propalice da|tako privlaËe ûene?
{47954}{48023}Propalice... detektivi...
{48037}{48111}éenu ne interesuje Ëime se|muökarac bavi...
{48134}{48192}samo kako vodi ljubav.
{48259}{48309}Ko je ona, Lenarde?
{48340}{48433}Glupa sam, Lenarde, za sve drugo,|osim za muökarce.
{48461}{48521}Muökarce... poznajem.
{48578}{48644}Dodaj mi cipele,|idem kuÊi.
{48762}{48813}Obuj mi ih.
{49135}{49275}Kad te ponovo povredi, duöo...|nemoj Ëekati öest meseci.
{49820}{49881}Da... uzela sam piÊe.
{49917}{50052}Ne gledaj me tako kao da sam|pijanica. -Ugasi tu muziku!
{50082}{50143}Meni se svia.|-Rekao sam, ugasi je.
{50239}{50309}Zbog Ëega smo danas|tako veseli?
{50339}{50412}Odakle ti ta garderoba?|-äta joj fali?
{50417}{50518}Viöe mi se sviaö u belom. Imaö hiljadu|belih haljina, zaöto ih ne nosiö?
{50523}{50574}Belo mi se viöe ne dopada.
{50580}{50625}éena se oblaËi za muökarca,|ti se oblaËiö za mene.
{50630}{50671}Idi, i presvuci se u belo!
{50689}{50726}NeÊu.
{50830}{50877}äta ti je?
{50882}{50932}äta sam ti sad uradila?
{50938}{51032}Pre nego öto sam uöao, sluöala si|ploËe, o Ëemu si razmiöljala?
{51048}{51126}Pokuöavala sam da se setim kako|sam se zaljubila u tebe.
{51147}{51201}Zar je to tako teöko?
{51215}{51318}DevojaËka prva ljubav zaborava nema,|bar bi tako trebalo da bude.
{51358}{51424}Moûda zato i ne mogu|da te ostavim.
{51433}{51493}Neki drugi put Êemo|priËati o ljubavi.
{51498}{51575}Da li znaö öta radim,|öta se deöava?
{51581}{51675}Ljudi mi svaöta priËaju,|ali ja ne sluöam.
{51726}{51799}Nisam te ranije pitao,|jer si bila bolesna...
{51834}{51886}öta ti je Dajmond rekao?
{51932}{52068}Dajmond! PoruËnik Dajmond!|Detektiv iz DevedesettreÊe?
{52073}{52168}Tri sata te je gnjavio u bolnici,|öta ti je rekao?
{52174}{52250}Uporno se raspitivao o devojci.|-Kojoj devojci?
{52266}{52335}Zove se Aliöa.|-Ko je to?|
{52341}{52389}Ne znam.
{52396}{52489}Bio je izuzetno uporan.|-Kako reËe da se zove?
{52510}{52549}Aliöa.
{52637}{52693}Niöta mi ne govori.
{52928}{52980}Suzan, reci mi,|molim te...
{52992}{53037}öta te muËi?
{53062}{53128}Mrzim te i prezirem te!
{53253}{53343}Suzan... öta pokuöavaö, da me|nateraö da poludim?
{53384}{53445}äta hoÊeö, Suzan?|Reci mi!
{53457}{53520}DaÊu ti sve öto ûeliö,|samo reci. -Niöta!
{53526}{53586}Baö sve.|-Niöta! Niöta...
{53923}{53993}PoruËniËe, imali ste poziv dok je|kapetan bio tu...
{53999}{54038}pa nisam hteo da vas|uznemiravam. -Ko?
{54043}{54162}Samo je rekla, "Rita". Rekla je da ûeli|da vas vidi i da znate gde je. -Hvala.
{54614}{54696}Dobro veËe, poruËniËe.|-Zdravo, ∆ale.
{54701}{54798}Ako traûite Ritu, u svojoj|garderobi je. -Hvala.
{54933}{55019}Zdravo, Rita. -Moram priznati da|nisi baö poûurio da doeö.
{55024}{55094}Molim te, imao sam gadan dan.|Nemoj joö i ti.
{55099}{55181}Imam neöto loöe da ti kaûem.|Namesti mi ovo, molim te.
{55186}{55219}Reci.
{55224}{55303}Samo ti teraj po svome,|hapsi pola grada.
{55308}{55410}Straöno su ljuti na tebe, samo öto|ne eksplodiraju. -Ma nemoj?
{55416}{55516}Ucenili si ti glavu, najbolje bi bio da|odeö na odmor. -äta si Ëula?
{55521}{55625}Svi priËaju, Ëula sam malo ovde,|malo tamo. äta Êeö da radiö?
{55630}{55692}Isto öto ve radim samo|joö ûeöÊe.
{55697}{55739}HoÊeö...
{55751}{55817}HoÊeö da ostaneö bez|glave, Lenarde?
{55822}{55902}Braun ne ubija da bi dobio ono|öto ûeli, kupuje.
{55908}{55980}Onda ti je bolje da se prodaö|ili da poËneö da beûiö.
{55985}{56089}Stvarno brineö za mene.|-Po malo.
{56094}{56133}Dovoljno.
{56165}{56213}Za mene je i to mnogo.
{56236}{56288}Ovo je moja muzika!
{56395}{56466}Lenarde! -Da?|-Kad Êemo se opet videti?
{56471}{56564}Pa, ako nisam mrtav, pronaÊi Êeö|me u zatvoru, kao i uvek.
{57289}{57352}Zaveûi! Vodimo ga odavde!
{57910}{57978}Kad Êe se osvestiti?|Za BoûiÊ?
{57984}{58060}Upucao me je roenim piötoljem,|ne mogu to da preûalim.
{58078}{58114}Fanti!
{58121}{58195}Daj da ga ja probudim.|-Ostavi ga na miru.
{58202}{58301}Gospodin Braun ne ûeli da ostavi|nikakve tragove krvi ili masnice.
{58306}{58360}Mogu li da dobijem|gospodina Brauna?
{58382}{58465}Daj ga meni, Fanti. Dva minuta|su mi sasvim dovoljna.
{58477}{58557}Zaöto? -Da mu postavim|jedno pitanje.
{58579}{58650}U redu, samo navali.|Tvoj je...
{58658}{58700}ali, prvo...
{58733}{58769}Pare.
{58786}{58857}Fanti, prijatelji smo. NeÊeö|pljaËkati prijatelja.
{58863}{58887}Pare.
{58893}{58989}Zar ti gospodin Braun nije platio?|-Ti nisi gospodin Braun.
{58998}{59128}Za gospodina Brauna bih budzaöto|oteo sudiju iz Vrhovnog Suda.
{59134}{59233}Isto vaûi i za Minga.|Je l' tako, Mingo? -Tako je.
{59279}{59336}Koliko?|-Stotku.
{59343}{59404}I za Minga.|-äta?
{59409}{59464}Po stotka... svakom.
{59578}{59614}Mingo!
{59715}{59757}Hvala, Fanti!
{59779}{59849}Sad ga pitaj öta god|hoÊeö.
{60252}{60316}Zaöto si me priveo?
{60416}{60501}Pitao sam te neöto!|Zaöto si me priveo?
{60554}{60622}Tebi se obraÊam, odgovori mi!
{60637}{60696}Zaöto si me priveo?
{60809}{60915}Evo ga ovde, gospodine Braun.|Malo sam ga omeköao za vas.
{60922}{61016}Dobro sam obavio posao.|-Rekao sam da ga ne dirate.
{61021}{61092}Nisam ga povredio, i dalje|je sve po zakonu.
{61097}{61196}Problem sa tobom MekKlure je öto nikad|nemaö vremena da nauËiö tehniku.
{61202}{61272}Fanti! Mingo! Donesite ovamo|taj radio.
{61430}{61473}UkljuËite ga.
{61620}{61678}Samo ûelim da ga pozajmim, Dûo.
{62010}{62092}PoruËniku Êemo prirediti jedan|mali koncert.
{62166}{62237}Moûe ovako? -Preglasno je,|ugasi.
{62318}{62378}»ujete li me, poruËniËe?
{62496}{62585}éelim da vam postavim samo jedno|pitanje pa moûete da idete.
{62609}{62692}äta traûite? Moûda mogu|da vam pomognem.
{62766}{62810}äta je sa Aliöom?
{62818}{62903}Kakvu informaciju imate?|Priveli ste sve moje prijatelje!
{62909}{62959}Laûni nalozi.
{62977}{63031}äta se krije iza toga?
{63182}{63225}Mingo, probaj ti.
{63445}{63511}Ne budite tvrdoglavi,|poruËniËe.
{63566}{63617}äta je sa Aliöom?
{63755}{63815}Zar vi ne znate odgovor?
{64035}{64103}Sad ide dobar prelaz,|klinac na bubnjevima...
{64108}{64153}Ludilo!
{64198}{64296}Volite li bubnjeve, poruËniËe?|Uûivajte.
{64949}{65013}Mislim da bi gospodinu Dajmondu|prijalo jedno piÊe.
{65046}{65094}Imate neki alkohol?
{65230}{65323}Moûe li razreivaË? -Ne, to bi|ga ubilo. Neöto drugo?
{65365}{65429}Neko Ëudo, 40% alkohola.|-Dobro.
{65489}{65554}Doi ovamo i drûi mu|glavu, Fanti.
{66459}{66506}Pusti ga.
{66550}{66593}Gurni ga napred.
{66887}{66977}Pogledaj pijanog pandura.|Kakva sramota!
{67280}{67316}Drûi ga.
{67835}{67910}Dajmonde, öta radiö ovde?
{67930}{68086}Vidi, vidi... Lenarde, pa ti si|pijan. »estitam.
{68109}{68145}Ui.
{68275}{68398}Grom ga ubio... da otme jednog od|mojih ljudi. Da ga napije, muËi!
{68407}{68492}Bio si u pravu, Lenarde. NeËega|su se uplaöili. -Aliöe.
{68498}{68539}Pa, to je samo poËetak.
{68555}{68603}MoraÊemo da se bacimo|na Brauna.
{68609}{68697}Ja bih da poËnemo privoenjem|Brauna i kompanije...
{68702}{68752}E pa, neÊe moÊi.|Nadmudrili su te.
{68757}{68804}Pogledaj se u ogledalu, na tebi|nema nikakvog traga.
{68809}{68903}Napio si se i doöao si ovamo sam.|Tako Êe da se brane.
{68908}{68995}I sve je Ëisto, Lenarde. Zato te|je Braun i isporuËio ovde.
{69001}{69092}Njegov glavni svedok sam ja,|Piterson. éao mi je, Lenarde.
{69117}{69190}Aliöa...|-Aliöa! Aliöa!
{69215}{69300}Ne znaju da li je konj,|brod ili cura.
{69312}{69393}äta joö imaö? -Isplivalo je|joö jedno ime, Betini.
{69399}{69475}Jesi li Ëuo nekad za njega?|-Da, gde se on uklapa?
{69480}{69577}Od 97 naloga on je bio jedini kog|nismo uspeli da naemo.
{69588}{69657}Isplivao je na Braunovom|detektoru laûi...
{69662}{69728}Sedi, Lenarde.|SeÊam ga se.
{69734}{69861}Bio je Gracijeva desna ruka, pre Brauna,|pre MekKlura iz moje generacije.
{69884}{69945}Povukao se kad je Graci morao|da napusti zemlju.
{69951}{69998}Mrtav?|-Ne, preplaöen.
{70003}{70069}Nije se uklapao u novu|Braunovu postavku.
{70088}{70141}Kao ni ostali iz starog|druötva.
{70147}{70222}Betini nije hteo da Ëeka|da bude ubijen.
{70229}{70318}Postao je poöten graanin. Promenio|je ime i nastavio da se krije.
{70323}{70364}Znaö li gde je?
{70370}{70420}Jednom sam mu uËinio|uslugu.
{70425}{70521}Mogao sam da ga uhapsim zbog neËega|öto nije uradio. Ali, nisam.
{70536}{70622}Zasluûio je, s obzirom za öta|je sve veÊ bio kriv...
{70627}{70705}ali nisam imao dokaze.|-Reci mi gde da ga naem.
{70711}{70783}PrepaöÊe se, Lenarde.|Previöe da bi progovorio.
{70788}{70861}Ako je toliko uplaöen,|onda Êe sluöati.
{71977}{72019}Napred.
{72173}{72210}Ne joö...
{72228}{72272}Samo minut...
{72284}{72345}To je sve öto traûim,|samo jedan minut.
{72361}{72421}Samo da iskljuËim öporet.
{72435}{72543}Mogao bi da izazove poûar a u zgradi ima|mnogo finog, starog sveta. U redu?
{72653}{72741}Dugo... dugo sam vas Ëekao.
{72758}{72850}Vi Ëak... delujete kao|fini mladiÊ.
{72888}{72960}Taj Braun, oËigledno zna|da izabere.
{72970}{73030}U vas nikad ne bih|posumnjao.
{73079}{73158}Mogu li da legnem...|biÊe laköe.
{73285}{73327}Priite bliûe.
{73357}{73418}Jedan metak biÊe sasvim|dovoljan.
{73430}{73497}NeÊete umreti, gospodine|Betini.
{73508}{73568}Nemam novac da vam ponudim.
{73575}{73635}Ali ja imam neöto vama da|ponudim.
{73641}{73727}Ne sprdajte se sa mnom, mladiÊu.|Zavröimo sa tim!
{73732}{73785}Nije me poslao gospodin Braun.
{73790}{73901}Zovem se Dajmond, poruËnik|Dajmond iz 93. stanice.
{73966}{74019}Ako mi pomognete...
{74039}{74106}mogu da vas oslobodim|vaöeg koömara.
{74141}{74184}Ne mogu.
{74239}{74338}Ja viöe ne mogu ni sebi da pomognem,|kako onda da pomognem vama?
{74350}{74423}Interesuje me jedno ime...|Aliöa.
{74444}{74523}Jeste li ga ikad Ëuli?|ZnaËi li vam neöto?
{74615}{74732}Aliöa je...|ûena gospodina Brauna.
{74737}{74821}Ko vam je to rekao?|-Ona mi je rekla.
{74854}{74908}Bila je dobra devojka.
{74942}{75003}Zdrava, odrasla na farmi.
{75045}{75148}Braun se oûenio dok je radio|kao zatvorski Ëuvar.
{75191}{75293}Dve godine kasnije propila se,|pila je kao smuk.
{75376}{75474}A onda je...|dozlogrdila Braunu.
{75499}{75553}I, stavio je taËku.
{75717}{75776}Samo polako, gospodine|Betini.
{75860}{75922}Bio je na Gracijevom brodu...
{75961}{76022}na tri dana od Portugala.
{76049}{76142}Aliöa je doöla pijana za sto.
{76154}{76221}Braun joj je rekao da ide|da odspava.
{76229}{76282}PoËela je da ga vrea.
{76294}{76371}Graciju je to bilo smeöno,|ali Braunu nije.
{76408}{76492}SeÊam se pogleda na|Braunovom licu...
{76511}{76555}kad ju je udario.
{76576}{76679}Ustala je od stola i skinula|svoju burmu.
{76684}{76811}Teöko je skinula, verovatno|joj se usekla u prst.
{76817}{76881}Skinula je burmu i bacila|je u okean.
{76933}{76971}A onda?
{77005}{77067}Onda je otiöla u kabinu...
{77119}{77215}Viöe je nikad nisam video.|-äta je bilo s njom?
{77314}{77360}Kako znate?
{77393}{77435}Znam Brauna.
{77440}{77512}I ja znam Brauna,|ali to nije dokaz.
{77549}{77674}Da... brod je imao sidro.|-Pa öta s tim?
{77713}{77782}Stali smo na Azorima...
{77791}{77867}a kapetan se iskrcao da|kupi novo.
{77912}{78051}Mislite da je ubio a onda vezao|za sidro i bacio u more?
{78063}{78132}Ne znam redosled...
{78139}{78216}ali, Ëim smo pristali ja sam|pobegao sa broda.
{78226}{78268}Ko je bio kapetan?
{78363}{78409}Neki äveanin.
{78415}{78459}Kako se zvao?
{78494}{78592}Nikad nisam priËao sa njim.|-Kako je izgledao?
{78608}{78694}Imao je uniformu!|U uniformi svi su isti!
{78808}{78877}To je jako bitno, gospodine|Betini.
{78883}{78973}Ako je upotrebljeno sidro,|kapetan to mora da zna.
{79013}{79106}Morao bi biti isplaÊen...|ili ubijen.
{79130}{79211}Pokuöajte... molim vas, pokuöajte|da se setite kako se zvao.
{79236}{79320}Odlazite! Ostavite|me na miru!
{79363}{79477}Sedam godina nisam ni sa kim|priËao, a sad ne prestajem.
{79508}{79579}MoraÊete da poete sa mnom,|gospodine Betini.
{79745}{79799}Hapsite me?
{79811}{79878}SledeÊi stranac koji ue ovamo...
{79887}{79943}neÊe biti policajac.
{79953}{80003}Sa nama Êete biti|bezbedniji.
{80087}{80158}Najbolje Êe biti...|da spakujete stvari.
{80182}{80237}Sve sam veÊ obukao.
{80340}{80384}Osim ovoga.
{80587}{80674}Kako to, tako fini momak|a policajac?
{80697}{80749}SluËajno, pretpostavljam.
{80920}{80993}Volite li antikvitete,|detektive?
{81008}{81060}Ko moûe sebi da uh priuöti?
{81114}{81220}Ako ste kapetan broda koji|plovi za Portugal...
{81286}{81347}i ako umete da Êutite...
{81394}{81463}onda moûete da kupite|mnogo antikviteta.
{81491}{81551}Moûda i celu radnju punu|antikviteta.
{81856}{81988}Da, ljubavi. To ti priËam poslednjih|pet minuta, ali ti ne sluöaö.
{81997}{82077}Pa, smiri se, moûemo da|promenimo naö plan.
{82516}{82577}Izvolite, gospodine?
{82584}{82639}Ja sam poruËnik Dajmond,|policija.
{82644}{82716}Dajmond! Skupo prezime.
{82741}{82799}NeÊu vas dugo zadrûavati,|gospodine Drajer...
{82804}{82844}samo bih vam postavio|nekoliko pitanja.
{82849}{82938}Izvolite. -Radi se o jednoj velikoj|nabavci koju ste obavili.
{82943}{83005}Da, ja uredno vodim knjige.
{83010}{83126}Zapisujem svaki dolar, svaki cent, crno|na belo... dok ne ode u crveno.
{83137}{83263}Ovu kupovinu ste obavili 1946.|-1946.!?
{83275}{83425}éao mi je, ali tada se nisam bavio ovim|poslom. Tako da vam ne mogu pomoÊi.
{83430}{83553}Nadao sam se da ste negde zabeleûili|kupovinu... jednog sidra.
{83571}{83620}Ne razumem.
{83629}{83724}1946. bili ste kapetan na|privatnom brodu,
{83731}{83813}koji je isplovio iz njujoröke luke|ka Lisabonu, Portugal,
{83818}{83924}Usput ste stali na Azorima da|kupite novo sidro. Zaöto?
{84059}{84120}Ne razumem...
{84138}{84192}Razmislite malo bolje.
{84198}{84264}Ne poznajete me, ja sam|izuzetno glup.
{84273}{84361}Brod je bila jahta za krstarenje u|Gracijevom vlasniötvu.
{84373}{84479}Sada pripada gospodinu Braunu.|Poznajete gospodina Brauna?
{84487}{84584}Proöle nedelje sam ruËao sa njim,|jako fini jedan gospodin.
{84590}{84630}On je vucibatina.
{84654}{84738}To öto sam ruËao sa njim|nije nikakav zloËin.
{84746}{84879}Ja ruËam sa svima. äirokih sam vidika.|RuËao bih Ëak i sa vama.
{84907}{85002}Ko je platio ovu radnju?|-Ja, Drajer.
{85007}{85104}Vi, Drajer, ste pozajmili pare od|Bolomak korporacije.
{85109}{85201}Bolomak korporacija je Braun,|ili Braun u Graci.
{85206}{85281}Gospodin Braun nikome ne daje|novac bez razloga.
{85313}{85422}Zaöto ste vi toliko vredni gospodinu|Braunu? »ime ste ga zaduûili?
{85432}{85526}Zovem se Nils Drajer, ûivim na|aveniji Mejson, 821.
{85531}{85582}To je sve öto moram da|vam kaûem.
{85598}{85654}Znate, gospodine Drajer,|stvari su se promenile...
{85659}{85697}od onog trenutka kad sam|kroËio ovamo.
{85702}{85802}Braun zna da sam ovde, da razgovaram|sa vama. -Niöta nisam rekao.
{85808}{85865}Da, ali Braun to ne zna.
{85934}{86049}U zamenu za informaciju, gospodine|Drajer, daÊu vam zaötitu.
{86055}{86133}I viöe od toga, staviÊu|vas u zatvor.
{86141}{86273}Recimo da me stavite u zatvor. »ovek|u susednoj Êeliji sluËajno ima piötolj.
{86281}{86411}Bum! Jedan mrtav äveanin. Mnogo|vam hvala, radije Êu ostati glup.
{86435}{86532}Kako ste uöli, gospodine,|radnja je zatvorena?
{86537}{86612}Izvinite, ali kasnim na|sastanak.
{86628}{86760}Gospodine Drajer, tajna za koju mislite|da vas ötiti, obiÊe vam se o glavu.
{86774}{86881}Imate posla sa...|bezobzirnim Ëovekom.
{86906}{86998}Gospodine Dajmond, 30 godina|sam bio moreplovac.
{87003}{87068}Na more sam se otisnuo sa 14.
{87081}{87192}Video sam oluje, video topovske|paljbe, video torpeda.
{87197}{87265}Bio sam potapan, ne jednom,|nego Ëetiri puta.
{87270}{87351}Preûiveo sam 37 dana na splavu,|samo na vodi.
{87360}{87405}Neuniötiv sam.
{87410}{87512}UmreÊu u Stokholmu, kao moj|pradeda u 93-oj godini.
{87517}{87629}Ne plaöim se nikoga, ukljuËujuÊi|i vas, zato... izaite.
{87752}{87809}Ako se predomislite,|gospodine Drajer,
{87814}{87903}samo pozovite 93. stanicu,|poslaÊu ljude po vas.
{88669}{88708}Halo?
{88720}{88756}Halo?
{88774}{88809}Halo?
{90243}{90285}Sedi, Dûo.
{90584}{90652}Rekao sam da ga dovedete ûivog,|öta se desilo?
{90665}{90727}Imao je piötolj.|Je l' tako, Fanti?
{90732}{90810}Jeste, imao je piötolj, gospodine Br...|-Rekao sam vam da ne nosite piötolje!
{90815}{90900}Ko je od vas preinaËio moju odluku?|-Ja nisam poneo svoj piötolj.
{90906}{90975}Mingo? -Nisam ja,|kunem se.
{91013}{91093}Uperio je piötolj u mene,|öta sam drugo mogao?
{91099}{91169}Sa mozgom koji funkcioniöe kao tvoj|niöta drugo mu nije ni preostalo.
{91174}{91250}Sluöajte me, vas dvojica.|Idite za svojim poslom.
{91255}{91326}Idite gde obiËno idete,|radite öta obiËno radite.
{91331}{91387}Ako vas neko neöto pita|ne odgovarajte.
{91392}{91441}A ti, penji se na sprat,|lezi i ne mrdaj.
{91446}{91504}Bolestan si, jasno?|Bolestan!
{91509}{91602}A ako te odvedu u policijsku stanicu|pucaj sebi u glavu.
{91607}{91654}Tako Êeö nam svima|olaköati stvar.
{91667}{91708}Gubite se odavde.
{91913}{91949}Dûo!
{91985}{92022}Doi ovamo.
{92181}{92233}Zaöto si to uradio, Dûo?
{92239}{92292}Rekao sam vam, potegao je|piötolj na mene.
{92310}{92364}Pokuöavam nepristrasno da|vodim posao.
{92369}{92480}Ubistvo je liËna stvar. Jednom kad|krene viöe se ne zaustavlja.
{92495}{92587}Mogao bih da shvatim da si neki|neiûivljen klinac, ali nisi.
{92592}{92650}Zreo si Ëovek, Dûo.
{92665}{92710}Zaöto si to uradio?
{92812}{92906}Izgled da postajem prestar da|bih nosio piötolj. -Da.
{92911}{92972}A moûda samo postajeö|prestar, Dûo.
{92986}{93041}Baö ti se ne sviam,|je l' da?
{93053}{93141}Misliö, kad je Graci otiöao da si ti|trebao da preuzmeö posao, a ne ja.
{93146}{93182}Je l' u tome stvar?
{93192}{93252}Ne... ovaj posao je|preteûak za mene.
{93257}{93333}Da... tako kaûeö ali|ne misliö tako.
{93371}{93418}Daj mi svoj piötolj, Dûo.
{93759}{93795}Hajde!
{93922}{93968}Vidiö öta sam mislio, Dûo?
{93973}{94038}Pre dve sekunde si imao|piötolj u ruci.
{94043}{94089}Bili smo sasvim sami.
{94095}{94199}Na trenutak si pomislio da pucaö...|ali, nisi mogao.
{94210}{94290}Ali, u Drajera si pucao bez|oklevanja, zaöto?
{94299}{94401}Zato öto je bio mali Ëovek, Dûo.|Mali Ëovek, kao ti.
{94419}{94540}Imaö lagan posao i dobru platu. Prestani|da razmiöljaö öta je moglo da bude.
{94552}{94660}I, ko zna... moûda doûiviö da|umreö u krevetu.
{94686}{94726}To je sve, Dûo.
{95450}{95514}Prazno je.|-NemoguÊe.
{95520}{95584}Da li je ovo neko otvarao od juËe?|-Gospoice Hartlebi?
{95589}{95632}NemoguÊe, gospodine.
{95643}{95681}äta si naöao?
{95739}{95821}{Y:i}Zabeleöka u dnevniku za|15.11.1946.
{95826}{95887}Drajerovo ûivotno osiguranje.
{95894}{95961}Gde bi bivöi moreplovac|Ëuvao svoj dnevnik?
{95966}{96097}Drajer je bio veoma pedantan Ëovek,|sve svoje knjige Ëuvao je u radnji.
{96105}{96147}U radnji...
{96342}{96475}Ako traûite dnevnik sa Gracijeve jahte|iz leta '46. naÊi Êete ga tamo.
{96762}{96864}Seme, pozovi tuûioca i traûi nalog|za Braunovo hapöenje.
{96869}{96932}Pod kojom optuûbom?|-Paljevina!
{96937}{97013}Imam sudski nalog koji je|jutros izdat.
{97018}{97129}Piöe da svi ugovori, svi papiri i sve|öto je u ovoj radnji, pripada meni.
{97134}{97179}Drajerovo je bilo 20%.
{97184}{97312}Bolemak korporaciji pripada ostatak, a|ja sam Bolemak korporacija. Niko drugi.
{97317}{97395}»ak ni Graci? -Otkupio|sam njegov deo.
{97401}{97529}Zaöto bi Bolemak korporacija spalila|taj brodski dnevnik? Zaöto?
{97534}{97639}Likvidacija imovine, koja nikako|ne moûe biti kriviËno delo.
{97688}{97785}»ekaÊu dok ne budem mogao|da vas optuûim za ubistvo.
{97793}{97843}»ije ubistvo, poruËniËe?
{97848}{97949}Moje, ako bude neophodno.|-Ne izazivajte previöe.
{97955}{98029}Moja duûnost je da|vas izazivam.
{98037}{98120}Dajmonde, jedini vaö problem je|öto biste voleli da ste ja.
{98125}{98213}Voleli biste da imate moju organizaciju,|moj uticaj, moj poloûaj.
{98218}{98272}Ali ne moûete, nemoguÊe je.
{98279}{98335}Mislite da je stvar u novcu,|ali nije.
{98341}{98442}Radi se o liËnosti... a vi to nemate,|poruËniËe, vi ste policajac.
{98448}{98529}Spor, temeljit, inteligentan...
{98546}{98636}gadne naravi i sa piötoljem|ispod miöke.
{98660}{98743}Plus, Ëeûnja za devojkom|koju ne moûete imati.
{98750}{98821}Prvi je prvi a drugi|je niko.
{98842}{98911}Tuûilac je izaöao, javio|mi se pomoÊnik.
{98949}{98996}Prekini vezu, Seme.
{100227}{100270}Gospoice Loel.
{100409}{100453}Odlazite, molim vas.
{100458}{100522}NeÊu dugo, gospoice Loel.
{100527}{100612}Zaöto ovde? Zar nije moglo|da saËeka? -Nije.
{100631}{100694}Onda... o Ëemu se radi,|molim vas?
{100699}{100789}Doöao sam da vas zamolim za uslugu.|-Da li vam dugujem uslugu?
{100818}{100889}éelim da ostavite gospodina|Brauna.
{100947}{101017}Zamolila sam vas da odete,|gospodine Dajmond.
{101032}{101146}Ako vi neÊete, onda Êu ja. -Mislite da|je ovo lasica, gospoice Loel?
{101151}{101285}Mislite da su ovo koûe malih ûivotinja,|saöivene da vam priËine zadovoljstvo?
{101296}{101348}Greöite.
{101362}{101463}Sklonite ruke sa... -Ovo su koûe|ljudskih biÊa, gospoice Loel.
{101469}{101557}Ljudi koji su prebijani,|prodavani, pljaËkani...
{101562}{101639}drogirani i ubijani od|gospodina Brauna,
{102009}{102082}Nisam doöao da vas povredim,|gospoice Loel.
{102087}{102162}Ne morate viöe nikad ni da me vidite|ni da priËate sa mnom, ali...
{102167}{102220}spasite sebe, ostavite ga.
{102255}{102294}Kako?
{102310}{102453}Treba samo da odöetate. -I to je|sve, gospodine Dajmond?
{102484}{102575}Dovoljno dugo ste me pratili|da znate da... ne mogu.
{102671}{102735}éivim u lavirintu, gospodine|Dajmond.
{102740}{102839}»udnom, bezizlaznom i|naopakom lavirintu.
{102845}{102967}I sve njegove male, uvrnute stazice...|vode nazad ka gospodinu Braunu.
{103015}{103075}Ne mogu to da prihvatim,|gospoice Loel.
{103080}{103141}Ni za milion godina.
{103249}{103334}Zaöto ûelite da mi promenite|ûivot, gospodine Dajmond?
{103412}{103479}Moj öef kaûe da sam|zaljubljen u vas.
{103562}{103661}A ja sebi uporno govorim...|da samo radim svoj posao.
{103694}{103760}Jeste li zato doöli da|me vidite?
{103797}{103833}Ne.
{103870}{103921}Doneo sam vam poklon.
{103926}{104009}Zadrûite ga ili spalite,|kako vam volja.
{104016}{104054}äta je to?
{104059}{104188}Fotografija Braunove ûene.|Zvala se Aliöa.
{104225}{104290}Mogli biste da ga pitate|öta joj se desilo.
{105484}{105540}Ko je?|-Suzan.
{105651}{105696}Tek je 10:30.
{105733}{105787}Koncerte je bio toliko|dosadan?
{105900}{105992}Sklanjaj ruke s mene!|-U redu.
{106036}{106136}Moramo da razgovaramo.|-Ne sad, kasnije. -Ne, sad!
{106148}{106209}Doi ovamo, hoÊu neöto da|ti pokaûem.
{106598}{106670}äta je sve ovo?|-Ovo je moja banka.
{106679}{106784}Mogao sam ovaj sef da izgradim u svom|stanu, ali bilo bi previöe oËigledno.
{106790}{106872}Ne primamo Ëekove, radimo|iskljuËivo sa gotovinom.
{106890}{106995}Pored ovolikog iskuöenja nikome|ne verjem, izuzev sebi.
{107044}{107084}I, moûda tebi.
{107114}{107158}Veruj mi.
{107163}{107220}Sa kim si bila na koncertu?
{107225}{107292}Ni sa kim. -Ni sa kim koji|se zove Dajmond.
{107297}{107369}Zaöto, onda pitaö?|Sve znaö.
{107383}{107501}Samo jednu stvar ti Fanti i Mingo|ne mogu reÊi, da li te joö volim.
{107506}{107599}äta ti je Dajmond rekao?|-Da je zaljubljen u mene.
{107729}{107839}Dajmond zaljubljen? NemoguÊe,|on je kao ova pametna maöina.
{107844}{107947}Ta maöina mi je dala Ëudan poklon.|-äta? Par lisica?
{108115}{108164}éelim da je upoznam.
{108179}{108250}éelim da upoznam vaöu ûenu,|gospodine Braun. -Ne moûeö.
{108255}{108326}Zaöto? Zato öto je mrtva?|-Nije, ûiva je.
{108334}{108399}éivi na Siciliji,|u Gracijevoj kuÊi.
{108404}{108481}Ovo je slikano pre mesec dana,|poslala je pismom.
{108487}{108569}Zaöto je tebi poslala?|-éeli da se vrati.
{108580}{108655}Zaöto si je ostavio?|-NeÊu da priËam o tome.
{108660}{108736}Ja hoÊu. -Zar moraö da mi|uniötiö sav ponos?
{108742}{108799}Ti si moj veÊ uniötio.
{108855}{108905}U redu, reÊi Êu ti.
{108915}{108963}Bio sam zaljubljen u nju.
{108973}{109022}Ja, zatvorski Ëuvar.
{109030}{109092}Zbog nje sam krenuo da|se probijam ka vrhu.
{109097}{109176}Imao sam samo petlju. Menjao|sam je za novac i uticaj.
{109182}{109244}Stekao sam poötovanje svih,|osim njeno.
{109249}{109314}Radila je sve öto je mogla samo|da bi me ponizila.
{109320}{109384}Stalno je bila pijana i|flertovala sa drugima
{109389}{109436}Pokuöao sam da je|dovedem u red.
{109441}{109521}Poveo sam je na krstarenje kad|je Graci morao na Siciliju.
{109526}{109626}Tri dana poöto smo pristali, nestala je.|Mesecima sam je traûio.
{109631}{109678}äta misliö, gde je bila?
{109683}{109743}éivela je u Gracijevoj kuÊi.
{109749}{109809}Bio je veÊi Ëovek od mene.
{109836}{109893}Sad znaö ko je Aliöa.
{110007}{110107}Dobro veËe, gospoice Rita.|äta ima, kako ste?
{110112}{110228}Usamljena sam, Frede. Usamljena, izmeu|dve predstave, imam pauzu do 12:00.
{110233}{110286}Gospodin Dajmond je izaöao,|hoÊete...
{110291}{110383}HoÊete da se popnete gore,|da ga saËekate? -Hvala.
{110393}{110499}Reci mi, öta obiËno radi|uveËe? -Radi.
{110514}{110668}UbiÊu ga! -Nemojte da ga ubijete.|PlaÊa kiriju u dan, nedostajaÊe mi.
{110673}{110719}I meni.
{111179}{111215}Da?
{111229}{111293}Ne! Ne, budan sam.
{111340}{111394}Kad to treba da se obavi?
{111428}{111473}Jasno.
{111647}{111717}Mingo!|-äta je bilo?
{111722}{111792}Gospodin Braun nam je dao|zadatak za veËeras.
{111798}{111834}Koga?
{111847}{111883}Dajmonda.
{112489}{112519}Otvoreno je.
{112524}{112594}Idemo?|-Idemo!
{113474}{113510}Lenarde?
{113522}{113577}Lenarde! -äta, Seme?|äta je?
{113583}{113677}äta god da razmiöljaö, zaboravi,|to je neÊe vratiti nazad.
{113721}{113766}Saks Peta Avenija.
{113808}{113882}Doöla je da me vidi u svojim|najboljim cipelama.
{113909}{113993}PozvaÊu Pitersona, baciÊe u vatru|sve raspoloûive ljude.
{113999}{114114}Pusti, Seme.|Rekao sam, pusti!
{114161}{114240}Ne moramo da proveravamo|ni metke, ni otiske prstiju.
{114246}{114355}Po celoj sobi je ispisano njegovo|ime... Braun! Braun!
{114380}{114491}éeleo je mene da ubije, umorio se|od Ëekanja. E pa, i ja sam.
{114496}{114552}äta Êeö da uradiö?|-Da zatvorim sluËaj.
{114557}{114645}Znam kako se oseÊaö. -Niko ne zna|öta druga osoba oseÊa.
{114650}{114700}Svejedno, sedi!
{115389}{115435}UËini mi uslugu...
{115440}{115489}ostavi piötolj.
{115591}{115667}Ponaöao sam se prema njoj|kao da je stvar.
{115708}{115793}Zvao sam je samo kad|bi mi zatrebala.
{115904}{115985}Ne krivi sebe, poludeÊeö.
{116475}{116582}ProËitala sam jutros u|novinama. éao mi je.
{116587}{116686}Straöno, straöno mi je ûao.|-Zaöto, öto nisam ja nastradao?
{116713}{116773}Kaûite öta ste doöli da|kaûete.
{116867}{116947}Ostavila sam gospodina Brauna.|-Malo ste zakasnili.
{116978}{117084}Braun je ubio devojku u vaöem|stanu. Njegovi ljudi.
{117089}{117137}Moûete li to da dokaûete?|-Ne, ja...
{117142}{117205}Moûete li da dokaûete da su|Fanti i Mingo to uradili?
{117210}{117288}Da im je on naredio?|-Ne.
{117316}{117354}Sedite.
{117455}{117508}Da li zna da ste otiöli?
{117520}{117556}SaznaÊe.
{117572}{117648}Otvorila sam njegov privatni|trezor. -Zaöto?
{117671}{117773}éelela sam da vam pomognem,|ako mogu. -äta drûi u trezoru?
{117779}{117860}Oruûje i novac.|-Nije zloËin imati novac.
{117865}{117919}Nije zloËin imati ni oruûje,|zloËin je upotrebiti ga.
{117924}{117977}Videla sam joö neöto?|-äta?
{117982}{118037}Neöto u vezi Aliöe.
{118059}{118138}Moûete li da dokaûete da|je ubijena? -Ne.
{118143}{118215}Mogu da dokaûem da|je ûiva.
{118239}{118294}äta priËate?
{118310}{118383}éivi na Siciliji, sa Gracijem.
{118398}{118449}NemoguÊe.
{118459}{118518}Ovo je poslala Braunu.
{118531}{118579}Stvarno je Aliöa.
{118584}{118668}Nekoliko godina starija nego|na onoj slici sa broda.
{118675}{118726}Onda je sigurno ûi...
{118777}{118854}Ovo nije slikano na Siciliji.
{118875}{118931}Zemlja je prekrivena snegom.
{119100}{119249}Da, jeste ista devojka.|-Promenila se od prethodne slike.
{119255}{119308}Moûe li da bude falsifikat?|-Ne, gospodine.
{119313}{119418}Ovo je snimljeno obiËnim öirokougaonim|objektivom. E sad, sudeÊi po polju...
{119423}{119489}Pusti sad to. Moûeö li da mi kaûeö|kad je ovo slikano?
{119494}{119542}Original je ötampan na|Varagan papiru...
{119548}{119638}A to znaËi... -Taj papir se na trûiötu|pojavio pre godinu i po dana.
{119643}{119673}Frenk!
{119679}{119759}Vidiö onu oznaku autoputa kroz ogradu?|Moûeö li da mi kaûeö öta piöe?
{119764}{119777}Da je identifikujeö?
{119782}{119881}Ne mogu, ali mogu da proverim|-Proveri, molim te.
{119886}{119960}Lenarde... -Da?|-Aliöa je ûiva.
{119966}{120095}Ako nema ubistva, nema ni sluËaja.|-Moûda imamo i jaËi sluËaj.
{120101}{120167}»uo sam se sa naöom prekomorskom|obaveötajnom sluûbom.
{120173}{120253}Godinama veÊ traûe Gracija i|ne mogu da ga nau.
{120258}{120321}Ne postoji nikakav dokaz da|je ikada stigao na Siciliju.
{120326}{120375}A öta je sa Betinijevom|priËom?
{120380}{120461}Betini je bio u pravu za ubistvo|koje se desilo na brodu.
{120467}{120548}Samo je pogreöno|identifikovao ûrtvu.
{120553}{120618}Stani malo...|Reci öta misliö.
{120627}{120724}Pa... sve vreme sam traûio|pogreöno ubistvo.
{120743}{120862}Braun nije ubio svoju ûenu!|Ubio je svog öefa, Gracija.
{120867}{120942}I zato naöi obaveötajci|ne mogu da ga pronau.
{120953}{121066}Graci je na dnu Atlantika|zavezan za sidro.
{121102}{121260}Prelepa teorija, Lenarde. Prelepa.|Osim jedne male zaËkoljice.
{121274}{121338}Ne moûeö da je dokaûeö,|nemaö svedoka.
{121343}{121404}Uspeo si, Frenk?|Daj da vidimo.
{121416}{121534}To je oznaka 225A na drûavnom|autoputu. -225A, znaö li gde je?
{121540}{121588}Mogu da je naem u roku|od dva sata.
{121593}{121695}To je öljunËani puteljak koji skreÊe|na zapad od obalskog autoputa.
{122442}{122581}Ne znam öto ste doöli kod mene, detektive.|Zovem se Ana Li Dûekson.
{122590}{122662}Sigurno nikad niste iöli na|krstarenje okeanom?
{122667}{122740}Da jesam, sigurno bih|zapamtila.
{122777}{122838}Baö umete sa cveÊem.
{122843}{122907}Hvala.|-Kako se ovo zove?
{122912}{122956}To su boûuri.
{122981}{123053}Predivni su, svi do jednog.|Kako vam to uspeva?
{123060}{123119}Morate da ih volite.
{123130}{123185}OseÊaju to.
{123216}{123276}O, Boûe!|-äta je to?
{123301}{123343}Gusenica.
{123364}{123408}Jede pupoljke.
{123433}{123536}A zaöto je niste ubili?|-Ne mogu niöta da ubijem.
{123548}{123617}»ak ni ovo cveÊe ne seËem.
{123631}{123739}Ako ljudi ûele da ga vide, moraju|da dou ovamo dok je ûivo.
{123744}{123860}Ne... dok vene i...|umire u vazi.
{123890}{123991}Iskreno tako mislite, zar ne?|-O, da, joö kako.
{124009}{124077}Mogu da vam kaûem|zaöto tako mislite.
{124082}{124119}Moûete li?
{124127}{124227}Zato öto ste videli kako vaö muû|ubija Ëoveka po imenu Graci.
{124234}{124329}SpelovaÊu vam ime,|G-R-A-C-I. Graci.
{124385}{124494}Ovde imam i vaöu sliku... slikanu|pre sedam godina.
{124500}{124554}Ako vam se svia,|daÊu vam je.
{124633}{124740}Muökarci sa slike su vaöi stari|prijatelji, jedan je ûiv, drugi mrtav.
{124969}{125025}Sluöajte me, Aliöa.
{125040}{125206}Braun, naûalost, nije gusenica.|Ne jede cveÊe, proûdire ljude.
{125254}{125369}Imao sam prijateljicu... devojku,|imala je 24 godine.
{125396}{125484}SinoÊ je ubijena. Braun je|hteo mene da ubije.
{125489}{125556}Nije joj znao Ëak ni ime. -NeÊu viöe|to da sluöam! Molim vas!
{125562}{125637}Molim vas, dosta mi je!|Zar ne vidite da mi je dosta?
{125645}{125704}Znam da vam je dosta,|Aliöa.
{125709}{125845}Dosta vam je straha. Sad ste pod naöom|zaötitom, viöe ne morate da se plaöite.
{125855}{125954}Svesni ste toga, jer ste|savröeno razumni.
{126019}{126063}Radije bih bila...
{126084}{126146}luda i ûiva...
{126201}{126243}nego razumna...
{126277}{126314}i mrtva.
{126399}{126472}Boli me. -Ako moûeö da ga pomeraö,|znaËi da nije polomljen.
{126477}{126526}Ali, boli me.|-Popij neöto.
{126531}{126603}VeÊ sam popio a i dalje me boli.|-Popij joö neöto.
{126608}{126680}Fanti, pokuöavam da ti objasnim,|kako ne shva...
{126906}{126980}Pa? -Imam vesti,|velike vesti.
{126992}{127031}Braun je gotov.
{127036}{127133}Policija je pronaöla Aliöu koja Êe|propevati pred velikom porotom.
{127179}{127262}Rekoh da je sa Braunom gotovo!|Kraj! Nema ga viöe.
{127267}{127376}To ti kaûeö. To niöta ne znaËi.|-Kad Graci kaûe, to je neöto.
{127381}{127433}Nema viöe Gracija, mrtav je.
{127438}{127497}Otkad to?|-Sedam godina.
{127508}{127549}Video sam telegrame.
{127554}{127624}Braun öalje te telegrame.|On ga je i ubio.
{127630}{127698}Braun ga "odrûava" u ûivotu da|se momci ne bi pobunili.
{127703}{127799}Zaöto niste malo obratili paûnju|na onu gospoicu Loel?
{127804}{127889}HoÊete da vam kaûem gde je?|Pomaûe policiji.
{127894}{127972}Izgleda da je gospodin Braun|ostao bez öarma.
{128032}{128087}I öta sad ti predlaûeö?
{128116}{128152}Da ga ubijemo.
{128317}{128378}Da ga ubijemo joö veËeras,|ne sutra.
{128383}{128436}Gospodin Braun Êe uskoro|ionako biti mrtav.
{128441}{128521}Momci Êe se postarati za njega Ëim Ëuju|koliko ih je dugo vukao za nos.
{128526}{128661}Ali, ako mi to brzo obavimo, mnoge ljude|Êemo spasti mnogih neprilika.
{128667}{128733}I imaÊemo jaËe pozicije|nego ikad.
{128746}{128842}Umesto da trËim naokolo za Brauna i da|tetoöim njegove uvrnute damice...
{128848}{128914}pokazaÊu vama dvojici öta|znaËi biti muökarac.
{128919}{129014}Idemo sve od poËetka.|Ovaj put malo sporije.
{129891}{129929}Poranili smo.
{129934}{129993}Rekoöe da Êe sleteti u|1:00 posle ponoÊi.
{129999}{130089}Nisam ûeleo da zakasnim,|dolaze Ëak iz Denvera.
{130094}{130168}»udno da javljaju preko tebe a|ne na uobiËajeni naËin.
{130174}{130235}To nije neuobiËajeno u|posebnim prilikama.
{130240}{130324}Rekli su da im treba 200.000|u malim novËanicama.
{130329}{130391}Doneo sam ih, ali u|Ëemu je stvar?
{130397}{130470}Denver je obiËno miran.|-Ne znam.
{130475}{130541}Pitao sam ih, ali nisu hteli da|mi kaûu preko telefona.
{130546}{130622}Nisu ti niöta ni nagovestili?|-Ne.
{130627}{130747}äta misliö, o Ëemu se radi?|-Uskoro Êemo saznati.
{130832}{130909}Dobro, gospodine Braun,|kako se sad oseÊate?
{130916}{130962}Ne baö sjajno, a?
{130999}{131065}Uzeo si mi posao,|uzeo si mi hotel.
{131070}{131144}Mislio si da moûeö skroz da|me skloniö s puta.
{131149}{131246}Propalice! Knjigovoo,|raËunovoo bedni!
{131267}{131359}Dajte mu... dajte mu odmah,|ono öto je zasluûio.
{131507}{131549}Stanite!
{131555}{131623}äta vam je, momci,|jeste li poludeli?
{131640}{131748}To sam ja, MekKlur!|Pogledajte, MekKlur!
{131789}{131855}Nemoj, Mingo!|DaÊu ti lovu!
{131860}{131951}Sve öto imam! 10.000!|20.000! Sve!
{131963}{132027}Nemoj, Fanti!|Nemoj!
{132037}{132070}Gospodine Braun!
{132075}{132111}Gospodine Braun!
{132261}{132326}Gospodine Braun, recite im,|molim vas!
{132331}{132423}UradiÊu sve öto hoÊete, otiÊi Êu!|Nikad me viöe neÊete videti!
{132429}{132531}Molim vas, gospodine Braun! Zaöto samo|Êutite? Ne dajte im da me ubiju!
{132536}{132577}Molim vas, gospodine Braun.
{132582}{132664}Ne ûelim da umrem, recite im.|Recite im, molim vas.
{133014}{133127}éao mi te je, Dûo.|Zato Êu ti uËiniti uslugu.
{133135}{133189}NeÊeö Ëuti pucnjeve.
{133821}{133873}Seme...|{y:i}-Da?
{133878}{133962}Reci kapetanu da sam|zavröio ispitivanje.
{134315}{134353}Gospoica Loel...
{134666}{134720}Jeste li policajka?
{134733}{134819}Nisam.|-A ko ste?
{134840}{134992}Zovem se... Suzan Loel. Ja sam...|svedoËiÊu protiv gospodina Brauna.
{134998}{135039}Ja neÊu.
{135131}{135179}Ne mogu ja ovo.
{135191}{135265}Zar se nisam veÊ dovoljno|ponizila?
{135271}{135352}Niko nije dovoljno uradio|sve dok je on na slobodi.
{135394}{135492}Bila sam... devojka|gospodina Brauna...
{135499}{135561}u protekle Ëetiri godine.
{135596}{135697}Uvek se kretao u ûenskom druötvu.|Devojke su lude za njim.
{135702}{135752}Nisam ponosna na to.
{135763}{135830}Zaöto ste onda ostali sa|njim Ëetiri godine?
{135842}{135916}Zaöto ste uopöte poËinjali?|-Ne znam.
{135921}{136009}Ne, nije istina.|ReËeno mi je, ali...
{136040}{136095}jednostavno nisam|verovala.
{136103}{136160}Pogledajte je, Aliöa.
{136167}{136284}Dobro je pogledajte, videÊete|sebe od pre deset godina.
{136322}{136432}Da ste tada progovorili... i vaö|ûivot bi bio sasvim drugaËiji.
{136474}{136530}Zato öto vas je ubio.
{136543}{136603}éivu vas je sahranio.
{136609}{136722}Zato öto je ubica.|Niöta drugo, ubica.
{136728}{136764}Ne ûelim to da sluöam.
{136770}{136843}Ubio je Gracija, zar ne?|I videli ste to?
{136848}{136895}Nikad to nisam rekla!
{136946}{137042}Pored toga, Graci je|zasluûio da umre.
{137047}{137171}A öta je sa devojkom koju je ubio pre|tri dana? I ona je zasluûila da umre?
{137176}{137216}Koja devojka?
{137266}{137382}SeÊate se devojke... devojke o kojoj sam|vam priËao u sanatorijumu. SeÊate se!
{137387}{137490}Ne, ne seÊam se! -Onda se|prisetite! To je ta devojka!
{137512}{137602}Devojka koju nije znao, nikad|upoznao, nikad video.
{137608}{137691}Izvadili su jedanaest|metaka iz nje.
{137704}{137789}SledeÊeg jutra gospoica Loel|je doruËkovala sa njim.
{137795}{137898}NaruËio je öunku i dva jajeta.|Recite joj, Suzan.
{137903}{138009}Recite joj kako je jeo öunku sa|jajima dok je Ëitao novine...
{138014}{138111}i gledao telo ove devojke|kako leûi u mrtvaËnici.
{138192}{138254}ReÊi Êu vam sve öto znam.
{138332}{138418}OdveöÊemo je kod tuûioca da|da izjavu.
{138439}{138477}Gospoo Braun.
{138892}{138989}Kapetane! Kapetane, ovo je|gospodin Maloj, advokat.
{138994}{139088}Imam nalog {y:i}habeus corpus{y}|za gospou Aliöu Braun.
{139093}{139205}Ne znamo mi nikakvu gospou Braun.|Ovo je gospoa Ana Li Dûekson.
{139328}{139369}Zdravo, Aliöa.
{140064}{140124}Nema svrhe, niöta od nje.
{140130}{140186}Pa, ne zavröava se svaki sluËaj|unapreenjem,
{140191}{140269}ni imenom u novinama.
{140320}{140421}Pronaöli smo MekKlurovo telo|u reci, prepuno je rupa.
{140454}{140556}Ovo je Ëin oËajnika!|Gospodin Braun puca.
{140566}{140664}Seme, povedi ljude iz stanice i|privedite Fantija i Minga.
{140690}{140762}Pravo Drajer, Rita, MekKlur...
{140767}{140859}NemoguÊe da imaju alibije za|sva tri ubistva.
{140870}{140936}Dobro, Mingo, okani se toga.
{141011}{141088}Mingo, rekao sam,|okani se toga!
{141259}{141309}Moraö neöto da pojedeö.
{141347}{141405}Ne mogu viöe tu salamu.
{141410}{141464}To je sve öto imamo.
{141479}{141590}Gde je Braun, kad dolazi?|Koliko Êemo ostati ovde?
{141607}{141671}Ovde smo amo dva dana,|niöta viöe.
{141691}{141768}Ja... ja ne mogu viöe,|Fanti.
{141798}{141915}Mislim da mi se palac neöto inficirao,|boli gore od öupljeg zuba.
{141921}{142037}Ako nas panduri do'vate boleÊe joö gore.|-Panduri! äta mogu da dokaûu?
{142055}{142118}Ne moraju niöta ni da|dokazuju.
{142131}{142223}Izdali su tri naloga za hapöenje,|optuûnice za tri ubistva.
{142228}{142312}Neka nas optuûuju, ne mogu|niöta da dokaûu...
{142374}{142413}Mogu li?
{142498}{142590}Znaö koliko bi trajala suenja|za ta tri ubistva?
{142612}{142703}Bili bismo u zatvoru bar tri godine.|Opusti se, bre malo.
{142708}{142767}Braun Êe nas izvesti iz grada dok|se situacija malo ne smiri,
{142772}{142816}a onda moûemo da|se vratimo.
{142821}{142911}Odakle znamo da smo ovde bezbedni?|-Ovo je najbezbednije mesto na svetu.
{142916}{142970}Graci ga je izgradio za vreme|prohibicije.
{142975}{143053}Ni hotelski potrËko|ne zna ovo.
{143058}{143118}Dosta m i je ovog grada,|Fanti.
{143176}{143259}Kad odemo, hajde da se|viöe ne vraÊamo.
{143313}{143379}Najviöe me brine kako da izaemo|iz ovog hotela...
{143384}{143464}panduri Êe zaviriti u|svaki orman.
{143667}{143758}VeÊ smo mislili da nikad neÊete|doÊi. -Smirite se, momci
{143794}{143853}Sluöajte, sada je Ëetiri|popodne.
{143858}{143976}Sutra ujutru u 5:30, panduri se smenjuju|u straûnjoj ulici. Tada Êu doÊi po vas.
{143981}{144076}Jeste li nam nabavili auto? -Sve je|sreeno. Strpite se joö malo.
{144081}{144167}Doneo sam vam neöto da pojedete.|-Ako ovo potraje poludeÊu.
{144172}{144220}Obojica ste bili dobri momci.
{144225}{144304}Ovde imate dovoljno novca|za dug i lep ûivot.
{144309}{144388}Podelite poöteno i ne svaajte|se oko toga.
{144483}{144569}äta misliö, koliko ima?|-Gospodin Braun je öiroke ruke.
{144574}{144646}VideÊu kad prebrojim.|-Daj ga ovamo.
{145363}{145422}Policija je u prizemlju.
{145506}{145557}Donesi mi joö jednu flaöu.
{145585}{145640}Mingo je joö ûiv.
{145791}{145852}NemoguÊe.|-Ali, jeste.
{146420}{146476}Ne ûelim opet da idem tamo.
{146481}{146560}Morate da identifikujete neke|stvari iz Braunovog trezora.
{147041}{147135}Ko je ovo uradio, Mingo? Mingo!|Ko ti je ovo uradio?
{147141}{147168}Niko.
{147173}{147248}Ko je ubio devojku po imenu Rita?|Ko je ubio MekKlura?
{147253}{147316}Ko ti je platio da ih ubijeö?|-Niko.
{147322}{147391}Imaö opekotine treÊeg stepena,|Mingo. Umireö.
{147396}{147440}NeÊu umreti.
{147463}{147505}Ti neÊeö...
{147583}{147627}a neÊe ni Fanti?
{147786}{147825}Fanti...
{147889}{147948}Ne ostavljaj me, Fanti...
{147953}{148035}Mrtav je. Ubio ga je isti onaj koji|je pokuöao i tebe da ubije.
{148040}{148129}Nemamo mnogo vremena, Mingo. Reci nam|ko je ovo uradio. Reci nam zbog Fantija.
{148135}{148192}Nije smeo to da uradi...
{148208}{148270}Fanti mi je bio prijatelj...
{148369}{148404}U redu...
{148409}{148450}ReÊi Êu vam...
{148476}{148530}Ali, ne zbog vas...
{148565}{148668}Bili smo poöteni prema njemu,|nije smeo da ubije Fantija.
{148673}{148766}Nemamo puno vremena, Mingo. Ko je ovo|uradio? Ko je ubio devojku u mom stanu?
{148771}{148832}Ko ti je platio da to|uradiö?
{148913}{148952}Gospodin Braun.
{148987}{149036}Gospodin Braun.
{149062}{149115}Lenarde...|-Molim?
{149133}{149199}Sem je ranjen. Upucan.
{149218}{149319}äta? Gde... gde je? -U bolnici.|BiÊe sve u redu.
{149324}{149412}Sluöaj, Lenarde...|Suzan je nestala.
{149602}{149683}Lari, uzmi mu izjavu,|neka potpiöe.
{149750}{149822}»ovek kao öto je Braun|sigurno ima neki plan.
{149828}{149979}Gde bi otiöao ako ûeli da pobegne?|-Policajac ste, pronaite ga sami.
{150003}{150079}Nije sam, poveo je sa sobom|i Suzanu Loel.
{150084}{150158}Ne bih mrdnula ni malim prstom da|pomognem toj devojci.
{150170}{150281}Neka proe kroz ono kroz öta sam i ja|proöla. -Niöta vam nije uradila, Aliöa.
{150286}{150360}On vas je sklonio u stranu,|zaöto ste kivni na nju?
{150365}{150406}Zato öto je mrzim.
{150411}{150500}Nju, i svaku drugu ûenu koja je|ikad imala iöta sa njim.
{150530}{150599}A öta sam vam ja uradio,|zaöto mene mrzite?
{150604}{150642}Ne mrzim vas!
{150693}{150746}Moram da... -Onda mi pomozite|Pomozite mi!
{150751}{150841}Recite mi gde da ga naem.|-Moram da se vratim svom cveÊu.
{150847}{150922}Sigurna sa da se niko|ne stara o njemu.
{151155}{151194}PoruËniËe...
{151347}{151406}Ne ûelim da vam pomognem...
{151435}{151471}Ne ûelim.
{151506}{151542}Ali, hoÊu.
{151653}{151752}Gde je taj avion? Trebalo je da|bude ovde pre sat vremena.
{151758}{151866}Godinama plaÊam tog glupog pilota|samo za ovakav sluËaj.
{151872}{151923}Zaöto ne dolazi?
{152028}{152082}To da viöe nisi pokuöala!
{152186}{152276}éelim da me vide.|-Ne pokuöavaj to viöe!
{152361}{152414}Zaöto ne dolazi?
{152421}{152526}Sve sam smislio. Od poËetka |do kraja, do detalja.
{152543}{152602}A sad se sve raspada!
{152620}{152685}»ovek ne moûe nikome|da veruje.
{153687}{153741}Izai, Braune!
{154334}{154392}Ne moûeö da pobegneö,|Braune!
{155586}{155695}Ne moûeö da pobegneö, baci piötolj!|-Doi da ga uzmeö!
{155896}{155936}Hajde!
{155952}{156017}Vodim vas u zatvor, gospodine|Braun. -Ne, ne vodiö!
{156023}{156097}NeÊeö me strpati u zatvor!|MoraÊeö da me ubijeö!
{156102}{156176}Hajde, pucaj! Pucaj!|Ubi me, ûaco! Ubij me!
{156181}{156282}Hajde! Ubij me! Ubij me!|-Idemo... propalice.
{156352}{156388}Idemo!
{156394}{156445}NeÊu u zatvor!
{156451}{156487}NeÊu!
{156494}{156530}Pucajte!
{157166}{157467}{Y:i}zgaca62@yahoo.com
{157492}{158992}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/8teze|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
