{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1922}{2062}MRTVI PREDSEDNICI
{5900}{6010}SeveroistoËni Bronks, 1968. g.
{6245}{6292}Gde si do sad?
{6300}{6370}Morao sam do zadnje kuÊe.|Tiöina. -Smrzavam se!
{6380}{6427}Poûuri!
{6645}{6682}Huanita ti je veÊ dala?
{6697}{6755}Prestani. -äta je?
{6780}{6835}Drugovi smo. Samo pitam.
{6842}{6940}Zaöto to moraö da me pitaö?|-Pazim na tebe.
{6960}{7052}Koliko god da je dobra,|veÊ bi morala malo da ti da.
{7060}{7115}Joö joj nije ni primirisao.
{7155}{7245}Znate da Êemo uskoro|zavröiti ökolu? -Jasno.
{7252}{7325}Posle 4 godine sranja.|Jedva Ëekam da zavröi.
{7330}{7380}Samo o tome razmiöljam.
{7385}{7455}Znate öta Êu|posle da radim?
{7461}{7522}Voleo bih malo da putujem.
{7535}{7590}ZvuËiö kao bogataö.
{7597}{7686}»ujeö li ga?|-Nema ni posao. -Znam.
{7695}{7825}Upiöi se na faks jer Êe te|uzeti u vojsku kao Hozea.
{7830}{7892}Gluposti, Skip.|Niko mene neÊe uzeti.
{7922}{7986}Regruter vidi|da si glup nadaleko!
{8000}{8077}Ti si njegov san.|Pravi prioritet.
{8082}{8147}Jednosmerna karta|u jebeni Vijetnam.
{8155}{8262}Ja Êu zato u Hanter koledû.|NeÊu da ratujem za belce.
{8270}{8346}Oni Vijetkongovci|mi nisu niöta skrivili.
{8353}{8391}Ne poznajem ih.
{8416}{8473}Ne bojim se rata.
{8496}{8543}äta si to puöio?
{8546}{8593}Moûda mislite da sam lud,
{8643}{8691}ali ûelim da radim|neöto drugaËije.
{8696}{8758}Pa, poginuti je drugaËije.
{8786}{8873}Stiöaj to sranje!|I ne poûuruj nas u ökolu.
{8881}{8913}Ostavi to.
{9061}{9098}Jebao sam Moniku.
{9106}{9186}Mama nas je uhvatila. Videla|mi ga je i skoËila u krevet.
{9193}{9268}Vidimo se, naivËine.|-Jebi se. -Tvoju mamu!
{9278}{9336}Vrati se u kamion.
{9341}{9406}Uûasno je hladno.|Vrati se unutra.
{9646}{9681}Kako si?
{9708}{9741}Rano si budna.
{9763}{9803}»ula sam tvoj kamion.
{9823}{9878}»ini se da ga|Ëujeö svako jutro.
{9911}{9963}Jutro je najbolje|vreme za uËenje...
{9981}{10056}Trebala bi da se potrudiö|da naeö svog prvog deËka.
{10101}{10163}Prezaposlena sam uËenjem|da mislim na deËke.
{10213}{10243}Sestra ti je budna?
{10303}{10338}Uspavana lepotica?
{10388}{10451}Reci joj da sam je pozdravio.|Vidimo se.
{10576}{10613}Dobro jutro, Entoni.
{10651}{10718}Mislio sam da spavaö.|-Probudio si me.
{10761}{10798}Ideö danas u ökolu?
{10836}{10888}Mogla bih da leûim|celi dan.
{10901}{10993}To bi bilo dobro.|-Ni ne pomiöljaj na to.
{11021}{11113}Sluöaj, moram da idem.|Vidimo se posle.
{11128}{11168}Vidimo se.
{11251}{11341}PROLE∆E, 1969. g.
{11631}{11736}Teöka cipelo, doi ovamo.|Kako je? äta ima novo?
{11738}{11828}Sluöaj, reci Kirbiju|da hoÊu 645, tim redom.
{11841}{11928}Stalno dobijamo.|-Samo mi dajte novac.
{11933}{12026}Vrati se veËeras s novcem!|-Namestite öeöir. -Budalo.
{12081}{12128}äta ima? Kako je, frajeru?
{12146}{12188}Entoni, kako si?
{12201}{12236}Doneo si mi sreÊu.
{12246}{12303}10 od ovog je za tebe.
{12403}{12443}KoristiÊu isti broj.
{12448}{12573}äta ima? Frajeru, öta ima?
{12926}{12998}äta ima? Kako si?|Kirbi je pozadi?
{13095}{13156}Pogodi to.|-Hvala, mladiÊu.
{13173}{13223}Hej, öta ima?
{13511}{13563}Idi u Bruklin i nai Spajdera.
{13701}{13723}Evo brojki.
{13761}{13788}I lova.
{13973}{14067}Ideö u lov s tatom?|-SledeÊi vikend.
{14370}{14406}Sranje.
{14416}{14481}Zbog tebe sam promaöio, Kirbi.
{14516}{14608}Pitam se, veruju li oni majmuni|na jugu onomu öto govore?
{14645}{14681}äta da crnac radi?
{14736}{14781}Robovska krv je u zemlji.
{14791}{14863}Prolivena u ratu.|Bio sam u ratu ranjen.
{14892}{14933}Tako je. Reci im, Kirbi.
{14938}{14976}Borio si se u Koreji.
{14986}{15046}Tako sam dobio plastiËnu|nogu. Daj mi piÊe.
{15066}{15102}Jebeni idioti.
{15243}{15277}Prokletstvo.
{15356}{15458}Da sam ostao na jugu,|ubio bih jednu od tih gnjida.
{15473}{15543}To se nikada neÊe promeniti.|Zaöto misliö da hoÊe?
{15573}{15636}äta ti radiö ovde?
{15683}{15727}Ostavi ga na miru|i pusti da igra.
{15756}{15833}Znaö da je premlad|da bude ovde.
{15848}{15893}Moûe da te pobedi.
{15936}{16023}Sranje. Sigurno si poludeo.
{16093}{16127}Da se kladimo?
{16243}{16316}UzeÊu ti novac. Sloûi ih.
{16486}{16511}Gledaj ovo.
{16732}{16759}Imaö moja dva dolara?
{16777}{16817}Joö nije gotovo.
{16839}{16882}Osmica u ugao.
{17074}{17139}Nemoj da pobegneö da mi|ne platiö kad izgubiö.
{17152}{17212}Barem mogu da pobegnem odavde.
{17219}{17259}DugovaÊeö mi novac.
{17382}{17439}HoÊeö li mi se|skinuti sa stola?
{17549}{17579}Jebena kukavica.
{17622}{17669}Nemaö tu öta da traûiö.
{17832}{17919}Promaöio si za dlaku.|Vreme je za kraj.
{18004}{18054}Osmica u ugao.
{18209}{18254}Da! Pobeda.
{18342}{18382}Dobra igra, Kauboju.
{18397}{18442}SreÊkoviÊu prokleti.
{18534}{18582}Ne bih rekao da je sreÊa.
{18587}{18629}Malo znam i da igram.
{18637}{18684}Za Kirbija.
{18744}{18789}»ekaj, Ëekaj.|To je dva dolara.
{18814}{18912}Kladio si se sa mnom.|ZnaËi da i meni dugujeö.
{18962}{19002}Jebi se, ËoveËe.
{19049}{19084}Zaöto moraö da varaö?
{19112}{19169}S kim misliö da razgovaraö?
{19182}{19274}ReÊi Êu svima da kad|se radi o bilijaru,
{19282}{19322}Kauboj voli da vara.
{19332}{19387}NamlatiÊu te.
{19397}{19422}»oveËe.
{19464}{19504}Zaveûi.
{19522}{19564}Trebao bi da te iseckam.
{19592}{19634}PederËino.
{19684}{19719}Boli, zar ne?
{19772}{19837}äta to...? äta to radiö?
{19897}{19959}Pusti me! äta to radiö?
{19982}{20017}äta radiö?
{20032}{20089}Gubi se odavde!
{20127}{20174}Ne vraÊaj se ponovo ovakav.
{20374}{20404}Jesi li dobro?
{20422}{20494}Da. Samo mala|posekotina. U redu je.
{20584}{20684}Dobro radiö sa brojkama.|-Pa, znaö, trudim se.
{20744}{20784}Ali, bolje budi paûljiv.
{20792}{20872}Ne daj da ti roditelji saznaju.|-Nikako. Nema öanse.
{21022}{21064}Za tebe.
{21117}{21159}»oveËe.
{21217}{21299}Hvala. -Ne zahvaljuj|meni. Zaradio si.
{21392}{21469}Hej, momËe, hoÊeö li|da se provozaö sa mnom?
{21549}{21594}Da, hoÊu.
{21727}{21764}Kirbi, gde idemo?
{21784}{21829}Rekao sam ti. Mala voûnja.
{21847}{21879}Voûnja?
{21972}{22007}éeliö da voziö?
{22027}{22094}Ja? -Ne ja. Ti, budalo.
{22119}{22169}Joö nemam dozvolu.
{22174}{22222}Jebeö to. HoÊeö li da voziö?
{22232}{22274}Da, voziÊu.
{22397}{22444}Stani ovde. -Dobro.
{22464}{22494}Hajde.
{22524}{22569}Kako je zoveö? Neli?
{22594}{22644}Zovem ovu kuju kako god hoÊu.
{22972}{23067}Sluöaj, ostavi motor|neka radi. Odmah dolazim.
{23724}{23784}Petljaö sa mojom lovom?|Koliko puta moram da ti kaûem?
{23917}{23967}Sa mnom se ne igra!
{23969}{24047}NapraöiÊu te! Diûi se!
{24059}{24109}Odjebi od Spajdera!
{24182}{24229}Hrabrija si od ove|svoje propalice.
{24299}{24334}»oveËe.
{24367}{24429}Daj mi moju nogu!|KuËkin sine!
{24439}{24494}Zgrabio si pogreönu|nogu, idiote!
{24509}{24544}äupËino!
{24572}{24649}HoÊu svoj jebeni novac!|-Polako, Kirbi.
{24667}{24774}Glupane jedan. Daj mi moju|nogu, idiote! SrediÊu te.
{25031}{25058}Nagazi!
{25108}{25143}Idemo!
{25476}{25506}Bio si dobar, momËe.
{25531}{25606}Skoro si dobar vozaË|za beg kao ja. -Hvala.
{25638}{25706}ZnaËi, bio si vozaË za beg?
{25840}{25883}KuËkin sin.
{25890}{25926}äta je?
{25931}{25983}Moram da se vratim|i ubijem ga. -Zaöto?
{25990}{26063}Zbog njega sam izgubio|cigarete. -Cigarete?
{26127}{26201}Mislio sam da brineö zbog|noge ili neËeg drugog.
{26211}{26281}Misliö da je to smeöno?|-Ne, ne. Nije.
{26311}{26368}SledeÊi put kada mi|zgrabi pogreönu nogu,
{26373}{26423}prebiÊu ga.
{26477}{26526}Stvarno si ga sredio.
{26531}{26606}Svi znaju da imam jednu|nogu, a on je zgrabio pogreönu!
{26611}{26683}Ja i Kirbi. Tako je.
{26833}{26883}Ovo su divne vesti, Edvarde.
{26986}{27018}Vidiö, Entoni?
{27027}{27101}Moûeö da ideö na koledû|uz finansijsku podröku.
{27156}{27215}Za Ëetiri godine|moûeö da budeö kao ja.
{27268}{27306}Kao ti?
{27336}{27413}Moûeö da diplomiraö, a moûda|da ideö i na postdiplomski.
{27448}{27515}Moja mama bi sigurno|bila ponosna.
{27531}{27606}Nikada ne bih verovala|da imam dva diplomca.
{27683}{27727}Na koji Êeö stepen?
{27802}{27858}U mornaricu. Dodaj mi so.
{27863}{27896}äta si rekao?
{27986}{28090}Rekao sam, u mornaricu.|PrijaviÊu se.
{28098}{28136}Mornarica?
{28158}{28196}To je originalno.
{28215}{28258}O Ëemu to govoriö?
{28273}{28333}éelim da radim neöto drugaËije.
{28348}{28383}Ne ûelim u koledû.
{28401}{28448}Dosta mi je ökole.
{28543}{28608}Zaöto me svi tako|Ëudno gledaju?
{28633}{28723}To je moj ûivot.|-Da. Tvoj ûivot.
{28798}{28856}»ini se da pokuöavaö|da ga uniötiö.
{28996}{29033}Ti si idiot, znaö?
{29151}{29226}Ne ûelim u koledû.|Nisam za to spreman.
{29298}{29351}Rekao si da te mornarica
{29356}{29413}i borba u Koreji|uËinila Ëovekom.
{29465}{29538}Mislim, ûiveÊu svojim ûivotom.
{29581}{29621}RazgovaraÊu sa tvojom mamom.
{29731}{29823}MATURSKO VE»E, 1969. g.
{30556}{30616}Rekao sam ti da ne|moûeö da pijeö uz mene.
{30931}{30996}Joö ne mogu da verujem|da si maturirao, Skitere.
{31021}{31047}∆uti!
{31053}{31103}Drago mi je öto smo|zavröili ökolu.
{31153}{31203}RadiÊu kao svodnik.
{31210}{31272}Imam toliko kurvi|da mi treba pomoÊnik
{31281}{31335}da ih pratim.
{31347}{31438}Skipi, zaöto uvek|priËaö o svodniötvu?
{31446}{31513}Ja sam svodnik.|To mi je porodiËno.
{31518}{31558}Moj prapradeda je bio rob
{31566}{31643}i svodnik. Kurve su|mu brale pamuk.
{31651}{31733}Budi paûljiv.|ZaraziÊeö se neËim.
{31735}{31828}Roen sam od pice, i umreÊu|od nje. Ne brini se za mene.
{31853}{31922}Praznoveran si, Skipe?|-Nisam.
{31968}{32046}Trebao bi da budeö, ËoveËe.|Urekao si me.
{32085}{32116}äta?
{32121}{32163}Vojska.
{32181}{32235}Prvi sam na listi prioriteta.
{32246}{32297}Rekao sam sebi, zar ne?
{32306}{32366}Kad se to desilo?|-Proöle nedelje.
{32371}{32421}Da. Dodaj mi dûojnt.
{32488}{32522}Entoni, ËoveËe.
{32535}{32613}Znaö da smo Marisol|i ja bliski.
{32622}{32678}Da, dobro vam ide.
{32683}{32766}Rekao bi da je volim?|-Mogao bih to da kaûem.
{32776}{32858}Mislim da Êu je oûeniti.|-»ekaj malo.
{32866}{32943}Nemoj to da uradiö.|-Moûda ideö prebrzo.
{32956}{33048}Volim je, ËoveËe.|Vidiö kako danas izgleda?
{33061}{33148}Dovoljno dobro za udaju.|-Drago mi je da me ûeliö.
{33221}{33313}O Ëemu govoriö, Entoni?|-Zaöto stojite tamo?
{33318}{33357}Zaveûi, Skipi.
{33429}{33509}PriËaÊeö sa Skipom|dok svira moja pesma?
{33514}{33577}Ne, ako oËekuju da Êe|biti s nama veËeras.
{33627}{33699}Skip, mi idemo.|-Gde idete?
{33704}{33744}Da se zabavljamo.
{33752}{33839}Mislio sam da se zabavljamo.|Rekao sam vam za ûenske.
{33874}{33929}U svakom sluËaju,|Brenda te traûi.
{33939}{34014}Baö me briga. Reci joj|da sam tamo gde jesam.
{34032}{34119}Ja sam svodnik. Da sluöam|svaku kurvu, bio bih zbunjen.
{34132}{34189}Reci joj da ne ûelim da|povredim ruku.
{34597}{34629}Hoze.
{34644}{34674}Volim te.
{34724}{34767}I ja tebe volim, draga.
{34802}{34852}Ako daö moju malu|nekom drugom
{34864}{34899}dok me nema,
{34914}{34969}doÊi Êu i razneti ga.
{35027}{35094}Neöto me svrbi|öto treba poËeöati.
{35284}{35384}Kaûeö da ti mama|radi noÊnu smenu?
{35437}{35474}Znaö öta joö?
{35497}{35567}Moûeö me Ëeöati|celu noÊ ako hoÊeö.
{35652}{35709}Znaö da sam crnac.|Ja sam crnac.
{35769}{35839}Tvoja mama moûe|doÊi ranije. -NeÊe.
{35877}{35924}Bojiö li se? -Ne.
{35929}{35967}Tako se ponaöaö.
{36024}{36079}Gde je Dilajla?|-U svojoj sobi.
{36279}{36314}Izlazi!
{36327}{36369}Idi u svoju sobu.
{37074}{37104}Sluöaj, u redu je.
{37124}{37159}U redu je.
{37252}{37289}Daj da ti skinem grudnjak.
{37387}{37437}Samo ga odveûi. Samo...
{37469}{37502}Ne mogu. -Ja Êu.
{37612}{37664}Ne viri. Nemoj da me gledaö.
{37849}{37879}To nije.
{37912}{37964}Gore, gore. Viöe.
{37977}{38034}To je previöe. Niûe, niûe.
{38042}{38069}Ovde? -Da.
{38344}{38377}Polako.
{39127}{39164}»ekaj.
{39189}{39224}Sranje.
{39337}{39409}Marisol i Hoze idu sutra|u Gradsku Skupötinu.
{39422}{39469}Da? Zaöto?
{39479}{39519}Da se venËaju.
{39572}{39629}Stvarno?|-äta misliö o tome?
{39697}{39737}Verovatno niöta.
{39767}{39832}ZnaËi, ni ti ne ûeliö|da ja tebe Ëekam?
{39862}{39909}Huanita, nisam to rekao.
{39927}{39979}OûeniÊeö se mnome|kada se vratiö?
{40062}{40122}Ako ne budeö imala|nekog drugog.
{40172}{40217}Ne ûelim nikog drugog.
{40299}{40364}Huanita, jesi li|ikada pomislila
{40409}{40479}da bih mogao da nastradam|i ne vratim se?
{40504}{40564}Ne ûelim da Ëekaö uzalud.
{40652}{40707}Ne bojiö se da|moûeö da me izgubiö?
{40732}{40772}Nisam to rekla.
{40817}{40869}Bojim se da te izgubim.
{41069}{41164}Moûemo li to da uradimo|joö jednom pre mog odlaska?
{41622}{41659}O, ne.
{41738}{41775}To je mama!
{41783}{41830}Ali tek je 6:30 h.|-Upravo je doöla.
{41835}{41890}Idi odugovlaËi.|I zatvori vrata!
{41945}{42048}Nisam trebao da se petljam|sa tobom. UbiÊe nas.
{42088}{42130}Pomeri se!|-»ekaj malo.
{42178}{42228}Da ti pomognem sa paketima.
{42273}{42375}Namirnice su mi na|podu. Podigni ih!
{42435}{42495}Barem biste mogle ovu|kuÊu da odrûavate Ëistom.
{42785}{42840}»ekaÊu te, Entoni.
{43288}{43333}Moram da idem, Huanita.
{43563}{43595}Moram da idem.
{43678}{43730}Gubi se iz mog vrta!|-Jebi se!
{43850}{43890}Zaveûi!
{43910}{43998}Kakav je vaö status?|Prijem.
{44053}{44138}POVLA»ENJE SA NEPRIJATELJSKE|TERITORIJE KVANG TRI, 1971. g.
{44255}{44290}Sranje!
{44328}{44388}Prema bazi!|ldite prema bazi!
{44445}{44493}Nestanite odavde!
{44560}{44620}Idemo! Brûe! Hajde!
{44633}{44693}Hajde, idemo! Brûe!
{44788}{44823}Napunite puöke!
{44918}{44965}Sranje. Ostao sam|bez municije.
{44968}{45025}Pokrij me, Devo!|-Ostani dole!
{45085}{45115}Ja Êu.
{45193}{45283}Nemoj da nas ostaviö.|BiÊeö dobro. -Ja Êu.
{45378}{45455}Prikljeötili su nas.|NeÊemo moÊi da stignemo do baze.
{45505}{45543}Dugan!
{45560}{45625}Misliö da je vreme da|se reöimo ovih Azijata?
{45648}{45678}Smiri se.
{45683}{45740}Jebi se!
{45783}{45815}Donesi radio!
{45863}{45900}Bogu se ovo ne svia.
{45915}{45953}Kako je on?
{45988}{46038}Hvala öto me nisi ostavio.
{46045}{46108}Gde je taj radio?!|Donesite ga!
{46125}{46170}Ovamo sa radiom!
{46183}{46243}Pokrivaj vatrom.|éeliö da umreö?
{46248}{46288}Frekvencija artiljerije!
{46335}{46398}Gospodine, frekvencija|artiljerije!
{46425}{46508}Hamerhed, Kobra. Potrebna|podröka artiljerije.
{46538}{46633}Drûi se, brate. PreûiveÊeö.|Joö samo malo.
{46703}{46743}Reci mojoj mami...
{46745}{46790}Ne, ne.
{46933}{46993}Traûio artilje rijsku paljbu.
{46998}{47038}»ujete li? Prijem.
{47045}{47138}Potvrdno. Prijem dobar.|Artiljerija ide sa paljbom.
{47140}{47173}Dolazi!
{47188}{47218}Dole!
{47228}{47288}Dole! Dole, Kertis!|Spusti se dole!
{48313}{48360}Superjebeni posao.
{48380}{48465}Idemo do baze. Odvedimo|helikopter kuÊi.
{48480}{48525}Sada idemo u bazu?
{48638}{48710}Misija je otkrivena.|Odlazimo.
{48740}{48800}Viöe nije otkrivena.|Mrtvi su.
{48823}{48910}Ovde Pit na neprijateljskoj|teritoriji.
{48918}{49015}Neki od ovih mrtvih Azijata|moûda imaju neke papire.
{49113}{49140}Dobro.
{49188}{49233}Maknite se. -Maknite se!
{49298}{49368}Hamerhed. Kobra je|na mestu tvoje misije.
{49375}{49405}Ima deset
{49410}{49468}poginulih Vijetnamaca.
{49588}{49680}Hamerhed, Kobra. Dobar|posao. Kobra zavröava.
{49775}{49863}Sranje, ËoveËe! äta|to radiö? VeÊ je mrtav.
{50127}{50159}Budale!
{50192}{50234}»ini se da smo|ubili oficira.
{50277}{50319}SreÊni kuËkin sine.
{50334}{50407}VraÊamo se u ötab.|Reci koliko traûiö.
{50412}{50492}Niöta od toga.|ZadrûaÊu ovo.
{50502}{50579}Traûim ovakav otkad smo Kleon|i ja doöli ovamo 66-te.
{50582}{50624}Zar ne, Kleone?
{50707}{50754}Hodao sam ravno kraj njega.
{50762}{50802}Moraö da budeö paûljiv.
{51079}{51112}äta to...?
{51647}{51684}Gladan si, Kleone?
{51739}{51782}Baö kao i vi, gospodine.
{51807}{51872}Uzimam suvenir.
{52002}{52049}Spremite se. Odlazimo.
{52092}{52172}To je sve öto Êete reÊi?|-Moramo da se pomirimo sa ovim?
{52672}{52714}Taj crnja Kleon je lud.
{52722}{52774}Vidiö to sranje? -Da.
{52779}{52809}Video si?
{52827}{52889}»uo sam da je|propovednikov sin.
{52893}{52952}SeËe glave za suvenire.
{52957}{53084}Da nisi odvisio sa studija,|propustio bi ovu divotu.
{53089}{53184}Ma nemoj. Zbog tebe|i jesam dospeo ovamo.
{53192}{53279}Nisi mi priËao o ovom.|-Jer me nisi pitao.
{53287}{53384}Mislio sam da je bolje od|peöadije. -Da, bolje je.
{53392}{53447}Celi dan smo u öumi.
{53449}{53537}Vijetnamci iskaËu poput|Indijanaca. Crnci nisu za ovo.
{53542}{53617}Mislio si da je to sitnica.|-Nema niöta loöe u tome.
{53629}{53684}Proglasi me jebenim dezerterom.
{53689}{53762}Zbrisao bih odavde|da imam priliku.
{53817}{53889}Meu mojima nema lenËina.|-O Ëemu ti to?
{54393}{54427}Za Bronks.
{54484}{54593}Za mladiÊa koji nije danas|sa nama. Za kaplara Martina.
{54604}{54637}Za kaplara Martina.
{54872}{54902}Entoni, ËoveËe.
{54927}{54967}äta ti to govore?
{54982}{55049}Malo si zaglibio u svemu ovom.
{55062}{55134}I ti isto, Skipe.|Ovde si.
{55197}{55247}Jebeö to sranje, ËoveËe.
{55264}{55302}Ovo nije naö rat.
{55306}{55377}Mi bismo trebali|da budemo kuÊi u Bronksu.
{55392}{55464}Hoze je imao sreÊe. Poslali|su ga kuÊi. Bio je ranjen.
{55468}{55564}Bio je teöko ranjen|u ruku, ËoveËe.
{55567}{55618}U redu je. Izvukao se.
{55624}{55684}Bolje je biti kod kuÊe|sa ranjenom rukom i jebati,
{55687}{55752}nego ovde biti zdrav.
{55781}{55847}Nisi se promenio, Skipe.|-Tako je.
{55877}{55909}Huanita ti se javlja?
{55952}{56012}Na poËetku duûnosti|puno mi je pisala.
{56052}{56106}Ispada da je, pre mog odlaska,
{56137}{56179}zatrudnela.
{56224}{56268}Sereö! -Ne.
{56277}{56343}Ozbiljno?|-Kod kuÊe imam curicu.
{56349}{56399}To je super, ËoveËe.
{56452}{56529}Znam da imaö njenu sliku.|Daj da je vidim.
{56537}{56579}Ne mogu je ni gledati.
{56592}{56684}Kako to misliö?|To ti je mala, tvoja Êerka!
{56692}{56759}Znaö kako sam preûiveo|ovih 26 meseci?
{56764}{56837}Ne mislim na svet.|Ne postoji.
{56864}{56924}Viöe mi nije vaûan.
{56927}{57012}Jer Ëim to postane,|gotov sam. Upamti to.
{57037}{57104}RazgovaraÊemo o|svetu kada se vratimo.
{57127}{57168}Da, kako ti kaûeö.
{57184}{57272}Planiram da se drogiram.|Ozbiljno.
{57287}{57339}I puöiÊe mi kurac.
{57497}{57547}Velik je. Velik.
{57549}{57624}Vrlo velik. Moûeö li|s tim izaÊi na kraj?
{57677}{57752}Zdravo, Kirbi. äta se|zbiva tamo u svetu?
{57762}{57837}Ako veÊ nisi Ëuo,|na drugoj sam duûnosti.
{57864}{57899}Vatra u rupi!
{58006}{58059}Provodimo veÊinu vremena u öumi.
{58124}{58164}Ne oseÊamo ovde viöe niöta.
{58179}{58217}Pokuöavam da saËuvam razum.
{58234}{58317}PoruËnik nam je ludi|belac Dugan iz Ohaja.
{58438}{58493}Dobro nas izvlaËi|iz ludih situacija.
{58585}{58663}Ovde imamo jednog ludaka|koji se zove Kleon.
{58694}{58785}Tata mu je propovednik.|Njegov sin se tako ne ponaöa.
{58790}{58865}Sad si dobar.|Sad te Isus voli.
{58890}{58930}On je iz Mt. Vernona.
{58938}{59019}NeÊeö verovati, ali Skip je|dobrovoljac u mojoj jedinici.
{59053}{59098}Nije on baö za to.
{59103}{59203}Uvek se drogira, pokuöavajuÊi|da zaboravi na sve to.
{59219}{59330}A ja? éivim dan za danom|i radim ono öto treba,
{59368}{59405}öto god to bilo.
{59423}{59498}Vidimo se kada se vratim|u Bronks. Entoni.
{61285}{61325}To jebeno sranje smrdi.
{61388}{61470}Ne ûelim da ti nareujem,|ali reöi se te glave.
{61498}{61545}Niko drugi se ne ûali.
{61575}{61628}Moûda bi trebao da sluöaö svoje.
{61638}{61705}Medicinski savet, Kleone.|Reöi se toga.
{61715}{61775}Zaveûi, Dok.|Pojma ti nemaö.
{61790}{61860}Jebi se. Smrdi kao|u vreÊi punoj öupaka.
{61875}{61982}Niko od nas nije ni najmanje|ozleen otkada to imam.
{62010}{62057}Ovo glava nam je amajlija.
{62093}{62170}Ne. Ovo nam je amajlija.
{62193}{62273}Ako nemaö niöta protiv, ja|sam za to da se toga reöimo.
{62278}{62370}Kleone, zaboravi to.|Ta glava smrdi ko avo.
{62375}{62440}Ovo je na stvari naredniËe;
{62478}{62555}Reöite se te glave|öto je pre moguÊe,
{62563}{62620}ili Êete pred vojni sud.
{62668}{62710}Jasno?
{62993}{63038}Kobra. Ovde Delta 6.
{63053}{63113}Ovde Delta 6.|Primamo poruku.
{63180}{63223}Sada smo u pravoj nevolji.
{63225}{63288}Upravo sam nam pokopao sreÊu.
{63305}{63365}Sluöajte. Promena misije.
{63368}{63470}Patrola je naöla puno oruûja|u selu kilometar i po odavde.
{63475}{63530}éele da ih ispitaju tamo.
{63538}{63623}Betankur, ti najbolje|govoriö vijetnamski.
{63628}{63665}Dakle, idemo tamo.
{63715}{63750}Gde je D'Ambrozio?
{63780}{63815}Iöao je da sere.
{63828}{63888}Kada?|-Kada je Kleon kopao rupu.
{63898}{63980}Nisi iöao sa njim?|-Ne voli druötvo kada sere.
{64028}{64068}Idemo da ga naemo.
{64320}{64360}Oh, jebiga.
{64375}{64410}Dok.
{64423}{64518}U krug. D'Ambrozio,|öta si radio?
{64525}{64570}BiÊe ti dobro.|Dok Êe se pobrinuti za tebe.
{64780}{64832}Jedino mu mogu|dati ovaj morfijum.
{64957}{65030}Evo, Dok. Uzmi moj|ako nije dovoljno.
{65043}{65100}Jesi li lud? Joö jedna|doza bi ga ubila.
{65372}{65415}äta je to, Kertise?
{65433}{65463}Neöto o...
{65472}{65530}Crnci, idite kuÊi.
{65558}{65603}Ovo nije vaö rat.
{65605}{65680}Reöi se tog|komunistiËkog sranja.
{65750}{65800}Tako je.
{65803}{65850}Kertise, pritisni ovde.
{65853}{65890}Moramo da ga odnesemo do baze.
{66025}{66065}Spasi me, Kertise.
{66073}{66155}Niöta se ne brini.|Mi smo ekipa, brate.
{66173}{66243}PobrinuÊemo se za tebe.|-Molim te.
{66258}{66323}Joö samo malo.|Skoro smo stigli.
{66355}{66385}Ubij me.
{66450}{66485}Ubij me.
{66535}{66590}UËinio bih to za tebe.
{66603}{66648}UËinio bih to za tebe, Kertise.
{66670}{66724}Helikopter. Ovdje Kobra.|Prijem.
{66909}{66941}BiÊeö dobro.
{66949}{66991}Uskoro Êe doÊi pomoÊ.
{67026}{67059}UËini to.
{67179}{67226}Misliö da ne mislim ozbiljno?
{67274}{67321}Ne mogu ovakav kuÊi.
{67351}{67379}äta to govori?
{67391}{67429}U bunilu je.
{67579}{67611}Molim te.
{67684}{67729}Ovde Kobra.|»ekamo vas. Prijem.
{69084}{69131}Ispaljujemo petardu.|Prijem.
{69139}{69206}Ispali. Spremite Ëoveka|za medicinsku pomoÊ!
{69484}{69551}Kada je izdahnuo?|-Pre par minuta.
{69606}{69676}Bolje je otiÊi,|nego kuÊi doÊi sjeban.
{69744}{69781}Tako je.
{71289}{71344}Sranje! Dole!
{71464}{71521}Ostanite dole!|-UbiÊu te, majmune!
{71526}{71556}Uzvratite vatrom!
{71589}{71621}Hajde, sredite ih!
{71759}{71811}Skip, pucaj na njih!
{71834}{71871}Misija otkazana!
{71881}{71934}Idemo! Nazad u bazu!
{71946}{72014}Fergusone, poËni|konaËno da pucaö!
{72071}{72121}Pokrivaj me, Skip!
{72136}{72161}Dugan!
{72231}{72261}Dugan!
{72569}{72654}Skip, saberi se! Idemo!
{72659}{72741}Idemo odavde, Leone!|-Kobra, povlaËite se!
{72761}{72811}Brûe! Brûe!
{72819}{72891}Brûe! -PovlaËenje! Brzo!
{73054}{73136}6 MESECI POSLE
{73241}{73311}Posebnu fotku za Skipija.|Ide kuÊi.
{73316}{73404}Tako je dobro. -Skip,|Entoni, dajte ruke.
{73601}{73641}Slikaj jednu ovakvu.
{73669}{73721}Svi se pribliûite.
{73734}{73771}Ovo je Kobra!
{73789}{73851}Jedinica Kobra!|-Kobra, ËoveËe.
{73904}{73939}Kobra je spremna?
{74219}{74319}SEVEROISTO»NI BRONKS, 1973. g.
{74774}{74836}»ekaj malo.|Neka brojaË ide.
{75005}{75040}Ispravi se, marinËe!
{75143}{75175}On ti je prijatelj?
{75193}{75245}Ako jeste, daÊu ti popust.
{75260}{75288}Ne, ËoveËe.
{75370}{75403}Sranje.
{75438}{75493}Vidi ko se vratio|u jebeni svet.
{75508}{75553}Pogledaj ovog ovde.
{75588}{75620}Pogledaj se.
{75625}{75708}Ovo je super uniforma.|Vidi pruge. NatporuËnik si?
{75723}{75753}Ne.
{75758}{75840}Sa tom uniformom,|imaÊeö sve ûenske.
{75843}{75900}Pogledaj ovog, ËoveËe.
{75953}{75993}Uzmi mi cigarete.
{76020}{76073}Moram da sredim neke stvari.
{76105}{76145}Budi zdrav.
{76228}{76273}Kako si, brate?
{76280}{76315}Vratio sam se, ËoveËe!
{76413}{76450}Prijatelju moj.
{76573}{76603}Hej, Lutere!
{76613}{76673}Reci sestri da Êu kasnije doÊi.
{76798}{76843}Kvart se menja.
{76855}{76948}Joö uvek je dobro mesto.|Belci odlaze.
{76990}{77060}Neki dan sam video Huanitu.
{77073}{77125}Super izgleda.
{77140}{77165}Stvarno?
{77208}{77273}Idi kod nje. Idi vidi Êerku.
{77293}{77363}SeÊaö se velikih uöiju|koje si imao kao mali?
{77368}{77430}Ona ih ima. Tako|znam da je tvoja.
{77478}{77545}äta je sa Dûoom? Radi li?
{77553}{77630}U poöti.|Skoro puno radno vreme.
{77638}{77693}Mora da nahrani puno usta.
{77723}{77765}äta je sa tobom? Kako si?
{77788}{77813}Ja?
{77823}{77895}Dobro sam. To sam ja, Skipi.|Joö uvek sam svodnik.
{77958}{78000}Treba ti love?
{78013}{78080}Dobio sam dosta na odlasku.
{78090}{78160}Imam novac za|ökolarinu svaki mesec.
{78168}{78233}MeseËni Ëek za veterane.
{78238}{78335}Plus medicinska novËana|pomoÊ do kraja ûivota.
{78353}{78435}Moram samo da idem|do sanduka sa poötom.
{78440}{78535}Kako si dobio medicinsku|pomoÊ? Ti nisi nesposoban.
{78543}{78605}Neöto me je tamo primilo.
{78680}{78740}Krvne Êelije su mi oöteÊene.
{78753}{78825}Katkad se noÊu budim|u hladnu znoju.
{78863}{78958}To nije zbog heroina.|On mi nikad nije naökodio.
{78968}{79035}Puno veterana to ima.|-Ne znaju öta je?
{79048}{79085}Ozbiljna stvar.
{79123}{79155}Prokletstvo.
{79183}{79235}HoÊeö li kod mene?
{79258}{79305}Ne, idem.
{79318}{79388}Ti si kod kuÊe. Imamo puno|vremena da se zabavljamo.
{79538}{79568}Brate.
{79570}{79633}Idi do mame. -Idem.
{79638}{79715}Dobra guza.|Brinuo sam za nju dok te nije bilo.
{79718}{79765}UdariÊu te.|Ne priËaj tako.
{80393}{80435}Jesi li dobro?
{80553}{80595}Zaöto me ne pogledaö u oËi?
{80610}{80650}Nisam te videla 4 godine.
{80875}{80930}äta si tamo radio?|Kako je bilo?
{80938}{80968}Sluöaj,
{80975}{81023}radije sada ne bih o tome.
{81038}{81093}MoraÊeö nam neöto reÊi.
{81098}{81183}Mnogi momci koji su tamo|otiöli postali su zavisnici.
{81185}{81220}Sluöaj,
{81223}{81340}to je bila posebna jedinica.|To bi nas koötalo ûivota.
{81343}{81390}O tome i govorim.
{81395}{81505}Ako imaö loöe navike,|postoje mesta koja pomaûu.
{81510}{81595}Nemam loöih navika, mama.|Osim malo ubijanja.
{81633}{81685}Za svoju zemlju, naravno.
{81723}{81803}Uzmi joö malo ovog.|Baö je dobro.
{82280}{82400}Kako si, mladiÊu?|Dugo se nismo videli.
{82408}{82448}Kako si?
{82483}{82563}Kako si?|Dugo te nisam video.
{82623}{82690}éiveo, ËoveËe. Kako si?
{82798}{82895}Kako je? Ja igram sledeÊu,|a znaö da je to moj sto.
{83038}{83080}Ne poznajemo li se odnekuda?
{83180}{83230}Dûo, prijatelju, kako je?
{83253}{83303}Pogledaj se.|-Kako si?
{83308}{83361}Kako je?
{83374}{83419}Ne mogu da verujem|da si to ti.
{83424}{83481}»uo sam da si bio ranjen.
{83496}{83604}Bio sam u razminirivanju|i raznelo mi ruku.
{83664}{83786}NauËili su me sve|moguÊe o eksplozivima.
{83819}{83884}Pogledaj se. Imaö decu.
{83899}{83966}Idi do Kirbija. Pozadi je.
{83971}{84006}Idemo pozadi. Joö je tamo?
{84069}{84111}Kirbi uûiva tamo.
{84129}{84179}Ko je to, jebi ga?|-Ja sam!
{84184}{84231}MladiÊu! Kako si?
{84239}{84309}Niki, kako je?|-Kirbi je pozadi.
{84316}{84354}Taj deËko me pogledao i rekao:
{84361}{84449}Kada je skinula gaÊice,|bila je to prava öumica.
{84541}{84589}Kako je, natporuËniËe?
{84696}{84749}Vratio si se?|-Da, jesam!
{84774}{84809}MladiÊu!
{84824}{84866}Kako si?
{84874}{84924}Doi ovamo, momËe.
{85051}{85129}Svuda sam traûio posao.
{85169}{85246}Ljudi zaboravljaju|da si skoro poginuo.
{85304}{85336}Sluöaj, Kirbi,
{85379}{85456}mislio sam ponovo|da radim za tebe.
{85469}{85516}äta? Radiö za mene?
{85531}{85599}Da. Znaö, kladionica,|kao nekada.
{85664}{85716}Murja mi je prekinula posao.
{85734}{85811}Kako su to mogli da urade?|PotplaÊivao si ih.
{85829}{85866}Murja je pohlepna.
{85889}{85996}Ovo je njujorköka murja,|najpohlepnija i korumpiranija.
{86054}{86086}Pa sam prekinuo.
{86094}{86159}Radije Êu jesti|maËja govna.
{86169}{86244}NeÊu se muËiti da öaljem|njihovu decu na faks.
{86289}{86321}Shvatam.
{86359}{86414}Ovo mesto nikada nije|puno zaraivalo.
{86454}{86544}Snalazim se. Preûivljavam|kao i svi drugi.
{86671}{86711}BiÊe sve u redu.
{86741}{86786}Za preûivljavanje.
{86816}{86864}Nadam se, ËoveËe.|Nadam se.
{86951}{86994}Bojiö se krvi?
{87009}{87071}Video sam je dosta|u zadnje 3 godine.
{87139}{87251}Entoni Kertis. U rodu|si sa glumcem Tonijem?
{87384}{87461}Druge je boje koûe, zar ne?|-Da, belac je.
{87466}{87546}I zvao se ävarc, a ne Kertis.
{87576}{87659}Znaö li öta o mesarstvu?|-Brzo uËim.
{87666}{87701}Evo, stavi ovo.
{87746}{87794}Uzmi ovo.
{88408}{88443}Huanita je tu?
{88450}{88493}Ne, ali vratiÊe se...
{88558}{88598}Uskoro.
{88665}{88725}Tamo Êeö stajati ili Êeö uÊi?
{88735}{88773}UÊi Êu.
{88850}{88895}Pogledaj se, devojko.
{89010}{89063}Mislila sam da Êeö|preÊi u komuniste.
{89080}{89123}Ne ja.
{89145}{89200}Da si pametan, uradio bi to.
{89268}{89323}Ne znaö o Ëemu govoriö.
{89343}{89433}Nisi ti kriv öto ti je|Amerika isprala mozak.
{89498}{89555}Barem si se vratio ûiv.
{89578}{89633}Zdravo, kako si?
{89638}{89705}To bi bilo lepo Ëuti pre|ovog politiËkog sranja.
{89775}{89808}Dobrodoöao kuÊi.
{89858}{89903}I dobrodoöao u revoluciju.
{90022}{90081}ZnaËi, ovo je Sarino.
{90251}{90294}Je li pametna?
{90359}{90401}Uveri se sam.
{90491}{90551}Zdravo svima. Izvinite|öto kasnim. U saobraÊaju je
{90556}{90609}bilo straöno.
{90744}{90804}U redu. Tako...
{90834}{90869}Tako...
{90881}{90926}Idi da se igraö sa kockama.
{91471}{91536}Ne, Huanita. »itav sam.
{91716}{91759}éelim da nekog upoznaö.
{91766}{91846}Doi ovamo, Sara.|Doi mami. Dobra curica.
{91861}{91919}Doi ovamo. Pogledaj ovo.
{91949}{92001}To je tata. Reci zdravo.
{92006}{92056}Ovo je Sara Mari Kertis.
{92069}{92099}Zdravo.
{92116}{92169}Primi je. Tvoja je.
{92591}{92661}To je to?|-Da, to je dom.
{92736}{92789}Pogledaj uspavanu lepoticu.
{92831}{92896}Ne mogu da verujem|kako je divna.
{92911}{92959}Takva je na mamu.
{93084}{93121}Znaö, Huanita,
{93151}{93219}samo hoÊu da ti kaûem|da si mi nedostajala.
{93241}{93269}Puno.
{93279}{93321}Misliö da to ne znam?
{93336}{93409}Bitno je da si sada ovde.
{93476}{93516}Doi ovamo.
{93966}{93996}Zdravo, devojËice.
{94024}{94056}Zdravo, Kati.
{94129}{94191}Doöao sam ranije,|ali nisi bila kod kuÊe.
{94261}{94346}Imala sam nastavu veËeras,|a onda sam iöla kod mame.
{94421}{94464}Zaboravio sam da je subota.
{94514}{94571}Vidim da moja|curica ovde spava.
{94601}{94644}Naigrala se.
{94721}{94761}Upoznaj...
{94766}{94796}Pogledaj.
{94814}{94854}Imam neöto za Saru.
{94871}{94911}Kupi joj neöto lepo.
{94985}{95052}Rekla sam ti da|prestaneö da je maziö.
{95202}{95247}Neko i to mora.
{95287}{95357}Kati, ûelim da|upoznaö Entonija.
{95577}{95657}StaviÊu je u krevet.|Raskomoti se.
{96317}{96365}Neöto za piÊe?
{96397}{96437}Bolje da idem.
{96447}{96487}Ali tek si doöao.
{96500}{96565}Moûda oËekujeö druötvo.
{96592}{96645}Niko ne dolazi, Entoni.
{96655}{96700}Mislim da bi|ipak trebao da odem.
{96815}{96845}Entoni,
{96877}{96935}izlazila sam sa Katijem.|To ûeliö da Ëujeö?
{96950}{97000}To mi je jasno|dao do znanja.
{97007}{97072}U Ëemu je onda problem?|-Problem?
{97147}{97200}Daje ti 200 dolara?
{97212}{97257}Pitaö u Ëemu je problem?
{97262}{97302}OËigledno, ni u Ëemu.
{97307}{97347}Ne prosuuj me.
{97377}{97442}Vodiö svodnika oko moje Êerke?|-On nije svodnik.
{97455}{97512}Da ti je stalo do Êerke,
{97517}{97580}pisao bi mi kad sam|ti poslala sliku.
{97585}{97670}Ne kritikuj me zato öto|ûivim. Nisi ûeleo sa mnom.
{97740}{97787}äta sad?
{97815}{97845}OtiÊi Êeö?
{97887}{97915}Baö sranje.
{98107}{98140}Doi ovamo.
{98145}{98210}Molim te. Doi ovamo.
{98687}{98715}Prokletstvo!
{99005}{99042}Sredi se, kauboju.
{99055}{99125}Zaöto uvek tako govoriö?
{99225}{99297}Zato sam ga tukao|kada je bio dete.
{99305}{99352}Uvek mudruje.
{99557}{99627}Sada se ponaöaö kao|mornariËki ratni junak.
{99677}{99710}Znaö öta mislim?
{99727}{99852}Bio si budala öto si|iöao da se boriö u rat belaca.
{99862}{99900}Tako je.
{99937}{99979}äta si dobio na povratku?
{100032}{100094}Niöta.
{100144}{100209}Naravno, imaö lepu Huanitu.
{100241}{100336}Zaöto me tako gledaö?|»estitam ti na ukusu.
{100464}{100501}Znaö, naravno,
{100514}{100569}najveÊeg momka od svih,
{100579}{100634}mog öefa, Katija.
{100701}{100764}Mislio sam da Êeö se setiti.
{100801}{100881}äevio ju je dok si|ti bio u Vijetnamu.
{100899}{100929}Jebi se!
{100996}{101034}Kretenu!
{101091}{101144}Ne, ne. Treba ga istuÊi.
{101191}{101246}Jebi ga! Sada tako govori!
{101276}{101306}Zaveûi, jebem ti!
{101344}{101386}Kreteni jebeni!
{101389}{101429}UbiÊu te, jebem ti!
{101446}{101504}Dosta je.|-Izvadi noû!
{101516}{101561}Dosta je. Dosta je.
{101576}{101626}UbiÊu ga!|-Dosta je!
{101639}{101674}Smiri se, momËe.
{101679}{101741}Pusti me!|-VeÊ je sreen.
{101751}{101784}Sranje.
{101791}{101826}Idemo na vazduh.
{101854}{101899}Ne treba mi jebeni vazduh.
{101929}{101969}Gotovo je.
{102506}{102540}Sranje!
{102559}{102635}Evo aviona. Idemo.
{102693}{102729}RazmaziÊeö je.
{102760}{102859}I ovo u tvom trbuhu. -Ne|trebaju mi razmaûena deca.
{102890}{102931}Zaöto ne?
{102939}{103018}Nije dovoljno crne dece|razmaûeno. Zar ne, Sara?
{103029}{103074}Imaö pravo.
{103124}{103159}Sedi.
{103226}{103292}Velika curica.|Doi ovamo.
{103331}{103362}Doi.
{103411}{103440}Pogledaj se.
{103476}{103515}Debela curica.
{103536}{103584}Da vidimo öta imamo ovde.
{103606}{103670}Mislim da Êemo imati deËka.
{103717}{103779}Da, hajde, moraö da budeö deËko.
{103789}{103834}DeËko. DeËko.
{103856}{103890}Entoni Junior.
{103894}{103963}Vidiö li? To je snaga uma.
{103976}{104026}éelimo deËaka.
{104081}{104138}Moûeö li da poûeliö|bolji posao?
{104226}{104284}Moûeö li da poûeliö|da prestaneö da pijeö?
{104290}{104339}Hajde, Huanita, ne zapoËinji.
{104363}{104410}Trebali bis da se zabavljamo.
{104584}{104626}Sluöaj, Huanita,
{104656}{104712}naÊi Êu dobar posao.
{104734}{104804}Znaö koliko dugo|pevaö istu pesmu?
{104834}{104888}Ovo je stvaran svet.
{104899}{104963}Nema besplatnih obroka|kao u marincima.
{105028}{105112}Sluöaj me, nije niöta bilo|besplatno u marincima.
{105116}{105185}Zaradio sam svaki obrok|i svaki jebeni dolar.
{105300}{105345}Sve Êe biti dobro.
{105425}{105477}SledeÊe nedelje biÊe 5 meseci.
{105487}{105552}Onda viöe ne mogu|da radim kao bolniËarka.
{105566}{105610}Rekao sam da Êe|biti sve u redu.
{106640}{106687}HoÊete malo spida?
{106730}{106791}MiËi se s tim sranjem?
{106795}{106840}Zaöto ne prestaneö s tim?
{106846}{106900}Ne moûeö naËas biti Ëist?
{106911}{107005}Siguran si da podiûu gotovinu?|-Gotovinu, brate.
{107015}{107060}Jednom na mesec.
{107062}{107130}Staju kod poöte i onda|idu u Vaöington.
{107155}{107249}U Vaöington, gde uniötavaju novac.|Moûeö li da verujeö?
{107284}{107385}Stare novËanice. Katkad i par miliona.|-Koliko straûara?
{107387}{107487}»etiri. Dvojica napred,|jedan pozadi, sa piötoljima.
{107495}{107525}Drugi
{107531}{107586}ima puöku, ËoveËe.
{107591}{107639}Misliö da moûemo da ih sredimo?
{107720}{107752}Nisam siguran.
{107791}{107837}»etiri straûara sa oruûjem?
{107865}{107900}NabaviÊu oruûje.
{107930}{107966}SkupiÊu novac.
{107974}{108080}Ali ti Êeö isplanirati. -Imaö|medalje zbog ubijanja ljudi.
{108085}{108157}Bio si kao Dûon Vejn.|-Dogovor je takav.
{108170}{108224}Da, sav taj novac.
{108335}{108364}Entoni?
{108380}{108410}Slaûeö se?
{108607}{108646}Nazdravimo svejedno.
{108881}{108921}»uj, ËoveËe...
{108990}{109037}Skloni tu prokletu stvar.
{109050}{109115}Piromanu jedan.|Peöke Êeö kuÊi.
{109120}{109199}Smiri se. NeÊu ti zapaliti|auto. Barem ne joö.
{109501}{109536}Zaboravi, Huanita.
{109557}{109585}Pazi se.
{109807}{109846}U Ëemu je problem, Entoni?
{109871}{109941}äta je?|To je zato öto sam trudna?
{109952}{110033}Ne budi smeöna.|-Onda, u Ëemu je stvar?
{110163}{110197}Reci mi. äta je?
{110328}{110375}Rekla sam ti|da ostaviö alkohol.
{111022}{111108}Entoni, duöo.|To sam ja. Sve je u redu.
{111233}{111297}To je bio samo san.|Samo san.
{111503}{111566}Ovo je najbolji deo.|Uûivajte.
{111717}{111758}Moramo da razgovaramo.
{111860}{111920}äta se deöava?|-Dobar si Ëovek.
{111938}{112031}Nemam vremena za priËu.|Moram da naseËem puno mesa.
{112083}{112122}Zatvaram mesaru.
{112183}{112247}Trebao sam ti reÊi ranije, ali...
{112256}{112308}Mislio sam da Êe|posao iÊi bolje.
{112347}{112383}Izvini.
{112427}{112461}Izvoli.
{112466}{112522}Ne, sluöaj, Sole... Ne mogu.
{112528}{112592}Ne mogu to da zadrûim.|Moram toga da se reöim.
{112603}{112640}Uzmi.
{113197}{113262}Evo, brate.|Ne daj da te sve to pritisne.
{113291}{113341}Pokuöavam. Pokuöavam.
{113345}{113428}HoÊeö li da se oslobodiö uticaja|belaca? Doi kod nas.
{113472}{113533}Brini se za sebe.|éivi pravedno.
{113633}{113731}NAT TARNER - SPASITE NAäE|DRUäTVO - ISKORISTITE VREME
{114297}{114341}Zdravo, mladiÊu.
{114413}{114447}Doneo si namirnice?
{114500}{114533}Oh, Boûe.
{114555}{114600}Kada sam bio oûenjen
{114622}{114686}voleo sam kuÊi|da donosim namirnice.
{114699}{114745}OseÊao sam se jako dobro.
{114758}{114792}Kao Ëovek.
{114808}{114841}Znaö öta hoÊu da kaûem?
{114894}{114928}Sluöaj, mladiÊu,
{114938}{114997}samo sam svratio da vidim|Huanitu i Saru.
{115022}{115082}Doöao si da vidim moje dete?|Tako?
{115106}{115217}Brinuo sam se za njih|kada si bio u ratu.
{115229}{115283}Zato zasluûujem|malo poötovanja.
{115314}{115353}NeÊu ti lagati.
{115362}{115429}Stalo mi je do Huanite.|Jako mi je stalo.
{115443}{115513}Ali ti si se vratio,|ja sam otiöao.
{115542}{115629}Trebao bi da me smatraö|porodiËnim prijateljem.
{115637}{115744}Ako budeö u nevolji i treba ti|novac, pozajmiÊu ti ga.
{115754}{115792}Zadrûi svoj novac.
{115798}{115826}Sluöaj,
{115832}{115914}znam öta je ponos, ali|ti treba da nahraniö usta.
{115926}{116017}Neöto sam gotovine dao Huaniti|-Dalje od moje porodice.
{116049}{116121}äta si rekao?|-»uo si me, proklet bio.
{116149}{116206}Dalje od moje porodice, jebem ti.
{116251}{116299}Nisam ti neprijatelj, mladiÊu.
{116362}{116394}Ne ûelim nevolje.
{116767}{116851}Vidiö? Pokuöao sam da ti|budem prijatelj, budalo.
{117037}{117069}Iznenaenje, crnjo.
{117139}{117194}Veliki, snaûni marinac.
{117218}{117257}Pogledaj se sad.
{117287}{117332}Puöi ga?
{117346}{117382}Jebeö je?
{117419}{117457}OseÊaö li se kao muökarac?
{117482}{117520}Onako stvarno dobro?
{117571}{117601}Ha, momËe?
{117643}{117721}To nije tako radila pre|tvog odlaska u rat.
{117824}{117887}Sada se tako dobro seksa,
{117914}{117984}a ti ne moûeö ni da|osiguraö obroke.
{118024}{118101}Hajde, BoûiÊ Bato,|otvori usta i liûi ovo.
{118117}{118169}Imam poklon za tebe. Liûi ga!
{118175}{118219}Liûi ga, crnjo!
{118228}{118300}Ubij me, kretenu.|Sad odmah.
{118312}{118357}UËini öta hoÊeö. Pucaj.
{118513}{118571}Imaö sreÊe öto je|ovo liËne prirode.
{118587}{118644}NeÊu te ubiti zbog ûene.
{118676}{118708}Nikada
{118721}{118769}u svom jebenu ûivotu
{118792}{118854}nemoj gristi ruku koja te hrani.
{119029}{119071}Vidimo se, BoûiÊ Bato.
{119264}{119287}Dobro sam.
{119299}{119357}Budi miran.|-Dobro sam, do avola.
{119759}{119799}Vrati mu taj novac.
{119834}{119867}NeÊe ga primiti.
{119894}{119959}Bolje je da mu|vratiö novac.
{119995}{120072}»ak i da to ûelim,|ne bi ga primio.
{120126}{120196}O Ëemu to govoriö;|Ne ûeliö da mu ga vratim?
{120222}{120269}Jebeö to sranje.
{120274}{120352}Izgubio si prokleti posao, seÊaö se?|Treba nam taj novac.
{120357}{120399}Ne njegov.
{120408}{120488}PoËni da donosiö novac|kuÊi kao pravi muökarac,
{120495}{120587}i razmisliÊu o vraÊanju.|Do tada, Êuti.
{120620}{120699}Treba da se sabereö|i prestaneö da se saûaljevaö.
{120735}{120817}Katkad nisi isti kao pre rata.
{120824}{120918}Mislila sam da se vratio|Ëovek kojeg sam volela.
{120976}{121093}Tako dobro mu puöiö|da ti daje novac?
{121121}{121243}äta je tebi? Zaöto si tako paranoiËan?|Ne jebem se sa njim.
{121247}{121290}Ne sad.
{121296}{121402}Ali on dolazi ovamo|i daje ti novac bez razloga.
{121410}{121460}Spavam sa tobom|svake noÊi, zar ne?
{121490}{121564}Znaö, Huanita, to je|jako dobro pitanje.
{121608}{121640}Hajde.
{121647}{121745}Priznaj. Budi iskrena.|Jebeö se sa njim, zar ne?
{121749}{121776}To ûeliö da Ëujeö, Entoni?
{121810}{121870}Dobro. Jebem se sa njim.
{121963}{122029}Pa, Ëije je to dete?
{122102}{122199}Nemoj na to ni da odgovoriö.|-NeÊu da odgovorim.
{122208}{122293}Ti si, Entoni, veliki|marinac bez posla. Znaö sve.
{122304}{122347}Odgovori mi ovo;
{122358}{122451}Ako misliö da toliko laûem,|zaöto si onda sa mnom?
{122458}{122547}Misliö da te ja trebam?|Da mi treba ovo sranje?!
{122552}{122613}Ne moûeö da naeö posao,|neÊeö me jebati.
{122618}{122682}Mogu da te zagrlim samo|posle tvojih noÊnih mora!
{122688}{122785}Zaveûi, jebem ti!|Ne znaö kako mi je!
{122863}{122897}Ne odlazi od mene!
{122902}{122960}Pusti me.|-Ne odlazi!
{122964}{122999}Pusti me!
{123004}{123038}A Sara?
{123043}{123127}UbiÊu te, jebem ti! Nikada me|nemoj zaustavljati. Nikada!
{123133}{123233}UbiÊu te, Huanita!|Ostavi me, jebem ti!
{123903}{123954}Poslali su naöe|muökarce u Vijetnam
{123957}{124058}da se bore za ovu|tzv. demokratiju.
{124117}{124193}Ali kada su se vratili|u Bronks, Bed-Staj,
{124197}{124245}Harlem, Vots itd...,
{124258}{124312}éivot je gori nego ikada.
{124404}{124479}Postoji neöto vrlo|izopaËeno u tome.
{124785}{124862}Vlast ljudima!|-Vlast ljudima!
{125270}{125358}Sreo sam tog momka.|On mi je dao ovaj letak.
{125362}{125409}Mislio sam da doem|da pogledam.
{125413}{125506}Bila si tamo ispred i priËala|o svim tim pravednostima.
{125536}{125578}Ja sam samo studentkinja,
{125581}{125639}koja pokuöava da pokrene ljude.
{125648}{125733}Treba nam viöe od priËe.|Vreme je za akciju.
{125744}{125817}Kakvu? -Revoluciju.
{125828}{125894}»ekaj malo.|Sad te viöe ne pratim.
{125898}{125994}A öta kad doe revolucija|i bude vreme da se uzme oruûje?
{126019}{126064}äta ti znaö o oruûju?
{126109}{126158}Znam da se sluûim kalibrom 45,
{126169}{126203}puökom M-16,
{126211}{126287}.38 i Kalaönjikovim.
{126294}{126344}Kalaönjikovim?
{126469}{126509}Zaöto nam se ne pridruûiö?
{126521}{126587}Puno braÊe iz rata veÊ i jeste.
{126621}{126688}Imam dovoljno ozbiljnih probIema|kojima moram da se bavim.
{126881}{126912}Opusti se.
{126969}{127002}Tako si napet.
{127034}{127084}Moram da zaradim|nekakav jebeni novac.
{127106}{127167}Gotovo je sa mnom|i tvojom sestrom.
{127173}{127231}Ali moram da se brinem za Saru.
{127253}{127314}I za ono dete na putu.
{127344}{127373}Prokletstvo.
{127403}{127498}Sluöaj, u svakom sluËaju,|imam plan za zaradu.
{127514}{127564}Ali to zadrûi za sebe.
{127628}{127703}U 6:15 h kamion|odlazi s poöte,
{127706}{127767}na raskröÊu 149-te|i Grand Konkorsa.
{127770}{127889}Jednom staje pre odlaska|u Vaöington. Ostavlja poötu
{127894}{128012}u Drûavnoj ötedionici na|raskröÊu ulica Nobl i Zapadne.
{128034}{128067}Kirbi,
{128078}{128169}ti sedi u auto za beg na uglu,
{128178}{128221}odakle se sve vidi.
{128223}{128248}Hose,
{128253}{128320}mi Êemo biti iza banke,
{128322}{128391}ispod mesta za utovar kamiona.
{128439}{128492}Dilajla, tvoja pozicija je
{128496}{128556}u kontejneru za smeÊe,
{128559}{128617}taËno nasuprot utovariöta.
{128684}{128717}Skipi,
{128727}{128823}ti budi na 10 m od ulice.
{128839}{128888}Tamo budi na izvidnici.
{128928}{129006}Znamo sve o napadu, jer|smo to sve veÊ prouËili.
{129044}{129081}Ako ikoga uhvate,
{129094}{129159}Êutite, a mi Êemo|vam Ëuvati novac.
{129171}{129242}Jebeö to sranje.|Sada vam kaûem,
{129252}{129280}ako me uhvate,
{129339}{129394}sam Êu se ubiti.|-Spusti to.
{129402}{129506}Treba nam jedan na ulici sa|Skipom. Da pazi drugu stranu.
{129521}{129580}Slaûem se.|-Ne, ËoveËe.
{129589}{129684}Ne treba mi pomoÊ. Vidim|i sam. Previöe nas veÊ ima.
{129692}{129767}Jebeö to sranje, Kirbi.|-Svi verujemo.
{129892}{129948}Mogla bih da uzmem|nekoga iz grupe.
{129952}{130005}NeÊu da upliÊem revolucionare.
{130038}{130094}Moûeö da buljiö u mene|koliko god hoÊeö.
{130103}{130153}Nisam sreÊan ni zbog tebe.
{130157}{130230}Rekao si da nam treba|joö jedan muökarac.
{130240}{130289}Imaö li koga na|pameti, Entoni?
{130309}{130385}Stavimo jednostavno|jebeni oglas u novine!
{130398}{130457}NeÊe ostati dovoljno|novca za nas.
{130474}{130553}BOéJA CRKVA ISUSA|KRISTA ANTIOH
{130605}{130688}Niste znali da vam je|sveötenik kockar? Greönik?
{130757}{130832}Ja sam Ëovek|koji je osakaÊivao!
{130880}{130935}Ja sam Ëovek|koji je ubijao!
{130970}{131068}Svi mi znamo da je to|uËinjeno u Njegovo zlo ime.
{131090}{131138}Njega, koji je
{131145}{131195}izbaËen iz Raja.
{131273}{131348}Znate na koga mislim!
{131385}{131443}Moûe li se Ëuti aleluja|u ovoj Boûjoj kuÊi?
{131445}{131493}Aleluja!
{131535}{131598}Sluöajte, Skip je sa nama.|Dobro?
{131620}{131690}Mogu puno da izgubim|ako ovo ne uspe.
{131713}{131780}SeÊam se da je ubrizgavao|otrov u svoje vene.
{131790}{131860}Pokuöava da se reöi tog sranja.
{131868}{131958}Joö se drogira?|-I joö uvek mu slepo verujem.
{132003}{132043}SeÊaö se zadnje bitke?
{132085}{132118}UkoËio se.
{132135}{132210}Na minut.|A onda se oslobodio.
{132220}{132278}A kada se oslobodio,
{132293}{132398}Dugan je bio mrtav.|-To se moglo desiti svakom od nas.
{132405}{132473}Ili si sa nama, ili nisi.|äta Êe biti?
{132488}{132535}Koliko novca je u tom kamionu?
{132553}{132608}PETAK - 6:27 H UJUTRO
{132898}{133000}BANKA DRéAVNIH|REZERVI U ULICI NOBL
{135981}{136024}Joö uvek imamo 15 minuta.
{136029}{136071}Treba mi joö kafe.
{136081}{136116}Poûurimo.
{136316}{136351}Obezbeenje banke.
{137846}{137901}»ekate autobus broj 11?
{137911}{137946}Da.
{137961}{138019}Mislim da ne vozi ovako rano.
{138046}{138129}Neki dan sam se vozio|u isto ovo vreme.
{138151}{138186}Sigurni ste u to?
{138269}{138301}Dajte da proverim.
{138314}{138394}Nemojte da se gnjavite.|-Nije mi problem.
{138469}{138536}Po vaöoj jakni vidim|da ste bili u borbi.
{138546}{138641}Bio sam marinac. Uvek spreman|da pomognem drugom marincu.
{138771}{138821}Ovde Braun iz patrole.
{138826}{138891}Treba mi provera|voznog reda broja 11.
{138896}{138959}Ovde baza. »ekaj malo.
{138971}{139004}Primio.
{139019}{139059}UËini neöto, Kleone.
{139936}{139998}Zaseda!|-Spusti ga, majmune!
{140855}{140887}äta to...?
{140967}{141000}Sranje.
{141800}{141840}Poûuri, Dûo!
{141842}{141867}Idemo!
{142115}{142145}Prokletstvo!
{143155}{143180}Jebi ga!
{143182}{143212}Sranje!
{143387}{143415}O, sranje.
{143485}{143522}Entoni!
{144342}{144385}Jeste li videli to sranje?
{144390}{144462}äta ti je?|-Video si raznesena vrata?
{144467}{144570}Ne, budalo! Razneo si celi kamion!|-Razneo sam ga.
{144572}{144672}Tako si zajebao ruku zadnji put!|Kretenu!
{144675}{144737}Uhvati öta moûeö pre nego öto izgori.
{144742}{144810}Entoni i Dilajla ovo moraju da vide.|Idem po njih.
{144887}{144957}Moraö ovo da vidiö!|Razneo sam ga!
{144974}{145046}Moraö to da vidiö.|Moraö da vidiö öta sam uradio.
{145133}{145196}Spusti piötolj.|Hajde, Dilajla, diûi se.
{145258}{145298}Poûuri, brate.
{145323}{145361}Moramo da idemo, ËoveËe.
{145388}{145433}Ne mogu da je ostavim.
{145478}{145518}NeÊeö je ostaviti.
{145546}{145586}VeÊ je mrtva.
{147188}{147263}Javi se, 1004.|»ujeö li? Molim odgovor.
{147303}{147358}Treba vam pomoÊ?
{148268}{148321}Bog mi ovo neÊe oprostiti.
{148338}{148376}Sluöaj, sveöteniËe.
{148386}{148453}Sa ovim novcem,|moûeö da kupiö mesto u raju.
{148478}{148521}Tu nemaö pravo, brate.
{148548}{148596}Kupili smo mesto u paklu.
{148658}{148763}»injenica je da sam obeÊao|Bogu da neÊu ovako da greöim.
{148823}{148911}Nisam siguran ûelim li|uopöte taj prljavi novac.
{148958}{148993}Sluöaj, sveöteniËe,
{149018}{149098}smisliÊemo neöto sa tvojim delom.|-Tako je.
{149133}{149226}UzeÊu novac.|-Laûljivi seronjo.
{149278}{149356}Bog Êe naÊi drugi|naËin da se pokajem.
{149398}{149503}Reci mi jednu stvar, Kleone.|Zaöto nisi sredio policajca?
{149516}{149588}Ti si ga ubio.|Mladoga brata.
{149598}{149673}Ti si se ukoËio,|pa sam ja morao, zar ne?
{149678}{149736}UÊutite!
{149771}{149828}Dilajla, ËoveËe. Sranje!
{149851}{149903}Na radiju kaûu da su ubili Dûoa.
{149928}{149963}Zajebali smo.
{149970}{150023}Celi plan je bio zajeban.
{150085}{150165}Nismo niöta taËno uradili.|Sranje.
{150225}{150295}Pobrini se da Hozeov deo dobiju
{150297}{150375}Marisol i njegova deca.|-Jasno.
{150532}{150595}Stvarno si ga zajebao,|narkomanu jedan.
{150600}{150647}Ne krivi mene za svoj zajeb.
{150652}{150727}Rekao sam Entoniju da|neÊu imati posla sa ludim,
{150742}{150785}vraûjim narkomanom!
{150820}{150850}Sluöaö li ti?
{150887}{150955}Sranje.|-Reci joö neko sranje!
{150962}{151060}IzmlatiÊu te, ti sveöteniËki|prevarantski idiote!
{151067}{151142}Prestanite da se ponaöate|kao jebeni klovni!
{151170}{151245}Znate, vi crnje ste smeöni.
{151250}{151345}Tu se tuËete,|a imamo preko 300.000 dolara
{151350}{151427}u pravoj, neoznaËenoj gotovini|koje delimo na 5 delova.
{151447}{151545}Ako ponovo zaboravim gde sam,|deliÊemo na 4 dela!
{151630}{151717}Ne mogu da verujem.|Mislili su da spale sve ovo.
{151730}{151810}Sve ovo sranje!|A crnac ne moûe ni posao da nae.
{151845}{151900}To ti je ameriËka vlast.
{151937}{151975}Pale novac.
{152050}{152132}Policija je izdala|poternicu za napadaËima...
{152165}{152260}Lica obojenih u mrtvaËko belu.|-Kobra, vaö poloûaj.
{152270}{152342}...5 federalnih Ëuvara...|-VeÊ je mrtva.
{152350}{152382}Uradi to.
{152390}{152435}Kada je izbila pucnjava...
{152445}{152512}Ne, budalo.|Razneo si kamion!
{152517}{152562}...smrt 9 ljudi...
{152665}{152742}...ubijen je malopre...|-Neöto je tamo u mene uölo.
{152985}{153017}Zaöto usporavaö?
{153022}{153107}äta je, ËoveËe? Sranje!
{153142}{153177}äta radimo ovde?
{153215}{153255}Pogledaj svu ovu decu.
{153277}{153390}Idemo u klub. -PobrinuÊu se|za tebe. DoÊi Êemo tamo.
{153392}{153470}Ne znaö ih.|-U tome i jeste stvar. Uûivi se.
{153475}{153575}Doite ovamo! -OpljaËkaÊe nas.|-Opusti se. Doite ovamo.
{153582}{153620}Prokletstvo.
{153700}{153752}Svi Êete neöto dobiti.
{153762}{153790}SreÊan BoûiÊ!
{153797}{153847}Da, sreÊan BoûiÊ, klinjo.
{153890}{153957}Skipi, doi ovamo i|prestani da govoriö gluposti.
{153970}{154020}Da, uzmite sve te igraËke.
{154057}{154110}Uzmite jednu.|Poklanjamo ih.
{154115}{154172}BoûiÊ Bata ne ûeli ovamo|da doe jer mogu da ga opljaËkaju.
{154177}{154242}Daj mi to. Uzmi igraËku.
{154302}{154347}Zaöto kradete? Ne kradite.
{154397}{154452}NeÊe doÊi bez|policijske zaötite.
{154460}{154525}Proöle ste mu godine|ukrali jednog irvasa.
{154762}{154820}Idimo i ubijmo tog kretena.
{154847}{154930}Ja i Entoni smo podelili|neke stvari, ali to je sve.
{154935}{155001}Davali ste igraËke i Êurke ljudima,|pa pobegli.
{155036}{155126}Kaûete da moj prijatelj|daje novËanice od 100 $
{155131}{155196}i govori da mu ih je Bog dao?
{155203}{155286}Moj roak tamo ûivi.|Kaûe da se Kleon ponaöa kao budala.
{155293}{155353}CrnaËka budala u javnosti.
{155358}{155441}Kupio je novi Kadilak.|Znaju da ga sebi ne moûe priuötiti.
{155448}{155511}PopriËaÊu sa njim.|-Ne, jebeö priËu!
{155518}{155601}Ubio bih ga pre|nego öto nas izda.
{155608}{155641}Sluöaj, Kirbi...
{155646}{155708}Ja Êu to da reöim.|PopraviÊu to.
{155718}{155756}Dobro.
{155766}{155826}Ako se ti ne pobrineö|za to, ja Êu.
{155853}{155901}Rekao sam da nam|ne treba joö jedan.
{155908}{155971}Eto ti tvog|bezvrednog prijatelja.
{156281}{156331}Sranje, Kleone!
{156396}{156423}Prokletstvo!
{157176}{157263}Evo mladiÊa koji radi stvari|na svoj vlastiti naËin.
{157268}{157401}Prema onome kako ljudi reaguju|na njega, zna öta radi.
{157406}{157488}Pozdravimo velikog AI Grina!
{157663}{157701}Stan 13.
{158158}{158196}Ne miËi se!
{158903}{158958}Evo pedesetica.|-Stavi ih tamo.
{159041}{159111}Joö se oseÊam izmuËenim|zbog svega ovog.
{159116}{159176}Takav oseÊaj niöta ne pomaûe.
{159178}{159233}I nikoga neÊe vratiti u ûivot.
{159238}{159298}Samo se ti brini za sebe.|Moramo da idemo.
{159358}{159391}Imaö sve?
{159408}{159451}Da. Zgrabi tu torbu.
{159576}{159651}To je to, ËoveËe.|To je to.
{159656}{159758}Samo moramo stiÊi do Meksika.|Onda Êemo kupiti vilu.
{159763}{159846}KupiÊemo brod|i jedriti oko zaliva.
{159868}{159967}Samo moramo da odemo. -Moûda Sara|moûe da doe kada stignemo.
{159992}{160045}Pa, sve je moguÊe. Idemo.
{160072}{160154}TrËi, Entoni! Hajde!|Izai pozadi! Beûi, Entoni!
{160224}{160257}Sranje.
{160777}{160812}G. Kertis,
{160824}{160914}sueno vam je i proglaöeni|ste krivim po svim taËkama.
{160924}{160997}Imate li öta da kaûete pre|nego öto izreknem kaznu?
{161079}{161144}Niöta öto kaûem neÊe me izvuÊi.
{161174}{161227}Ali iölo mi je loöe,
{161259}{161324}i uradio sam to da preûivim.
{161399}{161449}Moûda nisam bio u pravu,
{161457}{161519}ali nisam ûeleo da iko nastrada.
{161524}{161629}Molim da uzmete u obzir da je|moj klijent sluûio domovini
{161634}{161712}u marincima.|Bio je u elitnoj jedinici,
{161717}{161792}poËaöÊenoj mnogim|medaljama, ukljuËujuÊi
{161799}{161867}i srebrnu zvezdu za hrabrost.
{161874}{161937}Imao je problema|sa prilagoavanjem...
{161942}{162009}Izvinite.|I ja sam bio u marincima
{162014}{162094}i sluûio sam domovini|u II. sv. ratu.
{162099}{162144}Nisam zavröio.
{162154}{162222}Dobio sam purpurno|srce u Gvadalkanalu.
{162229}{162277}Ovaj mladiÊ je zaboravio neke
{162282}{162382}osnovne stvari;|Ëestitost, odanost i Ëast.
{162392}{162517}U marincima smo to nauËili.|Osramotio je svakog marinca.
{162522}{162559}NeÊu vam dozvoliti
{162564}{162639}da koristite vijetnamski|rat kao izgovor.
{162679}{162752}Entoni Kertis, za svoju|ulogu u ovom zloËinu,
{162759}{162829}u kojem su ubijeni neduûni ljudi,
{162834}{162907}osuujem te na kaznu zatvora
{162929}{163029}u trajanju 15 godina do doûivotnog.|-O, Boûe moj.
{163042}{163094}ZakljuËujem sluËaj.
{163102}{163134}Suenje je zavröeno.
{163147}{163179}Doûivotno?
{163184}{163227}Kako misli doûivotno?
{163229}{163352}Posle onoga öto sam uradio za zemlju?|O Ëemu on to? Jebi se!
{163354}{163397}Jebi se!
{163469}{163532}Udaljite zatvorenika iz suda!
{163552}{163649}Jebi se! Vi niste niöta uradili|za mene! Kreteni jedni!
{163662}{163727}Unesite u zapisnik da je|na sudiju baËena stolica!
{163750}{163999}PREVOD I OBRADA|»EDO FILM - by Lucifer
{164024}{165524}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
