{1}{1}25.000
{26}{176}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{2392}{2462}-Tko ste vi ?| -Mi smo tri mudraca.
{2464}{2532}-äto ?| -Mi smo tri mudraca.
{2532}{2618}-Pa dobro, öto se muvate okolo| po ötalama u dva ujutro
{2620}{2686}-To mi baö i ne zvuËi mudro.
{2688}{2766}-Mi smo astrolozi. | -Doöli smo sa istoka.
{2768}{2822}-Jel' se vi to malo zezate?
{2824}{2870}-Htjeli bismo se pokloniti djetetu.
{2872}{2918}-Moramo mu odati poötovanje.
{2920}{3000}-Poötovanje? Vi ste pijani!|Odvratno !
{3002}{3098}-'Ajde vani ! Vani ! Zasipate me|priËama o orijentalnim gatarama.
{3100}{3156}-Hajde, hajde, vani !| -Ne, ne. Mi ga moramo vidjeti.
{3158}{3239}-Idite i slavite neËije tue deriöte!| -Nas je dovela zvijezda.
{3240}{3292}-Prije Êe biti da vas je,|dovela flaöa. 'Ajdete vani, vani.
{3294}{3344}-Mi ga moramo vidjeti.|Donjeli smo poklone
{3347}{3400}-Vani !| -Zlato, tamijan i smirnu.
{3402}{3472}-Pa zaöto niste rekli ?!Evo ga ovdje.
{3474}{3528}-Oprostite öto je ovdje|malo nered.
{3563}{3650}-A öto je uopÊe smirna? | -To je dragocjeni balzam.
{3650}{3750}-Balzam? Pa zaöto mu uopÊe dajete balzam?| To bi ga moglo izgristi!
{3752}{3828}-äto ?| -Pa to je opasna ûivotinja!
{3830}{3884}-Ne, nije.| -Da, jeste.
{3884}{3950}-To je jako veliko i...| -Ne, to je miomiris.
{3952}{4054}-Pa, postojala je ûivotinja|po imenu balzam... ili sam ja to sanjala?
{4056}{4136}-Dakle, vi ste astrolozi, ne ?|Pa koji je on znak ?
{4138}{4206}-Mmm ?| -Koji je on znak u horoskopu ?
{4206}{4312}-Pa, jarac.| -Jarac, a? Kakvi su oni?
{4314}{4374}-On je Sin Boûji,|naö mesija
{4376}{4422}-Kralj éidova!
{4424}{4504}-Takvi su znaËi svi jarci, ne?|-Ne, takav je samo on.
{4504}{4582}-O, pa to sam i mislila reÊi|inaËe bi ih bilo puno.
{4584}{4662}-Uzgred, kako mu je ime ?| -Brian.
{4662}{4776}-Mi te ötujemo, o Briane|tebe koji si gospodar nad nama svima.
{4778}{4904}-Slava tebi, Briane, i|Gospodu, naöem Ocu. Amen.
{4906}{4956}-Onda, vi ovo Ëesto Ëinite ?|-äto ?
{4958}{5008}-Ovo slavljenje.|-Ne, ne, ne, ne.
{5010}{5082}-Pa, ako ste usput|svratite ponovo.
{5084}{5146}-I hvala puno za|zlato i tamijan.
{5148}{5232}-Ali nemojte se sljedeÊi put previöe|truditi oko smirne, dobro?
{5234}{5292}-Hvala.|-Dovienja.
{5336}{5392}-Pa, zar nisu divni.
{5394}{5474}-A u pivsku bocu...ali ipak...|-Vidi ovo!
{5476}{5534}-Vidi! Vidi!
{5536}{5634}-To je moje!|Hej, pa on je beba! O!
{5936}{5990}-Zaöuti!
{6122}{6174} MONTHY PYTHON-ov
{6178}{6240}- BRIANov   éIVOT -|("Brian")
{6240}{6314}- BRIANov   éIVOT -|("Beba po imenu Brian")
{6354}{6422}" Ona je rasla "
{6424}{6502}" Rasla, rasla i rasla "
{6504}{6582}" Narasla da bi postala "
{6584}{6662}" Narasla da bi postala "
{6664}{6742}" DeËko po imenu Brian "
{6744}{6818}" DeËko po imenu Brian "
{6852}{6944}" On je imao ruke i noge "
{6946}{7024}" I öake i stopala "
{7026}{7085}" Taj djeËak "
{7086}{7188} " »ije ime bijaöe Brian "
{7190}{7266}" I on je rastao "
{7267}{7348}" Rastao, rastao i rastao "
{7349}{7420}" Narastao da bi postao "
{7421}{7499}" Da, narastao da bi postao "
{7502}{7582}" Tinejdûer po imenu Brian "
{7584}{7676}" Tinejdûer po imenu Brian "
{7678}{7758}" I njegovo lice je postalo pikniËavo "
{7758}{7844}" Da, njegovo lice postade pikniËavo "
{7846}{7928}" I njegov glas ogrubi "
{7930}{8010}" I stvar poËe rasti "
{8012}{8089}" Na mladom Briano da bi mogla pokas'ti "
{8090}{8181}" Da on svakako nije "
{8184}{8264}" Djevojka po imenu Brian "
{8266}{8350}" Ne, nije djevojka po imenu Brian "
{8540}{8610}" I poËe se brijati "
{8612}{8676}" I öakom se poËe gladiti "
{8678}{8768}" I htjede cure gledati "
{8770}{8856}" I sasvim popizditi "
{8858}{8936}" »ovjek po imenu Brian "
{8938}{9018}" Taj Ëovjek po imenu Brian "
{9020}{9208}" »ovjek kojeg su zvali Brian "
{9210}{9302}" Taj Ëovjek po imenu..."
{9304}{9524}" Braaa... "
{9812}{9862}JUDEJA|ljeta gospodnjeg 33.
{9998}{10092}SUBOTA POPODNE
{10262}{10342}taman negdje|vrijeme za Ëaj
{10536}{10636}-Blaûeni oni koji znaju|da On je bog
{10638}{10746}-Blaûeni tuûni|jer Êe naÊi utjehu
{10804}{10894}-Blaûeni oni blagi duhom
{10896}{10968}-Oni Êe dobiti Zemlju u vlasniötvo
{11004}{11100}-Blaûeni oni koji su|gladni i ûedni...
{11100}{11168}-...zadovoljenja pravde
{11170}{11232}-Oni Êe biti zadovoljni
{11278}{11364}-Blaûeni oni Ëista srca
{11366}{11426}-Jer Êe vidjeti Boga
{11428}{11502}-Glasnije!|-Psst. Tiho, mama.
{11504}{11618}-Pa ne Ëujem niöta|Hajdemo na kamenovanje
{11620}{11688}-Psst |-Na kamenovanje moûemo iÊi bilo kada.
{11690}{11774}-Ma, hajde, Briane|-HoÊeö li zaöutjeti?
{11776}{11828}-Nemoj ËaËkat' nos.
{11830}{11890}-Nisam ËaËkao nos|Samo sam ga Ëeöao.
{11892}{11956}-»aËk'o si ga dok si se|obraÊao onoj dami.
{11958}{12016}-Nisam.|-Ne diraj ga. Ostavi ga na miru.
{12018}{12080}-HoÊete malo, molim vas?|Ne Ëujem niöta öto govori.
{12082}{12166}-Nemoj ti meni "hoÊete malo"!|ObraÊala sam se svom muûu.
{12168}{12250}-Pa odi razgovarat s njim negdje drugdje|Ne Ëujem prokleto niöta!
{12252}{12300}-Nemoj psovati moju ûenu!
{12302}{12378}-Samo sam je zamolio da zaËepi kako bismo|mogli Ëuti öto Ëovjek govori, Nosati.
{12380}{12464}-Nemoj zvati mog supruga Nosatim!|-Pa kad ima velik nos.
{12466}{12520}-HoÊete li molim vas biti tiho?|äto je to rekao?
{12522}{12578}-Nisam Ëuo kad sam|priËao sa Nosatim.
{12580}{12646}-Mislim da je bilo|"Blaûeni proizvoaËi sira"
{12648}{12720}-äto je to posebno kod|proizvoaËa sira ?
{12722}{12786}-Pa oËito to ne treba|shvatiti doslovce.
{12786}{12854}-To se odnosi na bilo koje|proizvoaËe mlijeËnih proizvoda.
{12856}{12923}-Vidiö, da nije bilo tebe|mi bi smo Ëuli ovo, Nosati.
{12926}{12996}-Hej! Ako to joö jednom kaûeö|razbit Êu ti njuöku!
{12998}{13078}-Bolje sluöaj pozorno. Moûda Êe reÊi|neöto poput "Blaûeni svi nosati"
{13080}{13126}-Ma ostavi ga na miru.
{13126}{13176}-A nisi ti ni tako|loö ökoljkoliki.
{13178}{13230}-Od kuda ste vas dvoje,|iz Nosograda?
{13232}{13302}-Joö jednom prijatelju|pa Êu ti jebati sve po spisku.
{13304}{13384}-Ne laj!|I ne kopaj po nosu!
{13386}{13450}-Nisam mislio kopati po nosu.|Mislio sam ga lupiti.
{13451}{13522}-Jeste li Ëuli ovo? "Blaûeni u votki" | -Votki?
{13523}{13584}-Pa, oËito da Êe naslijediti|neöto ruske zemlje.
{13586}{13654}-Zna li itko kako se zove ?|-NeÊeö ti nikog lupit'!
{13655}{13722}-Lupit Êu ga ako me joö|jednom nazove "Nosati"!
{13723}{13798}-Daj zaËepi Nosati|-E, dobro. Upozorio sam te.
{13800}{13890}-Stvarno Êu te mlatnuti tako jako...|-O, rekao je "krotki".
{13892}{13960}-"Blaûeni krotki"!|O, pa to je baö lijepo, ne?
{13962}{14034}-Drago mi je da Êe i oni neöto dobiti|jer im je ûivot baö grozan.
{14034}{14123}-Sluöaj. Ja samo govorim istinu.|Ti imaö vrlo velik nos.
{14126}{14240}-Hej! Nos Êe biti dva metra razmrskan|po tvojem licu kad zavröim s tobom!
{14242}{14314}-Psst!| -A tko je tvoj razmrskao...Golijatov stariji brat?
{14315}{14370}-O...Dobro.|Ovo ti je zadnje upozorenje.
{14372}{14448}-Ma dajte se smirite.
{14450}{14522}-Glupa kuËka.|Staje mi na put.
{14602}{14678}-Ma hajde, idemo|na kamenovanje.
{14680}{14730}-U redu.
{14784}{14883}-Blaûeni su gotovo svi sa|najmanjim interesom za status quo.
{14884}{14998}-No Isus ne shvaÊa da su upravo|krotki srû problema.
{15000}{15097}-Da, da. Apsolutno, Reg.|Da, razumijem.
{15098}{15204}-Ma hajde, Brian.|Ili Êe ga kamenovat prije no öto stignemo.
{15205}{15273}-U redu.
{15274}{15350}-To je odvratno.
{15350}{15465}-Sve je krivica lika sa velikim nosem|On je sve zapoËeo.
{15468}{15528}-O, mrzim nositi ove brade.
{15530}{15600}-Mama, zaöto ûenama nije|dozvoljeno gledanje kamenovanja?
{15602}{15654}-Tako je zapisano, eto zaöto.
{15656}{15697}-Bradu, gospoo ?
{15698}{15762}-Ma daj, nemam vremena|iÊi na kamenovanje.
{15764}{15810}-Opet mu nije dobro.
{15812}{15862}-Kamen gospodine ?
{15864}{15926}-Ne treba. Ima kamenja tamo gore|posvuda po tlu.
{15928}{15984}-Da, ali nisu kao ovi.|Pogledajte ovog.
{15986}{16050}-Osjetite ovu kvalitetu.|Pravi ruËni rad gospodine.
{16052}{16142}-Pa, dobro. Uzet Êu dva toËkasta|i jedan veliki pljosnati.
{16144}{16196}-Mogu ja dobiti jedan pljosnati mama ?|-Psst!
{16198}{16244}-Oprosti. Tata.|-Dobro.
{16246}{16315}-Dva toËkasta, dva pljosnata|i paketiÊ öljunka.
{16318}{16374}-PaketiÊ öljunka. Danas bi|trebalo biti zanimljivo.
{16376}{16416}-Tko je?|-Lokalni deËko.
{16418}{16458}-O, dobro.|-Uûivajte.
{16906}{16976}-Matija, sine|Deuteronomija iz Gata ?
{16978}{17034}-Da li da kaûem da? - Da.|-Da.
{17036}{17122}-Optuûen si od strane|vijeÊa staraca...
{17124}{17198}-...jer si spominjao uzalud|ime gospodnje...
{17200}{17292}-...te si prema tomu|bogohulnik.
{17294}{17358}-Stoga Êeö biti kamenovan|na smrt.
{17360}{17440}-Sluöajte: dobro sam veËerao...
{17442}{17494}-...i sve öto sam rekao svojoj|ûeni je bilo:
{17494}{17560}"Ova riba bi bila odliËna|Ëak i za Jahvea."
{17562}{17638}-Bogohuljenje! Opet je rekao!
{17640}{17702}-Jeste li ga Ëuli!?
{17758}{17804}-Zaista!
{17874}{17926}-Ima li moûda|ovdje ûena danas?
{18070}{18192}-Dobro. Na osnovu vrijednosti|ovlasti koje mi pripadaju...
{18194}{18266}-Oo! Smirite se!|Joö nismo poËeli!
{18268}{18342}-Dajte!|Tko je bacio to?!
{18344}{18406}-Tko je bacio taj kamen?|Hajde...
{18408}{18458}-Ona je! Ona je!
{18460}{18510}-On je! On je!
{18512}{18566}-Oprostite mislio|sam da je poËelo.
{18568}{18646}-Idi straga!
{18648}{18738}-Uvjek netko...|Gdje smo ono stali...
{18740}{18828}-Sluöajte, mislim da ne bi trebalo biti|bogohuljenje öto sam samo rekao "Jahve"
{18830}{18928}-Samo si pogoröavate|situaciju.
{18930}{19002}-Pogoröavam?|Zar ikako moûe biti gore?
{19004}{19068}-Jahve! Jahve! Jahve!
{19070}{19162}-Upozoravam te!|Ako joö jednom kaûeö "Jahve"...
{19164}{19214}-Dobro...|Tko je to bacio?
{19250}{19304}-Hajde...|Tko je bacio?
{19354}{19406}-On, on, on!
{19408}{19454}-Jesi li to bio ti|-Da.
{19456}{19502}-Dobro.|-Ali vi jeste rekli "Jahve".
{19610}{19674}-Dosta!|-HoÊete li prestati!?
{19676}{19794}-Prestanite! Vidite ovako...|Nitko ne smije nikog kamenovati...
{19796}{19850}-...dok ja ne puhnem|u ovu zviûdaljku!
{19852}{19960}-Razumijete li? Pa Ëak i ako,|neka vam ovo bude savröeno jasno,...
{19962}{20018}-...Ëak i ako taj kaûe "Jahve"
{20180}{20250}-OdliËan pogodak.
{20490}{20584}-Mama, imam li ja velik nos?|-Daj, prestani misliti na seks!
{20586}{20672}-Ma nisam! -Ti stalno o tome:|ujutro, u podne, naveËer...
{20674}{20742}-"Jesu li cure ovakve|jesu li cure onakve"
{20742}{20808}-Je li prevelik|Je li premali...
{20810}{20862}-Izvoli prijatelju.
{20864}{20916}-Blaûen bio gospodine.|-Milostinju siromaönome.
{20918}{21000}-Milostinju gubavcu|-Milostinju bivöem gubavcu.
{21002}{21072}-Prokleti vlasnici magaraca|Svi su isti, zar ne?
{21074}{21134}-Nikad nemaju sitnoga|A, evo prilike.
{21136}{21220}-Udijelite talenat bivöem gubavcu.|-Briöi!
{21220}{21278}-Udijelite talenat|bivöem gubavcu?
{21280}{21344}-Talenat? Pa to je viöe|no öto on zaradi u mjesec dana.
{21346}{21396}-Pola talenta, onda.|-Daj, skloni se!
{21398}{21456}-'Ajde nosati, idemo se cjenjkati.|-äto?!
{21458}{21542}-PoËni s jednim öekelom.|Ja Êu poËeti sa 2000 i zavröit Êemo na 1800.
{21544}{21590}-Ne.|-1750?
{21590}{21638}-Odlazi!|-1740?
{21640}{21710}-Ostavi ga na miru!|-Dobro, dva öekela. Zar nije zabavno, a?
{21712}{21794}-Sluöaj, on ti neÊe dati nikakvu|lovu, zato odjebi!
{21894}{22006}-Dobro. Pola öekela za bivöeg gubavca?|-Jesi li rekao "bivöeg gubavca"?
{22008}{22074}-äesnaest godina izvan zvona|i ponosan sam na to.
{22076}{22138}-Pa öto se desilo?|-IzljeËen sam gospodine.
{22140}{22196}-IzlijeËen?|-Da, prokleto blaûeno Ëudo, gospon!
{22198}{22264}-Pa tko te je izlijeËio?|-Isus, moj gospodine.
{22266}{22326}-TrËkarao sam okolo|gledajuÊi svoja posla...
{22328}{22384}-...kad odjednom doe on|i izljeËi me!
{22386}{22434}-Jednog trenutka sam|gubavac sa obrtom...
{22436}{22484}-a sljedeÊeg moj|posao nestade.
{22486}{22550}-"IzljeËen si prijatelju"|Prokleti dobroËinitelj.
{22552}{22638}-Pa dobro zaöto mu ne odeö i ne|kaûeö da ûeliö opet biti gubavac?
{22640}{22704}-Mogao bih to uËiniti gospon...|Da, pretpostavljam da bih to mogao uËiniti.
{22706}{22796}-Mislio sam ga zamoliti da me uËini malo|öepavim na jednu nogu jedno pola tjedna.
{22798}{22884}-Kuûiö: neöto za prosjaËenje|ali ne gubu, koja je priliËno dosadna.
{22886}{22950}-Brian! Odi ovamo i|pospremi svoju sobu!
{22952}{23026}-Evo ti.|-Hvala gospon. Hvala.
{23028}{23096}-Pola denara?!|Prokleta priËa mog ûivota.
{23098}{23150}-Neke ljude ne|moûeö zadovoljiti.
{23152}{23224}-Upravo to je i Isus|rekao gospon...
{23480}{23556}-O...|-Dobar dan.
{23558}{23630}-Aaa... zdravo ËasniËe...mmm...
{23632}{23710}-Samo trenutak, sad Êu|doÊi, dobro?
{23712}{23802}-äto on tu radi?!|-Brian nemoj zapoËinjati...Idi i pospremi sobu.
{23804}{23864}-Prokleti Rimljani!|-Vidi ovako, Brian,...
{23866}{23926}-...da nije bilo njega|mi ne bismo imali sve ovo.
{23928}{24010}-Ne zaboravi to!|-Mama, mi ne dugujemo Rimljanima niöta.
{24012}{24098}-Pa, to baö nije sasvim tako.|-Kako to misliö?
{24100}{24198}-Paa..znaö kako me ispitujeö o svojem...|-O svojem nosu?
{24200}{24276}-Da. Vidiö, ima razlog tomu|öto je to tako Brian.
{24278}{24324}-Koji je to razlog?
{24326}{24396}-Paa..Pretpostavljam da sam ti|odavno ovo trebala reÊi.
{24398}{24476}-äto?|-Pa,Brian...
{24478}{24552}-...tvoj otac nije|gospodin Cohen.
{24554}{24624}-Pa nisam nikad ni mislio da mi je on otac!|-Ne budi drzak!
{24626}{24682}-Otac ti je Rimljanin, Brian.
{24684}{24758}-Bio je centurion|u rimskoj vojsci.
{24758}{24858}-HoÊeö reÊi da su te silovali?!|-Pa, u poËetku jesu...
{24860}{24954}-Tko je to bio?!|-Zvao se Vragolanus Maksimus.
{24956}{25018}-ObeÊao mi je cijeli svijet, znaö...
{25020}{25088}-Trebao me je odvesti u Rim|i smjestiti u Forum...
{25090}{25142}-...robovi...magareÊe mlijeko...
{25144}{25200}-i onoliko zlata koliko|mogu pojesti.
{25202}{25262}-A onda poöto me je iskoristio...
{25264}{25340}-Bris! Kao ötakor iz vodovoda!|-Bitanga!
{25342}{25418}-Da...tako da sljedeÊi put kad budeö|govorio protiv prokletih Rimljana...
{25420}{25466}-...nemoj zaboraviti da si|i ti jedan od njih.
{25468}{25544}-Ja nisam Rimljanin mama!|I nikad neÊu ni biti!
{25546}{25616}-Ja sam ûuÊo, jevrej|ûidovËina, kukonosi!
{25618}{25733}-Ja sam koöer, mama! Ja sam pjeöak|preko Crvenog mora i ponosan sam na to!
{25832}{25905}-Seks, seks, seks... Samo|o tome razmiöljaju, ha?
{25908}{25986}-Onda, ËasniËe, kako ste mi?
{26022}{26122}KOLOSEUM U JERUZALEMU
{26322}{26372}DJE»JI MATINE
{26396}{26490}-Dame i gospodo,|sljedeÊa borba je...
{26492}{26538}-...izmeu...
{26540}{26652}-...Franje Golijata,|makedonskog razbijaËa beba.
{26654}{26743}-...i Borisa Svojeglavca.
{26798}{26877}-äevini jezici.|VrapËeva jetrica.
{26880}{26983}-Mozak od kanarinca.|Uöke od jaguara.
{26986}{27054}-»ips od vuËjih bradavica.|Navalite dok su tople...krasne su...
{27055}{27142}-Devini pereci, samo pola denara.|Toskanski prûeni öiömiöi.
{27144}{27237}-»ini mi se, Reg, da bilo koja|anitiimperijalistiËka grupa poput naöe...
{27238}{27333}-...mora odraûavati takvo razilaûenje|u interesima unutar svojeg stoûera.
{27336}{27424}-O, odliËno. Francis?... -Da, mislim da|je Judithino stajaliöte vrlo ispravno, Reg,...
{27426}{27474}-...samo ako pokret nikada|ne previdi...
{27476}{27532}-...da je neotuivo pravo svakog Ëovjeka...|-Ili ûene...
{27534}{27572}-...ili ûene, da se|rijeöi njegovih...
{27574}{27616}-Ili njezinih.|-Ili njezinih.
{27618}{27660}-Slaûem se.|Hvala ti, brate.
{27662}{27708}-Ili sestro.|-Ili sestro.
{27710}{27756}-Gdje sam ono stao?
{27758}{27828}-»ini mi se da si zavröio.|-O...Dobro.
{27830}{27898}-Nadalje, uroeno je pravo|svakog Ëovjeka...
{27899}{27972}-Ili ûene...|-Daj zaËepi o ûenama!
{27974}{28050}-éene imaju savröeno pravo|da sudjeluju u naöem pokretu.
{28052}{28106}-Stan, zaöto ti uvijek|govoriö u ime ûena?
{28108}{28146}-Zato öto ûelim biti.
{28198}{28272}-äto?!|-éelim biti ûena.
{28274}{28370}-Od sada pa nadalje, hoÊu|da me svi zovete "Loretta".
{28404}{28472}-äto?!|-To je moje pravo, kao muökarca.
{28474}{28562}-Pa zaöto ûeliö biti|Loretta Stan?
{28564}{28626}-éelim raati bebe.
{28627}{28690}-éeliö raati bebe?
{28692}{28756}-Svaki Ëovjek ima pravo raati|bebe, ako on to ûeli.
{28758}{28826}-Ali ti ne moûeö raati bebe!|-Nemoj me tlaËiti.
{28826}{28910}-Ne tlaËim te, Stan.|Ti nemaö maternicu.
{28912}{28960}-Gdje Êe fetus|sazrijevati?
{28962}{29021}-HoÊeö li ga|drûati u kutiji?
{29094}{29140}-»ujte...Imam ideju.
{29143}{29206}-Idemo se sloûiti da on|zapravo ne moûe roditi bebu,...
{29208}{29287}-...s obzirom da nema maternicu, za|öto nije nitko kriv, Ëak ni Rimljani,...
{29288}{29358}-...no on moûe imati pravo|na raaje djece.
{29360}{29426}-OdliËna ideja Judith.|Borit Êemo se protiv tlaËitelja...
{29428}{29480}-...za tvoje pravo na|raanje djece brate.
{29482}{29548}-Sestro...oprosti.|-Ali u Ëemu je smisao?
{29549}{29626}-äto? -U Ëemu je smisao borbe|za njegovo pravo da raa djecu...
{29628}{29708}-...kad on ne moûe raati.
{29710}{29794}-To je simbol naöe borbe|protiv tlaËitelja.
{29842}{29905}-Simbol njegove borbe|protiv stvarnosti.
{30110}{30178}-Tamo je opasno!
{30680}{30778}-äevini jezici. Vidrini nosevi.|Risova slezena.
{30780}{30833}-Imaö li ljeönjaka?|-Nema ljeönjaka na ûalost.
{30834}{30916}-Imam vrapËeve jetrice, jazavËevu slezenu|-Ne, ne, ne...
{30918}{30980}-Vidrini nosevi?|-Ne ûelim to rimsko smeÊe!
{30982}{31058}-Zaöto ne prodajeö normalnu hranu?|-Normalnu hranu?
{31060}{31126}-Da, a ne te bogatunske|imperijalistiËke svaötarije.
{31126}{31202}-Nemojte me kriviti|Nisam je traûio da prodajem ovo.
{31204}{31254}-Dobro.Daj vreÊicu|vidrinih nosiÊa.
{31256}{31322}-Daj dvije. -Dvije.| -Hvala Reg.
{31324}{31390}-Jeste li vi Judejski Narodni Front?|Odjebi!
{31392}{31466}-äto?|-Judejski Narodni Front!?
{31466}{31546}-Mi smo Narodni Front Judeje!
{31548}{31638}-Judejski Narodni Front!|-Drkadûije...
{31696}{31768}-Mogu li se pridruûiti grupi?|-Ne. Odjebi!
{31768}{31837}-Nisam ja ûelio prodavati ove|stvari. To je samo posao.
{31838}{31926}-Ja mrzim Rimljane jednako kao i svi|-Pssst!
{31927}{32033}-Jesi li siguran?|-Potpuno siguran. Mrzim Rimljane.
{32036}{32118}-Sluöaj, ako se|ûeliö pridruûiti N.F.J.-u...
{32120}{32190}-...moraö istinski mrziti|Rimljane.
{32192}{32264}-Mrzim ih|-O, da? Koliko?
{32266}{32314}-Jako!
{32368}{32418}-Dobro...Upadaö.
{32420}{32492}-Sluöaj. Jedini ljudi koje|mrzimo viöe od Rimljana...
{32494}{32548}-...je jebeni|Judejski Narodni Front.
{32550}{32588}-Da!|-Izdajice!
{32590}{32660}-I Judejski Nezavisni Narodni Front.|-O da! Izdajice!
{32662}{32726}-I Narodni Front Judeje.|-Izdajice!
{32727}{32788}-äto?!  -Narodni Front|Judeje.Izdajice!
{32788}{32850}-Mi smo Narodni Front Judeje!
{32852}{32924}-O...Ja mislio da smo|Nezavisni Front.
{32926}{32982}-Narodni Front!
{32984}{33082}-äto se dogodilo sa Nezavisnim Frontom?|-Eno ga tamo!
{33144}{33214}-Izdajnik!
{33342}{33448}-Au! »ini mi se da Êu dobiti|srËani napadaj.
{33472}{33548}-Apsolutno uûasno!
{33892}{33936}-Kako se zoveö?
{33938}{34000}-Brian. Brian Cohen.
{34002}{34080}-Moûda Êemo imati jedan|posliÊ za tebe, Brian.
{35408}{35504}-äto je ovo sad?|"Romanes eunt domus" ?
{35506}{35580}-"Rimljanin iÊi kuÊa" ?
{35582}{35634}-Tu piöe: "Rimljani idite kuÊi!"
{35634}{35734}-Ne, ne piöe! Kako se|na latinskom kaûe Rimljanin?
{35734}{35786}-Hajde!|-"Romanes" ?
{35788}{35834}-Deklinira se kao?|-"Annus" ?
{35836}{35890}-Vokativ mnoûine od "annus" je ?|-"Anni" ?
{35892}{35958}-"Romani."
{35960}{36022}-"Eunt" ? äto znaËi "eunt" ?|-"IÊi"
{36024}{36074}-Konjugiraj glagol "iÊi".
{36076}{36158}-"Ire, eo, is, it,|imus, itis, eunt."
{36160}{36208}-Dakle, "eunt" je ?
{36210}{36274}-TreÊe lice mnoûine u|sadaönjem indikativu. "Oni idu"
{36276}{36388}-Ali "Rimljani idite kuÊi!" je|naredba, dakle moraö rabiti...
{36390}{36442}-Imperativ.|-A to glasi...
{36442}{36494}-Aooo..."I".
{36494}{36556}-Koliko je Rimljana?|-Aaa! Mnoûina. Mnoûina.
{36558}{36626}-"Ite."|-"Ite."
{36628}{36704}-"Domus" ? Nominativ ?
{36706}{36806}-Idite kuÊi. To je kretanje|prema, zar ne Brian?
{36808}{36854}-Dativ !
{36856}{36904}-Ne, ne dativ!
{36906}{36964}-Akuzativ, akuzativ!
{36966}{37048}-"Domum," gospon. "Ad domum."|-Osim kad "domum" prima...
{37050}{37098}-Lokativ, gospon.|-A to glasi...
{37100}{37152}-"Domum."|-"Domum."
{37154}{37206}-"Um."
{37208}{37254}-Razumijeö?|-Razumijem.
{37254}{37286}-Sad to napiöi stotinu puta.
{37288}{37324}-Razumijem. Hvala gospodine.|éivio Cezar gospodine.
{37326}{37394}-éivio Cezar. Ako ne zavröiö do|svitanja odrezat Êu ti muda!
{37396}{37478}-O, hvala gospodine. Hvala vam.|éivio Cezar i sve ostalo, gospodine.
{37968}{38042}-Zavröio!
{38082}{38174}-Dobro. I nemoj|to viöe raditi!
{38748}{38800}-Hej, prokleti Rimljani!
{39616}{39688}-UÊi Êemo kroz podzemni|sustav za grijanje ovdje...
{39688}{39758}-...gore kroz glavne|primaÊe odaje ovdje...
{39760}{39836}-...i u spavaÊu sobu|Pilatove ûene ovdje.
{39838}{39918}-Kada mu zgrabimo ûenu, obavijestit|Êemo Pilata da je u naöim rukama...
{39920}{39976}-...i proslijediti predmet naöih zahtjeva.
{39978}{40048}-Ima li pitanja?|-Koji su naöi zahtjevi?
{40050}{40100}-Dat Êemo Pilatu dva dana|kako bi onesposobio...
{40102}{40162}-...cijeli sustav Rimske|imperijalistiËke drûave...
{40164}{40220}-...i ako odmah ne postupi tako|smaknut Êemo je.
{40222}{40292}-Odrezati joj glavu?|-Odrezati joj sve dijelove tijela...
{40294}{40366}-...i slati mu ih jednom|u sat vremena, svaki sat.
{40368}{40432}-I naravno, istaknuti da|oni snose...
{40434}{40494}-...punu odgovornost|za njeno sakaÊenje.
{40496}{40570}-...i da neÊemo biti|podloûni ucjeni.
{40572}{40626}-Bez ucjene!
{40628}{40716}-Krv su nam popili, kopilad!|Uzeli su nam sve öto imamo!
{40718}{40808}-I ne samo od nas. Nego i od|naöih oËeva...i od oËeva naöih oËeva.
{40810}{40866}-I od oËeva oËeva naöih oËeva.|-Da.
{40866}{40954}-I od oËeva oËeva oËeva naöih oËeva.|-Nemoj skretati s teme...
{40956}{41042}-I jesu li nam ikad iöta|dali zauzvrat?
{41092}{41154}-Vodovod?|-äto?
{41154}{41206}-Vodovod.
{41206}{41258}-O, da, da|To su nam dali.
{41260}{41318}-I kanalizaciju.
{41320}{41404}-A, da, i kanalizaciju, Reg.|SjeÊaö se na öto je grad ranije liËio?
{41406}{41496}-Da, prihvaÊam, vodovod i kanalizacija su|jedine dvije stvari koje su Rimljani uËinili.
{41498}{41568}-I ceste.|-Da, oËito i ceste...
{41570}{41630}-Mislim, ceste se|podrazumijevaju, ne?
{41632}{41704}-Ali osim kanalizacije,|vodovoda i cesta...
{41706}{41750}-Navodnjavanje.|-Medicinu.
{41750}{41810}-Obrazovanje.|-Da, dobro...To je u redu.
{41812}{41886}-I vino.
{41886}{41964}-Da, to bi nam stvarno nedostajalo,|Reg, ako bi Rimljani otiöli.
{41966}{42058}-Javna kupaliöta. -A sad je |sigurno öetati ulicama po noÊi.
{42060}{42150}-Da. Zacijelo znaju odrûavati red.|Jedino oni to mogu u ovakvom mjestu.
{42206}{42272}-Dobro, ali osim |kanalizacije, medicine,...
{42274}{42350}-...obrazovanja, vina, javnog reda,|navodnjavanja, cesta...
{42352}{42414}-...sustava za svjeûu vodu|i javnog zdravstva...
{42416}{42494}-...öto su Rimljani|ikad uËinili za nas?
{42496}{42590}-Donjeli su nam mir.|-O mir...Daj öuti!
{42860}{42922}-Ja sam siroma' Ëovjek.|Moj vid je slab.
{42922}{42978}-Moje su noge stare i svinute.
{42980}{43028}-U redu je, Matija.
{43030}{43078}-»isto je.
{43260}{43324}-Dobro, gdje je Reg?
{43326}{43404}-O Reg, Reg. Judith je.
{43406}{43502}-äto je bilo?|-Prvi udarac je nanesen!
{43504}{43580}-Je li napisao parolu?|-Stotinu puta...
{43582}{43678}-...pola metra velikim slovima|po cijeloj palaËi.
{43680}{43744}-O, odliËno, odliËno!
{43746}{43816}-Potrebni su nam ljudi od|akcije u naöem pokretu Brian...
{43818}{43876}-...ali prije no öto nam se|pridruûiö, moraö znati sljedeÊe:
{43878}{43940}-Nema niti jednog meu nama|koji ne bi rado otiöao u smrt...
{43942}{44000}-...kako bi oslobodio drûavu|od Rimljana jednom i zauvjek.
{44002}{44080}-Ovaj, ima jedan!|-A, da, ima jedan...
{44082}{44138}-Ali osim njega, mi smo jedinstveni|Jesi li s nama?
{44140}{44204}-Da.
{44206}{44320}-Od sada Êemo te zvati|"Brian po imenu Brian"
{44322}{44394}-Objasni mu napad|na Pilatovu palaËu Francis.
{44396}{44466}-Dobro.|Ovo je plan.
{44468}{44530}-Ovo je palaËa na|Cezarovom Trgu.
{44532}{44600}-Naöa specijalna jedinica Êe priÊi|sa Riblje ulice pod krinkom noÊi...
{44602}{44686}-...i probiti se do sjeverozapadnog|glavnog ispusta.
{44688}{44784}-Ako nas se pita, mi smo|Kanalizacionari na putu na simpozij.
{44786}{44872}-Reg, naö slavni voa|i osnivaË N.F.J.-a...
{44874}{44958}-...Êe biti koordinirajuÊi savjetnik|u glavnom ispustu...
{44960}{45036}-...iako sam neÊe sudjelovati u|teroristiËkoj akciji...
{45038}{45084}-...jer ga muËi kraljeûnica.
{45086}{45138}-Zar ne ideö s nama?|-Solidarnost, brate!
{45140}{45206}-O, da, solidarnost, Reg.
{45208}{45284}-Kad se naemo u kanalizaciji,|toËnost Êe biti od osnovne vaûnosti.
{45286}{45362}-Kasnije naveËer se odrûava rimska|gozba, tako da morate raditi brzo.
{45364}{45434}-I nemojte obuti|sveËane sandale.
{45436}{45526}-Ako ovdje skrenemo lijevo, uÊi Êemo u| memorijalnu kanalizaciju Augusta Cezara...
{45526}{45592}-...i ako nastavimo ravno|dolazimo toËno u hipokaust.
{45594}{45710}-Ovdje je nedavno poploËano,|zato, teroristi, paûljivo s oruûjem.
{45712}{45802}-Sad Êemo biti toËno ispod|Pilatovih primaÊih odaja.
{45802}{45882}-Ovo je trenutak da|se isuËu pijuci.
{47322}{47392}-Psst.|-Psst.
{47780}{47844}-Pokret za Slobodnu Galileju.
{47846}{47920}-Ovaj...hm...Narodni Front|Judeje...ZvaniËnici.
{47922}{47986}-O...|-äto Vaöa grupa radi ovdje?
{47988}{48064}-Kidnapovat Êemo Pilatovu ûenu|odvesti je i prikazati svoje zahtjeve.
{48066}{48136}-Mi isto. -äto?|-To je naö plan.
{48138}{48198}-Mi smo stigli prvi!|-Kako to mislite?
{48200}{48254}-Mi smo se toga prvi sjetili.|-Mi smo!
{48256}{48318}-Da, prije nekoliko godina.|-Mi smo!
{48318}{48376}-Ma nemoj! A jeste li|razradili sve vaöe zahtjeve?
{48378}{48430}-Naravno da jesmo.|-I kako glase?
{48430}{48490}-NeÊu tebi reÊi!|-Ma daj!
{48492}{48558}-Nije u tome stvar. Mi|smo se toga sjetili prije vas.
{48560}{48606}-Niste!|-Jesmo!
{48608}{48684}-Nitkovi jedni!|Mi smo ovo planirali mjesecima.
{48686}{48786}-E baö öteta Buljooki.
{48788}{48854}-BraÊo, mi bismo se|trebali boriti zajedno!
{48856}{48942}-A ne jedan protiv drugog.
{48944}{49026}-Naravno, trebali bismo se|ujediniti protiv zajedniËkog neprijatelja.
{49028}{49088}-Judejskog Narodnog Fronta!
{49090}{49148}-Ne, ne, Rimljana!
{49150}{49208}-O, da, da...
{49208}{49272}-Da, u pravu je.
{49418}{49502}-Dobro... Gdje smo ono stali?|-Htio si me lupiti.
{50052}{50112}-BraÊo!
{50812}{50858}-äto je?
{51582}{51632}-Ti, sretna bitango!
{51634}{51682}-Tko je to?
{51684}{51732}-Ti, sretna,|presretna bitango!
{51734}{51813}-äto? |-Mali tamniËarev mezimac, ha?
{51814}{51898}-Kako to misliö?|-Mora da si mu ubacio par öekela u ruku.
{51900}{51972}-Ubacio mu par öekela?|Pa vidiö da me je pljunuo u lice!
{51974}{52074}-O, öto bih ja sve dao|da meni pljune u lice!
{52076}{52188}-Nekad visim budan po|noÊi i sanjarim kako me pljuju u lice.
{52190}{52258}-Pa to nije baö prijateljski Ëin, ne?|-Joö su me stavili i u okove.
{52260}{52319}-Okove?
{52320}{52410}-Moj san raja je da mi se|dopusti staviti ruke u okove...
{52412}{52462}-...bar na nekoliko sati.
{52463}{52563}-Mora da misle da|sunce sija iz tvoje guzice sinko...
{52564}{52613}-Ma pusti me na miru|Vidiö da nije moj dan!
{52614}{52694}-Nije tvoj dan?|Ja sam ovdje pet godina!
{52696}{52774}-Tek su me juËer objesili|uspravno, zato mi nemoj...
{52776}{52834}-Dobro, dobro...
{52836}{52926}-Mora biti da misle|da si ti SvemoguÊi Gospod!
{52928}{53019}-äta Êe mi uraditi? |-O, vjerojatno Êeö se uzvuÊi sa raspeÊem.
{53020}{53094}-RaspeÊem?!|-Da, to ti je prvi prekröaj...
{53096}{53146}-IzvuÊi s raspeÊem?|-Pa to je...
{53148}{53216}-...najbolje öto su nam Rimljani donjeli.|-äto?
{53219}{53300}-Da, da... Da nema razapinjanja na kriû,|ova bi zemlja bila u prokletom neredu.
{53301}{53370}-Straûar!|-Pribij ga, velim!
{53372}{53446}-Straûa!|-Pribij mu razum!
{53448}{53496}-äto ûeliö?
{53498}{53576}-éelim da me|prebacite u drugu Êeliju.
{53578}{53660}-Aaa!|-Vidi ovo! Prokleta pristranost!
{53662}{53732}-ZaËepi!|-Oprostite.
{53807}{53882}-Pogledaj mene: objesili su|me ovdje prije pet godina.
{53884}{53956}-Svake veËeri me spuste na|20 minuta i onda me ponovo objese...
{53957}{54030}-...öto smatram priliËno u redu|s obzirom na ono öto sam uËinio.
{54032}{54146}-I ako niöta drugo, bar me|je nauËilo da poötivam Rimljane...
{54148}{54242}-...i nauËilo me je da neÊeö|na ovom ûivotu niöta postiÊi...
{54244}{54351}-...ako nisi spreman zapeti|puno radno vrijeme.
{54351}{54413}-Daj zaöuti!
{54416}{54488}-Evo ga.|-Pilat te ûeli vidjeti.
{54488}{54536}-Mene?|-Hajde!
{54538}{54590}-Pilat? Zaöto bi|me on ûelio vidjeti?
{54592}{54663}-Mislim da hoÊe znati|na koji naËin ûeliö biti raspet.
{54666}{54746}-Dobra fora, centurione...|Baö mi se svia.
{54748}{54851}-Zaöuti!|-Dobro, dobro.
{54854}{54946}-Sjajna rasa, |ti Rimljani! Sjajna!
{55366}{55413}-éivio Cezar!|-éivio!
{55414}{55504}-Samo jedan preûivjeli gospodine.|-O. Tuesnite ga o pod.
{55506}{55582}-Kako ste rekli gospodine?|-Tvesnite ga o pod.
{55582}{55630}-O...
{55700}{55780}-Dakle, kako se|zoveö, éidove?
{55782}{55851}-Brian, gospodine.|-Buajan, a?
{55852}{55898}-Ne, ne, Brian.
{55901}{55954}-Au!
{55956}{56026}-Mali uazbojnik ima huabuosti.
{56026}{56082}-äto ima gospodine?|-Huabuosti.
{56084}{56134}-Da, baö je to kanio...
{56136}{56240}-Ne, ne. Huabuost, |neustuaöivost, uz tvunku dvËnosti.
{56242}{56302}-Ovaj, oko jedanaest, gospodine.
{56366}{56451}-Dakle, ti se usuujeö|izvuöiti puepad na nas?!
{56452}{56500}-Na öto, gospodine?
{56501}{56560}-Dvmnite ga centuvione,|jako gvubo!
{56560}{56642}-Aa!|-I da ga tuesnem o pod gospodine?
{56644}{56706}-äto?|-Da ga ponovo tuesnem o pod gospodine?
{56707}{56780}-O, da, tuesnite ga|o pod, molim.
{56782}{56898}-Aaa!|-Dakle, ûidovska bauaba!
{56900}{56951}-Ja nisam éidov,|ja sam Rimljan.
{56951}{57022}-Uimljan?|-Ne, ne, Rimljan.
{57024}{57070}-Aaa.
{57072}{57192}-Dakle, tvoj otac je bio|Uimljan. Tko je on bio?
{57192}{57282}-On je bio centurion u|Jeruzalemskom garnizonu, gospodine.
{57284}{57360}-Stvarno?|Kako se zvao?
{57363}{57442}-Vragolanus Maksimus.
{57508}{57600}-Centuvione, imate li ikoga s|takvim imenom u Vaöem gavnizonu?
{57601}{57652}-Pa, ne, gospodine.
{57654}{57730}-Dakle, zvuËite vlo sigurno.|Jeste li pvovjeuili?
{57732}{57824}-Pa, ne gospodine.|Mislim da je to öala.
{57826}{57924}-Kao, ovaj, Glupius Budalus,|ili Velikus Pimpekus, gospodine.
{57976}{58046}-äto je smjeöno oko|Velikus Pimpekusa?
{58080}{58152}-Pa to je posprdno ime, gospodine.
{58154}{58236}-Ja imam jako dobvog puijatelja u|Uimu pod imenom Velikus Pimpekus.
{58300}{58374}-Tiöina!|Kakva je ovo dvskost!?
{58376}{58458}-Vi Êete jako bvzo dospjeti|u ökolu za gladijatoue...
{58460}{58507}-...ako se budete tako|bezobuazno ponaöali.
{58507}{58590}-Mogu li iÊi sad gospodine?|Aaa!
{58590}{58651}-»ekajte dok Velikus|Pimpekus Ëuje za ovo!
{58651}{58732}-Dobuo! Odvedite ga!
{58734}{58770}-Ali gospodine, on...
{58774}{58819}-A ne! HoÊu da se veÊ sljedeÊi|tjedan boui s uazbjeönjelim zvijeuima.
{58822}{58890}-Razumijem!|Hajde...
{58992}{59102}-NeÊu da mi neki|legionaui zafukavaju puijatelje.
{59146}{59257}-Bi li se joö|tko kikotao...
{59258}{59344}-...kada spomenem|svojega puijatelja...
{59346}{59424}-...Velikusa...
{59426}{59500}-...Pimpekusa?
{59557}{59682}-A ti? Smatraö li|da je uvnebesno...
{59722}{59798}-...kada kaûem...
{59800}{59910}-...Velikus...Pimpekus?
{60382}{60472}-On ima ûenu, znate...
{60474}{60538}-Znate li kako se zove?
{60598}{60678}-Zove se Inkontinencija.
{60742}{60796}-Inkontinencija Guzicorum
{60798}{60854}-Zaveûite!|äto je ovo!?
{60856}{60934}-Dosta mi je ovog|gvubijanskog, uazbojniËkog ponaöanja!
{60934}{61026}-Tiöina! Tiho!|Puetovijski stuaûavi...
{61026}{61119}-Uhvatite ga! Uhvatite ga!|Ispuöite noseve i uhvatite ga!
{63942}{64012}-Ti sretno kopile!
{64380}{64463}-I Ëudoviöte Êe biti|ogromno i crno...
{64463}{64574}-a oËi Êe mu biti crvene|od krvi ûivuÊih biÊa!
{64574}{64644}-A kurve Babilona...
{64644}{64722}-...Êe jahati na|troglavoj zmiji...
{64724}{64842}-...a po cijeloj zemlji|trljat Êe se dijelovi tijela...
{64844}{64951}-Demon Êe nositi|maË sa devet oötrica...
{64951}{65060}-Sa devet...Ne dvije|ili pet ili sedam, nego devet...
{65063}{65176}-...koji Êe podiÊi na sve jadne|grijeönike, kao öto ste vi gospon tamo...
{65178}{65278}-I kurvanje Êe biti|u glavama Adaje...
{65280}{65410}-U to vrijeme Êe biti govorkanja|kako je to otiölo krivim putom...
{65410}{65519}-...ovaj, i bit Êe svi zbunjeni|gdje se zbilja öto nalazi...
{65520}{65592}-...i nitko neÊe stvarno|znati gdje se nalaze...
{65594}{65656}-...one stvarËice...
{65658}{65734}-...sa nekom vrstom baze|od pletiva uz ruËkice.
{65736}{65850}-U to vrijeme, prijatelj|Êe izgubiti prijateljev ËekiÊ...
{65852}{65944}-...i mladi neÊe znati gdje se nalaze...
{65946}{66000}-...one stvarËice koje su|posjedovali njihovi oËevi...
{66002}{66090}-...koje su njihovi oËevi tamo|stavili noÊ prije, negdje oko 8 sati.
{66090}{66182}-Eee, to je zapisano|u Knjizi po ∆irilu.
{66184}{66242}-...u to vrijeme...
{66460}{66532}-Brzo: kol'ko koöta!?|To mi je za ûenu.
{66534}{66606}-Ovaj...20 öekela|-Dobro.
{66606}{66656}-Kako?|-Evo ti.
{66658}{66704}-»ekaj malo!|-äto?
{66706}{66764}-Trebali bismo se cjenjkati.|-Ne, ne, ne, ûurim.
{66766}{66812}-Kako to misliö: ne?|-Nemam vremena.
{66814}{66872}-Onda vrati!|-Ne, ne, pa sad sam ti platio.
{66874}{66956}-Burt, ovaj mali se neÊe cjenjkati.|-NeÊe se cjenjkati?
{66956}{67008}-Dobro. Zar baö moramo?
{67010}{67074}-HoÊu 20 za to.|-Pa upravo sam ti dao 20!
{67076}{67140}-HoÊeö reÊi da to ne vrijedi|20 öekela?  -Ne.
{67142}{67224}-Popipaj kakvoÊu. To nije od tvojih koza| -Dat Êu ti onda 19.
{67226}{67274}-Ne, ne, ne... UËini to kako treba.|-Molim?
{67276}{67320}-Cjenjkaj se na pravi naËin.|Ovo ne vrijedi 19
{67322}{67358}-Pa rekao si da vrijedi 20!
{67360}{67426}-O boûe dragi...|Daj, cjenjkaj se!
{67428}{67486}-Dobro: dat Êu ti deset.|-To je veÊ bolje.
{67488}{67540}-Deset?!|Jel' ti to mene vrijeaö?!
{67542}{67608}-Mene sa jadnom|bakom na umoru? Deset?
{67610}{67678}-Dobro, dat Êu ti 11|-E sad kuûiö.
{67680}{67786}-Da li sam dobro Ëuo?! Jedanaest?!|Pa ovo me je koötalo 12. HoÊeö me upropastiti?!
{67786}{67852}-Sedamnaest?|-Ne, ne, ne. Sedamnaest...
{67854}{67914}-Osamnaest.|Ne, ne. Moraö ponuditi 14 sada.
{67916}{67984}-Dobro. Dat Êu ti 14.|-»etrnaest?! Se ti to öaliö?!
{67986}{68040}-Pa to si mi rekao da kaûem!|-O boûe...
{68042}{68098}-Molim te, reci|mi öto da kaûem!
{68098}{68146}-Ponudi mi Ëetrnaest|-Nudim ti 14
{68148}{68222}-Nudi mi 14 za ovo!|-Petnaest!
{68224}{68304}-Sedamnaest. Zadnja cijena. NeÊu|ni lipe manje makar umr'o na mjestu!
{68306}{68350}-äesnaest.|-Dogovoreno.
{68350}{68400}-Bilo mi je ugodno|poslovati s Vama.
{68402}{68474}-Evo, dodat Êu ti i ovo.|-Ne treba mi, hvala, kao da jesam.
{68476}{68530}-Burt.|-Dobro, dobro...
{68530}{68596}-Dakle, gdje je 16 koje mi dugujeö?|-Pa bio sam ti dao 20!
{68598}{68664}-Ah da. Dakle dugujem ti Ëetiri.|-Ma dobro. U redu je.
{68666}{68724}-Tu su negdje.|-Zadûite 4 za tikvicu.
{68726}{68788}-»etiri? Za ovu tikvicu?!
{68790}{68858}-Pogledaj je! Ako iöta|vrijedi, vrijedi bar deset!
{68860}{68938}-Pa dao si mi ju za dûabe!|-Jesam, ali vrijedi deset.
{68940}{68984}-Dobro, dobro...
{69046}{69102}-Ne, ne, ne, ne|Ne vrijedi deset.
{69104}{69190}-Sad bi se trebao raspravljati:|"Deset za to?! Mora da si poludio!"
{69256}{69338}-A tako...Ima|svega u boûijem vrtu.
{69338}{69386}-Daniel.| -Daniel.
{69388}{69440}-Job.|-Job.
{69442}{69492}-Joshua.|-Joshua.
{69494}{69550}-Judges.|-Judges.
{69550}{69616}-I Brian.|-I Brian.
{69618}{69722}-Predlaûem da se ovih|sedam naöih bivöih braÊa...
{69724}{69806}-upiöu u spisak kao|probni muËenici za naöu stvar.
{69808}{69892}-Podrûavam to, Reg.|-Hvala ti Loretta. Zaöutimo...
{69894}{69994}-BraÊo, neka nas ovo ne pokunji.
{69994}{70076}-Jedna potpuna katastrofa poput ove...
{70078}{70122}-...je samo poËetak!
{70122}{70194}-Njihove slavne smrti|Êe nas sve ujediniti u...
{70194}{70242}-Pazite!
{70498}{70550}-Alo?
{70552}{70602}-Matija?
{70602}{70658}-Reg ?|-Odlazi!
{70700}{70746}-Reg, to sam je, Brian.
{70748}{70798}-Briöi!|-Odlazi odavdje!
{70800}{70848}-Stan !|-Odjebi!
{70848}{70894}-Da, odjebi|-Gibaj!
{70950}{71018}-O, sranje!
{71018}{71066}-Dolazim.
{71178}{71266}-Da, priliËno u to vrijeme|napisano je u knjizi Obadaje...
{71268}{71386}-»ovjek Êe udariti magarca|i magarca svojega neÊaka...
{71458}{71534}-Moje oËi su mutne.|Ja ne vidim...
{71536}{71596}-Jesi li ti Matija?|-Da.
{71598}{71668}-Imamo razlog za sumnju da moûda|skrivate Briana iz Nazareta...
{71670}{71746}-...Ëlana teroristiËke organizacije|Narodnog Fronta Judeje.
{71748}{71814}-Ja? ne.|Ja sam samo siromaöni starac.
{71816}{71864}-Nemam ja vremena|za kröitelje zakona.
{71866}{71922}-Moje noge su sive|na uöi ne osjetim.
{71924}{71972}-Moje oËi su stare i iskrivljene.
{71974}{72022}-Tiöina!|»udna osoba.
{72024}{72074}-Straûa! Pretraûite kuÊu!
{72326}{72386}-Znaö li kaznu koju|propisuje rimski zakon...
{72388}{72436}-...za ugoöÊenje poznatog krinimalca?
{72438}{72484}-Ne.|-Razapinjanje na kriû.
{72486}{72540}-O...
{72542}{72630}-Gadno, ha?|-Moglo bi biti i gore.
{72632}{72690}-Kako to misliö|"Moglo bi biti i gore"?
{72692}{72744}-Pa...mogli bi me izbosti.
{72746}{72830}-Izbosti? To traje sekundu.|Razapinjanje traje satima.
{72832}{72894}-To je spora, uûasna smrt.
{72896}{72972}-Pa, bar si na svjeûem zraku.
{73002}{73048}-Ti si Ëudak.
{73224}{73302}-Niöta gospodine.Nismo|mogli niöta naÊi, gospodine.
{73304}{73406}-Pa, ne brini. Ovo nije zadnji|put da si nas vidio, Ëudak.
{73406}{73466}-Nosati!|-Pazi se!
{73534}{73596}-Uh, imali smo sreÊe.
{73674}{73720}-Oprosti Reg.
{73722}{73776}-Ma u redu je.|éao mu je...
{73778}{73842}-éao mu je öto je doveo|Petu Legiju pravo u naö stoûer!
{73844}{73912}-Pa to je sasma u|redu Brian. Sjedi.
{73914}{74000}-Uzmi keksiÊ, raskomoti se.|Budaletino!
{74002}{74084}-Glupi, kretenoidni, öupljoglavi...
{74262}{74342}-Noge su mi stare i svinute...
{74344}{74390}-Uöi su mi sijede. Da?
{74392}{74468}-Na jednom mjestu nismo|pretraûili. Straûari!
{74470}{74568}-Ja sam jadni starac.
{74570}{74616}-Nos mi je puknut.
{74618}{74676}-Jesi li ikad vidio|razapinjanje na kriû?
{74678}{74734}-Razapinjanje je öala mala.
{74736}{74782}-Nemoj tako govoriti.
{74898}{74952}-Naöli smo ovu ûlicu gospodine.
{74954}{75008}-OdliËno, poruËniËe.
{75010}{75094}-Joö Êemo se vratiti, uvrnuti.
{75152}{75202}-Otvori!
{75204}{75266}-Niste nam dali|vremena da se skrijemo.
{75556}{75646}-U to vrijeme,|zmija Êe napasti...
{75648}{75756}-...rupe svake kuËke...|-...Jumbo jet...
{75858}{75922}-Ne sudite druge ljude...
{75924}{75974}-...ili Êete i sami biti osueni.
{75976}{76064}-äto?|-Rekao sam ne sudite druge ljude...
{76066}{76130}-...ili Êete i sami biti osueni.
{76132}{76178}-Tko, ja?|-Da.
{76180}{76254}-O, hvalam vam lijepa.|-Ne samo vi. Svi vi.
{76256}{76312}-Baö lijepa tikvica.|-äto?
{76314}{76374}-Koliko traûiö za tikvicu?|-Evo ti je.
{76376}{76442}-Dajeö mi je ?|-Da. Uzmite na primjer ljiljane.
{76444}{76496}-Zar se neÊeö cjenjkati?|-Ne. Na polju...
{76498}{76552}-äta nije u redu s njom?|-Niöta, uzmi je.
{76554}{76628}-Da uzmemo na primjer ljiljane?|-Pa... onda ptice...
{76630}{76676}-Koje ptice?|-Bilo koje ptice.
{76678}{76740}-Zaöto?|-Pa.. Imaju li one posao?
{76742}{76788}-Tko?|-Ptice.
{76790}{76836}-Imaju li ptice posao?
{76838}{76922}-äto nije u redu s njim?|-Kaûe da ptice zabuöavaju
{76924}{76994}-Bit je u tome da|je pticama dobro, ne?
{76996}{77064}-Pa, sretno im bilo.|-Da, baö su slatke.
{77066}{77160}-OK. A vi ste puno|vaûniji nego one, dobro?
{77162}{77228}-Pa zaöto onda brinete?|Eto, vidite?
{77230}{77294}-Mene brine öto|ti imaö protiv ptica!
{77296}{77346}-Nemam ja niöta protiv ptice.
{77348}{77418}-Zamislite ljiljane.|-Sad napada cvijeÊe!
{77420}{77490}-Daj cvijeÊu priliku!|-Dat Êu ti jedan za nju..
{77492}{77544}-Tvoja je.|-Dva onda.
{77546}{77602}-Sluöajte, bio je jedan|Ëovjek i imao dvoje sluga.
{77602}{77668}-Kako su se zvali?   -äto?|-Kako su im bila imena?
{77670}{77730}-Nemam pojma.|I dao im je neöto talenata.
{77732}{77798}-Ne znaö?|-Pa to nije vaûno.
{77798}{77848}-Ne zna kako su se zvali!
{77850}{77928}-Zvali su se äimun i Adrijan|-Rekao si da ne znaö!
{77930}{78004}-To zbilja nije bitno. Poanta|je u tome da su to dvoje sluga...
{78006}{78076}-Izmiölja dok priËa!|-Ne, ne izmiöljam.
{78078}{78132}-I on im je dao...|Ëekaj malo, jeli ih je bilo troje...?
{78134}{78190}-O, grozan je!
{78192}{78276}-Pa bilo ih je dvoje ili troje.|-Daj miËi se!
{78416}{78482}-Sluöajte ovo sad!|Blaûeni oni...
{78484}{78538}-Tri!|...koji preobrate susjedove magarce...
{78540}{78630}-...jer Êe smanjiti obujam svojeg trbuha.|-SmeÊe!
{78632}{78710}-I samo Êe oni dobiti...
{78712}{78790}-Samo oni...
{78792}{78882}-...Êe dobiti...
{78926}{78974}-äto?|-Mmm?
{78974}{79038}-Dobit Êe öto?|-O, niöta.
{79040}{79098}-äto si to priËao?|-Niöta.
{79100}{79154}-Jesi, kanio si neöto reÊi.|-Ne, zavröio sam
{79156}{79230}-Reci nam prije no öto odeö.|-Zavröio sam.
{79232}{79288}-Ne, nisi.|-Zaöto nam neÊe reÊi?
{79290}{79354}-NeÊe reÊi!|-Da nije tajna?
{79354}{79422}-Mora biti, inaËe bi nam rekao|-Reci nam!
{79424}{79472}-Pustite me na miru!|-Koja je tajna?
{79474}{79532}-Je li to tajna vjeËnog ûivota?|-NeÊe reÊi!
{79534}{79598}-Da ja znam tajnu vjeËnog|ûivota, ne bih je rekao.
{79600}{79662}-Ostavite me!|-Molim te, samo mi reci.
{79664}{79732}-Mi smo prvi doöli.
{79734}{79796}-Odlazite!|-Reci nam gospodaru.
{79798}{79870}-Je li to njegova tikvica?|-Da, ali je ispod cijene.
{79870}{79922}-Ovo je njegova tikvica.
{79924}{80000}-Deset!|-Ovo je njegova tikvica!
{80002}{80074}-NosiÊemo je za tebe gospodaru.
{80074}{80158}-Gospodaru?|-Otiöao je!
{80160}{80218}-Uznesen je!
{80220}{80270}-Uznesen je!
{80272}{80340}-Devetnaest!|-Nije, eno ga tamo. Tamo!
{80970}{81024}-Vidite! Oo!
{81026}{81072}-Dao nam je znak.
{81074}{81132}-Dao nam je cipelu.
{81134}{81200}-Cipela je znak|Pratimo njegov primjer.
{81202}{81302}-äto?|-Idemo, svi podignite jednu cipelu u ruci.
{81304}{81406}-Jer ovo je znak po kojem Êe se|raspoznavati svi koji njega prate.
{81408}{81468}-Da!|-Ne, ne. Cipela je znak...
{81470}{81546}-...da moramo skupiti cipele|u potpunoj ispunjenosti.
{81548}{81608}-Odbacite cipele|Pratite tikvicu!
{81610}{81682}-Ne, skupimo svi cipele|Dajte...
{81684}{81788}-Ne, to je znak da, poput njega,|ne smijemo misliti na tijelo...
{81790}{81836}-...nego na lice i glavu.
{81838}{81900}-Daj mi svoju cipelu!|-Briöi!
{81902}{81984}-Pratite tikvicu.|Svetu Tikvicu iz Jeruzalema!
{81986}{82074}-Tikvica!|-Uzdignite sandale, jer nas je odredio...
{82076}{82138}-To je cipela!|-To je sandala!
{82140}{82200}-Ne nije!|-Bacite je!
{82202}{82248}-Obujte je|-Maknite se!
{82250}{82312}-Uzmite cipele i pratite ga.
{82454}{82518}-Vratite se! Stanite!
{82520}{82604}-Hajdemo. Hajdemo se pomoliti.
{82632}{82700}-On je doöao k nama...
{82702}{82758}-...kao sjeme ûita...
{83294}{83382}-Gospodaru! Gospodaru!
{83908}{83980}-Hej! Ima li|drugog puta do dolje?
{84010}{84070}-Ima li drugog|puta dolje do rijeke?
{84072}{84150}-Molim vas, lijepo molim pomozite.|Moram stiÊi do...
{84236}{84310}-Au! Moje stopalo! Au!
{84312}{84392}-Psst!|-O, do vraga, do vraga, do vraga!
{84394}{84478}-Oprostite.|-O k vragu! Jebi ga!
{84480}{84534}-Oprostite. Psst!|-Nemoj me uöutkivati!
{84536}{84610}-Osamnaest godine potpune|tiöine i sad me uöutkujeö!
{84610}{84686}-Kako?|-Drûao sam zavjet 18 godina...
{84688}{84786}-Niti jedan prepoznatljiv artikuliran|zvuk nije preöao preko mojih usana.
{84786}{84848}-Moûete li biti tiho|sljedeÊih pet minuta?
{84850}{84914}-Sad nije vaûno|Mogao bih se malo izûivjeti.
{84914}{84982}-Zadnjih 18 godina|ûelim uzviknuti...
{84984}{85048}-...i pjevati svoje|ime na glas!
{85050}{85100}-Psst. Psst!|-O! éiv sam!
{85102}{85176}-"Hava nagila, hava nagila"
{85178}{85246}-"Hava nagila"
{85248}{85336}-O, ûiv sam, ûiv sam!|Zdravo ptice, zdravo drveÊe!
{85338}{85404}-éiv sam! éiv sam!
{85406}{85522}-"Hava nagila"|"Hava n'ra, n'ra"
{85524}{85608}-Gospodaru!|Gospodaru! Gospodaru!
{85610}{85694}-Gospodaru!|-Gospodar! Ovdje je!
{85696}{85800}-Njegova nas je|cipela dovela k njemu!
{85802}{85890}-Govori! Govori nam gospodaru!|Govori nam!
{85892}{85934}-Idite!
{85934}{85998}-Blagoslov! Blagoslov!
{86000}{86058}-Kako Êemo iÊi, gospodaru?
{86060}{86118}-Ma samo idite|i ostavite me na miru!
{86120}{86172}-Daj nam znak!
{86174}{86252}-VeÊ nam je dao znak!|Doveo nas je na ovo mjesto!
{86254}{86322}-Nisam vas ja doveo ovamo.|Pratili ste me.
{86324}{86398}-O, no to je svejedno|dobar znak po svim mjerilima.
{86400}{86470}-Gospodaru, tvoju ljudi su pjeöaËili|puno kilometara nebi li bili s tobom.
{86470}{86518}-Izmoreni su i nisu niöta jeli.
{86520}{86572}-Nije moja krivica|öto nisu niöta jeli.
{86574}{86632}-Nema hrane u|ovim visokim planinama!
{86634}{86712}-A öto je s onim|pinjola ûbunom tamo?
{86714}{86802}-»udo! »udo!
{86804}{86908}-Svojim rijeËima je|naËinio ûbun plodnim.
{86910}{86968}-I rodio je pinjolama.
{86970}{87058}-Pa naravno da je rodio pinjolama kad je to|pinjola ûbun! äto ste oËekivali drugo?
{87060}{87110}-Pokaûi nam joö Ëuda!
{87112}{87162}-Ne iskuöavajte ga, plitki!
{87164}{87252}-Nije li Ëudo pinjola ûbuna dovoljno?
{87254}{87304}-Vidi ovo!|To je moj pinjola ûbun!
{87306}{87394}-To je dar od Boga!|-To je jedino öto imam za jesti!
{87396}{87520}-Vidi ih! Maknite se|od tog ûbuna. Hajde, crta!
{87522}{87624}-Gospode, pogoen sam ÊelavoöÊu.
{87626}{87706}-IzljeËen sam!|Gospodar me je izljeËio!
{87708}{87754}-Nisam ga ni pipnuo!
{87756}{87824}-Bio sam slijep, a sada vidim!
{87826}{87900}-»udo! »udo!
{87902}{87976}-Reci im da prestanu!
{87978}{88062}-Nisam prozborio niti rijeË|u 18 godina, dok nije on doöao.
{88064}{88154}-»udo!|On jeste Mesija!
{88156}{88198}-On mi je ozljedio nogu!
{88198}{88278}-Ozljedi moju nogu!|-Ozljedi moju!
{88280}{88370}-éivio Mesija!|-Nisam ja Mesija!
{88372}{88456}-Ja kaûem da si ti Gospod, a ja|znam, veÊ sam ih nekoliko slijedio.
{88458}{88514}-éivio Mesija!
{88514}{88584}-Nisam ja Mesija! HoÊete li|me molim vas sasluöati?
{88586}{88664}-Nisam ja Mesija!|Razumijete li? Ozbiljno!
{88666}{88772}-Samo se istiniti Mesija|odriËe svojeg boûanstva.
{88774}{88854}-Kako? Pa, to mi|baö i ne daje neku priliku, ne?
{88856}{88908}-Dobro.|Ja sam Mesija!
{88910}{89000}-On jeste!|On je Mesija!
{89002}{89058}-E sad, odjebite!
{89244}{89292}-Kako Êemo odjebati, o Gospode?
{89294}{89338}-Samo me ostavite na miru!
{89340}{89414}-Ti si rekao ovim ljudima|da pojedu moje pinjole!
{89416}{89488}-Slomio si moje prokleto stopalo,|slomio si moj zavjet öutnje...
{89490}{89564}-...i onda joö pokuöaö|obrstiti moj pinjola ûbun!
{89566}{89646}-Ostavi me!|Ovo je Mesija, Izabranik!
{89646}{89722}-Ne, nije!|-Nevjernik!
{89724}{89824}-Nevjernik!|-Prognati ga! Ubiti heretika!
{89886}{89968}-Drû'te ga!|-Pustite ga!
{89970}{90024}-Pustite ga!
{90026}{90080}-Pustite ga!
{90082}{90154}-Spustite ga! Molim vas!
{90248}{90318}-Brian ?|-Judith ?
{90432}{90502}-Kukuriku!
{91440}{91552}-Pogledajte! Eno ga!|Izabranik se probudio!
{91614}{91672}-Brian !
{91730}{91780}-Brian !|-»ekaj, majko!
{91782}{91832}-Psst!
{91880}{91954}-Zdravo mama.|-Nemoj ti meni "zdravo mama"!
{91956}{92008}-äto svi oni ljudi rade vani?
{92010}{92080}-Pa, ja...|-Hajde reci! äto si smislio?
{92082}{92142}-Mislim da mora biti|da su svratili po neöto.
{92142}{92210}-Svratili?|Sunovratili, bit Êe prije.
{92212}{92262}-Vani je mnoötvo!
{92264}{92314}-PoËeli su me pratiti juËer.
{92316}{92392}-Pa, mogu te|prestati pratiti sada.
{92394}{92462}-Prestanite viöe|pratiti mog sina.
{92464}{92534}-Trebali biste se sramiti!
{92536}{92638}-Mesiju! Mesiju!|Pokaûi nam Mesiju!
{92640}{92710}-Koga?|-Mesiju!
{92710}{92774}-Nema ovdje mesije.
{92776}{92854}-Malo masno jeste, ali|mesije nema. Hajde, idite sad.
{92856}{92916}-Brian! Brian!
{92918}{92968}-Dobro stari moj, |öto si sad naumio?
{92970}{93018}-Niöta mama.|-Hajde, da Ëujem...
{93020}{93066}-Pa, oni misle da|sam ja Mesija, mama.
{93068}{93124}-äto si im to priËao?
{93126}{93182}-Niöta. Samo sam...|-Samo si pogoröavaö situaciju!
{93182}{93268}-»ekaj da ti objasnim...|-Dopustite da Vam  ja objasnim go Cohen!
{93270}{93332}-Vaö sin je roeni voa.
{93334}{93422}-Ovi ljudi vani ga|prate jer mu vjeruju.
{93424}{93494}-Vjeruju da im moûe uliti nadu;|nadu u novi ûivot,...
{93496}{93556}-...novi svijet, bolju buduÊnost!
{93608}{93662}-Tko je ova?
{93664}{93738}-Mama, ovo je Judith.|Judith, mama.
{93828}{93926}/Mesija, Mesija, Mesija!/
{93928}{93998}-Mesija!|Pokaûi nam Mesiju!
{94000}{94078}-Sluöajte sad!|On nije Mesija!
{94080}{94158}-On je vrlo zloËest deËko.|Sad nestanite!
{94160}{94256}-Tko si ti?|-Ja sam mu majka, eto tko.
{94258}{94366}-Vidite mu majku|Vidite mu majku!
{94368}{94450}-Podrav o tebi|majko Brianova!
{94450}{94560}-Blagoslovljena da si!|Hosanna!
{94562}{94648}-ätujemjemo tebe|sada i zauvjek!
{94650}{94728}-Eh, nemojte misliti da|me moûete samo tako zaobiÊi.
{94730}{94812}-On neÊe izaÊi|i gotovo!
{94844}{94912}-Sad crta!|-Ne!
{94914}{95020}-Jeste li Ëuli öto sam rekla?|-Da!
{95022}{95092}-A tako...|ZnaËi tako, jel'?
{95094}{95176}-Da!|-Dobro, onda...
{95178}{95266}-Moûete ga vidjeti na minutu|ali niti sekundu duûe.
{95268}{95328}-Razumijete li?|-Da!
{95330}{95430}-ObeÊavate li?|-Paa..Dobro.
{95432}{95520}-Dobro. Evo ga onda ovdje|Izai Brian. Izai i prozbori.
{95522}{95602}-Ali, mama, Judith...|-Daj, ostavi sad tu velöku kurvu.
{95604}{95652}-Ali ja zbilja ne bih...
{95654}{95726}-Brian ! Brian !|Brian ! Brian !
{95810}{95902}-Dobro jutro.|-Blagoslov! Blagoslov!
{95904}{96012}-Ne, ne, molim vas|Molim, lijepo vas molim, posluöajte.
{96014}{96094}-Imam jednu ili|dvije stvari za reÊi.
{96096}{96156}-Reci nam!|Reci nam obje!
{96158}{96224}-Vidite ovako: sve ste|krivo shvatili.
{96226}{96288}-Ne trebate me pratiti.
{96290}{96370}-Ne trebate nikoga pratiti.
{96370}{96426}-Morate misliti svojom glavom.
{96428}{96494}-Vi ste svi pojedinci.
{96496}{96574}-Da, mi smo svi pojedinci!
{96576}{96624}-Svi ste razliËiti.
{96626}{96702}-Da, mi smo svi razliËiti!
{96704}{96768}-Ja nisam!|-Psst!
{96770}{96858}-Morate sami rjeöavati|svoje probleme.
{96860}{96960}-Da, moramo sami|rjeöavati svoje probleme.
{96962}{97008}-ToËno tako.
{97010}{97064}-PriËaj nam joö!
{97066}{97174}-Ne! U tome i je stvar! Ne dajte|nikome da vam govori öto da radite.
{97176}{97224}-U suprotnome... au!
{97226}{97276}-Dosta je!|Dosta je!
{97278}{97362}-Uuuu, to nije bila minuta!
{97394}{97502}-Je, bila je|-Ne, nije bila!
{97504}{97574}-Hajde, dosta!|I briöite!
{97576}{97628}-Oprostite|-Da?
{97630}{97734}-Jeste li vi djevica?|-Kako molim?
{97736}{97842}-Mislim, ako nije intimno pitanje|jeste li vi djevica?
{97844}{97908}-Ako nije intimno pitanje?
{97910}{97970}-Koliko intimnije|moûe biti?
{97970}{98026}-'Ajde sad, gibajte!
{98056}{98108}-Jeste.|-Da, sigurno je.
{98226}{98284}-'Jutro, Spasitelju.
{98520}{98570}-Poloûi ruke|na mene, brzo!
{98572}{98650}-Nemojte naguravati Izabranika,|molim vas.
{98652}{98748}-Ne guraj to djete|Spasitelju u lice.
{98750}{98838}-»ujte, biste li|mogli pogledati moju ûenu?
{98840}{98888}-Bojim se da Êete|morati priËekati.
{98890}{98950}-Imamo dogovoren poslovni ruËak.
{98950}{98998}-Gubavci Ëekaju u redu.
{99000}{99070}-Moj öogor je bivöi|gradonaËelnik Gata
{99070}{99170}-Brian, mogu li te upoznati s gospodinom|koji Êe nam dopustiti jahanje u nedjelju?
{99172}{99296}-Ne guraj se!|-I tiöe malo, molim vas!
{99298}{99420}-Vi opsjednuti vragom |pokuöajte se malo kontrolirati.
{99422}{99490}-NeizljeËivi, moraÊete priËekati par minuta.
{99492}{99602}-Aa, ûene zateËene u grijehu,|poredajte se uz ovaj zid, hoÊete li?
{99604}{99718}-Brian? Brian,|bio si fantastiËan!
{99720}{99772}-Ni ti nisi bila|tako loöa.
{99774}{99844}-Ne. Ovo öto si maloprije rekao.|To je neöto iznimno!
{99846}{99894}-äto?|A to... Je li?
{99894}{99946}-Mi ne trebamo voe|potpuno si u pravu.
{99948}{100014}-VeÊ predugo Reg dominira nama|-Ovaj, da.
{100016}{100106}-Trebalo je to reÊi, a ti si rekao Brian.|-Vrlo si privlaËna.
{100108}{100186}-Ovo je naöa revolucija.|Sve to moûemo napraviti skupa.
{100188}{100256}-Mislim...Mislim...|-Svi te podrûavam Brian.
{100258}{100332}-Revolucija je u tvojim rukama!|-Molim?
{100334}{100388}-Ne, nisam uopÊe|tako mislio!
{100390}{100470}-Jebeno smo te|uhvatili lijepi moj!
{100472}{100518}-Tako.
{100656}{100712}-Prestani!
{100764}{100846}-Dakle, Buajane dobvu|si nam pauadu pviuedio.
{100902}{100986}-Ali ovoga puta ti|gauantiuam da neÊeö pobjeÊi.
{100988}{101108}-Stuaûa, ima li danas|uazapinjanja na kuiû?
{101110}{101196}-139 gospodine.|Posebna proslava Pashe.
{101198}{101300}-Dobuo. Sada ima 140.|Fini okvugli buoj, ha Velikus?
{101302}{101392}-éivio Cezar!
{101394}{101466}-éivio!|-Gomila vani postaje nemirna.
{101468}{101516}-Molim dopuötenje|da ih rastjeram.
{101518}{101602}-Uasteuati ih?|Joö im se nisam niti obuatio.
{101604}{101642}-Znam gospodine, ali...
{101644}{101702}-Moje obuaÊanje je|jedan od vhunaca ove puoslave.
{101704}{101756}-Moj puijatelj Velikus|Pimpekus je doöao Ëak iz Uima.
{101758}{101842}-éivio Cezar|-éivio Fezar!
{101842}{101910}-Zar ne...
{101912}{102000}-A, zar ne mislite da je bolje|propustiti to ove godine gospodine?
{102002}{102052}-Puopustiti?
{102054}{102136}-Pa, Ëini se da su malo|Ëudno raspoloûeni danas, gospodine.
{102138}{102210}-Stuavno centuione, iznenaen|sam da se Ëovjek poput vas...
{102212}{102270}-...uazbubljao o uazulauenoj|masi uazbojnika.
{102270}{102346}-Ovaj...malo buËno gospodine.|-Odvedite ga.
{102346}{102415}-Ja sam Rimljanin. Mogu|to dokazati! Ozbiljno!
{102416}{102496}-I uasnite ga dobuo.
{102498}{102560}-Velikus.
{102562}{102626}-Ja zbilja to ne bih gospodine...|-Makni se centuvione.
{102629}{102682}-Idem i ja f tobom Pontiuse.
{102684}{102784}-Movda ti flufajno budem od|pomofi ako doe do ivnenadne krive.
{102786}{102891}-Dobro. Sada toËka Ëetiri: tekovine|svjetske premoÊi u sljedeÊih pet godine.
{102892}{102968}-Ovaj, Francis, ti si radio na ovome?|-Da, hvala Reg.
{102970}{103054}-Iskreno reËeno braÊi, mislim da|je pet godina optimistiËno...
{103054}{103126}-...ukoliko ne razbijemo Rimsko|Carstvo tijekom sljedeÊih 12 mjeseci.
{103128}{103174}-Dvanaest mjeseci, da?|-Dvanaest mjeseci.
{103176}{103258}-I moramo se suoËiti s tim da|je, kako carstva prolaze, ovo velika stvar.
{103260}{103362}-Zato moramo pokrenuti guzice|i prestati samo priËati o tome!
{103365}{103434}-Tako je!|Slaûem se. Djela se raËunaju, a ne rijeËi!
{103436}{103492}-A nama se sada potrebna djela!|-Tako je!
{103494}{103542}-U pravu si. Moûemo|sjedeti ovdje cijeli dan...
{103544}{103626}-...priËati, provoditi rezolucije,|govoriti pametno....
{103629}{103684}-...a da to neÊe pomaknuti|niti jednog rimskog vojnika!
{103686}{103768}-Zato dosta brbljanja o tome!|To je potpuno besmisleno...
{103770}{103817}-...i nikuda ne vodi.|-ToËno!
{103818}{103878}-Slaûem se. Ovo je|potpuno gubljenje vremena.
{103912}{103970}-Uhitili su Briana!|-äto? äto?
{103972}{104036}-Odvukli su ga!|Raspet Êe ga na kriû.
{104038}{104122}-Dobro!|Ovo zahtjeva hitnu diskusiju!
{104124}{104162}-Kako|-Hitno!
{104164}{104198}-Dobro.|-Novi predlog?
{104200}{104255}-Potpuno novi predlog.|Da ovaj, da...
{104258}{104322}-...treba poduzeti|hitnu akciju...
{104324}{104386}-...kada se jednom izglasa...|-OËito da, kada se izglasa.
{104388}{104453}-Ne moûeö izvröiti prijedlog|dok ga ne izglasaö!
{104454}{104488}-Reg, hajdemo sada, molim te.
{104490}{104560}-Tako je... U svjetlu svjeûih|informacija od sestre Judith.
{104562}{104610}-Ne tako brzo Reg.
{104612}{104704}-U ime boûije Reg,|savröeno je jednostavno!
{104705}{104779}-Sve öto treba je|da izaete vani...
{104782}{104842}-...i pokuöate zaustaviti|Rimljane da ga ne zabiju na kriû.
{104844}{104938}-Dogaa se Reg!|Neöto se konaËno dogaa!
{104940}{105000}-Razumijeö li?
{105003}{105050}-Ouu!
{105090}{105162}-O. O. Da...
{105165}{105220}-Mali feministiËki egoistiËki ispad?
{105222}{105282}-Molim?|-O, oprosti Loretta...
{105284}{105332}-ProËitaj molim|te to ponovo.
{105646}{105710}-SljedeÊi? RaspeÊe?
{105712}{105758}-Da.|-Dobro...
{105760}{105846}-Kroz ova vrata, pa na|lijevo, svaki po jedan kriû.
{105848}{105898}-SljedeÊi? RaspeÊe?
{105900}{105946}-Da.|-Dobro...
{105948}{106008}-Kroz ova vrata, pa na|lijevo, svaki po jedan kriû.
{106010}{106068}-SljedeÊi? RaspeÊe?
{106070}{106132}-Ovaj, ne. Sloboda.|-Mm? Kako?
{106134}{106192}-Ovaj, za mene sloboda.|Rekli su da nisam niöta uËinio...
{106194}{106262}-...tako da mogu ûivjeti|slobodno na nekom otoku ili sliËno.
{106265}{106341}-O, pa to je baö fino.|Onda moûeö iÊi.
{106344}{106406}-Ma ne, samo te zezam.|Razapinjanje na kriû u stvari.
{106408}{106467}-A, tako.|Jako dobro.
{106470}{106524}-Dakle, kroz ova vrata.|-Da, znam put: kroz vrata...
{106526}{106572}-...svaki po jedan|kriû s lijeve strane.
{106574}{106620}-S lijeve strane.|Da, hvala.
{106622}{106670}-Razapinjanje? Dobro...|-Da
{106998}{107116}-Nauode Jeuzalema
{107118}{107192}-Uim je vaö puijatelj.
{107316}{107410}-kako bi puikazao naöe|puijateljstvo obiËaj je da se u ovo vuijeme...
{107412}{107488}-oslobodi uazbojnik iz naöih zatvoua.
{107594}{107708}-Koga ûelite da puepustim na slobodu.
{107710}{107784}-Puepusti Uodûeua
{107786}{107850}-Puepusti Uodûeua!|Puepusti Uodûeua!
{107938}{108060}-Vlo dobuo,|pustit Êu Uodûeua.
{108130}{108191}-Gospodine, ovaj,|nemamo Rogera.
{108192}{108250}-Molim?    -Ovaj, nemamo nikog|s takvim imenom.
{108253}{108355}-A. Nema Uogeua.
{108424}{108470}-A öto je sa Uodeuikom?
{108472}{108578}-Da, pusti Uodeuika!|Pusti Uodeuika!
{108579}{108696}-Centuvione|zaöto se tako kikoÊu?
{108726}{108790}-Radi se o, ovaj|ûidovskom vicu...
{108829}{108898}-Da li oni mene zafkavaju?
{108938}{109020}-O, ne, gospodine.
{109022}{109128}-Vlo dobuo.|Oslobodit Êu Uodeuika!
{109129}{109176}-Gospodine, nemam ni Rodericka.
{109179}{109256}-Nema Uodûeua, nema Uodeuika|-Oprostite gospodine.
{109258}{109376}-Tko je taj Uodû...Tko je taj|Uodeuik na kojeg aludiuate?
{109378}{109446}-on je uazbojnik!
{109448}{109516}-i kuadljivac!
{109517}{109568}-i pljaËkaö!
{109570}{109617}-Daj... Pssst!|-äuti!
{109655}{109740}-On zvuËi kao notovni kuiminalac|-Nemamo ga gospodine.
{109741}{109808}-Imamo li onda ikoga|u naöim zatvorima?
{109810}{109879}-O, da gospodine, imamo Samsona.|-Samsona?
{109882}{109984}-Samsona Saducejskog VjeöaËa gospodine|-I, ovaj, Silusa, Asirskog Ubojicu.
{109986}{110058}-Onda sitne pisare-huökaËe|iz Cezareje.
{110060}{110148}-Oko öezdeset sedam njih.|-Daj da im fe ja obratim!
{110150}{110205}-O, ne!|-Da, dobra ideja Velikuse.
{110208}{110318}-Ftovani graani, imamo|Famfona Fadufejfkog Vjefafa,...
{110320}{110384}-...Filufa Afirfkog Ubojifu...
{110386}{110472}-Fitne pifare|hufkafe iz Fevareje.
{110474}{110522}-SljedeÊi.
{110524}{110580}-RaspeÊe?|-Da.
{110582}{110666}-Dobro. Kroz vrata,|na lijevo, svaki po jedan kriû.
{110668}{110680}-TamniËaru...
{110682}{110732}-Oprostite, Ëini se|da je doölo do greöke.
{110734}{110822}-Samo trenutak, molim. |-TamniËaru, koliko ih je proölo da sada?
{110824}{110874}-Kako?
{110876}{110948}-Koliko ih je proölo?
{110950}{111008}-Kako?|-MmmmoraÊÊÊÊete...
{111010}{111141}-...ppppprprprpprriËati glasssnije.
{111141}{111212}-Oooooon on on on je ggggg|-Aa...
{111214}{111270}-On je gluh. On je gluh. On je gluh|On je gluh kkkkao tttop.
{111272}{111318}-O da.
{111320}{111414}-Ovaj, koliko ih je proölo?
{111486}{111553}-O Boûe...|-Ja sam izbrojao devedesetppp
{111554}{111658}-devedesetppp|devedesetppp
{111660}{111714}-devedesetöest, gospon.
{111716}{111772}-Kakav besmislen gubitak|ljudskih ûivota, ne?
{111774}{111822}-Nnnne, gospon.
{111822}{111934}-Nnnnne kod ovih bbbitangi.
{111934}{111984}-Rassss
{111986}{112048}-Rassss
{112050}{112129}-RRassspeÊe je|predobro za njih gospon.
{112132}{112194}-Mislim da ne moûeö reÊi da|je predobro, to je baö zloËesto.
{112196}{112304}-O, nije to zzzzz...zloËËËË
{112305}{112384}-Ëesto kao ovo|Ëega sam se sad sjetio, gospon.
{112386}{112480}-Da. Dakle, raspeÊe?|-Ima li nekoga s kome bih se mogao obratiti?
{112482}{112566}-Pa...|-Znam gdje se to moûe naÊi, ako zbilja hoÊeö.
{112568}{112629}-äto?|-Nnnne brinite zzzzza njega gossspon.
{112630}{112717}-On je ggg.|On je ggggl
{112718}{112834}-On je gluh i lud, gospon.|-Pa kako je dobio ovaj posao?
{112836}{112912}-Ppprokleti Pppppilatov mezimac.
{112914}{112994}-Hajde nosati!|Ljudi ovdje Ëekaju na raspeÊe...
{112996}{113048}-Mogu li razgovarati|s odvjetnikom ili nekim veÊ?
{113050}{113117}-Ovaj, imaö li ti odvjetnika?|-Ne, ali ja sam Rimljanin!
{113120}{113188}-äta kaûeö na ponovno suenje?|Mi ovdje imamo puno vremena.
{113190}{113264}-Zaöuti!|-Bijedni Rimljani, nemaju smisla za humor.
{113266}{113322}-éao mi je.|Malo sam u ûurbi.
{113322}{113428}-HoÊete otiÊi pravo vani,|pa lijevo i svako po jedan kriû.Dakle...
{113646}{113696}-Jesam li nefto krivo rekao?
{113698}{113772}-Tiöina!
{113842}{113922}-Ovaj Ëovjek upravlja|uazbijaËkom legijom!
{114053}{114116}-Kotiua visoko|kao i svi u Uimu!
{114191}{114274}-Odred za raspinjanje.
{114310}{114410}-'Jutro. Imat Êemo|nastup dok budemo hodali kroz grad.
{114412}{114460}-zato se drûite ravno.
{114462}{114534}-Ostanite u pravoj liniji uz tri koraka|izmeu prethodnika i vas.
{114536}{114591}-I dobar, stalni ritam hoda.
{114592}{114646}-Kriûeve na lijevo rame!
{114648}{114710}-i ako oslonite|lea Ëvrsto o gredu...
{114712}{114758}-...stiÊi Êete za Ëas.
{114760}{114806}-Dobro, centurione.
{114808}{114910}-Odred za raspeÊe!|»ekaj malo!
{114912}{115054}-Odred za raspeÊe!|Lijevom nogom, naprijed!
{115160}{115212}-Sretnici jedni!
{115248}{115336}-Sretna musava kopilad!
{115536}{115598}-Daj mi da ti|ponesem teret brate.
{115600}{115646}-O, hvala...
{115694}{115762}-Hej, hej!|-Hej, öto to radiö?
{115762}{115834}-Ovaj, to nije moj kriû.|-ZaËepi i nosi!
{115906}{116012}-Zeznuo te je, stari moj, ne?|To Êete nauËiti pameti.
{116014}{116082}-Dobuo!
{116084}{116138}-Dat Êu vam|joö jednu puiliku.
{116140}{116212}-Ali sad ne ûelim|Ëuti za Ueubense
{116215}{116291}-ili Uedûinalde.
{116294}{116374}-ili Vudolf Cvenonosi.
{116376}{116472}-Bez Fpenfera Trejfija!|-Ili neÊemo nikoga osloboditi.
{116474}{116553}-Oslobodinte Briana.|-O da, ta ti je dobra.
{116554}{116670}-Oslobodi Buajana|Oslobodi Buajana.
{116672}{116738}-Dobvo. Dosta mi je.
{116740}{116804}-Gospodine, ovaj, imamo Briana.|-Molim?
{116805}{116855}-Ovaj, upravo ste|ga poslali na kriû.
{116858}{116929}-»ekajte, Ëekajte!|Imamo Buajana!
{116932}{116970}-Dakle idite i uazvijeöite|ga okova ovog tuenutka.
{116972}{117010}-Razumijem. Razumijem.
{117072}{117120}-Dobvo.
{117122}{117208}-PuepustiÊu slobodi... Buajana!
{117294}{117360}-Hajde tamo, pomakni se, ili...|-Ili öto?
{117362}{117426}-Ili Êeö nadrapati!|-O joj...
{117428}{117503}-Misliö da bih mogao propustiti|popodnevno razapinjanje na kriû?
{117504}{117565}-Zaöuti!|-To bi stvarno bila öteta, ne?
{117566}{117648}-Ne bih imao öto raditi.|O, hvala ti.
{117729}{117798}-Jesu li otiöli?
{117798}{117900}-Imamo hrpe toga|negdje straga.
{117903}{117972}-Molim?|-O, ne obazirite se na njega gospodine.
{117974}{118041}-On je llu. On je llu|On je llllulu
{118042}{118112}-On je lllll|On je lllll...
{118115}{118186}-On je lud, gospon.|-Jesu li otiöli?
{118212}{118265}-O dd nnn
{118266}{118380}-A nn aa nnnnn
{118382}{118454}-NNNN|-Ma daj!
{118455}{118514}-Da gospodine.
{118515}{118555}-Dakle, da nastavimo s priËom
{118558}{118605}- Znao sam da joj se|nikad nije sviao, pa sam...
{118608}{118644}-Dobro.
{118646}{118700}-To je prijedlog koji treba sprovesti|a proöao je uz jednog suzdrûanog.
{118703}{118740}-Predlaûem da idemo|bez daljnjih odlaganja.
{118741}{118766}-Mogu li joö samo dodati...
{118767}{118817}-Idemo.|-Da.
{119094}{119141}-O ne.
{119191}{119254}-Prokleti Rimljani!|-Pazi öto priËaö!
{119256}{119304}-Ostalo je joö nekoliko|slobodnih kriûeva.
{119342}{119404}-Diûi se Nosati!
{119405}{119476}-Uhvatit Êu te ja zbog|ovog barabo!   -Da?
{119479}{119556}-O, da, ne brini. Nikad|ne zaboravljam lica   -Ne?
{119558}{119662}-Upozoravam te: tako Êu|te mlatnuti, ti, rimski idiote!
{119664}{119717}-Zaveûi, ûidovsko govno!
{119720}{119794}-Koga ti zoveö éidovom?!|Nisam ja éidov!
{119796}{119848}-Ja sam SamariÊanin!|-SamariÊanin?
{119850}{119894}-Ovo bi trebao biti ûidovski dio.
{119896}{119988}-Nije ni vaûno, svi Êete|umrijeti za dan-dva!
{119990}{120050}-Moûda tebi nije vaûno Rimljanine,|ali je svakako bitno nama.
{120053}{120074}-Zar ne draga?
{120076}{120162}-O, svakako.|-Uvijeti rimske okupacije nam...
{120165}{120236}-...daju za pravo da budemo|raspeti u Ëistom ûidovskom podruËju.
{120238}{120298}-Farizeji odvojeni|od Saduceja
{120300}{120376}-I Velöanin|odvojena od äved.
{120378}{120472}-Dobro, dobro, dobro.|Sad Êemo i to rijeöiti.
{120474}{120580}-Tko ne ûeli biti raspet|ovdje nek podigne ruku.
{120582}{120655}-Dobro. SljedeÊi!
{120658}{120729}-Uh, sluöajte: ovo nije moj kriû|-Kako?
{120729}{120796}-Ovaj, to nije moj kriû|Nosio sam ga umjesto nekoga...
{120798}{120846}-Samo ti lezi. Nemam cijeli|dan na raspolaganju.
{120846}{120904}-Naravno da nemate. Vidite|ne bih htio praviti probleme...
{120905}{120984}-Sluöaj: mi smo priliËno zauzeti|Vas 140 Ëeka da ga popnemo gore.
{120986}{121048}-Je li on éidov?|-HoÊeö li se ti veÊ umiriti?
{121050}{121104}-Ne ûelimo joö|SamariÊana ovdje!
{121105}{121184}-Diûite ga!|-HoÊete li me spustiti ako se on vrati?
{121186}{121248}-Da, da... spustit|Êemo te...SljeseÊi!
{121250}{121316}-Ne morate ovo raditi.|Ne morate sluöati zapovjedi.
{121318}{121374}-Ja volim zapovjedi.
{121910}{121958}-Vidiö? Nije tako loöe|kad si veÊ jednom gore.
{121984}{122029}-Tebe Êe doÊi|spasiti, ne?
{122032}{122078}-Sad je malo prekasno|za to, zar ne?
{122079}{122136}-Ma hajde... Imamo nekoliko|dana na raspolaganju ovdje.
{122138}{122186}-Dovoljno vremena...|Puno ljudi bude spaseno.
{122186}{122270}-Da?|-Da. Mene obiËno spasi moj brat...
{122272}{122334}-...ako se uspije suzdrûati|od guzova bar 20 minuta...
{122336}{122382}-Da?|-Poûudni dripac...
{122384}{122440}-Gora pa dolje,|baö kao Asirsko carstvo.
{122541}{122598}-Alo...To ti|stiûe familija?
{122600}{122641}-Reg!
{122642}{122724}-Zdrav, brate Brian.|-Hvala Bogu da ste doöli, Reg.
{122726}{122784}-Pa, mislim da bih prvo trebao|istaknuti, Brian, da, iskreno govoreÊi,...
{122786}{122836}-...mi nismo odbor za spaöavanje.
{122838}{122906}-UnatoË tomu, zamoljen sam da|ti proËitam sljedeÊu izjavu...
{122908}{122955}-...u ime pokreta:
{122958}{123044}-"Mi, Narodni Front Judeje|zagrada, zvaniËnici, zatvorena zagrada...
{123046}{123132}-...ovdje reËenim izraûavamo naöe|iskrene bratske i sestrinske Ëestitke...
{123134}{123216}-...tebi, Brian, u ovaj|tren tvojeg muËeniötva."
{123217}{123286}-Molim?!|-"Tvoja smrt Êe stajati kao primjer...
{123288}{123358}-...u stalnoj borbi za|osloboenje oËinske zemlje...
{123358}{123420}-...iz ruku rimskog|imperijalistiËkog agresora...
{123422}{123494}-...osim öto se tiËe kanalizacije,|medicine, cestovlja, kuÊne opreme...
{123494}{123570}-...obrazovanja, vinikulture i|bilo kojeg rimskog doprinosa...
{123572}{123672}-...dobrobiti éidova oba spola,|ukljuËujuÊi i hermafrodite."
{123674}{123741}-Potpis: u ime N.F.J., itd.
{123744}{123828}-Uz to bih htio dodati kao osobnu|opasku moje osobno divljenje...
{123829}{123876}-...tomu öto radiö za|nas, Brian...
{123878}{123954}-...a öto sigurno je|vrlo teöko samom tebi.
{123955}{124054}-Reg, öto Êeö...|-Zbogom Brian i hvala.
{124108}{124155}-OdliËno Brian|Samo nastavi tako stari!
{124158}{124220}-Izvrsno obavljeno, Brian!
{124348}{124400}-Dobro. I...
{124402}{124453}-"Jer on je dobar momak"
{124454}{124502}-"Jer on je dobar momak"
{124503}{124579}-"Jer on je dobar momak"
{124580}{124634}-"To kaûemo svi mi"
{124636}{124686}-"To kaûemo svi..."
{124754}{124800}-Nitkovi jedni!
{124802}{124932}-Nitkovi! Nitkovi svetoglumatavi!|-Gdje je Brian iz Nazareta?
{124934}{125016}-Imam naredbu da ga se oslobodi.|-Glupa kopilad!
{125017}{125072}-Ovaj, ja sam Brian iz Nazareta|-Molim?
{125074}{125122}-Da, ja sam Brian iz Nazareta.|-Skidajte ga!
{125124}{125204}-Ja sam Brian iz Nazareta!|-Ja sam Brian!
{125205}{125288}-Ja sam Brian!|-Ja sam Brian!
{125291}{125367}-Ja sam Brian!|-Ja sam Brian, baö kao i moja ûena!
{125370}{125438}-Ja sam Brian!|-Ja sam Brian!
{125438}{125476}-Vodite ga i oslobodite!
{125479}{125596}-Ne, samo sam se öalio! Ja u stvari|nisam Brian. Ne, ja nisam Brian!
{125598}{125676}-Samo sam...To je samo öala|Zezao sam vas...
{125678}{125791}-To je öala! Ja nisam on.|Samo sam vas navlaËio! Vratite me!
{125794}{125853}-Prokleti Rimljani!|UopÊe ne shvaÊaju öalu!
{126072}{126134}-Judejski Narodni Front!
{126136}{126218}-Judejski Narodni Front!
{126220}{126286}-Naprijed svi!
{126382}{126441}-Idemo!|Judejski Narodni Front!
{126442}{126508}-Judejski Narodni Front!
{126667}{126800}-Mi smo Gromoviti Odred Samuobojica|Judejskog Narodnog Fronta!
{126802}{126888}-Odred Samoubojica...|Napad!
{127102}{127154}-Sad smo im pokazali!
{127202}{127308}-Budalaöi jedni!
{127310}{127400}-Brian! Brian! Brian!
{127403}{127504}-Judith!|-Izvrsno! OdliËno!
{127505}{127592}-Reg mi je objasnio sve. Mislim|da je veliËanstveno to öto radiö.
{127594}{127641}-Hvala ti Brian.
{127644}{127708}-Ja...Nikada te|neÊu zaboraviti.
{127910}{127972}-Dakle tu si!
{127974}{128032}-Mogla sam si misliti|da Êeö ovako zavröiti.
{128034}{128129}-Kad samo pomislim na svu ljubav i|naklonost koju sam protratila na tebe...
{128130}{128204}-Dakle, ako se tako ponaöa|prema svojoj jadnoj staroj majci...
{128206}{128256}-...u poznim godinama|njenoga ûivota...
{128258}{128341}-...sve öto mogu reÊi je:|idi, idi i budi razapet!
{128344}{128404}-Baö me briga!|Mogla sam si misliti!
{128405}{128460}-Mama!
{128462}{128565}-Mama!|-äto Êe s ovim svijetom biti...
{128694}{128786}-Ozari se Brian!|Znaö kako kaûu:
{128788}{128860}-Neke stvari se Ëine ruûnima
{128862}{128920}-Mogu nas naËiniti tuûnima
{128922}{129018}-Zbog drugih stvari|psujemo i loöe smo volje.
{129020}{129086}"Dok grickaö ûivot ne kukaj"
{129088}{129172}"Skupi usne zafuÊkaj"
{129174}{129272}"I stvari Êe ti krenuti na bolje..."
{129274}{129320}"I..."
{129322}{129434}"Uvijek gledaj svjetliju stranu ûivota"
{129522}{129636}"Uvijek gledaj sjajnu stranu ûivota"
{129698}{129804}"Ako ti ûivot razjeda plijesan|neöto zaboravljaö, pravi si blesan"
{129805}{129888}"A to su osmijeh, smijeh|i plijes i pjesma."
{129891}{129946}"Kad se osjeÊaö kao da si za gnoj"
{129946}{129994}"Ne budi luckast stari moj..."
{129996}{130091}"Samo napuÊi usne,|fuÊkaj, to je to"
{130092}{130210}"I...Uvijek gledaj svjetliju stranu ûivota"
{130222}{130262}-Hajdete!
{130286}{130403}"Uvijek gledaj svjetliju stranu ûivota"
{130474}{130528}"Jer ûivot je apsurdan priliËno"
{130529}{130576}"A smrt te doËeka konaËno."
{130578}{130658}"Pokloni se pred zastorom an-face"
{130660}{130712}"Zaboravi na grijeh"
{130715}{130762}"Daj publici osmijeh"
{130762}{130844}"Uûivaj, to ti je tvoj zadnji Ëas"
{130846}{130980}"I zato: Uvijek gledaj|svjetliju smrti stranu"
{131055}{131172}"Prije no öto izdahneö|u posljednjem danu"
{131246}{131338}"éivot je obiËno sranje|kad ga sagledaö: viöe-manje"
{131340}{131432}"Smrt je öala,|ûivot je tek smijeh"
{131434}{131536}"Gledaj to kao predstavu:|svi se smiju tvojem odlasku"
{131538}{131614}"Al' zapamti da Êe|zadnji bit tvoj smijeh."
{131614}{131742}"Uvijek gledaj svjetliju stranu ûivota"
{131830}{131948}"Uvijek gledaj pravu stranu ûivota"
{131950}{132018}-Hajde Brian, razvedri se!
{132018}{132134}"Uvijek gledaj svjetliju stranu ûivota"
{132216}{132328}"Uvijek gledaj pravu stranu ûivota"
{132330}{132400}-Ima i gorih stvari|na svijetu, znaö?
{132402}{132492}"Uvijek gledaj svjetliju stranu ûivota"
{132494}{132550}-äto moûeö izgubiti?|Dolaziö iz niËega...
{132550}{132610}-VraÊaö se u niötavilo...|I öto si izgubio?
{132612}{132708}-Niöta!|"Uvijek gledaj pravu stranu ûivota"
{132710}{132784}-Niöta dolazi iz niötavila...|Znaö kako kaûu...
{132786}{132832}"Uvijek gledaj..."|-Ozari se lega.
{132834}{132900}"...svjetliju stranu ûivota"" |-Da vidimo smijeöak...Eto vidiö!
{132902}{132996}-Vidiö? Ovo je kraj filma.|Uzgred, ovaj CD moûete kupiti na ulazu...
{132998}{133092}"Uvijek gledaj pravu stranu ûivota"|-Neki moraju ûivjeti od ovoga.
{133094}{133166}-Tko bi joö platio|da sluöa ovo smeÊe?!
{133168}{133270}"Uvijek gledaj svjetliju stranu ûivota"
{133272}{133364}-Rekao sam mu. Lijepo sam mu rekao:|"Bernie,nikad neÊemo od ovoga zaraditi..."
{133366}{133468}- K R A J -|Prijevod i titlovi: Shtimkily ARTS, 2001.
{133493}{134993}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/m2wc|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
