{1}{1}23.976
{26}{176}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{2685}{2811}Da, sreÊan sam zbog ove prilike. lako|neki moji ljudi ne razumiju prednosti
{2812}{2880}siguran sam da oni|u Cardiff razumiju.
{2881}{2944}SreÊni su öto imaju|tako odluËnog vou.
{2945}{3046}A sad je dosta priËe|o poslu, g. Premijeru,
{3047}{3121}i popijmo prvu vodu iz postrojenja.
{3195}{3270}Hvala. Da. Hvala.
{3337}{3427}Nadam se da je ovo tek prvi od|mnogih zajedniËkih projekata.
{3429}{3505}Mi kaûemo da zmaj|sudbine ima dugi rep.
{3579}{3644}Za Cardiff. Za|vaö novi vodovod.
{3734}{3805}Imamo veliku Ëast. I mi.
{3856}{3989}Svi mi u Cardiffu imamo sreÊe|öto poslujemo sa vama. Da. Hvala.
{4056}{4121}G. Premijeru, hvala Vam.
{5674}{5794}BEZ IZLAZA
{6345}{6435}17 sati pre
{6619}{6763}Spavaö? Zlato, öto|se dogaa? Beeze.
{6765}{6819}Vidi ti to.
{6883}{7007}Odakle ta iznenadna|energija? Molim te! Boûe...
{7082}{7135}Jesmo li stigli?
{7151}{7306}SudeÊi po ovome, Ëeka nas joö|samo 11 uûasnih sati leta. Sranje.
{7307}{7370}Moraö staviti jedan|dolar u kasicu prostakicu.
{7371}{7459}Ostavio sam kasicu|prostakicu u Teksasu.
{7461}{7552}Sranje! Kako sam mogao biti|tako glup. Tata! Dûek.
{7595}{7725}Gde je Bob? äta traûiö? Ne mogu|naÊi Boba. Jesi li pogledala ispod?
{7726}{7830}Ne smeö govoriti|reË SRANJE. Molim?
{7832}{7914}Jesi li je upravo sroËila?|Da. Ti ne smeö to govoriti.
{7915}{7986}Ja smem, ali u posebnim|hitnim sluËajevima.
{7987}{8131}Prema pravilima koje usput|smiöljam. To nije bio hitan sluËaj.
{8132}{8261}Kuda je nestao? Zlato, ne gnjavi|tu ûenu. Joö uvek ga ne vidim.
{8402}{8514}Izvoli. Zdravo, Bobe.|Hvala. Kako si? Dobro.
{8534}{8653}äta vam je bilo sa rukom?|Borio sam se protiv tigra.
{8682}{8753}Stvarno? Stvarno. Ali ne brini.
{8776}{8869}On je proöao gore od mene.|äta vam je bilo sa glavom?
{8889}{8968}Pao sam po stubiötu u Hong Kongu.
{8970}{9124}Sedni, zlato. Ne gnjavi ga. Oprostite.|Hvala. Bilo mi je zadovoljstvo.
{9155}{9259}äta ako nam se tamo ne svidi?|Tamo kuda idemo? SvideÊe nam se.
{9261}{9335}äta ako i ova firma propadne?
{9397}{9523}Nema öanse, jer ova firma je|puno veÊa no öta je bila tatina.
{9525}{9580}A to je bolje, ha?
{9806}{9911}ObeÊali su nam auto, zar|ne, dragi? Jesu. Ali ne...
{9913}{9966}Moûeö li nazvati koga?
{9967}{10044}Ovaj telefon bi trebao öljakati|meunarodno, ali ne öljaka.
{10045}{10141}Niöta ne vidim. Mislim|da smo loöe krenuli.
{10169}{10256}Uzmimo jednog od ovih|tipova. Hvala! Aha!
{10257}{10368}»ekaj. Jedan savet.|Ovi tipovi su prevaranti.
{10370}{10432}Nose odeÊe kako bi|izgledali sluûbeno,
{10433}{10532}ali Êe vas samo opljaËkati.|Napolju je sluûbena taksi linija.
{10533}{10613}Mogu vam pokazati. Super.|Hvala. Ili Êe vas oderati.
{10614}{10709}Ne brini, momËino.|Doite. PokazaÊu vam.
{10725}{10825}Evo. Zaboravili ste svoje|torbe. Ne, to je sve, mala.
{10827}{10917}Volim putovati sa malo|prtljaga. Shvataö? Baö prikladno.
{10918}{11048}Odakle ste? Iz Ostina u Teksasu.|Iseljenici? Za koga radiö?
{11051}{11155}Za Cardiff. Jedan sam od|inûenjera koji Êe obnoviti vodovod.
{11156}{11270}Vi kardifovci ste svuda, ha?|Gde odsedate? U Imperial Lotusu?
{11271}{11336}Da, kako znaö? Svi tamo|odsedaju. I ja sam tamo.
{11337}{11390}Mogu vas prebaciti. Imam sastanak.
{11391}{11476}Vaûi? Da, bilo bi to super.|BiÊe mi zadovoljstvo.
{11477}{11543}Ja sam Hamond.|Dûek. Drago mi je.
{11544}{11637}Zdravo, ja sam Enie.|Ovo su Lusi i Briegel.
{11638}{11757}Ali moûete je zvati Beeze. Zdravo,|Beeze. Svia ti se tu? Itekako.
{11758}{11858}Tu sam bio 15 puta.|To je puno puta.
{11860}{11944}Bogami. Super mi je|tu. Volim ûene ovde.
{11945}{12042}éeljne su zadovoljiti|Ëoveka, razumeö? Zanimljivo...
{12043}{12152}Gledam naöe torbe i mislim da|imamo previöe prtljaga. äaliö se?
{12153}{12203}Moûda bismo trebali uzeti taksi...
{12204}{12330}Ne brinite zbog njih. Sve im|stane na moped. BiÊe super.
{12355}{12462}Evo vaöeg prevoza.|Ovo je moj Ëovek!
{12485}{12591}Hajde. U sigurnim ste|rukama. Falio si mi. Vidi ga!
{12616}{12692}Tako! Pazi na nogu!|Lepo je videti te.
{12694}{12794}Ovi dobri ljudi trebaju|prevoz. Njihov se nije pojavio.
{12795}{12899}U redu. Hvala. Ali moram|vas pitati neöto jako vaûno.
{12915}{13004}Volite li Kennyja|Rodûera? Kennyja Rodûersa?
{13060}{13146}Da, naravno.|Da? Aha.
{13148}{13295}Jer ovo je Kenny Rodûer taksi.|Boûe! Pojma nisam imala.
{13297}{13433}Ja sam Samnang Pichairongkramgiskerong.|Svia mi se tvoje ime.
{13435}{13558}Da? Ali svi moji drugovi me zovu|Kenny Rodûer. To je veÊ laköe.
{13559}{13633}Jer smo sliËni. Ozbiljno?
{13708}{13804}Jezovito. Razdvojeni|pri roenju! Idemo.
{13828}{13913}Hajde. Tako. Ja Êu uzeti ptice.
{14300}{14428}Kenny Rodûers, a da malo|pripaziö kuda voziö? Hvala.
{15882}{15980}Mi Ëastimo, dobro?|OK. Hvala. »uvajte se.
{16071}{16194}Ova je lepa. Tata, vidi, to|si ti! To je tvoje ozbiljno lice.
{16196}{16288}Radije bih vozaËa, ali i|ovo je lepa dobrodoölica.
{16296}{16392}Tata, svetlo ne|radi. Kako to misliö?
{16393}{16494}Ja imam Boba. Ne,|ne radi. U pravi si.
{16496}{16610}Ali mi je super kako je ovaj hotel|nepredvidiv. Nije ti! Super mi je!
{16611}{16694}Jer na mnogim mestima, kad|stisneö prekidaË, svetla se upale.
{16695}{16774}Ali ovde je tajanstveno, napeto.
{16775}{16910}Enie, kad smo veÊ kod misterija,|öto je ovo? Moje kuvalo za pirinaË.
{16912}{17030}Znam, ali mi smo u Aziji. Misliö|da ovde ne znaju skuvati pirinaË?
{17031}{17158}To je moje kuvalo za pirinaË.|Pokaûimo kako mi to radimo.
{17160}{17237}To! Hvala.|éelim iÊi plivati.
{17239}{17323}Ne, ne moûemo na plivanje.|Moraö na spavanje.
{17324}{17403}Nisam umorna i stvarno|ûelim iÊi plivati.
{17405}{17496}Neöto Êemo se dogovoriti.|Smirit Êemo se.
{17497}{17579}Moûete ovde u tiöini gledati TV.
{17664}{17771}Ne primamo nijedan|kanal. Samo smetnje.
{17772}{17853}Niöta ne radi! Ne budimo teöke.
{17854}{17965}Lusi je oduvek|teöka. Od samog roenja.
{17966}{18043}Cure! Tata, ispriËaj nam|priËu kako se Lusi rodila?
{18044}{18116}Da! Svia vam se ta priËa, ha?
{18117}{18211}Bilo je to teûak porod. Znala|sam! Ali na dobar naËin!
{18212}{18294}Dobar teûak porod. éeliö|li nazvati u vezi televizije?
{18295}{18387}NazvaÊu. IspriËaÊu|vam priËu. Samo malo.
{18388}{18470}Nisam teöka! Telefon ne radi.
{18484}{18578}Dobrodoöli u TreÊi svet.|Ovo je zapravo »etvrti svet.
{18579}{18672}Stvarno? Tako piöe u knjizi.|Nisam znao da to postoji. Ni ja.
{18673}{18831}Moûda si uötekala kuvalo. Da nije to|izazvalo kratki spoj? Ne. Dripac!
{18833}{18898}To se dogaa po|Ëitavom gradu. äta to?
{18899}{18986}U Ëitavom gradu nema interneta i|televizije? Bojim se da je tako.
{18987}{19072}Imate li koji poziv iz|Cardiffa? Za Dûeka Dwyera?
{19073}{19192}Rade li telefoni? Rade, ali|nemamo poziva iz Cardiffa za vas.
{19193}{19289}Viöe sreÊe ujutro. U redu. Hvala.
{19491}{19596}Idemo! Sad Êe!|Mogu li dobiti pivo?
{20073}{20199}Hvala. Hvala! Hvala!
{20211}{20291}To je bilo super. Vidi|njega! Sedi ovde sasvim sam.
{20292}{20386}Lagani jetlag, ha? Aha,|malo mi je magla pred oËima.
{20387}{20462}A ti? Izgledam li ti ja kao|neko ko pati od jetlaga?
{20463}{20539}Ne. Sve to sranje je samo u glavi.
{20541}{20590}Sve je tu gore.
{20591}{20678}Sranje. Dûo, dva mala. Tako...
{20708}{20832}Mislim da Êu ostati kod piva.|Ovo nije za tebe, veÊ za mene.
{20857}{20979}Svira li to onaj tip Kasiove|klavijature na klaviru?
{21002}{21094}Dobrodoöao u Aziju. Svidet|Êe ti se ovde. Stvarno?
{21097}{21249}Moûeö raditi toliko toga. Ne znam.|Pre 10 godina nisam se zamiöljao
{21250}{21316}kako odvlaËim svoju porodicu|na drugu stranu sveta
{21317}{21442}kako bi iznova poËeo, sa osrednjim|menadûmentom. Barem je dobro plaÊeno.
{21444}{21574}I... Dobro ti ide. Aha.
{21576}{21648}Znam obmane koje|prodaju oni iz Cardiffa.
{21649}{21748}Imaö neöto protiv Ëiste|pitke vode? OËito.
{21832}{21932}Moûda mi treba ûestoko. Ne|treba ti. Gore su ti klinke.
{21933}{22041}äta si uradio u svojim boljim|danima? Izumio sam jedan ventil.
{22069}{22157}Znam da ne zvuËi seksi, ali|je bilo. Bogami ne zvuËi.
{22158}{22270}Ne, ali izmislili smo jedan ventil|koji je umalo postao velika stvar.
{22300}{22395}Bili smo jako blizu. Za umalo.
{22438}{22511}Umalo. Umalo.|éiveli.
{22608}{22706}A ti? Imaö li klince|ili öto veÊ? Ne.
{22708}{22775}Ne. Viöe nemam.
{22842}{22943}Valjda sam i ja imao bolje dane.
{22945}{23069}U tom duhu, mislim da Êu|posetiti striptiz bar.
{23071}{23197}U redu. Moûda bih se|trebao presvuÊi u trenirku.
{23199}{23300}Neka znaju da mislim|ozbiljno. O, da!
{23301}{23442}Ne daj da te gadovi bace u|depresiju. U redu. Hvala. Naravno.
{23444}{23492}Vidimo se.
{25303}{25377}Draga, jesi li dobro?|Jesi li bolesna? Ne.
{25379}{25470}äta to radiö? Samo sam umorna.
{25521}{25623}Ljutiö se na mene? Ne.
{25757}{25866}Enie, ûao mi je öto nisam...|nisam te sa ovime hteo prevariti.
{25868}{25999}U redu je. Nisam planirao|da Êe stvari ispasti ovako,
{26001}{26115}ali sam mislio da je|ovo najbolja opcija.
{26117}{26186}Dûek, ne mogu.|Znam. Dajem sve od...
{26187}{26264}Trenutno te ne mogu|teöiti. Znam. Nisam...
{26455}{26503}U redu.
{26971}{27089}Jesu li zvali iz Cardiffa? Dûek|Dwyer. Nisu, gospodine. éao mi je.
{27091}{27204}Imate li novine? Naöa dostava|danas nije doöla. Nemamo.
{27205}{27302}Mogu li ih gde kupiti? Da.|Moûete otiÊi do Kampuchea Kroma.
{27303}{27359}Ne znam gde je to.
{27399}{27465}Ovde smo mi, a ovde|je Kampuchea Krom.
{27466}{27573}Kad stignete do Mao TseTunga, skrenite|desno. Ali samo napola. Napola.
{27574}{27652}Novine, gospodine.|Hvala. Nema na Ëemu.
{30504}{30578}Imate li novine na engleskom?
{30593}{30681}Imate li D Herald|Tribune ili USA Today?
{30710}{30767}Imate li kakve ameriËke novine?
{30997}{31045}Super.
{31140}{31193}Hvala.
{31251}{31361}Ove se stare tri|dana. Imate li novije?
{31423}{31471}Hvala.
{34929}{34981}Brûe, brûe!
{36771}{36919}äta se dogaa? Ja sam|Amerikanac. MiËite ruke sa mene!
{36921}{36969}Pustite me!
{37020}{37085}MiËite ruke sa mene! Pustite me!
{38441}{38518}Dolaze u hotel. Nismo sigurni ovde!
{38690}{38755}Stavi tamo stol.|Donesite joö stolica.
{38757}{38834}Vratite se u svoju sobu|dok situacija ne zavröi.
{40365}{40474}HoÊeö li ikad koristiti svoje|naoËare? Kao da ih nikad ne koristiö.
{40477}{40545}Enie? Dolazim!|Enie, otvori.
{40546}{40642}Jesi li dobro? Aha. Neöto|ne valja? ZakljuËaj vrata.
{40643}{40752}Napolju kao da je rat. Doi videti!|Uspori. Pogledaj, vidiö li to?
{40753}{40863}NadjaËavaju policiju. Ne vidim niöta.|Doi, vidi! Plaöiö me, prestani.
{40864}{40928}Vidiö li onaj dim?|äta? Ne! Ne vidim niöta.
{40929}{41034}Enie, oni ubijaju ljude.|Vuku ih napolje i pucaju u njih.
{41035}{41093}U strance. Zaöto?
{41094}{41184}Ne znam öta se dogaa. Ubili|su Ëovek pred mojim oËima.
{41185}{41263}Enie, tu su u|hotelu. U predvorju su.
{41283}{41338}Gde je Lusi?
{41398}{41502}Bila je tu. Lusi,|istoga trena! Otiöla je.
{41503}{41606}Kako to misliö? Kamo|je otiöla? Na bazen.
{41621}{41705}Pustila si je da sama ode na|bazen? Nisam je pustila samu!
{41706}{41774}Bila je zloËesta. Ostani|ovde i zakljuËaj vrata.
{41775}{41840}Jesi li siguran?|ZakljuËaj vrata! »ekaj!
{41842}{41921}Na Ëetvrtom je|spratu! Zatvori vrata!
{42026}{42136}Odenimo drugu odeÊu.|Sve je u redu, ne boj se.
{42889}{42941}Tako.
{43047}{43102}Zavröi drugu.
{43548}{43700}Znaö öta, Briegel? Odi u kupaonicu|i zakljuËaj vrata, molim te. Smesta.
{44861}{44926}Napolje! Napolje!
{45070}{45185}Pustite ih na miru!|Ne, pustite ih na miru!
{45310}{45358}Ne...
{45823}{45913}Mamice? U kupaonicu,|Beeze. Smesta.
{46592}{46654}Izlazi napolje iz bazena! Doi!
{46768}{46821}Izlazi napolje iz bazena!
{46988}{47036}Doi.
{47821}{47876}Idite na krov! Brzo!
{47924}{47976}Idite na krov!
{48214}{48269}Dûek. Enie, otvori.
{48329}{48482}Sranje. Ona je dobro!|Moramo izaÊi napolje.
{48516}{48628}Enie, moramo na krov.|Ne moûemo otiÊi odavde.
{48629}{48720}Oni su tamo napolje. Nisu,|upravo smo doöli na ovaj kat.
{48721}{48804}Moûemo ostati ovde. Veruj|mi. Moramo ih odvesti na krov.
{48805}{48949}Moramo smesta krenuti,|molim te. Moramo iÊi.
{49100}{49227}Mama, Bob!|Ne, ne! Hajde!
{49229}{49317}Ne! Ne, ne. Prestani!
{49319}{49407}Ne! Hajde, brûe!
{49528}{49683}U redu je. Zatvori oËi. Tu smo.
{49719}{49840}Drûi vrata! Ne daj im da uu!|Otvarajte! Mi smo Amerikanci!
{51364}{51419}SjesÊu ovamo.
{51515}{51613}Jesi li dobro? Tako.|Jesi li dobro? U redu.
{51615}{51735}Bile ste dobre, cure.|Da vidim öta se dogaa.
{51738}{51839}Znate li öta se dogaa? Nemamo|pojma. Zna li ko da smo na krovu?
{51840}{51914}Nadam se. Imaö li|signala? Ne radi.
{51915}{51983}Neko je rekao da|su ubili premijera.
{51984}{52077}Ne pribliûavaj se|rubu. PucaÊe na tebe.
{52177}{52280}äta to viËu? Ne znam. Dole je|neki ludak. Skroz se raspametio.
{52281}{52381}OstaÊemo na krovu i ubiti|svakoga ko pokuöa doÊi ovamo.
{52382}{52482}Moja ûena govori francuski.|Enie, ovaj tip govori francuski.
{52483}{52531}Samo malo.
{52599}{52683}äta govori? Govori|mi da se ne opiremo.
{52688}{52758}NeÊe biti zarobljenih|jer Êe nas ionako ubiti.
{52759}{52842}To uporno ponavljaju.
{53012}{53119}Krv za vodu. Krv za|vodu? äta to znaËi?
{53121}{53275}On ne zna. NosaË zna. Kompa,|öta znaËi "krv za vodu"?
{53276}{53349}ViËu "krv za vodu". äta to znaËi?
{53350}{53447}Amerikanci preuzimaju vodopskrbnu|tvrtku i njima se to ne svia.
{53476}{53557}Imamo Ëitavo... Cardiff?
{53575}{53649}On govori o Cardiffu?|Jesi li znao öto o tome?
{53650}{53730}Naravno da nisam. Mislio sam|da smo doöli pomoÊi. Tata?
{53750}{53824}Pokuöavaju li nas ubiti?|Ne, ne pokuöavaju nas ubiti.
{53825}{53924}Tamo su dole su ljudi koji nas ûele|ozlediti. Nemoj joj to govoriti.
{53925}{54013}Ne ûelim se pretvarati da se ovo|ne dogaa. DrûaÊemo se zajedno,
{54014}{54100}sluöaj mamu i pazi|na svoju mlau sestru.
{54101}{54195}Zaöto nas pokuöavaju ubiti?|Ne znam. Pazi na Beeze,
{54196}{54271}jer je ona tvoja sestrica|i treba tvoju pomoÊ.
{54272}{54387}»ekat Êemo ovde i pomoÊ Êe|stiÊi. »ujeö li helikopter?
{54389}{54490}Dûek, Ëujeö li to? Je li|to helikopter? »ujete to?
{54491}{54578}Da, to je helikopter.|Odlazimo odavde!
{54580}{54722}Vidite? Sve Êe biti u redu. Jesi|li dobro? Jesi li ozleena?
{54724}{54805}Naterao si me da ostavim Boba.|Kupit Êemo ti drugog Boba.
{54806}{54878}Ne ûelim novog Boba.|Bio je to dugaËak dan.
{54879}{54962}Nisi mi rekao kakav je|dogovor? äta kaûeö na ovo?
{54963}{55034}NabaviÊemo ti psa.|NabaviÊemo ti novog psiÊa.
{55035}{55145}Buldoga? Da, buldoga.|Ruûnog buldoga?
{55173}{55276}Najruûnijeg na svetu.|Dogovoreno. Dogovoreno.
{55625}{55673}Vidiö ga?
{56272}{56351}Dole! Glave dole!
{57376}{57424}Jeste li dobro?
{57464}{57544}»ekaj, Dûek. äta to radimo?
{57747}{57823}Dûek, öta to radiö? Sranje!
{57825}{57936}Doite! Doite! Idemo|na drugu stranu. Imam te!
{57938}{58013}Brzo! Imam te. Brzo!
{58162}{58221}Brûe. Ovamo.
{58270}{58342}Sagnite se! Odite tu ispod.
{58384}{58442}Moramo doÊi do onog krova. äta?
{58481}{58586}Nema öanse. Enie, sluöaj|me. äta Êemo uËiniti?
{58588}{58651}Moramo to uËiniti.|Sakrit Êemo se tamo. Ne.
{58652}{58738}Kad se probiju ovamo,|mrtvi smo. Dûek, ne.
{58739}{58825}Tamo imamo öansu. Tamo|preko? Tamo Êe biti isti ljudi.
{58826}{58903}Moramo se Ëim viöe udaljite od njih.
{58904}{58996}Ako ostanemo tu, ubiÊe nas.|Dûek, ovo je jebeno ludo.
{58997}{59050}Ovde Êemo umreti.
{59051}{59132}Molim te, nemamo izbora.
{59133}{59218}Kako? Ti Êeö prva skoËiti,|zatim Êu ti dobaciti decu.
{59219}{59272}Ja idem za vama.
{59297}{59398}Hajde, moûeö ti|to. Kako? Ovamo.
{59404}{59471}Tu se popni.
{59473}{59543}Zaleti se i onda jednostavno skoËi.
{59544}{59693}Nemoj, mama. Maknite se.|Prestanite! Moûe ona to.
{59695}{59743}Hajde!
{60047}{60152}Sranje! Ne mogu... äto|to radiö? Da, moûeö.
{60231}{60328}Enie, pogledaj me. Samo uËini to. Ne|razmiöljaj o tome. Ne viËi na mene.
{60329}{60422}Ne razmiöljaj o tome. Gledaj|me. Nemoj to uËiniti, mamice!
{60423}{60476}»oveËe, bojim se.
{60674}{60773}Jesi li dobro? Jesi li dobro? Aha.
{60775}{60868}PoslaÊu Beeze preko.|Ona je dobro. Ne! Ne.
{60870}{60975}Zatvori oËi na trenutak.|Nemoj to uËiniti.
{61041}{61092}NeÊu da me baciö mami!
{61093}{61148}NeÊu to uËiniti. Dobro?
{61149}{61201}Kako Êe se zvati tvoj buldog?
{61202}{61326}ChoV»ou. To je bolje ime|nego Winston? Misliö? Ne!
{61713}{61820}Briegel, jesi li|dobro, zlato? Bravo!
{61822}{61901}Hajde. Ne.
{61903}{61995}Lusi. Ne. Lusi,|doi ovamo. Ne!
{61997}{62112}Sluöaj me! Moram te|baciti na onaj krov.
{62114}{62189}U suprotnom Êete oni|zloËesti ljudi ozlediti.
{62223}{62313}Doi. Ne. Ne!|Moûeö ti to!
{62350}{62438}Ne. Tatice!
{62528}{62644}Povuci se gore! Nemoj me|pustiti! Drûi se za moju ruku!
{62678}{62768}Hajde! Vuci!
{63015}{63064}Lusi, skoro smo pali!
{63065}{63186}Sluöaj me! Kad ti neöto|kaûem, to napravi! Bojim se.
{63205}{63311}Znam, i ja se bojim, ali sve|Êe biti u redu. Samo zatvori oËi.
{63312}{63449}Ne. Ne.|Lusi. Ne!
{63880}{63971}Zlato, jesi li dobro?
{64047}{64194}U redu je. Uhvati malo|vazduha. Bravo, cure! éao mi je.
{64604}{64691}Jesi li dobro? Da, dobro|sam. Odite tu ispod.
{64996}{65072}Jesi li dobro? Jesam.
{65156}{65287}Prokletstvo! Sranje!
{65310}{65378}Tu se moûemo spustiti.|Jesi li siguran? DA.
{65379}{65463}Joö samo 10 stuba. Joö|samo 10 stuba. Brzo, brzo.
{65464}{65512}Brzo, brzo...
{65738}{65791}Spusti Lusi.
{65831}{65952}Imam je. Jesi li dobro? Aha.
{65954}{66065}Opet, tako. Imam te. Pusti je.
{66123}{66176}Hajde.
{66178}{66285}Stavi nogu ovde.|Imam te. Tako, ovamo.
{66347}{66469}Sagni se, zlato.|Sednite na trenutak.
{66581}{66664}Jesi li dobro? Aha.
{66666}{66768}Prebrodit Êemo ovo. Znam.
{66791}{66884}Lusi, jesi li dobro?|Beeze, dobro si?
{66912}{67030}Briegel. Zlato. Beeze,|pogledaj me? HoÊu kuÊi.
{67084}{67137}Znam.
{67282}{67415}Tata, ispriËaj nam priËu o|mom roenju. Ne sad, zlato.
{67417}{67470}IspriËaÊu ti je kasnije.
{67621}{67674}Ja sam gladna.
{67723}{67842}Zdravo, Gladna. Ja sam|tata. To nije smeöno.
{67844}{67933}Nisam ja Smeöna, ja sam|Tata. Joö uvek nije smeöno.
{67981}{68100}Meni je smeöno. I|zato si ti moja miljenica.
{68102}{68204}Baö si zloËesti. Obe|ste moje miljenice. Tata!
{68220}{68268}Doi.
{68426}{68517}Sagnite se. Sagnite se!
{68577}{68660}Tamo dole je tenk. Moramo|se pokrenuti. Molim?
{68778}{68901}Hajde, tamo dole je|tenk. Ovde unutra.
{68986}{69034}Brzo!
{69663}{69782}Jesi li dobro? Aha.|Zlato, jesi li dobro?
{70119}{70174}Makni se, brzo!
{70329}{70489}Makni se. Dûek?|Sranje! Ovde unutra!
{72672}{72739}Otiöli su. Sve je u redu, otiöli su.
{72863}{72970}Mama, moram iÊi srati.
{73118}{73192}U redu je, pokaöta se u gaÊe.
{73212}{73365}Ali... Ja nisam mala|beba. Znam to, zlato.
{73367}{73503}Znam. Samo ovaj put. Ali...
{73528}{73613}ObeÊavam ti da je u|redu. U redu je, Beeze.
{73741}{73789}U redu je.
{74214}{74275}Znate li koliko vas volim?
{74355}{74415}Volim vas.
{74470}{74537}Dûek, niko ne zna da smo tu.
{74595}{74697}Niko nam neÊe doÊi pomoÊi. Moramo|doÊi do ameriËkog veleposlanstva.
{74698}{74783}To Êemo uËiniti. Moûemo mi to.
{74886}{74939}DoÊi Êemo tamo.
{75447}{75533}Znam, znam. Hajde,|zlato. Jesi li dobro?
{75535}{75672}Tako. Ne moûemo ovakvi napolje.|PotraûiÊu nekakvu odeÊu.
{75708}{75761}PogledaÊu uokolo.
{75883}{75942}Nemojte gledati, molim te.
{76199}{76265}Doite ovamo. Nemojte gledati.
{76369}{76423}Ne gledajte dole.
{76643}{76698}Ne svia mi se ovde. Znam.
{76747}{76807}Ostanite ovde.
{77067}{77216}Ne mogu proËitati ovu kartu.|äta traûiö? Veleposlanstvo.
{77716}{77854}Mama, gledaj. äta?|AmeriËka zastava. Bravo.
{77927}{78036}Ovde je ameriËko veleposlanstvo,|ali znaö li gde smo mi na karti?
{78037}{78185}Ovde smo negde. Udaljeni|smo pet ulica i mislim...
{78681}{78729}ZaËepi.
{78827}{78941}Tiöina! Prestani!
{79004}{79093}Ne smeö vikati. Ne smeö...
{79477}{79525}Ne!
{80736}{80794}Joö 10 stuba.
{80859}{80920}Idem po odeÊu.
{82357}{82405}Hajde.
{83282}{83335}Joö nekoliko ulica.
{84567}{84619}Tu skreni desno.
{84997}{85128}Okreni se, Dûek. Gde? Nemoj!|Vratimo se odakle smo doöli.
{85179}{85248}Cure, glave dole.|Stani sa strane.
{85249}{85397}Ne moûemo, sagnite glave.|Dole, dole! Dûek, molim te.
{85544}{85609}Glave dole.
{86378}{86431}Klizim!
{88098}{88151}Ovde? Aha.
{88425}{88549}Ovde se mogu popeti. Idemo. Ne.
{88550}{88643}Stigli smo. Moramo preko. Ovo mi|ne izgleda kao pravo mesto. Zaöto?
{88644}{88740}Ovo su postavili kao|odbranu. Niöta ne Ëujem.
{88762}{88853}PogledaÊu. Ostanite|iza... Ne, sluöajte mamu.
{88855}{88946}Idem pogledati. äta Êeö uËiniti?
{88988}{89080}Budi oprezan. Jeste li dobro?
{89166}{89272}Vidiö li öta? »ekaj|malo, idem bliûe.
{89947}{90004}AMERI»KO AMBASADA
{90900}{90948}Tata!
{91155}{91203}Tata!
{91263}{91311}Ovamo!
{91598}{91646}Hajde.
{91913}{91961}Doite.
{92482}{92591}Ne! Molim vas... Porodica.
{92622}{92750}Molim vas... Porodica. Molim vas...
{92876}{92968}Sve je u redu. Drûite se blizu.
{93120}{93175}Lusi, dole.
{93779}{93843}Ne znamo gde ste! NaÊi vas!
{94723}{94787}Trebamo tu puöku, Ëekajte ovde.
{95223}{95271}Tatice.
{95582}{95704}Ne znam gde! NaÊi|vas! A onda vas ubijem!
{96116}{96250}Dûek, sakrij se. Boûe!|VideÊe ga. Sranje!
{96488}{96573}Cure, tata treba naöu pomoÊ.
{96575}{96664}Bez obzira öto Ëule,|ne mrdajte odavde.
{97030}{97128}Hej! Ovde sam!
{97304}{97356}Dûek, uzmi je!
{97677}{97735}Hej, seronjo!
{98525}{98667}Ne! Ne! Ne!
{98721}{98825}Ne, ne! Maknite se sa mene!
{98890}{98943}UbiÊu...
{99084}{99241}Ne! UbiÊu te, piËka ti|materina! Prokletstvo! Boûe!
{99391}{99480}»ekaj! Nemoj pucati!|Nemoj pucati! Imam novac!
{99481}{99627}»ekaj, imam novac.|Imam novac i oruûje.
{99663}{99811}Mogu vam nabaviti oruûje.|Sung, Sung. Svi vole Sunga.
{99812}{99896}Moji su 1, 3 i 5, a tvoji 2 i 6!
{100084}{100132}Sranje!
{100483}{100631}Boûe! Dobro sam. Rekoh da su|moji 1, 3 i 5. Ali ono tamo je 3.
{100632}{100745}Onaj tamo je 3. Sa tvoje|pozicije on je 2. Nije.
{100746}{100822}Sat je baziran na mojoj|glavi, a ne mojim stopalima.
{100874}{100994}SreÊan? Moûe proÊi. Brzo,|svi, idemo. Ajmo, ljudi!
{100996}{101096}Moramo smesta odavde. Uzmi cure.|Onaj tip Êe se vratiti sa prijateljima.
{101097}{101199}Hajde, dolazi ih joö.|Brzo. Sve je u redu, hajde.
{101200}{101257}Znam za jednu kuÊu|nekoliko ulica odavde.
{101258}{101363}Tamo Êemo biti na sigurnom.|Tu sam, zlato. Mamice!
{101393}{101462}Poûurite! KupiÊu|vam neöto vremena.
{101464}{101593}Hajde. Idemo.
{101671}{101770}Hajde. Ne, ne|ûelim iÊi. Lusi.
{101800}{101921}Ovo nije vreme za raspravu.|Pogledaj me, pogledaj me.
{101948}{102071}Ovo mi je dala moja Êerka kad sam je|poslednji put video. Rekla mi je
{102073}{102188}da mi se niöta loöeg neÊe|dogoditi sve dok to nosim.
{102189}{102303}Uzmi je. U redu? Sad si na|sigurnom. Bez obzira na sve.
{102305}{102380}A Beeze? DelovaÊe i na Beeze.
{102381}{102461}DelovaÊe na obe. Nemaö se|Ëega bojati. Sad si na sigurnom.
{102462}{102567}Budi tiha, brza i blizu nas.|Ozleen si? Imaö tu krvi.
{102568}{102698}Nije moja. Hajde.|Hajde, hajde.
{102784}{102905}Tako. Samo napred.|Idemo po stubama.
{103879}{103971}Kosale. Hamonde. Dobro|je videti te. Takoe.
{103973}{104053}PrenoÊit Êemo ovde, moûe?
{104055}{104129}OK. Dobro. Jeste li|dobro? éelite li Ëaj?
{104130}{104232}Moûe, moûda i koju kap ûestokog.
{104308}{104443}Lepo miriöeö. Ovamo.
{104445}{104591}Evo nas, porodici.|U redu je. Na krov.
{104781}{104871}Uspeli smo. Drago mi je videti|te u jednom komadu, Kenny.
{104874}{104946}Popnite se gore. Hajde, stigli smo.
{104964}{105052}Sigurno umirete od gladi.|Ima dovoljno hrane za sve.
{105053}{105147}Hajde, sednite. Lepo.
{105169}{105217}Bravo.
{105280}{105367}Svia ti se? äto|je to? "äta je to?"
{105369}{105491}Joö nikad nisi probala Kan|»ou piletinu? SvideÊe ti se.
{105492}{105573}PiliÊe hrane groûicama.|Stvarno? Stvarno.
{105575}{105677}Zato su piliÊi slatkog ukusa.|Groûice? Zanimljivo.
{105679}{105781}»ime hrane piliÊe|u SADu? U SADu?
{105819}{105880}Drugim piliÊima, valjda.
{105919}{106048}Mama, tata, moûemo li|popriËati? Tamo. Aha.
{106050}{106106}Pojedite neöto. Hajde.
{106193}{106246}Jedite.
{106302}{106434}Vidite onu tamo reku? Vijetnamska|granica je par kilometara niz reku.
{106435}{106502}Ako uspemo preÊi,|moraÊe nam dati azil.
{106503}{106602}Zatim moûemo sve ovo|ostaviti iza nas. U redu? Da.
{106625}{106711}Hamonde, hvala ti.|Bilo mi je zadovoljstvo.
{106712}{106868}Dûek, idem pogledati klinke. Nisi|ovde samo zbog cura, je l' da?
{106910}{107010}Ma kakvi. Moûda malo.
{107097}{107208}Ti si britanska CIA ili neöto|takvo? Neöto takvo. A Kenny je...
{107309}{107408}Hvala ti. Ne, hvala ti öto|si navratio u pravo vreme.
{107410}{107530}Nemoj mi zahvaljivati. Ja sam|zapoËeo ovo sranje! Kako to misliö?
{107532}{107637}Tipovi poput mene pripremaju|teren za takve poput tebe.
{107639}{107694}ObiËno ne uzvraÊaju udarac.
{107696}{107775}VeÊinu vremena niti|ne kuûe öta radimo.
{107776}{107897}Zaöto? Kako to misliö? Mi|imamo interese na ovom podruËju.
{107899}{107959}Mi? Naöe drûave.
{107989}{108131}Korporacije koje upravljaju njima imaju|interese. Ja se pojavim kao prijatelj,
{108154}{108239}ponudim im pozajmicu za|plaÊanje za naöe usluge,
{108240}{108340}a znamo da si to ne mogu priuötiti.|Zatim izgradimo elektrane,
{108341}{108411}vodovod, autoputa... Nema veze.
{108412}{108477}A kad nam ne mogu vratiti dug...
{108517}{108639}Posedujemo ih. Sjebani pos'o.
{108684}{108783}Voe otpora kaûu da smo|pokuöali porobiti njihov narod
{108785}{108881}kontrolirajuÊi vodovod.|I bili su u pravu.
{108883}{108960}VeÊina onih tamo|nemilosrdnih ljudi...
{108962}{109055}Samo pokuöavaju zaötititi|svoju decu, baö kao i ti.
{109057}{109188}Zato mi nemoj zahvaljivati. Ja sam|onaj koji je ugrozio tvoju porodicu.
{109190}{109278}Najmanje öta mogu uËiniti|jest izvuÊi vas odavde.
{109358}{109491}Je li ono tamo Kan »ou piletina?|Izgleda kao pas. Treba ti snage.
{109520}{109672}I oni trebaju tvoju snagu. Groûice?|»inilo mi se kao fin dodatak.
{109808}{109915}Ubio sam Ëoveka. éiv si, Dûek.
{109917}{110027}Tvoja porodica je ûiva. Nema|tu dobro ili loöe, samo...
{110051}{110114}Samo izbavi svoju porodicu odavde.
{110160}{110290}Hajde. Naspavaj se.|Polazak je za 4 sata.
{110742}{110794}Jesi li dobro?
{111078}{111174}Retrospektivno gledajuÊi, nisam|trebala poneti kuvalo za pirinaË.
{111175}{111263}äaliö se? Nismo|mogli otiÊi bez toga.
{111329}{111416}Hvala ti öto si uz mene|poslednjih nekoliko godina,
{111417}{111547}jer znam da to nije ono öto si|htela, ono Ëemu si se nadala.
{111572}{111645}Da je moj ûivot ispao|onako kako sam htela...
{111675}{111812}Bila bih u Parizu. éivela|bih u stanu na SentSulpiceu.
{111814}{111902}IspijajuÊi vino. ZvuËi dobro.
{112033}{112095}Ali onda ne bih srela tebe.
{112155}{112228}I ne bih poznavala one|prekrasne devojËice.
{112302}{112413}I uzviöenost Ëinjenice|da sam njihova majka.
{112511}{112638}Ovaj ûivot je ispao neöto mnogo viöe
{112698}{112804}nego sam ikad planirala ili htela.
{112921}{113017}Ako sutra ovde|umremo, vredelo je.
{113229}{113285}Pogledaj me...
{113326}{113399}Ovde niko neÊe umreti.
{114269}{114368}Iza zida, iza zida! Sagnite se!
{114386}{114484}Preko puta je toranj sa|strelcima. Ostanite dole.
{114537}{114605}U tornju ih je Ëetvorica.|PrivuÊi Êu njihovu paljbu.
{114606}{114703}TrËite kao ludi prema|stubiötu. Razumete li me?
{114704}{114814}Spremni? »ekaj, Ëekaj.|Spremni? Krenite!
{115600}{115677}Ne! Kroz ona vrata!
{115795}{115897}Boûe! Boûe!
{116857}{116939}Idite dalje! Hajde.|Prijeite granicu.
{117045}{117156}Samo idi. Imat Êeö|ti i bolje dane, Dûek.
{117473}{117526}Idite dalje! Idi!
{117851}{117950}äteta öto neÊu|uspeti! Sranje! Boûe!
{118284}{118405}»ekaj... »ekaj...
{118441}{118529}»ekaj! Doi tatici, govnaru!
{118557}{118605}Govnaru!
{119071}{119165}»ekaj. Samo malo.
{119188}{119306}äta Êemo sad? Ne znam.
{119360}{119438}Ne znam. äta Êemo sad?
{119603}{119651}Ne znam.
{120076}{120184}Pogledaj me. U redu je. Joö|10 stuba, seÊaö se, Dûek?
{120186}{120319}Ostani uz mene. Ostani uz mene.
{120376}{120521}Moramo doÊi do reke. Do|reke! PrijeÊi granicu.
{120523}{120675}Idemo dalje. Spreman?|Do reke, je l' da?
{120678}{120761}Ostani uz mene. U redu, hajde.
{121141}{121193}Stopala me...
{121341}{121431}Eno reke. Idemo.
{122453}{122529}Uite unutra. Brzo, brzo.
{122641}{122738}äta Êemo sad? Ostanite tu.|Idemo do reke po Ëamac.
{122739}{122787}»ekajte ovde.
{123663}{123711}»amac?
{123746}{123870}DaÊu vam sat. Sat za|Ëamac. Evo, gledajte...
{123872}{123992}Zlatni sat. Pogledajte!|Za Ëamac. Hiljadu dolara.
{124090}{124147}Tenisice... éelite tenisice?
{124195}{124252}Tenisice. Gledajte...
{124684}{124740}»ekajte.
{124800}{124848}»ekajte.
{125316}{125409}äta? Gde?
{126706}{126798}Ovde Êemo biti dobro. Mamice.
{127358}{127476}Tata! Tata! Lusi!
{127541}{127594}Tata, pazi!
{127761}{127847}Tata! Ne! Ne!
{127905}{127964}Pusti je!
{128117}{128246}Ne! Molim te! Ona je samo|klinka, prestani! Molim te!
{128248}{128316}Pusti je! Molim te!
{128367}{128437}Ne!
{128470}{128556}Ne! Ne!
{128607}{128702}Ne! Molim te! Stani!
{128764}{128822}UËini to!
{129062}{129136}Lusi, tu sam, tu sam.
{129180}{129285}Zajedno smo! Volim te! Tatice!
{129287}{129396}U redu je. UËini to. Ne,|tatice! Trebamo te.
{129500}{129575}Ne!
{130295}{130368}Gde je Beeze?|Idem po nju.
{130402}{130556}Oprosti, tatice! Bila|si super! Sve je u redu.
{130557}{130669}Sve je u redu.
{130671}{130719}Mamice.
{130806}{130859}U redu.
{130907}{130955}Doite.
{132178}{132261}Sranje! VideÊe nas, Dûek!
{132300}{132385}Sagnite se! Sagnite|se i budite tiho!
{132565}{132647}Vijetnam! Eno Vijetnama. Veslajte.
{132828}{132876}Hajde!
{133128}{133250}Stanite! Ne idite dalje! Nemate|dozvola za ulazak u Vijetnam!
{133252}{133334}Okrenite Ëamac!|Stanite! Ne pucajte!
{133336}{133458}Ne pucajte! Nemate dozvola|za ulazak u Vijetnam!
{133459}{133574}Traûimo azil! Mi smo samo|porodica! Trebamo pomoÊ!
{133575}{133706}Stanite! Ne idite dalje!|Nemate... Nemojte pucati!
{133708}{133850}Vodimo porodica u|Vijetnam! Ne idite dalje!
{133852}{133971}Nemojte pucati! Okrenite Ëamac!|NeÊemo se okrenuti! Nemojte pucati!
{133972}{134020}Nemojte pucati!
{134058}{134161}Spustite oruûje! Ovaj Ëamac|je sad u vijetnamskim vodama!
{134162}{134239}Ako pucate, smatrat|Êemo to ratnim Ëinom!
{134241}{134335}Ovaj Ëamac je sad u|Vijetnamu! Spustite oruûje!
{134957}{135017}Gotovo je.
{137172}{137263}Tatice, hoÊeö li mi|ispriËati priËu o mom roenju?
{137360}{137518}Mislio sam kako bi bila dobra|ideja snimiti poraanje vaöe majke.
{137520}{137662}Rekao sam, "StiöÊi jaËe",|a ona me pogledala...
{137664}{137768}Znate onaj pogled vaöe|mame... "U nevolji si".
{137770}{137914}I onda sam ja izaöla? Onda si ti|izaöla, da. Onda su mi da li po guzici?
{137915}{138006}Sve bebe dobe po guzici, jer|ih pokuöavaje naterati na plaË.
{138007}{138086}Ali ja nisam plakala?|Ona nije plakala.
{138088}{138235}Pa si opet dobila po guzici. I|opet. Onda su ponovo pokuöali.
{138236}{138305}Ali nisam disala. Tako je.
{138322}{138445}Onda je doölo joö lekara|i unijeli su joö aparata i...
{138462}{138564}Sestra je rekla,|"Ugasite tu kameru".
{138666}{138759}A onda me vaö otac pogledao i|rekao, "Moraö porazgovarati sa njom.
{138760}{138882}Moraö joj reÊi neka diöe, jer|poznaje tvoj glas. Glasno.
{138884}{138997}Reci joj". Pa sam poËela|vikati, "Diöi, Lusi.
{138999}{139138}Diöi, mala Lusi, molim te".|I onda sam poËela disati?
{139140}{139233}Aha. I onda si poËeti disati.|Zatim se odneo tvojoj mamici
{139235}{139313}i ona te drûala po prvi put u|svom naruËju, a ja sam rekao,
{139314}{139406}"Ne brini, mala Lusi, dobro|si. Mi Êemo te Ëuvati".
{139695}{139775}Ne budi tuûan, tata. Nisam tuûan.
{139810}{139870}SreÊan sam.
{139921}{139981}Zaista sreÊan.
{140006}{141506}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
