{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{3385}{3433}KreÊite...|- Idemo!
{3574}{3662}Koliko puta je Dûon Vejn bio|kandidovan za "Oskara"?
{3675}{3700}Verovatno ne dovoljno puta...
{3813}{3840}Anelino joö spava.
{3954}{3978}Idem da smenim Eda.
{3987}{4068}Kako moûe toliko da spava?|- Zbog straha.
{4073}{4124}Ma, pusti ga, vaûno je da se|probudi radi svedoËenja.
{5039}{5099}Ne...
{5305}{5339}Traûili smo te.
{5410}{5491}HoÊeö da budeö svedok?|Gledaj onda ovo...
{5742}{5839}Roendan mu je za dve nedelje.|- Hari, oni bi da ga iznesu.
{6054}{6150}27 godina gledam ovakva sranja|i joö se nisam navikao.
{6263}{6332}HoÊu popis svih kojih su bili na|obezbeenju, i svih koji...
{6335}{6421}...su mogli da znaju neöto o tome|od javnog tuûioca...
{6426}{6458}...do öefa policije.
{6501}{6570}Oni su mrtvi, Majk...|Moramo neöto da uradimo.
{6614}{6741}äta god da je potrebno...|Oni su mrtvi!
{7518}{7591}SUROVI UGOVOR
{7818}{7989}Tel: 063/8 107 692|E-mail: novdan@ptt.yu
{11344}{11441}Mnogi stanovnici su se ûalili|zbog smeÊa oko gradiliöta.
{11460}{11574}Mislim da bi trebalo da uËinimo|neöto po tom pitanju. Prijatno.
{11788}{11839}Uhvatio si kopile!|- Na delu.
{11849}{11897}Sere, iöao sam na maskenbal.
{11914}{11993}Zaustavio je neke ljude|zbog prebrze voûnje.
{12006}{12050}Traûio im je 50 dolara|da ih pusti.
{12056}{12087}Zaustavili su se da bi me|pitali za pravac!
{12089}{12208}Uhapsi ga za laûno|predstavljanje, opiranje...
{12210}{12274}...hapöenju, prevaru,|ugroûavajuÊu voûnju...
{12278}{12320}...i laganje öerifa.
{12357}{12403}BiÊu kod kuÊe ako vam budem|trebao. - U redu, öerife.
{12519}{12545}Hajde, pseto.
{13130}{13213}Ejmi! Ejmi...!
{13338}{13366}Ejmi!
{13553}{13600}Jel mi to spremamo ûurku?|- Naravno!
{13620}{13693}I drago mi je öto si stigao|na vreme da uËestvujeö.
{13705}{13763}Da li Êemo biti sami,|ili dolazi joö neko?
{13780}{13831}Naravno da Êemo biti sami.
{13878}{13936}A, öta to slavimo?
{13952}{14074}Komemoraciju...|naöe pete godiönjice braka.
{14104}{14199}5 godina u izgnanstvu,|zakopani u ovoj rupi gde...
{14222}{14358}...Ëovek moûe da razgovara|samo o ûivotu i vremenu.
{14362}{14422}NeÊe biti tako zauvek.|- –avola neÊe!
{14468}{14567}Prestani veÊ jednom.|Ovo je najbolje reöenje.
{14597}{14675}–avola! Joö si mogao|da radiö za FBI.
{14680}{14720}Joö smo mogli da|ûivimo u Njujorku.
{14724}{14758}Nisi morao da|napustiö posao!
{14761}{14795}Dali su mi priliku|da dam ostavku.
{14809}{14847}Da nisam, iöao bih na|suenje, izgubio bih ga!
{14852}{14883}Bio bih izbaËen!
{14899}{14950}Ne bih imao öanse ni|ovaj posao da dobijem!
{15251}{15280}äta ima za veÊeru?
{15328}{15360}Samo ovo.
{15492}{15528}Od toga Êemo|da se ugojimo.
{15536}{15606}Misliö da ako smo u|kondiciji nismo i debeli?
{15617}{15676}Mi smo kao krave koje|se gaje ovde u okolini.
{15691}{15761}Nemamo izbora,|mi smo ûrtve okolnosti!
{15778}{15872}Znaö li ti koji je kravin najveÊi|doprinos ovome svetu?
{16006}{16040}Govno!
{16171}{16234}Ne bi trebalo da|pijeö dok kuvaö.
{17595}{17649}Zdravo, Martine.|- Da...?
{17676}{17720}äenon ovde.|Hari äenon.
{17747}{17853}Odavno se nismo Ëuli, Hari.|äta ima novo?
{17858}{17905}HoÊu da razgovaram sa tobom.|Imam problema.
{17928}{18007}PriËaj.|- Ne, ne preko telefona.
{18029}{18066}Imam vremena samo za|takav razgovor.
{18090}{18131}äta je, ne ide|ti baö najbolje?
{18157}{18188}Imao sam i boljih dana...
{18215}{18292}Ako hoÊeö da ih ponovo|imaö, moramo se videti.
{18995}{19073}BRA»NO SAVETOVALIäTE
{19145}{19208}Biro se uvek pobrine da mesto|sastanka bude neupadljivo.
{19258}{19287}Ovo nema veze sa njima.
{19337}{19491}G. PETROVITA, VI PORI»ETE BILO|KAKVU VEZU SA ORGANIZOVANIM...
{19494}{19634}...KRIMINALOM. ZA PROäLU GODINU|STE PRIJAVILI PRIHOD OD 73 000 DOLARA.
{19638}{19784}OD TOG NOVCA VI IMATE|VILU OD 7 SOBA U »IKAGU,
{19794}{19903}VIKENDICU U VISKONSINU, ZIMSKU|REZIDENCIJU U KALIFORNIJI,
{19909}{20026}4 KADILAKA ZA KOJE ZNAMO I|VODITE éIVOT PREMA KOJEM JE...
{20031}{20073}...ROKFELER OBI»AN PROSJAK.
{20087}{20218}MOéETE LI NAM OBJASNITI KAKO VAM|SVE TO USPEVA SA SAMO 73 000 DOLARA?
{20223}{20280}Stani, pa to je Bakster!|- Znam, znam...
{20291}{20325}Pa, kakve on veze|ima sa tim?
{20330}{20369}On je specijalni|federalni tuûilac.
{20373}{20412}Taj kuËkin sin mi je|upropastio karijeru!
{20418}{20493}Sluöaj, ti si doveo osumnjiËenog|sa pola polomljenih kostiju.
{20497}{20570}Svaki tuûilac bi te za to tuûio.|- Pa, seÊaö se tog sluËaja!
{20574}{20633}Taj tip je kidnapovao|devojËicu od 11 godina.
{20641}{20695}MuËio je, ubio|i raskomadao.
{20737}{20815}U to vreme javnost nije|volela previöe grube policajce.
{20828}{20909}Bakster je ûeleo moju koûu.|Pokuöao sam da razgovaram...
{20913}{20943}...sa njim, da mu objasnim|öta se dogodilo...
{20949}{20979}I, öta ti je rekao?
{20982}{21046}"Daj ostavku ili Êemo|te tuûiti. Biraj."
{21082}{21214}Pa sad, prema Petroviti je gori|nego öto je bio prema tebi.
{21236}{21282}IMAM PUNO DUGOVA!
{21344}{21403}KOME?|- PRIJATELJIMA.
{21435}{21491}KAO äTO SU PAOLO ROKA I|BIL ROSMEN?
{21602}{21647}POZIVAM SE NA 5. AMANDMAN.
{21684}{21794}To je Lu Petrovita. On je öef|najjaËe »ikaöke porodice.
{21963}{22076}G. ROKA, VAä IZVOR PRIHODA JE|VAäA TURISTI»KA AGENCIJA.
{22081}{22230}ALI, I VAä STIL éIVOTA PRELAZI|VAäE PRIJAVLJENE PRIHODE.
{22234}{22347}DA LI BISTE NAM OBJASNILI|ODAKLE VAM TOLIKI NOVAC?
{22374}{22455}POZIVAM SE NA 5. AMANDMAN.|TO ∆U URADITI I SA SVAKIM VAäIM...
{22458}{22574}...NAREDNIM PITANJEM. »ASNI LJUDI|NE MORAJU DA TRPE OVAKVO...
{22577}{22689}...MALTRETIRANJE. - HVALA äTO STE|NAS PODSETILI NA NAäA PRAVA.
{22708}{22737}Roka je pogrebnik.
{22759}{22835}Ko god smeta Petroviti,|Roka ga eliminiöe.
{22859}{22899}Dobro, sada smo videli|ko je ko u »ikagu.
{22932}{22990}Ti si u birou.|äta hoÊeö od mene?
{23100}{23220}Da li se seÊaö mog sina?|- Blera? Da.
{23258}{23373}Zajedno smo igrali fudbal.|I on je sada u birou.
{23435}{23512}Da.|Kako je on?
{23649}{23679}Mrtav...
{23854}{23958}HoÊu Petrovitu!|- On je ubio Blera?
{23975}{24060}Bler je Ëuvao vladinog svedoka|koji je zauvek mogao da...
{24066}{24102}...ukloni to kopile.
{24184}{24264}Petrovita je izdao|nalog za ubistvo.
{24289}{24350}Pa, öta tu moûe da|uradi mali provincijski öerif?
{24375}{24525}Ovo nema veze sa biroom.|Ja sve finansiram.
{24537}{24622}Imam 45.000 dolara|uöteevine...
{24666}{24806}éelim da se uvuÊeö u njihovu|organizaciju i rasturiö je.
{24834}{24895}Na koga ti ja liËim?|Na Prljavog Harija?
{24902}{24946}LiËiö mi na|nesreÊnog Ëoveka.
{24958}{25076}Imaö li lek? - MoguÊnost|ponovnog zaposlenja u birou.
{25143}{25175}Kako?
{25190}{25253}Biro pokuöava veÊ godinu dana|da ubaci svog Ëoveka u...
{25257}{25325}...Petrovitinu organizaciju,|ali neko odaje tajne.
{25345}{25454}Sve naöe momke sreuju.|Zato, niko osim mene neÊe...
{25462}{25528}...znati za tebe.|Niko.
{25555}{25658}Obavi ovaj posao,|i na konju si.
{25692}{25722}äta misliö?
{25765}{25815}Misliö li da Êu proÊi na|proveri kondicije?
{26908}{27013}Ovde Kominski. Istraûujem|provalu u skladiöte benzina.
{27046}{27076}PRIMLJENO.
{29013}{29084}éAO MI JE äTO SI MORAO DA SE|UBIJEä NA ONAKO GADAN NA»IN,
{29087}{29201}ALI TAKO JE SIGURNIJE.|NA GORNJOJ SLICI JE LUI–I...
{29205}{29370}...PETROVITA. U POSLU JE PREKO|20 GODINA. PAMETAN JE.
{29435}{29538}NJEGOVA DESNA RUKA JE TIP PO|IMENU ROKA. UBIJA ZA SITNICU.
{29573}{29739}NJEGA SE »UVAJ. LAéNE ISPRAVE|KOJE IMAä ODGOVARAJU »OVEKU...
{29745}{29831}...KOJI IMA DEBEO DOSIJE|U POLICIJI.
{29836}{29887}TELEFONSKI BROJ JE ZA|OSTAVLJANJE PORUKA.
{29891}{30026}JAVI∆E TI SE AUTOMAT.|25.000 DOLARA JE ZA TROäKOVE.
{30065}{30216}NA SLICI JE NOVA FACA, LAMANSKI|KOJI PODRIVA PETROVITINE...
{30219}{30389}...POSLOVE. MOéDA BI NAJBRéE|USPEO KAD BI NAPAO LAMANSKOG.
{30420}{30560}NE ZABORAVI, NEKO ODAJE TAJNE.|ZBOG NJEGA JE UBIJEN BLER.
{30593}{30691}ON JE TAJ KOGA JA éELIM.|PA, VIDIMO SE U »IKAGU.
{31513}{31587}Mislim da sto nije u redu.|HoÊu da vidim g. Lamanskog.
{31597}{31680}On nije tu, a svi koji gube|uvek misle da sto nije u redu.
{31698}{31724}Ponekada su i u pravu.
{31845}{31931}Sranje.|- Hej, pa sto je "sreen".
{32079}{32172}Magija? Magnet!|- Policija!
{33682}{33749}Momci, sredite nered pre nego|öto zatvorite radnju.
{34722}{34768}UbiÊu to kopile!
{34950}{35021}Izvinite, moûete li|da se malo pomerite?
{35054}{35101}Niste upalili svetla...|- Hvala.
{35321}{35358}O, sranje.
{36228}{36398}Ovo sastajanje je skupo, jer|moje vreme vredi koliko i vaöe.
{36406}{36467}Tvoje vredi viöe,|jer ga manje imaö.
{36478}{36575}Pristao sam na ovaj razgovor|jer dugo godina radiö za mene.
{36596}{36687}Kao öto sam rekao,|zatvaraj sve i gubi se!
{36696}{36758}InaËe, jednog jutra Êeö|se probuditi mrtav.
{36762}{36851}Ali, ja imam obaveze...|Ima dovoljno za obojicu.
{36855}{36919}Nema dovoljno za obojicu,|samo za mene.
{36954}{36997}Imaö 2 dana.|- I öta onda?
{37011}{37047}Ponovo da radim za vas?
{37080}{37203}Ti ovde viöe ne radiö, ni za|mene, ni za bilo koga drugog!
{37574}{37605}SPREMNI!
{37821}{37850}Dole!
{38249}{38348}Prokleti Lamanski!|äta on zamiölja da je?!
{38420}{38498}To kopile je ludo!|Jebeni amater!
{38506}{38628}Nema pojma ni o Ëemu! Samo|je dûaba troöio metke!
{38676}{38792}Toni je bio dobar momak.|Nai mu dobru zamenu.
{38801}{38838}KuËkin sine!
{39454}{39515}Drugar, u pogreöna si kola|uöao. - Zaveûi!
{39523}{39583}Znaö li ti kome...ona|pripadaju?
{39586}{39653}Njihov gazda Êe sigurno biti|mrtav pre isteka garancija.
{39936}{40034}äta vi radite ovde?|»ekam tebe. Vozi!
{40136}{40193}äta hoÊete?|- Da vam uzmem sav nakit.
{40218}{40289}Znate li ko ga je kupio?|- Lamanski.
{40321}{40409}On ima ukusa öto se nakita tiËe,|ali vi nemate za ljude.
{40678}{40718}Dobra devojka...|I ostalo.
{41317}{41362}KuËkin sine!
{41845}{41885}Dole.|- Nema nikakvo dole.
{41926}{42002}Ja nisam policajac.|Ja sam igraË.
{42404}{42502}äta vam treba?|- Par minuta sa g. Rokom.
{42530}{42570}To nije moguÊe.
{42581}{42635}Recite mu da sam ja|Lamansijev problem.
{42669}{42698}SaËekajte ovde.
{43194}{43285}Gubitak poboljöava karakter.|- A dobitak - garderobu.
{43947}{43976}Uite.
{44327}{44409}Kako se zoveö?|- Dûozef P. Brenon.
{44466}{44640}ZnaËi, ti si Lamanskijev|problem. Rasturio si mu lokal...
{44685}{44730}Ovo je pripadalo|njegovoj devojci.
{44808}{44868}Zaöto si to uradio?|- Zastraöivanje.
{44889}{44935}Da mu pokaûem da|niöta nije bezbedno.
{44940}{44979}äta pokuöavaö time da|dokaûeö?
{45025}{45173}Dûoi, ovo je Maks Keler. On|sreuje stvari... sve stvari.
{45198}{45247}HoÊete da kaûete da bi mogli|da me iskoristite?
{45263}{45370}Za öta?|- Za sreivanje stvari.
{45426}{45500}To mesto je popunjeno.|- Siguran sam da pametni ljudi,
{45504}{45547}kao öto je g. Roka, brinu|o poboljöanju radne snage.
{45551}{45584}Ja sam najbolji|u tom poslu.
{45594}{45720}Maks, da si ti najbolji|ja ne bih postojao.
{45790}{45827}Kako si znao da|traûimo ljude?
{45833}{45921}Nisam znao. Mislio sam|da Êu imati sreÊe.
{46002}{46030}Odakle si?
{46067}{46174}Poslednjih godina... Majami.|- Imaö li preporuke?
{46193}{46278}Imam dosije. Siguran sam da|moûete pronaÊi par pandura...
{46283}{46323}...koji bi mogli|to da vam potvrde.
{46327}{46387}Zaöto misliö da ûelim|da sredim Lamanskog?
{46428}{46617}Lamanski se svake nedelje|sve viöe razmahuje.
{46643}{46707}Znam da time otima|od nekog drugog.
{46833}{46927}Idi na blagajnu i neka ti|daju 1000 dolara u Ëipovima.
{46948}{47074}Zabavi se malo.|- Ako zaboravite...doÊi Êu opet.
{47401}{47448}Ja mu ni reË|ne verujem.
{47536}{47658}IzviaËi izgrauju karakter,|a i mnogo je jeftinije.
{47703}{47754}Ne gnjavi me,|traûiÊu da te izbace.
{47775}{47859}Poznata si ovde?|- Znaju me.
{47882}{47986}Baö im zavidim. NeÊe im smetati|ako kreneö kuÊi pre nego...
{47990}{48063}...öto sve prokockaö?|- Ne brini ti o mom novcu.
{48069}{48110}Kad god mi treba,|ja dobijem.
{48142}{48239}Probaj sa tuim novcem da|igraö. Moûda ti donese sreÊu.
{49054}{49145}Gde li je ovaj poöao?|- Moûda da piöa?
{49286}{49338}Hajdemo.
{49399}{49479}Ako joö neko krene tamo|poËeÊu da prodajem ulaznice.
{50443}{50499}Hajde!
{50642}{50680}Beûimo!
{50753}{50789}Brûe!
{51001}{51125}Problemi?|- Niöta posebno.
{51154}{51207}Imas li liËnu kartu?|- Naravno.
{51263}{51317}Video sam trojicu kako|kreÊu za tobom.
{51351}{51449}Neöto liËno,|ili obiËna pljaËka?
{51458}{51501}Nisu stigli da mi kaûu|öta hoÊe.
{51575}{51648}Dûozef P. Brenon...|äta znaËi ovo "P"?
{51688}{51720}PiËka!
{51774}{51824}VideÊemo se...
{51871}{51967}Hari, sve ide po planu.|Stan je dobar...
{52007}{52131}Sutra iznajmljujem kola.|Neöto se desilo sinoÊ öto me...
{52134}{52213}...nateralo da razmiöljam.|Mogao bih da doem u situaciju...
{52216}{52289}...da panduri pucaju na mene.|Kako onda da se ponaöam?
{52311}{52436}Tri tipa su me sinoÊ napala.|Mislim da Maks stoji iza toga.
{52466}{52582}Roka me sigurno proverava.|OstaÊemo u kontaktu...
{53105}{53214}Zdravo, kada si se poslednji|put dobro ispiöao?
{53722}{53753}Pusti me unutra,|moram da piöam.
{53801}{53912}Ne mrdaj!|Policija!
{54364}{54435}Imate nalog?|- Ja imam nalog, ti imaö svoja...
{54438}{54484}...prava, a Petrovita Êe imati|jebenu glavobolju!
{54648}{54717}Zovite predsednika. Mislim da|smo upravo reöili naö deficit.
{54808}{54883}Propalo je 100 miliona dolara.
{54928}{54977}NadoknadiÊemo to za|par nedelja.
{55110}{55160}Upravo to je trebalo Lamanskom.
{55199}{55322}Sada Êe nam oteti|veliki deo trûiöta.
{55371}{55411}Zaöto ga jednostavno|ne sredimo?
{55433}{55567}On to i traûi. Ne prilazi mu,|ako ne misliö da poËneö rat!
{55627}{55726}To nikome nije potrebno.|Kasnije...
{55815}{55872}Koliko ih je uhapöeno?|- Osmorica.
{55884}{55954}Niko nije upotrebio oruûje.|Svi Êe se izvuÊi uz kauciju.
{56044}{56162}Jesi li naöao zamenu za Tonija?|- Proveravam jednog tipa.
{56267}{56331}NoÊu novac natrag.|- äta?
{56349}{56427}Novac, droga, moje je!|HoÊu to nazad.
{56432}{56492}Kako to da uradimo? Da|opljaËkamo gradsku veÊnicu?
{56506}{56554}Ne znamo ni gde se|nalazi taj novac.
{56564}{56620}Znam nekoga ko Êe nam|reÊi gde se to nalazi.
{56632}{56714}Droga je moja, platio sam|za nju, i hoÊu je natrag!
{56820}{56856}I dobiÊu je.
{56989}{57032}Kako to da nikada nisi|bio u zatvoru?
{57041}{57109}Ja sam pametan.|Ne kao neki ovde...
{57150}{57252}Maks misli da izazivaö nevolje.|Ne ûeli te u blizini.
{57260}{57342}Maks pravi greöke.|- Nikada dva puta istu.
{57419}{57537}Primljen si.|Privremeno...
{57720}{57807}Ako je Maks u pravu,|joö kraÊe.
{57957}{57983}PoËinjeö sutra.
{58037}{58090}Lepo je biti Ëlan porodice.
{58199}{58235}Moja kola, molim.
{58325}{58367}Sem, pozovi mi taksi.
{58513}{58603}Kako ste proöli ono veËe?|- Vaö novac mi nije pomogao.
{58628}{58697}A, veÊeras?|- Imam samo za taksi.
{58722}{58780}Moûda treba da probate drugu|vrstu rekreacije.
{58838}{58903}Gubitak u tenisu|me neÊe odobrovoljiti.
{58913}{58956}Ali, dobra veûba bi mogla.
{59243}{59294}NeÊete nam trebati.|Hvala.
{59358}{59414}Vi baö umete da vodite|raËuna o svemu.
{59766}{59919}Ne znam zaöto reklamiraju|tablete za spavanje?
{59994}{60099}Par flaöa öampanjca|imaju mnogo bolji efekat.
{60216}{60315}HoÊeö da kaûeö da|si spreman za krevet?
{60356}{60467}Mislim da jesam. - Mislim da Êe|ovo biti veoma burna noÊ...
{60980}{61058}Znaö öta mi se svia kod|spavaÊih soba? - äta?
{61063}{61127}Skoro uvek imaju krevet.
{61209}{61334}Znaö öta? I ja sam primetila|potpuno istu stvar.
{61816}{61861}O, Boûe!
{62081}{62113}Sjajno.
{62475}{62804}Naöla sam. Dûozef P. Brenon.|Licni broj 567345787...
{62840}{63015}VozaËka dozvola, broj...|48736892-R
{63061}{63319}Pasoö... H-1032642. U redu?|On spava.
{63435}{63555}Ovo sreuje moj dug od|1000 dolara koje ti dugujem.
{63644}{63709}Ako budem imala neöto da ti|kaûem, nazvaÊu te.
{64145}{64247}Hteli smo da proverimo vaö bojler, ali kljuËevi nisu bili...
{64250}{64414}...tamo gde je trebalo da budu.|Proveri gde su, i javi mi.
{64502}{64645}Saznaj öto pre kako znaö,|kako se ne bi smrz'o u vodi.
{64677}{64729}Jebeni mali crv!|- äta mu je?
{64745}{64816}Dali smo mu milion dolara da|kaûe gde su krili svedoka.
{64820}{64864}Sada taj kuËkin sin hoÊe|da se povuÊe!
{64886}{64927}Moûda ne zna gde je|droga smeötena.
{64943}{65010}Na koliko mesta misliö da su|panduri mogli da smeste...
{65013}{65106}...toliku koliËinu love i droge?|Ako ne zna, neka sazna.
{65129}{65186}Moûda mu se ne dopada|to öto si naumio.
{65222}{65335}Boli me öta on misli!|ReËi Êe nam on veÊ...
{65341}{65423}Nema izbora, jer se veÊ|zaglibio do guöe.
{65445}{65490}Nema naËina da te nagovorim|da odustaneö?
{65513}{65578}Da ima, ne bih bio|ovde gde jesam.
{65596}{65681}»im pomislimo da ima neöto öto|ne moûemo da sredimo, öto je...
{65687}{65775}...preveliki zalogaj za nas,|treba da se Ëistimo.
{65804}{65954}Ovo je kao rvanje. Sve je|nameöteno. Panduri uvek gube.
{67062}{67109}Gde je Mecke?|- Nisam ga video.
{67125}{67202}Kako ide posao?|- Umiremo.
{67489}{67515}To je on!
{67735}{67786}Hej!|- Pazi malo!
{68307}{68330}Doi ovamo!
{68405}{68472}»ujem da svima plaÊaö,|sem nama?!
{68476}{68533}Lamanski mi preti da Êe|da mi zapali lokal!
{68538}{68672}Nisam znao da imaö toliko love.|- Nemam, posao slabo ide...
{68735}{68782}Ti si obiËno govno!
{69085}{69197}Ovako Êeö izgledati kada te mi|sredimo! Ne plaÊaj Lamanskom!
{69219}{69279}InaËe Êu te pretvoriti|u govno!
{69330}{69371}Joö jednom mi se nai|na putu i ubiÊu te.
{69381}{69430}Nadam se da ti majka|nema joö dece.
{69495}{69545}G. Mecke, da li ste dobro?
{69814}{69891}Zvali su nas.|Kaûu da ovde ima nekih problema.
{69908}{69966}Momci imaju problema|sa öminkanjem.
{69972}{70083}Dûozef P. Brenon, ti se|uvek pojaviö na nezgodnom mestu.
{70100}{70137}Snalazim se nekako...
{70150}{70221}Pa, naöao si dobrog vodiÊa.
{70312}{70397}Odakle poznajeö tog pandura?|- Od one tuËe u prolazu.
{70406}{70465}Neka tri tipa su htela|da me rasture.
{70641}{70725}Ne znam kako se zove, ali sam|siguran da radi za Petrovitu.
{70730}{70840}NeÊu njegovo ime, veÊ glavu!|- PostaraÊu se da nestane.
{70869}{70996}Prvo ga dobro sredi,|za primer ostalima.
{71148}{71193}Jebem ti ovakvu gru!
{71209}{71246}Izgleda da Êe biti zabavno.
{71263}{71347}Ne mora da znaËi.|- Zar on nije dobar domaÊin?
{71360}{71432}Neki njegovi gosti znaju da|budu strahovito dosadni.
{71436}{71536}Ako budeö imala problema,|samo mi reci.
{72032}{72113}Dûoi...|drago mi je da si doöao.
{72174}{72199}Veliki prijem.
{72231}{72295}Ovo je samo sastanak|uûe porodice.
{72304}{72448}Luii hoÊe da te upozna.|- VraÊam se.
{72614}{72676}Hej, jel se dobro zabavljate?|Ja se sjajno zabavljam.
{72697}{72735}OvekoveÊi ovaj trenutak.
{72789}{72863}Maks, moûda se|previöe zabavljaö.
{72879}{72907}Jedi neöto.
{73011}{73101}PoslaÊu ti jednu, uramljenu.|- Zadrûi, nisam sentimentalan.
{73208}{73238}Ui.
{73469}{73537}Dûoi Brenon.|Luii Petrovita.
{73558}{73587}Drago mi je.
{73669}{73765}Suviöe si blizu mog prijatelja.|- HoÊeö da dobro obavim posao?
{73782}{73851}äta si saznala?|- Niöta.
{73956}{74044}éelim te...|- Pokuöali smo to, seÊaö se?
{74061}{74185}Hajdemo kod mene.|- Mislim da nema svrhe.
{74224}{74364}G. Roka misli da Êete biti|dobra ispomoÊ naöim ljudima.
{74388}{74467}I ja tako mislim.|- A, vi ste mislilac.
{74476}{74551}Ponekad. Dovoljno da|ne upadnem u nevolju.
{74558}{74651}Koliko znamo, ne zadrûavate se|dugo na jednom mestu.
{74658}{74808}Kada nemaö nekoga da te ötiti,|najbolje je biti u pokretu.
{74818}{74854}On trazi dom.
{74927}{75037}Da li si nekoga ubio do sada,|Dûoi? - Da.
{75128}{75215}Viöe od jednog?|- Trojicu.
{75237}{75278}HoÊete imena i adrese?
{75536}{75657}Volim pametne momke,|ali ne i pametnjakoviÊe!
{75741}{75839}U redu, vrati se na prijem.|HoÊu da razgovaram sa g. Rokom.
{75904}{75943}Drago mi je öto smo|se upoznali.
{76147}{76173}Ne znam...
{76305}{76369}Ne dozvoli mu da previöe|brzo napreduje.
{76379}{76432}Daj mu malo vremena|da ostavi utisak.
{76458}{76563}Ako ne uspe, upotrebiÊemo ga|za neöto prljavo i ubiti ga.
{76567}{76691}Slatka, a?|Kakva lutka...
{77078}{77197}äta misliö, je li dobra?|- I ja bih izabrao tu istu.
{77223}{77333}Ta je po mom ukusu. - Stvarno?|Da li ti se ova viöe dopada?
{77374}{77460}Probaj je.|- Ne zameraö öto sediö ovde?
{77464}{77498}Ma ne, uûivam u tome.
{78068}{78123}Izaberi jednu, ja ne mogu|da se odluËim.
{78127}{78178}Zaöto ne kupiö obe?|- Nemam para za obe!
{78251}{78369}Imam ja.|- Ti to zaista olako radiö...
{78393}{78448}Jesi li uvek takav kavaljer|prema damama?
{78490}{78519}VeÊ odavno nisam|imao priliku...
{78524}{78569}Poljubi je za zbogom,|drkadûijo!
{78647}{78709}Ovo je pljaËka.|Zovite obezbeenje.
{78744}{78785}Idi veÊ jednom!
{79514}{79549}...upravo se tuku...
{80189}{80229}Nemam vremena da probam.
{80281}{80395}Ovuda! - Ne, ovuda!|- Zavröili smo sa kupovinom!
{80771}{80834}Smisli neöto!|- Kad bi bilo moguÊe, u öta...
{80838}{81009}...nisam siguran, zahtevalo bi|veliku pripremu.
{81012}{81068}Imamo plan prostorija.
{81073}{81128}PotkupiÊemo Ëoveka unutra|i idemo!
{81134}{81215}Naö Ëovek ne samo da mi je|rekao gde je, veÊ mi je rekao...
{81220}{81306}...i da ga sele sledeÊeg|utorka u federalni trezor.
{81327}{81416}O, Boûe! Ovo je ludost!|- Proöle nedelje je neko u...
{81419}{81477}...Njujorku ukrao kokain u|vrednosti od 10 miliona dolara...
{81480}{81566}...iz policijske stanice i otiöao!|Niko ne zna gde je!
{81571}{81694}To je uradio neko iznutra, a mi|govorimo o velikoj pljaËci!
{81730}{81869}U toj zgradi ima 50 pandura,|po ceo dan i noÊ!
{81872}{81932}Kako da ih izmamim? Da im dam|karte za utakmicu?!
{82035}{82069}Bomba...
{82206}{82244}Da dignemo sve u vazduh, a?
{82347}{82374}Genijalac...
{82432}{82462}O Ëemu priËaö?
{82470}{82532}Pretnja o podmetnutoj bombi.|Kad god dobiju takvu pretnju,
{82538}{82647}moraju da evakuiöu zgradu.|- Da, naravno...ako poveruju.
{82662}{82752}Takve pretnje stalno dobijaju.|Otkud znaö da Êe nasesti?
{82760}{82824}UËinite ih nervoznim. Neka|pomisle da neki ludak hoÊe da...
{82828}{82878}...raznese svaku policijsku|stanicu u gradu.
{83341}{83427}Hej, kuda?|- Do aparata za Koka-kolu.
{83458}{83537}Treba da ga popravimo.
{83623}{83657}Ovde narednik Mort.
{83774}{83807}U redu, gospoo,|gde se nalazite?
{83835}{83863}Ima li povreenih?
{83892}{83933}PoslaÊu nekoga.
{85040}{85117}Izgleda da nisu nameravali da|celu zgradu dignu u vazduh.
{85124}{85169}Moûda je bomba bila|loöe napravljena.
{85229}{85315}äta ti radiö ovde, Hari?|- Nadam se da ovo nije delo...
{85321}{85441}...nekog maloumnog teroriste,|pa da Biro ostane po strani.
{85560}{85597}Zdravo, Hari.
{85656}{85695}Zdravo, Martine.
{85710}{85811}Ja sam dobro, a ti?|- NeÊe mi pomoÊi ako se ûalim...
{85850}{85936}äta ti misliö o ovome?|- Da je neko bio ljut na...
{85939}{85976}...automat za Koka-kolu.
{86001}{86089}Nego, moûete li vas dvojica da|kibicujete napolju? Smetate...
{86124}{86183}Pa, kako napredujeö|u sluËaju Petrovita?
{86194}{86228}Svaki dan pokuöavamo|neki novi prilaz.
{86236}{86304}Veruj mi, njemu Êe pre|puËi film neko nama.
{86318}{86385}Meni je veÊ pukao.|- Niko te ne krivi zbog toga.
{86388}{86422}Zato su te i skinuli|sa tog sluËaja.
{86436}{86502}Da, ali ja imam i svoje|slobodno vreme.
{86541}{86637}Ne meöaj se, Hari. Moûda mi|imamo plan za koji ti ne znaö.
{86653}{86744}Kladim se da, öta god da|planirate, neÊe uspeti.
{86771}{86846}Trudimo se koliko moûemo.|- Da. I ja...
{86876}{86907}Znam da imaö liËnog interesa|u ovom sluËaju, ali obojica...
{86909}{86979}...traûimo isto...|pravdu!
{87017}{87070}Jel tako, Hari?|Pravdu...
{87073}{87111}Jebeö pravdu !
{87468}{87593}äta ima novo na zadatku?|- Nisam joö otkucala izvestaj.
{87718}{87781}SeÊaö se onog konja koji ti se|dopadao? Kupio sam ga.
{87814}{87952}äta ti je na umu, Maks? - Ti...|I öta radiö sa onim tipom...
{87981}{88075}To je bila tvoja ideja. - Nisam|znao da Êe to tako daleko da...
{88077}{88143}...dogura.|- A koliko je to?
{88198}{88303}Diûe li ti noge pet puta|dnevno? - Stvarno hoÊeö da znaö?
{88310}{88354}Ne, nego da li|bih i ja mogao?
{88390}{88448}Jedini naËin da ti i ja legnemo|zajedno je da nas...
{88454}{88495}...pregaze ista kola.
{88573}{88681}Ne volim kada me vreaö,|mala. - Ja volim...
{88698}{88794}Ja ree dajem, nego öto uzimam.|VraÊaj to!
{88931}{89050}Maks, mislim da neÊemo biti|dobri drugovi, a hteo sam.
{89282}{89311}Impresionirana sam...
{89344}{89391}A ja sam gladan.
{89489}{89551}äto se duûe poznajemo,|ti me sve viöe izbegavaö.
{89581}{89659}Jel to tvoj naËin muvanja,|ili si to proËitao negde?
{89668}{89741}Maks Êe se vratiti sa|pojaËanjem, a ja ne ûelim...
{89744}{89785}...da ti budeö u blizini|kada se to desi.
{89992}{90022}Sviaö mi se...
{90072}{90130}Moûda viöe nego öto se ja|tebi sviam. Ne znam...
{90172}{90263}Ako mi ne kaûeö da si oûenjen,|ili neöto sliËno, ne odustajem.
{90498}{90588}Oûenjen si?|- Odavno...
{90840}{90908}Gde je ona?|- Daleko odavde...
{91079}{91185}To je olaköanje... VeÊ sam|mislila da je beznadeûno.
{91199}{91357}Priroda te tako obdarila, a ti|niöta. Zabrinula sam se.
{91360}{91468}Ti mi mnogo znaËiö. Mi smo|prijatelji i viöe od toga!
{91473}{91492}Prijatelji?!
{91516}{91551}Mi smo prijatelji.
{91616}{91679}Kada budem htela prijatelje,|prijaviÊu se u "Fortunu".
{91950}{91990}HoÊeö da Ëujeö|neöto smeöno?
{92031}{92130}Bila sam polaskana... Mislila|sam da polako napredujeö,
{92139}{92201}jer ti je zaista stalo do naöe veze,|jer nisi hteo da je uprskaö.
{92440}{92541}Dugo Êe mi trebati da shvatim|ko je od nas dvoje veÊi seronja!
{93144}{93180}Cela stvar moûe|da propadne.
{93198}{93242}Petrovita hoÊe da|sredi Lamanskog.
{93270}{93341}Dok god se meusobno|tamane, boli me uvo.
{93365}{93445}Petrovita hoÊe drogu i lovu|koju su mu panduri zaplenili.
{93459}{93524}Znam da Êe to i dobiti.|- äaliö se?
{93647}{93691}Znaö li öta Êe se desiti ako|pokuöaö da ih zaustavis u tome?
{93695}{93794}Da... Ja sam novi, i misliÊe|da ja odajem tajne.
{93796}{93870}Pusti ih neka to izvedu.|Naö cilj je neöto sasvim drugo.
{93878}{94098}A, Lamanski? - Pa, na njega Êeö|morati sam da paziö...
{94139}{94174}HoÊeö li da se povuÊeö?
{94345}{94442}SinoÊ sam zvao Ejmi, da joj|javim da sam ûiv.
{94448}{94506}To je bilo riziËno.|- Jeste...
{94526}{94590}I, ako sada stanem, sve ovo|do sada je bilo dûabe.
{94626}{94719}PoznavajuÊi Ejmi, siguran sam|da bi me ona prva ubila.
{94872}{94904}ZnaËi, ne odustajeö?
{94993}{95144}Dûoi ima dobar ûivot...|Dobra odela, skupa kola...
{95179}{95235}Mnogo novca i|slobodnog vremena...
{95299}{95339}Ja sve to nikada|nisam imao.
{95407}{95458}Samo da ti to|ne udari u glavu, vaûi?
{95595}{95663}Ovo je nekako iznenada.|- äta bi ti, obaveötenje?
{95672}{95777}Sve öto je brzo, to je i kuso.|- Napadamo za jedan sat.
{95792}{95877}Tom prilikom Êemo da sredimo|Lamanskog. To je moja ideja.
{95935}{96036}äta misliö o tome?|- ReËi Êu ti kada bude gotovo.
{96508}{96536}Mi smo spremni.
{96868}{96912}Policijska stanica.|Narednik Vaöington.
{96917}{97110}Imate bombu u zgradi.|EksplodiraÊe za 22 minuta!
{97205}{97235}Sve je sreeno.
{97438}{97530}Imamo bombu u zgradi.|- Zovi odeljenje za demontaûu.
{97546}{97575}Evakuiöi zgradu.
{97794}{97821}Demontaûa.
{97908}{97959}Evakuiöite zgradu i|postavite barikade u krugu...
{97961}{98051}...od 100 metara oko zgrade.|- KreÊemo.
{98080}{98115}Spremni smo.
{98118}{98153}I mi...
{98668}{98706}Brûe!
{99252}{99274}Hajde!
{99509}{99615}Vidiö li Lamanskog?|Pucaj kada bude sam.
{99738}{99832}Sranje! Nema öanse!|Otkud toliki narod?
{99849}{99876}Moûda su igrali tombolu.
{99892}{99966}Imaö li ti kalendar, Maks?|Sigurno je neki praznik.
{100007}{100049}BiÊe to njegov praznik.
{100066}{100117}PratiÊemo ga i srediti|kada bude moguÊe.
{100736}{100805}Sve je spremno.|Napolje.
{101028}{101061}Sranje.
{101200}{101255}Hajde.
{101742}{101804}Kad stignemo na auto put,|izbaciÊu ga s puta.
{101822}{101910}Njihov auto je teûi od naöeg.|- Nije vaûno, ako pogodiö vozaËa.
{104161}{104184}UdariÊe u zid.
{105731}{105758}Gubimo se odavde!
{105964}{105988}»uvaj glave!
{106228}{106255}To je to!
{106334}{106358}Otvori vrata!
{106987}{107064}Ne znam ko je ovo.|Nikada ga nisam video.
{107080}{107104}Siguran si?
{107158}{107206}Pre 3 godine sam hapsio|Brenona dva puta za...
{107209}{107322}...2 nedelje.|To nije on.
{107384}{107480}Znaö li gde je?|- Na Karibima.
{107671}{107747}Kad se vraÊaö u Majami?|- Za sat vremena.
{107842}{107935}Sutra moram da budem na|utakmici u dobrotvorne svrhe.
{107941}{108048}Panduri protiv pandura?|To treba videti.
{108139}{108198}äta doavola radiö za|novac koji ti dajem!?
{108201}{108253}Drûim jaja u procepu!|- Nije dovoljno!
{108307}{108398}Neko je nekoga uvalio|u organizaciju!
{108401}{108480}Taj se svuda slobodno öeta.|»ak je bio i u mojoj kuÊi.
{108516}{108581}On moûda u ovom trenutku|tuca moju ûenu!
{108584}{108640}Ne znam kako je|dospeo tamo!
{108686}{108729}Uostalom, sada smo|saznali ko je.
{108731}{108793}Kako to misliö, "mi"?|Maks ga je sam provalio.
{108796}{108877}äta hoÊeö? Ne mogu ti reËi|stvari koje ne znam.
{108880}{108924}A öta ti uopöte znaö?!
{108981}{109062}PriËaö mi o Ëoveku iz Biroa|koji u svoje slobodno vreme...
{109065}{109176}...hoÊe da me sredi, jer mu je sin|poginuo u naöem napadu.
{109200}{109235}Imaö li koju dobru novost?
{109267}{109331}Jedan moj prijatelj iz Biroa je|proverio äenonov dosije.
{109355}{109435}äta god da radi, to je|nezvaniËno. Nema tragova.
{109496}{109593}Ako bi bio ubijen, ne bi to|mogli da poveûu sa tobom.
{109696}{109839}To je dobra vest, a?|A, ko Êe to da uradi? Ti?
{109951}{110139}Brenon.|- Tako je...
{110208}{110278}Mislim da treba da idem...|- Gde? U Kanadu, Meksiko?
{110299}{110363}Ne ideö ti nikuda|dok se ovo ne zavröi.
{110377}{110481}Ako si naudio mojoj organizaciji,|hoÊu da znam gde mogu...
{110484}{110532}...da te se doËepam.
{111062}{111145}Odmah se vraÊam.|- Hej, ne smemo da kasnimo!
{111147}{111170}Samo minut!
{111251}{111312}äta ti radiö ovde?|- Izvini zbog onoga.
{111346}{111411}Nisam ja gde imala da nauËim|kako se druûi. - U redu je.
{111417}{111464}Idemo!
{111510}{111584}Mislila sam da porazgovaramo.|- Imam neöto da uradim.
{111608}{111671}A kasnije?|- Moûe.
{111712}{111813}Uzmi moja kola i idi kuÊi.|JaviÊu se Ëim se vratim. Vaûi?
{112117}{112149}Pazi se...
{112218}{112248}Ne brini.
{113823}{113856}HoÊeö li mi sada reËi|ko je u pitanju?
{113870}{113931}Pandur...|ObiËan jebeni pandur.
{113982}{114065}Idi pravo na njega,|ja idem sa strane.
{115665}{115704}Hari?!|- Ubijte ga!
{116277}{116433}Nisam znao da si ti u pitanju.|- U redu je, beûi sada.
{116441}{116513}PozvaÊu hitnu pomoÊ.|- DoÊi Êe oni i bez toga.
{116525}{116630}Ali, ako te uhvati policija,|a ja umrem, gotov si.
{116662}{116718}Ne smeö da umreö,|nismo joö zavröili!
{116723}{116791}Hajde, gubi se!
{116806}{116831}Vidimo se ubrzo...
{117556}{117614}äta ti radiö ovde?|- Spaöavam ti ûivot!
{118200}{118337}Pakuj sve öto moûeö da poneseö.|Idi na aerodrom i iznajmi avion.
{118343}{118393}»ekaj malo...|Gde ti ideö?
{118404}{118510}Moram da uËinim uslugu jednom|prijatelju...da sjebem bandu!
{118791}{118916}SPOMINJAO SAM KAMENOLOM|KOJI POSEDUJE PETROVITA.
{118922}{118978}AKO TE POZOVU, NE IDI|TAMO, JER SE...
{118981}{119052}...TAMO NE KOTRLJA|SAMO KAMEN.
{123127}{123221}Imamo druötvo!|- Gde? Ne vidim ga.
{124234}{124290}Svi napolje!
{128885}{128948}äTA SE OVDE DESILO,|NIKO NE ZNA TA»NO.
{128951}{129031}POLICIJA MISLI, NA OSNOVU|NOVCA I DROGE KOJA JE...
{129034}{129103}...NA–ENA NA MESTU ZLO»INA,|DA SE RADI O RATU MAFIJE.
{129107}{129154}Rat mafije u bulji!
{129192}{129266}Brenon! Ne znamo gde je|taj kuËkin sin.
{129323}{129491}Nadajmo se da nije ûiv.|- Ja mislim da je mrtav. - I ja...
{129495}{129593}Nemoj da misliö, moli se!|Ako je on ûiv, ti nisi!
{129648}{129683}E, sranje!
{129811}{129855}Hajde da ga sredimo pre nego|öto se domogne lifta!
{129909}{129958}Ti ostani ovde!
{130969}{131017}Ventilacija!
{132287}{132305}Sranje!
{133100}{133191}KuËkin sin!|Hajde!
{133746}{133761}Jebote!
{134117}{134133}Prokletstvo!
{134521}{134557}Sredite kuËkinog sina!
{135155}{135197}äta Êemo sad?|- Zovi policiju.
{135200}{135241}äta?!|- Zovi jebenu policiju!
{135448}{135492}ProkletniËe...
{136680}{136704}Kaminski?
{136718}{136809}Sigurno na ovo misle kada|kaûu "pravda postoji".
{136856}{136893}Nije to öto misliö.
{136911}{136980}Ja sam hteo da ih|uhvatim na delu...
{137026}{137087}Opet radiö za Biro?|Nisam znao...
{137132}{137195}Znaö, ona stvar|je bila greöka...
{137220}{137359}Zbog tebe je mnogo ljudi umrlo.|Sada je red na tebe.
{137593}{137708}Daj ostavku ili Êu te tuûiti.|OdluËi sam.
{138515}{138537}Sranje!
{138729}{138763}äta li je Bakster|radio ovde?
{138796}{138860}Izgleda da je on tip koji je|izdavao naöe tajne.
{138901}{138932}äta misliö,|öta se ovde desilo?
{139005}{139062}Izgleda da se neko naljutio.|- Ko?
{139077}{139103}Mislim da znam.
{139149}{139213}LOKALIZOVALI SMO AUTOMOBIL.|- Daj to meni.
{139232}{139322}19790 REGISTROVAN NA IME|LUI–I PETROVITA.
{139328}{139388}KRE∆E SE PREMA SEVERU.|DA IH ZAUSTAVIMO?
{139390}{139435}Ne, samo ih pratite.
{139439}{139483}Obaveötavajte me o njihovom|kretanju. - PRIMLJENO.
{139548}{139633}Gde ideö?|- Da vidim koliko sam pametan.
{140298}{140366}Ulazi u avion.|- Jesi li dobro?
{140592}{140635}Ti ne ideö?|- Ne!
{140686}{140770}Onda ni ja ne idem.|- Ti nemaö opravdanje.
{140784}{140896}U torbi je 250.000 dolara.|Uzmi ili ostavi... Biraj.
{140919}{140957}Gubi se odavde!
{141061}{141096}BiÊeö dobro, zar ne?
{141404}{141442}KreÊi.
{142802}{142840}Drago mi je da me nisi|naterao da te jurim.
{142871}{142905}Suviöe sam umoran.
{142927}{143007}Godinu dana policijskog rada...|sve gotovo za jedno popodne.
{143034}{143076}Oduvek sam imao oseÊaj|da si naö Ëovek.
{143195}{143222}Koliko joö dana u kolicima?
{143346}{143437}Koliko joö da gledam|kako niöta ne radite?
{143473}{143586}Nisam zainteresovan da|postanem dobar invalid.
{143617}{143709}Odgurajte me nazad u sobu,|ili pod kamion, svejedno mi je.
{143768}{143797}Ne napredujeö, Hari?
{143901}{143974}Imao sam i boljih dana.|- HoÊeö li da ih imaö ponovo?
{144005}{144037}Teöko, iz ove pozicije.
{144105}{144287}Pa, vratio si se u Biro?|- Da. I svojoj ûeni.
{144294}{144324}ZahvaljujuÊi tebi.
{144426}{144524}Prestani! Ne izvodi!|Dajte mi moja kolica!
{144602}{144667}Potrebna mi je tvoja pomoÊ,|Hari. - Za öta? Gde su mi kolica?
{144691}{144743}Moje ponovno vienje|sa Ejmi je bilo uspeöno.
{144811}{144945}Zatrudnela je. - Super! Sjajno!|Dajte mi moja kolica!
{144956}{145061}Ja ne znam niöta o oËinstvu.|Moraö da mi pomogneö.
{145065}{145144}HoÊu da mi budeö kum. - Dobro,|dobro, dajte mi kolica!
{145155}{145211}Onda, hodaj.|- Ne mogu da hodam!
{145228}{145259}Doi na pola puta.
{145317}{145355}Ne moram da hodam|da bih bio kum!
{145373}{145455}Ne moraö da hodaö, ali|moraö da se trudiö!
{145576}{145601}Ne mogu!
{145615}{145663}Da li si ikada odustao|pred Blerom?
{146898}{146963}Preveo: SLOBA  Tel: 063/8 107 692|NEGOTIN  E-mail: novdan@ptt.yu
{146968}{147045}KRAJ
{147070}{148570}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3rdk2|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
