{1}{1}25.000
{26}{176}-== [ www.OpenSubtitles.com ] ==-
{1058}{1178}{C:$0000FF}{y:ib} U ORLOVOM |{C:$FF0000}{y:b} GNIJEZDU 
{5241}{5333}Veæ smo tu, gospodine. | Posada spremna i èeka nareðenje. Prijam.
{5720}{5762}Dobro. Gotovo.
{6039}{6115}Naš èovjek oboren je jutros u 2 sata.
{6119}{6215}Uza svu svoju mudrost, | to su nam rekli tek u 10 ujutro.
{6223}{6295}Idioti prokleti! | Idioti prokleti, jer nam nisu javili
{6297}{6378}i dvaput idioti jer nas nisu slušali.
{6386}{6449}U svakom sluèaju tu je
{6462}{6509}u gradu po imenu Werfen.
{6511}{6592}Schloss Adler. Orlov Dvorac.
{6602}{6694}Dobro ime, jer onamo može samo orao.
{6709}{6810}Zadatak nam je da uðemo | i što prije ga izbavimo
{6812}{6872}prije no što iz njega izvuku podatke.
{6874}{6926}Zašto ste sigurni da je on tamo?
{6940}{7020}Komarac u kojem je bio | srušio se samo 16 km dalje.
{7027}{7070}Schloss Adler je stožer
{7072}{7131}njemaèke tajne službe u Južnoj Bavarskoj.
{7133}{7181}Gdje bi ga inaèe odveli?
{7183}{7274}Kako se srušio zrakoplov? | - Najgora prokleta zla sreæa.
{7276}{7353}Sinoæ smo nenadano napali Nurnberg.
{7355}{7454}Nismo oèekivali ni jednog njemaèkog | vojnika 160 km od austrijske granice.
{7456}{7523}Uhvatila ga je zalutala | Messerschmitt patrola.
{7525}{7577}No to nije bitno.
{7587}{7675}Bitno je da ga izvuèemo | prije no što progovori.
{7710}{7779}Odnosno, da ga vi izvuèete.
{7794}{7835}A padobranci, gospodine?
{7850}{7939}Schloss Adler je nepristupaèan i neosvojiv.
{7955}{8019}Trebao bih bataljun padobranaca | da ga osvoje.
{8021}{8059}Nemamo vremena.
{8073}{8133}Preostaju nam jedino tajnost i šutnja.
{8146}{8220}Vi znate èuvati tajnu.
{8227}{8316}Jasno nam je da nikad niste radili u timu
{8327}{8428}ali ste dovoljno meðusobno bliski. | Osim poruènika Schaffera
{8435}{8489}koji, primjeæujete
{8491}{8568}nosi oznake Amerièke rangerske divizije.
{8572}{8617}To govori dovoljno.
{8635}{8687}Bojnik Smith æe uvesti odred.
{8692}{8773}Svi ste struènjaci za preživljavanje | iza neprijateljskih linija.
{8775}{8815}Poruènik Schaffer
{8817}{8896}narednici Harrod i McPherson u okviru | svojih vojnih ovlasti
{8898}{8954}a ostali, na drugim zadacima.
{8975}{9020}Svi teèno govorite njemaèki.
{9027}{9093}Obuèeni ste za sve vrste borbi.
{9116}{9192}Ako ga itko može izvuæi, onda ste to vi.
{9200}{9251}Postoji i drugi naèin
{9253}{9321}koji bi jamèio potpuni uspjeh.
{9337}{9445}Ni admiral Rolland ni ja ne | tvrdimo da sve znamo i da smo nepogrešivi.
{9456}{9516}Jesmo li izostavili neku moguænost?
{9519}{9609}Podignemo li izviðaèku eskadrilu | Lancastera s 10-tonskim bombama
{9641}{9716}nitko iz dvorca više nikad neæe progovoriti.
{9718}{9795}Ne shvaæate stvarnost.
{9797}{9871}Zarobljenik, gen. Carnaby, je Amerikanac.
{9881}{9952}Uništimo li ga, Eisenhower
{9954}{10041}æe svoju Drugu armiju | prije poslati na nas nego na Nijemce.
{10043}{10158}U odnosima sa saveznicima | valja misliti na neke sitnice.
{10206}{10290}Dakle, gospodo, veèeras u 22 na uzletištu.
{10325}{10386}Nema pitanja? | - Ima!
{10404}{10482}Neka mi pukovnik oprosti, | ali o èemu se u stvari radi?
{10493}{10552}Zašto je taj èovjek tako važan?
{10554}{10592}To je sve, narednièe.
{10594}{10646}Imate sve potrebne podatke.
{10648}{10718}Šaljemo li èovjeka u moguæu smrt
{10720}{10770}ima pravo znati zašto.
{10781}{10838}Stvar je bolno jednostavna, narednièe.
{10852}{10923}Gen. Carnaby je jedan | od glavnih koordinatora
{10925}{10970}Druge fronte.
{10994}{11085}Sinoæ se trebao naæi | sa svojim kolegama na Srednjem istoku
{11087}{11156}da završe planove za invaziju Europe.
{11168}{11241}Sastanak s Rusima trebao je biti na Kreti.
{11243}{11303}Na žalost, nije uspio.
{11349}{11415}Natjeraju li ga Nijemci da progovori
{11444}{11501}možda ne bude Druge fronte.
{11512}{11582}Jasno, narednièe? | - Da.
{11622}{11697}Oprostite. | - OK, narednièe. Zaboravite.
{11710}{11788}Imate li još pitanja, | bojnik Smith æe vam dati objašnjenja.
{11790}{11831}To bi bilo sve, gospodo.
{12542}{12607}Neka se spreme. | Približavamo se podruèju iskakanja.
{12609}{12639}Pozor!
{13073}{13108}Zeleno! Kreæi!
{16734}{16764}Gdje je Harrod?
{16865}{16960}Zadnji put sam ga vidio kad se | spuštao prema ovim stablima.
{17092}{17143}Dobro. Raziðite se.
{17170}{17208}Pronaðimo ga.
{17900}{17927}Bojnièe!
{19033}{19084}Slomio je vrat. | - K vragu!
{19208}{19291}Što sad? Da ga pokopamo, | ili æemo ga ovdje ostaviti?
{19293}{19322}Ostavit æemo ga ovdje.
{19324}{19378}Za par sati prekrit æe ga snijeg.
{19380}{19478}Vratite se po opremu. | Želim vidjeti radi li radio stanica.
{21953}{22040}Dobro radi. | U dolini ima koliba na oko 1,5 km.
{22042}{22091}U njoj æemo pregledati opremu.
{22093}{22159}A ljudi koji tamo žive? | - Nema nikoga.
{22161}{22213}Ovo je visoki alpski pašnjak.
{22227}{22303}Dovode stoku u svibnju | i opet je odvode u rujnu.
{22305}{22372}Ostatak godine mjesto je posve prazno.
{22376}{22416}Idemo!
{23258}{23316}Nije ovo za mene.
{23328}{23367}Nije ni za jednog od nas, Jock.
{23369}{23410}Ti si kuhar i kuhaj.
{23427}{23541}Nešto toplo za jelo i tople kave. | Onda zovi London.
{23549}{23617}K vragu, ostavio sam šifre kod nar. Harroda.
{23619}{23713}Idem po njih, ako želite. | - Ne, ja sam napravio glupost.
{23715}{23776}Meæava kao da još uvijek traje.
{23817}{23869}Ako me nema za 1 sat
{23875}{23945}dajte mi svjetlosni znak pištoljem | 4 puta svakih 5 min.
{23947}{23990}To bi i slijepca dovelo doma.
{23992}{24053}Ali bi moglo dovesti i dobar | dio njemaèkog pješaštva.
{24055}{24112}Nema nijednog Nijemca na 10 km.
{24120}{24177}Nitko neka ne izlazi dok se ne vratim.
{24182}{24265}Jock, ostavi mi malo kave. | - Ohladit æe se dotad.
{24274}{24349}Kažu da je to prednost. | Ne možeš odgonetnuti kakva je.
{26294}{26320}Stoj!
{26345}{26378}Okreni se!
{26583}{26646}Dugo ti je trebalo.
{26663}{26700}Bilo je posla.
{26734}{26763}Uživala u putovanju?
{26765}{26830}Divno. Smrzla sam se u vražjem zrakoplovu.
{26832}{26936}Zašto nisi osigurao toplu vodu | ili odijelo s grijanjem?
{26946}{27023}Mislila sam da me voliš. | - Misli što te volja.
{27044}{27091}Uspjela si dovuæi opremu.
{27099}{27151}To je sva dobrodošlica?
{27153}{27257}Zasad, na žalost, da. | Poginuo mi je radio operater pri spuštanju.
{27259}{27295}Što je bilo?
{27307}{27357}Udaren je po vratu
{27359}{27415}drškom noža ili kundakom puške.
{27417}{27467}Koža je cijela, ali tamna.
{27469}{27520}Znaèi da mu je odmah potom | netko slomio vrat
{27522}{27570}kako bi izgledalo kao nesretan sluèaj.
{27572}{27663}U zoru vodim momke | preko grebena u iduæu dolinu.
{27665}{27742}Bit æemo u šumi do 19, | pa nemoj nabasati na nas.
{27763}{27830}Èim se smrkne idemo za selo Warfen
{27832}{27910}gdje je krèma Zum Wilden Hirsch.
{27912}{27977}Iza nje s desna je drvena koliba u šumi.
{27979}{28057}Vidimo se ondje sutra naveèer toèno u 20.
{28095}{28169}A što poslije? | - Reæi æu ti kad bude vrijeme.
{28212}{28282}Vidim da si došla u punoj opremi. | - Pusti to sad.
{28284}{28371}Kako znaš za taj "Zum Wilden Hirsch" | i kolibu?
{28435}{28478}Imam pravo znati.
{28487}{28535}Ništa ti nemaš pravo znati.
{28595}{28659}Veæ 3 godine radimo skupa. | Profesionalac sam.
{28661}{28687}I ja sam.
{28693}{28759}Da sam od onih koje se udaju, a što...
{28923}{28988}Mislila sam da ti se žuri. | - I žuri mi se.
{29013}{29046}Tebi ne?
{30671}{30707}Što te zadržalo?
{30723}{30774}Imao sam veliku sreæu.
{30793}{30841}Naletio sam na èudesnu plavušu.
{30854}{30901}Ležala je na snježnom nanosu.
{30910}{30943}Ima li prijateljicu?
{30945}{30996}Ne, bojim se da nemaš sreæe.
{31025}{31102}Svejedno, hvala što ste me èekali. | - Ništa za to.
{31437}{31486}Poruènièe, zašto ne idete leæi?
{31488}{31547}Uskoro æe zora. I ti, Jock.
{31551}{31586}Hoæu.
{31799}{31837}Ništa ne mogu dobiti.
{31901}{31937}Valjda zbog oluje?
{32000}{32053}Pokušat æemo opet u jutro.
{32945}{33020}Poruènièe, za mnom. Vi ostali, ostanite.
{33418}{33466}Opremu ostavite ovdje.
{34164}{34215}Netko je oèito lud.
{34237}{34296}Kako tvoj pukovnik zamišlja | da æe netko u to uæi?
{34298}{34365}Valjda misli ako je on mogao | prodrijeti u Njemaèki stožer
{34367}{34420}ni nama ne bi trebalo biti teško uæi unutra.
{34422}{34451}Molim?
{34465}{34550}Pukovnik Turner je od 1940. do 1943. | Proveo u Njemaèkoj. Prvo u Wermachtu
{34552}{34621}potom u Glavnom stožeru u Berlinu.
{34623}{34677}Kažu da je dobro poznavao Hitlera.
{34681}{34747}Uvijek sam ga držao pomalo šašavim. | - Vjerojatno i jest.
{34749}{34824}Sad imamo svojih nevolja. | Vrati momke u šumu.
{34826}{34908}Doveli smo ih preblizu. Neka ne izlaze.
{34910}{34967}A ti? | - Odmah æu i ja.
{34969}{35034}Samo neka budu iza stabala.
{36524}{36604}Široki maè zove Malog Dannyja! Prijam.
{36657}{36732}Mali Danny zove Široki Maè. | Otac Machree èeka.
{36745}{36807}Ovdje Otac Machree.
{36809}{36870}Gdje si Maèu? Prijam.
{36892}{37000}U šumi zapadno od dvorca. | Silazim u sumrak. Harrod mrtav.
{37009}{37035}Prijam.
{37067}{37149}Je li Harrod poginuo nesretnim sluèajem? | Prijam.
{37169}{37200}Ne. Prijam.
{37223}{37294}Nijemci? Prijam. | - Ne.
{37317}{37401}Vrijeme iduæeg prijenosa nesigurno. | Bit æete spremni?
{37453}{37548}Puk. Turner i ja ostajemo | u Stožeru do kraja operacije.
{37550}{37586}Sretno! Kraj.
{37857}{37910}Izgleda da ste u pravu, gospodine.
{37935}{37977}Da, bojim se.
{37997}{38041}Pitam se tko je iduæi.
{38052}{38125}Možda Smith osobno. | - Sumnjam.
{38152}{38205}Neki ljudi imaju šesto èulo.
{38222}{38285}On ima šesto, sedmo i osmo.
{38290}{38353}On nam je najbolji agent. | - Osim vas.
{38413}{38517}No makar bio najbolji, | èini se da je operacija sada nemoguæa.
{39518}{39585}Pogledaj u podnožje dvorca.
{39656}{39688}Dobermani.
{39722}{39790}Da. Dobermani, kula i žièana ograda.
{39804}{39869}Ogradu se da presjeæi ili prijeæi, poruènièe.
{39879}{39986}Sumnjam da se ona tamo može prijeæi. | U njoj je valjda 3.000 ljudi.
{40001}{40084}Ako ne griješim, tamo je vojarna.
{40140}{40233}Ne griješite. | To je stožer Wermachtova Alpskog korpusa.
{40235}{40319}Divota. Imate li još iznenaðenja, | trebao bih znati.
{40321}{40365}Mislio sam da znate.
{40367}{40429}Zašto nismo odjeveni | kao njemaèki mornari?
{40431}{40482}Stalno dolaze vojnici na obuku.
{40484}{40544}Što je 6 izmeðu 600 novih lica?
{40546}{40624}Èujte, bojnièe, | ovo je ponajprije britanska operacija.
{40626}{40695}Ja sam Amerikanac. | Èak ne znam kog vraga tu radim.
{40697}{40766}Poruènièe, tu ste baš zato | jer ste Amerikanac.
{42751}{42830}Dragi Krameru, malo ste posjedili | otkako sam vas zadnji put vidio.
{42832}{42873}Da, bojim se.
{42889}{42943}Kako je u Berlinu? | - Stvari su se promijenile.
{42945}{42980}Sviða vam se moj stroj?
{42982}{43047}Izgleda opasno. | - Morate ga iskušati.
{43051}{43101}Bojnik Bergholder, moj poboènik.
{43119}{43186}Bojnik Brandt, Lovaèki bataljun.
{43199}{43272}Pukovnik Weissner, terensko osiguranje.
{43294}{43348}Bojnik von Hapen, Gestapo.
{43535}{43605}Jeste li ga veæ ispitali? | - Ne, èekao sam vas.
{43632}{43715}Taj bojnik von Hapen, | zna li on da je tu gen. Carnaby?
{43717}{43812}Da, izvijestio sam ga kad je stigao, | ali ne i koliko je on važan.
{43815}{43900}Dobro. Ako je moguæe, volio bih u to | ne miješati Gestapo
{43902}{43962}dok ne saznamo što želimo.
{43964}{44034}Ne treba nam još zbrka | s njegovim sobama za muèenje.
{44036}{44104}Ovo neka ostane strogo vojna stvar, | za sada.
{44106}{44143}Slažem se. | - Dobro.
{44146}{44240}Imao sam vrlo naporan put iz Berlina. | Htio bih se malo osvježiti
{44242}{44308}i zaspati koji sat | prije nego što upoznam gen. Carnabyja.
{44310}{44368}Otpratit æu vas do vaše sobe. | - Hvala.
{44370}{44436}Sve æe biti spremno za susret | kad god zaželite.
{49314}{49356}Propusnicu, molim.
{49563}{49586}Jasno.
{49593}{49663}Puno sam joj puta pisao ali
{49674}{49779}toliko je vojnika na odmoru u Berlinu | i teško da æe se sjetiti baš mene.
{49788}{49854}Ali uvijek se nadaš da baš | tebe nikad neæe zaboraviti.
{49856}{49923}Kako se uopæe zvala?
{49962}{50044}Fred. Da, sjeæam se! Sitna i crvenokosa.
{50904}{50957}Pokušat æemo ovu iza nas.
{50962}{51014}Kad uðete, kružite uokolo
{51016}{51103}i dobro napregnite uši | ne biste li èuli štogod o gen. Carnabyju.
{51110}{51180}Naæi æemo se opet ovdje za pola sata.
{52332}{52364}Dvije pive.
{52822}{52858}Vidimo se.
{53228}{53270}Trebate li još nešto?
{53283}{53353}Tko si, lijepa alpska ružo?
{53355}{53446}Heidi. Dosta, bojnièe, imam posla. | - Što ima važnije
{53448}{53500}od zabave domovinskog vojnika.
{53502}{53570}Da ti otpjevam pjesmu? | - Dosta mi je pjevanja.
{53572}{53651}Dobro, onda æu zviždati. Ide ovako...
{53767}{53834}Kladim se da predivno pjevate.
{53843}{53875}Hvala.
{53883}{53943}Budi u drvenoj kolibi za 5 minuta.
{53975}{54039}A sad me ošamari što jaèe možeš.
{54159}{54280}Bojnièe, takvo ponašanje | ne prilièi èasniku Wehrmachta.
{54307}{54369}Gospodine bojnièe, kad mi se obraæate.
{54374}{54459}Ja sam bojnik Bernd Himmler. | Znaèi li vam nešto to ime?
{54500}{54570}Savjetujem vam da ubuduæe | gledate svoja posla.
{54586}{54620}Je li jasno?
{54972}{55025}Konjak. | - Dajte dva.
{55050}{55131}Sumnjam da ste otkrili | nešto o gen. Carnabyju.
{55136}{55185}Nisam još stigao do toga.
{55187}{55249}Što ste rekli onom bojniku?
{55257}{55311}Rekoh mu da sam Himmlerov brat.
{55352}{55416}Vidim da ga je to malo uzrujalo.
{55418}{55467}I više nego malo.
{55470}{55519}Bacite malo oko, vratit æu se.
{57120}{57155}Svuci se.
{57157}{57221}Ne raspravljaj, samo se svuci.
{57404}{57470}Smiri se. Nisam mislio na to.
{57537}{57621}Veèeras ideš u dvorac kao domaæa.
{57663}{57703}Gola?
{57712}{57765}Dobra zamisao, ali je malo upadljivo.
{57767}{57869}U Njemaèkoj je velika nestašica osoblja. | Ni Schloss Adler nije iznimka.
{57925}{58009}Trebaju im baš takve kao ti. | Mlada, zdrava, zgodna
{58011}{58067}i kako oboje znamo, | ne bez smisla za humor.
{58069}{58105}Ma, ti si lud!
{58107}{58168}Zar bih inaèe radio ovo?
{58170}{58213}Sad me pozorno slušaj.
{58215}{58301}Trebala bi stiæi autobusom iz | Steingadena za oko 20 minuta.
{58303}{58376}Zoveš se Maria Schenk. | Dolaziš iz Rhinelanda.
{58381}{58421}Daj tu èizmu.
{58433}{58493}Dobila si sušicu i morala napustiti posao.
{58495}{58565}Imaš roðakinju, zove se Heidi, | i radi u Zum Wilden Hirsch.
{58567}{58620}Ona ti je sredila posao u dvorcu.
{58622}{58693}A isprave? | - U ovoj torbi
{58695}{58774}skupa s putnom dozvolom. | Heidi æe ti poslije dati ostalo.
{58776}{58837}Za ovo je zacijelo trebalo vremena.
{58839}{58940}Vjerojatno. Naš odjel za krivotvorenje | posebno se pozabavio ovim ispravama.
{58957}{59058}Nije li se generalov zrakoplov | srušio tek juèer ujutro?
{59069}{59113}Sve je pozorno pripremljeno.
{59115}{59186}Srušeni zrakoplov je pao | na vojno uzletište Oberhausen
{59188}{59227}oko 8 km odavde.
{59229}{59313}Bio je izrešetan strojnicama. Britanskim.
{59315}{59396}Ali, k vragu, rupa je rupa, kako se kaže.
{59403}{59490}Zar si stavio na kocku | život amerièkog generala
{59492}{59563}i sve planove za Drugu frontu? | - Jasno da ne.
{59602}{59648}Daj mi drugu èizmu.
{59661}{59708}Ja naime želim uæi u dvorac
{59710}{59777}prije nego što otkriju | da nemaju gen. Carnabyja.
{59781}{59846}Momak kojeg su uhvatili o Drugoj fronti zna
{59848}{59901}koliko ja o tamnoj strani Mjeseca.
{59904}{59952}On je amerièki kaplar.
{59962}{60002}Zove se Cartwright Jones.
{60004}{60060}Bivši glumac, vjerojatno drugorazredni
{60062}{60119}ali pljunuti general.
{60121}{60198}Jesi li poprièao s jadnikom | prije nego se u sve upetljao?
{60200}{60276}Nisam trebao. Dobrovoljac. | Koji glumac ne bi to uèinio?
{60309}{60404}Izvuèe li se, bit æe to | vrhunac njegove karijere.
{60418}{60477}Bit æe mu to kratkotrajni angažman.
{60481}{60538}Da, jednoveèernji.
{60972}{61000}Tu smo.
{61002}{61054}Mary, sad Maria, | ovo je tvoja roðakinja, Heidi.
{61056}{61108}Bolje to sakrijte, u sluèaju da te pretraže.
{61110}{61162}Heidi æe ti odsad govoriti što ti je èiniti.
{61164}{61248}Ona je jedan od naših vrhunskih agenata | u Bavarskoj od 1941.
{61289}{61327}Kakva maska.
{62477}{62526}Znaèi otišao je 3 minute poslije mene.
{62528}{62605}U žurbi, kažeš. Znaèi, nije mene slijedio.
{62640}{62685}Je li još tko izašao?
{62687}{62752}Ne, koliko ja vidim. Mjesto je vraški krcato
{62754}{62797}a postoji još par izlaza.
{62805}{62867}Svatko se mogao išuljati.
{62903}{62999}Bolje budi otvoren | ili me izbaci iz ovog meteža.
{63007}{63091}Oboje znamo da radio operater | nije poginuo pri spuštanju.
{63109}{63178}Sad kad je mrtav i McPherson, | samo smo petorica.
{63200}{63285}Zato mi reci što se dogaða, | da ne ostanete samo èetvorica.
{63287}{63328}Dobro.
{63330}{63422}Jutros si me pitao zašto si ti, | Amerikanac, ukljuèen u ovaj zadatak.
{63441}{63495}Odgovor je doista vrlo jednostavan.
{63704}{63775}Draga moja Maria! Napokon si stigla.
{63779}{63860}Draga Heidi, krasno što te vidim | nakon toliko godina.
{63862}{63926}Gestapo. Kako ti se radujem!
{63952}{64038}Da te upoznam s mojim prijateljem. | Bojnik von Hapen.
{64042}{64088}Moja roðakinja Maria Schenk.
{64132}{64228}Vaša roðakinja nam je rekla da vas oèekuje, | gðice Schenk, ali Heidi
{64236}{64298}niste mi rekli da je ovako lijepa.
{64300}{64333}Hvala.
{64347}{64427}Kad budete htjeli uspinjaèom u dvorac
{64429}{64484}bit æe mi èast da vas pratim. | - Hvala vam.
{64486}{64533}I ja æu s njom.
{64577}{64647}Obje, dakle. Baš imam sreæe.
{64681}{64733}Do skorog viðenja, gospoðice.
{65334}{65377}Ovo je plan dvorca.
{65423}{65457}Tvoje upute.
{65470}{65503}Dobro obavi domaæu zadaæu.
{65907}{65957}Èini se da ga nigdje nema.
{65959}{66045}Gdje li je, k vragu? | Naredio sam da nitko ne odlazi.
{66047}{66092}Da iziðem i pogledam vani?
{66520}{66552}Pozor!
{66565}{66649}Tražimo 4-5 dezertera | Alpskog korpusa iz Stuttgarta.
{66651}{66721}Pri bijegu ubili su dvojicu èasnika | i narednika straže.
{66723}{66777}Zadnje što znamo jest da su krenuli ovamo.
{66779}{66829}Pametno. Vrlo pametno.
{66832}{66942}Neka smjesta istupe stariji èasnici | odreda 13, 14 i 15.
{66998}{67037}Provjerite im isprave.
{67066}{67125}Pa, gospodo, ima li kakvih prijedloga?
{67257}{67289}Poruènièe?
{67308}{67409}Mislim da æemo vani | imati puno više izgleda.
{67427}{67456}Dogovoreno.
{67484}{67541}Gospodo, vidimo se poslije rata.
{67732}{67818}Ove isprave su iz 4. tenkovske | divizije iz Stuttgarta.
{67820}{67863}Što kažete, gdje ih je dobio?
{67865}{67919}Pukovnièe? | - Da, bojnièe?
{67926}{68033}Generale, mi smo ljudi koje tražite. | Došli smo se predati.
{68036}{68100}Poruènièe, odvedite ih na ispitivanje.
{68102}{68157}Èasnici æe sa mnom.
{68415}{68447}Oprostite.
{69179}{69230}Ovdje bojnik von Hapen.
{70837}{70897}Stani! | - Ma, samo vezice.
{72800}{72853}Bolje da se riješimo kola. | - Da.
{72867}{72912}Niz liticu. Gurnimo ih.
{73410}{73457}Dobro. Guraj!
{73699}{73732}Još malo.
{74315}{74356}Dobra veèer, poruènièe.
{74362}{74424}Ovo je gðica Schenk. Poruènik Kernitser.
{74426}{74512}Ona je pukovnikova tajnica. | Ona zapovijeda svim ženskim osobljem.
{74514}{74592}Isprave, molim. I vaše, gospoðice.
{74840}{74891}Poðite za mnom, molim.
{74894}{74965}Vidimo se kasnije. | - Hvala.
{75486}{75548}Jeste li našli štogod zanimljivo, bojnièe?
{75647}{75723}Èujem da je u selu veèeras bilo uzbudljivo.
{75739}{75781}Ništa ozbiljno.
{75783}{75852}Uhitili su 5 dezertera i to je sve.
{75856}{75933}Baš i nije. Bila su izdana nareðenja.
{75935}{76031}Oni su zapravo 5 britanskih agenata | preobuèenih u njemaèke odore.
{76049}{76104}Zašto nisam izviješten?
{76129}{76175}Jeste sada.
{76203}{76258}Ako ste izdali nareðenja
{76265}{76323}onda veæ neko vrijeme znate
{76342}{76417}tko su oni i da se tu nalaze.
{76426}{76493}Zvali smo vas u ured i u sobu.
{76504}{76544}Nije vas bilo.
{76546}{76620}Pukovnièe, ne moram vas podsjeæati
{76643}{76720}da sam ja nadležan za poslove Gestapa | na ovom podruèju.
{76722}{76807}Ako su tu strani agenti, | odmah ste me morali izvijestiti.
{76812}{76896}Nije vas bilo. | - Onda me pronaðite!
{76899}{76991}Dužnost mi je izvijestiti vas, | ali ne i tražiti vas po krèmama!
{76993}{77034}Znam vaše dužnosti.
{77066}{77108}I vašu odanost.
{77129}{77211}Da vas podsjetim, ja sam SS pukovnik
{77213}{77283}a ne neki poruènik | koga možete zaplašiti prijetnjama!
{77285}{77376}Vaš èin u vojsci i položaj | su mi jasni, pukovnièe.
{77412}{77505}Kao i pokušaji da me ocrnite | pred nadreðenima u Berlinu!
{77507}{77600}Ako se neèega sramite, | sami ste za to odgovorni.
{77607}{77640}Laku noæ!
{77742}{77794}Bolje zakljuèaj. | - Svakako!
{77964}{78018}Ovdje ti je sve potrebno.
{78079}{78178}Automatski pištolj, terenske naoèale, | uže i olovni uteg.
{78193}{78244}Ti si to spremila? | - Da, prošli tjedan.
{78246}{78323}Veæ si tada za sve znala? | - Da. Sretno, roðakinjo.
{78580}{78620}Ovo nam možda zatreba.
{78633}{78742}Valjda ti je jasno | da Nijemci sigurno sad veæ sve znaju.
{78749}{78789}Palo mi je na pamet.
{78950}{79003}Široki Maè zove Malog Dannyja.
{79067}{79091}Prijam.
{79285}{79324}Široki Maè, gospodine!
{79353}{79428}Mali Danny zove Široki Maè! Javi se!
{79451}{79533}McPherson ubijen. | Thomas, Christiansen i Berkeley uhiæeni.
{79535}{79586}Kanim uæi u roku od sata.
{79588}{79646}Osigurajte prijevoz. Prijam.
{79659}{79726}Izvlaèi se, Maèu. Spašavaj se. Prijam.
{79746}{79796}Šalite se. Prijam... gotovo.
{79798}{79858}Nareðujem to, Široki Maèu! Prijam.
{80095}{80136}Ne javlja se, gospodine.
{80209}{80249}Za sve sam ja kriv.
{80263}{80312}Obojica smo, pukovnièe.
{80326}{80364}Zamisao je bila moja.
{80402}{80450}Možda sam prestar.
{80460}{80503}Možda smo obojica.
{80542}{80607}U svakom sluèaju, više nema sumnje.
{80613}{80678}Nijemci su posve prodrli u MI6.
{80718}{80782}Znaju nam svaki korak | prije nego ga uèinimo.
{80784}{80836}Otkud sve to znaju?
{80838}{80894}Pomno smo birali sve ljude za ovaj zadatak.
{80896}{80956}Sve je strogo povjerljivo! | - Povjerljivo?
{80995}{81055}Ta je rijeè postala vraški smiješna!
{81650}{81690}Imamo društvo.
{81997}{82054}Otvori prozor. | - Dobro.
{90751}{90841}Stavi torbu u autobus | i vidi možeš li pokrenuti motor.
{91785}{91837}Kako ide? | - Pokušaj ga pokrenuti.
{94071}{94131}Satnik Müller s tri zarobljenika.
{104081}{104173}Ovaj ostavi, a taj sveži za kraj konopca.
{105704}{105754}Bože, ovo me skoro ubilo!
{105757}{105821}Nisu za tebe ovi ludi zadaci.
{105825}{105861}Odveæ si star.
{105863}{105933}Hvala ti na toplim rijeèima.
{105977}{106073}Prvi put mi je toplo | otkako sam u ovoj prokletoj zemlji.
{106107}{106161}Imaš li nacrt dvorca? | - Da.
{106165}{106208}Donesi mi ga.
{106731}{106785}Zašto mu ne pomogneš?
{106802}{106884}Èemu? Sasvim je sposoban | brinuti se sam o sebi.
{106891}{106953}Ako sam se ja popeo sam, zašto ne bi i on?
{107093}{107153}Najprije lijevo stubištem, treæa vrata.
{107156}{107214}Prvi desni hodnik vodi nas u istoèno krilo.
{107216}{107263}Opet dolje, druga lijevo.
{107292}{107333}Telefonska centrala.
{107484}{107556}A da mi malo pomogneš?
{107749}{107848}Èini se da ste u ovoj zemlji | sakrili puno žena, bojnièe.
{107850}{107907}Oprosti. Mary Ellison. Ona je iz grupe.
{107909}{107961}Poruènik Schaffer.
{107991}{108033}'Dan, Mary.
{108058}{109558}-== [ www.OpenSubtitles.org ] ==-
