{1}{1}23.976
{26}{176}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{300}{434}IMATI I NEMATI
{1642}{1757}MARTINIK, leto 1940|Nakon pada Francuske
{2263}{2311}Dobro jutro, kapetane Morgan.|äta ûelite danas?
{2338}{2362}Isto öto i juËe.
{2374}{2482}Isplovljavate s putnikom iz luke?|- TaËno.
{2563}{2635}Ime?|- Heri Morgan.
{2688}{2736}Narodnost? - Eskim.|- Molim?
{2762}{2834}Amerikanac. - Ime broda?|- Kvin KonË, iz Ki Vesta.
{2863}{2911}Idemo u ribolov|kao i proöle dve sedmice.
{2937}{3009}VraÊamo se veËeras i ne|udaljavamo se viöe od 50 km.
{3038}{3062}Pet franaka, molim.
{3088}{3208}Ne pribliûavajte se teritorijalnim|vodama, Sv. Luciji
{3237}{3278}ili Dominiki.|- Nova naredba?
{3294}{3335}Naredbu je dao sinoÊ admiral Robert,
{3361}{3481}guverner Francuske Zapadne Indije.|Imate primedbu? - Nemam.
{4812}{4860}Zdravo Heri, kako je?
{4913}{5009}To me je osveûilo.
{5037}{5061}Doneo si mi piÊe?|- Horacio ga donosi.
{5088}{5136}U pravu si. Mamuran sam jutros.|- Kao i svako jutro.
{5162}{5258}U Ëetvrtak nisam bio.|- U pravu si, zaboravio sam.
{5287}{5359}Pomogni Horaciju.|- Dobro jutro, kapetane.
{5387}{5459}Nabavio si mamce?|- Dovoljno
{5562}{5634}Straûar je uzeo flaöu piva.|- G-din Dûonson Êe to platiti.
{5687}{5735}Mogu jednu? - Samo jednu.
{5764}{5788}Dobro jutro.
{5812}{5860}HoÊemo li isploviti?|- Zavisi od vas.
{5889}{5960}Kakvo Êe biti vreme?|- Kao juËe, samo bolje.
{5987}{6059}Onda krenimo.|- Upadajte.
{6212}{6284}G- dine Dûonson, moram po gorivo.|- Dobro. - Treba mi novac.
{6337}{6457}Koliko? - 160 lit. po 7 centi,|To je 11,20 dolara.
{6488}{6536}Evo vam 15 dolara.|- Ostatak vraÊam na pumpi.
{6562}{6658}Oduzmite od mog duga.|- Idemo.
{7888}{7936}Pazite, tamo je vaö ulov.
{8013}{8061}Povucite jaËe, ali ne previöe.
{8113}{8209}Povucite je ponovo.|Nekoliko puta. Neka se zakaËi.
{8413}{8509}Stavi drugi mamac.|- Imam ga! - Manje zateûite.
{8564}{8660}Pobegao je!|- Nije. Zateûite manje.
{8739}{8763}Popuötajte.
{8962}{9058}Nestao je! - Dobro je uhvaÊen.|Povucite ga.
{9113}{9209}Siguran sam da se otkaËio.|- Ja Êu vam reÊi. Vucite.
{9351}{9435}Sad se otkaËio.|- Zaista.
{9463}{9511}Nije. Okrenite se i za njim.|- Namotajte kanap.
{9538}{9586}OseÊam kako vuËe.|- To je balast na kanapu.
{9614}{9710}Jedva ga namotavam. Moûda je uginuo.|- Moûda. Ali tamo joö skaËe.
{9988}{10060}Poûuri! - éurim.|Zar vi ne moûete staviti mamac?
{10089}{10137}Mogu.|- Zaöto onda vodite ovog?
{10163}{10199}Kad naie velika riba,|onda Êete videti.
{10214}{10262}U Ëemu je ötos?|- Radi brûe od mene.
{10362}{10458}Potreban mi je. Zar ne Horacije?|- Nadam se.
{10489}{10537}Zar to ne moûe Edi?|- Ne moûe.
{10564}{10660}äta se desilo?|- Pobegla mu je riba.
{10689}{10736}G- dine Dûonson, nemate sreÊe.
{10763}{10835}Heri, da li bih mogao...|U hladnjaku je. Samo jednu.
{10864}{10911}Zaöto vodite tog pijanca?
{10938}{11010}Edi je bio dobar mornar|sve dok nije postao pijanac.
{11039}{11087}Sad je beskoristan.|- Pokreni brod.
{11113}{11173}Je li vam rod? - Nije.|- Zaöto se brinete za njega?
{11190}{11262}On misli da se brine za mene.
{11288}{11336}Neka se vuËe za nama.
{11602}{11662}G- dine Dûonson,|smem li vas neöto pitati?
{11700}{11784}Znajte da nisam platio samo pivo|nego i kauciju za flaöe.
{11813}{11885}Je li vas ikada ubola mrtva pËela?|- äta? - Mrtva pËela.
{11914}{11986}Nikad i nikakva me nije ubola.|- Sigurni ste? - Naravno.
{12014}{12086}U tom sluËaju i dalje Êu dremati.|Hvala za pivo.
{12115}{12187}Pazite na kanap!
{12388}{12460}Za danas je dosta.
{12489}{12585}äta se dogodilo?|Izgubili ste ötap sa Ëekrkom.
{12640}{12676}Kad se riba propela,|niste ga mogli zadrûati.
{12688}{12760}Da ste se vezali za Ëekrk,|i vas bi povukla.
{12789}{12837}Nemate sreÊe g-dine Dûonson.|Moûda imate sreÊe kod ûena.
{12863}{12935}Da izaemo veËeras?|- PokazaÊu ti sreÊu, pijanico!
{12964}{13012}G- dine Dûonson, znate li plivati?|Dosta mi je svega!
{13038}{13086}Pazite se da mi ne iskliznete iz ruku.|- Smiri se.
{13115}{13163}Ovaj ti duguje za 16 dana.
{13189}{13225}Petnaest!
{13415}{13486}PriËaö previöe, Edi.|- Znam, Heri.
{13539}{13587}Uredu, zaboravi.
{14088}{14184}äta Êemo sutra?|Dosadilo mi je takvo ribarenje.
{14215}{14239}Kako i ne bi.
{14263}{14311}Lovite ribu 16 dana,|uhvatite dve, za koje bi svako
{14340}{14436}dao ûivot, i izgubite obadve.|- Nemate sreÊe.
{14465}{14501}Umukni! - Kaûete 16 dana.|Dugujem vam samo 15.
{14515}{14587}Danas je 16-ti put. Izgubili ste|kompletan ötap. - Vaö rizik.
{14613}{14637}Ne ako ga gubite na taj naËin.
{14664}{14700}PlaÊam najam, ali ötap je vaö rizik.
{14714}{14774}Ako unajmite auto i spustite|ga preko klisure, platiÊete ga.
{14788}{14812}To je drugo.
{14889}{14937}Izgubili ste opremu nepaûnjom.|Koöta me 275 dolara.
{14963}{15035}Kanap ne raËunam jer bi ga|i onako odvukla.
{15064}{15160}16 dana po 35 $, to je ukupno 560.
{15215}{15263}Neöto ste veÊ dali pa je to|sve zajedno 825 dolara.
{15289}{15337}Toliko mi dugujete i to hoÊu.
{15390}{15438}Nemam toliko kod sebe.|Sutra idem u banku. Uredu?
{15539}{15611}Ti ostani i zakljuËaj sve.|- Siguran si da... -Ne, Edi.
{15752}{15812}Mislio sam da svi skidaju zastave|posle 18 Ëasova. -VeÊina.
{15839}{15910}To je Viöi.|- Njihova zastava.
{15939}{15963}Prati ga.
{16265}{16337}Oprostite, kako se zovete?|- Zaöto?
{16364}{16436}Ovaj se gospodin narugao Viöiju.
{16491}{16539}Nisam spominjao Viöi, zar ne?|- Nisam obraÊao paûnju.
{16565}{16613}Kako se zovete? Mi smo Amerikanci.|Zove se Dûonson.
{16666}{16714}Ja sam Morgan.|Stanujemo u hotelu Markiz.
{17040}{17136}äta pijete?|- Burbon. -Za mene rum.
{17164}{17212}Je li bilo sreÊe?|Nije, FrenËi.
{17239}{17263}Pobegla nam je najveÊa|riba koju sam video
{17277}{17337}Moûda je ulovite sutra.|- Gotovo je. Danas je zadnji dan.
{17366}{17438}äteta.|- U vaöe zdravlje!
{17541}{17661}Idem se okupati. Dugujem vam|osam stotina... dvadeset pet.
{17689}{17761}Ej, Dûonsone, u koliko sati?
{17790}{17886}Kad doem iz banke, oko 11 Ëasova.|- »ekam vas.
{17939}{17987}MuËi li te neöto?|- Ne, od danas sam slobodan.
{18016}{18159}Jesam. Zaöto?|- Neki ljudi ûele iznajmiti tvoj brod.
{18191}{18263}Ribari? - Ne. neki moji prijatelji.
{18339}{18387}Ne dolazi u obzir.
{18428}{18500}Dobar dan. -Izvolite kljuË.
{18514}{18634}Sluöaj me. Treba im brod samo|za jednu noÊ. Dobro plaÊaju.
{18665}{18713}Za öto? Rado ti pomaûem, ali ne|meöam se u vaöu politiku.
{18740}{18860}Ne bih te pitao da nije vaûno.|Da poemo u tvoju sobu? Idemo.
{19516}{19564}Ima li neko öibicu?
{20089}{20113}Hvala.
{20190}{20262}Ko je ova?|- Doletela je danas avionom s juga.
{20341}{20413}Vidiö FrenËi, znam ko si|i na Ëijoj si strani.
{20540}{20588}To je uredu,|ali ja se u to ne meöam.
{20603}{20639}Ako me uhvate s tvojim momcima,|ja sam peËen.
{20665}{20761}IzgubiÊu brod. Ne zanima me.|- Ali, posetiÊe te veËeras.
{20790}{20885}Javi im da neÊu. DoÊi Êe uzalud.|éalim. Vidimo se kasnije.
{21540}{21636}Jesam li tuûan?
{21665}{21761}Zar ti moje suze niöta ne govore?
{21816}{21936}Jesam li tuûan? I ti bi bio kad bi ti|se sve izjalovilo.
{22166}{22262}Nekad sam mu bila jedina.
{22290}{22434}Sad sam ûalosna i usamljena.
{22466}{22561}Bila sam vesela, sve do danas.
{22590}{22662}Sad je otiöao i gotovo je.
{22691}{22715}Nastavi.
{22765}{22861}Nekad sam mu bila jedina.
{22940}{23060}Sad sam ûalosna i usamljena.
{23091}{23163}Bila sam vesela, sve do danas.
{23240}{23312}Sad je otiöao i gotovo je.
{23415}{23463}Jesam li tuûna?
{23815}{23887}Pokuöao sam, ali nisam mogao|doÊi u vezu s njima.
{23916}{23964}S onima koji su|hteli unajmiti moj brod?
{23990}{24026}Opasno je kad dou ovamo,|pa joö i uzalud.
{24041}{24137}Nisam ih molio da dou.|Vrati ih nazad.
{24966}{25086}Predajte mi ga. -äta hoÊete?|Dûonsonov novËanik. Hajde.
{25117}{25213}O Ëemu vi to govorite?|äta vam je gospodine?
{25467}{25515}äta Êete uraditi?
{25592}{25640}HoÊu taj novËanik, mröavice.
{25666}{25714}Volela bih da me|ne zovete mröavicom.
{25741}{25813}Premröava sam da bi mi se to svidelo.|- Prekinimo govor za bebe.
{25892}{26012}Gde je? -Znaö, Stiv,|nisam mislila da si takav.
{26067}{26115}Nisam znala da si hotelski detektiv.
{26141}{26213}Dûonson je moja muöterija.|- Ne govori lepo o tebi.
{26242}{26338}Ipak je moja muöterija.|Kradi od nekog ko mi nije duûan.
{26390}{26414}Ispao mu je, a ja sam ga podigla.
{26441}{26537}I htela si mu ga vratiti, naravno.|- Nisam. Ne svia mi se.
{26616}{26688}Dobar razlog. -Treba mi novac da|pobegnem iz Martinika.
{26716}{26788}Joö jeda razlog,|ali ukradi nekom drugom.
{26817}{26865}äta kaûeö na to! -Naöao si neöto?
{26891}{26987}60 dolara gotovine i 1400|u putnim Ëekovima.
{27016}{27088}OËekivao si viöe?|»ova mi duguje 825 dolara.
{27117}{27153}Nemam toliko kod sebe, reËe.
{27167}{27215}Idem u banku|pa Êu vas sutra isplatiti.
{27268}{27304}Uz to ima rezervaciju za avion,
{27316}{27352}koji poleÊe rano ujutru.
{27366}{27414}Hteo je klisnuti.|Tvoja muöterija!
{27467}{27515}Dobro da mu to nisi vratila.|- UËinila sam ti uslugu.
{27568}{27616}Da te nisam zaustavio,|odmaglila bi s tim.
{27642}{27738}Pripada mi jedan deo, zar ne,|mröavice.
{27817}{27865}Koliko da ti ostavim?
{27942}{27990}Sve prepuötam tebi.|äta kaûeö na...
{28191}{28263}Rekao sam im, ali neÊe ni da Ëuju.|- éerar nije kriv.
{28292}{28340}Uite i zatvorite vrata.
{28392}{28488}Rekao sam FrenËiju da me ne zanima.|- Znam. Zatvorite vrata.
{28567}{28663}Oprostite öto smo upali,|ali ovo je za nas vrlo vaûno.
{28716}{28752}Trenutak. -Ja idem.
{28817}{28865}VideÊemo se kasnije. -Ostani.
{28891}{28951}Moûete govoriti pred njom, zar ne,|mröavko? -Samo nastavite.
{28968}{29016}Ali ne pomaûe.|Doöli ste rizikujuÊi.
{29042}{29114}Ne bojimo se. -Ja da.|Ne mogu i neÊu to uraditi.
{29143}{29215}Dajemo vam 2500 franaka.|- To je samo 50 dolara.
{29241}{29313}Nama je to mnogo.|- Za plovidbu od samo 40 km.
{29368}{29392}Nemamo viöe novca.
{29416}{29464}Nemojte kriviti mene,|rekoh vam da ne mogu.
{29493}{29589}Kad doe do preokreta,|znaËiÊe vam mnogo. -Znam.
{29618}{29666}Mislio sam da su svi Amerikanci|na naöoj strani.
{29692}{29764}Jesu, ali sve koji rade öto i vi,|öalju na –avolje ostrvo.
{29793}{29912}Amerikanca neÊe poslati.|- Verujete u to?
{29992}{30016}Ko je?. -Ja sam, Heri.
{30116}{30140}Zdravo, kako ide?
{30167}{30215}Hteo sam samo popriËati...|- G. Organe, da nastavimo.
{30243}{30291}Ko su ovi? -Edi je moj prijatelj.
{30318}{30366}Ovaj je bio u luci kad si ti otiöao.
{30392}{30416}Imate dobro pamÊenje iako pijete.
{30430}{30526}Ne smeta mom pamÊenju.|Da mi smeta, ne bih pio.
{30543}{30615}Zaboravio bih kako je dobro piÊe.|Pio bih opet vodu.
{30641}{30761}Moûda biste zaboravili i vodu.|- Ne bih. Stalno je gledam.
{30843}{30891}Je li vas ikada ubola mrtva pËela?
{30917}{30965}Ne seÊam se da me je ikad ubola.
{31018}{31042}Je li vas ubola?
{31068}{31140}Vi i Heri ste jedini...|- Ne zaboravite FrenËija.
{31166}{31190}Vi, Heri i FrenËi.
{31217}{31265}Pazite mrtve pËele kad idete bosi.
{31293}{31341}Ako na nju nagazite,|ubode vas kao da je ûiva.
{31368}{31416}NaroËito ako se naljutila|kad su je ubili.
{31442}{31514}Mene su ubole stotinak puta.|- Zaöto im niste uzvratili?
{31567}{31639}To uvek Heri pita.|Ali ja nemam ûaoku.
{31668}{31763}PriËa li ovaj uvek toliko?|- Uvek. Zaöto sam ti trebao?
{31843}{31890}Ovaj, Heri...
{31943}{32039}Zaboravio sam.|- Vidimo se veËeras na pristaniötu.
{32068}{32140}Heri, moûeö li mi...? Hvala.
{32193}{32265}Moûemo razglabati celu noÊ,|ali odgovor je uvek isti.
{32293}{32365}Briga me ko vlada|Francuskom ili Martinikom.
{32392}{32487}Naite nekog drugog. Mröavko,|joö nismo zavröili s poslom.
{32543}{32615}Raskomotite se.|Cigarete su tamo na stolu.
{32718}{32802}Da vidim Dûonsonovo lice|kad mu ga vratiö.
{33367}{33427}Gde ste, svuda vas traûim.|Pobegli ste s mojom devojkom.
{33542}{33590}Vaö novËanik.
{33643}{33715}Odakle vam? -Ukrala sam ga.|- Lepo. äta Êete preduzeti.
{33780}{33888}Pitanje je öta Êe te vi.|Proverite je li sve tu.
{33955}{34015}Uredu je, sigurno.|- Proverite, moûda hoÊe priznanicu.
{34142}{34190}Niöta ne nedostaje.|- Sigurno? -Jesam. Mlada damo...
{34219}{34266}Prebrojte putne Ëekove.
{34343}{34391}Ima 1400 dolara.|- Sutra morate u banku.
{34418}{34465}U koje vreme poleÊe avion?|-6:30.
{34542}{34590}A banka se otvara u 10.
{34768}{34816}Ni meni se ne svia kao ni tebi.
{34842}{34866}Sluöajte, nameravao sam...
{34892}{34928}Nameravali ste potpisati|ove Ëekove, zar ne?
{34943}{35015}Da, svakako.|- Emile, imaö li pero?
{35319}{35367}Osam stotina dvadeset pet
{35417}{35465}Stanite! Ostanite gde ste!
{35719}{35815}Ostani gde si.|- Sedim na neËijoj cigareti.
{36518}{36566}Heri, ovo je gadno.|- Jesu li uhvatili sve?
{36595}{36666}Jedan je pobegao. Bokler.|Samo ja znam da ste ih upoznali.
{36743}{36815}I Edi, ali on ih se neÊe seÊati.
{36844}{36868}Kad doe policija, vi niöta ne znate.|Razumete?
{36880}{36916}FrenËi, ne budi lud. Ostani.
{37331}{37367}G. éerar!
{37657}{37693}Prekini, Krikit!
{37906}{37990}Da je bar brûe pisao,|ovi bi Ëekovi bili vaûeÊi.
{38280}{38316}Ostanite na mestu i budite mirni!
{38544}{38616}Ko su ovi? - Suret Nasional.|- Gestapo? - Da.
{38645}{38692}Mnogo ih je.
{39069}{39165}äta se dogodilo? - Zalutali metak.|Zove de Dûonson.
{39194}{39218}Nosite ga.
{39369}{39417}Tiöina. -Paûnja svima!
{39493}{39565}éalim zbog ovog,|ali nema mesta panici.
{39594}{39690}Zanimaju nas samo|prekröioci zakona.
{39769}{39889}OdveöÊemo samo neke.|Ostali neka se odmah raziu.
{39994}{40042}Ova gostionica se zatvara.
{40143}{40179}Ovaj.
{40193}{40289}Vi. I gospoica.
{40445}{40541}Je li te ikada ubola mrtva pËela?|- Poite sa mnom.
{40843}{40891}Ponavljam, ne poznajem te ljude.|Doöli su na piÊe.
{40920}{40992}Kaûete da ih nikada niste videli?|- Nisam.
{41018}{41066}Za koga ste G. éerar?|- Za Francusku.
{41095}{41167}Dobro. I ostanite takvi.
{41220}{41289}UpozoriÊemo G. éerara|da nas obavesti
{41294}{41414}Kad sledeÊi put u njegov restoran|dou sumnjiva lica.
{41445}{41493}Tako Êe spreËiti krvoproliÊe|na svom pragu
{41543}{41591}Kako Êu znati ko je sumnjiv,|a ko nije.
{41620}{41668}ZnaÊete. Laku noÊ.|- Moûete iÊi.
{41694}{41742}Jeste li sve uhvatili? -Nismo.|- Bokler i Emil su pobegli.
{41769}{41805}Kako? -IskoËili su i pobegli.
{41819}{41867}Pretraûite sva mesta prema popisu.
{41893}{41941}Kapetane Morgan, jeste li poznavali|te ljude? - Nisam.
{41970}{42018}Niste ih videli u kafeu? -Ne.
{42044}{42116}Kakve ste veze imali s ubijenim?|- Unajmio je moj Ëamac.
{42145}{42241}Prema karti u novËaniku|trebao je otputovati u zoru.
{42270}{42390}Nije bilo novca, samo Ëekovi.|Je li to kod njega uobiËajeno?
{42418}{42490}Bilo je 60 dolara.|- äta je s njima? -Uzeo sam ih.
{42519}{42591}Zaöto?|- Jer mi je dugovao 825 $.
{42620}{42668}ZnaËi, niste imali razlog da ga ubijete.|- Izgleda.
{42694}{42838}Naûalost, ubijen je,|pa ste vi uterali deo duga.
{42919}{42991}Imate li taj novac?|Dajte mi ga.
{43293}{43389}Molim, kapetane. -Ovo je moje.|- Kako to moûemo znati?
{43471}{43591}Ne brinite,|novac Ëuva pravna drûava.
{43646}{43718}Ako je vaö zahtev osnovan,|vratiÊemo ga.
{43845}{43893}Vi moûete iÊi.
{43946}{43994}Brauing Meri,|Amerikanka, 22 godine.
{44020}{44068}Koliko dugo ste u Fort d' Fransu?|- Stigla sam danas.
{44121}{44169}Gde str se smestili?|U hotelu Markiz.
{44195}{44243}Odakle dolazite?|Iz Port Spena.
{44269}{44389}A pre tog? -Iz Ria, Brazil.|- Sami? -Da.
{44444}{44540}Zaöto ste doöli ovamo?|- Da kupim novi öeöir.
{44569}{44617}Zaöto? -Da kupim novi öeöir.
{44646}{44694}»itajte nalepnicu|pa Êete mi verovati.
{44744}{44840}Nisam sumnjao,|ali stalno ste prigovarali.
{44871}{44943}Pitam ponovo,|Zaöto ste doöli ovamo?
{44969}{45017}Nisam imala novac za dalje.
{45070}{45118}Gde ste bili kada je poËela pucnjava?|- Ne moraö odgovoriti.
{45144}{45192}Umuknite! -Ne odgovaraj.
{45221}{45341}Hajde udarite me! -Smirite se.|éelimo samo da zakljuËimo istragu.
{45370}{45490}To neÊete postiÊi öamarajuÊi ljude.|Donosi nesreÊu. -VideÊemo.
{45521}{45593}Ako nam budete trebali,|biÊete u hotelu?
{45619}{45691}Gde da odem kad je moj|pasoö i novac kod vas?
{45720}{45768}Pasoö Êemo vam vratiti.
{45821}{45916}Ako je novac vaö,|sve Êe se srediti blagovremeno.
{45969}{46041}Da odem ameriËkom konzulu|da vam pomogne?
{46070}{46118}To je vaöe pravo.
{46171}{46243}Nego, kojoj strani ste naklonjeni?|- Ne meöam se u tue poslove.
{46271}{46319}Mogu li... - Ne trebaju mi saveti.
{46346}{46418}Laku noÊ, kapetane.|- Maknimo se öto pre.
{46645}{46765}Ne shvatam. Tek sam stigla.|- Usred malog rata.
{46796}{46844}Momci s kojima smo upravo bili|vezani su za Viöi.
{46945}{47017}ätiti ih mornarica.|Videla si nosaË u luci.
{47046}{47094}Oni momci na koje su pucali,|oni su za slobodnu Francusku.
{47146}{47194}Nije mi nimalo jasnije.
{47221}{47341}VeÊina domorodaca je za De Gola,|ali do sada su malo uradili.
{47369}{47441}Heri, jesmo li u nevolji?|- Nismo.
{47496}{47544}Video sam da su te odveli.|- Sve je u redu. Idi i spavaj.
{47571}{47667}Ja bih te izbavio, znaö ti mene.|- Znam. Vrati se na brod.
{47695}{47767}Mogu li...? -Ne.|VeËeras nema viöe. Posluöaj me.
{47945}{48041}Ja bih neöto popila.|- Moûemo ovde.
{49072}{49168}Samo razgledamo.|- Predomislio si se?
{49196}{49244}Nemam novca. Opeljeöili su me.
{49271}{49367}Zaboravila sam. Moûda mogu ja|neöto uËiniti. éedna sam.
{49446}{49518}Jesi li nekog odabrala?|- Ne zameraö?
{49597}{49693}Ako mi dosadi, vraÊam se u hotel.
{49971}{49995}Mogu li?
{50071}{50119}Hvala.
{50170}{50194}Izvinite me.
{50947}{50971}Ui.
{51146}{51194}Ljutiö se? -Zaöto bih?
{51246}{51270}Nisam se lepo ponela.
{51297}{51393}Sve je u redu. Imaö flaöu.|- Ljutiö se zar ne?
{51421}{51517}Sluöaj, nije me...|- Znam. Baöte briga öta ja radim.
{51570}{51690}Rekao si mi sam. -Ja?|- Rekao si, samo napred.
{51721}{51841}Mislim da jesam. I bila si uspeöna.|- Hvala.
{51872}{51944}Bilo bi ti milije da nisam.|- Da nisi öta? -»inila to.
{51970}{52018}Zaöto pitaö mene?|- Volela bih da znam.
{52272}{52392}S muökarcima je lako.|Svi su gomila...
{52447}{52567}I to kaûem ja.|Rugala se sova senici.
{52596}{52668}Koliko dugo nisi kod kuÊe?|- Sad je pravo vreme. - Za öta?
{52697}{52817}Za moju ûivotnu priËu. Odakle|da poËnem? - Znam veÊ sve.
{52846}{52917}Ko ti je rekao? - Ti. Na naËin|na koji si prihvatila öamar.
{52946}{53018}Ni okom nisi trepnula.|Za to treba duga veûba.
{53071}{53119}Znam mnogo o tebi, mröavko.
{53148}{53196}IduÊi put kad me oöamare|moraÊu neöto preduzeti.
{53222}{53294}Zaboravila si piÊe. - Ne treba mi.|- Ko se sada ljuti? - Ja.
{53797}{53893}Ko je? - Ja sam.|- Vrata nisu zakljuËana.
{53946}{53994}Zaboravila si bocu.|- Rekla sam da je ne ûelim.
{54071}{54119}Ljutiö se, zar ne?
{54147}{54219}Neöto sam te pitao, a nisi mi|odgovorila. - Ljutiö se.
{54246}{54342}Vidiö, umorna sam i ûelim spavati.|- Nije loöe. äta te je naljutilo?
{54476}{54550}- Poludela sam od kad sam te videla.|- Isto kao i veÊina njih.
{54565}{54641}Samo jedan pogled|i veÊ sve znaö o meni.
{54646}{54701}Ti si bio... »emu sada sve to?
{54725}{54764}Samo napred. I nastavi priËu.
{54788}{54828}Be znaö ti mene, Stiv.
{54869}{54900}Ne vredi.
{54948}{55018}Donela sam flaöu ovde|da bi se oseÊao manje vredan.
{55030}{55068}Zaista, nije vredelo.
{55116}{55166}Umesto toga,|ja se ovde oseÊam bezvrednom.
{55190}{55243}Nikad se pre nisam tako oseÊala.
{55329}{55356}éelela sam...
{55409}{55452}Mislila sam moûda...
{55672}{55754}Ajde, nastavi. Idi, pre nego|napravim joö veÊu budalu od sebe.
{55936}{55991}Koliko si veÊ dugo|izvan kuÊe i porodice?
{56025}{56056}Neöto oko...
{56116}{56147}Oko öest meseci.
{56157}{56183}VraÊaö li se?
{56202}{56257}- Kako?|- äta misliö da radiö ovde?
{56284}{56339}Ne znam. Moûda Êu dobiti posao.
{56365}{56444}Teöko je dobiti posao. Mislim da|ti se ovde ne bi nimalo svidelo.
{56507}{56552}Da li te podseÊam na nekoga, Stiv?
{56624}{56679}Ti si potpuno nova za mene.|Sviaö mi se.
{56703}{56749}Da li bi se vratila ako bi mogla?
{56773}{56797}Pa, iöla bih peöice...
{56847}{56893}da nije oko tolika vodurina.
{57312}{57375}Prestani da se brineö malecka.|VratiÊeö se sigurno.
{57936}{57996}- äta, ako...|- Evo ponovo flaöe.
{58079}{58147}Izgleda da to postaje problem,|zar ne?
{58195}{58231}- éeliö piÊe?|- Ne.
{58264}{58312}Mislio sam da si umorna|i da ûeliö da legneö..
{58317}{58401}Znam. I ja sam mislila.|Dao si mi ideju da razmislim o neËemu.
{58408}{58480}- Rekao si da bi mi mogao pomoÊi.|- Tako je.
{58485}{58528}Ali, kako to misliö ako...
{58547}{58631}Misliö li da radiö ovde|sa ljudima kod FrenËija?
{58636}{58693}Pa, ako ostane neöto od njih.
{58698}{58784}Letela sam iznad –avoljeg ostrva.|Ne izgleda kao odmaraliöte prve klase.
{58794}{58859}- Sluöao sam o tome.|- Ne ûelim da budem neöto öto Êe...
{58866}{58962}Nemoj misliti da to radim samo|da ti pomognem. I meni treba novac.
{59084}{59151}Zar FrenËi ne moûe da ti pomogne,|da ne bi morao sve to raditi?
{59156}{59194}Ne ûelim njegovu pomoÊ.
{59199}{59247}Nemoj to raditi, reci Stiv?
{59266}{59321}- Sluöaj, zar me nisi molila...|- Nemoj to raditi.
{59362}{59420}Zaöto ne uzmeö flaöu|i ne ideö u krevet?
{59477}{59520}Ovde. Uzeo bi ovo?
{59528}{59578}Mislio sam, ti reËe da si pobegla.
{59609}{59674}Baö si dobra. Neverovatno dobra.
{59705}{59770}"Otiöla bih kuÊi|da nije svuda voda."
{59851}{59918}- Ko je bila devojka, Stiv?|- Koje bila ta devojka?
{59928}{59995}Ona koja te je ostavila|sa tako lepim miöljenjem o ûenama.
{60000}{60045}Mora da je bila posebna devojka.
{60067}{60120}Misliö da i ja liËim na nju, zar ne?
{60125}{60177}SluËajno, ovde mi se zateklo $30.
{60182}{60244}Nije dovoljno za brodsku kartu|ali ni za neku drugu voûnju.
{60249}{60316}To samo znaËi "ne",|bar ja tako oseÊam.
{60324}{60379}Uzmi ako ûeliö.
{60420}{60451}éao mi je, mröavice.
{60501}{60554}Ali, ponovo kaûem, straöno si dobra|i ne bih...
{60556}{60640}Zaboravila sam. Ti ne bi uzeo niöta|od bilo koga, zar ne?
{60645}{60671}Tako je.
{60707}{60738}Znaö, Stiv...
{60765}{60849}nisi tako loö raËundûija.|Samo ponekad.
{60882}{60940}Ponekad znam taËno öta Êeö reÊi.
{60942}{61019}VeÊinom. U drugim sluËajevima...
{61093}{61146}U ostatku vremena ti si odvratan.
{61290}{61383}- Zbog Ëega si to uradila?|- Pitala sam se da li bi mi se svidelo.
{61388}{61424}I kakav je zakljuËak?
{61443}{61474}Joö ne znam.
{61664}{61709}Joö je bolje uz tvoju pomoÊ.
{61805}{61860}Jesi li siguran da se neÊeö|predomisliti u vezi ovog?
{61896}{61978}Pripada meni, kao i moje usne.|Ne vidim nikakvu razliku.
{61983}{62004}Siguran sam.
{62028}{62052}Uredu.
{62098}{62153}Znaj da ne moraö meni glumiti.
{62155}{62227}Ne moraö niöta reÊi ili Ëiniti.
{62232}{62261}Ni jednu stvar.
{62309}{62350}Moûda samo zviûdi.
{62450}{62508}Znaö kako se zviûdi, zar ne, Stiv?
{62513}{62577}Samo sastavi usne i duni.
{63102}{63158}Doi, pilence.
{63436}{63472}Nastavi da paziö.
{63517}{63563}Sve je uredu. Otiöli su.
{63594}{63620}Nastavi.
{63644}{63709}Doi pored obale Angilije|s juûne strane.
{63714}{63755}Oko tri kilometra od znaka.
{63757}{63827}- Tu ima mala peÊina i brana?|- Onda, sve znaö.
{63836}{63886}- Signal je ugovoren?|- Emil Êe vam pokazati.
{63891}{63927}- Emil neÊe biti tamo.|- Zaöto?
{63930}{63985}Radim to na svoj naËin. Idem sam.
{64021}{64052}Kakvi su signali?
{64057}{64129}PoslaÊeö znak svetlom prema obali.|Oni Êe odgovoriti sa dva prekida svetlom.
{64148}{64215}Jedan za drugim.|BiÊe dvoje ljudi koje Êeö dovesti.
{64222}{64263}- Kako Êu ih prepoznati?|- Mi ih nismo nikada videli.
{64265}{64318}Znamo ime samo jednoga.|Pol de Birsak.
{64323}{64397}Sasvim dovoljno.|Gde da ih iskrcam ovde?
{64404}{64447}Poznajete li Cap Sent-Pier?
{64450}{64534}- »amac Êe ih primiti na otvorenom moru.|- Ti Êeö biti u Ëamcu, FrenËi.
{64541}{64601}PoÊi Êu oko podne.|Kao da idem u ribolov.
{64603}{64682}Sa malo sreÊe i bez patrolnih brodova,|vratiÊu se u San-Pjer oko ponoÊi.
{64687}{64747}NeÊu paliti nikakvo svelo,|zato dobro pazite.
{64750}{64786}Joö neöto, Mr. Morgan.
{64795}{64877}Proöle noÊi vi ste definitivno odbili|bilo kakvu saradnju sa nama.
{64884}{64922}Zaöto ste se predomislili?
{64927}{64980}Sada mi je potreban novac.|Proöle noÊi mi nije trebao.
{64985}{65054}- Ako ste znali koliko to nama znaËi...|- Ne ûelim da znam.
{65059}{65095}Drago mi je da ste na naöoj strani.
{65100}{65143}Nisam. Za to Êu biti plaÊen.
{65160}{65224}Nego, kad veÊ priËamo o tome,|ûeleo bih taj novac sada.
{65253}{65335}Da sam na vaöem mestu, mislim|da ne bih verovala Mr. Morganu.
{65419}{65452}Da li vam je doktor pregledao nogu?
{65457}{65526}Nije. Motre na sve doktore koji|su naöi simpatizeri.
{65529}{65589}- Je li promaöilo kost?|- Rekao bih da nije suviöe blizu.
{65591}{65637}Imao je sreÊe.|Zaöto ste podmetnuli jastuk?
{65641}{65694}- A zaöto ne?|- Ovako manje boli.
{65697}{65742}BoleÊe te, trebalo bi da uzmeö...
{65747}{65814}pod uslovom da ne ûeliö|da dobijeö gangrenu.
{65817}{65850}Uredu, uzeÊu.
{65855}{65886}Jeste li vi doktor?
{65893}{65965}Nisam, ali sam leËio dosta rana|od posledica metka.
{65987}{66023}Sada mi moûete verovati.
{66023}{66054}SreÊno, Heri.
{66121}{66150}Uredu je.
{66423}{66473}- Joö kafe, gospoice?|- Da, molim vas.
{66636}{66699}- äta je to öto svirate?|- Rekli ste neöto?
{66704}{66740}Kako se zove melodija?
{66744}{66828}Joö nema ime.|Zamajavam se sa reËima pesme.
{66835}{66900}Nisu prejake, pretpostavljam.|éelite da ih Ëujete?
{66905}{66929}Naravno.
{67262}{67385}TrËim do telefona Ëim zazvoni
{67461}{67588}Ne mogu biti sam,|to ti se ponekad dogaa
{67663}{67761}I priËam zvezdi o patnjama
{67811}{67886}Visim u baru dok ne zatvore
{67970}{68092}- Eto, tako ide.|- Svia mi se.
{68099}{68149}Da. Kad bih pronaöao prave reËi|za pesmu.
{68401}{68461}- Dobro jutro, Krikit.|- Jutro, Heri.
{68466}{68499}- Dobro jutro, mröavko.|- Zdravo.
{68502}{68559}- Kako si spavala?|- Mnogo dobro, posle duûeg vremena.
{68564}{68624}- éeliö li kafu?|- Ne, hvala. VeÊ imam.
{68631}{68694}Ustao si rano. äta si radio?
{68696}{68782}Doneo sam ti avionsku kartu za|poslepodnevni let. PoleÊe u 4:00.
{68790}{68835}- UradiÊeö to?|- Naravno.
{68878}{68921}Prihvatio si posao, zar ne?
{68948}{69020}Znaö, kontao sam to ovako:|ne bi trebalo da pokvasiö noge.
{69025}{69058}Eh. Tako je nekako.
{69063}{69120}- To si ûelela, zar ne?|- Naravno.
{69128}{69152}Upravo sam...
{69226}{69305}- éeliö da odem, zar ne?|- Da, ûelim da odeö.
{69334}{69367}Uredu, Stiv.
{69377}{69427}Pomozi joj da ode u avion,|hoÊeö li Krikit?
{69432}{69466}Naravno da hoÊu, Heri.
{69470}{69562}ImaÊu puno posla danas,|verovatno te neÊu ponovo videti.
{69576}{69622}- Ako me nekada nanese put do tebe...|- E, pa neka te nanese.
{69626}{69705}OstaviÊu adresu kod FrenËija,|tako Êeö me pronaÊi.
{69727}{69787}Moûda Êu nauËiti|do tada da zviûduÊem.
{69799}{69852}- Dovienja, mröavko.|- Dovienja, Stiv
{70053}{70108}Eto, bilo je lepo dok je trajalo.
{70127}{70175}Moûda je ovako bolje, mröavko.
{70187}{70214}Ne znam.
{70238}{70305}Ti ga ne poznajeö dovoljno dugo.|Pomalo je neobiËan momak.
{70660}{70753}- Kako si Heri? Je li sve uredu?|- Lepo. Rekao sam ti da ostaneö u hotelu.
{70760}{70818}- Znam da negde polaziö.|- Ko ti je to rekao?
{70823}{70883}Ne moûeö me prevariti, Heri.|Znao sam da se neöto sprema.
{70885}{70950}- Reci, da li bih mogao malo...|- Ti ne ideö.
{70955}{71034}Da li bi moglo jedno malo,|samo jedno malecko?
{71046}{71094}- Ma daj, Edi. Mani me se.|- O Ëemu se radi?
{71098}{71178}Nema naËina da me uÊutkaö.|Smiri se. Dobio si...
{71439}{71470}Ja to tebi ne bih nikad uradio.
{71475}{71547}U pravu si, zaista ne bi. Ne mogu|da te povedem, samo toliko da znaö.
{71552}{71624}- Zbog Ëega me odbacujeö?|- Trebao bi da mi verujeö.
{71628}{71691}- Nemoj da me smatraö vezanom vreÊom.|- Ko misli da si vezana vreÊa?
{71693}{71767}Mogao bi prevariti svoju majku.|LiËno si mi rekao.
{71772}{71806}Samo sam se öalio.
{72017}{72079}Hvala, Heri.|Znao sam da si moj drug.
{72101}{72173}- Ali, zaöto neÊeö da me povedeö?|- Zato öto mi ne trebaö.
{72189}{72237}Znaö, opet si me prevario.
{72242}{72316}Nije vaûno stari druûe,|biÊe ti drago da me ponovo vidiö.
{72935}{72978}Uredu. Hajde izlazi odatle.
{73031}{73074}To sam samo ja, Heri.
{73105}{73141}Kako si se vratio na brod?
{73146}{73192}Izaöao sam na ulicu|da nabavim nekoliko flaöa.
{73196}{73256}Onda sam se uöunjao|dok si ti radio oko motora.
{73259}{73307}- Znao sam da Êeö me povesti.|- Tebe povesti, nikada.
{73309}{73369}Da znam da se moûeö plivajuÊi vratiti|nazad, bacio bih te preko ograde.
{73376}{73448}Baö si öaljivËina.|Uvek smo skupa kada smo u nevolji.
{73453}{73546}- Kako si znao da sam u nevolji?|- Ne moûeö me prevariti. Ja uvek znam.
{73558}{73590}Gde idemo, Heri?
{73592}{73633}äta bi uradio|ako bi neko pucao u tebe?
{73637}{73676}Pucao u mene? Iz piötolja?
{73733}{73808}- Ko bi pucao u mene?|- Ako budeö imao sreÊe, onda niko.
{73858}{73894}Gde idemo? äta Êemo to raditi?
{73899}{73964}ReÊi Êu ti kad za to doe vreme.|Prihvati se posla.
{73968}{74007}Jesi li zadovoljan öto si poöao?
{74033}{74057}Ne.
{74314}{74390}- Uzmi. Ogrni se. Postaje hladno.|- Dobro sam, Heri.
{74601}{74654}Reci, öta se deöava?
{74678}{74726}- U Ëemu je stvar?|- Ni u Ëemu.
{74740}{74812}Da, ima tu neöto.|Za öta Êe ti kog avola puöke?
{74836}{74887}U sluËaju da naletimo na ajkule|ili tako neöto.
{74891}{74927}Ajkule? Po noÊi?
{74973}{75045}Ili neöto?|äta si mislio, "ili neöto"?
{75047}{75098}- Pazi na kurs.|- äta se deöava?
{75102}{75170}Idemo da radimo. ReÊi Êu ti|öta Êemo raditi kad doe vreme.
{75174}{75196}Posao?
{75225}{75287}Kakav posao?|äta oËekujeö od mene da radim?
{75297}{75333}Znaö li rukovati sa ovim?
{75335}{75400}Naravno da znam.|Svi znaju rukovati puökom.
{75405}{75484}Sve öto treba da uradiö je da repetiraö i|pritisneö okidaË. Znaö da to umem.
{75491}{75580}Baö glupa pitanja.|Da li znam rukovati puökom.
{75711}{75793}- äta treba da radim ako ni treba puöka?|- Baö sam se pitao da li moûe.
{75795}{75824}Znaö da mogu.
{75829}{75901}Heri, ponekad Ëiniö gluposti.|»iste gluposti.
{75908}{75999}Ponekad mislim da ne obraÊaö paûnju|na ono öto govorim.
{76119}{76165}Da li Êe biti gadno, Heri?
{76169}{76241}Joö ne znam.|Sve zavisi koliko budemo imali sreÊe.
{76380}{76428}Zbog toga me nisi hteo povesti.
{76433}{76522}Znao sam da postoji neki razlog.|Nisi uopöte bio ljut na mene.
{76632}{76685}Plaöio si se da ne budem povreen.|Mislio si o meni.
{76690}{76730}Pazi na kurs, Edi.
{76754}{76843}Sad se oseÊam bolje, Heri.|BiÊu ja dobro. VideÊeö.
{77107}{77181}äta je bilo?|Zaöto me tako gledaö?
{77210}{77246}Zaöto se smejeö?
{77248}{77311}Samo zbog öale za koju ne znamo|odgovor, ni ja ni ti.
{77315}{77339}Kakve öale?
{77344}{77390}Jesmo li zajedno ili ne.
{77390}{77459}Nemoj tako govoriti, Heri.|Dobar sa Ëovek. Znaö da jesam.
{77486}{77560}Jesi, ali voziö preko okeana.|Drûi kurs.
{77570}{77608}Zaöto uvek...
{77687}{77757}Mogu li samo jedno?|Ne ûelim da dobijem drhtavicu.
{77771}{77843}Samo jedno malo. éelim da te rum|ohrabri, a ne da budeö beskoristan.
{77845}{77876}Hvala, Heri.
{78375}{78416}O Ëemu se radi, Heri?
{78845}{78936}- Ko je to? äta trba da radimo?|- Da prevezemo neke momke.
{78943}{79027}Evo öta ûelim da uradiö.|Uzmi puöku i idi pozadi na krmu.
{79034}{79102}Ako bude neke nevolje, pucaj.|Ali nemoj da pogodiö mene.
{79104}{79169}Ako pretpostavimo da ti se neöto desi?|äta treba onda da radim?
{79174}{79245}Kako da znam? Sam si se pozvao|na putovanje, nisam ja.
{79255}{79296}Uredu, idi pozadi.
{79936}{79991}Zovem se Heri Morgan.|Poslao me je Bokler.
{79996}{80027}Maknite to svetlo s mog lica.
{80058}{80128}- äta se desilo Bokleru?|- Upao je u malu nezgodu.
{80135}{80178}- Kako se zovete?|- De Birsak.
{80200}{80252}Ime je uredu. Uredu je, Edi.
{80269}{80298}Ukrcavajte se.
{80312}{80370}Samo trenutak.|Niöta nije rekao o ûeni.
{80372}{80430}Dozvolite.|Ovo je moja ûena, Madam de Birsak.
{80435}{80466}Kako ste?
{80468}{80514}Koga ûeliö da povedeö...
{80612}{80679}Ovo je tvoj pogreb.|Hajdemo odavde.
{81132}{81180}Uredu je, Edi, moûeö da se opustiö.
{81223}{81271}Nemoj prazniti. Nismo joö ko kuÊe.
{81288}{81351}Ako joj bude hladno,|smestite je dole u kabinu.
{81389}{81432}Mr. Morgan, ko ste vi zapravo?
{81446}{81535}Ovo je moj brod. Bokler mi je platio|da prevezem vaöe ljude na Martinik.
{81542}{81600}Vi niste jedan od naöih.|Niste na naöoj strani.
{81614}{81648}Ne razumem.
{81653}{81713}Ne razumem|koju borbu i za koga je vodite...
{81717}{81794}vodite vaöe ûene sa sobom.|Zar vam ih nije dosta kod kuÊe?
{81799}{81852}- Kaûete da ste plaÊeni za ovo.|- Tako je.
{81856}{81919}Onda vam preporuËujem da prestanete|priËati i vodite nas na Martinik.
{81924}{81974}Tamo i idemo.
{82676}{82729}- äta se deöava, Heri?|- Budi tih.
{82765}{82816}Mislim da sam tamo video neöto.
{82878}{82902}Sluöaj.
{83041}{83082}- äta li je to?|- Ne znam.
{83086}{83137}UÊuti. »ujeö li to?
{83168}{83204}Da li je to patrolni brod?
{83214}{83305}Zar ne prepoznajeö te motore?|ZvuËe kao da su ovde.
{83413}{83472}Stani iza kormila..|SaËekaj trenutak. Daj mi puöku.
{83477}{83523}Ne moûeö se puökom boriti|protiv tih momaka, Heri.
{83525}{83559}äta je s tobom?
{83561}{83609}Ti bi mi trebao reÊi koliko si dobar.
{83614}{83671}Mogu to uraditi.|äta ûeliö da uradim?
{83683}{83777}Ako budemo imali sreÊe, onda niöta.|A ako ne budemo imali, ona öto brûe odavde.
{83784}{83854}- äta to znaËi, Mr. Morgan?|- Nevolja, ako nas opaze.
{83856}{83914}- äta Êemo da radimo?|- Vi ne moûete niöta uËiniti.
{83926}{83986}Idite dole u zaklon,|lezite i ostanite tamo.
{83993}{84031}Ne znam da li Êe to biti dobro.
{84031}{84101}- Ako pokuöate pruûiti otpor, ubiÊe nas.|- Zaveûite, oboje.
{84108}{84146}Idite dole u zaklon i lezite.
{84156}{84211}Vi spaöavate Francusku,|a ja hoÊu da spasem svoj brod.
{84242}{84285}Opusti se Edi. Idemo.
{84367}{84393}Ne pucaj!
{84885}{84918}Ponovo smo imali sreÊe.
{84971}{85057}Usmeri je na 160|i da mi kutiju prve pomoÊi.
{85268}{85299}Nije tako loöe.
{85302}{85364}Ne bi vam se to desilo|da se niste unervozili.
{85369}{85405}Molim vas, pomozite mi|da ga smestim na sediöte.
{85410}{85470}Ostavite ga.|Ne ûelim da mi krvari na jastuku.
{85474}{85534}- Evo, Heri.|- Moûeö sad popiti piÊe.
{85542}{85570}Hvala, Heri.
{85604}{85645}Pomozite mi oko njegovog kaputa.
{85695}{85724}Polako momËe.
{86050}{86086}Uredu. Spremite se.
{86091}{86146}»ovek u Ëamcu Êe vas odvesti odavde.
{86151}{86191}Ali, ja ne shvatam.
{86196}{86258}Neki ljudi su proveli mnogo vremena|da bi ovo sredili na ovaj naËin.
{86263}{86311}Oni znaju mnogo viöe od nas.
{86592}{86623}Ovo je Birsak.
{86635}{86704}Ovo je druga osoba koju sam|trebao pokupiti. Njegova ûena.
{86709}{86755}- Zovem se éerar.|- Kako ste?
{86757}{86822}- Polako sa njim. Malo je upucan.|- äta se desilo?
{86824}{86889}Naleteli smo na patrolni brod.|Oni Êe ti ispriËati.
{86968}{87033}Plovio sam okolo|i dao ti öansu da doeö do obale.
{87035}{87076}- SreÊno.|- Hvala.
{87524}{87565}Dobro veËe, Mama.
{87762}{87838}- Mislilo sam da si rekao, ona odlazi.|- I ja sam isto mislio.
{88222}{88251}Zdravo, Stiv.
{88265}{88304}Trebao si je odvesti u avion.
{88306}{88380}- äta je bilo? Nije iölo?|- Iöla sam. Ali sam odluËila da ostanem.
{88385}{88457}I ostala si? Upao sam u mnoge nevolje|da bi ti mogla odavde otiÊi.
{88462}{88505}- Za to nisam ni otiöla.|- Jeah.
{88543}{88618}Da si prokleta.|Momak je podmetnu lea da bi...
{88639}{88685}Moûda sam to i oËekivao.
{88769}{88802}Nije ti ûao, zar ne?
{88805}{88879}- Sve Êe biti uredu...|- Dobila sam nazad novac od karte. Evo ga.
{88884}{88934}To Êe baö puno pomoÊi.|Bolje da se obesiö o njega.
{88939}{88980}- Moûemo uzeti...|- Ona Êe to kupiti za tebe.
{88982}{89030}- Niöta, samo pivo za njega.|- ZapamtiÊu.
{89032}{89080}Sve Êe biti uredu. Dobila sam posao.
{89083}{89162}- äta si uradila?|- FrenËi misli da mogu pevati.
{89172}{89205}Ovo je njegov lokal.
{89210}{89265}Ponekad me razljutiö i mogla bih...
{89270}{89296}äta bi mogla?
{89301}{89335}Heri, potrebna mi je tvoja pomoÊ.
{89342}{89373}äta je sada?
{89395}{89428}Uredu je. Samo nastavi.
{89430}{89476}Onaj Ëovek je vrlo teöko ranjen,|Heri.
{89481}{89550}Pogledao sam ga. Metak je pogodio|oplatu broda, zamalo da je probije.
{89555}{89615}- Sve öto treba da uradiö je da ga izvadiö.|- Da li bi to uËinio?
{89622}{89701}Ja? Ja sam sumnjiviji od bilo kojeg doktora.|Sigurno Êe prepoznati moj brod.
{89709}{89735}Sigurno su mi za petama.
{89737}{89807}- Sve öto treba da uradim je da se|Ëistim odavde. - Ne moraö da odlaziö.
{89814}{89872}- Ti ih nisi doveo ovde?|- U skloniöte.
{89888}{89958}Zaöto ih nisi stavio u zdelu sa zlatnom|ribicom i sve bi bilo uredu?
{89963}{90042}Moramo neöto uËiniti.|Oni nadgledaju sve izlaze iz grada.
{90049}{90102}Vidiö u öta si se uvalila|övrljajuÊi okolo?
{90107}{90143}Spremna sam da poem|svakog trenutka kad i ti.
{90145}{90217}- Molim te, Heri, hoÊeö li to uËiniti?|- Nema öanse, FrenËi.
{90248}{90308}Vi ste bili ovde u hotelu,|ostali ste...
{90310}{90382}to iznosi 6,356 franaka.
{90397}{90435}U pravu je, Edi.
{90437}{90483}Vi zaista vodite knjigu, zar ne?
{90488}{90581}Bilo bi nam drago da zaboravimo|na taj dug, ako to uradite za nas.
{90615}{90660}- PriznaÊete i njezin raËun?|- Podrazumeva se.
{90663}{90735}- I sve sam to dobio samo da izvadim|metak iz rane... - To je sve.
{90756}{90835}Skoro ste ubedili, Mama,|izuzev jedne stvari.
{90840}{90871}Ja joö uvek dugujem taj raËun.
{90876}{90917}Gore, u mojoj sobi,|naÊi Êeö kutiju prve pomoÊi.
{90919}{90970}Siva je i velika,|ima na sebi oznaku broda.
{90970}{91015}- Donesi je u skloniöte.|- Svakako.
{91020}{91068}Evo ti kljuË. Donesi i tople vode.
{91073}{91104}Ovuda, Heri.
{91188}{91209}Mogu li ja da pomognem?
{91214}{91279}Samo se malo negde skloni.|Ako sluËajno naletiö na policiju...
{91284}{91361}- nemoj zaboraviti öta sam ti rekao|da im kaûeö. - äta ono beöe, Heri?
{91392}{91435}Samo se malo negde skloni, Edi.
{91452}{91478}ZapamtiÊu.
{92087}{92116}äta vi hoÊete ovde?
{92118}{92171}ReÊi Êu vam. Ja sam neko|koga su pozvali. On me zamolio.
{92176}{92207}- Vi niste doktor.|- Nisam.
{92212}{92252}- Gde je doktor?|- Molim vas, smirite se.
{92257}{92310}Bila sam strpljiva.|Kako da znam da znate bilo öta?
{92315}{92365}- I ne morate.|- Samo malo.
{92751}{92792}Koliko dugo je bio u nesvesti?
{92794}{92828}Samo nekoliko minuta.
{93142}{93202}Ima groznicu i puls mu je sniûen.
{93207}{93255}BiÊe on uredu,|samo kad mu izvadimo metak iz rane.
{93259}{93331}- Da ga niste taknuli. »ujete li?|- Uredu je. Nisam plaÊen za ovo.
{93334}{93389}Ne zna öta govori.|Sva je van sebe.
{93394}{93449}- Ko je ona?|- Heri, obeÊao si.
{93473}{93545}éelite da pomognete muûu, zar ne?|Onda razmislite glavom.
{93552}{93605}Ne moûemo dobiti doktora,|a da se ne otkrijemo.
{93609}{93672}Uzgred, sa mnom ima öanse|kao ni sa kime drugim.
{93674}{93710}NeÊu vam to dozvoliti.
{93713}{93761}A zaöto ne?|On nije drugaËiji od bilo koga drugog.
{93761}{93847}Samo malo bolesniji, to je sve.|Mislite da nije vredan dovoljno.
{93957}{94000}ImaÊete öansu|da to pokuöate malo kasnije.
{94000}{94036}- Zdravo, mröavko.|- Zdravo.
{94039}{94072}Mis Brauning, Madam de Birsak.
{94077}{94137}Nemoj to pokuöati sa mröavkom.|UzvratiÊe ti udarac.
{94142}{94197}To je ono öto si rekla da Êeö uraditi,|nije li tako?
{94204}{94242}Stavi vodu ovde.
{94247}{94295}- Samo trenutak...|- Pokuöava da vam pomogne.
{94300}{94370}- Ko ste vi?|- Niko. Samo joö jedan dobrovoljac.
{94456}{94516}- Gde ûeliö ovu vodu?|- U lavor.
{94542}{94578}- Je li vruÊa?|- Vrela.
{94633}{94710}Uredu, onda.|Nakvasi ovo. I stavi ovo unutra.
{94787}{94863}- Izaite odavde. Moûda vam se|ovo neÊe dopasti. - BiÊu ja dobro.
{94907}{94938}Onda, uzmite ovo.
{94959}{95000}- äta je to?|- Hloroform.
{95003}{95070}Stanite mu iznad glave.|Ako se probudi dok pokuöavam...
{95074}{95149}naspite malo na gazu|i dajte mu da udahne.
{95166}{95213}Nemojte otvarati|dok vam ja ne kaûem.
{95252}{95295}Uzmi Ëetiri od ovih.
{95408}{95487}Dûordû, podigni lampu malo bliûe|tako da mogu videti öta radim.
{95688}{95717}Dobro je tako.
{95813}{95851}Uredu, mröavko.
{95995}{96033}Zadrûi to neko vreme.
{96156}{96185}Polako, momËe.
{96206}{96259}A sada, otvorite poklopac|i dajte mi malo.
{96264}{96324}Dûordû, Vidi da li mu moûeö drûati|spuötenu glavu.
{96331}{96362}Hajde, poûuri.
{96415}{96494}Dobro je. Ne brini se za nju.|Podigni tu boËicu.
{96549}{96602}- Je li ötogod ostalo u njoj?|- Mislim da ima dovoljno.
{96700}{96779}Samo trenutak, nisam mislio|da Êe nam trebati. I on se gubi.
{96810}{96861}Spusti lampu malo niûe.
{96897}{96947}FrenËi, prinesi lavor ovde.
{97036}{97117}Rasteraj malo isparenje dalje od nas,|inaËe Êemo i mi popadati.
{97474}{97542}Tu smo, FrenËi, evo tvog metka.
{97563}{97625}Rekao sam ti da je od oplate broda.|Moglo mu je slomiti kost.
{97630}{97676}Uredu, to mi ne treba.
{98040}{98122}Tako je, ti zavröi previjanje.|Flaster stavi u kutiju.
{98136}{98210}Trebam da iznesem odavde pomoÊnicu,|ili neÊe se nikada probuditi.
{98515}{98575}äta pokuöavaö da uradiö,|proceni koliko je teöka?
{98587}{98630}Teûa je nego öto misliö.
{98776}{98855}- Bolje bi bilo da joj raskopËaö odeÊu.|- Uradio si to kako treba.
{98949}{99004}Bolje bi bilo da paziö|na njezinog muûa.
{99014}{99074}- NeÊe on poÊi za mnom.|- NeÊe ni ona.
{99232}{99304}Stiv, da li bi bilo dobro|da joj dam malo ovoga da udahne?
{99711}{99755}Ponovo ste s nama.
{99781}{99831}Imali ste sreÊe. Spasili ste se.
{99867}{99913}äta se desilo? Mi moramo...
{99918}{100009}O tome Êemo priËati ujutru.|Pokuöajte da malo spavate.
{100040}{100066}Hvala.
{100486}{100558}Zaöto ste uopöte poöli s njim|na ovakvo putovanje?
{100560}{100651}Volim ga.|éelim da budemo zajedno.
{100690}{100764}- To i jeste razlog.|- Postoji i drugi razlog.
{100790}{100848}Rekli su mi da i ja doem,|naöi ljudi su traûili.
{100932}{101030}Oni kaûu da Ëovek ne vredi mnogo|ako je ostavio nekoga u Francuskoj...
{101037}{101092}da je nau Nemci i da je zatvore.
{101150}{101234}- To je razumno.|- Rekla sam im da Êu biti na putu...
{101241}{101313}koji ne obeÊava niöta dobro,|i za to se plaöim.
{101378}{101469}Ali, joö teûe je za njega|da me vodi sa sobom...
{101526}{101617}za to i ja snosim krivicu.|Sada je i on uplaöen.
{101692}{101735}Nije to on izmislio.
{101752}{101802}- äta nije izmislio?|- Da se plaöi.
{101881}{101915}Hvala, Mr. Morgan.
{102332}{102370}Groznica je proöla.
{102423}{102471}Da li ste...
{102483}{102543}Nisam doktor,|ali meni izgleda sasvim dobro.
{102598}{102663}Ako se probudi,|dajte mi jednu od onih tableta.
{103027}{103111}- Mr. Morgan, ja...|- Ne morate me se viöe plaöiti?
{103138}{103245}Ne, doöla sam u teöku situaciju|pokuöavajuÊi da neöto kaûem.
{103253}{103308}Samo napred, recite.|NeÊu vas udariti.
{103341}{103401}Da nije bilo vas, moûda bi Pol...
{103437}{103478}éao mi je öto sam se onako ponela.
{103483}{103569}Uopöte vam nije ûao.|ûalite öto ste napravili budalu od sebe.
{103596}{103629}Jesam, zar ne?
{103723}{103780}Ne ljutim se öto to kaûete.
{103802}{103878}Mislim da se nikada neÊu naljutiti|bilo öta da kaûete.
{103905}{103958}Joö jedna ekscentriËna dama.|Nego, kako moûete...
{103962}{104051}Dobro jutro. éao mi je öto vas prekidam,|donela sam vam doruËak.
{104109}{104154}- Dobro jutro.|- Kako je vaö pacijent?
{104159}{104224}- BiÊe on dobro...|- Ili da pogledate kasnije?
{104228}{104305}BiÊe on dobro. VratiÊu se popodne.
{104324}{104384}- Ako vam budem trebao pre toga,|zovite me. - HoÊu.
{104389}{104447}Da, i nadam se da imaö ovde|sve öto ti treba.
{104449}{104487}Moûda su jaja tvrdo kuvana...
{104490}{104571}- Uredu je, volim ih na taj naËin.|- Imate sreÊe.
{104732}{104792}Idem da malo odspavam,|videÊu te kasnije.
{104895}{104924}Hvala.
{104957}{105020}- äta ti treba?|- Da se posluûim öibicom.
{105238}{105305}Hvala. Sada mi treba i cigareta.
{105576}{105648}SaËekaj, ja Êu to uraditi.|Ma hajde, dozvoli mi da ti pomognem.
{105653}{105734}Kad hoÊu da skinem cipele,|ja to uradim sam.
{105768}{105796}Pa, dobro.
{105830}{105878}- éeliö li neöto za jelo?|- Ne.
{105907}{105984}- Jedan mali doruËkiÊ?|- Sve öto ûelim je da malo odspavam.
{105986}{106053}Dobra ideja. PomoÊi Êu ti u tome.
{106079}{106168}- Gde sada ideö? - Idem|da ti pripremim lepo i toplo kupatilo.
{106180}{106221}Bolje Êeö spavati.
{106223}{106310}Ne ûelim da mi skidaö cipele,|ne ûelim da mi doneseö doruËak...
{106317}{106362}ne ûelim da mi pripremiö|toplo kupatilo...
{106365}{106437}ne ûelim da mi... - Ima li iöta|öto bih mogla uraditi za tebe, Stiv?
{106441}{106499}- Da, hajde...|- Znaö, Mr. Morgan...
{106504}{106564}uopöte me ne ljutiö kad to kaûeö.
{106569}{106652}Ne mislim da se nikad neÊu naljutiti|kad neöto kaûeö.
{106748}{106811}Kako ja to radim, Steve,|da li vredi pokuöati drugi put?
{106815}{106885}»ekaö da neöto uradiö za mene, zar ne?
{106967}{107002}KoraËaj oko mene.
{107022}{107079}Hajde, koraËaj oko mene, pun krug.
{107367}{107415}- Da li si pronaöla neöto?|- Ne.
{107444}{107552}Ne, Steve.|Joö nije niöta prikaËeno za tebe, joö ne.
{108007}{108033}Volim tako...
{108122}{108156}osim brade.
{108199}{108242}Zaöto se ne obrijeö...
{108300}{108336}pa da pokuöamo ponovo.
{108475}{108518}- Kasnije, FrenËi.|- Heri, Ëekaj.
{108520}{108583}Renar, Inspektor, je dole.|Bolje da sieö dole.
{108587}{108650}- Ne mogu sada, idem da se obrijem.|- Sa Edijem je.
{108681}{108736}Daje mu da pije|i postavlja mu razna pitanja.
{108741}{108779}Toga sam se bojao.
{108810}{108853}Dobro je da me ne smesti u kadu.
{108856}{108945}Pazi na ûice, Stiv.|Pazi kuda koraËaö, slomiÊeö vrat.
{108952}{109040}- éice? Nisam video nikakve ûice.|- Samo nisu vidljive, FrenËi.
{109115}{109151}Trebalo je da vidite tu ribu.
{109153}{109201}Mora da je teûila 900|ako merimo funtama.
{109206}{109271}To je najveÊi marlin|koga ste ikad videli u svom ûivotu.
{109278}{109316}Znate, marlin je sabljarka.
{109319}{109388}- Dobro jutro, kapetane.|- Zdravo, Heri. Je li sve uredu?
{109395}{109431}- Lepo.|- éelite nam se pridruûiti?
{109431}{109486}Joö je malo rano|za ovakvu vrstu zabave.
{109489}{109515}Nastavite, Mr. Edi.
{109520}{109563}Jesi li Ëuo?|Nazvao me je gospodinom.
{109568}{109606}Reci, da si dobro.
{109618}{109683}- Da li te je ikad ujela...|- Ne, nije nikad, Edi.
{109688}{109726}Nastavite o onome öto ste priËali.
{109729}{109810}Baö im priËam o onoj velikoj|koju smo zakaËili proöle noÊ.
{109817}{109901}Ser, riba je bila toliko velika da je|ni ja ni Heri nismo mogli pomeriti.
{109904}{109966}Batrgali smo se oko nje|sve dok se nismo zamorili, zar ne?
{109971}{110004}Tako je, Edi.
{110014}{110071}VeÊ se bilo smraËilo,|a mi smo se joö s njom borili.
{110076}{110175}Mora da je teûila bar 1,000 funti.
{110208}{110299}Svaki put kad Mr. Edi popije piÊe,|Ëuvena riba joö viöe poraste.
{110306}{110366}Mora da je poËeo sa dosta malenom.
{110393}{110448}Kako se na kraju zavröili|sa takvim morski Ëudoviötem?
{110450}{110489}Nismo nikako, zar vam nije rekao?
{110491}{110551}- Naleteli smo na nemaËku podmornicu.|- nemaËku podmornicu?
{110558}{110613}äta god da je bilo, uperilo je svetla|prema nama i osulo paljbu.
{110618}{110664}- Nisam Ëekao da saznam.|- Ja ne mislim...
{110666}{110719}Znate, ne moûete biti dovoljno|paûljivi ovih dana.
{110721}{110791}Mislim da niko ne moûe dati|logiËnije objaönjenje...
{110798}{110872}i odbiti nareenje patrolnog broda.
{110887}{110944}Da ne govorimo o pucanju|u njihov reflektor.
{110947}{110978}- Patrolni brod?|- Da.
{110980}{111021}To je to. Bio si u pravu Edi.
{111026}{111071}Dobar sam za noÊ, uvek sam bio.
{111074}{111150}Smeöno, stalno je ponavljao da je to|patrolni brod, a ja mu nisam verovao.
{111158}{111232}Ima jedna stvar koja mi nije jasna,|Kapt. Morgan.
{111244}{111268}Koja to?
{111273}{111357}Zaöto profesionalni ribar ide|u ribolov za svoje zadovoljstvo?
{111407}{111484}Da li ste ikada postavili neko pitanje?|Da li ste ikad priËali?
{111522}{111577}Ne, mislim da niste.|O Ëemu ste priËali?
{111582}{111675}Da li profesionalni ribar ide u ribolov|za svoje zadovoljstvo?
{111695}{111745}On i to radi samo ako mu se svia,|a to smo i mi, ili nismo?
{111750}{111798}Jeah, seti se Ki Vesta|kad smo poöli...
{111802}{111886}- »inilo se da neÊemo nigde stiÊi.|- Bio je Ëetvrti juli...
{111891}{111944}Upravo i priËam,|Ki Vest, Ëetvrti juli...
{111949}{111992}pre tri godine u 8:00. Tu sam bio.
{111997}{112047}- äta je sa vaöim putnicima?|- Bilo je 7:00.
{112052}{112107}IzgoreÊete ga sa tim rumom.
{112112}{112172}- äta je sa vaöa dva putnika?|- Kakva putnika?
{112177}{112220}One koje ste doveli iz Angilije.
{112224}{112275}On je Ëekao na keju kad smo se vratili.
{112280}{112323}Mislite da sam ih doveo na obalu|u svojim rukavima?
{112325}{112387}Mogao si da ih iskrcaö|bilo gde na naöoj obali.
{112392}{112426}Stvarno, mogao sam to uraditi.
{112428}{112515}- Da li bi $500 osveûilo vaöe pamÊenje?|- PamÊenje mi je u dosta dobrom stanju.
{112527}{112598}SeÊam se da ste vi onaj momak|koji mi je oduzeo pasoö i novac.
{112606}{112692}Da li bi vam se pamÊenje poboljöalo|ako vam vratim pasoö i novac?
{112697}{112752}Da li je tu ukljuËeno i $825|koje mi je Dûonson dugovao?
{112759}{112817}- äto da ne?|- I $500 koje sam malopre pomenuo?
{112833}{112886}To je povoljna prilika,|Kapetane Morgan.
{112891}{112958}Nije povoljno.|Ako su ti ljudi tako vaûni...
{112961}{113052}- Onda Êe ih biti teöko pronaÊi. - NeÊe|biti teöko za Ëoveka tvojih sposobnosti.
{113056}{113112}Razmislite, pa da Ëujem od vas.
{113404}{113452}- Jesi li Ëuo ovo?|- VeÊi deo.
{113457}{113498}SlatkoreËivi je otiöao priliËno ljut.
{113512}{113567}Kad se malo oladi,|onda Êe poËeti da razmiölja.
{113570}{113625}Misli da Êeö mu ih dovesti.
{113627}{113706}- Zar to nije ono o Ëemu ûeli da razmiölja?|- äta Êe se onda desiti?
{113713}{113769}- Joö nije pretresao tvoj hotel, da li je?|- Nije joö.
{113771}{113797}To je tvoj odgovor.
{113797}{113840}On ih ne ûeli, ali cela postavka.
{113845}{113900}- äta da radimo?|- Ne mi, nego ti.
{113905}{113980}Moraö uËiniti neöto sve dok se to druötvo|ne oporavi da bi moglo otiÊi.
{113984}{114032}Sve do tada, biÊeö verovatno siguran.
{114039}{114073}Joö bolje, oslobodi se svega ovoga.
{114078}{114121}- Donesi nam neki doruËak.|- Naravno.
{114126}{114193}- Mislila sam da ne ûeliö nikakav doruËak.|- Tad nisam ûeleo.
{114198}{114260}- O Ëemu priËaö, Edi?|- Neöto kontam.
{114265}{114358}Ono druötvo ne misli da sam pametan,|pa pokuöavaju da me napiju.
{114382}{114430}Oni me ne znaju, je li tako Heri?
{114502}{114550}Mislim da pokuöavaju|da neöto iöËaËkaju.
{114553}{114579}äta misliö da je to?
{114581}{114632}- Zar ne znaö?|- Nemam blage veze.
{114634}{114694}Dobro je öto su otiöli.|Dobio si ötucavicu.
{114701}{114756}Jesam li,Heri?|Jeah, nisam ni primetio.
{114759}{114823}- Bolje je da pijeö vodu.|- äta, vodu?
{114828}{114893}- Dobra ideja, mröavko.|- Ne, samo ne to.
{114898}{114951}- Dobro bi ti doölo.|- BiÊe mi dobro.
{114994}{115032}- Edi.|- Jeah, Heri?
{115032}{115087}Skloni se i budi öto dalje od policije.
{115092}{115159}Drugi put neÊe poverovati u priËu.
{115166}{115209}Kakvu priËu, Heri?
{115245}{115279}Samo ih se kloni.
{115624}{115754}Ovo je priËa o nesreÊnom Kinezu|koji je uhvaÊen u Hong Kongu
{115850}{115979}Izgubio je sva prava jer je|udario nogom po Budinom gongu.
{116001}{116082}Sada udara po klaviru|da bi skupio novac
{116125}{116183}za kartu u slobodan svet
{116200}{116257}Kaûe da mu je kuÊa u|Frisku, tamo öalju riûu.
{116276}{116358}Ali on je zapravo u Tenesiju.
{116375}{116432}Tako on kaûe.
{116475}{116605}Treba mi neko ko me voli,|da me odvede u San Francisko.
{116751}{116809}I da me tamo ukopa.
{116825}{116955}Traûim nekog da mi|pozajmi 50 dolara
{117000}{117058}Tad Êu napustiti Hong Kong.
{117075}{117204}Verujte mi da Êu ponovo|videti taj zaliv.
{117401}{117506}Ali kad sam pokuöao otiÊi,|nisu mi dozvolili da odem.
{117600}{117729}Treba mi neko ko me voli|da me odvede u San Francisko.
{117852}{117909}I da me tamo sahrani.
{118072}{118106}Videli ste negde Edija?
{118111}{118175}Ne, Mr. Morgan,|Nisam ga video celo popodne.
{118185}{118216}Gde je FrenËi?
{119127}{119199}Idem da radim. Dopada li ti se?
{119206}{119261}Ne moraö baö mnogo da pevaö|da bi pokazala odeÊu.
{119266}{119329}- Znaj, nekada me isteraö...|- Zato to i radim.
{119331}{119403}- Jesi li negde videla Edija?|- Ne, ne od podne, zaöto?
{119405}{119453}Napustio je brod|i nije se vratio nazad.
{119458}{119511}- Je li neöto ne valja?|- Ne znam.
{119525}{119585}Nemoj odmah da pogledaö,|ali tamo, za drugim stolom...
{119592}{119662}tamo je Ëovek s brkovima.|Mislim da me prati.
{119664}{119731}Pripazi krajiËkom oka na njega,|hoÊeö li? Silazim dole.
{119751}{119801}Ej, Heri. 'Ajde proöetaj okolo,|ona treba da peva.
{119806}{119854}- Odmah se vraÊam.|- Kaûi joj da je volim.
{119858}{119914}I ja bih samo kada bi htela.
{119926}{119988}Evo ostalih reËi pesme.|Kako se oseÊaö?
{119990}{120057}- Mogu li uzeti piÊe, Krikit.|- Naravno, doi.
{120108}{120170}- äta Êemo, mröavko?|- SkoË i sodu.
{120184}{120211}Isto.
{120475}{120525}- Dobro veËe.|- Dobro veËe, Kapt. Morgan.
{120530}{120592}- Kako se oseÊate?|- Mnogo bolje. Mnogo sam vam zahvalan.
{120597}{120654}Zaboravite.|Dozvolite mi da pogledam.
{120726}{120767}- Nema krvarenja.|- Ne.
{120805}{120849}- Da li ovo boli?|- Samo malo.
{120851}{120928}Nezgodno mi je samo kada jedem.|Trapav sam sa levom rukom.
{120933}{121024}GledaÊemo da vas sledeÊi put|pogode u drugu ruku.
{121028}{121069}Viöe vam nisam potreban.
{121108}{121139}FrenËi, odlazim.
{121141}{121172}- Kada?|- »im pronaem Edija.
{121177}{121213}- Je li vaö prijatelj nestao?|- Jeah.
{121215}{121237}äta se desilo?
{121242}{121297}Uopöte ne znam,|napustio je dok i nije se vratio nazad.
{121299}{121367}- ObiËno radi ono öta mu kaûem.|- éao mi je ako se neöto desilo.
{121371}{121441}- Ne ûelim da znam sve dokle ga ne naem.|- Zar ga ne moûete ostaviti ovde?
{121446}{121486}Mislim da se to Ediju ne bi svidelo.
{121491}{121530}FrenËi, Ëim budem otiöao...
{121534}{121589}Renar Êe upasti ovde|i prevrnuÊe sve naopaËke...
{121594}{121669}pa treba da smisliö gde|i kako Êeö smestiti ove ljude.
{121671}{121755}- Zar ne bi bilo najbolje da poemo s vama?|- Zaöto ûelite da idete?
{121760}{121848}Joö pokuöavam da se izvuËem iz meteûa|u koji sam upao, dovodeÊi vas ovde.
{121853}{121894}Zaöto ste doöli ovde u prve redove?
{121899}{121966}Znam zaöto je ona doöla,|ona mi je rekla, ali zaöto vi?
{121971}{122014}Da li ste Ëuli za Pjera Viljemara?
{122016}{122107}Pjer Viljemar? Jeah, Ëitao sam izveötaje.|On je bio baö neko.
{122119}{122170}- Viöi ga je uhvatio. Mrtav je, zar ne?|- Ne.
{122175}{122239}On je na –avoljem ostrvu.|Poslali su me ovde da ga izbavim...
{122244}{122287}i da ga dovedem na Martinik.
{122292}{122359}On je Ëovek kome ugnjeteni|i poniûeni narod...
{122364}{122405}moûe verovati i slediti ga.
{122465}{122522}Pa kako to mislite da ga izbavite?
{122546}{122604}Nemojte mnogo razmiöljati o meni,|Kapt. Morgan.
{122606}{122685}»udite se zaöto su izabrali mene|za ovu misiju.
{122692}{122726}I ja se takoe Ëudim.
{122736}{122795}Kao öto znate,|nisam baö mnogo hrabar Ëovek.
{122843}{122901}Baö obratno, uvek sam se plaöio.
{122937}{123002}éeleo bih da mogu bar malo|pozajmiti vaöe naravi, kapetane.
{123004}{123059}Kada se susretnete sa opasnosti|nikad ne mislite ni o Ëemu...
{123064}{123112}izuzev, kako da to zaobiete.
{123122}{123203}ReË, poraz za vas ne postoji, dok ja...
{123261}{123330}ja uvek mislim, "öta ako promaöim"...
{123361}{123402}i zato sam uplaöen.
{123409}{123481}Jeah, lako se mogu uveriti|koliko je potrebno hrabrosti...
{123486}{123539}da se izbavi veliki patriota|sa –avoljeg ostrva.
{123544}{123649}Ali iz profesionalnih razloga voleo bih|znati kako ste to mislili uraditi.
{123656}{123692}Naöli bismo naËin.
{123702}{123769}Moûda ne bi uspelo, ali ako uspe...
{123776}{123850}i ja sam joö ûiv...
{123882}{123963}PokuöaÊu da moje informacije,|moju misiju predam nekome drugom.
{123982}{124040}Moûda boljem Ëoveku|koji neÊe omanuti.
{124049}{124102}Uvek postoji neko drugi.
{124150}{124203}to je greöka,|Nemci uvek to rade...
{124208}{124253}sa ljudima koje pokuöavaju da uniöte.
{124282}{124347}Uvek Êe tamo biti neko drugi.
{124421}{124481}Stvarno, planirali smo|da sve uradimo odavde.
{124488}{124565}Ali za to, zbog moje nespretnosti,|to je bilo nemoguÊe.
{124582}{124642}I to je razlog da i mi|moramo poÊi sa vama.
{124651}{124721}Ne bih vas mogao izvesti na pristaniöte,|tamo je Ëovek koji nadgleda...
{124728}{124776}jedan se nalazi gore,|nalaze se svuda.
{124781}{124853}- Kako da vas provedem ulicama?|- Kako Êete vi iÊi?
{124857}{124896}Oni motre na mene da bi uhvatili vas.
{124901}{124975}Sve dotle, dokle vas ne povedem,|mogu nekako da doem do broda.
{124980}{125044}Tamo Êe biti magla,|a posle ponoÊi poËeÊe plima.
{125049}{125104}mogu preseÊi vezove|i polako ploviti pored lukobrana...
{125109}{125148}pre nego pokrenem motore.
{125169}{125222}Joö uvek imam mnogo nevolja,|Ëak i bez vas.
{125224}{125277}- Ali, Heri...|- Kapt. Morgan je upravu.
{125323}{125366}To joö nije njegova borba.
{125387}{125488}Nadam se da Êe jednog dana biti,|zato jer je bio s nama.
{125529}{125572}VeÊ ste puno uradili za nas.
{125577}{125665}éerar mi je rekao da ste odbili|Renarovu ponudu da nas predate.
{125692}{125742}Kako znate da to neÊu ponovo uraditi?
{125754}{125812}Ima mnogo stvari|koje Ëovek moûe uËiniti...
{125821}{125924}Vi ne biste nikada izdali za novac.
{126003}{126032}SreÊno.
{126056}{126109}- Nadam se da Êete naÊi vaöeg prijatelja.|- Hvala.
{126114}{126152}Dovienja, i hvala.
{126277}{126346}FrenËi, moram da raspravim neke|stvari s tobom, pre nego se izgubim.
{126354}{126411}BiÊu gore za nekoliko trenutaka, Heri.
{126519}{126550}Ima li ikakvog traga o Ediju?
{126574}{126644}- Vaöi prijatelji i dalje sede|za onim stolom. - Znam.
{126651}{126713}- äta je, Stiv?|- Ne bih znao.
{126716}{126775}Mislim da Êe ova situacija eksplodirati,|suviöe je mirno.
{126778}{126831}- äta Êemo da radimo?|- Odlazimo veËeras...
{126833}{126871}Ëim naem Edija.
{126874}{126948}Napuötamo svo troje za naöe dobro.
{126974}{127027}»ekaj, ûelim da znam|u öta se upuötamo.
{127032}{127078}Grubo reËeno, pukao sam.|Ako odemo...
{127082}{127145}imaÊemo nekoliko stotina galona nafte,|i nekoliko franaka.
{127147}{127202}Taman toliko|da nas moûda doveze do Porto Prinsa.
{127205}{127243}Nikad nisam bila tamo.
{127255}{127339}Ne znam kada Êeö se vratiti kuÊi.|Dugo Êe potrajati.
{127351}{127413}Moûda Êe biti za uvek,|da li se plaöiö toga?
{127430}{127514}Teöko mi je da se odluËim, Stiv.|Sve öto treba da uradiö je da me pozoveö.
{127550}{127600}Koliko ti treba vremena|da se spakujeö?
{127629}{127696}Ovde ima puno ljudi, poötedi ih.
{127773}{127847}NeÊemo iÊi bar do ponoÊi.|Hajde na posao.
{127967}{128039}- Je li sve spremno, mröavko?|- Naravno, ali nemoj da bude tuûno, Krikit.
{128044}{128121}- Ne oseÊam se tako.|- Nemoj to gledati na taj naËin. Idemo.
{128123}{128159}Poviöena nota, momci.
{128387}{128471}moûda Êe se tako dogoditi,|moûda pripadamo jedno drugome.
{128588}{128648}Ali ko zna.
{128713}{128821}Moûda samo za jedan dan.|Ljubav je prevrtljiva.
{128912}{128972}Ali ko zna.
{129012}{129144}Ko zna zaöto aprilski|vetriÊ utihne.
{129164}{129295}Zaöto se zvezde sakriju|kad kiöi?
{129413}{129473}Ljubav dolazi, opËinjava te.
{129538}{129621}HoÊe li ti zapevati?|HoÊe li ti reÊi zbogom?
{129698}{129725}Ko zna.
{129739}{129799}Moûda Êeö biti moj.
{129837}{129897}Moûda Êu ostati u tvom naruËju.
{129962}{130094}Je li to ono öto sam Ëekala?
{130214}{130346}Nadam se u duöi da je tako.|Iako ne znamo mnogo.
{130636}{130676}Madam de Birsak ûeli da vas vidi.
{130681}{130744}- Vidi, FrenËi, sve je gotovo.|- Gore je u vaöoj sobi.
{130748}{130775}Zaöto si je doveo...
{130777}{130832}Molim vas, Heri, to je sve öto traûim.
{130866}{130899}Hvala, Heri.
{131012}{131060}Niste smeli da dolazite,|suviöe je riskantno.
{131065}{131094}Rekao sam vam da vas neÊu povesti.
{131098}{131182}Nisam doöla zbog toga.|VeÊ ste dosta uËinili za nas...
{131187}{131247}ali ima joö neöto,|öto bih volela da vas zamolim.
{131254}{131295}éelela bi da uzmete ovo.
{131297}{131360}Pripadalo je mojoj baki,|a pre toga njezinoj majci.
{131367}{131453}Dala ga je meni kada sam se udala.|Ovo mi je sve öto mi je ostalo.
{131456}{131535}éelim da to nosite odavde|i saËuvate dok mi mognemo...
{131540}{131585}Pretpostavimo|da me uhvate pre nego odemo?
{131587}{131659}Onda ga bace preko palube,|u najmanju ruku, ne ûelim ga.
{131669}{131717}Pretpostavimo da nikada|ne doete po njega?
{131722}{131789}Onda neka to bude mala plata|za ono öto ste uËinili za nas.
{131794}{131825}Molim vas, hoÊete li?
{131842}{131904}Stiv, Renar je upravo uöao,|i ide gore.
{131909}{131957}- Da li te je video?|- Mislim da nije.
{132002}{132089}Uredu, uzmite ovo,|obadve idite tamo i budite tihe.
{132096}{132153}»im ih se otarasim,|vodi je u skloniöte.
{132158}{132182}Uredu.
{132434}{132477}Dobro veËe, Moûemo li uÊi?
{132599}{132630}Dobro veËe.
{132652}{132690}Ne, nikada ih ne nosim.
{132736}{132760}äta ste naumili?
{132765}{132822}Skloniöte dvoje ljudi|za kojima tragamo.
{132827}{132865}- Joö ih niste pronaöli?|- Ne.
{132868}{132952}Joö od jutros, osnovu naöih izvora,|saznali smo njihova imena...
{132959}{133043}Gospodin i gospoa Birsak.|Je li tako ili nije?
{133045}{133117}- Kako ja da znam?|- Mislio sam moûda...
{133187}{133215}Vrlo prijatan miris.
{133259}{133304}- Svia vam se?|- Da.
{133335}{133400}I meno. Uredu, mröavko, hajde izai.
{133501}{133563}- VeÊ ste sreli momke.|- Dobro veËe.
{133570}{133657}Gospoice. Sada smo svi ovde.
{133673}{133769}Izuzev vaöeg prijatelja, Mr. Edija,|on voli da ga tako oslovljavamo.
{133889}{133925}- I tako, vi ste ga uhvatili.|- Da.
{133935}{133983}Joö nam fale samo dve nestale osobe.
{133983}{134014}äta nameravate uraditi s njim?
{134016}{134098}Ako nam vi ne date informacije|koje ûelimo, moûda Êe on.
{134115}{134174}Pre nego napravimo greöku|i damo mu piÊe...
{134179}{134213}ovaj put Êemo se suzdrûati.
{134215}{134261}- Znate li kako Êe to delovati na njega?|- Mislim da znam.
{134266}{134345}- NeÊe moÊi izdrûati i pokleknuÊe.|- Moûete to lako spreËiti.
{134352}{134383}Jeah, mogu.
{134424}{134460}Imate li cigaretu?
{134503}{134582}- Moûete li ga naterati da govori?|- Ako bude potrebno.
{134647}{134700}Pronai ötogod u ladici, mröavko.
{134733}{134829}Moûete Mr. Ediju uötedeti mnogo,|da kaûemo, neprijatnosti?
{134899}{134980}A meni puno vremena,|ako nam kaûete gde se nalaze ti ljudi.
{135162}{135205}Koliko mi dajete vremena?
{135205}{135244}Viöe nego ga imam sada?
{135246}{135330}Mislim da sada ne moram|viöe platiti nikome za bilo öta.
{135419}{135455}Moûda ste upravu.
{135512}{135565}- Nisam dobio öibicu.|- Ne mrdajte...
{135606}{135661}Uredu, hajde, podignite ga. Hajde.
{135687}{135738}Potegnite piötolje, samo napred.
{135743}{135807}Haje, izvucite ih. Probajte ih!
{135870}{135920}- Svakako Êete ih upotrebiti.|- Zar neÊete.
{135922}{135968}Dovoljno dugo vremena|me jurite okolo.
{135973}{136057}HoÊete da nasankate Edija, budale.|Nalivate ga rumom da nikada...
{136059}{136121}Okolo öamarate devojke.|Tako je, samo to radite!
{136148}{136191}Vaöem momku treba druötvo.
{136373}{136455}Pogledajte, zar nije Ëudno?
{136531}{136577}Kako ste blizu priöli.
{136618}{136668}Ajde, FrenËi, uzmi im piötolje.
{136944}{136975}Evo ih, tu su.
{137114}{137183}A sada, pravo na kauË.|Ajde, priite i okrenite se.
{137277}{137306}Sedite.
{137397}{137440}Uredu je, izaite.
{137512}{137567}To je jedna od njihovih.|Drugi je u skloniötu.
{137572}{137605}Odvedi je dole, treba da pomogne.
{137610}{137673}Pripremi ih da odu na brod,|a onda se vrati ovamo.
{137677}{137730}Mröavko, ti se pakuj.|Odlazimo Ëim dobijemo Edija.
{137735}{137759}Uredu, Stiv.
{137761}{137807}- Samo, kako to vi mislite...|- Zaveûi.
{137812}{137879}éelite da znate kako Êu ga izbaviti?
{137898}{137951}BiÊete porazbijani kao ove krhotine.
{137956}{137989}U hodniku je telefon.
{137991}{138049}Nekome Êete reÊi da ga puste|i da ga poöalju ovamo.
{138054}{138099}Da, vi, jedan od vas.
{138159}{138205}Nisam zaboravio ni tebe.
{138255}{138313}Obadvojica Êete biti udarani,|sve dok jedan ne uzme telefon.
{138318}{138370}Tako Êe jedan od vas biti|premlaÊen za niöta.
{138375}{138464}Nije me briga ko Êe to biti.|PoËeÊu od tebe.
{138517}{138574}Odmah Êete ga pustiti.
{138620}{138706}- Reci im da Êeö objasniti kasnije.|- ObjasniÊu kasnije.
{138720}{138807}Reci im da ga poöalju nazad u hotel i da ne|preduzimaju niöta dok se ti ne vratiö tamo.
{138811}{138910}Poöaljite ga nazad u hotel i da ne|preduzimate niöta dok ne Ëujete od nas.
{139003}{139082}A sada, ulazi unutra. Treba da popunite|nekoliko propusnica za ulaz u luku.
{139159}{139217}A sada Pol i Madam de Birsak.
{139303}{139351}FrenËi, s tobom Êe biti sve uredu.
{139593}{139653}- Svi su sada vaöi.|- Hvala, Mr. Morgan.
{139682}{139711}Oni su svi spremni.
{139715}{139766}Ovo Êe im omoguÊiti da prou straûare|i da se ukrcaju na brod.
{139770}{139806}Gde ih vodite?
{139806}{139847}- Moûda na –avolje ostrvo.|- äta?
{139852}{139912}Moûda da izbavimo Viljemara,|zar to nije ono öto ste ûeleli?
{139917}{139991}Izuzetno mnogo.|Zaöto to radite, Heri?
{140032}{140068}Ja ne znam.
{140080}{140152}Moûda zato öto vas volim,|a moûda zato öto ne volim njih.
{140157}{140214}Drago mi je öto ste jedan|od naöih, Heri.
{140219}{140260}Bez ljubljenja, FrenËi.
{140284}{140367}- Pazite na ove momke, vodite raËuna.|- ImaÊete dovoljno vremena.
{140372}{140435}Ako ih pustite,|vratiÊe se ponovo i zapaliti ovo mesto.
{140439}{140487}Pustite ih, biÊe samo mala pucnjava.
{140492}{140588}Kada se Viljemar vrati, onda Êe doÊi|naöe vreme. PoËeÊemo neöto viöe.
{140593}{140629}SreöÊemo se na brodu.
{140658}{140694}Trenutak, molim vas.
{140698}{140749}Uredu je, pustite ih da prou.
{140830}{140897}- Kako si Heri? jeli sve uredu?|- Sad je sve uredu.
{140902}{140962}Drago ti je da me vidiö.|Znaö, neöto Ëudno...
{140976}{141036}Ne znam öta su hteli,|ali nisu hteli da mi daju...
{141041}{141113}UzeÊu jednu dole u brodu.|Odlazimo, Edi.
{141118}{141159}- Spremna si, mröavko?|- Za koji trenutak, Stiv.
{141163}{141197}Zatvori to, hoÊeö li?
{141197}{141279}- Reci, öta je ovo,ide li ona sa nama?|- Jeah, tako izgleda.
{141286}{141334}Heri, misliö... äta ako dobije...
{141351}{141427}- Ko ste vi?|- Da li vas je nekada ubola mrtva pËela?
{141461}{141490}- A vas?|- Jeah.
{141492}{141535}Morate biti paûljivi s mrtvim pËelama.
{141538}{141585}Mogu vas gadno ubosti|isto kao da su ûive.
{141588}{141653}NaroËito ako su se naljutile|onda kad su ubijene.
{141657}{141698}»ini mi se kao da priËam|sam sa sobom.
{141703}{141763}Na taj naËin su me ubole|bar stotinu puta.
{141787}{141876}- Zaöto im niste uzvratili ubod?|- I bih. Samo nisam imala ûaoku.
{141928}{142012}Setio sam vas se. Dobro ste. Ona|moûe doÊi, sve je uredu öto se tiËe mene.
{142017}{142055}Ima da se brinem o obadvoma.
{142060}{142130}Dobro je, Edi.|PoËni da uzimaö torbe.
{142135}{142168}Ajde, mröavko.
{142626}{142679}Imam li vremena|da se pozdravim sa Krikitom?
{142684}{142717}Naravno, samo napred.
{142914}{142950}- Doöla sam da se pozdravimo.|- äta?
{142952}{143017}Odlazimo sada. Hvala za sve.
{143022}{143101}- Hej, mröavko. Jesi li sreÊna?|- äta ti misliö?
{143125}{143209}Preveo i obradio:|Mihailo TeöeviÊ
{143234}{144734}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3u7pu|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
