{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{4231}{4282}Zove se Kyungjin.
{4294}{4327}Kyungjin Yeo.
{4344}{4423}Svaki put kad joj spomenem|ime, obuzme me Ëudan oseÊaj.
{4447}{4550}Ima neöto u njoj.
{4586}{4711}Nema Ëoveka na svetu koji|ne sanja da pobegne s curom koju voli.
{4728}{4807}Ja jesam i,|jednog dana, pobeÊemo zajedno.
{4845}{4881}Ali, moja nada...
{4907}{4977}Da poËnem od poËetka.
{5066}{5121}Lopov! UpomoÊ!
{5126}{5193}Ima moju torbicu!
{5198}{5255}Neka mi neko pomogne!
{5699}{5725}Ups! Izvinjavam se!
{5795}{5828}Stoj! Stani.
{5843}{5898}- Stani!|- Nisam ja! On je! Tamo!
{5905}{5936}Eno ga tamo!
{6034}{6133}Nisam ja lopov!
{6157}{6205}Ja sam pristojan graanin.
{6368}{6411}Beûi. Vidite!
{6483}{6521}Imate pogreönog tipa!
{6559}{6600}ZaËepi! Svaki kriminalac|to kaûe.
{6662}{6775}Nisam ja, zaboga!
{6900}{6993}Imate pravo da Êutite, ali|ako neÊete, onda Êu Vas ja uöutkati.
{7005}{7070}Sve öto kaûete moûe|da se iskoristi protiv Vas na sudu.
{7192}{7240}Moûete da se|konsultujete s odvetnikom,
{7255}{7331}ali ako ste övorc,|drûava Êe Vam ga nabaviti,
{7336}{7382}öto, usput, ne verujem|da Êe Vam pomoÊi.
{7420}{7468}Gospodine, uhvatila|sam ga golim rukama.
{7518}{7554}PolicajËe Yeo, niste|li danas osloboeni duûnosti?
{7557}{7610}Jesam, ali ne i kad|je u pitanju zloËin, gospodine.
{7629}{7698}Gospoo, ovaj Ëovek Vam|je uzeo torbicu? Uhvatila sam ga.
{7732}{7782}Gospoo, znate da to nisam ja.
{7799}{7883}»uo sam kako vriöti|pa sam potrËao za tipom.
{7885}{7921}Hej, zaveûi!
{7921}{7952}Sigurna si da nisi|zafrknula?
{7974}{8046}- Hajde, ne verujeö mi?|- Pa...
{8115}{8147}Identifikacija.
{8154}{8180}U zadnjem dûepu|mojih hlaËa.
{8266}{8300}Ne izmiöljaj!
{8437}{8482}- Zanimanje?|- UËitelj sam.
{8497}{8561}Nastavnik fizike u Sunik|Girls High School! Trebao sam poËeti u ponedeljak.
{8590}{8629}Ne zajebavaj se sa mnom.
{8638}{8686}Mogu ti upropastiti ûivot|zbog toga, shvaÊaö?
{8691}{8734}Mogu Vam dati dobar opis|kako Ëovek izgleda.
{8746}{8811}Plava koöulja i|crne hlaËe.
{8828}{8902}KovrËava kosa,|nauönica u uvu,
{8911}{9000}male oËi, vrat,
{9015}{9077}dugaËak nos,|koûa mu vuËe na crveno
{9082}{9182}i... nosio je cipele napravljene|od gume sa zlatnim pertlama.
{9233}{9305}SeÊaö se svega toga?
{9321}{9410}Mislim da odajeö partnera|da spasiö svoje dupe.
{9417}{9473}- Mogu nacrtati njegovu sliku...|- Tiöina!
{9484}{9597}- Znam da suraujeö s njim.|- Pa... Ne verujem da je on...
{9607}{9648}Vidiö? Nisam!
{9657}{9719}O Ëemu priËate?|Ja sam uzoran graanin.
{9751}{9779}Doi ovamo!
{9904}{9930}Nasmeöi se!
{10014}{10043}Gospodine, izgledaju|sliËno, zar ne?
{10067}{10103}Mislim da izgledaju.
{10120}{10146}Pa...
{10161}{10206}O Ëemu priËaö?|Uopöte ga ne volim.
{10213}{10264}Zaveûi i odvuci|guzicu tamo.
{10326}{10362}Miriöi kao kriminalac.
{10372}{10429}Kakav miris!
{10448}{10480}Moûe Ëuti sve!
{10487}{10532}Nacrtaj facu|od lopova.
{10554}{10599}- Ovo...|- Da ti pomognem.
{10676}{10767}Nikad nisam lagao.|Ni jednom.
{11184}{11232}Sigurno sliËe.
{11479}{11566}Nisi loö slikar.
{11721}{11748}Gotovo.
{11820}{11863}- Nacrtaj i mene!|- Nema öanse!
{12520}{12549}Ne!
{12563}{12604}Naöao sam ovo ovde|i vratiÊu je gospoi.
{12755}{12812}Svo vreme sam|bila u pravu.
{12822}{12856}Ne, nisam to uËinio!
{12889}{12927}Uhapöen si!
{12942}{13023}Joö jednom.|Jedan... dva... tri...
{13143}{13210}- Da li je to on?|- Da, sam je.
{13318}{13364}Idem odavde.
{13520}{13599}Gde Êeö?
{13714}{13755}Mogla bi reÊi|da ti je ûao.
{13786}{13851}ReË "ûao" mi|nije u reËniku.
{13872}{13927}Jedino Êeö me Ëuti da govorim|ûao mi je ako svoje ime promenim u éao Mi Je.
{13939}{13994}Onda Êeö me|Ëuti kako kaûem ûao dok te zovem.
{14601}{14627}Tako si zgodna!
{14632}{14690}Tu ste da nadgledate|mlade u diskreciji?
{14709}{14771}- Da.|- Kasnite.
{14776}{14822}Otiöli su.
{14850}{14898}- Da idem sam?|- Ne.
{14910}{14980}SaËekajte. Vaö partner|bi trebao biti tu za minut.
{15222}{15272}- Skidaj ruke!|- ZaËepi!
{15294}{15332}Kako policajac moûe da tuËe|nevine graane kao mene?
{15332}{15414}Zaöto ne?|äta Êeö uraditi u vezi toga?
{15495}{15548}äta radiö ovde?|Neöto muljaö?
{15630}{15692}Hej, ti!|Doi i sedi ovde.
{15771}{15807}Ima mnogo delikvenata|u tvojoj ökoli?
{15850}{15884}Ne znam, joö|sam nov tamo.
{15896}{15932}Drogiraju se?
{16040}{16085}Rekao sam da|ne znam.
{16121}{16157}Njam! Da jedemo.
{16325}{16390}Mnogo ökolaraca uzima|ekstazi.
{16409}{16478}TuËe i kompjutersko|hakiranje su problem,
{16490}{16569}ali najgori su oni koji su|organizovali ökolske bande da uzimaju tui novac.
{16591}{16658}Trebali bi smo ih smrviti i dati|im lekciju koju neÊe brzo zaboraviti.
{16668}{16737}Kako stara poslovica glasi:|"Samo proklet vidi proklete."
{16747}{16776}äta?!
{16802}{16831} Ne, niöta.
{16864}{16893}Ti plaÊaö!
{17037}{17066}Imam samo 100 dolara.
{17083}{17123}UzeÊu dva.|SaËekaj malo.
{17529}{17579}Hej, deËki! Doite ovamo.
{18205}{18233}Ti to bacaö na mene?
{18238}{18272}Vi ste srednjoökolci?
{18346}{18372}Podigni.
{18387}{18413}Zaöto bih to uradio?
{18430}{18456}PlatiÊu.
{18461}{18550}Ne ûeliö me uzrujati, mali.|Digni to.
{18555}{18588}- Nema öanse.|- Smesta!
{18593}{18651}äta ti je, sestro?
{18667}{18749}Imaö PMS? Ili öta?|UËini si uslugu i ostavi nas na miru.
{18917}{18943}Pokupi je, smesta!
{18955}{19032}Hajde, kurvo,|da te vidimo.
{19190}{19226}Hajde, skuleriöi se.
{19243}{19291}Ne ûeliö se meöati|s ovom decom.
{19303}{19372}NazvaÊemo ökolu|i dobiÊe svoje.
{20084}{20128}Propalice.|Dolazi ovamo!
{20156}{20197}- Skini se s mene.|- Hajde!
{20211}{20247}Idemo!
{20458}{20514}Kurvo!
{20526}{20569}- Pokupi je!|- ZaûaliÊeö zbog ovoga.
{20590}{20621}Pokupi je!
{20727}{20772}Tata!
{21427}{21458}Ide dilanje drogom.
{21473}{21499}Drogom?
{21533}{21583}Levo je diler.
{21590}{21686}Ako ga pratimo, mogli|bi smo da uhvatimo celi drogeraöki krug. Idemo.
{21703}{21734}Nema öanse!
{21736}{21825}Ovde smo da nadgledamo|studente, ne da suzbijamo drogu!
{21839}{21895}Oni prodaju drogu i studentima.
{21911}{22002}Ostavimo to DEA. NazvaÊemo|stanicu, u redu? Idemo odavde.
{22012}{22050}Ne, otiÊe dok DEA ne|doe ovde.
{22070}{22113}Dobro. Ti idi za njim.|Nema öanse da idem s tobom.
{22305}{22353}Pusti me!
{22909}{22969}Nisam zatvorenik!
{22990}{23014}Molim te!
{23019}{23069}Znaö öta? äto se viöe|mrdaö, sve je tanje...
{23079}{23115}- Daj mi kljuË! Odmah!|- Nemam ga.
{23120}{23187}- Znam da imaö.|- Ne pipaj me, perveznjaku!
{23213}{23240}Idemo.
{24088}{24134}- Leûi.|- Ne zafrkavaj me!
{24146}{24175}Samo se sagni!
{24374}{24402}Diûi se.
{24530}{24558}A sad se ti spusti|na zemlju i lezi za mene.
{24575}{24649}äta misliö da sam,|merdevina? Stepenice?
{24683}{24724}Ne, ja sam uËitelj!
{24810}{24887}I ti ne smeö ovo da radiö!
{24971}{25014}Nema piöanja na|javnim mestima.
{25510}{25537}Jedan...
{25546}{25573}Dva...
{25577}{25604}Tri!
{26939}{27011}- Moramo uhvatiti öefa.|- Ne! Odlazi odavde!
{28574}{28598}Stoj!
{29061}{29102}Doavola! Ko si ti?
{29111}{29143}Ko si ti?
{29231}{29337}Ja sam tajni agent!
{29445}{29473}Tajni agent?|äta je to?
{29521}{29548}Nemam pojma!
{29555}{29641}Agent koji ide u|srce zla i pravi se da je kriminalac.
{29816}{29929}Ko si ti?|Uniötila si mi sluËaj!
{29936}{30018}Mogli smo ih uhvatiti.
{30118}{30229}Namestio sam celu stvar i ti|si morala da uletiö i zafrkneö sve!
{30236}{30332}To öto si uradila je kao|da dodajeö boju na Picassova dela!
{30397}{30442}Hajde!
{30883}{30924}- Odveûi me.|- OK.
{31013}{31085}Nestao je. Mora|da je isklizao iz dûepa.
{31113}{31142}Da vidimo!
{31209}{31255}Ne dodiruj me!
{31339}{31377}Boli!
{31569}{31636}Pridrûi mi ruku.|NeÊe boleti.
{31665}{31696}Nije bolelo.
{31744}{31773}Nemam kljuË.
{31833}{31905}Tamo se dogaa ogromna stvar|i pozvali su sve kao pojaËanje
{31914}{31965}i uzeli su sve|öto smo imali.
{32001}{32027}Usput...
{32060}{32130}Sredila si srednjoökolca|na ulici, zar ne?
{32152}{32178}Da, pa öta?
{32180}{32250}Njegov otac je Ëlan|Gradskog VeÊa.
{32259}{32351}Popizdeo je. DoÊe za minut.|Otiöao bih da sam ti.
{32389}{32454}Nisam uradila niöta loöe.
{32466}{32516}On je poznat kao Kum|noÊnih klubova.
{32528}{32619}On zarauje novac crvenim svetlima,|sve je to isto.
{32626}{32669}UËini si uslugu i drûi se|dalje dok se stvari ne smire.
{32681}{32725}Uötedio si mi vreme|predstavljajuÊi me njoj.
{32842}{32907}Jesi li ti istukla|mog sina, kurvo?
{32936}{32962}Da. Zaöto?
{33008}{33041}Ti se drûi podalje, öerife!
{33048}{33101}- Gospodine, da popriËamo malo...|- Nosi se.
{33118}{33228}Ko si ti da mi|tuËeö sina?
{33243}{33305}Policajac si, pa öta?|Koliko ûivota imaö?
{33334}{33370}Drûi oËi otvorene, kurvo!
{33384}{33463}DobiÊeö ti svoje!
{33523}{33593}äta ti misliö da radiö?|Smiri se. Da popriËamo...
{33600}{33645}Ko si sad ti, jebote?|Makni mi se s oËiju!
{33657}{33722}Reci mi. äta je uËinio moj sin?
{33732}{33784}Zoveö se policajcem,|a tuËeö decu?
{33796}{33899}Bio je veoma naduvan kasno u noÊ|pa sam ga nauËila kekciju.
{33904}{33967}äta je tu loöe?|Nisam niöta rekao da ne sme puöiti.
{33974}{34024}äta misliö da si ti, kurvo?
{34074}{34156}Ne zovi me kurvom,|lajavi skote!
{34194}{34281}äta?! Vidi ti tu kurvu!|Da joj slomim vrat?
{34285}{34384}Gospodine, daÊu joj ja lekciju.|Sad idite.
{34393}{34429}Otpusti je!
{34437}{34508}Ne radi niöta|osim öto troöi taksu!
{34518}{34578}»uvaj lea, kurvo!
{34592}{34645}Momci, zapamtite njeno lice. Znate|öta trebate uraditi ako naletite na ulici na nju.
{34652}{34739}- Dobro?|- Da, gospodine!
{34779}{34863}Samo ti i ja.|äta kaûeö?
{34878}{34976}Kakva kurva! Zaöto bi prljao|ruke o kurve kao ti?
{34986}{35031}Ne zajebavaj se sa mnom,|smeÊe jedno!
{35048}{35103}Uplaöen si, pileÊi izmetu?
{35108}{35156}Jebena kurvo!
{35281}{35328}Bestraga!
{35350}{35432}Jebem ti!|Ne mogu trpiti ovo sranje.
{35441}{35511}äta si rekao, skote?
{35520}{35561}Odjebi!
{35671}{35760}Da, Ëlan si Gradskog|VeÊa. Pa öta?
{35770}{35844}To ne znaËi da moûeö da|istuËeö policajca, mamlaze!
{35849}{35918}Koji si ti kurac?
{35930}{36000}Ja?
{36029}{36127}Ja sam tu zbog ubistava,|primedbi i kraa!
{36136}{36168}éeliö videti|kako izgleda pakao?
{36256}{36319}Mogu ubiti joö jednog|prije elektriËne stolice!!!
{36333}{36412}Hajde, idemo!|Na kolena!
{36431}{36487}Rekao sam, na kolena!
{36494}{36592}StajaÊeö tu i gledati?|Uradi neöto!
{36602}{36733}Sad si zajebao stvar!|Na kolena!
{36849}{36928}Svi vi! Na kolena!
{36983}{37045}Dosta mi je ovog sveta|gde bogati pobegnu
{37076}{37110}s bilo kojim zloËinom!
{37129}{37211}Nemam öta izgubiti!|Na kolena!
{37292}{37330}Ponavljaj za mnom!
{37388}{37431}" éao mi je, policajËe."
{37450}{37505} éao mi je, policajËe.
{37522}{37558}Glasnije, zajebu!
{37565}{37611} éao mi je, policajËe!
{37616}{37712}- "NeÊu se petljati s tobom."|- NeÊu se petljati s tobom!
{37776}{37839}NauËi sina pravilima, u redu?
{37844}{37899}NauËi sina pravilima, u redu?
{37935}{37966}Ne to, glupo sranje!
{38023}{38081}BrojaÊu do tri.|HoÊu da svi odete.
{38131}{38194}Osim ako ûelite|da otegnete papke!
{38230}{38258}Jedan...
{38306}{38335}Pomeraj guzicu!
{38680}{38709}Izvinite. Izvinite.
{38769}{38846}Dobro glumim?
{39131}{39160}Stavi mi na jaknu.
{39810}{39877}Moûeö li ih oprati|prije nego öto se ja operem?
{42260}{42320}Proces da se to dovröi...
{42620}{42696}»ija je ovo uûina?
{42749}{42828}NiËija? Onda|mora da je od nastavnika.
{42862}{42888}Evo.
{43145}{43221}Dame, da vas malo|posavetujem kao policajac.
{43233}{43281}Ja sam policajac|Kyungjin Yeo.
{43308}{43353}Vaö posao je da uËite.
{43370}{43420}- TaËno?|- Da!
{43428}{43509}Zato se nemojte koristiti|viöom silom protiv studenata,
{43516}{43564}ne pijte alkohol i|ne puöite.
{43588}{43679}Hej! Kako se usuujete|jesti dok ja priËam?!
{43773}{43845}Ako vas vidim da se|ömucate posle ponoÊi,
{43850}{43907}gotovi ste. Razumete?
{43922}{43965}A vaö nastavnik,|Myungwoo Ko,
{43974}{44058}je veoma dobar Ëovek.|Zato ga nemojte muËiti.
{44073}{44178}I joö jedna stvar. On je|moj momak. Zato se nemojte peniti na njega.
{44310}{44341}I spavali smo zajedno.
{44401}{44439}äta ti je?|Beûi odavde!
{44552}{44607}Kakav prekrasna poema!|Ko je ovo napisao?
{44612}{44667}Nemoj mi reÊi da si ovo|napisala jer je predobro.
{45142}{45202}Znaö öta?
{45219}{45267}Mislim da ûeliö slugu,|ne momka, zar ne?
{45274}{45386}Momak bi trebao pomoÊi devojci|sa ovakvim stvarima.
{45437}{45468}Koji sprat?
{45478}{45511}Na vrhu.
{45835}{45883}- Stavi ih na sto.|- Dobro.
{46079}{46103}Imaö bliznakinju?
{46118}{46168}Ne, drugaËije je slika.
{46379}{46405}Bliznakinje ste?
{46439}{46494}- Koja misliö da sam ja?|- Ona desno.
{46504}{46547}Pogreöno! Ona levo.
{46573}{46662}- Vi ste blizanci! Ko je izaöao prvi?|- Moja sestra.
{46863}{46935}- Ne koristim crne kljuËeve.|- Zaöto?
{47079}{47177}Kako ti je setra?|Da li je sliËna tebi?
{47259}{47293}Poveûi me s tvojom|sestrom blizankom.
{47362}{47388}Nemoj, öalim se.
{47489}{47520}Mrtva je.
{47623}{47734}Toliko smo sliËile da nas|je malo ljudi razlikovalo.
{47789}{47890}Mama nas je poslala u|razliËite ökole da se drugi ne zbune.
{47966}{48060}Bila je kao crni kljuË,|a ja kao beli.
{48093}{48218}Ali, moja sestra se volela|igrati i ponekad bi smo zamenile uloge.
{49657}{49729}Pitala bi me da|budem ona ili...
{49745}{49817}Terala me je da radim|stvari koje nije volela raditi.
{50170}{50213}Mrzela sam je zbog toga.
{50515}{50613}Bio je to dan kad sam htela|uzeti sliku za godiönjak.
{50635}{50743}Imala sam takmiËenje|u sviranju klavira,
{50781}{50822}pa sam je pitala
{50875}{50915}da mi ga izvadi i...
{51018}{51107}Na putu do moje ökole|kao öto sam je i pitala,
{51150}{51201}bila je ubijena|u auto nesreÊi.
{51261}{51299}Trebala sam ja umreti.|Ona je umrla umesto mene.
{51393}{51462}Tako da nemamo zajedniËke|slike u godiönjaku.
{51560}{51608}Htela je biti policajac.
{51707}{51755}äta radiö kad|ti se svira klavir?
{51769}{51810}Sviram ga,
{51879}{51934}ali ne koristim crne note.
{52030}{52083}- Kakav si bio u ökoli?|- Ja?
{52109}{52167}Jedino seÊanje koje imam u|vezi ökolskih dana je odeÊa,
{52177}{52241}koju sam imao, sa probuöenim|rukavima jer sam pao s bicikla.
{52412}{52462}- To je ludo.|- Znam.
{52469}{52495}Idemo na posao.
{55464}{55524}- Ne kasnim?|- Samo sat vremena.
{55550}{55579}Stvarno?
{55624}{55658}Imam neöto za tebe.
{55663}{55708}Kao i ja.
{55780}{55826}Knjigu koju je napisao Chundeuk!
{55912}{55984}Reci njegovo pravo ime.|Ima sad preko 90 godina.
{56001}{56058}Stvarno?|Mislila sam da je mrtav.
{58665}{58705}Ovde S2.
{58724}{58811}Mi smo u komöiluku.
{59197}{59230}Ovde S2 izveötava.
{59233}{59331}Jedan paket je prikupljen,|drugi ide ka 103.
{59333}{59360}IzraËunajte taËku za presecanje.
{59396}{59449}- Stoj!|- Ostani dole!
{59638}{59688}- Nazovi pojaËanje!|- Pazi lea!
{59830}{59933}Jedan paket je prikupljen,|drugi ide ka 103.
{59938}{59998}Poöalji pojaËanje.
{60022}{60048}Da, ja sam.
{60060}{60156}Trljam guzicom koliko mogu,|a ti leûiö na podu?
{60161}{60194}Ne, ne leûim!
{60213}{60273}Ovde S2! Ovde smo!
{60276}{60374}Idi sporednom ulicom.|Poöalji pojaËanje!
{60388}{60417}Moram iÊi!|NazavaÊu te kasnije!
{62067}{62100}Ovde Êemo je ostaviti.
{62103}{62136}Da je ubijemo?
{62146}{62208}Zna kako izgledamo, ËoveËe.|Ubij je.
{62211}{62283}- Kako?|- Ti je sredi!
{62287}{62316}- äta?|- Rekao sam da je srediö!
{62321}{62381}Ne mogu.|Ti si za to zaduûen.
{62388}{62434}Ne, nije!
{62844}{62875}Ne!
{63028}{63067}äta je to bilo?
{63196}{63258}Kako si se tu naöao?
{63361}{63436}Ne! Nisi je trebao ubiti!
{63529}{63601}Zaöto?
{64361}{64412}Bestraga!|Imam takav smrdljiv dan!
{64414}{64500}- PosetiÊu te u zatvoru!|- Stoj tamo!
{64563}{64599}Kyungjin!
{64656}{64716}Kyungjin!
{64766}{64829}Kurvin jebaËu!|Izlazi!
{64862}{64898}Nemaö mesta da se sakrijeö.
{64968}{65006}äta radiö tu?
{65467}{65498}Da ti pomognem?
{65510}{65555}Ovde sam da vidim|Myungwoo Ko. Gde je?
{65565}{65632}Otiöao je. Nisi li|ga videla kako izlazi?
{65649}{65678}Ne... Svejedno, hvala.
{65793}{65826}Gad!
{67425}{67459}Gde si naöao|ovo sranje?
{67471}{67524}Pazi se,|ona je sad moja.
{67529}{67562}- Kupio si to?|- Da.
{67567}{67620}- Za koliko?|- Ne ûeliö znati.
{67624}{67682}Kad poËnu raspusti,|idem lutati zemljom.
{67689}{67771}- Bez plaÊa, samo prljave ceste.|- Stvarno? Povedi me sa sobom.
{67778}{67850}- Ja Êu uzeti slobodno vreme.|- Trebala bi ostati i hvatati loöe momke.
{67855}{67907}Loöi momci se|nalaze svuda.
{69216}{69281}Uradi to kao ja!|LiËiÊe ti kao da letiö.
{69399}{69468}Mislim da sam bio|vetar u proölom ûivotu.
{69540}{69586}éelim leteti|kao vetar.
{69706}{69761}Kad duva,|dok budem otiöao,
{69782}{69811}misli na mene.
{69821}{69873}Onda je ovaj vetar ti?
{69900}{69933}To su mi prijatelji.
{69964}{70000}Ako umrem,
{70017}{70060}ûelim biti vetar.
{71087}{71139}Hmmm...|Miris izgorelog drveÊa.
{71168}{71223}- Toliko dobro?|- Kladim se!
{71348}{71446}Znaö zaöto ljudi prekrste|prste kad obeÊavaju neöto.
{71499}{71528}Zaöto?
{71557}{71650}Jednom davno postojalo|je jedno veliko carstvo.
{71688}{71756}Princeza je bila tako lepa.
{71825}{71926}Ogledalce, ogledalce, ko je|najlepöa devojka na svetu?
{71978}{72026}Naravno, Vi, moja ekselencijo.
{72034}{72089}Govoriö mi istinu?
{72106}{72149}Ako laûeö,|nadrapaÊeö.
{72170}{72209}Nikad ne laûem.
{72216}{72271}Najlepöa si|dama na svetu.
{72424}{72480}Bila je tako lepa i mudra da su
{72492}{72597}prinËevi iz celog sveta dolazili|da je zaprose.
{72616}{72691}Pet zgodnih prinËeva je|uölo u finale.
{72712}{72825}Da vidi ko bi joj|najbolje odgovarao,
{72832}{72861}dala im je test.
{72882}{72976}Stavila je desnu ruku iza lea|i pokazala samo jedan prst
{72993}{73089}i prinËevi su morali|pogoditi koji je to prst bio.
{74139}{74208}To bi bio znak|da bi se udala za njega.
{74227}{74309}Uskoro su se venËali i|nisu mogli biti sreÊniji.
{74328}{74436}Ali opsada je poËela i|princ je morao otiÊi u rat.
{74472}{74568}ObeÊao joj je da|Êe se vratiti kuÊi ûiv
{74590}{74630}i da Êe prekrstiti|prste s njom.
{74983}{75067}Deset godina je proölo,|a on se nije vratio.
{75083}{75117}Nije znala da li|je ûiv ili mrtav.
{75155}{75246}I, poöto je bila|joö uvek lepa nakon toliko godina...
{75268}{75357}Iako su mnogi ljudi dolazili|u palaËu da je ponovo oûene,
{75393}{75515}ona je verovala da|Êe se vratiti on vratiti.
{75546}{75597}Ali doöla je do taËke|kad ih viöe nije mogla odbiti.
{75606}{75704}Pa je odluËila da se oûeni|s onim ko Êe joj prekrstiti prste.
{76229}{76335}Onda, jednog dana,|prljavi Ëovek joj se pojavio u palaËi.
{76359}{76412}Ljudi su ga pokuöali izbaciti,
{76426}{76544}ali ga je princeza pozvala|unutra govoreÊi svima da mu se pruûi prilika.
{76714}{76783}Taj prljavac je bio princ.
{77905}{77999}Istina je bila da je|princ poginuo na putu kuÊi.
{78025}{78126}Duhovi ostanu ovde samo|49 dana.
{78155}{78258}To je bio 49 dan|od kako je umro.
{78296}{78371}Ali morao se vratiti,|makar kao duh,
{78383}{78430}da ispuni obeÊanje koje|je dao ûeni.
{78534}{78613}Napokon, naöla je njegovo telo.
{78896}{78958}Sad sigurno razumeö öta|znaËe prekröteni prsti?
{78963}{78989}Naravno.
{79061}{79147}Mogu li te neöto pitati?
{79212}{79250}Moûeö li umreti posle mene
{79318}{79375}kao öto|je i princeza?
{79392}{79449}Zaöto bih?
{79457}{79505}Nemoj stavljati viöe drva.
{79517}{79567}HoÊeö da me spaliö|do smrti?
{79593}{79651}Soba je prevruÊa.
{81178}{81205}Da li jako boli?
{81214}{81322}Usne su ti debele|kao öupak od krave.
{81375}{81420}Zaboravi o ljubljenju.
{81428}{81492}Nakon svega öto si|mi uradila, joö neÊeö da se izviniö?
{81516}{81545}Kao öto sam rekla,
{81555}{81624}ako hoÊeö da me Ëujeö kako kaûem|izvini, moraÊeö promeniti ime u tu reË.
{81629}{81672}Dobro! Od sad se zovem|Izvini. Kaûi moje novo ime!
{81679}{81713}Zoveö se Myungwoo!
{81720}{81761}Promenio sam ga!
{81763}{81830}- Ne vredi se.|- Zaöto? Mogu promeniti me!
{81845}{81941}Dosta priËe i poËnite jesti!|éivcirate me!
{83525}{83554}Myungwoo!
{83576}{83602}Myungwoo!
{83621}{83655}Probudi se!
{87302}{87338}Myungwoo!
{87386}{87431}Diöi!
{87465}{87515}Diöi!
{87669}{87726}Diöi!
{87772}{87846}Idiote! NeÊeö mi umreti!
{87944}{88019}Molim te!
{88023}{88095}Molim te, probudi se!
{90040}{90133}Zaöto si me spasila?
{90150}{90191}Da ne moram umreti|za tobom.
{90737}{90785}Vratili smo se|normalnom ûivotu.
{90805}{90893}Ona je i dalje|lovila loöe momke.
{90989}{91076}Ovde je S2.|Putujem do "Jezera."
{91080}{91116}Poöaljite pojaËanje.|Odjava.
{91140}{91207}Onaj tip tamo je|Changsoo Shin.
{91210}{91255}Ne pomerajte se dok|ne stigne pojaËanje.
{91275}{91363}Kyungjin, preopasno je.|Drûimo se podalje od ovoga.
{91404}{91507}On je pobegao iz zatvora.
{91524}{91562}NeÊu da propustim|dobru priliku da dobijem unapreenje.
{93147}{93197}- Diûi ruke!|- Oruûje na sto, odmah!
{93231}{93279}Bacaj oruûje ili Êu|vas ubiti! Odmah!
{93670}{93713}Jesi li u redu?
{93943}{94037}Naöao sam neöto.|Ovo je fantastiËno!
{94056}{94101}Nalazim se u|centru kriminala.
{94111}{94147}Gde si?|PomoÊu ti.
{94166}{94197}Ne! Preopasno je!
{94413}{94473}Njen glas je|zvuËao nekako drugaËije tog dana.
{94499}{94578}Od te pesme,|shvatio sam gde je.
{95437}{95482}Bila je tvra nego ja,
{95485}{95607}a ponekad se Ëinila tako krhkom|i tankom. To me brinulo.
{95811}{95888}Kurvin sine!
{95967}{96041}Ta stoka ne zna|kako treba da se ponaöa.
{96216}{96254}Leûi!
{96571}{96602}Prestani puöiti.
{96643}{96672}Dobro.
{96756}{96815}Ne znaju koristiti piötolje?
{96892}{96919}Okreni auto!
{97026}{97070}- To je Changsoo Shin!|- äta?
{99578}{99606}Stoj!
{99671}{99697}Stoj!
{100163}{100234}Ne ûelim to|sranje na naöim rukama.
{100249}{100278}Odletimo odavde.
{100961}{101047}Ovde S2.
{101066}{101153}Ovo je podruËje 117! »ovek|je u tvornici iza VeËernjeg parka.
{101160}{101217}Trebam ambulantu ASAP.
{102057}{102129}Ovde S2.
{102145}{102220}Ovo je podruËje 117! »ovek|je u tvornici iza VeËernjeg parka.
{102248}{102330}Trebam ambulantu ASAP.
{102884}{102968}Nisam te spasila|u reci za niöta.
{103076}{103133}Ne moûeö umreti!|Hajde.
{103160}{103243}Reci mi da je ovo san.|Reci mi da je ovo san!
{103320}{103450}Ovde S2.
{103457}{103529}Ovo je podruËje 117! »ovek|je u tvornici iza VeËernjeg parka.
{103606}{103685}Trebam ambulantu ASAP.
{104238}{104332}Moûda sam trebao|umreti u toj reci.
{105008}{105080}Ne! äta to radiö?|Ne moûeö si to uraditi!
{105106}{105171}Pusti! Pusti me!|Pusti me da umrem!
{105303}{105423}Ubila sam ga.|I ja sam trebala umreti!
{106643}{106679}∆ao! Ovo je Myungwoo Ko.
{106691}{106794}Ili mi ne radi baterija|ili sam izvan podruËja.
{106811}{106864}Ostavite poruku posle signala.
{106878}{106907}NazvaÊu Vas öto prije.|Hvala.
{106917}{106967}Bip!
{106981}{107037}Mislim da ne postoji|niöta izvan podruËja.
{107128}{107154}Dolazi ovamo.
{107221}{107259}Dolazi odmah!
{107370}{107401}Ne, ne.
{107423}{107482}Ne. DoÊu ja k tebi, u redu?
{107511}{107542}Ja...
{107590}{107636}Bilo gde da si,|uskoro Êu biti s tobom.
{108144}{108173}Gice! Gice!
{108216}{108278}äta radite tamo?
{108324}{108367}äta vas briga.
{108432}{108509}I ne zovi me gica.|Mrzim to.
{108518}{108590}Pokuöavaö se ubiti?|SkoËiti s krova?
{108698}{108739}Kaûe da nije gica.
{108756}{108832}- Pitaj je za novac.|- Zaboravi. To je sramotno.
{108914}{108971}Gice... Ne, sestro.
{108986}{109043}Mi smo pobegli!
{109053}{109120}Daj nam malo novca,
{109146}{109209}i mi te neÊemo zaustaviti da skoËiö?|- äta?
{109259}{109285}Moûe 50$?
{109377}{109417}Jesi li pukao?
{109425}{109492}Ili nam daj|kreditne kartice.
{109496}{109544}Ako umreö, ne moraö|plaÊati raËune, zar ne?
{109549}{109592}Produûi.
{109604}{109648}Postajem besna.
{109705}{109755}- äta sad?|- Stvarno je pobesnila.
{109813}{109873}Ako mi hoÊeö neöto reÊi,|reci sad.
{109885}{109938}Nemoj mi traËarati|iza lea!
{109947}{109995}Zaöto nam ne daö malo|novca prije nego öto se dokrajËiö?
{110005}{110072}Ako skoËiö, pukniÊe ti|glava, utroba Êe ti izleteti napolje.
{110074}{110139}- U redu. 10$?|- Ili daj da te pojebemo.
{110146}{110197}Iskoristi telo prije|nego öto postane beskorisno.
{110206}{110264}- Daj da vodimo ljubav s tobom.|- Stoj tamo.
{110271}{110316}- Mrtav si!|- Pukla je.
{110319}{110369}Dolazi ovamo!
{110374}{110410}- Beûimo.|- Stoj!
{110458}{110499}Sad si gotov smrad!
{110527}{110566}Uhvati nas!
{110583}{110633}Vidim ti gaÊe!
{110635}{110688}- Da, vidim ih. Crne su.|- Ne nosi ih.
{110690}{110726}Zato je crno.
{110815}{110873}Sad si gotov!
{111316}{111371}VraÊajte guzice ovamo!
{111376}{111460}Da me pojebete?|Prije Êete umreti nego to doûiveti!
{111465}{111510}Samo smo gladni.
{111554}{111599}Nismo jeli niöta 3 dana.
{111616}{111669}- Govorim ti istinu!|- äta hoÊete?
{111705}{111774}- Kako misliö?|- Pica!
{111801}{111827}Pica!
{111947}{111973}Pogledaj je.
{111995}{112091}Ne mogu da verujem da se|htela ubiti prije minut.
{112098}{112122}Znam!
{112155}{112194}I ja gladujem 3 dana!
{112206}{112244}Trebam sd dobro jesti da|dobro izgledam kao duh.
{112251}{112299}Kakvo je to dobro?
{112314}{112376}Ako skoËiö s krova,|odleteÊe ti glava
{112381}{112431}i utroba ti izletiti kroz usta...
{112453}{112520}Hej, jedem!
{112541}{112609}Daj mi malo salate.|Bez hleba, dodataka.
{112618}{112657}Hej, ti.|NeÊu pasulj, u redu?
{112661}{112716}Zaöto ti stalno nareujeö?|Ti idi!
{112800}{112848}- Ne pojedi sve dok ne doem.|- U redu.
{112942}{112978}Joö jednu picu, molim!
{113074}{113124}Ovo je za tebe|da ideö kuÊi.
{113138}{113167}Idi kuÊi,|nemoj da lutaö.
{113179}{113234}NazvaÊu te da se uverim|da si kod kuÊe, u redu?
{113282}{113311}U redu, hvala.
{113325}{113412}Ne, ona treba da ti zahvali,|mi smo joj spasili ûivot.
{113436}{113472}- Da uzmem novac nazad?|- Ne!
{113501}{113527}Hvala!
{113637}{113671}Idite kuÊi!
{113685}{113733}- U redu?|- Nemoj se ubiti!
{116591}{116620}éao mi je.
{116677}{116730}To je izlaz?
{116747}{116783}∆ao!
{117296}{117346}Kad bude duvao vetar,|dok odem,
{117363}{117401}misli na vetar kao|da sam to ja.
{117706}{117780}Ako umrem, ûelim biti vetar.
{120542}{120578}Myungwoo, jesi li to ti?
{120595}{120626}Jesi li?
{120689}{120727}Vetar duva...|jesi li to ti?
{120763}{120808}Ili je samo vetar?
{120856}{120885}Gde si?|Reci mi, Myungwoo.
{120916}{120952}Reci mi.
{120976}{121003}Myungwoo!
{121094}{121166}Postao si vetar?
{121211}{121269}Postao si vetar?
{121338}{121384}Ne mogu da verujem.
{123451}{123525}Danas je dan|kad zauvek odlaziö.
{123657}{123719}49 dan!
{123892}{123949}Ali videÊu te prije|nego öto odeö.
{124014}{124048}Da!
{124429}{124484}Gice Park, stavite|tipa od juËe u Êeliju.
{124494}{124647}Uzmite taj sto...|KljuË je ovamo...
{124681}{124743}- Gde je detektiv Kim?|- Nemam pojma.
{124983}{125038}- Detektiv Kim?|- Ja?
{125059}{125103}Ne, ne ti. Youngho!
{125119}{125158}Ima mnogo Kim ovde.
{125199}{125230}Evo ga.
{125419}{125462}Youngho!
{125510}{125563}Ona ti je partner.
{125642}{125680}Dobro radite!
{125781}{125810}Zdravo!
{125894}{125927}Kako ste, gospodine?
{132192}{132238}Koji si sad ti? Gubi se!
{132252}{132298}Upozoravam te.|Ne prilazi.
{132327}{132367}- Kyungjin, stani!|- Upozoravam te.
{132372}{132401}Rekao sam da ne prilaziö!
{132847}{132885}Ako ûeliö da uradiö to,|onda uradi kako treba.
{133377}{133449}U redu, nazovi|me kad se pojavi.
{133521}{133612}Nikog drugog osim mene, shvaÊaö?
{133621}{133665}Moj je.
{133691}{133717}Ne boj se.
{133741}{133770}Changsoo Shin?
{133792}{133864}Moram iÊi! Kasnije!
{134221}{134276}- NeÊu viöe toliko juriti.|- Ne sada. Nagazi!
{135177}{135209}Stoj!
{135702}{135734}Stoj!
{135755}{135782}Upucaj ga!
{136115}{136153}Zovite pojaËanje|i ambulantu!
{136165}{136194}Budi oprezna!
{140855}{140886}Myungwoo...
{140934}{140960}Myungwoo...
{141085}{141126}Ti si, zar ne?
{141231}{141318}Kyungjin, ostani sa mnom.|Misli na neöto lepo..
{141330}{141385}Ne smeö mi umreti, devojko!
{141428}{141457}PriËaj s njom.
{141462}{141524}ZaplakaÊu.
{141545}{141579}Kyungjin, seÊaö se tog dana??
{141605}{141649}Bila i prava!
{141658}{141721}Ne smeö umreti zbog metka!
{141723}{141809}Ne smeö mi umreti!|Moram ti neöto priznati!
{141905}{141972}Kyungjin, ostani sa mnom.
{141982}{142059}Moram ti joö mnogo|stvari reÊi.
{142066}{142121}- Moram ti priznati neöto.|- Tiöe!
{142142}{142193}Rekao je da|moram priËati.
{142217}{142253}Kyungjin!
{142545}{142584}Proverite otkucaje srca!
{142596}{142624}BP je 60.
{142660}{142718}EKG je ukljuËen. Dajte joj ToatriËku|kardiovaskularnu kiselinu.
{142744}{142792}Disanje je stalo.
{142795}{142835}Spremite se za oûivljavanje.
{143010}{143054}300 dûula!|Spremni! Kreni!
{143090}{143135}Niöta! EKG se ne menja!
{143140}{143190}300 dûula!|Spremni! Kreni!
{143233}{143265}EP i BB!
{143279}{143327}360 dûula! Spremni! Kreni!
{143358}{143399}Niöta! EKG se ne menja!
{143406}{143452}300 dûula!|Spremni!
{144279}{144365}Kyungjin. Gotova ti je noÊna|smena. Idi kuÊi, u redu?
{144389}{144418}Dobro.
{144976}{145008}Myungwoo!
{145202}{145231}Myungwoo!
{145420}{145446}Myungwoo!
{146019}{146048}Myungwoo!
{146108}{146168}Ti si, zar ne?
{146365}{146403}éiv si.
{146576}{146621}Zaöto si beûao|od mene?
{146631}{146679}Ne trËiö dovoljno brzo.
{146732}{146770}Mogao sam ti pobeÊi
{146859}{146897}da sam imao viöe|nego jedno pluÊe.
{146943}{147010}Kako si mogao|iscenirati smrt?
{147038}{147125}Nisi pomislio koliko bi|me to povredilo?
{147132}{147173}Nisam ûeleo da me vidiö takvog.
{147192}{147228}O Ëemu priËaö?
{147237}{147307}- Volim te takvog kakav jesi!|- Ne, nisam isti Myungwoo.
{147350}{147384}I ti nisi...
{147446}{147472}Myungwoo!
{147480}{147513}Myungwoo je mrtav.
{147532}{147559}Pusti to.
{147597}{147662}- Mrtav je.|- Nije.
{147669}{147705}Ovde si! éiv,|ispred mojih oËiju.
{147707}{147746}Mrtav je!
{148089}{148115}Myungwoo!
{148604}{148633}EKG se vraÊa!
{148688}{148731}- Ima volju da preûivi.|- äta?
{148736}{148825}éeli ûiveti!|Proverite pluÊa!
{148827}{148853}Vratite inhalatore!
{148863}{148904}I pripremite tranfuziju|krvi!
{149259}{149350}Youngho... znam da je voliö|i ûeliö da to ona zna,
{149355}{149391}ali ti si oûenjen Ëovek.
{149417}{149455}Mislim da nije dobro|da joj kaûeö öta oseÊaö.
{149599}{149625}Osvestila si se.
{149661}{149724}Operacija je uspela|i dobro se oporavljaö.
{149817}{149848}Odspavaj malo.
{149968}{149997}Koji je danas datum?
{150011}{150038}Danas?
{150050}{150093}Zadnji dan u oktobru.
{150570}{150597}Myungwoo!
{150980}{151009}Myungwoo!
{155219}{155250}Myungwoo!
{155320}{155349}Myungwoo!
{155389}{155440}Myungwoo! Myungwoo!
{155485}{155540}Myungwoo! Myungwoo!
{158125}{158245}Neko mi je odgovorio|na ûelju!
{158780}{158816}Ja... vidim te!
{159681}{159712}Moram iÊi.
{159933}{159983}Drago mi je da te mogu|videti prije nego öto te zauvek ostavim.
{160091}{160165}Ne. Nemoj iÊi!
{160182}{160271}Ako moraö iÊi,|povedi me sa sobom!
{160285}{160312}Ne idi!
{160491}{160520}Ne...
{160547}{160602}Tvoje vreme nije zavröilo.
{160657}{160690}Imaö joö mnogo|dana da ûiviö.
{160698}{160731}Ne!
{160750}{160782}Ne!
{160839}{160885}Ne saûaljevaj me.
{160969}{161005}Moûda se opet sretnemo.
{161045}{161074}Moûeö to osetiti,|siguran sam.
{161170}{161223}Kad se naemo kasnije,
{161273}{161321}reci mi neöto smeöno|i sreÊno
{161362}{161422}öto si okusila u ovom ûivotu.
{161443}{161544}A kad osetiö da|öaputam vetru,
{161597}{161705}naÊeö nekog Ëiji|je duh kao moj.
{161849}{161877}Sad moram...
{161954}{162016}Pusti me sa srcem|punim ljubavlju.
{162366}{162395}Myungwoo!
{162635}{162666}Izvini!
{162738}{162776}Nemoj to govoriti.
{162858}{162889}Joö uvek se zovem Myungwoo.
{163290}{163340}NeÊu viöe biti tuûna.
{163417}{163491}Mislim da Êeö biti|uvek tu kraj mene!
{163522}{163592}Doi me videti|kad ti nedostajem!
{163652}{163762}Moûeö se uvek vratiti|kao vetar!
{165258}{165287}Traûili ste me?
{165306}{165351}Ja sigurno jesam.
{165366}{165457}Neko je doneo ovo u|Izgubljeno-Naeno i tvoje ime je bilo na njoj.
{165903}{165948}Za Kyungjin koja mi je spasila ûivot...
{165975}{166006}Predajem se tebi.
{166634}{166687}Kako si?
{166716}{166756}Nema viöe suza zbog mene?
{166766}{166802}Uvek sam s tobom.
{166821}{166860}Jednom sam ti rekao
{166879}{166948}da, kad me osetiö da|öapuÊem vetru,
{166963}{167037}naÊeö nekoga Ëiji je duh|sliËan mojemu.
{167075}{167104}Osetiö li me?
{167119}{167164}Sad sam s tobom.
{167186}{167224}UpoznaÊeö ga.
{167238}{167267}Danas!
{167435}{167469}Ko je doneo ovu knjigu?
{169200}{169269}äapnuo mi je|u vetru.
{169293}{169348}Osetim ga.
{169394}{169495}Stojao je kraj mene.
{169713}{169749}Da ti predstavim|devojku.
{169780}{169816}Ona...
{169830}{169912}Pretrpela je ogromnu bol|zbog mene i isplakala reku suza.
{169926}{170000}Zove se Kyungjin.
{170015}{170046}Kyungjin Yeo.
{170120}{170187}Svaki put kad joj spomenem|ime, Ëudan soeÊaj me obuzme.
{170233}{170341}Ima neöto u njoj.
{170555}{170640}KRAJ
{170665}{172165}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
