{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{2392}{2437}-Hvala, duöo.|-Nema na Ëemu.
{2684}{2709}-Boo.|-Hej!
{2736}{2788}Oprosti, neöto sam odlutao.
{2793}{2905}Sasvim razumljivo. I ja bih bila u transu da sam|pojela jedan od tih burgera.
{2909}{2945}Gdje ti je prijatelj?
{3012}{3044}Duöo?
{3064}{3105}Salata je gotova.
{3660}{3724}Dajte mi vaöu vozaËku dozvolu|i prometnu.
{3776}{3847}-Znate zbog Ëega sam vas zaustavio?|-Da.
{5500}{5524}Dobar dan.
{5528}{5584}Dobar dan, gospodine.
{5588}{5650}Oprostite za...
{5654}{5705}Bili smo usred voûnje i ja--
{5709}{5757}éao mi je.
{5762}{5813}-Jeste li uzeli moju lutku?|-Duöo, tiöina.
{5835}{5863}U redu je.
{5867}{5941}Uzeo sam je duöo. Malo je izudarana.
{5974}{6009}U svakom|sluËaju oprostite joö jednom.
{6022}{6084}Od ruËka, se ponaöa nevjerojatno.
{6088}{6158}-Dosadno mi je.|-Pa, znam kako ti je.
{6162}{6253}Ali moramo biti paûljivi sa naöim stvarima|tako da i svi ostali mogu biti sigurni, zar ne?
{6394}{6461}-NeÊe se dogoditi ponovno, gosp.|-OdliËno, hvala vam puno.
{6488}{6515}Prestani sa tim.
{6519}{6570}Oprostite. Vezana je, ali--
{6574}{6654}Ne brinite, sve je to|u opisu posla. Donijet Êu je.
{7318}{7346}Spusti glavu!
{7718}{7790}Daj mi ruku! Daj mi ruku!
{7960}{8160}{C:$0000FF}{y:ib} »OVJEK |{C:$FF0000}{y:b} OD PRU∆A 
{9015}{9078}-Hej.|-Hej.
{9182}{9221}Dakle.
{9225}{9279}To bi otprilike bilo to.
{9342}{9418}»ula sam za odlikovanje,|to je super.
{9422}{9461}Hvala.
{9535}{9640}Momci iz stanice priËaju da Êeö moûda|dati otkaz ili tako neöto. Da li je to istina?
{9651}{9702}Otac bi me ubio.
{9802}{9890}Izvoli. Pete me natjerao da ti|to donesem.
{9894}{9969}``Ozdravi brzo`` stvari.|Samo stiûu, pa....
{10088}{10161}-HoÊeö sjesti ili...?|-Moûe.
{10664}{10688}Da li ti ovo pomaûe?
{10749}{10778}Neöto pomaûe.
{10817}{10897}Ne moraö ostati.|Baö mi i ne trebaju posjetioci.
{11038}{11100}HoÊeö li sad postati|detektiv ili öta?
{11126}{11170}Samo trebam malo odmora.
{11230}{11297}Joö uvijek nisu naöli tijela iz onog|auta, zar ne?
{11301}{11338}Nisu.
{11363}{11425}Auto Ëak nije bio ni registriran,|ako moûeö vjerovati u to.
{11457}{11496}Pa, tko su one bile?
{11532}{11572}Ne znam.
{11704}{11751}Moûda se nikada|i ne sazna.
{11897}{12043}Edwarde, znam da nismo priËali zadnjih|nekoliko godina i da se sve zavröilo dosta loöe...
{12048}{12128}...bolje reËeno,|ja sam ih zavröila loöe...
{12132}{12207}...i nisam te ûeljela povrijediti joö|viöe no öto jesam.
{12225}{12262}Ali sada moram.
{12293}{12362}Da preem na stvar. Imam kÊerku.
{12376}{12489}Ona je savröeno dijete|i zove se Rowan.
{12506}{12606}Sada je dva tjedna kako je nestala,|i potrebna mi je tvoja pomoÊ.
{12624}{12661}Objasnit Êu ti.
{12668}{12753}éivim u Summersisleu,|malenom mjestu u Puget Soundu.
{12757}{12799}Sumnjam da si Ëuo za to.
{12804}{12911}Tamo sam odrasla. SjeÊaö se kako si me|uvijek ispitivao u vezi toga?
{12918}{12957}Sada znaö.
{12980}{13057}Rowan nije mogla sama otiÊi|s otoka. Premala je.
{13093}{13145}Pokuöala sam je naÊi sama...
{13149}{13217}...ali ljudi iz mjesta mi|ne ûele pomoÊi.
{13221}{13299}Bojim se da je u opasnosti,|pa se obraÊam tebi.
{13312}{13369}Molim se da mi oprostiö.
{13380}{13433}Tvoja Willow Woodward.
{13596}{13631}Halo?
{13669}{13706}Halo?
{14041}{14075}Eddie. Kako ide?
{14079}{14130}Dobro, hvala ti.
{14153}{14206}-Bok.|-Hej.
{14218}{14246}-Hej.|-Hej.
{14250}{14277}-Kako si?|-Bolje.
{14281}{14326}-VraÊaö se?|-Ne joö nekoliko tjedana.
{14340}{14398}Jesi li moûda vidio ovu ûenu|da ulazi?
{14419}{14477}-Ne, zaöto?|-Zato, nema markice.
{14513}{14546}ProËitaj.
{14702}{14779}Zaintrigirao me zaplet.|Nisam ni znao da imaö zaplet.
{14783}{14809}Ne seri.
{14814}{14869}Dakle ovo je, kao,|neka bivöa djevojka ili tako neöto?
{14887}{14911}Ova Willow?
{14915}{14973}Ne, ne, ona je bila....
{15008}{15047}-Bili smo zaruËeni.|-Molim?
{15051}{15150}Bili smo, znaö, bliski,|a onda me ostavila.
{15154}{15221}Da. ZvuËi kao da je postala bliska|sa joö nekim.
{15238}{15297}I ima te obraza|sada kontaktirati? Sranje.
{15302}{15392}Znam. Znam.|To je zbog Ëinjenice da sam policajac, valjda.
{15396}{15453}-Moramo biti na onom briefingu.|-Ok.
{15483}{15553}-Hej. Lijepo te vidjeti.|-Da.
{15593}{15650}-Odjebat Êeö ju, zar ne?|-Ne znam.
{15654}{15697}Da, ljut sam na nju.
{15701}{15729}Ma daj.
{15733}{15790}Nisi je vidio veÊ,|kako dugo? VjeËnost?
{15794}{15860}Nestalo joj je dijete, Pete, ok?|Ja sam moûda sve öta ima.
{15864}{15909}Reci joj neka kontaktira oca.
{15938}{15988}-Samo kaûem.|-Da, kuûim. Ja samo--
{15992}{16072}Zaöto je malo ne provjeriö|prvo? HoÊu reÊi, ma daj.
{16085}{16145}Summersisle? Gdje je to do vraga?
{16149}{16187}Da. Ovo je sve öto sam naöao.
{16191}{16268}To je privatno vlasniötvo|na Pacific Northwestu.
{16272}{16356}To je nekakva farmerska zajednica|ili tako neöto.
{16361}{16410}Da, neöto kao Amishi.
{16445}{16475}Nazovi je.
{16479}{16560}Pokuöao sam veÊ i|pogodi öto...tamo nema telefona.
{16583}{16633}Summersisle.
{18363}{18406}Hej, Pete, ja sam.
{18424}{18536}Hej, drago mi je da mi se javila sekretarica,|jer Êeö mi se vjerojatno smijati, ali--
{18540}{18581}Halo?
{18593}{18629}Halo?
{18965}{18994}Pozdrav tamo.
{19025}{19064}äta je to?
{19068}{19116}Ne znam kako|pozdraviti.
{19120}{19151}Jednostavno bok.
{19155}{19188}Dobro. Bok.
{19225}{19270}Znate li za mjesto|koje se zove Summersisle?
{19286}{19353}Da, znam. VeÊina dostava|ide za to mjesto.
{19358}{19385}Dostava, ha?
{19389}{19463}Da. Skoro svaki dan.|To i sada radim.
{19467}{19514}äta moram napraviti da|bih dobio prijevoz?
{19518}{19629}Oh, ne. Ne ûelim izgubiti ugovor|sa njima. Oni su dosta zahtjevni.
{19634}{19692}U redu, onda me ostavite|malo dalje na plaûi...
{19696}{19751}...ili öta veÊ imaju,|pa Êu ja pjeöice do gradiÊa.
{19755}{19792}Odgovor je joö uvijek ne.
{19796}{19857}To je samo par kilometara.|Mogao bih i preplivati to.
{19861}{19897}Onda vam je bolje da|poËnete plivati.
{19925}{19953}Zaöto? U Ëemu je stvar?
{19957}{20041}Zato jer je privatno.|Zabranjeno je i poötujemo to.
{20045}{20101}Ovdje svi drûimo do|svoje privatnosti.
{20105}{20182}Da, ali vi ste tako topli i otvoreni,|pa to mijenja stvari.
{20215}{20245}äalim se.
{20249}{20305}Ok, gledajte, kako bi bilo|da nas sve odvedete tamo?
{20309}{20357}Kako to mislite, ``sve``?
{20361}{20392}Pa, mene...
{20397}{20457}...G. Granta ovdje|i njegovog brata blizanca Ulyssesa.
{22659}{22699}Izgubili ste se?
{22703}{22784}Oh, hej. Oprostite.|Prikrali ste mi se.
{22807}{22837}Mislim da nisam.
{22841}{22900}-Ovo je Summersisle, zar ne?|-Da.
{22904}{22973}-Na pravom sam mjestu.|-Bojim se da niste. Ovo je privatno imanje.
{22977}{23037}Ne moûete doÊi ovdje|bez dopuötenja.
{23042}{23147}Sluöajte, potpuno vas razumijem,|ali ja sam pozvan ovamo.
{23182}{23248}-Ja sam murjak.|-I öta to znaËi?
{23252}{23338}Policajac.|Radim öta mogu za ljude. Pomaûem im.
{23362}{23432}Dakle, poûalio mi se jedan|stanovnik ovog otoka.
{23436}{23460}éalba, kaûete?
{23464}{23504}Da, gospoo. Da je nestalo dijete.
{23508}{23563}Pa, sada, to je uvijek problem.
{23567}{23613}Da. Za sve.
{23617}{23693}Moûda bi to trebali izloûiti|sestri Summersisle.
{23698}{23772}Ona je posebno zainteresirana|za svakoga tko sleti ovdje.
{23782}{23828}Uzgred, kako ste stigli ovdje?
{23859}{23897}Da li vas je dovezao luËki pilot?
{23902}{23936}On je samo...
{23980}{24016}Dobro, popriËat Êemo sa njim.
{24020}{24104}äto je u torbi,|morski pas ili tako neöto?
{24242}{24277}Da li je znate?
{24302}{24349}Ne prepoznajem to dijete.
{24353}{24406}-Ti Violet?|-Ne. Ne bih rekla.
{24410}{24495}Mali savjet. Puno bi pomoglo|kad bi ustvari pogledali fotografiju.
{24513}{24576}äta ûelite reÊi?|Da ova djevojËica nije sa otoka?
{24581}{24619}Ne bi se reklo.
{24623}{24668}Majka joj se zove Willow.
{24686}{24743}Aaa, sestra Willow.
{24747}{24804}Nije mi pala na pamet.
{24808}{24874}Da, imamo Willow ovdje, da.
{24878}{24949}-Odite gore do kuÊe za sastanke.|-Kakva koincidencija.
{24953}{24996}Ima slobodan duh.
{25029}{25060}Neöto vam curi iz torbe.
{25197}{25229}Hajde.
{25239}{25283}Pogledajte.
{25890}{25920}To nije njena kÊerka.
{26315}{26347}Izgleda da je ovo veËer za dame.
{26352}{26459}Bok. Da li ste vi ovdje barmen,|ili kako bi se to nazvalo?
{26464}{26508}Ja sam sestra Beech, da.
{26512}{26583}A vi ste taj policajac|iz Kalifornije?
{26628}{26690}Tako je. Zovem se Malus.
{26707}{26803}Edward Malus.|Htio bih sobu i obrok.
{26807}{26857}-Moûete li to izvröiti?|-Izvröiti öto?
{26861}{26907}Da li je to neki gradski govor?
{26944}{27037}Srediti. To misli.|Moûemo li mu srediti smjeötaj?
{27055}{27170}Pa, poöto nije prihvatio natuknicu i|otiöao, pretpostavljam da moramo.
{27174}{27211}Barem na jednu noÊ.
{27215}{27241}Dobro doöli.
{27327}{27408}Ovo je G. Malus,|policajac sa kopna.
{27419}{27469}-A ovo je--|-Willow.
{27492}{27539}Naravno.
{27646}{27697}Odvest Êe vas gore.
{27750}{27819}Ima prazna soba na zadnjem katu.
{27906}{27950}Mislim da Êu prvo neöto popiti.
{27984}{28048}Ako vam ne smetam.
{28062}{28172}Ovo je medovina.|To je jedna od poslastica naöeg otoka.
{28184}{28238}Mjeöavina meda, bilja...
{28258}{28299}...i koje Ëega.
{28328}{28367}Hvala.
{28427}{28467}Da.
{28678}{28732}Mislim da morate znati.
{28805}{28865}Mislim da svi morate znati|da sam ovdje poslovno.
{28869}{28973}Ovo je sluûbeni policijski posao i morat Êu|sa svakime od vas popriËati.
{29019}{29083}Sluûbeni Kalifornijski posao, zar ne?
{29087}{29155}Jer ovo je Washington.
{29159}{29183}Svjestan sam toga.
{29187}{29212}-Dobro onda.|-Nije dobro.
{29216}{29348}Go Beech, nije dobro.|Sve je osim dobrog kad je u pitanju nestala osoba.
{29352}{29376}Pogotovo dijete.
{29704}{29763}Dakle, zaöto ste to napravili?
{29770}{29816}Oprostite, alergiËan sam.
{30405}{30510}Nadziru me, moramo pokuöati|porazgovarati kasnije nasamo.
{30514}{30627}Ima mjesto izvan granice sela.|NaÊi Êemo se tamo za sat vremena.
{30631}{30751}Edwarde, budi paûljiv i ne vjeruj|ni u öto, öto budeö vidio ili Ëuo.
{30756}{30865}Boûe, vidjeti ti|lice ponovno...
{31032}{31131}Znaö, tradicija nalaûe da muökarac dobije prsten|natrag kada mu zaruËnica pobjegne.
{31223}{31306}Joö uvijek ga nosim, na izvjestan naËin.
{31433}{31480}Ne znam öto bih napravila|da nisi doöao.
{31491}{31557}-Kako sam mogao ne doÊi?|-Lako.
{31561}{31670}Mogao si pomisliti da sam luda ûena ili neöto|sliËno koja laûe o svojoj izgubljenoj kÊeri.
{31689}{31719}Kao svi ostali.
{31723}{31845}Gledaj, tek sam prihvatio Ëinjenicu|da imaö kÊer, ok?
{31849}{31891}Zato idemo polako.
{31977}{32006}Dakle....
{32023}{32077}Ne. Ne.
{32081}{32171}To je jedini naËin da zapoËnemo ovo.|äta ti se do vraga dogodilo?
{32175}{32199}Nisam....
{32318}{32390}Gledaj, to je bilo davno.|Bili smo mladi.
{32394}{32433}Pa öto?
{32475}{32526}Pa, zaöto bilo öto radimo|u svom ûivotu?
{32591}{32659}Trebam neki odgovor u vezi toga.
{32726}{32773}Da li je bio drugi Ëovjek u pitanju, ili...?
{32778}{32858}HoÊu reÊi, oËito,|si srela nekog, ali--
{32907}{32969}Gledaj, bila sam preplaöena i....
{33030}{33089}Ne znam, samo sam--|Nisam bila spremna za to...
{33138}{33180}...pa sam pobjegla nazad doma.
{33184}{33286}Usput, straöan ti je dom.|Ovo mjesto.
{33290}{33388}Mi smo drugaËiji. Znam to.
{33413}{33515}Ako odrasteö ovdje,|to je druga stvar, ali inaËe je....
{33547}{33620}Da, Ëudno.
{33657}{33688}Kako god....
{33699}{33799}Moja kÊer mi je trenutno|bitna. Rowan.
{33858}{33902}Zaöto raditi ovo?
{33953}{34030}IzvuËi sve to ponovno? To je tako....
{34129}{34177}Zaöto ne pozoveö njenog|oca da ti pomogne?
{34181}{34250}Zato jer samo tebi vjerujem.
{34294}{34352}»ak i nakon svih ovih godina.
{34479}{34520}Edwarde.
{34538}{34628}Ljudi Êe te pokuöati zavesti na krivi trag,|ali moraö mi vjerovati.
{34632}{34689}-éelim ti pomoÊi, ali--|-Ne, ona je oteta.
{34693}{34789}Od koga, ne znam. Ne znam.|Ali moja mala curica je joö ovdje.
{34793}{34896}ObeÊajem ti, ako je ovdje, naÊi Êu je.
{34900}{34967}-Znam da hoÊeö.|-Morat Êu ti postaviti neka pitanja.
{35001}{35074}Ok. NaÊi Êemo se opet kad|bude sigurno. Sad moram iÊi.
{35554}{35595}Ostavite nas.
{35693}{35742}Pozdrav, Sestro Beech.
{35756}{35809}Prekrasna veËer.
{35813}{35860}Stvarno je. Dobrodoöli, svi.
{35913}{35986}HoÊe li nas Sestra Summersisle|blagosloviti sa svojom prisutnoöÊu?
{35991}{36034}Ne ûalost neÊe.
{36038}{36140}Uûivajte u veËeri. Samo, pobrinite se da|budete spremne za sutraönji dan.
{36144}{36213}Vrijeme smrti i roenja.
{36244}{36350}-Da. Za Wicker Manov povratak.|-Da. Za Wicker Manov povratak.
{36411}{36442}IspriËajte me.
{36466}{36538}Da li je netko raspakiravao moju torbu?|Nedostaju mi neke kazete.
{36543}{36606}-Ne bih znala.|-Zovu se "SVE JE OK"!
{36626}{36660}Dobro.
{37238}{37357}Edwarde, znam da nismo priËali zadnjih|nekoliko godina i da se sve zavröilo dosta loöe...
{37401}{37465}...bolje reËeno,|ja sam ih zavröila loöe...
{37474}{37533}...i nisam te ûeljela povrijediti joö|viöe no öto jesam.
{37537}{37572}Ali sada moram.
{37692}{37740}To nije njena kÊer.
{37964}{37993}Jeste li uzeli moju lutku?
{37997}{38062}Da, jesam, duöo.|Malo je natuËena.
{39924}{39955}Rowan?
{40934}{40971}Rowan?
{41275}{41315}Rowan?
{42656}{42694}Halo?
{42817}{42855}Rowan?
{44721}{44804}Zaöto imate stvari iz duÊana?|Mislio sam da sve tu radite.
{44883}{44932}Gledajte, ja vam samo|posluûim ono öto mi je dano.
{44951}{45031}Ako vam se ne svia, morat Êete|priËati sa Sestrom Beech, u redu?
{45035}{45084}äta je to uopÊe sa tom|``Sestrinskom`` stvari?
{45099}{45172}To je naö naËin.|Nemamo Kraljevskog Meda za vas.
{45203}{45227}Ni malo?
{45231}{45279}Ne, ni kapi.
{45303}{45363}Naöi usjevi su ureËeni|proöle godine.
{45433}{45475}Mogu vam naÊi malo öeÊera.
{45531}{45574}U redu.
{45603}{45640}Ok.
{46654}{46706}G. Malus? Vaö zaslaivaË.
{46710}{46795}Hvala. äto je ovo?|Neka vrsta festivala?
{46799}{46913}Tako je, naö éetveni Festival.|Svake godine na kraju jeseni imamo festival.
{46917}{46997}A onda naravno i Festival Plodnosti.
{47001}{47094}Ali to je presveto.|Ne smije se slikati.
{47121}{47173}äta se dogodilo|sa proölogodiönjim?
{47205}{47309}Bojim se da je uniöten|proöle noÊi. Razbio se.
{47997}{48083}Hej. Htio sam te joö tamo pitati,|prepoznajeö li ovu djevojËicu?
{48214}{48249}Ne?
{48364}{48463}-Gdje je druga ûena koja radi ovdje?|-Otiöla je do seoske ökole.
{48515}{48558}Gdje je to?
{48585}{48631}Uz brdo i onda kroz öumu.
{48713}{48752}U redu. Savröeno.
{48817}{48847}Gledaj, ûao mi je.
{48878}{48940}äta Êe se ovdje dogoditi sutra?
{48951}{49051}Misliö, prekosutra?|To je teöko za objasniti.
{49055}{49155}Da, pretpostavljam.|Mislio sam da je to neki lokalni izraz.
{49159}{49182}Da vidimo.
{49187}{49316}Prekosutra Êe biti 02. 05.|Niöta, koliko ja znam.
{49320}{49393}Ne, mislio sam na sutra.|äta Êe se dogoditi sutra?
{49407}{49431}Rekla sam ti.
{49457}{49492}Jesi?
{49535}{49610}Kad Êeö odlaziti,|hoÊeö li me uzeti sa sobom?
{50676}{50700}Bok.
{50832}{50865}Dobro jutro.
{51332}{51447}I Daisy, hoÊeö li nam reÊi öto|Ëovjek predstavlja u svojoj najËiöÊoj formi?
{51545}{51657}-Da.|-Phallic symbol. Phallic symbol.
{51702}{51752}äkola se stvarno promijenila|otkad sam ja bio dijete.
{51757}{51830}Kako se usuujete stajati tamo i|plaöiti mi djecu.
{51834}{51914}Oprostite.|Ja sam Edward Malus iz Kalifornije.
{51918}{52010}Ja sam policajac. Vidite moju znaËku?
{52014}{52076}Nisam znala da neka od mojih|djevojaka treba biti uhapöena.
{52080}{52114}Ne treba.
{52118}{52199}Ovdje sam da bih pronaöao nestalu djevojËicu,|Ëiji ljudi se pretvaraju da ona ne postoji.
{52203}{52255}-Kako Kihotovski od vas.|-Kihotovski?
{52259}{52379}Od Don Quixotea, tragaËa uzviöenih,|ali nepraktiËnih ideala.
{52384}{52439}Uglavnom muökarca.
{52443}{52510}Gledajte, samo trebam priËati sa|Willow Woodward. Da li je ovdje?
{52536}{52652}Bojim se, da je veÊ otiöla. Zakasnili ste.|A zakon vam tu ne moûe pomoÊi.
{52715}{52763}Mogu li imati vaöu|pozornost na sekundu.
{52768}{52863}Kao öto ste veÊ Ëuli, ovdje sam da pronaem|prebivaliöte male djevojËice.
{52961}{53006}-Kako ti je ime?|-Lily.
{53011}{53057}Lily, ja sam policajac Ed. Bok.
{53061}{53111}Moûeö li ovo pokazati okolo|za mene, duöice?
{53529}{53585}To joj je ime, Rowan Woodward.
{53589}{53671}Da li netko od vas prepoznaje|ime ili fotografiju?
{53757}{53807}Evo vam odgovora.
{53811}{53918}Da je postojala, znali bismo za nju.|HoÊete li molim vas sada otiÊi?
{54035}{54087}»iji je ovo stol?
{54272}{54302}äto?!
{54357}{54446}Zarobili smo pticu unutra da|vidimo koliko dugo moûe izdrûati.
{54491}{54578}Zaöto ste im k vragu dozvolili|da naprave takvu bolesnu stvar?
{54625}{54699}-Gdjeje popis djece?|-Imate li ovlaötenje od Sestre Summersisle?
{54703}{54770}Ne, nemam--|Zaboravljate da je ovo stvar zakona.
{54774}{54838}Pa, bojim se da joö|uvijek trebate dozvolu.
{54938}{54978}Vratite to. Vratite to.
{54982}{55052}Oprostite. Morat Êete me|otrpjeti.
{55392}{55423}Vi male laûljivice.
{55453}{55520}Rowan Woodward je s vama u razredu,|zar ne?
{55537}{55629}Zar ne? To je njezin stol.
{55634}{55660}Vi ste najveÊa laûljivica.
{55665}{55735}Upozoravam vas, slaûite joö jednom|i uhapsit Êu vas.
{55739}{55793}To je obeÊanje, Gice...?
{55797}{55830}Rose. Sestra Rose.
{55834}{55898}Naravno. Joö jedna biljka. Rose.
{55902}{55977}Zadnji puta pitam, gdje je djevojËica?
{55981}{56037}Razgovarat Êemo vani.
{56050}{56115}Djevojke, nastavite sa|svojim sastavcima.
{56597}{56647}-Pa?|-Ne razumijete.
{56651}{56718}To je toËno. Ne razumijem.|Ali shvatit Êu.
{56722}{56787}G. Malus, nitko vam ne laûe.
{56791}{56858}Rekla sam vam da je Rowan Woodward|postojala, znali bismo za nju.
{56862}{56910}Ako je postojala? Ako?
{56914}{57026}-Ali ne moûete samo tako upadati u naöe--|-Svojim oËima sam vidio da je postojala.
{57030}{57108}Pretpostavljam da mi i njezina majka|laûe, zar? Ona laûe?
{57112}{57159}Ne laûe, ne.
{57163}{57205}Tuguje.
{57220}{57265}Svi tugujemo.
{57311}{57373}»ekaj, Ëekaj, Ëekaj.|Kad kaûete da tuguje...
{57377}{57447}...hoÊete reÊi da je Rowan mrtva?
{57451}{57491}Kad tako kaûete. Da.
{57495}{57571}-SMrtva je ili nije?|-Mi ne koristimo tu rijeË ovdje.
{57575}{57610}Ne, to bi bilo previöe Kihotovski.
{57615}{57645}Da.
{57649}{57749}Vidite, mi vjerujemo da nakon öto|ljudski ûivot zavröi, duöa ûivi dalje...
{57753}{57829}...u zraku, u drveÊu, u ûivotinjama,|Ëak i u vatri.
{57833}{57937}U redu, u redu, samo-- Ma dajte.|Recite mi öto joj se dogodilo. Iskreno.
{57985}{58043}-Bila je to nesreÊa.|-Kakva nesreÊa? Kako?
{58059}{58142}G. Malus, to je bila nesreÊa.|Ostavite to na miru, molim vas.
{58159}{58213}Dakle, ako je to istina, gdje joj je tijelo?
{58217}{58290}Upravo tamo gdje i oËekujete da bude.|U zemlji.
{58295}{58335}Na groblju?
{58339}{58373}Njezina majka je inzistirala.
{58387}{58461}Sad me ispriËajte,|moram se vratiti na nastavu.
{58505}{58598}»ekajte, Ëekajte, Gice Ro-- Sestro Rose.|»ekajte joö minutu.
{58620}{58657}Kako je umrla?
{58661}{58712}Izgorjela je.
{58719}{58778}Molim? äto ste rekli?
{58827}{58926}Upravo ono kako je i zvuËalo.|Izgorjela je.
{59465}{59493}IspriËajte me.
{59513}{59601}-Ima li kakva crkva ovdje?|-Ima.
{59605}{59628}Nizbrdo.
{59674}{59783}Hej, zar nisam upravo priËao sa vama?|Gica Rose-- Sestra Rose.
{59793}{59817}Ne, niste.
{60974}{61065}-To nije Rowanin grob.|-U redu.
{61069}{61165}Nije. Znam da se ovo Ëini....
{61184}{61226}Ali oni su je stavili ovamo.|Ja nisam.
{61246}{61282}Tko su ``oni``?
{61408}{61447}Ne znam.
{61460}{61555}Tko god da ovo radi, pokuöava--
{61880}{61988}Nije viöe neöto,|ali nekada je bilo lijepo.
{61992}{62050}Barem tako kaûu.
{62054}{62118}Sagraeno je prije nego|öto su moji preci stigli ovdje.
{62144}{62214}To je grobnica, ali je potopljena.
{62224}{62256}To je nova brava.
{62411}{62439}Rowan je ûiva.
{62538}{62602}Nisu mi tako rekli.
{62643}{62726}»uo sam da ne postoji,|da je zakopana na tom groblju...
{62740}{62790}...Ëak i da je....
{62824}{62875}Izgorjela.
{62889}{62997}Laûljivci!|Ne mogu je prihvatiti ili ne ûele.
{63001}{63074}Izgleda da je krive za sve--
{63211}{63325}Edwarde, mislim da Êe je|ozlijediti ili Ëak--
{63329}{63435}Zaöto bi?|Pokuöavam razumjeti. Stvarno pokuöavam.
{63439}{63480}Ali zaöto?
{63520}{63658}Jednom sam pobjegla, pokuöala pobjeÊi.|Misle da sam preponosna ili da sam--
{63731}{63811}Sestra Summersisle nikada nije|voljela moju divlju stranu.
{63815}{63937}Da, to ime se stalno spominje.|Ta Summersisle.
{64002}{64072}-Tko je ona?|-Ona je sve.
{64087}{64166}Sve öto vidiö,|sve to, stvarno, sve je ona.
{64170}{64244}Mi ostali, mi samo--|éivimo u njenoj sjeni.
{64270}{64305}Pogotovo ja.
{64404}{64455}Svi govore da sam poludjela?
{64466}{64500}Nisam, Edwarde.
{64504}{64560}Kunem se, nisam. Ona je--
{64641}{64710}Ne mogu im dozvoliti da|mi to uËine.
{64754}{64821}äto?|äto mi ne govoriö?
{64847}{64883}Oprosti mi?
{64917}{64969}Da ti oprostim za...?
{65000}{65028}Izgubljen sam.
{65033}{65084}Ne znam.
{65120}{65153}Ne brini, to je....
{65176}{65203}Znaö?
{65207}{65301}Ne. Ne znam. Ne znam da li Êe|naöa kÊer biti dobro.
{65473}{65543}Sada znaö öto sam ti|pokuöavala reÊi.
{65577}{65647}Zaöto mi je potrebna tvoja pomoÊ.
{65771}{65864}éeliö reÊi da sam ja Rowanin otac?
{65891}{65930}Da.
{66263}{66303}To nije u redu.
{66510}{66565}Trebala si mi reÊi, Willow.
{66961}{67009}Ovdje si zadnji puta vidjela Rowan?
{67040}{67075}Da?
{67092}{67151}Moûeö li mi reÊi detalje?|To je vaûno.
{67179}{67256}Da. Kad sam je zadnji puta vidjela....
{67260}{67321}Sjedila je tamo za stolom.
{67354}{67402}Rowan voli crtati.
{67419}{67489}I plivati. Znaö,|pliva poput--
{67493}{67536}Pliva. Ok.
{67545}{67612}ZnaËi otiöla si van, zar ne?|Izaöla si van.
{67616}{67678}Samo do duÊana.|Nisam bila duûe od pola sata.
{67683}{67742}-I vratila si se i öto je onda bilo?|-Nje viöe nije bilo.
{67761}{67807}Nestala.
{67811}{67907}I sve njezine stvari, njene igraËke,|knjige, sve, kao da je sve--
{67911}{67947}äta je imala na sebi?
{67951}{68016}Vestu öto sam joj isplela.
{68031}{68138}Onu na slici. To je imala na sebi.
{68142}{68201}OblaËi se kao i sva djeca|na otoku.
{68234}{68305}-Imaö li joö koju njenu fotografiju?|-Ne.
{68318}{68422}Nemamo puno.|HoÊu reÊi, samo Dr. Moss ih slika.
{68454}{68502}Dr. Moss?
{68611}{68686}I sigurna si da ne postoji moguÊnost da ju|je oteo netko tko nije sa otoka?
{68718}{68743}Ne.
{68786}{68834}Oprezni su s time koga|puötaju ovamo.
{68838}{68908}Da li je Rowan bila u depresiji?
{68912}{68991}Jesi li vidjela öta je nacrtala ispod|svog stola? To je uznemirujuÊe.
{68995}{69049}Edwarde, znam to.
{69258}{69282}äto to radiö?
{69319}{69373}Avion. Trebam njegov radio.
{69377}{69420}»ekaj me.
{69995}{70039}Halo?
{70114}{70159}Halo?
{70169}{70224}Gdje je taj Ëovjek?
{71500}{71532}Rowan?!
{71626}{71664}Rowan!
{72502}{72553}K vragu!
{74570}{74668}Uporni ste. Na odlasku sam,|ali moûda vam mogu kako pomoÊi?
{74682}{74736}Moram vam postaviti par pitanja.
{74740}{74767}Brzo Êemo.
{74771}{74824}Stvari su rijetko brze.
{74828}{74857}Uite unutra, onda.
{74861}{74904}Hvala vam.
{75029}{75085}Vi ste T.H. Moss, fotograf.
{75089}{75187}Prvo sam doktor,|a tek onda fotograf. Daleko iza.
{75197}{75232}éelite da vas slikam?
{75272}{75347}ZnaËi vi slikate éetveni Festival|svake godine?
{75352}{75410}Onaj koji sam vidio u taverni?
{75414}{75484}Da, bojim se da je to dosta|jednoliËan posao.
{75537}{75609}Moja majka je prenijela tu vjeötinu na mene,|a njena majka na nju.
{75613}{75706}Vaöa majka. Naravno.|Imate li fotografije od proöle godine?
{75719}{75810}-Zar nije tamo sa ostalima?|-Ne. Ne, navodno je uniötena.
{75814}{75855}Kakva öteta.
{75889}{75918}Imate li kopiju?
{75922}{76012}Imam negativ. Ako ûelite|mogu vam isprintati jednu.
{76016}{76069}To bi bilo super.
{76167}{76202}Hvala.
{76579}{76628}Vrijeme je, sestro.
{76648}{76695}Moramo poûuriti.
{77430}{77542}"U druötvima toliko razliËitima poput|drevnog Egipta i pre-Columbijskim Incama...
{77546}{77623}...festivali plodnosti su se odvijali|na sliËne naËine.
{77635}{77714}Mlada ûena je izabrana da|personificira plodnost...
{77718}{77790}...i onda je ubijena u krvavom ritualu|od ruke predsjedajuÊe sveÊenice.
{77794}{77907}Mislilo se da Êe ta gesta pridonijeti|plodnoj ûetvi u nadolazeÊoj godini.
{77965}{78060}Meutim, u Europi i Americi,|ûrtva je spaljivana. "
{78076}{78120}Spaljivana.
{78577}{78613}Oh, Boûe.
{79540}{79581}``Rowan Woodward Goddess.``
{79644}{79692}``Najgora zabiljeûena ûetva.``
{79937}{79966}Hej.
{80021}{80052}äto je do vraga ovo?
{80168}{80258}-To je slika i to je sve.|-Ne, to nije sve!
{80297}{80387}Zaöto mi nisi rekla da je Rowan bila|dio svega ovoga? Tih rituala?
{80424}{80448}Ne znam.
{80452}{80527}Pokuöaj, zato jer se vrtim u krug|i dobro bi mi doöla pomoÊ!
{80531}{80612}-Edwarde, zaöto viËeö na mene?|-äta misliö o ovome, za poËetak:
{80616}{80675}Naöa kÊer je dio vaöe|najgore zabiljeûene ûetve.
{80679}{80750}Rekla si da je krive za neöto.|Zaöto mi nisi rekla u vezi ovog?
{80754}{80838}To je samo-- To je samo naöa ceremonija.
{80842}{80878}Ne znam niöta drugo o tome.
{80883}{80949}éiviö ovdje! Moraö neöto znati.
{80953}{81000}Spomenula si tu ceremoniju.|Definiraj to!
{81019}{81081}äta je dan smrti i roenja?
{81085}{81168}To je priËa. To je sve öto je, priËa.
{81172}{81261}Pokuöavam ti vjerovati, ali Ëim okrenem|glavu, neöto tu nema smisla.
{81265}{81317}Pa i mene ovo mjesto plaöi.
{81335}{81438}Bila sam sretna öto sam mogla otiÊi.|Iako sam se vratila...
{81443}{81469}...voljela bih da nisam.
{81474}{81535}Da sam barem ostala i|imala ûivot sa tobom...
{81539}{81601}...bila sa tobom svih ovih godina,|ali nisam.
{81605}{81670}Vratila sam se ovamo i rodila naöe dijete,|a sad je ona--
{81674}{81781}Ok. U redu. éao mi je.|Nisam htio....
{81786}{81821}Nije bitno. Nije bitno.
{81890}{81919}Nastavit Êemo traûiti.
{81994}{82040}IÊi Êu vidjeti tu Gu Summersisle.
{82044}{82094}Moramo sve provjeriti, ako|ûelimo pronaÊi Rowan.
{82104}{82141}Ako?
{82155}{82189}Ako je pronaemo?
{82193}{82247}Ne. Kad. Kad je naemo.
{83085}{83150}Daj da ti pomognem.|éeliö li pomoÊ?
{83474}{83515}Jesi li dobro?
{83562}{83587}Zar ne moûeö priËati?
{86515}{86561}Pogni glavu!
{86610}{86698}Da je postojala, znali bismo za nju.|HoÊete li molim vas otiÊi?
{86719}{86793}Rowan Woodward je tvoja ökolska prijateljica,|zar ne?
{86804}{86834}Zar ne?
{87014}{87100}Malo smo se uplaöili, zar ne?|Spavali ste nekoliko sati.
{87173}{87204}Gdje sam?
{87225}{87281}Ovo je dom Sestre Summersisle.
{87285}{87323}lvy?
{87510}{87549}Jeste li upotrijebili moju prvu pomoÊ?
{87573}{87633}-Adrenalinsku injekciju, ili--?|-Oh, ne.
{87637}{87669}Niöta takvog.
{87673}{87753}Kad su me doveli do vas,|bili ste blizu smrti, oËito.
{87757}{87833}Pa sam otklonila opasnost|starim naËinom.
{87964}{88056}éivi ste. To je najvaûnije.
{88191}{88247}Doöao sam vidjeti Sestru Summersisle.
{88251}{88303}Da. Vani je trenutno.
{88391}{88452}I oËekuje vas.
{90299}{90342}Zamalo su vas sredile.
{90346}{90393}Oprostite?
{90411}{90483}Naöe male prijateljice, pËele.
{90496}{90527}Zamalo su vas rijeöile.
{90531}{90568}Da.
{90585}{90621}äteta.
{90633}{90731}äto, öteta? äto zamalo jesu ili nisu?
{90844}{90928}Nekoliko naöih Ëuvara vas je naölo,|dolje blizu staja.
{90936}{90960}Bez svijesti.
{90964}{91053}Da. »uvari pËela.|Izgleda da su svugdje na otoku.
{91058}{91167}Oh, da. Treba ih nekolicina|da saËuvaju red ovdje.
{91171}{91214}Siguran sam.
{91255}{91325}Mogu vam reÊi öto vidi u vama.
{91330}{91417}Sirovi potencijal.
{91421}{91468}Hvala, valjda.
{91473}{91547}»ujem da ste me oËekivali.
{91552}{91585}Zaöto?
{91606}{91677}Bilo je pitanje vremena|kad Êete doÊi ovamo.
{91685}{91757}Vjerujem da traûite dijete?
{91769}{91821}-Moûda sam je naöao.|-Izvrsno.
{91825}{91864}Nije baö.
{91869}{91893}U grobu.
{91906}{92006}I ûelio bih vaöe dopuötenje|da ekshumiram tijelo, ako postoji...
{92010}{92053}...i da ga odnesem na autopsiju.
{92073}{92127}Mislite da je moguÊ zloËin?
{92131}{92180}Da. Ubojstvo.
{92206}{92248}Kako zbunjujuÊe za vas.
{92279}{92353}U tom sluËaju, morate nastaviti.
{92402}{92448}Ne Ëinite se zabrinutima.
{92452}{92493}Ne.
{92497}{92558}Vjerojatno zato öto sam...
{92562}{92660}...uvjerena da su vaöe sumnje|neopravdane.
{92665}{92711}Mi ne ubijamo ovdje.
{92734}{92852}Da. Pa, Ëak i ako je ûrtva suglasna,|to je joö uvijek ubojstvo.
{92856}{92922}Pa, moûda tamo od kuda vi dolazite.
{92950}{92991}Ali mi imamo svoja uvjerenja.
{92995}{93052}Da, da, da.
{93056}{93175}Festivali. Sva ta ûrtvovanja.|Kome, toËno?
{93214}{93303}Velikoj Majci Boûici|koja vlada ovim otokom...
{93307}{93400}...sa mnom kao njenom zemaljskom|predstavnicom.
{93416}{93454}Vama?
{93458}{93554}Ja sam duhovni voa ove zajednice.
{93589}{93660}Vi stvarno ohrabrujete|ovakva uvjerenja?
{93704}{93823}Ma dajte. Lijepo je. Proöetajmo.
{93890}{93974}Nekada davno, moji Keltski preci...
{93978}{94058}...su se pobunili protiv|zapostavljanja ûena.
{94062}{94218}Pa su potkraj 17-og stoljeÊa,|otplovili u Novi Svijet.
{94227}{94319}Na nesreÊu, smjestili su se blizu Salema.
{94323}{94435}Pa kad su vidjeli da su se|progoni nastavili, Ëak i ovdje...
{94454}{94570}...pa, to je pokrenulo veliku|i bolnu migraciju prema zapadu.
{94574}{94711}1850, moja pra-pra-prabaka|dovela je grupicu ljudi ovdje...
{94734}{94850}...i zaklela se da se viöe nikada|neÊe vratiti u vanjski svijet.
{94855}{94899}Kako je to moguÊe? Ne moûete samo--
{94903}{95010}Oh, tim pionirima je trebao|jako malen nagovor na izolaciju.
{95014}{95102}Traûili su jednostavniji|naËin ûivota.
{95130}{95197}Naravno, neki odu,|poput naöe Willow...
{95216}{95280}...znate, da testiraju sebe ili nas.
{95284}{95320}Ili da nau muökarca.
{95334}{95412}Ali uvijek se na kraju vrate.
{95430}{95586}-Muökarci su öto, graani drugog reda?|-Ne, uopÊe ne. Mi volimo naöe muökarce.
{95594}{95672}Samo im nismo podloûne.
{95676}{95763}Muökarci su vaûan dio|naöe male kolonije.
{95805}{95847}Za oplodnju, znate.
{95872}{95918}Boûe.
{95922}{96017}Lijepo ste se vi to sve|dosjetili. Oplodnja?
{96034}{96083}Meni to zvuËi kao sroivanje.
{96087}{96164}Molim vas nemojte kritizirati ono|o Ëemu niöta ne znate.
{96168}{96260}Zar nitko od vas jednostavno ne|ûeli biti s nekim? Zaljubiti se?
{96264}{96357}Mi raamo zato jer|je to Boûicina volja.
{96361}{96433}Da si osiguramo vrijedno potomstvo.
{96437}{96529}NajjaËe, najbolje,|najotpornije od naöe vrste.
{96553}{96612}Kuûim. éene, zar ne?
{96630}{96730}A öto, ako netko dobije|sina? äto napravite?
{96749}{96778}Ovisi.
{96923}{97001}Da vas pitam neöto drugo, zato öto,|iskreno, ja vas jednostavno ne shvaÊam.
{97005}{97044}Ne shvaÊam ovo mjesto.
{97048}{97101}Oh, hoÊete. Moûda, s vremenom.
{97105}{97173}Moûda je vrijeme da mi|prestanete srati, ok?
{97177}{97201}Budite oprezni.
{97205}{97288}Pogotovo kad je u pitanju ûivot|male curice. Moje male curice.
{97292}{97337}Siguran sam da ste shvatile.
{97341}{97385}äto se toga tiËe, jesam.
{97414}{97480}Mene zanima samo zakon, sestro.
{97484}{97593}Da vas podsjetim, vi ste joö uvijek u dohvatu|zakona normalnog druötva.
{97597}{97705}Dakle, ako vi luaci prakticirate otmice|i ritualna ubojstva, moj posao je da--
{97709}{97795}Vjerujem da sam vam spomenula|naöa stajaliöta o ubojstvu.
{97800}{97853}Ubojstvo je ubojstvo.
{97857}{97940}Dakle, imam li dozvolu da otvorim|grob Rowan Woodward?
{97944}{98016}Bila sam pod utiskom da|sam vam veÊ dozvolila.
{98020}{98061}Vaö prijevoz.
{98065}{98215}Pa, bilo je fascinantno razgovarati s|nekim iz normalnog druötva.
{98220}{98259}Do naöeg ponovnog susreta.
{99992}{100038}Rowan?
{100104}{100143}Rowan?
{100750}{100793}Rowan?
{101777}{101815}Rowan?
{102159}{102199}Rowan?
{102523}{102578}Rowan? Rowan!
{104162}{104202}UpomoÊ!
{104234}{104261}Hej!
{104422}{104474}UpomoÊ!
{104546}{104603}UpomoÊ!
{105098}{105201}Moja kÊer mi je sada|najvaûnija. Rowan.
{105377}{105457}Da sam barem ostala i|imala ûivot sa tobom, ali nisam.
{105461}{105529}Vratila sam se ovamo i rodila naöe dijete,|a sad je ona--
{105533}{105605}-Pa, tko su oni?|-Ne znam.
{105655}{105692}Moûda nikada ne saznamo.
{106029}{106068}Edwarde?
{106130}{106165}Dolje sam.
{106169}{106197}Edwarde?
{106201}{106272}Da. Netko je zatvorio poklopac.
{106276}{106339}-Dolazim.|-Oh, Boûe.
{106965}{107061}Willow. Pogledaj. Pogledaj ovo.
{107081}{107196}Bila je tu. Bila je ovdje dolje.|Netko je drûi ovdje.
{107366}{107414}éelim ti joö neöto pokazati.|Doi.
{107606}{107670}Je li ovo njezino? Reci mi!
{107675}{107722}Da, mislim da-- Da, ali--
{107727}{107780}Kako je spaljeno?|Kako je spaljeno?!
{107784}{107816}Kako je spaljeno?!
{107820}{107857}Ne znam!
{107869}{107908}-Gdje ideö?|-Natrag k njoj.
{107912}{107962}-Idem s tobom.|-Ne, Willow! Ozbiljan sam.
{107967}{108000}Ali moûda ako--
{108020}{108062}Zaöto me--?
{108066}{108110}Zaöto me tako gledaö?
{108114}{108226}Neöto loöe Êe se dogoditi.|OsjeÊam to.
{108284}{108358}Idi u kuÊu i zakljuËaj se unutra.|Vratit Êu se po tebe.
{108383}{108413}Idi! Odmah!
{108845}{108880}Summersisle!
{108968}{109010}Summersisle?
{109070}{109116}Summersisle!
{109346}{109392}Summersisle?
{109421}{109456}Summersisle!
{109565}{109613}Summersisle!
{109980}{110025}Summersisle?
{110060}{110103}Summersisle!
{110145}{110194}Summersisle!
{110449}{110484}Otiöao je.
{110492}{110539}Izvrsno.
{110930}{111012}-äto je s ovim perjem?|-Pripremamo se.
{111016}{111073}-Za öto? Proslavu?|-Oh, da.
{111077}{111144}Smrti i roenja.
{111148}{111208}Sestro Rose, ona je joö dijete.
{111224}{111278}Vi ste uËiteljica.|Razmislite o tome öto radite.
{111282}{111377}Vrijeme za sentimentalnost je proölo.|Stigao je Ëas.
{111381}{111414}NeÊu dozvoliti da umre.
{111418}{111509}Tako galantno, Gdine Viteûe.|Vidim da se joö borite protiv vjetrenjaËa.
{111513}{111548}Skroz do kraja.
{111552}{111583}Siite s bicikla.
{111616}{111647}Siite s bicikla.
{111708}{111754}Odmaknite se od bicikla.
{111826}{111872}Uzmite svoju glupu masku.
{112137}{112171}-To je on.|-To je on.
{112883}{112950}Trebam vaöu pomoÊ. Od svih vas.
{112954}{113009}Zar me ne Ëujete?|Rekao sam da trebam vaöu pomoÊ.
{113102}{113145}Ne bojte se.
{113506}{113589}Traûim nestalu djevojËicu.|Skinite tu masku sa svog djeteta.
{113665}{113745}»ekajte malo! Imate li dozvolu da|upadnete ovamo i uznemira--?
{113749}{113800}Ne! Ne trebam niËiju|prokletu dozvolu!
{113817}{113893}Pretraûit Êu svaki komadiÊ ovog otoka|i svatko tko se umijeöa...
{113898}{113952}...Êe biti optuûen za ubojstvo,|razumijete?
{113956}{114037}Imate moju dozvolu da mi|se jebeno maknete s puta!
{114529}{114599}Hej! Skidajte te maske.
{114603}{114664}-Hej! Stanite!|-Doi ovdje.
{114668}{114737}-Maknite se. Nemojte.|-Gubite se van.
{114867}{114908}Rowan?
{114986}{115011}Rowan?
{116655}{116747}Vjerujem da neÊete morati vaditi|vaö kostim i ove godine, sestro.
{116751}{116848}Uskoro Êete biti|cijela obitelj medvjeda.
{116895}{116941}Oh, snaÊi Êu se, Sestro Oak.
{116945}{117030}Izgleda kao da se malo smanji|svake godine.
{117054}{117144}Dakle, sestro, jeste li|sredile onaj posliÊ u luci?
{117148}{117217}Oh, da. Kao öto ste naredili.
{117292}{117321}OtiÊi Êu sad.
{117355}{117382}Dakle, dakle.
{117396}{117479}Izgledate dosta loöe,|sada, zar ne?
{118241}{118302}O Boûice Polja...
{118318}{118428}...donosim ovu poniznu koloniju|pred tebe na ovaj dan.
{118432}{118489}Ovaj najsvetiji dan.
{118493}{118546}Molim te primi naöu ûrtvu.
{118550}{118648}éivjela, Boûice Polja.|Primi naöu ûrtvu.
{118652}{118717}Joö jednom nas|u godini koja dolazi...
{118725}{118836}...daruj sa bogatstvom i raznovrsnoöÊu|svih plodova na ovom svijetu.
{119652}{119684}Boûe!
{121303}{121356}Mislim da sam ti rekao da me Ëekaö.
{121374}{121423}Kako to misliö? Morala sam doÊi.
{122117}{122154}A sada...
{122161}{122216}...ispunit Êemo naöu najveÊu svrhu...
{122234}{122296}...da izbalansiramo sile dobra i zla.
{122390}{122427}Oh, dragi Boûe.
{122828}{122865}äto je? äto nije u redu, sestro?
{122901}{122930}Nemoj se bojati.
{122954}{122994}Idi.
{122998}{123050}Moje ime je Edward. Spasit Êu te.
{123670}{123725}Hajde. Ovuda.
{123829}{123868}Poûuri.
{124647}{124722}»ekaj. Rowan. Rowan, Ëekaj. »ekaj.
{124821}{124898}Halo? Halo? Pete! Pete! Pomozi nam!
{124902}{124993}UpomoÊ! Molim te! Molim te pomozi!
{125179}{125225}Hajde. Idemo.
{125359}{125456}Rowan. Duöo. Uspori.
{125539}{125586}Rowan, uspori.
{125682}{125752}Rowan! Rowan, stani!
{125779}{125824}Jesam li bila dobra, mamice?|Jesam li?
{125828}{125858}Jesi, ljubavi.
{125862}{125902}Oh, mala moja Rowan.
{125906}{125946}Bila si odliËna.
{125955}{126029}Ne dirajte je! Ne diraj je!
{126045}{126073}Rowan, doi ovamo.
{126115}{126141}Dobrodoöli, G. Malus.
{126145}{126198}Doöli ste svojom slobodnom voljom...
{126202}{126263}...na sastanak sa|»ovjekom od pruÊa.
{126267}{126308}Nazad!
{126358}{126407}A sada je igra gotova.
{126411}{126470}Igra lovca koji|slijedi lovinu.
{126475}{126530}Doöli ste pronaÊi naöu malu Rowan.
{126534}{126611}Ali mi smo ti koji su pronaöli vas,|baö kao öto smo i htjeli.
{126615}{126716}Ne razumijem. Rowan je nestla.|Morao sam doÊi. Dobio sam pismo.
{126720}{126751}Willow, reci im.
{126810}{126842}Willow, molim te reci im.
{126866}{126937}Pismo je bilo od svih nas.
{126951}{126986}Vaöa pozivnica da posjetite...
{127022}{127046}...nas.
{127050}{127110}Vi ste bili muökarac kojeg trebamo.
{127120}{127173}I bili smo odluËni da vas|dovedemo ovamo.
{127178}{127223}PrimjeÊujete kako smo vas naveli|da povjerujete...
{127227}{127351}...da Êe vaöa kÊer biti ûrtvovana|zbog loöe ûetve proöle godine.
{127355}{127397}Ali bila je loöa ûetva. Vidio sam sliku.
{127402}{127488}Da, stvarno je bila loöa.|Katastrofalno.
{127492}{127561}To se dogodilo samo par puta|otkad su moji preci stigli ovamo.
{127582}{127694}Ali uvijek smo spremni|sa moÊnom ûrtvom.
{127708}{127805}A to je, prijatelju moj, tvoja sudbina.
{127809}{127859}-To je tvoja sudbina.|-Odbijte!
{127874}{127974}Trebamo stranca,|ali da je ipak povezan sa nama.
{127978}{128027}-Povezan je sa nama.|-Povezan je sa nama.
{128031}{128073}Povezan krvlju.
{128248}{128287}Willow.
{128421}{128473}Zaöto si mi ovo napravila?
{128516}{128574}Organizirali smo sve ovo sa|najveÊim oprezom prema...
{128578}{128643}...svemu öto se dogaalo.
{128649}{128726}Budi ponosan na sebe.|Bio si jako dobar.
{128730}{128827}Tako je. Moja kÊer govori istinu.
{128832}{128976}Tvoja sudbina je zapeËaÊena prije mnogo godina|kada te je odabrala da bude s tobom.
{129032}{129076}Vaöa kÊer?
{129097}{129166}Da. Moja Willow.
{129191}{129286}Ovo je priËa Ëiji su dijelovi|oprezno ispriËani.
{129416}{129503}Izabran si da umreö|muËeniËkom smrÊu.
{129507}{129617}Sjedit Êeö pored Bogova i Boûica|za sve vjeke vjekova.
{129628}{129700}Nazad! Kunem se Bogom, ubit Êu vas!
{129710}{129808}To je velika Ëast,|ona koju ne moûeö odbiti.
{129830}{129864}To je odreeno.
{129886}{129946}Nema izlaska iz toga.
{129951}{129989}Nazad!
{130963}{130996}Kuje jedne!
{131043}{131074}Kuje jedne!
{131150}{131220}To je ubojstvo! Ubojstvo!
{131224}{131286}Svi Êete biti krivi!
{131290}{131343}I radite to zbog niËega!
{131358}{131425}Moje ubojstvo vam neÊe vratiti|vaö prokleti med!
{131430}{131469}Ali ja znam da hoÊe.
{131582}{131629}Oh, Boûe.
{131715}{131744}Kako moûe?
{131780}{131843}Ja nisam jedan od vas!
{131878}{131919}Ne vjerujem u vaöe bogove!
{131942}{132001}Ne vjerujem u ûrtvovanje.
{132218}{132271}Oh, Boûe.
{132382}{132445}Ne, nemojte-- Nemojte me micati!
{132487}{132541}äto je to? äto je to?
{132550}{132598}äto je to? äto je to?|äto je to?
{132616}{132710}Oh, ne. Ne, ne pËele!|Ne pËele!
{132753}{132835}U oËima su mi! Moje oËi!
{133585}{133644}Ovaj puta Êemo na vaö naËin.
{133711}{133770}Moram te odrûati ûivim.
{134798}{134841}Oh, Boûe.
{134851}{134952}Oh, moj Boûe. Oh, moj Boûe!
{135400}{135462}O bogovi i boûice prirode.
{135525}{135632}Primite ovu ûrtvu i budite zadovoljeni.
{135650}{135729}O bogovi i boûice prirode.
{135733}{135829}Primite ovu ûrtvu i budite zadovoljeni.
{136805}{136849}Rowan.
{136887}{136936}Ne. Rowan!
{136987}{137088}Ne, Rowan, nemoj! Spusti to! Ne!
{137113}{137140}Spusti to!
{137188}{137227}Rowan!
{137241}{137314}Spusti to, duöo. Spusti to.
{137525}{137596}Rowan, ne! Ne!
{137600}{137659}Ne!
{137863}{137940}Trut mora umrijeti!
{137944}{137998}Trut mora umrijeti!
{138009}{138071}Trut mora umrijeti!
{138075}{138116}Trut mora umrijeti!
{138120}{138171}Trut mora umrijeti!
{138180}{138280}{C:$0000FF}{y:ib} d |{C:$FF0000}{y:b} d 
{138305}{139805}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
