{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{1552}{1680}K-19|PODMORNICA
{2800}{2845}Neka sva odeljenja prijave stanje.
{2912}{3008}Odeljenje jedan, pripravno i spremno.|Odeljenje dva, pripravno i spremno.
{3109}{3156} Odeljenje 4, pripravno i spremno.
{3157}{3221}Odeljenje 5, pripravno i spremno..
{3225}{3330}Odeljenje 6, pripravno i spremno.|Odeljenje 7, pripravno i spremno.
{3368}{3491}Odeljenje 8, pripravno i spremno.|Odeljenje 9, pripravno i spremno.
{3550}{3628}Odeljenje 10, pripravno i spremno.|Druûe Kapetane
{3630}{3721}brod je pripravan i spreman za bojevo|lansiranje glavne raketne baterije.
{3756}{3844}Activirajte hitnu proceduru|za ispaljivanje nuklearnog projektila.
{3845}{3908}Druûe Kapetane, PolitiËko|Odeljenje je spremno da izvröi svoju duûnost.
{3911}{3940}Izvinite me.
{4035}{4088}Hidraulika|prema raketnoj cevi 1 otvorena.
{4451}{4545}Druûe Kapetane, Moskva je potvrdila|dozvolu za ispaljivanje nuklearnog oruûja.
{4548}{4621}Poklopac br.1 otvoren.|Silos ispraûnjen od vode.
{4624}{4730}UkljuËujem lansirne konzole.|UkljuËujem konzolu br.1.
{4733}{4794}Polianski,|odrûavajte sadaûnji kurs i brzinu.
{4796}{4901}Kurs stabilan 2-9-0.|Odrûavam brzinu öest Ëvorova.
{4969}{5049} Poklopac br.1 otvoren.|Silos ispraûnjen od vode.
{5200}{5245}Punjenje u toku.
{5248}{5313}Nastavite sa aktiviranjem|bojeve glave na raketi br.1.
{5354}{5392}Gore periskop.|Periskop se podiûe.
{5395}{5429}DemiËev, nazad u kontrolno.
{5433}{5488}Pripremite cev br. 3 za aktivni status.
{5491}{5543}Prebacite lansirnu konzolu na primarni.
{5546}{5591}Konzola na primarnoj poziciji za br.1.
{5594}{5625}äezdeset sekundi u dometu.
{5628}{5686}Pripremite se za zaranjanje nakon lansiranja.
{5793}{5844}Raketa br.1 napunjena.|Postolje izdignuto.
{5848}{5896}Postolje izdignuto.|Dole periskop.
{5899}{5930}Spremni za lansirnu sekvencu.
{5998}{6092}Lansiraj raketu br.1.|Vreme do lansiranja: 1 5 sekundi.
{6095}{6147}1 4, 1 3, 1 2...
{6150}{6201}1 1, 1 0...
{6204}{6260}Kapetane, pucaju na nas.
{6263}{6325}Neprijateljsko torpedo na kursu 1 -9-0.
{6328}{6396}7 Neka podmornica zaroni.|Drûite na 50 metara.
{6399}{6459}Drûite na 50 metara.|Obim turbinama punom snagom napred.
{6462}{6503}Punom snagom napred.
{6506}{6568}3, 2, 1. Kapetane!
{6601}{6633}Preuzmite ruËno komandu.
{6634}{6681}Mehanizam lansiranja ne reaguje.
{6684}{6766}Procenjujem da je torpedo na 6,000 metara.|Veûba je zavröena.
{6850}{6884}Pa, Druûe Polenin
{6887}{6982}imate li objaönjenje|za ovo razoËarenje?
{6985}{7097}Druûe Admirale, to je samo joö jedno|pregorevanje u lansirnoj sekvenci.
{7100}{7178}Druûe Kapetane, treba Êe mi|imena odgovornih.
{7181}{7251}Neznam im imena. Kako bih dovraga|mogao da znam imena magaraca
{7254}{7363}koji su poslali insulator vredan 30 kopejki|tamo gde treba od 50 kopejki?
{7366}{7419}Sa tim prvo treba da se izborim|pre nego krenem u rat.
{7422}{7552}Druûe Admirale, plovilo Êe|biti porinuto po rasporedu
{7555}{7600}pre kraja meseca.
{7603}{7679}DaÊu vam ime. Moje. Polenin.
{7682}{7741}Mihail. Kapetan, K-19.
{7745}{7774}Zapiöite ga.
{10371}{10426}Poöto uspeöno okonËate probe
{10428}{10488}na mechaniËkim, propulsionim|i navigacionim sistemima
{10491}{10525}u Beringovom moru
{10528}{10587}produûiÊete ispod leda|do lansirne zone
{10646}{10690}i izvröiti probno lansiranje.
{10838}{10950}Moja su nareenja da pripremim K-1 9 za|pomorske probe,i one Êe poËeti na vreme.
{10954}{11028}Ali dok probe ne prou
{11030}{11083}preduzeti veûbu ovakvih razmera
{11102}{11211}moûda je, uz poötovanje, prerano.
{11434}{11495}U mojoj glavi nema sumnje
{11499}{11543}da je K-1 9 spremna za njenu misiju.
{11547}{11640}Operacija ArktiËki Krug|nije obiËna veûba.
{11643}{11752}äta spreËava Amerikance|da uniöte Moskvu i Lenjingrad?
{11755}{11800}Samo jedna stvar.
{11838}{11893}Jedna spoznaja
{11897}{11962}uzvraÊenog razaranja.
{12000}{12065}K-1 9 je ta spoznaja.
{12103}{12213}Ali ne dok Kenedija njegovi öpijunski|avioni ne obaveste da je imamo
{12244}{12301}i da radi.
{12304}{12370}ObeÊao sam Drugu HruöËovu
{12371}{12472}da Êe AmeriËki predsednik dobiti|tu poruku pre kraja meseca.
{12475}{12510}Druûe Maröale
{12514}{12613}moûda bi Kapetan Polenin mogao.
{12614}{12713}Kapetan Polenin je stavio svoj brod|i ljude pre partije.
{12716}{12768}BiÊe pod vaöom komandom.
{12857}{12894}To je sve.
{14142}{14236}Kapetan na CCP.|Kapetane.
{14287}{14331}Vaöe ime, molim?|DemiËev.
{14335}{14375}Torpedni oficir, Druûe Kapetane.
{14377}{14452}Smem li upitati za Kapetanovo ime|i za svrhu njegovog prisustva?
{14455}{14551}Moje ime je Vostrikov.|Gde je Kapetan Polenin?
{14578}{14641}Uite.
{14644}{14678}Da?
{14705}{14781}Dobro jutro, Kapetane.|Druûe Kapetane Vostrikov.
{14784}{14870}To je sve, Juri. Uite. Molim.
{14999}{15052}Kapetane.
{15055}{15110}Zbog kratkog vremena uvoenja pred probe
{15113}{15181}ötab je ûeleo vaöu ekspertizu
{15182}{15237}i drago mi je da je imamo.
{15239}{15298}Znam da je moûda teöko.
{15301}{15370}Nikada nije teöko|vröiti duûnost, Kapetane.
{15426}{15505}Pripremao sam moj raport|o posadi i plovilu.
{15507}{15573}Vidim.|Problem je njeno opremanje.
{15575}{15637}Ali u nareenju je stajalo|da ne stiûete do sutra.
{15682}{15752}Raport moûe da saËeka.|Molim vas, pokaûite mi podmornicu.
{15754}{15776}Naravno.
{15970}{16039}Turbine najzad postiûu brzinu.
{16073}{16167}Sa sreÊom, mislim da bi za nedelju dana|mogli sprovesti test.
{16170}{16239}Oprema joö nije stigla,|Druûe Kapetane.
{16416}{16516}Pribeleûeno, Druûe Kapetane.|Reaktorsko odelenje.
{16913}{16972}Na koliko ga drûite?
{16974}{17023}Sada smo na 50 procenata|radi testa turbina, Kapetane.
{17058}{17126}Koji je ciklus absorpcije ötapina?
{17129}{17177}Tri procenta iznad normalnog.
{17249}{17284}Gde je oficir reaktora?
{17359}{17404}PoruËnik Jaöin?
{18004}{18069}Ovaj Ëovek je pijan. Da li vi ovo toleriöete?
{18072}{18149}Naravno da ne.|Pripremite optuûbe protiv njih.
{18152}{18220}Obavestite komandu|da nam treba zamena.
{18223}{18260}Da, Kapetane.
{18316}{18412}PoruËnik Jaöin je najbolji|oficir raktora u mornarici.
{18415}{18501}Nikada nije bio pijan na duûnosti.|Potreban nam je, Kapetane.
{18502}{18562}Savetujem vam da razmislite.
{18565}{18676}éelim ovaj brod porinut.|Probe poËinju za dve nedelje.
{18679}{18755}Brod nije spreman, Kapetane.|Problem je Moskva.
{18758}{18814}Organizuju posebne obilaske
{18817}{18879}dok se mi borimo sa nesposobnim osbljem|brodogradiliöta i loöim delovima.
{18882}{18943}Probe na moru Êe poËeti na vreme.
{18947}{19004}IspuniÊemo to ili se utopiti.
{19623}{19705}U istoriji sovjetske mornarice
{19708}{19773}nikada mornari
{19777}{19882}nisu imali takav brod kao öto je K-19.
{19914}{20003}To je najbolja podmornica na svetu.
{20006}{20079}Vama je pripala Ëast|da budete njena posada.
{20102}{20161}A meni Ëast da budem vaö Kapetan.
{20246}{20291}Bez mene
{20294}{20336}vi ste niöta.
{20491}{20558}Bez vas.
{20562}{20600}Ja sam niöta.
{20603}{20665}Mnogo se oËekuje od nas.
{20691}{20740}Mi Êemo uspeti.
{21770}{21793}Prokleti smo.
{21922}{22002}Lagano, lagano. Drûi ga jednako.
{22030}{22067}Polako!
{22070}{22115}Sada, dole. Dole.
{22272}{22327}Prolaz.|Dozvolite da proem.
{22329}{22403}äta vam je to?|Novi niöan za sonarno postrojenje.
{22407}{22479}Produûi. Montiraj ga.|Ja radim na reaktoru.
{22510}{22585}Gde je oficir sonara?|On ima 24-Ëasovni dopust.
{22588}{22684}Kapetane, inicirao sam rotaciju za odmor.
{22687}{22739}To je dobro za efikasnost.|Nma viöe propusnica. Otkaûite sva odsustva.
{22743}{22832}Potrebni su nam svi ovde.|Da, Kapetane.
{22835}{22872}Druûe Kapetane.
{22874}{22962}PoruËnik Vadim RadtËenko|se javlja na duûnost.
{22990}{23047}Ja sam vaö novi oficir reaktora.
{23123}{23152}Koja vam je poslednja komanda?|Akademija za niklearnu obuku.
{23154}{23210}Koja vam je poslednja komanda?|Akademija za niklearnu obuku.
{23236}{23298}Nikada nije rukovao reaktorem na moru.
{23299}{23342}Bio sam prvi u klasi.
{23371}{23405}Hvala.
{23408}{23480}Javite se u kontrolnu salu reaktora.|Da, gospodine.
{23507}{23570}Tuda.|Hvala.
{23611}{23673}Kapetane.|On je kvalifikovan
{23676}{23741}inaËe nam ga komanda|nebi poslala.
{23788}{23837}Oficir na palubi.
{23857}{23926}Pavel Loktev, stariji tehniËar.
{23929}{24005}Stepan Komarov, Anatolij SubaËev,
{24008}{24080}Grigori Djomin, Oleg Argunov.
{24084}{24128}Pokaûite mi komandnu sobu.
{25201}{25270}Pazi! Moram da zaustavim kamion.
{25300}{25345}Dali su mi pogreöne lekove!
{25459}{25503}Zaustavite kamion!
{25596}{25646}Stani! Stani!
{25648}{25688}Pogreöni lekovi!
{25692}{25767}Dao si mi pogreöne lekove!
{25784}{25821}Idiote! Stani!
{26008}{26048}Doktor!
{26051}{26096}To je doktor!
{26392}{26415}Mrtav je.
{26487}{26539}Ostanite sa telom dok|ne doe hitna pomoÊ.
{26542}{26605}Vi ostali, nazad na posao.
{26668}{26714}Nazad na posao!
{26855}{26898}Gavril.
{27210}{27286}Kapetane. Odkada smo|ukrcali Ëvrsti balast
{27289}{27334}imamo naginjanje pola stapena napred.
{27337}{27386}Sve sam probao,|ali neÊe da se izjednaËi.
{27434}{27493}Pola stepena moûemo izdrûati.
{27495}{27589}KompenzovaÊemo balastom od slane vode|dok se nevratimo u luku.
{27592}{27643}Ako se vratimo u luku.
{27701}{27780}Znate li kako posada zove ovaj brod?
{27783}{27829}Crna Udovica.
{27832}{27883}Petorica su se uguöila vareÊi rezervoare.
{27886}{27947}Joö Ëetvorica pri konstrukciji.|A sada doktor.
{27949}{27995}Flaöa öampanjca.
{28028}{28058}Deset mrtvih
{28061}{28109}a nismo ni napustili pristaniöte.
{28112}{28187}Iznenauje me da poveravaju svoje strahove|svom stareöini.
{28240}{28311}Posada je porodica.|Kapetan je otac.
{28342}{28425}Moj otac je inspirusao viöe straha|nego öto se on plaöio.
{28503}{28599}ReËeno mi je da postoje dve verzije|priËe o vaöem ocu.
{28644}{28706}Prva, da je bio heroj revolucije.
{28707}{28754}Druga, da je umro u gulagu.
{28792}{28840}Obe su taËne.
{28880}{28974}Kako idu te provere bezbednosti|dole, Kapetane?
{28977}{29011}Napreduju.
{29084}{29131}Miöa, Miöa.
{29159}{29207}Eto vidiö.
{29210}{29285}40 centimetara mesta za glavu,|a on pola da glodaru.
{29309}{29343}Jevgeij
{29344}{29391}obmotaj ovo oko privatnih delova.
{29392}{29439}Gama zraci mogu da.
{29488}{29549}Treba takoe da nosiö dozimetar|svaki dan kod doktora.
{29553}{29581}äto?
{29584}{29674}On ga proËita i kaûe ti koliko ti je ostalo vremena|pre nego ti otpadne torpedo.
{29961}{29982}Kapetane?
{30053}{30113}Ja sam Genardi Savran,|vaö novi oficir saniteta.
{30116}{30235}Gde ste pre sluûili?|Ne. Ja sam lekar ovde u bazi.
{30236}{30303}Rekli su da je hitno.|I tako eto me.
{30305}{30362}Dobrodoöli na K-19, Doktore.
{30363}{30452}Kapetane, brzo se vraÊamo, zar ne?
{30472}{30529}Ja dobijam.|äta?
{30531}{30586}Morsku bolest.
{30589}{30656}Gospodo. Gospodo.
{30658}{30711}Miöo, molim te.
{30713}{30787}Vostrikov se oûeni curom.|Juri, ObeÊao si. ObeÊao si.
{30791}{30891}Vostrikov se oûeni curom|koja ima jake partijske veze.
{30894}{30961}Zna koja se viljuöka koristi za salatu,|pa su ga postavili za Kapetana.
{30963}{31041}Zato ti nikada nisi unapreen.|Umukni.
{31044}{31117}Mi smo ovde svi dobri komunisti.
{31157}{31226}Predobri komunisti.|Predobri komunisti!
{31329}{31445}Pijan si. Sedi dole. Sedi.|Gospodo, malo poötovanja.
{31448}{31546}Kapetan Vostrikov vas|ne poznaje kao ja.
{31549}{31621}Vi ste i dalje Kapetan,|öto se nas tiËe.
{31624}{31679}On jee Kapetan.|Ja sam izvröni oficir.
{31682}{31747}SreÊan sam. BiÊu sa mojim momcima.
{31751}{31784}Moj red.
{31817}{31939}Kaûu da je bio kaosmonaut|koji je obiöao Zemlju pre Juri Gagarina.
{31963}{32022}Ali nije bio dovoljno lojalan
{32025}{32064}da zadrûi dah
{32067}{32149}kada je ostao bez vazduha.
{32152}{32194}I sada
{32197}{32242}nikada nije postojao.
{32289}{32359}Gagarin je imao sreÊe.
{32362}{32424}Nadajmo se da Êemo je i mi imati.
{32427}{32479}Za sreÊu!|Za sreÊu!
{32852}{32875}Kataja!
{33373}{33424}Ne brini.|Ne idi.
{33550}{33572}Molim te.
{33873}{33949}Ministre Odbrane Zolentsov,|Admirale Bratjev
{33952}{34038}traûimo odobrenje da izvröimo nareenja|za odbranu otadûbine.
{34041}{34103}Izvröite svoju patriotsku duûnost.
{34181}{34238}Svi dole.|Svi dole!
{34466}{34524}Izdvojte sve veze.|Izdvojte sve veze.
{34525}{34576}Izdvojte sve veze!|Potvrdi izdvajanje!
{34580}{34624}Spusti stazu.
{34628}{34665}Spusti stazu!
{34668}{34718}Staza spuötena!
{34720}{34768}Staza spuötena!
{34771}{34867}K-19 spremna za more, Kapetane.|Prednjom turbinom, polako napred.
{34868}{34916} Prednjom turbinom, polako napred.
{34917}{34971}Polako napred zajedno!
{35303}{35361}Samo se nadam da smo odabrali pravog Ëoveka.
{36746}{36851}Sva odeljenja spremna za zaranjanje.|Gornji poklopci zatvoreni i osigurani.
{36853}{36936}Otvorite srednji ventil.|Srednji ventil otvoren.
{36938}{37005}Spremni za zaranjanje, Kapetane.|Zaronite.
{37008}{37083}Brzina 6 Ëvorova.|Neka dubina bude 50 metara.
{37087}{37138}Brzina 6 Ëvorova.|Planer, neka dubina bude 50 metara.
{37141}{37196}Pripremam za dubinu 50 metara.|Polako napred zajedno.
{37199}{37258} Polako napred zajedno.
{37261}{37323}Kurs?|Kurs je 3-2-3, Kapetane.
{37324}{37408}Dubina ispod kobilice.|Ehograf oËitava 350 metara, Kapetane.
{37707}{37728}20 metara.
{38211}{38246}30 metara.
{38298}{38372}Ne brinite. PrestaÊe|kada se pritisak izjednaËi.
{38411}{38506}Simulirajte elektriËni poûar|u menzi, molim.
{38602}{38664}Poûar u kutiji sa prekidaËima br.65.
{38667}{38716}Ovo je veûba. Ponavljam. Ovo je veûba.
{38718}{38753} Ovo je veûba. Ponavljam. Ovo je veûba.
{38948}{39010}Zaglavio se.
{39013}{39048}50 metara.
{39051}{39133}Poûar se proöirio na|sledeÊe odelenje.
{39136}{39206}Simulirajte elektriËni kvar,|odelenje 4.
{39267}{39319}ElektriËni kvar, odelenje four.| Ovo je veûba.
{39322}{39380}Odelenje 4,|gubitak elektriËne energije.
{39383}{39477}Ovo je veûba.|PomoÊna svetla. Hajdemo.
{39592}{39655}Vatra u menzi ugaöena, Kapetane.
{39704}{39771}Previöe ötete.|Previöe povreenih.
{39775}{39901}Simulirajte plavljenje, odelenje 4.|Neka rade u mraku.
{40248}{40293}Da ovo nije veûba
{40296}{40354}plovilo bi bilo onesposonljeno|a pola posade mrtvo.
{40358}{40454}Pustite da popriËam sa nadleûnim oficirom.|Probajte ponovo sura.
{41060}{41122}Samo sam ûeleo da kaûem
{41125}{41239}koliko razumem smenu u komandi.
{41242}{41343}Ove odluke nisu uvek|razumljive za nas.
{41366}{41413}Hvala vam, Druûe Suslov.
{41415}{41502}Ipak, sigurno oseÊate da je Ëast
{41504}{41552}sluûiti na ovom brodu u bilo kom kapacitetu.
{41589}{41671}Zaista.|Istorijski je.
{41766}{41798}Izvinite me.
{41973}{42018}Proveravate zadnji davaË pritiska?
{42042}{42075}Da, PoruËniËe.
{42123}{42168}Znaö da su religiozne relikvije zabranjene.
{42394}{42439}Ovo je buduÊnost, Pavel.
{42442}{42559}Kola kojima ne treba dopuna.|Besplatna struja za svaku porodicu.
{42560}{42631}Moûda i putovanje na druge planete.
{42635}{42693}Privilegija je biti deo ove buduÊnosti.
{42717}{42741}Da, PoruËniËe.
{43921}{43958}Dobro jutro, gospodo.
{44140}{44212}äta je ovo?|Na moru se tuöiramo samo subotom.
{44215}{44285}Svi na svoja mesta. Hemijska vatra|u motornom odelenju.
{44311}{44350} Ovo je veûba.
{44377}{44404}Pazi!
{44589}{44648}Poûar na glavnoj centrali. C2 L.
{44720}{44754}Pukao je ventil u odelenju 8.
{44830}{44888}Torpedno gorivo se izlilo u torpednoj sobi.
{45080}{45114}Ponovite veûbu.
{45779}{45858}Drugovi, oficiri i mornari,|zapamtite
{45861}{45946}da Êe AmeriËka propaganda|uvek pokuöati da igra na kartu
{45947}{45947}da Êe AmeriËka propaganda|uvek pokuöati da igra na kartu
{45950}{46008}vaöih osnovnih, primitivnih nagona.
{46009}{46081}Pohlepe, poûude, individualizma.
{46113}{46170}U AmeriËkoj propagandi,|videÊete kako svi
{46173}{46243}imaju kola, lepa odela,|lepe stanove
{46246}{46325}ali nikada neÊete videti|istinu iza ove laûi.
{46328}{46420}NeËete videti policijske pse kako|napadaju ötrajkaËe ili demonstrante.
{46421}{46503}NeÊete videti prosjake|na ulicama, baskuÊnike.
{46506}{46538}CrnaËke straÊare na jugu.
{46541}{46606}NeÊete videti ratne huökaËe
{46609}{46664}koji prete svetu|sa nuklearnim holokaustom.
{46783}{46887}Spremite se za simulaciju|ispaljivanja torpeda br.8.
{46890}{46948}Broj osam nije puna, Kapetane.
{46952}{46984}Znam to.
{46987}{47069}HoËu da iz 7 prebacite u 8.
{47103}{47134}Sada, molim.
{47137}{47171}Kapetane.
{47199}{47264}Formacije leda na naöoj dubini.
{47267}{47316}Predelaûem da odemo dublje|i veûbu odgodimo za kasnije.
{47319}{47438}Negativno. Led neÊe|mirovati za vreme rata.
{47466}{47529}Istovari torpedo iz 7.|Prebaci u 8.
{47532}{47610}istovari torpedo iz 7.|Prebaci u 8. Ovo je veûba.
{47654}{47688}HoÊe li ikada prestati?
{47690}{47755}Potreban nam je odmor.|Jeveski, tiöina.
{47758}{47830}Svi na svoja mesta odmah.
{47833}{47867}Hajde!
{47953}{47988}UkljuËite opremu.
{48016}{48063}Torpedo povuËeno.
{48094}{48132}Otvorite vrata osmice.
{48160}{48194}Prenesite torpedo.
{48276}{48321}Prenesite torpedo.
{48385}{48437}Dmitri! Hajde. Pomozi mi. Pomozi mi!
{48561}{48591}Ne prekidaj!
{48794}{48862}Dvojica su povreeni.|Neka ih doktor pregleda
{48865}{48902}a veûbu ponovite izpoËetka.
{48934}{48992}Fale nam dvojica, Kapetane.|Neka vrate torpedo
{48993}{49099}nazad u cev 7 i ponovite veûbu.
{49177}{49212}Prenesite torpedo!
{49214}{49262}Prenosimo torpedo!
{49338}{49398}Idemo ispod. Razlaz.
{49462}{49503}Paûnja!
{49541}{49569}Lagano.
{49624}{49694}ReËeno mi je da ima nekih prituûbi.
{49736}{49804}Ali rekao sam, "Ne moji ljudi.
{49805}{49877}Oni su najbolja posada u floti.
{49880}{49945}TrpeÊe do poslednjeg."
{49946}{49986}Dakle
{49989}{50045}ima li prituûbi?
{50073}{50111}Ovde ih nema, Kapetane.
{50164}{50207}OdliËno.
{50295}{50373}Nije krivica ljudi.
{50374}{50423}Krivica je vaöa.
{50426}{50497}Vas oficira.
{50498}{50559}Niste uspeli da postavite visoke standarde
{50563}{50618}da isptavite njihove nedostatke.
{50662}{50759}Ako vi obavite svoje, i oni Êe obaviti svoje.
{50810}{50860}To je sve.
{51232}{51324}Kako se zove?|Kataja.
{51482}{51516}Lepa je.
{51653}{51685}Lepa je.
{51735}{51796}Izvini.|Piöem joj.
{51797}{51907}Odakle Êeö poslati?|To je u sluËaju da umrem.
{51910}{51963}U sluËaju da umreö?
{52222}{52267}U sluÊaju da umrem.
{52977}{53045}Raport Kapetanu.|8km. od zone lansiranja.
{53048}{53093}Idemo pre roka.
{53319}{53364}Dobro jutro, gospodo.
{53385}{53447}Kurs kormila, 1 -8-5.
{53450}{53482}1 -8-5.
{53560}{53593}Kapetane.
{53639}{53673}Kapetane.
{53676}{53735}Izvedite veûbu hitnog zaranjanja.
{53738}{53796}Povröine luka su blokirane 20 stepeni dole.
{53797}{53906}Povröine luka su blokirane 20 stepeni dole.|Podeöeno. 20 stepeni dole.
{54015}{54091}Povröine luka su blokirane 20 stepeni dole.|Preuzeo komandu.
{54173}{54194}Mrdaj!
{54458}{54490}120 metara.
{54646}{54691}130 metara.
{54737}{54791}140 metara.
{54879}{54924}150 metara.
{54983}{55065}Zaronite na maksimalnu|operativnu dubinu.
{55117}{55175}Neka dubina bude 250 metara.
{55178}{55246}Turbine polako napred zajedno.
{56107}{56139}240 metara.
{56217}{56252}250 metara.
{56255}{56330}Kapetane, uz duûno poötovanje,|zaranjanje ispod 250 metara
{56333}{56372}je nepotreban rizik.
{56375}{56420}Nastavite zaranjanje do 300 metara.
{56446}{56499}300 metara je blizu dubine smrskavanja.
{56526}{56550}Znam.
{56683}{56718}260 metara.
{56765}{56817}Neka bude 300 metara.
{57170}{57225}280 metara.
{57304}{57356}290 metara.
{57610}{57648}300 metara, Kapetane.
{57699}{57744}IzjednaËite ravni.|IzjednaËite ravni pramca.
{58388}{58446}Simulirajte poplavu|u pozadinskoj torpednoj sobi
{58449}{58504}i hitno izranjanje.
{58508}{58572}Brzo izranjanje ispod leda|nije preporuËljivo, Kapetane.
{58607}{58653}Nisam nikoga pitao za savet.
{58820}{58869}Poplava u odelenju 10.|Hitno izranjanje.
{58891}{58950}Kreni, kreni, kreni, kreni, kreni!
{58974}{59016}Svi na svoja mesta!
{59087}{59157}Polianski, dovedi ravni|do punog izranjanja. Drûi 10 dignutom.
{59159}{59215}Zaokreti za 20 Ëvorova.|Punim napred zajedno.
{59218}{59317}Povröine do punog izranjanja. Punim napred|zajedno. Drûim 10 dignutom. Brzina 20 Ëvorova.
{59563}{59608}Pavel, klin!
{59680}{59733}Umiri ga! Kreni!
{59935}{59976}Kreni! Kreni! Kreni!
{60191}{60271}Pukotina zapeËaÊena, Kapetane.|Izvrsno.
{60274}{60332}PreporuËujem da ostanemo|na bezbednoj dubini, Kapetane.
{60408}{60463}Koliko je ovde debeo led?|Kornilov.
{60466}{60514}Izveötaj o ledu.
{60517}{60617}Ajde. Ajde.|Manje od metra u ovoj oblasti.
{60686}{60760}Ovi su izveötaji skoro nedelju stari.|U ovo doba godine
{60763}{60820}led je samo tanji.|Nastavite izranjanje.
{60823}{60880}Nisam siguran da moûemo da kontroliöemo uzdizanje|koje ide ovom brzinom, Kapetane.
{60935}{61004}Nisam ni ja.|130 metara.
{61076}{61110}120 metara.
{61213}{61274}110 metara.|Izbacite glavni balast.
{61408}{61498}PoËinje da se okreÊe.|Dozvola da ostanemo na sigurnoj dubini.
{61501}{61554}UskraÊena.|80 metara.
{61557}{61604}Pumpno odelenje,|pumpamo li rezervoare za podeöavanje?
{61608}{61636}OkreÊe se ka napred.
{61800}{61882}Izbaci prednji. Zatvori zadnji.|Prebacujem na rezervu vazduha.
{61885}{61938}60 metara.|Zaustavi turbine.
{61941}{61971}Zaustavi obe turbine.
{62016}{62075}IzjednaËi, prokletstvo.|40 metara.
{62119}{62174}Spremite se za udar.|Spremite se za udar!
{62177}{62222} Spremite se za udar.
{63977}{64022}Preuzmi kontrolu.
{64056}{64136}Izvucu radio i radar.
{64139}{64184}Napravi tri prelaza.|Srednjeg dometa.
{64876}{64933}Pripremite se za ispaljivanje test projektila.
{65205}{65325}Pripremite se za ispaljivanje test projektila.|Ovo nije veûba.
{65478}{65527}Centralna komanda,|raketna komanda prisutne i spremne.
{65531}{65592}Pripremamo silos br.3 za probno lansiranje.
{65709}{65756}UkljuËite konzole za lansiranje.
{65980}{66025}Lansirna vrata broj tri se otvaraju.
{66591}{66672}Druûe Kapetane, Moskva potvruje|odobrenje za lansiranje.
{66913}{66991}Paûnja! Iniciranje|procedure napajanja, Kapetane.
{66994}{67028}Uredu.
{67332}{67375}Punjenje u toku.
{67427}{67482}Simulirajte aktiviranje bojeve glave,|rakete broj tri.
{67581}{67630}Hajde krenimo. Hajde.
{67687}{67722}Kontakti?|Nema kontakata.
{67742}{67779}Radar, sonar. Kontakti?
{67781}{67845}Nema kontakata.
{68061}{68140}Punjenje kompletno. Ravni izjednaËene.|Spremni za sekvencu ispaljivanja.
{68179}{68212}Ispaljivanje rakete br.3.
{68270}{68305}Vreme do lansiranja:
{68308}{68347}15 sekundi.
{68349}{68397}1 4, 1 3, 1 2...
{68401}{68465}1 1, 1 0, 9...
{68467}{68510}8, 7...
{68514}{68575}6, 5...
{68578}{68619}4, 3...
{68621}{68679}2, 1.
{69514}{69567}Potvrujem lansiranje, Kapetane.
{69724}{69759}»estitam, Druûe Kapetane.
{69762}{69828}Upravo smo upisali svoja imena|u istoriju.
{69885}{69910}Kapetane.
{69913}{69971}potvrujem uspeöno lansiranje|komandi flote.
{69974}{70003}Da, Kapetane.
{70094}{70125}Govori vam Kapetan.
{70128}{70208}Uspeöno smo lansirali|naöu test raketu.
{70209}{70260}Svo osoblje neka|odstupi sa borbenih poloûaja.
{70263}{70307}Ura!
{70591}{70656}NaÊiÊete se u mom izveötaju|jer ste napustili svoj poloûaj.
{70658}{70697}A vi Êete biti u mom.
{70722}{70791}Nepotrebno ste ugrozili ovo|plovilo i njegovu posadu.
{70794}{70894}200 miliona Sovjetskih graana|zavisi od nas, Kap. Vostrikov
{70897}{70962}da ih saËuvamo od nuklearnog napada.|Ugrozili ste i njih.
{70966}{71035}Doveo sam ovaj brod i njegovu|posadu do ivice
{71038}{71110}jer smo morali da saznamo gde je ta granica.
{71113}{71200}Ovih 120 su sada posada|postigli su neöto zajedno
{71203}{71260}öto nisu mislili da mogu.
{71261}{71328}SledeÊi put, kada to nebude veûba
{71330}{71402}oni Êe doÊi do ivice, preÊi je|i umreti, ako zatreba
{71405}{71477}jer to je ono öta|njihova duûnost traûi.
{71562}{71637}Imali ste sreÊe, Kapetane, ovoga puta.
{71640}{71707}Nadam se da Êu biti na drugom brodu|kada bez nje ostanete.
{73151}{73243}Miöa, Jeljtsine, doite, brzo. Svi.
{73273}{73373}Sklonite veö odatle.|Obrazujte grupu oko zastave.
{73428}{73492}Sklonite veö odatle.
{73494}{73596}Branan, Jel¥ spavaö?|Odmah. Primakni se.
{73675}{73749}Svi se pomerite, da.
{73781}{73839}Bliûe. Bliûe.
{73842}{73919}Priite bliûe.
{73922}{73972}PobedniËki tim bliûe.
{74051}{74092}Osmeh.
{74244}{74264}Dobro.
{75262}{75345}Da li je sve uredu? Problemi?
{75462}{75567}Da. Ima zaostale kondenzacije|u odelenji reaktora.
{75570}{75615}Ali iskljuËio sam generator broj 3
{75618}{75695}i to bi tebalo da smanji kondenzaciju.
{75698}{75745}RaËunam na tebe, znaö?
{75780}{75811}Da, Druûe Kapetane.
{75849}{75939}Druûe Kapetane.|Poruka od komande.
{76185}{76264}Druûe Komandante, posada|je postrojena po vaöoj naredbi.
{76291}{76360}Primili smo poruku|od Moskve.
{76363}{76463}»estitaju nam uspeöno|lansiranje rakete.
{76466}{76551}Dokazali smo svoju spremnost.|SluûeÊi Sovjetski Savez!
{76554}{76614}A sada nam ukazuju Ëast|novim zadatkom.
{76641}{76753}K-19 treba da preuzme patroliranje|istoËnom obalom.
{76757}{76798}Sjedinjenih Drûava.
{76827}{76926}Ovo je misija od|strateöke vaûnosti.
{76929}{77005}Plovilo Êe doÊi|u potpunu borbenu gotovost.
{77032}{77113}UËinite sve u svojoj moÊi. Niöta manje ne oËekujem.
{77163}{77223}Posada voljno!
{77293}{77346}Zamalo da nas ubije danas.
{77381}{77429}A za öta?
{77432}{77530}Da bi dokazao da nije dobio Ëin|oûenivöi se neÊakom Politbirovca.
{77734}{77793}Ti si nam joö uvek Kapetan, Miöa
{77837}{77895}i jedini kome verujemo.
{78023}{78082}Kapetane Polenin?|Da.
{78085}{78143}Kapetan Vostrikov ûeli da vas vidi|u sobi sa kartama.
{78146}{78178}Da.
{78547}{78626}Komanda ûeli da se postavimo|öto je pre moguÊe.
{78675}{78770}Naö kurs nas vodi pored|NATO baze Jan Mayan
{78774}{78842}i odatle do patrolne zone
{78843}{78898}400 kilometara od obale
{78901}{78938}izmeu Vaöingtona
{79007}{79054}i Njujorka.
{79175}{79248}Zaokrenite za 1 5 Ëvorova.|Brzina 1 5 Ëvorova.
{79251}{79296}Brzina 1 5 Ëvorova.
{79401}{79480}Nema kontakata. Dole periskop.|Spuötam periskop.
{79573}{79606}Zaronimo.
{80158}{80204}Andrej, joö vina.
{80207}{80259}Dobijate samo jednu Ëaöu.
{80262}{80317}Ali poöto smo mi krem druötva
{80320}{80365}Êaöa crvenog vina za veËerom
{80368}{80488}je naËin komande da pokaûe|kako posada K-19 nema ravne.
{80492}{80574}Ne. Nego zato öto sedimo|na gomili uraniuma.
{80577}{80636}Crveno vino daje stroncium
{80639}{80686}ili ga oduzima.
{80687}{80749}Ili tako neäto. Neöto dobro.
{81256}{81332}Dakle, biÊemo 115 kilometara
{81335}{81408}od Jan Mayan NATO baze.
{81445}{81502}Jedna planina. Nema drveÊa. 15 ljudi.
{81526}{81588}Jedna radio stanica.
{81590}{81650}Video sam to ostrvo|toliko puta periskopom.
{82624}{82658}äta nije uredu?
{82723}{82768}Nedostaje ni drveÊe
{82771}{82854}sunce, zvezde.
{82858}{82913}NaviÊiÊeö da budeö pod vodom.
{82967}{83019}Kada zavröim
{83022}{83095}radiÊu u rudniku uglja|sa mojom braÊom.
{83232}{83280}Tako da je meni svejedno.
{84397}{84449}Gubitak pritiska na sklopki|zadnjeg reaktora.
{84452}{84493}Proveri druge senzore.
{84634}{84668}Potvrujem gubitak pritiska.
{84816}{84864}Propustite me!|Pazi!
{84867}{84921}Curi!|Daj mi priruËnik za hitne sluËajeve.
{84973}{85039}Hajde!|PoruËniËe.
{85042}{85089}Primetio sam da pumpe vuku|previöe energije
{85091}{85183}tokom testa turbine, ali|nisam mislio da je ozbiljno.
{85327}{85381}Skloni mi se sa puta!
{85385}{85426}Mrdaj!
{85553}{85610}Kontrolni ötapovi propadaju,|PoruËniËe.
{85652}{85711}PomoËne pumpe.|Pavel, pomoÊne pumpe.
{85823}{85878}Ni pumpe ne rade.|Obnovite ih!
{85881}{85954}Jesam, ali pritisak i dalje opada.
{86005}{86041}Potvrujem.
{86044}{86095}Ali ötapovi Êe ga ohladiti, Zar ne?|Ne.
{86098}{86174}Nemogu da se ohlade sami|od sebe. Treba im rashlaivaË.
{86177}{86248}PoruËniËe, temperatura jezgra|je 400 stepeni i raste.
{86250}{86297}Prekini izjednaËavanje!
{86660}{86701}U Ëemu je problem?
{86704}{86760}Primarni Ëvor rashlaivaËa|na zadnjem reaktoru je pukao.
{86763}{86852}äta? Kako se to desilo?|Kakve to veze ima?
{86855}{86921}Odgovori mi. Kako?|Ne znam, Kapetane.
{86924}{86970}Jezgro se zagreva.|Misija je zavröena.
{86973}{87047}Ja Êu vam reÊi|kada misija bude zavröena.
{87049}{87089}Ko je odgovoran za ovo?|HoÊu ime.
{87093}{87181}HoÊete ime? DaÊu vam|ime Vostrikov, Aleksej.
{87184}{87248}Pripazite, Druûe.|A imam joö jedno ime
{87251}{87285}RadtËenko, Vadim.
{87288}{87361}Neprovereni oficir reaktora|koga ste vi postavili.
{87710}{87767}PopraviÊemo ovaj problem.
{87769}{87816}NastaviÊemo misiju.
{87957}{88023}NA povröinu. Izranjaj na povröinu!|Izranjaj na povröinu.
{88468}{88540}Koliko je loöe?|Pukotina je u zapeËaÊenom delu.
{88601}{88646}Ne moûemo joj priÊi.
{88695}{88786}Temperatura Êe nastaviti da raste|dok ne dostigne 1,000 stepeni.
{88789}{88831}I.|I?
{88872}{88951}I öta?|Niko nezna.
{88995}{89054}Moglo bi zapoËeti lanËanu reakciju.
{89057}{89102}Iscurela bi radijacija.
{89105}{89156}Jezgro bi probilo do reaktora
{89158}{89212}i zapoËelo termonuklearnu|eksploziju.
{89400}{89479}Koliko imamo?|Tri ili Ëetiri sata.
{89513}{89561}Moûda manje.
{89701}{89791}Uzmi sve öto ti treba,|bezobzira na Ëin.
{89794}{89864}I reöi ovo.|Da, Druûe Kapetane.
{89887}{89976}Reöi ovo. Zato si|ovde, razumeö?
{89980}{90031}Diûi se!
{90034}{90083}Diûi se!
{90086}{90134}Diûi se!
{90162}{90229}Zar mu veûbe nikada ne dosade?
{90257}{90302}Kreni! Kreni!
{90655}{90700}Govori vam Kapetan.
{90725}{90783}Imamo kvar na reaktoru.
{90817}{90881}Preduzimamo mere da|ispravimo ovu situaciju.
{90926}{90974}Ostanite na svojim mestima.
{91101}{91172}ProËitajte.|"U sluËaju iznenadnog pada
{91174}{91228}pritiska u|primarnom vodu
{91229}{91310}moraju se preduzeti mere da se smanji|suprotstavljanje ispuötanju toplote."
{91313}{91395}Ali to neradi.|Ventil nije tu.
{91397}{91481}Kakve mere?|Nema ih. Uzaludno je.
{91484}{91536}Ostatak je o pomoÊnom sistemu,|koji nikada nije ugraen.
{91537}{91636}Kada se izdignemo do nivoa periskopa,|moram da kontaktiram komandu flote.
{91639}{91680}Da, Druûe Kapetane.
{91938}{92003}Zaöto ne bi jednostavno|iskljuËili reaktor?
{92006}{92082}IskljuËili smo ga, ali|ne moûemo da kontroliöemo reakciju.
{92085}{92144}A da upotrebimo prednji reaktor|reaktor?
{92147}{92233}Mogli bi da prepoveûemo pumpe.|Pa da ohladimo oba.
{92236}{92297}Pukotina reaktora nije dostupna.
{92299}{92345}Stoga, ne moûamo da zatvorimo|pukotinu
{92347}{92393}imao bih dva reaktora van kontrole.
{92419}{92497}Dakle moramo da ohladimo reaktor.
{92532}{92597}Traûim dozvolu da se obratim, PoruËniËe.|Naravno.
{92648}{92720}Rashladno sredstvo je samo|destilovana voda.
{92757}{92847}A mi imamo 30 tona|sveûe vode na brodu.
{92850}{92891}Da.
{92894}{92970}Ali kako je dovesti do jezgra?|Dodajte öemu.
{93871}{93947}Treba mi veza sa|komandom flote. Odmah.
{93950}{93982}Pokuöavam, Kapetane.
{94009}{94078}Cevi ventilacije mogu da dovedu|rashladno sredstvo do jezgra.
{94081}{94153}Moûemo da preseËemo ventil|i upumpamo sveûu vodu.
{94156}{94202}Imamo 30 tona, Kapetane.
{94245}{94291}Imamo jake cevi kod torpeda.
{94294}{94345}Nemamo dovoljno za varenje.|Najviöe pola sata.
{94370}{94442}I ako ne popravimo?|Hiroöima.
{94445}{94551}1.4 megatona, ako uraËunamo dva|reaktora i bojeve glave.
{94554}{94602}Samo Hiroöima je bila manja.|Mnogo manja.
{94606}{94681}Napustite brod.|Poöaljite posadu u Ëamce.
{94809}{94918}NeÊemo ga napustiti.|Uzimajte cevi.
{94921}{95003}BiÊemo spremni da krenemo kada|stigne odobrenje. Kreni!
{95592}{95655}Jeste li kontaktirali komandu flote?|No, Druûe Kapetane.
{95733}{95813}Kapetane, dalekometna antena|je pregorela.
{95816}{95878}Mora da je naprsla|kada smo izranjali.
{95916}{95991}Koliki je domet pomoÊnog|transmitera, 90 kilometara?
{95992}{96090}Do 100 kilometara, Kapetane.|Temperatura jezgra 490 stepeni.
{96441}{96496}To je to.|Preuzmi, Dmitri.
{96640}{96687}Ja Êu preuzeti, Kapetane.|Preuzmi.
{96745}{96793}Pobrini se da krhkotine|ne upadnu u cevi.
{96913}{96976}Gde je testera?|Molim vas za vaöu paûnju.
{96979}{97020}Ljudi, sluöajte.
{97116}{97191}OdluËio sam da Êe reaktorska jedinica|poËeti popravke.
{97192}{97270}KrenuÊete u timovima od dvojice.|10 minuta, maksimum.
{97273}{97328}Ja Êu iÊi sa prvim timom.|Ne.
{97332}{97380}Potreban mi je moj izvröni oficir|da komanduje.
{97383}{97452}Ali sa obzirom na situaciju.|Svestan sam situacije.
{97455}{97554}Ne dolazi u obzir.|Ja Êu iÊi sa prvim timom.
{97627}{97722}To je moja duûnost.|Ja sam spreman da sluûim.
{98000}{98075}Ti Êeö iÊi sa treÊim timom|da ispitaö popravku.
{98107}{98158}Da, Druûe Kapetane.
{98185}{98240}To je sve. Nastavite.
{98720}{98762}Brzo! Dajte neöto!
{98782}{98878}Brzo.|Curi gorivo kod torpeda!
{98898}{98950}Dobro je.
{99153}{99207}äefe.|Alat.
{99365}{99412}Sistem dovoda goriva izolovan!
{99413}{99491}Ispraznite ventilacioni rezervoar.|Imam 3 metra ovde.
{99601}{99646}Meso.
{99649}{99722}Samo meso otpada sa kostiju.
{99757}{99827}Lepo i mekano.|Topi se u ustima.
{99828}{99924}Valjuöci.|Dmitri voli valjuöke.
{100059}{100100}Temperatura reaktora?
{100139}{100185}530 stepeni.
{100220}{100288}Koliko?|Oko 15 minuta, Kapetane.
{100291}{100328}Dobro obavljeno.
{100331}{100380}Druûe Kapetane?|Da?
{100384}{100442}Naöa oprema je spremna|i spremni smo da uemo.
{100445}{100486}Imamo par minuta.|Vodite ljude gore.
{100490}{100556}Dajte vazduha.|Hvala. »uli ste ga.
{100559}{100606}Dajte vazduha.
{100648}{100702}Kreni, kreni.|PoruËniËe.
{100740}{100819}Kreni.|Trebao sam da se oûenim.
{100857}{100890}I hoÊeö.
{100918}{100953}I hoÊeö.
{101141}{101203}Kosa ti otpadne, ili tako neöto.
{101204}{101306}NeÊe biti tako straöno.|10 minuta nije niöta.
{101375}{101423}Joö sat vremena i naöa smena|bi se zavröila.
{101516}{101554}To je sudbina.
{101780}{101852}Nemamo odela za radijaciju.|Nije bilo u magacinu.
{101855}{101895}Dali su nam|hemijska odela umesto njih.
{101898}{101982}Onda mogu da nose i kiöne mantile!|Miöa, znam.
{102191}{102236}Reci ljudima da Êe ovo pomoÊi.
{102239}{102287}äta drugo moûemo?
{102290}{102325}Da.
{102561}{102616}Samo deset minuta.|Deset minuta.
{102619}{102684}UËini öto moûeö a onda izlazi.|Uredu, Anatolij?
{102747}{102802}Uredu?|Da.
{102931}{102986}BiÊe uredu.|Kapetane.
{103152}{103188}Ljudi.
{103230}{103285}Teûak je zadatak pao na vas.
{103352}{103397}Naöa sudbina je u vaöim rukama.
{103400}{103490}Traûim dozvolu da izvröim|popravku reaktora, Druûe Kapetane.
{103493}{103522}Imate dozvolu.
{107981}{108025}Koja je temperatura jezgra?
{108079}{108122}725 stepeni.
{108495}{108561}Ulazim u vazduönu komoru.
{109250}{109302}Hajde. Polako.
{109352}{109403}Kako je unutra?
{109530}{109597}Doktore. Doktore.|Vodi ih do torpeda na pramcu.
{109600}{109657}Drûite ih öto je dalje|moguÊe od radijacije.
{109835}{109891}Kako se oseÊaö?|Uredu je.
{110524}{110578}Dobro. Dobro.|Dajte mi njegov dozimetar.
{110613}{110648}Hvala.
{110892}{110973}Njegov nivo radijacije|je nizak, Doktore. Jel¥da?
{110976}{111022}Da, naravno.
{111065}{111126}Izveötavajte me o njihovom stanju,|u roku od sat vremena.
{111215}{111282}Dobre vesti, Anatolij.|Dobio si blagu dozu.
{111312}{111405}Uredu. Uredu.|Lagano.
{111408}{111487}Vreme je.|Drugovi, vreme je.
{111529}{111583}Stavi masku.
{111586}{111638}Hej, hajde.|Idemo.
{111744}{111803}10 minuta.|Gledaj me.
{111806}{111843}Hajde! Probudi se!
{111934}{111981}Vreme je.
{112016}{112055}Ajde, ajde.
{112169}{112216}Uredu je.
{112452}{112487}äefe.
{113111}{113146}Sanitet.
{113190}{113225}Hajde.
{113293}{113337}Imam ga.
{113436}{113490}äefe Gorelov|je otiöao umesto njega.
{113550}{113595}Dobar momak. Dobar momak.
{114083}{114154}Kapetane.|Zvali ste me?
{114180}{114264}Da. NeÊemo ispaljivati|nikakve rakete.
{114267}{114325}Pa, da li znate da|oËitavate radijaciju?
{114328}{114422}Da, Druûe Kapetane.|HoÊu podatke iz svih odelenja.
{114480}{114514}Da, Kapetane.
{115356}{115426}Temperatura?|925 stepeni.
{117016}{117049}Koliko?
{117076}{117123}7 minuta, 40 sekundi.
{117616}{117663}Spusti ga dole.
{117711}{117745}äefe!
{117788}{117823}äefe!
{117932}{118000}Da. Konstantin Êe ga uzeti.
{118045}{118139}On Êe ga uzeti.|Dobro si postupio. Dobro si postupio.
{118238}{118306}On Êe ga uzeti.|Mi Êemo ga uzeti.
{118309}{118369}Da, da, da.
{118856}{118966}ProtiËe. ProtiËe.|Rashladno sredstvo protiËe.
{119050}{119098}Recite kapetanu|da rashladno sredstvo protiËe.
{119220}{119289}Uspeo si.|Oh, uspeo si.
{119349}{119384}äefe!
{119677}{119725}Uspeo si, momËe.
{119728}{119780}Uspeo si, momËe.
{119783}{119910}Uspeo si. Da, pokazao si im.|Pokazao si im.
{119944}{120041}Pokazao si im.|Polako. Polako.
{120268}{120325}Pomozite mu.|Lagano. Lagano.
{120328}{120398}Uredu. Hajde.
{120427}{120490}Imam te, ortak.
{120753}{120842}Kapetane.|950.
{120845}{120939}930. Opada.|920.
{120942}{121009}910.
{121012}{121049}900.
{121440}{121486}Kapetane.|äefe.
{122116}{122150}850.
{122278}{122325}830.
{122356}{122379}800.
{122548}{122604}Govori vam kapetan.
{122607}{122658}»ini se da je reaktor|pod kontrolom.
{122708}{122767}Naöa zahvalnost ide|öefu inûenjerije Gorelov
{122810}{122866}i treÊoj smeni|reaktorskog osoblja
{122869}{122927}za dobro obavljen posao.
{123004}{123038}Odmori se, deËaËe.
{123176}{123235}Kurs?|2-2-0, Kapetane.
{123455}{123527}Okrenite ga.|Preite na kurs 0-4-0.
{123629}{123746}Prednji motor, polako napred.|BoËni, 30.
{123748}{123852}Kurs, 0-4-0.|Prednji motor, polako napred.
{123855}{123930} BoËni, 30.|Standardni Kurs, 0-4-0.
{123999}{124045}Nazad u bazu?
{124076}{124168}Brzinom od 5 Ëvorova,|trebaÊe dani.
{124193}{124240}BiÊemo brod duhova.
{125456}{125490}Kapetane.
{125493}{125566}Ljudi su gladni.|Hrana je kontaminirana.
{125596}{125661}Dajte im öta god imate u|konzervama ili foliji.
{125664}{125748}A i crvenog vina da usporimo|brzinu upijanja radijacije.
{125751}{125797}Uredu, Kapetane.
{125906}{125962}Kapetane, ovde,|je samo 5 jedinica.
{125965}{126023}Ali u sobi reaktora,|je 10 puta toliko.
{126077}{126122}IskljuËite ventilacioni sistem.
{126152}{126208}Sva odelenja,|iskljuËite ventilaciju.
{126213}{126259}Kapetane, ako...
{126285}{126363}RadiÊemo sa minimalnom posadom.|Neka ljudi idu gore
{126365}{126417}öto dalje od radijacije.
{126420}{126504}Mi smo 160 kilometara od|NATO baze Jan Mayan.
{126507}{126561}Mogli bi otiÊi tamo,|yatraûiti pomoÊ od Amerikanaca.
{126564}{126609}Ni pod kojim uslovima
{126612}{126670}neÊemo napustiti moj brod|i prepustiti moj brod neprijatelju.
{126673}{126712}Kakav nam je plan?
{126930}{127016}Daleko smo od raio kontakta.|Ako ostanemo na kursu
{127019}{127065}komanda flote Êe poslati|dizelaöe da nas nau.
{127068}{127122}Nivoi radijacije rastu|previöe brzo.
{127125}{127187}Idemo samo na elektriËnim|motorima. Nemamo vremena.
{127228}{127275}NaÊiÊe nas.
{127301}{127380}Kao i obiËno, kapetan ne ostavlja|mesta za sumnju.
{128219}{128254}Dobro.
{128409}{128443}Dobro ti je.
{128651}{128739}Dobro. Dobro ti je, Jevgenij.|SledeÊi.
{128861}{128908}Dobro. Da. SledeÊi.
{129408}{129443}Ikone
{129481}{129520}su zabranjene.
{129793}{129889}Kontakt u pravacu 0-1-5.|Domet 2,000 metara, Kapetane.
{130409}{130469}Polako, polako.|Polako, polako!
{130488}{130520}Polako, polako!
{130820}{130864}To su Amerikanci.
{130977}{131009}Kapetane.
{131058}{131138}äakali su nas naöli.|To je AmeriËki razaraË.
{131141}{131175}Kapetane.
{131231}{131290}Amerikanci nas kontaktiraju|na kanalu za hitne sluËajeve.
{131293}{131338}Helikopteri su videli|naöe ljude na palubi.
{131341}{131400}Njihov kapetan nam nudi pomoÊ.
{131403}{131458}Recite im da|nam ne treba.
{131461}{131497}Samo smo izaöli na vazduh.
{131663}{131723}äta to rade?|Slikaju nas.
{131823}{131868}Hej!
{131871}{131914}Hej, öpijuni!
{131917}{131963}Pgledajte!
{132042}{132111}Hej, morate ovo da vidite!|Svi!
{132422}{132496}Pogledajte ovaj divni, divni brod.
{132647}{132732}Hej!|Hej!
{132850}{132897}Nude pomoÊ.
{132926}{132999}éele ovaj brod.|Kakva bi to pobeda bila.
{133001}{133057}Dubina vode ovde je|dva kilometra.
{133062}{133104}Moûemo da izuËemo ljude,|rasturimo brod.
{133107}{133172}Oni bi nas morali preuzeti.|Kapetan Polenin ima pravo.
{133175}{133216}Imamo Ëamce za spasavanje.|Moûemo sve spasiti.
{133267}{133323}Da potopimo vodeÊi brod flote?
{133326}{133388}Predstavim moje ljude Amerikancima|za ispitivanje?
{133391}{133443}Vaöa je duûnost jasna, Kapetane.|Morate spasiti njihove ûivote.
{133446}{133503}Moja duûnost je prema drûavi
{133506}{133551}i ËiniÊu to sve do svoje smrti.
{133554}{133599}Vi samo branite svoju ambiciju.
{133602}{133692}Recitr to ljudima koji|dole umiru. Recite im.
{133851}{133932}NeÊe viöe biti priËe|o predaji Amerikancima.
{133934}{133978}To je izdaja.|Ako joö jednom to pomenete
{133981}{134026}zatvoriÊu vas u vaöe odaje.
{134029}{134084}A ti, ti si komesar
{134087}{134153}predstavnik partije,|odgovoran za moral posade.
{134156}{134192}Da, Kapetane.|Onda se tako i ponaöaj.
{134195}{134248}Posadi treba hrabrost,|a ne strah.
{134250}{134296}Strah je zarazan.|Da, Kapetane.
{134422}{134484}Da, Kapetane?|Prestani da pratiö Amerikance.
{134502}{134556}Oni su neprijatelj.|Da, Kapetane.
{135295}{135320}Pomozite mi.
{135352}{135392}Molim vas.
{135554}{135648}Kako su?|Otkud ja znam?
{135650}{135715}Neznam niöta o izlaganju|radijaciji.
{135734}{135768}Molim vas.
{135797}{135853}Dajem im aspirin.
{135856}{135909}I pokuöavam da spreËim da|oni koji umiru
{135912}{135971}ozraËe one od nas|za koje moûda ima nade.
{135974}{136020}Saberite se.
{136022}{136071}VI ste oficir|SOVJETSKE MORNARICE.
{136285}{136356}Vratite se i recite im|da se oporavljaju.
{136359}{136442}Kao öto ste rekli, niöta ne znate|o ozraËivanju.
{136445}{136491}Moûda se i oporavljaju.
{136536}{136579}Kapetane.|Da?
{136582}{136640}Izmerene vrednosti rastu|sada u svim odelenjima.
{137140}{137187}Druûe Suslov.|äta je?
{137258}{137314}Radijacija Êe|nas sve pobiti.
{137349}{137394}PolitiËki ogranak|vas ovlaöÊuje
{137397}{137446}da odobrite bilo koju|promenu komande.
{137449}{137518}Samo u ekstremnim sluËajevima|nevröenja duûnosti.
{137521}{137572}äto ovo i jeste.
{137574}{137630}I on sam boluje|od trovanja radijacijom.
{137633}{137748}Ne rasuuje dobro, inaËe|bi evakuisao ljude.
{137810}{137901}Kada trenutak doe, znaÊemo.
{139621}{139666}äav vara popuöta!
{139669}{139716}Temperatura jezgra|je 450 stepeni i raste.
{139719}{139764}Kapetane.
{139767}{139839}Popravka reaktora nije uspela.|Kapetane.
{139842}{139905}Temperatura Jezgra je 450 stepeni|i raste.
{140132}{140209}Govori vam kapetan.|Svi u potpalublje.
{140237}{140284}Priprema za hitno poniranje.
{140561}{140672}Svi dole! Svi dole!|Pozicije za poniranje! Pozicije za poniranje!
{140675}{140716}ZapeËatite pregrade!
{140786}{140864}Ja se dole ne vraÊam!| Ja se dole ne vraÊam!
{140867}{140936}Svi na svoja mesta!|Mrdaj! Mrdaj! Hajde!
{140938}{140984}Moramo da idemo, sada!
{141045}{141076}Andrej, ne!
{141079}{141136}Ne, Andrej!|äta to radiö!
{141138}{141203}Zaranjaj!|Zaranjaj!
{141206}{141272}Mrdaj! Ajde! Ulazi!
{141274}{141344}Ulazi u komoru!|To je nareenje!
{141347}{141442}Mrdaj!|Nemoûemo ga ostaviti tamo!
{141461}{141532}Da li Amerikanci i dalje|nude pomoÊ?
{141535}{141582}Kapetan je rekao da ne.|Proveri.
{141713}{141822}Joö su tamo.|Zaöto zaranja? SkuvaÊe nas.
{141885}{141932}Ne! Ne idem!|Hej!
{141935}{142006}Jevgenij! Zaranjamo!|Ne!
{142009}{142087}Pripremite rezervoar!|Brzo!
{142266}{142324}Daj mi to!
{142751}{142835}Ovo je sranje!|Pusti me!
{143082}{143140}Poûar u komori torpeda!|Idemo!
{143443}{143508}Zadnjoj komori?|Hajde.
{143535}{143574}Raport!
{143577}{143626} Poûar u komori torpeda.|Nemamo komunikaciju.
{143629}{143711}Vatrogasni tim se sprema.|Aktivirajte poûarni sistem.
{143714}{143780}To Êe pobiti sve koji su tamo.|Torpeda Êe nas sve pobiti.
{143783}{143836}Imaju opremu za disanje.|Nemaju.
{143839}{143884}Uzeli smo njihov kiseonik|za tim reaktora.
{143887}{143936}Dajte vatrogascima vremena.|Aktivirajte sistem.
{143939}{143999}Primarni nije ukljuËen.|Mora se lokalno aktivirati.
{144029}{144115}Idite u devetku i ukljuËite ga.
{144167}{144206}Odbijate moje nareenje?
{144249}{144280}Sam Êu to uraditi.
{144310}{144392}Ako napustite komandni centar, ja|Êu traûiti pomoÊ od Amerikanaca
{144395}{144442}a vi me neÊete moÊi zaustaviti.
{144567}{144632}Ako ne uspemo,|liËno Êu aktivirati sistem.
{144753}{144850}Ugasite poûar.|Brzo!
{144853}{144892}Zaöto ne zaranjamo?
{144932}{144989}Ovlaöten od strane|partije
{144992}{145074}uklanjam vas sa komandnog mesta|zbog neizvröavanja duûnosti.
{145441}{145475}Izolujte elektriËne vodove!
{145478}{145579}Gubite vreme.|Neka poprave reaktor.
{146150}{146196}Torpedo broj 8!
{146545}{146634}Kornilov, reci Amerikancima|da evakuiöemo podmornicu
{146637}{146683}i da nam treba pomoÊ.
{146761}{146798}Poöalji pomoÊ.
{146955}{147034}RazaraËu SAD. RazaraËu SAD.|Ovde Sovjetska podmornica. Prijem.
{147528}{147575}Druûe Admirale.
{147629}{147679}General Veröinin, KGB.
{147738}{147846}éelim da znam da li|je vaö Ëovek Vostrikov izdajnik.
{147849}{147918}Sve öto znamo je da K-19|nije u radio kontaktu sa nama.
{147921}{147971}Prekinuli su radio kontakt sa nama.
{148001}{148072}IzviaËki avion je|primetio razaraË
{148075}{148122}koji prati K-19.
{148173}{148237}AmeriËki razaraË.
{148650}{148711}Kapetan Polenin|u centralnu komandu.
{148713}{148798}Ponavljam. Kapetane Polenin|u centralnu komandu.
{148801}{148859}Kapetan Polenin|u centralnu komandu.
{148862}{148922}Ponavljam. Kapetan Polenin|u centralnu komandu.
{148925}{148976}575 stepena i raste.|Umukni!
{148979}{149024}Nemate pojma|öta radite.
{149041}{149072}Polako, polako.
{149075}{149140}Ko je to?|To je Dmitri.
{149143}{149194}Kapetan Polenin|u centralnu komandu.
{149197}{149278}Ponavljam. Kapetan Polenin!|UËini öta moûeö, Vanja.
{149281}{149347}Sve je uredu.|U centralnu komandu. Odmah!
{149421}{149468}Petorica.
{149471}{149542}Kapetane Polenin, upotrebio|sam svoj autoritet
{149545}{149592}da plovilo prebacim|pod vaöu komandu.
{149817}{149886}Vi ste naö kapetan|uvek ste i bili.
{149924}{149970}Kontaktirali smo Amerikance.
{149973}{150047}Sve öto treba je da naredite|napuötanje broda.
{150428}{150462}Dobro.
{150538}{150573}Dobro.
{150599}{150664}Ovde nema mesta oruûju.|Dajte mi ih.
{150691}{150738}Daj mi piötolj.
{150763}{150822}Daj mi piötolj i kljuËeve|od lisica. Hajde.
{150852}{150915}Daj mi ih.|Posada je porodica.
{150917}{151024}Naravno, Kapetane.|I kljuË od lisica.
{151052}{151086}Kapetane.
{151109}{151155}Izdao si svoju porodicu.
{151219}{151259}Izdao si mene.
{151285}{151338}Uhapöen si.|äta?
{151341}{151378}Obojica!|Maknite mi ih sa oËiju!
{151381}{151444}Uzmite im oruûje.|ZakljuËajte ih u kabine. Mrdaj.
{151447}{151494}Kapetane Polenin,|to je izdaja!
{151561}{151603}Poûar u odelenju 10|je ugaöen.
{151606}{151647}Sistem gaöenja nije bio|potreban.
{151650}{151708}Naûalost,|imamo samo jednog preûivelog.
{151760}{151795}Hvala vam.
{151831}{151870}Kapetane.|Kapetane.
{151906}{151953}Moramo da zaronimo.
{151959}{152012}Govori vam kapetan.
{152146}{152213}Ne nareujte im, Kapetane.
{152216}{152262}Pitajte ih.
{152485}{152532}Govori vam kapetan.
{152560}{152607}Naöa situacija je oËajna.
{152642}{152700}Popravka reaktora nije uspela.
{152729}{152784}Svakog Ëasa,|moglo bi doÊi do eksplozije
{152787}{152868}koja bi aktivirala bojeve glave.
{152871}{152963}Ovo bi uniötilo AmeriËki brod
{152965}{153047}samo par kilometara
{153049}{153100}od NATO baze.
{153130}{153189}Uzevöi nivo trenutnih|tenzija
{153191}{153240}izmeu naöe dve zemlje
{153284}{153365}to bi moglo izazvati|straviËnu odmazdu
{153367}{153414}prema otadûbini.
{153511}{153568}Mogli bi da zaronimo
{153570}{153619}i probamo popravku rektora.
{153670}{153716}Nema garancija.
{153779}{153828}Ja Ëekam.
{154104}{154151}Obezbedite obe komore.
{154475}{154537}Odelenje 10 izolovano.
{154540}{154588}Odelenje 9 oËiöÊeno od dima
{154591}{154645}popunjeno i spremno.
{154688}{154764}Odelenje 8 u sluûbi|Sovjetskog Saveza, Druûe Kapetane.
{154795}{154881}Odelenje 7 spremno|da izvröi duûnost, Druûe Kapetane.
{154884}{154942}Odelenje 5|popunjeno i spremno.
{154945}{155018}Odelenje 4.|»ekamo vaöa nareenja, Kapetane.
{155021}{155113}Odelenje 1.|Sa vama smo, Druûe Kapetane.
{155116}{155164}Spremni da zaronimo, Kapetane.
{155167}{155228}Zaronite.|Zaronite.
{155230}{155298}Na dubinu 300 metara.|Drûite 5 stepeni.
{155301}{155385}Poplavite glavne balaste.|Poplavite glavne balaste.
{155388}{155458}ElektriËni motori punom snagom napred zajedno.|Punim napred zajedno.
{155461}{155508}Drûite 5 stepeni, pramac dole.
{156136}{156209}RadËenko.|PoruËniËe RadËenko.
{156284}{156333}PoruËniËe RadËenko, raport.
{156787}{156893}Kapetane, temperatura reaktora je|760 stepeni i raste.
{157161}{157196}PoruËniËe RadËenko.
{157297}{157343}Gde je?|Unutra.
{157531}{157578}Koliko dugo je unutra?
{157626}{157705}18 minuta.|18 minuta?
{157739}{157786}Polako. Kapetane.
{157789}{157841}Ne moûete unutra bez vaöeg.|Osiguraj poklopac.
{158439}{158486}Ne vidim.|Ne vidim.
{158489}{158536}PomoÊi Êu ti.|Kapetane.
{158538}{158577}Imam te.|éao mi je.
{158851}{158898}Otvori poklopac!
{159024}{159105}280 metara.|IzjednaËi.
{159646}{159693}Prolaz.
{159696}{159746}970 stepeni i drûi se, Kapetane.
{159749}{159795}Otvorite vrata pregrade.
{159853}{159899}Dobio je preveliku dozu.
{159902}{159953}Ko ide sledeÊi?
{159984}{160057}Kapetane,|temperatura opada.
{160117}{160183}Uspeo je.|Postao je heroj.
{160186}{160232}Izronite.
{160265}{160323}Izbaci glavni balast.|Nastavite sa podizanjem.
{160326}{160420}Drûite 15 stepeni prema pramcu.|Motori idu punom snagom.
{160423}{160499}Imate komandu.|Puno podizanje, 15 stepeni prema pramcu.
{160524}{160570}Imam komandu.
{160616}{160689}Signalizirajte AmeriËkom kapetanu|Ëim izronimo.
{160736}{160809}Recite mu da|nam treba asistencija.
{160854}{160889}Da, Kapetane.
{160920}{160955}Da, Kapetane.
{161068}{161127}Diûi periskop.|Diûem periskop.
{161471}{161506}Ljudi
{161561}{161614}obavili ste duûnost|prema otadûbini.
{161681}{161738}Partija je ponosna na vas.
{161741}{161801}Ja sam.|Ja sam ponosan na vas.
{161802}{161867}Ja sam.|Ja sam ponosan na vas.
{161964}{162051}Kapetane. Kapetane.
{162106}{162162}Da, Vadim. Ovde sam.
{162185}{162232}äav, da li drûi?
{162262}{162347}Da, Vadim, öav drûi.
{162423}{162470}Ti si heroj, Vadim.
{162473}{162520}»ujeö li?
{162580}{162627}Ti si heroj.
{162849}{162896}Svi ste vi
{162932}{162980}svi ste
{162983}{163018}heroji.
{163514}{163584}Nadao sam se da|Êe nas naöi naÊi.
{163705}{163764}Nivo radijacije se penje|suviöe brzo.
{163910}{163957}Zamolio sam AmeriËkog|kapetana
{164030}{164079}da nam pomogne.
{164364}{164420}Pripremite se za napuötanje.
{164682}{164772}AmeriËki razaraË, na kursu 0-4-5.|Daljina, 2,000 metara.
{164895}{164942}Kapetane, imam vezu!
{164992}{165053}äta kog...|Kapetane!
{165058}{165162}Brod je moûda u nevolji.|Kakvoj nevolji?
{165165}{165248}Poznajem Kapetana Vostrikova|liËno polovinu njegovog ûivota.
{165273}{165368}Ne postoji podmorniËar u mornarici|Ëijoj lojalnosti viöe verujem.
{165370}{165428}Viöe nego lojalnosti njegovog oca?
{165524}{165572}Oca mu nisam poznavao.
{165788}{165823}Kapetane.
{165851}{165886}Kapetane.
{165990}{166039}Kada je moj otac odlazio na more
{166042}{166088}nosio je
{166091}{166153}pune öake zemlje|u svojim dûepovima.
{166181}{166242}"Komad otadûbine,"|govorio je.
{166293}{166366}Pre bi umro nego|da izda svoju zemlju.
{166418}{166500}Javite mi sa mosta kada se|svi ukrcaju u Ëamce.
{166503}{166563}Ja Êu potopiti brod.|Amerikanaci je neÊe dobiti.
{166584}{166639}Nema potrebe za tim, Kapetane.
{166658}{166731}Naöa podmornica, S270,|nas je naöla.
{167306}{167340}Da.
{167386}{167420}Da.
{167546}{167592}Potvrujem i kraj.
{167654}{167736}Odgovor od Moskve, Kapetane,|poslat preko S270.
{167738}{167798}Vaö zahtev za evakuaciju broda
{167801}{167861}je odbijen, Druûe Kapetane.
{167938}{167989}äalju tegljaË da nas|odvuËe u luku.
{168082}{168119}Joö neöto?
{168185}{168220}Rekli su.
{168255}{168313}Rekli su da posadi date|puno sveûeg voÊa.
{168410}{168508}HoÊu da evakuiöem svoju posadu.|ProtivureËim Moskvi.
{168534}{168587}Svesni ste da Êe to|biti kraj vaöe karijere.
{168658}{168737}PoslaÊe vas u gulag,|kao vaöeg oca.
{168786}{168863}Pa, to je porodiËna tradicija,|zar ne?
{169236}{169283}Idemo! Idemo!
{169942}{170003}Hajde!|Imamo te.
{170079}{170126}Polako. Polako.
{170154}{170197}Dobro. Dobro ljudi. Dobro.
{170239}{170289}Morate biti dekontamirani.|Razumete li?
{170292}{170355}Moramo vas oËistiti.|Oribajte ga.
{170358}{170448}Hladno je. BiÊe toplije unutra.|Morate se skinuti.
{170451}{170504}DekontaminiraÊemo vas|i uniötiti odeÊu.
{170507}{170579}Onda moûete dole.|Skidaj pantalone.
{170644}{170678}Polako.
{170736}{170782}Ovuda.|Pazite na konopac.
{170785}{170880}Prebaci ga.|Hajde, povuci.
{171113}{171148}Paûljivo.
{171151}{171207}Ovo je tvoj brod, Miöo.
{171236}{171312}Izgubio sam poloûaj, Juri,|Ali ne i moje samopoötovanje.
{171315}{171362}Ti si izgubio oba.
{171562}{171618}Kuda me nose?|Dajte Êebe ovamo.
{171620}{171667}Nose te preko, Vadim.
{171670}{171733}Treba mi KaÊina slika.
{171736}{171791}Gde je?|U mom dûepu.
{171870}{171913}Izvoli.
{171941}{171976}Evo je.
{172120}{172166}Ne vidim.
{172168}{172222}Ne vidim je.
{172636}{172704}Svi ljudi su prisutni, Kapetane.
{172742}{172809}Hajde, hajde.|Dajte ih ovamo.
{172876}{172947}Zaöto nisi preuzeo komandu|kada si imao priliku?
{173041}{173118}Jer je ono öto su|uradili bilo pogreöno.
{173253}{173309}Pripremite se za ölepanje, Kapetane.
{173312}{173347}Kapetane.
{173563}{173651}Sklonite ih sve. Mrdaj.|Pomerite se.
{173704}{173778}Lev, ti si dobrodoöao prizor.
{173780}{173839}Moskva je mislila da Êeö|da prebegneö sa svojim brodom.
{173842}{173914}éele da sastavim spisak|svih sposobnih da svedoËe.
{173916}{173976}SvedoËe? O Ëemu?
{174018}{174053}O tebi.
{174189}{174248}Proverite da li su sve|veze osigurane.
{174251}{174298}Hajde. Idete kuÊi.|Hvala vam, Doktore.
{174300}{174347}Uspeli smo.|Idemo kuÊi.
{174404}{174461}Produûite.|Produûite.
{174464}{174543}Da, hajde sada.|Idemo kuÊi.
{174840}{174905}U svakom stadijumu ove nesreÊe,|koja je bila blizu
{174908}{174964}da postane mnogo|veÊa katastrofa
{174967}{175054}oficiri i posada|uËinili su ono öto se moralo.
{175056}{175103}Sedmorica su sada mrtvi
{175105}{175159}a niko nezna koliko ih joö umire
{175162}{175215}ni koliko brzo.
{175218}{175278}To su ljudi koji su se vratili kuÊi|da bi ih vi sasluöavali
{175281}{175340}kao da se neki zloËin desio
{175343}{175427}ispituju ih dok prolaze|kroz tretman od zraËenja.
{175448}{175521}ZakljuËani i bez pristupa|ûenama i porodicama.
{175564}{175628}Ali oni i njihovi drugovi|spasili su K- 19.
{175662}{175758}A moûda, moûda,|su spasili i sve nas.
{175760}{175807}Hvala vam, Kapetane Polenin.
{175810}{175861}Samo joö jedna stvar, molim.|Hvala vam.
{175864}{175974}Nijedan kapetan Sovjetskog Saveza|nije bio pred takvim odlukama
{175999}{176046}sudbina broda, posade
{176074}{176131}sudbina sveta.
{176133}{176184}Sve u ravnoteûi.
{176237}{176284}Mornarica je moj ûivot.
{176326}{176412}I znam jednu stvar, moûe biti samo|jedan kapetan na brodu.
{176455}{176514}Teret komande je|na njegovim pleÊima
{176517}{176564}i samo njegovim.
{176705}{176766}Niko od vas.
{176769}{176853}Niko od vas nema pravo|da sudi Kapetanu Vostrikovu.
{176883}{176947}Vi niste bili tamo.|Ja jesam.
{176978}{177025}Bio je naö kapetan.
{177084}{177129}Bio je moj kapetan.
{177325}{177383}I bila bi mi Ëast
{177385}{177432}da ponovo plovim|pod njegovom komandom.
{177756}{177802}IstoËna NemaËka je pristala da uradi
{177805}{177879}ono öto je Zapad govorio da treba|viöe od jedne generacije.
{178024}{178088}Posle otvaranja Berlinskog Zida,|vlada je objavila
{178090}{178120}da Êe odrûati|demokratske izbore.
{178121}{178147}da Êe odrûati|demokratske izbore.
{180165}{180221}Nisi toliko visok|kao öto te pamtim.
{180224}{180263}Dobro je videti te.
{180327}{180362}I tebe.
{180396}{180430}Molim te.
{180564}{180627}Drago mi je öto si me naöao
{180630}{180723}ali danas, ustvari,|nije baö zgodno.
{180725}{180774}Ne, ne. moralo je biti danas.
{181103}{181150}Vaöa posada.
{181217}{181271}Bilo je pre 28 godina na danaönji dan.
{182610}{182677}Kapetane, zdravica.
{182767}{182814}Za ljude joö uvek u patroli.
{183003}{183062}Za njihovu hrabrost,|nominovao sam ih
{183119}{183190}za titule|Heroja Sovjetskog Saveza.
{183284}{183331}Ali komitet je presudio
{183401}{183451}da zato öto nije|bilo ratno stanje
{183585}{183639}veÊ je bila SAMO nesreÊa
{183689}{183750}nisu vredni titule Heroja.
{183959}{184029}äta im i vrede poËasti|od takvih ljudi?
{184125}{184174}Ovi ljudi su se ûrtvovali
{184177}{184226}ne za medalje
{184282}{184333}veÊ zato öto su,|kada je doöao trenutak
{184402}{184462}ispunili njihovu duûnost
{184495}{184597}ne prema mornarici|ne prema drûavi
{184705}{184751}veÊ prema nama
{184797}{184843}njihovim drugovima.
{184988}{185022}I zato
{185093}{185127}za drugove.
{186140}{186215}{C:$FF0000}{y:b} Obrada DIVX-a u DVD |{C:$0000FF}{y:ib} éile
{186240}{187740}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/8ckus|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
