{29}{29}23.976
{54}{204}-== [ www.OpenSubtitles.org ] ==-
{721}{814}ST. JOVITE, KANADA 1983
{1193}{1234}Gdje idete?
{1464}{1524}Jednu kartu, molim vas.
{1685}{1759}Mogu li, onaj Ëovjek iza ne prestaje hrkati.
{1812}{1848}Naravno.
{1920}{1992}Ja sam Met. - Ja sam Marty.
{1992}{2049}Zdravo Marty, drago mi je.|- I meni.
{2049}{2076}Gdje si poöao?
{2112}{2159}äto dalje mogu.
{2188}{2229}Da popijemo u to ime, brate.
{2397}{2426}Na zdravlje.
{2699}{2768}MISLIM DA IMAMO MALI PROBLEM|SA MOTOROM, NARODE,...
{2776}{2814}SAMO SE SMJESTITE UDOBNO.|- Jao ËovjeËe...!
{2828}{2903}Isto ovo mi se desilo u St. Lorens|kada sam morao Ëekati 8 sati.
{2929}{2982}Dovraga, ova smrdi.
{3003}{3044}Ova stvarno smrdi.
{3085}{3150}385 dolara. Samo u gotovini.
{3150}{3190}Zar ne primate kreditne kartice?
{3224}{3246}Ne znaö Ëitati?
{3262}{3296}Samo u gotovini!
{3361}{3449}Da li ti imaö dozvolu?|- Imam, ali su mi je oduzeli.
{3473}{3509}ZnaËi ti Êeö voziti.
{4006}{4044}Vidiö li ovo?
{4164}{4248}äto se desilo? - Ovo mi je od oËuha.
{4250}{4341}Udario me tako jako da sam preleteo kuhinju.|Majka je gledala sve to.
{4351}{4413}Zaöto je uradio to?|- Zato öto uûiva u tim stvarima.
{4416}{4485}On je jebeni psihopat, ma to je|120 kg. bezvrijednog smeÊa.
{4507}{4588}Ali vratio sam mu. - Udario si ga?
{4593}{4675}SlijedeÊe jutro je bilo najgore,|upisao me u vojnu ökolu.
{4751}{4806}Jebeö ljude, jebeö njihova pravila.
{4814}{4859}Zato sam prije|dva dana preskoËio zid.
{4864}{4907}E a sada hoÊu svirati.
{5487}{5547}Jako mi je ûao, ËovjeËe...|mislim, ponio sam se kako idiot,
{5550}{5598}- Nisam primjetio.|- Ne, ne... zaboravi, ËovjeËe...
{5672}{5729}Da li si nekada mijenjao gumu, Martyn?
{5734}{5780}Nisam ni mislio. Cool...
{5833}{5924}Ok... öto imamo ovdje...|oh da, zamjenit Êu je odmah.
{5943}{5974}Dok ne lupiö, stvarno.
{5981}{6027}SlijedeÊi put ja vozim. Cool.
{6147}{6190}»vrsto je stegnuto.
{6662}{6756}Ovo je najteûi dio,|ostatak je laköi.
{6871}{6959}Ja i ti smo skoro iste visine, ËovjeËe. - äto?
{9491}{9686}OH JE... JA IMAM VOJNI|BLUES, IMAM VOJNI BLUES...
{9724}{9829}ONI NEMAJU MOJU KOSU, SRCE...
{9861}{9928}NEMAJU MOJU DUäU.
{9971}{10016}DE»KO POGINUO U PROMETNOJ NESRE∆I.
{10055}{10115}POGINULI SU NA MJESTU.
{10338}{10364}UMRLICA
{10364}{10390}KVEBEK, MONTREAL|KANADSKO ZDRAVSTVENO
{10390}{10410}UDRUéENJE
{10726}{10791}ODUZIMANJE éIVOTA
{11364}{11390}OTKRIVANJE TIJELA
{11412}{11438}NEMA OSUMNJI»ENIH
{11673}{11690}NERIJEäEN SLU»AJ
{12009}{12076}IDENTITET éRTVE|POD ISTRAGOM
{12623}{12692}NOVELA MICHAELA PAJA
{12994}{13021}NESTAO HENRY BIZONET
{13028}{13059}35 G. KESTENJASTA KOSA,|SVIJETLE O»I, VISINA OKO 175 CM.
{13083}{13109}NESTAO OD UTORKA
{13268}{13397}MONTREAL, KANADA DANAäNJI DAN
{14531}{14589}Oh, treba mi vaöa pomoÊ. - Da, g-o.
{14608}{14680}Samo öto sam vidjela svog sina na feribrodu.
{14685}{14764}U Ëemu je problem, madam?|- Moj sin je mrtav!
{14778}{14831}Umro je prije toËno 19 godina.
{14833}{14903}Jasno sam vidjela da je to on,|a umro je predamnom.
{14910}{15001}Vidio je i on mene i prepoznao me je.
{15008}{15063}Majke ne grijeöe u ovakvim stvarima.
{15102}{15171}Ne mogu vam objasniti|koliko je opasan, koliko...?
{15198}{15241}Ne, bio je...
{15303}{15442}Moj sin je veoma opasan Ëovjek.
{15636}{15744}- äta to radiö?|- Pripremam brifing za agenta Scota.
{15772}{15811}Agent Scott?
{15816}{15867}Nije mi jasno öto je sve ovo?
{15871}{15934}Imamo sve pod kontrolom.|- Nemamo niöta. Joseph.
{15938}{15991}To je zato öto nemamo dovoljno vremena.
{15994}{16042}Nama treba samo malo|viöe vremena, to je sve.
{16044}{16135}- Da li je stigla?|- Bila je na letu.
{16140}{16207}Ali ne mogu je naÊi. Gerard|provjerava da li je uzela prtljagu.
{16212}{16267}Ona samo dijeli dobre savjete zar ne?|Ovdje se ne radi o teritoriji.
{16272}{16317}Ovakvo ubojstvo se godinama nije desilo.
{16322}{16353}OK, a prvo öto Êeö uraditi je da...
{16356}{16406}dovedeö nekoga. Ajde!
{16418}{16452}Imam Ëudan osjeÊaj u vezi ovog ubojstva.
{16488}{16535}Treba nam pomoÊ, nemamo niöta.
{16564}{16634}Pozovite me kada bude bilo neËega.
{17840}{17895}Sigurno se öaliö samnom.
{17897}{17952}Specijalni agent Skot? - Da.
{17993}{18080}»ekali smo vas u stanici.|- To je grob, da li znaö?
{18094}{18118}Da, znam.
{18216}{18293}Agente Scot!|- G-ne Leclair, zdravo.
{18295}{18355}Vidim raskomotili ste se.
{18360}{18439}Ovo su Joseph Paket i Emil|Duval, oni vode istragu.
{18446}{18480}Drago mi je.|- I meni, takoer.
{18497}{18547}Hvala vam öto ste me pozvali.|- Mi vas nismo zvali.
{18590}{18636}Mi smo priliËno sigurni|da je ûrtva ubijena negde drugde...
{18641}{18660}a zatim donesena ovde.
{18734}{18784}Mislim da je bilo sa|predumiöljajem. - äto?
{18796}{18844}Mislim da je bilo sa predumiöljajem,|i da se ubojica odluËio...
{18856}{18916}za ovu stranu konkretno.
{18938}{19027}Mogu vam pokazati...|moûete i sami vidjeti po uglovima,
{19060}{19146}dimenzije su simetriËne.|Proporcije su precizne.
{19151}{19238}ToËno su 2 i pol metra.|Jel' ûrtva 180?
{19247}{19276}Da, toËno!
{19295}{19379}Mislim da ih promatra|nekoliko tjedana, prouËava...
{19384}{19441}njegove navike, njegovu rutinu|... i toËno zna da moûe...
{19444}{19540}stati u ovaj grob.|- A kako zna da Êe ûrta biti...
{19542}{19576}baö tamo gdje on ûeli?
{19607}{19710}To je staza za bicikliste, zar ne?|Na slikama koje ste poslali...
{19715}{19813}ûrtva ima male povrede na koljenima.
{19830}{19887}Pretpostavljam da su od bicikla.
{19899}{19964}Mislim da u svemu ovome|ima i seksualnih elemenata...
{19976}{20046}davljenje odpozadi, sjeËenje|ruku, smrskavanje glave...
{20050}{20129}sve to se dogaa trenutno.|To njega uzbuuje.
{20153}{20276}I... on ûeli da vi|pronaete dijelove tijela.
{20305}{20405}Ostavlja ih po gradiliötima,|jer ûeli da budu otkopani.
{21551}{21604}A oËi, mi mislimo da|ih odstranjuje ili ih oni...
{21609}{21690}ipak imaju? - Ne znamo.|- Onda pretpostavljam da...
{21695}{21748}Radimo rekonstrukciju lobanje. Da, naravno.
{21752}{21816}Upravo se radi.
{21820}{21885}- Da li smo zavröili|ovdje? - Da... - OK!
{21889}{21916}Laku noÊ!
{21956}{22057}Ne brini za Paket, on je... impulsivan,|ûeli u sve biti upuÊen.
{22064}{22129}- Ne krivim ga.|- Dobro je öto te vidim...
{22134}{22199}ponovno, Ileana.|Mnogo mi znaËi öto si ovdje.
{22266}{22390}Neki misle da si vjeötica.|- »ula sam i gore.
{22398}{22429}Ti to znaö.
{24661}{24714}Zdravo, ûao mi je öto je|uznemiravam, ubijen je Ëovjek...
{24716}{24776}sinoÊ.|- Na parkingu proöle veËeri,
{24781}{24855}oko 9 sati.|- ZnaËi da je isti?
{24867}{24944}Sve je isto. Naöli|smo djevojku, uûasno je.
{24949}{25001}Lice joj je smrskano tvrdim predmetom.
{25004}{25069}- Izgleda nije imao vremena|odsjeÊi joj ruke - Zaöto ne?
{25090}{25119}Bio je prekinut.
{25138}{25222}Ime ûrtve je Klaren Moren.|Ovo je Jim Costa.
{25232}{25280}Tvrdi da je vidio sve öto se desilo.
{25323}{25407}Kada su naöi stigli,|pokuöavao ju je oûiviti.
{25414}{25481}A ODAKLE OVA KRV PO VAMA?|- POKUäAVAO SAM POMO∆I
{25483}{25529}NEKOME TKO JE...|KRVARIO NA SMRT...
{25534}{25627}Da li ste ga proverili?|- James McKean Costa.
{25634}{25740}Roen 1965-te, iako...|izgleda sasvim normalno.
{25771}{25881}Imame ostatke krvi.|- OKRENUO SAM SE I VIDIO...
{25934}{26028}KAKO »OVJEK STOJI NAD NEKIM SA...
{26080}{26145}SA KAMENOM... u rukama.
{26253}{26337}PoËeo ju je udarati po licu...
{26380}{26462}ja sam poËeo vikati...|- Kako ste vikali?
{26512}{26615}Staniii! Otprilike tako...|ne sjeÊam se...
{26637}{26677}a onda sam potrËao ka njima...
{26747}{26828}on... pogledao me je, izvadio|piötolj i uperio ga ka meni...
{26843}{26891}i... ja...
{26975}{27039}ne znam, pomislih...|ne znam öto sam pomislio...
{27044}{27090}a on je vec pobjegao, NESTAO!
{27116}{27214}ZATIM SAM ZVAO POLICIJU!|I PROBAO SAM UMJETNIM...
{27224}{27291}DISANJEM DOK NIJE STIGLA HITNA POMO∆
{27301}{27401}Jesi li pomicao garotu?|- Stvar oko njenog vrata? Sasvim malo.
{27440}{27485}Da. - Da, mislim da jesam.|Nekako... kao da sam morao.
{27490}{27569}Jesi li vidio gde je napadaË otiöao?|- Da, pobegao je od mene.
{27593}{27629}Kakav je piötolj imao?
{27677}{27749}Imao je piötolj koji pravi velike rupe u ljudima.
{27823}{27922}Vidio sam tipa, u redu,|mogu ga opisati, nacrtati...
{27926}{28008}Moûeö... Samo mi dajte komad papira.
{28013}{28058}I nacrtat Êu ga.
{28238}{28291}Nisam siguran za ovog ovdje.|Ne mogu ga proËitati.
{28303}{28356}Neöto kod njega ne odgovara...
{28377}{28413}Ne bi vam smetalo da ja probam?
{28423}{28452}Ne, molim vas, pokuöajte.
{28576}{28607}Zdravo.
{28850}{28929}Da li ste i vi policajac?|- Na neki naËin, jesam.
{28943}{28984}Specijalni agent Ileana Skot.
{28998}{29061}- Specijalni agent!|- Ja sam iz FBI.
{29061}{29092}Pomaûem im oko sluËaja.
{29250}{29305}Mogu li vam postaviti par pitanja?
{29307}{29351}Moûete isto kao i vaö kolega.
{29353}{29377}Da, vjerojatno.
{29413}{29451}Ne smeta vam da zapalim cigaretu?
{29459}{29492}Ne, slobodno.
{29986}{30022}Nervozni ste?
{30060}{30101}Da. Jesam.
{30130}{30151}Veoma.
{30197}{30233}Hvala vam.
{30504}{30542}Pa, kako izgleda?
{30605}{30653}Ima neobiËno svijetle oËi.
{30677}{30705}U redu?
{30729}{30772}Da... Ëak se i u mraku vide.
{30772}{30811}Njegova kosa...
{30842}{30885}mislim da je bila svijetla.
{31017}{31132}Mislim da je imao bradu. Nisam|ga baö dobro vidio u mraku, ali...
{31149}{31197}nekako kultivirano...
{31321}{31403}Da li vam se uËinilo da je smiren|ili uzrujan, nervozan?
{31441}{31513}Isuse... Da li je to öto mislim da je?
{31528}{31626}Da li je to...?|TO JOJ JE BILO OKO VRATA, ZAR NE?
{31631}{31676}JESAM LI U PRAVU?|JESAM LI?
{31679}{31731}- DA...|- U redu, da li ste to namjerno uradili?
{31746}{31815}U redu, ja se trudim najbolje öto mogu?
{31820}{31847}Nije imao pola lica.
{31849}{31902}Skoro da nije ni izgledao kao Ëovjek.
{31906}{31947}UËinio sam sve öto sam|mogao da bi mu pomogao ali...
{32017}{32072}umro je. Imao je...
{32129}{32177}Sluöaj, bilo je previöe krvi a ja...
{32180}{32221}nikada nisam vidio toliko puno krvi...
{32225}{32259}u svom ûivotu...
{32269}{32336}Ali ûelio sam pomoÊi|iako sam znao da je kasno.
{32357}{32420}Vidio sam Ëovjeka koji je uradio ovo.
{32427}{32480}OK? Vidio sam ga.
{32484}{32537}Mogu vam pokazati kako izgleda.
{32583}{32609}A zatim...
{32643}{32700}- Onda ga moûete uhvatiti! - Dobro.
{32909}{33012}- äto misliö?|- Rekao nam je da je ubica ljevoruk.
{33031}{33103}On crta desnom rukom,|a i cigaretu je zapalio...
{33105}{33168}desnom rukom.|- Mislim da Êe nam trebati malo viöe...
{33170}{33228}da bi saznali.|- Da, znam. Ima otvoren...
{33230}{33307}dosje na tvom stolu, to su|tvoji dokazi, unutra je sve.
{33311}{33374}Ako je ubojica potrudit Êe se da ih pogleda.
{33422}{33494}Psihopate u suötini imaju veoma|razliËit parametar zapaûanja.
{33498}{33616}Ti izgovaraö rijeËi kao: drvo|ili kuÊa, silovanje, incest,
{33621}{33709}ubojstvo. Normalna|osoba bi to izmjenila.
{33721}{33829}Psihopate ne reagiraju.|Imaju potpuno isti osjeÊaj za silovanje,
{33834}{33875}ubojstva kao i osjeÊaj za veËeru.
{33880}{33916}Nemaju emocionalnu povezanost.
{33935}{34026}Svejedno, poenta je|da kada je vidio garotu...
{34028}{34124}pokazao je prirodni öok i zgroûenost.
{34254}{34297}Mozak psihopate.
{34345}{34417}Ti si nauËila puno|toga u FBI-u, zar ne?
{34422}{34474}Mislim, sve te teorije, sve te knjige.
{34484}{34527}Da, toËno.
{34587}{34664}Nisam siguran da sam|vidio sve tvoje trikove.
{34700}{34740}- Nema nikakvih trikova. - Sereö.
{34752}{34822}Pritegla si ga u toj sobi.
{34824}{34884}Agente Scot! Moûemo|li popriËati na kratko?
{34896}{34918}IspriËavam se.
{35021}{35093}To je zato öto i ja imam tri sestre|i njegov pogled dok me je...
{35098}{35158}sasluöavao nije mi se svidio.|éao mi je ako grijeöim.
{35172}{35234}- Ne! Hvala vam. - OK.
{36467}{36535}- Agente Scot.|- Mogu li da razgovaram s vama?
{36624}{36705}- Joö niste spavali.|- Ne.
{36726}{36783}Postoji straûar|u holu hotela.
{36787}{36858}I mi smo odmah pored puta.|Tako da nema smisla.
{36862}{36904}Misliö da je iscenirano?
{36908}{36970}Ne. Postoji smisao|u zadovoljstvu insceniranja.
{36974}{37044}Oblik arogancije.|Takvog ponaöanja nema ovde.
{37048}{37144}Moûda je hteo da brzo naemo telo,|kao na gradiliötu.
{37148}{37231}Da. Ali zaöto?
{37236}{37299}Mislim, zaöto?|Neruga nam se.
{37303}{37389}Znaö,|nema "jebite se" nigde.
{37803}{37850}Zaöto to radiö?
{37867}{37911}- äta?|- Pokrivaö uöi?
{37993}{38043}Bolje mislim kad je tiho.
{38048}{38098}Ima smisla.
{38269}{38336}Sa svim ovim,|moûda samo postaje oËajan.
{38340}{38428}- To se deöava, zar ne?|- Da, ali zaöto?
{38432}{38518}Nismo mu ni blizu.|I on to zna.
{38531}{38574}Da li imate razloga za brigu?|Da li postoji...
{38577}{38646}serijski ubojica koji je na slobodi?|- Da, mi tragamo za serijskim...
{38651}{38709}ubojicom, ali je prerano|donositi bilo kakve zakljuËke.
{38713}{38790}Ja samo ûelim da narod Montreala|bude upoznat sa situacijom.
{38794}{38883}Henri Bisonnette,|ronilac.
{38888}{38960}- Da li je to tijelo pronadjeno na gradiliötu?|- Da.
{38963}{39001}Njegova sestra ga je identificirala.
{39023}{39104}Radio je za njih par godina.
{39121}{39210}Rekla nam je da je|nestao prije par tjedana.
{39222}{39274}A njegova kreditna kartica|je koriötena svo ovo vrijeme.
{39342}{39442}Vidiö, sve öto mi je trebalo|je samo par dana.
{39452}{39500}Kakav je Ëovjek bio, öto znamo o njemu?
{39514}{39629}éivio je u malom apartmanu|i radio sa kompjuterima.
{39661}{39696}Nije imao puno prijatelja.
{39728}{39778}Da li radiö ti to nekada? Ronjenje?
{39792}{39862}Jednom je moja bivöa ûena|otiöla u club Med holidays,...
{39867}{39919}zaronila je 20 stopa pre nego öto se uplaöila.
{39927}{39989}- Nije mogla izdrûati.|- Sa takvim sisama, iznenaen sam
{39994}{40078}da je i mogla da zaroni.|- Zaranjanje nije problem.
{40090}{40133}Volio bih da je ostala dolje.
{40162}{40207}Ta ti je dobra.
{40317}{40380}Jeste li ronili nekada, agente Scot?
{40389}{40437}Ona isuviöe vremena|provodi sa mrtvacima.
{40442}{40490}Ne, nikada nisam ronila.
{40516}{40555}éao mi je jer ne znate öta propuötate.|- äto?
{40562}{40620}Ribe plivaju svuda oko|vas i ne smeta im öto...
{40622}{40682}ste tu. Dopalo bi vam|se, tiho je i mirno.
{40727}{40799}Imamo podudarnost sa crteûom.|- Gdje?
{40804}{40876}Negdje pored rijeke.|Ej... öta radiö to?
{40902}{40931}Ne idemo?
{40950}{41003}Nismo zavröili sa doruËkom.
{41396}{41466}- Prati me. - Hvala.|- Platio mi je u gotovini,
{41473}{41540}za tri mjeseca unaprijed i|od tada ga nisam viao.
{41543}{41607}Mislite da je to bio on?|- Da, siguran sam da je on.
{41629}{41738}Pre nego ga uhapsite.|Duûan mi je 90$ za telefonski raËun.
{41742}{41785}Da li biste se vi mogli|pobrinuti oko toga.
{41816}{41883}Znaö öto? Treba nam taj telefonski raËun.
{41938}{41991}- U redu. - HoÊete li platiti?
{46225}{46273}Sve je Ëisto.
{47074}{47115}Oh, sranje! - äto?
{47429}{47527}Vlasnik prsta je Clark Wiliam Edward.
{47539}{47668}Iz Vankuvera je. 34 godine,|privremeno je ovdje.
{47692}{47750}Kreditna kartica je|zadnji put koriötena juËer.
{47776}{47827}Joö nitko nije prijavio njegov nestanak.|- Dobro.
{47841}{47882}- I bolje öto je tako. - Zaöto?
{47894}{47937}Bilo bi dobro da mediji|ne saznaju za ovo ubojstvo.
{47944}{47992}To Êe ga iznervirati.
{47997}{48050}Ako bude bio iznerviran,|moûda i napravi greöku.
{48059}{48110}Sada treba slijediti|njegovu kreditnu karticu i...
{48112}{48160}to mjesto staviti pod nadzor.
{48182}{48242}ZnaËi pribliûavamo mu se.|- Samo joö neöto...
{48254}{48328}Onaj Kosta, on je Ëist.
{49874}{49925}Imate li kave i sendviË?
{50083}{50138}ZnaËi ovo nije koincidencija?
{50150}{50169}Ne.
{50198}{50256}Policajci pored galerije, nije ni to...
{50256}{50277}sluËajno, zar ne?
{50294}{50327}Da li ti to smeta?
{50361}{50438}Samo gledam iza sebe otkako se ovo|poËelo deöavati, da li znaö...
{50459}{50498}Drago mi je zbog druötva.
{50531}{50555}Kako se drûiö?
{50596}{50627}Ne mogu spavati.
{50656}{50685}To je u redu, ja...
{50701}{50773}Imam veliku izloûbu u petak i|hrpu novih slika koje moram...
{50773}{50807}prodati, inaËe ostajem bez love.
{50831}{50893}Zato se predajem samo poslu, kao i ti!
{51032}{51128}Jeste li naöli neöto...|jel' vam crteû pomogao.
{51135}{51169}Moûe se reÊi.
{51279}{51318}Neodreeni ste?
{51524}{51555}Dobro!
{51562}{51632}Te noÊi, da li se sjeÊate|jel' ûrtva davala otpor?
{51764}{51859}Trebalo mi je samo|par sekundi da vidim i...
{51864}{51900}shvatim öta se deöava...
{51931}{51999}Vidio sam öta namjerava napraviti,|vidio sam kamen u njegovoj ruci,
{52001}{52130}a onda sam ugledao Klivea Morana|koji se nije pomicao...
{52241}{52303}OK. A ipak ste mu pokuöali pomoÊi.
{52329}{52392}SjeÊam se. Mislim, ja... ja...
{52421}{52521}pokuöao sam mu pomoÊi,|uradio sam sve öto sam mogao, ja...
{52567}{52620}Uradio sam ono öto sam vidio na TV-u.
{52687}{52759}Sve vrijeme gledate u moje prste?|Ovdje me gledate?
{52773}{52811}- Da.|- Vi sve vidite!
{52814}{52907}Ne, ovaj... ovo je zbog... ja...|ja pravim svoje ramove,
{52917}{53044}samo znate,...|ponekad nisam baö spretan.
{53119}{53212}Koliko dugo to radite,|umetnost?
{53225}{53308}PoËeo sam posle ökole.
{53330}{53423}Bio sam na Tajlandu, znaö?|I ja...
{53427}{53513}Sreo sam Ëudnog starca|koji je bio slikar.
{53517}{53584}Ali nije imao novca|pa je samo...
{53588}{53670}Znaö, slikao je sve i svaöta.|Imao je ta vrata.
{53674}{53733}Ta neverovatna vrata koja je oslikao.
{53737}{53787}I dao mi je par od njih.
{53792}{53847}I tako sam ih doneo ovde|i prodao...
{53852}{53951}...za, pa znaö, ne baö puno novca,|ali sam mu ga poslao, novac.
{53956}{54036}Znaö? I to je bila sreÊa za njega.
{54048}{54132}I tako sam poËeo.
{54176}{54216}To je veoma lepo.
{54280}{54366}Volio bih vas poËastiti jednom kavom,|ali vidim da imate neki problem.
{54395}{54467}Pa, to je prvi korak da se prizna.
{54486}{54563}Da li je to vaö smisao za humor?
{54565}{54661}To je...! Sve to i... öta je ovo?
{54797}{54872}Broj mog mobitela, u sluËaju da...
{54874}{54946}se prisjetiö joö neËega.|Bilo öta öto bi moglo pomoÊi.
{54968}{54994}OK.
{55088}{55121}U redu, hvala.
{55171}{55241}Ako bi ûeljela doÊi|u petak na izloûbu.
{55246}{55279}Mislim da Êe ti se svidjeti.
{55284}{55327}To su Ëudna djela.
{55382}{55402}U redu.
{55598}{55673}Taj öto je bio u sobi, zvao|je ovaj broj bar 20 puta.
{55682}{55800}- Rebbeca Asher. - Ona tvrdi da ga je|vidjela na terminalu u Kuebeku...
{55802}{55857}prije tri tjedna.|- A öta znamo o njoj?
{55867}{55958}Ona je u kasnim öezdesetim|godinama, nema muûa i ûivi sama.
{56099}{56166}Potrudit Êu se oko nje.
{56222}{56262}Misli da Êu joj dozvoliti da se potrudi...
{56265}{56306}u vezi ovog jebenog sluËaja.
{56339}{56399}Ako se mogu potruditi|oko tvoje öale sa sisama...
{56404}{56447}mislim da mogu i oko sasluöanja...
{56452}{56469}ove ûene.
{56509}{56548}Ona govori francuski!
{56600}{56648}Znam da ste vidjeli sliku u vijestima.
{56651}{56708}G-o Asher da li biste je|ponovo pogledali, molim vas.
{56771}{56807}Naravno...
{56939}{56974}da li bi ovo mogao biti vaö sin?
{56994}{57025}Mogao bi biti...!
{57241}{57286}Prepoznala sam ga na feribotu.
{57291}{57375}Sa kapom na glavi, i|sav obrastao u bradu...
{57389}{57483}ali njegove oËi...|one se ne zaboravljaju.
{57598}{57672}A onda je poËeo Ëeöati uho.|To je njegova navika iz djetinjstva...
{57677}{57713}kada je nervozan.
{57720}{57775}Nisam ga uspjela odviknuti od toga.
{57809}{57874}Jesu li vas prije par godina pozvali...
{57876}{57924}da identificirate tijelo?
{57962}{58075}Pokazali su mi neke slike, jer su|mislili da ga je udario kamion.
{58149}{58238}Ne mogu reÊi da sam na neki naËin bila...
{58240}{58284}spremna na to. - Da, razumije se...
{58300}{58324}éao mi je.
{58483}{58552}- Da li smijem? - Da, molim vas...
{58742}{58890}- Ovo je?|- Ne, ne... to je Ris, Martinov stariji brat.
{58929}{59044}Stariji tri minute.|- Blizanci! - IdentiËni.
{59082}{59183}Da li je Ris dobijao neke|Ëudne telefonske pozive ili...?
{59247}{59346}Trebate znati, Ris je umro.
{59367}{59470}- éao mi je...|- Imali su 14 godina.
{59503}{59567}Otiöli su na splavarenje kod Saint Michela...
{59580}{59647}Te godine je bilo|veliko otapanje snega...
{59652}{59706}...i Martin je pao u vodu.
{59710}{59770}Ris je skoËio da ga spase.
{59795}{59855}Samo je Martin dospeo do obale.
{59873}{59952}To sigurno je bilo uûasno za vas.|- Jeste...
{60034}{60125}Bilo je za oboje. Znate Ris...
{60216}{60305}On je bio baö radoznao. Otvoren.
{60329}{60446}Otkako je umro, Martyn se|promijenio. Postao je nasilan.
{60497}{60580}Onda je pobjegao.
{60621}{60696}Policija ga je pronaöla poslije par dana.
{60722}{60758}»ula sam za nesreÊu.
{60825}{60926}- Ona je odliËna.|- Oh, da... ona je na odmoru.
{60981}{61074}- A ova?|- Oh... to je bila prva simfonija.
{61096}{61177}- »arobna flauta.|- Svakako... sladak je.
{61201}{61221}Bio je sladak.
{61290}{61321}Baö je bio sladak.
{61463}{61499}E to je Martin.
{61516}{61561}Morao je nositi te velike naoËale.
{61594}{61674}Nisam ih mogla razlikovati|ako ih nije nosio.
{61882}{61942}Moram uzeti torbu, zaboravila sam je...|- Ja Êu ti je doneti.
{62407}{62503}- Izvolite. - Cijenim vaöe vrijeme,|bili ste mi od pomoÊi.
{62535}{62594}Javit Êeö mi kada ga budeö naöla, zar ne?
{62604}{62630}Da, naravno.
{62882}{62971}Pa? - Koliko je ovdje vremena|potrebno da bi se tijelo iskopalo?
{63345}{63426}Po majci, Martyn Asher je imao|samo jednu slomljenu kost...
{63431}{63515}u svom ûivotu. Levi radius kada je pao sa stolice.
{63546}{63635}Ovo dijete ima dosta polomljenih kostiju.
{63640}{63709}Najviöe po licu, rukama i negovom torzu.
{63717}{63853}Ali... kako öto i vidite|levi radius je Ëitav.
{63858}{63916}Ovo nije tijelo Martyna Ashera.
{63963}{64038}Bolje da g-u Asher sklonimo|na netko sigurno mjesto.
{64261}{64350}Kako se sloûila da doe ovdje?|- G-a Asher zna sa rijeËima.
{64405}{64469}Mislim da krije neöto. Ima|neka vrata u njenoj kuÊi.
{64481}{64558}KuÊa je pod naöom zaötitom
{64560}{64613}ali to ne znaËi da je moûemo...
{64618}{64683}pretresati. - A öta kaûete|o velikom FBI agentu kome...
{64690}{64755}ovdaönja pravila nisu baö poznata?
{64759}{64803}E to je sad veÊ druga priËa.
{69114}{69173}Evo te...
{70466}{70552}- Scot!|- ILIANA, ISTRAéITELJ SA MJESTA ZLO»INA
{70557}{70607}MISLI DA JE UäAO KROZ PROZOR NA DRUGOM SPRATU
{70614}{70662}G-–a ASHER TVRDI DA NITKO NEMA NIKAKAV KLJU».
{70667}{70720}A OTISCI NAM JOä UVIJEK NIäTA NE GOVORE.
{70739}{70804}KAKO SE OSJE∆Aä? JESI LI OK?
{70816}{70878}- Dobro sam...|- DA LI SI SIGURNA?
{70888}{70938}- Dobro sam!|- ILIANA...
{71092}{71175}Da li bi sutra mogao sat vremena|ranije doÊi u kancelariju?
{71180}{71226}- Svakako! - Vidimo se tamo.
{71233}{71252}ZDRAVO...
{71379}{71470}Uzima éivote. To je ono|öto nam Martyn Asher radi...
{71473}{71492}20 godina.
{71502}{71581}Njegova prva ûrtva, John Dou,|bio je ûrtva prometne nesreÊe,
{71585}{71638}Ëime se on pokrio i laûirao vlastitu...
{71638}{71696}smrt. A poslije je uzeo njegov identitet.
{71701}{71780}Postoji praznina izmeu|smrti Johna Doua i Henri Bisonnette ali to...
{71784}{71841}ne znaËi da Asher nije bio aktivan.
{71845}{71942}- VicLAS nam je dao trag u vezi|19 ubojstava u istoËnoj Kanadi.
{71947}{71991}Najmanje 11 odgovara njegovom naËinu rada.
{71995}{72029}Svi koji su ûiveli skroman ûivot ili ne bi...
{72034}{72070}odmah nedostajali nekome.
{72079}{72142}Kako koga ubije, on|preuzima njegov ûivot,
{72147}{72182}ûivi u njegovom apartmanu,|koristi njegove...
{72185}{72226}kreditne kartice, Ëak|plaÊa i njegove raËune.
{72233}{72310}Niöta posebno, on samo ûivi svoj ûivot.
{72322}{72422}Zatim odbacuje njega i|preuzima Edwardsov ûivot.
{72434}{72513}Ali svi ovi muökarci imaju|neöto zajedniËko, Ëemu on teûi.
{72525}{72592}Jednostavno ûivot drugaËiji od njegovog.
{72639}{72681}Upoznala sam njegovu majku.
{72685}{72747}Asher je imao brata blizanca,|koji je njoj oËigledno bio omiljen.
{72752}{72798}On se udavio nesreÊnim sluËajem.
{72802}{72857}Ne bi mi trebalo puno|da je nateram da prizna...
{72861}{72947}...da ona misli da Martin ima|neöto s tim. Ona ga mrzi.
{72951}{73082}I tako on nemoûe da zamisli|da bude ono öto jeste.
{73091}{73172}Tako on zamjenjuje tijela.
{73200}{73236}On je kao kraba pustinjak.
{73240}{73327}Kako zavröi sa jednim telom|poËinje tragati za drugim.
{73357}{73472}ZnaËi on je negdje vani,|traga za svojom ûrtvom.
{73335}{73373}OK.
{73397}{73500}Netko samo öto je provalio|u Kostinoj galeriji.
{73464}{73533}Jedino öto nedostaje su|organizator i biznis podsjetnik? Niöta drugo?
{73551}{73583}- Alarm je preseËen.
{73587}{73682}ZnaËi, ovo ne liËi na normalnu provalu?
{73694}{73761}äto se noÊas desilo, g-ne Kosta?
{73766}{73852}Sluöajte, sva djela koja öaljem|za Europu öaljem noÊu.
{73857}{73926}äaljem poöiljke noÊu.|Ja sam tu, odem popiti...
{73929}{73989}kavu u restoranu preko|puta, a kada sam se vratio...
{73994}{74058}vrata su bila öirom otvorena|i sve je nestalo.
{74066}{74135}Mislite da je on?|- Dat Êemo vam par policajaca...
{74140}{74207}koji Êe biti u vaöem apartmanu,|g-ne Costa. éelimo biti...
{74209}{74269}sigurni da ovo niöta ne znaËi.|- To je odgovor na moje pitanje.
{74279}{74336}NA PICU SA CLARKOM|EDWARDSOM "LES FRERES".
{74370}{74464}Da li se trebaö vidjeti sa|Clarkom Edwardsom veËeras?
{74476}{74540}Da! On je potencijalni kupac.
{74583}{74639}Zvao me juËer.
{74679}{74725}Mogao bi biti dobar klijent.
{74809}{74840}Dali se ti to öaliö samnom?
{74871}{74919}Imamo policajce koji su na|tajnom zadatku i paze na vas...
{74924}{74974}svo vrijeme.|- Najbolji tim za osmatranje.
{74981}{75056}Mi joö uvijek govorimo o istom|tipu koji masakrira lica...
{75058}{75121}ljudima i sijeËe im ruke?
{75142}{75207}Ne moûete biti sami, ok?
{75221}{75284}To Êe biti od velike|koristi za grad Montreal.
{75336}{75396}Zaista je jako opasno da|se bilo öta radi, ali to...
{75401}{75447}nam je najveÊa öansa da ga uhvatimo.
{75542}{75650}- U redu?|- U redu, u redu...
{75682}{75789}Samo u sluûbi velikog grada, Montreala.
{75914}{75967}ZnaËi on Êe me Ëuvati?
{75981}{76032}Da li me moûe agent Scot|otpratiti do kuÊe?
{76139}{76195}Trebao sam ostati u Vinipegu.
{76216}{76281}Imao sam finu galeriju,|slike na zidovima...
{76288}{76358}nikad nitko nije uöao...|- Da si ostao mi ne bismo imali...
{76362}{76425}svjedoka koji bi nam|dao toËan opis ubojice.
{76439}{76473}A to je velika razlika.
{76547}{76612}Pa... to je zaista velikoduöno|ako se gleda na taj naËin.
{76614}{76681}- Levo?|- Ne samo napred, samo da proemo...
{76943}{77029}Da li smijem... da li te mogu|pitati neöto...?
{77055}{77163}- Da.|- Kako radiö ovo? Kako ûiviö...
{77168}{77278}okruûena svim ovim...|ovom grozotom, mislim...
{77286}{77367}ubojice i... ûrtve i... slike...
{77420}{77482}Zanaö, ja sam samo mali|dio svega ovoga, ali...
{77492}{77530}ti ûiviö sa ovim svakog dana, zar ne?
{77535}{77583}To je moj posao.|- Postoje razliËiti poslovi.
{77597}{77652}Postoje bolja radna mjesta.|- Ne i za mene, znaö da...
{77655}{77753}- 219?|- Da, da, da... ovde.
{77772}{77895}- Kaûeö to kao da je neka kazna.|- Nije kazna.
{77918}{77972}To je viöe kao poriv.
{78272}{78320}Okay, tu smo.
{78335}{78384}äta te pokreÊe?
{78571}{78620}äta te pokreÊe?
{78731}{78819}U redu. Kada sam imala 12 godina...
{78823}{78896}...Ëula sam neku buku iz prizemlja|i mislila sam da je to moj otac.
{78900}{78971}I... I tako sam siöla dole.
{79003}{79068}A neko je provalio|u naöu kuÊu.
{79075}{79211}Video me je i krenuo je prema meni.|A ja sam zgrabila noû i pojurila na njega.
{79215}{79259}I ubila sam ga.
{79280}{79376}Imao je 16 godina.|Verovatno je hteo da ukrade TV.
{79427}{79475}Ali ja sam ga ubila.
{79513}{79547}To me pokreÊe.
{79691}{79775}- Da vas otpratim do vrata, gospodine Kosta?|- Da, hvala. Ja...
{80031}{80104}äta gospodin Agent Scot|misli o svemu ovome?
{80116}{80159}Nisam udata.
{80163}{80227}Ja samo... Ja je samo tako nosim.
{80279}{80375}Sluöaj, sutra... biÊe sve u redu.
{80411}{80447}Potrudi se da se dobro naspavaö.
{80473}{80531}Onda, vidimo se sutra.
{80879}{80951}Postoji li neki signal koji bi|vam poslao, ako mi bude...
{80953}{80975}bila potrebna pomoÊ?
{80987}{81099}Nema potrebe. Mi te Ëuvamo.
{81099}{81162}Imamo petoro unutra|i dosta njih vani.
{81166}{81236}Zato ne brini, ako se|pojavi skoËit Êe na njega.
{81245}{81289}E ovo bilo utjeöno.
{82290}{82322}Je li sve u redu?
{82326}{82389}- äta?|- éeliö li joö jedno?
{82393}{82467}- Da napunim?|- Oh, da. Da.
{82471}{82538}- Viski?|- Da.
{82866}{82933}- Kasni.|- Da.
{83562}{83600}DA SE NA–EMO U TOALETU.
{84007}{84077}Samo öto sam dobio poruku.|Piöe da se naemo u toaletu.
{84927}{84975}Idem u muöki toalet.
{85805}{85858}Da se naemo vani.
{85942}{86009}Dovraga, öta se deöava?|- Rijeöili smo prekinuti ovo.
{86014}{86081}Sjedim unutra dva sata!|- Namjestio nam je.
{86088}{86143}Namestio nam?|äta to treba znaËiti?
{86148}{86191}Jel' vas vidio, zna öta se|deöava, zna da suraujem...
{86193}{86251}sa policijom?|- Samo polako, ok?
{86256}{86320}Ja da se smirim, a...?|Jesi li pecao ribe nekada?
{86332}{86371}Mamac uvijek umire.
{86623}{86714}Samo da vam osiguram|soËan dokazni materijal.
{86738}{86843}Samac, umjetniËki diler, koji|ûivi u konstantnom...
{86848}{86896}i organiziranom kaosu.
{86915}{86987}Naoruûan je vatrenim oruûjem,|iako ne zna kako se koristi...
{87006}{87085}Sve to zbog laûnog oseÊaja|osobne sigurnosti.
{87176}{87239}Da znaö, moûeö uÊi.|- Ne, u redu je, hvala.
{87291}{87342}Vas dvoje na vratima.
{87375}{87452}BiÊeö siguran. Imamo|dvoje na terasi, dvoje...
{87457}{87486}u hodniku, ok? - OdliËno.
{87627}{87692}Idem joö jednom provjeriti na ulici.
{87697}{87749}OK. ZnaËi, ako ti zatrebam|znaö gdje me...
{87754}{87809}trebaö traûiti? - Da. Tamo u baru.
{87821}{87877}- U redu je...|- Ne, ja... stvarno bih volio da...
{87881}{87987}se nisam uspaniËio. Nikome nisam pomogao...
{88001}{88073}- OdliËan si bio. - Ti bi voljela da...
{88076}{88152}budem siguran u sebe.|- Ti si dobar. - Oh, ne...
{88186}{88239}To je poljubac smrti!|- Kako to misliö?
{88291}{88342}Fin momak nikada ne dobija djevojku.
{88538}{88586}Trebam iÊi.
{88596}{88634}Dalje od prozora.
{88929}{89015}ZnaËi, idem. - Zaöto ideö?
{89035}{89116}Moj posao ovdje je zavröen.|Moûete raditi na sluËaju,
{89118}{89152}imate svjedoka, neÊu|vam biti potrebna viöe.
{89159}{89315}Ali Ileana, treba nam netko ko mu moûe uÊi u glavu.|- Ali vi imate osumnjiËenog.
{89320}{89357}To moûda nije dovoljno...
{89406}{89464}- äto se zaista ovdje deöava?|- Niöta.
{89502}{89555}Molim te, öta je?
{89610}{89665}Moûda imam reakciju na svjedoka.
{89682}{89708}Reakciju...
{89749}{89792}Pozitivnu.
{89821}{89862}Takvu da mi moûe pomutiti rasuivanje.
{89886}{89907}Razumijem.
{89994}{90025}Ileana...
{90039}{90125}- Koliko vremena se znamo?|- 6 mjeseci.
{90140}{90202}Koliko puta sam te zvao na piÊe?
{90217}{90298}- Koliko puta si odbila?|- Svaki put.
{90315}{90389}Mislim da treba dosta toga|da se tebi pomuti rasuivanje.
{90401}{90464}Sluöaj, moram uhvatiti|tog tipa. Znam da ga i ti moraö...
{90468}{90492}uhvatiti.
{90502}{90545}Ja vjerujem u tebe.
{90593}{90641}Molim te.
{90950}{91020}G-ne Kosta, vaöi prvi klijenti su stigli.
{91243}{91298}Barem je hrana dobra.
{91317}{91392}Da, zato öto su slike sranje.
{91432}{91492}Potrudite se da ne liËite toliko na policajce.
{91775}{91873}- Ne mogu te zamisliti bez mrtvog|tijela kraj sebe. - To je baö fino!
{91926}{91998}Bolje je zvuËalo u mojoj glavi. HoÊeö piÊe?|- Ne hvala.
{92003}{92075}- To je samo voda.|- Hvala ti.
{92130}{92226}IspriËavam se.|- Ovo je moja omiljena, ova...
{92243}{92336}ne znam, nebo... nebo me podsjeÊa|na odrastanje u Novoj äkotskoj...
{92401}{92504}- Gdje si ti odrasla?|- Pored Harisburga, Pensilvanija. - Da?
{92516}{92545}Ti si sa sela?
{92571}{92626}- Moûeö se sada|vratiti na posao. - Hvala.
{93329}{93365}On!
{95721}{95779}ZnaËi opet je na slobodi.
{95786}{95849}Izgubio se u masi.
{95884}{95971}I Kosta? - Potresen je,|ali nije povrijeen.
{96002}{96050}äto mislite, koji je|njegov slijedeÊi korak?
{96055}{96119}Mislim da sa Kostom|ima nezavröena posla.
{96139}{96213}Sutra öaljemo Kostu avionom|za Toronto, ujutro u 8 i 30.
{96251}{96328}HoÊu da ga jedan od vas|osobno odveze do aerodroma.
{96338}{96383}Ja idem. - Slobodni ste.
{96633}{96707}Samo ove da ponesemo.|- Kasnimo.
{96712}{96748}Da, znam, znam...
{97954}{97997}Zdravo James.
{98018}{98057}Gdje ideö?
{98258}{98306}Ne odlaziö?
{98349}{98414}Ma daj, poslije ovako zanimljivih igara?
{98428}{98483}Poslije ovoliko vremena|koje sam potroöio na njih?
{98543}{98577}Sjedni.
{98675}{98730}Ispred tvog apartmana|je jedan policajac.
{98762}{98853}Nisam mogao da ne primetim,|ti si se spakirao!
{98949}{99083}I to nije ok!
{99244}{99301}Mislio sam da ja i ti|imamo poseban odnos.
{99318}{99380}A to zahtjeva veliko poötovanje.
{99387}{99464}OËigledno ti ne razumijeö.|Zato Êu ti ponovno...
{99467}{99486}objasniti.
{99500}{99577}Ti imaö neöto öto ûelim.
{99591}{99689}I zato je to moje.
{99704}{99805}Zato, nemoj mi bjeûati.|To se ne smije desiti.
{99833}{99881}HoÊu da mi neöto odgovoriö.
{99910}{99953}äto si rekao policiji za mene?
{99984}{100044}äta znaju o meni?
{100574}{100675}POMO∆! POMOZITE MI! POMO∆!
{100900}{100929}Baci ga!
{100996}{101044}Rekao sam, baci ga!
{101938}{102008}Agente Scot, policajac je|pogoen na 219 St. Henry.
{102130}{102147}Sranje.
{105095}{105124}Da li je mrtav?
{105247}{105311}PomoÊ! Da li je mrtav?
{105323}{105382}- Ubio je Duvala.|- Baci oruûje!
{105387}{105416}To je on!
{105420}{105475}- Baci oruûje!|- To je on. To je Asher!
{105479}{105530}- Baci oruûje!|- Ubio je Duvala.
{105544}{105599}Kreni, kreni! Idi!
{106380}{106440}Imao je sreÊe.|Ovakva nesreÊa...
{106464}{106546}...a samo par öavova. - Da li znate|kuda vas je vodio g-n Kosta?
{106560}{106589}Nemam pojma.
{106649}{106719}Mislim da je hteo da doda|gospodina Kostu svojoj kolekciji.
{106762}{106831}éao mi je... inspektora Duvala.
{106850}{106894}éelio je spasiti mi ûivot.
{106906}{106994}I öta Êemo sada raditi?|- Mislim da je gotovo.
{107004}{107073}Aöerov DNK se poklopiti sa|dlakom naenom na tijelu ûrtve.
{107095}{107121}ZnaËi sve je gotovo.
{107172}{107236}Trebat Êe nam vaöa izjava.|Malo papirologije.
{107251}{107316}Sada kada je mrtav sve je gotovo.
{107356}{107431}Bili ste baö hrabri danas|u autu, g-ne Kosta.
{107522}{107546}Vi ste odliËni!
{107627}{107656}Hvala...
{113103}{113151}Dobar dan, mogu li vam pomoÊi?
{113154}{113199}Da, hoÊete li pozvati|g-cu Scot, molim vas?
{113295}{113367}éao mi je gospodine, jasno je|zatraûila da je nitko ne uznemirava.
{113377}{113410}Mogu li ja primiti|poruku i preneti joj?
{113427}{113446}Ne.
{114890}{114942}Ej! Ej...
{115089}{115122}Samo öavovi.
{115276}{115323}Kao da vam se od predhodne|noÊi rana otvorila.
{115345}{115403}Moram da ponovo uöijem neke.
{115611}{115695}- Umaju umetnost dole, zar ne?|- äta?
{115704}{115755}Dole u Washingtonu, D.C.
{115759}{115861}Ti politiËari, vole da veöaju|stvari na zidove, zar ne?
{115865}{115928}Samo kaûem, mogu da otvorim...
{115935}{116028}Znaö, galeriju.
{116040}{116100}Mogu da naem prostor tamo.
{116113}{116169}Imaju galerije tamo, zar ne?
{116219}{116268}Oh, Boûe.
{116359}{116420}Gde je? Oh, moj Boûe.
{116472}{116503}Scot!
{116532}{116565}Tu je?
{116587}{116635}Ne, u bolnici sam...
{116709}{116748}Odmah dolazim. OK.
{116786}{116815}Leclair.
{116844}{116906}- Moram smjesta krenuti.|- IspriËavam se.
{116990}{117038}HoÊeö li... vraÊaö se? Dolazim li ja?
{117086}{117134}Kasnije, ok. - U redu.
{117215}{117244}U redu.
{117325}{117361}Kako ti je stopalo?
{117383}{117457}Znam da je ovo baö neprijatno|za vas, g- o Asher, ali ako biste...
{117460}{117524}ga mogli identificirati.
{117553}{117582}Razumijem...
{117767}{117798}Ne dodirujte tijelo.
{117829}{117901}Dodirivat Êu sve öto poûelim.
{118426}{118474}Luda stara krava.
{118630}{118678}G-o Asher! G-o Asher!
{118814}{118846}Zdravo majko.
{119419}{119467}Sve öto sam htjeo je...
{119522}{119570}samo da te volim.
{119608}{119658}Ali mi nisi dala.
{119682}{119781}Uvijek je bio samo Ris.|Mogla si me imati zauvijek...
{119783}{119829}ali ti...
{119867}{119965}si uniötila to... ti si uniötila... sve.
{120114}{120210}Pomakni se od mene.
{120267}{120325}Ja te se ne plaöim.
{121482}{121571}Ileana!? Ileana!
{121712}{121815}Kosta je uradio sve to...|Kosta je on... Kosta je Asher.
{121825}{121909}- äto kaûeö? Oh sranje...|- IspriËaj mi!
{121911}{121974}- Gdje je? - Gdje?|- Tamo dolje...
{121979}{122026}- Dolje? Gdje? - U kom?
{122974}{123014}Ajde...
{123338}{123415}Ej ËovjeËe... ovi su ispali|iz maöine, jesu li tvoji?
{123424}{123475}- Hvala ti kompa!|- Da, ja ustvari...
{123698}{123811}ZnaËi ne vjerujeö nam, ali njoj dovoljno verujeö|da doe ovde i pojebe naöeg ubicu.
{123820}{123840}- SluËaj je bio zatvoren.
{123845}{123899}Uradila je vrlo profesionalno.|- Sranje!
{123951}{124023}Reci to Duvalu. SjeÊaö se Duvala?
{124027}{124094}I pasjeg kopila u mrtvaËnici!
{124141}{124208}Znam kako se osjeÊaö.|- Ako imaö reÊi neöto...
{124211}{124249}zaöto ne bi rekao meni osobno?|- äto? äto si rekla?
{124256}{124338}- Ako imaö neöto za reÊi...|- Paket!
{124732}{124806}Protekle 4 godine,|sam skaut za ligu.
{124810}{124897}Quebec, Alberta, Manitoba, Bc proöle godine.
{124901}{124959}Gdegod Ëujem o nekom izuzetnom klincu.
{124806}{125008}- Ti uvijek putujeö negdje.|- Da, navikneö se poslije...
{125013}{125051}nekog vremena.
{125053}{125104}- Sigurno je teöko tvojoj ûeni.|- Ne, nisam oûenjen.
{125108}{125166}Nisi? A da, ûiviö sa sestrama...?
{125185}{125267}- Susan i Debby.|- Gdje su one?
{125300}{125324}Kod kuÊe.
{125377}{125435}Tamo se igra hokej.|- Isuse, niöta se drugo i ne...
{125437}{125509}radi u tom jebenom gradu.|- Jesi li igrao kada si bio dijete?
{125521}{125578}Da, pomalo. Bio sam u timu dvije godine.
{125595}{125672}Stvarno? Mogu vidjeti,|mogu vidjeti svu tu...
{125681}{125761}individualnu samouvjerenost|öto izlazi iz tebe zato öto...
{125765}{125787}si bilo zlatan momak.
{125792}{125823}NaËin na koji puöiö...
{125833}{126017}Glas... tako dubok...|da klinci nebi shvatili kakvi ste luzeri postali.
{126034}{126082}äta priËaö ti ËovjeËe?
{126107}{126146}Ne uzbuuj se.
{126271}{126341}- To je Cristopher Heart.|- äto znamo o njemu?
{126350}{126427}On je narkoman, i krade umetniËka dela.
{126442}{126557}Kosta mu je prodavao ukradena umetniËka dela.|Kosta mu nije plaÊao.
{126566}{126617}Heart je htio samo svoju lovu.
{126621}{126679}Dugovao mu je viöe od 80000 dolara.
{126727}{126765}- Kosta mu je namjestio. - Da...
{127341}{127377}ZDRAVO... JESI LI TAMO? 
{127441}{127489}Ja sam.|- Tko je to?
{127568}{127600}ZNAä TI TKO JE.
{127629}{127723}Ajde Iliona. Ti se nisi|zaljubila u Jamesa.
{127737}{127823}Netko toliko lijep i moÊan kao ti...
{127847}{127950}ne pada na laûne dilere.|OK? U REDU?
{127955}{128034}IONAKO NIäTA NIJE VREDIO,|JA MU NISAM ODUZEO...
{128037}{128097}éIVOT, JA SAM NEäTO NAJBOLJE|äTO MU SE DESILO U éIVOTU.
{128104}{128214}Pogledala si u njega i vidjela si mene.
{128252}{128339}A ja sam pogledao u tebe|i vidio samo tebe.
{128352}{128404}MI SMO ISTI.
{128419}{128483}Jebi se.
{128455}{128477}Jebi se?
{128500}{128563}Jebi se? Da, ja jesam jebao tebe.
{128575}{128635}SjeÊaö se kada smo vodili ljubav sa|svim onim mrtvim ljudima na slikama...
{128637}{128668}oko nas?
{128680}{128845}BUDIMO REALNI ILIANA,|OBI»NI LJUDI NEVOLE TO KOLIKO MI.
{128850}{128910}ONAJ MOMENT KADA SAM BIO U|TEBI BIO JE NAJBOLJI MOMENT...
{128915}{128942}U MOM éIVOTU.
{128944}{128992}A SADA SE OSJE∆AM JOä BOLJE.
{129026}{129069}Jednostavno mi sve ide od ruke.
{129222}{129256}- äto ti je rekao? - Gdje je?
{129263}{129304}Koristio je kreditnu karticu.
{129311}{129370}Kupio je kartu za vlak|za Moncton pre tri sata.
{129375}{129407}Tri sata, biÊe tamo za 20 minuta.
{129409}{129452}Pozovi mi direktora.
{129457}{129479}Ajde, idemo!
{130052}{130112}BiÊu dobro. Hvala ti.
{130467}{130524}OVDJE SAM, HO∆U KAVU,|IDEM DO RESTORANA...
{130531}{130579}PREKOPUTA, VRA∆AM SE|OVDJE, VRATA SU OBIJENA...
{130584}{130625}I MOJ RADNI STOL JE BIO U KAOSU.
{130694}{130733}OVO NIJE KOINCIDENCIJA?
{130958}{131006}POMO∆!
{132207}{132255}Policija!
{132619}{132680}Zatvorite sve izlaze.|Sad, sad! Uradite to smesta!
{132817}{132851}Ti.
{133491}{133534}POSLIJE PAéLJIVOG PROMATRANJA...
{133537}{133573}IZVEäTAJA SPECIJALNOG|AGENTA SCOTA IZ BIROA...
{133575}{133618}KANCELARIJA ZA PROFESIONALNU...
{133623}{133664}ODGOVORNOST IZDALA JE|NALOG ZA...
{133668}{133745}ISKLJU»ENJE, KAO POSLEDICU|LOäEG RASU–IVANJA...
{133762}{133824}I NEPRIMERENOG PONAäANJA|FEDERALNOG AGENTA.
{133834}{133896}BIRO éALI ZBOG GUBITKA|AGENTA TAKVOG KVALITETA.
{133911}{133992}ODLU»NI SMO U OVOJ ODLUCI,|I OBJE STRANE SMATRAJU...
{133994}{134033}DA JE TO NAJBOLJE RJEäENJE.
{134300}{134400}CARLISLE, PENSILVANIJA|SEDAM MESECI KASNIJE
{135364}{135416}Duöo, ti trebaö iÊi kuÊi.
{135457}{135495}Vani je straöno.
{135553}{135615}Hvala. Vidimo se.
{135673}{135726}- Budi paûljiva, ok? - BiÊu.
{139183}{139262}Nisam te htio uplaöiti. Sjedni.
{139320}{139372}Doi, doi, samo sjedni.
{139442}{139545}HoÊeö Ëaj? Ok, napraviÊu ti.
{139698}{139744}Da li ti... äta traûiö?
{139818}{139929}Traûiö... Ovo traûiö?
{139977}{140077}Stvarno si me zbunila.
{140104}{140173}Postavila si sve ovo po kuÊi.
{140245}{140279}Ovaj si stavila iza friûidera!
{140307}{140346}Jedan ispod kreveta!
{140389}{140432}Jedan u kupaonicu.
{140451}{140526}Sigurno si uûasno uplaöena|poöto si sama, a?
{140545}{140607}Jel' to? Plaöiö se?
{140717}{140789}Pratio sam sva ona deöavanja u Washingtonu...
{140852}{140969}za koja mislim da su laûna.
{140995}{141036}Sretni su öto su imali tebe.
{141046}{141082}Baö sretni...
{141106}{141168}A ti si odjednom... nestala.
{141206}{141238}Nestala si.
{141269}{141338}Ipak si ostavila par stvari?
{141391}{141446}Da te priliËno lako pronaem.
{141487}{141547}A sada kada nema policajaca u okolini..
{141588}{141638}ne javljaö se na telefon...
{141640}{141662}Izvoli.
{141789}{141825}Paûljivo, joö je vruÊe.
{141945}{142014}A onda sam te video kako rasteö...
{142074}{142122}i znao sam se da me Ëekaö.
{142201}{142264}äto nosiö? Blizance?
{142564}{142623}Svia mi se da odlazim u njihovu sobu.
{142640}{142695}Ima toliko ljubavi i topline.
{142734}{142858}Mogu ih zamisliti kako se igraju.
{142887}{142916}Kako se zabavljaju.
{142964}{143012}Ti i ja...
{143067}{143096}ih promatramo...
{143158}{143192}i smijemo se...
{143259}{143292}Ti i ja...
{143419}{143482}moûemo poËeti iz poËetka.
{143606}{143676}Moûemo to.|- Ne ûelim...
{143700}{143762}äto? äto to znaËi?
{143796}{143834}Da ne ûelim to.
{144002}{144072}éao mi je... to su naöe|bebe, stvarno mi je ûao...
{144081}{144144}Ovo nisu tvoja djeca, veÊ Jamesa Koste.
{144163}{144196}Ja ne znam tko si ti.
{144448}{144496}A zaöto bi rekla tako neöto?
{144544}{144616}Zaöto bi rekla takvo neöto?
{144625}{144690}- Povuci rijeË!|- OK, ok, povlaËim rijeË.
{144702}{144760}PovlaËim rijeË! - U redu!
{144791}{144846}U redu... Ajde ustani.
{144865}{144889}Ajde!
{144975}{145009}Ustani.
{145282}{145309}Da li si ok?
{145407}{145467}- Da li su djeca moja?|- Tvoja su. - Moji su?
{145544}{145582}Poljubi me.
{146414}{146467}NeÊu te ubiti.
{146474}{146522}Ovo öto Êu ti uraditi, proÊi Êe.
{146527}{146582}Samo ako uradim kako treba, zar ne?
{146589}{146623}Smiri se. U redu je...!
{146630}{146666}Opusti se. Sve je u redu.
{146790}{146843}OK, daj mi to.
{146915}{146951}Ajde sad...
{146963}{147006}Smiri se.
{147210}{147251}Daj to meni.
{147457}{147486}äta radiö...?
{147663}{147706}HoÊeö se smiriti?
{147706}{147776}NeÊu te povrijediti, ok?|Ne ûelim te povrijediti.
{147797}{147874}- HoÊeö se smiriti?|- Da! Da... da...
{148572}{148625}Sve öto si video...
{148663}{148704}ûelela sam da vidiö.
{148936}{148975}Jebi se.
{150126}{150162}HALO! INSPEKTOR LECLAIR!
{150185}{150255}- Leclair.|- ILIANA! ZABRINUO SAM SE.
{150277}{150315}DA LI JE GOTOVO?
{150339}{150377}Gotovo je. - ODLI»NO.
{150384}{150432}SAMO MIRUJ, ODMAH STIéEM.
{150459}{150504}BI∆U USKORO TU.
{150550}{150750}{C:$0000FF}{y:ib} PREVOD I OBRADA|{C:$0000FF}{y:b} »EDO FILM - by Lucifer 
{150775}{152275}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/7f6p|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
