{100}{700}Obrada by: DivX Genius ©2002|http://go.to/divxgenius
{725}{875}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{2652}{2697}Film Alena Parkera
{2750}{2805}PINK FLOYD - ZID
{21963}{22010}Polako. Budi oprezan.
{22289}{22342}- äta?|- Da li biste me stavili tamo?
{22344}{22418}- Onda, gde je tvoja majka?|- Otiöla je do prodavnice.
{22420}{22471}Da, uredu.
{22523}{22588}Kako je? Da li uûivaö?
{22744}{22772}Lepo, lepo.
{23038}{23119}Sad idi.|Idi.
{23168}{23220}Sad, öta sam ti rekao o ovome?|äta sam ti rekao?
{23222}{23318}Idi, idi sada. Zategni svoju praÊku.|Hajde. Zategni svoju praÊku.
{31871}{31951}»ekaj me, Pinki, ti pokvareni krvavko.
{31953}{32026}- To su moji metkovi, zar ne?|- Ne znam.
{32028}{32112}Hajde Tabs.|OdliËno je dole u tunelu.
{32114}{32173}Zar ne misliö|da bi moglo biti opasno, Pinki?
{32175}{32220}Ne. Ne budi lud.
{32512}{32576}- Da li si dobro, Tabs?|- Da. Malo me boli koleno.
{32777}{32819}- Hajde.|- Ne. Previöe je opasno.
{32820}{32894}- Mi Êemo Ëekati na voz.|- Daj mi baklju.
{33146}{33210}Pinki! Dolazi voz!
{33211}{33274}Silazi sa öina, prokleti idiote!|Dolazi!
{33342}{33421}Pinki, silazi sa öina!|Dolazi!
{33453}{33476}Pinki, silazi sa öina!
{33943}{33997}Ti!
{34036}{34125}Ti! Da, ti!
{34127}{34172}Stoji mirno, momak!
{35315}{35376}äta to imamo ovde, momak?
{35378}{35459}Misteriozne ûvrljotine?|Tajni kod?
{35489}{35548}Ne. Pesme, niöta manje.
{35550}{35604}Pesme, svi!
{35606}{35660}Ovaj momak ovde zamiölja|da je pesnik.
{35692}{35766}"Money, get back.|I'm all right, Jack.
{35767}{35847}Keep your hands|off my stack.
{35849}{35931}New car, caviar,|four-star daydream.
{35933}{36012}Think I'll buy me|a football team."
{36013}{36079}Absolutno ubre, momak!
{36080}{36163}Nastavi sa svojim poslom.
{36164}{36205}Ponavljajte za mnom:
{36207}{36287}Jedan ar je povröina pravougaonika...
{36289}{36346}Ëija je duûina 200 metara...
{36348}{36416}i öirina jednog lanca.
{38475}{38529}Pogreöno! Uradite to ponovo!
{38870}{38944}Ukoliko ne pojedete meso,|neÊete dobiti puding!
{39029}{39099}Kako moûeö da dobijeö puding|ako ne jedeö meso?
{39183}{39248}Ti! Da, ti momak!
{39250}{39332}Pesme, svi.|Ovaj momak ovde zamiölja da je pesnik.
{42009}{42120}Ponovo. Jedan ar je povröina|pravougaonika...
{42121}{42178}Ëija je duûina 200 metara...
{42180}{42249}i öirina jednog lanca.
{49217}{49392}Zdravo. Zdravo.|Ima li nekog unutra?
{49492}{49534}Da li me se seÊaö?
{49535}{49592}Ja sam iz matiËnog ureda.
{53727}{53766}- Halo?|- Da. Naplativi poziv...
{53768}{53824}za gospou Flojd od gospodina Flojda.
{53825}{53901}Da li Êete prihvatiti cenu|iz Sjedinjenih Drûava?
{54038}{54097}Pitam se zaöto je spustio sluöalicu.|Da li bi joö neko tamo...
{54099}{54151}pored Vaöe ûene, ser, trebao da odgovori?
{54243}{54303}- Halo?|- Sjedinjene Drûave zovu.
{54305}{54356}Da li nas Ëujete--
{54419}{54505}Vidite, nastavlja da spuöta sluöalicu,|i muökarac se javlja.
{65517}{65567}Oh, moj Boûe.
{65596}{65657}Kakva neverovatna soba.
{65756}{65802}- Da li su sve ove gitare tvoje?
{66164}{66214}- Boûe.
{66215}{66287}Ovo mesto je veÊe od naöeg celog stana.
{66623}{66682}- Voliö tubu?
{66758}{66833}Da li mogu da dobijem vodu?
{66913}{67003}- Da li mogu da ti donesem vodu?
{67397}{67487}- Oh, pogledaj ovu kadu!
{67488}{67549}Da li ûeliö da se okupaö?
{67812}{67903}- äta to gledaö?
{68053}{68123}- Zdravo? Zdravo?
{68309}{68348}- Da li se oseÊaö dobro?
{72044}{72134}- SledeÊi put, drkadûije!
{98799}{98888}Pogreöno! Uradite to ponovo!
{99081}{99147}- Da li se oseÊaö dobro?
{99468}{99523}- Jebi me.
{99524}{99605}Potpuno je iskrvario.
{99607}{99680}Ti pokvareno kopile,|nikada me nisi voleo, zar ne?
{100354}{100468}- Momak je asmatiËar.
{100470}{100544}- AsmatiËar!?
{100545}{100658}- On je umetnik!
{104209}{104240}- Dolazi sebi.
{104242}{104365}-Eto, vidiö?
{104367}{104457}- Kako se oseÊaö?
{112725}{112833}- Stavite ih uzazid!|- Uzazid
{112834}{112915}Eno jednog ispod reflektora|on ne izgleda uredu
{112970}{113084}- Stavite ga uza zid!|- Uza zid
{113086}{113195}Jedan izgleda jevrejski|I jedan je krtica
{113196}{113286}Ko je pustio svo ovo smeÊe u sobu
{113287}{113342}Eno jednog duva dûoint
{113343}{113448}I jedan ima taËke
{113449}{113553}Ako bi bilo po mome|sve bih vas streljao
{122122}{122195}Stanite!
{124963}{125005}Stanite.
{137727}{137775}Obrada by: DivX Genius ©2002|http://go.to/divxgenius
{137800}{139300}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
