{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1215}{1340}
{1408}{1533}Upravo Êete vidjeti|pravu uliËnu frku.
{1751}{1876}ALI G INDAHOUSE
{2278}{2357}Moj prijatelj vas je video sa|Ramon Camacho-om. - Nije istina.
{2344}{2389}Umukni kurvo!
{2472}{2536}Vrijeme je da vas|nauËim pameti.
{2540}{2628}Ne bi' to radio da|sam na tvom mjestu!
{2632}{2712}Bolje ti je da razguliö,|jer bi mog'o najebat'!
{2728}{2853}Ovo je moj kraj, a ove |cure pripadaju meni!
{2827}{2952}Pripadaju?!?!
{2860}{2985}To je vrlo seksistiËka izjava|o tim kuËkama.
{3082}{3207}Bonjour, J'ai ma appelle Ali.|(Zovem se Ali.)
{3161}{3286}J'habite in Staines.|(Ja sam iz Stains-a.)
{3701}{3843}Zbog tebe sam potroöio |svoju zadnju maramicu...
{3769}{3911}...viöe nemam ni jednu!
{3818}{3879}Hijo su chingada madre.|(Pitaj svoju mamu.)
{3886}{3957}Te crees chingon, cabron?
{3937}{3978}...No sabes que te puedo matar...
{3982}{4016}...pinche canario.!
{4036}{4058}To ti meni?
{4069}{4194}Obrati se ruci,|jer te glava ne sluöa!
{4163}{4288}Matalo! (Razvalite ga!)
{4305}{4373}Oprostite!
{4430}{4556}Neeeee...
{4996}{5021}Zapamti...
{5022}{5120}éivot je najvrijednija |stvar koju nam je Jah dao.
{6151}{6200}Baksuzi!
{6266}{6291}Spasio si nas...
{6303}{6363}...moram ti se zahvaliti.
{6450}{6490}Mili boûe
{6496}{6655}Ovo Êe zahtijevati nas obje
{6639}{6874}De da vam pomognem malo...
{7168}{7210}O, Tupac, ne!
{7313}{7368}Nema veze.
{7504}{7629}To baby, igraj se s jajima.|Dobar cuko.
{7548}{7605}- Ali, jesi li budan?|- Definitivno.
{7622}{7747}- Ali duöice, pa znaö li|koliko je sati?
{7694}{7745}A joö si u krevetu.
{7768}{7893}Lijepo je ustati rano ujutro...
{8161}{8246}- Al' je bolje ostat' u krevetu.
{8275}{8300}Uf, dobro je...
{8325}{8461}Nije lijepo igrati se sa svojim malim|kada ti je baka u sobi.
{8438}{8563}Hajde, danas moraö odrûati|predavanje. - Strava.
{8496}{8545}Ustaj iz kreveta...
{8720}{8776}ALI     MOJA KU»KA
{8796}{8851}P O ä T U J
{10360}{10384}Poötovanje
{10392}{10443}äta ima novo u Staines-u, kompa?
{10451}{10559}- Ima, kompa, kulirali malo.|Pili  dûin i us. Opuöteno.
{10567}{10591}- Opuöteno?
{10604}{10648}- Aha.|- Blago vama.
{10634}{10702}Dûezi, jel' si se ti to obuk'o u zeleno?
{10708}{10833}Znao sam! Ti to öurujeö sa |Eastside bandom, a?
{10816}{10866}Ajde da ga izbodemo!|- »ek' malo!
{10877}{10958}Mama mi je oprala ûutu majcu|sa burazovim plavim Ëarapama.
{10965}{11018}Dobro, al' reci toj glupaËi|da pranje obojene...
{11017}{11218}odjeÊe na 60 stupnjeva te|moûe koötat glave u getu.
{11217}{11326}Momci, pomerite se! Reko' sam vam |i prije da je opasno zbog poûara!
{11489}{11614}Briöi! |- SeöÊemo na klupu, ok?
{11762}{11800}Banda sa Eastend-a!
{11813}{11938}Vidi bandu sa Westenda ispred| njihovog dragocenog Centra, a?
{12111}{12283}- Eastside (istok) je najbolji!|- Westside (zapad) je najbolji!
{12192}{12267}- Eastside je najbolji!|- Westside je najbolji!
{12304}{12454}- Westside je najbolji!|- Eastside je najbolji!
{12456}{12501}Sranje, hteo sam da kaûem | Westside je najbolji!
{12516}{12641}Bez obzira, na naöem |ste teritoriju.
{12601}{12726}Kad proete Bumblebees|obdaniöte i skrenete na rotoru
{12698}{12822}neposredno prije parka|onda ste na Westside-u!
{12788}{12913}Baö nas briga!|- Jel tako?
{12853}{12978}Mama ti je tako debela, da|kad se prijavila da...
{12954}{13079}Ëisti kaveze u ZOO-u,|ljudi koji su prolazili su govorili...
{13054}{13179}pogledajte onog nilskog konja!
{13120}{13245}To nije poöteno!|To joj je zbog ûljezdi!
{13237}{13362}Idemo, pustimo ove pederËine!|- Mama ti je pederËina!
{13614}{13739}Uspori!
{13803}{13828}Staniiiiii!
{13883}{13936}Prati Eastside!|-Budala, poginut Êe!
{13955}{14058}Ej G pazi, eno Los|Andjeleske policije! - Da, pa?
{15082}{15155}»ek, Ëek, zakasnit Êu na|predavanje. Idemo!
{15173}{15290}ALI G  "BUDIMO REALNI"|(NAPREDNI TE»AJ)
{15240}{15315}Krak i kokain nas uniötavaju.|Zato kad se neki skinu...
{15319}{15356}zasluûuju naöe poötovanje.
{15375}{15500}Zato podrûimo Darena, koji|je Ëist od kraka veÊ 8 godina.
{15529}{15609}- 8 godina i 3 cetvrtine.|- Nema veze.
{15606}{15731}Ne ûelim, al' moram vam reÊi da |veÊina vas neÊe doûivjet' 11.
{15857}{15982}- PlaËko, plaËko.|Ti si homiÊ.
{15932}{16057}- Ej, neÊu to da Ëujem!|Kaûe se pederËina!
{16062}{16136}- PederËino, pederËino!
{16136}{16273}- Dobro je, ustanite. Sad Êemo|podijeliti ovonedeljne nagrade.
{16231}{16356}Prvo, svaka Ëast mom Andy-ju,|koji je konaËno dobio orden za tuËnjavu...
{16375}{16503}...i za napredno psovanje.|- Puöi dlakavi kurac mojoj dûukeli!
{16506}{16528}Poötujem!
{16548}{16673}Poöto si dobio svoj 5. orden,|zaradio si i drugi rez na obrvi.
{16680}{16806}Nadam se da Êeö jednom|dostiÊ' Tyron-a.
{16776}{16901}Tyron-e, ako budeö joö bolji,|morat Êemo ti Ëupat' stidne dlake.
{16879}{17004}- Ali ja ih nemam!
{16922}{17047}- Ali ja ih imam na milione!
{16989}{17191}Zapamtite, ako ne ûivimo  |u realnosti, mi smo niöta.
{17091}{17259}Zato, BUDIMO REALNI!
{17168}{17293}- BUDIMO REALNI!|BUDIMO REALNI!
{17273}{17398}- Na ulici, morate znati da Êe se|vaö kompa ûrtvovati za vas.
{17392}{17518}Zato poËnimo sa osnovnom|vjeûbom o povjerenju.
{17497}{17572}Jedan, dva, tri...
{17587}{17628}- Ali, moûemo li popriËati?|- Naravno!
{17659}{17784}- U vezi sa Centrom je...
{17713}{17838}Znam koliko ti znaËe|ovi Ëasovi koje dajeö...
{17792}{17892}i koliko djeca uûivaju...
{17899}{18024}ali vlada Êe nam|ukinuti sredstva...
{17974}{18099}...zatvaraju John Nike Centar.
{18143}{18268}- äta?! Kako Êe sad ova |djeca preûivjet u getu?
{18280}{18405}- Morat Êe iÊi negdje drugo.|- Negdje drugo?
{18329}{18454}Znate li koliko njima|znaËi ovaj centar?
{18393}{18518}A tek meni!? Ovo je duhovno |srediöte Westend-a.
{18526}{18651}ZnaËi nam kao Meka éidovima,|kao Kentaki piliÊima.
{18677}{18802}I ovdje je bilo kad |sam prvi put pipnuo Dûulinu...
{18813}{18938}- Ali... ne moûeö niöta uËiniti.|Bolje ti je da kaûeö djeci.
{19450}{19575}Nikad im neÊu dopustiti|da nas zatvore.
{19539}{19664}Budimo realni!
{19670}{19795}- VeËera sa belgijskim premijerom u 8,|kasnije brifing od pola sata.
{19771}{19834}I zamjenik premijera ûeli hitan|razgovor s vama.
{19835}{19860}- Ima li rezultate ankete?
{19866}{19991}- Oprostite. - A tu ste...|- Rae bih da ih nemam.
{19930}{20055}Po anketi, Gallop zaostaje 22 poena.
{19982}{20107}- äto je sa Morlingom?|- Zaostaje 23 poena.
{20041}{20166}Omladina nas masovno napuöta.
{20109}{20234}Svi nam sugeriraju da|smo van tokova.
{20167}{20299}- Moûda i jesmo.|Znam da ja jesam.
{20203}{20328}- Ne budite smijeöni. - HoÊemo|li izgubiti ove izbore?
{20268}{20393}- Nema öanse. U Staines-u nismo izgubili| posljednjih 20 godina i neÊemo ni sad!
{20373}{20519}Samo imamo problem |s imidûom.
{20430}{20556}Moramo naÊi kandidata|koji Êe ga poboljöati.
{20530}{20566}Nekoga mladog.
{20602}{20739}Nekog iz etniËkih skupina.|- Nekog tko je u toku.
{20681}{20806}- Upravo tako, premijeru.|- Gdje Êemo naÊi takvoga...
{20806}{20931}koji je intelektualno superioran,|koji nam moûe garantirati pobjedu?
{20878}{21003}- Vozdra gospoo Sue.|-Booyakasha.
{20917}{21042}Jel' moja Julia tu?|- Gore je.
{21012}{21137}- –e si mala, baö si mi|nedostajala danas.
{21102}{21227}Pravo si dobra.|Rado bi' ti skin'o gaÊice...
{21227}{21352}- Ali !|- O, e s' Julia...
{21280}{21406}- Prekini da 'vataö Ninu|i dolaz' 'vamo!
{21337}{21462}- Izvini, zabunio sam se.
{21364}{21489}- »udno je öto se nikad|ne zabuniö sa Tracy.
{21424}{21549}- Zdravo Ali.|- Zdravo.
{21508}{21633}Znaö da si ti jedina|moja kuËka...
{21591}{21716}...dama...
{21621}{21786}Kad zatvorim oËi,|mislim samo na tebe.
{21897}{21972}- Ali, otvori oËi.
{21949}{22087}- Oprosti, jer upalo mi je|neöto u oËi, jer okolo...
{22020}{22145}...lete neke muöice i dvije su|mi uletjele direktno u oËi...
{22229}{22354}- Ali G, bio si jako zloËest|i moraö biti kaûnjen!
{22321}{22446}Jesi li zloËest?|- Jesam...
{22412}{22536}- Koûa mi je tako suha, |zato ako si bio zloËest...
{22502}{22627}...moraö mi utrljati ulje u tijelo.|Posebno pazi na grudi i guzove.
{22648}{22773}- Dobro, moûe...
{22712}{22837}- Ali prvo moraö skinuti kapu!|Ti zloËesti zloÊko!
{22819}{22944}- Al' nikad je ne skidam!
{22867}{22992}- Ti skini kapu,|a ja Êu ovo...
{22941}{23066}- Dobro...
{23138}{23263}- A sad cu te pomusti!
{23206}{23331}- Ali...|- Pusti me joö malo.
{23277}{23402}- Budi pristojan, Alistere.|- Dûej Lo, zatvaraju nam Centar...
{23407}{23532}Zato idem u ötrajk glau dok|ga ne spasim ili ne umrem.
{23519}{23644}Stoga u sluËaju da se pridruûim Tupac-u|i Bigi-ju u nekom nebeskom getu...
{23643}{23768}...doö'o sam da te |zguzim zadnji put.
{23732}{23858}- Mislim da g. Johnson ima |neöto reÊi o tome...
{23789}{23914}- Jel' mogu gledat'?
{23809}{23934}- Nema problema, jel tako?
{23856}{23981}- Ali, ne Ëini gluposti!
{24171}{24296}Ona u stvari nije moja Julie.|OËigledno je da u stvarnom ûivotu izlazim...
{24260}{24385}... s mnogo lepöim curama.
{24304}{24429}Ali to su napravili kako|bih bio öto "pristupaËniji"...
{24371}{24496}kako bi i vi mislilli da bi' vas|prcn'o, Ëak i ako ste rugoba.
{24658}{24783}Ok, imaö joö 10 sekundi|do poËetka ötrajka...
{24731}{24856}- Joö, joö...
{24821}{24946}- Ok, poËinjemo ötrajk.
{24896}{25021}- Mr. G, zaöto poËinjete|ötrajk glau?
{25057}{25182}- Zbog pravde i ljudskih prava|spreman sam poloûit' ûivot...
{25172}{25297}kao i Martin Luther...|Van Drostis
{25322}{25447}Ovo je lokalni stranaËki|voa, Alan Swan.
{25387}{25512}Sastavlja izbornu listu.|- Velika mi je Ëast...
{25462}{25587}...oduvijek sam bio veliki|oboûavatelj...
{25502}{25627}- Imena, g. Swan
{25561}{25686}- Da...hm, imamo|3 kandidata koji...
{25696}{25834}...u potpunosti zadovoljavaju|postavljene uvjete.
{25757}{25882}Na vrhu liste je Andrew Hamilton,|doktor politiËkih nauka,
{25834}{25959}studirao na Oxford-u, |zavröio prvi u klasi.
{25915}{26040}- Jesi l' probo nove pileÊe filete?|- Pravo su dobri, je l' da?
{25988}{26113}- Aha, mrak su!|- Koji to sos jedeö s njima?
{26060}{26185}- Uh, Ëini mi se da je|sos za peËenje.
{26315}{26440}- Ne mogu izdrûat',|ne mogu!!!
{26566}{26691}- PileÊi filetiiiii!
{26683}{26808}- Super, sad moûemo iÊi kuÊi.
{26726}{26851}- E jebiga!
{26759}{26884}- Idem po kljuËeve.
{26831}{26956}- PoËinjemo iz poËetka... sad!
{26997}{27122}Ne!
{27157}{27282}- O, öta ima?
{27214}{27339}- Protestiram, ako nemate niöta protiv.
{27276}{27401}- E onda Êemo te pustit' na miru.
{27350}{27475}- O, fala.
{27395}{27520}- Samo joö neöto...
{27961}{28086}Digni se Veliki, digni se!|Daj da se malo najebemo...
{28067}{28192}Jenifer Lopez, Jenifer Lopez
{28192}{28317}Jenifer Lopez se mazi sa onom iz|Destiny's Child öto ima veliko dupe.
{28438}{28563}Vidi ga sad, vidi ga sad!|Pogledaj moje remek djelo!
{28589}{28714}- Stoko smrdljiva!
{28795}{28920}Uh Shep, ovaj je priliËno zahro'.|MoraÊu ga fino uglancat'.
{29002}{29127}- Doktorat iz ekonomije, 3 godine|na Harward-u, 34 godine...
{29105}{29230}- Swan, ima li ikakvog razloga da|Ëudno obuËenom, polugolom
{29225}{29350}Ëovjeku, vezanom za ogradu,|slijepi sluûbenik drka?
{29422}{29547}- Ignoriöite ga. To je neki lokalni idiot|koji protestira protiv neËega.
{29554}{29679}- Odveûite ga i dovedite ovamo.|- Ali nisam joö... - Dovedite ga, Swan.
{29768}{29893}Samo naprijed, do kraja|stepeniöta.
{30440}{30565}Pustime da ti radim svaötaaaa...
{30636}{30761}Jer veËeras mala,|rado bi' se odvalio s tobom.
{30848}{30973}- Ja sam Kate Hedges, osobna tajnica|zamjenika premijera
{30925}{31050}Izvolite, i... mislim da sad|moûete navuÊi hlaËe.
{31163}{31288}- Zdravo, ja sam David Carleton,|zamjenik premijera.
{31259}{31384}- Vozdra, ja sam Ali G, glavni MC |zbog kojeg ribe diraju svoje pice.
{31429}{31554}Broj nakon dva je...|- Tri
{31508}{31682}- Nisam Ali A, ni Ali B, ni Ali C,|ni Ali D, ni Ali... E???
{31719}{31844}Ni Ali...(abcdef)|F???
{31862}{31987}Nego Ali...|- G.
{31910}{32035}- Bravo, sriËete za|zlatnu medalju!
{32010}{32135}- Ovo mu je pravo ime i adresa.
{32078}{32203}- Reci mi, Ali, jel' radiö?|- Naûalost, odnedavno sam na berzi rada.
{32206}{32331}- Stvarno, od kada?|- Od prije 8 godina i 3 mjeseca.
{32280}{32405}- Ovdje piöe da si traûio|invalidsku pomoÊ.
{32346}{32471}- Da, u stvari spastiËan sam.|Imam straönu DJ povredu.
{32480}{32606}Joö nemam potpunu pokretljivost|svog glavnog prsta za miksanje.
{32654}{32779}Ali dole sve funkcionira.|O, da, da...
{32751}{32876}- Ali, sjedi na trenutak.
{32929}{33054}Jesli li ikad pomiöljao da|postaneö Ëlan parlamenta?
{32986}{33111}- Koji Êe mi to?|Sve sami kreteni!
{33048}{33174}- To je malo grubo. Ja sam Ëlan parlamenta,| pa zar me to Ëini kretenom?
{33138}{33263}- Da!
{33202}{33327}- Probajmo drukËiji pristup...
{33244}{33369}Postoji li iöta na svijetu |öto bi ûelio promijeniti?
{33338}{33463}- Da, htio bi' spasit' John Nike Centar.|OËigledno...
{33437}{33562}- Ako bi predstavljao Staines u Parlamentu,| mogao bi da uspeö u tome.
{33513}{33638}Bi li bio naö kandidat na|slijedeÊim (bi)izborima?
{33577}{33739}- Pa, iskreno, baö i nisam bi (sexualan).|Mislim, jesam sa 2 ûenske odjednom...
{33755}{33917}...ma, dobro, vidio sam na internetu|al' nikad mi ne bi bilo fino da mi
{33862}{33944}ga muökarac stavi, ili Ëak|da ga ja stavim njemu.
{33955}{34030}Znam da mnogi kaûu|nikad ne reci nikad, ali
{34032}{34126}siguran sam da Êe moja zadnja vrata|uvek sluûiti za izlaz, a ne za ulaz!
{34149}{34330}Kuûiö öta priËam?|- Razumijem.
{34239}{34364}Dobro, bilo mi je drago|öto smo se upoznali.
{34436}{34561}- Kasnije, mala.
{34880}{35005}Davide, öto radiö?|Ovaj je bio najveÊi kreten
{35019}{35144}kojeg sam ikad srela. Nikad ne |bismo pobijedili s njim.
{35086}{35211}- Znam! - Nastat Êe kriza u |vodstvu stranke.
{35186}{35311}Premijer Êe izgubiti i...|- A, tko Êe ga zamijeniti?
{35357}{35482}Ali ima 2 tjedna da izgubi|18 tisuÊa glasova.
{35437}{35562}Pripremimo ga za |predizbornu kampanju.
{35595}{35720}Vozdra, matori, ja sam Ali G,|predstavnik Stains-a.
{35708}{35833}O'ö glasat' za mene, a?|- Nema öanse!
{35821}{35946}- Dobro, kad sam veÊ ovde,|da li te zanima da uzmeö malo...
{35929}{36054}...marokanskog haöiöa,|stvarno je super shit... 
{35995}{36120}Dave, tvoj je red da se|posereö u poötansko sanduËe.
{36096}{36221}Uvela sam anti-nasilniËki|program u cijelu opÊinu
{36173}{36298}A problemi sa nasiljem u |ovoj ökoli su mali kao i uvek.
{36275}{36400}Evo ga Jonathan, koji je prije|imao problema sa nasilnicima.
{36388}{36513}- Ne Ëudi me, vidi malog!|Debeli bombarder!
{36568}{36693}Ej, 'oÊeö joö jednu krempitu?
{36754}{36879}Baö je debeo, zar ne?
{36790}{36915}O, piËka li vam materina,|mate-mate-materina.
{36929}{37054}Glasajte za G-ja, jebenog|G-ja, jer to sam ja.
{37015}{37140}Nek' sve kuËke kaûu: Yoooo
{37105}{37241}UDRUGA FEMINISTKINJA - STAINES
{37143}{37268}Glasajte za mene, jer ja znam|öto vi lezbaËe ûelite.
{37259}{37384}Potpuno vas podrûavam i imam|jako mnogo vaöih video kazeta.
{37406}{37531}Ako glasate za mene, predloûiÊu|smanjenje poreza na koûno remenje.
{37581}{37706}Zaöto ste tako ljute,|zar se ne slaûete?
{37664}{37789}Dame i gospodo, u cilju obiljeûavanja|proöirenja gradske VijeÊnice...
{37764}{37888}zamolili smo sve kandidate|da poloûe po ciglu.
{37843}{37968}Ali, da li bi bio ljubazan da prvi|postaviö jednu?
{37930}{38055}äto, ovdje?
{37954}{38079}Bili bismo poËaöÊeni!
{37990}{38115}Pred svima?
{38014}{38139}Naravno.
{38417}{38542}Nije loöe.
{38441}{38566}Ovo je jako vaûno!|Prije 10 dana bili smo...
{38520}{38645}14 poena ispred, a predzadnji|dan zaostajemo 8 poena.
{38618}{38743}Sluöaj, jesi li dobio manifest|koji sam ti poslao?
{38768}{38893}Imaö papira?|- Uhm... definitivno.
{39002}{39127}Imaö joö papira?|- Aha, definitivno.
{39172}{39297}Da, bio je od velike pomoÊi.
{39237}{39362}Imamo joö 30 sekundi,|hoÊete poÊi sa mnom?
{39310}{39435}Sretno!|Nemoj da se suzdrûavaö!
{39546}{39671}... u vjerojatno najvaûnijim izborima|u proteklih 10 godina...
{39656}{39780}VeËeras su s nama bivöi ministar|zaötite okoliöa i poznati politiËar
{39739}{39864}David Griffiths i novajlija|Ali G.
{39810}{39935}Ako ste joö neodluËni, vjerojatno|Êete se odluËiti nakon ove debate.
{39914}{40039}Ali, ako budete izabrani,|öto mislite uËiniti za Stains?
{40001}{40126}- Pa, recimo, spasiti omladinski |druötveni centar, zar ne?
{40072}{40197}- Nije valjda svrha vaöe politike|spaöavanje centra koji se slabo...
{40210}{40335}...koristi i crpi mnogo sredstava?|äto joö mislite?
{40327}{40452}- Joö?|- Da, sigurno mislite joö neöto?
{40517}{40642}- Pa, mislim da je jako vaûno...|sma-nji-ti  in-flaj-ti-ju...
{40708}{40833}takoer, in-ve-sti-ra-ti  u nehas.
{40883}{41008}nehaes...|Aaa, NHS (zdravstvo)
{40967}{41092}- »itate iz mojih papira!|- Ne Ëitam, sve sam...
{41031}{41156}smislio ranije, oËigledno|si ti prepis'o od mene.
{41095}{41220}Nisam bio ja.
{41137}{41262}- Pa onda mi vjerojatno moûete reÊi|svoje miöljenje o ERM (zaötita okoliöa)?
{41266}{41391}- Nema problema, prvi album|im je bio sranje, a da budem iskren
{41331}{41456}nisam baö jako u toj vrsti muzike.|- Vrlo iskreno mislim da glasaËi...
{41426}{41551}Stainsa zasluûuju bolje, vi pravite|sprdnju od ove debate.
{41503}{41628}- Molim? Jel' se ti to |gledaö u ogledalo?
{41570}{41695}- Samo od sebe pravite joö|veÊu budalu pred biraËima.
{41684}{41809}- Opet priËaö o sebi?
{41768}{41893}- Vi ste sramota za svoju stranku|i ljude iz Stainsa.
{41851}{41976}- Nije baö lijepo tako priËati|o svojoj mami.
{41925}{42050}- Sad Êu vam reÊi:|vi ste najgori kandidat
{42057}{42182}kojeg je ikad vaöa jadna|stranka ponudila na izborima.
{42127}{42252}- A ja Êu tebi reÊi...
{42392}{42517}...da si ga popuöio konju.
{42538}{42663}- Nisam, ovaj, popuöio konju.|VeÊ sam to raspravio...
{42691}{42816}sa öefom stranke i kao|öto sam mu objasnio, bio sam
{42835}{42960}sa prijateljem u lovu i spotaknuo|sam se na konjski falus,
{42991}{43170}koji je zbog sezone|parenja, bio dignut.
{43299}{43424}- Zaöto odlazi?|Ideö probat' s ponijem?
{43716}{43841}Joö jedan dramatiËan dan na|izborima u Stainsu...
{43776}{43901}kandidat David Griffis je neoËekivano|podnio ostavku.
{43856}{43981}Sutra je glasanje, ostala su samo 2|kandidata, Thomas Alvares i Ali G.
{43969}{44094}Rezultat je vrlo tijesan za|bilo kakvu prognozu.
{44034}{44159}Thomas Alvarez, liberalni |demokrat, 5080 glasova.
{44235}{44441}Alistair Leslie Graham - Ko???|Koje glupo ime! - 5086 glasova! - Dobio si!
{44537}{44662}Proglaöavam da je Ali G izabran |za Ëlana parlamenta iz Stainsa.
{44846}{44971}E, o'ö da vidiö novog|zastupnika, a?
{44993}{45118}Gledaj kako se diram...|Je l' ti se svia?
{45135}{45260}Je l' te uzbuuje?|- Pa ne baö.
{45230}{45390}Bi l' poljubila gospodina Gurkina?|- Oh, dragi, tako si dugaËak i tvrd!
{45408}{45533}- To je ruËna!|- A sada, ajmo se kresnut.
{45893}{46018}- Jesi l' ga viöe stavio?
{46308}{46433}Poötovanje.|Poötovanje.
{46417}{46542}Ej, tebe znam, ti si onaj tip|öto su ga uhvatili sa onom kurvom...
{46572}{46697}Poötovanje!
{46731}{46856}Mir, mir!
{46779}{46904}Ekonomska politika ove vlade|ne samo da je neuËinkovita...
{46947}{47072}veÊ je korumpirana i|ne ulijeva povjerenje.
{47087}{47212}Ovaj nas zajebava.|Idem to rijeöit'.
{47244}{47370}Mir, mir!|- A pogledajte samo ovoga...
{47699}{47824}äto ovaj radi?|- Nemam pojma, premijeru.
{47972}{48097}Smiri se, pederËiÊu.
{48191}{48316}Pogledajte se...
{48246}{48371}sve öto radite je konstantno |meusobno prepucavanje...
{48347}{48472}R.. E.. S.. T.. E.. K.. P..|(respekt)
{48456}{48581}znate li uopÊe öto to znaËi?|- Restekp?!?!
{48637}{48762}Da, restepk!|- (respekt)
{48747}{48872}Kako se, tamo napolju,|neko moûe uzajamno restepkirati...
{48877}{49002}ako ni vi ovde ne poËnete| meusobno se restepkirati...
{48992}{49117}NaredniËe, izbacite gospodina!
{49029}{49154}Znate li kako Êemo poboljöati stanje|u ovoj drûavi? Jednostavno...
{49102}{49227}U dvije rijeËi:|DA BUDEMO REALNI!
{49190}{49315}To su tri rijeËi!?
{49222}{49363}Ne budi picajzla, "da" nije|prava rijeË. To je skraÊeno od "dakle"!
{49303}{49428}BUDIMO REALNI!
{49356}{49481}Zastupnik iz Stainsa Êe biti|izbaËen iz parlamenta!
{49427}{49552}Je l' to zato öto sam crnac?
{49477}{49602}Za boga miloga, |öto ste mi to uËinili?
{49551}{49676}éelim da mi taj idiot|doe ujutro u kancelariju...
{49618}{49743}sa svojom ostavkom.|Je l' jasno? - Da, premijeru.
{49728}{49853}Naprijed...
{49808}{49933}- »ujte, znam da sam pogrijeöio...|- Ali, jesi li Ëitao danaönje novine?
{49948}{50073}"BUDIMO REALNI"|progovara glas nove generacije
{50034}{50159}Oporbu konaËno utiöao|"Pravi Heroj"
{50175}{50300}Ne mogu vjerovati!
{50213}{50338}G-»AROBNJAK JE REALAN|(ötene igra ping-pong)
{50267}{50392}Postoji pas koji igra|stolni tenis!
{50315}{50440}Ali, to je tisak, oboûavaju te!
{50365}{50490}Ali kako moûe da drûi reket?
{50415}{50540}Ali, moj zamjenik i ja se pitamo|öto bi rekao ako te zamolimo...
{50549}{50674}.. da ueö u vladu?
{50585}{50749}Ne, razmisli malo, Ali ulazi u vladu,|usere motku i obojca padaju.
{50801}{50926}- Zaöto misliö da Êe Ali pristati?|- Zato jer sam predloûio premijeru...
{50895}{51020}...da mu ponudi spaöavanje|njegovog Centra.
{50969}{51094}- Jesi li poludio? Mislim to bi...|- Pusti me da zavröim...
{51039}{51164}ponuda da spasi Centar |ako mu Ali donese prednost |od 20 bodova na izborima.
{51178}{51303}äefe, mogu li sad kad sam u vladi,|bacit' pogled na crveno dugme?
{51304}{51429}- Mogu li ti vjerovati?|- Da...
{51362}{51487}- Dobro, evo...
{51469}{51594}Jedan pritisak na to dugme|moûe uniötiti cijeli svijet.
{51567}{51692}- Vrlo je zanimljivo to öto|govorite jer... - Ne!
{51689}{51814}Ali, molim te skloni se!
{51779}{51904}- Dajte samo da malo neöto razorimo.|- Ne dolazi u obzir!
{51838}{51963}- Molim vas. - Ne! - Ma samo |neko sranje kao npr. Walles?
{51960}{52085}»uo sam da vam je premijer|Walles-a mamu nazv'o kurvom!
{52007}{52132}Ja sam premijer Walles-a!
{52073}{52198}O, pa ne biste tako trebali|priËati o svojoj mami!
{52147}{52272}Sluöaj, tvoj prvi sastanak u vladi|je slijedeÊeg Ëetvrtka
{52206}{52330}S obzirom na diskusiju o azilantima,|öaljem te na specijalni zadatak
{52360}{52485}Ako bi netko pokuöao iöta|prokrijumËariti u Britaniju...
{52425}{52550}najvjerojatnije Êe probati ovuda.|I nisu u pitanju samo imigranti.
{52536}{52661}Pogledajte ovo...|Zaprepastit Êete se!
{52686}{52831}Pogledajte ovo smeÊe,|30 kila marihuane...
{52767}{52946}prokrijumËarene iz Europe,|Amerike i Bliskog Istoka.
{52847}{52972}To je... uûasno!|Ima li iöta skunk-a?
{52956}{53081}Ima, neko ubre je|prokrijumËarilo 15 kg ovoga...
{53058}{53183}NajjaËi superskunk|ikad naen!
{53197}{53322}Ovamo drûimo|oduzeto oruûje.
{53436}{53561}Mora da vam je ovdje|pravo zabavno, zar ne?
{53543}{53668}Ne, nije!
{53607}{53732}U ovom dijelu Ëuvamo|gomilu najtvre pornografije
{53685}{53810}veÊinom dolazi iz NjemaËke.|éelite li preskoËiti ovo?
{53778}{53903}Ne, moram odraditi posao!
{53957}{54082}Znam, i meni se gadi!
{54049}{54174}Dobro, sad moram napisat' izvjeötaj |pa bi' te zamolio da odjebeö.
{54157}{54282}Naravno, gospodine!
{54200}{54325}O, Westminster Êe mi poslati struËnjake|koji Êe mi pomoÊi u istraûivanju
{54390}{54515}Zdravo, mi smo struËnjaci.
{54796}{54921}Dobro, Ali, reci nam, öto si|otkrio u Doveru?
{54885}{55010}Pa, vidio sam mnogo toga, veÊinom|iz NjemaËke,|uglavnom ulaze otpozadi.
{55030}{55155}- Potpuno je u pravu! Sama sam |to iskusila u NjemaËkoj!
{55182}{55307}Svaka Ëast! - SjeÊam se, |jednom su se 2 ogromna crnca...
{55327}{55452}smjestila u tu malu kutiju|- Kol'ko su bili unutra?
{55496}{55621}15 sati! Bilo je straöno!|- Garant je boljelo, a?
{55630}{55755}Joö boli!|- ûao mi je.
{55705}{55830}Dakle, John, öto Êemo|sa tim azilantima?
{55796}{55921}Ne moûemo ih sve pustiti|u zemlju radi ekonomske stabilnosti
{55936}{56061}Reci, Ali...|- Razmislimo malo...
{56004}{56129}äto je najvaûnije Ëega nemamo |dovoljno u ovoj zemlji?
{56098}{56223}Bolnice? - Ne!|Knjiûnice? - Ma daj!
{56187}{56312}Fali nam zgodnih ûena,|a imamo previöe rugoba.
{56314}{56439}Bez uvrede, Karen.
{56382}{56507}Dakle, zaöto ne pustimo zgodne,|a one gadne vratimo natrag?!
{56499}{56624}Na taj naËin bismo rijeöili oba problema.
{56547}{56672}SprËili bismo dvije piËke|jednim kurcem, zar ne?
{56650}{56775}Ovo je suludo!|- äto ti misliö?
{56743}{56868}Mislim da trebamo|biti realni!
{56855}{56980}Zgodna!|Zgodna!
{56979}{57104}Stani, natrag u Sloveniju!
{57193}{57318}Obrazovanje je na najniûoj|razini u zadnjih 15 godina!
{57269}{57394}Da, pa naravno, kad djeca uËe|stvari koje im ne trebaju...
{57379}{57504}mislim je l' iko od vas ikad|koristio matematiku ili engleski?
{57576}{57701}PoËnimo djecu uËiti vaûnim |stvarima!
{57650}{57774}Dakle, ako Kevin kupi 6 grama|jamajkanske marihuane od
{57810}{57935}Debelog Tonija za 480 funti,|keö na ruke, i mora to podijeliti
{57880}{58005}na 11 svojih muöterija, koliko Êe naplatiti|jednu osminu, tako da zaradi 100 funti
{58028}{58153}da plati za alimentaciju svom djetetu?
{58101}{58226}Situacija u Sjevernoj Irskoj|izmiËe kontroli.
{58258}{58383}Jedini naËin da zaustavite te hinduse|da prestanu ubijati muslimane
{58368}{58493}- Radi se o katolicima i protestantima|- äto god!
{58452}{58577}...je da im date jedan zgodan komad|da im pokaûe svoje sifone zarad mira.
{58594}{58719}- Premijeru...|- Ne ti, ljubavi!
{58640}{58765}Vojska koöta porezne obveznike|4,2 milijarde funti godiönje...
{58780}{58905}Kako vlada namjerava smanjiti|ovu cifru?
{58869}{58994}UnajmiÊemo specijalce.
{58971}{59096}Njeno visoËanstvo, kraljica.
{59087}{59212}Vaöe visoËanstvo. mogu li |Vam predstaviti Ali-ja G, Ëlana |parlamenta Stanis-a...
{59577}{59702}Vozdra, komad!, Izgledaö puno|bolje uûivo nego na onim novËiÊima!
{59734}{59859}Da znaö, slijedeÊi put kad stavim|50 penija u dûep biÊe mi Ëast...
{59852}{59977}öto je tvoja glava tako blizu|mojih jaja.
{59921}{60046}Nitko ne radi. Nezaposlenost|je na najviöem stupnju.
{60087}{60212}Ova zemlja ima poseban odnos|sa Sjedinjenim Drûavama...
{60171}{60296}öto mislite o Bush-u?
{60218}{60343}Ja volim Bush (grm), mislim...|volim sve öto daje bolji
{60314}{60439}i puniji izgled zoni oko pice.
{60400}{60525}Da li biste otplesali za mene neöto?
{60615}{60740}O moj boûe!|- Obrijani raj! Respekt!
{60706}{60831}I dok utjecaj Ali G-a|nevjerojatno raste...
{61180}{61305}Do 12 sati sva RIZLA Êe biti besplatna...
{61265}{61390}Da bi se manje nosile,|uvodi se porez od 25 penija na gaÊice
{61406}{61531}Tange se ne raËunaju...
{61470}{61595}äto se tiËe zdravstva,|marihuana Êe biti besplatna...
{61587}{61712}...za lijeËenje|kroniËnih bolesti...
{61664}{61789}kao öto je|svrab od picajzli...
{61777}{61902}zatim...|ja sam öupËina...
{62007}{62132}Ja ne mogu ovo da...|- Nastavi, Davide.
{62123}{62248}Volim da ga primim u guzu.
{62219}{62344}Da, zaista i jako mi je |lijepo i najviöe to volim.
{62395}{62520}Bio sam ûensko i |nosio sam ötramplice...
{62476}{62601}...stvarno, pitajte moju mamu.
{62822}{62947}U Centralnoj Africi rat se razbuktava...|Britanija vodi pregovore o primirju...
{62940}{63065}Drûavni budûet predloûen od|strane najkontraverznijeg zastupnika...
{63128}{63253}Chequers: Prijem za afriËki summit.
{63599}{63752}To öto si mi kupio skupu odeÊu|ne ispravlja zapostavljanje u...
{63677}{63802}zadnja 3 mjeseca.|- Ma znam...
{63735}{63860}Sluöaj Ali, nikad nisam bila na|ovakivm prijemima, zato me ne|ostavljaj samu, moûe?
{63849}{63916}Ne brini, mala!
{64004}{64129}Vidi, eno ga premijer,|vidjela sam ga na TV-u,|da ga pitam za autogram?
{64100}{64225}Yo öefe,|ovo je moja Julie.|- Divno.
{64213}{64338}Da upoznamo delegate...|Ovo je predsjednik Watana|sa Tajlanda.
{64265}{64390}»ast mi je upoznati Vas.|-Tajland, a? Poklon.
{64420}{64545}Ali, idemo dalje. Oprostite.|Ovo je mongolski delegat...
{64577}{64702}Je l' on pravi monah?|Pa to je fantastiËno da ste i vi zastupljeni.
{64701}{64826}
{64824}{64949}NabaviÊu ti malo kreona.
{64983}{65108}- Idemo dalje.
{65099}{65224}Ovo je Borat iz Kazahstana.
{65223}{65348}Pozdrav.|-Drago mi je öto smo se upoznali.
{65314}{65439}Marö pederËino!|-Ali, u redu je. Molim, oprostite!
{65431}{65472}Puöi kurac!
{65698}{65823}Bonur!|- Kanape, gospodine?
{66654}{66778}Moja Julie...
{66908}{67033}Zdravo...
{67073}{67198}äto radiö ovdje? Zaöto nisi |dolje sa onim zgodnom ribom?
{67194}{67319}- Samo smo razgovarali|o politici...
{67242}{67366}- Baö me briga öto Êeö reÊi.|Umukni!
{67356}{67481}Stvarno? Ne ûeliö da|viöe priËam?
{67552}{67677}Stvarno si kreten!|Dolazi ovamo!
{67713}{67838}Hej, ne moûemo, ovo je|premijerova soba!
{67899}{68024}Dobro, onda se pretvaraj|da si premijer!
{68021}{68146}Moûe...
{68160}{68285}Dame i gospodo, molim vas...|s obzirom na sutraönji skup
{68276}{68401}imat Êu privatni razgovor |s obje stranke
{68347}{68472}zato prvo, predsjedniËe Muroku|biste li mi se pridruûili gore?
{68482}{68607}- Sa zadovoljstvom!|- Hvala!
{69364}{69488}Moram priznati da sam uûivao!|- I ja!
{69479}{69604}Tako mi je drago da smo svröili!|Dame i gospodo ûelim da svi...
{69617}{69742}znate da je predsjednik Muroku|veoma veliki Ëovjek!
{69702}{69879}- A ja ûelim reÊi da se premijer drûao|veoma kruto ali i uspravno!
{69890}{70015}Predsjednik je Ëitavo vrijeme|davao sve od sebe...
{70015}{70140}...dok sam ja zaglibio vrlo duboko.|- O, jako duboko!
{70115}{70240}No, iako smo imali nekoliko|nesuglasica oko privodjenja kraju...
{70187}{70312}...drago mi je da moram reÊi da|smo na kraju ipak svröili zajedno.
{70309}{70434}- Da, svidjelo mi se sve|öto ste mi ponudili!
{70407}{70532}PredsjeniËe Mupeba, biste li|mi se i vi pridruûili gore?
{70500}{70633}Nema teoretske öanse!
{70566}{70630}Mogu li ja?
{70847}{70972}Ajde, Ali, idemo kuÊi.|SkuhaÊu ti ono öto najviöe voliö.
{70976}{71101}Angel Delight (torta)?? - Da,|öeÊerlemu!
{71083}{71208}Mmmmm, öeÊerlema...
{71157}{71282}Ovaj dio je za cure, da vide|kako znam biti osjeÊajan.
{71298}{71491}Usput, ako je neka od vas zgodna|i voli otpozadi, evo mog broja mobilnog...
{71469}{71594}Oni koji zovu moraju imati|preko 16, ali ne baö mnogo preko.
{71688}{71813}Ne mogu. Sutra moram biti|na mirovnoj konferenciji...
{71817}{71942}- äto? äto je s ljudima|kojima stvarno trebaö?
{71940}{72065}äto je s Rikijem, sa Dave-om?|A öto je sa mnom, Ali?
{72100}{72225}Vrati se u Stains, molim te!
{72205}{72330}- Svijet je veÊi od Stains-a.|I ja ga moram spasiti!
{72417}{72542}E pa onda Êeö to morat' sam!|- Julie... Moja Julie?
{72666}{72791}Moram ga se otarasiti prije|no öto se spasi Centar!
{72748}{72874}- Mislila sam...|- Ti si mislila?!?!?
{72845}{72970}Amerika Êe pruûiti punu potporu |»adu u sukobu sa susjedima.
{72989}{73114}Rusija neÊe dopustiti da se |ova zapadna agresija nastavi.
{73112}{73274}U cilju podröke Burkini Faso,|spremni smo ustupiti svu naöu|vojnu silu.
{73321}{73446}To je neËuveno!
{73514}{73639}Zahuktava se, Ali, daj pomozi mi.|- OÊu, öefe.
{73610}{73817}Amerika se ne plaöi ovih prijetnji!|Namjeravamo u potpunosti|iskoristiti svu vojnu silu!!
{74212}{74337}Znaö li zaöto viËu?|Matorci joö nisu dobili svoj Ëaj!
{74357}{74482}Hajde, brzo, brzo.
{74653}{74894}Neka dignu ruke svi koji su za|to da se poöalje Iran dolje do|benzinske po Ëips i Ëokoladu!
{75107}{75232}Izvini sto smo vas napali.|Baö je bilo glupo.
{75240}{75365}Ma öta ima veze?|Ionako je to veÊ sve proölo.
{75323}{75448}A i ako Êe me neko zveknutu,|najrae bi da to budeö ti!
{75479}{75604}Pravi si!|Fino si obuËen!
{75594}{75759}Spasio si moje bijelo dupe, Ali.|- Nema problema, brate.|ûivio biljni Ëaj!
{75790}{75915}Hej ti, Britanijo!|- Poötujem!
{75966}{76091}Kako mu to uspijeva?
{76686}{76811}Znaö, Ali, prava smo ekipa!|ZahvaljujuÊi tebi, u plusu sam 22 poena!
{76851}{76976}Morat Êu spasiti onaj tvoj Centar!
{76961}{77086}Vidi paparazze!|- Da, Ëekaju tebe, Ali.
{77062}{77187}Ovo je tvoj trenutak.
{77273}{77398}HoÊete li komentirati optuûbe da|ste drogirali svjetske voe?
{77432}{77557}- Molim? - Imamo dokaze koji |vas okrivljuju!
{77572}{77697}Pa imamo dokaze koji|vas okrivljuju!
{77634}{77759}To je djetinjasto!|- To je djetinjasto!
{77706}{77831}Zar se joö viöe ne inkriminirate|ovom apsurdnom retoriËkom taktikom |ponavljanja reËenica?
{77819}{77944}Zar se ne "#$%! kriminirate|"!&%$"&% taktikom &%"&#|retorika &/!"#&"/#&
{77930}{78056}Ova vreÊica je jutros anonimno |poslana u moj ured.
{77991}{78116}PoriËete li da ste je ukrali|sa carine u Doveru?
{78077}{78202}To je moga biti bilo ko!|Kakve ima veze sa mnom?
{78149}{78274}ALI-jeva ROBA|NE DIRAJ!
{78180}{78305}Moram iÊi, sere mi se,|imam proliv.
{78334}{78459}O dragi, ode tvoj|druötveni Centar.
{78404}{78529}OËisti stol prije odlaska, hoÊeö?|Premijeru...
{79420}{79545}Drûi se Ali!
{79543}{79668}Nedostajat Êeö nam.|Poötovanje!
{79919}{80044}"Eastside je najbolji"
{80002}{80127}Bako, mogu li posudit' auto?
{81034}{81159}"Hvala za svo vrijeme |koje si mi dala..."
{81253}{81378}"...uspomene koje pamtim..."
{81557}{81682}"jednom, dvaput, triputa|dama..."
{81959}{82084}Imaö loö dan?|Moûda mogu pomoÊi?
{82086}{82212}Je l' je vlaûno vani?|- PriliËno!
{82212}{82337}- äta radiö ovdje?|- Da ti pokaûem...
{82324}{82449}Danaönje najnovije vijesti:|premijer je dao ostavku...
{82468}{82593}...nakon otkriÊa sigurnosne|video kazete, na kojoj se...
{82555}{82680}...vidi perverzan seks premijera|sa nepoznatom prostitutkom.
{82672}{82797}To nije prostitutka, to|je moja kuËka.
{82734}{82859}PoËev od 11 sati, zamjenik premijera|David Carleton Êe preuzeti duûnost.
{82870}{82995}Nije poöteno!|Ono nije bio premijer!
{82952}{83077}Zaöto ne pokaûu ostatak trake?|- Na ûalost, moj öef ju je zakljuËao...
{83052}{83177}...u sefu u svom novom uredu|u Checkers-u i tamo Êe ostati.
{83120}{83245}- NeÊe to tako proÊi!|- Ako ne budeö priËao...
{83230}{83355}David Êe biti jako dareûljiv.|Ja sam spremna biti...
{83377}{83502}...jako dareûljiva.
{83477}{83602}Samo trebaö...
{83518}{83643}...zaËepti...
{83585}{83710}...gubicu!
{83769}{83894}Zagrijavam svoju maöinu, Ali...
{83882}{84007}...napuni me benzinom
{83912}{84037}- NapumpaÊu te sa svojim|vrhunskim bezolovnim, aaaaj!
{84022}{84147}- Da ti vidim pumpu...|- Molim? A, oö da mi vidiö malog?|U redu.
{85123}{85248}Daj mi svoj ubrizgivaË goriva.
{85211}{85397}...i u sutraönjem glasanju pitat Êemo vas|da li ste spavali sa svinjiom. Ja jesam!
{85372}{85497}... i istraûit Êemo zaöto ovakve|devojke postaju drolje.
{85484}{85609}- NeÊe niko moju Julie|nazivat' droljom.
{85563}{85688}- Doi mami.
{85733}{85858}"Budimo REALNI"
{85880}{86005}Skini ih...
{86786}{86911}Ovo nije poöteno!|Podesi ga na vibru i zavröi sama.
{87322}{87447}Otvori, otvori.|Yo, brate, moraö mi pomoÊ'.
{87397}{87522}Na TV-u su nazvali moju Juliu droljom|- äta, Ëuli su kad smo je nas trojica...?
{87509}{87634}- Koja trojica?|- Ma niöta, niöta...
{87569}{87798}Nema veze, mogu dokazat' da nije.|Moramo ponovo pokrenut' naöu|radio stanicu "Drive By FM".
{87816}{87941}"Drive By FM" se vraÊa!|Tooooo!
{88026}{88151}Ovo je Drive By FM, zvuk geta|koji dolazi do vas iz srca Berköira.
{88402}{88527}äto je to bilo?|- Helikopter
{88470}{88595}- Aaaa, imitirao si krila.|Kul.
{88545}{88746}Lopine moje, deöava se teöko sranje!|Premijera je zajebo öupak
{88864}{88989}...koji je zlobniji i od Skeletora.|Da vratimo premijera, moramo...
{89009}{89134}se dokopati te trake, na kojoj|ja karam moju kuËku.
{89114}{89239}Ako mi pomognete da naem traku,|spasiÊemo drûavu!
{89235}{89360}I joö Êu vam dat' da vidite|sifone moje Julie.
{89297}{89332}- To!
{89354}{89479}- Zato vas sve pozivam da|prekinete sa meusobnim sukobima.
{89505}{89718}Bilo je dosta bratskog ubijanja, zato|spustite svoje kalaönjikove i uzije...
{89696}{89821}i ujedinimo se u jednu masivnu...|Masivnost!
{89861}{89986}
{90074}{90199}I mislio sam da ovo nikad|neÊu reÊi, ali...
{90197}{90378}Veliki pozdrav Eastend bandi.|- Ali, öta to radiö bre?
{90454}{90683}Ëuj, Hasane B., ako nam se pridruûite,|predaÊu vam Borrester "climbing" zid u parku.
{90720}{90947}Hajde da se pomirimo i uradimo|ono öto Tupacu i Biggy-ju nikada|nije poölo za rukom.
{91116}{91241}PoËujte, poËujte, ako se ûelite|pridruûiti ovoj vojnoj operaciji...
{91223}{91348}doite u kamuflaûnoj uniformi|sa opremom, sutra ispred |Centra u 9 ujutro.
{91344}{91469}- Da nije malo rano?|Moûemo'l u 12?
{91565}{91690}Oprosite öto kasnim, al na|TV-u je bilo neöto o majmunima...
{91729}{91854}bilo je stvarno smeöno, kad|rade ono s rukama, ovako...
{91888}{92013}Poötovanje svima koji nosite|kamuflaûne uniforme.
{91975}{92100}Ona Êe vam pomoÊi da |ostanete neopaûeni.
{92048}{92173}Sad ajmo u Checkers da|naemo tu kazetu.
{92138}{92263}UËinimo to za Britaniju.|UËinimo to za moju Julie.
{92225}{92350}I uËinimo to za hip-hop!|Selekta!
{92647}{92797}Nacrt'o sam detaljan|plan Checkers-a.
{92737}{92862}Kazeta je u premijerovom|sefu u njegovom uredu.
{92823}{92948}Prvo Riki, Dave i ja ulazimo unutra.|Jezzy, ti ostajeö ovdje.
{92965}{93090}BiÊemo kao specijalci.|A ja Êu bit' glavni.
{93059}{93184}- Ej, ja 'oÊu bit' B.A. Baraccas.
{93120}{93246}- Al' ja najbolje glumim B.A. Baraccas-a...
{93559}{93684}- Ti budi Murdock, |a ti Dave, budi Faca.
{93629}{93754}A öto mi da radimo?|- Vi svi ostanite ovdje...
{93712}{93899}svi Êemo se sakriti i stopiti s okolinom.|Kad se smraËi daÊu tajni signal.
{94118}{94243}Idemo!
{94146}{94271}U tom trenutku naötimajte|radio na najbolju "street garage" stanicu...
{94278}{94403}i odvrnite do daske.|To Êe privuÊ straûu...
{94444}{94569}i onda Êemo ih lukavo|zaskoËiti i savladati.
{95007}{95166}- Gospodine?.|- äto se, dovraga, deöava?
{95052}{95177}- Siguran sam da nije niöta,|ali poslao sam ljude da vide.
{95132}{95257}- Pobrinite se za to, ûelim |maksimalnu sigurnost.|Patrolrajte i u kuÊi.
{95324}{95449}Velika dvorana je ista kao|u kuÊi Lare Croft.
{95418}{95543}Znate, u Tomb Raider-u 2,|na Playstation-u
{95481}{95606}Dakle, Dave, ako otrËiö do stupa, |stiÊi Êemo u vodeno kraljevstvo
{95592}{95717}i na sljedeÊi nivo.
{95739}{95864}Ako iz nekog razloga to ne|uspije, moraÊemo naÊi naËin
{95826}{95951}da preemo pod koji je|osjetljiv na pritisak
{95904}{96029}Ako dignemo nogu,|mrtvi smo!
{96250}{96375}Niöta. Nastavljamo pretragu.
{96337}{96462}- Onda moramo proÊi lasersku sobu.|Dave, ti si specijalist za ovo.
{96925}{97050}Zapamtite, ako prekinemo ijednu|od ovih zraka, aktiviraÊe se alarm.
{97035}{97160}Zato budite jako paûljivi!|Idemo!
{97900}{98025}Ovo je sigurno premijerova soba.|Kazeta je tamo.
{98069}{98194}Uljezi u mojoj sobi!|Ovo je teroristiËki napad!
{98176}{98301}Pucajte Ëim ih ugledate!|Ponavljam, pucajte odmah!
{98383}{98508}Da, na sigurnom (safe) sam!|Da, dobro sam. Otvori sef!
{98559}{98684}Iza vas!
{98756}{98881}»ek malo, mislio sam|da si ti mutav!?
{98839}{98964}Nije baö, nego mi je jako|neprijatno zbog visine glasa
{98937}{99062}Ma dobro, nemoj sad davit'|s time. Prekini srat' s time.
{99061}{99186}Ako mogu na trenutak |prekinuti tvoju ûivotnu priËu...
{99178}{99304}veûimo ove öupke i otvorimo|taj sef veÊ jednom.
{99345}{99470}NeÊe! Sjetio sam se! Zaöto |ne bismo povezali sve...
{99474}{99599}akumulatore iz automobila i onda|kroz ljudski lanac prenijeli..
{99578}{99703}elektriËnu struju do sefa i |razvalili ga!?
{99601}{99726}- Zar nas neÊe "izudarati" struja?|- RazvaliÊe akumulatore, al...
{99691}{99816}neÊe nam bit niöta dok|god je lanac neprekinut.
{99801}{99850}Vjerujte mi, imao sam dvojku|iz fizike.|-Strava! PoslaÊu im SMS.
{100070}{100279}Ne, akmltore.|Akmulatore, akumulatore!
{100295}{100420}Spti. Spojti. Spojiti!
{100384}{100509}Pokuöao sam da|uötedim vrijeme!
{100480}{100551}Glupan glupi!
{100896}{101021}Upali motor, prenesi dalje...|- Hahaha, Ëuj mu glasa!
{101040}{101246}Upali motor, prenesi dalje...
{101261}{101386}Opali matoru, popuöi dolje. -äto?|Jel' da upalim motor? - Da!
{101919}{102044}- äta rade? - Ne mogu drûat', vuku me!|- Neeeee...
{102516}{102641}- Mir ËoveËe!|- Mir brate!
{102849}{102974}Nema kazete!|Pogledaj sam!
{102973}{103240}Samo neke fotke i...|mapa Stains-a.
{103371}{103496}Jah Ras Tafari, Haile Selassie.|Produûuju aerodrom preko Stains-a.|Potpuno Êe ga uniötit'.
{103549}{103674}PoËinju za 3 sata.|- Dva sata, 57 minuta!
{103755}{103880}Zaöto se terminal mora izgradit'|preko Stains-a?
{103818}{103943}- Jer sam kupio 600 hektara|zemlje tamo. Dajte mi to, molim vas.
{104027}{104152}Ne pokuöavajte pobjeÊi odavde.|Ovo je ojaËani nuklearni bunker.
{104148}{104324}Potpuno je neprobojan uzvana, a |zaboravio ugraditi spremnik zraka.
{104340}{104506}- Zaöto ga sad ne ugradiö?|- Stvarno si uûasno glup!
{104714}{104839}- Ej, matori|- äto je?
{104838}{104963}- Daj planove!
{105060}{105184}- Ili öto...? - Il' Êu|ti sise isËupat! Indijanska vatra!
{105628}{105753}Udario si me u nos, luaËe!
{105885}{106010}Ne zajebavam se, ozbiljno, iza tebe|je 1000 policajaca...
{106138}{106263}Vidi, vidi, eno je Jennifer Lopez.|äta kaûeö??? Oö' se karat odma' sad...
{106298}{106423}...jer si tako napaljena i ako|ga ne dobijeö odma'...
{106423}{106606}Vidi, eno 20 funti na podu.|Eno je vjeverica, sa glavom pileta i sa krilima...
{106732}{106857}Oö' me opet zveknut'?
{106944}{107069}A sad Êu te ubiti!
{107715}{107840}Ovo ti je od gradjana Stains-a!
{107963}{108088}Uf, Ëini mi se da je|malo izletilo!
{108070}{108195}Julie jesi l' tamo?|Znam öta misliö o meni.
{108157}{108395}Znam da sam isp'o govno, al' moram spasit'|Stains, a ne mogu sam, a i ukakio sam se.
{108423}{108485}Sranje, Riki i Dave!
{108748}{108873}Riki!
{108847}{108972}- Mislili smo da Êemo umrijeti|pa rekoh 'ajde da probamo!
{108943}{109068}- I, kako je?|- Pa uopöte nije loöe!
{109014}{109139}- Dave?|- Sasvim fino, stvarno!
{109098}{109223}- PriËaÊemo kasnije, sad moramo|spasit' Stains.
{109169}{109294}- Dvije minute, naemo|se u autu?
{109233}{109358}- Moûe, budi brz, dolazi murija|i nemoj svröit' unutra!
{110077}{110202}Ne bih to radio da sam |na tvom mjestu!
{110152}{110315}Aliiiii, volim teeeee!
{110274}{110399}- Julieeeeee,...zdravo.
{110406}{110531}Ignorirajte ih i poËnite ruöenje. - »ek' |ne sluöajte ga, on je kriminalac!
{110521}{110698}I to ne od dobrih koji|diluju drogu i kradu aute. Ovdje|je dokaz da je htio sruöit' Stains!
{110711}{110836}Pa öta, ionako je obiËna rupËaga!
{110784}{110909}- Uhapsite ih!|- Jebiga, odoh u zatvor!
{110879}{111004}SljedeÊih 20 godina Êe |me guzit' pod tuöom svaki dan.
{111026}{111151}Stanite, oslobodite ih!
{111094}{111219}- Pod Ëijom naredbom?|Ako ste zaboravili, ja sam...
{111171}{111296}aktualni predsjednik,|a vi ste osramoÊeni!
{111254}{111379}Samo zahvaljujuÊi vama, öto|se dobro vidi na ovoj kazeti.
{111345}{111470}- Kate!|- Ne Davide!
{111423}{111548}Kad sam uöla u politiku,|to je bilo za bolji svijet...
{111548}{111673}svijet poötenja i istine.
{111668}{111793}Negdje usput je ta vizija nestala.|Moj san je nestao i umjesto toga...
{111803}{111928}otkrila sam pohlepu,|lopovluk i korupciju...
{111869}{111994}- DOSADNO!
{111940}{112066}- Uhapsite ga!
{112008}{112133}- Uûivaj s ovom budalom,|taman ste jedno za drugo!
{112104}{112229}- Odjebi!
{112189}{112314}Ali, moûeö biti siguran da neÊemo |izgraditi terminal preko Stains-a...
{112271}{112396}umjesto toga, demolirat Êemo|Slough, drugi kvart. - Super.
{112344}{112469}Sad Êe mi trebati novi|zamjenik premijera.
{112416}{112541}äto misliö da budeö|moja desna ruka?
{112491}{112616}- Desna ruka, hahaha|pederËiÊu, pederËiÊu!
{112599}{112652}äto kaûeö Ali?
{112684}{112809}Pokaz'o sam ti put.|Dalje moraö sam.
{112837}{112962}Ja Êu ostat' sa svojom rajom |i mojom kuË... mojom damom.
{113278}{113403}K R A J
{113313}{113438}U stvari, mogli bi neöto|uËinit' za mene...
{113404}{113529}Britanska ambasada|- JAMAJKA -
{113531}{113656}Poötovani ambasadore...
{113681}{113806}Vaö usjev je spreman|za inspekciju
{114025}{114150}Dobro jutro, ambasadore!
{114079}{114204}Ambasadore, ûelite|li probati berbu?
{114552}{114677}Ovo je dobar öit.
{114631}{114756}- »ovjek iz Stainsa |kaûe DA!
{114999}{115124}Leda, molim!
{115101}{115226}- Ali, ovo je sjajan jakuzi!|- To nije jakuzi!
{115294}{115336}Oprostite!
{116105}{116230}Pleöi za mene, kujo!
{116354}{116411}"Ovako mi to radimo"
{116470}{116596}"Ovako mi to radimo"
{116548}{116673}Julie, moram te neöto pitat'...
{116716}{116841}OÊeö li me uËinit' |najsretnijim na svijetu?
{116919}{117044}- OÊu!
{116968}{117093}- Pusti me da je kresnem!
{117198}{117323}Stvarno kraj!
{117473}{117598}I kako vam se svidio film?|Nije bio loö, jel da?
{117578}{117703}Puno bolji od Harry Potter-a.|Koji je po meni jako djetinjast.
{117700}{117825}Ako gledaö ovo Potter-u,|ja sam bolji od tebe!
{117792}{117917}Ti vjerojatno joö nisi ni|spavao sa ûenskom.
{117861}{117986}Ja sam spav'o sa tri!|I naterao jednu da masturbira.
{117988}{118113}äto god mislili o filmu, recite| svojim prijateljima da je otkaËen
{118133}{118258}jer ako ovo propadne, neÊu |moÊ' ugradit baki novi kuk.
{118237}{118362}Tako da je izbor na vama...|bez pritiska!
{118317}{118442}Odi bako, reci im sama.|äta, opet si pala?
{118457}{118582}Slomila si i drugi kuk?|Ne plaËi, ajde...
{118599}{118724}nekako Êemo |te veÊ pokrpat' gomilo kostiju!
{118812}{118937}Ne budite sebiËni,|kupujte robu i ostalo!
{118962}{120462}-== [ www.OpenSubtitles.org ] ==-
