{1}{20}Made by CVStudio v.1.0.3.1|[][PT][25][129584][AtomAnt]
{45}{195}-== [ www.OpenSubtitles.org ] ==-
{270}{299}Zovem se Alis.
{327}{384}Radila sam za Ambrela korporaciju.
{393}{469}NajveÊi komercijalni entitet na svetu.
{498}{531}Bila sam öev obezbeenja
{539}{623}U haj-tek ustanovi|zvanoj koönica.
{658}{793}Dole su bile laboratorije|u kojima se istraûivalo eksperimentalno bio naoruûanje.
{820}{918}Desio se incident, virus je osloboen,|i svi su poginuli.
{981}{1057}Nevolja je bila u tome|öto nisu ostali mrtvi.
{1117}{1183}Virus je reanimirao|njihova tela.
{1281}{1368}Preûivela sam, ja i joö|jedan nauËnik zvani Met.
{1401}{1463}Kad smo izaöli doËekali|su nas neki nauËnici.
{1480}{1537}Met i ja smo bili razdvojeni.|-Mutira.
{1552}{1587}HoÊu ga u programu|Nemesis.
{1592}{1623}Met!
{1698}{1793}Vodite je u Rakun siti,|i sastavite tim.
{1811}{1900}Otvaramo koönicu, hoÊu|da znam öta se dole deöavalo.
{1941}{1984}Mislili smo da smo|preûiveli uûas.
{2093}{2127}Nismo bili u pravu.
{2189}{2304}NASTANJENO ZLO|APOKALIPSA
{2472}{2588}Sada je 6:10 ujutru a napolju je veÊ|92 stepena farenhajta.
{2600}{2668}Nastavlja da se|razvedrava.
{2672}{2757}»ista neba u Rakun sitiju|i povetarac koji ide sa zapada...
{2793}{3033}Imamo i bonus za astmatiËare|pritisak je danas odgovarajuÊi.
{3048}{3122}Sve u svemu, izgleda|kao da Êe biti joö jedan divan dan.
{3131}{3231}Ostanite sa nama, posle|Êemo gledati mesta za odmore.
{3941}{3987}Time, nastavi.
{4408}{4451}O jebote...
{5467}{5529}Izvinite gospoo,|desio se incident.
{6042}{6084}Izvinite gospodine,|desio se incident.
{6144}{6194}Koliko je loöe?|-Morate poÊi sa nama.
{6208}{6295}Moram da odem po Ëerku.|-Sreeno je gopsodine. -äta radiö to?
{6307}{6354}Ne razumete, otiöla|je u ökolu!
{7436}{7542}Imamo potvrdu, evakuacija zavröena, ali|smo izgubili kontakt sa gamom12.
{8378}{8444}Traûimo podröku!
{8474}{8607}Joö uvek nema objaönjenja za|ubistva koja se deöaaju po gradu...
{8750}{8825}Treba nam podröka, odmah!
{9499}{9550}Ne pucajte, naöa je!|-Valentajn!
{9555}{9622}Zaraûeni su.|-Ako je zaraûena, skidaj je sa mene!
{9651}{9690}Rekla sam ti|pucaj im u glavu.
{9703}{9752}Molim vas, nek je neko ubije!
{9816}{9866}Ne, ne mene!
{9882}{9931}Idemo iz grada, savetujem|ti da ti isto uradiö.
{10015}{10074}Zatvorite sva vrata i prozore...
{10401}{10485}Projekat Alis, aktivacija poËela.|Automatsko gaöenje anestetika.
{12411}{12453}Smirite se zbog|bezbednosti...
{12532}{12650}Grad je skroz blokiraö,|naöe trupe su sve zatvorile, jedini izlaz je preko mosta.
{12659}{12734}Svi moraju proÊi|skeniranje.
{12740}{12764}Gospodine!
{12777}{12806}Doite da vidite ovo!
{13227}{13270}Ne gurajte se, drûite liniju!
{13312}{13359}Treba nam pojaËanje dole!
{13397}{13526}Dolaze pojaËanja preko mosta.
{13541}{13581}Prijem bazo|idemo.
{14961}{15017}Hajde, u nevolji je,|spuötaj nas!
{15030}{15098}Ne moûemo, imamo|nareenje!
{15143}{15229}UbiÊe je, spuötaj se!|-Imamo nareenja!
{15335}{15386}Jebeö nareenja!
{15416}{15452}Nikolas, odveûi me!
{15512}{15549}»ekaj!
{15913}{15949}Sad!
{16103}{16194}Spusti nas niûe,|odmah!
{16350}{16391}Hej, jesi li dobro?
{16432}{16479}Odalji se od ivice,|i prii mi.
{16509}{16560}Sve je u redu.|-Nije.
{16618}{16689}Videla sam öta se|deöava kad te ugrizu.
{16698}{16756}Moûemo ti pomoÊi.|-Nema vraÊanja nazad.
{16785}{16825}Ne!
{17307}{17351}Hej!|-Valentajn!
{17364}{17417}Hej, Valentajn!
{17483}{17537}Hej, drago mi je öto|si doöla, treba nam pomoÊ.
{17673}{17726}Ima slabo srce!|-Beûi od njega!
{17739}{17773}Svi se odaljite!
{17795}{17836}Tata!|-Beûi od njega!
{17862}{17892}Beûi od njega!
{17995}{18016}Tata!
{18024}{18056}U redu je, imam te.
{18371}{18421}Ovde je, stiglo|je do kapije.
{18514}{18603}Zaöto si ovde?|Trebao si da izaeö dok si imao priliku.
{18618}{18657}Ovo su sve ljudi.
{18722}{18790}Zatvaraj.|-Gospodine? -Zatvaraj kapije!
{18811}{18843}Ne razumem...|-Samo to uradi.
{19500}{19580}Ovo je barijera|karantina.
{19592}{19693}Vi ste moguÊi zaraûeni|i ne moûete izaÊi iz karantina!
{19732}{19809}äta se deöava?|-Sve mere su preduzete.
{19827}{19937}Situacija je pod kontrolom,|molimo vas da se vraÊite kuÊama.
{20279}{20369}Imate pet sekundi da se|okrenete i vratite u vaö grad.
{20459}{20494}Uradi to!
{20505}{20576}Autorizovano je|koriöÊenje bojeve municije.
{20637}{20710}5... 4...
{20752}{20812}3...2....|-Nazad!
{20832}{20888}1...|-Nazad!
{21813}{21891}Idemo u sektor 0-1|izvröavamo zadatak.
{22460}{22480}Granata!
{22659}{22713}Ekipe 3-7|se povlaËe.
{22759}{22813}Ne gospodine,|mere suzbijanja nisu uspele.
{22827}{22926}Ne moûemo je zadrûati,|infekcija se öiri brûe nego öto smo mislili.
{22958}{23048}Doktore Eöroud,|zar ne biste trebali da ste u helikopteru?
{23057}{23086}Ne idem.
{23103}{23181}ReËeno mi je da izbavim|nauËnike iz vruÊe zone.
{23197}{23250}Previöe ste vaûni za Ambrelu|da bi rizikovali.
{23256}{23315}Ne idem bez Êerke.
{23366}{23426}éao mi je, stvarno,|ali grad je zatvoren.
{23448}{23518}Moûda je preûivela|udes, ali je nismo mogli naÊi.
{23543}{23669}I da je ûiva nisam je mogao|naÊi, rizik infekcije je preveliki.
{23688}{23718}Morate razumeti.
{23738}{23833}Ti znaö öta moraö da uradiö.|Ja ostajem.
{24681}{24721}PRISTUP ODBA»EN
{24899}{24936}PRSITUP ODBA»EN
{25061}{25173}PRISTUP ODOBREN
{25348}{25424}PRONALAZAK OSOBLJA.|META: AN–ELA
{25458}{25542}TRAéIM AN–ELU AäFORD
{25571}{25612}NA–ENA:GIMNAZIJA|KAMERA
{25867}{25909}Mora da je neko ostao|ûiv.
{26067}{26099}NA–ENA|KAMERA
{27446}{27499}Odvedite je u ustanovu|Rakun Sitija.
{27522}{27597}HoÊu je u karantinu|drûite je na oku.
{27718}{27774}Spremite je za|izlaganje.
{27925}{27978}Zaustavite dozu.
{27988}{28033}Samo to uradite!
{28422}{28454}NA–ENA|CRKVA REJVENS GEJT
{28571}{28590}Unutra.
{28621}{28656}Da te pokrijemo.
{29379}{29478}Izaite, ovo je moje|mesto, ja se krijem ovde!
{29482}{29543}Mislim da je dovoljno veliko|za sve nas.
{29547}{29572}Ok, smiri se!
{29589}{29625}Spusti taj piötolj.
{29721}{29769}Spusti piötolj.
{29824}{29876}A ti se smiri.
{29936}{30058}Dakle, da li policija RS ima|komentar öta su one stvari?
{30123}{30154}äta ti je to?
{30175}{30272}Moj Emi,|ako preûivimo.
{31710}{31747}Jeste li dobro?
{32009}{32033}äta to radiö?
{32078}{32115}äta mu je?
{32133}{32221}To je moja sestra, nije joj dobro.|-Moûda mogu pomoÊi?
{32229}{32256}Ne...|-Skloni mi se sa puta!
{32324}{32351}Samo izaite!
{32521}{32580}Hraniö je?|Ti si bolestan!
{32640}{32675}Samo nas ostavite|na miru.
{32724}{32754}Ne!
{32905}{32930}Beûim odavde!
{32940}{32977}Hej! Hej!
{32993}{33030}Hej, nemoj!
{33032}{33064}O moj boûe!
{33227}{33252}Pomozite!
{33957}{33979}Tamo!
{34122}{34146}Isuse!
{34176}{34200}äta je ono jebote?!
{34212}{34255}äta to radiö?|VraÊaj se!
{37769}{37813}Budalo!
{37924}{37951}Znam.
{37974}{37999}Ima ih 3.
{38029}{38064}Imaju nas u Êoöku.
{38093}{38124}äta Êemo da uradimo?
{38137}{38161}Idemo!
{38693}{38723}Isuse!
{38740}{38799}TrebaÊe nam joö|municije, ja nemam.
{39121}{39158}Sranje, o ne...
{39679}{39704}Pokret!
{41387}{41418}Ko si ti?
{41594}{41637}Jipi kaj jej pederu!
{41720}{41750}10 poena!
{42706}{42724}Skini ga!
{42813}{42851}Jurij, jesi li dobro?
{42920}{42938}Pazi ovo!
{43322}{43345}Jesi li dobro?
{43349}{43376}Jesam.
{43861}{43904}Nazad, nazad!
{44241}{44272}Idemo!
{44356}{44444}Ovde je Farel,|opkoljeni smo, traûimo evakuaciju helikopterom.
{45222}{45270}Moramo da naemo neko|mesto da stanemo za tren.
{45284}{45325}Mislim da to nije dobra ideja.
{45344}{45407}Moûda bude joö|onih stvorova.
{45420}{45455}Da ih ima joö|veÊ bi smo ih videli.
{45485}{45539}Znaö öta su?|-Biooruûja.
{45548}{45591}Napravljeni su|u laboratorijama ispod grada.
{45600}{45646}Kako znaö toliko|o ambreli?
{45673}{45699}Radila sam za njih.
{45737}{45796}Doavola!|-Stoj!
{45846}{45877}äta to radiö?
{45892}{45940}Ranjen je, infekcija|se öiri.
{45959}{45991}Dobro sam.
{46019}{46058}Sada bi trebalo da|se pobrinemo za njega.
{46086}{46134}BiÊe mu mnogo|teûe kasnije.
{46155}{46193}Znaö to.
{46220}{46245}Ne.
{46265}{46353}Ako doe do toga,|sama Êu se za to pobrinuti.
{46505}{46534}Kako hoÊeö.
{46584}{46662}Niöta liËno, ali za sat dva|Êeö biti mrtav.
{46704}{46763}A posle nekoliko minuta|Êeö postati jedan od njih.
{46779}{46874}UgroziÊeö prijatelje,|pokuöati da ih ubijeö, verovatno Êeö uspeti.
{46959}{47019}éao mi je. Tako je kako je.
{48546}{48574}Previöe ih je!
{48612}{48646}Beûimo odavde, ovuda!
{49004}{49077}Gospodine, T virus je|dostigao kritiËne nivoe.
{49173}{49229}Ovo predstavlja pravu|priliku.
{49257}{49373}Snimaj sve postupke, aktiviraj|program Nemesis, sad!
{50284}{50322}Hej, ovamo!
{50333}{50361}Dole smo, hej!
{50431}{50497}Gde Êe?|-SleÊu tamo kod Jurija, idemo!
{50540}{50581}Ajde Juri, idemo.
{50598}{50633}SrediÊemo te, idemo!
{51072}{51128}»ekaj, joö malo|smo stigli.
{51189}{51220}Ne, ne!
{51221}{51243}Ne, ne idi!
{51261}{51341}Ovde smo, vratite se!|-Bacili su neöto u bolnicu, ajde da vidimo.
{51349}{51410}Moûda ima radio koji radi,|uzmi Jurija.
{51702}{51745}Pazi se Jurij.
{52778}{52819}Ok, ovde se odmaraj.
{52934}{52980}äta je ovo?
{53013}{53079}Izgledaju kao|kutije za oruûja.
{53090}{53154}Ne trebaju nam oruûja,|treba nam evakuacija!
{53194}{53238}Ovo nije za nas.
{53805}{53852}Ima dosta za sve!
{54353}{54395}Ne pucaj!
{54497}{54544}Sredio sam je!|-Hvala!
{54559}{54601}Dugujem ti ËoveËe!
{54705}{54732}Sranje!
{54812}{54859}Sad sam bio napolju,|zar mi ne prepoznajete lice?
{54934}{55016}Mamojebac molim te,|moja sranje je domaÊe.
{55314}{55366}äta je ono jebote?
{55685}{55711}Sranje...
{55945}{55989}Padaö kurvin sine!
{56337}{56391}Idemo na poloûaje,|skinite ga!
{56500}{56582}Ovo je ludo, kako Êete|na njega, a ima zolju?
{56624}{56699}äta imamo?|-Tucu naoruûanih ljudi, organizovani su.
{56901}{57036}Iznenadna poseta.|-To su STARS, specijalna jedinica.
{57070}{57109}Najbolji su.
{57123}{57160}Pali!
{57462}{57494}Nazad!
{57543}{57593}Da vidimo koliko|su dobri.
{57608}{57680}Aktiviram protokole.|-UBIJ »LANOVE STARS
{58135}{58167}STARS
{58340}{58367}Sranje...
{58555}{58587}Respekt!
{58687}{58735}Naoruûani civil
{58761}{58824}Ne-borben.
{59153}{59265}Dobri su ti potezi,|dobra sam, ali ne toliko.
{59294}{59342}Budi zahvalna zbog toga.|-Kako to misliö?
{59439}{59481}Neöto su mi uradili.
{59498}{59537}Jedva se oseÊam|ljudsko.
{59624}{59695}Trebalo bi da krenemo
{59958}{59995}Nastavite!
{60330}{60382}Halo?|-Pomislio sam da se neÊeö javiti.
{60416}{60480}Ko je to?|-Mogu da vas izbavim iz grada.
{60514}{60546}Svo Ëetvoro.
{60569}{60626}Prvo moramo da se|dogovorimo.
{60636}{60669}Jeste li spremni da se|dogovorimo?
{60702}{60777}Imamo li izbora?|-Ne ako sutra ûelite da ûivite.
{60841}{60969}Zove se Eöford i radi?|-U naprednim istraûivanjima u Ambreli.
{60987}{61048}äta hoÊe od nas?|-Njegovu Êerku, Anelu.
{61056}{61155}Zarobljena je u gradu,|trebali su da je evakuiöu ali nisu uspeli.
{61164}{61199}Krije se u ökoli.
{61205}{61263}Moramo da je naemo, da bi|nam dao da izaemo.
{61285}{61434}Nema dogovora. NaÊiÊemo najËvröÊu|zgradu, i zabarakadiraÊemo se.
{61449}{61485}Samo Êemo Ëekati, |i stiÊiÊe nam pomoÊ.
{61490}{61525}NeÊe biti pomoÊi.
{61542}{61607}Prema Eöfordu, ambrela ne|zna kako da zadrûi infekciju.
{61614}{61713}Do jutra Êe grad biti saniran.
{61786}{61832}Kako to misliö ''saniran''?
{61850}{61898}Precizna taktiËka|nuklearka.
{61903}{61949}Koje snage?|-Pet kilotona.
{62007}{62050}Jebeö me...|-äta to znaËi?
{62073}{62202}ZnaËi da Êe uniötiti infekciju,|a i nas ostale.
{62254}{62307}Sranje, to je sranje!
{62329}{62370}Nema öanse da se izvuku sa time!
{62388}{62422}BiÊe na vestima!
{62439}{62502}LAgaÊe, to je veÊ|spremljeno.
{62512}{62610}OkriviÊe nuklearnu elektranu.|-TragiËni nesreÊni sluËaj.
{62631}{62702}Niko nije sposoban za ovo.|-Nesposoban? Bio si tamo.
{62765}{62853}Na mostu, video si dokle|Ambrela ide.
{62976}{63022}äta sad da radimo?
{63056}{63101}Mislim da je bolje da je|naemo do zore.
{63282}{63406}äta ako nema izlaza, i gleda|nas na kamerama, kao da je ovo bolesna igra?
{63479}{63520}äta je to?|-äta se deöava?
{63530}{63595}»ekaj.|-Zora neÊe da Ëeka!
{63654}{63694}Dole je neöto.
{63705}{63748}Gde?
{63766}{63795}Tamo.
{63810}{63881}Ne vidim niöta.|-To ne menja Ëinjenicu da je neöto tamo.
{63901}{63975}Neöto je dole.|-Muka mi je od ovog sranja.
{64243}{64306}Locirao je joö|dva Ëlana STARS-a.
{64395}{64461}Nemesis.. beûi!
{64476}{64514}Samo beûi!
{64614}{64632}PRETNJA
{64731}{64761}Meta identifikovana.
{64791}{64867}Gospodo, na ovo Ëekamo.
{64909}{65064}Potvrdi öifre, Nemesis|program je sada u potpunosti aktiviran.
{67563}{67610}PRESTATI
{69062}{69127}Gledaj, ûao mi je zbog|tvog prijatelja.
{69206}{69272}Idemo do ökole, i naimo|tu klinku.
{70190}{70263}NeÊe da prestane|da krvari rana.
{70300}{70395}Zaöto nas nisu videli. -äTa?|-Helikopter.
{70421}{70505}Bili smo na ulici pred|bolnicom, kako nas nisu videli?
{70521}{70579}Videli su nas.|-Kako to misliö?
{70639}{70718}Mi smo sredstva Nikolaj, potroöiova|sredstva.
{70799}{70844}Upravo smo potroöeni.
{71203}{71240}Stani!
{71265}{71393}Znam öta mislite,|gledajte, nisam ugriûen!
{71469}{71496}Upadaj.
{71542}{71679}Lori Dûeferson Vejn, zovite me|LJ zbog ove situacije.
{71843}{71892}Anela eöford naena.
{72854}{72894}MoraÊemo da se razdvojimo|da pretraûimo ovo mesto.
{72915}{72993}Zaboravi, neÊu da|idem tamo sama.
{73029}{73111}IÊiÊu sa tobom.|-Ti, idi na prvi sprat.
{73131}{73175}Ti, idi na drugi.
{73196}{73233}Ja Êu u podrum.
{73245}{73306}Nisam pucala iz piötolja ranije.|-Prosto ko pasulj.
{73333}{73376}Pokuöaj da gaaö|u glavu.
{74882}{74927}Vidim te pede...
{75071}{75118}Jeste li i vi dobili poziv?
{75143}{75183}äta?|-Jeste li doöli po devojËicu?
{75197}{75226}Da, klinku.
{75260}{75317}Nije nam rekao da je poslao|nekog drugog.
{75345}{75380}Izgleda da smo|partneri.
{76350}{76385}Hej, jesi li dobro?
{76541}{76572}Vodimo te kuÊi...
{77798}{77898}Ne moûeö joj pomoÊi,|ne sad.
{78032}{78058}Jesi li ti Anela?
{78066}{78091}Jesam.
{78100}{78153}Poûurimo, pre|nego öto se vrate.
{78211}{78242}Drûi ovo.
{78391}{78423}Anela Aöford, a?
{78446}{78490}To je odraslo ime|za malu devojËicu.
{78511}{78558}Nisam samo mala devojËica.
{78569}{78657}Uostalom, svi prijatelji|me zovu Eni.
{78667}{78694}Eni, jeli?
{78730}{78757}Svia mi se to.
{78880}{78951}äta ako su ovde?|-Ne brini se, spori su.
{78963}{79067}Moûemo ih zaobiÊi.|-Ne, ne njih.
{79112}{79165}Njih.
{79245}{79272}Nazad!
{79932}{79959}Miran.
{80008}{80037}Pomislio sam da vam|treba pomoÊ.
{80048}{80081}Ti radiö za Ambrelu?
{80086}{80161}Radio, dok nas nisu ovde|ostavili.
{80174}{80262}Sad sebe smatram|slobodnjakom.
{80304}{80355}Narednik Nikolaj|JunoviÊ.
{80364}{80408}Na vaöoj usluzi.
{80445}{80488}Beûi!|-»ekaj, Eni!
{80493}{80551}Ostani sa devojËicom,|imam ovu kuËku.
{81019}{81058}Ostani pored mene.
{81133}{81166}ZakljuËano je.
{81206}{81230}äta sad da radimo?
{81567}{81656}»ekaj ovde, oËi tamo, ok?
{83849}{83889}Hvala vam.
{83898}{83934}Znate se?
{84015}{84064}Inficirana je.
{84091}{84136}Inficirana je neËime jaËim.
{84154}{84217}Kako to znaö?|-Zato öto je i ona.
{84238}{84302}Ti si inficirana, kad|si to nameravala da nam kaûeö?
{84487}{84517}Daj da vidim.|-Ne.
{84640}{84689}Znaö da te neÊu|povrediti.
{84721}{84759}Daj da vidim.
{85288}{85357}To je antivirus, lek|za T virus.
{85369}{85405}Postoji lek?
{85419}{85481}Odakle ti ovo?|-Od tate.
{85502}{85534}Napravio je za mene.
{85554}{85676}Bolestan je, i jednog dana Êu|se i ja razboleti, samo hoÊe da spreËi to.
{85710}{85800}Kad sam bila mala|hodala sam sa ötakama.
{85814}{85876}Rekli su da se nikada|neÊu oporaviti, samo Êe se pogoröavati.
{85976}{86018}Naöao je naËin da me ojaËa.
{86030}{86068}T virus?
{86119}{86173}Onda su to oduzeli|njemu.
{86421}{86505}Nije loö Ëovek,|nije hteo da se ovo desi.
{86817}{86869}Ne pucaj, kul je.
{86883}{86931}Nagodio se sa njime|isto kao i vi.
{87039}{87065}Koliko vas ima?
{87090}{87118}Kako to misliö?
{87231}{87279}Nikolaj...
{87382}{87417}Kad si ugriûen?.
{87430}{87463}Pre tri sata.
{87578}{87617}Danas ti je sreÊan dan.
{87702}{87785}Nisi mi rekao da si ugriûen, a|ja visim sa tobom i ta sranja...
{87900}{87955}Jeli imate moju Êerku?|-Reci nam kako da izaemo.
{88022}{88076}Spremljen je helikopter.
{88088}{88252}Polazi za 47 minuta, to je poslednji|prevoz iz grada pre detonacije.
{88260}{88331}Kako da znamo da je ovaj|helikopter za nas?
{88354}{88448}Ne zna svoju svrhu, ali slabo je|Ëuvan. -Gde Êe sleteti?
{88463}{88506}Mogu li da priËam sa Êerkom?
{88611}{88632}Tata?
{88649}{88720}Zdravo duöo, jesi|li u redu?
{88735}{88785}Kad Êemo se videti?|-Uskoro.
{88796}{88861}Oni Êe de doneti meni,|vidimo se uskoro.
{88885}{88916}Daj mi onu damu.
{88946}{88973}Gde idemo?
{88988}{89030}Helikopter Êe biti|kod gradske skupötine.
{89041}{89078}Savetujem da ûurite.
{89293}{89375}Kompjuteri...|tako nepouzdani...
{89594}{89625}Isto kao ljudi.
{89793}{89845}Stvarno si mislio|da ne znamo?
{90143}{90180}äta mi to ubrizgavaö?
{90199}{90227}Antivirus.
{90305}{90437}T virus animira mrtve Êelije,|diûe mrtve iz mrtvih.
{90447}{90540}Na svakoj osobi izazivaju|mutaciju.
{90558}{90693}Moûeö se oporaviti, ako ovime|kontroliöeö virus. -Eni je inficirana?
{90705}{90782}Da. Ima dovoljno Êelijskog rasta da je|regereniöe, ali neÊe mutirati.
{90867}{90915}I tebe su inficirali T virusom?
{90935}{90965}Da.
{90985}{91043}Ne brini se, nisam|zarazna.
{91126}{91161}Izvoli.
{91180}{91246}Uzmi tu igraËku, vidi|da je öto bolje iskoristimo.
{91333}{91426}Zovem se Alis, radila sam|za Ambrela korporaciju.
{91457}{91550}NajveÊi i najmoÊniji komercijalni|entitet na svetu.
{91579}{91699}Bila sam öef obezbeenja u tajnoj|ustanovi zvanoj koönica.
{91718}{91840}Ginovska podzemna stanica|koja je istraûivala biogenetiËko oruûje.
{92583}{92605}Idemo.
{93332}{93347}NACILJANO
{95722}{95772}Promaöila si jednog.
{96546}{96587}Moramo da poûurimo.
{96607}{96660}»ekaj, imamo vremena.|-Ne, moramo da poûurimo.
{96743}{96784}Jebote, krade|nam prevoz.
{96793}{96843}UzleÊi.
{96857}{96903}Rekla sam da uzletiö!|-äto se ûurite?
{96987}{97024}OËekivali smo vas.
{97147}{97189}Okolina bezbedna.|-ZakljuËajte sve sektore.
{97419}{97454}Eni!|-Tatice!
{97517}{97582}Znala sam da me neÊeö ostaviti.|-Nikad!
{97634}{97690}Odbaci primarno naoruûanje.
{98005}{98101}Vas dvoje ste bili|veoma obeÊavajuÊi, ali Ëekamo akciju.
{98144}{98249}Bili ste veoma impresivni,|vi ste kao brat i sestra.
{98261}{98322}Imate brzinu, snagu, agilnost...
{98332}{98523}Isi ubistveni instinkti, na istom ste|bili istraûivanju, a sad Êemo videti ko je jaËi.
{98599}{98632}Bori se sa njime.
{98673}{98707}NeÊu.
{98720}{98764}Bori se sa njime ili|Êu ih pobiti.
{98825}{98886}Zaöto misliö|da me je briga?
{99001}{99041}Tata!
{99097}{99117}Ne!
{99153}{99208}Bio je vredno sredstvo korporaciji.
{99220}{99300}Nije me briga za ove ljude.
{99593}{99615}PoËni.
{103568}{103628}Mutira, hoÊu ga|u programu nemesis.
{103702}{103736}Met!
{103857}{103966}KreÊemo sa|ubrizgavanjem, T Virus poËeo mutaciju.
{104084}{104137}vidimo sliËne|Êelijske flukcuacije.
{104290}{104346}Met, tako mi|je ûao.
{104452}{104477}Dovröi ga.
{104521}{104549}Rekao sam: dovröi ga.
{104595}{104639}Ne...
{104679}{104712}Ne...
{104740}{104797}Zar ne razumeö|koliko si mi vaûna?
{104822}{104964}To stvorenje je jedno,|ali ti si se vezala sa virusom na Êelijskom nivou.
{104986}{105078}Ti si ga prihvatila, promenila,|postala si veliËanstvena.
{105101}{105128}Postala sam nakaza.
{105134}{105221}Ne, ti nisi mutacija, ti si|evoluirala.
{105256}{105335}Zamisli öta moûeö da postigneö|uz moju pomoÊ.
{105398}{105430}A on?
{105507}{105575}Evolucija ima|svoje Êorsokake.
{105636}{105671}Oslobodiga jadova.
{105692}{105732}I poi samnom.
{105788}{105818}NeÊu.
{105880}{105930}Ti si veliko razoËarenje.
{105960}{106035}Sva ta snaga, bez volje|koja je vodi.
{106100}{106146}Kakva öteta...
{106391}{106433}Spremite se za uzletanje.
{106501}{106575}Operacija Rakun Siti poËinje|na moj znak.
{106818}{106858}Ubij je.
{107070}{107090}äta to radiö?!
{107513}{107544}Vodi nas odavde!
{107754}{107849}Operacija Overlord, poËni|sekvencu lansiranja!
{107864}{107915}Detonacija za 5 minuta!
{108138}{108164}Spusti se!
{108355}{108395}UzleÊemo!
{108423}{108461}Ja inaËe vozim|kadilak.
{108987}{109025}Predajte se ili otvaramo vatru.
{109761}{109786}Baci ih.
{110203}{110240}Baci oruûje i predaj se!
{111221}{111258}Neka ovo poleti!
{111385}{111424}Moraö da ustaneö!
{111539}{111564}Met...
{111609}{111632}Met...
{111682}{111710}Hajde, moramo da idemo.
{111723}{111749}Moramo da idemo, hajde.
{111854}{111884}Hajde.
{112139}{112169}Hvataj ih!
{112210}{112285}Ako mislite da Êu moliti,|neÊu.
{112346}{112399}»ekaj!
{112616}{112752}Moja smrt neÊe ovo zavröiti.|-Ne, ali Êe poËeti.
{114548}{114585}HoÊeö li biti dobro?
{115467}{115500}Drûite se za neöto!
{115815}{115862}Jebote!
{115935}{115966}Padamo!
{116934}{117033}Devetka bazi, potvrdili smo|mesto pada.
{117370}{117407}Dovedite medicinski |tim.
{117462}{117485}äta je sa ostalima?
{117513}{117559}Nema viöe tela gospodine.
{117893}{117970}Imamo nepotrvrene izveötaje o|katastrofi u Rakun sitiju.
{117976}{118102}Ove vesti su sad stigle, neki teûak|virus je vladao...
{118115}{118197}Ambrela je umeöana|u smrt nevinih civila...
{118205}{118307}Ove snimke je snimila bivöa|novinarka Semi Morales.
{118312}{118411}Novi dokazi potvruju da|je ono samo bolesna öala.
{118423}{118574}Laûna traka je diskreditovana.|-To je obiËna sprdnja na tragediju koja se desila.
{118616}{118755}Reaktor u nuklearnoj stanici|je dostigao kritiËno stanje i napravio atomsku nesreÊu.
{118765}{118825}PodseÊa na »ernobil|iz 1986te.
{118833}{118946}Guverner je zahvalio|Ambreli za brzu reakciju.
{118956}{119087}PoËicnioci ovih|zloËina su traûeni od strane policije.
{119746}{119770}Aleks!
{119781}{119811}Probudi se!
{119907}{120043}Moûeö li me Ëuti?|-HoÊeö da prestanem sa time?
{120143}{120173}Dobro.
{120257}{120294}PoËni proces isËiöÊavanja.
{120328}{120354}UZBUNA
{121037}{121174}Oporavak je neverovatan,|fiziËki i mentalni oporavak je nevien.
{121426}{121508}äta?
{121543}{121567}Gde si?
{121602}{121648}Bolesna si.
{121657}{121701}Hajde.
{121771}{121796}Tako je.
{121815}{121840}Eto nas.
{122155}{122188}Znaö li öta je ovo?
{122241}{122274}Ovo je olovka.
{122298}{122371}Vidiö... Ti pokuöaj.
{122462}{122488}Tako je.
{122524}{122548}Olovka.
{122706}{122785}Pogledaj me.
{122813}{122877}SeÊaö li se iËega?
{122959}{122997}SeÊaö li se imena?
{123045}{123079}Moje ime...
{123222}{123279}HoÊu da je 24 Ëasa|nadgledaju.
{123317}{123422}HoÊu celu analizu krvi|do kraja dana
{123476}{123513}Moje ime...
{123549}{123629}Moje ime...|-Gospodine, testiranje refleksa je isto prioritet.
{123689}{123741}Da se elektronski|impulsi prate...
{123795}{123826}Gospodine!
{123896}{123923}äta je sad?
{124021}{124067}Moje ime...
{124102}{124136}je Alis.
{124228}{124264}I svega se seÊam.
{125060}{125110}Ovo je centrala, treba|nam podröka, odmah!
{125119}{125154}Maksimalni nivo odziva!
{126156}{126216}Hvala gospodo, mi|sad preuzimamo.
{126230}{126312}Treba nam autorizacija.|-Klasifikovani smo, autorizacija 6.
{126401}{126432}Pardon gospodine.
{127864}{127896}Pusti ih da idu.
{127997}{128046}Drago nam je öto|si se vratila.
{128101}{128131}JEsi li dobro?
{128153}{128203}Program Alis Aktiviran.
{128346}{128379}äta su ti uradili?
{128411}{128703}PREVOD I OBRADA|»EDO FILM - by Lucifer
{128728}{130228}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
