{1}{1}25.000
{26}{176}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{1467}{1591}Film Pedra Almodovara
{1717}{1828}LOäE OBRAZOVANJE
{3560}{3646}Magija ovog ledenog vremena|je öËepala svoju prvu ûrtvu.
{3670}{3735}Motorciklista se smrzao na |autoputu broj 4
{3753}{3828}i vozio je joö 90 kilometara|nakon smrti.
{3885}{3934}Dvojica policajaca su|ga zaustavljala.
{3949}{4014}a poöto motorista nije reagovao|oni su ga gonili.
{4032}{4070}Vozili si kraj njega
{4079}{4121}i prekoravali zbog takvog ponaöanja.
{4140}{4203}a poöto se on nije maËinjao|uvideli su da neöto nije u redu.
{4220}{4250}To zvuËi neverovatno.
{4264}{4297}To je neverovatna slika.
{4321}{4390}Mlad, mrtav Ëovek vozi svoj|motor kroz zaleenu planinu.
{4411}{4453}u pratnji dva policajca.
{4472}{4514}Gde je iöao te tog |ledenog sumraka.
{4547}{4603}Da vidi nekog koga nije moga|da Ëeka do jutra.
{4642}{4675}Ovo je priËa.
{4699}{4753}IseÊiÊu je i zadrûati.|Moûe biti inspirativna.
{4853}{4882}Ja Êu.
{5028}{5067}Zdravo.|äta treba?
{5084}{5121}Ja sam glumac.|Traûim Enrikea Godeda.
{5135}{5160}On nije ovde.
{5204}{5239}Ali ja ga vidim ËoveËe.
{5264}{5329}U svakom sluËaju, nemamo nikakav|projekt, pa...
{5345}{5402}Voleo bih da popriËam sa njim.|Mi smo drugovi iz ökole.
{5417}{5454}Ja sam Ignacio Rodrigez.
{5481}{5525}Dobro. Ui.|Hvala.
{5549}{5603}Ne verujem da Êe te primiti.|Nema veze.
{5627}{5672}SaËekaj malo.
{5707}{5747}On je glumac, neprilika.
{5756}{5809}Rekao sam mu da ne spremamo|nikakav film.
{5840}{5892}Kaûi da nisam ovde.|Reako sam, ali te je on video.
{5914}{5934}Ali ne mogu da ga primim.
{5946}{5995}Kaûe da je drugar iz ökole.
{6039}{6085}Kako se zove?|Ignacio Rodrigez.
{6138}{6161}NemoguÊe.|Tako je rekao.
{6174}{6211}Ignacio, to si stvarno ti?
{6314}{6363}Naravno Enrike.
{6418}{6481}Lepo öto me se seÊaö.|Kako bih mogao tebe da zaboravim.
{6509}{6560}Pa proölo je 16 godina.
{6578}{6609}Toliko?|Manje-viöe.
{6628}{6689}Ne bih te nikada prepoznao|zbog te brade.
{6701}{6764}Izgledaö bolje bez nje.|Ui u kancelariju.
{6778}{6815}HoÊeö li kafu?|Ne hvala.
{6839}{6862}Ja Êu uzeti jednu.|Onda dobro.
{6904}{6959}Martine, da li bi nam skuvao kafu?|Da.
{7009}{7048}Sedi.
{7070}{7103}Otkud ti?
{7126}{7176}Doöao sam da pitam za posao.|Ja sam glumac.
{7203}{7262}Doneo sam svoj CV.
{7346}{7426}Grupa Bumblebii.|Nezavisna pozpriöna trupa.
{7503}{7573}"El Retablillo de San Cristoba"|Od Garsija Lorke.
{7646}{7710}"Dnevnik Adama i Eve" od Mark Tvena.
{7737}{7775}Mark Tven, Garsija Lorka...
{7787}{7835}Samo najbolje u Bamblbiu.
{7857}{7879}zar viöe ne piöeö?
{7895}{7926}Prestao sam pre par godina.
{7940}{7998}Ali sam doneo moju poslednju priËu.
{8093}{8123}"VIZITA" od Ignacija Rodrigeza.
{8137}{8170}"Vizita"...
{8190}{8268}Uzgred, kada poËinjeö|sledeÊi film?
{8287}{8335}Pa...|Sve Êu da uËinim.
{8351}{8431}Pregledavamo tabloide da vidimo|da li Êu da iznaem priËu.
{8451}{8498}Uhvatio si me u|kreativnoj krizi.
{8510}{8537}Baö neprijatno.
{8560}{8625}ProËitaj moju priËi|moûda Êe neöto da ti sine.
{8640}{8678}O Ëemu je?
{8690}{8706}O naöoj ökoli.
{8717}{8756}Jedan deo je vezan|za naöe detinjstvo.
{8770}{8851}a drugi nije, kada|obrauje likove koji su odrasli.
{8868}{8898}To je priËa.
{8914}{8979}Nisam ti predstavio.
{8993}{9012}Ignjaciov  Martin...
{9037}{9057}Drago mi je.
{9087}{9098}äeÊer i mleko?|Da.
{9106}{9140}Uzgred, viöe nisam Ignacio.
{9157}{9195}Ja sam Anhel.
{9209}{9228}A zaöto?
{9240}{9259}To mi je umetniËko ime.
{9270}{9312}Ne moûe glumac da se|zove Ignacio Rodrigez.
{9337}{9375}Ne moûe?|Naravno da ne.
{9390}{9418}Anhel Andrade.
{9434}{9493}Svi me tako zovu.|»ak i moja majka.
{9504}{9534}Baö dobro.
{9545}{9565}Hvala.
{9587}{9615}Ignacio je..|Anhel.
{9668}{9687}Ignacio|Anhel.
{9740}{9784}Onda, Ignacio, pre nego öto|je postao Anhel,
{9809}{9860}bio..|stari ökolski drug.
{9878}{9909}Martin je moj direktor produkcije.
{9923}{9945}I devojka za sve.
{9975}{10006}Pa Ignacio...|Anhel!
{10034}{10051}Dobro.
{10073}{10112}Drago mi je da sam te video.
{10123}{10167}I Ëim budem neöto imao...
{10179}{10220}Daj mi tvoj broj,|i zvaÊu te.
{10235}{10268}Nemam telefon.
{10278}{10304}Ali Êu ja tebe zvati.
{10314}{10346}Da ostavim neke fotografije.|Ne, ne brini.
{10426}{10481}Pa, Anhel, drago|mi je da smo se videli.
{10515}{10559}Treba da idem?|Mislim da da.
{10606}{10690}Mogu li da ti pomognem oko seËenja...?|Ne hvala ti.
{10728}{10759}Do vienja.|Drago mi je.
{10840}{10878}OdliËno izgledaö.
{10895}{10931}Ti takoe.
{10950}{10990}ProËitaj "Vizitu".|HoÊu.
{11017}{11076}Naravno da hoÊu.|Vaûi. Vidimo se.
{11129}{11170}Mislio sam da nikada neÊe da ode.
{11198}{11251}Da li ti je stvarno tvoj prijatelj?|Jeste.
{11284}{11334}Nisam ga video joö od ökole.
{11351}{11390}Bili smo veoma bliski.
{11409}{11457}On je bio moja prva ljubav.
{11487}{11535}Ali se puno promenio.
{11548}{11582}Nisam ga prepoznao.
{11593}{11657}HoÊeö li ga opet videti?
{11693}{11707}Ne.
{11729}{11764}Ali, Ëinilo se da ga voliö.
{11776}{11854}Ne, nema niöta manje erotiËnog|od glumca koji traûi posao.
{11871}{11923}"Vizita"
{12014}{12081}Od kako smo poËeli da pripremamo|predstavi "Bomba"
{12093}{12137}»ekao sam taja trenutak.
{12159}{12240}Danas igramo u gradu u kojem|sam iöao u ökolu.
{12260}{12334}Ne pominjem njegovo ime|da ga ne bih promovisao.
{12359}{12414}Moje najlepöe uspomene vezane|su za bioskop "Olimp"
{12431}{12470}koji je danas sav ruiniran.
{13043}{13091}Kartu.
{13203}{13247}Dojadilo mi je da gubi.|Onda se povuci.
{13287}{13313}Odmori.
{14250}{14311}Hvala
{14366}{14428}Ona sebe definiöe kao...
{14446}{14506}miks pustinje, kocke,
{14518}{14559} i kafeterije.
{14574}{14613}Ona je veliki umetnik
{14625}{14678}i moja velika prijateljica.
{14708}{14740}Za sve va
{14753}{14783}naöa sledeÊa taËka,
{14796}{14818}misterija
{14830}{14853}i fascinacija
{14871}{14894}jedna i jedina,
{14912}{14931}jedinstvena
{14952}{14978}Zahara!
{15002}{15034}Malo aplauza |za Kitas!
{17105}{17137}Pa...|äta?
{17178}{17236}Sluöaj...|Vidimo se u hostelu.
{17246}{17287}Da ali...|Pakito, Ëuo si me.
{17378}{17436}Imaö vremena za|sve pederu.
{17471}{17493}Monda.
{17506}{17540}»ekaj me ljubavi!
{17650}{17671}Zdravo.
{17709}{17803}äta je bilo?|Ne mogu da naem kljuËeve.
{17837}{17874}Mogu li ti pomoÊi?
{17896}{17916}Naravno.
{18074}{18111}Ne, nisu ovde.
{18159}{18180}Da vidimo.
{18340}{18362}Nisu ni ovde.
{18561}{18588}Evo ih.
{18922}{18962}Usne su mi se zamorile.
{18990}{19055}Previöe sam popio.
{19068}{19106}Rekao si mi.
{19408}{19516}Hej!|Puöim ti kurac!
{19672}{19715}On se zanesvesti.
{20080}{20109}Dete.
{20293}{20328}Ni dinara.
{20358}{20394}Loto tiket,|To Êu zadrûati.
{20477}{20537}Nemoj paliti auto|odmah ispred
{20550}{20600}Ali onesvestio se!|Pijan, zar ne?
{20615}{20634}Nije loö
{20647}{20706}I vidi, joö uvek mu je dignut.
{20736}{20840}Ljubav...
{20852}{20897}Pusti me da mu popuöim malo.|Ne, moraö da obaviö neke stvari
{20915}{20956}Ti si bio sa njim satima.|Pogledaj usnu.
{20971}{20996}Ajde.|Motor neÊe pobeÊi.
{21012}{21074}Umukni!|Idi sakri motor.
{21087}{21138}I poûuri, Vidimo se|u tvojoj sobi pre sedam.
{21162}{21209}Dobro, Ja prljam ruke|dok se ti zabavljaö.
{21274}{21312}Sada ti se digao, kretenu!
{21347}{21374}Nije fer.
{21466}{21494}Enrike Serano.
{21628}{21662}Enrike!
{21702}{21875}Pakito!
{21950}{21978}Doi gore!
{21990}{22012}A motor?
{22028}{22062}Ostavi ga. Doi gore.
{22161}{22215}Niöta bolje nego|nadrogirati se
{22228}{22261}ili biti na hormonima.
{22281}{22322}da bi zavröio|lud kao ti kuËko.
{22668}{22718}Daj kljuËeve!|NeÊemo da ukrademo motor!
{22731}{22771}Zaöto ne?|Imamo kupca.
{22788}{22846}ObjasniÊu kasnije.|NaÊiÊemo se kasnije.
{22858}{22927}ZnaËi idemo u ökolu?|Da, ide mi se viöe nego ikad.
{22937}{22986}PoËinjem da ludim kuËko!|Mogu da zamislim.
{24106}{24156}Dragi Enrike,|to sam ja, Ignjacio.
{24186}{24240}Toliko sam sanjao|o ovom momentu!
{24265}{24328}Proöle su godine|ali ja te nisam zaboravio.
{24337}{24397}Moramo se ponovo naÊi,|ali kada nisi oduzet.
{24416}{24481}HoÊu da ti priËam o svom ûivotu|i da sluöam o tvom
{24491}{24546}dok jedemo kolaËe| u poslastiËarnici Malol,
{24555}{24602}Kao kada smo beûali|iz ökole vikendom.
{24636}{24681}NeÊu ti zakomplikovati ûivot.
{24690}{24733}Znam da si oûenjen|i da imaö dete.
{24756}{24803}Znam da ûiviö u drugom gradu,
{24815}{24881}da si bez para|i voleo bih da ti pomognem.
{24899}{24966}Trenutno radim na neËemu,
{24993}{25052}Ali sve Êu ti objasniti|u poslastiËarnici.
{25075}{25116}»ekaÊu te od 6 do 7.
{25134}{25168}Doi.
{25200}{25227}Oboûavam te.
{25246}{25269}Ignjacio.
{26617}{26683}Da?|Nedostajeö mi.
{26695}{26731}Jesi li odpakovao|sve kutije?
{26775}{26823}Ne, ni polovinu.
{26850}{26913}Treba li ti pomoÊ?|Ne bi mi smetalo.
{26925}{26963}Bolje ne Martine,|Hvala.
{26993}{27031}Mogu li te pozvati kasnije?
{27041}{27077}»itam.|Oprosti mi.
{27093}{27137}Ne budi tako jebeno oseÊajan!
{27151}{27224}ZvaÊu te kasnije.|Zovi, Ëak i ako je kasno.
{27438}{27511}Ovde smo gledali Sarine prve filmove.
{27524}{27575}i "DoruËak kod Tifanija"
{27592}{27668}Ovde smo se spustili|jedan drugom po prvi put.
{27707}{27775}Klecaju mi kolena|od same pomisli na to.
{27895}{27949}Nalazim se sa njium|u 6 u poslastiËarnici.
{27960}{28031}Ne nadaj se.|On je oûenjen.
{28047}{28085}Da nas Fr. Manolo|nije razdvojio...
{28099}{28131}Kakve sad to veze ima?
{28143}{28170}Velike, sve!
{28181}{28250}Taj pop mi mnogo duguje|i vreme je da plati.
{28281}{28324}Ne podnosim da te gledam ovakvog.
{28335}{28367}Jel ti ostalo neöto?
{28414}{28427}äta?
{28437}{28457}Speedball.
{28475}{28501}Ajde da se uradimo.
{28517}{28554}Ovde?|Naravno.
{28567}{28618}Joö nisu izaöli na ulice.
{28631}{28662}U pederËino!
{28683}{28706}Ajde
{28716}{28754}Pun nokat za moju ûensku PAKU:
{28873}{28932}Joö jedan.|Ja verujem u parove.
{28950}{28995}Dva tucanja, dva dupeta,|dva "drugara".
{29072}{29125}"dvojica su vozila",|"Dvojica za put".
{29198}{29222}Takva si svinja!
{29261}{29297}Idemo u ökolu!
{29312}{29335}Diûi se ûenska!
{29423}{29477}Ajde, samo napred.
{29558}{29612}Ovo je bila moja ökola.
{29649}{29697}Puöta me.|Jel ti ostalo joö malo?
{29732}{29756}∆uti.
{29812}{29829}PoËelo je.
{29877}{29956}Bog nade koji,|po milosti Svetog Duha,
{29975}{30025}puni nas Njegovom sreÊom i mirom...
{30033}{30056}To je Otac Manolo.
{30066}{30125}Izgleda staro!|Pa nije on kokoöka.
{30133}{30155}Predpostavljam.
{30167}{30205}Zahara, ovo je ludost!
{30216}{30262}PovlaËiö se kuËko?
{30294}{30362}Ne, ali kapela je mala|nema gde da se sakrije.
{30376}{30419}Kada nas bude video,
{30431}{30470}uradiÊe sa nama ono öto|je Isus uradio prodavcima u hramu.
{30481}{30538}Isterao ih je biËem,|a on je bio Isus!
{30550}{30586}Tako da ovaj ovde,|koji je toliko nesavröen...
{30614}{30800}Priznajem Bogu,|svemoÊnom Ocu,
{30812}{30848}i tebi, svom bratu,
{30862}{30933}da sam greöio|mislima, reËima,
{30947}{30974}i delima.
{30989}{31032}Svojim greökama.
{31056}{31095}Tvojim greökama.|Svojim greökama.
{31122}{31160}Tvojim greökama.
{31179}{31201}Svojim smrtnim gresima.
{31224}{31251}Molim Devu Mariju, prisnodjevi,
{31268}{31292}Andjelima, svecima,
{31301}{31322}i vama mojoj braÊi,
{31336}{31381}da me oËistite greha|pred naöim Bogom.
{31407}{31458}SvemoÊni boûe|smiluj se na nas,
{31489}{31538}Oprosti nam grehe|i vodi nas u veËni ûivot
{31579}{31617}kroy gospoda naöeg Isusa Hrista.
{31638}{31685}VideÊemo.
{31701}{31723}Neka je Bog sa vama.
{31743}{31762}Trebao bi mi.
{31787}{31817}U ime Oca i Sina,
{31845}{31872}i Svetoga Duha
{31920}{31947}Amin
{31985}{31994}Moûete iÊi u miru.
{32006}{32037}Nadam se.
{32716}{32785}Vrati se u spavaonicu|i odspavaj malo.
{32799}{32818}Hvala oËe.
{33085}{33131}Ako se dugo zadrûim,|nemoj me Ëekati.
{33148}{33198}NaÊi Êemo se u hotelu|za ruËak,
{33244}{33268}Duöo.
{33388}{33419}Slatko.
{33494}{33525}Predivno.
{33644}{33677}Dobro jutro OËe Manolo.
{33725}{33800}äta hoÊeö? Ne moûeö uÊi ovde!
{33812}{33879}Ja sam sestra bivöeg uËenika.|Ignjacija Rodrigeza.
{33887}{33929}I dalje ne moûeö uÊi ovde!
{33943}{33976}Ne seÊate ga se?
{33993}{34024}Imali smo mnogo uËenika.
{34043}{34111}Ali ni jednog kao öto je Ignjacio|Sigurna sam.
{34137}{34180}Donosim vaûnu poruku|od njega.
{34214}{34248}Moûe sam da mi je kaûe.
{34260}{34274}Ne moûe.
{34293}{34337}Umro je u nesreÊi.
{34357}{34451}éao mi je.
{34469}{34529}Molim vas idite.
{34556}{34575}Idite.
{34770}{34826}Sakrij se!|Sve sam uzeo!
{34860}{34875}Sakrij se, dolazi!
{36427}{36462}Ignjacio...
{36547}{36670}Rekao sam vam da idete!|äta radite ovde?
{36686}{36747}Isto öto i vi,|seÊam se Ignjacija.
{36767}{36800}Napolje!
{36820}{36856}Moramo da priËamo, OËe.
{36868}{36913}TrebaÊe mi samo minut.
{36931}{36987}Recite öta imate a |onda odlazite!
{37030}{37070}PriËaÊemo u tami?
{37108}{37141}Ne smeta mi.
{37150}{37188}Navikla sam da radim u mraku.
{37206}{37227}äta hoÊete?
{37263}{37311}Bolji ûivot
{37343}{37386}I bolje telo.
{37414}{37469}äta ja mogu da radim|za tim promenama?
{37518}{37564}Moûete mi pomoÊi da|ih finansiram.
{37581}{37629}Ne verujem|da je Ignjacio mrtav
{37643}{37676}niti da si ti njegova sestra.
{37691}{37742}»ak ni ne verujem|da si ti ûensko.
{37885}{37930}ZakljuËavate me?
{37939}{37995}Ne ûelim da neko ue greökom.
{38043}{38088}A ti,|reci mi zaöto si ovde"
{38110}{38151}Ok. PreÊi Êu na stvar.
{38250}{38298}Ovo je Ignjaciova priËa.
{38324}{38400}Tako je, prihvatio je tvoj|savet i nastavio je da piöe.
{38414}{38463}Imam prijatelja, svinju,
{38475}{38501}Koji radi u "Diario 16".
{38511}{38567}Veoma ga zanima|da objavi ovu priËu.
{38580}{38627}Ali me prvo zanima vaöe miöljenje.
{38638}{38687}Pored toga öto ste|bili Ignjaciov uËitelj
{38706}{38776}Vi ste jedan od|glavnih likova u ovoj priËi.
{38861}{38897}ProËitajte.
{38927}{38987}Svakog meseca, deËaci su|se pojavljivali na tabli.
{38998}{39026}to jest, oni koji|su imali najbolje ocene,
{39057}{39110}bili si nagraivani|danom u selu.
{39126}{39200}Uvek smo bili praÊeni naöim nastavnikom,
{39218}{39248}Ocem Manolom.
{39475}{39510}Ignjacio!
{41718}{41775}Kap krvi se razdvojila|na mom Ëelu.
{41791}{41844}Mislio sam da Êe ista stvar|da se dogodi sa mojim ûivotom.
{41858}{41944}Uvek Êe biti razdvojen|a ja nisam mogao niöta da uËinim.
{42144}{42193}Otvorite vrata OËe. To je I.
{42457}{42493}äta se desilo?|PljaËka.
{42505}{42543}Gde?|U kapeli.
{42562}{42601}Desilo se posle vaöe mise.
{42625}{42681}Da li vam nedostaje neöto?
{42695}{42774}Moraju biti naeni!
{42800}{42901}DeËaci nesmeju Ëuti za to.|U redu.
{42927}{42994}I niko me ne sme uznemiravati,|sem tebe.
{43312}{43354}To je bio otac Jos?
{43373}{43406}Ignjacio ga je mrzeo.
{43419}{43468}Joö uvek tuËe uËenike?|Nikada nije takao Ignjacija.
{43537}{43583}To je bila|privilegija direktora.
{43623}{43679}Ovako,|éelim milion u keöu.
{43713}{43787}Ili Êe "Diario 16"|objaviti celu priËu.
{43804}{43874}Nemam milion pezeta,|pogotovo u keöu.
{43889}{43919}Ali moûete nabaviti.
{43955}{44004}Sada bih, ako nemate|niöta protiv, otiöao.
{44016}{44056}Rekao sam sve öto sam hteo.
{44082}{44129}Ali nastavite da Ëitate,|kasnije je bolje.
{44192}{44231}KljuË.|SaËekaj.
{44249}{44300}saËekaj do posle odmora.
{44319}{44356}Samo pa minuta.
{44385}{44443}ZnaËi doöao si da me ucenjujeö.
{44463}{44550}Reci Ignjaciju da preteruje,|ovaj tekst, to je ubre!
{44573}{44612}–ubre je vruÊe!
{44625}{44700}Vi i ja smo savröen par.
{44731}{44764}i urednik "Diaria 16" to zna.
{44776}{44826}Ti nisi u poziciji da pretiö bilo kome.
{44843}{44900}Ljudi Êe verovati meni, a ne tebi.
{44937}{44998}Ne, ljudi su se promenili.|Sada je 1977.
{45024}{45087}Ovo druötvo stavlja moju|slobodu ispred hipokriteta.
{45131}{45218}Ako sam tako loöe tretirao Ignjacija,|zaöto se vratio?
{45231}{45298}Zaöto nas nije prijavio|ili promenio ökolu?
{45377}{45452}Vratio se jer|se zaljubio,
{45469}{45504}u druga iz odeljenja.
{45522}{45567}Enrike Serano.
{45579}{45601}SeÊate ga se?
{45611}{45625}Da.
{45639}{45736}SmetaÊe vam ako nastavim da Ëitam?
{45858}{45918}bilo je dosta proslava u ökoli.
{45926}{45985}najvaûniji je bio dan direktora.
{46002}{46060}Tada je bolo sportskih takmiËenja.
{46070}{46133}Religioznih Ëinova,|i imali smo poseban obrok.
{49110}{49131}Poi samnom Ignjacio.
{49154}{49181}Polazi.
{49238}{49300}Nisam zavröio.|Bolje Êeö da pevaö tako.
{49538}{49575}Znaö li nove reËi?
{49600}{49651}Da imam skriptu koju mi|je Otac Manolo dao.
{49666}{49706}Zovi ga PreËasni Direktor.
{49725}{49775}Od danas je direktor ökole.
{49789}{49826}Znam.|Ne odgovaraj.
{49863}{49936}Kada pevaö,|nastavi da ga gledaö,
{49950}{50004}kao da niko drugi|ne postoji u hali za ruËavanje.
{50016}{50049}Razumeö?|Da.
{50123}{50188}Otac Jos me je postavio u sredinu hale.
{50204}{50276}OseÊao sam se Ëudno pred|svim tim sveötenicima koji ruËaju,
{50292}{50313}i bio sam uplaöen
{50325}{50389}ali svi su me neûno|gledali sem Oca Manola
{50391}{50477}Koji je izgledao kao da Êe da zaplaËe.
{50497}{50537}A sada Otac Jos Manuel.
{50548}{50591}Kao roendanski poklon,
{50600}{50642}Ignjacio Êe zapevati
{50654}{50701}jednu od vaöih omiljnih pesama.
{50718}{50754}"Torna A Sorrento".
{50767}{50806}Nove reËi, "Baötovan",
{50823}{50869}napisao je Otac Manolo,
{50891}{50936}a pomogla mu je moja malenkost.
{50968}{51005}Kada budeö bio spreman, Ignjacio.
{53587}{53660}Mislio sam da ti se ne dopadam.|Ne, baö obrnuto!
{53677}{53753}Ali svaki put kada sam te pogledao,|ti si okrenuo glavu.
{53766}{53807}Jer si me Ëinio nervoznim.
{53860}{53892}A sada ne?|Ne.
{54119}{54132}"TA éENA"
{54141}{54160}Uite.
{54307}{54337}Mogu li vam pomoÊi?
{54386}{54430}Ne prepoznajete me, Majko?
{54510}{54561}Zar se svet toliko promenio?
{54592}{54639}Majko Soledad!
{54724}{54762}äta radite ovde?
{54784}{54815}Doöla sam da ostanem.|Da ostanete?
{54861}{54898}Sara je prelepa!
{55094}{55134}U ovoj kuÊi?
{55219}{55239}Ne.
{55286}{55324}Nikada.
{55346}{55375}Ko se seÊa da li sam uradila|neöto öto nisam trebala?
{55386}{55439}To je nemoduÊe.
{55496}{55529}Ne odbacuje te Bog.
{55552}{55612}Ja te odbacujem.
{55642}{55712}U ime svog reda.
{56895}{56942}äta nije u redu?|Ne mogu da spavam.
{56967}{57008}Ne mogu ni ja.
{57024}{57065}Ono öto smo uadili u bioskopu|nije bilo u redu.
{57080}{57122}Dopalo mi se.|I meni.
{57144}{57209}Ali mislim da je to greh|i Bog Êe nas kazniti.
{57223}{57247}Bog?
{57258}{57288}Ja ne verujem u Boga.
{57307}{57335}U öta verujeö?|Ja sam hedonista.
{57379}{57435}äta je to?|To su ljudi koji vole zabavu.
{57451}{57489}ProËitao sam u enciklopediji.
{57545}{57592}äta nije u redu?
{57791}{57824}»ujeö to?
{57838}{57875}Otac Manolo!
{59182}{59240}Otvorite vrata!|Ili Êu ih provaliti
{59258}{59316}i pustiti celu ökolu da zna öta ste uradili.
{59364}{59389}Ignjacio!
{59414}{59452}Znam da ste unutra!
{59469}{59500}Video sam vam noge.
{59523}{59575}»ujem kako diöete.
{59608}{59626}Ignjacio.
{59704}{59733}Ne radimo niöta!
{59755}{59879}Izalzi.
{59898}{59932}Sa tobom Êu kasnije.
{59955}{59994}Ne ostavljam Ignjacija samog sa vama.
{60012}{60041}Kako se usuujeö!
{60059}{60109}Ilzazi odavde smesta!
{60158}{60190}Molim te Enrike.
{60220}{60251}Uradi kao öto kaûe.
{60587}{60609}Doi ovamo.
{60780}{60816}äta ste radili unutra?
{60834}{60858}Niöta.
{60913}{60939}Niöta?
{60972}{61007}Kunem se OËe.
{61024}{61069}Zaöto ste zakljuËali vrata?
{61186}{61207}Doi.
{61251}{61289}Hajde samnom u kapelu.
{61339}{61573}Zvono!
{61599}{61630}O Ëemu razmiöljaö.
{61715}{61822}Mislim da sam upravo u|tom trenutku izgubio veru,
{61836}{61886}tako da viöe ne verujem u Boga ili pakao.
{61916}{61980}I poöto ne verujem u pakao|ne bojim se,
{61996}{62047}a bez straha mogu da uradim öta hoÊu.
{63135}{63173}ZaboraviÊemo ovo Ignjacio.
{63194}{63259}»ak i da ûelim,|ne mogu da se ljutim na tebe.
{63280}{63363}Ali obeÊaj da öta se dogodilo veËeras,|neÊe se ponoviti.
{63384}{63423}A Enrike?
{63453}{63485}äta sa njim?
{63502}{63536}BiÊe kaûnjen?
{63552}{63590}Trebalo bi da ga izbacim.
{63626}{63672}Siguran sam da je|on za sve odgovoran.
{63696}{63727}Nije, ja sam.
{63833}{63883}Ne plaËi.
{63915}{63975}On loöe utiËe na tebe.
{63991}{64044}Ja ûelim ono öto je najbolje za tebe.
{64145}{64204}Ako ga ne izbacite,|uradiÊu öta hoÊete.
{64234}{64258}∆uti.
{64353}{64397}Prvi put sam se prodao u toj kapeli
{64414}{64459}da Enrike ne bi bio izbaËen.
{64471}{64509}Ali Otac Manolo me je prevario.
{64524}{64588}I zakleo sam se da Êu|mu se osvetiti jednog dana.
{64628}{64766}Na noge!
{64859}{64915}Ruke iza glave.
{64930}{64950}I, jedan!
{64965}{64982}Promena.
{64996}{65320}Poûuri Enrike,|propustiÊemo autobus!
{65854}{65892}Drago mi je da si doöao.
{65915}{65946}Bolje izgledaö bez brade.|Hvala.
{65988}{66051}äta to radiö?
{66079}{66100}Ponovo Ëitam tvoju priËu.
{66111}{66147}Zar ti se prvi put nije dopala?|Ma jeste.
{66162}{66195}Ali, pogledaj je.
{66219}{66264}Pravio sam zabeleöke.|MoÊ navike.
{66288}{66334}Nema veze.|To je tvoj primerak.
{66365}{66382}Hvala.
{66414}{66475}Pa...|Kako da kaûem?
{66497}{66536}Mislim da u ovoj priËi|leûi dobar film.
{66551}{66594}I ja bih voleo da ga reûiram.
{66636}{66688}Stvarno?
{66700}{66740}Ne zavitlavaö me?
{66765}{66795}Nikada se ne zavitlavam oko posla.
{66807}{66869}Ali, prvo mi reci koliko traûiö|za prava.
{66883}{66940}Ma kakva prava?
{66953}{66987}To je tvoja priËa.
{67003}{67054}Uradi sa njom |öta ûeliö.
{67084}{67111}I stvarno ti se dopada?
{67124}{67191}Priznajem da kada si rekao|da se radi o naöem detinjstvu
{67224}{67250}ja sam se osetio,
{67263}{67282}uplaöenim.
{67294}{67332}Ali je ona veoma dirljiva.
{67362}{67402}»oveËe, koliko sam sreÊan.
{67422}{67484}Zapamti da sam ja glumac i|da ûelim da zbriöem od Bamblija.
{67501}{67525}Da, znam to.
{67536}{67571}Ti bi bio izvanredan kao|Enrike Serano.
{67584}{67605}Go u krevetu,
{67616}{67659}Sa Zaharinim pismima|na jastuku.
{67676}{67697}Enrike Serano?
{67717}{67775}Mislim da bih bolje igrao Zaharu.
{67789}{67825}Ti Zahara?
{67836}{67858}Jesi li lud.
{67871}{67904}Zaöto?|Pa..
{67937}{68000}Ti si veoma dobro graen.|Nisi taj tip.
{68029}{68073}Martine, imamo priËu!
{68094}{68144}Mogu da oslabim.|Mogu da uem u ulogu.
{68158}{68211}Navikao sam na to u teatru|kao De Niro...
{68245}{68275}Napravi fotokopiju.
{68350}{68374}"Vizita"?
{68387}{68400}Da.
{68413}{68457}Ignacio i ja Êemo da|poËnemo da radimo na tekstu.
{68470}{68532}Ako Êeö ti da reûiraö,|najbolje je da ga sam napiöeö.
{68554}{68586}Vaûi.Ignacio.
{68600}{68652}Anhel"|PoËni da me zoveö Anhel,
{68664}{68709}ili se nikada neÊeö naviÊi.
{69037}{69077}HoÊeö li da voziö?
{69089}{69119}Ja sam malo pripit.
{69132}{69198}»udi me da uopöte moûeö da ideö|kada si toliko popio.
{69211}{69242}Pa morali smo da proslavimo.
{69254}{69292}Mislio sam da Êemo priËati|o samom projektu.
{69308}{69336}PriËaÊemo kasnije.
{69351}{69394}Imamo vremena.
{69742}{69771}SeÊaö se?
{69828}{69857}»ega?
{69920}{69947}NiËega.
{70033}{70071}Ti si stvarno odlepio.
{70109}{70150}»ega da se satim?
{70166}{70190}NiËega.
{70278}{70309}Skreni ovde.
{70844}{70878}Sve je ovo tvoje?
{70891}{70928}Nije, samo|ga iznajmljujem.
{70961}{71027}Ne divi se previöe.|unitra je straöan nered.
{71182}{71215}HoÊeö li da plivamo?
{71232}{71275}To Êe ti dobro Ëiniti.
{72476}{72500}Kakva je voda?
{72515}{72549}»eka na tebe.
{74655}{74676}HoÊeö li mi dodati cigarete?
{74930}{74999}Nisi ozbiljno mislio da|igraö Zahara, jelda?
{75022}{75051}Sasvim ozbiljno.
{75069}{75117}Ni ja se ne zavitlavam oko posla.
{75138}{75176}Ajde da onda ne priËamo o poslu.
{75208}{75237}äta Êeö da radiö?
{75250}{75284}Da spavaö ovde, ili|da se vratiö u Madrid?
{75312}{75346}Ako ûeliö, ostaÊu.
{75371}{75419}Ali ako priËamo o telima,
{75441}{75505}ako izgledam debelo|ja Êu oslabiti.
{75526}{75562}Ja sam veoma fleksibilan|mogu sve da uËinim.
{75613}{75650}Ti me zbunjujeö Anhel.
{75667}{75700}To si mi veÊ jednom rekao.
{75734}{75771}I ti si meni o slabljenju.
{75797}{75838}Hajde da rasËistimo.
{75879}{75926}Ne mogu da budem jasniji.
{75939}{75962}Ja sam glumac.
{75974}{76052}Proveo sam tri godine radeÊi|sranja sa Bamblijem.
{76065}{76123}Ovo je moja prva prilika|da dobijem odliËnu ulogu.
{76137}{76174}I ne ûelim da je ispustim.
{76196}{76226}Ti ne moûeö da igraö Zaharu.
{76238}{76290}Ne na prvi pogled|ali mi daj vremena.
{76315}{76345}Ti si dobar reûiser.
{76354}{76386}A ja Ëi da dam sve od sebe.
{76411}{76446}Ti samo treba da|nam verujeö, obojici.
{76502}{76562}Prokuöao sam.
{76574}{76611}Ali ne mogu da verujem tebi.
{76632}{76654}Zaöto?
{76723}{76786}Zato öto ne mogu da prepoznam |ignjacija kojeg znam iz ökole.
{76832}{76905}Onog koji voli "Cuore MAtto"|i mnoge druger stvari.
{76923}{76955}Moj ukus se promenio.
{76996}{77030}To tebe muËi?
{77109}{77138}Ljudi se vremenom menjaju.
{77175}{77197}Ti ne.
{77214}{77257}Jednostavno, ti nisi Ignacio.
{77278}{77345}A ko si pa ti da odluËujeö|ko sam ili ko nisam?
{77374}{77404}Kako se usuujeö?
{77441}{77485}Zaöto ja nisam Ignjacio?
{77499}{77554}Zato öto se ne seÊam pesme|od pre puno godina?
{77587}{77650}Ne samo zbog toga.|Zato öto ti nisam popuöio?
{77700}{77785}Da sam ostao onaj klinac kojeg si znao|ja bih veÊ bio mrtav.
{77801}{77837}Ja veÊ jesam.
{77864}{77897}Mrtav umoran.
{77926}{77957}Idem u krevet.
{77973}{78012}äta Êeö ti da radiö?
{78041}{78075}Ne znam.
{78091}{78125}Ti mi reci.
{78137}{78171}äta da ti kaûem?
{78201}{78260}Da li Êu da igram Zaharu.
{78294}{78345}Da li tvoj ostanak |zavisi od toga?
{78363}{78387}Ne.
{78401}{78454}Ali ako ja ne igram Zaharu|nema niöta od filma.
{78499}{78582}Onda ne znam zaöto si|ovde puöiko.
{78610}{78629}Marö napolje.
{78786}{78851}Zaöto li odluËih da te |opet vidim pederËino!
{79489}{79562}"éena se bacila u bazen|pun gladnih krokodila
{79575}{79627}i zoovrtu koji je bio|tada pun posetilaca.
{79653}{79723}Kada ju je prvi krokodil napa|ûena ga je obgrlila,
{79737}{79762}kako kaûu svedoci.
{79775}{79834}Krokodil je proûdrao |njeno telo.
{79853}{79887}za öta mu je trebalo
{79901}{79930}nekoliko minuta.
{79949}{79985}Kakva uûasna smrt.
{80005}{80026}Pa...
{80059}{80098}Ona nije ni otvorila usta.
{80248}{80273}O Ëemu razmiöljaö?
{80353}{80391}O gladnom krokodilu.
{82200}{82226}Zdravo, ui.
{82257}{82289}O,novinar.
{82289}{82323}Zaöto ste ovde?
{82380}{82409}Da me intervjuiöete?
{82432}{82458}Ne.|U stvari da.
{82478}{82510}äta je slatkiöu?
{82523}{82555}Ja nisam novinar, |ja sam glumac.
{82578}{82652}I ûelim da mi pomognete|da pripremim ulogu.
{82682}{82720}Koji karakter?
{82741}{82812}Travestit koji imitira|Saru Montiel, i druge.
{82842}{82905}To sam ja.|äto meni ne daju tu ulogu?
{82925}{82977}Ali ti nisi glumac,|ti si samo peder.
{83039}{83095}Ono öto treba da nauËiö to |je kako biti pristojan.
{83113}{83154}zato öto ovo nije naËin kako|se obhodi sa damom.
{83175}{83210}Izvinjavam se.
{83227}{83262}Dakle, hoÊete li ne poduËiti?
{83289}{83341}A kako Êeö mi platiti|slatkice?
{83374}{83442}To je ono öto traûim.
{83462}{83482}Dva minuta.
{83491}{83516}RazgovaraÊemo kasnije.
{83526}{83554}Sada nastupam.
{83576}{83609}Sve öto Ëinite je|za mene izvanredno.
{83625}{83651}Oduöevljena sam.
{83674}{83700}Vidimo se kasnije.
{84177}{84205}Ortigueira 6 milja.
{84912}{84949}äta ûelite?|Pivo.
{85116}{85187}Izvinite öto pitam, ali|odakle vam taj upaljaË?
{85200}{85229}Niste odavde.|Ukrao sam ga prijatelju.
{85270}{85311}NJegovi ûive ovde.
{85325}{85378}Moûda ga znate.|Zove se Anhel Andrade.
{85403}{85414}Da.
{85426}{85459}To mu je umetniËko ime.|Naravno da ga znam.
{85500}{85534}Znaö ga?|Veoma dobro.
{85550}{85583}OdliËno.
{86255}{86279}Ko je?
{86312}{86385}Enrike.|Ja sam iöao u ökolu sa Ignaciom.
{86408}{86454}Odlazi odavde ili|Êu da zovem policiju.
{86712}{86753}SaËekaj.
{86772}{86801}Ti si Enrike Goded?
{86815}{86834}Da.
{86909}{86944}Ja sam Ignaciova majka.
{86957}{86989}Drago mi je da sam|vas upoznao.
{87002}{87035}Ui.|Hvala.
{87075}{87112}Oprosti mojoj snaji.
{87124}{87194}Ja imam problema sa srcem,|a ona je ona koja se plaöi.
{87213}{87239}Nema veze.
{87262}{87302}Ignacio je puno priËao o tebi.
{87324}{87379}Bili smo dobri prijatelji.|Znam.
{87400}{87477}Poslednji put kada je doöao da|me vidi, pisao ti je pismo.
{87492}{87514}Pismo?
{87526}{87553}Nikada ga nisam primio.
{87567}{87619}To je bilo pre tri godine.
{87638}{87725}Nije znao tvoju adresu pa ga je|poslao na Ministarstvo kulture.
{87757}{87801}Onda me ne izunenauje.
{87827}{87873}Ali dok se vratilo|on je veÊ umro.
{87904}{87953}Hajdemo u trpezariju.
{88094}{88139}To je moj sin Huan.
{88155}{88188}Mlae dete.
{88203}{88227}On je u pozoriötu.
{88239}{88257}Promenio je svoje ime.
{88265}{88310}Kaûe da ima previöe Huana.
{88320}{88361}éeli da ga Ëak |i ja zovem Anhel.
{88385}{88559}Voleo bih da vidim Ignaciovu sobu.
{88578}{88658}Da budem iskrena, on|Ëak i nije imao sobu.
{88675}{88750}Ali kada je dolazio voleo|je da koristi tavan.
{88763}{88809}ûelite da ga vidite?
{88920}{88958}Mi idemo gore.
{89355}{89386}Huan je sve spalio.
{89397}{89440}Rokovnike, odeÊu...
{89457}{89494}Sve osim ovih Ëasopisa.
{89589}{89630}Nije ostali niöta od|onoga öto je Ignjacio pisao?
{89660}{89735}Kakva öteta.
{89762}{89803}Jeste li i vi  izdavaË?
{89823}{89883}Kakav izdavaË?
{89912}{89955}Poöto je Ignjacio umro,
{89970}{90058}doöao je Ëovek koji se bavi| ötampanjem mladih autora.
{90074}{90114}ili barem tako reËe.
{90133}{90203}OËajniËki je ûeleo da se|doËepa Ignjaciovih priËa.
{90226}{90292}SeÊate li se njegovog imena|ili izdavaËke kuÊe?
{90309}{90350}On je bio veo uporan.
{90362}{90424}Pa sam mu rekla da je|huan sve spalio,
{90437}{90486}a on je Ëak traûio |Huanovu adresu.
{90498}{90533}Naravno da sam mu|dala pogreönu.
{90569}{90616}Mislim da je bio|malo lud.
{91098}{91130}Ovo je Ignjacijevo pismo.
{91222}{91244}Nije spaljeno.
{91254}{91292}jer nikada nisam rekla|Huanu da je vraÊeno.
{91369}{91401}Mnogo vam hvala gospoo.
{91421}{91464}Nemojte osuivati Huana.
{91492}{91525}On je dobar sin.
{91564}{91607}ali ga je bratovljeva|smrt baö potresla.
{91637}{91685}On je bio taj oji ga je naöao.
{91995}{92026}Dragi Enrike,
{92041}{92074}Napokon imam vesti o tebi.
{92087}{92117}»itao sam u novinama.
{92127}{92166}Ti, ËoveËe reûiraö|svoj prvi film.
{92184}{92252}Pa i ako je andergraund|znaö da sam filmski fan.
{92301}{92355}BiÊe ti drago da Ëujeö|da joö uvek piöem.
{92371}{92433}Blizu sam priËe koja moûe|biti izvanredan film.
{92449}{92491}Otac Manolo mi je inspiracija.
{92503}{92580}ZvuËi neverovatno, ali sam iöao|do njega u Valensiju.
{92591}{92647}Ja sam majci u poseti|ali ûivim u Valensiji.
{92675}{92736}Raspitao sam se, on|viöe nije sveötenik.
{92748}{92807}Sada se imenuje samo|svojim prezimenom gosp.Bereguer.
{92825}{92903}Radi u izdavaötvu, oûenjen|je i ima sina.
{92925}{92975}Pomislio sam kako Ëezne|da bude ucenjivan.
{92996}{93058}Pa sam napisao "Vizitu", |priËu koju tebi öaljem.
{93079}{93114}Molim te, proËitaj je.
{93138}{93221}Sada sam u ûivotnom periodu|kada mi treba puno novca.
{93230}{93275}i spreman sam da ga|uzmem od te barabe.
{93296}{93346}On mi popriliËno duguje.
{93355}{93397}I vreme je da to plati.
{93450}{93509}Piöi mi i ispriËaÊu ti|ostatak priËe.
{93525}{93591}Jedino öto traûim je|je tvoj odgovor.
{93605}{93657}Jedino sa tobom mogu da|podelim ovu priËu.
{93690}{93722}Volim te.
{93735}{93767}Tvoj Ignacio.
{94129}{94148}Ja Êu.
{94417}{94439}äta ûeliö?
{94478}{94513}Doöao sam da se izvinim.
{94686}{94726}DaÊu ti tvoj öorc.|Ostavio si ga ovde.
{94778}{94804}Hvala.
{94848}{94892}Mnogo mi je ûao za|sve öto sam rekao.
{94913}{94949}Svaku reË povlaËim.
{94969}{95017}Ako si joö zainteresovan,|"Vizita" je tvoja.
{95029}{95077}Radi sa njom öta|god ûeliö.
{95158}{95200}Oslabio si?
{95219}{95270}Da.|Ja zaista na tome radim.
{95280}{95348}OslabiÊu joö.|A i uzimam Ëasove.
{95371}{95447}»asove Ëega?|O tome kako biti kraljica.
{95505}{95564}RAdim sa najboljim.|Imitator Sare Montijel.
{95575}{95619}Ona to izvodi u "Bamboli"|gej klubu.
{95628}{95657}RAdim tamo kao konobar.
{95667}{95715}da bih mogao da prouËavam|kraljicu öto bolje.
{95752}{95800}ZnaËi joö uvek misliö|o Zahari.
{95813}{95838}Da.
{95847}{95887}Samo me pozovi na audiciju.
{95912}{95937}Hvala.
{95984}{96076}Kod tebe je.|Da i to si zaboravio.
{96124}{96185}Ignacio,|voleo bih da porazgovaramo.
{96196}{96242}Dok me ne budeö zvao Anhel|neÊi ti verovati da me ozbiljno shvataö.
{96277}{96338}Anhel, izvini|ti si dobar glumac,
{96375}{96427}sada viöe nego ikada.
{96442}{96487}Dakle, daÊeö mi audiciju?
{96740}{96780}Audicija je trajala|par meseci.
{96812}{96894}dovoljno dugo da sebe bacim|u snimanje "Vizite",
{96908}{96965}kao öto se ona ûena|bacila krokodilima,
{96975}{97035}i grlila ih dok su je|oni proûdirali.
{97454}{97485}Promenio si kraj.
{97519}{97552}Da.
{97566}{97636}"Vizita" ne moûe da se zavröi|hepiendom kao u tvojoj priËi.
{97650}{97666}Zaöto?
{97695}{97748}Zahara ne moûe tek tako|da se iöeta iz ökole.
{97762}{97800}Ona je opasna po sveötenike.
{97819}{97869}A mi znamo na|öta je crkva sve spremna.
{97887}{97938}Ali ovaj kraj je|stvarno teûak.
{97962}{98029}Za tebe kao glumca,|to je mnogo interesantnije.
{98045}{98077}Misliö?|Naravno.
{98159}{98187}Snimao sam "Vizitu" kao|posvetu Ignaciju.
{98196}{98276}U svom pismu je rakao|da bi voleo da je vidi na filmu.
{98288}{98321}A istovremeno sam  |reöavao enigmu Huana.
{98355}{98411}Dozvolio je da ga|Ëesto penetriram,
{98425}{98461}ali samo fiziËki.
{98486}{98573}Bili smo pri kraju snimanja|a njegova tajna je ostala netaknuta.
{98595}{98628}Ali poslednjeg dana,
{98640}{98675}imali smo posetu.
{98698}{98733}Tiöina!
{98771}{98796}I... kamera- ide!
{98846}{98907}"Vizita"|91, 1, prva.
{98936}{98975}Zahara, draga.
{98988}{99002}Akcija!
{99071}{99138}DeËaci su u uËionici|a meni je muka od rasprave.
{99154}{99188}Pusti me napolje.
{99222}{99273}äta je, ûeliö da me kidnapujeö?
{99297}{99323}Otvori vrata!
{99337}{99413}Moram da piöam, da kupim|cigarete, da se ufiksam.
{99430}{99470}»ak i da imam pare,
{99480}{99524}kako da budem siguran da|me neÊeö opet uceniti?
{99550}{99590}Nikada neÊeö biti siguran.
{99603}{99637}To je moja osveta.
{99813}{99866}Pusti me napolje ili Êi da vriötim.
{99879}{99920}Voleo sam Ignacija.
{99938}{100025}Ne moûeö voleti desetogodiönjaka.|Ti si ga maltretirao, obljubio ga.
{100051}{100083}Voleo sam ga.
{100200}{100225}Otvorite, molim vas.
{100238}{100265}ZakljuËan sam ovde.
{100892}{100955}Ona je pretnja|ûeli da nas denuncira.
{100970}{100991}éeli milion pezerta|da bi Êutala.
{101051}{101087}Ako platiö i jednu pezetu|neÊeö prestati da plaÊaö.
{101171}{101216}Znao sam da Êemo se|opet sresti, öljamu.
{101262}{101280}Znaö je?
{101299}{101347}Vi ga znate mnogo|bolje od mene.
{101361}{101394}To je Ignacio Rodrigez.
{101440}{101475}Ignacio.
{101570}{101590}NemoguÊe!
{101625}{101661}Moramo ga dokrajËiti.
{101674}{101719}On je opasan za |celu kongregaciju.
{101784}{101820}éeli neöto da kaûe.
{101838}{101873}Da, da ga oslobodimo.
{102157}{102201}Ako Êete me ubiti,
{102232}{102285}prvo ûelim da se ispovedim.
{102303}{102336}äta da ispovediö?
{102355}{102404}ZahvaljujuÊi tebi, mi nemamo izlaza.
{102660}{102731}Moraö da ostaneö miran.
{102747}{102790}Ja Êu se osloboditi tela.
{102801}{102818}Kako?
{102829}{102875}Najbolje je da niöta ne znaö.
{102890}{102927}Bila je samoodbrana.
{102941}{102989}ZagorËao bi nam  ûivote.
{103000}{103016}Da.
{103043}{103075}Predpostavljam.
{103103}{103150}I nema svedoka.
{103186}{103210}Bog.
{103227}{103248}Da.
{103263}{103295}Ali je on na naöoj strani.
{103519}{103541}Rez.
{103591}{103616}Secite, momci.
{103695}{103749}Ovaj je dobar.|äta je sa ostalima?
{103798}{103825}daj mi prvi.
{103856}{103879}Dobro odraeno.
{103921}{103959}Ne bilo je odliËno.
{104085}{104131}Neöto nije u redu?
{104244}{104293}VideÊemo se kasnije.
{104505}{104550}Stvarno je bilo dobro.
{105673}{105722}Ostavi to.|KO si ti?
{105738}{105772}Nitkov u tvom filmu.
{105796}{105825}OËe Manolo!
{105840}{105869}Gospodin Berenger.
{105952}{106017}Ja Ëak ni sopstvenom sinu|sada nisam otac.
{106127}{106158}Izlazite.
{106178}{106254}ProËitao sam u novinama|da si ovde.
{106348}{106419}Idi i popi vrelo mleko|sa medom i aspirin.
{106431}{106470}i ostavi me na miru.
{106483}{106544}Imam puno da radim, nemam|vremena da ga gubim na tebe.
{106580}{106634}»ak ni da bi saznao|kako je Ignacio umro?
{106726}{106759}Ili, ko ga je ubio?
{106779}{106835}Ili da li je sluËaj|baö kao u tvom filmu.
{106935}{106975}Reci öta imaö|i onda idi.
{107094}{107135}éiveo sam u Valensiji.
{107155}{107230}Radio sam za izdavaË koji|promovira mlade pisce.
{107277}{107342}Pre tri godine sam dobi|priËu pod nazivom "Vizita",
{107381}{107425}potpisanu sa Ignjacio Rodrigez.
{107443}{107507}Ignacio Rodrigez zove|u vezi nove antologije.
{107521}{107563}Jeste li mu rekli da|je odbijen?
{107579}{107628}Da, ali on insistira|da razgovara sa vama.
{107641}{107673}Sada je na liniji.
{107800}{107842}Gospodin Manuel Bereger?|Da.
{107858}{107925}Ja viöe volim -otac Manolo.|Izvinite?
{107936}{107978} Vi ste autor "Vizite"?|Da.
{108009}{108078}OdluËili smo da je ne uvrstimo| u "Kratke priËe 80-tih".
{108096}{108157}éao mi je.|Vi i ja treba da popriËamo.
{108176}{108231}Mislim da ne.|Nemam öta drugo da kaûem.
{108249}{108284}Ali ja imam.
{108304}{108350}Iöao sam u ökolu "St. Dûon".
{108365}{108410}Vi ste mi bili profesor literature,
{108428}{108479}i bili ste ludo|zaljubljeni u mene.
{108502}{108563}SeÊam se kako ste me|grlili od pozadi.
{108576}{108622}dok ste izraûavali svoju ljubav.
{108632}{108676}Ne verujem da ste zaboravili.
{108720}{108766}SeÊam se dugmadi sa|vaöe odore
{108780}{108826}kako mi se zarivaju u kiËmu.
{108858}{108902}Zar ste stvarno zaboravili?
{108936}{109004}OËekujem vas u mojoj|kuÊi u 7 sati.
{109023}{109084}Moja adresa je nazad na|koverti, oËe Manolo.
{109495}{109533}Gurni vrata.
{109546}{109588}Samo su zaglavljena.
{109977}{110040}To nije bio Ignacio kojeg|smo ti i ja voleli.
{110057}{110098}Zdravo gosp. Berenger.
{110109}{110142}Ja sam Ignacio.
{110158}{110198}Molim vas uite.
{110425}{110470}Da, ja sam dûanki.
{110486}{110547}Ali ûelim da ostavim, i|verujem da mi moûete pomoÊi.
{110599}{110627}Pa, znam jednu kliniku.
{110642}{110706}I ja, ali prvo idem|da se popravim malo.
{110721}{110801}Znam da imam divne sise|ali sve ostalo...
{110820}{110856}Uostalom, neÊemo o tome.
{110872}{110934}Lepo izgledati |puno koöta. oËe Manolo.
{110947}{110997}Mislim da bi milion bio dovoljan.
{111030}{111056}Milion?
{111076}{111159}Da, u gotovom, i moje usne|Êe biti neme.NeÊu reÊi ne reË.
{111172}{111205}Ti si poludeo!
{111223}{111281}Seksualno zlostavljanje je|kaûnjivo oËe Manolo.
{111298}{111360}äta Êe da misli vaöa ûena|ili vaö öef?
{111376}{111432}Nisi u poziciji da|bilo koga ucenjujeö.
{111448}{111495}Mogao bih da srediim |da te noÊas uhapse.
{111514}{111544}Dobro.
{111564}{111632}Ti zovi policiju, a ja Êu|tvoju ûenu i medija.
{111661}{111723}Ucena ne moûe da bude|bespomoÊna kao öto si ti.
{111750}{111799}Veruj mi|ja znam öta priËam.
{111892}{111940}Huan, idi u svoju sobu.
{111958}{111999}éelim da gledam TV.
{112014}{112066}Gledaj kasnije|imamo poslovni razgovor.
{112082}{112120}Ne smeta mi ako oastane.
{112143}{112171}éao mi je, ne moûe.
{112186}{112249}On mi je brat,|on me pazi.
{112260}{112289}Ili je to ideja moje majke.
{112302}{112346}Ja sam gospodin Berenger.
{112365}{112406}Milion, i kraj priËe.
{112455}{112493}HoÊeö da ga |zovem Huan.
{112535}{112558}ili Anhel?
{112643}{112690}Ucena je postala|investicija za mene.
{112906}{112986}»esto sam poseÊivao braÊu|pa sam mogao da nastavim da viam Huana.
{113113}{113159}SeÊaö se Don Narcisa,|naciste.
{113177}{113235}Voleo je moje ilustracije.|Pogledaj ovu.
{113290}{113336}Evo joö jedne...|Pogledaj, ova je lepa.
{113351}{113386}Pa ova...
{113411}{113467}Deca äpanije|Doneo sam ti ovo.
{113483}{113539}Drûao sam Ignacija sreÊnim|sa malim svotama novca.
{113581}{113626}I zadrûavao sam ga.
{114014}{114054}éudeo sam za Huanom.
{114080}{114119}svakom danom sve viöe.
{114281}{114310}Zdravo.
{114328}{114360}Doneo si lovu?
{114375}{114413}Mogu ti dati samo 50 000.
{114428}{114465}Rekao si da Êeö|doneti milion.
{114481}{114535}Rekao sam da Êe mi danas|reÊi ako nabavim zajam.
{114560}{114592}Rekli su -da.
{114602}{114648}Ali moraju da provere|moje garante.
{114684}{114729}Potrebne su mi sledeÊe tri nedelje.
{114747}{114777}Joö tri nedelje.
{114796}{114840}Ja sam danki.|Da li si to primetio?
{114855}{114900}Mogu da umrem u sledeÊe tri nedelje.
{114922}{114964}Izlaziö?|OËogledno.
{114999}{115059}éelim da vidim majku|pre nego Ëekiram.
{115074}{115142}Mrzi öto Êe me videti sa ovakvim zubima|i ovakvim licem, a ti si kriv.
{115156}{115211}Ne budi nefer, Ignacio,Radim sve öto mogu.
{115232}{115263}UËini neöto viöe.
{115286}{115326}NeÊe me biti nedelju dana.
{115342}{115379}Kada se budem vratio|ûelim taj milion.
{115395}{115452}ZaûaliÊeö ako ga ne bude bilo.|Dojadilo mi je da me zaobilaze.
{115495}{115538}Ja ih poûurujem, ali...
{115894}{115924}OËe!
{116004}{116032}KreÊemo.
{116074}{116100}Da ti pomognem?
{116121}{116198}Naravno, uzmi Oliveti|oto je najteûe.
{116398}{116452}Kad si veÊ tu, |ponesi i ovo.
{116997}{117034}Zaustavi taxi.
{117192}{117232}∆ao oËe.|Dovienja.
{117249}{117290}Otvorite prtljaûnik.
{117603}{117638}Moja marama.
{117999}{118032}Izvini.
{118046}{118111}Doöao sam po svoju maramu.|Mora da sam je ovde ostavio.
{118444}{118500}Baö je mekana.|Svila.
{118524}{118550}Tvoja je.
{118580}{118630}Da budem iskren, ostavio|sam je radi tebe.
{118672}{118716}Prekini.|Ja nisam Ignacio.
{118739}{118772}SreÊom.
{118826}{118854}Koliko je sati?
{118970}{119018}Da li ti je dao|neöto za mene?
{119028}{119053}Ignacio? Ne.
{119071}{119097}Jebiga.
{119109}{119153}Danas moram da|platim ökolarinu.
{119177}{119194}Ti studiraö?
{119208}{119252}Da. Dramu.
{119263}{119281}Ja sam glumac.
{119293}{119326}SebiËna bitanga.
{119341}{119388}Znao je da danas moram da platim|i nije niöta ostavio.
{119425}{119465}Naravno da sam mu ja|platio ökolarinu.
{119506}{119539}Nisam rekao Ignaciju.
{119569}{119638}ali mi je banka dala|garanciju na zajam od dva miliona.
{119684}{119767}Podigao sam prvi milion.
{119785}{119859}éeni sam rekao da idem na|konferenciju u inostranstvo.
{119910}{119948}Nije mi verovala.
{120068}{120125}Predpostavljam da|te to ne interesuje.
{120238}{120280}Ni najmanje.
{120363}{120405}Kako je Ignacio umro?
{120429}{120474}Huan i ja smo proveli|jednu nedelju sami.
{120490}{120525}najsreÊniju u mom ûivotu.
{120541}{120579}Svakog dana sam |mu donosio po neöto.
{120596}{120652}OdeÊu, vokmen|kameru super 8.
{120672}{120734}Ja sam uûivao u poklonima|viöe nego on.
{120755}{120796}Skini koöulju.
{121356}{121400}Na mene je red.
{121584}{121625}Sada skini ovo.
{121639}{121674}Pokaûi mi svog oku.
{121686}{121733}Ako Êeö da snimaö moj kurac,
{121746}{121776}nemoj da mi se vidi lice.
{121796}{121815}Prekasno.
{121841}{121872}Ne mogu...
{122570}{122608}Ti.|Daj mi neku lovu.
{122621}{122648}PoËinje mi kriza.
{122659}{122711}Kako je mama?|Imala je joö jedan srËani udar.
{122725}{122784}Ali je sada u redu.|Ja sam taj koji je bolestan.
{122986}{123016}Lovu.
{123060}{123107}Viöe.|To je sve öto imam.
{123120}{123181}éelim milion odmah!|Nema viöe izgovora.
{123198}{123264}Nema viöe poza|i nema viöe poklona.
{123313}{123335}Mama.
{123347}{123388}Kako si Huan?|Da li je Ignacio stigao?
{123398}{123409}Da.
{123423}{123455}äta se dogodilo?
{123467}{123502}UobiËajene stvari, sina, ali...
{123513}{123557}Ukrao je moju penziju...
{123574}{123639}Jel to istina?|Jeste ljubavi, jeste
{123697}{123746}Kaûo teti da Êu|joj poslati neke pare.
{123763}{123816}ObeÊao mi je da|Êe otiÊi na kliniku.
{123860}{123886}I ti mu verujeö?
{123907}{123966}Da, ovaj put stvarno ûeli.|PokuöaÊe.
{123986}{124027}Moraö mu pomoÊi.|Kako?
{124047}{124103}Tako öto Êeö biti uz njega.|Ne ostavljaj ga.
{124120}{124150}ObeÊaj mi.
{124164}{124189}ObeÊavam.
{124209}{124250}Sluöaj, da li ti je dao
{124266}{124305}sir i koritos.
{124323}{124339}Veoma ukusno.
{124351}{124384}äto si se maltretirala?
{124399}{124436}Ima hrane u Valensiji.|Ne troöi pare.
{124448}{124494}To ti je omiljeno jelo.|Spremila sam ih za tebe.
{124506}{124550}U Valensiji ih nema.|Dobro, hvala ti.
{124581}{124647}Mnogo te volim.|Dobro, javi ako se neöto dogodi.
{124673}{124700}Ne brini, hoÊu.
{124718}{124733}∆ao.
{124836}{124858}Gde je Ignacio?
{124911}{124929}UbiÊu ga.
{124961}{124992}To je bila Huanova ideja.
{125018}{125046}Ili moja, ne znam.
{125092}{125134}Jedino reöenje je bilo|osloboditi ga se.
{125180}{125228}Manj-viöe|ono öto ste snimili.
{125257}{125291}Ali ne tako nasilno.
{125328}{125372}äta ste mislili o tome?
{125397}{125445}Ignaciova priËa se|tako ne zavröava.
{125498}{125572}Kada sam poËeo da je pripremam|saznao sam da je Ignacio mrtav.
{125652}{125681}Da li vam je Huan to rekao?
{125711}{125776}Sam sam saznao.
{125823}{125884}HoÊete li mi samo|raÊi kako se to dogodilo?
{125907}{125982}Dogovorio sam se da se ssa Huanom|vidim u muzeju "Gigantske  figure".
{126003}{126050}On je sve isplanirao.
{126064}{126119}Mnogo viöe nego|öto sam ja mislio.
{126213}{126254}Ja Êu kupiti drogu|a ti Êeö mu je dati.
{126284}{126300}Zaöto ja?
{126331}{126372}Jebote, on mi je brat.
{126394}{126425}Ja nisam monstrum.
{126457}{126499}Misliö da mi|nije teöko?
{126561}{126601}Ali on uniötava sve naöe ûivote.
{126654}{126678}A öta Êemo posle?
{126709}{126745}NeÊemo se sastajati neko vreme.
{126776}{126793}Zaöto?
{126822}{126867}Rekao si da neÊe|biti nikakve istrage.
{126882}{126915}Za svaki sluËaj.
{126929}{126983}Najboilje da ne |budimo nikakve sumnje.
{127004}{127075}Ja Êu otiÊi da se naem majci|biÊu joj potreban.
{127093}{127159}Kada se sve smiri zvaÊu|te i onda Êemo nastaviti.
{127177}{127214}Imaö li para?|Da.
{127272}{127303}äta da radim|dok te Ëekam?
{127326}{127393}RAdi, zarauj pare.|TrebaÊe nam.
{127420}{127459}Situacij u kuÊi mi|je nepodnoöljiva.
{127476}{127527}Izvini se ûeni|i uûivaj u sinu.
{127556}{127596}Reci joj istinu.|äta?
{127611}{127671}Kaûi da si bio sa|nekim drugim.
{127692}{127723}sa ûenom.
{127743}{127777}Daj mi adresu tvoje majke.
{127797}{127839}Najbelje da je nemaö.
{127868}{127925}Tako neÊeö biti u iskuöenju|da doeö i vidiö me.
{127972}{128003}A Ëemu se oni smeju?
{128078}{128104}Smeju se nama.
{128205}{128231}Meni, naposletku.
{128273}{128317}Huan je kupio smrtonosno Ëist heroin.
{128338}{128379}Dao ga je meni.
{128396}{128429}A ja sam otiöao kod Ignacija.
{128464}{128475}Sam.
{128650}{128697}Dragi Enrike
{128791}{128840}Mislim da sam uspeo
{129075}{129114}Ovo mi je poslednji fiks.
{129130}{129158}Kako to misliö?
{129178}{129201}Ostavljam.
{129232}{129275}Ovaj put to stvarno mislim.
{129298}{129361}Predhodno Êu srediti|lice i onda sve ostalo.
{129383}{129441}Rezervisao sam kliniku|za detoksikaciju.
{129460}{129484}VeÊ sam primljen.
{129490}{129516}Dobro je.
{129538}{129572}ImaÊeö novac sutra.
{129590}{129613}Nadam se.
{129644}{129673}Pre podneva. Ok?
{129686}{129731}Za svaki sluËaj, |Napisao sam dva pisma.
{129747}{129792}Jedno za izdavaËa, a |drugo za tvoju ûenu.
{129805}{129874}i ispriËao öta si skrivao od njih|u proölosti i u sadaönjosti.
{129940}{130008}To nije neophodno.Dajmi ih.|kada dobijem novac.
{130041}{130075}Pre podneva.
{130397}{130434}Lepe su, zar ne?
{130449}{130467}äta?
{130481}{130505}Moje sise.
{130559}{130596}Da, divne su.
{130615}{130636}Hvala.
{130848}{130878}Da ti pomognem?
{130939}{130964}Idi.
{130991}{131035}Ne ûelim da se fiksam|pred tobom.
{132544}{132577}UËinjeno.
{132725}{132751}Stani ovde.
{132766}{132800}IÊiÊemo u bioskop|da ubijemo vreme.
{132819}{132856}"Nedelja crnog talasa".
{133308}{133364}Kao da svi filmovi|priËaju o nama.
{133491}{133511}äta sada?
{133552}{133581}Ja idem kuÊi.
{133603}{133667}HoÊeö da poem sa tobom?|Bolje ne.
{133720}{133770}Ne zaboravi da uzmeö|ona dva pisma.
{133790}{133850}Ako ih ne uzmeö|imaÊemo problema.
{133877}{133934}Sve Êu pokupiti|ne brini.
{134139}{134288}Ako se neÊemo viati|neko vreme,daj mi neöto sa Super8-ce.
{134348}{134408}TeöiÊe me da nas gledam|kako se tucamo.
{134425}{134451}Jesi li ti lud!
{134465}{134504}äta ako to vidi tvoja ûena?
{134522}{134595}Moramo ih spaliti.|Ja Êu se za to pobrinuti.
{134640}{134667}Poimo.
{134911}{134950}UÊi na Ëas.
{134978}{135014}Ne, uzeÊu taksi.
{135068}{135093}Onda,
{135142}{135184}neÊu te opet videti...
{135201}{135239}To je samo na par dana.
{135521}{135565}Zovi me Ëim budeö mogao.
{135575}{135590}Da.
{137267}{137305}äta je bilo?
{137375}{137424}Napokon.
{137442}{137500}ProËitao sam u ovom Ëasopisu|da si ovde.
{137520}{137546}äta si mu rekao?
{137561}{137584}Sve.
{137620}{137691}Sada samo mene imaö dragi moj.|Ti si lud.
{137710}{137781}Ne zaboravi da imam|bratovljeva pisma.
{137794}{137823}koja te optuûuju za njegovu smrt.
{137836}{137900}To smo oboje uradili ljubavi.|U pismima se spominjeö samo ti.
{138382}{138434}Jesi li dobro?|Ostavi me na miru!
{138475}{138566}Ako te opet budem video|kunem se, ubiÊu te.
{138575}{138621}Sada kada sam te naöao|neÊu te pustiti.
{138640}{138674}Navikni se na tu ideju.
{138817}{138859}Monika.
{138879}{138926}Moûeö li da me odbaciö?|Naravno.
{138956}{138996}Idi napred.
{139044}{139123}Ko je to?|Neko ko traûi Enrikea.
{139706}{139733}Ko je?
{139747}{139769}Ja sam.
{140209}{140254}Vrati mi kljuË.
{140354}{140428}Tvooje stvari su u holu.|Odnesi ih.
{140760}{140800}Taksi je otiöao.
{140816}{140885}Moraö mi ili pozajmiti kola|ili me odvesti do Madrida.
{141151}{141206}éelim da poöaljete taksi.
{141320}{141365}Enrike Goded, da.
{141409}{141444}Hvala.
{141515}{141569}Hteo sam da ti sve kaûem|posle snimanja.
{141592}{141625}äta da mi kaûeö?
{141648}{141675}Da se zovem Huan.
{141700}{141770}Da sam Ignaciov brat|i da je Ignacio umro pre par godina.
{141805}{141835}To veÊ znam.
{141851}{141884}Znam da znaö.
{141905}{141931}Kako to misliö?
{141968}{142036}Majka me je zvala da mi|kaûe da si bio u kuÊi.
{142061}{142111}Predpostavio sam da|si sve shvatio.
{142128}{142186}Kada si traûio audiciju|znao si da znam?
{142198}{142211}Da.
{142225}{142266}I dalje si se pretvarao?
{142283}{142315}A öta sam drugo mogao?
{142331}{142372}Nisam lagao|sve si znao.
{142383}{142428}Ne, ni deliÊ svega.
{142443}{142507}Znam da si zauzeo Ignaciovo mesto|i da on  umro.
{142520}{142575}Ali nisam mogao zamisliti|da si ga ti ubio!
{142598}{142609}Evo ti ga taksi.
{142621}{142684}Nisam ga ja ubio, nego Berenger!|Ignacio ga je ucenjivao.
{142697}{142742}Ali si ga ti navukao.
{142755}{142777}Taksi Ëeka.
{142848}{142892}Ti nemaö pojma kako je imati|takvog brata.
{142914}{142951}i ûiveti u malom gradu.
{142984}{143003}Huan,
{143042}{143063}taksi Ëeka.
{143719}{143750}Zaöto si mene izabrao?
{143789}{143814}I dalje me ne vidiö |kao Zaharu.
{143859}{143894}samo zato da bi me potucao?
{143920}{143958}To je bila znatiûelja.
{143974}{144022}äteo sam da vidim|koliko daleko moûeö da ideö
{144042}{144085}i koliko ja mogu da podnesem.
{144125}{144163}Mogu ja joö dalje.
{144186}{144218}Kladim se da moûeö.
{144363}{144396}Ne moraö dalje da objaönjavaö.
{144409}{144467}Ovo nije moje.|od Ignacija je.
{144931}{145015}Dragi Enrike|Mislim da sam uspeo...
{145241}{145291}Posle realizacije "Vizite"
{145306}{145353}Anhel Andrade je poastao|glavni srcolomac.
{145372}{145410}Njegova vladavina traje 10 godina
{145424}{145480}Tokom devedessetih njegova |pati od stalnih padova i uspona.
{145496}{145548}Oûenio je Moniku|kostimografkinju.
{145572}{145601}Trenutno radi u |jednoj TV seriji.
{145616}{145653}Gdin Berenger| (bivöi otac Manolo)
{145667}{145723}Nije nestao iz ûivota|Anhela Andfradea (Huana)
{145734}{145783}POËeo je da traûi novac|i da ga ucenjuje.
{145796}{145846}Jedne noÊi su ga |usmrtila kola koja se nisu zaustavila.
{145857}{145916}Kola je vozio Anhel Andrade.
{146017}{146116}Enrike Goded sa istom straöÊu|i dalje snima filmove.
{146141}{147641}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/7xy5u|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
