{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{3048}{3131}prevod: memara
{5127}{5195}Tako si lepa.
{5316}{5382}Sad smo iste temperature.
{5863}{5997}Bela... Znaö da si sada|snaûnija od mene.
{6202}{6266}Sada ti moraö paziti|da ne slomijeö mene.
{6303}{6373}Volim te.|-I ja tebe.
{6648}{6740}Renesme?|-Neverovatna je.
{6761}{6818}Gde je? éelim da je vidim.|-»ekaj malo.
{6860}{6924}Prvo moraö nauËiti da kontroliöeö ûe.
{6998}{7054}Moraö u lov.
{8128}{8177}Zatvori oËi.
{8278}{8334}äta Ëujeö?
{9579}{9625}Bela, nemoj.
{10061}{10107}Bela, stani!
{10135}{10220}Izvini, nisam znao da Êe biti|ljudi ovako daleko od puta.
{10324}{10410}Moram da odem odavde.|-Mogu ti pomoÊi.
{10565}{10606}Ili ne.
{11228}{11329}Zadivljen sam. Odolela si|ljudskoj krvi u sred lova.
{11338}{11398}Mnogi stariji vampiri to ne mogu.
{11557}{11617}Joö uvek si ovde.|-I ti.
{11652}{11759}Nisam oËekivao da Êeö|biti toliko... Ti!
{11804}{11865}Osim tih jezivih oËiju!
{11867}{11941}Drûala bih se na odstojanju, za sad.
{11944}{12018}Sigurnije je za bebu, ako se|prvo sretneö sa mnom.
{12029}{12091}Od kad je tebe briga za Renesme?
{12190}{12282}Dobro. Hajde, udahni.
{12579}{12649}Sad razumem o Ëemu su svi priËali.
{12674}{12718}Dûejk, zaista smrdiö.
{12829}{12948}Druötvo... Izgledate dobro zajedno.
{13056}{13136}HoÊeö li da ueö i upoznaö kÊerku?
{13401}{13465}Dobro doöla u porodicu.
{13499}{13589}Bela, izgledaö predivno.|-Neko Ëeka da te upozna.
{13649}{13696}Rouz.
{14484}{14545}Prelepa si.
{14638}{14734}äta je to bilo?|-Pokazala ti je kako te pamti.
{14789}{14848}Pokazala mi- kako?
{14876}{14978}Kako ja Ëitam misli?|Kako Alis vidi buduÊnost?
{15046}{15110}Ima dar.
{15159}{15248}Bili smo u lovu dva dana?|-Njen rast je ubrzan.
{15287}{15363}Dobro. Dosta je|eksperimentisanja za jedan dan.
{15389}{15473}Dûejkobe, ide joj odliËno.|-Hajde da ne preterujemo.
{15516}{15612}Koji je tvoj problem?|-Reci joj.
{15634}{15690}Ovo Êe biti zanimljivo.|-SaËekaj malo.
{15826}{15956}Bela... Vidi... To je vuËija stvar.|-äta je vuËija stvar?
{16073}{16179}Znaö da nemamo kontrolu nad tim.|Niti moûemo da biramo ko Êe biti.
{16191}{16262}To ne znaËi ono öto ti misliö.|ObeÊavam ti.
{16272}{16331}Odnesite Renesme u drugu sobu.
{16337}{16412}Edvarde, ne diraj me sada.|Ne ûelim da te povredim.
{16585}{16659}Imao si utiskivanje na moju kÊerku?|-To nije bio moj izbor.
{16667}{16713}Ona je beba.|-Nije kao öto misliö.
{16721}{16777}Misliö da bi me Edvard|ostavio u ûivotu da je tako.
{16780}{16839}Joö se dvoumim.|-Drûala sam je jednom.
{16850}{16963}Samo jednom, a ti misliö|da imaö neko vuËije pravo na nju.
{16989}{17033}Ona je moja!
{17189}{17242}Lija, sve je u redu.
{17256}{17323}KloniÊeö je se.|-Znaö da ne mogu.
{17391}{17457}Edvarde, zaustavi je.|-Sve je u redu.
{17467}{17520}Neverovatna je, zar ne?
{17579}{17654}SeÊaö li se koliko si ûelela da|budeö uz mene pre tri dana?
{17662}{17708}To je nestalo, zar ne?|-Davno.
{17717}{17816}Zato öto je to bila ona. Od poËetka|je Nesi bila ta koja me ûelela.
{17830}{17938}Nesi?! Dao si mojoj kÊerki|nadimak po Ëudoviötu iz Loh Nesa?!
{18128}{18186}Sete, jesi li dobro?
{18231}{18347}Sete, izvini.|-BiÊe on u redu.
{18493}{18658}Znaö me bolje nego iko.|Sve öto ûelim za Nes... Renesme,
{18684}{18817}to je da bude sigurna, sreÊna.|Vidi, nikad niöta nije imalo smisla.
{18846}{18942}Ti, ja, niti bilo öta od ovog.|Sada i razumem zaöto.
{18971}{19040}Ovo je bio razlog.
{19607}{19672}KonaËno.
{19810}{19877}Sad sam ja na redu.
{20024}{20093}Gde spava?|-U mojoj sobi.
{20101}{20159}Gde Edvard moûe da je vidi.
{20311}{20394}SreÊan roendan.|-Prestala sam da starim pre tri dana.
{20409}{20495}Svejedno ga slavimo. Izdrûi!
{20634}{20702}I dalje mrzim iznenaenja.|To se nije promenilo.
{20714}{20761}Ovo Êeö voleti.
{20842}{20895}Dobro doöla kuÊi.
{20912}{20979}Mislili smo da Êete ûeleti|sopstvenu kuÊu.
{21020}{21095}äta misliö?|-Da je savröena.
{21139}{21201}Uite unutra.
{21395}{21443}Zabavite se.
{22061}{22138}Ovo je Renesmina soba.
{22368}{22416}Ormar.
{22483}{22543}Alis ga je napunila za tebe.|-OËigledno.
{22925}{22990}Ovo je naöa soba.
{23139}{23231}Vampiri ne spavaju.|-Nije namenjeno za spavanje.
{25216}{25289}Zaista si se suzdrûavao ranije.
{25351}{25430}Ovog se nikad neÊu zasititi.|Ne umaramo se.
{25464}{25537}Ne treba nam odmor, niti pauza.
{25568}{25645}HoÊu reÊi... Kako Êemo stati?
{25728}{25823}Rozali i Emet su bili toliko loöi,|da je trebalo puno napora biti
{25833}{25921}blizu njih u krugu od 5 kilometara.
{25971}{26058}Mislim da bi mogli biti i gori.|-Dosta gori.
{26481}{26554}VeÊ ste zavröili?!|-Gde je Renesme?
{26579}{26647}Plavuöa je ukrala.
{26680}{26771}Jeste li mnogo razbijali?|-Emete, nemoj.
{27117}{27195}Je li to »arli?|-Zove dva puta dnevno.
{27240}{27292}PriliËno je loöe.
{27335}{27426}Na posletku Êemo mu morati|reÊi da nisi preûivela.
{27440}{27503}Mora da odboluje./preûali.
{27574}{27661}Dobro. UradiÊemo to sutra.
{27704}{27792}NedostajaÊe mi ovo mesto.|-VratiÊemo se, kao i uvek.
{27860}{27914}»ekajte.
{27930}{27999}Niko nije spominjao odlazak.|-Kada ljudi budu uvereni
{28006}{28076}da je Bela mrtva, ne moûemo|rizikovati da je neko vidi.
{28088}{28179}Samo Êete nestati?!|-Dûejkobe, nemamo izbora.
{29155}{29213}Jesi li Ëuo iöta?
{29251}{29359}»arli, Bela je...
{29490}{29593}Gotovo je?!|-Ne, dobro je. Kod kuÊe je i...
{29611}{29753}Bolje joj je.|-äto ne kaûeö. To je odliËno.
{29850}{29946}»ekaj, prvo treba neöto da vidiö.|-Moram da vidim Belu.
{29985}{30158}Da bi Beli bilo bolje, morala je...|Da se promeni.
{30219}{30287}Kako misliö da se promeni?
{30386}{30461}Idemo na sve ili niöta.|-Do avola, öta to radiö?
{30494}{30563}Ne ûiviö u svetu kakvim ga ti vidiö.
{30635}{30683}Obuci se.
{30705}{30804}Ovo Êe moûda delovati Ëudno,|veoma Ëudno, ali...
{30864}{30938}»udnije stvari se deöavaju|svaki dan. Veruj mi.
{31305}{31412}Reöio sam problem. Otiöli biste.|äta ste oËekivali da ja radim?
{31423}{31517}Ne znaö u kakvu si ga opasnost doveo.|Volturijevi Êe ubiti svakoga ko zna.
{31526}{31608}Nisam mu rekao za vas, veÊ za mene.|Samo sam rekao da si drugaËija.
{31619}{31715}I da smo usvojili moju neÊakinju.|-On to neÊe tek tako prihvatiti.
{31735}{31801}Jesi li razmiöljao o fiziËkom bolu|koji Êeö prirediti Beli?
{31809}{31898}To je kao da joj guraö uûarenu cev|niz grlo. I to ukoliko uspe
{31911}{31975}da kontroliöe svoju ûe.|-»arli je prolazio kroz pakao
{31984}{32039}i znam da Êe biti mnogo sreÊnija|ako i on bude u tvom ûivotu.
{32048}{32115}Ne pretvaraj se da si mislio|i o kome drugom osim o sebi.
{32139}{32209}éao mi je öto tako misliö,|jer Êe biti ovde za 10 minuta.
{32232}{32259}Molim?
{32269}{32322}Na poËetku Êe te malo iritirati.
{32360}{32459}Glavno je da se ne kreÊeö prebrzo.|-Pokuöaj da sedneö i prekrstiö noge.
{32684}{32793}Moûda malo sporije.|-I trepÊi bar tri puta u minuti.
{32874}{32924}OdliËno.
{32940}{33029}Za lik iz crtaÊa.|-Zadrûi dah. Pomaûe kod ûei.
{33056}{33134}Ne zaboravi da pomeraö ramena.|IzgledaÊe kao da diöeö.
{33207}{33287}I nemoj sedeti tako ispravljeno.|Ljudi to ne rade.
{33389}{33469}Dobro. Shvatila sam.|Kretanje, treptanje, disanje.
{33850}{33907}Sretno.
{34194}{34253}Zdravo, »arli.
{34313}{34370}Gde je Bela?
{35053}{35111}Bela?|-Zdravo, tata.
{35201}{35278}Jesi li dobro?|-Nikad bolje.
{35335}{35400}Najgore je proölo.
{35488}{35561}Ti se ne pretvaraö u ûivotinju?
{35642}{35727}Volela bi da je tako dobra.
{35789}{35855}OstaviÊemo vas nasamo.
{36183}{36330}Dûejk je rekao da je ovo...|Bilo neophodno. äta to znaËi?
{36395}{36472}Mislim da bi bilo bolje...|-éelim znati öta ti se desilo.
{36481}{36574}Ne mogu ti reÊi.|-Mislim da zasluûujem objaönjenje.
{36584}{36687}Zasluûujeö. Ali, ako ti ga dam|ne mogu ostati ovde.
{36706}{36808}Ma daj! Ne! Nema viöe odlazaka.|-Tata, moraö mi verovati
{36817}{36918}da koji god razlog bio, dobro sam.
{36946}{37042}Moûeö li ûiveti sa tim?|-Mogu li ûiveti sa tim?
{37091}{37190}Ne znam, Bela. Upravo sam gledao|dete koje znam ceo ûivot
{37200}{37301}kako se pretvara u veoma velikog psa.|moju kÊerku koja izgleda kao moja
{37340}{37396}ali nije.
{37451}{37538}Moûeö li mi verovati da Êu ti reÊi|sve öto treba da znaö.
{37606}{37717}A ovo ne treba da znam?|-Ne, zaista ne trebaö.
{37941}{38038}Ne ûelim da te opet izgubim.|Ne mogu.
{38099}{38204}Onda ni neÊeö. ObeÊavam.
{38627}{38734}Nedostajala si mi. Mnogo.
{38793}{38857}I ti meni.
{39033}{39085}Ovo je Renesme.
{39188}{39242}Tvoja neÊakinja?
{39271}{39331}KÊerka.
{39401}{39477}Tako je. Usvojili ste je.
{39619}{39759}Rene-esme. Ima tvoje oËi, Bela.
{39970}{40043}Pretpostavljam da ne treba da znam.
{40382}{40422}Veoma dobro, Bela.
{40432}{40490}Nikad nisam video novoroenog|da se toliko suzdrûava.
{40501}{40594}Nisam siguran da je ona|novoroeni. Tako je pitoma.
{40631}{40708}Ne bih je sada izazivao.|Ipak je najjaËi vampir u kuÊi.
{40733}{40786}Ma, daj, molim te.
{40918}{40976}Emete, nemoj da se povrediö.
{41037}{41197}Dobro, idemo na tri. Jedan, dva, tri.
{41595}{41656}Jesi li video?
{41780}{41838}Hvala vam.
{42369}{42440}Vreme da budem Ëovek je zavröeno.
{42459}{42526}Ali, nikad se nisam oseÊala ûivljom.
{42550}{42607}Roena sam da budem vampir.
{42963}{43027}Sve dolazi na svoje mesto.
{43090}{43211}»ak su i Volturijevi prihvatili moj|status. Edvard se konaËno dokazao.
{43300}{43377}Izgleda da nam je ostao|samo jedan neprijatelj. Vreme.
{43441}{43502}Renesme raste previöe brzo.
{43596}{43669}Svi smo zabrinuti|koliko Êe biti sa nama.
{43672}{43740}To svaki trenutak Ëini dragocenijim.
{43746}{43819}Vidi, pahuljica.|-Prelepa je.
{43840}{43907}Zaöto ne bi uhvatila joö jednu?
{43979}{44048}Edvard misli da Êemo naÊi|odgovor u Brazilu.
{44076}{44140}Tamo ûivi jedno pleme,|koje moûda neöto zna.
{44521}{44574}Ko je to?
{44588}{44659}Mislim da je naöa roaka iz Denalija.
{44745}{44805}Irina.
{45313}{45380}Tanja je ubedila Irinu|da doe i pomiri se sa nama.
{45389}{45437}Izgleda da se predomislila.|-To öto je videla Dûejkoba je
{45446}{45498}verovatno bilo previöe za nju.|-Volela bih da sam mogla
{45508}{45575}da razgovaram sa njom.|-Ona je deo porodice. VratiÊe se.
{47260}{47336}Kako divno iznenaenje.
{47371}{47426}äta ûeliö?
{47555}{47681}Moram da prijavim zloËin.|Kalenovi...
{47745}{47822}Uradili su neöto uûasno.
{47872}{47934}Dozvoli mi, draga moja.
{48378}{48437}Boûe moj.
{49193}{49247}Alis, öta je bilo?|-Volturijevi.
{49312}{49477}Dolaze po nas. Aro, Kaius, Markus,|straûari i Irina.
{49502}{49581}Draga, doi ovamo.|-Zaöto?
{49601}{49665}äta je Irina videla u öumi?|-äetali smo.
{49686}{49753}Nes je hvatala pahuljice.
{49822}{49963}Naravno. Irina misli da je|Renesme bila ljudsko dete.
{50057}{50199}Ljudska deca su divna. OËaravajuÊa.|Samo biti pored njih znaËi voleti ih.
{50209}{50272}Ali, njihov razvoj se zaustavlja|u vremenu kom se pretvoreni.
{50286}{50349}Ne moûete ih niËem nauËiti|niti obuzdati.
{50369}{50433}Jedan dvogodiönjak moûe|da uniöti celo selo.
{50604}{50697}Ljudi su Ëuli za ova uniötavanja.|PriËe su se öirile.
{50723}{50788}Volturijevi su bili|prinueni da se umeöaju.
{50881}{50974}Poöto deca nisu mogla da Ëuvaju|naöu tajnu morali su ih uniötiti.
{51216}{51271}NE!
{51332}{51415}Tvorci su bili veoma privrûeni|i pokuöavali su ih zaötititi.
{51499}{51593}Mnogi koveni su se raspali.|Bezbroj ljudi je bilo poklano.
{51670}{51758}Tradicije, prijatelji|i porodice izgubljeni.
{51810}{51873}Mama... Ne! Majko!
{51987}{52062}Denalijina majka je|napravila dete vampira?
{52075}{52146}Jeste. A ona je platila cenu.
{52697}{52795}Renesme nije kao ta deca.|Roena je, a ne ugriûena.
{52806}{52889}Raste svaki dan.|-Moûete li to objasniti Volturijevima?
{52899}{52976}Aro ima dovoljno dokaza.|»uo sam njegove misli.
{53062}{53147}Onda Êemo se boriti.|-Njihovo oruûje je previöe moÊno.
{53158}{53244}Niko se ne moûe odupreti Dûejn.|-Aleks je joö gori.
{53255}{53342}Onda ih moûemo uveriti.|-Dolaze da nas ubiju, ne da priËaju.
{53361}{53490}U pravu ste, neÊe nas sluöati.|Ali, moûda ih drugi mogu uveriti.
{53504}{53557}Imamo prijatelje öirom sveta.
{53567}{53638}NeÊu traûiti od njih da se bore.|-Ne da se bore. Da svedoËe.
{53647}{53728}Ako dosta ljudi zna istinu moûda|nateramo Volturijeve da sasluöaju.
{53752}{53815}To moûemo zamoliti prijatelje.
{54124}{54221}Barem opet idemo u London.|Odavno nismo bili tamo.
{54241}{54320}Dobro. Krenimo.
{54426}{54477}Alis me zamolila da vam ovo dam.
{54485}{54560}Ona i Dûasper su sinoÊ preöli|preko naöe zemlje i otiöli u okean.
{54584}{54664}Karlajle?|-Ostavili su nas.
{54694}{54788}Zaöto?|-Nije rekla.
{54838}{54902}Mogu li da vidim?
{55031}{55118}"Skupite koliko god moûete svedoka|pre nego sneg prestane da pada.
{55127}{55166}Tada Êemo mi doÊi."
{55181}{55237}"Trgovac iz Venecije" V. äekspir
{55247}{55310}Aleksine instrukcije su bile jasne,|ali pitanja su i dalje bila tu:
{55329}{55403}Zaöto bi ona i Dûasper otiöli|u trenutku kad su nam najpotrebniji?
{55418}{55461}äta su znali?
{55512}{55606}Potraga za svedocima je zapoËela|odlaskom na sever, do prvih roaka.
{56442}{56539}Edvarde, da li je sve u redu?|Zaöto nam nisi javio da dolaziö?
{56592}{56657}Da li je Irina u pitanju?|Nismo se Ëuli sa njom.
{56666}{56728}Ne direktno.|-Zaöto tvoja ûena Ëeka u autu?
{56738}{56806}Zaöto si doveo vuka?|Mogu ga namirisati odavde?
{56809}{56904}Porodica mi je u opasnosti i|potrebna mi je pomoÊ. -äta se desilo?
{56917}{56990}Teöko je objasniti, ali je potrebno|da budete otvoreni za sve. Moûete li?
{56998}{57046}Naravno.
{57152}{57229}Dobro. Vreme je da|upoznaö neke ljude.
{57239}{57301}äta ako im se ne dopadnem?|-VoleÊe te.
{57311}{57363}HoÊe, kada te budu razumeli.
{57372}{57444}Samo öto nikad nisu videli|nikoga kao öto si ti.
{57797}{57873}Volturijevi Êe doÊi po sve nas.|-Sklanjaj to odavde.
{57882}{57933}Ona nije ono öto vidite.|-To je zloËin.
{58192}{58233}Ostani gde si.
{58243}{58331}Njenim venama teËe krv.|Moûete osetiti njenu toplotu.
{58340}{58399}Mogu da osetim.|-Ja sam joj bioloöki otac.
{58413}{58463}Bela joj je majka.|-To je nemoguÊe.
{58472}{58531}Istina je. Roena je|dok sam joö bila Ëovek.
{58540}{58601}Nikad nisam Ëuo tako neöto.|-Moûe vam pokazati ako joj dozvolite.
{58708}{58795}Tanja, dugujeö nam toliko.|Svima nam preti smrt
{58806}{58872}zato öto nam tvoja sestra|nije dozvolila da joj objasnimo.
{59039}{59136}Ne plaöi se. Ona tako komunicira.
{59500}{59565}Istina je.
{59588}{59649}Nije dete vampir.
{59723}{59802}Znala sam da Êe se i ostatak|porodice susresti sa istim strahom.
{59840}{59892}Strahom od nepoznatog.
{59930}{59994}Strahom od Volturijevih.
{60129}{60222}Amine, molim te.|-Ne mogu ti pomoÊi.
{60237}{60317}Ne bih ni pitao da nije hitno.|-Moraö da ideö.
{60594}{60722}Ja bih voleo da Ëujem o tome. Nemam|priliku upoznati njegove prijatelje.
{60733}{60807}Voli da me krije.|-Ne znam samo zaöto.
{61155}{61219}Karlajl|-Bendûamin.
{61827}{61967}Bendûamin upravlja elementima.|-»ula sam da imam super samokontrolu.
{62539}{62642}Ko su one?|-Ksena i Zafrina. Amazonke.
{62912}{63028}Njihov dolazak znaËio je da se naö|apel Ëuo i u najudaljenijim krajevima.
{63038}{63095}Dok su drugi traûili|svedoke bliûe kuÊi.
{63210}{63270}Patriota kog je Karlajl davno|upoznao na bojnom polju,
{63281}{63333}verovatno Êe postati|neobiËan saveznik.
{63382}{63445}ZaËepi.
{63492}{63622}Mrzeo sam prvu britansku invaziju.|Drugu sam mrzeo joö viöe.
{63645}{63725}»ak i Bitlse?! Zaista, Geri?
{63756}{63830}Starih navika se teöko osloboditi.|-Karlajl te treba.
{64002}{64119}Samo prvo da zavröim svoj obrok.|-U pomoÊ.
{64304}{64378}»im bi neko od njih doöao,|morao je sam da vidi.
{64559}{64650}Karlajl je ubedio prijatelje|iz Irske da dou u Forks.
{64684}{64790}Iako smo im bili zahvalni njihova ûe|za ljudskom krvi je komplikovala sve.
{64919}{65001}Nomadi Randal i Zen|bili su joö nepredvidljiviji.
{65039}{65123}Posebno Piter. Borio se sa|Dûasperom kao novoroeni.
{65179}{65271}Mnogo je crvenih oËiju ovde.|-Sloûili su se da ne love u okolini.
{65346}{65419}Moraju negde da se hrane.
{65442}{65530}äto je viöe vampira dolazilo|viöe je Kvilita imalo preobraûaj.
{65547}{65624}Njihova priroda ih je terala|da se pridruûe Ëoporu.
{65666}{65779}Polako. Sve je u redu. BiÊeö u redu.
{65882}{65961}Napokon su se Karlaj i Esme vratili|sa poslednjim svedokom.
{66019}{66102}Koliko ih je doölo?|-18. Imaö dobre prijatelje.
{66131}{66174}A Alis?
{66209}{66308}Sada smo svi na Arovoj listi.|Centurion je krenuo. Zato si me doveo.
{66337}{66426}Baö si pravi prijatelj, Karlajle.|-Aliastere, doi da upoznaö druge.
{66437}{66516}VeÊ sam ti rekao da ako doe do borbe|neÊu se suprostaviti Volturijevim.
{66526}{66608}NeÊe doÊi do borbe.|-BiÊu na tavanu.
{66837}{66896}Nije druûeljubiv.
{66926}{67046}Osamnaest vampira je ûivelo u naöoj|kuÊi. Mnogi od njih su bili daroviti.
{67082}{67142}Zufrina je imala dar da vlada umom.
{67157}{67223}Mogla je svakoga da natera|da vidi ono öto ona ûeli.
{67820}{67899}Da mi sad ne drûiö ruku|zakleo bih se da je to stvarnost.
{67918}{67981}Ne vidim niöta.
{68016}{68093}Nisi mi rekao da ti je ûena ätit.
{68155}{68247}äta je ätit?|-Jedini kog sam sreo je drugaËiji.
{68267}{68322}To je dar za odbranu.
{68334}{68413}Zato ti ni ranije nisam mogao|Ëitati misli. Ni Aro nije mogao.
{68424}{68511}To je veoma moÊan dar.|-Da, ona je ätit.
{68540}{68589}Ovo je trebalo da te obori na zemlju.
{68600}{68692}Tvoja voltaûa je precenjena.|-Moûda pali samo na slabima.
{68786}{68843}Ja ne bih...
{68971}{69054}Ti si neverovatna ûena.
{69109}{69221}Druötvo, vi moûete napraviti pravi|haos. Zato se morate kontrolisati.
{69263}{69349}Majke vam ne smeju videti preobraûaj.|Ne ûelite da joj otkinete glavu.
{69580}{69656}Ko god da dolazi, nije pozvan.
{70884}{70977}Vladimire. Stefane.|Daleko ste od kuÊe.
{70999}{71039}äta oni rade ovde?
{71048}{71142}»uli smo da Volturijevi kreÊu|na vas, ali da niste sami.
{71153}{71244}Nismo uradili ono za öta nas optuûuju.|-Baö nas briga öta ste uradili.
{71259}{71387}»ekali smo ceo milenijum da neko|izazove to italijansko smeÊe.
{71428}{71502}Ne planiramo da se bijemo sa njima.|-äteta.
{71518}{71629}Arovi svedoci Êe biti razoËarani.|-Oni uûivaju u dobroj borbi.
{71692}{71734}Arovi svedoci?
{71745}{71831}A ta osoba bi uvek imala dar.|I on bi je naËinio Straûarom.
{71843}{71916}Ovo je sve zbog Alis.|Nema nikog kao öto je ona.
{71924}{71975}Zato je i otiöla.|-äta Êe mu svedoci?
{71984}{72042}Da bi raöirili vesti da je|pravda zadovoljena.
{72053}{72110}Nakon öto pokolje ceo koven.
{72185}{72271}Bendûamine. Tia. Odlazimo.|-Gde Êete?
{72306}{72363}Zaöto misliö da Êe stati sa Alis?
{72375}{72440}äta Êe ga zaustaviti|da ne krene i po Bendûamina.
{72448}{72515}Ili Zafrinu ili Kejt ili bilo koga|drugog ko ima dar ili koga ûele.
{72524}{72588}Njihov cilj nije kazna nego moÊ.|Osvajanje svega.
{72598}{72674}Karlajl moûda ne ûeli da se bori,|ali ja ûelim. Zbog moje porodice,
{72684}{72779}ali i svih vas. I naËina|na koji ûelite da ûivite.
{72985}{73070}»opor Êe se boriti. Nikad se|nismo plaöili vampira.
{73134}{73188}Mi Êemo se boriti.
{73198}{73260}NeÊe biti prvi put|da kröim kraljevski zakon.
{73275}{73325}PridruûiÊemo vam se.|-Ne.
{73360}{73452}Ja Êu uraditi ono öto je ispravno.|Ti uradi öta god ûeliö.
{73521}{73586}BiÊemo uz vas.|-I mi Êemo.
{73685}{73775}Nisu dugo razmiöljali.|-Nadamo se da neÊe doÊi do toga.
{73796}{73847}VideÊemo.
{74059}{74122}Svi su pokazali hrabrost.
{74124}{74202}Znali smo da je Aro|veÊ krenuo na nas.
{74215}{74278}Uskoro Êemo se suoËiti|sa mraËnom Dûejn.
{74288}{74362}I joö gorom paralizujuÊom|moÊi njenog brata, Aleka.
{75082}{75137}Alek.
{75613}{75742}Nisam ti prkosio.|-Naravno da nisi, dragi moj Toöiro.
{76200}{76298}Izgleda da te Karlajl oËekuje.
{76518}{76599}Karlajl pokuöava da osigura|sopstveno uniötenje.
{76622}{76680}Tuûno, zar ne?
{76738}{76814}Aro ûeli da nas oslabi|pre nego napadne.
{76820}{76905}Dûejn i Alek Êe mene prvog napasti|poöto mogu predvideti njihove poteze.
{76912}{76994}äteta öto svi nemamo tvoj ötit.|-On ne pomaûe u borbi.
{77002}{77067}Ali, moûeö pomoÊi ostalima,|ako moûeö da ih zaötitiö.
{77074}{77135}Kako to misliö?|-Da zaötitiö joö nekog osim sebe.
{77145}{77198}Zar je to moguÊe?|-Darovi se mogu razvijati. Vremenom.
{77209}{77313}Moj je na poËetku bio na dlanovima.|Sada ga emitujem po celom telu.
{77321}{77384}Kako to radiö? Reci mi.
{77427}{77491}Moraö da ga vizualizujeö.
{77507}{77609}Da vidiö kako se kreÊe, koje je boje.
{77662}{77766}Zamisli kako se öiri.|Da ide daleko oko tebe.
{78102}{78184}Mislim da joj je potrebna motivacija.
{78284}{78347}Ne.|-U redu je. Mogu da izdrûim.
{78360}{78432}To kaûe sada.|-Koncentriöi se ili Êe biti povreen.
{78516}{78610}Edvarde, nisam spremna na ovo.|Izvini, rekla sam da nisam spremna.
{78627}{78694}Drugar, ne motiviöeö je.|-HoÊeö da probaö?
{78966}{79041}Kejt.|-Delujeö mi bez oseÊanja.
{79050}{79117}Da probudim Renesme?|-Jesi li normalna?
{79158}{79234}Dobro, sad idemo punom snagom.
{80044}{80117}Bolno je, ali podnoöljivo.
{80246}{80309}Hajde da probamo sa drugima.|-Emete.
{80359}{80413}Neka hvala.
{80417}{80538}"»uje se mirna muzika öto omeköava|na travu pad latica sa procvalih ruûa"
{80581}{80709}"i noÊno kapanje vode iz vodopada|öto pravi odsjaj preko kamenja."
{80783}{80895}"Muzika öto donosi mirni san|sa blaûenih nebesa."
{81236}{81286}Mama?
{81296}{81411}Jesu li tetka Alis i teËa Dûasper|otiöli zato öto Êemo da umremo?
{81541}{81588}Ne.
{81655}{81731}Mislim da su otiöli|da bismo mi bili sigurniji.
{81741}{81813}To je ono öto svi|pokuöavamo da uradimo.
{81826}{81882}Nikad nikome neÊu dozvoliti|da te povredi.
{82054}{82124}Spavaj sada.
{82565}{82691}»udno. FiziËki se oseÊam kao|da mogu da razvalim tenk,
{82707}{82779}a mentalno sam iscrpljena.
{82867}{82936}äta kaûeö na kupku?
{83379}{83511}Znam i sama da se skinem.|-Da, ali ja to radim bolje.
{83678}{83727}Vidi...
{83776}{83873}Imam loöu naviku da te potcenjujem.
{83907}{84023}Toliko sam bio opËinjen, da sam mislio|da to niËim neÊeö moÊi prevaziÊi.
{84095}{84205}A opet jesi. Dala si mi|razlog za öta da se borim.
{84267}{84330}Moju porodicu.
{84695}{84786}Idem da pripremim vodu.
{85509}{85558}"Dû. Dûenks, Sijetl.|Uniöti ovo!"
{85568}{85618}Alis se pobrinula da|samo ja dobijem poruku,
{85629}{85684}jer Êe samo moj um|biti siguran od Aroa.
{85855}{85925}Iznenauje me da|praviö pauzu u treningu.
{85936}{86007}Ako tajno ne odvedem Renesme da|vidi mog oca, on Êe doÊi da vidi nas.
{86029}{86091}Dvadeset ûednih vampira i jedan Ëovek.
{86115}{86206}Loöija verzija.|-Znam zaöto nisi rekla Edvardu.
{86367}{86460}Kako bilo. Drago mi je da smo|otiöli od prokletih krvopija.
{86517}{86611}éao mi je. Znam.|Oni su dobri momci.
{86676}{86753}Ali, moraö priznati,|Drakula 1 i 2 su...
{87200}{87303}Evo nje. Doi ovamo.|Vidi ti nju.
{87333}{87435}Porasla si 30 centimetara.|Stvarno. Ili bar 15.
{87483}{87545}Uite. RuËak je na stolu.|Treba da ukrasimo jelku.
{87567}{87653}Zapravo, moram neöto da zavröim.|VraÊam se uskoro.
{87723}{87767}Hajde, idemo.
{87952}{88012}Alisina poruka mi je dala novu nadu.
{88029}{88161}Moûda je ipak imala neki plan,|a moûda je Dû. Dûenks kljuË.
{88679}{88751}Treba da se naem sa g. Dûenskom.|-Ovuda.
{88823}{88867}Izabela.|-Zdravo.
{88878}{88931}Drago mi je da si nazvala.
{89234}{89348}Najbogatije klijente uvek ovde viam.|Udobnije je nego u kancelariji.
{89361}{89411}I u javnosti je.
{89450}{89530}Dakle, Ëime se vi bavite?|-Svim i svaËim.
{89551}{89634}Uvek je neöto drugo, pa|je zato i interesantno.
{89678}{89803}Znate Alis i Dûaspera odavno?|-Radim sa njima duûe od 20 godina.
{89831}{89924}A moj partner zna Dûaspera|15 godina duûe od mene.
{89939}{90051}On se, neobiËno dobro drûi.
{90086}{90131}Da, tako je.
{90205}{90288}Verujem da Êe mu se vaö muû|pridruûiti na godiönjem odmoru.
{90329}{90398}Nije vam rekao gde ide?|-Nije.
{90430}{90500}Samo je rekao da ide i|da je svratio da sve sredi.
{90567}{90640}Pretpostavljam da je sve spremno.|-Naravno.
{90661}{90721}Nikada ne kasnim sa isporukama.
{91165}{91265}Ima li nekih problema?|-Ne.
{91354}{91413}Moj muû i ja smo mislili|da Êemo zajedno putovati.
{91423}{91501}Dûasper je rekao samo dvoje.|Instrukcije su bile veoma jasne.
{91512}{91561}Moja greöka.
{91593}{91671}Izgleda da se to neÊe desiti.
{92164}{92225}Alisina vizija je bila jasna.
{92301}{92366}Renesme Êe imati buduÊnost,
{92390}{92446}ali Edvard i ja neÊemo biti deo nje.
{93089}{93175}"Draga moja Renesme, mislila sam|da Êemo zauvek biti zajedno."
{93215}{93283}"Ali, to zauvek neÊe trajati|dugo koliko sam se nadala."
{93292}{93364}"Sada znam zaöto mi je Alis|ostavila trag. Da te zaötiti."
{93423}{93537}"Sve öto tebi i Dûejkobu treba je u|ovom rancu. Dûejkob Êe te zaötititi."
{93576}{93640}"I nadam se da Êe te|nauËiti sve legende."
{93706}{93771}To je romantiËno, zar ne?
{93781}{93847}Imamo pravedan razlog da se|suprostavimo velikom zlu.
{93865}{93968}Moram priznati, Ëak si|i mene uverila. Na trenutak.
{94070}{94166}Sretno vam bilo. TrebaÊe vam.
{94238}{94276}éiveli.
{94488}{94586}Sneg prestaje.|-Imamo joö posla.
{94736}{94820}Drago mi je da je »arli naöao|nekoga ko Êe brinuti o njemu.
{94822}{94880}Bela, niko nema sve.
{94909}{94973}Dobro. Vreme je za poklone.|Idemo.
{94978}{95029}Set, Lija. Prestanite da jedete.
{95054}{95101}Dûejk, ti poËni. Izvoli.
{95111}{95159}äta si ti dobila?|-Niöta.
{95192}{95259}Ma, daj. äta si dobila?|-Tata, nismo stigli da upakujemo.
{95272}{95310}Izvoli.
{95427}{95516}Petodnevno pecanje na|reci Frejzer, za tebe i Saru.
{95527}{95599}KreÊete sutra.|-To je veoma lepo. Hvala vam.
{95624}{95717}Sutra? Ne, ne mogu sutra.|-Sredila sam sve na poslu.
{95748}{95938}Podmuklo. I ekstravagantno.|-I nije povratno, na ûalost.
{95966}{96031}Pokuöavate da me se reöite?
{96071}{96108}Uspeva vam.
{96147}{96208}Idemo na Frejzer.|ZnaËi da Êemo loviti somove.
{96219}{96289}Moûda i jelene i divlje veprove.|-éena zna znanje.
{96355}{96413}Prelepo je. Da vidim.
{96437}{96510}Dûejkob ti je napravio?|Mogu li da ti stavim?
{96643}{96706}Tako je lepa.|-Jeste.
{97229}{97283}To se zove logorska vatra.
{97304}{97419}Druûenje uz vatru pre borbe?|-PriËamo ratne priËe.
{97538}{97615}Zaöto stoji tamo poput statue?
{97655}{97740}Imenuj bilo koju ameriËku|bitku i ja sam bio tamo.
{97740}{97764}Litl Big Horn.
{97861}{97956}Bio sam tako blizu da ujedem Kastera,|ali su ga se indijanci prvi doËepali.
{97995}{98108}Probaj sa Konstantinopoljem?|Tamo nije bio sam.
{98130}{98207}PriËamo o borbama,|a ne o dugogodiönjim ratovima.
{98217}{98299}Niko nema ustanke kao Irci.|-Jedanaestogodiönji rat je izgubljen.
{98315}{98380}Da, ali je to bio avolski ustanak.
{98396}{98460}Kada smo mi vladali,|svi su nam dolazili.
{98472}{98567}Vernici, diplomate, koristoljupci.
{98578}{98640}Tolika je bila naöa moÊ.
{98651}{98726}Ali, nikad se nismo ogrnuli belim|mantijama i nazvali se svecima.
{98747}{98875}Bili smo iskreni oko toga öta smo.|-Bili smo mirni dugo vremena.
{98925}{99003}Nismo ni primetili da smo|poËeli da se pretvaramo u kamen.
{99047}{99159}Moûda su nam Volturijevi uËinili|uslugu kad su nam zapalili zamkove.
{99186}{99307}»ekamo 500 godina|da im uzvratimo uslugu.
{99492}{99569}Ne mogu da ne mislim kako svi|oni rizikuju, zato öto sam se ja
{99578}{99649}zaljubio u ljudsko biÊe.|-Naöao si svoju partnerku.
{99660}{99742}Zasluûujeö da budeö sreÊan.|-Ali, po kojoj ceni.
{99754}{99825}Svako od njih ima razlog za borbu.|Ja svakako imam.
{100100}{100175}Karlajl, nisam ti se nikad zahvalio
{100213}{100299}za ovaj izuzetni ûivot.
{100687}{100775}Ovo mi znaËi viöe od ûivota.|Toliko te volim.
{100800}{100868}Sutra moraö ostati uz Dûejkoba.
{100896}{101009}Bez obzira na sve, Ëak i ako umrem,
{101054}{101115}molim te idite negde.
{101268}{101329}On Êe te zaötititi.
{101386}{101428}Uvek.
{102486}{102589}Ako ovo preûivimo,|pratiÊu te bilo gde.
{102690}{102757}Sada mi to kaûeö.
{103104}{103173}Evo ih, dolaze. Dolaze.
{104064}{104117}Aro traûi Alis.
{105597}{105682}Lepe reËi, Karlajl.|Ali, malo Ëudne
{105693}{105774}s obzirom na bataljon,|koji si pripremio za naö doËek.
{105786}{105883}ObeÊavam ti da mi to nije namera.|Ni jedan zakon nije prekröen.
{105907}{106035}Vidimo dete. Smatrate nas budalama?|-Ona nije dete vampir.
{106115}{106211}Ovi svedoci Êe vam to potvrditi.|Moûete i sami videti.
{106244}{106304}Vidite trag ljudske krvi|na njenim obrazima.
{106313}{106398}Dosta je sa ovim.|-PokupiÊu sve deliÊe istine,
{106446}{106621}ali od nekog ko je kljuËan u priËi.|Edvarde, poöto se dete priljubilo
{106638}{106772}uz tvoju novoroenu partnerku,|pretpostavljam da si umeöan.
{108551}{108626}Voleo bih da je upoznam.
{109929}{110038}Mlada Bela. Besmrtnost ti lepo stoji.
{110260}{110348}Ti si zaista Ëudno biÊe.
{110812}{110891}Ko sam ja?
{111273}{111338}Predivno.
{111482}{111567}Pola smrtnik pola besmrtnik.
{111581}{111737}ZaËeta i noöena dok je ova|novoroena joö bila ljudsko biÊe.
{111773}{111822}NemoguÊe.
{111845}{111914}Misliö da su me prevarili, brate?
{112112}{112179}Dovedite cinkaroöa.
{112484}{112570}Da li je to dete koje si videla?
{112663}{112716}Nisam sigurna.|-Dûejn.
{112728}{112840}DrugaËija je. Ovo dete je veÊe.|-Tvoje informacije su bile laû.
{112866}{112971}Kalenovi su nevini. Preuzimam|potpunu odgovornost za moju krivicu.
{113066}{113118}Izvinjavam se.
{113236}{113278}Kaiuse, nemoj.
{113826}{113872}Ne zadrûavajte nas.
{113885}{113960}Tanja, ovo je ono öto ûele.|Ako sada napadneö gotovi smo.
{114479}{114548}Bol.
{115377}{115432}Radi.
{116176}{116245}Aro, video si da ni jedan|zakon nije prekröen.
{116304}{116418}Slaûem se. Ali, to ne znaËi|da nema opasnosti.
{116569}{116732}Po prvi put u naöoj istoriji|ljudi su pretnja naöoj vrsti.
{116775}{116915}Moderna tehnologija je omoguÊila|raanje oruûja koje nas moûe uniötiti.
{117009}{117116}I zaötititi naöu tajnu|nikad nije bilo vaûnije.
{117163}{117336}U ovako paralizujuÊem momentu samo|ono öto je poznato je sigurno.
{117404}{117512}Samo poznato je podnoöljivo,|a mi niöta ne znamo o tome
{117530}{117740}öta Êe ovo dete postati. Moûemo|li ûiveti u takvoj neizvesnosti?
{117815}{118013}Da se poötedimo danaönje borbe|da bismo sutra umrli?
{118052}{118100}Ne.
{118404}{118450}Alis.
{118825}{118922}Draga moja, Alis.|Tako sam sretan öto te vidim.
{118928}{119006}Imam dokaz da dete neÊe|biti rizik za naöu vrstu.
{119049}{119119}Dozvoli da ti pokaûem.|-Brate.
{119730}{119798}Nije bitno öta Êu ti pokazati.
{119827}{119929}»ak i poöto si video|ne ûeliö da promeniö odluku.
{119966}{120017}Sada.
{120265}{120337}Pazi na moju kÊerku.
{120445}{120498}Drûite ih.
{121120}{121170}Vodite je.
{121213}{121256}Pusti je.
{126109}{126184}Dûejkobe.
{126376}{126416}Pazi.
{130411}{130462}DokrajËi ga.
{130817}{130863}KonaËno.
{133510}{133591}Sada znaö. To je tvoja buduÊnost.
{133626}{133717}Osim ako drugaËije odluËiö.|-Ne moûemo promeniti odluku.
{133729}{133806}Dete je i dalje velika pretnja.|-äta ako vas uverimo
{133816}{133896}da moûe da ûivi u ljudskom svetu.|Moûemo li ûiveti u miru?
{133907}{134031}Naravno, ali to ne moûemo znati.|-Zapravo, moûemo.
{134943}{135026}TraûeÊi svedoke,|meu plemenima u Brazilu...
{135039}{135101}Imali smo dovoljno svedoka.|-Brate, pusti je da govori.
{135129}{135240}Ja sam pola Ëovek pola vampir,|poput deteta.
{135291}{135380}Vampir je zaveo moju majku,|koja je umrla na poroaju.
{135397}{135491}Moja tetka Hulien me odgojila.
{135530}{135650}Ja sam je napravio besmrtnom.|-Koliko imaö godina?
{135719}{135764}150 godina.
{135798}{135873}U kojim godinama si dosegao|svoju zrelost?
{135885}{135958}Svoju punu veliËinu sam dosegao|sedam godina po roenju.
{135976}{136035}Od tada se nisam menjao.
{136138}{136219}A tvoja ishrana?|-Krv i ljudska hrana.
{136263}{136382}Mogu da opstanem na obe.|-Ova deca su nam dosta sliËna.
{136417}{136517}Kalenovi su se udruûili sa vukovima,|naöim prirodnim neprijateljem.
{136830}{136938}Dragi moji, ovde|nema nikakve opasnosti.
{137007}{137079}NeÊemo se boriti na smrt.
{137748}{137817}Kako skupa cena.
{137891}{137959}Sada kada su u begu je najbolji|momenat da napadnemo.
{137976}{138012}Ne danas.
{138082}{138165}Svi ste vi budale.|-Volturijevi su moûda otiöli,
{138179}{138260}ali vam nikada neÊe oprostiti|ono öto se ovde desilo.
{139226}{139320}prevod: bojanadj|www.titlovi.com
{139886}{139997}Ipak Êe biti uz nas dugo?|-Veoma dugo.
{140094}{140161}Drago mi je öto ima tebe.
{140336}{140441}Treba li da te zovem tata?|-Ne.
{140926}{141012}Da. Sada Êemo svi ûiveti zajedno.
{141922}{142017}éelim neöto da ti pokaûem.|-äta?
{142787}{142838}Ja sam Edvard Kalen.
{143819}{143885}Kako si to uradila?|-Veûbala sam.
{143989}{144039}Sada znaö.
{144099}{144212}Niko nikada nikog nije voleo|onoliko koliko ja volim tebe.
{144230}{144292}Osim jednog izuzetka.
{144524}{144613}HoÊeö li mi opet pokazati?|-Ne, to je sve öto mogu.
{144686}{144739}I bolje.
{144777}{144842}Zauvek.
{145388}{145452}"Zauvek."
{145492}{145563}prevod: memara
{145588}{147088}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
