{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{553}{690}Nekada davno u jednoj dalekoj Galaksiji...
{740}{1000}Z V E Z D A N I|R A T O V I
{1001}{1225}Epizoda 4|N O V A   N A D A
{1226}{1501}Period je graanskog rata.|pobunjeniËki brodovi, napadajuÊi iz|skrivenih baza, dobili su...
{1502}{1751}...prvu bitku protiv zle galaktiËke Imperije.|Tokom bitke, pobunjeniËki öpijuni uspeli su|da ukradu tajne planove o Imperijalnom...
{1752}{2002}...konaËnom oruûju, ZVEZDI SMRTI,|naoruûanoj svemirskoj stanici koja je imala|snagu da uniöti Ëitavu planetu.
{2003}{2252}Gonjena od strane Imperijalnih agenata,|Princeza Leja ûurila je da odnese ukradene planove,
{2253}{2452}...koji mogu da spase njen narod,|i da vrate slobodu u Galaksiju....
{2502}{3003}www.Diveks.tk|isporuka na kuÊnu adresu
{4230}{4295}Jesi li Ëuo to?|IskljuËili su glavni reaktor.
{4313}{4373}Sigurno Êe nas uniötiti.|Ovo je ludilo!
{4647}{4698}Propali smo!
{4738}{4790}Ovoga puta princeza neÊe umaÊi.
{4869}{4920}äta je to?
{7474}{7537}R2-D2, gde si?
{7944}{7982}KonaËno! Gde si bio?
{7996}{8048}Idu u ovom pravcu.|äta Êemo da radimo?
{8074}{8137}PoslaÊe nas u rudnike zaËina|na Kesselu ili nas rasturiti na komade!
{8204}{8262}Stani malo. Kuda Êeö?
{8570}{8630}Planovi Zvezde Smrti nisu|u glavnom kompjuteru.
{8647}{8700}Gde su poruke|koje ste presreli?
{8710}{8760}äta ste uradili sa planovima?
{8778}{8830}Nismo presreli nikakve poruke.
{8856}{8943}Aaah....Ovo je konzularni brod.|Mi smo na diplomatskoj misiji.
{8960}{9064}Ako je ovo konzularni brod...|gde je ambasador?
{9159}{9247}Komandante, rasturite brod|dok ne naete planove
{9260}{9308}i dovedite mi ambasadora.|éelim je ûivu!
{9638}{9678}Eno je! Podesi|na oöamuÊivanje!
{9820}{9899}BiÊe dobro. Obavestite|Lord Vadera da imamo zarobljenika.
{9951}{10003}Hej, Nije ti dozvoljeno tamo.|Zabranjeno je.
{10019}{10055}Zasigurno Êe|te deaktivirati.
{10107}{10177}Ne nazivaj me praznoglavim|filozofom, ti debela grudvo ulja!
{10186}{10216}Sad izai pre nego|te neko vidi.
{10290}{10399}Tajna misija? Kakvi planovi?|äta to priËaö? Ne ulazim ja u to!
{10498}{10536}ZaûaliÊu ovo.
{10720}{10821}-Evo joö jedne.|-Ne pucajte. Nema ûivota.|Mora da je kratak spoj.
{10850}{10929}Baö Ëudno, oöteÊenja ne izgledaju|tako straöna odavde.
{10994}{11046}Siguran si da je|ova stvar bezbedno?
{11514}{11570}Lord Vader, trebalo je da znam.|Samo vi biste bili toliko smeli.
{11579}{11671}Imperijalni Senat ovo neÊe mirno|prihvatiti kada Ëuje za napad na diplomatski...
{11681}{11775}Ne igrajte se samnom, VisoËanstvo.|Niste bili na mirovnoj misiji ovog puta.
{11785}{11854}Nekoliko poruka je poslato ovom|brodu od strane pobunjeniËkih öpijuna.
{11864}{11944}HoÊu da znam öta je sa|planovima koje su vam poslali.
{11955}{12080}Ne znam o Ëemu govorite.|Ja sam Ëlan Imperijalnog Senata|na diplomatskoj misiji na Alderaan-u...
{12093}{12156}Vi ste deo Saveza Pobunjenika|...i izdajica.
{12167}{12193}Vodite je!
{12297}{12409}Opasno je zadrûati je. Ako se proËuje,|to bi moglo da stvori simpatije|prema Pobuni u senatu.
{12427}{12557}Pratio sam öpijune do nje.|Sada mi je ona jedina veza|da naem njihovu tajnu bazu!
{12570}{12649}-UmreÊe pre nego iöta kaûe.|-Prepustite to meni.
{12661}{12740}Poöaljite poziv u pomoÊ i onda|javite senatu da su svi na brodu poginuli!
{12766}{12870}Lorde Vader, planovi stanice|nisu na brodu! I poruke nisu slane.
{12882}{12974}Kapsula za spasavanje je|ispaljena tokom borbe,|ali bez znakova ûivota.
{13000}{13053}Mora da je sakrila|planove u kapsuli.
{13066}{13118}Poöaljite jedinicu da ih nae.|Pobrinite se liËno za to, komandante.
{13131}{13195}Ovog puta nas|niko neÊe zaustaviti.
{13600}{13692}Kako sam se uvalio u ovo?|Stvarno ne znam kako.
{13730}{13808}Izgleda da smo roeni da|se muËimo. Takva nam je sudbina.
{13887}{13964}Moram da se odmorim pre nego|se raspadnem. Zglobovi su mi se skoro smrzli.
{14147}{14192}Kakvo opustoöeno mesto.
{14325}{14381}Kuda ideö?|Pa, ja neÊu tim putem.
{14421}{14486}Isuviöe je stenovito.|Ovuda je mnogo laköe.
{14512}{14569}Zaöto misliö da tamo|ima naseobina?
{14617}{14652}Nemoj da tu mi komplikujeö.
{14694}{14742}Kakva misija?|äta to priËaö?
{14798}{14864}Dosta mi je tebe!
{14890}{14981}Idi tim putem!|PokvariÊeö se za dan,|ti kratkovida gomilo otpada!
{15007}{15085}I nemoj  da te uhvatim da juriö zamnom|moleÊi za milost, jer je neÊeö dobiti.
{15450}{15528}Dosta je avantura.|Ja neÊu tim putem.
{16415}{16478}Taj pokvareni mali örafciger.|Za sve je ovo on kriv!
{16490}{16584}Prevario me je da krenem ovuda,|ali ni on neÊe proÊi bolje.
{16675}{16780}Stani, öta je to?|Prevoz! Spaöen sam!
{16805}{16844}Ovamo!
{16884}{16988}PomoÊ!|Molim vas, pomoÊ!
{22397}{22474}R2-D2!|To si ti! To si ti!
{23335}{23412}Neko je bio u kapsuli.|Tragovi vode u ovom pravcu.
{23441}{23470}Pogledajte, ser -- droidi.
{23884}{23921}Budi se! Budi se!
{24104}{24137}Proali smo.
{24351}{24383}Misliö da Êe nas rastopiti?
{24729}{24808}Ne pucajte! Ne pucajte!|HoÊe li ovo ikad prestati?
{26058}{26126}Luke, reci Owenu da ako uzme|prevodioca neka proveri da zna Bocce.
{26136}{26189}Izgleda da nemamo mnogo izbora,|ali podsetiÊu ga.
{26546}{26579}Ne, ne tog.
{26632}{26696}Pretpostavljam da si|programiran za protokole.
{26710}{26800}Protokol. To je moj|primarni niz funkcija...
{26814}{26880}-Ne treba mi protokolarni droid.|-Naravno da vam ne treba.
{26892}{26945}Ne u ovakvoj sredini.
{26971}{27062}Ono öto mi stvarno treba je droid|koji razume binarni jezik isparivaËa vlage.
{27075}{27193} IsparivaËi! Ser -- moj prvi posao je bio|programiranje binarnog filtra...sliËno njima.
{27205}{27288}-Govoriö li Bocce?|-Naravno, ser. To mi je kao drugi|jezik...teËno govorim Bocce...
{27302}{27335}Dobro, umukni!|UzeÊu ovog.
{27439}{27505}Luke, vodi ovu dvojicu u garaûu, hoÊeö?|HoÊu da su obojica Ëista pre veËere.
{27518}{27583}Ali iöao sam u Toshi Stanicu|da uzmem pretvaraËe snage...
{27596}{27648}Moûeö da dangubiö sa druötvom|kada zavröiö svoj posao.
{27662}{27698}Hajde sad, kreni!
{27752}{27779}Dobro, hajde!
{27857}{27896}I crveni, hajde.
{27935}{27987}Pa, hajde,|crveni, idemo.
{28469}{28501}UjaËe Owen...
{28508}{28573}Ovaj R2 ima loö|pokretaË. Vidi!
{28586}{28631}Hej, öta to hoÊeö|da nam uvaliö?
{28729}{28821}Oprostite, ser, ali onaj R2 je u|odliËnom stanju. Dobra kupovina.
{28833}{28907}UjaËe Owen!|Moûe ovaj?
{28920}{28957}Moûe ovaj?|UzeÊemo taj.
{29004}{29094}Siguran sam da Êete biti zadovoljni njime, ser.|U prvoklasnom je stanju.
{29108}{29160}Radio sam i ranije sa njim.
{29270}{29316}OK, idemo.
{29330}{29431}Sada, ne zaboravi! Zaöto da rizikujem|zbog tebe stvarno mi je neshvatljivo!
{29603}{29695}Hvala tvorcu! Ova kupka od|ulja Êe mi tako prijati.
{29733}{29804}Straöno sam zaprljan praöinom,|jedva se kreÊem!
{29824}{29929}Baö nije fer. Oh, Biggs je u pravu.|Nikada neÊu otiÊi odavde!
{29942}{29980}Mogu li nekako da pomognem?
{30008}{30125}Pa, ne osim ako moûeö da utiËeö na vreme,|ubrzaö ûetvu i teleportujeö me odavde!
{30137}{30241}Ne verujem, ser. ja sam samo droid|i ne znam mnogo o tim stvarima.
{30255}{30359}Bar ne na ovoj planeti. U tvari,|nisam Ëak siguran ni na kojoj sam planeti.
{30385}{30471}Pa, ako postoji svetli centar univerzuma,|ti si na najudaljenijoj planeti odatle.
{30489}{30583}-Shvatam, ser.|-Uh, zovi me Luke.
{30593}{30633}Da, ser Luke.
{30651}{30685}Samo Luke.
{30698}{30776}A ja sam C3PO,|ljudsko-kiboröki odnosi,
{30789}{30842}a ovo je moj parnjak, R2D2.
{30932}{31008}Ovde imaö mnogo zapeËenog ugljenika.|Izgleda da ste vi momci dosta proöli.
{31023}{31127}Kroz öta smo sve proöli, ponekad se Ëudim|da smo u tako dobrom stanju,|uz Pobunjenike i sve to.
{31154}{31219}-Znate za Pobunjenike protiv Imperije?|-Tako smo dopseli u vaöu sluûbu,|ako me shvatate, ser.
{31297}{31349}-Jesi li bio u mnogo bitaka?|-Nekoliko, bar mislim.
{31363}{31402}U stvari, nema öta da se priËa.
{31415}{31479}Ja sam samo prevodilac,|i ne priËam dobro priËe.
{31506}{31558}Pa, bar ih ne Ëinim|interesantnim, u svakom sluËaju.
{31584}{31662}Pa, mali prijatelju, imaö|neöto ovde stvarno zaglavljeno.
{31675}{31715}Da li ste bili na krstarici ili...
{31740}{31805}Pomozite mi, Obi-Wan Kenobi.|Vi ste mi jedina nada.
{31819}{31857}äta je to?
{31871}{31923}äta je öta?!? Posatvio ti je pitanje...|äta je öta?
{31949}{32013}Pomozite mi, Obi-Wan Kenobi.|Vi ste mi jedina nada.
{32132}{32197}Pomozite mi, Obi-Wan Kenobi.|Vi ste mi jedina nada.
{32274}{32354}Oh,kaûe da je to niöta, ser. »ista greöka.|Stari podaci. Ne obraÊajte paûnju.
{32379}{32444}Ko je ona?|Prelepa je.
{32458}{32522}-Bojim se da nisam siguran, ser.|-Pomozite mi, Obi-Wan Kenobi...
{32548}{32626}Milsim da je bila putnik na poslednjem putovanju.|Neka vaûna osoba, ser -- verujem.|Naö kapetan je bio povezan...
{32679}{32718}Ima li joö na ovom snimku?
{32756}{32822}Uprostoji se, R2.|UvaliÊeö nas u nevolje.
{32835}{32900}U redu je, moûeö mu verovati.|On je naö novi gospodar.
{32913}{32952}...Vi ste mi jedina nada..
{32992}{33083}Kaûe da je vlasniötvo Obi-Wan Kenobia,|stanovnika ovih krajeva.
{33096}{33188}I to je privatna poruka za njega.|Iskreno, ser, ne znam o Ëemu priËa.
{33226}{33264}Naö poslednji gospodar|je bio kapetan Antilles,
{33278}{33344}ali kroz öta smo proöli,|ovaj mali R2 j eposato ekscentriËan.
{33396}{33448}Obi-Wan Kenobi? Pitam se|da li misli na matorog Ben Kenobia?
{33460}{33513}Oprostite, ser,|ali znate li o Ëemu govori?
{33526}{33577}Pa, ne znam nikog po imenu Obi-Wan,
{33591}{33695}ali stari Ben ûivi iza mora dina.|Baö je Ëudan samotnjak.
{33733}{33786}Pitam se ko je ona.
{33812}{33865}ZvuËi kao da je u nevolji.|Bolje da pustim celu stvar.
{33956}{34034}Kaûe da je sigurnosna veza|kratkospojila njegov snimaË.
{34053}{34138}Predlaûe da uklonite vezu,|moûda Êe moÊi da pusti ceo snimak.
{34242}{34319}Mislim da je isuviöe mali|da mi pobegne ako mu ovo skinem! OK.
{34516}{34582}Gde je nestala?|Vrati je! Pusti celu poruku.
{34607}{34712}Koju poruku?|Onu koju nosiö u zaraloj utrobi!
{34803}{34855}U redu, stiûem odmah, ujna Beru.
{34868}{34920}Oprostite, ser, ali izgleda|da malo preskaËe.
{34946}{34999}Pa, vidi öta moûeö sa njim.|Odmah se vraÊam.
{35103}{35168}Razmisli da ponovo pustiö poruku.
{35193}{35246}Ne, mislim da mu|se uopöte ne dopadaö.
{35272}{35311}Ne, ni meni se ne dopadaö.
{35533}{35610}-Znaö, mislim da je onaj R2 koji smo|kupili moûda ukraden.|-Zaöto to misliö?
{35638}{35702}Pa, naiöao sam na snimak|dok sam ga Ëistio.
{35714}{35767}Kaûe da pripada nekom po|imenu Obi-Wan Kenobi.
{35846}{35950}Da nije mislio na starog Bena.|Da li znaö o Ëemu priËa?
{35989}{36067}-Pa, pitam se da nije u srodstvu sa Benom.|-Taj starac je samo matora budala.
{36119}{36182}Sutra hoÊu da odneseö R2-a u|Anchorhead da mu izbriöu memoriju.
{36197}{36249}Tu Êe biti kraj tome.|Sada pripada nama.
{36302}{36353}Ali öta ako taj Obi-Wan|doe da ga traûi?
{36368}{36393}NeÊe,
{36419}{36497}mislim da viöe ne postoji.|Umro je otprilike u isto vreme kada i tvoj otac.
{36524}{36588}-Znao je moga oca?|-Rekoh ti da zaboraviö na to.
{36628}{36692}Tvoj ajedina briga je da spremiö|ta dva droida za sutra.
{36719}{36770}Ujutru hoÊu da su na juûnom|grebenu da rade na sakupljaËima.
{36888}{36941}Mislim da Êe ti novi droidi fino raditi.
{36992}{37057}Takoe sam mislio na naö dogovor|da ostanem joö jednu sezonu.
{37136}{37213}I ako ovi novi droidi rade, ûelim|da se prijavim za Akademiju ove godine.
{37253}{37330}-Misliö sledeÊi semestar pre ûetve?|-Svakako ima viöe nego dovoljno droida.
{37344}{37396}Najviöe si mi potreban kada je ûetva.|Samo joö jedna sezona.
{37409}{37526}Ove godine Êe ûetva biti dobra|da mogu da unajmim joö pomoÊnika.
{37539}{37591}A onda idi na|Akademiju iduÊe godine.
{37618}{37696}-Shvati da si mi potreban ovde, Luke.|-Ali to je joö cela jedna godina.
{37709}{37787}-To je samo joö jedna sezona.|-Da,to si rekao kada su Biggs i Tank otiöli.
{37800}{37892}-Kuda Êeö?|-Izgkeda da ne idem nigde.|Treba da zavröim ËiöÊenje droida.
{37917}{37983}Owen, ne moûe zauvek ostati.|VeÊina drugova mu je otiöla.
{37996}{38126}-Ako mu toliko znaËi.|NadoknadiÊu mu sledeÊe godine. ObeÊavam.
{38164}{38230}Luke nije za farmera, Owen.|Isuviöe je na oca.
{38269}{38321}Toga se i plaöim.
{39547}{39586}Zaöto se tu krijeö?
{39599}{39690}Nsam ja kriv, ser.|Molim vas da me ne deaktivirate.
{39703}{39794}Rekao sam mu da ne ide,|ali pun je greöaka, neispravan.
{40041}{40093}Taj R2 je uvek bio problem.
{40107}{40211}Ovi astro-droidi izmiËu kontroli.|»ak ni ja ponekad ne shvatam njihovu logiku.
{40225}{40316}Kako sam bio tako glup?|Nema ga nigde. Prokletstvo!
{40329}{40381}Oprostite, ser, ali zar|ne bismo mogli za njim?
{40393}{40458}Opasno je zbog Pustinjskih Ljudi.|Moramo da saËekamo jutro.
{40497}{40563}-Luke, gasim struju preko noÊi.|-Dobro, dolazim za par minuta.
{40589}{40642}»oveËe, ala Êu nadrljati.
{40654}{40733}-Znaö, taj mali droid Êe|mi zadati mnogo nevolja.|-Oh, nenadmaöan je u tome, ser.
{41319}{41372}Jesi li videla Luka od jutros?
{41384}{41436}Rekao je da ima neöto da obavi|pre nego poËne danas, pa je otiöao ranije.
{41448}{41528}-Je li poveo ona dva droida sa sobom?|-Mislim da jeste.
{41553}{41657}Pa, bolje da ih donese popravljene do|podneva ili Êu mu napraviti pakao!
{41697}{41749}Na skeneru je neöto pravo ispred.
{41761}{41814}Izgleda da je R2...|dodaj gas.
{42400}{42453}Hej, auu, gde si to ti poöao?
{42479}{42530}Gospodar Luke|je tvoj zakoniti vlasnik.
{42543}{42583}NeÊu viöe da Ëujem|to trabunjanje o Obi-Wan Kenobiu...
{42635}{42739}I ne pominji ni tu tvoju misiju.|SreÊan si ako te odmah ne rasturi.
{42751}{42791}Ne, u redu je.
{42817}{42870}äta mu je sad?
{42870}{42935}Kaûe da se nekoliko stvorenja|pribliûava sa jugoistoka.
{42974}{43026}Pustinjski ljudi! Ili joö gore!
{43052}{43092}Hajde, da pogledamo. Hajde.
{43234}{43313}Dole su dve Bantha-e ali|ne vidim...stani malo,
{43339}{43391}to su Pustinjski ljudi.|Vidim jednog od njih.
{45281}{45320}Zdravo tamo!
{45372}{45450}Doi mali moj prijatelju.|Ne boji se.
{45514}{45567}Ne brini, biÊe dobro.
{45723}{45789}Miruj, deËko,|imao si naporan dan.
{45802}{45855}SreÊan si öto si Ëitav.
{45959}{46011}Ben? Ben Kenobi!
{46023}{46063}Kako mi je drago öto te vidim!
{46076}{46127}Pustara Jundland nije za turiste.
{46219}{46297}Reci mi mladi moj Luke,|öta te dovodi ovako daleko?
{46310}{46363}Oh, ovaj mali droid!
{46414}{46519}Mislim da traûi proölog gospodara...|Nikad nisam video tako odanog droida...
{46557}{46636}Tvrdi da je vlasniötvo|Obi-Wan Kenobia.
{46649}{46701}Je li to tvoj roak?|Da li znaö o kome govori?
{46910}{46987}To ime dugo nisam Ëuo...
{47027}{47066}dosta dugo.
{47106}{47170}Mislim da ga je moj ujak znao.|Rekao mi je da je umro.
{47183}{47235}Oh, nije umro,|ne...ne joö uvek.
{47274}{47366}-Da li ga ti poznajeö?|-Pa naravno da ga znam. To sam ja!
{47444}{47535}Nisam iöao pod imenom Obi-Wan|joö pre nego öto si ti roen.
{47600}{47640}Onda ovaj droid nije tvoj.
{47652}{47704}Ne seÊam se da|sam posedovao droida.
{47756}{47796}Vrlo interesantno...
{47836}{47887}Bolje da uemo unutra.
{47900}{48004}Pustinjske ljude je lako zaplaöiti|ali uskoro Êe se vratiti u veÊem broju.
{48369}{48447}Gde sam ja?|Mora da sam loöe stao...
{48500}{48551}Moûeö da ustaneö? Moramo da|odemo odavde pre nego dou Pustinjski ljudi.
{48565}{48630}Mislim da neÊu uspeti.|Vi nastavite, gospodaru Luke.
{48642}{48722}Nema smisla da rizikujete|zbog mene.Ja sam gotov.
{48773}{48838}-Ne, nisi. äta to priËaö?|-Brzo, deËko...krenuli su.
{48994}{49073}Ne, moj otac se nije borio u ratu.|On je bio navigator na svemirskom teretnjaku.
{49086}{49139}To ti je ujak rekao.
{49151}{49230}Mada je trebalo da ostane|ovde i da se ne meöa.
{49268}{49320}Ti si se borio u|kolonijalnim ratovima?
{49333}{49411}Da, i ja sam nekada bio|Dûedaj vitez poput tvog oca.
{49503}{49581}-éeleo bih da sam ga poznavao.|-Bio je najbolji pilot-lovac u galaksiji,
{49620}{49660}i lukav ratnik.
{49673}{49724}»ujem da si i ti postao|priliËno dobar pilot.
{49789}{49828}I bio je dobar prijatelj.
{49869}{49945}äto me je podsetilo...|Imam neöto za tebe.
{50025}{50077}Tvoj otac je hteo da ovo|dobijeö kada odrasteö,
{50102}{50154}ali tvoj ujak nije dozvolio.
{50167}{50220}Plaöio se da ne kreneö|za matorim Obi-Wanom
{50233}{50324}na neki suludi idealistiËki|pohod kao tvoj otac.
{50337}{50415}-Ser, ako vam ne trebam,|ja bih se iskljuËio.|-Vaûi, samo napred.
{50507}{50533}äta je to?
{50546}{50637}Laserski maË tvoga oca.|To je oruûje Dûedaj vitezova.
{50689}{50741}Ne nezgrapno i|nekontrolisano kao blaster.
{50779}{50793}Elegantno oruûje
{50819}{50884}za civilizovanije doba.
{50950}{51001}Hiljadama generacija|Dûedaj vitezovi
{51015}{51092}su bili zaötitnici mira|i pravde u Staroj Republici.
{51131}{51210}Pre mraËnih vremena,|pre Imperije.
{51314}{51367}Kako je moj otac umro?
{51418}{51471}Mladi Dûedaj po|imenu Darth Vader,
{51484}{51536}koji je bio moj uËenik|postao je zao,
{51549}{51640}pomogao je Imperiji da nau|i uniöte Dûedaj vitezove.
{51693}{51757}Izdao je i ubio  tvoga oca.
{51797}{51849}Sada su Dûedaji skoro nestali.
{51888}{51966}Vadera je zavela|mraËna strana Sile.
{51992}{52018}Sile?
{52057}{52110}Pa, Sila je ono|öto daje Dûedajima moÊ.
{52122}{52200}To je energetsko polje koje|se nalazi oko svakog ûivog biÊa.
{52214}{52304}Ona nas okruûuje i proûima.|Ona drûi galaksiju u celosti.
{52500}{52552}Sada da vidimo öta je sa tobom,|moj mali prijatelju.
{52591}{52631}I odakle dolaziö.
{52644}{52696}-Video sam deo poruke koju je...|-Izgleda da sam je naöao.
{52721}{52826}Generale Kenobi, godinama ste|verno sluûili moga oca u Ratu Klonova.
{52852}{52917}Sada vas moli da mu pomognete|u borbi protiv Imperije.
{52930}{52996}ûalim öto liËno ne mogu|da vam uruËim oËevu molbu,
{53008}{53087}ali moj brod je napadnut i|bojim se da je moja misija da vas|odvedem na Alderaan propala.
{53125}{53228}Smestila sam informacije neophodne|za opstanak pobunjenika u memoriju ovog R2-a.
{53257}{53295}Moj otac Êe znati kako da ih izvuËe.
{53309}{53374}Morate da se pobrinete da mu|se ovaj droid vrati neoöteÊen na Alderaan.
{53413}{53465}Ovo je naö najteûi trenutak.
{53478}{53556}Pomozite mi, Obi-Wan Kenobi,|vi ste moja jedina nada.
{53934}{54025}MoraÊeö da nauËiö tajne Sile|ako Êeö da ideö na Alderaan.
{54051}{54155}Alderaan? Ja ne idem na Alderaan.|Moram kuÊi. Kasno je, i onako sam u sosu.
{54195}{54247}Potrebna mi je tvoja pomoÊ, Luke.|Njoj je potrebna tvoja pomoÊ.
{54260}{54311}Isuviöe sam star za takve stvari.
{54442}{54520}Ne mogu da se meöam!|Imam posao da zavröim!
{54547}{54637}Nije da mi se dopada Imperija. Mrzim je!|Ali sada niöta ne mogu da uËinim.
{54703}{54781}-To je tako daleko odvade.|-Tako govori tvoj ujak.
{54807}{54873}Oh, Boûe, moj ujak.|Kako Êu ovo objasniti?
{54885}{54924}NauËi o Sili, Luke.
{55106}{55145}»uj, mogu da te|povezem do Anchorhead-a.
{55171}{55262}Tamo moûeö da naeö prevoz|do Mos Eisley-a ili ma gde drugde.
{55302}{55354}Moraö da postupiö kako ti|misliö da je ispravno, naravno.
{55563}{55641}Dok ova stanica ne bude potpuno|operativna biÊemo ranjivi.
{55654}{55732}PobunjeniËki Savez je suviöe dobro|opremljen. Opasniji su nego öto mislite.
{55732}{55850}Moûda po vaöu flotu, komandante,|na po ovu borbenu stanicu!
{55888}{55967}Pobunjenici Êe nastaviti da dobijaju|podröku Imperijalnog Senata sve dok....
{55980}{56058}Imperijalni Senat viöe|neÊe biti naöa briga.
{56071}{56162}Upravo sam saznao da je|Imperator trajno raspustio savet.
{56188}{56267}Poslednji ostaci Stare Republike|su zbrisani.
{56318}{56384}To je nemoguÊe! Kako Êe Imperator|odrûati kontrolu bez birokratije?
{56397}{56501}Regionalni guverneri sada imaju|direktnu kontrolu nad svojim teritorijama.
{56527}{56605}Strah Êe drûati lokalne|sisteme u posluönosti.
{56631}{56697}-Strah od ove stanice.|-A öta je sa pobunjenicima?
{56710}{56788}Ako su oni doöli do kompletnih|planova ove stanice, moguÊe je,
{56801}{56866}{69832}{69909a koliko malo verovatno,|da pronau slabost i da je iskoriste.
{56906}{56996}Planovi o kojima govorite Êe|uskoro biti nazad u naöim rukama.
{57010}{57074}Bilo kakav napad pobunjenika|na stanicu bi bio uzaludan potez,
{57087}{57139}ma do kakvih tehniËkih|podataka da su doöli.
{57152}{57243}Ova stanica je sada|neprikosnovena moÊ u univerzumu.
{57283}{57323}Savetujem da je upotrebimo!
{57335}{57414}Ne budite isuviöe ponosni na|ovaj tehnoloöki uûas koji ste stvorili.
{57427}{57531}MoÊ uniötenja planete je|niötavna prema moÊi Sile.
{57570}{57648}Ne pokuöavajte da nas zaplaöite|svojim Ëarobnjaötvom, Lorde Vader.
{57660}{57712}Vaöa jadna posveÊenost|toj drevnoj religiji
{57726}{57791}vam nije pomogla da|prizovete ukradene podatke,
{57804}{57882}ili da vam se ukaûe privienje|gde su skriveni pobunjenici...
{58053}{58104}Uznemirava me|vaö nedostatak vere.
{58169}{58221}Dosta! Vader, pustite ga!
{58234}{58274}Kako ûelite.
{58325}{58378}Ovo prepiranje je besmisleno.
{58417}{58495}Lord Vader Êe nam dati|lokaciju uporiöta pobunjenika
{58508}{58560}dok ova stanica bude zavröena.
{58574}{58651}SlomiÊemo pobunu jednim brzim udarom.
{58847}{58977}Izgleda da su ovo uradili Pustinjski ljudi.|Vidi, ovde Gaffi palice, tragovi Bantha.
{59004}{59095}Nisu. Ali treba da mislimo da jesu.
{59081}{59134}Ove stazu su jedna kraj druge.
{59147}{59238}Pustinjski ljudi uvek idu jednom|stazom da sakriju svoj broj.
{59251}{59315}To su iste Jawae koje su nam|prodale R2-a i 3PO-a.
{59328}{59420}A i ovi pogotci, isuviöe su|precizni za Pustinjske ljude.
{59446}{59524}Samo su imperijalni|vojnici tako precizni.
{59551}{59602}Zaöto bi imperijalne|snage pobile Jawae?
{59745}{59837}Ako su pratili roobote do ovde, moûda|su saznali kome su ih prodali.|A to Êe ih odvesti...
{59849}{59902}-kuÊi!|-Stani, Luke!
{59915}{59954}Isuviöe je opasno.
{60554}{60579}UjaËe Owen!
{60593}{60619}Ujna Beru!
{61935}{61975}A sada VisoËanstvo,
{61987}{62066}razgovaraÊemo o lokaciji|skrivene baze pobunjenika.
{63161}{63213}Nisi mogao niöta da uËiniö,|Luke, i da si bio tu.
{63225}{63342}I ti bi poginuo, a droidi bi|pali u ruke Imperiji.
{63408}{63486}HoÊu sa tobom na Alderaan.|Ovde viöe nemam niöta.
{63526}{63591}éelim da nauËim o Sili i|postanem Dûedaj kao i moj otac.
{63981}{64034}Svemirska luka Mos Eisley.
{64047}{64151}Nikad neÊeö naÊi gore gnezdo|öljama i pokvarenjaka.
{64190}{64216}Moramo biti oprezni.
{65258}{65337}-Koliko dugo imate te droide?|-Oko 3 ili 4 sezone.
{65350}{65375}Na prodaju su ako ih ûelite.
{65415}{65507}-da vidim vaöa dokumenta.|-Ne treba da vidite naöa dokumenta.
{65532}{65583}Ne treba da vidimo|vaöa dokumenta.
{65598}{65649}Ovo nisu droidi koje traûite.
{65663}{65715}Ovo nisu droidi koje traûimo.
{65728}{65779}Moûemo da idemo svojim poslom.
{65792}{65858}-Moûete da idete svojim poslom.|-Krenite.
{65884}{65936}Krenite. Krenite.
{66353}{66418}Ne podnosim ove Jawae.|Odvratna stvorenja.
{66535}{66614}Ne shavatam kako smo proöli pored|onih vojnika. Mislio sam da smo gotovi.
{66626}{66718}Sila ima jak uticaj|na one slabe volje.
{66810}{66887}Stvarno misliö da Êemo ovde|naÊi pilota da nas prebaci na Alderaan?
{66901}{66979}Pa, veÊina boljih pilota teretnjaka|je ovde. Pazi samo gde stajeö.
{67005}{67057}Ovde moûe da bude opasno.
{67071}{67096}Spreman sam na sve.
{67200}{67227}Hajde, Artoo.
{68503}{68646}-takve ovde ne sluûimo!|-äta?|-Tvoji droidi.Moraju da Ëekaju napolju.
{68687}{68738}Sluöaj, zaöto ne saËekate kod brzinca.|Ne ûelimo nevolje.
{68751}{68777}Iskreno se slaûem sa vama, ser.
{69950}{70015}-Ne dopadaö mu se.|-éao mi je.
{70055}{70106}I meni se ne dopadaö.
{70119}{70185}Nemoj da si nas vreao. Pazi se.|Mi smo traûeni kriminalci
{70198}{70263}Imam smrtnu|presudu u 12 sistema.
{70276}{70341}-Onda Êu biti oprezan.|-BiÊeö mrtav.
{70355}{70407}Taj mali nije vredan truda.
{70419}{70459}Da vas poËastim neËim...
{71136}{71175}Ne treba.
{71213}{71332}Chewbacca je moj zamenik|na brodu koji bi vam odgovarao.
{71449}{71501}Ne dopada mi se ovo.
{71866}{71943}Han Solo. Ja sam kapetan|Milenijumskog Sokola.
{71957}{72035}Chewie mi reËe da traûte|prevoz do sistema Alderaan.
{72047}{72100}Da, zaista. Ako je brod brz.
{72113}{72192}Brz brod? Nikada niste Ëuli|za Mislenijumskog Sokola?
{72218}{72322}-Zar je trebalo?|-To je brod koji je preöao|trku Kessel za manje od 12 parseka!
{72360}{72413}Beûao sam Imperijalnim brodovima,
{72426}{72530}ne lokalnim teökaöima, da naglasim.|PriËam o velikim Corellian brodovima.
{72582}{72635}Dovoljno je brz za tebe, matori.
{72660}{72713}-äta prevozim?|-Samo putnike.
{72739}{72805}Mene, deËaka, dva droida,
{72830}{72882}i bez pitanja.
{72922}{72961}äta je? Neke lokalne nevolje?
{72973}{73078}Recimo da ûelimo da|izbegnemo meöanje Imperije.
{73130}{73182}Pa, u tome je trik, zar ne?
{73208}{73247}I to Êe vas dodatno koötati.
{73299}{73339}10,000, sve unapred.
{73378}{73403}10,000?
{73442}{73495}Za to bi mogli i|sami da kupimo brod!
{73507}{73559}Ali koÊe da ga vozi, klinac! Ti?
{73573}{73625}Nego öta. nisam ni ja tako loö pilot!|Ne moramo da sluöamo ovo...
{73703}{73833}Moûemo da platimo 2,000 odmah,|plus 15,000 kada stignemo na Alderaan.
{73862}{73891}17,000, uh!
{73976}{74029}OK. Dobili ste brod.
{74042}{74133}-KreÊemo Ëim budete spremni.|Poletaliöte 94.|-94.
{74185}{74264}Izgleda da je neko poËeo|da se zanima za tvoj ruËni rad.
{74303}{74329}Dobro, proveriÊemo.
{74654}{74733}17,000!|Mora da su stvarno oËajni.
{74746}{74823}Ovo bi moglo da me spase.|Vrati se na brod i pripremi ga.
{74850}{74954}-MoraÊeö da prodaö brzinac.|-U redu je. Viöe se ne vraÊam na ovu planetu.
{75006}{75046}Krenuo si nekud, Solo?
{75053}{75163}Da, Greedo. U stvari, baö sam|hteo da vidim tvog öefa.|Reci Jabbi da imam njegov novac.
{75176}{75280}Prekasno je. Trebalo je da platiö|dok si imao prilike.
{75306}{75359}Jabba je ucenio tovju glavu,
{75372}{75423}na toliku sumu da te traûe|svi lovci na ucene u galaksiji.
{75463}{75568}- SreÊa öto sam te prvi naöao.|-Da, ali ovog puta imam novac.
{75580}{75658}Ako ga daö meni,|moûda zaboravim da sam te naöao.
{75672}{75749}Nije kod mene. Reci Jabbi...
{75757}{75789}Jabba je zavröio sa tobom.
{75828}{75932}Nema vremena za övercere koji bacaju|tovar Ëim se pojavi Imperijalna krstarica.
{75945}{76023}»ak i mene ponekad zaskoËe.|Misliö da imam izbora?
{76061}{76141}To kaûi Jabbi.|Moûda ti samo uzme brod.
{76166}{76336}-Preko mene mrtvog.|-Tako je i mislio. VeÊ dugo Ëekam da te ubijem.
{76349}{76374}Da, kladim se da je tako.
{76739}{76791}Oprosti zbog nereda.
{77013}{77066}Ima znantnu otpornost|na sondu za Ëitanje misli.
{77079}{77170}ProÊiÊe neko vreme pre nego budemo|mogli da dobijemo neke informacije od nje.
{77183}{77248}KonaËna proba je zavröena.|Svi sistemi rade.
{77260}{77300}Koji pravac da zauzmemo?
{77326}{77404}Moûda Êe reagovati na|durgaËije oblike ubeivanja.
{77417}{77509}-Kako to mislite?|-Mislim da je vreme da demonstriramo|punu moÊ ove stanice.
{77521}{77587}-Postavite kurs za Alderaan.|-Sa zadovoljstvom.
{77625}{77677}ZakljuËaj varat, R2.
{77730}{77781}Dobro, proveri onu stranu ulice.
{77861}{77926}ZakljuËano je.|Kreni na sledeÊa vrata.
{78122}{78199}Radije bih sa gospodarom Lukom|nego da ostanem ovde sa tobom.
{78212}{78278}Ne znam Ëemu tolika guûva,|ali sam siguran da si ti za to kriv.
{78303}{78355}Pazi kako se izraûavaö!
{78407}{78460}Prihvatam.
{78486}{78564}Od kada se pojavio XP-38,|viöe nisu traûeni.
{78577}{78603}BiÊe dovoljno.
{79084}{79150}Izlazi odatle Solo!
{79189}{79229}Ovde sam, Jabba.
{79268}{79359}-»ekao sam te.|-Jesi li?
{79397}{79450}Nisi mislio da|Êu naleteti na tebe?
{79489}{79567}Han, deËaËe, ponekad|me iznenaujeö.
{79593}{79724}Zaöto mi nisi platio?|I zaöto si spalio jadnog Greeda,|posle svega öto smo zajedno proöli?
{79738}{79828}»uj Jabba, kada sledeÊi put hoÊeö|da razgovaramo, doi liËno.|Ne öalji ove mamlaze.
{79867}{79919}Han, Han, shvati me, ne mogu|da priuötim sebi takve troökove.
{79933}{79998}Shvataö da ne mogu|da napravim izuzetak.
{80010}{80063}Gde bih stigao kada bi|svaki moj övercer bacao robu...
{80075}{80127}...Ëim se pojavi Imperijalni brod?
{80141}{80193}To nije dobar posao.
{80206}{80284}»uj Jabba, Ëak i|mene ponekad zaskoËe.
{80311}{80363}Misliö da sam imao izbora?
{80376}{80454}Sada imam fin posao.|VratiÊu ti...
{80456}{80506}...uz dodatak.|Samo mi treba viöe vremena.
{80519}{80584}Han, deËaËe,|najbolji si.
{80610}{80714}ZnaËi, za dodatnih 20%...
{80728}{80780}15 Jabba, ne preteruj.
{80793}{80870}Dobro, 15%.|Ali ako me ponovo izneveriö,
{80885}{80949}uceniÊu tvoju glavu na toliko
{80961}{81041}da neÊeö smeti ni da prieö|nekom civilizovanom sistemu.
{81066}{81145}Jabba, ti si duöa od Ëoveka.
{81183}{81210}Idemo.
{82056}{82096}Kakav krö.
{82108}{82160}Postiûe 0.5 preko|brzine svetlosti.
{82174}{82239}Moûda ne izgleda tako,|ali ima ono öto vredi, klinac.
{82252}{82304}Sam sam uneo posebne dorade.
{82317}{82383}Malo smo u ûurbi, zato ako poûurite|da se ukrcate i da se izgubimo odavde.
{82539}{82577}Zdravo, ser.
{82865}{82904}Dobro, vojsko.|Napunite oruûje!
{82969}{83008}Zaustavite brod!|Rasturite ih!
{83269}{83307}Chewie, vadii nas odavde!
{83347}{83439}Oh, Boûe.Zaboravo sam koliko|mrzim svemirska putovanja.
{83920}{83985}LiËi na Imperijalnu krstaricu.|Mora da ste baö 'vruÊa roba'.
{83998}{84077}Pokuöaj da ih zadrûiö. OkreÊi ötit malo|dok ja proraËunam skok na svetlosnu brzinu.
{84350}{84416}Oprez! Dolaze joö dvojica;|PokuöaÊe da nam preseku put.
{84429}{84520}-Zaöto im ne pobegnemo? Zar nisi|rekao da je ova stvar brza.|-Pazi öta priËaö, klinac !
{84546}{84611}BiÊemo bezbedni kada|skoËimo u hipersvemir.
{84624}{84676}Pored toga, znam par fora.|UteÊiÊemo im!
{84793}{84859}-PoËinje zabava!|-Koliko joö do skoka|na svetlosnu brzinu?
{84884}{84963}-Treba par trenutaka da unesem|koordinate u navigacioni kompjuter.|-äaliö se?
{84989}{85055}Put kroz hipersvemir ti nije|zapraöivanje kukuruza, klinjo!
{85067}{85119}Bez taËnih proraËuna|proleteli bi kroz neku zvezdu
{85121}{85211}ili priöli nekoj supernovi i zavröili|put malo prerano, zar ne?
{85236}{85327}äta to bljeska?|Gubimo ötit.
{85889}{85940}Stigli smo u Alderaan sistem.
{85953}{86057}Guverneru Tarkin, trebalo je|da oËekujem da vas Vader drûi na lancu.
{86070}{86161}Osetila sam vaö smrad kada|su me doveli ovde.
{86196}{86248}äarmantna do kraja.
{86266}{86358}Ne znate koliko je bilo teöko|potpisati naredbu za vaöu likvidaciju!
{86370}{86435}»udi me da ste imali hrabrosti|da liËno snosite odgovornost!
{86448}{86553}Princezo Leia, pre nego vas pogube|ûelim da prisustvujete ceremoniji
{86566}{86631}koja Êe uËiniti ovu|stanicu operativnom.
{86657}{86723}nijedan zvezdani sistem se sada neÊe|usuditi da se suprotstavi Imperatoru.
{86735}{86866}äto viöe steûete obruË, Tarkin,|viöe Êe vam sistema izmaÊi kroz prste.
{86874}{86944}Ne posle demonstracije|moÊi ove stanice.
{86970}{87074}Na neki naËin, vi ste odredili izbor|planete koja Êe biti prva uniötena.
{87100}{87192}Poöto ste odbili da nam date|poloûaj baze pobunjenika,
{87204}{87288}izabrao sam da testiram moÊ|ove stanice...na vaöoj rodnoj planeti
{87300}{87326}Alderaan-u.
{87361}{87425}Ne! Alderaan je miroljubiv. Nemamo|oruûja. Ne biste nikako mogli...
{87439}{87530}éelte neku drugu metu? Vojni cilj?|Onda dajte ime tog sistema!
{87600}{87686}Dosadilo mi je da postavljam|pitanja. BiÊe ovo poslednji put.
{87700}{87751}Gde je baza pobunjenika?
{87842}{87882}Dantooine.
{87908}{87947}Oni su na Dantooine-u.
{87960}{88026}Tako. Vidite Lorde Vader,|ume da bude razumna.
{88038}{88090}Nastavite operaciju.|Pucajte kada budete spremni.
{88098}{88148}-äta?|-Isuviöe ste lakoverni.
{88155}{88221}Dantooine je predaleko|za efektnu demonstraciju.
{88229}{88325}Ali ne brinite. Uskoro Êemo se|pozabaviti sa vaöim prijateljima.
{88403}{88455}PoËinje primarno paljenje.
{89029}{89081}Dobro si? äta nije u redu?
{89120}{89173}Osetio sam veliki|poremeÊaj u Sili...
{89185}{89290}kao da je milione glasova|vrisnulo od uûasa, a onda iznenadautinulo.
{89329}{89367}Plaöim se da se|dogodilo neöto straöno.
{89433}{89486}Bolje nastavi sa veûbom.
{89550}{89642}Pa, zaboravite na nevolje sa|Imperijalnim puûevima. Rekoh vam da Êemo umaÊi.
{89758}{89784}Nemojte da se|pretrgnete od hvale.
{89811}{89889}Treba da smo kod Alderaan-a|za oko oh-2.00 sati.
{90097}{90150}Oprezno, R2.
{90372}{90436}Odigrao je pravilno.|Kuknjava tu ne pomaûe.
{90448}{90540}-Pusti ga. Nije mudro uznemiriti Vukija.|-Ali, ser, niko ne brine o uznemiravanju droida.
{90580}{90671}Zato öto droid ne kidaju|drugima ruke kada izgube.
{90697}{90749}Vukiji su poznati po tome.
{90801}{90840}Shvatam vas, ser.
{90853}{90931}Predlaûem novu strategiju R2.|Pusti da Vuki pobedi.
{91387}{91478}Zapamti, Dûedaj oseÊa|kako ga Sila proûima.
{91503}{91635}-Misliö da kontroliöe pokrete?|-DelimiËno. Ali se i povinuje tvojoj volji.
{91740}{91844}Prazonoverja i drevna oruûja ne mogu|da se porede sa blasterom u ruci, klinac.
{91856}{91883}Ne verujeö u Silu?
{91921}{91974}Klinac, obiöao sam galaksiju|uzduû i popreko.
{91987}{92052}Video sam mnogo Ëudnih stvari,
{92065}{92183}ali nikad nisam niöta video|öto bi me uverilo da postoji|neka svemoÊna sila koja sve kontroliöe.
{92196}{92273}Nemam nikakvog mistiËnog polja|energije öto kontroliöe moju sudbinu.
{92300}{92365}Sve su to trikovi i besmislice.
{92378}{92429}Predlaûem da ponovo pokuöaö, Luke.
{92469}{92534}Ovog puta, ostavi|svoju svesnu stranu
{92586}{92638}i reaguj instinktivno.
{92665}{92742}Sa spuötenim vizirom,Ëak i|ne vidim. Kako tek da se borim?
{92756}{92808}OËi te mogu prevariti.|Ne veruj im.
{93055}{93108}Upotrebi svoja oseÊanja.
{93108}{93471}www.Diveks.tk
{93472}{93524}Vidiö da moûeö.
{93538}{93628}-To se zove sreÊa.|-U mom iskustvu,  sreÊa ne postoji.
{93656}{93772}»uj, sukob sa tom stvari je jedno.|Sukob sa ûivim protivnikom? To je veÊ drugo.
{93812}{93864}Izgleda da stiûemo na Alderaan.
{93941}{94007}Znaö, osetio sam neöto.|Skoro da sam video to udaljeno.
{94020}{94111}Dobro je. Naparavio si prvi|korak ka öirem svetu.
{94294}{94346}Naöi izviaËi su|stigli do Dantooine-a.
{94358}{94437}Pronaöli su ostatke pobunjeniËke baze,|ali je napuötena veÊ neko vreme.
{94450}{94542}Sada sprovode opseûnu|istragu obliûnjih sistema.
{94554}{94619}Lagala je! Slagala nas je!
{94632}{94711}Rekoh vam da nikada svesno|ne bi izdala pobunjenike.
{94750}{94803}Likvidirajte je..odmah!
{94879}{94945}Spremi se, Chewie, idemo.|Prebaci sub-svetlosne motore.
{95011}{95050}Ma öta...?
{95128}{95206}Au, izaöli smo iz hipersvemira u|pljusak meteora. Neka vrsta sudara asteroida.
{95220}{95258}-Nema ga ni na jednoj mapi.|-äta se deöava?
{95271}{95337}Poloûaj nam je taËan,|osim...öto nema Alderaana!
{95349}{95441}-Kako to misliö?Gde je?|-To ti i objaönjavam, klinac.|Nema ga.Potpuno je uniöten.
{95453}{95505}-äta? Kako?|-Uniötila ga je...Imperija!
{95518}{95623}Cela flota ne bi mogla da uniöti planetu.|Trebalo bi za to hiljade brodova...
{95675}{95727}-Stiûe joö jedan brod.|-Moûda znaju öta se desilo.
{95741}{95779}To je Imperijalni lovac.
{95818}{95884}-Pratio nas je!|-Ne. To je lovac kratkog dometa.
{95897}{95950}Nema baza u blizini.|Odakle je doöao?
{96014}{96078}Baö mu se ûuri.|Ako su nas prepoznali, u nevolji smo.
{96092}{96197}-NeÊe moÊi.Chewie...ometaj mu signale.|-Bolje ga je pustiti.Daleko je van dometa.
{96210}{96235}Ne zadugo...
{96327}{96405}Lovac te veliËine ne bi mogao|da stigne sam duboko u svemiru.
{96418}{96470}Mora da se izgubio, bio je deo|nekog konvoja ili neöto tako.
{96509}{96561}Pa, neÊe biti dovoljno dugo tu|da ikome priËa o tome.
{96614}{96704}-Vidi ga. Ide ka tom malom mesecu.|-Mislim da ga mogu srediti pre nego stigne...|skoro da je u dometu.
{96770}{96808}To nije nikakav mesec!
{96822}{96900}-To je svemirsk astanica.|-Preveliko je za svemirsku stanicu.
{96991}{97082}-Imam loö predoseÊaj.|-Okreni brod.
{97096}{97200}Da, u pravu si. Pun rikverc!|Chewie, ukljuËi dodatno napajanje.
{97329}{97382}Chewie, ukljuËi dodatno napajanje.
{97448}{97538}-Zaöto joö idemo ka njoj?|-Uhvatio nas je vuËni zrak! UvlaËi nas!
{97551}{97604}-Ali mora da neöto moûeö da uËiniö!|-Ne mogu niöta, klinac.
{97630}{97695}MoraÊu da ga ugasim.|Ali me neÊe dobiti bez borbe!
{97799}{97891}Ne moûeö pobediti.|Ali borba ima alternativu.
{98777}{98842}Na svoja mesta!|Poite zamnom.
{99102}{99181}Uhvatili smo teretnjak koji je|ulazio u ostatke sistema Alderaan.
{99194}{99272}Oznake se slaûu sa brodom|koji se probio sa Mos Eisley-a.
{99285}{99376}Mora da pokuöavaju da vrate|ukradene planove princezi.
{99390}{99441}Joö Êe nam ona koristiti.
{99585}{99662}Otvorite 1-5-7 i 9.|Pustite punjenja.
{99859}{99949}Nema nikoga na brodu, ser.|Prema dnevniku, posada je|napustila brod po poletanju.
{99975}{100054}Mora da je mamac, ser. Ispaljeno je|nekoliko kapsula za spasavanje.
{100067}{100158}-Da li ste pronaöli droide?|-Ne, ser. Ako ih je i bilo, mora da su i ga oni napustili.
{100171}{100249}Poöaljite pretraûivaËe na brod.|HoÊu da provere svaki deo.
{100288}{100380}OseÊam neöto...prisustvo|koje nisam osetio joö od...
{100445}{100537}Neka pretraûivaËi hitno dou.|HoÊu da provere svaki deo!
{101031}{101096}-SreÊa da imaö ovaj odeljak.|-Koristim ih za överc.
{101110}{101187}Nikad nisam mislio da Êu se|i sam övercovati. Ovo je suludo.
{101201}{101292}-»ak i da poletim, nikad ne bih|proöao pored vuËnog zraka.|-Prepustite to meni!
{101305}{101371}Prokleta budala.|Znao sam da Êe to reÊi!
{101383}{101461}Ko je veÊa budala...sama budala|ili ona budala öto ide za njim?
{101696}{101800}Brod je vaö. Ako skeneri|neöto otkriju, odmah to prijavite.
{101840}{101891}Dobro, idemo.
{102243}{102295}Hej, tamo dole,
{102321}{102374}moûete li da nam|pomognete oko ovog?
{102608}{102660}TX-4-1-2. Zaöto nisi na svom mestu?
{102686}{102726}TX-4-1-2, da li me Ëujeö?
{103038}{103103}Preuzmi. Imamo loö predajnik.|VideÊu öta mogu da uradim.
{103546}{103651}Znaö, uz njegovo zavijanje i tvoju|pucnjavu na sve öto vidiö,pravo je|Ëudo da cela stanica ne zna gde smo.
{103664}{103755}Neka samo dou! Viöe volim|dobru tuËu nego ovo öunjanje.
{103768}{103859}-Pronaöli smo prikljuËak za kompjuter, ser.|-UkljuËite se. Trebalo bi da vidi celu| Imperijalnu kompjutersku mreûu.
{104159}{104250}Kaûe da je naöao kompjuter koji|upravlja napajanjem zraka koji drûi brod.
{104263}{104328}PokuöaÊe da precizira|lokaciju na monitoru.
{104342}{104419}VuËni zrak je vezan na glavni|reaktor na sedam mesta.
{104432}{104498}Nestanak napajanja na samo|jednom bi oslobodio brod.
{104575}{104641}Mislim da mi ne moûete pomoÊi.|Moram da krenem sam.
{104654}{104745}Kako kaûeö. VeÊ sam uËino|viöe nego za öta smo se pogodili.
{104758}{104836}-HoÊu da krenem sa tobom.|-Strpljenja, Luke.Ostani i Ëuvaj droide.
{104849}{104954}Moraju se saËuvati ili Êe i drugi|sistemi doûiveti sudbinu Alderaan-a.
{104979}{105045}Tvoja sudbina leûi na|stazi drugaËijoj od moje.
{105162}{105228}Sila Êe biti sa tobom...uvek!
{105462}{105513}U pravu si, Chewie.
{105541}{105645}-Gde si iskopao tog fosila?|-Ben je sjajan Ëovek.
{105658}{105722}-Da, sjajno nas je uvalio u nevolje.|-Nisam te Ëuo da ti neöto predlaûeö...
{105736}{105840}-Pa, sve je bolje nego da Ëekamo|da nas on oslobodi...|-äta ti msiliö...
{105879}{105958}-äta je?|-Bojim se da nisam siguran, ser.
{105970}{106035}Kaûe "Pronaöao sam je",|i stalno ponavlja, "Ona je ovde".
{106048}{106114}-Pa, koga...koga je naöao?|-Princezu Leiu.
{106126}{106179}-Princeza? Ona je ovde?|-Princeza? äta se ovde deöava?
{106192}{106243}Gde je ona?
{106388}{106452}5 nivo. Zatvorski blok A A-23.
{106584}{106635}Bojim se da je na listi za pogubljenje.
{106660}{106740}Oh, ne! Moramo neöto da uËinimo.
{106752}{106830}Ovi droidi su njeni. Ona je u poruci..|Moramo da joj pomognemo.
{106844}{106921}»uj, nemoj da ti svaöta pada na pamet.|Matori hoÊe da ga saËekamo ovde.
{107001}{107052}-NeÊu ja nigde.|-Oni Êe je pogubiti.
{107065}{107143}»uj, pre par trenutaka si rekao|da ne ûeliö da Ëekaö da te uhvate.|Sada hoÊeö da ostaneö
{107157}{107209}Nisam mislio na|uletanje u zatvorski blok.
{107222}{107286}-Ali oni Êe je ubiti!|-Bolje nju nego mene...
{107500}{107534}Bogata je.
{107599}{107625}Bogata?
{107650}{107742}Da. Bogata, moÊna! Sluöaj,|ako bi je ti spasao, nagrada bi bila...
{107755}{107821}-äta?|-Pa, viöe nego öto moûeö da zamisliö.
{107834}{107899}-Ne znam, mogu mnogo da zamislim!|-I dobiÊeö!
{107912}{107963}-HoÊeö...
{107963}{108016}Dobro, klinac.|Ali bolje da si u pravu.
{108029}{108082}-U redu.|-Kakav je plan?
{108108}{108159}Uh...3PO, daj mi te lisice.
{108212}{108238}OK.
{108276}{108329}Sada, staviÊu ti ih.
{108368}{108425}OK. Han, ti mu ih stavi.
{108446}{108512}Ne brini, Chewie.|Mislim da znam öta je smislio.
{108525}{108576}Gospodaru Luke !|Oprostite öto pitam...
{108589}{108668}ali, ah..öta da radimo ja|i R2 ako nas pronau ovde?
{108681}{108746}-ZakljuËajte vrata!|-I nadajte se da nemaju blastere.
{108759}{108811}To baö i nije umirujuÊe.
{110089}{110140}Niöta ne vidim od ölema.
{110935}{111001}-Ovo neÊe uspeti.|-Zaöto to ranije nisi rekao?
{111014}{111053}I jesam!
{111431}{111496}Kuda vodite tu...stvar?
{111509}{111560}Transfer zatvorenika|iz bloka 1-1-3-8.
{111613}{111678}Nisam obaveöten.|Moram da potvrdim.
{111873}{111926}RasturiÊe nas.
{112539}{112565}Pazi!
{112825}{112877}Moramo da naemo u kojoj|Êeliji je ta tvoja princeza.
{112891}{112968}Evo ga...Êelija 20-1-8-7.|Idi po nju. Ja Êu ih zadrûati.
{113099}{113151}Sve je pod kontrolom.|Situacija je normalna.
{113163}{113242}-äta se desilo?|-Uh...mali kvar na naoruûanju.
{113255}{113346}Ali, uh, sad je sve u redu.|Dobro smo. Ovde smo svi dobro, sada, hvala.
{113360}{113450}-Kako ste vi?|-äaljemo vod tamo.
{113464}{113541}Uh, uh, negativno.|Imamo curenje na reaktoru.
{113555}{113659}Dajte nam par minutra da ga|iskljuËimo. Veliko curenje...jako opasno.
{113672}{113725}Ko je to?|Koji je tvoj operativni broj?
{113789}{113868}I onako posatajalo dosadno.|Luke! ImaÊemo druötvo!
{114233}{114285}Nisi li malo nizak za vojnika?
{114310}{114351}äta? Oh...uniforma.
{114389}{114441}Ja sam Luke Skywalker.|Tu sam da vas spasim.
{114455}{114532}-Ti si ko?|-Tu sam da te spasim.Samnom je R2.|Tu sam sa Ben Kenobijem.
{114540}{114587}-Ben Kenobi je ovde! Gd je on?|-Hajde!
{114649}{114728}-On je ovde...|-Obi-Wan Kenobi!
{114753}{114819}-Zaöto tako mislite?|-Podrhtavanje u Sili.
{114832}{114924}Poslednji put sam to osetio|u prisustvu svog starog gospodara.
{114936}{115040}-On bi morao da je do sada mrtav.|-Ne potcenjujte Silu.
{115080}{115171}Dûedaji su izumrli, njihova|vatra se ugasila u univerzumu.
{115185}{115236}Vi, moj prijatelju, je sve|öto je ostalo od njihove religije.
{115289}{115379}Guverneru Tarkin, imamo uzbunu|u zatvorskom bloku A A-20-3.
{115406}{115457}Pronceza!|Stavite sve u stanje uzbune!
{115470}{115562}Obi-Wan je ovde.|Sila je sa njim.
{115574}{115627}Ako ste u pravu,|ne sme mu se dozvoliti da pobegne.
{115640}{115731}Nije ni planirao da beûi.|Moram se sam suoËiti sa njim.
{115966}{116005}Stani iza mene!|Stani iza mene!
{116422}{116500}-Tamo ne moûemo da izaemo.|-Izgleda da si uspeo da odseËeö sebi odstupnicu.
{116513}{116564}Moûda bi vam se viöe dopalo|da se vratite u svoju Êeliju,  VisoËanstvo.
{116617}{116644}3PO! 3PO!
{116683}{116748}OdseËeni smo!|Postoji li drugi izlaz iz zatvorskog odseka?
{116839}{116865}äta je to bilo?|Nisam razumeo!
{116891}{116969}Rekoh, svi sistemi su obaveöteni|o vaöem prisustvu, ser.
{116981}{117086}Glavni ulaz je jedini izlaz;|sve ostale informacije su nedostupne.
{117100}{117152}Otvorite!
{117190}{117218}Oh, ne!
{117243}{117282}Nema drugog izlaza.
{117394}{117451}Ne mogu zauvek da ih odbijam!|äta sada?
{117464}{117543}Sjajno spasavanje. Kada ste dolazili|niste imali plan da se izvuËete?
{117555}{117607}-On je mozak, duöo.|-Pa, ja nisam...
{117673}{117751}-Kuda Êeö dovraga?|-Neko mora da nas izvuËe.
{117816}{117895}U odvod za otpad, pametnjakoviÊu.
{118052}{118077}Ulazi, Ëupavi tikvane!
{118103}{118194}Briga me kako ti miriöe!
{118208}{118233}Ulazi i ne brini o tome.
{118324}{118365}Divna devojka!
{118411}{118475}Ili Êu je ubiti|ili Êe mi se dopasti.
{118533}{118559}Ulazi!
{118898}{118976}Oh! Odvod za otpad|je bio sjajna ideja.
{118989}{119067}Kakav si neverovatan miris otkrila!
{119133}{119185}Hajdemo odavde!|Sklanjas se odatle...
{119217}{119242}Ne! Stani!
{119393}{119459}HoÊeö da prekineö? VeÊ smo probali.|Magnetski je zapeËaÊeno!
{119471}{119523}Skloni to! Sve Êeö nas pobiti.
{119536}{119627}Svakako, Uzviöenosti. »uj, Sve sam imao pod|kontrolom dok nas nisi dovela ovde dole.
{119654}{119706}Znaö, neÊe im dugo trebati|da shvate öta nam se desilo.
{119713}{119758}Moûe biti i gore...
{119863}{119967}-I jeste gore. -Tu ima neöto ûivo!|-Privia ti se.
{119988}{120032}Neöto mi je dodirnulo nogu!
{120071}{120123}Vidi! Jesi li video?
{120136}{120161}äta?
{120710}{120749}Luke! Luke! Luke!
{121048}{121087}Luke, Luke, uhvati se za ovo.
{121100}{121179}-Pucaj ! ZakoËila mi se puöka.|-Gde?
{121204}{121232}Bilo gde! Oh!!
{121440}{121465}Luke! Luke!
{122052}{122077}Uhvati ga!
{122090}{122194}-äta se desilo?|-Ne znam, pustilo me je i nestalo...
{122364}{122417}Imam loö predoseÊaj.
{122573}{122639}-Zidovi se pomeraju!|-äta Ëekate.|Pokuöajte da ga poduprete neËim.
{123224}{123264}Stani malo!
{123329}{123381}3PO! Javi se 3PO!
{123420}{123473}3PO! Gde li je?
{123616}{123654}Preuzmi!
{123746}{123772}Pogledaj!
{123838}{123928}To su ludaci! Idu na zavorski|nivo. Ako poûurite, moûete ih uhvatiti.
{123942}{123967}Zamnom!
{124084}{124111}Ti Ëuvaj straûu.
{124241}{124267}Hajde!
{124476}{124554}Oh! Od ovog uzbuenja su mom|drugu pregorela kola.
{124567}{124632}Ako ne smeta, odveo|bih ga na popravku.
{124644}{124672}Dobro.
{124919}{125075}3PO! Javi se, 3PO! 3PO!
{125089}{125153}-Popni se na vrh!|-Ne mogu.
{125165}{125218}Gde li je? 3PO!
{125245}{125270}3PO, hoÊeö li se javiti?
{125310}{125362}Nisu tu! Neöto|mora da im se desilo.
{125374}{125427}Vidi da li su uhvaÊeni. Poûuri!
{125518}{125597}Jedno je sigurno.|Svi Êemo se stanjiti!
{125662}{125714}-Popni se na vrh!|-Pokuöavam!
{125870}{125935}Hvala Bogu, nisu ih naöli!|Gde li su?
{126000}{126040}Da upotrebim komlink?
{126052}{126104}Zaboravio sam|da sam ga iskljuËio!
{126208}{126274}-Jeste li tamo, ser?|-3PO!
{126287}{126353}-Imali smo problema...|-HoÊeö da umukneö i da me sasluöaö?
{126361}{126413}IskljuËi sve prese za otpad|na zatvorskom nivou, hoÊeö li?
{126417}{126509}Da li si Ëuo? IskljuËi sve prese za ubre|na zatvorskom nivou.
{126561}{126625}IskljuËi sve prese za ubre|na zatvorskom nivou.
{126639}{126705}Ne. Sve ih iskljuËi!|Poûuri!
{127095}{127160}Sluöaj ih! umiru, R2!
{127174}{127238}Prokleto metalno telo! Nisam bio dovoljno brz.| Za sve sam ja kriv! Jadni moj gospodar!
{127290}{127343}3PO, dobro smo!|Dobro smo. Dobro ste uradili.
{127369}{127459}Hej...hej, otvori poklopac u delu broj|... Gde smo to mi?
{127473}{127539}32-63-827!
{128698}{128776}Ako izbegavamo ûenske savete,|trebalo bi da se izvuËemo odavde.
{128790}{128815}Krenimo!
{128867}{128894}Kuda Êeö?
{128919}{128958}Ne, stani. »uÊe!
{129011}{129024}Dolazi ovamo, ti velika kukavice!
{129115}{129180}Sluöaj. Ne znam ko si,|niti odakle si doöao,
{129193}{129259}ali od sada, radiö po mome. OK?
{129284}{129336}Sluöaj, Vaöa Ogromnosti,|da raöËistimo neöto!
{129350}{129416}Meni nareuje samo jedna osoba! Ja!
{129441}{129480}»udo da si joö uvek ûiv.
{129480}{129558}HoÊe li neko da mi skloni|ovaj hodajuÊi tepih sa puta?
{129584}{129637}Nijedna nagrada|nije vredna ovog.
{129884}{129949}Daj mi regularni izveötaj.
{130014}{130093}-Da li znaö öta se deöava?|-Moûda je joö jedna veûba.
{130378}{130406}äta to bi?
{130431}{130497}Oh, niöta. Ne brini o tome.
{130653}{130705}-Eno ga.|-C3PO, da li me Ëujeö?
{130719}{130783}-Jeste li bezbedni?|-Trenutno.
{130795}{130851}Uh, u glavnom smo hangaru|naspram broda.
{130875}{130914}Mi smo iznad vas. SaËekajte.
{130940}{131031}-Doöao si u tome? Hrabriji si nego öto sam mislila.|-Fino! Hajde!
{131148}{131174}To su oni! Rasturite ih!
{131227}{131292}-VaraÊajte se na brod!|-Kuda Êeö? Vrati se!
{131304}{131369}-Hrabar je, to priznajem.|-äta nam to vredi ako pogine?
{132022}{132074}Mislim da smo pogreöno skrenuli.
{132203}{132243}Nema brave!
{132321}{132399}-To bi trebalo da ih zadrûi.|-Brzo, moramo preko.
{132412}{132477}-Nai kontrole koje puötaju most.|-Oh, Mislim da sam ih upravo sprûio.
{132491}{132504}Prolaze!
{133077}{133103}Evo, drûi to.
{133546}{133572}Evo ih, stiûu!
{133843}{133871}Za sreÊu!
{134524}{134562}Gde li su?
{134667}{134693}Zatvori vrata!
{134889}{134927}Otvori vrata! Otvori vrata!
{135397}{135501}»ekao sam na tebe, Obi-Wan.|Ponovo se sreÊemo, konaËno.
{135539}{135579}Krug je sada potpun.
{135592}{135696}Kada sam te napustio, bio sam|obiËan uËenik;Sada sam ja gospodar.
{135709}{135761}Samo gospodar zla, Darth.
{136269}{136308}Tvoje moÊi su slabe, starËe.
{136335}{136400}Ne moûeö pobediti, Darth.|Ako me i ubijeö,
{136408}{136504}postaÊu snaûniji viöe|nego öto bi mogao da zamisliö.
{136686}{136738}Nije trebalo da se vratiö.
{137391}{137429}Zar nismo upravo|napustili druötvo?
{137495}{137547}-Gde ste do sada?|-Naleteli smo na stare prijatelje.
{137560}{137612}-Je li brod dobro?|-Izgleda da jeste, ako doemo do njega.
{137618}{137676}Samo se nadaj da Êe matori|iskljuËiti taj zrak.
{138042}{138060}Vidi!
{138146}{138198}Hajde, R2, idemo!
{138238}{138277}Sada je naöa öansa! Napred!
{138360}{138381}Ben!
{138771}{138798}Ne!
{139019}{139071}-Hajde!|-Hajde!
{139111}{139181}-Luke, prekasno je!|-Pogodi vrata! DeËko!
{139424}{139462}Beûi, Luke! Beûi!
{139567}{139645}Nadam se da je matori iskljuËio zrak, ili Êe ovo biti najkraÊe putovanje.
{140479}{140518}Nailaze brodovi Ëuvari.
{140531}{140588}Zadrûi ih! Upravljaj ötitom dok ja|napunim glavne topove!
{140831}{140876}Ne mogu da verujem da ga nema.
{140988}{141078}-Nisi mogao niöta da uËiniö.|-Hajde, drugar, joö se nismo izvukli!
{141521}{141574}Spreman, deËko?|OK, budi na oprezu!
{141861}{141886}Evo ih!
{142329}{142368}Isuviöe su brzi!
{142576}{142668}-Izgubili smo boËne kontrole.|-Ne brini, izdrûaÊe.
{142708}{142760}»ujeö me, duöo? Izdrûi!
{143319}{143346}Imam ga! Imam ga!
{143359}{143398}Sjajno deËko!|Nemoj da se uobraziö.
{143450}{143476}Joö ih ima dvojica!
{144336}{144401}-To je to! uspeli smo!|-Usepli smo!
{144428}{144492}UpomoÊ! Topim se!|Za sve si ti kriv.
{144688}{144779}-Jesu li otiöli?|-Upravo su uskoËili u hipersvemir.
{144818}{144897}Sigurni ste da je odaöiljaË dobro|skriven na njihovom brodu?
{144922}{145014}Dosta riskiram ovim, Vader.|Bolje da upali.
{145054}{145092}nije loöe spasavanje,a?
{145105}{145171}Znaö, ponekad i sam sebe zadivim.
{145196}{145275}To i ne zvuËi tako teöko.|Pored toga, pustili su nas.
{145287}{145326}To je jedino objaönjenje|za ovo lako bekstvo.
{145339}{145457}-Lako...to je tebi lako? -Prate nas!|-Ne i ovaj brod, sestro.
{145496}{145548}Bar su podaci u R2-u Ëitavi.
{145562}{145600}äta je tako vaûno? äta to nosi?
{145627}{145679}TehniËke planove te stanice.
{145704}{145769}Samo se nadam da kada analiziraju|podatke da Êe naÊi neku slabost.
{145796}{145860}-Joö nije zavröeno!|-Jeste za mene, sestro!
{145874}{145952}Nisam u ovome zbog te revolucije,|i nisam ni zobg tebe, Princezo.
{145959}{146031}OËekujem da mi se dobro plati.|U ovome sam zbog novca!
{146041}{146103}Ne treba da brineö za nagradu.|Ako samo voliö novac,
{146109}{146161}onda Êeö to i dobiti!
{146239}{146330}Tvoj drug je pravi plaÊenik.|Pitam se da li mu je do iËega stalo
{146343}{146369}...ili do bilo koga.
{146382}{146413}Meni je stalo!
{146656}{146735}-Pa...öta misliö o njoj, Han?|-Pokuöavam da ne mislim, klinac!
{146774}{146799}Dobro...
{146891}{146943}Ipak, puna je duha.
{147007}{147073}Misliö da bi princeza i tip kao ja...
{147087}{147112}Ne!
{148298}{148363}Bezbedni ste!|Bojali smo se najgoreg.
{148376}{148429}Nemamo vremena|za tugovanje, komandante.
{148435}{148519}Morate upotrebiti informacije iz R2-a|da isplanirate napad. To nam je jedina nada.
{149080}{149132}-Da.|-Pribliûavamo se planeti Yavin.
{149144}{149197}PobunjeniËka baza je|na drugoj strani meseca.
{149210}{149249}Spremamo se da|uemo u orbitu planete.
{149471}{149537}Stanica je jako zaötiÊena
{149549}{149614}i ima bojevu moÊ veÊu|od polovine flote.
{149641}{149732}Njena odbrana je ispalanirana|za masovne napade.
{149758}{149862}Mali lovci-jednosedi bi trebalo|da probiju spoljnu odbranu.
{149926}{150005}Izvinite öto pitam, ser,|öta vrede lovci protiv toga?
{150018}{150122}Pa, Imperija ne smatra male|lovce za ozbiljnu pretnju,
{150135}{150187}ili bi imali guöÊu odbranu.
{150201}{150305}Analiza plana koji je donela|princeza Leia je pokazala
{150318}{150383}slabost u stanici.
{150396}{150447}Prilaz neÊe biti lak.
{150462}{150513}Treba da manevriöete|kroz ovaj prolaz
{150527}{150579}i kreÊete se po samoj|povröini do ove taËke.
{150604}{150670}Meta je öiroka samo 2 metra.
{150684}{150774}To je mali toplotni izduvni prikljuËak,|Odmah ispod glavnog prikljuËka.
{150806}{150865}Ovaj prolaz vodi direktno|do sistema reaktora.
{150879}{150983}Precizan pogodak Êe zapoËeti|lanËanu reakciju koja bi trebalo da uniöti celu stanicu.
{151009}{151073}Samo Êe precizan pogodak|zapoËeti lanËanu reakciju.
{151101}{151177}Otvor ötiti zrak, pa Êete|morati da koristite protonska torpeda.
{151192}{151269}-To je nemoguÊe, Ëak i sa kompjuterom.|-Nije nemoguÊe.
{151282}{151373}Gaao sam pacove u moËvari u mojem|T-16 kod kuÊe. Ni oni nisu bili mnogo veÊi.
{151399}{151478}Ukrcajte se na brodove!|I neka Sila bude sa vama!
{151686}{151751}U orbiti smo planete|maksimalnom brzinom.
{151765}{151843}Mesec sa bazom pobunjenika Êe biti|u dometu za 30 minuta.
{151856}{151921}Ovaj dan Êe se dugo pamtiti.
{151935}{151973}Video je kraj Kenobija
{151986}{152052}i uskoro Êe videti kraj pobune.
{152195}{152220}Svi piloti, zauzmite mesta.
{152286}{152312}Svi piloti, zauzmite mesta.
{152429}{152481}Pa...dobio si nagradu|i sada odlaziö?
{152494}{152520}Tako je, da!
{152566}{152625}Imam da ovim otplatim|neke stare dugove.
{152637}{152703}»ak i da nisam, misliö da bih|bio toliko lud da ostanem ovde sa tobom?
{152755}{152821}Zaöto ne kreneö sa nama?|Dobar si pilot. Koristio bi nam.
{152833}{152937}Hajde! Zaöto ne pogledaö oko sebe?|Znaö öta Êe se dogoditi.Znaö protiv Ëega se bore
{152963}{153042}Trebao bi im dobar|pilot kao ti. OkreÊeö im lea.
{153054}{153106}äta vredi nagrada|ako nisi ûiv da je iskoristiö?
{153120}{153198}Pored toga, ovaj napad na|stanicu mi ne liËi na hrabrost.
{153224}{153250}Viöe liËi na samoubistvo.
{153302}{153406}Dobro. Pa, Ëuvaj se, Han.|U tome si najbolji, zar ne?
{153459}{153485}Hej, Luke...
{153563}{153602}neka Sila bude sa tobom!
{153784}{153851}äta ti gledaö? Znam öta radim.
{154266}{154305}-äta nije u redu?|-Oh, to je Han!
{154319}{154371}Ne znam, stvarno|sam mislio da se predomislio.
{154385}{154461}Mora da ide svojim putem.|Niko mu ga ne moûe izabrati.
{154496}{154553}éeleo bih da je Ben ovde.
{154879}{154944}-Luke!|-Biggs!
{154953}{155010}Kako si?
{155023}{155087}LeteÊu sa tobom!|Sluöaj, imam toliko da ti priËam...
{155100}{155127}Skywalker!
{155166}{155219}Siguran si da moûeö da|upravljaö tim brodom?
{155231}{155288}Ser, Luke je najbolji|niskoletaË sa periferije.
{155320}{155375}-SnaÊi Êe se odliËno.|-Hvala, ser. PokuöaÊu.
{155387}{155452}Moram da se ukrcam.|Sluöaj, priËaÊemo kada se vratimo. Vaûi?
{155483}{155544}Rekoh ti da Êu jednom uspeti, Biggs.
{155556}{155622}BiÊe kao nekad,|nikada nas neÊe zaustaviti.
{155700}{155764}Ovaj R2 izgleda priliËno izubijano.|éelite li novog?
{155779}{155844}Ni za ûivu glavu! Taj mali|droid i ja smo proöli mnogo zajedno.
{155856}{155883}Dobro si, R2?
{155921}{155939}Dobro.
{156068}{156126}Drûi se, R2, moraö se vratiti.
{156196}{156247}Ne bi hteo da mi ûivot|postane dosadan, zar ne?
{156248}{157459}www.Diveks.tk
{157460}{157512}Luke, Sila Êe biti uz tebe.
{157832}{157902}Uzbuna.|Zvezda Smrti se pribliûava.
{157916}{157994}Vreme do ulaska|u domet, 15 minuta.
{158319}{158346}Neka se svi lovci jave.
{158359}{158405}-Crveni 10 spreman.|-Crveni 7 spreman.
{158410}{158458}-Crveni 3 spreman.|-Crveni 6 spreman.
{158468}{158521}-Crveni 9 spreman.|-Crveni 2 spreman.
{158522}{158601}-Crveni 11 spreman.|-Crveni 5 spreman.
{158646}{158697}Postavite krila u poloûaj za napad.
{158802}{158868}-Prolazimo kroz magnetsko polje.|-Drûite se!
{158880}{158932}UkljuËite ötitove.|Dupli prednji!
{159049}{159076}-Vidi kolika je ta stavr!|-Prekini priËu, Crveni 2.
{159089}{159140}Ubrzajte do brzine za napad.
{159224}{159285}-To je to, momci!|-Crveni Voo, ovde Zlatni Voa.
{159297}{159336}-»ujem, Zlatni Voo.
{159349}{159427}KreÊemo na metu.|Na poloûaju smo.
{159831}{159896}Jaka paljba, öefe! 20 stepeni.|Vidim. Ostanite nisko.
{160091}{160123}Ovde Crveni 5.| KreÊem!
{160248}{160275}Luke, diûi se!
{160313}{160366}-Jesi li dobro?|-Bilo je blizu, ali dobro sam.
{160522}{160613}Izbrojali smo 30 brodova, Lorde Vader.|Ali su tako mali da izbegavaju naöe turbo-lasere!
{160626}{160704}Moramo ih uniötiti lovcima.|Spremite posade za lovce.
{160783}{160900}-Pazi se! Sa desne stran eje jaka|paljba sa tog tornja.|-Vidim.
{160913}{161005}-KreÊem, pokrivaj me Parkins!|-Uz tebe sam, Crveni 3!
{161154}{161187}Ima problema...
{161213}{161277}-Diûi se|-Ne, dobro sam...
{161408}{161473}Baza pobunjenika|Êe biti u dometu za 7 minuta.
{161578}{161655}Luke, veruj svojim oseÊanjima!
{161851}{161930}Voe odreda, hvatamo nove signale.
{161943}{162020}-Stiûu vam neprijateljski lovci.|-Nema niöta na radaru. Ne vidim ih.
{162034}{162086}-UkljuËite vizuelno praÊenje.|-Evo ih.
{162164}{162216}Pazi, jedan ti je na repu.
{162347}{162373}Pogoen sam!
{162412}{162464}-ZakaËio si jednog...pazi!|-Ne vidim ga!
{162516}{162555}Baö mi se zakaËio,|ne mogu da mu pobegnem.
{162607}{162633}Stiûem.
{162958}{163050}Nekoliko lovaca se izdvojilo|iz glavne grupe. Krenite zamnom!
{163194}{163259}»uvaj lea! Lovac iznad tebe, napada!
{163428}{163493}Pogoen sam, ali nje straöno.|R2, vidi öta moûeö da uradiö.
{163571}{163624}Crveni 6 vidiö Crvenog 5?
{163632}{163684}Ovde je teöka paljba.|Crveni 5, gde si?
{163697}{163728}Ne mogu da mu pobegnem!
{163820}{163858}Imam ga, Luke!
{163949}{163980}Biggs, gde si?
{164171}{164210}-Hvala, Wedge.|-Dobar pogodak, Wedge!
{164236}{164306}Crveni Voo,ovde Zlatni Voa.|KreÊemo u napad.
{164353}{164411}Razumeo, Zlatni Voo.|Zauzmite poloûaj.
{164470}{164510}Zadrûite formaciju za napad!
{164536}{164602}Izduvni otvor je...
{164797}{164901}Prebacite snagu na prednje ötitove.
{165026}{165068}Koliko topova misliö|da ima, Zlatni 5 ?
{165078}{165135}Rekao bih oko 20.|Neki na povröini, neki na tornjevima.
{165148}{165214}Zvezda Smrti Êe biti|u dometu za 5 minuta.
{165279}{165331}UkljuËujem kompjuter za gaanje.
{165417}{165461}Kompjuter naniöanio.|Hvatam signal.
{165540}{165578}Topovi...prestali su!
{165622}{165683}Stabilizujte zadnje ötitove.|Pazite na neprijateljske lovce.
{165709}{165749}Napadaju! Trojica na 2 i 10.
{165808}{165878}-Ja Êu na njih! Pokrivaj me!|-Da, ser.
{166256}{166322}-Ne mogu da manevriöem!|-Preblizu smo.
{166326}{166366}-Preblizu smo.|-Pazi na metu!
{166413}{166438}Odvajaj se!
{166506}{166577}Zlatni 5 Crvenom Voi...|Izgubli smo Tireea, izgubili smo Dutcha.
{166587}{166647}-Razumeo, Zlatni 5.|-Doöli su otpozadi....
{166804}{166868}Analizirali smo napad, ser,|i postoji opasnost.
{166881}{166942}-Da vam spremim brod?|-Evakuacija?
{166951}{167024}u trenutku naöeg trijumfa?|Mislim da precenjujete njihove öanse!
{167077}{167116}Baza pobunjenika,|3 minuta i odbrojavanje.
{167151}{167189}Crvena Grupo,|ovde Crveni  Voa.
{167194}{167233}SakupiÊemo se na taËki 6.1.
{167247}{167305}-Ovde Crveni 2. Idem prema tebi.|-Crveni 3, spreman.
{167337}{167377}Crveni Voo, ovde Baza 1.
{167389}{167434}Ostavite pola grupe|van dometa za sledeÊi napad.
{167447}{167497}Razumeo, Bazo 1.|Luke, uzmi Crvenog 2 i 3.
{167507}{167573}Ostani tu i saËekaj|signal da kreneö u napad.
{167815}{167841}To je to!
{167953}{167992}Sada bi trebalo da to vidimo.
{168046}{168098}Pazite na neprijateljske lovce!
{168141}{168195}Ima isuviöe smetnji!|Crveni 5, vidiö li ih odatle?
{168204}{168253}Nema znaka...stani!|Stiûu iz pravca 3-5.
{168309}{168336}Vidim ih.|U dometu sam.
{168374}{168401}Nailazi meta!
{168480}{168536}Samo ih zadrûite par sekundi.
{168563}{168588}Zatvorite formaciju.
{168641}{168667}Skoro smo tu!
{168901}{168993}-Bolje ga ispali.
{169019}{169050}Ne mogu da ih zadrûim!
{169266}{169293}Ispaljeno!
{169397}{169488}-Pogodak!|-Negativno. Negativno! Nije uölo.
{169502}{169546}Ekplodiralo je na povröini.
{169723}{169827}Crveni Voo, iznad vas smo.| Preite na 0.5;pokrivaÊemo vas.
{169839}{169894}Ostani tu, ugasio mi se desni motor.
{169931}{169977}Spremi se za napad.
{170308}{170374}Baza pobunjenika,|1 minut i odbrojavanje.
{170400}{170465}Biggs, Wedge,|hajde da zavröimo to.
{170478}{170544}-Idemo punim gasom.|-Uz tebe smo, öefe.
{170583}{170635}Luke, hoÊeö li moÊi|da se izvuËeö pri toj brzini?
{170648}{170674}BiÊe kao Kanjon Prosjaka kod kuÊe.
{170870}{170921}BiÊemo dalje pozadi da te pokrivamo.
{170930}{170982}Na radaru vidim toranj,|ali ne vidim izduvni otvor!
{170995}{171038}Siguran si da kompjuter|moûe to da pogodi?
{171117}{171197}-Pazi se! Dodaj gas do daske!|-äta je sa tornjem?
{171213}{171266}Ti brini o lovcima!|Ja Êu brinuti o tornju!
{171430}{171521}R2...taj, taj stabilizator se opet otkaËio!|Vidi da li moûeö da ga stegneö!
{172017}{172042}Pogoen sam!
{172056}{172133}-Izvuci se, Wedge.|Ne moûeö viöe niöta da pomogneö!|-éao mi je!
{172173}{172213}Pustite ga! Pratite vou!
{172289}{172346}Poûuri, Luke, sada dolaze brûe|Ne mogu da ih zadrûim!
{172451}{172485}R2, pokuöaj da|pojaËaö napajanje!
{172654}{172681}Poûuri, Luke!
{172706}{172733}Stani!
{172902}{172960}Baza pobunjenika, 30 sekundi i odbrojavanje .
{172986}{173012}Pratim vou.
{173098}{173128}Drûi se, R2!
{173528}{173571}Upotrebi Silu, Luke.
{173658}{173684}Prepusti se, Luke.
{173749}{173788}Sila je jaka u ovom!
{173809}{173841}Luke, veruj mi.
{173984}{174062}Kompjuter mu ne radi. Luke,|iskljuËio si kompjuter za gaanje.
{174075}{174141}-äta nije u redu?|-Dobro sam.
{174487}{174518}Izgubio sam R2-a!
{174558}{174646}Zvezda Smrti je proöla pored planete.|Zvezda Smrti je proöla pored planete.
{174696}{174744}Baza pobunjenika, u dometu.
{174753}{174782}Pucajte Ëim budete spremni.
{174805}{174844}PoËnite primarno paljenje.
{175196}{175222}Sada si moj.
{175285}{175311}äta?
{175573}{175639}Slobodan si, deËko.|Rasturi ovo i idemo kuÊi!
{175821}{175848}Spremni.
{175938}{175965}Spremni.
{176226}{176278}Sjajan pogodak, klinac.|Jedan u milion.
{176317}{176405}Zapamti,|Sila Êe biti uz tebe...uvek.
{177033}{177098}-Hej! Hej!|-Znao sam da Êeö se vratiti!|Prosto sam znao!
{177112}{177151}Pa, Nisam hteo da sam|pokupiö svu slavu i nagrade.
{177159}{177211}Hej, znao sam da tu|ima joö neöto osim novca.
{177268}{177359}Oh, Boûe! R2!|»ujeö li me? Kaûi neöto!
{177385}{177464}-Moûete li da ga popravite?|-Odmah poËinjemo.
{177477}{177568}Morate ga popraviti!|Ako bude potrebno neko kolo,|daÊu mu svoje drage volje.
{177581}{177606}BiÊe dobro.
{177677}{178511}www.Diveks.tk|isporuka na kuÊnu adresu
{178536}{180036}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/a69mq|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
