{1}{1}25.000
{26}{176}-== [ www.OpenSubtitles.com ] ==-
{1805}{1844}INSPEKTOR CHAN
{2641}{2712}SUPER BORCI PROTIV ZLO»INA
{2977}{3028}Joö netko?
{3213}{3277}Tako lijepa ûena...
{3281}{3360}...a vi je uhitite...
{3365}{3430}...samo zbog pljuvanja?
{3458}{3524}Zar nema pravde?
{3541}{3602}Zar nema zakona?
{3625}{3689}Vaö öef je naËelnik...
{3693}{3754}...samo zato öto plaÊa | Krokodilskoj bandi.
{3773}{3830}A ti me ne poznajeö?
{3843}{3921}Oprostite, nisam znao | da vam je supruga.
{3979}{4020}Kukavice ruûna!
{4267}{4344}äto ti gledaö? Nikad nisi vidio | tako zgodnog öefa bande?
{4509}{4566}Tko bi ûelio biti | u filmskom poslu?
{4571}{4636}Nedjelja je, a kino je prazno.
{4657}{4692}Gdje je auto?
{4965}{5000}Vratimo se unutra.
{5517}{5554}Zovite pomoÊ!
{5605}{5669}Nema potrebe za tim, | sjevernjaËe.
{5673}{5801}Dok si se igrao s murjakom, | tvoji su ljudi preöli k nama.
{5834}{5904}Pobit Êu sve vas Sjekiraöe!
{6711}{6812}Stani! SjeÊaö se kad | sam te Ëastio veËerom?
{7077}{7104}Brate Sum.
{7290}{7316}Molim te...
{7359}{7398}Molim te, poötedi me.
{7413}{7456}Ne brini se.
{7471}{7561}Ne ubijam ûene. Moûeö iÊi.
{7581}{7620}Hvala, Veliki Brate.
{7957}{8017}Murjaci! | PoËistite nered!
{9892}{9980}BANDA SJEKIRAäA
{10033}{10046}U doba socijalnih nemira | i nereda vladaju bande.
{10046}{10079}U doba socijalnih nemira | i nereda vladaju bande.
{10084}{10150}Najstraönija od svih | je banda Sjekiraöa.
{10155}{10212}Samo u najsiromaönijim | Ëetvrtima...
{10217}{10308}...koje bandama nisu zanimljive...
{10313}{10352}...ljudi mogu ûivjeti | u miru.
{10413}{10452}ULICA SVINJAC
{10956}{10991}Jedan, dva, tri!
{11017}{11060}- U redu je, NadniËaru? | - Nema problema!
{11496}{11528}KROJA»
{11633}{11666}TJESTENINA
{12165}{12227}RaËun, Krafno.
{12285}{12368}- Koliko? | - KuÊa Ëasti.
{12374}{12401}Krafno.
{12406}{12461}- Niöta. | - Sviaö mi se.
{12466}{12537}Pitat Êu ûenu da ti smanji najamninu.
{12577}{12619}Dobro jutro, gazda!
{12669}{12692}Gazda!
{12697}{12736}Jill! Narasla si!
{12741}{12793}Doi da te pregledam!
{13097}{13152}Lijepo je vidjeti vas, gazda!
{13157}{13192}äto je lijepo u tome?
{13197}{13224}Nemojte!
{13365}{13493}Moûeö li malo skratiti koöulju?
{13509}{13544}Dakako!
{13549}{13584}Vidi, komet!
{13669}{13704}Jane! | ZloËesta si!
{13709}{13797}Gazda, baö ste mangup!
{13849}{13968}Ne idi, Jane! Razgovarajmo!
{13977}{14052}Samo se öalim. Jane!
{14544}{14576}Gazdarice!
{14597}{14632}Gazdarice!
{14706}{14766}äto je s vodom?
{15113}{15140}Voda nije | besplatna!
{15145}{15246}Puno govoriö za nekoga | tko ne plaÊa stanarinu.
{15251}{15339}Ali usred öamponiranja sam.
{15344}{15378}Pa öto?
{15383}{15455}Odsad, nema vode ponedjeljkom, | srijedom i petkom.
{15460}{15529}Voda samo utorkom, | Ëetvrtkom i subotom.
{15534}{15650}Volim sluöati kako se ûalite. äupci!
{15655}{15683}Dobro jutro, | gazdarice!
{15688}{15789}Plati najamninu ili Êu ti | spaliti trgovinu.
{15807}{15882}äto je smijeöno? Stanarina | nije smijeöna, pederu!
{15930}{16024}Tako ti i treba kad si nadniËar!
{16029}{16105}Mjesecima kasniö, | a ne kaûeö ni 'dobro jutro'.
{16110}{16154}Bit Êeö nadniËar | cijeli ûivot.
{16298}{16342}Evo ti, ljepotane!
{16437}{16495}Gdje si tako dugo?
{16500}{16568}Pomagao sam starici | da prijee ulicu.
{16573}{16639}- äto onda radiö ovdje? | - Traûim öpijune.
{16644}{16696}Je li te tko öpijunira, | teta äest?
{16701}{16786}Ne blebeÊi bez dokaza.
{16861}{16931}Luda je.
{17712}{17752}Odlazi!
{18209}{18266}Moûete li nas nauËiti?
{18271}{18296}Dosta nogometa!
{19167}{19220}- Tko ûeli öiöanje? | - Moj öef.
{19285}{19312}Sjednite.
{19573}{19632}Gotovo! 50 centa, molim.
{19669}{19706}Zar nije sjajno?
{19713}{19748}Predobro je!
{19770}{19821}Zaöto si ga uËinio | tako lijepim?
{19839}{19872}Zaöto?
{20050}{20137}Ne ljutite se, öefe. On mi je | stari prijatelj. Sredit Êu to.
{20186}{20273}On je öef bande Sjekiraöa. | Ne vidiö sjekire? Opaki smo.
{20278}{20346}Loöe je ako dobro izgleda. | Razumijeö?
{20350}{20404}- Nisam znao. | - Tupavac si!
{20411}{20496}Ali sviaö mi se. | Plati mi i ja Êu sve srediti.
{20501}{20525}Nema öanse!
{20581}{20670}Polako sa sjekirom, öefe. | Razgovarat Êu s njim.
{20723}{20808}Stalo mi je do tebe. | I sam si vidio. Ozbiljno.
{20813}{20916}Zaöto ne platiö? Ne puno. | Dovoljno za piÊe.
{20921}{20972}ZnaËi, ucjena.
{21017}{21048}äefe!
{21069}{21096}äefe!
{21189}{21264}Sad si mrtav.
{21269}{21328}»ini se da se budi.
{21333}{21364}Ne bojim se.
{21369}{21416}Moûete me ubiti.
{21421}{21501}Ali bit Êe ih joö tisuÊe poput mene!
{21580}{21657}HoÊete igrati grubo? äef bande | Sjekiraöa drijema unutra.
{21662}{21704}Svi koji ûele umrijeti | neka istupe.
{21760}{21817}éelite borbu?
{21822}{21895}Izvrsno! Borit Êemo se | jedan na jednoga.
{21900}{21975}Nemojte ni pomiöljati na varanje.
{21985}{22023}Ona starica s lukom!
{22081}{22209}Izgledaö opasno. | éeliö borbu? Udari prva.
{22321}{22354}»ime se baviö?
{22359}{22400}Zemljoradnica sam.
{22405}{22488}Zemljoradnici se ne bore. | Nestani!
{22493}{22524}Lud je.
{22529}{22566}Vrijeaö me?
{22570}{22632}Imaö sreÊe öto si ûena.
{22661}{22786}Hej, kratki! Da, ti! | Ako si kratak, nisi patak.
{22859}{22952}äto sam rekao za varanje?
{22957}{22986}Sjedni!
{23059}{23123}Ti s naoËalama. | Izgledaö opasno.
{23200}{23274}Ne, ne ti. Mislio sam...
{23279}{23305}Ti!
{23310}{23376}Mali, u borbu!
{23423}{23466}U redu, u redu!
{23474}{23559}Danas nema borbe.
{23564}{23616}Svi ste mlakonje!
{23685}{23736}On me ucjenjivao.
{23746}{23821}Debela, ti si ovdje glavna?
{23826}{23868}Kakva debela?!
{23874}{23945}- Ja sam u bandi Sjekiraöa! | - Kakva banda Sjekiraöa?!
{23951}{23974}äefe!
{23979}{24016}Kakav öef?!
{24023}{24075}- Moraö platiti naöe lijeËenje! | - Kakvo lijeËenje?!
{24080}{24133}- Na istoj smo strani! | - Kakva ista strana?!
{24222}{24284}Misliö da si opasna? | Zvat Êu pojaËanje!
{24291}{24396}Glupane! Da vidim to pojaËanje!
{24429}{24516}Ne znaö kakvo pojaËanje imam. | Govorim o cijeloj vojsci.
{24553}{24664}Nemoj pobjeÊi. | Uplati vlastiti lijes!
{24989}{25022}Tko je bacio | petardu?
{25172}{25207}Ja sam vaö, brate.
{25744}{25779}Gledajte svoja posla!
{25784}{25867}Pada kiöa. Unesite rublje!
{25874}{25904}Debela!
{26217}{26319}I vi me ucjenjujete? Ne bojim se.
{26711}{26734}Ja...
{27206}{27278}Je li tko vidio öto se dogodilo?
{27303}{27367}Nemojte! | Slomljena mi je kiËma!
{27385}{27449}Zovite pomoÊ!
{28727}{28809}»ekajte, polako. Jeste li gladni?
{29417}{29446}Tiöina.
{29819}{29852}Ne.
{30423}{30460}Tko je ovo uËinio?
{30553}{30598}Brojat Êu do tri.
{30667}{30694}Jedan...
{30781}{30828}...dva...
{31104}{31131}Ja sam to uËinio!
{35871}{35916}Je li roba dobra, | brate Sum?
{35969}{35997}Oprostite.
{36073}{36120}Ne gledaj, mali.
{36224}{36255}Rijeöite ga se!
{36289}{36336}Mi smo negativci!
{36341}{36388}Mi trebamo razvaljivati...
{36413}{36463}...a ne obratno.
{36468}{36547}I to sve zato öto su ti | kreteni glumili Sjekiraöe.
{36552}{36628}Ne gubite vrijeme, brate Sum.
{36633}{36699}Mi Êemo to rijeöiti.
{36704}{36748}Ti! Sredi to.
{37088}{37208}- Kako ovaj zna obijati brave. | - Od toga ûivim.
{37213}{37277}Obij i onu ako si tako dobar.
{37287}{37310}Doi.
{37328}{37394}Brojat Êu do tri.
{37414}{37438}Poûuri se!
{37482}{37525}Spreman? Tri!
{37764}{37806}To je bilo brzo!
{37839}{37899}Brate Sum, mi doista | ûelimo biti Sjekiraöi.
{37904}{37972}Zato smo ono uËinili. | Dajte nam priliku.
{37981}{38012}Jeste li ikada | nekoga ubili?
{38017}{38076}Uvijek sam razmiöljao o tome.
{38086}{38120}Onda idi i ubij | nekoga.
{38125}{38171}HoÊu!
{38205}{38229}Hajde!
{38240}{38275}Hvala, brate Sum.
{38553}{38636}Takve uvijek moûemo | za neöto iskoristiti.
{38718}{38786}VeÊ sam ti rekao. | Moraö izgledati opasno.
{38790}{38825}Opasnije!
{38858}{38900}Opasnije!
{38950}{38987}Uûivi se u ulogu.
{38992}{39063}- I pokuöaj ostati budan. | - Biti opasan je zamorno.
{39068}{39141}Zamorno? Od toga ûivimo!
{39169}{39257}Ulice su pune novca i ûena.
{39262}{39328}Trebaö samo volju i odluËnost...
{39332}{39411}...da iskoristiö priliku | za pobjedom.
{39419}{39456}Ovo je naöa prilika!
{39461}{39525}Moramo samo nekoga ubiti | i u bandi smo.
{39537}{39620}Onda Êemo biti puni novca i ûena!
{39643}{39711}NeÊemo biti kao prosjaci.
{39717}{39781}Bez ambicija.
{39901}{39976}Koga gledaö, Ëetverooki? | Razbit Êu ti naoËale!
{40010}{40048}Gubi se!
{40059}{40090}Vrati se i ponovi to!
{40095}{40146}- Doista Êeö nekoga ubiti? | - Tako je!
{40151}{40236}»etverookog, debelu i | sve stanovnike Svinjca.
{40241}{40283}Ali dobri su u kung fuu.
{40288}{40356}- I ja znam kung fu! | - Da?
{40407}{40494}Zar ti nisam rekao da znam | kung fu BudistiËkog dlana?
{40538}{40620}Lijepi djeËaËe, stani.
{40661}{40726}»udesno!
{40737}{40838}Znaö li da imaö posebnu auru?
{40853}{40935}Tako si mlad, ali imaö | strukturu kostiju...
{40940}{41020}...i chi kung fu genija.
{41035}{41136}Uspijeö li usmjeriti svoj chi, | bit Êeö nepobjediv!
{41140}{41224}Kao öto stara izreka kaûe: | "Ne moûeö pobjeÊi sudbini."
{41237}{41350}Duûnost Ëuvanja svjetskog mira | i kaûnjavanja zla je tvoja.
{41365}{41388}Moûe.
{41411}{41492}Ovo je svitak BudistiËkog | dlana. Neprocjenjiv je.
{41497}{41581}No buduÊi da je takva sudbina, | dajem ti ga za 10 dolara.
{41638}{41685}PRIRU»NIK BUDISTI»KOG DLANA
{41781}{41841}- Dao si mu svoju ûivotnu uöteevinu? | - Da.
{41846}{41924}ätedio sam da postanem | lijeËnik ili odvjetnik...
{41929}{41985}...ali ovo je bio mir u svijetu.
{42562}{42617}Pustite djevojku!
{43069}{43136}Pa to je BudistiËki dlan!
{43145}{43196}'PriruËnik za kung fu | od 20 centa.'
{43201}{43242}Sigurno imaö love.
{43253}{43304}Jesi li ubio koga | u zadnje vrijeme?
{43575}{43692}On je glup, a ona je mutava. | Gubitnici!
{43735}{43826}Tada sam shvatio da pozitivci | ne pobjeuju. éelim biti loö.
{43847}{43896}éelim biti ubojica!
{43929}{43980}- Sladoled! | - Gdje?
{44001}{44042}Ja Êu vaniliju.
{44047}{44080}»okolada za mene!
{44357}{44428}äto gledaö? Nikad nisi vidjela | besplatan sladoled?
{44559}{44586}Gledaj | kako trËi!
{44955}{45083}Baö ste majstori kung fua. | Izaite na ulicu.
{45087}{45142}Mjesto vam je u cirkusu, | a ne ovdje!
{45147}{45248}Nemojte tako, gazdarice. | Sigurno su s razlogom ovdje.
{45256}{45312}Svi imaju svoje razloge.
{45317}{45366}Ne ûelimo stvarati probleme.
{45371}{45435}Drago mi je da shvaÊate. | Mafija se ljuti na nas.
{45440}{45514}Ovo nikada neÊe zavröiti. | Zaöto se ne izgubite?
{45541}{45594}Vaöa ûena ne bi trebala | biti tako zloËesta.
{45649}{45692}Dobro ste?
{45740}{45776}Majstori.
{45959}{46006}Nemamo niöta | dragocjeno za vas, ali...
{46011}{46066}...primite ovo kao znak | naöe zahvalnosti.
{46088}{46132}Hvala öto ste nas spasili!
{46319}{46390}Prestani plakati. | Ovo nije predstava!
{46395}{46480}- Ledenog ste srca. | - Odgovaraö mi?
{46485}{46551}Moûda znaö kung fu, | ali i dalje si peder.
{46612}{46680}Nije zloËin znati kung fu!
{46685}{46751}Jednom peder, uvijek peder.
{46756}{46840}Pogledaj se. | »emu crveno donje rublje?
{46845}{46904}Zaöto nemaö pelenu, | kad smo veÊ kod toga.
{46935}{46983}äto nedostaje crvenom | donjem rublju?
{46989}{47056}Gdje ste vi bili | kad je bila frka?
{47061}{47156}Da nije bilo njih, bili bismo | gotovi. Budite razumni.
{47161}{47196}Urazumit Êu ja tebe.
{47201}{47278}Dugujete mi tri mjeseca | stanarine. To je 90 dolara.
{47283}{47336}Platite ili se pakirajte!
{47341}{47392}Ne brinite se, | platit Êu za vas.
{47397}{47456}Misliö da si pametna, | Jane ZeËji Zubi?
{47461}{47525}Zaöto pitaö, vreÊo sala?
{47529}{47556}Kujo!
{47584}{47623}Smirite se, gazdarice.
{47657}{47706}Vi ste krivi za ovo.
{47761}{47815}- éelite nas ubiti? | - Imaö pravo.
{47820}{47871}Kako ste mogli?
{47876}{47921}Tiöina!
{48237}{48290}Mislite da mene | moûete nadvikati?
{48389}{48455}Debela zbilja zna pjevati.
{48481}{48516}Gledaj ovo!
{48875}{48903}äto se dogodilo?
{48913}{48982}Kako to misliö, öto se | dogodilo? Pokuöaj ti.
{48987}{49033}- Ja? | - Brzo!
{49173}{49227}Oprosti. Dobro si?
{49246}{49325}Mislim da se trebaö pribliûiti | i bolje naciljati. Dobro?
{49330}{49353}Dobro!
{49647}{49711}- Tko baca dröke? | - Dröke?
{49762}{49808}Gdje je treÊi noû?
{49825}{49883}Tko zna kamo je odletio.
{49888}{49946}Moûe li to biti ovaj? | NemoguÊe...
{49951}{49992}- Nemoj! | - Oprosti.
{50045}{50088}éeliö neöto reÊi?
{50093}{50192}Upravo sam se sjetio da | imam nekog posla. Vidimo se!
{50256}{50304}Vidjeli su nas!
{50341}{50376}Odmakni se!
{50584}{50681}Ne paniËari! Zmije vole glazbu. | Ako zviûdim, neÊe gristi.
{50686}{50723}Molim te. Dosta | pametnih ideja.
{50822}{50856}Ma, zaöto ne!
{51020}{51056}Opet ti, seronjo!
{51061}{51141}Gledajte svoja posla!
{51186}{51221}Razdvojimo se!
{51277}{51304}Razdvajanje?
{54492}{54523}äto radiö tu?
{54528}{54579}Traûio sam te. | Zar nisi bio ozlijeen?
{54584}{54612}Dobro sam!
{54662}{54731}Kako to da se uvijek | tako brzo oporaviö?
{54740}{54775}Ne znam.
{54785}{54847}- U koju si bolnicu iöao? | - Ne sjeÊam se.
{54866}{54904}Moûda je tako bolje.
{54909}{55021}SjeÊanja mogu biti bolna. | Blagoslov je zaboraviti ih.
{55026}{55094}Nisam znao da si tako dubokouman.
{55124}{55183}Sva tuga koju Ëovjek | moûe podnijeti...
{55375}{55452}...odlazi niz neku rijeku.
{55507}{55544}MiËite se s puta!
{55549}{55579}MiËite se!
{55584}{55623}äamarat Êu vas do | kraljevstva nebeskog!
{55633}{55724}Vidi Ëetverooke kako nose lijes.
{55769}{55804}Kakvi idioti!
{55856}{55907}Nemojte mene kriviti | öto vas tjeram.
{55912}{56008}Neka Buda odluËi...
{56024}{56080}...hoÊete li ostati...
{56085}{56143}...ili otiÊi.
{56237}{56284}STRAHOVITO LOäA SUDBINA
{56573}{56614}Popijte malo Ëaja.
{56788}{56860}Zahvalni smo za | profesionalnu pomoÊ.
{56865}{56952}ShvaÊamo problem. | 12 Udaraca iz ökole Tam...
{56957}{57076}...éeljezna äaka iz ökole Hung | i äesterokutna Palica...
{57091}{57138}Ti iz Svinjca su | doista dobri.
{57143}{57196}Njihovi ratniËki dani | odavno su zavröili...
{57209}{57291}...no joö uvijek su vrhunski borci.
{57301}{57416}Ovaj posao je velik izazov za nas.
{57425}{57485}To je profesionalnost.
{57490}{57618}Ubojice broj jedan. Skupi su, | ali vrijede svakog novËiÊa!
{57622}{57645}Ne!
{57650}{57771}Broj jedan je Zvijer, | najbolji ubojica na svijetu.
{57783}{57885}Toliko se posvetio | kung fuu da je poludio.
{57890}{57968}»uo sam da je sada u ludnici.
{57984}{58062}ZnaËi da ste sada vi | najbolji ubojice.
{58067}{58171}Strogo govoreÊi, | mi smo samo glazbenici.
{58179}{58292}Pjesma koja slama srce | Gdje da naem uho znanja?
{58300}{58404}Sjajna pjesma, zar ne?
{58599}{58636}Uskoro Êemo se oprostiti.
{58640}{58699}Tko zna kada Êemo se | opet vidjeti.
{58717}{58818}Nas trojica smo isti. Volio bih | da smo to prije znali.
{58822}{58900}Iskoristimo ovu priliku | za mali sparing.
{58907}{58987}Ne. »eka nas pakiranje.
{59006}{59047}Imaö pravo.
{59960}{60039}12 Udaraca iz ökole Tam! | Izvrstan napad i obrana!
{60045}{60112}éeljezna äaka, snaûan, | a opet njeûan. Vrhunski!
{60119}{60197}äesterokutni ätap sa svojih | tisuÊu pokreta. MistiËan!
{60209}{60264}Dok se opet ne sretnemo!
{60497}{60520}Tragovi sjajila | za usne!
{60986}{61057}Ostani tu | ili Êu te prepoloviti.
{63070}{63119}éalim, zatvoreni smo.
{63124}{63172}Moûeö u trenu | napraviti odijelo.
{63177}{63212}Selimo se.
{63217}{63260}Ovo je dobar materijal.
{63277}{63332}Razumijete se u tkaninu.
{63345}{63396}Ima visoku umjetniËku | vrijednost.
{63412}{63443}Kako visoku?
{63454}{63497}Barem nekoliko katova...
{65179}{65232}Vrijeaju bandu Sjekiraöa! | Pokazat Êemo mi njima.
{65237}{65312}Pobijmo ih sve i sagradimo | na ovom mjestu bordel.
{65317}{65364}Ne blokiraj mi pogled!
{66553}{66576}äto se dogaa?
{66851}{66877}Dobro!
{66882}{66925}Ne blokiraj mi pogled!
{67050}{67125}Kvragu! Rekla sam glupanima | da odu, ali joö uvijek su tu.
{67130}{67171}- Doista? | - Da.
{67737}{67832}Kakva je ovo borba? | Tko Êe platiti ötetu?
{67837}{67884}Oprostite, nije to niöta!
{70298}{70371}Znate li koliko je sati? | Moram spavati.
{70399}{70444}Debela, jedi govna i crkni!
{70466}{70501}Da crknem? | S ovom bukom?
{70506}{70554}Oprostite, oprostite!
{70610}{70657}MiËi mi se s puta!
{70677}{70717}Izdrûi, krojaËu.
{70929}{70984}Tiöina!
{71110}{71223}Popustite malo! | Zaöto nas toliko tlaËite?
{71576}{71604}Postoji joö jedan | majstor?
{75132}{75179}To je Lavlja Rika!
{75196}{75239}Mislio sam da je ona mit.
{75269}{75339}Tko je znao da Lavlja Rika | doista postoji?
{75344}{75429}To je zadnji put da ih vidimo.
{75501}{75561}Nije dobro, Brate Sum. | Brzo, upali auto!
{75571}{75609}Upali auto!
{75772}{75799}äefe!
{75804}{75857}Tiöe! | Zar nemate pristojnosti?
{75862}{75919}Gubite se. | Ljudi ûele spavati.
{75924}{75994}Sutra rade. Gubite se odavde!
{76073}{76111}Oloö!
{78170}{78242}Ne mogu joö dugo izdrûati.
{78300}{78392}Ali nakon öto sam vidio | prave majstore kakvi ste vi...
{78410}{78459}...sada mogu umrijeti | u miru.
{78464}{78509}Nemoj to govoriti.
{78514}{78584}Mi smo obiËni ljudi.
{78589}{78630}ObiËnost je blagoslov.
{78635}{78717}Ne nazivaj nas majstorima.
{78722}{78767}Ali, sjajni ste borci!
{78772}{78873}Da ste im ranije pomogli, | ne bi morali ovako umrijeti.
{78886}{78985}Kao öto je Krafn rekao, | svi imaju svoje razloge.
{79005}{79045}Prije mnogo godina...
{79058}{79132}...vidjeli smo kako nam | jedini sin pogiba u borbi.
{79186}{79250}Osveta moûe uniötiti.
{79259}{79310}Razumijete li?
{79315}{79388}Zaöto nas ne uvjeûbate | da postanemo vrhunski borci...
{79393}{79464}...i osvetimo ih?
{79469}{79568}Da biste postali vrhunskim | borcem treba vremena.
{79573}{79634}Osim ako nisi prirodni | kung fu genij.
{79639}{79728}A takav je jedan od milijun.
{79911}{79963}OËito je da sam ja taj!
{80049}{80101}Ne bih rekla.
{80125}{80253}Ljudi, zakleli smo se da se | viöe nikada neÊemo boriti.
{80258}{80315}Ali danas smo | prekröili tu zakletvu.
{80320}{80404}Zbog vaöe sigurnosti | molimo vas da odete!
{80512}{80596}U velikoj moÊi leûi | i velika odgovornost.
{80609}{80653}Od toga nema bijega.
{80664}{80724}Krafno, teöko si ranjen.
{80729}{80766}Odmaraj se.
{80885}{80943}Ne razumijemo öto govoriö.
{80983}{81008}Krafno!
{81323}{81370}Tebe poznajem, Ëetverooki!
{81405}{81514}»ini se da imaö predrasude | prema kratkovidnima.
{81519}{81597}Da. Osobito prema Ëetverookima | sa zlatnim okvirima.
{81700}{81779}Zlatni okviri su savröeni za Ëinovnike.
{81784}{81857}Mislim da dobro izgledam. | Zaöto me napadaö?
{81915}{81938}Pomozi.
{81995}{82072}"Pomozi! Pomozi!" HoÊete | se igrati, propalice?
{82077}{82120}Zmajev stil? | Tigrov stil?
{82234}{82340}Sii i razbit Êu ti naoËale. Hajde!
{82381}{82433}Znaö da bih to uËinio, zar ne?
{82466}{82497}Zakuni se!
{82513}{82544}Zakuni se!
{82613}{82715}Zar nemaö poötovanja? | Gdje si bio kad sam te trebao?
{82758}{82798}ZvuËiö kao mlakonja!
{82803}{82878}Uvijek nas istuku! | Niöta nismo postigli.
{82883}{82972}Ni ubijanje, ni paleû, | ni pljaËke, ni silovanja.
{82977}{83037}I to sve zbog tebe!
{83042}{83097}Glupan si!
{83156}{83187}Za mnom!
{83395}{83433}Ovo je pljaËka! | Gdje je novac?
{83552}{83604}Gdje je novac?
{83643}{83693}äto gledaö? Ozbiljan sam!
{83813}{83908}Ubijam ljude i za manje! | Daj mi novac.
{84350}{84389}Novac je ovdje.
{85252}{85295}Pustite djevojku!
{85608}{85719}On je budala, a ona je mutava. | Gubitnici!
{86762}{86843}Odlazi! Sputavaö me!
{86862}{86984}Vrati se kuÊi i uzgajaj svinje.
{87102}{87137}Idi dok te nisam ubio.
{88309}{88389}Ti! Kako ti je veÊ ime!
{88608}{88689}Uzmi ovo i kupi novu odjeÊu. | Odsad si Sjekiraö!
{88694}{88785}- Ozbiljno? | - Netko te Ëeka.
{88952}{88979}Brate Sum!
{88984}{89091}Jednom sam te pogledao i | znao sam da Êeö uËiniti sve.
{89099}{89122}Tako je!
{89127}{89169}Samo si trebao priliku.
{89189}{89213}Upravo tako!
{89218}{89257}Imamo zadatak za tebe.
{89262}{89299}Samo reci, brate Sum!
{89752}{89823}"Centar za abnormalne ljude." | äto je to?
{89828}{89870}Mentalna ustanova.
{90009}{90037}Vojnici!
{90042}{90083}IzviaËi!
{90088}{90111}Tenkovi!
{90116}{90162}Bez brige.
{90167}{90253}Kad izviaËi promijene smjenu, | imaö toËno pet minuta.
{90258}{90352}Slijedi strelice na karti. | Idi do zadnje Êelije...
{90357}{90468}...i oslobodi Ëovjeka u njoj. | Evo ti alat.
{90610}{90645}A vi?
{90650}{90697}Mi ti Ëuvamo lea.
{90972}{91019}Pet minuta. Poûuri se!
{94240}{94355}Najbolji ubojica na svijetu | doista tako i izgleda!
{94381}{94436}To je samo naslov.
{94441}{94523}Ne seri. éelimo ubiti dvoje ljudi. | Reci svoju cijenu.
{94537}{94572}äto da kaûem?
{94630}{94756}Toliko sam ih ubio nastojeÊi | pronaÊi dostojnog protivnika.
{94765}{94843}Dosad ga joö nisam naöao.
{94852}{94895}Zato sam ostao unutra.
{94900}{95004}Da sam naöao sebi ravna, | odavno bih bio vani.
{95009}{95068}Ako mi naete | dostojnog protivnika...
{95073}{95127}...uËinit Êu to besplatno!
{95179}{95206}Imate li nekoga?
{95211}{95336}Da. Sjajne borce dostojne izazova.
{95341}{95396}No hoÊeö li nam prije | pokazati neke pokrete?
{95401}{95473}Nije da ti ne vjerujemo. Samo | te ûelimo vidjeti u akciji.
{95483}{95584}Vi glupani niste dostojni!
{95693}{95732}Ne izgleda dorastao | zadatku.
{95755}{95879}NatikaËe su malo usrane. | Ali dobro Êe ih srediti.
{95884}{95928}Siguran si da si doveo | pravog Ëovjeka?
{95933}{96012}Svakako. Kunem se da sam | uËinio ono öto ste mi rekli.
{96045}{96139}Pokaûite nam neke pokrete, | g. Zvijeri. Ne oteûavajte mi!
{96144}{96182}Zar si glup?
{96203}{96250}Znaö li öto je ovo, starËe?
{96261}{96319}Jesi li ikad vidio | ovako veliku öaku?
{96324}{96398}Ne prisiljavaj me na borbu. | Sam sebe plaöim kad se borim!
{96403}{96448}Doista? | Onda me iskuöaj.
{96541}{96592}Je li dobro?
{96732}{96792}Kaûeö da se znaö boriti?
{96827}{96850}JaËe!
{96872}{96895}JaËe!
{96973}{97004}JaËe!
{97073}{97156}Tako udaraö i sebe nazivaö | gangsterom?
{97276}{97306}Uvozni piötolj!
{97922}{98050}U svijetu kung fua brzina | odreuje pobjednika.
{98149}{98217}Zvijer je najbolji od svih.
{98225}{98312}Banda Sjekiraöa | odaje mu poötovanje!
{99314}{99382}Pravi majstori, | zajedno u jednoj prostoriji!
{99409}{99510}Samo najbolji ubojica na svijetu...
{99514}{99566}...ima takvu auru.
{99585}{99613}Takoer.
{99630}{99694}Moûda ste vas dvoje | sudbonosni ljubavnici.
{99698}{99752}- Paris... | - I Helena Trojanska!
{99772}{99811}Uistinu mi je | zadovoljstvo.
{99818}{99909}Doöli smo podmiriti raËune | s bandom Sjekiraöa...
{99914}{99955}...i samo s bandom Sjekiraöa.
{100003}{100070}Trebali ste me ubiti prije.
{100079}{100184}Sada ste poËinili samoubojstvo.
{100189}{100268}éiviö na posuenom vremenu.
{100273}{100344}Ne moûeö pobjeÊi sudbini!
{100363}{100418}äto je ovo? Pogrebno zvono?
{100437}{100516}BuduÊi da je Zvijer tu, | vidjet Êemo Ëiji je sprovod!
{100537}{100578}ZnaËi, | na drugoj si strani?
{100583}{100634}Nemojte me pogreöno shvatiti.
{100639}{100724}Ja vas samo ûelim ubiti...
{100729}{100798}...ili da vi ubijete mene.
{100859}{100905}äto kaûeö?
{100910}{101038}Dobro ne moûe ûivjeti sa zlom. | Ne moûeö pobjeÊi sudbini.
{101053}{101132}Neka tako bude. UËinimo to.
{101157}{101184}U redu.
{101222}{101246}UËinimo to!
{101729}{101786}Udarite jaËe. | Mogu podnijeti viöe.
{102013}{102081}Dobar pokuöaj, | no ipak promaöaj.
{103995}{104034}Lavlja Rika?
{107893}{107922}»ekaj!
{107951}{108066}Nisam znao da se lavlja rika | moûe postiÊi s mikrofonom!
{108071}{108126}Izgubio sam.
{108829}{108908}- »ini se da mu nisu dorasli! | - DokrajËimo ih dok su slabi.
{108913}{108936}Ti to uËini!
{108941}{109012}- Povratit Êu! Trebam lijeËnika! | - Idi u pakao!
{109118}{109160}Ti! Doi.
{109185}{109236}- Udari ga! | - Da!
{109345}{109389}- Glava! | - Naravno!
{109396}{109436}- Udari ga u glavu! | - U redu.
{109441}{109484}- Evo ti prilike. | - Moûe!
{109489}{109515}- Udari ga! | - Udari ga!
{109520}{109555}- Prebij ga! | - Dobro!
{109560}{109589}- Udari ga! | - Udari ga!
{109594}{109636}Prebij ga na mrtvo ime!
{109685}{109708}äto radiö?
{109727}{109796}HoÊeö da ga udarim ili | prebijem na mrtvo ime?
{109801}{109847}Zbunjujeö me!
{110527}{110598}E, to je velika öaka!
{111380}{111412}Zaöto si me udario?
{112107}{112186}Gdje su?
{112195}{112246}Kako si im mogao dopustiti | da pobjegnu?
{112393}{112488}Meni nitko ne bjeûi!
{112817}{112868}Zaöto si nas spasio?
{112873}{112947}Mladi ljudi Ëine pogreöke.
{112956}{113045}No ipak se na kraju iskupio.
{113060}{113148}Vidi ga! Prebijen na mrtvo.
{113214}{113292}Imaö li posljednju ûelju?
{113756}{113824}»ekaj!
{113834}{113925}Zaöto ne piöeö kineski? | Ne razumijem.
{115278}{115326}Ovdje nema nikoga!
{115441}{115505}KINESKA MEDICINA
{115833}{115904}»udo je da je izdrûao tako dugo.
{115921}{115974}Ljekovito bilje | Êe mu pomoÊi.
{115981}{116085}PomoÊi Êe samo djelomiËno. | KljuËna je tjelesna graa.
{116090}{116193}Sve kosti i tetive su mu slomljene.
{116198}{116268}»udo je da se tako brzo oporavlja.
{116281}{116332}NemoguÊe...
{116337}{116374}Osim ako nije...
{117269}{117306}Kakav je to miris?
{118121}{118168}Ne smijeö puöiti | dok si ozlijeena.
{118205}{118240}Ja Êu se za ovo | pobrinuti.
{118595}{118630}Ovo nema smisla.
{118909}{119006}Tko bi rekao da Zvijer | moûe oËistiti chi...
{119011}{119072}...i tako osloboditi deËkov | istinski potencijal.
{119077}{119146}Trebali smo pretpostaviti.
{119177}{119257}On je taj!
{119509}{119554}Je li ovo ozbiljno?
{119559}{119620}Joö si ûiv, izdajice?
{119625}{119681}Ubijte ga, ljudi!
{120997}{121032}Kakav je to potez?
{121041}{121100}DjeËja igra!
{121769}{121855}Da je naö sin ûiv, | sada bi bio njegovih godina.
{121860}{121988}Ako naporno uËi, moûe postati | lijeËnik ili odvjetnik.
{121992}{122060}Vjerojatnije kaskader!
{123574}{123611}Nije loöe. Idemo.
{124644}{124692}Mogu Ëak i metke zaustaviti...
{126381}{126461}äto? éablji stil ökole Kwan Lun?
{126466}{126494}O, ne!
{129266}{129360}SjeÊaö se poteza dlana | koji pada s neba?
{129365}{129440}To je davno izgubljen | BudistiËki dlan.
{130503}{130534}Predajem se!
{132007}{132040}Kakav je to bio potez?
{132085}{132136}Ako ûeliö znati, | nauËit Êu te.
{132419}{132450}UËitelju!
{134222}{134313}Reci mu da ne slini po Ëaöi.
{134318}{134380}Vas dvoje, odjenite se!
{134385}{134449}Nema lizanja ako ne kupujete!
{136041}{136151}Mali, imaö grau kostiju | kung fu genija.
{136156}{136246}Svjetski mir je u tvojim rukama. | "Svitak BudistiËkog dlana."
{136251}{136312}BuduÊi da ti je to sudbina, | dajem ti ga za 10 dolara.
{136317}{136342}»ekaj!
{136353}{136410}Ne svia ti se taj? | Imam joö...
{136411}{136611}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
{136636}{138136}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/5gwt2|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
