{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{247}{325}JUNI 1946.|U SOVJETSKE AMBASADE
{333}{411}U FRANCUSKOJ, BUGARSKOJ,|JUGOSLAVIJl, STléE VEST.
{418}{487}SVI RUSI PROGNANI|PO»EV OD 1917.
{492}{572}MOGU DA DOBIJU|SOVJETSKI PASOä
{577}{649}I DA SE VRATE U SSSR.
{660}{723}HILJADE NJIH POäLO JE KU»l.
{729}{796}POSLEDNJI PUTNICI|ZA 5 GODINA MRAKA
{803}{895}TOKOM KOJIH JE 30 MILIONA|LJUDI NAPUSTILO DOM.
{2234}{2341}I S T O K - Z A P A D
{3074}{3137}STléETE U DOMOVINU.
{3146}{3304}OSTAVILI STE JE PRE 30 GODINA,|ALI ONA NIJE OSTAVILA VAS.
{3312}{3388}Sad ste joj svi vi potrebni.
{3397}{3466}Treba da je obnovimo.
{3474}{3562}Mi smo platili najviöu cenu|tokom rata.
{3570}{3691}Ali nas je rat protiv|faöizma i ujedinio.
{3714}{3817}Sovjetska vlada vam|otvara vrata.
{3824}{3941}Dobro ste doöli,|uprkos svemu iz proölosti.
{3950}{4059}Nemoj tako ozbiljno.|Da pijemo, da pevamo...
{4103}{4239}Neka nazdravi onaj koji ima|najmanji broj na pasoöu!
{4244}{4343}Mogu li ja? Mene je prognala|francuska policija.
{4350}{4384}Svakako!
{4397}{4452}Znate li ko ima pasoö br. 1?
{4460}{4538}Glavar pravoslavne crkve|u Parizu!
{4567}{4653}Koji vi broj imate?|- Broj 2002.
{4674}{4836}Moj sin Leonid ima broj 2003.
{4850}{4959}Ne zamerite mu - ruski|ne govori dobro.
{4978}{5062}Koji si ti broj, doktore?|- 17.
{5119}{5190}Onda nazdravi!
{5401}{5464}éelim da se zahvalim|mojoj ûeni.
{5504}{5629}Mari, zamolio sam te|da poeö sa mnom.
{5650}{5755}Napustila si rodbinu,|prijatelje, svoju zemlju.
{5766}{5852}Zbog toga i zbog mnogo Ëega...
{5863}{5953}volim te i divim ti se.
{6459}{6514}Da li je stvarno tako?
{6569}{6653}Vi ste hrabra ûena.
{8637}{8735}DRAGI SUNARODNICI !|DOBRODOäLI U ODESU!
{8750}{8979}NA SOVJETSKO TLE GDE, POD|VO»STVOM DRUGA STALJINA,
{8999}{9095}NAJMUDRIJEG ME–U MUDRIMA,
{9102}{9194}SVI éIVE ZAJEDNO I|SRE»NO KAO PORODICA!
{9783}{9890}Boûe moj... KonaËno sam|u Rusiji.
{9960}{10048}Rusijo... zemljo moja.
{10268}{10348}Putnike Êemo podeliti|u dve grupe.
{10357}{10478}Kozlov Sergej VasiljeviË...|tamo.
{10527}{10590}Kozlov Leonid SergejeviË.
{10614}{10671}Leonid... tamo.
{10681}{10773}To mi je sin!|On mora sa mnom!
{10906}{11044}Ljona, ne brini.|To je neki nesporazum.
{11357}{11462}Stoj! PucaÊu...
{11775}{11913}Rekla sam istinu. Doöla sam|s muûem. Ja sam francuskinja.
{12040}{12095}Poludeli ste! äta vam je?
{12108}{12182}Znamo da radiö za|francusku obaveötajnu.
{12189}{12226}Gluposti!
{12286}{12354}Zahtevam da se vidim|s francuskim konzulom.
{12403}{12466}VideÊeö i englesku kraljicu!
{12746}{12803}Odavno te pratimo, Golovine.
{12820}{12939}Dobar si lekar. NaÊi Êemo|ti smeötaj, posao.
{12945}{12986}Gde je moja ûena?
{12994}{13061}Zaboravi ûenu. äta Êe ti?
{13080}{13135}NaÊi Êemo ti Ruskinju.
{13149}{13250}Kaûem da Êemo mu dati naöu -|a on neÊe!
{13282}{13337}Tvoja ûena je öpijun.
{13359}{13392}äalite se?
{13397}{13491}Nikako. 90% emigranata|su öpijuni,
{13496}{13565}u sluûbi imperijalizma.
{13599}{13669}Maloga Êemo vam dati.
{13752}{13787}Gde je moja ûena?
{13794}{13878}Pazi öta radiö.|Mi ti verujemo.
{14022}{14071}HoÊeö ûenu?
{14188}{14241}Onda prvo da porazgovaramo.
{15010}{15048}Gde je Serjoûa?
{15053}{15104}Sad Êe da ga dovedu.
{15145}{15188}Hajde, idite.
{15198}{15228}Kuda?
{15243}{15277}U Kijev.
{16853}{16925}Doveo sam nove stanare.|Francuze.
{16931}{17063}Objasni da ja ovde upravjam i|da su pravila stroga.
{17068}{17115}Ja govorim ruski.
{17359}{17383}Hvala.
{17895}{17942}Kaûe - neki Francuzi.
{17996}{18043}Dobar dan. Petrov.
{18083}{18157}Aleksej... Moja ûena Mari.|Sin Sergej.
{18163}{18266}Dobro nam doöli.|Vi ste u poseti?
{18278}{18325}Ne. éiveÊemo ovde.
{18421}{18521}Vaöa ûena govori ruski?|- NauËiÊe.
{18527}{18576}Ako neöto treba -|pomoÊi Êemo.
{18591}{18646}Saöa, idi po hleb.
{18781}{18820}KljuË od ulaza.
{18864}{18958}Da odmah sve raöËistimo.
{18965}{19041}Da ona sve shvati.|PrevodiÊete.
{19116}{19204}Vi ste öesta porodica|u ovom stanu.
{19209}{19289}Najbolje je da svi|poötujemo pravila.
{19294}{19370}Ovde je veÊ pet|porodica...
{19430}{19549}Ovaj sto je ostao od|prethodnika. Vaö je.
{19562}{19642}Ovo je sad naö sto...
{19725}{19764}Kupatilo.
{19870}{19966}Vaöe je Ëetvrtkom. Tad|moûete i veö da perete.
{19974}{20112}»etvrtkom je|kupatilo naöe.
{20120}{20278}Gasite svetlo u toaletu.
{20609}{20677}Da li ti se svia ovde?
{21152}{21257}äta je vaûno za putnika?|- Da bude jak i hrabar!
{21262}{21292}Bravo.
{21324}{21394}Zavröi krevet.|Odmah se vraÊam.
{21909}{21964}Kako si mogao da znaö?
{21972}{22139}VratiÊemo im sobu|i otiÊi Êemo.
{22213}{22272}Ne mogu da nas spreËe.
{22388}{22449}Ne moûemo ovde da ûivimo.
{22457}{22549}VratiÊemo se u Francusku.
{22637}{22700}I iz zatvora se izlazi.
{22850}{22901}Oprosti mi...
{23895}{24012}Radila sam za maöinom.|Od toga boli rame.
{24020}{24131}Sigurno. A vazduh?|Kakva li su im pluÊa?
{24138}{24303}PostaviÊemo cevi,|vlaûiÊemo prostoriju.
{24417}{24526}Praöina Êe padati na pod.|Tako rade u Francuskoj.
{24532}{24595}Baö me briga za Francusku.
{24625}{24717}Tamo eksploatiöu radnike.
{24755}{24825}Nismo te uzeli da|sve menjaö.
{24830}{24962}Odgovaram za zdravlje radnika.|Time Êu i da se bavim.
{25223}{25305}Francuskinjo! To nije|tvoj sto!
{25323}{25374}Izvinite.
{25519}{25617}Pusti je, pijanduro.|Gubi se odavde!
{25830}{25908}Zaöto ste doöli?|Niste znali?
{25915}{25987}Govorite francuski?|- Govorila sam.
{25993}{26062}Moja guvernanta je|bila Francuskinja.
{26067}{26157}U istom ovom stanu...|ali u drugom ûivotu.
{27189}{27246}U vaöe zdravlje.
{27378}{27439}Pevajte sa mnom.|Znate reËi!
{27516}{27610}"A drugi je kazao...|dajte mi vaöu kÊer..."
{27813}{27872}Zaöto ste prestali?
{27884}{27954}Madam Mari, öubare...
{27960}{28015}Da probate?
{28071}{28104}Ne, hvala...
{28197}{28254}Uzmi. DaÊu jeftino!
{28259}{28343}Mogao bi i da vam pokloni.|- Ukrali su je?
{28351}{28369}Ne! Ne!
{28376}{28445}Imaju dobavljaËe na|sve strane.
{28450}{28509}Nosi kapu i odlazi.
{28526}{28569}Hajde... idite!
{28619}{28678}Pazi öta radiö, baba.|Mnogo priËaö.
{28685}{28734}Pusti to. Idi!
{28780}{28835}éive u mojoj sobi.
{28844}{28940}Vi ste u maminom salonu.
{28954}{29036}Uvalili ste se u govna.
{29042}{29111}Pokuöajte da zaboravite|Francusku.
{29118}{29163}Dobro veËe...
{29188}{29227}Votkica!
{29233}{29288}Da vidim supu...
{30009}{30039}Hajde! ldemo!
{30044}{30113}To je nesporazum, Saöa.|VratiÊu se.
{30130}{30204}Samo ti plivaj.|To ti je prilika.
{30277}{30336}Nemoj da se ljutiö,|molim te.
{30396}{30437}Dosta je bilo!
{30598}{30697}Jesi li komunista?|Tebe pitam.
{30717}{30803}Onda se savladaj!
{30837}{31008}Smiri se... Sve je|u redu... Tako...
{31188}{31334}äta se desilo, Saöa?|Ko je to bio?
{31444}{31515}äta se dogodilo?|- Prijavili su je!
{31521}{31558}Zaöto?
{31614}{31708}Zbog vaöe ûene!|OsudiÊe je za öpijunaûu.
{31713}{31824}Vas stance uvek prate!
{31852}{31926}Idite! ostavite nas!
{32537}{32584}Dobar dan. Izvinite...
{32592}{32694}Dajte mi adresu|Ministarstva unutraönjih.
{32699}{32740}Ministarstva?
{32765}{32841}Zaöto? HoÊete da|idete tamo?
{32846}{33012}Da.|- SaËekajte malo.
{33128}{33214}OdveöÊu vas do autobusa.
{34217}{34285}Fabrika "Crvena zastava"?
{34326}{34390}Molim doktora Golovina.
{34697}{34762}Tu ne smeö da stojiö.|- Pratio si me?
{34773}{34814}Hajde, brzo!
{34822}{34859}Ko ti je javio?
{34868}{34923}Hajde, kad ti kaûem!|- Pusti me!
{35094}{35137}Sve je u redu.
{35145}{35192}Da vas odvedem|u ambulantu?
{35200}{35269}Neka, hvala.|Ja sam doktor.
{35277}{35318}Poite!
{35365}{35414}äta je htela|ta strankinja?
{35424}{35496}Niöta. Pogreöila je adresu.
{35547}{35582}äta ti je bilo?
{35589}{35679}Ne mogu viöe. »ekam dva|meseca da neöto uradiö.
{35686}{35755}Ako hoÊu da odem -|znaËi da osuujem reûim.
{35760}{35807}Mi Êemo u logor,|a Serjoûa u sirotiöte.
{35815}{35915}Ne smeju da nas drûe ovde.|Moraju da nas vrate.
{35924}{35983}Nemoj da govoriö francuski.|- Baö me briga!
{35990}{36109}Dogovorili smo se da Êemo da|se vratimo ako ne ide.
{36116}{36227}UmreÊemo ovde... ja Êu|da umrem ovde.
{36242}{36275}HoÊu da odem!
{36434}{36528}Pusti me! HoÊu da odem!
{36572}{36613}Ne mogu viöe!
{37190}{37334}IzvuÊi Êemo se.|Strpi se... veruj mi...
{37458}{37555}Zasad moramo da ûivimo|Ovde.
{39009}{39056}Irina, svaka Ëast.
{39062}{39119}Tolja, öto si se oduzeo?
{39126}{39177}Ti predstavljaö|sovetskog Ëoveka.
{39184}{39239}A ti... sav mlohav!
{39250}{39303}äta ti to znaËi?
{39761}{39890}Ovo nije moja koöulja.|Opet je sve pomeöala.
{39898}{39959}A ova? - To je moja.
{40270}{40391}Zaöto ste ovde?|Morate odmah na scenu.
{40395}{40446}Zbog Francuskinje...
{40741}{40817}Dobar dan, draga moja.|Umorila si se?
{40950}{41003}Treba da se jede.
{41024}{41141}Nepoverljivi su, jer si|strankinja. ProÊi Êe to.
{41167}{41218}Vrlo si lepa.
{41494}{41561}Ne znaju da rasporede pisma.
{41568}{41658}Moram da se staram i za to.
{41689}{41748}Hvala vam öto ste|paûljivi...
{41756}{41823}Lako je meni s vama.
{41837}{41931}Lepo ste vaspitani.|Sve razumete.
{41968}{42054}Kupio sam piroöke...|HoÊete?
{42125}{42151}Hvala.
{42959}{43111}Ne znam gde su je odveli.|Viöe je nisam video.
{43121}{43172}Umrla je sama.
{43179}{43228}Znala je da je voliö.
{43234}{43298}Da misliö o njoj...
{43345}{43404}HoÊe li joö neko da doe?
{43975}{44024}Mama, öta je ovo?
{44030}{44100}Mesto za baba Anastaziju.
{44151}{44243}Kratko smo poznavali|Anastaziju Aleksandrovnu.
{44249}{44364}Bila je izuzetna osoba.
{44402}{44550}Da popijemo za pokoj duöe.
{44603}{44724}Neka joj je laka zemlja.
{45493}{45552}Evo vam novih stanara.
{45560}{45615}Kako? Nemamo slobodnih soba!
{45621}{45662}Soba Vasiljeve.
{45667}{45718}Tamo ûivi njen unuk Saöa.
{45724}{45899}Moj muû je ostao bez noge.|Zasluûujemo udoban smeötaj!
{45906}{45945}A gde Êe on da ûivi?
{45956}{45997}Nemate pravo da...
{46114}{46157}On Êe u dom.
{46168}{46207}Tamo ne idem.
{46215}{46264}Smiri se, Saöa.
{46270}{46306}Pogreöili su.
{46311}{46420}Ja sam ovde odgovorna.|Niko mi nije javio.
{46427}{46472}Imam dokumenta...|- Polako...
{46480}{46535}Ne mrdam odavde!
{46541}{46565}äta se dogaa?
{46571}{46638}Saöa nema pravo na sobu.|Ide u dom.
{46716}{46765}Moûe da pree kod nas.
{47321}{47374}Bakine knjige.
{47465}{47543}Iz njih sam nauËio|francuski.
{47577}{47676}Za vas... - Hvala.
{47902}{47955}Sad ostajem sam.
{49070}{49133}Vasiljev! Doi ovamo!
{49188}{49317}äta je s rezultatom?|Loöije nego proöle godine!
{49323}{49370}Pet sekundi duûe!
{49388}{49542}Posmatram ja tebe.|Puöiö, kaûu i da pijeö.
{49550}{49648}Ako tako nastaviö,|plutaÊeö po vodi kao govno!
{49702}{49734}Umrla mi je baka.
{49740}{49812}I meni. I to obe!
{49920}{50031}Hajde, gubi se!|Da te viöe ne vidim!
{50077}{50122}U vodu, devojke!
{50659}{50710}Sve vreme si ûmurio.
{50729}{50825}Nisam znao gde sam.
{50890}{50928}Zajedno smo.
{50978}{51029}To znam sve vreme.
{51060}{51162}Voleo bih da si samo moja.
{51203}{51287}Da smo slobodni i da...
{51329}{51395}Tako si lepa.
{51434}{51586}Nas dvoje... sami na svetu.
{52390}{52466}Saöa, ti si pio?
{52512}{52571}Nisam mnogo.
{52596}{52657}Opet si iöao kod njih?
{52678}{52750}Madam Mari, da|popijemo po jedno.
{52756}{52793}NeÊe ti ta doÊi.
{53370}{53413}Nastavi da plivaö.
{53435}{53490}Izbacili su me iz tima.
{53536}{53597}Za plivanje ne treba tim.
{53628}{53689}Treba dar i upornost.
{53697}{53785}Nisam ja viöe dete.|- Ponaöaö se kao dete.
{53807}{53881}Spavaj. PriËaÊemo sutra.
{53907}{54028}NoÊima ne spavam...|mislim na baku.
{54047}{54135}I na roditelje.
{54176}{54244}Zaboravio sam njihove|likove.
{54267}{54376}Zajedno su uhapöeni|i osueni.
{54415}{54524}Bio sam mali. Baka mi|godinama nije rekla.
{54557}{54637}»ak mi je i pisma pisala...
{54673}{54720}Zaöto su uhapöeni?
{54796}{54864}To se nikad ne zna.
{54894}{55007}I ja ûelim da odem odavde.
{55029}{55125}Zaöto mi to govoriö?
{55140}{55263}»uo sam kako noÊu|priËate s Aleksejem.
{55268}{55331}Ni vi ne spavate.
{55337}{55405}»uo sam kako plaËete.
{55600}{55731}Ti si hrabar, Saöa.|I ja hoÊu da tebi pomognem.
{55736}{55783}PriËajte mi o Francuskoj.
{57084}{57114}Kako je?
{57140}{57193}Ovo radim zbog vas.
{57243}{57348}Radiö... zbog sebe...|i zbog nas.
{57456}{57544}BiÊeö najbolji.|PlivaÊeö uzvodno.
{58840}{58873}Vrlo dobro, doktore!
{58877}{58934}Tako i treba da bude.
{58994}{59051}Imate li ovo i kod kuÊe?
{59363}{59406}Joö pet minuta.
{59480}{59544}Dobar si lekar, Aleksej.
{59569}{59616}Svi to znamo.
{59652}{59926}Oni gore se pitaju|da li si i Ëasan graanin.
{60138}{60164}Prestani!
{60187}{60250}Ideö li, Saöa? OdluËi!
{60256}{60309}Nemam öta da obuËem.
{60462}{60490}Biraj!
{60533}{60584}Smiri se. Ima vremena!
{60613}{60683}Kola stiûu kroz pet minuta.
{60690}{60756}Kakva kola?|- Nine Fjodorovne.
{60778}{60823}Tvoje direktorke?
{61096}{61151}Divno izgledaö.|Svi smo lepi!
{61742}{61801}Dragi Kijevljani!
{61819}{61915}Okupili smo se zbog|velikog dogaaja.
{61923}{62040}GledaÊemo "Mariju Tjudor"|od Viktora lgora,
{62048}{62144}vrlo naprednog pisca.
{62368}{62545}Uloge tumaËi francuska|umetnica Gabriel Devlej.
{62551}{62573}Gde je tata?
{62843}{63096}Sutra Êeö biti u novinama.|To je Ëast za tebe...i za mene.
{63228}{63324}Sad dajem reË naöem Ëoveku|koji je ûiveo u Francuskoj
{63331}{63401}i koji govori taj|lepi jezik:
{63421}{63513}drug Golovin, direktor|fabriËkog dispanzera.
{63730}{63868}Dragi prijatelji iz|Francuske, dragi sugraani...
{63918}{64072}Prvo ûelim da se zahvalim|gradu Kijevu,
{64111}{64236}sovetskoj vladi i|komunistiËkoj partiji,
{64251}{64416}koji su mi dozvolili da se|vratim, dali mi posao
{64447}{64554}i koji su prihvatili moju|ûenu i moga sina.
{65590}{65785}Voliö me, zar ne?|Kaûi mi opet, s istim pogledom.
{65808}{66045}éena nikad ne zna öta se|zbiva u srcu muökarca.
{66116}{66180}Gledaö me iskreno.
{66190}{66284}Ako takve oËi varaju,|to je pakao.
{66300}{66388}Tvoje oËi su ili oËi|anela, ili demona.
{66399}{66518}»ast nam je da pozdravimo|ugledne goste.
{66548}{66589}»ekaju nas...
{66658}{66711}NeÊu na vaö prem.
{66734}{66810}Ja sam iz ubeenja doöla na|turneju po SSSR.
{66816}{66956}DesniËarska ötampa me je|blatila i opet Êe.
{66985}{67056}éelim da im odgovorim.
{67073}{67128}HoÊu da vidim ljude,|ûene...
{67133}{67178}da priËam s njima.
{67184}{67237}Ti premi nisu ûivot.
{67245}{67296}Funkcioneri, zvaniËnici...|prava maskarada.
{67302}{67338}»uli ste aplauz.
{67343}{67382}Svi su oduöevljeni!
{67389}{67455}Dosta mi je poruËenog|oduöevljenja!
{67460}{67548}Jedva da je iko|razumeo francuski!
{67574}{67617}Vodite me u bilo|koji restoran!
{67622}{67712}Najbolji restorani su za|partijce, tamo ne moûemo.
{67720}{67758}Moûemo u staniËnu birtiju.
{67765}{67802}Hajdemo! I to mi odgovara.
{67808}{67846}Moram da vas vidim.|Hitno je.
{67852}{67882}Izvinite, Madam...
{67889}{67934}Ne mogu da stignem do|francuskog diplomate.
{67941}{67971}Niste izabrali pravi|trenutak...
{67978}{68039}U pitanju je ûivot mog|muûa, sina i moj.
{68045}{68098}Sad nije ni vreme|ni mesto...
{68104}{68145}Doite!
{68356}{68403}Ostanite tu.|SaËekajte me.
{68453}{68502}Traûite prem u ambasadi.
{68508}{68610}Ambasada je u Moskvi, nemam|dozvolu za put. ZatoËena sam.
{68637}{68706}éelim da odem odavde.|Pomozite!
{68739}{68805}To pismo je zvaniËna|molba...
{68816}{68931}Imate li francuski pasoö?|- Uniötili su ga.
{68937}{69004}Onda ste sovjetska graanka.
{69034}{69116}Obratite se njima.
{69155}{69227}Nemojte tako!|Preduzmite neöto!
{69233}{69272}Ne mogu to da primim.
{69280}{69381}Gluposti! Vidite da govori|istinu. Dajte mi pismo.
{69387}{69479}NeÊe vam vredeti.|Niko neÊe pomoÊi.
{69597}{69644}Vratite mi to.
{69733}{69852}Moja porodica i ja smo|zadovoljni ûivotom.
{69880}{69974}Ne treba nam pomoÊ.|Vratite mi pismo.
{69994}{70051}Niste mi ga vi dali.
{70531}{70578}Znaö li öta rizikujeö?
{70583}{70692}Nije me briga, samo da odem.|UspeÊu, makar i bez tebe!
{70996}{71020}Sluöaj, Aleksej...
{71029}{71107}Ne govori... Daj mi ruku.
{71222}{71271}Tvoj tvrdoglavi francuski|mozak ne shvata naö poloûaj.
{71277}{71394}On dobro shvata|öta si ti postao.
{71403}{71505}Nastojim da spasem|tebe i Serjoûu.
{71510}{71610}Zahvaljujeö se onima koji|su nas zarobili.
{71616}{71665}Izdao si me!
{71737}{71858}Svi koji su doöli s nama|pobijeni su, ili zatvoreni.
{71863}{71991}Uradio sam sve zbog tebe i|Serjoûe. I nastaviÊu tako.
{72274}{72348}Nemam izbora, Mari...
{72355}{72452}Umesto da pomogneö,|ti me optuûujeö.
{72460}{72571}Ujutro, uveËe,|kadgod doem kuÊi,
{72580}{72689}u tvom pogledu vidim|neprijateljstvo.
{72695}{72767}Ne mogu to da podnesem.
{72852}{72946}Viöe neÊeö ni da vodimo|ljubav u ovoj sobi.
{72952}{73075}Dosta! Dozlogrdilo mi je!|- NOSI SE, INTELEKTUALCE!
{73242}{73353}Spavao sam s Olgom...
{73485}{73629}Ona me drugaËije gleda.
{73762}{73811}Gubi se, Aleksej!
{73846}{73901}Napolje iz ove sobe!
{74155}{74181}Napolje!
{74817}{74883}Mari, otvori.
{75001}{75042}HoÊu cigarete!
{75678}{75766}Posvaali ste se?|Ne puöta te da ueö?
{76141}{76254}DVA MESECA KASNIJE
{77251}{77300}Vi ste mu trener?
{77581}{77614}Pa, kako ide?
{77686}{77735}Svaki dan pliva.
{77748}{77826}I ja sam ovde plivao.|Odavno...
{77930}{77996}Znao sam da on neÊe|diÊi ruke.
{78397}{78489}Kaûite Saöi da doe u bazen.|Voda je toplija.
{78702}{78761}Kako je, mali? U redu?
{78931}{78961}Otvoreno je!
{78975}{79007}Dobro jutro!
{79050}{79091}HoÊeö da jedeö s nama?
{79098}{79141}Jeo sam s mamom.
{79177}{79255}Ne mogu da reöim|jedan problem.
{79409}{79442}Sam Êu...
{79503}{79591}Zaöto juËe nisi doöao?|- Zaboravio sam.
{79600}{79655}äta Êeö danas da radiö?
{79661}{79729}IÊi Êu u park sa Saöom.
{79736}{79801}A mama? - Ne znam.
{79824}{79860}Dobro...
{79993}{80069}Nemoj tako pred|mojim sinom!
{80074}{80174}Tvoj sin zna u|kakvim smo odnosima.
{80284}{80376}Ja sam obiËna ûena...
{80386}{80464}SreÊna sam öto si sa mnom.
{80471}{80547}éelim da bude ovako.
{80752}{80813}Pismo za tvoju ûenu.
{80847}{80933}»itala si ga? - Nisam.|Na francuskom je.
{81123}{81226}Mene su uËili da ne Ëitam|tua pisma.
{81333}{81398}Ja nisam rasla kao ti.
{81633}{81771}Sve je u redu...|Samo vam treba odmor.
{81809}{81872}Ne umem da se odmaram.
{81880}{81939}I ti si sliËan.
{81962}{82023}Ja volim da radim.
{82080}{82203}Aleksej...|OtkriÊu ti tajnu.
{82208}{82310}Odlazim na viöu duûnost.
{82335}{82431}»estitam!|NedostajaÊete nam.
{82501}{82694}PremestiÊu te u bolnicu kakvu|ni u Francuskoj nisi video.
{82738}{82851}PremestiÊemo te u dvosoban|stan.
{82859}{82976}UseliÊeö se s onom...|Olgom.
{82999}{83044}Ona je proverena.
{83050}{83099}VeÊ su vam otkucali?
{83106}{83268}Samo... moraÊeö da nam|vratiö sobu koju imaö.
{83303}{83406}Ne mogu. U njoj su|moja ûena i sin.
{83426}{83559}Razvedite se.|Onda Êe da zadrûi sobu.
{83602}{83674}Moraö brzo da odluËiö.
{83682}{83774}Ja volim svoju ûenu.
{83884}{84079}Zar da im kaûem da voliö|svoju, a ûiviö s drugom?
{84091}{84188}To je mnogo francuski.
{84260}{84398}Ipak je bolje da|se razvedeö.
{84415}{84458}Sve najbolje!
{85596}{85651}"Nemojte da piöete|mojoj ûeni..."
{85695}{85725}Zdravo!
{85777}{85865}U kuÊi govorimo francuski.
{85889}{85942}Ne, nego ruski.
{86012}{86082}Nisi zavröio zadatke?|- Sad Êu.
{86089}{86165}Ja sam kasno stigao...|A gde si ti bila?
{86188}{86247}Treba li ti tata joö?
{86310}{86380}Treba da razgovaramo.|- Sve smo kazali.
{86438}{86493}HoÊu da se vratim kod vas.
{86515}{86549}Kasno je.
{86936}{87064}PoËela je selekcija za|evropski öampionat.
{87071}{87291}Selektor dolazi kroz 3 nedelje.|UzeÊe najbolje meu najboljima.
{87296}{87374}Od veËeras svi stanujete|u domu!
{87405}{87535}äampionat je na zapadu,|a tamo nas preziru.
{87674}{87762}Kaûi opet: Te reËi|divno zvuËe.
{87781}{87846}U BeËu, u Austriji.
{87861}{87916}ZvuËi lepo, kao Pariz.
{87931}{88002}Tek treba da me izaberu.
{88019}{88095}IzabraÊe te.|Sigurna sam.
{88134}{88210}Zaöto? - Zato öto|nemaö izbora.
{88229}{88280}äto mi nemamo izbora.
{88433}{88525}Kad stigneö u BeË,|idi u francuski konzulat.
{88536}{88593}Oni Êete poslati|u Francusku.
{88600}{88736}Otii kod mojih. Ne znaju|ni da li sam ûiva.
{88745}{88808}Onda zajedno kod|one glumice.
{88814}{88880}Nije me zaboravila.|Znam. PomoÊi Êe vam.
{88885}{88932}Ako stignem u Francusku,
{88937}{88990}moûda neÊu moÊi|da ti pomognem.
{88995}{89102}äta Êu ja tamo,|ako si ti ovde?
{89158}{89213}Neka se uËesnici spreme!
{92527}{92564}Je li to Vasiljev?
{92571}{92616}Tvoj miljenik?
{92633}{92684}Ti si pao na teme!
{92724}{92771}Pogledala sam dosije.
{92780}{92885}Svi iz te porodice su|narodni neprijatelji!
{93147}{93192}äta opet petljate?
{93417}{93456}Ukrali ste kokoöke?
{93462}{93527}Same su nam doöle.
{93535}{93615}Kuda Êeö, susedo?|Lepa si!
{93630}{93685}Na Bojkov roendan!
{93700}{93755}Za Serjoûu!
{93819}{93862}Za madam Mari!
{93870}{93981}Dajemo na zajam.|Sutra Êeö vratiti!
{93988}{94045}Nasledili smo od bake.
{94111}{94216}Hvala.|- »etiri puta. Za tebe!
{94222}{94261}Otvori. To je Saöa.
{94632}{94677}Treba ti veliki broj.
{94712}{94751}Spremi stvari, duöo.
{94935}{95062}Ako Saöa ode na öampionat,|hoÊeö li ti ostati?
{95138}{95263}Ja ostajem s tobom.|Uvek Êu biti s tobom.
{95754}{95823}Daj Serjoûi da jede.|Neka legne ranije.
{95829}{95919}Kuda Êeö ti? - Izlazim.|OstaÊeö do kasno? - Sigurno.
{96234}{96289}Spremaö se, öampione!
{96297}{96381}Joö ne znam.|ReÊi Êe nam na kraju.
{96971}{97041}Drugovi! Poklon od nas!
{97547}{97602}Za tebe i za naöe|prijateljstvo!
{97625}{97674}Za prijateljstvo!
{98112}{98184}Stvorili ste pravog|sportistu!
{98284}{98446}Imam lepu vest:|izabrali su te.
{98692}{98749}Borio sam se za tebe.
{98761}{98835}Nadam se da neÊeö da|praviö gluposti.
{98840}{98887}SergejeviËu, taman posla!
{98892}{98953}Ako praviö gluposti,|ja Êu da platim.
{98958}{98986}Shvatio sam.
{98991}{99019}Verujem ti.
{99039}{99078}Pardon, momci!
{102198}{102265}Hvala öto ste odmah doöli.
{102366}{102415}äta je bilo sa Saöom?
{102452}{102631}Ne ide u BeË. Pogledali|su njegov prtljag.
{102721}{102782}To su pisma za moju|porodicu.
{102801}{102838}Gde je Saöa?
{102845}{102945}Moûda je ûeleo da|pisma preda liËno.
{102967}{103024}Gde je on?
{103051}{103129}U Nacionalnom centru|na Crnom moru.
{103139}{103268}Tamo öaljemo najbolje|sportiste. PosmatraÊemo ga.
{103369}{103459}Ostavite ga na miru.
{103470}{103577}Ne ûeli da i dalje|utiËete na njega.
{104112}{104293}"Tri savröena dana,|pravi medeni mesec."
{104354}{104424}"Bili su u hotelu|u Bolonji."
{104445}{104527}"Zatvorili su ûaluzine|i vrata"
{104549}{104672}"pod prekrili cveÊem i|hranili se sladoledom."
{104763}{104895}"UveËe su brodom odlazili|na ostrvo da veËeraju..."
{105619}{105718}"Gradska buka bila|je sve dalja."
{105741}{105854}"Skidala bi öeöir i|popela se na ostrvo."
{105872}{105997}"Leûali su na travi,|ljubili se ispod topola"....
{106012}{106121}"i ûeleli, kao Robinzon,|da stalno ûive tu",
{106130}{106280}"gde im se Ëinilo da je|najlepöe na svetu."
{107058}{107101}Kuda tako ûuriö?|- U nabavku.
{107108}{107167}Radnje su zatvorene.|- Pusti me!
{107493}{107577}Upamti: moj ûivot se|tebe ne tiËe.
{107585}{107634}Zar ti öefovi nisu|objasnili?
{107639}{107731}Videla sam nekog Ëoveka|kako ubacuje pismo.
{107739}{107778}PrijaviÊu te.
{107786}{107866}Tu bi pogreöila. Ja sam|uticajan Ëlan partije.
{107873}{107951}Niko ne veruje|ljubomornim ûenama.
{108179}{108261}Bolje gledaj da preeö|da ûiviö negde drugde.
{108267}{108320}Ti Êeö mene da izbaciö?
{108326}{108375}TraûiÊu da ti nau sobu.
{108382}{108505}Znam da si bio sa mnom da|ne bih pratila tvoju ûenu!
{108511}{108589}Sad ti ne trebam,|pa si me bacio!
{108598}{108682}Ti si pokvaren, da znaö!
{108701}{108750}Ti si ubre!
{108967}{109001}»etiri puta. Za nas.
{109191}{109296}Ne brini za mene, mama.|Meni je lepo ovde.
{109415}{109489}Imamo gosta.
{109540}{109599}Mogao si i da piöeö.
{109604}{109700}Stalno sam trenirao.
{109895}{109996}Poklon. Nasledili smo|Od dede.
{110011}{110070}Sedi. Tata je spremio supu.
{110137}{110173}Ti si porastao.
{110206}{110267}Kako kaûu preko radija:
{110276}{110399}ûivot je bolji,|ûivot je veseliji.
{110412}{110486}VraÊaö li se ovamo,|u Kijev?
{110494}{110551}Ne. Dali su mi jedan dan.
{110572}{110608}Hvala vam.
{110844}{110887}To je sitnica.
{110908}{110953}Idem na groblje.|HoÊeö li sa mnom?
{111226}{111277}NeÊu te zaboraviti, bako.
{111306}{111411}PamtiÊu öta si govorila,|Ëemu si me uËila.
{111622}{111725}Odlazim, Mari.|Idem na zapad.
{111753}{111789}Kako Êeö?
{111803}{111869}U Odesu dolaze brodovi...
{111902}{112015}PreveöÊe me jedan kapetan,|TurËin. VeÊ je to radio.
{112082}{112189}Kakvi su izgledi:|1prema 10, 15?
{112196}{112260}Ako uhvate, streljaju,|je li?
{112267}{112345}UspeÊu. Ti Êeö posle|da doeö.
{112351}{112417}Nemoj. To je bezumno.
{112473}{112549}Mnogo si se promenila!
{112565}{112697}Dobra supruga DR. Golovina!|Ne mogu da te prepoznam.
{112826}{112906}Izvini. Ljubomoran sam.
{112965}{113012}U pravu si.
{113066}{113138}Treba da mi pomogneö.
{113165}{113241}Treba mi novac.|- PokuöaÊu.
{113268}{113371}Treba da mi ga doneseö|u Odesu.
{113382}{113429}Nemam dozvolu da putujem.
{113436}{113547}Armijski hor gostuje u Odesi|kroz 3 meseca.
{113553}{113604}Zamoli Bojka da te povede.
{113612}{113669}Na sve si mislio!
{113680}{113739}Ti si me nauËila.
{113783}{113904}Upornost, sloboda po|svaku cenu.
{114324}{114359}Da li je ukusno?
{114405}{114460}Ima li sladoleda|u Francuskoj?
{114484}{114539}Viöe se ne seÊam.
{114920}{114979}Moûeö li da mi prodaö|neöto?
{114989}{115069}Ne bavimo se time.|- Zavisi öta...
{115213}{115345}Odakle ti to? - Od bake.
{115398}{115498}Zadrûi ga. To je|deliÊ Francuske.
{115511}{115552}Treba mi novac...
{115628}{115669}Ja te volim...
{115696}{115729}Drû'te ga!
{115748}{115791}Dosta je bilo!
{115978}{116031}Nemoj da ideö,|molim te.
{116042}{116173}Samo 10 dana. Nisam|nigde bila veÊ dve godine.
{116239}{116317}Strpi se. IÊi Êemo|na Krim.
{116339}{116411}NeÊu da odustanem|od putovanja.
{116522}{116618}Odesa! Da li si ti|Saöina ljubavnica?
{116636}{116728}Ne!
{116784}{116847}Mogu da te spreËim...
{116901}{116950}Onda Êu da te napustim.
{117258}{117307}ObeÊavam da Êe sve|biti u redu.
{117545}{117584}Vi ste Mari Golovina?
{117597}{117683}»eka vas neki mladiÊ.|Kod ulaza.
{117696}{117741}Kaûe da ste roaci.
{117766}{117802}Dobro. Hvala.
{118476}{118587}Brod je u luci. Plaöio|sam se da neÊeö doÊi.
{118672}{118739}Slobodna sam do predstave.
{118749}{118790}Kuda Êemo?
{119406}{119443}Nisu vas pratili?
{119502}{119553}Doneli smo novac.
{119607}{119668}Ne mogu da vas povedem.
{119675}{119739}Nestao je Ëovek koji mi|je pomogao u luci.
{119745}{119790}Uhapöen?
{119796}{119911}Ne znam. NoÊas se|Ëula neka pucnjava.
{120011}{120085}Idite. Nismo se nikad|videli.
{120132}{120173}Sasluöajte me!
{120241}{120333}Svi brodovi idu u ovom|pravcu...
{120429}{120587}Na obali ima stena koja se|spuöta u more.
{120635}{120674}Ne mogu da preem.
{120681}{120740}Ali ja mogu da doplivam.
{120747}{120916}To je dobrih deset|morskih milja.
{120972}{121058}Treba mi 5, moûda 6 sati.
{121071}{121155}Nemoj. To je nemoguÊe.
{121170}{121235}To joö niko nije izveo.
{121242}{121314}Znam da ja mogu.|- To je ludost.
{121367}{121484}Ako izdrûite 6 sati u moru|i ako vas naem,
{121496}{121572}spustiÊu vam Ëamac.
{121579}{121638}NeÊu da vas Ëekam.
{121671}{121704}Imate li novac?
{121711}{121777}Stalo mu je samo do novca.
{121784}{121864}To je samoubistvo...|Saöa, molim te...
{121895}{121998}Rizikujem kako ja hoÊu.|Ovo je moj ûivot.
{122007}{122056}Daj novac. - Ne.
{122130}{122167}Daj odmah.
{122269}{122316}Moram da poem.
{122399}{122471}Ovo radim zbog tebe,|zbog nas.
{122480}{122562}Pomozi mi. Pogledaj me.
{122877}{122926}Mari, gde si bila?
{122936}{123030}Nisam te poveo u Odesu|da se öetaö.
{123065}{123155}Ovde se radi, nismo|na odmoru!
{123270}{123321}Da li me poznajeö?
{127118}{127161}Zaöto te je Bojko poveo?
{127173}{127210}Pitajte njega.
{127238}{127297}Ostavila si muûa i sina.
{127351}{127460}Koji je tvoj ljubavnik?|Da nije pukovnik?
{127467}{127582}Dosta mi je vaöih insinuacija.|Pustite me da radim.
{129163}{129189}Gde je Mari?
{129251}{129314}Moj kolega iz Kijeva|je dobar policajac.
{129319}{129389}Nije pametan, ali|je revnosan.
{129400}{129583}Iöla si u Kijev da vidiö|plivaËa, Vasiljeva.
{129604}{129665}On ti je ljubavnik.
{129738}{129758}Sluöam...
{129766}{129852}»im sazna da ste me|uhapsili, puk. Bojko...
{129859}{129943}Taj viöe ne moûe da|ti pomogne.
{129954}{130100}TraûiÊemo da nam|poöalju Vasiljeva.
{131521}{131572}ProgovoriÊeö ti,|kurvetino!
{131613}{131654}Gde je on?
{131702}{131749}Kurvo francuska!
{131760}{131793}Govori!
{131798}{131843}UbiÊu te!
{133141}{133221}MESEC DANA KASNIJE
{133949}{133963}Mari.
{133972}{134023}Nemate pravo da|razgovarate.
{134030}{134093}Vaöa ûena je|imperijalistiËki öpijun.
{134100}{134166}Trebalo je da je|odmah ubijem.
{134171}{134208}Za öta je krivite?
{134214}{134265}Znate Saöu Vasiljeva?
{134270}{134354}Zavela ga je, obrlatila.
{134366}{134450}Ganjala ga je sve do Odese.
{134465}{134580}Organizovala je bekstvo|uz pomoÊ CIA-a.
{134626}{134690}Kriva je öto se udavio!
{134751}{134820}Gluposti! Moja ûena|je nevina!
{134839}{134886}Potpisala je priznanje.
{135013}{135054}Potpisala si?...
{135157}{135202}äta su ti uradili?
{135295}{135321}Ne verujem vam.
{135330}{135373}On ne veruje!
{135409}{135460}äta je ovo?
{135505}{135579}Vasiljev s vaöom|svastikom?
{135656}{135715}Zaöto ste kazali da|je poginuo?
{135742}{135797}Kuda sreÊe da jeste!
{135811}{135870}On je u Francuskoj!|Slobodan je!
{136045}{136109}Sad znaö s kim si ûiveo.
{136153}{136198}Potpiöi izjavu.
{136213}{136268}Priznajeö da je izdajnik|i odriËeö je se.
{136274}{136308}Nikad!
{136314}{136406}PotpisaÊeö! Ti voliö|svog sina!
{136462}{136528}Potpiöi, Aleksej,|molim te.
{136635}{136723}P A R I Z|NARODNO POZORläTE
{136756}{136789}Dobro veËe, madam.
{136849}{136877}Da li je doöao?
{136884}{136925}»eka vas u vaöoj loûi.
{136941}{136988}Vi ga danas motrite?
{136996}{137041}Ne motrimo - Ëuvamo ga.
{137090}{137135}Ne sad. ZvaÊu te.
{137176}{137285}Ministarstvo je odbilo|zahtev sovjetske ambasade.
{137333}{137436}NeÊe te vratiti, ali|ne moûeö da ostaneö.
{137463}{137559}Mnogo se priËalo o tebi,|pa Rusi zahtevaju...
{137566}{137648}Kanada Êete prihvatiti.
{137673}{137757}Maloletan si,|bez porodice...
{137771}{137832}Tamo Êeö poËeti|novi ûivot.
{137838}{137924}Jedino ovde mogu da|pomognem Mari.
{137969}{138092}Za nju je bolje da|odeö iz Francuske.
{138100}{138161}Rekli su mi uvijeno,|ali to je to...
{138166}{138215}Ja neÊu da idem!
{138236}{138279}MoraÊeö!
{138299}{138368}Kakva je to sloboda?
{138418}{138477}Ja Êu da pomognem Mari.
{138482}{138519}Kako?
{138547}{138625}Ne mogu da ti kaûem.|Zasad ne...
{138672}{138723}Da li mi verujeö?
{138791}{138879}Shvatam. Treba da|nestanem...
{139106}{139144}Moram da idem.
{139221}{139305}Uzeo si moje stvari?|Jesu li kola tu?
{139317}{139351}äta vam je, madam?
{139358}{139413}Trebalo je da ga zadrûim.
{139895}{139921}Kuda Êete?
{139938}{139975}Je li Saöa tu?
{139987}{140034}Gde je soba?
{140067}{140106}Brzo!
{140255}{140302}Otvarajte! Ne Ëekajte!
{140483}{140509}Do avola!
{140686}{140772}Ostanite tu.|PozvaÊu bolnicu.
{141281}{141512}Saöa, tu sam... uz tebe.|SpaöÊu Mari, kunem ti se.
{141517}{141564}Samo ti ûivi!
{141584}{141641}»ujeö li?|Moraö da ûiviö!
{141674}{141781}POSLE äEST GODINA|TRANZITNI LOGOR
{143577}{143669}KA SVETLOJ BUDU»NOSTI|»OVE»ANSTVA - KOMUNIZMU...
{143839}{143983}Svilena je... Kupio sam u|dva broja. nisam znao koji...
{144071}{144205}Nisi se promenila. Lepöa|si nego öto pamtim.
{144214}{144294}Hvala. Oprosti öto sam...
{144398}{144507}Treba ti vremena...
{144584}{144621}PomoÊi Êu ti.
{144626}{144689}Radije bih bila sama.
{145250}{145291}Volim te, Mari.
{145334}{145377}Svröeno je, Aleksej.
{145421}{145491}Meu nama nikad neÊe|biti svröeno.
{145626}{145749}Stidim se... Nikad neÊu|oprati smrad logora.
{145943}{146004}Ljubavi moja...
{146023}{146093}Mnogo te volim.
{146373}{146453}Tata i ja smo znali|da Êeö izaÊi.
{146465}{146532}Kad je postao upravnik|bolnice,
{146539}{146607}pisao je drugu Staljinu.
{146613}{146699}Staljin je, naûalost, umro.
{146844}{146971}Nina mi je pomogla.|Sad je glavna u sindikatu.
{147001}{147075}Bila si osuena greökom.
{147083}{147183}Nije bila greöka.|Kriva sam.
{147233}{147304}Ja sam organizovala|Saöino bekstvo.
{147344}{147465}»uo sam o Saöi.|éivi u Kanadi.
{147523}{147609}Radila sam to i za sebe.
{148532}{148587}Moj mali deËko.
{148738}{148812}Kad oni stiûu?
{148871}{149027}FRANCUSKA AMBASADA|U SOFIJI
{149032}{149112}Sutra, ako ide prema planu.|- Zaöto ovamo?
{149117}{149160}Sofija je jedini grad|iza gvozdene zavese
{149165}{149210}gde je moj drug ambasador.
{149216}{149302}Odavno ovo radiö?|- »im si postavljen.
{149309}{149342}Ti si luda.
{149348}{149415}Ti me barem poznajeö.|Uvek sam bila ovakva.
{149419}{149482}Mene uhode sve vreme.
{149524}{149616}Nemaö pojma u kakvoj|sam opasnosti.
{149651}{149717}Uostalom, i ti si!
{149721}{149782}PremestiÊe te u|najgorem sluËaju,
{149790}{149878}a mene Êe diskretno da|sklone. NeÊemo na robiju.
{149886}{150007}Briga njih öto ti radiö za|mir, za proletere!
{150015}{150070}Zaöto pomaûeö toj ûeni?
{150210}{150284}Videla si je nekoliko|minuta.
{150299}{150342}ObeÊala sam.
{150464}{150562}Iskreno govoreÊi:|nisam ûelela da doemo.
{150569}{150694}Sad mi je ipak drago|öto smo u Sofiji.
{150702}{150757}Lepo smo radili.
{150770}{150883}Zahvaljujem svima, a|posebno drugu Golovinu,
{150904}{151003}öto je predloûio ovaj put.
{151020}{151164}Da nazdravimo za saradnju|naöe dve zemlje!
{151328}{151468}Imam jednu molbu... Moja|ûena je opet kupila luster.
{151501}{151577}PomoÊi Êeö mi na carini?
{151594}{151724}ImaÊu neprijatnosti|zbog tvoje ûene.
{153381}{153428}Hvala ti, éan-Lui.
{153484}{153545}To je sve öto mogu|da uËinim.
{153575}{153665}Odnesi pasoö toj ûeni|i gotovo.
{153701}{153820}Neka se vrati u Kijev i|ne pominji je viöe.
{154112}{154147}Gde je mama?
{154168}{154200}Izaöla je.
{154852}{154882}Da li kasnimo?
{155033}{155105}SeÊaö li se one francuske|glumice? - Da.
{155124}{155216}U Sofiji je. OdveöÊe te|u ambasadu.
{155249}{155279}Ma öta priËaö?
{155307}{155385}Idemo dole.|PoÊi Êeö sa njom...
{155447}{155481}Niöta ne razumem.
{155488}{155582}Ambasador je Gabrijelin|prijatelj.
{155589}{155642}Jedinstvena prilika.
{155702}{155761}Ovo Ëekam veÊ 10 godina.
{155854}{155926}Nisi mi rekao.|- Nisam bio siguran.
{155978}{156077}Hajdemo. Sad Êe i|ostali da dou.
{156103}{156150}A ti? A Serjoûa?
{156158}{156229}Serjoûa ide s tobom,|a ja se vraÊam u Kijev.
{156251}{156356}PoslaÊe te u logor.
{156369}{156482}NeÊe. MisliÊe da si|me izneverila.
{156564}{156602}Poi s nama.
{156615}{156738}Tebe Êe da zaötite poöto|si Francuskinja.
{156746}{156814}Ja sam sovjetski graanin.
{157644}{157682}»aj molim...
{157706}{157755}Ima li koga iz delegacije?
{157762}{157798}Nisam ih video.
{159358}{159384}Idite.
{159561}{159612}DoÊi Êu.
{159858}{159899}ObeÊavam ti.
{159947}{159973}Kada?
{160377}{160436}Hajdemo, mama.
{160868}{160973}Imate li kljuË od sobe?|- Da, hvala.
{162748}{162828}Obucite ovo. Da|izgledate kao na zapadu.
{162875}{162949}Treba da poemo pored|bugarskih policajaca.
{162993}{163046}Vaö je, Mari.
{163528}{163563}Nestali, isparili!
{163570}{163644}Pustite da proem.|Sad Êu da ih naem.
{163653}{163706}Znao si, priznaj!
{163776}{163866}Svi Êemo imati probleme|zbog tebe! - Smirite se.
{163873}{163938}Ja Êu prvi. - Smirite se.
{164267}{164335}Ne brinite. BiÊe dobro.
{164760}{164817}Izvadite pasoö.
{165642}{165691}Pustite ih. Sa mnom su!
{165913}{165991}Ovo je Francuska.|Slobodni ste.
{166198}{166243}Hajdemo...
{166570}{166627}Preduzmite neöto!|Dajte vode!
{166750}{166801}Aleksej... Boûe...
{166899}{166954}Da bi ostao u vezi|sa Gabrelom,
{166962}{167040}tata je saËekivao|francuske delegacije.
{167047}{167121}Po cenu da bude prijavljen.
{167176}{167252}Odgovori nisu|stizali mesecima.
{167264}{167360}Na kraju mi je sve|objasnio.
{167381}{167514}NoÊima smo razgovarali.
{167578}{167675}Nisam hteo da se rastajem|Od tebe.
{168363}{168552}Ambasador je bio tvrdoglav...|Bugari Êe vas pustiti
{168560}{168729}da izaete, ali moûda|Êe da traûe protiv-uslugu...
{168786}{168893}Moûda Êemo im izruËiti|nekog azilanta.
{168899}{169119}Vaûno je da ste vi ovde.|- Ne idem bez njega.
{169152}{169189}O Ëemu priËate?
{169195}{169262}Aleksej mora da doe.
{169320}{169379}On neÊe doÊi.
{169387}{169467}Zna da sad ne moûemo|da mu pomognemo.
{169490}{169557}Godinama se borio|da izbavi vas.
{169574}{169617}Nije mario za ostalo.
{170120}{170309}Kaûi mi, vrlo mi je vaûno.|Da li se znao öta ona radi?
{170428}{170495}Da li si joj pomogao?
{170510}{170569}Nisam znao.
{170607}{170732}Kad su nestali, mislio|sam da su pobegli...
{170751}{170852}ali da Êe da se vrate.
{170944}{171053}Verujem da Êe da|stignu na voz...
{171623}{171763}TOG ISTOG DANA SMO OTläLI|U SLOBODNI SVET. U GR»KU.
{171793}{171856}Nl»EG SE NE SE»AM.|SPAVALA SAM.
{172866}{172929}ALEKSEJA SU POSLALI|NA OSTRVO SAHALIN,
{172934}{173014}KAO LEKARA U LOGORU.
{173554}{173628}30 GODINA KASNIJE, ZA|VREME GORBA»OVA,
{173635}{173676}SSSR SE OTVORIO.
{173683}{173765}ALEKSEJ JE 1987.|MOGAO DA ODE U FRANCUSKU.
{173800}{173900}Kraj
{174000}{175000}Movie by KOSTA ZULU LESKOVAC
{175025}{176525}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
