{6}{193}Razlog öto sam poslat u ludnicu je öto sam|video da tvoj tata ubija tvoju mamu
{193}{276}-Vil,moja mama je umrla u|saobracajnoj nesreci
{276}{381}-Ne,to je ûeleo da poverujeö,|ali ja sam bio tu Lori
{381}{533}Prikradao sam se tvojoj sobi kao i uvek|samo öto ti nisi bila tu
{551}{649}Video sam ga da je ubija
{649}{744}-TataÖ-Izadji iz kombija|Izadji iz kombija!
{744}{818}-Tata öta to radiö?|-Lori svuda sam te traûio
{818}{889}-Sklanjaj se od nje|-U velikoj si nevolji znaö
{889}{959}-Kao da me je briga|-Ulazi u kucu!
{959}{1101}Vodim te nazad u Veston...-Ne,ne veruj mu|öta god radiö ne idi sa njim u kucu Lori
{1101}{1194}Ne,sluöaj me,on me je zatvorio tamo
{1194}{1323}-Nisi razumeo,joö ne razumeö,zbunjen si|-Prestanite,prestanite,obojica
{1323}{1456}-Dodjavola Vile,necu dopustiti da mi opet|ugroziö cerkuÖ-Prestanite!
{1456}{1574}Prestanite,prestanite,stani!|-Lori
{1676}{1768}Lori,Lori
{1789}{1893}-Da li je mama umrla u saobracajnoj nesreci?|-Da,naravno da jeste
{1893}{2025}-Dokaûi,pokaûi mi smrtovnicu|Pokaûi mi izveötaj sa autopsije
{2025}{2159}-Lori,mislim da sad nije vreme|-Dokaûi tata,mislim da je sad savröeno vreme
{2159}{2334}Zaöto mi nisi rekao za Veston Hils,ti radiö tamo|a ja sam mislila da si lekar opöte prakse
{2334}{2434}-Da,vröim neke konsultacije tamo sad aliÖ
{2434}{2550}Öto nije ono öto misliö|-O moj Boûe
{2550}{2698}Znaci znao si sve vreme|-Lori,sluöaj me
{2710}{2822}Uznemirena siÖoboje smo
{2822}{2955}Ja mislim da ti sad treba viöe|od svega malo odmora
{2955}{3097}Da ti dam neke pilule,od toga ceö zaspati|pa cemo razgovarati ujutru
{3097}{3200}-Necu da spavam tata,|hocu da znam zaöto si me lagao
{3200}{3294}-Razgovaracemo ujutru,uradi to öto kaûem|Lori!
{3294}{3416}Lori,Lori
{3416}{3511}Otvori vrata,otvori vrata|-Odlazi
{3511}{3652}-Dodjavola Lori pusti me unutra,Lori!
{3738}{3831}Dodjavola
{3843}{3974}Lori,Lori!
{3999}{4149}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{4301}{4441}-U redu je,ja sam,ja sam
{4495}{4614}Ne znam kako je tvoj otac povezan|sa svim ovim aliÖ
{4614}{4745}Mark je u pravu,u toku je neko|zataökavanje oko Krugera
{4758}{4850}Ne moûemo verovati policiji
{4850}{4956}Ne moûemo verovati nikom odraslom
{4956}{5046}-äta cemo da radimo?|-Idemo do Marka
{5046}{5183}On je ekspert u vezi sa ovim,|on ce znati öta se deöava
{5391}{5520}-Uvek si mi bio uzor braco
{6469}{6598}Mogu da ostanem budan
{7262}{7389}-Zdravo Mark,zaboravio si na mene,zar ne?
{7389}{7516}Tako je,svi su zaboravili,|zato se niko nije viöe plaöio
{7516}{7628}Zato mi je bio potreban Dûejson da ubija za|mene,da bih ih naterao da me se sete
{7628}{7748}Ali sad nece da stane,usijana glava
{7961}{8075}-Nije stvarnoÖ
{8102}{8266}Neka me neko probudi,molim vas!
{8495}{8588}-Mark,Mark probudi se
{8588}{8724}-Treba da mi poöaljeö jednu malu poruku,|to je sve samo malu poruku
{8724}{8875}-Necu to da uradim,necu|-Ne!
{8875}{9001}-Necu to da uradim
{9156}{9342}-Onda cu morati da je prenesem sam
{9666}{9799}-Pomozite mi
{9870}{9992}-Ne!
{10019}{10174}-Prenesi malu poruku za mene,hoceö
{10393}{10521}-äerife,kombinovao sam poglede svedoka|na ubicu sa hokejaökom maskom
{10521}{10682}-Vec znamo ko je ovo uradioÖ-äerife,uveli|smo policijski cas za sve ispod 18
{10682}{10831}-24 casa blokada,niko ne izlazi,niko ne ulazi,|zadrûacemo kuckinog sina da se ne proöiri dalje
{10831}{10896}-Da,gospodine
{10896}{11004}-Ser,zar nam ne treba FBI|-Bez stranaca Stabs
{11004}{11160}Uspecemo,vec smo ga ranije zaustavili|-Izgubio sam se,koga ste zaustavili
{11160}{11248}-Njegovo ime ne izgovaramo glasno
{11261}{11366}Nisi odavde,ne ocekujem da shvatiö|-S duûnim poötovanjem öerifeÖ
{11366}{11460}Ömislim da imamo imitatora ubice Dûejsona|sa Kristalnog jezera
{11460}{11562}-Sluöaj me,mi ovde radimo neke stvari|s razlogom
{11562}{11692}I to nam je dalo 4 godine mira,|pa ti ili radi svoj posao i cutiÖ
{11692}{11795}Öili cu te zatvoriti,da li me razumeö?
{11795}{11914}Da li razumeö?|-Da,ser
{12176}{12325}-Ne smemo zaspati,cak i ako odemo|Fredi moûe da nas sredi
{12325}{12464}Svi znamo za njega i svi ga se plaöimo
{12464}{12625}Naö strah mu je dao moc|Gotovi smo
{12646}{12777}-Zajebi seronju,kakva to pickica|ti dolazi u snovima
{12777}{12905}Onog velikog drkadûije kod kukuruziöta|treba da se plaöimo
{12905}{13033}Recite mi ko je to koji kurac|-Ime je Dûejson
{13033}{13176}-Sranje covece,kako si znao da smo ovde?
{13176}{13280}-Niöta licno ali onaj SKUBI kombi napolju|nije baö olicenje suptilnosti
{13280}{13393}Nikad ne drûi kljuceve u kolima|-Super,sad smo totalno sjebani
{13393}{13517}-Niste,doöao sam da vam pomognem
{13517}{13688}Dûejson se navodno udavio u kampu na|Kristalnom jezeru u 1957 u 11 godini
{13688}{13834}Nisu ga pazili,napravili su greöku|koja je njegovu majku koötala ûivota
{13834}{13993}Legenda kaûe da se Dûejson vraca iz groba|da kazni sve koji se vrate u kamp
{13993}{14131}Mislim da imamo posla sa imitatorom|-Ne,ne,ne,nije imitator
{14131}{14248}Video sam öta radi,to je pravi Dûejson|-To je nemoguce,Dûejson je mrtav
{14248}{14330}-Da,bolje pocni da razmiöljaö öire ortakÖ
{14330}{14458}Neko definitivno kröi pravila realnosti|-Ima smisla na neki nacin
{14458}{14543}äta ako je Fredi vratio Dûejsona nazad
{14543}{14623}Jer je bio suviöe slab da krene za nama sam
{14623}{14747}Pa je iskoristio Dûejsona,znao je da cemo|misliti da je on ponovo,da ce se strah proöiriti
{14747}{14868}A sad kad je uspelo ne moûe da|ponovo iskljuci Dûejsona
{14868}{14967}-Cekaj malo,Fredija je ubila vatra,|a Dûejsona voda
{14967}{15097}Kako moûemo to da iskoristimo?-Mislim da|treba da se koncentriöemo prvo na Dûejsona
{15097}{15228}-Mislim da smo se sloûili da je Fredi pravi|problem,zar necemo njega prvog
{15228}{15341}-Ponudicemo Frediju ûrtvu|-Da,da,totalno
{15341}{15437}Kao devicu,nekog cistog
{15553}{15686}-Ortak ne gledaj u mene cak i ako platiö|i dalje se racuna
{15686}{15804}-Hajde,svi mi znamo ko je prava devica ovde
{15804}{15915}-TeaÖ-Hajde Lori,|znam da nisi bila sa Vilom
{15915}{16100}-Zaöto bih ja to hteo?|-Da bi kresnuo nekog kao ja
{16180}{16290}-Veûimo kucku
{16290}{16412}-äta?
{16412}{16597}-Ne brini andjele joö imaö mene,|hajde daj tatici poljubac
{16687}{16779}Tvoje oci kaûu ne,ne
{16779}{16950}Ali moja usta kaûu da,da
{16991}{17166}-Lori probudi seÖ-Lori|-To je bio san
{17267}{17360}-Sranje
{17411}{17515}-To sam donela iz sna|-Kako je to moguce?
{17515}{17618}-Sve je moguce,pobogu,|ti jednostavno ne kapiraö
{17618}{17709}-Od dvojice ubica nismo sigurni|ni budni ni na spavanju
{17709}{17853}-Ne ubija nas spavanje,vec naöi snovi|-U Vestonu Mark i ja nismo sanjali
{17853}{17989}-Da li ste bili na nekim lekovima?|-Da,zove se hipnosil
{17989}{18099}Nismo znali cemu sluûi,ali svi su ga uzimali
{18099}{18195}-HIPNOSIL,eksperimentalni lek
{18195}{18275}Nije joö odobren od FDA,sranje
{18275}{18375}Koristi se za potiskivanje snova
{18375}{18460}-Potrebne su nam te pilule,dovoljno za sve
{18460}{18577}Da li moûeö da nas vratiö u Veston Hils?
{18843}{18942}-Moram da zapalim jedan|-Uhvatice te
{18942}{19052}-Daj,öta mi moûe,da me uhapsi?
{19066}{19197}-Zabranjeni deo,hajde
{19527}{19756}-Ovo su oni koji nisu mogli da prestanu|da sanjaju
{19828}{19961}-Jesu li mrtvi?
{19961}{20107}-U komi su,dato im je previöe hipnosila
{20107}{20174}-Ko bi ovo uradio ljudima?
{20174}{20345}-Ime tvog oca je na dnu oba ova kartona
{20769}{20880}-äta koji mojÖ
{21178}{21295}Lepo
{21910}{22027}äta?
{22083}{22187}äta hocete?
{22187}{22327}Ne,ne znam gde je hipnosil,ok
{22555}{22709}Ne smem ovo da bacim,treba nam
{23137}{23230}-äta to radiö,trebaju nam te pilule?
{23230}{23322}Ortak,ne!
{23451}{23555}-Beûi odavde,idi
{23922}{24033}-äta to bi?
{24033}{24149}-Idemo da vidimo
{24721}{24794}-Sranje,sve su prazne|-Nastavi da traûiö
{24794}{24914}-Moûda ima neceg dole|-Mora da budu negde ovde
{25119}{25266}-Kriperu idemoÖ-Idemo|-äta cekaö,idemo
{25266}{25373}-Kriperu,ide ovamo,|moramo da idemo,odmah,idemo
{25373}{25509}-Pusti me da obavim ovo kucko|-äta?
{25612}{25760}-Hajde,idemo|-Cekaj,cekaj,vidi
{25775}{25863}-Dodji Frediju
{25863}{26009}Ovo su moja deca Dûejsone|Vrati se tamo gde pripadaö
{26257}{26362}-Jebi se
{26362}{26458}-Lindermane
{26458}{26598}-Ovo su moja deca Dûejsone|Vrati se tamo gde pripadaö
{26908}{27008}-Dûejsone,Dûejsone
{27008}{27132}Moj specijalni,specijalni decko
{27196}{27298}Razocarana sam u tebe Dûejsone|Nisi me posluöao
{27298}{27396}Trebao si da se vratiö kuci|kad ih ubijeö nekoliko
{27396}{27521}Krivim sebe,trebala sam da znam|da neceö prestati da ubijaö
{27521}{27633}Ti si kao veliki glupi pas koji ne zna|da prestane da jede
{27633}{27772}Cak i kad ti gazda kaûe da je dosta
{27930}{28065}-Vreme je da uspavamo tog loöeg psa
{28065}{28175}Zauvek!
{28272}{28385}Ne moju ruku
{28967}{29103}Dobrodoöao u moju nocnu moru
{29537}{29645}Novcic za tvoje misli öefe
{29645}{29765}O,usrao sam se
{30806}{30912}Zaöto neceö da umreö?
{31501}{31636}Dodji,dodji
{31999}{32161}Znaci ipak se necega plaöiö
{32346}{32436}-Kako ste me nagovorili na ovo?
{32436}{32517}-Zaöto to ne bi smo uradili ovde,|zaöto idemo cak na Kristalno jezero?
{32517}{32645}-To je kljucno,ako Dûejson pobedi,|bice kuci,tamo gde pripada
{32645}{32740} Nece nas viöe pratiti|-A ako Fredi pobedi?
{32740}{32865}-Bar ce Dûejsonu domaci teren pomoci
{33469}{33599}-Baö slatko,ti ruûni govnaru
{33599}{33769}Eto licaÖkoje samo mama moûe da voli
{33769}{33868}Da,nekud idemo
{33868}{33993}Da vidimo öta te zaista plaöi
{34085}{34214}Kopajmo malo dublje
{34903}{35091}Umirem da vidim kakve skelete|ti krijeö u ormanu
{35435}{35542}-Ozbiljno nam ponestaje uspavljivaca,|moûda joö samo jedna doza
{35542}{35713}Plus ono za LoriÖ-Skoro smo tu|-Bolje da krenemÖ-Ne,ne
{35794}{35869}Ne ûelim da ideö|-Vracam se
{35869}{35994}Dajte mi 15 minuta i budite me,|vraticu ono kopile Fredija sa mnom
{35994}{36159}Samo se postarajte da ga Dûejson ceka
{36182}{36286}Sada se spremam za spavanje
{37456}{37565}Zar necete pomoci klincu?|-Zar ne vidiö da sam zauzet
{37565}{37647}-Necete doci
{37673}{37824}-Nisam ja kriv öto je ova kucka hodajuci leö
{37975}{38071}-Proölo je 5 minuta|-Ovo je bio poslednji,nemamo viöe
{38071}{38210}-Smirite se,samo se opustite
{38561}{38712}-Daj mi ruku,daj mi ruku
{38798}{38917}Dûejsone molim te
{39152}{39254}-Neöto nije u redu,kao da se davi,|mora da ga ja Fredi ubio
{39254}{39390}-Treba nam ûivÖ-äta da radim,|da mu dam usta na usta
{39567}{39678}-O ne,ne znam to,necu to da radim,ne
{39678}{39815}-Uradio bih to sam ali imam astmu od 6|godine,nemam dovoljno moci u plucima
{39815}{39918}-Tea,ima astmu!
{39978}{40087}-Ti to moûeö,ti to moûeö samoÖ|-Ucuti!
{40087}{40215}Ti ne moraö to da radiö|-Znam jerÖ-Ucuti
{40284}{40367}Moj Boûe
{40576}{40723}-O coveceÖsranje
{41286}{41401}-Ti!
{41684}{41833}Neöto nije u redu Lori,|propustila si poziv za budjenje
{41833}{41937}Probudite me,imam ga,imam ga
{42020}{42159}Neee|-Lori probudi se,molim te
{42159}{42329}-HajdeÖ-Lori|-Momci vidite,skoro smo tamo
{42438}{42536}-Probudite me!
{42536}{42644}Tata nemoj
{43247}{43355}Tata,ne tata nemoj,tata!
{43370}{43513}-Mislim da imamo neöto zajednicko u vezi|sa kurvama koje ûive ovde
{43719}{43825}-Lori probudi se
{43825}{43930}-O sranje
{43974}{44161}-On je,ovde je|-Lori,hajde,probudi se
{44338}{44431}Moj Boûe
{44431}{44522}Hajde,budi se,Lori molim te probudi se
{44522}{44649}Lori molim te,Lori molim te
{44729}{44819}-Idi,idi
{45003}{45119}-Jebeni seronjo,dodjavola
{45166}{45294}-Dobrodoöla u moj svet kucko
{45305}{45541}Upozoricu te princezo,|prvi put je uvek bolno
{45936}{46144}-Beûi od nje!
{46379}{46529}-O ne
{46582}{46719}-Umri mala kucko
{48012}{48150}-Lindermane stvarno si povredjen|-Ne,ne brini za mene,samo je ogrebotina
{48150}{48225}Idi po pomoc|-äta?
{48225}{48328}-Samo cu malo da se odmorim minut|-Ne,neÖ-Da
{48328}{48464}Beûi odavde,idi po pomoc|-AliÖ-Samo idi
{48464}{48593}-Ok,ali vracam se öto pre
{49544}{49674}Lori!|-Baö si pametna je li kucko?
{49674}{49750}-Fredi!
{49956}{50062}-Baö slatko,tamno meso
{50062}{50164}-NeÖ-Idemo|-Tea,ne
{50164}{50274}-Ti si taj koga se svi plaöe?
{50274}{50473}Reci mi neötoÖkakva to pedercina trckara|naokolo u Boûicnom dûemperu
{50491}{50580}Uozbilji se stvarno,nisi ni straöan
{50580}{50702}Nisi ni straöan|A da popricamo o ovim noûevima
{50702}{50840}äta je to sa dugim secivima,|kompenzujeö neku manu
{50840}{50972}Moûda ste malo kratki medju nogama|g.Kruger
{50972}{51076}Mislim imaö malu tananu stvarÖ
{51076}{51194}Öa Dûejson ima veliku stvar kaoÖ
{51649}{51743}-Hajde Lori,ne moûemo joj viöe pomoci|-Ne,ostajem
{51743}{51858}-Je si luda,dobila si öta si htela,izvukla si|Fredija,sad se bije s Dûejsonom,hajde
{51858}{51969}äta viöe hoceö?|-Ubio mi je majku Vil,to je bio Fredi
{51969}{52062}Moj tata je zataökao da bi me zaötitio,|nije on to ucinio
{52062}{52156}Uzeo nam je sve,|uniötio nam je oboma proölost
{52156}{52282}I ne idem dok ga ne vidim da umire!
{52950}{53107}-Hvataj torpedo
{53599}{53783}Hej,seronjo,gore
{54182}{54300}Da
{54657}{54777}Ne mogu da verujem
{55345}{55496}O ne,o nee!
{57584}{57711}-Lori,poprskaj rezervoare
{57727}{57804}-Odustani
{58451}{58647}-FrediÖidi u pakao
{62106}{62234}-TiÖ
{62941}{63129}-Dobrodoöao u moj svet kucko!
{65038}{65660}PREVOD I OBRADA|»EDO FILM - by Lucifer
{65685}{67185}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/8268j|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
