{1}{1}23.976
{26}{176}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{4862}{4927}Jebi se!
{5034}{5110}Ne, ne sad. Jebiga!
{5845}{5913}APA»OV SKOK
{6033}{6081}DOZVOLJENO SKRETANJE|POLUKRUéNO
{7207}{7284}Imam poûar ovde.
{7717}{7803}Ko mi je iskljuËio muziku?
{7908}{7986}Ti si m i iskljuËio muziku.
{7990}{8083}Jesi li ti Harlin?|Jeli Harlin tu?
{8087}{8168}Sumnjam. Mrtav je.
{8172}{8242}Jesi li ti vlasnik?|- Da.
{8246}{8371}Zaöto ga zoveö "Harlinovo"?|- Zato öto je to bilo Harlinovo.
{8391}{8511}Moûeö li da pogledaö moj auto?|Mislim da je crevo hladnjaka crklo.
{8563}{8678}BiÊe toplo danas.|Opet, moûda i neÊe.
{8682}{8778}Nikad ne moûeö reÊi. Kad je vruÊina,|ne volim Ëak da izaem iz kreveta.
{8782}{8851} Ni kad je hladno.|- Harlin...
{8855}{8971} Darel.|- Mislim da je crevo hladnjak crklo.
{9016}{9139}Crevo hladnjaka je crklo.|- Znam. äta sam ti upravo rekao?
{9143}{9223}Ako toliko znaö,|popravi ga sam.
{9227}{9356}Da mogu, ne bih bio ovde.|Popravi ga, ili idem na neko drugo mesto.
{9360}{9483}Drugo mesto?|To je 50 milja odavde.
{9487}{9605}Stanica u centru grada|je zatvorena pre tri godine.
{9609}{9700}U redu. Moûeö li da popraviö ili ne?
{9704}{9776}Da, mogu.|- OdliËno.
{9780}{9895}VideÊu ako imam crevo|kao ovo. PotrajaÊe malo.
{9899}{9996}Koliko vremena?|- Ne znam. Vreme.
{10000}{10092} Koliko je sad?|- 10:20.
{10096}{10155}Arizona...
{10188}{10282}Mora da ima 32 stepena.|- 33.
{10286}{10385} äta se desilo sa tvojom rukom?|- Nezgoda.
{10390}{10516}Moraö da budeö oprezniji.|Ruke su veoma vaûne.
{10520}{10616}Ne znam da li joö uvek moûeö da|vidiö, ali kad sam bio mali...
{10620}{10715}Interesantno...|Gde mogu da popijem neöto?
{10719}{10805}Tamo je restoran. Nije neöto.
{10809}{10877}Mi obiËni ljudi ga volimo.
{10881}{10996}VratiÊu se za nekoliko sati.|Samo budi veoma paûljiv sa tim.
{11087}{11191}To su samo kola.|- To je mustang kabriolet iz 64.
{11195}{11341}To je razlog zbog kojeg ti ûiviö ovde|a ja samo prolazim.
{11600}{11750}Samo da izvadim neke stvari.|- Samo izvoli.
{13096}{13188}Isto kao grad,|samo ruûnije.
{13871}{13961} Hej, ti tamo.|- éeliö neöto, stari?
{13965}{14092}Idi do ugla tamo do one maöine|i donesi mi gazirano piÊe.
{14096}{14207}Ne moûeö to sam da uradiö?|- Ne mogu do avola, slep sam.
{14211}{14296}Izgubio sam oËi u Vijetnamu.|- Izvini.
{14300}{14408}Neka ti ne bude ûao. Samo mi donesi|piÊe pre nego öto umrem od ûei.
{14504}{14660}Imaö li sitno?|- HoÊeö sitno od slepog veterana?
{14664}{14744}Gde je otiöao svet?
{14748}{14872}Uzmi mi Dr. Pepera.|Kola nije niöta drugo do zaöeÊerena voda.
{14876}{15011}I otvori ga. Ja ne mogu.|Ako to uradiö, onda si dobar deËko.
{15015}{15084}Neverovatno. Jebeni...
{15160}{15242}To je za majku zemlju.|Ja sam 50% indijanac.
{15246}{15346}»estitam.|- Za sve naöe odnose.
{15379}{15463}HoÊeö malo?|- Drugi put.
{15467}{15547}Pas izgleda bolesno.
{15551}{15676}Zato öto je mrtav.|Nadam se da ga nisi mazio.
{15680}{15773}äta radiö sa mrtvim psom?|- Samo je mrtav.
{15777}{15887}äta je trebalo da radim? Ja i Dûesi|smo bili drugovi joö od rata.
{15891}{15976}Hajde, Dûesi.
{15980}{16095}Vidimo se kasnije, osim|ako ne naiem na neöto gore.
{16324}{16416}Treba li ti pomoÊ, lepotice?|- Idem samo do mojih kola.
{16420}{16561}To mi je usput.|- Mama me je upozorila na strance.
{16608}{16737}Ja sam Bobi. Viöe nismo stranci.|Vidiö kako je to bilo lako, lepotice?
{16741}{16841}Zar moraö tako da me zoveö?|- Ne znam tvoje ime.
{16845}{16940}Moûda ne ûelim to od tebe.|- Zaöto si onda stala?
{16982}{17065}Pun si sebe.|- To mi se svia kod mene.
{17069}{17192}Zovem se Grejs.|- Grejs, mogu li da ti ponesem paket?
{17257}{17404}Moûeö li? Da uzmem to?|- Ne, nije problem.
{17408}{17512}äta se desilo sa tvojom rukom?|- Nezgoda.
{17516}{17644}Trebalo bi da budeö paûljiviji.|To su samo zavese i garniöne.
{17648}{17805}Toliko sam se umorila od starih.|Moja mama ih je napravila.
{17809}{17940}Znala sam da moram da imam ove.|Jesi li se ikad oseÊao da moraö da imaö neöto?
{17944}{18057}Da, jesam. - Tu smo.
{18095}{18168}Hvala, Bobi.|- Nema na Ëemu, Grejs.
{18172}{18317}Nisi odavde.|- Ne, moja kola su se pregrejala na putu.
{18321}{18457}SreÊa je öto nisi u pustinji.|Po ovakvom danu bio bi mrtav.
{18559}{18643}Kad odlaziö?
{18647}{18744}Ne dok ne popravim kola.
{18748}{18831}A ja sam te ovde|umorila i oznojila.
{18912}{19009}Dobro jutro, Grejs.|- Dobro jutro, äerife.
{19013}{19145}Nabavila sam moje zavese.|- Imaö takoe i pöomoÊnika.
{19149}{19220}Dobro jutro, äerife.
{19348}{19478}Drago mi je öto smo se upoznali, sinko.|- Takoe, öerife.
{19598}{19709}Trebala bi mi pomoÊ da|da unesem ove kutije u kuÊu.
{19713}{19829}Mogao bi da se istuöiraö.|Nai neöto hladno da popijeö.
{19877}{19953}Joö uvek imaö sreÊe.
{20197}{20299}Odakle dolaziö?|- Posvuda. Detroit.
{20303}{20425}»ikago, Majami. Imam neki|nedovröeni posao u Las Vegasu.
{20429}{20556}äta radiö?|- äta se najviöe iplati. Barmen.
{20560}{20621}PoduËavao sam tenis ranije.
{20693}{20765}TakmiËio sam se jednom.
{20793}{20856}Ja nikad nisam igrala tenis.
{21809}{21893}Dosta mi je tvog sranja.|- Polako, polako.
{21897}{22014}Bobi, hoÊu moj novac.|- Jesi li Ëuo?
{22018}{22144}DobiÊeö tvoj novac.|Ne moraö ovo da radiö.
{22148}{22233}Imaö dve nedelje, seronjo.|Sjebi mu dva za sada.
{22346}{22423}Prvi prst.
{22634}{22724}Drudi prst.
{23530}{23659}Joö limunade?|- To bi bilo divno.
{23741}{23853}äta inaËe radiö?|- Malo ovo, malo ono.
{23857}{23955}Uglavnom proriËem sudbinu.|- Gde si to nauËila?
{24006}{24066}Od mog oca.
{24141}{24221}Doi ovamo.
{24662}{24749}Sedi.
{24891}{24982}Neöto je u tvojoj proölosti...
{24986}{25095}Neöto...postoji bol.
{25182}{25327}Neöto uûasno ûeliö.|Izgleda ti daleko sada.
{25395}{25510}Ali odluËan si.
{25514}{25584}I uradiÊeö öta moraö|da bi to dobio.
{25614}{25763}To sve moûeö da kaûeö po mom licu?|- Sva lica mi govore isto.
{25782}{25918}Svako ima proölost. Imaju bol|i neöto öto ûele.
{25970}{26110}äta ti ûeliö?|- Isto öto i ti.
{26246}{26350}Stvarno?|Ja hoÊu da kaËim zavese.
{26710}{26778}Moûeö li da me drûiö?
{27053}{27144}»vröÊe. NeÊu da se slomim.
{27217}{27291}Tako. Spusti me.
{27424}{27533}Moûeö da me spustiö sada.|Sigurna sam.
{27698}{27786}Dosadilo mi je da kaËim zavese.
{27814}{27951}äta sad da radimo?|- Imam ideju.
{27992}{28086}Koju?
{28306}{28402}U redu, bez igara viöe.|- Kakvu igru hoÊeö da igraö?
{28406}{28490}Ti nosiö moje pakete|i idemo u krevet?
{28494}{28638}Idem nazad u grad.|- HoÊu prvo da znam o Ëoveku neöto..
{28642}{28748}Od Ëega je graen.|- Hvala na limunadi.
{28766}{28850}Nisi mi odgovorio.|- Joö uvek igraö.
{28854}{28946}äta ûeliö?
{29685}{29747}Grejs!
{29751}{29835}Dûejk...|Mislila sam da si u Feniksu.
{29839}{29920}Ko je do avola ovo?
{29924}{30035}Ko si do avola ti?|- Njen muû.
{30092}{30214}Ko si ti? Ovo bolje da je dobro,|inaËe Êu da te polomim.
{30218}{30333}Samo sam pomagao vaöoj|ûeni oko zavesa.
{30337}{30416}Nije tako izgledalo.|- To je sve.
{30420}{30527}To mnogo govori.|- Grejs, reci mu.
{30531}{30741}Pretpostavljam da je samo dolutao ovde?|Trebalo bi da izveslam tvoju bulju!
{30745}{30877}Namamila si me ovde tako|da nas dvojica treba da se pobijemo zbog tebe?
{30909}{30979}Zaboravi.
{31070}{31146}Ne moûeö tek tako da ueö i izaeö.
{31150}{31259}Polomio si mi nos!|- Nije polomljen.
{31263}{31342}Polazi, seronjo.
{32403}{32552}äta hoÊeö jebote?|- UskaËi. UmreÊeö na ovoj vruÊini.
{32556}{32701}Nisi valjda joö uvek uznemiren|zbog onog ljubakanja, zar ne? Ulazi.
{32945}{33022}äta se desilo s tvojom rukom?|- Nezgoda.
{33026}{33112}Moraö da budeö...|- Viöe oprezan. Znam.
{33116}{33213}Ja sam Dûejk Mek Kena.
{33217}{33367}Bobi Kuper.|- äta te dovodi u Superior?
{33371}{33483}Kola su se pregrejala.|- Da li se Darel stara o tome?
{33487}{33644}Glup je kao vreÊa ËekiÊa.|- Da, pravi je lik.
{33675}{33784}Gde ideö?|- Kalifornija.
{33788}{33885}Da li ûiviö tamo?|- »ovek hoÊe da plovim njegovim brodom.
{33889}{34011}Ti si mornar.|To je ûivot.
{34015}{34096}Samo sedi u brod i otplovi.
{34100}{34231}»ovek moûe tako da nestane.|- Da sam znao da je udata...
{34235}{34403}To bi bila razlika.|Ti si Ëovek bez skrupula.
{34407}{34486}To mogu da osetim na tebi.
{34507}{34635}Da, to je znoj Ëoveka koji|nema nijednu poötenu kost u svom telu.
{34679}{34836}Ne vreaj se. »ovek bez etike|je slobodan Ëovek. Zavidim ti.
{34840}{34967}éena onakvog izgleda i Ëovek|mojih godina, öta sam mogao da oËekujem?
{34971}{35072}éene...Ne moûeö da ûiviö sa njima,|ne moûeö da ûiviö bez njih.
{35076}{35197}Ne moûeö da ûiviö sa njima,|ne moûeö da ih ubijeö.
{35270}{35388}Kladim se da te je napalila ûestoko,|mrdajuÊi buljom u tvoje lice.
{35392}{35532}Hteo si da joj skineö gaÊe i razvaliö je,|a onda ja da uem.
{35536}{35682}Imaö narav. Kladim se da si|samo hteo da joj slomiö vrat.
{35686}{35785}Kladim se da si hteo samo da je ubijeö.
{35816}{35929}Da li bi ti? Da li bi je ti ubio?
{36004}{36141}Zaöto bih je ja ubio?|- Dojadile su mi njene male igre.
{36145}{36252}Mogao bi to da uradiö i da odlepröaö|tim brodom a da te ne primete.
{36256}{36440}Voleo bih da podelim 50000 dolara ûivotnog|osiguranja sa njenim ubicom.
{36444}{36545}Radio sam neke stvari,|ali nisam ubica.
{36550}{36656}Kako Êeö da znaö|kad nikad nisi probao?
{36679}{36766}äalis se. zar ne?
{36862}{36994}Tako je.|Niöta drugo do öala.
{36998}{37073}Uûivaj ovde, momak.
{37735}{37872} Imaö li sode?|- PriËaj polako.
{37876}{37982}Hladnu sodu.|- Neöto za klopu.
{37986}{38068}Ne, ne. PiÊe.
{38072}{38190}Drûi to u sebi i niko neÊe biti povreen.|Isto vaûi i za tebe, kopile.
{38194}{38274}Daj mi novac.
{38571}{38689}To je sve? Gospoo, imam decu|koju treba da izökolujem.
{38693}{38787}äta ti imaö, druûe?
{38892}{39020}Lepo. Imaö ukusa.|Daj mi kutiju.
{39061}{39154}To su samo kutije.|- Ja sam ËitaË. Baci.
{39158}{39265}To su porodiËne stvari.|- Daji mi torbu.
{39269}{39343}Ne. - Ne?
{39347}{39478}To nije dobro. Hajde.|- Ne?
{39482}{39569}NeÊe da mi da torbu.
{39573}{39680}Ne mora.|- Hajde!
{39782}{39919}Ne moj venËani prsten!|- Ekstra nikad ne ökodi.
{40308}{40378}Ubico!
{41429}{41577}Gospodine, povreeni ste.|ZvaÊu policiju.
{41581}{41673}Ne. Ne policiju.
{41677}{41811}Evo. Ne policiju.|- 100 dolara, ne policiju?
{41889}{41961}Ne policiju.
{42519}{42601} äta se desilo sa tvojim licem?|- Imao sam nezgodu.
{42605}{42702}Joö jedna nezgoda?|Moraö da budeö viöe oprezan.
{42723}{42824}äta se do avola desilo sa mojim kolima?
{42986}{43137}Morao sam da promenim i donje crevo|takoe, ali sad ide kao san.
{43194}{43304} Koliko?|- Da vidimo...
{43308}{43441}Imaö delove i rad.|Hajde neka bude...150 dolara.
{43482}{43554} Koliko?|- 150.
{43558}{43679}Da zameniö crevo hladnjaka?|- Crevo u mustangu iz 1964.
{43683}{43762}To je Ford, ne Ferari!
{43766}{43881}To nije samo Ford.|To je Mustang iz 1964.
{43885}{43982} Kakve to ima veze?|- Ne znam.
{43986}{44087}Ali razlog je öto je ûivim ovde,|a ti samo prolaziö.
{44091}{44173}Dugujeö mi 150 dolara.
{44327}{44403}Upravo sam opljaËkan.
{44407}{44574}Izvadi svoju Amerikan Ekspres|zlatnu karticu i zovi tipa na TV-u...
{44578}{44702}Nemam kreditnu karticu.|- Onda Êeö morati da odradiö ovo.
{44736}{44860}Imam Movado. Vredi 7.800 dolara.|Mogao bi da ga prodaö.
{44950}{45077} Ne vidim brojeve.|- Zato je tako skup!
{45081}{45131}Pogledaj zlato.
{45135}{45229}Nema datuma.Mogu da ti kaûem,|da ovo ne vredi ni paËjeg prdeûa.
{45233}{45436}Dobio sam ovo za 3.75 dolara. Ima dosta|spravica. DrûaÊu se ovog.
{45440}{45514}Ti kuËkun sine!
{45518}{45637}- Moj advokat Êe te zatvoriti.|- Nemaö kreditnu karticu, ali imaö advokata?
{45641}{45777}PriËaj koliko hoÊeö,|ali zar nisi proËitao znak?
{45793}{45923}- Koji znak? HoÊu moja kola.|- Ja hoÊu mojih 150 dolara.
{46198}{46330}- Koja je linija u Dalasu?|- Ti neplatiöo. Izgubi moj broj!
{46334}{46421}- Majk, ti...|- Koji Majk?
{46425}{46594}Cici, Bobi je. Znam da je bilo|dugo, alËi u frci sam.
{46598}{46677}- Treba ti novac?|-150 dolara.
{46681}{46820}Ne, ti si ukrala moje CD-ove. Ili je to|bio moj bivöi cimer, s kojim si se trpala?
{46824}{46914}Ok, gde je moj G. Kafa?|Cici?
{46934}{47036}- Rozarita. Bobi.|- Jebi se!
{47157}{47258}- Mama, Bobi je. Tvoj sin.|- On je mrtav.
{47262}{47350}- Ne, nisam mrtav.|- Jesi za mene.
{47419}{47550}Halo? G. Arkadi,|ovde neplatiöa Kuper.
{47579}{47666}Smrad zove na moj raËun.
{47717}{47838}Bobi, oËekivao sam da te vidim,|ne da priËam s tobom preko telefona.
{47842}{48017}Kakav sam dan imao. Ovo Êe zvuËati|neverovatna priËa.
{48021}{48202}Imao sam novac. Na putu sam za Vegas,|i kola mi se pokvare.
{48206}{48428}Ulazim u radnju da kupim hranu,|i mesto biva opljaËkano.
{48432}{48562}- I pljaËkaö uzme tvoj novac?|- Bilo ih je dvojica, i ubijeni su.
{48566}{48634}Stara gospoa ih je ubila.
{48638}{48811}Ona ih ubije, i novac u torbi|se rascepa u komade.
{48815}{48946}Kakve su öanse?|Pa sam mislio da bi moûda mogao...
{48950}{49138}Moûeö Ëi da mi poöaljeö 150 dolara?|PaltiÊu ti sa ostatkom.
{49142}{49253}- Koji nemaö.|- Mogu da prodam moja kola u Vegasu.
{49257}{49338}Gde si?
{49372}{49483}U malom usranom mestu|200 milja istoËno od Feniksa.
{49487}{49567}Superior.
{49655}{49797}- Zar ne moûeö da poöaljeö...|- Ne! Sluöaj me, seronjo!
{49801}{49910}Ne zanima me ako te je udario|kamion ili pregazio parni valjak.
{49914}{50074}Dugujeö mi 13.000 dolara i hoÊu|ih na mom stolu sutra!
{50078}{50143}Ili Êu ti pokazati öta je loöa sreÊa!
{50147}{50221}- Kapiraö?|- Jebi se i ti!
{50225}{50362}- äta si rekao?|- Ne. Izvini.
{50366}{50506}- Toliko sam pod stresom.|- Dugujeö mi 4 nedelje.
{50510}{50594}Sad hoÊeö joö jednu nedelju.|To je 5 nedelja.
{50598}{50709}To je takoe 5 prstiju,|zato öto ide jedan prst za jednu nedelju!
{50713}{50790}Doiu sutra i budi dobar.
{50794}{50906}I moûda neÊu sjebati|ostala tri prsta...
{51087}{51234}Idi u Superior.|Ovaj neplatiöa neÊe videti sutra.
{51835}{51979}Dobio si tri glave zaredom,|öanse su da sledeÊa bude pismo.
{51995}{52103}∆uti i pij tvoju kafu,|i prestani da bacaö taj prokleti novËiÊ.
{52275}{52414}- Mogu li da ti donesem neöto?|- Pivo. Bekovo.
{52418}{52527}- Nemam Bekovo. A-1, Korovo?|- Hajneken?
{52531}{52650}- Ne. Imamo Milerovo.|- Bojd misli da su öanse 50-50.
{52654}{52759}- "Original Draft"?|- Ne, imamo samo stari dobri Miler.
{52763}{52856}Moûeö da ga uzmeö ili ostaviö.
{52860}{52943}UzeÊu ga jebote.
{52956}{53095}- Flo. »izburger krvavi.|- VratiÊu se sa tim pivom.
{53099}{53235}I konobarica po imenu Flo...|Isuse!
{53269}{53454}- On ne zna statistiku.|- äta si ti? Raketni nauËnik?
{53470}{53551}Jebena maËka.
{53555}{53623}Imaö li novËiÊ za dûuboks?
{53627}{53727}HoÊu da pustim jednu pesmu.|Imaö li novËiÊ?
{53761}{53850}- äta ti se desilo sa rukom?|- Posekao sam se brijajuÊi se.
{53854}{53972}- Da, moram da budem viöe oprezan.|- Imaö li ûelje?
{53976}{54121}- Svo kantri sranje zvuËi isto.|- Kako bi bilo da izaberem jednu za tebe?
{54305}{54449}Zar ne voliö Petsi Klajn? Zaöto|ona ne izbacuje viöe ploËa?
{54493}{54627}- Zato öto je mrtva.|- To je tuûno.
{54648}{54804}- Zar te to ne rastuûuje?|- Imao sam vremena da to prebolim.
{54808}{54935}Nisi odavde, zar ne?|Odakle si?
{54939}{55047}- Oz.|- Ne, nisi iz Oza!
{55051}{55151}- Oz je iz onog filma.|- Isuviöe si brza za mene.
{55155}{55295}Ne! Vidim, ali|ne verujem.
{55337}{55424}äta radiö sa mojom devojkom?
{55446}{55525}Pitao sam te pitanje.
{55529}{55653}- Tobi, samo smo priËali.|- ∆uti. Vrati se za naö sto.
{55657}{55763}Ne teraj me da te ponovo pitam.|äta radiö sa mojom devojokm?
{55767}{55874}- Niöta nisam radio.|- Tako mi nije izgledalo.
{55878}{55997}- Hteo si da se smuvaö sa njom.|- Da li su svi u ovom gradu na drogama?
{56001}{56096}- Samo sam ga pitala za novËiÊ.|- UÊuti.
{56100}{56269}Imamo posao da obavimo.|I nikad nisam uzimao drogu.
{56273}{56383}Moûda bi trebalo. Nisam pokuöavao|da se smuvam sa tvojom devojkom.
{56387}{56463}Izazivam te.
{56503}{56575}HoÊeö da se bijemo zbog nje?
{56579}{56727}Ne znaö ko sam.|Zovem se Tobi N. Taker.
{56731}{56813}Ljudi me zovu TNT.
{56817}{56930}- Znaö zaöto?|- Nisu mnogo maötoviti?
{56934}{57035}Zato öto sam kao dinamit.|Kad se iznerviram, neko strada!
{57039}{57119}Dobro.|Pokuöao sam da se smuvam s tvojom devojkom.
{57123}{57243}Sad sam uplaöen, i nauËio sam lekciju,|i sad moûeö da ideö.
{57247}{57351}- Isuse Hriste.|- Ustani.
{57355}{57482}- Ili Êu te isprebijati gde sediö?|- Zavröi svoje piÊe i ostavi ga.
{57486}{57607}Nemoj ti meni nema veze, Flo.|Ovo Êe biti gotovo veoma brzo.
{57627}{57728}Tobi jedan dodir.|Hajde, pizdo.
{57876}{58005}Imaö sreÊe ovaj put.|Ali doteraÊu ovo do kraja.
{58035}{58135}Mislim da Êu te ispratiti kuÊi.
{58236}{58370}- äta je to bilo?|- Tobi misli da svi ûele Dûeni.
{58374}{58472}Dûeni ûeli svakog tipa|koga vidi.
{58476}{58585}- Ne mogu da otvorim otvorenu prodaju za tebe.|- Ovo je pustinja.
{58589}{58710}Ljudi bi poludeli.
{58714}{58850}- PomoÊi Êu sebi sa malo kafe.|- Budi paûljiv.
{58974}{59064}- KuËkin sine!|- Pogledaj öta si uradio.
{59068}{59172}- Ispekao sam ruku.|- Sva je crvena.
{59176}{59268}StaviÊu puter na nju kasnije.
{59316}{59392}Dûo, nai metlu i obriöi ovo.
{59435}{59588}äasta, ne plaöi tog finog Ëoveka.|Izvini za to, öeÊeru.
{59592}{59700}Da vidimo. 3.25 dolara.
{59876}{59956}Prijatan dan.
{59960}{60036}PokuöaÊu.
{60295}{60392}Do avola!
{60412}{60521}Zaöto?|Izvuci me iz ovog prokletog grada.
{60708}{60792}Mek Kena nekretnine
{60865}{60953}Dûejk mi je ime,|nekretnine su moja igra.
{61957}{62038}äta mogu da uËinim za tebe. momËe?
{62042}{62134}- Nadao sam se da moûemo da razgovaramo.|- O Ëemu?
{62138}{62294}O tvojoj ûeni. O tvojih 50.000 dolara|ûivotnog osiguranja.
{62350}{62498}- Podelio bi ga sa njenim ubicom.|- Mislim da ti je vruÊina udarila u glavu.
{62502}{62584}Ti si to pomenuo.
{62588}{62714}- Ne mislim uvek sve öto kaûem.|- Mislio si to.
{62718}{62856}Ti si ljigavo kopile koje|bi ubilo svoju ûenu da bi se obogatio.
{62860}{62977}- äta to tebe Ëini?|- Ljigavo kopile bi bilo dovoljno.
{62981}{63116}Ti si ljubomoran Ëovek. Ako nemoûeö|da imaö Grejs za sebe...
{63120}{63209}Ti nisi tip osobe koja deli.
{63245}{63358}Ja imam, kako se zove,|volim-mrzim odnos sa Grejs.
{63362}{63461}- Voliö je, ali je mrziö.|- Ne, mrzim da je volim.
{63465}{63555}Mrzim da toleriöem male|igre koje igra.
{63559}{63677}Kao öto se trpa sa pola grada|iza mojih lea i smeje mi se. Kurva!
{63681}{63843}HoÊe da je bijem. Ona to voli.|Voli da me muËi.
{63941}{64058}Ali posle svega...|Ona je moja porodica.
{64199}{64327}Ona je moja mala devojka.|Moja duöa.
{64386}{64569}Ne bih mogao da podnesem|da gledam kako izdiöe svoj poslednji dah.
{64627}{64723}Ne. Ne ja.
{64753}{64909}Ali ti...|Imaö ubicu u sebi.
{65029}{65128}Recimo da hoÊu da ubijeö kuËku.
{65132}{65239}- äta ûeliö?|- Koliko ceniö ubistvo?
{65243}{65418}Cenim ga 50.000 dolara minus|tvoj deo, naravno. A to je?
{65460}{65620}- 20.000.|- Nemam toliko novca.
{65624}{65745}- Za uzimanje osiguranja treba vremena.|- Koliko moûeö da uzmeö?
{65749}{65852}Moûda 10.000.
{65856}{65951}Treba mi 13.000.|- To je malo mnogo.
{65955}{66057}Ne priËamo o kupovini kola,|veÊ o ubijanju tvoje ûene.
{66061}{66133}13.000 ili niöta.
{66498}{66588}Tvrdiö pazar.
{66607}{66725}Ali imao sam utisak da si moj tip|kad sam te prvi put video.
{66729}{66849}Izgleda da imamo dogovor.
{66853}{66916}Da li da se pozdravimo.
{66920}{67041}Ako ne verujeö Ëoveku koga|si unajmio da ti ubije ûenu...
{67045}{67150}Mora da izgleda kao nesreÊa.
{67154}{67229}Ako ne bude tako, onda ne valja.
{67233}{67385}Ja bih bio osumnjiËeni za ubistvo bez novca|dok bi ti pobegao negde.
{67389}{67480}Kako ûeliö?
{67484}{67628}- Ne sme da buide obavljeno u kuÊi.|- HoÊu malo novca unapred.
{67632}{67828}Zaöto ti ne bih kupio avionsku kartu|dok mo tu? Znam te.
{67894}{67949}Sluöaj...
{67953}{68079}Idi do kuÊe da je vidiö.|Reci da si morao da je vidiö.
{68083}{68245}PriËaj joj neûne reËi. Mladi pastuv|kao ti mora da si dobar u tom.
{68249}{68379}Onda promeni temu. PriËaj o dûipu.|Ona voli to.
{68383}{68446}Moûda jedina stvar koju voli.
{68451}{68558}OdveöÊe te u voûnju u pustinju, negde|gde je tiho.
{68562}{68662}Voûnja kroz crvene stene i mese.|Ona voli tamo.
{68666}{68729}I ja. To nam je zajedniËko.
{68733}{68883}Tamo neÊe biti niko,|samo vi i neki prerijski psi.
{68922}{69068}I onda...poËni sa neûnim reËima.|Meni to nije bitno.
{69072}{69158}Opusti je,|i onda...
{69162}{69237}...uradi to!
{69405}{69499}- Mogla bi da ga ostaviö.|- Nije tako lako.
{69542}{69645}- Odeö.|- Moûda bi ti mogao da rizikujeö.
{69649}{69762}Ti moûeö da lutaö|gde ti je volja. Ja ne mogu.
{69882}{69955}Ne ûelim da budem sama.
{70106}{70197}Volela bih da sam ptica.
{70262}{70430}Neki stari indijanci su mislili|da moûeö da se pretvoriö u ûivotinju.
{70434}{70565}Volela bih da mogu. Da sam ptica,|odletela bih u FLoridu.
{70569}{70635}Diznijev svet.
{70704}{70794}Uvek sam ûelela da idem tamo.
{70798}{70876}Onda Êu odleteti u Njujork, moûda.
{70917}{71042}Onda Êu odleteti u St. Luis|onda kroz ceo Teksas.
{71065}{71155}Onda Êu odleteti u Kaliforniju.
{71200}{71290}Onda pretpostavljam da bih videla sve.
{71323}{71421}Onda mogu da umrem.
{71606}{71694}Kaûu da niöta ne oseÊaö.
{71698}{71818}äok te ubije pre nego|öto udariö u zemlju.
{71961}{72081}Uvek sam zamiöljala|da je to kao letenje.
{72788}{72939}Kladim se, sad,|da ne znaö da li da me ubijeö...
{73035}{73098}...ili jebeö.
{74519}{74615}Stani! Ne mogu!
{74686}{74770}äta nije u redu?|- Niöta.
{74774}{74851}Ne igleda kao niöta.
{74855}{74944}Beûi iz grada brzo, Bobi.
{75093}{75211}Ne radi mi to. Sjebale su|me dosta njih.
{75215}{75291}Ti si kraljica toplog i hladnog.
{75295}{75444}Takav je haos sa Dûejkom.|- Znam kako je biti u haosu.
{75667}{75758}Dûejk je bio sam mojom mamom.
{75762}{75835}Kada je moj pravi otac umro.
{75988}{76086}Zvao me je|njegovom "malom melezkinjom".
{76090}{76263}Drûao je moju mamu po strani.|Imao je ûenu negde drugde.
{76267}{76351}Kontrolisao bi me.
{76355}{76431}Izgledaö tako lepo.
{76513}{76647}Zagrli me.
{76700}{76806}Zaöto?|- Ne zajebavaj se okolo kao tvoja mama.
{76843}{76978}Silovao me je sve vreme.|Godinama.
{76982}{77064}Moja mama...
{77112}{77223}Cepalo ju je to zato|öto nije mogla niöta da uradi.
{77481}{77559}Postala je alkoholiËar.
{77616}{77714}Naöli su moju mamu ovde dole.
{77771}{77872}Na dnu ApaËevog skoka.
{77913}{78075}Virdûil, öerif Poter, je rekao|da je bila pijana i poludela.
{78079}{78199}Nikad nisam verovala da je|skoËila sa stene sluËajno.
{78225}{78355}Bila je kao ja.|Samo je htela da odleti.
{78460}{78548}Tako mi je ûao.
{78582}{78677}äta Êeö da radiö? éivot, zar ne?
{78739}{78850}Jesi li ikad bio u Kaliforniji?|- Da.
{78905}{79031}Jeli lepo?|- To je drugi svet.
{79112}{79178}Prelepe plaûe|i plava voda.
{79252}{79344}»isto nebo,|dokle god oko moûe da vidi.
{79348}{79483}Povedi me sa sobom.|NeÊu se osloniti na tebe.
{79487}{79572}Moûeö tamo da me ostaviö.|HoÊu samo da odem.
{79576}{79715}Ne mogu da odem pre nego öto|nabavim 150 dolara za onog ludog mehaniËara.
{79719}{79835}Darel? On i Dûejk...|- Imaö li novac?
{79839}{79923}Dûejk mi samo daje 20 dolara tada.
{79972}{80091}Ako bi mogla da nabaviö novac,|mogao bih da nas odvedem odavde.
{80180}{80292} Ima novca. Puno.|- Gde?
{80296}{80461}Dûejk ga krije u sefu.
{80480}{80608}U podu spavaÊe sobe. Moja mama je rekla|da ima viöe od 100,000 dolara tamo.
{80632}{80747}U keöu?|- Nema niöta drugo kod Dûejka.
{80751}{80864}On sedi tamo, smeje se,|priËa sam sa sobom i broji ih.
{80868}{80973}100,000...kuËkinm sin.
{81015}{81111}Kako to misliö?
{81150}{81296} Treba nam kombinacija.|- Treba kljuË.
{81300}{81367}On ga drûi na sebi sve vreme.
{81452}{81568}Bar udara u mene kad|vodimo ljubav.
{81572}{81675}Kako onda da ga uzmemo?
{81719}{81804}Ubij ga.
{81976}{82076}Ne mogu nikog da ubijem.
{82080}{82192}Nije kao da je mlad.|éiveo je dovoljno.
{82196}{82318}Bilo bi brzo.|Ne mora Ëak ni da oseti.
{82322}{82533}Uradi to noÊu. Doeö iza njega|kada spava.
{82537}{82623}Ili kad me trpa...
{82648}{82719}Bobi!
{82723}{82820}Vidim to. U tebi je.|Vidim smrt.
{82824}{82913}U srcu ti je.|Uradi to za mene.
{82917}{83065}UradiÊu sve za tebe. Treba ti novac|da odeö odavde.
{83069}{83186}Trei milje je nazad do grada.|Ima mnogo viöe od 100,000 dolara.
{83192}{83254}Gde ideö?
{83279}{84779}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/j7ks|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
