{1}{1}25.000
{26}{176}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{5129}{5166}Kako se oseÊaö, Kitone?
{5259}{5305}Ne oseÊam noge...
{5367}{5397}...Kajzer.
{5500}{5524}Spreman?
{5812}{5844}Koliko je sati?
{5880}{5907}Pola jedan.
{7481}{7539}Sve je poËelo u Njujorku|pre öest nedelja.
{7554}{7636}Kamion pun delova rasklopljenog|oruûja je otet van Kvinsa.
{7641}{7694}VozaË nije video nikog,|ali je neko zajebao stvar.
{7699}{7767}»uo je glas.|Ponekad, to je sve öto vam treba.
{7851}{7876}Gospodin MekManus?
{7880}{7954}Isuse! Zar vi jebaËi nikad ne spavate?
{7958}{7988}Imamo nalog za vaöe hapöenje.
{7993}{8024}Jebi se!
{8222}{8249}Tod Hokni?
{8266}{8292}Ko ûeli da zna?
{8297}{8333}Njujoröka policija.
{8449}{8470}Sranje.
{8475}{8515}Ne mrdaj!
{8648}{8688}Siguan si da si poveo dovoljno ljudi?
{9554}{9639}Veoma je jednostavno. Restoran|koji se menja sa ukusom...
{9644}{9699}bez gubljenja celokupne estetike.
{9701}{9797}Drugim reËima, atmosfera neÊe biti|ocrtana na zidovima.
{9837}{9876}Dozvolite da vam dam primer...
{9881}{9924}Ovo moram sam da vidim.
{9992}{10011}Dejvide.
{10046}{10095}Ja sam na sastanku.|- Vreme je za jedan drugi.
{10123}{10182}Ovo je Dejvid Kujon.
{10187}{10250}Specijalni agent Kujon, Carina.
{10264}{10320}Ova gospoda su iz|njujoröke policije.
{10348}{10368}Dobro izgledaö, Kitone.
{10383}{10404}Bolje nego öto bih pomislio.
{10414}{10449}Problem, gospodine Kiton?
{10461}{10539}Mala stvar oko ukradenog|kamiona sa oruûjem.
{10601}{10625}Gospodine Kiton?
{10655}{10696}Izvinite me na trenutak?
{10753}{10815}Treba da vam postavimo|neka pitanju u stanici.
{10895}{10945}Ne, ne molim vas... sedite.|Ovo je...
{10966}{11007}Ovo je manji problem.
{11023}{11048}Uûivajte u jelu.
{11625}{11671}{Y:bi}Nije imalo smisla da sam i ja tamo.
{11683}{11738}{Y:bi}Mislim, ovi tipovi su bili|vrhunski otmiËari...
{11754}{11799}{Y:bi}...ali bio sam tamo.
{11859}{11900}{Y:bi}U tom trenutku nisam bio uplaöen.
{11911}{11969}{Y:bi}Znao sam da nemaju niöta öto mogu|da mi prikaËe.
{12002}{12048}{Y:bi}Osim toga, bilo je zabavno.
{12056}{12104}{Y:bi}Trebalo je da izgledam kao ozloglaöen.
{12136}{12172}U redu, svi znate proceduru.
{12176}{12252}Kad vaö broj bude prozvan,|istupite i proËitajte reËenicu...
{12257}{12283}...koja vam je data.|Razumeli?
{12297}{12312}Broj 1...
{12317}{12347}...istupi.
{12455}{12514}Daj mi kljuËeve,|jebeni drkadûijo.
{12569}{12614}Broj 2, istupi.
{12687}{12770}Davaj kljuËeve, ti|jebena piËko drkadûijska!
{12776}{12808}Prekini! Nazad!
{12814}{12857}Broj 3, istupi.
{13081}{13110}Da' kljuËe,|drkadûi'o.
{13115}{13151}Na engleskom, molim.
{13171}{13195}Izvin'te?
{13202}{13237}Na engleskom.
{13257}{13319}Daj mi jebene kljuËeve,|drkadûijo, öta jebote...
{13327}{13372}Broj 4, istupi.
{13383}{13450}{Y:bi}Bilo je to kenjanje.|Cela stvar je bila nameötena.
{13455}{13521}Daj mi kljuËeve,|jebeni drkadûijo.
{13533}{13570}{Y:bi}Sve je bila pajkanska greöka.
{13574}{13632}{Y:bi}Takvi momci se ne stavljaju|zajedno u sobu.
{13651}{13688}{Y:bi}Ko zna öta se moûe desiti.
{13703}{13788}Daj mi kljuËeve,|jebeni drkadûijo.
{13805}{13841}Ovo stvarno mora da je...
{13846}{13882}...blam za vas.
{13887}{13914}{Y:bi}Celu noÊ su nas obraivali.
{13919}{13998}{Y:bi}Neko je bio nadrkan zbog kamiona|öto je otet, a pajkani nisu imali niöta.
{14003}{14070}{Y:bi}Nadali su se da Êe se neko izlanuti|i reÊi im neöto sa Ëim Êe moÊi da rade.
{14082}{14143}{Y:bi}Znali su da se mi neÊemo opirati,|zato öto su znali kako da nas pritisnu.
{14148}{14177}{Y:bi}Rade nam to veËno.
{14181}{14270}{Y:bi}Mislim, naöa prava su odletela kroz prozor.|To je bilo kröenje. Mislim, sramotno.
{14275}{14300}{Y:bi}Prvo su krenuli na MekManusa.
{14316}{14341}{Y:bi}Vrhunski obijaË.
{14346}{14372}Koji kamion?
{14388}{14433}Kamion sa oruûjem, sjebani.
{14438}{14464}Sjebani? Brrr...
{14541}{14593}{Y:bi}Bio je dobar tip.|Mada, pomalo lud.
{14600}{14641}Znaö li öta nam je|tvoj ortak Fenster rekao?
{14647}{14670}Ko?
{14675}{14732}MekManus. IspriËao nam je|totalno drugaËiju priËu.
{14738}{14824}O, onu o kurvi sa|dizenterijom.
{14829}{14864}{Y:bi}Fenster je uvek radio|sa MekManusom.
{14872}{14914}{Y:bi}Bio je prava prznica...
{14918}{14974}{Y:bi}...ali kad je reË o poslu,|bio je pravi. Pametan Ëovek.
{14991}{15015}äta priËaö?
{15020}{15048}Ima da te oöamari.
{15054}{15095}On Êe öta?|- OöamariÊete.
{15100}{15163}I to stvarno.|- Ma da, sav se tresem. Hajde.
{15180}{15197}Odgovori mi na pitanje.
{15202}{15234}»ujete li me vi pozadi?
{15279}{15322}'Alo? HoÊu...
{15328}{15359}...svog advokata.
{15364}{15426}Ima svima da vam uzmem|znaËke, drkadûije.
{15437}{15502}{Y:bi}Tod Hokni.|Dobar sa eksplozivom.
{15507}{15592}{Y:bi}Bez sumnje, tip koga je|bolela bulja za bilo koga.
{15597}{15651}Vi momci nemate niöta|na öta moûete da se oslonite.
{15655}{15685}Misliö, faco?
{15691}{15746}Mogu da te smestim u Kvins noÊi|kad se desila otmica.
{15751}{15776}Stvarno?
{15788}{15820}Ja ûivim u Kvinsu.
{15825}{15881}Jesi li... to sam|povezao, Ajnötajne?
{15888}{15941}Ili si imao, tim majmuna|koji su danonoÊno radili na tome?
{15945}{16010}Znaö li öta Êe se desiti|ako joö jednom odleûiö u Êorci?
{16072}{16123}KaraÊu ti Êaleta pod tuöem,|a onda Êu da prezalogajim.
{16128}{16168}HoÊeö da me optuûiö,|kurËino?
{16173}{16205}OptuûiÊu te kad budem|bio spreman.
{16210}{16232}S Ëim?
{16236}{16274}Znaö ti odliËno,|mrtvac.
{16279}{16368}{Y:bi}Ali Kiton... Kiton je bio prava nagrada|za njih, iz oËiglednih razloga.
{16373}{16429}To je bila vaöa greöka,|ne moja.
{16500}{16549}Jeste li iakda svratili|da me pitate?
{16586}{16684}Mislim, ûivim sa istim licem,|sa istim imenom.
{16719}{16750}Ja sam biznismen.
{16755}{16798}Ma da, a öta je to?|Posao sa restoranom?
{16810}{16898}Ne, od sad, ti si u poslu|u kojem te mi jebemo.
{16903}{16959}Ima da te proslavim, drkadûijo.
{16964}{16995}Kao öto rekoh...
{17011}{17055}...to je bila vaöa greöka.
{17066}{17097}Ne moja.
{17107}{17163}A optuûiö li me|za ovo sranje...
{17190}{17221}...ju Êu se izvuÊi.
{17248}{17288}U redu?
{17309}{17358}Da se vratimo na taj|kamion, kenjaro.
{17521}{17558}Pa öta ako sam malo odleûao...
{17566}{17612}...zar to znaËi da me privode|svaku put...
{17620}{17668}...kad neki kamion nestane?
{17674}{17702}Ma, jebi ih!
{17714}{17754}Fenster, hoÊeö li se opustiti?
{17764}{17809}Ovi momci nemaju osnovanu sumnju.
{17819}{17857}Ma 100% si u pravu.|Nemaju osnovanu sumnju...
{17862}{17897}Nemaju prokleta prava.
{17902}{17943}Ako malo odleûiö,|nikada te ne puötaju.
{17954}{17993}Zanö, ako me tretiraju|kao kriminalca...
{18025}{18052}...zavröiÊu kao kriminalac.
{18057}{18086}Ti i jesi kriminalac!
{18123}{18163}Hej, zaöto si morao|to da uradiö?
{18194}{18215}Pokuöavam da dam poentu.
{18220}{18262}Pa zaöto onda ne kaûeö poentu.
{18278}{18324}Celog me zamaraö.
{18337}{18366}Ma zajebi.
{18378}{18422}»uo sam da si mrtav.|- O, stvarno?
{18434}{18460}Pa, Ëuo si dobro.
{18465}{18506}»uo sam da si se penzionisao.
{18519}{18547}O Ëemu se tu radilo?
{18552}{18578}äta je sad pa to?
{18599}{18641}PriËa se da je,|Kiton postao poötenjaËina.
{18661}{18706}»uo sam da jebe|Idi Fineran.
{18711}{18735}Ko je pa to?
{18741}{18795}Ona je kriminalni advokat iz|predgraa za teöke prestupe.
{18800}{18839}»uo sam da je ona Kitonova|glavna premija.
{18853}{18886}äta ti kaûeö, Kitone?
{18902}{18939}Ti si advokatova ûena?
{18964}{19005}Kakve "isplate" joj dajeö?
{19077}{19131}Hej, Fenster.|UËini svom ortaku uslugu...
{19158}{19194}Reci mu da Êuti.
{19224}{19257}Din Kiton...
{19296}{19327}...postao poöten, a?
{19345}{19382}Reci da nije tako.
{19390}{19432}Jesi li taj koji je|odradio taj kamion?
{19437}{19467}Ma zaboravi ga.
{19475}{19512}Jesi li razgovarao sa|svojim advokatom?
{19553}{19592}Sve ovo je bilo iznuivanje.
{19602}{19632}Zaöto to kaûeö?
{19637}{19677}Koliko puta si bio u liniji?
{19707}{19756}Uvek si ti i joö|Ëetiri glupaka.
{19765}{19840}U pola sluËajeva pajkani plaÊaju|beskuÊnike 10 dolara po glavi za to.
{19850}{19924}I nema öanse da postroje pet|prestupnika u istu liniju. Nema öanse!
{19935}{19975}A öta je postojavanje|sa proverom glasa?
{19981}{20016}Javni branilac bi te izvukao|iz toga.
{20021}{20060}Pa zaöto su me onda|pretresali do gole koûe?
{20068}{20102}To su bili federalci.
{20113}{20159}Kamion sa oruûjem biva otet...
{20172}{20260}...Carina doe do njujoröke policije|traûeÊi odgovore - i dou do nas.
{20267}{20292}Hvataju se za slamku.
{20297}{20341}Momci su mi lupali|prstence u bulju noÊas.
{20349}{20375}Zar je veÊ petak?
{20429}{20455}Da, ljubavniËe.
{20462}{20522}HoÊeö malo?|Neöto kao, volim te.
{20538}{20574}Ko je onda do kurca...
{20580}{20616}...ukrao jebeni kamion?
{20648}{20677}äta reËe?
{20688}{20719}Ko je ukrao jebeni kamion!
{20725}{20756}Ne ûelim da znam.
{20762}{20800}Ko je tebe pitao,|biznismenu?
{20805}{20863}Jebeö ko je to uradio.|HoÊu da znam ko je Êopavi.
{20868}{20888}On je u redu.
{20893}{20965}To ti kaûeö. Kako da ja znam? äta ti|kaûeö, Êopavi? Koja je tvoja priËa?
{20972}{21005}Njegovo ime je Verbal.
{21026}{21055}Verbal Kint.
{21060}{21080}Verbal?
{21097}{21171}Rodûer, u stvari.|Ljudi kaûu da mnogo priËam.
{21177}{21220}Da, baö sam hteo da ti kaûem|da umukneö.
{21226}{21268}Sreli smo se veÊ|jednom ili dvaput.
{21273}{21310}U okruûnom. Leûao sam zbog prevare.
{21315}{21368}Bio si i tada postrojavan.|äta se desilo?
{21373}{21419}Osloboen sam.
{21425}{21444}Devedeset dana,|suspendovano.
{21449}{21471}ZnaËi ti si to uradio!
{21478}{21512}Dosta je bre...
{21549}{21604}Sve nas je potkaËilo ovo, jel' tako?
{21620}{21694}Tako sam skontao da dugujemo sebi|pravo da saËuvamo malo dostojanstva.
{21721}{21746}Sad...
{21760}{21797}...ja i Fenster smo Ëuli|za mali posliÊ.
{21803}{21844}Zaöto se ne smiriö?
{21856}{21897}äta tebe briga öta on ima da kaûe?
{21926}{21965}Ja samo priËam.
{21983}{22054}A meni se Ëini da je gos'n Hokni|ûeli da Ëuje öta ja imam da kaûem...
{22059}{22098}...znam i za Fenstera.
{22128}{22159}äta kaûeö ti momak?
{22203}{22233}Zainteresovan sam, naravno.
{22264}{22293}Eto, vidiö?
{22302}{22373}Sad ûelim da iskoristim svoje|pravo na slobodno okupljanje.
{22380}{22423}Zaöto prosto ne umukneö?
{22574}{22606}PromiËe ti poenta.
{22655}{22716}Ne...|Tebi promiËe poenta.
{22727}{22786}Ne ûelim da Ëujem niöta od tebe.
{22799}{22843}Ne zanima me niöta o tvom poslu.
{22971}{23021}I... ne ûelim da imam bilo|öta sa nekim od vas.
{23039}{23080}Izvinjavam se...
{23086}{23122}...ali svi vi moûete|da se nosite doavola.
{23186}{23215}Din Kiton...
{23234}{23270}...postao poötenjaËina.
{23306}{23354}Na öta je spao ovaj svet?
{23476}{23503}Zajebite ga.
{23620}{23658}{Y:bi}I tako je sve poËelo.
{23664}{23759}{Y:bi}Nas petorica smo privedeni na osnovu laûne|optuûbe, da bi nas pritiskale budale.
{23847}{23901}U redu, ne mogu da priËam|puno o tome ovde...
{23907}{23988}{Y:bi}Ono öto pajkani nikad nisu|shvatili, a öto ja sad znam...
{23995}{24072}{Y:bi}...je da se ovi ljudi nikad neÊe|slomiti, nikad neÊe zalegnuti...
{24097}{24140}{Y:bi}...nikad neÊe saviti|zbog bilo koga...
{24170}{24198}{Y:bi}...bilo koga.
{24575}{24591}Ko ste vi?
{24611}{24681}Agent Dûek Ber, FBI.|Koliko mrtvih?
{24687}{24764}15 do sada. Mada joö uvek|izvlaËe tela iz vode.
{24783}{24802}Ima preûivelih?
{24808}{24831}Da, dvojica.
{24837}{24916}Jedan je u okruûnoj bolnici, ali je|u komi. A tuûilac ima drugog tipa...
{24922}{24972}...bogalja iz Njujorka, mislim.
{24978}{25032}Sluöaj, öef ûeli da|zatvorite ovo mesto.
{25037}{25086}Ako imate bilo kakva pitanja,|pozovite ga...
{25924}{26004}{Y:bi}Ovo je Dejvid Kujon. BiÊu u|Los Anelesu do utorka.
{26009}{26057}{Y:bi}Ako me trebate, kontaktirajte...
{26062}{26143}{Y:bi}...Dûefa Rebina iz policije|San Pedra, na lokalu 112.
{26149}{26174}{Y:bi}Prijatan vam dan.
{26282}{26325}Zaöto ne mogu da ga vidim?|- Dejv, rekao sam ti...
{26330}{26399}...tuûilac je doöao sinoÊ...
{26404}{26453}...spreman da ga otpuûi pre|odlaska na sud. U redu?
{26459}{26509}Kintov advokat se pojavio,|pet minuta kasnije...
{26513}{26592}...tuûilac je izaöao iz kancelarije|izgledajuÊi kao da se tukao sa duhom.
{26598}{26669}U redu? Uzeli su mu izjavu|i sklopili dogovor.
{26675}{26704}äta? Jesu li ga|optuûili za neöto?
{26710}{26736}Da, posedovanje oruûja.
{26741}{26775}Drugostepeni prekröaj.
{26781}{26808}äta je pa to?
{26829}{26912}»uj, mogu da pohvalim tuûioca|öto je i toliko uspeo, razumeö?
{26918}{26944}Izvinte.
{26983}{27033}Cela stvar je|postala politiËka.
{27038}{27099}GradonaËelnik je ovde bio sinoÊ.|äef. Ovog jutra...
{27104}{27154}...guverner je zvao, u redu?
{27159}{27257}Kaûem ti, ovog tipa ötiti i sam avo.
{27263}{27284}Veruj mi na reË.
{27290}{27319}Kada Êe platiti kauciju?
{27324}{27349}Maûda za 2 sata, najviöe.
{27354}{27377}éelim da ga vidim.
{27382}{27421}Ne, Dejve.|- Moram da ga vidim, Dûefri.
{27426}{27488}Dejve, nemoj!|Ne mogu to da ti uËinim.
{27492}{27521}Mnogo sam preöao zbog ovoga.
{27564}{27594}Dejv, molim te.
{27689}{27751}»ak iako ti dozvolim da priËaö sa njim,|on neÊe priËati sa tobom.
{27785}{27829}Plaöi se da Êe biti sniman.
{27833}{27870}Zna da je soba za ispitivanje ozvuËena.
{27875}{27894}Ovo neÊe biti ispitivanje...
{27900}{27970}...samo prijateljsko Êaskanje|da se ubije vreme.
{27976}{28020}NeÊe iÊi u sobu za ispitivanje.
{28027}{28070}Na nekom drugom mestu Êemo onda.|- Gde?
{28162}{28193}Ako je ovo bio posao oko droge,|gde je onda droga?
{28199}{28245}Ako je bilo ubistvo,|ko ga je naruËio?
{28251}{28342}Siguran sam da imaö gomilu ludih teorija|koje daju odgovore na sva ta pitanja.
{28348}{28386}Znaö vrlo dobro öta ja mislim.|- To je ludost.
{28392}{28415}I pored toga, Ëak i nije vaûno...
{28421}{28487}...tip ime totalni imunitet.|Njegova priËa se poklapa.
{28494}{28533}On ne zna to öto tebe zanima.
{28538}{28595}I mislim da ne zna.|Ne taËno.
{28604}{28669}Ali ima mnogo viöe u njegovoj|priËi, veruj mi.
{28679}{28760}Dûefri, vidi... éelim da znam zaöto|je 27 ljudi poginulo na tom pristaniötu...
{28766}{28859}...zbog neËega öto liËi na drogu vrednu|91 milion dolara koje nije bilo tamo.
{28874}{28906}I povrh svega...
{28915}{28956}...ûelim da budem siguran|da je Din Kiton mrtav.
{28963}{28990}Mrtav je.
{29007}{29036}Hajde, dva sata.
{29042}{29073}Samo dok ne poloûi kauciju.
{29094}{29125}Svi su mrtvi.
{29129}{29177}Ne zanima me koliko kaûeö|da je taj Kiton bio Ëvrst...
{29181}{29243}...ali niko na tom brodu|nije mogao da preûivi.
{29332}{29352}Jel' progovorio?
{29357}{29422}Doöao je k svesti|pre manje od sat vremena...
{29427}{29460}...progovorio je, ali ne engleski...|onda je pao u komu.
{29465}{29518}Maarski?|- Ne znam. MoguÊe je.
{29522}{29557}Da, veÊina njih su bili Maari.
{29562}{29580}Morate da stavite ovo.
{29585}{29643}értve poûare su veoma|podloûne infekcijama.
{29672}{29717}I, naravno,|zabranjeno je puöenje.
{29967}{30019}Vratite masku.|Molim vas da ga ne dirate.
{30023}{30043}HoÊe li umreti?
{30060}{30113}Ima opekotine na preko 60% tela,|nekoliko slomljenih rebara...
{30123}{30148}Zovi bolniËko obezbeenje.
{30154}{30187}Naite nekog. Postavite ga|na vrata dok policija ne doe.
{30192}{30215}Da li je opasan?
{30225}{30245}Da!
{30251}{30275}Uradite to!
{30283}{30299}Uradite smesta!
{30393}{30416}Dûoel?
{30422}{30459}Da, Ber, iz okruûne bolnice LA-a.
{30464}{30551}Vidi, tip kojeg su izvukli|iz luke je Arkaö KovaË.
{30560}{30600}Da!|Da, siguran sam.
{30609}{30676}Ne, ne, totalno je sjeban.|äta?
{30697}{30725}Ne Ëujem te.
{30753}{30796}Umukni! Razgovaram!
{30815}{30840}Da.
{30855}{30903}Pa, ne. Ne...
{30913}{30954}Samo mi poöalji nekog|ko priËa maarski.
{30971}{31013}Da! Budan je i priËa|kao tajlandska kurva.
{31025}{31075}Ne, samo nekog...
{31095}{31115}äta?
{31264}{31293}Ne seri!
{31339}{31408}Dûoel. Da, pozovi|Dena Methajzera iz Pravne...
{31413}{31472}...i nai Dejva Kujona iz Carinske.
{32282}{32354}Verbal, ovo je agent Kujon,|iz Carine.
{32380}{32408}Drago mi je da vas upoznam.
{32422}{32474}éeli da ti postavi par pitanja|pre nego öto odeö.
{32480}{32507}O Ëemu?
{32516}{32559}Najviöe o Din Kitonu.
{32593}{32644}Ali, voleo bih da poËnem od|postrojavanja u Njujorku.
{32650}{32676}Mogu li da dobijem malo kafe?
{32682}{32731}Uskoro.|PriËajmo o postrojavanju.
{32737}{32767}Stvarno sam ûedan.
{32778}{32818}»esto sam dehidrirao|kao klinac.
{32824}{32869}Jednom mi je bilo tako loöe,|piöaÊka mi je izlazila kao sline...
{32876}{32902}...ne öalim se...
{32907}{32944}DoneÊu ti jebenu kafu.
{32951}{32987}Donesi i meni jednu|kad veÊ ideö.
{33118}{33156}Ovaj tip je napet.
{33165}{33198}Napetost ubija.
{33210}{33276}Nekada sam bio u muökom kvartetu|u Skokiju, Ilinois...
{33282}{33325}...bariton je bio neki Kip Diskin.
{33330}{33375}Veliki, debeo tip.|Mislim, kao kit.
{33380}{33413}Bio je tako napet ujutru...
{33418}{33466}Verbal, znaö da se trudimo|da ti pomognemo.
{33471}{33512}Naravno. I ja to cenim.
{33517}{33560}I ja ûelim da pomognem vama,|agente Kujon.
{33566}{33592}Volim pajkane.
{33598}{33653}I sam sam ûeleo da budem fereralac,|ali moj problem sa srcem...
{33661}{33706}Verbal, ne govoriö nam sve.
{33712}{33751}Znam da znaö neöto.
{33758}{33803}Rekao sam tuûiocu sve öto znam.
{33850}{33874}Verbal...
{33888}{33964}...znam da ti se Kiton sviao.|Znam da misliö da je on dobar Ëovek.
{33975}{34005}Znam da je bio dobar.
{34011}{34041}Bio je korumpirani policajac.
{34046}{34112}Naravno, pre 15 godina.|Ali bio je dobar lopov.
{34132}{34175}Kako bilo, pajkani mu nisu|dovolili da radi legalno.
{34182}{34223}Din Kiton je bio govno.
{34303}{34364}Da li vi hoÊete da me|isprovocirate, agente Kujon?
{34389}{34424}Samo ûelim da Ëujem tvoju priËu.
{34430}{34458}Sve je tu.
{34484}{34508}Mogu li da dobijem cigaretu?
{34603}{34642}Prema tvojoj ijavi...|- Treba mi upaljaË.
{34747}{34817}Prema tvojoj izjavi,|ti radiö brze prevare.
{34971}{35032}Prema tvojoj izjavi,|ti radiö brze prevare.
{35077}{35110}éiviö od sitnih prevara.
{35118}{35167}To je poniöteno.|Sve to tu je nedostupno.
{35172}{35188}O, znam.
{35209}{35256}Dobar dogovor si sklopio.|Totalni imunitet.
{35290}{35360}Pa, imam optuûbu za|posedovanje oruûja.
{35365}{35416}»eka me celih öest meseci|teöke robije.
{35422}{35467}Znaö li dilera po imenu|Rubi Dimer, Verbal?
{35505}{35552}Znaö li religioznog tipa|po imenu Jovan Pavle?
{35560}{35586}Znaö li da je Rubi u Atici?
{35594}{35629}Nije imao mog advokata.
{35634}{35658}Znam Rubija.|Ceni poötovanje.
{35666}{35728}Dobar mi je prijatelj.|Puno me voli.
{35745}{35784}Sad, znam da je tvoje|svedoËenje zapeËaÊeno.
{35792}{35843}Rubi ima dobre veze.|Ima mnogo prijatelja unutra...
{35849}{35875}...koji mu Ëine mnogo usluga.
{35880}{35972}äta misliö da bi on rekao kad bi|saznao da si ga odrukao tuûiocu?
{35981}{36018}Tu nema niËeg o Rubiju.
{36023}{36062}Sigurno Êu mu to pomenuti.
{36068}{36134}Znaö li koja je prva stvar koju sam nauËio|na poslu? Kako da prepoznaö ubicu.
{36140}{36166}Recimo da uhapsiö 3 tipa...
{36173}{36199}...za isto ubistvo.
{36204}{36287}Strpaö ih u Êorku da prenoÊe. sledeÊeg|jutra, koji god da spava je tvoj Ëovek.
{36293}{36346}Vidiö, ako si kriv i znaö da|si uhapöen, moûeö da se odmoriö...
{36352}{36399}...spuötaö svoj gard.|Pratiö li me?
{36404}{36424}Ne.
{36446}{36472}Da preem na poentu.
{36522}{36554}Pametniji sam od tebe.
{36571}{36628}I saznaÊu ono öto ûelim da znam.
{36635}{36678}I izvuÊiÊu to iz tebe,|svialo se to tebi ili ne.
{36709}{36742}Ja nisam taster.
{36894}{36934}Hvala.
{37039}{37117}Onomad kad sam brao pasulj u Gvatemali,|pravili smo sveûu kafu.
{37123}{37160}Pravo sa drveÊa,|mislim.
{37166}{37186}To je bilo dobro.
{37195}{37215}Ovo je sranje.
{37222}{37242}Ali, hej,|u policijskoj sam stanici...
{37248}{37281}Moûemo li ispoËetka?
{37292}{37343}Sad, öta se desilo|posle postrojavanja?
{37491}{37552}...deûurni narednik je ustvari pokuöavao|da mi kaûe da ne moûe da te pusti.
{37557}{37624}Moûeö li da verujeö?|»ak nije ni podignuta tuûba!
{37634}{37665}Njujoröka policija!
{37737}{37789}Znaö, ûelim da slikam|tvoje lice i da...
{37794}{37839}...odnesem slike u tuûioËevu|kancelariju odmah sutra ujutru.
{37844}{37864}Samo zaboravi.
{37870}{37929}Apsolutno ne! IsteraÊu ovo pred|Veliku porotu do ponedeljka.
{37935}{37983}Vidi, ne ûelim o tome|da priËam, Idi. U redu?
{38056}{38098}Pa, öta su Fortije i Reno rekli?
{38120}{38165}Traûili su joö malo vremena da|razmisle o restoranu.
{38177}{38212}Samo ûele viöe vremena! U redu je...
{38217}{38244}Viöe vremena za öta, Idi?
{38256}{38337}Bez obzira koliko sakrivala moje|tragove, ponovo Êe saznati o meni.
{38351}{38382}Odaj mi bar malo priznanja.
{38399}{38427}Do ovde sam te dovela.
{38432}{38493}Idemo pred Veliku porotu.|Znaö, ovo neÊe prestatio ako mi...
{38499}{38545}Nikad neÊe prestati. TaËka.
{38568}{38648}Do sledeÊe nedelje, svaki investitor|u ovom gradu Êe beûati od nas.
{38702}{38728}Gotovo je.
{38745}{38774}Ja sam gotov.
{38916}{38962}Ne diûi sad od mene ruke, Din.
{39018}{39056}Nikad neÊe prestati.
{39238}{39266}Volim te.
{39295}{39349}Upropastili su me tamo veËeras.
{39401}{39427}Volim te.
{39473}{39499}»ujeö li me?
{39672}{39693}äta?
{39761}{39781}U redu.
{39820}{39854}Hajdemo samo da odemo do mog stana.
{40232}{40270}O ovome Êemo da brinemo sutra.
{40479}{40550}{Y:bi}Fenster i MekManus imaju lukav predlog.
{40555}{40612}{Y:bi}Brz posliÊ. Visok rizik.|Dugotrajna kinta.
{40617}{40656}{Y:bi}Svi smo znali da je izvodljivo.
{40661}{40728}{Y:bi}Kako sam ja shvatio,|pogreöno odraditi znaËilo je ubijanje.
{40733}{40790}{Y:bi}Ispravno odraditi|podrazumevalo je petoricu.
{40795}{40835}{Y:bi}Petorica su podrazumevala Kitona.
{40868}{40916}{Y:bi}Kitona je trebalo ubediti.
{40974}{41017}Njujoröka najbolja taksi sluûba.
{41048}{41074}Sereö!
{41157}{41198}Oni viöe ne rade.
{41214}{41309}MekManus ima prijatelja u 14. stanici.|IÊi Êe da obave jedan posao - Ëetvrtak.
{41314}{41375}Treba da pokupe tipa koji övercuje|smaragde iz Juûne Amerike.
{41380}{41426}MekManus veÊ ima muöteriju koja|je zainteresovana za kupovinu.
{41431}{41451}Muöteriju? Koga?
{41456}{41496}Neki tip iz Kalifronije.|Zove se Redfut.
{41501}{41532}Nikad Ëuo za njega.
{41543}{41569}Moraö da poeö.
{41574}{41608}äta ti imaö od toga|da li Êu i ja poÊi?
{41613}{41682}Oni...|Oni me ne znaju. Ti me znaö.
{41689}{41738}NeÊe me primiti|ako ti ne kreneö.
{41755}{41792}Pogledaj me.|Potrebno mi je ovo.
{41817}{41864}O, ti mi kaûeö da tebi|ovo ne treba?
{41869}{41902}Jel' ovo tvoj stan?
{41912}{41989}Ne zvocam ti, ali izgleda da odliËno|iskoriötavaö ovog tvog advokata...
{42107}{42130}Izvini.
{42156}{42199}U redu je.
{42232}{42283}Kaûeö da je prava stvar?|To je u redu.
{42359}{42382}Jesi li u redu?
{42398}{42431}Preterao sam.
{42459}{42511}Ali oni nikad nee prestati da rade|ovo sa nama, znaö i sam.
{42529}{42588}Koliko god Ëist da budeö,|nikad te viöe neÊe pustiti.
{42593}{42677}Ovako Êemo udariti pajkane tamo gde ih|najviöe boli, a usput Êemo i uÊariti.
{42785}{42818}Sigurno si u redu?
{42838}{42866}BiÊu u redu.
{43220}{43250}Vidi, ja...
{43275}{43316}...ponekad se...|- Zaboravi.
{43411}{43458}Verovatno Êu veËeras de serem krv.
{43825}{43862}Dakle, kako oni hoÊe to da obave?
{43903}{43968}MekManus hoÊe da upadne pucajuÊi.|Ja kaûem ne.
{44011}{44057}Fenster?|Hokni?
{44066}{44121}PriliËno su nadrkani.|UradiÊe sve.
{44142}{44208}Sad, imam plan kako da se odradi|a da niko ne bude ubijen.
{44213}{44259}Ali, kao öto rekoh, neÊe me|primiti bez tebe.
{44708}{44736}Tri miliona?
{44789}{44818}Moûda i viöe.
{44931}{44958}Bez ubijanja.
{44999}{45038}Ne ako odradimo na moj naËin.
{45860}{45934}{Y:bi}Njujoröka najbolja taksi sluûba|nije bila obiËna taksi sluûba.
{45940}{46037}{Y:bi}Bio je to krug pokvarenih pajkana u|njujorökoj policiji, koji su uzimali...
{46043}{46094}{Y:bi}...veliki reket za voûnju krijumËara|i dilera droge po celom gradu.
{46099}{46160}{Y:bi}Za nekoliko stotina dolara po milji,|dobijaö svoja pajkanska kola...
{46165}{46180}{Y:bi}...i policajsku pratnju.
{46191}{46233}{Y:bi}Imaju Ëak i svoje podsetnice.
{46238}{46268}{Y:bi}Posle izvesnog vremena,|neko je poËeo da se...
{46272}{46336}{Y:bi}...raspituje i taksi|sluûba je ugaöena.
{46341}{46425}{Y:bi}Od tada, Unutraönja kontrola|Ëeka da ih uhvati na delu.
{46441}{46471}{Y:bi}I tu smo mi nastupili.
{46476}{46507}Pa, kakav je bio let?
{46513}{46544}Jebeno dobar.
{46594}{46639}HoÊe li me ovo odvesti do Stejten Ajlanda?
{46676}{46731}äaliö se? Ovo Êe te|odvesti do Kejp Koda.
{46742}{46810}{Y:bi}MekManus nam je predloûio posao,|Fenster je nabavio kombije...
{46816}{46849}{Y:bi}...Hokni je nabavio gvoûuriju.
{46854}{46910}{Y:bi}Ja sam smislio kako da obavimo|a da niko ne bude ubijen.
{46916}{46944}{Y:bi}Ali Kiton...
{46954}{47002}{Y:bi}Kiton je dodao|zavrönu glazuru.
{47007}{47097}{Y:bi}Malo "jebite se" od nas|petorice njujorökoj policiji.
{47176}{47204}U redu, gledaj ovo.
{47229}{47255}Paûljivo!
{47261}{47281}Kretenu!
{47390}{47420}Ne mrdaj, drkadûijo!
{47426}{47463}Ko do...|- Baci! Sad, drkadûijo!
{47468}{47523}Baci jebeni piötolj!
{47531}{47569}Nemoj da se zajebeö i pipneö|te jebene stvarËice!
{47575}{47613}äta koji kurac hoÊete?
{47652}{47677}Glupi kretenu!
{47689}{47718}Pazi!
{47761}{47814}HoÊeö öamponiranje saËmom, Debeli?
{47989}{48021}Dobar dan, moji mesni odresci.
{48027}{48057}Daj mi to sranje.
{48064}{48094}Daj mu to jebeno sranje!
{48100}{48121}Daj mu to jebeno sranje!
{48189}{48213}Poûuri!
{48219}{48243}Hajde!
{48248}{48267}Sad novac!
{48273}{48317}Nemam novac!|- Daj mi novac! Odmah!
{48322}{48350}Nema jebenog novca!
{48356}{48385}Daj mu novac!
{48391}{48408}Novac!
{48421}{48463}Daj mi jebeni novac!
{48468}{48492}Daj mu!
{48506}{48529}Daj mu novac!|- Poûuri!
{48636}{48669}Da li vi ljudi|znate ko sam ja?
{48689}{48732}Znamo, drkadûijo.
{48924}{48966}äta je to?
{49002}{49032}Koji kurac...?
{49042}{49082}Jebote!
{49480}{49526}{Y:bi}Kiton je anonimno dojavio...
{49531}{49584}{Y:bi}...a novinari su bili|na licu mesta pre pajkana.
{49589}{49646}{Y:bi}ätraus i Rizi su osueni|tri dana kasnije.
{49651}{49705}{Y:bi}U roku od nekoliko nedelja,|joö 50 pajkana je optuûeno.
{49726}{49792}{Y:bi}Svi su dobili po bulji,|od öefa pa naniûe.
{49813}{49842}{Y:bi}Bilo je predivno.
{50046}{50083}Dugujem ti 2.50$.
{50220}{50256}Ovde ima viöe nego öto sam mislio.
{50263}{50295}Kada muöterija dolazi?
{50316}{50376}Redfut nikad ne dolazi da vidi mene,|ja uvek idem da vidim njega.
{50414}{50441}U Kaliforniju?
{50472}{50530}Da, Verbale, u Kaliforniju.|Fenster i ja Êemo...
{50537}{50584}»ek', Ëek'...|Stani malo jebote...
{50590}{50618}...ti i Fenster?|Ne, ne, ne...
{50656}{50682}Ti me zajebavaö?
{50688}{50713}U redu. Ko...
{50719}{50749}...Êe onda da ide?
{50761}{50788}Svi Êemo iÊi!
{50833}{50868}Koji je tvoj jebeni|problem, ËoveËe?
{50896}{50981}Moj jebeni problem, ËoveËe, je da Êete ti i|Fenster iÊi na medeni mesec u Kaliforniju...
{50986}{51015}...dok Êemo mi ostali da sedimo|ovde drûeÊi se za naöeg stojka.
{51060}{51089}Hej!|Posao je gotov.
{51106}{51131}Ohladite se.
{51158}{51212}L.A. je dobro mesto|da se malo pritajimo.
{51286}{51313}HoÊeö da pleöemo?
{51496}{51521}Dame...
{51718}{51758}éeleo bih da nazdravim...
{51797}{51820}Izvoli.
{51895}{51924}...za gospodina Verbala...
{51969}{52008}...Ëoveka sa planom.
{52337}{52370}PropustiÊmo let.
{52400}{52456}Ne Ëini ovo.|Poöalji joj poruku ili neöto.
{52491}{52524}Rekao sam da Êemo stiÊi.
{53348}{53387}OdleteÊe nam avion.
{53431}{53466}RazumeÊe ona.
{53936}{53974}Baö dira u srce.
{53978}{54005}Stvarno.
{54048}{54075}PlaËem.
{54109}{54146}Dûef, hoÊeö li da saËekaö napolju?
{54235}{54305}Hteli ste da znate öta se desilo posle|postrojavanja. To vam i priËam.
{54311}{54339}Ma daj, Verbal.
{54350}{54389}S kim ti misliö da priËaö?
{54410}{54464}OËekujeö da Êu da|poverujem da se povukao?
{54489}{54517}Zbog ûene?
{54570}{54593}To je sranje!
{54610}{54637}Kiton ju je koristio.
{54644}{54671}Voleo ju je.
{54678}{54695}Naravno.
{54702}{54778}Treba da poverujem da napad na taksi|sluûbu takoe nije bila njegova ideja?
{54784}{54821}Sve su smislili Fenster i MekManus.
{54826}{54871}Ma daj, Kiton je bio|policajac 4 godine!
{54876}{54952}Ko je bolje znao taksi sluûbu od njega?|Ceo taj posao baö i liËi na njega.
{54957}{54991}Ali Idi ga je totalno|preobratila.
{55002}{55038}Da ti kaûem neöto.
{55049}{55076}Ja znam Din Kitona.
{55088}{55149}Istraûujem njegov sluËaj|poslednje 3 godine.
{55157}{55214}Tip kojeg znam je|hladnokrvno kopile.
{55231}{55323}Unutraönja ga je u tri navrata teretila za|ubistva pre nego öto je öutnut iz policije.
{55333}{55377}Zato nemoj da mi prodajeö|kurvu sa zlatnim srcem.
{55393}{55424}Sve ste pogreöno skontali.
{55454}{55475}Jesam li?
{55496}{55595}Din Kiton je bio pod optuûnicama ukupno|sedam puta dok je bio u policiji.
{55602}{55684}U svakom od tih sluËajeva svedoci su ili|menjali svedoËenja pred velikom porotom...
{55697}{55750}...ili umirali pre svedoËenja.
{55772}{55874}Kad su ga konaËno uhvatili zbog prevare|odleûao je pet godina u Sing singu.
{55881}{55928}Unutra je ubio tri zatvorenika.
{55940}{56000}Naravno, ja ne mogu|to da dokaûem.
{56026}{56075}Takoe ne mogu da dokaûem|ni najbolji deo:
{56121}{56164}Din Kiton je bio mrtav.
{56194}{56215}Da li si znao to?
{56225}{56271}Umro je u poûaru|pre dve godine...
{56275}{56329}...tokom istrage o ubistvu svedoka...
{56336}{56387}...koji je trebao da|svedoËi protiv njega.
{56396}{56464}Dvoje ljudi je videlo Din Kitona|kako ulazi u svoje skladiöte...
{56470}{56509}...tren pre nego|öto je eksplodiralo.
{56520}{56586}Rekli su da je uöao da proveri|curenje glavnog dovoda gasa.
{56610}{56694}Odletelo je u vazduh,|odnevöi sa sobom Din Kitona.
{56722}{56774}U roku od tri meseca|od eksplozije...
{56783}{56826}...dva svedoka,|bila su mrtva.
{56843}{56890}Jedan se ubio u kolima...
{56900}{56964}...drugi je propao kroz|otvoreno okno od lifta.
{57045}{57082}Agente Ber.
{57090}{57133}Ovo nije ono o Ëemu smo pirËali.|Previöe je ljudi u sobi...
{57139}{57217}Vidi, doktore, obeÊavam da Êemo otiÊi|pre nego öto otegne papke. U redu?
{57222}{57257}Imam sastanak u podne, Ber.
{57261}{57328}Pet minuta, agente Ber.|- Hajde, svi se smirite. U redu?
{57334}{57414}HoÊu da pitaö ovog Ëoveka|o pucnjavi u luci.
{57700}{57721}On kaûe da su kupovali...
{57733}{57780}Drogu, znamo.
{57915}{58005}Ne zna öta su kupovali, ali|nije droga... ljude.
{58012}{58033}äta?
{58222}{58267}Trebaju mu garancije...
{58272}{58295}O Ëemu bre on to priËa?
{58301}{58349}Kaûe da mu je ûivot u opasnosti.
{58377}{58465}Video je avola.|Pogledao da je u oko.
{58471}{58529}Odoh ja.|- Ne, ne. SaËekaj trenutak.
{58535}{58602}Pitaj ga da mu kaûe ono öto je rekao meni.
{58616}{58648}O avolu.
{58665}{58700}Ko je avo.
{58829}{58870}Kajzer Soze.
{59005}{59040}Bio je u luci...
{59056}{59097}...pobio mnogo ljudi.
{59102}{59149}Video je Kajzer Sozea?
{59297}{59338}Video je njegovo lice.
{59365}{59431}Reci mu da kaûe njoj kako izgleda.
{59436}{59473}Da ga opiöe.
{59637}{59715}Pre öest nedelja dobio sam|anoniman poziv iz kog sam saznao...
{59720}{59789}...da mogu da naem Kitona kako jede|u Mondinu sa advokatom. I tamo je bio.
{59808}{59879}Sad, poöto nikad nije profitirao|od svoje navodne smrti...
{59885}{59966}...i zato öto smo osudili drugog za ubistvo|koje smo pokuöavali njemu da pripiöemo...
{59972}{60011}...morali smo da ga pustimo.
{60036}{60108}Bio je dovoljno dugo mrtav|da ga mimoie kazna za ubistvo.
{60113}{60154}A onda je otiöao na ruËak.
{60163}{60197}Nisam znao za to.
{60212}{60243}O, nisam ni mislio da znaö.
{60263}{60342}A ti kaûeö da si video Kitona kako|umire. Mislim da mu ötitiö bulju...
{60348}{60392}...a on je i dalje tamo negde.
{60398}{60444}Mislim da je on iza|celog cirkusa u luci.
{60450}{60532}Kladim se da te koristi zato öto si|glup i misliö da ti je prijatelj.
{60538}{60593}Kaûeö mi da je mrtav?|Neka bude tako.
{60617}{60666}HoÊu da budem siguran da je mrtav|pre nego öto se vratim za Njujork.
{60672}{60733}Nije on bio iza svega.|Nego advokat.
{60756}{60783}Koji advokat?
{60810}{60829}Koji advokat, Verbal?
{60835}{60901}Znate, kada sam bio u muökom|kvartetu u Skokiju, Ilinois, ja...
{60908}{60961}Misliö da ne znam da|nisi sve rekao tuûiocu?
{60967}{61003}äta si izostavio u svedoËenju?
{61009}{61052}Mogu da telefoniram|Rubiju Dimeru za deset minuta.
{61057}{61096}Tuûilac mi je dao imunitet.
{61101}{61183}Ne od mene. Od mene nemaö|imunitet, govno jedno.
{61191}{61267}Svaki kriminalac kojeg sam strpao u zatvor,|svaki policajac koji mi duguje uslugu...
{61275}{61369}...svi najgori öljamovi koji preûivljavaju|na ulici Êe znati ime Verbal Kint.
{61375}{61396}Sad, priËaj sa mnom...
{61404}{61462}...ili taj dragoceni imunitet,|koji su ti odmah dodelili...
{61468}{61546}...neÊe vredeti ni papira na kojem je|odötampan nalog za tvoje ubistvo.
{61621}{61664}Bio je tu advokat.
{61693}{61731}Kobajaöi.
{61752}{61791}Jel' je on ubio Kitona?
{61801}{61868}Ne.|Ali sam siguran da je Kiton mrtav.
{61881}{61923}Ubedi me.
{61928}{61981}IspriËaj mi do poslednjeg detalja.
{62443}{62534}Stigli smo u L.A i sastali se sa|MekManusovim prijateljem, Redfutom.
{62549}{62588}Imao je dobru reputaciju.
{62597}{62636}Delovao je kao dobar Ëovek.
{62640}{62684}Ipak, trebalo je bolje da znamo.
{62689}{62708}Kako si?
{62720}{62790}Dobro. Ti?|- Nije loöe.
{62809}{62842}Kako ide, Fenster?
{62877}{62917}Nema potrebe da otvaram, jel' tako?
{63068}{63106}Ti mora da si Kiton.
{63135}{63175}Redfut, Din Kiton.
{63183}{63216}Tod Hokni i Verbal Kint.
{63221}{63279}Verbal. »ovek sa planom, a?
{63295}{63333}Interesuje li vas joö posla?
{63362}{63395}Uvek smo zainteresovani|za joö posla.
{63402}{63432}Na odmoru smo.
{63469}{63503}Pa dobro... baö öteta.
{63515}{63561}Imam posla na tone,|a nemam dobre ljude.
{63576}{63615}Ne kao vas.|- Koji je posao?
{63628}{63692}Postoji taj draguljar iz Teksasa,|zove se Sal.
{63698}{63746}Iznajmljuje apartmanu u|nekom hotelu u centru...
{63756}{63835}...radi besplatne procene za ljude.|Ponekad kupuje, ponekad ne.
{63846}{63904}Kako bilo, priËa se da|nosi puno keöa sa sobom.
{63925}{64019}Tako sam mislio, ja da|zadrûim robu, a vi zeleniö.
{64033}{64085}Jednostavno je.|- äta je sa obezbeenjem?
{64091}{64123}Nekoliko telohranitelja.
{64130}{64166}Niöta sa Ëim ne moûete|da izaete na kraj.
{64176}{64216}Daj mi vremena da to proverim.
{64226}{64274}Niöta drugo nisam ni|oËekivao od tebe.
{64312}{64363}Drago mi je da smo se videli. ZvaÊemo te.|- Drago je i meni.
{64368}{64430}Uûivaj u L.A.-u, a?|Uzmi i pojebi neöto.
{64548}{64642}Moj prijatelj iz Njujorka mi|reËe da znaö Spuk Holisa.
{64669}{64707}Kako sam Ëuo...
{64713}{64739}...zajedno si robijao sa starim Spukom.
{64747}{64789}Bio je dobar Ëovek, zar ne?
{64800}{64840}Nekada sam valjao drogu za njega.
{64862}{64905}äteta öto ga izbodoöe noûem.
{64963}{64989}Da. Ja sam ga izbo noûem.
{65053}{65128}Bolje da Ëujeö od mene sada|nego od nekog drugog kasnije.
{65172}{65214}Cenim to.
{65247}{65279}»isto iz radoznalosti...
{65295}{65369}...jel' bilo poslovno ili liËno?
{65414}{65437}Malo od oba.
{65489}{65582}Pa, kao öto rekoh, zvrcnite me|ako ste zainteresovani.
{65708}{65745}Ima li problema?
{65791}{65861}Jedan posao. To je bio dogovor.
{65995}{66031}Jedan posao?
{66097}{66134}Jedan posao!
{66168}{66212}Ta ti je dobra, Kitone.
{66271}{66355}{Y:bi}Kiton se drûao najbolje öto je mogao,|ali Ëovek ne moûe da promeni ono öta je.
{66360}{66430}{Y:bi}Moûe da ubedi nekoga da je|neko drugi, ali nikada sebe.
{66435}{66518}{Y:bi}Trebao je jedan dan MekManusovog|zvocanja i bacili smo se na posao.
{67349}{67415}Daj mi aktovku!|Daj mi jebenu aktovku!
{67576}{67605}Daj mi jebenu aktovku!
{67613}{67655}Po poslednji put ti kaûem...
{67664}{67702}...daj mi jebenu aktovku!
{68722}{68762}Sad mi samo daj aktovku.
{68790}{68834}Daj mi jebenu aktovku!
{69488}{69533}Loö dan. Jebeö ga.
{70265}{70326}Izgleda mi kao mnogo droge.|Sranje.
{70483}{70522}Momci, hajdete.
{70555}{70611}äta to radiö?|- Na öta ti liËi da radim? UbiÊu ga.
{70616}{70659}Vidi, radili smo po tvom.|Sad Êemo po mom.
{70664}{70710}Ti Êeö ga ubiti?|- NagodiÊu se sa njim.
{70717}{70763}Bolje se nagodi sa njim...
{70768}{70792}Umukni.
{70964}{70991}äta treba da radim sa ovim?
{71031}{71068}Otkud ja znam? Nahrani Êopavog.
{71075}{71112}Ublaûuje bolove. Ne znam öta je to.
{71119}{71157}Kako misliö ne znaö?|- Umukni.
{71175}{71207}Ne znam. Ovaj posao mi je|nabacio neki advokat.
{71214}{71233}Da, ko?
{71243}{71292}Ne znam. Neki Englez.
{71297}{71362}On je posrednik za nekoga.|On nije rekao. Ja nisam pitao.
{71369}{71411}Pun si govana.|- Jebi se!
{71448}{71510}Sluöaj me. HoÊemo da ga upoznamo, u redu?
{71548}{71581}»udno. Nazvao me je sinoÊ...
{71602}{71656}...i rekao da ûeli da vas upozna.
{71704}{71749}U redu. SastaÊemo se.
{71754}{71796}NazvaÊu vas.|- Dobro. Uradi tako. Nema problema.
{71801}{71832}Ne svia mi se dogovor.
{71837}{71884}Joö jedna stvar, frajeru.
{71900}{71955}Bude li joö iznenaenja, ubiÊu te.
{72000}{72086}Takva si faca MekManuse.|UËini mi uslugu, vaûi?
{72092}{72126}Skini mi se s kurca!
{72198}{72238}Stavi povodac tom dûukcu.
{72290}{72374}Baö je prava öteta|öto je Sal skenjan.
{72385}{72434}Murkani Êe traûiti tipove|koji su to uËinili.
{72468}{72522}Pre ili kasnije, doÊi Êe|i do mene da se raspituju.
{72584}{72631}Lepo spavajte, dame.
{72909}{72977}ZnaËi taj advokat...|- Kobajaöi.
{72995}{73048}...je doöao preko Redfuta.|- Da.
{73060}{73117}I zaöto si ovo izostavio kad|si razgovarao sa tuûiocem?
{73127}{73172}Dejv. Neko je doöao da te vidi.
{73315}{73349}Dûek.|- Svuda sam te traûio.
{73364}{73445}Joö uvek juriö onaj kokain koji je|izöetao iz one klanice u luci juËe?
{73450}{73518}Da. - Pa, moûeö da prestaneö|da traûiö. Nije bio kokain.
{73522}{73600}Bio sa u okruûnoj bolnici u L.A.-u i|razgovarao sa tipom kojeg su izvukli...
{73604}{73649}...iz odvodne cevi u San Pedru|juËe posle pucnjave.
{73654}{73698}Doöao je k sebi jutros.|PoËeo je da priËa.
{73703}{73793}Bio je Ëlan maarske mafije koja je|sklopila posao sa gomilom Argentinaca...
{73800}{73840}...i kaûe da definitivno|nije bio posao sa drogom.
{73845}{73868}Ali 91 mil...|- Da, znamo.
{73880}{73925}Naö Ëovek kaûe da|sigurno nije droga.
{73930}{74013}Taj Maar mi reËe da je cela grupa|trebala da isplovi sutradan za Tursku.
{74020}{74102}Nisu imali vremena da pregovoraju o takvoj|robi i nisu imali nameru da iöta prenose.
{74107}{74151}Pa Ëemu onda novac?|- Nije znao.
{74160}{74224}Ko god je radio posao nije znao,|osim nekoliko kljuËnih ljudi.
{74229}{74288}Svi su bili Êutljivi po|tom pitanju, kaûe on.
{74293}{74351}äta god je bilo, bilo|je osetljive prirode.
{74360}{74384}Ne kapiram.
{74410}{74498}Kaûu mi da tu imaö onog bogalja iz|Njujorka. Jel' pomenuo Kajzer Sozea?
{74507}{74527}Koga?
{74542}{74585}Sasluöaj me Ëasak.
{74624}{74653}Ko je Kajzer Soze?
{74657}{74687}O, jebote!
{74707}{74792}Raspravljamo o ovome|veÊ sat i po vremena.
{74803}{74890}Ono öto treba da uradimo je da naemo|Redfuta i odmaglimo odavde odmah.
{74895}{74937}Ono öto treba da uradimo je da razmislimo.
{74954}{74983}Misli unazad.
{75011}{75041}Neko...
{75048}{75082}...moÊan.
{75088}{75159}Neko sposoban da nas prati od|Njujorka do Los Anelesa.
{75164}{75204}Ma daj, Din.|Koji kurac radimo ovde?
{75209}{75241}»ekamo.
{75256}{75304}Ma zdravo.|- Sedi.
{75309}{75343}Jebeno se dosaujem...
{75348}{75437}Gospodine Hokni, ipak ostanite.|Gospodine Kiton...
{75452}{75550}...gospodina Fenstera prepoznajem sa|poternica,kao i gospodina MekManusa.
{75555}{75672}Mogu samo da pretpostavim da ste vi gospodin|Kint, dûentlmen koji je ubio Sol Berga.
{75677}{75774}Moj poslodavac vam öalje zahvalnicu.|Veoma neoËekivana korist.
{75795}{75835}Ja sam gospodin Kobajaöi.
{75840}{75918}Moj poslodavac me je zamolio|da predloûim neöto...
{75925}{75951}...vama gospodo.
{75956}{76027}äta hoÊeö? - Mom poslodavcu su|potrebne vaöe usluge gospodo.
{76080}{76166}Jedan posao. Jedan dan rada.|Veoma opasno.
{76171}{76250}Ne oËekuje da svi preûivite.|Ali oni koji preûive...
{76257}{76325}...Êe imati 91 milion dolara|da podele meu sobom...
{76332}{76375}...kako god budu ûeleli.|- Ko je tvoj öef?
{76449}{76487}Radim za Kajzer Sozea.
{76770}{76816}Ko je Kajzer Soze? - SudeÊi po nagloj|promeni raspoloûenja, gospodine Kint...
{76823}{76903}...siguran sam da Êe vam|vaöi saradnici reÊi.
{76929}{76999}Dolazim sa ponudom direktno|od gospodina Sozea.
{77004}{77039}Nareenjem, ustvari.
{77044}{77090}Kako misliö, nareenjem?
{77097}{77135}1981., gospodine Kiton,...
{77140}{77224}...uËestvovali ste u otmici|kamiona u Bafalu, Njujork.
{77231}{77316}Tovar je Ëinio sirov Ëelik. »elik|koji je pripadao gospodinu Sozeu...
{77321}{77414}...i koji je bio namenjen za Pakistan,|za koriöÊenje u nuklearnom reaktoru.
{77424}{77497}Najprofitabilnije kröenje|UN odredbi.
{77502}{77545}Niste mogli to da znate,|gospodine Kiton...
{77555}{77623}...zato öto je momak koji je prebacivao|Ëelik radio za gospodina Sozea...
{77630}{77669}...bez svog znanja.
{77674}{77710}Ranije ove godine...
{77717}{77829}...gospoda Fenster i MekManus su oteli|elisni avion sa Njuark aerodroma.
{77834}{77935}Avion je nosio zlato i platinaste|öipke. Taoke namenjene Pakistanu.
{77952}{78049}Pre dva meseca, gospodin Hokni je|ukrao kamion sa delovima oruûja...
{78056}{78076}...koji je prolazio kroz Kvins...
{78114}{78186}...delovi koji su bili odreeni za|uniötenje od strane drûave Njujork.
{78191}{78279}Trebalo je da se "izgube" na teretnoj|stanici i da se upute u Belfast.
{78284}{78353}Ponovo, gospodine Soze je koristio|pione koji nisu imali pojma.
{78364}{78421}äto nas dovodi do gospodina Kinta.
{78444}{78468}Pre devet meseci...
{78475}{78542}...jedan od gospodin Sozeovih|manje inteligentnih kurira...
{78547}{78653}...je uvuËen u komplikovanu prevaru|...od strane bogalja.
{78678}{78747}Bio je olaköan za 62.000$.
{78782}{78828}Sad, bilo name je potrebno|izvesno vreme da vas naemo.
{78833}{78920}Namera nam je bila da vam priemo|posle vaöeg privoenja u Njujorku.
{78930}{78975}Vi ste namestili postrojavanje...
{78982}{79037}Da. Niste trebali da budete|puöteni dok vas ja ne vidim.
{79042}{79110}Izgleda da je gospodin Kitonov|advokat, gospoica Fineran...
{79120}{79166}...je bila malo previöe efikasna|u ubrzvanju njegovog oslobaanja.
{79174}{79258}Zadrûavanje ostalih je postao|sporni momenat.
{79267}{79332}äta je sa Redfutom?|- Gospodin Redfut nije znao niöta.
{79339}{79394}Gospodine Soze retko|radi sa istim ljudima...
{79401}{79443}...na duûe vreme, i oni nikad|ne znaju za koga rade.
{79470}{79549}Neko ne moûe biti izdan|ako taj neko nema ljudi.
{79564}{79616}Pa... zaöto nam to priËate?
{79623}{79716}Zato öto ste ukrali od gospodina|Sozea, gospodine Fenster.
{79726}{79741}Svi vi.
{79751}{79796}Zato öto niste znali|da ste krali od njega...
{79801}{79851}...je jedini razlog zaöto|ste joö uvek ûivi.
{79857}{79943}On misli da mu dugujete.|Vi Êete se oduûiti za taj dug.
{79955}{80001}U redu, jebi taj dug!|I jebi se ti!
{80006}{80044}Kako da znamo da|radiö za Sozea?
{80058}{80122}Mislim da to nije od velike|vaûnosti, gospodine Hokni.
{80127}{80235}Sva petorica ste odgovorni za ubistvo|Sola Berga i njegovih telohranitelja.
{80242}{80344}Gospodine Redfut moûe posvedoËiti o vaöoj|umeöanosti, a mi moûemo da se pobrinemo za to.
{80349}{80423}äta je tvoja poenta?|- Ponuda je ovakva, gospodo.
{80431}{80485}Primarni interes gospodina Sozea...
{80492}{80527}...su narkotici.
{80532}{80595}On se "takmiËio", da kaûemo,|sa grupom Argentinaca...
{80602}{80657}...veÊ nekoliko godina.
{80662}{80735}TakmiËenje sa gospodinom|Sozeom je uzelo danka.
{80750}{80828}Ti Argentinci pregovaraju|o prodaji...
{80835}{80905}...91 miliona dolara|u kokainu za tri dana.
{80916}{80979}Nepotrebno je reÊi, da Êe|ova prodaja oûiveti...
{80984}{81052}...smanjenu snagu|njihove organizacije.
{81069}{81151}Gospodine Soze bi voleo da|vi zaustavite taj posao.
{81178}{81240}Ako izaberete, moûete da Ëekate|do kraja transakcije.
{81245}{81301}Koji god novac da se|tu nalazi, vaö je.
{81328}{81441}Gospodine Soze bi voleo da se domognete|broda i uniötite kokain na njemu.
{81459}{81562}I onda Êete biti osloboeni vaöih|obaveza prema gospodinu Sozeu.
{81610}{81700}Daj mi jedan dobar razlog|zaöto te odmah ne bih ubio.
{81738}{81761}Poklon...
{81768}{81808}...od gospodina Sozea.
{81883}{81922}Prijatan vam dan, gospodo.
{83587}{83660}Ovde im je ceo moj ûivot!|Sve öto sam uradio od 18-te!
{83672}{83705}Jebote, sve znaju!
{83724}{83775}Svako sa kim sam|radio ili robijao.
{84219}{84264}Ne... ovo nije u redu.|- Ne znam.
{84271}{84332}Ko je bio tip koji je priËao|o Sozeu u Njujorku?
{84388}{84415}Briks Marlin.
{84420}{84489}Da, on je radio za njega.|Indirektne stvari.
{84496}{84571}Uvek je priËao da zarauje 5 puta|viöe nego öto je posao vredeo.
{84606}{84700}Ma taj tip je puka izmiöljotina. Kobajaöi|ga je samo iskoristio da bi ulepöao stvar.
{84714}{84752}Ne znam.|Ovo je loöe.
{84764}{84854}Ma to je sranje! Tip moûe biti iz|policije L.A.-a... Jebena nameötaljka!
{84876}{84945}Kako sam ja Ëuo, Soze...|je neka vrsta kasapina.
{84954}{85007}Neustraöivi psihopata...|sjebeni kasapin.
{85012}{85055}Ne postoji Kajzer Soze!
{85116}{85144}Ko je Kajzer Soze?
{85186}{85265}Trebalo bi da je TurËin.|Neki kaûu da mu je otac Nemac.
{85279}{85330}Niko nije verovao|da je on stvaran.
{85335}{85408}Niko ga nikad nije upoznao ili video|nekoga ko je radio direktno za njega...
{85413}{85481}...ali Ëuvöi Kobajaöija,|svako je mogao raditi za Sozea.
{85486}{85547}Nikad nisi znao.|To je bila njegova moÊ.
{85579}{85655}NajveÊi trik koji je|avo ikada izveo...
{85663}{85730}...je bilo ubediti svet|da on ne postoji.
{85769}{85830}Jedna priËa koju su mi momci ispriËali|- priËa u koju verujem...
{85835}{85875}...datira iz njegovih dana u Turskoj.
{85880}{85943}Postojala je banda Maara|koji su hteli sopstvenu mafiju.
{85948}{85986}Oni su shvatili da bi imao moÊ...
{85995}{86064}...nisu potrebni piötolji,|novac, Ëak ni brojevi.
{86069}{86156}Potrebna ti je samo volja da|uradiö neöto öto drugi ne sme.
{86162}{86238}Posle nekog vremena, stekli|su moÊ i krenuli su na Sozea.
{86243}{86311}On je tad bio mali, samo je|radio sa drogom kako kaûu.
{86382}{86411}Doöli su u njegovu kuÊu...
{86423}{86445}...jedno popodne...
{86452}{86484}...ûeleÊi njegov posao.
{86492}{86522}U kuÊi su zatekli njegovu|ûenu i decu...
{86529}{86571}...i odluËili su da|saËekaju Sozea.
{86964}{86997}On dolazi kuÊi...
{87002}{87069}...da bi zatekao svoju ûenu|silovanu i decu kako vriöte.
{87074}{87152}Maari su znali da je Soze tvrd orah.|Da se ne treba sa njim öaliti.
{87159}{87193}Zato su mu dali do znanja|da misle ozbiljno.
{87324}{87408}Rekli su mu da ûele njegovu|teritoriju. I sav njegov posao.
{87419}{87507}Soze je pogledao u lica|svoje porodice...
{87549}{87636}...a onda je pokazao tim voljnim|ljudima öta je volja zaista.
{88101}{88177}Rekao im je da bi radije|video svoju porodicu mrtvu...
{88187}{88243}...nego da ûivi i|jedan dan posle tog.
{88253}{88322}Poslednjeg Maara je pustio da ode.
{88350}{88423}SaËekao je da sahrani svoju ûenu i decu,|a onda je krenuo na ostatak mafije.
{88434}{88511}Ubija njihovu decu. Ubija njihove ûene.|Ubija njihove roditelje...
{88518}{88553}...i prijatelje njihovih roditelja.
{88570}{88620}Pali kuÊe u kojima oni ûive...
{88648}{88682}...i radnje u kojima rade.
{88700}{88781}Ubija ljude koji su im dugovali novac.|I tek tako...
{88817}{88861}...nestao je.|U zemlju.
{88866}{88924}Niko ga od tada nije video.|Postao je mit.
{88929}{89001}Straöna priËa koju kriminalci|priËaju svojoj deci noÊu.
{89006}{89079}"Ocinkari nekog i Kajzer Soze|Êe doÊi po tebe."
{89101}{89150}Niko stvarno nikad ne poveruje.
{89173}{89197}Da li ti verujeö u njega, Verbal?
{89265}{89308}Kitone je uvek govorio:
{89313}{89391}"Ne verujem u Boga,|ali ga se plaöim."
{89441}{89492}E pa, ja verujem u Boga.
{89497}{89590}A jedina stvar koja me|plaöi je Kajzer Soze.
{89764}{89808}Pridajeö li ovom neki znaËaj?
{89814}{89866}Mogu da te upoznam sa|Den Methajzerom iz Pravne.
{89871}{89959}Ima dosije o Sozeu u Vaöingtonu. To mu|je bio hobi poslednjih nekoliko godina.
{89964}{90041}Mnogi ga smatraju za onog reportera|koji je javio za Neverovatnog Hulka.
{90170}{90232}»uo si za njega?|- Misliö na ulici?
{90242}{90302}Nekoliko puta.|Ne vezane stvari.
{90315}{90367}Neko radi za tipa koji|radi za tipa...
{90372}{90438}...koji je dobio novac od Kajzer Sozea.|Znaö, sva takva sranja.
{90464}{90499}MoguÊe da je neki penzionisani pajkan.
{90504}{90544}MagiËni talisman koji spreËava|ljude da se zajebavaju sa tobom...
{90549}{90595}...nekada kad je|ime neöto znaËilo.
{90600}{90627}A ti si ovde.
{90632}{90652}Pa naravno.
{90657}{90719}Imam tipa koji pokuöava da izae iz|bolnice na ispeËenim patrljicima...
{90724}{90749}...zato öto se plaöi Sozea.
{90764}{90813}Naleteo sam na pravu stvar.
{90859}{90909}Ispao sam Ëist. IspriËao sam|öta se desilo na brodu.
{90914}{90952}Pa öta ako sam izostavio|kako sam dospeo tamo?
{90958}{91030}Bilo je toliko puno rupa, da je tuûilac|mogao 'ladno da me ispali za amnestiju.
{91035}{91084}Izvukao si iz mene öto si|hteo, jebeno velika stvar.
{91089}{91118}I zato nikad to nisi|rekao tuûiocu.
{91125}{91197}Pa, recite mi, agente Kujon... da sam vam|rekao da me je Ëudoviöte iz Lok Nesa...
{91204}{91241}unajmilo za posao u luci,|öta biste vi rekli?
{91246}{91305}Predali dokaze drûavi. Stavili te|da svedoËiö, sasluöali bi te.
{91312}{91359}Imam imunitet sad.|äta mi uopöte moûete ponuditi?
{91366}{91426}Ako Kajzer Soze stvarno postoji,|krenuÊe da te traûi.
{91461}{91495}Gde vam je glava,|agente Kujon?
{91510}{91544}äta mislite odakle stiûe|sav taj pritisak?
{91549}{91588}Kajzer Soze, ili kako|god ûeleli da ga zovete...
{91593}{91627}...on zna gde|sam sad ja.
{91634}{91679}Jebe vas u bulju samo tako|da bi me pustili...
{91684}{91726}...a da bi me on 10 minuta|kasnije overio.
{91732}{91774}Imunitet je bio dogovor|samo sa vama kretenima.
{91779}{91819}Imam totalno drugaËiji|problem kad poloûim akuciju.
{91828}{91872}Pa zaöto bi onda pao u njegove ruke?|Moûemo da te zaötitimo.
{91896}{91931}O, bravo, hvala Dejve.|Super ste radili posao do sada...
{91936}{91996}...iznuda,|prinuda...
{92004}{92046}...verovatno bi me pardonirali ako|bi vam traûio da mi poljubite stojka.
{92052}{92094}Isti jebaËi koji su sve ovo zamesili|i nas gurnuli u tu guûvu...
{92099}{92125}...mi sad plaÊaju kauciju?
{92130}{92152}Jebi se!
{92219}{92277}Misliö da moûeö da uhvatiö|Kajzer Sozea?
{92283}{92348}Misliö da takav tip doe ovoliko|blizu da bude uhvaÊen...
{92353}{92381}...i samo promoli glavu?
{92399}{92462}Ako zbog bilo Ëega doe,|to Êe biti da se mene otarasi.
{92467}{92487}A posle toga...
{92520}{92582}...pretpostavljam da za njega|viöe nikad neÊete Ëuti.
{93115}{93154}äta se dalje desilo?
{93163}{93222}Probudili smo se sledeÊeg jutra,|a Fenster je nestao.
{93227}{93292}Nije mogao da ponese ideju |da öibicarimo za Sozea.
{93297}{93341}Ostavio nam je poruku|u kojoj nam ûeli sreÊu...
{93346}{93397}...i uzeo je dobar deo novca za|koji smo zajedno rmbaËili.
{93413}{93443}äta je bilo onda?
{93449}{93477}MekManus je bio besan.
{93482}{93529}PriËao je da Êe ga traûiti i|da Êe mu iöËupati srce...
{93534}{93570}...i sliËna sranja.
{93604}{93645}Te noÊi smo dobili poziv.
{93662}{93690}Kakav poziv?
{93695}{93753}Kobajaöi nam je rekao gde|moûemo da naemo Fenstera.
{93945}{93988}U redu, idemo odavde.
{94042}{94078}Moramo da ga sahranimo.
{94086}{94116}Sa Ëim?
{94127}{94162}Golim rukama.
{94400}{94437}Ovo je ludost!
{94448}{94511}Ovo je jebeni suvi pesak,|MekManus. Kad istrune...
{94516}{94570}...surferi Êe ga namirisati|na kilometar daleko.
{94577}{94599}Kopaj, kretenËino!
{94604}{94668}Hej, a öta Êemo da radimo?|Onaj jebeni tip ima da nas sve pobije.
{94673}{94710}Ne znam za tebe, takvog sa|drvenom nogom, ali ja mogu da trËim.
{94717}{94765}Uopöte nemam problema s tim.
{94788}{94858}Ni Kobajaöi izgleda|nema problem s tim.
{94888}{94977}Da beûiö? NeÊu kopati rupu|za tebe. Razumeö?
{95005}{95087}Ovo nije moj ortak kojeg sahranjujemo.|Ja nikom ne dugujem!
{95106}{95139}Jebi se!
{95144}{95193}Pet godina mi je bio partner.
{95202}{95281}Obavili smo viöe poslova, i video sam|viöe love, nego öto ti moûeö da prebrojiö.
{95286}{95363}Zato, jebi se!|Zato öto je sad naplata duga!
{95369}{95412}Nije naplata duga.
{95484}{95555}Nego predostroûnost. HoÊeö da|naplatiö dug? Ti da beûiö? Nije me briga.
{95665}{95719}Ne radim ovo zbog Fenstera.
{95736}{95778}Ne radim ni zbog tebe.
{95820}{95861}Ovo radim zbog sebe.
{95908}{95954}ZavröiÊu ovu stvar.
{95968}{96047}Ono Kobajaöi kopile|neÊe stojati nadamnom.
{96555}{96603}I poöto su ubili Fenstera,|niko nije beûao?
{96608}{96662}Ja sam hteo. Mislio sam|da bi uspeli da pobegnemo.
{96667}{96702}Zaöto niöta nisi rekao?
{96707}{96765}Veruj mi, pokuöao sam.|Ali Kiton nije dao.
{96770}{96810}Za njega je to bilo nepraktiËno.
{96815}{96872}Kiton je bio prizeman tip,|bivöi pajkan.
{96877}{96975}Pajkanu, objaönjenje nikad nije toliko|komplikovano. Uvek je jednostavno.
{96990}{97053}Na ulici ne postoji misterija, ne postoji|veliki kriminalni mozak iza svega.
{97058}{97098}Ako postoji neki mrtvac, i ti misliö|da je njegov brat to uËinio...
{97103}{97135}...otkriÊeö da si u pravu.
{97141}{97221}Niko se nije raspravljao sa Kitonom.|Svi su se usredsredili na Kobajaöija.
{97488}{97510}Dolaze.
{97555}{97605}»ujeö li me?|Dolazi.
{97614}{97647}Krenuo je dole.
{99014}{99038}Ne miËi se.
{99066}{99103}Pritisni dvadeseti.|Odmah.
{99592}{99615}MiËi se.
{99700}{99729}Odgovor je ne.
{99746}{99772}Gospodin Soze Êe biti veoma uzne...
{99778}{99827}Sluöaj, drkadûijo,|ne postoji Kajzer Soze.
{99833}{99873}Joö jednom pomeneö njegovo ime,|tog momenta Êu te ubiti.
{99879}{99969}»udna pretnja, gospodine Kiton. Samo|pretpostavljam da Êete me ionako ubiti.
{100111}{100175}Znamo da moûeö|da doeö do nas.
{100192}{100249}Ali sada znaö da|i mi moûemo do tebe.
{100273}{100337}Dajem ti poslednju öansu|da sve ovo opozoveö.
{100342}{100372}Gospodin So...
{100381}{100459}Moj poslodavac se odluËio.|On svoj stav ne menja.
{100467}{100486}Ni mi.
{100513}{100574}Sredio si Fenstera.|Ali neÊeö moÊi sve nas.
{100581}{100626}Ne pre nego öto te|sredi neko od nas.
{100631}{100709}Verujem vam, gospodine MekManus.|Iskreno.
{100732}{100794}Ne bi bili izabrani da|niste bili odgovarajuÊi.
{100800}{100847}Ali ja ne mogu da|donesem tu odluku.
{100853}{100913}Kako god mi pretili, to je|... smeöno...
{100920}{101018}...u poreenju sa onim öto Êe mi biti uraeno|ako u potpunosti ne ispunim nareenja.
{101209}{101262}Ja sam tip koji Êe te srediti.
{101310}{101363}Samo ûelim da to znaö.
{101386}{101436}Tako mi je ûao, gospodine MekManus.
{101444}{101502}Preklinjem vas, gospodine Kiton,|verujte mi.
{101514}{101595}Gospodin Soze je veoma stvaran|i veoma odluËan.
{101602}{101630}VideÊemo.
{101809}{101889}Pre nego öto me...|...sredite, gospodine MekManus...
{101902}{101947}...dozvoliÊete mi da zavröim|moj posao...
{101953}{101990}...sa gospoicom Fineran prvo,|hoÊete li?
{102114}{102149}äta si rekao?
{102176}{102265}Idi Fineran.|Gore je u mojoj kancelariji.
{102284}{102350}Zbog sasluöanja o ekstradiciji.
{102361}{102425}LiËno sam traûio|da ona bude na sluËaju.
{102431}{102473}Doletela je juËe.
{102522}{102554}Nema veze.
{102565}{102614}Ubijajte, gospodine MekManus.
{102724}{102758}Laûeö.
{102775}{102801}Da li?
{103219}{103272}Pratnja gospoice Fineran|dok je u Los Anelesu.
{103279}{103345}Nikad je ne ispuöta iz oka.
{103356}{103425}Mislio sam da Êe vam biti drago|öto je u dobrim rukama.
{103533}{103597}Sad se malo odmorite.|»eka vas brod u petak.
{103604}{103661}Ako vidim vas ili nekog|od vaöih prijatelja pre...
{103670}{103718}gospoica Fineran|Êe biti ûrtva...
{103724}{103779}...najodvratnijeg zloËina|pre nego öto umre.
{103785}{103839}Kao i vaö otac,|gospodine Hokni...
{103858}{103932}...i vaö ujak Rendal u Arizoni,|gospodine Kint.
{103951}{104001}Moûda Êu samo da uötrojim...
{104009}{104050}...neÊaka gospodina MekManusa, Dejvida.
{104102}{104142}Da li sam bio jasan?
{104164}{104215}Mi Êemo se pobrinuti|za ona dva leöa dole.
{104221}{104275}DodaÊemo ih na raËun|gospodina Fenstera.
{104296}{104327}Sad me izvinte,|gospodo.
{105260}{105309}Jebote. LogistiËki koömar.
{105317}{105386}Zatvoreno mesto. Deset,|moûda dvadeset ljudi.
{105403}{105454}Ne moûe se reÊi koliko Êe ih|joö biti ispod palube.
{105467}{105519}Moûemo li da budemo neprimeÊeni?
{105536}{105598}Ne. Sa svim tim kokainom,|biÊe spremni.
{105629}{105686}äto me dovodi do sledeÊe|svetle taËke.
{105703}{105784}»ak i ako se neko probije i otme|brod, i dalje nemamo niöta.
{105790}{105825}äta ako saËekamo novac?
{105843}{105892}To je joö desetorica najmanje.
{105903}{105976}Vidite, po mom miöljenju|ovo se ne moûe obaviti.
{105983}{106032}Ko god da ue unutra,|odande ûiv neÊe izaÊi.
{106037}{106063}Ja Êu da Ëekam novac.
{106081}{106103}I ja isto.
{106108}{106150}Jesi li me Ëuo öta|je upravo rekao?
{106158}{106207}Ako ulazim, hoÊu svoje deo.|- I ja isto.
{106260}{106303}Ne postoji niöta|öto se ne moûe obaviti.
{106381}{106442}Ne mogu da verujem da Êemo|uöetati u sigurnu smrt.
{106620}{106678}Na vestima kaûu da|pada kiöa u Njujorku.
{107200}{107239}Koji je to jezik?
{107244}{107316}Ne znam.|Mislim da je Ruski.
{107363}{107398}Maarski?
{108940}{108973}Paket je stigao.
{109475}{109497}Jeste li spremni, klinci?
{109525}{109560}Bio bih, da ne moram da se|zaustavljam i tebi odgovaram.
{109593}{109616}Spreman.
{109645}{109693}MekManus, bilo bi ti bolje|da si spreman za deset sekundi.
{109748}{109768}Spreman.
{109815}{109847}HoÊu da ostaneö ovde.
{109883}{109910}Ali ja treba da pokrijem...
{109918}{109983}Sluöaj, ako se mi ne izvuËemo iz ovoga,|ûelim da uzmeö novac i pobegneö.
{110004}{110066}Nai Idi, reci joj öta se|desilo. Sve joj reci.
{110072}{110109}Ona zna ljude.|Ona zna öta treba da radi.
{110125}{110196}Ako ja ne sredim Kobajaöija na svoj|naËin, ona Êe ga srediti na svoj.
{110218}{110250}Samo uradi kako sam ti rekao.
{110275}{110303}Molim te.
{110380}{110409}Reci joj...
{110504}{110545}Reci joj da sam pokuöao.
{110884}{110917}MekManuse. Krenuo je.
{110930}{110957}Tu sam.
{112411}{112454}Ha, Osvald je bio peder.
{112699}{112730}Zdravo.|Kako ide?
{112802}{112856}Postoji li... problem?
{113474}{113492}Sad...
{114218}{114243}{Y:bi}Stari MekDonald...
{114249}{114283}{Y:bi}...je imao farmu...
{114293}{114349}{Y:bi}...ija, ija, o.
{114373}{114471}{Y:bi}I na farmi je|ubijao neke tipove...
{114481}{114546}{Y:bi}...ba-da-bum, ba-da-bing,|bang-bum.
{115289}{115318}Elvis je napustio zgradu.
{118753}{118786}Zaöto nisi beûao?
{118809}{118833}UkoËio sam se.
{118861}{118930}Pomislio sam na Fenstera i kako|je izgledao kada smo ga sahranjivali.
{118944}{119015}I pomislio sam na Kitona.|Izgledalo je da moûe da uspe.
{119196}{119263}Klinac je naleteo na telo na plaûi|jutros. Sletelo sa broda dok je goreo...
{119268}{119339}...upucano dva puta u glavu. Dva tipa|iz Biroa su ga upravo identifikovali.
{119345}{119361}äta joö?
{119366}{119439}Njegovo ime je Arturo Markez,|sitni krijumËar iz Argentine.
{119445}{119511}Uhapöen je proöle godine u|Njujorku zbog prelaska ulice.
{119516}{119599}Pobegao je u Kaliforniju.|Pokupili su ga na Long BiËu...
{119607}{119684}...i ugovarali ekstradiciju,|kad je ponovo pobegao.
{119689}{119720}Sad, pazi ovo...
{119725}{119806}Idi Fineran je dovedena da|bude savetnik u proceduri.
{119814}{119842}Kobajaöi.
{119847}{119924}Iz Njujorka su mi faksovali kopiju|njegovog svedoËenja. Bio je taster.
{119928}{119955}Veliki jebeni taster.
{119960}{120025}Arturo se izriËito protivio|svom povratku u zatvor.
{120031}{120125}Toliko, da je imenovao|skoro 50 ljudi.
{120131}{120187}Pogodi koga je imenovao na kraju?
{120210}{120245}Kajzer Sozea.
{120252}{120284}Ima joö.
{120580}{120675}ReÊi Êu ti öta ja znam. Zaustavi|me ako ti zazvuËi poznato.
{120716}{120775}Na brodu nije bilo droge.
{121773}{121802}Budi tih!
{121811}{121879}On je ovde!|Znam da je ovde!
{121899}{121946}To je on!|Kaûem ti da je to on!
{121953}{121994}Znam da je ovde!
{122029}{122079}Ne razumete.|To je on...
{122083}{122112}Umukni!|- To je on, Ëujeö li me?
{122137}{122185}Kaûem ti,|to je Kajzer Soze!
{125050}{125121}Gde je Hokni?|- Ne znam. Nema kokaina!
{125156}{125211}äta bre? - »uo si me,|glupi jebivetru. Nema kokaina!
{125223}{125299}Proverio sam ceo brod!|Bio sam u svakoj jebenoj kabini!
{125306}{125361}Mora da ima kokaina!|- Nema niËeg!
{125366}{125399}NiËeg!
{125407}{125441}Zajebavaö me!
{125446}{125538}Nema... jebenog... kokaina!
{125801}{125839}Beûim odavde.
{126826}{126872}Niöta im nisam rekao.
{126895}{126930}Kunem se.
{126943}{127002}Niöta im nisam rekao.|Molim te!
{128143}{128186}MekManus?|äta se koji kurac dogaa?
{128245}{128290}NajËudnija stvar...
{129597}{129669}To si rekao u svojoj izjavi:|"»ovek u odelu, mröave grae."
{129673}{129689}Stani na minut.
{129695}{129754}Nemam minut.|Kaûeö da si video Kajzer Sozea?
{129760}{129805}Rekao si tuûiocu da nisi|znao ko je to bio!
{129810}{129851}Znam da je bilo|droge na bodu.
{129856}{129888}Ne odugovlaËi viöe Verbal!|- Ne odugovlaËim!
{129893}{129949}Znaö na öta ciljam.|- Makni mi se sa lica.
{129954}{130004}Imam imunitet, ne moram|da trpim ova sranja.
{130008}{130053}Ti znaö... na öta|ciljan, Verbal.
{130058}{130076}Ne znam o Ëemu priËaö.
{130089}{130119}Znaö... o istini!
{130124}{130196}Kaûeö da si video nekog kako ubija Kitona.|- Ne znam o Ëemu priËaö. Jesam!
{130202}{130235}Laûeö me!
{130243}{130297}Ti znaö. Znao si svo|ovo jebeno vreme!
{130305}{130377}Ne znam öta priËaö. Video sam|kako je Kiton pogoen, kunem se.
{130389}{130454}Onda, zaöto mu nisi pomogao? Imao|si piötolj! Zaöto mu nisi pomogao?
{130461}{130493}Bio je tvoj prijatelj!
{130597}{130645}Zato öto sam se plaöio.|U redu? Plaöio!
{130717}{130748}Plaöio Ëega?
{130789}{130831}Znam da je to bio Kajzer Soze!
{130847}{130929}Bio je to Kajzer Soze.|Znate, agent Kujon, avo liËno.
{130966}{131023}Kako da pucate|avolu u lea?
{131137}{131176}äta ako promaöite?
{131290}{131347}U redu.|Da se vratimo na pristaniöte.
{133343}{133384}Arturo Markez.|Jesi li Ëuo za njega?
{133390}{133420}äta? Ne.
{133428}{133517}Bio je cinkaroö za one iz suda.
{133524}{133627}Kleo se u izjavi saveznim|öerifima da je video...
{133638}{133673}...i taËno moûe da|identifikuje Kajzer Sozea.
{133680}{133766}Kaûe upravo ovde u izveötaju.|LiËno je imao uvid u njegove poslove...
{133772}{133817}...ukljuËujuÊi, ne samo...
{133825}{133864}...trgovinu drogom i ubistva.
{133870}{133938}Nikad Ëuo za njega.|- Njegovi ljudi su ga prodavali...
{133944}{133966}...bandi Maara.
{133977}{134059}Najverovatnije istim onim Maarima|koje je Soze pobio tamo u Turskoj.
{134069}{134098}Novac nije bio tu zbog droge.
{134114}{134169}Maari su kupovali tog tipa...
{134177}{134218}...koji je mogao da inkriminiöe|Kajzer Sozea.
{134225}{134253}Rekoh da nisam nikad Ëuo za njega.
{134261}{134279}Ali Kiton jeste.
{134288}{134306}Idi Fineran je bila...
{134313}{134354}...Markezov savetnik u ekstradiciji.
{134368}{134401}Ona je znala ko je on bio|i öta je on znao.
{134430}{134473}Ne razum...|- Nije bilo droge na brodu.
{134479}{134565}Bilo je ubistvo. SamoubilaËka|misija da se ubije jedini tip...
{134573}{134620}...koji je mogao da ukaûe|na Kajzer Sozea.
{134629}{134672}Zato je Soze okupio lopove.
{134687}{134738}Ljude za koje je znao da moûe|da ih odvede u sigurnu smrt.
{134750}{134807}Kaûeö da je Soze poslao|nas da ubijemo nekog?
{134835}{134853}Kaûem da je Kiton to uradio.
{134864}{134900}Verbal, ostavio te|je pozadi sa razlogom.
{134908}{134948}Radi samo kako ti kaûem.
{134956}{135026}Ako ste svi znali da Soze|moûe da vas nae bilo gde...
{135031}{135118}...zaöto ti je dao novac da beûiö?|Koristio bi mu na brodu.
{135127}{135153}éeleo je da ja preûivim.
{135196}{135241}Jedan pokvareni pajkan bez|lojalnosti prema ikom na svetu...
{135248}{135301}...nalazi da je teöko da spasi...
{135309}{135338}...bezvrednog bogalja tastera.
{135345}{135372}Ne, gospodine!|Zaöto?
{135396}{135418}Idi!
{135423}{135483}Ne padam na tu priËu|o promeni!
{135492}{135549}»ak i da padam, sigurno|ne verujem...
{135555}{135635}...da bi tebe poslao da|zaötitiö nju. Pa zaËto?
{135704}{135745}Zato öto mi je bio prijatelj!
{135752}{135811}Ne, Verbale. On nije bio tvoj prijatelj.
{135817}{135850}Kiton nije imao prijatelje!
{135857}{135877}äta radiö ovde?
{135883}{135907}On te je spasao...
{135914}{135974}...zato öto je tako ûeleo!|To je bila njegova volja.
{135992}{136051}Kiton je bio Kajzer Soze!|- Ne!
{136059}{136102}Tip Ëoveka koji je mogao da|upravlja voljama ljudi...
{136109}{136137}...kao öto su Hokni i MekManus.
{136143}{136160}Tip Ëoveka...
{136166}{136213}...koji je mogao da izdejstvuje|policijsko postrojavanje...
{136220}{136263}...preko svih njegovih viöegodiönjih|veza u njujorökoj policiji.
{136278}{136331}Tip Ëoveka koji je mogao da|da ubije Idi Fineran!
{136452}{136520}Naena je juËe u hotelu|u Pensilvaniji.
{136526}{136571}Upucana dvaput u glavu.
{136687}{136739}äta sada misliö o|Kitonu, Verbale?
{136778}{136847}Idi...|- Sve vas je iskoristio...
{136862}{136901}...da ga ubacite na taj brod.|Nije mogao da to uradi sam...
{136906}{136981}...morao je sam da povuËe oroz|da bi bio siguran da ima svog Ëoveka.
{136986}{137046}Jedinog Ëoveka koji je|mogao da ga identifikuje.
{137072}{137113}To je sve sranje...
{137119}{137164}Rekao si da si ga video kako umire?
{137227}{137248}Jesi li?
{137257}{137304}Morao si da se sakrijeö kada si|Ëuo policijska kola.
{137312}{137368}Rekao si da si Ëuo pucanj|pre nego öto je poËeo poûar.
{137381}{137430}Ali ga nisi video kako umire.
{137437}{137470}Znao sam ga.|On ne bi nikada...
{137475}{137504}On te je isprogramirao!
{137512}{137566}On te je isprogramirao da nam|kaûeö taËno ono öto je hteo!
{137572}{137621}Znao je da smo bili blizu,|to si i sam rekao.
{137626}{137696}Odakle je poticao politiËki pritisak?|Zaöto si zaötiÊen?
{137701}{137768}To je bio Kiton!|Imunitet je bio tvoja nagrada!
{137775}{137814}Zaöto ja?
{137826}{137873}Zaöto ne Fenster ili|MekManus ili Hokni?
{137878}{137937}Zaöto ja? Ja sam glup,|Ja sam bogalj! Zaöto ja?
{137943}{137976}Zato öto si|bogalj, Verbale.
{137989}{138073}Zato öto si glup.|Zato öto si slabiji od njih.
{138186}{138215}Ako je on mrtav...
{138229}{138310}...ako je istina ono öto tvrdiö,|onda neÊe biti bitno.
{138359}{138425}Bila je njegova ideja da napadnete|taksi sluûbu u Njujorku, zar ne?
{138432}{138460}Hajde, kaûi mi|istinu.
{138466}{138505}To je sve bilo Kitonovo maslo!
{138538}{138606}Pratili smo ga|od poËetka.
{138642}{138666}Nisam znao.
{138682}{138729}Video sam ga kako umire.
{138742}{138818}Verujem da je mrtav.|O, Boûe!
{138848}{138885}Sam nisi bezbedan.
{138989}{139014}Misliö li da je on...
{139023}{139058}Kajzer Soze?
{139080}{139119}Ne znam, Verbale.
{139156}{139243}Kajzer Soze je maska.|Kao öto si rekao, straöljiva priËa.
{139277}{139363}Ali ja znam Kitona. I postoji|neko ko povlaËi konce za tebe.
{139380}{139410}Ostani ovde i|pusti nas da te zaötitimo.
{139416}{139464}Nema öanse. Ja nisam mamac.|Danas treba da budem puöten.
{139472}{139501}Puöten si pre 20 minuta.
{139518}{139566}Kapetan Leo ûeli da|nestaneö odavde öto pre...
{139575}{139643}...osim ako ne daö dokaze tuûiocu.|- Neka hvala.
{139652}{139736}Ako neko ûeli da te uhvati...|uhvatiÊe te napolju.
{139742}{139822}Predaj dokaze tuûiocu.|Verovatno neÊeö videti suenje.
{139828}{139861}Moûe biti.
{139896}{139950}Ali ja nisam taster, agente Kujon.
{140342}{140385}Jebeni pajkani.
{140963}{141023}Izvinite. Mogu li da se|posluûim vaöim faksom?
{141119}{141163}Morate potpisati za ovo.
{141235}{141279}Jedan sat, zlatan.
{141286}{141335}Jedan upaljaË, zlatan.
{141357}{141403}I kutija cigareta. Hvala vam.
{141421}{141472}Joö uvek nemaö niöta, Dejve.
{141482}{141532}Znam ono öto sam ûeleo|da saznam o Kitonu.
{141537}{141574}Prosto niöta.
{141585}{141662}Nema veze. MoraÊe da zna|koliko smo blizu priöli.
{141683}{141748}Kajzer Soze ili ne...
{141754}{141819}...ako je Kiton ûiv,|neÊe se ponovo pojaviti.
{141834}{141874}NaÊi Êu ga.
{141888}{141927}Gubiö vreme.
{141989}{142051}TraË nije traË|koji ne umire.
{142059}{142084}äta?
{142112}{142133}Niöta.
{142183}{142222}»oveËe, baö si aljkav.
{142227}{142296}Da, u svemu postoji sistem, Dejv.
{142307}{142393}Sve ima smisla kada posmatraö na pravi|naËin. Treba da odstupiö od toga, znaö?
{142448}{142515}éeliö li da vidiö pravi horor öou?|Trebalo bi da vidiö moju garaûu.
{143414}{143457}{Y:bi}Ubedi me. IspriËaj mi|do poslednjeg detalja...
{143467}{143520}{Y:bi}Znate, kada sam bio u muökom|kvartetu u Skokiju, Ilinois, ja...
{143531}{143563}{Y:bi}Gde vam je glava, agente Kujon?
{143571}{143594}{Y:bi}Ono öto treba da uradimo je da razmislimo.
{143601}{143622}{Y:bi}Misli unazad.
{143630}{143660}{Y:bi}Siguran sam da ste Ëuli|mnoge naduvane priËe...
{143666}{143700}{Y:bi}Briks Merlin.|- Ovo nije u redu.
{143707}{143732}{Y:bi}Samo ûelim da Ëujem tvoju priËu.|- IspriËaj mi do poslednjeg detalja.
{143739}{143796}{Y:bi}Sve je tamo.|I govorim istinu, kunem se.
{143808}{143852}{Y:bi}Neki tip u Kaliforniji. Njegovo ime|je Redfut. - Poklon...
{143860}{143900}{Y:bi}...od gospodina Sozea.|- PriËaj mi, Verbale.
{143912}{143939}{Y:bi}äta je sa Redfutom?
{143948}{143983}{Y:bi}Gospodin Redfut nije znao niöta.
{143998}{144061}{Y:bi}...koristeÊi pione... - Veliki,|debeo tip. Mislim, debeo kao kit.
{144153}{144228}{Y:bi}Onomad kad sam brao pasulj u Gvatemali,|pravili smo sveûu kafu.
{144237}{144267}{Y:bi}...bio je dobar Ëovek...
{144275}{144292}{Y:bi}Znam da je bio dobar.
{144364}{144407}{Y:bi}IspriËaj mi do poslednjeg detalja.
{144413}{144428}{Y:bi}NajËudnija stvar.
{144435}{144468}{Y:bi}Kako da pucate|avolu u lea?
{144481}{144521}{Y:bi}...ovaj tip je zaötiÊen|sa vrha...
{144527}{144559}{Y:bi}...tipa ötiti i sam avo.
{144565}{144604}{Y:bi}äta ti kaûeö, Êopavi?|Koja je tvoja priËa?
{144613}{144655}{Y:bi}Postojao je advokat...|- Koji advokat, Verbale?
{144662}{144698}{Y:bi}Ja sam gospodin Kobajaöi.
{144737}{144773}{Y:bi}IspriËaj mi do poslednjeg detalja.
{144778}{144809}{Y:bi}Ja radim za Kajzer Sozea.
{144814}{144865}{Y:bi}Ubedi me.
{145236}{145335}{Y:bi}Svi najgori öljamovi koji preûivljavaju|na ulici Êe znati ime Verbal Kint.
{145350}{145387}Bogalj!|Da li si ga video?
{145393}{145429}Bogalj!|Kojim putem je otiöao?
{145434}{145463}O, on je izaöao onuda.
{145470}{145526}{Y:bi}Znam da znaö neöto.
{145532}{145573}{Y:bi}Pametniji sam nego ti,|i otkriÊu ono öto ûelim da znam...
{145580}{145615}{Y:bi}...svialo se to tebi ili ne.
{145620}{145698}{Y:bi}Pajkanu, objaönjenje nikad nije toliko|komplikovano. Uvek je jednostavno.
{145719}{145774}{Y:bi}Na ulici ne postoji misterija, ne postoji|veliki kriminalni mozak iza svega.
{145781}{145833}{Y:bi}Neko ko ima moÊ...
{145838}{145889}{Y:bi}Kajzer Soze!
{145918}{146024}{Y:bi}Misliö da takav tip doe ovoliko blizu|da bude uhvaÊen i samo promoli glavu?
{146062}{146132}{Y:bi}Zato öto si glup, Verbale!|Zato öto si bogalj!
{146137}{146168}{Y:bi}HoÊu da znam ko je Êopavi.
{146174}{146228}{Y:bi}Znaö.|Znao si Ëitavo jebeno vreme!
{146248}{146294}{Y:bi}Ako zbog bilo Ëega doe,|to Êe biti da se mene otarasi.
{146330}{146410}{Y:bi}Ne oseÊam noge... Kajzer.
{146415}{146495}{Y:bi}Znaö li koja je prva stvar|koju sam nauËio na poslu?
{146504}{146578}{Y:bi}Pomenuo je Kajzer Sozea?
{146596}{146623}{Y:bi}Koga?
{146629}{146665}{Y:bi}A posle toga...
{146678}{146744}{Y:bi}...pretpostavljam da za njega|viöe nikad neÊete Ëuti.
{147242}{147297}{Y:bi}NajveÊi trik koji je|avo ikada izveo...
{147302}{147365}{Y:bi}...je bilo ubediti|svet da on ne postoji.
{147416}{147439}{Y:bi}I tek tako...
{147482}{147521}{Y:bi}...nestao je.
{147546}{149046}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3rqv9|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
