{1}{1}25.000
{2}{135} MULJATORI 
{136}{180}Nakon öto umreö
{182}{245}Ja Êu joö biti ûiv
{273}{322}Nakon öto umreö
{324}{430}Ja Êu joö biti ûiv
{432}{478}Maury, Ëuj, imam dijete.
{480}{526}Trebam posao.
{528}{600}Nisam ja kriv. | Sad je kasno, Dave,
{602}{653}UspaniËio si se. | - Ti si odustao.
{655}{714}Odustao si veÊ öest puta, | a mogli smo sklopiti posao.
{716}{754}Sereö! S kime? | - Popis je dugaËak:
{756}{825}Crocker, narednik Saigon | sa örapnelom u glavi.
{827}{873}Bio je zreo za posao.
{875}{942}Davey, öto ti je jutros? | Moraö se opustiti.
{944}{1015}Daj da ti | stimuliram treÊe oko.
{1017}{1043}Dat Êe ti energiju.
{1045}{1102}Makni to. | Nisam pokusni kuniÊ.
{1104}{1182}Prvo dobij dozvolu, | a onda me bodi pribadaËama.
{1184}{1252}Iglama.
{1254}{1318}Svejedno trebaö dozvolu.
{1320}{1370}Kako izgledam?
{1372}{1423}Dobro. | - Jako mi nedostaje!
{1488}{1578}Samo se usredotoËi | na ono öto te Ëeka danas.
{1656}{1741}äto je? | Ma daj!
{1795}{1827}Brûe!
{1960}{2035}Dolly. Dolly, tatica je.
{2064}{2111}Tatice!
{2143}{2194}Tiho.
{2196}{2253}Hajde! Kasnimo!
{2340}{2380}Volim te.
{2382}{2449}I ja tebe. | - äto i ja tebe?
{2451}{2529}Volim te. | A öto si ti mislio?
{2531}{2603}Tu-tu! Znaö | li öto to znaËi?
{2688}{2749}Korejski par.
{2751}{2817}äto? | - BolniËarka. Odustao si.
{2819}{2910}Kao da ti se ûivo sere za to. | - Ne sere mi se.
{2912}{2964}Ako do ponedjeljka | ne platim ökolarinu,
{2966}{3025}Propustit Êu semestar. | - Tko to kaûe?
{3027}{3073}SveuËiliöte akupunkture.
{3075}{3118}SveuËiliöte? | To je ökola.
{3120}{3168}A nego öto je sveuËiliöte?
{3170}{3216}Kompleks zgrada.
{3218}{3322}Sestrinstva, zafrkancija, | stabla i sliËno.
{3324}{3380}Aha. | - Tvoje sveuËiliöte je u Resedi,
{3382}{3428}izmeu dvije trgovine.
{3430}{3486}A gdje je tvoje? | - Ne treba mi.
{3488}{3539}Sve imam ovdje.
{3566}{3622}Zapleöimo
{3624}{3662}Viöe ne mogu | trpjeti to sranje.
{3664}{3744}Ma pusti! | - Ovo ne ide.
{3746}{3833}Nemoj se ljutiti, ali | moram zaraditi za ûivot.
{3878}{3931}éeliö pokuöati sam?
{4043}{4118}Bez ovoga ne moûeö | niöta. Uzmi ih.
{4120}{4186}Ne trebam popis | moguÊih klijenata!
{4188}{4232}Ni tvoja knjiûica! | - Dobro.
{4234}{4280}Trebam samo aplikaciju | za kredit i ugovor.
{4282}{4334}Krasno. | - Ovo sam nauËio obilazeÊi kuÊe.
{4336}{4402}Od vrata do vrata. | Trebam samo cipele
{4404}{4450}i svoja usta. Stani.
{4452}{4525}IzaÊi Êu ovdje. | - Dobro, u redu.
{4527}{4566}äto radiö?
{4568}{4614}Izai. | - Mislio sam na uglu.
{4616}{4682}Jesi li kada odbacio | nekog Zemljanina?
{4684}{4767}Sjajno. | - Moûe ovdje! Dobro?
{4820}{4874}Sklopit Êu ugovore.
{4876}{4926}Kamo Êeö? | - Svijet je velik.
{4928}{4971}Samo ga nemoj pojesti.
{5008}{5070}Kretene! | - Kretene!
{5095}{5245}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{5442}{5485}Ja sam Dave Langer | iz Valley Food Service.
{5487}{5542}Ne znam jeste li Ëuli za nas,
{5544}{5586}ali reÊi Êu vam öto radimo.
{5588}{5624}Dajemo 10 piliÊa besplatno
{5626}{5678}za cijenu jednoga | mesnoga paketa.
{5680}{5762}PlaÊanje jedanput na mjesec | ukljuËuje sve. Dobro, niöta.
{5764}{5810}G. Simmons, zdravo.
{5812}{5852}Maurice Burns, | iz Valley Food Service.
{5854}{5898}Uite.
{5900}{5946}Gdje ûivite? | - To nije...
{5948}{6003}Sherman Oaks, | ali to nije vaûno.
{6005}{6053}Onda Êu ja doÊi k vama.
{6055}{6096}Kuc-kuc! | éelite li sranje?
{6098}{6130}éelite kupiti sranje?
{6132}{6186}Oprostite öto sam vam smetao.
{6188}{6229}Ugodan vam dan. | Ma jebi se!
{6231}{6313}I zaöto ne pokosiö travu?
{6315}{6362}Sigurno mrzite | kupovati, g. Simmons.
{6364}{6402}Itekako.
{6404}{6456}Viöe ne morate.
{6458}{6540}Madden. Najbolji | trener NFL-a.
{6542}{6588}Sjajno radi posao.
{6590}{6692}Sedam naslova Zapadne | divizije. MuökarËina!
{6694}{6730}Molim?
{6732}{6796}Madden. | Odakle ga poznajete?
{6798}{6856}To mi je mama.
{6858}{6941}Aha.
{7190}{7243}Zdravo. Prepoznajeö | moj zdravo?
{7245}{7291}Maurice?
{7293}{7339}Da, ja sam joö Maurice.
{7341}{7397}äto mi radi moja crvenokosa?
{7399}{7470}Ne znam, Maurice. | Nikada nisam imala crvenu kosu.
{7472}{7511}Je li to Carol?
{7513}{7598}Carolyn. I kosa mi je | smea, ako se sjeÊaö.
{7600}{7658}Zdravo. | Ma naravno da se sjeÊam.
{7660}{7706}Iöli smo u kino?
{7708}{7754}Gledali smo film | kod tebe. Kako si?
{7756}{7814}Zbilja ti je stalo? | Ili da prekinemo?
{7816}{7871}Ako to ûeliö. | - éelim.
{7873}{7920}Onda moûe.
{8000}{8082}Voli me ujutro | Voli me ujutro
{8664}{8710}Zdravo, duöo kako si?
{8712}{8760}Tata, zaboravio | si moj roendan?
{8762}{8822}Naravno da nisam. | To si mislila?
{8824}{8905}Nisam znala. | - Nikada ne bih zaboravio.
{8907}{8935}Znaö öto ûelim?
{8937}{8986}Znam. Moûeö | li mi ponoviti?
{8988}{9046}LjuljaËku i tobogan. | - LjuljaËku i tobogan.
{9048}{9127}Da. Evo ti mama.
{9182}{9238}Nemoj je razoËarati, Dave.
{9240}{9286}Ne smije misliti da si gubitnik.
{9288}{9326}Ne misli to.
{9328}{9410}Moraö biti pravi. | Imali u tebi joö toga?
{9412}{9489}Renee, dajem sve od sebe.
{9491}{9584}Ako moûeö, | kupi joj neöto lijepo.
{10716}{10769}To nam je najbolji model.
{10771}{10827}550 dolara?
{10829}{10893}Drvo je zbilja | nuûno za ljuljaËku?
{10895}{10951}Najbolje je za dijete.
{10953}{10999}Ovaj je model na sniûenju.
{11001}{11038}Posljednji nam je.
{11040}{11083}Ovo je moûda posljednja prilika
{11085}{11132}da je dobijete po ovoj cijeni.
{11175}{11214}Zafrkavaö me?
{11216}{11286}Molim? | - Meni uvaljujeö to sranje?
{11288}{11347}Molim? | - To je tvoja udarna spika?
{11349}{11414}Udarna spika? | - Udarna spika, Glenne.
{11416}{11470}Moraö to malo razraditi.
{11472}{11526}Primi se neke teme. | Govori o sjeËi stabala.
{11528}{11576}Sijeku ih diljem svijeta.
{11578}{11624}Ovako kvalitetno drvo
{11626}{11672}ne stavlja se na svu | opremu za djecu.
{12322}{12409}Hej. | - Hej.
{12411}{12450}Kako si proöao?
{12452}{12502}Nikako.
{12504}{12546}Ni ja.
{12611}{12657}Oprosti zbog onoga.
{12659}{12739}Nema veze. | Bilo, proölo.
{12782}{12829}Proölo.
{12869}{12929}Gledaj.
{12931}{12978}Pogledaj to.
{12980}{13066}Zgodna je. Samo polako.
{13068}{13115}Presretna je za tebe.
{13156}{13236}Kako je? | - Sada imam dva ledena Ëaja.
{13238}{13302}Sigurno ste ûedni.
{13304}{13388}Kristy, vidiö li öto radim | kako bismo malo bili zajedno?
{13390}{13464}A tanjur je pobjegao sa ûlicom.
{13466}{13536}Teöko mi je | öto nismo zajedno.
{13538}{13581}Moramo se ËeöÊe viati.
{13583}{13663}To ja mislim. | - A ja mislim da ste ludi.
{13889}{13939}PomoÊi Êeö mi | da ukradem ljuljaËku?
{13976}{14034}Nakon öto kuöamo ovo.
{14038}{14090}Sve piöe u aplikaciji.
{14092}{14129}Besplatna dostava, | besplatan zamrzivaË
{14131}{14185}i 10 besplatnih filea.
{14222}{14263}Uzmite.
{14300}{14373}äto Êe nam ovoliko mesa?
{14417}{14477}Razgovarali smo o tome. | Andy voli filee.
{14479}{14513}Vi volite rebrica.
{14515}{14593}Ova narudûba | naËinjena je za obitelj Wilson.
{14595}{14642}Sally's se fura na zdravlje.
{14644}{14726}To nije furka. | - Program, duöo.
{14728}{14790}éeli se hraniti zdravom hranom.
{14792}{14840}Srû zdrave | prehrane jest meso.
{14842}{14930}Svu ostalu hranu | jedete kao dodatak.
{14932}{14996}Bog nas je stvorio | da jedemo meso.
{14998}{15065}Probava bolje radi | kada dobije ono öto treba.
{15067}{15149}Nije li zdravo jesti ono | öto Bog ûeli da jedete?
{15151}{15209}Pa valjda jest.
{15211}{15258}I ja mislim.
{15321}{15369}Uzmite zbog Sallyna zdravlja.
{15371}{15427}Duöo...
{15486}{15554}Aha... | - Dobro.
{15556}{15620}Ujutro Êemo vam | donijeti zamrzivaË.
{15622}{15736}Aha
{15738}{15807}Sve Êe
{15809}{15916}Sve Êe biti dobro
{15918}{15996}JuËer nam je krenulo. | - Slaûem se.
{15998}{16051}Aha
{16172}{16221}Pobjeda lijepo miriöi. | - I ima dobar okus.
{16223}{16279}G. Wilson? | - Ne, ûao mi je.
{16281}{16331}Ne moûete to unijeti. | I maknite kamion.
{16333}{16375}Ne ûelimo to.
{16377}{16446}Pobjedu okusiö, | a uspjeh nanjuöiö.
{16448}{16497}Sranje! Hajde! | - Ne!
{16499}{16538}Ipak smo trebali ostati na Ëaju.
{16540}{16596}Nema öanse! | - »ekaj.
{16652}{16710}Sve je u redu. | PriËekajte.
{16712}{16748}Bit Êe dobro.
{16750}{16816}Andy, Sally, svidjet | Êe vam se, lijep je.
{16818}{16874}Predomislili smo se. | - Ne, ne, u redu je.
{16876}{16930}Andy i Sally, | stalno to viamo.
{16932}{17015}Normalno je osjetiti | te snaûne osjeÊaje
{17017}{17074}kada neöto kupite. | - Ma naravno.
{17076}{17155}Promjena je dobra! | Znate da je tako.
{17157}{17216}Pokucajte ako mislite | da je promjena dobra.
{17218}{17297}Rukuj se s vragom
{17359}{17460}Hajde, Andy, Sally. | Dogovorili smo se!
{17462}{17508}Brzo prolazite ljude s popisa.
{17510}{17575}Mislim da vam | treba odmor.
{17577}{17625}Psihijatar si?
{17627}{17673}Mogao bi malo | u Ensenadu, Langeru.
{17675}{17721}Vjerojatno obojica, odvojeno.
{17723}{17758}Ti si nam druötveni direktor? | - To znaËi da smo dobili otkaz.
{17760}{17806}To znaËi fraza | "OtiÊi u Ensenadu"?
{17808}{17880}Ovo je samo loöa faza, | Dick. Svatko ih ima.
{17882}{17938}Dick, ne shvaÊaö | da samo nemamo sreÊu?
{17940}{18026}Ako vjerujeö u sreÊu, | onda si papak.
{18028}{18074}Bio si ubojica, Maury. | äto se dogodilo?
{18076}{18136}Sve se mijena, Dick. | - Zaboravi, Maury.
{18138}{18178}Dick, razgovaraö sa mnom.
{18180}{18226}Reci mojoj kÊeri da je | volim. Idem ja skoËiti.
{18228}{18278}Ne dramatiziraj.
{18280}{18329}Dat Êu vam neöto.
{18404}{18498}Ovo su nam najbolji | potencijalni klijenti.
{18500}{18565}Ovdje sigurno ima | jedan, moûda dva ugovora.
{18567}{18618}Ako vam ni | s njima ne uspije,
{18620}{18666}morat Êemo se raziÊi.
{18668}{18734}Trebam prodavaËe | koji prodaju.
{18736}{18807}ProfiÊi ste.
{18809}{18870}Ne forsirajte, zaboga!
{18872}{18938}Pojedite dobar doruËak, | moûda koje pecivo viöka,
{18940}{19005}a onda idite sklapati ugovore.
{19128}{19210}Rashladite se. | Bit Êe paklena vruÊina.
{19212}{19289}Rano je jutro | i niöta mi ne ide
{19291}{19355}SinoÊ sam se | posvaao s curom
{19357}{19427}I rano je jutro
{19471}{19542}Ne znaö da je rano jutro?
{19662}{19746}Rano ujutro
{19748}{19813}Ostao mi je samo blues
{19958}{20033}Moûda je ovdje. | Savröeni potencijalni klijent.
{20035}{20133}Boûji papiriÊ. | Spreman sam za njega.
{20135}{20189}Kada pomislim na njega,
{20191}{20230}neöto se dogodi.
{20232}{20318}Znam, znam. | Jako se uzbudiö.
{20407}{20453}Vrlo lijepo.
{20455}{20494}Vrlo dobro.
{20496}{20531}Zdravo. | - Zdravo.
{20578}{20633}Zbilja brzo uÊi.
{20635}{20697}PoËeo sam je | poduËavati prije tri godine.
{20699}{20786}Sada ona meni daje | lekcije, ali ne iz klavira.
{20788}{20847}»ujte. | Ovim programom
{20849}{20942}uötedjet Êete veÊi dio onoga | öto zaradite kao uËitelj glazbe.
{20944}{21014}To je dobra ideja, Leone.
{21016}{21096}Priznajem da zvuËi | dobro. Da razmislim.
{21100}{21130}Hajde. | - Razmislite.
{21132}{21178}éeli razmisliti.
{21180}{21216}Leone.
{21218}{21300}Beethoven. Mislite | da je on razmiöljao:
{21302}{21378}Da li da skladam...
{21380}{21434}Nije, samo je skladao.
{21436}{21520}Hvala Bogu da jest. | To je ispravna odluka, Leone.
{21522}{21562}Potpiöite.
{21564}{21672}NeÊu biti veliki skladatelj. | Mogu bar dobro jesti.
{21674}{21729}IduÊe godine odlazim odavde.
{21731}{21772}I reÊi Êu vam joö neöto.
{21774}{21852}»ak i ako se vi i ta | gospoica odluËite vjenËati,
{21854}{21906}malo Êemo promijeniti ugovor.
{21908}{21944}I vi, ha?
{21946}{22018}Mnogo razgovaramo o tome.
{22020}{22066}Trebali bismo | se vjenËati, zar ne?
{22068}{22153}Odmah se vidi | da vam ûeli biti ûena.
{22155}{22250}To je dobra prilika, | ali trebao bih...
{22252}{22302}Razgovarati s Karen.
{22304}{22396}Kada se doseli ovamo, | to Êe biti i njezin zamrzivaË.
{22398}{22444}Ostavite mi posjetnicu.
{22446}{22507}Razgovarat Êemo.
{22555}{22600}Potpiöite.
{22602}{22690}Samo pruûi olovku! | Niöta ne govori!
{22720}{22774}IduÊi je potez njegov.
{22776}{22826}Ima samo jedan potez.
{22828}{22874}Uzme olovku. | - Znam.
{22876}{22922}Zaöto mi nisi dao signal?
{22924}{22965}Pokaûi mi prst.
{22967}{23021}Rekao sam ööö. | - To nije dovoljno.
{23023}{23090}Ne mogu to Ëuti. | Samo mi takni nogu.
{23092}{23180}Isuse, Davey, | moram dovröiti semestar.
{23182}{23257}äest mjeseci staûiranja | i bit Êu lijeËnik.
{23259}{23297}Znam.
{23299}{23365}Da je moj otac to znao...
{23367}{23426}Bio bi...
{23428}{23506}Joö bi bio mrtav, ali | s drugim izrazom lica.
{23508}{23570}Znat Êe.
{23572}{23653}Mislim da u meni | nikada nije vidio muökarca.
{23655}{23738}Znaö, moj otac... | Razgovaram s njime
{23740}{23814}i kaûem mu: | Budi strpljiv.
{23816}{23868}Za mene joö nije gotovo.
{23870}{23916}A ako nije gotovo za mene,
{23918}{23982}onda ne neki Ëudan | naËin nije ni za njega.
{23984}{24043}Joö se trudim i traûim.
{24045}{24109}Da, a öto traûiö?
{24111}{24182}Neki znak da | znam da me Bog vidi.
{24428}{24476}Sranje!
{24478}{24530}Gdje je drugi papiriÊ?
{24532}{24580}Bili su kod tebe.
{24582}{24667}äto je, Davey? | äto se dogaa, Davey?
{24669}{24709}Stani!
{24711}{24766}Nai taj | papiriÊ koji si izgubio!
{24768}{24817}Pogledaj sve ove | papire od hamburgera!
{24819}{24865}Rekao sam ti da to ne jedeö. | - Aha, samo ih ja jedem!
{24867}{24913}Samo ja! | - Samo ti.
{24915}{24950}Ne seri!
{24952}{25013}Ti samo gledaö | kada ja naruËim? I ti jedeö
{25015}{25065}Ali meni to nije religija! | - I ti jedeö, jebote!
{25067}{25146}Meni to nije | poput voûnje u lunaparku.
{25148}{25222}Daj mi zadnji prije | nego öto i njega izgubiö.
{25224}{25317}Oprosti! | - To je to, Davey.
{25319}{25365}Ovo je zadnja öansa. | - éao mi je.
{25367}{25416}Zadnja adresa, Davey. | Moramo se usredotoËiti.
{25418}{25470}U redu? Udahni. | - U redu.
{25472}{25530}Sve je dobro. | Jesi li dobro?
{25532}{25607}Dobro sam.
{25640}{25727}Gade! | Udarit Êu te u öupak!
{26128}{26199}Dobro sam.
{26201}{26259}Udarit Êu te u öupak?
{26261}{26342}Zbunio sam se. | Htio sam reÊi: Udarit Êu te.
{26344}{26392}I onda: äupËino.
{26394}{26470}Aha.
{26472}{26519}Smislit Êemo putem.
{26695}{26766}Moj ûivot
{26768}{26820}Na suncu
{26871}{26943}Svatko voli sunce
{27046}{27107}Sunce
{27157}{27225}Svatko voli sunce
{27323}{27373}Sunce
{27440}{27534}Ljudi izlaze na sunce
{27536}{27617}Boûe, samo | ne daj da molim.
{27619}{27667}Trenutak.
{28054}{28089}Zdravo.
{28091}{28185}Ja sam Maurice Burns. | Iz Valley Food Service.
{28187}{28274}Ovo je Dave Langer. | On radi za mene.
{28276}{28342}Doöli ste. Uite.
{28344}{28391}Hvala.
{28435}{28510}Razgovaram. Prijateljica | ima problem s deËkom.
{28512}{28575}Sjednite, odmah dolazim.
{28609}{28685}PutujuÊi trgovci.
{28748}{28813}»ovjeËe!
{28815}{28877}Lijepo. »isto je.
{28879}{28948}Boûe!
{28950}{29006}Maury, stavi kurac | u vreÊu i zakopaj je.
{29008}{29062}Sklopit Êemo ugovor. | Njuöim to.
{29064}{29135}I ono öto | njuöim dobro miriöi.
{29137}{29191}Spreman sam.
{29193}{29239}Budi spreman. | - Ovdje sam.
{29241}{29307}- ZaËepi! »uje te. | - Prodajmo meso.
{29309}{29425}äuti! | - VeÊ sam viao lijepe ûene.
{29427}{29502}VreÊa bi trebala biti velika. | - ZaËepi!
{29504}{29552}Odreske moûemo | narezati debele 1,25 cm,
{29554}{29624}2 cm ili 2,50 cm. | äto vam se viöe svia?
{29626}{29698}Volim raznolikost.
{29700}{29798}Paket Êemo poËeti | s 5 kg besplatnih filea.
{29800}{29882}Najboljih. Tako vam pokazujemo | da nam mnogo znaËite.
{29884}{29946}Zar ne? | - Kakav zamrzivaË imate?
{29948}{29981}Samo jedan u...
{29983}{30023}Onako na vrhu hladnjaka?
{30025}{30087}U redu je. | Moûemo vam ugraditi jedinicu.
{30089}{30140}Zbilja? Kakvu jedinicu?
{30236}{30315}IspriËavam se.
{30408}{30477}Ovo ide dobro.
{30479}{30538}Bez problema. | Samo ne poûuruj.
{30540}{30586}Nema ûurbe.
{30588}{30625}Samo kaûem. | - Dobro sam.
{30627}{30666}Suzy je izvan sebe.
{30668}{30714}Ne moûe naÊi zlatnu ribicu
{30716}{30769}i neöto joj se | mota po ûelucu.
{30771}{30820}Oprostite, ali rekla sam | joj da je kod mene lijeËnik
{30822}{30874}i da mi je prijatelj. | To ste vi. Doite.
{30876}{30945}Recite joj da to nije niöta.
{30947}{31007}Doite.
{31196}{31275}Suzy, duöo, evo ga.
{31305}{31375}Zdravo, ovdje...
{31404}{31467}Dr. Kissinger.
{31469}{31539}Mogu li vam pomoÊi? Aha.
{31541}{31586}Mnogo je takvih sluËajeva.
{31588}{31652}Nemoj se brinuti.
{31654}{31728}U medicini se | drûimo jednog pravila.
{31730}{31800}Ako je neöto veliko, | onda to vadimo.
{31802}{31862}Ali ako je riba, | pusti da otpliva niza struju.
{31864}{31940}Moûeö ako to ûeliö.
{32092}{32170}Je li sve u redu?
{32172}{32223}Doite.
{32492}{32603}Moûete li prevrnuti | tu teöku bocu, Maurice?
{32605}{32673}Dok ste ovdje. | - Moûe.
{32675}{32739}Niöta ne mogu zbog noktiju.
{32938}{32984}Volite mjehuriÊe?
{32986}{33043}Oboûavam ih.
{33148}{33195}Ha?
{33243}{33332}Vama je to bilo lako. | Tako ste jaki.
{33334}{33398}Vjeûbate?
{33400}{33481}Ne, jak sam sam od sebe. | Ne znam zaöto.
{33523}{33565}Dobri geni.
{33567}{33637}Majka mi je bila jaka.
{33639}{33701}I moja.
{33703}{33765}Hm.
{33767}{33845}Znate, trebali | bismo razgovarati o poslu.
{33847}{33924}Da, da. | Dave je rekao bez oËijukanja,
{33926}{33998}ali mislio je samo na mene. | Vi slobodno moûete.
{34000}{34088}Izvolite. | Pokuöajte me privuÊi.
{34090}{34160}Pokaûite mi svoje meso.
{34162}{34266}Vaö partner misli | da je najbolje u drûavi.
{34268}{34326}To je istina.
{34328}{34402}Kada se oporaviö, | kupit Êeö novu ribicu.
{34404}{34434}Dobro?
{34436}{34503}Sada samo prilegni i smiri se.
{34505}{34582}Odmaraj se. | Dobro. Zdravo.
{34711}{34773}Naravno, kako bi | vam se to isplatilo,
{34775}{34821}isporuËujemo veÊe koliËine.
{34823}{34906}Kupite goveu polovicu... | - Vi Êete mi je donijeti?
{34908}{34977}Ja osobno?
{34979}{35059}A koliko bi to | bilo bez tobogana?
{35061}{35126}Da, isti model bez...
{35128}{35209}Moûete li priËekati | trenutak, molim vas?
{35211}{35289}Halo? Suzanne.
{35291}{35347}Mislio sam da se odmaraö.
{35349}{35420}Jesam, joö sam ovdje.
{35422}{35509}Dobro, ali sada | ûelim da se smiriö, dobro?
{35511}{35573}Zaûmiri i sjeti se | da ima mnogo stvari
{35575}{35618}o kojima moûeö sanjati.
{35656}{35743}Pa na primjer | bilo öto öto ûeliö.
{35781}{35826}Voliö lubenicu.
{35828}{35940}Potpiöite se. | - Dobro.
{35942}{36004}To je loöa ideja. Smiri se.
{36006}{36064}Smiri se! Suzanne!
{36066}{36134}Jeste li potpisali?
{36136}{36213}Morate razgovarati s njom. | Mislim da se ûeli ubiti.
{36215}{36242}Opet?
{36244}{36306}éao mi je, ali nisam lijeËnik.
{36308}{36361}Morate razgovarati s njom.
{36363}{36410}Baö je htjela potpisati Ëek.
{36412}{36465}äto mogu? | Nisam lijeËnik!
{36467}{36512}Sranje!
{36514}{36585}Suzanna, doÊi Êu. | Nemoj zakljuËati vrata!
{36587}{36642}Suzy, nemoj!
{36644}{36714}Suzy je prerezala venu. Kaûe | da ne ûeli samo privuÊi paûnju,
{36716}{36754}ali ja znam da ûeli.
{36756}{36808}Moram joj otiÊi pomoÊi.
{36810}{36877}Moûemo ovo i poslije. | - Ne moûemo poslije.
{36879}{36934}Odvest Êemo vas. | Mi Êemo voziti.
{36936}{36998}Hajdemo. Poslije | Êemo ovo dovröiti.
{37000}{37094}Ne bih smjela. | - Nekada se utrkivao.
{37096}{37152}Dobro, hajdemo.
{37154}{37212}Neka potpiöe u autu.
{37567}{37630}Sada moûemo | dovröiti papirologiju.
{37632}{37675}Da.
{37677}{37770}Suzy mi je jedina | prijateljica otkako sam doöla.
{37772}{37875}Mnogo smo puta | zajedno upadale u nevolju.
{37877}{37926}NauËila me svim | prostotama na engleskome.
{37928}{38002}Recimo jebemti | ili govno jedno
{38004}{38070}i jebem ti mater | i öupËino
{38072}{38173}i puöi kurac | i popuöi mi ga.
{38208}{38268}Nije loöe. | - Da.
{38270}{38365}Zelenooka ûeno... | - Dobro je.
{38367}{38437}Polako hodaö
{38439}{38505}Prema suncu
{38878}{38925}Suzy, Suzy!
{38927}{38991}DeËki, laûna uzbuna.
{38993}{39110}Mnogo mi je bolje. | Aha, dovela si druötvo.
{39112}{39212}Uite. Baö mi je | neugodno öto sam vikala.
{39214}{39268}»uli ste me kako viËem?
{39270}{39373}Priznajem, katkada | zbilja znam pretjerati.
{39375}{39425}»ekajte. Gledajte.
{39427}{39470}Pogledajte.
{39472}{39556}Gle, gle.
{39558}{39644}A nisam iöla | na teËaj za bolniËarku.
{39646}{39696}Mogla bih biti bolniËarka.
{39698}{39774}Prijo, da vidim. | äto si uËinila?
{39776}{39822}Loridonna, nije ni krvarilo.
{39824}{39891}Ma to nije niöta.
{40054}{40097}Doöli ste me ubiti?
{40099}{40158}Ne, Suzy, ne.
{40160}{40222}To je lijeËnik.
{40224}{40309}Boûe!
{40311}{40398}Kissinger. | Vi... Vi...
{40400}{40431}Ja sam.
{40433}{40479}Vi...
{40481}{40529}»udno izgledate.
{40531}{40604}Dobro.
{40606}{40684}Jesam li ispravno postupila? | - Suzy, molim te.
{40686}{40750}Ne znam.
{40752}{40817}Mnogo ste popili, zar ne?
{40819}{40876}Nisam. Samo... | - Jesi.
{40878}{40954}Popila sam | samo jedno piÊe.
{40956}{41007}Ne mogu vjerovati da si doöla.
{41009}{41105}Super si prijateljica. | I dovela si ljude.
{41168}{41244}Usred posla smo. | - Odjebimo odavde.
{41246}{41292}Ne, ne, ne.
{41294}{41346}Smirit Êe se | i tada Êe potpisati.
{41348}{41397}Ne mogu! Ne mogu!
{41399}{41495}Idi je nekako zabavi | i poöalji mi Loridonnu.
{41497}{41530}Nema öanse | - Zaöto?
{41532}{41578}Maury, ovo je posao.
{41580}{41611}Znam da je ovo posao.
{41613}{41701}LijeËnik... | éeli lijeËnika.
{41703}{41746}éeli lijeËnika.
{41748}{41811}Dave, sve je u redu.
{41853}{41907}Bit Êu u kuhinji.
{42324}{42406}Mislim da tvoj prijatelj | sve ima pod kontrolom.
{42408}{42462}Oh.
{42464}{42513}Da.
{42515}{42570}Dobro radi pod pritiskom.
{42572}{42625}Pogledaj öto sam naöla.
{42627}{42707}Ah.
{42709}{42803}Moûda bismo | trebali dovröiti posao.
{42889}{42968}Moûda bismo | trebali malo popiti.
{43338}{43413}Vjerojatno bismo trebali | dovröiti papirologiju.
{43472}{43556}Ti si od onih koji | prvo zavröe posao?
{43558}{43633}Mnogi misle | da je tako najbolje.
{44032}{44094}Kao da si zabrinut? | - OsjeÊam se kao da...
{44096}{44129}Imam visove i doline.
{44131}{44180}Uvijek ima... | Ali tako je sa svima.
{44182}{44248}To je ûivot. | Tako je Bog i htio.
{44250}{44291}Visovi i doline.
{44293}{44369}Koji je loö dio?
{44371}{44446}Visovi ili doline? | - Mislim da su doline.
{44448}{44506}Zato öto su niûe | od visova i ne moûeö...
{44508}{44568}Tako se uvijek osjeÊaö.
{44570}{44646}Da, kao da | si posve sam.
{44648}{44718}Da. | - ShvaÊaö me?
{44972}{45019}Sve imaö pod kontrolom.
{45050}{45090}To mi se svia.
{45092}{45166}To me pali.
{45232}{45279}Pravi si...
{45330}{45371}Muökarac.
{45373}{45430}I zasluûila si patiti
{45432}{45522}To je samo gluma.
{45524}{45570}Mnogo zamiöljam.
{45572}{45643}Ja sam stalno zamiöljala.
{45706}{45757}Zamiöljaö i sada?
{45759}{45834}Samo... Znaö.
{45836}{45909}Cure nisu jake.
{45911}{45993}Varamo.
{45995}{46042}Zato uvijek pobijedite.
{46220}{46281}Trebali bismo | sklopiti posao do kraja.
{46283}{46330}Da.
{46397}{46470}Da, trebali bismo.
{46528}{46596}Trebali bismo...
{46598}{46660}Dovröiti papirologiju.
{46662}{46709}Ne slaûeö se?
{46711}{46740}Budemo, budemo.
{46799}{46860}Imaö pravo. | - Vidiö?
{46862}{46918}Totalno imaö pravo.
{46920}{47016}Moram biti prava. | - Da.
{47018}{47056}Budi prava.
{47058}{47098}Moraö si htjeti pomoÊi.
{47100}{47174}I ûelim! | éelim si pomoÊi.
{47176}{47234}I moûeö jer u tebi | se krije dobra osoba.
{47236}{47300}Moraö je izvuÊi. | - Kako se to radi?
{47302}{47351}Kako da izvuËem staru sebe?
{47353}{47421}Moraö je natjerati da izae.
{47423}{47478}Izbaci je iz tijela! | - Mogu je opaliti!
{47480}{47516}äutni je! | - äutnu Êu je!
{47518}{47562}Da. | - Van!
{47564}{47605}Ali to nije doslovno!
{47607}{47647}Nije doslovno.
{47649}{47684}To je... | - Kako je moram udariti?
{47686}{47745}Samo iznutra. | - Ali koja sam ja ja?
{47747}{47814}Ti si ona dobra ti. | Ona jaka ti. Dobro?
{47816}{47865}Da.
{47867}{47912}Ovako...
{47914}{47973}Idemo. Ovo... | - Dobro.
{47975}{48026}Ovo si stara ti.
{48028}{48072}Jebi se! | - Dobro je.
{48074}{48116}Odjebi!
{48118}{48162}Kravo!
{48164}{48266}Tako je. | - Pokuöala si me pokopati.
{48268}{48314}Pokopati te. | - JaËa sam od tebe.
{48316}{48390}Mnogo si jaËa od nje. | - JaËa sam nego öto Êeö ikada biti.
{48392}{48448}Idem vidjeti öto radi Maury. | - Puna si...
{48450}{48496}Dobro je. | - »ekaj!
{48498}{48565}U redu je. Nikamo ne idem.
{48567}{48608}Ne mogu ovo bez tebe.
{48610}{48655}Uredu je, ovdje sam.
{48780}{48849}Tony, vratio si se.
{48946}{48999}Odmah se vraÊam.
{49056}{49098}Boûe!
{49100}{49150}äto? | - Pomaknut Êu se.
{49152}{49200}Zna da nismo niöta radili?
{49202}{49284}Moûeö li, molim te, | to odjenuti?
{49318}{49394}Koje su öanse da | mi budemo zajedno?
{49396}{49450}Moûda nikakve.
{49452}{49530}Nikakve? | Zaöto tako?
{49571}{49618}Joö ti ne ûelim reÊi.
{49620}{49669}Gle, gle.
{49671}{49738}Ako neöto veÊ | imaö, mogu ja otiÊi.
{49740}{49803}Nje stvar u tome.
{49805}{49858}Ne brini se sada zbog toga.
{50001}{50058}U redu je. | Nemojte stati.
{50060}{50109}Nemojte stati. | Ne vidim NeÊu gledati.
{50111}{50156}Slijep sam.
{50212}{50257}To je super pjesma.
{50259}{50329}Moram pogledati. | Tko je ovdje?
{50331}{50372}Zdravo, Tony.
{50374}{50441}Loridonna, Loridonna, | Loridonna, Loridonna, Loridonna.
{50443}{50551}Kakva Ëast! | Nemoj ustajati.
{50553}{50616}äto god da radiö, | ostani kako jesi.
{50651}{50711}äto se dogaa?
{50713}{50770}Krvari. HoÊeö li... | - TipiËno.
{50772}{50806}U dûepu ima 2-3 piötolja.
{50808}{50839}U redu je.
{50841}{50903}Toga su tipa nastrijelili.
{50905}{50982}To je tipiËno.
{50984}{51033}Prijatelju, moûeö li mi pomoÊi?
{51069}{51106}Tko? Ja?
{51108}{51154}Da, ti. | - Ja?
{51156}{51203}Da, ti.
{51247}{51306}Da. | - Ui.
{51308}{51350}äto je?
{51352}{51410}To je...
{51412}{51463}Uzmi to, to, | ovo, ovo.
{51465}{51506}Da. | - Stavi to.
{51508}{51579}To bi trebalo pogledati. | - Upravo gledam.
{51625}{51665}Netko te napao?
{51667}{51745}Ogrebotina. | Taj drugi je mrtav.
{51747}{51797}ShvaÊam.
{51799}{51858}Ne shvaÊaö.
{51860}{51926}Ovo je lijepa kuÊa. | Baö je svjeûe.
{51928}{51982}Zabavna gajba.
{51984}{52056}Bomba je ta Loridonna.
{52058}{52099}Jest.
{52101}{52160}Jest, valjda.
{52162}{52215}Teöko je vjerovati da je muöko.
{52217}{52298}Kako to misliö? | - Bila je muökarac.
{52300}{52370}Ali uopÊe se ne vidi, je li?
{52372}{52429}Nema öanse!
{52431}{52474}Tako sam Ëuo.
{52476}{52527}Nema öanse!
{52578}{52650}Loridonna.
{52652}{52702}Jesi li bila muökarac?
{52704}{52767}Hajde, reci mu.
{52958}{53005}Davno.
{53096}{53143}Magija ûivota.
{53170}{53217}Vi to rijeöite.
{53448}{53496}»ovjeËe.
{53498}{53564}Bez obzira na to | öto kaûe, ostani smiren.
{53566}{53618}Niöta nismo radili. | - Baö ga sere!
{53620}{53668}Niöta nismo radili. U redu je.
{53670}{53694}Dolazi.
{53696}{53738}Zdravo, Suze. | - Zdravo, Tony.
{53740}{53782}Zdravo.
{53784}{53823}Zdravo. | - Zdravo.
{53825}{53861}Kako si?
{53895}{53922}Boûe! Ne!
{53924}{53975}Ulovio sam te kako mi | öeviö curu! - Boûe, ne!
{53977}{54019}Nisam, kunem se! | - Jebeö moju curu?
{54021}{54078}Nisam, kunem se! | - Upucavaö se ili jebeö?
{54080}{54124}äto? | - Tony, nemoj!
{54126}{54164}Nisam, kunem se! | - Boûe!
{54166}{54202}Jebao te? | To ste...
{54204}{54277}Nismo. | - Nemoj, molim te.
{54368}{54442}Ma u redu je. | Samo se zafrkavam.
{54444}{54503}äalim se. | - To je bilo duhovito.
{54545}{54583}Tko je ovaj?
{54585}{54640}Loridonnin prijatelj.
{54642}{54678}Ona ga je dovela.
{54680}{54723}Dobro. Prijatelj? | - Da.
{54725}{54783}Da. | - Sjedni poput prijatelja.
{54785}{54883}Sjedni. äto ti je | radio? - Niöta.
{54885}{54932}äto si radio s mojom | curom u mojoj kuÊi?
{54934}{54994}Niöta. Razgovarali smo.
{54996}{55045}»itao ti je dlan? | - Nisam.
{55047}{55152}Sav novac koji joj dajem | potroöi na jebeni dlan.
{55154}{55226}To je sjajno.
{55228}{55326}To se tvoj prijatelj | tamo igra s Loridonnom?
{55328}{55374}Maurice je moj suradnik.
{55376}{55430}Poznajem je | preko Mauricea.
{55432}{55472}Dobar je momak.
{55474}{55521}U redu je.
{55787}{55834}To je Boris?
{55878}{55942}Tko? Ne znam.
{55944}{55999}Ja postavljam pitanja.
{56001}{56042}Boris te plaÊa?
{56044}{56121}Ne poznajem Borisa. | Ako mislite da ga poznajem,
{56123}{56166}stekli ste pogreöan dojam.
{56192}{56222}Dobro.
{56224}{56272}Dobro.
{56274}{56315}Dobro.
{56362}{56396}»ime se onda baviö?
{56398}{56444}äto ti je posao?
{56446}{56530}Ja sam savjetnik.
{56532}{56570}Oh. | - Aha.
{56572}{56649}Ali moja je | prava strast govedina.
{56651}{56742}äaliö se? | Imaö dva posla?
{56744}{56853}To je bolje nego imati | jedan posao. To je super.
{56855}{56923}Hej. | Vau-vau.
{56925}{56975}Tony, ne u javnosti. | - Vau-vau.
{56977}{57036}Boûe! | - Laj.
{57038}{57113}Baviö se stokom? | - Da. Dave Langer, zdravo.
{57115}{57168}Dave, kako si? | - Drago mi je.
{57170}{57230}Koliko grla imaö? | Ili sve drûi korporacija?
{57232}{57266}Usrani gadovi!
{57268}{57337}Da, sve viöe, ali mi se | bavimo gurmanskom stranom
{57339}{57410}i ljudima koji | vole kvalitetnu govedinu.
{57412}{57507}Dobru, lijepo | ostarjelu govedinu.
{57509}{57625}Ali ako teletina | ostari, je li joö teletina?
{57627}{57692}Jednoga dana mora odrasti.
{57694}{57762}I öto onda postane?
{57764}{57820}To je poput djece glumaca.
{57822}{57870}Kada odrastu, | uvijek su...
{57872}{57917}äuti!
{57962}{58009}äto je? | - äuti!
{58085}{58177}Tvoja je | govedina zbilja dobra?
{58179}{58223}Japanska je sjajna.
{58225}{58281}Znaö li öto rade | kako bi meso bilo mekano?
{58283}{58344}»itao sam da | krave udaraju öakama.
{58346}{58416}Moraju udarati kravu!
{58418}{58468}To je govedina iz Kobea.
{58470}{58542}Voliö odreske. | Srednje peËene.
{58544}{58608}Slabo peËene. | - Slabo peËene.
{58610}{58650}I ja. | - Da.
{58652}{58721}Zato sam i znao | jer sam isti takav.
{58723}{58823}Jesi li gladan? | - Gladan sam.
{58825}{58854}éeliö piÊe? | - Rado bih...
{58856}{58892}ZaËepi! Naravno da ûeliö.
{58894}{58927}éeliö piÊe, duöo? | - PiÊe.
{58929}{58971}éeliö piÊe? Cijelu bocu?
{58973}{59015}Samo Ëaöu, molim.
{59017}{59082}Pobjegni iz ludnice. | Pokuöaj niöta ne sruöiti.
{59084}{59127}Dave, vidimo se poslije.
{59168}{59241}Ne bih smio. Ali hoÊu.
{59243}{59308}Ne volim varati. | Vidiö li ovo?
{59310}{59373}Moraju se pacati joö jedan dan.
{59375}{59440}Najbolje je prije | nego öto istrune. Primi.
{59442}{59489}Vidiö? Proöarano masnoÊom.
{59491}{59544}Znaö li öto je to?
{59546}{59617}To je najbolji | prijatelj ljubitelja mesa.
{59619}{59662}Ovo je poput naöe govedine.
{59664}{59734}Neöto bih ti rekao. | - Idemo van, Dave.
{59736}{59842}Ja volim kada je | malo viöe proöarano.
{59844}{59903}Moûemo varirati | debljinu. - Je li?
{59905}{59970}1,5 cm, 2 cm,
{59972}{60015}restoranski, | kako god ûeliö.
{60017}{60074}G. Goldbluthu | bi se to svidjelo.
{60076}{60113}Razumije se u to.
{60115}{60159}Ljubitelj je?
{60161}{60198}Voli jesti.
{60200}{60277}Njemu donose | hranu iz cijelog svijeta.
{60279}{60333}Kavijar iz Rusije.
{60335}{60403}Dobiva jebene | smokve iz Irana.
{60405}{60466}Posebne kolaËe iz Pariza.
{60508}{60567}Iz Francuske. | - To je sjajno.
{60611}{60695}Okus uvelike ovisi | o tome kako kuhaö.
{60697}{60746}Dobro je öto ti | i u tome moûemo pomoÊi.
{60748}{60835}Moûemo ti dati recepte | s detaljnim uputama i...
{60879}{60930}Pravit Êu se da to nisi rekao.
{61008}{61054}Ali ne zaboravi to.
{61056}{61131}Ovdje ja dajem | lekcije iz roötiljanja.
{61133}{61179}Oh!
{61181}{61243}Ti nabavi meso, | a ja Êu kuhati.
{61447}{61505}Svia mi se öto ti se sviam.
{61507}{61573}Nedostaje mi | to öto smo imali.
{61575}{61649}äto smo imali? | A öto smo imali?
{61682}{61729}Maurice?
{61771}{61818}Mogu li te opet poljubiti?
{61845}{61902}Ne.
{62208}{62244}Reci mi.
{62246}{62307}Ovaj...
{62369}{62407}äto?
{62460}{62506}äto je dolje?
{62508}{62566}éeliö vidjeti? | - Ne, ne, ne.
{62568}{62619}Samo mi reci. Ali Ëekaj.
{62621}{62667}Nemoj reÊi niöta Ëudno.
{62669}{62720}Nije niöta Ëudno.
{62722}{62814}Od jedne stvari | naËinili su drugu.
{62816}{62896}Moju izboËinu | pretvorili su u rupicu.
{62898}{62961}Poput pupka.
{63011}{63057}Bolje je. | - Dobro.
{63059}{63127}Dobro, to shvaÊam.
{63129}{63183}Da.
{63185}{63234}I...
{63236}{63281}Zadovoljna si time?
{63283}{63343}Presretna.
{63622}{63680}Onda moûe
{63682}{63712}äto?
{63714}{63761}Poljubac.
{63815}{63942}Dobar muökarac
{63944}{64045}Danas se teöko nalazi
{64047}{64094}Aha
{64096}{64205}Trebam nekoga | koga Êu voljeti
{64209}{64309}Pogledaj boju. | Koja je to boja?
{64311}{64372}Svjetlocrvena. Kaûu | da je ruûiËasta, ali bez brige.
{64374}{64435}Ne vidim ruûiËasto. | Je li to svjetlocrveno?
{64437}{64477}Jest. | - Lijepa boja.
{64479}{64507}Nije li? | - Zovu je svjetlocrvena?
{64509}{64540}RuûiËasta, ali...
{64542}{64583}Izgleda svjetlocrveno.
{64585}{64640}Pijmo za svjetlocrvenu. | - Apsolutno.
{64642}{64686}»uj.
{64688}{64736}Treba li vam oruûje?
{64738}{64826}Automatsko oruûje, | uziji, AK-47, M-16,
{64828}{64894}bacaËi raketa, | maleni bombarderi.
{64896}{64984}Dostavljamo diljem | svijeta, bez ograniËenja.
{64986}{65066}äto ti radiö?
{65068}{65122}Prodajem.
{65124}{65219}äaliö se? | - Ne öalim se.
{65221}{65261}Sada mi ne treba.
{65263}{65320}Maury, trebamo li oruûje?
{65322}{65400}Sada ne. | Ne trebamo.
{65402}{65465}Neöto Êu vam pokazati.
{65467}{65502}Sada ne? | - Da.
{65504}{65556}Kako ûelite. Loridonna. | Loridonna. - Da.
{65558}{65622}Loridonna, Loridonna, Loridonna. | - Hvala na tome.
{65624}{65675}Loridonna. | - Hvala
{65726}{65765}On je ubojica, | a ona je muöko.
{65767}{65814}U redu je.
{65902}{65930}Dajem otkaz.
{65932}{65972}Sklopit Êemo ugovor!
{65974}{66031}Pokazat Êu vam | kako se to radi.
{66033}{66109}Zaboravi je. | - Tehnika dimljenja.
{66111}{66205}Goldbluth mi je to pokazao. | Zaklopiö i otklopiö.
{66207}{66261}Sjajno!
{66263}{66306}To je dobro. | - Super.
{66308}{66370}Kakav ugovor? | - Dvije kutije. Donesi.
{66372}{66428}To je gurmanska tehnika.
{66430}{66498}Ne svia mi se taj tip. | Ovdje niöta nije normalno.
{66500}{66586}On je pravi. | Donesi knjiûicu.
{66588}{66634}Saberi se.
{66636}{66666}Baö slatko.
{66668}{66724}Sada ti meni drûiö lekcije.
{66726}{66766}Trebat Êu neke informacije.
{66768}{66827}Znaö öto je uËinio?
{66829}{66942}Morala sam gledati obrazovni | film o prepariranju ûivotinja.
{66944}{67026}Tada me pitao koliko | mislim da bi stajalo
{67028}{67131}da oËistim i prepariram | majmuna teöka 50 kilograma.
{67133}{67227}Pitala sam: Molim? | Pa toliko ja imam kilal
{67268}{67341}Boûe! | - Da se javim?
{67524}{67549}Da?
{67551}{67595}Zdravo. | - Zdravo.
{67597}{67677}äööö.
{67679}{67756}Bez buke. | - Da nisi ni pisnula.
{67758}{67825}Idemo.
{67827}{67886}Sve je ispunjeno.
{67888}{67941}Sve izgleda sjajno.
{67943}{68006}Ako moûeö...
{68008}{68056}Ovdje.
{68058}{68108}Da.
{68170}{68204}Hopa! | - Sranje!
{68206}{68244}Nema veze. | - Ovdje?
{68246}{68300}Da. Samo jako stisni.
{68302}{68337}JaËe? | - Trebala bi pisati.
{68339}{68399}Ne piöe, ûalim. | - U redu je.
{68401}{68463}éao mi je. | Idem po ubrus.
{68783}{68848}Boûe!
{68850}{68897}Isuse! | Kvragu!
{68899}{68958}Kako si, Tony? | Zbilja si daveû.
{68960}{69006}Jebote!
{69008}{69075}Dobro. | Idi Goldbluthu.
{69077}{69132}Idi njemu? | Svi ti polomljeni dijelovi...
{69134}{69186}Tih 1500 AK-47, | on zna za to.
{69188}{69242}Idemo do njega. | - On je kriv, a ne ja.
{69244}{69300}On je iduÊi, bez brige. | - Idite njemu.
{69302}{69345}On zna za ovo sranje.
{69347}{69389}Bolje je da te ubijemo.
{69436}{69502}Boûe! Kvragu!
{69504}{69596}Spomenuo si to! | - Kakav usran dan!
{69598}{69653}Morate otiÊi njemu.
{69655}{69708}Zna sve o tome. | - IduÊi je, bez brige.
{69710}{69757}Ubit Êemo ga dok si joö topao.
{69759}{69806}Ovo je od Borisa.
{69930}{69990}ProstaËe.
{70064}{70141}Boûe! Ne!
{70143}{70182}Smirite se!
{70184}{70230}Sjednite. Ne vriötite.
{70232}{70330}Stanite! Tiho! Sjednite!
{70332}{70375}Sjednite! | - äto se dogodilo?
{70377}{70442}äto ste uËinili? | - Znaö öto se dogaa.
{70444}{70496}To je to. | - Niste to valjda uËinili?
{70498}{70551}Sve je sreeno. Gotovo je.
{70553}{70610}Boûe! | - Smirite se!
{70612}{70668}Ubojice ste! | - Profesionalci smo.
{70670}{70720}Sve je sreeno. | - Profesionalci?
{70722}{70762}äalite se? | - Molim?
{70764}{70819}Trebali ste doÊi | u 12 sati vani,
{70821}{70882}a ne u moju kuÊi, kretene! | - Samo mirno.
{70884}{70945}Smirite se! | - Nije trebalo biti ovako.
{70947}{70992}Suzy, öto si uËinila? | - Mrtav je?
{70994}{71039}Ne pravi se da ne shvaÊaö.
{71041}{71081}Ne mogu vjerovati da je mrtav.
{71083}{71118}Samo polako. | - äto ste uËinili?
{71120}{71158}Ne dramatizirajte.
{71160}{71209}Nemojte! | - Tiho!
{71211}{71242}Tiho!
{71244}{71288}Smirite se!
{71290}{71362}Tiho! | - Nemojte, molim vas!
{71364}{71402}Ne miËi se! Baci piötolj!
{71404}{71450}Koji kurac?! | - Baci piötolj!
{71452}{71490}Baci ga! | - Tko je ovaj?
{71492}{71522}Ne öalim se. | Reci mu da spusti oruûje.
{71524}{71577}Spusti ga!
{71579}{71616}Spusti ga! | - Tko si ti?!
{71618}{71650}Spusti piötolj! | - Ma nabijem te!
{71652}{71693}Ne govori mi öto | da radim. Tko si ti?
{71699}{71741}Ne miËi se. | Reci mu da spusti piötolj.
{71743}{71790}Smiri se. | - Neka ga spusti.
{71792}{71831}Reci mu. | - Ti spusti piötolj.
{71833}{71879}Smiri se. | - Ne ûelim ovo.
{71881}{71930}Moraö spustiti piötolj! | - Spusti piötolj!
{71932}{71996}ShvaÊaö li me? | - Spusti piötolj!
{71998}{72062}Smiri se. | - Brojim do dva.
{72064}{72110}Nemoj brojiti.
{72112}{72149}Jedan...
{72187}{72229}I ti.
{72231}{72286}Polako mi ga daj. - Dobro.
{72312}{72386}Tko je ovaj? | Tko si ti?
{72388}{72458}Umrijet Êete, | to vam je jasno?
{72460}{72501}Zato sada uûivajte.
{72540}{72580}ZaËepi!
{72582}{72630}Isuse!
{72632}{72681}äto si rekao,
{72683}{72725}kretene debeli?!
{72727}{72782}U redu je, Dave!
{72784}{72836}Pozovimo murjake!
{72838}{72895}Dobro. Pozovi murjake.
{72897}{72934}Dobro, svjedoËit | Êete protiv nas.
{72936}{72986}Ostatak ûivota | provest Êete u rupi.
{72988}{73067}Samo dajte. | Pozovite policiju.
{73236}{73278}Neöto dobro miriöi.
{73280}{73354}OsjeÊaö li to? | - äto je to?
{73356}{73448}Ne znam, | ali umirem od gladi.
{73450}{73514}Neka govedina. | - Telefon ne radi.
{73516}{73553}Sjedni.
{73605}{73658}Maury, doi! | - äto je?
{73660}{73730}Doi ovamo. | - äto je?
{73776}{73826}Ovdje sam.
{73852}{73898}Vidim rupu.
{73900}{73953}Jesi li ti lud? | - Vidio si.
{73955}{74001}Vidio sam da si vidio. | - Ne ûelim umrijeti.
{74003}{74052}Imaö neöto drugo? | Ja nemam.
{74054}{74104}Hajde.
{74318}{74358}Volite meso?
{74551}{74614}Molim? Misliö, jesti?
{74661}{74713}Mislim, najbolje | meso koje moûete kupiti.
{74743}{74793}Meso za prave gurmane.
{74795}{74856}Ovako bih ja.
{74858}{74929}Mislim da ste vi dobri,
{74931}{74978}obiËni ljudi.
{75026}{75080}Koji moraju obaviti posao. | - Koji moraju obaviti posao.
{75113}{75162}Nemamo baö niöta protiv vas.
{75164}{75227}Iskreno, divimo se vaöoj...
{75229}{75307}Vaöoj... | - Profesionalnosti.
{75355}{75426}Ubili su Tonyja. Pa?
{75428}{75502}Bio je kreten. | Poznavao sam ga 20 minuta,
{75504}{75548}a veÊ me poËeo ûivcirati.
{75550}{75614}Vrlo je drzak. | Da sam imao metaka,
{75616}{75654}i ja bih ga ubio.
{75656}{75734}Dugujemo vam | svoju zahvalnost.
{75736}{75794}Itekako. | Hvala obojici.
{75796}{75843}Nema na Ëemu.
{75876}{75919}Cijenimo to.
{75958}{76037}Dobro. Onda, | kako Êemo ovo?
{76174}{76209}Ne znam.
{76250}{76298}Mogli bismo... | - Ne, molim te.
{76300}{76350}ZaËepi gubicu, | molim te. - Isuse!
{76352}{76419}Samo budi tiho.
{76476}{76534}Imate li vi
{76536}{76583}razloga ubiti nas?
{76644}{76726}Imamo li razloga... | Ne, nemamo.
{76728}{76790}Nemamo vas | razloga ubiti.
{76792}{76835}To je lijepo.
{76837}{76934}»ini se da nam je | onda neöto zajedniËko.
{76936}{76977}Tako je.
{77028}{77068}Ja sam Maurice.
{77070}{77118}Ja sam Bobby.
{77120}{77188}Bobby? Dobro.
{77190}{77246}Bobby, ovo je Dave. | - Drago mi je.
{77248}{77301}I meni. | - Dave...
{77303}{77398}Nisam... | - Irv. Irving.
{77400}{77428}Irving. | - Da.
{77430}{77462}Nevjerojatno!
{77464}{77494}Otac mu se zvao Irving.
{77496}{77560}Sereö! | - Nedavno je umro.
{77562}{77634}Nedostaje mi. Hvala öto | mu ime odrûavate na ûivotu.
{77636}{77694}U redu je. | - A moja ûena,
{77696}{77773}bivöa ûena, | ûivi u Irvingovu bulevaru.
{77775}{77821}Svijet je baö mali.
{77823}{77889}Sve je povezano. | - Svi smo...
{77891}{77934}Nekako smo povezani.
{78107}{78154}Poötujem te, Bobby.
{78232}{78282}Rado bih...
{78284}{78339}Rado bih ti vratio piötolj.
{78375}{78430}Maurice, | i ja bih to volio.
{78432}{78483}Bih.
{78520}{78568}HoÊeö li prisegnuti
{78570}{78644}kao muökarac, | da moûemo zajedno sjesti
{78646}{78702}i zajedno jesti | kao prijatelji?
{78704}{78758}Pokazat Êemo vam | kako se kraljevski jede,
{78760}{78815}a onda svatko | na svoju stranu.
{78847}{78916}Mogli bismo to.
{78918}{79014}Ne vidim zaöto... | - Je li to obeÊanje?
{79016}{79058}Naravno. | - Jest.
{79060}{79132}»asna rijeË?
{79134}{79178}»ast je vaûna.
{79180}{79232}Sinatra je rekao | da je Ëast sve.
{79234}{79294}»ovjek je vrijedan | koliko je Ëastan.
{79296}{79374}Kada se sustav Ëasti | dobro primjenjuje,
{79376}{79432}to je dobar sustav.
{79434}{79493}Onda...
{79495}{79559}UËinimo to | tako, Ëasno.
{79886}{79920}Hvala na ovome.
{79922}{79966}Dobar si profiÊ. | - Cijenim to.
{80029}{80095}Oprosti öto sam | ti rekao da si debeo.
{80097}{80147}Ali sada | proûivljavam mnoga sranja.
{80149}{80207}Ma nema veze.
{80372}{80411}éelite li jesti?
{80413}{80469}Moûemo li jesti?
{80471}{80520}Stiûe.
{80522}{80572}PriËekajte trenutak.
{80574}{80623}äutite na trenutak.
{80625}{80704}Je li gotovo? - Jest.
{80706}{80767}Suzy je dobro? | - Dobro je.
{80769}{80830}Daj mi je. | - Zanima ga jesi li dobro.
{80832}{80911}Duöo, dobro sam.
{80913}{80948}Rekao sam | ti da Êe biti lako.
{80950}{81017}UËini ono | öto ti oni kaûu.
{81019}{81070}Ako ti se öto | dogodi, neÊe dobiti plaÊu.
{81072}{81158}Vidimo se poslije. | - Dobro.
{81196}{81229}Reci mu kako ste zasrali.
{81231}{81264}Reci mu za Mauryja i doktora.
{81266}{81301}äuti! | - ZaËepi!
{81303}{81345}Sereö?
{81347}{81399}Sve je u redu. | - Tko su Maury i doktor?
{81401}{81498}Tipovi koji su se | pojavili, ali sve je u redu.
{81500}{81562}Rijeöi ih se. | - Sada ne mogu, Borise.
{81564}{81619}Zaöto? | - ObeÊao sam im.
{81621}{81658}Jebe mi se za tvoja obeÊanja!
{81660}{81724}Ne ûelim niöta | nedovröeno. Jasno?
{81726}{81784}Sve je pod kontrolom.
{81786}{81852}Trebam te ovdje. | - Dobro.
{81854}{81902}Goldbluth ima tulum za dijete.
{81904}{81959}Sada je laka meta.
{81961}{82007}Kasno je. Sredite se.
{82009}{82065}Doite ovamo. | - Kako da se sredimo?
{82067}{82135}Stavite kravatu. To je tulum.
{82237}{82333}To je bio moj... Boris. | Kaûe da ih moramo ubiti.
{82335}{82376}Nemoj! - Moramo!
{82378}{82413}- Boûe! - Hajde!
{82415}{82457}Dogovorili smo se! | - Sve smo to proöli!
{82459}{82504}Tiöina! | - Molim te.
{82506}{82553}ObeÊali smo. | - NeÊemo to sada.
{82555}{82594}Platit Êe, nagodit Êemo se.
{82596}{82649}Dogovorili smo | se. - Nismo, dobro?
{82651}{82690}éivot mi je bolji svaki put | kada prekröim dogovor.
{82692}{82764}Sjedni i öuti!
{82766}{82819}BrbljavËe!
{83116}{83159}OtiÊi Êemo | i viöe nas neÊete vidjeti.
{83161}{83210}Ako nas odmah pustite.
{83212}{83266}Moûe. | - äutjet Êemo.
{83268}{83314}Dobro. Kako ti se zove mama?
{83316}{83385}Ovo je koma. | - Suzanne, idi k Loridonni.
{83387}{83454}Idem. | - Ti i Tony ste se posvaali.
{83456}{83518}Aha, kao alibi! | - Tako je.
{83520}{83562}Jedan: Ti i Tony | ste se posvaali.
{83564}{83609}Dva: Cijeli | si dan bila kod nje.
{83611}{83673}Tri: Ne znaö gdje | je Tony. Jedan, dva, tri.
{83675}{83736}Cipelu mi veûi
{83738}{83785}Isuse!
{83922}{83970}Suzy, gdje je Tony?
{83972}{84042}Ne znam.
{84775}{84824}äto Êeö s njima?
{84826}{84884}Bez brige. | Ne idu nikamo.
{84948}{85018}Misliö da su otiöli? | - Niöta ne Ëujem.
{85020}{85066}Pokuöajmo.
{85068}{85124}Guraj, guraj!
{85126}{85173}Ne mogu jaËe!
{85247}{85312}Nabit Êu to!
{85314}{85348}Jesi!
{85350}{85389}Probio si!
{85391}{85447}Gurni me.
{85449}{85503}Izaöao sam.
{85556}{85620}Daj ruku. | IzvuÊi Êu te.
{85622}{85708}Jedan, dva...
{85710}{85758}Ovo nije moguÊe!
{85760}{85824}Idem okolo. | - Dobro. Jebiga!
{85932}{85987}Zapeo sam u oba smjera.
{85989}{86035}Idem okolo.
{86037}{86095}Smiri se.
{86220}{86285}Izvuci me. | - Dobro. Samo öuti.
{86287}{86372}Maury, ne svia mi se ovo. | - Znam, znam.
{86488}{86548}äto radiö?
{86592}{86631}Dobro.
{86633}{86691}Malo sam povratio. | - Idem okolo.
{86725}{86774}Maury, ne moûeö | me ostaviti ovdje!
{86800}{86841}Sranje! Potraûit Êu neöto!
{86843}{86878}Maury! | - Odmah se vraÊam!
{86880}{86925}Prvo me izvuci! | - Odmah se vraÊam.
{86927}{86977}Maury, ne ostavljaj me!
{86979}{87030}OsjeÊam se usamljeno, | Maury! Jesam li?!
{87032}{87083}Vadi me van!
{87171}{87217}Gotovo je!
{88117}{88174}G. Goldbluth, | ovo je doista
{88176}{88241}divna proslava | s mnogo hrane,
{88243}{88330}a to je, kao uvijek, | fantastiËno iskustvo.
{88332}{88427}Danas Jerry postaje muökarac.
{88502}{88568}Hvala, | Cookie Goldbluth.
{88570}{88622}Hvala na velikoduönosti
{88624}{88712}gostoprimstvu | i dobrom ukusu.
{89118}{89186}To si rekao | toËno kako sam ti rekao.
{89274}{89342}Pa...
{89344}{89382}Zahvalimo Bogu
{89384}{89451}koji nas je danas okupio
{89453}{89522}jer je djeËak u Njegovim | oËima postao muökarac,
{89524}{89622}a sin je postao muökarac | u oËima svoga oca.
{89624}{89686}Kaûu da djeËak | postaje muökarac
{89688}{89741}onda kada muökarac zatreba.
{89743}{89826}Ali kada to zbilja postaje?
{89828}{89894}Jutros, za vrijeme ceremonije,
{89896}{89946}Jerry je Ëitao o ljudima
{89948}{90012}koji su bjeûali od moÊne vojske
{90014}{90070}i bili suoËeni | s penjanjem
{90072}{90130}na golemu planinu.
{90132}{90210}Bog je progovorio i rekao im:
{90212}{90263}Sklopite pakt sa mnom
{90265}{90334}kako biste se | popeli na pola puta.
{90336}{90434}Kada su preûivjeli | doöli dokle su mogli,
{90436}{90489}Boûja ruka
{90491}{90550}spustila se s nebesa
{90552}{90589}i podigla ih na vrh.
{90916}{90965}Vidio sam ga, Dave. | Bio je vrlo lijep.
{91008}{91094}Da? Koga? | - Goldblutha.
{91096}{91146}Naöega savröenoga | potencijalnoga klijenta.
{91148}{91222}Ma daj odjebi!
{91224}{91282}Nismo li se za | danas dovoljno zabavljali?
{91284}{91340}éele nas ubiti. | - I njega.
{91342}{91406}éele ubiti Goldblutha. | Hajdemo.
{91408}{91489}Maury, stani. | Unutra su ti luaci.
{91491}{91557}éele nas ubiti. | Budi sretan öto si ûiv.
{91559}{91634}Neöto nas je dovelo | ovamo, ka Goldbluthu.
{91636}{91683}OËito je. | Ovo danas nije bilo sluËajno.
{91685}{91735}Sve nas je vodilo ovamo.
{91737}{91810}Ta ideja | o savröenom klijentu
{91812}{91893}naöa je fantazija. | Izmislili smo to.
{91895}{91950}Jesmo, ali sada | znam o Ëemu smo govorili.
{91952}{92003}Kao da smo rekli: | Ako gore ima nekoga
{92005}{92086}onda bi nam trebao | stvoriti ovakvoga tipa. I jest.
{92088}{92165}Ljudi stalno govore | da su vidjeli Boga.
{92167}{92244}Kao da sam vidio Boga. Ali | velika je razlika izmeu toga
{92246}{92293}i kada Ga zbilja vidiö.
{92324}{92370}äto si vidio?
{92372}{92427}Rekao sam ti.
{92892}{92939}Hajdemo.
{93410}{93470}Zbilja je lijep.
{93503}{93565}Gledaj.
{93567}{93597}Leon?!
{93599}{93658}Kojeg vraga on radi ovdje?
{93660}{93731}I on je doveden ovamo.
{93911}{93973}Doi! Hajdemo okolo.
{94018}{94067}Bobby, iz koje je godine Caddy? | - Ne razumijem se u aute.
{94069}{94106}Od kada je, Irv? | - Iz '89.
{94108}{94142}'89? Nadam se | da je velik. - Jest.
{94144}{94178}'89 | - Koke vole aute.
{94180}{94215}To je lijep auto.
{94217}{94281}Ne radim besplatno, Borise.
{94283}{94334}Ovo mi nije | hobi. ShvaÊaö?
{94336}{94393}Ako ûeliö da ljudi o tebi | svaöta govore, dobro.
{94395}{94442}Ako ne, daj ponudu.
{94444}{94476}Za novac.
{94478}{94534}Obojicu kretena | koknut Êemo za...
{94536}{94566}10 po glavi.
{94568}{94596}Smiri se | i detalje prepusti meni.
{94598}{94641}Dobro. | - Dvojicu za cijenu jednoga.
{94643}{94681}OdluËit Êu koliko vrijede.
{94683}{94726}Dobro.
{94828}{94869}äto si uËinio? | - Niöta!
{94871}{94918}Trebao si ih vezati. | - Ovo nije u redu.
{94920}{94963}Vidio si da ih | veûem. - Rekao sam vam.
{94965}{95026}Ne ûelim nered! | Naite te kretene!
{95028}{95069}I vratite se po Goldblutha.
{95071}{95117}Za öankom sam.
{95164}{95209}Svaki put kad je neki zajeb
{95211}{95258}ja sam kriv!
{95302}{95350}Moramo brzo govoriti. | Biti ûestoki.
{95352}{95401}Brz sam. | éestok sam.
{95567}{95602}Zdravo, kako ste?
{95604}{95636}Leone!
{95638}{95672}Zdravo.
{95674}{95707}DeËki.
{95709}{95795}Pogledajte. SjeÊate | li se tko je to?
{95797}{95846}Tvoja krasna cura Karen.
{95848}{95894}Nekada je bila.
{95896}{95970}Sada je moja | krasna zaruËnica Karen.
{95972}{96032}Bravo! | - »estitam!
{96034}{96069}IduÊi ples, duöo.
{96071}{96108}Prijatelj si Goldbluthovih?
{96110}{96165}Jerryjev sam | uËitelj klavira. Vi?
{96167}{96233}Imamo zajedniËkog | prijatelja koji ûeli
{96235}{96273}da g. Goldbluthu | kaûemo za svoju ponudu.
{96275}{96349}S Goldbluthom morate | razgovarati o kvalitetnoj hrani.
{96351}{96398}Upoznat Êu vas.
{96506}{96581}Ti tipovi | prodaju meso?
{96583}{96610}Da.
{96612}{96651}Pokucaju na vrata i kaûu:
{96653}{96722}éelite li kupiti | jebeni cheeseburger?
{96724}{96774}Od toga ûive? | To je ûivot?
{96832}{96882}G. Goldbluth. | - Da, gospodine?
{96884}{96969}éelim vam | predstaviti ovu gospodu.
{96971}{97025}Dave i... | - Maury.
{97027}{97054}Morty. Dave i Morty. | - Zdravo.
{97056}{97084}Ovo je g. Goldbluth. | - Kako ste?
{97086}{97122}Krasna zabava. | - Vrlo dobro.
{97124}{97185}Tony je rekao | da cijenite dobar ukus.
{97187}{97241}PreporuËio vas je. | - Gdje je Tony?
{97243}{97293}Sigurno Êe doÊi. | Lijepo govori o vama.
{97295}{97346}Kaûe da je o roötilju | sve nauËio od vas.
{97348}{97438}Ma kojeg vraga | on zna? Vidimo se.
{97476}{97528}Zbilja. Kaûe | da ste Ëarobnjak.
{97530}{97586}Klijente snabdijevamo | najboljom govedinom na svijetu.
{97588}{97628}Mislimo da | zasluûujete najbolje.
{97630}{97687}Je li? | - Da.
{97689}{97722}G. Goldbluth? | - Da.
{97724}{97846}VeÊ dobivam najbolje. | Stiûe mi iz Omahe.
{97848}{97899}Ali dobra vam zabava.
{97978}{98009}PrvaËe!
{98139}{98187}Hej
{98189}{98222}Oh!
{98224}{98287}Oh, da
{98289}{98335}Da
{98337}{98384}Dame i gospodo.
{98510}{98562}Gospodo.
{98615}{98686}Doölo je vrijeme
{98688}{98786}Ugasi svjetlo
{98788}{98852}Gotovo da ste vrönjaci.
{98854}{98895}Cindy, moj sin Jerry.
{98897}{98935}Zdravo, Jerry. | Drago mi je.
{98937}{98980}äto je ovo?
{99014}{99097}IspriËavam se. | Tata, doi.
{99099}{99152}Misliö da sam spreman?
{99154}{99222}äaliö se? | Svidjet Êe ti se.
{99224}{99283}Isuse! | - Kada sam bio tvojih godina
{99285}{99350}dao bih desnu | ruku za ovakvo öto.
{99352}{99428}Ja sam prvi put s 10 g. | Ti si veÊ i prestar za prvi put.
{99430}{99474}NeÊe te ugristi.
{99476}{99517}Ostani uz njega, | a ja idem sprijeda.
{99519}{99564}Ubit Êe ga kada se vrate.
{99566}{99628}Odmah moramo | sklopiti ugovor. Uvedi ga.
{99808}{99866}Harolde, öto se dogaa?
{99868}{99906}Gdje je Jerry? | - U autu.
{99908}{99982}U au... | - Faye, Faye, doi.
{99984}{100048}äto ti je? | Cura dolazi na zabave.
{100050}{100098}Diplome, roendane.
{100100}{100139}Harry!
{100398}{100446}Da bar imam kameru.
{100448}{100486}Ovo bi mogao | biti poster za sreÊu.
{100488}{100541}Onakav kakve prodaju.
{100543}{100614}Hvala. | »ujeö? To je oËito.
{100616}{100657}Rijeöit Êu se te cure.
{100659}{100750}Pustite da mu ga | bar izdrka. Jedanput.
{100752}{100848}Jedanput | - Eto. Vidiö?
{100850}{100925}Idem po piÊe.
{100927}{100967}Tko je taj?
{101013}{101110}Razmirice odrûavaju | vezu, ha g. Goldbluth?
{101112}{101161}Zovi me Cookie.
{101163}{101209}Da vas pitam. | Kada roötiljate,
{101211}{101283}volite li da je odrezak | debeo 2,5 ili 3,5 cm?
{101285}{101342}äaliö se? | 5 cm.
{101344}{101402}Ti su tipovi odavno pobjegli.
{101404}{101440}Dosta mi je.
{101442}{101517}éelim srediti | Goldblutha i otiÊi spavati.
{101624}{101658}Govorim o najboljemu mesu.
{101659}{101774}Hibridu Kobe-Angus, | superiornim ûivotinjama.
{101776}{101814}Najboljim? | - Na Zemlji.
{101816}{101870}Valjda i na Marsu. | Ondje nisam jeo.
{101872}{101928}Maury!
{101930}{102010}Bolje je od svega u krugu od 4,5 | milijuna km od Sherman Oaks.
{102012}{102063}To je meso s pet zvjezdica.
{102065}{102128}Idi po knjigu. | - Kakvu knjigu?
{102179}{102238}MjeseËni iznos ukljuËuje | sve. Filee, T-bone odrezak,
{102240}{102309}njujoröki odrezak, | londonski i divna rebrica.
{102311}{102357}I to po mnogo povoljnijoj cijeni
{102359}{102400}od one koju plaÊate | za dostavu iz Omahe.
{102402}{102465}Molim? | - Da vam pokaûem.
{102467}{102513}Ne ûelim upirati prstom,
{102515}{102560}ali ova krava imala je problema.
{102562}{102606}Najvjerojatnije.
{102608}{102678}Kaûete da je meso loöe? | To je najbolja govedina.
{102680}{102731}Tako je zovu.
{102733}{102802}To stalno viamo. | Nitko ne misli na kvalitetu.
{102804}{102847}G. Goldbluth,
{102849}{102912}odvest Êemo vas | na vrh goveeg svijeta.
{102914}{102981}Najviöeg vrhunca gurmanstva.
{102983}{103059}To je meso tako mekano | da ga ne morate ni ûvakati.
{103061}{103148}To se meso | topi u ustima.
{103150}{103204}Da.
{103206}{103252}»ujete?
{103254}{103330}Ne morate ga ni ûvakati.
{103364}{103414}To mi se svia.
{103504}{103548}Bilo je puno takva mesa.
{103550}{103607}Izgledalo je kao dar.
{103609}{103664}Bio bi to dobar dar za obitelj.
{103666}{103711}To je krasno.
{103713}{103758}Znate öto?
{103760}{103838}NeobiËno me | privlaËi maglovito ûuta.
{103840}{103892}To nije nimalo Ëudno.
{104188}{104248}Otvori vrata!
{104250}{104294}Druga vrata | - Opet, kretene!
{104296}{104329}Jebi se. NeÊu opet.
{104331}{104363}Hajdemo ovuda.
{104533}{104590}Sedam zamrzivaËa, | sedam ujaka.
{104592}{104644}Znate öto? | Trebat Êe mi
{104646}{104691}vaöi financijski | podaci, niöta straöno.
{104693}{104766}Borise. | - Niöta, ha?
{104768}{104815}Koliko je sranje? | - Joö je malo sranje,
{104817}{104861}ali sve je pod kontrolom. | Otjerali smo ih unutra.
{104863}{104905}Kriju se u kuhinji.
{104907}{104958}To je dobro. | I Goldblutha odvedite onamo
{104960}{105002}jer ovo Êe | biti oproötajni paket.
{105004}{105043}Ubit Êemo ga s njima.
{105045}{105101}Dva crvena, dva plava i...
{105103}{105163}Morat Êete se | potpisati ovdje,
{105165}{105206}ovdje, ovdje i ovdje.
{105208}{105250}Na mnogo mjesta.
{105252}{105289}Uzmite.
{105408}{105453}To je najbolje?
{105455}{105504}Sve je stvar osobna ukusa.
{105506}{105576}Davey! | - Samo je jedno najbolje.
{105578}{105666}Zato ne volim | tu rijeË najbolje.
{105668}{105708}äto je najbolje?
{105710}{105775}Najbolje za | mene ili za vas?
{105815}{105868}Lagali ste.
{105870}{105917}Zakleli ste se Sinatrom.
{106123}{106204}Hajde! Drûi ga!
{106206}{106253}Pazi!
{106304}{106356}Hajde! Idi!
{106358}{106403}Kvragu!
{106405}{106467}Razvali vrata!
{106524}{106556}Stvar je ukusa.
{106558}{106602}Vaûno je prodati.
{106604}{106666}Treba znati öto | i od koga treba kupovati.
{106668}{106750}Moûda ste vi | obiËni muljatori
{106752}{106830}koji su se | namjerili na pogreönoga.
{106996}{107054}Ali izgledate mi u redu.
{107056}{107172}Da
{107208}{107282}Da
{107284}{107346}G. Goldbluth.
{107348}{107411}Ovdje su ljudi | koji vas ûele ubiti.
{107459}{107505}Tony s razlogom nije ovdje.
{107507}{107559}Govori brzo.
{107625}{107659}Bjeûite odavde.
{107661}{107710}Bjeûimo. | - Hajdemo, g. Goldbluth.
{107712}{107750}Idemo, brûe!
{107752}{107779}Ralphe. | - Da, öefe.
{107781}{107813}21 tisuÊa. | - Moûe.
{107874}{107926}U redu, deËki.
{107928}{107982}Za vaöe darove.
{108066}{108134}G. Goldbluth,
{108136}{108190}bio je Tonyjev.
{108293}{108364}IduÊih deset dana | oËekujem zamrzivaËe.
{108366}{108435}Stiûu.
{108954}{108981}Tata!
{108983}{109035}OËistite ovo kao | da se niöta nije dogodilo.
{109037}{109061}Niöta se nije dogodilo.
{109063}{109100}Tata!
{109102}{109163}Jesi li dobro?
{109165}{109260}Uvijek sam dobro. | Samo smo slavili.
{109528}{109562}Dick.
{109564}{109604}Izgledaö umorno, | Dick. Kako si?
{109606}{109708}Isuse, oËekivao sam | razglednicu iz Ensenade.
{109710}{109747}Jeste li öto? | - Jesmo li öto?
{109749}{109792}Ne znam. Da vidimo.
{109794}{109850}Broji li se ovo?
{109852}{109889}Pitajmo Dicka öto misli.
{109891}{109922}Tri, öto kaûeö na to?
{109924}{110006}Prije nego öto odgovoriö, | öto kaûeö na Ëetiri?
{110008}{110069}Naravno, pet je | broj koji sve zadovoljava.
{110071}{110124}Valjda zbog dlana i prstiju.
{110126}{110156}Sklopili ste pet ugovora?
{110158}{110204}Nismo.
{110206}{110239}äest.
{110241}{110290}Kad bih rekao öest, lagao bih.
{110292}{110342}Jer bi zaboravio sedmi.
{110344}{110393}Koji je ovo vrag?
{110395}{110464}Sklopili smo sedam ugovora.
{110466}{110532}Da namjestim sedam kutija?
{110534}{110622}U ove stavi dobre | stvari jer ovo je zlatno.
{110624}{110687}Dobili smo keö. 21 tisuÊa.
{110689}{110740}Minus naöa provizija.
{111220}{111420}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan  
{111423}{111509}Evo ga, | duöo. SkoËi.
{111511}{111557}Vidi öto mi je tata kupio!
{111559}{111630}Tako je, duöo. | - Hajde. Spremna?
{111632}{111697}Jesam. | - Idemo visoko.
{111699}{111742}Nije li lijepa?
{111744}{111779}Maury, nemoj mi spaliti piletinu.
{111781}{111838}Spalit Êeö piletinu, idiote!
{111865}{111919}Ovako Êemo.
{111944}{113444}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/42dvt|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
