{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1407}{1470}Upitnik nekretnina Real Estate Query Engine
{1472}{1552}je pravo vrelo informacija,
{1554}{1610}koji stavlja odvjetnika na Ëelo.
{1612}{1714}Sluöaj, ja idem.|Pokuöat Êu se vratiti onim u dva.
{1717}{1772}Sada napuötaö seminar?|Nije joö ni pauza.
{1774}{1859}Mislim da se to ne smije.|Ne, u redu je. Samo me nemoj odati.
{1861}{1915}Sve snimi.|Valjda hoÊu.
{1917}{1982}Daö mi svoju ploËicu?|Da.
{1983}{2055}Vrijedi dva besplatna piÊa u kafiÊu.
{2417}{2443}Zdravo.
{2445}{2521}U zraËnu luku.|éuri mi se.
{2559}{2603}»ini se da je vaö pojas puknuo.
{2605}{2648}äto mi preporuËate da uËinim?
{2662}{2734}PreporuËam da prestaneö biti|takav peder.
{2745}{2794}Na straûnjem si sjedalu.
{2803}{2838}Isuse.
{2903}{2935}Vidiö?
{3000}{3500}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
{5011}{5040}Ima li koga?
{5151}{5193}Bok, deËko.
{5195}{5261}Dobar si, Orsone.|Gdje je mamica?
{5318}{5350}Duöo?
{5405}{5437}Heidi?
{5722}{5747}Heidi?
{6077}{6100}Mitch!
{6131}{6220}äto radiö kod kuÊe?|Prestraöio si me!
{6223}{6307}Ja sam tebe prestraöio?|Nakratko sam pomislio...
{6333}{6371}Ne ûelim to ni reÊi.
{6500}{6571}To je porniÊ.
{6573}{6615}Da, znam.
{6617}{6700}Ne, ne osuujem.|Neka ti ne bude neugodno.
{6702}{6775}Ovo je velika promjena.|Prepustimo se.
{6778}{6835}Ovo radiö kad me nema?|Mitch, Ëekaj.
{6837}{6931}Ne, i ja to katkad radim,|ali s Ëasopisima.
{6931}{6978}Mitch, moramo razgovarati.
{6979}{7016}Zdravo!
{7127}{7162}Budi iskrena.
{7163}{7237}Molim te, reci da je ovo prvi puta.
{7261}{7358}éeliö li da budem iskrena,|ili ûeliö Ëuti da je ovo prvi puta?
{7360}{7455}Isuse, öto je tebi?|Niöta mi nije!
{7456}{7503}Pokuöavala sam ti reÊi za ovo.
{7505}{7551}äto? Kada?
{7573}{7630}Cijelo vrijeme!|Kada na primjer?
{7654}{7730}Kad smo u krevetu.|U krevetu?
{7759}{7816}Mislio sam da samo prostaËiö.
{7819}{7894}I jesam, ali sam mislila ozbiljno.
{7981}{8045}Rekla si neke stvarno bolesne stvari.
{8047}{8078}Moraö priznati,
{8079}{8166}nismo baö vodili najuzbudljiviji ûivot.
{8167}{8250}Za mene je ovo potpuno drugaËije|zadovoljstvo.
{8251}{8290}To je samo seks.
{8391}{8437}Stvarno mi je ûao.
{8720}{8740}Zdravo.
{8754}{8770}Da?
{8787}{8827}Doöao sam na grupnjak.
{8965}{9026}Malo si blijed, Mitch.|Moraö disati.
{9027}{9080}Pusti malo krvi u lice.
{9082}{9154}Ne ûelim disati.|Trebao bi se ponositi sobom.
{9156}{9246}Znaö kako je teöko naÊi taku spolno|osvijeötenu curu kao öto je Heidi?
{9247}{9314}Takva cura se nae jednom|u sto godina.
{9316}{9370}Nisam traûio takvu curu.
{9372}{9448}Kolumbo nije traûio Ameriku,|ali svima je odgovaralo.
{9467}{9518}Ovdje si.|Znaö öto hoÊu reÊi?
{9519}{9603}Samo vam joö jednom ûelim|zahvaliti öto ste ovdje.
{9605}{9645}Ovo mi je najbolji dan.
{9647}{9733}Nemoj ni poËeti, Frankline.|Moraö öto prije otiÊi.
{9735}{9798}äto?|Moraö izaÊi, Frankie.
{9965}{10049}To je to. Sad ili nikad.|Moraö otiÊi dok si joö sam.
{10051}{10147}Nisam sam.|Petnaest metara je od tebe, sad si joö sam.
{10149}{10242}Ma daj, Marissa je neöto najbolje|öto mi se ikad dogodilo.
{10243}{10303}PriËekaj öest mjeseci.|Misliö da se to neÊe promijeniti?
{10304}{10353}Imam ûenu, djecu.
{10355}{10423}Izgledam li sretno, Frankie?
{10435}{10495}Tamo mi je ûena. Vidiö?
{10497}{10568}Uvijek se smije? Bok, draga.|Osuuje, promatra, "Pogledaj dijete."
{10570}{10634}Prilazi nam, Beanie.|Dosta.
{10697}{10774}Onda mi dopusti da ti prvi Ëestitam.
{10775}{10866}Dobio si jednu vaginu do kraja ûivota.|Vrlo pametno. Tako treba.
{10867}{10950}Ne sluöaj ga.|Trebam svoj inhalator.
{10991}{11066}Hrabri ste öto predajte anela.|Dragi ste.
{11068}{11117}Prelijepa si.
{11119}{11150}Super.
{11231}{11262}Dragi moji,
{11264}{11315}sakupili smo se ovdje
{11317}{11379}kako bi spojili Franklina i Marissu...
{11381}{11414}Ne Ëini to!
{11518}{11556}Grlo mi je suho.|Oprostite.
{11571}{11602}Puöim.
{11617}{11648}Dobro.
{12914}{12936}Mitch Martin?
{12954}{12982}Da.
{13082}{13112}Nicole!
{13134}{13180}Boûe!
{13182}{13236}Ovo je ludo!
{13238}{13293}Ne mogu vjerovati da si to ti!
{13352}{13378}Boûe.
{13403}{13469}äto radiö ovdje?|Dobila sam pozivnicu.
{13503}{13631}Zadnje öto sam Ëuo je|da si se odselila...
{13633}{13676}Kako se ono zove?|Denver.
{13691}{13738}Drûava sunca.
{13739}{13770}Denver!
{13771}{13829}Predivno! Predivno!
{13951}{13990}Jesi li dobro?
{13991}{14025}Ne, ja...
{14027}{14088}Da, osjeÊam se malo...
{14122}{14152}sjebano.
{14163}{14246}Marissa mi je priËala o tvojoj curi.|éao mi je.
{14310}{14400}Kod ove se ne radi samo o tome.
{14413}{14481}Radi se o mnogo stvari.
{14483}{14549}Imali smo psa, divnu kuÊu,,
{14551}{14621}ali jednostavno...
{14649}{14723}Znaö öto?|Mislim da ti treba malo ovoga.
{14726}{14786}äto je to?|Kava.
{14889}{14968}Isuse!
{14981}{15058}Tako mi je ûao! Molim te, samo...|Ne, ne diraj!
{15059}{15119}Mogu to popraviti. Samo...|Mitch, stvarno.
{15122}{15209}Ne, Mitch!|äto radiö toj jadnoj djevojci?
{15211}{15267}Mitch, prestani!|Ja Êu.
{15269}{15330}Ne. Nepristojno je.|Odmah prestani.
{15331}{15381}Duöo, ovdje je kupaonica.|Hvala.
{15382}{15438}Mitch, dragi? Dragi?
{15441}{15488}Izai na zrak?|Ishodaj to.
{15489}{15535}Ne, Ëekaj malo.
{15537}{15572}Da?
{15574}{15646}Reci koju dobro rijeË za mene.|Da, dobro.
{16035}{16090}Hej, Marissa!
{16091}{16136}Ti si dama.
{16456}{16496}Ne Ëujem te!
{16524}{16548}Oprostite.
{16550}{16646}Stvarno mi je drago i sretan sam|öto sam veËeras ovdje.
{16683}{16778}Drago mi je öto je Frankov tata uspio.|Nisam ga vidio osam godina.
{16780}{16824}OdliËno.|»estitam.
{16826}{16874}Volim te, tata!
{16876}{16940}Teöko je naÊi pravu ljubav.
{16942}{16992}Katkad misliö da imaö pravu ljubav,
{16994}{17074}i tada se ranije vratiö|iz San Diega,
{17076}{17154}i nekoliko golih iskoËe zavezanih|oËiju iz tvoje kupaonice
{17155}{17254}kao u nekoj maioniËarskoj predstavi,|spremni da oboje tvoju curu...
{17255}{17346}Zavröava tamo, i nastavlja se ovdje
{17347}{17428}jer mislim da Mitch pokuöava reÊi|da je prava ljubav slijepa.
{17474}{17530}Podignimo Ëaöe,|ötogod da je pred nama.
{17532}{17580}éivjeli. Zdravlja i sreÊe.
{17595}{17626}éivjeli.
{17653}{17711}Toliko te volim, Frankie.|Volim te.
{17713}{17758}Ne znam drûati govore.
{17759}{17814}Volim te.|»estitam.
{18315}{18400}Mislio sam da si rekao blizu doma.|Ovo je praktiËno u domu. Uûas.
{18402}{18454}OdliËno je.|Kako si to naöao?
{18456}{18502}Ne znam, bilo je priliËno lako.
{18503}{18590}Jedan profesor je ovdje ûivio oko 30 godina|i onda je umro.
{18593}{18625}Ludnica!
{18670}{18708}Ludnica!
{18710}{18764}Mala dobrodoölica.
{18766}{18812}Za nove poËetke.
{18847}{18873}Hvala.
{18933}{19004}Ja sam to tebi poklonio za vjenËanje.
{19041}{19084}Ovaj model?
{19086}{19142}Ne, baö ovaj.
{19176}{19209}Oprosti.
{19211}{19257}Neugodno mi je.|Oprosti.
{19259}{19288}U redu je.
{19290}{19331}Nadam se da ti se svia.
{19347}{19405}Predivno je.|Hvala.
{19407}{19454}Ovdje je nevjerojatno.
{19456}{19506}Svia ti se?|Kako joö moûeö biti potiöten?
{19507}{19589}Ovo je sigurno neöto najbolje|öto nam se ikad dogodilo.
{19591}{19629}Nama?|Da, nama.
{19631}{19699}Ne budi sebiËna?|Otprati me.
{19701}{19747}Tamo Êeö staviti bar, zar ne?
{19749}{19850}Nekoliko naslonjaËa, kauË.|Kada stane bilo gdje.
{19851}{19893}Max, zatvori uöi.
{19923}{19990}Dovest Êemo toliko guzica|da Êe biti odvratno.
{19992}{20042}PriËam gluposti, mislim na muöko druûenje.
{20043}{20098}ZvuËi zabavno, ali
{20100}{20172}trebam malo viöe vremena|da sredim svoj ûivot.
{20174}{20243}Moram prirediti veliku zabavu|za poËetak.
{20244}{20322}Svakako.|Da upoznamo susjede.
{20324}{20371}Hajde, Mitch.|Znaö öto mislim.
{20372}{20402}Zamisli.
{20404}{20487}»ovjek iz agencije je bio|nepopustljiv u vezi...
{20489}{20559}Mislim da ne shvaÊaö|kakva nam je to prilika.
{20560}{20625}Cure vole deËka koji je|u situaciji kao i ti.
{20627}{20654}Kakvoj situaciji?
{20656}{20706}Mitch, na prekretnici si.
{20707}{20764}Ti si kao ozlijeeno lane|koje je ozdravilo,
{20766}{20834}koje Êe konaËno biti puöteno|u divljinu.
{20835}{20873}Oprosti.
{20875}{20913}Pazi. 
{20915}{20978}Oprosti. Dobro si?|Nemoj se ispriËavati meni nego djetetu.
{20980}{21018}Uznemirio si ga.|Oprosti, dijete.
{21020}{21066}U redu je. Dogaa se.
{21067}{21122}Ovdje treba neöto tropskoga.
{21124}{21202}Pijesak od zida do zida.|Poznajem tipa koji se time bavi.|Spustit Êe nam cijenu.
{21204}{21230}Ovdje pijesak?
{21231}{21294}Ili pjena, svejedno je.|Neöto mora biti unutra.
{21295}{21358}Razumijeö öto ûelim reÊi?|Naravno.
{21360}{21422}Slaûem se.|Samo moram pitati Marissu.
{21485}{21533}Zezam vas.|To je öala!
{21570}{21615}Nije smijeöno.|A sad se dijete uznemirilo.
{21862}{21915}Hej!
{21979}{21995}Hej!
{22013}{22053}Bok, duöo!
{22063}{22103}Donijela sam ti ledeni Ëaj!
{22105}{22158}Ne, hvala. Imam pivo.
{22161}{22213}Moûeö li nakratko ugasiti?
{22304}{22380}Stvarno je glasno.
{22382}{22414}Da. Hvala.
{22415}{22490}Skinuo sam graniËnik,|da pojaËam Crvenog zmaja.
{22492}{22594}Ali ne priËaj o tome.|Nije baö dopuöteno.
{22595}{22623}Hej, Mike!
{22625}{22652}Da.
{22654}{22727}äto ima?|Ne mnogo.
{22729}{22797}Sutra bismo mogli pisati zahvalnice.
{22799}{22859}Draga, sutra moram k Mitchu.
{22861}{22917}Pa, da.|Potpuno sam zaboravila.
{22919}{22961}Ali ne moram iÊi.
{22963}{23011}Ne, idi.
{23031}{23073}Ne budi lud. 
{23075}{23167}Ne ûelim da mijenjaö svoj ûivot|zbog mene.
{23200}{23257}Nazvat Êu Laru i isplanirati|veËer s curama.
{23259}{23314}Bit Êe zabavno.|Hvala.
{23315}{23357}Najbolja si.
{23376}{23426}Samo obeÊaj da Êeö se Ëuvati.
{23428}{23506}Kako to misliö?|Znaö öto mislim.
{23523}{23605}Mnogo je proölo od Spremnika Franka i|ne ûelimo da se vrati.
{23607}{23693}Dragi, Spremnik Frank se|neÊe vratiti, dobro?
{23695}{23770}Taj dio mog ûivota je zavröen.|Lanjski snijeg.
{23771}{23809}ObeÊavam.
{24139}{24167}Lijepo, zar ne?
{24169}{24215}Ovo je nevjerojatno.|Kako ti je to uspjelo?
{24217}{24279}Toliko ljudi i zvuËnika.
{24281}{24340}Mislio sam da Êe se okupiti|malo druötvo.
{24342}{24406}To je jedno od mnogih|malih druötava.
{24407}{24453}Zato imaö kuÊu, brate.
{24455}{24491}Zabavljaö se, zar ne?
{24493}{24552}OdliËno je.|Dobro.
{24554}{24651}äto si joö isplanirao?|Studentsku grupu?
{24653}{24685}Da, tako je.
{24687}{24768}SlijedeÊi na binu dolazi|studentska rock grupa.
{24770}{24810}Vlasnik sam öest Speaker Citieja.
{24811}{24879}Vrijedim 3.5 milijuna dolara,|za koje vlada zna.
{24881}{24951}Tamo imam viöe elektronike|nego prokleti KISS koncert.
{24953}{25057}Misliö da bih postavio crveni tepih|za grupu koja svira koraËnice?
{25059}{25095}Samo pazi da vidiö pozornicu.
{25107}{25155}Oprostite. Pardon.
{25156}{25233}Samo ûelim proÊi kroz vrata.
{25235}{25262}Hvala.
{25263}{25330}O njemu sam ti priËao.|Ovo je njegova kuÊa.
{25331}{25414}äto ima?|Ne, to je moj prijatelj, Mitch.
{25415}{25475}Moj prijatelj Mitch,|on je vlasnik kuÊe.
{25475}{25565}Potegni ovo.|Treba ti.
{25567}{25654}Ne, hvala, ali rekao sam ûeni|da veËeras neÊu piti.
{25666}{25745}I sutra imam vaûan dan.|Ali vi se zabavljajte.
{25747}{25807}Vaûan dan? äto Êeö raditi?
{25809}{25878}Zapravo zgodna, mala subota.
{25880}{25918}Idemo u  Dom.
{25939}{26003}Kupit Êemo tapete, moûda i parket.
{26015}{26076}Takve stvari. Moûda krevet,|kadu i ostalo. Ne znam.
{26078}{26136}Ne znam hoÊemo li imati|dovoljno vremena.
{26197}{26269}Znaö öto? Daj mi to.|Potegnut Êu jednom.
{26271}{26348}Potegnut Êe jednom!|Potegnut Êe jednom.
{26458}{26510}Ovo je daroviti Ëovjek.
{26602}{26660}O tome ja priËam.|NatoËi mi opet!
{26662}{26739}Boûe, kako je dobro.|Tako je dobro!
{26741}{26803}Kad ti dotakne usnice, tako je dobro.
{26807}{26890}Mnogo vam hvala, deËki.|Ovo Êe se dogaati cijele godine ovdje.
{26892}{26942}Pripremite se,|nemojte veËeras izgorjeti.
{26943}{27036}Hvala öto ste doöli na|festival slobode Mitcha Martina.
{27131}{27189}Za one koji ne znaju tko je|Mitch Martin,
{27190}{27242}on je vrlo uspjeöan,
{27242}{27318}vrlo zdrav gospodin koji stoji|kod mini- bara.
{27419}{27481}Sad, hvala Speaker Cityju,
{27483}{27574}koji kreöe cijene svemu|od bipera do DVD playera,
{27576}{27680}toplo pozdravite mog prijatelja
{27682}{27767}i vaöeg najomiljenijeg,|gospodina Snoop Dogga.
{28358}{28429}Frank! Frank!
{28660}{28770}Spremnik Frank!
{28811}{28892}Znaö!
{29182}{29217}To si ti.
{29219}{29242}äto?
{29244}{29291}Mitch Palooza, s postera.
{29292}{29327}Da, to sam ja.
{29327}{29387}Tulum je super. OdliËno.
{29387}{29445}Moji prijatelji su ga organizirali.
{29447}{29531}Puötaju me u divljinu.
{29533}{29587}O Ëemu to priËaö?
{29589}{29626}Niöta. Oprosti.
{30223}{30281}Idemo juriti!
{30414}{30441}Oprostite
{30443}{30566}Idemo juriti kroz kvart|i do dvorane.
{30568}{30599}Doite svi!
{30601}{30639}Hajde, Snoop!
{30659}{30682}Snoop-a-loop!
{30684}{30707}Snoop!
{30717}{30767}Ne, u redu je. Dobro sam.
{30769}{30815}Uzmi svoj zeleni öeöir. Idemo.
{30817}{30875}Doite, svi, idemo!
{30876}{30911}KreÊemo!
{30913}{30980}»ovjeËe, ËovjeËe.|UkljuËi opet glazbu.
{30982}{31042}Nastavimo s tulumom.
{31065}{31129}Hajde!
{31131}{31185}Jurimo! Doite!
{31187}{31252}Doite, svi...|Mi... hajde!
{31321}{31402}Jurimo! Jurimo!
{31454}{31493}Hajde!
{31527}{31553}Reci joj!
{31564}{31599}Marissa, potpuno sam zaboravila.
{31601}{31703}Znam da je malo kasno,|ali donijele smo ti svadbeni dar!
{31705}{31780}Ma dajte, rekla sam vam da mi|ne morate niöta kupiti.
{31782}{31876}Naöa prijateljica Ashley pozvala je tipa|da poduËava puöenje.
{31883}{31942}Bilo je super.|PoduËavanje?
{31942}{32010}I stvarno je dobar pa smo ga|morali unaprijed naruËiti.
{32012}{32050}Zaöto bih ja trebala na poduku?
{32052}{32145}Bernard bi trebao iÊi.|Kunem se, Ëovjek je oralni izazov.
{32160}{32250}Samo malo, je li taj tip...
{32251}{32295}Moj Boûe.
{32324}{32381}Odvratno!
{32403}{32447}Zaöto to gledam?
{32470}{32510}Zaöto usporavaö?
{32512}{32578}Samo vozi. Hajde.
{32597}{32621}Frank?
{32638}{32678}Nema öanse.
{32731}{32755}Frank!
{32775}{32810}Bok, duöo.
{32838}{32886}äto to radiö?
{32888}{32986}Jurimo. Idemo do gimnazije.
{33008}{33052}Tko juri?
{33054}{33098}Joö ih dolazi.
{33115}{33161}Frank, ulazi u auto.
{33163}{33208}Svi to rade.|Odmah!
{33210}{33233}Dobro.
{33361}{33422}Pomakni se.
{33548}{33588}Bok, dame.
{33595}{33677}Bok, Frank.|Vani je malo hladno, ha?
{33753}{33789}Molim vas, cure.
{33800}{33843}Misliö da je KFC joö otvoren?
{34269}{34315}Sranje.
{34393}{34429}Dobro jutro.
{34464}{34512}To je bio tulum.
{34598}{34654}Otkad si tako srameûljiv?
{34656}{34698}Nisam. Samo...
{34700}{34784}Jesam li noÊas hrkala.|Katkad hrËem kad sam pijana.
{34804}{34866}Ne sjeÊam se.
{34868}{34918}Mislim da nisi.
{34965}{35031}U vezi proöle noÊi.
{35053}{35157}Upravo sam izaöao iz vrlo ozbiljne|i traumatiËne veze.
{35187}{35253}Sad sam malo Ëudan.
{35276}{35308}äto?
{35310}{35365}Opusti ste, Rich, nema frke.
{35389}{35454}Mitch, s "M."
{35481}{35532}Dobro. Sluöaj.
{35554}{35659}Nema veze. Samo smo se zabavljali.|Nemaö se zaöto brinuti.
{35661}{35692}Ne.
{35694}{35753}Da, imaö pravo.|Nemam niöta protiv.
{35755}{35809}Desilo se. Samo sam...
{35811}{35876}Moram na nastavu, zato...
{35878}{35956}Kako Êemo to? Da ja...
{35958}{36008}Ostavit Êeö mi svoj broj?
{36010}{36074}Ne moraö se ni brinuti za to.
{36166}{36211}Vidimo se.
{36275}{36301}Bok.
{36351}{36380}Volim te.
{36382}{36473}U Speaker Cityju, reûemo cijene|od DVD playera
{36475}{36525}do kamkordera, i svega ostaloga.
{36527}{36605}Naöe uljudno osoblje Êe vas|poduËiti o öirokom izboru najmodernijeg
{36607}{36654}kuÊnog kina i ostalog pribora.
{36656}{36718}Pokaûite nam konkurentsku cijenu.|Mi Êemo biti niûi.
{36720}{36810}Ako ne moûemo, dat Êu vam|kljuËeve trgovine. Doslovno.
{36812}{36844}HoÊu reÊi, figurativno.
{36846}{36924}Bolje od naöih zvuËnika|zvuËe samo naöe cijene!
{36926}{36957}Bok, ludi klinac.
{36981}{37050}äto misliö? Iskreno.|Reci mi otvoreno.
{37051}{37082}Stvarno je dobro.
{37083}{37131}OdliËno izgleda.|Stvarno?
{37173}{37229}Boûe, malo sam otiöao...
{37231}{37286}SinoÊ sam poludio.
{37288}{37363}Da, joö se nisam Ëuo s Frankom.|Malo sam zabrinut.
{37365}{37411}Ima koga?
{37452}{37496}Ui. Isuse!
{37498}{37545}Ovo je tvoj kompiÊ?
{37547}{37613}Ovdje ima oko tri opasnosti za poûar.|äto radiö?
{37712}{37795}Cheese, jesi li to ti?
{37808}{37908}Bok, Mitch, Bernard.|Niste se mnogo promijenili.
{37910}{37933}Tko je taj?
{37935}{37988}SjeÊaö se Cheesea,|Rodneyjev mlai brat?
{37990}{38083}Zapravo se viöe ne zovem Cheese.|Zovem se Gordon Pritchard.
{38085}{38114}Pa da!
{38116}{38163}Cheese!
{38164}{38225}Nismo li te jednom zatvorili u kontejner?
{38227}{38264}Izaöao sam.
{38266}{38338}Super. Drago mi je.
{38395}{38450}SinoÊ ste se zabavili?|Jesmo.
{38451}{38533}Moûda ima ostataka cuge, uzmi ako ûeliö.
{38535}{38595}Ne, hvala. Radim.|äto radiö?
{38597}{38625}Patroliraö domom?
{38646}{38704}Pokuöaj ponovno.|Ti si Jehovin svjedok? 
{38706}{38749}Ja sam dekan.
{38751}{38799}Dekan Pritchard. Da.
{38801}{38876}I od jutros ova kuÊa je zatvorena.
{38903}{38975}Sada sluûi samo za svrhe doma.
{38977}{39014}O Ëemu to priËaö?
{39015}{39101}Ne moûeö to uËiniti.|Platio sam najam za prvi i zadnji mjesec!
{39103}{39133}Pogledaj ovo.
{39158}{39249}Imaö tjedan dana za iseljenje|i hvala na suradnji.
{39251}{39282}Super.
{39290}{39336}Mogu li neöto pitati?|Ne moûeö.
{39338}{39421}Bilo mi je drago, deËki.|»ini se da vam odliËno ide.
{39703}{39757}Frank, ovdje je sigurno.
{39759}{39853}Ovo je mjesto gdje moûemo priËati|o svojim osjeÊajima.
{39855}{39961}Zamisli moj ured kao gnijezdo|na drvetu povjerenja i razumijevanja.
{39963}{39999}Ovdje moûemo sve reÊi.
{40022}{40047}Sve?
{40094}{40157}U redu je, duöo.|Zbog toga smo doöli.
{40239}{40372}Ja mislim...|Malo sam zbunjen.
{40388}{40471}Odjednom se oûeniö
{40473}{40534}i oËekuje se da budeö posve drugaËiji.
{40536}{40580}Ja se ne osjeÊam drugaËije.
{40588}{40649}JuËer na primjer.
{40651}{40748}Izaöli smo o Maslenik na veËeru,|öto je bilo odliËno.
{40750}{40790}I...
{40792}{40911}Za vrijeme jela pogledao sam|konobaricu kako uzima narudûbu,
{40913}{41038}i pitao sam se koje su joj|boje gaÊice.
{41059}{41095}Njezine gaÊice.
{41161}{41273}Vjerojatnost je da ima obiËne|bijele, pamuËne gaËe.
{41275}{41386}Ali poËeo sam razmiöljati,|"Moûda su svilene."
{41387}{41429}"Moûda ima tange."
{41431}{41560}"Moûda ima neke stvarno super|za koje joö ni ne znam."
{41562}{41645}Znaö?|I poËeo sam se osjeÊati...
{41655}{41679}äto je?
{41697}{41769}Mislio sam da smo na drvu povjerenja,|u gnijezdu. Zar nismo?
{41771}{41835}Jesmo. U redu je.|Dobro?
{41861}{41937}U redu je. Molim, nastavi.
{41947}{42010}Ne znam öto sam time htio reÊi.
{42066}{42144}Valjda pokuöavam reÊi,|da sad kad sam oûenjen,
{42146}{42237}sad me izbezumljuje ta Ëinjenica
{42239}{42338}da Êu spavati samo s jednom osobom
{42376}{42428}do kraja ûivota.
{42459}{42535}Walsh kaûe da je tvoje putovanje|u San Diego bila ludnica!
{42538}{42568}Da.
{42570}{42604}Kako je bilo u Hooters?
{42606}{42655}Zapravo nisam iöao u Hooters.
{42657}{42695}Pa da.
{42697}{42732}Skittles?
{42734}{42766}Ne, hvala.
{42768}{42828}Sluöaj Manetti me nazvao.
{42830}{42928}Kaûe da je tvoja ponuda|Sunshine Squara bez veze.
{42930}{42966}äto ne valja?
{42968}{43051}Prvo, kröi odreena teritorijalna ograniËenja
{43053}{43140}iz Zakona o povijesnom oËuvanju iz 1966.
{43142}{43207}Najvjerojatnije, Ëlanak Ëetvrti.
{43209}{43239}Da nastavim?
{43241}{43301}Poznat mi je taj Ëlan...|Duöo.
{43303}{43351}Bok, tata, prekidam?|Ne, ui.
{43389}{43466}Nisi upoznao moju kÊer.|Darcie, ovo je Mitch Martin.
{43518}{43564}Drago mi je, Mitch.
{43566}{43614}Bok, drago mi je.
{43616}{43672}Kako je bilo na tulumu?|Super. Znaö,
{43674}{43726}filmovi i kokice.
{43729}{43774}Aneo je.
{43796}{43877}ZvuËim kao starac, ali ne mogu vjerovati|kako brzo odrasta.
{43879}{43946}Tata, prestani!|Oprosti, zlato, ali tako je.
{43947}{44055}Za samo 7 mjeseci Êeö zavröiti srednju.
{44123}{44167}Dobro si?
{44169}{44215}»ini mi se da si rekao srednju ökolu.
{44217}{44265}Da. äokantno, zar ne?
{44293}{44334}Da.
{44556}{44587}Super.
{44589}{44627}Hej, Mitch.
{44722}{44798}Bok. Imao si ugodan dan?
{44799}{44843}Nije bio loö.
{44872}{44907}äto se dogaa?
{44908}{45009}Mislio sam ovdje prespavati,|ako nemaö niöta protiv.
{45011}{45080}Marissa ima osobnih problema.
{45117}{45223}Osobni problem jer ti trËiö|kvartom gol i pijan?
{45224}{45310}To i neöto drugo.
{45347}{45393}Nema problema.|Raskomoti se.
{45395}{45424}Hvala.
{45440}{45530}Gospodo, razgovaramo o|novom naËinu bratstva.
{45532}{45665}Drugim rijeËima, zaboravite normalna pravila|koja vrijede za faks i druötvo
{45667}{45733}jer ovo je vrlo velika zamisao, prijatelji.
{45735}{45834}Radi se o ne ekskluzivnom,|ravnopravnom bratstvu
{45836}{45907}gdje druötveni poloûaj i,|öto je joö vaûnije, godine,
{45909}{45962}nemaju nikakve veze.
{45988}{46041}Da? Kaûe tip koji neÊe dobiti.
{46043}{46107}Ovdje sam iöao u ökolu.|Dobro.
{46109}{46204}Zanima me, kakve Êeö veze imati s faksom?
{46206}{46257}Tko su ti ljudi?|Ne znam.
{46259}{46338}Pravno govoreÊi,|to Êe biti labava veza,
{46340}{46421}ali niöta neÊemo vraÊati|akademskoj zajednici.
{46423}{46517}I neÊemo raditi besplatno.|To vam obeÊavam.
{46519}{46573}äto se ovdje dogaa?
{46575}{46634}DeËki, ovo je posebna prilika.
{46636}{46731}Sam kum nas je poËastio svojom prisutnoöÊu.
{46733}{46765}Kum!
{46767}{46846}Ovo je njegova kuÊa.|On ûivi ovdje, spava 15 metara odavde.
{46902}{46949}Moramo razgovarati.
{46955}{46979}U kuhinju.
{47005}{47085}Budi dobar, moram razgovarati|sa striËekom Mitchom.
{47091}{47130}Tako.
{47131}{47208}Koliko dugo su ti ljudi ovdje?|Cijeli dan.
{47210}{47272}Zbog juËeraönjeg tuluma smo stekli|povjerenje ulice.
{47274}{47316}O Ëemu to priËaö?
{47318}{47400}Ovo je zove "navala."|Sluûbeno osnivamo bratstvo.
{47402}{47449}Svia mi se. Genijalno!
{47451}{47490}Sigurno se öaliö.
{47492}{47542}»uo si Pritcharda?|Moramo to uËiniti.
{47544}{47642}Ova kuÊa sluûi samo u druötvene svrhe|i stanovanje studenata.
{47644}{47688}Bratstvo rjeöava oboje.
{47690}{47754}Ali ovo je moja kuÊa.|Ja ûivim ovdje, Beanie.
{47756}{47836}Ima 30 godina.|Nismo upisani na faks.
{47838}{47926}ShvaÊam. Gledaö krive pojedinosti.
{47927}{47999}Nisi li se zabavio na tulumu?
{48000}{48043}Meni je bilo ludo.
{48053}{48102}Znam da ti je bilo ludo.
{48104}{48163}Cijeli grad zna da ti je bilo ludo.
{48165}{48226}Pokuöavam pitati Mitcha|da li je njemu bilo ludo.
{48228}{48269}Bilo mi je dobro.|To je dobro.
{48271}{48319}Ne ûeliö li da se ta zabava nastavi?
{48321}{48377}Joö bolja...|Boûe, hoÊu reÊi...
{48379}{48469}Ne shvaÊam. Ne znam zaöto je|tako teöko priznati da ovo ûeliö.
{48471}{48551}»etrdesetorica to ûele.|Mora postojati razlog za to.
{48553}{48607}Cijenim tvoj zanos.
{48609}{48703}Znam da pokuöavate pomoÊi,|ali istina je,
{48704}{48796}imao sam uûasan dan,|i joö gori mjesec.
{48798}{48895}Imam 40 stranaca u dnevnoj sobi
{48897}{48962}i samo se ûelim jebeno dobro|naspavati.
{48964}{49066}Zato oprostite, ali neÊemo|osnovati bratstvo.
{49068}{49145}Ne znam zaöto moraö prostaËiti|pred djetetom.
{49147}{49197}Samo mu moraö reÊi da pokrije uöi.
{49199}{49247}Tada moûeö reÊi,|"jebi ga, sranje, kuËka," ötogod ûeliö.
{49249}{49280}Kurac. Muda.
{49282}{49350}Samo ûelim dokazati.|Ne moraö preuveliËavati, Frank.
{49351}{49409}Oprosti.|Nemoj se meni ispriËavati.
{49411}{49473}Iznevjerio si Franka, mene,|i najvaûnije, iznevjerio si Maxa.
{49475}{49527}I upravo sada|mi je teöko
{49530}{49615}shvatiti zaöto troöim svoje slobodne vrijeme|kako bih ti pomogao preboljeti...
{49617}{49666}Pokrij uöi.|Onu kurvu s kojom si izlazio.  
{49667}{49783}éeliö vidjeti ostale?|StriËeku Mitch je ûao.
{49823}{49858}Pristani.
{49860}{49885}Pristani.
{50053}{50101}Ovako Êemo. Sluöajte!
{50103}{50172}Do sada smo skupili 14 molbi.
{50174}{50221}»ekaj, to je ovaj?
{50223}{50257}To je Plavi.
{50259}{50315}On je veteran mornarice koji je|Ëesto kod moje trgovine.
{50317}{50357}Ali ne brini za to.|Pravi je.
{50359}{50421}Izgleda kao da ima sto godina.|éeli se prijaviti?
{50423}{50510}äaliö se?|Stari moreplovac neprestano priËa o tome.
{50511}{50558}KreÊemo!
{50928}{50991}Nemoj si joö viöe oteûavati!
{51294}{51317}äto se dogaa?
{51319}{51377}Reci to nekome i ubit Êu te!
{51380}{51450}äalim se. Vratit Êemo ga veËeras.|U redu, draga?
{51452}{51484}Idemo!
{51768}{51824}Hajde, idemo.|Idemo, Plavi.  
{52069}{52116}»estitam, gospodo.
{52118}{52167}Trebali bi se ponositi sobom.
{52170}{52240}Svaki od vas je izabran
{52242}{52325}kako bi predstavljali naö|inauguracijski razred.
{52328}{52390}SljedeÊih 21 dan,
{52390}{52548}iskusit Êete intenzivni umni|i fiziËki napor.
{52614}{52660}Frank, suzdrûi se.
{52681}{52756}Razumijem. Malo sam se previöe uzbudio.|Oprosti.
{52758}{52859}Sada se moûda pitate,
{52861}{52974}"zaöto drûim tu ciglu u ruci?"
{53015}{53071}Moûda se i pitate,
{53096}{53223}"Zaöto ova cigla ima dugaËko uûe
{53246}{53286}na sebi?"
{53300}{53354}I konaËno.
{53400}{53496}"Zaöto je drugi kraj uûeta privezan
{53510}{53554}za vaö penis?"
{53585}{53664}I odgovor na to, moje dame,|je povjerenje.
{53689}{53766}Ovo vam je prvi test.
{53780}{53816}äpanjolac!
{53822}{53880}Vjerujete li da smo ti dali|dovoljno prostora
{53882}{53944}da tvoja cigla padne sigurno|na travu?
{53945}{53982}Da, gospodine.
{53984}{54026}I Plavi!|Da, gospodine?
{54028}{54084}Vjerujeö li da noÊas ne ûelim|vidjeti kako umireö?
{54086}{54142}Da, gospodine.|Plavi, ti si moj deËko!
{54144}{54176}Hvala, gospodine.
{54236}{54273}Okrenite se.
{54352}{54395}Pristupite rubu!
{54489}{54547}»lanovi, pripremite se za puötanje!
{54600}{54637}Jedan...
{54647}{54678}dva...
{54689}{54741}tri! Pusti!
{55007}{55061}Nije trebalo biti tako, Weensie!
{55063}{55126}Izdrûi, veliki.|Silazimo.
{55558}{55602}Brûe!
{55643}{55714}Isuse. Tko su ti ljudi?
{55785}{55845}Patricia, pozovi osiguranje|na juûnu livadu.
{55847}{55913}Tamo je nedozvoljeno vozilo.
{55915}{55965}VeÊ su pozvani, gospodine.
{55967}{56021}Zovi ih ponovno.
{56138}{56244}Proölo je dva tjedna.|Kako joö mogu biti bratstvo?
{56246}{56288}Nisu bratstvo.
{56290}{56360}Dobili su privremenu dozvolu|od studentskog vijeÊa.
{56362}{56418}Polovica ih niti ne ide na faks.
{56419}{56466}Jedan izgleda kao da ima 90.
{56468}{56535}TehniËki, to nema veze.|Naöli su rupu u zakonu.
{56537}{56572}Rupu u zakonu?|Da.
{56575}{56612}Zanimljivo je.
{56614}{56693}Bez obzira koliko se Ëinili glupi,|zapravo znaju s papirima.
{56695}{56738}To je anomalija.
{56751}{56818}Oprosti, to je smijeöno?|Ti si komiËar?
{56820}{56855}Time se sada baviö?
{56927}{56979}Ja odlazim. Odlazim.
{57262}{57302}Evo ga.
{57323}{57364}äto ima, brate?
{57366}{57420}Niöta.|Samo kopiram.
{57451}{57487}Vidimo se kasnije.
{57489}{57541}Hej, Mitch, Ëekaj malo.
{57543}{57610}»ujem da osnivate bratstvo.
{57612}{57645}Tko ti je to rekao?
{57647}{57697}Nitko. Je li istina?
{57699}{57757}Ne znam o Ëemu priËaö.|Baö.
{57759}{57818}ZvuËi super.|éelim pristupiti.
{57846}{57925}Sluöaj me.|Nema bratstva.
{57927}{57982}Ne znam ni o Ëemu priËaö.
{57984}{58048}Sluöaj ti mene.|To mi je potrebno.
{58050}{58150}Moja ûena, moj posao, moja djeca.|Svaki dan je isti.
{58152}{58208}Subotom idem na golf.
{58210}{58260}Mrzim golf.
{58262}{58318}Nemoj me odbiti, Mitch.|Molim te.
{58320}{58406}NeÊu te odbiti.|Radimo zajedno, Walsh.
{58408}{58485}I ne ûelim mijeöati posao|s onim öto radim kod kuÊe.
{58493}{58566}Vjeruj mi, ionako niöta ne propuötaö.
{58568}{58597}Stvarno?
{58599}{58657}»ujem da si se spanao|s Goldbergovom kÊerkom.
{58666}{58728}Oprosti. Oprosti.
{58753}{58803}To nije istina!
{58899}{58959}Mitch, samo ûelim da razmisliö o tome,|dobro?
{58961}{58998}Razmisli!
{58998}{59050}Pa öto?|Koga briga öto radiö s njim?
{59052}{59110}Mene je briga.|Moram razmiöljati o karijeri.
{59112}{59208}Naporan si.|Moraö poËeti voljeti ovu stvar.
{59210}{59281}Mislim da ne cijeniö öto sam sve|uËinio za tebe.
{59283}{59329}Za mene?|Da, za tebe.
{59331}{59410}Misliö da volim zapostavljati ûenu i djecu|kako bih se druûio s curicama?
{59410}{59451}Da, mislim.|Pa, ne volim.
{59454}{59506}Ovo radim za tebe.|Bok.
{59508}{59586}Nicole, kako si?|Tko je ovo?
{59587}{59641}Ovo je moja kÊer, Amanda.|Pozdravi, duöo.
{59643}{59699}Bok, Amanda.|SjeÊaö se Nicole, zar ne?
{59701}{59784}Da, plesali smo na svadbi.
{59786}{59838}Kako si?|Dobro, hvala.
{59838}{59857}Dobro.
{59859}{59931}Htio sam se ispriËati zbog vjenËanja.
{59932}{59977}Nadam se da ti nije bilo neugodno.
{59979}{60048}U redu je.|Sebe si osramotio.
{60050}{60137}Donijela sam ti dar za useljenje.|Lijepo od tebe.
{60139}{60229}To je samo drûaË CD-a za tvoj stol.|Mislila sam...
{60231}{60293}Ne, ovo je sranje. Uûas.
{60325}{60389}Prestao sam ga prodavati prije öest mjeseci.|Molim te, Beanie.
{60391}{60431}Hvala.|Mnogo prituûbi.
{60433}{60488}Ali je lijepa gesta, mislim.|Ne, ovo je super.
{60489}{60524}Hej, Kume!
{60526}{60584}äto je?|Hej, ti si glavni!
{60587}{60620}Vidimo se, stari!
{60622}{60670}Je li to ovaj upravo nazvao Kumom?
{60672}{60736}Sigurno se öali.
{60738}{60778}Gdje sada ûivite?
{60779}{60854}Ostat Êemo malo kod mog tate,|dok ne naemo neöto bolje.
{60855}{60903}Amanda je teöko podnijela selidbu.
{60904}{61017}Moj Êe sin u subotu imati öest godina.|Prireujemo mu zabavu.
{61019}{61075}Sa ûivotinjama i klaunovima.
{61077}{61123}Ali vi ste dobrodoöli, ako ûelite.
{61125}{61174}OdliËna ideja! Morate doÊi.|Dobro.
{61175}{61262}äto viöe volite?|Medicinsku sestru ili navijaËicu?
{61306}{61339}Bok, Nicole.
{61353}{61387}Bok, Frank.
{61389}{61449}Imaö lijepu lutku.
{61451}{61501}Hvala. Dobra je.
{61526}{61561}Jesi li se zabavljala na vjenËanju?
{61582}{61626}Da, bilo je zabavno.
{61663}{61727}Za sada ûivim ovdje.
{61729}{61769}Vidimo se u nedjelju.
{61771}{61817}Da, u nedjelju.
{61819}{61863}Bok. Pozdravi.|Bok.
{61892}{61921}Bok.
{62092}{62145}Bok, dobili ste Marissu.|I Franka!
{62147}{62203}Nismo ovdje, ostavite poruku.
{62204}{62243}Bok, duöo, ja sam.
{62245}{62333}Samo sam se htio javiti.
{62335}{62422}U zadnje vrijeme imam posla.|Mnogo papirologije
{62424}{62447}K vragu.
{62449}{62559}Ako ste zadovoljni pritisnite "1."|Za ponovno snimanje pritisnite "2."
{62582}{62654}Bok, Marissa, ja sam.|Sluöaj.
{62655}{62711}Kasnije Êu biti u blizini.
{62713}{62806}Nisam znao ûeliö li da se katkad|zajedno pojedemo smrznuti jogurt
{62808}{62863}ili moûda cijeli obrok.
{62865}{62925}Ako se slaûeö...|Glupo.
{62927}{63025}Ako ste zadovoljni pritisnite "1."|Za ponovno snimanje pritisnite "2."
{63048}{63112}Bok, Marissa, ovdje Frank Ricard...
{63147}{63174}U redu, dame.
{63175}{63247}Tajna dobrog puöenja je koncentracija.
{63247}{63301}Ne tiËe me se je li vam|deset godina muû
{63303}{63424}ili je to neki mornar koje ste sreli|prije nekoliko mjeseci.
{63426}{63462}Koji me nikad nije nazvao
{63464}{63547}ali mi je ostavio neöto|öto se zove herpes.
{63548}{63619}äto sam onda prenio psu.
{63634}{63671}Ali to nije niti tu ni tamo.
{63692}{63736}Uzmite svoje povrÊe.
{63892}{63956}Tko je gladan? Tko je gladan?
{63958}{64008}Hajde. On to ozbiljno?
{64010}{64085}Da, dobar je.|Najbolji je.
{64087}{64162}Dame, palci su nam dolje,|dlanovi spuöteni,
{64164}{64222}hoÊemo li se postaviti za umetanje.
{64288}{64340}Spremne? Idemo.
{64388}{64449}Dobro, Marissa.
{64451}{64520}Moûete upotrijebiti zube|ali nemojte gristi.
{64578}{64629}Sad Êete obaviti posao, dame.
{64631}{64698}Mrkve neÊe same ejakulirati.
{64698}{64758}Primite se posla.|Vrlo dobro.
{64759}{64800}Vrlo dobro.
{64802}{64862}Dobro, dobro, dobro.|Ne tako dobro.
{64864}{64908}Molim vas, öto radiö?
{64910}{64962}Nisi Romul koji siöe cice vuËice.
{64962}{65010}Ako poznajete grËku mitologiju.
{65010}{65058}Dame, mi puöimo.
{65058}{65106}Ne siöemo mitoloöku dojku.
{65152}{65207}To ti je smijeöno?|Jer neÊeö se smijati
{65209}{65255}kad ti netko prerano svröi u lice.
{65257}{65339}To peËe, i zato sam razrok.
{65341}{65409}Mnogo vam hvala.|Nastavite, molim.
{65411}{65471}Gore i unutra.
{65484}{65533}I pazite na pastorke.
{65535}{65586}Pazite na pastorke.
{66009}{66088}Marissa, hajde.|Tako je.
{66191}{66244}Svia mi se öto vidim.|Ne boj ga se svinuti.
{66300}{66367}Marissa, hajde.|Tako.
{66433}{66510}Svi mogu nauËiti od Marisse.|Uzet Êu kratku stanku.
{66511}{66559}Vi nastavite.
{66611}{66659}OdliËno, Marissa.
{66684}{66755}Tako se daje sve od sebe.
{66757}{66817}Kad se vratim, pokazat Êu vam|neöto öto zovem
{66819}{66881}"PuzeÊi tigar, skriveni penis."
{66905}{66932}Gledali ste taj film?
{66934}{67023}Svia mi se zbog letenja i magije.
{67034}{67104}Gad!
{67109}{67164}Netko je upravo gadno pogrijeöio!
{67380}{67460}Isuse, Frank!|äto Êeö ti ovdje?
{67462}{67504}Poznajeö ovu osobu?
{67506}{67555}Tako mi je ûao.|Ozlijeen si?
{67557}{67605}Da, ozlijeen sam.
{67746}{67801}Boba nema. U planinama su.
{67880}{67941}Ovaj puta si nadmaöio samog sebe.
{67943}{68013}Lijepo je, zar ne?|äpanjolac, öto to radiö?
{68015}{68079}Samo idem po vode.|VruÊe mi je u kostimu.
{68081}{68172}Nastavi glavu! Poludio si?|Za njih to moûe biti traumatiËno.
{68174}{68230}Imaö pravo, oprosti.|Nemoj ti meni "oprosti".
{68232}{68291}Maöi repom kad hodaö.|Znaö ti bolje.
{68293}{68321}Smiri se.
{68322}{68361}Joö nije gotovo.
{68367}{68410}Bok, deËki.|Bok.
{68412}{68457}Lijep kostim.|Hvala.
{68459}{68513}OdliËna zabava.|Kad si stigla?
{68514}{68585}Prije nekoliko minuta.|Ovo je moj deËko, Mark.
{68586}{68669}JuËer je doletio iz Colorada.|Ovo su Mitch i Beanie.
{68671}{68708}Kako je, deËki?
{68710}{68735}Drago mi je.
{68737}{68798}Netko mi je rekao
{68800}{68858}da ste u bratstvu.|Je li to istina?
{68860}{68918}Nije.|Bratstvo. Je li to istina?
{68920}{69031}Nije baö, hoÊu reÊi, ne.|To je viöe kao druötveni klub.
{69033}{69092}Samo gledamo nogomet i druûimo se.
{69094}{69155}Druûite se i lupate po dupetu.
{69157}{69208}Nije tako.|Ne shvaÊamo to ozbiljno...
{69210}{69284}Plavi!|Zaöto nema leda u limunadi?
{69286}{69321}Oprostite, gospodine!
{69323}{69381}Daj mi deset sklekova!
{69383}{69415}Odmah!|Razumijem.
{69434}{69458}Idemo!
{69460}{69488}Hvala Frank.
{69518}{69586}Dat Êu vam ovo.|Moj broj s posla. Nazovite me.
{69587}{69625}Speaker City.|Moje su svih öest lokacija.
{69639}{69728}Max ûeli otvoriti poklone,|ali neka otvori jedan.
{69730}{69799}Ui, Maxy.|IspriËajte me.
{69801}{69866}O surround zvuku i ostalom Êemo poslije.|Dat Êu vam ponudu.
{69868}{69917}NeÊu te nagovarati.
{69919}{69958}Kako si, stari?|Kakav dan!
{69960}{70026}Moûemo otvoriti ujaka Franka,|ali ostale Êemo kasnije.
{70028}{70092}Ne znam tko je uzbueniji,|Frank ili Max.
{70094}{70158}Rastrgaj! Hajde.|äto je to?
{70160}{70238}Je li moûda svemirski brod?|Da vidimo öto smo dobili!
{70312}{70374}äto kaûeö, Max?|Ima tri brzine.
{70553}{70586}Prokletstvo.
{70689}{70754}Oprosti. éelim jedan.
{70792}{70836}Ja sam Mark.|Kako se ti zoveö?
{70838}{70864}Tracy.
{70897}{70962}Drago mi je, Tracy.
{70966}{71037}Evo ga..|Tako je.
{71038}{71098}Sad moûeö izaÊi i igrati se.
{71100}{71130}Hajde.
{71132}{71217}Uzmi lutku.
{71269}{71333}Mislim da joj se sviaö.|VeÊinu ignorira.
{71335}{71370}PoËaöÊen sam.
{71411}{71522}Mark je zanimljiv.
{71524}{71561}Bezopasan je.
{71567}{71625}Koliko ste zajedno?|Dvije godine.
{71647}{71735}Rekla sam da sam u srednjoj bila zaljubljena|u tebe i mislim da je bio ljubomoran.
{71737}{71782}Bila si zaljubljena u mene?
{71784}{71861}äaliö se.|Ja sam bio opsjednut tobom.
{71863}{71972}Niöta opasno.|Samo sam te promatrao iz daljine.
{71974}{72026}Zaöto me nisi onda pozvao van?
{72028}{72090}Tada si bila priliËno zastraöujuÊa.
{72092}{72199}Uvijek si bila sa starijima.|Imala si jaknu Whitesnake od trapera.
{72201}{72276}Puöila si crveni Marlboro.|Bila si naprednija od mene.
{72327}{72391}Joö uvijek imam tu jaknu.
{72406}{72486}Joö te se priliËno bojim.
{72571}{72666}Loö si.
{72670}{72735}Imaö pravo. Loö sam.
{72796}{72849}Oprosti...
{72851}{72906}Ne kucamo?|Oprosti.
{72907}{72962}Oprosti, moram se vratiti na posao.
{72964}{73025}...samo vratiti zavoje.
{73055}{73104}äto Êeö uËiniti?|Cinkat Êeö me.
{73106}{73200}Znaö da ne moûeö, stari.|To je muöko pravilo. Dobro?
{73206}{73279}DeËki ne cinkaju druge deËke.|To...
{73281}{73321}rade ûenske.
{73382}{73434}Ti nisi ûenska, zar ne?
{73499}{73590}Hvala na razgovoru.|Vidimo se vani.
{73794}{73833}Bok, stari.
{73835}{73876}Trebaö prijatelja?
{73898}{73936}I ja.
{74014}{74038}Hej.
{74307}{74369}Divan je, zar ne?|Da.
{74370}{74423}Kakav je to piötolj?
{74425}{74470}Za uspavljivanje.
{74472}{74550}Ako netko od njih napadne djecu,
{74552}{74586}moram ih uspavati.
{74625}{74672}Zar ne, mama?|äto je?
{74674}{74724}To sam i mislio. Zaveûi.
{74733}{74786}Hej, oprezno s time.
{74788}{74854}Ovo je najjaËi piötolj|za uspavljivanje na trûiötu.
{74855}{74893}Kupio sam ga u Meksiku.
{74895}{74951}Guba.|Da, guba je.
{74953}{75023}Kaûe da moûe probiti koûu|nosoroga na sto...
{75199}{75232}To!
{75234}{75271}Ludica!
{75294}{75324}äto?
{75335}{75398}Dobio si u ûilu kucavicu!
{75488}{75514}Da!
{75553}{75596}Boûe moj.
{75618}{75681}Moj Boûe, jesam.|Je li to loöe?
{75690}{75730}Je li loöe?
{75732}{75798}Trebao bi to izvaditi.|Ovo nije guba.
{75866}{75897}»ekaj.
{75899}{75959}»ekaj. äto da izvadim?
{75961}{76045}Strelicu, ËovjeËe.|Imaö strelicu u vratu.
{76119}{76189}Lud... Lud si, ËovjeËe.
{76191}{76235}Lud si.
{76237}{76278}Sviaö mi se.
{76297}{76337}Ali si lud.
{76374}{76419}Umoran sam.
{76689}{76761}Ne!
{78055}{78130}Ovo je najljepöi dan.
{78158}{78193}Da.
{78210}{78254}Stvarno je.
{78433}{78474}Nedostajao si mi, Frank.
{78475}{78533}Drago mi je öto si se vratio.
{78556}{78604}I ti si meni nedostajala, draga.
{78636}{78680}Predivno izgledaö.
{78710}{78759}Drag si.
{79039}{79112}Zaûvalio me!
{79241}{79273}Nadam se da Êe upaliti.
{79274}{79368}»lanovi odbora se raspituju|o tom "civilnom bratstvu."
{79370}{79425}Ne brini, upalit Êe.
{79455}{79547}Evo je.|Zove se Megan Huang.
{79549}{79583}Ona je predsjednica studenskog vijeÊa
{79585}{79674}pravo, zvijezda teniskog tima,|mnogo obeÊava.
{79676}{79722}Mlada ûena koja moûe mnogo izgubiti.
{79723}{79761}Megan, zdravo.|Bok.
{79763}{79801}Sjedni.
{79953}{80013}Sigurno poznajeö dekana Pritcharda.
{80015}{80051}Ne okreÊi se.
{80118}{80204}Megan, ono malo bratstvo|u Brookovoj ulici
{80206}{80298}postalo nam je smetnja.
{80299}{80399}I kao predsjednica studentskog vijeÊala,|dala si im privremenu dozvolu.
{80401}{80497}Naûalost, samo ti je moûeö ukinuti.
{80498}{80557}Trebat Êemo te da to uËiniö.
{80559}{80638}Da je ukinem? Zaöto?|Ti deËki se svima sviaju.
{80640}{80743}Prireuju lude zabave.|Na kasino veËeri sam upoznala svog deËka.
{80745}{80790}To je super.
{80791}{80873}Piöe da se ûeliö upisati|na Pravni fakultet Columbia.
{80875}{80940}Teöko je upasti tamo.
{80942}{81037}Dekan Pritchard ima jake veze|na Columbiji.
{81057}{81094}PodmiÊujete me?
{81167}{81221}Nemoj si oteûavati ûivot, Chang.
{81222}{81259}Zovem se Huang.
{81275}{81349}Svejedno.|Kako sezona tenisa?
{81359}{81449}Napravilo sam male promjene,|ali sve u svemu je u redu.
{81451}{81518}Ovo je standardni ugovor o najmu.|Dobro, super.
{81519}{81616}Hvala öto si ga proËitao.|Takva stvari me uvijek zbunjuju.
{81618}{81646}Nema na Ëemu.
{81650}{81740}Ti i Mark Êete ûivjeti zajedno?
{81755}{81854}Da.|Financijski ima smisla, zato...
{81866}{81976}Mislim da bi neöto trebala znati...
{81999}{82042}o Marku.
{82043}{82079}äto?
{82090}{82169}Pa...
{82208}{82277}Veze su naporne.
{82278}{82351}I hoÊu reÊi...
{82467}{82504}Sretno.
{82531}{82589}Hvala.
{82590}{82634}Sluöaj.
{82636}{82741}Moûda moûemo jednom na veËeru.
{82743}{82790}Moûe.|Ako se ti slaûeö.
{82792}{82836}Rado.
{82838}{82948}Naravno, morao sam Ëekati|da imaö deËka
{82950}{82993}da te konaËno pozovem van.
{82994}{83037}Nikad nisi znao odabrati vrijeme.
{83039}{83070}Nisam.
{83120}{83166}Dakle, hvala.
{83209}{83266}I nazovi me u vezi veËere.
{83267}{83321}HoÊu.|Oprostite, gospodine!
{83328}{83370}Imamo problem!
{83371}{83425}äto Êete vi ovdje?|Rekao sam nikad na poslu.
{83426}{83462}Ali je hitan sluËaj.
{83464}{83523}Moûemo kupiti gel samo od sto grama.
{83525}{83645}Za veliko pakiranje treba 3 do 4|radna dana. U frci smo.
{83646}{83673}äto Êe vam to?
{83675}{83726}Plavi ima roendan.|Imat Êemo natjecanje u hrvanju.
{83728}{83808}Moûemo li kasnije o tome razgovarati?
{83901}{83972}Idem opet, duöo!
{84252}{84324}Nije fer!|Krenulo mi je!
{84596}{84694}Otkini mu glavu!
{84990}{85035}Svia mi se tvoja soba.
{85037}{85121}Hvala.|Ona mi je dom daleko od doma.
{85123}{85175}Svi posteri su moji.
{85183}{85263}InaËe ne volim deËke iz bratstva.|Oni su bezveznjaci.
{85265}{85364}Ali ti si... zreo.
{85379}{85408}Zreo?
{85410}{85438}Da.
{85440}{85521}Gdje spavaö?
{85522}{85587}InaËe kod kuÊe.
{85589}{85646}Katkad prespavam ovdje.
{85647}{85729}Ovo je kauË.|RazvlaËi se.
{85731}{85768}Guba. Nisam znala.
{85782}{85823}Mogu vidjeti?
{85834}{85871}KauË?
{85880}{85913}Da.
{86076}{86122}Amy, oprosti.
{86135}{86214}Oûenjen sam.|Ne mogu ja to.
{86215}{86262}Ne ûelim da postane Ëudno, ali...
{86264}{86326}Dobro. ShvaÊam.
{86342}{86410}Ali ostavi mi svoj broj.
{86411}{86486}Ako se mojoj ûeni neöto dogodi,|nazvat Êu te.
{86488}{86554}NeÊe iÊi.|To je bila loöa ideja.
{86615}{86697}Dame i gospodo, dobrodoöli na|veËeraönji glavni dogaaj!
{86831}{86907}U ovom uglu, 60 kila teûak,
{86909}{86978}i 89 godina ûivota,
{86980}{87056}nedavni dobitnik novog plastiËnog kuka,
{87058}{87114}Joseph "Plavi" Pulasky!
{87213}{87326}A u suprotnom uglu,|s teûinom od 105 kila,
{87328}{87394}doËekajmo iz doma Hayden,
{87395}{87444}Jenny i Jeanie!
{87585}{87657}Borci, jeste li spremni?
{87714}{87761}Plavi, sigurno to moûeö?
{87763}{87831}Daj pozvoni veÊ jednom, piËkice.
{87852}{87914}PoËnimo!
{88026}{88089}Hajde.|Hajde, djede, idemo.
{88103}{88146}Idemo, slavljeniËe!
{88147}{88216}Bojiö se?
{88218}{88249}Halo?
{89195}{89274}Bolje da malo priËekamo s hrvanjem.
{89275}{89325}Dobra ideja.
{89327}{89432}Nemoj se ûivcirati.|Niti ti kriv.
{89434}{89490}Prokletstvo, Plavi je bio star.
{89491}{89558}To i Ëine stari ljudi.|Umiru.
{89559}{89598}éao mi je.
{89932}{89971}Ti si moj, Plavi!
{89983}{90029}Ti si moj.
{90116}{90172}Ovo je bio Ëudan mjesece, zar ne?
{90174}{90209}Da.
{90249}{90336}Oprosti öto te nisam nazvala|za roendan.
{90338}{90386}Kako to misliö?
{90388}{90430}Da, proöli Ëetvrtak.
{90463}{90534}Zaboravio si svoj roendan, zar ne?|K vragu!
{90536}{90584}Baö sam glup.
{90616}{90736}äto si radio?|Imao sam posla.
{90762}{90867}Pokuöao sam se uËlaniti u novu teretanu.
{90882}{90932}To je bilo jedno.
{90939}{91039}A ostalog se ne sjeÊam,|ali imao sam posla.
{91041}{91130}Nedostajeö mi. Znaö?
{91132}{91173}éelim da to znaö.
{91174}{91261}Moûda se veËeras moûemo naÊi kod kuÊe
{91262}{91330}i posluöati Sisqoov CD...
{91331}{91395}Mislim da to nije dobra ideja.
{91402}{91460}Stvarno?
{91462}{91508}Ne znam.
{91521}{91585}Moûda smo se poûurili.
{91606}{91705}Ne Ëini mi se u redu.
{91744}{91789}äto smo vjenËani?
{91826}{91870}Kako to misliö?
{91900}{91970}Mislim da bismo se trebali razvesti.
{92013}{92058}Prava rastava?
{92082}{92115}Da.
{92128}{92162}ShvaÊam.
{92197}{92241}Dobro, dakle...
{92278}{92310}Oprosti.
{92311}{92377}Ne. Moram iÊi.
{92414}{92499}Ali ako ne razgovaram s tobom,
{92501}{92563}radim gluposti.
{92624}{92682}Dobro je.
{92961}{93014}äto misliö?
{93016}{93067}Da, u redu je.
{93069}{93122}Samo u redu?|Da.
{93150}{93245}Dala sam Mitchu da to pogleda ugovor.|Misli da je u redu.
{93247}{93315}Dala si to Mitchu?|Kad?
{93317}{93374}Proöli tjedan, navratila sam|u njegov ured.
{93376}{93431}Boûe.|äto je?
{93450}{93496}Ne znam.
{93504}{93553}Ne svia mi se baö.
{93555}{93608}Mitch? Zaöto?|Tako je sladak.
{93625}{93698}Proöli tjedan sam neöto vidio,|na roendanskoj zabavi.
{93700}{93739}äto si vidio?
{93741}{93809}Nisam ti htio reÊi, ali...
{93821}{93916}Ulovio sam ga kako gnjavi|jednu konobaricu.
{93918}{93951}Mladu djevojku.
{93958}{93998}Stvarno?|Da.
{93999}{94065}Bio je agresivan i dirao ju je.
{94066}{94132}Bilo je odvratno.|Nisam htio niöta reÊi.
{94134}{94171}Jer ti je prijatelj.
{94173}{94229}Molim?|Bok Nicole, Mitch ovdje.
{94230}{94267}Bok, Mitch.
{94269}{94338}Mislio sam ako nemaö posla,
{94340}{94395}da odemo na kavu.
{94408}{94482}Sad mi ne odgovara.|Sluöaj.
{94491}{94601}éao mi je zbog onog neki dan.|Dopusti da objasnim.
{94603}{94673}Ne znam baö.|To je...
{94678}{94745}Imao sam teûak dan,
{94746}{94804}to bi mi mnogo znaËilo.
{94883}{94961}Nekoliko stvari ûelim pojasniti,
{94962}{95071}jer mislim da imaö|krivo miöljenje o meni.
{95073}{95137}Stvarno?|Odakle ti to?
{95138}{95210}Jedna pita od oraha i dvije kave.
{95211}{95299}Ne brini.|Kuma uvijek kuÊa Ëasti.
{95307}{95364}Ne ovdje.|Znam tko si.
{95366}{95421}Ja sam Avi.|Podrûavam öto Ëinite.
{95422}{95443}Hvala.
{95445}{95531}Lijepa si.|Ali bez uvrede, on je kralj.
{95533}{95593}Pijeö kavu i jedeö pitu|sa ûivuÊom legendom.
{95595}{95654}Hvala ti, ali ûelim platiti.
{95655}{95702}Tvoj novac ovdje ne vrijedi.
{95703}{95760}Veselim se svojoj prijavi|slijedeÊi semestar.
{95795}{95886}Nije li ovo otiölo predaleko?
{95887}{95962}»ujem da je jedan umro.|Je li istina?
{95979}{96050}Je. Ali bio je star.
{96052}{96120}I mislim da Êe obdukcija,
{96122}{96175}pokazati da je umro prirodnom smrÊu.
{96177}{96279}Da budem iskrena, nisi osoba|za koju sam te smatrala.
{96281}{96339}Ali u redu je.|Nema veze.
{96341}{96396}Mislim da jesam ta osoba.
{96398}{96485}Jer veÊ se dugo°nisam tako osjeÊao.
{96486}{96561}Zato napadaö mlade ûene?
{96563}{96605}äto?|Konobaricu.
{96606}{96679}Na roendanskoj zabavi.|Mark mi je ispriËao.
{96681}{96762}Samo malo.|Nisam niöta htio reÊi,  
{96763}{96841}ali Mark se ponaöao nedoliËno.
{96842}{96895}Nevjerojatan si.|Istina je.
{96897}{96940}Pogledaj tko je to.
{96942}{96982}Bok, Mitch.
{96983}{97016}Bok, Darcie.
{97018}{97089}Htjela sam te nazvati.
{97090}{97146}Ne ûelim da se brineö za mog tatu.
{97147}{97215}On niöta ne zna, to je super.
{97217}{97246}Njezin tata?
{97248}{97290}Da.|Da.
{97307}{97423}Nije to niöta.|Oni rade zajedno.
{97442}{97567}Moramo iÊi, organiziramo maturalnu veËeru.|Vidimo se.
{97569}{97591}Oprosti.
{97593}{97629}Bok.
{97647}{97697}Maturalna veËera?
{97699}{97759}Ovo mogu objasniti.
{97761}{97810}Sigurna sam da moûeö.
{97812}{97873}Moram iÊi.|Molim te, Ëekaj.
{97875}{97945}Ne, stvarno moram iÊi.
{98051}{98110}Hej. éenske.
{98112}{98158}Ne brini zbog nje.
{98160}{98236}Ljubav je pravi gad.
{99006}{99093}Dragi Mitch, ako drûiö ovo pismo,|sigurno veÊ znaö.
{99095}{99198}KuÊa je zatvorena.|Prozori, vrata, sve.
{99200}{99268}Mi smo u Comfort Innu, soba 112.
{99270}{99318}Volim te. Frank.
{99330}{99430}Zbog tih prekröaja, ne samo|da Êemo vam oduzeti kuÊu,
{99433}{99517}nego i studenti meu vama Êe biti|izbaËeni s faksa
{99517}{99592}zbog Ëlanstva u nedozvoljenom bratstvu.
{99595}{99684}PriËekajte da vam ovaj podatak sjedne.
{99789}{99865}Dobro. Vjerujte mi,
{99865}{99987}mjere koje je poduzelo studentsko vijeÊe|öokirale su me.
{100008}{100064}Ali na ûalost,|niöta ne mogu uËinit.
{100066}{100159}Hvala öto ste gledali.|Sretno i Bog blagoslovio Ameriku.
{100294}{100332}Ne moûe to uËinit!
{100335}{100384}Ovi igraju pokvareno.
{100405}{100484}Moram reÊi da me impresionirao.
{100486}{100518}IzbaËeni smo.
{100519}{100578}éivot mi je gotovo,|radit Êu u Crvenom jastogu.
{100581}{100671}Pa i radiö u Crvenom jastogu.|Da, ali samo privremeno.
{100673}{100735}DeËki.|Sluöajte.
{100737}{100844}Ovo je ozbiljna problem.|IzbaËen sam s faksa.
{100879}{100937}Ne znam öto Êu.|Mama Êe me ubiti.
{100939}{100991}Ma neÊe te ubiti.
{100994}{101072}HoÊe.|Ja sam prvi u obitelji koji studira.
{101075}{101201}Kad sam odlazio rekla je,|"Weensie, ako ovo zaribaö, ubit Êu te."
{101210}{101258}Pokazala mi je noû.
{101351}{101455}Mitch je pravnik.|On Êe ovo srediti.
{101457}{101496}Sve Êe biti u redu.
{101572}{101623}On je trebao glumiti Lukea Skywalkera.
{101626}{101688}Joö ûelite u bratstvo?
{101737}{101810}Cijeli semestar Ëekamo da nas to pitaö.
{101812}{101866}Dobro.|Trebam vaöu pomoÊ.
{101866}{101929}Nesluûbeno.|Obavite ovo i primljeni ste.
{101931}{101966}Razumijem, gospodine.
{101968}{102061}Walsh, nai kopiju studentskog zakona 7- A,
{102062}{102112}i odmah je faksiraj na ovaj broj.|Dobro.
{102114}{102170}Moram razgovarati s tobom.|Za pet minuta.
{102171}{102239}Booker, napravi dvije kopije ove peticije,|ovjeri ih,
{102242}{102303}i poöalji u Langley 34, i onda trebam...
{102305}{102386}Donald mi kaûe da ovi deËki|rade na arbitraûi.
{102388}{102465}Rekao sam ti da ûelim da rade|na pogodbi za Sunshine Square.
{102466}{102528}Taj sam posao juËer sklopio,
{102530}{102585}i sada mi oni pomaûu oko arbitraûe,
{102586}{102649}i bio ti zahvalan da me pustiö|da organiziram svoju ekipu,
{102650}{102725}i ne visi mi nad vratom|svaki puta kad neöto uËinim.
{102760}{102795}U redu.
{102798}{102846}Samo ûelim provjeriti|da li si na Ëelu svega.
{102848}{102882}Jesam.
{102884}{102937}Dobro. Nastavi tako.
{102938}{103012}Vidiö? Zato ga nazivaju kumom.
{103062}{103111}Obavite to.
{103178}{103280}Gospodo, imam dobre i loöe vijesti.
{103282}{103326}Malo sam istraûivao.
{103328}{103409}Ono öto je Pritchard uËinio,|tehniËki je nezakonito.
{103409}{103457}Imamo pravo na procjenu
{103460}{103524}prije nego odbiju naöu molbu.
{103525}{103619}Sad smo predmet certifikacijske inspekcije
{103622}{103657}koju su odredili Ëlanovi odbora.
{103658}{103689}Prokletstvo.
{103702}{103779}»ekaj malo, öto to toËno znaËi?
{103781}{103875}Prema zakonu faksa,|to je temeljiti pregled bratstva,
{103877}{103924}i naöeg doprinosa zajednici.
{103924}{103981}Gledaju pet kategorija:  
{103981}{104062}Znanost, sport, druötveni rad,
{104064}{104127}razgovor i ökolski duh.
{104135}{104205}Sretno svima.|Bilo mi je drago.
{104205}{104251}Vidimo se oko doma.
{104254}{104324}Zapravo sve nas provjeravaju.
{104326}{104397}O Ëemu to priËaö?|Ja niti ne studiram.
{104399}{104483}Tako je u zakonu.|Svaki Ëlan bratstva predmet je inspekcije
{104486}{104546}u svakoj kategoriji,|ukljuËujuÊi znanost.
{104548}{104618}Mitch, moûeö li malo doÊi?|Ne ûelim doruËak.
{104619}{104681}Ja se bavim zvuËnicima, ne testovima.
{104694}{104735}Nevjerojatno.
{104737}{104829}Kamo je nestala "potreba za bratstvom?"|Trebaju nas.
{104829}{104880}Faks je ionako precijenjen.
{104880}{104959}Izgradio sam Speaker City iz temelja|a jedva znam Ëitati. Stvarno.
{104961}{105057}Ovo je bila tvoja ideja,|i ti si me nagovorio na to,
{105059}{105107}i sad su ljudski ûivotu uniöteni.
{105107}{105167}Uniöteni? »iji ûivot je uniöten?
{105169}{105218}Da vidimo.
{105223}{105261}Plavi je mrtav.
{105263}{105310}Frank je rastavljen.
{105312}{105404}Ja sam izgubio kuÊu.|Nicole misli da sam kreten.
{105404}{105509}A devetero djece Êe izbaciti s faksa.
{105510}{105563}A ne ûeliö im ni pomoÊi.
{105893}{105993}HoÊemo li ovo brzo rijeöiti?|Propuötam 18 rupa u golfu.
{105995}{106063}Sto posto.|Napravio sam im zanimljive testove.
{106063}{106101}Ovo bi trebao biti zabavan dan.
{106103}{106163}Uûivat Êu izbacujuÊi ih iz doma.
{106166}{106188}Slaûem se.
{106222}{106317}Dobrodoöli na inspekciju debate.
{106346}{106404}Naûalost,
{106406}{106506}kapetan razgovorne ekipe|nije mogao doÊi.
{106509}{106598}Pa smo morali uzeti zamjenu za njega.
{106610}{106722}Dame i gospodo, pozdravimo|voditelja CNN- ovog Crossfirea,
{106725}{106809}slavnog politiËkog savjetnika|Raging Cajun,
{106811}{106852}gospodina Jamesa Carvillea.
{106966}{107009}Hvala.|Nemoj pljeskati.
{107011}{107088}Hvala vam, dekane Pritchard.|»ast mi je biti ovdje.
{107090}{107141}Tema broj jedan.
{107182}{107254}äto mislite o ulozi vlade
{107257}{107350}u podrûavanju inovacije|na polju biotehnologije?
{107370}{107427}Dekane, drago mi je öto te to pitali...
{107430}{107505}htio bih se ubaciti i odgovoriti,|ako smijem.
{107538}{107589}Samo navali?
{107589}{107637}Zaöto ne Ëeka lagano pitanje?
{107808}{107874}Nedavna istraûivanja su pokazala|da je opipljivih dokaza
{107875}{107938}za globalizaciju inovacije|vrlo ograniËen.
{107940}{108016}I rezultat toga je smanjivanje|trûiöta tehnologije.
{108018}{108076}Kao svjetski voa Amerika mora
{108078}{108130}mora dopustiti sistematsko|istraûivanje znanstvenicima.
{108132}{108227}Mislim da Êe uvijek biti potrebno|da imamo jasnu politiku o inovaciji
{108229}{108308}s naglaskom na razvoj ljudskih izbora.|Hvala.
{108415}{108446}Odakle ti to?
{108446}{108487}äto se dogodilo?|Zacrnilo mi se.
{108489}{108525}Bilo je super.
{108527}{108594}Ovo je bilo zanimljivo.|Hvala vam.
{108596}{108675}I vaö odgovor g. Carville?
{108677}{108772}Nemamo odgovor.
{108780}{108828}Bilo je savröeno.
{108905}{108985}Tako se to radi!|Tako se debatira.
{109234}{109271}Broj  12.
{109280}{109394}Koja od navedenih je opÊe|prihvaÊena grafiËka tehnika.
{109396}{109480}za odreivanje prvog pravila|sustavnih parametara?
{109498}{109601}Je li to, A, Harriotova metoda|rjeöavanja kocke?
{109614}{109682}B, Pitagorin pouËak?
{109685}{109785}Ili C, migracijska metoda|crtanja kvadratnih funkcija?
{109857}{109904}Harriotova metoda rjeöavanja kocke.
{109906}{109977}Odgovor je A, Harriotova metoda|rjeöavanja kocke.
{110128}{110168}Dobar test.
{110387}{110441}Dobro, Frank. UËinimo to.
{110468}{110504}Navali Harrisone!
{111451}{111497}To!
{111693}{111740}Idemo, pume!
{111822}{111865}O, ne!
{111911}{111978}Pomozite mi! U pomoÊ!
{112071}{112127}Dekane Pritchard, moûemo razgovarati?
{112129}{112167}Megan, imam posla.
{112169}{112232}Nisam se upisala na pravni|fakultet Columbia.
{112234}{112271}Kako straöno.
{112273}{112345}Rekli ste da Êete me ubaciti|u Columbiju ako ih izbacim.
{112348}{112375}Imaö pravo, rekao sam to.
{112377}{112426}Nitko na Columbiji nije Ëuo za vas.
{112429}{112459}O, Megan.
{112470}{112545}Ja sam svoj dio dogovora izvröila,|sad vi morate svoj.
{112547}{112603}Takvo je mito.|Znam öto je mito.
{112605}{112664}Stalno podmiÊujem ljude,|ali predomislio sam se.|Ovo je slobodna zemlja.
{112666}{112715}NauËila si lekciju.
{112805}{112840}K vragu!
{112865}{112959}éao mi je, izgubio sam prisebnost.|Koja sam ja budala.
{112961}{113040}Frankie, ne brini.|Skupit Êemo bodove, obeÊavam.
{113042}{113094}I koûa Êe ti ponovno narasti.
{113096}{113131}Oprosti.
{113134}{113185}Koliko nam je joö ostalo?
{113188}{113275}Jedno.|Frankova nesreÊa nas je unazadila.
{113277}{113372}Ali ako proemo u sportu,|uspjeli smo.
{113374}{113442}O tome ja priËam, deËki.
{113444}{113504}Do sada smo bili super.|Nastavimo tako!
{113506}{113598}Tako je!|Nitko vani ne smije prolupati.
{113599}{113678}Moramo ostati smireni!|Toliko smo daleko dogurali.
{113680}{113757}Mnogo moûemo izgubiti!|Samo ostati mirni!
{113758}{113861}Za zavröni test sam izabrao|muöku gimnastiku.
{113861}{113955}Sudionike za sva tri natjecanja|izabrat Êu ja sam nasumce
{113957}{113985}upravo sada.
{113987}{114042}Da vidimo.
{114044}{114079}Bernard.
{114079}{114147}Super. Vjeûba na tlu.
{114149}{114211}Frank? Moûe.
{114212}{114339}I za vjeûbu na konju, ne znam...
{114341}{114381}äto kaûete...
{114418}{114463}Ti.|Ja?
{114470}{114527}Da. Ima li problema?
{115513}{115559}Joö se drûim!
{115578}{115610}Drûim se!
{115710}{115762}Ovo je fiziËki nemoguÊe.
{115764}{115842}Ne brini.|Abdul Êe te primiti.
{115938}{115981}»ekamo, gospodo.
{115983}{116051}Samo se odrazi od daske koliko moûeö|i zatvori oËi.
{116053}{116096}Spreman?|Zabavi se.
{116098}{116161}Kreni!
{116322}{116351}Hajde!
{116682}{116745}Moj Boûe! To!
{117050}{117085}Hej, bio sam dobar.
{117142}{117220}»estitam.|Stvarno ste se potrudili.
{117220}{117247}Stvarno.
{117250}{117326}Ali imam loöe vijesti za vas.
{117328}{117376}Niste proöli.
{117409}{117490}O Ëemu to priËaö?|Imali smo 84%.
{117490}{117557}Da, imali ste 84 posto,
{117558}{117660}ali jedan od vas je dobio "0" iz|svake kategorije.
{117661}{117688}Tko?
{117690}{117773}Joseph "Plavi" Pulasky.
{117833}{117939}Plavi je mrtav.|Umro je prije dva tjedna.
{117941}{117998}Upisan je u vaö sluûbeni popis,
{118001}{118087}i te nule Êe vam srozati prosjek na 58%.
{118090}{118155}Sigurno se öaliö.
{118157}{118203}Bilo je to pravo iskustvo.
{118230}{118295}Sve Êe biti u redu, Frank.
{118308}{118387}Hajde, macane.|Nemam razloga za ûivot.
{118389}{118441}NaÊi Êemo ti jednosobni stan,
{118444}{118514}osovit Êemo te na noge,|moûda Êeö stanovati s Beaniejem...
{118514}{118555}To neÊe biti isto.
{118557}{118616}Niste uspjeli, zar ne?
{118617}{118687}Znaö öto?|PreporuËam ti da odmah odeö,
{118689}{118744}prije nego se neöto grozno dogodi.
{118746}{118788}Bojim se.|Oprosti, Mitch?
{118790}{118819}Prekidam neöto?
{118821}{118898}Megan, prekidaö.|Bilo bi super da odeö.
{118900}{118960}Mislim da Êe vas ovo zanimati.
{118968}{119050}Rekli ste da Êete me ubaciti|na Columbiju ako ih izbacim.
{119051}{119094}Rekao sam to.|Sluöajte...
{119095}{119178}Ja sam svoj dio dogovora izvröila,|sad vi morate svoj.
{119181}{119220}Znam öto je mito...
{119222}{119268}Znaö öto?|Daj mi...
{119293}{119338}Uhvati ga, Frankie!
{119402}{119438}Prolaz!
{119467}{119521}Ovim putem!|Uspori!
{119632}{119698}Pritchard, gotovo je.
{119707}{119802}Daj mi vrpcu.|Gotovo je.
{119804}{119833}Znaö gdje su ostali?
{119835}{119906}Ne znam, razdvojili su se.
{119907}{119942}äto radiö?|äto...
{119983}{120033}Stani. Stani.
{120156}{120216}Oprostite! Oprostite!
{120218}{120258}Gospodo... Boûe!
{120461}{120505}»ekaj, moje rame.
{120661}{120696}Napao me!
{120701}{120742}Svi ste svjedoci!|Napao me!
{120745}{120793}Frank!
{120891}{120937}Frank, jesi li dobro?
{120942}{121025}Mitch, tako mi je hladno.
{121082}{121131}Hajde, macane.
{121133}{121180}Mislim da vidim Plavog.
{121209}{121249}Izgleda boûanstveno.
{121250}{121309}Ostani sa mnom.|Dobro.
{121330}{121371}Bio sam dobar.
{121409}{121452}Bio si odliËan.
{122190}{122220}Bok.
{122249}{122319}Hej!
{122349}{122379}Kako si?
{122381}{122411}Dobro.
{122417}{122463}Dobila sam onaj stan.
{122465}{122517}Drago mi je. Super.
{122519}{122579}I imao si pravo u vezi Marka.
{122581}{122613}äto se dogodilo?
{122614}{122721}Uhvatila sam ga na djelu|i nije bilo lijepo.
{122750}{122808}Valjda sam mislila da se moûe promijeniti.
{122810}{122841}Ne znam.
{122879}{122929}Seliö se?
{122938}{123024}Da, idem u novu kuÊu,
{123027}{123075}daleko odavde.
{123076}{123124}äto je s vaöim malim bratstvom?
{123127}{123216}Idu u novu zgradu.
{123218}{123275}I da budem iskren,
{123276}{123355}viöe im ne treba Kum.
{123367}{123486}Nadam se da Êeö misliti|da sam super Ëak i bez ovoga.
{123488}{123537}Mislim da bih mogla.
{123538}{123578}Hvala ti.
{123592}{123650}Iako moram reÊi,
{123652}{123761}uvijek me zanimalo öto se unutra dogaa.
{123762}{123799}Je li?|Da.
{123864}{123942}Najam mi istiËe tek za 12 sati.
{123943}{124034}Rado Êu ti pokazati kuÊu.
{124042}{124068}Stvarno?
{124070}{124097}Da.
{124121}{124158}Moûda nakratko.
{124175}{124207}Super.
{124223}{124265}Sretan vam utorak svima.
{124266}{124353}Ovdje "Spremnik Frank"|na radiju Harrison Cougar, 88.6.
{124355}{124423}éelim pozdraviti Kuma.
{124426}{124496}Da nije bilo tebe,|danas ne bih bio ovdje, Mitch.
{124498}{124540}Najvjerojatnije bih bio mrtav.
{124545}{124623}S licem u praznom bazenu.
{124645}{124709}Brza poruka za buduÊu braÊu,
{124710}{124816}postoji nova kuÊu u domu,|bivöa kuÊa dekana Pritchard.
{124818}{124880}Svi se sjeÊate tog ludog gada.
{124912}{124990}Doite na otvorenje u subotu,
{124991}{125088}na Ëips, sokove i ponoÊnu jurnjavu.
{125090}{125150}Malo udesno. Joö malo.
{125163}{125214}Da, tako je dobro. Dobro je.
{125228}{125280}Dobro doöao, Bookeru.|Hvala, gospodine.
{125282}{125340}Walsh. Bravo.|Spremnik Frank.
{125342}{125386}Donesi mi joö jedno pivo?
{125388}{125417}Stvarno?
{125417}{125444}Odmah!
{125452}{125533}Odmah! Poûuri, jadni gade!
{126354}{126386}Sranje.
{127327}{127373}Ostani na golu.
{127375}{127434}Moraö ostati na golu.|Ne moûeö se öetati okolo.
{127435}{127489}Grozan si.|Moûeö li ostati izmeu stupova?
{127491}{127577}éelim koncentraciju, ûestinu,|i ûelim "1,2,3"!
{127578}{127605}Wooferi!
{127607}{127699}Krenite, pojedite ih!|Gladni ste! Progutajte ih!
{127702}{127799}Caleb, znaö öto moraö.|PriËali smo o tome!
{127802}{127850}Smiri se, vodimo ih za öest.
{127851}{127964}Sudac je kreten.|Da, Ëuo si me!
{127966}{128058}Broj Ëetiri igra laktovima|i neËije dijete Êe stradati.
{128059}{128093}äto?
{128094}{128138}Neka bude sluûbeno, budalo!
{128140}{128182}Neka bude sluûbeno!
{128202}{128275}Donesi ploËu.|Bit Êu u autu.
{128277}{128327}Pokaûi malo poötovanja prema se.|Hvala.
{128345}{128415}Je li to Spremnik Frank?
{128418}{128466}Bok, Heidi.
{128488}{128558}Kako si?|Stvarno sam dobro.
{128561}{128629}Bavim se oslikavanjem tijela.
{128629}{128674}Nisam znao.
{128674}{128701}OdliËno.
{128704}{128768}Izgledaö zdravo.
{128770}{128849}Hvala.|I ti.
{128850}{128897}Hvala ti.
{128898}{128979}»ujem da ste se ti i Marissa razveli.|Je li to istina?
{128980}{129026}Jest.
{129042}{129090}Jadnik.
{129109}{129146}Prireujem malu zabavu
{129147}{129186}kod mene sutra naveËer.
{129190}{129279}Samo nekoliko prijatelja s Interneta.|Navrati.
{129282}{129329}Stvarno?|Svakako.
{129350}{129384}Dobro. U redu.
{129385}{129460}ZvuËi ludo.|Vidimo se sutra naveËer.
{129530}{129562}Super.
{129563}{129598}To!
{129666}{129712}Vratio sam se!
{129714}{130768}{C:$0000FF}{y:ib} B & M |{C:$FF0000}{y:b} movies 
{130793}{132293}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/4789u|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
