{1}{1}25.000
{26}{176}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1408}{1481}U glavnoj ulozi:
{1650}{1750} IZBACIVA» 
{2270}{2322}U ostalim ulogama:
{3141}{3189}Moûe malo zlatne plastike?
{4003}{4044}Odjebi od njega!
{4323}{4378}Gospodo, mislim kako je | vrijeme da odete.
{4390}{4473}Sve u redu, samo se | malko zabavljamo.
{4491}{4537}éalim...
{4847}{4879}U redu, Daltone.
{4890}{4930}Uvijek sam te ûelio iskuöati.
{4945}{4985}Mislim da te mogu srediti.
{5010}{5038}Vani.
{5144}{5211}Evo nas, hajde!
{5308}{5376}Stoko, kamo Êeö?!
{5380}{5421}KretenËino!
{5794}{5849}Glazba:
{6368}{6458}Mogu li s vama malo | porazgovarati? Dalton, ne?
{6497}{6523}Ne poznajem vas.
{6550}{6623}Ja sam Frank Tilghman.
{6671}{6748}Imam mali klub izvan Kansas | Cityja, 'Par dvojki'.
{6870}{6943}NekoÊ je to bio lijep posliÊ.
{6951}{7036}Sad po zatvaranju metu | oËi s poda.
{7077}{7145}No, doöao sam do malo novca.
{7183}{7231}éelio bih bolje ûivjeti.
{7268}{7341}Trebam nekoga da mi | pomogne poËistiti mjesto.
{7363}{7397}Treba mi najbolji.
{7421}{7500}Wade Garrett je najbolji. | - Wade Garrett stari.
{7513}{7584}Ipak je najbolji. | - éelim vas.
{7760}{7835}5000 unaprijed, 500 na noÊ, | gotovina.
{7838}{7881}Vaöi su svi | bolniËki troökovi.
{7914}{7954}S time mogu ûivjeti.
{8000}{8059}Ja sam öef... posve.
{8094}{8144}Kad posao bude gotov, idem.
{8149}{8203}Ovdje imam vaöu | avionsku kartu.
{8221}{8256}Ne letim.
{8306}{8335}OdveÊ opasno.
{8372}{8431}Kada vas mogu | oËekivati...? - Nemojte.
{8436}{8471}DoÊi Êu.
{8530}{8581}Dalton? Dobro si?
{8585}{8659}Samo ogrebotina. | Usput, Oscare...
{8665}{8731}'Bandstand' je tvoj. | - Sto to treba znaËiti?
{8742}{8775}Odlazim odavde.
{8804}{8834}Sjajno!
{8915}{8982}Znate, mislio sam | da Êete biti...
{8994}{9022}...veÊi.
{9772}{9855}Izgledam ti kao nosaË? | - Zadrûi, tvoj je.
{10580}{10656}DOBRO DOäLI U JASPER
{10999}{11037}PAR DVOJKI
{11060}{11156}Scenarij:
{11738}{11791}I ne vraÊaj se, | mudonjo!
{11840}{11905}Reûija:
{12073}{12117}Daj pravi bend!
{12617}{12652}Steve!
{12673}{12717}Jebi ih, braÊa su.
{12784}{12864}Znaö, gotov sam u 2.
{12867}{12961}Rado bih tebe zgotovio | pola sata nakon toga.
{13103}{13151}Prvo dame, sroljo!
{13274}{13306}Kvragu!
{13619}{13692}Isuse, ne ovdje! | Za mnom u zahod.
{14094}{14138}Treba mi piÊe.
{14405}{14470}Votka s ledom. | - Vrijedi, mila.
{14505}{14620}Votka s ledom! | äto kaûeö da se ti i ja
{14623}{14681}taknemo bradavicom | o bradavicu?
{14711}{14771}Ja to mogu i bez tebe.
{15016}{15066}Gonite ga van!
{15183}{15261}Ne budeö li pio, | i ti letiö van.
{15388}{15499}Ne daj se smetati. Morgan je | roen kao öupak i samo raste.
{15539}{15655}Ja sam Carrie Ann. | Ako ti iöta zatreba,
{15665}{15720}samo mi javi.
{15844}{15874}Imaö li ime?
{15960}{16007}Pa, kako glasi?
{16087}{16124}Dalton.
{16172}{16273}Sranje, Ëula sam ja za tebe.
{16284}{16341}Carrie Ann! äto Ëekaö, BoûiÊ?!
{16359}{16437}MiËi se! - Kuö! Eto me...
{16441}{16479}Isuse Kriste!
{16570}{16725}ZA DOBAR FUK | ZOVI 555-7617
{17117}{17152}Goni ga van.
{17307}{17383}Misliö da je ovo | staraËki dom?
{17586}{17706}VraÊamo se za desetku. | Treba napumpati ûilu.
{17711}{17778}PlaÊen si da sviraö! Sviraj!
{18503}{18535}Hvala, stari.
{18539}{18600}PriliËno dobro sviraö | za slijepoga bijelca.
{18612}{18671}A ja mislio da si veÊi.
{18704}{18770}Daltone, kako si? | Dobro te vidjeti!
{18771}{18874}DeËki i ja smo Ëuli | da stiûeö u grad.
{18878}{18961}Stari, ovaj öekret je gori | od one rupe u Daytonu.
{18963}{19065}Stvarno? | - Grdno ti je ovdje.
{19102}{19171}Svake noÊi krv na podu.
{19175}{19253}Hank, znaö li tko je to? | - Tko? - Dalton!
{19562}{19640}Taj momak na kraju | öanka je jebeni Dalton!
{19699}{19752}Jednom je ubio kita.
{19775}{19826}IöËupao mu grkljan.
{19850}{19889}Kenjaö!
{19922}{19997}äto trebaö, stari? | - Kavu, crnu.
{20111}{20188}Jesi li vidio | ljepöe stajaliöte?
{20201}{20236}Fino, a?
{20240}{20356}Evo öto... za 20 komada | moûeö ih poljubit.
{20361}{20446}Zezaö se? - 10 za pusu. | Ovdje i sad.
{20472}{20521}Hajde... daj!
{20678}{20731}10 pusa. Hajde!
{20994}{21074}Stari, öto radiö? | Poljubit Êeö ih, ili ne?
{21089}{21127}Ne mogu!
{21136}{21237}Kako misliö 'ne moûeö'? | - Nemam 20 komada!
{21419}{21453}Sranje!
{21458}{21504}TuËnjava!
{21630}{21668}Prekidaj!
{22321}{22362}Pasji skote!
{22577}{22604}Gade!
{23732}{23793}Jebiga. Ima li tko zrcalo?
{23854}{23900}Sranje!
{23988}{24102}A da nam kaûeö öto se jebiga | zbiva. PomoÊi Êeö, ili ne?
{24120}{24161}Javit Êu vam.
{24163}{24253}Znaö, Ëuo sam da imaö jaja | prevelika za smetlarska kola.
{24255}{24306}Ali meni baö | ne izgledaö neöto.
{24363}{24398}Miöljenja se razlikuju.
{24530}{24562}Cody?
{24566}{24592}Kasnije.
{24595}{24639}Stari, Ëuvaj se.
{24754}{24812}Taj Dalton... | kako glasi priËa?
{24814}{24895}Jebi se s njime | i zapeËatit Êe ti sudbinu.
{24901}{24990}Zasad mi nije | pokazao ni govna.
{25543}{25582}Bogme ide.
{25734}{25782}Rade? - Bogme.
{25997}{26023}Uzet Êu.
{27474}{27517}Dobro jutro.
{27532}{27591}Vi iznajmljujete sobu?
{27662}{27696}Hajde.
{27864}{27922}Poöten? - Jesam.
{27952}{28027}OËekujeö da ti vjerujem? | - Ne, gospodine.
{28681}{28713}Kvragu!
{29410}{29505}Kunem se da to radi | samo da me raspizdi!
{29508}{29563}Tko to? | - Brad Wesley.
{29769}{29815}Voliö konje, je li?
{29818}{29862}Oni vole mene.
{29870}{29932}Ne bi ih krao? | - Ne, gospodine.
{29973}{30056}Zvati mene gospodinom je kao | staviti dizalo u konobu.
{30061}{30130}Ne spada. Ja sam Emmet.
{30146}{30174}Dalton.
{30506}{30535}Pa, öto misliö?
{30586}{30617}Uzet Êu.
{30700}{30775}20 ljudi je lani | gledalo tu sobu.
{30778}{30819}Nema telefona, | nema televizora.
{30822}{30914}Nema air-conditiona, | ne trpe mirise prirode.
{30917}{30999}Nitko je nije htio. | Zaöto ti da?
{31015}{31076}Valjda ste za me | odveÊ uvjerljivi.
{31100}{31176}Ne radi se o novcu, znaö. | Ali ako ti ne naplatim,
{31179}{31264}Prezbiterijanci Êe | moliti za moju propast.
{31265}{31326}Kako ti se Ëini | 100 dolara mjeseËno?
{31338}{31374}Sjajno.
{31378}{31431}Moûeö toliko priuötiti?
{31443}{31512}Ako vas zadrûi u dobrim | odnosima s crkvom.
{31514}{31580}Nije Ëudo kako novac | upravo to i Ëini.
{31636}{31729}Ovo... ovo je novi | 'Par dvojki'.
{31739}{31804}Uloûio sam u to | puno para i vremena.
{31808}{31916}Da zaötitim ulaganje, najmio | sam najboljeg 'miritelja'.
{31933}{32021}Odsad je on öef sveg | posla u baru. Sto on kaûe,
{32023}{32066}...vrijedi!
{32080}{32113}Daltone...
{32308}{32342}Morgane, odlaziö.
{32368}{32461}äto priËaö, jebiga? | - Nemaö pravu Êud za zanat.
{32475}{32546}Seronjo! äto da radim?!
{32551}{32610}Uvijek je tu koledû | za brijaËe.
{32700}{32744}Ti si mrtav Ëovjek.
{33033}{33122}I ti ideö. Ovdje prodajemo | cugu, ne drogu.
{33178}{33212}Hvala!
{33329}{33368}Dila li joö tko?
{33422}{33538}Iskreno vam kaûem... | ili po mome, ili cesta.
{33576}{33631}Tko ûeli u öetnju, | nek' krene odmah.
{33883}{33920}U redu.
{33991}{34084}Ljudi koji se stvarno ûele | zabaviti neÊe u klaonicu.
{34088}{34167}A ovdje imamo skroz | previöe svadljivaca.
{34169}{34240}Previöe 40-godiönjih | maloljetnika,
{34242}{34362}kriminalaca, pilulaöa, | uzdanika u suvremenu kemiju.
{34364}{34461}To Êe se promijeniti. | - Bogme dobro zvuËi.
{34463}{34575}Ali veÊinu koja dolazi | ne moûemo srediti 1 na 1.
{34577}{34658}Ni dvojica na jednog. | - Ne brini se.
{34662}{34730}Treba samo slijediti | 3 jednostavna pravila.
{34734}{34812}Prvo: Nikad | ne podcjenjuj protivnika.
{34816}{34871}OËekuj neoËekivano!
{34885}{34997}Drugo: Izai. Nikad | ne poËinji niöta u baru,
{35000}{35091}osim ako nije posve | neophodno. TreÊe:
{35120}{35183}Budi pristojan. | - Ma, daj!
{35210}{35287}Ako ti se tko unese u lice | i kaûe ti da puöiö kurac,
{35290}{35344}hoÊu da | budeö pristojan.
{35411}{35459}Zamoli ga da ide.
{35462}{35541}Ali budi pristojan. | Ako neÊe otiÊi, izvedi ga.
{35544}{35606}Budi pristojan. | Ako ga ne moûeö izvesti,
{35609}{35712}pomoÊi Êe drugi, | ali obojica budite pristojni.
{35738}{35817}éelim da upamtite | kako je to posao.
{35842}{35890}Niöta osobno.
{35929}{36037}ReÊi ti da puöiö | kurac nije osobno? - Nije.
{36040}{36151}Glagol i imenica s namjerom | a pobude odreeni odaziv.
{36171}{36226}äto ako mi netko | mamu nazove kurvom?
{36254}{36295}Je li?
{36379}{36501}éelim da budete pristojni | dok ne svane trenutak
{36504}{36552}da ne budete pristojni.
{36557}{36697}Kako da znamo kada je to? | - NeÊete, ja Êu vam reÊi.
{36724}{36787}Vi ste izbacivaËi, | ja sam 'miritelj'.
{36789}{36887}Trebate mi samo paziti lea, | i jedan drugome,
{36898}{36939}i iznijeti smeÊe.
{37376}{37469}Searsova kreditna kartica! | - Beverly, Anges!
{37475}{37517}Sve u redu, | moje prijateljice.
{37520}{37572}Dalton je rekao... | - U redu, vjeruj mi.
{37720}{37768}Olovnu ili bezolovnu? | - Olovnu.
{38146}{38189}Hank!
{38336}{38408}Stari, uËini mi uslugu | i skini je. Moûe?
{38414}{38461}Neka pleöe!
{38651}{38684}Hajde, mila.
{38778}{38820}Hajde, majku ti!
{39066}{39133}Ispratite gospodina do vrata.
{39176}{39224}Jesi li vidio to sranje?
{39460}{39497}Tko je taj momak?
{39552}{39647}Dobar je. Ma baö je dobar.
{39683}{39740}Ime je... Dalton.
{39901}{40001}Bit Êeö mi stalna subota | naveËer, mila...
{40018}{40067}Mislio sam na tebe...
{40196}{40236}Steve!
{40277}{40332}Pripadaö povijesti.
{40338}{40380}Imam odmor.
{40394}{40431}Ostani na njemu.
{40464}{40500}Sranje!
{40578}{40641}Razvio si priliËnu | slobodnu inicijativu.
{40669}{40699}äto?
{40723}{40815}Svakih pola sata makneö bocu, | dereö kasu za 6 piÊa po boci.
{40816}{40887}Pivo na Ëaöe, | jedna na svakih deset.
{40940}{41026}Mislim da vas stoji | 150 na noÊ.
{41049}{41072}Pa?
{41102}{41182}Smatraj to pozdravnom | plaÊom. Put pod noge.
{41248}{41358}Nisam tebe Ëuo da to kaûeö. | - Kaûem ti sada.
{41383}{41413}Siguran si?
{41465}{41495}Odlazi.
{41771}{41848}Bila je to dobra noÊ. | Nitko nije umro.
{41906}{41959}Postat Êe gore | prije nego postane bolje.
{43883}{43952}Volim ovoga momka. | Zar nije sladak?
{43957}{43992}Mio...
{44174}{44229}Dalton!
{44656}{44732}'Jutro. Donijela | sam ti doruËak.
{44784}{44817}Sranje.
{45131}{45171}Kako si me naöla?
{45183}{45264}Nije bilo teöko. | Mislim... znaö...
{45385}{45436}äto si to uËinio sinoÊ?
{45484}{45587}Kako to misliö? | - Otpustio öankera Pata.
{45615}{45650}Krao je.
{45660}{45711}Nisi to smio uËiniti, Daltone.
{45778}{45808}Zaöto?
{45814}{45886}Nisi smio, to je sve.
{45932}{46003}Evo ti... doruËak.
{46046}{46073}Hvala.
{46138}{46182}Moj Boûe!
{46227}{46300}U Ëemu je vic? | - Nema vica.
{46316}{46367}No mislim da gledam | mrtvoga Ëovjeka.
{46407}{46469}Kamo god poöao | Ëujem isti vic.
{46485}{46550}Neöto mi kaûe | da ga sam vuËeö za sobom.
{48079}{48162}Novi vjetrobran stajat Êe | vas viöe od te starudije.
{48164}{48287}Savjetujem da ga bacite. | - Drag mi je. NaruËite.
{48291}{48386}Potrajat Êe par dana. | Antenu vam mogu dati odmah.
{48505}{48575}Ti si iz 'Para dvojki'? | - Jesam.
{48618}{48689}Nekako sam mislio | da Êeö svratiti.
{48692}{48798}Preko narudûbenice? | - Ne, plaÊam kad stigne.
{48809}{48854}Dalton. | - Red Webster.
{48857}{48932}Koliko Êete biti u gradu? | - Ne baö dugo.
{48936}{49028}To sam i ja rekao pred 25 | godina. - Da? Sto je bilo?
{49031}{49115}Oûenih ruûnu ûenu. | Nikad to nemoj uËiniti.
{49117}{49171}To ti iscrpi svu snagu.
{49179}{49285}No, ostavila me. | Naöla ruûnijega od sebe.
{49303}{49362}Takav je ûivot. | Tko da ga objasni?
{49369}{49407}5 dolara.
{49475}{49567}Zaöto ste ostali? | - Svidjelo mi se.
{49771}{49822}Zdravo, Brad. - Red...
{49881}{49934}Brad Wesley. | - Dalton.
{49963}{50003}Radi u 'Paru dvojki'.
{50029}{50107}Sjajno, valjda Êete | poËistiti to mjesto.
{50109}{50161}Gadan element vlada ondje.
{50169}{50231}Ako ikako mogu pomoÊi...
{50253}{50286}Hvala, Red.
{50508}{50558}Dakle, Red...
{50570}{50647}...krasan dan. | - Bio.
{53252}{53314}Nevolje? | - Nema nevolja.
{53317}{53384}Samo mala pogreöka. | - A to je?
{53422}{53455}Moj posao.
{53495}{53584}Nije ti jasno, je li? | - Zaöto mi ne objasniö?
{53610}{53687}Ja Êu ti objasniti! | - Kuö, seronjo.
{53690}{53805}G. Tilghman se predomislio. | To je sve öto trebaö znati.
{53826}{53896}Ne, bojim se da Êu morati | znati malko viöe.
{53900}{54051}G. Tilghman je moûda vlasnik, | no piÊe snabdijeva Brad Wesley
{54054}{54145}Pat McGurn radi za | g. Wesleyja, svoga ujaka.
{54147}{54241}Ne za g. Tilghmana. | - Vidiö, ja ostajem.
{54243}{54302}A ti ideö! | - Stvarno?
{54316}{54356}ToËno!
{54366}{54425}Hajde, Daltone. Ti i ja.
{54429}{54463}Odmah!
{54502}{54607}äto je, pizdo kukavna? | »ega se bojiö? Mene?
{54633}{54694}Je li, bojiö se potuÊi | sa mnom?
{54698}{54739}Veliki, zli Dalton!
{54749}{54791}éeliö li pusicu?
{54946}{54981}Isuse Kriste!
{55919}{55967}Ustani!
{56191}{56243}Ustani!
{56715}{56760}Ja sam dr. Clay.
{56861}{56924}Kako se to zbilo? | - Prirodni uzroci.
{56943}{56988}Izgleda kao rana od noûa.
{57002}{57035}Kako rekoh...
{57126}{57192}IzbacivaË? | - 'Par dvojki'.
{57215}{57299}Zgodno mjesto. | Salju mi puno posla.
{57311}{57397}Nadam se da Êu to | promijeniti. - Posve sami?
{57511}{57599}G. Dalton, moûete dodati | 9 spojnica svome kartonu
{57602}{57675}od 31 prijeloma kostiju, | 2 rane od metka,
{57678}{57750}9 uboda i 4 vijka | od nerajuÊeg Ëelika.
{57753}{57811}Jasno, to je procjena. | Dat Êu vam lokalnu.
{57814}{57852}Ne, hvala.
{57864}{57951}Uûivate u boli? | - Bol ne peËe.
{57965}{58046}VeÊina mojih pacijenata | ne bi se sloûila.
{58209}{58278}Uvijek nosite lijeËniËki | karton sa sobom?
{58349}{58388}ätedi vrijeme.
{58422}{58507}U kartonu stoji da imate | diplomu njujorökog. Iz Ëega?
{58513}{58550}Filozofija.
{58615}{58709}Neka posebna disciplina? | - Ne baö.
{58728}{58806}»ovjekova potraga | za vjerom. To sranje.
{58837}{58912}Pronaöli kakav odgovor? | - Ne previöe.
{58934}{59007}Kako takav momak | da zavröi kao izbacivaË?
{59010}{59063}Valjda sreÊa.
{59402}{59467}Lijep rad. | Dobri Ëisti öavovi.
{59470}{59512}Hvala.
{59541}{59592}Jeste li kad dobili borbu?
{59599}{59649}Nitko nikada ne pobijedi.
{59816}{59869}Eto... - Hvala.
{59921}{59956}»ujte...
{60026}{60141}Biste li kad svratili | u 'Dvojku' na kavu, ako...
{60144}{60199}Ako se zateknem | u susjedstvu?
{60355}{60442}Znate, mislila sam da Êete | za takav posao biti veÊi.
{60489}{60540}Boûe, to joö nikada | nisam Ëuo.
{61794}{61868}Krivo sam objasnio? | U tome je stvar?
{61871}{61985}Ne, öefe, niste. - Pat je | slabe grae, to znate.
{61988}{62040}Zato radi kao öanker.
{62043}{62135}On je sin moje jedine sestre. | Ako nema mene, koga Êe?
{62140}{62205}A ako nema mene, | vi ste tamo.
{62235}{62289}Trebao sam poslati | tebe, Jimmy.
{62337}{62407}Jedan od vas duguje ispriku. | Vama prepuötam da odluËite
{62409}{62467}koji Êe reÊi 'ûao mi je'.
{62532}{62595}éao mi je, öefe. | - Oprostite...
{62599}{62643}Vjerujem ti, Tinker.
{62668}{62738}Ali tebi, O'Connor, | nekako ne vjerujem.
{62742}{62824}Bolje pokuöaj opet. | Neöto ne podnosim,
{62827}{62878}a to je neiskren Ëovjek. | - éao mi je, öefe.
{62880}{62935}Gadi mi se kad Ëovjek | ne priznaje pogreöku.
{62938}{63008}Kunem se Bogom, öefe... | - Gadiö mi se, O'Connor!
{63011}{63062}Znaö zaöto? | - Ne, zaöto?
{63147}{63224}Jer krvariö. | Previöe krvariö.
{63228}{63288}Sve zaprljaö krvlju.
{63340}{63417}Slab si. | Ne moûeö otrpjeti bol!
{63498}{63560}Hajde... ustaj.
{63564}{63607}Bit Êe ti dobro.
{63659}{63689}Pomozite mu!
{63816}{63884}Bit Êe ti dobro. Znaö zaöto?
{63908}{63950}Jer si mi drag.
{64063}{64115}Gonite to govno odavde.
{64329}{64399}Posao nije posao kad se | zabavljaö! - éivot je dobar.
{64954}{64991}Isuse...
{65051}{65084}Red?
{65180}{65257}äto je bilo? OpljaËkali te? | - Svaki tjedan.
{65521}{65587}äto uzima? | - Tko?
{65594}{65627}Brad Wesley.
{65732}{65846}10 posto, za poËetak. | Sve je toboûe zakonito.
{65849}{65923}Osnovao je Druötvo | za unapreenje Jespera.
{65926}{65985}Pripada mu sav posao u gradu.
{66026}{66067}Svi plaÊaju?
{66122}{66170}Ima li drveni konj | drveni pimpek?
{66602}{66651}Napad!
{66716}{66802}Polako, Rambo! Znam da ûeliö | spasiti svijet od komunjara,
{66806}{66872}ali morat Êeö to | obaviti odavde, stari.
{66893}{66937}äpricaj ga!
{67042}{67089}Garrett!
{67093}{67144}Neki momak po imenu Dalton!
{67224}{67263}äto se zbiva, mijo?
{67266}{67313}Kako si, stari?
{67318}{67379}Sranje, mali, med i mlijeko.
{67382}{67460}Da mi je bolje, sam sa sobom | ne bih mogao ûivjeti. Ti?
{67463}{67581}Dobro sam. - I trebao bi biti | koliko zaraujeö.
{67585}{67722}äto se zbiva u Jasperu? | - Znaö; novi grad, ista priËa.
{67783}{67892}»uj, jesi li kad Ëuo | za nekog Brada Wesleyja?
{67896}{67979}Ne bih rekao. Imaö nevolja?
{68008}{68070}Niöta na öto nisam navikao.
{68072}{68126}No Ëudo je na öto se | sve moûeö naviÊi.
{68129}{68241}Da, priËaj mi. | Tu iznad zahoda piöe:
{68244}{68318}'Nemoj pojesti veliku | bijelu gumu za ûvakanje'.
{68396}{68442}Drû' se, mali.
{68464}{68546}Moram iÊi. | Vidimo se kasnije.
{69363}{69448}Zaöto me ne pogledaö u oËi, | Dalton? - Sramim se.
{69466}{69529}Bi li te zaprepastilo da | kaûem: Hajdemo se do mene
{69548}{69581}...jebati?
{69643}{69680}NeÊe te ubiti.
{69715}{69778}Znaö, moûda ti se | Ëak i svidi.
{69816}{69867}Poûeli laku noÊ, Denise.
{70121}{70169}Pusti me!
{70790}{70850}Nisam znao da moûe pjevati.
{71000}{71041}Desna Ëizma!
{71123}{71152}Vidim.
{71272}{71317}éalim, zatvoreni smo.
{71320}{71428}äto onda rade ovi ljudi? | - Piju i zabavljaju se.
{71464}{71500}Zato smo mi ovdje.
{71541}{71585}Preglup si da bi se zabavljao!
{72142}{72204}Ispraöi mu tur!
{72774}{72810}Pasji skote!
{72849}{72895}Daj mi najveÊeg momka | na svijetu.
{72899}{72956}Smoûdi mu koljeno | i pada kao kamen.
{73331}{73389}Traûite nekoga? | - Vas.
{73983}{74039}Uvijek ste bolji od njih?
{74080}{74155}PriliËno. - Nikad | vas nisu oborili?
{74171}{74198}Ne.
{74215}{74293}Ne baö. | - Kako to objaönjavate?
{74369}{74477}Oni öto traûe nevolje nisu | problem onome tko je spreman.
{74481}{74535}Mislim da je oduvijek tako.
{74691}{74794}Netko to mora raditi. | - Netko mu mora platiti.
{74847}{74892}Moûete to biti i vi.
{74994}{75043}Bolje da vas odvedem kuÊi.
{75058}{75144}Nastavim li priËati, | pomislit Êete da sam drag.
{75157}{75205}Znam da niste.
{75281}{75349}Uskoro Êu toj propalici | poËeti naplaÊivati najamninu.
{75451}{75492}NoÊaönja.
{76044}{76106}Vaö klub oboûavatelja? | - Odani su.
{76301}{76356}Bogme vodite neki | ûivot, Daltone.
{76415}{76461}OdveÊ ruûan za vas.
{76498}{76530}Nisam to rekla.
{77107}{77145}Vidimo se.
{78082}{78132}Svuda te traûimo.
{78275}{78349}G. Wesley te ûeli vidjeti. | Hajdemo.
{78561}{78592}Poslije vas.
{79379}{79441}Dalton! 'Krvavu Mary'?
{79485}{79533}DoruËak? | - Ne, hvala.
{79547}{79576}Kako ûelite.
{79624}{79664}IskljuËi to sranje!
{79771}{79807}Ne mogu sluöati to govno, | nema srca.
{79807}{79828}Ne mogu sluöati to govno, | nema srca.
{80045}{80126}Moj djed. | - Izgleda vaûan Ëovjek.
{80151}{80188}Bio je öupak.
{80234}{80393}Ali ti... ti si mudar | momak. Nisi odveÊ realan.
{80417}{80516}Kriste, isti sam kao ti. | Uspeo sam se teöko.
{80519}{80562}S ulica Chicaga.
{80564}{80638}Kad sam doöao amo nakon | Koreje, nije bilo niËega.
{80641}{80696}Doveo samo ovamo | trgovaËki centar.
{80699}{80763}'7-11', 'Photomat'.
{80768}{80887}Kriste, J.C. Penny dolazi | radi mene. Pitaj kog bilo.
{80939}{81016}Obogatili ste se | na ljudima iz ovoga grada.
{81044}{81137}Joö kako! A joö Êu i viöe.
{81192}{81274}Vjerujem da na zemlji | svi imamo neku svrhu.
{81277}{81363}Sudbinu. Vjerujem u sudbinu.
{81366}{81479}Ona mi govori | da uzimam öto je moje.
{81483}{81561}Ali, Kriste, tebe plaÊaju | da mlatiö ljude.
{81564}{81626}Reci mi da ti se | to ne svia. Jasno!
{81628}{81689}Ne bi bio Ëovjek | da nije tako.
{81812}{81931}Daltone, imam | bratiÊa u Memphisu.
{81935}{82006}Kaûe mi da si ondje | ubio Ëovjeka.
{82009}{82078}Kaûe da si na sudu tvrdio | da je bilo u samoobrani.
{82078}{82082}Kaûe da si na sudu tvrdio | da je bilo u samoobrani.
{82087}{82157}Ali ti i ja znamo | da nije bilo tako, je li?
{82211}{82277}Polako, polako...
{82384}{82507}Reci... da sam vlasnik | bara i ûelim ga oËistiti,
{82520}{82577}koliko bi stajalo | da doeö raditi za mene?
{82801}{82836}Nema tog novca.
{85190}{85284}Ernie, kako ide? | - Ponestaje viskija.
{85343}{85449}Napokon naËinih od mjesta | öto ûelim, i nestane cuge.
{85454}{85519}Zvao sam sve dobavljaËe | koje znam.
{85541}{85631}Zaöto ne isporuËuju? | - Wesley.
{85649}{85685}Ernie, daj mi telefon.
{85757}{85808}Ja Êu to srediti.
{86246}{86344}»ujem da si novi maröal | u gradu. - Krivo Ëujeö.
{86416}{86459}Gle rupu.
{86762}{86797}Tu ûiviö?
{86813}{86823}Tamo gore.
{86823}{86835}Tamo gore.
{86835}{86848}Tamo gore.
{87323}{87405}Mirno je, a konji me | upozore ako tko dolazi.
{87424}{87464}Svia mi se.
{88788}{88876}Vidio sam tvoju sliku kod | Reda Webstera. - Ujak mi je.
{88905}{88950}Dragi starac.
{88965}{89079}Podigao me poöto su moji | umrli. Zato sam se vratila.
{89084}{89141}Sad pazimo jedno drugo.
{89178}{89267}I zaöto se nikad nisi | udavala? - Jesam.
{89300}{89362}äto je bilo? | - Nije upalilo.
{89370}{89466}Zaöto? - Valjda sam | izabrala krivoga.
{93679}{93715}Little Rock.
{93733}{93803}Sve Êe te boljeti | kad budeö stariji.
{93805}{93914}Moûeö postati bogalj | ako ne usporiö. - Da, kaûu.
{93932}{94031}VeÊ to znaö? - Ne, | samo velim 'kaûu'.
{94210}{94254}Kamo Êeö odavde?
{94375}{94411}Ne znam.
{94440}{94525}Mogao bi ostati. Kad bi htio.
{94651}{94690}Ne bih rekao.
{95825}{95855}»ekajte.
{96015}{96090}Imaö ûenu gore? | - Da.
{96094}{96177}Ne drûi mi prodike, | Gospode. Kamo je poöla?
{96179}{96267}Vratit Êe se. - Ako si | mudar, ulogorit Êeö se.
{96271}{96348}Katkad nisam mudar | koliko bih htio.
{96353}{96439}Nikad ne znaö, moûda Êe | biti mudra za oboje.
{96601}{96644}Zdravo, Dal.
{96646}{96692}Evo ga!
{96803}{96913}Cody! - äto je, bratac? | - Niöta veliko.
{96926}{96977}Ja tako ne Ëujem.
{96986}{97127}PriËa se da se zabavljaö | s Elizabeth Clay. - Pa?
{97145}{97248}Znaö li tko je za nju | bio zapeo? Brad Wesley.
{97296}{97421}Kako sam Ëuo, ona je otiöla | iz grada, a on poöaöavio.
{97476}{97521}Mali je ovo grad.
{97588}{97627}Doöao kamion!
{97706}{97790}Jasno, to su tek | glasine. - Hvala.
{98414}{98462}'Par boljki'.
{98882}{98963}Vrati to. Bar ne radi.
{98988}{99033}Sve u redu, Jime. | Poi na odmor.
{99246}{99298}Mogu li vas Ëastiti piÊem?
{99347}{99380}»ini se ne.
{99803}{99870}Radi li tu neki mali | ûgoljo po imenu Dalton?
{99931}{100009}Straga je, vani. | - Znam ja tebe.
{100057}{100111}NatoËi mi pivu. VraÊam se.
{100179}{100228}Kako ti se ovo svia, Kung Fu?
{100266}{100307}Kako ide, mijo?
{100332}{100399}Gledaj svoja posla, tata!
{100539}{100646}Ti bi se tukao, kastratu? | - Pimpek ti neÊu pokazivati.
{100753}{100792}Sranje!
{100795}{100840}Vraöki kako boli, ne?
{101548}{101624}Imao sam sve | pod nadzorom. - Znao sam.
{101657}{101728}Drago mi je öto te | vidim. - I meni.
{101760}{101819}Gospodo... Wade Garrett.
{101837}{101879}Jebote...
{101888}{101926}Baö tako.
{101984}{102041}Morgane, baö lijepo | öto te vidim.
{102127}{102234}Kamo Êemo sad, jebiga? | - éelim da upoznaö nekoga.
{102576}{102640}Nisi li rekao da si dobro? | - OdliËno.
{102753}{102801}Znao sam, jebiga.
{103016}{103187}1975., Albuquerque. Snaöla | me boca 'Jack Danielsa'.
{103193}{103281}Zajebavao sam se ondje | gdje nisam smio.
{103284}{103379}Bio sam jako pijan. | Malome razbili glavu.
{103397}{103442}Ti imaö oûiljak.
{103450}{103562}Pokazat Êu ti oûiljak. Jako | sam sentimentalan prema njemu.
{103725}{103806}éena? - Ti bokca, | kakva je bila!
{103821}{103890}Boûe, pleöe mi se. | Biste li zaplesali?
{103921}{103987}Koje je doba? | - Dan.
{103993}{104071}Onda je otvoreno i drugdje. | Hajdemo odavde.
{104074}{104173}Vodi damu nekamo | gdje je romantiËnije.
{104175}{104222}On to ozbiljno. | - Hajde!
{104225}{104265}Bolje da poemo.
{104928}{105012}Sjajno izbacuje, | ali nema puno snage.
{105311}{105384}Sad Êete mi reÊi kako je | vaö prijatelj silan momak?
{105388}{105432}Teöko.
{105454}{105533}Sad Êu vam reÊi | da vas ûelim za sebe.
{105598}{105679}äto god da kaûe, budi | uvjerena da je laû.
{105914}{105956}Nemoj se kladiti.
{106069}{106107}IspriËajte me, gospodo.
{106276}{106381}Ta cura ima skroz previöe | mozga za takvo dupe.
{106444}{106492}Imaö pune ruke, mali.
{106585}{106614}äto je?
{106721}{106776}Joö ûiviö u proölosti, je li?
{106819}{106868}Daleko si od Memphisa.
{106922}{106996}Memphis s time nema niöta. | - Kenjaö!
{107000}{107046}Taj pas neÊe u lov.
{107070}{107144}Ne mogu vjerovati da i dalje | vuËeö to govno za sobom.
{107192}{107324}Drûao sam da Êeö misliti | viöe filozofski o tome.
{107347}{107391}I odjebati Ëitavu stvar.
{107458}{107505}Znaö da ti jebena pi...
{107537}{107700}Ta cura ti nije rekla | da je udana. Je li?
{107776}{107839}A kad ti Ëovjek zabije | piötolj u lice,
{107842}{107956}imaö 2 izbora. Ili umreö, | ili ga ubijeö, majku mu!
{108175}{108273}Ne ûelim uniötiti provod, | ali za 2 sata imam smjenu.
{108306}{108414}Pomislih poÊi doma malko | odspavati. Niste umorni?
{108427}{108490}Naspavat Êu se koliko | treba kad umrem.
{108517}{108551}Hvala za ples.
{110023}{110092}Dalton, gori | Redova trgovina!
{111369}{111449}Niöta nisu mogli | uz takav poûar. Niöta!
{111453}{111489}'Jack Daniels'.
{111740}{111777}Hvala.
{111802}{111873}Ovdje je kao u mrtvaËnici. | Sviraj neöto, Elvis.
{111877}{111950}Amo s vatrogascima, | Ëastim ih.
{111951}{112054}Izloûili su ûivot da spase | pedersku varalicu Webstera.
{112057}{112175}Zatraûiö prilog za unapreenje | grada. Svi daju, osim njega!
{112216}{112296}Jasno da moûeö zaplesati, | mila. Elvis!
{112301}{112354}Sviraj neöto s mudima!
{115711}{115777}Ako ûeliö mezimca, | drûi ga na uzici.
{115841}{115880}Jimmy!
{117775}{117820}Moûe li netko ovdje | dobiti piÊe?
{118354}{118389}Ti!
{119066}{119101}Hajde, starËe!
{119526}{119557}U redu, dosta!
{119693}{119732}Ovo ne ide, Daltone.
{119895}{119927}Hajdemo, momci.
{120016}{120071}Tvoje dupe je moje, djeËaËe.
{120263}{120312}Isti grad, nova priËa?
{120397}{120437}Hajdemo na pivu.
{120517}{120588}PriËao sam dok mi lice | nije poplavilo, kvragu.
{120591}{120701}Moûemo spasiti, opet | izgraditi. Ja Êu ti pomoÊi.
{120712}{120780}Osiguranje imaö, ne? | - 20 godina gledam
{120783}{120860}kako se Wesley bogati, | dok oko njega svi siromaöe.
{120863}{120962}Moûete li dokazati da je | on podmetnuo poûar? - Kome?
{120967}{121055}Ima öerifa i Ëitavu policiju | u dûepu, zaboga!
{121058}{121139}Mogu zvati prijatelja u | Springfieldu. Radi za FBI.
{121148}{121206}SvjedoËit Êeö protiv njega?
{121349}{121430}Ovdje samo jednoj osobi | moraö dokazivati.
{121433}{121484}Wesleyju osobno.
{121607}{121661}SinoÊ si ga uplaöio.
{121669}{121733}Brad Wesley se niËega | ne boji, je li?
{121738}{121821}SinoÊ se pasji skot uplaöio.
{121846}{121878}Ne, nije.
{122270}{122380}Moraö ovo vidjeti. Wesley ûeli | staviti neöto na nova kola.
{122494}{122556}Izgubio si vjeru, | Stroudenmire.
{122560}{122664}U tome je vic. | To te uËinilo prekröiteljem!
{122695}{122773}äto Ëekaö, Gary? | Provezi se kroz to!
{123937}{124032}Koji je vrag s tobom, | Brad? Siöao si s uma?
{124066}{124114}On je lutalica, znaö?
{124117}{124190}Sramota je gledati kako | Êeö zavröiti s takvim.
{124193}{124248}Ovo s njime nema veze.
{124285}{124353}Makni ga odavde, | Elizabeth. InaËe...
{124399}{124430}...on tone.
{124451}{124517}I zbog tog neÊu | loöe spavati.
{124909}{124977}Nisam mislio | da Êeö me i ti iznevjeriti.
{125017}{125052}Ovo je moj grad.
{125125}{125161}Nemoj to zaboraviti.
{125199}{125235}Hajdemo, Jimmy.
{125319}{125370}Imaö osiguranje, ne?
{125957}{126012}Skroz si sjeban, je li?
{126129}{126197}Dignimo to u zrak, | pa put pod noge.
{126229}{126317}Do zore nas neÊe biti | i viöe se ne vraÊamo.
{126320}{126366}Moûeö otiÊi kad ûeliö.
{126386}{126432}Sranje, klinac!
{126582}{126615}Jebiga...
{127023}{127096}Ovo ti ne treba. | - Ne govori öto mi treba!
{127098}{127178}Ako ûeliö, idi! Odjebi | i ostavi me na miru!
{127222}{127343}Imaö pravo. Trebao bih ti | prestati govoriti öto Êeö.
{127348}{127414}Moûda bih ti trebao | ispraöiti tur.
{127495}{127551}Ne, mi ne ûelimo ovo.
{127620}{127676}I reÊi Êu ti joö neöto.
{127724}{127790}NauËio si me koliko | i ja tebe.
{127952}{127995}Volim te, mijo.
{128062}{128102}Vidimo se.
{128971}{129060}Malo je prekasno za posjete. | - Doöla sam razgovarati.
{129063}{129155}Ne... doöla si mi reÊi | da odem.
{129161}{129286}Stalo mi je do tebe, Dalton. | Ne poznajeö ga. - Kenjaö!
{129338}{129400}Znam toËno | tko je Brad Wesley!
{129404}{129499}Puno sam puta vidio takve. | Uzima i uzima
{129501}{129566}dok netko ne uzme njega.
{129569}{129632}U gradu mu se oËito | nitko ne moûe usprotiviti.
{129634}{129711}Ali ti ga moûeö zaustaviti. | - Wesley je izabrao mene
{129714}{129850}i tu se sjebo! | Samo sam u jednome dobar;
{129853}{129924}nikad ne gubim. | - A öto Êeö dobiti?!
{129927}{129982}Za koga sve ovo, za njih?
{130020}{130055}Sumnjam.
{130123}{130193}Misliö da Êeö te ljude | spasiti od Brada Wesleyja?
{130196}{130255}A tko Êe ih spasiti od tebe?!
{130528}{130565}Emmet!
{131615}{131678}Dalton ovdje, dobro ste?
{131705}{131761}Bit Êu sjajno | ako se skineö s mene.
{132548}{132651}Spremi se da umreö! | - Kakav si ti seronja...
{134585}{134666}Takve sam jebo u zatvoru!
{135038}{135124}Kvragu, momËe, | mislio sam da si dobar!
{135128}{135163}Jebi se...
{135875}{135937}Ubit Êu te | na staromodni naËin!
{136960}{137023}Wesley!
{137323}{137368}Jebeö tebe!
{138504}{138623}Dobro ti jutro! Evo öto | je na programu za danas...
{138629}{138690}Wade ili Elizabeth?
{138719}{138797}äto? | - Jedno umire.
{138839}{138881}Tko Êe to biti?
{138997}{139046}Ti si bolestan Ëovjek.
{139065}{139163}Moram samo bacati novËiÊ. | PriËekaj sekundu.
{139483}{139547}Rado bih ti rekao | öto je ispalo.
{140249}{140293}Jesi li dobro?
{140320}{140363}Bila su ih samo trojica.
{140423}{140462}Rekoöe da imam sreÊe.
{140552}{140592}Moram naÊi doktoricu.
{140624}{140707}Hajdemo... | - Sjedi, jebiga.
{140712}{140760}Popij pivo, vraÊam se.
{140857}{140933}Wesley je pobijedio, stari. | Odlazimo odavde.
{140959}{141012}To je pravi deËko, mijo.
{141265}{141328}Gdje je dr. Clay? | - Na rentgenu.
{141537}{141607}Skupi stvari, odlazimo. | - NeÊu nikamo s tobom.
{141673}{141746}Bogme hoÊeö! Hajdemo odmah!
{141767}{141795}Zaboravi!
{141998}{142034}»ovjek je lud.
{142087}{142114}A ti nisi?
{142219}{142256}Sad odlazi odavde.
{143154}{143233}Probudi se, jebiga! Odlazimo.
{143288}{143337}Daj pivu, senor...
{143381}{143430}BILO JE PISMO
{144893}{144939}SjeÊaö se one plavuöe?
{144944}{145000}Cicala bi dok i 'harley' | ne bi upalio.
{145044}{145075}Eno ga.
{145523}{145560}Goni se!
{146440}{146475}Sjebite kurËinu!
{146955}{146987}Carter?
{147156}{147186}Sranje!
{148285}{148326}Opet pismo.
{149296}{149334}Mrzim ovu kuÊu.
{150039}{150080}G. Wesley!
{150179}{150218}Stvoreni ste jedno za drugo.
{150490}{150554}Vidim da si naöao moju | sobu s trofejima, Daltone.
{150593}{150643}Jedino öto nedostaje -
{150650}{150696}tvoje dupe.
{150748}{150795}O Ëemu se zapravo radi?
{150810}{150888}Tvome prijatelju Wadeu? | Jednome starcu?
{150907}{151011}To ja zovem ubojstvom iz | milosra. Rijeöih ga bijede.
{151022}{151087}Ne ljutiö se valjda | na mene zbog toga?
{151113}{151213}Ti si sredio Jimmyja. | Bio je u boljem stanju.
{151314}{151367}Kvragu, sredio si mi | sve momke!
{151749}{151798}Izai sad, Daltone.
{151851}{151958}Grad je dovoljno velik | za obojicu. PopriËajmo o tome.
{153611}{153685}Mislio sam da Êe biti | zabavno boriti se s tobom.
{153688}{153729}Doista jesam.
{153765}{153825}Ali sada jednostavno | nemam vremena.
{154679}{154715}Ne!
{154746}{154784}Gotovo je!
{155209}{155297}Ovo je naö grad. | I nemoj to zaboraviti.
{156216}{156287}Brad, gdje si? | - Tu su, öerife!
{156489}{156588}U redu... tko Êe mi reÊi | koji se vrag ovdje zbio?
{156595}{156640}Ja niöta nisam vidio.
{156676}{156766}Jesi li ti öto vidio, Pete? | - Ne, nisam niöta.
{156783}{156874}A ti, Rede? | - Ama baö niöta.
{156910}{156956}Jesi li ti, Tinker?
{156980}{157180}{C:$0000FF}{y:ib} uredio |{C:$FF0000}{y:b} drdamjan 
{157181}{157236}Polarni medvjed pao na mene. 
{157261}{158761}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/63392|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
