{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1050}{1100}KRALJEVSTVO SUMRAKA
{1157}{1232}1500 godine veÊina Europe
{1260}{1357}je napustila svoju veru i|preöla na hriöÊanstvo.
{1407}{1507}Jedino na Severu su|se ljudi drûali vere svojih predaka.
{1510}{1587}NajmoÊniji od tih|bogova je bio Odin.
{1590}{1672}On se smestio kod zvezda,|u Valhalli, a njegovi gromovi
{1690}{1760}su mu dali mudrost i pamet.
{1765}{1845}Ali vatra davne moÊi|je öirila
{1865}{1962}Ëudnu priËu koja je|zarobila srce mnogih ljudi.
{1980}{2062}PriËala je o vitezu|koji je zarobio zmaja
{2077}{2155}i osvoji legendarno|bogatstvo: zmajevo zlato.
{3655}{3700}Previöe.
{3795}{3867}Gde Êemo?|- Brzo!
{5965}{6062}- Ne moûemo drûati juûni zid!|- Uzmi naöeg sina i idi, Sieglind.
{6065}{6127}Ne napuötam te!
{6145}{6190}Siegfried!
{6515}{6552}Ksant Velp!
{6720}{6785}Idi sad, idi.
{7422}{7497}Moj me brat uvek pazi!
{7700}{7765}Ovuda, goispodarice.
{8437}{8512}- äta Êemo?|- Moramo ovuda, kraljice.
{8880}{8945}Tamo! Hajde!
{10025}{10097}Popni se, Siegfried.|Drûi se.
{10272}{10337}Drûi. Moj sin.
{12015}{12100}Malo je prerano za plivanje,|zar ne? Ko si ti?
{12155}{12217}äta se desilo?
{12240}{12310}äta se desilo?|- Ne znam...
{12315}{12380}Ne seÊam se.
{12407}{12442}Oh...
{12670}{12677}12 GODINA KASNIJE
{12677}{12747}12 GODINA KASNIJE
{12907}{12982}äta vidiö?|- Budi strpljiv, dete.
{13005}{13082}Odinova moÊ je u ruöevinama.|Oni nikad ne laûu,
{13105}{13190}ali se ne mogu sruöiti.|- Hallbera, nemoj da Ëekam.
{13215}{13292}Vatra Êe se spustiti|s neba uskoro.
{13332}{13407}PriËaj mi joö!|- A svetlost vatre
{13410}{13480}Êe otkriti tvoju sudbinu.
{13510}{13592}Tako daleko od doma.|Koju sudbinu mogu imati ovde?
{13640}{13712}Posle vatre Êe|doÊi Ëovek,
{13752}{13822}Ëovek snaûan kao ti.
{13847}{13967}Ratnikova snaga Êe biti|kao tvoja. »ak Êete pobediti u borbi.
{14052}{14127}Niko to nije mogao.
{14130}{14202}Niko ni neÊe.
{14575}{14647}Trebamo se spremiti za noÊ.
{16320}{16392}Bolje da pripremim teret za kralja.
{16395}{16472}- Radi na tome.|- U redu.
{17060}{17172}Pozdrav. Kako Vam mogu pomoÊi?|- Traûimo Eyvinda, crnog kovaËa.
{17177}{17222}To sam ja.
{17260}{17335}Kaûu da je tvoje gvoûe|najbolje u okolici.
{17360}{17442}- äta mogu uraditi za tebe?|- Kakve maËeve imaö?
{17460}{17532}Sad nikakve.
{17567}{17665}Vidim "niöta" tamo unutra.|- Ah, ti...
{17675}{17760}Ti su za kralja Gunthera iz|Burgunda. - Ali on nije ovde,
{17787}{17852}a mi jesmo...
{17960}{18042}Planiraö da ukradeö|vlasniötvo kralja Gunthera?!
{18087}{18185}"Ukrasti", kaûe. Smatraj|se sreÊnim öto nismo naoruûani.
{18212}{18287}Erik. Mislim|da ti se gvoûe hladi.
{18990}{19032}Dobar dan.
{19252}{19330}- Ne volim Saksonce.|- Ja ih volim kad doe vreme.
{19355}{19430}Da, znam... da veûbaö maËevanje.
{20240}{20315}Pogledaj put svetlosti...
{20340}{20410}To je put za Valhallu...
{20415}{20512}Voleo bih da ih vidim kako|sede tamo, sve heroje
{20530}{20602}za Boûjim stoom.
{20605}{20715}I gledaju na nas smrtnike.|- Ali zaöto bi se brinuli za nas?
{20717}{20792}Trebaju nas kao|öto i oni nas trebaju.
{20795}{20880}BoriÊemo se na njihovoj strani|kad zlo napadne.
{20930}{21040}Kako oni znaju öta Êemo mi|uraditi?|- Oni imaju mapu sudbina...
{21045}{21142}Razmisli o svim znacima na nebu.|A ako oni vide nas odande
{21145}{21230}da radimo loöe stvari, razbesne se!
{21257}{21342}HruiöÊani kaûu da je njihov|Bog milosrdan.
{21360}{21417}HriöÊani.
{21420}{21492}Oni su Ëudna vrsta.
{21745}{21790}Oh, vidi!
{22130}{22205}Ragnarok!|Bogovi rata!
{22220}{22292}HoÊu da ih vidim bliûe!|- ne, ne.
{22295}{22390}Ne idi! Nikada se ne smemo|meöati s Bogovima. Nikad!
{25690}{25765}Ti si ûena sa broda.
{25785}{25857}A ti si Ëovek|iz kovaËnice.
{25912}{25987}Vatra i njeni|elementi.
{26072}{26147}Onda mi moûda moûeö|reÊi öta je ovo...
{26185}{26297}Nekakav Ëudan metal.|Nikada nisam video neöto sliËno.
{26302}{26377}Zamisli oruûje i|od koga je moglo doÊi.
{26387}{26465}- Da li je ovaj metal razlog zbog|kojeg si doöla? - Ne.
{26527}{26572}Ti si.
{26702}{26775}Ne brini se, kovaËu.
{26817}{26882}Reci mi neöto.
{26885}{26957}Verujeö li u subinu?
{26995}{27032}Zaöto?
{27045}{27130}Oboje smo poslali znak da|nas ovde spoji.
{27177}{27262}Taj znak je bio dovoljno|velik da ga je videla cela zemlja.
{27277}{27352}Jedini ovde smo ti i ja.
{27392}{27462}Danas mi je proroËica|obeÊala
{27467}{27552}da Êe me odvesti k Ëoveku Ëija|je snaga kao moja.
{27615}{27680}I ti si me pobedio.
{27717}{27802}- Samo sam te oborio.|- Niko to do sad nije mogao.
{27925}{27970}Do sad.
{28005}{28070}Vidiö...
{28117}{28187}Sueno nam je da se sretnemo.
{29912}{29987}Zaöto ne ostaneö kod mene?
{29992}{30065}Oh, Erik, ûelela bih to.
{30075}{30150}Ali, kao i ti,|i ja imam duûnosti.
{30185}{30270}- Ali Êu te Ëekati.|- Gde Êu te naÊi?
{30310}{30352}Island.
{30387}{30472}Moûe biti viöe nego jedan|Brunhild u Islandu.
{30492}{30565}Ne jedan od kojeg je kraljica.
{30595}{30665}Ti si kraljica Islanda?
{30667}{30707}Da.
{30790}{30862}da li to pravi razliku?
{30895}{30935}Ne.
{30952}{31027}- Ne muti moje oseÊaje.|- Dobro.
{31060}{31142}Jer, bilo öta da se dei,|voleÊu te zauvek.
{31212}{31285}IObeÊavam da hoÊu.
{33265}{33340}Bogovi su to ûeleli|da se dogodi.
{33342}{33415}Ja sam kovaË, a|ona je kraljica.
{33417}{33502}Na severu postoje mnoge priËe|gde kovaË postaje kralj.
{33525}{33565}Stvarno?
{33567}{33665}Uvek su bile stvari|drugaËije kod tebe, sine.
{33667}{33737}Moûda ih je i ona osetila.
{33832}{33942}- OËe, vodi me s tobom na putovanju|do Burgunda ove godine. - Zaöto?
{34005}{34117}Moûda reka drûi odgovor öta mi|se dogodilo pre nego öto si me ti naöao.
{34135}{34210}Nikad nisi pre bio|tako radoznao.
{34215}{34290}Pre nije bilo vaûno.
{34305}{34375}Moûda si se sinoÊ|promenio.
{34435}{34510}Ne znam niöta o sebi,
{34515}{34597}nikad nisam napustio kovanje.|Sad oseÊam da moram.
{34652}{34737}Namestimo Ëamac.|Odlazimo sutra ujutro.
{34802}{34847}Hvala ti!
{34880}{34945}Hvala ti, oËe.
{36100}{36165}äta je to?
{36195}{36260}Rat?
{36260}{36337}Izgleda da jeste.|Ali ko je neprijatelj?
{36360}{36435}Kralj Gunther je|u miru sa Saksoncima.
{37997}{38042}Gore!
{38065}{38115}Alberich.|- Gospodaru Hagen.
{38137}{38207}Vidim da se nisi promenio.
{38210}{38257}Nisi ni ti!|- Primio sam poruku...
{38260}{38345}- äta sad hoÊeö?|- Fafnir, zmaj, je budan.
{38375}{38435}Moraö uveriti kralja|Gunthera
{38437}{38512}da okupi najbolje ratnike|da ubiju Fafnira.
{38537}{38612}Zaöto da stavim ûivote|na rizik?
{38637}{38722}- Ne zanima me zmaj.|- Ne bi to rekao
{38737}{38810}kad bi znao öta je sakriveno|u peÊini... - Nastavi!...
{38812}{38890}Legendarno zlato horde|Nibelungsa!
{38985}{39082}PriËaö o tome joö od kad|su te izbacili
{39085}{39185}jer si pookusio da to ukradiö.|Sad hoÊeö da verujem da je horda ovde?
{39187}{39255}Zmaj je spavao na njoj!
{39257}{39355}Pa si potroöio sve godine smrtniËkog|ûivota kojim su te prokleli,
{39357}{39442}a zlato ti je bilo|ispred nosa!
{39457}{39502}Smeöno.
{39505}{39582}Ne bi se ti smejao|kadf bi ga video.
{39605}{39690}Nikad nisi sanjao takvu hordu|zlata i dijamanata.
{39705}{39802}Ali, zaöto bi ti pomogao i ne|zadrûao Ëitavu hordu za sebe?
{39805}{39890}Ti i ja se znamo predobro.|Moja krv
{39905}{40010}je prokleta isto i tvojim venama...|- Da se nisi usudio da priËaö o tome?
{40015}{40090}Znaö da je istina.|- Budi tih!
{40115}{40200}Znam da se sramiö|odakle dolaziö.
{40215}{40300}Ali se seti koliko sam ti|puta pomogao sa mojim moÊima.
{40362}{40435}Moûemo si sada pomoÊi.
{40445}{40490}Dobro,
{40510}{40585}izabraÊu najbolje kraljeve ljude.
{40587}{40625}Brûe.
{40725}{40807}Ali opet... Zaöto|su stvari takve?
{41340}{41417}- U redu, Kriemhild. - Spreman?|Idemo...
{41492}{41532}Idi!
{41632}{41730}- Toliko o golubima.|- Moram poraditi na lovu.
{41745}{41795}Ako se ikad vrati...
{42295}{42367}- Drago mi je da te vidim!|- I ja tebe, dragi prijatelju.
{42380}{42442}Eno ga!
{42500}{42582}- Siguran si da Êe doÊi po tebe?|- Naravno!
{42590}{42687}Zna on da sam ja njegov|gospodar.|- Dobro, kralju i gospodaru,
{42690}{42750}vrati ga!
{43022}{43095}Kakva prekrasna priËa.
{43110}{43182}- Meni pripada!|- Kako se zove?
{43185}{43257}- Arminius.|- Oh, kao veliki junak koji je
{43260}{43372}jurio RImljane po celoj zemlji.|- Da! Sad mi ga vrati, momËe.
{43375}{43447}Koga ti zoveö momËe,|deËaËe?
{43450}{43535}Ja sam kraljev brat i|zovem ljude kako hoÊu.
{43550}{43622}Jesi li to Ëuo?|äta?
{43652}{43717}äta je to?
{43745}{43785}Aha.
{43800}{43897}Kaûe da nisam obiËan Ëovek,|ali vatra i njeni elementi,
{43900}{43972}tako me trebaö zvati!
{44192}{44275}- Da pokuöamo opet?|- Prestani s glupostima, Erik!
{44322}{44397}Vrati orla princu Giselheru!
{44492}{44537}Odmah!
{45030}{45102}Nadam se da neÊeö|odustati prelako.
{46540}{46610}NabaviÊu ti novog.
{46627}{46700}Eyvind!|- Oh, gospodaru Dankwart!
{46705}{46790}- Drago mi je da si doöao ovamo sigurno.|- Videli smo nerede
{46810}{46892}dok smo iöli rekom.|- To je bio zmaj. Fafnir ga zovu.
{46930}{47035}»udoviöte je doölo od nigde|i poËelo ubijati, uniötavati sve.
{47037}{47130}- ReÊu kralju da si ovde.|- Da. Hvala!
{47200}{47275}Pogledaj ovo.|Ovo je bolje.
{47312}{47422}Imaö dobro oko za maËeve, kralju.|Sve je raeno od mog sina,
{47457}{47557}dobro je ispraksiran da|bi mogao da napravi maË za vaöu ruku.
{47560}{47642}- zaradio si sve!|- Hvala, kralju.
{47645}{47730}Uvek sam govorio da|nema boljeg kovaËa u zemlji.
{47740}{47837}Eyvind, stigao si na vreme.|Trebam najbolje gvoûe da pomogne mojim ljudima
{47840}{47910}za borbu protiv zmaja.|- Brate,
{47915}{48012}sa ovim maËem bi se mogao boriti|s zmajem na tvojoj strani. Pusti me s tobom!
{48015}{48107}Znaö moj odgovor, Giselher.|Ne bi bilo mudro da se stave dva princa
{48110}{48207}od Burgunda u opasnost u isto vreme.|- Dobro si to podneo!
{48210}{48330}Izdrûljivost ti je dobra. Molim|te, zadrûi ga, tvoj je.
{48332}{48415}- Hvala.|- Ovo stvorenje se mora loviti.
{48417}{48492}Pozivam te da se pridruûiö|nama protiv zmaja.
{48495}{48620}Toe je samo za najËasnije|i najodanije kraljeve ratnike.
{48637}{48715}Molim Vas, oprostite|mu njegovu strast, moj kralju.
{48752}{48822}Znam kako se oseÊaö.
{49197}{49295}Na öta si mislio, Erik?|Da Êete kralj Ëekati
{49297}{49372}da ubijeö zmaja za njega.|- Mogu ja to!
{49392}{49507}Sa svojim ustima! Pobrini|se da su dostigle pravu temperaturu.
{49555}{49637}- NeÊeö mi pomoÊi?|- To je tvoj maË.
{49655}{49737}- Nisam li te uËio kako se to radi?|- Jesi.
{49750}{49812}Onda napravi!
{50312}{50382}VoleÊu te zauvek.
{51730}{51800}U öume za Fafnirom!
{51900}{51977}Neka Bog bude s nama|i podari nam veliku pobedu!
{53090}{53167}Ne bulji u princezu.|Nije lepo.
{53190}{53255}Ne buljim.
{53287}{53352}Ona gleda mene.
{53737}{53815}Deo Vatre i Elementi,|mogu li uÊi?
{53820}{53895}Moûeö. I, molim|te, zovi me Erik!
{53947}{54027}Ja sam princ Giselher.|- Da li bi mi
{54040}{54112}mogao malo pomoÊi, prinËe?
{54150}{54192}Hvala!
{54210}{54307}Doöao sam da se zahvalim|tvom ocu za maË. Uradio ga je brzo.
{54310}{54407}On sad spava, ali reÊu|mu da si navratio.
{54410}{54505}Nikad nisam sreo kovaËa koji|zna tako dobro da se sluûi maËem.
{54507}{54592}Moj tata uvek kaûe da|nema dobrog maËa
{54607}{54692}ako se ne znaö njime koristiti.|äta je s tvojim ocem?
{54702}{54780}Moj je otac ubijen u|bici pre mnogo godina.
{54800}{54870}Moja je majka potom umrla.
{54912}{55010}- Kako znaö da je gvoûe spremno?|- OseÊam. Kako  izgleda.
{55012}{55087}Ovaj Êe se morati raditi danima.
{55112}{55232}- Nije li lepo praviti ovakve stvari?|- Imaö li talenta ili ne?
{55235}{55307}Ja sam princ. Meni|nije dozvoljeno da radim.
{55332}{55407}To bi obeöËastilo mog brata,|kralja.
{55437}{55522}- Nije li ti dosadno?|- Da! Da mi nije sestre,
{55535}{55607}poludeo bi.|- Lepa je devojka.
{55630}{55727}Svako plemiÊ u naöem carstvu je ûeli.|Ona ne ûeli nijednog.
{55730}{55812}- Koji joj je srcu prirastao?|- Zaöto toliko puno pitaö?
{55825}{55910}- Nisi li i ti opsednut njome?|- Moje srce pripada drugoj...
{56065}{56145}Samo se nadam da je moj|brat u stanju da ubije zmaja.
{56805}{56880}Kralj! Kralj se vraÊa!
{57907}{57952}Gunther!
{57967}{58012}Gunther!
{58110}{58222}Zmajeva Ëeljust je bila teöka|kao gvoûe. Naöa oruûja su bila preslaba.
{58305}{58367}Uvedite ga.
{58650}{58722}BiÊe osveÊen!
{58787}{58852}Kunem se!
{59942}{60017}To je tvoj izbor, sine.
{60185}{60262}- Kako Êeö ga zvati?|- Ne znam. Zaöto?
{60297}{60372}MaË tako dobar|zasluûuje ime.
{60495}{60567}Onda Êu ga zvati|Balmung!
{60577}{60662}Balmung? Balmung je bio maË|zadnjeg lkralja od Xantena,
{60675}{60760}uniötenog u borbi.|Zaöto ga hoÊeö tako nazvati?
{60807}{60877}Volim takvo ime.
{63295}{63340}Fafnir!
{63347}{63417}Izlazi! Izlazi, ti crve!
{63467}{63537}Fafnir! Ovde sam!
{64905}{64947}To je to.
{65075}{65137}Izlazi! Hajde!
{76230}{76307}Ako si mudar,|otiÊi Êeö bez iËega.
{76390}{76465}Ovo zlato nije|za ljudsku vrstu.
{76517}{76582}Pripada nama.
{76685}{76797}- Mislim da je pripadalo zmaju.|- Mi smo Ëuvari zlata.
{76825}{76897}Zlato koje mi|samo smemo imati.
{76905}{76987}Horda je bila naöa|dok nam je Fafnir nije ukrao...
{77030}{77105}Posluöaj naöe upozorenje|ili Êeö platiti.
{77155}{77230}- Ko si ti?|- Mi smo Nibelungsi.
{77245}{77342}Ljudi misterije i zagonetki.|Vratio si nam zlato
{77345}{77422}ubivöi Fafnira. I|zahvaljujemo ti se zbog toga.
{77462}{77575}Ne morate me hvaliti jer sam|ja riskirao ûivot ubivöi zmaja!
{77577}{77675}- To bi trebalo biti vredno.|- Ne vredi ni malog novËiÊa
{77677}{77757}od ovog zlata,|jer je prokleto.
{77815}{77895}- Ne verujem u prokletstva...|- Dokaz ti je napolju.
{77915}{78025}- Fafnir leûi mrtav zbog toga.|- Mislim da on leûi mrtav zbog mene.
{78140}{78225}- äta je ovo?|- To je PRSTEN NIBELUNGA,
{78240}{78317}najstarija stvar u öumi.|Samo srce.
{78340}{78420}Onaj koji ga ima,|ima i celo zlato.
{78782}{78857}- Prelep je.|- A i smrtonosan za tebe,
{78875}{78947}kao i sve ostalo ovde.
{78985}{79070}TrebaÊe ti delo, a ne|reËi da me uplaöiö.
{79085}{79157}VratiÊu se.
{79577}{79675}Kad prokletstvo poËne gristi,|setiÊeö se. NaÊe ti slabost
{79677}{79750}i kroz nju te uniötiti.
{80620}{80702}- Kakav je ovo Ëarobnjak?|- Vrati ga! - Ko si ti?
{80730}{80805}- Trebao sam bolje znati.|- äta?
{80812}{80897}Zmajeva krv ti je napravila koûu|neprobojnom. - Sluöaj,
{80912}{81010}öta me zaustavlja da te sad|ne ubijem? - MagiËni Tarnhelm!
{81035}{81110}Moûeö ga zadrûati!|Naterao me je da ti ukradem prsten.
{81130}{81212}äta Êe mi to?|LiËim na sebe.
{81235}{81320}Da, ali s tim|moûeö uzeti bilo koji oblik.
{81420}{81495}- Dokaûi!|- Stavi ga na glavu.
{81725}{81822}- Ti me pokuöavaö prevariti?|- Ne! Moraö reÊi magiËne reËi!
{81825}{81922}"Senke i mrak, sve je isto",|i moraö misliti u koga
{81925}{82007}se ûeliö pretvoriti...|- Senke i mrak, sve je isto!
{82210}{82280}Izgledaö gadno!
{82337}{82407}Onda mora da izgledam kao ti.
{82530}{82600}PoötedeÊeö me?
{82662}{82702}Idi!
{82852}{82937}Joö jedna greöka, mladi smrtniËe.|Sad isto nosiö i njegove greöke
{82975}{83047}i prokletstvo...!|- Zaöto? Ko je on?
{83085}{83162}Zove se Alberich i|bio je jedan od nas.
{83185}{83282}Ali pohlepa se pojavila u njemu.|éeleo je blago samo za sebe,
{83285}{83360}kao ti.|Kad je pookusio da ga ukrade,
{83385}{83467}izbacili smo ga i|oduzeli mu besmrtnost.
{83500}{83572}äta ako napravimo dogovor?|Ja Êu uzeti samo pola blaga,
{83575}{83650}a vi ostatak. Nije|li to poöteno?
{83675}{83775}Pola, svo blago, ili|samo prsten, sve je dovoljno
{83777}{83852}da donese celo prokletstvo na tebe...
{83890}{83952}Sve je moje.
{84250}{84325}Gospodarice, hteli ste testove.
{84355}{84465}Skoro su svi na pripravnosti.|Ljudi koji traûe vaöu ruku
{84467}{84552}su kraljevi i princeze!|- A ja sam kraljica, isti su.
{84572}{84672}Imam pravo da u svojoj zemlji|radim zakone kakve hoÊu.
{84675}{84772}Onda im reci da Êe kraljica|Islanda poÊi za Ëoveka
{84775}{84872}koji proe testove koje sam namestila,|i ko me moûe pobediti u borbi.
{84875}{84957}Ali niko se ne moûe|nadati da to moûe ispuniti, VisoËanstvo.
{84975}{85055}Jedan Êe uspeti. I|taj Êe me oûeniti.
{85080}{85165}PoznaÊu to Ëoveka kad|ga vidim. Moûeö iÊi.
{85402}{85522}Misliö na Ëoveka koji|te je sruöio one zvezdane noÊi?
{85525}{85607}KovaËa?|- Mislim na njega od tada stalno.
{85645}{85742}i neÊu nikog drugog, Hallbera.|NeÊu princa, ni kralja,
{85750}{85820}Ëak ni rimskog imperatora.
{85852}{85937}A öta ako se tvoj zgodni|maËevalac ne pojavi?
{85955}{86062}i da li je on snaûan i hrabar|da proe sve tvoje testove...?
{86065}{86162}Pobedio me je.|Samo Êe me on moÊi joö jednom pobediti.
{86200}{86272}Rune ne laûu.
{86870}{86915}Erik.
{87237}{87312}- Gde si bio?|- Lovio sam. - Bilo öta?
{87440}{87515}äta je ovo?|Na öta izgleda?
{87522}{87592}Zmajeva potpetica...
{87595}{87667}- Gde si to naöao?|- Pod zmajevom nogom.
{87670}{87755}Naravno da jesi. Misliö|da moûeö da prevariö svog starog oca?
{87770}{87842}Ako ti se ne svia potpetica,
{87895}{87960}moûe glava?
{88027}{88067}äta?
{88125}{88202}Ne mogu da verujem!|Stvarno je zmaj!
{88240}{88302}Prelepo.
{88327}{88402}Fafnir je mrtav.|Eri, kovaË,
{88427}{88502}je ubio zmaja.|- Da, mrtav je.
{88565}{88630}»ujeö li?
{88655}{88720}Zmaj je mrtav.
{88730}{88797}Erik je ubio zmaja!
{88800}{88872}Gotovo je, gotovo je.
{88950}{89012}Hvala, dobro sam.
{89197}{89240}Gunther!
{89242}{89315}Erik je ubio zmaja, sam.
{89322}{89407}- Ovaj kovaË mora da je blagoslovljenWod Boga...- Ili avola.
{89422}{89507}Uspeo je sam gde ste ti|i 12 ratnika maöili.
{89525}{89630}Bilo koju moÊ öto je koristio|protiv zmaja bi mogao iskoristiti protiv tebe.
{89632}{89697}Uradio je ovo za mene....
{89700}{89810}Otvori oËi, Hagene, i|dozvoli da tvoj sumnjajuÊi um uzme odmor...
{89845}{89917}Ljudi iz Burgunda! Zapovedam
{89935}{90020}da Erika, kovaËa,|proglasimo junako carstva!
{90035}{90155}Dugo ûiveo za svoju pobedu!|Dugo ûiveo ubica zmaja!
{90687}{90785}»ak i Ëast öto se Ëuva takvo|zlato bi donela slavu carstvu
{90787}{90885}i poötovanje njegovog kralja bi|se podiglo izvan opsega, kad se sazna
{90887}{90972}da ste Vi umeöani sa|sigurnoöÊu horde...
{90990}{91072}Moj kralju, ubica zmaja je napolju.|- Poöalji ga unutra.
{91075}{91172}VuËi veoma privlaËno, Hagene,|ali svo ovo
{91175}{91252}ovisi o tome öta|Êe naö mladi junak reÊi.
{91265}{91362}Kralju Gunther, poËastovan sam|Vaöom ponudom da Ëuvam zlato
{91365}{91447}kod sebe. Ali...|-- Ne verujeö kralju?
{91465}{91572}Verujem mu toliko da sam|ubio zmaja za njega, gosp. Hagen,
{91575}{91650}zar ne?|- To je bio pravedan pogodak, Hagen.
{91677}{91762}Erik, reË "ali" veÊinom|znaËi nekakve poteökoÊe.
{91850}{91895}Moj kralju,
{91935}{92017}nisam siguran da|Vi imate dovoljno soba.
{95170}{95252}- Mogu li ti videti lice?|- Ne! To bi uniötilo sve!
{95312}{95392}On mi je jedini sin.|Podigao sam ga sasvim sam.
{95412}{95490}- Otac naöeg junaka!|- Ne samo to!
{95500}{95575}Ja usto i pravim|maËeve koje kralj voli.
{95595}{95670}- Joö i paganin!|- Thorov buzdovan,
{95707}{95785}Boûe munje,|Boûe smrtnika,
{95807}{95882}su moji Bogovi.|Jesi li preobraÊena?
{95895}{95935}Da,
{95955}{96025}ali noÊas sam|paganin.
{96192}{96262}Idemo po malo vode.
{96440}{96537}äta ubica zmaja sad radi|kad nema viöe zmajeva?
{96540}{96612}VraÊa se u kovaËnicu.
{96625}{96722}Sa svim zlatom koje si doneo|iz peÊine, ne moraö viöe da radiö!
{96725}{96822}Tata me nauËio umetnosti|pretapanja raznih metala u gvoûe,
{96825}{96880}a ja u tome uûivam.
{96882}{96967}Pobediö zmaja sa maËem,|ali osvojiö zlato!
{97012}{97082}Koliko? Jedan?|Dva? Previöe?
{97107}{97147}Nijedno.
{97185}{97255}Moje srce je|veÊ zarobljeno.
{97305}{97385}Ko je ta dama?|Visoki poloûaj ili niski?
{97402}{97475}Visoki, mislim... ili se plaöim.
{97520}{97582}Moûda previsok.
{97590}{97670}Moûda ona ne zna da|je ti voliö toliko puno,
{97690}{97787}ali sve se moûe namestiti tako|velikom junaku.
{97802}{97872}- Znam li je?|- Ne.
{97885}{97950}éivi daleko.
{98020}{98105}Tako. Kome je tvoje srce dano?|Jesi li oûenjen?
{98125}{98190}Ne, nisam.
{98200}{98275}Ako se ikad oûenim,|to Êe biti iz ljubavi.
{100120}{100190}HoÊeö li doÊi k meni?
{100220}{100290}»ekam te, ljubavi.
{100320}{100395}Znaö li makar ko si?
{100455}{100537}Zovu me Erik kovaË,|Erik-ubica zmajeva,
{100577}{100645}i Erik, junak Burgunda.
{100647}{100720}Ali to su samo pohvale.
{100722}{100792}Jedna Ëast,|jedan je poËastvovan,
{100810}{100875}jedini poËaöÊeni.
{100885}{100962}Ali ni jedni nisu|kao ti...
{103840}{103937}Kraljevi, blizanci, su napali|na Odinwood.|Spalili su nam gradove
{103940}{104037}i uzeli nam ljude za robove.|Sad kad govorimo, Bonna je pod opsadom.
{104040}{104125}Bestraga. Bestraga s obojicom.|éiveli smo u miru s
{104140}{104237}kraljevima-blizancima skoro 10 god.|- Da, ali veÊu deo tih 10 godina,
{104240}{104347}Burgundovo zlato je nije bilo|popunjeno s Fafnirovom hordom.
{104350}{104435}- Pohlepa Êe raskinuti sve ugovore.|- Koliko im je jaka vojska?
{104460}{104545}4 000, moûda 5 000 ljudi.|- Moûemo protiv njih.
{104560}{104657}Ali su u pokretu. Nije vaûno.|Poöaljite poruke svim naöim gradovima.
{104660}{104742}Pripremite vojsku Burgunda. Odlazimo.|- Moj kralju,
{104745}{104842}Erik ti ne treba sluûiti,|ali je ubio zmaja za vas...
{104875}{104995}Ako se sloûi da se pridruûi vojsci,|to Êe ohrabriti naöe ratnike.
{105005}{105072}I obeshrabriti neprijatelja.
{105075}{105187}Upoznati Ëoveka koji je ubio zmaja|bi dalo svima pauzu za razmiöljanje.
{105202}{105257}Zapovedi... ne,
{105260}{105357}pitaj ga da doe s Burgundskom|konjicom. - Brate, ûelim da...
{105360}{105457}Giselher, poötujem tvoju hrabrost.|Ali ovo viöe nije pitanje slave.
{105460}{105542}Ako se ne vratimo, moraö|ûiveti da odbraniö Burgund.
{105560}{105632}I tvoja sestra.|Do tada, mi kreÊemo.
{106210}{106250}Idemo.
{106540}{106582}Kraljevi Burgunda! Moji|uËitelji, dobri kraljevi Thorkwin i Thorkilt,
{106585}{106657}ne ûelite ovu borbu!
{106670}{106767}- Od kad smo te nadbrojali, verujem da hoÊemo.|- PoötedeÊemo vam ûivote i
{106770}{106900}poötedeti Burgund i sve u njemu,|ako predate zmajevo zlato.
{106902}{107010}Pogreönog Ëoveka pitate za zlato,|glasniËe. Ako hoÊete
{107012}{107122}zlato, morate to razreöiti|s ubicom zmaja.
{107500}{107547}Da popriËam s njim, kralju.|- Ne,
{107550}{107635}neÊu to dozvoliti!|BoriÊemo se zajedno s njim.
{107650}{107777}To je moje blago, moj kralju.|Previöe je krvi zbog toga prosuto.
{107797}{107895}Moj kralju, ako ubica zmajeva|moûe izbeÊi prolivanje krvi,
{107905}{107970}onda ga pustite.
{108225}{108297}Ako on propadne,|napaöÊemo.
{108310}{108375}Joö jedan glasnik...
{108505}{108580}»uo sam da ûelite|neöto moje.
{108592}{108677}Ja sam gospodar zmajevog|zlata. Ako ga ûelite,
{108695}{108805}moûete probati da ga uzmete.|Ali Êete morati prvo preko mene!
{108827}{108897}Velike reËi za jednog kovaËa!
{108900}{108982}Treba neöto viöe od zlata da|natera Ëoveka da se bori protiv kralja.
{109000}{109085}I treba viöe od krune|da uËini Ëoveka kraljem.
{111360}{111437}Ti nisi niöta gore|nego Burgundski klovn !
{111460}{111522}Ksanten velp!
{112240}{112312}Ti si mi ubio oca!
{112625}{112705}Ja sam Siegfrid! Sin|Siegmunda, kralja od Xantena!
{112745}{112842}Ti si pobeen i tvoje|carstvo Êe biti podeljeno meu kraljevima
{112845}{112917}od Burgunda i Xantena.
{112935}{113007}Trebam vas ubiti oboje|zbog onoga öto ste uËinili,
{113035}{113110}ali mi to neÊe|biti olaköanje.
{113130}{113200}Samo mi se gubite s oËiju.
{114105}{114185}éelim da bude vezan za|Burgundsku kuÊu zauvek.
{114205}{114302}- äta imate na umu, kralju?|- Moja sestra Êe se udati za njega.
{114347}{114432}I siguran sam da ti neÊe|biti teöko da to napraviö.
{115112}{115132}Idi sad!
{115250}{115320}Tata, otvorio sam oËi.
{115780}{115852}Znam ko sam.
{115855}{115930}Kralj i vredan,|nadam se, kraljice.
{115957}{116042}Doi u Island, ljubavi, i otkrij.|- Uskoro, ljubavi.
{116085}{116185}Osvojio sam veliko blago i|ûelim ga doneti kuÊi, k tebi.
{116187}{116232}Siegfried,
{116237}{116315}ti si jedino blago koje ûelim.
{116335}{116407}Poûuri, ljubavi, Ëekam.
{116782}{116857}Sad si ti doöao kod mene.|äta ûeliö?
{116860}{116957}Siegfried ûeli da vrati blago nazad|u oËev dvorac, U Xanten.
{116960}{117042}- Mora biti zaustavljen.|- Cela vojska ga ne moûe zaustaviti.
{117065}{117162}Kralj ûeli da ga veûe za kuÊu|Burgunda tako da oûeni Kriemhild.
{117165}{117250}- Ali postoji druga ûena.|- Na öta ciljaö?
{117265}{117337}Jedna tvoja magija ili otrov
{117340}{117452}da bi zaboravio staru ljubav|i pronaöao da je ova princeza zgodnija,
{117455}{117527}öto znaËi da Êe tad|zlato ostati kod nas.
{117545}{117620}Mislim da ti mogu pomoÊi.|Ako je cena odgovarajuÊa.
{117647}{117732}- äta ûeliö?|- Taj mi je momak neöto uzeo.
{117747}{117875}Izgleda kao maska. »ovek|koji zna njenu tajnu, moûe se pretvoriti u koga hoÊe.
{117885}{117960}Siegfried je zna.|- lnteresantno.
{117965}{118037}Vrati mi Tarnhelm nazad|i napitak je tvoj.
{118040}{118137}Napitak prvo.|Kad budem otkrio da radi, tad
{118140}{118237}Êeö dobiti svoj Tarnhelm.|- ImaÊeö ga prekosutra, sine.
{118250}{118322}Nemoj da me tako zoveö!
{118335}{118369}Ali ti jesi moj sin.
{118370}{118467}Ako bi ubistvo to promenilo,|davno bih to uËinio.
{119205}{119280}Kako mesec rudi,|srce se Ëudi,
{119305}{119382}memorije se podele,|srce hladno raste.
{119400}{119475}Popivöi napitak|nova se ljubav raa,
{119817}{119892}stara se briöe,|izvipori slaa,
{119917}{119992}protiv napitka nema leka,
{120290}{120360}ni gvoûe, niti srebro,
{120410}{120460}Ëak ni zlato.
{120972}{121017}OËe?
{121075}{121120}OËe!
{121292}{121337}OËe!
{121397}{121472}äta ti je?|Jesi li bolestan?
{121505}{121575}Ako su u pitanju godine, da.
{121625}{121747}Dugo si radio.|Viöe ne moraö.
{121750}{121870}- Imamo previöe zlata.|- Ne mami me s zlatom, sine.
{121875}{121957}- Gvoûe je moj metal.|- Samo si umoran, oËe. To je sve.
{121975}{122057}- DoneÊu ti neöto da pojedeö|i popijeö. - "OËe",
{122075}{122145}joö me tako zoveö?
{122147}{122220}Tvoj pravi otac je bio kralj.
{122247}{122320}- Znao si.|- Sumnjao sam.
{122352}{122435}Video sam znak kraljevske|porodice na tvom telu.
{122460}{122560}A kasnije sam Ëuo da kraljevi-|blizanci tragaju za izgubljenim sinom,
{122562}{122635}ali ga nikad nisu naöli.
{122655}{122730}Jer si mi dao drugo ime da me zaötitiö.
{122732}{122817}Bila bi laû kad bi|rekao da je to bio jedini razlog.
{122825}{122902}Vidiö, nikad nisam imao ûenu,|ali s tobom...
{122925}{122990}Dobio sam sina.
{123037}{123122}I bio sam tako sreÊan öto|sam ti otac... Tvoj otac!
{123155}{123240}I uvek Êu se ponositi tobom.|éelim da znaö to.
{123285}{123342}I öta god da sam,
{123345}{123420}to je zbog toga öto|si me ti nauËio.
{123435}{123532}Svet oko nas je|u velikoj promeni
{123582}{123667}i nove moÊi se bore protiv|starih za novo vladanje.
{123702}{123777}Uradio sam svoj deo|boreÊi se.
{123800}{123882}Kad moje vreme doe, moje|telo Êe biti poslano Bogovima
{123912}{123977}na stari naËin,
{123980}{124052}naËin vatre i vode.|Ali ti
{124057}{124137}i tvoja kraljica ste|deca starog sveta.
{124165}{124240}Bogovi su vam dali|prekrasnu moÊ.
{124242}{124340}I morate da ispunite sudbinu|zajedno, ma gde vas ona vodila.
{124367}{124447}DoveöÊu moju ljubav|u Xanten kao svoju ûenu.
{124470}{124532}ObeÊavam ti.
{124565}{124640}Ali i ti ideö sa mnom!
{124672}{124747}Nema viöe putovanja za mene.
{124777}{124852}Jedva i diöem.
{124865}{124947}Joö ima dosta stvari za tebe,|mnogo maËeva za napraviti.
{124990}{125060}Moj najbolji maË se pravi.
{125070}{125147}Ne trebamo se muËiti|s lekcijama.
{125210}{125307}Grlo mi je suvo, sine.|Ono piÊe öto si rekao da Êeö doneti,
{125310}{125382}dobro bi mi sad doölo.
{125437}{125512}Naravno, oËe.|Odmah se vraÊam.
{126190}{126232}OËe?
{126240}{126282}OËe!
{126640}{126692}éivotinje umiru,
{126695}{126740}ljudi umiru,
{126742}{126812}svi na Zemlji moraju umreti...
{126832}{126905}Ali istiniti junak nikad ne umire,
{126925}{126995}biÊe zauvek pamÊen.
{127275}{127320}Moja ljubav
{127340}{127415}je tako blizu|mome srcu i umu.
{127422}{127497}A tako daleko od mojih|ruku i tela.
{127517}{127577}Koliko joö?
{127580}{127645}Koliko joö ima?
{127815}{127855}Da?
{127957}{128022}Moja draga Kriemhild,
{128030}{128102}mogu li s tobom priËati?
{128105}{128187}- éelim biti sama, gosp. Hagene.|- O Siegfriedu.
{128217}{128297}- äta s njim?|- OËekujem da se vrati svakog dana.
{128322}{128355}Naravno da Êe se vratiti,
{128357}{128432}zbog blaga.|- Ne zbog tebe?
{128530}{128627}- Na öta misliö?|- Video sam njegove oseÊaje za tebe.
{128657}{128732}PriËaö, a niöta ne znaö o tome.
{128757}{128855}Znam, draga Kriemhild, da si|zavolela ubicu zmaja
{128857}{128967}joö od prvog trenutka kad si|ga videla i ja sam doöao da ti pomognem.
{128997}{129082}Kad ode zlato, niöta|ga viöe neÊe zadrûavati ovde.
{129140}{129225}- äta je to?|- Biljke s interesantnom istorijom.
{129252}{129337}Ako se iskoriste kako treba,|srce Ëoveka Êe narasti veÊe.
{129392}{129470}To je pogreöno!|To hriöÊani ne rade.
{129505}{129582}To je stara magija|vraËanja i prokletstva.
{129607}{129707}Sve öto on mora uraditi je da|popije ovo, pomeöano s vinom samo dok
{129710}{129807}mu ti dajeö kup i bilo koja|ljubav prema drugoj ûeni
{129810}{129892}Êe biti zaboravljena i|samo ti Êeö goreti u njegovom srcu
{129910}{129972}od tog trenutka.
{129990}{130035}Ali zaöto...?
{130055}{130165}U bitki i miru, uvek|sam sluûio kuÊu Burgunda
{130180}{130252}i imao najbolje namere za kraljevstvo.
{130477}{130547}
{130572}{132072}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
