{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{1418}{1624}Zemlja pre vremena 8
{1685}{1903}Velika HladnoÊa
{2209}{2271}Planeta Zemlja.
{2274}{2390}Svet stalnih promena|i nepredvidivog vremena.
{2392}{2451}Naö dom.
{2452}{2535}Milionima godina ranije,|bila je dom
{2585}{2644}D I N O S A U R U S I M A.
{2788}{2889}I ako te divlje zveri|ne izgledaju kao mi,
{2891}{2962}u nekom pogledu|nisu uopöte bili razliËiti.
{3033}{3136}Kao i ljudi,|ima ih u svim veliËinama...
{3138}{3204}i oblicima i bojama.
{3360}{3417}Neki mogu da skaËu.
{3563}{3620}Neki da se penju na drveÊe.
{3921}{3979}Neki umeju da plivaju...
{4103}{4162}a neki ne.
{4483}{4572}Neki Ëak mogu da zviûde.
{4887}{4974}I baö kao svima|nama ponekad,
{4976}{5069}nekima ne polazi za rukom|da se na spavaju.
{5122}{5198}Whoa!
{5400}{5485}Pomeri se malo, Spike.|Nemam mesta.
{5692}{5782}Ti stvarno zauzimaö|mnogo mesta.
{5784}{5874}Svaki put kad spavamo,|uvek ista stvar!
{6163}{6220}Whoa!
{6291}{6371}Spike?|                  Spike!
{6374}{6431}Molim te, ne noÊas.
{6434}{6533}Nemoj noÊas da hrËeö.|Tako sam umoran.
{6534}{6593}Molim te, |molim te, molim te!
{7245}{7316}Mnogo, |mnogo vremena ranije,
{7317}{7389}Mnogo ranije|nego öto se bilo ko moûe setiti,
{7392}{7491}moÊna stvorenja|doöla su prvo...
{7492}{7623}iz mraËnog mulja|ispod suve zemlje,
{7625}{7705}i tako je poËela|era dino...
{7707}{7806}Izvinjavam se, Mr. Thicknose?|Molim?
{7809}{7887}Pa,|ako je to bilo toliko mnogo ranije|da se toga niko ne moûe setiti,
{7889}{7947}kako ti onda znaö|da se uopöte dogodilo?
{7949}{8007}Ja, uh...
{8009}{8074}Pa, znamo da se dogodilo...
{8076}{8134}Jer, da se nije dogodilo,|mi ne bismo bili ovde.
{8136}{8194}Duh!
{8276}{8389}Aha, ali kako znaö|da su prvi doöli|iz mracnog mulja?
{8390}{8504}Ja letaË!|Porodica moûda siöla|sa visokih brda!
{8505}{8570}A u Daki-evoj porodici|su plivaËi.
{8573}{8631}Moûda su isplivali|pravo iz velike vode.
{8632}{8709}Pitam se odakle je doöla|Spike-ava porodica?
{8712}{8800}Odakle god da je doöla|sigurno je bilo daleko,
{8803}{8902}zato öto je uzaöno umoran.
{9033}{9098}Mladi, molim vas!|Daki,
{9100}{9196}da li je tvoje krdo bilo budno celu noc|sakupljajuci zvezdano liöce?
{9198}{9257}- Ne.
{9259}{9334}Onda molim te pokuöaj da ostaneö budna.
{9336}{9422}To nije fer!
{9425}{9518}I ti si bio pospan.|Zaöto baö...|Daki!
{9521}{9638}Da li bi, molim te, mogla biti|malo tiöa, kao Spike?
{9794}{9883}Pa, uh, gde sam ono stao?
{9885}{10011}- Objaönjavao si|odakle smo doöli.|- Oh, da, da. Pa...
{10014}{10117}A ja sam rekao, "Kako zaista znaö|odakle smo doöli?"|A ti si rekao...
{10119}{10237}Secam se.|Mozda bi trebalo da pricamo|o necem drugom.
{10239}{10316}Hmph!
{10323}{10389}Sakupljanje hrane.
{10391}{10549}Ja sam imao priliku|da proucavam razne nacine...
{10551}{10621}ishrane...
{10623}{10712}razlicitih krda|iz zelene hrane...
{10715}{10832}koja nas okruzuje ovde|u naöoj plodnoj Velikoj Dolini.
{10835}{10904}Oötrorepi|i Trorogi...
{10907}{10995}upraznjavaju|metod udaranja lobanjom,
{10997}{11069}razbijajuci drvece|svojom glavom...
{11071}{11140}ne bi li zvezdano liöce palo.
{11142}{11262}Letaci koriste krila|da odlete|do najboljih grana...
{11264}{11335}Oh, oh, oh!|Ja znam kako to rade Dugovrati!
{11337}{11419}Da, Malo stopalo,|i ja takoe,
{11421}{11546}ali ne govorim|sada o Dugovratima.
{11548}{11606}Ali, gde sam ono stao?
{11608}{11698}Trorogi, Dugovrati,|Oötrorepi...
{11700}{11801}Oh, da. Oh, da.
{11803}{11897}Ali verovatno naj...|Ne, ne, ne!
{11899}{12002}öta je sad?|Spike je pojeo moje specijalno|zvezdano liöce.
{12004}{12066}Moja mama mi ih je dala|specijalno za mene.
{12281}{12374}Svi ti prekidi.|Ne mogu da mislim lepo!
{12376}{12444}Hajde, vas dvoje|udaljite se jedno od drugog.
{12446}{12534}Daki, ti doi ovamo.|Spike, idi tamo.
{12607}{12719}I savröen primer|onoga na öta sam upravo ukazao.
{12721}{12814}PrimeÊujete da neki|od Oötrorepih pasu travu,
{12816}{12934}dok drugi koriste|metod udaranja lobanjom...
{12936}{12994}o kome sam malopre govorio.
{12996}{13095}Ti Oötrorepi|su lutalice.
{13097}{13211}Oni dolaze u Veliku Dolinu|sa vremena na vreme|na svojim putovanjima,
{13213}{13288}u potrazi za hranom.
{13289}{13366}SreÊom, mi imamo|dovoljno hrane za sve,
{13368}{13437}i mirni posetioci|su dobrodoöli.
{13500}{13614}Da nastavim.|Sakupljanje hrane.
{13616}{13705}Mozda najinteresantnija|tehnika od svih...
{13707}{13809}je ona koju koriste äupljorogi.
{13811}{13927}Oni ricu tako glasno|kroz rogove|na njihovim glavama...
{13928}{14026}da zvezdano liöce|samo pada svuda unaokolo.
{14028}{14163}Naravno, neko drveÊe|neÊe tako lako|da da svoju zelenu hranu.
{14165}{14298}Mozda se najviöe opire|baö ovo ovde,|iznad mene.
{14301}{14397}Njegovo öiroko,|lisnato zelenilo,
{14399}{14461}iako toliko|prijatnog ukusa,
{14464}{14585}Ëesto se pokazalo|suviöe uznemiravajuÊe...
{14587}{14691}- Aah!
{14842}{14907}äta ti znaö?
{14910}{14988}Radi!
{15260}{15336}Ne znam zaöto se|Mr. Thicknose uopöte trudi|da razgovara sa nama.
{15339}{15442}Izgleda da ga mi samo uznemiravamo.|Kako to misliö, "mi"?
{15495}{15573}Stvarno misliö da je|Mr. Thicknose uznemiren?
{15575}{15713}Pa, kako bi se ti oseÊao|da je neko ispustio veliku staru|voÊku na tvoju glavu?
{15715}{15793}Ja ne znam.|Aah!
{15875}{15933}Ha!
{15935}{15993}Ja znam.
{16346}{16406}Hajde, Malo stopalo.|Zaboravi.
{16408}{16484}Dodaj loptu!
{16486}{16544}Pa...
{16691}{16756}Ovamo!
{17081}{17139}äta nije u redu sa tobom?
{17141}{17199}Ne znam.
{17202}{17291}Osecam se... Ëudno.
{17293}{17359}»udno dobro|ili Ëudno loöe?
{17361}{17460}»udno loöe... ovde.
{17461}{17546}Misliö da|si mozda bolestan?
{17548}{17641}OseÊam se kao da ima neöto|u mom stomaËiÊu...
{17643}{17702}öto je vruÊe, vruÊe, vruÊe,
{17703}{17824}kao kljuËala voda|unutar planine|öto eksplodira na njenom vrhu.
{17826}{17897}Oh, to!
{17900}{17989}Ti nisi bolestan.|Oh, dobro je.
{18058}{18115}Pa öta onda nije u redu sa mnom?
{18118}{18185}Niöta.|Samo si ljut.
{18187}{18248}- Ljut?|- Aha.
{18251}{18308}Stvarno? Hmm.
{18311}{18370}Ko bi rekao?|Ja sam ljut.
{18371}{18483}- A na koga sam ljut?|- Zar ne znaö?
{18485}{18565}Hmm. Pa,|da vidim.
{18567}{18648}Eto ga!|Znam!
{18649}{18710}Spike, ne!|Ovamo!
{18712}{18771}NabaviÊu drugo.
{18807}{18911}Znam, u redu.|Ljut sam na Spike.
{18914}{19016}- äta da radim sad?|- Doöao si na pravo mesto.
{19018}{19127}Ako postoji neöto|sto mi trorogi umemo,|to je da se ljutimo!
{19866}{19923}Hia!
{20134}{20216}Zapamti, Tippy,|sazvaÊi hranu.
{20218}{20277}Na taj naËin, moûeö da pojedeö viöe.
{20278}{20343}Pogledaj, Mama! Prijatelj!
{20345}{20405}Pa, zdravo.
{20408}{20482}Nisam znao da ovde|u okolini ima Oötrorepih.
{20483}{20545}Baö lepo!
{20548}{20617}Mi smo upravo stigli.
{20620}{20705}Ti i tvoja porodica|morate doÊi da nas vidite.
{20875}{20990}Prijatelj!|Da, izgleda da je veoma fin.
{21286}{21344}To nije toliko loöe.
{21346}{21421}Samo napravi da ti|se ivice usana spuste.
{21542}{21626}Pa ne mogu viöe|da se spuste.
{21628}{21708}Sluöaj, ako hoceö da se oseÊaö ljuto,
{21711}{21807}moraö da izgledaö ljuto|i da se ponasaö ljuto.
{21809}{21886}- Ali ja ne znam kako.
{21888}{21956}Vidim da Êemo morati|da poËnemo od poËetka.
{22038}{22133}Kada u stomaku oseÊaö|neprijatnost i vrucinu  
{22134}{22233}Kao da je napunjen|balonËiÊima  
{22236}{22353}I to zujanje|u tvojoj glavi  
{22356}{22448}Koje te Êini tuûnim i plavim    
{22450}{22563}Nemoj iÊi unaokolo pretvarajuÊi se  
{22565}{22667}da je sve|u redu sa tobom  
{22670}{22784}Kada oseÊaö|neko bockanje  
{22785}{22923}-Uradi ono öto rade trorogi  |- öta vi radite?
{22925}{23015}Mi postanemo lj-lj-lj-lj-lj-ljuti  
{23017}{23100}Kako to radite?
{23158}{23275}Prvo, napravi straöan|izraz lica  
{23278}{23388}Ne podiûi glavu    
{23390}{23493}Zadrûi dah|dok ne poplaviö
{23496}{23613}-I dok ti oËi|ne pocrvene
{23616}{23698}Napravi opasan izraz lica|naboraj nos  
{23701}{23810}Kao da si upravo pomirisao|neöto ruûno  
{23812}{23924}Okreani svoje nasmejano lice|naopaËke    
{23925}{24002}Tako treba da izgledaö  
{24004}{24068}Kada si ljut  
{24112}{24238}Sad, stavi ruke na kukove|ramena nazad  
{24240}{24315}Lupi nogama u praöinu  
{24354}{24445}äutni neku stenu|ali ne suviöe jako  |Oh!
{24448}{24534}Zato öto moûe stvarno da boli  
{24571}{24643}Pretvaraj se|da si oötrozubi
{24646}{24765}Ja mogu da se pretvaram|da sam tvoj tata  
{24768}{24871}Mrmljaj i mumlaj|i gunaj jako glasno  
{24872}{24957}Tako treba da zvuÊiö  
{24960}{25020}Kada si ljut  
{25078}{25190}Kada postoji ljutnja u tebi|ili tuga  
{25191}{25286}Moraö da pustiö napolje|to öto je unutra  
{25288}{25404}Frkci jako|i lupi nogama  
{25407}{25493}Ispravi kljun|i viËi  
{25494}{25564}- Reci, "Ne!"|- Ne!
{25565}{25607}- Reci, "Grrr!"|- Grrr!
{25608}{25672}- Reci, "Ne!" "Grr!"|- Ne! Grr!
{25674}{25741}Sada si ljut!
{25744}{25859}I jednom kad se naljutiö,|moraö da ostaneö ljut. Ne odustaj.
{25861}{25928}Oh, ali öta ako|poËnem da se oseÊam bolje?  Ne!
{25931}{26036}- Budi ljut dok nepiËnu da puzel.|- Dok oni öta?
{26039}{26131}- Puze!|- Oh. Uredu, onda,ali ja ne mogu...
{26133}{26244}I kada si stvarno|stvarno, stvarno, stvarno|stvarno ljut  
{26246}{26343}I kad moraö|da ispustiö paru  
{26345}{26408}- Udahni duboko
{26410}{26474}Zabaci unazad glavu  
{26476}{26538}Stani na vrhove prstiju  
{26541}{26638}I vriöti   
{26639}{26711}Ona je ljuta na nekog.
{26760}{26819}Vidiö?
{26897}{26988}Nisam znao da je potrebno toliko|truda da budeö ljut.
{27409}{27483}Hej, deda, l...|Huh?
{27622}{27698}Oh, ne.|Izgleda prilicno bistar,
{27700}{27758}ali na ûalost,
{27760}{27870}Nalazim da ima|veoma negativan stav.
{27873}{27935}On izgleda|ne shvata...
{27938}{28060}da sam ja najstariji i najmudriji|u Velikoj Dolini.
{28062}{28150}Trebalo bi da nauÊi da poötuje.
{28548}{28615}Malo stopalo, jesi li to ti?
{28656}{28713}Da, deda.
{28716}{28810}Tvoja baka|je poËela da brine.
{28813}{28905}éao mi je.|Da li si ljut na mene, deda?
{28907}{29001}Zaöto bih bio ljut|na tebe, Malo stopalo?
{29090}{29154}Video sam te da razgovaraö|sa Mr. Thicknose.
{29157}{29277}Oh, Malo stopalo, znam|da nisi bez poötovanja.
{29279}{29337}Ali iz nekog razloga,
{29339}{29429}nisi baö|u dobrim odnosima|sa Mr. Thicknose.
{29431}{29496}Ja ne znam zaöto.
{29497}{29579}Pokuöavam da sluöam|i postavljam dobra pitanja.
{29581}{29687}Ponekad mislim da|on naprosto ne voli decu.
{29689}{29862}Ipak, Mr. Thicknose|se prijavio da podeli svoju mudrost|sa vama mladima,
{29864}{29967}da vam podari korist|svih svojih znanja...
{29968}{30042}koja je stekao|tokom godina.
{30044}{30115}Znam.
{30212}{30269}Znaö, Malo stopalo,
{30272}{30333}Baka i ja imamo tebe,
{30335}{30423}ali Mr. Thicknose|nema nikog.
{30425}{30516}Stvarno, on nema niöta|osim svog dostojanstva.
{30519}{30594}Dostojanstvo?|äta je to?
{30597}{30687}To je kad oseÊaö|da si cenjen...
{30689}{30776}da imaö öta da ponudiö|i kad drugi to znaju.
{30779}{30882}To je veoma vaûno|oseÊanje, Malo stopalo.
{30884}{30968}Nikad nemoj raditi niöta|öto bi nekom oduzelo taj oseÊaj.
{30969}{31041}NeÊu, deda.
{31234}{31323}I neÊu reÊi baki|niöta o ovome.
{31325}{31387}To Êe biti naöa mala tajna.
{31389}{31449}Hvala, deda.
{31997}{32070}Hmm?
{32108}{32174}Wow!
{32177}{32246}Wow!
{32288}{32347}Wh-Wh...
{32438}{32496}Tako divno.
{33096}{33165}äta je to?
{33167}{33277}Smrznute nebeske zvezde|koje ti padaju na glavu?
{33278}{33359}Uh-huh.|A kada ih dodirneö,|pretvore se u vodu.
{33361}{33469}Ali, Malo stopalo, stvarno.
{33471}{33534}Poznato je da|tako neöto postoji,
{33536}{33595}ali se nikad nije desilo u Velikoj Dolini.
{33597}{33733}Samo na udaljenim mestima|od kojih lutalice dolaze|ovamo da se sklone.
{33735}{33841}Ali ja sam video!|ja...
{33843}{33950}Ok. Izvini.
{33952}{34015}U redu.
{34017}{34134}Sad, da se vratimo|naöoj preaönjoj diskusiji.
{34137}{34227}Ti mi verujeö, zar ne?
{34229}{34338}Oh, naravno. Ja ti verujem.|Ali ipak, ja svemu verujem.
{34800}{34899}Roar! Vee!|Pogledajte mene!
{34902}{35026}Roar, roar, roar!
{35108}{35200}Ja sam plivajuÊi oötrozubi.|Roar!
{36078}{36175}Daki, mislim da se Spike|oseca izostavljenim.
{36177}{36265}Ne mogu da izdrzim|ja mogu da plivam a Spike ne moze.
{36267}{36334}Ja sam plivaÊ,|a on nije.|Ne, ne, ne.
{36465}{36523}Hiya! Hiya!
{36525}{36618}Huh?
{36621}{36690}Pa, zdravo tamo.|Ponovo se sreÊemo!
{36693}{36786}A gde je tvoja porodica,|dragi?|Zdravo.
{36789}{36918}- Ja sam njegova majka.|- Stvarno? Bas fino!
{36921}{37009}Pa, vidiö,|Spike je izgubio roditelje i...
{37012}{37112}Spike!|Da li mu je to ime?
{37114}{37200}Spike, Spike, Spike!|Da. InaÊe,
{37202}{37280}nije bilo drugih Oötrorepih|u Velikoj Dolini, i...
{37283}{37371}- Do sada.|- Pa, da.
{37374}{37432}I tako ste ga primili|Tako je.
{37434}{37573}- Oh, ja mislim da je to divno.|- Pa, naravno,|nije uvek bilo tako lako.
{37575}{37643}Hej, pazite, vas dvoje!|Pomerite se!
{37645}{37733}Pazite!
{37735}{37853}Mama! Mama!
{37854}{37913}Oh, Daki, samo plivaj, draga.
{38007}{38081}Hmph!
{38115}{38183}Upravo mi je palo na pamet...
{38185}{38309}Da li misliö da bi Spike|voleo da poseti moje krdo?
{38311}{38381}Jea, jeah!|Poseta!
{38383}{38498}- Pa, ja ne...|- Pa, ne. Mislim,|samo na jedan dan. Mogao bi...
{38499}{38603}Pa, mogao bi da vidi|kako ûivi njegova vrsta.
{38605}{38691}Oh. Uh...|Da li bi voleo to, Spike?
{38694}{38754}Aha.
{38756}{38860}Super! Super!|Hmph!
{38863}{38962}Pa, vratiÊu ga pre|nego öto veliki krug napusti nebo.
{39002}{39060}Doite, deËaci.
{39345}{39402}Poseta! Zabava!
{39454}{39514}I ako ti se bude dopao|danaönji dan,
{39516}{39600}moûda bi Ëak mogao|da ostaneö duûe.
{40075}{40139}Da li cemo se|vratiti u vodu, Daki?
{40142}{40223}Moûda kasnije.
{42577}{42643}Tako je.|Spike je izgubio svoje roditelje...
{45356}{45425}Huh?
{45428}{45501}Mama, öta je to?
{45502}{45574}Da li sanjam?|Oh!|Ne, dragi.
{45576}{45634}Stvarno je.
{45721}{45870}Ooh!|Sve je tako... svetlucavo.|Tako je lepo!
{45871}{45969}Da li misliö da i Spike moûe to videti?
{45972}{46056}Sigurna sam da moze,|Daki.
{46477}{46534}Ahhh!
{46963}{47052}Huh? Rakao sam im!
{47054}{47112}Wow!
{47401}{47464}Da li si ikada|ranije ovo video, dragi?
{47467}{47623}Ne, ali sam Êuo za to.|Od toga su Lutalice pobegle|u Veliku Dolinu.
{47625}{47685}A sada|je to doölo i ovde.
{47687}{47765}Moramo da razgovaramo|sa Mr. Thicknose.
{47768}{47834}Pa, uh...
{47836}{47946}Nisam znao da Êe se ovo|desiti u Velikoj Dolini.
{47949}{48069}- Za sve moje godine...|- Pa zaöto se to sada dogaa?
{48071}{48160}Ova stvar je uûasna!|Ona je svuda!
{48161}{48227}Kaûem.|Tako je klizava,
{48229}{48308}da skoro nisam mogao da se|popnem na brdo do mog gnezda.
{48311}{48401}Aha! On se okliznuo unazad|pravo na moj nos!
{48403}{48497}Bilo je stvarno zabavno.
{48499}{48590}Vidiö?|Bele zvezde sa neba,|baö kao öto sam ti rekao!
{48593}{48649}äta si rekao,|Malo stopalo?
{48650}{48721}Idi napred, Malo stopalo.
{48722}{48825}Ja, uh... ja sam...
{48828}{48908}samo video neke bele iskrice|kako padaju proöle noÊi,|i rekao sam...
{48910}{48970}Rekao kome?|Kome si rekao?
{48973}{49095}Um, mojim prijateljima...|i Mr. Thicknose.
{49179}{49236}Ti si znao|da ovo pada?
{49239}{49305}DeËko je rekao neöto,
{49307}{49373}ali se Ëinilo tako neverovatno...
{49375}{49438}Stvarno smo se|razoËarali u tebe.
{49440}{49514}Mislili smo|da ti sve znaö.
{49517}{49590}I ja sam.
{49800}{49867}Evo dolaze Oötrorepi.
{49956}{50077}Vi ste Lutalice.|Sigurno ste videli|ovo i ranije.
{50079}{50212}Oh, da.|Kada smrznute zvezde poËnu da padaju sa neba,|pa, tada mi odlazimo.
{50215}{50332}Ali tako samo mi radimo.|Znate, mi prilicno|jedemo sve vreme,
{50333}{50420}a zelenilo je|malo teze naÊi|ispod svega ovoga.
{50422}{50524}- Oh, da.|- Mislim da ce se to ovde|u Velikoj Dolini...
{50525}{50584}vrlo brzo|pretvoriti u vodu.
{50691}{50773}Hmph!
{50776}{50844}Prekini, Spike!
{50926}{50994}Nije mi do toga.
{51370}{51457}- Hej, to izgleda zabavno!
{51900}{51988}Pazi, dete!|Oh! Oh!
{51990}{52048}éao mi je.
{52316}{52375}VratiÊu ti za ovo!
{52376}{52436}Whoa!
{53288}{53357}Oh!
{53435}{53492}Moûete vi to, momci!
{53527}{53610}Hej!
{53612}{53718}Dobar pogodak, mama!|Drago mi je da pomognem, dragi.
{54067}{54161}Hej, dugovrati,|evo ga dolazi!
{54861}{54930}Pa, vreme je da se krene|ka gnezdu.
{55011}{55084}Laku noÊ, Malo stopalo.|Laku noÊ, Sera.|∆ao. Laku noÊ.
{55087}{55144}Laku noÊ. Vidimo se.|Laku noÊ, Daki.
{55147}{55215}Laku noÊ!|Laku noÊ, Spike.
{55217}{55281}Ovo je bio dobar dan.
{55283}{55348}Da, da, da.
{55382}{55449}Hajde, Spike.|Idemo kuci.
{55549}{55650}Ako bi voleo da ostaneö|joö jednu noÊ, u redu je.
{55651}{55713}Je! Je!
{55715}{55806}Pa, doite, deËaci.|Idemo kuÊi.
{56445}{56560}Ja volim|bele pahuljice,|a ti, deda?
{56604}{56686}Da, Malo stopalo, volim.
{58261}{58344}Da li joö uvek|voliö bele pahuljice,|Malo stopalo?
{58432}{58507}M-M-Moûda ne toliko|koliko sam mislio.
{58591}{58657}∆ekaj, Malo stopalo.
{58659}{58744}Vidim neöto|öto ce ti se svideti.
{59044}{59102}Odbi, Thicknose!
{59104}{59213}Ali, ja sam...|Ja sam tako gladan.
{59216}{59299}Pa öta?|Svi su gladni.
{59302}{59439}Viöe skoro uopöte nema hrane,|i ako mene pitaö,|za sve si ti kriv!
{59441}{59519}Ja? Ali ja-ja...
{59521}{59654}Hajde, sad.|Ne moûeö kriviti Mr. Thicknose|za vreme.
{59656}{59745}Pa, moûda ne.
{59747}{59808}Ali ako je on toliko pametan,|zaöto nije znao...
{59810}{59943}da Êe bele iskrice|doneti sa sobom takvu hladnoÊu|koja Êe ubiti svu hranu?
{59944}{60075}Zaöto nas nije upozorio|da sklonimo malo zvezdanog liöca|dok ne doe toplije vreme?
{60078}{60184}Ali nisam mogao!|Mislim, kako sam mogao...
{60185}{60274}Ovo se nikada ranije nije|dogodilo u dolini.
{60277}{60374}Zaöto bi oËekivali da Êe on|znati kako ce ovo izgledati?
{60376}{60510}Pa, svi kaûu|da je on bio svuda|i da sve zna.
{60513}{60588}Ako mene pitate,|on uopöte ne zna mnogo,
{60591}{60649}i ne mislim|da mu treba dozvoliti...
{60651}{60753}da zbunjuje mlade|svojim glupim idejama!
{60754}{60841}- Gosh.|- Zaista, Mr. Three Horn.
{60844}{60905}Mislim da ste|nerazumni.
{60907}{60986}Pa, ja ne mogu drugacije.|Gladan sam!
{60989}{61064}To je razlog zbog kog|smo odluËili da odemo.
{61067}{61186}Ali, nemojte da me pogreöno razumete|samo zato öto sam vikao na njega.
{61189}{61252}Niko nije rekao|da morate da odete.
{61255}{61321}Znam, ali jedva da ima|dovoljno hrane u dolini...
{61323}{61382}za one koji su ûiveli ovde|sve vreme.
{61384}{61487}Mi Oötrorepi jedemo viöe|nego öto je naö poöten deo.
{61490}{61561}Osim toga, mi smo navikli|da se kreÊemo unaokolo.
{61562}{61668}I otiÊiÊemo sutra|pre nego öto veliki krug|bude visoko na nebu.
{61671}{61776}SreÊno.|Nadam se da Êete naÊi hranu.
{61779}{61840}Pa, ne moûe nam biti|gore nego ovde.
{62152}{62282}Hej, probudi se.|Da li si Êuo vesti?|äta?
{62285}{62364}Oötrorepi|napuötaju Veliku Dolinu.
{62366}{62470}Hmm.|Da, da, da!
{62530}{62598}SreÊno svima.
{63070}{63129}Ne brini, Spike.
{63193}{63271}Siguran sam da Êe se|vratiti jednog dana.
{63306}{63424}Spike!
{63575}{63671}éao mi je öto se ovo dogodilo.|Nismo svi mi za to|da vi odete.
{63673}{63786}Mi cemo biti dobro.|Mi smo lutalice.
{63842}{63971}Ne znam baö kako|da pitam ovo,|ali da li bi on...
{63974}{64069}äta? Ma, ne.|Siguran sam da ne bi...
{64070}{64146}Mislim, mi smo njegova porodica.|On...
{64204}{64280}Uh... ja Êu ga pitati.
{64417}{64475}Da li ûeliö da ideö|sa njima, Spike?|Huh?
{64477}{64535}RazumeÊemo ako ûeliö.
{64537}{64615}Daki i ja ti samo|ûelimo najbolje.
{65043}{65136}Ako je to tako teöko odluÊiti,|ja Êu da to uradim za tebe.
{65138}{65198}Idi, Idi, Idi!
{65303}{65386}Oh! Oh!|Oh! Oh!
{65388}{65474}Zbogom, Spike.|NedostajaÊeö nam.
{65537}{65621}Mi Êemo se vratiti uskoro,|zar ne, Spike?
{65623}{65701}Kada sa zemlje nestanu|bele iskrice.
{65704}{65796}Ma, mi Êemo se videti|i pre nego öto misliö.
{66443}{66562}Ja ne razumem zaöto bi Spike|napustio sopstvenu porodicu.
{66565}{66645}Mislim, öta je onda|porodica uopöte?
{66862}{66965}Da li je to neko|ko izgleda kao mi  
{66967}{67073}Da li je to neko|ko se ponaöa kao mi  
{67075}{67178}Da li je to neko|ko spava pored nas  
{67181}{67265}u gnezdu  
{67267}{67398}Da li je to neko|ko govori kao mi    
{67399}{67509}Ima rep ili kljun kao mi  
{67512}{67654}Da li je to neko|koga najviöe volimo  
{67700}{67843}Ja mislim da je porodica, porodica  
{67845}{67934}viöe od prijatelja  
{67935}{68085}Kada ste porodica, porodica    
{68117}{68214}ljubavi nema kraja  
{68255}{68323}Ne mogu da verujem da Spike|stvarno odlazi.
{68326}{68449}Mozda on ûeli da ode sa njima.|Izmeu ostalog, mi nismo njegova porodica.
{68502}{68567}On ne izgleda kao mi  
{68621}{68694}On ne jede kao mi  
{68695}{68793}Da, ali on ipak voli|da se igra  
{68796}{68858}kao mi  
{68912}{69045}Hmm.|On ne hoda kao mi  
{69046}{69135}On uopöte ne govori  
{69137}{69231}Ali pomisli samo|na sve stvari  
{69233}{69315}kroz koje smo zajedno proöli  
{69346}{69474}On je porodica, porodica  
{69477}{69548}I ako moûe otiÊi  
{69551}{69708}On je od uvek bio|naöa porodica
{69740}{69875}I porodica Êe ostati  
{69987}{70101}Pretpostavljam da neko|koga voliö  
{70104}{70178}moûe da te naljuti  
{70237}{70392}To je neöto|öto moramo da prevaziemo  
{70452}{70540}Iako su|porodice razlicite  
{70542}{70661}Jedno je isto   
{70662}{70790}Srce svake porodice  
{70793}{70880}je ljubav  
{70914}{71082}I porodica, porodica    
{71084}{71180}je neöto jako i fino    
{71183}{71328}Ti Êeö uvek biti|deo njegove porodice  
{71330}{71476}I on Êe uvek biti    
{71479}{71613}veoma, veoma veliki deo    
{71615}{71786}moje porodice  
{72023}{72096}Porodica   
{72297}{72366}Daki,|to je za njegovo dobro.
{72367}{72435}Spike treba viöe hrane|nego nama.
{72438}{72559}- Znam.|- Pored toga, oni Êe se vratiti.
{72561}{72644}»uo si öta je|Tippy-eva mama rekla.|Znam.
{72645}{72752}I on nikad nije imao|priliku da provede vreme|sa drugim Oötrorepim.
{72754}{72850}Njemu je potrebno da bude|sa svojom vrstom.|Znam!
{72853}{72936}I jasno je|da oni vole Spike.
{72939}{73006}Njihovo strpljenje|i ljubaznost i...
{73008}{73089}- Znam, u redu? Znam!|- Daki!
{73091}{73156}éao mi je, mama.
{73158}{73259}U redu je, draga.|Razumem.
{73404}{73493}Um, mi smo rekli|Mr. Thicknose...
{73495}{73555}da Êemo se sastati sa njim|poslednji put.
{73557}{73639}Da li je u redu|da ja odem?|Naravno, dragi.
{74821}{74953}Oh, meni ce sigurno|nedostajati Spike!
{75014}{75073}Aha. I meni.
{75136}{75242}Hej, ako je naöao|neke prijatelje koje viöe voli,|to je njegova stvar.
{75244}{75370}Kladim se da neÊe proci|puno vremena dok ne zaboravimo|kako on uopöte izgleda.
{75372}{75456}Pa, moûda.
{75459}{75560}- ∆ao, deco.|- Zdravo, Daki-eva mama.|- »ao.
{75562}{75640}Gde je Daki?|Da li je Mr. Thicknose otiöao?
{75642}{75718}Uh...|Huh?
{75830}{75925}To joj je pomoglo|da razmiölja o neËem drugom|osim o Spike.
{75990}{76069}- I vama nedostaje.|- Baö nam nedostaje.
{76071}{76142}Aha.|I meni.
{76179}{76238}Pa, trebalo bi da krenem.
{76239}{76333}Ona me verovatno vec Ëeka|u gnezdu.
{76334}{76449}Zdravo, deco.|Ostanite toplo.|Zdravo!
{76451}{76587}Zaöto bi Daki rekla njenoj mami|da se sastajemo sa Thicknose?|To nije istina!
{76589}{76648}Ne znam.
{76649}{76734}Moûda nije htela|da njena mama zna|gde ona stvarno ide.
{76737}{76803}A gde ide?
{76863}{76920}Kladim se da znam.
{76975}{77081}Spike! Spike!
{77165}{77301}Nisam znala da Oötrorepi|mogu da hodaju tako brzo.
{77304}{77361}Ne, ne, ne.
{77532}{77606}Pazljivo.|Klizavo je ovde.
{78090}{78179}Tippy, Spike,|ne zaostajte.
{78223}{78292}Mmm.
{78347}{78457}Whoa!
{78798}{78891}Ah, öta se to deöava nazad...
{79085}{79150}Zabava, zabava, zabava!
{79152}{79268}Moja lea!
{79537}{79621}Pa, ako je Daki|otiöla za Spike,
{79624}{79682}zaöto samo ne kaûemo|njenoj mami?
{79684}{79836}Moûda greöim,|ali nema svrhe|da je brinemo.
{79838}{79941}Zemljotres!
{80000}{80103}- A öta vi|to radite?|- Mr. Thicknose?
{80104}{80191}Oh. Zdravo, deco.
{80193}{80278}äta-öta radiö|ovde sam?
{80279}{80406}Molim te, Malo stopalo.|Bez pitanja.
{80453}{80511}Malo stopalo, hajde.
{80513}{80626}Moramo da pronaemo Daki|i vratimo se pre nego|öto odrasli primete da nas nema.
{80628}{80725}Da, ok.
{80728}{80801}Zdravo, Mr. Thicknose.
{80963}{81053}Aha. Daki je sigurno|proöla ovuda.
{81055}{81141}Pa, idemo.
{81143}{81230}Deco!|Mr. Thicknose?
{81232}{81319}Da li sam|dobro razumeo...
{81321}{81476}da idete|u nepoznato...
{81478}{81555}bez dozvole|roditelja?
{81557}{81645}Ne.       Da.|Moûda.
{81707}{81810}Ok, da, ali|moramo. Daki|tamo negde sama.
{81812}{81898}Ja to nikako|ne mogu da dozvolim.
{81900}{81973}Ali...|Ako vaöe porodice|saznaju...
{81975}{82070}da sam vas pustio da|napustite dolinu bez nadzora,
{82073}{82170}Nikad viöe ne bih|mogao da se pojavim ovde.
{82247}{82338}Zato,|ja idem sa vama.
{82340}{82395}Idete?|Huh?
{82397}{82455}OdliËno.
{82576}{82646}Deco...
{82648}{82707}saËekajte, |molim vas.
{82709}{82801}Viöe nisam tako mlad|kao öto sam bio.
{82803}{82910}on nije viöe mlad kao öto niko bio nije.|Ne budi zao.
{82912}{82978}Zaöto moramo da ga pustimo|da poe s nama?
{82980}{83044}Zato öto ako ga ne pustimo,|reÊiÊe odraslima.
{83046}{83123}Pored toga, on je svuda bio|i sve je video.
{83125}{83213}On nam moze pomoci da|naemo put kroz nepoznato.
{83271}{83353}Nadam se da je tako.
{83543}{83660}Evo ga.|Ovo su|tragovi Oötrorepih.
{83663}{83776}Izgleda da ih je Daki pratila|joö od doline.
{83779}{83847}Onda treba da pratimo|ove tragove.
{83850}{83922}Oötrorepi ne mogu biti|previöe daleko.
{83924}{84009}Oni se krecu uûasno sporo,|znate.
{84011}{84099}Aha, za razliku od nas.
{84101}{84226}Ja imam ideju.|Ja Êu leteti, pa moûda|primetim Daki negde ispred nas.
{84228}{84312}Baö sam to|hteo da predloûim.
{84606}{84692}- Joö uvek ne vidim niöta.|- Leti viöe!
{84824}{84911}Joö uvek niöta.
{84912}{85022}Postaje mi baö hladno|ovde.
{85100}{85199}äta se deöava|sa Petrie?|Baö Ëudno leti.
{85202}{85301}Boûe. Ima|smrznute vode na njegovim krilima.
{85304}{85420}Krila su tako teöka.
{85422}{85498}Ne mogu da ih pomerim.
{85500}{85574}Petrie!
{85647}{85719}Ne mogu da gledam!
{85945}{86023}- Ooh!
{86025}{86083}Uspeo je!|Da!
{86085}{86195}Oh, boûe.|To je bilo blizu.
{86197}{86250}- Dobro sam!
{86301}{86390}Kakva... je to buka?
{86392}{86505}- Ne gledaj u mene.
{86507}{86565}Huh?
{86744}{86824}- Pazi!
{86826}{86922}TrËi!|Hajde! Ovuda!
{86925}{86977}Hajdemo!|Kreni!
{87090}{87156}Brûe! Brûe!
{87646}{87704}Da li ste dobro,|deco?
{87706}{87783}Aha.|I ja.
{87833}{87908}I ja.
{87909}{87982}- Oh, moj boûe.|- öta?
{87984}{88050}Prolaz|ka dolini.
{88084}{88168}Nestao je.|Zaglavljeni smo ovde?
{88170}{88266}A takoe i Spike|i Daki.
{88447}{88550}Ja cu samo reci,|"U redu je, Spike.|Opraötam ti,"
{88553}{88625}i on Êe se vratiti|samnom.
{88626}{88731}Ali öta ako on|ne oprosti meni?
{88734}{88803}Oh, ne, ne, ne.
{88856}{88961}Barem je lako pratiti|tragove Oötrorepih.
{88964}{89032}Jao!
{89192}{89264}Ovo nisu|tragovi Oötrorepih stopala.
{89265}{89373}Nadam se da ce, öta god|da je napravilo ove tragove,|nastaviti da ide napred.
{89375}{89455}Aha, aha, aha.
{89458}{89539}Sigurno je usamljeno|ovde.
{89542}{89630}Spike! Spike!
{89633}{89696}Spike! Spike!
{89736}{89795}Hej!|To je smeöno.
{89797}{89885}Eho.|Spike!
{89886}{89977}Spike! Spike!|Spike!
{89979}{90079}Huh? »ak i moji koraci|imaju eho.
{90784}{90856}Pogledaj|one stene.
{90899}{91002}Moûeö li da zamisliö|koliko dugo|su vec tamo?
{91004}{91080}Skoro kao|da su nas|Ëekale.
{91082}{91145}Ja taËno znam|kako su pale.
{91147}{91230}Divno.|Baö divno.
{91231}{91306}Nikad nisam video|niöta slicno.
{91309}{91381}- Nikad?|- Ma, ne, ja...
{91382}{91456}Uh, to je, uh...
{91459}{91549}Mr. Thicknose,|ne volim öto ovo pitam,
{91551}{91629}ali da li je ovo vaö prvi put|u nepoznato?
{91631}{91708}Pa, ja...|Pa, ja...
{91800}{91858}Daki!
{91945}{92070}Oh, zaboga.
{92587}{92668}Petrie, Sara,|pomozite mi!
{93404}{93462}Hej, ruûno.|Hoceö da se igraö?
{93756}{93826}Mr. Thicknose!|Sklonite se sa puta!
{93829}{93910}Molim!
{93913}{93999}Oh, vidim.
{94360}{94419}OdliÊno uraeno!
{94451}{94552}Jea!
{94553}{94612}Tako sam sreÊan|öto vas vidim.
{94614}{94711}Da, da, da.|Osim tebe.|Huh?
{94714}{94771}Za sve si ti kriv.
{94774}{94848}Ti si mi rekao da budem ljut|na Spike, i pogledaj|öta se desilo.
{94849}{94955}Ja? Ali ja sam samo rekao|da izraziö svoja oseÊanja.
{95002}{95077}Znam.
{95120}{95178}A moja oseÊanja su|bila ljuta.
{95180}{95306}éao mi je.|Ni ja ne ûelim|da budem ljut na tebe.
{95308}{95429}Ja ne volim da budem ljut.|Ne, ne, ne.
{95432}{95526}- Pa, da li si pronaöla Spike?|- Mmm-mm.
{95529}{95649}Pa, barem je|Mr. Thicknose ovde|da nam pomogne da naemo put.
{95651}{95746}Da, pa,|bojim se da, uh...
{95748}{95813}Da je...
{95815}{95945}Mislim da je doölo vreme|da priznam.
{95946}{96044}Vidite, uh...|Kako da ovo kaûem?
{96047}{96138}Stvarna veliËina|mog iskustva...
{96139}{96210}izvan|Velike Doline je...
{96212}{96301}malo manja|nego öto mislite.
{96369}{96512}Mislite... da niste|bili u nepoznatom toliko|puta koliko svi misle?
{96514}{96640}- TaËno.|- Koliko puta ste bili|ovde?
{96643}{96737}RaËunajuÊi i ovaj put?|Jednom.
{96740}{96851}Ohh.
{97041}{97157}Kako bi situacija|mogla biti gora?
{97219}{97291}Morao si da pitaö,|zar ne?
{97387}{97496}Ma, ne, draga.|Nismo videli|Daki.
{97498}{97584}Tako sam zabrinuta.|Postaje kasno.
{97586}{97684}Da li bi htela da|ti pomognem da je potraûimo?
{97687}{97791}Ne, ne. Samo se odmarajte|i pokuöajte da se zagrejete.
{97793}{97867}Verovatno je sa|Malo stopalo i ostalima.
{97869}{97952}Oh, nadam se da|nisu odlutali daleko...
{97954}{98012}po ovakvom vremenu.
{98108}{98171}Spike!
{98352}{98410}Spike!|Hmm?
{98412}{98470}Spike?
{98472}{98530}Spike?
{98720}{98796}Daki!
{98798}{98886}Sara! Sara!
{98951}{99021}Petrie!
{99083}{99174}Malo stopalo!
{99485}{99543}Drago mi je da je gotovo.
{99545}{99602}Meni je hladno.
{99672}{99788}I gladan sam.|I ûedan.
{99791}{99873}Voleo bih|malo vode.
{99876}{99962}I ja.|Hej!
{99963}{100022}Eno je voda.
{100256}{100313}Ta voda je tvrda.
{100384}{100481}Hej. Kao ona|öto mi se nahvatala na krilima.
{100841}{100933}Mr. Thicknose!|Vratite se!|Whoa!
{100936}{101055}»ekajte nas!|Whoa!
{101416}{101518}- Ne, ne, ne!|- Stop, stop, stop!
{101723}{101808}To nije dobro.
{102063}{102168}Oh boûe.|Ovo je priliÊno toplo.
{102216}{102307}I nije duboko.|Ja stojim|na dnu.
{102309}{102437}I ja!|Pa, sorta.
{102469}{102561}Ovo baö prija.
{102564}{102642}Zaöto je ovako|toplo, Mr. Thicknose?
{102795}{102892}Pa, izgleda da je to|neka vrsta podzemnog izvora.
{102895}{103007}Vidite? Tamo dole|kljuËa topla voda.
{103085}{103188}Ahh! Mmm!|»ak su i stene tople.
{103261}{103330}Mr. Thicknose,|da li ste nekad videli|ovakvo mesto...
{103332}{103410}Ne, nisam.
{103412}{103484}éao mi je öto moram|da kaûem da nisam.
{103486}{103604}Ali sam Ëuo o tome|od lutajuÊih krda koja|su proöla kroz Veliku Dolinu,
{103607}{103697}I koliko mogu da se setim...
{103699}{103786}kada postoji|ovakva toplota i voda...
{103789}{103897}tu verovatno ima...|Zelene hrane.
{103899}{104021}Mmm. Nije loöe.
{104024}{104105}Ahh!
{104108}{104204}- Mr. Thicknose?|- Da, Malo stopalo?
{104206}{104277}Kako to da ste priËali|sve te izmiöljotine...
{104279}{104344}o tome kako|ste svuda bili|i sve videli?
{104401}{104527}Znaö, Malo stopalo,|nikad nisam imao nameru da postanem|takav laûov.
{104530}{104599}To se samo...
{104645}{104717}desilo.
{104719}{104834}Kad sam bio mlad,|bio sam veoma stidljiv.
{104837}{104925}Nisam bio poznat.
{104927}{105018}Ali kad su lutalice priËale|o dalekom nepoznatom,
{105020}{105094}zapamtio sam svaku reË.
{105127}{105194}I kako sam rastao,
{105196}{105329}priËao sam te priËe|kao da sam ih i sam proûiveo.
{105332}{105400}Svima su mislili,
{105403}{105470}Bio sam dobar,|bio sam mudar,
{105472}{105569}za sve  
{105570}{105633}osim za tebe  
{105635}{105725}To je razlog|zaöto sam imao tolike muke|sa tobom, Malo stopalo.
{105727}{105853}Ti si tako radoznao, tako pametan,|i pitaö tako dobra pitanja,
{105854}{105973}pa sam se plaöio da Êeö me|uhvatiti u laûi,|otkriti moju tajnu.
{105974}{106089}- Oduzeti ti tvoje dostojanstvo?|- Da, pretpostavljam da je tako.
{106092}{106223}Vidiö,|  svako ûeli|da bude vaûan  
{106225}{106350}Svako ûeli|da se o njemu Ëuje  
{106352}{106490}Svako zeli da bude|u centru kruga  
{106492}{106610}Kada ti prijatelji poveruju|u svaku reË
{106612}{106742}nebitno koliko si blizu|jajetu
{106744}{106866}ili koliko star|ti Êeö odrasti    
{106869}{107010}Svakom treba|neko da ga sluöa  
{107051}{107154}»ak i nekom kao meni  
{107393}{107514}Svako ûeli|da bude poötovan  
{107516}{107644}Svako ûeli|da bude voljen  
{107647}{107767}Bez obzira da li imaö|tri roga na glavi  
{107769}{107888}- ili oötar kljun  |- ili öiljat rep  
{107890}{107999}Kada ûeliö da|zaseniö druge  
{108002}{108114}Moûda kaûeö stvari|koje nisu sasvim istinite  
{108151}{108281}Svako nekad padne|u iskuöenje da slaûe  
{108327}{108452}»ak i neko dobar|kao ti  
{108544}{108660}Mi zelimo da nam|se ljudi dive  
{108662}{108793}Mi ûelimo da se|neko brine za nas  
{108795}{108915}éelimo da|budemo razliÊiti  
{108918}{109067}I da znamo da ostali|znaju da smo tu  
{109125}{109253}Ali svako ima|svoj sopstveni znaÊaj  
{109256}{109385}To je ono öto|sam uvideo  
{109387}{109503}Svako ima|sopstveno specijalno mesto    
{109505}{109563}u gnezdu|u krdu
{109565}{109625}U porodici
{109627}{109699}Poötovanje nije neöto    
{109702}{109765}öto moûeö nekog|naterati da ti pruûi
{109768}{109860}To je neöto|öto moraö da stekneö
{109897}{109955}Ko bi pomislio
{109957}{110080}da posle ovoliko vremena
{110082}{110175}ima joö stvari|koje moram da nauËim
{110335}{110465}I hvala vam svima|öto me uËite...
{110468}{110537}da nikad nisi 
{110540}{110625}suviöe star
{110661}{110734}da uËiö  
{111115}{111215}Voleo bih kada bi odrasli bili|ovde da uzmu neöto od ove hrane.
{111217}{111327}I Spike.|Jea.|I Spike.
{111330}{111448}Kladim se da ima dovoljno zelene hrane|da nam traje dok|ne nestanu iskrice sa zemlje.
{111451}{111557}Ali prolaz|ka dolini je zakrËen.|SeÊaö se?
{111559}{111695}Odrasli su svi|u klopci,|a mi smo zaglavljeni ovde.
{111698}{111788}I izgubljeni.
{111790}{111855}Ne. Nismo se izgubili.
{111857}{111945}Ja znam to|visoko, stenovito mesto.
{111946}{112013}TaËnije, nikad ga nisam|video, naravno,
{112015}{112095}ali su mi ga opisivali|mnogi putnici.
{112097}{112192}Dolina je taËno|sa druge strane.
{112194}{112291}Ja taËno znam|gde smo.
{112294}{112418}- Nije da nam to neöto znaËi.
{112421}{112499}»ekaj.|Ne misliö valjda da...
{112500}{112597}- Uh-huh!|- Ali mi ne moûemo!
{112599}{112682}Mislim, naöa vrsta|ne moûe...
{112684}{112780}Mi ne moûemo da se popnemo|uz tako neöto!
{112783}{112852}Da li moûemo?
{113034}{113099}Ooh!
{113325}{113454}Nema svrhe.|Posle te oluje,|potpuno sam izgubljen.
{113456}{113514}I iscrpljen.
{113635}{113759}Oh, ne plaËi, Tippy.|PronaÊiÊemo hranu.|»ekaj samo.
{113924}{114044}Oh, Spike. I ti?|éao mi je, ja...
{114134}{114201}Da li oseÊaö|neöto, Spike?
{114203}{114272}Mm-hmm.
{114273}{114345}OseÊate li hranu?
{114484}{114597}- Da li mislite da je moûete pronaÊi?|- Mmm-hmm.
{114598}{114691}Spike zna kuda da ide.|Ja kaûem da ga pratimo.
{114694}{114780}Da ga pratimo?|On je samo dete.
{114782}{114925}äta imamo da izgubimo?|Ok, Spike, vodi nas.
{115059}{115120}Spike, Êekaj me!
{115538}{115632}Oh, nije dobro.|Zaöto me samo|ne ostavite ovde?
{115635}{115747}- Ne moûemo to da uradimo.|- Ja vas usporavam.
{115750}{115807}I iskreno,
{115810}{115888}ne mislim da|mogu viöe da idem.
{115889}{115968}Naravno,|moûda greöim.
{116368}{116473}äta se to deöava...
{116475}{116630}Sara, poûuri.|Idemo!|éurim, ok?
{116746}{116837}äta ja to radim?|Trabalo bi da ötitim|ove mlade,
{116840}{116897}a ne da trcim kao budala.
{117753}{117848}To mora da boli.
{117969}{118037}Mr. Thicknose?
{118040}{118126}Hvala.
{118127}{118216}SreÊan sam da mogu|da uzvratim uslugu.
{118217}{118311}Dugujemo zahvalnost|i tom oötrom zubu.
{118313}{118405}On nam je omoguÊio|podröku koja mi je trebala...
{118408}{118486}da stignem do vrha.
{118488}{118546}Jea!|Uspeli smo!
{118548}{118665}Tamo. Prolaz!|Kroz planine!
{118668}{118806}Pa, da. Baö ispod|te stene-mosta.|Moûemo da odemo do tamo.
{118808}{118899}Pa öta?|Skroz je blokiran,|zahvaljujuci Petrie.
{118902}{118962}Ne idemo tamo.
{119083}{119202}Skoro smo kuÊi.|Jeste, ali kako da odvedemo|naö narod do toplih izvora?
{119205}{119288}Baka i deka nikad|ne bi mogli da se popnu uz ove planine.
{119290}{119392}Kada bi samo postojao|naËin da prokrËimo prolaz.
{119394}{119488}Oh, ja ne zelim|da se ponovo penjem uz planinu.
{119536}{119626}Moûda neÊeö morati.|Mr. Thicknose,
{119628}{119730}da li se seÊate öta ste nas uËili|da Trorogi rade|ne bi li zvezdano liöÊe palo?
{119732}{119862}Uh... Ahh.|Sjajno!
{119864}{119943}Malo stopalo!
{120008}{120087}- Ima li traga?|- Ne mogu da ih naem nigde...
{120090}{120234}To je Ëudno.|ZvuËi baö kao Daki.
{120236}{120329}- And Malo stopalo.
{120332}{120389}Sara?
{120681}{120765}Ugh. Ne ide.
{120767}{120856}Nismo dovoljno glasni.
{120858}{120925}Ali vi jeste.|Huh?
{120928}{121018}Sara, naljuti se na|bele pahuljice.
{121020}{121133}- Huh?|- Baö se naljuti.|Baö, baö naljuti.
{121135}{121257}Oh, jea. Ok.
{121413}{121537}Tamo gore!
{121684}{121762}Gde se bili?|äta ste uradili?
{121764}{121858}U redu je.|Mr. Thicknose je bio sa nama|sve vreme.
{121860}{121959}Oh, yeah.|Siguran sam da|je bio od pomoÊi.
{121961}{122076}Bio je. Ipak,|on je najstariji i najmudriji|od svih nas.
{122138}{122231}- Izvini.|- U redu je.
{122233}{122297}Ali imaö ti joö|svaöta da nam objasniö,|mlada damo.
{122299}{122357}Znam, tata.
{122359}{122462}Ali zar ne biste radije|sluöali dok jedete?
{122463}{122546}Da li si rekla "jedete"?
{122918}{123026}Kako se oseÊaö?|Bolje nego öto sam|se oseÊao godinama.
{123028}{123116}ZahvaljujuÊi Malom stopalu|i njegovim prijateljima.
{123118}{123191}Jeste, deco|bili ste dobri.
{123193}{123303}I vi, Thicknose.|Kako ljubazno od vas.
{123305}{123371}Mr. Longneck,
{123372}{123456}PovlaÊim sve|öto sam rekao|o Malom stopalu.
{123457}{123547}On je izvanredan|deËko.
{123550}{123661}- Trebalo bi da ste ponosni.|- Jesmo.
{123722}{123787}Hvala, |Mr. Thicknose.
{123926}{123993}Voleo bi da je Spike ovde,|zar ne?
{123994}{124095}»ak se ne bih ûalio|ni kad usvinji gnezdo.
{124096}{124159}Ne, ne, ne.
{124161}{124242}Kada bi on samo mogao...
{124525}{124638}- Spike?
{124640}{124763}Spike! Vratio si se!|U redu!
{125614}{125686}Oh boûe!
{125793}{125851}Ima li dovoljno|da podelimo?
{125853}{125962}Ma, vi...|Ohh.
{125964}{126053}Naravno.|Dobrodoöli ste.
{126210}{126306}Mislio sam da ih nikad|viöe neÊu videti kako se igraju zajedno.
{126308}{126366}To je divan prizor.
{126398}{126478}Whoa-oa-oa-oa!
{126525}{126615}Spike! Budi paûljiv!
{126617}{126695}Spike!
{126698}{126779}- Oh, ne, Spike!|- Voda je dublja tamo!
{126782}{126872}- A Spike ne zna da pliva!|- Neka mu neko pomogne, brzo.
{127146}{127211}Mama!
{127731}{127823}Uhvatila ga je!|Da!
{127925}{128060}To je moja mama.|Moja mama je to uradila.|Aha, aha, aha.
{128139}{128247}Mama, uspela si!|Spasila si ga!
{128249}{128364}Naravno da jesam.|On je moj deËak.
{128462}{128572}Hmm. Ocigledno je|ko je Spike-ova prava porodica.
{128689}{128775}Uvek Ëemo biti zahvalni|öto si spasio naöe krdo.
{128778}{128866}I moûeö da nas posetiö|kad god budeö ûeleo.|Jel` tako, Tippy?
{128869}{128934}Tippy voli Spike!
{128936}{129020}I Daki voli Spike.
{129097}{129202}Od sad, moûeö|da hrËeö|koliko god hoÊeö.
{129205}{129324}I ja se viöe nikad|neÊu naljutiti. Ne, ne, ne.
{129532}{129597}Porodice Êe biti|sreÊne ovde...
{129599}{129715}dok veliki krug ne poËne|da zagreva zemlju|joö jednom,
{129716}{129794}i otapa bele|pahuljice...
{129797}{129878}omoguÊavajuÊi novom|ûivotu da buja,
{129881}{129959}cineci zemlju|ponovo zelenom.
{129961}{130046}Onda Êe moÊi da se vrate|u Veliku Dolinu,
{130049}{130152}gde Êe svi moÊi|lepo da se naspavaju...
{130154}{130220}Ëak i Daki.
{130245}{131745}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3u6cj|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
