{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{1224}{1411}NeÊu viöe dopustiti da itko|stane izmeu nas...
{1546}{1688}NeÊu viöe dopustiti da itko|stane izmeu nas...
{1744}{1787}Snimaju li?
{4854}{4890}Pomozite!
{5229}{5263}Cigareta.
{5360}{5397}UpaljaË.
{5584}{5656}Ne mogu verovati öto sam sanjala.
{5662}{5721}TrËala sam öumom, bosa.
{5723}{5793}Bila sam ozlijeena i|neko me je slijedio.
{5797}{5888}äta sam viöe trËala, bio je sve bliûe.|-Ko te je slijedio?
{5891}{5971}-Nije bio tip. To sam bila ja.|To je najËudnije, trËala sam sama za sobom.
{5973}{6072}-Zar ne moûeö normalno sanjati|kao drugi ljudi? -Ne.
{6093}{6158}Glupo je biti kao drugi ljudi!
{6174}{6258}-Nismo trebale izaÊi sinoÊ.|Iscrpljena sam.
{6265}{6321}-Odmori se. Probudit Êu te.|-Moûeö misliti.
{6323}{6371}-Ja Êu voziti, ako ûeliö.
{6373}{6457}-Misliö kao proöli put? -Oh, prestani.|Bilo je kasno i bila sam umorna.
{6461}{6529}-Umorna?|Pijana, pre bih rekla!
{6531}{6650}Pa, ti si bila kriva öto si me ostavila na|3 sata i nestala s nekim likom!
{6701}{6799}-Nadam se da je bio vrijedan toga.|-I viöe nego vrijedan. Neverojatan!
{6808}{6846}-Baö si kurva.
{6853}{6890}-KuËka!|-Prostitutka!
{6893}{6918}-Drolja!|-SvaËija ûena!
{6921}{6967}-Jeftina ûenska!
{7038}{7096}-Ima li ovde nekakvih cool mesta|za izaÊi van?
{7099}{7154}-Pa, ima gradska vijeÊnica,|ali to je sve.
{7156}{7243}-Vau, da moram ûiveti ovde celu|godinu, upucala bih se.
{7245}{7302}-Ovde je sasvim drugi ritam.|DrukËije je.
{7305}{7399}Osim toga, nismo se doöle zabavljati.|Ovde smo da uËimo.
{7486}{7559}-Hej, nismo gluve!|-Smiri se, Marie!
{8593}{8679}-'Ajde Hendrix, beûi!|Bang! Bang! Bang!
{8860}{8961}-Tom, prestani vikati barem na minutu.|Boli me glava zbog tebe!
{8963}{9012}-Koliko dugo trebamo Ëekati Alex, ha?
{9013}{9062}-BiÊe ovde nakon|öto se okupaö.
{9064}{9167}-Ne, jer Alex nikad nije videla|ovu kaubojsku odeÊu.
{9170}{9260}-Tom, okupaj se i onda se moûeö|opet preobuÊi u kauboja. U redu?
{9264}{9387}Bang, bang, bang!|Hajdemo, Hendrix, bang, bang!
{9445}{9537}To... joö... joö...
{11168}{11208}-Pazi na cestu!
{11211}{11273}-Joö imaö öminke na sebi, znaö.
{11479}{11532}-Jesi li sigurna da treba ovim putem?|-Naravno da sam sigurna.
{11532}{11646}-Nakon 50 metara, skreni desno kod|kukuruza. Tamo. Skreni desno...
{11648}{11703}...i idi pravo 4 kilometara.
{11710}{11745}-Stvarno se znadeö snaÊi ovde.
{11747}{11813}-Ovom stazom ne ide nitko,|osim traktora.
{11825}{11915}-4 kilometara ove staze|i - zbogom, auto!.
{11985}{12056}-Ne moûeö se uvek tako ponaöati|kada ti neki tip prie.
{12058}{12096}-Ne ponaöam se tako sa svima.
{12099}{12169}-Ma daj, Marie.|Uvek ista priËa.
{12233}{12279}-Stani!|-äta je?
{12286}{12349}-Videla sam nekoga!
{12353}{12443}-To nije smeöno, Alex!|-Ne öalim se. Videla sam nekoga, kunem se!
{12463}{12543}-Prestani se zajebavati!
{12638}{12693}Alex, vrati se, molim te!
{12993}{13035}-Sranje!
{13087}{13132}Alex!
{13227}{13283}Ako je ovo öala, poûalit Êeö!
{13318}{13362}Alex, gde si?
{13574}{13621}Gde si?
{13715}{13758}UhvatiÊu te.
{13989}{14052}Ako misliö da je ovo smeöno,|videÊeö!
{14233}{14266}Alex?
{14302}{14341}Alex!
{14520}{14615}Stani, gaduro i vrati se!
{14671}{14747}Dosta mi je tvojih igara!|Preöla si granice!
{14781}{14855}-GlupaËo!|-äto da sam te ostavila tamo?
{14867}{14912}-Jako smeöno!!
{14923}{14979}-Preplaöila si me!
{15381}{15411}-Evo nas.
{15580}{15649}-Sad znam zaöto tako lako|prolaziö ispite.
{15662}{15739}Ako provodiö vikende ovde,|ne moûeö niöta drugo veÊ uËiti!
{15742}{15826}-Ne mogu se nadmaöiti mir i tiöina.|»uju se jedino prolazeÊi vozovi i niöta viöe.
{16011}{16047}Hendrix, smiri se.
{16102}{16140}-Kako ste?|-Hej, tata.
{16159}{16199}-Ne brini se. Ne grize.
{16199}{16239}-Govoriö o meni ili psu?
{16242}{16292}-Marie, ovo je moj tata. Tata, Marie.
{16296}{16325}-Drago mi je.
{16327}{16385}-Napokon te vidim uûivo,|a ne samo na fotografiji.
{16386}{16433}-Fotografiji?|-Ma znaö, onu kad smo bile u äpanjolskoj.
{16439}{16487}-Na kaminu je.|Ti si ûiveo tamo.
{16489}{16541}-A ovo je Tom. Hej kauboju!
{16545}{16648}-Hej, jesi li sreÊan öto me vidiö, partneru?|-Naravno da je sreÊan.
{16756}{16799}-»ekao te je celu veËer.
{16803}{16858}A majka je zabrinuta veÊ celi dan.
{16859}{16915}-U redu je.|Mama se uvek brine zbog gluposti.
{16924}{16964}-Mislim da ti je ostavila neöto u peÊnici.
{16965}{17011}-Ali rekla sam da Êemo se snaÊi|i da se ne brine.
{17020}{17075}-Nije znala hoÊeö li imati vremena|da jedeö putem.
{17077}{17179}-To je mama! StaviÊu Toma PalËiÊa|u krevet i pokazati Marie njezinu sobu.
{17183}{17254}-Dobro. Onda te tu ostavljam.|Imam neöto nedovröenog posla.
{17257}{17301}-'NoÊ. Spavaj dobro.|Vidimo se sutra.
{17305}{17358}-Laku noÊ, gospodine.|Ugodno spavajte.
{17421}{17467}-Je li tvoj tata izgradio ovo mesto?
{17469}{17515}-Renovirao je jednu staru farmu.
{17516}{17590}Ima ih puno u ovoj regiji.|VeÊina su ruöevine.
{17593}{17668}äteta. Ovde ûive veÊ 5 godina.
{17674}{17720}Jeste li imali problema|sa susedima?
{17724}{17759}-Sa starosediocima?
{17778}{17872}-Isprva su zamijenili moje starce za par hipija|koji su doöli raditi kozji sir, ali sada je sve OK.
{17875}{17963}Uglavnom, ono je moja soba.|Tamo. Ovim putem.
{18012}{18065}Soba roditelja je na desno.
{18086}{18171}Tomova soba je tamo.|Tvoja je gore, u gostinjskoj sobi.
{18173}{18219}Samo par sekundi.|StaviÊu ga u krevet.
{18694}{18734}-Alexis, jesi li to ti?
{18792}{18864}-To je moja mama.|Idi. DoÊi Êu za Ëas.
{18953}{18982}-Hej mama.
{18985}{19077}-Da li ti se prijateljica smestila?|Pokaûi joj gde su pokrivaËi.
{19083}{19158}Ako treba ruËnike,|Ëisti su u ormaru.
{20624}{20675}-Tvoja privatna kupaonica.|Super, ha?
{20683}{20739}Grijanje je elektriËno.|HoÊu li upaliti?
{20743}{20785}-Ne, ja Êu ako zahladi.
{20798}{20870}-Pa, öto misliö?
{20875}{20930}-Kao kuÊica za lutke, vrlo lepo.
{21194}{21283}-Problem je öto ima devojku|s kojom ne ûeli raskinuti.
{21286}{21329}-Zaöto se onda toliko zanimaö?
{21332}{21379}-Neko koji je zauzet|ne moûe biti tako loö.
{21382}{21434}-Uvek su mi sumnjivi slobodni|tipovi. Ovde.
{21480}{21506}-éeliö joö?|-Ne, hvala.
{21511}{21585}-Mislim da je lako biti ûenskar|kad si veÊ zauzet.
{21587}{21630}-Moûda se samo pokuöavam uveriti.
{21763}{21802}Moûda mu se uopöte ne sviam.
{21805}{21869}-Kakva mu je cura?|-Ona je Brazilka.
{21872}{21915}Zajedno su 3 meseca.
{21918}{22007}-äto radi s Brazilkom? Jel' to nekakav|njegov otrcani naËin da se uzbudi.
{22011}{22103}-Kako god, moram öto pre potamniti...|i uËvrstiti guzu.
{22107}{22150}Da vidiö samo kako je graena!
{22154}{22203}-Ako budeö iöla na teËaj salse|iÊi Êu s tobom.
{22213}{22276}-Nemoj ih dirati ili Êe nas|gnjaviti celu noÊ!
{22313}{22389}A öto je s tobom? Kada|Êeö ti iskuöati svoju sreÊu?
{22400}{22423}-Nemoj mi poËinjati s time.
{22425}{22487}-Zavröit Êeö kao stara cura, Marie!|-Nisam napaljenica kao ti!
{22490}{22528}-Ti se bojiö, to je sve!
{22537}{22561}-Dosta!.
{22592}{22633}-Idem puöiti napolje.|A ti?
{22635}{22684}-Ne, idem u krevet.|Premorena sam.
{22687}{22759}-Nemoj ostati predugo.|Probudit Êu te u 9 sati.
{22762}{22788}-Koji je plan?
{22792}{22852}-PoËinjemo s meunarodnim|pravom. OK?
{22864}{22900}-Laku noÊ, Alex.|-Laku noÊ.
{22903}{23014}-Hey Alex, drago mi je öto sam|konaËno upoznala tvoju porodica.
{23620}{23681}'Ajmo Hendrix. Hajde.
{26360}{26393}Laku noÊ, Hendrix.
{33308}{33355}Evo, dolazim.
{33393}{33447}-Ko bi to mogao biti?|Hendrix, stiöaj se.
{33476}{33512}Ko je?
{33603}{33634}äto ûeliö?
{36304}{36367}-äta je bilo, mamice?|-Niöta, zlato.
{36369}{36400}Idi natrag u sobu, zlato.
{36425}{36473}-Ali kakva je to buka?|-Tom, uËini kako ti kaûem.
{36475}{36525}Hajde, natrag u svoju sobu!
{36735}{36773}Daniel?
{36819}{36857}Daniel?
{46910}{47066}Sranje, to je utiËnica za TV!|äto Êu... äto Êu napraviti?
{52963}{53118}A, ali, z... zaöto? Zaöto?
{53620}{53658}Isuse!
{54563}{54609}Alex?
{54649}{54688}Alex?
{54749}{54779}Alex?
{55107}{55260}-»ekaj malo!|Ne mogu skinuti! »ekaj!
{55422}{55495}Mama! Mama! Mama!|Mama! Mama! Mama!
{56942}{56977}Sluöaj me, Alex, sluöaj.
{56980}{57043}Da te je hteo ubiti,|veÊ bi to uËinio, zar ne?
{57141}{57252}Alex, sluöaj me. Reci mi gde|mogu naÊi telefon, ha?
{57257}{57297}U kuhinji?
{57313}{57455}U kuhinji? Odgovori mi, Alex!|Trebam tvoju pomoÊ! Ne mogu sama.
{57467}{57553}VratiÊu se.|VratiÊu se, Alex.
{57561}{57621}Moram videti je li ko u kuÊi.
{58248}{58288}Ne mogu verovati!
{63213}{63247}Telefonska linija je prerezana!
{63247}{63322}IzvuÊi Êu te odavde!|VideÊeö.
{66264}{66309}Ne tako glasno!
{66554}{66600}Nemoj upropastiti naöu jedinu öansu,|molim te!
{66685}{66714}Alex.
{66996}{67038}IzvuÊi Êemo se iz ovoga.|ObeÊavam ti.
{67038}{67101}»ak i ako se moramo boriti|uspet Êemo!
{67398}{67458}Ostali su bili sami.|Mi smo DVIJE!
{69109}{69144}Joö samo malo...
{69181}{69217}Alex, uspela sam!
{70085}{70130}Sad smo na benzinskoj crpki.
{70457}{70543}Ovo bi nam mogla biti jedina öansa.|Noû.
{70596}{70636}Ovo je ako se ne vratim.
{72420}{72483}-Gospoice. -Hitno!|Zovite policiju!
{72515}{72545}-äto?
{72628}{72654}Gospoice, Ëekajte!
{72900}{72931}-Hej Jimmy.
{72994}{73046}-Kako si?|-Dobro.
{73119}{73161}-Sam si veËeras?
{73232}{73297}-Vikendi su spori ovde.|Da, sasvim sam sam.
{73328}{73395}-ZnaËi, svi su otiöli i|ostavili ti trgovinu?
{73400}{73442}-Da, tako nekako.
{73576}{73641}-Ovo mesto nije loöe za|dovesti curu po noÊi, zar ne?
{73684}{73726}Nemoj mi reÊi da nikad nisi.
{73762}{73836}-äef me ne bi drûao ni 2 minuta|kad bih doveo nekoga ovde.
{73963}{74010}-Kladim se.
{74061}{74132}Da ti mlade dame dolaze ovde
{74139}{74270}i traûe te za male usluge.|Uzbuujeö ih.
{74295}{74335}Jel' tako, Jimmy?
{74363}{74418}-Pa, valjda, mislim da je tako.
{74617}{74700}-äta kaûeö, Jimmy?|Sviaju ti se?
{74753}{74828}-Pa, izgledaju dobro na vama.
{74852}{74904}-ätite te.|-Od Ëega?
{74907}{75023}Od sunca, Jimmy...od sunca.|-Da, to su sunËane naoËare...
{75045}{75090}pa vam ötite oËi, naravno.
{75240}{75280}-Koliko sam duûan?
{75332}{75397}-28 eura. éelite li naoËare?
{75402}{75473}-Ne, nisam uveren, ali trebam piÊe
{75473}{75548}pa kako da mi prodaö bocu od J&B?
{76272}{76325}Radije bih bocu Campbell's.
{76419}{76497}-Moûe. Ustvari, nije mi dozvoljeno|da prodajem alkohol u ovo vreme.
{76501}{76575}-ObeÊavate da neÊete reÊi öefu?|-ObeÊavam.
{79431}{79492}äto si to gledao, Jimmy?
{79525}{79579}äto si gledao?
{85033}{85096}Neka se neko javi, zaboga!
{85164}{85210}Javite se!|-Drûavna policija.
{85214}{85288}-Halo? Halo, policija?|Oh, preklinjem vas, pomozite mi!
{85302}{85351}-OK, smirite se i recite|koji je problem.
{85354}{85412}-Soralovi, imaju farmu blizu Puyanne.
{85415}{85463}Prijateljica sam njihove kÊeri Alexis.
{85465}{85538}Taj tip je provalio usred noÊi.|Provalio je i ubio sve!
{85541}{85611}Odveo je moju prijateljicu u kamionu|i zaista sam uplaöena za nju.
{85613}{85647}-Upravo je ubio tipa koji|radi na benzinskoj stanici.
{85647}{85679}-Benzinskoj stanici?|-Da.
{85679}{85714}-Vi ste na benzinskoj stanici?
{85717}{85756}-Da.|-Kojoj benzinskoj stanici?
{85916}{85954}-PriËekajte, pogledat Êu.
{86081}{86132}-Ne znam koja je stanica.|Bila sam u njegovom kamionu.
{86135}{86193}Sve öto znam je da je kamion|smee boje, vrlo star i hrav.
{86195}{86248}-Jeste li zapamtili|registracijski broj vozila?
{86250}{86310}Kako sam mogla zapamtiti broj?|Rekla sam da sam bila u kamionu!
{86313}{86362}-Shvatate li koliko je starih|kamiona na cesti?
{86365}{86414}Bez registracije n...|-Isuse, stari kamion
{86416}{86495}na seoskoj cesti u ovo doba noÊi|bi trebalo lako zapaziti, zar ne?!
{86497}{86575}-Molim vas, gospoo,|smirite se i recite gde ste.
{86583}{86664}-Sluöajte, taj gad je pobegao s njom.|Ako ne poöaljete nekoga sada
{86667}{86703}neÊe preûiveti!
{86707}{86768}-Razumem, ali ne moûemo pomoÊi|ako ne znamo gde ste.
{86771}{86873}-Ako spalim prokletu stanicu|moûda Êete ju onda spaziti, ha?!
{87085}{87189}KljuËevi... kljuËevi...
{91473}{91538}Gde ûivi prokletni kuËkin sin?
{94677}{94711}Sranje!
{94791}{94835}Gde je otiöao...
{106443}{106499}-Zaöto te toliko brine Alex?
{106513}{106662}Napaljuje te? I mene isto.|Napaljuje me.
{110691}{110797}-Svetla su ugaöena. Izgleda zatvoreno.|Bolje pogledajmo.
{111020}{111068}-Idi na zadnji ulaz, Fred.
{111079}{111126}I pazi se.|-U redu, kapetane.
{111534}{111613}-Kapetane, straûnja su vrata zakljuËana.|Moramo...
{111626}{111672}-Radije zovi policijsku stanicu.
{111788}{111905}-Ovde patrola, auto 214.|Imamo ûrtvu ubistva ovde.
{112253}{112284}Boûe moj!
{112856}{112893}-Ja sam, Alex. To sam ja.
{113074}{113124}Gotovo je.
{113227}{113261}Sve je gotovo.
{114318}{114343}OK.
{114375}{114411}-Ne diraj me!
{114429}{114469}Ne diraj me, rekla sam!
{114489}{114540}-Sve je gotovo. Mrtav je.
{114544}{114584}Mrtav je. Gotovo je.
{114584}{114660}-Luda si! Makni se!
{114663}{114717}-Sve je gotovo, gotovo je.|-Makni se!
{114740}{114785}-Alex, smiri se.|-Makni se!
{114893}{114951}-Sve je gotovo, Alex.|Ubila sam ga. Mrtav je.
{115010}{115127}-Alex, molim te smiri se.|-Makni se! Ne prilazi mi!
{115129}{115243}Alex, daj. Sve je gotovo sada.|Ne moûe nam viöe niöta uËiniti.
{115257}{115338}-Ti luda kuËko! IzrezaÊu ti|glavu na komade!
{115341}{115441}-To sam ja, Marie, tvoja prijateljica.|Na tvojoj sam strani!
{115445}{115505}-Ubila sam ga, Alex.|Gotovo je. Mrtav je.
{115520}{115594}-Ubila si moju celu obitelj!|Ubila si moju celu obitelj!
{115596}{115677}-Ne znaö öto priËaö.|Nisam ih nikako mogla spasiti.
{115681}{115720}-Tamo si bila samo ti. Znadeö to.
{115723}{115813}-Alex, sve Êe od sada|biti u redu.
{115816}{115941}Molim te, moraö mi verovati, Alex.
{116828}{116900}PlatiÊeö za ovo, kuËko!
{117184}{117242}Sredit Êu te, Alex!
{117432}{117481}Sredit Êu te, Alex!
{118076}{118159}Pomozite mi! UpomoÊ! Pomozite mi!
{118247}{118283}Krenite! Brûe! Poûurite!
{118287}{118323}-äta se dogaa?|-Poûurite!
{118326}{118427}-Poûurite! Krenite! Krenite!
{120109}{120152}-Glavu Êu ti otkinuti!
{122545}{122623}éeliö me izluditi,|ti jebena kuËko, ha?
{122667}{122709}Ne... Ne...
{122780}{122817}Voliö li me?
{122844}{122883}Ne voliö me.
{122939}{122985}Ne voliö me, zar ne?
{123206}{123339}Ne voliö me.|-Da, da!
{123347}{123600}Da, volim te! Da,|volim te! Volim te!
{124768}{124920}-Niko viöe neÊe doÊi izmeu nas, Alex...|Nikada viöe.
{124954}{125095}NeÊu viöe dopustiti da itko|stane izmeu nas...
{125168}{125270}NeÊu viöe dopustiti da itko|stane izmeu nas...
{125386}{125492}NeÊu viöe dopustiti da itko|stane izmeu nas...
{126016}{126070}-Jeste li sigurni|da me ne moûe videti?
{126266}{126516}Prevod sa hrvatskog na srpski:|kosta zulu leskovac
{126541}{128041}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/mp78|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
