{1}{1}23.976
{26}{176}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{4673}{4749}Attila! Gde si?|Da li si uhvatio tog zeca?
{4794}{4856}Kladim se da jesi,|moj veliki lovËe.
{4860}{4933}Ti, straöni ubico.|Takav je moj pas.
{4938}{5008}Moja zver. Poljubi me.
{5309}{5340}»ekaj malo.
{5378}{5450}»ekaj malo.|Doavola, Attila!
{5463}{5509}I ti sebe zoveö Ëuvarom?
{5609}{5648}Ne menjaj temu.
{5883}{5911}Zdravo, George.
{5956}{6008}PomoÊi Êeö mi s ovim?
{6014}{6060}äta to nosim?
{6084}{6145}Uzeo sam solarne ploËe|i baterije na rasprodaji.
{6151}{6264}NeÊu viöe da renoviram kuÊu.|Jednog dana Êu da je prodam.
{6309}{6351}Vidim da si renovirao baötu.
{6355}{6410}Da, ali zec je ipak uöao.
{6453}{6524}Proöao ti je ispod|ograde, George.
{6530}{6616}Nije. -Jeste! -Stavio sam je|viöe od pola metra ispod zemlje.
{6666}{6704}Pa, Ëudno je to.
{6726}{6841}Dakle, sa solarnom opremom|Êeö da uötediö i besplatna je.
{6888}{6969}Pa, sreÊan ti roendan.|- Hvala, Nate. Hvala ti.
{7086}{7129}Ko Êe da je sloûi?
{7153}{7239}Ja ne. PriruËnik je|na 3 razliËita jezika.
{7253}{7328}Zaboravi. Ako se radi|o autu, mogu da ga popravim.
{7333}{7376}Ako je baöta, mogu da posadim,
{7419}{7465}ali u ovo se ne razumem.
{7481}{7578}Dolaziö sa nekim veËeras?|- Ne, a ti?
{7616}{7665}Mislim nekoga da pozovem.
{7673}{7720}Kada? Danas?
{7736}{7805}Ne dajeö im puno vremena.|- HoÊeö li ikoga da pitaö?
{7836}{7920}Uvek pitam Dianu Ross,|ali nikada ne pristane.
{7976}{8018}Vidimo se.|- ∆ao.
{8646}{8703}George, zaboravio|sam da ti kaûem.
{8738}{8763}»ekaj.
{8811}{8843}Doktor je zvao.
{8856}{8900}»ekaj, Banes.
{8980}{9006}U 10 sati.
{9181}{9300}éeli da pogledaö|u njegov prozor u 10 sati.
{9358}{9425}Pogledaj u prozor.|- »oveËe.
{9663}{9744}Kako si, Lace?|Izgledaö sjajno.
{9795}{9871}Kako se prodaju stolice?|- Imam joö jednog. Trebam joö 4.
{9900}{9940}{Y:i}PRODAJA STARIH STVARl
{9958}{9999}Bolje nego öto sam oËekivala.
{10006}{10065}Da, Ijudi Êe puno|sedati ovde.
{10088}{10133}Mogu ti ja to.|- Mogu sama.
{10195}{10228}PomoÊi Êu ti.
{10268}{10343}Lace, veËeras je|zabava u baru Elkhorn.
{10348}{10415}Zaöto Elkhorn? Ovde|nema jelena. -Ne znam.
{10420}{10509}Rogovi nekog jelena|vise iznad bara?
{10516}{10618}Ne bih rekao. U svakom|sluËaju, danas mi je roendan.
{10625}{10693}Zabava je veËeras u Elkhornu.|To sam rekao, zar ne?
{10718}{10753}George!
{10773}{10815}Moram gore da pogledam u deset sati.
{10823}{10914}Zaöto? -To je kancelarija|dr. Brundera. -äta hoÊe?
{10923}{10948}Ne znam.
{10971}{11029}HoÊeö li da doeö na zabavu?
{11035}{11088}Ne ostavljam decu samu po noÊi.
{11093}{11150}Znam dobru dadilju...|Titovu ûenu. Tito!
{11193}{11243}{Y:i}SRE∆AN RO–ENDAN, GEORGE.
{11274}{11309}Lepo.
{11438}{11486}ZnaËi, to je doktor?|- To je doktor.
{11611}{11670}Molim te, doi veËeras.|- Ne. Ne veËeras.
{11748}{11783}U meni je stvar?
{11796}{11840}Ne, nije u tebi.
{11866}{11901}Onda Êu i dalje da pitam.
{11978}{12048}Voleo bih da proËaËkam|po tvom rasplinjaËu.
{12061}{12103}Sigurna sam da bi.
{12288}{12331}Vi kaûete preöla te.
{12335}{12365}Natrag na posao, momci.
{12465}{12588}{Y:i}DOBRO DOäLl NA RO–ENDAN|G. MALLEYJA. PRVO PI∆E BESPLATNO!
{12811}{12866}Nate, to je skandalozno.|Ti i Diana Ross.
{12873}{12909}Rekao sam novinarima.
{12933}{13031}Bila bi tako sretna na mojoj|farmi. Bez stresa. -Istina.
{13038}{13105}Bez medija i novinara.|Kao u raju.
{13130}{13193}Ti ne bi smeo kupovati piÊe.
{13199}{13275}Jimmy! George ne kupuje|piÊe. Roendan mu je.
{13293}{13338}Hej, doktore, doöli ste.
{13385}{13449}Kako su svi? Joö|uvek moûete da diöete?
{13482}{13571}Probajte kolaË. Napravila ga|je Titova ûena. Jako je dobar.
{13623}{13663}Hvala, doktore.
{13715}{13808}UËiö, ali nikad nisi igrao|u previranju i haosu.
{13820}{13893}Da se vratimo dami,|mogao bih da pobedim.
{13899}{14005}Ne, ti imaö potencijala.|Uvek sam govorio da imaö neöto.
{14018}{14098}To sam rekao onog dana|kad sam te obrezao.
{14114}{14158}To kaûe svakog roendana.
{14197}{14283}Pokvario si mi priliku za|romansu s onim na prozoru.
{14292}{14338}Sramota jedna.
{14353}{14407}Kriminalno. Ta predivna|devojka je otiöla.
{14417}{14462}Ona sa stolicama?
{14473}{14573}Neudobni su.|- Moraö da nauËiö da sediö u njima.
{14585}{14675}KuÊa Ëasti.|SreÊan roendan!
{14690}{14773}Nema odelenja za puöaËe u raju.|- Nemojte, doktore. Evo.
{14812}{14868}{Y:bi}SreÊan roendan, prijatelju.
{15024}{15070}Ovo je sjajno.
{15108}{15148}»ekaj, Tito. Tito!
{15195}{15248}Hvala öto si mi|doöao na zabavu.
{15259}{15292}SreÊan roendan.
{15298}{15338}Da, sreÊan roendan.
{15504}{15537}SreÊan roendan.
{15719}{15765}37.
{15780}{15808}37.
{16943}{17007}Da li je neko ono|video? Ono svetlo?
{17018}{17082}Koje svetlo?|- Da li ste Ëuli buku?
{17109}{17150}Moûemo li da zavröimo, George?
{17193}{17230}Bilo je kao...
{17258}{17313}Eksplozija i bljesak...
{17324}{17413}Kao avion?|- VeÊe. I dalje.
{17420}{17520}Misliö, kao zvezda, George?|- Oborilo me na tlo.
{17544}{17612}Pao si? -Da, pao sam!|Pogodilo me taËno...
{17639}{17713}»ovek je pijan.|- Upozorio sam te.
{17722}{17804}Nisam pijan.|- Uzimam ti kraljicu, George.
{17862}{17898}äah-mat.
{17913}{17955}äah-mat, zar ne?
{18003}{18094}Pobedio te? -Pustio si ga|da pobedi? Roendanski dar?
{18103}{18192}Niöta mu nisam pustio.|- Malo si Ijut zbog toga?
{18215}{18285}HoÊeö joö jednu?|- OsvetiÊeö mi se sutra.
{18302}{18358}OseÊaö li se dobro?|- Moûeö da voziö?
{18368}{18397}Dobro sam.
{18434}{18472}Hvala svima.
{18478}{18550}SreÊan roendan. -SreÊan|roendan. -Dobra zabava.
{18998}{19028}Ne mogu da spavam.
{19260}{19288}To je to!
{19505}{19540}Shvatio sam.
{19547}{19610}Isuse, zaöto me zoveö? Kasno je.
{19617}{19677}Mislio sam da se|farmeri diûu pre zore.
{19687}{19793}Ako imaju krave.|Ja ih nemam, George.
{19829}{19892}Postoji objaönjenje za tog zeca.
{19904}{19979}Kad sam sagradio novu|ogradu, veÊ je bio unutra.
{19993}{20063}Krio se. Zagradio sam ga.
{20095}{20163}Sad moram da ga pustim napolje.|- Laku noÊ, George.
{21554}{21603}{Y:i}MALLEYJEV AUTO SERVIS
{21635}{21667}Evo Rogera.
{21673}{21723}George, moûeö li da mi vratiö auto?
{21728}{21793}Sad nemam gotovine,|ali treba mi auto.
{21807}{21865}Moram da postavim|solarne ploËe na krov.
{21872}{21910}Ne znam niöta o tome.
{21917}{21988}Charlie zna, a on|treba da iskopa bunar.
{21995}{22077}Ti ga iskopaj, on Êe da postavi|ploËe, a ja Êu da popravim auto.
{22089}{22118}Moûe?
{22133}{22173}Da, moûe!
{22222}{22263}NazvaÊu Charlieja.
{22324}{22369}Zvao sam zbog popravke koËnica.
{22375}{22418}Odmah. Tito...
{22724}{22755}Doi.
{22768}{22853}On sad govori öpanski bolje|od mene. -Da, i od mene.
{23769}{23816}Gde je vlasnik ovog vozila?
{23822}{23877}Ti si policajac?|- Mama je u trgovini.
{23918}{23978}Da li je zakoËeno, momËe?|- Zove se Al.
{23984}{24029}Kako se ti zoveö?|- Glory.
{24073}{24107}Ja sam George.
{24113}{24148}Otvori haubu, Al.
{24185}{24214}Zaöto?
{24228}{24288}Znaö kako da ga upaliö?|- Jasno.
{24362}{24441}Hitna sluûba. Motor nema|dosta vazduha i loöe je podeöen.
{24474}{24515}Moram da idem. -gde?
{24537}{24614}Ne odlaziö iz grada?|- Idemo danas u San Francisco.
{24624}{24713}éiveo sam tamo. Pitaj me za|smer ili bilo öta drugo.
{24753}{24828}Pitaj me hoÊu li sa vama. äta misliö?
{24833}{24887}Mislim da prebrzo voziö.
{24898}{24957}San Francisco, ha?|Ali, tu si roen.
{24963}{25023}Kako si znala?|- U prodanici je neko rekao:
{25028}{25148}Znam ga dugo. Ako kaûe da je|video NLO, onda ga je video.
{25192}{25228}To nisam rekao.
{25236}{25314}Video si ga?! -Nisam|rekao öta sam video.
{25321}{25392}Kako je izgledao?|- Mogao je da bude.
{25498}{25541}To ti je mat, doktore.
{25547}{25588}»ekaj, Ëekaj, George.
{25606}{25654}äto se, doavola, dogaa?
{25678}{25743}Ne znam, doktore.|Stvarno ne znam.
{25758}{25833}U poslednje vreme sve|doûivljavam puno jasnije.
{25883}{25951}Odmah shvatam. Mogu|da se koncentriöem.
{25989}{26072}I knjige... Ne mogu da prestanem|Ëitam. Po 2, 3 knjige na dan.
{26078}{26191}Ne mogu da prestanem|i ne mogu da spavam.
{26206}{26246}Znaö, od onda...
{26343}{26379}Moram da se vratim na posao.
{26389}{26506}Od onda...|- Od svetla.
{26512}{26583}Da, bilo je to prokleto|svetlo. -I eksplozija.
{26593}{26648}Da li si je ti Ëuo?|- Pa, nisam.
{26678}{26743}Bilo ko? Pre devet|dana, baö ovde?
{26754}{26816}Da li je bila ponoÊ, George?
{26846}{26904}George, doi na pregled. Dobro?
{27101}{27169}Dve ili tri knjige|na dan? -Najmanje.
{27183}{27228}O Ëemu? -O svemu.
{27248}{27299}Sve öto sam ûeleo da znam.
{27318}{27352}Kao npr.?
{27361}{27443}Ti reci meni. äta si|oduvek ûeleo da znaö?
{27544}{27581}Razmisli malo.
{29786}{29883}C.Q. ovde WB6QLF.|Javljam se
{29888}{29957}iz Harmona, Kalifornija.|Ima li koga?
{29968}{30056}Traûim Dianu Ross, ali|prihvatÊu svakog na engleskom.
{30099}{30128}To si ti, Diana?
{30183}{30213}Zdravo, George.
{30228}{30298}Nisi poöteno seo dok|ne probaö jednu od ovih
{30303}{30413}stolica kuÊne izrade.|Doneo sam 2. Jedna za tebe,
{30421}{30497}a prijatelj moûe da sedne tamo,|ako ikad nekog pozoveö. Pa?
{30569}{30603}Ne uklapaju se.
{30612}{30683}äta ti znaö? Ovde|je kao na sajmu.
{30689}{30738}Treba ûenska ruka.
{30746}{30784}I to hitno.
{30801}{30864}Radio sam na solarnoj|opremi koju si mi dao.
{30873}{30927}Celo podruËje fotovoltaûe
{30933}{31003}tek se razvija. HoÊu da kaûem,
{31009}{31101}biljke su pohranjivale|i koristile sunËevu energiju
{31111}{31153}od postanka sveta.
{31161}{31239}Fotosinteza je za nas|novo. Upravo poËinjemo
{31244}{31356}da uËimo öta moûemo da uËinimo sa|tim Êelijama silikona. -äta?
{31459}{31491}äta?
{31497}{31571}Govoriö tako brzo,|George. I toliko znaö.
{31589}{31676}éao mi je, ali ne|mogu da si pomognem, Nate.
{31694}{31727}U redu je.
{31779}{31809}äta je to?
{31831}{31881}Kompjuteri meusobno komuniciraju.
{31888}{31963}Ne, ostavi. -Ide|prebrzo za deöifrovanje.
{31971}{32046}Ne, Ëujem ga.|- Glupost.
{32052}{32119}Stalno se ponavlja.|Odaöiljaju poruku.
{32158}{32229}Zalevanje cveÊa u petak.
{32269}{32329}Ko bi slao takvu öifrovanu|poruku Morseovom azbukom?
{32353}{32458}Primam 2 vazduhoplovne baze.|Bolje da se ne bavimo ovim.
{32468}{32521}Ova je drugaËija! Sluöaj.
{32533}{32612}Ova je mnogo zbijenija,|ali ipak se ponavlja.
{32658}{32734}Ozbiljno... -Moram ovo da snimim.|- Trebalo bi to da ostavimo.
{32773}{32803}äta to radiö?
{32811}{32882}DeöifrovaÊu kod kuÊe. Onda|moûemo da odgovorimo. -Zaöto?
{32903}{32967}Zato jer me to zaokuplja. Dobro?
{33082}{33143}Ne znam poboljöava li se|ili pogoröava.
{33153}{33221}Moram neöto da radim|12 sati po noÊi.
{33229}{33298}Umorim se od Ëitanja.|Ukrötenice su prejednostavne.
{33343}{33381}Prejednostavne?
{33398}{33481}Svi koje znam spavaju,|a ja sam budan.
{33498}{33543}Mogu li ja öta da pomognem?
{33591}{33643}Zaöto se ne bismo tukli napolju?
{33652}{33723}Opet Êu ti da raseËem usnu.|OseÊaÊeö se mnogo bolje.
{33801}{33891}Ako poöaljeö poruku, hoÊe li|oni da je dobiju? -Da, naravno.
{33911}{33938}Poöalji ovo.
{33957}{34028}Poöalji "Ne zalevajte|previöe cveÊe. " Reci to.
{34034}{34082}U redu. CveÊe?|- Da.
{34093}{34168}Ne. Reci "Ne zalevajte|previöe cveÊe u petak. "
{34203}{34266}Ne zalevajte previöe...
{34277}{34321}cveÊe u petak.
{34344}{34402}MotriÊemo vas. U redu?
{34414}{34466}Oh, Boûe. Ovo je sjajno.
{35401}{35443}U redu je. Nije niöta.
{35451}{35503}StatiËki elektricitet.|To je sve.
{35581}{35617}Evo.
{35636}{35663}Dobro.
{35683}{35718}U redu. Dobro.
{35905}{35937}Oh, Boûe!
{35943}{35980}Oh, Boûe moj!
{35998}{36031}»oveËe.
{36035}{36093}Neko pokuöava neöto da mi kaûe?!
{36198}{36223}äta?!
{36525}{36552}Popiöao si se?
{36573}{36651}Joö ne moûeö da spavaö?|- Da. Imaö li pojma zaöto?
{36707}{36742}Koliko dugo se ovako oseÊaö?
{36755}{36811}Znaö koliko dugo. Svi znaju.
{36831}{36876}Roendan mi je bio|pre mesec dana.
{36917}{36958}Jesi li primetio|joö neöto?
{37023}{37051}Da.
{37157}{37202}Gledaj svoju olovku.
{37226}{37261}Kako to misliö?
{37518}{37556}To je telekineza.
{37616}{37652}Da li je to u redu?
{37697}{37723}UËini to opet.
{38110}{38206}Znaö, smatram se razumnim Ëovekom,
{38212}{38280}nauËnikom, otvorenim|prema... bilo Ëemu.
{38313}{38387}Ali oseÊam se kao dete,|George. Prestraöen.
{38412}{38442}I ja isto.
{38525}{38601}äta god da je razlog za ovo,|obeÊavam da Êemo ga naÊi.
{38646}{38675}A sada,
{38688}{38738}uËini to opet.
{38940}{38976}Ovo je Ëudoviöte, George.
{38992}{39081}Ovaj Frankenstein pree|150 km na galonu goriva
{39087}{39146}od metana napravljenog|od mog ubreta
{39153}{39233}i Nateovog gnojiva za|svinje. Posebna smeöa.
{39238}{39281}Miriöe baö tako.
{39485}{39520}Zdravo, Lace.
{39535}{39597}Ovi su drugaËiji.|Koristila sam öire grane.
{39603}{39672}Izgledaju sjajno.|- Da li su ovo tvoji?
{39688}{39781}Radim na posebnom|organskom gnojivu.
{39788}{39867}Hajde, probaj.|Zagrizi kao jabuku.
{39978}{40023}Imaö malo na|bradi. Izvini.
{40103}{40147}Moûda Êe deca malo hteti.
{40183}{40218}Sjajne su. Hvala ti.
{40225}{40272}»ekaj, Lace.|IzabraÊu ti neke.
{40280}{40323}Deci Êe se svideti.
{40371}{40423}Moûeö da napraviö sos ili Ëorbu.
{40527}{40571}Mislio sam da si pametan.
{40578}{40623}äto uopöte vidiö na njoj?
{40628}{40680}Da, osim neudobnih stolica.
{40737}{40786}Moje srce, prijatelji.
{40800}{40838}Moje srce.
{41575}{41617}George, gde ideö?
{41648}{41742}Vi idete kuÊi?|HoÊete da vas povezem?
{41746}{41777}U redu.|- Glory!
{41803}{41835}Doi, Glory.
{41871}{41918}HoÊeö li?|- U redu.
{41943}{41992}Al!|- Dolazim!
{41998}{42036}Poûuri!
{42378}{42423}Ovo je za naöu mamu?
{42498}{42557}Mislio sam da je|cveÊe za devojke?
{42588}{42626}Ne preteruj, Al.
{42632}{42666}Pozvala te?
{42733}{42761}»ekajte.
{42775}{42826}Plavo. Nemam plave.
{43088}{43120}Sjajno.
{43383}{43436}Znate kako se zove ovaj cvet?
{43468}{43558}Delphinium belladonna.|Iz porodice Ranunculace je.
{43578}{43630}Nisam se oduvek razumeo u cveÊe,
{43636}{43723}ali sada prepoznajem|sve öta vidim. -Stvarno?
{43740}{43801}Ovaj je, npr. Lamonium sabbatam.
{43821}{43853}A ovo je...
{43916}{43958}Zbog toga nisu niöta lepöi.
{44011}{44052}To je zatvaraË za kesicu?
{44105}{44146}Improvizovao sam.
{44222}{44260}To je dobra ideja.
{44523}{44563}To je puno bolje.
{44596}{44628}Hvala ti.
{44957}{44996}Mama mi je otpozadi!
{45124}{45155}Lace?
{45292}{45348}Nisi uzela dovoljno paradajza.
{45352}{45431}Veoma sam ponosan|na njega. Evo, izvoli.
{45509}{45544}Doneo sam ti ovo.
{45571}{45637}Tu je sve poljsko cveÊe|od moje do tvoje kuÊe.
{45649}{45692}Pomogli su mi.
{45741}{45792}Na Ëemu radiö?|- Ni na Ëemu.
{45825}{45854}Ni Ëemu.
{45881}{45939}Pazi ovo.|Stvarno sjajan rad.
{45959}{45997}Pazi ovo. Divno.
{46006}{46041}HoÊeö li da se proöetaö?
{46114}{46215}Moram da ti kaûem... imaö sjajnu|decu. -Da, sjajni su.
{46231}{46329}Da, ali ti to ne znaö, jer|ne poznajeö ni njih ni mene.
{46345}{46386}Pokuöavam da te upoznam.
{46391}{46474}Znam. éelim da mi ûivot|ostane veoma jednostavan.
{46481}{46554}»ak i predvidljiv.|Zato sam ovde preselila.
{46584}{46674}Ne volim iznenaenja.|Ne volim komplikacije.
{46706}{46751}äta ti se dogodilo, Lace?
{46816}{46884}Izvini. To nije moja|stvar. -Ne, u redu je.
{46907}{46944}Baö mi je ûao.
{46952}{47002}PitaÊu te neöto.
{47009}{47102}Ako muökarac doe s vreÊom|paradajza, öta oËekuje? VeËeru?
{47134}{47194}Ne. Samo se nada.
{47259}{47315}Trifolium. Pogledaj.
{47326}{47377}Nisam ti doneo IjubiËasto cveÊe.
{47446}{47481}OseÊaö to?
{47489}{47519}äta?
{47639}{47687}Doi ovamo. Doi i vidi.
{47734}{47770}Oseti to. Evo.
{47781}{47815}äta?
{47862}{47936}Oh, Boûe. Mislim|da znam öta je ovo.
{47949}{48000}Mogu li da se posluûim|tvojim telefonom?
{48119}{48182}TaËno istoËno od Harmona.|Znate na öta mislim?
{48200}{48306}Rekli su mi da vas nazovem.|Osetio sam neko pokretanje.
{48344}{48401}Ne, nisam koristio instrumente.
{48419}{48507}Ne, nemam diplomu.|Samo pokuöavam...
{48517}{48582}Pokuöavate da me se|reöite? To hoÊete?
{48614}{48736}HoÊu da vam kaûem da sam osetio|talase najmanje frekvencije.
{48740}{48814}Izazivaju muËninu|i vrtoglavicu, zar ne?
{48827}{48869}Pa, to sam osetio.
{48876}{48929}I pokuöavam da vam|kaûem da mislim
{48969}{49015}da dolazi zemljotres.
{49089}{49161}Al, priËvrsti öoljice|lepljivom trakom.
{49169}{49234}Glory, spusti dole|vaze i porculan.
{49904}{49939}Ovo je dobro, Lace.
{49989}{50026}Mislim da si dobra kuvarica.
{50039}{50074}Nisam.
{50081}{50194}Samo dva jela dobro radim...|svinjska rebra i Êuretinu.
{50261}{50289}Koje je ovo?
{50772}{50806}Gledajte!
{50986}{51020}Al.
{51060}{51104}Samo sam se öalio.
{51289}{51325}Nije smeöno.
{51726}{51781}Dobro, mogu li sada da ti kaûem?
{51814}{51855}Imaö sjajnu decu.
{51869}{51904}I hvala ti na veËeri.
{51921}{51954}I laku noÊ.
{51994}{52027}Laku noÊ.
{52131}{52169}Dolazi.
{52186}{52244}Reci joj.|- Ne, ti joj reci.
{52350}{52377}Super je.
{52384}{52435}Da, strava je.
{52442}{52522}Misli da je video NLO i predvia|zemljotrese. To je upozorenje.
{52541}{52597}Nije bio siguran da je NLO.
{52909}{52944}Ulazite u kamion!
{52947}{53000}Gotovo je, mama.|- Znam! Idemo!
{53327}{53397}Da li si to osetio?|Uplaöio si se?
{53432}{53520}Shvataö li moguÊnosti svega|ovog? Znaö öto ovo znaËi?
{53736}{53776}Osetila si ga, zar ne?
{53812}{53861}Jesi.|- äta se dogaa?
{53866}{53917}Nije li to Ëudesno?|- äta se dogaa?
{53929}{53984}Ne znam öta se dogaa.
{53989}{54035}Treba mi samo istina.
{54042}{54119}Ovo je istina. Ono öto|mi se dogaa jeste istina.
{54437}{54475}O, ne.
{54869}{54959}Sviaju mi se ove stolice,|Lace. Baö mi se sviaju.
{54979}{55044}Napravila si ih. U redu?
{55147}{55194}Hteo sam da te vidim. U redu?
{55200}{55251}VratiÊu ti novac.
{55255}{55335}Ne ûelim tvoj novac.|- Traûila sam ti jednu stvar, George.
{55343}{55411}Istinu. Ti to nisi|mogao da prihvatiö.
{55948}{55992}Da li si je veÊ nazvao?
{55999}{56095}Nema veze. Druga je gladiola|- Moûda viöe nije Ijuta.
{56101}{56162}Ljuta je. Dobro.|- Napiöi joj neöto.
{56170}{56243}Ne. Ovo sam naöao.|Plan baöte sa 5 redova.
{56256}{56359}Poöalji cveÊe ili slatkiöe.|- Marigold, gladiole, ruûe...
{56369}{56461}U biblioteci, naöao sam u|tekstu silos za raketu
{56473}{56519}u vazduhoplovnoj bazi Masterson.
{56525}{56596}Napravio sam sopstveni nacrt. Evo ga.
{56628}{56716}Vidiö, ovo je njihova|baöta. Vidiö li?
{56740}{56809}To je staro i viöe|nije poverljivo.
{56813}{56910}Ovo je komplikovanije. Trigrafi,|tetragrafi, ABBA struktura.
{56920}{56946}George,
{56954}{57000}öta ûeliö da poöaljem?
{57006}{57056}U redu. Poöalji ovo.
{57074}{57176}Pazite baötu. Dolazi zima.|SreÊno sa Mozopom. Znaö za to?
{57184}{57248}U redu je. Ovo je|tvoja igra, George.
{57264}{57301}VeÊ si seo u ovu stolicu?
{57308}{57358}Dobra je. Trebalo|bi da je nazoveö.
{57361}{57430}Ne. PustiÊu|je da se smiri.
{57454}{57500}DaÊu joj oko godinu dana.
{57548}{57590}Uzmi telefon i nazovi je.
{57596}{57721}Ko mi kaûe. Progovorio si 10|reËi sa ûenama ove godine?
{57846}{57885}Oprosti, Nate.
{57914}{57948}Poslao sam ti poruku.
{57974}{58026}Prolazim kroz nekakvu fazu.
{58053}{58099}Svi mi prolazimo kroz neöto.
{58106}{58144}Znam, ali...
{58163}{58215}ovo je bilo malo teûe.
{58239}{58279}PokazaÊu ti neöto.
{59050}{59099}Misliö da su te magnetizovali?
{59119}{59189}Ne znam, prijatelju.|Da bar znam.
{59413}{59466}äta je?|- Bolje poûurite, doktore.
{59470}{59545}Poûurite. Uvedite ga.|Jako je loöe, doktore.
{59555}{59645}Idite do reta. Donesite|mi ambalaûu od hrane.
{59664}{59729}Neko drugi neka|ode do ormariÊa.
{59739}{59795}Traûite oöteÊene|ili izboËene limenke.
{59801}{59851}Trovanje hranom?|- Mislim da jeste.
{59859}{59914}äta govori?|Ko zna öpanski?
{59924}{59994}Portugalski. Stigli su proöle|nedelje. -Portugalski?
{60058}{60109}Kaûe neöto o Albertu.
{60123}{60175}To je deËak.
{60184}{60278}Neki od vas neka potraûe dete.|Moûda je veoma bolestan.
{60293}{60323}»ekaj, Bonnie.
{60329}{60401}Nazovi Georgea Malleyja.|Neka doe ovamo.
{60409}{60486}Reci mu da nae englesko-|portugalsku knjigu,
{60498}{60601}i sazna kako se pita gde je|izgubljeni deËak. Shvatila?
{60619}{60650}George Malley?
{60656}{60739}Tako je. George.|Hajde, uËini to. Idi!
{60918}{60981}NeÊeö li se javiti?|- Ne kada radim.
{61014}{61095}Farmer sam celog ûivota,|ali ovaj rast je neverovatan.
{61193}{61229}Neugodno mi je.
{61234}{61294}éelim da probati svoje|gnojivo kod tebe.
{61300}{61411}Nasprejao si mi Ëizme. To je|najgora zemlja. Niöta ne raste.
{61436}{61489}Kladim se da bi kukuruz iöao.
{61498}{61595}Kladiö se? Nemaö novca za|klaenje. Sve si dao na stolice.
{61969}{62029}George Malley?|- Ja sam taj.
{62039}{62089}Ja sam John Ringold.
{62093}{62121}»uli smo se pre neki dan.
{62165}{62195}Sa Berkeleya?|- Da.
{62265}{62326}Drago mi je öto ste doöli.|- HoÊe li vaö pas da me pusti?
{62331}{62428}Da. Samo ga jako zanimaju|seizmolozi. Izaite.
{62468}{62511}Ovo je moj prijatelj,|Nate Pope.
{62554}{62619}DoneÊu vam hladno piÊe.|- Sa sveuËiliöte ste?
{62644}{62755}Jako nas zanima kako ste|uspeli da predvite zemljotres.
{62764}{62804}A, to.
{62829}{62893}Osetio sam subsoniËne talase.
{62900}{62958}Bio sam nad pukotinom,|öto je pomoglo.
{62964}{63034}Kakve ste instrumente|koristili? -Samo sebe.
{63055}{63159}Trebate da vidite kako pokreÊe|stvari umom. -Pusti sad to.
{63170}{63229}Osetio sam talase niske frekvencije.
{63238}{63324}Uhvatila me muËnina i vrtoglavica.|Tako sam to osetio.
{63331}{63421}ProuËavamo predvianje|zemljotresa 10 godina.
{63429}{63526}Nikad niko nije osetio|aktivnosti pre zemljotresa.
{63531}{63569}Sada jeste.
{63621}{63741}Imamo opremu u laboratoriji.|Moûete da doete na eksperiment?
{63755}{63793}DoÊi u Berkeley?
{63859}{63930}éeleli bismo da razgovaramo|sa vama da ovo razjasnimo.
{63938}{64014}Veoma bih rado doöao u Berkeley.
{64020}{64088}Mogu li da se upoznam|i sa drugim odelenjima?
{64094}{64156}Imam neke eksperimente|koje bih vam pokazao.
{64194}{64229}Dobri su.
{64291}{64340}U redu. Da vidimo.
{64441}{64481}Ovde sam koristio|solarne ploËe
{64489}{64566}za klijanje semena od|kojeg rastu ove biljke.
{64570}{64645}Promenio sam elektromagnetsko|polje. -G. Malley?
{64653}{64725}Ovde sam pretvorio svetlo|sijalice u sunËevu svetlost.
{64775}{64809}G. Malley.
{64829}{64913}Uzeo sam svinjsko gnojivo|i pretvorio u gorivo
{64919}{64974}koje pokreÊe automobil.
{64980}{65034}Samo me interesuje zemljotres.
{65039}{65124}Treba da znamo da li je to|bila sreÊa, sluËajnost.
{65156}{65199}SreÊa?
{65253}{65309}Zaöto ne pomeriö|neöto svojim umom?
{65338}{65409}Moûda njegovu periku,|ili tako neöto.
{65429}{65481}G. Ringold...|- Doktor.
{65489}{65537}Dr. Ringold, sluöajte...
{65573}{65649}Imam svoju baötu koja mi|sluûi kao laboratorija.
{65657}{65751}Imam ono öto vidite, ali moram|da priËam sa nekim poput vas.
{65819}{65876}Molim vas, ne idite.|U redu? Ne idite.
{65984}{66043}Doktor kaûe da je bolje da|odmah doeö. -äta je bilo?
{66050}{66156}Hitno je! Moraö usput|da nauËiö portugalski.
{66169}{66199}Moram da idem.
{66224}{66295}Portugalski?|NauËiti portugalski?
{66335}{66380}Zaöto i vi ne biste poöli?
{66584}{66672}{Y:i}KONVERZACIJSKl PORTUGALSKl|ZA PUTOVANJE I POSAO
{66823}{66892}Doktor je unutra. Misli|da je trovanje hranom.
{66975}{67014}Doktore, doöao je George.
{67029}{67080}On je dobro,|ali nema mu unuka.
{67088}{67164}Ako je pojeo ono öto je,|bi'e mu gore. Imaö knjigu?
{67200}{67245}Pitaj ga gde je deËko.
{67339}{67404}{Y:bi}U voÊnjaku je.|- U voÊnjaku je.
{67659}{67735}Kaûe da su pojeli neöto|pokvareno i da je deËko oboleo.
{68175}{68237}Tito je vozio kamion|dok sam ja Ëitao knjigu.
{68250}{68338}George Malley, nauËio si|portugalski za 20 minuta?
{68363}{68397}Ne sve.
{68445}{68494}Traûite dete?|- Kako se zove?
{68509}{68574}Berto.|Alberto ili Albert.
{68628}{68732}Raöirimo se i proËeöIjajmo|ovo drveÊe. Idemo.
{68739}{68783}PaûIjivo traûite.|Zovite ga.
{68804}{68839}Berto!
{68853}{68894}Berto!
{69092}{69127}Gde si, mali?
{69158}{69194}Gde si? Dolazimo.
{70334}{70369}George, öta je?
{70453}{70494}Nije u voÊnjaku.
{70500}{70535}Bolestan je, doktore.
{70614}{70643}Tamo je.
{70649}{70702}Gde tamo, George?|- Ovde.
{70740}{70770}To je dobro.
{70820}{70864}Sledimo te, George.
{71277}{71312}Da li si dobro, George?
{71324}{71364}Nisam to ja, nego on.
{71389}{71423}Reci mi gde je.
{71464}{71508}Ne znam. Ne znam.
{71849}{71898}{Y:bi}Boûe moj!
{72047}{72078}Tu su merdevine!
{72117}{72165}Sledite me!
{72415}{72449}Imao je pravo.
{72455}{72509}{Y:bi}Doite.|Ovde je gore.
{72529}{72595}Doktore, doi brzo.
{72618}{72654}Dobar si, George.
{72965}{73030}Moûe sreda? U 14 h?
{73037}{73120}Moûe. -Da poöaljem auto?|- DoÊi Êu sam, Johne.
{73125}{73223}BiÊe tamo neko iz solarnog|odelenja. Joö neöto?
{73264}{73348}Imate li poljoprivrednu|ökolu u Berkeleyu?
{73379}{73413}Za moje gnojivo.
{73429}{73465}PobrinuÊu se za to.
{73629}{73675}George...
{73714}{73759}{Y:bi}Ona ûena sa doktorom
{73784}{73883}deËakova je majka.|Ona jedina govori engleski.
{73902}{73950}äteta da ranije|nije bila ovde.
{73957}{74039}Da. Verovatno je|morala da traûi posao.
{74099}{74204}HoÊu da upoznate posebnog|Ëoveka. Naöao je vaöeg sina.
{74229}{74304}Poseban je. Ovo je George|Malley. Ovo je Ella.
{74499}{74528}Hvala vam.
{74534}{74579}U redu je.
{74659}{74700}Odvest Êu vas u bolnicu.
{74829}{74868}Bravo, öefe.
{74874}{74919}Kakav je posao traûila?
{74928}{75039}Mislim, kuvarice ili domaÊice.|Zaöto? Znaö nekog kome treba?
{75115}{75144}Nate.
{75153}{75194}George...
{75224}{75312}Naöao sam ti domaÊicu. Portugalka je.|I kuva. Savröena je.
{75329}{75378}Ne mogu da jedem|portugalsku hranu.
{75384}{75492}KuvaÊe öta god hoÊeö. I moûe|da ti sredi tvoju tzv. kuÊu.
{75509}{75542}Govori engleski?
{75549}{75619}Malo. RadiÊemo na|tvom portugalskom.
{75637}{75669}Mom?
{75675}{75714}Imaö neöto protiv?
{75744}{75830}Ne znam hoÊe li to uspeti.|- Pokuöajmo. äta hoÊeö da kaûeö?
{75889}{75993}Npr. neöto kao Moûete|li da doete dvaput nedeljno?
{76012}{76053}Moûete li da doete|dvaput nedeljno?
{76134}{76229}Lepöi ste od muzike.
{76270}{76317}To zvuËi komplikovano.
{76329}{76405}Imaö kasetofon.|NauËi fonetski.
{76420}{76476}Nema problema. äta joö?
{76524}{76564}Koliko na dan?
{76589}{76632}Dobro. Koliko na dan?
{76638}{76703}Vaöe lice je kao pesma.
{76732}{76789}Ovo mi se svia.|To je lepo. U redu...
{76873}{76954}Moûete li da poËnete sledeÊe|nedelje? -Savröeno. LogiËno.
{76984}{77087}Moûete li da poËnete sledeÊe nedelje?|U vaöim oËima... nebo.
{77107}{77144}Predivan jezik, zar ne?
{77150}{77197}To je sve?|- Da. Radi na tome.
{77239}{77304}Znaö, mogao bih da budem|dobar u portugalskom.
{77474}{77574}{Y:i}NLO-i: »INJENICE I FIKCIJA
{77636}{77667}Ne.
{77712}{77758}Nema veze. NaviknuÊeö se na njih.
{77769}{77854}Ako ih ostavimo na miru,|i oni Êe nas. Dobar odgovor.
{77883}{77919}äta to Ëitaö?
{77949}{78021}Gde si to uzela?|- Od mene.
{78044}{78102}To nije dobar izbor pre spavanja.
{78124}{78184}Joö se Ijutiö na njega?|- Da li je bitno?
{78192}{78297}Strava je. Kaûu da je spasio|ûivot deËaku u voÊnjaku.
{78317}{78352}Smeöan je.
{78358}{78422}Veoma smeöan. Stalno se smejemo.
{78502}{78578}»itaÊemo "Crnu lepoticu"|i neÊemo da govorimo o muökarcima.
{78584}{78639}Imam dovoljno briga. Previöe.
{78662}{78698}Kakvih?
{78704}{78781}Vas dvoje, npr.|- Viöe nismo mali.
{78787}{78873}Znam, ali mislite da je|George Malley siguran,
{78878}{78959}a bojite se kojota.|Pomeöali ste to malo.
{78966}{79052}Evo. Nai naöe mesto.|Idi da opereö zube.
{79096}{79144}Ne moraö li da napiöeö sastav?|- Jesam.
{79271}{79303}Verujeö li u ovo?
{79311}{79407}Da. Ljudi za NLO su|doöli otkad je George...
{79414}{79519}{Y:i}VANZEMALJCl: BLISKI SUSRET U HARMONU|- ... video. äiri se glas.
{79524}{79617}Veruj u öta god hoÊeö.|ProÊi Êe te to.
{79714}{79761}Mislila sam da idemo u krevet.
{79898}{79974}Moûemo li prestati da govorimo|o njemu? -Zaöto ga mrziö?
{80009}{80074}Jer mi se svia.|- Rekla sam ti.
{80086}{80218}Ali da je sad ovde sa nama,|ne biste li ga promatrali?
{80234}{80283}Pitale se o Ëemu razmiöIja?
{80293}{80371}Kad Êe otiÊi?|HoÊe li otiÊi?
{80461}{80494}To nam ne treba.
{80602}{80641}U redu je.
{80684}{80774}Za 20 minuta je proËitao celu|knjigu i znao portugalski.
{81107}{81206}Pa, George, kako si|osetio da zemljotres dolazi?
{81213}{81294}Da li su ti glasovi rekli?|- Glasovi? Ma ne.
{81312}{81351}äta joö znaö?
{81376}{81463}Znam da si se juËe opet|posvaao sa Lisom. -Kako znaö?
{81471}{81544}Kad ste zajedno, ona se|brine da ti se odeÊa slaûe.
{81596}{81648}Primaö li poruke, George?
{81654}{81714}Kad Paulette donese poötu, da.
{81721}{81811}Danas je kasnila 2 sata.|Trebal bi da se ûalimo.
{81868}{81909}äta je s zemljotresom?
{81914}{82018}Bio sam kod potoka Ash i|osetio vibracije. To je sve.
{82024}{82101}Kako si znao gde je deËak?|- Ne znam. Bonnie?
{82107}{82197}Znaö li öta Êe se dogoditi?|- Hajde, Rogere. éao mi je...
{82211}{82314}U biblioteci kaûu da Ëitaö 4|knjige dnevno. -Proöle nedelje.
{82439}{82483}Bolje je da idem.
{82496}{82548}Koliko jezika sada govoriö?
{82554}{82586}Oprosti, Jimmy.
{82636}{82682}Ako Êe se iöta loöe|dogoditi, reÊi Êeö nam.
{82709}{82739}Zar ne?
{83411}{83467}éao mi je öto sam|lagao o stolicama.
{83534}{83616}Samo sam ûeleo da mi doeö|u radionicu da razgovaramo,
{83668}{83757}umesto da uvek odlaziö od mene.
{83778}{83814}äta ûeliö?
{83889}{83933}Doi sa mnom u Berkeley.
{83939}{84002}Pozvali su me na|razgovor sa nauËnicima
{84009}{84087}o zemljotresu i nekim|mojim eksperimentima.
{84094}{84174}Gnojivo i solarne ploËe...|- Lepo.
{84182}{84214}Uzbuen sam,
{84264}{84369}ali sam verovatno i uplaöen.|Voleo bih da si tamo sa mnom.
{84381}{84439}Zaöto?|- Zbog podröke.
{84456}{84491}Samopouzdanja.
{84506}{84544}Prijateljstva.
{84551}{84609}Imaö prijatelje.|Znaö sve u okrugu.
{84628}{84692}Ne znam. Od onog sa voÊnjakom...
{84699}{84797}Ljudi su sada drugaËiji.|Ne svia mi se to. »udno je to.
{84803}{84913}Ti si verovatno jedina koja|se Ijuti na mene sa razlogom.
{85036}{85079}Samo pokuöavaö da se pomiriö.
{85108}{85202}Da. Pokuöavam da te|izmamim na izlazak.
{85208}{85264}I voleo bih kad bi|bila sa mnom kad me
{85269}{85399}nauËnici budu ispitivali.|U ökoli su me Ëesto kaûnjavali.
{85473}{85543}Kada? -U sredu.|- U koliko sati?
{85586}{85628}Krenuli bismo u podne.
{85634}{85727}BiÊu pred tvojom radionicom|u podne, ako idem.
{85733}{85769}Ako me nema...
{85788}{85819}U redu.
{85839}{85874}Hvala, Lace.
{86013}{86151}Dodirni me ujutro
{86198}{86294}Onda samo idi
{86488}{86514}Samo malo.
{86564}{86597}Evo me.
{86756}{86799}Vi ste g. Pope?
{86829}{86883}Vi ste g. Pope?
{86901}{86949}Ja sam Michaela.
{86964}{87010}Michaela.
{87048}{87089}Vi ste Ella?
{87179}{87224}Izvinite. Izvolite.
{87235}{87269}Moûda trebate...
{87298}{87340}Da, to je to mesto.
{87370}{87427}I kuvam. Treba vam kuvanje?|- Kuvanje.
{87460}{87538}Dobro. Fino.|Koliko plaÊate?
{87611}{87642}»ekajte.
{87688}{87752}Govorim malo portugalskog.
{87963}{88027}Ne znam öta ste rekli,|ali je zvuËalo sjajno.
{88086}{88117}Izvinite.
{88123}{88222}U redu. Sutra Êu da se|vratim. U devet. Moûe?
{88230}{88295}RadiÊu, pa Êemo onda o novcu.
{88321}{88348}»ekajte.
{88525}{88562}To je sve öto znam.
{88572}{88605}To, i...
{88818}{88862}Da li je to dobro?
{88911}{88950}Sladak si.
{89038}{89075}Do sutra.
{89123}{89157}Onda, do sutra.
{89182}{90682}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
