{1}{1}25.000
{26}{176}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{563}{633}Evo tople juhe,|sa pravim mesom.
{639}{687}Dega ti je poslao.
{1082}{1113}Moje ime je Maturette.
{2962}{2987}Kako si?
{3010}{3049}Dosta dobro.
{3100}{3178}Bio bi bolje da si im rekao moje ime.
{3215}{3242}Skoro jesam.
{3280}{3353}Netko je jednom rekao|da opiranje iskuöenju...
{3400}{3451}...je pravo mjerilo karaktera.
{3502}{3547}Kako si se izvukao iz "sto Ëetrdeset"?
{3570}{3633}Malo sam ih korumpirao.
{3639}{3720}Nepotrebno je reÊi, upravitelj|sada ima novu kuÊu...
{3725}{3776}...a ja sam postao njegov|glavni sluûbenik.
{3798}{3827}Papi, gledaj.
{3836}{3954}Moja ûena i odvjetnik su ubijedili|Ëlanove u Ministarstvu Pravosua...
{3960}{4009}...da je moja kazna bila preoötra.
{4019}{4072}Prije nekoliko mjeseci sam|ih pitao...
{4078}{4189}...da provjere tvoj sluËaj,|i napravili su neke pomake.
{4195}{4259}Jedan od glavnih svjedoka|protiv tebe...
{4265}{4369}...voljan je promjeniti priËu,|za odreenu cijenu.
{4383}{4444}Ako se to dogodi, kad Êe to biti?
{4450}{4492}Mogao bi biti vani za tri godine.
{4504}{4557}-Predugo.|-Ne, nije.
{4563}{4637}Sa dobrim poslom,|vrijeme Êe vrlo brzo proÊi.
{4661}{4762}Sluöaj me prijatelju.|Niöta mi ne dugujeö.
{4878}{4913}Reci mi öto ûeliö.
{4946}{4971}»amac.
{5131}{5173}Mogao sam si misliti.
{8470}{8524}Papi, zar me se ne sjeÊaö?
{8545}{8610}-Clusiot.|-Aha.
{8646}{8695}äto ti se dogodilo sa oËima?
{8737}{8851}Stavio sam otrovne bobice u njih,|da izgledam bolesno da doem ovdje.
{8857}{8891}Zaöto?
{8897}{8937}Idem s tobom.
{8942}{9025}-Molim?|-Aha. Sluöaj.
{9031}{9103}Dega te je stavio na listu|za rendgen sutra.
{9109}{9191}Doktor,on je isto zatvorenik,|Hindu ili neöto sliËno.
{9197}{9276}Ima nekoga vani tko ti|moûe prodati brod...
{9287}{9335}...ako je cijena prava.
{9407}{9449}Kada kreÊemo, Papi?
{9562}{9628}PopriËat Êemo sutra sa doktorom.
{9875}{9941}Zadnji Ëamac koji sam nabavio|je bio za seksualnog ubojicu.
{9947}{10037}Upucali su ga 6 milja nizvodno,jadnik.
{10043}{10101}Ali Ëamac je dobro izdrûao.
{10107}{10172}-Imaö srce ko u vola.|-Koji Ëamac?
{10178}{10239}5 metara,|kompletan,sa kompasom...
{10245}{10322}...jedra,alat,odjeÊa.
{10328}{10426}Generator je proradio.|Nauka preuzima stvar!
{10435}{10482}Rendgen je beskorisan.
{10488}{10572}Uvijek je bio.|Lezi dole,moliÊu.Na lea.
{10578}{10609}Koliko Êe koötati?
{10615}{10662}3000 unaprijed...
{10668}{10761}...koje daö meni,a ja dam Pascalu,|koji Êe sve nabaviti.
{10767}{10851}Duboko udahni, i miruj.
{10857}{10959}Joö 3000 moraö direktno dati|Pascalu kada nabavi Ëamac.
{10965}{11026}Izdahni i okreni se.
{11051}{11137}Ako se odluËim za to,|kako Êemo to obaviti?
{11143}{11221}Neboj se.NaÊi Êemo naËin.
{11248}{11311}Vjeruj mi.
{11320}{11431}Zadnji put kad sam nekom vjerovao,|zavröio sam 2 godine u samici.
{11436}{11484}Prevarili su te,ha?
{11490}{11586}Sva sreÊa da me novac ne privlaËi.|Ja se palim na neöto veÊe.
{11592}{11636}Duboko udahni.
{11661}{11750}Vidiö,pobio sam cijelu svoju obitelj.
{11756}{11857}Sve do jednog.|Moju ûenu i Ëetvoro djece.
{11869}{11927}Izdahni,ako veÊ nisi.
{11989}{12064}Ako me prevariö,ubit Êu te.
{12074}{12112}Naravno.
{12131}{12187}To bih smatrao uslugom.
{12199}{12253}Velikom uslugom.
{12729}{12807}Moûda Êu te zamoliti da odvedeö|onoga u wc...
{12812}{12897}...i zabaviö ga. Kada izaeö,|dobit Êeö 1000.
{12939}{12967}Zaöto?
{12993}{13088}To je moja stvar. Tvoje je|da ga usreÊiö 10 minuta.
{13094}{13137}1000.
{13147}{13183}Prljav je.
{13189}{13251}2000. Je li sada ËiöÊi?
{13394}{13444}-Misliö da sam kurva?|-Polako.
{13450}{13492}Varaö se.
{13514}{13548}SljedeÊi!
{15528}{15609}UËinit Êu öto si traûio,|pod jednim uvjetom.
{15614}{15692}Zadrûi novac,|i povedi me sa sobom.
{15697}{15779}-Ne.|-Ja sam jedini koji te moûe izvuÊi van.
{15968}{16008}-Ti si...|-Znam.
{16019}{16134}Ja sam peder.|Ja sam puöaË,ha?
{16174}{16229}Ali neöto si zaboravio.
{16236}{16348}Moûda ti je namjeöteno kao öto|priËaö,ali meni nije.
{16353}{16464}Izmeu nas,|ja sam taj koji je ubio Ëovjeka.
{16473}{16500}Ne ti.
{16611}{16644}Ok.
{17710}{17760}VeËeras za vrijeme koncerta.
{17783}{17876}Bit Êu tamo. Moram,|posluûujem napitke.
{17911}{17946}Moraö iÊi sa nama.
{17952}{18018}-Moraö.|-Hvala.
{18024}{18117}Supruga mi sreuje oslobaanje.|Njeno pismo kasni.
{18213}{18238}Sluöaj me.
{18271}{18353}Da je ona ovdje a ti u Parizu,|sa svim tim novcem...
{18359}{18418}...koliko bi platio|da je dovedeö nazad?
{18425}{18461}Sve öto imam.
{18514}{18602}A koliko bi ona platila|da te vrati nazad?
{18717}{18765}Zato trebaö pobjeÊi.
{18785}{18843}Sada,Louis, dok joö imaö öanse.
{18849}{18907}Ali imam öansu i bez bjeûanja.
{18986}{19030}Mene mogu ubiti.
{19047}{19082}Tebe posjeduju.
{19198}{19234}Zbogom.
{19251}{19285}Sretno.
{26705}{26730}Clusiot!
{27113}{27138}Clusiot!
{27230}{27264}Stoj!
{27504}{27595}Dega, prokletniËe!
{27602}{27635}Sranje!
{27640}{27675}Straûa!
{27877}{27905}Vuci!
{27917}{27950}Vuci!
{28103}{28130}PriËekaj.
{28499}{28527}Idemo.
{28532}{28561}Gdje je Clusiot?
{28567}{28620}-Straûa ga je uhvatila.|-Idemo.
{28987}{29031}Ovdje! Ovdje!|Gdje je drugi?
{29037}{29120}Ovdje.|Malo sam iöËaöio.
{29125}{29165}Idemo,idemo!
{30215}{30254}Eno ti Ëamac,tamo.
{30301}{30341}3000.
{30492}{30570}Provjeri je li u redu.|éuri mi se.
{30583}{30631}Idemo,idemo!
{30678}{30761}Nemojte koristiti puöke ako ne ûelite|lovce na ljude za vratom.
{30803}{30861}Utovario sam dva galona ruma.
{30876}{30934}Poöaljite mi razglednicu iz Hondurasa.
{31374}{31427}Isprobajmo taj rum.
{31682}{31712}Pa ovaj...
{31734}{31832}...prokleti brod niöta ne valja.|Pogledaj!Ubit Êu onu bitangu!
{31846}{31915}-Sav je od dijelova!|-Ko i moja noga.
{31976}{32029}Nisam iöËaöio zglob.|Slomio sam ga.
{32035}{32066}Slomio si nogu?
{32081}{32175}-Zaöto nisi rekao?|-Sumnjao sam da Êete me ostaviti.
{32181}{32240}-Prokleto si u pravu!|-Slomljena je.
{32246}{32295}Moramo je namjestiti.|Trebam pomoÊ.
{32300}{32363}-Pretpostavljam da Êe biti bolno.|-Moûeö se kladiti!
{32369}{32458}Zapamti da je ovo moj novac|öto tone.
{32464}{32553}Ovdje sam da glumim heroja,|da sprijeËim da te netko ne upuca.
{32559}{32616}Vjerojatno bi me ionako promaöio.
{32626}{32667}Opusti se sad. Opusti se.
{32672}{32725}Na krivom si kraju!
{32819}{32877}Trajat Êe samo nekoliko minuta.
{32989}{33081}-Isuse!|-Drûi ga iznad koljena!Spreman?
{33283}{33365}-To bi bilo to.|-Kako si to napravio?
{33385}{33426}Svi imamo osjetljive toËke.
{33435}{33464}äto se dogodilo?
{33470}{33538}Naöao je osjetljivu toËku za koju|nisi znao da je imaö.
{33993}{34038}Pomakni se,i mrtav si.
{34067}{34103}Okreni se.
{34128}{34183}Baci puöku ispred sebe.
{34249}{34303}Znaö, dobije 200 za ovoga.
{34308}{34388}Ne ûelim ga izgubiti.|Okreni se.
{34470}{34543}Pobjegao si iz St. Laurenta|sinoÊ,zar ne?
{34549}{34602}-ToËno.|-Drugi su kod broda?
{34629}{34673}-ToËno.|-Brod nevalja.
{34679}{34713}Nije za niöt.
{34752}{34780}OËekivao sam vas.
{34958}{34998}Idemo.
{35150}{35219}Ne pucaj.U redu je.
{35336}{35407}Uhvatio sam ova dva lovca u spavanju,|prije zore.
{35413}{35479}Muvali su se okolo,|ËekajuÊi vas.
{35511}{35594}Svaki put kad proda Ëamac,|u gorem je stanju nego prije.
{35679}{35706}Svia ti se ovo?
{35736}{35770}Jako.
{35776}{35839}I meni,nekad davno.|Ali bio sam pijan.
{35863}{35914}Evo,uzmi ovo.
{35919}{36005}Nareûi si bambusa|i spoji ih zajedno sa jedrom.
{36011}{36059}Vratit Êu se u sumrak.
{36125}{36199}OdvuÊi Êu vas uzvodno|do otoka Pigeon.
{36215}{36274}Moûete dobiti brod,|ako imate novca.
{36301}{36380}Ako nemate dovoljno,|vjerojatno Êe vas ubiti.
{36386}{36459}Njima je svejedno.|Svi su gubavci.
{37581}{37627}Radoznali kurvini sinovi.
{37646}{37695}Je li psi prenose gubu?
{37995}{38067}Pa,do vraga s tim.
{38072}{38115}-Bolje da uzmeö...|-äöö!
{38184}{38300}Ne ûelim se boriti sa ovim ljudima.|Samo ih ûelim maknuti od Ëamca.
{39448}{39496}Tko si ti?
{39565}{39616}Odbjegli zatvorenik Leptir.
{39628}{39721}-Gdje su ostala dvojica?|-Dolje na plaûi.
{39731}{39836}-Jedan ima slomljeni Ëlanak.|-Ui.
{40885}{40918}Imaö dvije puöke?
{40932}{41002}-Tako je.|-I ûeliö Ëamac?
{41034}{41107}-Tako je.|-Ali nemaö dovoljno novca.
{41157}{41192}To je toËno.
{41234}{41323}Zaöto se ne udostojiö da gledaö|u mene dok priËaö?
{41604}{41658}Bavimo se dosta krijumËarenjem.
{41664}{41733}PljaËkamo sa kopna.|Krademo Ëamce.
{41739}{41818}Kada autsajder doe,|ubijemo ga...
{41824}{41865}...kao mjeru predostroûnosti.
{41901}{41942}To ima smisla.
{41959}{42067}Opa! »ovjek kröËanskog razumijevanja!
{42108}{42157}Voliö li cigare?
{42181}{42222}Kada ih se dokopam.
{42281}{42332}Probaj ovu.
{43064}{43129}Kako si znao da imam suhu gubu?
{43135}{43179}Koja nije zarazna?
{43230}{43270}Nisam znao.
{43892}{43994}S povoljnim vremenom, ugledat Êeö|Honduras za tri i pol, moûda Ëetiri tjedna.
{44027}{44128}Kada doeö tamo, trebat Êe ti novac.
{44152}{44223}Uzmi,dezinficirano je.
{44273}{44393}Ako Êeö se zaraziti gubom,|bolje od novca nego od ljudi.
{44485}{44518}Uzmi.
{44598}{44664}Nama koristi samo za kockanje...
{44670}{44763}...i za dovoz gubavih ûena iz Albina.
{44768}{44818}Za to uvijek imamo dovoljno.
{44980}{45074}Poûuri se ukrcati.|Propustit Êeö plimu.
{45399}{45429}Zbogom.
{46318}{46354}Honduras!
{46932}{46997}Moja noga! Skini mi s noge!
{47002}{47081}Na nozi mi je! Prokletstvo!
{48532}{48591}U redu,hajde.|Hajde,joö jednom.
{48597}{48681}-Toliko sam pijan da ne mogu misliti.|-Aha.
{48687}{48730}To i hoÊu.
{48825}{48886}Stavi ovo izmeu zuba.
{48950}{48991}Ovo Êe te boljeti.
{49066}{49186}-Ako se ûeliö derati,deri se.|-Naravno da hoÊu.
{49903}{49966}-Pre....|-äto?
{50023}{50071}Prevario sam te,zar ne?
{51954}{51988}Samo malo.
{51994}{52023}äto hoÊete?
{52042}{52113}Identifikacija.Tko ste vi?
{52119}{52203}Mi smo ribari.|Naö prijatelj...
{52469}{52534}Prokletstvo,uspjeli smo!
{53223}{53253}Hej,prijatelju!
{53442}{53565}One bitange su me zavezale kao svinju.
{53573}{53633}-Ha?|-Bitange!
{56741}{56775}TragaËi!
{73717}{73761}Pokaûite papire,molim vas.
{74531}{74577}Novac,molim.
{76038}{76087}Koji je vaö zloËin?
{76126}{76157}Ubojstvo.
{76174}{76236}Ali nisam kriv.|Nikad nisam nikog ubio.
{76277}{76354}Da vam se povrati sloboda,|öto biste uËinili?
{76405}{76456}Nisam imao vremena razmiöljati o tome.
{76464}{76521}Ako ste lopov ili ubojica...
{76527}{76618}...do jutra, moûete ukrasti|sve öto imamo.
{76747}{76822}Ovo je moje.|Dobio sam na poklon.
{76843}{76893}Zadrûite ih dok ne odem.
{77349}{77387}Jesi budan?
{77392}{77433}Da,gospoo.
{77818}{77925}Ako si zgrijeöio, iskupio si se tako|öto si nahranio siromaöne ovdje.
{77937}{78013}Ako stvarno nisi zgrijeöio,|nemaö se Ëega bojati.
{78018}{78070}Bog Êe paziti na tebe.
{79885}{79965}Tvojih 5 godina u samici bliûi se kraju.
{79994}{80052}Platio si dio duga Francuskoj.
{81292}{81322}Papi.
{84021}{84086}To je jedini put sa otoka Devil.
{84172}{84227}Pokuöavamo ovdje uËiniti|stvari podnoöljivima.
{84264}{84377}Morski psi i plima obavljaju pravi straûarski|posao, zato ûivi i pusti druge ûivjeti.
{84394}{84447}Jedino ako ne stvoriö nevolje.
{84543}{84598}To je prazno,|moûeö uzeti.
{84604}{84689}Pripazi okolo drugih nastambi.|Mogli bi te ubiti.
{85727}{85783}Kako se usuujeö tu sjesti!
{85789}{85860}Ova klupa pripada kapetanu Dreyfusu!
{85866}{85921}Tko si ti da sjediö na toj klupi!
{85954}{85979}Nitko.
{85989}{86062}Tako je.Nitko.
{86081}{86132}Znaö li ti tko sam ja?
{86750}{86775}Dega?
{86955}{86995}Dega?
{87110}{87143}Dega.
{87398}{87428}Dega!
{87925}{87958}Louis.
{88050}{88078}Louis.
{88203}{88252}Bolje da nisi doöao ovamo.
{88506}{88554}Voliö li ribu?
{89311}{89344}Dobro je.
{89384}{89424}Stvarno tako misliö?
{89438}{89519}Nisam godinama bolje jeo.
{89656}{89693}Jesi Ëuo za moju ûenu?
{89735}{89780}Udala se za moga odvjetnika.
{89786}{89870}Ili je on oûenio nju,|iako...
{89876}{89914}...stvarno nije bitno.
{89920}{90021}Sve se svodi na jednu stvar,zar ne?
{90172}{90280}Nisam je Ëuo od...
{90319}{90375}Lijepo je ovdje,zar ne?
{90398}{90450}Ti si napravio da bude lijepo, Louis.
{90494}{90530}Jako lijepo.
{90610}{90640}Zanimljivo...
{90677}{90730}...kako smo ti i ja zavröili ovdje.
{90775}{90820}Mi smo jedini ostali.
{90910}{90940}Nije li to Ëudno?
{90946}{90975}Ne.
{91022}{91055}Meni je.
{91132}{91170}Bjeûi!
{91222}{91285}Bjeûi!Bjeûi!
{91305}{91345}Sad je dosta!
{91632}{91685}Dolaze i kradu iz mog vrta.
{91697}{91725}Tko to?
{91862}{91895}Moûda je bolje da krenem.
{91905}{91935}Da.
{92021}{92111}Znam tvoju kuÊu.Nema duhova unutra.
{92963}{93011}U mislima sam s tobom.
{93701}{93731}Isuse!
{94472}{94530}Louis! Louis!
{94536}{94640}Gledaj. SjeÊaö li se onih sjemenki öto|mi je dao Santini? Iznikle su.
{94646}{94670}-Mrkva.|-Louis.
{94676}{94754}Rekao je za 6 nedjelja,|ali bilo je potrebno samo 4.
{94760}{94833}Ako naem naËina da odemo odavdje,|bi li poöao?
{94839}{94871}Oh, da,naravno.
{94877}{94952}Freddie, znaö ti i bolje.|Bjeûi!
{94994}{95067}-Nemam novca,sve su uzeli|-Zaboravi.
{95073}{95128}-Ne moûeö platiti bijeg.|-Kako onda?
{95179}{95252}-Ne znam.|-Onda ne moramo priËati o tome.
{95258}{95335}Voliö li krumpire?|Imam viöka sjemena.
{95341}{95402}Mogao bi posaditi svoj vrt.
{95987}{96053}Vidiö,to je potkova.
{96075}{96138}Kad se valovi slome,|nemaju gdje otiÊi...
{96143}{96184}...nego se vratiti nazad.
{96190}{96264}Ne moûeö isploviti sa Ëamcem otamo.
{96270}{96361}Nema ni jednog mjesta na otoku|s kojeg moûeö krenuti Ëamcem.
{96367}{96464}VreÊe kokosovih oraha povezane|zajedno,samo ih prebacimo.
{96470}{96518}Plutat Êe na valovima.
{96557}{96603}I öto onda?
{96613}{96671}Kopno je samo 48 km odavdje.
{96677}{96728}Plutat Êemo po struji.
{96784}{96853}-Samo dva dana.|-Jesi siguran?
{96859}{96893}Aha.
{96929}{96963}»ini se...
{96976}{97010}OËajniËki.
{97030}{97059}Aha.
{97094}{97123}Misliö da bi moglo upaliti?
{97169}{97208}Zar je bitno?
{97398}{97433}To nije tvoje.
{97438}{97499}Bjeûi.|NeÊu ti ponavljati.
{97505}{97543}Evo ti, Freddie.
{97548}{97658}Freddie se ne osjeÊa dobro danas,|i to moraö uzeti u obzir.
{97668}{97698}Evo nas.
{97768}{97823}Ok,maleni.U redu.
{97880}{97920}Freddie!
{97935}{98000}Freddie, to nije za tebe,|to je za Adama.
{98006}{98044}Adame,doi.
{98086}{98144}-Proöetajmo.|-Naravno.
{98156}{98209}NIje li to premalo?
{98229}{98304}-Samo da isprobam.|-Naravno.
{98331}{98427}Znaö,razmiöljao sam da izgradim trijem.
{98433}{98525}Nema ni jedne kuÊe na otoku|sa trijemom.
{98531}{98649}»ak ni narednik Santini nema trijem.|äto misliö,ha?
{98655}{98692}Idemo.
{102211}{102249}Bio je krivi val.
{102290}{102336}Oh, da.
{102360}{102417}Dolaze u seriji od po sedam.
{102423}{102542}Sedmi val je dovoljno velik da nas odbaci|do toËke sa koje nema povratka.
{102604}{102629}Jesi siguran?
{102635}{102665}Aha.
{102693}{102726}OdliËno.
{102842}{102921}Oh, ako idemo bolje da|povadim mrkvu.
{103282}{103321}»etvrti val.
{103552}{103583}Spreman?
{103597}{103652}Moram ti neöto reÊi.
{103658}{103744}Louis, ne moraö niöta reÊi.
{103769}{103812}Mislim ozbiljno.
{103844}{103869}éao mi je.
{103921}{103947}Znam.
{104058}{104135}Poginut Êeö.Znaö to?
{104160}{104185}Moûda.
{104214}{104258}Molim te,ne Ëini to
{108186}{108284}Hej bitange,joö sam ovdje!
{108578}{108634}Papillon se dokopao slobode.
{108658}{108719}Ostatak svog ûivota...
{108724}{108769}...proveo je kao slobodan Ëovjek.
{108810}{108902}Ovaj, neslavni kazneni sustav|u Francuskoj Guiani...
{108908}{108954}... nije ga nadûivio.
{108987}{109112}UjAkStRiC subtitles 2003
{109137}{110637}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/58yx9|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
