{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{244}{395}TRGOVINA
{530}{623}ANNABELLA, UTAH - 10. rujna
{1937}{1984}Jesi li dobro, Stu?
{2065}{2095}Jesam.
{2142}{2174}Ne radi se o meni.
{2260}{2301}Radi se o Haroldu.
{2347}{2396}Haroldu se neöto dogodilo.
{2696}{2725}Nadine!
{2779}{2809}Pomozi mi!
{2907}{2935}UpomoÊ!
{2964}{3015}Sam si rekao, Harolde.
{3080}{3115}Prokleti smo.
{3147}{3195}Ne moûeö me ostaviti!
{3237}{3286}Ne smeö! Ne smeö me ostaviti.
{3512}{3553}Slomljena su mi rebra.
{3565}{3628}l noga! Vrati se!!
{4040}{4111}Vrati se!
{4158}{4270}Nadine! Nadine!
{4535}{4638}PRlJEVOJ TARGHEE, lDAHO - 1 1 . rujna
{5738}{5807}Prijatelj protiv GRlPE|Zaustavlja gripu pre nego ona vas!
{5810}{5886}OVlSNlK O DROGl
{6232}{6292}Ako sad izaeö, Bobby Terry...
{6375}{6419}Remi!|- Dovraga!
{6448}{6519}Javi se, Straûa 9!
{6521}{6575}To je Henreid!|- Znam.
{6630}{6684}Ovde sam, g. Henreid.
{6706}{6785}Nismo joö niöta videli. Nijedno vozilo.
{6787}{6830}Dobro motrite!
{6850}{6920}l ne zaboravite da ga ne smete ubiti!
{6922}{6974}TaËno... HoÊu reÊi prijam!
{6982}{7013}Samo to upamti.
{7016}{7098}HoÊemo da svi tamoönji ljudi|znaju öto ih Ëeka.
{7100}{7131}Pozor!
{7133}{7166}Prijam to!
{7320}{7411}Taj si ni nos ne bi znao pametno ispuhati.
{7457}{7524}VraÊaö li se, Lloyde?!
{8093}{8154}Mislio sam da kaniö spavati.
{8164}{8228}Moûda bih trebala pilulu za spavanje.
{8310}{8352}Smatraj me doktorom.
{8756}{8800}DOBRODOäLl U COPPERFlELD lDAHO
{8803}{8871}OPUSTlTE SE l ODMORlTE
{8895}{8977}Ti si ih bacio, trebao bi ih i dignuti.
{8979}{9038}Baö si blesav.
{9041}{9090}A ti baö ne znaö gubiti.
{9142}{9210}Evo ga! Brzo, pobeÊi Êe!
{10038}{10103}Zapamti, u trbuh!
{10118}{10159}HoÊe njegovu glavu.
{10180}{10272}Kad ga ovime pogodim,|neÊe ni ostati niöta osim glave.
{10766}{10854}Ostani ovde. l pazi da ti ne vidi to Ëudo.
{10860}{10919}PoËelo je!
{11235}{11280}Nemoj ga razneti!
{11364}{11442}Ne bi valjda ubio|nenaoruûana Ëoveka, stari?
{11445}{11494}Jeste li bili u Copperfieldu?
{11496}{11558}Jesmo, videli smo kako prolaziö.|Ja sam Dave Roberts.
{11560}{11627}Gadovi!
{11646}{11693}lmam ga, Dave!
{12067}{12112}Sredio sam ga naËisto, Dave!
{12429}{12486}U velikoj si gabuli, sinko.
{12691}{12741}Rekao sam ti da ga ne ubijeö!
{12853}{12935}Rekao sam ti da ga ne ubijeö!!
{13582}{13633}Dobro, dobro! Dosta, do avola!
{13655}{13706}Ovde Lloyd. Javi se.
{13713}{13757}Sudija je gotov.
{13838}{13866}äto?!
{13924}{13952}Gotov!
{13962}{14021}Gotov je, sasvim gotov!
{14051}{14090}»ujeö, budalo?!
{14126}{14161}Da.
{14187}{14246}Vreme je da sredimo öpijuna broj 2.
{14282}{14311}Znaö li ko je to?
{14330}{14385}Od poËetka znam.
{14592}{14692}Sluöaj me vrlo pozorno, vojniËe.
{14729}{14755}Probudi se!!
{14874}{14905}Doi ovde.
{14910}{14973}Odjeni se, öpijunska kurvo!
{15134}{15182}Ne moraö u kupaonicu, moûeö i ovde.
{15184}{15221}Da, uËini to ovde.
{15223}{15333}NeÊeö me viöe videti golu|u svom kratkom, bijednom ûivotu!
{15335}{15396}ldem unutra, a pokuöaö li me spreËiti...
{15398}{15464}promijenit Êu ti spol!
{15466}{15500}lspriËavam se.
{15513}{15546}Pusti je.
{15550}{15621}Pokuöa li se zakljuËati, provali vrata.
{15623}{15708}Jasno ti je da sam svaki put|hinila da uûivam, zar ne?
{15910}{15964}Koga se avola smeö?
{16118}{16181}Nisam riskirala ûivot...
{16198}{16247}i spavala s tobom iz uûitka.
{16247}{16268}i spavala s tobom iz uûitka.
{16301}{16407}Znate li vi öto vaö limeni bog kani, ljudi?
{16453}{16548}äto mislite da rade tamo u lndian Springsu?
{16700}{16751}Ne izaeö li za pola minuta...
{16753}{16814}u gaÊicama Êeö pred Flagga!
{16816}{16840}Da!
{17087}{17194}On kaûe hop, a ti skoËiö!|Tako to ide, zar ne?
{17206}{17269}On je najveÊi i najmoÊniji.
{17272}{17336}Greöiö, glupane.
{17338}{17368}Hajde.
{17652}{17730}lmam je, R.F.-e.|- R.F.
{17732}{17775}Poöalji je unutra, molim.
{18101}{18165}Dayna! Prii!
{18230}{18317}OËekivala si u najmanju ruku|»arlsa Mansona.
{18323}{18376}Ne znam öto sam oËekivala. Lloyd...
{18464}{18559}Jadni Lloyd je u Phoenixu|imao vrlo gorko iskustvo. Nedavno.
{18589}{18672}To je ostavilo traga. Sedni, Dayna.
{19076}{19155}Gde su stoci?|- Dao sam ih izbaciti.
{19181}{19236}Laûljivci sede na stocima...
{19255}{19324}a istinoljubivi se zalegnu.
{19374}{19445}Prijatelji iz Bouldera poslali su te|da nas öpijuniraö?
{19447}{19489}Valjda.|- Tebe...
{19503}{19535}suca.
{19549}{19642}Nekako ne vidim ko je treÊi.
{19676}{19780}Katkad, zapravo uglavnom,|sam saznam takve stvari.
{19783}{19873}Ja sam ti jedan od retkih sreÊnika|s nadnaravnim moÊima.
{19886}{19965}Ali kad god pokuöam videti|ko je treÊi öpijun...
{20036}{20075}jedino öto vidim...
{20090}{20124}je Mesec.
{20144}{20237}Piöe se M-J-E-S-E-C.
{20391}{20455}ZnaËi li ti to öto, Dayna?
{20473}{20507}Baö niöta.
{20570}{20648}äta je sa sucem?|- On je nevaûan.
{20662}{20709}Dobro me sluöaj.
{20745}{20761}Voljan sam...
{20761}{20808}Voljan sam...
{20810}{20862}te poslati natrag u Boulder.
{20864}{20954}l hteo bih da im kaûeö...
{20957}{21051}kako se i mi pokuöavamo oporaviti.|Baö kao i oni.
{21062}{21113}l da im ne ûelimo nauditi.
{21119}{21224}A öto onda rade Carl Hough|i onaj nastrani Smetlar?
{21227}{21289}Projektilima u zraËnoj bazi...
{21292}{21345}buöe nove izvore vode?
{21388}{21442}Ma pusti Smetlara.
{21454}{21553}l odustani, duöo. Nema razloga|da se nastaviö baviti öpijunaûom.
{21571}{21649}Vaöa je stara crna veötica mrtva,|ljudi su zbunjeni.
{21651}{21716}Ako si i imala razloga da doeö,|viöe ga nemaö.
{21718}{21768}Majka Abagail nije mrtva!
{21866}{21907}Bojim se da jest.
{21940}{21970}Ne verujem!
{21973}{22054}Umrla je u komi, bez reËi.
{22148}{22183}To je sve, duöo.
{22359}{22413}HoÊeö reÊi da mogu jednostavno otiÊi?
{22503}{22551}Joö jedna stvar.
{22609}{22692}äto to?|- Ko je MjeseËar?
{22701}{22735}Ne znam.
{22802}{22833}Mislim da znaö.
{22835}{22916}Doista ne znam. Nisam znala ni za suca...
{22918}{23006}sve do Lloydova razgovora s ldahom.
{23008}{23055}LogiËno.
{23085}{23139}No ipak znaö.
{23160}{23227}Znaö i moraö mi reÊi. Jasno?
{23230}{23315}Zaöto ti to veÊ ne znaö?!
{23317}{23352}Ne znam!
{23393}{23444}Reci, gaduro! Reci!!
{23464}{23497}Evo ti ga na!
{23675}{23710}O, draga moja.
{23946}{24006}Reci mi öto hoÊu znati.
{24010}{24090}ReÊi Êeö mi pre nego öto zavröim s tobom!
{24336}{24390}Stani!
{25113}{25179}Vrati se za puna meseca.
{25188}{25226}Pun je mesec.
{25270}{25350}Piöe se M-J-E-S-E-C.
{25631}{25675}Pazi!
{25810}{25839}Umobolnik!
{27454}{27532}OPROSTlTE Ml - BlO SAM ZAVEDEN
{28023}{28060}äto je, Stu?
{28101}{28133}Harold...
{28170}{28202}mrtav je.
{28262}{28343}Ne znam kako ili zaöto, ali mrtav je.
{28381}{28428}Raznio si je glavu.
{28562}{28596}U ustima oseÊam...
{28615}{28667}okus maziva za piötolj.
{28740}{28818}Neka mu se Bog smiluje|njegovoj bijednoj duöi.
{30226}{30283}BAZA lNDlAN SPRlNGS
{30285}{30385}äto je stara Semple rekla|kad si joj spalio penziju?
{30387}{30457}Oni koji se igraju vatrom,|piöke u krevet, Smetlaru!
{30470}{30514}Ostavite me na miru.
{30533}{30628}Zaveûite o starici Semple|i ostavite me na miru!
{30652}{30696}MiËi ga od mene!!
{30700}{30777}Strpat Êete u ludnicu...
{30779}{30861}i dati ti hiljadu elektro öokova!
{31017}{31094}Smetlaru, svugde te traûim!
{31341}{31427}Prokleti piroman!|Nemam poverenja u njega.
{31546}{31584}Samo trenutak.
{31600}{31634}»ekaj malo, do avola!
{31634}{31659}»ekaj malo, do avola!
{31675}{31709}Boûe, ne!!
{31878}{31915}Ostavite me na miru!!
{32063}{32105}Nisam odolio!
{32150}{32217}Oprostite!!
{32280}{32347}Tako mi je ûao!!
{33343}{33385}Nadine!
{33453}{33487}Ovamo!
{33529}{33574}Ovde sam, ljubavi.
{33709}{33768}Las Vegas - 90 km
{33772}{33821}Tako treba, ovuda.
{34503}{34537}Randalle...
{34589}{34625}jesi li to ti?
{35844}{35899}Tako te dugo Ëekam.
{35926}{35971}»ekanje je zavröeno.
{37154}{37229}Ne!|- Prekasno ti je da kaûeö ne, draga.
{37281}{37320}Puno prekasno.
{37323}{37347}Ne!!
{37602}{37676}Boûe, ne!!
{38339}{38395}Od detinjstva nisi bio u takvoj formi.
{38397}{38436}SAN RAFAEL, UTAH - 13. rujna
{38438}{38486}VeÊ sto godina.
{38510}{38604}Postoji savröeno dobar razlog|za ovu öetnjicu, znate.
{38606}{38682}Majka Abagail ga je znala...
{38683}{38728}kad nas je poslala bez prtljage.
{38730}{38831}éeluci su nam prazni,|a öto je joö vaûnije, glave su prazne.
{38838}{38907}Moja je oduvek bila prazna.
{38925}{38957}Ozbiljno.
{38959}{39026}Sad smo usred|Velike ameriËke zemlje Nedoije.
{39029}{39113}Bez sve one prtljage|koju bismo nekoÊ nosili.
{39115}{39184}éeljela nas je oËiöÊene, prazne...
{39198}{39270}spremne da se ispunimo neËim novim...
{39273}{39317}velikim.
{39332}{39387}Zacelo i zadnjim na svetu.
{39535}{39641}Hajde, Kojak! Donesi!
{39936}{39988}Dobro doöli u Las Vegas!
{40409}{40452}Ako je krelac vaûan...
{40455}{40524}svakako reci da sam ti ja rekla.
{40529}{40578}Ja!|- Dobro, dobro.
{40606}{40705}Drago mi je öto te vidim!|- OËekivali smo te sinoÊ.
{40742}{40787}Znaö kakvi su mladenci.
{40791}{40840}Nismo uspeli naÊi Smetlara.
{40842}{40894}Traûimo ga po pustinji...
{40896}{40937}ali to su velika prostranstva.
{40940}{41027}VeÊ Êe se on vratiti. A kad se vrati, ubijte ga.
{41029}{41067}Milosrdno.
{41126}{41189}Dvojim da Êeö razumeti...
{41214}{41276}ali nekako sam se vezao uz momka.
{41291}{41349}Ne ûelim da pati.|- Dobro.
{41394}{41443}Mislio sam...|- Reci mu!
{41536}{41577}Drsko dete.
{41829}{41854}Doi, duöo!
{41857}{41922}Ovo bi moglo biti vaûno. Cura misli da je...
{41925}{42012}Poslije!! Doi posle podne. Moûe u 13 sati.
{42028}{42068}U meuvremenu...
{42093}{42144}Luda je za mnom.
{42149}{42194}Nikako da joj bude dovoljno.
{42219}{42256}Maöi pa-pa!
{42401}{42448}Mrtvi smo...
{42467}{42548}a ovo je pakao!
{42612}{42659}ObeÊao si da Êeö mu reÊi!
{42662}{42711}Zaveûi, do avola.
{43055}{43109}Moûeö li otvoriti, duöice?
{43152}{43185}»ini se da ne.
{43423}{43470}Ui, Lloyde!
{43648}{43735}Mislim da ti nisam rekao|kako mi se zove ûena.
{43926}{44014}Nadine, ovo je Lloyd Henreid,|moj prvi vojnik.
{44028}{44104}Drago mi je.|- A, ne! Rukujte se!
{44183}{44223}Daj mu ruku.
{44273}{44304}Tako je.
{44353}{44411}Moûeö je spustiti, ljubavi.
{44518}{44562}Mojoj ûeni nije dobro.
{44575}{44635}A i napumpana je.
{44642}{44693}Moûda to ima veze jedno s drugim?
{44705}{44763}Jesi li za malo vatrene vodice?
{44765}{44831}Da nazdravimo junioru.
{44885}{44942}Ja Êu gin i tonik.
{44951}{45003}PiÊe pobednika. Daj dva.
{45022}{45066}Sedni, ljubavi.
{45230}{45271}éalim, draga.
{45282}{45367}Ministar zdravstva rekao je|da trudnice ne smeju piti.
{45393}{45468}Rekao je to i umro od kuge, zar ne?
{45650}{45729}lz Bouldera stiûu Ëetiri muökarca.
{45748}{45809}Hodaju Autocestom 73,|iz nekog ludog razloga...
{45811}{45872}poznatog samo njima i mrtvoj staroj veötici.
{45874}{45951}HoÊu da ih dopremite ovamo.
{45957}{46000}Neka Barry Dorgan...
{46028}{46063}vodi momke.
{46066}{46126}HoÊeö li da postavim kriûeve?
{46160}{46253}Treba smisliti ötogod maötovitije, ovaj put.
{46324}{46384}Domoroci su nemirni, znaö.
{46409}{46493}äta je s onom mröavicom öiömiöasta lica?
{46523}{46553}äto je muËi?
{46556}{46619}Misli da je preksinoÊ videla|njihovog treÊeg öpijuna.
{46620}{46660}Pre ga je videla u Kansasu...
{46663}{46729}u druötvu gluvonijema momka.
{46740}{46821}Ne znam, ali moûda je to onaj gluvonijemi|iz Odbora...
{47021}{47047}äta je sad?!
{47150}{47185}äta sam uËinio?!
{47225}{47285}Pustio si me da odem gore,|a da mi to nisi rekao?!
{47287}{47371}Mogao bih ti u hipu zavrnuti vratom!|Moûda bih i trebao.
{47373}{47428}Pookusio sam ti reÊi. Prekinuo si me.
{47761}{47811}Mrzim to!
{47855}{47891}Pogledaj ovo.
{48487}{48551}Kakvo je piÊe?|- lzvrsno.
{48563}{48608}lma ga po celom zidu.
{48821}{48879}Moram ti priznati neöto.
{48894}{48963}PriliËno si hrabar za frajera...
{48965}{49047}koji je cimera hteo pretvoriti u sendviË.|- Hvala.
{49062}{49103}Je li tako, Nadine?
{49127}{49162}Kaûe da.
{49334}{49441}Taj frajer kojega ona Ëupava misli|da je videla...
{49535}{49573}Kako se zove?
{49701}{49733}Tom Cullen.
{49759}{49823}Verovatno nije vaûan, ali...
{49907}{49988}Poöalji sto ljudi. Neka ih vodi Russ Dorr.
{50005}{50079}Moûda im se posreÊi i nalete na njega.
{50083}{50166}äto Êemo sa Smetlarom?
{50454}{50493}Zapamti...
{50535}{50608}kad se vrati, hoÊu da umre brzo i bezbolno.
{50669}{50730}Je li sve u redu?
{50772}{50834}Super. Zaöto pitaö?
{50884}{50952}Neki su ljudi malo zabrinuti.
{50970}{51069}l ja sam malo, iskreno reËeno.
{51105}{51154}Sve je u redu, Lloyde.
{51194}{51305}l dalje Êe biti dobro,|sve dok ne zaboravljaö ko je öef.
{51365}{51412}l ko ima moÊ.
{51421}{51450}TaËno?
{51494}{51522}Tako je.
{51919}{52037}Dolaze po tebe, znaö!|Stara ih je poslala pre smrti.
{52083}{52142}Dovuci guzicu natrag ovamo!
{52257}{52374}Raspada se sve öto si ovde stvorio.
{52403}{52521}PriËa se da je maloumni momak|preveslao Randalla Flagga.
{52531}{52621}PriËa se da je sudija Farris|pobegao tvojima u ldahu.
{52639}{52694}Mrtav je kao Juda lökariotski.
{52721}{52786}Raspituju se i o Dayni.
{52818}{52913}Sve ti skliûe kroz prste.
{52954}{53006}äapÊu, Randy.
{53081}{53185}Vidim kako napuötaju|svoja straûarska mesta usred noÊi.
{53187}{53237}A tvoje ih oËi ne mogu videti.
{53311}{53361}A kad oni dou.
{53399}{53427}Stu...
{53458}{53491}i Ralph...
{53501}{53541}Glen...
{53549}{53574}i Lar...
{53652}{53697}Kad oni dou...
{53707}{53803}tvoje Êe vreme isteÊi. A ja Êu to gledati...
{53805}{53890}iz pakla, s tvojim detetom u naruËju.
{54019}{54061}Vrati se, Nadine.
{54063}{54136}DaÊu ti sve öto poûeliö.
{54181}{54234}Moûeö li mi opet dati Larrya?
{54311}{54379}Sjeme ti se zatrlo.
{54381}{54431}Laûeö!!
{54482}{54507}Ne!
{54717}{54754}Nije vaûno.
{54835}{54877}Sada nema odstepena.
{55006}{55051}Ostajem ovde!
{55104}{55141}»ujeö li me?
{55204}{55237}Ostajem ovde.
{55249}{55336}NUKLEARNO SKLADläTE PRUHROCK|1 7. rujna
{55704}{55733}Vatra!
{55762}{55832}Velika vatra!
{56321}{56406}ZA KRAJ SVlJETA
{56583}{56629}Moj ûivot za tebe!!
{57067}{57125}Zaöto si me pozvao ovamo, White?
{57220}{57259}Zidovi imaju uöi, zar ne?
{57303}{57327}Dakle?
{57353}{57421}Ja i joö neki briöemo odavde.
{57434}{57516}Lud sam öto ti ovo govorim.|- U redu je.
{57540}{57582}Kuda Êete?
{57587}{57658}U Juûnu Ameriku, blizu Ria.
{57698}{57766}Jenny je bila tamo i kaûe da je vrlo lepo.
{57771}{57851}Sveûa voda, sveûe voÊe, okeanski zrak.
{57885}{57929}ObiËni ljudi.
{57949}{58021}Oni koji ûele zaboraviti da su ovisili...
{58023}{58081}o Vraûjem VeliËanstvu.
{58129}{58195}äta kaûeö?|- Ja?
{58197}{58251}Ostajem ovde.|- Zaöto?!
{58265}{58339}Zar ne uviaö da se sve raspada?|- Moûda.
{58346}{58435}Ali on me spasio od smrti od gladi.|No ni to nije najvaûnije.
{58476}{58523}Promenio me.
{58546}{58626}Vjerovao mi je. Zato ostajem do kraja.
{58699}{58737}Lud si, ËoveËe!
{58771}{58804}Verovatno imaö pravo.
{58831}{58925}GRANlCA NEVADE l UTAHA - 1 7. rujna
{59022}{59102}Mislio sam da Êe biti prostitutki.|Ne vidim ih.
{59110}{59169}On ne ûeli ni da pijemo.
{59172}{59233}A droga. Ne dolazi u obzir.
{59266}{59304}Razmiöljao sam.
{59324}{59388}Moûda se i neÊu vratiti u Vegas.
{59397}{59467}Mexico je samo 450 km odavde,|u onom smeru.
{59575}{59663}äta je to?!|- Neki jelen. Svugde ih ima.
{59666}{59736}Moûda bismo trebali pogledati.|- ldi.
{59785}{59864}Zaöto bih ja tumarao po mraku?
{59866}{59951}Moûda i nogu slomio. Sve to|zbog perverznjaka u kaubojskim Ëizmama.
{59959}{60036}Oprezno, Rich. On nekako...
{60038}{60110}sve Ëuje i vidi. Ne bojim se ja Flagga.
{60157}{60239}Daj mi joö jednu.
{60253}{60285}M-J-E-S-E-C...
{60307}{60346}tako se piöe ¥¥mesec.¥¥
{60726}{60810}AX, UTAH - 18. rujna
{61677}{61757}Neko bi trebao obavestiti|prometnu policiju Utaha.
{61759}{61828}Odron od poplave, verovatno. Uûasno!
{61844}{61918}Misliö li da Êeö uspeti siÊi, Glene?|- Mislim da hoÊu.
{61930}{61975}äto ti misliö, Kojak?
{62159}{62217}Moûe li itko od nas bolje od njega?
{62233}{62265}Hajdemo!
{62566}{62614}Samo napred, profesore!
{62666}{62704}Pazite se!
{62771}{62801}U redu!
{62836}{62880}Krenite, momci!
{63376}{63411}Pazi, momËe.
{63503}{63537}Hajde, Stu!
{63647}{63706}Bilo je lako!|- Moûda.
{63732}{63767}Moûda smo samo imali sreÊe.
{63770}{63861}»inilo mi se da je i korak dovoljan|pa da se sve uruöi.
{63864}{63912}Ni na ovoj strani nije bolje.
{64022}{64075}Ko Êe sada iÊi prvi?
{64096}{64124}Ja Êu.
{64143}{64206}Vi Ëekajte da se popnem.
{64228}{64260}Budi oprezan!
{64275}{64314}Nema frke.
{64661}{64715}Ode!|- Sve je u redu!
{65329}{65358}Eto vidite!
{65374}{65424}Rekoh vam, nema frke!
{65451}{65487}Moj Boûe!
{65685}{65716}Polako, polako.
{65750}{65804}Nije glava, nego...
{65853}{65903}Ne miËi se!|- Noga!
{66130}{66171}Samo mirno, Stu...
{66319}{66359}Dobro sam. Samo napred!
{66439}{66478}Eto, gotovo je.
{66697}{66768}To je dobar naËin da se ubijeö.
{66831}{66883}Odakle ti piÊe?|- TuristiËki autobus...
{66885}{66947}nedaleko odavde.
{66950}{66990}lma i piva!
{67003}{67067}Ali neÊu da ovo uzmeö s alkoholom.
{67069}{67136}Ponio sam ih za svoj artritis.
{67149}{67187}Do dna!
{67205}{67259}lduÊi put idemo Ralph i ja.
{67261}{67322}Ostani sa Stuom i odmori se.|- Kuda Êete?
{67339}{67418}Napravit Êemo nekakva nosila|da te odnesemo.
{67420}{67479}SmestiÊemo te negde,|najbolje u Green Riveru.
{67481}{67512}Ne, Larry.
{67560}{67632}Ne idem.|- O Ëemu to govoriö?
{67655}{67747}Kaûem da ne idem. Nema puta|u Green River, nema nikakvih stvari.
{67749}{67832}To je protiv pravila igre.|- Ovo nije igra, Stu!
{67834}{67874}Stu ima pravo, Larry.
{67888}{67954}Majka Abagail je rekla|da Êe jedan usput pasti.
{67954}{67995}äto to znaËi?
{68017}{68111}äto to govoriö?!|Pa ti si sveuËiliöni profesor, zaboga!
{68142}{68222}Viöe nisam.|Nisi primetio da viöe nema ökole?
{68224}{68278}Mislio sam da ti je Larry prijatelj!
{68295}{68343}Dakako.
{68386}{68426}No to sad nije vaûno.
{68428}{68476}To je Boûji plan.|- Zaveûi o Bogu!
{68478}{68519}Dosta mi je priËa o Bogu!
{68521}{68573}Putovanje se temelji na tom...
{68575}{68631}da je Abagail znala öto govori.
{68635}{68679}TaËno!|- Nije u redu!!
{68731}{68797}Ne radi se o Boûjoj volji ili o Boûijem planu...
{68807}{68888}nego o odronu! lmaö slomljenu nogu.
{68891}{68946}NeÊu te ostaviti!|- Sluöaj!
{68948}{68982}äto?|- Sluöaj.
{69073}{69129}Kad smo krenuli na put,|prepustili smo ûivote...
{69132}{69223}u ruke Majke Abagail i Boga.|To se nije promijenilo.
{69242}{69331}Ako On ûeli da jedem, On Êe poslati hranu.
{69333}{69381}Ako ûeli da pijem...
{69427}{69463}poslat Êe kiöu.
{69518}{69637}To je Njegov posao,|a tvoj je da se suoËiö s Flaggom.
{69641}{69721}Moraö to uËiniti i bez mene!
{69887}{69953}Znaö li kako to ludo zvuËi?
{70020}{70093}Znaö li kako to vraöki ludo zvuËi?
{70760}{70788}Hvala.
{70823}{70898}Viöe od tri ili Ëetiri|verovatno su smrtonosne.
{70926}{70966}Jasno ti je, zar ne?
{71042}{71083}Valjda.
{71151}{71185}Zbogom, Stu.
{71220}{71268}Bilo je lepo poznavati te.
{71304}{71360}Ako se budemo vraÊali ovuda...
{71459}{71489}Da, ako.
{71538}{71656}U meuvremenu, recimo si dovienja.
{72374}{72416}ldemo, Kojak!
{72435}{72468}Hajde, deËko!
{72518}{72574}Vrati se po njega.
{72585}{72688}Majka je takoer govorila|da sve stvari sluûe volji Boûjoj.
{72706}{72770}Moûda se to odnosi i na velike, glupe pse.
{72790}{72848}Dobro se brini za njega, Teksaöanine!
{74464}{74557}KANOSH, UTAH - 21 . rujna
{74964}{75003}Dobar pas!
{75043}{75083}Dobar deËko!
{75210}{75292}HoÊeö jesti? Valjda je gotovo.
{75588}{75633}Sve mi je gore, stari.
{75683}{75755}»ini se da Êu naposljetku|ipak umreti od gripe.
{75900}{75970}To je priliËno smeöno, kad bolje razmisliö.
{76270}{76301}Evo, deËko!
{76371}{76424}lzgubio sam apetit.
{76467}{76495}Jedi.
{76817}{76860}Nedostajeö mi, Frannie.
{76898}{76930}Nedostajeö mi.
{77347}{77395}Stigosmo!
{77746}{77789}¥¥NeÊu se bojati zla.¥¥
{77826}{77858}NeÊu se bojati zla.
{78059}{78090}ldemo!
{78242}{78320}Ne pucaj! Flagg ih ûeli ûive!
{78629}{78676}Stojte! Ni makac!
{78684}{78724}Rekao vam je da stanete!
{78852}{78887}Kako ide?
{78953}{78995}Gde je Stuart Redman?
{78997}{79073}lmao je malu nezgodu na putu, gospodine...
{79075}{79183}Paul Burlson, moj zamenik! Ja sam|Barry Dorgan. äef vegaöke sigurnosti.
{79186}{79240}Kakva nezgoda?|- Slomio je nogu.
{79259}{79331}Sluöajte, öefe Dragone, kako se veÊ zovete.
{79331}{79362}Sluöajte, öefe Dragone, kako se veÊ zovete.
{79364}{79395}Nastavimo s ovim.
{79397}{79470}Dobro. Po sluûbenoj duûnosti,|pametnjakoviÊu...
{79472}{79516}uhapöeni ste.|- U Ëije ime?
{79518}{79607}Znaö koga predstavljam!|- Zaöto onda ne kaûeö?
{79690}{79737}Ja Êu.
{79744}{79799}Naziva se Randall Flagg...
{79801}{79872}a zapravo je vraûji aposto.
{79874}{79950}Jesi li to zapisao u svoju tekicu,|g. Burlsone?
{79952}{80044}HoÊete mi reÊi brojeve svojih iskaznica?
{80175}{80223}Razdvojite ih.
{80224}{80304}Onog nasmijanog i starog strpaj u moj auto.
{80307}{80392}SeljaËinu stavi u svoj.
{80435}{80490}Hajde! Smirite se!
{80539}{80610}Ne treba ti to. Zato smo i doöli ovamo.
{80666}{80721}lmamo poruku|za vaöeg malog limenog boga.
{80724}{80753}Limeni bog?!
{80837}{80873}Baö smeöno!
{80876}{80952}U policiji Santa Monice bio sam 22 godine.
{80959}{81040}l znam öta se dogaa|kad face poput vas preuzmu vlast.
{81042}{81107}U Vegasu nemamo nijednog ovisnika.
{81122}{81174}Moûete li se vi time pohvaliti?
{81213}{81281}G. Dorgan, Ëak i Ëovek|vaöe ograniËene inteligencije...
{81283}{81337}moûe shvatiti da vas iskustvo...
{81340}{81396}s tuËenom decom i ovisnicima...
{81398}{81471}ne opravdava öto ste se priklonili Ëudoviötu!
{81524}{81571}Sjajno! lzvrsno!
{81573}{81655}Zasluûujete Kingovu nagradu|za policijsku brutalnost.
{81696}{81794}Joö malo pa su gotovi, Larry. OseÊaö li to?
{81842}{81869}OseÊam.
{81870}{81936}Zaboravi lisice.|Samo ih strpajte u aute! Brzo!
{81951}{81977}KreÊite!
{82195}{82267}OKRUéNl ZATVOR CLARK - LAS VEGAS
{82324}{82392}Savröen si, g. éoharu.
{82407}{82465}Mogli bismo uËiti od tebe.
{82481}{82543}Posebice u svetlu proteklih dogaaja.
{82567}{82655}Ja Êu biti mrtav...
{82669}{82718}do sutra...
{82753}{82817}a ti Êeö i dalje glavinjati.
{82841}{82891}Obavljati svoje ûoharske poslove.
{83023}{83069}Glavinjavi je ûohar zaglavio.
{83273}{83310}Randall Flagg!
{83355}{83419}Nisi ni upola krampus kakva oËekujemo.
{83483}{83588}Upoznaj se s mojim suradnikom,|g. Lloydom Henreidom.
{83590}{83662}Lloyde, ovo je g. Glen Bateman.
{83668}{83706}Drago mi je.
{83708}{83782}Kako artritis, Glene? Smijem te zvati Glen?
{83805}{83844}Doima se bolnim.
{83939}{83993}Mogao bih to srediti. éeliö li to?
{83995}{84084}Ne bi bilo viöe nateklina, do kraja ûivota.
{84086}{84155}Moraö me samo zamoliti.|- Kakva pogodba!
{84170}{84258}Samo me zamoli da te oslobodim te boli.
{84527}{84573}Zapravo i nije tako straöno.
{84614}{84691}A öto se tiËe ostatka ûivota, koliko je to?
{84693}{84726}äest? Dvanaest sati?
{84765}{84845}Zapravo sam te odluËio pustiti.
{84884}{84913}Doista?
{84963}{84994}Divno!
{85031}{85093}Dakako, ne mogu otiÊi bez svojih prijatelja.
{85095}{85161}Dakako! Svi Êete otiÊi...
{85163}{85229}sutra ujutro. Moûe i noÊas.
{85293}{85354}Ali, jedino öto treba jest da me zamoliö.
{85362}{85442}Ali za tako golemu uslugu...
{85485}{85561}ipak bi trebao kleknuti.
{85824}{85852}Prestani!
{85894}{85946}Prestani mi se smejati!
{85961}{86054}Mislili smo da si opasan...
{86059}{86140}a ti si samo joö jedan ûohar!
{86142}{86226}Koji glavinja okolo|u svojim ûoharskim övrljanjima.
{86340}{86371}Ubij ga!
{86417}{86459}äto?!|- »uo si me.
{86584}{86639}Pucaj, idiote!!
{86652}{86689}Starac je.
{86745}{86841}Ne moûeö niöta obaviti kako treba?!|Pa pred nosom ti je!!
{86843}{86900}Ako vam se ubija...
{86902}{86937}bolje da ustrijelite Flagga.
{86939}{87000}Njegov se svet raspada, obojica to znamo.
{87002}{87101}Obojica znamo i to|da on pri padu moûe uËiniti puno ötete.
{87116}{87160}Mogli biste to promeniti.
{87177}{87224}Ubij jednoga od nas.
{87241}{87311}Ja sam te izbavio iz zatvora|da ne umreö od gladi.
{87313}{87362}A ljudi poput njega su te strpali u zatvor.
{87364}{87427}l oslobodili super gripu.
{87431}{87469}Samo izaberi, Lloyde.
{87472}{87561}On laûe, g. Henreid. No vi to dobro znate.
{87666}{87757}Rekao mi je viöe istine|nego itko u mom bijednom ûivotu.
{88084}{88138}Sve je u redu, g. Henreid.
{88185}{88228}l ne znate za bolje.
{88230}{88286}Zaveûi, brbljavi stari gade!!
{88627}{88673}Mislim da su upravo...
{88697}{88730}Jesu.
{88896}{88970}¥¥OËe naö, koji jesi na nebesima...
{89011}{89049}¥¥Sveti se ime tvoje!
{89089}{89177}¥¥Doi kraljevstvo tvoje,
{89555}{89607}¥¥Pogledam, a ono konj sivac!
{89617}{89682}¥¥A na njemu jahaË Smrt.¥¥
{89707}{89769}Moraö videti öto slijedi, Stuarte!
{89774}{89886}l prenijeti svima vesti|koje se nikad neÊe zaboraviti.
{89925}{89951}Probudi se!!
{89959}{89980}Probudi se!
{89982}{90017}Blijedi konj, Blijedi jahaË
{90019}{90072}Ne mogu, Majko!
{90150}{90198}Probudi se!|- Ne mogu...
{90406}{90448}Moram se popeti!
{91157}{91216}Moram gore!
{91868}{91950}Stu! Evo ruke!
{92074}{92117}Uhvati me za ruku!
{92189}{92216}Tommy?!
{92419}{92448}Moja noga.
{92783}{92824}Tommy, kako... Zaöto...
{92826}{92933}Bio sam istaËno odavde|i Nick mi je rekao da se vratim.
{92941}{92946}U mojim snovima on moûe govoriti.|Nije li to sjajno?
{92946}{93022}U mojim snovima on moûe govoriti.|Nije li to sjajno?
{93085}{93165}Jest, Tommy.
{93258}{93342}Bolestan si? Kaöljeö kao da si bolestan.
{93397}{93438}To je gripa, Tommy.
{93493}{93527}Nije li to grozno?
{93536}{93616}Moram te negde skloniti.|- Ne joö.
{93635}{93670}Zaöto ne?
{93713}{93751}Ne znam...
{93798}{93873}ali uskoro Êemo doznati.
{93953}{94003}Moramo samo Ëekati ovde.
{94450}{94505}Zaöto ste morali ubiti Glena?
{94514}{94555}Pookusio je pobeÊi.
{94625}{94658}Znaö...
{94670}{94758}jednog od ovih dana|i tebe Êe ustrijeliti u begu.
{94779}{94809}l tebe, ätakoraöu!
{94812}{94896}Da, na svetu Êe biti jedan ätakoraö manje!
{94898}{94947}ZaËepi tu seljaËku njuöku!
{94965}{95003}Ne budi glup!
{95067}{95166}äta je to?|- VideÊeö. Vrlo brzo.
{96017}{96044}Ubij!
{96164}{96199}Hajde!
{96307}{96346}lzlazi, gotovi ste.
{96443}{96484}Disko-glazba je mrtva!!
{96519}{96553}Ubijte ih!
{96555}{96615}Zaustavite ih.|- To samo Flagg moûe.
{96617}{96679}Ako se ne pojavi, rulja Êe ih ubiti!
{96682}{96747}Sviraj nam malo, putujuÊi glazbeniËe!
{96750}{96833}lonako Êeö na put, garantujem!
{96836}{96867}MiËite se!
{96902}{96964}Odmaknite se, do avola.
{96971}{97001}MiËi se s puta.
{97003}{97083}Pribliûe li nam se, raznesi koju glavu.
{97194}{97246}Hej, baö si slavan!
{97270}{97312}Sad sam i ja slavna!
{97463}{97508}Budi hrabar!|- Pokuöavam.
{97569}{97620}Dobro ih zaveûite!
{97638}{97691}Kad bih bar mogao razmiöljati o majci.
{97693}{97732}Stavi mu lisiËine!
{97806}{97849}Misliö da me to plaöi?
{97850}{97914}Metak u glavu sad bi mi dobro doöao.
{97916}{98011}Nemoj si oteûavati stvar.|- Misliö li da je to moguÊe?
{98024}{98055}Reci mi, öefe.
{98058}{98127}Jesu li te tako uËili|u policiji u Santa Monici?
{98386}{98481}GOLDEN GATE - KASlNO - HOTEL
{99468}{99553}U oËima Boûjim ti si niko i niöta!
{99558}{99601}¥¥NeÊu se bojati zla.¥¥
{99684}{99760}Sluöajte me, svi vi!
{99783}{99842}Ne oËekujem da Êete ovo spreËiti...
{99854}{99930}ali dobro upamtite öto ste veËeras videli.
{99951}{100038}lduÊi put Êe moûda na vas doÊi red|da ovako umrete!
{100116}{100162}Jeste li gotovi, g. Underwood?
{100170}{100219}Ti si gotov!
{100231}{100281}Shvatit Êu to kao potvrdan odgovor.
{100441}{100522}¥¥Ja, Randall Flagg... ¥¥
{100524}{100588}Reci im svoje pravo ime!
{100629}{100729}¥¥...ustvrujem da su pobunjenici...
{100732}{100839}¥¥odgovorni za uniötenje naöih izvidniËkih|zrakoplova u bazi lndian Springs.
{100841}{100901}¥¥l za smrt Carla Hougha.
{100903}{101019}¥¥Za te su zloËine|osueni na smrt raöËereËenjem.
{101361}{101438}¥¥Duûnost vam je svima da budete svedoci. ¥¥
{101462}{101549}No oni s malom decom mogu otiÊi.
{101552}{101588}PoËni, Barry.
{101817}{101902}Hej, ljudi!|Zar se ovako ponaöaju pravi Amerikanci?!
{101928}{101970}Moramo to spreËiti!
{102102}{102132}Whitney.
{102234}{102322}Trebao si öuteti, pustio bih te da odeö.
{102362}{102452}äto Êe mi ljigavac poput tebe?
{102769}{102871}Ovo daje sasvim novo znaËenje frazi.:|¥¥usta su mi zapeËaÊena. ¥¥
{103087}{103126}Vatra za tebe!
{103140}{103193}Veliki bum za tebe!
{103299}{103347}Velika je za tebe!
{103815}{103895}Boûe, pa to je bomba!!|lma atomsku bombu!!
{104122}{104153}Makni ga odavde!
{104156}{104250}Za tebe sam je doneo! Za tebe!
{104271}{104316}Makni ga odavde!
{104388}{104457}Moj ûivot za tebe!
{104688}{104717}Smetlaru?
{104768}{104806}Jesi li to ti, Lloyde?
{104855}{104899}Ne vidim dobro.
{104912}{104988}OËi su mi nekako Ëudne.
{105023}{105081}Ja sam. äto to imaö?
{105099}{105183}Veliku vatru!
{105229}{105273}Atomsku bombu!
{105385}{105460}Vatru za tebe!
{105483}{105574}Sluöaj, Smetlaru.|Moraö to odneti, opasno je.
{105700}{105769}Vratite se!! Vratite se, kukavice!
{105840}{105865}Ubij ga, Lloyde!
{105868}{105906}Ubij ludoga gada!
{106360}{106471}ObeÊanje je odrûano po Boûjoj volji. Amen.
{106548}{106576}Larry...
{106612}{106647}vidiö li?!
{106706}{106744}Boûja ruka!
{106753}{106791}Skloni se! Moj ûivot za tebe!
{106794}{106839}Vatra.
{107017}{107051}Milosti Boûija.
{107193}{107277}Dobro ste uËinili, momci. Vratite se doma.
{107312}{107346}Odvedi nas doma.
{107756}{107800}¥¥Vidjeh siva konja...
{107829}{107879}¥¥a na njemu bled jahaË.
{107919}{107988}¥¥lme konja beöe Kuga.
{108021}{108103}¥¥lme jahaËa Smrt.¥¥
{108209}{108247}äta je to bilo, Stu?
{108357}{108407}To je kraj Las Vegasa!
{108472}{108525}l kraj Randalla Flagga...
{108565}{108601}ako je Bog dobar.
{108668}{108717}A öto je s Glenom i Larryem?
{108745}{108784}A s Ralphom?
{109298}{109374}AX, UTAH - 23. rujna
{109382}{109434}Jesi li spreman, Tome?|- Jesam.
{109642}{109726}Molim te, Boûe. Samo malo pomozi.
{109768}{109816}Pokuöajmo!
{109956}{110010}UskaËi!
{110165}{110202}KreÊemo!
{110315}{110409}HoÊe li biti sve u redu, Stu?
{110412}{110499}Mislim da hoÊe.|Mislim da nas odsad sreÊa prati.
{110901}{110982}Koliba Green River
{110992}{111087}Od ovog Êe ti biti bolje.|Maslac od kikirikija i ûele.
{111089}{111158}To se piöe M-J-E-S-E-C.
{111172}{111249}Mama mi je to davala kad sam bio bolestan.
{111253}{111295}Oporavio bih se.
{111358}{111416}Moraö jesti, Stu!
{111523}{111591}Umrijet Êeö ako neÊeö jesti.
{111622}{111665}A onda Êu ostati sam.
{111696}{111745}Moraö jesti, zbog mene!
{112728}{112792}Molim te, Stu. Nemoj umreti, molim te.
{112952}{112980}Tome!
{113025}{113066}Jesi li to zaista ti?!
{113315}{113359}Stu je rekao da si mrtav.
{113377}{113426}Stu je jako bolestan.
{113436}{113489}Znam, ima gripu.
{113536}{113607}Pookusio sam ga nahraniti kao mama mene.
{113608}{113692}Ali neÊe jesti. Jako se bojim, Nick.
{113715}{113773}Sve je u redu. Znam öto mu treba.
{114120}{114153}Hajde, Tome.
{114371}{114437}Od ovog Êeö ozdraviti!
{114653}{114719}Kako si znao da mi to trebaö dati?
{114722}{114756}Nick mi je rekao.
{114798}{114882}On moûe govoriti u mojim snovima.|Jesam li ti to rekao?
{114919}{114991}Mislim da jesi.
{115581}{115650}2. novembar
{116863}{116905}äta ti je, Tommy?
{116961}{117036}Viöe se ne mogu setiti kako izgleda Nick.
{117065}{117124}A bio mi je najbolji prijatelj.
{117162}{117198}Dao mi je bicikl...
{117216}{117263}uvek je bio dobar prema meni.
{117275}{117328}A ja se ne mogu setiti.
{117357}{117445}Tako sam glup! NiËeg se ne seÊam.
{117497}{117575}lma mnogo vaûnih stvari koje nisi zaboravio.
{117587}{117626}Ja sam joö ûiv...
{117651}{117709}a ne bih bio da nije bilo tebe.
{117763}{117853}HoÊemo li stvarno iÊi doma,|kao Dorothy u »arobnjaku iz Oza?
{117896}{117948}Dakako, idemo doma.
{119012}{119089}SLOBODNA ZONA BOULDER - 15. studenog
{119102}{119200}Ovo je ludo, znaö!|Ove zime viöe niko neÊe doÊi.
{119220}{119302}Rano je, ali zima je poËela.
{119587}{119624}Budi oprezan.
{119628}{119712}Moûe biti Stu, ali i...|- Bilo tko!!
{119755}{119795}Ko ste?!
{119811}{119876}lzjasnite se ili pucamo!
{120068}{120119}To su oni!!
{120202}{120235}Stu!|- Hej, Teddy!
{120256}{120289}l Tom Cullen!
{120292}{120378}Ne mogu verovati! äta ti je s nogom?
{120381}{120474}Slomljena je. No nije vaûno.|Smrznuti smo, idemo u auto.
{120476}{120550}Odmah me vodite doma da vidim Frannie!
{120609}{120659}äta je?
{120705}{120740}äto nije u redu?
{120778}{120810}äta je?
{120819}{120896}Ne znam kako da ti kaûem...
{120928}{121036}Reci, öto je?!|- Dijete.
{121109}{121174}Ranije se rodilo. l ima gripu.
{121511}{121541}Fran?
{121730}{121752}Stuarte?
{121804}{121844}Je li ovo san?
{121892}{121940}Nije, duöo. Nije san.
{122352}{122392}Ne mogu verovati!
{122603}{122670}Sada samo Ëekam da sve ovo zavröi.
{122692}{122782}Pa onda moûemo razmiöljati|o novom poËetku.
{122807}{122861}Dûordû kaûe da se ne zna...
{122863}{122929}hoÊe li i deca biti imuna.
{122941}{123027}Nemojmo sada o tome razmiöljati, Frannie.|- Ne mogu drukËije.
{123037}{123117}U utrobi mi je velika, crna rupa.
{123125}{123216}Stalno se pitam zaöto smo sve ovo uËinili.|»emu?
{123272}{123340}U oËima Boûjim si niko i niöta.
{123674}{123769}Bar smo nas dvoje ostali zajedno, znaö.|- Znam.
{123826}{123922}Stu, ne mogu ti reÊi koliko sam sreÊan|öto te vidim! Kako smo svi sreÊni!
{123924}{124002}Dijete je umrlo, zar ne?
{124004}{124098}Nije, naprotiv. Mislim da je proöla kriza.
{124144}{124178}HoÊete reÊi...
{124203}{124240}da Êe ona biti dobro?
{124242}{124306}Da, mislim da Êe dete poûiveti.
{124860}{124920}lME Abagail Goldsmith|MAJKA Fran Goldsmith
{124922}{124968}Bila je to teöka bitka.
{124971}{125055}Mnoga od dece iz Godine Prve|neÊe biti tako dobro kao ona.
{125076}{125136}No ako je oboje roditelja imuno...
{125159}{125220}nestaÊe i te kuge.
{125267}{125302}To je pravo Ëudo!
{125322}{125355}Jest.
{125386}{125478}lmaö prekrasnu kÊer, Fran.|Dobro se brini za nju.
{125480}{125559}HoÊu. Oboje Êemo.
{125667}{125691}∆ao.
{125694}{125748}Moûemo se i posle vratiti.|- Ne.
{125795}{125832}äepaö.
{125849}{125907}A Ëujem da si i ti trudna.|- Jesam.
{126127}{126220}Lucy, Larry je...
{126221}{126291}Znam. Znam öta se dogodilo.
{126371}{126465}Sigurna sam da kad je doöao kraj...
{126528}{126571}doËekali su ga na nogama.
{126574}{126663}Zato su i poslani. Da zauzmu stav.
{126708}{126746}Mislim da je tako.
{126784}{126819}Njega viöe nema...
{126841}{126882}ali nosim njegovo dete...
{126899}{127015}Moûda to nije sve öto sam ûelela|i o Ëemu sam sanjala.
{127051}{127103}No moraÊe biti dovoljno.
{127607}{127679}Ne plaËi, biÊe ona dobro.
{127701}{127746}Tako je lepa!
{127764}{127813}Ne plaËem zbog nje...
{127838}{127929}nego zbog svih ovih praznih kolijevki.
{127986}{128016}Ku-kuc, beba!
{128127}{128195}Znam, duöo. Svi gledamo bebicu.
{128216}{128260}Nisi li prekrasna?
{128290}{128379}Lepa si poput zore u rajskom vrtu.
{129162}{129232}Fran? Misliö li da se ljudi|zaista mogu promeniti?
{129292}{129344}Misliö li da je to moguÊe?
{129411}{129450}Ne znam.
{129463}{129524}Stvarno ne znam.
{129582}{129680}Mislim da ona moûe sve.
{129832}{130082}Prevod KOSTA ZULU LESKOVAC
{130107}{131607}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/58hmz|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
