{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{1130}{1230}U D R I   D O   K O S T I
{3077}{3172}Dobro jutro,|Las Vegase. 5:58 ujutro.
{3173}{3247}BiÊe pakleno danas,|84 stepeni u zoru.
{3249}{3295}BiÊe 100 stepeni do meËa.
{3297}{3349}Za koga navijate veËeras u|Mendelej Beju?
{3351}{3416}Majk Tajson je napokon ponovo|u Vegasu.
{3418}{3500}5000 USD za mesta uz ring.
{3501}{3571}VeËeras Êe ovde biti vruÊe!
{3814}{3868}Jebiga! Fredi!
{3869}{3923}»oveËe! äta...
{3925}{3971}Fredi! Sranje, ËoveËe!
{4009}{4084}Ostavim te na sat vremena,
{4086}{4144}a ti sve upropastiö!
{4145}{4232}äta Êemo sad? 
{4233}{4293}Da, sranje.
{4354}{4408}Henku se ovo neÊe svideti
{4439}{4489}NeÊe mu se svideti.
{4491}{4560}Je li mrtav?|Nije?
{4561}{4649}Droga mu izlazi na uöi!|Ustondiran je sa dve kurve,
{4651}{4702}uopöte me i ne primeÊuje!
{4704}{4784}Ispustio si ga iz vida!|- Samo na minut, kunem se.
{4785}{4859}Propade mi uvodni meË.|- Znam. Znam.
{4861}{4932}Ko Êe se sad boriti protiv|»ikita Rosarija? - Ne znam.
{4934}{5018}To je Arumov borac.|- Ko pazi na njega?
{5020}{5056}Arum sigurno ima nekoga|da ga prati kao soko.
{5116}{5221}Kaûi mi öta imaö.|- Latinoamerikanac, srednjih dvadesetih godina.
{5222}{5269}Smrad alkohola.
{5297}{5345}Aurelio »ikito Rosario.
{5347}{5404}»ikito?|- Da. Znaö ga?
{5405}{5485}On je öampion u velter teökoj kategoriji.|VeËeras boksuje sa Fredi Grinom pre Tajsonove borbe.
{5486}{5575}Teöko! VeÊ su mu odbrojali do 10.
{6685}{6791}Dûoni.
{6793}{6842}Cezare.
{6998}{7079}Hej.|- Jesi li gledao sinoÊ seriju Sva moja deca?
{7081}{7176}Taj je nikad ne propuöta.|- Dûoni.
{7177}{7272}Da li je kuËka ostavila doktora?|- Koja kuËka? Kog doktora?
{7274}{7330}Ona mala plava kurcolomka.
{7332}{7387}Znaö. Ona veËito namrgoena|- Da.
{7389}{7448}Ostavila ga je.|- Je li?
{7450}{7520}Zbrisala.
{7545}{7628}Kakav idiot.
{8117}{8171}Da.|Samo trenutak.
{8173}{8248}Momci, za vas.|Dûo Domino.
{8306}{8384}Molim?|- Dûo Domino!
{8529}{8636}Dûo Domino veÊ 5 godina ne razgovara sa mnom,|od Gardena.
{8637}{8693}Kad si zeznuo u Gardenu.|- Nosi se, nisam.
{8695}{8756}Svejedno, zovu Domino i Henk iz Vegasa.
{8758}{8805}U redu. Daj mi.|Halo ?
{8806}{8889}Momci, ovde Henk i Dûo.|S nama je i Arti. Znate, Dûoov momak.
{8890}{8947}Hej momci, ovde Arti.|Kako ste?
{8949}{8995}Nije loöe.|- Dobro...
{9049}{9160}Drago mi je. Govorim u ime Dûoa Domina|Imamo neöto za vas
{9162}{9245}Ovde Dûo, momci.|Jeste li se ikad borili na brzaka?
{9246}{9296}Koliko na brzaka?|- VeËeras u 6.
{9297}{9400}Trebaju mi dvojica. BiÊe dobra zabava.|Vi se nikad niste borili meusobno, zar ne?
{9401}{9461}Misliö za novac?|- Da. - Ne!
{9462}{9549}Iz zabave boga mu!|Gde mi je kapa?|- U ruci, gospodine.
{9551}{9614}Dûo, molim te, ne pominji uzalud ime boûje.
{9616}{9728}Iskreno se izvinjavam.|Pustimo sad veronauku.
{9730}{9845}DaÊu vam 100 somova,|ali smesta morate da se nacrtate ovde.
{9874}{9969}»ujete li me?|BoksovaÊete pre Tajsona.
{9971}{10047}GledaÊe vas u 109 zemalja.|- 110!
{10049}{10107}Stiûemo. 
{10109}{10156}Ne. Ne, ne, ne, ne.|Ne stiûemo. Sluöaj.
{10158}{10212}Pozovi nas za pet minuta.
{10213}{10295}Hej! äta to radiö?
{10297}{10351}Ko su ti fosili?
{10353}{10402}äta je s tobom?|50 somova.
{10404}{10476}50 somova. Kad su ti toliko nudili?
{10478}{10538}Nije to niöta. Nije to niöta.|Moûemo da izvuËemo viöe.
{10540}{10586}Znam ja njih.|- Ma daj, ËoveËe!
{10588}{10634}Ne bi nas zvali da im nismo potrebni.
{10636}{10695}Vinsa ne traûe tri godine!
{10697}{10795}A Cezara od Gardena,|gde me je zeznuo!
{10797}{10877}Misle da su joö uvek imena.|Nisu!
{10879}{10956}Mi smo za njih imena potrebna za predigru.
{10958}{11028}Molim...Mi smo imena za sebe.|Ne za njih.
{11029}{11105}Ne, ne, sluöaj. Odgovori mi ovo.|Zaöto si nabacio 74 kilograma?
{11107}{11172}HoÊu opet priliku za titulu.|U srednjoj imam viöe izgleda.
{11173}{11238}Da. Nema nas toliko u kategoriji.|Zato sam ja smröao.
{11240}{11309}Pa, pa.|- Tri kilograma. Ok. Pa...
{11311}{11441}Da.- Dakle, ovo je prilika! Telefonski poziv.|Drûimo ih za "cajolles".
{11442}{11516}Kaûe se "cajones" (jaja).|- Cajones. Da. Svejedno.Sluöaj, sluöaj.
{11517}{11621}Boks nije samo borba.|To je i biznis. Zato gledaj i uËi.
{11623}{11669}Jel tako?|- Moraö...
{11671}{11765}Da.
{11767}{11844}Momci, opet Arti.|Govorite na spikerfon.
{11845}{11931}Sluöajte, hoÊemo viöe love.|- NaÊi Êu dve crkotine.
{11933}{12006}Arti, pokupi nekog s ulice.|- Ne, ne, ne, ne. U redu je.
{12008}{12088}U redu je. Henk, prihvatamo ponudu.
{12089}{12135}Ne. Nije u redu.|-Ne, ne, ima joö neöto.
{12137}{12186}Ovde Henk, momci.|äta ûelite?
{12262}{12343}Da, Henk. Zdravo. Sluöaj.|HoÊemo 100 somova za svakoga.
{12345}{12388}25 hiljada za svakoga.
{12390}{12483}Ne, ne, ne. éelimo 100 hiljada|i neÊemo popustiti.
{12485}{12565}25 hiljada.|To je moja poslednja ponuda.
{12567}{12626}25 je tvoja poslednja ponuda?|Kako 25? Sad si rekao...
{12628}{12731}25, 25. |- Dobro. Moûe 50.
{12733}{12787}Dogovoreno.|äta joö?
{12789}{12905}U redu. éelimo putovanje u Svetu Zemlju|za dvoje. Dobro, za jedno.
{12906}{12987}I donaciju Majci Terezi.
{13060}{13106}Nosi se!
{13108}{13193}Zaboravi na celu stvar!|Dogovor otpada!
{13195}{13272}Nije ni trebalo da vas zovem!
{13274}{13369}Zaboga, Dûo.|Sve si ispljuvao.
{13370}{13421}Ok, ok. Sluöaj.|Treba nam samo jedno.
{13423}{13556}A to je... OK.|Garantovan izazov za prvaka u srednjoj kategoriji,
{13558}{13615}onome ko od nas dvojice pobedi.
{13617}{13668}Reci im, nek se teraju.|- SaËekajte.
{13669}{13764}IskljuËi spikerfon.|- SaËekajte trenutak, momci. JaviÊemo se.
{13766}{13878}ZaplakaÊu.|Kako moûeö sve tako brzo da uprskaö?
{13880}{13940}Mislim, kako je to moguÊe? Kako je moguÊe?|- Hej, opusti se?
{13942}{13989}To je umetnost pregovaranja.
{13990}{14037}Umetnost.|- Strpljenje.
{14038}{14126}äta fali?|Ionako Êe popuniti sat vremena.
{14128}{14203}Samo da Cezar ne ponovi Garden.
{14205}{14287}Vins nikad nije bio zaustavljen.|Pobednikom Êemo nahraniti prvaka u srednjoj.
{14289}{14335}PojeöÊe ga za doruËak.
{14337}{14413}MoraÊemo da ih stavimo na listu izazivaËa,
{14415}{14461}ali to neÊe biti problem.
{14463}{14547}Za Rosarija i Grina Ëuvali smo 750,000.
{14549}{14607}Uötedeli smo gomilu love.
{14609}{14697}Doavola, mogao bih i Dûuli da stavim na listu.
{14699}{14785}VeÊ je na mojoj listi.
{14787}{14875}Hvala.|- UkljuËi veÊ jednom.
{14877}{14952}Vinse, Cezare, tu ste?|- Da. Tu smo.
{14954}{15039}Pametni ste vi.|Takve volim. Dogovoreno.
{15041}{15087}äta kaûe?|- Moûe.
{15089}{15151}Moûe? To! To!|- Da! Da!
{15153}{15251}OK, OK, sluöaj. U ugovoru mora da piöe|"zagarantovan izazov titule".
{15253}{15299}U ugovoru.|- Da.
{15301}{15398}I to razumljivo. Ne volimo|ona pravniËka sranja, u redu?
{15400}{15494}I prevod na öpanski iz tehniËkih razloga.
{15496}{15568}Da. I Dûo, ne zezaj se s nama.|OK? Biblija kaûe,
{15570}{15643}"Zao strada od sopstvene zlobe."|Izreka 11:5. OK?
{15645}{15704}Ugovor Êe biti jasan.
{15705}{15769}Samo doite na aerodrom|i pokupiÊemo vas.
{15771}{15829}BiÊe sjajno, momci.|Sjajno.
{16301}{16375}Grejs! HoÊeö u Vegas?
{16521}{16568}Hej.|- Vegas?
{16569}{16625}Da.|- Oboûavam Vegas. Zaöto?
{16627}{16702}VeËeras je veliki meË.|- Znam. Imaö ulaznice?
{16704}{16788}Zapravo, ne trebaju mi ulaznice|zato öto se borim ja.
{16790}{16840}Kako da ne.|Protiv koga?
{16842}{16889}Protiv njega.
{16935}{17001}Protiv Vinsa?|- Zabavno, zar ne? IspraöiÊu ga.
{17089}{17137}U Vegasu?|- U Vegasu.
{17139}{17198}VeËeras?|- VeËeras, tako je.
{17200}{17285}I hoÊeö da poem sa tobom.|- Naravno da hoÊu.
{17287}{17410}Trebaö mi. Tvoje oËi.|Tvoja koûa. Tvoja kosa.
{17412}{17484}I moja kola. - I tvoja kola. 
{17485}{17545}HoÊu da kaûem, trebaju nama.
{17546}{17609}Da.
{18030}{18128}Vegas je pun novca za ulaganje.
{18130}{18220}PotraûiÊu momke koji su spremni|da me podrûe.
{18222}{18284}Joö skupljaö za onaj glupi izum?
{18286}{18361}Imam 6 patenata i joö 6 koji Ëekaju.
{18363}{18458}Lovom od jednog, da te podsetim,|kupila sam stambenu zgradu.
{18460}{18521}Hvala ti öto nas voziö u Vegas.|Hvala ti duöo.
{18523}{18627}Nema problema. Vegas je grad|sa najbrûim rastom u Americi, 
{18629}{18675}a ja umem sa ljudima
{18677}{18773}Kako to onda ne umeö da zadrûiö muökarca?
{18775}{18862}Duöo, muökarci ne umeju da zadrûe mene.
{18864}{18930}Ja umem, srce.
{18970}{19021}VideÊemo.
{19023}{19096}Znate, mislim da Êe ovaj put|biti dobra prilika za mene...
{19097}{19145}da isprobam svoj novi sistem na ruletu.
{19146}{19205}To ti baö nije pametno.
{19207}{19277}Jeste. Imaö crno i crveno.
{19278}{19328}Izgledi su pola-pola.
{19330}{19383}I ako...
{19385}{19431}Kuda... Kuda to idemo?
{19433}{19511}Geologija je ovde lepöa.|Vide se brazde na planinama...
{19513}{19564}Jebeö brazde!
{19565}{19642}Moramo u Vegas!|- äta si to govorio ...
{19644}{19694}o ruletu, objasni?|- Oh, da, da.
{19696}{19773}Imaö crveno i crno.|Izgledi da udvostruËiö su pola-pola.
{19858}{19905}I budala moûe da dobije.
{19906}{19937}S naglaskom na budala.
{20005}{20097}Grejs, hoÊeö li da ponoviö,|zaöto idemo ovim putem?
{20099}{20153}Zbog brazda.|- Brazde.
{20155}{20235}Brazde.|Gospode.
{20285}{20384}Gospode, spomenuo sam tvoje ime uzalud.
{20386}{20434}Zajebao sam...|Uprskao!.
{20436}{20512}NeÊe se ponoviti|Amin.
{20513}{20576}Dobra fora.
{20578}{20661}Krenuli su prokletim kolima?
{20663}{20733}OËigledno.
{20734}{20829}Vins je jednom imao 14 sudara|za 14 meseci.
{20830}{20909}Idu Grejsinim kolima.
{20911}{20973}Vinsu su oduzeli dozvolu.
{20975}{21054}Grejs! Grejs. Nije valjda Grejs PaöiÊ.
{21056}{21119}Da!|- Joö je sa Vinsom? »udesno.
{21121}{21186}Ne, zapravo, sad je sa Cezarom.|- Nek sam proklet!
{21188}{21258}Ta mala se uvek palila na srednjeteökaöe.
{21260}{21381}Hej, Bobi, Sale.|Sastavite standardne ugovore.
{21709}{21778}Cezare, moramo da razgovaramo.
{21780}{21888}Nikuda ne idem. Reci.
{21922}{21995}Mislim da je gotovo.|- äta?
{21997}{22058}Gotovo, meu nama.
{22084}{22172}Hej duöo, kako to misliö?
{22174}{22236}Priznajmo. Bila je to kratka strast.
{22238}{22324}Niöta viöe.|- Ne i za mene.
{22326}{22421}Moglo je da preraste u neöto viöe, ali nije.
{22422}{22488}Sranje.|Upravo smo poËinjali.
{22490}{22543}Ne. Upravo smo zavröavali.
{22619}{22671}Zar se ja niöta ne pitam?
{22673}{22731}Ne.
{22790}{22903}Srce, volim te.|Ti si za mene jedina.
{22905}{22971}Ti si jedna i jedina.
{22973}{23023}Samo bez puzanja.
{23025}{23107}Ovo je konaËno?|- Nikad niöta nije konaËno.
{23109}{23182}Rekla sam da tako mislim,|nisam rekla da tako oseÊam,
{23184}{23268}öto bi za tebe bilo gore.|- Mnogo gore.
{23269}{23372}Ali kad misliö i oseÊanja se uskovitlaju,|moraö pripaziti.
{23374}{23439}Znaö? Sem toga...
{23441}{23500}Ti me i ne voliö.
{23543}{23637}Ali sam poËinjao. Korak po korak, malo po malo.
{23639}{23714}Duöo, prekasno je.
{24564}{24628}Cezare?
{24742}{24796}Zaustavi.
{25665}{25728}Zar sam neöto rekla?
{25730}{25777}Ne, ne.|Nema to veze sa tobom.
{25779}{25833}Uvek plaËe na dan borbe.
{26711}{26757}Dobro je on.
{27006}{27070}äta je to bilo s njim u Gardenu?
{27097}{27144}Neka ti on kaûe.
{27145}{27208}Ali sumnjam da o tome ûeli da priËa.
{27645}{27701}Ne znam hoÊu li moÊi da se borim s njim.
{27702}{27792}UkoËiÊu se.|UblaûiÊu udarce. Znaö?
{27793}{27853}Bliski smo.
{27854}{27939}A u ringu nije niöta gore od samilosti.
{27941}{28018}Vinse, samo treba da Ëujeö gong.
{28020}{28088}Nekako je... Neprirodno.
{28911}{28957}Idemo.
{28997}{29043}Hajde.
{29298}{29382}SaËinili smo ugovore za Budroa i Domingeza.
{29384}{29430}Proveri ih.
{29432}{29542}Stvarno Êeö jednom od tih propalica|omoguÊiti izazov?
{29544}{29603}ObeÊao sam,|ako to uopöte neöto znaËi.
{29605}{29700}IsfoliraÊemo ih!|NapraviÊemo duple ugovore.
{29702}{29788}Jedan Êemo tako da sastavimo|da lako moûemo da se izvuËemo.
{29790}{29885}I drugi Êe biti sliËan,|ali ne tako oËigledan.
{29887}{29948}Ako odbace jedan, prihvatiÊe drugi.
{29950}{29992}I svi su sreÊni.|- Dobro.
{29994}{30071}Henk, nai svojim slavnim bokserima...
{30073}{30127}advokata.
{30129}{30204}Dante, jel tvoja dozvola joö vaûeÊa?
{30206}{30312}Nedavno mi je vraÊena.|- Dobro.
{30313}{30399}Od sada zastupaö Budroa i Domingeza.
{30426}{30486}A moj honorar?
{30635}{30715}NeÊemo te prijaviti komori za nagovaranje porotnika,
{30717}{30804}iznuivanje, podmiÊivanje senatora, 
{30806}{30866}seksualno zlostavljanje, proneveru...
{30868}{30957}Poöteno, poöteno.|- To je dobar dogovor.
{30959}{31047}Vrlo rado Êu zastupati tu finu mladu gospodu.
{31306}{31360}Kad je poËelo to s Isusom?
{31386}{31448}Vaspitan sam da budem religiozan.
{31450}{31540}Veronauka, biblija, oseÊaj krivice i sve to.
{31542}{31651}Ali brzo sam shvatio da crkva,|pogreöno prikazuje Isusa,
{31653}{31734}koji je rekao "Ne sudite...
{31736}{31782}a oni su sudili svakome".
{31784}{31915}»im sam shvatio da je u pitanju gomila licemera,
{31917}{32003}usredsredio sam se na zabavu.
{32005}{32056}Znaö, ûurke, zabave, 
{32058}{32133}imao sam nekoliko devojaka, nekoliko sudara.
{32135}{32197}Nekoliko?|- Pa, nekoliko desetina.
{32199}{32309}Bio sam razuzdan.|Onda sam sreo tebe.
{32311}{32367}Da.
{32369}{32420}Dobro smo se proveli, zar ne?
{32422}{32469}PopriliËno smo ludovali.
{32500}{32560}Da. Kad si me ostavila, 
{32561}{32627}zabio sam se u drvo, 120 na sat.
{32629}{32708}Bio sam naroljan i seÊam se samo|da sam leûao na leima...
{32710}{32773}u lokvi krvi i benzina...
{32775}{32853}na glavi mi auto.
{32855}{32952}Pomislih, gotov sam.|A onda podignem pogled i koga vidim?
{32989}{33065}Isusa. A on je nepogreöiv, zar ne?
{33067}{33154}Gleda u mene i smeöi se!
{33156}{33220}Kao, sve je u redu.
{33221}{33308}Onda mi je skinuo auto s glave.
{33310}{33367}Da.
{33369}{33460}Ugledam ga s vremena na vreme.
{33461}{33508}Kako izgleda?
{33509}{33602}Kao na slikama.|Ista stvar.
{33604}{33681}Ako ga opet ugledaö,|hoÊeö li mi ga pokazati?
{33683}{33752}Naravno.
{33753}{33848}Ti verujeö u tu borbu|izmeu dobra i zla.
{33849}{33901}Ponekad.
{33903}{33961}A ponekad nisam raspoloûena.
{33962}{34081}Ponekad ûelim toplu kupku,|Ëist bade mantil,
{34082}{34179}Ëaöu vina i da me svi|ostave na miru.
{34208}{34268}Volim crkvenu muziku.|- Crkvenu muziku.
{34270}{34361}Previöe je dobra za crkvu|kao i Isus.
{34363}{34414}On je sve prodrmao.
{34416}{34481}Bio je anarhista.
{34483}{34536}Izbacio je zelenaöe iz hrama.
{34538}{34609}Kad se vrati prvo Êe spaliti Vatikan.
{34610}{34670}Ma daj! 
{34701}{34749}Svejedno.
{35165}{35225}Ponekad mi nedostajeö, Vins.
{35365}{35412}Ponekad i ti meni nedostajeö.
{35470}{35529}Znaö, umrla mi je mama.
{35531}{35592}Nisam znao.|éao mi je.
{35649}{35713}Bio si joj najdraûi od svih|mojih mladiÊa.
{35745}{35803}Ne i tebi.
{35805}{35884}Ja traûim neöto drugo.|Ne znam öta.
{35885}{35938}Pravog muökarca?
{35940}{35995}Pravu karijeru?
{35997}{36067}Prave okolnosti.|Ne znam.
{36069}{36121}Ali traûim neöto.
{36123}{36197}Moûda traûiö Isusa.
{36199}{36313}Ne, ne traûim Isusa.
{36378}{36425}Traûim novac.
{36650}{36711}Jedan! Dva!
{36713}{36794}Tri! »etiri! Pet!
{36796}{36842}äest! Sedam!
{37886}{37933}Narode.
{37975}{38113}ZakljuËio sam da sam|potpuno potcenjen kao bokser...
{38115}{38183}i kao ljudsko biÊe.
{38185}{38286}Volim te, ËoveËe.
{38288}{38353}Zaista. Volim sve Meksikance.
{38355}{38408}I ja, samo ja sam äpanac.
{38410}{38463}Govoriö MeksiËki, zar ne?
{38465}{38525}Ne, Meksikanci govore|öpanski iz äpanije.
{38527}{38573}Ti si iz Madrida?|- Da.
{38575}{38641}A Madrid je u Meksiku,|zar ne? Zar ne?
{38643}{38683}Svakako. Da.
{38685}{38763}Koliko znam,|Meksikanci su vam susedi,
{38765}{38855}ali Ëime äpanci zasluûuju|da budu u ovoj zemlji?
{38857}{38906}Mi smo je otkrili.
{38908}{38972}Ne nego Italijani.|- A ko je platio put?
{38974}{39021}Imaö li radnu dozvolu?|- Naravno da imam!
{39022}{39069}Da vidim.|- Zaöto... - Momci!
{39070}{39117}Momci, ajde o'ladite!
{39118}{39166}Hej!
{39168}{39221}Cezare.|- Da.
{39223}{39269}äta ti se to dogodilo|u Gardenu?
{39765}{39819}Grejs, ubiÊe nas sunce.
{39821}{39898}Molim te spusti krov.|- Pametno. Ne treba predugo biti na suncu.
{39900}{39958}äta to govorite o suncu?|Sunce je dobro.
{40079}{40166}OstaÊu u Vegasu joö par dana|da sklopim neke poslove.
{40168}{40214}Uzmite kola.
{40216}{40275}»uvaÊu ih kao svoja.
{40277}{40322}Cezar Êe da vozi.
{40324}{40376}äta Êeö u Las Vegasu sama?
{40377}{40449}Umem da brinem o sebi.
{40450}{40528}Zaglavilo se.|- Deöava se ponekad.
{40573}{40620}Samo neûno.|- Da, dobro.
{40621}{40668}Hej, hej, hej.|Nemoj rukama.
{40669}{40716}Treba da ih saËuvamo za veËeras.|- U redu.
{40717}{40776}Tako Êeö me i udarati laktom veËeras.
{40777}{40832}Hej, ja se ne borim prljavo.|U redu?
{40833}{40897}Nije nepoöteno udariti laktom iznutra.
{40899}{40994}Da znaö, kao öto sam ti i pokazao.|Roberto Duran je u tome bio najbolji.
{40996}{41042}Paûljivo.|Daj.
{41096}{41174}Silazi s boje!|To je "bezobrazno zelena"!
{41176}{41220}Moraö da mu tepaö.
{41249}{41297}»ekaj.|Hajde duöo.
{41299}{41402}Hajde mili, hajde mili.|Tako.
{41404}{41448}Dobar deËko.
{41507}{41559}Vidiö?.
{41561}{41650}»udna je prema meni,|niöta ne shvatam.
{41652}{41714}Navikni se.
{41716}{41768}Za tebe je to prednost,|moraö da priznaö.
{41770}{41820}Ma pusti to.|- Nemam vremena.
{41822}{41876}Jedina stvar koju moûeö da uradiö|je da bataliö.
{41878}{41934}To je sve öto moûeö.|- Imaö 6 godina
{41936}{42011}Pred tobom je velika noÊ.
{42013}{42067}Pusti to.
{42337}{42430}PriËaj mi o Gardenu.|- On to ne ûeli.
{42514}{42576}Ostavljaö me i joö traûiö|tako neöto.
{42578}{42668}Radoznala sam.|éelim da znam.
{42669}{42747}Dobro, nemoj da mi kaûeö.|Viöe te neÊu pitati.
{42749}{42840}U Evropi nije bilo dovoljno|ûestokih borbi.
{42874}{42933}U ringu skoro niöta.
{42934}{43011}Zato sam se iz Madrida|preselio u Filadelfiju.
{43013}{43118}Najbolji svetski bokseri su|iz Filadelfije.
{43120}{43172}Ako se bore dvojica koje ne znaö...
{43173}{43235}a jedan je iz Filadelfije,
{43237}{43283}kladi se na njega.|Zar nije tako?
{43285}{43391}To je istina.|- Imao sam 23 godine.
{43425}{43525}19 pobeda, bez poraza.|16 nokauta.
{43527}{43604}Imao sam najbolje menadûere,|iza mene Duvas.
{43659}{43709}Bio sam na naslovnoj strani "Ringa".|SeÊaö se?
{43740}{43806}Istina je.
{43808}{43878}I onda...
{43880}{43954}me je pozvala ta pizda Dûo Domino.
{43956}{44024}Jedan od najveÊih promotera.
{44025}{44124}ReËe da ostavim Duvasa|i preem kod njega,
{44126}{44221}i srediÊe mi izazov prvaka u Medison Skver Gardenu.
{44222}{44301}Njujork.|Zamisli öta to znaËi!
{44326}{44389}Znaö?|- U pravu si.
{44422}{44498}Duvas se uznemirio.
{44500}{44579}Rekoöe da mi treba joö|par godina iskustva.
{44581}{44668}Verovatno su bili u pravu, ali
{44669}{44759}ja sam raskinuo sa Duvasom|i preöao kod Domina.
{44838}{44915}Bio sam spreman.
{44955}{45013}U crvenom uglu,|izazivaË,
{45014}{45105}sa 19 pobeda i bez poraza,
{45107}{45156}16 nokauta,
{45157}{45250}iz Filadelfije,|preko Madrida u äpaniji,
{45252}{45364}Cezar "EI Kalifa "Domingez!
{45365}{45441}Domingez !
{45443}{45501}Momak u Gardenu,
{45503}{45549}kad ti izgovori ime,|onda ga i ponovi.
{45551}{45661}Kaûe, "Domingez.|Do-o-o-min-gez!"
{45663}{45705}O gospode.|- Domingez!
{45707}{45777}Bilo je kul Ëuti svoje ime|tako znaËajno,
{45778}{45880}pred tolikim ljudima.|Boûe, kako prija.
{45882}{45955}A prvak i nije izgledao|bogzna kako.
{45957}{46033}Roberto Velario!
{46065}{46119}A i nije me bilo briga.|Bio sam spreman.
{46121}{46171}Pobedio sam i opakije u Filadelfiji.
{46173}{46261}U redu, dotaknite se rukavicama.|SreÊno.
{46263}{46369}Cezare, sluöaj. Ovih 36 minuta|promeniÊe ti ceo ûivot.
{46370}{46438}Sluöaj me sad, ako veÊ nisi do sada.|Razumeö?
{46440}{46508}Da, da.- Spremili smo se za ovo.|Stariji je od tebe.
{46509}{46569}Nije tako mlad.|NeÊe izdrûati 12 rundi.
{46571}{46644}Ali razmiölja,|moûe da ti smesti.
{46646}{46693}NapaöÊe s par direkata
{46694}{46761}i zamahnuÊe desnom.|To je finta.
{46763}{46816}Nije opasno.|Opasan je levi kroöe.
{46818}{46892}Nikako nemoj da ustukneö|desno unazad, ni sekund.
{46893}{46946}InaËe, to je kraj.|Shvataö?
{46948}{47009}Idi sad i uzmi titulu!|- Da. Da. Idemo.
{47011}{47057}Hajde, hajde!
{47156}{47207}I tako, prvak izae, a ja...
{47209}{47289}poËnem da kruûim ulevo.
{47291}{47352}Moja leva noga ispred njegove desne.
{47354}{47432}I baö kako je tip rekao|on ispali direkt.
{47434}{47488}I niöta. Joö jedan.|Niöta.
{47490}{47573}I opet. Niöta.|A onda sevne desnica.
{47575}{47645}Izmaknem se.|A onda doe levi kroöe.
{47646}{47759}Baö kao öto je tip rekao.|Samo mi okrznuo rame. VetriÊ.
{47761}{47854}VetriÊ.- Da, luk i voda.|I ti bi mogla jaËe.
{47856}{47917}Zapravo i jesi.
{47919}{47965}Ne poËinji.
{47966}{48006}Amin.
{48008}{48062}Nastavim malo da kruûim.
{48064}{48124}Merkam ga
{48126}{48221}O Velariju treba neöto da znaö.
{48222}{48299}Ima milo lice.
{48301}{48352}Skoro da se smeöi dok boksuje.
{48354}{48448}Onda joö par direkata,|samo me oËeöu, niöta.
{48449}{48560}I prestanem da kruûim|moûda milioniti deliÊ sekunde.
{48562}{48649}A onda sevne desni direkt.
{48651}{48769}Ali momak uËini ovako|i povuËe se.
{48770}{48891}Izblefirani udarac desnicom,|baö kao öto mi je Ëovek rekao.
{48893}{48944}U tom trenutku ja razmiöljam.
{48945}{49026}Jer ponekad, u ringu
{49028}{49097}vreme naprosto stane|moûeö da razmiöljaö.
{49099}{49199}Sve vidiö usporeno
{49201}{49250}I vreme stane.
{49252}{49303}A ja razmiöljam,
{49305}{49408}"Ovaj je obiËan seronja."
{49501}{49570}Onda se setim öta mi je Ëovek|joö rekao.
{49605}{49646}Da je gotovo.
{49708}{49755}Gotovo, znaö?
{49893}{49940}Cezare, ustaj!
{49941}{50037}Ustaj, majku ti meksiËku!|Ustaj!
{50039}{50145}ZaËujem da odbrojavaju 5,|kleknem na jedno koleno,
{50147}{50235}mislim, zavröiÊu rundu,|ustaÊu na 8 ili 9.
{50237}{50283}I mislio sam da ustanem na 9.
{50285}{50352}äest! Sedam!|- Cezare, ustani, jebote!
{50354}{50432}Osam! Devet! Deset!
{50434}{50525}Gotovo.|- Govno jedno.
{50527}{50613}Dobro mi je. Dobro mi je. Hajde.|- Govno jedno.
{50615}{50702}MiËi ga odavde.|- Ali nisam.
{50728}{50779}Nisam dobro Ëuo.
{50781}{50861}Govnaru.
{50863}{50974}Nisam dobro Ëuo. A moraö|da ideö do kraja.
{50976}{51041}Do kosti.|- Da.
{51043}{51116}Da, udri do kosti.
{51118}{51168}Mislio sam da jesam.
{51169}{51272}A to je samo treptaj oka.
{51273}{51348}Podigneö pogled sa puta,|i eto sudara.
{51350}{51462}37 sekundi.|Toliko sam izdrûao.
{51464}{51552}Zavröio se tvoj meË,|ali ne i tvoj ûivot.
{51554}{51669}Ali mislili su da sam|mogao da izdrûim.
{51706}{51769}Da sam Ëekao do deset
{51771}{51864}kako bi izgledalo|kao da ûelim da ustanem.
{51865}{51968}Ali nisam mogao,|kunem se oËevim grobom
{51970}{52017}da nisam Ëuo odbrojavanje.
{52018}{52095}Nisam.|- Jebote.
{52331}{52443}Domino je svima rekao|da sam odustao.
{52445}{52493}Da nemam srca.
{52495}{52552}Domino je seronja.|- Da, ali je faca.
{52554}{52601}Da, faca je seronja.
{52626}{52685}Znaö öta?
{52687}{52733}Velario je bio peöko.|- Da?
{52735}{52813}O da! Muöko, ûensko, svejedno.
{52815}{52903}Pobedio me je peöko.
{52905}{52952}Mnogo ih je u boksu.
{52953}{53000}Nije!
{53001}{53053}Sigurno iznad proseka.
{53055}{53105}Dokaûi.
{53107}{53159}Dokaûi ti meni Isusa.
{53161}{53225}Dokazi samo ometaju instinkte!
{53227}{53298}äta to doavola priËaö?|- Nema veze.
{53300}{53409}Nakon öto me Velario nokautirao,
{53411}{53467}i ja sam malo bio peöko.
{53591}{53637}äta?
{53639}{53696}Ponovi to.|äta si rekao?
{53697}{53753}Rekao sam ti veÊ.
{53755}{53822}–avola si mi rekao!|Ti si peöko.
{53824}{53870}Ne, ne, ne, ne.|Bio sam nakratko.
{53872}{53919}Mnogo sam eksperimentisao|u ûivotu.
{53921}{53986}Eksperimentisao? Grejs,|znala si za to?
{53988}{54109}Naravno.- Trajalo je samo godinu dana.|Nije mi se svidelo.
{54111}{54185}Ako nije, zaöto nisi prestao|nakon pet sekundi?
{54187}{54281}Ako ti je oka u turu,|ne treba ti godinu dana
{54283}{54358}da shvatiö svia li ti se ili ne!|- Isprobavao sam ötoöta!
{54360}{54414}Znaö? Kad te ponizi peöko,
{54416}{54475}pomisliö da moûda on zna|neöto öto ti ne znaö.
{54477}{54536}Hej. |Ponizio me je peöko,
{54537}{54602}meni to nije dovoljno da kleknem|i popuöim mu oku!
{54604}{54651}Daj oladi!|- Gospode!
{54653}{54743}Oprosti öto te spominjem uzalud.
{54745}{54791}Oprosti, neÊu viöe.
{54793}{54875}Brinuo sam o tebi.|Zaöto mi nisi rekao?
{54877}{54983}Jer sam se bojao ovoga.|A i ne tiËe te se!
{54985}{55071}Je li?|- Nisu mene hapsili zbog droge.
{55073}{55121}Povukli su optuûbu!
{55123}{55233}Izvini!|- Ostavite se toga, momci. Smirite se.
{55513}{55584}Moj najbolji prijatelj je peöko.
{56449}{56540}Do avola!|- Do avola?
{56541}{56598}U Ëemu je problem?|- Ne znam.
{56600}{56668}Totalno puöenje.
{56669}{56724}Gospode, popravi to!
{56725}{56789}Ne mogu, ne umem.|- Zato öto si nesposoban!
{56791}{56877}Glupi automobil.|- Nije glup.
{56879}{56969}Koöta 100,000 dolara.|- Ali ne radi. Zovi 987.
{56971}{57048}äta ti je to?|- O boûe.
{57049}{57117}Ako to ne znaö onda si|stvarno glup!
{57143}{57215}Kuda Êeö?
{57267}{57358}Rekla si da Êeö da me prodrmaö|u Vegasu!
{57360}{57431}A naö seksi put u|grad greha?
{57689}{57743}äta ûelite?|- Vafle.
{57745}{57839}Puno vafla i zobene pahuljice.|Trebaju mi vlakna.
{57841}{57920}Meni isto. Vafle i zobene pahuljice.|- OK.
{57922}{57988}Znaö li öta je äugar Rej Robinson,|najveÊi borac svih vremena
{57989}{58063}pio pre borbe?|- Ne.
{58065}{58112}»aöu krvi.
{58113}{58178}Svakih par dana po Ëaöu,
{58180}{58232}pre borbe.
{58233}{58300}Onda mi dajte i Ëaöu krvi.|- Veliku ili malu?
{58302}{58361}Veliku.|- Znate öta? Ponestalo nam je krvi.
{58363}{58429}Ponestalo? - Ponestalo krvi?|Kakva je ovo rupa?
{58431}{58488}Ja Êu...
{58489}{58552}Zobene pahuljice.|- Zobene pahuljice.
{58585}{58637}I vafle.|- Dobro.
{58639}{58709}U redu. Gde je ûenski toalet?|- Napolju.
{58711}{58793}Izvinite me.|- VeÊ mi nedostajeö.
{58945}{59047}Trebalo je da mi kaûeö da si peöko.|- »oveËe.
{59049}{59129}Zbog neËega öto sam davno uradio.|Ma hajde.
{59131}{59177}NeËega?|- Da, neËega.
{59179}{59270}Zar nikad nisi Ëuo da se kaûe,|"Ko sagradi hiljadu mostova i popuöi jednog oku,
{59272}{59339}nije mostograditelj, nego puöaË."
{59341}{59411}Ne. Ne. Nisam Ëuo za tu staru izreku.|- Vrlo je poznata.
{59413}{59519}Vrlo je poznata.|- NaruËi Ëaj od kamilice, uzmi svoju brojanicu...
{59521}{59600}i ostavi me na miru neko vreme.
{59602}{59649}U redu, svejedno.|Znaö, tvoj direkt me ne plaöi.
{59651}{59755}Tvoj levi kroöe je sranje.|Sve ti je to mlitavi oka.
{59757}{59806}Zaöto si uzeo vafle?|Nikad nisi jeo vafle pre borbe!
{59808}{59852}Jedem ih jer ih ti jedeö.
{59853}{59910}Kopiraö me jer sam te uËio.
{59912}{60017}TaËno! Rekao si mi da kopiram|i uËim od velikih.
{60018}{60063}Zato hoÊu vafle.|- Poljubi me u dupe.
{60065}{60140}Da znaö da moûda i hoÊu.|Znaö? Otkako si obrijao glavu...
{60141}{60188}tako si zgodan i mnogo te volim.
{60189}{60261}Znao sam. Znao sam. Znao sam.|Joö si peöko! - Opsednut si s tim.
{60263}{60316}Ti si opsednut s tim! Da! Jesi!|- Nisam!
{60318}{60411}Jesi! Bojiö se da Êe se to|dogoditi i tebi.
{60413}{60476}Hej, nisam opsednut.|Mene opseda samo jedno...
{60478}{60573}a to je titula,|jer mogu da sredim Kampasa.
{60574}{60639}Prvo moraö da srediö mene,|a to ne moûeö?
{60641}{60694}Znaö öta? Voleo bih|da verujeö u Hrista,
{60696}{60773}jer kad te zviznem....|- Kome vafli?
{60775}{60841}Svima!|Zar je tako teöko upamtiti?
{60903}{60949}Izvolite.
{61300}{61346}VeÊ mrzite jedan drugoga?
{61348}{61433}Ne moraö mrzeti da rasturiö.
{61435}{61548}To je samo sport, zar ne?|- TaËno.
{61550}{61629}Dobro.|Hajde da jedemo.
{61631}{61720}Izvinite me.|- Samo izvoli.
{62090}{62200}Grejs.|Kad bi se kladila na veËeraönji meË,
{62202}{62266}öta misliö, ko Êe pobediti?
{62268}{62338}Ja ili Vins?|I ne foliraj me.
{62340}{62421}Budi iskrena.|Ja ili Vins?
{62473}{62554}IspraöiÊe te.
{62606}{62653}Ne.|- Suviöe je iskusan.
{62654}{62742}Ja sam brûi.|- Izdrûljiv je on.
{62744}{62815}IzbegavaÊe direkte i|uzvratiÊe kontrom.
{62817}{62912}éalim, samo se drûi ulevo|i biÊe dobro.
{62914}{62993}Ulevo.|- Da.
{63144}{63205}A ko je bolji ljubavnik?
{63207}{63260}Ja ili Vins?
{63330}{63404}Bez dvoumljenja. Ti.
{63406}{63475}U redu!
{64505}{64556}Ostani tu.
{64612}{64677}Ostani tu!
{64710}{64755}Grejs, doi.
{64757}{64804}Doi, do avola, poûuri!
{64938}{65011}Pa, ja sam bolji ljubavnik.
{65103}{65149}äta je?
{65203}{65268}Bio je ovde.|- Ko?
{65269}{65317}Isus !|Baö tu.
{65344}{65415}Isus?|Moûda se krije.
{65417}{65463}Ne krije se.
{65492}{65542}Hej.|- Isuse!
{65544}{65592}äta se dogodilo?|- Zbrisao nam Isus.
{65594}{65656}Stvarno.
{65658}{65707}Sranje.|- Ludnica.
{65709}{65770}Nosi se.
{65772}{65843}Isus se skrivao iza restorana|"Ludi Grk"...
{65845}{65891}u Bejkeru u Kaliforniji,
{65893}{65951}na pola puta izmeu|Doline smrti i Las Vegasa?
{65953}{65989}äta fali ovom mestu!
{65991}{66053}Ja ti verujem.
{66055}{66098}Ona mi veruje!|- Ona je devojka!
{66100}{66146}Ja sam ûena!|- Ona je ûena!
{66148}{66219}Znaö öta?|Nosi video kameru...
{66221}{66268}pa snimaj te stvari.|- Hej!
{66269}{66344}Nije to NLO nego sin boûji!
{66346}{66418}Uostalom, kao öpanski Meksikanac,|katolik si.
{66420}{66481}A ako si katolik, moraö da verujeö|u bogorodicu iz Guadalupea,
{66483}{66584}koja se ukazala pre 500 godina,|ni 3000 km odavde!
{66585}{66661}Hvala Bogu, ja sam ateista!
{66663}{66761}Lupaö.|- Ne! Daj ne davi me.
{66763}{66817}Da te ne davim?|- Vins. Hej, Vins!
{66819}{66868}RazbiÊu ti nos.
{66870}{66917}äta Êe ti taj prst?|- Momci!
{66955}{67048}Hej ! Dajte, do avola.
{67049}{67157}SaËuvajte to za Vegas.|»eka vas prilika za titulu i 50 somova!
{67159}{67275}O Ëemu razmiöljate?|Strpite se joö 5 sati!
{67328}{67385}50,000 dolara, ËoveËe.
{67387}{67448}To je mnogo love.|- Da.
{67488}{67549}Prilika za titulu.
{67551}{67629}Mogu da se strpim par sati.
{67631}{67705}Samo ne govori da ne vidim Isusa|kad ga vidim.- U redu.
{67707}{67774}U redu.|- Pa öta ako ga je video?
{67776}{67854}Pa öta ako je nekom popuöio?|- Niöta ja nisam puöio!
{67856}{67955}Samo bez detalja, molim!
{67957}{68003}Rukujte se.
{68058}{68133}Rukujte se, zaboga!
{68135}{68210}Do avola!
{68325}{68376}Hajde sad da jedemo vafle!
{68382}{68427}NeÊe da je primi.
{68429}{68504}Molim?|- Vaöu karticu.|Imate li drugu?
{68505}{68568}Ne, platila sam raËun.|Pokuöajte opet.
{68569}{68626}Jesam, veÊ tri puta.|NeÊe.
{68628}{68665}U redu je.|- Ne valja.
{68667}{68711}HoËete da kaûete da ne plaËam raËune?|- PozvaËu vlasnika.
{68713}{68759}"Ludog Grka?"|Dobro. Pozovite ga!
{68761}{68823}Samo ne govorite da ne plaËam raËune!|- To nije mnogo novca.
{68825}{68907}Zaöto ne platite gotovinom?|- Nemam je.
{68909}{68963}Htela sam da je uzmem u Vegasu!|Momci!
{69022}{69121}Platite raËun.|- Nismo poneli u ûurbi
{69163}{69213}Nemate niöta novca?
{69263}{69323}Treba nam za benzin!|- Izgleda...
{69325}{69373}da ste u nevolji, zar ne?
{69375}{69462}NapisaÊu Ëek. U redu.|- Ne primamo Ëekove.
{69464}{69582}Zovem pajkane.
{69584}{69630}Ja Êu da platim.
{69673}{69748}Treba mi prevoz do vegasa.|Ja Êu da platim benzin.
{69781}{69891}Samo podignite krov|da mogu da se sunËam.
{70041}{70106}Imate li koku?|Treba mi snif.
{70108}{70198}Ovde nema narkosa.|Samo bivöih.
{70200}{70281}" Bivöih."|- Ma dajte. Imate li travu?
{70283}{70330}Ne, ne, ne.
{70332}{70382}Baö ste konzervativni.
{70408}{70465}HoÊe li neko da se tuca?
{70467}{70575}Duöo, opusti se.|- Samo hoÊu da se zabavim.
{70577}{70631}Opusti se.
{70698}{70781}Hej.
{70783}{70848}Gle ti malu mis Azije.|äta misliö?
{70984}{71064}Svejedno.|Znaö öta?
{71065}{71161}Volim crnu kosu|i crne oËi.
{71163}{71260}Zato mi nije iölo sa Grejs.
{71262}{71347}Sem öto mi je dala nogu|nema ni crnu kosu.
{71349}{71416}Lud sam za crnom kosom, znaö?
{71418}{71535}Crna kosa. Kad vidim|kako bele gaÊice skliznu.
{71537}{71612}A crna öumica kaûe|" Hej ti"
{71705}{71808}Meni boja nije vaûna.
{71810}{71875}Moram da je imam.
{71877}{71949}Moûda da se smuvate nakon meËa.
{71951}{72009}Ne, ne, ne, ne, ne.|Sada.
{72011}{72057}Sada?|- Sada.
{72059}{72149}BoksovaÊemo...Grejs,|koliko joö do meËa?
{72151}{72229}Oko 5 sati.|-Za 5 sati, ËoveËe.
{72231}{72310}Ma na brzaka.
{72312}{72407}Nema tucanja par nedelja|pre borbe.
{72409}{72504}Ko to kaûe?|- Svi to znaju. Ima neke veze sa snagom.
{72505}{72572}Svi veliki tucaju pre meËa.
{72573}{72626}äto viöe, to bolje.
{72628}{72701}To mi nikada nisi rekao.|- Mislio sam da znaö.
{72703}{72787}Te reËi idu jedna s drugom.|"äampion" i "maca".
{72789}{72868}Prirodna stvar.|- Gospode.
{72869}{72953}Molim te.|- Oprosti.
{72955}{73052}Moram da imam ovu cicu,|oËigledno nije izbirljiva.
{73111}{73200}Znaö öta?|Ako ti tucaö, onda Êu i ja.
{73202}{73249}äta?|- Da.
{73250}{73316}Sluöaj. Nisu to vafli|da moraö isto öto i ja.
{73318}{73403}Molim? NeÊu da veËeras|budeö u bilo kakvoj prednosti. 
{73405}{73495}SreÊno. Grejs te je otkaËila.|OseÊa to.
{73497}{73555}Moûda i ne.|- Moûda da.
{73557}{73642}Moûda. VideÊemo.|- Da. VideÊemo.|- Da.
{73644}{73776}Hej. Kako se ono zoveö?
{73778}{73836}Lia.|- Oh, Lia.
{73838}{73928}Prelepo.|Hej, Lia,
{73929}{73998}nisam mogao a da ne primetim tvoju odeÊu.
{74000}{74079}Suknju sam sama saöila.
{74081}{74135}Stvarno? Da pipnem.
{74137}{74214}Lepo.
{74216}{74284}Zamene su se javile?|- Ne.
{74285}{74358}Tajson? - Kod kuÊe je.|Spreman je.
{74360}{74431}A Rustikov?|- Umire od straha.
{74433}{74519}S kim izlazim veËeras, Rudi?|Nikako da zapamtim.
{74521}{74580}Sa svojom ûenom.
{74582}{74648}éenom? - Da.BiÊe mnogo kamera.
{74650}{74723}Mislim da Êe to biti dobar potez.
{74762}{74852}Moja ûena?|U pravu si.
{74854}{74906}Dobar potez.
{75428}{75530}Imala sam hemi kudu 426|iz 1970, Pink Panter.
{75532}{75635}I teûak skoro 2 tone.
{75637}{75705}Ostao mi je od prvog muûa.
{75783}{75900}Miriöe na slobodu.|Zamenila sam ga za GTO Rem Er 3.
{75901}{75969}Takvih nema mnogo.
{76221}{76314}Oldsmobil, a jak auto.
{76316}{76363}Neverovatno.
{76365}{76429}Sluöaj ovo.
{76590}{76650}Predivno.
{76652}{76704}Ne verujem tihom autu.
{76706}{76790}Gladan sam te, ËoveËe.
{76792}{76863}"Gladan si me, ËoveËe"?|äta to treba da znaËi?
{76865}{76964}ZnaËi da te ûelim da vodimo ljubav...
{76965}{77038}i seks, znaö?
{77040}{77135}Sad.|- Kupi mi litar tridesetice.
{77137}{77224}Molim?|- Motorno ulje. Tamo.
{77277}{77325}Da.
{77421}{77536}" Gladan sam te, ËoveËe" ? Time ih neÊeö mnogo zapaliti.
{77725}{77824}Do vraga.Zar ne moûemo|da imamo poslednji trenutak?
{77826}{77947}"Poslednji trenutak"?|-Da. Poslednje tucanje, oproötajno kresanje?
{78033}{78112}Ne.|- Zaöto ne?
{78113}{78202}Ne zanima me.|- A da mi ga proöetaö, popuöiö?
{78204}{78272}Kresanje na brzaka?
{78273}{78368}Cezare, proveli smo tri lepa meseca.
{78369}{78457}äest meseci, duöo.
{78459}{78508}Samo su tri bila lepa.
{78551}{78671}Neka mi neko kaûe, zaöto onaj hriöÊanin...
{78673}{78746}moûe da tuca, a paganin|kao öto sam ja, ne moûe?
{78748}{78829}On tuca?|- Grejs. Grejs.
{78831}{78940}Znaö öta?|Previöe si brza za mene.
{78942}{79049}Potpuno sam zbunjen.|Zaöto me nisi ostavila sutra?
{79051}{79122}Besan sam.|Zbunjen sam.
{79486}{79569}Bolje se boriö kad si zbunjen.
{79744}{79796}Dosta.
{79798}{79881}Gde Êeö?|- Ne, ne, ne. Moram...
{79882}{79968}Moram da saËuvam neöto za veËeras.
{79969}{80094}Ne, ne, ne, ne.|Vrati se i sredi me.
{80096}{80187}Nije niöta liËno.|Samo moram u Vegas.
{80189}{80288}Pa, ja moram na drugu stranu.|Kakav si ti to muökarac?
{80290}{80368}To s tim nema veze.|Nema veze s muökoöÊu.
{80370}{80438}Hej, golupËiÊi!
{80440}{80543}äta?|- Moramo da krenemo.
{80545}{80612}5 minuta, srce.
{80614}{80688}Molim te?
{80812}{80926}5 minuta.|- Tri.
{80928}{81005}OK. OK.|U redu.
{81103}{81179}Da te sredimo.
{81181}{81247}Baö tu.
{81314}{81380}Tako, samo nastavi.
{81381}{81464}Odakle si?|Vijetnam, Kina, Koreja?
{81466}{81552}Ne. Monterej Park.|- Koja srednja ökola?
{81553}{81628}Alhambra. Dok nisam pala.
{81629}{81751}Alhambra? |Znaö Roba Morana? Klema Frenija?
{81753}{81842}A da. Klem.|On je bio maturant, a ja u prvom.
{81844}{81940}Imao je grupu.|A Dok Lorens?
{81942}{82023}Je li ti predavao?|- Da. Dvoprsti Dok.
{82244}{82290}Izvini.
{82323}{82395}Preterao sam
{82397}{82481}Znaö me.|Imam svoje uspone i padove.
{82521}{82582}Neka.
{82584}{82703}Nisam ni ja mislila to öto sam rekla.|Imali smo 3 Ëudesna meseca.
{82705}{82766}A dva su bila vrlo dobra.
{82893}{82991}äta Êeö kad prestaneö s boksom?|Mislio si o tome?
{83031}{83119}Ne, ne baö.|- Moûda bi trebalo.
{83121}{83192}Znaö?
{83193}{83330}Vins Êe biti propovednik,|sveötenik ili stolar.
{83332}{83442}Znamo graevinca u Saut Gejtu|gde nas Ëeka posao.
{83444}{83539}Ako postanem prvak sveta,
{83541}{83614}biÊe viöe moguÊnosti.
{83616}{83668}Da.
{83670}{83716}Da.
{83777}{83888}Ja ne bih bacila adresu graevinca,|za svaki sluËaj.
{83929}{83991}Vins je ima zapisanu.
{84027}{84127}Ako Vins pokuöa da te natera na rulet,
{84129}{84215}ne sluöaj ga.
{85109}{85217}Kakav oseÊaj.- Imam malecki dûoint.|Ima li neko vatre?
{85219}{85312}Ne, ne. Bez marihuane ovde.|Moûe da nam dospe u kosu, na koûu...
{85314}{85372}pa na doping test|i moraÊemo da vratimo novac.
{85373}{85456}Zaboravi. Nema öanse.|- Doping? Kuda vi to idete?
{85458}{85523}Da se borimo.|- Ko se bori?
{85525}{85579}Mi. Jedan protiv drugog.
{85581}{85656}Zaöto?|- Jer nas plaÊaju.
{85658}{85718}Mi smo profesionalci.
{85720}{85813}Zaöto onda ne idete avionom?|Brûe je. 
{85815}{85903}Volimo prirodu.|Ima mnogo brazda.
{85905}{85976}Brazda u prirodi.
{85978}{86064}Ova priroda je odvratna.|- Nama se svia.
{86066}{86147}Jesi li poznat?
{86149}{86213}Pa, znaö, bio sam,
{86215}{86316}bio sam sedmi na svetu|prema Ëasopisu "Ring".
{86318}{86423}Volela bih da gledam meË.|- Nemamo ulaznice.
{86425}{86485}Niöta zato. Jesi li ti poznat?
{86487}{86559}Do Gardena sam bio deseti.
{86561}{86624}äta je bilo u Gardenu?
{86625}{86748}Ne tiËe te se.|- Prava si kuËka.
{86750}{86852}E sad je dosta! Droljo narkomanska!|Ne sviaö mi se od prvog trenutka
{86854}{86959}i ako kaûem da te se ne tiËe|onda te se ne tiËe.
{86961}{87012}Samo se smirite.|- U redu.
{87110}{87158}äta je tako smeöno?
{87227}{87295}Zaöto viöe nisi poznat?
{87297}{87363}äta te briga.
{87392}{87462}Prevarili su ga.
{87464}{87568}Prevarili su me. Jebiga!
{87605}{87660}Prvak je bio Skiter Luis.
{87662}{87728}Izbegavao me je|otkako sam ga sredio kao amater.
{87730}{87809}Tri puta na "zlatnoj rukavici".
{87811}{87920}Bio je brz kao maËka, ali sam ga|navukao na svoj naËin borbe
{87922}{88037}i razbio ga. Gadno sam ga udesio..
{88039}{88108}Celo veËe po bubrezima.
{88110}{88191}Nedelju dana je piöao krv.
{88193}{88295}Mislio sam, od 12 rundi,|9 je mojih.
{88297}{88405}Moûda i sve.|Sem toga, oborio sam ga u osmoj.
{88407}{88509}Smeöi mi se titula.
{88511}{88607}Dame i gospodo,|evo odluke sudija.
{88609}{88747}Sudija Vili Brejden:|98 Budro, 95 Luis.
{88823}{88942}Sudija Arman Batervort:|97 Luis
{88944}{88990}Luis?|- 96 Budro.
{88992}{89089}Luis. Poludeo sam.|Rej »arls bi se bolje tukao.
{89091}{89170}Prokleti sudija...
{89172}{89302}promoter ga drûi u dûepu,|ali ostao je joö jedan i on mora biti za mene
{89304}{89404}I sudija Lu Debelo:|97 Budro,
{89406}{89452}97 Luis.
{89454}{89552}Ne! To je govno! Govno!|- Nereöeno.
{89642}{89778}RazbiÊu te! Ovo je nameötaljka!
{89780}{89826}Nereöeno.
{89866}{89939}Znaö öta se deöava|kada je nereöeno?
{89941}{90044}Prvak ostaje prvak.|Eto öta, jebiga.
{90078}{90128}-Nije poöteno.
{90130}{90235}Poöteno?|Niöta nije poöteno. Niöta.
{90292}{90407}Jedina prilika za mene jeste|da pobedim veËeras.
{90435}{90501}Niöta od toga.
{90533}{90639}VideÊemo.|- Da. To je dogovor.
{91484}{91606}Sranje! Sranje! - Dame i gospodo,|evo odluke sudija.
{91608}{91691}Nereöeno.
{91955}{91999}Ustaj!
{92353}{92445}Svetla! Hej,|Mark, Mark.
{92447}{92553}Moraö da mi izaeö u susret.|Ako diöu, moraö da odobriö.
{92555}{92625}Ako stoje, moraö da odobriö.
{92627}{92753}Ako abecedu znaju samo do slova F...
{93043}{93098}äta je sad?|- Pauza.
{93099}{93174}Vegas je samo malo niûe.
{93176}{93294}Zaöto stajemo?|- Idem da se doteram za borbu.
{93295}{93378}Idemo dalje.|Skoro smo stigli.
{93380}{93427}Nemoj da cviliö, mrzim to.
{93429}{93518}Ali, tako je blizu.|- OseÊam se prljavo.
{93520}{93644}éena na boksu mora da bude dama.|- "Prljava. "
{93646}{93730}Hej, prljavuöo mala!
{93850}{93924}äta je rekla?|- Prljavuöa.
{94059}{94106}Koliko imaö godina?
{94108}{94155}Dvadeset.
{94157}{94245}Za pet godina biÊeö ofucana,
{94247}{94302}izjebena i prosiÊeö hranu.
{94303}{94375}Ali kakvih 5 godina?
{94431}{94499}Tvoj izbor.|Samo navali.
{94573}{94655}Pomeri se.|Rekla sam, " Pomeri se."
{94778}{94871}Idem u ûenski toalet.
{94873}{94979}Dajem 25 na istok.|- 25 na Grejs.
{95091}{95170}U redu. äta je?
{95224}{95276}Prosto mi se ne sviaö.
{95470}{95537}Ni ti meni.
{95744}{95816}Jesi li dobro?
{95818}{95884}Hajde.
{95886}{95974}Nosi se, seronjo!|- Samo hoÊu da pomognem.
{95975}{96033}Gde si bio pre 5 minuta?
{96035}{96119}Posmatrali smo.|- Bedna kukavice
{96212}{96295}Krvariö...|- Hej, kuËko...|Goni se. HoÊeö malo?
{96297}{96370}Hej, ne zaboravite|da sam vam kupila...
{96372}{96442}Platila sam vam benzin i vafle,|zar ne?
{96443}{96511}Samo se ti doteraj, kuËko!
{96513}{96598}U öta bleneö, Kodûak?
{96600}{96667}Prokleti seronjo.
{96669}{96751}Misliö da imaö neöto?|Nemaö niöta! Ovoliki ti je!
{96819}{96888}Hej! Stani!
{96890}{96979}Treba mi prevoz .|- Ui, duöo. Dozvoli.
{96981}{97045}Nosi se!|- ∆ao.
{97047}{97143}NedostajaÊe mi.|- Pa-pa, Madam Baterflaj.
{97145}{97224}Baö je bila fina.|- äta joj ovo znaËi?
{97226}{97298}Pokazala je ovako.|- Ni to nije veliko.
{97300}{97370}Bar nije mlitavo.|- Svejedno.
{98774}{98852}Boûe moj.
{98971}{99030}Moja boginja.
{99094}{99154}Bila je predobra za mene.
{99156}{99217}TaËno.|- I za tebe?
{99219}{99303}Svaka devojka je previöe dobra|za svakog frajera.
{99305}{99383}Nismo mi opremljeni|za duge staze.
{99455}{99513}Ode nam drugarica?
{99568}{99657}Pa, kako izgledam?
{99659}{99728}Obaraö s nogu.
{99730}{99781}Neverovatno.|- Stvarno.
{99783}{99875}Stvarno neverovatno. Prelepo.|- ObarajuÊe. Prelepo.
{99913}{99978}Ti si stalno vozio.
{99980}{100044}Izvini. Ne, ne, ne. Izvini.|- Ne, ne, duöo.
{100046}{100094}Samo napred.
{100096}{100174}NeÊu da napadam.
{100175}{100277}Samo napred.|- Poötuj stvari onakve kakve jesu.
{100279}{100345}Samo napred.|- Hvala. Hvala.
{101018}{101047}Pa gde ste vi?
{101049}{101095}Hej.|- Kako ide?
{101097}{101143}Sve je u redu?|- Sve je sjajno.
{101145}{101245}Cezare. Rudi.|Hej, Vins. Ko je ovo?
{101247}{101323}Moja devojka, Grejs. Zove se Grejs.|-Nekad bila.
{101325}{101402}Ja sam Grejs.|- Zdravo Grejs, ja sam Rudi.
{101404}{101455}Imamo za vas posebnu ulaznicu.|- OdliËno.
{101457}{101549}A Henk Gudi vas poziva|da ga posetite pre meËa.
{101551}{101603}Samo trenutak. äta se ovde deöava?|- Moram da ih odvedem...
{101605}{101662}na lekarski pregled.|- Da. Da.
{101663}{101720}»ekaju da ih provere
{101722}{101774}Mogu li da popriËam s damom?|- Molim?
{101776}{101840}Samo brzo.|- Cezare
{101842}{101914}U redu. äta je?|- Sredi ih.
{101916}{102000}Sklanjaj ruke s moje devojke.
{102002}{102054}Bivöe.|- Ne verujem ti.
{102056}{102140}Bivöe.|- Joö nije zvaniËno.
{102183}{102250}äta je bilo?
{102252}{102386}Misliö da mogu da ga pobedim?
{102388}{102470}Previöe je brz za tebe.|I ûestoko ûeli pobedu.
{102510}{102567}Da.
{102620}{102666}Ipak...
{102695}{102752}Bolji sam ljubavnik, zar ne?
{102753}{102806}Bez dvoumljenja.
{102894}{102984}Joö te volim, znaö?|- Znam.
{102986}{103071}To ti je devojka?|- Da, to mi je devojka.
{103073}{103141}äta je?
{103143}{103215}Samo razgovaraju. Pa, prijatelji su.|Mogu da razgovaraju. - Da.
{103217}{103267}Bolje kreni.
{103269}{103376}Vidim vas. Vidim vas.
{103377}{103428}Bolje kreni.
{103430}{103509}Vins. Vins, hajde.
{103511}{103557}äta je to bilo?|- Niöta.|- Idemo.
{103558}{103615}Idemo. U redu.|- Kako niöta? 
{103617}{103688}Ljubio si je preda mnom.|- HoÊeö da se tuËeö?
{103689}{103738}Apsolutno.
{103740}{103833}Proöli su pregled.|Cela stvar je odobrena.
{103910}{103986}Henk, ûelim da te upoznam s nekim.
{103988}{104049}Ovo je Grejs.|- Zdravo.
{104051}{104133}Ima sjajne ideje i traûi ulagaËe.
{104135}{104192}Henk Gudi.|- Gospodine Gudi.
{104193}{104286}Za vas Henk. Uvek sam|zainteresovan za ulaganje.
{104288}{104382}äta to imate?|- Prototip nove muöke Ëarape.
{104384}{104453}Ovde imam uzorak.|Razlikuje se od ostalih...
{104455}{104519}svojim jedinstvenim dizajnom.
{104521}{104631}Nogavica je od svile,|a stopalo od pamuka,
{104633}{104727}pogodno za one s tegobama|i koji ne podnose veötaËka vlakna...
{104729}{104775}ili Ëarape öarenih boja.
{104777}{104848}A ipaj ûele da izgledaju elegantno?|- TaËno.
{104850}{104907}Rudi? Rudi?
{104909}{104955}Da.
{104957}{105062}äta joö imate?|- Periskop za gledanje TV-a iz kreveta...
{105064}{105154}pod pokroviteljstvom udruûenja kiropraktiËara.
{105156}{105192}Periskop?|- Periskop.
{105194}{105266}Da potraûimo krevet da ga isprobamo.
{105268}{105320}Nisam baö toliko laka.
{105321}{105393}Lampse. Ale.
{105394}{105441}Dûo, kako si?|- Dobro, kako ide?
{105442}{105503}Dobro.|- Sluöaj. Treba mi pomoÊ.
{105505}{105595}Briga me öta Êe sutra reÊi novine,|ali veËeras hoÊu da sam faca.
{105597}{105659}Dva oronula belca...|- Hej, jedan nije belac.
{105661}{105709}On je Latinoamerikanac.|- äpanac.
{105711}{105793}Briga me öta je.|Obojica su za penziju.
{105794}{105853}Ne, ne, ne, ne. BiÊe oni sjajni,|ali zbog tragedije sa...
{105855}{105973}Rosariom.|- Da. I zbog zloupotrebe droge itd.
{105975}{106077}Dakle, zapoËni sa tuûbalicom,|pa nastavi s pohvalama.
{106078}{106136}Moram da razgovaram sa Ratnerom.|- Zar Domingezu...
{106137}{106184}nije pre par godina napukla roûnjaËa?
{106185}{106257}Nije istina. Nije istina.|Hej, Mark! Ovde Dûo!
{106258}{106315}Vidi li on uopöte?|- Momci, malo ûivlje.
{106428}{106489}Vinse. Cezare.
{106530}{106600}Kako ide?|Pregled je proöao sjajno.
{106602}{106702}Dajte mi dragocenosti.|Stavite ih ovde.|NovËanike, satove, nakit...
{106704}{106794}Ostavio sam novËanik u Los anelesu jutros.|- Moj novËanik nije kod mene.
{106796}{106879}-A ovo? NeÊeö valjda to da nosiö.
{106881}{106946}Stavi tu. »uvaÊu ti.
{107007}{107060}Izvoli.
{107062}{107133}Hvala.|- Imam sjajne ljude za ugao.
{107135}{107215}Sigurno niste baö spemni.
{107217}{107270}Ne baö.|- Tebi je svejedno?
{107272}{107338}- U stvari... - LiËno...|- Dobro. U redu.
{107340}{107396}Lupe, ti Êeö s Vinsom.|Dûesi, ti sa Cezarom.
{107398}{107459}Vi ostali se rasporedite.
{107461}{107528}Sjajni su za rane.
{107529}{107637}∆uj, najvaûniji je ugovor.|Zanima nas izazov za titulu.
{107639}{107736}To je suötinska stvar.|- Da, to nam je vaûno.
{107738}{107800}Svakako. Svakako.|DoneÊu ih u svlaËionicu.
{107802}{107881}OK. Vinse, ti si tamo.|Cezare, ti si ovde. OK. Hajdemo.
{107883}{107935}Dobro.|- Hajdemo.
{108019}{108088}Dobro. Sjajno.|Sve Êe biti sjajno.
{108139}{108197}Izgledaö snaûno, momËe.
{108630}{108689}Ne Ëitam baö najbolje.
{108690}{108751}Pa, sad si Ëitao Bibliju.
{108753}{108851}Bibliju da, drugo baö i ne.
{108853}{108918}NeÊe potpisati.|- Postajem zabrinut...
{108920}{108966}Bez brige. Prestani.
{109275}{109342}Da potpiöem?
{109414}{109484}Nemaö izbora.|Potpiöi.
{109486}{109593}Gde? - PokazaÊu ti.|Samo opuöteno.
{109595}{109683}Da. Da.|Izgleda u redu. PotpisaÊu.
{109751}{109819}Imam samo jedno da vam kaûem.|I to pet puta
{109821}{109934}ne, ne, ne, ne|i ne, u redu, seronjo?
{109936}{110005}»ekaj. Cezare, ËoveËe!|- Hej.
{110007}{110096}Koliko je proölo?|Dobro si putovao? Sve u redu?
{110097}{110162}Davno je bilo?|- Znaö ti koliko.
{110164}{110211}Od Gardena, zar ne?|Jebeö Garden.
{110213}{110269}Da.- Jebeö Garden.|Vaûno je da si ovde.
{110270}{110325}Sluöaj. Ovo je tvoj advokat Dante Solomon.
{110327}{110400}Drago mi je.|- To je tvoj advokat, zar ne?
{110402}{110467}Tvoj je. Samo tvoj.|- Tvoj sam.
{110469}{110530}Imam li izbora?|- Nema vremena.
{110532}{110629}Jedan od najboljih ljudi|sa kojima sam ikad radio.
{110631}{110714}Pre 12 godina izabran je za Ëoveka godine.|Ne, pre 11 godina.
{110716}{110793}Kao da je bilo juËe.|- Ugovori su sjajni.
{110794}{110855}ProuËio sam ih.|- Mene zanima samo...
{110857}{110920}öansa za titulu u srednjoj.|- Jasno.
{110921}{110983}Sve je tu. Evo, vidiö?|- Da.
{110985}{111082}"U roku od 6 meseci,|po odobrenju svetskih tela za boks..."
{111084}{111179}I tako dalje. I tako dalje.|- A ovih preostalih 50 strana?
{111181}{111262}Niöta. To su samo crte na "t",|taËke na "i".
{111264}{111334}I joö par potpisa.
{111336}{111402}Zaöto je sve to neophodno? Zaöto?|- Do avola!
{111404}{111478}Do avola, Cezare,|jer ja tako kaûem!
{111664}{111735}Mislim na tebe poslednjih 5 godina.
{111737}{111851}Nisam isfolirao naokaut u Gardenu.
{111853}{111927}Iznenadio me je, kao i druge.
{111929}{111977}Dogaa se, znaö i sam.
{111979}{112052}Bilo je namerno...
{112054}{112146}legao si koliko si dug i öirok.
{112148}{112267}Osramotio si me.|Sada imaö priliku da se iskupiö,
{112269}{112315}i to samo zato öto je...
{112317}{112410}jedan naroljan, a drugi u mrtvaËnici!
{112412}{112472}U redu?
{112473}{112525}Potpiöi.|- Ne, ne Ëini to.
{112577}{112627}Potpiöi.
{112752}{112818}Ne, ti si dûukac!
{112820}{112887}I tvoji bokseri su dûukci.|Cela ekipa su ti dûukci.
{112889}{112968}Teraj se.|- Cezare. Cezare.
{112970}{113035}Potpiöi.|- Molim te.
{113036}{113090}Gde? Gde?
{113118}{113187}Ovde.
{113190}{113235}OK.
{113238}{113319}Ustali smo usred noÊi.|Morali smo u toalet.
{113320}{113398}Nisam znao je li levo ili desno,|ispred ili iza.
{113400}{113456}Pa Edi kaûe,|"Koliko Êemo morati ovo da trpimo?"
{113457}{113556}A ja kaûem, "Ko prvi zapiöa ormar,|znaËi da nismo u sobi."
{113558}{113606}Vidimo se, Stiv.
{113608}{113666}Henk.
{113754}{113849}Gde ste odseli?
{113884}{113960}Zapravo, joö uvek nigde.
{113962}{114060}Rudi, daj dami kljuË|od apartmana Pago Pago.
{114062}{114137}Vaûi.|- Nema potrebe.
{114139}{114200}To je moj hotel.
{114202}{114319}Aleksej Rustikov. Evo nas uûivo|u bajnom hotelu Mandelej Bej...
{114320}{114380}PoËinje, bolje da krenemo.
{114423}{114499}Idem tek na glavni meË.
{114500}{114560}Rudi Êe vas otpratiti,
{114562}{114636}i posle dovesti na prijem.
{114638}{114712}Pazi na Grejsi i dovedi je na prijem.
{114714}{114799}Jasno.|- Grejs, gospodine Rudi.
{114801}{114868}Grejs.|- Henk, Grejs.
{114870}{114945}Henk.|- Vidimo se.
{115038}{115135}Vinse, znaö li neöto o tom Domingezu?
{115220}{115306}Ne brini, mi Êemo ga proveriti.
{115556}{115633}Teraj se! Teraj se!|Teraj se! Teraj se!
{115742}{115802}Teraj se! Teraj se!|Teraj se! Teraj se!
{115887}{115956}Teraj se! Teraj se!|Teraj se! Teraj se!
{115958}{116056}Teraj se! Teraj se!|Teraj se! Teraj se!
{116061}{116164}Rustikov je pobedio mnoge|koje ne poznajemo.
{116166}{116232}Je li zbog toga pretnja Majku Tajsonu?
{116233}{116344}115 zemalja je kupilo TV prava|za ovaj meË...
{116346}{116449}u nadi da se Rustikov moûe|suprotstaviti Tajsonu,
{116451}{116526}ali Ëitaj mi sa usana na 115 jezika...
{116528}{116576}Novac ne vraÊamo.
{116578}{116672}A, shvatam. Nema optuûbi,|ûalbi, odöteta.
{116673}{116720}Ovo je sport.
{116721}{116783}Dvostruki prvak Dûordû Formen...
{116785}{116835}priËaÊe nam o Tajsonu.
{116837}{116937}Imao je mnogo pehova.|Je li moûda ovaj put bolje?
{116939}{117019}Joö uvek ima jak udarac. äta da kaûem?
{117020}{117096}»uÊemo se joö kasnije tokom veËeri,
{117098}{117166}ali prvo, prva, uvodna borba.
{117168}{117233}Nenajavljena i jedinstvena prilika...
{117235}{117314}za dva momka, ubaËena u poslednja 24 sata.
{117316}{117368}Spremimo se.
{117369}{117467}Kaûu da je Tajson uöao u arenu.|Da pogledamo.
{117876}{117981}Cezare, vreme je. Idemo Dûes.
{117983}{118032}Hajde.
{118034}{118104}Dobro izgledaö.
{119444}{119526}Provera.
{119983}{120039}Provera.
{120186}{120279}Cezare. Cezare!
{120280}{120338}Budi jak. Moûeö ti to.
{120340}{120407}U redu si?
{120508}{120554}Faco.
{120556}{120636}Vinse. Vinse!
{120638}{120696}Budi jak. Moûeö ti to.
{120795}{120850}Dame i gospodo,|prelazimo na srednju kategoriju.
{120852}{120965}Zamena u vaöem programu|pre glavne borbe.
{121016}{121108}Najpre predstavljamo u crvenom uglu,|teûak 80 kg,
{121110}{121171}sa 32 pobede,
{121173}{121227}6 poraza i 5 nereöenih meËeva.
{121229}{121290}Roen u Madridu, iz Filadelfije,
{121292}{121372}i sada Los Anelesa u Kaliforniji,
{121373}{121508}Cezar " EI Kalifa " Domingez!
{121510}{121599}Njegov protivnik, na suprotnoj strani ringa...
{121600}{121742}u plavom uglu, teûak 82 kg...
{121744}{121875}sa sjajne 42 pobede,|11 poraza i 9 nereöenih meËeva,
{121877}{121949}nekada prvi izazivaË u srednjoj kategoriji.
{121951}{122030}Takoe iz Los Anelesa u Kaliforniji,
{122032}{122124}Vins Budro!
{122126}{122173}Vins.
{122346}{122412}Domingez,|Budro.
{122559}{122629}Gospodo, u svlaËionici ste dobili uputstva.
{122631}{122680}Bez niskih udaraca.
{122682}{122770}Ima li pitanja?|HoÊu Ëistu borbu.
{122772}{122853}Dobro se zaötitite.|Sluöajte moja nareenja.
{122855}{122899}Dodirnite se rukavicama.|Hajde.
{122960}{123026}Znam ja njega. Nije viöe brz.
{123028}{123082}-Da.|- »uvaj se levice.
{123084}{123130}Znam.|- Udara kao mula. Kloni se levice.
{123132}{123182}Znam. Znam.|- Kaûu da ima dobar direkt,
{123184}{123230}ali pada na levi kroöe.
{123232}{123280}Hajde.
{123282}{123357}PoËinje prva runda.
{123359}{123424}Kaûu da Budro dobro udara u telo,
{123425}{123520}pa pripazimo kako Êe navaliti|na grudni koö.
{123522}{123594}Dobar rad nogu.
{123596}{123665}Ovo su pravi profesionalci,
{123667}{123757}obojica s 12-15 godina iskustva|u ovom sportu.
{123759}{123825}Hajde!
{123827}{123908}Budro traûi put do Domingeza,
{123910}{123966}koji zasad drûi stvari pod kontrolom.
{123967}{124062}Sjajan levi kroöe!|Domingez pada.
{124064}{124156}SliËno Domingezovom pokuöaju od pre 5 godina...|- Cezare, ustani! Ustani!
{124158}{124226}protiv Velarija u Medison Skver Gardenu...|- Cezare, ustani.
{124227}{124309}kada ga je u prvoj rundi|oborio isti takav kroöe.
{124311}{124366}Moûda imamo brz zavröetak borbe...
{124367}{124414}äest! Sedam!|- Hajde, Cezare. Ustani.
{124415}{124499}Osam!
{124501}{124583}Dobro si?|- Domingez Êe nastaviti.
{124585}{124632}VeÊ jedan nokdaun za Budroa.
{124634}{124691}Budro ûeli da ostavi utisak na publiku...
{124693}{124792}i pokuöava da dovröi stvar.
{124794}{124882}Drugi nokdaun desnim direktom!|- Ustani!
{124883}{124963}Budro!|- EI Kalifa opet pada.
{124965}{125027}Kako moûeö?
{125029}{125127}Ustaj! Ustaj!|- Na snazi je pravilo od tri nokdauna.
{125129}{125189}Moûeö ti to!|- Ako i ustane,
{125191}{125258}Pet! äest! Sedam! - Domingez mora da izdrûi|joö viöe od minuta koliko je preostalo u ovoj rundi.
{125259}{125343}Osam! Devet!|- Prva runda od zakazanih deset.
{125345}{125383}Domingez se oporavlja...|- Dobro si?
{125385}{125451}od veÊ drugog nokdauna...
{125453}{125502}od ruku Budroa.
{125503}{125604}Borba! - Domingez ustaje,|ali oËigledno je uzdrman, 
{125606}{125691}od dva nokdauna.
{125693}{125770}Pitate se kako Êe izdrûati do kraja runde.
{125798}{125863}Dobar rad tela.
{125865}{125923}Sredi ga!
{125990}{126054}Sudija pomno prati.|- Stani. Stani.
{126055}{126118}Prestani da udaraö.|- Budro napada.
{126119}{126191}Domingez upuÊuje direkt da preûivi.
{126193}{126292}Domingez se saginje izbegnuvöi dva udarca.
{126294}{126360}I to je to.|Domingez je preûiveo...
{126362}{126454}dokopao se kraja prve runde|uprkos dva nokdauna.
{126455}{126525}Dobro sam. Dobro sam.
{126527}{126576}Sve je u redu. Smiri se.
{126626}{126720}Gotov je. Samo se usredsredi i imaö ga.
{126722}{126797}Kloni se njegove levice.
{126799}{126849}U redu? HoÊeö da bacimo peökir?|- Ni govora.
{126851}{126913}Nikako.|- U redu.
{126915}{127017}Direkt, direkt, pa onda kroöe.
{127073}{127144}Kombinuj, pa Êe se otvoriti za onaj glavni.
{127146}{127201}Kloni se levice .|- Kombinuj, u redu?
{127203}{127298}PojaËaj direkte.|- UdvostruËi, utrostruËi i gotov je.
{127299}{127397}Kloni se levice.|- Nemoj da stojiö u mestu!
{127399}{127469}U redu 
{127471}{127530}Usredsredi se, u redu?
{127531}{127580}»ujem da su doöli zajedno kolima,
{127582}{127639}sigurno je bilo zanimljivo.
{127640}{127710}äteta öto nismo Ëuli viöe.
{127711}{127763}Pre smo svi tako putovali.
{127765}{127866}Sada Domingez ispaljuje udarac.
{127867}{127917}Budro se brani
{128087}{128211}Iznad Budroovog levog oka je posekotina.
{128212}{128286}Nije to niöta. Navali direktima.
{128287}{128369}Vinse! Daj direkte!
{128371}{128442}Za koga navijate?
{128443}{128510}Za obojicu.
{128511}{128580}Oboûavam ih.
{128582}{128671}Zar ga niste ostavili.|- Kruûi ulevo!
{128673}{128736}Domingez je potpuno drugi Ëovek.
{128738}{128799}Bori se energiËno i sa voljom,
{128801}{128897}isti Domingez, u ranijem pohodu na titulu,
{128899}{128967}je bio na zemlji veÊ u prvoj rundi|i nije mogao da ustane.
{128969}{129027}Ljudi uz ring sada burno prate...
{129028}{129075}ovu ûestoku borbu ispred njih...
{129076}{129131}jedan je dvaput pao...
{129133}{129223}dok drugi krvari iz posekotine.
{129225}{129297}Budro joö uvek traûi svoj ugao.
{129299}{129350}Joö ga nije naöao.|Evo ga.
{129415}{129508}Je li gadno? - Niöta.Niöta.|Imamo najboljeg za takve stvari.
{129643}{129732}To je onaj stari direkt|koji te je i doveo u Garden.
{129734}{129803}Moûeö da ga razbijeö.
{129804}{129873}Moûeö da ga dobijeö.|- Da vidim oko.
{129875}{129956}Nije niöta. VeÊ smo ga sredili.
{129958}{130009}Vinse, ne radiö po planu.
{130011}{130091}Izbegavaj direkt, kruûi.
{130093}{130166}Ne vidim od krvi.|- To smo sredili.
{130167}{130219}Sluöaj me. Sluöaj me,
{130291}{130342}Sluöaj!|- Da.
{130343}{130462}Kontriraj kroöeom kao Lopez s Kvortijem.
{130463}{130556}SeÊaö se te borbe? Oku nije niöta.
{130558}{130611}Imamo najboljeg za to u poslu.|Ne brini se.
{130613}{130682}Sad, sluöaj me.|Udri ga po posekotini.
{130683}{130758}U redu? Otvori je i ima da iskrvari.|Jesi li shvatio?
{130759}{130819}U redu. Udri po posekotini.
{130820}{130867}Po posekotini. U redu.
{130935}{131019}Po posekotini.
{131080}{131206}Vins Budro i Cezar Domingez|veûbaju u istoj dvorani u Los Anelesu.
{131207}{131272}Dugo se druûe.
{131274}{131325}Ali je ovo prvi put da su zajedno u ringu.
{131367}{131451}Kakva je ovo borba.
{131453}{131555}O tome ti priËam.
{131557}{131648}Straöna levica Domingeza.
{131694}{131787}Publika je tek sad shvatila kakav meË gleda...
{131943}{132008}Meusobno se guraju.|Oh, kakva desnica!
{132095}{132151}Ustani na 8.|- Jedan!
{132153}{132224}Dva!
{132226}{132287}Tri!|- Kakav si ti to muökarac?
{132289}{132380}»etiri!|- Hajde, Vinse. Na osam.
{132382}{132492}Pet! äest!
{132494}{132545}Sedam!|- Ustaj.
{132571}{132611}Osam!
{132613}{132743}Devet! Jesi dobro?|Prii mi.
{132790}{132845}Boks!
{132847}{132914}Domingez sad navaljuje.
{132915}{132989}Postao je lovac koji kontroliöe plen
{132991}{133092}dok publika na skupim mestima uz ring
{133094}{133160}poËinje napeto da prati meË
{133162}{133264}koji je naelektrisao arenu.
{133266}{133319}Opet sjajna runda, druga za redom...
{133321}{133403}za Domingeza.
{133405}{133510}Retku priliku da svetu pokaûu|sve öto umeju,
{133511}{133604}ova dva boksera ûele da iskoriste do kraja,
{133606}{133697}po cennu zabave.
{133845}{133965}Budroova snaûna desnica.
{133967}{134047}Sudija ga upozorava...
{134048}{134130}da ne koristi lakat.
{134185}{134301}Oba boksera imaju svoje trenutke,|joö jedan Domingezov reli.
{134523}{134590}Arena je poËela da se popunjava.
{134591}{134666}Holivudske zvezde su poËele...
{134668}{134763}da zauzimaju mesta uz ring|i poËinju da prate...
{134765}{134840}nadahnutu borbu pred sobom.
{134871}{134940}KreÊi se! KreÊi se! KreÊi se!
{135589}{135653}Kloni se direkta i kontriraj kroöeom.
{135654}{135722}Ti si öampion. Tako. Tako.|- Znao sam.
{135723}{135785}Ostani na njemu.|Ostani na njemu.
{135889}{135937}Na posao.
{136202}{136278}OK. U redu.
{136280}{136357}äest! Sedam!|- Hajde.
{136358}{136430}Osam! Devet!
{136432}{136518}Hajde.
{137192}{137292}Opusti se. Spusti ruke.|Spusti ruke. Ispruûi ruke. U redu.
{137294}{137360}Umoran je.|Navali.
{137362}{137415}Zar nisi Ëuo izreku,
{137417}{137478}"Ko sagradi hiljadu mostova i popuöi jednog oku...
{137480}{137550}Nije mostograditelj, veÊ puöaË."
{137552}{137619}Shvatio si. Shvatio si.
{137621}{137683}PuöaË.|- Dobro si?
{137685}{137757}PuöaË.|- U redu. Na njega.
{137758}{137855}Razbi mu facu.|Razbi mu mozak. Samo napred.
{138030}{138112}Sranje.
{138466}{138539}Idemo!
{138604}{138706}U redu. Dobro ti ide.|Dobro ti ide.
{138707}{138807}Nastavi da ga napadaö.|Ne povlaËi se. Samo napadaj.
{139180}{139239}éelim da ga napadaö.|Guraj ga.
{139708}{139766}Isuse.
{139890}{139960}Idemo. Boks.
{140361}{140436}Hej, hej, hej, hej.|Ne udarajte nisko.
{141170}{141246}Ostani dole! - Dva!
{141248}{141323}Tri! »etiri!
{141325}{141393}Pet! äest!
{141394}{141486}Sedam! Osam!
{141488}{141587}Devet! Dobro si?|Prii.
{141994}{142101}Diûi se!|- Sjajan Budroov udarac,
{142102}{142189}i nemoguÊe da Êe|Domingez opet ustati.
{142191}{142263}Tri! »etiri! Pet!|- Diûi dupe.
{142265}{142313}Hajde, Cezarer. Diûi se.|U redu.
{142314}{142361}Sedam!
{142362}{142437}Sudija broji.|- Osam! Devet!
{142439}{142489}Ali Domingez opet ustaje!|- Dobro si? - Da.
{142490}{142540}Prii.
{142601}{142670}Idemo! Boks!
{142766}{142850}OK, pauza, pauza, pauza!
{143197}{143257}Sedi i sluöaj.
{143259}{143311}U redu. To je to.|- Samo se opusti.
{143313}{143389}Dobro mu je, obiËna ogrebotina.
{143390}{143441}Moram da je pogledam.
{143442}{143492}Lekar u ringu, doktor Velvo Ginsberg...
{143494}{143565}gleda da li Budro moûe da nastavi.|- Da ga pogledam.
{143566}{143658}Ispljuni. - U redu, Vinse.|Koliko prstiju vidiö?
{143660}{143749}Koliko prstiju?
{143750}{143861}Tri. - Nije dobro.|Samo joö jedna runda.
{143862}{143934}Moûeö da izbegneö udarce...
{143936}{143982}i napadneö ga.
{143984}{144020}Shvatio? Sredi ga kroöeom.
{144022}{144082}Da ga vidim.
{144084}{144162}Da ga vidim.|VidiÊ moje prste? - Da gospodine.
{144163}{144210}Koliko ih je?|-Dva.
{144211}{144266}U redu. Ovaj je dobro.
{144267}{144338}Dao je taËan odgovor.
{144340}{144419}Dobro ti ide.
{144841}{144942}Ovo je tvoja noÊ. Sredi ga|i imaö priliku za titulu.
{144943}{144993}Obori ga. Razumeö?
{144994}{145085}Joö dve runde. Ovo je deveta.|Moûeö ti to. Bez milosti. Bez milosti. Hajde.
{145086}{145155}Imaö ga. Imaö ga.
{145287}{145376}Boks!
{145378}{145484}Deveta runda neËega öto je oËigledno|borba godine.
{145595}{145669}Joö jedan sjajan udarac i Budro pada!
{145670}{145748}Ne ustaj!
{145749}{145827}Ustaj! Ustaj! Ustaj!
{145828}{145909}»etiri!
{145911}{145990}Pet! äest!
{145992}{146059}Sedam!
{146061}{146177}Osam! Devet!|- Diûi se, diûi se!
{146203}{146254}Dobro si? Prii.
{146256}{146314}Prii.
{146316}{146370}Idemo. Boks!
{146479}{146543}Hajde!|Sredi ga!
{146636}{146700}Tako. Tako. Sredi ga.
{146737}{146800}Sredi ga. To je to.
{146801}{146923}OK. Pauza.|U redu. Pauza! Boks.
{147121}{147200}MiËi se iz ugla. Beûi odatle!
{147255}{147311}Dupli udarac!
{147360}{147440}Desno, desno.|- Beûi iz ugla.
{147959}{148015}Jeste li videli?
{148197}{148276}Kraj 9. runde.|Joö tri minuta...
{148277}{148348}ove junaËke borbe.|Dvojica boksera...
{148349}{148452}koji su do veËeras bili sasvim zaboravljeni.
{148453}{148537}Ako ûeliö titulu moraö da ga oboriö.
{148539}{148646}Moraö da ga oboriö!
{148761}{148812}Ovo je rat.|Kuda Êete?
{148814}{148896}Ne mogu viöe ovo da gledame.|- Opaka mala.
{148897}{148950}Nosi se.
{149365}{149443}Koja je runda?|- Poslednja, joö tri minuta.
{149445}{149491}Poslednja.|- Da.
{149493}{149565}Ako ûeliö titulu moraö da ga oboriö.|Moraö da ga oboriö.
{149567}{149661}Rasturi ga.|- Evo desete i poslednje runde...
{149662}{149716}u meËu koji ima sve.
{149717}{149767}Obojica su bili na podu.|- Idi i sredi ga.
{149769}{149835}- Povredili su jedno drugog.
{149837}{149919}Obori ga i ne daj mu da ikad|viöe ustane!
{149921}{150006}Titula! Titula!|Ovo je tvoja noÊ. Sredi ga.
{150008}{150073}I Vins Budro je spreman da izae.|- Vinse, idi tamo...
{150075}{150111}i ispraöi ga!
{150113}{150199}...krvava maska.|Domingez ne deluje bolje.
{150201}{150260}Obojica su bili podjednako dobri.|- Hajde. Dodirnite se rukavicama.
{150261}{150323}Popadali su viöe puta|nego öto moûemo da izbrojimo.
{150325}{150401}Publika je na nogama uz ring.
{150449}{150541}Ovo viöe nije boks, veÊ barska tuËa.
{150543}{150633}Obojica ispaljuju teöke salve udaraca...
{150635}{150716}u oËajniËkom pokuöaju|da obore protivnika.
{150717}{150828}Jutros su bili prijatelji,|ali ovo je sada drugi svet.
{150829}{150934}Deseta runda mudre i razorne bitke.
{151016}{151096}Budro ne moûe da se pribere|od joö jednog Domingezovog udarca desnicom.
{151097}{151188}I sad...
{151329}{151398}Budro je uzvratio udarcem u telo.
{151400}{151511}Domingez pada, a Budro ga udara|iako je na podu!
{151513}{151569}Pauza! Pauza!|Prestani! Pauza!
{151571}{151640}Skloni se, Budro.|Idi u ugao.
{151641}{151722}...napokon shvatajuÊi da treba da ih razdvoji.|- Nemoj da stajeö.
{151724}{151794}Tri! »etiri!
{151796}{151847}Ustaj.|- Pet!
{151849}{151926}Hajde, ustaj.|- Cezare, ustaj! - äest!
{151928}{151998}Ustaj. Hajde. Ustaj.|- Sedam!
{152000}{152054}Hajde, Cezare!|Cezare!
{152056}{152123}Osam!|- I Cezar ustaje!
{152125}{152209}Nije mu dosta.
{152211}{152291}Prii.|- Da gospodine.
{152293}{152361}Idemo. Boks!
{152363}{152417}Joö manje od dva minuta.
{152418}{152492}Hajde.|Hajde. Idemo.
{152621}{152723}njegov udarac desnom rukom je|ispruûio Budroa duû celog ringa....
{152725}{152836}I Budro je na podu!|To je Domingez !
{152837}{152924}I sada Budro udara iako je na kolenima.
{152925}{152993}Vinse, ustaj!
{152994}{153069}Vinse, ustaj.|Ustaj!
{153071}{153158}Ne prekidaj! Dobro je!|Vinse, dobro si?
{153160}{153206}»etiri!
{153208}{153278}Ustaj i sredi Meksikanca!|- Pet!
{153280}{153330}äest!|- Ne prekidaj, jebote!
{153332}{153374}Sedam!
{153428}{153490}Osam!|- Hej, Vinse! Vinse!
{153492}{153563}Vinse! Dobro si?|- Boks!
{153565}{153612}Idemo.
{153697}{153789}Ispraöi ga!
{154597}{154655}Prekinite borbu. Prekinite borbu!|- Hej.
{154700}{154747}Prekinite!
{155632}{155686}Evo gonga! Evo gonga!|- To je to.
{155688}{155743}Kraj junaËke borbe...
{155745}{155802}izmeu Vinsa Budroa|i Cezara Domingeza.
{155804}{155929}Pravi pobornici boksa joö dugo Êe priËati...
{155930}{155977}o onome öta su videli.
{155979}{156061}Da znaö da si dobar borac?|- Ni ti nisi loö.
{156063}{156125}Mislim da sam pobedio.|- I ja isto mislim.
{156718}{156770}Vinse! Vinse!
{156811}{156885}Bio si Ëudesan, sjajan.
{156887}{156990}Dobra borba, Vinse.
{157064}{157147}Cezare! Cezare!
{157148}{157194}Cezare! - Hej.
{157196}{157262}Bio si briljantan.|- Stvarno?
{157264}{157335}Briljantan.|- Stvarno tako misliö?
{157524}{157564}Vidimo se!
{157672}{157720}U redu. Hvala.
{157808}{157880}Dame i gospodo,|pre nego öto Ëujemo rezultat,
{157882}{157958}molim aplauz za ovu dvojicu boksera.
{157960}{158033}Bio je to pakleni rat!
{158286}{158393}A sad, sluûbeni rezultat.|Sudija Harison Perl...
{158395}{158455}96-95 za Budroa.
{158456}{158541}On je za Budroa.|- äta li sam ti rekao?
{158543}{158629}Pobedio si. Pobedio si.
{158680}{158803}Sudija Ejbrams Harlems,|96-95 za Domingeza.
{158804}{158862}U redu. U redu.
{158978}{159060}I sudija Stiv De Roö je glasao...
{159061}{159140}95-95.
{159142}{159205}MeË je nereöen!
{160185}{160243}Sjajno. Sjajno.
{160244}{160312}Gospoda iz komisije donela su Ëek.
{160314}{160372}Kakva paklena predstava.
{160373}{160459}Nije predstava, nego borba.|- Da. Znam.
{160504}{160635}äta je ovo? 24,000.|Dogovor je bio 50,000.
{160636}{160723}Honorari promotera, advokata,|ljudi u uglu...
{160724}{160793}Sve piöe u ugovoru.|- Vinse. Hej.
{160795}{160872}Vinse, jesi li video? 24,000.|- Da.
{160874}{160946}A ostatak?|- Standardne klauzule.
{160948}{161007}Standardne klauzule. äta ti to znaËi?|- Sve je u redu.
{161008}{161109}Sluöajte me.|Domino je oduöevljen veËeraönjim nastupom.
{161111}{161175}To je dobra vest.|- Lupaö.
{161176}{161243}éeli da opet radi sa vama.|- Opet ste u milosti.
{161244}{161303}Na öta misliö? Revanö?|- Moûemo da popriËamo.
{161304}{161379}A titula?|- Imamo mnogo da razgovaramo.
{161381}{161451}Revanö? Ko zna?|- Dolazi Tajson. Dobar posao, momci.
{161452}{161550}Moram da idem. Imate sjajna mesta|za glavnu borbu, i pobrini se za to oko
{161552}{161625}da ne zavröiö kao ja.|VideÊemo se gore.
{161627}{161689}OdliËno, momci. OdliËno.|- Sine, hajdemo u bolnicu...
{161691}{161774}da to odmah sredimo.
{161776}{161865}Hvala.|- Ne mogu da verujem.
{162345}{162418}I joö jednom,|Tajson protiv Rustikova...
{162420}{162530}Joö jedna skupa tuËa|u trajanju od 52 sekunde.
{162532}{162636}Tajson je odneo joö jednu pobedu.
{162754}{162854}Kad ste poslednji put zaradili toliko,|tako brzo?
{162856}{162914}PriliËno brzo? Sve si uloûio?|- Svakako, hvala.
{162916}{162977}Hej, Dik. Drago mi je öto si stigao.|- Zdravo, Henk. Kako si?
{162979}{163038}Patricija.
{163040}{163087}Hej, Henk. Kako si?|- Kako si ti?
{163089}{163143}Uûivao si u borbi? Bila je brza.|- Bila je previöe brza.
{163453}{163564}Izvinite nas, molim?|Rudi, daj Grejsinoj drugarici piÊe?
{163566}{163644}Da.|- ∆ao.
{163705}{163772}Kako vam se svia apartman?|- Nisam joö bila.
{163774}{163865}Moûemo gore privatnim liftom.
{163867}{163936}Rado bih vam pokazala planove...
{163937}{164026}svog proizvoda, periskopa,|o kom sam vam priËala.
{164084}{164146}Naopako.
{164239}{164328}Zanimljivo. Vrlo zanimljivo.
{164333}{164416}Vinse, ne znam baö.
{164418}{164470}Veruj mi. UpaliÊe.
{164472}{164541}Hiljadu, crveno.|- Ovde.
{164639}{164716}Moraö da uloûiö da bi dobio.
{164718}{164790}11 crno.
{164792}{164858}Gospode.|- Hej, hej, hej.
{164860}{164950}Nema problema. UdvostruËiÊemo.|2000, crveno.
{164952}{165028}A da pokuöamo s crnim?
{165030}{165100}Izgledi moraju da se poklope, zar ne?
{165101}{165148}Izgledi?|- Izgledi.
{165149}{165232}OK. Izgledi. U redu.
{165264}{165371}35, crno.
{165373}{165422}OK.|3000, crveno.
{165632}{165696}Haljina je prava, a la Bardo.
{165735}{165805}Poznavao sam Briûit Bardo.|- Kladim se da jeste.
{165901}{166022}Ne ûelim da odem,|a da ne pozdravim Grejs.
{166024}{166111}To nije u redu.|- Zasluûuje ona bolje od nas.
{166157}{166220}Svakako boljeg od tebe.
{166298}{166381}Po onome kako udaraö,
{166383}{166447}poËinjem da poötujem pedere.
{166448}{166547}Vinse, Vinse, ja nisam peder, znaö?
{166549}{166601}To je primitivan naËin razmiöljanja.
{166603}{166743}Ne, ne, ne, ne. HoÊu reÊi, da jesi peder,|da jesi, bilo bi OK.
{166744}{166820}Da si peder.
{166999}{167088}Rudi, izbaci kuËku odavde.
{167226}{167297}Obezbeenje.|- Da gospodine?
{167326}{167396}Izbacite kuËku.|- Ne dirajte me!
{167565}{167661}Pustite me na miru.
{167711}{167805}Momci, Ëekajte. Kuda Êete?
{167863}{167921}Idi pozadi, ja vozim.
{167923}{167983}Da, da.|- »uo si me, pozadi.
{167985}{168043}Pozadi.
{168520}{168608}Grejs, bila si na zabavi?
{168610}{168686}Nije mi se svidela.
{168780}{168862}Zaöto bogati misle da Êe|svaka spavati sa njim?
{168864}{168946}Bolje siromaöan koji ume da vodi ljubav...
{168947}{168994}nego bogataö koji ne ume.
{168995}{169055}Greöim?
{169056}{169103}Ne.|- Moûda ne baö siromaöak,
{169104}{169189}moûe osrednje dobrostojeÊi.
{169191}{169266}Osrednje dobrostojeÊi|koji dobro kreöe...
{169267}{169360}i ne boji se ûene|koja ûeli sopstvenu firmu.
{169362}{169450}Da.|- Moram da budem svoj gazda. To ûelim.
{169451}{169567}Moram da radim za sebe.|äefove samo ûelim da mlatim.
{169568}{169623}Da vidim.
{169625}{169751}Uz sve ove moje ideje,|potraûiÊu novac u L.A.
{169753}{169822}Dopada mi se L.A.|- Da.
{169823}{169891}VeÊini ljudi se ne dopada,|ali meni se svia.
{169893}{169989}A vrlo siromaöan tip|koji osrednje dobro kreöe?
{169991}{170062}Samo pitam.
{170097}{170151}Gde ste vi bili?
{170153}{170247}Ja sam se muvao kraj bazena,|priËao sa ljudima.
{170249}{170323}Je li ti iöta ostalo?|- 13.000.
{170325}{170443}Joö mi dugujeö 5.|- Mogu li da vratim dve i da ti ostanem duûan?
{170444}{170496}Naravno.|- Dobro je.
{170498}{170575}Ja imam 11.000.|Prokleti Vinsov sistem.
{170577}{170632}Hej, hej.|Posmatraj ovako.
{170634}{170703}Taj novac juËe ujutru, nismo ni imali?
{170704}{170776}Da.
{170916}{170974}Grejs,
{170975}{171059}öta misliö ko je pobedio,|Vins ili ja?
{171061}{171154}Mislim da je odluka poötena.
{171239}{171310}Poötena.|- OK. Dobro.
{171311}{171403}Jesi li Ëuo kako su nas ljudi bodrili?
{171404}{171478}Sjajno, zar ne?|- Ludilo, jebote.
{171480}{171552}Bilo je sjajno.
{171554}{171623}Da.|- Bilo je sjajno.
{171624}{171675}Da.
{171780}{171840}Volim vas, momci!
{171950}{172050}Kraj
{172150}{173150}Movie by KOSTA ZULU LESKOVAC
{173175}{174675}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3bawh|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
