{25}{175}–ü–æ–¥—Ä–∂–∏—Ç–µ –Ω–∞—Å –∏ –ø–æ—Å—Ç–∞–Ω–∏—Ç–µ VIP —á–ª–∞–Ω –¥–∞ –±–∏—Å—Ç–µ —É–∫–ª–æ–Ω–∏–ª–∏ —Å–≤–µ –æ–≥–ª–∞—Å–µ —Å–∞ www.OpenSubtitles.org
{1730}{1804}Ovo je Ëetvrti kvart|Bronksa.
{1805}{1888}Moj dom, svet za sebe.
{1904}{2000}Odavde se do svakog bara|stiûe za 15 minuta,
{2000}{2098}ali daljina moûe biti izraûena|i u hiljadama milja.
{2118}{2255}To su zvona crkve koja su|odzvanjala po susedstvu.
{2573}{2686}Bila je 1960. i pesma|je prekrivala ulice.
{2779}{2885}Vokalne grupe|na svakom Êoöku.
{2981}{3044}Kakvo vreme!
{3091}{3194}Njujoröki Jenki je igrao protiv|Pitsburökog tima u svetskom kupu.
{3194}{3285}A Miki Menson je bio|oliËenje Boga za mene.
{3285}{3353}Otac me je vodio na|Jenki stadion,
{3353}{3441}da gledamo kako Jenki|u finalu osvajaju kup.
{3478}{3646}Ovo je "äiz Bipi", gde su momci|izlazili, ali o tome kasnije.
{3754}{3854}Ovo je moja zgradi,|Zivim na treÊem spratu.
{3860}{3964}87. ulica, broj 667.
{4016}{4093}Moje stepeniöte.
{4148}{4256}U vrelim letnjim noÊima,|tu bi se skupljali.
{4264}{4338}To je bilo sastajaliöte|ljubavnika.
{4344}{4479}Mari, upadaj u jebena kola!|-NeÊu.
{4485}{4619}Upadaj! -Ostavi me na miru!|-Ma hajde. Volim te.
{4626}{4719}Sereö.|-Ulazi u jebena kola!
{5005}{5141}TaËno ovde, kod ovog stuba,|vidite vrlo vaûnog Ëoveka.
{5143}{5231}Tip broj jedan u kraju.|Sani.
{5251}{5404}Svi su ga voleli kao Boga.|To je i bio u kraju.
{5474}{5599}Ja sam ga gledao|od jutra do mraka.
{5626}{5719}On me nije primeÊivao.|Nikada!
{5725}{5794}Sve do jednog dana.
{6090}{6185}Ima li mesta za nas?|-Briöi!
{6675}{6784}P R I » A   I Z|B  R  O  N  K  S  A
{10496}{10575}To je moj otac,|Lorenco.
{10583}{10693}Voleo sam da se vozim|busom s njim.
{10735}{10835}Ovo sam ja.|Imam devet godina.
{11444}{11508}Vidmo se. -U redu.
{11745}{11829}Pravo kuÊi. -U redu, tata.
{11834}{11922}To je moja mama|Rozina.
{11929}{12059}Oni su se upoznali na plesu|i od tada su zajedno.
{15390}{15504}Ovde su se momci|okupljali.
{15590}{15729}Toni Tupe je vaûio za vlasnika.|U stvari, bar je bio Sanijev.
{15836}{15936}Toni je bio zbunjeni pevaË.|Svi su mrzeli njegov glas.
{15936}{16041}Ipak, niko nije Ëuo Tonija|da govori, samo je pevao.
{16064}{16209}Zvali su ga Tupe, jer je imao|najgoru periku na svetu.
{16291}{16436}Edi Moso je bio kockar öiroke|ruke i najveÊi gubitnik uopöte.
{16436}{16565}Zvali su ga "Suvi", jer bi svemu|doneo nesreÊu Ëega bi se takao.
{16585}{16730}Iöao je na trke i kladio se|na rage.  -Jenki su izgubili!
{16774}{16889}Da nema loöe sreÊe,|ne bih znao ni za kakvu.
{16906}{17020}–oro debeli, za koga se|govorilo da se moûe videti
{17026}{17169}kako je za sat vremena provedenog|sa njim, joö sala nabacio.
{17176}{17320}Po jednoj legendi, njeova je senka|pala na nekog psa, i ubila ga.
{17365}{17441}Njega su zvali "Frenki kafa",
{17449}{17549}jer mu je lice bilo tvrdo|i hrapavo kao zrnce kafe.
{17549}{17650}Trebalo je hrabrosti da se|suoËi s njegovim pogledom.
{17964}{18027}Kako je, mali?
{18075}{18195}Ovaj se zvao "Dûimi öapat",|i bio je Sanijeva desna ruka.
{18204}{18315}Tako su ga zvali, jer je za|njega sve bilo tajna.
{18451}{18551}Deni i Bobi su ötitili|njegova lea.
{18556}{18672}»inili su jaku Sanijevu ekipu.
{18680}{18796}Njih niko nije smeo|da zajebava.
{18801}{18920}äta radiö ovde? Koliko sam ti|puta rekla da tu ne zalaziö!
{18920}{19007}Tata ti je rekao da ideö|pravo kuÊi!
{19011}{19129}Traûio sam tatu....|-Traûio si tatu? Baö lepo!
{19211}{19336}Ovde me Ëekaj i ne mrdaj|dok se ne vratim iz radnje!
{19348}{19402}»ujeö li me?
{19454}{19574}Trudio sam se da|podraûavam Sanija,
{19580}{19642}ali me i dalje nije|zapaûao.
{19703}{19827}Imao je pet prstiju,|ali je samo tri koristio.
{19903}{19975}Hajde, idemo kuÊi!
{20231}{20347}Ne jede mi se ovo.|-Ne? Ne jede ti se meso?
{20355}{20488}Znaö koliko puta moram da vozim|gore dole da bi ovde bilo mesa?
{20495}{20594}Sedam puta. -Otkud znaö?|-Brojao sam.
{20600}{20697}Otac ti govori!|-Svestan sam toga.
{20703}{20842}Majka kaûe da si bio u baru?|-Nisam. -Kaûi istinu ocu!
{20848}{20947}Rekao sam. -äto laûeö?|-Samo sam gledao.
{20952}{21065}Treba neöto da preduzmeö.|-äta se tu moûe. -Hvala, tata.
{21072}{21118}Ali...
{21125}{21218}U naöoj je zgradi,|kako da se izbegne?
{21223}{21326}Dobro tata kaûe. Sluöaj ga.|-Tebi niko niöta ne kaûe!
{21331}{21381}Dodaj mi tanjir.
{21390}{21453}»uj me dobro!
{21465}{21525}U bar ne smeö da ulaziö!
{21525}{21620}Na stepeniöte moûeö,|ali u bar, ne.
{21626}{21703}Je li ti jasno, zaöto?
{21708}{21836}Kad si mene video tamo?|-Tebi mama ne da.
{21837}{21925}äta da mu radim?|-Nemam pojma.
{21925}{21997}äalio sam se, neÊu viöe.
{22125}{22248}Vidi ovo! Dve karte za|Jenkije na centru.
{22253}{22382}Iza Mika? -Iz broja sedam.|Sad jedi meso.
{22580}{22682}Stari koËijaö je svakog|psovao.
{22713}{22801}Zarekli smo se da|ga bijemo.
{22878}{22976}Moji najbolji drugovi su bili|"Zaliz" i "Ludi Mario".
{22982}{23118}Zaliza su tako zvali zbog kose,|a Ludog, zato jer je bio lud.
{23178}{23270}Nanu li vam naninu.
{23350}{23428}Ne diraj mi voÊe!
{23502}{23601}Ko vas tako puöta?
{23855}{23951}UhvatiÊu ja vas!
{24223}{24316}O, momci,|opet neka frka.
{24346}{24416}Probajmo i mi.
{24742}{24825}Opet "Dûimi öapat"...
{25286}{25351}Imitiraj nekog teûeg,
{25358}{25423}Probaj "Frenkija kafu".
{25432}{25497}Ne umem njega.
{25510}{25586}Koju facu ima!
{25717}{25748}Sranje!
{25770}{25857}Koji su oni öto se|kaËe na bus?
{25863}{25978}Nisu odavde, idu u ökolu.|-Otkud ti znaö?
{25983}{26115}Rekao mi je Êale. -Meni je Êale|rekao da se tako poËinje.
{26165}{26351}Beûi odavde, Crnjo!|U Australiju odakle si doöao!
{26710}{26753}Zaöto!?
{27157}{27248}Ma, odjebi i briöi odavde!
{27255}{27341}Niko nikog ne jebe!
{27452}{27562}äta radiö, jebo te ja!|-Jebi se, majmune!
{27575}{27678}Sad Êeö da vidiö,|jebivetru!
{28177}{28254}Sani, daj mi piötolj.
{28276}{28322}Skloni kola!
{28353}{28413}Dolazi!
{28702}{28822}Kad me je Sani pogledao|prvi put, sledio sam se.
{28837}{28937}Jedino sam video njegovu|ruku i piötolj.
{29557}{29609}äta je, tata?
{29681}{29784}äta je bilo, je li dobro? -Tata,|to je samo kazna za parking.
{29798}{29924}Je li u redu?
{29924}{30026}Duöo, jesi li dobro? -U redu je.|Idemo unutra. -Jesam, mama.
{30026}{30109}O, moj Boûe,|baö sam se uplaöila!
{30173}{30272}Tata, moûeö li da razumeö?|To je bilo zbog parkinga.
{30272}{30366}Zbog parkinga? -Ali zaöto?|-Nije zbog parkinga,
{30366}{30454}nego je naiöao|u pogreönom trenutku.
{30454}{30541}O Ëemu se radi?|Mogao je biti ubijen!
{30541}{30651}Ne meöaj se, to je glavno.|-Kako neko moûe to da uradi.
{30731}{30869}Ko je? -Policija.|Stanujete li ovde?
{30897}{31023}äta vam treba?|-Pitali bi vas neöto.
{31047}{31171}A öta?|-Otvorite nam vrata!
{31322}{31444}Ja sam detektiv Belsan.|Ovo je moj pomoÊnik.
{31453}{31527}Kako je, sine? Gospoo?
{31534}{31623}Hteli bi da vaöeg sina|pitamo. -Za öta?
{31623}{31746}Bilo je pucanja pred zgradom,|a mislimo da je mali bio tamo.
{31746}{31843}Stvarno? On niöta ne zna.|-Neki su ga videli napolju.
{31843}{31927}E, pa oni greöe.|On niöta ne zna.
{31927}{32018}Mi moûemo lepim,|a moûemo i drugaËije...
{32022}{32141}On nema pojma...|-Ja znam sve.
{32253}{32327}Deci se stvari priËine.
{32334}{32483}Ne zameramo vam, znamo da|je bio dole, pa poite sa nama.
{32509}{32607}Sine, sluöaj! HoÊemo da|uradiö neöto za nas.
{32614}{32759}SiÊi Êeö sa nama|i svojim ocem dole,
{32767}{32863}i reÊi nam koga si video|s piötoljem u ruci.
{32869}{32954}To je sve. Moûeö li to?
{33261}{33301}Da.
{33334}{33449}Dobro. Idemo onda.|G. Dono, idete s nama.
{33499}{33631}HoÊe li biti sve u redu?|-Sve Êe biti u redu.
{33631}{33702}VraÊamo se za dva|minuta.
{35353}{35408}Okrenite se.
{35491}{35546}Skinite öeöire!
{35573}{35688}Hej, digni glavu!|Gledaj pravo!
{35712}{35762}Je li on?
{35987}{36083}A ovaj? Gledaj pravo!
{36197}{36309}Stoj uspravno! A ovaj?
{36349}{36432}Odgovori mi. Je li on?
{36576}{36659}Da li je ovaj bio?
{36727}{36827}Je li to on? Odgovori mi.
{36943}{37032}Gore pogled.
{37041}{37127}Da li je ovaj?
{37279}{37335}Idemo dalje.
{37343}{37417}Ovamo gledaj. Gore glavu!
{37423}{37477}Gledaj me! Tako...
{37482}{37540}Je li on?
{37728}{37809}Vidi ovog, öta je sa njim?
{37854}{37959}Drûi pravo glavu!
{37974}{38034}äta je s njim?
{38047}{38107}Je li on?
{38533}{38604}Odgovori mi.
{38672}{38765}Nije. -Zadovoljni?|-Nisam.
{38768}{38870}Rekao je öta je znao.|-Ne zna niöta, to sam veÊ Ëuo.
{38872}{38972}Rekao je da ne zna...|-Znaö öta, proöetaj.
{39200}{39274}Sad se svi gubite!
{39462}{39540}Preöli smo ih. -Jesmo.
{39554}{39679}Nisam lagao. Nisam.|-Nisi.
{39707}{39808}Dobro sam uradio?|-Jesi, jesi.
{39814}{39909}Dobro delo loöem|Ëoveku.
{39918}{40043}Dobro delo loöem Ëoveku?|To nisam razumeo.
{40113}{40240}Znam da bi me svi ostavili|da sam cinkario.
{40247}{40278}A nisam.
{40770}{40915}Tata, zaöto si rekao da sam uradio|dobru stvar za loöeg Ëoveka?
{40920}{41085}Jer nekada Ëovek Ëini stvari|za koje zna da su pogreöne.
{41107}{41170}Razumeö li öta govorim?
{41188}{41312}Ne, ali kaûem ti. Mislio sam|da sam uradio dobro.
{41317}{41384}A sad viöe nisam siguran.
{41390}{41482}I jesi, a kad porasteö,|shvatiÊeö öta.
{41483}{41569}Mama i ja te mnogo|volimo.
{41708}{41785}Sutra te vozim?
{41904}{42014}Siti Ajlend je bio poslednja|stanica na tatinoj liniji.
{42014}{42135}Tamo sam voleo da idem,|kao na izlet.
{42178}{42290}Sluöao se dûez i priËalo|o bejzbolu.
{42447}{42575}Tata, mogu li na sladoled?|-Prvo naö posao, pa onda.
{42605}{42652}U redu, tata.
{42805}{42863}O kojoj igri je reË, tata?
{42867}{42942}Hajde da dobro uradimo|posao danas.
{42944}{43023}Da vidimo. Ko je poslednji|osvojio tri prva mesta?
{43030}{43152}Miki Menson.
{43160}{43220}Deni Edvards.
{43227}{43313}Vrlo dobro, sine. -To je|bejzbol, tata. Sve znam.
{43429}{43530}Jenki Klipersi imaju 56|meËeva bez poraza.
{43539}{43579}TaËno.
{43579}{43670}To niko neÊe nadmaöiti,|je li tako? -Tako je.
{43670}{43769}Zaöto je Dûo Bin bio najbolji?|-Jer je Italijan.
{43777}{43910}Ima i toga. -Nego zaöto?|-Zato öto je bio najtalentovaniji.
{43914}{43974}Talentovan? -Tako je.
{43992}{44130}Imam li ja toga? -Itekako!|Najviöe na svetu.
{44144}{44268}HoÊu li i ja postati bejzbol igraË?|-BiÊeö ono öto budeö ûeleo.
{44283}{44398}Najtuûnije je kad se talenat|protraÊi. Moûeö imati veliki
{44398}{44495}talenat, ali ako ne uradiö|pravu stvar, ne pomaûe niöta.
{44495}{44590}Ali ako uradiö pravu stvar,|deöavaju se dobre stvari.
{44590}{44705}Shvataö? -U pravu si.|-A sad na sladoled.
{44969}{45045}Super.
{45095}{45143}Pritisni. U redu?|-Da.
{45216}{45277}TraÊenje talenta.
{45278}{45372}O tome mi je otac govorio|Ëitavog ûivota.
{45388}{45484}Poûuri, da stignemo|na poËetak.
{47018}{47060}Idem.
{47253}{47363}Pravo kuÊi i sluöaj|prenos utakmice.
{47370}{47456}Idi gore, da ja ne izaem!
{47729}{47819}Nastavi da voziö! HoÊu neöto|da ti kaûem.
{47875}{47994}Cenimo öta je tvoj sin uËinio.|Dobar ti je mali. -Hvala.
{47994}{48118}Zahvalni smo ti zbog toga.|-Samo da sve ispadne dobro.
{48126}{48251}Mi ûelimo tebi da se oduûimo.|äto da stalno voziö bus?
{48258}{48331}Kod nas bi imao|150$ nedeljno.
{48331}{48430}Hvala, ali ne bih|da izgubim ovaj posao.
{48436}{48563}A to i nije za mene. -Razmisli.|-Nije to za mene.
{48569}{48706}Stopedeset dolara bi ti dali.|-Ne bih ja to umeo.
{48716}{48846}Sani Êe se razoËarati kad|mu kaûem. -U redu.
{48855}{48936}Zaustavi da siem.
{49488}{49591}Danas su mi nudili posao.|-äta?
{49600}{49715}Da raznosim za njih.|Nekakve papire.
{49715}{49778}Za stopedeset nedeljno.
{49781}{49844}150 nedeljno? äta si rekao?
{49849}{49943}Opasno je. Nije za mene.
{50046}{50086}äta?
{50120}{50246}Ne znam.|150$ nije mala para.
{50253}{50349}äta priËaö? -Ne znam.
{50380}{50518}Kad poËneö s njima,|onda sve ide i dalje...
{50531}{50580}Ne znam...
{50854}{50918}Moûda si u pravu.
{50924}{51005}Idem do dece.
{51024}{51068}Doi...
{51135}{51244}Nije ti ûao öto si se udala|za vozaËa busa?
{51258}{51383}Tako sam te upoznala.|-Da...
{51600}{51690}OseÊao sam se bedno.
{51698}{51838}Video sam kako umire Ëovek|i Ëinio sam smrtni greh.
{51846}{51939}Pitao sam se hoÊe li|mi Bog oprostiti.
{52219}{52284}Treba mi oproötaj, oËe!
{52294}{52400}Doöao sam da se ispovedim|i priznam svoje grehove.
{52418}{52530}éao mi je öto sam ubio Ëoveka|i öto me sada mrze zbog toga.
{52551}{52608}»ekaj malo!
{52615}{52690}Moûeö li sve ispoËetka?
{52735}{52819}Mislite, kako sam se uplaöio?
{52826}{52881}Ne. Joö malo unazad.
{52886}{52989}O noÊi kada se desilo ubistvo?|-Da, o tome.
{52996}{53103}Da li shvataö öta si rekao?|-Desilo se samo jednom, oËe.
{53113}{53221}Znaö li koja je peta?|-Naravno.
{53228}{53360}To je redni broj.|-Peta Boûja zapovest!
{53369}{53421}Ne ubij.
{53458}{53571}Tako je. Sada mi kaûi|öta se desilo.
{53581}{53771}Nikome to neÊu priËati.|-Ne boj se, jer Bog je najjaËi.
{53793}{53971}Vaö Bog je jaËi od mog gore,|a ovde dole moj Bog je jaËi.
{54082}{54210}U pravi si. Pet OËenaöa i pet|Zdravo Marija za oproötaj.
{54213}{54317}Za ubicu? Nije mnogo.|-äta reËe!?
{54364}{54455}Bilo je divno biti katolik|i ispovediti se.
{54455}{54549}Moûeö da poËneö ispoËetka|svake nedelje.
{54818}{54864}Mali!
{54966}{55047}Ostavi to i doi.
{55559}{55650}Evo ga deËko, Sani.
{55972}{56019}Kako je?
{56064}{56116}Dobro.
{56162}{56247}Gledao si me u lice.
{56289}{56335}Da.
{56362}{56429}Bojiö li me se?
{56444}{56520}Ne. -Dobro.
{56526}{56592}Kako se zoveö?
{56597}{56636}Kaloiro.
{56691}{56796}Krupno ime.|Ima li nadimak? -Ne.
{56827}{56930}Kako te zovu drugovi?|-Kloo.
{56939}{56994}To veÊ moûe.
{57011}{57140}Navijaö za Kliperse?|-Da.
{57164}{57201}Sedi.
{57264}{57356}Ovde, sa mnom.
{57521}{57620}Je l* se jedeö öto su|Jenki izgubili?
{57627}{57794}Veliki Berovski! Mrzim ga!|Naterao je Miki Mena da plaËe.
{57799}{57942}Novine kaûu da je Miki plakao.|-Miki Men razoËaran? Zaöto?
{57946}{58044}On zarauje hiljade dolara|godiönje. A tvoj tata?
{58047}{58189}Ne znam. -Ne znaö?|Nema ni stan da plati.
{58189}{58245}Kaûi to Mikiju.
{58250}{58361}Ne brine on za tebe,|ne moraö ni ti za njega.
{58434}{58531}Da te pitam neöto?|-Hajde.
{58562}{58695}Jesi li ubio onog Ëoveka|zbog parkiranja?
{58797}{58890}Kad porasteö, shvatiÊeö.
{59017}{59156}Od tog dana, drugaËije|sam mislio o Jenkijima.
{59767}{59860}Provodio sam sa Sanijem|sve viöe vremena.
{59881}{60002}Dolazio sam iz ökole,|kriöom.
{60010}{60115}Posluûivao sam momke|i uzimao baköiö.
{60504}{60564}Neverovatno!
{60599}{60760}Hajde, Sani. Pusti mene.|-Ma, znaö öta Êe se dogoditi.
{60766}{60862}OseÊam da mogu. OseÊam.
{60879}{61000}Ulazim, ulazim.|-Daj mu kocke!
{61317}{61421}Hajde, kockice! Uradite neöto.|Mojoj bebici su potrebne cipele.
{61699}{61800}U ûivotu nije dobio.
{61859}{61936}Daj te kockice.|Gde je mali?
{61957}{62066}Sani, uËini mi uslugu.|Da dobijem svoj deo.
{62080}{62181}Gde je mali?|Neka on baca.
{62296}{62412}Ima li neko neöto protiv?|-U redu je. Nema problema.
{62481}{62591}Hajde! Bacaj za mene.|-Ja se ne kockam.
{62596}{62705}U redu, samo mene sluöaj.|Radi öta ti kaûem.
{62742}{62852}Hajde, uloûite!
{63101}{63235}Odmakni se malo i|ne duvaj po meni.
{63245}{63368}Hej, –oro, opusti se!|-Sani nije ovde sam. I ja igram.
{63406}{63502}Da udare u zid. Ti to moûeö.
{63561}{63662}Prolaz, prolaz,|za moju lovu, Sani.
{63662}{63762}NeÊu tvoj novac za mene.|-äta fali mom novcu?
{63763}{63846}Kaûem ti da ga neÊu!|-Ali zaöto?
{63846}{63933}Ti si jebeni baksuz,|eto zaöto.
{63940}{64012}Nek ostane tamo...
{64136}{64223}Jebeni gubitnik!|-Baksuz.
{64435}{64500}Baci ih da udare u zid!
{64766}{64838}Hiljadu u stranu.
{65096}{65147}Moûeö ti to...
{65166}{65287}–oro, ne duvaj mi viöe.|Zabole me glava!
{65293}{65416}Ubi me promaja!|Prestani da duvaö!
{65416}{65465}Izbaci ga u komoru!
{65468}{65566}Sani, ne moûe. Debeo je.|-Boli me dupe! Nosi se!
{65915}{65957}Baci ih!
{66035}{66091}»etvorka.
{66450}{66546}Stavljam 500 $.
{66710}{66838}Na malog. Da Êe baciti|Ëetvorku.
{66846}{66958}NeÊe moÊi. Nikad.
{66968}{67023}Moûeö ti to.
{67030}{67147}Ne brini se, bacam sedmicu.|-Ne sedmicu!
{67253}{67342}Nemoj da mu se|neko smeje!
{67353}{67416}Sedmica ne valja ovde.
{67416}{67475}Bacaj da udari u zid!
{67475}{67557}Moraö da zaradiö poen.|Moûeö ti to!
{67561}{67665}Ne, ne! Lice "Frenki kafa"|nije dobro.
{67665}{67763}NeÊu da ga tvoja faca gleda,|dok baca kocke.
{67811}{67942}Dûimi, izvedi ga!|-Sani, zaöto da izaem.
{67967}{68067}Vodi ga! -»ekaj, Dûimi.
{68068}{68160}Uloûio sam novac.|-Izvedite ga napolje!
{68491}{68673}Vidiö one pare?|Ti Êeö dobro da baciö.
{68826}{68958}Nemoj da kenjaö,|baciÊu dobro.
{69150}{69213}Ne verujem oËima!
{69235}{69352}11. Imao sam 11 dobitaka|za redom.
{69391}{69508}Ne znam koliko,|ali Sani je puno dobio.
{69656}{69778}Uvek je govorio da je Belmont|Avenija najbolja ökola ûivota.
{69785}{69947}Sticao sam dvostruko obrazovanje.|Jedno na ulici drugo u ökoli.
{69948}{70041}Bio sam duplo pametniji|od ostalih.
{70442}{70481}Mali!
{70501}{70582}Bio si dobar. -Hvala.
{70676}{70735}To je sve?
{70850}{70900}U redu?
{70930}{71021}Sad kuÊi, kasno je.|-Vidimo se, Sani.
{71157}{71233}»uj!
{71261}{71346}Moramo neko ime|da ti damo.
{71365}{71517}Od sada se zoveö Si. -Si?|-Tako je. Si. Sad kuÊi!
{71632}{71738}Sani me je svuda vodio|i predstavljao kao svog.
{71742}{71835}PoËele su Ëudne stvari|da se dogaaju.
{71842}{71931}Kaloiro, doi.
{72017}{72065}Zovem se Si.
{72078}{72152}Si, htedoh reÊi.
{72159}{72258}Kako si mi danas,|deËko? -Dobro.
{72267}{72389}Nosi ove breskve mami.|-Nemam para danas.
{72396}{72446}Nije vaûno.
{72491}{72583}BiÊe mi neprijatno, ako|joö jednom to kaûeö.
{72616}{72758}Samo kaûi Saniju da sam|pazio na tebe.
{72886}{73012}Tada sam shvatio da je|to sve zbog Sanija.
{73029}{73088}Dopadalo mi se.
{73089}{73153}To mi se veoma|dopadalo.
{73323}{73394}Vidi öta sam dobio...
{73732}{73812}äta je ovo? -Koje, tata?
{73836}{73913}Odakle ti?|Mama je naöla u fioci.
{73921}{74019}Uötedeo sam...|-600 dolara si uötedeo?
{74027}{74109}Preko noÊi si postao|hirurg?
{74111}{74211}Reci ocu odakle ti novac!|-Zaradio sam.
{74213}{74331}Na Ëemu? -Stvari...|-äta to znaËi? Koje stvari?
{74339}{74404}Razne stvari... -Koje?
{74443}{74557}Nemoj da me laûeö,|neÊu se ljutiti.
{74567}{74667}ObeÊavaö? -Otac sam ti,|valjda mi verujeö?
{74732}{74824}Igrao sam sa kockama|i dobio baköiö.
{74824}{74909}Kockice! -Kakve kockice?!
{74916}{75007}Kakve kockice, pitam te!
{75016}{75126}Rekao si da se neÊeö ljutiti.|-Lagao sam. Sada govori!
{75126}{75233}Radio sam za Sanija i on me|je Ëastio. -Znao sam.
{75236}{75348}Koliko sam ti puta rekla...?|-Ja radim tamo, mama.
{75353}{75441}Radiö, öta?|Ne bi smeo ni da ueö!
{75443}{75528}Ovo vraÊam dole.|-»ekaj malo.
{75533}{75673}Zaöto? O Ëemu priËaö?|-To bi nam dobro doölo.
{75692}{75826}Za öta? Takav novac mi ne treba!|Odakle je doöao, tamo ide.
{75827}{75909}Razmisli malo... -Gotovo!|Idemo.
{75912}{75983}äto tako ideö, vrati se...
{75999}{76069}Lorenco, molim te!
{76131}{76181}Lorenco!
{76416}{76456}Lorenco!
{76502}{76569}Lorenco, molim te.
{76818}{76908}Je li Sani tu? -Pozadi.
{77252}{77381}Ne moûemo ovo da uzmemo.|-Nisam tebi ni dao, nego malom.
{77386}{77508}Da, mom sinu. NeÊu da se on|u ovo uvlaËi. -äta ti je?
{77513}{77606}äta priËaö?|-Ja nisam glup Ëovek.
{77611}{77726}Nema razgovora o ovome.|Samo mi ne diraj malog!
{77729}{77821}Si, izai da razgovaram|sa tvojim ocem.
{77822}{77927}Ja Êu mu reÊi.|Kloo, Ëekaj napolju.
{77996}{78119}Prvo, ja te poötujem jer si Ëovek|na svom mestu i moj komöija.
{78119}{78241}Ali tako mi se viöe ne obraÊaj.|Sin Êe ti iÊi u ökolu, koledû....
{78248}{78378}Znam öta on vidi.|Odela, kola, lovu, sve...
{78398}{78521}Bacio je sliku Mikija Mena,|jer mi ne bi platio kiriju.
{78547}{78598}Dobar je.
{78641}{78771}Nije smeöno kad ti sin ima|viöe para od tebe, sa 9 godina.
{78778}{78878}Ja sam ti nudio posao. Odbio si.|-Tako je. I sada odbijam.
{78883}{78958}Sina mi jedino pusti!
{78958}{79051}Ja sam sa njim kao sa|roenim sinom.
{79054}{79178}On je moj sin, a ne tvoj! -äta?|-Moj sin! -Teraj se odavde!
{79178}{79283}Ne bojim te se! -Trebalo bi!|-Znam na öta si sposoban.
{79286}{79399}Nikad ne bih prekoraËio crtu,|bar me ovde svi znaju.
{79399}{79497}Ovoga puta nisi u pravu. Sa|mojom porodicom se ne zezaj.
{79497}{79584}To je moj sin, ne tvoj.|-HoÊeö da me bijeö?
{79584}{79677}Samo se mani mog sina!|-Beûi da te ne raspizdim!
{79677}{79768}Drûi se dalje od mog sina!|-Hajde, probaj!
{79772}{79836}Dalje od mog sina!|-Napolje odavde!
{79836}{79975}Kako si mogao, to su moje pare.|-To je nevaljao novac i neÊu ga!
{79975}{80069}Zaradio sam ga...|-Rekoh da ti to ne treba!
{80069}{80159}Tata, sluöaj me....|-Dalje od njega, Ëujeö li!?
{80163}{80279}»ujeö li ti mene!|-Dalje od njega, razumeö?
{80287}{80384}Sani je bio u pravu. Ti|ne razumeö. On je super.
{80384}{80477}Pogreöno! Ne treba mnogo|snage za pucanje.
{80477}{80568}Ali neka on proba da svako|jutro ustaje, da radi!
{80568}{80659}Za to treba biti radni Ëovek!|To je pravi frajer.
{80659}{80774}Radnici su frajeri, kao tvoj otac!|-Njega svi vole, kao öto
{80779}{80899}vole i tebe u autobusu. To je isto.|-Nije isto. Ne vole ga.
{80899}{80989}Njega se svi plaöe.|To je velika razlika.
{81247}{81323}Izvini za öamar.
{82094}{82155}HoÊeö li da ga sredim?
{82163}{82223}Ne, pustiÊemo ga.
{82250}{82345}Sani i moj otac nikada|viöe nisu razgovarali.
{82352}{82449}Nisam oca posluöao da|izbegavam Sanija.
{82454}{82548}Odlazio sam tajno,|kad god bih mogao.
{82568}{82697}Proölo je 8 godina|i Sanijeva moÊ je narasla.
{82707}{82820}Postao je bos,|a ja njegov drug.
{82954}{83098}TRKA»KA STAZA "AKVADUKT"|1968.
{83259}{83387}Sada je 1968. Bitlsi su|promenili naö ûivot.
{83394}{83544}Jenki su napustili svoje mesto,|a mene nije bilo briga.
{83553}{83687}Svuda su bile promene,|osim u naöem kraju.
{83942}{84057}Jesi li uloûio?|-Da, na Kriptanita.
{84155}{84213}Hajde, brûe!
{84264}{84335}Napred, Kriptanit!
{84367}{84430}Sjajno trËi.
{84484}{84564}Nema öanse da izgubi.
{84798}{84863}Gotovo je.
{84939}{85065}Napred, Kriptinat!|Napred....
{85268}{85365}I on se na njega kladio!
{85388}{85467}Daj mi te tikete!
{85629}{85730}PobediÊe naö konj, Sani!|-Sad nema öanse.
{85864}{85954}Urekao nas je Suvi.
{86298}{86363}Ne, neee!
{86370}{86425}Sranje!
{86432}{86500}Jebeni konj!
{86518}{86614}Jebem ti takvog konja!
{86623}{86735}SledeÊu za tebe dajem.|-Jebi se!
{86770}{86842}Mnogo si osetljiv.
{87363}{87455}Najzad smo imali|svoj klub.
{87462}{87535}Nazvali smo ga|"Divlji parovi".
{87539}{87630}Svako je morao da uloûi|dva boksa cigareta.
{87634}{87723}Jedino öto smo radili je da|smo visili tamo.
{87727}{87858}Visili smo tamo dan i noÊ.|Niko nije hteo da ide kuÊi.
{87865}{87998}Svo vreme provodio sam tamo|da ne bi neöto propustio.
{88157}{88250}Gledajte ovo, momci!
{88367}{88445}Svrati!
{88707}{88809}Ovakve ribe su jebene|kurave.
{88818}{88881}Kako znaö?
{88888}{88970}Jebi se, Si!|-Pitam otkud znaö!
{88978}{89072}Na mom testu ne bi proöle.|-Koji test? -Da li ima ime?
{89072}{89204}Da znaö da li valja da je|ûeniö, daj je na test.
{89211}{89324}To je "Mariov test".|-Kakav je to test?
{89331}{89443}Ovakvu bi vozio kolima,|zar ne?
{89449}{89570}Kad izaeö na autoput, prii|uz neki od onih kamiona
{89576}{89668}i uradi sve da skreneö|paûnju kamiondûiji,
{89668}{89773}trubi mu, uradi bilo öta.|Budi siguran da gleda.
{89793}{89888}U isto vreme, njoj stavi|ruku iza glave
{89888}{90021}i guraj je na dole,|sebi do gaÊa.
{90054}{90141}Ma, hajde!|-Super je, verujte.
{90148}{90260}Ako ona poe tamo, a zna|da je kamiondûija vidi,
{90260}{90349}onda je kurava i nemoj|da je ûeniö.
{90349}{90474}Nema to veze.|-Ti si bolesni manijak.
{90483}{90588}Znam ja, one öto sa rukom,|prebace kosu, pusti...
{91104}{91270}Ovaj Niki po sedmi put prolazi.|-äta ti smeta, ne izlazi iz kola?
{91278}{91358}Smeta meni!|-Ne izlaze, ne smetaju ti.
{91366}{91448}Zaöto se vozikaju ovuda?|-Moûda zbog riba?
{91454}{91558}Nije im mesto ovde i taËka.
{91564}{91655}Niko ih nije zvao.
{91711}{91799}Palicu u glavu.
{91959}{92153}Lui, gde je moja lova?|-Moram neöto da uradim...
{92166}{92265}Duûan mi je 20 dolara,|dve nedelje.
{92271}{92344}To nije zauvek.
{92349}{92400}Govno jedno.
{92675}{92829}Idem do Êaleta, vraÊam se.|-U redu. -Vidimo se.
{93038}{93160}Poi sa mnom.|-Moram li? -Hajde.
{93415}{93475}Ovde sedi.
{93724}{93816}Moram li ovo da sluöam?|Puca mi glava.
{93823}{93924}Vi danaönji klinci ne znate|öta je prava muzika.
{94319}{94369}Kaloiro?
{94400}{94451}Kloo?
{94494}{94548}Sluöaö li me?
{94554}{94618}Kloo!
{94649}{94721}Mene svi zovu Si.
{94730}{94838}Kaloiro je ime tvog dede,|zato te ja tako zovem.
{95094}{95179}IÊu Êu ako hoÊeö...
{95351}{95418}Ne teram te...
{97407}{97505}Bila je prelepa, fina,
{97567}{97624}ali crna.
{97662}{97761}A ja viöe nisam|bio maza.
{98317}{98427}Ko je prvi?|-"Plava ptica".
{98437}{98522}E, pa, opet je u akciji.|-Ko? -Tvoj prijatelj.
{98531}{98665}Ne zajebavaj. Ponovo je|uzeo sobu 228?
{98724}{98827}Stavi neku svoju|muziku.
{98835}{98897}Nema veze, tata.
{99049}{99095}Vidimo se.
{99689}{99842}Lui! -»eka me baba.|éurim. PriËaÊemo posle.
{99892}{99957}Gde je moja lova?
{100016}{100117}Kad te uhvatim, govno...|-Si, doi!
{100489}{100607}Duguje mi pare.|-äta ga milujeö?
{100615}{100727}NeÊeö ga valjda juriti|po bloku?
{100734}{100811}äta mu rade barabe?|Doi.
{100872}{100932}Sad Êu ja.
{100980}{101029}äta je bilo?
{101031}{101125}VeÊ dve nedelje mi je|duûan 20 dolara
{101132}{101210}i stalno mi izvrdava.
{101230}{101410}Nervira me, öta da mu radim?|-äta sam te uËio?
{101429}{101514}Ne sme niko da te nervira.
{101562}{101657}Je li ti neki prijatelj?|-Nije. Ni ne svia mi se.
{101657}{101785}To je odgovor. Za piöljivih|20 zelenih se secaö.
{101785}{101886}OtkaËi ga. NeÊe te viöe nervirati.|NeÊe viöe traûiti novac.
{101886}{102010}Suviöe je jeftino da bi se|zbog toga nervirao.
{102016}{102199}U pravu si kao i uvek. -Da jesam,|ne bih bio 10 godina u zatvoru.
{102201}{102261}äta si tamo radio?
{102267}{102341}Ima tri moguÊe stvari.
{102347}{102470}Dizanje tegova, karte i upadanje|u nevolje. -äta si ti radio?
{102471}{102527}Ja sam Ëitao.
{102530}{102571}äta?
{102591}{102670}Makijavelija. -äta?
{102677}{102775}Makijaveli.|On je pisao pre 500 godina.
{102781}{102902}Prisutnost. O tome je on|govorio. -Prisutnost?
{102905}{102951}Tako je. Sluöaj me!
{102964}{103130}Ja ovde ûivim, a mogao|bih bilo gde. A zaöto?
{103137}{103267}Da pratim stanje.|Vidim ima li frke.
{103275}{103442}A to je kao rak, ako ga ne vidiö|odmah kad nastane, ubiÊe te.
{103447}{103512}Moraö ga zato odseÊi.
{103520}{103570}Jasno?
{103576}{103685}Koga briga za Luija?|Ni za koga.
{103765}{103871}Ni za tebe, ni za tvoju porodicu,|ni za ljude koji rade za tebe.
{103897}{104040}O tome se radi, o poverenju.|Kad me ljudi ovde vide,
{104047}{104140}znaju da sam prisutan|i oseÊaju se sigurni.
{104146}{104294}Znaju da ih volim. I oni drugi|dobro promisle, jer sam tu.
{104299}{104409}Razlog viöe da me se boje.
{104501}{104610}Je li bolje biti voljen,|ili da te se plaöe?
{104616}{104669}Dobro pitanje.
{104671}{104765}Lepo je oboje, ali|veoma teöko.
{104767}{104901}Da se ja pitam, radije|bih da me se plaöe.
{104910}{105060}Ali strah ne traje dugo.|Prijateljstvo nije niöta.
{105066}{105230}Kad se ja öalim, svi se smeju.|Ja jesam duhovit, ali ne toliko.
{105252}{105387}Strah ih drûi uz mene.|Ne treba biti omraûen.
{105391}{105511}Sa mojim ljudima sam dobar,|ali im ne dajem mnogo,
{105516}{105611}onda im ne bih bio|potreban.
{105667}{105761}Tek koliko da sam im potreban,|a da me ne mrze.
{105784}{105869}Ne zaboravi ovo öto ti|priËam.
{105874}{106032}Sani, danas imam neöto po tvom|ukusu. Lingvini, "Fruta di Mare".
{107346}{107448}Momci, niste propisno obuËeni,|molim napustite lokal.
{107448}{107535}Propisno? -Kaûem da niste|obuËeni kako treba.
{107535}{107627}äta ima? -Zamolio sam|ih da napuste lokal.
{107627}{107720}Ima li problema?|-Problem je öto tvoj Ëovek
{107720}{107832}neÊe da nas sluûi zbog odeÊe.|NeÊemo frku, samo pivo.
{107832}{107917}Dva piva. To je sve.|-To je sve i odlazimo.
{107917}{108013}Zauzmite mesta, gospodo.|Daj im pivo.
{108017}{108077}Zahvaljujemo.
{108256}{108320}Daj neko piÊe! I to hladno!
{108340}{108388}Lepo i hladno!
{108702}{108805}BraÊo, nazdravimo|naöem domaÊinu.
{108822}{108925}U ime Oca i Sina|i Svetoga duha...
{109058}{109136}Vidite öta ste uradili!
{109158}{109207}Opet ti?
{109215}{109295}To nije bilo lepo. Izaite.
{109302}{109363}Jebi se!
{109513}{109581}Pazi mi na motor.
{110040}{110105}Sad nema izlaska.
{110111}{110198}Nikada im neÊu|zaboraviti face.
{110206}{110308}Zinuli su.|ZaprepaöÊeno.
{110316}{110432}Sva snaga i hrabrost|iz tela su im iöÊileli.
{110451}{110547}Bili su poznati|po razbijanju barova.
{110555}{110700}OseÊali su svoju greöku.|Ali, sad su uöli u pogreöan.
{110722}{110803}Napred! Da sredimo jebene|öiljkurane!
{112728}{112813}Bacite ih napolje!
{113153}{113213}Ovo je moj bar!
{113922}{114038}Gledaj me!|Ja sam ti ovo uradio.
{114060}{114115}Zapamti me!
{114185}{114258}Sani, dosta je! Idemo!
{114497}{114567}Neka tako ostanu.
{114758}{114828}Razlaz.
{115232}{115381}Ovo ovde je kalibar 45.|Buöi kamion.
{115472}{115541}Niki je bio lokalni lopov.
{115547}{115647}Majka ga je zvala nula,|jer je dobijao loöe ocene.
{115693}{115827}Lep je. -Tebi Êe se dopasti|ovaj! Treba ti ovakav.
{115867}{115964}äta ti je? -Ne okreÊi ga|ovamo, Niki.
{115966}{116047}Momci, zakoËen je. äta mislite?|Da Êu vas ubiti?
{116047}{116148}Nemoj to nikada da radiö. A sad,|daj da vidim jebeni piötolj.
{116166}{116237}Nov je. Klasa je.|-Ne znam.
{116262}{116332}äta je ovo? Daj da vidim.
{116392}{116517}Lep je. Mogao bi da ubijeö|nekoga. Razumeö?
{116549}{116667}Piötolj je. I ja bih mogao|da ubijem. Ako treba.
{116687}{116761}äta se radi, momci?
{116812}{116869}Jesi li blesav?
{116876}{116996}äta, ovde prodajeö piötolje?|Jesi li normalan?
{117013}{117114}Do nam navuËeö muriju|zbog kradene robe?
{117118}{117179}Teraj se odavde!
{117187}{117251}Stanite! Ne mrdajte!
{117267}{117389}Da vas nisam video|sluËajno s piötoljima!
{117417}{117496}HoÊu s tobom|da priËam.
{117511}{117552}Prii!
{118024}{118191}Jesi li mislio da si frajer?|-Pa ono öto si mi priËao u...
{118198}{118316}Pa öta? Misliö da te to Ëini lafom?|Sluöaj me dobro!
{118323}{118433}Video sam takvih na gomile.|Ako tip ima piötolj,
{118439}{118558}onda se vidi ko je mudo.|-Sani, ne razumeö.
{118563}{118697}Razumem ja sve. To nije za tebe.|Samo Êeö se uvaliti u nevolje.
{118704}{118806}Oni su mi drugovi.|-Oni su drkoöi.
{118812}{118938}Gledaj me!|Zapamti, to su drkoöi!
{118943}{119119}äta ti priËam sve ovo vreme?|-Znam, da idem u ökolu...
{119141}{119334}Tako je. A ne kao ja.|Ovo je moj ûivot, ne tvoj.
{119341}{119453}Ja radim, kako radim,|a to nije za tebe.
{119459}{119524}U redu, izvini.
{119617}{119693}Idemo li sutra na boks?
{119704}{119753}Ne znam.
{119763}{119911}Ima dobra borba u srednjoj.|Poi sa mnom, zabaviÊemo se.
{119918}{120017}Morao bih sa Êaletom. To je|dan kada idemo zajedno.
{120022}{120182}Svrati samo. -Vaûi.|-Ne budi razoËaran.
{120471}{120513}Sedi.
{120572}{120729}Dobra mesta, samo da nas ne|vidi niko. -Ja bolje ne mogu.
{120738}{120816}Ma zezam se, tata.
{121691}{121776}Kako je, Si?|Zdravo, Lorenco.
{121781}{121939}Sani kaûe da siete,|ima par mesta za vas.
{121948}{121997}HoÊete li?
{122062}{122158}Kaûi hvala,|ali ostajemo ovde.
{122263}{122357}Kaûi hvala,|ali ostajemo ovde.
{122364}{122477}U svako doba moûete dole.|Mesta vas Ëekaju.
{122678}{122794}Hteo je da bude ljubazan...|-Ja svoje mesto imam,
{122798}{122891}platio sam ga,|a ti ako hoÊeö, idi.
{122898}{122953}Hajde.
{123164}{123286}Ako misliö da treba da si sa|njima, onda budi sa njima.
{123304}{123402}Ako neÊeö da sediö|ovde, idi.
{123466}{123552}Kako misliö da se|ja oseÊam?
{123733}{123799}Izvini, tata.
{124073}{124145}Govorio sam ti...
{124700}{124804}Kasni veÊ dve nedelje.|Kad ga vidim oleöiÊu ga...
{124848}{124950}Ne dopada ti se?|-Zezaö?
{124977}{125094}Duguje ti 10 dolara. To je|niöta za toliko uzbuenje.
{125232}{125268}Svejedno Êu ga razbiti.
{125268}{125359}Nisam mogao da verujem,|ali to je bila ona.
{125359}{125452}Nisam zaboravio kad sam|je video u busu.
{125452}{125549}Startovao bih je, ali bili smo|sa svojim druötvima.
{126157}{126252}Jebi ga, suviöe mnogo|mora da se radi!
{126853}{126929}Tako ti je to!  -Jebi ga,|stalno se grebeö za dim!
{126945}{127019}Pa öta!|-Nabavio bih jedan bicikl.
{127037}{127122}Ne Ëitam novine,|a treba mi jeftin.
{127189}{127290}äta Êe ti, doavola, bicikl?|-Ne znam. -Hajde, idemo!
{127425}{127474}Ajde, Si...
{127480}{127592}Ne mogu, moram da radim.|Puno sam propustio.
{127697}{127742}Vidimo se.
{128744}{128864}Prvi put smo bili sami i|morao sam da joj priem.
{128869}{128934}NeÊe biti druge öanse.
{128974}{129102}Morao sam biti hladne glave.|Nisam joj znao ni ime.
{129107}{129254}Mislio sam da mora imati neko|fino ime, kao Monik ili Danijela.
{129449}{129563}Ideö u ökolu?|-Ja sam Dûejn.
{129573}{129684}Dûejn? To ti je ime?|-Da, öta fali?
{129692}{129770}Niöta. Svia mi se.
{129778}{129903}VeÊ sam te videla.|-Da, u autobusu.
{129909}{129955}A ti si...?
{129963}{130083}Kaloiro. -Kalu...?|-Kaloiro.
{130105}{130238}Kakvo je to ime?|-Italijansko, sicilijansko.
{130244}{130368}Moja porodica je sa Sicilije.|-Sicilije? -Znaö gde je to?
{130377}{130500}Preko puta mesta gde se Ëizma|zavröava, nalazi se ostrvo.
{130520}{130635}Meni se sviaju Italijani.|-Da?
{130667}{130769}»ekaö nekoga? -Da.
{130837}{130900}Odoh onda.
{130950}{130997}»ekaj!
{131022}{131154}»ekam brata. Nekad se|vraÊamo zajedno.
{131160}{131260}Mogu i ja da te ispratim.|-Dobro.
{131268}{131357}Ja sam niz aveniju,|moûe?
{131379}{131463}Nije daleko, hajdemo.
{131498}{131563}ZnaËi, brata.
{131594}{131670}Super. -äta je tu super?
{131682}{131737}Niöta, tek tako.
{131825}{131914}Odakle ti öeöir?|-Ovaj?
{131919}{131995}Svia ti se? -Smeöan je.
{132004}{132124}Moûda bi mogao drugaËije.|Pridrûi mi ovo.
{132355}{132448}Imaö divne oËi.
{132469}{132515}I ti.
{132678}{132746}Sad je bolje.
{132785}{132920}Da odemo u bioskop?|-Ti sa mnom?
{132948}{133035}Rekla sam ti da volim|Italijane.
{133035}{133141}Sada? -Ne sada, naravno.
{133158}{133308}Moûe sutra?|Da se naemo ovde? U 6?
{133315}{133390}BiÊu ovde do sutra.
{133484}{133614}O, izvini.|Mislim, biÊu sutra.
{133620}{133730}Izvini öto sam glup.|Nervozan sam.
{133743}{133818}Nisi niöta lupao.
{133825}{133909}Dobro ti je iölo.|-Misliö?
{133946}{134101}Odakle si? -Brodvej.|-Gde je to -IstoËni Njujork.
{134111}{134208}Gde je to?|-Daleko odavde.
{134520}{134634}Kako ti je prezime?|-Vilijems.
{134640}{134774}Dûejn Vilijams. Vrlo jednostavno.|Ne znam zaöto, ali jeste.
{134911}{135023}Hajde da vidimo sad! Kaloiro.|Anelo. -Da. -Uspela sam.
{135031}{135195}Zovu  me Si.|-Viöe mi se dopada Kaloiro.
{135299}{135370}Teöke su ti knjige.
{135376}{135455}Zato mi je drago|öto si tu.
{136508}{136566}To je to.
{136578}{136650}Bilo mi je lepo.|-I meni.
{136681}{136783}Mislim da si fin.|-I ti si.
{136795}{136834}Hvala.
{136956}{137044}Mogao bih do kuÊe|da te pratim.
{137044}{137123}Tu sam ja, par blokova.
{137154}{137210}Vidimo se sutra.
{137220}{137271}Sutra, da.
{137280}{137353}Sutra uveËe u 6?
{137359}{137479}Popravljaö se.|-Sigurno je sigurno.
{137504}{137601}Pa, Êao!
{138791}{138856}Beli, nestani!
{139151}{139220}äije, öete...
{139358}{139428}»inkve, sete...
{139435}{139504}Stvar je u jednom prstu.
{139511}{139613}U tome i jeste stvar.|Je l* me pratiö?
{139640}{139750}Ma, o Ëemu priËate?
{139771}{139898}Nisam se ovog puta kladio.
{140048}{140111}äta je ovo, ljudi?
{140169}{140235}Naöta nam liËi kraj?
{140255}{140339}Ostavi ih na miru.
{140343}{140448}äta Êe nam ove Ëamuge?|-Kome oni smetaju?
{140448}{140519}Smetaju meni. -Meni ne.
{140728}{140798}Gubi se odavde!
{140881}{140949}Jebeni crnjo!
{141527}{141584}Si, doi!
{141805}{141864}Drkadûijo crni!
{141882}{141975}Lezi, neÊu da te bijem.
{142311}{142352}Idemo!
{142402}{142475}Klinci, briöite!
{142482}{142531}Murija!
{142537}{142601}Beûite! Beûite!
{142830}{142891}äta ti je? UbiÊeö ga!
{142926}{143011}HoÊu da ih pobijem!
{143446}{143542}Rekao sam ti da samo moûeö|da imaö frku sa njima.
{143542}{143600}Ali, drugovi su mi.
{143616}{143721}Drugovi! Ja sam ti prijatelj,|mali. Da te vidim kad se
{143721}{143857}naeö u sranju. Oni Êe ti|naökoditi. Misli na sebe.
{143911}{144039}Rekao sam ti. Pokuöavam.|Ali ih oni stvarno mrze.
{144049}{144127}Koji ljudi? äta priËaö?
{144136}{144214}Sreo sam jednu curu...-I?
{144239}{144359}Dobra je, ali nije bela...
{144384}{144504}Crna je, zar ne? -Da.|-Dopada ti se?
{144512}{144620}Da, ali ne mogu da sluöam|ove... -Jebeö njih!
{144620}{144710}Njima je ionako mesto|u zatvoru.
{144710}{144845}Nikoga nije briga. Vaûno je kako|je vama zajedno, öta oseÊate.
{144931}{145046}Kada ste sami, noÊu u|krevetu, ispod pokrivaËa,
{145089}{145149}to je najvaûnije.
{145170}{145245}Radi kako ti srce kaûe.
{145252}{145314}Da ti neöto objasnim.
{145320}{145411}Prave ûene su retkost.
{145415}{145520}Nailaze jednom u deset godina.|kao i svi dobri borci.
{145520}{145621}Roki MarÊano, Rej äuger,|Dûoe Luis.
{145630}{145745}Moûe se desiti da imaö tri|prave u isto vreme.
{145746}{145839}Meni se to desilo u öesnaest|godina. Tako je to.
{145862}{145939}Tako to ide, tako je i sada.
{145962}{146095}Vidiö nju? Moûda je ona|ta koja ti je namenjena.
{146170}{146255}Moûda je ona ta koja|Êe te oËarati.
{146256}{146320}Hvala, Sani. PotrudiÊu se.
{146326}{146426}Je li dobra devojka? -Tek sam|je sreo, ali nadam se.
{146432}{146532}Moûeö da uzmeö moja kola,|-Nije potrebno.
{146539}{146711}Uzmi moja kola da ostaviö utisak.|Onda je daj na test.
{146720}{146844}Mariov test? -Ma, ne.|On je lud. äta njega sluöaö?
{146851}{146922}Primeni moj test.
{146922}{147006}Kakav je to test?|-Sluöaj me!
{147012}{147115}Kad naieö kolima do nje,|pre nego öto izaeö iz kola,
{147126}{147244}zakljuËaö oboja vrata.|Izaeö iz kola, odeö do nje.
{147256}{147389}Dovedeö je do kola, izvadiö kljuË,|otkljuËaö vrata, pustiö je u kola.
{147439}{147572}Zatvoriö vrata, obieö kola sa|zadnje strane i prieö svom mestu.
{147732}{147829}Samo to? -Sluöaj, deËko.|Ako to ne uËini,
{147846}{147949}ako te ne pusti unutra,|znaËi da je sebiËna.
{147959}{148055}To je vrh sante leda.|Otresi je se öto pre.
{148064}{148160}A sve ono lepo öto si priËao?|Obostrano razumevanje,
{148187}{148284}otvoreni razgovor, neûnost,|moûe da bude veliËanstveno.
{148290}{148381}To je sranje. Ovaj test sa|vratima je vaûan.
{148382}{148446}äutneö je, i to veoma brzo.
{148446}{148491}äutnem?|-Da.
{148875}{148911}Tata!
{148919}{148976}Da te pitam neöto? -Da?
{149042}{149168}Onaj Dûo, iz susednog bloka me|pita da li da izvodi obojenu ribu.
{149176}{149334}äta da mu kaûem?|-Je l* ne moûe bolju da nae?
{149351}{149437}To nije odgovor.|Gde je problem?
{149443}{149546}Ja se sa svakim lepo slaûem,|ali kad je o tome reË,
{149546}{149647}treba biti sa nekim svoje vrste.|Nemam predrasuda.
{149647}{149788}Kako da ne! äta da ja|imam neku crnu?
{149812}{149876}Ne bi ti to uËinio.
{149883}{150003}Moûda ona bude jedna od|one tri vaûne u ûivotu.
{150042}{150102}Ko ti je to napriËao?
{150110}{150207}Dûoi Oso. -Dûoi Oso?
{150272}{150403}Kaûi ti njemu da strast|ponekad pomuti svest,
{150405}{150513}i da velika glava sluûi da se|dvaput promisli pre delanja.
{150593}{150649}I ti da paziö.
{153361}{153422}Dobro si? -Nisam.
{153422}{153512}Prebili su mi brata|u tvom komöiliku.
{153512}{153567}O Ëemu priËaö?
{153567}{153665}U tvom kraju su juËe|prebili mog brata.
{153668}{153767}äta ja imam s tim?
{153775}{153845}Jesi li i ti bio tamo?
{153850}{153920}Nisam.|-Nemoj da me laûeö.
{153926}{154030}Dûejn, govorim istinu. Nisam bio.|-VideÊemo ko laûe.
{154030}{154138}Brat mi je u kolima, rekla sam|da idem u grad, pa je poöao i on.
{154138}{154253}Poznao te i rekao je da si|ga ti prebio. Ti si to uradio!
{154260}{154353}Nisam ga ni dirnuo,|kunem se.
{154360}{154411}U redu, Ëekaj!
{154413}{154460}Vili!
{154671}{154746}Sad Êemo da razjasnimo.
{154977}{155065}To je on. On je.
{155101}{155193}On mi je to uradio.|-Nisam! -Jesi! -Nisam!
{155201}{155298}Vili, jesi li siguran? -Jesam!|-Molim te, ne veruj mu!
{155298}{155417}U Boga se kunem! -Bio si tamo.|-Da, ali nisam niöta uradio.
{155421}{155525}Veruj mi, Dûejn. -Lagao si,|rekao si da nisi ni bio tamo.
{155528}{155591}Ja sam hteo da|pomognem.
{155600}{155685}Drugi su te tukli,|ja sam te branio!
{155685}{155777}Sereö! -Nisam niöta uradio.|Znaö da su bili drugi!
{155780}{155867}Ti si bio tamo!|-Znaö da su bili drugi!
{155867}{155963}Ja sam ti jedini pomagao.|-Ti si to uradio!
{155970}{156093}Tako mi vraÊaö? -Jebi se, ËoveËe!|-Jebi se ti, niöta nisam uradio!
{156093}{156157}Jebi se, jebeni crnjo!
{156258}{156352}»ula si ga? PriËa kao|i svi ostali.
{158026}{158081}Kako je bilo?
{158083}{158176}KljuËevi su ti u kolima,|ja idem. -»ekaj...
{158217}{158327}Vrati se. äta je bilo?|-Nije iölo. Moram kuÊi.
{158333}{158412}A cura?|-Ispalo je naopako.
{158419}{158532}Pokuöaj da ispriËaö?|-Ne mogu. Moram da idem.
{158567}{158678}Jesi li siguran?|-Sani, moûda drugi put.
{158830}{158862}Idemo!
{158908}{158994}Uzmi moja kola.|-U redu, Sani.
{159763}{159856}äta Êeö u Sanijevim kolima?|-äta priËaö?
{159859}{159967}Znaö ti öta priËam. Video sam|te da voziö njegova kola.
{159973}{160058}To mi se ne dopada.|-Nisam raspoloûen.
{160058}{160153}Baö me briga! Govorim ti|o onim tuËama, o baru!
{160153}{160228}NeÊu da te vidim|u onom baru!
{160228}{160314}Pa da oni pomisle da|nemam hrabrosti.
{160314}{160408}Misliö da je njima stalo?|Zar si ti neöto posebno?
{160408}{160493}Ti ne znaö Sanija.|-Znam öta on misli.
{160493}{160582}UpropastiÊe te kao i druge.|-On mi veruje.
{160582}{160682}On nikom ne veruje!|äto pre to shvatiö, to bolje.
{160687}{160817}Ponavljam ti, njega ne poötuju,|veÊ se boje. To je drugo neöto.
{160817}{160926}Ako hoÊeö da budeö neöto,|brini se za svoju porodicu.
{160926}{160994}To je drugaËiji ûivot.|Sluöaj!
{161004}{161098}Ti si mi jedini sin|i stalo mi je do tebe.
{161098}{161197}Znaj da je na svetu najgore,|kad se talenat protraÊi...
{161197}{161279}To sam veÊ Ëuo.|-I ËuÊeö opet.
{161287}{161397}Ja nemam novca i ne vozim|"kadilak", ali se ponosim
{161401}{161463}onim öto sam stvorio.
{161469}{161574}Moja majka je doöla ovde|bez iËega. -Da, da... -Hej!
{161576}{161679}Da se nisi usudio da ih|omalovaûiö! »ujeö li me?!
{161682}{161797}Ti greöiö! Hteli su da mi|pruûe bolji ûivot i ja tebi...
{161799}{161911}Kakav bolji ûivot? Nemamo|kola, novca, niöta nemamo.
{161928}{162018}Ne pomiöljaj da si neöto,|ako voziö autobus!
{162027}{162084}äljakeri su budale!
{162522}{162621}Si, pogledaj öta su crnje|uradile naöem klubu!
{162637}{162731}Imaju muda, jebene crnËuge!|SrediÊemo ih!
{162737}{162831}Hajde u kola da ih|razbijemo!
{162832}{162914}Ulazi u kola!
{162953}{163006}Sranje!
{163032}{163112}Idemo! Hajde, briöemo!
{163126}{163181}äta ima, Sani?
{163212}{163347}Kad si uzeo kola, gde si iöao?|-Po Dûejn, zar ne znaö?
{163361}{163457}Po Dûejn? Da li? Govori!|-äta ti je, Sani?
{163462}{163552}Kad si ostavio kola, mi smo|pokuöali da startujemo motor.
{163552}{163653}Nije iölo, a kad smo digli|haubu, tamo je neöto stavljeno.
{163653}{163731}Nije se dalo skinuti. Govori!|Kako da raËunam na tebe?
{163737}{163793}Gde si iöao s mojim kolima?
{163793}{163912}Uzeo sam ih i odvezao pred|ökolu, kako si mi rekao.
{163924}{164002}Ne laûi! Gde si vozio|moja kola?
{164009}{164124}Nisam niöta uradio! Kunem se!|Sani, molim te! -Ne laûi me!
{164124}{164257}Nisam niöta uradio! Kunem se!|Samo se odvezao do ökole.
{164292}{164339}Kunem se Bogom.
{164339}{164434}Ne bih niöta protiv tebe!|Ti si mi kao otac!
{164821}{164881}Kaloiro!
{164892}{164951}Hej, Kaloiro!
{164988}{165105}äta je to sa mojim sinom?|-Vozi svoj autobus i idi odavde!
{165113}{165156}RazbiÊu te, piËkice!
{165167}{165269}Ako mi joö jednom prieö,|sabiÊu te u zemlju!
{165332}{165432}Drugi put se najpre|raspitaj.
{165839}{165888}Hej, Si!
{165919}{165968}Doi!
{166203}{166267}äta je to sa Sanijem?
{166292}{166379}Kako je bilo sa ribom?
{166538}{166677}Uspori, neÊu da nas pokupe|pre nego i doemo.
{166684}{166777}Znam zaöto ûurimo.|-Uspori!
{166804}{166882}Znam öta radim.
{166918}{167025}äta to miriöe?|-Koktel za Ëamuge.
{167049}{167115}Super koktel za uûivanciju!
{167177}{167264}Te crnËuge ima da|nauËe svoju lekciju.
{167264}{167350}HoÊe da se izvuku.|E pa, videÊe!
{167350}{167479}SjebaÊemo ih. Ovim.|-Zaöto nisi poneo veÊi?
{167498}{167608}ZaËepi tu jebenu gubicu!|JebaÊu ih, kako ja hoÊu.
{167707}{167764}Baci tu cigaru!
{167807}{167941}Koktel ti je ispod nogu!|-Oladi! Opusti se.
{168017}{168114}Ne mogu da doËekam|da im vidim jebene face!
{168114}{168222}Smeökali su se svi. I ja sam,|ali sam u sebi premirao.
{168257}{168349}éeleo sam da izaem,|ali nisam mogao.
{168362}{168458}äta bih im rekao? Da me|puste jer sam se prepao?
{168458}{168562}Da sam se usr*o? Ne bih mogao|viöe da izaem na ulicu.
{168564}{168657}Rekli bi da sam pizda,|ûutokljunac, seronja.
{168660}{168725}Rekli bi da nemam muda.
{168727}{168817}»uo sam oËeve reËi:|"Ne traÊi vreme, sine.
{168817}{168923}Ovi ljudi Êe te povrediti, sine.|Ne traÊi talenat, sine".
{168943}{169065}»uo sam i glas Sanija:|"Budi paûljiv, Si. Budi hladan.
{169075}{169137}»uvaj glavu, Si".
{169154}{169263}Neka neko povuËe vodu i|odoh ja u kanalizaciju.
{169480}{169573}DoûiveÊe iznenaenje ûivota.
{169687}{169737}Si, napolje!
{169739}{169863}Daj... -Gledaj svoja posla!|Hajde, Si!
{169953}{170005}Izai!
{170125}{170259}Njega da ostavite,|poslednji put vam govorim!
{170967}{171095}Ne mogu da verujem! Posle|svega nemaö poverenja u mene!
{171103}{171194}Nije to u pitanju...|-NeÊu da te sluöam!
{171213}{171300}Nisi verovao Ëak ni|da je to bila Dûejn.
{171300}{171398}Zar misliö da bih rizikovao|da namestim neöto i
{171399}{171492}da Dûejn bude ubijena?|Nisi o tome mislio, zar ne?
{171544}{171609}Nikome ne verujeö?
{171619}{171652}Ne.
{171705}{171774}To je teûak ûivot.
{171788}{171853}Jedini za mene.
{171870}{171947}Za mene nije.
{172487}{172584}Hej, Si! Neka crna devojka|te je upravo traûila.
{172589}{172678}Otiöla je iza Êoöka?|-Pre dva minuta.
{172678}{172752}Ako poûuriö, moûeö je stiÊi.
{172752}{172804}Doi! Doi!
{172879}{173003}Rekao sam, nije to za mene!|-Da ga sredim? -Pusti ga.
{173075}{173109}Dûejn!
{173195}{173233}Zdravo.
{173239}{173352}Brat kaûe da si mu pomogao.|-Rekao sam ti.
{173354}{173509}Znam, ali prvo je pokazao...|-Shvatam tvoja oseÊanja.
{173517}{173605}Drago mi je za to.
{173678}{173779}Gledaj svoja posla,|vrati se u kuÊu!
{173845}{173913}Baö vole da bulje.
{173922}{173957}Hajde!
{173979}{174072}Hajde, daj mi ruku!
{174180}{174295}äto si doöla? -Nedostajao si mi.|-I ti si meni.
{174384}{174489}Mislim da si divna.
{174497}{174529}Nemoj.
{174534}{174584}Ozbiljno mislim.
{174603}{174722}éelim da sam s tobom,|bez obzira öta ko kaûe.
{174738}{174784}Moûe poljubac?
{174812}{174848}Naravno.
{175109}{175169}To nije poljubac.
{175212}{175280}Poljubac je ovo!
{175649}{175730}Umeö li da napraviö sos?
{175738}{175778}äta?
{175785}{175876}Sos za makarone.
{175885}{175952}Ma Êuti...
{176307}{176396}Izvini za ono öto se desilo.
{176408}{176549}Moj brat... -Tvoj brat!|Daj mi kljuËeve! Idemo!
{176553}{176604}äta ti je?
{176608}{176665}Moramo ih stiÊi!
{177046}{177106}Toooo!
{177261}{177326}Ti si jedna od onih velikih!
{177331}{177464}Od velikih? Ne razumem te.|-To je na italijanskom.
{177764}{177836}Poûuri, ovde okreni!
{181139}{181190}Paûljivo, momci.
{181199}{181333}äta se desilo?|-Belci su nam zapalili!
{181613}{181696}Vili, jesi li dobro?|-Da.
{181971}{182083}Sada odliËno izgledaju,|zar ne? Ovako im je bolje?
{182149}{182248}Gubi se odavde, jebeni|kopilanu! Napusti okolinu!
{182256}{182351}JebaÊemo vas u dupe,|piËke jedne!
{182600}{182720}Kad se setim, ne znam da li|da budem sreÊan ili tuûan.
{182726}{182848}Drugovi su mi bili mrtvi.|Ja sam bio ûiv.
{182899}{183024}Znao sam da Saniju|treba da zahvalim.
{183034}{183069}Sani!
{183084}{183208}Dûejn, moram da idem.|Ti si u redu? -Da.
{183214}{183281}Sluöaj, ûao mi je...
{183331}{183446}Moram da idem. Misle da|sam bio u tim kolima.
{183453}{183513}Poludeli su, idi!
{183630}{183671}Idi!
{184632}{184694}Spasio mi je ûivot.
{185070}{185176}Hteo sam da ga vidim|i da mu zahvalim.
{185184}{185245}Spasio mi je ûivot.
{185600}{185715}Kunem se u babu,|vratiÊu ti...
{186200}{186322}Gde je Sani?|-äta me briga, ja gubim!
{186331}{186419}Kakve veze ima moj öef|sa tim?
{186449}{186519}Sani!
{186525}{186602}Si! Doi ovamo!
{186965}{187054}Video sam njegov öirok|osmeh.
{187075}{187186}Meu svim nasmejanim licima|bilo je i jedno drugaËije,
{187207}{187306}Privuklo me je. Ne znam zaöto|sam ga neprekidno gledao.
{187324}{187449}I odjednom sam shvatio.|Na njemu nije bilo osmeha.
{187466}{187566}To niko nije primetio|osim mene.
{187689}{187747}Neeeee!
{187799}{187851}Hajde, Si!
{188666}{188771}Ubio ga je sin Ëoveka,|koga je Sani ubio,
{188771}{188861}pre 8 godina ispred|moje zgrade.
{189991}{190070}Bilo je cveÊa na|sve strane.
{190077}{190194}Italijani su opsednuti cveÊem.|Misle da je onome
{190201}{190280}ko poöalje najveÊi buket,|najviöe i stalo.
{190974}{191067}Bilo je kao öto je i mislio.
{191080}{191140}Nikoga nije briga.
{191165}{191239}Nikoga nije briga.
{191694}{191761}Izvini, sine, zatvaramo.
{191841}{191981}Mogu li joö koji minut?|-U redu, biÊu u kancelariji.
{192614}{192714}Kako je, Sani?|Ne baö najbolje, a?
{192787}{192865}Proöla je test, to da znaö.
{192888}{192970}BiÊe mi prva velika.
{192981}{193074}IzlaziÊu sa njom.|Hvala ti na pomoÊi.
{193136}{193262}Nisam stigao da ti zahvalim|öto si mi spasao ûivot.
{193288}{193438}Oni su izginuli. Slik, Aldo,|Mario, Ralfi. Svi oni.
{193597}{193736}Zahvaljivao sam se.|-U redu je. Razumljivo.
{193867}{193977}Bio je veliki Ëovek.|éivot mi je spasao.
{194122}{194227}Ti si sin Lorenca,|vozaËa busa? -Da.
{194227}{194285}Si, zar ne? -Da.
{194287}{194356}Sani mi je priËao o tebi.
{194363}{194430}Ja ne znam ko ste vi.
{194437}{194610}Ime mi je Karmine.|Sani i ja smo proöli puno.
{194641}{194738}I meni je spasao|ûivot jednom.
{194840}{194903}Ne seÊaö se?
{194952}{195053}Pre mnogo godina.|Ispred tvoje zgrade.
{195083}{195173}SeÊaö se ovoga?
{195180}{195278}Da, bejzbol palica.|Vi ste bili sa palicom?
{195295}{195426}Da, seÊam se. Bio sam tamo.|Sve sam video.
{195432}{195588}Znam öta si ti uËinio.|Sani mi je priËao.
{195596}{195736}Ja Êu ostati u kraju,|da pazim na red.
{195801}{195911}Ako ti neöto treba,|svrati u bar.
{195933}{196032}Malo Êu se odmoriti,|ali hvala.
{196038}{196121}Razumem te.
{196131}{196212}Je li ono bilo zbog|parkiranja?
{196237}{196270}Ne.
{196705}{196812}Ako ti bilo öta zatreba,|potraûi me.
{196821}{196881}Bilo öta. -U redu.
{196893}{196957}Zbogom, momËe.
{197307}{197371}Tata, öta ti radiö ovde?
{197465}{197570}Odajem poötu tvom|prijatelju.
{197607}{197671}Jesi li ti u redu?|-Jesam.
{197677}{197753}éao mi je öto si|povreen.
{197803}{197851}U redu je.
{197867}{197933}BiÊe sve u redu.
{198185}{198311}Sani, hvala ti öto si mom|sinu spasio ûivot.
{198411}{198486}Nisam te mrzeo.
{198510}{198632}Bio sam ljut, jer mi je sin|prebrzo odrastao.
{198748}{198836}Neka se Bog smiluje|tvojoj duöi.
{198982}{199041}»ekaÊu te ovde.
{199176}{199261}Sani, Ëuo si.
{199267}{199350}Moj otac te nije mrzeo.
{199373}{199458}Tu nisi bio u pravu.
{199477}{199540}Pogreöio si.
{199713}{199781}A imao si talenat.
{199925}{199998}Vidimo se, Sani.
{200263}{200335}Hajdemo kuÊi, Si.
{200512}{200655}I Sani i otac su govorili da|Êu razumeti kad odrastem.
{200661}{200723}Tako je i bilo.
{200731}{200800}NauËio sam neöto od njih.
{200807}{200891}Da ljubav dajem|bezuslovno,
{200895}{200983}da prihvatam ljude onakvim|kakvi jesu,
{200995}{201055}a iznad svega,
{201063}{201185}da je najtuûnije na svetu|protraÊiti svoj talenat,
{201190}{201307}i da izbor koji uËiniö|odredi ti ûivot.
{201327}{201442}Pitajte bilo koga u mom|kraju i reÊi Êe vam,
{201456}{201567}"Ovo je samo jedna od|priËa iz Bronksa".
{201592}{203092}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/46n8r|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
