1
00:00:06,000 --> 00:00:12,074
–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org

2
00:00:32,543 --> 00:00:38,509
SKORO BEZGRANICNA, äIROKA I RODNA
SU LOVIäTA MESKALERO APA»A,

3
00:00:38,510 --> 00:00:44,097
KOJIMA JE VELIKI POGLAVICA
WINNETOU BREZPOGOVORNO UPRAVLJAO.

4
00:00:44,098 --> 00:00:49,032
NJEMU JE BILO SUDJENO éIVJETI U VRIJEME,
KOJE JE PROCVAT AMERICKI DRéAVNE BORBE

5
00:00:49,033 --> 00:00:54,541
ZA PRIVABLJANJE OGROMNE KOLI»INE
DOSELJENIKA PREKO VELIKE BARE.

6
00:00:54,542 --> 00:00:59,888
UJEDNO I DONOSENJE
DOSELJENICKIH OBICAJA NA ZAPAD.

7
00:00:59,889 --> 00:01:03,686
KLICAJI VODECIH MUSKARACA
ZA ZIVOT U MIRU,

8
00:01:03,687 --> 00:01:06,941
SU BILI NEUSPJEäNI, RADI
PREBRZIH RAZVOJA DOGADJAJA,

9
00:01:06,942 --> 00:01:11,897
»OVJECIJEG EGOIZMA I IZDAJE.

10
00:01:11,897 --> 00:01:16,117
IZ MJESECA U MJESEC, SMANJIVAO SE 
JE éIVOTNI PROSTOR INDIJANACA.

11
00:01:16,118 --> 00:01:19,305
PRIJETIO  IM JE PRITISAK DO
KONACNOG ISTREBLJENJA.

12
00:01:19,306 --> 00:01:23,192
POGLAVICA WINNETOU JE UVIDJEO
PRIBLIZAVAJUCU NESRECU. NEUMORNO...

13
00:01:23,193 --> 00:01:26,839
JE POKUäAVAO TO ODHRVATI 
OD CRVENIH LJUDI.

14
00:01:44,540 --> 00:01:51,867
Dobro doöli na teritorij Meskalerosa.
Winnetou ce vas otpratit u logor.

15
00:03:54,266 --> 00:03:58,793
Moja crvena braca s Winnetouom gledaju
na veliki teritorij svojih oËeva,

16
00:03:58,794 --> 00:04:05,276
sa bregovima, rijekama i planinama i rodnim 
pasnjacima, preko kojih se sire krda bizona.

17
00:04:05,276 --> 00:04:11,426
Winnetouovo srce je veselo, da je mir zapeËacen
izmedju naöih ljudi i udaljenih mjesta blijedolikih.

18
00:04:11,426 --> 00:04:15,908
Ali ne bez straha, jer nisu
svi ljudi istomisljenici i spremni

19
00:04:15,909 --> 00:04:18,600
pokoriti se pravdi i zakonu.

20
00:04:20,971 --> 00:04:24,037
Krda se ne krecu mirno.
Progonjena su.

21
00:04:56,912 --> 00:04:58,613
Indijanci!

22
00:05:44,553 --> 00:05:46,941
Bljedoliki bi se morali sramiti!

23
00:05:46,941 --> 00:05:50,347
Ne znam, zasto bi se morali sramiti!
Vi ste nas napadli!

24
00:05:50,348 --> 00:05:54,175
Zbog toga, jer ste pucali u bizone
na zemlji naöih oËeva, ali ne jer ste gladni.

25
00:05:54,176 --> 00:05:56,851
Ja se pred vama stidim,
poglavice Winnetou!   -Zacepi gubicu!

26
00:05:56,852 --> 00:05:59,606
Kad sam se pridruzio tim ljudima,
za to nisam znao.

27
00:05:59,607 --> 00:06:02,889
Rekao sam, zacepi gubicu! Skupa
ulovljeni, skupa krivi!

28
00:06:02,890 --> 00:06:07,411
Zahtjevam svoje oruûje i konje i sve ostalo!
E pa, ovdje ce biti tako i tako uskoro drugaËije!

29
00:06:07,412 --> 00:06:09,265
Pazite na svoj jezik!

30
00:06:09,266 --> 00:06:13,541
Ubijali ste bizone, iako niste gladni
i ubili ste tri naöa ratnika!

31
00:06:13,542 --> 00:06:15,612
éeljeli nisu nista drugo,
nego vas upozoriti!

32
00:06:15,613 --> 00:06:18,087
To vi kazete.
Napali su nas iza ledja!

33
00:06:44,998 --> 00:06:49,217
Vratite se, od kuda ste doöli.
Konje cemo vam vratiti.

34
00:06:49,218 --> 00:06:51,881
Takodjer vam vratim samo noz.

35
00:06:54,750 --> 00:06:59,333
Nece vam usfaliti ni dlaka na glavi,
dokle god se nalazite izvan zemlje crvnokosca,

36
00:06:59,334 --> 00:07:03,369
i samo radi sporazuma o miru.
Vaöe oruûje ce Winnetou zadrûati.

37
00:07:03,370 --> 00:07:06,442
Kao dokaz, za optuzbu.

38
00:07:15,950 --> 00:07:20,012
Ja...ja bi rado rekao samo....
-Vi slobodno uzmite vaöu puöku. -Hvala.

39
00:07:25,462 --> 00:07:29,120
To vam nikad necu zaboravit,
poglavice Winnetou.

40
00:07:29,120 --> 00:07:33,521
PriËekajte, mladi prijatelju. Winnetou
vas upozorava, da morate biti obazrivi.

41
00:07:33,522 --> 00:07:38,786
Winnetou vidi kod tih momaka
prezir, bezobzirnost i ubijanje.

42
00:07:38,787 --> 00:07:40,819
Sada idite.

43
00:07:43,857 --> 00:07:45,831
Zahvaljujem vam se!

44
00:09:10,582 --> 00:09:12,967
Brate moj.

45
00:09:26,825 --> 00:09:28,988
Dolazim pravo iz Clintona.

46
00:09:28,989 --> 00:09:33,165
Tamo se skupljaju nepregledne kolone
nadolazecih doseljenika sa zapada.

47
00:09:33,166 --> 00:09:36,577
I tamo su noci glasne ko ovdje dani.

48
00:09:36,578 --> 00:09:42,058
Obuzelo me je sjecanje na prosla vrmena,
Kad je jos ûivio poglavica Inchu-chuna...

49
00:09:42,059 --> 00:09:44,161
I Krasni Dan.

50
00:09:44,162 --> 00:09:50,252
 Winnetou je doöao ovdje, da se prisjeti
ponovo na to, kako je nekad bilo.

51
00:10:00,233 --> 00:10:05,303
Zeli li mi brat nesto otkriti?
-Winnetou se odloËio, da odjase u Santa Fee.

52
00:10:05,304 --> 00:10:06,903
U Santa Fee?

53
00:10:06,904 --> 00:10:12,984
Winnetou su poËeli bljedoliki prijetiti,
da ce uskoro biti sve drugaËije, za ApaËe.

54
00:10:12,985 --> 00:10:18,186
Winnetou se drûi sporazuma o miru.
I uvjeriti se mora da li je....

55
00:10:18,187 --> 00:10:22,988
veliki bijeli otac u Washingtonu zaista
izabrao taj put i hoce li se drûati tog sporazuma.

56
00:10:22,989 --> 00:10:26,798
Da li je moj brat pomislio, da u Santa Feeu
na njega preûaju neznane opasnosti,

57
00:10:26,799 --> 00:10:28,959
koje sa sobom donose nova vremena?

58
00:10:28,960 --> 00:10:34,898
Winnetou je na takve mogucnosti pomislio,
i da ne zatvara oËi pred dolaskom novih vremena,

59
00:10:34,899 --> 00:10:42,176
nego im ide u susret. Prvo ce biti, da
Winnetou posjeti mjesto bljedolikih...

60
00:10:42,177 --> 00:10:46,653
i raduje se, da na njegovoj strani
stoji njegov bijeli brat.

61
00:11:39,900 --> 00:11:42,269
Winnetou ga je upoznao.

62
00:11:43,262 --> 00:11:46,308
Kad je vjerovao u dobro,
a skoro je morao umrijeti.

63
00:12:01,151 --> 00:12:04,545
Sta je to?
- Crkvena zvona.

64
00:12:04,546 --> 00:12:08,485
Sve krcsane poziva na misu u crkvu.

65
00:12:08,486 --> 00:12:14,203
Winnetou zna, da bljedoliki mole,
da njihove duöe dodju u nebo,

66
00:12:14,204 --> 00:12:21,161
tako kao sto mi, crveni ljudi vjerujemo, da ce
naöe duöe otici u vjeËna loviöta k Manitou.

67
00:12:21,162 --> 00:12:26,586
Mozda su rijeci za to drugaËije,
ali je smisao jednak.

68
00:12:26,587 --> 00:12:30,197
Winnetou zadnjih dana pocesto
razmiölja o tim stvarima.

69
00:12:30,198 --> 00:12:35,554
Sada zvono govori Winnetouu
i on razumije njegov glas.

70
00:12:35,555 --> 00:12:37,814
Razumije ga?

71
00:12:37,815 --> 00:12:45,168
Govori: " Voli sve, sta je dobro
i odbaci sve, sta je zlo".

72
00:13:00,293 --> 00:13:06,426
Zahvaljujem vam se, da ste doöli.
Sve sta mogu da uradim za vas, uradit cu.

73
00:13:06,427 --> 00:13:10,318
Vi, poglavice Winnetou, ste Ëovijek,
u kojeg polazem svoje nade.

74
00:13:10,319 --> 00:13:15,578
Ako biste vi.... ali zaista vi, ikada
trebali pomoË, mi cemo je pruziti.

75
00:13:15,579 --> 00:13:20,373
Poslat cu vam vojnika koliko vam 
je potrebno i gdje god  ûelite.

76
00:13:20,374 --> 00:13:23,014
Prijeti zastrasujuËi nered.

77
00:13:23,015 --> 00:13:26,561
Bez prestanka se pomicu doseljenici
preko Santa Feea naprijed prema Clintonu,

78
00:13:26,562 --> 00:13:31,094
gdje se zaustavljaju. Taj ... Bijeli Bizon,
poglavica Sicarijaz indijanaca,

79
00:13:31,095 --> 00:13:34,652
zahtjeva vracanje zemlje,
koju nam je dao na raspolaganje.

80
00:13:34,653 --> 00:13:38,192
Bijeli Bizon, je preko bljedolikih
otkrio vatrenu vodu.

81
00:13:38,193 --> 00:13:42,291
Odkad je postao zarobljenik nje,
tako odlucuje.

82
00:13:42,292 --> 00:13:45,955
I skupina bezskrupuloznih
pojedinaca to izkoriötava.

83
00:13:45,956 --> 00:13:49,561
U Clintonu sam vidio ljude, koji se s njime
udruzuju u skupine, koje ne mogu opstati,

84
00:13:49,562 --> 00:13:52,796
i spremaju na doseljenike. Oduzimaju
im skoraönju dodjeljenu zemlju...

85
00:13:52,797 --> 00:13:56,378
i zahtjevaju veliko placanje danka.
-Ne samo to.

86
00:13:56,379 --> 00:14:00,879
Ne poznajem joö vodje te bande.
Ali znam, da svaki mjesec, jedno bure

87
00:14:00,880 --> 00:14:04,558
konjaka ide u planine k
poglavici Bijelome Bizonu.

88
00:14:04,559 --> 00:14:07,368
Govore, takodjer i o transportu oruûja.

89
00:14:07,369 --> 00:14:11,285
Nadam se samo, da ste vi, poglavice
Winnetou i vi, gospodine Shaterhand

90
00:14:11,286 --> 00:14:14,542
u stanju smiriti tu veoma
nemirnu i opasnu situaciju.

91
00:14:14,543 --> 00:14:18,625
Zato sam se cvrsto odloËio,
da na bilo koji naËin potrazim put, ka....

92
00:14:19,525 --> 00:14:22,420
Pozovi Scota, mora k
Van der Mollenu.

93
00:14:23,472 --> 00:14:29,101
Radi tih spomenutih svadja, bijeli
otac u Washingtonu radi mira je pristao,

94
00:14:29,101 --> 00:14:32,504
da zemljiste Sicarijaz indijanaca
znacajno poveËa.

95
00:14:32,505 --> 00:14:35,701
Winnetou ce odjahti
i prenijet mu poruku.

96
00:14:36,676 --> 00:14:40,621
I neka vam da obecanje, da ce se
od sad pa u buduce drzati nagodbe.

97
00:14:40,622 --> 00:14:43,061
da ce se dioba zemlje
doseljenicima lako obavit.

98
00:14:43,062 --> 00:14:48,658
Sicarijaz indijanci su kradljivci konja. I, kad
se pije vatrena voda, rijeci se lako izgovore.

99
00:14:48,659 --> 00:14:51,484
Dali ce moj brat
pratiti Winnetoua?

100
00:14:51,485 --> 00:14:55,998
Ako ja padnem u opasnost,
hoce li me Winnetou napustiti?

101
00:14:55,999 --> 00:15:00,099
Sada pripremite dokumente, koji su
juce doöli iz Washingtona.

102
00:15:00,100 --> 00:15:03,778
Poglavica Winnetou i Old Shaterhand,
krenite jos danas k Shicarijaz indijancima.

103
00:15:03,779 --> 00:15:05,899
Bit ce ucinjeno, ekselencijo.

104
00:15:05,900 --> 00:15:12,736
Budite oprezni, poglavaice. Mnogo
ljudi ima, samo malo takvih, kao vas dvojica.

105
00:15:12,737 --> 00:15:17,708
Winnetou je veseo, da je upoznao bijeloga
Ëovijeka, koji je takav, kao sto je njegov brat.

106
00:15:17,709 --> 00:15:20,769
NesebiËan i neiskvaren.

107
00:15:22,803 --> 00:15:26,594
Zahtjevam, kako je bilo dogovoreno.
Cjelokupno sve za mene i moje ljude.

108
00:15:26,595 --> 00:15:30,464
Ne dopustam se za par novcica natezat.

109
00:15:30,465 --> 00:15:33,719
Dobit cete to i ni centa vise.

110
00:15:33,720 --> 00:15:36,832
Sta bi jos volio?! Tri crvena
psa smo spremili u stranu.

111
00:15:36,833 --> 00:15:38,741
Trebali bi se jos pustiti zalediti?

112
00:15:38,742 --> 00:15:41,696
Morali bi se pobrinuti za incident,
zbog kojega bi guverner

113
00:15:41,697 --> 00:15:44,294
zahtjevao konjicu vojnika za odmazdu.

114
00:15:44,295 --> 00:15:45,295
Toga poglavicu Winnetoua
bi morali prisiliti na borbu,

115
00:15:47,181 --> 00:15:52,291
da bi lakse njegovu zemlju zaposjeli i prodali
doseljenicima, za ogromne novce.

116
00:15:52,292 --> 00:15:57,263
Da ne spominjem dragu nam naftu, koja se
tamo u zemlji brezkorisno razljeva.

117
00:15:57,264 --> 00:16:00,129
Sta ja mogu kad je to svetinja andjeoska?!

118
00:16:00,130 --> 00:16:04,482
Zahtjevam sav novac!
-Ali mi morate i nesto bolje prodat.

119
00:16:04,483 --> 00:16:09,429
Mozda i imam nesto bolje za prodat.
Nekome, ko bolje placa!

120
00:16:25,437 --> 00:16:30,078
No, molim.
Zasto ne i ionako?

121
00:16:34,699 --> 00:16:39,235
Previse prica. Pobrinite se,
da izgleda ko nesreca.

122
00:16:48,374 --> 00:16:51,567
Winnetou i Old Shaterhand
su za guvernera, gospodine.

123
00:16:51,568 --> 00:16:55,405
Jos nocas idete k poglavici Bijelome Bizonu,
Shicarijaz indijancima zagarantovat vece slobode

124
00:16:55,406 --> 00:16:58,298
i vise zemlje, ako se budu od sad 
pa u buduce drzali mira.

125
00:16:58,299 --> 00:17:01,209
Uvijek me obavjestavajte.
Gomez!

126
00:17:01,210 --> 00:17:05,806
Da, gospodine?!  -Ako se  Winnetouu
posreËi dogovoriti s Bijelim Bizonom,

127
00:17:05,807 --> 00:17:10,547
sve je izgubljeno. Onda necemo dobiti
niti apaöke zemlje niti nafte.

128
00:17:10,548 --> 00:17:13,883
Izgubljen ce biti novac, koji smo
posudili doseljenicima za opremu.

129
00:17:13,884 --> 00:17:17,899
Guvernera je vjerojatno taj
Winnetou veoma obmanuo.

130
00:17:17,900 --> 00:17:23,237
Tako dugo.... dokle ...
-éivi.

131
00:17:23,238 --> 00:17:26,591
Vjerojatno ste
to ûeljeli reËi, hm?

132
00:17:40,068 --> 00:17:44,605
Pri izlazu iz mjesta je nekakav
kamenolom, pored kojeg vodi cesta.

133
00:17:44,606 --> 00:17:46,658
Zaista je. I?

134
00:17:46,659 --> 00:17:51,743
Zar ne bi bilo moguËe, da se tamo
dogodi mala zalosna nesreËa?

135
00:17:51,744 --> 00:17:56,072
Zasto da ne, gospodine? Sve je moguËe.
-Winnetou i Old Shaterhand ce tamo...

136
00:17:56,073 --> 00:18:01,967
nocu jahati mirno. Mozda se mora ujutro
predvidjena eksplozija desiti a ne nocu?

137
00:18:57,361 --> 00:18:59,625
Tamo gore.
Nazad!

138
00:19:44,564 --> 00:19:47,753
Winnetouov konj je
osjetio vatru, koja tece.

139
00:19:47,754 --> 00:19:50,213
Najina zvijaËa se je posreËila.

140
00:19:50,214 --> 00:19:53,191
Winnetou bi morao sam
odjahati kod Shicarijaz indijanca.

141
00:19:53,192 --> 00:19:58,222
Jahac ce otici u Santa Fee.
Old Shaterhand ce slijediti njegove tragove.

142
00:19:58,223 --> 00:20:01,704
Privesce ga Ëovjeku,
kojega je zelio ubiti.

143
00:20:52,859 --> 00:20:56,806
Smijem gospodina upitati, cemu
zahvaliti njegov postovani posjet?

144
00:20:56,807 --> 00:21:01,237
éelio bi se dogovriti s
Ëovjekom, koji je provbitno prosao.

145
00:21:01,952 --> 00:21:08,617
Jeste vi, gospodje moje....ili, moje dame,
vidjele neog da je prosao?

146
00:21:08,618 --> 00:21:12,428
Osim toga gospodina,
koji pita, nikoga.

147
00:21:13,132 --> 00:21:18,370
Sami ste culi.
Vjerojatno ste se zabunili, gospodine moj.

148
00:21:40,747 --> 00:21:43,132
Vas pitam.

149
00:21:44,102 --> 00:21:47,822
Od kuda dolazite?
-No, od kud bi dosao?

150
00:21:47,823 --> 00:21:51,089
Iz kamenoloma, naravno.
Od tamo dolazim i ja.

151
00:21:51,090 --> 00:21:55,648
Od sve te prasine, naûalost niste opazili,
da se sve uleglo medju pukotine 
odmah nakon eksplozije.

152
00:21:55,649 --> 00:21:59,994
I... sta kamenolom ima
raditi s nama?

153
00:21:59,995 --> 00:22:05,165
To cu vam veoma lako odmah objasniti.
Ostat cu tako dugo u Santa Feeu,

154
00:22:05,166 --> 00:22:08,932
dok ne saznam, zasto
vi toga Ëovjeka stitite.

155
00:22:08,933 --> 00:22:12,024
To je vrlo lakomisleno i neoprezno.

156
00:22:12,025 --> 00:22:15,351
Nista neopreznije od toga,
sta se je desilo u kamenolomu.

157
00:22:15,352 --> 00:22:18,755
Trenutno ste dobroga osjecaja.

158
00:22:18,756 --> 00:22:20,154
Zaista dobroga.

159
00:22:31,860 --> 00:22:34,711
Prekleti idiot!
To ste nam vi skuhali!

160
00:22:34,712 --> 00:22:37,684
Obadva ste leûali tamo ko mrtvi.
S njihovim konjima.

161
00:22:37,685 --> 00:22:42,266
I Winnetou je naravno odjahao dalje.
Sada nam samo moze pomoci jedan.

162
00:22:42,267 --> 00:22:46,760
A to je Hollins. Zato mu idite poslati
depesu u Clinton.

163
00:22:51,599 --> 00:22:53,636
ToËno u centar.

164
00:23:20,303 --> 00:23:22,991
Daj!
Zaigraj!

165
00:23:37,095 --> 00:23:40,653
No, djevojko.
Mogu dobiti poljubac?

166
00:23:40,654 --> 00:23:43,448
Zbog mene moze i dva.

167
00:23:47,886 --> 00:23:49,667
Sacekaj,slatkisu.

168
00:23:49,668 --> 00:23:52,473
Pusti me!
-Samo mirno, slatkice, za takav udarac

169
00:23:52,474 --> 00:23:55,186
si mi svakako
duûna dati poljubac.

170
00:23:57,260 --> 00:24:01,409
Sta ûelite vi ovdje, vrtni patuljce?
Zelite po gubici?!

171
00:24:03,670 --> 00:24:06,905
Tako, taj nas vise nece smetat. Daj sad.
-Pustite me!

172
00:24:10,833 --> 00:24:16,284
Sluöajte. To je Rowlingsov namjestenik.
Morate ga se Ëuvati. Dodjite.

173
00:24:16,526 --> 00:24:19,208
No, kako je bebica?!

174
00:24:19,209 --> 00:24:21,889
Dolazi k sebi!

175
00:24:21,890 --> 00:24:25,023
No, konacno!

176
00:24:27,078 --> 00:24:31,205
Ko  je taj tip?!
-Odgegao je napolje na cestu!

177
00:24:44,212 --> 00:24:47,575
Dvije öirine prsta pored!
-Sranje!

178
00:24:47,576 --> 00:24:49,430
Sljedeci!

179
00:24:50,593 --> 00:24:52,336
Za dlan u krug!

180
00:24:56,677 --> 00:25:01,562
Hej! Jel prosao ovdje kakav tip?
Tako mali. Izgleda ko vrtni patuljak.

181
00:25:01,563 --> 00:25:04,022
Hej, Kid! Ko je tebe tako obradio?!

182
00:25:04,023 --> 00:25:07,721
Ko? No, sad upravo toga trazim.
Kad ga dobijem u ruke, ja cu....

183
00:25:07,722 --> 00:25:09,945
Tom patuljku cu zdrobit sve kosti!

184
00:25:09,946 --> 00:25:14,448
To moram vidjeti, ko te tako sredio.
Taj je nasa sorta.

185
00:25:17,378 --> 00:25:21,141
Stari Hawkins ima svoj naËin
za sklapanje poznanstava.

186
00:25:21,142 --> 00:25:23,905
To vam nikad ne bih pripisala

187
00:25:23,906 --> 00:25:28,638
Nista zato. Poznaö ovoga?
Ili njegovog öefa?

188
00:25:28,639 --> 00:25:31,845
Njih se treba pripaziti.
Radje maknite prste od njih.

189
00:25:31,846 --> 00:25:35,655
Stari Sam Hawkins je uvijek gurao
nos u tudje rasprave.

190
00:25:35,656 --> 00:25:41,046
Nikad nisam imao vremena za sebe.
Jedan put samo, ali otisla je s drugim.

191
00:25:41,047 --> 00:25:44,479
Ali, tako je.

192
00:25:44,480 --> 00:25:49,555
Zar nemaö familije? Mislim, tako
mlada ovdje pereö sudje?

193
00:25:49,556 --> 00:25:53,578
Mozes mi slobodno reci.
Mogu ti biti otac.

194
00:25:54,779 --> 00:26:01,585
Dobro. Onda cu vas zvati oËe.
-Ma daj. Mozes mi mirne duöe pocesati bradu.

195
00:26:01,586 --> 00:26:07,000
Tako,kao sto dolici dobroj kcerki.
-Oh, oËe.  -Ah, ovdje je!

196
00:26:10,925 --> 00:26:14,564
Jednog moga momka ste uûalostili, hm?
-Da.

197
00:26:14,565 --> 00:26:17,817
S puökom ste mu odvalili jednu po glavi?
-Da.

198
00:26:17,818 --> 00:26:19,523
Sta bi to bilo po meni, da?

199
00:26:19,524 --> 00:26:22,574
Da.
-Zar ne znate reËi nista drugo sem da?

200
00:26:31,108 --> 00:26:33,045
Znate dobro pucati?

201
00:26:39,180 --> 00:26:40,838
Da.

202
00:26:40,839 --> 00:26:43,519
Onda ste uz mene?
-Da.

203
00:26:43,520 --> 00:26:48,302
Ako pomognete vi, mala ce biti u  
vasem vlasnistvu. Ako pomognem ja...

204
00:26:48,303 --> 00:26:52,536
bit ce u njegovom. Sad,
Idi napolje i ubij se.

205
00:26:52,537 --> 00:26:55,313
Valja?
-Da.

206
00:26:58,505 --> 00:27:01,143
No....onda.

207
00:27:04,686 --> 00:27:08,814
Morat ce stari Sam Hawkins
pomagati, ako se ne varam.

208
00:27:13,250 --> 00:27:15,726
Jeste spremni öefe?
-Da, u redu je.

209
00:27:15,727 --> 00:27:18,979
Svako ima tri strijele.
Hocete vi prvi ili drugi?

210
00:27:18,980 --> 00:27:23,142
Da.  -No, u redu.
Ja cu biti prvi.

211
00:27:23,143 --> 00:27:26,118
Trenutak, öefe! Glasnik je 
upravo dosao iz Clintona!

212
00:27:26,119 --> 00:27:29,063
Sa sobom je dovezao cijeli
arsenal signalnih raketa

213
00:27:29,064 --> 00:27:31,171
i ûeli me za njih obrstiti za Ëetvtinu
dolara po komadu!   -Brown, ne lazi!

214
00:27:31,172 --> 00:27:33,809
-Tu imaö dolar
i nas pusti na miru!

215
00:27:33,810 --> 00:27:35,853
Brzo, nestanite!

216
00:27:39,699 --> 00:27:41,951
Zadatak!

217
00:27:43,483 --> 00:27:45,052
Samo tako naprijed!

218
00:27:49,801 --> 00:27:52,858
Za prst öiroko u kutu!

219
00:27:58,631 --> 00:28:02,908
Jos jedan hitac u srce. Bravo
Rowlings, to niko nece ponoviti!

220
00:28:12,490 --> 00:28:13,918
Neka se priËa.

221
00:28:13,919 --> 00:28:17,061
No, idemo. Zadatak u srce,
zaboravite sve druge zadatke.

222
00:28:17,062 --> 00:28:21,513
Uvijek je tako, da strijela u srce
sve druge strijele ponisti.

223
00:28:32,297 --> 00:28:34,696
Niti u krug nije stigao!

224
00:28:36,133 --> 00:28:37,721
Napunimo si!!

225
00:28:37,722 --> 00:28:41,013
Zatvorite toga tipa.
Sve nas ugroûava.

226
00:28:41,014 --> 00:28:45,415
Samo trenutak! Sta ste radili?
On je obe luknje stavio u sodu?

227
00:28:45,416 --> 00:28:49,148
Da, jedno pokraj druge!
Sve ûganje ce isteci!

228
00:28:52,350 --> 00:28:53,604
Pucajte!

229
00:28:54,936 --> 00:28:58,651
Sada sam razumio svoju puöku.

230
00:29:00,074 --> 00:29:02,440
Pozor!

231
00:29:05,342 --> 00:29:09,094
U sredinu srca.
U sredinu srca!

232
00:29:28,597 --> 00:29:31,784
U zadnjem trenutku se je
puöka okrenula, hm?

233
00:29:31,785 --> 00:29:36,579
Pucanj u srce ponisti sve druge,
ako se ne varam, hm?

234
00:29:37,491 --> 00:29:40,964
Tako,u redu, djevojce je
pod vaöom skrbi.

235
00:29:40,965 --> 00:29:44,444
I, ako ste zato, takvoga kao sto
ste vi, bi u naöim redovima trebali.

236
00:29:44,444 --> 00:29:45,979
äefe!

237
00:29:47,011 --> 00:29:50,003
Obvijestiti vas moram, da morate
odmah doci u telegrafski ured.

238
00:29:50,004 --> 00:29:52,101
Za vas imaju depeöu.

239
00:29:52,629 --> 00:29:56,459
Opet razmisli o mojoj ponudi ,mali moj.

240
00:29:57,760 --> 00:30:00,763
Cini mi se, da ce Sam Hawkins
prihvatit ponudu i

241
00:30:00,764 --> 00:30:05,413
pridruûit im se, ako s ene varam.
Zapamti, kËeri moja, kada...

242
00:30:05,414 --> 00:30:08,570
glupan primi depeöu, iza toga mora
stajati sigurno nekakva gluparija.

243
00:30:12,620 --> 00:30:16,097
I krenuti s  Winnetouom.

244
00:30:18,396 --> 00:30:23,495
Sta si rekao?   -Da je vrtni patuljak
Sam Hawkins, prijatelj Winnetoua.

245
00:30:23,496 --> 00:30:27,367
A tako, prijatelj
Winnetoua?

246
00:30:37,533 --> 00:30:40,426
Recite mi, zasto vucete
vrtnoga patuljka stalno sa sobom?

247
00:30:40,427 --> 00:30:45,456
Radje ga imam pod nadzorom,
nego da nas tajno slijedi.

248
00:30:48,356 --> 00:30:50,007
Kid!

249
00:30:54,938 --> 00:30:57,671
U sluËaju, ako bi nam Winnetou
s crnim vrancem pobjegao, treba...

250
00:30:57,672 --> 00:31:00,193
Ja sam mislio, da ûelite
Ovdje preko namjestiti zamku.

251
00:31:00,194 --> 00:31:04,483
Taj crvenokozac ima pet ûivota, ko maËka.
Za svaki sluËaj budi na oprezu kod medvedjeg jezera.

252
00:31:04,484 --> 00:31:06,047
Hocu.

253
00:31:06,048 --> 00:31:11,735
I najbolje ispod velikoga slapa.
Sad,uzmi ljude i drzite otvorene oËi.

254
00:31:11,736 --> 00:31:14,204
Moze se reci,da je vec pokojni.

255
00:31:14,205 --> 00:31:17,091
Izgledati mora tako,
kao da je bila nesreËa.

256
00:31:21,428 --> 00:31:25,169
Hej, vrtni ökart, ne bi li iöao s
nama k medvedjem jezeru?!

257
00:31:27,598 --> 00:31:30,075
Napred!

258
00:32:04,705 --> 00:32:07,873
Jeste vi to stalno na mjestu?
-Kao sto vidite.

259
00:32:07,874 --> 00:32:10,305
I sada cete govoriti.

260
00:32:15,884 --> 00:32:21,654
Govorite! Ili cu ja to izbiti iz vas.
Iako nerado prljam ruke!

261
00:32:24,947 --> 00:32:28,405
S napadom na nas smo raËunali!
-Sta imate za brijegom?

262
00:32:28,406 --> 00:32:32,284
PoËnite govoriti! Sta ûelite od
Winnetoua i mene?!

263
00:32:33,805 --> 00:32:36,794
Vidjeti ûelim, sta ûelite napraviti
s Winnetouom i sa mnom?

264
00:32:36,795 --> 00:32:44,508
Oruûje je na putu k Bijelomu Bizonu.
Podice se, ratovati i izgubiti zemlju.

265
00:32:44,509 --> 00:32:50,861
éelimo takodjer apaöku zemlju, zbog nafte.
Winnetou svuda pripremaju zamke.

266
00:32:50,862 --> 00:32:56,672
Na cijelom putu do
Shicarijaz indijanaca.

267
00:33:00,410 --> 00:33:02,631
Daleko necete stici.

268
00:33:22,718 --> 00:33:24,433
Ruke u vis!

269
00:33:27,829 --> 00:33:29,698
Okrenite se!

270
00:33:36,644 --> 00:33:38,855
Brzo, prema stijeni!

271
00:34:13,410 --> 00:34:15,579
Hej! Ko je pucao?!
Sta se ovdje dogodilo?!

272
00:34:15,580 --> 00:34:18,170
Nista. Samo smo malo raspravljali!

273
00:34:19,000 --> 00:34:23,273
Stooooj!
Sjasite!

274
00:34:25,767 --> 00:34:28,489
Tako, vrtni ökart, na
ûalost moramo popricati.

275
00:34:28,490 --> 00:34:31,190
Dovoljno ste jahali.
Sad morate ostati ovdje.

276
00:34:39,967 --> 00:34:45,009
Na kakav nacin postupate s Ëovjekom,
koji je upravo postao otac?!

277
00:34:46,867 --> 00:34:50,207
Brzo, napred!
Odjasimo k Bizonovom koljenu!

278
00:35:12,641 --> 00:35:15,747
Brzo, sjaöimo!
Dva neka ostanu kod konja!

279
00:35:34,290 --> 00:35:36,514
Netegnite ûiËani konop!

280
00:35:46,701 --> 00:35:49,242
éicu dobro sakrijte.

281
00:36:00,316 --> 00:36:03,831
Zasto ga jednostavno ne ustrijelimo?
-Jer mora izgledati ko nesreËa, idiote.

282
00:36:03,832 --> 00:36:08,081
Ako budemo imali sreËe, tako ce slomiti vrat,
ako ne, malo cemo mu pomoci u tome.

283
00:36:28,041 --> 00:36:31,023
Tamo iz daljine izgleda,
da neko dolazi.

284
00:36:32,403 --> 00:36:34,568
On je.

285
00:37:25,061 --> 00:37:27,033
Odlozite oruûje!

286
00:37:27,034 --> 00:37:29,255
Odlozite!

287
00:37:30,376 --> 00:37:32,527
Uradite tako, kako vam kazem!

288
00:37:34,560 --> 00:37:36,801
20 koraka nazad!

289
00:37:40,084 --> 00:37:42,364
No, brzo, krenite!

290
00:37:53,949 --> 00:37:57,213
Na konje,  brzo!
Za njim

291
00:38:10,725 --> 00:38:13,016
Stooooj!

292
00:38:13,017 --> 00:38:17,133
Prekletstvo! Na tom satanskom
konju ga nikad necemo dobiti!

293
00:38:17,134 --> 00:38:20,994
Onda, ce ga Kid uloviti
kod medvedjeg jezera.

294
00:38:20,995 --> 00:38:25,599
Mi jasemo napred,
po njegovim tragovima. Idemo!

295
00:38:52,528 --> 00:38:55,697
Sta je sad opet uraditi?
-Ah, lako je vama pricati.

296
00:38:55,698 --> 00:38:59,169
Zar i vi trenutno uûivate
oËinsku radost?

297
00:38:59,170 --> 00:39:01,695
Ako vas gledam kao
izgubljenoga sina, onda da.

298
00:39:01,696 --> 00:39:07,415
Odkud vam ideja, da me oslobodite ?
Ovdje se stvarno lijepo uûiva u ljepoti pokrajine.

299
00:39:07,416 --> 00:39:10,940
Upravo tako sam sve oslikavao.
-Zar je to tu zaista tako, Sam?

300
00:39:10,975 --> 00:39:16,601
Ulovili su Winnetoua, ja sam ga oslobodio,
tako, da je lako pobjegao...

301
00:39:16,602 --> 00:39:22,731
Sam?! -No, da,cuo sam, kako je njegov
konj galopirao ovdje pokraj, zatim banditi,

302
00:39:22,732 --> 00:39:26,531
zatim su ispaljena dva hitca iz njegove
srebrnocjevke, sada su mu za petama...

303
00:39:26,532 --> 00:39:28,377
prema medvedjem jezeru.

304
00:39:57,317 --> 00:39:58,935
Prolaz!

305
00:40:01,214 --> 00:40:02,611
Dolje.

306
00:40:12,065 --> 00:40:15,307
Skupa poËinjemo pucati,
kad bude na sredini slapa.

307
00:40:15,308 --> 00:40:18,605
Reci takodjer ostalima,
da ce vidjeti.

308
00:40:48,187 --> 00:40:51,473
Pazite, da ne pogodite konja.
Njega ûelim ja imati.

309
00:41:01,481 --> 00:41:04,346
Sta se je desilo?
Stvar se je zaostrila, uskoro cemo ga imati.

310
00:41:04,347 --> 00:41:08,207
Tamo je s konj   -Ne pucajte
na konja, on ce biti moj!

311
00:41:16,400 --> 00:41:19,100
Brzo! Za njim, sada je u skarama!
-Za njim!

312
00:41:28,171 --> 00:41:31,954
Prosao je!  -Nestao je!
-Tamo preko moramo!

313
00:42:09,994 --> 00:42:12,911
Mislim, da je to bez svrhe.
Medju hridima ga nikad necemo uhvatit.

314
00:42:12,912 --> 00:42:17,350
Ispod mora izaci napolje.
Krenimo po konje, na jezeru ga imamo.

315
00:42:36,812 --> 00:42:43,184
Tamo ide. Tim, Carter, od mene
dobijete sta poûelite, ako ga uhvatite!

316
00:42:58,756 --> 00:43:00,505
Stoooj!

317
00:43:02,060 --> 00:43:03,239
Brzo!

318
00:43:10,846 --> 00:43:15,453
Tako, sada pripazimo. Ovdje
nam sigurno nece pobjeci.

319
00:43:48,734 --> 00:43:50,941
Pazite!

320
00:43:58,769 --> 00:44:00,685
Hej, ovdje!

321
00:44:02,292 --> 00:44:05,700
Brzo! Pokupite ga napolje.
Podji s momcima na drugu stranu.

322
00:44:05,701 --> 00:44:09,400
Ja cu potraziti ovdje.
-U redu. Brzo decki, za mnom!

323
00:44:19,408 --> 00:44:22,302
Ovdje se ide dolje!

324
00:44:41,337 --> 00:44:45,757
Pretpostavljam, da truplo nece isplivati. 
Izgraditi treba splav i pregledati dno.

325
00:44:45,758 --> 00:44:50,352
Da. Ukoliko ih na onoj strani ne nadju!
Ovdje, idemo, brzo!

326
00:44:59,042 --> 00:45:02,304
Toga nikad ne uhvate.
Neka si ga öef sam ulovi!

327
00:45:11,403 --> 00:45:14,648
Nista se ne vidi.
Podjimo naprijed.

328
00:45:21,580 --> 00:45:24,498
Tipa se nigdje ne moze naci.

329
00:45:24,499 --> 00:45:28,903
Smrkava se. Predlazem, da
ranjenike poöljemo nazad u Clinton.

330
00:45:28,904 --> 00:45:33,159
Mi cemo se tu utaboriti i
ujutro sa splavi pretraziti jezero.

331
00:45:33,697 --> 00:45:37,000
Nesto mi tu nije jasno.

332
00:45:37,001 --> 00:45:41,166
Svakako  moramo preko
noËi postaviti straûe.

333
00:45:42,092 --> 00:45:44,830
Ovdje nesto nije u redu.

334
00:46:29,244 --> 00:46:32,299
Tamo leûi Jeff.
Hej, napadnuti smo!

335
00:46:32,300 --> 00:46:34,572
Momci, dizimo se!
-Sta se dogadja?!

336
00:46:37,889 --> 00:46:42,322
Jasite naprijed, jasite naprijed,
ja namjerno zaostajem, da vam dam

337
00:46:42,323 --> 00:46:45,213
radost, da budete prvi.

338
00:46:48,823 --> 00:46:51,804
To je Winnetouov Ilchi,
ako se ne varam.

339
00:47:03,474 --> 00:47:05,750
Sta se desilo?
-Winnetou me treba Sam.

340
00:47:05,751 --> 00:47:07,852
Brzo moram odjahati za njim.
-Onda idite.

341
00:47:07,853 --> 00:47:10,500
Mene nikad niste za ozbiljno vidjeli
da jasem.

342
00:47:10,501 --> 00:47:13,797
Sam! Odjasite nazad uClinton i
dobro pazite na Van der Mollena!

343
00:47:13,798 --> 00:47:17,557
Na staroga Sam Hawkinsa, jer se olako
u svakoj situaciji opasno zanesete!

344
00:47:17,558 --> 00:47:20,257
Znam to, Sam,
dobro govorite!

345
00:47:20,258 --> 00:47:23,533
Da, stvarno sam dobro 
odgovorio, pocetnice.

346
00:47:34,417 --> 00:47:39,799
Prokletstvo! Daleko nece doci ionako.
Konj je preumoran.

347
00:47:39,799 --> 00:47:42,439
Presjecite mu put. Brzo.

348
00:48:17,858 --> 00:48:19,085
Prokletstvo.

349
00:48:28,233 --> 00:48:31,667
Brzo! Nazad. Desno okolo
mu presjecite put!

350
00:48:45,315 --> 00:48:47,478
Tamo! Tamo gore je!

351
00:48:47,479 --> 00:48:50,318
äest muskaraca neka odjase preko
prolaza na gornji plato!

352
00:48:50,319 --> 00:48:53,508
Brze cete odozgor da ga ulovite. 
Brzo, pozurite!

353
00:48:53,509 --> 00:48:58,681
Drugi se spustite za njim. Stjerajte ga
u procjep, da ne moze vise naprijed!

354
00:49:04,636 --> 00:49:09,696
Oh, ta prokleta crvena bitanga.
Oh njegov noû mi je...oh...

355
00:49:10,641 --> 00:49:13,472
Winnetouov noû.

356
00:49:16,311 --> 00:49:20,487
Taj crvenokozac nema smao 5,
vec 9 zivota. -Da.

357
00:49:20,488 --> 00:49:24,127
Onda, sad mu to nece pomoci.
Vas dvojica odjasite nazad u Clinton,

358
00:49:24,128 --> 00:49:26,718
a ja cu potrazit Bijeloga Bizona.
-Zelim nam uspjeh.

359
00:50:48,355 --> 00:50:51,463
Sad gore, brzo i opkolite ga!

360
00:51:02,366 --> 00:51:04,961
To je bilo u pravi cas.

361
00:51:04,962 --> 00:51:07,051
Shicariaz indijanci.

362
00:51:11,977 --> 00:51:15,484
Crveno pero, zamjenik
Bjeloga Bizona.

363
00:51:15,485 --> 00:51:19,840
Sta zeli poglavica Meskalerosov
u loviötima Shicariaz indijanaca?

364
00:51:19,841 --> 00:51:24,913
Winnetou pozdravlja Crveno Pero.
Dosao je s  bratom Old Shaterhadom,

365
00:51:24,914 --> 00:51:29,211
da u logoru Bjeloga Bizona popusi
lulu savjetovanja.

366
00:51:29,212 --> 00:51:33,436
Crveno Pero je poslusao rijeci Winnetoua.
Njega i bljedolikog vodi sa sobom i

367
00:51:33,437 --> 00:51:36,611
predat ce njihovo oruzje
poglavaru, Bijelomu Bizonu.

368
00:51:36,612 --> 00:51:41,956
Zar Crveno Pero misli stvarno, da ce olako
Old Shaterhandu oduzeti oruûje?

369
00:51:41,957 --> 00:51:45,946
Bljedoliki, koji leûe ovdje, bili su
prijatelji Shicariaz indijanaca.

370
00:51:45,947 --> 00:51:49,156
Crveno Pero ce svoje neprijatelje,
ako je potrebno, prisiliti, da idu za njim

371
00:51:49,157 --> 00:51:53,126
i tako se pokore
zahtjevima Bjeloga Bizona.

372
00:51:55,511 --> 00:51:58,570
Shicariaz indijanci, nasi su,
zapravo, posebni prijatelji!

373
00:51:58,571 --> 00:52:01,446
Oni jako podupiru naöe
doseljenicko udruzenje!

374
00:52:01,447 --> 00:52:04,104
S njihovom pomoËi
cemo dostici naö cilj!

375
00:52:04,105 --> 00:52:07,449
I nije mi previse drago, ako vam kazem,
da moze svaki Ëas doci poruka,

376
00:52:07,450 --> 00:52:12,152
da se dodjeljivanje zemlje doseljenicima
vrlo lako pocne odmah izvrsavati.

377
00:52:14,861 --> 00:52:19,263
I svi, koji se jos nisu upisali,
lako to urade u naoj pisarni

378
00:52:19,264 --> 00:52:23,110
i skolope pogodbu bez placanja.
I onda, kad se gospodin Rowllins,

379
00:52:23,111 --> 00:52:28,354
koji je naö najodgovorniji saucesnik,
vrati od nasih crvenih prijatelja....

380
00:52:28,355 --> 00:52:30,674
Sta se desilo?!

381
00:52:30,675 --> 00:52:35,988
Oooh. Ti vraûiji Shicarijazi. Opominjem vas,
ne vjerujete tim Shicarijazima!

382
00:52:35,989 --> 00:52:38,538
Skalpirali su me na zivo!

383
00:52:38,539 --> 00:52:41,928
Ti crveni vragovi!
-Dolijte joö malo! -Oh, oËe.

384
00:52:41,929 --> 00:52:45,283
Pobrinite se da taj tip nestane.
I to brzo!

385
00:52:45,284 --> 00:52:48,601
Ne vjerujte tim krvolocima
Shicarijazima!

386
00:52:48,602 --> 00:52:50,257
Prolaz!
Dajte prolaza!

387
00:52:50,258 --> 00:52:52,857
Brzo do moga konja.

388
00:53:01,086 --> 00:53:02,493
Nestanite!

389
00:53:02,494 --> 00:53:05,549
Za njim!

390
00:53:14,689 --> 00:53:17,455
To nije prava krv.
To je malinovac!

391
00:53:30,631 --> 00:53:32,715
Brzo, gore u moju sobu, oËe!

392
00:53:45,183 --> 00:53:49,067
Brzo tamo napolje! -Sta ce biti s vama,
kËerkice? -Ah, meni nece napraiti nista. Brzo.

393
00:53:50,770 --> 00:53:54,120
I, Ëiji je  to konj? -Od onoga,
koji je naredio vatromet.

394
00:53:54,121 --> 00:53:57,272
Pozuriti morate.  -U redu, njemu dajte
moga konja. Njegovoga mu vratim...

395
00:53:57,272 --> 00:54:00,187
i njegove sanduke , upravo tako.

396
00:54:49,046 --> 00:54:53,153
éele li poglavica ApaËa
i Old Shaterhand vidjeti,

397
00:54:53,154 --> 00:54:56,676
sta se nalazi u to dva voza?

398
00:55:20,589 --> 00:55:24,391
Shicarijaz indijanci su narod, koji ima
mnogo hrabrih ratnika!

399
00:55:24,392 --> 00:55:28,424
Narod, koji ima oruûje i ratnike,
koji su hrabri, koji se ne trebaju bojati nikoga

400
00:55:28,425 --> 00:55:31,973
i nikome se ne moraju klanjati!
Niti izdajicama ApaËima,

401
00:55:31,974 --> 00:55:37,824
niti grabeûljivim, pljackasima bljedolikima,
koji su doöli krasti naöu zemlju!

402
00:55:37,825 --> 00:55:42,837
Sada imate vas dvojica rijec! Winnetou,
poglavica ApaËa neka govori! Howg!

403
00:55:49,632 --> 00:55:52,830
Apaöi nisu izdajice!

404
00:55:52,831 --> 00:55:56,823
Poglavica Winnetou je doöao
k vama kao prijatelj!

405
00:55:56,824 --> 00:56:03,671
Pogledajte na put sunca!
Svake godine sija na drugi svijet!

406
00:56:03,672 --> 00:56:08,933
Preûivjet ce samo onaj, koji se
ne suprostavlja sudnjem Ëasu!

407
00:56:08,934 --> 00:56:14,150
Bijeli Bizon, sasluöaj sadaj moga
brata, Old Shaterhanda!

408
00:56:14,151 --> 00:56:17,174
Neka govori bljedoliki!

409
00:56:20,633 --> 00:56:25,545
Bijeli otac u Washingtonu je spreman
Shicarijaz indijancima dati viöe zemlje,

410
00:56:25,546 --> 00:56:29,445
jer je uvidjeo, da vam
je dodijelio premalo!

411
00:56:29,446 --> 00:56:32,332
Ako ûeli Bijeli Bizon svu zemlju...

412
00:56:32,333 --> 00:56:36,152
I ûeli se zbog toga boriti, to ce
najaviti kraj za svo pleme!

413
00:56:36,153 --> 00:56:41,755
I novo proljevanje krvi! Znam, da su ratnici
Shicarijaz indijanaca hrabri i neustraöivi,

414
00:56:41,756 --> 00:56:45,990
zato moraju neprestano biti
u pripravnosti, da brane mir

415
00:56:45,991 --> 00:56:51,398
I vi, poglavica Bijeli Bizon, ne nasjedajte
nasmijanim, grabeûljivim, bljedolikim laûljivcima,

416
00:56:51,399 --> 00:56:55,442
koji vas huskaju u tu suludu
i smrtonosnu borbu s tim,

417
00:56:55,443 --> 00:57:00,306
sto vam poöalju
brezvrijedne stare puöke.

418
00:57:13,984 --> 00:57:20,464
Bijeli Bizon cuje u rijecima Winnetoua i
Old Shaterhanda zvuke istinske zabrinutosti.

419
00:57:20,465 --> 00:57:27,558
éeli saËakati s vracanjem sina Brzog Pantera,
koji je nespreman otiöao, da bi donesao rum.

420
00:57:27,559 --> 00:57:30,314
Bijeli Bizon sluti, da mu se bliûi
jesen ûivota...

421
00:57:30,315 --> 00:57:33,336
i ûeli, da se tesko breme
odgovornosti podijeli...

422
00:57:33,336 --> 00:57:37,427
i da se poloûi na ledja mladjih.
I, ako Brzi Panter kaze, da je to,

423
00:57:37,428 --> 00:57:41,914
sto govorite istina, svo
to oruûje ce ostavit za prepad.

424
00:57:49,451 --> 00:57:52,586
Zna li moj brat poglavicina sina?

425
00:57:52,587 --> 00:57:55,338
Brzi Panter je mlad i pun poleta!

426
00:57:55,339 --> 00:57:57,553
I kradljivac konja.

427
00:57:57,554 --> 00:58:00,634
Ali Bijeli Bizon jako voli svoga sina.

428
00:58:36,199 --> 00:58:39,324
Konji!
Neko je ovdje.

429
00:58:45,376 --> 00:58:48,809
Brzi Panter, budite
pozdravljeni od prijatelja.

430
00:58:48,810 --> 00:58:52,754
Zar me ne poznate? Ja sam prijatelj
prijatelja Shicarijaz indijanaca...

431
00:58:52,754 --> 00:58:56,264
i neprijatelj njihovih neprijatelja!
-Brzi Panter zna, vi ste Rowllins.

432
00:58:56,265 --> 00:58:59,376
Prijatelj oca Brzog Pantera!

433
00:58:59,377 --> 00:59:03,615
Vidim, da ste iöli u potragu za rumom
i bili veoma  uspjeöni.

434
00:59:03,616 --> 00:59:07,404
Brzi Panter je ukrao
konje od ApaËa. Pogledajte.

435
00:59:09,320 --> 00:59:12,495
Od ApaËa?

436
00:59:12,496 --> 00:59:15,046
Taj tu je bio od Loto-tchune.

437
00:59:16,425 --> 00:59:20,384
I onaj ondjej, je nekad stajao ispred
öatora Katchum-pattija.

438
00:59:21,599 --> 00:59:25,302
I taj tu je najljepöi.
Dolazi iz Winnetouove zbirke.

439
00:59:25,303 --> 00:59:30,316
Winnetuove zbirke?
Upozoravam vas, Brzi Panter!

440
00:59:30,924 --> 00:59:34,234
Upozoravam vas, Brzi Panter,
da se nikad ne pojavite

441
00:59:34,235 --> 00:59:37,258
u logoru Shicarijaz indijanaca s tim konjime,
jer upravo tamo je odjahao Winnetou

442
00:59:37,258 --> 00:59:39,348
k vaöem ocu, Bijelemu Bizonu!

443
00:59:39,348 --> 00:59:42,505
Winnetou!
-Da, Winnetou.

444
00:59:43,000 --> 00:59:47,588
Od kud bljedoliki to zna?
-Tu, to je Winnetouov noû.

445
00:59:47,589 --> 00:59:50,518
Naöli smo ga, dok smo sljedili
njegove tragove.

446
00:59:50,519 --> 00:59:54,185
Poglavica ApaËev Winnetou,
to ne bi nikad izgubio.  -Ne?

447
00:59:54,186 --> 00:59:56,555
Mislite mozda,
da mu ga je neko oduzeo?

448
00:59:56,556 --> 01:00:03,383
Nije njegov. -Jeste,
dobro ga pogledajte.

449
01:00:09,486 --> 01:00:12,395
Rowllins, jeste li ludi?!
-Zacepi gubicu!

450
01:00:13,683 --> 01:00:20,008
Sad cete cutati, hm?
-Da, vi odluËujete, öefe.

451
01:00:20,009 --> 01:00:24,439
Dignite ga na konja, ali pazite,
da noû ostane u njemu.

452
01:00:46,293 --> 01:00:50,773
Sta razmiölja, brat moj?
-Melodija se cuje preko vode.

453
01:00:50,774 --> 01:00:55,544
Jel moj brat spominje zvona
iz Santa Fee-ja?  -Da.

454
01:00:55,545 --> 01:01:01,593
Winnetou ponovno cuje njihov zvuk.
Pjevaju za njega. Sada je njegovo srce

455
01:01:01,594 --> 01:01:07,432
lagano i puno mira. Kao to jezero.
Ispunjeno je ljubavlju do Manitoua

456
01:01:07,433 --> 01:01:12,057
i Winnetou zna, da njegova
smrt nije vise daleko.

457
01:01:12,058 --> 01:01:18,938
To nije moguËe. Moj brat se zabunio.
Sigurno.

458
01:01:18,939 --> 01:01:24,678
Niko ne moze predvidjeti smrt.
-Winnetou to zna. I Winnetou se ne vara.

459
01:01:24,678 --> 01:01:28,882
Njegova duöa ce uskoro
krenuti u vjeËna loviöta.

460
01:01:28,883 --> 01:01:33,108
Umrijeti moramo jednom svi, da se lakse naöe
duöe na drugom svijetu ponovno sastanu.

461
01:01:33,109 --> 01:01:38,563
Ali taj dan je jos uvijek daleko, nas dvojica
jos imamo sretnih dana pred nama.

462
01:01:40,297 --> 01:01:45,360
Manitou je velik i njegov
ûivot je u njegovim rukama.

463
01:01:47,212 --> 01:01:50,839
Brzi Panter je ubijen.

464
01:01:50,840 --> 01:01:56,311
Sve sam vidio. Jednostavno je dojahao
sa konjima, koje je ukrao ApaËima.

465
01:01:56,312 --> 01:02:01,479
Vidio sa sve. I vidio sam takodjer,
kako ga je jedan ratnik iza ledja napao.

466
01:02:01,480 --> 01:02:07,587
Taj ratnik je bio ApaË, poglavica.
Poglavica Meskalerosa.

467
01:02:07,588 --> 01:02:13,862
Ali Brzi Panter se je hrabro postavio u obranu
i ranio napadaca u Ëelo. Vidite ranu?!

468
01:02:13,863 --> 01:02:17,199
Ali potom se je Brzi Panter
spotaknuo preko korijena...

469
01:02:17,200 --> 01:02:22,768
i onda mu je on, nemoËnom i lezecem,
zabio noû do rucke u srce.

470
01:02:22,769 --> 01:02:26,469
On je ubio vaöega sina.
-To je laû!

471
01:02:27,425 --> 01:02:29,545
Podla laû!

472
01:02:29,546 --> 01:02:32,806
Ja sam bio uhvacen u stupicu, tako,
da nisam mogao napasti,

473
01:02:32,807 --> 01:02:35,810
ali sam poslao svoje momke,
da mu presjeku put.

474
01:02:35,811 --> 01:02:40,189
Na ûalost je pobjegao. Ali
njegov noû je u prsima mrtvoga!

475
01:03:17,420 --> 01:03:21,321
Bijeli Bizon je povjerovao laûljivcu!

476
01:03:43,045 --> 01:03:50,288
Prije nego suce zadje iza vrha hridi,
poûeljet cete, da vas mati nikad nije rodila.

477
01:04:05,124 --> 01:04:10,054
No, gospodo. Nocas, kad bude
sunce za gorama, bit ce Winnetou mrtav.

478
01:04:10,055 --> 01:04:15,060
Oh, oprostite, i vi takodjer, Old Shaterhand.
KonaËno cemo apaöko zemljiste razdjeliti.

479
01:04:15,061 --> 01:04:20,577
Radosna vijest doseljenicima u Clintonu.
Bodite pozdravljeni.

480
01:06:19,286 --> 01:06:22,379
To je bilo u zadnjem
trenutku, ako se ne varam!

481
01:06:29,166 --> 01:06:36,968
I tako, se sada apaöko zemljiste
neupitno,naprosto nudi doseljenicima!

482
01:06:36,969 --> 01:06:41,730
To ne cujemo prvi put!
-Jasno da to ne ide od danas do sutra!

483
01:06:41,731 --> 01:06:45,108
Pripremiti treba pogodbe i pogadjati se
a za sve to treba vremena!

484
01:06:45,109 --> 01:06:48,690
Da, tako je! To treba priznati!

485
01:06:48,691 --> 01:06:53,887
No, dakle! I sada nam je takdjer
taj ûalosni dogadjaj doöao u pomoË!

486
01:06:53,888 --> 01:06:58,539
Jos jednom vam govorim!
Winnetou i Old Shaterhand su mrtvi!

487
01:06:58,540 --> 01:07:03,383
To je laû! Pogledajte sam, ûiv sam,
isto tako je ziv i Winnetou!

488
01:07:03,384 --> 01:07:08,514
Ne vjerujete tom covjeku niti rijeci!
Posluöajte mene, sve cu vam ispricati!

489
01:07:09,168 --> 01:07:12,921
Pazite se Rowllinsa!  -Tko ste vi?
-KËerka Sama Hawkinsa.

490
01:07:12,922 --> 01:07:16,255
Ubijte je!

491
01:07:17,473 --> 01:07:20,744
Brzo poöaljite depeöu guverneru
u Santa fee!  -Telegraf ...

492
01:07:20,745 --> 01:07:24,012
samo u poslovne namjene koristimo!
-Za poslovnu namjenu bandita!

493
01:07:24,013 --> 01:07:27,529
Brzo telegrafirajte ili cu vam
zavrnuti vrat!

494
01:07:27,530 --> 01:07:30,008
Ruke k vis!
-Samo trenutak!

495
01:07:30,008 --> 01:07:34,121
Unistite aparat, tipa ubijte!

496
01:08:23,005 --> 01:08:27,123
I po meni jasite, moje gospodje!
Neprestalno. I koliko je moguce brze.

497
01:08:27,124 --> 01:08:29,294
PoruËnik O¥Hara na mjestu.
-Hvala poruËniËe.

498
01:08:29,295 --> 01:08:32,328
PoruËnik O`Conor s cijelom
satnijom na mjestu.  -Hvala poruËniËe.

499
01:08:32,329 --> 01:08:35,735
Satnik Bred s cjelokupnom
satnijom na mjestu.  -Hvala, satniËe.

500
01:08:35,736 --> 01:08:40,932
U ovom trenutku se mozda odluËuje, kako
i, da li je stvarno moguË zajednicki suûivot...

501
01:08:40,933 --> 01:08:44,565
bijelaca i crvenokozaca. I, dali ce se
konaËno proljevanje krvi zavrs....

502
01:08:44,566 --> 01:08:49,152
Oprostite trenutak, ekselencijo. Samo zato,
jer neko u ime crvenih öalje depeöu?

503
01:08:49,153 --> 01:08:54,729
To nije neki öumski divljak ili neki crvenokoûac!
Ta dva Ëovjeka su zalozili svoje ûivote...

504
01:08:54,730 --> 01:08:59,776
za ËovjeËanstvo i mir! A vi imate
u mislima samo svoje poslove!

505
01:08:59,777 --> 01:09:02,526
Na raËun tisuËa, nista loseg
sluteËih doseljenika.

506
01:09:02,527 --> 01:09:05,646
I na raËun te drûave!
Odvedite ga!

507
01:09:05,647 --> 01:09:12,011
U ovom trenutku se udruûuju Shicarijaz
indijanci i banditi protiv ApaËa!

508
01:09:12,012 --> 01:09:17,158
Ali poslednji se ne budu borili, veË se
budu primirili, da dobiju na vremenu,

509
01:09:17,159 --> 01:09:22,328
u nadi, da dolazite vi s
vojskom i pobrinete se za red!

510
01:09:22,329 --> 01:09:26,950
Za red, zakon i pogodbe! I, da
cete doci, to sam im garantovao

511
01:09:26,951 --> 01:09:29,909
i svoju rijec drûim,
tako mi Bog pomogao!

512
01:09:45,317 --> 01:09:48,036
Dajte da vas privinem na moja
oËinska prsa, stari pocetnice.

513
01:09:48,037 --> 01:09:50,659
Sve ce biti u redu Sam.
Guverner je poslao vonike.

514
01:09:50,659 --> 01:09:52,393
Sada moramo mi odraditi svoje.

515
01:09:52,393 --> 01:09:54,234
Lako vama. Vi morate
samo odvoziti naftu.

516
01:09:54,235 --> 01:09:55,861
Istina ja, s svojim....

517
01:09:55,862 --> 01:09:57,966
Da li je Winnetou najzad 
odjahao u preriju?

518
01:09:57,967 --> 01:10:00,444
Da, jeste, tamo gdje ce se banditi
pridruûiti Shicarijaz indijancima.

519
01:10:00,445 --> 01:10:02,362
No, onda idemo, Sam.

520
01:10:10,893 --> 01:10:13,111
Stooooj!

521
01:10:24,722 --> 01:10:27,213
Pozdravljam svoga hrabroga
prijatelja, Bijeloga Bizona!

522
01:10:27,213 --> 01:10:31,172
Da li su bljedoliko spremni, da uz bok
Shicarijaz indijanaca uniste umoritelje plemena?!

523
01:10:31,173 --> 01:10:36,721
Moji momci su ogorËeni nad
djelom poglavice ApaËa!  -Dobro!

524
01:10:55,210 --> 01:10:57,734
Stooooj!

525
01:11:05,749 --> 01:11:09,051
Ovdje je Winnetou,
poglavica ApaËev!

526
01:11:09,052 --> 01:11:12,186
Poglavica Bijeli Bizon, sluöajte,
sta vam imam za reci!

527
01:11:12,187 --> 01:11:18,376
Zasto grakcu vrane u uöima onome,
koji je doöao ratovati i ubijati?!

528
01:11:18,377 --> 01:11:22,188
OËi Bijeloga Bizona su zamagljene
zbog smrti njegovoga sina!

529
01:11:22,189 --> 01:11:25,140
Neka se usredotoËi na to,
sta je njegova uloga!

530
01:11:25,141 --> 01:11:28,824
Svoje pleme bez strana nek povede
preko praga nadolazeceg vremena!

531
01:11:28,825 --> 01:11:31,261
Nahuskan je od krivih prijatelja!

532
01:11:31,262 --> 01:11:35,378
Bijeli Bizon neka pogleda u nazad na sve,
koji jasu uz njega, kome vjeruje!

533
01:11:35,379 --> 01:11:39,402
Pogledajte sada i uz sebe cete vidjeti
ubojicu vaöega sina!

534
01:12:33,975 --> 01:12:37,020
Nazad uz vas!
Nazad!

535
01:12:52,432 --> 01:12:55,020
Sta sada predlaze bljedoliki?
-Ispricat cu vam!

536
01:12:55,021 --> 01:12:59,336
Obidjite vatru i napadnite apaöki tabor otraga!
Mi cemo napasti s rijeËne strane!

537
01:12:59,337 --> 01:13:02,401
Zatim moraju bljedoliki ici
po rijeci na gore, do tabora!

538
01:13:02,402 --> 01:13:06,398
Napravit cemo splavove i doci
s vama istovremeno do tabora!

539
01:13:06,399 --> 01:13:10,256
Idemo!
Jasite sto brze mozete!

540
01:13:20,980 --> 01:13:24,211
Dolaze. Sami banditi. ToËno
tako, kao sto je rekao Winnetou.

541
01:13:24,212 --> 01:13:28,685
I stari Sam Hawkins se pobrinuo, da ce
upravo lijepo popadat unutra, ako se ne varam.

542
01:13:43,431 --> 01:13:45,533
Prokleti crvenokosci!

543
01:13:45,534 --> 01:13:48,737
Vas trojica se pobrinite za padinu!
Mi cemo odjahati znatno naprijed!

544
01:13:48,738 --> 01:13:51,655
Pazite, kad kaskaju konji!

545
01:13:54,143 --> 01:13:58,320
Tako, to je uspjelo. Sada jasu prema rijeci 
Rio Pecos, gdje ce si sagraditi splavove.

546
01:13:58,320 --> 01:14:02,032
Stari pocetnik ,tamo,ima nesto reci
u vezi s naftom.

547
01:15:15,581 --> 01:15:16,934
Nazad!

548
01:16:03,355 --> 01:16:07,748
I sada, öefe? Sta cemo sada?!
-Naprijed, u tabor!

549
01:16:07,749 --> 01:16:10,514
Da, ali kako?! Zar cemo letjeti?!
-Glupost! Nazad po konje idemo

550
01:16:10,515 --> 01:16:13,193
i odjahat cemo. I,
ako tako ne ide, ici cemo pjeöice!

551
01:16:13,194 --> 01:16:17,488
Napast cemo tabor. Bijeli Bizon sa
zapada, mi sa istoka!

552
01:17:04,582 --> 01:17:06,802
Nista se ne mice.

553
01:17:07,764 --> 01:17:09,863
Idemo!

554
01:17:32,784 --> 01:17:35,956
Stanite! Nazad!
U zaklon!

555
01:18:03,150 --> 01:18:09,201
Vidim, od tamo dolazi naö pocetnik,
zdrav i Ëio, ako se ne varam.

556
01:18:09,202 --> 01:18:12,850
Moje srce je zaista veselo,
jer opet vidi moga brata!

557
01:18:12,851 --> 01:18:15,793
Kad taj vidi svoga brata,
ne pozna nikoga vise.

558
01:18:15,794 --> 01:18:19,212
Kad bude u podne sunce najviöje,
dojurit ce.

559
01:18:19,213 --> 01:18:25,096
Do tad ce ApaËi, s djecom i
ûenama vec doseci gorsko izbjegliste.

560
01:18:28,225 --> 01:18:31,132
Bijeli Bizon mi je otvorio oËi!
Sada isto i ja vidim tragove!

561
01:18:31,133 --> 01:18:35,175
ToËno znam, kamo idu i
od tamo nemaju vise kamo! Naprijed!

562
01:18:46,187 --> 01:18:48,510
Deveti dan je.

563
01:18:48,511 --> 01:18:52,064
Vojska bi morala biti vec jako blizu.

564
01:19:16,329 --> 01:19:19,672
Najbolje ce biti, da ih
priËekamo ispod.  -Da.

565
01:20:03,352 --> 01:20:05,070
Dolaze.

566
01:20:19,171 --> 01:20:23,172
ToËno tako, kao sto sam rekao.
Tamo gore su i nemaju kamo!

567
01:20:23,173 --> 01:20:25,414
Sjaöite!

568
01:20:31,388 --> 01:20:35,910
Ovdje je Old Shaterhand!
-Ne pucajte vise! Tek, kad dam znak.

569
01:20:35,911 --> 01:20:38,945
Pokuöat cu Winnetouu
doci s boka.     -Da, öefe.

570
01:20:38,945 --> 01:20:45,266
Korak za korakom smo se micali, bez bitke! Ne
zbog straha, veË, jr se ne zelimo boriti.

571
01:20:45,267 --> 01:20:49,705
Vjerujemo u to, da su svi ljudi braca i,da se 
moramo pokuöati medjusobno razumjeti,

572
01:20:49,706 --> 01:20:52,518
bez, da se borimo ili ubijamo!.

573
01:20:52,519 --> 01:20:56,768
Tu smo se dobro utvrdili i,
ako napadnete, bit ce to

574
01:20:56,769 --> 01:21:01,610
besmisleno proljevanje krvi!
Poglavica Bijeli Bizon, skinite si

575
01:21:01,611 --> 01:21:05,356
povez sa vaöih oËiju i sagledajte,
zasto ti bljedoliki golaËi...

576
01:21:05,357 --> 01:21:12,879
zele svu zemlju za sebe! éele samo novac i vlast!
I, kad to dobiju,unistit ce i vas!  -Vatra!

577
01:21:39,259 --> 01:21:42,308
Ne vide, da idu toËno
pred puöke banditima.

578
01:21:42,309 --> 01:21:46,860
Pozor! Jasete toËno
pred puöke banditima!

579
01:22:23,492 --> 01:22:27,251
Ne! Nee! Neee!

580
01:23:10,546 --> 01:23:14,190
Metak ne mogu odstraniti.
Pre blizu srcu je.  -I?

581
01:23:14,191 --> 01:23:17,562
To leûi sada u Boûjih rukama.

582
01:25:08,139 --> 01:25:10,522
Brat moj je sada bez brige.

583
01:25:10,523 --> 01:25:14,301
Apaöi su sada zbrinuti i sigurni.

584
01:25:15,246 --> 01:25:21,813
To je... Winnetouova
misija zavrsena.

585
01:26:18,636 --> 01:26:23,788
 Brate moj.
-Brate moj.

586
01:26:23,789 --> 01:26:27,948
  Pomozi mi...
brate moj.

587
01:26:35,164 --> 01:26:40,009
Winnetou...
cuje u daljini...

588
01:26:41,221 --> 01:26:44,277
zvukove zvona, koji ga zovu.

589
01:26:45,576 --> 01:26:48,533
Zar nije tako,
brate moj?

590
01:26:49,677 --> 01:26:51,969
Brate moj.

591
01:26:52,868 --> 01:26:56,004
Winnetouova
duöa mora otici.

592
01:26:58,408 --> 01:27:01,876
Winnetou...
je spreman.

593
01:27:06,030 --> 01:27:07,719
Budi pozdravljen...

594
01:27:08,528 --> 01:27:10,433
moj istinski....

595
01:27:11,197 --> 01:27:15,119
moj...moj...mo...

596
01:28:29,306 --> 01:29:47,283
Prevela sa slo:EMMA40Cro
POZDRAV OD EKIPE CRO RIJEK@ HUBA!

597
01:29:48,305 --> 01:30:48,540
–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/54nrx
–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
