{25}{175}–û–≥–ª–∞—à–∞–≤–∞—ò—Ç–µ —Å–≤–æ—ò –ø—Ä–æ–∏–∑–≤–æ–¥ –∏–ª–∏ –º–∞—Ä–∫—É –∫–æ–¥ –Ω–∞—Å; –∫–æ–Ω—Ç–∞–∫—Ç–∏—Ä–∞—ò—Ç–µ www.OpenSubtitles.org
{980}{1148}D I V LJ A K|[U PAKLU]
{1340}{1402}Da li te je strah?
{1443}{1482}Da li se secaö?
{1589}{1652}Svet je omeköao.
{1810}{1888}Vremenom svaki covek gubi neki dio.
{1923}{1957}Svi se krijemo iza nekih maski.
{2087}{2156}Da li ti uopöte znaö ko si?
{2203}{2244}Verovatno ne.
{3849}{3912}Kravavi zatvor - Zabranjen Ulaz
{3990}{4074}Celicana Broj 8, Magnigorsk
{4658}{4694}Grej, sacekaj.
{4733}{4783}Kajl, uvek ista prica.
{4782}{4824}äta bi trebalo da radim?
{4839}{4880}Imam posao o kojem moram da brinem.
{4884}{4995}Vise te na gledam kao pre,| mislila sam da cemo na plazu zajedno.
{4983}{5054}Grej, jos sest meseci i vracamo se|kuci u Luizijanu.
{5053}{5105}Da dok ne dodje novi posao.
{5111}{5185}Moram ici, vidimo se kasnije.
{5902}{5925}Halo?
{5930}{5948}Hej, duso.
{5956}{5984}∆ao.
{6009}{6031}Jesi li uredu?
{6039}{6060}Uredu sam.
{6073}{6092}Umoran sam.
{6103}{6130}Molim te vozi polako.
{6142}{6195}Ne brini bicu tu za 10 minuta.|Ok?
{6233}{6272}Kajl, bila sam sebicna.
{6294}{6448}Nije lako tebi, bez prijatelja, daleko od kuce...
{6454}{6479}Kajl?
{6542}{6577}Sranje.
{6567}{6596}Mrzim ovo.
{7216}{7269}Bejbi, moja ljubavi,
{7271}{7385}pogodi sto, uzeo sam par dana slobodno,|samo ti i ja,
{7380}{7439}na plazi.|Obecavas?
{7446}{7512}Da, obecavam.
{7566}{7615}Grej, sto se dogadja?
{7685}{7715}Grej?
{8232}{8262}Bjezi.
{8288}{8357}Policija! Da li pricate engleski?
{8362}{8382}Da li me cujete?
{8538}{8572}Moja zena je u opasnosti.
{8649}{8661}Ne razumem.
{9480}{9519}Ne, ne.
{10059}{10079}Grej.
{10356}{10375}Grej.
{12810}{12869}On je, on je!
{13000}{13062}On je, ubio je moju zenu!
{13600}{13730}U nedostku dokaza
{13726}{13798}ne dajemi drugi izbor nego da Mr. Kovic,
{13833}{13894}proglasimo nevinim.
{13983}{14004}äta nije uredu?
{14018}{14188}Oslobodili su ga, odbacili su optuzbu.|Zao mi je.
{14322}{14344}Alo Momak!
{14506}{14624}Zbog oduzimanja zivota coveku,|ispred vrata od ovog suda
{14627}{14709}pokazali ste da nemate poötovanja prema zakonu.
{14721}{14831}Proglasavam vas na dozivotnu robiju|bez mogunosti pomilovanja.
{16459}{16490}Kucke.
{16594}{16630}Stani u liniju!...Nazad.
{16905}{16963}Nasli ste ga?|Da generale Kruscov.
{16972}{17028}Da li je ziv?|Da.
{17030}{17064}Dovedi ga ovamo.
{17295}{17336}Dobrodosli u Kravavi.
{17483}{17509}Cuti!
{17618}{17682}Mozete pokusati da pobegnete ako hocete.
{17696}{17744}Niko jos nije uspio pobeci ziv.
{17965}{17994}Kako se zoves?
{18025}{18043}Bili Kruper.
{18057}{18102}Koliko imas godina?
{18115}{18128}21.
{18151}{18178}Steta.
{18211}{18238}Nastavi.
{19562}{19615}Ne razumem.
{19665}{19693}Ne razumes?
{19721}{19784}Prsten, magarce.
{19907}{19925}To je od moje zene.
{22528}{22559}Kalderdon.
{24037}{24062}äta je?
{24076}{24091}Idemo.
{24099}{24116}De?
{24126}{24176}Drzi usta zacepljena.
{24191}{24251}Idemo, kreci se.
{24475}{24532}Idemo.
{24803}{24902}Andrej, hocu da vidim nesto zelno nocas.
{24897}{24923}Dobices.
{24956}{25049}Andrej, zabavi se.
{25235}{25265}Hajde, covece.
{25334}{25380}Odjebi.
{26436}{26490}Izvini.
{27168}{27187}Ustani.
{27209}{27239}Sad!
{27914}{27965}Kucko!
{28325}{28354}Stani!
{28431}{28469}Ti si covek koji pravi probleme.
{28806}{28861}Budi miran, jasno.
{33523}{33573}Nemoj da ga ubijeö, puöti ga.
{33657}{33744}Znas, neko veruje kad umres,
{33738}{33792}ides u jedan drugi svet.
{33813}{33866}äta bi bilo da sam otisao?
{33885}{33963}Bio bi ovde zauvek.
{34662}{34686}Ucuti.
{34862}{34888}Tiöina!
{36476}{36577}Olaköaj sebi zivot, ili Êeö platiti.|Jasno?
{36769}{36887}451, dovodimo ti novog cimera.
{36929}{36978}Bolje se cuvaj,
{37007}{37072}ubio je poslednja 3 cimera.
{37085}{37157}Ali ako hoces da promenis Êeliju,
{37169}{37202}pozovi me.
{40698}{40759}Kreci, nazad na posao.
{41363}{41417}Vratili smo je u Luizijanu.
{41452}{41493}Znam da Êeö da pitaö.
{41498}{41623}Naöao sam mesto, blizu vode, puno je drveca.
{41608}{41630}Hvala, Bobe.
{41655}{41704}Tvoje sestra treba da pociva u miru.
{41718}{41760}Kako je ovde?
{41800}{41850}Pakao, ovo je Rusija.
{41851}{41881}Mozemo li da ih podplatimo.
{42632}{42669}Jeste li poludeli, zivotinje.
{42669}{42705}Odmakni svoje pizde od mojih ljudi.
{42794}{42819}Odmakni se.
{42946}{42989}Imamo li problema ovde?
{43076}{43179}Ne sada.|Hocete da se borite?
{43184}{43248}Idite u Sparku.|Jasno!
{43691}{43766}Hej, strasljivo druze.
{43787}{43836}Zdravo.|Ja sam Bili.
{43848}{43912}Zaöto si ti unutra?
{43957}{44043}Joö nemogu da shvatim kako, muvao sam se okolo
{44066}{44152}sve je bilo super,|upoznao sam tu devojku,
{44148}{44267}pili smo, a on je imala potjernicu za sobom
{44280}{44486}onda su me optuzili, da sam sa njom u paktu|i dobio sam godinu ipo.
{44578}{44625}Zdravo, kako ide?|Ja sam Malikaj.
{44635}{44665}Kajl.
{44672}{44736}Vidio sam te covece,|u novinama.
{44737}{44800}ubio si coveka ispred vrata od suda.
{44812}{44880}Dobro za tebe, zasluzio je.
{44913}{44991}Covek koji me je gadjao loptom,|ko je on?
{45047}{45096}Andrej.
{45096}{45150}Ruska mafija.
{45155}{45213}Covek pored njega je njihov vodja.
{45218}{45338}Bol, imaju dogovor sa strazarima,|oni vladaju ovim mestom,
{45333}{45403}ostatak bandi se ubijaju izmedju sebe,
{45401}{45438}uobicajena zabava.
{45497}{45550}Celo mesto je jebena ratna zona,
{45559}{45599}i unutra i napolje.
{45611}{45828}Slusaj covece, sve sto ti treba,|ja sam covek, ok.
{45807}{45898}a ovaj ti dajem besplatno.
{45959}{46062} Podmiti strzare i izvadi sebe napolje,
{46054}{46130}iz Êelije onog ludog crncuge,
{46135}{46232}njemu je otisao mozak, ok.
{46926}{46972}Pomoc.
{47150}{47185}O, ne.
{47696}{47723}Da me nisi nikad vise takao.
{47818}{47926}Svet je imao previse buke
{47928}{48048}zasluzio sam malo svog mira, i to postujem.
{48452}{48572}Dobio si samo 18 meseci, i bolje ti je radi sto|ti kazu i briöi odavde.
{48570}{48630}Koliko dugo si ovde?|6 godina.
{48646}{48736}Uteci Êu odavde, i ima da razbijem ovo|mesto, jer ovo mesto je kao sranje.
{48728}{48786}Misli da je opasan momak, on nezna nista
{48790}{48864}on je tako mal. Hoces da preskocis zid,
{48867}{48926}onda uzmi to u svoje ruke.
{48923}{49016}Ti si mi to prodao. Jesam ja|pordajem ta sranja cio moj zivot.
{49010}{49125}Idem, pre nego sto krepam od|ovog sranja.
{49850}{49870}To mi se svidja.
{49924}{49960}Vidimo se nocas.
{50070}{50093}Idemo.
{50480}{50526}äta mislite da zamenim Êelije?
{50634}{50718}Amerika je skupa.
{50786}{50823}Zvao sam za novac.
{50846}{50904}Do tada cekamo.
{51658}{51691}äta je ovo?
{51699}{51795}Ako ima problem, ovo je reöenje.
{51792}{51861}Umesto fudbala, ovde je Sparka.
{51862}{51968}strazari ugovaraju borbe,|a General Kruskov zaradjuje pare,
{51958}{52069}dovodi svoje svinje od prijatelja,|i svi su srecni.
{52066}{52158}Izuzev jadnog smokljana koji izgubi glavu.
{52170}{52246}Hajdemo dosao sam da se kladimo.
{52265}{52322}Ok, kladim se u dva pakla na Andreja.
{52338}{52375}Navali.
{52582}{52652}Dame i gospodo,
{52640}{52740}Desno je onaj koji je uvek zamnom.
{52733}{52798}Levo je onaj koji ja uvek za njim.
{52813}{52875}i uvek sam sanjala da ih imam obadvoje zajedno.
{52872}{53024}I konacno je ostvareno i izazivam ih.
{53123}{53181}Sada Êe mi slomiti srce,
{53184}{53232}sad Êe se poklati,
{53342}{53503}sad je vreme za krv,|momci pokazite mi koliko me volite
{53489}{53558}ajte, jebite se.
{55121}{55147}Hajde, hajde.
{55545}{55573}Isuse.
{55819}{55836}Stani!
{56286}{56337}On se ne bori.
{56353}{56538}Jedini razlog sto je ziv, zato sto je dao|mnogo novca da ga stave u Êeliju.
{56527}{56603}Otarasi se toga, on to nevoli.
{57154}{57182}Dalje od mene.|Baci to.
{57186}{57200}Baci to.
{57345}{57374}Idi.
{57501}{57539}Vodi ga u bolnicu.
{57680}{57760}Hej magarce na putu si mi.
{57755}{57769}Izvini.
{57821}{57865}Stani, stani.
{57961}{58031}äta se desava?|Ne zelim probleme.
{58052}{58099}On nas ne poötuje.
{58112}{58161}Uzmi tvoje poötovanje.
{59087}{59110}Dosta je.
{59308}{59351}Nije potrebno.
{59504}{59557}Nadam se da je sve reöeno.
{59927}{59970}Ovo nije Amerika.
{59974}{60006}Nemoj biti heroj.
{60019}{60075}Vratite ga nazad.|Da.
{60109}{60152}Svi nazad na posao.
{61883}{61979}Dugo se nismo videli.
{62031}{62059}Ko si ti?
{63956}{64026}Gotovo je.|Idemo.
{64739}{64855}Napravicu od tebe moju najomiljeniju ribu.
{64870}{64915}Da, pravicemo rendaljku.
{65137}{65195}Mrtav si.
{65317}{65350}Spreman?
{65539}{65658}Lepo te videti opet.|Jesi li uredu?
{66190}{66223}Hej, vrati se.
{66377}{66447}Idioti. äta?
{66481}{66508}Moramo da idemo.
{66558}{66590}Idemo covece.
{67200}{67287}Mrznja, daje mi snagu.
{67299}{67349}Cak i kada nema nade.
{67393}{67470}Sjutra je dan kada Êu sve ispraviti.
{67495}{67591}Sranje, to mi daje mi ljubav.
{68519}{68569}Drago mi je da te vidim opet.
{68820}{68865}Vidimo se nocas.
{69245}{69303}De koji kurac on ide?
{69443}{69467}äta?
{70344}{70529}Ti Amerikanac, ides unutra na dugo, dugo vremena.
{70595}{70717}Kad sranje udari bol, svi trazimo Boga.
{70706}{70813}Ali do tada, vecinom je kasno.
{71180}{71234}Kada se ne pojavi,
{71250}{71351}na tebi je da nesto ucinis za tvojim bednim zivotom.
{71570}{71592}äta je?
{71607}{71639}Pronaöli smo minu.
{71651}{71677}Odalji se.
{71787}{71816}Zaustavi ono.
{71827}{71898}Bjezi, bezi.
{72306}{72347}Idemo, idemo.
{72356}{72392}Bjeze, beze.
{72430}{72455}U liniju.
{72513}{72547}Pucajte.
{72633}{72711}Covek dolje, covek dolje.|Dovedite pse.
{72928}{73015}Svi imamo neki nas izlaz.
{73011}{73043}Neki odluce da beze.
{73060}{73122}A neki ostanu da se bore.
{74177}{74218}Izgubio sam novac zbog tebe.
{74238}{74272}Dva sata kasnije.
{74663}{74715}Trebao bih da te bacim u rupu.
{74709}{74832}Dajem ti öansu, mnogo si mi|isplativi kao kurva, razumes?
{74870}{74899}Vodite ga.
{75121}{75206}Molim te, molim te, ne.
{75669}{75747}To je znak da smo dohvatili granicu.
{75848}{75918}Kada pravis zadnje korake,
{75965}{76047}kada viöe nemozes da ideö.
{76186}{76278}Nadjes ono tamno mesto duboko u sebi,
{76294}{76353}zaboravis svet odakle si dosao,
{76379}{76466}i uzdises svet u kojem si dosao.
{76805}{76859}Spreman je za Sparku.
{77554}{77649}Hej, volim vas i volim vas sve,
{77642}{77804}drzite se svojih gadja, jer|zabava je spremna da pocne.
{77892}{77947}Dajem ti 30:1 na Andreja.
{77947}{78004}Nema öanse ovaj Amerikanac nemoze|da pobedi.
{79743}{79778}Izbij govna iz njega.
{79979}{80000}Ajde.
{80919}{80947}Ajde, Kajl.
{82118}{82171}Smrt, smrt, smrt.
{83492}{83581}Dobar je osecaj, zar ne?
{84086}{84106}To, Kajl.
{84949}{85012}Tvoj Amerikanac, je vrlo, vrlo dobar.
{85013}{85143}Dovedi najboljeg iz tvog zatvora i dacu|ti priliku da vratis svoje pare.
{86147}{86183}Dokrajci ga, dokrajci.
{86844}{87005}Misliö da si pobedio kada igraö|igru u kojoj gubiö.
{87045}{87097}Izgubio si sebe.
{87231}{87268}Stvarno je sjeban.
{87834}{87883}äta gledas fantome?
{87960}{88007}Da li zaista znas ko si?
{88062}{88104}Verovatno ne.
{88342}{88430}O Hriste, izvini.
{88452}{88493}Mora da je teöko unutra.
{88512}{88553}Sve se poboljöava.
{88567}{88615}Prica sam sa Ambasadorom.
{88622}{88697}Rekao je da Êe da prica sa Premijerom.|Zaboravi. äta?
{88741}{88780}Odustajem.
{88826}{88865}Niöta se nece izmeniti.
{88889}{88927}Zaboravi me.
{89621}{89686}Tamo je gde treba da bude.
{90310}{90349}Da li je vredno.
{90365}{90412}Bolje i to nego da budem kucka.
{90420}{90501}Na dan nezavisnosti poslacu ti razglednicu.
{90864}{90914}Ti si Amerikanac.
{90919}{90970}Ja sam Volija.
{91152}{91303}Volija, naredjenja su da nema|problema danas.
{91470}{91505}Idemo.
{91572}{91670}To je covek sto su ga prebacili,|iz drugog zatvora, da se bori sa tobom.
{91801}{91907}Ruski dan nezavisnosti je proslava|dana oslobadjanja,
{91898}{91979}Sve sama sranja.
{91992}{92064}mi smo kao jedna porodica,|gde dolaze i odlaze
{92065}{92174}to je rehabilitacija samih nas i drustva.
{92794}{92927}Dobrom cemo se okrenuti,|zajedno cemo uzdici se,
{92907}{93012}zajedno cemo poboljöati naöu buducnost.
{93147}{93223}Glas vlasti bi trebao biti glas razuma,
{93225}{93432}primera, da nas nauci, a sto smo naucili|su sranja i da se smirimo.
{93731}{93777}Nema bezanja.
{93839}{93874}Jebem li ti.
{94000}{94061}Zeliö da upropastiö svoje lepo lice,
{94118}{94190}joö imaö malko vremena,
{94186}{94252}sad je sve na meni,
{94256}{94361}tvoje vreme moja mala kurvo.
{94874}{94924}Tvoja plata.
{94936}{94970}Kako je Bili?
{94982}{95087}Polako sa njim, on je samo decak.
{95360}{95505}Malikaj ga je izdao, mora da je i sve ostale.
{95573}{95604}Izlazi.
{95992}{96073}Kad ne osecaö
{96104}{96157}odlaziö u nepovrat,
{96178}{96227}zaboravi öto je bilo,
{96236}{96284}bolje öto je.
{96305}{96431}Ali ne, ne ja,|ja nemogu zaboraviti,
{96422}{96460}Ja nemogu zaboraviti.
{97652}{97691}Izlazi.
{97830}{97866}Odvedite ga u bolnicu.
{98170}{98259}Htio je da me poljubi,
{98259}{98317}ali sam mu pljunuo u lice.
{98413}{98461}Nije me mogao slomiti.
{98518}{98675}Kajl, nedaj da te pretvori u nesto sto nisi
{99267}{99375}Konacno je utekao,|ali na dugi nacin.
{100154}{100219}Dame i gospodo,
{100791}{100824}Digni se.
{101756}{101812}Digni se, bori se.
{102040}{102082}Tulik, öto se dogadja?
{102089}{102167}Neznam gospodine.|Onda saznaj.
{102225}{102288}Bolje se bori ili Êeö platiti mukama.
{102291}{102354}Necu da budem viöe vaöa igra.
{102423}{102519}Nece da se bori viöe.|Makni ga odatle i zapocni neku drugu borbu.
{102509}{102572}Videcu se stobom kasnije.
{103115}{103175}Daj mi do znanja kad si spreman za borbu.
{104398}{104496}Za koga je to?|Za tebe je.
{104556}{104586}Od Bilija.
{105126}{105193}Rekao sam pogledaj me.
{105189}{105227}Moram da izadjem iz ovog mesta.
{105253}{105475}Vezan sam za ovu stolicu ko kraja zivota,|serem, pisam, po sebi, i imam rane svuda,
{105457}{105534}Potrebne su mi specijalne stvari,|rekli su mi,
{105546}{105672}obecali, da ako otvorim oci i uöi,|da Êe voditi racuna o meni..
{105673}{105738}Nisam zelio da ubiju Bilija.
{105756}{105863}Kunem se Bogom,|samo pokuöavam da opstanem.
{106140}{106304}Moram da izadjem iz ovog jebenom mesta,|molim te pomogni mi.
{106604}{106690}Ovde sam pola mog zivota,
{106687}{106738}i pokuöavam da uteknem.
{106750}{106843}Okoliko veliko svetlo je svetlo...
{106885}{107069}Kad si decak neÊeö da verujeö kad ti|odrasli kazu, öto je uredu a öto nije.
{107151}{107172}"Savröenstvo"
{107187}{107377}Laz i beda, sva laz o ljubavi
{107377}{107554}Konacno sam shvatio, da tipicno napredujeö|za samo 1%
{107565}{107638}Sve je to jedna velika sramota,
{107642}{107742}kao öto i moj oziljak ostaje zauvek.
{108260}{108406}Pogledaj Amerikanca, tvrd je.|On je idiot, trebao se boriti.
{108440}{108537}On se bori za samog sebe.
{108773}{108853}äta zeliö?|Mir.
{108850}{108889}Sranje.
{108948}{109008}Dobro pogledaj.
{109059}{109100}On je mrtav covek.
{109115}{109272}On je mrtav, samo ako on hoce.
{109285}{109385}Zajedno mozemo svi pobediti.
{109393}{109461}Zelim borbu, odmah!
{109636}{109759}Viktor.
{109827}{109895}Dovedi mi Valija.
{109912}{110063}To je kao samoubistvo, ostale bande su|se ujedinile nema viöe borbi.
{110163}{110210}Niko nece da se bori.
{110284}{110371}Kad su ljudi ujedinjeni|lako mogu da slome bilo koji sistem,
{110372}{110513}oni su naoruzani sa oruzjem,|mogu svakog da ispraöe.
{111360}{111406}De si bila?
{111418}{111501}Kada si zaboravio sebe,|zaboravio si i mene.
{111581}{111688}Sve is izgubio.|Grej.
{111783}{111931}Po mom miöljenju izvedimo ga i ubijmo.|Ako ga ubijemo pretvaramo se u mrtvacnicu.
{111986}{112111}Moramo da uniötimo miöljenja svih|jednom zauvek.
{112367}{112403}Sacuvaj veru.
{112459}{112595}Bez nje nebismo mogli prepoznati|sto je dobro.
{112848}{112879}Grej.
{112891}{113026}Vratio si se.|Neizgledas mi srecan.
{113005}{113045}Nedostajeö mi.
{113055}{113163}Niko ne odlazi zauvek,|dok se mi secamo njega.
{113862}{113902}Vreme je.
{113996}{114111}U skorije vreme smo imali velikih|problema u Kravovicu
{114109}{114241}vlast je izazvana,|naredjenja nisu ispostovana.
{114234}{114280}To je neoprostivo.
{114287}{114442}Nocas Êu vam pokazati kaznu|za takvu vrstu nepostovanja.
{114582}{114723}Sve öto zelim je da gledam borbu,|i dobicu to.
{114749}{114805}Upoznaj Iloöa.
{117462}{117498}Nastavite borbu.
{117514}{117567}Hej, ubij mene.
{117618}{117679}Necu viöe da se borim.
{118139}{118212}Hajde ucini to, ubij me.
{118660}{118739}Odvali jebena vrata.|Ajde.
{120730}{120769}Maknite te ljude odatle.
{121415}{121521}Niko se ne igra Rumunima.
{121569}{121650}Spasu jedan dan a drugi poseru.
{121651}{121693}Uvek je sranje.
{121717}{121809}Svakoga koga sam ubio ovde,|pricao je mnogo.
{121853}{121902}Ne troöi reci,
{121919}{121974}najbolje je nista ne reci.
{122002}{122047}Evo vidji ucutao sam.
{122171}{122218}Moram izaci odavde.
{122271}{122308}Neko je ubio moju zenu.
{122338}{122434}Postao sam zivotinja,|izgubio sam samog sebe.
{122437}{122557}Izgubio sam i nju,|nezelim da
{122595}{122637}Mogu te izvuci.
{123023}{123166}Ja sam svaki dan, i svaki mesec|koji sam proveo ovde za 27 godina
{123192}{123265}Neko tamo mora ici.
{123286}{123335}I joö jedna stvar.
{123456}{123648}Ako nebudes se borio poveöce te i streljati|to im je plan. Necu da se borim.
{123629}{123733}Zato sam planirao zadnju borbu.
{123978}{124069}Sedam mrtvih i jedan straûar, tu noc.
{124078}{124224}Ali je to bilo prvi put da ja pamtim|da smo se zajedno borili.
{124244}{124351}Bili smo zakljucani dve nedelje.
{124486}{124532}Moram da se borim joö jednom.
{124550}{124601}Da bih nas izbavio odavde, zajedno.
{124663}{124742}Ako se bori viöe nije pretnja.
{124791}{124870}Ako izgubi otarsi ga se.
{127321}{127355}Hej, hej!
{128593}{128630}Srecno.
{128802}{128843}Stavi ga pozadi.
{129685}{129753}Otkljucaj, hajde.
{130152}{130208}Praviö veliku greöku.
{130372}{130419}Izvini zbog greöke.
{130681}{130722}Dodjavola.
{130805}{130835}Ovo je teûi dio.
{130859}{130937}Vozi kroz kapiju i|niko te nece zaustaviti.
{131025}{131115}Ideö samnom.|Ne, ovo je moj dom.
{131120}{131177}Ti imaö svoju ulogu,|ja moju.
{131359}{131417}Neka ljudi znaju.
{131483}{131537}Hajde, idi.
{132291}{132366}SledeÊi put povraticu svoj novac.
{132369}{132417}Kao öto si i pre.
{132761}{132832}Znaö...|Ti nebi smio biti ovde.
{132999}{133075}Izadji.|Znaö mnogo pricaö.
{133074}{133141}Ne, ne, neeee...
{134056}{134137}Uspio sam...zajedno.
{134195}{134334}Mnogi od nas znaju da maska iza koje su|da je obicno sranje.
{134327}{134476}Pre ili kasnije, skinuÊe se,|tada cete saznati,
{134464}{134525}ko ste vi ustvari.
{134811}{134896}Tri meseca kasnije,|Zatvor Kravavi je zatvoren.
{134941}{135141}Prevod: Mnemoric feat. N4zGuL / Montenegro
{135166}{136666}–ú–æ–ª–∏–º–æ –≤–∞—Å –¥–∞ –æ—Ü–µ–Ω–∏—Ç–µ –æ–≤–∞—ò —Ç–∏—Ç–ª –Ω–∞ www.osdb.link/3ek3f|–ü–æ–º–æ–∑–∏—Ç–µ –¥—Ä—É–≥–∏–º –∫–æ—Ä–∏—Å–Ω–∏—Ü–∏–º–∞ –¥–∞ –∏–∑–∞–±–µ—Ä—É –Ω–∞—ò–±–æ—ô–µ —Ç–∏—Ç–ª–æ–≤–µ
